### ISSUE TITLE
FTP_Storage plugin problem

### ISSUE THREAD

**Issue by tgd1973** [WWBN/AVideo#1352]
I just bought the plugin "FTP_Storage" from your store, and I have trouble getting it working ... 
The Streamer log is like this:
` ....  `
`[01-Jan-2019 20:16:59 UTC] Encoder receiving post`
`[01-Jan-2019 20:17:00 UTC] PHP Fatal error:  Uncaught FtpClient\FtpException: Unable to connect in` `/home/abc/web/def.eu/public_html/plugin/FTP_Storage/FtpClient/FtpClient.php(14) : eval()'d` `code(1) : eval()'d code:159`
` trace:`
`#0 /home/abc/web/def.eu/public_html/plugin/FTP_Storage/FTP_Storage.php(14) : eval()'d` `code(1) : eval()'d code(41): FtpClient\FtpClient->connect('192.168.xx.xx', false, '221', 2)`   --> in my case FTP server from NAS, works on a different port.
`#1 /home/abc/web/def.eu/public_html/plugin/FTP_Storage/FTP_Storage.php(14) : eval()'d` `code(1) : eval()'d code(123): FTP_Storage->getClient()`
`#2 /home/abc/web/def.eu/public_html/plugin/FTP_Storage/FTP_Storage.php(14) : eval()'d` `code(1) : eval()'d code(115): FTP_Storage->copy_to('/home/abc/tm...', '_YPTuniqid_5c2b...')`
`#3 /home/abc/web/def.eu/public_html/objects/functions.php(911): FTP_Storage-``>move_uploaded_file('/home/abc/tm...', '_YPTuniqid_5c2b...')`
`#4 /home/abc/web/def.eu/public_html/objects/youPHPTubeEncoder.json.php(88):` `('/home/abc/tm...', '_YPTuniqid_5c2b...')`
`#5 {main}`
`in /home/abc/web/def.eu/public_html/plugin/FTP_Storage/FtpClient/FtpClient.php(14) : eval()'d` `code(1) : eval()'d code on line 159`

It is in a shared server with other domains because i need to use as much as possible the public IP that I have, on an FTTH, (all mine), that I have installed on Debian 9.
I tried to log in a FTP server with an  another client FTP from windows pc, with the same credentials, and login is done without problems ...
The FTP Server is on a FreeNAS on which I have activated among other things that I need for other purposes, and  also a WebDAV service with which I managed to exit for the endpoint of this plug FTP_Storage ... in the Streamer.

I did some tests on your demo.youphptube.com  server before buying the Plugin and it seemed that everything worked fine (apart from the fact that with the WebDAV service i can not hide from the navigation of the index directory where the files that are moved to the NAS server are stored that must memorize them.

Since the plugin is encrypted I can not see or analyze anything else ...  Please if you can give me some lightening for how to test the problems that I have, on my server with your plugin?

Thank you.

**Comment by DanielnetoDotCom** [comment]
Hi

Did you try check/uncheck the ssl and passive mode?

**Comment by tgd1973** [comment]
Hi again ... yes but the problem persists ... the streamer with the FTP plug ... can not upload to NAS ...

**Comment by tgd1973** [comment]
is there any particular dependency to install for ProFTPD in debian 9? ... to make it work your plug script? The web server has its own ProFTPD server - (VestaCp) maybe it has some interference ... and that's why I changed the port from 21 to 221 ...

**Comment by DanielnetoDotCom** [comment]
if you look into your videos directory there are some dummy files with the file size of 10 bytes.

the dummy file has the same name as the main file on the FTP.

we distinguish the proper file by the file size

**Comment by tgd1973** [comment]
Difficult mission to write dummy ... for 300 files, and all of them ...
In fact it seemed to me a small can those files that I noticed only a 10bit ... but I did not have the curiosity to open them in an editor ... I thought they were corrupt.
Many thanks.
