### ISSUE TITLE
Missing rules in router.php

### ISSUE THREAD

**Issue by patriclougheed** [WWBN/AVideo#1463]
I tried moving to the router and removed the rewrite rules from my .htaccess/Nginx config and found a couple things missing from the router.php.

Tags and Trending not working so added:

`SimpleRouter::get($basePath."trending", function() {
    require_once "view/trending.php"; exit;
});
SimpleRouter::get($basePath."tag", function() {
    require_once "view/?tags_id=$1"; exit;
});`

Then I found embeds not working and noticed there are no vEmbed or videoEmbed in the router. The videosList has issues as the /videosList/video/ rewrite is not present. I have just re added these to the server config as a quick fix until I can figure out the router entries.

**Comment by JoshWho** [comment]
Very good find. I noticed the same thing with the Trending tab but I was just thinking it might be the server I was using. I am about to buy the Install/VPS package in a few days so I will let u know if that is what was causing it on my end.

**Comment by gregorymcewanmarriot** [comment]
cant get this to work - added the above to router file and also tried adding below to htaccess

`RewriteRule    ^view/?tags_id=$1 [NC,L]`

just get 

Not Found
The requested URL /tag/7/United+Kingdom was not found on this server.
