### ISSUE TITLE
Videotags don't show correct pages

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#1530]
Hi Daniel

Videotags  show only the first page correct and the next pages are random.
I have 30 videos on one page. This sample must have 5 pages (5x30=150) to show 139 videos

![_snap1](https://user-images.githubusercontent.com/39981177/53398821-de669880-39aa-11e9-92ed-a7e380e961cd.jpg)
![_snap2](https://user-images.githubusercontent.com/39981177/53398836-e7576a00-39aa-11e9-9dcb-e8ba99a7fd52.jpg)
136 Videos = 139 videos

**Comment by DanielnetoDotCom** [comment]
humm, I see

I could not reproduce it on the demo site.

maybe you have some extra configuration on your videos, like non public videos

**Comment by TLCReuver** [comment]
Tagging appr 400 videos and it works perfect.

Tested to set all videos to public (`videos_group_view`) but have the same result

![snap1](https://user-images.githubusercontent.com/39981177/53548527-f3216880-3b31-11e9-942b-535a965d4f31.jpg)

The output you can find on http://media.beesel-reuver.nl/tag/1/112

**Comment by DanielnetoDotCom** [comment]
Hi, I send some changes that may fix it, can you please check it?

**Comment by TLCReuver** [comment]
Updated VideoTags.php but still see only one page of the selected tags.

**Comment by TLCReuver** [comment]
Hi Daniel,
Today i looked what is going wrong....

When i click on next page (2) from http://media.beesel-reuver.nl/tag/1/112
it load root page 2 http://media.beesel-reuver.nl/page/2
It has to be http://media.beesel-reuver.nl/tag/1/112/page/2
or something like that.

The script to do that seem to be missing.
