### ISSUE TITLE
Import question

### ISSUE THREAD

**Issue by Code-Slave** [WWBN/AVideo#1551]
I have a very large collection of channels downloaded into a directory structure like so

/ytvids/woodworking/channel1
/ytvids/woodworking/channel2
/ytvids/cars/channel3

Is there a way to import into the app so that the group (woodworking) and channel name (channel1) are preserved?

**Comment by Criptos** [comment]
There is no direct way. 
The encoder can upload to the streamer from a directory, but you can only set the default category. 
Groups create a relation of users. 
Channel is a property of users. 
Category is a porperty of videos. 
You cant have multiple channels per 1 user. 
You would need a structure <user>/<channel> and asociate the videos by category. 
channel 1 would beloong to user channel 1 and all videos inside directory woodworking/channel1 would be set to the category woorworking. 
So you can view woodworking from channel 1 or channel 1  or woodworking from  channel 1 AND channel2 depending on the view, if per user, or per category.
