### ISSUE TITLE
Live stream questions

### ISSUE THREAD

**Issue by kevev** [WWBN/AVideo#1554]
Thank You for this awesome app!

1.) Can this be expanded to allow allow server clustering like the way nginx can do when serving up HLS chunks for thousands of viewers?

2.) What is the limit on concurrent live streams?

3.) Does the live stream support transcoding to multi-bitrate hls streams?

4.) Does the player support live streams with multi-bitrate scaling depending on available bandwidth?

**Comment by DanielnetoDotCom** [comment]
1. we do not have nothing designed on that way
2. the limit is your hardware, we do not limit anything
3. the default configuration has only one bitrate, but you can try to change it for multiple bitrates
4. yes

**Comment by GillyMoMo** [comment]
If the backend is nginx. Then yes you can use a VBR stream. You may have to edit the nginx.conf file in order to do so. 

Another option is to offload your encoder on a rig that is designed to take such a beating. If this is for many viewing you may also consider a cache server to help.

**Comment by kevev** [comment]
Thank You both for the reply. I am thinking of putting YouPHPTube behind CDN pull zone. Would that work for allowing increased viewers?

**Comment by kevev** [comment]
Actually that should work as nginx is creating standard stream.m3u8 & *n.ts files.

The video player does not seem to support multi-bitrate. Is this feature planned?

**Comment by raffeal** [comment]
LIVE STREAMING NOT WORKING
![ERROR](https://user-images.githubusercontent.com/47043451/54799469-37aaaa80-4c7f-11e9-8d39-a5d240f84eaa.png)

**Comment by DanielnetoDotCom** [comment]
@raffeal check this https://github.com/DanielnetoDotCom/YouPHPTube/issues/1566
