### ISSUE TITLE
Subscribers and Suggestions

### ISSUE THREAD

**Issue by scifiantasy** [WWBN/AVideo#1560]
Hey Guys, 

First off I just wanted to say you have an awesome product here and I actually made the switch from playtube to youphptube because of the quality.  Support has been great here and I appreciate that because I am not a coder and sometimes difficult for me to get things done. 

The only issue I have come across so far is when you click the subscribers so you can email them an error comes up. I attached a photo of the error. Even though the error message pops up the message still makes it through which is a good thing.

![error code](https://user-images.githubusercontent.com/43969902/54088561-b9244380-4335-11e9-812c-ca4316057ec5.png)

Now onto a couple of suggestions which probably have been talked about but there are a lot of threads to go through.

1. Have another notification Icon in the top menu for comments on videos or subscriptions that have uploaded new content. This will make it easier to find out what is going on, on the sites we run. And, will be useful for the users as they do not have to go searching around.

2. Video descriptions get to be very long sometimes and stretch the page out. I read more button would be great and add to the cleanliness of the page.

3. Video tags shown under the subscribe button take away from the cleanliness of the site too. Maybe a button that shows the tags or just keep the tags hidden like on youtube and are used just for searching. Again making the video page cleaner.

4. The comment box at 200 characters is very short. I probably can add to that I just have to figure out how to raise the limit on that. 

Thank you again for your time and effort and putting together YouPhpTube. I love it and it is an awesome product!!

**Comment by Criptos** [comment]
You are using the local sendmail program. 
Configure to use a smtp server and the errror will dissapear, or reconfigure your server to be able to send mail locally. 
 
1) Maybe if you add some images, would be easier to understand what do you want to achieve. 
2)  
3)
4)  
 
I have no other answer.. cheers

**Comment by DanielnetoDotCom** [comment]
@scifiantasy can you do what @Criptos said?

**Comment by scifiantasy** [comment]
Yes I just dropped my son off at school and was going to get some pictures
and better explain to you. Thank you for making youphptube it is awesome!!

**Comment by scifiantasy** [comment]
Ok, hopefully, this explains it a little clearer about what could possibly be implemented.

![003](https://user-images.githubusercontent.com/43969902/54824775-48105480-4c82-11e9-97df-94b4ec5d0976.png)

In the picture above sites like youtube, facebook, instagram all have an on-site notification icon to let the users know they have activity. YouPhpTube already uses a bell for live videos so another icon of a different looking bell would need to be used to notify users on the site of activity instead of constantly going back and forth to email to check on what notification they have received.

![004](https://user-images.githubusercontent.com/43969902/54824870-8efe4a00-4c82-11e9-86ea-f2711e82edb4.png)

In the above picture would be the drop-down list of all the notifications the user received from subscribers or subscriptions they may have. Again making it easier for the users to see all of their notifications.

![005](https://user-images.githubusercontent.com/43969902/54824970-c7058d00-4c82-11e9-8227-0323e78c4ecc.png)

In the above picture of an example from YouTube on the description. They use a show more button to reduce the size of the description so as not to stretch out the page. Some people have very long descriptions and scrolling far to the comments may annoy some users.

![006](https://user-images.githubusercontent.com/43969902/54825075-1055dc80-4c83-11e9-9c94-7269ab98207a.png)

![007](https://user-images.githubusercontent.com/43969902/54825089-151a9080-4c83-11e9-8463-132f7b2ee56c.png)

The next two photos show my description extended after hitting the show more button so the user can read the description if they choose to. And at the bottom of the second picture is the show less button so the can close the description and get to the comments quicker.

![008](https://user-images.githubusercontent.com/43969902/54825658-78f18900-4c84-11e9-83e2-ac0f53372827.png)

In the above picture are the tags. I only added half of the 100 tags that can be placed on a video. The location they are takes up a lot of room, stretches the page and again takes away from the cleanliness of your hard work. A possible solution to this could be a tag cloud or window under the comments that collapses or a collapsing window above the description to give that smooth clean look again.

![011](https://user-images.githubusercontent.com/43969902/54825840-d685d580-4c84-11e9-8855-fc81e788ce54.png)

And, the last picture above and probably the easiest one to fix (i would myself but I have no clue how to code and usually I really mess things up when I try) is to add more characters to the description. 200 is way too limited when people are trying to discuss the video. This has been a big complaint on my site because my site has to do with building models and 200 characters are not enough to do that.

I would like to thank you for getting back to me and taking a look at my suggestions. I am very happy I found your product and plugins for making a video hosting site. I hope my ideas are helpful and please let me know if I need to explain anything further.

I hope you guys have a great day!!

**Comment by scifiantasy** [comment]
Oh and I almost forgot to thank you for telling me how to get rid of the mail error message! :)

**Comment by DanielnetoDotCom** [comment]
Thanks for all your suggestions, I agree with all, it may be implemented in the future.

About the last one 200 chars limit, you can change it here 

![image](https://user-images.githubusercontent.com/18009293/54920293-a8510180-4ee1-11e9-8de8-f4bd43e53741.png)

**Comment by scifiantasy** [comment]
Sweet thank you and I appreciate you showing me where to find the text
limit. And, thank you for taking my suggestions into consideration.
