### ISSUE TITLE
Live stream issue

### ISSUE THREAD

**Issue by bigdog175** [WWBN/AVideo#1562]
Thanks, for your previous response.  I have checked the group and permissions on HLS I have them set to owner www-data and 755.  
I am able to http://My-URL:8080/stats and I get:
![rtmp stat](https://user-images.githubusercontent.com/48419263/54166963-9711ea80-4435-11e9-8a59-86e530b75c31.PNG) Seems to be working, I am able to upload and watch videos. The "LIVE" function is still not working.  
The nginx access log shows: 
9x.xxx.xxx.x02 - - [11/Mar/2019:] "GET /live/...9e94/index.m3u8 HTTP/1.1" 404 580 "http://my-url.com/plugin/Live/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"

Error log with debug shows:
2019/03/11 19:49:14 [debug] 30487#30487: timer delta: 60060
2019/03/11 19:49:14 [debug] 30487#30487: event timer del: -1: 186281077
2019/03/11 19:49:14 [debug] 30487#30487: hls: cleanup path='/HLS/live' playlen=30000
2019/03/11 19:49:14 [debug] 30487#30487: event timer add: -1: 60000:186341137
2019/03/11 19:49:14 [debug] 30487#30487: epoll timer: 60000
2019/03/11 19:50:14 [debug] 30487#30487: timer delta: 60063
2019/03/11 19:50:14 [debug] 30487#30487: event timer del: -1: 186341137
2019/03/11 19:50:14 [debug] 30487#30487: hls: cleanup path='/HLS/live' playlen=30000
2019/03/11 19:50:14 [debug] 30487#30487: event timer add: -1: 60000:186401200
2019/03/11 19:50:14 [debug] 30487#30487: epoll timer: 60000

The youphptube.log file only contains: Start Login Request

What else am I missing?

Thanks,

**Comment by bigdog175** [comment]
Further testing shows the RTMP Accepted count increases every time I try to connect either via the mobile app or OBS from my desktop.  OBS error: Failed to connect [Could not access the specified channel or stream key, please double check you stream key. If it is correct, there may be a problem connecting to the server.  I have check both from a computer thru the internet, as well as, on a computer on the same internal network.  With the same results.

unbuntu 18.04
PHP 7.2
nginx-rtmp-module 1.1.4, nginx 1.14.0
TCP ports 80,8080 and TCP and UDP port 1935 are open and accepting connections.

**Comment by bigdog175** [comment]
--Closed by mistake

**Comment by DanielnetoDotCom** [comment]
place your nginx.conf here please

**Comment by bigdog175** [comment]
This is the nginx/sites-available/default
server {
        listen 81 default_server;
        listen [::]:81 default_server;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/html/YouPHPTube;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }

This is the nginx.conf

user www-data;

pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

 worker_processes  auto;
 error_log  /var/log/nginx/error2.log debug;

    events {
            worker_connections  1024;
    }

 rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://my-url.com/plugin/Live/on_publish.php;
                            on_play http://my-url.com/plugin/Live/on_play.php;
                            on_record_done http://my-url.com/plugin/Live/on_record_done.php;
                    }
            }
    }


    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root /var/www/html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"
                    location / {
                            root   /var/www/html;
                            index  index.html index.htm;
                    }
            }
    }

**Comment by DanielnetoDotCom** [comment]
does your on_publish **http://my-url.com/plugin/Live/on_publish.php** URL works?

**Comment by bigdog175** [comment]
No, HTTP error 401

**Comment by DanielnetoDotCom** [comment]
that is why, it must be a valid address to the on_publish.php file

**Comment by bigdog175** [comment]
This is my on_publish.php file is there something wrong where do I look to fix this issue?  We would eventually like to purchase plugins and de-branded mobile but I need to first make sure this works the way we need it to.


<?php

require_once '../../videos/configuration.php';
require_once './Objects/LiveTransmition.php';
require_once './Objects/LiveTransmitionHistory.php';
$obj = new stdClass();
$obj->error = true;

// get GET parameters
$url = $_POST['tcurl'];
if (empty($url)) {
    $url = $_POST['swfurl'];
}
$parts = parse_url($url);
error_log(print_r($parts, true));
parse_str($parts["query"], $_GET);
error_log(print_r($_GET, true));
if (!empty($_GET['p'])) {
    $obj->row = LiveTransmition::keyExists($_POST['name']);
    if (!empty($obj->row)) {
        $user = new User($obj->row['users_id']);
        if(!$user->thisUserCanStream()){
            error_log("User [{$obj->row['users_id']}] can not stream");
        }else if ($_GET['p'] === $user->getPassword()) {
            $lth = new LiveTransmitionHistory();
            $lth->setTitle($obj->row['title']);
            $lth->setDescription($obj->row['description']);
            $lth->setKey($_POST['name']);
            $lth->setUsers_id($user->getBdId());
            $lth->save();
            $obj->error = false;

        } else {
            error_log("Stream Publish error, Password does not match");
        }
    } else {
        error_log("Stream Publish error, Transmition name not found ({$_POST['name']})");
    }
} else {
    error_log("Stream Publish error, Password not found");
}

if (!empty($obj) && empty($obj->error)) {
    http_response_code(200);
} else {
    http_response_code(401);
    error_log("Publish denied");
    error_log(print_r($_GET, true));
    error_log(print_r($_POST, true));
    error_log(print_r($obj, true));
}
//error_log(print_r($_POST, true));
//error_log(print_r($obj, true));
//echo json_encode($obj);

**Comment by bigdog175** [comment]
Full fresh re-install:

youphptube.log shows this error

where is the $url being passed to on_publish? Did I miss a URL some where in the config?

[13-Mar-2019 22:28:17 UTC] PHP Notice:  Undefined index: tcurl in /var/www/html/YouPHPTube/plugin/Live/on_publish.php on line 10
[13-Mar-2019 22:28:17 UTC] PHP Notice:  Undefined index: swfurl in /var/www/html/YouPHPTube/plugin/Live/on_publish.php on line 12
[13-Mar-2019 22:28:17 UTC] Array
(
    [path] =>
)

[13-Mar-2019 22:28:17 UTC] PHP Notice:  Undefined index: query in /var/www/html/YouPHPTube/plugin/Live/on_publish.php on line 16

**Comment by nightstryke** [comment]
You may want to edit  your nginx.conf where it says:
 `user www-data;`
change it to something like this:
 `user owner www-data;`

**Comment by bigdog175** [comment]
The owner and user of the processes are already www-data for both nginx, apache and php7.2-fpm I checked the above still no luck.  The nginx access.log shows this error when I try to connect a live stream:
"GET /plugin/Live/on_publish.php HTTP/1.1" 404 580 "-" where is the dir path for this line coming from? instead of it's relative location from html root seems to trying to access /.../plugin.../   instead of url root-dir/plugin.../

**Comment by nightstryke** [comment]
> The owner and user of the processes are already www-data for both nginx, apache and php7.2-fpm I checked the above still no luck. The nginx access.log shows this error when I try to connect a live stream:
> "GET /plugin/Live/on_publish.php HTTP/1.1" 404 580 "-" where is the dir path for this line coming from? instead of it's relative location from html root seems to trying to access /.../plugin.../ instead of url root-dir/plugin.../

You aren't listening, the line at the top of nginx.conf should be  `user username groupname;`
Just using username or usergroup doesn't help, you have to state both for the HLS folder as that's the only folder NGINX has access to, it doesn't make a difference if apache is on the same user or not. You're facing several issues not just one or two, as I said earlier you should check or redownload the .htaccess file for the main root folder as there's a permission issue with the plugin/Live/ folder that is preventing you access from **on_publish.php** **on_play.php** and **on_record_done.php**

**Comment by bigdog175** [comment]
Sorry, what I meant to say was that I tried that already with same results this is the first few lines of the currently run nginx.conf, both the group and owner is also set to www-data in php-fpm.conf

    user www-data www-data;
    worker_processes  auto;
    error_log  /var/log/nginx/error2.log debug;
    include /etc/nginx/modules-enabled/*.conf;

The only .htaccess file in use is in the root dir of YouPHPTube which is the .htaccess file that came with YouPHPTube package no modifications have been made to it.

**Comment by bigdog175** [comment]
I tried to make the root html for nginx the same as apache /var/www/html/YouPHPTube if I do that and try http://my-url/plugin/Live/on_publish.php my browser just downloads the .php file. What am I missing seems like I just missing something simple...???

**Comment by nightstryke** [comment]
> I tried to make the root html for nginx the same as apache /var/www/html/YouPHPTube if I do that and try http://my-url/plugin/Live/on_publish.php my browser just downloads the .php file. What am I missing seems like I just missing something simple...???

That's wrong.
NGINX is **ONLY** used for LIVE STREAMING.
YouPHPTube runs completely off of apache.

**Comment by bigdog175** [comment]
Ok, thanks for the clarification that's what I thought but I figured it couldn't hurt to try I don't know where/what else to look at the system is not producing any error logs the only thing I can find is this line in access.log of nginx 
GET /plugin/Live/on_publish.php HTTP/1.1" 404 580
       ^ seems like that should be plugin/... or url/plugin/... no?

**Comment by alnux** [comment]
hi there i was having maybe the same problem, where obs does not stream. having the same examples of youphptube nginx configs. 

It's a crazy thing, but this was transmitting normal but from one moment to another this stopped working, I saw in the error log that was happening and I found the following

`[06-Dec-2019 15:01:47 UTC] NGINX ON Publish POST: {"redirectUri":""}
[06-Dec-2019 15:01:47 UTC] NGINX ON Publish GET: {"app":"envivo","flashver":"FMLE\/3.0 (compatible; FMSc\/1.0)","swfurl":"rtmp:\/\/envivo.tribu510.com\/envivo?p=ad79f91279c97611d81c673b5bc3d780","tcurl":"rtmp:\/\/envivo.tribu510.com\/envivo?p=ad79f91279c97611d81c673b5bc3d780","pageurl":"","addr":"181.115.198.114","clientid":"4014","call":"publish","name":"5de8996d954d5","type":"live"}
[06-Dec-2019 15:01:47 UTC] PHP Notice:  Undefined index: tcurl in /home/admin/web/envivo.tribu510.com/public_html/plugin/Live/on_publish.php on line 15
[06-Dec-2019 15:01:47 UTC] PHP Notice:  Undefined index: swfurl in /home/admin/web/envivo.tribu510.com/public_html/plugin/Live/on_publish.php on line 17
[06-Dec-2019 15:01:47 UTC] Array
(
    [path] => 
)

[06-Dec-2019 15:01:47 UTC] PHP Notice:  Undefined index: query in /home/admin/web/envivo.tribu510.com/public_html/plugin/Live/on_publish.php on line 21
[06-Dec-2019 15:01:47 UTC] Array
(
)

[06-Dec-2019 15:01:47 UTC] Stream Publish error, Password not found
[06-Dec-2019 15:01:47 UTC] Publish denied
[06-Dec-2019 15:01:47 UTC] Array
(
)

[06-Dec-2019 15:01:47 UTC] Array
(
    [redirectUri] => 
)

[06-Dec-2019 15:01:47 UTC] stdClass Object
(
    [error] => 1
)`

seeing the code of the file on_publish.php detect that $ _POST was not receiving the data and $ _GET received all the data even those of $ _POST, so until they solve because this happens add the following code on line 11 just after the error_log statements

`if (!in_array("name", $_POST)) {
    $_POST = array_merge($_POST, $_GET);
}`

and it works well, as it has to be
