### ISSUE TITLE
YouPHPTube App

### ISSUE THREAD

**Issue by CorpCaleCloud** [WWBN/AVideo#1563]
Unfortunately I've install and reinstalled the app however video don't load on the homepage I see 3 dots in RGB bouncing but when I click on the placeholder image it goes to the video I just cannot see any of the videos on the home screen

**Comment by DanielnetoDotCom** [comment]
if you connect on the demo site, does the same happen?

**Comment by CorpCaleCloud** [comment]
Haven't tried and not sure what should be the difference between, surley the demo site is updated with the same version as the main site but I'll try it 











Get Outlook for Android







On Wed, Mar 13, 2019 at 2:16 PM +0000, "YouPHPTube" <notifications@github.com> wrote:












if you connect on the demo site, does the same happen?



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DanielnetoDotCom/YouPHPTube","title":"DanielnetoDotCom/YouPHPTube","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/DanielnetoDotCom/YouPHPTube"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DanielnetoDotCom in #1563: if you connect on the demo site, does the same happen?"}],"action":{"name":"View Issue","url":"https://github.com/DanielnetoDotCom/YouPHPTube/issues/1563#issuecomment-472438182"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1563#issuecomment-472438182",
"url": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1563#issuecomment-472438182",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by CorpCaleCloud** [comment]
It happens just for a few seconds while it loads the videos then they load fine so mine are not loading since update 













Get Outlook for Android







On Wed, Mar 13, 2019 at 2:16 PM +0000, "YouPHPTube" <notifications@github.com> wrote:












if you connect on the demo site, does the same happen?



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DanielnetoDotCom/YouPHPTube","title":"DanielnetoDotCom/YouPHPTube","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/DanielnetoDotCom/YouPHPTube"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DanielnetoDotCom in #1563: if you connect on the demo site, does the same happen?"}],"action":{"name":"View Issue","url":"https://github.com/DanielnetoDotCom/YouPHPTube/issues/1563#issuecomment-472438182"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1563#issuecomment-472438182",
"url": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1563#issuecomment-472438182",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DanielnetoDotCom** [comment]
happen for a few seconds is expected, those are the loading images.

but if it is not loading at all, should be something else.

what is your website URL?

**Comment by CorpCaleCloud** [comment]
Http://tube.audiofraternity.co.uk 




Get Outlook for Android







On Mon, Mar 18, 2019 at 12:25 PM +0000, "YouPHPTube" <notifications@github.com> wrote:












happen for a few seconds is expected, those are the loading images.


but if it is not loading at all, should be something else.


what is your website URL?



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DanielnetoDotCom/YouPHPTube","title":"DanielnetoDotCom/YouPHPTube","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/DanielnetoDotCom/YouPHPTube"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DanielnetoDotCom in #1563: happen for a few seconds is expected, those are the loading images.\r
\r
but if it is not loading at all, should be something else.\r
\r
what is your website URL?"}],"action":{"name":"View Issue","url":"https://github.com/DanielnetoDotCom/YouPHPTube/issues/1563#issuecomment-473888713"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1563#issuecomment-473888713",
"url": "https://github.com/DanielnetoDotCom/YouPHPTube/issues/1563#issuecomment-473888713",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DanielnetoDotCom** [comment]
You may have some cors protection on your site, I can not reproduce this error on my sites.
