### ISSUE TITLE
LDAP integration just imports username

### ISSUE THREAD

**Issue by wn-siebert** [WWBN/AVideo#1581]
hey, 

i bought the ldap plugin and had to search several hours to get it running. the simple hint to add the domain ({$user}@example.com) would have been great in the (very small) documentation...

nevertheless, after logging in via ldap, "name", "user" and "email" is filled up only with username. working this way, the plugin is useless.

where can i configure the plugin to work correctly?

![grafik](https://user-images.githubusercontent.com/48794053/54751478-640ceb00-4bdb-11e9-955b-03bbde864c28.png)

**Comment by DanielnetoDotCom** [comment]
Hi

what is happening on your side?

are you saying if you do not pass a password the user log in on your system?

**Comment by wn-siebert** [comment]
hey,

the login works. but that's all. please see the screenshot i attached. all fields are filled only with the username. 

and it seem's like the user could change his username?! it's a very bad idea with ldap ;-)

**Comment by DanielnetoDotCom** [comment]
Hi

The plugin does not import data from your LDAP database.

I agree with you, in the future I will release an option to not allow username change

**Comment by wn-siebert** [comment]
hey daniel, thanks for answer, but without importing anything from ldap this plugin makes - in the way it works actually - not really sense to me... the userscan login, but then he has anyway to correct his profile...? so far, so bad... but now, he also is able to change his username. how should this plugin be used? there is no benefit, nevertheless, in the way this plugin works right now, it is better, NOT to allow ldap login since the user has to correct ALL fileds anyway.

or am i missing the big button where i can configure this plugin to work correct? :-)

**Comment by DanielnetoDotCom** [comment]
This plugin uses your LDAP database to authenticate users.
 so only your LDAP credentials are valid.

I agree the username should not be changed, but we do not sync the other LDAP credentials, even if you change the password ou your YouPHPTube site, it will not affect your LDAP database and only the LDAP password will be valid

**Comment by wn-siebert** [comment]
hey, okay, password makes sense, but whats with importing name and e-mail? normally, they are both stored in ldap, and these fields are filled up by username - for what? ^^

**Comment by DanielnetoDotCom** [comment]
we do not sync any data from ldap, the controll will alway be on your LDAP server

**Comment by wn-siebert** [comment]
i know, and thats fine, of course ldap controls the data. i agree with that. but, again, it makes no sense if the plugin does NOT sync the other datas like mail and name. to be clear: sync from ldap to ypt. only this way.

and you are not right if u say the plugin does not sync anything else: the plugin syncs the ldap user to the ypt mail and ldap user to ypt name. like u can see on my screenshot.

**Comment by DanielnetoDotCom** [comment]
YouPHPTube saves the user you typed, does not grab it from your LDAP

**Comment by wn-siebert** [comment]
okay, thats bad too - the data is there (in ldap), i still do not understand, why it is not synced from ldap...? for what reason are the fields from ldap ignored, and for what reason are invalid datas stored to mail and name?

**Comment by DanielnetoDotCom** [comment]
the data can not be blank, so we saved the username on the email field.

if it helps you can force your username to be an email

**Comment by wn-siebert** [comment]
sorry, this ist NOT a suitable solutions i should not force changes to ldap, the plugin should simple work correctly... :-\

**Comment by DanielnetoDotCom** [comment]
I am not meaning force your LDAP

you can Force YouPHPTube 

![image](https://user-images.githubusercontent.com/18009293/54996343-ce40d980-4fa7-11e9-83e9-25eda713419a.png)

**Comment by SaliC-re** [comment]
I would love it, too if the the fullname and mail is imported. it is really nasty to have to users change it or change it on our own afterwards with a potential of 5000 active users.
can't someone connect the ldap plugin with two more fields like rdn/{$user} ?
