### ISSUE TITLE
LDAP Plugin How it works can I restrict specific users in LDAP for uploading videos any log of user actions done in database

### ISSUE THREAD

**Issue by prathabans** [WWBN/AVideo#1592]

**Comment by prathabans** [comment]
Hi Daniel,

I want to implement your application in my organization and we have Microsoft active directory for authentication. I want to allow certain LDAP users to be authenticated users with permission to upload videos. Is this possible with the LDAP Plugin. Is there any logging of user activities in the software? 

I also want to restrict the users uploaded videos to remain inactive and only admin should be able to activate the same after verification to avoid uploading inappropriate content. Is it possible in the current software? please clarify.

**Comment by wn-siebert** [comment]
hey, better use NOT this plugin. it has no possibility to configure anything else than the username-mapping. neither u can not import anything else from AD. even not the name, or the mailadress. all these fields are filled up only by username.

the plugin does not provide anything else. i made this bad experience last week :-\

**Comment by DanielnetoDotCom** [comment]
@prathabans  The plugin only authenticate on your AD, all rules you want to do on the website you have to do manually
