### ISSUE TITLE
is there a messenger plugin ? 

### ISSUE THREAD

**Issue by joey2354** [WWBN/AVideo#1594]
hi there i thought i saw a messenger plugin but it's disappeared or wasn't there and i never saw it :/

is there on please ? 

thank you

**Comment by DanielnetoDotCom** [comment]
are you talking about the LiveChat plugin?

it appears on the Live transmitions

**Comment by joey2354** [comment]
maybe that's the one i saw, i was more looking for a messenger for members

is there one ?

**Comment by DanielnetoDotCom** [comment]
there is something called Chat2, it is a new plugin that is not on the market yet.
if you are interested in earlier access, please email me.
