### ISSUE TITLE
LDAP-Plugin: overwrites user on each login

### ISSUE THREAD

**Issue by wn-siebert** [WWBN/AVideo#1595]
hey daniel, new problem with the plugin, related to #1581 - even if i correct the data of a user (name, mail, etc), these values are overwritten with just the username from ldap if the users logs in again.

sorry, but the plugin is in it actual behavior not usable... :-(

**Comment by DanielnetoDotCom** [comment]
The user name will always be the one on LDAP, if you change it, it will create a new user on the next login attempt.

I just sent a fix that if the LDAP plugin is enabled you can not change the username anymore.
