### ISSUE TITLE
Making my youphptube site fully mobile responsive 

### ISSUE THREAD

**Issue by joey2354** [WWBN/AVideo#1598]
hi there, i had a problem making my whole site mobile responsive in the header menu and i figured it out it was a member making a title with no spaces i.e  food,bacon,cheese,ham,bread

so i edited the title and added spaces, now the sites perfect 100% responsive 

it also happens when you add a video embed link like youtube, then in the post under the vid as the description all urls are too long making the site not mobile responsive again :/

how can i fix this in someway please ?  i'm doing it manually but had to delete some urls from someone's post which i don't want to be doing always.

thank you :) hope i've explained well enough

**Comment by DanielnetoDotCom** [comment]
can you please screenshot what you are considering not responsive?

**Comment by joey2354** [comment]
> can you please screenshot what you are considering not responsive?

no sorry as i explained in my 1st post i'v already fixed it ... give it a test urself my friend


thank you
matthew

**Comment by joey2354** [comment]
ok i felt sorry for you man, here's the screenshot https://i.imgur.com/w0fKmdD.png

#alwaysandhavebeenagainstbullys #nonracist #neverhavebeen #htmltags #mmatrained
