### ISSUE TITLE
Hello, the page has been playing buffer, OBS push is normal

### ISSUE THREAD

**Issue by 1vivikun** [WWBN/AVideo#1599]
Hello, the page has been playing buffer, OBS push is normal
Can't even play in 10 minutes, buffer state

![YY图片20190329144502](https://user-images.githubusercontent.com/46800103/55215152-b1e3ad80-51f0-11e9-84ac-5e8cb46cde7d.jpg)

**Comment by 1vivikun** [comment]
> 你好，页面一直在播放缓冲区，OBS推送正常
> 甚至无法在10分钟内播放，缓冲状态
> 
> ![YY图片20190329144502](https://user-images.githubusercontent.com/46800103/55215152-b1e3ad80-51f0-11e9-84ac-5e8cb46cde7d.jpg)

Can anyone solve this problem?

**Comment by DanielnetoDotCom** [comment]
check your server resources.

Maybe the Drive IO or RAM

**Comment by 1vivikun** [comment]
How to check me, please?

Drive IO,RAM

**Comment by 1vivikun** [comment]
How to Check Server Resources

Drive IO，RAM

**Comment by 1vivikun** [comment]
My server is fast, Ping = 35

But the interface card for playing video

**Comment by 1vivikun** [comment]
????????

**Comment by DanielnetoDotCom** [comment]
The IO and RAM is just a guess, I have no clue why your server is not answering fast

**Comment by DanielnetoDotCom** [comment]
try to see if you can find any Javascript error on your browser console
