### ISSUE TITLE
how to play live video over HTTPS fix Mixed Content

### ISSUE THREAD

**Issue by lamadya** [WWBN/AVideo#1601]
hi Daniel
i have ssl on my server 
how fix insecure content blocked in chrome 
 
my live not start play on google chrome 
http://dbillioplay.com:8080/live/5c9e6553767ff/index.m3u8

how to fixed like https://demo.youphptube.com/plugin/Live/?c=HillsongUNITED
https://youphptube.com:444/live/5c9e8e3ec3185/index.m3u8

thank you

**Comment by DanielnetoDotCom** [comment]
If you want to use SSL on your streamer, your NGINX must be SSL as well.

please take a look at this https://github.com/DanielnetoDotCom/YouPHPTube/issues/930

**Comment by lamadya** [comment]
i dont find how to install ssl in nginx

**Comment by DanielnetoDotCom** [comment]
we do not teach how to install the SSL certificate, you will need to google for that.

just make sure the NGINX SSL will be installed on port 444
