### ISSUE TITLE
Trouble using a different port for the site

### ISSUE THREAD

**Issue by cmdredearth** [WWBN/AVideo#1603]
I am experimenting with running YouPHPTube on my linux server. I currently have nextcloud loaded on my server. I used a snap install for that. I tried to add YouPHPTube to my main programming, but I ended up with an Apache2 conflict because of the nextcloud install. So I decided to create a VM to install YouPHPTube in. I was able to get everything running in network. However, I am having problems accessing it off network. My router only allows me to port forward. I was able to change the apache2 listening port. That allows me to enter the site from out of network, but as soon as I hit a link, I loose the page. I am assuming that it is because the website is still trying to communicate via port 80 and 443? I am still a beginner learning how these programs work. Is there a way for me to make this work? Thanks.

**Comment by Allesanddro** [comment]
i can send u my config i use 

`<VirtualHost *:urport>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
ServerName ur domain

        ServerAdmin webmaster@localhost
        DocumentRoot location of the install path

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet`

**Comment by DanielnetoDotCom** [comment]
Hi, we have some ports requirements. 

you can check them here https://github.com/DanielnetoDotCom/YouPHPTube/wiki/YouPHPTube-hadware-requirements#what-ports-do-i-need-to-open
