### ISSUE TITLE
How remove watermark from live stream holding page embeded into wordpress

### ISSUE THREAD

**Issue by CorpCaleCloud** [WWBN/AVideo#1614]
How do i remove the watermark form the live stream when embeded in a website as i wish not to have this present for people to see. please can i remove this watermark. 

As you can see from the image it has powered by youphptube in the bottom left right hand corner and its this i want removed

![remove this logo](https://user-images.githubusercontent.com/25417743/55437410-badcd200-5596-11e9-9760-c3d1b72dec25.JPG)

**Comment by DanielnetoDotCom** [comment]
You will need to replace the image file on your server

**Comment by CorpCaleCloud** [comment]
Please can I have the location of this file, thanks

**Comment by CorpCaleCloud** [comment]
and the name of the file i have found and img folde however it has multiple images and not specific name so i cannot see which one it actually is

![imgs php](https://user-images.githubusercontent.com/25417743/55507947-c12f8480-5650-11e9-87b3-cd12c4ec795c.JPG)

**Comment by DanielnetoDotCom** [comment]
the image is inside the plugin https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/plugin/Live/view/OnAir.jpg
