### ISSUE TITLE
Question - CNAME?

### ISSUE THREAD

**Issue by bobbyrabbit** [WWBN/AVideo#1622]
I have recently tried out Vimeo's PPV facility. One function they use is being able to set a subdomain to a user group. So on the video upload page they have an option to enter, for example:
yourclient.yourdomain.com

Would this be a possible add on for YouPHPTube?

Here are the details:

Vimeo On Demand allows you to sell your videos directly through vimeo.com/ondemand and/or on a custom domain on your own website.

You can use a domain that you already own (http://my-rad-site.com), setup a subdomain on your existing website (http://movies.my-rad-site.com), or purchase a new domain to use (http://my-new-site.com).

Step 1: Setting up your domain

If you don't already have a website you want to host your VOD title on, you can purchase a domain from a registrar such as DreamHost.com, name.com, or 1and1.com.

Alternately, you can set up a subdomain on your existing site. (Contact your registrar or hosting service for instructions.)

Step 2: Update your CNAME Record or A Record

If you want your VOD page to live on a subdomain (http://movies.my-rad-site.com), you will need to follow your registrar's instructions for updating your CNAME Record so that it points to vimeopro.com.

If you want your VOD page to live on your main domain (http://my-rad-site.com), follow your domain registrar’s instructions to set the domain’s A-Record to 184.73.186.224. Note: It may take up to 72 hours for these changes to take effect across the Interwebs.

Step 3: Update your VOD Settings

On the Distribution tab of your VOD Settings page, enter your domain or subdomain under "Sell your work on your own domain," then save your changes.

Step 4: Test your new VOD page

Open a new browser window and navigate to the domain or subdomain you just set up. You should now see your VOD page! If you don't see your page, and it has been more than 72 hours since you updated your CNAME Record or A Record, contact your domain registrar for further assistance.

**Comment by DanielnetoDotCom** [comment]
Hello I believe it would be possible, but you need some changes in the YouPHPTube code and certainly some settings on your WEB server
