### ISSUE TITLE
Error updating SQL

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#1626]
Crontab is updating YouPHPTube once a day.

Today i became an error. Restored the system and make some snapshots from the updating till the error_output

Theo.
![Error 1](https://user-images.githubusercontent.com/39981177/55650663-ad1d8b80-57e6-11e9-990b-103d712cedee.jpg)
![Error 2](https://user-images.githubusercontent.com/39981177/55650673-b4dd3000-57e6-11e9-8161-26283aed5a85.jpg)
![Error 3](https://user-images.githubusercontent.com/39981177/55650689-bdce0180-57e6-11e9-8a66-7e6075fa2652.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, Searching on google looks like you need to update your MySQL Version

767 bytes is the stated prefix limitation for InnoDB tables in MySQL version 5.6 (and prior versions). It's 1,000 bytes long for MyISAM tables. In MySQL version 5.7 and upwards this limit has been increased to 3072 bytes.

https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes/39767591

**Comment by TLCReuver** [comment]
Hmmm, i can patch this version because youphptube is running on vhost with a few million records of other dbases but patching means problems with exporting sql.

Updating to 5.7 without loss is taking a risk here so i stay a while in the current version of YouPhptube until i found a way to upgrade with a minimum of down_time.

Thankz spending your time for this issue.

**Comment by DanielnetoDotCom** [comment]
@TLCReuver FYI, this is only some indexes to speed up queries, if you update version without creating an index, the YPT should still work with no problem
