### ISSUE TITLE
Admin Lockout: Enabled signin with email address

### ISSUE THREAD

**Issue by adamnoeve** [WWBN/AVideo#1630]
I enabled the feature to force user to sign-in with email address. It has locked me out of my admin account. Help.

**Comment by DanielnetoDotCom** [comment]
you are right, to fix this you will need to change the username (to an email) directly on the database

what is your site domain, you look familiar.

**Comment by moses268** [comment]
hey daniel, how are you. i have this same problem and need to know what to do please

**Comment by DanielnetoDotCom** [comment]
@moses268 you will need to have access to your database and manually change your user name to an email address.

you probably can do this ...

`sudo mysql -u root -p -e "UPDATE users SET login = '[ENTER YOUR EMAIL HERE]' , isAdmin = 1 where user = 'admin'; "  'youPHPTube'`

**Comment by moses268** [comment]
The part that says "enter your email here" is part of the code or should I
put the admin email there?

**Comment by DanielnetoDotCom** [comment]
Yes, correct!

**Comment by moses268** [comment]
Just tried it many times. It is asking for a password but I can't type
anything 😔

Will have to reset the whole site😔

 is there a simple way to reset it without losing the set up you did for me?

**Comment by DanielnetoDotCom** [comment]
what email do you want to put for admin?

what is your site URL?

**Comment by moses268** [comment]
dadli.tube268@gmail.com

Dadlitube.com

**Comment by DanielnetoDotCom** [comment]
I tried to access your server and looks like I have no access to it anymore

**Comment by moses268** [comment]
I did not make any changes. How can I fix that?

**Comment by DanielnetoDotCom** [comment]
Ok I just notice your IP has changed

The MySQL command does not work because you already have a user with the username dadli.tube268@gmail.com

Now your user dadli.tube268@gmail.com is admin, you can try to login with it and do what ever you want.

**Comment by moses268** [comment]
Thanks man. I will send a tip

**Comment by moses268** [comment]
Just something I noticed different from this topic

I would like the radon videos to play up next but the "keep user on
channel" option is not working. When I turn it off below the video I am
watching still has only videos from that channel.

I would like it to stay as random videos up next all the time

**Comment by DanielnetoDotCom** [comment]
Hi

@moses268 can you please reproduce it on demo site?

**Comment by moses268** [comment]
Yep

https://drive.google.com/file/d/1jtn2XYIKAAdqTOOzBV_g-a30mRPgSR_v/view?usp=drivesdk

Notice in the video the check mark is off for "keep user on channel" but it
still only recommend videos from admin channel

**Comment by DanielnetoDotCom** [comment]
Can you please unckeck this and try again

![image](https://user-images.githubusercontent.com/18009293/73175921-03e3b100-40ea-11ea-866f-045110a9d326.png)

**Comment by moses268** [comment]
noted.
