### ISSUE TITLE
how to make icons categories dynamic in home page not icon folder

### ISSUE THREAD

**Issue by lamadya** [WWBN/AVideo#1632]
Hi:
how to make icons categories dynamic in home page (modeflex.php) like menu navbar (navbar.php) not icon folder
< i class=" fas fa-folder ">< /i >

please help thank you

**Comment by DanielnetoDotCom** [comment]
You should be able to change the icons on the category 

![image](https://user-images.githubusercontent.com/18009293/55683966-50bc8800-591c-11e9-921e-6d2ddc0afb5b.png)
