### ISSUE TITLE
Live User Counter Plugin issue 

### ISSUE THREAD

**Issue by gdulli111** [WWBN/AVideo#1633]
Hi i just purchased the live user counter plugin and installed it but its not working not sure what i may be doing wrong when i check the error log this is what i see any help please thanks

[06-Apr-2019 16:27:53 America/Chicago] PHP Fatal error:  Uncaught Error: Call to undefined method mysqli_stmt::get_result() in /home2/gdulli101/public_html/plugin/LiveUsers/Objects/LiveOnlineUsers.php(14) : eval()'d code(1) : eval()'d code:58
Stack trace:
#0 /home2/gdulli101/public_html/plugin/LiveUsers/view/beat.json.php(14) : eval()'d code(1) : eval()'d code(15): LiveOnlineUsers->loadFromTransmitionKey('5ca919ce27f5b')
#1 /home2/gdulli101/public_html/plugin/LiveUsers/view/beat.json.php(14) : eval()'d code(1): eval()
#2 /home2/gdulli101/public_html/plugin/LiveUsers/view/beat.json.php(14): eval()
#3 {main}
  thrown in /home2/gdulli101/public_html/plugin/LiveUsers/Objects/LiveOnlineUsers.php(14) : eval()'d code(1) : eval()'d code on line 58

**Comment by DanielnetoDotCom** [comment]
Please read the user notes for this method:

http://php.net/manual/en/mysqli-stmt.get-result.php

It requires the mysqlnd driver... if it isn't installed on your webspace you will have to work with BIND_RESULT & FETCH!

https://secure.php.net/manual/en/mysqli-stmt.bind-result.php

https://secure.php.net/manual/en/mysqli-stmt.fetch.php

**Comment by Martinsco12** [comment]
Hello. Has it been resolved?
