### ISSUE TITLE
Not an issue but question and idfk where to post it lol

### ISSUE THREAD

**Issue by BobSooper** [WWBN/AVideo#1635]
So there's a thing on google drive where you get infinite uploads for videos. It ain't a glitch they legit for some reason made it like this... And well I was wondering if there's a way to redirect the uploaded videos to the google drive?

**Comment by BobSooper** [comment]
If you want to know how to do it just ask.

**Comment by Criptos** [comment]
I use google drive, and haven't came across that feaature... where is it?

**Comment by DanielnetoDotCom** [comment]
@BobSooper we do not support Google drive yet.

FYI, Google Drive has a transfer limit. if you became to broadcast too much you will probably have problems to play your videos.

I am saying this because I saw some problem with files people share on the internet. they reach the daily transfer limit
