### ISSUE TITLE
Direct Upload

### ISSUE THREAD

**Issue by MrHuntersk** [WWBN/AVideo#1640]
Hi Daniel,
i hope you are well. about the direct upload. i would like to have a bulk upload, do i have to purchase a plugin. because it takes long to upload a single file of 20mbs. 
thanks

**Comment by DanielnetoDotCom** [comment]
Hi, I bulk direct upload will not speed up things.

looks like you have a bandwidth issue. 

Upload multiple files at once will only make it worst

**Comment by SubjectXXX** [comment]
With other words: bulk upload is already enabled, heck, you can even drag and drop folder full of videos into the uploader and it will pick them up (which is awesome!).

Can you tell us more about you internet bandwidth and where your server resides? Maybe you have some problems with upload speeds on your part (wifi?) or your server is throttling connections..
