### ISSUE TITLE
Edit Main Menu

### ISSUE THREAD

**Issue by adamnoeve** [WWBN/AVideo#1641]
Could you instruct me as how to edit these? I'd like to remove them.

**Comment by DanielnetoDotCom** [comment]
what would do you like to remove?

I do not recommend you to modify the file, but most of the items you can remove on customizeAdvanced

**Comment by adamnoeve** [comment]
I don't plan on using the YPT to separate audio. Therefore, the menu option
becomes an empty link. Is there a way I can just hide it, instead of
deleting it?

**Comment by DanielnetoDotCom** [comment]
Did you see this?

![image](https://user-images.githubusercontent.com/18009293/55888355-96c85480-5b85-11e9-8d6f-fe4adf16caae.png)

**Comment by adamnoeve** [comment]
Now I do -- don't know how I missed it. Thank you!
