### ISSUE TITLE
 Notice: Undefined variable: global in C:\wamp64\www\YouPHPTube-master\YouPHPTube-master\install\index.php on line 21 Call Stack #TimeMemoryFunctionLocation 10.0131405432{main}( )...\index.php:0 ">

### ISSUE THREAD

**Issue by dagialex** [WWBN/AVideo#1642]
Notice: Undefined variable: global in C:\wamp64\www\YouPHPTube-master\YouPHPTube-master\install\index.php on line 21 Call Stack #TimeMemoryFunctionLocation 10.0131405432{main}( )...\index.php:0 ">

please fix this

**Comment by DanielnetoDotCom** [comment]
I do not recommend installation on Windows, also the recommended OS is Ubuntu 16.04 or 18.04

**Comment by dagialex** [comment]
i was installed on windows before and it works fine. I need this application for local network streaming i have an internet cafe i need a customer to access movies from my HHD without internet

**Comment by AgThukhaKo** [comment]
@dagialex Did you solved that? I also getting that error.

**Comment by dagialex** [comment]
> @dagialex Did you solved that? I also getting that error.

No, I am using Now PHPSugar or PHPMelody CMS best script for Video Site
