### ISSUE TITLE
I want to Import Video from youtube and direct upload to my server not encoding it.

### ISSUE THREAD

**Issue by jaewoo0** [WWBN/AVideo#1645]
Is it possible? Because of the file size, I want to upload it as 6_tmpFile.mp4 not 6_tmpFile_converted_HD.mp4. Please make it possible. Thank you.

**Comment by DanielnetoDotCom** [comment]
Hi, this request makes no sense for me.

the tmpFile are temporary files and will be deleted after the encoder is finished
