### ISSUE TITLE
If I import video from youtube, my language does not show up.

### ISSUE THREAD

**Issue by jaewoo0** [WWBN/AVideo#1646]
It shows up like this.
[MV] Apink() _ FIVE
not
[MV] Apink(에이핑크) _ FIVE
but description is fine, but subject is the problem.

**Comment by DanielnetoDotCom** [comment]
Usually, we remove the non-standard chars from the file name.

what is the YouTube URL are you downloading?

**Comment by jaewoo0** [comment]
https://www.youtube.com/watch?v=xRbPAVnqtcs

**Comment by jaewoo0** [comment]
Is there a fix? thank you.

**Comment by DanielnetoDotCom** [comment]
Not yet, sorry
