### ISSUE TITLE
Requested Range Not Satisfiable

### ISSUE THREAD

**Issue by SubjectXXX** [WWBN/AVideo#1647]
Requested Range Not Satisfiable
None of the range-specifier values in the Range request-header field overlap the current extent of the selected resource.

Headers:
Request URL: https://video.xyz.si/videos/_YPTuniqid_5c6d09c20b8ed5.66886127_SD.mp4
Request Method: GET
Status Code: 416 Requested Range Not Satisfiable
Remote Address: 212.235.181.172:443
Referrer Policy: no-referrer-when-downgrade
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1
Date: Wed, 10 Apr 2019 09:53:26 GMT
Keep-Alive: timeout=5, max=78
Server: Apache/2.4.29 (Ubuntu)
Transfer-Encoding: chunked
Accept: */*
Accept-Encoding: identity;q=1, *;q=0
Accept-Language: en,en-GB;q=0.9,sl;q=0.8
Cache-Control: no-cache
Connection: keep-alive
Host: video.xyz.si
Pragma: no-cache
Range: bytes=4390912-
Referer: https://video.xyz.si/v/631
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

https://video.xyz.si/videos/_YPTuniqid_5c6d09c20b8ed5.66886127_SD.mp4

**Comment by DanielnetoDotCom** [comment]
I have never seen this error before

try to comment this line and check if it works
https://github.com/DanielnetoDotCom/YouPHPTube/blob/72f647b7d1fa1faa5e309aa5dee36e7e036ebad2/.htaccess#L227
