### ISSUE TITLE
Live Questions.

### ISSUE THREAD

**Issue by adamnoeve** [WWBN/AVideo#1650]
1. How can I integrate the live software, onto the server so every user doesn't have to download it?
2. How can mobile users go live?

Thanks in advance.

**Comment by DanielnetoDotCom** [comment]
1. I still not find any good tool to work as an RTMP publisher on the web.
2. yes using Android, we still not able to transmit using iOS

**Comment by variable205** [comment]
> 1. I still not find any good tool to work as an RTMP publisher on the web.
> 2. yes using Android, we still not able to transmit using iOS

I had stumbled across this during my search: https://medium.com/@yenthanh/setup-a-rtmp-livestream-server-in-15-minutes-with-srs-1b0046c77267
Not sure if it's relevant or not, but something to look at.

I also came across this app as well: https://streamlabs.com/mobile-app
It will allow you to place in your own RTMP URL and Stream Key

**Comment by JeffersonSimonJS** [comment]
Do we need to verify our site even it is Intranet site??

**Comment by variable205** [comment]
Not sure. I haven't tested it
