### ISSUE TITLE
Fresh install but redirection without slash after domain

### ISSUE THREAD

**Issue by integralmedia** [WWBN/AVideo#1651]
I just did a fresh install of YouPHPTube and go to the Completion page where it says to delete the install directory. I click the go to site button and it loads but none of the page dependencies do. It seems that the trailing slash is missing after the domain so the pages/elements don't resolve.

For example: http://domain.com/user is being redirected as http://domain.comuser

note the missing slash after the domain. I know what the problem is just don't know where to make the change...

**Comment by integralmedia** [comment]
Well I figured it out after several hours of looking...

In: 
/videos/configuration.php

Change:
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;

To:
 $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].'/'.$subDir;

I doubt this is a proper solution but its working now...

**Comment by SubjectXXX** [comment]
Its mainly has to do how you configured your virtual host on apache.

If you check the config for your virtual host, you have ServerName directive.

Your solution is proper anyway, I have fixed it in the same manner. Once you put your videos to other location and try to softlink it, you will also have to drop $subDir variable from there.. Just a heads up :)
