### ISSUE TITLE
Error (1045) Access denied for user ''@'localhost' (using password: NO)  

### ISSUE THREAD

**Issue by ghost** [WWBN/AVideo#1652]
Hi guys have YouPHPTube running okay on vps have my own server now and trying to install YouPHPTube on this cant connect to database  bin trying for a week   mysql works okay can connect with root or user no problem    but cant connect with install get this: Sorry!
Connect Error (1045) Access denied for user ''@'localhost' (using password: NO)  Have reset pasd added user etc, this is apache error log.  ubuntu 16.04  no cpanel

ERROR:
PHP Notice:  Undefined index: systemRootPath in /var/www/html/YouPHPTube/install/checkConfiguration.php on line 11, referer: http://81.150.166.172/YouPHPTube/install/index.php

permissions are 777 and ww.data owns   can you help here please dave

**Comment by SubjectXXX** [comment]
It seems that you misconfigured your ypt..

go to videos/configuration.php and enter correct DB username and password (non root one..)

**Comment by DanielnetoDotCom** [comment]
Also I can see you did not enter any username for the database

`Connect Error (1045) Access denied for user ''@'localhost' (using password: NO)`

**Comment by k7n2g** [comment]
Hi there is no  videos/configuration.php  file in YouPHPTube  
Connect Error (1045) Access denied for user ''@'localhost' (using password: NO)
i added user dave and password ABC123abacus1  to database and gave all permissions to dave and FLUSHED PRIVELEDGES;  still cant access

**Comment by k7n2g** [comment]
Okay got it added configuration.php from other site and it works thanks guys dave

**Comment by Maikuolan** [comment]
@DanielnetoDotCom This issue's author now displays as "ghost", which most likely means that they deleted their GitHub account at some point account a while ago. So, it should be safe to close this issue, I think.
