### ISSUE TITLE
Update Issues: Encorder, Menu Icons & Login Box

### ISSUE THREAD

**Issue by adamnoeve** [WWBN/AVideo#1654]
Was there an update pushed? Since today I've been my encoder just hangs & my login form has been cut short and other things. See screenshots

![image](https://user-images.githubusercontent.com/4432175/55914128-5df3a400-5bb4-11e9-81f5-d04ac2dc81eb.png)

![image](https://user-images.githubusercontent.com/4432175/55914200-88456180-5bb4-11e9-8e26-f6a1389227f7.png)

![image](https://user-images.githubusercontent.com/4432175/55914231-9d21f500-5bb4-11e9-996b-94762404e338.png)

**Comment by DanielnetoDotCom** [comment]
can you please email me your site admin credentials, I will check it

**Comment by DanielnetoDotCom** [comment]
I think it is fixed now, it was some misconfiguration some plugins enabled and not propper configured

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Moving-videos-directory-and-securing-files-from-direct-access-to-the-video-source-file#configure-your-apache-xsendfile

also, you try to use the encoder Network, but you do not have it

https://github.com/DanielnetoDotCom/YouPHPTube-Encoder-Network

**Comment by adamnoeve** [comment]
Sorry but it's not. The icons are missing only for guest.

[image: image.png]

**Comment by DanielnetoDotCom** [comment]
what icons?
