### ISSUE TITLE
deactivate the login

### ISSUE THREAD

**Issue by codelabinf** [WWBN/AVideo#1655]
Hi, I accidentally deactivate the login as admin (sing in and sign on) and when I exit, the option to enter username and password does not appear anywhere. Nor can I do it by entering the encoder and from there by clicking on the logo so that there will be the main page. Please, I need help to fix this. From already thank you very much!

**Comment by SubjectXXX** [comment]
Do you have any experience with writing directly into MySQL database?

**Comment by DanielnetoDotCom** [comment]
if you edit the plugin table and delete object_data column content the plugin will back to the default values and you should be able to access your login again

**Comment by codelabinf** [comment]
Hi, I'm not an expert on that topic, I solved it by reinstalling everything.
Thank you so much!
