### ISSUE TITLE
The page at 'https://video.xyz.si/v/838' was loaded over HTTPS, but requested an insecure image..

### ISSUE THREAD

**Issue by SubjectXXX** [WWBN/AVideo#1657]
The page at 'https://video.xyz.si/v/838' was loaded over HTTPS, but requested an insecure image 'http://212.xxx.xxx.xxx/view/img/userSilhouette.jpg'. This content should also be served over HTTPS.

I cannot find the code where hostname gets replaced with IP. This warning happens when I open a video, culprit is the image of video owner.

![http](https://user-images.githubusercontent.com/2082595/55950732-da8a8f00-5c55-11e9-80da-4b2cfeac2688.png)

**Comment by DanielnetoDotCom** [comment]
please check your configuration.php file

or maybe this page is cached.

I think this is a but on the cache system that saves the same cache for http and https.

I will send an update soon
