### ISSUE TITLE
My videos listing should be cached!

### ISSUE THREAD

**Issue by SubjectXXX** [WWBN/AVideo#1659]
I have around 500 videos on my site, I selected show all. First time it took long time to show all the videos I have access too as admin, which is OK, I understand that.

But then I opened video and clicked back in my browser and ypt went and searched all the videos again from the backend.

Could this list, even HTML, be cached for a few seconds?

**Comment by DanielnetoDotCom** [comment]
Hi, where is it, on the first page?

or on videos manager?

**Comment by SubjectXXX** [comment]
Videos manager
