### ISSUE TITLE
Livestream Installation Ubuntu 18.X Script Update Contribution

### ISSUE THREAD

**Issue by variable205** [WWBN/AVideo#1665]
The following script below is an updated version of the way to install everything needed for the 18.X installation of Live Streaming ngnix

sudo apt-get install build-essential libpcre3 libpcre3-dev libssl-dev sudo apt-get install --reinstall zlibc zlib1g zlib1g-dev && sudo mkdir ~/build && cd ~/build && sudo git clone git://github.com/arut/nginx-rtmp-module.git && sudo wget http://nginx.org/download/nginx-1.13.8.tar.gz && sudo tar xzf nginx-1.13.8.tar.gz && cd nginx-1.13.8 && sudo ./configure --with-http_ssl_module --with-http_stub_status_module --add-module=../nginx-rtmp-module && sudo make && sudo make install && sudo mkdir /usr/local/nginx/ssl/ && sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /usr/local/nginx/ssl/nginx.key -out /usr/local/nginx/ssl/nginx.crt && sudo /etc/init.d/apache2 restart && sudo mkdir /HLS && sudo mkdir /HLS/live

A couple things to note, I only added "apt-get install --reinstall zlibc zlib1g zlib1g-dev" and removed "php7.0-xml" because the zlibg already exists on the server, and I wasn't sure exactly what was installed. So I played it safe and installed the extras.

Php7.0-xml and higher versions are already installed on Ubuntu 18.X it seems. So the script throws an error when trying to find the older version.

No issues, but just wanted to contribute what little I can do this awesome project. The script appears to be working on my end, and I was able to live stream tonight, no problems!

**Comment by DanielnetoDotCom** [comment]
Hi, did you check this?

https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer

**Comment by variable205** [comment]
Ya, that's the page, but it looks different now. I also forgot to mention, "apt-get curl" too, as php-curl doesn't quite cover everything.
