### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by jaewoo0** [WWBN/AVideo#1666]
1. It's showing as LIVE when it isn't.
![live](https://user-images.githubusercontent.com/49477718/56098117-13698300-5f38-11e9-9ab9-984664224005.png)
2. When I turn Autoplay on, it skips to next video again and again sometimes. I can't upload screenshot of this error because it is impossible to take screenshot of it. I wasn't getting this error until I updated to 7.0.
3. It sometimes won't play video but sound is coming. Only loading icon showing.
![loadingicon](https://user-images.githubusercontent.com/49477718/56098164-9559ac00-5f38-11e9-9910-bcd1bf70d16f.png)
![loadingicon2](https://user-images.githubusercontent.com/49477718/56098224-44968300-5f39-11e9-851f-dc7ff67574ce.png)

**Comment by DanielnetoDotCom** [comment]
Is the same thing happening on demo site?

Most of your errors look like Javascript errors, are you able to detect what error is that?
