### ISSUE TITLE
Share Links From App

### ISSUE THREAD

**Issue by adamnoeve** [WWBN/AVideo#1667]
Hello. When sharing from the app to many of the major social networks, it only creates a picture without a url link. 

Thanks in advance

**Comment by DanielnetoDotCom** [comment]
can you please specify what social network does this happen?

I just include a bunch of new social share, but I didn't test it

**Comment by adamnoeve** [comment]
In particular I've seen this happen with the Facebook, Instagram & Snapchat
apps where only the image from the video is shared, not a link to the video
or site.

Thanks in advance Team.

**Comment by DanielnetoDotCom** [comment]
Hi

Is not clear to me what you saw and what was expected. do you mind to screenshot the share result?

**Comment by adamnoeve** [comment]
https://mail.google.com/mail/u/0?ui=2&ik=712548a851&attid=0.1&permmsgid=msg-f:1631005813411490458&th=16a27f2556fd2a9a&view=att&disp=safe&realattid=16a27f1f0ccd4ea3ae81

https://mail.google.com/mail/u/0?ui=2&ik=712548a851&attid=0.2&permmsgid=msg-f:1631005813411490458&th=16a27f2556fd2a9a&view=att&disp=safe&realattid=16a27f2113a314345cb2

https://mail.google.com/mail/u/0?ui=2&ik=712548a851&attid=0.3&permmsgid=msg-f:1631005813411490458&th=16a27f2556fd2a9a&view=att&disp=safe&realattid=16a27f2111e380890c61

Facebook, Snapchat & Instagram

**Comment by adamnoeve** [comment]
![Screenshot_20190416-165347](https://user-images.githubusercontent.com/4432175/56243765-62630580-6069-11e9-9a87-6283777bd76c.png)

![Screenshot_20190416-165308](https://user-images.githubusercontent.com/4432175/56243770-65f68c80-6069-11e9-9637-a5da6a35863e.png)

![Screenshot_20190416-165635 (1)](https://user-images.githubusercontent.com/4432175/56243792-73ac1200-6069-11e9-8a27-ff5cb5a9b146.png)

**Comment by KenRHill** [comment]
Hi Daniel,

First and foremost, I support you and the YouPHPTube project.  I think the platform is great and you work really hard on it and I appreciate that you have helped me many times, so I don't want to be considered a nitpicker.  

Currently as agreed, I am patiently awaiting a fix to this issue, as I do believe this is the same issue that I am having with both our Android and iOS apps for our site too.  I notice that when somebody uses the mobile app to try to share a video onto social media, especially Facebook, it appears that Facebook only shows a thumbnail of the video and there is no link included to the video to direct anyone to the site or the video page.

It appears that the mobile apps only share the thumbnails of the video being shared from the apps.  I hope we can resolve this issue soon, as I know quite a large number of people use Facebook, Twitter and LinkedIn and where we are not being able to share anything but the thumbnail from the mobile app is beginning to become an issue for my site users.

**Comment by DanielnetoDotCom** [comment]
Hello Friend

Thanks for your support, I'll be updating the app soon.

I'm going to add this review to my TODO list.

so far my TODO list includes the following ...

1. Add notifications 
2. Option to use the native mobile player (Currently it is an HTML Player)
3. Review the social sharing of videos
