### ISSUE TITLE
Floating Video Covered

### ISSUE THREAD

**Issue by adamnoeve** [WWBN/AVideo#1668]
The floating video is covered when the main menu sidebar is active. SEE SCREENSHOTS

![image](https://user-images.githubusercontent.com/4432175/56099266-9824b480-5ed8-11e9-8993-0650e70ca2b2.png)

![image](https://user-images.githubusercontent.com/4432175/56099271-a7a3fd80-5ed8-11e9-8aeb-efa51d91b8ad.png)

**Comment by adamnoeve** [comment]
In fact, there is not a issue with the main video. SEE SCREENSHOTS

![image](https://user-images.githubusercontent.com/4432175/56099302-108b7580-5ed9-11e9-8f66-77db36041a2e.png)

![image](https://user-images.githubusercontent.com/4432175/56099297-eb970280-5ed8-11e9-95ce-1ae96fbd3acb.png)

**Comment by tgd1973** [comment]
Found a solution? Maybe keeping the default sidebar closed? ( How do you do ?)

**Comment by DanielnetoDotCom** [comment]
Hi, @adamnoeve I understand what you mean. 

Right now there is no solution for that, but you should try the gallery style.
