### ISSUE TITLE
Instalação do youphptube no wamp por servidor compartilhado

### ISSUE THREAD

**Issue by heme007** [WWBN/AVideo#1669]
Se eu instalar meu youphptube no wamp e subir pra um servidor compartilhado, ele funciona? E como seria o passo a passo?

**Comment by DanielnetoDotCom** [comment]
Recomendo que você instale ele no Ubuntu, pode até usar uma máquina virtual para isso.

Servidor compartilhado tambem não funciona, funciona somente VPS ou servidor Dedicado
