### ISSUE TITLE
View Count Concern: See Screenshot

### ISSUE THREAD

**Issue by adamnoeve** [WWBN/AVideo#1670]
There appears to be an issue with the video counts. Some of these are duplicates, in other words... counted twice on one view. Also I was under the impression views an authentic view was; every 10 minutes per user. 

![image](https://user-images.githubusercontent.com/4432175/56131995-eb3d4c80-5f56-11e9-89a2-affa6d7ea291.png)

Please advise.

**Comment by adamnoeve** [comment]
FYI, these stats were from the same video, viewed by the same user. Also.... the date log is off, how can I correct that?

**Comment by DanielnetoDotCom** [comment]
what video was this?

this is the monetize plugin?

I probably need to improve the monetize plugin
