### ISSUE TITLE
Live Stream Page loading forever

### ISSUE THREAD

**Issue by itraxAdmin** [WWBN/AVideo#1673]
Hi just download the YouPHPTube 7.0.
Everything looks fine, but when I click on Live button the page don't load. It just gets loading forever.

I take a deep look and looks like the session_start() function on objects/include_config.php file is freezing when I try to load the Live page. 

What can I do?

Ps.: I'd configure the YouPHPTube to run on my site root. 

Thanks

**Comment by itraxAdmin** [comment]
Just start working.

**Comment by itraxAdmin** [comment]
The problem is back.
I reboot my server and now I cannot access the live page anymore. 
Before click on "LIVE" button I can navigate through all site with no problem, when I click it the apache freezes.

I track the problem source to the function call "session_start();" on /var/www/html/objects/include_config.php
The strange thing here is that several pages calls this function but only the "live" page freezes.

```
// each client should remember their session id for EXACTLY 1 hour
session_set_cookie_params($config->getSession_timeout());
session_start();

```

Any ideas?

Thanks

**Comment by DanielnetoDotCom** [comment]
I have no idea what is it. you should check your error log to try to find what is the problem
