### ISSUE TITLE
live streaming and live chat not working

### ISSUE THREAD

**Issue by benx3** [WWBN/AVideo#1675]
Hi support team,
I have followed your instructions. And install successfully. But I have problems with the streaming and chat plugins. I do not know why.
Can you help me check it out?
Thank you very much.
![image](https://user-images.githubusercontent.com/40012684/56454857-43be8080-6381-11e9-83e4-418057616f81.png)

my nginx config:
`    worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://stream.cupc1.tv/plugin/Live/on_publish.php;
                            on_play http://stream.cupc1.tv/plugin/Live/on_play.php;
                            on_record_done http://stream.cupc1.tv/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   
            }
    }
`
admin config:
`{"button_title":"LIVE","server":"rtmp://stream.cupc1.tv/live","playerServer":"http://stream.cupc1.tv:8080/live","stats":"http://stream.cupc1.tv:8080/stat","disableGifThumbs":false,"useAadaptiveMode":false,"experimentalWebcam":false}`
`{"port":"8888","websocket":"ws://stream.cupc1.tv:8888","onlyForLoggedUsers":false,"loadLastMessages":10}`
Log youphptube:

> [20-Apr-2019 06:43:13 UTC] Start Login Request
[20-Apr-2019 06:43:13 UTC] redirectUri: 
[20-Apr-2019 06:43:13 UTC] sane redirectUri: http://stream.cupc1.tv/
[20-Apr-2019 06:43:13 UTC] user::login: noPass = , encodedPass = , this->user, admin 123.21.104.207
[20-Apr-2019 06:43:13 UTC] encryptPasswordVerify: encrypt
[20-Apr-2019 06:43:13 UTC] Password check new hash pass does not match, trying MD5
[20-Apr-2019 06:43:13 UTC] Password check Old not encoded pass
[20-Apr-2019 06:43:13 UTC] Password check Old found
[20-Apr-2019 06:43:13 UTC] user::login: Do login without cookie
[20-Apr-2019 06:45:50 UTC] PHP Fatal error:  Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:8888": Address already in use in /var/www/html/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php:164
Stack trace:
#0 /var/www/html/plugin/LiveChat/ratchet/react/socket/src/Server.php(31): React\Socket\TcpServer->__construct('tcp://0.0.0.0:8...', Object(React\EventLoop\StreamSelectLoop), Array)
#1 /var/www/html/plugin/LiveChat/ratchet/cboden/ratchet/src/Ratchet/Server/IoServer.php(59): React\Socket\Server->__construct('0.0.0.0:8888', Object(React\EventLoop\StreamSelectLoop))
#2 /var/www/html/plugin/LiveChat/chat-server.php(20): Ratchet\Server\IoServer::factory(Object(Ratchet\Http\HttpServer), '8888')
#3 {main}
  thrown in /var/www/html/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php on line 164
[20-Apr-2019 08:02:26 UTC] Start Login Request
[20-Apr-2019 08:02:26 UTC] redirectUri: 
[20-Apr-2019 08:02:26 UTC] sane redirectUri: http://stream.cupc1.tv/
[20-Apr-2019 08:02:26 UTC] user::login: noPass = , encodedPass = , this->user, adsahihi@gmail.com 123.21.104.207
[20-Apr-2019 08:02:26 UTC] Password check new hash user not found
[20-Apr-2019 08:02:30 UTC] Start Login Request
[20-Apr-2019 08:02:30 UTC] redirectUri: 
[20-Apr-2019 08:02:30 UTC] sane redirectUri: http://stream.cupc1.tv/
[20-Apr-2019 08:02:30 UTC] user::login: noPass = , encodedPass = , this->user, admin 123.21.104.207
[20-Apr-2019 08:02:30 UTC] encryptPasswordVerify: encrypt
[20-Apr-2019 08:02:30 UTC] user::login: Do login without cookie
[20-Apr-2019 08:02:34 UTC] PHP Fatal error:  Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:8888": Address already in use in /var/www/html/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php:164
Stack trace:
#0 /var/www/html/plugin/LiveChat/ratchet/react/socket/src/Server.php(31): React\Socket\TcpServer->__construct('tcp://0.0.0.0:8...', Object(React\EventLoop\StreamSelectLoop), Array)
#1 /var/www/html/plugin/LiveChat/ratchet/cboden/ratchet/src/Ratchet/Server/IoServer.php(59): React\Socket\Server->__construct('0.0.0.0:8888', Object(React\EventLoop\StreamSelectLoop))
#2 /var/www/html/plugin/LiveChat/chat-server.php(20): Ratchet\Server\IoServer::factory(Object(Ratchet\Http\HttpServer), '8888')
#3 {main}
  thrown in /var/www/html/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php on line 164

Please let me know if you need something more.

**Comment by DanielnetoDotCom** [comment]
what I can see is:

PHP Fatal error: Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:8888": Address already in use in /var/www/html/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php:164

or your chat is already running or you have something else using this port.

About the live, I am not sure what are you missing. check your nginx log file for some clue
