### ISSUE TITLE
Hosting videos with cloudflare

### ISSUE THREAD

**Issue by hdavy2002** [WWBN/AVideo#1678]
Folks,

I came across Cloudflare's Stream. 

https://developers.cloudflare.com/stream/getting-started/uploading-cloudflare-dashboard/

One can upload video on their platform, then get an embed code or a link.

Question is: If I used the embed code/link option in YouPHPTube, can it work with a cloudflare stream link or does this exclusively work with Youtube.

actually, it just struck me, that I should sign up and give it a try. I can save a lot of storage space and cloudflare does all the encoding etc for me. Their pricing is not too bad also.

From the site:
**"Stream**
Stream is a video platform for developers. Upload a video and Cloudflare will encode, process and deliver it on all browsers and devices.
Every 1,000 minutes viewed costs $1 per month. Each 1,000 minutes of video stored costs $5 per month. Change storage capacity at any time to fit your needs.
After enabling Stream, upload videos to get an embed code in minutes. View developer documentation to learn more.

Cloudflare Stream is the most affordable and easy-to-use streaming platform.

**Processing: Free**
You get multi-bit rate encoding at no cost.

**Player: Free**
You get a reliable and fully customizable player with your own branding at no cost.

**Storage: $5.00 per 1,000 minutes (prepaid)**
You only pay for the length of your original video. Example: Even if your 10-minute video is encoded into 6 different bit rates, you will only pay for 10 minutes (instead of 60 minutes).

**Streaming: $1.00 per 1,000 minutes (postpaid)**
You will only be billed each month based on how many minutes you stream. If you plan to stream more than 1M minutes per month, please contact our Enterprise Team for discounted pricing."

**Comment by DanielnetoDotCom** [comment]
The prices are not bad, if you get the direct link it should work

**Comment by hdavy2002** [comment]
Thanks. I will try that and get back.

**Comment by Puyodead1** [comment]
This is what I discovered to day :P
Going to try to use it instead of a Cloud mounted GDrive.
How exactly would one use a video from this service though?
