### ISSUE TITLE
Encoder Stuck in Encoding Loop 2

### ISSUE THREAD

**Issue by JaredHeath1** [WWBN/AVideo#1687]
Hey Daniel,

I am having the same issue as this: https://github.com/YouPHPTube/YouPHPTube/issues/1340

Here are my logs: 
[YouPHPTube_EncodingIssue_1.txt](https://github.com/YouPHPTube/YouPHPTube/files/3124060/YouPHPTube_EncodingIssue_1.txt)

I am not receiving any PHP errors or anything. In the log I uploaded two files, the first file is 1.9 GB the second is 1.8 GB. The first file failed and entered into the loop as described by Ken. The second uploaded successfully. As the files are very similar, I don't know what is going on. This has happened repeatedly, especially when encoding all three qualities on large files (HD, SD, Low). It may be specific to the low quality encode though.

My apache/nginx logs on both the frontend video site and the encoder don't show any errors.

Where should I look further to troubleshoot? What information do you need from me or how should I proceed to fix this issue? Thoughts?

Great program, thank you for building it.

Sincerely,

Jared

**Comment by DanielnetoDotCom** [comment]
Hi

I am not sure, I could not find anything on your log.

does this issue happen all the time or it is random?

does the encode process complete? or it crashes in the middle?

**Comment by JaredHeath1** [comment]
It happens consistently when encoding all three qualities  (HD, SD, Low) options with a 1.9 GB file. With encoding the two (HD and Low only) it seems to happen randomly. On smaller videos (400 MB) with two qualities (HD and SD) it works every time. It fails sometimes even on smaller files encoding all three (HD, SD, Low).

It seems to happen when switching from SD to Low quality, or when finishing Low quality and it should transfer it doesn't. It stops and never goes to transferring. It halts the encoding of the queue until the broken video is removed from the queue.

Thoughts?

**Comment by DanielnetoDotCom** [comment]
I have no idea, I have never seen this before.

check your log file for some clue

**Comment by JaredHeath1** [comment]
Ok, thanks Daniel. I'll look around and let you know when I get it figured out.
