### ISSUE TITLE
Next up video should be in the same category 

### ISSUE THREAD

**Issue by honeyfairy** [WWBN/AVideo#1690]
I have many categories of videos.
So I have:

**Training Videos**
-UBNT Training videos
-Mikrotik Training Videos

**Marketing videos**
-ITECH Marketing for fiber
-Wireless marketing videos

Now, when a user clicks on Mikrotik Training Videos then when the video is finished the autoplay and next video shown in in another random category like UBNT or wirelss or some other category.

**My Question**
**How can I make it that the next video shown is only from the Same category?**

**Comment by DanielnetoDotCom** [comment]
try to check this 

![image](https://user-images.githubusercontent.com/18009293/56925715-79144e00-6aa6-11e9-8762-ae97a2817343.png)
