### ISSUE TITLE
Mobile player has 

### ISSUE THREAD

**Issue by honeyfairy** [WWBN/AVideo#1694]
![mobile](https://user-images.githubusercontent.com/17691989/56898442-54fa4200-6a91-11e9-992c-33f2e0be93bf.PNG)

Thats how the seek bar looks in mobile. I am sure that its not supposed to look like that!
One can hardly seek!

How do I make the seek bar long?

**Comment by DanielnetoDotCom** [comment]
For you you will need to disable some buttons plugins on your site
