### ISSUE TITLE
Live stream without being logged in...

### ISSUE THREAD

**Issue by davidjmaxey** [WWBN/AVideo#1697]
I keep having users report that the system will not let them view our live steam unless they first create an account and are logged in. If there a way to disable this? Or is something else forcing them to be logged in to view the live stream? Our live stream link is here. https://watchnow.trinitywired.com/plugin/Live/?c=Trinity

**Comment by DanielnetoDotCom** [comment]
How is this on your Livestream configuration?
![image](https://user-images.githubusercontent.com/18009293/56974266-e5458f00-6b44-11e9-88ce-cae14dfa030b.png)
