### ISSUE TITLE
Add multiple videos to a playlist

### ISSUE THREAD

**Issue by honeyfairy** [WWBN/AVideo#1698]
How do I add multiple videos at one time to a playlist?

So I have 100 videos, named like
Ertugrul 1
Ertugrul 2
Ertugrul 3

And I go to My videos, search for Ertugrul and all the videos show up. Then I can select it and add it to Category or user group, but cannot add it to playlist.

How do I add all to playlist?

If the feature is not available, then give me some indicators of how I can do it via editing the MySQL tables

**Comment by DanielnetoDotCom** [comment]
@honeyfairy this feature is not available, and I can not teach you how to do it.

if you want to try to do it directly into MySQL you need to debug the code to find out how to do.

**Comment by honeyfairy** [comment]
Thats helpful
