### ISSUE TITLE
strange main page after upgrade to 7.1

### ISSUE THREAD

**Issue by nfsiv** [WWBN/AVideo#1711]
good day daniel,

this morning i did a rebuild of my site, after a fresh installation, everything works good, because no video uploaded, so i cannot see any issue. but after i upload my first video, i found a thing quite strange.
as i make video inactive after upload, so after first video uploaded, i can see it under the admin menu, then i make it active, but i cannot see it at once on the first page, after about 5 minutes i can see it on the first page. i also tried delete the video, then first page still have it and it will gone after few minutes.

and i also tried, if after i make the video active then sign out, i can see the video on the first page, and can be viewed. but if i sign in again, the first page will show no videos.

so could you have a look?
thanks

**Comment by DanielnetoDotCom** [comment]
You probably have your cache plug-in enabled .

They to disable it and test it

**Comment by nfsiv** [comment]
yes, you are right, if i disable the cache, the video will be popup after i make it active. 

but in my mind, before the current version, even i enable the cache, i have not see such thing.
