### ISSUE TITLE
Video not playing on latest chrome Android Pie

### ISSUE THREAD

**Issue by Bass850** [WWBN/AVideo#1712]
Hi,

I tried playing videos (mp4 and webm) on latest chrome browser player in Android 9 (in my case Samsung Note 9, tried colleagues Samsung S10 same problem).

Video's play fine on PC browser and even on Adblock browser. It also plays fne on chrome with older Android 7.0 device.

Video player shows video first screen. We can drag slider and it shows frames but will not play.

Problem is reproducable with demo.youphptube.

Please advise since we need videos to play on android devices...

**Comment by DanielnetoDotCom** [comment]
I also use android and I have no problem on play them.

did you try a different network?

**Comment by Bass850** [comment]
Yes I did try that.

BTW i did get relief on this by changing setting in CustomizeAQdvanced, option 'disableYoutubePlayerIntegration' but I don know what iḿ missing otherwise because of this s setting.

**Comment by DanielnetoDotCom** [comment]
I see, are you talking about play an embed video?

**Comment by Bass850** [comment]
No i am talking about opening YouPHPtube frontend (http://[ip]/youtubephp) and then playing any video shown. Player is shown (even google cast button etc). I can even move slider under video and see frames in video but it will not play.

**Comment by DanielnetoDotCom** [comment]
can you share your site/video link?

**Comment by hanx-phy** [comment]
Hi I also have a video(but not all) cannot play on android 9. 
You can check by 
http://104.238.151.254/YouPHPTube/video/sun-set-in-weihai-shandong

**Comment by DanielnetoDotCom** [comment]
Hi, Looks like was a problem on the encoding process.

I got this message on your video.

**Media resource http://104.238.151.254/YouPHPTube/videos/_YPTuniqid_5d39938f8208e1.18443052_HD.mp4 could not be decoded.**

Maybe the video source was corrupted already

**Comment by hanx-phy** [comment]
@DanielnetoDotCom thanks for reply

I built the sites twice because I'm a beginner and just made some mistake at first time. So I also uploaded these videos twice for test.

At first time, another video cannot play by my phone. So that means this problem happened twice during about  10 videos' encoding.

I think this is too frequent

**Comment by DanielnetoDotCom** [comment]
There is a way you can reproduce it on our demo site?

https://demo.youphptube.com/
