### ISSUE TITLE
Multiple Icons for "My Videos"

### ISSUE THREAD

**Issue by brandonjohnson** [WWBN/AVideo#1713]
When any user is logged in, under the "My Videos" left menu item, there are two icons displayed. Can you please remove the headphones icon?

Further more, can the menu be edited to allow admin to change the icon for any of the menu items?

I understand it would be unwise to delete or remove the menu items, but could a feature be added to allow me to change the titles of the menu items?
<img width="329" alt="Screen Shot 2019-05-07 at 2 08 48 PM" src="https://user-images.githubusercontent.com/667375/57333453-bcd40c80-70d1-11e9-8586-59efe818454c.png">

**Comment by DanielnetoDotCom** [comment]
you right, if you know css you can hide the icons
