### ISSUE TITLE
Categories Error

### ISSUE THREAD

**Issue by brandonjohnson** [WWBN/AVideo#1717]
I have a category I cannot delete, I assumed it was because there were videos associated with it. (I was able to make a new category and delete it no problem, with no videos associated) So I deleted the videos, and made sure cache was turned off in plugins (it is/was) and the category is still showing as having 5 videos but when you go to videos there are none and when you visit the homepage it is blank (no videos)

Can I disable categories entirely? I dont want to use the feature at all, was hoping by deleting the videos that used the feature, I would essentially disable it.

**Comment by DanielnetoDotCom** [comment]
what is the category ID, I am not sure, but I guess the category #1 can not be deleted. it is the default category.

if everything fails it fall back to this category :)

**Comment by brandonjohnson** [comment]
If you could use .class designations for things like "Categories" and "Description" instead of just labeling them that inside <strong> elements, it would be easy to just display:none; them (at least for me, the user - without having to edit core files) 

Honestly, I have noticed a lot of <div> elements that have no class designators which makes it tough to customize without losing updates in the future.

**Comment by spqr1** [comment]
This was posted prior #1752 but was told was expected behavior. Crappy I know but it's how the house here runs.

**Comment by spqr1** [comment]
alsothe system does not recognize nor accept  '  & 'in the name .

Ie. 

Bed & House
