### ISSUE TITLE
different ads on header and client option

### ISSUE THREAD

**Issue by alimusa80** [WWBN/AVideo#1720]
![82c4f3ec-46e9-11e7-8d31-f76e83334466](https://user-images.githubusercontent.com/23726861/57421377-cd889d80-720b-11e9-8e3a-6292b6187208.png)

is there away to work around and put ads bellow the client option i figure it out header without using you auto ads on script, i know you have build system that let put ads both header and client option at the same time but i want to have different ads header and the client option that is why i am looking way to bypass

**Comment by DanielnetoDotCom** [comment]
Hi, sorry, it is not clear to me what ads are you looking for.

if you can, please explain with some screenshots

**Comment by alimusa80** [comment]
I am I don't want to use one code ads for header and user client option , ex I want to use ads x on header and ads F on client option under how can i  set it up sir, i have did my self but i wanna know if it simple way to do it

**Comment by DanielnetoDotCom** [comment]
Sorry, I still don't understand.
