### ISSUE TITLE
cant sign in

### ISSUE THREAD

**Issue by moses268** [WWBN/AVideo#1721]
after signing in it goes back to the default page with out the profile signed in

**Comment by DanielnetoDotCom** [comment]
can you please check if your server has the disk full?

**Comment by moses268** [comment]
Ok

**Comment by moses268** [comment]
It is still not working. I have another server on the same account and it
is working properly. Something is wrong with the site

**Comment by DanielnetoDotCom** [comment]
not, sure for some reason the session is not persisting.

make sure your browser allows cookies from this site.

if you want to share the site and the credentials for us to test the login.

also check your error log file for some clue

**Comment by DanielnetoDotCom** [comment]
As I told you your server is full


![image](https://user-images.githubusercontent.com/18009293/57782781-46ec2880-7703-11e9-948a-c83ae5d5e876.png)


I have warned you. Your server has a very low resource and only 7,7 G of drive.

**Comment by moses268** [comment]
Ok noted. Yes when u told me I increased it from the free server but I
guess I need to increase it more.

**Comment by DanielnetoDotCom** [comment]
The thing is, even if you increase the drive size of your server, your OS will not recognize it automatically.

you need to run some commands to resize your partition table, but to do this you will need to Google or ask the AWS support for help or you will need to reinstall all your OS again

**Comment by moses268** [comment]
Ok noted ..
