### ISSUE TITLE
additional directory for storage

### ISSUE THREAD

**Issue by tuxtechno** [WWBN/AVideo#1726]
I have 4 TB of videos for which i would like to use YouPHPtube in intranet, i have entry level server PC with with 2 TB x 2 HDD, how can set different path once storage is full on 1st HDD, please guide

**Comment by DanielnetoDotCom** [comment]
The 2 x2tb drive is to be used as a Raid drive , you can not use it to fill one drive the fill the other

**Comment by tuxtechno** [comment]
I will not use RAID, as i will be using these drives separately, so i will create two folder one each drive, once 1 drive is full, i will store further videos on 2nd drive.

**Comment by TLCReuver** [comment]
Is it an idea to store the videos in subfolders related to the records (Id_Tag) like:

Folder 1 (Record 1-999)
Folder 2 ( Record 1000-1999)
Folder 3 (Record 2000-2999)
etc ect.

Advantage is that you only have to backup the last folder and you can create an symbolic link to several harddisks.

**Comment by tuxtechno** [comment]
is anyone having experience is using MergerFS for youPHPtube storage folder, it seems to be solution for extension of space using multiple physical drives, without any modification with youphptube working but i am worried about performance degradation

@DanielnetoDotCom 
Please comment your views on this
