### ISSUE TITLE
PayPalYPT plugin 

### ISSUE THREAD

**Issue by partystreamsk** [WWBN/AVideo#1732]
Hi, after i have installed wallet and configured PayPalYPT plugin i have error. Bitcoin payments work fine but after i try to add funds by paypal i get modal window " Sorry! Error! "

**Comment by DanielnetoDotCom** [comment]
check your log file, you may find some clue there https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by fyudelgado** [comment]
How does the PayPalYPT works? I didnt see any option on the videos to subscribe and made a payment for that. Could you help me?

**Comment by DanielnetoDotCom** [comment]
Hi @fyudelgado I guess you are looking for this https://github.com/YouPHPTube/YouPHPTube/wiki/Monetization:-How-To-Make-Money-on-YouPHPTube#paid-content
