### ISSUE TITLE
Error sending test mail

### ISSUE THREAD

**Issue by charliedaps1** [WWBN/AVideo#1734]
Hello,

I configure the mail and I have this error message.

I tried with my smtp and with the gmail smtp.

Always the same message.

"Your message could not be sent!
The email is invalid"

Do you have an idea ?

Thanks by advance

**Comment by Puyodead1** [comment]
Check youphptube logs
https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube
