### ISSUE TITLE
could i request random video played on home page refresh

### ISSUE THREAD

**Issue by joey2354** [WWBN/AVideo#1735]
hi there, could i request random video played on home page after/on refresh please on next update.

thank you !

**Comment by DanielnetoDotCom** [comment]
what theme are you using?

Gallery?

**Comment by joey2354** [comment]
https://i.imgur.com/r7di5Zg.png
i think it's called paper ?

**Comment by DanielnetoDotCom** [comment]
Sorry, I mean first-page mode:

Gallery or Netflix or YouTube?

**Comment by joey2354** [comment]
hi there, is this something you may be doing sometime ?

**Comment by DanielnetoDotCom** [comment]
I will do it for sure, some day

**Comment by joey2354** [comment]
ok thank you man
