### ISSUE TITLE
Unable to update -- git issue

### ISSUE THREAD

**Issue by angelawong** [WWBN/AVideo#1737]
When I used the git method to update, I get this error message:
$ cd /var/www/html/YouPHPTube
$ sudo git pull
fatal: Not a git repository (or any of the parent directories): .git

When I first install the application, I downloaded the zip file from the site. My current version is 6.8 and my Linux distribution is Debian 9.

Thanks so much.

**Comment by Commifreak** [comment]
When you use git method to update, you should have used the git method to install as well. You are missing the .git folder, as described. Without git folder there is no update possible.

Install from git: `git clone https://github.com/YouPHPTube/YouPHPTube.git .` and move `/videos` folder back to new installation (where config and videos are.
After that `git pull` should bring you to the latest HEAD-Version.

**Comment by angelawong** [comment]
Thank you so much. I will give it a go.
