### ISSUE TITLE
embed ads into the right part

### ISSUE THREAD

**Issue by gchenfly** [WWBN/AVideo#1746]
hi.
I want to embed ads into the right part, before the up next.
see the attach photo.
where is file i can edit?
<img width="458" alt="屏幕快照 2019-05-22 10 43 39" src="https://user-images.githubusercontent.com/34537998/58143816-b53e6700-7c7e-11e9-8339-67b28f8620a2.png">

**Comment by DanielnetoDotCom** [comment]
I guess if you use an Adsense code the default behavior is to have an add there.

check the demo site

![image](https://user-images.githubusercontent.com/18009293/58172414-e878fa00-7c6e-11e9-8895-1c84169a03c8.png)
