### ISSUE TITLE
Direct links

### ISSUE THREAD

**Issue by jsmits76** [WWBN/AVideo#1753]
I have hundreds of MP4 files on my server. I would like to add them without having them encoded again. The "embed video link" is not working for me. I save a link and it disappears right after closing the window.

What is the best solutions for me?

**Comment by DanielnetoDotCom** [comment]
Hi, embed video link suppose to work. can you please share an mp3 link sample so we can test?

**Comment by jsmits76** [comment]
It is an MP4 file: http://95.216.116.126/testvideo.mp4

It is added but the box with the URL is still shown. The box dissapears and so does the added video.

**Comment by jsmits76** [comment]
Might had been a problem with the ab blocker of my browser. I am still testing but looks like that was the problem...

J.

**Comment by DanielnetoDotCom** [comment]
I just detect a problem on direct links

I also just sent a fix

**Comment by jsmits76** [comment]
Looks like my website is blocked because of adult content. No problem with that. I just can install the encoder on my server and run it or is this content always a no-go?

**Comment by DanielnetoDotCom** [comment]
No, is forbidden to use YouPHPTube, plugins or encoders  for adult content
