### ISSUE TITLE
about import local videos

### ISSUE THREAD

**Issue by venano** [WWBN/AVideo#1755]
Hi, I`ve got many tutorial videos,how can i upload quickly, I noticed there is an option，Import Local Videos，but I think it doesn't work, I built this YouPHPTube at a Ubuntu Linux server and When I was trying to get the path up and click List Files, nothing happened, I`ve tried both Windows and Linux system. I need to do some watermarking for my video，and it`s all MP4 files. Is there any problem with my configuration? thx!

**Comment by spqr1** [comment]
you need to create a DIR in root where the encoder resides

Example:
sudo mkdir /somedir

Took me a while to figure it out too

**Comment by DanielnetoDotCom** [comment]
YouPHPTube is developed for Linux, so, you should avoid windows.

if is not listing you should look into your encoder log file.
