### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by JDucommun** [WWBN/AVideo#1762]
Just a suggestion:  You would TRIPLE your income if you made this work with Cpanel / WHM Servers.

Do you realize the so very few percentage of the population that use specifically Ubuntu?

![Screenshot_5](https://user-images.githubusercontent.com/5632064/58340221-4f3a1700-7e19-11e9-8235-ce555f830a78.jpg)

**Comment by spqr1** [comment]
on the enduser side yes... but definitely not server side

> According to IDC [1], 47.9% of the servers worldwide ran Windows Server whereas 40.5% ran Linux. W3Techs [2] ran a survey this month, which checked the top 1 million Web servers (according to Alexa) and 64.9% of them were running Unix/Unix-like operating systems, 35.2% were running Windows and less than 0.1% were running Mac.

**Comment by JDucommun** [comment]
That may be true server side, but most people use CPanel and not bash ... therefore it would stand to reason a smart move would be to make a CPanel / WHM App out of it ... or at least make it compatible instead of using a "localhost" installer and expecting us idiots to be able to follow along ...

**Comment by JDucommun** [comment]
I've not paid for a server yet that used "Sudo App Get"  not a CPanel one anyhow.

**Comment by spqr1** [comment]
Amazon offers a free tier for all on AWS :)

**Comment by JDucommun** [comment]
I bet thats limp ...

**Comment by spqr1** [comment]
can run this app as  a test bed though
