### ISSUE TITLE
jqeury datepicker is not a function (error admin panel)

### ISSUE THREAD

**Issue by slaapkopamy** [WWBN/AVideo#1763]
Hi there, i saw mine admin panel is not more working after i uploaded a test video. I get the error in chrome console uncaught typeerror $(...) flagstrap is not a function and the same as datepicker.

screenshot: https://slaapkopamy.com/sc/images/6qa0oM5.png

update: i'm running version 7.2 fresh install (not really fresh anymore but yesterday installed)

for more information just ask

**Comment by DanielnetoDotCom** [comment]
Check your error log, for sure you have some fatal error
