### ISSUE TITLE
The requested URL /YouPHPTube/user was not found on this server.

### ISSUE THREAD

**Issue by cgavaller2** [WWBN/AVideo#1767]
I have mod rewrite enabled, and all the right code in the apache2 config. this usually is resolved just by setting rewrite to enabled and changing the code, but not in my case.

**Comment by spqr1** [comment]
can you look into logs from youphptubelog and paste any errors here?

**Comment by cgavaller2** [comment]
I deleted cache, same issue. How do I go by checking the logs?

**Comment by spqr1** [comment]
/videos/youphptube.log

**Comment by DanielnetoDotCom** [comment]
@cgavaller2 looks like you do not have mod_rewrite enabled or you did not copy the .htaccess

**Comment by cgavaller2** [comment]
I have enabled mod_rewrite, and I have .htaccess. I also have restarted apache multiple times, but ill check the logs now.

**Comment by cgavaller2** [comment]
There is no log file in the videos directory

**Comment by cgavaller2** [comment]
I should also mention that when installing ubuntu I had it installed on a 160GB drive, and then set the /var/ path to a 500GB drive, would this cause any problems? I wouldn't suppose so

**Comment by DanielnetoDotCom** [comment]
@cgavaller2 Looks like your installation is not even close to being completed.

what is your server specifications?

**Comment by cgavaller2** [comment]
an Athlon 2 core cpu (unknown) from 2008, onboard nvidia graphics, 2 160 GB IDE hard drives, one 500 GB SATA Drive. I know the specs are terrible, but i'm planning on upgrading in the future.

**Comment by DanielnetoDotCom** [comment]
I am asking about Linux version

**Comment by cgavaller2** [comment]
16.04, it wouldn't work on 18 for me

**Comment by DanielnetoDotCom** [comment]
16.04 is fine 

Did you use the git clone command?

Avoid upload the files, prefer to use git

**Comment by cgavaller2** [comment]
I just used this code:

"sudo apt-get install apache2 php7.0 libapache2-mod-php7.0 php7.0-mysql php7.0-curl php7.0-gd php7.0-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube.git && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube-Encoder.git && sudo apt-get install python && sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl && sudo a2enmod rewrite"

**Comment by DanielnetoDotCom** [comment]
yes, looks like you use git.

check the /var/logs/apache2/error,log

you may find something there

**Comment by cgavaller2** [comment]
I just got a new server to run the streamer and encoder on, Can you run both the streamer and encoder on windows? Thanks

**Comment by DanielnetoDotCom** [comment]
No, it must be Ubuntu
