### ISSUE TITLE
Custom work - Amazon Elastic Transcoder

### ISSUE THREAD

**Issue by spqr1** [WWBN/AVideo#1769]
I feel at present that there is a scalability issue with regards to encoding files and such due to costs of resources to encode and manage etc...

What would the costs be to have a plugin created so the app can encode using Amazon Elastic Transcoder?

[AWS LINK](https://aws.amazon.com/elastictranscoder/)

Thoughts/feedback welcome on the subject

**Comment by DanielnetoDotCom** [comment]
I have this in mind, I agree with you this would be a good idea.

I still have not deep look on it yet. but I will :)
