### ISSUE TITLE
Unable to change any general settings

### ISSUE THREAD

**Issue by Yukkun** [WWBN/AVideo#1776]
I'm unable to change any settings under Settings/General Settings on admin account. When I change the setting to what I prefer and press save, at first it does look like it saves it. But when I reload the page or go back to the page, it changes back to the default settings.

EDIT: These settings do work through advanced options, which atm kinda defeats the purpose of having simpler settings

**Comment by DanielnetoDotCom** [comment]
Hi

are you saying it does not work on the Admin panel but works on plugins page?

**Comment by Yukkun** [comment]
Yes. For some reason it works only through the plugins page when I enable CustomizeAdvanced and CustomizeUser and edit parameters through the plugins page

**Comment by heme007** [comment]
Eu desinstalei o plugin live e voltou a funcionar perfeitamente.

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: YouPHPTube <notifications@github.com>
Enviado: Wednesday, August 28, 2019 9:46:46 AM
Para: YouPHPTube/YouPHPTube <YouPHPTube@noreply.github.com>
Cc: heme007 <hlgmax@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [YouPHPTube/YouPHPTube] Unable to change any general settings (#1776)


@heme007<https://github.com/heme007> deve ser algum erro javascript

de uma olhada no seu console javascript e no log de erros do seu servidor.
