### ISSUE TITLE
Feature Request: Oembed Support

### ISSUE THREAD

**Issue by patriclougheed** [WWBN/AVideo#1777]
It would be great if this fantastic video sharing platform made it even easier to share videos by adding Oembed spec support. Not all sites allow iframe and using Oembed makes it possible to embed the video with just a link:

https://wordpress.org/support/article/embeds/#oembed

https://oembed.com/

**Comment by DanielnetoDotCom** [comment]
That rocks, thanks

How do I test an oembed URL?

**Comment by patriclougheed** [comment]
https://oscarotero.com/embed3/demo/

This site/code gathers all embed info from a link
