### ISSUE TITLE
YouPHPTube stream Server installation

### ISSUE THREAD

**Issue by spider988** [WWBN/AVideo#1780]
I tried to install the script on my Vps server under the youme.tube/YouPHPTube/install page.
It seems that everything is fine but when I go to install it gives me error on the website. I read a lot about the forums and I think I should insert them in

YouPHPTube / videos /configuration.php

the name of the site.

Where can I find this string?

**Comment by DanielnetoDotCom** [comment]
Will be easier if you place your error here.

also, check your apache error log.
