### ISSUE TITLE
Problem after updating 30 min ago from this issue

### ISSUE THREAD

**Issue by Cadosh** [WWBN/AVideo#1784]
Hello
my website goes down after the update and i don't know why 
what i did is exactly as you explained in this article
https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-Update-your-YouPHPTube
and i'm sure i did miss nothing
please check my website softytube.com and see what happened exactly
thank you

**Comment by DanielnetoDotCom** [comment]
Hi, your videos directory is not on the default directory.

I just disabled the dynamic URL generated on your configuration.php file

I add the false on the if below

<?php
$global['configurationVersion'] = 2;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
if(**false &&** !empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP))$
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'https://softytube.com/';
}

**Comment by DanielnetoDotCom** [comment]
<?php
$global['configurationVersion'] = 2;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
if(false && !empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP))$
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'https://softytube.com/';
}

**Comment by DanielnetoDotCom** [comment]
```
<?php
$global['configurationVersion'] = 2;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
if(false && !empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP))$
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'https://softytube.com/';
}

```

**Comment by Cadosh** [comment]
should i do that every time i update to a new version ?

**Comment by DanielnetoDotCom** [comment]
No, this time we had an update on the configuration.php

you use a non-standard configuration.php that is why you got the error
