### ISSUE TITLE
LOGIN - page missing user input, all I have is password

### ISSUE THREAD

**Issue by streamlifetv** [WWBN/AVideo#1788]
Just installed youPHPTube.  Appears to be missing part of login, and only part of header is shown.  I cannot login, no user input.

Any ideas?

Thanks,

John

**Comment by republicus** [comment]
I did not have that problem and I just installed my YouPHPTube on my VPS with the latest.
Have you tried repeating the install?

I installed onto Ubuntu 16.04 using the instructions [HERE](https://youphptube.readthedocs.io/en/latest/install/installUbuntu16.html)

My install was a separate streamer from the encoder. The above instructions worked until I configuring the encoder which I used [THESE](https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x-For-YouPHPTube-version-4.x-or-newer) instructions for some missing steps.

**Comment by DanielnetoDotCom** [comment]
@streamlifetv can you screenshot your screen?

also check the log file.

**Comment by streamlifetv** [comment]
This is my fourth time trying to install youPHPtube on UBUNTU without a 
cpanel it is tough to get a website set up.

I was able to get it installed partially here on my Centos server, I 
will point cloudflare there so you can see it:  I want to put everything 
in public_html folder and not have excess folder links.

Here is the link: http://streamlife.tube/

But, without cpanel there is no way to create a domain name link to work 
on UBUNTU....I need to have a way to share the video with our 
MEDIACONTROL PANEL for wowza.  I hope to be able to produce tv channels.

What will be costs for install, including NGINX and plugins for linking 
to my centos server all video files?

Thanks,


John

**Comment by DanielnetoDotCom** [comment]
Hi, 

I am not sure what do you mean with a "domain name link"

But all our installations include an SSL certificate on your YouPHPTube domain
Unfortunately, we only make installations on Ubuntu Servers
please check it here https://www.youphptube.com/services
