### ISSUE TITLE
mass download videos on youphptube with api key youtube

### ISSUE THREAD

**Issue by spider988** [WWBN/AVideo#1791]
I can in wordpress through plugins to make mass downloads of youtube videos. Is it possible to do this in youphptube? strange that I find nothing about it This is the main thing. Making embedding only through links is not very useful. In phpvibe this exists. Is there the same functionality in youphptube?

**Comment by DanielnetoDotCom** [comment]
The do not have mass download, they have mass embed, we may add this in the future.

BTW you can mass download a channel from youtube. just paste the channel link

**Comment by xemtube** [comment]
The function of mass batching a channel from youtube is very good. You develop this function soon.
