### ISSUE TITLE
Dashboard metrics missing

### ISSUE THREAD

**Issue by republicus** [WWBN/AVideo#1792]
I am reviving this issue because my dashboard appears identical to the OP of this issue. My account has videos with views but several charts are missing data. Admin dashboard appears the same for all videos.

![dashboard](https://user-images.githubusercontent.com/47370709/59212764-410e2980-8b81-11e9-84b7-fb79ef582638.PNG)

My reply did not reopen the issue so I am creating this new issue.

_Originally posted by @republicus in https://github.com/YouPHPTube/YouPHPTube/issues/170#issuecomment-500499530_

**Comment by DanielnetoDotCom** [comment]
Please check your log file

**Comment by republicus** [comment]
I am getting no errors when viewing the user or admin dashboard/charts. I checked videos/youphptube.log and /var/log/apache2/error.log

I also cleared the cache folder and the results remain. No errors. No data populating the three charts as pictured.

**Comment by republicus** [comment]
I reduced my admin account to a regular user and suddenly the charts filled in the data.
I cleared my browser cache and made the account an admin again and the charts are blank again ;(

I checked again your demo sight and saw that your admin account sees the charts, too.
So I installed another server running PHP 5.6 instead, and both admin and regular users see their video charts.

**Comment by republicus** [comment]
Actually.. I think i just figured out the problem. I believe its been going on since at least since Oct. 2017 as posted in issue #170 

The problem is the charts are showing the **admin USER** data. Not the admin **GROUP data**.
I just assigned a video's owner to the intially created admin account and now all admin accounts are showing in the charts the data for that one video.

The only reason it appears correct at demo.youphptube.com is because Daniel's account is the admin account.

![phptube-charts](https://user-images.githubusercontent.com/47370709/59414103-e813e080-8d8e-11e9-8da8-bb26f203fd84.PNG)
