### ISSUE TITLE
The next auto-play function does not work.

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#1795]
Currently I turn on the next auto-play function, but when the current video finishes playing, it will not automatically continue to the next video. Something has happened with this function, you can fix it for me. is not
![Loi phat tu dong](https://user-images.githubusercontent.com/50126312/59432251-1803c800-8e11-11e9-9939-225ef72c9180.png)

**Comment by DanielnetoDotCom** [comment]
I see, but this feature does not work for embed videos at the moment.

we are looking for a way to improve it.
