### ISSUE TITLE
Video automatically booked

### ISSUE THREAD

**Issue by mrtick2002** [WWBN/AVideo#1798]
Is there a way to keep this from showing up as soon as you click the "Upload MP4" tab? The issue is that as soon as the video finishes uploading, the system sends an email letting subscribers know that "Video automatically booked" has been uploaded and not the actual name of the video.

Here is a screenshot of what I mean. http://prntscr.com/o3hrcj

**Comment by DanielnetoDotCom** [comment]
I did not find any other way for now, but I will keeping trying

**Comment by millzee01** [comment]
Hi, did this get fixed?

Am assuming we can simply mod javascript to grab the filename on and automatically put it into $("#inputTitle").val()

**Comment by DanielnetoDotCom** [comment]
I guess with the update I just sent if the video is "Video automatically booked" it will be set to inactive and will not notify users
