### ISSUE TITLE
 I can not upload videos and I can not make live stream!

### ISSUE THREAD

**Issue by Skyybr12** [WWBN/AVideo#1799]
I can not upload videos and I can not make live stream!
when I try to start a live stream the following error appears in my obs studio, failed to connect to the server
I really do not know what else to do, could someone please help me?
my YouPHPTube is http://149.56.79.248/YouPHPTube/
my encoder http://149.56.79.248/YouPHPTube-Encoder

**Comment by mrtick2002** [comment]
I can't either. All I get is a blank screen. I was finally able to get the livestream going, but uploads are a no go.

**Comment by DanielnetoDotCom** [comment]
@Skyybr12 check your nginx error log file, should be some clue there.

also how is your nginx.conf?
