### ISSUE TITLE
Questions from newbie

### ISSUE THREAD

**Issue by soapstreams** [WWBN/AVideo#1802]
1. I want to my members to be able to monetize their own videos. Is there a way to do that?
2. Does the encoder compress the videos? If so, by how much?

Thanks.

**Comment by DanielnetoDotCom** [comment]
Hi

1. https://github.com/YouPHPTube/YouPHPTube/wiki/Monetization:-How-To-Make-Money-on-YouPHPTube
2. No, it creates 3 different resolutions of the same video (Low, SD and HD),  so you will probably use more space than the original video

**Comment by soapstreams** [comment]
Is that the only purpose of the encoder? Using the encoder seems to be the only way for my users to upload multiple video files at once, is that right?

**Comment by DanielnetoDotCom** [comment]
Yes , for now that is the best way

Please check this https://github.com/YouPHPTube/YouPHPTube/wiki/About-Video-Upload
