### ISSUE TITLE
Error deleting user: Cannot delete or update a parent row: a foreign key constraint fails

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#1808]
I will leave one screenshot of the error . I've seen 3 topics talking about the same error, but they were from 2017 ... So I want to re-open the topic if there's any solution.
![header](https://user-images.githubusercontent.com/52116577/59970380-ae945f80-955c-11e9-919c-68eae6c6b3b3.jpg)

Answering some common question from old threads :

1)Try to delete it manually
+Did it already and getting the same error
2)Give more privileges to the user database
+Did it and and still the same error ( mysql -u root -p mysql
> grant all privileges on DATABASE_NAME.* to USERNAME@localhost identified by 'PASSWORD';
> flush privileges;
> \q
Ofc replacing the hyper with my data
3)When this error appears?
-While installing for the first use

Additional information , I'm running the server locally on my dedicated server machine for test purposes

Thanks for the help , if anyone knows how to fix this issue , I'll appreciate it

**Comment by DanielnetoDotCom** [comment]
About the screenshot above, try to drop the database

About delete users, the results are unpredictable, users were not made to be deleted. you can inactivate them

**Comment by akhilleusuggo** [comment]
> About the screenshot above, try to drop the database
> 
> About delete users, the results are unpredictable, users were not made to be deleted. you can inactivate them

Hello and thank you for the answer . Just to give you some extra infos , they may be helpful since I still can't run it according my needs 
1- I'm running on Ubuntu server
2- I'm using ISPConfig , witch uses PHPMyAdmin and DB Maria

Do you think the problem is coming from there ?
Because following your guide on how to create the server with XAMPP etc worked fine , so definitely the problem is coming from DB Maria ,  but I have no idea why
----------------------------------------------------------------------------------------------------------
I will like to give some ideas since I've been testing it for a shot time .
I know that you have implemented the ''switch quality'' , I appreciate your work , but it's really poor . Don't misunderstand me , I would like you to try this plugin https://wordpress.org/plugins/video-embed-thumbnail-generator/ . I KNOW , it's something from wordpress but it's also an open source . It uses the same one that you're using FFMPEG and has a lot more features that you provide . Let me show you some screenshots . It gives total customization of the server encoding etc . Take a look

![image](https://user-images.githubusercontent.com/52116577/60138857-ba259780-97a3-11e9-8883-4452ac551ca8.png)
![image](https://user-images.githubusercontent.com/52116577/60138891-dc1f1a00-97a3-11e9-87ea-15bbff7018a9.png)


*Uses video.js*

Feature of this plugin that you YouPHPTube doesn't have
1-Default video encode formats ( more advanced options )
2-Automatic generator thumbnails randomly ( It can as much random thumbnails as you want )
3-Add watermark to thumbnails
4-Add watermark to encoded files ( for original content it's great to make people know about your site )
5-Encode quality control method ( ### This os is crucial , since there's no were to change the encoding setting as far as i've seen , need to browse more to find the parameters )
  +Constant Rate Factor
  +Average Bit rate 

I could be writing more and more , so please I would recommend you to try it and when you got time try to implement some of this awesome feature .

Have a nice day Sr

**Comment by DanielnetoDotCom** [comment]
About your database, you probably have a custom database name, you will not be able to create the database, you should choose the option to only create tables.

thanks for the ideas


> 1-Default video encode formats ( more advanced options )

You can customize your FFMPEG on encoder configurations page.
![image](https://user-images.githubusercontent.com/18009293/60214762-821e6300-983c-11e9-97d4-27cebb350364.png)

> 2-Automatic generator thumbnails randomly ( It can as much random thumbnails as you want )
> 3-Add watermark to thumbnails
> 4-Add watermark to encoded files ( for original content it's great to make people know about your site )

Yes those are great ideas, I have this in mind

> 5-Encode quality control method ( ### This os is crucial , since there's no were to change the encoding setting as far as i've seen , need to browse more to find the parameters )
> +Constant Rate Factor
> +Average Bit rate

you can also add this on the encoder configurations

**Comment by akhilleusuggo** [comment]
> About your database, you probably have a custom database name, you will not be able to create the database, you should choose the option to only create tables.
> 
> thanks for the ideas
> 
> > 1-Default video encode formats ( more advanced options )
> 
> You can customize your FFMPEG on encoder configurations page.
> ![image](https://user-images.githubusercontent.com/18009293/60214762-821e6300-983c-11e9-97d4-27cebb350364.png)
> 
> > 2-Automatic generator thumbnails randomly ( It can as much random thumbnails as you want )
> > 3-Add watermark to thumbnails
> > 4-Add watermark to encoded files ( for original content it's great to make people know about your site )
> 
> Yes those are great ideas, I have this in mind
> 
> > 5-Encode quality control method ( ### This os is crucial , since there's no were to change the encoding setting as far as i've seen , need to browse more to find the parameters )
> > +Constant Rate Factor
> > +Average Bit rate
> 
> you can also add this on the encoder configurations

I don't have those option that you have . 
In my encoder I can see only ''Sharing Queue and Queue Logs'' I don't have the other options . Maybe there's something that i'm missing ?

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/YouPHPTube/YouPHPTube/issues/207#issuecomment-343358059

**Comment by akhilleusuggo** [comment]
> Check this [#207 (comment)](https://github.com/YouPHPTube/YouPHPTube/issues/207#issuecomment-343358059)

hello thanks for the reply , I see what you have done , but since I'm not familiar with it , I don't even know how to open that location of the db with the installation method that you provided on your guide . That's why I prefer PHPMyAdmin where things are clear .
How can I get into the DB ? Anyway thou the browser ? Or how it's done ?

**Comment by DanielnetoDotCom** [comment]
you can use PHPMyAdmin to do it. but you need to know how to deal with tables and the databases

**Comment by akhilleusuggo** [comment]
I will try to fix that . I'm having 3 computers at home , i've set up the /YouPHPTube-Encoder-Network-master/
I wanna report some bugs , error that I have found
1- This is it's happening to everybody I guess . When one of the encoding servers is down , it shown as the recommended encoding server
2- This it's maybe happening only to me . Uploading video from youtube , got encoded , everything nice . But when uploading videos from the computer , the video got uploaded but the encoding doesn't start . The same happens on the Bulk Encode BUT only on the YouPHPTube-Encoder-Network-master/ , what I mean with that is , the encoding that is located on the main stream server works fine for basically everything except when I upload , the others just not working , except for the youtube import videos
