### ISSUE TITLE
Site problems

### ISSUE THREAD

**Issue by soapstreams** [WWBN/AVideo#1811]
My site is hosted through you. I bought the Customize and Secure Directory plug-ins and installed both. When I went to edit the parameters for the Secure Directory plugin, I ran into a few problems. I installed libapache2-mod-xsendfile without a problem, but there was no "<Directory /var/www/html/YouPHPTube/>" at all in my apache2.conf to add "XSendFile on" and "XSendFilePath /var/www/html/YouPHPTube/" to. So I just copied and pasted the whole thing in:

<Directory /var/www/html/YouPHPTube/>
    Options Indexes FollowSymLinks
    XSendFile on
    XSendFilePath /var/www/html/YouPHPTube/
    AllowOverride All
    Require all granted
    Order Allow,Deny
    Allow from All
</Directory>

I went into the .htaccess file as instructed to uncomment the "RewriteRule," but it wasn't commented at all. So I just left that as is.

When I went to my site, soappirat.es, the page was slow to load and most of the animated GIFs generated by the encoder and stored in the /videos directory (is that right?) wouldn't load. So I backtracked and undid everything. I disabled the secure directory plugin and deleted the "<Directory . . ." that I had added to the config file. I still couldn't get the site to come up right.

So I went into my .htaccess file and commented the part of the file I had been instructed to uncomment. That freed the GIFs to load, but still very slow and clunky. Sometimes, the home page won't load at all. In fact, I think it only loads through cache. I am afraid to empty the cache.

Can you help fix all this and get the secure directory plugin installed? Thanks.

**Comment by DanielnetoDotCom** [comment]
try to enable the plugin now

**Comment by soapstreams** [comment]
I have enabled the plugin, but I can't really tell whether it is working. My log shows the following error:

[25-Jun-2019 22:38:34 UTC] XSENDFILE ERROR: Not exists /var/www/html/YouPHPTube/videos/X-Sendfile.test


How exactly does this plugin worked? I had hoped it would be a way to hid the fact that the video files are stored on Backblaze, but in the Firefox browser, it still shows that data is being transferred from Backblaze.

jdr

**Comment by soapstreams** [comment]
Also seeing this in my log file while encoding videos:

[26-Jun-2019 01:57:21 UTC] XSENDFILE ERROR: Not exists /var/www/html/YouPHPTube/videos/_YPTuniqid_5d12cb97102b32.44153148.jpg

**Comment by DanielnetoDotCom** [comment]
If you are using backblaze this plugin is useless, you should disable it.

backblaze has his own token feature.

also, comment out the xsendfile line on .htaccess, it is useless for you and will save you some resources
