### ISSUE TITLE
Withdraw issues 

### ISSUE THREAD

**Issue by gvnut** [WWBN/AVideo#1813]
When someone requests a withdraw from their account, it will go to approval from the admin. But it does not hold that amount from the users account. So if a user has a balance of $100 and they request $100 for withdraw. Their account should show $0 while the withdraw request is pending approval. If the admin accepts, then nothing has to happen. But if it is denied, then the balance will go back to the users wallet balance. 

Right now someone can request a withdraw 10 times, making a ton of requests for the admin and make it confusing. Also a user can request a withdraw and then choose to transfer the amount to another user while the withdraw request is pending. Which could cause a double payment.

**Comment by DanielnetoDotCom** [comment]
on my installation, it holds the balance.

can you reproduce it on demo site?
