### ISSUE TITLE
site speed is slow

### ISSUE THREAD

**Issue by daniyalhasan** [WWBN/AVideo#1817]
Hi, I am seeing that YouPHPTube site is loading very slow on my server. Can you please help me? Also I want to stream videos with low latency so that I can reduce the delay in the video. Please help me with this.

**Comment by DanielnetoDotCom** [comment]
what is your server configuration?

CPU, RAM, DISK?

how many videos are you hosting?

**Comment by daniyalhasan** [comment]
I ma currently running t3.2xlarge of AWS. 
vCPUs 8, Memory- 32GB, DISK- 30GB
I am not hosting any video. There is no video in the site. I am using live stream feature. Is this possible, I can private message you my URL so that you can experience the side speed. Also do you have any good and easy tutorial for running the live stream at ultra low latency?

**Comment by DanielnetoDotCom** [comment]
reduce livestream latency you should try to find help on the RTMP NGINX repository 
https://github.com/arut/nginx-rtmp-module

To speedup try this https://github.com/YouPHPTube/YouPHPTube/wiki/Speed-up-your-page
