### ISSUE TITLE
Error on install on local machine

### ISSUE THREAD

**Issue by eriteria** [WWBN/AVideo#1820]
hey there, i was trying to install youphptube on my local machine running linux but its not working i've literally tried all solutions previously mentioned in other complaints but all to no avail. hope you can help

error log:
[Wed Jun 26 14:40:58.848210 2019] [mpm_prefork:notice] [pid 10554] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Wed Jun 26 14:40:58.848267 2019] [core:notice] [pid 10554] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jun 26 14:41:41.654214 2019] [php7:notice] [pid 10573] [client 127.0.0.1:57030] PHP Notice:  Undefined variable: global in /var/www/html/YouPHPTube/install/index.php on line 21
[Wed Jun 26 14:41:41.654310 2019] [php7:warn] [pid 10573] [client 127.0.0.1:57030] PHP Warning:  mkdir(): Permission denied in /var/www/html/YouPHPTube/objects/functions.php on line 158
[Wed Jun 26 14:43:04.475573 2019] [php7:notice] [pid 10591] [client 127.0.0.1:57046] PHP Notice:  Undefined variable: global in /var/www/html/YouPHPTube/install/index.php on line 21
[Wed Jun 26 14:44:21.875063 2019] [php7:notice] [pid 10573] [client 127.0.0.1:57060] PHP Notice:  Undefined variable: global in /var/www/html/YouPHPTube/install/index.php on line 21
[Wed Jun 26 14:45:25.518088 2019] [php7:error] [pid 10592] [client 127.0.0.1:57074] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/YouPHPTube/install/checkConfiguration.php:17\nStack trace:\n#0 {main}\n  thrown in /var/www/html/YouPHPTube/install/checkConfiguration.php on line 17, referer: http://127.0.0.1/YouPHPTube/install/index.php
[Wed Jun 26 14:46:09.888501 2019] [mpm_prefork:notice] [pid 10554] AH00169: caught SIGTERM, shutting down
[Wed Jun 26 14:50:06.864020 2019] [mpm_prefork:notice] [pid 1927] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Wed Jun 26 14:50:06.892742 2019] [core:notice] [pid 1927] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jun 26 14:50:13.285396 2019] [php7:notice] [pid 1946] [client 127.0.0.1:38882] PHP Notice:  Undefined variable: global in /var/www/html/YouPHPTube/install/index.php on line 21
[Wed Jun 26 14:50:31.096492 2019] [php7:error] [pid 1956] [client 127.0.0.1:38898] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/YouPHPTube/install/checkConfiguration.php:17\nStack trace:\n#0 {main}\n  thrown in /var/www/html/YouPHPTube/install/checkConfiguration.php on line 17, referer: http://127.0.0.1/YouPHPTube/install/index.php
[Wed Jun 26 14:50:41.970761 2019] [php7:error] [pid 1957] [client 127.0.0.1:38900] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/YouPHPTube/install/checkConfiguration.php:17\nStack trace:\n#0 {main}\n  thrown in /var/www/html/YouPHPTube/install/checkConfiguration.php on line 17, referer: http://127.0.0.1/YouPHPTube/install/index.php
[Wed Jun 26 15:59:24.572324 2019] [php7:error] [pid 1959] [client 127.0.0.1:39106] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/YouPHPTube/install/checkConfiguration.php:17\nStack trace:\n#0 {main}\n  thrown in /var/www/html/YouPHPTube/install/checkConfiguration.php on line 17, referer: http://127.0.0.1/YouPHPTube/install/index.php

![Screenshot from 2019-06-26 15-59-16](https://user-images.githubusercontent.com/51262474/60191262-f1d82200-982b-11e9-8d14-73d5bfdad3d0.png)
![Screenshot from 2019-06-26 15-59-22](https://user-images.githubusercontent.com/51262474/60191263-f270b880-982b-11e9-9f12-4e7db931ceca.png)
![Screenshot from 2019-06-26 15-59-28](https://user-images.githubusercontent.com/51262474/60191265-f270b880-982b-11e9-950e-02a04ec8b67a.png)

thanks a lot

**Comment by DanielnetoDotCom** [comment]
Google for that error and fix your local machine 

 `PHP Fatal error: Uncaught Error: Class 'mysqli' not found in `
