### ISSUE TITLE
Live streaming is always "offline"

### ISSUE THREAD

**Issue by foxinstone** [WWBN/AVideo#1824]
My YPT‘s version if V7.2 and it's fresh install.
I installed it according to the article "Set up my own Stream Server".except nginx version is 1.38.1，php-xml's version is 7.2.
I can use OBS to stream the stream normally:
![image](https://user-images.githubusercontent.com/35874666/60386415-1996e680-9ac7-11e9-9ba4-a73f65c685a8.png)
But no matter how I configure it, when I click the Live button, the page always shows "Offline":
![image](https://user-images.githubusercontent.com/35874666/60386464-a0e45a00-9ac7-11e9-8c69-d8badf37a3bc.png)

Why?
Please help me!

BTW, Other features are completely normal, and personal suspicions are related to SSL...

**Comment by foxinstone** [comment]
Now there is some progress:
I excluded the redirect by adding a server name,then,when i push a stream,the Offline became “online”,
and the number of displays in the list has also changed from "0" to "1".
But when I click the play button, it keeps spinning and can't play.
Why?

**Comment by DanielnetoDotCom** [comment]
Hi, 

looks like on the plugin you select the useAadaptiveMode mode.

uncheck it.

![image](https://user-images.githubusercontent.com/18009293/60402807-c4acac00-9b6a-11e9-826d-24bfa53cea9e.png)
