### ISSUE TITLE
Sticky videos?...

### ISSUE THREAD

**Issue by andreicaba** [WWBN/AVideo#1828]
Hi

  Is there any way to get some videos to be "sticky" on the first page (like some tutorials)?... Of course, if yes - is it possible for those videos to be "sticky" on the apps (Android & iOS) too?...

**Comment by republicus** [comment]
I think what your looking for is the PromoteVideos plugin which you can purchase for $19.99 in your admin panel.

**Comment by andreicaba** [comment]
I actually meant to have 2-3 videos which will help new users use the video library, which should be  "sticky" - regardless someone does "promote" their videos with more or less money... Something outside of the "promoting" - to be the first thing new visitors of the library will see (only 2-3 videos...)
  Is this possible?...

thanks for your reply 👍 🖐️

**Comment by DanielnetoDotCom** [comment]
Hi, that is what promote videos do.

also if you are expecting the big video, you can check the suggested videos on the videos manager

**Comment by Andiweb87** [comment]
Hi Daniel where is the option to leave in big video the last video added and not a randoms
 videos ??

**Comment by DanielnetoDotCom** [comment]
sorry for now, you have only suggested videos or random. we may add the option for the newest video in the future

**Comment by andreicaba** [comment]
As for the moment... I just changed the videos' dates in SQL directly... :) I've set it to year 2021... :) it's a working "workaround" till you will release the "fix", Daniel... :) 👍🏻

**Comment by andreicaba** [comment]
As for the moment... I just changed the videos' dates in SQL directly... :) I've set it to year 2021... :) it's a working "workaround" till you will release the "fix", Daniel... :) 👍🏻

**Comment by Andiweb87** [comment]
the problem is the random videos show after the update i made yesterday , before the update  in big video show only the last video added. maybe something change after the update ?

**Comment by andreicaba** [comment]
All is well now (by the way, Andiweb87 - "suggested videos" works really well)...

Still, one issue, Daniel:
Is there any way to hide a certain video for a specific user group?... Like: if user is in some specific certain user group, hide the video from the gallery view (both app and web)?...

**Comment by DanielnetoDotCom** [comment]
@andreicaba it is not clear for me.

but maybe you are talking about this

![image](https://user-images.githubusercontent.com/18009293/63098349-18bbf600-bf49-11e9-85ec-94e5525fb1e2.png)

**Comment by andreicaba** [comment]
No, not really :)
Actually, we created a video to show people how to subscribe to our library. But to users which are already logged in, the tutorials are useless and they even hinder as they occupy a few screens (there are a few tutorials). I thought of a possibility to hide a certain category of videos to a chosen user group, so all users in the specified group will not see that category of videos, or, at least, it will not show them in the gallery or maybe even at some search results?... :)

**Comment by DanielnetoDotCom** [comment]
I see and I understand and agree with your need. but for now we do not have this option.

**Comment by andreicaba** [comment]
This could be useful also if someone did subscribe to some subscription and then that particular user (or, better - that particular user group) will have access (allow or disallow list) to only the desired categories.
What do you say?...

**Comment by DanielnetoDotCom** [comment]
I like it.

It will be made some day for sure, but if you want to hurry up with the development, you can hire us to do it.

email us at developer@youphptube.com
