### ISSUE TITLE
Problema funcionalidade "Auto remove"

### ISSUE THREAD

**Issue by jadirj** [WWBN/AVideo#1829]
Boa tarde, segue outro comportamento não esperado na plataforma.

Quando feito o upload pela opção "From File" do encoder, caso a opção "Auto remove" (aba Configurations) não esteja marcada, o sistema não remove um dos arquivos temporários criados no momento da conversão, quando executamos a limpeza manual do log do upload na aba "Queue Log".

Somente os arquivos com nomes semelhantes a "original_5d0145401fd42156036588212Jun19153A583A02_YPTuniqid_5d1a609beb4570.42680216" permanecem. 

Se a opção "Auto remove" estiver marcada, todos os arquivos são apagados automaticamente após o processamento do vídeo.

![Capturar4](https://user-images.githubusercontent.com/52298160/60466840-2d5b5d80-9c2b-11e9-96df-fcd9d378a361.PNG)

**Comment by DanielnetoDotCom** [comment]
Não consigo ver o por que não está apagando, na dúvida eu adicionei um * curinga no codigo pra garantir que delete o arquivo
