### ISSUE TITLE
Autoplay in live links

### ISSUE THREAD

**Issue by Andiweb87** [WWBN/AVideo#1838]
Hi , any option for livelinks to autoplay when is open and not click the button play to start it ?

thank you

**Comment by akhilleusuggo** [comment]
@Andiweb87 Hi
I'm not using the live streaming option , but have you tried ''Autoplay Video on Load Page'' ?
You can find this option by going to : `Admin Panel > Settings > Site Settings > Regular Configuration > `at the bottom you can see '' Autoplay Video on Load Page '' . Try it
