### ISSUE TITLE
Option for download button

### ISSUE THREAD

**Issue by bobbyrabbit** [WWBN/AVideo#1843]
Is there an option to download a video per User/User Group or in fact, place a download button option per video?

Thanks

**Comment by bobbyrabbit** [comment]
This would something very useful. If someone could give me a yes or no, that would be great. Thanks

**Comment by DanielnetoDotCom** [comment]
Try this

![image](https://user-images.githubusercontent.com/18009293/60985201-6f635e00-a313-11e9-80cb-eb69914718b5.png)


The first option will allow you to download all the videos from a user, this options will enable a feature on the channel page

![image](https://user-images.githubusercontent.com/18009293/60985541-0c25fb80-a314-11e9-803f-56f8bc875db4.png)

The second, ( you must enable the first one on the channel ) you can find on videos manager

![image](https://user-images.githubusercontent.com/18009293/60985852-a423e500-a314-11e9-813b-82a13314c74b.png)

**Comment by bobbyrabbit** [comment]
I knew I had seen it somewhere. Thanks Daniel.

**Comment by bobbyrabbit** [comment]
How does a user then download the video? I see an option when I right-click the video itself called:
Download video (m3u8)
If I click that link it goes to a page which shows:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=800000
low/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1400000
sd/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2800000
hd/index.m3u8

**Comment by DanielnetoDotCom** [comment]
yeah, is not possible to download HLS files.

to download must be MP4 or WEBM
