### ISSUE TITLE
video does not play

### ISSUE THREAD

**Issue by risleem** [WWBN/AVideo#1845]
successfully install youphptube server unto ubuntu 18.04. Successfully uploaded .mp4 video, but when i click on it nothing happens, does not play. I am new to youphptube platform. Need help getting this working.

**Comment by akhilleusuggo** [comment]
You need to encode it. Otherwise is not gonna work. You can use the public encoder , or build your own one. More information here https://github.com/YouPHPTube/YouPHPTube-Encoder/wiki

**Comment by DanielnetoDotCom** [comment]
@risleem  please read this https://github.com/YouPHPTube/YouPHPTube/wiki/About-Video-Upload

**Comment by risleem** [comment]
Figured it out. It was based on the the file size.
