### ISSUE TITLE
How to bulk import (Youtube, Dailymotion, Vimeo) videos without encoding them like some other php scripts are doing?

### ISSUE THREAD

**Issue by saakaifoundry** [WWBN/AVideo#1856]

**Comment by akhilleusuggo** [comment]
As far I we know , that not possible . You can read more about bulk import here : https://github.com/YouPHPTube/YouPHPTube/wiki/Bulk-Upload-Videos

**Comment by DanielnetoDotCom** [comment]
the other scripts do not encode, they bulk embed videos.

in the future, we may release a similar feature.
