### ISSUE TITLE
Where to add custom CSS?

### ISSUE THREAD

**Issue by saakaifoundry** [WWBN/AVideo#1858]

**Comment by DanielnetoDotCom** [comment]
Try here 

![image](https://user-images.githubusercontent.com/18009293/61172164-374c5d00-a557-11e9-8a29-652b164a6b85.png)


![image](https://user-images.githubusercontent.com/18009293/61172176-459a7900-a557-11e9-845e-3c7d82f6e4b3.png)


Make sure you put it between <style></style> tags
