### ISSUE TITLE
VideoThumbnails plugin is enabled but thumbnails are not showing, we only see a text "Creating images, please comeback later"...Still the same message showing 5 hours later...The video is a 3min one...Should not have any issue.

### ISSUE THREAD

**Issue by saakaifoundry** [WWBN/AVideo#1859]

**Comment by akhilleusuggo** [comment]
Can you provide some more information ? Screenshot or logs ? Do you have an Encoder ? Did you checked that on your directory /video there's thumbnails created ?

**Comment by saakaifoundry** [comment]
Hi Akhilleusuggo, yes we have the thumbnails created under /video. The videoThumbnails plugin sounds like a well-known issue.

**Comment by DanielnetoDotCom** [comment]
Hi, the thumbs were successfully created on streamer videos?

If yes, should be a browser cache issue

if not, please check your streamer/encoder log

**Comment by saakaifoundry** [comment]
Hi Daniel,

It's not a browser cache issue (not working with incognito as well).
I have checked the streamer/encoder log...And the latest activity was July 11 when I have used the encoder today...So it seems that the encoder used is not the one under streamer/encoder.  Can you test from your side?

**Comment by saakaifoundry** [comment]
Hi Daniel,
After investigation, it seems that the settings you have done need some update because the logs and thumbnails are under /streamer/videos...No log records for the latest encoding under streamer/encoder/videos or /YouPHPTube-Encoder/videos...This is weird.

**Comment by DanielnetoDotCom** [comment]
what exactly encoder URL are you using? (check site configurations)

Also, please share your log files, must have some clue there

**Comment by saakaifoundry** [comment]
Daniel,
You have set up the encoder URL for us (Saakai) and you have full access to our server/app:)
