### ISSUE TITLE
How to make the Video Form modal (class: modal-dialog) responsive?

### ISSUE THREAD

**Issue by saakaifoundry** [WWBN/AVideo#1861]

**Comment by DanielnetoDotCom** [comment]
what video form?

**Comment by saakaifoundry** [comment]
Here the video form "direct upload"
![Screenshot_20190719-154712_Chrome](https://user-images.githubusercontent.com/7847961/61513134-7e4abe80-aa3f-11e9-9144-bc51d5a22d55.jpg)
