### ISSUE TITLE
Video sharing

### ISSUE THREAD

**Issue by soapstreams** [WWBN/AVideo#1862]
I am fine with setting "All Share This Video" on an individual video basis, but I would also like the default to be share rather than not so that individuals can turn off sharing if they choose rather than having to manually turn it on. Is that possible now?

**Comment by DanielnetoDotCom** [comment]
I understand but for now, we do not have this option.

change it require some code, and may be done in the future.

**Comment by soapstreams** [comment]
Ok. I don't know much about coding, but I would think that if you can't set the toggle to default to "share" instead of "don't share," we could add this setting to the advanced customization plugin. Just a thought. Thanks. I will close this out shortly.

**Comment by DanielnetoDotCom** [comment]
Maybe it is not a thought change, but the thought part is finding where to change.

I require time and testing.

also, in my opinion, is to add on configuration an option to let people choose the default state.
