### ISSUE TITLE
Hiding video directory load info

### ISSUE THREAD

**Issue by soapstreams** [WWBN/AVideo#1863]
I am using your backblaze plugin, which overall works great. My issue is that in some browsers when you go to a video's webpage, you can see that it is loading data from backblaze, and I want to hide this from prying eyes? Is there a way to do this? I bought the secure video directory plugin, but you said that doesn't work with the backblaze plugin.

**Comment by DanielnetoDotCom** [comment]
Hi, I am not sure how to configure it on backblaze, but you can use a CDN on it.

https://help.backblaze.com/hc/en-us/articles/217666928-Using-Backblaze-B2-with-the-Cloudflare-CDN

After configuring the CDN you can add the CDN URL in the plugin

![image](https://user-images.githubusercontent.com/18009293/61182967-514a7600-a611-11e9-8281-62b4215798e2.png)

**Comment by soapstreams** [comment]
I will see about using Cloudflare with Backblaze. I am reticent to do so because I have lots of problems with cloudflare in the past with other sites.

Is this the sort of thing you know how to do? I am willing to pay someone to help with this. Thanks.

**Comment by sipero** [comment]
I can help you with this. I've used Cloudflare with Backblaze for over 3 months now

**Comment by soapstreams** [comment]
Excellent. Email me at soappirates@protonmail.ch with cost. Thanks.

jdr
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 7/14/19, 5:49 PM sipero <notifications@github.com> wrote:
I can help you with this. I've used Cloudflare with Backblaze for over 3 months now

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/YouPHPTube/YouPHPTube/issues/1863?email_source=notifications\u0026email_token=AKI2MDW3JDXMWBOUAR47DPDP7OUO3A5CNFSM4IDEBVYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ4O37Q#issuecomment-511241726",
"url": "https://github.com/YouPHPTube/YouPHPTube/issues/1863?email_source=notifications\u0026email_token=AKI2MDW3JDXMWBOUAR47DPDP7OUO3A5CNFSM4IDEBVYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ4O37Q#issuecomment-511241726",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
