### ISSUE TITLE
Users Subscribe to Streamer Admin by Default

### ISSUE THREAD

**Issue by KenRHill** [WWBN/AVideo#1872]
I have a thought and suggestion that I think would be useful.  I would like to see where all of the streamer site users are automatically subscribed to the streamer site admin account by default, regardless of whether their account was created directly on the streamer site or created by using their social media accounts..

**Comment by DanielnetoDotCom** [comment]
There is no option to auto subscribe, but the admin can email all users at once
![image](https://user-images.githubusercontent.com/18009293/62779791-8c15c180-ba8a-11e9-89ff-94d14db8c169.png)

**Comment by akhilleusuggo** [comment]
What you're asking for already implemented on 2 ways . Send emails to only subscribers , only send email to all users subscribed to your channel or just created account on your site
