### ISSUE TITLE
Problem with YouTube-DL

### ISSUE THREAD

**Issue by KenRHill** [WWBN/AVideo#1873]
I have not had any trouble in the past importing videos from YouTube using the encoder.  I just tried to import another video from YouTube using the encoder and I get an error message.

See image for error message.  What causes this?  How can I fix it?

![YouTube-DL](https://user-images.githubusercontent.com/37643777/61272344-c88c2100-a75b-11e9-95e5-859804848c0d.JPG)

**Comment by sipero** [comment]
There are frequent changes made to the Youtube API so as it says in the message you just need to update YouTube-DL to the lastest version

**Comment by DanielnetoDotCom** [comment]
Here https://github.com/YouPHPTube/YouPHPTube/wiki/youtube-dl-failed-to-extract-signature

**Comment by guymass** [comment]
Not working. Updating with pip the latest version still gives this error. current version is not working.

  Downloading https://files.pythonhosted.org/packages/ec/4c/4aa3a86dc43623b9d5a4b0df2915908413703adc1899965c4b2e00bb8a4d/youtube_dl-2020.1.1-py2.py3-none-any.whl (1.8MB)
     |████████████████████████████████| 1.8MB 8.9MB/s 
Installing collected packages: youtube-dl
Successfully installed youtube-dl-2020.1.1
root@fetube:/var/mu_code# youtube-dl https://www.youtube.com/watch?v=gE8Rs6UUhPE&list=PLcMPOm4X0cl98YCnqf2LfWfHvQfnGCDDl&index=11&t=0s
[3] 22057
[4] 22058
[5] 22059
[4]   Done                    list=PLcMPOm4X0cl98YCnqf2LfWfHvQfnGCDDl
root@fetube:/var/mu_code# [youtube] gE8Rs6UUhPE: Downloading webpage
[youtube] gE8Rs6UUhPE: Downloading video info webpage
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
WARNING: unable to download video info webpage: HTTP Error 429: Too Many Requests
ERROR: gE8Rs6UUhPE: YouTube said: Unable to extract video data

[3]   Exit 1                  youtube-dl https://www.youtube.com/watch?v=gE8Rs6UUhPE
[5]   Done                    index=11

**Comment by guymass** [comment]
This is the issue: [see here on github repo](https://github.com/ytdl-org/youtube-dl/blob/d4f53af482cc47b0473a3576da7ad902bea4ac39/youtube_dl/extractor/youtube.py#L1831)

        if not video_info:
            unavailable_message = extract_unavailable_message()
            if not unavailable_message:
                unavailable_message = 'Unable to extract video data'
            raise ExtractorError(
                'YouTube said: %s' % unavailable_message, expected=True, video_id=video_id)
