### ISSUE TITLE
Encoder dropping files

### ISSUE THREAD

**Issue by soapstreams** [WWBN/AVideo#1876]
Does anyone else have a problem with the encoder NOT encoding video uploads into three different size video files? I use Backblaze and I see the files that are being stored there. All the files have a specific naming nomenclature and end with either _HD.pm4, _Low.mp4, or _SD.mp4. But I uploaded 25 videos yesterday, so I should have 75 files in Backblaze. I only have 70. I am missing 2 SD and 3 Low. Since the default is to play Low-res, those 3 don't play. I have the res-switcher plugin, but the settings button disappears when the low-res video play fails and I can't change the res to load a different video.

What's going on with this? Does anyone know? Thanks.

jdr

**Comment by soapstreams** [comment]
When I go to My Videos, I can click on a link to each of the three videos: HD, Low, and SD. I just tried one of the videos NOT missing from my Backblaze bucket and when I click on each of those three video res links, I get the following code:

{
  "code": "expired_auth_token",
  "message": "",
  "status": 401
}

When I try to just play the video, I get "The media could not be loaded, either because the server or network failed or because the format is not supported." All three versions of this video are in the backblaze bucket.

jdr

**Comment by soapstreams** [comment]
In fact 15 of the 25 videos I uploaded yesterday evening/early this morning are failing. They either didn't encode one of the 3 vid resolutions or they did, but I get an "expired auth token" message.

**Comment by sipero** [comment]
Have you checked your log file in the encoder site to see if there is anything in there indicating any issue
