### ISSUE TITLE
Images missing on videos

### ISSUE THREAD

**Issue by nightstryke** [WWBN/AVideo#1878]
So I have a problem, none of the jpg or gif are showing on all my videos. It happened after I updated to 7.3 and installed x send so I can take advantage of Amazon or Blackblaze. I need these images back, what should I do?

**Comment by DanielnetoDotCom** [comment]
remove or commend this from your .htaccess

```
<IfModule mod_xsendfile.c>
       RewriteRule    ^videos/([A-Za-z0-9-_.]+)$ view/xsendfile.php?file=$1    [QSA]
</IfModule>
```
