### ISSUE TITLE
allow unlimited session timeout

### ISSUE THREAD

**Issue by razyalov** [WWBN/AVideo#1884]
Much like with the real YouTube, (but also Facebook and Twitter) it would make sense to allow a "forever" session timeout option so that the session doesn't die unless the user logged out or an admin reset the user's token for any reason.
Couldn't find a way to set this option, only to set a session timeout value. Will it work this way if I set it to 0 or a negative value?

**Comment by akhilleusuggo** [comment]
why don't you try it ?

**Comment by akhilleusuggo** [comment]
seems that -1 works well

**Comment by razyalov** [comment]
Actually -1 ends the session immediately while 0 is just default.

**Comment by akhilleusuggo** [comment]
@razyalov I've tested -1 and never ended the session , just I get error with cache . But never ended the sesion

**Comment by razyalov** [comment]
For me the very next navigation I performed I was already logged out with -1.
