### ISSUE TITLE
Password Reset on self-hosted device

### ISSUE THREAD

**Issue by Fuquan999** [WWBN/AVideo#1887]
Hi could someone tell me how I can regain access to the YouTubePhp app as I have locked myself out.  Since it is being tested on a self-hosted server I do have ssh access to the server but where do I go or what should I do?  Thanks
Fuquan L

**Comment by akhilleusuggo** [comment]
How to Reset a password with SSH
you will need to move yourself to the install directory.

cd /var/www/html/YouPHPTube/install

then you will run the script using the command line

php recoverPassword.php

type the username of the user you want to change the password and you will be prompted for the new password

More info here : https://github.com/YouPHPTube/YouPHPTube/wiki/Reset-a-Password

**Comment by Fuquan999** [comment]
Hi,

THanks for the feedback but you sent this to me on the chat and I did inform you that there is NO install directory (the installation, if my memory serves me well, recommended removing the install folder after install. Thus since there is no install directory there is no "script" to run. Do you have the script somewhere so I can probably upload it to the server and then run it?

THanks
Fuquan

**Comment by Fuquan999** [comment]
Hi,

THanks for the feedback but you sent this to me on the chat and I did
inform you that there is NO install directory (the installation, if my
memory serves me well, recommended removing the install folder after
install. Thus since there is no install directory there is no "script" to
run. Do you have the script somewhere so I can probably upload it to the
server and then run it?

THanks
Fuquan

**Comment by akhilleusuggo** [comment]
@Fuquan999 Just upload it again to your server

**Comment by Fuquan999** [comment]
Thanks for the tip as managed to reset password using the tip. One quick
question as if I try things out and they work how I am hoping it will once
I can spare some cash I aim to get a few plugins may I ask (given cashflow
is often in short demand) if a buy  around 7 Plugins or more would you be
willing to offer a discount of some form?

Thanks
Fuquan

**Comment by Fuquan999** [comment]
Hi,

Another thing as I uploaded the customizer plugin and enabled it in plugins then tried to change the "About" and the Footer both in the Plugin section aND in the Admin Settings but I still keep getting the default message/passage. Could you tell me HOW I can change that passage and include my own ABOUT and FOOTER using the plugin? As Merely clicking save does not do anything. I also checked to ensure it was not a "Cache" issue so cleared cache and used three browsers (Chrome-Firefox and Edge) and still the default Passage message remains.

Thanks
Fuquan

**Comment by sipero** [comment]
If you buy 3 or more plugins at one time you will get a discount that will be displayed. Be sure to check out the new tutorials about installing and confuring plugins as this will help you decide the ones to purchase.

**Comment by DanielnetoDotCom** [comment]
Also make sure you install the tables for that plugin.

click on the install tables button

![image](https://user-images.githubusercontent.com/18009293/61582651-b9162a80-ab03-11e9-9b94-4b1364fb109d.png)

**Comment by Fuquan999** [comment]
Hi Daniel,

May I quickly ask what do I have to do to change the "English" locale "Language" file to have UK English Language showing instead of USA English? I see the "Locale" directory on my server but UK is not one of the options? 

Thanks
Fuquan

**Comment by DanielnetoDotCom** [comment]
@Fuquan999  I guess you will need to create the locale/gb.php file
you can also include your translation there. and make it the default lang on the site configurations menu

this is based on the flagstrap project http://blazeworx.github.io/flagstrap/
