### ISSUE TITLE
SSL configuration.php bug missing "/" for subDir

### ISSUE THREAD

**Issue by w41ru5** [WWBN/AVideo#1889]
I setup a new install with release 7.2 today using SSL. I ran into a problem where all the links to anything in a "subDir" were not preceded by a '/'.

For  example when viewing my site all links and content that should have been "https://www.example.com/subDir" came across as "https://www.example.comsubDir"

I found the problem to be in **./videos/configuration.php** with this line:
`    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;`

and my fix was to add another https conditional **(!empty($_SERVER['HTTPS'])?"/":"").** before $subDir;:
`    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].(!empty($_SERVER['HTTPS'])?"/":"").$subDir;`

I'm not sure why this is, but if I am doing something wrong elsewhere to cause this let me know what I can try. Otherwise everything seems happy with this so far.

**Comment by DanielnetoDotCom** [comment]
yes, you right we need the "/" at the end of the URL
