### ISSUE TITLE
Admin panel changes not sticking

### ISSUE THREAD

**Issue by jaynelim** [WWBN/AVideo#1891]
hello,
in admin panel, on this page /admin/?page=general_settings, when i make the change for example when i toggle a switch and then save, after i refresh the page, the switch reverts back to the previous position. the changes do not stay the way i want it to. how can i fix this?
thanks.

**Comment by sipero** [comment]
What is it you are trying to save. I do know some things work best if you use the Customize Advanced plugin

**Comment by DanielnetoDotCom** [comment]
@jaynelim can you please specify what item are you trying to save?

**Comment by tbennett6421** [comment]
I'm having this issue as well.
Specifically the following under general settings do not save correctly
* users > userMustBeLoggedIn
* Sign In/Up > userMustBeLoggedIn
* Upload > doNotShowUploadMP4Button
* Upload > doNotShowImportMP4Button

toggling these options does not persist after clicking save.

Looks like a duplicate issue possible #1776

**Comment by akhilleusuggo** [comment]
Before going any further , please clear the cache of your browser and your site , under "Site Configuration"

**Comment by DanielnetoDotCom** [comment]
@tbennett6421 I just test it on demo site, with the cache plugin enabled and it is working.

can you please try it on demo site?

If still do not work on the demo site, what browser are you using?

If works on demo site, check your log file

**Comment by AKNightHawk** [comment]
I am having this same problem. actually, it happens with a lot of stuff. like changing the logo pic for the site. or changing the banner for my channel. not sure why.

**Comment by akhilleusuggo** [comment]
@AKNightHawk Desable the cache , or just clear the cache of the server and browser

**Comment by jorgeiglesiasca** [comment]
Trying to bypass the problem i´m looking for the options userMustBeLoggedIn and disableNativeSignUp on database tablets but i cant find them.  Can you point me in right direction? regards.,

**Comment by DanielnetoDotCom** [comment]
Try to change it in the plugins menu

![image](https://user-images.githubusercontent.com/18009293/66204177-a6ca7800-e680-11e9-81f1-f7725601b72c.png)
