### ISSUE TITLE
Want to send mp4 files to my azure storage

### ISSUE THREAD

**Issue by psujit775** [WWBN/AVideo#1896]
Hii,
i want to send encoded videos to my azure storage instead of streaming site. basicly i want to use only YouPHPTube encoder to encode my videos in multiple formats and want to send them to my azure storage.

**Comment by akhilleusuggo** [comment]
@psujit775 I have never used azure or S3 , have no idea . Do you have any ssh access ? In case of no , you can send them manually I guess or with 3er party application ( for automatic )

When you encode the video , the video is being moved from the encoded location to your streaming site at /var/www/html/YouPHPTube/videos , you can send them from that location to your storage .
But I also think think that this can be done with the FTP Storage plugin . There's some new script that I'm still experimenting , with looks good from what I've been reading https://github.com/YouPHPTube/YouPHPTube-Storage

**Comment by DanielnetoDotCom** [comment]
I also never tested Azure, I guess to be able to use it, is necessary to build something like S3 or B2

for now we only support S3, B2, FTP and the brand new YPTStorage https://github.com/YouPHPTube/YouPHPTube-Storage

**Comment by psujit775** [comment]
Thanks.
