### ISSUE TITLE
please make home page different

### ISSUE THREAD

**Issue by joey2354** [WWBN/AVideo#1898]
hi

please make home page 
Most watched

thank you

**Comment by akhilleusuggo** [comment]
there's already

**Comment by joey2354** [comment]
> there's already

where please ?

**Comment by akhilleusuggo** [comment]
What plugin are you using for the home page ? I mean the ''template'' ? If you're using the YouPHPTube one it should be there by default .
You can scroll down and see it by yourself : https://tutorials.youphptube.com/
![image](https://user-images.githubusercontent.com/52116577/61923321-6e5d3e00-af5b-11e9-839a-60e359ea2f02.png)

**Comment by joey2354** [comment]
yes sorry, i meant move the 'most watched' to the top rather than newly added

**Comment by DanielnetoDotCom** [comment]
Hi, for now we do not have an option to sort the sections, we may add this in the future.

**Comment by joey2354** [comment]
ok cool, that would be a useful plugin


thank you



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
07/26/19,
02:56:20 PM
