### ISSUE TITLE
Video statistics table error does not display data

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#1900]
Statistics table lost data
 Total video views, Total Video comments, Total Videos Likes, Total Duration Videos (Minutes). How does it work again. Thank you !

![1](https://user-images.githubusercontent.com/50126312/61946795-b5841700-afcd-11e9-88c7-494e5bcaee5f.png)

![2](https://user-images.githubusercontent.com/50126312/61946888-ebc19680-afcd-11e9-8d1a-911543d42565.png)

**Comment by DanielnetoDotCom** [comment]
I will review the charts soon.

**Comment by akhilleusuggo** [comment]
It does display for me

**Comment by xemtube** [comment]
I see on the web demo.youphptube.com the statistics table of views, comments, like it still works normally. Stars on the web https://xemtube.online has an unrecognized error. Can you help me fix it again? Thanks a lot !

![1](https://user-images.githubusercontent.com/50126312/61988516-7943cb80-b04c-11e9-8d85-e721662514fc.png)

**Comment by akhilleusuggo** [comment]
Link the error . Check the log files and git pull to make sure you're not missing anything .
