### ISSUE TITLE
can we modify this free script ?

### ISSUE THREAD

**Issue by joey2354** [WWBN/AVideo#1904]
Hi

just wondering if we can fully modify this free script please ?

thxs

**Comment by DanielnetoDotCom** [comment]
Sure no problem.

the best option to add new features is creating plugins.

If you want to custom some plugin, I recommend you to copy the plugin directory and modify it.

if you modify the original file (plugin or core files) you will not be able to follow the updates anymore.

but the decision is up to you.

For example, if you want to create a new design and your design. looks like the gallery plugin, you can copy and rename the Gallery plugin (plugin/Gallery) and then you can customize it.

**Comment by joey2354** [comment]
ok thxs

**Comment by joey2354** [comment]
"the best option to add new features is creating plugins."

i don't believe this is the best option as i just wanna move a line up on home page which u are reluctantly not letting me know which file it's in as, teaching me or helping me learn as I've asked :/ 




anyways close this this thread thx u

**Comment by joey2354** [comment]
it's a free script but i don't feel i own it .... sorry man, truth is truth

**Comment by akhilleusuggo** [comment]
@joey2354 It's an open-source scritp . Even the developer @DanielnetoDotCom teorically doesn't own it . I mean , he gather and did a great work to make many open-source/code and knowledge to make a project working for free
I don't feel neither that's it's fully free , but still there's a lot of effort there to appreciate

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo it is open source, you do not have to create a new plugin, you can modify the existent one, as I told you above I just do not recommend.

After you modify it, the git pull command will need to overwrite all your modified files to be able to follow this project updates.

but again, it is up to you. you call if you want to modify.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I think you tagged the wrong person xD

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo you right, I mean @joey2354
