### ISSUE TITLE
General Settings

### ISSUE THREAD

**Issue by lunar54** [WWBN/AVideo#1907]
First page Mode and small logo are missing from General Settings

**Comment by akhilleusuggo** [comment]
No , everything is on the settings . Specify with a screen what do you want to change/edit .

**Comment by akhilleusuggo** [comment]
With small logo maybe you're talking about the icon ?

**Comment by DanielnetoDotCom** [comment]
If is the Favicon, we have plans to add that in the future as well.

**Comment by akhilleusuggo** [comment]
You can edit it manually . Go to /var/www/YouPHPTube/view/img/favicon.png

**Comment by lunar54** [comment]
In your tutorial https://tutorials.youphptube.com/video/how-set-a-video-gallery-and-set-video-ads
it shows to turn on First page mode to Gallery 
![gallery](https://user-images.githubusercontent.com/35050024/61999683-49b4b380-b08c-11e9-8c82-2b85341951c8.PNG)
but in the back end of my install small logo nor first page mode are there
![gallery2](https://user-images.githubusercontent.com/35050024/61999709-c0ea4780-b08c-11e9-8971-ffd31e8fc22b.PNG)
If i switch theme though to First Page Style to netflick or Default uploaded video shows on first main page but with Gallery  or youtube style nothing shows I just get Warning! We have not found any videos or audios to show.

**Comment by DanielnetoDotCom** [comment]
this small logo is a very old version, this was not a favicon. but we will add the favicon for sure

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom There's something that I can't find danniel  . When you pass the mouse on a video to see the trailer .gif , is shows an image ''GIF'' while is loading . Where that image is located ?
I wanna change it so bad , it's very unprofessional and looking bad . I wanna create something like '' Loading'' or just nothing . Where that file is located ?

**Comment by akhilleusuggo** [comment]
Ok , found it  ''loading-gif''

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom There's ''loading-gif.png'' & "loading.gif" 
I have never seen on the site the loading.gif . I have doubled the loading.gif changing it name to loading-gif.png and now does show the animated gif of Loading gif . You may want to implement this better then the loading-gif.png

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo sorry, I am lost, could you please screenshot so I can have a better understanding what do you mean?

**Comment by lunar54** [comment]
@DanielnetoDotCom  Any ideas about my issue ?

**Comment by DanielnetoDotCom** [comment]
@lunar54 sorry, you may have the cache plugin enabled. try to disable it.

**Comment by lunar54** [comment]
@DanielnetoDotCom it is off. this one correct ?
![cache](https://user-images.githubusercontent.com/35050024/62001086-9d83c480-b0ad-11e9-926d-10fd157fb630.PNG)

**Comment by lunar54** [comment]
Figured out my issue with First page style Gallery or youtube  you have to have more than one uploaded video.

**Comment by akhilleusuggo** [comment]
I wanted to tell you that , but not having videos makes sense yes

**Comment by DanielnetoDotCom** [comment]
Hoo, I see, yes it may be a bug caused by the Big video.

thanks for the notice.
