### ISSUE TITLE
Issue with the Bulk Embed plugin

### ISSUE THREAD

**Issue by torchnetwork** [WWBN/AVideo#1911]
Hi,
Thanks for emailing me.
I have some issues i would like to try and fix my self with yourt help if possible?
The bulk embed plugin was working but is no longer working. It simply doesn't function from point A when you press search...nothing happens.
It was working but once 1k vids had been embedded it stopped.

The console says:
Msg:TypeError: videojs is undefined 

 Url: http://torch.network/plugin/AD_Overlay/videojs-overlay/videojs-overlay.js, line: 39, Address: /plugin/BulkEmbed/search.php

 Msg:ReferenceError: videojs is not defined 

 Url: http://torch.network/plugin/BulkEmbed/search.php, line: 886, Address: /plugin/BulkEmbed/search.php

Currently, as I am only at the sstup stage I am hosting on a VPS.

Any help is greatly appreciated.
Regards
Anthony

**Comment by xemtube** [comment]
You may have used the API Key limit. Please Create your Key here API https://console.developers.google.com/apis/credentials/key to create your own key. Do not share API key on demo.youphptube.com web.

**Comment by torchnetwork** [comment]
Hi,
Thanks for getting back to me.
Ok so i created a new one but that still isn't working.
Also im seeing a lot of errors when I run the java console.

**Comment by DanielnetoDotCom** [comment]
@torchnetwork did you create the Key and replace it on the plugin parameters?

![image](https://user-images.githubusercontent.com/18009293/62049747-48979980-b1e6-11e9-847d-8e559e4f8a9a.png)

**Comment by torchnetwork** [comment]
yes i did and restricted to wild card torch.network

**Comment by DanielnetoDotCom** [comment]
please check you javascript console then.

try to make a search, usually, google answer what is the problem

**Comment by torchnetwork** [comment]
Ran the console again and to be frank there are over 80 errors in the list. Errors in parsing value of margin top, 
unkown property 'user select'
Expected 'none', url filter function but not found
unknown property line break
unrecognised at rule or error parsin at rule '@-ms-viewport
& '@-o-keyframes
error in parsing value for 'width'
unknown property this and unknown property thatr.


All of this on a fresh installation :/

**Comment by torchnetwork** [comment]
also downloadable fints are missing and many other things :(

**Comment by torchnetwork** [comment]
![torchconsolerrors](https://user-images.githubusercontent.com/53400703/62083492-f63e9300-b24e-11e9-8494-83dc7277da3a.png)

**Comment by DanielnetoDotCom** [comment]
You do not suppose to be worrying about CSS warnings, just filter for XHR / requests only

**Comment by torchnetwork** [comment]
Ok thanks. I was told by the console to enable the youtube api. Did that but still not working with bulk embed

**Comment by DanielnetoDotCom** [comment]
please paste your console error here

**Comment by torchnetwork** [comment]
also I turned off the ad plugins as they where throwing JS errors in this console screen. Since disabling them the js errors have disappeared but the bulk embed remains unfunctioning.

**Comment by torchnetwork** [comment]
Error in parsing value for '-webkit-text-size-adjust'.  Declaration dropped. normalize.less:11:2
Unknown property 'orphans'.  Declaration dropped. bootstrap.css:228:3
Unknown property 'widows'.  Declaration dropped. bootstrap.css:237:2
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. glyphicons.less:35:47
Error in parsing value for 'outline'.  Declaration dropped. scaffolding.less:70:2
Error in parsing value for 'outline'.  Declaration dropped. forms.less:84:2
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. vendor-prefixes.less:108:34
Unknown pseudo-class or pseudo-element '-ms-expand'.  Ruleset ignored due to bad selector. forms.less:146:2
Error in parsing value for 'margin-top'.  Declaration dropped. bootstrap.css:2654:14
Unknown property 'user-select'.  Declaration dropped. bootstrap.css:3009:1
Error in parsing value for 'outline'.  Declaration dropped. bootstrap.css:3030:20
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:3040:1
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:3572:1
Unrecognised at-rule or error parsing at-rule '@-o-keyframes'. progress-bars.less:18:2
Unknown property 'zoom'.  Declaration dropped. media.less:21:2
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:5848:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. close.less:28:4
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. opacity.less:4:2
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. modals.less:80:2
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. tooltip.less:18:2
Unknown property 'line-break'.  Declaration dropped. bootstrap.css:5985:1
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. tooltip.less:19:32
Unknown property 'line-break'.  Declaration dropped. popovers.less:28:14
Expected media feature name but found 'transform-3d'. vendor-prefixes.less:60:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. gradients.less:12:4
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. gradients.less:11:4
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. carousel.less:123:4
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:6353:10
Unrecognised at-rule or error parsing at-rule '@-ms-viewport'. bootstrap.css:6522:1
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. jquery.webui-popover.min.css:1:1076
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. jquery.webui-popover.min.css:1:1344
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. jquery.webui-popover.min.css:1:1526
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. jquery.webui-popover.min.css:1:1579
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. jquery.webui-popover.min.css:1:1687
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. jquery.webui-popover.min.css:1:2033
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. jquery.webui-popover.min.css:1:2158
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. all.min.css:5:49
Unrecognised at-rule or error parsing at-rule '@-o-keyframes'. dbfaa8d0a1c688520e2e048200f5c53b.css:625:14
Keyframe rule ignored due to bad selector. dbfaa8d0a1c688520e2e048200f5c53b.css:658:18
Keyframe rule ignored due to bad selector. dbfaa8d0a1c688520e2e048200f5c53b.css:668:18
Keyframe rule ignored due to bad selector. dbfaa8d0a1c688520e2e048200f5c53b.css:675:18
Keyframe rule ignored due to bad selector. dbfaa8d0a1c688520e2e048200f5c53b.css:685:18
Error in parsing value for 'width'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:696:95
Unknown property 'user-select'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:696:3612
Unknown pseudo-class or pseudo-element '-ms-clear'.  Ruleset ignored due to bad selector. dbfaa8d0a1c688520e2e048200f5c53b.css:726:39
Ruleset ignored due to bad selector. dbfaa8d0a1c688520e2e048200f5c53b.css:847:8
Error in parsing value for '-webkit-text-size-adjust'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:159
Unknown property 'orphans'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:2739
Unknown property 'widows'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:2748
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:3743
Error in parsing value for 'outline'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:15785
Error in parsing value for 'outline'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:36201
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. dbfaa8d0a1c688520e2e048200f5c53b.css:857:37158
Unknown pseudo-class or pseudo-element '-ms-expand'.  Ruleset ignored due to bad selector. dbfaa8d0a1c688520e2e048200f5c53b.css:857:37263
Error in parsing value for 'margin-top'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:38788
Unknown property 'user-select'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:45900
Error in parsing value for 'outline'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:46015
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:46375
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:56818
Unrecognised at-rule or error parsing at-rule '@-o-keyframes'. dbfaa8d0a1c688520e2e048200f5c53b.css:857:85583
Unknown property 'zoom'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:89893
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:107246
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:107359
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:108587
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:108642
Unknown property 'line-break'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:109605
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:109830
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:109878
Unknown property 'line-break'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:111458
Expected media feature name but found 'transform-3d'. dbfaa8d0a1c688520e2e048200f5c53b.css:857:113731
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:114980
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:115545
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:116106
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:857:116329
Unrecognised at-rule or error parsing at-rule '@-ms-viewport'. dbfaa8d0a1c688520e2e048200f5c53b.css:857:119558
Error in parsing value for 'padding'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:1126:14
Unknown property '-moz-background-size'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:1313:26
Unknown property '-moz-box-shadow'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:1442:21
Unknown property '-moz-border-radius'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:1445:24
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. dbfaa8d0a1c688520e2e048200f5c53b.css:1558:13
Expected media feature name but found '-ms-high-contrast'. search.php:102:21
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. search.php:1:19
Unknown property '-moz-opacity'.  Declaration dropped. search.php:2:24
downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:400 stretch:100 src index:1): status=2147746065 source: https://torch.network/videos/cache/fonts/glyphicons-halflings-regular.woff2 unknown:857:3072
XHRGEThttps://torch.network/objects/playlists.json.php
[HTTP/1.1 200 OK 241ms]

downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:400 stretch:100 src index:2): status=2147746065 source: https://torch.network/videos/cache/fonts/glyphicons-halflings-regular.woff unknown:857:3072
downloadable font: download failed (font-family: "Glyphicons Halflings" style:normal weight:400 stretch:100 src index:3): status=2147746065 source: https://torch.network/videos/cache/fonts/glyphicons-halflings-regular.ttf unknown:857:3072
downloadable font: no supported format found (font-family: "Glyphicons Halflings" style:normal weight:400 stretch:100 src index:5) source: (end of source list) unknown:857:3072

**Comment by DanielnetoDotCom** [comment]
you still showing the css errors, I can not see the **XHR / requests** errors

**Comment by torchnetwork** [comment]
the other thing i have noticed is the 'mbed Video Link' tool isnt importing correctly. the videos list the file shows as (EE:EE:EE) the video is there but not playable and no titles or descriptions.
The same problem happened with the import to encoder. I am still using your encoder for now while i save up enough cash to buy your top installation service.

**Comment by torchnetwork** [comment]
oh sorry. silly me :/

XHRPOSThttps://torch.network/objects/videos.json.php?showAll=1
[HTTP/1.1 200 OK 1607ms]

XHRGEThttps://torch.network/objects/playlists.json.php
[HTTP/1.1 200 OK 1157ms]

XHRPOSThttps://torch.network/objects/playlistsFromUserVideos.json.php
[HTTP/1.1 200 OK 3788ms]

XHRPOSThttps://torch.network/objects/playlistsFromUserVideos.json.php
[HTTP/1.1 200 OK 3934ms]

XHRPOSThttps://torch.network/objects/playlistsFromUserVideos.json.php
[HTTP/1.1 200 OK 2402ms]

XHRPOSThttps://torch.network/objects/playlistsFromUserVideos.json.php
[HTTP/1.1 200 OK 4159ms]

XHRPOSThttps://torch.network/objects/playlistsFromUserVideos.json.php
[HTTP/1.1 200 OK 2209ms]

XHRPOSThttps://torch.network/objects/playlistsFromUserVideos.json.php
[HTTP/1.1 200 OK 4330ms]

XHRPOSThttps://torch.network/objects/playlistsFromUserVideos.json.php
[HTTP/1.1 200 OK 4194ms]

XHRPOSThttps://torch.network/objects/playlistsFromUserVideos.json.php
[HTTP/1.1 200 OK 4530ms]

XHRPOSThttps://torch.network/objects/playlistsFromUserVideos.json.php
[HTTP/1.1 200 OK 4386ms]

XHRPOSThttps://torch.network/objects/playlistsFromUserVideos.json.php
[HTTP/1.1 200 OK 5262ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 646ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 578ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 644ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 580ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 594ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 584ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 615ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 608ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 571ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 837ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 684ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 583ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 588ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 606ms]

XHRGEThttps://encoder2.youphptube.com/status
[HTTP/1.1 200 OK 978ms]

**Comment by torchnetwork** [comment]
|  
-- | --
Response headers (569 B) | Raw headers
Access-Control-Allow-Origin | https://imasdk.googleapis.com
Cache-Control | no-store, no-cache, must-revalidate
Cache-Control | max-age=1, private, must-revalidate
Connection | Keep-Alive
Content-Encoding | gzip
Content-Type | application/json
Date | Mon, 29 Jul 2019 21:39:18 GMT
Expires | Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive | timeout=5, max=95
Pragma | no-cache
Server | Apache
Set-Cookie | PHPSESSID=515833863876ef59f675…:19 GMT; Max-Age=3600; path=/
Transfer-Encoding | chunked
Vary | Accept-Encoding,User-Agent
Request headers (586 B) | Raw headers
Accept | */*
Accept-Encoding | gzip, deflate, br
Accept-Language | en-GB,en;q=0.5
Connection | keep-alive
Content-Length | 58
Content-Type | application/x-www-form-urlencoded; charset=UTF-8
Cookie | acceptCookies=true; __stripe_m…833863876ef59f675160100c1f97a
DNT | 1
Host | torch.network
Referer | https://torch.network/admin/?page=videos
User-Agent | Mozilla/5.0 (Windows NT 10.0; …) Gecko/20100101 Firefox/68.0
X-Requested-With | XMLHttpRequest

**Comment by DanielnetoDotCom** [comment]
Ok, there is not much clue on the errors you pasted.

but as long as you said you are getting the EE:EE:EE on the videos you are bulk embedding, I guess your error is on the server-side.

check the YouPHPTube log file

**Comment by torchnetwork** [comment]
[26-Jul-2019 18:02:29 UTC] PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
[26-Jul-2019 18:02:29 UTC] PHP Warning:  Module 'pdo_sqlite' already loaded in Unknown on line 0
[26-Jul-2019 18:02:29 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/cpanel/ea-php56/root/usr/lib64/php/modules/sqlite.so' - /opt/cpanel/ea-php56/root/usr/lib64/php/modules/sqlite.so: cannot open shared object file: No such file or directory in Unknown on line 0
[26-Jul-2019 18:02:29 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/cpanel/ea-php56/root/usr/lib64/php/modules/pdo_mysql.so' - /opt/cpanel/ea-php56/root/usr/lib64/php/modules/pdo_mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
[26-Jul-2019 18:02:30 UTC] PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
[26-Jul-2019 18:02:30 UTC] PHP Warning:  Module 'pdo_sqlite' already loaded in Unknown on line 0
[26-Jul-2019 18:02:30 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/cpanel/ea-php56/root/usr/lib64/php/modules/sqlite.so' - /opt/cpanel/ea-php56/root/usr/lib64/php/modules/sqlite.so: cannot open shared object file: No such file or directory in Unknown on line 0
[26-Jul-2019 18:02:30 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/cpanel/ea-php56/root/usr/lib64/php/modules/pdo_mysql.so' - /opt/cpanel/ea-php56/root/usr/lib64/php/modules/pdo_mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0

**Comment by torchnetwork** [comment]
thanks for all the help everyone and especially Daniel :)
I have my hosting providerson the case. You where right it is infact on the server side. Seems there are several modules and stuff that need installing and configuring. Also need to do something about the server not recognizing sumo commands for updating youtubeDL and so on.

Daniel? I will be in touch with you via email regarding the installation and plugins over the coming weeks. Actually doing a fulltime job installing soundproofing in a music studio to cover the cost of setting up this lovely script of yours :) well done man. Pretty impressive work on the whole and I will add that your version of youtube is actually better in some ways such as the music mp3 capabilities, bulk importing and so on. 
All very good ideas mate :)
Cheers

**Comment by torchnetwork** [comment]
Hi,
Just got an email from my hosting provers as follows:

It appears, exiftool, although requested, was not installed earlier.

I'm sorry for the possible inconvenience.

I've just installed it, and also ensured the disable_functions variable is also corrected for PHP-FPM pool setup (as it overwrites php.ini setup when PHP-FPM is enabled).
This removed the error messages about shell_exec() function.

exiftool and ffmpeg are installed and available from the side of the cPanel user, but the script still appears to consider them missing.

You would want to contact the developer of this application for further investigation of the issue.

**Comment by DanielnetoDotCom** [comment]
Streamer can be installed on any Server, including Windows, but the encoder and Livestream should work fine on any Linux distribution. However we recommend Ubuntu 16+ **without any kind of control panel**. The problem with cPanel, Plesk, Webmin, VestaCP, etc. It's because we need full root access to install some libs, and maybe compile them. Another important point is that to make Livestream work, we need to compile Nginx and the control panels often prevent us from running the commands forcing the installation available only on your panel.

**Comment by akhilleusuggo** [comment]
@torchnetwork This project doesn't support PHP-FPM , only CGI

**Comment by mikweb2017** [comment]
> Streamer can be installed on any Server, including Windows, but the encoder and Livestream should work fine on any Linux distribution. However we recommend Ubuntu 16+ **without any kind of control panel**. The problem with cPanel, Plesk, Webmin, VestaCP, etc. It's because we need full root access to install some libs, and maybe compile them. Another important point is that to make Livestream work, we need to compile Nginx and the control panels often prevent us from running the commands forcing the installation available only on your panel.
I have plesk and ubutu 16 works great. you have to sometimes look for alternatives but google help always.
I have been using YouPHPtube for a long time now with all the streaming functions

**Comment by akhilleusuggo** [comment]
@mikweb2017 Your comment it's like :coolstorybob from twitch , witch doesn't provide any information about this topic . Thanks for sharing :coolstorybob

**Comment by torchnetwork** [comment]
Hey guys :)
So i managed to get stuff working nicely. Bulk embedd and importing all seems to be good.
Only thing now is the ad server.
For some reason the video-ads are not playing as they are meant to when the play bar hits the yellow marker.
The video just keeps playing past the markers and no ads display. All that happens is when you put your mouse over the yellow marker it shows a popup with the ad text.
Any ideas why this would happen?
Cheers

**Comment by DanielnetoDotCom** [comment]
Hi, I am not sure, check if is the cache plugin, try to disable it.

**Comment by torchnetwork** [comment]
I generally don't have the cache on while developing so i can see the changes reflected at the front end. So it's not that. Tried it on various browsers and also on some friends computers at entirely different ip addresses and still no ad vids displaying.
Also was wondering how your ad system works in terms of process? As in can you explain how members pay and display their ads? Do they fund their wallets and request ads or can they create an ad as soon as their wallet has  funds?
Also how much do we charge for the ads?

**Comment by DanielnetoDotCom** [comment]
https://github.com/YouPHPTube/YouPHPTube/wiki/Monetization:-How-To-Make-Money-on-YouPHPTube#advertisements
