### ISSUE TITLE
How to move the Description text more to the right

### ISSUE THREAD

**Issue by honeyfairy** [WWBN/AVideo#1912]
I want to just move the Description text box more to the right. How can I do that? What files should I look in?
![Capture](https://user-images.githubusercontent.com/17691989/62007293-06217e80-b14c-11e9-8e5c-fba5f3ae7df6.PNG)

**Comment by akhilleusuggo** [comment]
I think it's a CSS thingi

**Comment by honeyfairy** [comment]
> I think it's a CSS thingi

I think so too, but I wanted some direction as to where I could look or do it quickly

**Comment by honeyfairy** [comment]
anyone?

**Comment by DanielnetoDotCom** [comment]
To do it you should know CSS and how to inspect the code.

with this, you should be able to create a css to fit your needs.

maybe you can use this ...


.mainInfoText{margin-left: 25px;}
