### ISSUE TITLE
Live Stream

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#1914]
When livestream goes ON , doesn't appear on the notification ( list of the live streams ) . It does only when added manually as external stream from 3er party sites

**Comment by DanielnetoDotCom** [comment]
Did yo check this

![image](https://user-images.githubusercontent.com/18009293/62052324-a7134680-b1eb-11e9-92a3-3e7e65c9aeb4.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Of Course Daniel
![image](https://user-images.githubusercontent.com/52116577/62056787-42211600-b216-11e9-974b-be4fe315d5c5.png)

**Comment by akhilleusuggo** [comment]
it also shows the livestream OFFLINE when it's online 
![image](https://user-images.githubusercontent.com/52116577/62057156-fd49af00-b216-11e9-9df7-6b4219286c30.png)

**Comment by DanielnetoDotCom** [comment]
how is your stats page, is it https?

here is the demo: https://youphptube.com:444/stat

is it correctly configured in the plugin?

![image](https://user-images.githubusercontent.com/18009293/62066783-81e10100-b208-11e9-8761-87c2e6cea581.png)

**Comment by akhilleusuggo** [comment]
oho , the stats I have them on port 8088 ( the one on NGINX ) , let me try 444 and tell you

**Comment by DanielnetoDotCom** [comment]
Port 444 is not mandatory

as long as your nignx https is running on port 8088

**Comment by akhilleusuggo** [comment]
Yeh , I have tried it with 444 port , the RTMP stats working and but still , the notification is not showing

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/62067662-24f74200-b22c-11e9-8ea7-45154c679d4a.png)

**Comment by DanielnetoDotCom** [comment]
is the https certificate for nignx on port 444 valid?

check for errors on the JS console

**Comment by akhilleusuggo** [comment]
VIDEOJS: Play middleware has been registered with videojs
video.js:142 VIDEOJS: WARN: A plugin named "reloadSourceOnError" already exists. You may want to avoid re-registering plugins!
(anonymous) @ video.js:142
adsbygoogle.js:1 Uncaught M
video.js:142 VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead
(anonymous) @ video.js:142
video.js:142 VIDEOJS: overlay#mainVideo_component_427:  created, listening to "play" for "start" and "timeupdate" for "end"
video.js:142 VIDEOJS: overlay#mainVideo_component_427:  hidden
video.js:142 VIDEOJS: overlay#mainVideo_component_427:  bound `startListener_` to "play"
video.js:142 VIDEOJS: overlay#mainVideo_component_427:  unbound `endListener_` from "timeupdate"
?c=AkhilleusUggo:1191 Trying to reconnect on wss://tube.akhilleusuggo.com/wss/
?c=AkhilleusUggo:1002 A Javascript-error happend. Please tell your admin to clear the folder videos/cache. 
 If this doesn't help, attach these infos to a github-pull-request: 
 Msg:Script error. 
 Url: embed in html, line: 0, Address: /plugin/Live/?c=AkhilleusUggo
video.js:142 VIDEOJS: overlay#mainVideo_component_427:  shown
video.js:142 VIDEOJS: overlay#mainVideo_component_427:  unbound `startListener_` from "play"
video.js:142 VIDEOJS: overlay#mainVideo_component_427:  bound `endListener_` to "timeupdate"
?c=AkhilleusUggo:1194 Connection established!
script.js:34 closeYouTubeMenu

**Comment by DanielnetoDotCom** [comment]
I can not see anything wrong. is your https certificate valid?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Ofc , let's encrypt with crons , working with it for over 1 year auto-renew 
You can check it by yourself https://tube.akhilleusuggo.com

**Comment by DanielnetoDotCom** [comment]
Ok, is your plugins parameter with this address?

https://tube.akhilleusuggo.com:444/stat

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/62068545-1d389d00-b22e-11e9-846b-165b7f5f76fd.png)

**Comment by DanielnetoDotCom** [comment]
In this case, I am not sure, try to check the YouPHPTube error log.

**Comment by akhilleusuggo** [comment]
[29-Jul-2019 20:30:37 Europe/Helsinki] Page generated in 0.0194 seconds. User: admin - No Cache (/plugin/Live/stats.json.php?Label) FROM: xxx.xxx.xxx Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
[29-Jul-2019 20:30:38 Europe/Helsinki] PHP Fatal error:  Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:8888": Address already in use in /var/www/web/YouPHPTube/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php:164
Stack trace:
#0 /var/www/web/YouPHPTube/plugin/LiveChat/ratchet/react/socket/src/Server.php(31): React\Socket\TcpServer->__construct('tcp://0.0.0.0:8...', Object(React\EventLoop\StreamSelectLoop), Array)
#1 /var/www/web/YouPHPTube/plugin/LiveChat/ratchet/cboden/ratchet/src/Ratchet/Server/IoServer.php(59): React\Socket\Server->__construct('0.0.0.0:8888', Object(React\EventLoop\StreamSelectLoop))
#2 /var/www/web/YouPHPTube/plugin/LiveChat/chat-server.php(20): Ratchet\Server\IoServer::factory(Object(Ratchet\Http\HttpServer), '8888')
#3 {main}
  thrown in /var/www/web/YouPHPTube/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php on line 164
[29-Jul-2019 20:30:38 Europe/Helsinki] Page generated in 0.1101 seconds. User: admin - No Cache (/plugin/Live/?c=AkhilleusUggo) FROM: xxx.xxx.xxx Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
[29-Jul-2019 20:30:42 Europe/Helsinki] Page generated in 0.0194 seconds. User: admin - No Cache (/plugin/Live/stats.json.php?Menu) FROM: xxx.xxx.xxx Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Comment by akhilleusuggo** [comment]
Omg , now that I've seen that I have errors on the chat , I went to try it and got even more errors , but does that has anything to do with this ?

**Comment by DanielnetoDotCom** [comment]
I think I got it

The live stream name should be the stream key. https://github.com/YouPHPTube/YouPHPTube/issues/1382#issuecomment-468976335

![image](https://user-images.githubusercontent.com/18009293/62069378-83adc300-b20e-11e9-880a-6a4ddfd1243f.png)

![image](https://user-images.githubusercontent.com/18009293/62069316-5f51e680-b20e-11e9-84cd-4d314db633ac.png)

I guess you are redirecting your code somewhere on nginx.conf

**Comment by akhilleusuggo** [comment]
and how I fix this . I got what you mean , but I haven't modified any redirecting . The only one was from the control panel , redirect all traffic from http to https

**Comment by DanielnetoDotCom** [comment]
I am not sure, but one time I fixed a similar problem removing the redirect on the .htccess.

maybe you are redirecting on the nginx.conf.

you will need to find out where is it.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom The .htccess file you've removed , is the one on the /YouPHPTube directory ?
Because I'm having 3 of them 
.htccess
new.htccess
classic.htccess

**Comment by DanielnetoDotCom** [comment]
I am do not mean remove the .htaccess file, I mean remove the redirect parameter on the .htaccess.

the YouPHPTube default .htaccess does not have any redirect

**Comment by akhilleusuggo** [comment]
You didn't helped me at all :( 
Can you guide me to what to do exactly ? What part should I copy/past here so you can get a look at it ?
Thank you :)

**Comment by DanielnetoDotCom** [comment]
Did you changed the original .htaccess?

do you have something redirecting your NGINX site?

I would guess when you installed the SSL, on nginx, you add a redirect rule from http to https

**Comment by akhilleusuggo** [comment]
Let me show you: 

```
http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8088;
                    listen 444 ssl;
                    server_name example.com;
                    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
                    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"   $
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';
```

**Comment by TrippyTubeTV** [comment]
I am having the same issue. Did you ever find a resolution?

**Comment by akhilleusuggo** [comment]
@TrippyTubeTV #1945
