### ISSUE TITLE
Encoder install

### ISSUE THREAD

**Issue by lunar54** [WWBN/AVideo#1919]
install just stalls on Processing and i am seeing this in Apache log
le or directory in /var/www/encode.MyDomain.net/html/view/index.php on line 18
[Mon Jul 29 23:00:04.494011 2019] [php7:error] [pid 7987] [client MyIp:62187] PHP Fatal error:  require_once(): Failed opening required '/var/www/encode.MyDomain.net/html/view/../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/encode.MyDomain.net/html/view/index.php on line 18

If i refresh i get screen saying it has been installed and remove install dir when i do i get blank page when going to encoder page

**Comment by akhilleusuggo** [comment]
did you followed the guide ? I think it's permission problem

**Comment by lunar54** [comment]
yes i did just moved the encoder to a folder under site and installed fine. But with it in a subdomain no luck

**Comment by lunar54** [comment]
by the way seems to be better performance with out a control panel setup

**Comment by DanielnetoDotCom** [comment]
@lunar54 I recommend the installation, on Ubuntu without any kind of control panel.

is also possible to install on centos with CPanel, but we do not give support to it, to do it you must know how to do it.

**Comment by lunar54** [comment]
@DanielnetoDotCom That is what I am testing Ubuntu 18.04 with a virtual host/dir & nginx/rtmp on same machine. I did have it working with CP I use but noticed that for saving live streams you req all on 1 server.  I personal would rather see nginx/rtmp on separate machine but I do see a bit of performance increase with everything on 1 machine. right now have Ubuntu VM on proxmox going to test bare metal install soon. Do you see any performance gains with DDR4 ?

**Comment by DanielnetoDotCom** [comment]
@lunar54 I have never made a benchmark with ram memory 

yes, I also prefer all in one server.

**Comment by akhilleusuggo** [comment]
@lunar54 Will be no difference for this script . Unless you're having 10k users active . Just to let you know , I have a mini laptop , and I have installed this script on it ; The spect of the mini laptop :
1core CPU ( atom 10w , low performance )
1GB Ram
120Gb SSD

Conclusion , I see no difference between my GCP ( google cloud platform ) that I'm using right now and the mini laptop .

**Comment by lunar54** [comment]
@akhilleusuggo  wow 1gb mem I just did a test with a large 40min video close to 8gb in size. Took for ever but seen my mem spike to 63% of 16gb. Now you got me wanting to try it on a NanoPi Fire3 :) just for giggles.

**Comment by akhilleusuggo** [comment]
Look , Ubuntu server 18.04 ( the one I used ) , installing it on my mini laptop was using 53mb or RAM ( on a fresh ubuntu server installation ) . After the updates 85mb RAM . Following the guides of Daniel , and a successful installation the server used around 300-500mb ram . Too much left for other things . 
After that , I have added an encoder on my second machine , 16cores/32threads , just to speed up the encoding . And I have seen only some files not being sent due to low memory on a laptop .  But very few , that I didn't even bother trying them , since it was just for a fun test .

The site was consuming a lot of resouces only on the main page , where 50 videos shows , and the .gif , thumbs etc loads . The impact was on the CPU ( I have only @1.6Ghs , so normal 100% on use , once it loaded , goes back to 0.7%

**Comment by lunar54** [comment]
@akhilleusuggo are machines using static ips or you have a internal setup and opening ports on router ? Ya I had planed on doing test with encoder on 2nd machine also. my servers are setup with zfs raid storage which will also eat memory. Is there a Discord server etc for dev chat for YouPHPTube ?

**Comment by akhilleusuggo** [comment]
1-On my case , I didn't opened any ports , you don't have to if you're going to test this on a local server ( with local I mean the IPs that provide you the router 192.168.X.1XX ) . Yes on Netplan you can specify DHCP = true, false ( you can google it ) , or give a dedicated local IP for that specific machine with the MAC Address 
2- I didn't saw any Discord server , everything is happening here as far as I know

**Comment by lunar54** [comment]
@akhilleusuggo I was just wondering how you are running site. I use statics and ya you can even add 2nd nic to be used with internal lan just add extra netplan file for it so you can have access to nas etc. all my Dell R710's & R610's are setup like this for proxmox,backups and iso's & dedicated mysql server. idrac uses a separate internal lan for main server management.
