### ISSUE TITLE
gif and jpeg only upload, but video not upload from encoder

### ISSUE THREAD

**Issue by sivanaidu2011** [WWBN/AVideo#1921]
i am try to upload video through private encoder, but the video is not upload and only gif and jpeg of that video is uploaded , let me know the problem plz

**Comment by sivanaidu2011** [comment]
![image](https://user-images.githubusercontent.com/53479623/62131501-f6936880-b2f8-11e9-8f46-3dc19dac21f5.png)

**Comment by DanielnetoDotCom** [comment]
check your log file.

**Comment by akhilleusuggo** [comment]
Link your log files ; There are only 2 basic errors for this case 
1-Not enough permissions 
2-Lake of resources ( php_limit ) memory and uploads etc
