### ISSUE TITLE
Do not use Live Link Plugin from the u3m8 link of Youtube

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#1923]
I currently perform live getlink from YouTube to get the link.U3m8. But when you upload Youphptube Live Link Plugin for live streaming, it cannot be saved. The status is still in progress and hanging. The details you see are attached. Are there any to use? Thank you !

VD  The link I tried was not : https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1564584653/ei/bVZBXZTcApr6owPE46aQBA/ip/117.3.62.202/id/zS4C3yUzIK4.2/itag/95/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D136/hls_chunk_host/r3---sn-8pxuuxa-q5ql.googlevideo.com/gcr/vn/playlist_type/DVR/initcwndbps/14240/mm/44/mn/sn-8pxuuxa-q5ql/ms/lva/mv/m/mvi/2/pl/20/dover/11/keepalive/yes/mt/1564562844/disable_polymer/true/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,goi,sgoap,sgovp,gcr,playlist_type/sig/ALgxI2wwRAIgXGpxJHVbt8wKkkACXOtWsY_7TjU64lTLEeWFlGIelscCIE3n1tMh92QoHCGCyzkG6yhxRNGgVD8N7ViYBfsx4zxr/lsparams/hls_chunk_host,initcwndbps,mm,mn,ms,mv,mvi,pl/lsig/AHylml4wRQIhAN_n85mW3rj-kJKjJaNA-3UVXPSXE-2OnXdZL6tpsm8nAiB46Cvi71FsOV6WaZn36Nwq3NtcYKkJ7e_R4QWSsJ6o8Q%3D%3D/playlist/index.m3u8

![1](https://user-images.githubusercontent.com/50126312/62199089-184e2780-b3ad-11e9-8a50-5dba2937a95f.png)

I use VLC media software and still play normal video.

**Comment by akhilleusuggo** [comment]
Same problem here , I thought I had a problem with my config , but yeh , same here 
My case is different on the sense that the ''Progress Bar'' disappears , all it's ok , but the video won't play anyway

**Comment by DanielnetoDotCom** [comment]
I got the error  `Data too long for column 'link' at row 1`

I guess I was not expecting a link that big.

I will release a fix for it.

**Comment by xemtube** [comment]
When you release the error version, please notify me and let me proceed with the update. Thank you very much !

**Comment by DanielnetoDotCom** [comment]
Ok, it is updated and now you can update your files and plugin 

![image](https://user-images.githubusercontent.com/18009293/62217668-6a795380-b381-11e9-916e-3c7a95055926.png)


But FYI I try the link on demo site, and as expect google does not allow you to share it.

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1564584653/ei/bVZBXZTcApr6owPE46aQBA/ip/117.3.62.202/id/zS4C3yUzIK4.2/itag/95/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D136/hls_chunk_host/r3---sn-8pxuuxa-q5ql.googlevideo.com/gcr/vn/playlist_type/DVR/initcwndbps/14240/mm/44/mn/sn-8pxuuxa-q5ql/ms/lva/mv/m/mvi/2/pl/20/dover/11/keepalive/yes/mt/1564562844/disable_polymer/true/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,goi,sgoap,sgovp,gcr,playlist_type/sig/ALgxI2wwRAIgXGpxJHVbt8wKkkACXOtWsY_7TjU64lTLEeWFlGIelscCIE3n1tMh92QoHCGCyzkG6yhxRNGgVD8N7ViYBfsx4zxr/lsparams/hls_chunk_host,initcwndbps,mm,mn,ms,mv,mvi,pl/lsig/AHylml4wRQIhAN_n85mW3rj-kJKjJaNA-3UVXPSXE-2OnXdZL6tpsm8nAiB46Cvi71FsOV6WaZn36Nwq3NtcYKkJ7e_R4QWSsJ6o8Q%3D%3D/playlist/index.m3u8. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom So why does it work on VLC ?

**Comment by DanielnetoDotCom** [comment]
Because VLC is not a browser, CORS rules apply only to browsers

https://www.quora.com/What-is-CORS-How-does-it-work

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom thanks for the info , but this can be fixed by re-streaming it as I see . VLC>Stream with programs or RTMP ( like platforms re-stream with NGINX ) 
I'm not discussing the google user agreement , just the theory

**Comment by DanielnetoDotCom** [comment]
I agree with you, I guess a restream will resolve it.
