### ISSUE TITLE
Help with Mobile App 

### ISSUE THREAD

**Issue by Cosmopal** [WWBN/AVideo#1925]
Hi,
First of all, seems to be a very awesome project. I have not yet explored it fully, but it looks like this is one of the best open source projects I have found so far. Kudos to this work :D :+1: :+1: :1st_place_medal: 

I was trying to understand how YPT works for mobile services, but your main website has surprisingly limited information for that. I am posting these questions here because in several of your comments on the website you seem to prefer Github for discussion. I hope you don't mind me asking these here. :sweat_smile: 

* You mention on your site that to rebrand the mobile app for use, we need to buy it from you. But could you please tell **what do we get when we buy the app?**. Do we get the source code? Or just some options to add our own logo and stuff? Because we really would like to use this service but in our own app and our own template. 

*  Do you plan to have some sort of SDK for mobile development? Maybe something like a library which helps us connect to server, fetch and display videos etc? That would be really helpful

* In your professional plans, do you also offer services for setting up the mobile app? If not I think that'd be a great addition.

Thanks,
PA

**Comment by DanielnetoDotCom** [comment]
Hi, the app we offer on the website is a compiled version for Android and iOS.
This compiled version will have your icons, logo and builtin website.

we also can sell you the source code, to proceed with the source purchase please email developer@youphptube.com

About the SDK we have an API plugin what I use to build my mobile APP, you probably can use it to build any other app https://demo.youphptube.com/plugin/API/info.php

For publishing your app we have 3 options:

    1. We can publish to you using our YouPHPTube developer account, this would not have any cost
    2. You can publish for yourself, for this you would need to acquire/buy with Apple and Google their own developer accounts. If you wish to publish using your developer account, we can send you the APK (Android) and the XCode (iOS) project.
    3. We can publish to you using your developer account, just share your credentials with us.

**Comment by Cosmopal** [comment]
@DanielnetoDotCom Thanks for your response. I am more interested in in integrating an API/Sdk. I am getting "Error, you cannot do this" when I click the tutorial link you sent above.

**Comment by DanielnetoDotCom** [comment]
What URL are you using to get this error?

**Comment by Cosmopal** [comment]
The one you gave - https://demo.youphptube.com/plugin/API/info.php

**Comment by DanielnetoDotCom** [comment]
I see, that is because you need to login as admin before see it.

the admin credentials are:

- user: admin
- pass:123
