### ISSUE TITLE
What is the VPS service you use for your professional services?

### ISSUE THREAD

**Issue by Cosmopal** [WWBN/AVideo#1926]
Hi,
First of all, Kudos to this work :D :+1: :+1: :1st_place_medal: 

I was looking at the service you provide [here](https://www.youphptube.com/services). For the VPS professional services plans, which service do you use to setup the VPS?

**Comment by akhilleusuggo** [comment]
I would recommend you to use GCP ( Google Cloud Platform ) . Why ?
1- Google does give a free trial of 300$ to use their products ( for 1 year )
2- You have up to 96 cores ( xD crazy )
3-4TB RAM ( xD crazy )
4- All the above one you will not be able to use them on trial for the high cost 

The good thing is that everything is working with API . If you want to change location server frm NA to EU , you can do it on 30s
If you want to add more RAM , you don't have to contact your provider and wait 3h until he answer , you can change it on 30s
If you want to add a core or more , only with 1 click

I like more the think that you pay for what you use . With all providers , when you pick a VPS , no matter you use it or not you gonna pay for it . On GCP you don't pay for a machine that you're not using . In other words , when you turn off your VPS , you don't pay for it ( you may pay only for the storage that you're using , and it's really cheap , but not for the CPU/RAM etc

On this project it's very useful , why ?
You can create multiple machines or 1 machine powerful , and when you have a lot of videos to encode , just use the machine to encode , and turn off when it's done , and you don't have to pay for 1 month with other VPS

Hope was useful :)

**Comment by DanielnetoDotCom** [comment]
I use VPS located in USA with 2 GB ram 2 cores and 150 GB disk

For dedicated servers, they are located in Canada or France 16 GB ram , 4 cores, 2 TB disk
