### ISSUE TITLE
Livestream - Later Fix

### ISSUE THREAD

**Issue by mrtick2002** [WWBN/AVideo#1928]
Just a thought, but at some point it would be nice if the Livestream info would be Blank when the page is refreshed. Every time you go to setup a livestream it's the same info from the last livestream. Just think it should be blank every time, but maybe I'm wrong.

**Comment by akhilleusuggo** [comment]
@mrtick2002 Even on Youtube é and Twitch the data of the previous stream ( I think you're talking about title and description ) they're always the same
