### ISSUE TITLE
Plugin Report Video

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#1936]
I don't really understand the benefit from this plugin . The idea is great , but the functionality are useless . Let me explain . You reported the video , the admin got a notification on the email ( SHOULD BE also on the streaming site undender admin panel a section for reported videos showing the number of report ) . But the most important is the reason of the report . The user should have the possibility to give a reason of the report . After choosing the reason , can leave a feedback/message telling the admins what exactly think that the video is missing or been reported .

**Comment by KenRHill** [comment]
I agree and I like this idea.  There should be a place to put a reason as to why the user reported the video.  This way it gives the site admin something to focus on to see if it violates the Terms of Service etc.

**Comment by DanielnetoDotCom** [comment]
Hi, I also agree and it may be upgraded in the future.

the thing is I had to quickly develop this plugin, so Apple can approve the mobile app on the app store.

iOS does not approve videos app without a violation report tool
