### ISSUE TITLE
OBS studio not conect for mi server...

### ISSUE THREAD

**Issue by bersuit72** [WWBN/AVideo#1938]
hello good afternoon people, I can not make a transmission through OBS since it does not connect to the server ... what can it be? Do you have to open a port? Do you have to configure something else? It is not on my dedicated or local server

![Sin título](https://user-images.githubusercontent.com/31553331/62643025-6323ee00-b91d-11e9-8792-c771233dec21.png)
![Sin título2](https://user-images.githubusercontent.com/31553331/62643026-63bc8480-b91d-11e9-8e78-5321989dd4fa.png)
![Sin título3](https://user-images.githubusercontent.com/31553331/62643027-63bc8480-b91d-11e9-9e6c-eb5926ad10fd.png)

**Comment by akhilleusuggo** [comment]
Tienes que configurar el NGINX . Has seguido el guia que esta en la Wiki ? Cuales son los logs ? Errores ? En todo caso es cosa del NGINX . Si puedes haz un copy/past del NGINX config file

**Comment by bersuit72** [comment]
> Tienes que configurar el NGINX . Has seguido el guia que esta en la Wiki ? Cuales son los logs ? Errores ? En todo caso es cosa del NGINX . Si puedes haz un copy/past del NGINX config file

perfect I have not installed, NGINX do not even know what it is .. haha ​​could you pass me the wiki guide?

**Comment by akhilleusuggo** [comment]
https://github.com/YouPHPTube/YouPHPTube/wiki/Set-up-my-own-Stream-Server
