### ISSUE TITLE
Cannot enable plugins

### ISSUE THREAD

**Issue by nicsport** [WWBN/AVideo#1940]
I cannot enable any plugin. I receive the Following errors. I didn't find any documentation about this problem. Can you help me please ?

[08-Aug-2019 07:38:21 Europe/Zurich] Array
(
    [0] => Array
        (
            [file] => /home/clients/0fcef2c17ea46c8c26f864b7a7d7f15d/stream_bienz_family/objects/mysql_dal.php
            [line] => 85
            [function] => log_error
            [args] => Array
                (
                    [0] => [sqlDAL::writeSql] Prepare failed: (1136) Column count doesn't match value count at row 1<br>
INSERT INTO plugins ( `` ) VALUES ()
                )

        )

    [1] => Array
        (
            [file] => /home/clients/0fcef2c17ea46c8c26f864b7a7d7f15d/stream_bienz_family/objects/Object.php
            [line] => 214
            [function] => writeSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => INSERT INTO plugins ( `` ) VALUES ()
                )

        )

    [2] => Array
        (
            [file] => /home/clients/0fcef2c17ea46c8c26f864b7a7d7f15d/stream_bienz_family/objects/plugin.php
            [line] => 297
            [function] => save
            [class] => ObjectYPT
            [object] => Plugin Object
                (
                    [id:protected] => 
                    [status:protected] => active
                    [object_data:protected] => null
                    [name:protected] => CustomizeAdvanced
                    [uuid:protected] => 55a4fa56-8a30-48d4-a0fb-8aa6b3f69033
                    [dirName:protected] => CustomizeAdvanced
                    [fieldsName:protected] => Array
                        (
                        )

                    [pluginversion] => 1.0
                )

            [type] => ->
            [args] => Array
                (
                )

        )

    [3] => Array
        (
            [file] => /home/clients/0fcef2c17ea46c8c26f864b7a7d7f15d/stream_bienz_family/objects/pluginSwitch.json.php
            [line] => 44
            [function] => save
            [class] => Plugin
            [object] => Plugin Object
                (
                    [id:protected] => 
                    [status:protected] => active
                    [object_data:protected] => null
                    [name:protected] => CustomizeAdvanced
                    [uuid:protected] => 55a4fa56-8a30-48d4-a0fb-8aa6b3f69033
                    [dirName:protected] => CustomizeAdvanced
                    [fieldsName:protected] => Array
                        (
                        )

                    [pluginversion] => 1.0
                )

            [type] => ->
            [args] => Array
                (
                )

        )

)

[08-Aug-2019 07:38:21 Europe/Zurich] [sqlDAL::writeSql] Prepare failed: (1136) Column count doesn't match value count at row 1<br>
INSERT INTO plugins ( `` ) VALUES ()

**Comment by DanielnetoDotCom** [comment]
I have never seen this error before and it does not make sense for me.

I guess you miss something on the installation.


what is your OS version?

**Comment by nicsport** [comment]
Hello,

For your information, alter many tries, I could now enable and disable plugins without the mentioned error.
The problem come from the language. My previous tries were done in French. I tried then to install it with the default “english” and it works. 

Best regards

**Comment by akhilleusuggo** [comment]
Could you update your script ? Go to the location of your streaming site and update the script ( git pull )
