### ISSUE TITLE
some videos does not play.

### ISSUE THREAD

**Issue by honeyfairy** [WWBN/AVideo#1943]
![Capture](https://user-images.githubusercontent.com/17691989/62821849-b1cec380-bb7b-11e9-9c67-1a7072c4f74a.PNG)

Issues in blue and red
theses videos do not play.
Any reason?

**Comment by akhilleusuggo** [comment]
Those videos does not exist on your server . Make sure to check YouPHPTube and find them ( you will not find them )

Possible issues :
1- The encoder was not able to encode them or were not sent to the streaming server
2- The encoder encode them , but not enough permission to send them from the encoder to the streaming server
3- The encoder stopped working for some reason ( like when you restart apache2 )

Check the logs of your streaming site , and most important your Encoder site ( check the logs and link them here if you want )

Good luck
