### ISSUE TITLE
Issues Saving User Images

### ISSUE THREAD

**Issue by SamuelDSelf** [WWBN/AVideo#1947]
I have YouPHPTube running in a jailed environment and I get no errors, as far as I can tell, when I try to upload user pictures/backgrounds.  It has worked once but it usually just stops trying.  No errors, no errors in the log, etc.  I've been watching the log:   videos]# tail -f youphptube.log

So far everything else seems to work fine.  Does saving user images depend on a binary to resize things?

**Comment by DanielnetoDotCom** [comment]
as long as it has no errors, it is very hard to help you.

try to check for an javascript error instead a PHP error.

**Comment by TheOmnicron** [comment]
same error. just disable site caching or wait a few minutes

**Comment by SamuelDSelf** [comment]
I don't have the cache plugin enabled and I don't see anywhere that has a cache setting outside of that.  Plus, I've tried this after letting it sit for days and it still will not upload the user images.  I can upload the site logo/branding image without any issues.  The console appears to issue 1 error
![Screenshot_2019-08-29_10-18-10](https://user-images.githubusercontent.com/636925/63953373-d3b6ba00-ca46-11e9-9e67-2711f677d869.png)

**Comment by TheOmnicron** [comment]
still problems? i will try to help u

**Comment by TheOmnicron** [comment]
i created a profil. worked all fine. i uploaded avatar and background

**Comment by TheOmnicron** [comment]
after changing the pics, go to ur channel the check the pictures. if there are still the old ones, press on ur keyboard Ctrl + F5.

**Comment by TheOmnicron** [comment]
u can disable cache-control in html header. just google for HTML header cache-control. but ur page will be generate more data traffic.
or hard coded in the script or with a plugin. set an hash or timestamp to user avatar. "avatar.jpg?hash" if u need help u can mail me. my email adress is registered an ur page. profil Omnicron
