### ISSUE TITLE
Ad video impossible to add

### ISSUE THREAD

**Issue by illias1** [WWBN/AVideo#1949]
Hey!

Thank you for your hard work, it's amazing!

I have a problem with the AD_Server: it's active and I can start a campaign. But when I try to add a video to it, the URL field cannot be selected for input (the name field, however, is ok).
What's the problem? How to solve it?

Thank you in advance:)

**Comment by DanielnetoDotCom** [comment]
This problem is not clear for me.

try some screenshots

**Comment by illias1** [comment]
<img width="1215" alt="ads_problem" src="https://user-images.githubusercontent.com/54018215/62992778-ce2a7300-be8f-11e9-863e-9c4178f92d92.png">

**Comment by DanielnetoDotCom** [comment]
I see, the URL is auto filed, you need to search the video by the title

![image](https://user-images.githubusercontent.com/18009293/63024669-0cb73200-be7e-11e9-8f7f-0c9f6415e354.png)

**Comment by xemtube** [comment]
Video ads must be uploaded to your web site. When you enter a title, the url will be automatically filled in.

**Comment by DanielnetoDotCom** [comment]
another thing, ads MUST be encoded in MP4, does not work for HLS encoder, and webm is not tested yet

**Comment by illias1** [comment]
I see, thank you.
Where exactly do ads need to be uploaded? Because even if I have public/private videos I still can not enter the name in the field, so no options are available...

**Comment by akhilleusuggo** [comment]
Need to be uploaded to your server . You can upload them to the encoder , after the encoder ends , check the video on your site . Make sure it's working . Give it a name like '' Ads1 '' , go to the plugin , search for "ads1" , you should see it .

**Comment by mrtick2002** [comment]
I've noticed that those videos show up in the feed. Is there a way to make the ad videos private so they don't show up on the frontpage?

**Comment by DanielnetoDotCom** [comment]
@mrtick2002 if you make them unlisted, does not it work for you?
