### ISSUE TITLE
Plugin Not Found: oncologytube

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#1954]
[14-Aug-2019 15:09:30 UTC] Plugin Not Found: oncologytube
[14-Aug-2019 15:09:45 UTC] Plugin Not Found: oncologytube
[14-Aug-2019 15:09:47 UTC] Plugin Not Found: oncologytube
[14-Aug-2019 15:10:07 UTC] Plugin Not Found: oncologytube
[14-Aug-2019 15:12:27 UTC] Plugin Not Found: oncologytube

I'm getting this error trying the plugin BulkEmbed

**Comment by DanielnetoDotCom** [comment]
OMG, it not suppose to be there.
I will remove it

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I still can't embed videos , on anyway . I mean you can embed video by video ( on  My Videos>Embed a video Link > Past the link . I can not . It works very strange , the video is added ( not always , with a title like this kfjds54fd5s4f65s4df65s4 ) .
BTW , I have git pull and updated to 7.5 , logged out and logged in , in case that updates the user rights , and nothing . Got the API Key ( and removed the restriction ) , enabled the Youtube Data API v3 , no results . When I click on the search bar for a videos or a keyword , the chat log pops :

> [15-Aug-2019 20:55:03 UTC] encryptPasswordVerify: encrypt
> [15-Aug-2019 20:55:03 UTC] user::login: Do login without cookie
> [15-Aug-2019 20:56:57 UTC] Plugin Not Found: oncologytube
> [15-Aug-2019 20:57:05 UTC] Plugin Not Found: oncologytube
> [15-Aug-2019 21:01:27 UTC] Plugin Not Found: oncologytube
> [15-Aug-2019 21:01:32 UTC] Plugin Not Found: oncologytube
> [15-Aug-2019 21:01:36 UTC] Plugin Not Found: oncologytube
> [15-Aug-2019 21:01:40 UTC] Plugin Not Found: oncologytube

2 days ago was working fine , I don't know what happens

**Comment by DanielnetoDotCom** [comment]
Today I sent many updates related to embed videos.

can you update your site and try again? also please try to reproduce it on the demo site

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Works ! Sadly not perfect , when I type I keyword ; example YouPHPTube and i get many idea , when I click on embed all , it doesn't always , it may embed only 3 , or 7 or 1 or none . Like it's get stuck

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo what exactly page are you talking about?

**Comment by akhilleusuggo** [comment]
When you click on the the ''search'' button on the plugin , it takes you to the page where you can search for the videos

**Comment by DanielnetoDotCom** [comment]
Sorry, I am a bit lost here, are you talking about bulk embed videos?

**Comment by akhilleusuggo** [comment]
yes

**Comment by DanielnetoDotCom** [comment]
Hi, I am not sure if is that what you mean, but I just sent an update so when you click on the search button it will submit the search
