### ISSUE TITLE
Javascript error  "Player undefined"

### ISSUE THREAD

**Issue by ExeCRabLE2** [WWBN/AVideo#1955]
hello,
We got the following error in  the browser console.
> A Javascript-error happend. Please tell your admin to clear the folder videos/cache. 
>  If this doesn't help, attach these infos to a github-pull-request: 
>  Msg:TypeError: player is undefined 
>  Url: https://videos.example.com/video/videtitel, line: 689, Address: /video/videotitel

We clear the cache directory, but it does not help.

**Comment by DanielnetoDotCom** [comment]
I guess it does not affect your site.

if does, please give us more details.
