### ISSUE TITLE
ERR_RESPONSE_HEADERS_TOO_BIG

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#1958]
I'm getting this error only when I visit this path of the site 
https://domain.com/charts

On the site is the dashboard , is not able to make the calculation or something like this for the limitation fo kb , but I have no idea how to change it or list it into multiple parts

**Comment by DanielnetoDotCom** [comment]
the dashboard will be reviewed soon, thanks for notice
