### ISSUE TITLE
Integrate Promoted Videos into Mobile Apps

### ISSUE THREAD

**Issue by KenRHill** [WWBN/AVideo#1959]
Greetings Daniel,

One thing that I thought would be a good suggestion for YouPHPTube and the mobile apps, would be to integrate the promoted videos to show up in the top row in the mobile app versions like they do on the website.  That way if somebody pays to promote their videos, they will actually be promoted on both the website and the mobile apps at the same time.  Currently, promoted videos do not show up on either of the mobile app versions, however they do show up on the streamer website.

**Comment by DanielnetoDotCom** [comment]
Thanks, you are right, I just added it on our TODO list
