### ISSUE TITLE
Tips for optimization ?

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#1961]
After uploading/Embedding dozens of videos , the site become so laggy . Taking a look on the resources used , it actually not using much . I'm not sure about this , but looks like the DB sql doesn't not use more then 1 core . I have made this tests :

#Server1 : 1core ( 3.5ghz ) 4GB RAM ( 1TB storage , 50Gb SSD ) , the SSD is for the BD and system only mounted on ''/'' , the HDD is mounted on /var/www/html
Loading the site , checking heavy pages the CPU usage is 100% , the RAM may vary depending on number of requests
Server2 : 8cores ( 3.5ghz ) 32GB RAM ( 1TB storage , 50GB SSD ) , same thing as above
Loading the site on heavy pages uses only 10-15% of each core , witch makes like only 1 core is being used . 

Any way to optimize this and make more use of the CPU and resources of the server ?

**Comment by DanielnetoDotCom** [comment]
Yes, the thing is when you are encoding it will uses CPU, if you have only one CPU your system will slowdown, that is why I recommend at least 2 CPUS.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I do never encode on the streamer server. I've dedicated encoder servers . So it's not my case.

**Comment by SubjectXXX** [comment]
Well, just check which processes are using your 1core server..

Do you have cache enabled? Maybe the bandwidth is the culprit?

**Comment by akhilleusuggo** [comment]
@SubjectXXX I have 3gb/s , cache enabled , and apache -k start uses a lot. also mysql --daemonize --pid-file=/run/mysql/mysql.php
