### ISSUE TITLE
Download file button text

### ISSUE THREAD

**Issue by chinobaingo** [WWBN/AVideo#1962]
When you change “uploadButtonDropdownText” to a custom text it also adds this text to the download button under each video on the gallery page.

Can we have custom text on the download button separate from text in the drop down text?

**Comment by DanielnetoDotCom** [comment]
Right now we do not have this option, but it is possible.

It may be add in future versions.

**Comment by chinobaingo** [comment]
Well then is there a way to stop it from changing the download button text? 

When you change the menu name it also changes the download button text under each thumbnail.

**Comment by DanielnetoDotCom** [comment]
The only way I can see now is coding something
