### ISSUE TITLE
Chat feature

### ISSUE THREAD

**Issue by chinobaingo** [WWBN/AVideo#1963]
Is it possible to get a chat feature?

I get asked often if we can have integrated chat for all users not just livestream.

**Comment by mikweb2017** [comment]
you can install for example a rocket chat server and copy the code by adding it to YouPHpTube works great

**Comment by tiplovo** [comment]
> вы можете установить, например, сервер rocket chat и скопировать код, добавив его в YouPHpTube отлично работает
> ![Bildschirmfoto 2019-08-18 um 11 22 39](https://user-images.githubusercontent.com/30271757/63222614-a9ddd780-c1aa-11e9-89e8-f5fea7ebe246.png)

Это куда его скопировать?И какой код?

**Comment by mikweb2017** [comment]
esample:

 <script defer="defer" async="async" type="text/javascript">
        require([ 'jquery' ], function ($) {
            (function(w, d, s, u) {
                w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
                var h = d.getElementsByTagName(s)[0], j = d.createElement(s);
                j.async = true; j.src = 'https://rc.example.com/packages/rocketchat_livechat/assets/rocket-livechat.js';
                h.parentNode.insertBefore(j, h);
            })(window, document, 'script', 'https://rc.example.com/livechat');
        });
    </script>

**Comment by chinobaingo** [comment]
That will work for now but still really inconvenient to have to scroll to bottom or top of page. To be able to have it centered in sidebar would be ideal so people could chat WHILE watching videos on the same page.

**Comment by chinobaingo** [comment]
Thanks for all the help!
