### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by clienttask** [WWBN/AVideo#1965]
Hello,

The LiveLinks plugin works very nice. It can be very useful for IPTV if it comes with category and EPG url field.

Thanks.

**Comment by DanielnetoDotCom** [comment]
What is the IPTV file extension?

do you have a link sample?

**Comment by clienttask** [comment]
Hello,

Most IPTV use M3U file extension which already works on LiveLinks plugin. EPG (Electronic Programme Guide) normally XML feed of TV programme guide. See example http://www.webgrabplus.com/sites/default/files/download/ini/info/siteini.pack/Ireland/eirsport.ie.channels.xml

**Comment by DanielnetoDotCom** [comment]
Great, but how can I grab the M3U8 from the XML?

**Comment by DanielnetoDotCom** [comment]
maybe do you mean to create a XML for the livelinks?

**Comment by clienttask** [comment]
Hello,

Yes, both can be different url fields. You can create EPG data in .xml format using the following parameters :
channel_id
channel_number
title
short_name
short_description
program_start
program_end
long_description

**Comment by DanielnetoDotCom** [comment]
but I notice they are different, there is an standard that work in all TVs?

**Comment by clienttask** [comment]
I think you can look into Schedules Direct (http://www.schedulesdirect.org) and XMLTV format http://wiki.xmltv.org/index.php/XMLTVFormat.

**Comment by DanielnetoDotCom** [comment]
that would be nice, I am new on IPTV, if you can create it will help

**Comment by DanielnetoDotCom** [comment]
What XML standard do you recommend? I still a bit lost

**Comment by clienttask** [comment]
I will recommend XMLTV standard. Please, check https://github.com/jaylinski/xmltv .

Please, may I know the email I should send the installation? I will send you IPTV platform and access to the VPS server.

**Comment by DanielnetoDotCom** [comment]
sure, please send it to developer@youphptube.com

**Comment by clienttask** [comment]
Please, check your email, I sent the platform.

**Comment by DanielnetoDotCom** [comment]
I am quite busy now, but I will take a look on it soon

**Comment by clienttask** [comment]
Whenever you will be ready. Little modification can make it compete many platforms.
