### ISSUE TITLE
twitter share button not working

### ISSUE THREAD

**Issue by joey2354** [WWBN/AVideo#1968]
Hi there, the twitter share buttons not working atm

thank you

**Comment by DanielnetoDotCom** [comment]
I just tested on my site and it works fine

![image](https://user-images.githubusercontent.com/18009293/63262364-1b299300-c25c-11e9-926a-4e46620da3d3.png)

**Comment by joey2354** [comment]
you need to test it my site then

**Comment by DanielnetoDotCom** [comment]
I guess the first step is to update your site.

try this https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

**Comment by joey2354** [comment]
Ok but in my admin panel it says already updated 

_You are running YouPHPTube version 7.2!
Your system is up to date_

**Comment by akhilleusuggo** [comment]
@joey2354 Well , that's wrong , because we're at 7.5 
```
You are running YouPHPTube version 7.5!
Your system is up to date
```
You need to go to /var/www/html/YouPHPTube > git pull > go back to your streaming admin panel > Update version > You should see the new versions

**Comment by joey2354** [comment]
it's working now thank you for the help
