### ISSUE TITLE
Error creating sitemap

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#1974]
Error not creating a sitemap. The screen appears only to be running and then hangs.

![image](https://user-images.githubusercontent.com/50126312/63272530-6d9f9980-c2c6-11e9-9dd9-ddd08b7716a3.png)

And I can not access the link https://xemtube.online/sitemap.xml

**Comment by DanielnetoDotCom** [comment]
please check this 

![image](https://user-images.githubusercontent.com/18009293/63273911-3d7bda80-c275-11e9-8398-561d95df1f6a.png)

**Comment by xemtube** [comment]
I have granted sudo chmod 777 /var/www/html/YouPHPTube/sitemap.xml many times before but it still doesn't work

![image](https://user-images.githubusercontent.com/50126312/63274290-b9077700-c2c9-11e9-9833-b3b95cd266bc.png)

**Comment by DanielnetoDotCom** [comment]
please check your error log. should be something there.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Daniel same error here . Nothing on logs. It's a problem that happens when your site has open 3000-4000 links . Like the /chart that I have reported earlier

**Comment by DanielnetoDotCom** [comment]
I see, maybe the sitemap is too big

I sent some changes to limit it. please confirm if it is working now.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Omfg , that was so quick generation of sitemap ( I have 12.000 links , generated on less then a second , and no overload on CPU ) . Before was overloading the cpu for a really long time and stopping . 
-Feedback : Works perfectly now

EDIT: No , very bad , yes surprising . The sitemap actually only generated 123 links . After updating the sitemap on the google webmaster , the links droped from 12.000 to 123 ... :( sad CEO xD

Any news @DanielnetoDotCom about the /charts , i'm still getting 
```
This site can’t be reached The webpage at https://domain.tld/charts might be temporarily down or it may have moved permanently to a new web address.
ERR_RESPONSE_HEADERS_TOO_BIG
```
Any way similar way to do here to ?

**Comment by DanielnetoDotCom** [comment]
Carts, I will review, and probably limit it as well.

I limited the sitemap for 100 records for users, categories, channels  and videos

do you think I should make this number bigger?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom How do I manage my 12000 links then if you limit it to 100 ?  I hope you get back the old bugged sitemap

**Comment by DanielnetoDotCom** [comment]
what about if you can customize it?

![image](https://user-images.githubusercontent.com/18009293/63365661-6cb24a80-c34e-11e9-91ad-2e11d4d90c8f.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom That's really cool , but still doesn't fix the problem . I mean , now i'm able to generate all the links back again . But what is the point of putting a number / limiting the sitemap ?
The error is still the same : Processing... without end BUT , the sitemap has been created ( I confirm that ) just the message ''Processing...'' won't disappear

**Comment by DanielnetoDotCom** [comment]
I see, even if it is a small number it keeps processing?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom No daniel , around 600-700 on my second site is OK , on other site with a large number it just can't handle it . To know when I can refresh the page 'F5' , I just open the terminal , htop and wait until the CPU drops from 100% ( while generating ) until 1-2% when I know has finished , when F5 while is processing

**Comment by DanielnetoDotCom** [comment]
Ok, I guess it is a memory_limit or a max_execution_time issue, I just sent an update to unlimit both

**Comment by DanielnetoDotCom** [comment]
Multiple site maps may be a solution, how do you think they should be named?

**Comment by akhilleusuggo** [comment]
Blogger ( Google ) , does generate 1 sitemap every 150 posts ( but we can go up to 1000 )
On blogger the sitemaps where created like this : 

<loc>http://www.example.com/sitemap.xml?page=1</loc>
<loc>http://www.example.com/sitemap.xml?page=2</loc>
<loc>http://www.example.com/sitemap.xml?page=3</loc>
<loc>http://www.example.com/sitemap.xml?page=4</loc>

So actually was giving them a page , but in case we don't want that , just sitemap1.xml , sitemap2.xml
I've git pull and tried , and the problem persists ''Processing...''
