### ISSUE TITLE
 Plugin Bulk Embed has not filtered out videos that are not played back on the web when embedded Url Playlist. Can you fix this error

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#1978]
Plugin Bulk Embed has not filtered out videos that are not played back on the web when embedded Url Playlist. Can you fix this error.

https://www.youtube.com/watch?v=CxrFoy_QEFc&list=LLMAGTnvvCaSHnmZH5eNRXPQ

**Comment by DanielnetoDotCom** [comment]
I set `videoEmbeddable: "true" `on the API, for some reason YouTube API still bringing it.
I also tried `videoSyndicated: "true" ` but seems to not make any difference

I guess is something else

I google for that and I found the same issue, but I could not find any work around
