### ISSUE TITLE
what are the server requirements for this script please ?

### ISSUE THREAD

**Issue by joey2354** [WWBN/AVideo#1984]
hi 
what are the server requirements for this script please ? 

I'm going to do it myself on my own server, i can add a link in the footer for you no problem just for the help you've given over the past year.

thank you

**Comment by DanielnetoDotCom** [comment]
Please check here https://github.com/YouPHPTube/YouPHPTube/wiki/YouPHPTube-hadware-requirements

**Comment by joey2354** [comment]
thank you Daniel
