### ISSUE TITLE
Feature Request - Affiliates/Partners

### ISSUE THREAD

**Issue by mrtick2002** [WWBN/AVideo#1985]
I think we need a way to choose which content creators are eligible to share in ad revenue. 

I've noticed on my old installation that  spammers would put crap videos on my platform and then send bots (or whatever) to increase views. If we're paying ad revenue, we need to be able to control who actually gets it.

**Comment by joey2354** [comment]
_" then send bots (or whatever) to increase views "_  bots are not people therefore generate zero money 


the reason they have _"would put crap videos on my platform"_


crap videos don't earn money



i maybe wrong
