### ISSUE TITLE
Live streaming notification Vs Cache 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#1989]
I'm setting my cache time duration to 14400s , on that main time , if anyone streams , it just doesn't show the notification unless I clean the cache . Anyway to fix this ? Same happens with the thumbnail

**Comment by DanielnetoDotCom** [comment]
if you reduce the cache time duration does it show correctly?

**Comment by akhilleusuggo** [comment]
Yes , but not always . I just did a test 10s cache and apparently it does show when I go live 10-15s after I refresh the page . When I had the cache 14400 ( 4h ) , all users had to wait 4h before to be able to see if there's any recent activity on the notification , or manually clear the cache from the admin panel
