### ISSUE TITLE
Feature Request - Custom Thumbnail - Live Stream

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#1993]
I see that all live streams got the same thumbnail that can be edited on the web server . The default one comes with a red circle - ''On Air '' . But I'll leave it here as a feature request if possible to add for every user a custom thumbnail as for the videos , just this time for the live streaming videos

**Comment by JoshWho** [comment]
IT would also need to include OG graph tags for the page that way it share correctly on other networks.
