### ISSUE TITLE
Is it possible to broadcast TV programs?

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#1999]
how to do to broadcast TV programs?

**Comment by akhilleusuggo** [comment]
capture card > OBS > Stream it ( I'll not discuss with you if it's legal or not )

**Comment by palich91** [comment]
How can I broadcast http://194.67.209.145:2019/2022.stream TV online? How do I convect .stream streams

**Comment by palich91** [comment]
You can make such a module so that you can broadcast IPTV. For example, take video streams from .m3u of this kind: http://46.19.43.248:9981/stream/channelid/1313029335 and broadcast on your website

**Comment by palich91** [comment]
Thanks, I already figured it out myself
