### ISSUE TITLE
[ERROR] 404 No found after installing

### ISSUE THREAD

**Issue by HiiZun** [WWBN/AVideo#2000]
hello i have just installed a YouPhpTube on a shared hosting provider (1&1 ionos) i have used the tutorial for install it on a 000webhost recorded by the owner of this project (since 2017) https://www.youtube.com/watch?v=HI8dBaS-AVw
and i have all good no error and the database has been configured 
![image](https://user-images.githubusercontent.com/44111470/63882659-bfd17080-c9d2-11e9-9696-c5e024063484.png)
but when i want connect to the website where is installed YouPhpTube 
(http://video.youtube-bot.com)
![image](https://user-images.githubusercontent.com/44111470/63882721-df689900-c9d2-11e9-8d89-3aa68b0a8962.png)

i have a 404 error no found

**Comment by ChrisSlS** [comment]
Hey

Difficile à dire sans autre information... Tu peux envoyer le contenu du fichier error.log (apache) et aussi /vidéo/youphptube.log ?

**Comment by akhilleusuggo** [comment]
@HiiZun vous n'avez pas installé le site dans le correct répertoire '' Apache root '' 
Si vous utilisez apache2 , vous devez spécifier le répertoire , /var/www/html/NonDuFichier , example/var/www/html/YouPHPTube
@ChrisSlS je ne pense pas qu'il aura quoi que ce soit dans les logs puisqu'il ne peut même pas accéder au site. youphptube.log doit donc etre vide.

**Comment by HiiZun** [comment]
the problem is that it is a shared web host and I do not think I have access to apache configuration files

**Comment by akhilleusuggo** [comment]
On your control panel  then

**Comment by HiiZun** [comment]
okay

**Comment by HiiZun** [comment]
i have check and the subdomain is been connected to the subdirectory

**Comment by akhilleusuggo** [comment]
could you share it with us ? Could you tell what subdirectory ? did you used git clone to download the site or you have uploaded it manually ?

**Comment by tiplovo** [comment]
Я так понимаю скрипт поставили на бесплатный хостинг!он не будет там работать....

**Comment by akhilleusuggo** [comment]
@tiplovo не безплонтный а поделенный . За то что у него нет как то так зайти на араше2 он не может показать рут /YouPHPTube

**Comment by tiplovo** [comment]
> @tiplovo не безплонтный а поделенный . За то что у него нет как то так зайти на араше2 он не может показать рут /YouPHPTube

если у него нет доступа к конфигам сервера то даже тех поддержка не поможет

**Comment by akhilleusuggo** [comment]
ну он дальжно быть какой то панель конфигурации
