### ISSUE TITLE
First page with default video

### ISSUE THREAD

**Issue by one1page** [WWBN/AVideo#2008]
Is there any plugin available where we can select which video will be shown on first page as default video?

**Comment by akhilleusuggo** [comment]
no

**Comment by DanielnetoDotCom** [comment]
You can suggest a video 

![image](https://user-images.githubusercontent.com/18009293/64174484-c1b28e00-ce2f-11e9-8a43-4dfc864ea7dd.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom That is to suggest , not to suggest xD

PS: I've tried it and it works , witch mean you have bad wrote it on the html alt=

**Comment by DanielnetoDotCom** [comment]
Sorry, I still don't get what is bad wrote

can you help me?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Should be written : Suggest instead of Unsuggest . That's why never tried it out
![image](https://user-images.githubusercontent.com/52116577/64331052-070ac300-cfca-11e9-8932-91201df703c1.png)

**Comment by DanielnetoDotCom** [comment]
I sent an update, I hope is correct now.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom It's perfect 👍
