### ISSUE TITLE
Delete messages in the Livechat Plugin and block some users in Livechat

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#2013]
There are already some users who chat with pornography in the livechat section.I have a way to delete the content of a user in the livechat plugin, and can I block a user from chatting in the livechat section? ?

**Comment by akhilleusuggo** [comment]
for the moment only from DB as far as I know . The live chat plugin is really the worst plugin . I recommend not using it at all .
The Css is really bad , moving all across the page( not a fixed location ) , no anti spam , no emoji nothing .

- Possible solution: 
+Make only registered/Logged in users can chat .

This for sure gonna end up with the pornography ( the same problem I had ) 
I recommend to set up your own chat as I've seen on other tread talk ( Rocket.Chat )

**Comment by JoshWho** [comment]
It is a old plugin and there is a future project coming up for chat that will be available hopefully real soon. Just keep a eye out for it in the Store.
