### ISSUE TITLE
Mobile App - Recommended videos

### ISSUE THREAD

**Issue by mrtick2002** [WWBN/AVideo#2014]
The mobile app needs recommended videos on the player page. You watch a video on the app and it doesn't go to another video or suggest any other videos. Can we get that?

**Comment by DanielnetoDotCom** [comment]
do you mean next video?

**Comment by mrtick2002** [comment]
Yes. That's part of what keeps people on youtube and the other platforms. That's why you end up watching a video about physics, but end up watching stuff about the Illuminati and fights between bears and eagles,

**Comment by JoshWho** [comment]
Sounds like a great idea to me. The more engagement the better.
