### ISSUE TITLE
Steaming Server Not Working

### ISSUE THREAD

**Issue by TrippyTubeTV** [WWBN/AVideo#2017]
I have used YouPHPTube in the past without any issues but I am struggling to get live streaming to work correctly on my new site. As far as I am aware everything is configured correctly. 

The issue is not SSL related as far as I know. The issue is happening even without any SSL enabled. Essentially the live streaming is working but not reporting it to YouPHPTube as it states its offline. I have set up a vhost on apache for a nonssl version of the site and have my NGINX config setup to go to that. What I noticed and where I think the problem is that the stat page is not showing the stream key. It's showing the plugin path. On top of that, one thing I noticed is that the plugin path is starting with HTTPS when that URL should be HTTP. I have tried several times reinstalling the server on ubuntu 16.04 and 18.04. The issue happens on both. I can't seem to get past it. I have my config below as well as screenshots. Any help would be appreciated. 

nginx.conf below

  worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://nonssl.trippytube.tv/plugin/Live/on_publish.php;
                            on_play http://nonssl.trippytube.tv/plugin/Live/on_play.php;
                            on_record_done http://nonssl.trippytube.tv/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   
            }
            server {
            	listen 444 ssl;
    			listen [::]:444 ssl;
                server_name live.trippytube.tv;
    			ssl_certificate      /etc/letsencrypt/live/live.trippytube.tv/fullchain.pem;
    			ssl_certificate_key  /etc/letsencrypt/live/live.trippytube.tv/privkey.pem;
                
                #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    } 
                
            }
    }

Other screenshots:

![Screen Shot 2019-09-04 at 6 42 59 PM](https://user-images.githubusercontent.com/54918349/64300769-2531de00-cf4c-11e9-9201-e0eaf558f19d.png)
![Screen Shot 2019-09-04 at 6 42 39 PM](https://user-images.githubusercontent.com/54918349/64300770-2531de00-cf4c-11e9-96c8-93b1d3f9df9f.png)
![Screen Shot 2019-09-04 at 6 43 17 PM](https://user-images.githubusercontent.com/54918349/64300771-2531de00-cf4c-11e9-8f2d-c0b9e7a174e8.png)

**Comment by TrippyTubeTV** [comment]
Seems to be the same issue as described here but I see no resolution https://github.com/YouPHPTube/YouPHPTube/issues/1914

**Comment by TrippyTubeTV** [comment]
After trying to diagnose the issue more, I can confirm that live links are NOT working as well.

**Comment by akhilleusuggo** [comment]
@TrippyTubeTV Yeh , that was the issue I had , and the title of this topic is really misleading . I had that problem and fixed it as you can see on the topic that I've opened

**Comment by akhilleusuggo** [comment]
@TrippyTubeTV #1945 Please check this one not #1914
