### ISSUE TITLE
Strong Server but My Stream freezes why

### ISSUE THREAD

**Issue by lamadya** [WWBN/AVideo#2018]
sorry my first issue Closed by error
Hi
My Stream freezes why
I have 2 high server but my stream Freezing after seconds
Server one on contabo
CPU : 1-2 x Intel Xeon E5 2630v4 1-2 x (10 x 2.20 GHz)
RAM : 256 GB REG ECC
Port / bandwidth : 1 Gbit/s port UNLIMITED Traffic
Operating system : Ubuntu 16.04
Using Your Tutorial For install YouPHPtube And NGINX RTMP
Sent stream Via FFMPEG With Loop
Code Loop {
#!/bin/bash
while :; do
ffmpeg -re -i http://adtv.ercdn.net/adsport2/adsport2_720p.m3u8 -s hd720 -r 60 -g 60 -b:v 3M -c:v libx264 -x264-params keyint=60 -bufsize 500k -c:a aac -strict -2 -ar 44100 -b:a 128k -f flv rtmp://myipserver/live?p=4adc701664135e50b2354496086d53dd/5d70337586747 </dev/null > /dev/null 2>&1
done &
}

Server Two From a local distributor
RAM 16 GB
Processeur CPU 8 Cores / 8 Threads [Intel Atom™ 2,5 GHz]
Débit Internet 1 Gb/s (Garanti 700 Mb/s)
Operating system : Ubuntu 16.04
Using Your Tutorial For install YouPHPtube And NGINX RTMP
Sent stream Via FFMPEG With Loop
Code Loop {
#!/bin/bash
while :; do
ffmpeg -re -i http://adtv.ercdn.net/adsport2/adsport2_720p.m3u8 -s hd720 -r 60 -g 60 -b:v 3M -c:v libx264 -x264-params keyint=60 -bufsize 500k -c:a aac -strict -2 -ar 44100 -b:a 128k -f flv rtmp://myipserver/live?p=4adc701664135e50b2354496086d53dd/5d70337586747 </dev/null > /dev/null 2>&1
done &
}
This My Nginx Config http://lamadya.com/nginx.conf
But My Stream freezes why Please Help Me

@akhilleusuggo  You can check here and Thank you sir https://yallabeinhd.com/live/

sorry my first issue Closed by error

**Comment by akhilleusuggo** [comment]
@lamadya For some reason I don't see anything freezing ... I'm sure with the ffmpeg line that I gave you , it should not freezes .

**Comment by akhilleusuggo** [comment]
@lamadya Another thing to take in count , please run `htop` and take a look at the CPU usage , you're streaming more than 10 streams

**Comment by lamadya** [comment]
Thanks 
how to check my CPU

**Comment by akhilleusuggo** [comment]
@lamadya I've stayed on the previous comment . You can run ''htop'' or any other command . htop comes installed by default

**Comment by DanielnetoDotCom** [comment]
Hi, 

I had one customer that when he starts to have more than 50 users watching the live, it starts to freeze 

with the adaptive configuration, it grows to about 200 to start to freeze

https://github.com/YouPHPTube/YouPHPTube/wiki/Adaptive-Bitrates-on-Livestream

your problem may be the same
