### ISSUE TITLE
 Error creating Twitter ID and Key

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#2025]
When I create Create an twitter app, the Valid OAuth redirect URIs entry https://xemtube.tv/objects/login.json.php?type=Twitter gets an error
Query parameters are not allowed. How to add this url. Detailed error according to attached image file

![image](https://user-images.githubusercontent.com/50126312/64476171-d4252280-d1b5-11e9-9e1c-39a1c6254b4d.png)

**Comment by DanielnetoDotCom** [comment]
try to remove **?type=Titter**

**Comment by xemtube** [comment]
I have tried following your suggestion and successfully saved Callback URL. But when logging in with twitter account, this error message 

> Signed API request has returned an error. HTTP error 403. Raw Provider API response: <?xml version=1.0 encoding=UTF-8?><errors><error code=415>Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>.

![image](https://user-images.githubusercontent.com/50126312/64534174-26457f80-d33f-11e9-9e06-c9a10cc8935f.png)


Guide me to fix this error.

**Comment by xemtube** [comment]
I still can't use the login feature with my Twitter account. Have you tried using this login function on demo.Youphptube.com?
