### ISSUE TITLE
FEATURE REQUEST: Custom Video Thumbnails on Upload and Photo Upload Unique file names

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2028]
Would like to be able to upload my own thumbnail for manually uploaded videos. 

Also need to make all picture uploads generate new **unique file names** so you do not have to wait for Cache to clear including Cover Photo and Avatar. All User photos should get new names every time they change it.

**Comment by DanielnetoDotCom** [comment]
you can upload your own thumbs. dont you?

**Comment by JoshWho** [comment]
Yeah I can after. Im Talking during the upload on the encoder page. One that you can set right off the bat that doesn't get overwritten with the Auto Thumbnail Generated. Like how YT does it on theirs.
