### ISSUE TITLE
More resolution switch option

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2036]
Anyway to add more then 3 resolutions ? 144,240,360 ? I'm not talking about renaming them , I'm talking about to get more options

**Comment by DanielnetoDotCom** [comment]
The only way we have not to have more resolutions is with HLS

https://github.com/YouPHPTube/YouPHPTube/wiki/VideoHLS-Plugin#automatic-encoding-process-hls-only

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom But I saw many other sites using video.js with resolutions up to 2160p . What is the problem with adding more resolution ? It's a payed plugin with only 3 resolution , I almost feel it's a scam xD

**Comment by DanielnetoDotCom** [comment]
The problem is not Video JS. is to redesign the encoder and streamers and plugins to make work with more resolutions.
