### ISSUE TITLE
Have Live Stream configured but its not working

### ISSUE THREAD

**Issue by risleem** [WWBN/AVideo#2046]
I have installed YouPHPTube encoder and video on an Ubuntu 18.04 successfully. I just installed the Live Stream piece but its not working. I have installed on the LAN and trying to get it working internally before I put it externally. Here is a screen shot of my livestream page.  When I use OBS to test it I get the following "Failed to connect to server"

![image](https://user-images.githubusercontent.com/52410929/65200834-618a3180-da56-11e9-9666-8ea8d491f18d.png)

I can provide any other information needed. Please, I could use some help with this. Thanks

**Comment by tiplovo** [comment]
Нужно еще настроить Nginx для потоковой передачи

**Comment by DanielnetoDotCom** [comment]
I am pretty sure your NGINX is not running

**Comment by risleem** [comment]
So what can do to check if that is the case?

**Comment by DanielnetoDotCom** [comment]
check if your nginx is running?
how did you install it? and the RTMP module, how did you do?

**Comment by risleem** [comment]
I followed the instructions on the link below.
https://github.com/YouPHPTube/YouPHPTube/wiki/Set-up-my-own-Stream-Server

**Comment by tiplovo** [comment]
Если nginx не настроен то не будет работать ,проверьте работу сервера nginx

**Comment by akhilleusuggo** [comment]
Could you please copy/past what do you get on the console after you run this line ?
`sudo /usr/local/nginx/sbin/nginx`

**Comment by risleem** [comment]
OK, here you go, thanks
![image](https://user-images.githubusercontent.com/52410929/65334384-4a4f5f00-db90-11e9-8ade-a4a515a0c86c.png)

**Comment by DanielnetoDotCom** [comment]
@risleem for mee looks like you do not have NGINX installed

**Comment by risleem** [comment]
![image](https://user-images.githubusercontent.com/52410929/65431261-29cd1200-dde7-11e9-8f10-0f0872e69806.png)

**Comment by akhilleusuggo** [comment]
@risleem I'm pretty sure it will not work for you . You're using Ubuntu 18.04 ( and you followed the tutorial right )? You had many errors at the installation that you have ignored . First of all 

`sudo wget http://nginx.org/download/nginx-1.12.0.tar.gz` - Doesn't work on Ubuntu 18.04 try this 
`sudo wget http://nginx.org/download/nginx-1.16.1.tar.gz` - The tutorial are out dated , MAKE SURE TO READ WHAT'S MISSING ON THE INSTALATION ! You will have to install another command for `zliblg` 
`sudo apt-get install zlib1g-dev`

Hope it helps you

**Comment by DanielnetoDotCom** [comment]
you can not install nginx with apt-get, you need to compile one version with the RTMP module

**Comment by akhilleusuggo** [comment]
Forgot to mention that on Ubuntu 18.04 you have to use PHP7.2 not 7.0 like on the first line of the guide `sudo apt-get install build-essential libpcre3 libpcre3-dev libssl-dev php7.0-xml`
Try this `sudo apt-get install build-essential libpcre3 libpcre3-dev libssl-dev php7.2-xml`

**Comment by risleem** [comment]
I did change the it from 7.0 to 7.2 when I was installing it.

**Comment by risleem** [comment]
![image](https://user-images.githubusercontent.com/52410929/65438631-d0b7ab00-ddf3-11e9-9273-755405331d96.png)

**Comment by DanielnetoDotCom** [comment]
you still missing the nginx compilation.

please follow the full tutorial

**Comment by akhilleusuggo** [comment]
@risleem You have to reinstall everything , not only the command lines that I posted . Just remember to replace them . Then keep the guide

**Comment by maxlinux2000** [comment]
pelase update the tutorial. tnx
