### ISSUE TITLE
Problems immediately after installation

### ISSUE THREAD

**Issue by izumihiro** [WWBN/AVideo#2049]
My server is:
QNAP NAS  QTS Version 4.4.1.1064
PHP Version 7.3.7
MySQL 5.5.57-MariaDB
Apache web server 2.0

I installed the software, but it doesn't display well as.

/share/CACHEDEV1_DATA/Web/test/ is System Path to Application.

**Comment by tiplovo** [comment]
Очистите папку кешь,а так же у вас не настроем похоже mode rewrait

**Comment by izumihiro** [comment]
mod_rewrite is enabled in Apache settings.

httpd.conf
LoadModule rewrite_module modules/mod_rewrite.so

**Comment by akhilleusuggo** [comment]
<Directory /var/www/>
Options Indexes FollowSymLinks
AllowOverride `All`
Require all granted

Make sure you allow `All`

**Comment by DanielnetoDotCom** [comment]
in your configuration file try to ignore the automatic path creation 

you should have something like this in your configuration.php

```
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { 
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'http://yuming.fan/test/;
}
```

remove the first if

so you will replace the above code for this ...

```
$global['webSiteRootURL'] = 'http://yuming.fan/test/;
```
yes, that is right only one line of code

**Comment by izumihiro** [comment]
The Apache configuration is originally as follows.

DocumentRoot "/share/Web"
<Directory />
	Options FollowSymLinks
	AllowOverride None
	Require all denied
</Directory>
<Directory "/share/Web">
	Options FollowSymLinks MultiViews
	AllowOverride All
	Require all granted
</Directory>

and

As DanielnetoDotCom said, I replaced the code and reinstalled as follows, but the situation does not improve

objects/configuration.php

$global['webSiteRootURL'] = 'http://yuming.fan/test/;

**Comment by izumihiro** [comment]
Could this be due to this link setting?

[~] # ls -l /share/Web
lrwxrwxrwx 1 admin administrators 18 2019-09-19 17:13 /share/Web -> CACHEDEV1_DATA/Web/

**Comment by maxlinux2000** [comment]
it's easy to fix

please have a look to your document root directive. probably look like this

DocumentRoot "/var/www/html/YouPHPTube/"

and MUST look like this one (remove the last slash)

DocumentRoot "/var/www/html/YouPHPTube"

then service apache2 restart and enjoy

**Comment by izumihiro** [comment]
> it's easy to fix
> 
> please have a look to your document root directive. probably look like this
> 
> DocumentRoot "/var/www/html/YouPHPTube/"
> 
> and MUST look like this one (remove the last slash)
> 
> DocumentRoot "/var/www/html/YouPHPTube"
> 
> then service apache2 restart and enjoy

As I wrote before, my Apache document root configuration(http.conf) doesn't end with a slash
DocumentRoot "/share/Web"

Is there any file to fix other than Apache configuration?
Which file should I fix?
Please tell me specifically

**Comment by izumihiro** [comment]
My Apache document root configuration is
DocumentRoot "/share/Web"

"/share/Web" is symbolic link to "/share/CACHEDEV1_DATA/Web"

**Comment by maxlinux2000** [comment]
"/share/CACHEDEV1_DATA/Web" ??

are you using qsnap? or something alternative from apt-get to install apache?

The instructions tell us to use ubuntu (18.04) or debian (9) as OS,
and both have the web root in /var/www/html.

**Comment by izumihiro** [comment]
> "/share/CACHEDEV1_DATA/Web" ?? are you using qsnap? or something alternative from apt-get to install apache? The instructions tell us to use ubuntu (18.04) or debian (9) as OS, and both have the web root in /var/www/html.
> […](#)
> On 9/21/19, izumihiro ***@***.***> wrote: My Apache document root configuration is DocumentRoot "/share/Web" "/share/Web" is symbolic link to "/share/CACHEDEV1_DATA/Web" -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#2049 (comment)](https://github.com/YouPHPTube/YouPHPTube/issues/2049#issuecomment-533780379)

I am using qnap
Shouldn't I ask you to install on qnap here?

**Comment by maxlinux2000** [comment]
You can, but I don't use qsnap, so I can't help. The simplest way is to use
Debian 9 or Ubuntu 18.04 stock, and follow the manual.
Use other tools or OS, exposed you to found errors not reproducible for
others youphptubers so the help that we can do is limited

**Comment by izumihiro** [comment]
I was able to easily install this app on other Linux distribution servers.
So this time I bought QNAP in order to run this app in earnest.
It ’s a shame that it ca n’t operate well.
I would like to borrow the wisdom of those who are operating well with QNAP.

**Comment by maxlinux2000** [comment]
The only help that I can do is a google search for you

https://www.google.com/search?newwindow=1&sxsrf=ACYBGNTSnENj4EoTFca5VOIc_udjossJqQ%3A1569095589238&ei=pX-GXbyPDoKAjLsP1P-YiAc&q=apache2+trailing+slash+qsnap&oq=apache2+trailing+slash+qsnap&gs_l=psy-ab.3..33i160l2.2452.4481..4753...0.0..0.129.677.0j6......0....1..gws-wiz.......0i22i30.p3mIwGRJ1eg&ved=0ahUKEwj89dvJ2OLkAhUCAGMBHdQ_BnEQ4dUDCAs&uact=5


This problem i know as "apache2 trailing slash"... add "qsnap" and ask
to your guard angel to help to find the solution.

ciao
MaX

**Comment by izumihiro** [comment]
"qnap", not "qsnap".
Is this a problem with "apache2 trailing slash"?
Can you tell me why you think so?

**Comment by maxlinux2000** [comment]
you're right. It is not a problem of trailing shash.
I have looked at the chrome console and it show me that you have a lot of 404 errors.

For example this file is not found:

http://yuming.fan/share/CACHEDEV1_DATA/Web/test/view/js/video.js/video-js.min.css

If I were you, I would do these checks:

Does the file exist? 
/share/CACHEDEV1_DATA/Web/test/view/js/video.js/video-js.min.css 
in the server filesystem starting from root /? It may be on another route.

If there is, who is the owner? (it has to be www-data.www-data) then
chown -R www-data.www-data /share/CACHEDEV1_DATA/Web/  
(or something similar)

 
If all fails, look the apache log when you connect with the prowser, from console with:

tail -f /var/log/apache2/errors.log 
(or something similar)

**Comment by izumihiro** [comment]
As DanielnetoDotCom said, it was displayed properly after replacing the code in configuration.php.
What should be rewritten was video / configuration.php, not objects / configuration.php.
Thank you very much.
