### ISSUE TITLE
Problem does not include videos

### ISSUE THREAD

**Issue by Michoss** [WWBN/AVideo#2053]
Hello, how about everything was fine until no video I want to load I do not know how to fix it I wrote with the server provider wrote that the disks are ok I tried to change the permissions files to 777 but it did nothing
![problem 2](https://user-images.githubusercontent.com/7188417/65367253-cc8e6080-dc2e-11e9-8e41-709a5b27792e.png)

**Comment by XemTube-TV** [comment]
Please disable the Chromecast Plugin and try again

![image](https://user-images.githubusercontent.com/50126312/65370387-5ae00200-dc82-11e9-8105-82de870ab802.png)

**Comment by Michoss** [comment]
Thank you it works
