### ISSUE TITLE
Encoder enhancement: reverse order and refresh

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo#2054]
In the queue list, it would be better if the order was reversed by default (the video being processed at the top).
In addition, an automatic refresh every 10 seconds would be good ... or with a javascript to refresh only in the contents of the box that contains the video in the processing phase (tr data-row-id="0").

**Comment by DanielnetoDotCom** [comment]
sorry, you are talking about what queue?

**Comment by maxlinux2000** [comment]
This: Encoder -> Queue Log

![Captura de pantalla de 2019-09-23 21-38-07](https://user-images.githubusercontent.com/5683921/65456819-7c8be580-de4a-11e9-9809-51d03717dae4.png)

**Comment by DanielnetoDotCom** [comment]
I understand, agree and appreciate your ideas, it is noted and may be implemented in the future.
