### ISSUE TITLE
Is there an 'how to go live stream' tutorial for members to read please ? 

### ISSUE THREAD

**Issue by joey2354** [WWBN/AVideo#2056]
Hi

I want to add a page with help on how to go live stream for members to make it easier for people to understand.

how do i do that please, and what is the full tutorial ?

thank you
mat

**Comment by akhilleusuggo** [comment]
You can use the plugin to create the page . TopMenu (TopMenu)

**Comment by joey2354** [comment]
@akhilleusuggo thank you
