### ISSUE TITLE
VideoThumbnails (VideoThumbnails)

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2057]
Only generate Thumbnails when you play the video . If I upload 100 videos , I need to click all of them to generate the thumbnail ...
Anyway to fix this ?

**Comment by DanielnetoDotCom** [comment]
Hi, we do not have another option now, it will always create the video at the first access.

we may improve it in the future. I agree with you it must be improved

**Comment by akhilleusuggo** [comment]
:(
