### ISSUE TITLE
FTP plugin

### ISSUE THREAD

**Issue by chinobaingo** [WWBN/AVideo#2061]
How Do I move all of my videos to another server so that I can use the FTP plugin?

I want to take my 350gb of current videos from my current installation and move them to my storage server and then FTP them to my website.

**Comment by DanielnetoDotCom** [comment]
Hi, 

If you enable the FTP plugin now, only the new videos will go to the FTP.

for now, we do not have an option to move between your local videos and FTP videos.

**Comment by chinobaingo** [comment]
That should be in the description of the plugin. Very misleading.

You need ACTUAL DESCRIPTIONS on Your plugins. Very deceptive to make people pay hard earned money but no actual description of how it works.

**Comment by DanielnetoDotCom** [comment]
Sorry if I was not clear, but all plugins are in the demo site. You can check all options there before a purchase

**Comment by chinobaingo** [comment]
Didn’t know this.

You should put descriptions anyway. Sorry thanks for all your work. 

Just glad I didn’t buy it yet. 

Which plugin should I buy to do what a I need?

**Comment by DanielnetoDotCom** [comment]
The YPTStorage plugin allows you to transfer videos between storages 
https://github.com/YouPHPTube/YouPHPTube-Storage

**Comment by chinobaingo** [comment]
But does this work for off site storage? 

My main server has 100gb limit

Need to host my current 100gb plus another 300gb and all new videos on a different server with high storage capacity.

Will this plugin do that?
