### ISSUE TITLE
My Video Section - No videos showing

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#2062]
List of video's not showing in the 'my video' section.  

The videos stopped showing when I added an encoded that shows EE:EE:EE for time.  I wanted to delete the video to see if that fixed the issue but I can't because videos don't show up in my video section.

I thought  EE:EE:EE were showing because it was 1080.  So I  added same video as 720 but it has the exact same issue as the 1080 video. 

I hope someone can helpl

**Comment by DanielnetoDotCom** [comment]
check your log file, this may be some other problem
