### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by tiplovo** [WWBN/AVideo#2063]
After updating ,avatars and a background in a profile ceased to be loaded?What to do?

**Comment by DanielnetoDotCom** [comment]
I am not sure what happen, please check your log file

**Comment by akhilleusuggo** [comment]
@tiplovo I had the same problem , I re-uploaded them

**Comment by tiplovo** [comment]
> @tiplovo у меня была та же проблема, я повторно загрузил их

Повторно что загрузили,фото или обновления ?

**Comment by tiplovo** [comment]
В логах вообще нет ничего
