### ISSUE TITLE
Multiple ffmpeg encoding

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2065]
I'm having a dedicated server with 20 threads , and only using a 30% of the actual CPU for the encoding . I'm even using medium and slow presets to minimize the size and  maximize the quality . But still a bit wast of resources . Would be nice to tell me how can I make multiple encoding at the site time . We can add the `-threads 6` to adjust the number of threads we can't to be using . 

Having multiple streams been sent to encoder takes years to finish all the them . Is not a mater of specs of the server , even with 100 cores will still take for ever

**Comment by DanielnetoDotCom** [comment]
you can install multiple encoders in your server if you want to handle them limiting by -theads

please check this to connect them all

**Comment by akhilleusuggo** [comment]
Yes , I've seen that . The problem is that when the encoder send the file , the file will be encoded into 3 different resolutions . Even if I have 100 encoders , and the stream are 4h , it's going to take the encoder to encode 15h 1 video to 3 resolution . Multiple Encoders doesn't help to transcode 1 file in multiple resolutions , that can be done only by 1 encoder . And that's what I'm asking for .

To allow the HD , HD_DS and SD to encode at the same time
