### ISSUE TITLE
Unstable Software

### ISSUE THREAD

**Issue by rayk32** [WWBN/AVideo#2068]
Bad software. Installed as a VM on ESXi. Went through initial setup, installed purchased plug-ins, installed YPTStorage plug-in ... all plug-ins disappeared and are unrecoverable. This is a terrible waste of time.

I purchased the following plug-ins ... Customize, FTPStorage, MP4ThumbsAndGif, SecureVideosDirectory, VideoResolutionSwitcher and YPTStorage.

**Comment by DanielnetoDotCom** [comment]
Why are you saying your plugins are unrecoverable?

just login in your account again and you will be able to download them all

**Comment by rayk32** [comment]
I have the actual files that I've downloaded.  What I am saying is that all of the built-in plug-ins have disappeared in the interface as well as the ones that I've purchased.  I have restarted the server numerous times, logged out and in numerous times, created a new admin user and plug-in page remains empty.

**Comment by DanielnetoDotCom** [comment]
Hi, 

if you can not see the builtin plugins you may have a php fatal error. check your log file for some clue

**Comment by rayk32** [comment]
Thanks for the response, I have already deleted the VM.

**Comment by maxlinux2000** [comment]
When these things happen, you must immediately review the permissions and owner. 
It is very likely that you have unzipped the plugins as root and forgot to change the owner to www-data.
