### ISSUE TITLE
Video Not Playing

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#2074]
Uploaded a 1 video
Size: 242 MB
File: MP4
Video image, GIF and time appear in play but it will not play.

Up loaded 2nd smaller file but having the same issue.  It doesn't play.
Plugins Not Active:  Chromcast, AWS_S3, all AD plugins, Blackblase_B2, Payperview, paypalYPT

https://202dc.tv/video/202dctv-snarky-sister
https://202dc.tv/video/yvette-young-pmdawn

**Comment by DanielnetoDotCom** [comment]
Hi

Probably you are having problems with your AWS_S3 or B2

you can not have both enabled at the same time.

check your log file and make sure the credentials are OK

**Comment by willpower68** [comment]
Neither AWS_S3 or B2 are active as I stated above.  I will check logs
