### ISSUE TITLE
video is not playing

### ISSUE THREAD

**Issue by sai014014** [WWBN/AVideo#2078]
I have uploaded a 10sec video through both encoder and direct mp4 upload, the video is uploaded successfully and showing in home page also but the videos are not playing showing an error as: below    http://creativefreevideos.com/video/test2
![Screenshot_2019-09-26-09-06-39-951_com android chrome](https://user-images.githubusercontent.com/55822415/65656316-0b605400-e03d-11e9-976a-00154458f24c.png)

**Comment by DanielnetoDotCom** [comment]
please check your log file

**Comment by maxlinux2000** [comment]
enconder o upload corrupped. I have experiment some video like this. Delete it and re-upload

**Comment by sai014014** [comment]
yes! i did it but still can't play the videos, i have uploaded several mp4videos also but same problem

**Comment by maxlinux2000** [comment]
Please try to download the video with youtube-dl and try to play it in your computer...and yes... Youtube-dl can download the video from youphptube

**Comment by DanielnetoDotCom** [comment]
please check your log file, and also inspect the code and try to get the src value from the source of the video tags.

for example: 

![image](https://user-images.githubusercontent.com/18009293/69874756-8a227900-129a-11ea-8f93-dfe9a8a88474.png)
