### ISSUE TITLE
VIDEOJS: ERROR: SyntaxError: "JSON.parse: expected property name or '}' at line 1 column 3 of the JSON data"

### ISSUE THREAD

**Issue by hustler203** [WWBN/AVideo#2079]
VIDEOJS: ERROR: SyntaxError: "JSON.parse: expected property name or '}' at line 1 column 3 of the JSON data"

LINE 142 IN video.js         fn[Array.isArray(args) ? 'apply' : 'call'](window$1.console, args);

VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
{…}
​
code: 4
​
message: "The media could not be loaded, either because the server or network failed or because the format is not supported."
​
<prototype>: {…

[watchmylive.com-1569472835016.log](https://github.com/YouPHPTube/YouPHPTube/files/3655901/watchmylive.com-1569472835016.log)
[watchmylive.com-1569472865572.log](https://github.com/YouPHPTube/YouPHPTube/files/3655902/watchmylive.com-1569472865572.log)
[watchmylive.com-1569468489828.log](https://github.com/YouPHPTube/YouPHPTube/files/3655903/watchmylive.com-1569468489828.log)

**Comment by DanielnetoDotCom** [comment]
I am not sure where this error come from

what page?

you only send javascript error logs, we also need php logs

**Comment by hustler203** [comment]
it is the live plugin and embedded player does not work either

**Comment by hustler203** [comment]
![webpage error snip](https://user-images.githubusercontent.com/5101087/65712596-5e4e0180-e065-11e9-867d-8383557ac9f6.jpg)

**Comment by DanielnetoDotCom** [comment]
you shoud disable the webcam , it is an experimental feature

also looks like you are not streaming anything.

I am not sure what problem are you describing

**Comment by hustler203** [comment]
![webpage error snip2](https://user-images.githubusercontent.com/5101087/65718739-2dc09480-e072-11e9-9601-fdf2b8e4fe3a.jpg)
after disabling experimental webcam still the same error

**Comment by hustler203** [comment]
![webpage error snip3](https://user-images.githubusercontent.com/5101087/65719070-f56d8600-e072-11e9-8474-e51cc5c61615.jpg)
i get the same error in every browser here is snip in firefox seems to be an issue with  video.js

**Comment by DanielnetoDotCom** [comment]
this error looks for me is because you are not transmitting anything

**Comment by hustler203** [comment]
it is connected to OBS and writing too live folder
![writing t live folder](https://user-images.githubusercontent.com/5101087/65724272-096ab500-e07e-11e9-9b8a-7190a993bed5.jpg)

**Comment by DanielnetoDotCom** [comment]
make sure you checked the listed transmission

![image](https://user-images.githubusercontent.com/18009293/65724770-8189a880-e087-11e9-87b9-59b4cf0dceb4.png)

check your network tab, look for the m3u8 file and it's response

![image](https://user-images.githubusercontent.com/18009293/65725023-0eccfd00-e088-11e9-8edc-c37696756a72.png)

**Comment by hustler203** [comment]
![network get](https://user-images.githubusercontent.com/5101087/65729743-57d38000-e08d-11e9-9bcd-07f0994005fd.jpg)
i get 404 response

**Comment by hustler203** [comment]
await fetch("http://watchmylive.com:8080/live/5d8753f608382.m3u8", {
    "credentials": "omit",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0",
        "Accept": "*/*",
        "Accept-Language": "en-US,en;q=0.5",
        "Cache-Control": "max-age=0"
    },
    "referrer": "http://watchmylive.com/plugin/Live/",
    "method": "GET",
    "mode": "cors"
});

**Comment by hustler203** [comment]
everything seems to be working but it does the 5d8753f608382.m3u8 folder created could it be that it is missing CORS headers.

**Comment by DanielnetoDotCom** [comment]
Yes that IS the way to fix. You need to find if the file is created and why it is not found

**Comment by hustler203** [comment]
worker_processes  1;
error_log  logs/error.log debug;
events {
        worker_connections  1024;
}
rtmp {
        server {
                listen 1935;
                allow play all;
                #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                application live {
                    allow play all;
                    live on;
                    #record all;
                    #record_path /video_recordings;
                    #record_unique on;
                    hls on;
                    hls_nested on;
                    hls_path /HLS/live;
                    #hls_playlist_length 4s;
                    #hls_fragment 1s;
                    hls_fragment 10s;
                    on_publish http://watchmylive.com/plugin/Live/on_publish.php;
                    on_play http://watchmylive.com/plugin/Live/on_play.php;
                    on_record_done http://watchmylive.com/plugin/Live/on_record_done.php;

                    #creates the downsampled or "trans-rated" mobile video stream as a 400kbps, 480x360 sized video
                    exec ffmpeg -i rtmp://localhost:1935/$app/$name -acodec copy -c:v libx264 -preset veryfast -profile:v baseline -vsync cfr -vf scale=-2:360,setdar=16:9 -b:v 400k -bufsize 400k -threads 0 -r 30 -f flv rtmp://localhost:1935/low/${name};

                    #recorder video{
                    #    record all;
                    #    record_path /tmp;
                    #    record_notify on;
                    #    record_suffix -%d-%b-%y-%T.flv;
                    #}
                }

                #creates our "mobile" lower-resolution HLS videostream from the ffmpeg-created stream and tells where to put the HLS video manifest and video fragments
                application low {
                    allow play all;
                    live on;
                    hls on;
                    hls_nested on;
                    hls_path /HLS/low;
                    hls_fragment 10s;
                }

        }
}
http {
        include       mime.types;
        default_type  application/octet-stream;
        server {
                listen 8080;
                server_name localhost;
                #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                location /live {
                        # Disable cache
                        add_header 'Cache-Control' 'no-cache';

                        # CORS setup
                        add_header 'Access-Control-Allow-Origin' '*' always;
                        add_header 'Access-Control-Expose-Headers' 'Content-Length';

                        # allow CORS preflight requests
                        if ($request_method = 'OPTIONS') {
                                add_header 'Access-Control-Allow-Origin' '*';
                                add_header 'Access-Control-Max-Age' 1728000;
                                add_header 'Content-Type' 'text/plain charset=UTF-8';
                                add_header 'Content-Length' 0;
                                return 204;
                        }
                        types {
                                application/vnd.apple.mpegurl m3u8;
                        }
                        alias /HLS/live;
                }

                #creates the http-location for our mobile-device HLS stream - "http://my-ip/low/my-stream-key/index.m3u8"        
                location /low {

                    # Disable cache
                    add_header 'Cache-Control' 'no-cache';

                    # CORS setup
                    add_header 'Access-Control-Allow-Origin' '*' always;
                    add_header 'Access-Control-Expose-Headers' 'Content-Length';

                    # allow CORS preflight requests
                    if ($request_method = 'OPTIONS') {
                            add_header 'Access-Control-Allow-Origin' '*';
                            add_header 'Access-Control-Max-Age' 1728000;
                            add_header 'Content-Type' 'text/plain charset=UTF-8';
                            add_header 'Content-Length' 0;
                            return 204;
                    }
                    types {
                            application/vnd.apple.mpegurl m3u8;
                    }
                    alias /HLS/low;
                }  

                #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                #location /stats {
                #        stub_status;
                #}
                location /stat {
                        rtmp_stat all;
                        rtmp_stat_stylesheet stat.xsl;
                }
                location /stat.xsl {
                        root html;
                }
                location /control {
                        rtmp_control all;
                }
                #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                location / {
                        root   html;
                        index  index.html index.htm;
                }   
        }
}

**Comment by DanielnetoDotCom** [comment]
FYI in your case it should not be a folder, but should be a file .

Post here your NGINX.conf and your live plugin parameters screenshot

**Comment by DanielnetoDotCom** [comment]
I can see you have some custom configurations (low)

You should first keep yourself in the default configuration

**Comment by hustler203** [comment]
[nginx.txt](https://github.com/YouPHPTube/YouPHPTube/files/3660373/nginx.txt)

**Comment by hustler203** [comment]
https://github.com/YouPHPTube/YouPHPTube/wiki/Configure-NGINX-Stream-Resolutions

**Comment by hustler203** [comment]
switch back to default config restarted nginx and apache still same error and tested in firefox chrome and Opera

**Comment by hustler203** [comment]
they all give me same error

**Comment by hustler203** [comment]
nginx error log
2019/09/22 11:24:43 [info] 46713#0: *25 client connected '127.0.0.1'
2019/09/22 11:24:43 [info] 46713#0: *25 connect: app='low' args='' flashver='' swf_url='' tc_url='rtmp://localhost:1935/low' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 11:24:43 [info] 46713#0: *25 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 11:24:43 [info] 46713#0: *25 publish: name='5d8753f608382' args='' type=live silent=0, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 11:24:54 [info] 46713#0: *20 deleteStream, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 11:24:54 [info] 46713#0: *20 exec: terminating child 46821, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 11:24:54 [info] 46713#0: *20 disconnect, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 11:24:54 [info] 46713#0: *20 deleteStream, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 11:24:54 [notice] 46713#0: signal 17 (SIGCHLD) received
2019/09/22 11:24:54 [alert] 46713#0: unknown process 46821 exited on signal 9
2019/09/22 11:24:54 [info] 46713#0: *25 disconnect, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 11:24:54 [info] 46713#0: *25 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 11:24:54 [info] 46713#0: *23 disconnect, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 11:24:54 [info] 46713#0: *23 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 11:25:04 [info] 46713#0: *29 client closed connection while waiting for request, client: 184.90.112.44, server: 0.0.0.0:8080
2019/09/22 11:25:24 [info] 46713#0: *38 client connected '184.90.112.44'
2019/09/22 11:25:24 [info] 46713#0: *38 connect: app='live' args='p=59fe87c75dc3f9f5057a24b0de356bdf' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://watchmylive.com/live?p=59fe87c75dc3f9f5057a24b0de356bdf' tc_url='rtmp://watchmylive.com/live?p=59fe87c75dc3f9f5057a24b0de356bdf' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 11:25:25 [info] 46713#0: *38 createStream, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 11:25:25 [info] 46713#0: *38 publish: name='5d8753f608382' args='' type=live silent=0, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 11:25:25 [info] 46713#0: *38 notify: publish 'watchmylive.com/plugin/Live/on_publish.php', client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 11:25:25 [info] 46713#0: *38 exec: starting managed child 'ffmpeg', client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 11:25:25 [info] 46713#0: *40 client connected '127.0.0.1'
2019/09/22 11:25:25 [info] 46713#0: *40 connect: app='live' args='' flashver='' swf_url='' tc_url='rtmp://localhost:1935/live' page_url='' acodecs=3191 vcodecs=252 object_encoding=0, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 11:25:25 [info] 46713#0: *40 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 11:25:25 [info] 46713#0: *40 play: name='5d8753f608382' args='' start=0 duration=0 reset=0 silent=0, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 11:25:25 [info] 46713#0: *40 notify: play 'watchmylive.com/plugin/Live/on_play.php', client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 11:25:26 [info] 46713#0: *44 client connected '127.0.0.1'
2019/09/22 11:25:26 [info] 46713#0: *44 connect: app='low' args='' flashver='' swf_url='' tc_url='rtmp://localhost:1935/low' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 11:25:26 [info] 46713#0: *44 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 11:25:26 [info] 46713#0: *44 publish: name='5d8753f608382' args='' type=live silent=0, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 12:59:03 [info] 46713#0: *1579 client sent invalid method while reading client request line, client: 159.203.201.255, server: localhost, request: " Œ  ˆFZs£}è5”ÈÄ“º4‡Ò¼"ÛeJO¯÷dñOøÍ  À/À+ÀÀÀÀ	ÀÀ"
2019/09/22 13:30:21 [info] 46713#0: *2140 client 178.93.22.241 closed keepalive connection
2019/09/22 13:40:55 [error] 46713#0: *2326 open() "/HLS/live/5d8753f608382.m3u8" failed (2: No such file or directory), client: 166.172.190.68, server: localhost, request: "GET /live/5d8753f608382.m3u8 HTTP/1.1", host: "watchmylive.com:8080", referrer: "http://watchmylive.com/plugin/Live/"
2019/09/22 13:41:37 [error] 46713#0: *2326 open() "/HLS/live/5d8753f608382.m3u8" failed (2: No such file or directory), client: 166.172.190.68, server: localhost, request: "GET /live/5d8753f608382.m3u8 HTTP/1.1", host: "watchmylive.com:8080", referrer: "http://watchmylive.com/plugin/Live/"
2019/09/22 13:41:37 [error] 46713#0: *2326 open() "/HLS/live/5d8753f608382.m3u8" failed (2: No such file or directory), client: 166.172.190.68, server: localhost, request: "GET /live/5d8753f608382.m3u8 HTTP/1.1", host: "watchmylive.com:8080", referrer: "http://watchmylive.com/plugin/Live/"
2019/09/22 13:41:43 [error] 46713#0: *2326 open() "/HLS/live/5d8753f608382.m3u8" failed (2: No such file or directory), client: 166.172.190.68, server: localhost, request: "GET /live/5d8753f608382.m3u8 HTTP/1.1", host: "watchmylive.com:8080", referrer: "http://watchmylive.com/plugin/Live/"
2019/09/22 13:41:43 [info] 46713#0: *2326 client 166.172.190.68 closed keepalive connection
2019/09/22 13:41:44 [error] 46713#0: *2353 open() "/HLS/live/5d8753f608382.m3u8" failed (2: No such file or directory), client: 166.172.190.68, server: localhost, request: "GET /live/5d8753f608382.m3u8 HTTP/1.1", host: "watchmylive.com:8080", referrer: "http://watchmylive.com/plugin/Live/"
2019/09/22 13:41:46 [error] 46713#0: *2353 open() "/HLS/live/5d8753f608382.m3u8" failed (2: No such file or directory), client: 166.172.190.68, server: localhost, request: "GET /live/5d8753f608382.m3u8 HTTP/1.1", host: "watchmylive.com:8080", referrer: "http://watchmylive.com/plugin/Live/"
2019/09/22 13:41:46 [info] 46713#0: *2353 client 166.172.190.68 closed keepalive connection
2019/09/22 13:41:46 [error] 46713#0: *2356 open() "/HLS/live/5d8753f608382.m3u8" failed (2: No such file or directory), client: 166.172.190.68, server: localhost, request: "GET /live/5d8753f608382.m3u8 HTTP/1.1", host: "watchmylive.com:8080", referrer: "http://watchmylive.com/plugin/Live/"
2019/09/22 13:41:57 [error] 46713#0: *2356 open() "/HLS/live/5d8753f608382.m3u8" failed (2: No such file or directory), client: 166.172.190.68, server: localhost, request: "GET /live/5d8753f608382.m3u8 HTTP/1.1", host: "watchmylive.com:8080", referrer: "http://watchmylive.com/plugin/Live/"
2019/09/22 13:41:57 [info] 46713#0: *2356 client 166.172.190.68 closed keepalive connection
2019/09/22 13:41:57 [error] 46713#0: *2364 open() "/HLS/live/5d8753f608382.m3u8" failed (2: No such file or directory), client: 166.172.190.68, server: localhost, request: "GET /live/5d8753f608382.m3u8 HTTP/1.1", host: "watchmylive.com:8080", referrer: "http://watchmylive.com/plugin/Live/"
2019/09/22 14:24:31 [info] 46713#0: *38 deleteStream, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:24:31 [info] 46713#0: *38 exec: terminating child 46882, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:24:31 [info] 46713#0: *38 disconnect, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:24:31 [info] 46713#0: *38 deleteStream, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:24:31 [info] 46713#0: *44 disconnect, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:24:31 [info] 46713#0: *44 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:24:31 [notice] 46713#0: signal 17 (SIGCHLD) received
2019/09/22 14:24:31 [alert] 46713#0: unknown process 46882 exited on signal 9
2019/09/22 14:24:31 [info] 46713#0: *40 recv() failed (104: Connection reset by peer), client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:24:31 [info] 46713#0: *40 disconnect, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:24:31 [info] 46713#0: *40 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:25:39 [info] 46713#0: *3140 client sent invalid request while reading client request line, client: 14.187.59.1, server: localhost, request: "GET ../../mnt/custom/ProductDefinition HTTP"
2019/09/22 14:54:44 [error] 46713#0: *3338 open() "/HLS/live/5d878b343e3f2.m3u8" failed (2: No such file or directory), client: 184.90.112.44, server: localhost, request: "GET /live/5d878b343e3f2.m3u8 HTTP/1.1", host: "watchmylive.com:8080", referrer: "http://watchmylive.com/plugin/Live/"
2019/09/22 14:56:05 [info] 46713#0: *3360 client connected '184.90.112.44'
2019/09/22 14:56:05 [info] 46713#0: *3360 connect: app='live' args='p=f37fd9b461edd03d311bbbb9f1f0c696' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://watchmylive.com/live?p=f37fd9b461edd03d311bbbb9f1f0c696' tc_url='rtmp://watchmylive.com/live?p=f37fd9b461edd03d311bbbb9f1f0c696' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:56:05 [info] 46713#0: *3360 createStream, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:56:05 [info] 46713#0: *3360 publish: name='5d878b343e3f2' args='' type=live silent=0, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:56:05 [info] 46713#0: *3360 notify: publish 'watchmylive.com/plugin/Live/on_publish.php', client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:56:05 [info] 46713#0: *3360 exec: starting managed child 'ffmpeg', client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:56:05 [info] 46713#0: *3362 client connected '127.0.0.1'
2019/09/22 14:56:05 [info] 46713#0: *3362 connect: app='live' args='' flashver='' swf_url='' tc_url='rtmp://localhost:1935/live' page_url='' acodecs=3191 vcodecs=252 object_encoding=0, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:56:05 [info] 46713#0: *3362 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:56:05 [info] 46713#0: *3362 play: name='5d878b343e3f2' args='' start=0 duration=0 reset=0 silent=0, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:56:05 [info] 46713#0: *3362 notify: play 'watchmylive.com/plugin/Live/on_play.php', client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:56:06 [info] 46713#0: *3365 client connected '127.0.0.1'
2019/09/22 14:56:06 [info] 46713#0: *3365 connect: app='low' args='' flashver='' swf_url='' tc_url='rtmp://localhost:1935/low' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:56:06 [info] 46713#0: *3365 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:56:06 [info] 46713#0: *3365 publish: name='5d878b343e3f2' args='' type=live silent=0, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:56:18 [info] 46713#0: *3360 deleteStream, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:56:18 [info] 46713#0: *3360 exec: terminating child 61351, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:56:18 [info] 46713#0: *3360 disconnect, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:56:18 [info] 46713#0: *3360 deleteStream, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:56:18 [info] 46713#0: *3365 disconnect, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:56:18 [info] 46713#0: *3365 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:56:18 [notice] 46713#0: signal 17 (SIGCHLD) received
2019/09/22 14:56:18 [alert] 46713#0: unknown process 61351 exited on signal 9
2019/09/22 14:56:18 [info] 46713#0: *3362 recv() failed (104: Connection reset by peer), client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:56:18 [info] 46713#0: *3362 disconnect, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:56:18 [info] 46713#0: *3362 deleteStream, client: 127.0.0.1, server: 0.0.0.0:1935
2019/09/22 14:56:35 [info] 46713#0: *3373 client connected '184.90.112.44'
2019/09/22 14:56:35 [info] 46713#0: *3373 connect: app='live' args='p=f37fd9b461edd03d311bbbb9f1f0c696' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://watchmylive.com/live?p=f37fd9b461edd03d311bbbb9f1f0c696' tc_url='rtmp://watchmylive.com/live?p=f37fd9b461edd03d311bbbb9f1f0c696' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:56:35 [info] 46713#0: *3373 createStream, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:56:35 [info] 46713#0: *3373 publish: name='5d878b343e3f2' args='' type=live silent=0, client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:56:35 [info] 46713#0: *3373 notify: publish 'watchmylive.com/plugin/Live/on_publish.php', client: 184.90.112.44, server: 0.0.0.0:1935
2019/09/22 14:56:35 [info] 46713#0: *3373 exec: starting managed child 'ffmpeg', client: 184.90.112.44, server: 0.0.0.0:1935

**Comment by DanielnetoDotCom** [comment]
Do **NOT** follow this tutorial until you get your nginx properly working

https://github.com/YouPHPTube/YouPHPTube/wiki/Configure-NGINX-Stream-Resolutions

you must find out why is your file not found

**Comment by hustler203** [comment]
![Nginx stats](https://user-images.githubusercontent.com/5101087/65802381-84e56880-e149-11e9-877a-afdbac317da8.jpg)

**Comment by hustler203** [comment]
instead of it creating a file "5d8753f608382.m3u8"  it is creating a folder called 5d8753f608382

**Comment by hustler203** [comment]
![Nginx partially working](https://user-images.githubusercontent.com/5101087/65823233-8170e080-e220-11e9-97b6-784c893e7b01.jpg)
got it to partially work by adding "hls_cleanup off; " (without Quotes) now it is partially working

**Comment by DanielnetoDotCom** [comment]
I already asked you this, " live plugin parameters screenshot"

I am pretty sure you are using the adaptive mode without the proper configuration

![image](https://user-images.githubusercontent.com/18009293/65874389-0ca2c100-e35c-11e9-83ec-d254d503c680.png)

**Comment by khadishi** [comment]
data-setup='{"fill": true}'
