### ISSUE TITLE
Storage plugin

### ISSUE THREAD

**Issue by fst24sx** [WWBN/AVideo#2080]
I need to move my site to a new server.
When using the storage plugin will this scenario work?

1. install storage server script on same server as current youphptube install
2. use plugin to transfer all videos from current install directory to the new directory of the storage server script. (same server different directory)
3. create new install of youphptube on new seperate server & install storage plugin
4. sync storage plugin from new site install with storage server that old site used to be on.

*i have a very large site and am moving it to a server with smaller SSD and using storage plugin to keep all my videos on other servers for load balancing. so the traditional clone function will not work because my new server has less local storage than my old server.

Thanks!

**Comment by DanielnetoDotCom** [comment]
Hi, I guess it will work

**Comment by fst24sx** [comment]
awesome ill try it. is there a way to add "storage type" to the sort options in my videos page?

i have thousands of videos, need to be able to sort which ones are local vs my storage sites.

**Comment by fst24sx** [comment]
or maybe just any way to be able to move multiple videos to another storage at once. moving like 2,000 videos one by one just isnt really practical...

**Comment by DanielnetoDotCom** [comment]
Yes, you are right, but for now, the only way is coding something.

In the future, I will think about in something like this for YPTStorage add an option for bulk move.

**Comment by fst24sx** [comment]
or maybe when selecting default storage for each user, allow files to move retroactively...just a thought

i will have the transfer them all by hand fo rnow.
