### ISSUE TITLE
How to limit the ffmpeg priority and add cpulimit to youphptube

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo#2082]
There has been much talk about how to limit the use of ffmpeg CPU resources. I have come to see that several proposals have been made such as putting ffmpeg inside a docker.

But it turns out that we have several options in Linux ... the first one is "nice" that regulates the priority of a process

With nice we will put a low priority to ffmpeg, because that way the server does not crash, and if it has no other tasks to do, then it will use all the power of the cpu to ffmpeg.

Here is an example:

**nice -19** ffmpeg -i {$pathFileName} -vf scale=-2:720 -movflags +faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -max_muxing_queue_size 1024 -y {$destinationFile}

I am already using the "nice" option with the encoder and it works perfectly. The server is much more responsive with the other tasks.

Another very very good possibility is the **cpulimit** command

`apt install cpulimit`

With this we can limit how many cpu and in what percent will a process use.

If we put -l 100 and we have 4 cores, he will use 25% of each core.
If we pome -l 400 we will use the 4 cores.

Another option is to limit the number of cpu with the -c 2 option. With 2 we will use 2 cpu, with 3 we will use 3.

Everything would be great, if it weren't for a particular.

It does not work with the encoder!
I think the problem is how the encoder monitors ffmpeg. As it is cpulimit to launch ffmpeg into a kind of cage, the encoder believes that the process is over and uploads partially encoded videos to the streamer.

I hope that one day the cpulimit can be added in the youphptube project.

Here you have an example command so you can check how cpulimit works

NOTE: Remember to install cpulimit

**apt install cpulimit**

nice -19 cpulimit -l 50 -- ffmpeg -i {$pathFileName} -vf scale=-2:720 -movflags +faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -max_muxing_queue_size 1024 -y {$destinationFile}

(with -l 50 ffmpeg will use the 50% of one cpu, but if you have 8 cpu you can put -l 700 or 750)

regards
MaX

**Comment by akhilleusuggo** [comment]
-threads $value works better 
`-threads 1 ` works fine . But if you're having a dedicated server , you wont be worried about this , since ffmpeg doesn't use the full cores

**Comment by maxlinux2000** [comment]
I don't note difference using  -threads 0-9.
I think thar on arm64 ffmpeg work different that amd64

About a dedicated server for the encoder...Yes! i'm working on it.

Actually I have only a problem to solve. I have only one IP public and
the Streamer and encoder need to works in different machine, so I need
to use the reverse proxy of apache, but It resist me.
This is anochter tutorial that we need in Documentation :)

My Scenario:

Fast home connection (Optical fiber) with Public IP. The DSL modem use
the DMZ method to expose the youphptube to internet.
So the modem has a public IP, but the server has a private IP
192.168.0.10. Ant this system work perfectly.

The server has a second ethernet interface (192.168.1.1), connected to
another board where I want put the encoder with IP 192.168.1.10.

I use a simple rule of iptable (NAT) in order to permit to the second
server communicato with internet.... and this is working too.

But now the apache reverse proxy, won't work. GRRR!!! >:-[

**Comment by akhilleusuggo** [comment]
I don't know what you're talking about , but documentation for Vhost ? xD
This has nothing to do with this open-source . Just google Virtual Host Apache2 and you can host as many site as you want on a single IP

**Comment by maxlinux2000** [comment]
If I count Apache Vhost, and in fact I have several web services on several servers.
What I fart is different:

I have an IP and two servers (2 different computers)
computer 1 is connected to internte by eth0 and connected to computer 2, by eth1.

Both have web services, but only computer 1 is visible from the internet, while computer 2 is not.

How do I also make computer 2 visible from the internet?

There is talk that you have to use the reverse proxy, but I have not managed to operate the system and the documentation is very old. But surely Apache can do it.
It was done in the '90s before he invented NAT ...
