### ISSUE TITLE
Plugin for Live Stream Notification ( when you're not on the site )

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2086]
Does the Notifications plugin work for the live streams ?
How did you added the  push notification on the https://tutorials.youphptube.com/ ?

**Comment by DanielnetoDotCom** [comment]
Hi

It notifies the subscribers each time you goes live

we use onesignal for push notifications

https://github.com/YouPHPTube/YouPHPTube/wiki/Notifications-Plugin#onesignal
