### ISSUE TITLE
Error after embed video Serializer not writable, please chmod to 777 V7.6

### ISSUE THREAD

**Issue by subas123** [WWBN/AVideo#2090]
/var/www/html/YouPHPTube/objects/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777

**Comment by DanielnetoDotCom** [comment]
change the directory permission with this command

`sudo chmod 777 /var/www/html/YouPHPTube/objects/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer`
