### ISSUE TITLE
Live

### ISSUE THREAD

**Issue by tiplovo** [WWBN/AVideo#2091]
Hello dears!I configured the flash player for the webcam, everything works, the video shows the screenshots attached....But the sound does not work on the video .Video works and there is no sound where to dig, I think that in codecs a problem
![image](https://user-images.githubusercontent.com/53423163/65903657-3a2c5080-e3d6-11e9-82bc-6c3a34863d74.png)
![image](https://user-images.githubusercontent.com/53423163/65903692-4ca68a00-e3d6-11e9-89e4-2263479380dd.png)
![image](https://user-images.githubusercontent.com/53423163/65903705-55975b80-e3d6-11e9-967c-fb65ca7077ff.png)

**Comment by DanielnetoDotCom** [comment]
can you please give more details about what did you do to configure the webcam?

**Comment by tiplovo** [comment]
Hi Daniel!Yes I can you straight for the code, and publisher player, write far and I you'll text archive

**Comment by DanielnetoDotCom** [comment]
Sorry I do not understand what do you mean.

**Comment by tiplovo** [comment]
I e-mailed you an archive.

**Comment by DanielnetoDotCom** [comment]
I guess I did not receive it.

is it possible to post here?

**Comment by tiplovo** [comment]
<!DOCTYPE html>
<html lang="<?php echo $_SESSION['language']; ?>">
    <head>
        <script type="text/javascript" src="<?php echo $global['webSiteRootURL']; ?>plugin/Live/view/SwfObj.js"></script>
    </head>

<div class="container">
            <div class="col-md-6">
                <?php
                if (!empty($obj->experimentalWebcam)) {
                    ?>
                    <div class="panel panel-default">
                        <div class="panel-heading">Вебкамера</div>
                        <div class="panel-body">
                            <div class="embed-responsive embed-responsive-16by9">
                                <script type="text/javascript">
             var swf = new swfObj("<?php echo $global['webSiteRootURL']; ?>plugin/Live/view/WebCam2.swf",320,240,"cam");
             swf.param("quality", "high");
             swf.param("wmode","Window"); 
             swf.flashVar("Server","<?php echo $p->getServer(); ?>?p=<?php echo User::getUserPass(); ?>");
             swf.flashVar("Public","<?php echo $trasnmition['key']; ?>");
             swf.flashVar("H264","Y"); //H.264
             swf.flashVar("Quality","80");
             swf.flashVar("MicRate","50");
             swf.add();
                         </script>
                            </div>
                        </div>
                    </div>

**Comment by tiplovo** [comment]
`<!DOCTYPE html>
<html lang="<?php echo $_SESSION['language']; ?>">
    <head>
        <script type="text/javascript" src="<?php echo $global['webSiteRootURL']; ?>plugin/Live/view/SwfObj.js"></script>
    </head>

<div class="container">
            <div class="col-md-6">
                <?php
                if (!empty($obj->experimentalWebcam)) {
                    ?>
                    <div class="panel panel-default">
                        <div class="panel-heading">Вебкамера</div>
                        <div class="panel-body">
                            <div class="embed-responsive embed-responsive-16by9">
                                <script type="text/javascript">
             var swf = new swfObj("<?php echo $global['webSiteRootURL']; ?>plugin/Live/view/WebCam2.swf",320,240,"cam");
             swf.param("quality", "high");
             swf.param("wmode","Window"); 
             swf.flashVar("Server","<?php echo $p->getServer(); ?>?p=<?php echo User::getUserPass(); ?>");
             swf.flashVar("Public","<?php echo $trasnmition['key']; ?>");
             swf.flashVar("H264","Y"); //H.264
             swf.flashVar("Quality","80");
             swf.flashVar("MicRate","50");
             swf.add();
                         </script>
                            </div>
                        </div>
                    </div>`

**Comment by tiplovo** [comment]
![image](https://user-images.githubusercontent.com/53423163/65982235-4d055a80-e494-11e9-8ec1-894e2f865478.png)

**Comment by DanielnetoDotCom** [comment]
Sorry but I am not sure what you want

**Comment by tiplovo** [comment]
Ah I here is so made, video I have works with cameras, and understanding sound there is no

**Comment by tiplovo** [comment]
Okay, thanks for responding, I will understand myself, the video from the camera works for me, only the sound from the microphone is not, I think somewhere in the codecs error

**Comment by RisKatOr** [comment]
Я тоже пытался но не получилась, у вас вижу прогрес есть, дайте я тоже попробую может у меня заработает.

**Comment by tiplovo** [comment]
Я могу вам отправить архив с кодом и плеером ,напишите куда,и я отправлю

**Comment by RisKatOr** [comment]
riskator@gmail.com пожалуйста

**Comment by tiplovo** [comment]
Отправил вам на почту!Думаю вы разберетесь что и как сделать

**Comment by RisKatOr** [comment]
Пока не совсем разобрался, видимо знания не хватает :(
Все что вы отправили загрузил в папку plugin/Live/view
https://www.ahiska.tv/plugin/Live/view/webcam.html webcam.swf тут работает но на сайт ничего не передает.
затем попробовал в той же папке (plugin/Live/view) TarantinovWebCam2.swf переименовать на webcam.swf но не сработала.

**Comment by tiplovo** [comment]
в папку /plugin/Live/view/ поместить нужно только TarantinovWebCam2.swf, TrSwfObj.js а из webcam.html взять код и заменить в  plugin/Live/index.php

**Comment by tiplovo** [comment]
скину исходник чуть позже

**Comment by RisKatOr** [comment]
понял, очень жду исходник.

**Comment by tiplovo** [comment]
`<?php
require_once '../../videos/configuration.php';
require_once $global['systemRootPath'] . 'objects/user.php';

$p = YouPHPTubePlugin::loadPlugin("Live");

if (!empty($_GET['c'])) {
    $user = User::getChannelOwner($_GET['c']);
    if (!empty($user)) {
        $_GET['u'] = $user['user'];
    }
}
if(!empty($_GET['c'])){
    $user = User::getChannelOwner($_GET['c']);
    if($user['status']!=='a'){
        header("Location: {$global['webSiteRootURL']}");
    }
}
if (!empty($_GET['u']) && !empty($_GET['embedv2'])) {
    include $global['systemRootPath'] . 'plugin/Live/view/videoEmbededV2.php';
    exit;
} else if (!empty($_GET['u']) && !empty($_GET['embed'])) {
    include $global['systemRootPath'] . 'plugin/Live/view/videoEmbeded.php';
    exit;
} else if (!empty($_GET['u'])) {
    include $global['systemRootPath'].'plugin/Live/view/modeYoutubeLive.php';
    exit;
} else if (!User::canStream()) {
    header("Location: {$global['webSiteRootURL']}?error=" . __("You can not stream live videos"));
    exit;
}

require_once $global['systemRootPath'] . 'objects/userGroups.php';
require_once $global['systemRootPath'] . 'objects/functions.php';
require_once $global['systemRootPath'] . 'plugin/Live/Objects/LiveTransmition.php';

// if user already have a key
$trasnmition = LiveTransmition::createTransmitionIfNeed(User::getId());
if (!empty($_GET['resetKey'])) {
    LiveTransmition::resetTransmitionKey(User::getId());
    header("Location: {$global['webSiteRootURL']}plugin/Live/");
    exit;
}

$aspectRatio = "16:9";
$vjsClass = "vjs-16-9";

$trans = new LiveTransmition($trasnmition['id']);
$groups = $trans->getGroups();
$obj = $p->getDataObject();

//check if channel name exists
$channelName = User::getUserChannelName();
if (empty($channelName)) {
    $channelName = uniqid();
    $user = new User(User::getId());
    $user->setChannelName($channelName);
    $user->save();
}
?>
<!DOCTYPE html>
<html lang="<?php echo $_SESSION['language']; ?>">
    <head>
        <title><?php echo __("Live"); ?> - <?php echo $config->getWebSiteTitle(); ?></title>
        <link href="<?php echo $global['webSiteRootURL']; ?>js/video.js/video-js.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $global['webSiteRootURL']; ?>css/player.css" rel="stylesheet" type="text/css"/>
        <?php
        include $global['systemRootPath'] . 'view/include/head.php';
        ?>
        <script src="<?php echo $global['webSiteRootURL']; ?>plugin/Live/view/swfobject.js" type="text/javascript"></script>
        <script src="<?php echo $global['webSiteRootURL']; ?>js/video.js/video.js" type="text/javascript"></script>
        <script src="<?php echo $global['webSiteRootURL']; ?>plugin/Live/view/videojs-contrib-hls.min.js" type="text/javascript"></script>
		<script type="text/javascript" src="<?php echo $global['webSiteRootURL']; ?>plugin/Live/view/TrSwfObj.js"></script>
    </head>
    <body class="<?php echo $global['bodyClass']; ?>">
        <?php
        include $global['systemRootPath'] . 'view/include/navbar.php';
        ?>
        <div class="container">
            <div class="col-md-6">
                <?php
                if (!empty($obj->experimentalWebcam)) {
                    ?>
                    <div class="panel panel-default">
                        <div class="panel-heading"><?php echo __("WebCam Streaming"); ?></div>
                        <div class="panel-body">
                            <div class="embed-responsive embed-responsive-16by9">
                                <script type="text/javascript">
             var swf = new swfObj("<?php echo $global['webSiteRootURL']; ?>plugin/Live/view/TarantinovWebCam2.swf",320,240,"cam");
             swf.param("quality", "high");
             swf.param("wmode","Window"); //Для Opera10-11 обязательно Window (баг)
             swf.flashVar("Server","<?php echo $p->getServer(); ?>?p=<?php echo User::getUserPass(); ?>");
             swf.flashVar("Public","<?php echo $trasnmition['key']; ?>");
             swf.flashVar("H264","Y"); //H.264
             swf.flashVar("Quality","80");
             swf.flashVar("MicRate","50");
             swf.add();
                         </script>
                            </div>
                        </div>
                    </div>
                    <?php
                }
                ?>
                <div class="panel panel-default">
                    <div class="panel-heading"><i class="fa fa-share"></i> <?php echo __("Share Info"); ?></div>
                    <div class="panel-body">          
                        <div class="form-group">
                            <label for="playerURL"><i class="fa fa-play-circle"></i> <?php echo __("Player URL"); ?>:</label>
                            <input type="text" class="form-control" id="playerURL" value="<?php echo $p->getM3U8File($trasnmition['key']); ?>"  readonly="readonly">
                        </div>       
                        <div class="form-group">
                            <label for="youphptubeURL"><i class="fa fa-circle"></i> <?php echo __("Live URL"); ?>:</label>
                            <input type="text" class="form-control" id="youphptubeURL" value="<?php echo $global['webSiteRootURL']; ?>plugin/Live/?c=<?php echo urlencode($channelName); ?>"  readonly="readonly">
                        </div>   
                        <div class="form-group">
                            <label for="embedStream"><i class="fa fa-code"></i> <?php echo __("Embed Stream"); ?>:</label>
                            <input type="text" class="form-control" id="embedStream" value='<iframe width="640" height="480" style="max-width: 100%;max-height: 100%;" src="<?php echo $global['webSiteRootURL']; ?>plugin/Live/?c=<?php echo urlencode($channelName); ?>&embed=1" frameborder="0" allowfullscreen="allowfullscreen" ></iframe>'  readonly="readonly">
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading"><i class="fa fa-hdd-o"></i> <?php echo __("Devices Stream Info"); ?></div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label for="server"><i class="fa fa-server"></i> <?php echo __("Server URL"); ?>:</label>
                            <input type="text" class="form-control" id="server" value="<?php echo $p->getServer(); ?>?p=<?php echo User::getUserPass(); ?>" readonly="readonly">
                            <small class="label label-info"><i class="fa fa-warning"></i> <?php echo __("If you change your password the Server URL parameters will be changed too."); ?></small>
                        </div>
                        <div class="form-group">
                            <label for="streamkey"><i class="fa fa-key"></i> <?php echo __("Stream name/key"); ?>:</label>
                            <div class="input-group">
                                <input type="text" class="form-control" id="streamkey" value="<?php echo $trasnmition['key']; ?>" readonly="readonly">
                                <span class="input-group-btn">
                                    <a class="btn btn-default" href="<?php echo $global['webSiteRootURL']; ?>plugin/Live/?resetKey=1"><i class="fa fa-refresh"></i> <?php echo __("Reset Key"); ?></a>
                                </span>
                            </div>
                            <span class="label label-warning"><i class="fa fa-warning"></i> <?php echo __("Keep Key Private, Anyone with key can broadcast on your account"); ?></span>
                        </div>
                    </div>
                </div>
                <?php
                YouPHPTubePlugin::getLivePanel();
                ?>
            </div>
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <?php
                        $streamName = $trasnmition['key'];
                        include $global['systemRootPath'] . 'plugin/Live/view/onlineLabel.php';
                        ?>
                    </div>
                    <div class="panel-body">          
                        <div class="embed-responsive embed-responsive-16by9">
                            <video poster="<?php echo $global['webSiteRootURL']; ?>plugin/Live/view/OnAir.jpg" controls 
                                   class="embed-responsive-item video-js vjs-default-skin <?php echo $vjsClass; ?> vjs-big-play-centered" 
                                   id="mainVideo" data-setup='{ aspectRatio: "<?php echo $aspectRatio; ?>",  "techorder" : ["flash", "html5"] }'>
                                <source src="<?php echo $p->getM3U8File($trasnmition['key']); ?>" type='application/x-mpegURL'>
                            </video>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo __("Stream Settings"); ?></div>
                    <div class="panel-body"> 
                        <div class="form-group">
                            <label for="title"><?php echo __("Title"); ?>:</label>
                            <input type="text" class="form-control" id="title" value="<?php echo $trasnmition['title'] ?>">
                        </div>    
                        <div class="form-group">
                            <label for="description"><?php echo __("Description"); ?>:</label>
                            <textarea class="form-control" id="description"><?php echo $trasnmition['description'] ?></textarea>
                        </div>
                        
                        <hr>
                        <div class="form-group">
                            <span class="fa fa-globe"></span> <?php echo __("Listed Transmition"); ?> 
                            <div class="material-switch pull-right">
                                <input id="listed" type="checkbox" value="1" <?php echo!empty($trasnmition['public']) ? "checked" : ""; ?>/>
                                <label for="listed" class="label-success"></label> 
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo __("Groups That Can See This Stream"); ?><br><small><?php echo __("Uncheck all to make it public"); ?></small></div>
                    <div class="panel-body"> 
                        <?php
                        $ug = UserGroups::getAllUsersGroups();
                        foreach ($ug as $value) {
                            ?>
                            <div class="form-group">
                                <span class="fa fa-users"></span> <?php echo $value['group_name']; ?>
                                <div class="material-switch pull-right">
                                    <input id="group<?php echo $value['id']; ?>" type="checkbox" value="<?php echo $value['id']; ?>" class="userGroups" <?php echo (in_array($value['id'], $groups) ? "checked" : "") ?>/>
                                    <label for="group<?php echo $value['id']; ?>" class="label-success"></label>
                                </div>
                            </div>
                            <?php
                        }
                        ?>
                        <button type="button" class="btn btn-success" id="btnSaveStream"><?php echo __("Save Stream"); ?></button>
                        <a href="<?php echo $global['webSiteRootURL']; ?>usersGroups" class="btn btn-primary"><span class="fa fa-users"></span> <?php echo __("Add more user Groups"); ?></a>
                    </div>
                </div>

            </div>
        </div>
        <?php
        $p->getChat($trasnmition['key']);
        ?>
        <?php
        include $global['systemRootPath'] . 'view/include/footer.php';
        ?>
        <script>
            var flashvars = {server: "<?php echo $p->getServer(); ?>?p=<?php echo User::getUserPass(); ?>", stream: "<?php echo $trasnmition['key']; ?>"};
                var params = {};
                var attributes = {};
                function amIOnline() {
                    $.ajax({
                        url: '<?php echo $global['webSiteRootURL']; ?>plugin/Live/stats.json.php?checkIfYouOnline',
                        data: {"name": "<?php echo $streamName; ?>"},
                        type: 'post',
                        success: function (response) {
                            offLine = true;
                            for (i = 0; i < response.applications.length; i++) {
                                if (response.applications[i].key === "<?php echo $trasnmition['key']; ?>") {
                                    offLine = false;
                                    break;
                                }
                            }
                            // you online do not show webcam
                            if (!offLine) {
                                $('#webcam').find('.alert').text("<?php echo __("You are online now, web cam is disabled"); ?>");
                            } else {
                                $('#webcam').find('.alert').text("<?php echo __("You are not online, loading webcam..."); ?>");
                                swfobject.embedSWF("<?php echo $global['webSiteRootURL']; ?>plugin/Live/view/webcam.swf", "webcam", "100%", "100%", "9.0.0", "expressInstall.swf", flashvars, params, attributes);
                            }
                        }
                    });
                }

                function saveStream() {
                    modal.showPleaseWait();

                    var selectedUserGroups = [];
                    $('.userGroups:checked').each(function () {
                        selectedUserGroups.push($(this).val());
                    });

                    $.ajax({
                        url: 'saveLive.php',
                        data: {
                            "title": $('#title').val(),
                            "description": $('#description').val(),
                            "key": "<?php echo $trasnmition['key']; ?>",
                            "listed": $('#listed').is(":checked"),
                            "userGroups": selectedUserGroups
                        },
                        type: 'post',
                        success: function (response) {
                            modal.hidePleaseWait();
                        }
                    });
                }
                $(document).ready(function () {
                    $('#btnSaveStream').click(function () {
                        saveStream();
                    });
                    $('#enableWebCam').click(function () {
                        amIOnline();
                    });
                });
        </script>
    </body>
</html>
`

**Comment by tiplovo** [comment]
plugin/Live/index.php заменить на предоставленный код

**Comment by tiplovo** [comment]
> понял, очень жду исходник.
> 
> на самом деле то что сейчас в скрипте webcam.swf работает если смотреть через внешний плеер, может и на самом деле проблема не в webcam.swf а в m3u8 плеере скрипта ?
> [#601 (комментарий)](https://github.com/YouPHPTube/YouPHPTube/issues/601#issuecomment-382306494)

я вам на почту лучше фаил скину

**Comment by tiplovo** [comment]
Отправил на почту

**Comment by tiplovo** [comment]
![image](https://user-images.githubusercontent.com/53423163/66231091-08312c00-e6ff-11e9-8d5a-8dddb9996ef2.png)
вот так будет выглядеть страница стримера

**Comment by tiplovo** [comment]
Я еще планирую вывести флешь плеер для зрителя... в скором времени наверно сделаю

**Comment by RisKatOr** [comment]
> ![image](https://user-images.githubusercontent.com/53423163/66231091-08312c00-e6ff-11e9-8d5a-8dddb9996ef2.png)
> вот так будет выглядеть страница стримера

Уменя так не выглядит, выглядит так же как с встроенной, тоесть TarantinovWebCam2.swf сработал (как и свой webcam.swf) везде онлайн показывает но картинки и звука нигде нет.

но если посмотреть с https://www.hlsplayer.net/rtmp-player то все есть, картинка и звук есть, по этому думаю что нужне не webcam.swf менять а нужно менять плеер и поставить точно такой же плеер как на этом сайте  https://www.hlsplayer.net/rtmp-player но я так понимаю что разработчик не желает использовать флеш плеер.

**Comment by tiplovo** [comment]
Я вам де отправил отредактированный фаил,и написал что его нужно заменить,и тогда все будет работать

**Comment by tiplovo** [comment]
А звука нет,это нужно перекодировать аудио ,и все работает...но я теперь делаю дополнительный плеер,с выбором html5 и флеш

**Comment by RisKatOr** [comment]
Отлично, попробую, спасибо.
Кстати я не получил вашу де отправку, перешлите пожалуйста.

**Comment by RisKatOr** [comment]
> Я вам де отправил отредактированный фаил,и написал что его нужно заменить,и тогда все будет работать

Вы мне отправили тот же что раньше отправили, я сверил изменений нет с предедущим, вообщем ни картинки ни звука так и нет.

**Comment by RisKatOr** [comment]
После перезагрузки сервера камера заработала, но звука нет.

**Comment by tiplovo** [comment]
> После перезагрузки сервера камера заработала, но звука нет.

привет!нужно кодировать в nginx кодек звука под hls чтоб был звук
