### ISSUE TITLE
Left categories menu hard to scroll on iphone after upgrade to version 7.7

### ISSUE THREAD

**Issue by ykhuat** [WWBN/AVideo#2092]
Hi DanielnetoDotCom,
TQ for great software.

Today i upgrade Youphptube from version 6.2 to version 7.7 and find out some small bug.

After upgrade to version 7.7, every thing is working fine, but when try on handphone (Iphone X), i find out the Left categories menu hard to scroll.

If got time please have a look on it.

TQ very Much..

![Youphptube_Issue](https://user-images.githubusercontent.com/30988187/65913949-47abff80-e403-11e9-9b30-862983f3bef0.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, 

I sent an update to it.

update your files, and clear your server cache dir and your browser cache
