### ISSUE TITLE
Live Stream Description 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2096]
Could you please add an option for '' show more'' and show less , if the description is very long , it does show all the description ( also on the videos ) , witch makes the comment section look very far away

**Comment by DanielnetoDotCom** [comment]
can you please screenshot a sample for me?

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/65975837-e5d9ad00-e477-11e9-8b66-f773f6e775cb.png)

The description goes down so long , on youtube for example , there's one boutton that does this : 
![image](https://user-images.githubusercontent.com/52116577/65975983-246f6780-e478-11e9-9a4c-0453ce26879c.png)
 and show less :
![image](https://user-images.githubusercontent.com/52116577/65976039-394bfb00-e478-11e9-8bb4-f3246aca51b5.png)

**Comment by tiplovo** [comment]
описание можно заключить в отдельный блок,просто дописать стили,и будет выезжать по кнопке

**Comment by alexious** [comment]
Was this done?

**Comment by akhilleusuggo** [comment]
@alexious Not yet , I'm trying to find a way to do it .

**Comment by akhilleusuggo** [comment]
I just need to know where is the file with css that is responsible for the video's description

**Comment by akhilleusuggo** [comment]
Giving this example from this website , I was able to make it work on my blog , but I'm lost into multiple files of this script . 
https://www.w3schools.com/howto/howto_js_read_more.asp
