### ISSUE TITLE
ServerMonitor

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2097]
Hello Daniel , one of your projects are ''ServerMonitor'' witch you've said that ( is old and you'll remove it )

I wanted to add it manually to YouPHPTube ( for admins only ) , no luck ( i'm noob )
Wouldn't be a great idea to add it to the dashboard of the admin section ? This is really good idea to monitor the server resources and privately , and make use of one of your scripts ;)

Sad that there's no bandwidth monitoring , but still gonna help :)

**Comment by lunar54** [comment]
you could just run a vm in Proxmox or ESXi

**Comment by akhilleusuggo** [comment]
My server is not at home ! I'm hosting a website not for testing purposes

**Comment by lunar54** [comment]
I use Proxmox on servers in remote data centers all the time as long as they allow custom OS reloads and you have 1 or 2 ips. although it would be better to use data center that also offers private internal network. So you can install Proxmox or ESXi on private net co-location is another thing to look.

**Comment by akhilleusuggo** [comment]
but I don't wanna wast resources on Proxmox ( it does use it ) , I have it at home , on my homeserver it's ok , but for a dedicated server ... plus I need to reinstall everything and make a backup ... Deferentially not what want to do . 
I'm asking for something that Daniel it self made , and not using anymore for anything . Asking for an implementation , not a solution to see my server resources . I could just see them from terminal .

**Comment by lunar54** [comment]
ya htop etc is best its direct on server. for Proxmox you should leave a couple cores and some memory for it if your using zfs your mem will be used up but that is just how zfs works. I know its not integrated but have you tried Monitorix ? Again not integrated but there are tons of alternatives to nagios.

**Comment by akhilleusuggo** [comment]
@lunar54 Ok , I see you don't get my idea . I don't wanna get into my server in anyway . I want get into my website and see the monitoring resources . If you haven't tried out https://github.com/DanielnetoDotCom/ServerMonitor then you're not understanding what I'm talking about

**Comment by lunar54** [comment]
yes I do understand but if that is broken/ not working for you. there are other ways to get stats on server resources that is all I was saying.
