### ISSUE TITLE
Live Chat

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2102]
I'm using the normal Live Chat , but is there anyway to take the link of the livechat ? Like popup the chat , to add it to OBS for example ?

**Comment by DanielnetoDotCom** [comment]
No, there is not that option for livechat.

Only Chat2 has this feature like this https://demo.youphptube.com/plugin/Chat2/?room_users_id=1&iframe=1&noFade=1

**Comment by DanielnetoDotCom** [comment]
Hi, where did you see bugged?
The pages it will appear is set up on the plugin parameters.

for now we do not have a fixed place for it
