### ISSUE TITLE
Playback not working on Mobile App

### ISSUE THREAD

**Issue by elsenandy** [WWBN/AVideo#2104]
Hi,
Unfortunately my mobile app plays no video.
I tried with imported Youtube Videos, and self uploaded Videos.
I get a response error from the server.
All the other features are working. Also streaming and viewing the stream, but no Videos.
![Screenshot_20191002-221827_PHPTube](https://user-images.githubusercontent.com/56048211/66078770-f4e95980-e562-11e9-91c8-77bb9dbc3d64.jpg)

**Comment by DanielnetoDotCom** [comment]
I am pretty sure you have some security module in your server blocking it.

**Comment by elsenandy** [comment]
I am a bit confused. It wants to open a file in Webroot/videoEmbeded
But this folder doesn't exists on my install.. Also no trace on Git.

**Comment by DanielnetoDotCom** [comment]
For me looks like you are having problems in your installation.

are you sure you are using **Ubuntu without a control panel**?

**Comment by elsenandy** [comment]
I have done the Installation exactly like your how-to. Its an Ubuntu 16 Server Clean Installation without any GUI (If you meant that by ControlPanel).
When using my browser an my Smartphone everything is working, and i can play videos, when connecting via the app, it is not working anymore. But i can stream, this is working. For me, there is an issue in the config of your app.. I googled a lot about this error, seems to have something to do with X-Frames,... thats to high for me ;) You can connect to my site, i just enabled anonymous login. https://youphptube.hostzone.lu/YouPHPTube/ only have some test videos online.

**Comment by DanielnetoDotCom** [comment]
try to connect in the demo site, if works must be something in your site 

https://demo.youphptube.com/
