### ISSUE TITLE
Google Webmaster

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2105]
When I add the sitemap to google webmaster , for some reason it does block ( for example the livestreams and the channels )
Where to change this ?

I see them here : 
`Disallow: /plugin`
But I don't wanna dismissal all plugins , only the /plugin/Live
Any way to add an exception ? or I have to write 
```
Disallow :/plugin/NamePlugin1
Disallow :/plugin/NamePlugin3
Disallow :/plugin/NamePlugin3
```

and so on ... ?

**Comment by akhilleusuggo** [comment]
Fixed by adding :

`Allow: /plugin/Live`

**Comment by akhilleusuggo** [comment]
How to add this to the sitemap ?

**Comment by DanielnetoDotCom** [comment]
I guess it should go to robots.txt

https://github.com/YouPHPTube/YouPHPTube/blob/master/robots.txt
