### ISSUE TITLE
HLS Plugin

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2113]
Multiple troubles : 

1- So , when removing the FFmpeg ( it's supposed to automatically detect the source ) and encode it . When using send stream to encoder , actually it does always encode it to 240p.

2- I'm having some conflicts with the VideoResolutionSwitcher plugin . Older videos are using now the new HLS switch and not showing the original files ( only the lowest quality ) like if I haven't the plugin .

3- The FFmpeg code linked on the wiki for the HSL :
`ffmpeg -re -i {$pathFileName} -c:a aac -b:a 128k -c:v libx264 -vf scale=-2:360 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 800k -maxrate 856k -bufsize 1200k -b:a 96k -f hls -hls_time 15 -hls_list_size 0 -hls_key_info_file {$destinationFile}keyinfo {$destinationFile}low/index.m3u8 -c:a aac -b:a 128k -c:v libx264 -vf scale=-2:540 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1400k -maxrate 1498k -bufsize 2100k -b:a 128k -f hls -hls_time 15 -hls_list_size 0 -hls_key_info_file {$destinationFile}keyinfo {$destinationFile}sd/index.m3u8 -c:a aac -b:a 128k -c:v libx264 -vf scale=-2:720 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2800k -maxrate 2996k -bufsize 4200k -b:a 128k -f hls -hls_time 15 -hls_list_size 0 -hls_key_info_file {$destinationFile}keyinfo {$destinationFile}hd/index.m3u8`
It does have only 3 resolutions . Is there anyway to add more ? Since removing the code , can go up to 4K , resulting on 7 different resolution , the FFmpeg command line can go up to 7 as well , but the code on the wiki only got 3 of them . Casically we need to replace the `hd/index.m3u8` `sd/index.m3u8` & `low/index.m3u8` with the value that we want the VideoResolutionSwitcher to show .

4- Changing the HLS resolution on the FFmpeg command , like `-vf scale=-2:1080` will always display 720p ( on the resolution switcher ), ( I know because the output is called `hd/index.m3u8` , but I want to know how to change it . 

5- One thing I haven't understand well on the Wiki . You mentioned that the encoder will not encode a file ( like 720p into anything above 720p ) . So my question is , writing a code on ffmpeg for all the resolution will it work ? Will it ignore the resolutions that are above the source's one , to save space and resources ?

Thanks

**Comment by DanielnetoDotCom** [comment]
1. yes 240 is the minimum to be encoded

2. do you mean the MP4 files do not have the resolution switcher?

3. Sorry no, it will not work

4. I see, you are right, I will find a way to let you customize what to display

5. the ffmpeg command will be dynamical, the script will detect the original resolution and not upencode videos

**Comment by akhilleusuggo** [comment]
1- No I mean, my 1080p videos got transcoded only to 240p ( not to 240,360,480 ... etc )
2- Sometimes they got like bugged , yes ( I have cleaned the cache )
3- What do you mean , the HLS code will only have 3 resolutions using FFmpeg? 
4- Thanks , would be nice to be like the VideoResolutionSwitcher plugin
5- I didn't understood your answer , since on the 3er question you've said ''Sorry no, it will not work'' , and now you've said ''the script will detect the original resolution''

**Comment by DanielnetoDotCom** [comment]
1. I need to be able to reproduce it, there is a way you can share your video? in my tests it always works
1.1 make sure you have the `ffprobe` command in your encoder server, try this `ffprobe -v quiet -print_format json -show_format -show_streams '$pathFileName'`, that is how we decide the format

2. I also need to be able to reproduce it so I can fix, for example this video is MP4 and has the switcher https://demo.youphptube.com/video/youphptubeintro-1

3. the predefined command only support 3 max resolutions, the dinamicaly command supports up to 7 resolutions

4. yes, I will work on that

5. you have only 2 options to encode HLS:
5.1 let the predefined ffmpeg command encode 3 resolutions for you
5.2 let the dynamical ffmpeg (empty field) choose the resolutions for you (up to 7)

**Comment by akhilleusuggo** [comment]
5.2- But is there anyway to change the parameters of the dynamical ffmpeg ? The quality it's really poor.
Like adding the -preset , the target bit-rate etc

**Comment by DanielnetoDotCom** [comment]
That is how we create it dinamically

https://github.com/YouPHPTube/YouPHPTube-Encoder/blob/ac17ffd3bc231e97dee97d129cd508d6383b76cc/objects/Format.php#L213

there is no way for you to customize it, but we can improve the source if you have a good idea

**Comment by akhilleusuggo** [comment]
I'm not a developer , I'm more on video editing ( that's why i'm more concerned on quality ) . 
But just take a look here : `//$videoBitrate = array(472, 872, 1372, 2508, 3000, 4000);` , you're giving 4000k bitrate for 4K videos ... I mean , you know what quality can be there ... 
Those are more into the average quality : 
![image](https://user-images.githubusercontent.com/52116577/66207546-b6b37d80-e6bb-11e9-9f0d-20d43a4696da.png)

But still , need compression .

```
// create command
            
            $command = 'ffmpeg -re -i {$pathFileName} ';
            $command .= ' -c:a aac -b:a 128k -c:v libx264 -vf scale=-2:240 -g 48 -keyint_min 48  -sc_threshold 0 -bf 3 -b_strategy 2 -b:v '.(300).'k -maxrate '.(450).'k -bufsize '.(600).'k -b:a 128k -f hls -hls_time 15 -hls_list_size 0 -hls_key_info_file {$destinationFile}keyinfo {$destinationFile}res240/index.m3u8';
            
            foreach ($resolutions as $key => $value) {
                if ($height >= $value) {
                    $rate = $bandwidth[$key]/1000;
                    $command .= ' -c:a aac -b:a '.($audioBitrate[$key]).'k -c:v libx264 -vf scale=-2:'.$value.' -g 48 -keyint_min 48  -sc_threshold 0 -bf 3 -b_strategy 2 -b:v '.($rate).'k -maxrate '.($rate*1.5).'k -bufsize '.($rate*2).'k -b:a '.($audioBitrate[$key]).'k -f hls -hls_time 15 -hls_list_size 0 -hls_key_info_file {$destinationFile}keyinfo {$destinationFile}res'.$value.'/index.m3u8';
                }
            }
            
            return array($destinationFile, $command);
        }

```
First I don't understand why do you use `-re` . This is ( as war as I know only for livestream , witch btw you have missed on your wiki for nginx config ) . -re ( like real time ) . If a video got 60mn , no mater what cpu/gpu you have will take 60mn to encode it . ( the speed on the logs on ffmpeg will be always x1 )

`$command .= ' -c:a aac -b:a '.($audioBitrate[$key]).'k -c:v libx264 -vf scale=-2:'.$value.' -g 48 -keyint_min 48  -sc_threshold 0 -bf 3 -b_strategy 2 -b:v '.($rate).'k -maxrate '.($rate*1.5).'k -bufsize '.($rate*2).'k -b:a '.($audioBitrate[$key]).'k -f hls -hls_time 15 -hls_list_size 0 -hls_key_info_file {$destinationFile}keyinfo {$destinationFile}res'.$value.'/index.m3u8';`

For sure here you can implement the preset ( again I don't know PHP , but for sure you can make a link with the plugin to make it more customizable with the $audioBitrate to let give a value )

**Comment by DanielnetoDotCom** [comment]
Ok, -re removed, about the customizable script, maybe in the future I can add it

for now, this must be hard coded
