### ISSUE TITLE
Low quality of animated GIFs and covers. We go to webp format instead of GIF?

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo#2114]
I was looking at how to improve the quality of the covers and animated gifs, because in many cases there is a big difference between the original on YouTube and the copy on YouPHPTube.

I have seen that the ffmpeg command for animated gifs and caratulas in the database is not yet in the encoder, because it is in the php code.
If I'm not mistaken it is in YouPHPTube-Encoder / objects / getImage.php and getImagemp4.php

I propose to use the webp format instead of the gif

Here is an example for ffmpeg:

> ffmpeg -i input.mov -vcodec libwebp -lossless 1 -q: 60 -preset default -loop 0 -an -vsync 0 output.webp

And something similar to this might work in YouPHPTube-Encoder/objects/getImage.php:

`$exec ="ffmpeg -y  -ss {$duration} -t 3 -i \"{$url}\" -vcodec libwebp -lossless 1 -q:60 -preset default -loop 0 -an -vsync 0  {$destination}";`

The generation of gif palette is not necessary

I hope you can take into account for the next version

**Comment by DanielnetoDotCom** [comment]
amazing, for sure I will review it.

thanks so much

**Comment by maxlinux2000** [comment]
Hi Daniel,
Can I test it? how? 
I'm using the 7.7 version of youphptube

**Comment by maxlinux2000** [comment]
mmm... have you consider this panel too?

![Captura de pantalla de 2019-10-20 23-15-16](https://user-images.githubusercontent.com/5683921/67166437-b1c71d00-f38f-11e9-9c66-141812982670.png)

**Comment by DanielnetoDotCom** [comment]
Hi, 

you need to update the encoder and the streamer.

and yes, I will take care of this panel later.
