### ISSUE TITLE
Not Writable on HTML Purifer

### ISSUE THREAD

**Issue by rmsaitam** [WWBN/AVideo#2118]
Adding the Youtube link to the embed video link displays the message "/var/www/html/yourphptube/object/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer not writable"

Permissions already changed in /var/www/html/yourphptube directory
chmod -R 777 /var/www/html/yourphptube

It did not solve.

**Comment by DanielnetoDotCom** [comment]
you made it wrong

if should be `chmod 777 /var/www/html/yourphptube/object/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer`

**Comment by rmsaitam** [comment]
Solved. Thanks.
