### ISSUE TITLE
 Member accounts cannot add photos in Plugin Article's article

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#2121]
Bug fix Member accounts cannot add photos in the Article Article plugin article . This error also occurs on demo.Youphptube.com page

![image](https://user-images.githubusercontent.com/50126312/66280742-4175c180-e8e2-11e9-9492-7b80703284bd.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure how did you do, but I just test on demo site and works fine.

I test with the user: test, pass: test

![image](https://user-images.githubusercontent.com/18009293/66310397-800b7c00-e8e2-11e9-988e-31d103153ccc.png)

what exactly steps did you take to get this error?

**Comment by XemTube-TV** [comment]
Currently I am using user Test on demo.Youphptube.com page. I choose the item Insert / Edit Image => Choose upload. Then receive the error message as the image shown. You can check again 1 time.

![image](https://user-images.githubusercontent.com/50126312/66312804-837f2180-e93b-11e9-8b89-f6f706a035ec.png)

**Comment by DanielnetoDotCom** [comment]
I did the same thing and it works on my side.

can you please clear your browser cache and try again?
