### ISSUE TITLE
Disable ads option - [ Feature request ]

### ISSUE THREAD

**Issue by eZweblogic** [WWBN/AVideo#2124]
Is there a way to disable ads on certain videos?
I looked everywhere for this feature but it's not available or I didn't see it.

If it's not available by default can you consider adding it to future release?
It's especially annoying for the Ad video to be intrrupted with an another ad if viewed directly while some ads are too short to be interrupted.

Thank you

**Comment by DanielnetoDotCom** [comment]
We have this

![image](https://user-images.githubusercontent.com/18009293/66399318-c978cb80-e9b5-11e9-92c4-5631d85e126e.png)

![image](https://user-images.githubusercontent.com/18009293/66399384-e7463080-e9b5-11e9-9e5d-81f9c16e610f.png)

with the allowFreePlayWithAds option, you will not play ads if the user pays for a PPV or a subscription

**Comment by eZweblogic** [comment]
The plugin is not installed. Do I need to buy it even though I paid for the Almost full package that includes all plugins?

**Comment by DanielnetoDotCom** [comment]
I am sorry for that.

when did you purchase the Almost full pack? maybe by that time this plugin does not exist yet.

this plugin is 10 months old, if you purchase your almost full pack after that and we miss this plugin we can fix it and add it into your account.

**Comment by eZweblogic** [comment]
Hi daniel,

That was on 18th May 2018

**Comment by DanielnetoDotCom** [comment]
I see, it is over a year.

feel free to contact me at billing@youphptube.com we can talk about a pack upgrade.
