### ISSUE TITLE
How to upload local video?

### ISSUE THREAD

**Issue by donCaster-tech** [WWBN/AVideo#2125]
Hi I have made a complete installation (encoder and streamer) of youPHPTube on Ubuntu Server, but I have a big issue with video upload. Into the admin account I have only two options in upload menu "encode video and audio" and  "Embed video link". I have seen video with users that have the  possibility to upload video (mp4 as in my case) from local folder, I haven't this option....where I wrong or as I can resolve the problem...thank you

**Comment by DanielnetoDotCom** [comment]
Check those options

![image](https://user-images.githubusercontent.com/18009293/66400911-b4ea0280-e9b8-11e9-943a-adde512ee80c.png)

**Comment by donCaster-tech** [comment]
Hi Daniel, thanks for your fast reply. I'm successuffly configured the buttons for upload local video, but I have another problem. My goal is to create a vod server for intranet use, I'm uploading .mp4 videos files on wich I don't need any encode process, but now after upload the file is not visible on site and stop in 'status: encoding'. How can I upload file as is as, disabling the encoding?

**Comment by DanielnetoDotCom** [comment]
I am not sure what happen, check your log file and also detail here what are you doing to submit the files.

also try to submit the same file on the demo site

**Comment by donCaster-tech** [comment]
maybe the problem is the dimension of the files, I need to upload the videos of 1hr that weight ca 400M. I have configured the php file to consent this dimension, but mayse the platform dont support it

**Comment by DanielnetoDotCom** [comment]
I am not sure what happen, check your log file and also detail here what are you doing to submit the files.

also try to submit the same file on the demo site

**Comment by DanielnetoDotCom** [comment]
a 400 MB file is not an issue

check your log file.

**Comment by donCaster-tech** [comment]
Hi Daniel, I dont know why, but today all magically works...I leaved the server with the issue that I wrote yesterday, today I upload the same video file and it is in Active Status and not  in Encoding. I'm testing the platform on a test server, the goal is create a private platform of video on demand to give like a bonus at our customers. I have two little requests at the moment. I have the possibility to hide the comment box? (I dont need it) and to create an automatic thumbnailn on the video when upload an .mp4 file?. At this moment all the files uploaded are visualized with a black screen and I manually inserting a .jpg logo like a thumbnail. And also, is possible configure a local or remote share as the video source of the site without upload the video anytime? Are all mp4 video files. I'm Sorry if it is not the place to make you all of this questions. Thaks a lot

**Comment by DanielnetoDotCom** [comment]
> I have the possibility to hide the comment box? (I dont need it) 

select No should do the trick

![image](https://user-images.githubusercontent.com/18009293/66483421-6ea9a780-ea7b-11e9-856b-87854808de8a.png)


> and to create an automatic thumbnailn on the video when upload an .mp4 file?.

A commercial plugin can do that
![image](https://user-images.githubusercontent.com/18009293/66483504-93058400-ea7b-11e9-8a31-f5df5b7bd3f1.png)
