### ISSUE TITLE
Encoder Streamer communications

### ISSUE THREAD

**Issue by momoko-squid** [WWBN/AVideo#2127]
My encoder site is having problems communicating with the streamer site..it's not able to get the streamer's operational limits..
Please help

The encoder Max File Size is: 100.00MB
The Streamer Max File Size is: **Loading** ... 
The Streamer Max Video Storage Limit is: **Loading** ...
The Streamer Current Video Storage is: **Loading** ...

**Comment by DanielnetoDotCom** [comment]
are they on the same server?

check your log file for both
