### ISSUE TITLE
Clone site not cloning

### ISSUE THREAD

**Issue by chinobaingo** [WWBN/AVideo#2128]
Using clone site plugin. All videos transfer to my server in videos category but no settings get saved on server. 

Clonesite finished successfully

But Homepage stays blank.  
- I have already checked same version  of youphptube and all plugins are the same
- there are NO errors on youphptube.log
-clone plugin says finished but homepage blank
-videos ARE in video directory of slave server. But it appears the sql database never over writes properly.

My master server is on Ubuntu 16 and my slave server Ubuntu 18. This is the only thing I can think of.

**Comment by fst24sx** [comment]
While this is not the reccomended way of doing it. it is a solution that works in a pinch.   ive had the "clone no work bug"  a few times. this solution fixes it.

export your database from the old site and import into the new one manually.

1. To Export a database from OLD SERVER , open up terminal, making sure that you are not logged into MySQL and type:
mysqldump -u [username] -p [database name] > [database name].sql

2. download the sql file and then upload to new server using FTP

3. To import a database into NEW SERVER, run command:
mysql -u [username] -p newdatabase < [database name].sql

this will import the old database into your newly cloned site. refresh page and it should work.

hope this helps!

**Comment by chinobaingo** [comment]
Thanks! This worked!

Still don’t know why it doesn’t work regular.
