### ISSUE TITLE
... looking for a way to translate the categories

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo#2135]
In my youphptube I have added a few categories in Spanish, from the admin control panel.
I would like if a german or a french or an english comes, they can see the same categories in their language.

How can we do it?

Is there a way to add these categories to Local sentences?

**Comment by DanielnetoDotCom** [comment]
For now, we do not have a solution for that without code.

**Comment by maxlinux2000** [comment]
Please consider to add this in the future... for the moment it can be enougth add the localized categories in the locales php file.
