### ISSUE TITLE
SystemRootPath fucked up

### ISSUE THREAD

**Issue by deuced23** [WWBN/AVideo#2136]
Hey,

i setup a subdomain for my site where i installed the cms inside the directory of my subdomain. As the systemrootpath i chose the default one (which was already registered at the installation setup).

After install, my page won't load correctly. Seems like it can't find the assets and stuff. After looking into my page source, i noticed that the cms forgot to put / after my domain, for example.

https://subdomain.mydomain.comview/img/userSilhouette.jpg

It seems that the cms configured the system path wrong. Also, Opera giving me several errors such as 

- Failed to load resource: net::ERR_NAME_NOT_RESOLVED
- Uncaught ReferenceError: $ is not defined
    at myErrorHandler ((index):428) 

and so on...

 How can i change the rooting? I mean, i used the default root path which was already registered in the setup...

**Edit:**

I tried installing it now on my root directy and still it seems that the cms won't install correctly for some reasons.

```
link href="https://perfectbooties.comview/js/video.js/video-js.min.css" rel="stylesheet" type="text/css"/
--
  | link href="https://mydomain.comview/css/player.css" rel="stylesheet" type="text/css"/
  | link href="https://mydomain.comview/css/social.css" rel="stylesheet" type="text/css"/
  | link href="https://mydomain.comview/js/jquery-ui/jquery-ui.min.css" rel="stylesheet" type="text/css"/
```

As you can see, after .com there is a / missing. Which means, the cms can't find the sylesheets and scripts.

**Comment by DanielnetoDotCom** [comment]
check your videos/configuration.php make sure you add the last slash in the `$global['webSiteRootURL']` variable

**Comment by deuced23** [comment]
Im wondering because I use the exact same files as on my localhost and it didn’t worked by default. I will test it when I am home, thanks for the reply.

**Comment by deuced23** [comment]
> check your videos/configuration.php make sure you add the last slash in the `$global['webSiteRootURL']` variable

`}else{
    $global['webSiteRootURL'] = 'https://tube.perfectbooties.com/';
}
$global['systemRootPath'] = '/home/sites/site100004988/web/tube/';`

As you can see the / is there. And still, it's not working.
Check https://tube.perfectbooties.com/

**Comment by DanielnetoDotCom** [comment]
please check this https://github.com/YouPHPTube/YouPHPTube/issues/2103

**Comment by deuced23** [comment]
> please check this #2103

I followed your instructions.

I get this page now:

`This page isn’t working
tube.perfectbooties.com is currently unable to handle this request.

HTTP ERROR 500`

My config

`<?php
$global['configurationVersion'] = 2;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
$global['webSiteRootURL'] = 'https://tube.perfectbooties.com/';

}
$global['systemRootPath'] = '/home/sites/site100004988/web/tube/';
$global['salt'] = '5da5aeb51f42f';
$global['enableDDOSprotection'] = 1;
$global['ddosMaxConnections'] = 40;
$global['ddosSecondTimeout'] = 5;
$global['strictDDOSprotection'] = 0;

$mysqlHost = ';
$mysqlPort = '';
$mysqlUser = '';
$mysqlPass = '';
$mysqlDatabase = '';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';
`

I deleted the cache folder.

**Comment by DanielnetoDotCom** [comment]
probably because you have a sintaxe error

![image](https://user-images.githubusercontent.com/18009293/66830261-72ca3f00-ef2b-11e9-8a91-7059ce7bcf62.png)

**Comment by maxlinux2000** [comment]
if nothig works have a look in your /etc/apache2/sites-enabled/myexampletube.com

at 

> DocumentRoot "/var/www/html/myexampletube.com/YouPHPTube/"


please remove the last slash like below

> DocumentRoot "/var/www/html/myexampletube.com/YouPHPTube"


then 

`service apache2 restart
`
