### ISSUE TITLE
how to Setup load balancing for youphptube streaming live 

### ISSUE THREAD

**Issue by lamadya** [WWBN/AVideo#2138]
Hi
I use YouPhpTube on main server but my stream freezes
And I want to create load balance on servers I have 2 additional servers
Are You can help me to setup 
thank you for all

**Comment by akhilleusuggo** [comment]
I'm streaming too , I have 2 servers , one with 16 cores , and the second with 20 cores . Both are freezing . I think it's something of the script

**Comment by tiplovo** [comment]
Мой сервер 2 ядро 2 гига оперативной памяти и 60гиг ,все летает ,30 трансляций одновременно. У вас что то неправильно настроено ))))

**Comment by DanielnetoDotCom** [comment]
Just to make clear, YouPHPTube only plays the live, the livestream is another script.

also, we may find help on their project https://github.com/arut/nginx-rtmp-module

**Comment by maxlinux2000** [comment]
Hi Daniel, I have seen that there is a plugin to accept external hls like wonza and others.
This also applies to an external ubuntu server with nginx-rtmp-module?

Practically ... can the livestream be on another server as is already done with the encoder?
And for live could it be saved, does the livestream server save the file in a folder mounted with NFS?
The idea is that the / HLS folder be a mount point shared with NFS between the "livestream server" and the "youphptube server"

**Comment by DanielnetoDotCom** [comment]
I have never tested, but it may work.

**Comment by maxlinux2000** [comment]
ok, I found it!! :) ...searching something with  "nginx-rtpm ffmpeg" 

```
#! /bin/bash
YOUPHPTUBE_URL="rtmp://live.mytube.com/live?p=xxxxxxxxxxxxx" 
SOURCE="MyVideo.mp4" 
KEY="12345789123456" 
ffmpeg -re -i "$SOURCE" \
-c:v libx264 -preset veryfast \
-maxrate 1500k \
-bufsize 3000k \
-pix_fmt yuv420p \
-g 50 \
-c:a aac \
-b:a 80k \
-ac 2 \
-ar 22050 \
-f flv "$YOUPHPTUBE_URL/$KEY"


```
