### ISSUE TITLE
HOME, USER BE DIRECTED TO REGISTER

### ISSUE THREAD

**Issue by apperm7** [WWBN/AVideo#2140]
GOOD AFTERNOON!
HOW TO SET UP FOR USER WHEN HE CLICKES ON SITE HOME AND HE IS DIRECTED TO REGISTER ON SITE.
I AM USING NETFLIX MODEL AND THEME.

**Comment by DanielnetoDotCom** [comment]
what do you mean?

can you please screenshot where would you like to click?

**Comment by apperm7** [comment]
BOM DIA!
NÃO. EU TENHO O YOUPHPTUBE INSTALADO NO MEU SERVIDOR LOCAL NO MEU PC. O QUE ACONTECE, EU INSERI ALGUNS VIDEOS NO SITE E TESTEI SEM NENHUM CADASTRO DE LOGIN E REPAREI QUE OS VIDEOS SÃO POSSIVEIS DE ASSISTIR POR QUALQUER USUÁRIO SEM SE CADASTRAR OU LOGADO, ENTÃO COMO EU CONFIGURO PARA QUE O USUÁRIO AO ACESSAR A HOME SEJA DIRECIONADO A SE CADASTRAR, OU SEJA, O USUÁRIO SO CONSEGUE RODAR OS VIDEOS DEPOIS DE CADASTRADO, DE FAZER LOGIN.

NO AGUARDO.,

ATT
CHARLES


________________________________________________________________________________________________


GOOD MORNING!
DO NOT. I HAVE YOUPHPTUBE INSTALLED ON MY LOCAL SERVER ON MY PC. WHAT HAPPENS, I INSERT SOME VIDEOS ON THE WEBSITE AND TESTED WITHOUT AN LOGIN REGISTRATION AND I REPAIR THAT THE VIDEOS ARE POSSIBLE TO WATCH ANY USER WITHOUT SIGNING UP OR LOGIN, SO HOW I SET UP FOR THE USER TO ACCESS HOME TO IF YOU REGISTER, OR YOU ARE, YOU CAN ONLY ROTATE VIDEOS AFTER REGISTERING, BY LOGINING.

AWAITING.

ATT
CHARLES

**Comment by apperm7** [comment]
GOOD MORNING!
DO NOT. I HAVE YOUPHPTUBE INSTALLED ON MY LOCAL SERVER ON MY PC. WHAT HAPPENS, I INSERT SOME VIDEOS ON THE WEBSITE AND TESTED WITHOUT AN LOGIN REGISTRATION AND I REPAIR THAT THE VIDEOS ARE POSSIBLE TO WATCH ANY USER WITHOUT SIGNING UP OR LOGIN, SO HOW I SET UP FOR THE USER TO ACCESS HOME TO IF YOU REGISTER, OR YOU ARE, YOU CAN ONLY ROTATE VIDEOS AFTER REGISTERING, BY LOGINING.

AWAITING.

ATT
CHARLES

**Comment by DanielnetoDotCom** [comment]
o video pode ser privado, basta remover a opcao de video publico 

![image](https://user-images.githubusercontent.com/18009293/66827297-d1d88580-ef24-11e9-9b35-2626b7d4181b.png)
