### ISSUE TITLE
Enable default plugin

### ISSUE THREAD

**Issue by bluems** [WWBN/AVideo#2154]
when First installed this program, CustomizeUser and more plugin is disabled.
However, even if the plug-in is disabled, the Users Layer still appears in the General settings of the Admin panel.
When I first change this, i didn't know why don't change.
Clicked save button but return no message.

If the plug-in is disabled, program must activate the default plug-in, hide the layer or show a message about it.
(Of course, even if it is recorded in the log.)

**Comment by DanielnetoDotCom** [comment]
CustomizeUser and CustomizeAdvanced do not need to be enabled to the system use its parameters.
