### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by fst24sx** [WWBN/AVideo#2158]
I would like to request the ability to be able to charge users a set amount per video upload. for example $1 per video upload.

1.video uploads disabled for new users
2. user funds wallet with lets say $5
3. upload is enabled for user for 5 uploads.
4. video uploads disabled again until user adds more to wallet.

doing this will all but eliminate spam and useless uploads. most people dont want to pay monthly subscriptions this is perfect for many things.

thanks!

**Comment by DanielnetoDotCom** [comment]
you can request us a quote for that type of feature.

if you want a quote, please email us developer@youphptube.com
