### ISSUE TITLE
customized advanced: videosCDN:

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2163]
Hi,  

I use maxcdn to deliver static content.  

This pulls images/js/css from a predefined folder and delivers it from their edge servers.  

To allow static images etc to be delivered via a different path (https://maxcdn/millzee/cdn/path to files) would I just set the VideoCDN setting to do this or do i need a plugin?  if so can you tell me which plugin I need?

thanks

**Comment by DanielnetoDotCom** [comment]
I guess you can use the CustomizeAdvanced plugin 

that is how I do with CloudFlare https://github.com/YouPHPTube/YouPHPTube/wiki/Using-CDN-for-Videos-Only
