### ISSUE TITLE
Livestreaming shows Offline Tag when Server in encoding

### ISSUE THREAD

**Issue by ChisdealHD** [WWBN/AVideo#2166]
Shows its offline but i correntlyu testing this on Test server and NGINX for RTMP all working and it can be pulled because in localhost and site not on HTTPS in HTTP. 

and i checked if i missing something and far as i know works but tag never changed to online.

Preview: 

![ApplicationFrameHost_XDY4Yi7QjK](https://user-images.githubusercontent.com/18028479/67145024-4d179f80-f275-11e9-9617-c844b51d122a.png)

**Comment by XemTube-TV** [comment]
You may have configured something wrong on Nginx. I can help you check if you agree. You can see it works well at https://xemtube.tv and can contact me there.

**Comment by ChisdealHD** [comment]
sorry to say, is this just promoting your own website.

like legit only need know if something up. not just direct your site because i feel like to and plus your site not English anyways so i wouldn't understand nothing.
