### ISSUE TITLE
User directory

### ISSUE THREAD

**Issue by Exhuned** [WWBN/AVideo#2168]
I'm Currently experiencing a problem with the login system, When i press Sign-in button , it automaticlly redirects me to "http://(iphere)/YouPHPTube/user" wich then shows me a page that says "404 not found, The requested url was not found on this server" , And indeed the user Folder was not In my YouPHPtube folder, I reinstalled it again. Still no change. can you help? thanks

**Comment by XemTube-TV** [comment]
Perhaps you have not configured Apache.

AllowOverride No available as AllowOverride All

**Comment by Exhuned** [comment]
> Perhaps you have not configured Apache.
> 
> AllowOverride No available as AllowOverride All

Sadly , this method dosen't work, :/

**Comment by XemTube-TV** [comment]
If You need reinstallation to work properly, you can contact me via Email: XemTube.TV@Gmail.com. My website for your reference https://xemtube.tv
