### ISSUE TITLE
Msg:TypeError: response.video is null 

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2173]
Hi,

I created a user with the API and now when I try and embed a video I get:
Msg:TypeError: response.video is null 
Url: https://test.domain.com/mvideos?link=1, line: 1391, Address: /mvideos?link=1

I've cleared the videos cache like it advises and retried with same msg.  

any ideas?

**Comment by DanielnetoDotCom** [comment]
Hi, please try to check your log file
