### ISSUE TITLE
embed video - private

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2176]
Hi, 

I am using the youtube plugin and have hidePrivateVideos set.

When i embed a video from say youtube it gets added fine.

If i then log into youphptube as another another user and click the home button I can see videos from other members and play them.    I can also go to their channels and see all their videos.

Am i missing something? or do i need to make another configuration change to secure the videos and channels to be seen by the member who uploaded/embedded them?

thanks

**Comment by XemTube-TV** [comment]
![image](https://user-images.githubusercontent.com/50126312/67211095-60c53080-f444-11e9-8f89-65af9d56ede6.png)

**Comment by millzee01** [comment]
Hi thanks for the info,  unfortunately I dont have that option.  Is it in a plugin?

thanks again!

**Comment by DanielnetoDotCom** [comment]
everyone should have this option, it is when you edit a video

**Comment by millzee01** [comment]
ah so the user has to set this?  is this something we can force with a config or do i need to hard code it to be set automatically?

**Comment by DanielnetoDotCom** [comment]
Look for the PredefinedCategory  plugin


you can choose the default category whenever a video is submitted to your site.

**Comment by XemTube-TV** [comment]
First you create the video category and set the privacy mode. Then use the Plugin

![image](https://user-images.githubusercontent.com/50126312/67253664-1de67580-f4a3-11e9-9f09-0d32429d0bfb.png)

PredefinedCategory sets the default upload uploaded for that category to be.

![image](https://user-images.githubusercontent.com/50126312/67253686-41112500-f4a3-11e9-9fb6-5d62517e9c2b.png)
