### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by felipe5512** [WWBN/AVideo#2178]
I can't install youphptube

Displays this error when connecting to database

**Comment by felipe5512** [comment]
ERROR DELETING USER: VARIABLE "SQL_MODE"  CAN"T BE SET TO THE VALUE  OF " @OLD_SQL_MODE

**Comment by XemTube-TV** [comment]
I will be able to help you if you agree to share your SSH and administrator account so that I can consider your error. You can contact me via Email: XemTube.TV@Gmail.com.

You can refer to my web at https://XemTube.TV
