### ISSUE TITLE
Encoder enable and disable option for users

### ISSUE THREAD

**Issue by sikanderraees** [WWBN/AVideo#2179]
just a quick question how can we disable sharing "Sharing Queue" which shows to everyone how can we disable that no show to everyone so only users can see only their uploaded videos queue.

Please advise  thank you

**Comment by XemTube-TV** [comment]
You can create your own encoder

**Comment by sikanderraees** [comment]
> You can create your own encoder

how ?????

**Comment by DanielnetoDotCom** [comment]
Here https://github.com/YouPHPTube/YouPHPTube-Encoder
