### ISSUE TITLE
Encoder setting

### ISSUE THREAD

**Issue by sikanderraees** [WWBN/AVideo#2180]
will you please help us with the encoder setting which one is best and fast for our script it's showing this option below. so it's using your encoder ? or we can use our encoder if its already installed into our server if yes then what will be the URL for the encoder in order to change into the below option thank you.
![image](https://user-images.githubusercontent.com/40593735/67337913-fec50380-f4f5-11e9-8e63-f806821a1714.png)

**Comment by DanielnetoDotCom** [comment]
those options you mark are for the Encoder Network

please check here https://github.com/YouPHPTube/YouPHPTube-Encoder-Network

**Comment by XemTube-TV** [comment]
@sikanderraees  
If you have a CPU service with 4 or more cores, you should install your own encoder for faster encryption. I can support installing your own encoder so you need support
