### ISSUE TITLE
URL Error!

### ISSUE THREAD

**Issue by thanhsr** [WWBN/AVideo#2184]
**http://vechai.onlineview/.....**
I don't know where can fix it.

       <link href="http://vechai.onlineview/js/video.js/video-js.min.css" rel="stylesheet" type="text/css">
        <link href="http://vechai.onlineview/css/player.css" rel="stylesheet" type="text/css">
        <link href="http://vechai.onlineview/css/social.css" rel="stylesheet" type="text/css">
        <link href="http://vechai.onlineview/js/jquery-ui/jquery-ui.min.css" rel="stylesheet" >

**Comment by XemTube-TV** [comment]
Hello Thanh !
Bạn đang cài YouPHPTube trên hệ điều hành nào. Nếu muốn mình hỗ trợ cài đặt thì cứ gửi tài khoản ssh service và tên miền mình hỗ trợ cho nhé.

**Comment by nazimboudeffa** [comment]
Are you sure that it's the right url as an url should finish by an extension like .com
