### ISSUE TITLE
The requested URL /user was not found on this server.

### ISSUE THREAD

**Issue by mobdatabox** [WWBN/AVideo#2188]
Not Found

The requested URL /user was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by XemTube-TV** [comment]
Please check this to see if you have successfully configured sudo nano /etc/apache2/apache2.conf.

 If you need assistance with installing and configuring YouPHPTube on your service, you can contact me. You can donate as much as you like.

**Comment by Martinsco12** [comment]
Hello team... Please does YouPHPTube (Netflix-type) has PDF/Articles Plugin???

Where one has to subscribe before he/she can read articles/PDF...

I don't have such plugin...

**Comment by mobdatabox** [comment]
I am in china mainland,I can donate to U,but ,I don't know how to pay some
money to you,because I have not PayPal account ,only just use WeChat and
AliPay, do you use these?

Martinsco12 <notifications@github.com> 于2019年10月28日周一 上午7:13写道：

**Comment by mobdatabox** [comment]
I am in china mainland and I have not PayPal ,only use Wechat and
aliPay,how can I pay some money to U ?other question:you use teamviewer to
install YPT?

Martinsco12 <notifications@github.com> 于2019年10月28日周一 上午7:13写道：

**Comment by XemTube-TV** [comment]
You can donetion to me via Paypal if you have an international credit card. 
If you want me to help you can send your teamviewer account via mail XemTube.TV@Gmail.com

**Comment by XemTube-TV** [comment]
@mobdatabox 
You can install YouPHPTube via teamviewer or directly via SSH. The operating system that supports YouPHPTube installation for you is ubuntu 16+

**Comment by mobdatabox** [comment]
yesterday I dowload the latest verision and install it ,all issue has
been fixed,thank you very much for your reply!

XemTube.TV <notifications@github.com> 于2019年11月10日周日 下午3:42写道：

**Comment by XemTube-TV** [comment]
congratulations. whenever you need assistance, please contact me again.

**Comment by mobdatabox** [comment]
OK,Thanks~!

XemTube.TV <notifications@github.com> 于2019年11月11日周一 上午9:20写道：
