### ISSUE TITLE
Urgent Issue for international reference

### ISSUE THREAD

**Issue by Martinsco12** [WWBN/AVideo#2190]
Hello team... Please does YouPHPTube (Netflix-type) has PDF/Articles Plugin??? 

I don't have such plugin... 

Even the Bulk Embed???

And how do I update manually???

**Comment by XemTube-TV** [comment]
See here https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

**Comment by DanielnetoDotCom** [comment]
@Martinsco12  you must enable the plugins for Articles and BulkEmbed

![image](https://user-images.githubusercontent.com/18009293/67673963-110dca00-f95a-11e9-975a-1d19fe5e8633.png)

The PDF is enabled by default but you also can disable it

![image](https://user-images.githubusercontent.com/18009293/67674021-34d11000-f95a-11e9-91d3-4fc01e26b8f9.png)

**Comment by Martinsco12** [comment]
Thanks dude. Am already in love with your script.

But one more stuff please.

My TopMenu plugin is not working.
I have followed the due process but yet not working.

Help out please...

**Comment by DanielnetoDotCom** [comment]
Are you sure you install the TopMenu tables?

check your log file and screenshot/detail the error here

**Comment by Martinsco12** [comment]
No logs sir. I installed the table, yet not working...
