### ISSUE TITLE
PHP Warning:  Error while sending QUERY packet

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2192]
I've been reading a lot of forums how to fix this , but I can not solve it .
I've tried : 
```
max_allowed_packet=524288000
wait_timeout = 100
```
But still having the same error . I'm having this issue only with long videos duration (like stream of 2h )

**Comment by Martinsco12** [comment]
Do you use YouTube style?? What's your site?

**Comment by akhilleusuggo** [comment]
What has YouTube style to do with this ?
And yes I do

**Comment by DanielnetoDotCom** [comment]
I could never reproduce this error.

I guess it comes from mariadb, this does not happen with MySQL

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom It happens only with Multi Bitrate HLS . ( Try to encode some long video with hls , that has 1080p [ leaving empty the encoder line ] to transcode them to all the resolutions possible ) . Long videos I mean +2h ( 1080p )

**Comment by DanielnetoDotCom** [comment]
I see I can only guess it is related to a memory issue.
I know you have a large server, but are you sure you are not using a container that can restrict the memory usage?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom It's a dedicated server ; I can't see where the container can be here . I've installed YouPHPTube on it , that's all .

**Comment by DanielnetoDotCom** [comment]
I am kind of lost

what database are you using? MySQL or MariaDB? what version?

what OS and version?

What PHP version?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom MySQL ( managed by phpmyadmin basically ) , OS ubuntu server 18.04 , PHP 7.2

**Comment by DanielnetoDotCom** [comment]
Do you have a Dedicated server with multiple sites on it or a server with YouPHPTube only?

Do you use any kind of controll panel?

Please did you see those, they have a similar error as you do

https://github.com/YouPHPTube/YouPHPTube/issues/543
https://github.com/YouPHPTube/YouPHPTube/issues/2050

**Comment by akhilleusuggo** [comment]
@DanielForthman Sorry for the late answer . Dedicated server (with no control panel ) dedicated only for YouPHPTube .

**Comment by DanielnetoDotCom** [comment]
the biggest problem is I can not reproduce it.

I don't know what is causing it.

I have longer and larger videos in a simpler server than yours, with fewer resources.
