### ISSUE TITLE
How to code a YouPHPTube plugin

### ISSUE THREAD

**Issue by nazimboudeffa** [WWBN/AVideo#2193]
Hi,

I have started to use YouPHPTube and I want to code a plugin to work with [Wasabi](https://wasabi.com/) API, _I know that it can be used with the Amazone one but anyway just love to code it as I really love the soft_, so I have started to code something that will probably be free like in **free beer** in my GitHub account just called it [Wasaaa](https://github.com/nazimboudeffa/Wasaaa)

My question is that when I upload the file it does display on the plugins table but when I try to activate it ... it hangs

So I have added it to the mysql plugin table with phpmysql, and here it does activate/deactivate

Can someone help me fix this issue

Thank you

**Comment by DanielnetoDotCom** [comment]
Hi, I just create this to try to help you understand how to start

https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-code-a-YouPHPTube-plugin

**Comment by nazimboudeffa** [comment]
Awsome! Thank you very much @DanielnetoDotCom for the quick answer, so it's exactly what I did by following the code of one of the available free plugins, and now the wiki page helps me understand more how it should look

The problem is that my plugin is now referenced in the plugin table but when I try to activate it it hangs, knowing that activating any of the free plugins available by default like Ads works and it adds them in the mysql plugin table and then we can activate/deactivate them in the same way with the button just near the plugin in the plugin table

The purpose of this attempt of coding a plugin is that I want first to retrieve some informations from the videos that are stored on wasabi.com like the duration using the API or I don't know maybe with some Javascript locally on the server but sure with a plugin

![NyvOfwQ4OS](https://user-images.githubusercontent.com/1375686/67791426-b4083600-fa77-11e9-992d-e58b27b96629.png)

You know am new actually to YouPHPTube but I really like it as it does exactly what am searching for

![Kg42GkfXW6](https://user-images.githubusercontent.com/1375686/67791593-fe89b280-fa77-11e9-9e26-a03f05edcb7e.png)

**Comment by nazimboudeffa** [comment]
I have generated it on [an online tool](https://www.uuidgenerator.net/) so I guess that the probability to have the same UUID then another plugin inside the available YouPHPTube plugins is really low

**Comment by DanielnetoDotCom** [comment]
you should be fine then.

check your log file then for some error
