### ISSUE TITLE
Need a Email OPT Out Option and A way to not send email notifications to dead or inactive accounts.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2198]
There needs to be 3 things done with this.

**1.** A way to only allow registration email to Not verified accounts and no other.
Reason: Everytime my admin account uploads something it will try to notify everyone in the database and a lot of time people either use fake emails or have a typo when signing up and there dead account just sits there with the email they used and the website keeps trying to email it and gets the mail blocked for spam activity. 

**2.** A option in the user account that will let a user turn off email notifications.

**3.** Separate SMTP relay options for notification and Registration. That way if say someone purposely keeps using the wrong email or non valid email and gets my mail server flagged it won't stop email signups from working because I will use a separate smtp relay just for that.

**Comment by DanielnetoDotCom** [comment]
1 and 2 I am preparing an update for the Notifications plugin, I will add the option for notifyVerifiedUsersOnly

3, I can not do it now, the SMTP configuration is a site level change, NOT a plugin change.

**Comment by JoshWho** [comment]
I have a custom Notifications file. Could you post what needs changed and I can add it on there.

**Comment by JoshWho** [comment]
Nevermind. I am back to using the normal Notification plugin so no need to patch the custom one I had.
