### ISSUE TITLE
Ad_Overlay plugin is broken

### ISSUE THREAD

**Issue by KenRHill** [WWBN/AVideo#2200]
Hi Daniel,

It appears the Ad_Overlay plugin is somehow broken.  It is enabled on my site, but it will not display the banner ads across my videos, however the same ad code is working correctly at the top of the site.  Did something change with the plugin or the player to make it so that the Ad_Overlay plugin does not work?  This was a major revenue earning tool for us, and to not have it working kind of hurts our ability to make ad revenue with our current ad network.  Please advise.

**Comment by XemTube-TV** [comment]
When I choose to disable disableYoutubePlayerIntegration, the AD_Overlay Plugin will not work.

**Comment by KenRHill** [comment]
Hi Daniel, I was running AdClickMedia code using the ad overlay plugin in version 7.4. It was working fine until recently. I also recently upgraded the site to version 7.7. Now the Ad Overlay plugin isn't even displaying, even though it is enabled. The same Ad code does work on our site in the top leaderboard, but only if we use the Ads plugin, so I know its not the Ad code itself. It is my belief that something happened between the two versions where this plugin no longer works like it did. Can I revert back to the previous 7.4 version, I backed up the site files except for the database before upgrading. If there is no fix for that I would like to revert back to 7.4. If I can revert back, what do I need to do? My site is at https://videorefuge.com

**Comment by XemTube-TV** [comment]
Please update to version 7.8. It will fix this problem for you.

**Comment by DanielnetoDotCom** [comment]
Hi @KenRHill 

I am not aware of any AdOverlay issue

I just create a user daniel in your site, if you can make me site admin I will take a look into your configurtions.

**Comment by KenRHill** [comment]
Hi Daniel,

I just made your account a site administrator.  I also contacted AdClickMedia and they can't see anything on there end preventing any ads from displaying, and said I should be ok from their end. 
 Please feel free to look over the ad code and make whatever changes are necessary.  I am going to try to post the Ad code on the demo site and see if it works.  I will let you know. Thanks for your help.

**Comment by KenRHill** [comment]
I just tried the Ad_Overlay plugin on the demo site.  It appears the Ad_Overlay plugin background is working at least.  The ad code is not setup to work on your domain through the ad code provider we use, so no ads from them will display on your demo site, however it appears on the demo site that the plugin seems to be functional.  I have not upgraded to YouPHPTube version 7.8 yet.  Maybe I should try that and see if it fixes the problem as suggested by XemTube-TV.  I can try the upgrade later today and see if the upgrade works to correct this.  If the upgrade does not correct the issue, can I use the old site files to revert back to the version that worked?

Also on a side note, our website is really slow right now, due to a lot of users watching videos.  Is it possible to upgrade the bandwidth on the dedicated servers that you provide?  Currently a command line speedtest reveals 86Mbps down and 16 Mbps up.  Is there a way to increase the amount of bandwidth for these servers to meet demand?  I don't think we have enough bandwidth to keep up with current demand.

**Comment by DanielnetoDotCom** [comment]
About the site slow, I notice you are displaying multiple categories.

I have admin access now, I will reduce the total videos per category to display, and you will let me know if you feel a difference

**Comment by DanielnetoDotCom** [comment]
What I found so far...

I reduce the number of videos and also enable the cache to let you handle more concurrent users.

Looks like your update was not properly done, so I follow this and force to update to the latest 7.8
 https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

now your ads overlay is showing

If you still want to upgrade the server please email me at developer@youphptube.com

**Comment by DanielnetoDotCom** [comment]
Also, I just enable your VideoThumbnails you have about videos

I am not sure why it was disabled, but I can tell you it works pretty good now.

I can see in your CPU it is processing all your videos now. It may take a while to complete.

**Comment by KenRHill** [comment]
It appears the Ad_Overlay problem has been resolved.  The site is loaded down again even with the changes you have made, due to the fact that we are experiencing a growth in server traffic during certain times of the day.  Right now I can't even access the site because it is so busy, however... I will email you with questions and see if we can't figure out migrating everything over to another server and then setting up S3 storage for future uploads.

**Comment by DanielnetoDotCom** [comment]
I can imagine you server was slow, processing over 800 videos thumbs at the same time .

I just disable the videos thumbnails please check again
