### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by Martinsco12** [WWBN/AVideo#2201]
Please how do I upload a PDF?

**Comment by DanielnetoDotCom** [comment]
PDF should be enabled by default, just like a direct video upload

you can disable the PDF here 
![image](https://user-images.githubusercontent.com/18009293/67957324-2db53680-fbd4-11e9-84f7-f9d2679f412e.png)

**Comment by Martinsco12** [comment]
Can you please help me with the screenshot. Show me the link.


Will be buying a plugin too but costly.

**Comment by DanielnetoDotCom** [comment]
What screenshot?
![image](https://user-images.githubusercontent.com/18009293/67966455-aae7a800-fbe2-11e9-9b8b-5b8113f1bf83.png)


![image](https://user-images.githubusercontent.com/18009293/67966532-cd79c100-fbe2-11e9-822d-1a03b98219a5.png)


why can't you upload a PDF?

what is the error message?

**Comment by Martinsco12** [comment]
Settled. Thanks...
