### ISSUE TITLE
Allow LiteSpeed

### ISSUE THREAD

**Issue by OptixLLC** [WWBN/AVideo#2203]
It says apache2 has to be installed but I believe that it will work on LiteSpeed

**Comment by JoshWho** [comment]
It will work but won't be supported for tech help. You will have to figure out how to make certain things work that would normally be set with Apache. 

Currently the only test environment that the core is building on is with Ubuntu Apache Mysql and Nginx. 

You won't be able to get to much support here for Litespeed.
