### ISSUE TITLE
Layout for the Live Streams gets buggy after 10 online

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2204]
After more than 10 streams are live the layout starts getting really weird and scatters the streams.

<img src="https://static.buddylist.co/x/formatlayout.png" border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
the problem is because of this user name has 2 lines, so is not the total amount of lives

We will ty to fix this layout in the future

![image](https://user-images.githubusercontent.com/18009293/68022863-509f2380-fc84-11e9-9892-781505fe1d69.png)

**Comment by JoshWho** [comment]
Ahhhh I C

**Comment by JoshWho** [comment]
I shortened all the titles and it still spaces out the bottom row for some reason. Must be some element that is hidden or something acting as a spacer. Looks fine in mobile view. It is only like this on Desktop browsers.

**Comment by DanielnetoDotCom** [comment]
Are you saying you made all titles one line only and still the problem?

**Comment by JoshWho** [comment]
Correct.

**Comment by DanielnetoDotCom** [comment]
can you please screen it shot again?

**Comment by JoshWho** [comment]
I will next time another person goes live.
