### ISSUE TITLE
embed youtube video - fullscreen issue

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2212]
Hi,

for some reason when I embed a youtube video I get the "full screen is unavailable" message on the embedded player (even when I have allowfullscreen="allowfullscreen" set.

this only happens when I play the video on an embedded page using https://mydomain.com/videoEmbed/video-name

Yet if i play the video using the standard link:
https://mydomain.com/video/video-name then the fullscreen option works as normal.

Is there something I need to do to make the videoEmbed player allow full screen?

thanks

**Comment by DanielnetoDotCom** [comment]
the main problem I can see here is because it will be an iframe inside another iframe.

I am not sure if it will work. it requires some research.

**Comment by millzee01** [comment]
i see, however  other functions seem to be ok like setting the quality and annotations etc which may be because they are not accessing the client.  And when u press f11 the iframe goes full screen but not the video.

**Comment by DanielnetoDotCom** [comment]
I am pretty sure it is a browser limitation.

Is very uncomun you use an iframe inside another iframe.

if you want to embed domething, you should use the direct link, NOT double embed things
