### ISSUE TITLE
Request: Disable VIdeo Ads on Embed Videos

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2214]
Would be kewl to be able to turn off the Vast Video ads for Youtube embeds. 

Reason for this: The ads stop the autoplay from working on the video. After the ad plays the YT video looks paused and you have to click the Pause button to make it play. 

I know I can disable the custom player and that would do it but wouldn't look good on the site anymore.

No rush on this but would be a neat feature to make a switch for this in the Customize menu or something.

**Comment by JoshWho** [comment]
Im going to try to integrate the https://plyr.io/  Player to use just for Youtube and see if this works out. I will post back my results.

**Comment by JoshWho** [comment]
OK it is a fail. NO GO. the main default site player overrides all settings.

**Comment by DanielnetoDotCom** [comment]
what VAST plugin are you using GoogleAds_IMA?

**Comment by JoshWho** [comment]
I was using both. I have them disabled. Would be a good idea though for switches on both though.
