### ISSUE TITLE
REQUEST: Video Creator Ad Slots for Self Monetization

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2217]
This would be a really exciting feature to have for your video platform. This will allow creators to make money using your platform and you won't have to be the payee.

Setup a Ad Code box in the User Profile Page.

Make it to where admins have to approve or have a list of **approved domains** for ad code.
A filter system for certain link patterns. That way if someone tries to do a bad redirect or java hack or something it will get rejected.

This will help prevent abuse of the system. 

Google already allows other publishers ads to be placed with the site owners.

https://www.youtube.com/watch?v=SYu4lRJoFEo

The ads could be in their description box and in the Video player using the Ad Overlay feature.

**Comment by JoshWho** [comment]
UPDATE REQUEST:

Since we are having problems with adsense resizing issue can the ad be placed under the video instead?

**Comment by DanielnetoDotCom** [comment]
can you please add some screenshots here so I understand better the issue?

**Comment by JoshWho** [comment]
<img src="https://static.buddylist.co/3c1ced08-9f34-482a-9ff4-905fbbe1c0c0.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
ths thing is the ad overlay is inside the video I can not move it to outside.

maybe we can make a better job to make it more resposible.

please give me a sample of a non responsive ad, so I can work and fix it.

**Comment by DanielnetoDotCom** [comment]
Please update and try again
