### ISSUE TITLE
Could not login when MaintenanceMode

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#2219]
Hi,

I can't login when the system is in "MaintenanceMode". It refers to YouPHPTube/user but no login_screen is coming up.  When i disable MaintenanceMode (plugin) the login_screen is showing when i click on that locker.

![Snap1](https://user-images.githubusercontent.com/39981177/68118004-2f963700-feff-11e9-8333-da024a7f985e.jpg)

Regards, Theo

**Comment by DanielnetoDotCom** [comment]
Hi, sorry, I am confused

are you able to login now or not?

if you disable the MaintenanceMode you should not see this screen anymore.

if you have the MaintenanceMode enabled, the green lock should send you to the login screen

**Comment by TLCReuver** [comment]
Yes, sorry... it is indeed to confuse 

In one browser i'm logged in as admin and set to MaintenanceMode to the "on"-position.
With second browser with guest rights i want to login with the green lock. This lock refers to YouPHPTube/user it does nothing at all, so i don't see the login-screen.

When i turn off the MaintenanceMode in the first browser (with admin rights) and go to the second browser (with guest rights) then the green lock works perfect and i see the login-screen.

**Comment by TLCReuver** [comment]
You can test it on:
http://media.beesel-reuver.nl/

**Comment by DanielnetoDotCom** [comment]
can you please screenshot your CustomizeUser plugin parameters?

![image](https://user-images.githubusercontent.com/18009293/68127593-f3f66f80-fef4-11e9-93dd-6b4c5694e1c0.png)
 

and also all other options.

**Comment by TLCReuver** [comment]
Here are my **CustomizeUser** plugin parameters:

![Total_80](https://user-images.githubusercontent.com/39981177/68133379-89f3bf80-ff20-11e9-9c29-56a06a233c10.jpg)

**Comment by DanielnetoDotCom** [comment]
Sorry, but I still have no clue

I guess it must be something regarding some plugin configuration.

can you please disable the cache, just to make sure is nothing related to it?

also, how is your customizeAdvanced?

**Comment by TLCReuver** [comment]
I disabled the cache, cleared the cache & logs (also apache) give no errors.

I know, its hard to solve this when you couldn't reproduce it.

Here is my customizeAdvanced (in pieces)

![Snap1](https://user-images.githubusercontent.com/39981177/68138202-74829380-ff28-11e9-9e57-19225cb2d0ec.jpg)
![Snap2](https://user-images.githubusercontent.com/39981177/68138214-78aeb100-ff28-11e9-88e2-81948d621095.jpg)
![Snap3](https://user-images.githubusercontent.com/39981177/68138222-7cdace80-ff28-11e9-9d61-43d14a0b8011.jpg)
![Snap4](https://user-images.githubusercontent.com/39981177/68138232-8106ec00-ff28-11e9-86b5-ec989d70e253.jpg)
![Snap5](https://user-images.githubusercontent.com/39981177/68138242-85330980-ff28-11e9-9930-f9c1cda118c5.jpg)
![Snap6](https://user-images.githubusercontent.com/39981177/68138252-88c69080-ff28-11e9-93e5-06a9dde7f12f.jpg)
![Snap7](https://user-images.githubusercontent.com/39981177/68138256-8b28ea80-ff28-11e9-883b-43417520daf7.jpg)

**Comment by DanielnetoDotCom** [comment]
Sorry, I still can not see any problem.

last chance, can you please try to disable the plugin one by one?

or if you do no mind truncate your plugins table, it will reset all your configuration.

**Comment by TLCReuver** [comment]
Hi Daniel,

Truncating the plugins_table & clearing the cache did not solve the problem.  
Maybe is it the system with multiple PHP_versions in Oracle VM with multiple vHosts what is causing the problem.
But many thanks for spending time for this issue.

Regards, Theo.

**Comment by DanielnetoDotCom** [comment]
Thanks for the update, if clear the plugins table does not slove, I have no idea what is causing that
