### ISSUE TITLE
File not found : fullscreen.css

### ISSUE THREAD

**Issue by tgd1973** [WWBN/AVideo#2220]
Failed to load resource: the server responded with a status of 404 (Not Found)  in  https://www.site.com/plugin/YouTube/fullscreen.css

**Comment by DanielnetoDotCom** [comment]
I am pretty sure you do not own the domain www.site.com

**Comment by DanielnetoDotCom** [comment]
I am not sure what if it will work, but I am sending an update.

**Comment by tgd1973** [comment]
Unfortunately for me it doesn't work. When I put the modified file ... if I activate the YouTube plugin, the player takes a fixed position overlaying all the other parts of the browser, deactivating the whole page without the possibility of exiting this setting.
I tried to duplicate the problem on the demo server but I think it still has a different version of the file ... because it doesn't give me any problems.

**Comment by DanielnetoDotCom** [comment]
the demo site always use the latest version

make sure your site also has the latest
