### ISSUE TITLE
( ! ) Notice: Undefined variable

### ISSUE THREAD

**Issue by mobdatabox** [WWBN/AVideo#2221]
I  install the YPT on the windows7 with wamp successfully.after I embed a video url , and play this Video,Video can be play normal, but above players shows below info:
 
****( ! ) Notice: Undefined variable: imgw in C:\wamp\www\YouPHPTube\objects\functions.php on line 2150 Call Stack #TimeMemoryFunctionLocation 10.0010386464{main}( )...\index.php:0 20.0300710288require( 'C:\wamp\www\YouPHPTube\view\modeYoutube.php' )...\index.php:25 30.08501224408getOpenGraph( )...\modeYoutube.php:220 " /> ( ! ) Notice: Undefined variable: imgh in C:\wamp\www\YouPHPTube\objects\functions.php on line 2151 Call Stack #TimeMemoryFunctionLocation 10.0010386464{main}( )...\index.php:0 20.0300710288require( 'C:\wamp\www\YouPHPTube\view\modeYoutube.php' )...\index.php:25 30.08501224408getOpenGraph( )...\modeYoutube.php:220 " />**

    YouPHPTube**

above info shows in my Godaddy.com VirHost also,How can I solve it ? thanks!

**Comment by mobdatabox** [comment]
![functionvarerro](https://user-images.githubusercontent.com/55123413/68210867-6e1c1680-0011-11ea-8b97-98fef5091deb.png)

**Comment by mobdatabox** [comment]
![Firefox_Screenshot_2019-11-05T13-19-33 655Z](https://user-images.githubusercontent.com/55123413/68211174-06b29680-0012-11ea-9290-e4581e329dae.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, we can only support installations on Ubuntu

**Comment by mobdatabox** [comment]
16.4 and 18 ubuntu all shows.

**Comment by DanielnetoDotCom** [comment]
An notice should not stop your code to work, but anyway, I just sent an update to avoid this error
