### ISSUE TITLE
HTTP:// to HTTPS://

### ISSUE THREAD

**Issue by Martinsco12** [WWBN/AVideo#2222]
Hello sir, thanks for your wonderful work. 

Please I have installed my ''SSL CERTIFICATE'' into my web server and placed the code at .htaccess 

My site is redirected to HTTPS but the green padlock is not showing...

Does it take days before the green padlock appears??

**Comment by Martinsco12** [comment]
It also tells me

   ''some parts of your website is not safe such as ''images''

**Comment by Martinsco12** [comment]
I did already. 

How do I change that for images

**Comment by DanielnetoDotCom** [comment]
I am not sure what you mean

**Comment by gregkeys** [comment]
i'm getting a similar issue, using ssl, the index page is secure but all assets are served as http which breaks ssl

**Comment by DanielnetoDotCom** [comment]
@gregkeys to fix it make sure you change it in your configuration.php file

**Comment by gregkeys** [comment]
To fix I had to remove the following from the configuration.php file

```PHP
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { 
                // get the subdirectory, if exists
                $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
                $global['webSiteRootURL'] = "https".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
            }else{
                $global['webSiteRootURL'] = 'https://avideo.example.com';
            }
```

and just add 

```PHP
`$global['webSiteRootURL'] = 'https://avideo.example.com';`
```

Note that our deployment was with docker & kubernetes along with an AWS ALB so our use case might not be typical.

**Comment by SergejGrin** [comment]
Faced a similar problem. Tell me which (where it is located) configuration.php file needs to be edited?

**Comment by SergejGrin** [comment]
Thank you all, I figured it out myself. He asked himself - he answered. This file is located /var/www/YouPHPTube/videos
![YouPHP4](https://user-images.githubusercontent.com/59236880/72225674-64221100-3588-11ea-8e3b-0c302f477d9b.png)
I added just one letter 's' (http -> https) 
Changed
 $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
on the
$global['webSiteRootURL'] = "https".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
and the problem (with streamer) disappeared
