### ISSUE TITLE
Settings Changes Not Saving

### ISSUE THREAD

**Issue by FaisalArifi12** [WWBN/AVideo#2228]
Hello dear
Thanks for developing a fantastic Project
Recently i have install YouPHPTube Script on my Server But Now When i want to Change the Settings its not going to Save and it go back with Default Like I wanted to uncheck do not show mp4 Upload to Show Mp4 Upload but when i save it, it go back to default and its Checked.
Please Help me to reslove the Issue.
Thanks

**Comment by DanielnetoDotCom** [comment]
can you please check your error log file?
