### ISSUE TITLE
NETFLIX

### ISSUE THREAD

**Issue by Martinsco12** [WWBN/AVideo#2230]
Hello sir, can you change the background colour to black, I mean Netflix-type of black colour. Pure black.

???

**Comment by DanielnetoDotCom** [comment]
Hi, try to edit the plugin YouPHPFlix2 

![image](https://user-images.githubusercontent.com/18009293/68405233-7a61ba00-015e-11ea-9cb8-2e01ddd9b1fc.png)

**Comment by Martinsco12** [comment]
Thanks, it works but just for the upper big video..

I want the black colour to be in the theme. The whole background..

**Comment by DanielnetoDotCom** [comment]
I see, so you can create a custom CSS (you need to know how to deal with CSS of course)

https://github.com/YouPHPTube/YouPHPTube/wiki/Site-Design-and-Templates#add-a-custom-css
