### ISSUE TITLE
SERIOUS ISSUE ON GOOGLE

### ISSUE THREAD

**Issue by Martinsco12** [WWBN/AVideo#2236]
My site could not be indexed on Google.

Google says that ROBOTS.TXT is blocking it!!!

What do I do please???

**Comment by DanielnetoDotCom** [comment]
Hi, 

we have many sites indexing on google with no problem and that is our robots.txt https://demo.youphptube.com/robots.txt

are you sure that is the problem?

can you screenshot the Google's message? where are you testing it?

**Comment by Martinsco12** [comment]
![Screenshot_20191108-235850](https://user-images.githubusercontent.com/56042911/68529304-8fc11a80-02fd-11ea-915e-00a5817141b8.png)

**Comment by Martinsco12** [comment]
![Screenshot_20191109-150644](https://user-images.githubusercontent.com/56042911/68529826-f72d9900-0302-11ea-9ea2-f93850ad2e31.png)

**Comment by DanielnetoDotCom** [comment]
Did you try the robots txt tester?

**Comment by Martinsco12** [comment]
Can 
![Screenshot_20191111-231242](https://user-images.githubusercontent.com/56042911/68625223-e46cbd00-04d8-11ea-9ce9-21bf3f3e2a95.png)

Can I edit it and change the ''mvideos'' to allow???

**Comment by DanielnetoDotCom** [comment]
sorry, you can not, and also it does not make sense.

mvideos is for logged in users only.
