### ISSUE TITLE
Suggestion video list issue

### ISSUE THREAD

**Issue by sikanderraees** [WWBN/AVideo#2237]
Hello Dev,

How can we set suggestion video list for example,
Once we play any video so on right side video list shows only recent videos which is suppose to display same category or same tittle videos list. 
KINLDY advise how can we fix or set suggestion video list after play any video. 

Thank you.  
Best regards Myvidplay

**Comment by DanielnetoDotCom** [comment]
Hi try to select this to always keep suggesting videos from the same channel

![image](https://user-images.githubusercontent.com/18009293/68527463-0cd09d80-02c6-11ea-9f76-8a9c575927ce.png)

You can also set the next video for each video

![image](https://user-images.githubusercontent.com/18009293/68527496-41dcf000-02c6-11ea-88a0-a263e4520e82.png)

**Comment by sikanderraees** [comment]
All right sir is there any ways we can set suggested videos as per category as well as title match please advise thank you and appreciate

**Comment by DanielnetoDotCom** [comment]
Sorry we do not have that feature
