### ISSUE TITLE
get live to work

### ISSUE THREAD

**Issue by ucmafialtd** [WWBN/AVideo#2240]
what needs to be done so live works get live to work

**Comment by DanielnetoDotCom** [comment]
Hi, do you mean the Livestream?

if yes, you need to install and configure NGINX RTMP try this https://tutorials.youphptube.com/video/10-min-youphptube-stream-server-installation

**Comment by ucmafialtd** [comment]
Yes can't get to work

UC MAFIA LTD.
David Bernard Jr
CEO
1-833-UCMAFIA(826-2342)
EXT.810
https://ultimatecarparts.shop
info@ultimatecarparts.shop
https://uclimited.app
info@uclimited.app

**Comment by DanielnetoDotCom** [comment]
What is the error.

You can try to get help how to fix by your own here or you can hire us to install it for you.

To help you fix by your own we will need more details , screenshots and logs

**Comment by ucmafialtd** [comment]
It's says offline

UC MAFIA LTD.
David Bernard Jr
CEO
1-833-UCMAFIA(826-2342)
EXT.810
https://ultimatecarparts.shop
info@ultimatecarparts.shop
https://uclimited.app
info@uclimited.app

**Comment by DanielnetoDotCom** [comment]
To be able to help you you need to provide more details.

If you were able to connect into your nginx server , what is your URL, , screenshots , nginx and Apache log, etc

**Comment by ucmafialtd** [comment]
Bro I've spent at least $200 on your plugins in the last 3 days you can't
just help somebody out when is it supposed to be open source and I'm still
paying for your s*** the light is supposed to be included now I got to set
f****** everything up dude like this is starting to get irritating like I'm
not going to pay you to set up one freaking thank dude so either you want
to help me out or I'll get it figure it out and then I'll let everybody
know across social media how great your helping services f****** I'm done
with people doing the stupid s***

UC MAFIA LTD.
David Bernard Jr
CEO
1-833-UCMAFIA(826-2342)
EXT.810
https://ultimatecarparts.shop
info@ultimatecarparts.shop
https://uclimited.app
info@uclimited.app

**Comment by DanielnetoDotCom** [comment]
I do not understand why you are so rude and upset.

Again I am not able to help you without informations

**Comment by ucmafialtd** [comment]
Bro do you have a phone number I can call please this whole emailing back
and forth and doing this stuff over text obviously you don't understand and
other people don't understand over email or text it's so much better to
just talk to somebody or if you don't want me to have your phone number
here's my personal cell phone number please call that it'd be so much more
easier bro I'm not trying to be rude and I'm not trying to be upset I've
been trying to get this stuff to run good for over a week now I spent a few
hundred dollars on your plugins bro I'm just getting irritated I've asked
you for your help a few times and I get this GitHub s*** or email back and
forth like I would rather just talk I apologize if you took me as rude but
I'm trying to just get my s*** running bro correctly,
725-2087969

UC MAFIA LTD.
David Bernard Jr
CEO
1-833-UCMAFIA(826-2342)
EXT.810
https://ultimatecarparts.shop
info@ultimatecarparts.shop
https://uclimited.app
info@uclimited.app

**Comment by ucmafialtd** [comment]
Maybe I got it all set up through the wrong people bro I don't know if you
know who, turnkey is but that's who I got setup through thinking for the
first few days that it was there software and then find out otherwise by
hitting the plug-in thing that it wasn't there software now don't me wrong
dudes been trying to help but he's not familiar with your stuff which I
don't understand if they're hooking it up and calling it turn key if they
don't fully know your setup and then I bought in plugins and then it's just
been a mess bro and I'm getting frustrated I would really appreciate if we
can just talk on the phone and get it handled I appreciate more than
anything in the world bro

UC MAFIA LTD.
David Bernard Jr
CEO
1-833-UCMAFIA(826-2342)
EXT.810
https://ultimatecarparts.shop
info@ultimatecarparts.shop
https://uclimited.app
info@uclimited.app

**Comment by ucmafialtd** [comment]
Can we talk on the phone please?Yes no maybe so?

**Comment by ucmafialtd** [comment]
Hello

UC MAFIA LTD.
David Bernard Jr
CEO
1-833-UCMAFIA(826-2342)
EXT.810
www.gappedtube.com
https://ultimatecarparts.shop
support@ultimatecarparts.shop
https://uclimited.app
support@uclimited.app

**Comment by DanielnetoDotCom** [comment]
Hi, please email me at developer@youphptube.com

**Comment by ucmafialtd** [comment]
I think I need to restore my backup from earlier I might have screwed up
something

UC MAFIA LTD.
David Bernard Jr
CEO
1-833-UCMAFIA(826-2342)
EXT.810
www.gappedtube.com
https://ultimatecarparts.shop
support@ultimatecarparts.shop
https://uclimited.app
support@uclimited.app

**Comment by XemTube-TV** [comment]
@ucmafialtd 
I can help you reinstall all YouPHPTube for it to work. You can donatione as many as you like or not. Just give me SSH 1 VPS of Ubuntu 16+ and within 2 hours I will perfect for you.

**Comment by JedMeister** [comment]
FYI, in the TurnKey appliance, rather than compile Nginx from source, we use the pre-built rmtp Nginx module from [stretch backports](https://packages.debian.org/stretch-backports/libnginx-mod-rtmp). FWIW our current v15.x range of appliances are based on Debian 9/Stretch. FYI you can see our Nginx/Live Streaming setup and config [here](https://github.com/turnkeylinux-apps/youphptube/blob/master/conf.d/main#L55-L66).

As per my previous comment, I didn't actually test the "live streaming" functionality myself, but the (community) developer that developed the YouPHPTube appliance explicitly said that he had tested it and it was working fine (we had some issues initially, but I worked through them with him).

As an aside, I've been working on updating to v16.0 (which will have a Debian 10/Buster base) for a while now and I'm not far away from migrating all our appliances to that. We were intending to use Nginx (and the RTMP) module from Buster for the live streaming component.

If you think that using default Nginx packages from Debian may be problematic, I'd be interested to hear.

Regardless, do you have documentation on how to test the live streaming feature? I recall seeing something somewhere that was using OBS to stream to YouPHPTube, but I can't find it now?!

**Comment by DanielnetoDotCom** [comment]
Hi @JedMeister that is how I test the live stream https://tutorials.youphptube.com/video/youphptube-video-stream-with-obs-and-vmix
