### ISSUE TITLE
video thumbnales showing white background with play button 

### ISSUE THREAD

**Issue by veljkostanar** [WWBN/AVideo#2242]
I have an issue videos not autogenerating thumbnales. both the encoder and streamer are on the same server. The video uploads okay on all resolutions. the animated Gif works okay but all videos regardlress of file size have a white background with the play button as a thumbnale. I checked the log files and noticed this 

[11-Nov-2019 03:05:35 UTC] PHP Warning: filectime(): stat failed for /var/www/html/nws/videos/_YPTuniqid_5dc8cfdf78d5b4.36003691_portrait_thumbsV2.jpg in /var/www/html/nws/objects/video.php on line 2255

[11-Nov-2019 03:05:35 UTC] im_resize: Function does not exists: imagecreatefromjpeg

Update to this the thumbsV2.jpg file does not get created but the reference to it does so i do have a workaround of manually creating on from the non .thumbsv2.jpg file and placing it in the same folder .
still like to know why this error is happening

**Comment by Martinsco12** [comment]
Its very simple brother..

After uploading a video, Click ''EDIT'' and add your images.. poster.jpg.  (JPG FORMAT)

Always add your posters after video upload.

**Comment by DanielnetoDotCom** [comment]
@veljkostanar 

Your error is **im_resize: Function does not exists: imagecreatefromjpeg**

try this https://stackoverflow.com/questions/13338339/imagecreatefromjpeg-and-similar-functions-are-not-working-in-php
