### ISSUE TITLE
Upload to youtube

### ISSUE THREAD

**Issue by omarruben** [WWBN/AVideo#2243]
Hello I have this error after clicking on the upload video to youtube

A service error occurred: { "error": { "errors": [ { "domain": "youtube.video", "reason": "invalidDescription", "message": "The request metadata specifies an invalid video description.", "locationType": "other", "location": "body.snippet.description" } ], "code": 400, "message": "The request metadata specifies an invalid video description." } } 

system debian 10
youtube account created and give permission without any problem

**Comment by DanielnetoDotCom** [comment]
but do ou have a valid description??

can you please check if it is an error due an invalid character?
