### ISSUE TITLE
Email verification error

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2244]
All new users getting this error, how to fix it ?

![image](https://user-images.githubusercontent.com/52116577/68583961-75b74180-048f-11ea-82d0-33f04559444a.png)

**Comment by DanielnetoDotCom** [comment]
Maybe they are receiving multiple emails verifications.

they must using the last one.

**Comment by akhilleusuggo** [comment]
no , they received only 1 . I have tested it myself , I got only 1 and it does give me the same error . How can I debug it ?

**Comment by DanielnetoDotCom** [comment]
Hi, 

should be something on the log file, to be able to debug you will probably need to put some codes there.

can you reproduce it on the demo site?

**Comment by JoshWho** [comment]
Seems like to me you are not using an SMTP  relay and some of the emails are getting delayed or dropped completely. If they are not receiving the first email and keep trying to login it will generate a new link and email them over and over until they get it right.
