### ISSUE TITLE
ARTICLE

### ISSUE THREAD

**Issue by Martinsco12** [WWBN/AVideo#2245]
Can I add Pictures inside the article???

**Comment by DanielnetoDotCom** [comment]
Yes, I guess you do.

**Comment by Martinsco12** [comment]
Am unable. I only do copy and paste.

I don't have the DESCRIPTION features to colour my article or add photos.

**Comment by DanielnetoDotCom** [comment]
here

![image](https://user-images.githubusercontent.com/18009293/68588380-1f82d800-0468-11ea-9d3b-2b3387f6fdff.png)

**Comment by Martinsco12** [comment]
![Screenshot_20191111-181956](https://user-images.githubusercontent.com/56042911/68606995-f1c18180-04af-11ea-8e3e-efd1d8b75afa.png)



That is my screenshot....

No ''DESCRIPTIVE FEATURES''

**Comment by DanielnetoDotCom** [comment]
First thing, try it from a PC, NOT from a mobile

also, make sure this option is not enabled
![image](https://user-images.githubusercontent.com/18009293/68607240-ef026480-048e-11ea-90f9-1b83ad6a5295.png)

**Comment by Martinsco12** [comment]
![Screenshot_20191111-183452](https://user-images.githubusercontent.com/56042911/68607898-03a42400-04b2-11ea-9984-944f00c5a4c7.png)



That is my screenshot sir....

No ''DESCRIPTIVE FEATURES''

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/68608012-b4013080-0490-11ea-996a-6ff4a2b71167.png)

**Comment by Martinsco12** [comment]
Yes. I did not check the box.

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/68608266-37228680-0491-11ea-864a-acb7798e3db7.png)

**Comment by Martinsco12** [comment]
Ok. I will use my PC in an hour's time

**Comment by Martinsco12** [comment]
Thanks in advance till I confirm.

I will come back for a testimony if it works... Lol

**Comment by DanielnetoDotCom** [comment]
Great thanks
