### ISSUE TITLE
how to bann users fast please 

### ISSUE THREAD

**Issue by joey2354** [WWBN/AVideo#2247]
hi, i would like to bann users but i dunno how sorry, what is the best fastest way to ban users on youphptube youtube clone thank you in admin panel

**Comment by DanielnetoDotCom** [comment]
Hi, 

The best way is using the User_Controll plugin (paid plugin)

You can ban, by the username also by the IP

To install this plugin, make sure you are using the latest version and you have the purchased this plugin

![image](https://user-images.githubusercontent.com/18009293/68593043-4c88b800-0473-11ea-9338-7fe08f6ad1da.png)
