### ISSUE TITLE
Youphptube install instructions do not cover these 2 questions

### ISSUE THREAD

**Issue by jimmyk1** [WWBN/AVideo#2248]
Two questions:
1: Can youphptube install on Centos 7 and 
2: can the streamer and encoder be installed when LAMP is already installed?

I searched for answer but cannot find.

Thanks

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/68608957-e90e8280-0492-11ea-9885-efc16f2f2fd7.png)

**Comment by jimmyk1** [comment]
Thanks...is there a way to install without installing apache and the other LAMP programs? I already have those running on centos

**Comment by DanielnetoDotCom** [comment]
You can install it on centos, we just do not provide support on it.

**Comment by JoshWho** [comment]
If you have LAMP which is Linux Apache MySql PHP  then you already have Apache.

You just have to copy to root docs into your www folder in your Apache directory.
