### ISSUE TITLE
Live Stream says offline

### ISSUE THREAD

**Issue by alexious** [WWBN/AVideo#2249]
Hello,

I created a new account as instructed by Daniel.  And  live streaming  still reads offline.

![4](https://user-images.githubusercontent.com/220803/68614835-bd3dcd80-048f-11ea-8234-d25f2acb253e.JPG)

**Comment by XemTube-TV** [comment]
Please follow this guide

![image](https://user-images.githubusercontent.com/50126312/68633733-8ca87300-0525-11ea-8602-2fab621f01e6.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I noticed a bug in the Live plugin, it has been fixed now and you will be able to see the full operation now
