### ISSUE TITLE
Bug - Gallery Theme won't display 5 columns Correctly

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2253]
In the ScreenColsLarge   when I try to set it to 5 it scatters everything.

4 and 6 work with no problem. Just 5 for some reason messes up.

**Comment by DanielnetoDotCom** [comment]
you should not use 5 columns, 

we use bootstrap, and it has 12 columns predefined.

if you want the video proportional, you can only use 1 or 2 or 3 or 4 or 6 or 12

any other value will have a weird space somewhere

**Comment by JoshWho** [comment]
I C.  Hmmmm Has to be a way to add some padding in between the videos a little more. I am just trying to stay with the times. If u have noticed the New Layout on YT everyone likes it. It is 4 columns but spaced out a little more. I like it to and have it implemented on my site but the videos seem to be too close together.
