### ISSUE TITLE
Verifed BAdge or verification system  on channel for my users 

### ISSUE THREAD

**Issue by BenjiHVG** [WWBN/AVideo#2255]
Where can I find the verified badge for my users or a chain verification system on youphptube

Thanks You

**Comment by DanielnetoDotCom** [comment]
Hi

check the customizeUsers plugin 

![image](https://user-images.githubusercontent.com/18009293/68781439-91008900-0616-11ea-9671-9bef49e30aba.png)

also the User manager

![image](https://user-images.githubusercontent.com/18009293/68781518-ad9cc100-0616-11ea-9e34-2cadc200ca7c.png)

The email verification mark is automatic

**Comment by BenjiHVG** [comment]
Thanks you dude
