### ISSUE TITLE
My dutch/belgium language translation (NL)

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#2258]
My dutch/belgium translation of US.php with a little translation tool to check the variables.

[nl.zip](https://github.com/YouPHPTube/YouPHPTube/files/3845210/nl.zip)

Some variables of US.php i didn't find and i appended it to nl.php to work properly (sometimes capital sensitive). The following $t in US.php was missing:

$t['Add an External a Live Streaming'] = "Voeg een Extern Live-Streaming toe";
$t['Add Article'] = "Artikel Toevoegen";
$t['Allow Download'] = "Downloaden toestaan";
$t['Allow download video'] = "Download videos toestaan";
$t['Authenticated users can view chart'] = "Geregistreerde gebruikers mogen statistiek zien";
$t['Basic Info'] = "Basis info";
$t['Can Download'] = "Mag Downloaden";
$t['Configure your Ads'] = "Configureer uw Ads";
$t['Contents'] = "Inhoud";
$t['Copy embed code'] = "Kopieer embed code";
$t['Create Campaign'] = "Campagne maken";
$t['Create Subscription Plans'] = "Abonnementsplannen maken";
$t['CSV File'] = "CSV bestand";
$t['Design'] = "Uiterlijk";
$t['Do you want to report this video? Sign in to make your opinion count.'] = "Wilt u iets over deze video melden? Log dan in want ook uw mening telt.";
$t['Edit Campaigns'] = "Campagnes wijzigen";
$t['Email All Users'] = "E-Mail alle Gebruikers";
$t['Enable Ads Plugin'] = "Ads Plugin Aanzetten";
$t['End on'] = "Stopt op";
$t['First Page Style'] = "Stijl eerste Pagina";
$t['General Settings'] = "Algemene Instellingen";
$t['Generate Sitemap'] = "Maak Sitemap aan";
$t['Live Stuff'] = "Live Instellingen";
$t['Miscellaneous'] = "Diverse";
$t['Monetize'] = "Betaalbeheer";
$t['Monetize User'] = "Betaalbeheer Gebruiker";
$t['My Menu'] = "Mijn Menu";
$t['New'] = "Nieuw";
$t['Pay User per Video View'] = "Betaal gebruiker per bekeken Video";
$t['Payments Settings'] = "Betaal Instellingen";
$t['Player Skin'] = "Uiterlijk Videospeler";
$t['Remember me'] = "Mij onthouden";
$t['Settings'] = "Instellingen";
$t['S3, B2, FTP settings'] = "S3, B2, FTP Instellingen";
$t['Sign In'] = "Inloggen";
$t['Sign in to subscribe to this channel'] = "Meld u zich aan om op dit kanaal te abonneren";
$t['Sign Out'] = "Uitloggen";
$t['Sign out'] = "Uitloggen";
$t['Site Advertisement with VAST Video ads'] = "Website Advertenties met VAST Video ads";
$t['Site Settings'] = "Website Instellingen";
$t['Social Login Settings'] = "Social Inlog Instellingen";
$t['Upload a File'] = "Bestand Uploaden";
$t['Want to subscribe to this channel?'] = "Wilt u zich op dit kanaal abonneren?";
$t['Warning'] = "Let op";

**Comment by DanielnetoDotCom** [comment]
Hi, I just add those lines into the nl.php file
