### ISSUE TITLE
Feature REQUEST: Infinite Scroll for the home page

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2261]
This is a must. Infinite Scroll will make it way easier for users to browse your video library.

**What does infinite Scroll do?**

Infinite Scroll is a JavaScript that automatically adds the next page while scrolling down saving users from having to click the next page and stops full page loads. 

You’ve likely seen it in use all over the web.

**Comment by maxlinux2000** [comment]
+1

**Comment by DanielnetoDotCom** [comment]
Hi

I know Infinite Scroll and I like it too.

I may be added in the future.
