### ISSUE TITLE
Maintenance Page twitter link has bug

### ISSUE THREAD

**Issue by alexious** [WWBN/AVideo#2262]
![8](https://user-images.githubusercontent.com/220803/68965059-e79dcc80-07a8-11ea-865d-a967844f2327.JPG)

**Comment by alexious** [comment]
I fixed on mine..

**Comment by DanielnetoDotCom** [comment]
Thanks for notice it.

I am just sending an update with that fix.

also, the update I sent the admin will be able to submit videos while is on maintenance mode
