### ISSUE TITLE
User in fo in admin comes up blank

### ISSUE THREAD

**Issue by alexious** [WWBN/AVideo#2263]
![userinfo](https://user-images.githubusercontent.com/220803/68982990-0e72f780-07d7-11ea-841d-6b7c7361bafc.JPG)

**Comment by DanielnetoDotCom** [comment]
It is blank because it must be  filled by the user (if the admin enable it)

![image](https://user-images.githubusercontent.com/18009293/68994263-ca780500-085f-11ea-9828-a986113e4186.png)

![image](https://user-images.githubusercontent.com/18009293/68994286-f8f5e000-085f-11ea-8f35-803ac89d5520.png)
