### ISSUE TITLE
I want to prevent uploaded files from being deleted

### ISSUE THREAD

**Issue by izumihiro** [WWBN/AVideo#2264]
次のうち、いずれかの設定にすることは可能でしょうか？

①アップロードされたファイルについて、管理者のみが削除や上書きして編集ができる。(アップロードしたユーザーは自分がアップロードしたファイルについて削除や上書きして編集はできない)

②アップロードしたユーザーは自分がアップロードしたファイルについて削除や上書きして編集はできる。ただし、彼らが削除したファイルや上書きして編集する前のファイルをサーバーに残しておく。

**Comment by DanielnetoDotCom** [comment]
Please translate it.

**Comment by izumihiro** [comment]
Is it possible to set one of the following settings?

① Only the administrator can edit the uploaded file by deleting or overwriting it. (The uploaded user cannot delete or overwrite the file that he / she uploaded)

② Uploaded users can edit the uploaded files by deleting or overwriting them. However, the files they deleted or the files before being overwritten are left on the server.

**Comment by DanielnetoDotCom** [comment]
this requires a lot of code, probably a new plugin to it.

If you are interested in a development quote, please contact us at developer@youphptube.com
