### ISSUE TITLE
can't auto load  video.js language

### ISSUE THREAD

**Issue by snowdream1985** [WWBN/AVideo#2269]
please add this code to view\include\footer.php(or other file) at first line

`<script src="<?php echo $global['webSiteRootURL']; ?>view/js/video.js/lang/<?php echo $_SESSION['language']; ?>.js" type="text/javascript"></script>`

example:html code:`<html lang="zh-CN">` it can auto load js/video.js/lang/zh-CN.js

the player can auto show Chinese

**Comment by DanielnetoDotCom** [comment]
Hi, try to add the js file here 

![image](https://user-images.githubusercontent.com/18009293/69057044-ef9b7d80-09ef-11ea-882d-02840084e89b.png)

some times the land will not match with the video.js file
