### ISSUE TITLE
External Storage

### ISSUE THREAD

**Issue by lunar54** [WWBN/AVideo#2271]
Is it possible to use NFS storage for external storage with YouPHPTube-Storage ?

**Comment by DanielnetoDotCom** [comment]
If you can install apache on it, I guess it will work

**Comment by guymass** [comment]
I also have an NFS issue!
I have setup NFS and moved the videos folder into it and created a symbolic link to that folder on the NFS named videos, however the site takes forever to load until it reaches a gateway timeout. Other means of accessing the NFS work really well, and my NFS server is a home connection with 3M upload speed, which I know is not much but should be enough to load the site I guess.

Permission are set properly, so I am not sure why this delay and slow liness once I use the NFS folder. What do you think should be the recommended upload speed to be able to serve the files in the videos folder?
