### ISSUE TITLE
"What user groups can view this video" setting doesn't work

### ISSUE THREAD

**Issue by Intermo101** [WWBN/AVideo#2274]
I uploaded a video and set it to a user group named test1. I logged into my test account which has the group test2 and that account could still see the video even though it wasn't in the matching user group.

**Comment by DanielnetoDotCom** [comment]
make sure your user is not an admin or the video owner.

can you please screenshot your videos manager and your users manager?

**Comment by Intermo101** [comment]
> make sure your user is not an admin or the video owner.
> 
> can you please screenshot your videos manager and your users manager?

Users
![image](https://user-images.githubusercontent.com/57767008/69154783-ec33ef00-0ae0-11ea-89b5-6d68baf01ff2.png)

User groups
![image](https://user-images.githubusercontent.com/57767008/69154724-d1617a80-0ae0-11ea-8eea-5475839220fd.png)

The video
![image](https://user-images.githubusercontent.com/57767008/69154811-fa820b00-0ae0-11ea-84ef-db6ad7b1998f.png)

**Comment by Intermo101** [comment]
Users
![image](https://user-images.githubusercontent.com/57767008/69154923-2ac9a980-0ae1-11ea-86b7-593e531a9998.png)
User groups
![image](https://user-images.githubusercontent.com/57767008/69154965-33ba7b00-0ae1-11ea-8df7-a2ea7f5be778.png)
The video
![image](https://user-images.githubusercontent.com/57767008/69154990-3f0da680-0ae1-11ea-8a57-3972a914510b.png)

**Comment by DanielnetoDotCom** [comment]
what user did upload the video?

check who is the video owner

**Comment by Intermo101** [comment]
> what user did upload the video?
> 
> check who is the video owner

The admin account uploaded the video. I uploaded the video

**Comment by DanielnetoDotCom** [comment]
sorry, I can not detect the error, can you reproduce it on demo site?

**Comment by Intermo101** [comment]
> sorry, I can not detect the error, can you reproduce it on demo site?

Cannot reproduce it on the demo site. I'll just do a reinstall
