### ISSUE TITLE
Subscribe user to group with API

### ISSUE THREAD

**Issue by Anitnelav** [WWBN/AVideo#2278]
Hi, 
I have a little question regarding user subscription into groups.
Is it possible to subscribe a user to a group using the signUp call of the API plugin?

If is not possible there is another plugin (free or commercial) that extendes the API so to achieve this?

**Comment by DanielnetoDotCom** [comment]
I understand what do you mean, but sorry we haven't implemented it yet in the API or another plugin.

if you want you can hire us to create this feature, just email us at developer@youphptube.com
