### ISSUE TITLE
YouPHPTube Home page not opening in css format

### ISSUE THREAD

**Issue by abelbarr** [WWBN/AVideo#2286]
![1](https://user-images.githubusercontent.com/56622710/69491078-3852ab00-0eb6-11ea-9c24-ca5795c003e1.jpg)
Please check the screenshot.
Let me know if the site can open directly on the IP address instead of the Folder name.
can I edit the Menu bar above the logo that says 
-YouPHPTube

**Comment by XemTube-TV** [comment]
I can help you install and configure YouPHPtube to work properly if you need my support. Just give me an SSH VPS ubuntu 16+ account I will set up the whole for you.

**Comment by DanielnetoDotCom** [comment]
@abelbarr can you please inspect your code to see the images URL?

from it, we may find the problem
