### ISSUE TITLE
Comments are indexing in Google

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2287]
We need a way to no-index the comment section of videos so it doesn't get pulled for description by bots. 

I noticed some video listings in Google and Yahoo show what people are commenting as a description.

**Comment by DanielnetoDotCom** [comment]
I am adding this option

![image](https://user-images.githubusercontent.com/18009293/69872904-8b9d7280-1295-11ea-9d2b-f8af0d838a3e.png)

and I follow these instructions 

https://perishablepress.com/tell-google-to-not-index-certain-parts-of-your-page/

but looks like it is only possible on google

**Comment by JoshWho** [comment]
Ok that will be awesome.

**Comment by JoshWho** [comment]
It has a bug. When I enable it, my right side display on desktop view stacks like I am viewing it in mobile.

If it is the GoogleIndex Off element it will not work in the search.

The best way to keep the comments from being seen by the robots is to include it using Java.

Google Bot will not be able to read it but everyone else still see's it like it was before.

**Comment by JoshWho** [comment]
I mean Include as the whole Comments section only gets added by java instead of PHP Inclusion.

**Comment by DanielnetoDotCom** [comment]
About the bug you mention, can I see a screenshot?

**Comment by JoshWho** [comment]
I just reproduced the same results on your demo site.

<img src="https://static.buddylist.co/x/rightsidegone.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
@JoshWho thanks for noticing it, the bug is fixed now

**Comment by JoshWho** [comment]
Good deal. DO I have to run the update for this to take place?

**Comment by DanielnetoDotCom** [comment]
just a git pull
