### ISSUE TITLE
Only Online/Offline in Livestream don't work

### ISSUE THREAD

**Issue by LightRO** [WWBN/AVideo#2288]
Hello, everyone,

I'm doing pretty well so far. The stream is running and I see it too, but it remains displayed offline. I have already thinned through the other contributions, but none of them brought a solution. I use completely SSL and also the certificates. As I said, everything else works even the livestream says that it is offline, although it is not so.

![fehler1](https://user-images.githubusercontent.com/19392688/69499987-9e135700-0ef7-11ea-97a0-f9ae7b858e04.png)

Many greetings,
LightRO

**Comment by XemTube-TV** [comment]
Please show me the Nginx configuration and parameter screenshot of your Live Plugin. I will check why you got the above error.

**Comment by LightRO** [comment]
Thats my Livestream NginX configuration (I have some links and ip changed here)


```
worker_processes  1;
error_log  logs/error.log debug;
events {
        worker_connections  1024;
}
rtmp {
        server {
                listen 1935;
                allow play all;
                #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                application live {
                        allow play all;
                        live on;
                        #record all;
                        #record_path /video_recordings;
                        #record_unique on;
                        hls on;
                        hls_nested on;
                        hls_path /HLS/live;
                        #hls_playlist_length 4s;
                        #hls_fragment 1s;
                        hls_fragment 10s;
                        on_publish http://phptube.meinesite.de/plugin/Live/on_publish.php;
                        on_play http://phptube.meinesite.de/plugin/Live/on_play.php;
                        on_record_done http://phptube.meinesite.de/plugin/Live/on_record_done.php;
                }
        }
}
http {
        include       mime.types;
        default_type  application/octet-stream;
        server {
                listen 81;
                server_name livestream.meinesite.de;
                #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                
		location /wss/ {
			proxy_pass http://meineip:8888;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}
		location /live {
                        # Disable cache
                        add_header 'Cache-Control' 'no-cache';

                        # CORS setup
                        add_header 'Access-Control-Allow-Origin' '*' always;
                        add_header 'Access-Control-Expose-Headers' 'Content-Length';

                        # allow CORS preflight requests
                        if ($request_method = 'OPTIONS') {
                                add_header 'Access-Control-Allow-Origin' '*';
                                add_header 'Access-Control-Max-Age' 1728000;
                                add_header 'Content-Type' 'text/plain charset=UTF-8';
                                add_header 'Content-Length' 0;
                                return 204;
                        }
                        types {
                                application/vnd.apple.mpegurl m3u8;
                        }
                        alias /HLS/live;
                }
                #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                location /stats {
                        stub_status;
                }
                location /stat {
                        rtmp_stat all;
                        rtmp_stat_stylesheet stat.xsl;
                }
                location /stat.xsl {
                        root html;
                }
                location /control {
                        rtmp_control all;
                }
                #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                location / {
                        root   html;
                        index  index.html index.htm;
                }  
	         listen 444 ssl; # managed by Certbot
	         ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
             ssl_ciphers HIGH:!aNULL:!MD5;
             ssl_prefer_server_ciphers on;
	     ssl_certificate             /opt/psa/var/certificates/scfKlNGmd;
	     ssl_certificate_key         /opt/psa/var/certificates/scfKlNGmd;
	     ssl_client_certificate      /opt/psa/var/certificates/scfulcwNE;

client_max_body_size 128m;

proxy_read_timeout 120;

	         
	         
              ssl		on;
             
  
               }
              
}
```

**Comment by XemTube-TV** [comment]
Please show me your screenshot of this Plugin parameter

![image](https://user-images.githubusercontent.com/50126312/69794307-99eb8000-11fc-11ea-87db-d2f8b07148b4.png)

**Comment by LightRO** [comment]
Here the Live Plugin config.

![liveplugin](https://user-images.githubusercontent.com/19392688/69797324-c341e700-11cf-11ea-99e0-fd34dbbab924.PNG)

**Comment by XemTube-TV** [comment]
Modify the Nginx configuration as follows:
Replace this line
``on_publish http://phptube.meinesite.de/plugin/Live/on_publish.php;
Into the line
`on_publish http://livestream.meinesite.de/plugin/Live/on_publish.php;`

and try checking again

**Comment by LightRO** [comment]
no its not working with this change.

**Comment by XemTube-TV** [comment]
What is your website link

**Comment by LightRO** [comment]
https://stream.redxnet.de is the Link to the Website.

**Comment by XemTube-TV** [comment]
I have now checked from your web link https://stream.redxnet.de. Perhaps your Nginx configuration and live plugin are not correct. Do you want me to check it all for you. If possible you can send me an SSH account and a webmaster I can set up the correct configuration for you.

**Comment by LightRO** [comment]
Sorry but we don't give our ssh account out. I don't think that the nginx config is not correct. All other is working without problems. I can streaming and when i click on the Play button i can see the stream. Only the Online and Offline check is not working correctly-

**Comment by DanielnetoDotCom** [comment]
Hi, what is your Nginx stats URL?

**Comment by LightRO** [comment]
Hello,
i have changed all to the subdomain stream.redxnet.de to check this but is the same problem here. The NginX Stats URL is:

https://stream.redxnet.de:444/stat

**Comment by DanielnetoDotCom** [comment]
you have no livestream there, so I could not check.

but I am pretty sure that is your error: https://github.com/YouPHPTube/YouPHPTube/issues/1914#issuecomment-516090913

**Comment by LightRO** [comment]
Yes thats is it but i dont now how can i fix it. My NginX Config is above.

**Comment by XemTube-TV** [comment]
If you can't fix it yourself, you can hire me to fix the bug to get it working for $ 5 if you want.

**Comment by DanielnetoDotCom** [comment]
@LightRO are you redirecting your Nginx somewhere? 

I mean, redirecting from http to https? or maybe using a CDN?

usually, this is the problem.

**Comment by LightRO** [comment]
@DanielnetoDotCom yes i use Nginx redirection from http to https.
Claudflare i use too but not for this domain actualy. 

I not known how can i change the redirection that its work by me because i have PLESK on my Server installed.

**Comment by DanielnetoDotCom** [comment]
Sorry, I am not sure how is your configuration and where is your redirect.

I can only say, for my self I redirect the sites on the virtual hosts

**Comment by LightRO** [comment]
you can find my configuration from NGinX above on my second post in this thread. Only i have changed the domain names.

**Comment by DanielnetoDotCom** [comment]
sometimes it can not be on your nginx.conf, there are multiple ways to redirect the page, I do not know them all.

BTW, for myself I only redirect the apache, I do not redirect nginx.
