### ISSUE TITLE
REQUEST: After Signup Redirect to a page that say to check your email

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2289]
When people signup it just takes them back to the login page and is why they get 2 notifications all the time because they sign in and it sends them a new email.

**Comment by DanielnetoDotCom** [comment]
The recovery code will have 10 minutes lifetime, will not change it

I hope it prevents the problem with duplicated emails until we fix the notifications

**Comment by JoshWho** [comment]
That will work. Not a bad fix actually.
