### ISSUE TITLE
YouPHPTube behind Apache Proxy

### ISSUE THREAD

**Issue by Cach2019** [WWBN/AVideo#2291]
Hi,
I have deployed  2 YouPHPTube Turnkeys OVAs on VMWAREs ESXi.
When asked about ip or domain under installation, I choose "xxxx.com", on one server and local ip on another one.
On the local ip VM, everything perfect no issue.
On the domain defined VM, I cannot reach the Website.
I have a hardware firewall for NATing ports, from the internet connection side to internal servers. There, ports 80 and 443 are routed to an Apache proxy server that handles domain requests, son I can host many domains on the same internet facing IP.
It worked always perfect while port 80 was the only port in use on diferent sites, but in YouPHPTube https/443 is used and I have had no luck routing to it.
Trying to Nat external 446 to internal 443, worked fine on a Owncloud server for example. But due YouPHPTubes config (I supose) it does not work doing that, not even pointing external 443 port to YouPHPTubes internal ip.
I presume that the proxy config will help but I am a bit lost there. 
I will apreciate any help.

Thanks in advance

**Comment by republicus** [comment]
I just answered a similar issue where I suggested using apache's mod_proxy

#2475

**Comment by SergejGrin** [comment]
Thank you for your help and support!
I don’t want to put YouPHPTube on one server with sites (this is very undesirable) for two reasons:
- The web server is backed up daily + 5 weekly copies - the total amount of backups is about 250 GB.
- From YouPHPTube there will be a big load on the web server and plus backup ... access to sites may be affected. Therefore, only the option with a separate independent server, but using an alternative port.
