### ISSUE TITLE
Customize quality HLS

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2292]
I need to optimize the quality of the HLS encoder ( the automatic one , when the command line it's empty , to detect the maximum resolution possible ) 
Is there anyway ? Because the quality of the encoder ''sucks'' if the videos got too much motion .
I need control over the bitrate and the preset ( medium - slow )

Thanks

**Comment by DanielnetoDotCom** [comment]
Right now, the auto resolution  is hardcoded

here is where we generate the code.
https://github.com/YouPHPTube/YouPHPTube-Encoder/blob/15fbd366a6c1547dfea8ca75e1e887f6931e638c/objects/Format.php#L232

If you have some ideas to improve it, we can change the main code
