### ISSUE TITLE
High-traffic YouPHPTube sites ????

### ISSUE THREAD

**Issue by jdr7181** [WWBN/AVideo#2294]
Has anyone used YouPHPTube for a high-traffic video sharing site, preferably using an encoder network with distributed storage? Any good URLs? 

I have tried to use YouPHPTube myself, and I like it a lot (which is why I keep coming back), but I have found it a bit unstable and unpredictable and its support somewhat lacking, probably because Daniel stays busy, which is a good sign.

**Comment by XemTube-TV** [comment]
You can refer to the scalability from here https://xemtube.tv

**Comment by JoshWho** [comment]
Be my guest and check out mine https://www.joshwhotv.com

**Comment by DanielnetoDotCom** [comment]
@JoshWho has a very good sample 

but what I can recommend to for start is to check your apache configuration...

https://github.com/YouPHPTube/YouPHPTube/wiki/Speed-up-your-page#tuning-your-apache-server

just with the default configuration and an apache tunning, I have sites handling over 1000 simultaneous users, but of course, I am talking about SSD drives and a large network over 1gbps at least.

**Comment by jdr7181** [comment]
Is Apache better than Nginx? I assumed Nginix is best for a video-sharing site.

**Comment by DanielnetoDotCom** [comment]
I will be honest, people say nginx is better, I use apache for myself, and I have no problem with it.

**Comment by JoshWho** [comment]
I never used Nginx as a webserver just because of the weird PHP configs you have to do to it to make it work correctly with most websites. WOuldn't be bad for static content and load-balancing reverse proxy

Lightspeed http is like an Nginx/Apache merge that might work for you but then again, this script uses nginx for the live streaming part so not sure if that would work to well.

**Comment by soapstreams** [comment]
@JoshWho 
Can you describe how you have it set up? How many encoders do you have? What are the specs of the server(s) you are using?

**Comment by soapstreams** [comment]
And what was your level expertise when you started? Did you already know PHP? Did you know how to setup servers.

**Comment by itdoka** [comment]
> Be my guest and check out mine https://www.joshwhotv.com

Hi, I really liked your site, and what does your support center work on? Thanks

**Comment by Wepwawetcode** [comment]
he uses osticket

**Comment by itdoka** [comment]
Thanks!  I'm sorry, I'm sorry, I have a couple more questions. How is the osticket embedded in the site? And how can the left menu be changed - add items?

**Comment by chinobaingo** [comment]
2 questions 

> I never used Nginx as a webserver just because of the weird PHP configs you have to do to it to make it work correctly with most websites. WOuldn't be bad for static content and load-balancing reverse proxy
> 
> Lightspeed http is like an Nginx/Apache merge that might work for you but then again, this script uses nginx for the live streaming part so not sure if that would work to well.

2 questions if I may:
1. How did you get the background image custom?
2. How did you get the front page to only load new videos upon scrolling?

You have a great layout!

**Comment by Wepwawetcode** [comment]
Customized code anyway we don't use this open source anymore since we find it too limited and it has several issues if you want to become big with it.

Verstuurd vanaf mijn iPhone
