### ISSUE TITLE
Issue with paid plugins.

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2295]
Hi there for some reasons the plugins which I bought dont work I don’t know why and I would like to get them to work,
Plug-ins:
Control users. (Doesn’t load when trying to ban a user)
Private videos. (doesn’t work for some reason)(our videos are located on blackblaze)

**Comment by DanielnetoDotCom** [comment]
I am really sorry for the delay...

Make sure you did install its tables

![image](https://user-images.githubusercontent.com/18009293/69875001-38c6b980-129b-11ea-95ee-312c88f006d4.png)

**Backblaze**

Make cure you uncheck this 

![image](https://user-images.githubusercontent.com/18009293/69875360-b4286b00-129b-11ea-877d-ea4745eb1888.png)
