### ISSUE TITLE
Video advertising does not show

### ISSUE THREAD

**Issue by LightRO** [WWBN/AVideo#2296]
Hello, everyone,

unfortunately the ad of the plugin Ad_Server does not work. Video is deposited for it. When I open the console I get the following error:

```
videojs.ima.js:1400 AdsLoader error: AdError 1005: There was a problem requesting ads from the server. Caused by: Error: 6
SdkImpl.onAdsLoaderError @ videojs.ima.js:1400
wh @ ima3.js:95
l.dispatchEvent @ ima3.js:93
cw.F @ ima3.js:437
wh @ ima3.js:95
l.dispatchEvent @ ima3.js:93
Zs.C @ ima3.js:320
th @ ima3.js:91
qh @ ima3.js:92
b @ ima3.js:89
747b35fd8caf18d9ce274ef4c4b2e85c.js?1574853478:144 VIDEOJS: adserror (Preroll)
```

Other error messages are not in the log of YouPHPTube

**Comment by DanielnetoDotCom** [comment]
Hi, I am not sure about this error, I have never seen before, can you please provide your video link here?

and also try to reproduce it on demo site

**Comment by LightRO** [comment]
I will check this on the demo page once and then give feedback.

The problem is that it does not load an ad even though the video was uploaded as described and added to the monetization. However, this promotional video does not appear in any of the other videos.

**Comment by DanielnetoDotCom** [comment]
Make sure you do not have an ad block
