### ISSUE TITLE
YouPHPTube Scalability.

### ISSUE THREAD

**Issue by gerryats** [WWBN/AVideo#2297]
Hi
I want to use YouPHPTube and my concern is how much scalable is this platform and can you provide any live link of its use.

Regarding plugins if I buy that do we get source code along with plugin my concern is  can we customize plugin or solve bugs ourself.

Thanks

**Comment by XemTube-TV** [comment]
You can refer to the scalability from here https://xemtube.tv

**Comment by walt93** [comment]
@XemTube-TV could you describe how you have the server setup for scaling, or point me to some more info?

**Comment by XemTube-TV** [comment]
You can use the YouPHPTube-Storage Plugin for unlimited replication. 
Details here
https://github.com/YouPHPTube/YouPHPTube-Storage

**Comment by gerryats** [comment]
If I buy plugin, will it be provided with source code and can I customize plugin myself?

**Comment by XemTube-TV** [comment]
You can customize the milk to your liking. But I recommend that you keep the original one

**Comment by DanielnetoDotCom** [comment]
@gerryats we sell the plugin source separately.

If you are interested, please email sales@youphptube.com

**Comment by gerryats** [comment]
@XemTube-TV It is important to know for me , can I customize plugins. If I buy plugin ,will I get source code of it.

**Comment by DanielnetoDotCom** [comment]
Hi, thanks, I have a fix for that, but I will only be able to upload it on the next release, I am working in a full rebrand now
