### ISSUE TITLE
Live streaming from https://xemtube.tv page auto-scales at 4-6fps

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#2300]
Mac OS X Mojave, Brave browser, streaming from https://www.joshwhotv.com/plugin/LiveLinks/view/Live.php?link=5

The screen is resizing +/- 8pixels at about 4-6hz. Left edge of the screen is stable, video shifts to the right/down and back. Right edge moves more than left, so its scaling.

It is making my brain ache.

I uploaded a movie of the glitch..

https://s3-us-west-1.amazonaws.com/veritas.1/YouPHPTube_glitch_on_brave.mov

**Comment by DanielnetoDotCom** [comment]
I have seen this before, I think it is something related to the HTML 5 render.

try to reduce a little bit the zoom, try to press ctrl/command+"-" (minus sign)
