### ISSUE TITLE
Backup Plugin Error, crontab not running

### ISSUE THREAD

**Issue by Powerbock** [WWBN/AVideo#2304]
I have installed the plugin, a manual backup of the data can be performed successfully. I also set the entry with "crontab -e", but obviously it doesn't work.

`0 1 * * * php /var/www/html/YouPHPTube/plugin/Backup/execBackup.json.php 5xxxxxxxxxxxxx`

Start this on cli:

```
php /var/www/html/YouPHPTube/plugin/Backup/execBackup.json.php 5xxxxxxxxxxx
PHP Notice:  Undefined index: backupType in /var/www/html/YouPHPTube/plugin/Backup/execBackup.json.php(14) : eval()'d code(1) : eval()'d code on line 54
PHP Notice:  Undefined index: backupType in /var/www/html/YouPHPTube/plugin/Backup/execBackup.json.php(14) : eval()'d code(1) : eval()'d code on line 54
PHP Notice:  Undefined index: backupType in /var/www/html/YouPHPTube/plugin/Backup/execBackup.json.php(14) : eval()'d code(1) : eval()'d code on line 58
PHP Notice:  Undefined index: backupType in /var/www/html/YouPHPTube/plugin/Backup/execBackup.json.php(14) : eval()'d code(1) : eval()'d code on line 58
PHP Notice:  Undefined index: backupType in /var/www/html/YouPHPTube/plugin/Backup/execBackup.json.php(14) : eval()'d code(1) : eval()'d code on line 67
Backup Done (): {"msg":"","error":true}
{"msg":"","error":true}
```

Ubuntu 18.04 LTS Server, PHP 7.2

What can I do, what's the mistake?

Thank you for this very nice Software

Kind Regards
Ronald

**Comment by DanielnetoDotCom** [comment]
try this 

`0 1 * * * php /var/www/html/YouPHPTube/plugin/Backup/execBackup.json.php 5xxxxxxxxxxxxx all`

as long as it is on crontab, it is expecting a second argument "all"

**Comment by Powerbock** [comment]
Thank you Daniel, it's works now.
