### ISSUE TITLE
REQUEST: Embedded Video Player Code for Player to work on Facebook

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2305]
This code will make it to when someone shares a video from your tube site on to Facebook, the user will be able to watch it on the Facebook platform like how to old Youtube format use to be.

You can use og:video for all content types. This section describes how to use additional tags to optimize the look of videos on Facebook. Facebook supports both mp4 and Flash videos.

Use a secure URL for both the og:video:url and og:video:secure_url tags to make your video eligible to play in-line in News Feed. Note that your video is not guaranteed to play in-line based on a variety of factors.

Here is the URL for the Dev docs on FB: https://developers.facebook.com/docs/sharing/webmasters#media

**Comment by JoshWho** [comment]
I remember CLipbucket has this option and would be kewl to see it here.

**Comment by DanielnetoDotCom** [comment]
I guess I found what I am doing wrong

the og:video I am posting a URL to play the video on your site, not the direct URL to the file.

If I add the direct URL to the file it will not work when you have the secure directory plugin enabled.

but anyway, I will add the direct file URL for the ones who have a more permissive video site.

**Comment by JoshWho** [comment]
That will be awesome. I am sure there is a way to do it with the secure directory as well. 

Like I always say with most videos sites that try to make it hard for people to download, "As long as the final output is compiled and un encrypted for the final view, it can always be reversed engineered."

Super kewl though, I think people will like this being able to play their videos directly on Facebook will get them more traction for shares.

**Comment by DanielnetoDotCom** [comment]
with the SecureVideosDirectory the video will only work while the token is valid.

after that, facebook will not be able to play the video file anymore

**Comment by JoshWho** [comment]
I C. WHat if it only grabbed the token opon playback. Not sure if that is a thing with them but I know it can be possible.

**Comment by DanielnetoDotCom** [comment]
it is only possible if they accept an embed code. NOT a direct file playback

**Comment by JoshWho** [comment]
I C

**Comment by JoshWho** [comment]
Looks like you have the Website url and not the Video url in the og:video meta.

og:video should be the direct playable video
