### ISSUE TITLE
HLS keeps giving me errors

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2307]
PHP Warning:  mysqli::query(): Couldn't fetch mysqli in /var/www/html/YouPHPTube-Encoder/objects/include_config.php on line 23
[29-Oct-2019 11:53:14 Europe/Berlin] PHP Warning:  mysqli::__construct(): (HY000/2002): No such file or directory in /var/www/html/YouPHPTube-Encoder/objects/include_config.php on line 14

**Comment by DanielnetoDotCom** [comment]
Hi, the HLS does not use database connection.

this should be something else.

**Comment by akhilleusuggo** [comment]
So what do I do ?

**Comment by DanielnetoDotCom** [comment]
You are getting an error here in the first query

https://github.com/YouPHPTube/YouPHPTube-Encoder/blob/15fbd366a6c1547dfea8ca75e1e887f6931e638c/objects/include_config.php#L23

I guess you are not connecting properly in the database, maybe wrong credentials

**Comment by akhilleusuggo** [comment]
I don't think so , because I have encoded like 27 videos and no problem . Is only the long videos that giving me this problem . For example when the server is encoding a video that I've streamed ( end with plugin were send to encoder )

**Comment by DanielnetoDotCom** [comment]
Check this https://stackoverflow.com/questions/20073168/my-database-user-exists-but-i-still-get-an-hy000-2002-no-such-file-or-direct/20074372

the first thing you have to make sure you are connecting, and this error must not appear
