### ISSUE TITLE
 Error 500 after updating and updating to version 8.0

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#2310]
After I updated to version 8.0, there was an error of 500 when playing the video. There was a problem with the home page, only an error occurred when opening the video.

![image](https://user-images.githubusercontent.com/50126312/70014102-5900bc00-15ac-11ea-843a-a6b83b88f44d.png)

![image](https://user-images.githubusercontent.com/50126312/70014134-7170d680-15ac-11ea-9541-0f9e7203914e.png)

**Comment by DanielnetoDotCom** [comment]
Important Information: We are updating our video system. It is important that your video system and plugins are up to date, everything must be updated after 2019-12-02. The new plugins will not work with the system before 8.0, so if you just got plugins and your installation is old, you must update your site.

If you have updated your site to version 8.0, your old plugins will not work, just download them again and you should be fine.

**Comment by TLCReuver** [comment]
Same problem here. So i have to update all plugins and github does the rest or i have to update by the clone_zip ?

**Comment by DanielnetoDotCom** [comment]
Hi, just update the premium plugins and you should be fine

**Comment by TLCReuver** [comment]
Th@nks, update successful.
