### ISSUE TITLE
Upload speed limited

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2313]
Hello:

The upload speed is limited for some reason. Is not a internet problem and not a hard drive limit or IO. Why ? I did several tests :

Server internet speed : 
```
Testing download speed................................................................................
Download: 763.78 Mbit/s
Testing upload speed......................................................................................................
Upload: 794.16 Mbit/s
```
Home internet speed 
![image](https://user-images.githubusercontent.com/52116577/70049036-d2180780-15dc-11ea-805b-7904453365ef.png)

Tests I've made to make sure is something wrong here : 

1)Uploading one single video : The speed is capped at around 40mb/s
2)Uploading 10 files : The speed went up to 350-430mb/s
3)My local Disk Drive is not the issue neither , since we can see that there's x10 more speed on the second test , and looking at the task manager , it's getting used 21% on the x10 files uploads 

No disk issues for sure , no IOps issues and not the bandwidth issues .

Anyone got any idea where the problem can come from ?

Thank you :)

**Comment by DanielnetoDotCom** [comment]
nice tests you have made, I am not sure what to setup to allow a larger bandwidth. maybe something on apache

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Can you test this on your server ? I've created a local server and i'm having the same issue .

**Comment by JoshWho** [comment]
Apache will not limit you and neither will Nginx. The only thing I can think of is either your Ethercard (Network Card eg eth0) might not be handling the packets correctly or just not fast enough to begin with.

Second thing would be a Hardware firewall on the isp node part of the hosting. 

It is one or the other.
