### ISSUE TITLE
Update trouble

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#2314]
I followed the git instructions to perform an update.  

sudo git pull
Getting a message: fatal: not a git repository (or any of the parent directories): .git

**Comment by DanielnetoDotCom** [comment]
Did you see this?

**Important Information: We are updating our video system. It is important that your video system and plugins are up to date, everything must be updated after 2019-12-02. The new plugins will not work with the system before 8.0, so if you just got plugins and your installation is old, you must update your site.
If you have updated your site to version 8.0, your old plugins will not work, just download them again and you should be fine.**

**Comment by heiress01** [comment]
Yes, I saw that and I was trying to update accordingly.  I followed the git instructions for updating the error is in relations to the update.  I'm new with this so, if I run into a problem it takes a long time to sort out.  I entered: sudo git pull
and get the message below:
 fatal: not a git repository (or any of the parent directories): .git

**Comment by DanielnetoDotCom** [comment]
I see, when you install it did you use "git clone"?

I guess you did not.

what you can do is to make a `git clone https://github.com/YouPHPTube/YouPHPTube.git` then rename this directory with the one you are using now. then copy your videos directory into this new directory

for example, lets say right now you have your installation in a dir called `/var/www/html/tv/` (tv)
when you execute the git pull you will have a directory called /var/www/html/YouPHPTube/

then you can rename the (tv) directory to `/var/www/html/tv_old` and then rename the `/var/www/html/YouPHPTube/` to `/var/www/html/tv/`

make sure you also copy the `/var/www/html/tv_old/videos` dir into the new `/var/www/html/tv/`

so after that, you will have the best way to follow the updates

**Comment by heiress01** [comment]
If I make these changes will I lose everything that I have done.  If so is there a way to avoid that?

**Comment by DanielnetoDotCom** [comment]
if you copy the videos directory you will not loose anything
