### ISSUE TITLE
Gallery - Big Video the Newest Video

### ISSUE THREAD

**Issue by gseiki** [WWBN/AVideo#2316]
I just updated my site and big videos are now random instead of being the newest video.  I read through some of the old issues and noticed that Daniel said he may add the ability for the big video to be the newest video sometime in the future.  Any updates on that feature?  

My site is used by elementary school students to view school activities and announcements.  Some of the younger students get confused and think that the random big video is the newest announcement. 

For now, I'm manually selecting the newest videos to be the suggested big video.  However, I upload all of my videos via RTMP, and send recorded stream straight to encoder.  It would help me out a lot if I didn't have to manually select which videos are displayed as the big video, as my site is updated multiple times a day.

If there is a work around, please share.  By the way, YouPHPTube is a great product and I appreciate that it's available for free.

**Comment by DanielnetoDotCom** [comment]
what layout are you using? Gallery?

**Comment by gseiki** [comment]
Yes

**Comment by gseiki** [comment]
Daniel, I have a more serious problem with my server.  Live stream no longer works reliably or records after update.  I backed up my server before updating, and just restored my server from backup to get streaming to work again.  Do you have any idea why updating would have broke the streaming functionality?  I after I did my update, I made sure to **_chmod 777 /tmp_** and restart nginx.

**Comment by DanielnetoDotCom** [comment]
please make sure you download the plugin again.

Important Information: We are updating our video system. It is important that your video system and plugins are up to date, everything must be updated after 2019-12-02. The new plugins will not work with the system before 8.0, so if you just got plugins and your installation is old, you must update your site.
If you have updated your site to version 8.0, your old plugins will not work, just download them again and you should be fine.

**Comment by gseiki** [comment]
Daniel, I have a couple of problems with the plugin page.  Chrome, Firefox, and Safari won't let me view the plugin page.  It says it's a security risk.  Any ideas on how I can fix this?

**Comment by DanielnetoDotCom** [comment]
can you please screenshot the message?
