### ISSUE TITLE
Bug: forceLoginToBeTheEmail does not work with existing users

### ISSUE THREAD

**Issue by republicus** [WWBN/AVideo#2319]
I thought I corrupted my database during a transfer of my setup onto a new server. But new accounts can be created without any problem.

It appears all old accounts that were created prior to requiring email authentication can no longer log in.

I verified this with a fresh install and my admin account cannot log in even with the email associated to the admin account. Unfortunately, I did not create any new users so I'm stuck blowing away that install and setting it up again.

I tried navigating the DB of my old setup to disable requiring email authentication but I had no joy locating the table/column. I hope I can still use my existing setup.

After that I'm not sure why accounts with email addresses will not authenticate if they were created prior to requiring the email authentication.. 

any thoughts?

**Comment by DanielnetoDotCom** [comment]
Hi

did you try to reset your password with SSH?

https://github.com/YouPHPTube/YouPHPTube/wiki/Reset-a-Password#how-to-reset-a-password-with-ssh

**Comment by republicus** [comment]
Yes I tried that several times with no joy. I also saw the same results on the avideo demo where the admin account would not log in with the developer email after setting **forceLoginToBeTheEmail** in CustomizeUser plugin.

**Comment by DanielnetoDotCom** [comment]
to reset the plugins configuration you can truncate the plugins table, so all will be reset.
