### ISSUE TITLE
AD Overlay ad plugin does not work

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#2323]
Currently the AD Overlay Plugin does not work. I have tried many ad codes that do not display ads on the player. The same ad code in other locations still displays normally.

**Comment by DanielnetoDotCom** [comment]
what do you mean does not work?

can you paste here a sample code of what do you mean?

there is any js error?

**Comment by DanielnetoDotCom** [comment]
BTW we are working on this plugin to release some improvements

**Comment by XemTube-TV** [comment]
Advertising no display. I have tried the code on the demo.YouPHPTube page. The status of not displaying ads also occurs on this Plugin

**Comment by DanielnetoDotCom** [comment]
Hi, The AD Overlay was under development, we just add new features check here https://github.com/YouPHPTube/YouPHPTube/wiki/AD_Overlay-Plugin

if you already install the AD Overlay tables, I recommend you to update your code, drop the AD Overlay  table and install it again

**Comment by XemTube-TV** [comment]
how to remove the AD Overlay panel and reinstall it. Can you guide me please.

Because I tried updating again but it still doesn't work.

**Comment by XemTube-TV** [comment]
I tried attaching the ad code on demo.Youphptube.com page. I see it also does not work.

**Comment by DanielnetoDotCom** [comment]
what is the code you tried?

**Comment by XemTube-TV** [comment]
The code I tested on demo.YouPHPTube does not work in Plugin AD_Overlay. But In another position it still works


`
<div id="M442744ScriptRootC742866">
        <div id="M442744PreloadC742866">
        Loading...    </div>
    </div>
<script>
        (function () {
        var script = document.createElement('script');
        script.src = "//jsc.mgid.com/d/e/demo.youphptube.com.742866.js?t=" +  ((d = new Date()) ? '' + d.getUTCFullYear() + d.getUTCMonth() + d.getUTCDate() + d.getUTCHours() : '');
        script.async = true;
        document.body.appendChild(script);
    })();
</script>
`


![image](https://user-images.githubusercontent.com/50126312/70496701-1e19fd80-1b43-11ea-9d05-02012793d8f0.png)

**Comment by DanielnetoDotCom** [comment]
Hi

the problem on the demo site was because I had a wrong/old table for this plugin.

I dropped the table and install it again `drop table ad_overlay_codes;`

Now it works

![image](https://user-images.githubusercontent.com/18009293/70519010-067a4f00-1b1a-11ea-9100-6f24c127ce9f.png)

but looks like your script does nothing
