### ISSUE TITLE
Banner Images are duplicated 

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2332]
I have set the banner images however they ar all over the website. Is there a way to fix the banner images. Also leaderBoardTop2 banner seems to not appear. I have tried jpeg and png both don't seem to work. 
![issue](https://user-images.githubusercontent.com/58635493/70381054-158eb080-1912-11ea-95e5-69602a45d995.JPG)

**Comment by DanielnetoDotCom** [comment]
Hi, 

the leaderBoardTop2 does not appear in the YouTube layout yet, but it will 

leaderBoardMiddle will appear in each row

I also recommend you to not use static images and use dynamic content from ads providers like adsense

**Comment by venwebsites** [comment]
How do I code the dynamic ads

**Comment by DanielnetoDotCom** [comment]
you do not code it, ad providers companies will give you the code

**Comment by DanielnetoDotCom** [comment]
You should try Google adsense
