### ISSUE TITLE
how to hide videos count

### ISSUE THREAD

**Issue by gujarraju** [WWBN/AVideo#2333]
Dear Mr. Daniel,

I want hide video count please help me.
![YouPHPTube v](https://user-images.githubusercontent.com/35865505/70389550-4d612b00-19da-11ea-8eb9-b7b5ec700bd1.jpg)

**Comment by XemTube-TV** [comment]
Turn it off here

![image](https://user-images.githubusercontent.com/50126312/70389756-37616380-19f6-11ea-93d1-dbd1ab8bda52.png)

**Comment by gujarraju** [comment]
Hi,
Thank you

I found its here.

![count](https://user-images.githubusercontent.com/35865505/70389968-bd25e480-19df-11ea-995c-2c5c3f3c084d.jpg)
