### ISSUE TITLE
Subscriptions and Paypal modules problems

### ISSUE THREAD

**Issue by gymia-demux** [WWBN/AVideo#2335]
Good morning! I'm writing for some problems on plugins purchased. In this case, we've problems on subscriptions and Paypal linked module. Screen remains locked on Progress bar and not link the user on Paypal to pay subscription. We've setup our Paypal App (id and secret pass obtained on developers.paypal.com) but now not works well. I wait your answer. Thank you so much
![Schermata 2019-12-09 alle 13 41 05](https://user-images.githubusercontent.com/28670683/70436446-97edb080-1a89-11ea-85d4-05f119cdab7e.png)

**Comment by DanielnetoDotCom** [comment]
Please provide your streamer log file.

**Comment by MrWeb** [comment]
We are having the same Issue. That problem is coming from `/plugin/YPTWallet/plugins/YPTWalletPayPal/requestSubscription.json.php` and the log says the following:

````
[05-Mar-2020 12:13:44 UTC] getSubscription: null - [904,1,true,"a"] - SELECT * FROM  subscriptions WHERE users_id=? AND subscriptions_plans_id=?  AND good_until > now()   AND status = 'a'
```

Is looking for a subscription and goes into error because it cannot find one from what I undestand, but that is my point, I want to CREATE a subscription.

How do we fix this? I can send a PR but I don't know the system that well

**Comment by DanielnetoDotCom** [comment]
Hi

did you install the plugins table?
![image](https://user-images.githubusercontent.com/18009293/76021114-6dce5200-5f03-11ea-8ea4-9bd91942cc0d.png)


did you create subscription plans?
![image](https://user-images.githubusercontent.com/18009293/76021174-89395d00-5f03-11ea-9ea0-90fcda9e116b.png)

**Comment by MrWeb** [comment]
> Hi
> 
> did you install the plugins table?
> ![image](https://user-images.githubusercontent.com/18009293/76021114-6dce5200-5f03-11ea-8ea4-9bd91942cc0d.png)
> 
> did you create subscription plans?
> ![image](https://user-images.githubusercontent.com/18009293/76021174-89395d00-5f03-11ea-9ea0-90fcda9e116b.png)

Yes we did, and to make sure I "re-installed" them but I have the same error.
And we do have a plan:

https://ibb.co/JmZNRKw

**Comment by DanielnetoDotCom** [comment]
Please provide a more complete log.

so we can find a clue of what is going on.

**Comment by MrWeb** [comment]
Ok this is the more complete log:

```
[05-Mar-2020 20:10:12 UTC] Warning: The plugin [PlayLists::getNetflixActionButton] takes 0.0576 seconds to complete. 
[05-Mar-2020 20:10:12 UTC] /home/uekjimos/public_html/virtualgym_jillcooper_it/app/v2/view/index.php
[05-Mar-2020 20:10:16 UTC] Start Login Request
[05-Mar-2020 20:10:16 UTC] redirectUri: 
[05-Mar-2020 20:10:16 UTC] sane redirectUri: https://now.jillcooper.it/app/v2/
[05-Mar-2020 20:10:16 UTC] user::login: noPass = , encodedPass = , this->user, admin 93.34.127.214
[05-Mar-2020 20:10:16 UTC] encryptPasswordVerify: encrypt
[05-Mar-2020 20:10:16 UTC] user::login: Do login without cookie
[05-Mar-2020 20:17:02 UTC] Start Login Request
[05-Mar-2020 20:17:02 UTC] redirectUri: 
[05-Mar-2020 20:17:02 UTC] sane redirectUri: https://now.jillcooper.it/app/v2/
[05-Mar-2020 20:17:02 UTC] user::login: noPass = , encodedPass = , this->user, mrwe 93.34.127.214
[05-Mar-2020 20:17:02 UTC] Password check new hash user not found
[05-Mar-2020 20:17:10 UTC] Start Login Request
[05-Mar-2020 20:17:10 UTC] redirectUri: 
[05-Mar-2020 20:17:10 UTC] sane redirectUri: https://now.jillcooper.it/app/v2/
[05-Mar-2020 20:17:10 UTC] user::login: noPass = , encodedPass = , this->user, mrweb 93.34.127.214
[05-Mar-2020 20:17:10 UTC] encryptPasswordVerify: encrypt
[05-Mar-2020 20:17:10 UTC] user::login: Do login without cookie
[05-Mar-2020 20:17:24 UTC] getSubscription: null - [904,1,true,"a"] - SELECT * FROM  subscriptions WHERE users_id=? AND subscriptions_plans_id=?  AND good_until > now()   AND status = 'a' 
[05-Mar-2020 20:17:29 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getDataObject() on boolean in /home/uekjimos/public_html/virtualgym_jillcooper_it/app/v2/plugin/YPTWallet/plugins/YPTWalletPayPal/requestSubscription.json.php:13
Stack trace:
#0 {main}
  thrown in /home/uekjimos/public_html/virtualgym_jillcooper_it/app/v2/plugin/YPTWallet/plugins/YPTWalletPayPal/requestSubscription.json.php on line 13
```

**Comment by DanielnetoDotCom** [comment]
Is your streamer up to date?

I can see a fatal error in your log file. This is probably the reason

**Comment by MrWeb** [comment]
> Is your streamer up to date?
> 
> I can see a fatal error in your log file. This is probably the reason

Ok, do you mean the the whole YouPHPTubeSystem to last version?

**Comment by DanielnetoDotCom** [comment]
Yes, make sure you are running the latest version v8.5

**Comment by MrWeb** [comment]
I'm trying to figure out where the version is. How do I find my current version?

**Comment by DanielnetoDotCom** [comment]
Find your version here 

![image](https://user-images.githubusercontent.com/18009293/76080746-5e441d00-5f86-11ea-9834-4958e8aabf59.png)

**Comment by MrWeb** [comment]
Hi, I had version 7.5, we did the update to 7.6 the, 7.7, 7.8, 8.0, 8.1 and we are currently at 8.2, what an update!

Now, when visiting the page: `mysite.com/plugin/Subscription/showPlans.php`

After seeing the plan I want i Press "Pay with Paypal" and I have the same exact problem but this time the ajax request spits out an error (an I don't have to go chase it in the log) saying:

```
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getDataObject() on boolean in /public_html/demos/ypt/plugin/YPTWallet/plugins/YPTWalletPayPal/requestSubscription.json.php:13
Stack trace:
#0 {main}
  thrown in <b>/public_html/demos/ypt/plugin/YPTWallet/plugins/YPTWalletPayPal/requestSubscription.json.php</b> on line <b>13</b><br />
```

**Comment by DanielnetoDotCom** [comment]
I just look into the code and I guess you do not have the plugin YPTWallet enabled.

please enable it and you should be fine.

I think is better if you go to version 8.5

**Comment by MrWeb** [comment]
Ok, I updated to latest (8.5) the plugin now sends me to the paypal page (yeah!) but I have 2 issues there:

1. There is no possibility of enabling a sandbox account to test it. I tried checking in `plugin/Subscription` parameters as well as in `plugin/YPTWallet` parameters neither of those have a checkbox to enable sandbox (version 5.7 had it)

2. I tried with the live (non-sandbox) payment and once done it redirects me to the wrong site even if I set these parameters in `plugin/YPTWallet`:

- RedirectURL: https://futurelabs.it/demos/ypt/plugins/YPTWallet/plugins/YPTWalletPayPal/redirect_url.php
- CancelURL:
https://futurelabs.it/demos/ypt/plugins/YPTWallet/plugins/YPTWalletPayPal/cancel_url.php

I get redirected to `https://now.jillcooper.it/app/v2/plugin/YPTWallet/plugins/YPTWalletStripe/redirect_url.php?token=EC-XXXXXXXXX` (note plugins/YPTWallet**Stripe** instead of plugins/YPTWallet**PayPal**)

**Comment by DanielnetoDotCom** [comment]
1. the sandbox is on the PayPal Plugin

![image](https://user-images.githubusercontent.com/18009293/76340408-4fd56880-62da-11ea-828d-5112d3f43250.png)

2. I am not sure if the problem is because you are forcing to be logged. please disable this option and test again.

![image](https://user-images.githubusercontent.com/18009293/76340529-7dbaad00-62da-11ea-8399-8be87e37603c.png)

There is an extra S in the plugin directory. the correct value should be:

    RedirectURL: https://futurelabs.it/demos/ypt/**plugin/**YPTWallet/plugins/YPTWalletPayPal/redirect_url.php
    CancelURL:
    https://futurelabs.it/demos/ypt/plugins/YPTWallet/**plugin/**YPTWalletPayPal/cancel_url.php

**Comment by MrWeb** [comment]
Ok good, we are now left with 2 issues:

1. "premium" videos are visible even if the person does not have a subscription (Subscription plugin) active not even a created one (table subscriptions" empty)

2. Paypal sends me to `https://now.jillcooper.it/app/v2/plugin/YPTWallet/plugin/YPTWalletStripe/redirect_url.php` even if I set the YPTWallet plugin to this (JSON plugin object_data):

```
{
 "decimalPrecision": "2",
 "wallet_button_title": "My Wallet",
 "add_funds_text": "<h1>Adding money instantly from credit/debit card</h1>Add funds on your Account Balance, to support our videos",
 "add_funds_success_success": "<h1>Thank you,<br> Your funds has been added<h1>",
 "add_funds_success_cancel": "<h1>Ops,<br> You have cancel it<h1>",
 "add_funds_success_fail": "<h1>Sorry,<br> Your funds request has been fail<h1>",
 "transfer_funds_text": "<h1>Transfer money for other users</h1>Transfer funds from your account to another user account",
 "transfer_funds_success_success": "<h1>Thank you,<br> Your funds has been transfered<h1>",
 "transfer_funds_success_fail": "<h1>Sorry,<br> Your funds transfer request has been fail<h1>",
 "withdraw_funds_text": "<h1>Withdraw money from your</h1>Transfer funds from your account to your credit card or bank account",
 "withdraw_funds_success_success": "<h1>Thank you,<br> Your request was submited<h1>",
 "withdraw_funds_success_fail": "<h1>Sorry,<br> Your funds withdraw request has been fail<h1>",
 "currency": "EUR",
 "currency_symbol": "&euro;",
 "addFundsOptions": "[5,10,20,50]",
 "showWalletOnlyToAdmin": true,
 "CryptoWalletName": "Bitcoin Wallet Address",
 "enableAutomaticAddFundsPage": true,
 "enableManualAddFundsPage": false,
 "manualAddFundsMenuTitle": "Add Funds/Deposit",
 "manualAddFundsPageButton": "Notify Deposit Made",
 "manualAddFundsNotifyEmail": "yourEmail@yourDomain.com",
 "manualAddFundsTransferFromUserId": false,
 "enableManualWithdrawFundsPage": false,
 "withdrawFundsOptions": "[5,10,20,50,100,1000]",
 "manualWithdrawFundsMenuTitle": "Withdraw Funds",
 "manualWithdrawFundsPageButton": "Request Withdraw",
 "manualWithdrawFundsNotifyEmail": "yourEmail@yourDomain.com",
 "manualWithdrawFundsminimum": "1",
 "manualWithdrawFundsmaximum": "100",
 "manualWithdrawFundsTransferToUserId": "1",
 "enablePlugin_YPTWalletBlockonomics": false,
 "enablePlugin_YPTWalletPayPal": true,
 "RedirectURL": "https://now.jillcooper.it/app/v2/plugin/YPTWallet/plugins/YPTWalletPayPal/redirect_url.php",
 "CancelURL": "https://now.jillcooper.it/app/v2/plugin/YPTWallet/plugins/YPTWalletPayPal/cancel_url.php",
 "enablePlugin_YPTWalletRazorPay": false,
 "enablePlugin_YPTWalletStripe": false
}
```

**Comment by DanielnetoDotCom** [comment]
Hi

1. is the video playable? or just appear on the first page?

2. this URL is wrong. try to remove the plan and recreate. maybe your plan has a wrong redirect URL on it. your URL should be this: https://now.jillcooper.it/app/v2/plugin/YPTWallet/plugins/YPTWalletPayPal/redirect_url.php

Sote you have a missing s and a wrong module (Stripe/PayPal), the correct URL should be YPTWallet/plugin**s**/YPTWallet**PayPal**/...

**Comment by MrWeb** [comment]
Ciao,
1. the video is playable and it plays fine. As you will see in this video the user does not have a paid plan and then in going in the premium videos the video plays fine:

https://streamable.com/ezsz5

2. I removed and recreated the plan and it worked!

**Comment by DanielnetoDotCom** [comment]
ok, make sure the video is on the same usegroup as your plan is

![image](https://user-images.githubusercontent.com/18009293/76625487-1b4df080-6516-11ea-9411-f36c8f847905.png)
![image](https://user-images.githubusercontent.com/18009293/76625549-40dafa00-6516-11ea-91d6-7f9abf6f6133.png)

**Comment by MrWeb** [comment]
Great! That worked!
