### ISSUE TITLE
Feature request : HLS transcoded files deletion after ending transcode 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2336]
Why the encoder does NOT clear the encoded files ?
This is happening only on the HLS transocoded files . On the normal MP4 it does deleted the trancoded files after sending them to the server . The HLS does keep them , and I need to delete them every times manually .

**Comment by DanielnetoDotCom** [comment]
you are right, sorry about that.

this new update should fix it.

**Comment by akhilleusuggo** [comment]
Thanks

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom This update has broke the Queue Log . Now I can't see anything that is happening on the encoder .  Basically the progress is empty

**Comment by DanielnetoDotCom** [comment]
I am so sorry, please make a git pull again, it should be fixed now
