### ISSUE TITLE
Top Menus plugin doesn't show menus created.

### ISSUE THREAD

**Issue by alexious** [WWBN/AVideo#2338]
Top Menus plugin doesn't show menus created.
https://www.avideo.com/plugin/TopMenu/page/editor.php#

I can't see test menus I created to delete them.

**Comment by DanielnetoDotCom** [comment]
I can see your menu

![image](https://user-images.githubusercontent.com/18009293/70482820-5b3faa80-1ac5-11ea-92a7-35ca3573f2b9.png)

**Comment by alexious** [comment]
Yeah, I figured it out.  A bit buggy though..



Best Regards,
Alexious Fiero
 
CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and proprietary information.  Any unauthorized review, use, disclosure or distribution is prohibited.  If you are not the intended recipient, immediately contact the sender by reply e-mail and destroy all copies of the original message. The contents of this email do not necessarily represent the views or policies of PeachWiz, Inc., or its employees. Please, consider the environment before printing this e-mail.


-----Original Message-----
