### ISSUE TITLE
SMTP Not working

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2340]
the smtp settings are not working I get an error message. please see attachment for your review
<img width="376" alt="email" src="https://user-images.githubusercontent.com/58635493/70476064-f031ac00-1aa3-11ea-8b88-394825250312.PNG">

**Comment by DanielnetoDotCom** [comment]
Make sure you follow this https://github.com/YouPHPTube/YouPHPTube/wiki/Setting-up-YouPHPTube-to-send-emails

**Comment by venwebsites** [comment]
I did, and still doesn't work. I tested the settings on outlook and that works. so there is something in the server that is blocking emails to be sent

**Comment by DanielnetoDotCom** [comment]
I think you did not switch the correct options 

![image](https://user-images.githubusercontent.com/18009293/70483502-5e3b9a80-1ac7-11ea-93c8-74ffd46617f1.png)

**Comment by venwebsites** [comment]
I did check that and I configured correctly

**Comment by DanielnetoDotCom** [comment]
The error you show above seems like you did not enable it.

but I changed it to tls and it works now

![image](https://user-images.githubusercontent.com/18009293/70485610-31d74c80-1ace-11ea-94c4-faa6e0e501b7.png)

**Comment by venwebsites** [comment]
Thank you. I did the same and didnt work for me. I opened another ticket on how to edit the email template.

**Comment by maxlinux2000** [comment]
Meanwhile the bug is resolved, you can do this from the terminal

`mcedit /etc/postfix/main.cf
`
modify or add:

> relayhost = [smtp.gmail.com]:587
> smtp_sasl_auth_enable = yes
> smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
> smtp_sasl_security_options = noanonymous
> smtp_tls_security_level = encrypt
> smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
> 

then create the passwd file

`mcedit /etc/postfix/sasl_passwd
`
and write in

> [smtp.gmail.com]:587 YourUserID@gmail.com:YourPassword


then :

```
chown root:root /etc/postfix/sasl_passwd
chmod 600 /etc/postfix/sasl_passwd
postmap /etc/postfix/sasl_passwd
sudo systemctl restart postfix
```


`echo "Test Postfix Gmail Relay" | mail -s "Postfix Gmail Relay" YourGmailAddress@gmail.com
`


I forgot ... also activate the option "Unsafe Apps" in your gmail account. It is possible that this is the real problem in your case
