### ISSUE TITLE
The categories in the add/edit/ of content and in the encoder do not display hierarchically.

### ISSUE THREAD

**Issue by alexious** [WWBN/AVideo#2341]
The categories in the add/edit/ of content and in the encoder do not display hierarchically.

Would be best if they displayed:

parent > sub > sub  

At the moment, they all display linearly.
![cats](https://user-images.githubusercontent.com/220803/70480948-10b33380-1aaf-11ea-9953-61b6d285e26d.JPG)

**Comment by DanielnetoDotCom** [comment]
I got a fix for that 

![image](https://user-images.githubusercontent.com/18009293/70854122-2d2be300-1e96-11ea-99f3-ebaada9e657c.png)

**Comment by alexious** [comment]
Coolness..
 
 
Best Regards,
Alexious Fiero
 
CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and proprietary information.  Any unauthorized review, use, disclosure or distribution is prohibited.  If you are not the intended recipient, immediately contact the sender by reply e-mail and destroy all copies of the original message. The contents of this email do not necessarily represent the views or policies of PeachWiz, Inc., or its employees. Please, consider the environment before printing this e-mail.


-----Original Message-----

**Comment by JSY-Ben** [comment]
Hi there

Unfortunately updating to the latest version has broken my categories, both in the encoder and the streamer. Categories and subcategories are not displaying as you've mentioned above, and in some cases categories with no parent are displaying the names of other categories. Example below:

<img width="609" alt="Screenshot 2019-12-16 at 2 31 38 pm" src="https://user-images.githubusercontent.com/13555701/70914938-de568880-2010-11ea-8858-91201de65a79.png">

<img width="1164" alt="Screenshot 2019-12-16 at 2 31 44 pm" src="https://user-images.githubusercontent.com/13555701/70914952-e0204c00-2010-11ea-824e-5c5269138c04.png">

**Comment by DanielnetoDotCom** [comment]
how did you update?

did you make a git pull?

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by alexious** [comment]
I didn't update..
 
I just got this email
 
Best Regards,
Alexious Fiero
 
CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and proprietary information.  Any unauthorized review, use, disclosure or distribution is prohibited.  If you are not the intended recipient, immediately contact the sender by reply e-mail and destroy all copies of the original message. The contents of this email do not necessarily represent the views or policies of PeachWiz, Inc., or its employees. Please, consider the environment before printing this e-mail.


-----Original Message-----

**Comment by JSY-Ben** [comment]
> how did you update?
> 
> did you make a git pull?
> 
> https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

Hi there

For security reasons at the place I worked I actually download the full zip file of the master and replace all files. I did the sequential database upgrades too on both encoder and streamer. :)

**Comment by DanielnetoDotCom** [comment]
That is why, yous site is not updated yet.

@alexious we will update it later

**Comment by SaliC-re** [comment]
@DanielnetoDotCom i can see the hierarchy while uploading but in the default theme it is not shown correctly in the left menu. The category repeats itself on some positions. You can see it on your demo site, too with the "kalin" and "ttt" example. Can you help out?

**Comment by DanielnetoDotCom** [comment]
Hi

I can not see your screenshot. can you please provide one?

**Comment by SaliC-re** [comment]
> Hi
> 
> I can not see your screenshot. can you please provide one?

https://pasteboard.co/J23IDzH.png

**Comment by DanielnetoDotCom** [comment]
Yes, you are correct.

I guess it fixes the problem
