### ISSUE TITLE
Changing Email Template and add SEO

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2345]
I read the admin manual and I don't see where you can change the email template to reflect my logo/website 

How do I add SEO to the front end and how can users add SEO tags to their videos

**Comment by DanielnetoDotCom** [comment]
You can add tags here 

![image](https://user-images.githubusercontent.com/18009293/70486580-289baf00-1ad1-11ea-9c51-05e1388c0a2a.png)

For security reasons your users can not add html tags, but they can add tags on videos if you enable the videoTags plugin.

when you enable do not forget to create the predefined tags types

![image](https://user-images.githubusercontent.com/18009293/70486954-69e08e80-1ad2-11ea-93ea-4d2ec263712b.png)


![image](https://user-images.githubusercontent.com/18009293/70486918-4ddced00-1ad2-11ea-9257-a532ea029c55.png)

Then the types will appear in your video edit page

![image](https://user-images.githubusercontent.com/18009293/70486904-3ef63a80-1ad2-11ea-9f20-8f085e23f5ba.png)

**Comment by venwebsites** [comment]
with YouTube and other platforms users can create their own tags. I would like to do the same . also I dont see an option for SEO Optomization

**Comment by DanielnetoDotCom** [comment]
the do can create, look the images above.

You just create the "tag type" what is basically a name like "keywords" or "recommended" it can be how many you want and whatever you want.
