### ISSUE TITLE
users adding paypal/merchant account

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2346]
How do I pay users for ads that run ads on their videos. YouTube uses adsense. How do users set up an account for monetization

**Comment by DanielnetoDotCom** [comment]
You can do this https://github.com/YouPHPTube/YouPHPTube/wiki/MonetizeUsers-Plugin

or you can let the users use their own adsense (or similar) code with AD_Overlay plugin https://github.com/YouPHPTube/YouPHPTube/wiki/AD_Overlay-Plugin#ad-overlay-per-user

**Comment by venwebsites** [comment]
The ads overlay plugin doesn't work very well I had to disable it

**Comment by venwebsites** [comment]
the ads overlay doesnt work for users. all that comes up is the word test in their menu.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot?

also, make sure you update your site to the latest

**Comment by venwebsites** [comment]
How do users cancel their account and purge videos off the platform. I been looking at the code and even tried adding a button but it doesn't seem to work

**Comment by DanielnetoDotCom** [comment]
Hi, 

what exactly are you trying to do?

**Comment by venwebsites** [comment]
Hi Daniel. I want to give the users the option to cancel their accounts, The users who have accounts I would like to have the ability for them to use multiple monetized accounts like adsense, paypal, etc.

**Comment by DanielnetoDotCom** [comment]
Ok, cancel the account we do not have this option yet.

monetize please check this https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform

**Comment by venwebsites** [comment]
ok do you know if that option is going to be available in the future

**Comment by DanielnetoDotCom** [comment]
Yes, we will add a better way to "remove" users

then show the inactive users in a different tab. also add an option to download the content is a good idea
