### ISSUE TITLE
Set SD as default resolution in the VideoResolutionSwitcher plugin

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo#2348]
I wish that I could configure the resolution that comes out by default, and then the user selects what he wants.

In my case I would like to have the SD (480p) as the default resolution, but another youphptube administrator might be interested in setting the HD as the default resolution.

Instead we now always have the Low resolution by default in the video list.

I think you could add a radio checkbox in the plugin configuration panel.
Here is an example of html5 code:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

Here a proposal to modify the interface
![VideoSwitcher](https://user-images.githubusercontent.com/5683921/70518834-4e5d9e00-1b3b-11ea-952c-e3c79e6f522d.png)

**Comment by jjacobs1** [comment]
I'm looking for the same. Its not worth having all our videos start on low. I noticed that the avideo demo page has an Auto option?

I may just uninstall the plug and reupload my videos as HD.

**Comment by akhilleusuggo** [comment]
@jjacobs1 the auto option is HLS
