### ISSUE TITLE
auto assign video on upload

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2350]
Hi,

I create a user category and user group on user creation,  i just wondered if there is a way to make all videos users upload go into their own categories and groups without having to manually select them?

i.e auto select disable "public media",  add video to user category and add default user group on upload and embed?

**Comment by DanielnetoDotCom** [comment]
Hi

the PredefinedCategory plugin may do the job

![image](https://user-images.githubusercontent.com/18009293/70533977-e8701700-1b38-11ea-9f44-1d392a901198.png)

**Comment by millzee01** [comment]
That works however it means manually doing this for every user which is a massive overhead.  Is there a way I can set this automatically per user?

**Comment by DanielnetoDotCom** [comment]
you have the site default option, check on the image above

**Comment by millzee01** [comment]
what i'm trying to achieve is to bypass the site default and use the user configured group and user category as their defaults.

i.e bob has a group called "bobs videos" and "bobs category", then sue has "sues group" and "sues category" etc etc

Suspect i'll need to look at hacking php to do this.

**Comment by DanielnetoDotCom** [comment]
I can not see why the plugin above does not work for what you need

**Comment by millzee01** [comment]
The plugin lets me assign a group and a category to a user however this has to be manually done by the admin.

What i'm trying to achieve is to set the logged in user default group to their own group, and set their default category automatically.

As an example of what I am trying to do:
If you look at your screenshot above,  on my environment your user "hillsong" will have a group called "hillsong" and a category called "hillsong".  And when they upload a video the video needs to be automatically placed into the hillsong group and hillsong category.  This means only the "hillsong" user will see the video.

If i can find what script creates the videos record then I can assign the user categories_id to the video and then create a new record in "videos_groups_view" with the user_id and user group_id uploading or embedding the video.

Does this make sense?

**Comment by DanielnetoDotCom** [comment]
Hi, yes it does make sense now

We do not have that way yet, but I guess it is possible to do.

You can code by yourself or you can hire us to do it for you

**Comment by millzee01** [comment]
yeah i figured it out thanks.
