### ISSUE TITLE
Cannot save settings

### ISSUE THREAD

**Issue by Bass850** [WWBN/AVideo#2351]
Hi,

While trying to save advanced site settings (in this case address for encoder site) the dialog is displayed that settings are saved. But on leaving settings page and returning settings are reversed to before. so we cannot change settings.

I checked other issues regarding this and checked error log. The Customize advanced and Customize user plugings are enabled. There is nothing logged in logfile in videos directory when this happens.

Please help.

Thanks in advance Bas

**Comment by DanielnetoDotCom** [comment]
please screenshot what screen are you using and share your log file here

**Comment by Bass850** [comment]
[log.txt](https://github.com/YouPHPTube/YouPHPTube/files/3945293/log.txt)
![Selection_012](https://user-images.githubusercontent.com/30600925/70537718-3862d400-1b61-11ea-9d9a-62bec86c51d7.png)

Here you are. I've cut last part of log file (as it was quite big). I made changes and sved and went back to page and nothing was added.

**Comment by DanielnetoDotCom** [comment]
Looks like you are running an old version, the newer version looks like this

![image](https://user-images.githubusercontent.com/18009293/70538202-78658f00-1b40-11ea-8c7f-f60a215bb328.png)

If you do not want to update try to change it direct from the configuration menu

![image](https://user-images.githubusercontent.com/18009293/70538317-a21eb600-1b40-11ea-9e15-1e2d2eb6310c.png)

**Comment by Bass850** [comment]
Thx for checking. I tried updating but pressing update version in side menu says version 7.1 your system is up to date. What am i doing wrong?

**Comment by Bass850** [comment]
![Selection_013](https://user-images.githubusercontent.com/30600925/70539271-be801a00-1b63-11ea-9b2a-280bc5938a97.png)

**Comment by Bass850** [comment]
nvm i found page how to update oher way to version 7.8

**Comment by Bass850** [comment]
I just did update to 8.0 as explained in this page: https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

Problem persists unfortunately. Log file youphplog.log in videos still shows nothing...

Any clues what might be going wrong?

![Selection_015](https://user-images.githubusercontent.com/30600925/70541804-0012c400-1b68-11ea-85e7-d41881402e9a.png)

**Comment by DanielnetoDotCom** [comment]
in version 8 the log is avideo.log now, NOT youphptube.log anymore

please share your log file

**Comment by Bass850** [comment]
Log file was supposed to be here (please disregard last post on other ticket. Don know what happened there.

[avideo.log](https://github.com/WWBN/AVideo/files/3949196/avideo.log)

**Comment by DanielnetoDotCom** [comment]
I can not see any error on this log file regarding the config save.

if there is no error I have no clue what it may be.

**Comment by Bass850** [comment]
I had the same issue. Is there maybe some way i can turn on extra debog logging or something?

**Comment by DanielnetoDotCom** [comment]
you have to manually debug, I really not sure.

last try ...

Inspect your code and watch your XHR request 

![image](https://user-images.githubusercontent.com/18009293/70638462-b08bd100-1c17-11ea-9d1b-283e9d808796.png)

**Comment by gregkeys** [comment]
I can't save any settings either, tried under Settings/General Settings nothing seems to persist

**Comment by baoang** [comment]
Debian 10 buster, Avideo 7.8 and 8.2, the same problem. I just don't want to display email, acct, etc info under the video, but no matter how to disable *donotidentifybyname/email, disablenativesignup, and etc* in general setting, all settings revert to default when refreshing the page.

**Comment by DanielnetoDotCom** [comment]
@baoang try to change it in the plugin menu, instead the Admin menu

![image](https://user-images.githubusercontent.com/18009293/72278158-2f5a9c00-3612-11ea-9a97-b27da711633e.png)

**Comment by baoang** [comment]
Thank you, @DanielnetoDotCom , finally addressed it!
