### ISSUE TITLE
Can't seem to add pages and place an icon on the menu bar

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2352]
I would like the feature to add pages on top the home screen. lease see screenshot as I highlighted what I am looking for
<img width="599" alt="adding_pages" src="https://user-images.githubusercontent.com/58635493/70542358-98905080-1b36-11ea-846a-c1e243e08185.PNG">

**Comment by DanielnetoDotCom** [comment]
You are looking for this https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-use-TopMenu-Plug-in

**Comment by venwebsites** [comment]
ok does it have a ticketing system for support as well

**Comment by venwebsites** [comment]
How do I delete a menu I created as a test

**Comment by DanielnetoDotCom** [comment]
It does not have a ticketing system

and you should see a delete button on the menu manager

![image](https://user-images.githubusercontent.com/18009293/70582540-94494f00-1b99-11ea-9b92-903c09aa91ed.png)
