### ISSUE TITLE
users cant skip ads

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2354]
When a user tried to skip ads a huge live chat menu is in the way of the skip ads button please see screenshot 
![overlay](https://user-images.githubusercontent.com/58635493/70546417-40a91800-1b3d-11ea-86d1-436ec168ef3f.jpg)

**Comment by DanielnetoDotCom** [comment]
try to change the height

![image](https://user-images.githubusercontent.com/18009293/70582617-d4103680-1b99-11ea-8f47-7ccc9e156e93.png)

**Comment by venwebsites** [comment]
what do you recommend I change it to

**Comment by venwebsites** [comment]
I don't think its the height its the with of the video

**Comment by DanielnetoDotCom** [comment]
try height = 80vh

**Comment by venwebsites** [comment]
I tried 80vh and still overlays

**Comment by DanielnetoDotCom** [comment]
then try 70vh then 60vh then ..., until you find the best size for you
