### ISSUE TITLE
Encoder doesnot transfer files

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2355]
[youphptube.log](https://github.com/WWBN/AVideo/files/3946597/youphptube.log)
this is my log file.

**Comment by DanielnetoDotCom** [comment]
Hi, make sure your encoder and streamers are up to date

the streamer is on version 8.0 now and encoder is on version 3

the log files are no longer called youphptube.log, they are called avideo.log now

**Comment by DanielnetoDotCom** [comment]
follow this to update https://github.com/WWBN/AVideo/wiki/How-to-Update-your-YouPHPTube

**Comment by Wepwawetcode** [comment]
That also counts for the encoding network and the encoders? If so I got my encoders straight of github are you be able to provide me to the new github?

Verstuurd vanaf mijn iPhone

**Comment by DanielnetoDotCom** [comment]
Yes, you must update encoder and encoder network also

If you just make a `git pull` command you should be fine 


All the projects are here https://github.com/WWBN
