### ISSUE TITLE
Adding Adsense Code

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2356]
How do you add the adsence code for google adsense

**Comment by venwebsites** [comment]
I have code from Adsense i need to know how to import it . Also would this be shared for monetization or its user specific

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/70582670-fb670380-1b99-11ea-925b-1011679f3ba4.png)

**Comment by venwebsites** [comment]
Maye I didn't say it correctly, AdSense needs to verify I am the site owner and they gave me these instructions 

Copy and paste this code in the HTML of your site, between the <head> and </head> tags.

Place the code on every page you want to show ads. After we’ve run some checks, your site will be ready to show ads.
Remember to go to Ads and choose the ad formats you want to show.
WordPress user? Learn how to insert code in your WordPress site.
URL of your site

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/70583620-096a5380-1b9d-11ea-98f1-c0fad0eca7f6.png)
