### ISSUE TITLE
 Please check the AD_Overlay Plugin as it does not work right on demo.YouPHPtube.com

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#2357]
Have you tried testing the AD_Overlay Plugin or dynamically on your demo.YouPHPTube page. I have tried it on my site and both on the demo.YouPHPTube.com page do not work. Details you can see Attached Photos.

![image](https://user-images.githubusercontent.com/50126312/70590685-08214100-1c06-11ea-94b9-ab56324584ba.png)

**Comment by DanielnetoDotCom** [comment]
It depends on what code are you using

adsense works great

would be easier if you share what code are you trying to do

**Comment by XemTube-TV** [comment]
This is the code I am using on the AD Overlay Plugin but it does not work.If put in other positions it still works normally

[ads.txt](https://github.com/WWBN/AVideo/files/3949912/ads.txt)

**Comment by DanielnetoDotCom** [comment]
I do not know what this script suppose to do, but I guess it is not a problem on AD Overlay

**Comment by XemTube-TV** [comment]
Because of this code, if I put it in a different position, it still displays normal ads. You can see the screenshot

![image](https://user-images.githubusercontent.com/50126312/70621980-789f8080-1c4d-11ea-846d-2d51efb2775d.png)

**Comment by DanielnetoDotCom** [comment]
This is an error in your JS

![image](https://user-images.githubusercontent.com/18009293/70637008-45d99600-1c15-11ea-83ff-49dc168aed16.png)
