### ISSUE TITLE
Error of not being able to log in to all accounts, Administrator accounts and member accounts cannot be logged in.

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#2359]
Error of not being able to log in to all accounts, Administrator accounts and member accounts cannot be logged in.

![image](https://user-images.githubusercontent.com/50126312/70625883-f5365d00-1c55-11ea-94fe-9419e73b1404.png)

**Comment by DanielnetoDotCom** [comment]
I can not see anything related to login errors in this log

**Comment by XemTube-TV** [comment]
Can you tell me where to check? I am not sure because I cannot log in to the account later. be logged in.

**Comment by DanielnetoDotCom** [comment]
tell you what?

I have no clue.

must be something in the log file otherwise may be something in your server or network

**Comment by DanielnetoDotCom** [comment]
what was that?
