### ISSUE TITLE
pages are not loading  login eventually very slow? 7.8 auto upgrade

### ISSUE THREAD

**Issue by k7n2g** [WWBN/AVideo#2363]
the site was fine auto-update to 7.8 site hangs forever, the main login bad, log in
[youphptube.log](https://github.com/WWBN/AVideo/files/3952134/youphptube.log)

 all gone to Encoder had to ad a new Encoder  but the main site not working accessing videos, etc  log file shows lots of  faults help, please guys

**Comment by DanielnetoDotCom** [comment]
are you talking about the ver 8.0?

the log file now is avideo.log, please share that

**Comment by k7n2g** [comment]
Hi Daniel  No this is a site auto-upgrade to V 7.8  can't find a log file avideo  in videos and logging in in is virtually impossible now just hangs cview.mobi

**Comment by DanielnetoDotCom** [comment]
the avideo.log is from version 8.0

your site loads here on my side and I could see it.

you are hosting your videos here as I can see http://www.wordupseo.com

Looks like you are having a hardware limitation, check for a bandwidth limit

also try to tune your apache https://github.com/WWBN/AVideo/wiki/Speed-up-your-page#tuning-your-apache-server

**Comment by k7n2g** [comment]
Thanks, Guys sorted

**Comment by DanielnetoDotCom** [comment]
how did yous love it?
