### ISSUE TITLE
Subscription showing on Home Page DOes not go away if you Unsubscribe from the channel

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2364]
When you subscribe to a channel it will appear on the homepage but when you unsubscribe it still stays on the homepage. 

Is there a way to just manually remove it from showing on the home screen when logged in?

Like Put a X on the ned of the Channel Row and it will just remove it from your home page.

**Comment by Wepwawetcode** [comment]
vouch

**Comment by DanielnetoDotCom** [comment]
Got it, the unsubscribe  bug is fixed, the X feature we may add in the future

**Comment by JoshWho** [comment]
Looks good now. I just ran a update and now all the un subs are gone from my home page. Thank you @DanielnetoDotCom
