### ISSUE TITLE
Admin Panel Not Saving Changes

### ISSUE THREAD

**Issue by piratesignal** [WWBN/AVideo#2371]
I can save changes everywhere so far except in the admin panel. 
It Hangs on processing
![hangs on processing change](https://user-images.githubusercontent.com/53704787/70714705-b4bafb80-1cb6-11ea-9aad-f11c2132609d.png)

**Comment by DanielnetoDotCom** [comment]
what version are you using?

can you reproduce it on demo site?

**Comment by piratesignal** [comment]
meh... already deleted the instance and wiped my whole aws because I had tinkered with it a bit too much. 
but it was 15.2 version i think?
it'd be nice if someone would offer up a complete turnkey aws hosted installation, i'd pay someone to do it

**Comment by DanielnetoDotCom** [comment]
We are not Turnkey

but we offer installation services in your instances https://www.youphptube.com/services

**Comment by allanmawerere** [comment]
you can save the changes through plugins 
CustomizeAdvanced (CustomizeAdvanced)
CustomizeUser (CustomizeUser)

**Comment by republicus** [comment]
I have always experienced this with all versions.

Unless I first enable the plugin CustomizeAdvanced or CustomeUser etc. first the changes would not take any changes from the Admin Panel > General Settings

Perhaps a "Show Advanced" option that would hide the settings on the Admin Panel > General Settings when not enabled. Once enabling "Show Advanced" it would enable the proper plugins CustomAdvanced, CustomUser etc and then allow. Or.. Those plugins should be enabled by default. Else these settings are worthless in my experience.

**Comment by allanmawerere** [comment]
let me see your website send me the link

**Comment by DanielnetoDotCom** [comment]
actually they are enabled by default. even if you do not enable it will be checked
