### ISSUE TITLE
Need a Turnkey AWS installation to run on EC2 including SSL  - How Much You Charge?

### ISSUE THREAD

**Issue by piratesignal** [WWBN/AVideo#2372]
and it would be nice if you already have one there up and running I can see

but, if you have a better cheaper place to host it that you are familiar with the installation I'm all ears
quoate here or send to my email freedomgone1984@gmail.com thanks

**Comment by piratesignal** [comment]
i see this here at your site 

Basic
Full Installation on your server$69.99

Would that be for AWS installation?

**Comment by DanielnetoDotCom** [comment]
Sure, no problem was is fine
