### ISSUE TITLE
Users are uploading videos but nothing is showing

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2373]
Users are having issues uploading videos and streamsing. Can we disable the embed link as I think thats causing issues.

**Comment by DanielnetoDotCom** [comment]
Try this

![image](https://user-images.githubusercontent.com/18009293/70731780-075fdc00-1ce6-11ea-82c5-74ebcf101daa.png)

**Comment by venwebsites** [comment]
I unchecked that however same issue. stuck on uploading. also users are having issues with doing live streams with OBS and third party streamers

**Comment by DanielnetoDotCom** [comment]
Please be clear about the issues you are having

**Comment by venwebsites** [comment]
issues are when they stream an error says cant connect. I tried under my account and the streams dont work. when a user uploads a video its stuck in encoding. They are uploading videos so it's not an empty video issue. also the videos are choppy. perhaps a linux firewall issue.

**Comment by venwebsites** [comment]
I need this issue fixed ASAP!! none of my users can stream including me

**Comment by DanielnetoDotCom** [comment]
Looks like you have a firewall and you closed the livestream ports

You will need ports 80, 8080, 443, 444 and 1935 to make the default installation

80 for apache HTTP
443 for apache HTTPS
8080 for nginx HTTP
444 for nginx HTTPS
1935 for RTMP connection

**Comment by venwebsites** [comment]
Those ports were opened. In addition I paid for the installation service. Can you go back in the server and make those ports permanently open. I already opened them back up but for some reason they closed again.

**Comment by DanielnetoDotCom** [comment]
I did not install any firewall or close any port

it is something in your network, there is nothing I can do

![image](https://user-images.githubusercontent.com/18009293/70801639-2ca82500-1d8e-11ea-9ff8-d1cd0c7eaf7c.png)

**Comment by venwebsites** [comment]
my firewalls and network have 80 8080 and 1935 open. it's the firewall in linux. Can you please assist

**Comment by DanielnetoDotCom** [comment]
Those ports are not enough 

Again, You will need ports 80, 8080, 443, 444 and 1935 to make the default installation

80 for apache HTTP
443 for apache HTTPS
8080 for nginx HTTP
444 for nginx HTTPS
1935 for RTMP connection

If you want to make sure completely disable your firewall and try

**Comment by venwebsites** [comment]
I disabled the firewall. can you see on your side if the ports are open

**Comment by DanielnetoDotCom** [comment]
No it is not working, but i can guarantee to you I did not install any firewall, the only way to have a firewall in the server is if somebody else enable it

**Comment by DanielnetoDotCom** [comment]
FYI port 8080 is working and port 8080 and 444 point to nginx

**Comment by venwebsites** [comment]
nobody installed a firewall. this is frustrating

**Comment by DanielnetoDotCom** [comment]
I am positive this is in your side.

Also check if you have a proxy or maybe a port forward

**Comment by venwebsites** [comment]
all I did was restart the server because I upgraded the RAM. this issue is critical. Ca. you please assist.  No firewall rules have changed. This was a fresh server as you requested for the install.

**Comment by DanielnetoDotCom** [comment]
Again, there is nothing I can do

The block is in your side, a server restart will not make any difference.

FYI the blocked ports are not standard ports , maybe that is why it is blocked

**Comment by DanielnetoDotCom** [comment]
Check here http://prostreams.live:8080

Nginx is running

**Comment by venwebsites** [comment]
my site is up but the issue is streaming and uploads. I can't even stream or upload either. no firewall is blocking connections . I really need assistance

**Comment by DanielnetoDotCom** [comment]
I am not on pc now, I can not check.

But upload should not be a port issue. What exactly error are you getting on the upload?

Maybe they are related.

Please provide screenshot and log file

**Comment by venwebsites** [comment]
Here is the screenshot for the streaming. Where do I find the log file
![rtmp issue](https://user-images.githubusercontent.com/58635493/70809920-cb358580-1d90-11ea-8ad6-53197f52ac3d.PNG)

**Comment by DanielnetoDotCom** [comment]
I am talking about the upload error you mention above NOT the livestream. 

We already know the live stream problem is the ports blocked . But upload should not be related to ports

**Comment by DanielnetoDotCom** [comment]
You can find the logs here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-YouPHPTube

**Comment by venwebsites** [comment]
right now I need the stream working. Nothing has changed on my side. i state again THIS IS CRITICAL Please assist

**Comment by DanielnetoDotCom** [comment]
We are in circles here

Do you have upload problem or not?

The problem on stream was found, the fix must be made in your side

**Comment by venwebsites** [comment]
THERE IS NOTHING TO FIX ON MY SIDE. FIREWALL IS DISABLED AND PORTS OPENED! SCREENSHOT
![firewall status](https://user-images.githubusercontent.com/58635493/70810989-c671d100-1d92-11ea-9640-2093fb73c34e.PNG)

**Comment by DanielnetoDotCom** [comment]
Look into your routers or anything . If you can not find the problem i suggest  you to use another server from another company.

I can not make anything else

**Comment by venwebsites** [comment]
Its a server issue. Nginx is not running please see screenshot
![nginx](https://user-images.githubusercontent.com/58635493/70811567-d6d67b80-1d93-11ea-8daf-ac5faea6828e.PNG)

**Comment by venwebsites** [comment]
I have other webservers running in my environment. I can assure you its not on my side

**Comment by DanielnetoDotCom** [comment]
Please check the link I provide you above http://prostreams.live:8080/ that is nginx also check the images I provide you above I could connect into port 444 using localhost so the nginx https port is running .  https://github.com/WWBN/AVideo/issues/2373#issuecomment-565430642

Again we are in circles

**Comment by DanielnetoDotCom** [comment]
Is your other server using port 444? 

Show me

**Comment by venwebsites** [comment]
We are not in circles. I am not sure if you understand. my ISP confirmed that Port 80, 8080, 443, 444, 1935 are open! My router also has the ports open! The Server firewall is disabled. None of my users can stream! You say the ports are blocked but they are open. All I did was boot down the server to install more RAM and rebooted and this issue is happening. I can Guarantee this is a configuration issue! Once this is resolved then we can address the video upload issue. Please assist

**Comment by DanielnetoDotCom** [comment]
Again, if you want to install again in another server OUTSIDE YOUR NETWORK , in a company that does not block ports ,I can assist you others wise I can not

**Comment by venwebsites** [comment]
Daniel,

   No ports are blocked! I am the hosting provider and I can assure you that ports are not blocked

**Comment by DanielnetoDotCom** [comment]
And yes we are in circles I keep answering you the same questions and giving you the same answers

**Comment by venwebsites** [comment]
Yes the server configuration!

**Comment by DanielnetoDotCom** [comment]
You have the server ssh access check the firewall

**Comment by venwebsites** [comment]
didnt you see the screenshot its inactive! all I am asking is for you to go back in the server and check the configuration you made. I guarantee
![firewall status](https://user-images.githubusercontent.com/58635493/70813179-13f03d00-1d97-11ea-9cea-618a44e917cb.PNG)
 when i rebooted the server your configuration changed

**Comment by DanielnetoDotCom** [comment]
I do not think a reboot can do this. it was blocked before the reboot .

**Comment by venwebsites** [comment]
Daniel, I am posting a public apology! The root of the problem was cloudflare proxied my servers IP blocking ports 1935! I have fixed the issue and able to stream again!! Thank you for your patience and help

**Comment by DanielnetoDotCom** [comment]
Thanks for the update. This issue may help others as well.

I did not know there are this option on Cloudflare

**Comment by venwebsites** [comment]
fixed that too! thanks for your help. I was frustrated because everything was open until i went into the cloudflare settings Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Daniel Neto <notifications@github.com> Date: 12/13/19  11:22 AM  (GMT-05:00) To: WWBN/AVideo <AVideo@noreply.github.com> Cc: venwebsites <designs@venwebsites.com>, State change <state_change@noreply.github.com> Subject: Re: [WWBN/AVideo] Users are uploading videos but nothing is showing (#2373) Also it may be also the upload problem
Check here https://github.com/WWBN/AVideo/wiki/About-Video-Upload#cloudflare

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/WWBN/AVideo/issues/2373?email_source=notifications\u0026email_token=AN7LJZLIWBJDCCUMRJRJEP3QYOZDJA5CNFSM4J2AKQF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEG2O2UA#issuecomment-565505360",
"url": "https://github.com/WWBN/AVideo/issues/2373?email_source=notifications\u0026email_token=AN7LJZLIWBJDCCUMRJRJEP3QYOZDJA5CNFSM4J2AKQF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEG2O2UA#issuecomment-565505360",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
