### ISSUE TITLE
default images overriding custom

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2375]
The Avideo logos keep appearing after I upload my custom logos. my logos stay for awhile but for some reason the avideo logo comes back

**Comment by DanielnetoDotCom** [comment]
I guess is your browser cache.

4 days ago I sent an update to prevent it to happen
https://github.com/WWBN/AVideo/commit/897ac7fdb3eea9f48cf985f6b7e0eb4f79fbfde9

Please update your code
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo

**Comment by venwebsites** [comment]
I followed those directions however 6 times today the avideo logo replaced my logo. I even deleted the logo out of the directory and still pulled and overwrote my logo. I can't keep changing logos everyday. Do you have any other suggestions

**Comment by DanielnetoDotCom** [comment]
it is your browser/network cache.

try in another PC/network you will probably see the correct image
