### ISSUE TITLE
Video encoding

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2377]
how to upscale the quality of the encoders to 1080 60 fps 10k bitrate

**Comment by DanielnetoDotCom** [comment]
Customise your FFMPEG commands

<img width="1238" alt="Screen Shot 2019-12-12 at 14 38 04" src="https://user-images.githubusercontent.com/18009293/70735512-29109180-1ced-11ea-9c2d-38125aa88f8c.png">

**Comment by Wepwawetcode** [comment]
but whats the command?

**Comment by DanielnetoDotCom** [comment]
is better you google for that, there are an infinity possibilities
