### ISSUE TITLE
Home Page error

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2378]
channels boxed still appear even after unsubscribing from channels

**Comment by DanielnetoDotCom** [comment]
please screenshot to explain better what you mean

**Comment by Wepwawetcode** [comment]
![A676EC11-C98D-4E81-AAD8-40035FA3442B](https://user-images.githubusercontent.com/28763945/70758396-2a6ca900-1d43-11ea-8d58-a05d789e5569.png)
![B08777D6-C803-45AC-8566-5E66E41DD8B3](https://user-images.githubusercontent.com/28763945/70758397-2a6ca900-1d43-11ea-931a-be192ce38f78.png)
![C5CBCD2C-4A87-48EC-9168-5C4EBE1AA86A](https://user-images.githubusercontent.com/28763945/70758398-2a6ca900-1d43-11ea-8722-6532cd84745e.png)

**Comment by DanielnetoDotCom** [comment]
still there even when you log off and log in again?

**Comment by Wepwawetcode** [comment]
I did it happens across all devices.

Verstuurd vanaf mijn iPhone

**Comment by DanielnetoDotCom** [comment]
Got it, here you go a fix

**Comment by Wepwawetcode** [comment]
ty
