### ISSUE TITLE
how to fix video size?

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2379]
https://xstreaming.vip/v/38
It looks really bad.

**Comment by DanielnetoDotCom** [comment]
this is not a video it is an audio file

**Comment by Wepwawetcode** [comment]
How do I deny audio upload?

Verstuurd vanaf mijn iPhone

**Comment by DanielnetoDotCom** [comment]
You can add or remove file types 

### For Streamer
Edit file: `/var/www/html/YouPHPTube/objects/include_config.php`
`$global['allowedExtension'] = array('gif', 'jpg', 'mp4', 'webm', 'mp3', 'ogg', 'zip');`


### For Encoder
File `/var/www/html/YouPHPTube/Encoder/videos/configuration.php`
`$global['allowed'] = array('mp4', 'avi', 'mov', 'mkv', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv', 'mpg', 'mpeg');`
