### ISSUE TITLE
Description panel

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2380]
![image](https://user-images.githubusercontent.com/28763945/70753386-ed99b580-1d34-11ea-83db-dd2dec5210e4.png)

how do I get rid of this images across the platform?
![image](https://user-images.githubusercontent.com/28763945/70753423-04400c80-1d35-11ea-9e90-ad4e4937f6b5.png)

**Comment by DanielnetoDotCom** [comment]
this is a poster image manually uploaded by the "Free" user

you are admin you can probably edit hos poster.

**Comment by Wepwawetcode** [comment]
I want to disable the function server wide.

Verstuurd vanaf mijn iPhone

**Comment by DanielnetoDotCom** [comment]
what functions users add posters on their medias?

this is not possible!
