### ISSUE TITLE
Upload to Cloudflare fails on all but Enterprise plans (413 Entity Too Large)

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#2383]
The suggested workaround is to use plupload to break uploads into chunks. See https://stackoverflow.com/questions/37749632/ddg#38696562. Need to send in chunks <100MB to make it work.

Note: The combination of Backblaze for storage at $5/TB/mo and using CloudFlare to pay $0/TB egress fee is really attractive.

**Comment by DanielnetoDotCom** [comment]
Encoder already works with chunks, but I can not do the same to send content to BackBlaze.

**Comment by walt93** [comment]
Ok, I'm sorry, I don't understand. I want to deploy using Backblaze for storage, but my test installation is failing because Cloudflare has a 100mb file transfer limit. That appears to be the issue that needs to be worked around. Did you see the article I referenced above?

You have a Backblaze plug-in, and you just said you can't send content to BackBlaze. 

I'm not decoding this properly, can you please help and clarify?

**Comment by DanielnetoDotCom** [comment]
I can not send content to Backblaze using chunks, Backblaze has it own API 

I really recommend you to disable Cloudflare proxy

**Comment by walt93** [comment]
Ok thank you. Do you have a recommended provider that either partners with Backblaze for their zero-egress fees model or can recommend something similar?

**Comment by DanielnetoDotCom** [comment]
you can use a CDN for your videos without upload problems

https://github.com/WWBN/AVideo/wiki/Using-CDN-for-Videos-Only

**Comment by walt93** [comment]
Thanks for the info! 🙏
