### ISSUE TITLE
disable youtube import encoder

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2384]
how do I disable youtube import on the encoders?

**Comment by DanielnetoDotCom** [comment]
Sorry we do not have this option yet

**Comment by Wepwawetcode** [comment]
anyway to remove the function completely? by removing the code?

Op vr 13 dec. 2019 om 22:50 schreef Daniel Neto <notifications@github.com>:

**Comment by DanielnetoDotCom** [comment]
If you know how to code you may be able to remove it directly from the code.

but change the core codes is not recommended. you will not be able to follow the updates anymore

**Comment by Wepwawetcode** [comment]
I know how to code I already changed a lot.

Verstuurd vanaf mijn iPhone

**Comment by DanielnetoDotCom** [comment]
ok, so you should be able to find out where to remove

**Comment by Wepwawetcode** [comment]
sure

Op zo 15 dec. 2019 om 19:35 schreef Daniel Neto <notifications@github.com>:
