### ISSUE TITLE
Livechat

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2385]
On refresh my livechat is empty even with livechat turned on and 25 messages history.

**Comment by DanielnetoDotCom** [comment]
Lovecraft require port 8888

What is also closed

**Comment by Wepwawetcode** [comment]
Port 8888 is enabled in the config. Its showing comments realtime but after a refresh the comments are gone

Verstuurd vanaf mijn iPhone

**Comment by DanielnetoDotCom** [comment]
I will review it when I get on pc

**Comment by Wepwawetcode** [comment]
now its automatically opening. without me clicking on it. and its still not saving messages

**Comment by DanielnetoDotCom** [comment]
please check the log files

**Comment by Wepwawetcode** [comment]
Already fixed it.

Verstuurd vanaf mijn iPhone
