### ISSUE TITLE
The noNavbar=1 variable 

### ISSUE THREAD

**Issue by alexious** [WWBN/AVideo#2386]
The noNavbar=1 variable works great when going to a channel, but when you click on a video to play the request goes away and NavBar comes up on play. 

https://avideo.com/channel/PeachWiz?noNavbar=1

It would be great if the request could be carried through all activities.  Request(QueryString) could be kept thought the user experience when coming from a link with noNavbar=1

The link below id hand coded for sample purpose.
https://avideo.com/video/peachwiz-email-archiving-demo?noNavbar=1

**Comment by alexious** [comment]
Or when coming with that request in the string you could create a session or cookie to keep the Nav Bar off until you click a button on top somewhere to kill the cookie or session to show nav bar again.

**Comment by DanielnetoDotCom** [comment]
Updated
