### ISSUE TITLE
Thumbnail error

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2389]
![image](https://user-images.githubusercontent.com/28763945/70842039-a89e7d80-1e1f-11ea-8bc9-f33e56e90672.png)

its public and rendered but it doesnot show the time.

**Comment by DanielnetoDotCom** [comment]
The one with EE:EE:EE you got an error somewhere and it is not recoverable.

try to submit the video again and check the logs

**Comment by Wepwawetcode** [comment]
Not even manual?

Verstuurd vanaf mijn iPhone

**Comment by DanielnetoDotCom** [comment]
if you manually overwrite the video you will not detect the problem

**Comment by Wepwawetcode** [comment]
So I can't edit the video files to add the time?

>

**Comment by DanielnetoDotCom** [comment]
you can edit in the database, but it is not a fix

**Comment by Wepwawetcode** [comment]
sure I will do that

Op zo 15 dec. 2019 om 21:20 schreef Daniel Neto <notifications@github.com>:
