### ISSUE TITLE
want to remove installation path

### ISSUE THREAD

**Issue by allanmawerere** [WWBN/AVideo#2391]
i have complete my Avideo site so i want remove http://35.192.163.105/YouPHPTube/
to http://35.192.163.105 any help please?

**Comment by akhilleusuggo** [comment]
you need Vhost or you should have installed it on /var/www/html/ ( not recommended )
Make some researches about Vhost ( virtual host )

**Comment by allanmawerere** [comment]
installed youphptube on ubuntu 16.04 LTS using google cloud as my host but after starting the apeach
it told me to remove this any help please

**Comment by akhilleusuggo** [comment]
you're not forced to remove it , you can leave it like it is . It's just a mater of security .
In case you wanna remove it :
`cd /var/www/html`
`ls`
Should show you files and directories
`rm -R NAME OF THE DIRECTORY `

gl

**Comment by XemTube-TV** [comment]
@allanmawerere 
I can set up the entire YouPHPTube for you if you need my help.

**Comment by allanmawerere** [comment]
@XemTube-TV  
i have done everything i just need help in changing the domain
for example YouPHPTube is running at http://35.192.163.105/YouPHPTube/
yet i want to it run on http://35.192.163.105 without the extension YouPHPTube

**Comment by XemTube-TV** [comment]
I need to access your server to do this. If you agree please send information via Email: XemTube.TV@Gmail.com
