### ISSUE TITLE
random links

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2392]
https://xstreaming.vip/v/31?channelName=ManyFlamesAway

when I click on a video on his channel for some reason his name appears behind it and it doesnot autoplay other videos is there anyway to fix that?

**Comment by DanielnetoDotCom** [comment]
This is something about your SSL 

![image](https://user-images.githubusercontent.com/18009293/70862053-c948ff00-1f15-11ea-94ff-90544cdeda28.png)

You may find a solution on google

**Comment by Wepwawetcode** [comment]
Already fixed it by clearing cache.

Verstuurd vanaf mijn iPhone

**Comment by Wepwawetcode** [comment]
what I mean is this, one sec

**Comment by Wepwawetcode** [comment]
[2019-12-15 22-33-02.zip](https://github.com/WWBN/AVideo/files/3965496/2019-12-15.22-33-02.zip)
I find it annoying that if you goto a channel and you click on a video that every video you see is filtered to that user.

**Comment by DanielnetoDotCom** [comment]
I am not sure what you mean.

can you please place screenshots? 

NOT a zip file?

**Comment by Wepwawetcode** [comment]
nevermind
