### ISSUE TITLE
google analytics

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2393]
![image](https://user-images.githubusercontent.com/28763945/70845251-7a836280-1e4c-11ea-9ae8-8cb4f6ba4806.png)
![image](https://user-images.githubusercontent.com/28763945/70845255-88d17e80-1e4c-11ea-96e6-60b0547bb6f4.png)
it doesnot seem to work for no reason.

**Comment by DanielnetoDotCom** [comment]
there is no reason to not work, check your JS console and inspect your code to make sure the google analytics code is there

**Comment by Wepwawetcode** [comment]
It does work just not realtime.

Verstuurd vanaf mijn iPhone

**Comment by DanielnetoDotCom** [comment]
I can see realtime in all sites I have, please check your side
