### ISSUE TITLE
Connect Error (1045) Access denied for user 'epiz_23132849_gft'@'192.168.2.184' (using password: YES)

### ISSUE THREAD

**Issue by GramingFoxTeam** [WWBN/AVideo#2394]
Hello,
i have  issue when installing.
![image](https://user-images.githubusercontent.com/29177546/70851170-01632a00-1ea3-11ea-985c-fa22ab4e3f3e.png)
How can i fix it?

**Comment by allanmawerere** [comment]
contact me at learningportal2@gmail.com

**Comment by GramingFoxTeam** [comment]
> contact me at [learningportal2@gmail.com](mailto:learningportal2@gmail.com)

İ already contacted you.Check email.

**Comment by allanmawerere** [comment]
instructions sent to your mail feel free to write me back

**Comment by GramingFoxTeam** [comment]
Closed.
