### ISSUE TITLE
caching error

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2395]
if you enable cache it doesnot update the homepage how do we fix that without disabling the cache plugin?

**Comment by DanielnetoDotCom** [comment]
that is how cache works

https://github.com/WWBN/AVideo/wiki/Speed-up-your-page#enable-cache-plugin

**Comment by Wepwawetcode** [comment]
Yes but I want the cache plugin to stop caching certain pages how do I disable that?

Verstuurd vanaf mijn iPhone

**Comment by DanielnetoDotCom** [comment]
I don't know if I can teach that, but if you want you can inspect the code and add this feature

**Comment by Wepwawetcode** [comment]
sure I will do that!

Op zo 15 dec. 2019 om 19:34 schreef Daniel Neto <notifications@github.com>:
