### ISSUE TITLE
Video Tags, Chat Window

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2396]
I'm not sure if you already explained. How can channel owners add tags to their videos for SEO. I Adjusted the chat window however users can't skip ads because the chat overlay gets behind it. Please see screen shot of Tags and Live chat window
![tags](https://user-images.githubusercontent.com/58635493/70851318-9d6c4180-1e61-11ea-9d77-6479b51835d3.png)
![screenshot_chat](https://user-images.githubusercontent.com/58635493/70851319-9d6c4180-1e61-11ea-9d9d-87a70876dd79.png)

**Comment by DanielnetoDotCom** [comment]
try this https://github.com/WWBN/AVideo/issues/2354
