### ISSUE TITLE
After changing the ip site disappeared description uploaded videos

### ISSUE THREAD

**Issue by ra3ggy** [WWBN/AVideo#2398]
The site runs on two different local networks without a DNS name. When accessing the site via ip_v4 address, everything is fine. When accessing a site from another network via ip_v6 address, it is impossible to view the description of this video in the video editor and there is no video description editor panel.
![Screenshot_20191215_001855](https://user-images.githubusercontent.com/58891658/70854781-9715ae00-1ed1-11ea-83af-52749fdd923a.png)

**Comment by ra3ggy** [comment]
![Screenshot_20191215_001855](https://user-images.githubusercontent.com/58891658/70854773-7a797600-1ed1-11ea-854a-142571487592.png)

**Comment by DanielnetoDotCom** [comment]
I have no idea why this , try to see the JS console for some clue

**Comment by ra3ggy** [comment]
![error2](https://user-images.githubusercontent.com/58891658/70887517-3bd9dd80-1fef-11ea-8691-8340a1d922ae.png)

**Comment by ra3ggy** [comment]
youphptube.js.log

[16-Dec-2019 07:02:37 UTC] [aEC] JS-Err: ReferenceError: videojs is not defined @ line 18 in file http://[2001:470:71:10a8:4677:29:4022:961e]/videos/cache/js/c309183ecb1a529ff9d5d5ed728aa36a.js?1576479753 at visit on /

**Comment by ra3ggy** [comment]
The same thing, only when logging in with ip_v4

![error3](https://user-images.githubusercontent.com/58891658/70889177-ffa87c00-1ff2-11ea-9199-1c319814ce89.png)

**Comment by ra3ggy** [comment]
IPv6 address has a colon ":"
The debugger writes: "Suspended on exception" SyntaxError: '* ,: x' is not a valid selector

![error5](https://user-images.githubusercontent.com/58891658/70892715-bceaa200-1ffa-11ea-9440-3fa026203722.png)

**Comment by DanielnetoDotCom** [comment]
does your IPV6 not suppose to be 2001:470:XXX:XXXX:XXXX:XXXX:XXXX:XXXX instead [2001:470:XXX:XXXX:XXXX:XXXX:XXXX:XXXX]

**Comment by ra3ggy** [comment]
my ip everywhere with brackets, in all figures and in the logs

**Comment by ra3ggy** [comment]
I found a temporary solution for ipv6:

![html1](https://user-images.githubusercontent.com/58891658/71113884-9b96db00-21df-11ea-947c-d993c51e1196.png)

Disabled HTML editor. This does not work with ipv6
