### ISSUE TITLE
Categories Do not appear if you are on the trending page!

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2400]
![image](https://user-images.githubusercontent.com/28763945/70857825-11f0c000-1ef6-11ea-84e5-0860f8b75504.png)
this is on the homepage
![image](https://user-images.githubusercontent.com/28763945/70857831-20d77280-1ef6-11ea-8435-732643144f71.png)
this is on the trending page, if you fix this please tell me where it problem is I made a replicate on your demo site
![image](https://user-images.githubusercontent.com/28763945/70857841-42d0f500-1ef6-11ea-956d-c3c7d1c5707d.png)
homepage
![image](https://user-images.githubusercontent.com/28763945/70857845-4cf2f380-1ef6-11ea-9555-74532975bc65.png)
trendingpage

**Comment by DanielnetoDotCom** [comment]
What exactly page are you looking at the demo site?

I went there and I could not reproduce

**Comment by Wepwawetcode** [comment]
There should be 5 categories appearing on your website but when you view your categories from the trending page it only shows 4 look closely at the screenshots

Verstuurd vanaf mijn iPhone

**Comment by DanielnetoDotCom** [comment]
I saw the screenshot and I could not reproduce it, I am not sure if it is a recently fix but I could not reproduce it 

I would like to check in the exact URL you mention

**Comment by Wepwawetcode** [comment]
you want me to reproduce it on your sites?

Op zo 15 dec. 2019 om 19:31 schreef Daniel Neto <notifications@github.com>:

**Comment by Wepwawetcode** [comment]
https://xstreaming.vip/trending?current=2

https://xstreaming.vip/trending

**Comment by Wepwawetcode** [comment]
https://demo.avideo.com/trending?current=2

https://demo.avideo.com/trending?current=1

https://demo.avideo.com/trending

**Comment by DanielnetoDotCom** [comment]
Thanks, bug confirmed and fixed

**Comment by Wepwawetcode** [comment]
how do I fix it? without doing a pull?

Op zo 15 dec. 2019 om 21:37 schreef Daniel Neto <notifications@github.com>:

**Comment by DanielnetoDotCom** [comment]
yes you will need to make a git pull
