### ISSUE TITLE
Ads overlay not working correctly on Mobile

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2402]
I am seeing full screen ads and no X to close it anywhere on mobile for some reason. 

Just watch a video from my seekingthetruth channel on mobile in vertical view and you will see what I am talking about.

**Comment by DanielnetoDotCom** [comment]
I went to watch a video in your site and I could notice that.

I am using a Firefox on Linux 

but I saw this happening in other sites due the adsence auto ads

can you please screenshot it?
