### ISSUE TITLE
Connection refused for streaming from mobile.

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#2403]
Hi Daniel,

I am getting a access denied when trying to stream from my mobile app. RTMP configuration is correct as I was able to stream from my home computer without any problems. Getting isConnected failed.

Another issue is trying to display videos in the video list page by category or any other type gives me an error window, just saying error. Could be nice to have few views as the video list is very long.

**Comment by DanielnetoDotCom** [comment]
Hi thanks for open this issue here 

Just to make clear , what mobile app are you using? Our demo app or another RTMP app?

About the display vídeo issue , please provide a screenshot of it . Right now I am not sure in what page are you.

Please next time create 2 separated posts for each issue

**Comment by guymass** [comment]
OK I will. Regarding the rtmp I am using the app from google store I think it is the demo app. The error msg displays very quickly so I cannot copy it, but it says the connection is refused while from my comptuer it works fine.

**Comment by DanielnetoDotCom** [comment]
did you download this app?

https://play.google.com/store/apps/details?id=mobile.youphptube.com

I went to your server and I found this in your NGINX error log file ` /usr/local/nginx/logs/error.log`

`host not found in url "localhost/YouPHPTube/plugin/Live/on_publish.php" in /usr/local/nginx/conf/nginx.conf:23`

So I add the line below in your **hosts** file to make sure your server can resolve the localhost properly
```
sudo nano /etc/hosts
127.0.0.1      localhost
```
pease try again

**Comment by guymass** [comment]
Hi thank Daniel, sorry but no this is not working. from what I can see in the error it is trying to connect to the IP address of my server, 82.165.158.89 on port 1935 and than there is another port showing 51032 and is incremented each try, I get isConnected failed. Only from mobile, my OBS streams perfectly and I must add I love this script and I intend to support you as much as I can.

**Comment by DanielnetoDotCom** [comment]
I am confused are you trying on mobile?

if yes why the IP? the mobile does not request you the IP

you should use the credentials provided on the Live link

**Comment by guymass** [comment]
Hi sorry couldn't get back sooner. I am connecting with my credentials, this is not the case. I am connected to my profile and the login is fine, but when I try to initiate a stream from my mobile I get that error. I haven't configured anything because there is nothing to configure, it is the error msg which says it is trying to connect with the IP on the given port. The initial login is fine no issues there.

**Comment by guymass** [comment]
I am using a Samsung S7 Galaxie with YouPHPTube for android downloded from Google Store.

**Comment by guymass** [comment]
I think the best way you can view that error yourself is to create a user on the site and try to stream.

**Comment by DanielnetoDotCom** [comment]
for some reason, your NGINX server was stoped 

I start it with this command

` sudo /usr/local/nginx/sbin/nginx`

and now is working from the phone

**Comment by guymass** [comment]
Much thanks, I will keep it in check as I had no idea. Sorry couldn't get back sooner was away from my computer. Would nginx -t reload would do the trick just the same or must it be the way you started it? 

Have a great weekend,
Cheers.

**Comment by guymass** [comment]
Forgot to mention before, some users experience problems with capcha not showing on the Andriod App login screen. They get Error Ilegal Capcha but the capcha is hidden from them.
![IMAGE 2019-12-20 16:08:30](https://user-images.githubusercontent.com/58882903/71260198-f72da980-2342-11ea-823e-0c9fc8012214.jpg)

**Comment by guymass** [comment]
Also would like to know how to switch the menu to right side and logo to the left as my menu is Hebrew for most users. If this a css issue maybe I can do it myself with you guidance. I will also soon make time to complete the entire Hebrew translation.

**Comment by guymass** [comment]
This is a user trying to login with the App from Apple Store for iPhone 6S
 He is getting a white screen.
![IMAGE 2019-12-20 16:42:07](https://user-images.githubusercontent.com/58882903/71262133-aa000680-2347-11ea-9fa4-a3256825cfae.jpg)

**Comment by guymass** [comment]
I went today on a trip to Nazareth and tried to do a video stream from my mobile. The connection was OK and it seemed to stream fine, but it did not save any of my streams, I made few. I thought that once I disconnect it, the video will remain on my channel, isn't it supposed to record it to my channel when I stream?

**Comment by maxlinux2000** [comment]
you need to buy the SendRecordedToEncoder plugin for that.

Daniel... I have a problem wih the make live stream from you app using a normal user. 
If a use the Admin user I can do the live,
but with normal user, the connection to live server fail.

Here the configuration fot thi user

![Captura de pantalla de 2019-12-22 21-48-15](https://user-images.githubusercontent.com/5683921/71327128-d614b680-2504-11ea-880c-91dfa1bc0626.png)

**Comment by DanielnetoDotCom** [comment]
Hi

@guymass the apple store app was just fixed, just delete the app and install it again.
to be able to record the livestreams you need the plugin SendRecordedToEncoder 

@maxlinux2000 if it works for admin, it also should work with the regular user.

try to logoff in the app then login again and try again. If the error persists check your NGINX log file

**Comment by guymass** [comment]
OK Much thanks I will try that. also wanted to ask how to make menu items which are just urls to open in new tab? I don't see option to do so, only in the Page option where you insert a url in the page it will give a check box to open in a new window. I will need also to be able to do so from menu items which are just links.

**Comment by guymass** [comment]
Also Regarding this plugin, SendRecordedToEncoder I have purchased it, and like I said it was working from PC but not from Android mobile. The apple mobile was a separate issue I will try to resolve as you suggested.

**Comment by guymass** [comment]
Forgot to ask about the Captcha issue with android phone when using the App YouPHPTube, the captcha is invisible and users cannot login. Is it resolved?

**Comment by DanielnetoDotCom** [comment]
> e menu items which are just urls to open in new tab? I don't see option to do so, only in the Page option where you insert a url in the page it will give a check box to open in a new window. I will need also to be able to do so from menu items which are just links.

What about the topMenu plugin?
https://github.com/WWBN/AVideo/wiki/How-to-use-TopMenu-Plug-in

> Also Regarding this plugin, SendRecordedToEncoder I have purchased it, and like I said it was working from PC but not from Android mobile. The apple mobile was a separate issue I will try to resolve as you suggested.

If it is working on PC it MUST work on mobile. make sure you are really streaming on mobile.

> Forgot to ask about the Captcha issue with android phone when using the App YouPHPTube, the captcha is invisible and users cannot login. Is it resolved?

Captcha is not supported on mobile yet.
It will be reviewed

**Comment by guymass** [comment]
Regarding:
"Captcha is not supported on mobile yet.
It will be reviewed"

Well this issue prevents my users from login with the App from Google store, because it is waiting for the user to enter the code, but it is in a hidden state, all the user sees is the username password login fields. When they try to log into their account they get blocked because they didn't enter the captcha which is hidden and is part of the login process. So either cancel it completely from the App or disable it or make sure the user is able to see and enter the captcha code. Either that or the other because some of my android users are having this issue when trying to access our site using the App.

Regarding the Menu I will take a look as I don't need to many menu items.

Best Regards,
