### ISSUE TITLE
Channel Users stuck on upload

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2404]
Users get stuck on encoding a video 1 GIG and up. I did a remote session and one of my users were stuck on uploading a 2.95 GIG video for 2 days. We had to delete until the issue is fixed. Can you please look into this

**Comment by venwebsites** [comment]
My server has 4 Physical cores and each processor is 8 cores. My RAM is 64GIGS. I am not sure where the issue is as I have looked on my server and DNS. It may be script/server related

**Comment by DanielnetoDotCom** [comment]
check your log files

**Comment by venwebsites** [comment]
where are the log files for this

**Comment by DanielnetoDotCom** [comment]
Here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by allanmawerere** [comment]
@DanielnetoDotCom 
please help me in need to change my domain after installing youphptube it works fine but i  need
it to work under my  domain for example to access my site now am using http://35.192.163.105/YouPHPTube/  i need it to run on http://35.192.163.105 please help me!
am using ubuntu 16.04 LTS and googlecloud platform as my host.

**Comment by DanielnetoDotCom** [comment]
Hi @allanmawerere 

I guess the easiest way for you is to move your directory, try this ...

`mv /var/www/html /var/www/html_old && mv /var/www/html_old/YouPHPTube /var/www/html`

this should do the trick

**Comment by venwebsites** [comment]
ere is the video log. Please see attaced
[avideo.log](https://github.com/WWBN/AVideo/files/3965395/avideo.log)

**Comment by DanielnetoDotCom** [comment]
@venwebsites ??? I guess you are in the wrong issue

**Comment by DanielnetoDotCom** [comment]
@venwebsites there are too many things in this log file and I could not find any error.

do this, delete the log file, run the encoder again, as soon as a file stuck share the log here

**Comment by venwebsites** [comment]
ok

**Comment by venwebsites** [comment]
For some reason every time a user uploads a video, it doesn't upload right. It says it's uploaded but then says there's no running time. It also changes their thumbnail to someone elses thumbnail or random thumbnails. They tried deleting it and reuploading it several times.

**Comment by DanielnetoDotCom** [comment]
I have never seen this before, what you can do now is to force update all your files to the original and newest files (streamer and encoder)

to force to overwrite your files, you can do this command.
`
sudo git fetch --all && sudo git reset --hard origin/master`

**Comment by venwebsites** [comment]
would this over write my customization or user video info

**Comment by DanielnetoDotCom** [comment]
it will overwrite your customizations, but all video data will be preserved
