### ISSUE TITLE
Users Can't Delete Video

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2405]
When a user tries to delete a video an error message pops up saying "Your Video was not deleted" Unsuccessful

**Comment by DanielnetoDotCom** [comment]
please check your log file

**Comment by venwebsites** [comment]
here is the video log 
[avideo.log](https://github.com/WWBN/AVideo/files/3965396/avideo.log)

**Comment by DanielnetoDotCom** [comment]
Again, please delete the log, try to delete and share the log

**Comment by venwebsites** [comment]
I did and users are still having issues

**Comment by DanielnetoDotCom** [comment]
You suppose to share the log file after deleting the log file and try to delete the user again
