### ISSUE TITLE
a fix if you dont see al your categories on the trending page 

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2406]
The problem is that you dont see all your categories, if you have 5 or more categories

Line 26 if (empty($_POST['rowCount'])) {
    if (!empty($_GET['rowCount'])) {
        $_POST['rowCount'] = $_GET['rowCount'];
    } else {
        $_POST['rowCount'] = 5;
    }
}
Line 32 

the fix is replace the 5 with a 0

**Comment by Wepwawetcode** [comment]
you can also remove line 26 - 32 that will also fix it.

**Comment by DanielnetoDotCom** [comment]
sorry, what issue is that?

can you reproduce it on demo site?

**Comment by Wepwawetcode** [comment]
Its not a issue I came up with a solution to prevent that issue from happening it made it that the max categories where 5 so when you added a sixth one it didnot display.

Verstuurd vanaf mijn iPhone

**Comment by ra3ggy** [comment]
Where to fix it? In which file?

**Comment by Wepwawetcode** [comment]
Are you be able to hit me up on discord?
Or another social platform I can help you aswell with other issues.

Verstuurd vanaf mijn iPhone

**Comment by Wepwawetcode** [comment]
Trending.php
The problem is that you dont see all your categories, if you have 5 or more categories

Line 26 if (empty($_POST['rowCount'])) {
if (!empty($_GET['rowCount'])) {
$_POST['rowCount'] = $_GET['rowCount'];
} else {
$_POST['rowCount'] = 5;
}
}
Line 32

the fix is replace the 5 with a 0


Verstuurd vanaf mijn iPhone

**Comment by Wepwawetcode** [comment]
> Where to fix it? In which file?

I hope it helped?
