### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2410]
I can't seem to find the area where I would add Keywords and tags for SEO Optimization

**Comment by DanielnetoDotCom** [comment]
add on the head section 

![image](https://user-images.githubusercontent.com/18009293/70929658-52456080-2012-11ea-9ed6-7d8379cb8ecd.png)

**Comment by JoshWho** [comment]
In site configurations you can add this code but for SEO sake I would avoid using keywords and any kind of descriptions because it will be indexed on all pages.

**Comment by venwebsites** [comment]
SEO is a must to be found in major search engines. Tags have been added for content creator video however there should be a way to add SEO for the main site

**Comment by JoshWho** [comment]
I do not see really any issues with how the seo is on here. Your main importance is title description and then your content that has its own meta and og tags. The only thing missing is the sitebox code which I just manually add in the script head section in site config.

**Comment by venwebsites** [comment]
Can you please share the site box code :)

**Comment by JoshWho** [comment]
`<script type="application/ld+json">
{
   "@context": "http://schema.org",
   "@type": "WebSite",
   "url": "https://www.example-petstore.com/",
   "potentialAction": {
     "@type": "SearchAction",
     "target": "https://query.example-petstore.com/search?q={search_term_string}",
     "query-input": "required name=search_term_string"
   }
}
</script>`

**Comment by JoshWho** [comment]
The idea behind this script is to display a searchable index of pages your site search can grab.

So for your site you have to set the domain and the search query to match how your search engine on the site works. 

A default Installation of youphptube has a search string of ?search=

So the correct way would be

`<script type="application/ld+json"> { "@context": "http://schema.org", "@type": "WebSite", "url": "https://www.YOURDOMAIN.com/", "potentialAction": { "@type": "SearchAction", "target": "https://www.YOURDOMAIN.com/?search={search_term_string}", "query-input": "required name=search_term_string" } } </script>`

**Comment by venwebsites** [comment]
awesome thank you. this wouldn't mess up seo for videos and tags correct

**Comment by JoshWho** [comment]
COrrect. It will actual enhance their listing in the search indexes
