### ISSUE TITLE
embeded player

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2411]
Hi,

Is there a way to control the embeded player using external controls like plyr.io?

i.e i have a site and want to show the videos imported from youtube on my own page with my own controls to play, pause seek etc.

problem I have is when I use the embed link to load into plyr.io it comes up with an invalid url.

anyone else tried this?

**Comment by DanielnetoDotCom** [comment]
I guess by default you use a custom player on the embed videos

CustomizeAdvanced->disableYoutubePlayerIntegration

**Comment by JoshWho** [comment]
Problem is plyr.io is another custom video player and YouPHPTube already uses its own custom embed player. 

You can not use plyr.io with it.
