### ISSUE TITLE
video says encoding when using direct upload

### ISSUE THREAD

**Issue by inferno-prime** [WWBN/AVideo#2412]
ok since the last few updates things have changed I do not seem to be getting any errors in my log file my filesize is set to 300mb in php.ini I am on shared hosting and I will not be using the live stream feature or the encoder. I will upload both the already encoded video and the thumbnail for it. My current problem is when the upload finishes it says its still encoding which should not be for a direct upload.

**Comment by akhilleusuggo** [comment]
Is happening for me too ... I think it some kind of bug

**Comment by DanielnetoDotCom** [comment]
can you reproduce it on demo site?

**Comment by inferno-prime** [comment]
I don't think that will be possible since your specs are different from mine. Please keep in mind that some of us are not as fortunate to be able to have dedicated hosting for this which is why I am using direct upload.

Also does a temporary directory need to be set in the php.ini file ? as mine is not.

**Comment by DanielnetoDotCom** [comment]
@inferno-prime you can use the public encoder in your site

to be able to find a solution I need to be able to reproduce it

**Comment by inferno-prime** [comment]
No I don't want to use the encoder that defeats the purpose of using direct upload. I don't want to use the encoder. I Will keep on the lookout for any errors but since updates are made every day and no stable release has been made yet I guess I will just have to wait.

I used another script and had no problems uploading my 100MB+ files and encoding them just the other day.
