### ISSUE TITLE
peer-to-peer functionality?

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#2413]
Hi

Is there a way to add peer-to-peer functionality for the videos, or how difficult it would be to implement something like that. Is it possible to have such a plugin created?

greeting
Donnerstein

**Comment by DanielnetoDotCom** [comment]
Can you please be more clear what P2P feature are you looking for?

**Comment by Donnerstein** [comment]
The aim is to reduce the server load by allowing users who are watching a video to share the pieces that have already been downloaded. Something like Bitchute.

greeting

**Comment by JoshWho** [comment]
There is a beta test being done right now that will decentralize the videos using torrent like protocol but it is not public yet. This will once it is available be what you are looking for.

**Comment by Donnerstein** [comment]
I am happy to hear that.
I thank you for the answer.
greeting
