### ISSUE TITLE
Video Report Issue

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2415]
If someone reports a video/strike How do I enable the strike feature without deleting the video

**Comment by DanielnetoDotCom** [comment]
Hi, what do you mean?

you can remove the video, inactivate the video or inactivate the users. is up to you

**Comment by venwebsites** [comment]
I am looking to inactivate the video however the subscriber reactivates it. with YouTube if a video is reported, they have the ability to inactivate it but keep it on the servers until the investigation is complete.

**Comment by JoshWho** [comment]
Yes we need a way for admins to deactivate a video and not allow it to be changed by the user.

**Comment by Wepwawetcode** [comment]
also maybe a strike system? otherwise we are going to work on that ourselves
