### ISSUE TITLE
upgrade from youphptube

### ISSUE THREAD

**Issue by fst24sx** [WWBN/AVideo#2417]
im currently on youphptube version 7.8

if i upgrade to the new "avideo" 8.0 using git will it break my current installation?

**Comment by DanielnetoDotCom** [comment]
Will not break, but please make sure you update the encoder, streamer, and plugins

**Comment by allanmawerere** [comment]
@DanielnetoDotCom 
my live streaming is not working could you please help me 
my stat like is here http://35.192.163.105:8080/stat please check it and tell what could be the problem

**Comment by fst24sx** [comment]
> Will not break, but please make sure you update the encoder, streamer, and plugins

all seems to be working now thank you!

**Comment by DanielnetoDotCom** [comment]
@allanmawerere looks like your nginx is not running
