### ISSUE TITLE
No Video Player?

### ISSUE THREAD

**Issue by eYour** [WWBN/AVideo#2418]
hello, after i upload my video in my youphptube or avideo website, the video player doesn't work and its only show black screen and i cant play the video here picture to see, i tried to change the video player from the settings but still the same problem? any solution please

@DanielnetoDotCom 

![Captuwhyre](https://user-images.githubusercontent.com/59019914/71090210-8d32ca00-21b3-11ea-8c3d-7f3311dfedf1.PNG)

**Comment by DanielnetoDotCom** [comment]
check your log file please
