### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2419]
Is it possible when a user uploads a video it automatically generates a thumbnail , then if they don't like it , they have the ability to change it. similar to what YouTube options are

**Comment by JoshWho** [comment]
You need the video thumbnail plugin. This is already a possibility.

**Comment by venwebsites** [comment]
I believe I already have that plugin.

**Comment by DanielnetoDotCom** [comment]
@venwebsites if you have it maybe not enabled.

encoders generate the thumbs automatically, direct upload you will need the plugin

**Comment by venwebsites** [comment]
Hi I have it enabled. it generates thumbnails for my videos but not the users who created channels

**Comment by DanielnetoDotCom** [comment]
It supposes to work for any video.

I can not see any relation why is not creating for othe users.

can you reproduce it on demo site?
