### ISSUE TITLE
Encoder sometimes uploads to the wrong account

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2420]
Ever since the last major update I have been getting reports of videos not uploading to the correct accounts.

I can't figure this one out. SOmething to do with how their login details gets grabbed when going to the encoder page. THis is a really big issue. 

There needs to be a double check verify that it is the correct account logged in.

**Comment by Wepwawetcode** [comment]
fr could you share me some details?

**Comment by JoshWho** [comment]
Not exactly sure what is causing this yet but we may have some ideas on it. This isn't a problem so far on anyone else's platform. I have a lot of customizations in mine so I am still keeping a eye out for it.

**Comment by Wepwawetcode** [comment]
You have discord? maybe I could help you better there?

Op do 19 dec. 2019 om 21:43 schreef JoshWho <notifications@github.com>:

**Comment by JoshWho** [comment]
I appreciate that but I think we have it figured out.

**Comment by Wepwawetcode** [comment]
what was the issue?

Op do 19 dec. 2019 om 21:51 schreef JoshWho <notifications@github.com>:

**Comment by JoshWho** [comment]
Someone would upload a video and it would show on someone else's channel

**Comment by JoshWho** [comment]
> You have discord? maybe I could help you better there?

You can join my server here https://discord.gg/qXpy3V
