### ISSUE TITLE
Clear Cache Crashes the whole server spiking the load up to 90 %

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2421]
Not sure why this is happening but now when u manually clear cache it crashes everything and I have to force a reboot for recovery.

 <img src="https://static.buddylist.co/spike.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
Now you should be able to clear only the first page cache, it is a lot faster then clear the full cache
