### ISSUE TITLE
404 header is needed on Video Not found Pages

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2422]
Google and other search indexes keeps your deleted or removed videos on the search because it never gets a 404 error header for that page.

If you add a 404 header on that page the search bots will stop listing dead videos.

**Comment by JoshWho** [comment]
<img src="https://static.buddylist.co/dd1.png" style='width:100%;' border="0" alt="Null">

<img src="https://static.buddylist.co/dd2.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
This should do the trick!!
