### ISSUE TITLE
Safari Problems

### ISSUE THREAD

**Issue by vielsaitig** [WWBN/AVideo#2424]
There seems to be missing support for WEBP in Safari. Therefor the Mouseover of Videos (YouPHPtubeFLIX template) only shows a question mark.

Next to that Safari brings up a console error. Only Safari as it seems...
Failed to load resource: the server responded with a status of 404 (Not Found)
https://mediathek.ztv.tirol/videos/cache/js/bootstrap-select.js.map

Is there a way to fix this or to give Safari some sort of fallback for the Video Mouseover? Would even help if you could use specific CSS for Safari only (for instance via a body tag for each browser type via browser detection).

Tanx for your effort!!!

**Comment by DanielnetoDotCom** [comment]
I sent an update, in case it is Safari, it will use the Gif instead webp

**Comment by vielsaitig** [comment]
Works absolutely fine!!!!! Amazing...
