### ISSUE TITLE
CloneSite plugin improvement proposal

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo#2428]
Currently, when we clone an Avideo in another server, we get a perfect copy of the videos and the database ... but ...

we get an exact copy of the configuration, comments etc, and therefore Live broadcasts do not work, and comments already present can be lost.
Furthermore the other servers can be on different subdomains in different regions. For example having a server in newyork and another in ireland, so that if there is a service interruption, the second server can take over quickly.
I'm practically describing an HA service.

In my opinion this plugin should be used to have two or more copy sites of which only one is active and the others can replace in case of need.
At the very least, the site configuration should be separated from other data.
It would also be good if the comments remained in a database and a separate application, as do other commercial services.

A quick way to start doing something in this direction would be to give the administrator the chance to NOT copy the SQL configurations table of the master site to the slave site.
A simple check that you can disable in the setup of the es suficiente plugin.

The syntax of mysqldump to exclude a table is this:

`mysqldump yophptube.db --ignore-table=yophptube.db.configurations -u root -p > dump.sql
`

regards
MaX

**Comment by Wepwawetcode** [comment]
a fallback server?
