### ISSUE TITLE
Incorrect operation of SignUpAgreement plugin with Cyrillic

### ISSUE THREAD

**Issue by itdoka** [WWBN/AVideo#2429]
I'm trying to write the rules, but in the input I get only encoded text, I attach screenshots
![bandicam 2019-12-22 12-24-21-761](https://user-images.githubusercontent.com/52359603/71318254-7b119e00-24c9-11ea-8e48-ecd376dafaa9.jpg)
![bandicam 2019-12-22 12-23-40-106](https://user-images.githubusercontent.com/52359603/71318258-8795f680-24c9-11ea-8186-6da791994b0c.jpg)
but in Latin everything is fine
![bandicam 2019-12-22 12-26-08-149](https://user-images.githubusercontent.com/52359603/71318274-aeecc380-24c9-11ea-8591-80872c79463a.jpg)
![bandicam 2019-12-22 12-26-47-978](https://user-images.githubusercontent.com/52359603/71318276-b4e2a480-24c9-11ea-97d7-768e788ddcdc.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi

can you please paste the text here, I will try it here

**Comment by itdoka** [comment]
Hi

for example in the field Label
правила    u043fu0440u0430u0432u0438u043bu0430

for example in the field Text
Пример текста    u041fu0440u0438u043cu0435u0440 u0442u0435u043au0441u0442u0430

**Comment by DanielnetoDotCom** [comment]
Thanks for the info, you should be good now.

Update your code, download a new plugin version and make sure you check the option **useJSON_UNESCAPED_UNICODE**

![image](https://user-images.githubusercontent.com/18009293/71517568-664c5600-288d-11ea-92ca-a51dc722cce5.png)

**Comment by itdoka** [comment]
Unfortunately, the plugin did not update, the item did not appear. I did the update according to the instructions on this site. Кнопка обновления плагина не появилась.

**Comment by itdoka** [comment]
Unfortunately, the plugin was not updated, the item as in the screenshot did not appear. The plugin update button did not appear. I did the update according to the instructions on this site.

**Comment by DanielnetoDotCom** [comment]
Hi

The notification plugin you have to download it again on the plugins site
