### ISSUE TITLE
clone manager plugin

### ISSUE THREAD

**Issue by fst24sx** [WWBN/AVideo#2431]
after upgrading from youphptube to avideo using clonesite plugin shows nothing on "clones manager" on master even after making new request form slave site.

**Comment by fst24sx** [comment]
also, the audit plugin no longer works. it was working fine before i used it daily. 

I have updated the custom plugins already.

**Comment by DanielnetoDotCom** [comment]
Can you please check your log files for some clue?

**Comment by fst24sx** [comment]
fixed it! mysql needed an update.

question:
how do i clear the audit logs? i have over 2,000,000 entries LoL

**Comment by DanielnetoDotCom** [comment]
now you need to manually delete from the database table.
