### ISSUE TITLE
Can't change .gif

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2434]
Yes , I can reproduce it on demo site .
I'm not able to change the .gif

**Comment by DanielnetoDotCom** [comment]
Hoo, I guess I know what is happening.

we are currently using an animated webp format instead a gif. the gif will only show on Safari browsers.

I just sent an update to let you upload webp images

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom But can I change the codec ? cause I'm not able to find the webp compile . Is there any plugin that can do that from the streamer site and not the encoder ?
Like deleting all the .gif and regenerating them again , or request the encoder to generate the .gif

**Comment by DanielnetoDotCom** [comment]
you can manually delete all gifs from the videos directory.

but all FFMPEG commands must be made on the encoder.

if you want to not generate the webp you may be able to comment it out on encoder

https://github.com/WWBN/AVideo-Encoder/blob/20299d62272e1bbd97dc1b480db8cbff92778c1c/objects/Encoder.php#L894
