### ISSUE TITLE
Adsense Error

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2435]
Hello,

I tried to link my adsense account to my site however these are the errors i received. Any suggestions

We’ve found some policy violations on your site which means your site isn’t ready to show ads yet.

Valuable inventory: Scraped content
As stated in our Program policies, we may not show Google ads on pages or apps with little or no value and/or excessive advertising to the user. This includes pages or apps that are scraping or rewriting of content from other sources without adding value. Please see Google’s Webmaster quality guidelines for thin content with little or no added value for more information.

For more information, review the following resources:

Policy tips for creating high quality sites (part 1)
Policy tips for creating high quality sites (part 2)
Webmaster quality guidelines
AdSense Program policies

**Comment by DanielnetoDotCom** [comment]
probably because you directly import videos from youtube

you must have original videos.

**Comment by venwebsites** [comment]
no these videos are not from YouTube.  they are directly for the website

**Comment by DanielnetoDotCom** [comment]
I am not sure what they are complaining about. they are not clear.

you should try to get more details from google.

also if you find it out please share here.

**Comment by venwebsites** [comment]
this site should be monetized.  I am going to post the details here

**Comment by venwebsites** [comment]
Please see attached Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Daniel Neto <notifications@github.com> Date: 12/27/19  8:02 AM  (GMT-05:00) To: WWBN/AVideo <AVideo@noreply.github.com> Cc: venwebsites <designs@venwebsites.com>, Author <author@noreply.github.com> Subject: Re: [WWBN/AVideo] Adsense Error (#2435) I am not sure what they are complaining about. they are not clear.
you should try to get more details from google.
also if you find it out please share here.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/WWBN/AVideo/issues/2435?email_source=notifications\u0026email_token=AN7LJZNAQNPV5DD25L2C7WTQ2X4GPA5CNFSM4J6WJOQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHXEZLQ#issuecomment-569265326",
"url": "https://github.com/WWBN/AVideo/issues/2435?email_source=notifications\u0026email_token=AN7LJZNAQNPV5DD25L2C7WTQ2X4GPA5CNFSM4J6WJOQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHXEZLQ#issuecomment-569265326",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DanielnetoDotCom** [comment]
Sorry attachments

**Comment by venwebsites** [comment]
did you get the attachments Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Daniel Neto <notifications@github.com> Date: 12/27/19  11:36 AM  (GMT-05:00) To: WWBN/AVideo <AVideo@noreply.github.com> Cc: venwebsites <designs@venwebsites.com>, Author <author@noreply.github.com> Subject: Re: [WWBN/AVideo] Adsense Error (#2435) Sorry attachments

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/WWBN/AVideo/issues/2435?email_source=notifications\u0026email_token=AN7LJZMFVYBJMC7AXEXFLPLQ2YVIHA5CNFSM4J6WJOQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHXN7BQ#issuecomment-569302918",
"url": "https://github.com/WWBN/AVideo/issues/2435?email_source=notifications\u0026email_token=AN7LJZMFVYBJMC7AXEXFLPLQ2YVIHA5CNFSM4J6WJOQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHXN7BQ#issuecomment-569302918",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DanielnetoDotCom** [comment]
sorry no attachments here

**Comment by JoshWho** [comment]
Google denied your adsense because they noticed you have ripped my Terms, Coppa, DMCA, and Privacy.
On top of that you also Copied all of my tutorials and even grabbing some of my videos. Google has reported me everything this morning. I am pretty sure your domain will be in their blacklist now.

**Comment by JoshWho** [comment]
Here I archived it so incase you want to play dumb and delete it it is recorded now. 

https://web.archive.org/web/20191231120344/https://support.venwebsites.com/kb/faq.php?id=5

**Comment by JoshWho** [comment]
Your forgot to remove my support email

<img src="https://static.buddylist.co/ripped.png" style='width:100%;' border="0" alt="Null">

**Comment by venwebsites** [comment]
No videos were used in any tutorials except my own. as far as "ripping off" Your content that is far from the truth. You assisted me in getting this platform up by suggestions not limited to terms, style,support system, CDN, etc.          I have followed your advice and furthermore I offered to retain your services further as this was a year long project and just wanted to get it going.      I must say that I went with Youphptube because of the fast turn around time for support however I am regretting not giving my business to StreamHash. They offered to complete the project start to finish with mobile apps for $2,000I still haven't decided what to do yet because StreamHasg advised me that the YouPHPTube script is not database friendly and would be hard to convert. Luckily for me I have disposable income where I can just start over with StreamHash and manually migrate.    I appreciate all the help you have provided me and that was not forgotten. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: JoshWho <notifications@github.com> Date: 12/31/19  7:05 AM  (GMT-05:00) To: WWBN/AVideo <AVideo@noreply.github.com> Cc: venwebsites <designs@venwebsites.com>, Author <author@noreply.github.com> Subject: Re: [WWBN/AVideo] Adsense Error (#2435) Your forgot to remove my support email


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/WWBN/AVideo/issues/2435?email_source=notifications\u0026email_token=AN7LJZPZVX7OI32AQSXHLGLQ3MYR7A5CNFSM4J6WJOQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEH4EJFY#issuecomment-569918615",
"url": "https://github.com/WWBN/AVideo/issues/2435?email_source=notifications\u0026email_token=AN7LJZPZVX7OI32AQSXHLGLQ3MYR7A5CNFSM4J6WJOQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEH4EJFY#issuecomment-569918615",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by venwebsites** [comment]
You would be incorrect in your statement ,as the terms that were placed resides on the ticketing system. a subdomain not even attached to the prostreams domain.Google Adsense advised me that the videos on my site are also on YouTube. I worked with Google and had that issue resolved Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: JoshWho <notifications@github.com> Date: 12/31/19  7:02 AM  (GMT-05:00) To: WWBN/AVideo <AVideo@noreply.github.com> Cc: venwebsites <designs@venwebsites.com>, Author <author@noreply.github.com> Subject: Re: [WWBN/AVideo] Adsense Error (#2435) Google denied your adsense because they noticed you have ripped my Terms, Coppa, DMCA, and Privacy.
On top of that you also Copied all of my tutorials and even grabbing some of my videos. Google has reported me everything this morning. I am pretty sure your domain will be in their blacklist now.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/WWBN/AVideo/issues/2435?email_source=notifications\u0026email_token=AN7LJZJKZGRUMZTCDDAEG5TQ3MYFRA5CNFSM4J6WJOQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEH4EFWQ#issuecomment-569918170",
"url": "https://github.com/WWBN/AVideo/issues/2435?email_source=notifications\u0026email_token=AN7LJZJKZGRUMZTCDDAEG5TQ3MYFRA5CNFSM4J6WJOQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEH4EFWQ#issuecomment-569918170",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JoshWho** [comment]
Ok Goodluck on your venture.

**Comment by venwebsites** [comment]
Thank you.  I hired a firm to do some customizations and update the terms and COPPA. Once that is done I can email it to you if you like to use it. What are your thoughts about the mobile app. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: JoshWho <notifications@github.com> Date: 1/7/20  5:53 PM  (GMT-05:00) To: WWBN/AVideo <AVideo@noreply.github.com> Cc: venwebsites <designs@venwebsites.com>, Author <author@noreply.github.com> Subject: Re: [WWBN/AVideo] Adsense Error (#2435) Ok Goodluck on your venture.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/WWBN/AVideo/issues/2435?email_source=notifications\u0026email_token=AN7LJZNV7DZAODXEGRPPD5DQ4UBUTA5CNFSM4J6WJOQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIKSFEY#issuecomment-571810451",
"url": "https://github.com/WWBN/AVideo/issues/2435?email_source=notifications\u0026email_token=AN7LJZNV7DZAODXEGRPPD5DQ4UBUTA5CNFSM4J6WJOQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIKSFEY#issuecomment-571810451",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JoshWho** [comment]
No thank you. My terms are fine. I never had a chance to use their mobile app. I had a huge problem with their encoders they use and a lot of uploads never converted correctly. Then they want you to pay for them to fix the bugs that comes with it. 

Avideo formerly known as YouPHPTube is the best of all the scripts out there and believe me I tried them all. Support is also the best because all the other projects out there charge for every bit of support you might need. 

Avideo is the closest script I have seen that comes really close to the original Youtube platform, Even the Nginx server for live streaming is super professional and not offered by many scripts. Most try to cheat and use Wowza for live streaming which is not that good of a server for commercial live sites. 

The next best thing next to Avideo is Clipbucket and it comes with a lot of bugs as well that you have to pay to fix.

**Comment by venwebsites** [comment]
I agree with you on YouPHPTube..Streamhash uses Laravel and to be quiet honest Daniel's script is a lot better. ClipBucket is expensive and don't get me started on WoWza :) I have been doing this project for a year using RedHat and was dissapointed I had to start from scratch when Daniel told me the script doesn't support Redhat/CentOS. I think I am going to give the mobile app a shot. If Daniel allows it would you allow me to share the license with you and compare both platforms. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: JoshWho <notifications@github.com> Date: 1/7/20  7:20 PM  (GMT-05:00) To: WWBN/AVideo <AVideo@noreply.github.com> Cc: venwebsites <designs@venwebsites.com>, Author <author@noreply.github.com> Subject: Re: [WWBN/AVideo] Adsense Error (#2435) No thank you. My terms are fine. I never had a chance to use their mobile app. I had a huge problem with their encoders they use and a lot of uploads never converted correctly. Then they want you to pay for them to fix the bugs that comes with it.
Avideo formerly known as YouPHPTube is the best of all the scripts out there and believe me I tried them all. Support is also the best because all the other projects out there charge for every bit of support you might need.
Avideo is the closest script I have seen that comes really close to the original Youtube platform, Even the Nginx server for live streaming is super professional and not offered by many scripts. Most try to cheat and use Wowza for live streaming which is not that good of a server for commercial live sites.
The next best thing next to Avideo is Clipbucket and it comes with a lot of bugs as well that you have to pay to fix.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/WWBN/AVideo/issues/2435?email_source=notifications\u0026email_token=AN7LJZNQ4V7DVJCGS5IOO6LQ4UL3VA5CNFSM4J6WJOQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIKX6UA#issuecomment-571834192",
"url": "https://github.com/WWBN/AVideo/issues/2435?email_source=notifications\u0026email_token=AN7LJZNQ4V7DVJCGS5IOO6LQ4UL3VA5CNFSM4J6WJOQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIKX6UA#issuecomment-571834192",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
