### ISSUE TITLE
other users thumbnails are attaching to other users videos

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2437]
This script is extremely buggy to the point its becoming embarrassing to my brand. Please see the message below

A Message from a user on my website :

Hi, when I look at the website it seems that my thumbnail has been placed on someone else's video? The attached screenshot is of the video 'Introduction to My Madness' by Casey Elizabeth Dennis with the thumbnail of my most recent Stardew Valley video. Maybe I'm the only one seeing this. I've sent a chat message to Casey but have yet to get a confirmation that she's seeing this as well.

**Comment by venwebsites** [comment]
Please see the attached log that is filled with errors 
[avideo.log](https://github.com/WWBN/AVideo/files/3996163/avideo.log)

**Comment by DanielnetoDotCom** [comment]
to be able to fix, I need to reproduce that.

That is the first time I hear about it.
