### ISSUE TITLE
Authenticated LDAP over SSL

### ISSUE THREAD

**Issue by joel6890** [WWBN/AVideo#2439]
Good evening,

Thanks for this fantastic project. Having an "internal, self-hosted Youtube" for our company will be just great!

I purchased the LDAP connector plugin today, but can't get it to work with our company's LDAP server. We have two requirements:

1. The connection to the LDAP server is secure (simple TLS)
2. YouPHPtube needs to authenticate with the LDAP server

The [LDAP connection instructions](https://github.com/WWBN/AVideo/wiki/Configure-LDAP-Plugin) say nothing about either scenario and I am beginning to wonder if these options are supported? I have tried connecting via non-TLS first, to take that variable out of the way, but can't make authentication work. I used a RDN as below:

`uid={$user},ou=Company Name,cn=admin,dc=auth,dc=companyname,dc=io,userPassword=REDACTED`

When attempting to log in via LDAP then, the following log line is written to avideo.log:

`LDAP BIND fail: 49: Invalid credentials`

I know the credentials I'm entering are correct however. Any help would be much appreciated.

**Comment by DanielnetoDotCom** [comment]
Sorry for the delay

the problem above looks like is due a wrong RDN

did you see that? https://github.com/WWBN/AVideo/wiki/Configure-LDAP-Plugin

**Comment by joel6890** [comment]
Hi Daniel,

I did see that page; in fact, I linked it in my post. I have tried many different RDNs without success. Basically I'd like these questions answered:

1. Our LDAP server doesn't accept anonymous queries. Is it possible to configure the plugin to authenticate with the directory server using admin (or other) credentials?
2. Is LDAP over simple TLS (port 636) supported?

**Comment by DanielnetoDotCom** [comment]
To be honest I am not sure about those questions but what I can tell you is:


>  Our LDAP server doesn't accept anonymous queries. Is it possible to configure the plugin to authenticate with the directory server using admin (or other) credentials?

You will use the user credentials to query the LDAP server, so I guess it is not a problem

> Is LDAP over simple TLS (port 636) supported

Right now we do not add the TLS option, but you can customize the port

?


each LDAP is a different environment.

the only way to make sure is by testing it inside your network and using your LDAP server.

If you can give us access to your network and you are willing to pay for the support please email us at developer@youphptube.com.
