### ISSUE TITLE
Plugin Programs (Playlists) not working

### ISSUE THREAD

**Issue by forsmartworld** [WWBN/AVideo#2440]
hello i can't activate plugin Programs / Playlists i did test it on 2 different server 1 with ubuntu 18 and one with ubuntu 16. same issues with both server when you try to activate plugin remains stuck in processing mode for ages, one demo site i did test it and is working.

Keen you help with an info how i can make it work?

Thank you

**Comment by DanielnetoDotCom** [comment]
Please check your log file

**Comment by forsmartworld** [comment]
![image](https://user-images.githubusercontent.com/42339163/71437868-18ecaf00-26fc-11ea-89a6-0b7cc12fe303.png)

**Comment by forsmartworld** [comment]
hello this is the right log file?

**Comment by forsmartworld** [comment]
![image](https://user-images.githubusercontent.com/42339163/71438103-08890400-26fd-11ea-97d7-64f9701cf4d3.png)

**Comment by DanielnetoDotCom** [comment]
Hi

No, the log is wrong, I am talking about this https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by forsmartworld** [comment]
[25-Dec-2019 12:27:15 Europe/Helsinki] plugin::setCurrentVersionByUuid error on$
[25-Dec-2019 12:27:15 Europe/Helsinki] Plugin Not Found: Statistics
[25-Dec-2019 12:27:24 Europe/Helsinki] plugin::setCurrentVersionByUuid 39d3b5fe$
[25-Dec-2019 12:27:24 Europe/Helsinki] plugin::setCurrentVersionByUuid error on$
[25-Dec-2019 12:27:24 Europe/Helsinki] Plugin Not Found: Statistics
[25-Dec-2019 12:28:07 Europe/Helsinki] PHP Fatal error:  Uncaught Error: Call t$
Stack trace:
#0 {main}
  thrown in /var/www/html/objects/pluginSwitch.json.php on line 36
[25-Dec-2019 12:40:10 Europe/Helsinki] Plugin Not Found: Statistics

**Comment by forsmartworld** [comment]
thank you

**Comment by forsmartworld** [comment]
is there a way to reinstall plugin manually

**Comment by forsmartworld** [comment]
on a new vps same issue but i see on demo site is working

**Comment by forsmartworld** [comment]
this is the line 36 on file /var/www/html/objects/pluginSwitch.json.php

if(empty($obj->pluginversion)||is_null($obj->pluginversion)){
    require_once $global['systemRootPath'] . 'plugin/AVideoPlugin.php';
    $p=AVideoPlugin::loadPlugin($_POST['name']);      = this line
    $currentVersion=$p->getPluginVersion();
    $obj->pluginversion=$currentVersion;
    Plugin::setCurrentVersionByUuid($_POST['uuid'], $currentVersion);

}



echo '{"status":"'.$obj->save().'"}';

**Comment by DanielnetoDotCom** [comment]
I think I found the problem, and I just sent a fix

**Comment by forsmartworld** [comment]
working like a charm thank you very much
