### ISSUE TITLE
Error. Oops you've encountered an error

### ISSUE THREAD

**Issue by reatherly** [WWBN/AVideo#2441]
*EDIT* I am running my Apache Stack on Windows 7. Manually installed Apache, MYSQl, and PHP. 

I just installed Avideo on my personal server at home. I am pretty well versed with .htaccess files, mod_rewrite and so on. I am also experienced with editing apache.conf files and php.ini. I have done everything to edit them the way they are supposed to be but I for some reason its is still giving me this error. I have tried and verified that mod_rewrite is configured properly. 

It appears that either something went wrong or the mod rewrite configration is not correct.
If you don't use apache, just let .htaccess stay or create a empty file - then this check will pass.

We need to allow Apache to read .htaccess files located under the X:\web directory. You can do this by editing the Apache configuration file:

Find the section <directory /var/www/html> and change AllowOverride None to AllowOverride All

sudo nano /etc/apache2/apache2.conf
After editing the above file your code should be like this:

<Directory /var/www/>
          Options Indexes FollowSymLinks
          AllowOverride All
          Require all granted
  </Directory>
In order to use mod_rewrite you can type the following command in the terminal:

sudo a2enmod rewrite
Restart apache2 after

sudo /etc/init.d/apache2 restart
or

sudo service apache2 restart

Thank you for your help.

**Comment by DanielnetoDotCom** [comment]
What operational system are you using?

Check your Apache error log and also the access log for some clue

**Comment by reatherly** [comment]
I am running some updates on my server right now. As soon as they are done i will be able to look at the logs. I will let you know. As for the OS it is Windows 7. I also manually installed Apache, MySQL, and PHP. No one click install WAMP stacks.
