### ISSUE TITLE
Admin without admin rights

### ISSUE THREAD

**Issue by Powerbock** [WWBN/AVideo#2442]
Hello,
How do I get administrator rights for my administrator again? In the user administration there was suddenly "Standard User" instead of Administrator. After logging out and logging in again, I am actually a normal user, no more extensions etc.
How do I get full rights as "admin" again? How do I change the mysql database manually, or is there another way?

Kind Regards
Ronald

**Comment by DanielnetoDotCom** [comment]
I am not sure what happen so you lose the admins rights.

but to enable the admin again you must change the isAdmin column in your users table.

**Comment by SergejGrin** [comment]
Hello!
I installed AVIDEO (YouPHPTube) on the Ubuntu server 18.04.3 Installation works well, but when you add a new user or change changes (enable) functions in the user panel, the administrator becomes a regular user. Reinstalled the system four (!!!) times. This is stably repeated. What am I doing wrong or is this a program error?
Conifugation:
Ubuntu Server 18.04
mysql Ver 14.14 Distrib 5.7.28
Apache / 2.4.29
PHP 7.2.26-1 + ubuntu18.04.1 + deb.sury.org + 1 (cli)
Installed on the manual:
https://www.linuxbabe.com/ubuntu/install-youphptube-ubuntu-18-04-server

My site: http://tube.wakeupnow.info
Thank you in advance,
Sergej

**Comment by DanielnetoDotCom** [comment]
@SergejGrin Please open a new issue for that

this issue is related to something else

**Comment by DanielnetoDotCom** [comment]
@SergejGrin sorry, you right I will review it.

**Comment by DanielnetoDotCom** [comment]
I found the bug and I sent a fix

**Comment by SergejGrin** [comment]
Wonderful!
And when will this fix be seen and tested? Where can I download the Russian language localization file?

**Comment by DanielnetoDotCom** [comment]
You need to update your files, try this https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

to translate copy any translation file and rename it with the propper flag name

**Comment by Powerbock** [comment]
Thank you Sergej, Thank you Daniel again,
for your help, it works now again.
I am very happy.

**Comment by SergejGrin** [comment]
Thank you Daniel!
I already translated the localization file and wanted to give it to the community (for the holidays), so I asked where it can be downloaded. I am new to this site.

**Comment by DanielnetoDotCom** [comment]
Thanks @SergejGrin  it will be added on the main branch

**Comment by SergejGrin** [comment]
Thank you Daniel!
There’s no problem with the administrator. Everything works great! I will continue to improve and add the localization file, since many more notifications are not included in the basic translation.

**Comment by DanielnetoDotCom** [comment]
Thanks awesome!
