### ISSUE TITLE
Configure custom cdn dns for AWS_S3 plugin?

### ISSUE THREAD

**Issue by razyalov** [WWBN/AVideo#2443]
I'm trying to understand how to configure AWS_S3 to use a custom dns for cdn. I can only see a boolean `CDN_Link` which I don't understand what it does, but where can I set my own custom cdn's dns name, if at all? (More specifically I configured aws CloudFront to serve the videos from s3, and I want to have the system point videos to the cdn instead of the s3 url.

Also, for some reason, after completing the upload of the files to the S3 bucket from the plugin page, some of the videos still point to the youphptube server instead of the s3 bucket. I couldn't tell, from looking at the database's videos table how does the system decide if a video should be served locally or from the cdn server.
All my vidoe files in the `/videos` folder are now dummy files that contains the words `Dummy File` in them.

**Comment by razyalov** [comment]
Ok, it seems to be an issue related to using the caching plugin. I manually deleted the cache's folder and now it all shows correctly.
Still not sure if there is a way to configure a custom CDN link instead of a direct link to the s3 bucket.

**Comment by DanielnetoDotCom** [comment]
Hi, yes you can configure a custom CDN

![image](https://user-images.githubusercontent.com/18009293/71528712-f7d4bb80-28bf-11ea-8c50-39b8a34caf7c.png)

**Comment by razyalov** [comment]
Thanks, by default the plugin installed it with a 'false' value, so it only showed me a checkbox. I edited the `code` to a string and now it works.
