### ISSUE TITLE
Embed URL into Wordpress

### ISSUE THREAD

**Issue by angelawong** [WWBN/AVideo#2446]
When I try to embed a URL from YouPHPTube into Wordpress and I keep getting this error message:
**No video with supported format and MIME type found.**

If I were to upload the video directly into my WordPress site, I don't have any issues viewing the video. Any advice or  help would be most appreciated. Thanks so much.

**Comment by DanielnetoDotCom** [comment]
Hi

how are you embedding?

can you please provide a screenshot from WP and from where are you getting the embed code?
 and a code sample what are you doing?

**Comment by angelawong** [comment]
Daniel,

Here are some screenshots







I have no problems embedding the codes but I could not use the URL like I could with a YouTube link. Please advise.

Thanks so much.

**Comment by DanielnetoDotCom** [comment]
Sorry no screenshots here

**Comment by angelawong** [comment]
Daniel,

I have attached a document with the screenshots. Hope this goes through. Thanks so much.
[wordpress.pdf](https://github.com/WWBN/AVideo/files/4005411/wordpress.pdf)

**Comment by DanielnetoDotCom** [comment]
FYI, you can copy and paste images here

but as I can see you are using a video upload option in WP

you should look for something like add HTML code and you will add the iframe code 

![image](https://user-images.githubusercontent.com/18009293/71519295-c34c0a00-2895-11ea-845d-b87419771132.png)

**Comment by angelawong** [comment]
Thanks Daniel. Yes, as mentioned, I could embed the codes without any issues. I was hoping that I could also just embed a link without having to mess with the codes. Anyway, no worries. Thank you so much. I do love the YouPhpTube application. Thanks for all that you are doing with it and for making it available to the rest of us.

Cheers,
Angela
