### ISSUE TITLE
YPT Wallet please explain

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#2448]
Can you please explain how the yptwallet works.  

If the video publishers add funds, can they withdraw them or transfer those funds to another user account?  If yes, how can I prevent that from happening? 

Is there a division between the funds they add and the monetization rewards credits they receive for view? or how can I tell the difference?

**Comment by DanielnetoDotCom** [comment]
Here is what we have to explain the wallet 
https://github.com/WWBN/AVideo/wiki/YPTWallet-Usage

the wallet basically will mix the rewards and add funds (from real money).

but to not allow them to manually add funds you just do not enable any payment gateway, so will be no option for that.
