### ISSUE TITLE
Improvement: Faster Avideo Encoder operations

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo#2450]
Currently the Encoder when processing a video, has to complete all operations (HD, SD, Low, WebM ...) and then transfer the files to the Streamer.
This can mean waiting hours, before a video is visible on the Streamer.

My proposal:
When the first operation (HD in mp4 format) ends, the Encoder immediately transfers thumbnails and HD video, and then continues with the other operations.
In this way the Streamer video will appear very fast (only in HD) and then over time, the other resolutions and formats.

**Comment by akhilleusuggo** [comment]
Daniel is not even gonna answer this post . Don't wait for it . Better hire someone .
Your idea is the same as youtube's one . Sadly it can not be used on HLS ..

**Comment by maxlinux2000** [comment]
I don't know if using HLS is a good idea.
Yesterday I tried an ffmpeg script to do a live at 720p (15f 1500kb / s) using a raspberry and an IP camera.
The script works for both Avideo and YouTube, simply by changing the RTSP_URL and Key variables.

In Avideo without HLS the image was very good, while in YouTube it was blurred.

So I am not sure if the HLS is really necessary to get the same fuzzy results as youtube and have to use very powerful machines to do a real-time coding and then quickly convert back to Mp4 and WebM.
Clearly YouTube can afford to use a lot of processor time for these tasks, but for a common user like us, I don't know if it's a good idea.

Of course YouTube almost forces you to use very high resolutions to obtain decent results, but this also means for us, having to hire very fast internet, powerful computers and very good cameras ...
Instead I want to use cheap ip cameras, a raspberrypi and a common adsl to make live on the internet.

And in addition youtube is now doing everything to lose user, greatly increasing publicity and censorship to all those who are not in line with their worldview.

So ... please Daniel, see if you can do this I ask.

Thank you
