### ISSUE TITLE
Message could not be sent You must provide at least one recipient email address

### ISSUE THREAD

**Issue by BrianKash** [WWBN/AVideo#2452]
All email operations not working despite inputting all the necessary requirement and configuring my everything correct, how can I fix this?

![error 2](https://user-images.githubusercontent.com/26645449/71554628-66ce2380-2a2a-11ea-87e2-3fb40ffa29a9.jpg)

![error](https://user-images.githubusercontent.com/26645449/71554622-5322bd00-2a2a-11ea-9d16-4d287720b558.jpg)

please help on the procedures to fix this

**Comment by DanielnetoDotCom** [comment]
Hi

what do you have here?

![image](https://user-images.githubusercontent.com/18009293/71555378-61f97780-2a0a-11ea-9094-2dd92be41c32.png)

also check your log file

**Comment by BrianKash** [comment]
Hello, I have the email I used for installation there. it's not working either, I added a new one all the same

**Comment by DanielnetoDotCom** [comment]
please check your log file

**Comment by BrianKash** [comment]
Hello, kindly give me help on where  can find the log file, I have been searching for it

**Comment by DanielnetoDotCom** [comment]
Please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by BrianKash** [comment]
Hello, below is the error concerning email not sent I found in the log file

PHP Deprecated:  __autoload() is deprecated, use spl_autoload_register() instead in /home/zittvcom/public_html/objects/PHPMailer/PHPMailerAutoload.php on line 45
[29-Dec-2019 11:56:11 America/New_York] Sending SMTP Email
[29-Dec-2019 11:56:11 America/New_York] sendVerificationLink Error Info: You must provide at least one recipient email address.

**Comment by DanielnetoDotCom** [comment]
Hi

I can not see any error on this

Can you please provide a longer log file?

Also what php version and OS are you using?

**Comment by BrianKash** [comment]
Hello I am using PHP v7.4 on Apache

below is a screenshot of a longer version of the log

![error](https://user-images.githubusercontent.com/26645449/71560585-f3053880-2a74-11ea-83bf-18bb903464df.jpg)

**Comment by DanielnetoDotCom** [comment]
The only thing I can see is the Deprecated warning.
not sure if it is related to PHP7.4

what SMTP server are you using?

Is your AVideo installed in a Ubuntu server?

**Comment by BrianKash** [comment]
I have fixed the problem, thank you very much. Seems my PHP version7.4 was rendering some functions in PHP mailer absolute, I have dropped my PHP version to 7.0 and everything is working ok now... 

so turns out PHP mailer version isnt compatible with PHP version 7.4

**Comment by DanielnetoDotCom** [comment]
Thanks but I will look for a newer PHPMailer version to avoid this error

**Comment by BrianKash** [comment]
Sure thing, I had found this version https://github.com/PHPMailer/PHPMailer I just failed to integrate it but am sure you may wor with it, thank you once more.

**Comment by DanielnetoDotCom** [comment]
I sent an update with the newest PHPMailer

you may need to update the BlackBlaze plugin or the FTP_Storage plugin if you have them

**Comment by BrianKash** [comment]
> I sent an update with the newest PHPMailer
> 
> you may need to update the BlackBlaze plugin or the FTP_Storage plugin if you have them

Thank you very much i am yet to get the paid plugins i will update as soon as I do
