### ISSUE TITLE
Stream Key - Always the same

### ISSUE THREAD

**Issue by kikohdz** [WWBN/AVideo#2453]
Hello Daniel..  a small question..  is it possible to make the Stream Key that never change? .. i notice that when i restart the server it changes..   i want to be always the same..  

this is because we have to stream every day  and want to automate the process..  the computer start every day and opens the OBS automatically, and stream automatically as well..  

but sometimes the OBS dont start streaming beacuse the Stream Key has changed..  even if we did not restart the server.. 

hope you have a solution here... 

Many thanks and happy hollidays. !!!

![Anotación 2019-12-29 115757](https://user-images.githubusercontent.com/59340926/71560691-cfb99980-2a32-11ea-9256-c0e13ac64814.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, 

this key does not change when you restart the server.

it changes only when you click in the "Reset key" button
