### ISSUE TITLE
erro 500

### ISSUE THREAD

**Issue by apperm7** [WWBN/AVideo#2454]
BOA TARDE ! ESTOU TENDO DIFICULDADES DE HOSPEDAR POIS ESTA DANDO ERRO 500, INSTALEI VIA SERVIDOR NO MEU COMPUTADOR EM LOCALHOST E SUBI OS ARQUIVOS VIA FTP PELO FILEZILA EM UMA HOSPEDAGEM VPS QUE TENHO MAIS ESTA DANDO ERRO 500 MEU DOMINIO netvideon.com.br preciso resolver esse problema o mais rapido possivel pois meu objetivo é adquirir plugins para uma possivel locadora online do tipo netflix com mais inclementações.
Fico no aguardo. 
Desde de ja te agradeço.
Obrigado!!!

**Comment by DanielnetoDotCom** [comment]
Olá

para transferir os arquivos recomendo que você use o git clone.

é muito mais rápido e seguro mas tem que ser feito na linha de comando.

vai até o seu diretório do apache e faz assim:

`cd /var/www/html`

`git clone https://github.com/WWBN/AVideo.git`

depois se o erro persistir tenta ver no log o que é o erro 500, pra achar o log olha aqui https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by apperm7** [comment]
ENTÃO NÃO SEI SE ENTENDI CERTO. EU JA TENHO FUNCIONANDO NO MEU SERVIDOR EM LOCALHOST DO MEU PC MAIS AGORA QUERO HOSPEDAR NA MINHA VPS DE HOSPEDAGEM. TRANSFERI DO LOCALHOST DO MEU PC PARA MINHA HOSPEDAGEM VPS, ENTÃO SUBI OS ARQUIVOS VIA FTP PELO FILEZILA PARA MEU DOMINIO JA PROPAGADO NA MINHA VPS E ESTA DANDO ERRO 500, DETALHE ENTREI NO ARQUIVO DE ERRO DE LOG E ESTA ZERADO.


MEU 1° PROCEDIMENTO FOI EXATAMENTE CLONAR PELO GIT USANDO O SHELL DO APACHE E DIRECIONEI PARA O MEU LOCALHOST.

ESSE CAMINHO QUE ME ORIENTOU SERIA DIRETO DO GIT VIA SHELL DO APACHE PARA MINHA VPS, NO CASO PARA O DIRETORIO PUBLIC_HTML, É ISSO QUE QUIZ ME ORIENTAR?

**Comment by DanielnetoDotCom** [comment]
se voce fez modificações voce terá que usar os seus arquivos.

se voce quiser instalar a versao que disponibilizamos o git clone é melhor.

se seu log está vazio, olhe o log do apache.

**Comment by apperm7** [comment]
DANIEL NÃO SACO MUITO DO ASSUNTO. MAIS EU USEI GIT CLONE. É POSSIVEL USAR O GIT CLONE E DIRECIONAR DIRETO PARA O MEU SERVIDOR DE HOSPEDAGEM VPS?

**Comment by DanielnetoDotCom** [comment]
acredito que vc possa sim, mas vc vai ter que pesquisar no Google como fazer isso. Não tenho como explicar

**Comment by apperm7** [comment]
BOM DIA DANIEL
QNT CUSTA PARA FAZER A INSTALAÇÃO NUMA HOSPEDAGEM VPS, JA COM UM DOMINIO PROPAGADO?

**Comment by apperm7** [comment]
BOA TARDE DANIEL. O QUE FIZ AGORA: COMO JA TENHO O SITE AVideo FUNCIONADO NO LOCALHOST NO PC, ENTÃO EXPORTEI E IMPORTEI PARA O MEU BANCO DE DADOS DO MEU SERVIDOR, CRIANDO ASSIM UM BANCO DE DADOS. ACREDITO EU QUE PRECISO CONFIGURAR DIS ARQUIVOS, UM SERI O ARQUIVO DO TIPO conf, PARA ALTERAR SENHA E USUARIO E O ARQUIVO DE  configuração LA NO MEU PHPMYADMIN DO MEU SERVIDOR.

NO CASO QUAL SERIA ESSE ARQUIVO QUE conf. ONDE TENHO QUE ALTERAR SENHA E USUARIO?

**Comment by apperm7** [comment]
[
![image](https://user-images.githubusercontent.com/55334056/71589042-496c8880-2b02-11ea-9c6a-76be1badf61c.png)
](url)

**Comment by apperm7** [comment]
QUAL SERIA O ARQUIVO QUE EU POSSO ALTERAR SENHA E USUARIO?

**Comment by apperm7** [comment]
qual seria o preço apenas para instalação uma vez que ja tenho servidor de hospedagem VPS?

**Comment by apperm7** [comment]
ou qnt ficaria dessa forma Pack Pro Netflix
Instalação + alguns plug-ins?

**Comment by DanielnetoDotCom** [comment]
ola, te respondi no email

**Comment by apperm7** [comment]
boa tarde Daniel.
eu so quero instalar para adquirir os plugins logo em seguida mais esta dificil. esse erro so pode ser no arquivo . htaccess
erro 500, erro de incompatibilidade

**Comment by DanielnetoDotCom** [comment]
O erro 500 vc vai achar a resposta no log de erro sondei Apache

**Comment by apperm7** [comment]
BOA NOITE DANIEL. FELIZ ANO NOVO ANTES DE TUDO. OLHA EU ACHO QUE JA TENTEI DE TD MAIS NÃO CONSIGO INSTALAR, NÃO ACREDITO!! JA INSTALEI VARIAS VZS NO LOCALHOST NO MEU PC , MAIS NA MINHA VPS DE HOSPEDAGEM NÃO CONSEGUI. NÃO SEI MAIS O QUE FAZER.

**Comment by DanielnetoDotCom** [comment]
Ja te falei pra olhar no log do apache, se voce nao sabe como fazer olhe no google
