### ISSUE TITLE
rodape powred by 

### ISSUE THREAD

**Issue by apperm7** [WWBN/AVideo#2455]
BOA TARDE TEM UMA OPÇÃO DE EXCLUIR O RODAPE POWERED BY DO SITE. NÃO ME LEMBRO DA PASTA. 
FAVOR ME AJUDE!. 
OBRIGADO!!!!

**Comment by DanielnetoDotCom** [comment]
recomendo adiquirir o plugin Customize, é apenas 10 USD

**Comment by apperm7** [comment]
BOA TARDE DANIEL EU JA RESOLVI ESTA QUESTÃO. ME TIRA UMA DUVIDA TEM ALGUM PLUGIN QUE PODE TRANSMITIR UMA LIVE EM TEMPO REAL, UMA VIDEO CONFERENCIA AO VIVO EM TEMPO REAL? SERIA O PLUGIN SendRecordedToEncode?
