### ISSUE TITLE
issue in detecting SSL

### ISSUE THREAD

**Issue by ashrafpro** [WWBN/AVideo#2456]
You have an issue in detecting ssl version for sites using cloudflare.com, this prevent the creation of AVideo and user login after this, because you use $_SERVER['HTTPS'] for detecting SSL, and cloudflare returns this false while the site url starts with https
you should use $_SERVER["HTTP_X_FORWARDED_PROTO"] to get if site is using https

**Comment by DanielnetoDotCom** [comment]
I am not sure, but we have another problem with Cloudflare, you should avoid it

https://github.com/WWBN/AVideo/wiki/Using-CDN-for-Videos-Only#why-cant-we-use-cdn-direct-into-my-avideo-platform-site

**Comment by walt93** [comment]
Cloudflare have numerous problems even routing simple web traffic. 🙄
