### ISSUE TITLE
Your configurations has NOT been updated

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2459]
![image](https://user-images.githubusercontent.com/52116577/71609021-e6283800-2b8d-11ea-8902-856247f4f49e.png)

Any idea what could be this error ? 
I don't see anything on the logs

**Comment by DanielnetoDotCom** [comment]
I guess must be something in the log

but inspect the XHR in your browser

![image](https://user-images.githubusercontent.com/18009293/71621075-1979bf80-2bac-11ea-8c48-3c454c990f70.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Thanks for help .
```
{status: "error", message: "No write Access"}
status: "error"
message: "No write Access"
```

Can you tell me what file I have to give the permission ?
I managed to change the parameters from the DB only .

**Comment by DanielnetoDotCom** [comment]
hi, it is probably something in the videos directory
this action will try to overwrite the logo.

maybe your logo.png has no write access.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom So what is the solution ? Because i'm still not able to update anything

**Comment by akhilleusuggo** [comment]
PHP Notice:  Undefined index: theme in /var/www/html/YouPHPTube/objects/configurationUpdate.json.php on line 43

**Comment by DanielnetoDotCom** [comment]
Try to change permissions from all your videos directory

`chmod -R 777 /path/to/videos`

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I've done that already , and nothing changed ...

**Comment by DanielnetoDotCom** [comment]
Strange, 

Can you debug the php to find what exactly has no write permission?

I am away from pc now and I can not look into the code now

**Comment by akhilleusuggo** [comment]
Very strange :
`$config->setTheme($_POST['theme']);`

**Comment by DanielnetoDotCom** [comment]
Do you have all your files up to date without any customization or change?

here is the permission issue https://github.com/WWBN/AVideo/blob/80188faeb3ce8a3368e38165fe71acd3a7b06d1e/objects/configurationUpdate.json.php#L52

looks like your `videos/userPhoto/` does not have the right permission.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Yeh , I see you were right ! THank you !
