### ISSUE TITLE
Plugin Request or Pay for each Video?

### ISSUE THREAD

**Issue by Powerbock** [WWBN/AVideo#2460]
I am looking for a solution to sell videos on my platform.
I have a video on my site, and playing it should only be possible after the user has paid an amount "X" (as an example $ 4.95) via PayPal. With the available means this seems not to work (keyword membership). Could this be realized by a plugin, or do I have to look for another solution?

Kind Regards
Ronald

**Comment by akhilleusuggo** [comment]
PayPerView (( Create Pay Per View plans for your users ))
https://youphp.tube/plugins/

**Comment by Powerbock** [comment]
from the Wiki:
"With The Pay-per-view (PPV) plugin you can let your users purchase exclusively contents for a certain amount of time."

If I read it correctly, the user can do anything he wants within the purchased time. But I want him to be able to buy movie #1 for $4.99, and movie #2 for $9.99.
If I give him access for e.g. one day (if I read it correctly, the shortest time possible), he can buy anything that is available. Right or wrong?

**Comment by akhilleusuggo** [comment]
He will pay 4.99$ for EACH VIEW . Isn't that what you want ? Not that he can watch all your videos for 4.99$ . For that one is another plugin ( subscriptions and group users )
