### ISSUE TITLE
sprit_ID.jpg ( not getting removed )

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2467]
When the encoder ends encoding , before we had one problem with the HLS that were not getting deleted automatically . That was fixed . Now I have opened the encoder folder again , and I have found hundreds of sprit_ID.jpg

**Comment by DanielnetoDotCom** [comment]
I sent an update to delete files older then 1 day

It supposes to delete the file automatically, but is not for some unkown reason
