### ISSUE TITLE
HLS plugin hierarchy

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2468]
![image](https://user-images.githubusercontent.com/52116577/71663862-81243c00-2d5f-11ea-8354-67f8d2af6517.png)

Can you please change the hierarchy to be normal ? 240 , 360 , 480 , 720 , 1080 , 1440 , 2160

**Comment by DanielnetoDotCom** [comment]
Hi

I just sent an update to the plugin, can you please download **CLEAR YOUR BROWSER CACHE** and try again?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom No difference ...
I have re-downloaded the plugin , uploaded it , cleared the cache , tried it on different browsers / laptop and still nothing changed

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Any news about this ? It is working on your site ?

**Comment by DanielnetoDotCom** [comment]
No news yet, the main problem is because I can not reproduce it.

but I agree I have to make sure the values will be sorted.
