### ISSUE TITLE
zend_mm_heap corrupted

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#2470]
Hi Daniel, I have couple of issues I can't figure why my live page is not opening and I get this zend error now. I am not sure if it has a connection to the Live recording but for now I still cannot record any live streams and now I cannot even play them because the Live page hangs the entire site. I wasn't able to speak with you sooner because I also was on a holiday. Please let me know what I can do to fix this.

Also besides making regulare updates to the server I haven't touched anything in config files of apache or nginx.

Kind Regards,
Guy

**Comment by guymass** [comment]
Seems like the problem is only on Firefox.

**Comment by guymass** [comment]
Also, still getting Illigal Captcha error when trying to login with android mobile, There is no captcha on the login screen! none is displayed and still I get this error when trying to login which means that I cannot type in the captcha code and I cannot login with some of the android mobiles. I have just tested on a new LG5 installation downloaded a fresh YouPHPTube copy, installed, typed in my server, than it asked for username and password (only!) but when clicking Send i get Illigal Captcha error. Please fix this issue this is a major bug IMO.

**Comment by DanielnetoDotCom** [comment]
I do not know how many attempts did setup

![image](https://user-images.githubusercontent.com/18009293/71733185-bdbb6a80-2e27-11ea-9d3c-b68652df8b70.png)


but I am sending an update to avoid asking for the captcha on mobile devices too earlier.
