### ISSUE TITLE
Encoder upload from file - max size

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2473]
Hi,

is there a setting that allows me to set the "The encoder Max File Size is: 100.00MB" that is shown on the encoder uploader?

and when a file is selected that is larger than the permitted setting should the encoder give a warning message?

Reason is I added a 300mb file and the encoder goes through the whole process until it needs to copy the file to the local storage where it just failed.

If we could stop this at file selection then it would save bandwidth because someone can select any size file atm.

**Comment by DanielnetoDotCom** [comment]
Did you see that?

**Comment by millzee01** [comment]
Yes i saw this when looking into using CDN.  I basically just want to put a limiter on of 10mb per video and if the user tries to upload a larger video they are advised of the restriction.

**Comment by DanielnetoDotCom** [comment]
on Encoder it will not work, since the encoder is using the chunk upload.

**Comment by millzee01** [comment]
thanks, i'll keep php.ini set to 100mb.
