### ISSUE TITLE
video gifs are acting up for no reason

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2476]
![image](https://user-images.githubusercontent.com/28763945/71752443-61843500-2e7f-11ea-8027-2e523f582540.png)
![image](https://user-images.githubusercontent.com/28763945/71752459-6ba63380-2e7f-11ea-91a4-340ff490abaa.png)

**Comment by Wepwawetcode** [comment]
https://xstreaming.vip/
[03-Jan-2020 23:26:52 Europe/Berlin] PHP Notice:  Undefined variable: img_portrait in /var/www/html/xStreaming/view/modeYoutubeBottom.php on line 38

**Comment by Wepwawetcode** [comment]
![image](https://user-images.githubusercontent.com/28763945/71753492-10764000-2e83-11ea-8a13-94ccdc67e70c.png)

![image](https://user-images.githubusercontent.com/28763945/71753499-1704b780-2e83-11ea-961b-27ec38b03ca0.png)

**Comment by Wepwawetcode** [comment]
tried a fresh install didnot change anything.

**Comment by DanielnetoDotCom** [comment]
what is your site URL?

**Comment by akhilleusuggo** [comment]
I'm having the same issue Daniel

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/71836192-40f4ee80-30bc-11ea-846f-43148c917074.png)

**Comment by Wepwawetcode** [comment]
https://xstreaming.vip/


Op ma 6 jan. 2020 om 18:39 schreef akhilleusuggo <notifications@github.com>:

**Comment by DanielnetoDotCom** [comment]
there is a specific page or browser that this happen?

I open your site and it was fine here

**Comment by Wepwawetcode** [comment]
Chrome. On the homepage. 

Verstuurd vanaf mijn iPhone

**Comment by akhilleusuggo** [comment]
Well it's true . I tried on different browsers and this is happening only in chrome . Chrome does support webp perfectly but this ''bug'' is weird

**Comment by Wepwawetcode** [comment]
Yup it doesn’t happen on my chrome browser on laptop.

Verstuurd vanaf mijn iPhone

**Comment by Wepwawetcode** [comment]
Fixed it for some reason by putting the css in a different folder and changing the link to the css.

Verstuurd vanaf mijn iPhone
