### ISSUE TITLE
No categories are shown in the left menu,

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2477]
Use the link below to replicate,

https://avideo.com/?search=default

![image](https://user-images.githubusercontent.com/28763945/71753104-c6d92580-2e81-11ea-98cd-82104d54d0ac.png)

**Comment by DanielnetoDotCom** [comment]
Thanks

**Comment by Wepwawetcode** [comment]
not fixed yet please check again.

**Comment by DanielnetoDotCom** [comment]
Sorry you were right
