### ISSUE TITLE
Request: Move Subscription Row on Homepage to the top Row

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2478]
@DanielnetoDotCom Is there a way we can Move the Subscriptions to the top row on the homepage for logged in users?  Or maybe under the First row which is Trending

That way when a user is logged in and they go to the home page subscriptions will be the first thing they see.

It would be kewl for when logged out you see the **Category** rows but once logged in disable category rows and put **Subscription** rows at the top on home page.

**Comment by Wepwawetcode** [comment]
not that hard take a look at my site for an example https://xstreaming.vip/

**Comment by JoshWho** [comment]
U have it in maintenance mode. I can't see it.

 I want  this added to the core so it will be a option for everyone to switch and won't get overwritten when updates happen.

**Comment by Wepwawetcode** [comment]
ah yeah true

Op zo 5 jan. 2020 om 03:21 schreef JoshWho <notifications@github.com>:
