### ISSUE TITLE
Can't upload webp

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2480]
![image](https://user-images.githubusercontent.com/52116577/71784820-7cca7e00-3000-11ea-9cc7-4622ac16ca1a.png)
Logs:

```
[05-Jan-2020 19:13:35 UTC] PHP Warning:  move_uploaded_file(/var/www/html/YouPHPTube/videos/_YPTuniqid_5e0305e85ba632.75568353.webp): failed to open stream: Permission denied in /var/www/html/YouPHPTube/objects/uploadPoster.php on line 62
 55933  [05-Jan-2020 19:13:35 UTC] PHP Warning:  move_uploaded_file(): Unable to move '/tmp/phppDehdE' to '/var/www/html/YouPHPTube/videos/_YPTuniqid_5e0305e85ba632.75568353.webp' in /var/www/html/YouPHPTube/objects/uploadPoster.php on line 62
 55934  [05-Jan-2020 19:13:35 UTC] PHP Notice:  Undefined variable: filename in /var/www/html/YouPHPTube/objects/uploadPoster.php on line 63
```

 `PHP Warning:  move_uploaded_file(): Unable to move '/tmp/phppDehdE' `
I have tried to chmod 777 /tmp/ , but no changes , still the same errors

**Comment by DanielnetoDotCom** [comment]
Basically your error is this  `PHP Warning:  move_uploaded_file(): Unable to move '/tmp`

and it is specific from your server, you should check your server configurations and try to google for that

**Comment by akhilleusuggo** [comment]
If someone having this same error in the future 
I've solved this problem by : 
`sudo chown -R www-data:www-data /var/www/html/`
