### ISSUE TITLE
PHP Warning:  Cannot use a scalar value as an array

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2486]
`PHP Warning:  Cannot use a scalar value as an array in /var/www/html/YouPHPTube/objects/functions.php on line 2476`

**Comment by DanielnetoDotCom** [comment]
I am not sure what causes this, but I sent an update to make sure this will not happen again

**Comment by akhilleusuggo** [comment]
looks like fixed ! Thanks
