### ISSUE TITLE
Send Verification Mail Automatic - FIX

### ISSUE THREAD

**Issue by republicus** [WWBN/AVideo#2489]
I hope to start contributing my fixes very soon, especially now that I have managed to resolve transferring my old setup to new servers and ironing out all my own bugs.

But I wanted to share this here so maybe the fix can be verified and pushed in my stead.

New users were not getting verification emails upon account creation. If they logged into their account after, they could access their My Account and successfully request a verification email be resent manually.

So then I knew my email server was configured properly and SMTP/AUTH in AVideo was also working. 

After checking avideo.log I saw:
`PHP Notice:  Undefined variable: global in /var/www/html/avideo/plugin/CustomizeUser/CustomizeUser.php on line 256`

And noticed that function was missing as all the other functions:
`global $global;`

adding that line before line 256 resolved my issues and emails appear to be sending upon account creation.

**Comment by DanielnetoDotCom** [comment]
thanks you were right. I just sent this fix
