### ISSUE TITLE
Encoder does encode the same video multiple times 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2493]
This isn't the first time . When I check why some videos are encoding so slow I find that THE SAME FILE are bein encoded multiple times . Met me explain with some screenshots :

![image](https://user-images.githubusercontent.com/52116577/71852242-f46fda00-30e0-11ea-8232-8d6bbfca46ea.png)
 In this screen we can see that the file has been downloaded x2 times ( It should be only 1! )
![image](https://user-images.githubusercontent.com/52116577/71852503-8546b580-30e1-11ea-846b-c0c658e52a66.png)

On htop is the same . I can see clearly that they're not under the same PID

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/71866665-a920f000-310f-11ea-9c03-1ccab3e1d932.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure how is this happening and how to reproduce it.

there is a way that you can describe, so I can reproduce it on my side?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom There's really nothing to describe . No logs nothing except what I've sent you up .
I just uploaded a video to the encoder , and tracking the activity and looking that it's taking too long with 16 cores and a lot of space , I started looking everywhere and I saw that this error happens and I need to find the problem source . 
Now that i'm using GPU , I managed to stop this by disabling parallel encoding . Only 1 file can be encoded at the same time .But still happens that some random encoding are using power to encode files into ( for example ) /video/1_tmpFile_Converted ; when I to check that folder , that folder doesn't even exists
