### ISSUE TITLE
Subscribes needs to become My Subscribers

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2494]
The Subscription button in the left menu should say **My Subscribers** and Also the list on the page should say **My Subscribers** as well.

<img src="https://static.buddylist.co/x/mysubs2.png" style='width:100%;' border="0" alt="Null">

<img src="https://static.buddylist.co/x/mysubs.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
Yes I agree :) I am sending an Update

**Comment by JoshWho** [comment]
I just did the update. I see the new text in the page above the subs list but the Button in the Left Menu still shows Subscriptions.  That should say **Subscribers** or **My SUbscribers** as well.

<img src="https://static.buddylist.co/subs.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
Ok, fixed

**Comment by JoshWho** [comment]
Looks good. Thank you @DanielnetoDotCom

**Comment by JoshWho** [comment]
Yes it is now in the latest update.

**Comment by heiress01** [comment]
Newby here how do you do that?

**Comment by JoshWho** [comment]
It is a switch in the live plugin you can turn on and off.

**Comment by JoshWho** [comment]
go to your website directory on ssh an run this

1 - Git Pull (Recommended)
go to your YouPHPTube dir and type git pull

cd /var/www/html/YouPHPTube/ && sudo git pull

In the simplest terms, git pull does a git fetch followed by a git merge.

You can do a git fetch at any time to update your remote-tracking branches under refs/remotes//.

This operation never changes any of your own local branches under refs/heads, and is safe to do without changing your working copy. I have even heard of people running git fetch periodically in a cron job in the background (although I wouldn’t recommend doing this).

A git pull is what you would do to bring a local branch up-to-date with its remote version, while also updating your other remote-tracking branches.

Git Documentation

Problems:
Some users some times change a file, and can not do a git pull command, usually they get this error:

… Please, commit your changes or stash them before you can merge. Aborting
the solution is to force to overwrite your files, you can do this command.

git fetch --all && git reset --hard origin/master

Check this video to know how to do it: https://tutorials.youphptube.com/video/force-git-to-overwrite-files

2 - Download and Upload files
Use your favorite file transfer to download a master copy of YouPHPTube and upload it to your site.

Unzip it and replace all files in your YouPHPTube-root. Do not clear or replace the videos-folder.

Always - Database-update!
Remember, always check your YouPHPTube menu -> Update version to run a script update. Never skip a version!

**Comment by heiress01** [comment]
Ok thanks
