### ISSUE TITLE
Live, failed to connect to the server

### ISSUE THREAD

**Issue by SICPRO** [WWBN/AVideo#2498]
in order not to describe the problem for a long time, I recorded everything on video.
http://grubtime.top/Untitled.mp4
I use virtual hosting. Please help

**Comment by DanielnetoDotCom** [comment]
Your video link does not open.

and you should check the log for nignx and for the streamer

**Comment by SICPRO** [comment]
sorry, I already deleted the video file. Installed the script, installed the tables, and enabled the script. But OBS says the server is unavailable

**Comment by akhilleusuggo** [comment]
@SICPRO You need to install/start nginx rtmp module . More information here https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server
