### ISSUE TITLE
Error uploading videos to my streaming server.

### ISSUE THREAD

**Issue by risleem** [WWBN/AVideo#2499]
I am getting an error when uploading a video on my streamer and encoder server. This is the error I am getting.
/var/www/html/YouPHPTube/objects/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer not writable please chmod to 777. Any help would be appreciate. Thanks

![image](https://user-images.githubusercontent.com/52410929/71985365-79014c00-31f8-11ea-919b-13b3b3a8f760.png)

**Comment by akhilleusuggo** [comment]
It is hard to read what they're asking you ?
`chmod 777 /var/www/html/YouPHPTube/objects/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer`

**Comment by risleem** [comment]
I am getting an error when uploading a video on my streamer and encoder
server. This is the error I am getting.
/var/www/html/YouPHPTube/objects/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer
not writable please chmod to 777. Any help would be appreciate. Thanks

image

**Comment by millzee01** [comment]
run this on your console:
`sudo chmod 777 /var/www/html/YouPHPTube/objects/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer`
