### ISSUE TITLE
Links being forgotten after login

### ISSUE THREAD

**Issue by JSY-Ben** [WWBN/AVideo#2502]
Hi there :)

As always, thanks for this project. It's a fantastic tool.

I'm having an issue where with the 'User Must Be Logged in' setting turned on and LDAP authentication, if a user tries to use a link to go directly to a video, after they enter their LDAP login details, it goes straight to the homepage.

Do you know if there is any way for the link to be remembered and followed after the user logs in after clicking a link?

Many thanks again
Ben

**Comment by DanielnetoDotCom** [comment]
It should do the trick

**Comment by JSY-Ben** [comment]
Many thanks for the work, but unfortunately not.

If it helps, i'm using the Gallery plugin as a front page and LDAP plugin as login. When a link is clicked on with 'usermustbeloggedin' enabled, for example:

https://hightube.highlands.ac.uk/streamer/video/5181/acting-to-camera-session-wednesday-8th-january-2020

The link changes automatically to this when the login page appears:

https://hightube.highlands.ac.uk/streamer/user

Then when login has gone through, the gallery homepage appears and the link reverts to this:

https://hightube.highlands.ac.uk/streamer/

Many thanks again
Ben
