### ISSUE TITLE
Automated plugin delivery

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2503]
Hi, i purchased a plugin yesterday and posted an inquiry on your site chat system a week ago but had no response from either.   

have checked spam and sent you an an email.

I did get an automated email saying daniel would send me an email after i purchased the plugin but had nothing back.   Wouldn't it be a good idea to automate the plugin delivery? or is there a download section somewhere on your site that allows me to download the plugin i brought?

**Comment by DanielnetoDotCom** [comment]
Hi

you must go back to the plugins site and login on it.

you will see a download button on the purchased plugin.

follow this to install the plugin. https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin

**Comment by millzee01** [comment]
lol what an idiot I am, didn't see that.

thanks again!
