### ISSUE TITLE
catalog selection - upload a file

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2504]
Hi, is there a way I can turn on catalog selection in the mini-upload-form?  

similar to the catalog selection dropdown on the encoder

**Comment by DanielnetoDotCom** [comment]
can you please give me more details of what do you mean?

**Comment by akhilleusuggo** [comment]
I think he means , to not have on your face the upload , but to have it minimized . ( direct upload )

**Comment by millzee01** [comment]
Hi, when you click "Upload a file" the video form has a "drop here | Browse" form which allows you to browse and select a file.  It would be handy if we can add a catalog selection so when the file is updated it is placed into the correct category instead of having to edit the uploaded video.

**Comment by DanielnetoDotCom** [comment]
I guess you have those options on Encoder
