### ISSUE TITLE
VIdeo Descriptions are all running together 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2506]
I can't figure out why video descriptions are not detecting return lines and just running everything together.

I do not have Article plugin enabled not sure why it changed all of a sudden.

You can see what I am talking about here [https://www.joshwhotv.com/v/15504?channelName=SeekingTheTruth](https://www.joshwhotv.com/v/15504?channelName=SeekingTheTruth)

**Comment by DanielnetoDotCom** [comment]
please try it now.

**Comment by DanielnetoDotCom** [comment]
Do not forget to update

**Comment by JoshWho** [comment]
Thank you. Looks perfect now.
