### ISSUE TITLE
Remove icon from category 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2507]
I'm not able to find a way to remove an icon from category without deleting all the category with sub-categories ...

**Comment by republicus** [comment]
Changing the icon on an existing category works. Try searching for **rendact** to filter to an empty icon.

**Comment by akhilleusuggo** [comment]
@republicus Yes but it's still taking space ...

**Comment by DanielnetoDotCom** [comment]
Maybe you can use a CSS with display none to hide the Icons
