### ISSUE TITLE
remove users or have a user deactive an account

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2508]
Is there a way a user can deactivate  their account. sort of like what twitter does. Keeps the account inactive for 30 days then deletes the account entirely after the 30 days. If not is there a way I can code a deactivation button into the dashboard.

**Comment by akhilleusuggo** [comment]
again , same thing like I've commented on your other post ... 

                      
![admin](https://user-images.githubusercontent.com/52116577/72177564-a103d180-33e9-11ea-89ca-5c2ecfce627a.png)

You can remove the account by one click , or disabled it
