### ISSUE TITLE
User account Creation

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#2509]
Is there an option in the script that I can manually review channels before they become active. More like an application process and my team and approve or deny the channel

**Comment by akhilleusuggo** [comment]
Yes , you can go to users and manually approve them or not . 
![admin](https://user-images.githubusercontent.com/52116577/72177507-7d408b80-33e9-11ea-937d-305d5a35dacb.png)

**Comment by venwebsites** [comment]
excellent thank you..Can you tell me what check mark 1 2 and 3 represent

**Comment by republicus** [comment]
Check marks 1,2,3 are to to signify a valued user.
Like many social sites have _Verified_ users.
You can define the marks in the CustomizeUser plugin (very bottom).

**Comment by venwebsites** [comment]
ok. I thought it gave the users the option to deactivate their account
