### ISSUE TITLE
Sitemap.xml & Private videos

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#2511]
Hi

Is it possible to exclude private videos in Sitemap.xml ?

**Comment by akhilleusuggo** [comment]
That's a great idea , but the sitemap need to be updated after each upload I guess

**Comment by DanielnetoDotCom** [comment]
On Customize advanced plugin look for the option and showPrivateVideosOnSitemap
By default it is off now 

Off = no private videos
On = All videos

the rebuild your sitemap

**Comment by TLCReuver** [comment]
Hi Daniel

Great, i found it. 
Many thanks.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom What about unlisted ? The private videos even if found by bots will not play , but unlisted could still be found , can you add the option for that too ? Thanks

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo agree, I sent an update
