### ISSUE TITLE
youtube-dl problem with  Web Servers: nginx-varnish-apache

### ISSUE THREAD

**Issue by alimusa80** [WWBN/AVideo#2512]
We could not get the title of your video (youtube video) go to Update your Youtube-DL to fix it

 Note: I have alread installed the latest and update the youtube-dl, my server is Centos 7 not Ubuntu can any one tell what  am i missing to submited to the streamer site the video, 

Note the streamer site an the encoder site with installled ffmpeg are working but when ever i need to use my encoder site to submited to the streamer site any video i got the above error

**Comment by akhilleusuggo** [comment]
Probably you've got banned from the source you're trying to download . This happens to me many times when I was using a cheap provider . Those IP are black listed for abuse . If you're getting error 404 ( when executing youtube-dl on terminal ) ; you need to wait X times before download again .
Anyway if you need help is not here . You need to write to youtube-dl not on this git

**Comment by alimusa80** [comment]
thank for your reply dear, I am not using ´cheap host dear, the server is based on my home and i build myself

CPU Model: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
CPU Details: 32 Core (1200 MHz)
ram 128GB
Distro Name: CentOS Linux release 7.7.1908 (Core)
Kernel Version: 3.10.0-1062.9.1.el7.x86_64

internet speed 1GB speed, 

my question is might be the AVideo dont work well with Centos 7, do i need to use the Ubuntu instead of Centos  dear

**Comment by akhilleusuggo** [comment]
@alimusa80 No , but can you link the output ? What error are you getting ?
Run on terminal `youtube-dl -f best LINK`
Just I wanna remind you that if you were trying to download a playlist is doesn't work on this script . 
More info here https://github.com/WWBN/AVideo/wiki/Import-a-Full-playlist-from-Youtube
