### ISSUE TITLE
Error in your SQL syntax

### ISSUE THREAD

**Issue by angelawong** [WWBN/AVideo#2513]
I am trying to do a clean install but I keep getting this error:
`Error creating database: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-avideo' at line 1`

Please advise. Thank you.

**Comment by DanielnetoDotCom** [comment]
I can not reproduce this error, is it for encoder or streamer?

can you please paste the complete log here?

**Comment by angelawong** [comment]
Daniel,

This is for the streamer. Please excuse my ignorance, but where do I find the logs? I could not get past the installation page because of the error.

Thanks so much,
Angela

**Comment by DanielnetoDotCom** [comment]
Please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by angelawong** [comment]
I have looked at all the places recommended by your link but there was nothing to be found.

This was the error I found when I created a database and just chose to add tables only:
Error performing query '<strong> 
ALTER TABLE `videos` 
ADD INDEX `videos_status_index` (`status` ASC), 
ADD INDEX `is_suggested_index` (`isSuggested` ASC), 
ADD INDEX `views_count_index` (`views_count` ASC), 
ADD INDEX `filename_index` (`filename` ASC); 
': Specified key was too long; max key length is 767 bytes<br /><br />

I downloaded the application via git and did the following before running the install:
$ git clone https://github.com/YouPHPTube/YouPHPTube.git
$ sudo chown www-data:www-data /var/www/vhosts/outreach/html/YouPHPTube/videos && chmod 755 /var/www/vhosts/outreach/html/YouPHPTube/videos

Any help or advice would be most appreciated.

Thank you.

**Comment by DanielnetoDotCom** [comment]
check here https://github.com/WWBN/AVideo/issues/649

**Comment by angelawong** [comment]
Thanks Daniel. Yes, it was a MariaDB problem. Once I upgraded it from 10.1 to 10.2 and upwards, it worked like a charm. Thank you so much!
