### ISSUE TITLE
Youtube Embed does not need autoplay causes spinning circle

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2514]
Auto Play is not needed on yt embeds that already auto play. this is causing a spinning circle to stay in the middle of the video until you advance the video forward, backwards, or pause and play again to make the circle go away.

<img src="https://static.buddylist.co/spin.png" style='width:100%;' border="0" alt="Null">

see this video for example: https://www.joshwhotv.com/v/2027?channelName=JoshWho+TV

**Comment by DanielnetoDotCom** [comment]
Hi, do you mean to remove the autoplay command from the embed youtube videos only?

are you sure that is the problem?

**Comment by JoshWho** [comment]
Im not 100% sure about that.

**Comment by DanielnetoDotCom** [comment]
please paste here a URL sample so I can make some tests

**Comment by JoshWho** [comment]
https://www.joshwhotv.com/v/2027?channelName=JoshWho+TV

**Comment by DanielnetoDotCom** [comment]
I am not sure if will works but I found this error 

`Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://www.youtube.com’) does not match the recipient window’s origin (‘https://www.joshwhotv.com’).`

I follow this to try to fix https://stackoverflow.com/questions/27573017/failed-to-execute-postmessage-on-domwindow-https-www-youtube-com-http

does this persist if you remove the video ads?

**Comment by JoshWho** [comment]
No, not as much. It is rare to see when video ads are disabled. Once in a blue moon i will see it without video ads on but this mostly only happens when the vast server is enabled.

**Comment by DanielnetoDotCom** [comment]
Yes, that is what I mean, if you disable the VAST server will this video work?

**Comment by JoshWho** [comment]
correct

**Comment by DanielnetoDotCom** [comment]
Hi, I think I got it now.
Bu can you please confirm if the ads still playing?

**Comment by JoshWho** [comment]
I think u got it. Looking good now.

**Comment by DanielnetoDotCom** [comment]
Great, just to make it clear that was a browser restriction with this error

`Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted.
`
so now I try to play once, if does not play I mute the video and play again.
