### ISSUE TITLE
Encoder Utility Dependencies at /usr/local/bin, not recognized by installer

### ISSUE THREAD

**Issue by GreggShimokura** [WWBN/AVideo#2516]
Hi,
I am a new user and have successfully installed the streamer at it is working fine. 

I have started the installation of the AVideo-Encoder and have found the installer cannot find `ffmpeg`, `exiftool` and `youtube-dl` on my server (Mac OS) even though they exist at /usr/local/bin.  

Is there a way to tell/configure the installer with my path to these utilities?

Gregg

**Comment by akhilleusuggo** [comment]
You'll need to change the PATH ; you can google it or remove ffmpeg and install it again .
Making it easier for you : 
```
sudo apt-get --purge remove libav-tools
sudo apt-get --purge autoremove

```
Then `sudo apt install ffmpeg `

**Comment by akhilleusuggo** [comment]
Oh wait ... Mac OS , I didn't saw that . I don't knew then .

**Comment by GreggShimokura** [comment]
Hi.  
Thanks for the reply. 

What is the path that Avideo is expecting?

Else is there a place in the code I can change to my path?

Gregg

**Comment by akhilleusuggo** [comment]
nono , you need to change the path of ffmpeg on your OS . Type ffmpeg , if you don't get any output that means the path is wrong or your user doesn't have the correct path the ffmpeg folder .

**Comment by GreggShimokura** [comment]
Ok thanks.  I do get output when I run say 
`$ ffmpeg -version
ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers
built with Apple LLVM version 7.0.2 (clang-700.1.81)
configuration: --prefix=/usr/local/Cellar/ffmpeg/3.4.2 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --disable-jack --enable-gpl --enable-ffplay --enable-frei0r --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-librtmp --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags=-I/usr/local/Cellar/openjpeg/2.3.0/include/openjpeg-2.3 --enable-nonfree
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100
$` 

I have been looking at the code and I have seen that there is a shell_exec command inside the object/functions.php code that executes 'which ffmpeg'.  

The issue now is that as a 'user', this command works fine as per the above or if I run as a user:
`$ which ffmpeg
/usr/local/bin/ffmpeg
$`

This is is because my user search path includes `/usr/local/bin`.

However, when executed from within PHP the search path that the code uses does not include `/usr/local/bin`. 

I am looking to see if I can find where in your code the search path for the utilities is set (if it is set).

Else if you have other suggestions I am open to trying.

Gregg

**Comment by akhilleusuggo** [comment]
Because this script is for linux ( ubtuntu ) . I have never used MacOs so I can't help you
Google how to give access to www:data ( ffmpeg )
On ubuntu copy the ffmpeg binary from `~/bin` to `/usr/local/bin`

Take a look to this https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu
You will need to compile it manually if you wanna make it work . First purge everything .
Good luck :)

**Comment by GreggShimokura** [comment]
Thanks.
I got it to work by hard coding the paths inside objects/function.php.
```
$ grep shell_exec functions.php 
//    return trim(shell_exec('which ffmpeg'));
    return trim(shell_exec('which /usr/local/bin/ffmpeg'));
    return trim(shell_exec('which /usr/local/bin/youtube-dl'));
    return trim(shell_exec('which /usr/local/bin/exiftool'));
$ 
```

MacOS is a variant of Unix so it is a bit of a mystery to me why the `shell_exec` does not work as expected.

Gregg
