### ISSUE TITLE
where can I find the line of code what makes this url works so weird?

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2519]
![image](https://user-images.githubusercontent.com/28763945/72437625-6f04bd80-37a3-11ea-93e3-93ff309f04cf.png)

![image](https://user-images.githubusercontent.com/28763945/72437676-893e9b80-37a3-11ea-8281-8fb58178f650.png)
it happens if you hover over the big video.

**Comment by DanielnetoDotCom** [comment]
If you update your code the parentOnly variable will be removed

You can use SEO links now that you can change the title with no problem to loose the old links

![image](https://user-images.githubusercontent.com/18009293/72439859-79648e80-3786-11ea-8452-669e81388877.png)
