### ISSUE TITLE
AVideo 'Programs' and 'Tags' - Intended Usage

### ISSUE THREAD

**Issue by GreggShimokura** [WWBN/AVideo#2520]
Hi,
I have gotten a fully working streamer and encoder on my Mac Mini and all seems great so far.

As I load up my content I have seen a few features that could be useful for filtering/sorting and customizing content for different users/audiences and I was wondering how they are intended to work and/or where they are documented.

1. Categories
This is pretty clear.  No questions here so far.

2. Programs (Playlist) Plugin
I have enabled this and can add videos to different Programs however:

- Where does a user access the Program/Playlist?
- Is this a Paid Feature?

3. VideoTags Plugin
I have enabled this and can add tags in the Admin/Plugin panel

- Where does a user access/user/sort videos using the tags?
- Is this a Paid Feature?

Thanks,

Gregg

**Comment by akhilleusuggo** [comment]
All of them are free . The playlist does display on channels ( just check them down )
If you create a tag and watch a video , you can see the tags of the video under the video player . Click on 1 tag and you gonna see all the videos with the same tag

**Comment by GreggShimokura** [comment]
Thanks for the answer.
When you say 'under the video player' I am not seeing what you mean?  
Is there a setting to enable to see the tags?

Attached is what I see when I click on play.

Gregg
<img width="558" alt="Screenshot 2020-01-15 15 36 44" src="https://user-images.githubusercontent.com/33208281/72480665-fefb3500-37ac-11ea-9cfa-499c3ae756eb.png">

**Comment by GreggShimokura** [comment]
Hi Again,
I have done some digging and have now been able to understand how the tags should work.
However, I had to manually enter an example tag into the MYSQL database directly.

### Question
Where in AVideo are the actual tags defined?  (I only see the Tags Type definition on the PlugIn page). 

### Playlists
I see now that the Playlists are listed on `My Channel` page.  This was my problem as I was looking only at the `Home` page.  No remaining issues on Playlists.

### Channels
No remaining issues on Channels.

Thank you,

Gregg

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/72493808-a9656d80-382a-11ea-8146-907bfaa52126.png)
![image](https://user-images.githubusercontent.com/52116577/72493834-c437e200-382a-11ea-8387-0169addc6d44.png)

**Comment by GreggShimokura** [comment]
Thanks.
My question is to know how to get  the 'test' tag defined to be chosen.  

Right now if I enter text into that box, nothing happens.   I might expect it to turn into the blue oval tag symbol you are showing.

Also I don't see a way to select from existing tags..  Is there a way to select from already existing tags?  I don't think it is a good idea to have users create tags when not needed or making a small typo.. (ie typing `text` instead of `test` and creating new un-needed tags).

**Comment by TLCReuver** [comment]
Hi,
In your sample just type in the  your classfield:

Birds (press enter)
Mammals (press enter)
Insects (press enter)

All your tags become a blue background color and you have only to save your video.

All your created tags are known in all your videos. Edit another video and edit the Class-field and type the letter B and it shows the tag "Birds". If that doesn't work, close your browser and open it again and try once again. I noticed that new tags not found untill you restart your browser.

**Comment by GreggShimokura** [comment]
Thanks.
Reopening the browser has solved seeing any new tags I have added manually to the MYSQL database.  Typing the first letter for an existing tag brings up a popup list - this works nicely.

However, when I try adding a new tag name in the Class-field (say Molluscs) it does not create a new tag (I look in the MYSQL database).

I don't see any error in ../avideo/videos/video.log or video.js.log.

Is there somewhere else I can look to see what the problem is?

Gregg
