### ISSUE TITLE
How do I limit access to videos to paid subscribers?

### ISSUE THREAD

**Issue by SoapTube** [WWBN/AVideo#2521]
I only want paid subscribers to have access to videos. 

What does "Only Paid User Can see" do? Even with it toggled on, anyone can watch the videos, paid or not. They don't even have to be logged in. 

When I toggle both Only Paid User Can see and Public Media to off and toggle "Subscribers" on, nothing. It is still viewable by anyone whether logged in or not, paid or not.

The only time access is limited to paid users only is when I have both Only Paid users can see on and public media off with subscribers on is access limited.

What are these toggles supposed to do?

SoapTube.TV

**Comment by SoapTube** [comment]
How do I make it so users can't change the user group their videos are in? If they can change the user group for their videos, they can make them free.

SoapTube.TV

**Comment by DanielnetoDotCom** [comment]
Hi, 

Are you using PPV or Subscription?

**Comment by SoapTube** [comment]
subscription

**Comment by DanielnetoDotCom** [comment]
Hi, now I understand what do you mean.

I just add an option for you to disable the ability to change user groups. (Only admin will be able to do)

In the customize user plugin look for the option **userCanNotChangeUserGroup** and check it.
