### ISSUE TITLE
Encoder Feature Request:  Descriptions Mandatory

### ISSUE THREAD

**Issue by KenRHill** [WWBN/AVideo#2522]
I would like to request a feature update to the Encoder.  Is there a way to make a title and description text mandatory before videos can be uploaded on the Encoder?  A way to control minimum character count would be nice as well.  I want to reduce the number of videos that are uploaded without having any description or much of a title present. I sometimes get users that are just uploading videos without putting any description and just have 2 or 3 characters as the title.

**Comment by DanielnetoDotCom** [comment]
Hi, sorry we do not have this option now.

the only way to force it is coding.

If you want we can quote the development for you.
