### ISSUE TITLE
Email Verification needs a Timer between retries

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2524]
I am having a issue when users signing up used the wrong or incorrect email address and then they keep clicking resend over and over again getting my mail server block for excessive sending email to a non valid address.

I mostly blame the host running my email server for this stupidity not recognizing some email being a bad email address and instead of blocking the email it blocks my server sending all mail. 

The resend verification email button needs to work once every 30 minutes or something like that.

**Comment by DanielnetoDotCom** [comment]
Hi, Is not tested but I guess it will do the trick

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom .
