### ISSUE TITLE
User Download How TO

### ISSUE THREAD

**Issue by GreggShimokura** [WWBN/AVideo#2526]
Hi Again

I am having trouble allowing users to download videos from other Users/Channels.

### Setup
See attached but basically
1. Downloads enabled in CustomizeUser Plugin Parameters
2. Downloads enabled on User Channel Page
3. Downloads enabled in Site Settings/Advanced Configuration
4. Individual Video Download Enabled

### Symptoms:
- I don't see a button anywhere when playing a video
- Right click on a video has no effect

I rebooted my system and restarted my browsers.  Tried Chrome and Safari.

### Questions
1. Is the setup correct?
2. How can I debug?

Thanks,

Gregg
<img width="417" alt="Screenshot 2020-01-16 15 13 41" src="https://user-images.githubusercontent.com/33208281/72571169-b5295200-3873-11ea-85a5-800558469821.png">
<img width="295" alt="Screenshot 2020-01-16 15 15 38" src="https://user-images.githubusercontent.com/33208281/72571170-b5295200-3873-11ea-92e1-f0180796edd3.png">
<img width="339" alt="Screenshot 2020-01-16 15 15 57" src="https://user-images.githubusercontent.com/33208281/72571171-b5295200-3873-11ea-8f1a-62d9500cfa62.png">
<img width="432" alt="Screenshot 2020-01-16 15 22 13" src="https://user-images.githubusercontent.com/33208281/72571284-02a5bf00-3874-11ea-9061-c656452fc408.png">

**Comment by DanielnetoDotCom** [comment]
what is the video link of the video you are trying to download.

Just to make it clear, is not possible to download embed videos.

**Comment by GreggShimokura** [comment]
Hi
All videos are local in that they have been encoded and uploaded using a local install of AVideo-encoder. 

Gregg

**Comment by GreggShimokura** [comment]
Closing Issue.  I think it is working but not as I was expecting.

I was hoping that a download button would be available in the player controls that appear at the bottom of the player.  Download from the player is useful for those on a slow connection that cannot keep the stream going so if a video becomes choppy due to lag, a download button from the player would be useful.

If it was intended to download only from a program, then it is not very convenient.  If the user is exploring new content and finds something, then there is an extra few steps of creating a program first before getting access to the download button I see there.

Maybe I don't understand how it is supposed to work.

Gregg

**Comment by guymass** [comment]
I would also like to understand how download works as I also have enabled all the options in all places and still I cannot see a button to download.
