### ISSUE TITLE
The encoder is really getting me frustrated!

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2527]
![Screenshot from 2020-01-17 07-18-49](https://user-images.githubusercontent.com/52116577/72586350-0ed45f80-38fa-11ea-84a9-530d63aff1d5.png)

Again , and again and again , the same input file getting transcoded into multiple different folders tmp_folders that doesn't even exist .
This problem happens very often and uses a lot of resources . Happens when downloading the file to get encoded . For some reason , the file to be transcoded get downloaded more then once . Like the screen below , and the encoder make unnecessary transocodes . Not only that , when the file is sent to the streaming server , it does fail . Why ? Because the folder containing the encryption key is different ! 

![tmpdownload](https://user-images.githubusercontent.com/52116577/72586770-8fe02680-38fb-11ea-9c51-d8e335ccf416.png)
![enc_key](https://user-images.githubusercontent.com/52116577/72586781-92428080-38fb-11ea-992e-5e1c91d50b28.png)

I don't even know how to debug this case . I just can't see it on logs .
PS: The extra transcoding that are pointing to a non existing path , keep just looping . The process is using CPU/GPU for transcoding , but never ends . I've tried it with a clip of 30s , and it's there for hours . Just never end , just using power of encoding

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo this is also new for me and I am not sure how to debug.

what I suggest (If you have some PHP Skills) is to edit the PHP files that download and encode to write in the log file everytime they are called.

with that I expect to have some clue what is going on. maybe fo realize why it is being calling more then once. from who?

**Comment by JoshWho** [comment]
Copy and paste your encoders configuration line for the ffmpeg. I want to see what commands are being issued.

**Comment by akhilleusuggo** [comment]
@JoshWho This issue has nothing to do with it . I've tried with the default ffmpeg commands ( the one that comes with script ) and same issue .
It happens randomly , and the hardware here has nothing to do with the problem 
Tried with GPU ( nvenc ) , iGPU ( quick sync ) , X264 ( software encoding ) , all of them gives sometimes this random error .
This is happening to all , not only me , just you don't notice it maybe . I do , because I have long videos duration on my streaming site , stream of +2h , so when I see that after 24h still encoding the same video ... I've checked and found that the same video is encoding x7 times .
Then I've started taking a look more closely

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I think I have a clue what could be causing this issue . 
The login . When I log multiple time to the encoder and I just close the tab without signing out , this issue appears .
Does download twice ( as if 2 IDs requested it , or more , depends on how much time I've logged in )
Also encoded multiple times . And generated multiples enc_keys . Ofc the video does stop every time , since they don't use the same enc_key and the token does block them . They load , but doesn't play .

Also , when you login , you can do with with password ( normal ) or with the hash pass md5 encrypted .

What I would recommend to start with , is to automatically log out the user after closing the tab , also to not cache the login .
