### ISSUE TITLE
Video's description .

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2528]
The video's description when it's too long , need an option to make it shot . For example on youtube the long descriptions look like this : 
![show more](https://user-images.githubusercontent.com/52116577/72595569-cb3a1f80-3912-11ea-8837-82bfd4e7bc6e.png)

For now, if the user's descriptions is too long gonna look like this : 
![no show more](https://user-images.githubusercontent.com/52116577/72595619-e7d65780-3912-11ea-9f08-5a062aa8572f.png)

I'm asking if you can add some option like that one to hide and show more the text's description 

Thanks

**Comment by palich91** [comment]
@DanielnetoDotCom what do you say
