### ISSUE TITLE
disableEmailSharing what exactly is that function for?

### ISSUE THREAD

**Issue by Wepwawetcode** [WWBN/AVideo#2529]
disableEmailSharing what exactly is that function for?

![image](https://user-images.githubusercontent.com/28763945/72599952-f9b7fa80-3912-11ea-992f-f7e8b85e2052.png)

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/72608889-7b535c80-3902-11ea-8a7f-e7c99179b7c6.png)
