### ISSUE TITLE
Video files are not transferred from the encoder to the streamer

### ISSUE THREAD

**Issue by SergejGrin** [WWBN/AVideo#2534]
The conversion process runs fine and to the end without errors. 
![encod4](https://user-images.githubusercontent.com/59236880/72621687-099b0300-3942-11ea-8379-f66ee6380aa6.png)
![encod3](https://user-images.githubusercontent.com/59236880/72621689-0a339980-3942-11ea-9ac4-372c6561dce4.png)
![encod2](https://user-images.githubusercontent.com/59236880/72621690-0a339980-3942-11ea-814c-a7d3fe058a50.png)
![encod1](https://user-images.githubusercontent.com/59236880/72621691-0acc3000-3942-11ea-8c6c-e33eff1ce0f9.png)
But as a result, only image files (gif, jpg, webp) are transferred to the streamer, and mp4 video files are not transmitted and, upon completion of the encoding process, are deleted by the encoder. 
![encod6](https://user-images.githubusercontent.com/59236880/72621747-246d7780-3942-11ea-914f-159eb4cfdf50.png)
![encod5](https://user-images.githubusercontent.com/59236880/72621751-25060e00-3942-11ea-8f14-d68331baaebc.png)
The PHP file was edited during installation:
max_execution_time = 7200
memory_limit = 3072M
post_max_size = 3072M
upload_max_filesize = 3072M
The site is installed on a virtual machine with 6 GB of memory.
What could be the reason?
Streamer Log    
[avideo-video.log](https://github.com/WWBN/AVideo/files/4077347/avideo-video.log)
Encoder Log   
[avideo-encod.log](https://github.com/WWBN/AVideo/files/4077349/avideo-encod.log)

**Comment by akhilleusuggo** [comment]
Your file is about 3h and half . Are you sure 3gb of `post_max_size = 3072M upload_max_filesize = 3072M` are enough ?

**Comment by SergejGrin** [comment]
I think that is enough. But this is what program developers must say. I think that the clipboard is overflowing, but this is again a question for the developers.

**Comment by akhilleusuggo** [comment]
What has developers to do with this ?

**Comment by DanielnetoDotCom** [comment]
@SergejGrin please read this https://github.com/WWBN/AVideo/wiki/About-Video-Upload#know-problems

**Comment by SergejGrin** [comment]
Thank you Daniel!
I have my own server and I can adjust the memory size. I encoded mp4 files ranging in size from 0.6 GB to 0.8 GB and there was not enough memory in 3072 GB. That is, the file size was three to six times smaller than RAM. I increased the memory to 4096 GB and the file transfer process began to take place, but when installing only one Low format. Apparently there is an overflow of the clipboard if encoded in Low, SD and HD formats. I basically have avi video files ranging in size from 500 MB to 1.8 GB maximum, I think that the available memory should be enough, but it is possible to increase it (if necessary).

**Comment by akhilleusuggo** [comment]
Really memory has nothing to do here . I have a small server at home , the server has only 1.5gb RAM , and I was able to transfer 20GB video ( only to test this ) , the file didn't fail . 
Daniel has linked you something important to take in count . Are you using cloudflare ?

**Comment by SergejGrin** [comment]
Of course I do not use cloudflare. Why do I need it if I have enough space on my server?

**Comment by akhilleusuggo** [comment]
I'm talking about cloudflare SSL

**Comment by SergejGrin** [comment]
I use the Let's Encrypt, the certificates are installed on my server and there are no problems in this matter.

**Comment by adelorenzo** [comment]
Hello,

I am having the same issue. Both my servers are running on the same lan. I do not use cloudflare. It was working in the past. Please advise.

Thank you very much!

**Comment by DanielnetoDotCom** [comment]
Check the encoder and the streamer log file

**Comment by adelorenzo** [comment]
Hello Daniel,
This is what I believe is the error message on avideo.log:

[21-Jan-2020 21:26:29 UTC] AVideo-Streamer answer {"error":false,"video_id":false}
[21-Jan-2020 21:26:30 UTC] {"error":false,"format":"mp4","file":"\/var\/www\/encoder\/videos\/3_tmpFile_converted_HD.mp4","resolution":"HD","videoDownloadedLink":null,"target":"https:\/\/vibe.dg74.pro\/aVideoEncoder.json","postFields":12,"videoFileSize":"67.55MB","response_raw":"{\"error\":false,\"video_id\":false}","response":{"error":false,"video_id":false}}

Please advise.

Thanks

**Comment by Chandrakant279** [comment]
When I am uploading videos it shows error...that the file is in the queue...and the youPHPTubeEncoder.json file is missing from the master file.

How could I resolve this issue?
![youtube_error](https://user-images.githubusercontent.com/60177461/72886471-dedcf000-3d2f-11ea-85d4-3696df594c63.PNG)

**Comment by DanielnetoDotCom** [comment]
sorry, there is no error on this logs

**Comment by DanielnetoDotCom** [comment]
@Chandrakant279 please make sure you are running Streamer 8.0 or greater and Encoder 3.0 or greater

**Comment by Chandrakant279** [comment]
I am using latest version from the website of yours.
Can please get me the link.

**Comment by Chandrakant279** [comment]
https://github.com/WWBN/AVideo
I download the filr from here

**Comment by DanielnetoDotCom** [comment]
Please check your version here

![image](https://user-images.githubusercontent.com/18009293/72888613-a7008900-3cec-11ea-91a2-60fdd6bdbc72.png)

![image](https://user-images.githubusercontent.com/18009293/72888526-7caecb80-3cec-11ea-9d45-76c2207786cb.png)

**Comment by adelorenzo** [comment]
I ran a `git pull` today and noticed you updated the code for the streamer. It is working now for me. Thank you very much and congrats for the amazing project!
