### ISSUE TITLE
Table 'avideo.videos' doesn't exist

### ISSUE THREAD

**Issue by adelorenzo** [WWBN/AVideo#2535]
Hello,

I am getting the error Table 'avideo.videos' doesn't exist right after a fresh install. Please advise.

Thanks,

Adolfo

**Comment by adelorenzo** [comment]
after refreshing the /admin page twice I now get the following error: DataTables warning: table id=dt1 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

thanks

**Comment by DanielnetoDotCom** [comment]
I can not tell you what is the error. but looks like you had a problem to install the tables since the main installation.

check your log files for a more specific error

**Comment by adelorenzo** [comment]
Hello Daniel,

Thank you for your reply. I scratched everything and started a new install. The screenshot below shows what happens every time:

![Screen Shot 2020-01-20 at 9 13 39 AM](https://user-images.githubusercontent.com/317860/72737598-7e9a5280-3b65-11ea-8610-f4d2a7a8126b.png)

and the install gets stuck on this error. If I force opening the main URL I get the standard homepage. I manage to login but as soon as I select Admin Panel the following error happens:

**SELECT u.*, v.*, c.iconClass, c.name as category, c.clean_name as clean_category,c.description as category_description, v.created as videoCreation, v.modified as videoModified, (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = 1 ) as likes, (SELECT count(id) FROM likes as l where l.videos_id = v.id AND `like` = -1 ) as dislikes FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id WHERE 1=1 AND v.users_id = '1' AND u.status = 'a' AND (v.status IN ('a','xmp4','xwebm','xmp3','xogg') OR (v.status='u' AND v.users_id ='1')) LIMIT 0, 50 \nError : (1146) Table 'aVideo.videos' doesn't exist**

My environment:
Debian 9 - arm64
MariaDB 10.1.41
PHP 7.4.1
Apache 2.4.25
OS - dietpi

Thanks

**Comment by DanielnetoDotCom** [comment]
check if the database user you are using has rights to create indexes.

also check your mysql error log and your apache error log .

FYI, I always test it on a Ubuntu + MySQL NOT on Debian + MariaDB

**Comment by adelorenzo** [comment]
Thanks Daniel for your guidance. I managed to fix the issue. So basically what I did was:

1) change the **innodb default row format** to **dynamic** for the mariadb
2) change the order of the tables creation with **playlists** before **videos**

BRegards,

Adolfo
