### ISSUE TITLE
Default Sort

### ISSUE THREAD

**Issue by angelawong** [WWBN/AVideo#2536]
At the moment, my videos are listed alphabetically. Is there a way for me to change the default to sort by Date Added (Newest)?

**Comment by DanielnetoDotCom** [comment]
what template are you using? Gallery?

you should have an option to show the latest videos on that.

**Comment by angelawong** [comment]
I am using the default template called YouPHPTube. I can certainly choose how I want to sort it from the user's end but the default sort when they first load the page is by Name. I want to change that default sort to Date Added so that when people load the homepage, they see the videos sorted by Date Added.

Is there somewhere under Admin that allows me to change the default sort to Date Added?

Thanks so much.
