### ISSUE TITLE
User Control DVR Switch and Make Public Stream Default

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2537]
I get some users that want to run 24/7 streams without the need for recording it. Is there a way a Switch for the DVR can be added for a Streamer to just turn on or off if they want to record the stream or not.

Also Can we make Public Stream Broadcast the default option for all new channels. Some people do not understand that switch and then send me complaints saying they do not see their stream in the live notification menu and I have to constantly explain how to make it public. 

So far I have a temp solution and I just run this command in a cron job every minute and it works for now with turning off record for channels that request it. 
                  **(put * at the end of the slash channel key for wildcard)**
EXAMPLE COMMAND : find /var/www/tmp/ . -type f -name 5e23630fb597a\* -exec rm {} \; 

Will Look like this

**find /var/www/tmp/ . -type f -name 5e23630fb597a\* -exec rm {} \;** 

This method works as long as the streamer does not change their key. If they do change their key then you will have to obviously update the key in your command in your cron job.

**Comment by akhilleusuggo** [comment]
What you're asking is basically give the user an option to save or not save the video when streaming .
This can be done by adding a new application to nginx . ( but i don't know much how would that work on the php script ) .
Also could be another option for transcoding videos for specific users ( for example premium users ). 
And same method , require just to add another application line on the config file .
Sadly the php part no clue

**Comment by JoshWho** [comment]
The switch already exists but it is only a global admin one at the moment. I am pretty sure it can be made into a individual switch for each user.
