### ISSUE TITLE
Video links are broken after upgrade

### ISSUE THREAD

**Issue by gurc4n** [WWBN/AVideo#2538]
Hi everyone,
I did the upgrade, site is working fine.
The only problem is video links are broken.

All links to videos are like below now;
http://xxxx-tube/YouPHPTube/video/26/xxx-xx-xxxxx-xxxxx-xxxxx?channelName=xxxxxxxx
But the true address is 
http://xxxx-tube/YouPHPTube/video/xxx-xx-xxxxx-xxxxx-xxxxx?channelName=xxxxxxxx

How do I get rid of that number in the url?

**Comment by akhilleusuggo** [comment]
on plugin , customize , you can try by check / uncheck permalinks

**Comment by DanielnetoDotCom** [comment]
@gurc4n both links should work.

but the important thing on the number on the URL now is because you can freely change the title and your links will still work

the one without number (ID) the link will change everytime you change the title
