### ISSUE TITLE
Can't save User settings

### ISSUE THREAD

**Issue by patrickwienecke** [WWBN/AVideo#2539]
When i change user settings, for example "userMustBeLoggedIn"  and i relaod the page, the setting ist lost. Only user settings have save problemes. I rember at inital configuration this bug was not present because i change this setting "disablePersonalInfo". At the moment this ist the only active slider at the user settings and i can't change this setting too

**Comment by DanielnetoDotCom** [comment]
Try do it on the plugin menu

Please check this, https://github.com/WWBN/AVideo/issues/2351

We will release a fix for this in the future.
