### ISSUE TITLE
about MOUSE ON POSTER

### ISSUE THREAD

**Issue by alifaaz** [WWBN/AVideo#2540]
my videos show this demo video on hover and I am looking for way to change it to  .gif  

![Capture](https://user-images.githubusercontent.com/15649967/72678251-56531b00-3ab5-11ea-8329-c124f3fd4ea0.PNG)

**Comment by DanielnetoDotCom** [comment]
Please check this 

https://github.com/WWBN/AVideo/wiki/Automatic-Thumbs-(JPG-GIF)-on-direct-uploaded-MP4-videos
