### ISSUE TITLE
Make Video quota

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#2542]
Can you create a video quota for each user?
For example, so that the user can download a maximum of 50GB. Also create quota rates:
100 GB = 5 $ / month
200 GB = $ 8 / month
400 GB = 12 $ / month

**Comment by DanielnetoDotCom** [comment]
sorry we do not have this option, you may need another app to handle it

**Comment by palich91** [comment]
can be created separately in your script?

**Comment by DanielnetoDotCom** [comment]
I am not sure how, but probably can
