### ISSUE TITLE
SMTP mail will not configure. Test email does not result in successful test, but rather endless "Processing".

### ISSUE THREAD

**Issue by deplatformed** [WWBN/AVideo#2543]
I checked the log in location [/var/www/html/AVideo/videos/avideo.log] and viewed the following error:

"PHP Fatal error:  require_once(): Failed opening required '/var/www/html/AVideo/objects/PHPMailer/src/PHPMailer.php' "

The directory, "PHPMailer" (in the "objects" directory), does not exist in the location where the application is looking. Instead, there is a directory, " 'PHPMailer (1)' ". The aforementioned directory has additional quotes because the name of the directory in fact includes single quotes around the name. I removed the single quotes and number 1, along with its parenthesis, thus changing it to "PHPMailer". Problem solved.

Why would the directory have such a clearly erroneous (and obvious) wrong name?

**Comment by DanielnetoDotCom** [comment]
Sorry I fount the bug

**Comment by deplatformed** [comment]
Great, thank you. I just realized that my comment had a bit of a negative tone, but I was concerned someone might be messing with you to cause such a strange issue. I don't really trust Github. I really like your product and especially like the religious position you are unafraid to stake. I am already buying plugins.
