### ISSUE TITLE
status code 202 and 403 downloading images from /videos

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2544]
Hi,

My phpYouTube is installed on vid.domain.com and I run a script on app.domain.com to load the images only.   Sometimes it works and sometimes I get
status code 202 and 403 downloading images from /videos which the server replies as forbidden.

Sometimes it works but if I run the script multiple times I start seeing the error above.

I need my app.domain.com to have full access to the jpg's.  Is there something I should set or remove from the htaccess? or should I create a new htaccess on my videos folder?

or is there a way I can change the image folder for the images only?

in my apache error.log i can see: client denied by server configuration when accessing the jpg.

**Comment by millzee01** [comment]
Hi, if i wait 30 - 60 seconds between script executions the server allows access to the jpg.  is there some spamming addon included in youphptube?

**Comment by DanielnetoDotCom** [comment]
Hi, there is no add on for this.

certainly, it is something in your server or network

**Comment by millzee01** [comment]
cool thanks, i just didnt want to mess up anything you set int he htaccess
