### ISSUE TITLE
blackblaze plugin setup advice

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2547]
Hi,
I purchase the backblaze plugin and setup my backblaze account

I then created a public bucket (i assume it should be a public bucket) and have added my API details to the plugin config. (went through the tutorial and can test fine so the text file gets uploaded - so thanks for making this super simple)

i just have a coupe of Q's to finish my setup:

1: Just wondering what i need to put into
CDN_Link:

2: Should i enable useDirectLink and usePublicBucket

3: Can I also configure my youtPHPTube to use backblaze to host the static css and js files?

4: I'm going to wipe out my videos and start fresh,  do I need to do anything to the encoder to upload videos to my B2 bucket from now on?

5: Once i delete my previous videos, does the videos folder get used to store images and videos anymore?

6: When i click "clear cache" on the plugin I just get a black page to:
https://vid.mydomain.com/plugin/Backblaze_B2/clearCache.php
am i missing a configuration?

many thanks

**Comment by DanielnetoDotCom** [comment]
> 1: Just wondering what i need to put into
> CDN_Link:

You only need to use that if you setup a CDN for your B2 bucket

> 2: Should i enable useDirectLink and usePublicBucket

It is up to you, but for my self I like to check the useDirectLink and uncheck the usePublicBucket

if you uncheck the usePublicBucket your videos will be private, and to be able to access them it will require a token from your B2 and this token will expire after some time. so if someone grab the file link from your site HTML, this link will expire after some time.

> 3: Can I also configure my youtPHPTube to use backblaze to host the static css and js files?

Sorry the B2 is only for videos.

> 4: I'm going to wipe out my videos and start fresh, do I need to do anything to the encoder to upload videos to my B2 bucket from now on?

the streamer is the one who upload the videos. you do not need to do anything on the encoder

> 5: Once i delete my previous videos, does the videos folder get used to store images and videos anymore?

yes, the videos folder is necessary, it will store the cache, images and dummy files

Dummy files are a 10 bytes file for each of video files you have on backblaze. it is necessary, so your streamer will not get lost.

> 6: When i click "clear cache" on the plugin I just get a black page to:
> https://vid.mydomain.com/plugin/Backblaze_B2/clearCache.php
> am i missing a configuration?

The clear cache clear the Tokens from private videos and create new ones. usually you do not need that.

**Comment by millzee01** [comment]
awesome, thanks daniel, works a treat!
