### ISSUE TITLE
disable animated gif

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2548]
Hi,

i purchased MP4ThumbsAndGif plugin and have disableAnimatedGif checked in the CustomizeAdvanced plugin however when i upload a video it created the gif (which is quite large).  Am wanting to completely remove the gif generation and just use jpg.

Do i need to hack the code to stop this?

**Comment by akhilleusuggo** [comment]
desable MP4ThumbsAndGif

**Comment by millzee01** [comment]
thanks, i need the MP4ThumbsAndGif plugin enabled so thumbs get created for direct uploads

**Comment by millzee01** [comment]
rem'd out line in encoder/objects/encoder.php
//$postFields['gifimage'] = new CURLFile(static::getGifImage($file, intval(static::parseDurationToSeconds($duration) / 2), 3));

however gif is still being created.  Is there anywhere else I need to disable getGifImage?

**Comment by millzee01** [comment]
ok, one step closer.

edited /view/mini-upload-form/upload.php and rem'd out:
MP4ThumbsAndGif::getImage($videoFileName, 'gif');

this has stopped gif's being added to embedded video.

now checking direct upload and encoding

**Comment by DanielnetoDotCom** [comment]
the gif will always be created, also the webp image, now there is no way to stop it when you are using the encoder.

**Comment by millzee01** [comment]
ok, I am finding the animated gif's are taking up lots of unwanted space as they are not required..  Will have to live with it atm.

**Comment by DanielnetoDotCom** [comment]
You can add a crontab to delete it everyday.

**Comment by millzee01** [comment]
lol i just brought up cron as you posted the message :-)

thanks
