### ISSUE TITLE
Video naming convention

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2549]
Hi,

if a video filename has an extension: _YPTuniqid does this mean its been uploaded by the encoder and will always be _SD.mp4 if i only allow SD videos to be encoded?

and if I upload a mp4 direct then the filename will not have _YPTuniqid at the beginning?

also, if I direct upload a wbem will the extension be stored anywhere?

reason is I am importing the videos into my own app and want to be able to access video file direct from backblaze b2?

**Comment by DanielnetoDotCom** [comment]
the script grabs the file name from the video table on the database, then if the type is a video the script will check:

Example: filename = _YPTuniqid1234abcd

### For MP4

_YPTuniqid1234abcd.mp4
_YPTuniqid1234abcd_Low.mp4
_YPTuniqid1234abcd_SD.mp4
_YPTuniqid1234abcd_HD.mp4

### For Webm

_YPTuniqid1234abcd.webm
_YPTuniqid1234abcd_Low.webm
_YPTuniqid1234abcd_SD.webm
_YPTuniqid1234abcd_HD.webm

### For HLS

Check if _YPTuniqid1234abcd is a directory 

that is why we keep the dummy files on the videos directory, so it speedup the serach, a search on external storages are slow.

**Comment by millzee01** [comment]
awesome, thanks i've included this check in my own script now.
