### ISSUE TITLE
thumb sizes

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2550]
Hi, is there  a plugin that allows me to change the size of the thumb? i.e having an option to allow the thumb to be hd would be cool!

**Comment by DanielnetoDotCom** [comment]
Sorry, not yet

**Comment by akhilleusuggo** [comment]
@millzee01 You can hard code it . I have made some changes and works

**Comment by millzee01** [comment]
thanks,  I'm looking for where I can change the ffmpeg param "scale=320" and adjust to my needs.  i suspect because i'm using the MP4ThumbsAndGif plugin it'll be encrypted.

**Comment by akhilleusuggo** [comment]
encryption has nothing to do with result of the size .

**Comment by millzee01** [comment]
i was referring to the encrypted plugin code.

**Comment by akhilleusuggo** [comment]
encrypted ? Maybe you mean hardcoded

**Comment by millzee01** [comment]
nope its encrypted!

http://phpcrypt.com/

**Comment by akhilleusuggo** [comment]
I see what you're talking about
