### ISSUE TITLE
TimeLogStart

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2553]
Hi, i just updated core files and now i'm getting

[23-Jan-2020 15:06:13 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function TimeLogStart() in /var/www/html/objects/videoAddNew.json.php:29
Stack trace:
#0 {main}
  thrown in /var/www/html/objects/videoAddNew.json.php on line 29

Is there something i've missed looking at this error?

**Comment by DanielnetoDotCom** [comment]
Did you use git pull to update? (Strongly recommended)

This function existis here https://github.com/WWBN/AVideo/blob/3ca0af879e0ed4207551ce282bd014fcafe9221f/objects/functions.php#L2482

I guess you did not update all your files.

**Comment by millzee01** [comment]
ah, i didnt use git pull.  Is this something I should use to update the files?

I manually updated which I suspect is probably not the way to do it

**Comment by DanielnetoDotCom** [comment]
Please check this https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by millzee01** [comment]
cool, i'll try this now.  Is there a requirement to do a db update?

**Comment by millzee01** [comment]
cool, i'll try this now.  Is there a requirement to do a db update?

**Comment by DanielnetoDotCom** [comment]
> cool, i'll try this now. Is there a requirement to do a db update?

Just do not skip any update, make it one by one

**Comment by millzee01** [comment]
all done, site is completely up to date now :-) thanks for that!

have cleaned the logs and can see the following msg:
PHP Notice:  Undefined property: stdClass::$filterRRating in /var/www/html/plugin/CustomizeAdvanced/CustomizeAdvanced.php

should I disable and enable the CustomizeAdvanced plugin again? if I do will this clear my current config?

**Comment by DanielnetoDotCom** [comment]
Hi, this is not an error , this is just a warning.

You do not have to worry about it . It will be fixed in a new release

**Comment by millzee01** [comment]
awesom thanks again
