### ISSUE TITLE
login page not displayed with 8.3

### ISSUE THREAD

**Issue by gregkeys** [WWBN/AVideo#2555]
when upgrading to 8.3 (from 8.0)

when the userMustBeLoggedIn option is enabled we are no longer redirected to /user
instead the user is presented with a landing page of videos with no side bar or login menu but has videos in the center. They are also able to watch the videos without logging in

expected behavior, when userMustBeLoggedIn the login page should be displayed and videos should not be playable.

**Comment by DanielnetoDotCom** [comment]
can you please screen shot it?

can you reproduce it on demo site?

**Comment by floska** [comment]
can't login https://surfow.xyz/user please help me admin pass dadada
