### ISSUE TITLE
direct upload - potential bug

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2557]
Hi, 
If you click "upload a file" and go back on the browser a new video record is created.

i've tested this on the test site as well.

also if I click upload a file or embed and click cancel after embedding a file i'm having a situation when if i click upload or embed and then click cancel the last added video gets deleted which is a bit scary.  

This only happens if I stay on the videos page,  if i go to another page and come back then I can click cancel without the videos getting deleted.

May be linked to the issue here?

Am trying to pin it down to a setting i have enabled.

**Comment by akhilleusuggo** [comment]
You post titles are insane like always 
The video upload is working by 'chunk' , I would even say that is good , since if something happens , and your connection to the server is lost , after refreshing the website , you can resume the upload

**Comment by millzee01** [comment]
no idea what you mean @akhilleusuggo ?

Fact is if my users cancel a video form then I wouldn't expect a new video record to be created!
