### ISSUE TITLE
Embed/Upload video bug

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2558]
Hi,

I have logged onto the  demo site and recreated a bug that seems to be associated with the Youtube theme.

To recreate: log into demo site as test.

1: Go to videos page
2: Click "Embed a video link" and add any YT video url then click save. (video will be added)
3: Now click "Embed a video link" and then click close.

You will see the previous embedded video gets deleted.

4: Click "Embed video link" and then click "close" again
You will now see an error popup saying "Your video has NOT been deleted!"

The same happens when you use the "upload a file" as well.

Looks like some JS event is not being reset as on my site nothing out or ordinary is shown in the log

**Comment by akhilleusuggo** [comment]
I have checked it , and you're right . No idea why . 
But , this is not the right way to embed ( I don't use this way )
Go to plugins , BulkEmbed (BulkEmbed) , Seach , then most the link of your search/video , or the keywords ( like if it was YouTube ) , and add the one you want ( or all ) . 
I have never got any errors with this 

When I tried your method , the embedded video doesn't detect the name of the video at all , nor the thumbnails

**Comment by millzee01** [comment]
This is how my users add videos. They don't have access to any admin content.

**Comment by akhilleusuggo** [comment]
Not only admins can bulk-embed
but I understand what you mean

**Comment by DanielnetoDotCom** [comment]
@millzee01 can you please update your site?

Recently (few days ago) we release a fix for a similar problem.

**Comment by millzee01** [comment]
Hi,

I updated to latest release and tested the dropdown menu "embed video" and this is now fixed.

If I use the button on the /mvideos page then the issue is still there on my site and the demo site.  I suspect the dropdown menu refreshes the page and vars because its an anchor?

**Comment by DanielnetoDotCom** [comment]
Humm, not sure.

I could not reproduce it.

can you reproduce it on demo site?

can you please make a video or screenshots?

**Comment by millzee01** [comment]
To recreate: log into demo site as test.

1: Go to videos page
2: Click "Embed a video link" button (not dropdown link) and add any YT video url then click save. (video will be added)
3: Now click "Embed a video link" and then click close.

You will see the previous embedded video gets deleted.

4: Now Click "Embed video link" button again and then click "close"
You will now see an error popup saying "Your video has NOT been deleted!"

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by millzee01** [comment]
am afraid the issue is still there after update @DanielnetoDotCom 

to debug, i placed
`console.log("videos_id=" + videos_id);`
just before: 
`$('#videoFormModal').modal();` in the #linkExternalVideo click event.

and
`console.log("videoFormModal: videos_id=" + videos_id + " | videoUploaded=" + videoUploaded);`
at the top of deleteVideo() which seems to be called whenever "close" button on the video form is clicked 

If I click the "embed video link" button the videos_id gets set to 0 (all good so far)

If i then go through the process and add an embedded video the video gets created fine and the modal closes.  
at this stage the videos_id has the value of the video_id it has inserted.

If I then click "embed a video link" again the videos_id gets set to 0 (as before) but if I click close then
deleteVideo is called and the videos_id within this function is set to the previously added video value.

here's the console output when I click "close":
videoFormModal: videos_id=254 videoUploaded=false

i suspect somewhere along the line videos_id is being re-added maybe by a element value or something.

**Comment by DanielnetoDotCom** [comment]
On the last update I sent the videos_id is set to 0 when you click on the add embed video button https://github.com/WWBN/AVideo/commit/7c3fba033917541115775e27a995a47adf6805c3#diff-02b7b0b3f51036897f32800b48e4b07aR1549

**Comment by millzee01** [comment]
thats correct, however the value inside:
fileUploadVideos_id element isnt getting reset.

if i add
$('#fileUploadVideos_id').val("");

below videos_id=0 it fixes the issue.

**Comment by DanielnetoDotCom** [comment]
Like that?

**Comment by millzee01** [comment]
yep, it works great now!
