### ISSUE TITLE
Password Protected

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2560]
Thanks for implementing this new feature , but 
Only admins can use it . I don't know if you forgot to add it to users as well .
And yes , I can reproduce it on demo site ( only with admins work , normal users can't )

**Comment by DanielnetoDotCom** [comment]
Hi, thanks for notice it, you were right it was a bug, once you enable all users should be able to set a password

I am sending a fix

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I don't know if good idea or not , but can you put '' do not ask password for video's owner'' ?

**Comment by DanielnetoDotCom** [comment]
For now, it may be a good idea, because it is a good way to test it.

change it is not too hard. but I would prefer to keep that way for now.

**Comment by akhilleusuggo** [comment]
thanks
