### ISSUE TITLE
Cache directory

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2561]
So by default the cache directory is : `/var/www/html/YouPHPTube/videos/cache/`
and it can be changed . My question if it's possible to change it to a non apache directory , for example `/mnt/ramdisk `
I have a ramdisk directory on `/tmp` and `/mnt/ramdisk `
I think I may be able to create a cache directory inside the apache directories , but never tired before , that's why I'm asking if possible to have it in a non apache directory .

**Comment by akhilleusuggo** [comment]
I'm not able to change the cache directory ...

**Comment by millzee01** [comment]
@akhilleusuggo - you can map a folder to a ramdisk at os level, i've done this and it works gr8

**Comment by DanielnetoDotCom** [comment]
Hi

@akhilleusuggo whe this latest version you should be able to change your cache dir.

But not all files will be saved on the changed directory, some files (.js, css, etc) will still be saved inside the videos/cache dir, because they need to be available on the web

the good thing on change the cache directory is because you can use a large drive to store your files and a ssd dive to store your cache. this will speedup your site and avoid overload the drivers

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I've reproduced it on demo site , and ever time I refresh the site the cache directory is back to default again . To avoid that , I have created ( on my server ) a ramdisk into `/videos/cache/speedcache/` and still , the cache directory goes back to `/videos/cache/`
Could you take a look ?
PS : Yes , I've already `git pull` and no changes

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo do you mean the cache dir path in the plugin is not saving?

or do you mean, even if you change it keeps creating the /videos/cache/ directory?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom the plugin is not saving , and keep creating on /videos/cache/

**Comment by DanielnetoDotCom** [comment]
Keep creating the /videos/cache/ is expected, I mention this above 

> But not all files will be saved on the changed directory, some files (.js, css, etc) will still be saved inside the videos/cache dir, because they need to be available on the web

About save the configuration, can you please try to save it directly from the plugins menu, NOT from the Admin panel?

![image](https://user-images.githubusercontent.com/18009293/73265855-8173f380-41b4-11ea-8f28-cb3e8e74041e.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom That exactly what I do , never done it from Admin panel 
Try changing it on demo site

**Comment by akhilleusuggo** [comment]
ok , now it's working
