### ISSUE TITLE
Properly sending custom metadata from encoder server to streamer server

### ISSUE THREAD

**Issue by hanyoonLDA** [WWBN/AVideo#2562]
Hi there, first of all -- awesome project! 

I've modified the encoder server to get some extra metadata while importing videos -- specifically video tags. I've taken a look at the database structure for how video tags are stored, and I must admit it's not in the most optimal structure to be easily able to send tag data from the encoder server to the streamer server.

Any idea on how to effectively send tag data over? I'm thinking that sending the tag data (after the initial video is sent) directly to the tags plugin would probably make the most sense. Let me know your thoughts! Perhaps I'll make a public plugin if all goes well :)

**Comment by millzee01** [comment]
Hi,  I had to mod objects/video.php so my users video gets automatically placed into a their own user group  

i used sqlDAL::writeSql to do this after the initial record is created..

**Comment by DanielnetoDotCom** [comment]
Do you mean when you use the encoder, you get the tags from youtube and import them to your AVideo installation?

**Comment by hanyoonLDA** [comment]
@millzee01 Thanks for the input! To clarify, you used the writeSql function within objects\video.php? Or is there another file that I'm not finding that handles all the incoming videos. I've also wanted to execute a Python command from PHP to do some back-end optimization but I'm having a brainfart on where to put the execution command. 

@DanielnetoDotCom Yup! Whether it be YouTube, Vimeo, or even a custom scraper to get certain metadata. The problem is that for each tag there needs to be a new row created for that specific tag -- any thoughts on simply adding a column to the videos table and not have to worry about checking for duplicate tag submissions? I do realize that it would significantly put more strain on the server if I was to query videos with a certain tag, but then again I'm lazy :)

**Comment by DanielnetoDotCom** [comment]
@hanyoonLDA about the tags, you should look into the VideoTags plugin, you may be able to integrate with it.
