### ISSUE TITLE
mp4ThumbsAndGif

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2563]
Hi,  

what is the best way to hide the "Get Jpeg/Gif" button on the videos page?
its the button with onclick="mp4ThumbsAndGif( video id)"

**Comment by DanielnetoDotCom** [comment]
Hi, I am not sure what you mean.

can you please explain it with a screenshot?

**Comment by millzee01** [comment]
sure:
![gif-button](https://user-images.githubusercontent.com/28105720/73178744-cee75680-4109-11ea-91f6-046fcb0fc273.png)

**Comment by DanielnetoDotCom** [comment]
What about if you add this CSS in your head section 

```
button[onclick*="mp4ThumbsAndGif"] {
    display: none;
}
```

![image](https://user-images.githubusercontent.com/18009293/73191069-ad846b80-4105-11ea-9708-3faf3f46b06f.png)

**Comment by millzee01** [comment]
awesome, words a treat thanks @DanielnetoDotCom
