### ISSUE TITLE
Expose Live Stream API

### ISSUE THREAD

**Issue by ejb1123** [WWBN/AVideo#2564]
I am working on making an app that integrates with AVideo and I am making this request to see if you can make an API available for live streaming.

**Comment by DanielnetoDotCom** [comment]
I guess you already have all the options you need.

just inspect the PHP site code and make similar requests

**Comment by ejb1123** [comment]
While I can see the requests can you expose them through the API plugin, so it can be easier to integrate with

**Comment by DanielnetoDotCom** [comment]
What about this ?

![image](https://user-images.githubusercontent.com/18009293/73257017-c5113200-41a1-11ea-8568-bc7de7205d9d.png)

**Comment by ejb1123** [comment]
Looks good.
What type of data does it return? I am looking for something that will return the info for doing the live stream like the server and stream key

**Comment by DanielnetoDotCom** [comment]
The API is here https://demo.avideo.com/plugin/API/info.php

If you check this API link https://demo.avideo.com/plugin/API/get.json.php?APIName=livestreams

you will notice you can get the current Lives from the json->applications parameter

![image](https://user-images.githubusercontent.com/18009293/73349757-85fae380-426a-11ea-8a1c-84c8a0d03487.png)


What exactly are you trying to extract?

if you need the user credentials and key to start a new Livestream you should query the user

I just submit an update that will query the user for you

check this API URL sample https://demo.avideo.com/plugin/API/get.json.php?APIName=user&APISecret=95a5f5981482dfe55a2a3eadf32c9a8d&user=admin

this will retreive all the informations from admin, including the livestream information.

![image](https://user-images.githubusercontent.com/18009293/73352821-bb0a3480-4270-11ea-9f2f-2797f44631f2.png)
