### ISSUE TITLE
backblaze api help

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2565]
Hi, i've been getting some help from backblaze support who say the files are actually being copied to my bucket but the web interface can take some time for it to show the file in my bucket.

I wonder if its possible to have some sort of debug option showing the full api response so we can diagnose whats happening with my setup?

and if i can pass some parameter into api call?

as it stands, the file is being copied up somewhere
[28-Jan-2020 07:29:02 UTC] decideMoveUploadedToVideos: 12809_5e2fe2be7a4e34.34326821.webm
[28-Jan-2020 07:29:02 UTC] decideMoveUploadedToVideos: NOT ZIp file 12809_5e2fe2be7a4e34.34326821.webm
[28-Jan-2020 07:29:02 UTC] decideMoveUploadedToVideos: B2 12809_5e2fe2be7a4e34.34326821.webm
[28-Jan-2020 07:29:02 UTC] copy_to_B2 Start 12809_5e2fe2be7a4e34.34326821.webm
[28-Jan-2020 07:29:08 UTC] copy_to_B2 done 12809_5e2fe2be7a4e34.34326821.webm {}
[28-Jan-2020 07:29:08 UTC] MP4ThumbsAndGif: (12809_5e2fe2be7a4e34.34326821), jpg
[28-Jan-2020 07:29:08 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[28-Jan-2020 07:29:08 UTC] MP4ThumbsAndGif: Video Not found (12809_5e2fe2be7a4e34.34326821), jpg

also, when the file is copied form the client is that direct from the client machine to the b2 bucket or does the file get copied to the server then up to the bucket?

reason i need to know is that i'm in the uk and my server is in the us so the file might be going to the Amsterdam dc then up to the us dc?

thanks

**Comment by DanielnetoDotCom** [comment]
It will only send a message from the BackBlaze if there is an error

If is success it only return a file object, NOT the backblaze object

if you want to inspect the response you may need to modify the file` /path/to/AVideo/plugin/Blackblaze_B2/vendor/gliterd/backblaze-b2/src/Client.php`

Look for the method  **public function upload(array $options)** 

![image](https://user-images.githubusercontent.com/18009293/73257908-5df47d00-41a3-11ea-8a8a-856880a52454.png)

**Comment by millzee01** [comment]
ah i thought that was encrypted as its in the plugin.  will check it out now

**Comment by DanielnetoDotCom** [comment]
The vendor dir is not encrypted

**Comment by millzee01** [comment]
the problem with the gliterd sdk is that its using v1 of the b2 api

```
    protected function authorizeAccount() {
        $response = $this->client->request('GET', 'https://api.backblazeb2.com/b2api/v1/b2_authorize_account', [
            'auth' => [$this->accountId, $this->applicationKey],
        ]);

        $this->authToken = $response['authorizationToken'];
        $this->apiUrl = $response['apiUrl'] . '/b2api/v1';
        $this->downloadUrl = $response['downloadUrl'];
    }
```

which should be using:
`$url = "https://api.backblazeb2.com/b2api/v2/b2_authorize_account";`

will check with babckblaze what implications this has on new buckets that use CORS

**Comment by DanielnetoDotCom** [comment]
I use the Official Backblaze API, maybe they have some update

**Comment by millzee01** [comment]
does the test script use the https://api.backblazeb2.com/b2api/v2 api?

**Comment by DanielnetoDotCom** [comment]
Test Script is pretty simple and use the same methods as the main one

test.php

![image](https://user-images.githubusercontent.com/18009293/73265326-7ff5fb80-41b3-11ea-9a01-e4ad87d82d1d.png)

Backblaze_B2.php

![image](https://user-images.githubusercontent.com/18009293/73265361-9603bc00-41b3-11ea-8812-e8f056f5e63a.png)

**Comment by millzee01** [comment]
the test works fine, however there seems to be a problem when I upload a video file form my client.

Does the video get transferred directly from my pc to the bucket? or does it get picked up by the server and transferred?

**Comment by millzee01** [comment]
Hi,

After doing something with backblaze support it seems to be working great now with encoder and direct upload :-),  I had to set the lifecycle setting on my bucket to keep only the original file.

seems to have kicked it into action so happy days!

one msg i do see in the log is

> [28-Jan-2020 13:41:55 UTC] removeHLSFiles: /var/www/html/videos/1280102_5e3038fe664014.85449077
> [28-Jan-2020 13:41:55 UTC] PHP Warning:  scandir(/var/www/html/videos/1280102_5e3038fe664014.85449077): failed to open dir: No such file or directory in /var/www/html/plugin/Blackblaze_B2/Blackblaze_B2.php(14) : eval()'d code(1) : eval()'d code on line 225
> [28-Jan-2020 13:41:55 UTC] PHP Warning:  scandir(): (errno 2): No such file or directory in /var/www/html/plugin/Blackblaze_B2/Blackblaze_B2.php(14) : eval()'d code(1) : eval()'d code on line 225
> [28-Jan-2020 13:41:55 UTC] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/plugin/Blackblaze_B2/Blackblaze_B2.php(14) : eval()'d code(1) : eval()'d code on line 226


even though the upload and thumbs are created fine so i suspect I can ignore this error?

**Comment by DanielnetoDotCom** [comment]
I just sent an update to the BlackBlaze_B2 plugin to get away from this error

Please download the plugin and overwrite it.

**Comment by millzee01** [comment]
Do i just download and reload plugin?

**Comment by DanielnetoDotCom** [comment]
Yes, correct.

You still have the download button from the plugins site correct? https://youphp.tube/plugins/

**Comment by millzee01** [comment]
hi, i downloaded it and then uploaded.

Is there a way to see if the latest code got updated?  

I cleared the cache etc

**Comment by millzee01** [comment]
I tan a test and got error 500

and this is in my log:
[28-Jan-2020 23:09:43 UTC] copy_to_B2 Start test.txt
[28-Jan-2020 23:10:04 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: pod-000-1014-07.backblaze.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185
Stack trace:
#0 /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/www/html/plugin/Blackblaze_B2/v in /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 185

was working fine uploading videos before i updated plugin.  Should i restart apache do you think? or is there a db update i need to do?

**Comment by millzee01** [comment]
ok, restarted etc and now get 
[28-Jan-2020 23:12:51 UTC] copy_to_B2 Start test.txt
[28-Jan-2020 23:12:59 UTC] copy_to_B2 done test.txt {}

will do some uploads and test

**Comment by millzee01** [comment]
seems to be a problem upload atm:

[28-Jan-2020 23:27:32 UTC] decideMoveUploadedToVideos: SoccerDrills3BeginnerDrills_5e30c364bc83e8.56290957.mp4
[28-Jan-2020 23:27:32 UTC] decideMoveUploadedToVideos: NOT ZIp file SoccerDrills3BeginnerDrills_5e30c364bc83e8.56290957.mp4
[28-Jan-2020 23:27:32 UTC] decideMoveUploadedToVideos: B2 SoccerDrills3BeginnerDrills_5e30c364bc83e8.56290957.mp4
[28-Jan-2020 23:27:33 UTC] copy_to_B2 Start SoccerDrills3BeginnerDrills_5e30c364bc83e8.56290957.mp4
[28-Jan-2020 23:27:54 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: pod-000-1063-12.backblaze.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185
Stack trace:
#0 /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/www/html/plugin/Blackblaze_B2/v in /var/www/html/plugin/Blackblaze_B2/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 185

does this mean anything?

**Comment by DanielnetoDotCom** [comment]
Looks like you go back to the last error 

`Could not resolve host: pod-000-1063-12.backblaze.com`

your server looks like can not resolve it.

**Comment by millzee01** [comment]
whats strange is the test file works and the encoder upload works fine,  its just direct upload that seems to be the issue.  Have logged a ticket with backblaze to see why we cannot resolve pod-000-1063-12.backblaze.com.  Server setup is fine and resolves at the a command line.

**Comment by DanielnetoDotCom** [comment]
really strange, I have never seen this before 

But researching I found this https://stackoverflow.com/questions/1341644/curl-and-https-cannot-resolve-host

Some of them find the solution disabeling IPv6, some restarting PHP, Docker, etc read it and you may find the problem.

**Comment by millzee01** [comment]
whats strange is i get this in the log:
```
[29-Jan-2020 13:01:17 UTC] copy_to_B2 Start SoccerDrills3BeginnerDrills_5e31821d896147.76687337.mp4
[29-Jan-2020 13:01:31 UTC] copy_to_B2 done SoccerDrills3BeginnerDrills_5e31821d896147.76687337.mp4 {}
[29-Jan-2020 13:01:31 UTC] MP4ThumbsAndGif: (SoccerDrills3BeginnerDrills_5e31821d896147.76687337), jpg
[29-Jan-2020 13:01:31 UTC] MP4ThumbsAndGif: https://vid.kwiktactix.com/encoder/getImageMP4/aHR0cHM6Ly9mMDAwLmJhY2tibGF6ZWIyLmNvbS9maWxlL3ZpZC1rd2lrdGFjdGl4L1NvY2NlckRyaWxsczNCZWdpbm5lckRyaWxsc181ZTMxODIxZDg5NjE0Ny43NjY4NzMzNy5tcDQ=/jpg/0
```

then when i do a clear cache the thumb appears..defo think its a Name resolution issue

**Comment by DanielnetoDotCom** [comment]
By this log, it means it goes thru

**Comment by millzee01** [comment]
@DanielnetoDotCom 

I get this in my log:

[29-Jan-2020 16:44:50 UTC] decideMoveUploadedToVideos: SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019.mp4
[29-Jan-2020 16:44:50 UTC] decideMoveUploadedToVideos: NOT ZIp file SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019.mp4
[29-Jan-2020 16:44:50 UTC] decideMoveUploadedToVideos: B2 SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019.mp4
[29-Jan-2020 16:44:50 UTC] copy_to_B2 Start SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019.mp4
[29-Jan-2020 16:44:54 UTC] copy_to_B2 done SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019.mp4 {}

All good, then:

[29-Jan-2020 16:44:54 UTC] MP4ThumbsAndGif: (SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019), jpg
[29-Jan-2020 16:44:54 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}

[29-Jan-2020 16:44:54 UTC] MP4ThumbsAndGif: Video Not found (SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019), jpg`
`

The file has definitely been copied up to my bucket but no image has been generated:
Should the filename be SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019.mp4 and not SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019
as in the log?


because if I put https://f000.backblazeb2.com/file/vid-kwiktactix/SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019.mp4 in the browser the video loads fine.

**Comment by millzee01** [comment]
@DanielnetoDotCom 

Can you confirm that the b2 plugin uses "authorization upload token" to get the correct load balanced upload server where the file gets copied?  and is there any chance we can drop the name in the log output after the copy please?  this is so we can determine which load balanced upload server is getting the file.

thanks

**Comment by DanielnetoDotCom** [comment]
> @DanielnetoDotCom
> 
> I get this in my log:
> 
> [29-Jan-2020 16:44:50 UTC] decideMoveUploadedToVideos: SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019.mp4
> [29-Jan-2020 16:44:50 UTC] decideMoveUploadedToVideos: NOT ZIp file SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019.mp4
> [29-Jan-2020 16:44:50 UTC] decideMoveUploadedToVideos: B2 SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019.mp4
> [29-Jan-2020 16:44:50 UTC] copy_to_B2 Start SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019.mp4
> [29-Jan-2020 16:44:54 UTC] copy_to_B2 done SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019.mp4 {}
> 
> All good, then:
> 
> [29-Jan-2020 16:44:54 UTC] MP4ThumbsAndGif: (SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019), jpg
> [29-Jan-2020 16:44:54 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
> 
> [29-Jan-2020 16:44:54 UTC] MP4ThumbsAndGif: Video Not found (SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019), jpg` `
> 
> The file has definitely been copied up to my bucket but no image has been generated:
> Should the filename be SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019.mp4 and not SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019
> as in the log?
> 
> because if I put https://f000.backblazeb2.com/file/vid-kwiktactix/SoccerDrills3BeginnerDrills5_5e31b682449be8.58453019.mp4 in the browser the video loads fine.
> 
> note this only happens with direct upload.

This is not a real error, If you got the thumbs and video lenght you are fine, you can ignore the "errors".

**Comment by DanielnetoDotCom** [comment]
> @DanielnetoDotCom
> 
> Can you confirm that the b2 plugin uses "authorization upload token" to get the correct load balanced upload server where the file gets copied? and is there any chance we can drop the name in the log output after the copy please? this is so we can determine which load balanced upload server is getting the file.
> 
> thanks

When the upload is successfuly complete you will have a log with the full response.

![image](https://user-images.githubusercontent.com/18009293/73443552-acd21c00-4335-11ea-9d72-fec523636398.png)

**Comment by millzee01** [comment]
@DanielnetoDotCom 

Hi i manged to get to the bottom of my issues.

Im using latest ubuntu build 18.04 which has a known bug with systemd-resolved

I had to do the following:
1: Edit the file in /etc/systemd/resolved.conf as sudoer and add google DNS servers entry 
[Resolve] DNS=8.8.8.8 8.8.4.4

2: Cancel the actual symlink to   /etc/resolv.conf  -> s udo rm /etc/resolv.conf

3: Create a new symlink sudo ln -s   /run/systemd/resolve/resolv.conf /etc/resolv.conf

4: Restart the systemd service -> sudo service systemd-resolved restart
test using nslookup is using new dns servers

After doing this i've upload 4 direct mp4's and the images have been created with no issues.

**Comment by DanielnetoDotCom** [comment]
hummm

so it was really a DNS problem

**Comment by millzee01** [comment]
The was the resolution issue.
There's seems to be something still intermittent going on with direct upload, b2 and mp4image plugin..

If i wait for the video to be uploaded and then hit save on the video form then the thumb gets created, 

If I select a video and hit upload then save before the video is uploaded then I have to clear the cache to get the thumb.

One thing i might do i force the user to stay on the upload form and only show the save button once the video has been uploaded.
