### ISSUE TITLE
encoder is external

### ISSUE THREAD

**Issue by karthikindia** [WWBN/AVideo#2566]
Hi I found in my tv.cobrasoftwares.org the encoder is redirecting to encoder1.avideo.com
since mine is a self hosted why i cannot have the encoder into my server ?

**Comment by DanielnetoDotCom** [comment]
Hi

You do have your own Encoder, check it here https://tv.cobrasoftwares.org/Encoder/

Maybe you missconfigure something.

you need to check 2 things ...

# 1. Check if your encoder is correct setup on Streamer.

![image](https://user-images.githubusercontent.com/18009293/73264508-bf234d00-41b1-11ea-9449-62e1803309bb.png)


# Check if you enable the Network

As long as you do not have a network, make sure you are not using the public one.

Uncheck useEncoderNetworkRecomendation
Check  doNotShowEncoderNetwork

![image](https://user-images.githubusercontent.com/18009293/73264628-f98cea00-41b1-11ea-85b8-80feab5869e4.png)

**Comment by karthikindia** [comment]
thanks please
