### ISSUE TITLE
youtube-dl

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2568]
Could you please show me the line the default encoder uses to download videos with youtube-dl ( witch folder/file to edit ?
The quality is poor and I would like to change the command line .

**Comment by DanielnetoDotCom** [comment]
Go to this file `https://github.com/WWBN/AVideo-Encoder/blob/master/objects/Encoder.php` and search for this` self::getYouTubeDLCommand()`

**Comment by akhilleusuggo** [comment]
thank you
