### ISSUE TITLE
Setting up payment information on YPTwallet

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#2570]
I'm testing the withdrawal feature in YPT wallet and not getting any prompts for the user to set up their personal paypal, stripe or credit card info info on yptwallet.   I thought I'd added my paypal and stripe account correctly, but, when I did a approved a withdrawal request there were no prompts.  I was not set up as a sandbox account either.  Can I get detailed instructions for dummies on setting that up as the host.  Also, How will my users go about adding their paypal, stripe accounts? Also, the box that asks for "informations" on the withdrawal pay,  should be corrected to "information" no (s) on the end. And an explanation about what should go into that box would be helpful.

**Comment by DanielnetoDotCom** [comment]
Hi

We do not have the payment gateway withdraw implemented yet. the withdraw to paypal or stripe is not automatic, you must do it manually .

only the virtual money in your wallet is automatically transfered.

**Comment by heiress01** [comment]
Ok so I need to create a form or system to collect their paypal or stripe information then manually pay them through another gateway, is that correct?  But, just to clarify, when I connected my paypal and stripe information, does that collect real money when I implement pay per view or subscriptions for me as the host?

**Comment by DanielnetoDotCom** [comment]
Yes you are correct
