### ISSUE TITLE
AD(LDAP guroup withi user) import YouPHPTube

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#2572]
I am using Your LDAP Plugin.
When I log in as an AD user for the first time, I want to turn on the group in AD, Can Stream Videos, Can Upload Videos, and is Active. Is there any way?
Or is there a way to export AD groups with csv and import this csv into YouPHPTube?

**Comment by DanielnetoDotCom** [comment]
Hi

the AD group and the AVideo groups are not connected. 

but you can tell your AVideo to auto enable the upload rights

![image](https://user-images.githubusercontent.com/18009293/73444159-c758c500-4336-11ea-8f29-523d9aa30d08.png)


 and the Livestream rights

![image](https://user-images.githubusercontent.com/18009293/73444086-a42e1580-4336-11ea-9532-a2786ab8b8ca.png)

Yes you probably can import the CSV into the database, but in that case you need to know how to deal with MySQL

**Comment by hnagasawa** [comment]
Dear Neto

Thank you for your replay.

My configuration is next.
OS Ubuntu 18.04.3
Apache/2.4.29 (Ubuntu)
mariadb Ver 15.1 Distrib 10.1.43-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
PHP 7.2.24-0ubuntu0.18.04.2 (cli) (built: Jan 13 2020 18:39:59) ( NTS )
AVideo version 8.2
AVideo Encoder version 3.0
AVideo is work fine.

I found next case "LDAP Plugin Authentication #1239"

He can import csv. 
What do you need DB infomation ?
![phpadmin](https://user-images.githubusercontent.com/46562199/73444996-1b969000-439d-11ea-8765-877cbf62953a.png)

**Comment by DanielnetoDotCom** [comment]
I do not know what this screenshot mean.

If you want to import a CSV, I just can tell you it is not just export your CSV from your AD and import it.

you MUST know what are you doing and the fields you will need and what to bring to MySQL  (NOT all CSV for sure).
if you are not sure how to do it, I recommend you to google for that or hire some one to do for you.

**Comment by hnagasawa** [comment]
Thank you for your replay.

I know how to export AD users and groups csv file.

Where do I import csv file ? Users index ? or other ?

**Comment by DanielnetoDotCom** [comment]
> Where do I import csv file ? Users index ? or other ?

that is what I am talking about. you must have the knowladge to inspect the MySQL table an make those decisions

**Comment by hnagasawa** [comment]
In which table does YHP manage users and groups?
Well, if there is a site to learn to solve this problem, please.

**Comment by DanielnetoDotCom** [comment]
If you look into the tables I am sure you can figure your what are the users and group tables.

To learn how to resolve, you must learn PHP + MySQL

**Comment by hnagasawa** [comment]
You said case #1239 "if you are willing to pay we can build an app to import a CSV."
If I order, how long is the delivery time? What is the price?

**Comment by DanielnetoDotCom** [comment]
Please email to developer@youphptube.com the CSV file and I will quote it for you

**Comment by hnagasawa** [comment]
I send you my test enviromet's csv file.
