### ISSUE TITLE
PHPadmin export and import tab open error messages

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#2574]
YouPHPtube Server configuration
OS Ubuntu 18.04.3
Apache/2.4.29 (Ubuntu)
mariadb  Ver 15.1 Distrib 10.1.43-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
PHP 7.2.24-0ubuntu0.18.04.2 (cli) (built: Jan 13 2020 18:39:59) ( NTS )
AVideo version 8.2
AVideo Encoder version 3.0
AVideo is work fine.

I ran phpAdmin. I selected YouPHPTube->Import 
Next message displayed.

"
Warning in ./libraries/plugin_interface.lib.php#551
count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/display_import.lib.php#371: PMA_pluginGetOptions(
string 'Import',
array,
)
./libraries/display_import.lib.php#456: PMA_getHtmlForImportOptionsFormat(array)
./libraries/display_import.lib.php#691: PMA_getHtmlForImport(
string '5e32aa8f3d743',
string 'database',
string 'YouPHPTube',
string '',
integer 1073741824,
array,
NULL,
NULL,
string '',
)
./db_import.php#43: PMA_getImportDisplay(
string 'database',
string 'YouPHPTube',
string '',
integer 1073741824,
)
"

I select export  next messages
"
Warning in ./libraries/plugin_interface.lib.php#551
count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/display_export.lib.php#381: PMA_pluginGetOptions(
string 'Export',
array,
)
./libraries/display_export.lib.php#883: PMA_getHtmlForExportOptionsFormat(array)
./libraries/display_export.lib.php#1099: PMA_getHtmlForExportOptions(
string 'database',
string 'YouPHPTube',
string '',
string '<div class="export_table_list_container"><input type="hidden" name="structure_or_data_forced" value="0"><table class="export_table_select"><thead><tr><th></th><th>テーブル</th><th class="export_structure">構造</th><th class="export_data">データ</th></tr><tr><td></td><td class="export_table_name all">全選択</td><td class="export_structure all"><input type="checkbox" id="table_structure_all" /></td><td class="export_data all"><input type="checkbox" id="table_data_all" /></td></tr></thead><tbody> <tr><td><input type="checkbox" name="table_select[]" value="categories" checked="checked" /></td><td class="export_table_name">categories</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="categories" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="categories" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="category_type_cache" checked="checked" /></td><td class="export_table_name">category_type_cache</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="category_type_cache" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="category_type_cache" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="comments" checked="checked" /></td><td class="export_table_name">comments</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="comments" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="comments" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="comments_likes" checked="checked" /></td><td class="export_table_name">comments_likes</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="comments_likes" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="comments_likes" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="configurations" checked="checked" /></td><td class="export_table_name">configurations</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="configurations" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="configurations" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="likes" checked="checked" /></td><td class="export_table_name">likes</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="likes" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="likes" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="playlists" checked="checked" /></td><td class="export_table_name">playlists</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="playlists" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="playlists" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="playlists_has_videos" checked="checked" /></td><td class="export_table_name">playlists_has_videos</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="playlists_has_videos" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="playlists_has_videos" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="plugins" checked="checked" /></td><td class="export_table_name">plugins</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="plugins" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="plugins" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="sites" checked="checked" /></td><td class="export_table_name">sites</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="sites" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="sites" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="subscribes" checked="checked" /></td><td class="export_table_name">subscribes</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="subscribes" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="subscribes" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="users" checked="checked" /></td><td class="export_table_name">users</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="users" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="users" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="users_blob" checked="checked" /></td><td class="export_table_name">users_blob</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="users_blob" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="users_blob" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="users_groups" checked="checked" /></td><td class="export_table_name">users_groups</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="users_groups" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="users_groups" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="users_has_users_groups" checked="checked" /></td><td class="export_table_name">users_has_users_groups</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="users_has_users_groups" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="users_has_users_groups" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="videos" checked="checked" /></td><td class="export_table_name">videos</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="videos" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="videos" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="videos_group_view" checked="checked" /></td><td class="export_table_name">videos_group_view</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="videos_group_view" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="videos_group_view" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="videos_statistics" checked="checked" /></td><td class="export_table_name">videos_statistics</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="videos_statistics" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="videos_statistics" checked="checked" /></td></tr> </tbody></table></div>',
integer 18,
array,
integer 0,
)
./db_export.php#154: PMA_getExportDisplay(
string 'database',
string 'YouPHPTube',
string '',
string '',
integer 18,
integer 0,
string '<div class="export_table_list_container"><input type="hidden" name="structure_or_data_forced" value="0"><table class="export_table_select"><thead><tr><th></th><th>テーブル</th><th class="export_structure">構造</th><th class="export_data">データ</th></tr><tr><td></td><td class="export_table_name all">全選択</td><td class="export_structure all"><input type="checkbox" id="table_structure_all" /></td><td class="export_data all"><input type="checkbox" id="table_data_all" /></td></tr></thead><tbody> <tr><td><input type="checkbox" name="table_select[]" value="categories" checked="checked" /></td><td class="export_table_name">categories</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="categories" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="categories" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="category_type_cache" checked="checked" /></td><td class="export_table_name">category_type_cache</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="category_type_cache" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="category_type_cache" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="comments" checked="checked" /></td><td class="export_table_name">comments</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="comments" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="comments" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="comments_likes" checked="checked" /></td><td class="export_table_name">comments_likes</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="comments_likes" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="comments_likes" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="configurations" checked="checked" /></td><td class="export_table_name">configurations</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="configurations" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="configurations" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="likes" checked="checked" /></td><td class="export_table_name">likes</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="likes" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="likes" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="playlists" checked="checked" /></td><td class="export_table_name">playlists</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="playlists" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="playlists" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="playlists_has_videos" checked="checked" /></td><td class="export_table_name">playlists_has_videos</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="playlists_has_videos" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="playlists_has_videos" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="plugins" checked="checked" /></td><td class="export_table_name">plugins</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="plugins" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="plugins" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="sites" checked="checked" /></td><td class="export_table_name">sites</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="sites" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="sites" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="subscribes" checked="checked" /></td><td class="export_table_name">subscribes</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="subscribes" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="subscribes" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="users" checked="checked" /></td><td class="export_table_name">users</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="users" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="users" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="users_blob" checked="checked" /></td><td class="export_table_name">users_blob</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="users_blob" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="users_blob" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="users_groups" checked="checked" /></td><td class="export_table_name">users_groups</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="users_groups" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="users_groups" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="users_has_users_groups" checked="checked" /></td><td class="export_table_name">users_has_users_groups</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="users_has_users_groups" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="users_has_users_groups" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="videos" checked="checked" /></td><td class="export_table_name">videos</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="videos" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="videos" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="videos_group_view" checked="checked" /></td><td class="export_table_name">videos_group_view</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="videos_group_view" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="videos_group_view" checked="checked" /></td></tr><tr><td><input type="checkbox" name="table_select[]" value="videos_statistics" checked="checked" /></td><td class="export_table_name">videos_statistics</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="videos_statistics" checked="checked" /></td><td class="export_data"><input type="checkbox" name="table_data[]" value="videos_statistics" checked="checked" /></td></tr> </tbody></table></div>',
)
"

Above these messages , Can I ignore ?

**Comment by DanielnetoDotCom** [comment]
Why are you doing this?

Why dont you use the installer?

I do not think it will work

**Comment by hnagasawa** [comment]
>Why are you doing this?
Why are you doing this?
>Why dont you use the installer?
Yes. I used "git clone ", I down load YouPHPtube form this site.
I used your installer in clone 

>I do not think it will work
Looks to me working fine.　streamer and endoer.

If you think this system have problem, where do I must correct ?

**Comment by DanielnetoDotCom** [comment]
I am not understanding what are you trying to do.

but here is the correct place to report bug or make questions

**Comment by hnagasawa** [comment]
I got a message when I installed it.
Please do not install clean tomorrow.
Because I live in Japan. GMT + 9.
Please not close this till 31^Jan-2020 24(JST).

**Comment by DanielnetoDotCom** [comment]
You do not need PHPMyADMIN to install AVideo

**Comment by hnagasawa** [comment]
I clean install AVideo next step(I already install apache2 and marinaDB and php (https://www.linuxbabe.com/ubuntu/install-lamp-stack-ubuntu-18-04-server-desktop))
cd /var/www
git clone https://github.com/YouPHPTube/YouPHPTube.git
cd YouPHPTube/
mv YouPHPTube-Encoder upload
chown www-data:www-data /var/www/YouPHPTube/ -R
apt install ffmpeg
apt install libimage-exiftool-perl
apt install php7.2-cli php7.2-common php7.2-json php7.2-opcache php7.2-readline php7.2-curl
apt install python3-pip
sudo -H pip3 install youtube-dl
mysql
create database YouPHPTube;
create user youphptube@localhost identified by 'your-password';
grant all privileges on YouPHPTube.* to youphptube@localhost;
create database YouPHPTubeEncoder;
create user encoder@localhost identified by 'your-password';
grant all privileges on YouPHPTubeEncoder.* to encoder@localhost;
flush privileges;
vi /etc/apache2/sites-available/youphptube.conf

add next 

<VirtualHost *:80>
    ServerName tube.yourdomain.com
    DocumentRoot /var/www/YouPHPTube

    <Directory /var/www/YouPHPTube>
       DirectoryIndex index.php
       Options +FollowSymLinks
       AllowOverride All
       Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/youphptube.error.log
    CustomLog ${APACHE_LOG_DIR}/youphptube.access.log combined

</VirtualHost>

a2ensite youphptube.conf

a2enmod rewrite

a2dissite 000-default.conf

upload_max_filesize 1024M

vi /etc/php/7.2/fpm/php.ini

chnage  next

post_max_max_size 1024M

upload_max_filesize 1024M

systemctl restart php7.2-fpm

systemctl restart apache2

I access http://192.168.1.247

![png2](https://user-images.githubusercontent.com/46562199/73505779-d9aa3000-4416-11ea-9471-c357a90e0e21.png)

click install

![png3](https://user-images.githubusercontent.com/46562199/73505815-f0e91d80-4416-11ea-8e2f-ae787d2e00ef.png)
above error messages display

Why does error messages ?
What do I misstake ?

rm /var/www/YouPHPTube/install/ -r
I access http://192.168.1.247
I can login admin user

vi /etc/php/7.2/fpm/php.ini

chnage next 

max_execution_time 7200

memory_limit 1024M

systemctl restart php7.2-fpm

systemctl restart apache2

I access http://192.168.1.247/upload/install/index.php
![pngenco](https://user-images.githubusercontent.com/46562199/73505894-2b52ba80-4417-11ea-9905-b0d5f74004eb.png)
I click install
![enco2](https://user-images.githubusercontent.com/46562199/73505920-402f4e00-4417-11ea-8f0a-f9f594b05f8c.png)

rm -rf /var/www/YouPHPTube/upload/install

I access http:192.168.1.247 and admin login .
I setup  settings -> site settings -> advanced configuration. Change the Encoder URL to http://192.168.1.247/upload

I create local user and upload and encode and watch mp4 file.
Is this bug ?

Server configuration
OS Ubuntu 18.04.3
Apache/2.4.29 (Ubuntu)
mariadb Ver 15.1 Distrib 10.1.43-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
PHP 7.2.24-0ubuntu0.18.04.2 (cli) (built: Jan 13 2020 18:39:59) ( NTS )
AVideo version 8.4
AVideo Encoder version 3.0
AVideo is work fine.

**Comment by DanielnetoDotCom** [comment]
About your SQL error it is a MariaDB problem upgrade it to version 10.2 or greater

**Comment by hnagasawa** [comment]
>About your SQL error it is a MariaDB problem upgrade it to version 10.2 or greater
 Do I upgrate MariaDB only ?
If not, do I reinsatll all ?

**Comment by DanielnetoDotCom** [comment]
I really recommend MySQL instead MariaDB, but upgrade MariaDB should do the trick

**Comment by hnagasawa** [comment]
What MySQL version do you recommend　?

**Comment by DanielnetoDotCom** [comment]
The version I have in my server is `version: 5.7.29-0ubuntu0.18.04.1 (Ubuntu)`

**Comment by hnagasawa** [comment]
I update mariaDB Ver10.4. I checked this system. local user password broken expect admin.
Video and other no problem.
Next week I will try to clean install again.

**Comment by DanielnetoDotCom** [comment]
Ok

**Comment by hnagasawa** [comment]
I clean install OS and YouPHPtube and Mysql5.7 and apache2 and other.
I access http://192.168.1.247 and install click.
Sorry messages does not display.

**Comment by DanielnetoDotCom** [comment]
Check your apache error log.

**Comment by hnagasawa** [comment]
I checked apache error log. "Sorry messages display problem" is fix.
