### ISSUE TITLE
Date Modified

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#2576]
Hi Daniel,

I noticed that field 'modified' is changed to the last timestamp of viewing that video.
So it is difficult for me to show a list of the last modified videos.

Regards, Theo

**Comment by DanielnetoDotCom** [comment]
humm, I see, for now I do not have a solution for that.

**Comment by TLCReuver** [comment]
No problem, i handle it by cron now
$sql = "UPDATE videos SET modified = created";
I noticed that MMB29P (think google crawler) do sometimes requests on modified_field.
But anyway thanks.

**Comment by DanielnetoDotCom** [comment]
Maybe we have to think that way ...

when should we say it is modified.
when change title and description only?
when get a new comment? new view?

not sure when to considere modified, but right now any table change is considered modified.

**Comment by TLCReuver** [comment]
I think that you can limit it to the primary information that a user used for his video.
These are only title and description because images are not often changed.
You can always made a toggle for comments if needed.
