### ISSUE TITLE
Direct upload from client to backblaze

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2579]
Does direct upload with the b2 backblaze plugin upload the mp4 from client to the aVideo server then from the aVideo server to the backblaze pod servers?

**Comment by DanielnetoDotCom** [comment]
Correct!

**Comment by millzee01** [comment]
ok thanks, do you think this is achievable?
https://stackoverflow.com/questions/37554667/upload-to-backblaze-from-client?noredirect=1&lq=1

Am just looking into potentially modifying the code to cut out 50% of the server bandwidth usage now b2 supports custom CORS

**Comment by DanielnetoDotCom** [comment]
I do not think so, on youphptube, the streamer must receive the file first to process it.

or maybe you can do with a lot of modifications, what I think does not worth

**Comment by millzee01** [comment]
i'll monitor it,  if more and more users upload at the same time then it'll probably be something i'll look into more.  thanks again!
