### ISSUE TITLE
Request Entity Too Large error when uploading a video

### ISSUE THREAD

**Issue by daynthishoho** [WWBN/AVideo#2580]
Im using a vm to run youphptube and i always get this error when i upload files that is higher than 100mb

Request Entity Too Large
The requested resource
/view/mini-upload-form/upload.php
does not allow request data with POST requests, or the amount of data provided in the request exceeds the capacity limit.

i changed memory_limit, post and upload max size but still gets this error. 
is there a way to fix this?

**Comment by akhilleusuggo** [comment]
@daynthishoho 
1- `sudo nano /etc/php/7.2/apache2/php.ini`
2 - `upload_max_filesize = 2048 ` #For 2 gb
3 - `post_max_size = 2048 ` #For 2 gb
4 - make sure you're not using CloudFlare ( you can't upload files larger then 100mb ) , more info here https://github.com/WWBN/AVideo/wiki/About-Video-Upload

**Comment by daynthishoho** [comment]
i already changed that fields before on php.ini, and on nginx and still get the error.

but i found out that the limit was coming from modsecurity:
Apache-Error: [file "apache2_util.c"] [line 271] [level 3] [client 127.0.0.1] ModSecurity: Request body (Content-Length) is larger than the configured limit

ill close this issue now
