### ISSUE TITLE
All videos start muted

### ISSUE THREAD

**Issue by vielsaitig** [WWBN/AVideo#2581]
I don't know why, but in the recent version all Videos are being played without sound (muted). I cannot find any settings regarding this behaviour. And I didn't have that problem before the latest update.

**Comment by akhilleusuggo** [comment]
You got a screen explaining everything .
What didn't you understood ?
```
Your Media is Muted
Would you like to unmute it?
Permanently unmute videos and allow autoplay
upon startup pressing Ctrl+Alt+S
logging in
opening a Chrome browser and typing: chrome://flags/#autoplay-policy
changing the "Autoplay policy" from "Default" to "No user gesture is required"
pressing "relaunch"
rebooting the device
```

**Comment by DanielnetoDotCom** [comment]
Also check this https://github.com/WWBN/AVideo/wiki/Autoplay-and-Browser-Policies

**Comment by vielsaitig** [comment]
Thanks for the info... I don't like that behavior, but there seems to be no way around that...
