### ISSUE TITLE
Click the Skip Ad button and the following video does not start at the beginning

### ISSUE THREAD

**Issue by vielsaitig** [WWBN/AVideo#2582]
After clicking the "Skip Ad" button the following main video starts some seconds in. So basically the main video already plays during the advertising. Of course the main video needs to start at the beginning. Also seems to be a but in the latest update.

**Comment by DanielnetoDotCom** [comment]
Maybe the video starts from the last position.

the script memorize the last view position.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom No Daniel , I'm using GoogleAds_IMA (GoogleAds_IMA) plugin , and i'm having the same problem , even in a new video

**Comment by DanielnetoDotCom** [comment]
can you guys please make sure you update the plugin to the latest version? there were some modifications the way the plugin loads.

If still the problem, please let me know.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I've played the video on different browser , private windows to make the video not start from the last point . Same issue .
If the plugin has selected the Start Ad at the Start , the video and ad are playing both at the same time

**Comment by DanielnetoDotCom** [comment]
I see, is it possible to reproduce on demo site?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom For some reason , I can't play any media on your demo site , only live streams . 
![image](https://user-images.githubusercontent.com/52116577/73568328-de033700-4470-11ea-9f66-7ca7419b23a9.png)

If the videos does not play , I can't reproduce the test on the demo site

**Comment by DanielnetoDotCom** [comment]
Sorry, try again

**Comment by akhilleusuggo** [comment]
The plugin GoogleAds_IMA doesn't work at all . I've added the tag line : 
`http://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=40000&adtest=on` For the test from the get approval link . It's working on my site , but on demo is not working . 
https://support.google.com/adsense/answer/1705823
PS: I do have disabled ad-block , no results

**Comment by DanielnetoDotCom** [comment]
You have to disable the other ads plugin, 4jesus and adsserver

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom No changes

**Comment by DanielnetoDotCom** [comment]
Google is giving me the error 403, so it is blocked for our demo site for some reason.

![image](https://user-images.githubusercontent.com/18009293/73584131-1ad12d00-4475-11ea-8de7-9bddfe95d327.png)


you can use the 4jesus.tv link, it will not block anyone

https://vast.forjesus.tv/vast.xml

So I guess  the Plugin is working now

**Comment by vielsaitig** [comment]
I've updated the AD_Server plugin and there is no change when skipping the ads. Skipping the ad and the main video starts exactly at the time where the ad stopped (for instance 5 seconds ad and the main video starts at 5 seconds).
