### ISSUE TITLE
Safari problems - again!

### ISSUE THREAD

**Issue by vielsaitig** [WWBN/AVideo#2583]
The video previews don't work in the latest update. This was already fixed in #2424 and seems to be be a problem again!

**Comment by DanielnetoDotCom** [comment]
can you please check if your ssafari is loading a webp or a gif?

**Comment by vielsaitig** [comment]
Safari is loading webp but needs animated gif!

**Comment by DanielnetoDotCom** [comment]
Hi, I found another bug, it may be fixed now

**Comment by vielsaitig** [comment]
Hi Daniel, sorry, but there is still the webp loaded instead of the gif.  Interest is just, that there are a view videos where the gif is loaded and so it is working on these (just a few) videos. On the not working videos I tried to find the gif -- and when I change the .webp to .gif in the browser developer tools it shows, that the gif is there and would work if the link would work correctly in Safari.

**Comment by DanielnetoDotCom** [comment]
@vielsaitig I just test the demo site on safari and it works.

maybe you are seeing the cache in your site, make sure you delete the cache folder before test it.

**Comment by vielsaitig** [comment]
I've deleted the cache (internally and Safari cache) -- no change here...

Something strange: some videos load the gif correctly (see image upper tile). Some load the webp (see image lower part), which safari cannot load. 

![image](https://user-images.githubusercontent.com/59013822/73746270-19458480-4755-11ea-9041-135b2b7b2089.png)

![image](https://user-images.githubusercontent.com/59013822/73746364-527df480-4755-11ea-85a1-0ad1b2e00056.png)

**Comment by DanielnetoDotCom** [comment]
can you please check if the same happen on demo site?

**Comment by vielsaitig** [comment]
Demo site works... I don't know what to do actually. I can (again) run an update. But whenever I run an update, something else is broken as it seems...

**Comment by DanielnetoDotCom** [comment]
The only thing I can think is you are not running the same version as I am.
