### ISSUE TITLE
stop blank videos being shown on videos page

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2584]
If a direct upload fails or the browser gets restarted during an upload then the video record is created in the db without a filename.

I have a cron job that deletes videos without filenames at midnight each day to counter this however to stop blank videos from being shown on the videos page i have added ` AND filename != '' ` to the sql statement in getAllVideos() within /object/video.php which seems to work well.

am i correct in thinking every video record should have a filename?

**Comment by DanielnetoDotCom** [comment]
I probably right, all video records should have a filename.

**Comment by millzee01** [comment]
thanks
