### ISSUE TITLE
B2 response ERROR: 503

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2585]
When we get a b2 error 503 in the log does the script automatically retry the copy operation?

[31-Jan-2020 14:48:30 UTC] BlackBlaze response ERROR: 503
[31-Jan-2020 14:48:30 UTC] BlackBlaze response ERROR Body: {
  "code": "service_unavailable",
  "message": "Tome is overly busy",
  "status": 503
}

apparently this happens from time to time with b2

**Comment by DanielnetoDotCom** [comment]
that is why on the B2 code we retry to upload up to 10 times.

**Comment by millzee01** [comment]
when it fails does the record get marked in any way? because i've had several fail today and the records stay in the db.  If i wanted to mark the video record as failed for deletion then can i do it or Is the code in the encrypted plugin?

**Comment by DanielnetoDotCom** [comment]
I see, 

sorry but right now we do not have this option, but we can sell the plugin source code for extra 100 USD.

If you are interested in the source code, please contact me at developer@youphptube.com

**Comment by millzee01** [comment]
hi i'll definitely look at getting the source as i think it'll be handy for my setup.  Will ping you in the next few days after i've finished the stuff im working on.
