### ISSUE TITLE
Paypal Error

### ISSUE THREAD

**Issue by jarredmoore** [WWBN/AVideo#2589]
I keep getting an "Error" popup when I try to subscribe the Subscriptions I created. I followed all the steps here https://github.com/WWBN/AVideo/wiki/Subscription-Plugin and I don't see anything in avideo.log logs
![Annotation 2020-01-31 161706](https://user-images.githubusercontent.com/7459434/73578517-7c79a300-4445-11ea-9493-77b0ab7f1747.jpg) any suggestions?? maybe a differnt log??

**Comment by jarredmoore** [comment]
I used this link to find errors https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform..

**Comment by DanielnetoDotCom** [comment]
Hi

Must be something on the log, but you must provide the log right after the PayPal attempt.

But the main error reason is the wrong credentials

**Comment by jarredmoore** [comment]
Sorry I don't usnderstand..

**Comment by DanielnetoDotCom** [comment]
You provide the log information at the wrong moment . You probably had the PayPal error some time before you get the log file.

In your log have only upload information. 

Try this, delete your log file, try to use PayPal, and nothing else. The erro popup Will appear, then share your log here

**Comment by jarredmoore** [comment]
deleted the log file, hit the subscribe button and got this.. 
![Annotation 2020-01-31 175437](https://user-images.githubusercontent.com/7459434/73582474-fcf2d080-4452-11ea-9a07-15cb6e83de74.jpg)

**Comment by DanielnetoDotCom** [comment]
Ok, then looks like the PayPal request neve reach your server.

Please screenshot or record a video of what are you trying to do.

Also please you need to inspect your XHR request in your browser develop tools-> network

What is your site URL?

**Comment by jarredmoore** [comment]
I want to offer three paid montly subscriptions to users. I removed two of them earlier when I was troubleshooting. I followed the steps here https://github.com/WWBN/AVideo/wiki/Subscription-Plugin 

I took a peek at the XHR requests a little earler as well. It's still showing a 200 status

![Annotation 2020-01-31 1754377](https://user-images.githubusercontent.com/7459434/73583549-7a6d0f80-4458-11ea-9ebf-bf7988fd7c8b.jpg)

My site url is https://www.divinecreative.us/

**Comment by DanielnetoDotCom** [comment]
Ok, I am checking it directly into your site, I will update you soon

**Comment by jarredmoore** [comment]
Okay, Thank You

**Comment by DanielnetoDotCom** [comment]
Ok, I went to check your plan, and I notice you have an empty amount of days

![image](https://user-images.githubusercontent.com/18009293/73583984-fa54a300-4473-11ea-9712-ce0d4b18c3a5.png)

you plan has to renew after a certain amount of days, I guess you want it to renew each 30 days

Once I changed the "How many days" to 30 looks like is working

**Comment by jarredmoore** [comment]
🤦🏽‍♂️😃 Thanks, I missed that!

It worked for me however it took me to a page that only had the option to sign in or create an account with Paypal account. Is there a way to show the "Pay with a Card" option on this page?? I noticed in the url it said express in the url and though maybe that had something to do with it..

![Annotation 2020-01-31 1859ff52](https://user-images.githubusercontent.com/7459434/73584295-0123eb80-445d-11ea-922d-39d615d6b71a.jpg)

Also when I clicked the return to my website link at the bottom of the page I got this error page with a Stripe url??

![Annotation 2020-01-31 185952](https://user-images.githubusercontent.com/7459434/73584372-8909f580-445d-11ea-8602-111ef49fe098.jpg)

**Comment by DanielnetoDotCom** [comment]
The not found is fixed, sorry my bad.

If you want to use just a credit card popup you should try [Stripe ](https://stripe.com/) instead of PayPal

**Comment by jarredmoore** [comment]
Will do, Thanks Again
