### ISSUE TITLE
video editor - slice video etc

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2590]
Hi, i've added a video editor tab into the video form which allows me to easily slice videos and save them out.  I plan to add extra functionality like adding text to video and overlays etc.

When i save the exported video (ffmpeg out) i save it to the videos folder,  all good so far however i'm trying to find the best way to import the video into the db and save it over to backblaze.

is there something already in place that I can hook into to add the video to the db and ping it over to backblaze?  something like a local import?

**Comment by DanielnetoDotCom** [comment]
Hi, 

that is an awesome idea.

I guess you can try to "Upload" it to the streamer thru cURL, please check this https://github.com/WWBN/AVideo/wiki/About-Video-Upload

But this is for new videos only. are you trying to edit a pre existent video?

If yes you should try this to move your videos from the video directory to your BackBlaze bucket

```
require_once '../../videos/configuration.php';
require_once './Blackblaze_B2.php';

$b2 = new Blackblaze_B2();
$sourceFile = "[Path from the source file]";
$filename = "[Original file name]";
$result = $b2->move_uploaded_file($tmp_name, $filename);
```

**Comment by millzee01** [comment]
hi, at the moment i'm creating a new video but want to have a button that allows me to create a new clip of the current loaded video.

i'll have a play and see if i can get it uploaded to b2 as a new video first then try and edit a current video.

thanks for the advice!
