### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#2591]
i want to ask you about software upgrade
A) plugins are updated at the same time? or another command is needed?  if yes which one?
B) the database is updated separately? or together with the software upgrade?

Thank you in advance
Ilias

**Comment by DanielnetoDotCom** [comment]
> A) plugins are updated at the same time? or another command is needed? if yes which one?

Only free plugins are updated with the core code. the paid plugins, if you want to update, you have do download again and overwrite the one on the site.

> B) the database is updated separately? or together with the software upgrade?

If there is a database update you will see this

![image](https://user-images.githubusercontent.com/18009293/73592196-74b60f00-44d6-11ea-902a-97c93463f3be.png)

Make sure you do not skip any database update.

The plugins database update is separate. once you update the files or overwrite the paid plugins you will see this

![image](https://user-images.githubusercontent.com/18009293/73592229-ca8ab700-44d6-11ea-9b8d-8c014182a233.png)

**Comment by wetubeclub** [comment]
thank you Daniel for your response
A) plugins are updated at the same time? or another command is needed? if yes which one?

Only free plugins are updated with the core code. the paid plugins, if you want to update, you have do download again and overwrite the one on the site.


 i have all the addons installed on the site,
you had installed when i bought them and i don't have the files
how can i download them and from where?

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
Hi, email me at developer@youphptube.com a screen shot of your plugins page with your user ID number

you can find your user ID number on the side of your logoff button (you need to login first), I will enable the plugins for you to download.

![image](https://user-images.githubusercontent.com/18009293/73593545-2f004300-44e4-11ea-953c-bc1579839ae6.png)

**Comment by wetubeclub** [comment]
I have send to your email

thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
Got it and answer it.
