### ISSUE TITLE
The problem with TWO menu items and work with categories

### ISSUE THREAD

**Issue by SergejGrin** [WWBN/AVideo#2592]
Hello everybody!
I ask the help of experienced users and developers of this wonderful program.
Everything works fine, but there is a problem with two items in the administrator’s main menu.
After installing the AVideo, the menu worked completely, but then two items stopped opening - error 502
1. Dashboard (statistics panel)
2. Admin Panel
![tube1](https://user-images.githubusercontent.com/59236880/73597173-98ef0b80-4529-11ea-80b2-11244e74df30.png)
All other menu items open and work without problems.
Tell me what is the problem? What to do and how to fix this error?
![tube2](https://user-images.githubusercontent.com/59236880/73597192-c471f600-4529-11ea-96c0-e1c559012a14.png)
The second question: during the filling of the site with video clips, due to my carelessness, one video was assigned the wrong category.
How can I move a video from one category to another? Or should it be converted again with the correct category?
I would be grateful for any advice and help.

**Comment by akhilleusuggo** [comment]
Answer to you second question:
Go to videos , select the video . Click on categories , and select the desired category .
You can even change the owner user of the video ( if you're admin )

About your first question , I think some logs are needed to understand what is going on

**Comment by SergejGrin** [comment]
Yes, really with the categories everything turned out to be very simple. Thank you **akhilleusuggo** for the tip.
Regarding the first question: here is a log of attempts to open these menu items
[avideo.log](https://github.com/WWBN/AVideo/files/4144121/avideo.log)

**Comment by DanielnetoDotCom** [comment]
@SergejGrin there is nothing in your log that helps.

but I could notice you are using NGINX as your webserver (I can not help you much), we recommend apache.

502 Bad Gateway in Nginx commonly occurs when Nginx runs as a reverse proxy, and is unable to connect to backend services. This can be due to service crashes, network errors, configuration issues, and more

https://bobcares.com/blog/502-bad-gateway-nginx/

**Comment by SergejGrin** [comment]
Thank you, Daniel, but here's the interesting thing - the server was configured before it started and worked without problems for several days. Server system settings have not changed. Then the access ONLY TO TWO menu items disappeared. All others open without problems. I will try to change the settings, but it is strange that at first everything worked, and then only two local problems arose.
The only thing I did was turn on the CustomizeAdvanced plugin, then turn it off. Now I turned it on again, I wanted to make sure that in its settings there are no such items that affect these two menu items. Perhaps something was incorrectly registered in the database during these manipulations?

**Comment by DanielnetoDotCom** [comment]
the CustomizeAdvanced plugin is not possible to disable, it by default is always enabled.

But I do not think it is anything related to the plugin, I guess is something related to the dashboard.

Admin menu also loads the dashboard. as long as I can not reproduce it, I can not help.

**Comment by SergejGrin** [comment]
Thank you for your reply Daniel.
Why is it not possible to disable the plugin? There is a slider 'Off-On'. What help is needed to reproduce this error? I have this error for the second time. Two times I completely reinstalled the system and somewhere when decoding and downloading 40-45 video clips I received it. Now there are 110 rollers and again reinstalling a little difficult. What is the most correct way out of this situation?
![tube1](https://user-images.githubusercontent.com/59236880/73659654-fbb1e580-4696-11ea-8287-d457dbb8fab6.png)

**Comment by DanielnetoDotCom** [comment]
even if you turn off, it will still loading.

I am sending an update to avoid confusion

**Comment by DanielnetoDotCom** [comment]
I do not use NGINX as webserver, so I guess is not possible to me to reproduce it.

**Comment by SergejGrin** [comment]
I also have Apache. But access to the global network goes through the ISP manager panel (NAT and proxies through Nginx)

![tube2](https://user-images.githubusercontent.com/59236880/73666788-9e706100-46a3-11ea-9b64-1ccd50d474f1.png)
![tube3](https://user-images.githubusercontent.com/59236880/73666789-9e706100-46a3-11ea-8bf6-f41266b891ce.png)

I can reinstall and change the whole system configuration once again, but what about 110 video clips (110 GB)? Can they be transferred to a new system without conversion?

**Comment by akhilleusuggo** [comment]
@SergejGrin If you have videos mp4 ( converted ) , use the plugin CloneSite (CloneSite) , will clone everything .
If you have HLS , you can't use this plugin .
If you wanna make a manual buck-up , I recommend you `tar -cvpf` to conserve permission .
The flag `-p` is the important thing here 
This happened to me , I've lost some permission and I had to change permissions manually for each folder .

**Comment by SergejGrin** [comment]
Many thanks to you Daniel. I will try this plugin. But I think that reinstalling nothing will help. I have analyzed the system and the situation and I think that still there is a problem with the code of the program for these two menu items. The rest of the items work fine! Therefore, please pay attention to this.

**Comment by SergejGrin** [comment]
Hi Daniel!
Today a miracle happened - for a while the menu item - Administrator Panel and an error message (see figure) opened.
How can this be fixed?
![tube1](https://user-images.githubusercontent.com/59236880/74254570-e9682500-4cf0-11ea-99d6-d16123a988df.png)

**Comment by DanielnetoDotCom** [comment]
check your error log file.

**Comment by SergejGrin** [comment]
Unfortunately, I am not good at reading error logs. I am surprised by the fact that the program works great, all menu items work except two.

**Comment by akhilleusuggo** [comment]
@SergejGrin `cat -n /var/www/html/AVideo/video/avideo.log`

**Comment by SergejGrin** [comment]
@akhilleusuggo Thank you for your help!
I don’t see any errors in the log, but I found such an entry:
[12-Feb-2020 10:41:46 UTC] encryptPasswordVerify: encrypt
[12-Feb-2020 10:41:46 UTC] user::login: Do login without cookie
[12-Feb-2020 10:43:08 UTC] **Plugin Not Found: Statistics**
What is this plugin? Where can I find it and how to install it?

**Comment by DanielnetoDotCom** [comment]
This plugin is not released yet, do not worry about it.

But I am pretty sure you may find something else in your logs.

**Comment by SergejGrin** [comment]
Does the name of the folders matter? In my case, the path to the log folder 
/var/www/html/**YouPHPTube**/video**s**/avideo.log

**Comment by SergejGrin** [comment]
Is this a mistake or should it be so?
14-Feb-2020 02:39:27 UTC] Warning: The plugin [CustomizeAdvanced::getModeYouTube] takes 0.0974 seconds to complete.

**Comment by DanielnetoDotCom** [comment]
@SergejGrin your log path is correct

the CustomizeAdvanced::getModeYouTube is just a warning, ignore it.

**Comment by SergejGrin** [comment]
> @DanielnetodotCom This plugin is not released yet, do not worry about it.

Isn't this the statistics plugin pointed out by the log?
![tube2](https://user-images.githubusercontent.com/59236880/74538074-b1a0ed80-4f3b-11ea-89ae-431b782768c1.png)

**Comment by SergejGrin** [comment]
Hi Daniel
Today I tried to update the program files and got this

![update](https://user-images.githubusercontent.com/59236880/75632071-dadaa280-5bf8-11ea-98b8-c40f18416104.png)

Perhaps this is somehow related to the problem of two menu items?
What should I do now?

**Comment by DanielnetoDotCom** [comment]
@SergejGrin here https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform#problems

**Comment by NAndras95** [comment]
I have this issue too, Im using this versions:
Apache/2.4.38 (Debian) is Present
PHP 7.2.34 is Present
Avideo: 8.4
