### ISSUE TITLE
Thumbnail Load Speed

### ISSUE THREAD

**Issue by jjacobs1** [WWBN/AVideo#2593]
Recently I noticed that the thumbnails on our site takes a few seconds to load. It actually seems to load a low res version and eventually the higher one loads.

The site never did this before and I'm starting to work backwards to see what changes I made. I added a few plugins but that doesn't seem to be the issue. I did a a symlink recently and moved all our videos to a new virtual disk in Azure but both the new disk and the OS are set as SSD Premium disks. I followed > https://github.com/WWBN/AVideo/wiki/Moving-videos-directory-and-securing-files-from-direct-access-to-the-video-source-file

Videos and the site seem to load fine, its only thumbnails. So i don't think its anything to do with storage/server speed or the symlink?

Main Site - https://streaming.shmd.org/

Example: 
GIF - **This loads fine on its own but not on the main page.
https://streaming.shmd.org/videos/_YPTuniqid_5e025fd6bef9e0.91773396.webp?download=1 

JPG - https://streaming.shmd.org/videos/_YPTuniqid_5e025fd6bef9e0.91773396.jpg?1580012663

PNG - ** Does not load, maybe part of the issue?
https://streaming.shmd.org/view/img/notfound_portrait.jpg?download=1

MP4 - https://streaming.shmd.org/videos/_YPTuniqid_5e025fd6bef9e0.91773396_HD.mp4?download=1

Is the site suppose to display the JPG /PNG first and then the GIF?

**Comment by akhilleusuggo** [comment]
@jjacobs1 You can disable cache/asycjobs
You will get better results , but gonna load slower due to the db query pull

**Comment by jjacobs1** [comment]
I upgraded to 8.4 and its a lot better now.
