### ISSUE TITLE
Youtube Upload: (Swall) Message windows with visible html code

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo#2596]
As subject, after uploading a video to youtube, there is a modal window (swall) that show the html code.
See the picture, please.
(The procedure is OK and the video was uploaded in youtube without errors, but this windows can confuse the final user)

![YoutubeUpload](https://user-images.githubusercontent.com/5683921/73604452-41848600-4591-11ea-8a5e-b4608ef78198.png)
SweetAlert error

I think that we need to change the "text:blablabla" with "html:blablabla"

**Comment by maxlinux2000** [comment]
No here you are not using Sweet Alert.
The problem is in:
objects/youtubeUpload.json.php
at line 108
I don't understand why use sprintf...

**Comment by DanielnetoDotCom** [comment]
@maxlinux2000 in what exactly page did you get this error?

**Comment by maxlinux2000** [comment]
I followed this video tutorial from youphptube, in the latest version of AVideo (8.4)

https://tutorials.youphptube.com/video/5/enable-google-auth-and-youtube-uploader-ver-3-4?channelName=yeshua

the message with the html code visible, is what appears in minute 3.18 of this old version of youphptune that you used to record this tutorial

**Comment by DanielnetoDotCom** [comment]
Please update and try it again

**Comment by maxlinux2000** [comment]
Hi I just updated, but now I can't list the videos, so I can't try this bug

![xdaniel2](https://user-images.githubusercontent.com/5683921/73658053-dcfe1f80-4693-11ea-864f-12dbe98418c2.png)

**Comment by DanielnetoDotCom** [comment]
Sorry my bad

**Comment by maxlinux2000** [comment]
Sorry Daniel but it still occurs.
![xdaniel4](https://user-images.githubusercontent.com/5683921/73660326-408a4c00-4698-11ea-9e89-384694bc9a80.png)


![xdaniel3](https://user-images.githubusercontent.com/5683921/73660340-47b15a00-4698-11ea-9429-127e7ffc7f86.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure where does it comes from. I can not find anything wrong.

can you please check the XHR response from the youyube upload request?

**Comment by maxlinux2000** [comment]
This can help you?
I'm not sure, but seem that there is a double html codification.

![xdanie5](https://user-images.githubusercontent.com/5683921/73741076-cd411280-4749-11ea-8c60-5bd104a2b2d7.png)

And then there is an annoy problem with mixed containing because there is 1 thumbnail that is served with http instead https, But if you prefer I can open another bug for that

![xdaniel6](https://user-images.githubusercontent.com/5683921/73741077-cd411280-4749-11ea-9896-84c13ded01d4.png)

**Comment by DanielnetoDotCom** [comment]
Is almost that what I am looking for.

click in the network tab reload your page, filter for youtubeUpload.json.php, click in the upload and check the response

![image](https://user-images.githubusercontent.com/18009293/73744423-821a0600-472f-11ea-9e46-38985130b249.png)

**Comment by maxlinux2000** [comment]
![xdaniel7](https://user-images.githubusercontent.com/5683921/73748067-fddc7880-4758-11ea-9bf6-e4d634d3a0c0.png)

**Comment by DanielnetoDotCom** [comment]
Hi, thanks.

I think I found the problem

**Comment by maxlinux2000** [comment]
OK this is fixed! :-)

![xdaniel9](https://user-images.githubusercontent.com/5683921/73877351-cbb24000-4858-11ea-9634-fd7ea9db1d74.png)
