### ISSUE TITLE
Videos not displaying on home page

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#2597]
I removed a video from PPV and now none of my videos are showing on the home page.  It just displays this message:  Warning! We have not found any videos or audios to show.
All of the videos are still there I didn't make any changes to anything just remove a single video from PPV, .  The home page still displays to me as the admin, but to public and other users, it just shows the error message. Please advise.

**Comment by heiress01** [comment]
Ok, so I unchecked hidePrivatevideos on the gallery plugin and that solved the problem.  But, now how do I keep videos from public view when they are private?

**Comment by DanielnetoDotCom** [comment]
Hi

what exactly do you want to do?
uncheck hidePrivatevideos will show the videos in the main page, but when a regular user click on it, it will be requested for a PPV

**Comment by heiress01** [comment]
Got it ty.
