### ISSUE TITLE
PPV request

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#2599]
Can the same link to PPV,  be added on the video play button itself, so when the video is clicked it goes to the same link (place) as when the pay-per-view words are clicked?  Because, currently when a PPV video play button is clicked it's redirected to the update your user page with a pop-up that says: "Ops! Sorry this video is private"

**Comment by DanielnetoDotCom** [comment]
Humm, this not suppose to be that way. when you click in a PPV link it suppose to go to the payment page or to the signup page if you are offline.

Check this video, it is a PPV. https://demo.avideo.com/video/248/2020-01-24-17-07-15?channelName=TheAdminChannel

Just to make sure we are on the same page. please update your streamer site and your PPV plugin.

**Comment by heiress01** [comment]
The PPV link works correctly, it's the actual video that redirects to update your user page with that pop-up.  It seems that the viewer has to search for the PPV link, that is under the video,  It would be easier if the video itself was redirected to the PPV pricing info instead of going to the update user page.

**Comment by DanielnetoDotCom** [comment]
Hi

Sorry I am confused. can you please detail a bit more the steps that happen and the ones that suppose to happen?
