### ISSUE TITLE
cache plugin

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2602]
hi,

when i have the cache plugin enabled i notice that when im logged in with a test user after a certain amount of time i have to re log in.  It only happens with the cache plugin active so wonder if this is normal?

**Comment by DanielnetoDotCom** [comment]
Does this happen even if you have the remembe me checked?

**Comment by millzee01** [comment]
i am using the api to log in from another page.  to temp fix it i call the api when i open the link from my test page but wondered if the cache plugin ends a session after a certain time

**Comment by DanielnetoDotCom** [comment]
no, the cache plugin has nothing to do with it.
I am pretty sure you also can send the "remember me" variable from another page

**Comment by millzee01** [comment]
cool, i'm just using:

`get.json.php?APIName=signIn&user=test&pass=f321d14cdeeb7cded7489f504fa7762b&encodedPass=true`

is there something like rememberme=true?

**Comment by DanielnetoDotCom** [comment]
yes, I guess that is it

**Comment by millzee01** [comment]
i don't think the api posts rememberme so i hard coded it to 1 in user.php as we don't allow signup or standard login.  Seems to have done the trick

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom In my case is not the same . It's not about API ; simple after login/logout , the cache is recreated . I would have understand that if I had the 

- enableCachePerUser
- enableCacheForLoggedUsers

but I don't have them enabled , only asyncjobs
