### ISSUE TITLE
Error performing query

### ISSUE THREAD

**Issue by SebyPlays** [WWBN/AVideo#2603]
Hey, i was currently setting up aVideo, and when i clicked on the Install button
and i got the following error ;

Sorry!
Error performing query '<strong>
ALTER TABLE `videos`
ADD INDEX `videos_status_index` (`status` ASC),
ADD INDEX `is_suggested_index` (`isSuggested` ASC),
ADD INDEX `views_count_index` (`views_count` ASC),
ADD INDEX `filename_index` (`filename` ASC);
': Specified key was too long; max key length is 767 bytes<br /><br />

i dont know what to do now, can anyone help?

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/WWBN/AVideo/issues/2574

About your SQL error it is a MariaDB problem upgrade it to version 10.2 or greater
I really recommend MySQL instead MariaDB, but upgrade MariaDB should do the trick
