### ISSUE TITLE
Youtube API

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2604]
Anyway to converse the tags when bulk embedding videos from YouTube API ?
When I bulk embed a playlist , the script does create the playlist automatically , can do the same with tags ?

**Comment by DanielnetoDotCom** [comment]
Hi, I  can not add it right now, but definitely I will add it in the future

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Thank you :)
