### ISSUE TITLE
Direct upload - edit b2

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2605]
Hi,

When direct uploading a video, 
After the video has been uploaded to the server i'd like to intercept the copy request to b2 and allow  the video to be edited (cut, crop, add text and watermark image) whilst the file is on the server,

at what stage in `$('#upload').fileupload({` does the b2 copy request happen? or does the upload.php manage that?

If my mod works well i'll ping it over as i'm sure it will be a handy feature for others.

**Comment by DanielnetoDotCom** [comment]
sorry, do you mean you want to get the uploaded file URL?

**Comment by millzee01** [comment]
When the file is uploaded to my server I just thought it would be easier to edit it before the file gets transferred to the b2 servers.

**Comment by DanielnetoDotCom** [comment]
to do this I guess you will need to change the original B2 plugin.

**Comment by millzee01** [comment]
sweet,  for now we'll see how it performs when we go live then look at purchasing the b2 plugin code.
