### ISSUE TITLE
Captcha not appear

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#2606]
Hello Daniel,
i have a problem with the captcha image does not appear when the site is in greek
appears in all other languages normally
some help with this problem?

Thank you
Ilias

![capcha](https://user-images.githubusercontent.com/60543030/73746250-0f238600-4755-11ea-904a-69a905517021.jpg)
![captcha us](https://user-images.githubusercontent.com/60543030/73746251-0f238600-4755-11ea-84be-203dd2b43695.jpg)

**Comment by DanielnetoDotCom** [comment]
Check your log file, it may be something else because it is working on demo site

![image](https://user-images.githubusercontent.com/18009293/73752126-22c3f200-473f-11ea-880a-6a5a44cb6bd3.png)

**Comment by wetubeclub** [comment]
must have been the problem from the language file
i did a new one and the captcha is showing right now!

Thank you
Ilias

**Comment by thushy07** [comment]
watubeclu, how did you fix this. i have the same issue even with English default language

**Comment by wetubeclub** [comment]
in English it worked normally in my case
the problem I had was when I changed the language
I replaced the language file and it worked fine

**Comment by thushy07** [comment]
Ok thank you, how did you replace the language file, i am new to this 
thanks

**Comment by wetubeclub** [comment]
the language files are in the folder **locale** 
change if you want the entire locale file
to test it if it works in English
if not, somewhere else is your problem with captcha

Thanks
