### ISSUE TITLE
Sitemap XML coming up with errors..

### ISSUE THREAD

**Issue by alexious** [WWBN/AVideo#2607]
https://avideo.com/sitemap.xml

https://tutorials.avideo.com/sitemap.xml

https://demo.avideo.com/sitemap.xml

Sitemap XML coming up with errors..   http://gdrive.local/YouPHPTube/channel/5d4d867c0339c

**Comment by akhilleusuggo** [comment]
@alexious You talking ''only'' about the demo site or your site ?
On my site everything works fine

**Comment by alexious** [comment]
Probably just our sites then..

**Comment by DanielnetoDotCom** [comment]
Or you did not create the site map, or you did not gave the correct file permission

![image](https://user-images.githubusercontent.com/18009293/73838199-e43b3f80-47f1-11ea-8bf6-e1e775a427ac.png)
