### ISSUE TITLE
MP3 files are saved as Video

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#2608]
Hi Daniel,

Uploading a *.mp3 file is handled as video and not as audio in 'type'-field and can't be played.
(Snapshot from demo-site)

![Snap1](https://user-images.githubusercontent.com/39981177/73760941-62ee9900-476e-11ea-8968-203e8c4cb4c7.jpg)
![Snap2](https://user-images.githubusercontent.com/39981177/73760969-6e41c480-476e-11ea-865d-d2d16ea15a4a.jpg)

**Comment by DanielnetoDotCom** [comment]
Thanks for notice it.

Please update and try again.

**Comment by TLCReuver** [comment]
MP3's is working perfect now.

During the weekend i have also problems with *._thumbsSmallV2.jpg & * _thumbsV2.jpg which doens't created but this issue is also fixed during the last update,

Many thanks.
