### ISSUE TITLE
mvideos page polling encoder

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2609]
Hi,

Is there a readon why the mvideos page constantly poll the encoder?

looking in my networking log i get lots of:

{"queue_size":0,"is_encoding":false,"queue_list":[],"msg":"There is no file on queue","encoding":false,"cmd":"","encoding_status":""}

**Comment by DanielnetoDotCom** [comment]
If you are using the network and your video is not being encoding on the main encoder, it will not show progress on the mvideos page.

In the future we will send an update to fix it.

**Comment by millzee01** [comment]
sweet,  we don't use network encoder.  Have Just noticed its polling when i'm on the page doing nothing.
