### ISSUE TITLE
how can I change this message and the background image

### ISSUE THREAD

**Issue by awistudio** [WWBN/AVideo#2610]
how can I change this message and the background image

"The media could not be loaded, either because the server or network failed or because the format is not supported."
![kas1](https://user-images.githubusercontent.com/60708776/73866795-bed82100-4845-11ea-85b0-256049e1a36f.jpg)

**Comment by DanielnetoDotCom** [comment]
This message comes from videojs lib.

you probably needs to inspect and hardcode the message in videojs files

P.S. I do not recommend you change it. maybe you can try to use the videojs translation
Check this.
https://docs.videojs.com/tutorial-languages.html

**Comment by maxlinux2000** [comment]
Seem a bug of video.js.
I tried to put the ES into the EN files (both) and there are no change. Apparently video.js don't use the localized files that come as default.

**Comment by maxlinux2000** [comment]
Daniel, 
please have a look to this bug  https://github.com/videojs/video.js/issues/3199

seem that is necessary to add the language, like this example:
```
  <script src="http://vjs.zencdn.net/5.8.0/video.js"></script>
  <script src="http://vjs.zencdn.net/5.8.0/lang/de.js"></script>
```
but I don't see it in haders of AVideo.
Can be this the problem? 
Or the languages.js, are loaded in another way from the code?

**Comment by DanielnetoDotCom** [comment]
Yes I was expecting you to add something like this.
But I guess you are right, right now there is no way to add the lang file in the correct position. Only if you hard code it.

**Comment by maxlinux2000** [comment]
mmm... do you think that can works adding the langiage.js in the script texzone?... like this?

![xdaniel14](https://user-images.githubusercontent.com/5683921/73933358-93ecdc00-48dc-11ea-93c1-3f3f22fb9f9b.png)

**Comment by DanielnetoDotCom** [comment]
I do not think this will work, the way to have it to work is to add this line right after the video.js js file.

right now it is not possible.

**Comment by awistudio** [comment]
I solved the problem.
change player.css
.vjs-modal-dialog-content {
    opacity: 0;
}

**Comment by maxlinux2000** [comment]
well, no exactly solved, but as workaround is enought :D

tnx a lot
