### ISSUE TITLE
Strange error of "Loading mixed (insecure) display content"

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo#2611]
In my installation of Avideo (8.4) I use LetsEncrypt certificates and they work very well.
But it turns out that many times some thumbnails are loaded by http instead of https.
The result is that firefox warns me that there is a security flaw, and some user could be scared and go on another website.

Look at the picture

![xdaniel10](https://user-images.githubusercontent.com/5683921/73878191-6c552f80-485a-11ea-9d95-f174e15b8a1c.png)
![xdaniel11](https://user-images.githubusercontent.com/5683921/73878693-4d0ad200-485b-11ea-8338-a28f28074de4.png)
![xdaniel12](https://user-images.githubusercontent.com/5683921/73878697-4e3bff00-485b-11ea-9fad-92ffad3eaa5d.png)

**Comment by maxlinux2000** [comment]
I don't understand if this an error of my configuration or a bug of AVideo

**Comment by TLCReuver** [comment]
We use LetsEncrypt certificates too but don't have such behaviour.
Seem to be an error of your configuration.

We use this tutorial for LetsEncrypt:

https://devanswers.co/lets-encrypt-ssl-apache-ubuntu-18-04/

**Comment by DanielnetoDotCom** [comment]
@maxlinux2000 check your configuration.php for a http reference and replace it to https.

also force redirect from http to https. maybe you cache is being created as http for some reason.
