### ISSUE TITLE
Video views not saving in database

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#2612]
I set up a clean install on a new server. I uploaded a mess of videos  for testing.

But video views are not recording. And I cannot remove the animated gifs although I kept trying.

I shut that server down and set up another clean install on a new server. Same issue. Video views not recording and I cannot get rid of those animated gifs.

Both times it seems that everything else is working though.

I am using Ubuntu 18.04 on a VPS if that matters.

Here is the site: http://144.202.53.219/DIYTubeVideo/

What can the problem be?

**Comment by The-Do-It-Yourself-World** [comment]
Note: even thumbs up work. Just no video views. I dont get it.

**Comment by akhilleusuggo** [comment]
@The-Do-It-Yourself-World Post logs after you visit a video

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Actually he's right . Nothing on logs , but :
![dabiel](https://user-images.githubusercontent.com/52116577/73906872-15c51100-48ad-11ea-95ea-4f6e2f98edc8.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Ok , nvm , I just saw your fixed it already , didn't git pull yet

**Comment by DanielnetoDotCom** [comment]
@The-Do-It-Yourself-World update your site again, this issue was fixed yesterday.
