### ISSUE TITLE
cant open my stream stream video using firefox on youphptube

### ISSUE THREAD

**Issue by JulianMartos** [WWBN/AVideo#2614]
hi, i downloaded the youphptube container from proxmox page. and using OBS i can make live stream but cant open it from firefox or microsoft edge,only from chrome, this is the error i get, how can i fix it?
![youphptubeerror](https://user-images.githubusercontent.com/55887328/73986410-8a2e9d00-490b-11ea-8acd-ceba4517f61a.PNG)

**Comment by DanielnetoDotCom** [comment]
Hi

I do not know proxmox.

but you should check your log file, also share here your nginx.conf and your Live plugin parameters screen shot.

**Comment by PastaPerla** [comment]
nginx.conf
user www-data;
worker_processes 1;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
            worker_connections  1024;
    }

rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://127.0.0.1/plugin/Live/on_publish.php;
                            on_play http://127.0.0.1/plugin/Live/on_play.php;
                            on_record_done http://127.0.0.1/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    listen 444 ssl;
                    ssl_certificate /etc/ssl/certs/cert.pem;
                    ssl_certificate_key /etc/ssl/private/cert.key;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root /var/www/html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"
                    location / {
                            root   /var/www/html;
                            index  index.html index.htm;
                    }
            }
    }

![Capturaasad](https://user-images.githubusercontent.com/55887328/74037468-521b6e80-498c-11ea-96b3-03620724357a.PNG)

**Comment by DanielnetoDotCom** [comment]
does this error only happen with firefox?

does it work with chrome?

I can not see anything in your configurations.

the only thing is that it looks to me you are using an old version.

**Comment by baoang** [comment]
So if I want to stream video or audio, I have to install Nginx instead of Apache2? Will Apache2 make it?

**Comment by akhilleusuggo** [comment]
So , on your config you have as IP address 127.0.0.1 ( local host ) , BUT on your plugin , you have 192.168.25.238 ... 
Is your ngixn server hosted on a different server ? Or the 192.168.25.238 is the ngixn server hosted on the same streaming server and you replaced it with localhost ip ?
And I don't know why your plugin are missing some options . Try changing on your config file the 127.0.0.1 to 192.168.25.238


![image](https://user-images.githubusercontent.com/52116577/74082879-0f7a9480-4a67-11ea-9c99-93b18647c8fd.png)

**Comment by DanielnetoDotCom** [comment]
@baoang to make the site and the livestream to work you need to install both.

Ningx + RTMP module and Apache

**Comment by baoang** [comment]
> 
> 
> @baoang to make the site and the livestream to work you need to install both.
> 
> Nginx + RTMP module and Apache

Oh, now I see. I previously thought one server fits all. Thank you @DanielnetoDotCom
