### ISSUE TITLE
Are the .webp video thumbnails created encoder-side or streamer-side?

### ISSUE THREAD

**Issue by hanyoonLDA** [WWBN/AVideo#2615]
A bit confused here as I see that thumbnails are sent directly from the encoder, but then in the admin panel on the streamer side there's also a function called `useFFMPEGToGenerateThumbs` -- what exactly is this function? I'd like to modify the FFMPEG command to make the video thumbnail three 3-second gifs' stitched into one webp, but I'm scratching my head figuring out where in the platform the video webp thumbnails are being created.

Any help would be appreciated! :)

**Comment by DanielnetoDotCom** [comment]
webp is created on encoder, the useFFMPEGToGenerateThumbs was created by somebody else, I guess it never updates.

I like to keep the streamer more simple, that is why I do not use FFMPEG on it. But the encoder that will requires third party apps to convert videos and images.
