### ISSUE TITLE
Unable to Open Encode Video & Audio facing error 

### ISSUE THREAD

**Issue by wahabzafar** [WWBN/AVideo#2618]
Facing error as below,

This site can’t be reachedencoder2.avideo.com’s server IP address could not be found.

**Comment by akhilleusuggo** [comment]
@wahabzafar If you wanna use the public encoder , the address is https://encoder2.avideo.com/ , not reachedencoder2.avideo.com

**Comment by wahabzafar** [comment]
Thanks for your reply but dear facing same issue on link u provided

**Comment by akhilleusuggo** [comment]
can you provide a screen shot please . I really don't understand what the problem is

**Comment by wahabzafar** [comment]
I just select encode video and audio option and website automatically redirect to this link

**Comment by wahabzafar** [comment]
![Screenshot_20200208-003811](https://user-images.githubusercontent.com/60570245/74060234-5cc91880-4a0b-11ea-8acd-9afa506a7e20.jpg)

**Comment by akhilleusuggo** [comment]
I see that you're on phone 
Did you tried from computer ?
Anyway the error that you have is DNS_PROBE_FINISHED_NXDOMAIN , you're having a DNS problem . Before going too deep , try by changing DNS

**Comment by wahabzafar** [comment]
Dear I have tried it from computer as well same issue arises and can you guide how to change DNS

**Comment by akhilleusuggo** [comment]
https://kinsta.com/knowledgebase/dns_probe_finished_nxdomain/

**Comment by wahabzafar** [comment]
Thank u very much dear I will try now and update u
