### ISSUE TITLE
Playlist player not showing all controls

### ISSUE THREAD

**Issue by adryanm2m** [WWBN/AVideo#2620]
Hi I have added subtitle switcher plugin and works every where but not on the playlist player page

/plugin/PlayLists/player.php?playlists_id=XX

On this page the subtitle and resolution plugins do not appear

**Comment by DanielnetoDotCom** [comment]
Sorry, right now this playlist does not work with all resources.

you may want to try this...

![image](https://user-images.githubusercontent.com/18009293/74239474-aee19680-4cb6-11ea-998b-c46413739e5e.png)

**Comment by adryanm2m** [comment]
Thank you, That worked for me

Great product, many thanks
