### ISSUE TITLE
Copied to new server but some videos wont play

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#2621]
I have copied everything over to a new server but some videos will not play. When I check the page source code, there is no link for a video. I checked the database and the correct filename is in there.

Also the thumbnail shows up just fine on the homepage.

I cant figure out why some fail to produce a link. Any ideas?

New server is www.diytubevideo.com

An example video is: http://www.diytubevideo.com/v/31796

Everything works on the original server but not on the new one but I only have a couple days left before the old server is gone.

**Comment by DanielnetoDotCom** [comment]
I can not take a look on it now, but make sure you have the same plugins with the same configuration on both

**Comment by The-Do-It-Yourself-World** [comment]
Yes, I copied the plugins and the database over to the new server so it has the same settings.

**Comment by akhilleusuggo** [comment]
@The-Do-It-Yourself-World for me , the example that you have sent does work

**Comment by The-Do-It-Yourself-World** [comment]
Oh, now it does. That is very strange. For half the day it would not work at all. Many videos on the site did not work.

I will keep an eye on things and, if there are no issues, I will close this thread.
