### ISSUE TITLE
Videos Uploaded but unable to play on website

### ISSUE THREAD

**Issue by wahabzafar** [WWBN/AVideo#2622]
i have uploaded MP4 videos through encoder almost 12 hours ago and now some videos are still on encoding status and some videos are active but File format is as others so due to file format unable to play any video can anyone help?

**Comment by wahabzafar** [comment]
One more thing to add that I have uploaded video in low quality of 666 mb but after uploading with encoder it's showing many small parts upload like in screenshot.
![Screenshot_20200209-093417](https://user-images.githubusercontent.com/60570245/74096385-334de100-4b20-11ea-9faf-bfec133a22a8.jpg)

**Comment by wahabzafar** [comment]
can anyone help that why my MP4 files are in other format and why my encoding is pending since log?

**Comment by DanielnetoDotCom** [comment]
Are you using the public encoder or your private encoder?

If it is your own encoder, please check your encoder log.

**Comment by wahabzafar** [comment]
i am using public encoder

**Comment by DanielnetoDotCom** [comment]
I have never seen this before.

what browser are you using?
do you have a stable connection or it does disconnect some times?

the biggest problem is because I can not reproduce it.

**Comment by wahabzafar** [comment]
i am using chrome and main problem is that my MP4 videos are not uploading in MP4 format encoder show them as other format.

**Comment by JoshWho** [comment]
Youtube API is limiting pull requests from IP addresses that over use it. It is a Temp Ban for like 30 minutes but it will kill all YT grabs that you have pending when it does this. It is wise to not overuse the Import tool on Youtube. It also works for other video sites, so you do not just have to only import from youtube.

Only Solution for this would be for the Encoder Que to not grab the video until the encoder is ready for it so it has a fresh API grab that won't expire so fast.

**Comment by wahabzafar** [comment]
Ok thanks Josh I understand but same case is with downloaded videos which I am uploading through encoder.

**Comment by JoshWho** [comment]
Not sure what would cause that unless the video was corrupted that you uploaded.

**Comment by wahabzafar** [comment]
Ok thanks for your response dear.have a great day.
