### ISSUE TITLE
public streaming for private site

### ISSUE THREAD

**Issue by ashrafpro** [WWBN/AVideo#2624]
Hi,
How can I make a live streaming public for audience, while the website is private?
I enabled: **userMustBeLoggedIn** (Hide the website to non logged users) from General settings
and want the streaming embed iframe to be public

**Comment by DanielnetoDotCom** [comment]
Hi, I guess to do it the code will need some modifications to be able to do what you want.

Just to make sure,  userMustBeLoggedIn the embed iframe will also request you the credentials?

I don't know if you know how to code and change it. but if you want you can hire us to modify it for you.
