### ISSUE TITLE
Thumbs not showing after server change

### ISSUE THREAD

**Issue by kurabutu** [WWBN/AVideo#2625]
I recently switched to a dedicated server and now the encoded videos doesn't show the *thumbsSmallv2 and *thumbsV2 images. Before everything is working fine. I could confirm that the images files do not exist on the /videos/ folder. I do not use any plugins, this is a straight out of the box fresh installation. 

![image](https://user-images.githubusercontent.com/60864262/74118648-4089cf00-4bf7-11ea-97a5-54457e848b78.png)

**Comment by DanielnetoDotCom** [comment]
if you moved from another server you should also move the image files.

but anyway, the thumbs images are auto-created by the script. maybe you are missing the gb lib for PHP.

check your error log.

**Comment by kurabutu** [comment]
I made a fresh installation with a fresh database. I have a separate encoding server. May I know where I should check the error log? Is it on the encoding server or the main server?

**Comment by kurabutu** [comment]
This is fixed. I installed the PHP GD library and it works fine now. Thank you for your help!
