### ISSUE TITLE
Youtube API 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2627]
![image](https://user-images.githubusercontent.com/52116577/74220896-742d2d80-4cb9-11ea-85fe-6fc22c39c4c7.png)

1-When clicking on Embed all , it got stuck .
2-When trying to bulk a playlist , only the first page appears , when going to next it's empty . Every page does show 50 videos maximum ( i know ), just wanna clarify that the playlists I was trying to embed had more then 200 , but only the first 50 appears , the next page is empty

**Comment by akhilleusuggo** [comment]
Ok , about the processing stuck , the bug is Discord Notify . When enabled , it stay stuck .
About the playlist , can't find any fix

**Comment by DanielnetoDotCom** [comment]
Are you using the bulk embed or the encoder to do it?

**Comment by akhilleusuggo** [comment]
youtube API ...  bulk embed ofc
