### ISSUE TITLE
Audit : Error in writeSql

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2628]
`Error in writeSql : (1366) Incorrect string value: '\xEFn' for column 'statement' at row 1, SQL-CMD:INSERT INTO audit ( `id`,`method`,`class`,`statement`,`ip`,`users_id`,`formats`,`values`,`created` ) VALUES ( NULL ,  'save' ,  'Video' ,  'INSERT INTO videos (title,clean_title, filename, users_id, categories_id, status, description, duration,type,videoDownloadedLink, next_videos_id, created, modified, videoLink, can_download, can_share, only_for_paid, rrating, externalOptions, sites_id, serie_playlists_id, video_password) values`

I'm doing a bulk embed youtube api , and I'm getting this error , and the bulk stops 
Disabling Audit does fix the issue , that means something is wrong with audit .
PS: I'm using mysql 8 , storage engine InnoDB , collation utf8mb4_unicode_ci

**Comment by DanielnetoDotCom** [comment]
I sent an update that should do the trick

**Comment by akhilleusuggo** [comment]
Still error : 

`Error in writeSql : (1366) Incorrect string value: '\xE2\x96n' for column 'statement' at row 1, SQL-CMD:INSERT INT                                                                                                O audit ( `id`,`method`,`class`,`statement`,`ip`,`users_id`,`formats`,`values`,`created` ) VALUES ( NULL ,  'save' ,  'Video' ,  'INSERT INTO                                                                                                 videos (title,clean_title, filename, users_id, categories_id, status, description, duration,type,videoDownloadedLink, next_videos_id, create                                                                                                d, modified, videoLink, can_download, can_share, only_for_paid, rrating, externalOptions, sites_id, serie_playlists_id, video_password) value`

**Comment by DanielnetoDotCom** [comment]
I am still not sure why is not fixed, but I am sending a new try.

**Comment by akhilleusuggo** [comment]
'\xE2\x96n' , same as before . I don't get it 
I was able to bulk 32 out of 50 , then stuck with the error
