### ISSUE TITLE
Changed domain now under half the thumbnails work

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#2630]
I changed my domain name and now over half the thumbnails dont work. Checking the page source I see they are pointed to the old domain.

But oddly some thumbnails work, which leaves me confused.

I checked the "customize advanced" settings and the domain is correct. I checked manually in the database under the configuration settings and it looks right there too. The DNS settings check out fine and the rest of the website works. The videos even play fine.

The website is diytube.video

The entire homepage is missing most of the thumbnails.

**Comment by DanielnetoDotCom** [comment]
Make sure you clear your cache after change the domain

**Comment by The-Do-It-Yourself-World** [comment]
Well, that made it worse. Now I have even fewer thumbnails.

**Comment by The-Do-It-Yourself-World** [comment]
Looking at a video page source I get this: poster="https://www.diytubevideo.com/videos

Everything else is all good. Even the videos play fine. But almost all thumbnails are pointing to the old domain. Most, but not all. Still confusing me.

**Comment by DanielnetoDotCom** [comment]
check this 

![image](https://user-images.githubusercontent.com/18009293/74290992-432d1700-4d12-11ea-80ab-1cfb99a2e0d7.png)

also, check your configuration.php file 

![image](https://user-images.githubusercontent.com/18009293/74291043-6c4da780-4d12-11ea-9f79-7d3f82e983a8.png)

**Comment by The-Do-It-Yourself-World** [comment]
I dont have a CDN yet

And the config file has this: $global['webSiteRootURL'] = 'http://144.202.53.219/DIYTubeVideo/';

The IP is correct. Not sure if I should change it to the domain but it should work with the IP just as well right?

**Comment by DanielnetoDotCom** [comment]
You should change it, your IP is NOT correct

![image](https://user-images.githubusercontent.com/18009293/74291585-15e16880-4d14-11ea-8c9a-a18b5bdebdf7.png)

**Comment by The-Do-It-Yourself-World** [comment]
I changed it. Still no good. Cleared cache in the admin panel and in my browser.

$global['webSiteRootURL'] = 'https://diytube.video/';

**Comment by The-Do-It-Yourself-World** [comment]
Still get this when viewing page source: poster="https://www.diytubevideo.com/videos/_YPTuniqid_5ddfb1dc704e20.05020922.jpg

If you copy the link and put diytube.video instead of diytubevideo.com the image works. But I cant figure out where this is coming from.

So far literally everything else works that I can see.

**Comment by The-Do-It-Yourself-World** [comment]
Newly uploaded videos work perfect, thumbnails and all. The older ones are giving me trouble.

**Comment by JoshWho** [comment]
You do not have your domain fully switched over. You have to change it in your main config file in the /videos/ folder. 

I still see your site trying to load resources from https://www.diytubevideo.com/  
Should say https://diytube.video/

**Comment by The-Do-It-Yourself-World** [comment]
Please see above. I did that, including the root path. It looks just like you say. It is not making sense to me. I spent all last night searching for the issue.

Everything points to the correct site except the thumbnails. It does not make sense.

**Comment by JoshWho** [comment]
Clear your cache folder after you made the changes.

**Comment by JoshWho** [comment]
Copy and paste your config file here.

**Comment by The-Do-It-Yourself-World** [comment]
$global['configurationVersion'] = 2;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { 
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'https://diytube.video/';
}
$global['systemRootPath'] = '/var/www/html/DIYTubeVideo/';

**Comment by JoshWho** [comment]
DId u see if this directory exists? /var/www/html/DIYTubeVideo/

Something is telling me that it doesn't.

**Comment by The-Do-It-Yourself-World** [comment]
I cleared the cache and my browser cache. Also tried on various browsers on various computers. Changing the name of the config file killed the site.

I only changed the domain name and the virtual hosts file. I disabled the old virtual host and then deleted the file itself.

I then created a new virtual host file and activated it on the server.

Again, what is odd is that literally everything else works fine. All the other dynamically called files work perfect. Looking at the page source, only the image files are pointing to the wrong domain.

**Comment by JoshWho** [comment]
DId u reboot APache after you changed the virtual host?

**Comment by JoshWho** [comment]
http://144.202.53.219/DIYTubeVideo/    this does not work

http://144.202.53.219/    this does

**Comment by The-Do-It-Yourself-World** [comment]
Checking virtual host right now. I only had one single install using www.diytubevideo.com and then changed it to diytube.video when I was done setting it up.

**Comment by JoshWho** [comment]
Make sure the SSL virtual is pointing to the site root

You can make the non SSL one just go to the html directory and you can put a dummy page there.

**Comment by The-Do-It-Yourself-World** [comment]
Got it!!! Thank you!!!!!!

I am not sure what went wrong but the virtual host file was empty. Must have failed somehow when I set it up. No idea how. Anyway, its working.

Thank you.

**Comment by JoshWho** [comment]
GOod Deal Brotha.
