### ISSUE TITLE
Make Keep Me Logged in a Permanent Default thing

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2631]
Users are always getting signed out and I have to keep telling them there is a switch to slide to stay logged in but some say it still logs them out.

Any way to just make it stay logged in to the year 3044 or something?

**Comment by DanielnetoDotCom** [comment]
Hi

I do not have this option, but maybe you can add a Jquery in the configurations->head code , to auto check the rememberme on page load
