### ISSUE TITLE
Email Verification Page Template Change

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2632]
Would love to be able to explain to all new signups on the login verification redirect page to Whitelist our domains and do not flag us as spam or your email will get unverified. 

This will help cut down a lot of Complaints from email providers from people not understanding that flagging your domain as email spam hurts your reputation score and thus to fix it you can no longer send them emails until they unflag you.

**Comment by DanielnetoDotCom** [comment]
You should be able now to add a custom HTML text in the plugin customizeAdvanced->verificationLinkText
