### ISSUE TITLE
Problem importing videos from youtube: characters like á è ñ ú are lost

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo#2634]
In order to reproduce, we will choose a short YouTube video, where the title has an accent. for example this one: https://www.youtube.com/watch?v=VWcfbywJqdI

Go to the encoder / Import / paste the URL and press the Share button

After a short time we will have our video on Avideo, but all the characters such as the "I" accented will have disappeared.

To eliminate the possibility that youtube-dl is a problem I have downloaded this video from the console on the same server, and the result is that youtube-dl regards the hits:
```

root@s2:/tmp# youtube-dl https://www.youtube.com/watch?v=VWcfbywJqdI
[youtube] VWcfbywJqdI: Downloading webpage
[youtube] VWcfbywJqdI: Downloading video info webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: La policía quería detener al Padre Luis Toro.-VWcfbywJqdI.f247.webm
[download] 100% of 6.80MiB in 00:01
[download] Destination: La policía quería detener al Padre Luis Toro.-VWcfbywJqdI.f140.m4a
[download] 100% of 3.29MiB in 00:00
[ffmpeg] Merging formats into "La policía quería detener al Padre Luis Toro.-VWcfbywJqdI.mkv"
Deleting original file La policía quería detener al Padre Luis Toro.-VWcfbywJqdI.f247.webm (pass -k to keep)
Deleting original file La policía quería detener al Padre Luis Toro.-VWcfbywJqdI.f140.m4a (pass -k to keep)
root@s2:/tmp# 

```

**Comment by akhilleusuggo** [comment]
mysql collation should be utf8 ( if you're using mysql 5.7 )
I'm using mysql 8 and it's utf8mb4_unicode_ci and no problems . I've seen this problem before and fixed it by adding `$global['mysqli_charset'] = 'utf8';` on `videos/configuration.php` file
https://github.com/WWBN/AVideo/issues/2172

also make sure you have disabled 
![image](https://user-images.githubusercontent.com/52116577/74427848-8ac1b900-4e60-11ea-9336-375dbb776806.png)

**Comment by maxlinux2000** [comment]
Already done in installation phase, but I forget to say that this problem occurs only in the title of video. Have a look to the last photo

![Captura de pantalla de 2020-02-13 12-39-29](https://user-images.githubusercontent.com/5683921/74431232-cc516480-4e5e-11ea-9b9b-5131e75b2e1a.png)

![Captura de pantalla de 2020-02-13 12-40-07](https://user-images.githubusercontent.com/5683921/74431244-d2474580-4e5e-11ea-970e-941ce439cb02.png)

![Captura de pantalla de 2020-02-13 12-43-03](https://user-images.githubusercontent.com/5683921/74431337-d96e5380-4e5e-11ea-9c76-88f352da4b14.png)

**Comment by JoshWho** [comment]
The encoder strips special characters on purpose so the file doesn't break. In order for your server to play files with special characters in its link u have to install that in the apache and PHP directives to use.

**Comment by maxlinux2000** [comment]
">> In order for your server to play files with special characters in its link u have to install that in the apache and PHP directives to use."

Hi, I don't understand exactly what I have to install in apache and php .. are you talking about some module?

">> You can always retitle it after you get it qued."
This is true, but when a user imports their YouTube channel with for example 2000 videos, imagine the madness of correcting all the titles by hand

**Comment by akhilleusuggo** [comment]
@maxlinux2000 No , tienes que cambiar las tablas no la database . Mira , si estas usando phpmyadmin , ve a la database del encoder , ve a encoder_queue , y abre las columnas . 
![image](https://user-images.githubusercontent.com/52116577/74504623-7bdd1400-4efd-11ea-8061-168b0fd53fc1.png)

Tienes que cambiar las columnas . Puedes hacerlo manualmente una a una ( lo que recomiendo ) , o vas a donde pone ''operaciones'' , collation utf8mb4_unico_ci , cambiar todas las collation de las columnas

Sinceramente , no tengo la database en español , asi que no sé si los nombres corresponden correctamente .
![image](https://user-images.githubusercontent.com/52116577/74504768-edb55d80-4efd-11ea-98db-fb8ad82eb7e2.png)

**Comment by maxlinux2000** [comment]
**English below**

Hola, lo he cambiado según tus instrucciones pero por mala suerte sigue igual. el título del vídeo se importa sin carácteres con acientos.

Yo tambíen tengo el db del encoder (y del streamer) en inglés. Antes las tablas estaban con "utf8mb4_general_ci " y le he puesto tabla por tabla a "utf8mb4_unicode_ci "

![Screenshot_2020-02-14_10-08-26](https://user-images.githubusercontent.com/5683921/74517418-5c9cb180-4f12-11ea-8987-fc80cdd9d2ad.png)

después hechas las modificaciones al db, he ido al encoder haciendo login con un usuario en el el streamer, y luego he vuelto a importar el mismo víde de ejemplo.... y nada todo sigue igual :(
(mira a bajo que hay dos fotos más)

**English**
Hello, I have changed it according to your instructions but the bug still remains. The title of the video, is imported without accented characters .

Before the tables were set with "utf8mb4_general_ci" and I have set the tables to "utf8mb4_unicode_ci"

![Screenshot_2020-02-14_10-08-26](https://user-images.githubusercontent.com/5683921/74517481-763df900-4f12-11ea-87b1-0529f4259543.png)

After making the modifications to the db, I went to the encoder by logging in with a user in the streamer, and then I re-imported the same example video ... and nothing remains the same :(

![Screenshot_2020-02-14_10-15-40](https://user-images.githubusercontent.com/5683921/74517790-0bd98880-4f13-11ea-8ce9-a48424310cc3.png)
![Screenshot_2020-02-14_10-16-02](https://user-images.githubusercontent.com/5683921/74517795-0d0ab580-4f13-11ea-8ade-034826b72a78.png)

**Comment by akhilleusuggo** [comment]
@maxlinux2000 Hay que aclarar cosas . El importe de los archivos , es un upload normal o es el bulk encode desde el server ? Si es un importe normal ( upload ) , deberia de funcionar normal .
![image](https://user-images.githubusercontent.com/52116577/74546885-f173cf00-4f53-11ea-9a8e-d5e1d52bc54d.png)

puse de titulo , el mismo titulo del topico que has abierto .

![image](https://user-images.githubusercontent.com/52116577/74547034-22ec9a80-4f54-11ea-990d-8d757188b152.png)

Para acabar , tal vez te queda una cosa por hacer . Ve al archivo de la configuracion /videos/configuration.php ( del encoder y del streamer ) , y añade esta linea .

`$global['mysqli_charset'] = 'utf8mb4_unicode_ci';`

como ejemplo esta screen : 

![image](https://user-images.githubusercontent.com/52116577/74547251-7bbc3300-4f54-11ea-99f2-c25810674074.png)

**Comment by maxlinux2000** [comment]
**English below**

Hola, se trata de una importación normal y corriente desde un video de youtube, este, por podría ser otro mientras que tenga caracteres con acientos en el título.
https://www.youtube.com/watch?v=VWcfbywJqdI

ahora voy a probar lo que me dices.

------

Hello, it is a normal import from a YouTube video, this could be another as long as it has characters with accents in the title.
https://www.youtube.com/watch?v=VWcfbywJqdI

Now I will try what you tell me.

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/74549112-bc697b80-4f57-11ea-8c8a-8444e9178add.png)

**Comment by maxlinux2000** [comment]
ES: Parece que no funciona, aquí mis configuraciones del streamer y Encoder (en la misma maquina)
EN: It seems that it doesn't work, here my streamer and Encoder settings (on the same machine)

```
root@s2:/var/www/html/cathotube.com# cat YouPHPTube-Encoder/videos/configuration.php 
<?php
$global['webSiteRootURL'] = 'https://encoder.s2.cathotube.com/';
$global['systemRootPath'] = '/var/www/html/cathotube.com/YouPHPTube-Encoder/';

$global['disableConfigurations'] = false;
$global['disableBulkEncode'] = false;
$global['disableWebM'] = false;

$mysqlHost = 'localhost';
$mysqlUser = 'Encoder';
$mysqlPass = 'MyPass';
$mysqlDatabase = 'Encoder';
$global['mysqli_charset'] = 'utf8mb4_unicode_ci';

$global['allowed'] = array('mp4', 'avi', 'mov', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv', 'mpg', 'mpeg', 'f4v', 'm4v', 'm4a', 'm2p', 'rm', 'vob', 'mkv', '3gp');
/**
 * Do NOT change from here
 */

```


Y aquí el Streamer / Here the streamer

```

root@s2:/var/www/html/cathotube.com# cat YouPHPTube/videos/configuration.php 
<?php
$global['configurationVersion'] = 2;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { 
    // get the subdirectory, if exists
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), __FILE__);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'https://s2.cathotube.com/';
}
$global['systemRootPath'] = '/var/www/html/cathotube.com/YouPHPTube/';
$global['salt'] = 'dsadasadasdasd';
$global['enableDDOSprotection'] = 1;
$global['ddosMaxConnections'] = 40;
$global['ddosSecondTimeout'] = 5;
$global['strictDDOSprotection'] = 0;

$mysqlHost = 'localhost';
$mysqlPort = '3306';
$mysqlUser = 'Strreamer';
$mysqlPass = 'MyPass';
$mysqlDatabase = 'Streamer';
$global['mysqli_charset'] = 'utf8mb4_unicode_ci';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';

```

**Comment by maxlinux2000** [comment]
te enseño en este vide lo que hago:

https://s2.cathotube.com/video/xavideo-2020-02-14-17-41-24

**Comment by akhilleusuggo** [comment]
@maxlinux2000 Eso mismo hago yo , y funciona sin problemas .
En el streamer el $global tiene que estar con los globals , pero no sé si hara algun cambio . TU lo pusistes justo debajo de la db . Lo mismo en el encoder , tiene que estar debajo de $global['disableWebM'] = false;

Y como llegas el streamer site ? Tienes todas las columnas en collation utf8mb4_unicode_ci ?
las de video en conctreto 

Una vez cambiado el collation de videos ( tal vez no puedas poner utf8mb4 para filename ) , pero el resto si , cambia la posicion de $global a donde corresponde . Debe de funcionar asi .

**Comment by maxlinux2000** [comment]
para akhilleusuggo 
voy a seguir tus instrucciones... pero mañana. ahora tengo que salir. saludos

**English below**

Que  raro!
Tengo 2 instalaciones de Avideo en dos maquinas iguales con el mismo sistema operativo (raspberryp4), las dos actualizadas al día (git, sistema  yyoutube-dl también).
He revisado la confguración y es identica, a parte las urls que son obviamente diferentes.
Pero la primera importa los videos desde youtube sin  
problemas, mientras que la segunda falla en los caracteres con acientos....
seguiré buscando....



Thats weird!
I have 2 installations of Avideo on two equal machines with the same operating system (raspberryp4), both updated daily (git, yyoutube-dl system as well).
I have checked the configuration and it is identical, apart from the urls that are obviously different.
But the first one imports the videos from YouTube without
problems, while the second fails in the characters with hits ....
I'll keep looking....
