### ISSUE TITLE
request Clean Title

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2636]
can you add allow non latin characters in urls ? The database does allow me to add it manually , but the video does fail to load . If the title of the video is a non latin character , the url of the video is kinda empty .

**Comment by DanielnetoDotCom** [comment]
Try this change.

make sure you clear your cache dir

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 
Prepare failed: (1054) Unknown column 'encoderURL' in 'field list'<br>

**Comment by DanielnetoDotCom** [comment]
I was planning to send this update late, but now I guess I will need to release it now.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Wow , this release is cool .
Thank you
