### ISSUE TITLE
disable import video 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2637]
in the config file on the encoder , there are option that could be change from false to true .

```
$global['disableConfigurations'] = false;
$global['disableBulkEncode'] = true;
$global['disableWebM'] = true;
```

can you add something like 
$global['disableImportVideo'] = true; ?

**Comment by DanielnetoDotCom** [comment]
Done :)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Do I have to add it manually now ? because the git pull only changed the 
`install/checkConfiguration.php`

not the `/videos/configuration.php`

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Ok , looks like when `$global['disableBulkEncode'] = true;` is set to true , it is disabled to all users except for admins . Looks good for me. Thanks
