### ISSUE TITLE
Video Link HTTP should be HTTPS and throwing off SSL warnings

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#2638]
I have everything on my server pointing to HTTPS but the video link itself is HTTP and is throwing off security warnings in browsers as not safe.

Everything else is working fine and points to HTTPS. Only the video links are HTTP.

I am using the Amazon AWS_S3 plugin and it has HTTPS in the settings. I have my virtualhost file redirecting to HTTPS and my SSL works fine on the homepage and tests good.

How can I fix this?

**Comment by akhilleusuggo** [comment]
If you're hosting the video , and your have the 
```
RewriteEngine on
RewriteCond %{SERVER_NAME} =yoursite.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
```
the video can not be on a non https

**Comment by The-Do-It-Yourself-World** [comment]
That did not fix it. I still get

source src="http://diytube.s3.wasabisys.com/_YPTuniqid_5df14a289670c1.90805100_Low.mp4

**Comment by akhilleusuggo** [comment]
are you sure you have 

```
RewriteEngine on
RewriteCond %{SERVER_NAME} =yoursite.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
```

on your apache configuration ?

Second fix would be deleting : 
```
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) {
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), FILE);
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
```

from your configuration file on `/videos/configuration.php`
this should fix your problem

**Comment by The-Do-It-Yourself-World** [comment]
I did make the change to my htaccess and it made no difference. I tried a different variation as well but it did not help.

I made the change to my config file but still only the video link is http.

Where is that in the code so I can manually change it?

**Comment by akhilleusuggo** [comment]
@The-Do-It-Yourself-World what htaccess ?
man , put 

```
RewriteEngine on
RewriteCond %{SERVER_NAME} =yoursite.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
```
`/etc/apache2/sites-available/`
now you have to edit your site config file , `nano whatever.conf`

on the code , i told you already 
```
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) {
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), FILE);
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
```
if you remove it , should work 

https://diytube.s3.wasabisys.com/_YPTuniqid_5df14a289670c1.90805100_Low.mp4

**Comment by The-Do-It-Yourself-World** [comment]
Thanks. That did it. I had put the rewrite code in the .htaccess file.
