### ISSUE TITLE
Video won't play

### ISSUE THREAD

**Issue by fontrealm** [WWBN/AVideo#2640]
So, when i upload a video via an encoder (doesn't matter if its our own encoder or the default hosted by YouPHPTube), it will show up on the website, but not in the files. So the video is basically non-existant. max_execution_time is set to 7200 and post/upload_max_size is set to 1024M. The video meets all of those requirements, but it still will not work. Other videos, however, DO work, and that's probably because they are smaller in filesize and less long. Here's the video URL: [https://vidza.co/video/bananas-mario-kart-double-dash](https://vidza.co/video/bananas-mario-kart-double-dash)

Can someone help me with this?

**Comment by DanielnetoDotCom** [comment]
Check your log file.

also if you can update your site to the latest version

**Comment by fontrealm** [comment]
> Check your log file.
> 
> also if you can update your site to the latest version

Where is the log file located?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
