### ISSUE TITLE
Clone or Download archive problem ...

### ISSUE THREAD

**Issue by tgd1973** [WWBN/AVideo#2644]
Hello! For some days I have known that when you try to download the encoder archive ... this does not contain all the files with the changes made up to the day.
https://github.com/WWBN/AVideo-Encoder/archive/master.zip

  Example: the encoder archive in the "update" folder does not contain all files but only up to "updateDb.v2.3.sql". Only online I see that it has arrived at the "updateDb.v3.0.sql" version ... but apart from copying them from raw, how do you get them all updated?
I didn't believe it was enough
"sudo git clone https://github.com/DanielnetoDotCom/AVideo-Encoder.git" ... because it downloads the same version without all the files ...
Thank you.

**Comment by tgd1973** [comment]
I apologize ... I should have opened this tichet in the Encoder area ... but it's the same ...

**Comment by DanielnetoDotCom** [comment]
This is something related to GitHub, NOT related to this specific project.

but even the master.zip or git clone should download all the files
