### ISSUE TITLE
Promote Channel Plugin Mod

### ISSUE THREAD

**Issue by KenRHill** [WWBN/AVideo#2646]
Greetings Daniel,

I would like to request a Promote Channel Plugin modification.  Can we add the Promote Videos button and the Promote Channel button to the sites main menu system in the same button list as My Account, My Channel, My videos, Dashboard, Subscriptions and Comments?  Only have them visible when a user is logged in.  Maybe place them right above the My Channel button?  It would have to work for each user individually who is signed in.  I am assuming this would be done in the navbar.php file somehow, but I am not a coding master, I just dabble and modify as I can.   Maybe you can add it in to the next verion release of AVideo. How much will you charge me to modify it for me?  Thanks.

**Comment by DanielnetoDotCom** [comment]
Hi, sorry for the delay.

for a quotation please email developer@youphptube.com
