### ISSUE TITLE
When do you add Japanese Locale package ?

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#2647]
Avideo add Korean Language Locale Ver8.5.
When do you add Japanese Locale package ?

**Comment by DanielnetoDotCom** [comment]
Hi

if you can provide a translation we can add it in the main branch

**Comment by hnagasawa** [comment]
Dear Daniel

I will do translation.

Please let us know if you have any precautions when translating.

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
when you finish the translation please make a pull request, I will review if the code is fine.

**Comment by hnagasawa** [comment]
I  doone  translation Japanes. I created jpn.php.
I want to check it on Our Avideo.
I put jpn.php under locale.
Which files should be modified next?

**Comment by DanielnetoDotCom** [comment]
I guess the Japanese translation should be a jp.php file.

If you want to send the file to me I will check it and add it in the main core

developer@youphptube.com

**Comment by hnagasawa** [comment]
Dear Daniel

I send you jp.php file.

Please check it

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
hi

I still not received the file. I just check it.

**Comment by hnagasawa** [comment]
Dear Daniel

I resend jp.php.
I attached it this mail.

Reagrds
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
sorry, I still not receive anything. I also check on the spam folder.

can you please try to attach the file here?

**Comment by hnagasawa** [comment]
Dear Daniel

I resend you jp.php again.
I ataached jp.php

If you do not recived jp.php,
Please download next URL till 30-Mar-2020(JST)

https://www.cs3cube.com/s/PW9nyeoM8PsDaGi

(this site is nextcloud.)

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
Thanks, I got it.

**Comment by hnagasawa** [comment]
Dear Daniel

Some of the Japanese translations have been corrected.
You can download it from the following URL.

https://www.cs3cube.com/s/ojjr6oHWpDYrWLZ

Please use this file.

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
thanks, updated.

**Comment by hnagasawa** [comment]
Dear Daniel

I installed Avideo new machine.
I upload mp4 file form http://192.168.1.153/upload.
But this file's format is other. I do not play it.

I tried upload form same file on other Avideo Server(IP 192.168.1.228)
I play it.

Both Avideo version Ver8.6 and Ver3.1
OS ver Ubuntus 18.0.4.
IP 192.168.1.153 machine have jp.php.

What do we check ?

Please inform us.

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
please open another issue, regarding your problem and add the log files and screenshots.

**Comment by hnagasawa** [comment]
Dear Daniel

Some of the Japanese translations have been corrected.
You can download it from the following URL.

https://www.cs3cube.com/s/ojjr6oHWpDYrWLZ

Please use this file.

By the way,
What other files besides jp.php do I need to edit to translate each 
plugin and General Settings items  summary into Japanese?

Regards
Hiroshi Nagasawa

**Comment by hnagasawa** [comment]
Dear Daniel

Some of the Japanese translations have been corrected.
You can download it from the following URL.

https://www.cs3cube.com/s/ojjr6oHWpDYrWLZ

Please use this file.

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
@hnagasawa Thanks
