### ISSUE TITLE
Source map error in console

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2649]
Is this console info anything to be concerned about?

Source map error: Error: request failed with status 404
Resource URL: 

```
https://test.mydomain.com/videos/cache/js/c6608764659b3b429ea16329a20f06cb.js?1582025788
Source Map URL: bootstrap-select.js.map
```

Is it a cache plugin issue?

**Comment by DanielnetoDotCom** [comment]
Nothing to worry about. But I guess, if you are up to date it will not appear anymore
