### ISSUE TITLE
Videos are Still on public encoder

### ISSUE THREAD

**Issue by wahabzafar** [WWBN/AVideo#2651]
why other people videos are still/hanged on public encoder and my videos are pending since 3 days.

**Comment by DanielnetoDotCom** [comment]
@wahabzafar I always do my best to let you guys use the public encoder, but the best option is to install your own.

what exactly encoder is hanging?

**Comment by wahabzafar** [comment]
anyone's video is stuck on encorder on "Downloading 0 percent" now whoever upload through encoder video goes in pending.

**Comment by DanielnetoDotCom** [comment]
some times, we need to refresh the public encoder and some videos are lost.
you may need to try to submit the video again.

**Comment by wahabzafar** [comment]
why MP4 videos converted to other format while uploading through public encoder?

**Comment by DanielnetoDotCom** [comment]
Sorry, I do not understand your question

**Comment by wahabzafar** [comment]
Whenever I upload MP4 videos after encoding and get activated videos automatically converted to other format which are not playing on website.

**Comment by wahabzafar** [comment]
![Uploading IMG_20200225_155025.jpg…]()
