### ISSUE TITLE
Are updates automatic now - multiple errors found recently (edited)

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#2652]
I am not pleased at all right now. I have my site for over two years and I do not like it when the entire site changes on me overnight. I paid a lot of money for development of some of the original apps people now use.

My "Playlists" for example are now called "Programs". We are not a TV channel. I want my "Playlists" back. The word "Program" is  British as well. We dont use that word here. How can I fix this?

Some other things changed and not as easy to use. Editing a video suddenly went wide screen on me, making it harder to read and see what I am doing.

Are updates now automatic? How do I turn it off?

**Comment by The-Do-It-Yourself-World** [comment]
Also the entire website jerks back to the top when I am editing playlists, now called "programs". When I am working with a long list of videos, this is confusing and causes me to have to scroll back to where I was working every single time.

I also noticed this when working in "My Videos". I often work with many videos at a time and now the screen jerks back to the top every single time I edit something. Before it waited patiently for me in place. Now I have to scroll back down to the next video in line once I save a video I was editing.

**Comment by The-Do-It-Yourself-World** [comment]
When editing a video most of the time the paragraph breaks are removed and all my sentences are jumbled together into one now. This happens with videos copied over from YouTube as well. All the paragraph breaks are gone.

**Comment by akhilleusuggo** [comment]
@The-Do-It-Yourself-World Calm down xD
1- The word programs ( playlist ) can be changed 
![image](https://user-images.githubusercontent.com/52116577/74932919-9aef1080-53eb-11ea-9b52-f15da143bbb8.png)

2-Updates are not automatic . If you don't `git pull` nothing gonna update . Maybe the developers that you paid have added crontab to automatic update every day .

3-

> When editing a video most of the time the paragraph breaks are removed and all my sentences are jumbled together into one now. This happens with videos copied over from YouTube as well. All the paragraph breaks are gone.

I think this was fixed time ago , for me it's working perfectly .

**Comment by The-Do-It-Yourself-World** [comment]
I am getting reports of the "charts" under my dashboard now working and giving this error "err_response_headers_too_big". This is coming from multiple people around the World now.

**Comment by akhilleusuggo** [comment]
@The-Do-It-Yourself-World I've already reported that error , and no fix .
I found for myself one fix , by activating AsyncJobs
This will fix the issue , but will use more resources

**Comment by The-Do-It-Yourself-World** [comment]
Thats sad. It worked up to about October, I think. I have to go back and see if I can find an old backup file to replace it with. Thanks for the answer.

I will let you know if it works, if I can find that older file.

**Comment by The-Do-It-Yourself-World** [comment]
I wonder if firefox updates made this horrible change. Even "CustomizeAdvanced" plugin is all messed up looking now.

Everything is center justified but was left justified until last night.


![Screenshot_20200220_133300](https://user-images.githubusercontent.com/45924889/74966746-a9d2c480-53e5-11ea-97a0-bab521dfdc75.jpeg)

**Comment by The-Do-It-Yourself-World** [comment]
On the video edit page, the entire page widened out overnight. It was a small box taking up half the center of the screen and suddenly got wide on firefox browser. Also the text is all run together, removing all paragraph breaks. It makes it impossible to edit now.

Although, in the second screen shot you can see that the video play page shows the paragraph breaks properly although its all center justified suddenly. These problems all happened last night.

![Screenshot_20200220_133710](https://user-images.githubusercontent.com/45924889/74967136-67f64e00-53e6-11ea-8a45-05861b50cebb.jpeg)

![Screenshot_20200220_133832](https://user-images.githubusercontent.com/45924889/74967289-b0157080-53e6-11ea-8090-b6c77721be9d.jpeg)

**Comment by DanielnetoDotCom** [comment]
@The-Do-It-Yourself-World, as I can see in your screenshots, looks like you have some changes on the code or CSS.

if you can check in the demo site you will notice we do not have this layout on the fields.

FYI, the demo site uses the latest version.

**Comment by The-Do-It-Yourself-World** [comment]
But nobody made any changes to our site. I was uploading and editing videos when suddenly this all changed. That is why I thought it was an automatic update because so much changed at once. I dont understand how this can happen unless it was a firefox update?

**Comment by DanielnetoDotCom** [comment]
something is happening in your site, you should then inspect the code to find out if there is a missing HTML tag or a CSS causing this center alignment.

Because I can not reproduce this error, I can not help much

**Comment by The-Do-It-Yourself-World** [comment]
I had been using the instructions and links from here: https://youphptube.readthedocs.io/en/latest/install/installUbuntu18.html

This may be an outdated version and could be the cause of my problems. If you could kindly direct me to the newest version and instructions, I can update my website and see what happens.

Thanks.

**Comment by DanielnetoDotCom** [comment]
the instructions look fine for me. but for myself, I use the instruction on this link https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer
