### ISSUE TITLE
widgets for Avideo

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo#2653]
It would be very interesting if Avideo can provide some widgets to embed in other web pages using the iframe technique.

For example, the widget could offer a list of the latest videos uploaded on Avideo within an iframe on a wodrpress.

Also a widget with a search engine of the available videos, it would be very interesting, and that the result can be reproduced in a box within an iframe or in a separate window.

regards
MaX

**Comment by maxlinux2000** [comment]
I forgot to comment that a widget with the "Live now" would be very useful

**Comment by maxlinux2000** [comment]
For example, the "libretime" ex "airtime" project provides simple widget like this:

<iframe frameborder = "0" width = "280" height = "216" src = "https://cathoradio.com/embed/player?stream=auto&title=Now Playing"> </iframe>

... this is a music stream player for icecast

or this one:
<iframe height = "400px" width = "550px" scrolling = "no" frameborder = "0" src = "https://cathoradio.com/embed/weekly-program"> </iframe>

... which is a calendar of the radio programming of the week.

**Comment by DanielnetoDotCom** [comment]
Hi

I agree widgets would be awesome.
If you want to hire us to develop a specific one, you can send us an email to quote it,
If you want to develop one by your self, but open an issue on GitHub then will be a pleasure help you supporting you on the development

**Comment by palich91** [comment]
I support that it would be very interesting

**Comment by maxlinux2000** [comment]
Daniel, I may develop something, but is there documentation of how youphptube or its APIs work internally?
I think I could use the first page, which has all the necessary, and go removing the pieces that I don't want to have, and then go ahead with css

**Comment by DanielnetoDotCom** [comment]
> Daniel, I may develop something, but is there documentation of how youphptube or its APIs work internally?

https://github.com/WWBN/AVideo/wiki/AVideo-Platform-API

> I think I could use the first page, which has all the necessary, and go removing the pieces that I don't want to have, and then go ahead with css

Here is what we have to help you https://github.com/WWBN/AVideo/wiki/How-to-code-a-AVideo-Platform-plugin
