### ISSUE TITLE
EE:EE:EE Encoder error

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#2654]
Hi Daniel,

I have recently moved my main site to the server where I am running my sub domain fetube. However I am not sure if this is what causing my issue. currently all videos are getting this EE:EE:EE error and I am not sure what the log is saying about it. Can you please tell me how I can fix this.

Best Regards,
Guy Mass

fetube.flatearth.co.il
[avideo.log](https://github.com/WWBN/AVideo/files/4230674/avideo.log)

**Comment by akhilleusuggo** [comment]
Can you upload the encoder log files

**Comment by guymass** [comment]
I figured it out from one of you other issues, it is CLOUDFLARE!!!! that were limiting my uploads. After stopping the service the videos are now loading correctly. So the question is how do I continue using them? I guess it will be a problem. So YouPHPTube vs CloudFlare haha. No choice there.

**Comment by akhilleusuggo** [comment]
@guymass https://github.com/WWBN/AVideo/wiki/About-Video-Upload#cloudflare
