### ISSUE TITLE
Cannot upload a video getting 413 error

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#2655]
I set up a separate video encoder on a fresh server but people cannot upload a video file. It gives a 413 error saying "Your client issued a request that was too large". (Note, using an external link from youtube works fine tho)

I double checked my PHP.ini file and its set for 4000mb post size and max upload size.

I have gone over the install instructions over and over again but I cannot find the issue.

I am sure its simple but what am I missing?

**Comment by akhilleusuggo** [comment]
Post the encoder logs and how much ram your assigned on php.ini ?

**Comment by DanielnetoDotCom** [comment]
@The-Do-It-Yourself-World I have never seen this before.

check your logs, access log and error log.

also, try to google for it.

**Comment by The-Do-It-Yourself-World** [comment]
Here are the last few hours of the encoder log file:

[21-Feb-2020 08:55:38 UTC] Verification Start https://diytube.video/
[21-Feb-2020 08:55:38 UTC] Verification GetFrom Cache https://diytube.video/
[21-Feb-2020 08:55:38 UTC] Verification Response (): {"msg":["Start","https:\/\/diytube.video\/ Site verified"],"verified":true,"status":"a"}
[21-Feb-2020 14:57:51 UTC] https://diytube.video/ == https://diytube.video/
[21-Feb-2020 14:57:51 UTC] login.json: Login::run
[21-Feb-2020 14:57:51 UTC] Login::run (diytube, ***, https://diytube.video/, true)
[21-Feb-2020 14:57:51 UTC] Verification Start https://diytube.video/
[21-Feb-2020 14:57:51 UTC] Verification Creating the Cache https://diytube.video/
[21-Feb-2020 14:57:52 UTC] Verification Response (https://search.avideo.com/verify.php?url=https%3A%2F%2Fdiytube.video%2F): {"msg":["Start","https:\/\/diytube.video\/ Site verified"],"verified":true,"status":"a"}
[21-Feb-2020 15:09:47 UTC] https://diytube.video/ == https://diytube.video/
[21-Feb-2020 15:09:47 UTC] login.json: Login::run
[21-Feb-2020 15:09:47 UTC] Login::run (diytube, ***, https://diytube.video/, true)
[21-Feb-2020 15:09:47 UTC] Verification Start https://diytube.video/
[21-Feb-2020 15:09:47 UTC] Verification Creating the Cache https://diytube.video/
[21-Feb-2020 15:09:48 UTC] Verification Response (https://search.avideo.com/verify.php?url=https%3A%2F%2Fdiytube.video%2F): {"msg":["Start","https:\/\/diytube.video\/ Site verified"],"verified":true,"status":"a"}
[21-Feb-2020 15:32:53 UTC] https://diytube.video/ == https://diytube.video/
[21-Feb-2020 15:32:53 UTC] login.json: Login::run
[21-Feb-2020 15:32:53 UTC] Login::run (diytube, ***, https://diytube.video/, true)
[21-Feb-2020 15:32:53 UTC] Verification Start https://diytube.video/
[21-Feb-2020 15:32:53 UTC] Verification GetFrom Cache https://diytube.video/
[21-Feb-2020 15:32:53 UTC] Verification Response (): {"msg":["Start","https:\/\/diytube.video\/ Site verified"],"verified":true,"status":"a"}

**Comment by The-Do-It-Yourself-World** [comment]
My php.ini settings are all set to 4000M. I triple checked.

I cant figure this out. I can copy from YouTube but I cannot upload a local file. It errors out every single time.

**Comment by The-Do-It-Yourself-World** [comment]
![Screenshot_20200221_103933](https://user-images.githubusercontent.com/45924889/75048486-92074900-5496-11ea-973f-b4c338be225c.jpeg)

**Comment by The-Do-It-Yourself-World** [comment]
I just set up another server using the exact instructions from here: https://youphptube.readthedocs.io/en/latest/install/installUbuntu18.html

And I am getting the same error. The VPS told me its not on their end.

post_max_size = 4000M
upload_max_filesize = 4000M
memory_limit = 4000M

max_execution_time = 7200

**Comment by The-Do-It-Yourself-World** [comment]
Update. I started a brand new server (3x today) and installed just the encoder. It worked perfectly well. Then I set up the SSL certificate and it gave me the same error again. I cannot upload videos anymore.

Before SSL - works fine. After SSL - broken.

I am using Lets encrypt

**Comment by The-Do-It-Yourself-World** [comment]
Now I have installed the software on 5x new servers and keep getting the same issue. I am using Vultr hosting but it was never a problem before the new software updates.

I cant figure this out. We have been down for two weeks now.

**Comment by akhilleusuggo** [comment]
@The-Do-It-Yourself-World 
First : You can't upload a file of 4gb size on a vps with less then 8gb size . Even if you put 
```
post_max_size = 4000M
upload_max_filesize = 4000M
memory_limit = 4000M
max_execution_time = 7200
```
Your server may even crash , read more about it here : https://github.com/WWBN/AVideo/wiki/About-Video-Upload#ram-memory

Second : 
The server provider may vary . Many server provider nowday are cheap , but cheap for a reason : They oversell the hardware . You may see that you have 16gb of ram , but that ram is shared with others , since it's a VPS . Same happens with CPUs . You can also get this type of error where vps are set to auto increment in ram .

The best thing to do is to get a dedicated server , and install everything you need on it . You can even create your own VPS on it later and get some more dedicated IPs to asigne to each one of them .

PS: After you change 
```
post_max_size = 4000M
upload_max_filesize = 4000M
memory_limit = 4000M
max_execution_time = 7200
```
You need to restart apache2 to take effect . Also I would recommend you to increase 7200 to something else .

To make sure everything is not about the size , try uploading small files , 50mb or so .
Make sure you're not using Cloudflare ! More info here : https://github.com/WWBN/AVideo/wiki/About-Video-Upload#cloudflare

**Comment by The-Do-It-Yourself-World** [comment]
The issue is that I cannot even upload a 1.4 mb file. THAT is a real problem. And I was running everything just fine before the last software update.

Vultr allows CPU overages, so that is not the issue either. Especially with a single 1.4 mb file.

I am not using any CDN or anything else at this time until I get this running.

And my hompepage server is separate from the encoder server so that is also not an issue

**Comment by akhilleusuggo** [comment]
@The-Do-It-Yourself-World what SSL are you using ?
And why your error 413 takes you to google ? 
What has google to do here ?

**Comment by The-Do-It-Yourself-World** [comment]
I am using Lets Encrypt. But I have been getting the same error even before I put on SSL. My last 4 attempts, all fresh installs, were without SSL.

I dont know why it takes me to a google error. I did see this morning that it is referring to this link:

https://jquery-file-upload.appspot.com/

The second I hit "start upload"

I have included a full screen shot.

![error](https://user-images.githubusercontent.com/45924889/75095754-6d7aa200-5566-11ea-9c91-6a2a7574603c.jpeg)


I am guessing that the encoder calls up this website for some reason??? Maybe they made some changes and there is where I am getting the error from?

I have no idea what to do now. I am losing two years of work because nobody can upload. I will try yet again today. And again......

**Comment by The-Do-It-Yourself-World** [comment]
I just tried using an older version of the encoder on a clean server but it just sits there and does nothing when I select a file to upload. No errors but it does not upload either.

**Comment by The-Do-It-Yourself-World** [comment]
I installed one more time on a new server. Clean install. Did NOT install SSL. Upload worked fine. Installed Lets Encrypt and it failed on a 12 mb upload.

But often it has been failing even without SSL so I am not sure if that is the issue.

This was my 6th attempt at getting a video encoder to work.

![Screenshot_20200222_130409](https://user-images.githubusercontent.com/45924889/75097024-d7e60f00-5573-11ea-8733-934a568165e5.png)

**Comment by The-Do-It-Yourself-World** [comment]
I just purchased a decently powered server at Ionos and it worked until I set up the virtual host files.

I wonder how that could possible cause an error? Could that be the cause of the issue?

**Comment by akhilleusuggo** [comment]
@The-Do-It-Yourself-World the error 413 , it's a browser error ( what I've been reading in forums ) , in case you're using chrome . On the pic above you're uploading a 12gb file ?

**Comment by The-Do-It-Yourself-World** [comment]
I am using firefox on an ubuntu 18.04 server (my desktop) and it was a 12 mb file I was uploading.

At home I also have firefox on ubuntu 18.04 and same issue. I think I tried it in brave browser last night but I will double check.

**Comment by DanielnetoDotCom** [comment]
@The-Do-It-Yourself-World did you try to disable all plugins so see if it works?

is your configuration.php files, (for Encoder and Streamer), properly configured with the https, I mean do avoid redirections

the most strange thing is this address **https://jquery-file-upload.appspot.com/** where does it come from? what exactly upload form are you using?

The important thing, look into your browser console, I am pretty sure there is a Javascript error on it.

**Comment by The-Do-It-Yourself-World** [comment]
I have everything pointing to https on the streamer site. That works perfect.

I dont understand where that jquery link comes from either. But I am using the instructions right here: https://youphptube.readthedocs.io/en/latest/install/installUbuntu18.html

And just installing the encoder on a clean server with Ubuntu 18.04

I have tried various hosting companies with the same error.

Also I am accessing the encoder directly using the server IP address and logging in as admin. I can then get the same error so it has nothing to do with the streamer site at all.

I copy/pasted the jquery link in my browser and came to this site: https://blueimp.github.io/jQuery-File-Upload/

Which looks exactly like the upload section of the encoder.

It has to be from your code. So now I am wondering if there is a file size limit in the code itself somewhere?

I have tried multiple servers on multiple hosting companies and get the same error every time.

**Comment by The-Do-It-Yourself-World** [comment]
Well, I do not like this at all. The upload form on the encoder site is being processed by a third party website. Not good at all relying on an external site.

Here is the part of the code I found located at Encoder/view/jquery-file-upload/form.php

Line 6: <form id="fileupload" action="https://jquery-file-upload.appspot.com/" method="POST" enctype="multipart/form-data">

And there is the site our data is going to.

**Comment by The-Do-It-Yourself-World** [comment]
On line 32 of the same file there is an optional link of javascript is disabled:

https://blueimp.github.io/jQuery-File-Upload/

Why cant we process the uploads on our own servers????

**Comment by DanielnetoDotCom** [comment]
I guess you miss to provide a important information

![image](https://user-images.githubusercontent.com/18009293/75103955-81f38480-55d0-11ea-9d43-7a81d4241a45.png)

the video is not processed outside your server. I am pretty sure it is happening due to an javascript error

**Comment by The-Do-It-Yourself-World** [comment]
Members around the World have been complaining about the same issue on various operating systems and browsers. Thats how I found out in the first place. For two weeks nobody has been able to upload a local file from their computers.

We are dying here.

The form is sent to that website, which I have shown. I showed you the code and the file name and line number. It is quite clear that the form is processed by a third party website.

My guess is that the limit is on that site.

I have compared the encoder code from a year ago with the code I just downloaded. A year ago the form was clearly processed on the same page. Now its being sent to a remote server, as I have shown.

**Comment by DanielnetoDotCom** [comment]
@The-Do-It-Yourself-World I already answer you twice what is the problem "THE JAVASCRIPT ERROR".

if you want help to fix it you must provide a browser console screenshot, so we can see the js error and try to find a solution. otherwise, I am sorry I will not be able to help you.

**Comment by The-Do-It-Yourself-World** [comment]
So, you are telling me that every single one of my members around the World, have a javascript error in their browsers? Various computers, operating systems and browsers?

I have no idea what you are looking for, but from a web search, here is a screen print with and without warnings.

![screenshot](https://user-images.githubusercontent.com/45924889/75159472-36cb9580-56e6-11ea-905b-858ea46bb54d.png)
![screenshot2](https://user-images.githubusercontent.com/45924889/75159484-3cc17680-56e6-11ea-894a-163f49e6cd60.png)

**Comment by The-Do-It-Yourself-World** [comment]
I get the same errors in chrome, brave and firefox. Same error on my home computer and my office computer.

Here is a screen shot of the video trying to upload.

![Screenshot_20200224_092237](https://user-images.githubusercontent.com/45924889/75160093-7646b180-56e7-11ea-8bab-de1e094a53c1.png)

Notice the bottom left corner the video is uploading

And here, when it is sent to the remote website, which is in the code I copy/pasted above.

![Screenshot_20200224_092320](https://user-images.githubusercontent.com/45924889/75160154-8f4f6280-56e7-11ea-8c04-5e3ad8c66113.png)


Notice the bottom left corner of the screen.

**Comment by The-Do-It-Yourself-World** [comment]
Again, Here is the part of the code I found located at Encoder/view/jquery-file-upload/form.php

Line 6: form id="fileupload" action="https://jquery-file-upload.appspot.com/" method="POST" 

Pulled straight from your source code at github.

There is the link in the code.

**Comment by The-Do-It-Yourself-World** [comment]
As you can see, the file uploads and then is sent to that external website, then I get the error.

This has been confirmed on multiple computers in multiple countries running various browsers and operating systems.

Not one person can upload a file from their computer.

Try it yourself - encoder.diytube.video

**Comment by akhilleusuggo** [comment]
@The-Do-It-Yourself-World I don't think someone can help you , since you're not using the latest version of this script . You're using outdated version , that means , none can follow up with you

**Comment by The-Do-It-Yourself-World** [comment]
What are you talking about? I am pulling right from github. I have tried six times with a brand new install of the latest software from github. This is what I have been talking about all along. Please read what I have been saying above.

I have "looked at" older code but I have not been using it. It wont work with the new version anyway.

**Comment by The-Do-It-Yourself-World** [comment]
The newest version of the software is what BROKE my site.

**Comment by akhilleusuggo** [comment]
@The-Do-It-Yourself-World I was able to reproduce this error only from this source 
https://github.com/WWBN/AVideo/wiki/VirtualBox-AVideo-Platform-Ready

After updating everything , I've got the error that you have . I'll try it later

**Comment by DanielnetoDotCom** [comment]
@The-Do-It-Yourself-World yes I am telling you "that every single one of my members around the World, have a javascript error in their browsers and Various computers, operating systems and browsers"

probably some file that did not load due to a wrong URL or from a non Secure source.

Looks like you are using the Encoder network and if your network is SSL make sure your encoders are also using SSL NOT an IP

I notice from the screenshot of your console so many warnings and errors some of them call my attention.

**1. the server IP. 188.175.15.196**

are you using IP or a domain? if you are using a domain where does this IP come from?

**2. banneradvertising.admediaclick.com**

the encoder does not have ads. what is it doing there? did you change the code?

after that adscript, I can see many Javascript crashes, that is may causing your upload errors

I hope you review it and give us a feedback

**Comment by The-Do-It-Yourself-World** [comment]
Yes, I saw those ad errors and they are very confusing. Am I pulling from the wrong place?

Here is where I am installing from: https://youphptube.readthedocs.io/en/latest/install/installUbuntu18.html

Is that the right link?

Because I am literally starting with a clean Ubuntu 18.04 server and following the instructions on that link. Nothing more. Nothing less. No code modifications. Nothing.

When I use a direct IP, it works and I can upload files. But when I try to set up a domain or SSL, I get the errors.

**Comment by The-Do-It-Yourself-World** [comment]
> @The-Do-It-Yourself-World I was able to reproduce this error only from this source
> https://github.com/WWBN/AVideo/wiki/VirtualBox-AVideo-Platform-Ready
> 
> After updating everything , I've got the error that you have . I'll try it later

Thank you for trying to help find this. Its driving me insane. I cant sleep until I fix this.

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/75341764-2260d780-5863-11ea-9ea0-3c33ce6b9ec9.png)

**Comment by The-Do-It-Yourself-World** [comment]
I am not using an encoder network. I cannot even get one encoder to work. There is no network installed on my new streamer server at all.

1. I am using an IP. As I wrote above, it only works with an IP. When I set up a domain or SSL, it wont work anymore.

2. I removed it. That was from the main homepage admin configuration. The google header ad code which never worked for me anyway. Deleted. The encoder calls some files from the streamer site, so the ad code came from there. Its gone now.

**Comment by akhilleusuggo** [comment]
@The-Do-It-Yourself-World 
I think you're not clear on your explanation :
1- Quote 

> I am using an IP for the encoder site. As I wrote above, it only works with an IP.

Are you using a domain name ( sub domain ) or not ? If you're using an IP how are you running an SSL then ?

> When I set up a domain or SSL, it wont work anymore.
That mean you're doing something wrong on the installation .

What I recommend you to do .
1- Remove everything that you have on your encoder site , if your server provider does provider a fast re-installation of the OS I would recommend it .
2- BEFORE YOU START INSTALLING THE SCRIPT , work on the security stuffs that you want to do on your server
3- Point your IP to your domain name ( or subdomain ) , example . encoder.example.com
4- Install the SSL for that subdomain , you can find many guides to do so with let's encrypt . Giving an example :  https://www.tecmint.com/install-free-lets-encrypt-ssl-certificate-for-apache-on-debian-and-ubuntu/
5- Make sure the SSL is running when your type your domain/subdomain name
6- Follow with the installation script : 
I'm not going to provide you with a link , since the wiki is really outdated . For the encoder ONLY ( ubuntu 18.04 )

1- `sudo apt-get install apache2 php libapache2-mod-php php-mysql php-curl php-gd php-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl`
2- `cd /var/www/html`
3- `sudo git clone https://github.com/WWBN/AVideo-Encoder.git`
4- `sudo apt-get install python`
5- `sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl`
6- `sudo a2enmod rewrite`
7- `sudo apt install php-mbstring php-gettext`
8- `sudo phpenmod mbstring`
9- `sudo systemctl restart apache2`

If you followed this step , everything should be fine.

**Comment by The-Do-It-Yourself-World** [comment]
First of all, thank you very much for the help.

So, I have been using this link:
https://github.com/DanielnetoDotCom/YouPHPTube-Encoder.git

from this page:
https://youphptube.readthedocs.io/en/latest/install/installUbuntu18.html

Now, the only thing different is today I used your updated link: 
https://github.com/WWBN/AVideo-Encoder.git

And it appears that everything is working fine right now with SSL and everything. I will work on it over night before I close this thread and be sure.

**Comment by The-Do-It-Yourself-World** [comment]
The link you gave me works fine. I have tested it and nobody is complaining about any problems. Thank you.

That old one is rotten and has cost me nearly three weeks of work.

Thank you again for the help. Closing this thread.
