### ISSUE TITLE
PayPal error

### ISSUE THREAD

**Issue by moses268** [WWBN/AVideo#2656]
![IMG_20200220_153900](https://user-images.githubusercontent.com/47680534/74972042-11d9d880-53ef-11ea-84cd-f9420b88e118.jpg)

I keep getting this error when trying to use PayPal in the subscription option. I checked all the documents and errors here with no luck of solving

**Comment by DanielnetoDotCom** [comment]
Please check your streamer log file.

**Comment by Powerbock** [comment]
Paypal have many problems at all, ebay and paypal not working anymore. It does not have to be YouPHPTube, it could also be PayPal as service provider.

**Comment by moses268** [comment]
Ok. I am watching YouTube to see how to create the log file

**Comment by DanielnetoDotCom** [comment]
@Powerbock thanks for the info

@moses268 here how to find the log files

**Comment by moses268** [comment]
i did not see an attached file on how to create the log file. thanks

**Comment by DanielnetoDotCom** [comment]
Sorry @moses268 here is the link https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by moses268** [comment]
Thanks

**Comment by DanielnetoDotCom** [comment]
In your log file, we have this message when I try to use PayPal

`PayPal Error: {"error":"invalid_client","error_description":"Client Authentication failed"}`

For me looks like you have the wrong PayPal credentials.

please double-check it and also make sure you are not mixing the sandbox credentials and the live credentials.

**Comment by moses268** [comment]
Ok I tried a different us account for one of my friends and it did not work

**Comment by DanielnetoDotCom** [comment]
Ok, first thing, please use the PayPal sandbox credentials, and share here the PayPal screenshot and your PayPal plugin settings here in case you got an error on sandbox.

https://developer.paypal.com/docs/api/sandbox/

once it is working on the sandbox we will move to the live environment.

**Comment by moses268** [comment]
Same thing happened.


Attached are the pictures

**Comment by moses268** [comment]
![IMG_20200224_081929](https://user-images.githubusercontent.com/47680534/75153250-eef24180-56d8-11ea-8738-31bba1b361e2.jpg)
![IMG_20200224_080836](https://user-images.githubusercontent.com/47680534/75153264-fd405d80-56d8-11ea-8bc1-6e25b5a86d79.jpg)
![IMG_20200224_080657](https://user-images.githubusercontent.com/47680534/75153302-1517e180-56d9-11ea-88bb-bd5526fc6afb.jpg)

**Comment by moses268** [comment]
![IMG_20200224_082107](https://user-images.githubusercontent.com/47680534/75153523-97a0a100-56d9-11ea-8327-e5a0f7965bfc.jpg)

Maybe this is the problem. The code for the subscription plugin never worked

**Comment by DanielnetoDotCom** [comment]
From the images I can see your secret key is different

**Comment by moses268** [comment]
noticed the part " 5D_lBWN" is part of the code

**Comment by moses268** [comment]
it is correct

**Comment by DanielnetoDotCom** [comment]
Ok, I went to your logs again and now I got this message

"details":[{"field":"transactions.amount.currency","location":"body","issue":"Currency should be a valid ISO currency code"}]}

So I notice you are using as a currency "US" and it must be "USD", I  just changed it for you and now looks like it is working

![image](https://user-images.githubusercontent.com/18009293/75241509-338ee300-5794-11ea-9340-621827d9370d.png)

**Comment by moses268** [comment]
Woah 👐👐👐👐 it works. Ok thanks.
