### ISSUE TITLE
AVideo Encoder using internet rather than 127.0.0.1 to upload video to AVideo Streamer

### ISSUE THREAD

**Issue by xicciodj** [WWBN/AVideo#2659]
Hi!
I'm using AVideo Streamer and Encoder on the same server and I found an issue with my configuration:
When I upload a video to the encoder, it encodes it correctly but then it sends the video using Internet rather than localhost. This saturates all the upload bandwidth while transferring.
The domain setup is something like this:
AVideo Streamer Site - avideostreamersite.com
AVideo Encoder Site - encoder.avideostreamersite.com:8080
avideostreamersite.com is proxed behind Cloudflare, and encoder.avideostreamersite.com:8080 is proxed behind Portmap (to circumvent the 100mb cloudflare limit).
Is there a way to "force" AVideo Encoder to use 127.0.0.1 to transfer files?
I kind of fixed the issue by editing the Encoder.php, but it still sends something via internet, and I was searching for a cleaner solution.
This issue is also present when using SendRecordedToEncoder, when the Streamer site sends the recorded stream to the Encoder site.

**Comment by DanielnetoDotCom** [comment]
sorry, we do not have this option yet
