### ISSUE TITLE
YouTube API

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2660]
The YouTube API by default does allow only 10 000 queries per day . That's too low when your site is growing , and when multiple users are embedding .
Is there anyway or will be implemented on the future that each user can add his own YouTube API Key? 

Under section My Account could be added this function , so each user had it's own 10 000 queries per day .

**Comment by DanielnetoDotCom** [comment]
this is not a bad idea, we may add this in the future.
