### ISSUE TITLE
Ban abusive commentors

### ISSUE THREAD

**Issue by tgibson1** [WWBN/AVideo#2661]
Is the chat plugin open source? Table LiveChat, could be adapted to include an ip address column which is recorded whenever a user posts a comment. This information could be used to effectively ban a user from the server by adding a new iptables rule.

Enter the following rule to block an IP address from accessing your server
iptables -A INPUT -s "IP-ADDRESS of the abusive commentor" -j DROP

This process could be automated via a button that is only viewable by admins. The ipaddress column could also be added to the users table and be updated whenever a user is authenticted to allow banning a user from the server at the user level and not be constrained by a negative comment.

**Comment by tgibson1** [comment]
![chatPhp](https://user-images.githubusercontent.com/9651663/75118685-17266580-5631-11ea-889a-995cb8c25c17.png)

What is calling this method? Is it possible to include the request ip address inside the json object being deserialized on line 26? Then we can add it to the liveChatObject, add the new column in the LiveChat db and save it accordingly.

**Comment by DanielnetoDotCom** [comment]
The LiveChat plugin is discontinued, you should migrate to the Chat2 + User_Controll plugins
