### ISSUE TITLE
Live stream doesn’t work

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#2662]
I have looked at the past issues and still can’t get the live stream to work. Changed from https to http and from 444 to 8080. 
![7956C2D4-15E1-4369-973F-4DCC40A03E0E](https://user-images.githubusercontent.com/58601786/75118149-759d1500-562c-11ea-955f-ba93a304e823.jpeg)

**Comment by maxlinux2000** [comment]
post the logs, configuration, etc, so someone can help you

**Comment by barrunning** [comment]
Logs I have no idea about. 
![2B33676F-2826-4A44-94C7-37F77CA46054](https://user-images.githubusercontent.com/58601786/75188533-21179980-5701-11ea-9c48-c40a03a78ce9.jpeg)

**Comment by barrunning** [comment]
Player url http:// website:8080/live/ long number.m3u8
Live url https://website/plugin/Live/?c=torque+athletics 
Server url rtmp ://website/live?p=

**Comment by DanielnetoDotCom** [comment]
First disable/unckeck the adaptive mode. If you want to use it check this first https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream

them if your site is https your player and server URLs must be https as well, usually we use port 444 for it

**Comment by barrunning** [comment]
Ok will do. It was set up with https and 444. It didn’t work that way either. I switched it after reading previous issues.

**Comment by DanielnetoDotCom** [comment]
check your nginx log file

**Comment by barrunning** [comment]
I have no idea how to check that. What would I be looking for when  checking it?

**Comment by maxlinux2000** [comment]
`tail -f /usr/local/nginx/logs/error.log`

**Comment by jjacobs1** [comment]
020/03/07 05:28:30 [error] 14214#0: *22 open() "/HLS/live/5e3649b630894/index.m3u8" failed (2: No such file or directory), client: 72.0.152.19, server: localhost, request: "GET /live/5e3649b630894/index.m3u8 HTTP/1.1", host: "streaming.shmd.org:444", referrer: "https://streaming.shmd.org/plugin/Live/?c=SHMD+Admin&embed=1"

**Comment by DanielnetoDotCom** [comment]
Post a more complete log here

also post your nginx.conf

also uncheck the useAdaptive mode. I am pretty sure you did not configure it.

that is how to configure the adaptive https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream

**Comment by jjacobs1** [comment]
This was my bad. Not sure why it wasn't obvious to me but I did not have the HLS plugin. Once I got that installed everything worked.

**Comment by jjacobs1** [comment]
Has anyone modified one of the ffmpeg streams to 1080? Not sure what value to use for -bufsize and hls_variant_hi BANDWIDTH.

-c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:1080 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 4200k -maxrate 6000k -bufsize 100000k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi;

**Comment by akhilleusuggo** [comment]
@jjacobs1 -bufsize should be the double of the targeted bitrate . In your case `-b:v 4200k` , then 
`-bufsize` should be around `8400k` . 
Putting this value too low , will be rechecking the bitrate so often and you'll stress the encoder and resulting in very poor quality when the encoder could have done a better job .
Same happens if this value is too high , the encoder will not check if your bitrate is the correct one , and you may end up with very high bitrate then indicated .
