### ISSUE TITLE
Bugs vignettes video webp uploader via streamer-video

### ISSUE THREAD

**Issue by JeanDavis91** [WWBN/AVideo#2664]
Hello
![fichier webp](https://user-images.githubusercontent.com/61474191/75303536-4b707080-5841-11ea-81c4-48e4ad42105a.jpg)
![webpp](https://user-images.githubusercontent.com/61474191/75303539-4dd2ca80-5841-11ea-833b-d81fa3f754aa.jpg)

I noticed this bug on my site and on the Avideo-demo site when I post a youtube video via the "Send a video" link and when I then send the .webp file from youtube for this video via the interface of streamer-video there is no more thumbnail for these videos

I also noticed a strange thing when we send the file .webp or .gif there is deletion of _thumbsV2.jpg and in BD data when we change the value in videos column type embed in video the thumbnail .webp works

Maybe a bug?

Thank you

**Comment by akhilleusuggo** [comment]
@JeanDavis91 without the logs hard to determine what is it .
Are you re-encoding a youtube video or are you embedding a youtube video ?

**Comment by JeanDavis91** [comment]
Bonjour

J'integre une url video youtube ensuite je vais chercher la vignette animé de cette video et j'upload celle-ci avec Mouse Over Poster (WebP) ou Mouse Over Poster (Gif) mais rien j'ai une vignette avec un bouton play Jaune et en plus cela efface le fichier _thumbsV2.jpg.

Merci

**Comment by akhilleusuggo** [comment]
@JeanDavis91 Can you provide the logs error ? It could be a mysql error or permissions folder error .
