### ISSUE TITLE
Privat marked videos showing in category overview panel

### ISSUE THREAD

**Issue by scharc** [WWBN/AVideo#2669]
AVideo Version 8.5 / ubuntu 18.04 lxc container with apache2

I enabled the setting "hidePrivateVideos" in YouTube and Gallery FrontPage setting. In all panels except categories panel my private marked videos are NOT shown but in the Category Panel the videos show up. 
In screenshot attached you see demo instance with 4 videos. One is marked hidden. it is not shown in "most viewed" panel but in category "Ausstellungen" and the subcat "GamePlay"
Is it a feature or a bug? I do not want to see hidden videos in the category if I am not in the correct user group...
![screenshot](https://user-images.githubusercontent.com/474799/75543715-c5138480-5a22-11ea-8f72-ed2500f0178f.png)

**Comment by akhilleusuggo** [comment]
@scharc First thing : The video will always show up if you're logged in and you have the rights to see it . Try by logging out.
Second : If you wanna hide completely private videos , so even users with rights to see them can't find them , then select : 

![image](https://user-images.githubusercontent.com/52116577/75562295-00c54300-5a51-11ea-88cc-5fdea2bd49dd.png)

Have a nice day :)

**Comment by scharc** [comment]
@akhilleusuggo Yes. I know about this setting AND I enabled it in the Plugin settings panel BUT in the category panel on the first page it still shows for not-logged-in users as seen in my screenshot.
This is definitely a bug... 
Attached you can find the settings
![plugins](https://user-images.githubusercontent.com/474799/75585863-5b6f9680-5a73-11ea-8c74-19fb1d9c1ad2.png)
HidePrivateVideos enabled
![hidePrivateVideos](https://user-images.githubusercontent.com/474799/75585880-64606800-5a73-11ea-8506-6a71e1074e1b.png)
Categories enabled
![categories](https://user-images.githubusercontent.com/474799/75585888-6cb8a300-5a73-11ea-997a-0b301441161f.png)
Still as not-logged-in-user you can see the private videos

**Comment by DanielnetoDotCom** [comment]
@scharc are you saying even if you check hidePrivateVideos the private videos will still showing in the main page for **non logged** users?
