### ISSUE TITLE
Title Permalinks containing illegal chars

### ISSUE THREAD

**Issue by scharc** [WWBN/AVideo#2670]
I tried to name one of my videos "#insideGameplay | Episode 1 | »The next level«"
I breaks the URL and returns 404. Fixed this in the database with the following modified clear_string addon:

$text = preg_replace("/-$/","",preg_replace('/[^a-z0-9]+/i', "-", strtolower($text)));

will get rid of all the none valid chars in a url. One problem still ist if titel are almost the same it will generate the same permalink. I attached a small md5($filename)-checksum to the end of the permalink

**Comment by DanielnetoDotCom** [comment]
I could not reproduce this error.

can you reproduce it on demo site?
