### ISSUE TITLE
Website with AVideo platform freezes after every 2-3 requests.

### ISSUE THREAD

**Issue by sarabhi92git** [WWBN/AVideo#2671]
I have installed latest version of AVIDEO platform and uploaded few youtube links and when I brouwse website it freezes after 2or 3 requests and after 1-2 minutes of wait site loaded frequently. 

I have checked at server end but server was running fine with 1% load.

I think there is error in platform.

@DanielnetoDotCom Please help me out to resolve the issue

Thanks in advance!

**Comment by DanielnetoDotCom** [comment]
Please check your log files
