### ISSUE TITLE
Thumbnail URLs are insecure

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#2672]
Site is loading mix content and for some reason  some thumbnails are loading with http and not https which renders my site insecure. I tried searching and replacing in the database but only managed to get those in the description of the video. Here is a screenshot. 

![Screen Shot 2020-02-29 at 2 21 42 AM](https://user-images.githubusercontent.com/58882903/75596864-0182c700-5a9b-11ea-854d-19e63ed6c487.png)

**Comment by tgd1973** [comment]
Me too, it makes me the same and I have not found the reason ...

**Comment by palich91** [comment]
it may be easier for you to create a rule in htaccess:
Redirect all pages from http: // to https: //, including from http: // www to https: //
Option 1:
`RewriteEngine On

RewriteCond %{SERVER_PORT} !^443$

RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]
 `
or use the second option (if the first option does not help):
`RewriteEngine On

RewriteCond %{HTTPS} =off 

RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [QSA,L]`

if all the options didn’t help and a cyclic redirect occurs, add:
`RewriteEngine On

RewriteCond %{HTTPS} off

RewriteCond %{HTTP:X-Forwarded-Proto} !https

RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`

or

`RewriteEngine On 

RewriteCond %{ENV:HTTPS} !on 

RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`

**Comment by guymass** [comment]
I tried all options and none worked for me. It seems that there are some images created with a http url instead of https, also in the video descriptions, sometimes it may get wrong urls from YT shared videos, so I ran an SQL replace command to search and replace all those wrong urls, it did find a few and changed them, but the problem consists. I son't know where those urls coming from so I don't know how to change them. I don't think this is an htaccess issue though.

**Comment by akhilleusuggo** [comment]
If you have done the apache2 redirect and you're still having the issue , delete this lines from the configuration.php on the /videos folder 

```
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) {
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), FILE);
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
```

**Comment by tgd1973** [comment]
I discovered some things that makes me think that the information in the database is causing the problem: I made a new installation and everything was ok ... but only by moving to a new directory (with the necessary changes in configuration.php) with the new folder immediately gave these problems (I also cleared the cache of the script and also of the server) ... but going back on the old folder they disappear immediately. I hope that DanielnetoDotCom can solve the problem because surely there is something in the script that does not fully take into account the settings of the configurazion.php

**Comment by guymass** [comment]
if you open my site and view the console you will those errors have something to do with the thumbnail creation. I think because i was dealing with some apache vhost configurations and changes for a short time period the site was creating the video's thumbnail images with the wrong URL, as my complete site URL is hhtps://fetube.flatearth.co.il, I have seen in the cache files that have either http://flatearth.co.il or https://flatearth.co.il, most are OK which I suspect that during my config changes in my hostname and domain name that needed to be done, while the script was still running, it was getting the wrong values at that time, a today which all is back to normal, the thumbnails I think are created properly, but it leaves all those which were created still stuck as thumbnails for those videos which renders the entire site to be "un-secure". This is for sure something internally inside the script in the process where it creates the video thumbnail image and attaching it to the video file.

**Comment by guymass** [comment]
Also after clearing my cache and reloading, those same links are recreated. If you go now to my site you will notice some videos do not have thumbnails but instead your aVideo yellow image.

**Comment by tgd1973** [comment]
I did another experiment ... I did an installation from scratch, and it was OK. I emptied the database and I loaded a database (with the necessary configuration and plugin changes) from a site located in the other folder (and that I have to move it) that in that site's folder is ok ... in the new database and now the new site just installed but with the database of the old site is no longer ok ... having the thumbnails that load only with the http links making me the mix https and http ... I think it is something that has to do with the database .. .

**Comment by guymass** [comment]
It is where all the links reffering to videos which are set in the database but I don't know where?
grep -r on video folders shows many output some to mp4 files whilch I have no way of editing it and I am not sure why they show up either. I am quite sure this is a url->thumbnail somewhere in the db.

**Comment by guymass** [comment]
OK so here is my update. the site is back to operating normal and it seemed that after clearing all those links from the video description I needed to reboot the server and after that everything came up with all the correct URLs. So I cannot say exactly if that was the fix or some other thing i did while cleaning those bad URLs.

**Comment by tgd1973** [comment]
From me, however, it has not resolved ... In what sense have you cleaned the url?

**Comment by guymass** [comment]
OK so here is my update. the site is back to operating normal and it seemed that after clearing all those links from the video description I needed to reboot the server and after that everything came up with all the correct URLs. So I cannot say exactly if that was the fix or some other thing i did while cleaning those bad URLs.

> From me, however, it has not resolved ... In what sense have you cleaned the url?

I ran an SQL replace statement on the descriptions field of the videos table.

**Comment by DanielnetoDotCom** [comment]
Please check your configuration.php file.

check this line

![image](https://user-images.githubusercontent.com/18009293/76145317-324c9880-6067-11ea-8e60-32f6c32368a8.png)

**Comment by guymass** [comment]
OK I tried removing this live of code and setup it as only to point:
 $global['webSiteRootURL'] = 'https://fetube.flatearth.co.il/';
I also dumped the database again and searched to replace any wrong URLs. I uploaded several new videos of which couple did not create the thumbnail correctly and its not showing.
I also purchased and installed your plugin but that doesn't seem to generate a new thumbnail either. I am not sure what is going on but I will keep testing with new videos to see how it goes. Maybe it will sort itself out now after these changes. But I would hate to delete those videos without thumbnail due to the already views count which are important to me. So I am not sure how to fix those. Luckily there aren't that many of them so I will update of any changes.

**Comment by DanielnetoDotCom** [comment]
FYI, I went to your site and looks like the thumbs are all secure

![image](https://user-images.githubusercontent.com/18009293/77226212-56bf6f00-6b55-11ea-8e53-35be9b4344b7.png)

I saw some thumbs without an image. the thumbs are generated on the encoder, so if it is failing you will need to check the encoder log.

also, the thumbs path is stored in the cache. so after some change, you may need to clear the cache.

![image](https://user-images.githubusercontent.com/18009293/77226253-b6b61580-6b55-11ea-85a1-42ac9dc7e7d8.png)
