### ISSUE TITLE
Plugin Not Found: Statistics

### ISSUE THREAD

**Issue by scharc** [WWBN/AVideo#2675]
Found this in my log-files. There should be a php-file...

```
root@avideo:/var/www/html/avideo/plugin/Statistics# tree
.
-- install
    -- install.sql

1 directory, 1 file
```

**Comment by chinobaingo** [comment]
I have the same problem. Happened overnight with no changes and now my dashboard is also broken... any fix?

**Comment by chinobaingo** [comment]
![B735E0A1-C067-43D8-A662-06E1FF7DC8EE](https://user-images.githubusercontent.com/46426659/76147987-bba79f00-6056-11ea-940f-32532a36d231.jpeg)

**Comment by DanielnetoDotCom** [comment]
Statistcs is a future plugin, you can ignore this error.
