### ISSUE TITLE
Can we import full youtube channel instead of one by one videos

### ISSUE THREAD

**Issue by wahabzafar** [WWBN/AVideo#2677]
Can we import full youtube channel instead of one by one videos

**Comment by akhilleusuggo** [comment]
yes

**Comment by wahabzafar** [comment]
Thanks dear can you please guide steps.

**Comment by wahabzafar** [comment]
Dear please anyone share how to import full youtube channel?

**Comment by akhilleusuggo** [comment]
@wahabzafar just put the link of the channel , youtube-dl will do the rest
In case is not working for some reason , you can go to `sudo /var/www/` , `sudo mkdir tmp` , `sudo chmod 777 tmp` , `cd tmp`
/var/www/tmp$ `sudo youtube-dl -f best -ciw -o  "%(title)s-%(id)s.%(ext)s" -v LINK CHANNEL`

**Comment by wahabzafar** [comment]
thanks dear if will contact you if i need further assistance.
