### ISSUE TITLE
Since recent updates apps will not play video. The media playback was aborted...

### ISSUE THREAD

**Issue by bobbyrabbit** [WWBN/AVideo#2678]
I've updated to the latest version 8.5, all of my videos are encoded with the VideoHLS plugin.
Using both the YPT Mobile Android and IOS apps I am receiving the error:
"The media playback was aborted due to a corruption problem or because the media used features your browser did not support".

Everything worked without a problem before I updated.

**Comment by DanielnetoDotCom** [comment]
check your log file and also your browser console for some clue.
