### ISSUE TITLE
Docker!  Avideo working inside a Container?

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo#2679]
Hi everyone,
Is there any document to install Avideo (streamer and encoder together) in a Docker container?
It would be great to be able to use Avideo together with Portainer and Traefik!

I have seen that in hub.docker.com there is something about Youphptube, but they are obsolete and for amd64 processors, and in several the image no longer exists.

So a document that explains how to install Avideo on Docker would be great

**Comment by akhilleusuggo** [comment]
+ I need that too
