### ISSUE TITLE
videos not able to playback after ftp configuration plugin

### ISSUE THREAD

**Issue by karthikindia** [WWBN/AVideo#2680]
I installed the ftp plugin today and configured
i am able to see the files uploaded in the ftp path
and able to see the newly uploaded video in web apps list too
I am unable to playback the videos
getting the below error
"The media could not be loaded, either because the server or network failed or because the format is not supported"

**Comment by DanielnetoDotCom** [comment]
What value do you have on endpoint?

![image](https://user-images.githubusercontent.com/18009293/75990536-cf76c800-5ed3-11ea-8a30-68e7bdea445a.png)

**Comment by karthikindia** [comment]
i have given my ftp hostname http://vdos.cuetube.in
https://pix.cobrasoftwares.org/images/2020/03/05/vdos1.png
[img]https://pix.cobrasoftwares.org/images/2020/03/05/vdos1.png[/img]

**Comment by DanielnetoDotCom** [comment]
please use this in your end point 

**http://vdos.cuetube.in/vdos.cuetube.in/store/**

**Comment by karthikindia** [comment]
ok its working now
thanks
