### ISSUE TITLE
Why i am unable to save changes from admin panel

### ISSUE THREAD

**Issue by wahabzafar** [WWBN/AVideo#2681]
i am unable to save changes like enable or disable anything or to save google analytic code whenever i click on save button it goes in process of saving but do not save even after half hour.

**Comment by akhilleusuggo** [comment]
@wahabzafar without logs , hard to help.
Post here the logs after you pressed save

https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by HighTowerSF** [comment]
i'm having a similar issue. on the front page when I click the dropdown for the video camera there are only two options: Encode Video and Audio; Embed a video link

I want the option for direct upload an MP4. 

In the admin panel > settings> General Settings  I notice that two buttons are clicked on: 
1) doNotShowUploadMP4Button
2) doNotShowImportMP4Button

I click each button to deactivate it, then click Save. When I click save a pop-up window opens and a loading bar animation shows. However, as soon as I go to a different page and come back -- those two buttons are clicked on again -- it didn't save.

**Comment by DanielnetoDotCom** [comment]
Try to save the options from the plugin menu instead of from admin menu.

![image](https://user-images.githubusercontent.com/18009293/76017382-41173c00-5efd-11ea-9ed0-79d73d539204.png)

**Comment by wahabzafar** [comment]
Dear also unable to to save from plugin option.

**Comment by wahabzafar** [comment]
Overlay ads are not saving

**Comment by chinobaingo** [comment]
in case you cant tell @DanielnetoDotCom ALOT of us are having this problem. ive been asking for help for days. cannot edit head codes in cofiguration menu, cannot save changes, and missing save button on plugin menu and upload menus.

this is obviously effecting more and more people.

error logs show "plugin not found: statistics" when refreshing plugin page.

@wahabzafar try checking avideo.log error log while loading plugin page. do you get errors like me?

**Comment by DanielnetoDotCom** [comment]
Please test it on demo site and see if you can save.

I could not reproduce this error. please screen shot or make a video of the error for me

**Comment by mschouhdry** [comment]
overlay ads unable to save after put code in it but if i am putting simple 123 its saving dear 
![Untitled121212333](https://user-images.githubusercontent.com/26069646/76519675-3de2f980-6483-11ea-89ba-ccc85aa7764a.png)
![Untitled121211111](https://user-images.githubusercontent.com/26069646/76519682-420f1700-6483-11ea-85b6-9ac6ced77354.png)

**Comment by mschouhdry** [comment]
keep showing prepossessing after click on save button dear

**Comment by DanielnetoDotCom** [comment]
@mschouhdry in what page did you try it? plugin or admin page?

did you try it on demo site?

check your log files.

**Comment by mschouhdry** [comment]
its working on demo site

**Comment by mschouhdry** [comment]
working on dmeo sire

**Comment by mschouhdry** [comment]
where is log file dear

**Comment by mschouhdry** [comment]
log file location dear

**Comment by mschouhdry** [comment]
log file location dear

**Comment by mschouhdry** [comment]
POST https://moviestubeonline.com/objects/pluginAddDataObject.json.php 404
send @ jquery-3.3.1.min.js:2
ajax @ jquery-3.3.1.min.js:2
(anonymous) @ plugins:1062
dispatch @ jquery-3.3.1.min.js:2
y.handle @ jquery-3.3.1.min.js:2

**Comment by wahabzafar** [comment]
@DanielnetoDotCom please rply.

**Comment by DanielnetoDotCom** [comment]
Here is how to find the log files https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
