### ISSUE TITLE
Feature Request: Live Stream Schedule Countdown Page.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2684]
A way for users to get their next stream ready and can set a time and date for it so it shows a countdown on the streamers live feed page if anyone goes to it before the actual live stream. 

This one could just be a simple timer script that will just display on the Live Video window.

Would be even better if we can also add a custom thumbnail to the timer view.

**Comment by palich91** [comment]
I like this offer

**Comment by maxlinux2000** [comment]
+2 :-)
