### ISSUE TITLE
Feature Request: Auto Youtube Channel Grab latest video

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2686]
A way to just sync your Youbetube account to your channel on the Avideo website. It doesn't have to grab every video but would be nice to just set it up to grab the next latest video you uploaded to your youtube channel.

The reason why i do not want a bulk yt grabber is because some channels are massive and it can tie up the encoders for days. 

I guess it could be a option the admin can turn on or off wouldn't be bad or have a limit of how many vids it can grab at once. 

Another possible solution would be to let us choose a dedicated encoder to use only for the yt bulk uploads.

**Comment by maxlinux2000** [comment]
+1

**Comment by akhilleusuggo** [comment]
+1
