### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by Skyybr12** [WWBN/AVideo#2687]
Como instalar o nginx para fazer lives? não encontrei nenhum conteúdo referente a isso, tentei algumas formas aqui porem não tive exito.

**Comment by Skyybr12** [comment]
achei um conteúdo que fala sobre como instalar o nginx, https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server - segui todos os passo mais acho que fiz algo de errado, porque não consigo iniciar o servidor nginx, aparece a seguinte mensagem de erro quando o comando ``sudo /usr/local/nginx/sbin/nginx`` e usado ``nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] still could not bind()``

**Comment by DanielnetoDotCom** [comment]
isso quer dizer que seu servidor ja está rodando

**Comment by Skyybr12** [comment]
então meu problema pode está relacionado a abertura de portas do linux, você sabe algum comando para abri portas?

**Comment by Skyybr12** [comment]
tentei abri portas com esses comandos porem não consegui
``iptables -A INPUT -p tcp --sport 8080 -j ACCEPT``
``iptables -A INPUT -p tcp --dport 8080 -j ACCEPT``

**Comment by Skyybr12** [comment]
> @Skyybr12 `sudo /usr/local/nginx/sbin/nginx -s stop && sudo /usr/local/nginx/sbin/nginx`

do you know which commands are used to open ports on linux ubuntu?

**Comment by akhilleusuggo** [comment]
@Skyybr12 `sudo ufw allow PORTNum/tcp` , example `sudo ufw allow 443/tcp`

**Comment by Skyybr12** [comment]
when starting nginx this message appears, is this normal? https://imgur.com/a/1eehzeb
I opened all the necessary doors for the youphptube and I still can't start the live
the following error message appears on my obs: https://imgur.com/a/si9WWl2
the following message appears on the website: https://imgur.com/a/nSaHMdD

**Comment by akhilleusuggo** [comment]
@Skyybr12 
1 `nginx: [error] open() "/usr/local/nginx/logs/nginx.pid" failed (2: No such file or directory)`
This only means that your nginx is already stopped . This error will appear only if you run `sudo /usr/local/nginx/sbin/nginx -s stop` , but your nginx is already stopped .

The error may not be coming from nginx it self , but the config file . Your configuration is missing something . Also make sure your plugin is enabled and is configured .

Take a look here , and make sure everything is set correctly . I'm sure your nginx is fine , but you're missing with the config files/plugin .

https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

If you wanna share your config file here ( you can hide your website name if you want ) , the config file is located here : `/usr/local/nginx/conf/nginx.conf`

`sudo cat /usr/local/nginx/conf/nginx.conf`

**Comment by Skyybr12** [comment]
my file is like this
``    worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://35.215.250.137/plugin/Live/on_publish.php;
                            on_play http://35.215.250.137/plugin/Live/on_play.php;
                            on_record_done http://35.215.250.137/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   
            }
    }

rtmp {
    server {
         listen 1935;
         chunk_size 4096;

         application live {
                 live on;
                 record off;                    
                 on_publish http://35.215.250.137/plugin/Live/on_publish.php;
         }
    }
 }``

**Comment by Skyybr12** [comment]
when using this command ``sudo cp ~/build/nginx-rtmp-module/stat.xsl /usr/local/nginx/html`` 
the following error appears: https://imgur.com/a/LCgnyBz

**Comment by akhilleusuggo** [comment]
@Skyybr12 do you have a domain name ? 
```
on_publish http://35.215.250.137/plugin/Live/on_publish.php;
on_play http://35.215.250.137/plugin/Live/on_play.php;
on_record_done http://35.215.250.137/plugin/Live/on_record_done.php;
```

If your website is running on a domain name , need to have the same 
On the plugin you need to do the same .

I don't understand your last part that you have linked 

```
rtmp {
server {
listen 1935;
chunk_size 4096;

     application live {
             live on;
             record off;                    
             on_publish http://35.215.250.137/plugin/Live/on_publish.php;
     }
}
}``
```

If you have this at the end of your config file , remove it then . In my installation I'm not using it , you can install it later .
On the plugin you need to replace the IP/domain with the right now ( of course install tables and enable it )

**Comment by Skyybr12** [comment]
I don't have a domain yet.
in the tutorial it says that I needed to put this part at the end, but as you are saying it is wrong I will remove it right now.
in the area of plugins I have already changed the ip as shown in the tutorial, installed and updated the tables.

Having done all this I made progress, now the error shown in OBS and another
``unable to access the specified channel or transmission key, check your key and transmission. if it is correct, there may be a problem connecting to the server.``

I believe that this may be related to ports, I used that command you gave me earlier, but I think it didn't work, is there any way to test ports on ubuntu?

**Comment by Skyybr12** [comment]
I did some tests and came to the conclusion that it is not the doors, because I can access `` http: //35.215.250.137: 8080 / stats``

**Comment by Skyybr12** [comment]
I got more progress, I can stay live but this error appears in the player: https://imgur.com/a/OvF7o9f

**Comment by akhilleusuggo** [comment]
@Skyybr12The unable to access the specified channel or transmission key, check your key and transmission. if it is correct, there may be a problem connecting to the server. Try reseting your key , if doesn't help , reset the password of your user account , then copy the new rtmp link and key .

To help you more , when you start the live , and you got this ''error'' https://imgur.com/a/OvF7o9f , check `http: //35.215.250.137: 8080 / stats` and link a screen

**Comment by Skyybr12** [comment]
I did everything you told me to do, and the error still persisted, this is a screenshot of the screen ``http://35.215.250.137:8080/stats`` https://imgur.com/a/tMsFshj

**Comment by DanielnetoDotCom** [comment]
@Skyybr12 what OS are you using?

for me looks like your nginx installation is not the one we recommend.

The directory `/usr/local/nginx/html` must exists

**Comment by Skyybr12** [comment]
@DanielnetoDotCom OS and referring to the operating system? if yes it is ubuntu 16.04 LTS
the directory you mentioned does exist on my machine
I am using the recommended configuration yes

**Comment by Skyybr12** [comment]
I managed to solve it, reinstalled everything and it worked, I have no idea why it wasn't working before.
I thank everyone who helped me. <3
