### ISSUE TITLE
Cache not clearing when expired 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2688]
I've noticed that cache is kept on the cache folder even after days / months , when it expired ( in my case 3600s )

```
du -h /var/www/html/AVideo/videos/cache/
12.1G    /var/www/html/AVideo/videos/cache/
```

Also I have noticed that when the cache is created to each user ( logged or not ) even with the option off .

**Comment by DanielnetoDotCom** [comment]
When a cache is expired it is not deleted, it is overwritten.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom But the idea of cache is to load fast the pages . When the visitor returns should get the latest cache saved . Depending on how large the first page , can take up to 10-12s to load ( if categories included and sub-categories ) . The page should be generated once , when expired and the user check the page again , should load the expired one , and on the background created the new cache to save time of loading .
It's something like the asyncjobs on Dashboard . Does take miliseconds to load the dashboard , and on the background does update the stats , when they're ready , the next time when you re-check , it's updated with the new values .
