### ISSUE TITLE
Cannot upload new plugin

### ISSUE THREAD

**Issue by chinobaingo** [WWBN/AVideo#2690]
I can select file but there is no submit or upload button.
![232FBC3F-619D-44A9-9F7A-5282422F029C](https://user-images.githubusercontent.com/46426659/76114366-c3a20900-5f9a-11ea-86f0-f486b839eb1c.png)

**Comment by DanielnetoDotCom** [comment]
Check your browser console.

maybe a javascript error

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform#javascript-errors

**Comment by chinobaingo** [comment]
> Check this https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform#javascript-errors

When I load plugin page it says avideo error.log

Plugin not found: statistics

Same as here:
https://github.com/WWBN/AVideo/issues/2675

**Comment by chinobaingo** [comment]
> Check your browser console.
> 
> maybe a javascript error

A Javascript-error happend. Please tell your admin to clear the folder videos/cache. 
 If this doesn't help, attach these infos to a github-pull-request: 
 Msg:Uncaught TypeError: $(...).fileinput is not a function 

*I cleared my cache but it didnt help

**Comment by maxlinux2000** [comment]
for the moment upload the plugin with console in Avideo/plugins, unzip it and change owner with
chown -R  www-data.www-data NewPluginFolderPath

**Comment by chinobaingo** [comment]
> Workaround: for the moment upload the plugin with console in Avideo/plugins, unzip it and change owner with
> chown -R www-data.www-data NewPluginFolderPath

yea I did that as a last resort. everytime I load the plugin page i get avideo.log error:
"plugin not found: statistics"

and i cannot use half my plugins or save new settings. im basically stuck with no dashboad, and no backend functionality.
same issue as here:
https://github.com/WWBN/AVideo/issues/2675

**Comment by DanielnetoDotCom** [comment]
Statistcs is a future plugin, you can ignore this error.

this has nothing to do with the dashboard.

**Comment by chinobaingo** [comment]
> Statistcs is a future plugin, you can ignore this error.
> 
> this has nothing to do with the dashboard.

ok well problem still stands...

browser console error:

A Javascript-error happend. Please tell your admin to clear the folder videos/cache.
If this doesn't help, attach these infos to a github-pull-request:
Msg:Uncaught TypeError: $(...).fileinput is not a function

**Comment by chinobaingo** [comment]
ive done the clear directory cache already may times, and verified the folder gets emptied.

**Comment by DanielnetoDotCom** [comment]
please screen shot the browser console.

looks like your JS files are not loading.
