### ISSUE TITLE
Admin page broken

### ISSUE THREAD

**Issue by chinobaingo** [WWBN/AVideo#2691]
![8F73DF34-D686-4663-A953-0F3F59967675](https://user-images.githubusercontent.com/46426659/76114601-52af2100-5f9b-11ea-93f7-37a4e7d335b2.jpeg)

All pages work fine except admin page no statistic load and it shows date picker below footer.

On load  plugin page
A video log says:
Plugin not found: statistics

**Comment by chinobaingo** [comment]
When logged in a regular user and refresh dashboard avideo.log shows:
![CE49394B-BC68-4DBF-8CCA-A6DC4B9C87D5](https://user-images.githubusercontent.com/46426659/76117048-eedb2700-5f9f-11ea-89f1-6333dfaabadd.png)

**Comment by akhilleusuggo** [comment]
@chinobaingo can you try again by disabling asyncjobs ?

**Comment by chinobaingo** [comment]
> @chinobaingo can you try again by disabling asyncjobs ?

Already tried this.  Avideo error.log shows:

![C8869051-05E1-467B-A407-395DADE6232E](https://user-images.githubusercontent.com/46426659/76147964-72efe600-6056-11ea-8ae4-7bac4fa576e9.png)

**Comment by DanielnetoDotCom** [comment]
Check your browser console for errors.

**Comment by chinobaingo** [comment]
> Check your browser console for errors.

I ALREADY POSTED THE CONSOLE ERROR ABOVE!

browser console shows error:
charts:1204 Uncaught ReferenceError: Chart is not defined
at charts:1204
(anonymous) @ charts:1204

**Comment by DanielnetoDotCom** [comment]
I can guarantee that is not the only error on it.

share a screenshot.
