### ISSUE TITLE
Google detectou três erros no site Missing field "thumbnailUrl"  Missing field "uploadDate"  Missing field "name"

### ISSUE THREAD

**Issue by glaudeslm** [WWBN/AVideo#2696]
Hello!
Google detected these three errors in the website's video folder.
I await a solution.

Problems related to Videos detected at https://www.keshetube.com/

For the site owner https://www.keshetube.com/:

Search Console found that your site is affected by 3 Video related issues:

Top Mistakes

Errors can prevent your page or resource from appearing in Search results. The following errors were found on your site:

Missing field "thumbnailUrl"

Missing field "uploadDate"

Missing field "name"

We recommend that you correct these issues when possible to allow for the best experience and coverage on Google Search.

Att,
Glaudes Moreira

**Comment by akhilleusuggo** [comment]
Same problem here .
![image](https://user-images.githubusercontent.com/52116577/76232794-e4cf5780-622f-11ea-87b4-9f58c9de4520.png)

**Comment by glaudeslm** [comment]
Please, does anyone know how to fix this problem?
Need a specific plugin?

**Comment by DanielnetoDotCom** [comment]
Plese inspect the HTML and detect in what element it is missing.

**Comment by glaudeslm** [comment]
Okay, but I want to know how to fix this. Can you show me how?

The following errors were found on your site:

Missing field "thumbnailUrl"

Missing field "uploadDate"

Missing field "name"

**Comment by DanielnetoDotCom** [comment]
This must be fixed on the source code. right know I do not know how to do. but as soon as I figure it out you will be able to see it in the github

**Comment by glaudeslm** [comment]
It seems to me that this is an error in the site code, because other users are also having the same problem.

Is there any specific configuration or plug-in to resolve this?

**Comment by DanielnetoDotCom** [comment]
No plugin to resolve it as long as I know.
