### ISSUE TITLE
 PHP Warning:  Error while sending QUERY packet.

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2697]
I've opened time ago an issue with this same error .
The logs direct to the error `/objects/Format.php on line 33`
on the line 33 : `cat -n /objects/Format.php`
`$res = $global['mysqli']->query($sql);`

This error happens only when the encoded files was too large , I though it was a hardware lack ( RAM ).
But actually it's about the time it takes to encode . I've made sure on apache config `execution_time` very high to remove doubts .
I'm not sure if this could be fixed on MySQL my.ini or it's something on the script .
If some files takes too long to encode ( doesn't mater the size ) , the error will pop .
Noticed this very often on webm , since they're too slow . It's like the query time expires 
Digging into forums/posts : 

**What’re the Reasons to Get Such Warning
This error is appearing because of the maximum number of database connection requests have made. No further requests are allowed.**

Anyone has any idea how to fix this ?

**Comment by DanielnetoDotCom** [comment]
Did you try to increase the max connections on MySQL?

https://www.linode.com/community/questions/18791/how-can-i-increase-the-max_connections-in-mysql

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom But this definitely something on the script . I believe it send too many connection to update the status of the encoder queue ( Status )

![image](https://user-images.githubusercontent.com/52116577/76430498-10317e00-63b9-11ea-9e4a-a27e0dc55bd9.png)

For test purposes only I've changed the default one from 151 to 1500 . Let's see

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom same errors : 
```
PHP Warning:  Error while sending QUERY packet. PID=643 in /var/www/html/YouPHPTube-Encoder/objects/Format.php on line 33
PHP Notice:  Undefined property: stdClass::$code in /var/www/html/YouPHPTube-Encoder/objects/Encoder.php on line 558
```
`$res = $global['mysqli']->query($sql);`
&
`$msg = "Trying again: [$try] => Execute code error " . json_encode($resp->msg) . " \n Code: {$resp->code}";`

**Comment by DanielnetoDotCom** [comment]
I can not reproduce this error and I have a lot of servers encoding large files.

are you using MariaDB or MySQL?

FYI, I use MySQL in all my servers.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom MySQL , InnoDB
Large files ? what is large for you ? Is not about the size , is about the length ( duration ) . 2h videos 1080p/60fps on webm or hls will need time to encode .
You encode files on mp4 and transcoding to 720p 30fps with `-preset ultrafast ` obviously with those poor setting you can't reproduce this error .

**Comment by DanielnetoDotCom** [comment]
> @DanielnetoDotCom MySQL , InnoDB
> Large files ? what is large for you ? Is not about the size , is about the length ( duration ) . 2h videos 1080p/60fps on webm or hls will need time to encode .

When I say large files, I mean the final size. the length reflects on that. if its a 2 hours video it will probably be a large file.

> You encode files on mp4 and transcoding to 720p 30fps with -preset ultrafast obviously with those poor setting you can't reproduce this error .

So do you think it is something related to the settings you are using? what settings are that?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I'm using 1080p/60fps . Using -preset veryfast / medium will take longer time to encode ( better quality ) , means will take longer . I don't mind to encode more time if the result will be a great video quality .
The problem here is , when encoding a video may take up 12h to encode on some of my servers , apparently the connection between the encoder and the BD get lost .

> When I say large files, I mean the final size. the length reflects on that. if its a 2 hours video it will probably be a large file.

the result is about 3-4gb ( when encoding with vp9 , webm ) . I have 16gb ram ( on php.ini memory set to 8196 )

**Comment by DanielnetoDotCom** [comment]
Yes, a lost connection may be a reason. but I really can not reproduce this error on my installations.
