### ISSUE TITLE
is there a way to get commisoin on the wallet funding?

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#2698]

**Comment by freedomshare** [comment]
is there a way to get commisoin on the wallet funding?

**Comment by DanielnetoDotCom** [comment]
Not yet, but check this https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform

**Comment by freedomshare** [comment]
Well getting ad compnays to approve such site is very hard... i have ppv and earns nothing still needs work like streaming PPV for sporting events, 
and subscripts needs work still to on how it works
