### ISSUE TITLE
Feature request: Allow video player size to be changed.

### ISSUE THREAD

**Issue by mukulz** [WWBN/AVideo#2699]
Hi,
I recently installed Youphptube with the addon plugin 'chat2'
However, the chat overlay gets on front of the video player, cutting out and blurring the video.
The video player takes the width of whole screen and so they can not co exist. 
It would be great if the video player was allowed to resize to 3/4 of the width of the screen allowing place for other widgets.

**Comment by DanielnetoDotCom** [comment]
can you please provide a screenshot to help me understand?

**Comment by mukulz** [comment]
![Untitled](https://user-images.githubusercontent.com/6472809/76537816-557eaa00-64a4-11ea-830b-a721c4830d6f.png)

Collapsing the left sidebar does not help as the video player just scales its width.

**Comment by DanielnetoDotCom** [comment]
you know you can close the hat on the red button right?

also, you can align it right if you need
