### ISSUE TITLE
Feature request : VideoThumbnails 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2700]
Sometimes the VideoThumbnails does fail to generate the Thumbnails . If you have a small site it's fine to Delete thumbnails , but when you having hundreds or thousands of videos the thing changes , and it's a big wast of resources .

I manage to re-generate the thumbnail by deleting manually the file from /videos directory .
My request is to add a bottom ( for admin ) , to delete video thumbnail for a specific video so next time when it plays can generate it , instead of doing to dirty work looking for the ID on db or in videos directory .

Thank you

**Comment by DanielnetoDotCom** [comment]
Hi, do you mean fail to generate on encoder?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Yes . Resubmit it to encoder , or an option to delete it from admin panel ( so can be generated next time when someone loads the videos )

This is very important for big websites . Removing all the thumbs , could take days/weeks to complete
