### ISSUE TITLE
Persons in private group can't see videos 

### ISSUE THREAD

**Issue by moses268** [WWBN/AVideo#2701]
The users in the group keep getting the error and there is a glitch where it's saying unknown user

**Comment by moses268** [comment]
The persons in the user group cannot see the videos

Site is dadlitube.com

**Comment by DanielnetoDotCom** [comment]
this error looks like for me something else.

looks like the video does not encode correctly

how did you upload?

it shows the video is 50 years old and the duration is 00:00:00

I really need more details about how did you upload

**Comment by moses268** [comment]
It works when I turn the video to free

**Comment by moses268** [comment]
Just regular upload. I did maybe 8 of them the same day some showed the
right numbers and times others did not

**Comment by DanielnetoDotCom** [comment]
it does not make sense, it seems to me that not suppose to work at all.

what exactly video URL is this?

**Comment by moses268** [comment]
All the videos in the playlists does the same thing

**Comment by moses268** [comment]
https://dadlitube.com/video/157/pms-inter-house-talent-show?page=1

**Comment by moses268** [comment]
If I make it public it plays but once it's in a group it don't work

**Comment by DanielnetoDotCom** [comment]
I guess I understand now.

we are talking about a video in a playlist, not a single video.

can you please configure it the way it fails, and email me a user in the same user group, so I can test it in your environment? I will make tests directly unto your site,

**Comment by moses268** [comment]
Ok will do

**Comment by DanielnetoDotCom** [comment]
Please try now and let me know if there is some progress

**Comment by moses268** [comment]
ok will do

**Comment by moses268** [comment]
Same thing I tried different users and different play list same thing
