### ISSUE TITLE
Keep viewer on channel

### ISSUE THREAD

**Issue by moses268** [WWBN/AVideo#2704]
![IMG_20200315_232457](https://user-images.githubusercontent.com/47680534/76721327-b9f07200-670d-11ea-83d6-99af52b238e3.jpg)
![IMG_20200315_232530](https://user-images.githubusercontent.com/47680534/76721339-c1b01680-670d-11ea-8d80-0430006440a7.jpg)

The keep viewer on channel stays on even while it's  unticked.

 I would like my video to play randomly no only what's on the channel

**Comment by DanielnetoDotCom** [comment]
Sorry, this is not clear to me.

if it does not change when you untick , try to clear the page cache.

what do you mean with it: "I would like my video to play randomly no only what's on the channel"?

**Comment by moses268** [comment]
First on the mobile the button to leave the channel is sometimes covered by
the tittle of other videos so it can't be clicked

See attached

But the issue I am having is I want the auto play to work like how it
worked in the past, I would like videos in auto play to come from all
different channels not to stay on one channel.

Turning off the option to keep viewer on channel is not working

**Comment by DanielnetoDotCom** [comment]
that modification is not possible to do right now.

for me makes more sense to the next video be a video from the same channel.

also, you can force the next video.

![image](https://user-images.githubusercontent.com/18009293/77201553-71e59c80-6acb-11ea-8c32-2a0752ce6076.png)

**Comment by moses268** [comment]
Ok
