### ISSUE TITLE
html file error

### ISSUE THREAD

**Issue by moses268** [WWBN/AVideo#2708]
i added a file in the html option in the customize site plugin now i cant access the pages

how can i access the menu thru putty to delete the code

**Comment by moses268** [comment]
![IMG_20200317_141511](https://user-images.githubusercontent.com/47680534/76888275-a51cf700-6851-11ea-93c5-a9282db12aa4.jpg)

**Comment by akhilleusuggo** [comment]
@moses268 you need to install phpmyadmin and delete it from DB ( if the code you have inserted was on plugin section )

**Comment by moses268** [comment]
ok will try that

**Comment by DanielnetoDotCom** [comment]
hi, what do you mean with that: "i added a file in the html option in the customize site"?

I do not understand.

**Comment by moses268** [comment]
What the person recommended worked

**Comment by DanielnetoDotCom** [comment]
Sorry who?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom basically what he did is : `Log as admin > Plugins > CustomizeAdvanced (CustomizeAdvanced) > menuBarHTMLCode `

He broke something , and needed to remove that from the plugin ( but he can't access anymore to the page ) , phpmyadmin , and browse to plugins and remove manually .
