### ISSUE TITLE
LoginLDAP

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2709]
Can anyone tell me what is the usefulness of LDAP ?
Any article or quick explanation ?

**Comment by DanielnetoDotCom** [comment]
LDAP is more for companies that need to add rules to your employees credentials.

it is like a centralized login for multiple systems. so if an employe quit from the job, you just remove his LDAP rights and he will be out of all company systems.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom So what is the usefulness for this project ?

**Comment by DanielnetoDotCom** [comment]
maybe it is not useful for you, but for companies, it is very interesting
