### ISSUE TITLE
Last commit HLS , Quality Selector bugged

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2710]
![image](https://user-images.githubusercontent.com/52116577/76890725-8ee25b80-6890-11ea-9b69-5496f34efcd4.png)

**Comment by DanielnetoDotCom** [comment]
thanks for the notice.

On my side, it shows fine. can you clear your cache and try again?

FYI, today I will release another update for the HLS plugin, regarding IPhone/Safari

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I've cleared the cache , no changes . Same bugg

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Aparently on your site you don't use the automatic detect . 
https://github.com/WWBN/AVideo/wiki/VideoHLS-Plugin#automatic-encoding-process-hls-only

**Comment by DanielnetoDotCom** [comment]
I have it locally and does not have this problem

**Comment by akhilleusuggo** [comment]
So how I do debug this ?

**Comment by akhilleusuggo** [comment]
Fixed by cleaning the cache of the browser ( not the server's one )
