### ISSUE TITLE
after update my template is messed

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#2712]
hello after update my template is messed up

https://freedomshare.net

as you can see every thing is out of place 

also tell me how to check logs??????
and what i can do to if this

**Comment by DanielnetoDotCom** [comment]
not sure what you mean but try to clear the site cache and browser cache and try again.

**Comment by freedomshare** [comment]
i did all that  nothing working if you go on home page go down to gaming area you will see what i mean 
also  some videos have this
"});return false;' > Description

Description is list on some of the videos maybe part of the problem?

**Comment by DanielnetoDotCom** [comment]
Check the description of this video https://freedomshare.net/v/1262. something there is breaking your site.

once you find what is messing up please let us know.

**Comment by freedomshare** [comment]
i have no idea im just gonna delete those videos and hope for the best

**Comment by DanielnetoDotCom** [comment]
You should only edit the description. some character there is breaking the layout.

**Comment by freedomshare** [comment]
Directory /var/www/html/YouPHPTube/objects/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777
when i try to update oneof them

**Comment by akhilleusuggo** [comment]
`sudo chmod 777 /var/www/html/YouPHPTube/objects/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer`

**Comment by freedomshare** [comment]
i edit it and still nothing i think delete gonna be teh way maybe bad upload i dont knwo but othere thens on home tempate are broken like catagorys names

**Comment by DanielnetoDotCom** [comment]
after edit clear your cache.

**Comment by freedomshare** [comment]
i did there seems to be any video oevr 1month ago thats doing it iam just gonna start deleting them cant be bother to delete all txt and in one that dose it

**Comment by freedomshare** [comment]
looks like all youtube videos

**Comment by freedomshare** [comment]
is there a way to delete all youtube videos easy?

**Comment by DanielnetoDotCom** [comment]
only if you do it directly into the database` where type = 'embed'`

**Comment by freedomshare** [comment]
ok thanks
