### ISSUE TITLE
VideoThumbnails and HLS 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2714]
I think after the video HLS update the videothumbnails plugin is not working anymore , since can't download the videos ( ''protected'')
I've tried it by command lines , and I'm getting errors : 

```
Error when loading first segment 'https://fsdfsd.com/videos/_YPTuniqid_ldjshjfhsdkfh/res240/index0.ts'
https://fsdfsdfs.com/videos/_YPTuniqid_fsfsdfsdfsdfs/index.m3u8: Invalid data found when processing input
```

I've just replaced the IDs and links by random letters

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Any fix to this ?
I've deleted some working thumbs to confirm this , and yes , since ffmpeg can't download them , means can not generate the thumbs

**Comment by DanielnetoDotCom** [comment]
I notice that, I am working on a fix.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Thank you Daniel . But I would suggest to create the thumbs when encoding the video . Makes really nonsense to encode it in this way . 
Huge waste of resources , IO and bandwidth .

**Comment by DanielnetoDotCom** [comment]
Hi

I just sent another update to the HLS plugin. now you have a field to whitelist your encoder plugin, so the encoder can access your encryption key file and extract the images from it.

![image](https://user-images.githubusercontent.com/18009293/77160165-9454c700-6a85-11ea-8959-fd47fe05797f.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom So , if I have 4 encoders from the same IP ( DNS ''A record'' pointing to the same IP , no need to add domain names , only the IP ) right ?

**Comment by akhilleusuggo** [comment]
Apparently works no dns changes needed . Thank you for the fix .

**Comment by DanielnetoDotCom** [comment]
Add only the IP, but you really only need to add the encoder that is in your configuration

![image](https://user-images.githubusercontent.com/18009293/77167256-6dea5800-6a94-11ea-8b83-41a742325b2d.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom since I'm using network encoder , that url changes depending on the delay ( ms ) and the queues encoder

**Comment by DanielnetoDotCom** [comment]
But you can also white list all the encoders IP
