### ISSUE TITLE
Livesearch (Livesearch) , possible bug

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2715]
When a video is private / unlisted or even on a user ground , should not be shown on the livesearch .
I have several private videos and videos on user group that I don't want other to see ( not even the title/thumbs ) but on the livesearch does show them . 

I had to disabled it after 3 users report , since it breaks privacy and also breaks the ''private'' options completely .

**Comment by DanielnetoDotCom** [comment]
Hi

I just sent an update for this plugin that fixes this issue.

please download it again.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom thank you
