### ISSUE TITLE
 Your server is LiteSpeed, you must install Apache

### ISSUE THREAD

**Issue by pcservicespanama** [WWBN/AVideo#2716]
Your server is LiteSpeed, you must install Apache ayuda por favor

**Comment by akhilleusuggo** [comment]
Has seguido las instrucciones de la instalacion ?

**Comment by pcservicespanama** [comment]
Buenas tardes si tal cual pero mi hosting no tiene Apache podrían ayudarme
Puedes ver el error en www.Sr-cosmo.com

Yohendri valles

**Comment by akhilleusuggo** [comment]
Tienes que intalarlo en apache , nunca he usado el LiteSpeed .
Pero por probar podrias ignorar el error y proceder . Si no te funciona quiere decir que el script es incompatible con el LiteSpeed

**Comment by pcservicespanama** [comment]
Ya intente y nada
