### ISSUE TITLE
Invalid HLS key at URL

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2717]
When watching videos longer then 10mn , users are getting this error : `VIDEOJS: WARN: Problem encountered with the current HLS playlist. Invalid HLS key at URL`  (on dev tool )
Maybe you have set up the token key to 10mn ? The token key should be equal to the duration of the video .

**Comment by DanielnetoDotCom** [comment]
please update your HLS plugin again, this issue is already fixed

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom ok thanks for the quick response ,but ... How can I know that you update the plugins ? Can you add some notification options or something ?
there's noway for users to guess when you update or when you don't .

**Comment by DanielnetoDotCom** [comment]
Sorry, about that, right now there is no way to know if there is an update.

soon I will add an easier way to know if there is an update to run.

**Comment by guymass** [comment]
I have this issue with the HLS
VIDEOJS: WARN: Problem encountered with the current HLS playlist. Trying again since it is the only playlist.

**Comment by DanielnetoDotCom** [comment]
Please open a specific issue for that and provide your logs and Javascript console screenshot.
