### ISSUE TITLE
Missing route for latest version of encoder?

### ISSUE THREAD

**Issue by foobarzap** [WWBN/AVideo#2719]
I just tried to setup the most recent version of AVideo and AVideo-Encoder and had problems uploading new videos through the encoder. Images (thumbnails) were uploaded successfully, videos were missing and therefore no playback was possible.

It turned out that adding

```
SimpleRouter::put($basePath . "aVideoEncoderChunk.json", function() {
    require_once "objects/aVideoEncoderChunk.json.php";
    exit;
});
```

fixed the problem. 

Taking a glimpse at the source of the encoder, this seems to make sense as an associated put request is generated in `sendFileChunk` (see  `objects/Encoder.php`).

Now the question is, whether there are more things to do or when there will be a suitable version of AVideo available to integrate with the most recent version of the encoder. Or should I better use  older versions for now and if so, which one would you recommend?

Any hints / help is appreciated.

**Comment by foobarzap** [comment]
Are there even more routes missing? Comparing `new.htaccess`, `classic.htaccess` and `routes.php` I would guess "yes"  - links to `/video` are no longer rewritten ...

**Comment by foobarzap** [comment]
Sorry .. didn't meant to close this ...

**Comment by inc002** [comment]
Hello, 
With fresh install I can't play videos like you, just put the put into routes.php solved the problem ?

**Comment by inc002** [comment]
OK the video size in video folder after encoding is 0Kb...

**Comment by foobarzap** [comment]
> OK the video size in video folder after encoding is 0Kb...

I installed AVideo and the Encoder in a subdirectory of `/var/www/html` on my system. For some reason I also had to establish a symlink from `videos` to `AVideo/videos` to get it working.

**Comment by foobarzap** [comment]
As an alternative to adding the `put`-route, I had success in installing version 8.1 of AVideo and version 3.0 of the encoder like so:

```
git clone https://github.com/WWBN/AVideo.git --branch 8.1
ln -s AVideo/videos videos
git clone https://github.com/WWBN/AVideo-Encoder.git --branch 3.0
```

With this I was able to upload and watch videos, however, several links are still broken :-(

**Comment by foobarzap** [comment]
Now, I was even able to get rid of the symbolic link - it seems that we need separate `<Directory>`-entries in apache2.conf; mine now look like this:

```
<Directory /var/www/html/AVideo>
	Options Indexes FollowSymLinks
	XSendFile on
        XSendFilePath /var/www/html/AVideo/
	AllowOverride All
	Require all granted
</Directory>

<Directory /var/www/html/AVideo-Encoder>
	Options Indexes FollowSymLinks
	XSendFile on
       XSendFilePath /var/www/html/AVideo-Encoder/
	AllowOverride All
	Require all granted
</Directory>
```

However, there are still broken links ....

**Comment by inc002** [comment]
> > OK the video size in video folder after encoding is 0Kb...
> 
> I installed AVideo and the Encoder in a subdirectory of `/var/www/html` on my system. For some reason I also had to establish a symlink from `videos` to `AVideo/videos` to get it working.

**Comment by foobarzap** [comment]
No, structure within `/var/www` is

```
.
`-- html
    |-- AVideo
    |-- AVideo-Encoder
    |-- index.html
    `-- videos -> AVideo/videos/
```

And sorry, I was wrong, I still need the symbolic link as shown above, otherwise I receive

```
[19-Mar-2020 14:20:35 UTC] PHP Fatal error:  require_once(): Failed opening required '../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/html/AVideo/view/modeYoutubeBottom.php on line 2
```

Btw. I am running ubuntu 18.04; apache and mysql on the same machine. Currently I simply want a running environment to play with; later I might want to separate services to different machines.

**Comment by inc002** [comment]
OK, I don't use this plugin. For my problem I have installed encoder in branch 3 with the last streamer and it's work fine

**Comment by foobarzap** [comment]
Wow, this makes me curious. How did you install it? I basically followed the instructions of the [wiki](https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer).

**Comment by foobarzap** [comment]
**Oh gosh** - got it! The big mistake was to copy `.htaccess` from one of the templates! I remember that I got this recommendation from somewhere when I was still struggling with newest version of the encoder.

Now everything works fine!
