### ISSUE TITLE
How to change the encoding in MySQL

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#2720]
I suggest that developers take into account and install phpMyAdmin so that you can change the encoding and make changes to the tables

**Comment by DanielnetoDotCom** [comment]
It is up to the server owner, I do not like PHPMyAdmin for my self. I think it is a security branch. but like I said before it is up to you.

**Comment by akhilleusuggo** [comment]
You can always google how to change the encoding with command lines
