### ISSUE TITLE
custom video playback speed

### ISSUE THREAD

**Issue by rgguoc** [WWBN/AVideo#2721]
several users have been asking for this feature, this will allow them to playback videos at speeds other than the standard 0,5x 1x 1,5x or 2x. 
Our scenario: The site administrator could allow users to play videos at 1,2x if requested and this speed would be available for the whole site or single channels.

**Comment by akhilleusuggo** [comment]
this already exists 
You can customize them as you want . You can change it on plugin section x2 , x5 , x10 , x8 , what ever speed you want
![image](https://user-images.githubusercontent.com/52116577/77089993-3ab1b580-6a0f-11ea-8edd-9c3ecae86d50.png)
![image](https://user-images.githubusercontent.com/52116577/77090040-49986800-6a0f-11ea-8017-a0980c071fd6.png)

**Comment by bklier-mpl** [comment]
> this already exists
> You can customize them as you want . You can change it on plugin section x2 , x5 , x10 , x8 , what ever speed you want

What's the plugin containing these settings?

**Comment by DanielnetoDotCom** [comment]
PlayerSkins

**Comment by bklier-mpl** [comment]
Thank you for your quick reply, I think you can close that issue now.
