### ISSUE TITLE
BigVideo: YouPHPFlix theme

### ISSUE THREAD

**Issue by debjit-biswas** [WWBN/AVideo#2722]
How do I get the BigVideo start automatically? Like here:  https://flix.avideo.com/

**Comment by DanielnetoDotCom** [comment]
That is the trailer we set for every video.

![image](https://user-images.githubusercontent.com/18009293/77128662-ac016080-6a2f-11ea-9e8c-1b6656d6a7a7.png)

**Comment by debjit-biswas** [comment]
If I copy embed code from any other video and paste it here, It simply does not save after saving.

**Comment by DanielnetoDotCom** [comment]
Can you please give us a sample?

can you please test it on the demo site to see if the error is on your side or in the script?

check your log file.

**Comment by debjit-biswas** [comment]
It does not work as per my procedure on the demo site either. However, the demo site has an additional Trailer switch. Which I don't have.
![01](https://user-images.githubusercontent.com/50593814/77131124-82245a00-6a80-11ea-8138-a6725d2eb6b2.PNG)
![02](https://user-images.githubusercontent.com/50593814/77131136-881a3b00-6a80-11ea-9c2d-d6761ecbe80b.PNG)
![03](https://user-images.githubusercontent.com/50593814/77131143-8e101c00-6a80-11ea-9822-0b85a59b16d2.PNG)

**Comment by debjit-biswas** [comment]
Here are the log files:

[avideo.log](https://github.com/WWBN/AVideo/files/4357863/avideo.log)
[avideo.js.log](https://github.com/WWBN/AVideo/files/4357864/avideo.js.log)

**Comment by DanielnetoDotCom** [comment]
Hi

you are placing a full embed code.

you should place only the embed URL

For example, you paste this:

<iframe width="640" height="480" style="max-width: 100%;max-height: 100%;" src="https://demo.avideo.com/vEmbed/251" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay"></iframe>


you should paste only this: https://demo.avideo.com/vEmbed/251

**Comment by debjit-biswas** [comment]
Thank you, Daniel! That was really helpful.
