### ISSUE TITLE
Error paying user for watching video

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#2723]
If you change the value from 0.1 to 1, an error message appears. Unable to determine payment amount
Screenshot https://vfl.ru/fotos/c35b4f5129930038.html

**Comment by palich91** [comment]
Say at least how to return the value back

**Comment by DanielnetoDotCom** [comment]
Hi

First, the best place to deal with plugins configurations is on the plugins menu. there are some hidden options that may be interesting for you.

![image](https://user-images.githubusercontent.com/18009293/77225317-c2510e80-6b4c-11ea-9786-6b9cdb30ef2e.png)

In case you misconfigure a plugin you can reset it deleting all the JSON code and save it.

![image](https://user-images.githubusercontent.com/18009293/77225335-df85dd00-6b4c-11ea-82b2-3ec65314d973.png)

If you want to use 1 as the default value, use 1.0
