### ISSUE TITLE
Request: Embed videos on other Youtube-based sites

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#2724]
Request: Use the same opportunity as on YouTube if you embed a video from your site to another site.
Here's how it works when adding videos to other sites (screenshot):
http://vfl.ru/fotos/a635d0d529930062.html
http://vfl.ru/fotos/06e92fac29930063.html

**Comment by DanielnetoDotCom** [comment]
The automatic conversion on the URL into an Iframe is NOT a youtube feature it is the site feature, so I can do nothing about it. It must be implemented in your site side. NOT on AVideo side.

BTW, you can use our embed code.

![image](https://user-images.githubusercontent.com/18009293/77225843-de0ae380-6b51-11ea-8d96-4b97d0a355bb.png)

**Comment by palich91** [comment]
I paste to other Iframe sites it doesn’t work.
Check it out on your site https://tutorials.avideo.com
Copy iframe and try posting somewhere

**Comment by DanielnetoDotCom** [comment]
It does work

But what did you see?

Screenshot, also share the iFrame code here

**Comment by palich91** [comment]
I use the code from your site http://demo.avideo.com/
`<iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="https://demo.avideo.com/videoEmbed/242/avideo1080hd?channelName=TheAdminChannel" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no">iFrame is not supported!</iframe>`   
When you add code to your site, it does not display video

**Comment by DanielnetoDotCom** [comment]
Why will you add this code in my site? 

Where are you adding it?

Please screenshot

**Comment by akhilleusuggo** [comment]
Daniel basically what he means is , when you link a youtube video on ( for example ) discord , the video will show like this : 

![image](https://user-images.githubusercontent.com/52116577/78031894-d70f7c80-736c-11ea-9bdc-0328a67f4e30.png)

When linking something from Avideo , will look like this : 
![image](https://user-images.githubusercontent.com/52116577/78032205-54d38800-736d-11ea-9cdd-04d86b56230a.png)

**Comment by DanielnetoDotCom** [comment]
But what does it has to do with embed code?

it is a feature that discord/facebook and other apps create to handle YouTube videos.

I have nothing to do about it.

**Comment by palich91** [comment]
Try to do this

**Comment by DanielnetoDotCom** [comment]
@palich91 I already answer it

**Comment by palich91** [comment]
Maybe there is some kind of opportunity to implement this, many would find this feature useful. Do it as a plugin and sell. I am ready to pay you

**Comment by akhilleusuggo** [comment]
Is not something to be implemented on the script ... 
The external websites should implement it , not you .

**Comment by palich91** [comment]
I found a solution for embedding videos on other sites, @DanielnetoDotCom, I ask you to add this to AVideo.
Solution (example):
`<object width="640" height="360"><param name="movie" value="https://vicovi.ru/videoEmbed/53/Как-скопировать-лендинг-lending-page?channelName=skriptcms"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="https://demo.clipbucket.com/enterprise/player/embed_player.php?vid=1840" allowscriptaccess="always" allowfullscreen="true" width="300" height="250"></embed></object>`

This is how it will look:
<a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/4/2/f9c756cb8e1009754755c05fcb4d498e-full.jpg" border="0"/></a>

I suggest doing it this way:
<a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/4/2/716c4fdeccb74454a353a374e9826188-full.jpg" border="0"/></a>

**Comment by DanielnetoDotCom** [comment]
Please confirm if that works.

**Comment by palich91** [comment]
It works
