### ISSUE TITLE
Public video: Category not working

### ISSUE THREAD

**Issue by macfori** [WWBN/AVideo#2725]
Public videos which could be played without login and have a public category show an error by clicking on the category link.

"Ops! Sorry, this video is private"

But the videos are public!.

Where can I find information about settings or logs to find the real error?
I have no idea what could be mis-configured.
Some categories work.
Is there a restriction by using names for categories?

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by macfori** [comment]
Logfile says:
User::canWatchVideo (videos_id is empty)

In the database the tables for videos have all an "id".
The problem is indipendent of beeing logged in as admin or anonymous user (no login).

**Comment by macfori** [comment]
Additional information
When changing the settings to Gallery or youtube on start-site, the categories Links work fine.
Perhaps that helps.

**Comment by DanielnetoDotCom** [comment]
@macfori please provide more of your log file.

**Comment by macfori** [comment]
This is the only entry in Logfile when clicking on a category (using standard view).
By using youtube or gallery as startsite there is no problem.


[21-Mar-2020 13:49:22 Europe/Berlin] Plugin Not Found: Statistics
[21-Mar-2020 13:49:25 Europe/Berlin] plugin::setCurrentVersionByUuid youu05bf-3570-4b1f-977a-fd0e5cabtube, 1.0
[21-Mar-2020 13:49:26 Europe/Berlin] Plugin Not Found: Statistics
[21-Mar-2020 13:49:53 Europe/Berlin] User::canWatchVideo (videos_id is empty)
