### ISSUE TITLE
Using CDN 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2729]
So I've seen that you have added the option of chunk ( to cancel the 100mb limit by cloudflare )
https://github.com/WWBN/AVideo/wiki/Using-CDN-for-Videos-Only#our-solution

I have a question about the videosCDN on the plugin and the copy of the demo site that you have created . 
Are the copy of the site on a vhost ? Pointing to the same directory ? /AVideo ? Like an ServerAlias ?
With this new option that you have added videosCDN can be the same as root url streaming site ?
Does the encoder works too with this ?

**Comment by DanielnetoDotCom** [comment]
Sorry, I do not understand your question.
but I do not have a copy of the demo site. the CDN points to the same site. but the CDN server will handle the copies of the static files around the world.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Can you specify what are the static files ?
Are we talking about videos ? Or only html/css/javascripts or videos as well ?

**Comment by DanielnetoDotCom** [comment]
non PHP files are static. html/css/javascripts/videos

but for example, the free Cloudflare layer does not host your videos.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom thank you the explanation about the free plan .
That means also that I can't livestream with cloudflare . With cloudflare up I can't get access to `.com:444/stat`
Any idea about this ? Does the upgrade plan allow that ? Or rtmp is not supported ?

**Comment by DanielnetoDotCom** [comment]
Hi

I do not have much information about it, but I guess it will not work.

try to ask Cloudflare what plan do you need for that. once you get the answer I will appreciate your share.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom enterprise customers only 
https://blog.cloudflare.com/introducing-concurrent-streaming-acceleration/
