### ISSUE TITLE
MonetizeUsers plugin not working

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#2731]
MonetizeUsers plugin does not work, money for watching videos is not credited.
On your demo https://demo.avideo.com/, this also doesn't work. Please correct the error.

**Comment by DanielnetoDotCom** [comment]
I just double check and it is working

![image](https://user-images.githubusercontent.com/18009293/77225483-4952b680-6b4e-11ea-9790-07ffa78d5bb4.png)

please make sure you read the rules to get rewarded.
https://github.com/WWBN/AVideo/wiki/MonetizeUsers-Plugin#rules-to-be-rewarded
