### ISSUE TITLE
Poster upload not retaining the upload

### ISSUE THREAD

**Issue by debjit-biswas** [WWBN/AVideo#2732]
Hi Daniel! 
While uploading poster to a video previously uploaded, I am getting no error in the UI but the error log has errors. 
Here is what I am doing:
![Screenshot 2020-03-21 at 11 48 33 AM](https://user-images.githubusercontent.com/50593814/77221174-5337e200-6b6d-11ea-8391-f9694c347b3c.png)
![Screenshot 2020-03-21 at 11 49 02 AM](https://user-images.githubusercontent.com/50593814/77221178-57fc9600-6b6d-11ea-80e2-3cec389c6413.png)

And here is the log-file
[avideo.log](https://github.com/WWBN/AVideo/files/4362527/avideo.log)

**Comment by DanielnetoDotCom** [comment]
Please check if it was not your browser cache.

clear the first-page cache and check again.

![image](https://user-images.githubusercontent.com/18009293/77225897-6ab5a180-6b52-11ea-9206-8f3b90c2c265.png)

**Comment by debjit-biswas** [comment]
I have tried both Cashe cleaning. Still no luck. Please help

**Comment by DanielnetoDotCom** [comment]
Ok, lets do this ...

1. delete your avideo.log file (to try to make easier find the problem)
1. go to your videos manager and try to change an image.
1. share here your new avideo.log and your javascript console.  https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

also make sure the file does not change, it may be a browser cache. NOT a system cache.

**Comment by debjit-biswas** [comment]
Done the exercise. Javascript error is in the screenshot.
Error log attached. 
Thank you in advance.

[avideo.log](https://github.com/WWBN/AVideo/files/4366731/avideo.log)

![Screenshot 2020-03-23 at 6 32 05 AM](https://user-images.githubusercontent.com/50593814/77270053-bee69000-6cd0-11ea-8ca3-dff97ba20928.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I can not see any error on your log

also, I notice your image was updated https://time8.tv/videos/_YPTuniqid_5e77472185c794.65074270_portrait.jpg

but your thumbs does not exist https://time8.tv/videos/_YPTuniqid_5e77472185c794.65074270_portrait_thumbsV2.jpg

can you please confirm you have the PHP GD installed?

FYI, usually, the thumbs are created when you cleat the cache and access the first page

**Comment by debjit-biswas** [comment]
GD is installed 
![GD1](https://user-images.githubusercontent.com/50593814/77331664-0e67a300-6d47-11ea-891c-6a2b39630bc3.PNG)
Cleared cache again. still no luck

**Comment by debjit-biswas** [comment]
Cache clear and page load log would be available in this log file. I did not notice any error but you are the expert. 
[avideo.js.log](https://github.com/WWBN/AVideo/files/4372866/avideo.js.log)
[avideo.log](https://github.com/WWBN/AVideo/files/4372867/avideo.log)

**Comment by debjit-biswas** [comment]
With the present state, I am unable to get thumbnails for any new video that I upload. Please help resolve the issue

**Comment by DanielnetoDotCom** [comment]
Please send to my email your admin user and ssh root credentials. I will check this.

**Comment by debjit-biswas** [comment]
Sent to you by mail. Much appreciate your help! Thank you.

**Comment by DanielnetoDotCom** [comment]
I went to your site and the video with thumbs error is not there. if you can please put a video with a thumbs error so I can check.

also, I notice you modify the main code. the first thing I recommend to do is to update your site with all original files so we can make sure the bug on the site is something on the main code or is something you modified.

**Comment by debjit-biswas** [comment]
My modifications were very cosmetic. Changed the navbar.php + userLogin.php + BigVideo.php only. Restored to original files now. Some CSS modifications are still on, through "Script Code" pannel. That should have no effect. 
Added a video named "Code Flythrough". Added poster to it. No thumb still.

**Comment by DanielnetoDotCom** [comment]
do you mind if I update you to the latest version restoring all original files?

**Comment by debjit-biswas** [comment]
Sure you can update.

**Comment by DanielnetoDotCom** [comment]
I notice you have changed the code in the streamer and encoder.

Once I update/overwrite both codes I can see your image on "Code Flythrough"

**Comment by debjit-biswas** [comment]
Frankly I am unaware of any change in these areas. Need to check how that happened.

**Comment by debjit-biswas** [comment]
I uploaded a video today morning. And it suffers from the same problem. 
![Capture](https://user-images.githubusercontent.com/50593814/77716333-f07a9680-7003-11ea-838c-8b59c7de97a4.PNG)

**Comment by debjit-biswas** [comment]
Another observation! The portrait thumbnail is visible on iPhone Chrome + Safari browsers. However the same is not visible on Android 10 Chrome + Firefox. Not visible on any windows machines any browser. Mac Safari - visible. Mac Chrome - Not visible. 
Cashe cleared for 1st page + Directory + Browser. 

Another observation: Cache clear menus on my site linking to https://time8.tv/# 
Is that okay?

**Comment by timbo-la** [comment]
> Another observation! The portrait thumbnail is visible on iPhone Chrome + Safari browsers. However the same is not visible on Android 10 Chrome + Firefox. Not visible on any windows machines any browser. Mac Safari - visible. Mac Chrome - Not visible.
> Cashe cleared for 1st page + Directory + Browser.
> 
> Another observation: Cache clear menus on my site linking to https://time8.tv/#
> Is that okay?

looks like I am having a similar problem.  i just opened up new issue as i didnt see this one. 

did you solve the problem?

Regards Tim

**Comment by DanielnetoDotCom** [comment]
@debjit-biswas I really not sure what happened.

I was just debugging and the image appears.

I can only guess is something related to some type of cache. browser or server cache.

If you get another image like this please let me know.

**Comment by debjit-biswas** [comment]
@DanielnetoDotCom The issue still remains! Though it works perfectly for iOS devices, does not work for any other OS. Tested on MAC/Windows/Android. Chrome inspect shows its pointing towards notfound_portrait.jpg. Kindly help!

**Comment by timbo-la** [comment]
> @DanielnetoDotCom The issue still remains! Though it works perfectly for iOS devices, does not work for any other OS. Tested on MAC/Windows/Android. Chrome inspect shows its pointing towards notfound_portrait.jpg. Kindly help!


check out my issue here,   as i was having similar problems and seemed to have solved them

https://github.com/WWBN/AVideo/issues/2765

regards Tim

**Comment by DanielnetoDotCom** [comment]
@debjit-biswas do you have another image with the same issue now?

**Comment by debjit-biswas** [comment]
Yes. And whenever I upload any video it meats the same fate. As @timbo-la has suggested it could be due to the character set. I am using an Indian character set(Bengali)in video name. It could be caused by that. 
If I install phpmyadmin on the server, will I break anything?

**Comment by DanielnetoDotCom** [comment]
I do not think it will break.

please try the characters solution.

**Comment by debjit-biswas** [comment]
I changed all databases to utf8_general_ci
All tables to utf8_general_ci
Unfortunately, it did not have any effect on my site. However, I am noticing that about a day from posting a video the poster-thumbnail becomes visible on all OS except iOS. On iOS it is visible right after posting. @DanielnetoDotCom do you think any cron that runs once a day may be responsible for this?
