### ISSUE TITLE
Language German: translation E-Mail

### ISSUE THREAD

**Issue by macfori** [WWBN/AVideo#2733]
Suggestion for the language German:  locale/de.php
The Item "E-Mail"  is in german identical "E-Mail"
The translation to E-Brief would point to another item, meaning mail as a letter.

Edit: I tried to make a change about the repository. (First time I do that, hoping it would be all right :)

**Comment by DanielnetoDotCom** [comment]
Make sure you send us a pull request of your modification, will be a pleasure to approve it.

**Comment by macfori** [comment]
Thanks for your hint. 
I hope I did it the right way :)

**Comment by DanielnetoDotCom** [comment]
Hi, 

I did not receive any pull requests.

**Comment by macfori** [comment]
Hm - I dont know where I did the pull request, but I'm shure I did an got the entry in a comment.
Here is the file.
Would that work?
[de.php.txt](https://github.com/WWBN/AVideo/files/4363101/de.php.txt)
