### ISSUE TITLE
Labels always on.

### ISSUE THREAD

**Issue by Social-Loafer** [WWBN/AVideo#2735]
Can you please fix it so we can turn off the "paid" and "free" labels.

**Comment by DanielnetoDotCom** [comment]
Fix what?

**Comment by Social-Loafer** [comment]
Well under the CustomizeAdvanced plugin it shows the option "paidOnlyShowLabels". I assumed that affected the label to either show or not show either of the "paid" and "free" labels.  If not then yes it would be a feature to be able to turn off those labels.
Much appreciated.

**Comment by akhilleusuggo** [comment]
@Social-Loafer Go to your plugin , and remove ''Free'' or replace it with a space ( blank )
![image](https://user-images.githubusercontent.com/52116577/77233543-d75f8900-6bb0-11ea-853c-33138a73d8f4.png)

**Comment by Social-Loafer** [comment]
I tried that it still shows a green label, blank on some, and some still show free, kind of weird...

**Comment by akhilleusuggo** [comment]
@Social-Loafer Clear the cache . you can browse to /videos 
`sudo rm -r cache/`

Also clear the cache of your browser , you should not see it .

**Comment by Social-Loafer** [comment]
That did the trick!
Much appreciated akhilleusuggo.
