### ISSUE TITLE
Encoder

### ISSUE THREAD

**Issue by nleonard20** [WWBN/AVideo#2737]
Hi there.
How would I be able to change the /encoder to /upload as I cant seem to find the /dir where it is located.
Also, is there away I can change the email message?
Thank you,
Nicholas L.

**Comment by DanielnetoDotCom** [comment]
It depends, what is your encoder URL?

try to find inside your dir /var/www/html/YouPHPTube/Encoder

**Comment by nleonard20** [comment]
Thank you.
