### ISSUE TITLE
Autoplay next-video-order _Option_ No longer playing videos in order "By Name"

### ISSUE THREAD

**Issue by Social-Loafer** [WWBN/AVideo#2738]
After Updating to the most recent version the autoplay next video is 'random' even though I have it set to 'By Name' under the 'Category Form' for option  'Autoplay next-video-order'.

**Comment by DanielnetoDotCom** [comment]
can you reproduce it on demo site?

**Comment by Social-Loafer** [comment]
Yeah, i changed the default category to 'By Name' and the next autoplay was not sorted by name, its random.
