### ISSUE TITLE
E-Mail (SMTP)

### ISSUE THREAD

**Issue by macfori** [WWBN/AVideo#2739]
E-Mail per SMTP is installed / configured correctly.
E-Mails will be send for testing. But in the Mail Text there ist your Server-Name

>>>> MAIL CONTENT >>>>
Name: Your Site test
Email: MY_MAIL_CORRECT
**Website: www.avideo.com**

Teste of comment
<<<<< MAIL CONTENT<<<<

How can I change the Name of the website? In the configuration panels I could not see a filed to get my server name in.

**Comment by DanielnetoDotCom** [comment]
that is only the test email.

the real emails will not have any relation with avideo

**Comment by macfori** [comment]
Great - tx fyi
