### ISSUE TITLE
live stream

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2740]
I'm setting up a dedicated only for live streams , to have a dedicated bandwidth for live-streams .
Before starting my confusions , the streaming server ( main domain ) ww1.domain.com , and livestreaming server ( stream.domain.com )

Questions : 
1-Since the livestreaming server is located on a different server , the rtmp config on ww1.domain.com can be deleted ? does it play any roll at all ?
2-What URL should be placed on the lines below . ww1.domain.com or stream.domain.com ?
```
on_publish http://[YouPHPTubeURL]/plugin/Live/on_publish.php;
on_play http://[YouPHPTubeURL]/plugin/Live/on_play.php;
on_record_done http://[YouPHPTubeURL]/plugin/Live/on_record_done.php;

```
3-Or maybe the script should be installed also on stream.domain.com ?
4- What about the plugin ? 
![image](https://user-images.githubusercontent.com/52116577/77259752-6db4ad00-6c8c-11ea-9cc5-02d7ce2402d8.png)

I can't understand it honestly .
I hope someone can help me .
Thanks in advance

**Comment by imrah6** [comment]
In the nginx.conf on your live streaming server it should be stream.domain.com and on the non-live streaming server it should be ww1.domain.com.

If you aren't using it on the main server then you don't need it in nginx.conf at all but you won't be able to start nginx with those three lines in there if you don't replace the [] with a valid URL. You can try just commenting out those lines.

**Comment by akhilleusuggo** [comment]
doesn't work 
And something is not making sense . How the dedicated streamer sites does accept the rtmp and key stream . Need to have some mixed parameters to make a connection between the streamer server and livestream server

**Comment by imrah6** [comment]
let me think about it a bit...I'm new to this myself.

**Comment by imrah6** [comment]
OK, without digging further into the code why don't you just setup a 
separate server for live streaming, as if it was your only server, and 
then use an http redirect to redirect "live" requests to that server 
with a normal redirect ?

That way you can avoid any coding and configuration issues and you also 
remove an additional load on the uploaded videos server. Apart from the 
redirect this will also keep the static video server cleaner and easier 
to manage when their are code updates.

This may be the only practical way to do it anyway.

R

**Comment by akhilleusuggo** [comment]
redirecting I guess you mean 301 oe 302
And what are you gonna redirect ? the domain name ? DNS ?
That's not gonna make any sense .
When someone gonna stream to stream.domain.com , the dns will redirect it to ww1.domain.com and the traffic will be sent to ww1.domain.com instead of stream.domain.com 
So it's like i've made nothing at all .

Maybe I didn't understood you well , that's why on my first question I've said 

> 3-Or maybe the script should be installed also on stream.domain.com ?

When i start obs , I get the same error when you introduce a wrong key stream or RTMP . And makes sense , since the server is not confirming the key and rtmp .
Definitely part of the script should be on the second server , or at the least part of the configuration.

**Comment by DanielnetoDotCom** [comment]
> 1-Since the livestreaming server is located on a different server , the rtmp config on ww1.domain.com can be deleted ? does it play any roll at all ?

Yes

> 2-What URL should be placed on the lines below . ww1.domain.com or stream.domain.com ?
> 
> on_publish http://[YouPHPTubeURL]/plugin/Live/on_publish.php;
> on_play http://[YouPHPTubeURL]/plugin/Live/on_play.php;
> on_record_done http://[YouPHPTubeURL]/plugin/Live/on_record_done.php;
> 

You should use ww1.domain.com but the on_record_done will not work, it requires the streamer and live stream to be on the same server

> 3-Or maybe the script should be installed also on stream.domain.com ?

you can move the streamer to there

> 4- What about the plugin?

all URLs point to stream.domain.com

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom can you explain the point 3 ?

> 3-Or maybe the script should be installed also on stream.domain.com ?
> 
> you can move the streamer to there

what do you mean move the streamer to there . Should I ? Or it's optional ?

**Comment by akhilleusuggo** [comment]
I'm just not able to start the stream 
![image](https://user-images.githubusercontent.com/52116577/77342447-deb19e80-6d38-11ea-83d2-16cf907d89df.png)

**Comment by akhilleusuggo** [comment]
Ok boys , I'm sorry my bad .
I had an issue with the firewall port .............. Kill me
