### ISSUE TITLE
User Management with MySQL Maybe??

### ISSUE THREAD

**Issue by jarredmoore** [WWBN/AVideo#2741]
I want to delete, add, update user, How and where do I do this?? Directly in SQL?? and How can I access mysql GUI?? I can get to it using my terminal but I'd perfer an interafce.

**Comment by akhilleusuggo** [comment]
phpmyadmin can do what you want .
You can edit users on user panel ( with admin account )
![image](https://user-images.githubusercontent.com/52116577/77270612-1840c600-6cb5-11ea-8401-d8eff4752856.png)

**Comment by DanielnetoDotCom** [comment]
For myself I use MySQL command line. for security reasons I do not use PHPMyAdmin.

but if you want you can install PHPMyAdmin in your server https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-phpmyadmin-on-ubuntu-18-04

**Comment by jarredmoore** [comment]
I try to stay on command line. So can I add and remove users from groups form the command line?? also can I add and remove videos for playlists and programs directly in the MySQL database on command line or stick to the admin dashboard of my VOD Instance..

**Comment by DanielnetoDotCom** [comment]
Hi, you can do all using the command line. but you must know what you are doing. there is no documentation for that.

why not use the site UI?

or  maybe use the API for that https://github.com/WWBN/AVideo/wiki/AVideo-Platform-API

**Comment by jarredmoore** [comment]
I added a bunch of videos to a playlist or membership level by mistake, now when I click on most of my video I get that annoying "this video is private" modal pop up so I need to remove/ recatagorize pretty much all my videos. I could firure out a clean way to do that  in the UI. The api looks promising and the upload video documentation as well. Let me try a few things and post my results when I done.

**Comment by jarredmoore** [comment]
Good Morning I still need some help using the UI to add an remove User and videos. Is there a way to do this in bulk??

**Comment by jarredmoore** [comment]
> phpmyadmin can do what you want .
> You can edit users on user panel ( with admin account )
> ![image](https://user-images.githubusercontent.com/52116577/77270612-1840c600-6cb5-11ea-8401-d8eff4752856.png)

**Comment by DanielnetoDotCom** [comment]
Looks like you skipped some versions.

The order column was in version 8.4. You CANNOT skip any version.

you may need to rollback https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform#rollback-the-update

**Comment by jarredmoore** [comment]
I followed option 1 but could tell if anything changed so I tried option two and got this "duplicate column name "rrating" error 
![Annotation 2020-04-10 104313](https://user-images.githubusercontent.com/7459434/79004414-53971d80-7b1a-11ea-8ea1-cb7212a0420a.jpg)

**Comment by DanielnetoDotCom** [comment]
You may find the duplicate column error. You can just ignore it and move to the next update script

**Comment by jarredmoore** [comment]
okay I'm on it..

**Comment by jarredmoore** [comment]
Okay so that got the site back up! I'm on version 8.6 now. Thanks again for point me to the link in the wiki. The docs are spot on about the importance of updates and Not to skip them. 

The paypal subsciption is still hanging up as it did after I upgraded from version 8.2 > 8.6 (git update)
![Annotation 2020-04-10 104313](https://user-images.githubusercontent.com/7459434/79007155-382f1100-7b20-11ea-85fd-cf8a9a7f275c.jpg)

As https://github.com/WWBN/AVideo/issues/2335 points out I thought it had to do with a video or user group settings assciated with the subscriotions but I don't thinks is being captured in the paypal log file.
![Annotation 2020-04-10 114854](https://user-images.githubusercontent.com/7459434/79007766-75e06980-7b21-11ea-95da-6393375a50c7.jpg)
 
Please advise..

**Comment by jarredmoore** [comment]
also after I went installed all the updateds I had to turn on the Walet plugin back on. Now I get my original error. 
![Annotation 2020-04-10 204928](https://user-images.githubusercontent.com/7459434/79032921-b2d34d00-7b6f-11ea-8599-c92ff044fcd0.jpg)

**Comment by jarredmoore** [comment]
I also tried stripe 
![Annotation 2020-04-10 221716](https://user-images.githubusercontent.com/7459434/79034130-583eee80-7b79-11ea-8876-b2ec40f45fed.jpg)

**Comment by DanielnetoDotCom** [comment]
Check your avideo.log file

**Comment by DanielnetoDotCom** [comment]
Also check this for stripe https://tutorials.avideo.com/video/79/configure-stripe?channelName=yeshua

**Comment by jarredmoore** [comment]
Here's a clip from my log. This is the first error that stood out to me [11-Apr-2020 03:17:09 UTC] PHP Warning:  It looks like the mbstring extension is not enabled. UTF-8 strings will not properly be encoded. Ask your system administrator to enable the mbstring extension, or write to support@stripe.com if you have any questions. in /var/www/html/YouPHPTube/plugin/StripeYPT/lib/Util/Util.php on line 183
![Annotation 2020-04-11 090736](https://user-images.githubusercontent.com/7459434/79046140-b64cef80-7bd4-11ea-9762-1d4bfaf05d58.jpg)

I'm going to go through the strip setup again..

**Comment by DanielnetoDotCom** [comment]
I cannot see all your error log lines. It would be good if I can.

definitely you have an error in creating a customer. maybe you did not give the permission on the Stripe Credentials API site.

![image](https://user-images.githubusercontent.com/18009293/79048167-8fe97d00-7bf1-11ea-9e3a-95184e560117.png)

**Comment by jarredmoore** [comment]
Yes, It was a permission issue so I just went through all the steps again and it's working now!   https://tutorials.avideo.com/video/79/configure-stripe?channelName=yeshua 

When a card is declined is there a different alert for insufficient funds?? I just get the error popup.
