### ISSUE TITLE
Questions about Subscriptions plugin

### ISSUE THREAD

**Issue by SoapTube** [WWBN/AVideo#2743]
I paid for this plugin quite a while back, but I downloaded a few months ago in December 2019. Is that the most recent version? If not, how do I update the plugin I currently have?

The plugin parameters include a field for "authKey." What is that for? It has a 13-digit "key" in their now, but it came like that.

Your instructions from the wiki for installation asks to configure the PayPal IPN and provides a link to PayPal for instructions. I follow those instructions, but I have no idea whether it is set up right. It asks me to "Specify the URL for your listener in the Notification URL field," but I have no idea what the URL should be and nothing in your instructions or their instructions make that at all clear.

Your instructions say to "Enable your IPN https://yoursite.com/plugin/PayPalYPT/ipn.php," but when I go to http://soaptube.tv/plugin/PayPalYPT/ipn.php, it simply says, "IPN Fail."

The log reads:

[22-Mar-2020 23:21:46 UTC] PayPalIPN Start
[22-Mar-2020 23:21:48 UTC] IPNcheck ERROR: The response from IPN was: <b>INVALID
[22-Mar-2020 23:22:23 UTC] userCanWatchVideoWithAds the plugin (Subscription) said user () can watch

**Comment by DanielnetoDotCom** [comment]
> I paid for this plugin quite a while back, but I downloaded a few months ago in December 2019. Is that the most recent version? If not, how do I update the plugin I currently have?

If you want to update , download it again from the plugins site https://youphp.tube/plugins/

> The plugin parameters include a field for "authKey." What is that for? It has a 13-digit "key" in their now, but it came like that.

No need to change it, it is like a secret that is used to talk with the payment gatways.

> Your instructions from the wiki for installation asks to configure the PayPal IPN and provides a link to PayPal for instructions. I follow those instructions, but I have no idea whether it is set up right. It asks me to "Specify the URL for your listener in the Notification URL field," but I have no idea what the URL should be and nothing in your instructions or their instructions make that at all clear.
> 
> Your instructions say to "Enable your IPN https://yoursite.com/plugin/PayPalYPT/ipn.php," but when I go to http://soaptube.tv/plugin/PayPalYPT/ipn.php, it simply says, "IPN Fail."
> 
> The log reads:
> 
> [22-Mar-2020 23:21:46 UTC] PayPalIPN Start
> [22-Mar-2020 23:21:48 UTC] IPNcheck ERROR: The response from IPN was: INVALID
> [22-Mar-2020 23:22:23 UTC] userCanWatchVideoWithAds the plugin (Subscription) said user () can watch

Also no need to change the IPN URL, it is for Paypal only, so you can not access it directly, it requires some PayPal parameters.

**Comment by SoapTube** [comment]
But what is the IPN URL? How do I find that? PayPal is asking for it and I don't know what my IPN URL is or how to find it. Thanks.

jdr

**Comment by DanielnetoDotCom** [comment]
If PayPal is asking it should be http://soaptube.tv/plugin/PayPalYPT/ipn.php

**Comment by SoapTube** [comment]
Ok. That is what I put in there already. I thought so. Just needed to confirm. Thanks.
