### ISSUE TITLE
Update to 8.6

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#2747]
Is there a new update available?  I see in the wiki and the issues mention of 8.6 but when I check my update version it tells me I'm up to date with version 8.3.

**Comment by nleonard20** [comment]
Hm, thats awkward. Mine says im up to date with 8.5 maybe its coming soon?

**Comment by DanielnetoDotCom** [comment]
If you make a `git pull` on git, you will get the version 8.6

check here how to do it https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by heiress01** [comment]
I'm still learning once again, I can update.  Here are the steps I took,  I entered: sudo git pull
and get the message below:
fatal: not a git repository (or any of the parent directories): .git

I entered:
cd /var/www/html/YouPHPTube/ && sudo git pull
and it ran something, I'm scared I might've messed something up.  

I don't know what to do next. Help!!

**Comment by heiress01** [comment]
> I'm still learning once again, I can update. Here are the steps I took, I entered: sudo git pull
> and get the message below:
> fatal: not a git repository (or any of the parent directories): .git
> 
> I entered:
> cd /var/www/html/YouPHPTube/ && sudo git pull
> and it ran something, I'm scared I might've messed something up.
> 
> I don't know what to do next. Help!!

I think I must have done something right.  As I now see available updates.  Whew!
