### ISSUE TITLE
Powered By

### ISSUE THREAD

**Issue by nleonard20** [WWBN/AVideo#2748]
Hi there
I bought the customize plugin however this still shows:
![seo](https://user-images.githubusercontent.com/62496317/77298029-90f94f80-6cc0-11ea-9c16-795d4227d5bc.PNG)
Please let me know how to remove the "Powered by Avideo"

**Comment by DanielnetoDotCom** [comment]
you need to wait for google to crawl your site again. I do not know how long it takes. 

but maybe this can help you https://support.google.com/websearch/answer/6349986?hl=en
