### ISSUE TITLE
Setting up Open Graph

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#2749]
Tell me which file is the main page on which I can configure the Open Graph protocol

**Comment by DanielnetoDotCom** [comment]
I am not sure what you want to do. but there is no main page. it is all dynamic.

**Comment by palich91** [comment]
There must be a <head> main page, I want to put Open Graph there. tell me where the file is located where <head> </head>

**Comment by DanielnetoDotCom** [comment]
To add something into the head tag Just go to site configuration menu -> in the section Script Code -> Head Code, you will find a text area to place your code
