### ISSUE TITLE
would someone be will to help make my server/ site load faster?

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#2750]
hello i have done updates and seem my site loads slow i am not sure why could someone maybe take a looking at my server settings/ site see if there anything they can do to make my server/site run better

you can see some issue at freedomshare.net

**Comment by freedomshare** [comment]
the server cpu useage is %0 - %10 at any given time so i am not sure why loading is such a progem

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/Speed-up-your-page
