### ISSUE TITLE
o embed no AVideo

### ISSUE THREAD

**Issue by heme007** [WWBN/AVideo#2751]
Gostaria de reabrir esta dúvida de muitos. O que rohitnehra quis dizer, é o que os vídeos, quando compartilhado no facebook, ou em qualquer stream, ou o vídeo não é apresentado aberto, ele fica com o link para clicar. E quando postar vídeos no youtube ou assistir a ele é apresentado com o link aberto, uma pessoa consegue assistir na minha página

**Comment by DanielnetoDotCom** [comment]
Isso e uma funcionalidade do facebook, não ha nada que possamos fazer.
