### ISSUE TITLE
/plugin/Livesearch/myVideos.json.php ( privacy break / issues )

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2753]
This plugin is exposing more data then it should .
Taking as example the demo site .
`{  "current": 1,"rowCount": 5, "total": 62, "rows":[{"id":83,"user":"admin","name":"Daniel Neto","email":"developer@youphptube.com","created":"2019-02-27 19:03:39","modified":"2020-02-15 08:17:43","isAdmin":1,"status":"a","photoURL":"videos\/userPhoto\/photo1.png","lastLogin":"2020-03-24 `

https://demo.avideo.com/plugin/Livesearch/myVideos.json.php

Why should this plugin expose the ''id'' user ( login ) and email , the day created account and modified , admin or not ( "isAdmin":1,"status":"a" ) ? 
This breaks privacy and and security issues .
I'm removing this plugin for now .

I'll keep reading all this pages to find out what more it's exposed .

**Comment by DanielnetoDotCom** [comment]
I agree, I just sent an update to it. and will remove most of the user information

**Comment by akhilleusuggo** [comment]
The access should denied like https://demo.avideo.com/objects/playlists.json.php

**Comment by DanielnetoDotCom** [comment]
the access can not be denied
