### ISSUE TITLE
Video switcher

### ISSUE THREAD

**Issue by moses268** [WWBN/AVideo#2754]
Is there a way in the player code to make this option
![IMG_20200324_131508](https://user-images.githubusercontent.com/47680534/77456721-a7d79900-6dc9-11ea-8eb2-3652093cc81d.jpg)

Show when the mobile screen is upright
![IMG_20200324_131441](https://user-images.githubusercontent.com/47680534/77456799-c0e04a00-6dc9-11ea-92d1-cf9c13ab04f1.jpg)

**Comment by DanielnetoDotCom** [comment]
I understand.

Looks like your player has too many buttons to display on mobile.
please, for now, disable the SeekButton and next plugin or try a player skin with smaller controls.

**Comment by moses268** [comment]
Ok
