### ISSUE TITLE
Database update issue

### ISSUE THREAD

**Issue by RogerWaldrip** [WWBN/AVideo#2755]
I finally gave up on trying to get this to work on a QNAP machine.  To many issues with what QNAP does (for instance, not letting me turn on the Apache logging and using to many sym-links which are nearly impossible to follow).  Anyhow, I moved my WordPress to another server and am in the process of trying to get Avideo/YouPHPTube installed and working.

I installed the latest version of Avideo streamer and encoder on the computer and still had an issue with the file not showing up in the streamer when the encoder is finished with it .  So I went back and found an older version of Avideo and installed it.  Whala!  Works.  Then I went and ran the updates all the way to 8.5.  Then I had problems. Not being to surprised, since I ran all the updates without checking after each subsequent update.  Anyhow, I wiped it all out, including the databases, and started over.

I installed streamer 4.8 and encoder without a hitch. All is working.  And decided to try my first update.  Seems like everything is OK.  Went to do the second update when I noticed a message about the database that reads, "Database-update needed You have version 4.91 installed , but your database is not up to date. This could lead to bugs. Please go to the update-site.'  When I click the link, it takes me to the update page.  I clicked update, thinking this may update the database, but it updated the version of Avideo.  Then I get the same error except it says, 'Database-update needed You have version 5.0 installed , but your database is not up to date. This could lead to bugs. Please go to the update-site.'

And I noticed that the encoder does send the file to the streamer but it never shows up in the GUI (I see the files show up in the streamers video folder).

So, I guess I'm asking how I go about getting Avideo to update it's database.

Thanks

**Comment by akhilleusuggo** [comment]
I don't understand why are you complicating the situation and yourself so much ...
Just follow this wiki guide , and you will not have any issues ...

https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer
