### ISSUE TITLE
Orphan files

### ISSUE THREAD

**Issue by jimhtwong** [WWBN/AVideo#2757]
Hi, 

We noticed that there are quite number of orphan videos files in videos folder. We try to find the function of deleting orphan files, but cannot find it. Can you advice what we can do?

**Comment by DanielnetoDotCom** [comment]
Hi

a long time ago I build something that does it.

https://github.com/WWBN/AVideo/blob/master/install/deleteOrphanFiles.php

I do not use it for a long time. **I recommend you to make a backup of the videos directory before run this procedure.**

to use, navigate into the install directory, usually it is `cd /var/www/AVideo/install/`

then run the php file with the php command `php deleteOrphanFiles.php`

the app will scan your videos directory and match with the videos on the database. 

then you will need to confirm if you really want to delete

**Comment by jimhtwong** [comment]
This one only execute is command prompt?

**Comment by jimhtwong** [comment]
https://github.com/WWBN/AVideo/issues/5#issuecomment-298981848

**Comment by jimhtwong** [comment]
https://github.com/WWBN/AVideo/issues/5#issuecomment-298981848

Can we have this function?

**Comment by DanielnetoDotCom** [comment]
This is an old version.

We do not have it anymore.
