### ISSUE TITLE
Encoder 

### ISSUE THREAD

**Issue by moses268** [WWBN/AVideo#2758]
![IMG_20200325_142346](https://user-images.githubusercontent.com/47680534/77571995-3ddbf400-6e9c-11ea-89c6-e0b1489ee6da.jpg)
Can I edit this code in the encoder for the low mp4 from 360 to 144p

Will it work after I change the number?

**Comment by DanielnetoDotCom** [comment]
Yes it will work

**Comment by moses268** [comment]
THANKS
