### ISSUE TITLE
Set up my own Stream Server

### ISSUE THREAD

**Issue by rogercong** [WWBN/AVideo#2759]
Dear all,

Sorry to bother you if this question has been asked before, anyway, I am trying to setup live after successfully installed stream server, followed instruction "Set up my own Stream server", after step 8, running nginx and check the stat, I received time-out error.
following is my nginx.conf
    worker_processes  1;
    error_log  logs/live-error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://my-steam-server.com/plugin/Live/on_publish.php;
#                            on_play http://my-steam-server.com/plugin/Live/on_play.php;
#                            on_record_done http://my-steam-server.com/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name my-steam-server.com;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   
            }
    }
and following is the error log:
2020/03/26 13:40:42 [notice] 25057#0: using the "epoll" event method
2020/03/26 13:40:42 [notice] 25057#0: nginx/1.12.0
2020/03/26 13:40:42 [notice] 25057#0: built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 
2020/03/26 13:40:42 [notice] 25057#0: OS: Linux 4.4.0-142-generic
2020/03/26 13:40:42 [notice] 25057#0: getrlimit(RLIMIT_NOFILE): 65535:65535
2020/03/26 13:40:42 [notice] 25058#0: start worker processes
2020/03/26 13:40:42 [notice] 25058#0: start worker process 25059
2020/03/26 13:40:42 [notice] 25058#0: start cache manager process 25060

Thank you！
roger

**Comment by DanielnetoDotCom** [comment]
is the http://my-steam-server.com/plugin/Live/on_publish.php; accessible?

check your nginx log file.

**Comment by rogercong** [comment]
no it's not working, error message 401, 
logs/error.log:
2020/03/26 23:43:05 [notice] 25058#0: signal 15 (SIGTERM) received, exiting
2020/03/26 23:43:05 [notice] 25059#0: exiting
2020/03/26 23:43:05 [notice] 25059#0: exit
2020/03/26 23:43:05 [notice] 25058#0: signal 17 (SIGCHLD) received
2020/03/26 23:43:05 [notice] 25058#0: worker process 25059 exited with code 0
2020/03/26 23:43:05 [notice] 25058#0: signal 29 (SIGIO) received
2020/03/26 23:43:05 [notice] 25060#0: exiting
2020/03/26 23:43:05 [notice] 25058#0: signal 17 (SIGCHLD) received
2020/03/26 23:43:05 [notice] 25058#0: cache manager process 25060 exited with code 0
2020/03/26 23:43:05 [notice] 25058#0: exit
2020/03/26 23:43:14 [notice] 26507#0: using the "epoll" event method
2020/03/26 23:43:14 [notice] 26507#0: nginx/1.12.0
2020/03/26 23:43:14 [notice] 26507#0: built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 
2020/03/26 23:43:14 [notice] 26507#0: OS: Linux 4.4.0-142-generic
2020/03/26 23:43:14 [notice] 26507#0: getrlimit(RLIMIT_NOFILE): 65535:65535
2020/03/26 23:43:14 [notice] 26508#0: start worker processes
2020/03/26 23:43:14 [notice] 26508#0: start worker process 26509
2020/03/26 23:43:14 [notice] 26508#0: start cache manager process 26510

**Comment by DanielnetoDotCom** [comment]
error message 401 is expected.

but looks like you have never made a publish  attempt 

are you sure you can reach port 1935?

**Comment by rogercong** [comment]
firewall blocks, thanks!!
