### ISSUE TITLE
Installing the torrent client on VPS

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#2760]
I want to install a torrent client on the server and download movies, so that in the future they can be placed on my video site vicovi.ru through Encoder.
Is it possible to do this?
torrent: https://www.utorrent.com/intl/ru/downloads/linux
Can I use µTorrent Server for Ubuntu 13.04?
Can you help me install and run a torrent client on VPS?

**Comment by akhilleusuggo** [comment]
what has your request to do with this project ?
