### ISSUE TITLE
why MP4 videos converted to other format while uploading through public encoder?

### ISSUE THREAD

**Issue by wahabzafar** [WWBN/AVideo#2761]
whenever i upload any video or encode through encoder MP4 videos status goas active but format changes as Other why?

**Comment by DanielnetoDotCom** [comment]
what do you mean?

please provide more details

**Comment by wahabzafar** [comment]
![image](https://user-images.githubusercontent.com/60570245/77782221-bf887900-7078-11ea-85c3-fa521dfac01c.png)

**Comment by DanielnetoDotCom** [comment]
??

**Comment by wahabzafar** [comment]
you can see first one it should be as MP4 because i have uploaded Mp4 format video but its is in other format due to this unable to play video.

**Comment by DanielnetoDotCom** [comment]
You have no MP4 file because your script fails somewhere. check your logs for some clue.

all other formats are images that means at least the images were extracted.

Just a guess, make sure your FFMPEG version is at least version 4

**Comment by wahabzafar** [comment]
i have uploaded many of videos earlier with same procedure and videos were going uploaded smoothly but now facing this error.

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/77783010-ec1ba100-7036-11ea-9ce4-546769c0e2ff.png)

**Comment by wahabzafar** [comment]
i have also contacted hosting provider for same issue but there is no problem at their end.

**Comment by wahabzafar** [comment]
can you please share how to check logs?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by wahabzafar** [comment]
ok thanks will update you soon.

**Comment by wahabzafar** [comment]
dear is there any video or screenshots to follow How-to-find-errors-on-AVideo-Platform.

**Comment by wahabzafar** [comment]
@DanielnetoDotCom dear please help me i am unable to understand as per your guidance please help me out.

**Comment by DanielnetoDotCom** [comment]
what is your website URL?

don't you know how to check the log files?

**Comment by wahabzafar** [comment]
my website url is https://moviestubeonline.com/ 

our script is on Cpanel and i dont know how to check log files.

**Comment by DanielnetoDotCom** [comment]
Sorry, I can only support ubuntu installations, but I am sure there is a way to do on Cpanel

**Comment by wahabzafar** [comment]
@DanielnetoDotCom please suggest any solution.

**Comment by DanielnetoDotCom** [comment]
Try to get an Ubuntu server and install it again.

**Comment by bunyamin19** [comment]
Hi can you help uploading direct link video    
my site http://wordsinema.com/evet/

**Comment by wahabzafar** [comment]
@DanielnetoDotCom dear please suggest any other solution i cant purchase ubuntu server please suggest solution on Cpanel.

**Comment by DanielnetoDotCom** [comment]
Sorry, I do not have another solution.

There are some users that could make it work over Cpanel. but I cannot support it.

**Comment by wahabzafar** [comment]
Please any user can help to resolve my issue on Cpanel???
