### ISSUE TITLE
Install instructions accurate?

### ISSUE THREAD

**Issue by soapstreams** [WWBN/AVideo#2762]
Are these instructions even up to date:

`sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube.git`

Or should that be:

`sudo git clone https://github.com/WWBN/AVideo.git`

I got this reference to `AVideo.git` in a post about an issue I created related to the lack of installation instructions for the Network. After the obligatory, smarmy insults implying I am stupid, I was eventually given some useful instructions.

Did I install an older version from an outdated repository? Not too long ago I installed this and it created an AVideo directory. This last time it created the YouPHPTube directory.

Any thoughts?

**Comment by DanielnetoDotCom** [comment]
Both links are the same. 

We renamed the project, but they both will install the same version, just the directory will be different.
