### ISSUE TITLE
Ads on paid videos

### ISSUE THREAD

**Issue by moses268** [WWBN/AVideo#2763]
![Screenshot_2020-03-26-13-28-27-938_com android chrome](https://user-images.githubusercontent.com/47680534/77677440-b35bc900-6f5d-11ea-8913-e8aabcff2729.png)

Ads still show on the paid videos although I have the option selected to show ads only on free play only

![Screenshot_2020-03-26-13-32-30-770_com android chrome](https://user-images.githubusercontent.com/47680534/77678122-9dafc900-6f88-11ea-8ef3-891365749161.png)

**Comment by DanielnetoDotCom** [comment]
You forgot to enable the plugin GoogleAds

I enable for you, but you are using the ads test tag.

make sure you apply for the video ads. https://github.com/WWBN/AVideo/wiki/Plugin:-GoogleAds_IMA---Videos-Ads-on-your-page

FYI, you can use any Video ads company you want, NOT just google.

![image](https://user-images.githubusercontent.com/18009293/77682127-2b81b900-6f75-11ea-9748-22a979b4d731.png)

Also I removed that from your GoogleAds_Ima

![image](https://user-images.githubusercontent.com/18009293/77683356-08580900-6f77-11ea-9de3-8f173c0fea03.png)


Also you check this option in your video

![image](https://user-images.githubusercontent.com/18009293/77682890-5a4c5f00-6f76-11ea-9086-36f10c178321.png)

this will not show the video for non paid users.

You had a misconfiguration on your notification plugin

![image](https://user-images.githubusercontent.com/18009293/77683050-997ab000-6f76-11ea-98c8-ca4c7385679a.png)

I disable it until you get the correct credentials

![image](https://user-images.githubusercontent.com/18009293/77683133-bb743280-6f76-11ea-98af-299f00a71088.png)


Now I can see some ads

**Comment by moses268** [comment]
Maybe you misunderstood,
I want when persons pay and are in the subscription groups the videos to
not show any ads and the ads to pay only on the free videos

**Comment by DanielnetoDotCom** [comment]
@moses268 I apologize, I really misunderstood you.

we do not have this option for now.

**Comment by moses268** [comment]
Kool. How much would it cost to make or create? For future reference

I doubt persons who pay will want to see ads

**Comment by DanielnetoDotCom** [comment]
Please email me the requirements to developer@youphptube.com

I will quote it for you.

**Comment by moses268** [comment]
Ok will do
