### ISSUE TITLE
Live plugin videojs-drvseekbar.min.js

### ISSUE THREAD

**Issue by djslmft** [WWBN/AVideo#2764]
Hello,

I have this line in my php error log:
JS-Err: IndexSizeError: The index is not in the allowed range. @ line 2 in file https://url/plugin/Live/videojs-dvr/videojs-dvrseekbar.min.js at visit on /plugin/Live/?c=streamkey
and the dvr function is not working at all

Do you have any idea what it could be?

Another thing:
The live user counter doesn't work as we expect on the network traffic on the server
It shows 10 viewers by 100Mbps or more traffic by a 3,5Mbps stream, what should i check?

**Comment by DanielnetoDotCom** [comment]
DVR is an experimental feature, it is not 100% yet.

I do not understand what do you mean with "10 viewers by 100Mbps or more traffic by a 3,5Mbps stream"

**Comment by djslmft** [comment]
Thanks for the fast reply.

Waiting for an update for the live plugin!

The Live User counter shows 10 viewers, but on the server is 100Mbps or more traffic that indicates about 30+ viewers at a time.

**Comment by DanielnetoDotCom** [comment]
U see, can you please check it with some google analytics?

**Comment by akhilleusuggo** [comment]
maybe other users are watching some videos ?
Maybe something on the background 
It's not a 100% sure to measure it

**Comment by djslmft** [comment]
i made some calculations, and it looks okay, sry for the inconvenience
