### ISSUE TITLE
uploaded thumbnail not showing

### ISSUE THREAD

**Issue by timbo-la** [WWBN/AVideo#2765]
Hi, 
i have looked at similler issues like this but cant figure out if they are related.

my issue is:

i installed AVideo and set it up so users have to login to view the website, because it is an educational website only available to people who I give permission to.

The problem i have:

I direct upload an .mp4 to my site, then upload custom ,jpg, ,webp, .gif files to act as the videos thumbnail. 

in the my videos page i can see the video thumbnail (see attached jpeg)

![admin - my videos](https://user-images.githubusercontent.com/62733119/77721762-1bc6ab00-702f-11ea-8395-cb4fc1b10001.jpg)

but in the front-end they don't appear

![front end](https://user-images.githubusercontent.com/62733119/77721880-6cd69f00-702f-11ea-827c-da5fa6e9aa10.jpg)

when i view them on Windows 10 chrome browser, Brave Browser, microsoft edge they dont appear.  HOWEVER on an iphone 10  safari and chrome browser they are viewable.

[avideo.log](https://github.com/WWBN/AVideo/files/4391514/avideo.log)

thanks for the help

Tim

**Comment by TLCReuver** [comment]
If *._thumbsSmallV2.jpg and/or *_thumbsV2.jpg does not exists you can restart Ubuntu (not apache). Avideo generate these files. I have that problem after a few direct uploads with no errors in log.

**Comment by timbo-la** [comment]
> If *._thumbsSmallV2.jpg and/or *_thumbsV2.jpg does not exists you can restart Ubuntu (not apache). Avideo generate these files. I have that problem after a few direct uploads with no errors in log.

hi, thanks for the reply.
If i understand restarting Ubuntu only applies to when it is installed on a local machine?

My AVideo is on my hostings webserver.

Regards Tim

**Comment by akhilleusuggo** [comment]
@timbo-la Can you try something just for testing ? Change your password , then try again .
```
[27-Mar-2020 02:32:06 UTC] Password check new hash pass does not match, trying MD5
[27-Mar-2020 02:32:06 UTC] Password check Old not encoded pass
[27-Mar-2020 02:32:06 UTC] Password check Old not found
```

Also you could get the plugin for that .

**Comment by timbo-la** [comment]
> @timbo-la Can you try something just for testing ? Change your password , then try again .
> 
> ```
> [27-Mar-2020 02:32:06 UTC] Password check new hash pass does not match, trying MD5
> [27-Mar-2020 02:32:06 UTC] Password check Old not encoded pass
> [27-Mar-2020 02:32:06 UTC] Password check Old not found
> ```
> 
> Also you could get the plugin for that .

tried changing the password but no luck.

do you mean the plugin that makes the thumbs when you upload?

Tim

**Comment by akhilleusuggo** [comment]
@timbo-la yep , a payed plugin ( I don't have it ) , I use the encoder that's why .
Try also to `sudo chown -R www-data *`  ( on the /var/www/html )
`sudo chmod -R 755 *`

Maybe a permission error ( should be on `/videos` directory )

**Comment by timbo-la** [comment]
> @timbo-la yep , a payed plugin ( I don't have it ) , I use the encoder that's why .
> Try also to `sudo chown -R www-data *` ( on the /var/www/html )
> `sudo chmod -R 755 *`
> 
> Maybe a permission error ( should be on `/videos` directory )

thanks for the input, but it didn't seem to solve the issue, However I think i have found the solution to my issue.

after trying  a possible workaround, I discovered the the possible problem

my database was using collation  latin1_swedish_ci

i am a mixture of  Japanese and English in the titles of my videos, after changing the database and all tables over to utf8_general_ci and doing a direct upload of an .mp4 as well as uploading the images to be displayed, everything seems to be working ok now.

hope this can help other people  troubleshoot similar problems.

thanks for all the help 

Tim

**Comment by debjit-biswas** [comment]
Hi @timbo-la 
Did you change the code here? updatedb/updateDb.v5.5.sql  and updatedb/updateDb.v5.7.sql
Or you just migrated the Database from latin1_swedish_ci to latin1_general_ci? 
In either case, @DanielnetoDotCom would you kindly change the code so that non-latin characters can be taken care of? My site too has Bengali characters. Thanks @timbo-la for pointing this out!

**Comment by timbo-la** [comment]
Hi,

I logged into my hosting and went to "PHP my admin" then changed the database to utf8_general_ci  as well as all of the tables.

little bit time consuming as i didnt know how to do it in a batch process.

hopefully the images make sense:

![Annotation 2020-03-30 134636](https://user-images.githubusercontent.com/62733119/77876218-4f9f0c00-728d-11ea-84ca-65112f191c07.jpg)
![Annotation 2020-03-30 134636b](https://user-images.githubusercontent.com/62733119/77876220-5168cf80-728d-11ea-99c2-6565b817501c.jpg)
![Annotation 2020-03-30 134636c](https://user-images.githubusercontent.com/62733119/77876221-5168cf80-728d-11ea-89fa-8f06c3c79487.jpg)


hopefully it solves your problem, in hindsight i have this problem with other CMS as well.

stay safe Tim

**Comment by debjit-biswas** [comment]
Thank you Tim! really appreciate your support...
@timbo-la

**Comment by timbo-la** [comment]
> Thank you Tim! really appreciate your support...
> @timbo-la

no worries, report back if it worked.

**Comment by debjit-biswas** [comment]
I changed all databases to utf8_general_ci
All tables to utf8_general_ci
Unfortunately, it did not have any effect on my site. However, I am noticing that about a day from posting a video the poster-thumbnail becomes visible on all OS except iOS. On iOS it is visible right after posting. @DanielnetoDotCom do you think any cron that runs once a day may be responsible for this?

**Comment by DanielnetoDotCom** [comment]
Yes, it looks like for me some type of server cache.

I am not sure where it comes from. 

are you using some type of CDN? or maybe some lib to speedup PHP?

**Comment by debjit-biswas** [comment]
I have no additional code or CDN

**Comment by timbo-la** [comment]
> I have no additional code or CDN

sorry it didn't solve your problem.  i am no expert myself to be honest, the only thing i can suggest is to, if you can.

1, upload a fresh install to your hosting (in sub directory for testing purposes)
2, check the database to make sure it is utf-8
3, upload a video to see if it works.

sorry if is not much help, but on the site you are working,  you may have changed a setting  that you forgot about that is giving you problems. 

Tim

**Comment by akhilleusuggo** [comment]
I had this problem time ago , and has nothing to do with database

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/issues/2480

**Comment by timbo-la** [comment]
thanks for the input, out of interest how would you go about doing the change not using the sudo command?  

regards Tim

**Comment by debjit-biswas** [comment]
@akhilleusuggo I am certain that the permission issue is not preventing the display. I surely have the right permission.

**Comment by akhilleusuggo** [comment]
@timbo-la I used used , but you can switch to root ( not recomended )
`sudo -s`

**Comment by DanielnetoDotCom** [comment]
I recently submitted an update for thumbs, that seems like was not updating.
