### ISSUE TITLE
Live problems

### ISSUE THREAD

**Issue by gersonfernandes** [WWBN/AVideo#2766]
good, when trying to do the live, I have the following problem:

<img src="http://www.gersonfernandes.pt/imagens/1.jpg">
<img src="http://www.gersonfernandes.pt/imagens/2.jpg">

can you help me please?

**Comment by DanielnetoDotCom** [comment]
Looks like for me it is a windows machine.

I doubt you could install RTMP Nginx on it

In the first step, try to install it on Ubuntu.

**Comment by gersonfernandes** [comment]
> Looks like for me it is a windows machine.
> 
> I doubt you could install RTMP Nginx on it
> 
> In the first step, try to install it on Ubuntu.

Daniel speak in portuguese?

**Comment by DanielnetoDotCom** [comment]
Sim eu falo

**Comment by gersonfernandes** [comment]
> Sim eu falo

Boa! Sou Português =)

Tentei tambem através do servidor onde tenho a minha página e também não consegui

<img src="http://www.gersonfernandes.pt/imagens/5.jpg">
<img src="http://www.gersonfernandes.pt/imagens/3.jpg">
<img src="http://www.gersonfernandes.pt/imagens/4.jpg">

**Comment by DanielnetoDotCom** [comment]
Seu servidor é Centos.

na primeira página recomendamos apenas o Ubuntu sem nenhum painel de controle (apenas linha de comando)

O servidor tem que ser VPS ou dedicado. servidores compartilhados não funcionam tambem.

**Comment by gersonfernandes** [comment]
que chatice...
Podes indicar-me um que possa usar?

**Comment by DanielnetoDotCom** [comment]
Nós vendemos 

1 ano de VPS (120 USD/ano)
RAM 2GB, Storage 150GB, 2 CPU, Transfer 4TB

Servidor dedicado (100 USD/mes)
RAM 16GB, Storage 2TB, 4 CPU, Transfer Unlimited.

se pegar o servidor o serviço de instalação vai com desconto.

Olha os valores aqui https://youphp.tube/services
