### ISSUE TITLE
How can I add an MRSS code to videos?

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#2768]

**Comment by DanielnetoDotCom** [comment]
Looks like we only have RSS for channels and for the whole site.

I am not sure the difference between MRSS and RSS, but I guess it will require some code.

**Comment by heiress01** [comment]
Here's a link to a page that I found.  https://tubularinsights.com/mrss-rss-mrss-video-syndication/ it explains the difference between MRSS and RSS.  I'm new to all of this so, what they say is simple is complicated for me.  I can see the rss for my site but, I don't have a clue how to access it or how to add the extension to it. Here's another link explaining how to add the extension https://tubularinsights.com/how-to-create-mrss/ 
but again, it's totally confusing as I don't know where to start.

**Comment by DanielnetoDotCom** [comment]
Why do you need MRSS? to use where?

**Comment by heiress01** [comment]
> Why do you need MRSS? to use where?

I need it to create a channel stream for Roku.
