### ISSUE TITLE
Only verified users can comment 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2769]
Can you add this option please ?

**Comment by DanielnetoDotCom** [comment]
This should do the trick

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Thank you !

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Well , actually it's miss leading 
None verified users sees this : 
![image](https://user-images.githubusercontent.com/52116577/77935534-32ccfd80-72ba-11ea-91bb-8ae9144f72b6.png)

**Comment by DanielnetoDotCom** [comment]
Update sent
