### ISSUE TITLE
Trying to stream from my network

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#2770]
I ran into a problem with the streaming. I am using OBS, Prism Live Studio to connect to the streaming server, it is telling me: the media could not be loaded, either because the server or network failed or because the format is not supported. Can you assist me on this matter, please?

Thank you again

![image](https://user-images.githubusercontent.com/62782361/77813663-4be66c00-7078-11ea-898a-bf0990ee10af.png)

**Comment by CROSSMediaNet** [comment]
I just figure it out...man, I fill stupid

**Comment by maundinc** [comment]
How did you solve this issue please?
