### ISSUE TITLE
live stream not working

### ISSUE THREAD

**Issue by rogercong** [WWBN/AVideo#2771]
Hi all,

First of all, thank you for your time!  

I did look into some of the previous posted issues, tried to follow but lost... anyway there is my problem, just could not get live stream going, I tried to OBS from my computer to server, I did test vod, which is working, i guess rtmp server is up and running.  here is what i have:
![1](https://user-images.githubusercontent.com/13609453/77814916-2c9d0e00-707b-11ea-8555-723458d986ae.jpg)

![2](https://user-images.githubusercontent.com/13609453/77815026-193e7280-707c-11ea-9069-0a04ba3cd180.jpg)

![3](https://user-images.githubusercontent.com/13609453/77815118-39226600-707d-11ea-8676-3fb025c09772.jpg)

Here is my nginx.conf: 

user  www-data; ##nobody
worker_processes  1;

error_log  logs/rtmp-error.log debug;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       8080;
        server_name  mv.mywebsite.com;
        root /usr/local/nginx/html;
        index index.html index.htm index.php;
        location /{
                index index.html;
        }
        # sample handlers
        #location /on_play {
        #    if ($arg_pageUrl ~* localhost) {
        #        return 201;
        #    }
        #    return 202;
        #}
        #location /on_publish {
        #    return 201;
        #}

        #location /vod {
        #    alias /var/myvideos;
        #}

        # rtmp stat
        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }
        access_log /usr/local/nginx/logs/host.access.log;
        access_log /usr/local/nginx/logs/host.access.404.log;
        location /stat.xsl {
            # you can move stat.xsl to a different location
            root /usr/local/nginx/html;
        }

        # rtmp control
        location /control {
            rtmp_control all;
        }
        location /live {
            # Serve HLS fragments
 
            # CORS setup
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length';
 
            # allow CORS preflight requests
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /HLS;
            add_header Cache-Control no-cache;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}

rtmp {
    server {
        listen 1935;
        #ping 30s;
        allow play all;
        notify_method get;

        application live {
            allow play all;
            live on;
            record off;
            # sample play/publish handlers
            #on_play http://mywebsite.com:8080/on_play;
            #on_publish http://mywebsite.com/plugin/Live/on_publish.php;

            # sample recorder
            #recorder rec1 {
            #    record all;
            #    record_interval 30s;
            #    record_path /tmp;
            #    record_unique on;
            #}

            # sample HLS
            hls on;
            hls_nested on;
            hls_path /HLS/live;
            #hls_fragment 10s;
            on_publish http://mv.mywebsite.com/plugin/Live/on_publish.php;
            on_play http://mv.mywebsite.com/plugin/Live/on_play.php;
            on_record_done http://mv.mywebsite.com/plugin/Live/on_record_done.php;
            #hls_path /tmp/hls;
            #hls_sync 100ms;
        }

        # Video on demand
        application vod {
            play /usr/local/nginx/rtmp;
        }

        # Video on demand over HTTP
        #application vod_http {
        #    play http://localhost:8080/vod/;
        #}
    }
}
Thank you in advance!
roger

**Comment by akhilleusuggo** [comment]
what about the plugin ?

**Comment by DanielnetoDotCom** [comment]
check your NGINX log file.

**Comment by rogercong** [comment]
Here is my nginx log:

2020/03/28 10:59:25 [info] 5808#0: *709 client connected '104.243.196.208'
2020/03/28 10:59:25 [info] 5808#0: *709 connect: app='live' args='p=76c73030eb03fe4e6176063ca3b39221' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://mv.mywebsite.com/live?p=76c73030eb03fe4e6176063ca3b39221' tc_url='rtmp://mv.mywebsite.com/live?p=76c73030eb03fe4e6176063ca3b39221' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 104.243.96.208, server: 0.0.0.0:1935
2020/03/28 10:59:25 [info] 5808#0: *709 createStream, client: 104.243.196.208, server: 0.0.0.0:1935
2020/03/28 10:59:26 [info] 5808#0: *709 publish: name='5e7d9c811bf79' args='' type=live silent=0, client: 104.243.96.208, server: 0.0.0.0:1935
2020/03/28 10:59:26 [info] 5808#0: *709 notify: publish 'mv.ip2telephone.com/plugin/Live/on_publish.php', client: 104.243.196.208, server: 0.0.0.0:1935
2020/03/28 10:59:26 [info] 5808#0: *709 disconnect, client: 104.243.196.208, server: 0.0.0.0:1935
2020/03/28 10:59:26 [info] 5808#0: *709 deleteStream, client: 104.243.196.208, server: 0.0.0.0:1935
2020/03/28 11:25:21 [notice] 5807#0: signal 15 (SIGTERM) received, exiting
2020/03/28 11:25:21 [notice] 5809#0: exiting
2020/03/28 11:25:21 [notice] 5807#0: signal 17 (SIGCHLD) received
2020/03/28 11:25:21 [notice] 5807#0: cache manager process 5809 exited with code 0
2020/03/28 11:25:21 [notice] 5807#0: signal 29 (SIGIO) received
2020/03/28 11:25:21 [notice] 5808#0: exiting
2020/03/28 11:25:21 [notice] 5808#0: exit
2020/03/28 11:25:21 [notice] 5807#0: signal 17 (SIGCHLD) received
2020/03/28 11:25:21 [notice] 5807#0: worker process 5808 exited with code 0
2020/03/28 11:25:21 [notice] 5807#0: exit

**Comment by rogercong** [comment]
2020/03/28 10:59:25 [info] 5808#0: *709 client connected '104.243.196.208'
2020/03/28 10:59:25 [info] 5808#0: *709 connect: app='live' args='p=76c73030eb03fe4e6176063ca3b39221' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://mv.mywebsite.com/live?p=76c73030eb03fe4e6176063ca3b39221' tc_url='rtmp://mv.mywebsite.com/live?p=76c73030eb03fe4e6176063ca3b39221' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 104.243.196.208, server: 0.0.0.0:1935
2020/03/28 10:59:25 [info] 5808#0: *709 createStream, client: 104.243.196.208, server: 0.0.0.0:1935
2020/03/28 10:59:26 [info] 5808#0: *709 publish: name='5e7d9c811bf79' args='' type=live silent=0, client: 104.243.196.208, server: 0.0.0.0:1935
2020/03/28 10:59:26 [info] 5808#0: *709 notify: publish 'mv.mywebsite.com/plugin/Live/on_publish.php', client: 104.243.196.208, server: 0.0.0.0:1935
2020/03/28 10:59:26 [info] 5808#0: *709 disconnect, client: 104.243.196.208, server: 0.0.0.0:1935
2020/03/28 10:59:26 [info] 5808#0: *709 deleteStream, client: 104.243.196.208, server: 0.0.0.0:1935
2020/03/28 11:25:21 [notice] 5807#0: signal 15 (SIGTERM) received, exiting
2020/03/28 11:25:21 [notice] 5809#0: exiting
2020/03/28 11:25:21 [notice] 5807#0: signal 17 (SIGCHLD) received
2020/03/28 11:25:21 [notice] 5807#0: cache manager process 5809 exited with code 0
2020/03/28 11:25:21 [notice] 5807#0: signal 29 (SIGIO) received
2020/03/28 11:25:21 [notice] 5808#0: exiting
2020/03/28 11:25:21 [notice] 5808#0: exit
2020/03/28 11:25:21 [notice] 5807#0: signal 17 (SIGCHLD) received
2020/03/28 11:25:21 [notice] 5807#0: worker process 5808 exited with code 0
2020/03/28 11:25:21 [notice] 5807#0: exit

**Comment by rogercong** [comment]
I do see live video stream sent to server, as indicated on server menu bar there is "1";  the next question is, can not display on the server, it shows: 
The media could not be loaded, either because the server or network failed or because the format is not supported.
Thank you for your time!

**Comment by rogercong** [comment]
from apahce2 error log, we have:

hromaprint --disable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[http @ 0x557cbe54a2c0] HTTP error 404 Not Found
http://mv.mywebsite.com/live/5e7ecd115e03f.m3u8: Server returned 404 Not Found

There is 5e7ecd115e03f folder, and within it, there are some .ts files and index.m3u8, why it became 5e7ecd115e03f.m3u8, which file should I look into?

Thanks in advance!

**Comment by akhilleusuggo** [comment]
what about the plugin ???
If you're getting error on OBS , most likely you're having a firewall issue on your nginx server .
Make sure the ports are open .

**Comment by rogercong** [comment]
I dont have any plugin, normally which port are used by nginx server?

**Comment by rogercong** [comment]
Sorry, did you mean live plugin...
{"button_title":"LIVE","server":"rtmp://mv.mywebsite.com/live","playerServer":"http://mv.mywebsite.com/live","stats":"http://mv.mywebsite.com:8080/stat","disableDVR":true,"disableGifThumbs":true,"useAadaptiveMode":true,"experimentalWebcam":true,"doNotShowLiveOnVideosList":false}

**Comment by akhilleusuggo** [comment]
that's the key !! change 
`"useAadaptiveMode":false`

or make it look like this : 
![image](https://user-images.githubusercontent.com/52116577/77862687-c30d3300-7225-11ea-93ca-7faedb15e413.png)
 and save !

**Comment by rogercong** [comment]
Working now, Thank you for your help！
