### ISSUE TITLE
YPTWallet turns off by itself

### ISSUE THREAD

**Issue by MrWeb** [WWBN/AVideo#2772]
Since we upgraded to latest version we have customer notifying the paypal button is stuck on loading.
Every time this happens we go into plugins ant the YPTWallet is off. 

![WhatsApp Image 2020-03-28 at 14 18 43](https://user-images.githubusercontent.com/4120466/77824000-80513b00-70ff-11ea-9a55-29a4b1dc8bc1.jpeg)

We manually turn it back on but this lasts 1-2 days, then we have the same precise issue and the plugin is off again. How can this be?

Also, in the Subscription plugin there is a "YPTWallet" button. Is "red" ON or OFF?
There is no feedback on this and I have no Idea what is the correct state, should it be red or green?

![Screenshot 2020-03-28 at 14 22 20](https://user-images.githubusercontent.com/4120466/77824024-9f4fcd00-70ff-11ea-9a45-7af673f1cb03.png)

**Comment by DanielnetoDotCom** [comment]
can you please check your log file?

I have never seen this happen before

**Comment by MrWeb** [comment]
The log file was 500+MB so I manually turned on the plugin and emptied the log so that next time it happens I can share it.

Can you please tell me about this green/pink button?
Is pink ON or OFF?
There is no feedback on this and I have no Idea what is the correct state, should it be pink or green?

![](https://user-images.githubusercontent.com/4120466/77824024-9f4fcd00-70ff-11ea-9a45-7af673f1cb03.png)

**Comment by DanielnetoDotCom** [comment]
you can delete your log file, try again, then check your new log file.

the color depends on your theme. what really matters is the switch button

**Comment by MrWeb** [comment]
Ok do the log I did. Now let’s wait it turns off again.

Ok for the color BUT if I press it becomes green and if I press it again goes pink. Looks like a toggle of the crib but I don’t understand when it is on and when off. Do you see my point? What state should that be?

**Comment by DanielnetoDotCom** [comment]
Green is probably ON. but I use only the default color schemes, you are using a customized scheme, that is why I am not sure about your colors.

**Comment by MrWeb** [comment]
Ok great. Can you tell me what that does in the DB or file system so that I can check if is on or off? I tried looking inside the plugin but it looks like it does nothing there.

**Comment by DanielnetoDotCom** [comment]
You should find a status column in the plugins database
