### ISSUE TITLE
In general setting can't toggle any button.

### ISSUE THREAD

**Issue by sharad22gupta** [WWBN/AVideo#2773]
in general settings cant toggle any button in user, uploads, singin and encode. when I click on save it keeps showing processing and nothing happens.

**Comment by DanielnetoDotCom** [comment]
Check for Javascript errors

then look into the logs

also you have the option to change it directly into the plugins menu. instead, use the admin menu.

**Comment by sharad22gupta** [comment]
Worked using plugins menu, Thanks
