### ISSUE TITLE
encoder processing forever

### ISSUE THREAD

**Issue by GodgivenButhelezi** [WWBN/AVideo#2775]
Good Day I have A Problem with my encoder it's not logging me in, but is says processing forever and never log me in, but my login details are correct because it did say congratulations, but did not log me in. Please help

**Comment by akhilleusuggo** [comment]
check the logs , and try changing browser

**Comment by GodgivenButhelezi** [comment]
How do I check the logs for Encorder? I'm using chrome and explorer as browser

**Comment by DanielnetoDotCom** [comment]
@GodgivenButhelezi here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by GodgivenButhelezi** [comment]
Mr Danielneto Sir . how much would you charge me to fix my my Stream I thought it was working but i was wrong. I want to purchase the video to encorder plugin and chat plugin now, but I'm worried my stream is not working yet.  This codes here on the top does not work because I installed my avideo platform via cpanel uploading it through ftp, so  will need your assistance please and price if you may let me know. I want to start preaching in my stream during this corona lock down.

**Comment by DanielnetoDotCom** [comment]
Hi

Basic installation costs 70 USD but to make the installation we require from you a clean Ubuntu server. we do not install on a Centos with Cpanel.

All our prices are on our services website https://www.youphptube.com/services , on the site also you will find packages with excellent discounts, which include services and plugins.

If you want, you can also buy the plugins separately, the plugins also have a progressive discount, more plugins, the bigger the discount.

Or you can hire us for an hour of support. hour rate is 30 USD/hour
