### ISSUE TITLE
separate page for live broadcasts

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#2776]
Hello!
Tell me how to make a separate page on which only the m3u8 broadcasts that I add here will be displayed (see screenshot): https://vfl.ru/fotos/912295b130042614.html

**Comment by DanielnetoDotCom** [comment]
Are you talking about livelinks plugin?

Inside the live plugin, we have a sample player.

maybe you can use this player as a base to build your page https://github.com/WWBN/AVideo/tree/master/plugin/Live/sample-player

**Comment by palich91** [comment]
I'm talking about the LiveLinks plugin, I want the broadcasts to be shown on a separate page. How can I do that?
<a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/3/31/40f6a3e433abf9f6f1a6db2e090d4efc-full.jpg" border="0"/></a>

**Comment by DanielnetoDotCom** [comment]
Right now we do not have this done.

it needs to be developed.

you can hire us to develop it or you can try to do it by yourself.

**Comment by palich91** [comment]
What price?
