### ISSUE TITLE
mediarecorder webm files

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2777]
Hi,

is there a reason why videos created using mediarecorder in webm format when uploaded to youphptube show a duration of 00:00:00 ?

This happens to all my videos I create using mediarecorder.   

If i load them locally I see the correct metadata so suspect its something to do with ffmpeg

**Comment by DanielnetoDotCom** [comment]
00:00:00 means an encoding error.

check your encoder log file.

also try to run the FFMPEG command in the terminal and check the output.
