### ISSUE TITLE
Error playing from mobile device

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#2779]
The video does not play from the phone, it gives an error 
**Error:** _The media playback was aborted due to a corruption problem or because the media used_ features your browser did not support
(see screenshot)
<a href="https://radikalno.ru" target="_blank"><img src="https://cdn1.radikalno.ru/uploads/2020/3/30/f64acb33afbc4d20028aba5db0ba7af1-full.png" border="0"/></a>

**Comment by DanielnetoDotCom** [comment]
Is it only on Android?

works on iOS?

what type of video is that? MP4 or HLS?

**Comment by palich91** [comment]
HLS Video

**Comment by DanielnetoDotCom** [comment]
Did you setup this video as private?

I notice an error when using Chrome on Android.

it is not respecting the cookies. so it will not be possible to play any private HLS video on Android/Chrome until they release a fix.

**Comment by palich91** [comment]
My site is https://vicovi.ru/
Video Content: Free
Source: youtu.be
Enter: video
Views: 41
Format: HLS
What should I do to prevent this error?

**Comment by DanielnetoDotCom** [comment]
Please uncheck downloadProtection and try again.

![image](https://user-images.githubusercontent.com/18009293/77918753-ad722a80-7272-11ea-8277-bcd6e117fda3.png)

**Comment by DanielnetoDotCom** [comment]
Hi

If you want to update your VideoHLS plugin, enable the protection again and try again.

I just sent some updates to it. and now the protection may work on android devices.
