### ISSUE TITLE
SEO Link Error

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#2780]
SEO error: invalid links. When I import a video from YouTube through an encoder, the title text leaves a link, fix it.
Example:
Here is the link to the video: https://vicovi.ru/video/59/%D0%92%D0%B8%D0%B4%D0%B5%D0%BE-%D0%BA%D0%B0%D0%BA-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C-instantcms-%D0%BD%D0%B0-%D1%85%D0%BE%D1%81%D1%82%D0%B8%D0%BD%D0%B3?page=1&channelName=skriptcms
<a href="https://radikalno.ru" target="_blank"><img src="https://cdn1.radikalno.ru/uploads/2020/3/30/4062ec44a27a53e2f1f23e68182c1e73-full.jpg" border="0"/></a>

**Comment by akhilleusuggo** [comment]
And what do you want ?
Everything is correct

**Comment by palich91** [comment]
The link must be in English. of such a plan: https://vicovi.ru/video/videos-kak-install-instantcms-na-hosting
So that the Russian letters are replaced with English in the link

**Comment by akhilleusuggo** [comment]
Then replace it ... Just go on seo link and replace it .
I don't know if you're aware of what you're asking ... You're asking an intelligent script that understands russian and able to translate how it sound to english ... Magnificent xDDDDD

**Comment by palich91** [comment]
I can’t change links for every video. Links should not be like this: https://vicovi.ru/video/59/%D0%92%D0%B8%D0%B4%D0%B5%D0%BE-%D0%BA%D0% В0% D0% BA-% D1% 83% D1% 81% D1% 82% D0% B0% D0% BD% D0% BE% D0% B2% D0% B8% D1% 82% D1% 8C-instantcms-% D0% BD% D0% B0-% D1% 85% D0% BE% D1% 81% D1% 82% D0% B8% D0% BD% D0% B3? страница = 1 & ChannelName = skriptcms
You must make the title Russian and the link in English like this: https://vicovi.ru/video/videos-kak-install-instantcms-na-hosting

**Comment by palich91** [comment]
I need customization CNC

**Comment by DanielnetoDotCom** [comment]
What about this update?

Make sure you clear your browser cache and your browser load the new js file.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom just for feedback ( the update didn't change anything )

**Comment by DanielnetoDotCom** [comment]
It supposes for the new links it replaces the Russian characters correctly

**Comment by akhilleusuggo** [comment]
If you copy the link from browser , will not show normal . But if I right click ( on video ) + Copy video URL , then it works ( but shows the russian letters )

**Comment by akhilleusuggo** [comment]
Ok , quick feedback . You don't indicate the video title , the script will not change it automatically .
The second thing is that the translation is not right .
![image](https://user-images.githubusercontent.com/52116577/77924173-0ad69d80-72ac-11ea-8b94-3b39485352db.png)

**Comment by DanielnetoDotCom** [comment]
Ok, I got something but I have one question...

the characters below, or it does not make sense for me to replace or I guess it will break something on English characters.

can you please confirm that?

"В"=>"V"
   "Е"=>"E"
"К"=>"K"
   "М"=>"M"
"Р"=>"R",
   "С"=>"S",
"Т"=>"T",
"Х"=>"H",
"г"=>"g"
   "е"=>"e"
"о"=>"o"
"р"=>"r",
"х"=>"h"

**Comment by palich91** [comment]
"В" => "V"
"Е" => "E"
"К" => "K"
"М" => "M"
"Р" => "R",
"С" => "S",
"Т" => "T",
"Х" => "H",
"г" => "g"
"е" => "e"
"о" => "o"
"р" => "r" ,
"х" => "h"

**Comment by palich91** [comment]
You wrote it right

**Comment by DanielnetoDotCom** [comment]
Ok, but in english, if I replace "Р"=>"R" I will have a problem.

P is also an English letter

**Comment by DanielnetoDotCom** [comment]
Nevermind, I guess I am wrong, they are different chars В is NOT equal to B.

Looks the same, but they are different code

**Comment by DanielnetoDotCom** [comment]
I sent a new update, please try now

**Comment by DanielnetoDotCom** [comment]
Just send another fix

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/77934189-66a72380-72b8-11ea-83e4-46adaf4cb8de.png)
Not working as it should

**Comment by DanielnetoDotCom** [comment]
can you please paste here some Russian words and the expected results so I can test on my side

**Comment by palich91** [comment]
тест => test
установить на хостинг => ustanovit-na-hosting

**Comment by DanielnetoDotCom** [comment]
I guess it is correct now.

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/77938129-f4d1d880-72bd-11ea-9396-23ff1dac35c7.png)

It works !
