### ISSUE TITLE
how to insert a video into an encoder with a direct link

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#2781]
tell me how can I add a link to a video in the encoder, for example, here I have a video https://dlcache4.vibio.tv/80394bf710a9024d662710e4b77decd3/2729/2729006/output.lq.mp4 how can I insert it into the encoder

**Comment by DanielnetoDotCom** [comment]
First step is fix this 

![image](https://user-images.githubusercontent.com/18009293/77910591-c0cac900-7265-11ea-80a6-f8446f0d8b2d.png)

then we can see what we can do.

**Comment by palich91** [comment]
Sorry, I deleted that video. For example, here is a video: https://wmklik.ru/video.mp4

**Comment by DanielnetoDotCom** [comment]
I just paste the link in the import option and it works fine

![image](https://user-images.githubusercontent.com/18009293/77911691-9d088280-7267-11ea-8a5b-13674c2e756f.png)

**Comment by DanielnetoDotCom** [comment]
Here is your video https://demo.avideo.com/video/256/video
