### ISSUE TITLE
Localhost cannot Live Streaming

### ISSUE THREAD

**Issue by boom02456** [WWBN/AVideo#2783]
Hi all,

I cannot live stream in localhost

here's the log from /usr/local/nginx/logs/error.log:
2020/03/30 22:13:54 [info] 555#0: *30 client connected '172.17.0.1'
2020/03/30 22:13:54 [info] 555#0: *30 connect: app='live' args='p=f321d14cdeeb7cded7489f504fa8862b' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://localhost/live?p=f321d14cdeeb7cded7489f504fa8862b' tc_url='rtmp://localhost/live?p=f321d14cdeeb7cded7489f504fa8862b' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 172.17.0.1, server: 0.0.0.0:1935
2020/03/30 22:13:54 [info] 555#0: *30 createStream, client: 172.17.0.1, server: 0.0.0.0:1935
2020/03/30 22:13:54 [info] 555#0: *30 publish: name='5e81fe7fb782b' args='' type=live silent=0, client: 172.17.0.1, server: 0.0.0.0:1935
2020/03/30 22:13:54 [info] 555#0: *30 notify: publish 'localhost/YouPHPTube/plugin/Live/on_publish.php', client: 172.17.0.1, server: 0.0.0.0:1935
2020/03/30 22:13:54 [info] 555#0: *30 disconnect, client: 172.17.0.1, server: 0.0.0.0:1935
2020/03/30 22:13:54 [info] 555#0: *30 deleteStream, client: 172.17.0.1, server: 0.0.0.0:1935

OBS shows msg :
Could not access the specified channel or stream key, please double-check your stream key. If it is correct, there may be a problem connecting to the server. 

Any suggestions?

**Comment by akhilleusuggo** [comment]
past here the config nginx , and try to access to localhost:8080/stat

**Comment by boom02456** [comment]
localhost:8080/stat
RTMP | #clients | Video | Audio | In bytes | Out bytes | In bits/s | Out bits/s | State | Time
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Accepted: 3 | 1 KB | 0 KB | 0 Kb/s | 0 Kb/s |   | 9m 45s
live
live streams | 0


Config

 worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://localhost/YouPHPTube/plugin/Live/on_publish.php;
                            on_play http://localhost/YouPHPTube/plugin/Live/on_play.php;
                            on_record_done http://localhost/YouPHPTube/plugin/Live/on_record_done.php;


                        recorder video{
                            record all;
                            record_path /var/www/tmp;
                            record_notify on;
                            record_max_size 2048M;
                            #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
                            record_suffix -%d-%b-%y-%T.flv;
                        }


                    }
            }
    }
http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"
                    location / {
                            root   html;
                           index  index.html index.htm;
                    }
            }
    }

**Comment by boom02456** [comment]
sorry, here is the config 

worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://localhost/YouPHPTube/plugin/Live/on_publish.php;
                            on_play http://localhost/YouPHPTube/plugin/Live/on_play.php;
                            on_record_done http://localhost/YouPHPTube/plugin/Live/on_record_done.php;


                        recorder video{
                            record all;
                            record_path /var/www/tmp;
                            record_notify on;
                            record_max_size 2048M;
                            #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
                            record_suffix -%d-%b-%y-%T.flv;
                        }


                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }
            }
    }

**Comment by boom02456** [comment]
Sorry, here's the config

`worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://localhost/YouPHPTube/plugin/Live/on_publish.php;
                            on_play http://localhost/YouPHPTube/plugin/Live/on_play.php;
                            on_record_done http://localhost/YouPHPTube/plugin/Live/on_record_done.php;


                        recorder video{
                            record all;
                            record_path /var/www/tmp;
                            record_notify on;
                            record_max_size 2048M;
                            #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
                            record_suffix -%d-%b-%y-%T.flv;
                        }


                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }
            }
    }`

**Comment by akhilleusuggo** [comment]
and the plugin ?
Can you screen it ?

**Comment by boom02456** [comment]
Here's from plugins

{"button_title":"LIVE","server":"rtmp://localhost/live","playerServer":"http://localhost:8080/live","stats":"http://localhost:8080/stat","disableDVR":false,"disableGifThumbs":false,"useAadaptiveMode":false,"experimentalWebcam":false,"doNotShowLiveOnVideosList":false}

**Comment by DanielnetoDotCom** [comment]
is that accessible from your stream server ??


on_publish **http://localhost/YouPHPTube/plugin/Live/on_publish.php**;

can you please try to use `lynx http://localhost/YouPHPTube/plugin/Live/on_publish.php`

FYI Lynx is a customizable text-based web browser to use in the terminal, very good to test your connection.

**Comment by boom02456** [comment]
ow, it's not found. Could you please point me where to fix this?

Alert!: HTTP/1.0 404 Not Found

**Comment by boom02456** [comment]
I've checked in the Live folder, it's still there

/var/www/html/YouPHPTube/plugin/Live# ll
total 516
drwxr-xr-x 1 root     root       4096 Mar 31 11:25 ./
drwxr-xr-x 1 www-data www-data   4096 Mar 27 00:46 ../
-rw-r--r-- 1 root     root       4779 Mar 26 23:39 Live.php
drwxr-xr-x 2 root     root       4096 Mar 26 23:39 Objects/
-rw-r--r-- 1 root     root       2174 Mar 26 23:39 getImage.php
-rw-r--r-- 1 root     root      15285 Mar 26 23:39 index.php
drwxr-xr-x 2 root     root       4096 Mar 26 23:39 install/
-rw-r--r-- 1 root     root        169 Mar 26 23:39 on_connect.php
-rw-r--r-- 1 root     root        163 Mar 26 23:39 on_done.php
-rw-r--r-- 1 root     root        163 Mar 26 23:39 on_play.php
-rw-r--r-- 1 root     root        173 Mar 26 23:39 on_play_done.php
-rw-r--r-- 1 root     root       2066 Mar 26 23:39 on_publish.php
-rw-r--r-- 1 root     root        234 Mar 26 23:39 on_record_done.php
-rw-r--r-- 1 root     root        167 Mar 26 23:39 on_update.php
-rw-r--r-- 1 root     root       2287 Mar 26 23:39 report.php
drwxr-xr-x 3 root     root       4096 Mar 26 23:39 sample-player/
-rw-r--r-- 1 root     root     423193 Mar 26 23:39 sample-player.zip
-rw-r--r-- 1 root     root        803 Mar 26 23:39 saveLive.php
-rw-r--r-- 1 root     root       3508 Mar 26 23:39 stats.json.php
drwxr-xr-x 3 root     root       4096 Mar 26 23:39 videojs-dvr/
drwxr-xr-x 3 root     root       4096 Mar 26 23:39 view/

**Comment by boom02456** [comment]
I got it!
I gotta change path in nginx.conf.

But right now I got another problem that when live streaming, 

it's not show 'online'

it shows 'offline'

**Comment by boom02456** [comment]
RTMP	#clients	Video	Audio	In bytes	Out bytes	In bits/s	Out bits/s	State	Time
Accepted: 1	codec	bits/s	size	fps	codec	bits/s	freq	chan	2.35 MB	0 KB	0 Kb/s	0 Kb/s		3m 25s
live
live streams	1
5e82c1889588b	1	H264 High 3.1	0 Kb/s	1120x700	30	AAC LC	0 Kb/s	44100	2	2.35 MB	0 KB	0 Kb/s	0 Kb/s	active	8s

**Comment by akhilleusuggo** [comment]
does the stream work ? and showing offline status ?

**Comment by boom02456** [comment]
yeah, streaming is working now and I just configure forward port 8080 again. Right now it's all working fine, thanks guys :)
