### ISSUE TITLE
Video not showing after encoding

### ISSUE THREAD

**Issue by biosifaru** [WWBN/AVideo#2784]
I encoded like 20 videos using HLS the system shows them as finished but I can't find the videos on the platform. I can't find them anywhere on the platform

**Comment by akhilleusuggo** [comment]
logs ?

**Comment by biosifaru** [comment]
I don't where to get the logs. please help

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by biosifaru** [comment]
installation was done by Youphptube guys...
cd /var/www/html/AVideo-Encoder/videos/
-bash: cd: /var/www/html/AVideo-Encoder/videos/: No such file or directory

**Comment by akhilleusuggo** [comment]
then @DanielnetoDotCom will have to take a look 
Maybe you have it installed on cd /var/www/html/YouPHPTube/videos/

**Comment by DanielnetoDotCom** [comment]
Yes, check inside cd /var/www/html/YouPHPTube-Encoder/videos/

**Comment by biosifaru** [comment]
cd /var/www/html/YouPHPTube-Encoder/videos/
-bash: cd: /var/www/html/YouPHPTube-Encoder/videos/: No such file or directory

**Comment by biosifaru** [comment]
how should the log files look like? what extensions do they have?

**Comment by akhilleusuggo** [comment]
man , this are basics of linux .. You can't be server admin without this minimum knowledge .
`cd /var/www/html` # `cd` stands for ''Change Directory''
one of the /var/www/html type `ls` # ls stands for ''list'' . Basically shows what files/directories inside the directory you're in .

Show us what you see on html folder . You should see the AVideo directory or YouPHPTube

**Comment by biosifaru** [comment]
First of all I am not a server admin, that is why we paid for all you services... in the hope that I should work with application but not we the server itself. But it is very well noted your approach for paying customers.

I see the YouPHPTube, but I don't know how your log files should look like.
![image](https://user-images.githubusercontent.com/62892712/78014176-3c08a980-7350-11ea-8a6f-464d7fd7312d.png)

**Comment by akhilleusuggo** [comment]
go into videos directory or
cat videos/avideo.log

**Comment by biosifaru** [comment]
log file is attached
[avideo.log](https://github.com/WWBN/AVideo/files/4409681/avideo.log)

**Comment by akhilleusuggo** [comment]
@biosifaru maybe you should start from here 
```
BlackBlaze response ERROR Body: {
  "code": "bad_auth_token",
  "message": "",
  "status": 401
}
```
```
BlackBlaze response ERROR Body: {
  "code": "bad_auth_token",
  "message": "",
  "status": 401
```

**Comment by biosifaru** [comment]
Nop. Backblaze plug in is off

**Comment by akhilleusuggo** [comment]
Can you link the encoder logs ? because I don't see that you're receiving anything

**Comment by akhilleusuggo** [comment]
/var/www/html/YouPHPTube-Encoder/videos/avideo.log   ( should be )

**Comment by biosifaru** [comment]
in the Encoder folder I found this log file
[youphptube.log](https://github.com/WWBN/AVideo/files/4410193/youphptube.log)

**Comment by akhilleusuggo** [comment]
I have no idea what the html/css doing on your log file .
Did you updated ?

1- `cd /var/www/html/YouPHPTube`
2- `sudo git fetch --all && sudo git reset --hard origin/master `
3- `cd /var/www/html/YouPHPTube-Encoder`
4 - `sudo git fetch --all && sudo git reset --hard origin/master `

Read more about updates here : https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by biosifaru** [comment]
ok. website is updated:
![image](https://user-images.githubusercontent.com/62892712/78110959-9400e800-7404-11ea-9d8a-23485c9b83f1.png)

But for encoder I can't find where to update. 
My interface of encoder it looks different:
![image](https://user-images.githubusercontent.com/62892712/78111025-b430a700-7404-11ea-9997-0b5cb79ca110.png)

**Comment by akhilleusuggo** [comment]
on the encoder you need to log as admin .

**Comment by biosifaru** [comment]
can i reset the password for the admin for the encoder?

**Comment by akhilleusuggo** [comment]
I don't know how you manage the DB , but if you're using phpmyadmin , you need to give to your user ( the one you use ) , a value 1 ( to make it be admin )

I don't know if there's anyway to reset admin password for encoder .
@DanielnetoDotCom if he installed the script for you , he may remember the admin password .

**Comment by DanielnetoDotCom** [comment]
@biosifaru Once you update. please make sure you update your paid plugins as well

**Comment by DanielnetoDotCom** [comment]
You can do this yo reset your password https://github.com/WWBN/AVideo/wiki/Reset-a-Password

**Comment by biosifaru** [comment]
again... the password I need to reset is for admin at the encoder, not the main user.

**Comment by biosifaru** [comment]
@DanielnetoDotCom you said to update the encoder, but my interface for encoder looks different than what you suggested. Then your colleagues said that I need to be admin on encoder to be able to update... but I have no admin username from you for this encoder. IF you send just random information it will not solve the issue, only gets me frustrated and makes me feel sorry that I wasted a lot of money on your solution and get a very bad support in return...

**Comment by DanielnetoDotCom** [comment]
The encoder credentials comes from the streamer.

So if you fix the streamer you should be able to login in the encoder .

If you want to make some specific user a encoder admin and you do not have admin access anymore. You must change it directly in the database

**Comment by biosifaru** [comment]
ok... I have no idea, your friend is saying different... but whatever. I will try it now.
![image](https://user-images.githubusercontent.com/62892712/78137175-890e7d80-742d-11ea-9b9f-ee1c806103de.png)

**Comment by DanielnetoDotCom** [comment]
The encoder admin is different then the streamer admin

Login in your MySQL and select the encoder database 
check your streamers table on your database.
check your column isAdmin, and make it = 1

After that log off an login again in your encoder

**Comment by biosifaru** [comment]
@DanielnetoDotCom I don't really care to make admin... but your suggestion will help solve the problem? or?

**Comment by DanielnetoDotCom** [comment]
You point many problems here in this thread .

My suggest it to let you be encoder admin.

After that i suggest you to update your streamer and encoder 

Then if the problem persist we will check the logs

**Comment by biosifaru** [comment]
ok... whatever, lets see

**Comment by biosifaru** [comment]
still not working. I've updated all that you requested. Videos still don't show at all... system say it is no videos.
New log file:
[avideo.log](https://github.com/WWBN/AVideo/files/4415907/avideo.log)

**Comment by akhilleusuggo** [comment]
database problems you having 
[sqlDAL::writeSql] Prepare failed: (1054) Unknown column 'sites_id' in 'field list'<br>

**Comment by biosifaru** [comment]
Ok. And how to solve it?

**Comment by DanielnetoDotCom** [comment]
@biosifaru looks like you skip updates.

check this https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform#rollback-the-update

**Comment by biosifaru** [comment]
Why do you mean?
Why do I to roll back....

**Comment by biosifaru** [comment]
I followed the upgrade steps you recommended. Now these are not ok..

**Comment by DanielnetoDotCom** [comment]
Are you sure you did not skip any?

sites_id is on version 7.3

BTW, when you paid was all delivery correctly and working. but for some reason, you decide to update or change something. that is why it is not working now.

If you want you can hire us for direct intervention in your server.

**Comment by DanielnetoDotCom** [comment]
did you pay for support??? where?

I guess you paid for installation in Apr 3, 2018 (2 years ago)

**Comment by biosifaru** [comment]
How much is it ?

**Comment by DanielnetoDotCom** [comment]
If you have a recent installation I will be happy to take a direct look into the server.

If you want to hire us to fix it for you please email me at developer@youphptube.com
