### ISSUE TITLE
adaptive stream

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2785]
Anyway to add an option for source stream ?
Usually it supports up to 3 resolution transcoded with ffmpeg , but I want to add a new array with ''source'' witch means without transcoding + the 720 , 480 , 360

**Comment by DanielnetoDotCom** [comment]
Humm, do you mean on encoder?

**Comment by akhilleusuggo** [comment]
On encoder could end up badly ( size of the source/original video size )
I'm talking only for adaptive mode ( for live streaming )
Giving you an example from twitch . 
![image](https://user-images.githubusercontent.com/52116577/77928567-40ca5080-72b1-11ea-9bd8-49c03fe63e26.png)

Does transcode the video , but leaves you with the option to watch the original stream quality ( without trancoding it ) , same quality/bitrate as the streamer has set it up on obs

**Comment by DanielnetoDotCom** [comment]
Ok, you are talking about the Nginx configuration.

did you make those changes already in your nginx.conf?

**Comment by akhilleusuggo** [comment]
No , because none is needed .
What I need is the hls option ( on the video player ) on the plugin section 

This is the default one .
But my question is , from where does it pull the stream to display on the video player ?

```
#application adaptive {
                    #live on;
                    #hls on;

                    #hls_path /HLS/live;
                    #hls_nested on;

                    #allow play all;
                    #allow publish 127.0.0.1;
                    #deny publish all;

                    #hls_variant _low BANDWIDTH=400000;
                    #hls_variant _mid BANDWIDTH=2100000;
                    #hls_variant _hi  BANDWIDTH=4200000;
```

On the ffmpeg part : `$name_hi;` `$name_mid;` `$name_low;`
Need one more `$name_source;`  without transcoding .
With source I mean like if you have disabled the adaptive stream mode .
So what I'm asking is Adaptive stream mode + non adaptive stream mode .

**Comment by JoshWho** [comment]
it pulls from the stream path by nginx

You need HLS on to do this. Firefox and Safari will not be able to view source stream anymore and looks for a Low Res and High res by default. Soon they r forcing those to be the only ones on google chrome.

As long as you have a High and Low set you should be able to also make a option for direct stream as well but u need the other 2 in place or it will just show Network error to people on other browsers.

**Comment by DanielnetoDotCom** [comment]
I guess a modification on nginx.conf is required. otherwise what will be the source path for the m3u8 file?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 
The non transocoded one . /live/id/index.m3u8
