### ISSUE TITLE
Erros ao rodar script database.sql

### ISSUE THREAD

**Issue by mauriciodavel** [WWBN/AVideo#2788]
Tentei rodar a instalação com a interface web, mas o mesmo apresentava erro de criação do banco, mais precisamente na tabela vídeos. Como não tinha como saber o motivo do erro.
Desta forma, optei por rodar o script manualmente utilizando o MySQL WorkBench executando bloco por bloco separadamente e assim pude perceber que ele apresenta um alerta ao criar a tabela videos:

0 row(s) affected, 1 warning(s): 1071 Specified key was too long; max key length is 767 bytes	0.047 sec

Ele cria a tabela, mas com esta exclamação.
No final do script, quando executo este bloco:

ALTER TABLE `videos` 
ADD INDEX `videos_status_index` (`status` ASC),
ADD INDEX `is_suggested_index` (`isSuggested` ASC),
ADD INDEX `views_count_index` (`views_count` ASC),
ADD INDEX `filename_index` (`filename` ASC);

Novamente referente à tabela "videos" apresenta este erro:
Error code: 1071. Specified key was too long; max key length is 767 bytes	0.047 sec

Poderiam me ajudar a resolver?

**Comment by akhilleusuggo** [comment]
are you using utf8mb4 ?

**Comment by mauriciodavel** [comment]
Olá akhilleusuggo,

Sim, estou usando este mesmo. Seria este o problema?

**Comment by akhilleusuggo** [comment]
@mauriciodavel 
UTF8 can have a maximum of 255 on VARCHAR
UTF8MB4 on innobd can have a maximum of 191 on VARCHAR

utf8 uses 3 bytes per char (3 255 = 765)
utf8mb4 uses 4 bytes per char (4 191 = 764)

**Comment by akhilleusuggo** [comment]
take this as an example what you have to do to fix this 
![image](https://user-images.githubusercontent.com/52116577/77986542-04820900-7320-11ea-9afe-269b15ba445e.png)

**Comment by mauriciodavel** [comment]
Obrigado !!
Resolveu este problema.
O banco agora está OK e a instalação foi efetuada.

Estou com outro agora, mas vou abrir outro referente à este.
