### ISSUE TITLE
How to update the encoder?

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#2789]
Tell me how to update Encoder? Have an instruction?

**Comment by DanielnetoDotCom** [comment]
Hi

To update the encoder you do at the same way you do for the streamer.

Follow this instructions https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

Just make sure you will be inside the encoder directory.

FYI usually the encoder directory location is 
     /var/www/html/YouPHPTube/Encoder/

**Comment by palich91** [comment]
failed to update, you can write commands

**Comment by DanielnetoDotCom** [comment]
Please screenshot the error and the command

**Comment by DanielnetoDotCom** [comment]
Please screenshot the error and the command

**Comment by palich91** [comment]
Sorry, I made a mistake when typing a command
