### ISSUE TITLE
Email confirmation to allow the user to log in

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#2790]
hello 
i have a problem with email confirmation
I have many user registrations through facebook and twitter, but a large percentage 95% cant not have confirm to be able to connect
and when registered with the normal registerings of the site form can makes confirmation and can be connected!
my question is this:
how do i know if the system has sent the email to confirm who has registered via facebook or twitter??

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
If you are using the latest version. we do not require confirmation anymore from those who log in using social networks.

**Comment by wetubeclub** [comment]
Hello Daniel and thank you for your response!
i have version 8.6 of the software
because the site is not visible to non-users and in order to login you need to confirm the email
Question:
![verification](https://user-images.githubusercontent.com/60543030/78024563-df5dbc80-7358-11ea-8200-4bad13336672.jpg)

if you registered for example with facebook
you can login properly or you must confirm the email first??

Thank you again
Ilias

**Comment by DanielnetoDotCom** [comment]
If I signup after you are in version 8.6 I do not need to verify.

but if someone signup before this version, it is probably requiring the verification.

**Comment by wetubeclub** [comment]
Ok! Thank you Daniel
Ilias
