### ISSUE TITLE
HLS plugin

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2791]
When playing a video the default quality is ''auto'' . When selecting a quality ( for example 1080p ) , the viewers has to wait until the playlist downloaded finishes to refresh the playlist .

In the other hand , I can force refresh playlist by selecting 240p then again to 1080p ( this makes the change immediate )

Can you add force refresh playlist when ''auto '' is the default one ?

**Comment by DanielnetoDotCom** [comment]
this HLS feature is related to the videojs lib. I do not have the control to make those changes.

**Comment by mostafaaalii** [comment]
hello sir can i contact with you?
