### ISSUE TITLE
Incorrect encoding in the mail from the site

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#2792]
Unreadable mail arrives from the site

<a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/4/1/1ccd8aedb8a41778eda85b6ce2280fac-full.jpg" border="0"/></a>

**Comment by akhilleusuggo** [comment]
this is usually a DB miss configuration . You need utf8 or utf8mb4 ( in case you have innodb )

**Comment by palich91** [comment]
I used phpmyadmin on all my sites, but on this site I do not have phpmyadmin, and I don’t know how to change the encoding. Tell me what to do

**Comment by akhilleusuggo** [comment]
@palich91 do you mean with command lines ?

**Comment by palich91** [comment]
Yes

**Comment by akhilleusuggo** [comment]
ща погоди у тебя проблема только на эмайл ? А когда видос на сайта , такого нету ? Типа титул видос , его норм видно ( на русском буквах ) ?

**Comment by palich91** [comment]
An error only with sending mail to mail.ru, on gmail comes without errors

**Comment by akhilleusuggo** [comment]
I don't know then . I misunderstood your problem problem's description

**Comment by DanielnetoDotCom** [comment]
If it works fine in gmail, I guess the problem is on mail.ru

**Comment by palich91** [comment]
No, this is an encoding problem

**Comment by DanielnetoDotCom** [comment]
Are you talking about email?

Or are you talking about encoder?

FYI encoder does not send any email , only streamer does it

**Comment by palich91** [comment]
I'm talking about the Notifications plugin

**Comment by DanielnetoDotCom** [comment]
This post confuses me

![image](https://user-images.githubusercontent.com/18009293/78143822-243f2d00-7405-11ea-82ef-986c9752ff28.png)

But as long as it is working on Gmail, I cannot reproduce it. and I can only guess the problem is in your webmail

**Comment by palich91** [comment]
I found a solution for embedding videos on other sites, @DanielnetoDotCom, I ask you to add this to AVideo.
Solution (example):
`<object width="640" height="360"><param name="movie" value="https://vicovi.ru/videoEmbed/53/Как-скопировать-лендинг-lending-page?channelName=skriptcms"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="https://demo.clipbucket.com/enterprise/player/embed_player.php?vid=1840" allowscriptaccess="always" allowfullscreen="true" width="300" height="250"></embed></object>`

This is how it will look:
<a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/4/2/f9c756cb8e1009754755c05fcb4d498e-full.jpg" border="0"/></a>

I suggest doing it this way:
<a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/4/2/716c4fdeccb74454a353a374e9826188-full.jpg" border="0"/></a>

**Comment by palich91** [comment]
I need a decoded Notifications plugin to deal with the problem

**Comment by palich91** [comment]
This situation is due to the fact that when encoding a letter is used
standard iso-8859-1, which contains almost all European
non-standard characters (i.e. does not contain Cyrillic) while
The information in the letter is written in Cyrillic.

**Comment by palich91** [comment]
> This situation is due to the fact that when encoding a letter is used
> standard iso-8859-1, which contains almost all European
> non-standard characters (i.e. does not contain Cyrillic) while
> The information in the letter is written in Cyrillic.

what can you answer?

**Comment by DanielnetoDotCom** [comment]
I just sent an update for the send email function, where you can try one of those options.

![image](https://user-images.githubusercontent.com/18009293/78568020-e6247d80-77f7-11ea-8c5f-f5686f6a3a69.png)

**Comment by palich91** [comment]
If I choose utf8 Encode or utf8 Decode, then the title text and description will go bad
<a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/4/7/fb1481fedf6e96ce54f36037c2756585-full.jpg" border="0"/></a>

**Comment by DanielnetoDotCom** [comment]
but does it fixes the email?

if yes, what option fixes the email?

**Comment by palich91** [comment]
does not correct email
both are not displayed correctly
<a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/4/7/78a07a5fb252e5d82cc4d913c48a4472-full.jpg" border="0"/></a>

**Comment by DanielnetoDotCom** [comment]
and without check anything it is also going wrong encoded?

if yes, I am out of options. the error is probably in your email client.

**Comment by palich91** [comment]
That's what they answered with mail.ru support:

> This situation is due to the fact that when encoding a letter is used
> standard iso-8859-1, which contains almost all European
> non-standard characters (i.e. does not contain Cyrillic) while
> The information in the letter is written in Cyrillic.

**Comment by DanielnetoDotCom** [comment]
Please update and try again, I follow this solution https://stackoverflow.com/questions/29093727/phpmailer-cyrillic-charset-trouble
