### ISSUE TITLE
Duplicate user emails

### ISSUE THREAD

**Issue by MrWeb** [WWBN/AVideo#2793]
Hi, I noticed people subscribe to my app more than once because they either forget they are registered or think they are not and the system allows duplicated emails:

```
SELECT 
    email, 
    COUNT(email)
FROM
    users
GROUP BY email
HAVING COUNT(email) > 1;
```

Result:

![Screenshot 2020-04-01 at 12 12 19](https://user-images.githubusercontent.com/4120466/78125997-21970480-7412-11ea-9d7d-e108ecb44c24.png)

As you can see there are 14 subscription where people registered 2 or 4 times (and some I already manually deleted them).

How do we prevent this?

**Comment by DanielnetoDotCom** [comment]
I guess you are looking into the database.

the script takes care to not count it twice

**Comment by MrWeb** [comment]
Nope, I probably was not clear.
The image above is my users table. There are people who signup with the SAME email more than one time.

The AVideo system checks for a unique **username** BUT NOT a *unique* email.

I think it should check for a **unique email** as well so people cannot register if they already registered.

Example:

![Screenshot 2020-04-01 at 14 10 42](https://user-images.githubusercontent.com/4120466/78135757-aee25500-7422-11ea-8693-7aaa5d0500b0.png)

This 2 users are the same person, with the same mail. But perhaps they did not remember the username so they registered again with a different username **but same email**!

**Comment by akhilleusuggo** [comment]
I agree with , this option should be added . Same email should be used only once .
And I'm not talking about 'Force E-mail to be Login'

**Comment by MrWeb** [comment]
Ok great! Do we have a time estimate for this?

**Comment by DanielnetoDotCom** [comment]
Hoo, I see.

what people do they force the username to be the email. so it guarantees they will be unique

![image](https://user-images.githubusercontent.com/18009293/78277869-8ffbc580-74eb-11ea-9de0-6266cc3d40a5.png)

**Comment by MrWeb** [comment]
Perfect thank you very much!
