### ISSUE TITLE
Route not found

### ISSUE THREAD

**Issue by praneethpj** [WWBN/AVideo#2795]
Hi,
I installed successfully AVideo on the shared hosting package. But the following error occurs while I open a video file. I have used the embed video URL in youtube.

Site URL : http://bluelandnature.com/video/2/full-day-of-eating-contest-prep-edition-|-antoine-vaillant-|-3933-calories?page=1&channelName=5e84aca65fa01

Fatal error: Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/video/2/full-day-of-eating-contest-prep-edition-|-antoine-vaillant-|-3933-calories/" in /home4/sanjeewa/public_html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300 Stack trace: #0 /home4/sanjeewa/public_html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest() #1 /home4/sanjeewa/public_html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start() #2 {main} thrown in /home4/sanjeewa/public_html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300

This is my .htaccess file,

 
```
<ifModule mod_expires.c>
    ExpiresActive On
    ExpiresDefault "access plus 1 seconds"
    ExpiresByType text/html "access plus 1 seconds"
    ExpiresByType image/gif "access plus 2592000 seconds"
    ExpiresByType image/jpeg "access plus 2592000 seconds"
    ExpiresByType image/png "access plus 2592000 seconds"
    ExpiresByType text/css "access plus 604800 seconds"
    ExpiresByType text/javascript "access plus 216000 seconds"
    ExpiresByType application/x-javascript "access plus 216000 seconds"
</ifModule>
# END Expires
# BEGIN Caching
<ifModule mod_headers.c>
    Header set Access-Control-Allow-Origin: *
    <filesMatch "\.(ico|pdf|flv|jpg|jpeg|png|gif|swf)$">
        Header set Cache-Control "max-age=2592000, public"
    </filesMatch>
    <filesMatch "\.(css)$">
        Header set Cache-Control "max-age=604800, public"
    </filesMatch>
    <filesMatch "\.(js)$">
        Header set Cache-Control "max-age=216000, private"
    </filesMatch>
    <filesMatch "\.(xml|txt)$">
        Header set Cache-Control "max-age=216000, public, must-revalidate"
    </filesMatch>
    <filesMatch "\.(html|htm|php)$">
        Header set Cache-Control "max-age=1, private, must-revalidate"
    </filesMatch>
</ifModule>
# END Caching
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ index.php [L,QSA]

# from official example
# RewriteEngine on
# RewriteCond %{SCRIPT_FILENAME} !-f
# RewriteCond %{SCRIPT_FILENAME} !-d
# RewriteCond %{SCRIPT_FILENAME} !-l
# RewriteRule ^(.*)$ index.php/$1
</IfModule>
    <IfModule mod_xsendfile.c>
       RewriteRule    ^videos/([A-Za-z0-9-_.]+)$ view/xsendfile.php?file=$1    [QSA]
</IfModule>

<Files routes.php>
Order Allow,Deny
Deny from all
</Files>
```

Thank you.

**Comment by DanielnetoDotCom** [comment]
are you sure your mod-rewrite is installed?
