### ISSUE TITLE
I Can't See what i need to do Please help

### ISSUE THREAD

**Issue by TakeAchance365** [WWBN/AVideo#2796]
![Haleyville Live 4_1_2020 1_28_44 PM](https://user-images.githubusercontent.com/45086315/78173292-19909200-741d-11ea-9e46-f398c4e57832.png)

I don't know how to fix this it's hard to read what i need to do please fix and tell me what i need to do if you can please

**Comment by TakeAchance365** [comment]
I still can’t really figure this out

**Comment by akhilleusuggo** [comment]
`sudo chmod 777 /var/www/html/YouPHPTube/objects/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer`

You're welcome
You can always inspect XHR for error ( dev tools )

**Comment by TakeAchance365** [comment]
I think my suggestion would be for future updates for the Avideo platform To make the pop-ups bigger To make the pop-ups bigger Or a button to copy the code that you need to get it to work

**Comment by TakeAchance365** [comment]
But since it’s late I will try that code tomorrow see see if I don’t run into any other problems before I close this Issue

**Comment by akhilleusuggo** [comment]
If you double click or just select with the mouse to the bottom it will be selected 
But I agree with you

**Comment by TakeAchance365** [comment]
I did that originally and the only copy part of it Which is what got me frustrated originally but now I got  it fixed thanks to you for giving me the code
