### ISSUE TITLE
Verification mail error

### ISSUE THREAD

**Issue by sharad22gupta** [WWBN/AVideo#2797]
when in my account I click on verify email, it shows processing for 10-15 mins and then shows
congratulation  verification mail sent but I don't receive any email, I checked avideo logs it says 

[01-Apr-2020 21:07:40 Europe/Berlin] Sending SMTP Email
[01-Apr-2020 21:12:40 Europe/Berlin] PHP Fatal error:  Maximum execution time of 120 seconds exceeded in C:\xampp\htdocs\new\AVideo\objects\PHPMailer\src\SMTP.php on line 1169
[01-Apr-2020 21:12:40 Europe/Berlin] PHP Fatal error:  Maximum execution time of 10 seconds exceeded in C:\xampp\htdocs\new\AVideo\objects\functions.php on line 2570

can you help me with this? Also at the time of account creation, no verification mail is sent.

**Comment by DanielnetoDotCom** [comment]
you probably have a misconfiguration in your SMTP, the streamer server never reaches your email server

**Comment by sharad22gupta** [comment]
These are my settings, it keeps processing for 5 mins and then says mail sent. but i dont receive any email.
![Annotation 2020-04-04 023822](https://user-images.githubusercontent.com/15939963/78405127-722e7d80-761d-11ea-81c4-300012f3a383.png)

**Comment by DanielnetoDotCom** [comment]
check if you server can reach the SMTP host on port 465.

make a `telnet smtp.gmail.com 465` and paste the output here

**Comment by sharad22gupta** [comment]
i receive a blank screen, i think that means the connection is successful.

**Comment by akhilleusuggo** [comment]
@sharad22gupta make sure that on your gmail , you allow less secure application ( on gmail settings )

**Comment by sharad22gupta** [comment]
Allow less secure feature is turned on and the settings are as mentioned, I have shared the error above @akhilleusuggo

**Comment by DanielnetoDotCom** [comment]
@sharad22gupta I guess your server is blocked to access the Gmail SMTP. probably the firewall.

**Comment by sharad22gupta** [comment]
@DanielnetoDotCom  so how do I check it and correct it, thankyou forthereply

**Comment by DanielnetoDotCom** [comment]
try a telnet command in the SMTP port

BTW in your configuration instead SSL try the tls port 587

**Comment by akhilleusuggo** [comment]
I tried gmail and works on tls 587 port
SSL did not work as expected .

**Comment by sharad22gupta** [comment]
i tried tls 587 ,it results in endless processing and when i did telnet smtp.gmail.com 587, i got this response : 220 smtp.gmail.com ESMTP a75sm2178480pje.31 - gsmtp  
and in avideo.log file i got this error  
: [07-Apr-2020 20:26:40 Europe/Berlin] Sending SMTP Email
[07-Apr-2020 20:26:51 Europe/Berlin] sendEmail: Message could not be sent (SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting)
@akhilleusuggo @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
please screenshot your SMTP configuration how it is now.

**Comment by sharad22gupta** [comment]
@DanielnetoDotCom  here it is 

![Annotation 2020-04-08 003123](https://user-images.githubusercontent.com/15939963/78708830-5c2c0000-7930-11ea-87bf-3b6d924088cc.png)

**Comment by DanielnetoDotCom** [comment]
All seems correct for me.

if you could make telnet from the same stream server, I really have no idea

**Comment by sharad22gupta** [comment]
is there any alternate solution for this. @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Maybe you can try to install the sendmail

**Comment by sharad22gupta** [comment]
do you have any tutorial for that, it would be really helpful. @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Sorry, I don't, I always use STMP for myself.

**Comment by sharad22gupta** [comment]
@DanielnetoDotCom  i have installed postfix on my ubuntu server and checked it, its working now how do i connect it with this platform.

**Comment by DanielnetoDotCom** [comment]
Just disable the smtp in the site configuration menu , then it will try to use the sendmail

**Comment by akhilleusuggo** [comment]
@sharad22gupta things to take in count .
Make sure your providers are not blocking the ports
On gmail , allowing less secure apps is not the only thing you need to do , but also confirm that your '' server '' , is the one using your SMTP . 
I have this problem the first time I used it , until I confirmed '' it was me ''
![image](https://user-images.githubusercontent.com/52116577/78791155-2df20300-79b8-11ea-8ba4-6ee678ef20e8.png)

Otherwise google will block it . It may take 5-15mn , then it should work .

**Comment by sharad22gupta** [comment]
postfix is working fine, thank you for the help. @DanielnetoDotCom @akhilleusuggo
