### ISSUE TITLE
Error - The media could not be loaded, either because the server or network failed or because the format is not supported

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#2798]
Hi Guys..

Not sure what happened here but it uploads the videos, then says sthe above when you open the video.

please advise.
Thanks

**Comment by DanielnetoDotCom** [comment]
Hi, looks like you had a problem with the video process.

how did you submit the video encoder or direct upload?

can you please share here a link with the video failing?

**Comment by kollossus55** [comment]
Hi

There was no problems uploading the video, either a file from my PC or from youtube..

It's only when you play the video, that the error
Occurs.. would I need to reload encoder.



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by DanielnetoDotCom** [comment]
Ok, so you are using the encoder.

for this, please share your encoder log file.

please check here how to do https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by kollossus55** [comment]
[avideo-video.log](https://github.com/WWBN/AVideo/files/4422340/avideo-video.log)
[avideo-encoder.log](https://github.com/WWBN/AVideo/files/4422342/avideo-encoder.log)

**Comment by kollossus55** [comment]
I have uploaded the log files...

**Comment by DanielnetoDotCom** [comment]
I could not find any error in your encoder

but I found many errors in your streamer.

basically you have the FTP_Storage misconfigured

please screenshot your FTP_Storage parameters, but make sure you hide the password in the image you will paste here.

**Comment by kollossus55** [comment]
Hi

Will Check this out..In the meantime, I will disable it..

Thanks
________________________________
