### ISSUE TITLE
Theme setting and Cover preview

### ISSUE THREAD

**Issue by myCherokee-24** [WWBN/AVideo#2799]
Hello,
I am currently dealing with AVideo. Everything works so far, but I would like to make some adjustments.
Instead of the video clip screenshot - a DVD cover for the film should be displayed.
The film clip screenshot is created automatically, but I would only want to use covers.
The homepage https://www.filmboxlive.com/de serves as a template, it should be the same software (AVideo) with Netflix and then adapted ...
Does anyone have any tips on where to start ...
My homepage runs as a test at filmways24.com - and is still far from the template.
Many thanks for your help!
regards
Thomas

**Comment by DanielnetoDotCom** [comment]
Hi, I do not think https://www.filmboxlive.com/ is our software.

but to start you may want to use portrait images

Make sure you uncheck this 
![image](https://user-images.githubusercontent.com/18009293/78284820-52e90080-74f6-11ea-91ff-eb1f40f56784.png)

and make sure you upload the portrait images when you edit the videos

![image](https://user-images.githubusercontent.com/18009293/78284905-70b66580-74f6-11ea-9125-90711fc2f0ca.png)

right now I can provide you 2 samples of a flix site

1. https://flix.avideo.com/
2. https://flixhouse.com/

**Comment by myCherokee-24** [comment]
Hello,

it's possibel to switch the Theme Netflix to look like https://flix.avideo.com/

Best regards,
Thomas

**Comment by DanielnetoDotCom** [comment]
Yes, please check this in the admin menu

![image](https://user-images.githubusercontent.com/18009293/78565064-becbb180-77f3-11ea-83f7-75aca8d1d26e.png)

**Comment by Cherokee-24** [comment]
Hello,
now i change the setting. First time it's run with Cover preview.
A few days later, it does't work.
Only 2 demo videos, to show withe a Cover...
I hope, everyone have the same problem, a we can fix it together.
Please look for www.filmways24.com - to know what i meen.
Best regards,
Thomas
