### ISSUE TITLE
Update from version 5.8 to current version (8.6) caused issues with loading

### ISSUE THREAD

**Issue by siniztr** [WWBN/AVideo#2800]
After neglecting a site that I manage for a little while, I ran through quite a few updates on the youPHPtube installation on a live server. I was successful with the updates, however certain pages doesn't load (Live for example) and was getting a lot of errors with the apache2 mod mod_pagespeed not being able to access certain css or js files. I had to disable the mod and reload apache2 and php-fpm as the loading of the Live page literally freezes the website. 

I am no longer getting any errors in the apache2 error.log, but clicking on Live still causes the site to freeze up the PHP and apache2. If I click on the Live button, and then stop the page loading and try to go somewhere else, or if someone else is browsing the page at that moment, the site freezes and takes very long to load. At last measurement was 3 mins before I was forced to restart apache and php-fpm again.

Any advice?

**Comment by siniztr** [comment]
Because the live and the live-chat was causing the issues, I currently have them disabled. But the issue so far seems to revolve around the Live stream.

**Comment by siniztr** [comment]
Ok new update, Even on a new site using a different domain with a clean install, if I activate the Live and the Live-chat, and then click on Live, it causes the server to freeze.

**Comment by akhilleusuggo** [comment]
to upgrade you need to upgrade to all versions and do not skip any version .
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by siniztr** [comment]
I was able to successfully resolve the issue at hand. It was being caused by the live app not being able to connect to the RTMP server, due to the website being https, and the rtmp server being http. Closing the ticket.
