### ISSUE TITLE
Improve: direct download

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#2801]
I propose to implement in direct download, download not only from the local computer, but also by direct link from the Internet
Screenshot:
<a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/4/3/dbb7703f7bd8efd13f00442663bee084-full.jpg" border="0"/></a>

**Comment by akhilleusuggo** [comment]
you can do other thing ( I did this on my home server )
Go to your encoder . Create a new array ( yours )
If not , modify one line on the encoder . 
![image](https://user-images.githubusercontent.com/52116577/78333505-9abd6580-7592-11ea-80e6-8005167a3354.png)

This basically means , no transcoding will happens

**Comment by palich91** [comment]
@akhilleusuggo you can say your mail, I would like to talk with you

**Comment by akhilleusuggo** [comment]
same as my nickname , with @gmail.com

**Comment by palich91** [comment]
> Предлагаю реализовать в прямой загрузке, скачать не только с локального компьютера, но и по прямой ссылке из интернета.
> Скриншот:
> [![](https://camo.githubusercontent.com/a690498b345df2b1c55b326ff0c498ac54283dbb/68747470733a2f2f63646e312e73617665706963652e72752f75706c6f6164732f323032302f342f332f64626237373033663762643865666431336630303434323636336265653038342d66756c6c2e6a7067)](https://savepice.ru)

I still suggest doing it
