### ISSUE TITLE
youtube api plugim error

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#2803]
YouTubeAPI Error
The developer_key10 is empty and we could not use

there is no  10???

why am i get this error i filled out all api keys 

why is is it asking for _key 10 when there isnt one?

**Comment by DanielnetoDotCom** [comment]
It may happen because your key is not valid anymore. 

maybe exceed the limits.

that is why I put up to 10 keys. when one exceeds it will try another one.

**Comment by freedomshare** [comment]
ok i fixed it but after i embeded one time  can no longclick the search button..

**Comment by DanielnetoDotCom** [comment]
Also, I just sent you an update, that will give you some clue what is happening with your keys on your log files.

**Comment by DanielnetoDotCom** [comment]
I do not understand what you are saying about the embed and click

**Comment by freedomshare** [comment]
when i use bulk embed  i type the name of video im looking for and i cant run the seach then seach button is not click able

**Comment by freedomshare** [comment]
![image](https://user-images.githubusercontent.com/60738260/78360581-039de100-7585-11ea-9472-e42295641476.png)


cant click it as if the link is broken

**Comment by freedomshare** [comment]
it worked 2 times then stoppped i cleared everything and still dont work

**Comment by freedomshare** [comment]
i think it time to get rid of server my logo not working html set dose not work either youapi not working :( im at a loss with all the issues cant aford to pay for support as corna has me jobless :(

**Comment by DanielnetoDotCom** [comment]
I guess is the same credential problem limits.

![image](https://user-images.githubusercontent.com/18009293/78360999-0a7d2180-758e-11ea-866b-33c627658b0b.png)

**Comment by freedomshare** [comment]
that didnt fix it i change the api there still cant click

**Comment by freedomshare** [comment]
i also still have this issue

and this still happens 
![image](https://user-images.githubusercontent.com/60738260/78361974-46f94f00-7587-11ea-9605-f8df173591d5.png)

![image](https://user-images.githubusercontent.com/60738260/78362026-5d070f80-7587-11ea-93d9-9c36bff50334.png)
there also nothing in there to break it like this this happenw hen i updated to the new version 8.6 
only way i found to fix it is to delete eveything from it and save but i can only find these videos when they land on home page

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Can you add multiple API key for bulk embed like you've done with YouTube API upload ?

**Comment by freedomshare** [comment]
i have also tryed from my webserver to click  bulk embed and it will not work at all

**Comment by freedomshare** [comment]
please try it from you end freedomshare.net i have turn the admin only off

**Comment by freedomshare** [comment]
i fixed it.
