### ISSUE TITLE
Issues with RSS

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#2804]
Why do you need MRSS? to use where?

_Originally posted by @DanielnetoDotCom in https://github.com/WWBN/AVideo/issues/2768#issuecomment-605935867_

I'd posted previously that I needed help with the MRSS feed.  But, I'm also having problem with the RSS feed.  When I try to import the RSS feed into a podcast it's only capturing one or two of my videos.  I have both videos and audios, mp3, mp4, and mov files.  It's brought over both a video and an audio both mp4.  I can see the feed everything looks to be the same, I'm stumped as to why only these two posts come over and the rest don't.

**Comment by JoshWho** [comment]
I have no problems with the rss feed from channels. TuneIn pulls in my rss feed no problem and makes it a podcast https://tunein.com/podcasts/News--Politics-Podcasts/JoshWho-SeekingTheTruth-Podcast-p1298670/

So does a few others

https://www.podbean.com/podcast-detail/p3r5f-aa0f9/RSS-SeekingTheTruth-Podcast
https://player.fm/series/joshwho-tv-news

**Comment by heiress01** [comment]
> I have no problems with the rss feed from channels. TuneIn pulls in my rss feed no problem and makes it a podcast https://tunein.com/podcasts/News--Politics-Podcasts/JoshWho-SeekingTheTruth-Podcast-p1298670/
> 
> So does a few others
> 
> https://www.podbean.com/podcast-detail/p3r5f-aa0f9/RSS-SeekingTheTruth-Podcast
> https://player.fm/series/joshwho-tv-news

Does your channel feed look like this?  yourdomain.com/channel/your+channel+name/feed
