### ISSUE TITLE
User_controll plugin

### ISSUE THREAD

**Issue by franranchito** [WWBN/AVideo#2805]
I'm trying to use user_controll plugin, when I try to ban an IP, I get this error:

![imagen](https://user-images.githubusercontent.com/19801224/78387215-3bd20d80-75df-11ea-806a-9541bede9404.png)

which output this in the avideo.log:

_[0] => [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'streamerDB.bans' doesn't exist<br>_

"bans" table doesn't actually exist, I could manually create it if I knew its structure, but it probably should have automatically been created by a script which didn't work (just a guess).

I read the link in the plugin description: [](https://github.com/arut/nginx-rtmp-module/wiki/Control-module) but I don't know how to enable it, nor to check if it is enabled in AVideo Streamer.

Thank you

**Comment by DanielnetoDotCom** [comment]
Hi.

did you click on the install button?

![image](https://user-images.githubusercontent.com/18009293/78407586-8e112f80-75db-11ea-83c9-10fd95d0c7eb.png)

please make sure you clicked it instead manually create it.

**Comment by franranchito** [comment]
Yes, when I click on the "Install tables" button, a brief loading screen appears:

![imagen](https://user-images.githubusercontent.com/19801224/78655903-e93a6f00-78c6-11ea-9e97-05c698ce7f03.png)


and then in the log file output:

```
[07-Apr-2020 11:49:08 Europe/Berlin] Plugin Not Found: Statistics
[07-Apr-2020 11:49:24 Europe/Berlin] Array
(
    [0] => Array
        (
            [file] => /var/www/html/AVideo/objects/mysql_dal.php
            [line] => 130
            [function] => log_error
            [args] => Array
                (
                    [0] => [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'streamerDB.bans' doesn't exist<br>
SELECT * FROM bans WHERE  IP = ? LIMIT 1
                )

        )

    [1] => Array
        (
            [file] => /var/www/html/AVideo/plugin/User_Controll/Objects/Ban.php(14) : eval()'d code(1) : eval()'d code
            [line] => 52
            [function] => readSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => SELECT * FROM bans WHERE  IP = ? LIMIT 1
                    [1] => s
                    [2] => Array
                        (
                            [0] => 192.168.1.20
                        )

                )

        )

    [2] => Array
        (
            [file] => /var/www/html/AVideo/plugin/User_Controll/User_Controll.php(14) : eval()'d code(1) : eval()'d code
            [line] => 136
            [function] => getFromIP
            [class] => Ban
            [type] => ::
            [args] => Array
                (
                    [0] => 192.168.1.20
                )

        )

    [3] => Array
        (
            [file] => /var/www/html/AVideo/plugin/User_Controll/User_Controll.php(14) : eval()'d code(1) : eval()'d code
            [line] => 28
            [function] => isIPBan
            [class] => User_Controll
            [type] => ::
            [args] => Array
                (
                    [0] => 192.168.1.20
                )

        )

    [4] => Array
        (
            [file] => /var/www/html/AVideo/plugin/AVideoPlugin.php
            [line] => 482
            [function] => getStart
            [class] => User_Controll
            [object] => User_Controll Object
                (
                )

            [type] => ->
            [args] => Array
                (
                )

        )

    [5] => Array
        (
            [file] => /var/www/html/AVideo/objects/include_config.php
            [line] => 101
            [function] => getStart
            [class] => AVideoPlugin
            [type] => ::
            [args] => Array
                (
                )

        )

    [6] => Array
        (
            [file] => /var/www/html/AVideo/videos/configuration.php
            [line] => 30
            [args] => Array
                (
                    [0] => /var/www/html/AVideo/objects/include_config.php
                )

            [function] => require_once
        )

    [7] => Array
        (
            [file] => /var/www/html/AVideo/objects/pluginRunDatabaseScript.json.php
            [line] => 6
            [args] => Array
                (
                    [0] => /var/www/html/AVideo/videos/configuration.php
                )

            [function] => require_once
        )

)

[07-Apr-2020 11:49:24 Europe/Berlin] [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'streamerDB.bans' doesn't exist<br>
SELECT * FROM bans WHERE  IP = ? LIMIT 1
```

**Comment by akhilleusuggo** [comment]
what database are you using ?

**Comment by DanielnetoDotCom** [comment]
the provided log error does not match with the install tables button request.
try to install the tables manually running the .SQL script located inside the plugin install directory.

![image](https://user-images.githubusercontent.com/18009293/78674275-bd64bc80-78b9-11ea-8588-3583cca328bb.png)

**Comment by franranchito** [comment]
Thank you all!

> 
> 
> what database are you using ?

Server version:         5.7.29-0ubuntu0.18.04.1 (Ubuntu)

It's the stock mySQL in Ubuntu 18.04.4 LTS



> 
> 
> the provided log error does not match with the install tables button request.
> try to install the tables manually running the .SQL script located inside the plugin install directory.
> 
> ![image](https://user-images.githubusercontent.com/18009293/78674275-bd64bc80-78b9-11ea-8588-3583cca328bb.png)

After manually executing that script, the bans table was created and now I can successfully ban:

![imagen](https://user-images.githubusercontent.com/19801224/78774999-d2168280-7995-11ea-81ee-00531d6ba98c.png)


![imagen](https://user-images.githubusercontent.com/19801224/78774982-c9be4780-7995-11ea-9362-6295f13cf4d6.png)


Here are the steps in case someone encounters this problem (done in Ubuntu 18.04.4 LTS):

1º Login with root user in mysql, from the OS shell:

`sudo mysql -u root`

2º In mysql client, enter your database (use the name of your AVideo streamer database):

`use YOURAVIDEODATABASE;`

3º Check if the "bans" table exists:

`mysql> show tables;`

4º If it doesn't exist, then execute the script (you may need to edit the path in case you installed it elsewhere, or if your AVideo Streamer isn't called "AVideo"):

`mysql> source /var/www/html/AVideo/plugin/User_Controll/install/install.sql`

5º Now check if you already can ban, you could see the entries in:

`select * from bans;`
