### ISSUE TITLE
is there a way to force https with out  .htaccess

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#2806]
is there a way to force https with out  .htaccess?
i dont want to have to put the line in each time i update is tehre another way?

you should add a setting in admin panel to force https that way updates dont effect it
i have this setting on one of my other sites in the main panel could you do the same here?

**Comment by akhilleusuggo** [comment]
you need to add on vhost
```
RewriteEngine on
RewriteCond %{SERVER_NAME} =www.example.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
```

On your config `/videos/configuration.php` remove the lines 

```
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) {
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), FILE);
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
```

**Comment by freedomshare** [comment]
vhost?

**Comment by akhilleusuggo** [comment]
yes apache vhost
I don't know how you're hosting your site , but google it or find a way to get into it .
