### ISSUE TITLE
Videos filters error

### ISSUE THREAD

**Issue by Krystian95** [WWBN/AVideo#2807]
Hi,

I've tried to use the filters "Categories" and "Status" on the videos page (admin and user both) but an error happens:

<img width="1435" alt="Schermata 2020-04-03 alle 19 35 14" src="https://user-images.githubusercontent.com/24765669/78389614-48f0fb80-75e3-11ea-8bd1-cee46712d6ec.png">

<img width="1435" alt="Schermata 2020-04-03 alle 19 35 42" src="https://user-images.githubusercontent.com/24765669/78389638-5312fa00-75e3-11ea-96a0-5f27b41a146c.png">

Really many thanks,
Chris

**Comment by akhilleusuggo** [comment]
well , you need to select the video xD

**Comment by Krystian95** [comment]
> well , you need to select the video xD

So there are no way to filter (show) only the videos unactive on the admin panel? If I have to approve the uploaded videos before publish it could be useful to see only the videos I have to approve.. is there another way to do so?

**Comment by akhilleusuggo** [comment]
I think this option is not implemented yet . If I understood right , you're looking for the option , ''show videos ''unlisted'' ''private'' or ''active''
There's no such option for now .

**Comment by Krystian95** [comment]
> I think this option is not implemented yet . If I understood right , you're looking for the option , ''show videos ''unlisted'' ''private'' or ''active''
> There's no such option for now .

Exactly

**Comment by DanielnetoDotCom** [comment]
It will probably be implemented in the future
