### ISSUE TITLE
A Few curiosity questions/suggestions

### ISSUE THREAD

**Issue by TakeAchance365** [WWBN/AVideo#2808]
@DanielnetoDotCom this is a Curiosity question because I’ve been doing research and for context what I’m thinking about doing with Avideo Platform is making a local video streaming service for my very small town so I am just wondering a few things which this could also count as suggestions

1. I’ve seen where mobile apps can be made but is there a way I can use like the Avideo platform API to make like a TV version or make my own mobile app or make an universal windows app because I want to see if I can put this on like all platforms if that’s possible

2. It would be cool to have a custom theme editor in addition to the themes Already there like changing the color and  really making Your own like professional theme That could reflect the look of the other what business websites 

3. Since This is Linux-based is it possible to make a snap app for the Linux  Snap Store

**Comment by DanielnetoDotCom** [comment]
Hi

Follow the answers...


> I’ve seen where mobile apps can be made but is there a way I can use like the Avideo platform API to make like a TV version or make my own mobile app or make an universal windows app because I want to see if I can put this on like all platforms if that’s possible

yes you can. our mobile app also use out API.
please check this https://github.com/WWBN/AVideo/wiki/AVideo-Platform-API

> It would be cool to have a custom theme editor in addition to the themes Already there like changing the color and really making Your own like professional theme That could reflect the look of the other what business websites

Yes, that is a good idea. I will think about it.

> Since This is Linux-based is it possible to make a snap app for the Linux Snap Store

the main problem with that is if you want to configure the SSL, it will be manually set.
But I will really think about it.
