### ISSUE TITLE
YouTube video error

### ISSUE THREAD

**Issue by Krystian95** [WWBN/AVideo#2810]
Hi, I've tried to import some videos from YouTube, some of them work perfectly, but some others not start, displaying this error: "Playback on other Websites has been disabled by the video owner".

Link: https://www.youtube.com/watch?v=ue1NT3QhuVU

![Schermata 2020-04-04 alle 12 41 37](https://user-images.githubusercontent.com/24765669/78425042-1510e700-7672-11ea-9666-868fd0ef9e4b.png)

Is there any way to make them playable or prevent them to be embed (also only with a warning in the embed link page)?

**Comment by akhilleusuggo** [comment]
If you understand english , I'm pretty sure you understand what it means : 

> Playback on other Websites has been disabled by the video owner

On youtube , video settings , you have the option to allow your videos to be embed or not .
The owner of this particular video did not allowed the embedding of this video . You can't do anything about it , unless you're going to download it and encode it .
