### ISSUE TITLE
YouTube video unactive by default and category

### ISSUE THREAD

**Issue by Krystian95** [WWBN/AVideo#2811]
Hi,

is possible to make all videos imported from YouTube marked as unactive by default as the same is possible to do with the videos uploaded using the encoder? (settings "makeVideosInactiveAfterEncode")

Is also possible to set a category directly on the embed link page? Because if I upload a video from YouTube I can change category only after uploaded it (from the videos page, both user and admin).

Really many thanks,
Chris

**Comment by DanielnetoDotCom** [comment]
Right now we can not treat embed videos differently than the regular videos.

all rules apply to all videos.

but if you really want you can hire us to do it. 

send an email to developer@youphptube.com with details and we can give you a quotation for it.
