### ISSUE TITLE
How can I remove Tags Paid Content from the AVideo

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#2812]
Hi,

I want to hide Tags "Free" Content in the Home Pages & My Video Pages.
Is it possible to do that?

Thanks & BR,

**Comment by akhilleusuggo** [comment]
`CustomizeAdvanced (CustomizeAdvanced) - paidOnlyFreeLabel: `
Make it blank ( empty )

Clear the cache of the site ( both of them )

**Comment by guitarpound** [comment]
Thank you so much

**Comment by zenalien** [comment]
Hello, this workaround doesnt fix the issue.
It leaves a green spare/dot where the word "free" vas.
