### ISSUE TITLE
youtube api issue by google

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#2814]
so google picked up that i am using 10 api keys for the same site this is teh email i have gotten 
![image](https://user-images.githubusercontent.com/60738260/78450802-2b597b80-764f-11ea-8497-fe87c81f79f7.png)

all my api key have gotten the smae email

**Comment by DanielnetoDotCom** [comment]
WOW.

A good solution I found to avoid expire the limits is to increase the cache time.

On the demo site, the cacheTimeOut was = 600 (10 minutes) and it used to expire before 10 am

I increased it to 3600 (1 hour) now the credentials last all day.

![image](https://user-images.githubusercontent.com/18009293/78452377-5351da80-7661-11ea-8d4e-70fc027d3cab.png)

**Comment by freedomshare** [comment]
ok i did that i also use 10 google account and changed all api keys 1 per account not sure if it will help but we will see
