### ISSUE TITLE
Additional Storage Problem

### ISSUE THREAD

**Issue by orangereddy** [WWBN/AVideo#2816]
I have Installed The Streaming Server And Encoder In One Server Which Has 256 GB Of SSD And Additional In That Server I Had 6 TB Hardrive Separate, So Can I Use That Storage As Additional , Like Can I Use Multiple Path As Storage, i would like to use YouPHPtube in intranet, And I Would Like To Remove User Signup can i do it, please guide

Dear @akhilleusuggo Please Look Into This Post Sir

**Comment by akhilleusuggo** [comment]
What do you mean you wanna remove the User Signup ?
If your storage is on different server , you need a plugin . With it you can have unlimited servers with their own storages and encoders ( optional )
https://youphp.tube/plugins/

If it's on the same disk , you can get the plugin SecureVideosDirectory or follow this guide 
https://github.com/WWBN/AVideo/wiki/Can-I-store-my-videos-in-another-location

@DanielnetoDotCom correct me if I'm wrong

**Comment by orangereddy** [comment]
Yes I Want remove signup

**Comment by akhilleusuggo** [comment]
@orangereddy what do you mean ? You want users to upload to your site without identification ?

**Comment by orangereddy** [comment]
No Sir User are only able to watch the content thats it no more option will there for them

**Comment by orangereddy** [comment]
Actually I’m an Internet Service Provider I Wish To Provide Content To My Customers  In Intranet Only

**Comment by akhilleusuggo** [comment]
if you want users to see videos only asigned for them , you can configure User Group .
https://github.com/WWBN/AVideo/wiki/Create-non-public-videos-and-deal-with-user-groups

**Comment by orangereddy** [comment]
Okay sir

**Comment by DanielnetoDotCom** [comment]
@orangereddy what about this

![image](https://user-images.githubusercontent.com/18009293/78563383-4237d380-77f1-11ea-8e00-a450282b0313.png)
