### ISSUE TITLE
branding the video

### ISSUE THREAD

**Issue by rajmaha** [WWBN/AVideo#2819]
Is there any plugins that overlays my logo in uploaded videos permanently? 
I've used VideoLogoOverlay plugin but it only overlay logo in default video player. I wanted logo permanently overlay in all uploaded videos.

**Comment by DanielnetoDotCom** [comment]
I guess what you require must be changed on the ffmpeg command on the encoder site.

I am not sure what will be the ffmpeg but you can google for that and change it in your encoder configurations

**Comment by akhilleusuggo** [comment]
@rajmaha Ok , I can write for you the ffmpeg command line for permanent overlay
Where do you want to place the logo ?

**Comment by rajmaha** [comment]
I need to overlay bottom right. I tried updating ffmpeg command in encoder's configuration but it did not worked.

**Comment by akhilleusuggo** [comment]
I've made a test with the avideo logo and works fine

![image](https://user-images.githubusercontent.com/52116577/78576879-f5c2b700-7835-11ea-8d8f-006cf0f865e3.png)

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo what FFMPEG command did you use?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I've followed https://ffmpeg.org/ffmpeg-filters.html#overlay
The thing is that , for each resolution , the parameters ( where the img gonna overlay ) will change .
I'm still trying to find a command that gonna be responsive to all resolutions . 
Tested on hls as well and works .
