### ISSUE TITLE
Need a limit for number of characters shown in Live Notification

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2821]
There is no cutoff so if someone wants to use 500 characters as their title of the stream that is what it will show when people are looking at it.

<img src="https://static.buddylist.co/x/download.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
What about it? I put a max-width of 400 px

**Comment by JoshWho** [comment]
I am not understanding what u mean.

**Comment by akhilleusuggo** [comment]
He basically changed the size of the GUI display ( the pop up window )

**Comment by akhilleusuggo** [comment]
@JoshWho You can limite the title of livestreams on Database ( change maximum Charvar )

**Comment by DanielnetoDotCom** [comment]
@JoshWho the max width may do the trick. even for long titles
