### ISSUE TITLE
Users can create groups and invite other users

### ISSUE THREAD

**Issue by Krystian95** [WWBN/AVideo#2824]
Hi, first of all, we really appreciate your great work!
Before going to definitely use YouPHPTube, we'd like to know if is possible to users to create private groups (like admin can) and choice to share them (via invitation) with other specified registered users. The goal of this it's to make possible a sort of "private playlists", where users can share videos among other users in a private way.

Really many thanks,
Chris

**Comment by DanielnetoDotCom** [comment]
Hi

Thanks for your words.

No, only admin can create user groups now.

the only way to archive it is coding. 

If you want you can hire us to build it.
