### ISSUE TITLE
Notifications does not show after live stream start

### ISSUE THREAD

**Issue by mukulz** [WWBN/AVideo#2825]
Hi,
I have purchased notifciation plugin and followed the guide to set up onesignal.

I get notification normally when a new video is uploaded. 
However, i do not get a notification when a live stream is started.
Live stream works normally otherwise and people can see online in bell icon. 

I really need oneSignalOnLiveStream to work properly. Any suggestions?

Stream was not working  before due to redirect rule but adding this made it work. Maybe this is related?

RewriteEngine On
RewriteCond %{HTTPS} off [OR]
RewriteCond %{HTTP_HOST} ^www\. [NC]
RewriteCond %{THE_REQUEST} !/plugin/ [NC]
RewriteCond %{THE_REQUEST} !/plugin/Live [NC]
RewriteCond %{THE_REQUEST} !/HLS/ [NC]
RewriteCond %{THE_REQUEST} !/live/ [NC]
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

**Comment by mukulz** [comment]
Only getting notifications from the recorded video which is created after livestream from sendrecodedtoencoder plugin. I should get notification right after stream is started.

**Comment by DanielnetoDotCom** [comment]
First.

please make sure you have those options enabled.

![image](https://user-images.githubusercontent.com/18009293/78667899-234c4680-78b0-11ea-968c-c0acb6db723b.png)

Also, I found something in the plugin that may be making this happen.

please download the notification plugin again and try again.

please update us if it works.

**Comment by mukulz** [comment]
Hi Daniel,
Thank you for the response.
I have verified that those settings are enabled.
I re-downloaded and uploaded the plugin. 

The behaviour is very strange now. The notification was sent only once for live stream and after that it does not show anymore, not even in onesignal debugger. But that one time it worked perfectly. I did not change anything during these events.
The email for 'someone is live now' was also only triggered once. 

Notifications for video upload works as expected.  Any suggestions on what could be wrong?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Same thing here . The notification for live-stream never getting sent .

**Comment by DanielnetoDotCom** [comment]
Are we talking about onesignal or email notification?

**Comment by mukulz** [comment]
Neither of them seem to trigger second time after first attempt happens successfully.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom yes , only email works

**Comment by DanielnetoDotCom** [comment]
I could not find anything that may avoid the once signal to work.

I guess is because we are sending the same message, so I did that, I add an auto date and time into the subject and the message, so each message will have different content.

you will need to download the plugin again.
