### ISSUE TITLE
Video won't play 

### ISSUE THREAD

**Issue by gamersalpha** [WWBN/AVideo#2827]
Hello evryone, i m just installe my new youphptube and youphtube encoder on my local LAN, and i got an issue, when video is upluoad, the video won't start : 

look this ; 

![image](https://user-images.githubusercontent.com/32466950/78603693-dab56e80-7858-11ea-887d-505727c0033e.png)

and on log i can see this : 

`Cette page utilise la propriété non standard « zoom ». Envisagez d’utiliser calc() dans les valeurs des propriétés pertinentes ou utilisez « transform » avec « transform-origin: 0 0 ». naruto---trap-remix-loneliness-elihu-remix-
VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead video.js:84:49
La ressource média http://192.168.50.24/YouPHPTube/videos/_YPTuniqid_5e8b8f4fba0983.95478789_Low.mp4 n’a pu être décodée. naruto---trap-remix-loneliness-elihu-remix-
Le chargement de toutes les ressources possibles a échoué. Le chargement du média a été arrêté. naruto---trap-remix-loneliness-elihu-remix-
Le chargement de toutes les ressources possibles a échoué. Le chargement du média a été arrêté. naruto---trap-remix-loneliness-elihu-remix-
La ressource média http://192.168.50.24/YouPHPTube/videos/_YPTuniqid_5e8b8f4fba0983.95478789_Low.mp4 n’a pu être décodée. naruto---trap-remix-loneliness-elihu-remix-
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
video.js:84:49
playerPlay: Trying to play script.js:581:21
playerPlay: promise found script.js:588:25
playerPlay: Autoplay was prevented, trying to mute and play *** script.js:621:29
playerPlay: Trying to play script.js:581:21
playerPlay: promise found script.js:588:25
playerPlay: Autoplay was prevented, trying to mute and play *** script.js:621:29
playerPlay: Trying to play script.js:581:21
playerPlay: promise found script.js:588:25
playerPlay: Autoplay was prevented, trying to mute and play *** script.js:621:29
playerPlay: Trying to play script.js:581:21
playerPlay: promise found script.js:588:25
playerPlay: Autoplay was prevented, trying to mute and play *** script.js:621:29
playerPlay: Trying to play script.js:581:21
playerPlay: promise found script.js:588:25
playerPlay: Autoplay was prevented, trying to mute and play *** script.js:621:29
playerPlay: Trying to play script.js:581:21
playerPlay: promise found script.js:588:25
playerPlay: Autoplay was prevented, trying to mute and play *** script.js:621:29
playerPlay: Trying to play script.js:581:21
playerPlay: promise found script.js:588:25
playerPlay: Autoplay was prevented, trying to mute and play *** script.js:621:29
playerPlay: Trying to play script.js:581:21
playerPlay: promise found script.js:588:25
playerPlay: Autoplay was prevented, trying to mute and play *** script.js:621:29
playerPlay: Trying to play script.js:581:21
playerPlay: promise found script.js:588:25
playerPlay: Autoplay was prevented, trying to mute and play *** script.js:621:29
playerPlay: Trying to play script.js:581:21
playerPlay: promise found script.js:588:25
playerPlay: Autoplay was prevented, trying to mute and play *** script.js:621:29
playerPlay: Promise is Pending, try again 10 script.js:585:29
`

**Comment by akhilleusuggo** [comment]
You need to update your hls plugin 
Go to the website and upgrade your HLS ( redownload it )

**Comment by DanielnetoDotCom** [comment]
I am not sure if @gamersalpha is using the HLS.

the first step is to make sure the video you are trying to play if its file exists (you must inspect the code)

then, if it exists, check its file size.

if it does not exists describe here how did you submit the video. and check the log files.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Actually you're right , he's not using hls `http://192.168.50.24/YouPHPTube/videos/_YPTuniqid_5e8b8f4fba0983.95478789_Low.mp4`

I've just got a similar error 1-2 weeks ago when you updated the hls 
@gamersalpha What version are you using ?

**Comment by gamersalpha** [comment]
Hello i m using this how to install : 

https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer


Look like is avideo 8.6 
![image](https://user-images.githubusercontent.com/32466950/78695141-fc1c6600-78fd-11ea-9c24-3ae313c0e198.png)

when i put the link of the video on my web navigateur : 
![image](https://user-images.githubusercontent.com/32466950/78695273-2d953180-78fe-11ea-8ca7-b98f793e4af6.png)

on command line : 
i can see the video files : 

the only thinks i m using a fstab share to my video folder

```
//192.168.50.49/GoFlex\040Home\040Personal/YouPHPTube /var/www/html/YouPHPTube/videos/ cifs   vers=1.0,credentials=/root/.share-credentials,iocharset=utf8,file_mode=0777,dir_mode=0777 0 0
//192.168.50.49/GoFlex\040Home\040Personal/YouPHPTubeEncoder/videos/ /var/www/html/YouPHPTube-Encoder/videos/ cifs   vers=1.0,credentials=/root/.share-credentials,iocharset=utf8,file_mode=0777,dir_mode=0777 0 0
```

![image](https://user-images.githubusercontent.com/32466950/78695507-7ea52580-78fe-11ea-842c-db6b3852ef95.png)


like u see i got the video files on the directory video : 

![image](https://user-images.githubusercontent.com/32466950/78695652-a8f6e300-78fe-11ea-9a3b-e6217486c25e.png)



what is wrong please

**Comment by DanielnetoDotCom** [comment]
I can think in 2 things

a problem in your SSL certificate, what seems to be wrong

a problem in your mod_rewrite

they the apache error log and access log

also try to comment this line 250 in your .htaccess

https://github.com/WWBN/AVideo/blob/30d36504b33e2cdc00d9fc4591152b467f7f16b0/.htaccess#L250

**Comment by gamersalpha** [comment]
hello

so i remove my shared fstab folders, and works like a charm

so now i have a space disk problem, need a disk  on my serveur

and make works https without let's encrypt with autosigned

**Comment by gamersalpha** [comment]
Hello so i reinstall evrything from scratch and not using fstab sharing files smb
and now that's works
