### ISSUE TITLE
Video-Thumbnails in the video list are not shown

### ISSUE THREAD

**Issue by VWarte** [WWBN/AVideo#2828]
Thank you for that great piece of software!

I have installed AVideo and AVideo-Encoder on my Ubuntu 18.04 server. If I upload some videos using the encoder, the thumbnails of the uploaded videos aren't shown on the main page:

![0000_07 04 2020_00 14 21](https://user-images.githubusercontent.com/63266168/78610318-1ac62280-7854-11ea-9fe6-be15cb3e8fb9.jpg)

If I hover with the mouse over those videos, I can see the preview of the video. It seems like only the static thumbnails are missing.

Also, as you can see for **TEST VIDEO 2**, the thumbnail is shown under "Up Next" heading, but not in the list right underneath.

If I go to My Videos, there are thumbnails for every uploaded video:

![0000_07 04 2020_00 19 09](https://user-images.githubusercontent.com/63266168/78610611-c7080900-7854-11ea-80c7-f50083385e4d.jpg)

Also, if I take a look at the source of the front page, the thumbnail link like looks like this:
`<img src="https://mydomainname.tld/videos/_YPTuniqid_5e8ba27e178992.58355988_thumbsV2.jpg?" alt="Test Video 3" class="thumbsJPG img img-responsive rotate0" id="thumbsJPG3" style="">`

But there are no images with the suffix **_thumbsV2.jpg** in the /videos/ directory, so it looks like the thumbnails aren't getting created in the first place?

Any idea how to fix that problem?

**Comment by akhilleusuggo** [comment]
check the log files and inspect the java script on web console
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

**Comment by VWarte** [comment]
> 
> 
> check the log files and inspect the java script on web console
> https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Thanks for the tip. I was looking in the apache log files, which wasn't very helpful. But in /videos/avideo.log I've finally found what was causing the issue:

`im_resize: Function does not exists: imagecreatefromjpeg`

So, GD support in my PHP installation was missing. In case someone has the same issue, just install GD module for PHP:

`apt install php7.2-gd`

Regards.

**Comment by SaliC-re** [comment]
Hi all,

i had the same problem and fixed it temporarily with your answer (installing gd). But I see, if you change something in the video details like the name of the video - the thumbnails disappear again. If I edit the video after it, click on "Images" and save it - the thumbnail is back again. Is it a bug? I'm on v8.7. @VWarte @DanielnetoDotCom
