### ISSUE TITLE
mp4 file do not encode

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#2829]
AVideo Ver8.6 and encoder Ver3.1 under ubuntu18.04.
I used AVideo's encoder mp4 file.
Enode finishied. I look My Video. This file's format is Other. I could not play it.
Original file size is 25.5MB. But this file size is small in My video.
[avideounderupload.log](https://github.com/WWBN/AVideo/files/4441625/avideounderupload.log)
[avideo.log](https://github.com/WWBN/AVideo/files/4441627/avideo.log)
![afterencode](https://user-images.githubusercontent.com/46562199/78621960-cdcb6600-78be-11ea-9005-43e7d84822a6.png)
![afterencode](https://user-images.githubusercontent.com/46562199/78621975-dde34580-78be-11ea-96af-fa9224a47ec6.png)
![beforeencode](https://user-images.githubusercontent.com/46562199/78621988-e8054400-78be-11ea-82bf-33bacf28fccb.png)

**Comment by DanielnetoDotCom** [comment]
I guess the video file was not transferred.

check your encoder and streamer log files.

**Comment by hnagasawa** [comment]
where is streamer log?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by hnagasawa** [comment]
I use Apach3. Do I see streame.log under /var/log/apach2 ? I treied tuploade other system(other system build Feb=2020)).
same error occured. This system update only. previos version dfirent snd Avideo Ver8.6 and encoder 3.1 ?
Please tell me.

**Comment by wahabzafar** [comment]
same problem with me dear i am wondering from one month for solution.

**Comment by DanielnetoDotCom** [comment]
without log files, I can not help you

**Comment by hnagasawa** [comment]
I scrach my system and I reinstall OS and AVedio and AVideo Enconder.
 I tried to upload mp4 file 13:19 08-Apr-2020.
But same error occured.
encoder log
[encoder-avideo.log](https://github.com/WWBN/AVideo/files/4448209/encoder-avideo.log)
AVideo log
[avideo.js.log](https://github.com/WWBN/AVideo/files/4448327/avideo.js.log)
[avideo.log](https://github.com/WWBN/AVideo/files/4448328/avideo.log)
Under /var/log/apache2 logs
[avideo.access.log](https://github.com/WWBN/AVideo/files/4448344/avideo.access.log)
[avideoerror.log](https://github.com/WWBN/AVideo/files/4448348/avideoerror.log)

If you need other logs, Please tell me log's file name and directry name.

**Comment by akhilleusuggo** [comment]
what php version are you using ?
Looks like an old version .
Have you followed the installation instruction ?
https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer

**Comment by hnagasawa** [comment]
>what php version are you using ?
I installed PHP Ver7.2.
#php -v
php -v
PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )

I see next url
https://www.linuxbabe.com/ubuntu/install-youphptube-ubuntu-18-04-server

Avideo(I build it this Feb) worked  before update AVideo 8.6 and Econder 3.6

**Comment by akhilleusuggo** [comment]
encoder can't be 3.6 if the lastest version is 3.1

Please follow up with this guide 
https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer

If you follow guides on other sites , then your errors/problems should be redirected there , not here

**Comment by hnagasawa** [comment]
I am sorry. enconder ver3.1. I use Mysql.
I think the video file was not transferred.
Which file do I check ?

**Comment by akhilleusuggo** [comment]
so what happens when you click on the video ?
I can't see errors ( related to the video ) , except 
`aVideoEncoder.json: Files EMPTY` ( not necessary to be an error )

1) Try to open the video , if it doesn't play , step 2
2) Change your password on ''My account''
3)Log out , from encoder and streamer site 
4) Open encoder , and manually type your login/password

And let us know if the problem persists

**Comment by DanielnetoDotCom** [comment]
I found this in your logs


`PHP Fatal error:  Uncaught Error: Call to undefined function imagecreate`

Looks like you are missing the GD lib for PHP.

Fix it and try again.

**Comment by akhilleusuggo** [comment]
Oh , that's something I've missed 
`sudo apt-get install php-gd`

**Comment by hnagasawa** [comment]
I scratch the system. I reinstalled OS and AVideo and AVideo-encoder(of cource install php-gd)
I uploaded mp4 file to enconder 14:25 9-Apr-2020. but same error occured.
mp4 file size is 0.
# ls -l
合計 936
-rw-r--r-- 1 www-data www-data 614546  4月  9 14:25 _YPTuniqid_5e8eb1b40f8216.34925335.gif
-rw-r--r-- 1 www-data www-data  10300  4月  9 14:25 _YPTuniqid_5e8eb1b40f8216.34925335.jpg
-rw-r--r-- 1 www-data www-data 188148  4月  9 14:25 _YPTuniqid_5e8eb1b40f8216.34925335.webp
-rw------- 1 www-data www-data      0  4月  9 14:25 _YPTuniqid_5e8eb1b40f8216.34925335_HD.mp4
I upload direct mp4 file to AVideo stareamer. It fine and I play this file.
I think encoder porblem or trasfer from AVideo encoder to AVideo streamer.

encoder log
[encoderavideo.log](https://github.com/WWBN/AVideo/files/4454345/encoderavideo.log)
stearmer log
[avideo.log](https://github.com/WWBN/AVideo/files/4454346/avideo.log)

avideo logs under /var/log/apache2
[avideo.access.log](https://github.com/WWBN/AVideo/files/4454347/avideo.access.log)
[avideo.error.log](https://github.com/WWBN/AVideo/files/4454352/avideo.error.log)

**Comment by akhilleusuggo** [comment]
witch guide have you followed ?

**Comment by hnagasawa** [comment]
I referred to the URL you told me.
https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer
I did git clone under /var/www
I move /var/www/AVideo/AVideo-encoder to /var/www/AVideo/upload
All files and directry "chown www-data:www-data /var/www/AVideo/ -R
I created /etc/apache2/sites-available/avideo.conf file
<VirtualHost *:80>
    ServerName tube.yourdomain.com
    DocumentRoot /var/www/AVideo

    <Directory /var/www/AVideo>
       DirectoryIndex index.php
       Options +FollowSymLinks
       AllowOverride All
       Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/avideo.error.log
    CustomLog ${APACHE_LOG_DIR}/avideo.access.log combined

</VirtualHost>

I run "a2ensite avideo.conf" "a2enmod rewrite" "a2dissite 000-default.conf"
I run systemctl restart apache2.
systemctl restart php7.2-fpm

I setup AVideo this Febrary. I follwed https://www.linuxbabe.com/ubuntu/install-youphptube-ubuntu-18-04-server
AVideo worked fine.
Today, I ran "git pull" AVideo and AVideo-enconder.This system(I set up this Febrary) occured same error.

**Comment by akhilleusuggo** [comment]
I don't know why you're making that much modifications and not following the guide .
You're running the script locally
`cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube.git`
And you installed in on `/var/www` , why ?
php7.2-fpm , why ?

I'm out of this issue . You have the guide , if follow up you will have it running , if you wanna follow some other guide , gl
Start with a standard installation , then start changing things

**Comment by hnagasawa** [comment]
I have any questions.
Which is corect https://github.com/WWBN/AVideo.git or https://github.com/DanielnetoDotCom/YouPHPTube.git ?
>And you installed in on /var/www , why ?
I git clone under /var/www/html, I access AVideo. 404 error ocuured.
>php7.2-fpm , why ? 
This Febrary, I did not install php7.2-fpm AVideo did not work.
You suggestion URL
https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newe
This is not include how to install AVideo-encoder.
Where do your recommand AVideo-encoder's install manual ?
Please tell me

**Comment by akhilleusuggo** [comment]
is the same
The most recent is  https://github.com/WWBN/AVideo.git after changing the project name

**Comment by hnagasawa** [comment]
Where direcry do you recommand to install AVideo-econder ?
For example 
under /var/www/html/AVideo

**Comment by akhilleusuggo** [comment]
under /var/www/html , like it should be
You will have 2 directories on /var/www/html
AVideo and AVideo-Encoder

**Comment by hnagasawa** [comment]
When I install AVideo and AVideo-Encoder under /var/www/html ,
please tell me how to set AVideo streamer's menu sitesetting -> Advanced Configuration ->Encoder URL

**Comment by hnagasawa** [comment]
I scrach the system> I reinstall again
I referred to the URL you told me.
https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer

Streamer Setup Wizard finish.
![5](https://user-images.githubusercontent.com/46562199/78892077-a97cae80-7aa3-11ea-9930-f2e2159a74c5.png)
![6](https://user-images.githubusercontent.com/46562199/78892101-b4cfda00-7aa3-11ea-848f-5020b4dd8d36.png)

I click Sigin in. 404 error ocurred
![7](https://user-images.githubusercontent.com/46562199/78892188-e183f180-7aa3-11ea-9fe9-eebf7de21e54.png)

Why ?

[apache2.conf.txt](https://github.com/WWBN/AVideo/files/4455992/apache2.conf.txt)

**Comment by akhilleusuggo** [comment]
it is really easy to read , take your time , breath !
`sudo nano /etc/apache2/apache2.conf`
```
<Directory /var/www/>
          Options Indexes FollowSymLinks
          AllowOverride All
          Require all granted
  </Directory>

```
`sudo a2enmod rewrite`
`sudo /etc/init.d/apache2 restart`

**Comment by hnagasawa** [comment]
There is a description of your point in the original file.
I am already running sudo a2enmod rewrite and sudo /etc/init.d/apache2 restart.
Do you need to execute those commands again after I web setting ?

**Comment by akhilleusuggo** [comment]
On your apache2 config that you have posted , I can see that you have not set `AllowOverride All`

**Comment by hnagasawa** [comment]
This problem is fix. Thank you for your support.
By the way, Now to access the AVideo Streamer is http://192.168.1.153/AVideo.
Is there a way to access the AVideo Streamer top page at http://192.168.1.153?

**Comment by wahabzafar** [comment]
same problem is with me but i am using cpanel.videos autometically converted to other format.

![image](https://user-images.githubusercontent.com/60570245/78982210-15f6bc80-7b3b-11ea-952f-8a836ff614d4.png)

**Comment by akhilleusuggo** [comment]
@hnagasawa try to google more about vhosts and default.conf

**Comment by wahabzafar** [comment]
@akhilleusuggo my problem is only with encoder videos direct upload videos are working fine.
