### ISSUE TITLE
Default video & PPV

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#2830]
1. How to choose which video to use as default when someone visits the website I don't like the fact that the newest video becomes the first video loaded. I'd prefer choose the video I want to load first. Or maybe select a feature video or stream.

2. Is there a way to have pay per view available for live streams as well?

**Comment by akhilleusuggo** [comment]
Go to your videos ( admin )
Make a video with a ''start'' to feature 
If you select more then 1 , they will appear randomly the selected ones 

![image](https://user-images.githubusercontent.com/52116577/78689159-b01df100-78fe-11ea-9798-7c24b7ece1bd.png)

**Comment by DanielnetoDotCom** [comment]
About the PPV we do not have it for lives, but we have subscription that may work in live streams.

you can make the Livestream only available for some user groups, and the subscription plugin will auto-assign users to those user groups.

**Comment by ganddser** [comment]
Thanks. Worked
