### ISSUE TITLE
Make videos for certain groups be visible only to those groups on the main page?

### ISSUE THREAD

**Issue by VWarte** [WWBN/AVideo#2831]
Hello dear friends!

I have a question according the lockdown of videos to certain groups.

Right now, if I upload a video and chose a group (eg. "Friends") to which this video should be accessible, this video is still listed on the main page. Only if someone, who is not a member of the group, clicks on this video, there is a "not accessible" message.
If I set the video as "unlisted", this video is not seen on the main page to regular users as well as to the members of the certain group.
Is there a way to set up the video as visible on the main page to the members of the group, but not visible to regular or anonymous users?

Best regards.

**Comment by DanielnetoDotCom** [comment]
Did you try this?

![image](https://user-images.githubusercontent.com/18009293/78702379-df246a80-78de-11ea-9f5e-f88e02fd1004.png)

**Comment by VWarte** [comment]
This is exactly what I was looking for! Thank you very much for your help!
