### ISSUE TITLE
Unable to encode video through public encoder

### ISSUE THREAD

**Issue by wahabzafar** [WWBN/AVideo#2832]
I am unable to encode videos through public encoder please help.

![image](https://user-images.githubusercontent.com/60570245/78690841-67236800-7911-11ea-895a-81cc2337e2cd.png)

**Comment by DanielnetoDotCom** [comment]
Hi

we now have encoder 1 to 6, but due to a server limitation, encoder 2 is not available anymore. you still can use any other.

check our encoder network https://network.avideo.com/

![image](https://user-images.githubusercontent.com/18009293/78702584-31fe2200-78df-11ea-9f8f-aef55647f3c0.png)
