### ISSUE TITLE
Video Display and Overlap of Top Pane

### ISSUE THREAD

**Issue by rielcomms** [WWBN/AVideo#2833]
The top part of the windows for the admin page and video page is too big that it cuts off a portion of the viewable area. See Screenshot
![arisetube com-2020 04 06-20_57_04](https://user-images.githubusercontent.com/46077574/78698126-0e2ae400-78bf-11ea-99d0-753f4de8de98.png)

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
try to reduce the buttons on the top bar.

for example, reduce the text on the upgrade button and disable live links plugin if you are not using.

**Comment by akhilleusuggo** [comment]
You can simple press ''CTRL'' key , and the scroll wheel  ( mouse ) , to resize your browser zoom .
