### ISSUE TITLE
Cannot Login to AVideo app

### ISSUE THREAD

**Issue by rielcomms** [WWBN/AVideo#2834]
When I change site in Avideo Android app, it gives an error that streamer site needs to be updated.
See screenshot
![Screenshot_20200407-110958](https://user-images.githubusercontent.com/46077574/78699086-8ba32400-78c0-11ea-984b-d38271746a9a.png)

**Comment by DanielnetoDotCom** [comment]
what is your streamer version?

**Comment by rielcomms** [comment]
I dont know how to find the version

**Comment by rielcomms** [comment]
The nginx version is
nginx version: nginx/1.14.0 (Ubuntu)

**Comment by DanielnetoDotCom** [comment]
Hi

you can check your version on the footer, or clicking in the Update version menu

![image](https://user-images.githubusercontent.com/18009293/78770343-d4141d80-7964-11ea-9a51-a6c106411fe1.png)

![image](https://user-images.githubusercontent.com/18009293/78770389-e1c9a300-7964-11ea-8f73-34a5787064fa.png)

**Comment by rielcomms** [comment]
See attached for streamer version. Say 6.4
Issue now is that its not playing videos also
![stream_version_1](https://user-images.githubusercontent.com/46077574/78815573-b1e2c580-798d-11ea-8ec0-7d4e35a7df73.png)

**Comment by DanielnetoDotCom** [comment]
we are currently in Streamer version 8.6 and encoder version 3.1

please update both to the latest.
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by orangereddy** [comment]
I Aslo Can't Able Resolve The Site

**Comment by DanielnetoDotCom** [comment]
@orangereddy what are you talking about?
