### ISSUE TITLE
Unable to save changes in admin panel 

### ISSUE THREAD

**Issue by wahabzafar** [WWBN/AVideo#2835]
i want to save changes in admin panel but it is stuck on below screen.nothing saves in my admn panel even its any code.

![image](https://user-images.githubusercontent.com/60570245/78703326-65fb3680-7923-11ea-90a4-2a0f778d3d16.png)

**Comment by DanielnetoDotCom** [comment]
try this https://github.com/WWBN/AVideo/issues/2681#issuecomment-595400965

**Comment by wahabzafar** [comment]
@DanielnetoDotCom is there any other way to change encoder setting or can we directly login to encoder?https://encoder3.avideo.com/

**Comment by DanielnetoDotCom** [comment]
Check in your site configuration menu what encoder did you set there

**Comment by wahabzafar** [comment]
yes i am trying to save https://encoder3.avideo.com/ instead of https://encoder2.avideo.com/ but unable to save changes screen remain same as above.

**Comment by akhilleusuggo** [comment]
@wahabzafar check the log files / console java script
But I'm sure you need to give the rights to the folder to be able to save .
```
chmod 755 /var/www/html/AVideo
cd /var/www/html/
chown -R www-data *
```

This should do the trick

**Comment by wahabzafar** [comment]
thanks @akhilleusuggo i am using cpanel can you guide how to find on cpanel?

**Comment by akhilleusuggo** [comment]
@wahabzafar Sorry I can't 
Used once ispconfig , but not much experience with the panels ( I hate them )

**Comment by wahabzafar** [comment]
@akhilleusuggo oh ok thanks can you please help to trace anyone who can help me out actually i am asking for help from a month.

**Comment by akhilleusuggo** [comment]
@wahabzafar Do you have access to the server ? Or you're using a cpanel from a shared/hosting provider ? 
Can you get access to the server via command lines ?

**Comment by wahabzafar** [comment]
@akhilleusuggo dear i cant access server via command line.

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

If you're using chrome it's F12
Go to Network , XHR
Now go to your configuration that it's looping , and find the error and share it .

**Comment by wahabzafar** [comment]
@akhilleusuggo dear please find below as guided by you.

![image](https://user-images.githubusercontent.com/60570245/78802024-c4352180-79d6-11ea-8cf2-b3f44767ced3.png)

**Comment by akhilleusuggo** [comment]
That's exactly what you need to read 
Do you see that red thing ? ConfigurationUpdate ? We need to see what's there . That's a clue where the error is coming from .

**Comment by wahabzafar** [comment]
<br />
<b>Notice</b>:  Undefined index: contactEmail in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>17</b><br />
<br />
<b>Notice</b>:  Undefined index: language in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>18</b><br />
<br />
<b>Notice</b>:  Undefined index: webSiteTitle in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>19</b><br />
<br />
<b>Notice</b>:  Undefined index: authCanComment in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>20</b><br />
<br />
<b>Notice</b>:  Undefined index: authCanUploadVideos in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>21</b><br />
<br />
<b>Notice</b>:  Undefined index: authCanViewChart in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>22</b><br />
<br />
<b>Notice</b>:  Undefined index: disable_analytics in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>24</b><br />
<br />
<b>Notice</b>:  Undefined index: disable_youtubeupload in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>25</b><br />
<br />
<b>Notice</b>:  Undefined index: allow_download in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>26</b><br />
<br />
<b>Notice</b>:  Undefined index: session_timeout in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>27</b><br />
<br />
<b>Notice</b>:  Undefined index: encoder_url in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>28</b><br />
<br />
<b>Notice</b>:  Undefined index: smtp in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>29</b><br />
<br />
<b>Notice</b>:  Undefined index: smtpAuth in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>30</b><br />
<br />
<b>Notice</b>:  Undefined index: smtpSecure in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>31</b><br />
<br />
<b>Notice</b>:  Undefined index: smtpHost in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>32</b><br />
<br />
<b>Notice</b>:  Undefined index: smtpUsername in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>33</b><br />
<br />
<b>Notice</b>:  Undefined index: smtpPassword in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>34</b><br />
<br />
<b>Notice</b>:  Undefined index: smtpPort in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>35</b><br />
<br />
<b>Notice</b>:  Undefined index: head in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>38</b><br />
<br />
<b>Notice</b>:  Undefined index: adsense in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>39</b><br />
<br />
<b>Notice</b>:  Undefined index: autoplay in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>42</b><br />
<br />
<b>Notice</b>:  Undefined index: theme in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>43</b><br />
<br />
<b>Notice</b>:  Undefined variable: response2 in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>112</b><br />
{"status":"1", "respnseLogo": [], "respnseFavicon": null}

**Comment by wahabzafar** [comment]
if i click on error this file opens.

**Comment by DanielnetoDotCom** [comment]
looks like you are missing files. you have an error 404 for configurationUpdate.php

**Comment by akhilleusuggo** [comment]
all this problems would have solved in 2s without those panels ( that's why I hate them )
Anyway !

> @DanielnetoDotCom is there any other way to change encoder setting or can we directly login to encoder?https://encoder3.avideo.com/

Go to your database , and change it manually , I'm pretty sure that on panels phpmyadmin are installed

**Comment by wahabzafar** [comment]
thanks @akhilleusuggo and @DanielnetoDotCom now i can save link of encoder but unable to save codes like analytic code and my website text also gone on right side from left side can you guide how to set it.
and please also guide for for mp4 videos which converted to other format this only problem is with encoder videos direct videos are workinf fine.

https://user-images.githubusercontent.com/60570245/78982210-15f6bc80-7b3b-11ea-952f-8a836ff614d4.png

**Comment by DanielnetoDotCom** [comment]
About the Text align to the right, what language are you using?

I mean the only reason is if you are using one of the following languages

        'JO', // Arabic Jordan
        'PS', // Arabic Palestinian Territory, Occupied
        'SY', // Arabic Syrian Arab Republic
        'IL'  // Hebrew

Or you have some CSS messing up your site.


"mp4 videos which converted to other format "???

It does not make any sense.

**Comment by wahabzafar** [comment]
@DanielnetoDotCom text aliegn issue has been resolved.

but "mp4 videos which converted to other format " issue exist through encoder videos.

**Comment by DanielnetoDotCom** [comment]
@wahabzafar I have no idea what are you talking about.
please open a new issue regarding the MP4 problem, and place a lot of more details.

and what was the alignment problem?
