### ISSUE TITLE
Cannot Login as admin to Site

### ISSUE THREAD

**Issue by rielcomms** [WWBN/AVideo#2837]
I disabled traditional Login so as to login with Facebook, Twitter and Google
However when I login, I dont get admin console even when logged in as Admin
Even after login the status is still sign, it returns to login window or logs in without providing the admin interface for logged in user
![login_issue](https://user-images.githubusercontent.com/46077574/78705072-27855d80-78ca-11ea-80fb-0184554768ae.png)

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
You have 2 options 

1- reset the plugins table deleting everything on it so you will be able to login again with the admin user . 

2- edit the users table and make one of your social users admin, change the isAdmin column =1

**Comment by akhilleusuggo** [comment]
Follow this guide to reset the admin password .
https://github.com/WWBN/AVideo/wiki/Reset-a-Password

Go to your database , plugins table , CustomizeUser , 
change `"disableNativeSignIn":true` to `"disableNativeSignIn":false`
