### ISSUE TITLE
How to reenable native login fields on back end?

### ISSUE THREAD

**Issue by ConnerK442** [WWBN/AVideo#2838]
In my infinite wisdom, I was playing with the settings on my new site and disabled the log in ability, not realizing that this would apply to admin user as well. Overnight, admin user was logged out, I think automatically but possibly I did it and forgot. 

Now, I cannot edit the setting because I am not logged in, and I cannot log in because I disabled it. Is there a way I can change this setting somewhere on the back end? I looked around and could not find anything that worked, but I assume it is possible. 

Thank you

**Comment by DanielnetoDotCom** [comment]
Truncate the plugins table and you will be back

**Comment by ConnerK442** [comment]
> Truncate the plugins table and you will be back

I tried this with no luck. I made sure to clear my browser cache in case that mattered. I also restarted the apache server, in case that mattered.

Anything else I can try?

mysql> TRUNCATE TABLE plugin;
Query OK, 0 rows affected (0.04 sec)

**Comment by DanielnetoDotCom** [comment]
the correct table is plugin**s** NOT plugin

so you should run `TRUNCATE TABLE plugins;`

**Comment by ConnerK442** [comment]
That worked! Thank you so much!

I was using the wrong database - "mysql", instead of "aVideo". 

Do you know of anything else I may have just broken by truncating "plugin" table on "mysql" database? Sorry for dumb questions, still learning...

**Comment by DanielnetoDotCom** [comment]
as long as your command was 0 rows affected you should be fine.

**Comment by ConnerK442** [comment]
> as long as your command was 0 rows affected you should be fine.

Ok, fingers crossed. Thanks again, really appreciate the super fast help!
