### ISSUE TITLE
File Upload Options

### ISSUE THREAD

**Issue by twumb** [WWBN/AVideo#2839]
I have downloaded and installed the application but cannot find the upload options as listed in the installation procedure. 

I have attached the only two options I see on my portal
![Screen Shot 2020-04-07 at 7 18 59 PM](https://user-images.githubusercontent.com/7141101/78715609-2a557200-790d-11ea-8ab1-d564faa2ff72.png)

Please help

**Comment by akhilleusuggo** [comment]
I don't know why you labeled ''bug''
Log as Admin - Plugins - CustomizeAdvanced
Uncheck what you wanna show
![image](https://user-images.githubusercontent.com/52116577/78720592-a613e680-792e-11ea-8540-bde98109b178.png)

**Comment by twumb** [comment]
Sorry,
I didn't tag it well, wanted to change it later but couldn't. Apologies

Regards,
