### ISSUE TITLE
Question about user groups

### ISSUE THREAD

**Issue by TakeAchance365** [WWBN/AVideo#2840]
@DanielnetoDotCom Can user goups be used as a way like for example this user group titled Content Creators And set that group to be the only ones to upload videos

And the other groups would be for regular users and they can’t upload content but watch the content and comment on it

**Comment by akhilleusuggo** [comment]
But what is the goal ?
I just don't see the sense of it . At the end they have to share the same user grp to watch the video.

**Comment by DanielnetoDotCom** [comment]
No, the user groups rules are only to watch videos, it does not reflect in the upload rights

**Comment by TakeAchance365** [comment]
@akhilleusuggo basically mostly for closed beta testing Since I’m hosting it on my own server and my Goal with Haleyvillelive That’s what I’m calling my platform to make a local video streaming service for my small town of Haleyville to be used Too tie all the local businesses and the school  video Content all together The make up place where the community can I have it on like a little video streaming service for local news sports any information going on with the school Maybe some local bands to maybe some local bands to but basically it’s to control all the content coming in at once to where my server doesn’t get overloaded and I can make sure I have the right amount of storage to handle all of this
