### ISSUE TITLE
Videos encoded and Videos status

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2841]
**Is your feature request related to a problem? Please describe.**
If the feature ''makeVideosInactiveAfterEncode'' is disabled , that means when a video is encoded notifications will be sent , but not all users want to immediately publish videos .

**Describe the solution you'd like**
An option on the encoder , under categories , that let users chose what state their videos will be :
Active ( default )
Unlisted ( no notification should be sent )
Private ( no notification should be sent )

**Describe alternatives you've considered**
Users groups on encoder should be visible only to users groups , not to everybody .

**Additional context**
Hi Daniel :)

**Comment by ronaldod** [comment]
Interesting feature.
