### ISSUE TITLE
error on admin page

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#2844]
**Describe the question**
A clear and concise description of what is your question.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.
![image](https://user-images.githubusercontent.com/60738260/78802774-32082b80-798c-11ea-9311-2c716df999cc.png)

**Comment by akhilleusuggo** [comment]
Yes , this is well knows bug . When your Dashboard is has too many items to load , this error appears .
The only way to fix it right now is by enabling AsyncJobs on CustomizeAdvanced 
![image](https://user-images.githubusercontent.com/52116577/78814918-293d4700-79d8-11ea-8003-23055cdf8561.png)
