### ISSUE TITLE
Webcam

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#2845]
Anyone experiencing webcam stream issues?

I can't get the Webcam stream to enable the webcam. Says "You are not online, loading webcam..." but that's all it never returns a response, just sits here.
I've tried it on a different computers including a Mac and one without a webcam to see if it would respond with no webcam found or something, nothing.

Tried a mobile device as well still nothing. Any ideas?
![sc-2](https://user-images.githubusercontent.com/37193130/78817861-ce88f880-79a1-11ea-9891-f550038bb413.jpg)

**Comment by DanielnetoDotCom** [comment]
this is experimental, it is not working yet.

**Comment by ganddser** [comment]
Thanks I thought it may work in some circumstances.
