### ISSUE TITLE
User Redirect

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#2846]
Is there a way to redirect non-admin users to "My Channel" or another area after they sign-up or login? 
Rather than staying on the sign up after completing the signup form. And loading the video after signing in.

**Comment by akhilleusuggo** [comment]
Yes , Plugins -  CustomizeUser
![image](https://user-images.githubusercontent.com/52116577/78843528-b1890f80-7a0b-11ea-9221-b6fa27c9e031.png)
