### ISSUE TITLE
not getting country,  state and city option list

### ISSUE THREAD

**Issue by sharad22gupta** [WWBN/AVideo#2848]
not getting the dropdown list here.

![Annotation 2020-04-09 173130](https://user-images.githubusercontent.com/15939963/78894825-729a9e80-7a8b-11ea-9a03-5b574d28a723.png)

**Comment by akhilleusuggo** [comment]
You need to have installed ( tables db ) and enabled plugin User_Location (User_Location)
At the least the tables should be installed
