### ISSUE TITLE
Email settings bug

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2849]
**Describe the bug**
The change of email checking ( only 1 can exist ) , made users unable to save settings .
When going to ''My Account'' , and want to save , you can't save since the email there ''already exists'' .

**To Reproduce**
1. Go to '...' My Account
2. Click on '....' Try to change a pic or password or what ever
3. Save

**Expected behavior**
The check should be done to make sure that other emails ( not the account of the changer ) does get duplicated , not the one saving the setting .

**Error Logs**
Nothing on the logs related to this error 
Apparently not implemented yet 

**Screenshots**
![image](https://user-images.githubusercontent.com/52116577/78901051-707f1280-7a80-11ea-9aa5-939dddccfade.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu Server 18.04
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
Hello Daniel !

**Comment by DanielnetoDotCom** [comment]
Please try now and let me know.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Works , thanks
