### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by gamersalpha** [WWBN/AVideo#2850]
i send many youtube video with audio settings : 

i m using this settings : 

![image](https://user-images.githubusercontent.com/32466950/78909156-601c6700-7a83-11ea-8dd1-2178b6f4f7c7.png)

and on my youphptube interface i got this, and i can't play musique : 
![image](https://user-images.githubusercontent.com/32466950/78909213-77f3eb00-7a83-11ea-83eb-abecfff329c5.png)
![image](https://user-images.githubusercontent.com/32466950/78909251-86da9d80-7a83-11ea-822d-b2027f2ade24.png)

so i can't found log :

this my folder with the videos : 

![image](https://user-images.githubusercontent.com/32466950/78909320-a07be500-7a83-11ea-806f-80d3afa06eb6.png)

do u have some clue why audio not working ?

the video works very well !

thanks all

**Comment by akhilleusuggo** [comment]
encoder logs ?

**Comment by gamersalpha** [comment]
i reinstall evrything from scratch and look like working now thanks
