### ISSUE TITLE
Can't change encoder network

### ISSUE THREAD

**Issue by gamersalpha** [WWBN/AVideo#2851]
Hello, 
so i m using the last release of Avideo

and avideo-encoder

and on my interface admin panel of avideo i can't change the encoder network: 

![image](https://user-images.githubusercontent.com/32466950/78909629-1d0ec380-7a84-11ea-85db-5723127ce666.png)

evry time i add the mine

the conf reset to https://network.avideo.com/
i can't change it why ?

thanks all

**Comment by akhilleusuggo** [comment]
Don't change it from admin panel
Go to plugins , CustomizeAdvanced
