### ISSUE TITLE
CHAT like on homepage promo

### ISSUE THREAD

**Issue by partystreamsk** [WWBN/AVideo#2852]
**Describe the question**
I back to youphptube and buy some plugins chat2 included , because i see lot of improvement. I see that you added a new chat and is cool but is possible to have it like you promote it on your homepage?? 

**Screenshots**

![chatt](https://user-images.githubusercontent.com/50631455/78934157-ba7cee00-7aaa-11ea-9ecf-a6f612142e2a.PNG)

**Comment by DanielnetoDotCom** [comment]
Hi

this is an old screenshot. we do not have a chat like this anymore.

the chat we offer now it the one that stays over the page.

**Comment by partystreamsk** [comment]
Sorry but chat before was not like on screenshot. I know because i tryed to use youphptube time ago. Did you know that this chat2 is unusable on mobile devices? Should be something like on screenshot. So its there any way to get chat like on screenshot? I really back and install youphptube (Avideo) cause i need a solution like on screenshot.  I already 6 plugins (chat2) included and need to know if i get any support or help to be sadisfied or i wasted time. thanks.

**Comment by DanielnetoDotCom** [comment]
right now, the chat has not supported that way, but we may add this option for the chat 2 in the future

**Comment by partystreamsk** [comment]
in future when? its there possibility to attack this chat like on screenshots? i spendt some money on plugins and i have plan to buy others so some help and interest will be appreciated!

**Comment by DanielnetoDotCom** [comment]
Sorry I do not have a specific time for that upgrade yet

**Comment by partystreamsk** [comment]
ok so than you can refund me all if you dont wanna help me with nothing and you dont have interess about your paying customers! Everytime if there is an issue , you just reply without interest. Always need to solve issues bymyself. That is not good way to treat your customers!

**Comment by DanielnetoDotCom** [comment]
The chat 2 was always on the demo site, so you can test how it works and looks like.

If you want to change or improve some plugin, you can hire us to do it.

**Comment by partystreamsk** [comment]
Again ... You promote on your site this layout of chat, after i buy it it different. I buyed it because i like item as you describe in screenshot. Its a misleading ad and promo of your plugin! I will not hire you and pay for something that should be included in plugin that is offered by default.

![chatt](https://user-images.githubusercontent.com/50631455/79047181-693d3d80-7c15-11ea-8715-165c9369c9d6.PNG)

**Comment by DanielnetoDotCom** [comment]
if you download version 3.x or older you will have a chat like that

the new versions do not have this anymore

feel free to download older versions from here https://github.com/WWBN/AVideo/releases?after=7.2

**Comment by partystreamsk** [comment]
i dont see any older plugin there. Why you dont post an direct link of correct plugin?

**Comment by DanielnetoDotCom** [comment]
the liveChat plugin, you must download the full old version. 

it will not work in the new versions.

**Comment by partystreamsk** [comment]
So i need to download an old software too? sorry no. I didnt pay money for old software or this mistakes. If you dont have any solution for my purchase and dont wanna solve it i will open dispute on paypal becuase i buyed an item that wasn’t as described.

**Comment by DanielnetoDotCom** [comment]
It is as described, exactly the same we have on demo site.

**Comment by partystreamsk** [comment]
No its not. Your screenshots and promo on homepage and in plugin area are clear. Again : 
![pluginarea](https://user-images.githubusercontent.com/50631455/79047694-90493e80-7c18-11ea-9b62-0ac914bebeca.PNG)

**Comment by DanielnetoDotCom** [comment]
We are in circles here, you can get it from the older version.
