### ISSUE TITLE
Possible to disable showing "trending", "newest", "most popular", and "most watched" on home page?

### ISSUE THREAD

**Issue by ConnerK442** [WWBN/AVideo#2853]
I would like to use Netflix theme, but under top video instead of showing the "trending", "newest", "most popular", and "most watched" sections on top of the categories I have made, I would like to show only the category sections. Or have the category sections show up first (above "trending", etc) would be awesome.

Is this possible? Where would I need to make this change?

**Comment by akhilleusuggo** [comment]
yes , on plugins

**Comment by ConnerK442** [comment]
I found it, thank you!
