### ISSUE TITLE
How to move videos directory

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#2854]
When / var / www / runs out of storage space
Is it possible to move / var / www / html / AVideo / videos to another storage?
I am thinking of the next method.
/ dev / sda1 (original HDD)
/ dev / sdb1 (New HDD)
1.stop apache2 and mysql.
2.mount sdb2 temorary directory.
For example
mount / dev / sdb2 / temp
3.all files copy under / temp
for exmaple
cd / var / www / html / AVideo / videos
mv ./* / temp
4.umount / temp
5.mount / dev / sdb1 / var / www / html / Avideos / videos
   and add / dev / sdb1 mount line / etc / fstab
6.chown www-data: www-data / var / www / html / AVideos -R
7.start apach2 and mysql or system reboot

Please point out any mistakes.

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/Can-I-store-my-videos-in-another-location

**Comment by hnagasawa** [comment]
I have a question about your suggestion

Do I have to stop AVideo's prcess before "mv /var/www/htdocs/YouPHPTube/videos /home/videos" ?

**Comment by DanielnetoDotCom** [comment]
At least stop the video upload before move the directory, to avoid problems
