### ISSUE TITLE
Live broadcast streaming delay

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#2855]
**Describe the question**
Hi, 

I setup the AVideo Server in LAN and then do live streaming (RTMP).

The problem is when I compare Video streaming output with the video source.  
It delay about 35-40 sec.
Is it possible to reduce the latency time close to video source?

Thanks & BR,

**Comment by akhilleusuggo** [comment]
you better ask that on https://github.com/arut/nginx-rtmp-module

**Comment by guitarpound** [comment]
thx
