### ISSUE TITLE
Connection time out for live broadcast

### ISSUE THREAD

**Issue by debjit-biswas** [WWBN/AVideo#2856]
**Describe the bug**
Unable to go live. 

**To Reproduce**
1. Clicked live
2. Used server and key in OBS studio streaming setting
3. Click Start Streaming on OBS
4. Getting the error as in the screenshot

**Screenshots**
![Capture](https://user-images.githubusercontent.com/50593814/78982520-edbd8c80-7b3f-11ea-8f5f-c6c8bbc1d512.PNG)

**Error Logs**
Provide the log files at the moment you found the issue.
[avideo.log](https://github.com/WWBN/AVideo/files/4461047/avideo.log)

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Browser [e.g. chrome]

**Comment by akhilleusuggo** [comment]
not a bug ...
You miss configured your nginx server 
Working perfectly for me

https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server
