### ISSUE TITLE
New install, login page error

### ISSUE THREAD

**Issue by tokunboajewole** [WWBN/AVideo#2857]
A pleasant day to you,

Im trying our your software on a local server.

I followed the tutorial here: https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x---For-AVideo-Platform-version-3.x-or-older

in reference to this video tutorial: https://tutorials.youphptube.com/video/how-to-install-youphptube-in-a-fresh-ubuntu-server

Installation completed successfully. I can see the frontpage, but when click the login link, it results in a 404 not found page: http://ip-address/AVideo/user

1) Why is the login link reporting an error page?
2) with reference to the above, does this mean that I need to setup another server as the streamer?....as in ill need 2-servers
3) what kind of hardware requirements would you advice for a potential 20,000 viewers 

regards
ayotokunbo

**Comment by DanielnetoDotCom** [comment]
Hi, 

1. usually, the 404 error is related to a misconfiguration about the URL rewrite (google for that).
2. 1 server is fine
3. please check this https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements

**Comment by akhilleusuggo** [comment]
@tokunboajewole 
Why would you install an older version ? Anyway
1) Make sure your apache2 does have `AllowOverride All`

`sudo nano /etc/apache2/apache2.conf
`
```
<Directory /var/www/>
          Options Indexes FollowSymLinks
          AllowOverride All
          Require all granted
  </Directory>
```

`sudo a2enmod rewrite`
`sudo /etc/init.d/apache2 restart`

**Comment by tokunboajewole** [comment]
thanks for the headsup..

regards
Tokunbo
