### ISSUE TITLE
Frech install - no way tu update Image

### ISSUE THREAD

**Issue by gamersalpha** [WWBN/AVideo#2858]
Hello, 

on a audio when i try to put  image i got this error 
![image](https://user-images.githubusercontent.com/32466950/79026799-44e84f00-7b8a-11ea-8183-b4ac01d07fbb.png)

how to fix please

**Comment by akhilleusuggo** [comment]
Is not a bug , please read what is written 
You need to chmod the directory ( give permissions )
`chmod 777 /var/www/html/YouPHPTube/objects/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer`

**Comment by gamersalpha** [comment]
ok works but adding a 777 rights is not a security breach ?
