### ISSUE TITLE
can you add the ability to sell ad space?

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#2859]
**Is your feature request related to a problem? Please describe.**
can you make an ad addon to sell ad space video and banner to the users i have this on one of my other sites where the users and buy ad space monthly or by the view 

this would be great so you dont need google or any other ad company just sell ad zones and video slots 
user could set the rates they are willing to pay or admin and set defualt price oer zone

me for one i can find any ad companys willing to wrok with my site and this could fix that problem

**Comment by akhilleusuggo** [comment]
there's something similar to what you're asking , I never tried it , but I know it works . Take a look first 
![image](https://user-images.githubusercontent.com/52116577/79039261-c4a50680-7be8-11ea-99a9-2b29d2ad002d.png)

Is the first plugin on the list xD
AD_Overlay (AD_Overlay)

**Comment by DanielnetoDotCom** [comment]
Hi

We do not have payment integration yet but check this https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform
