### ISSUE TITLE
i cant do live and i cant upload video 

### ISSUE THREAD

**Issue by landydawood** [WWBN/AVideo#2860]
I did installed all with cpanel vps and system CentOS 7.7 need help to run live and upload the videos 

-installed Encoder 
-installed Encoder network 
-Installed Nginx-RTMP on CentOS 7

but still give me error when i start stream

**Comment by akhilleusuggo** [comment]
There's no support for pannels 
There's no support for centos 
You need to find your own way to make them work .

**Comment by landydawood** [comment]
i did installed in ubuntu-1804 but is not working too

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer

**Comment by landydawood** [comment]
i fallowed all think but still not working

**Comment by akhilleusuggo** [comment]
Error logs ?
If encoder , then the encoder ones 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by landydawood** [comment]
is not even accept to install the database

**Comment by akhilleusuggo** [comment]
if you don't/can't/don't wanna provide errors , please close the issue

**Comment by landydawood** [comment]
this is the error  Connect Error (2002) No such file or directory

**Comment by landydawood** [comment]
Connect Error (1698) Access denied for user 'root'@'localhost'

**Comment by landydawood** [comment]
Im stuck on this 

landy@live3:~/build/nginx-1.13.8$ sudo cp ~/build/nginx-rtmp-module/stat.xsl /usr/local/nginx/html && sudo mv /usr/local/nginx/conf/nginx.conf /usr/local/nginx/conf/nginx.conf.old && cd /usr/local/nginx/conf/ && sudo wget https://raw.githubusercontent.com/DanielnetoDotCom/YouPHPTube/master/plugin/Live/install/nginx.conf
cp: cannot create regular file '/usr/local/nginx/html': No such file or directory

**Comment by DanielnetoDotCom** [comment]
@landydawood looks like for me you are far from an installation. You are missing the MySQL and NGINX configurations. I am not sure if you skip steps or you are having other problems. I recommend to start all over in an Ubuntu 18.04 server

**Comment by landydawood** [comment]
I didnt skip ant steps and this is 9 times i strated over and have same issues

**Comment by akhilleusuggo** [comment]
Ok
1)Witch Version of ubuntu Server are you using ?
2)Are you sure that when installing you didn't get ANY errors ? I'm sure that you should have got errors that you ignored when installing nginx rtmp module .
3)Witch version of nginx-rtmp are you installing ?

**Comment by landydawood** [comment]
1)Witch Version of ubuntu Server are you using ?

ubuntu-1804

2)Are you sure that when installing you didn't get ANY errors ? I'm sure that you should have got errors that you ignored when installing nginx rtmp module .

no error 100% as lonh as i know 

3)Witch version of nginx-rtmp are you installing ?

nginx-1.13.8

**Comment by akhilleusuggo** [comment]
Before you do any of this , can you get access to http://yoursite.com:8080/stat ?
In case you use ssl , https://yoursite.com:444/stat ?

Like I told you , ngixn-1.13.8 should bring errors on ubuntu 18.04
The errors are not WRITTEN in RED , when extracting and installing the ngixn , read carefully what you're missing .
I'm talking about the step : 
`./configure --with-http_ssl_module --with-http_stub_status_module --add-module=../nginx-rtmp-module && sudo make && sudo make install`
Here you will be required to install some extra modules that doesn't come out of the box on ubuntu 18.04

The version 1.13.8 is not the optimal , I recommend 1.16.1
Try with this one , and make sure to read 
You will need to install 1 or 2 things , and you should be ready to go ( google is your friend , and easy thing , apt install blabla )

PS: Before you do any of this , can you get access to http://yoursite.com:8080/stat ?

**Comment by landydawood** [comment]
:8080/stat no access keep loading i will try 1.16.1 


and can you please adjust this code for me regaringing to 1.16.1

sudo apt-get install build-essential libpcre3 libpcre3-dev libssl-dev php7.0-xml && sudo mkdir ~/build && cd ~/build && sudo git clone git://github.com/arut/nginx-rtmp-module.git && sudo wget http://nginx.org/download/nginx-1.12.0.tar.gz && sudo tar xzf nginx-1.12.0.tar.gz && cd nginx-1.12.0 && sudo ./configure --with-http_ssl_module --with-http_stub_status_module --add-module=../nginx-rtmp-module && sudo make && sudo make install && sudo mkdir /usr/local/nginx/ssl/ && sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /usr/local/nginx/ssl/nginx.key -out /usr/local/nginx/ssl/nginx.crt && sudo /etc/init.d/apache2 restart && sudo mkdir /HLS && sudo mkdir /HLS/live

**Comment by akhilleusuggo** [comment]
Without logs , none can say what's the issue .

**Comment by landydawood** [comment]
how i can get the logs ?

**Comment by akhilleusuggo** [comment]
read the comments above ...........

**Comment by landydawood** [comment]
perfect i solved thanks alot for your help
