### ISSUE TITLE
Portrait poster

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#2863]
**Describe the question**
I have a question to ask about creating thumbnails in videos
if we look at the video editing there is the images tab
there are a total of 5 tabs
Poster (JPG)  is created ok!
Portrait Poster (JPG) is not created...
Mouse Over Poster (WebP) is created ok!
Mouse Over Poster (GIF)  is createdok!
Mouse Over Portrait Poster (GIF)  is not created...
what I want to ask is: if creating portrait poster and mouse over are created automatically?
if so why not for me?
if not I will have to upload them manually?

Thank you in advance
wetube
Happy easter to catholic!
Happy easter to orthodox next week!
**Screenshots**

![poster](https://user-images.githubusercontent.com/60543030/79065182-a0136200-7cae-11ea-8903-886c88625c72.jpg)
![over portrait](https://user-images.githubusercontent.com/60543030/79065189-ac97ba80-7cae-11ea-8566-6c3d1b70e363.jpg)

**Comment by DanielnetoDotCom** [comment]
The portrait image must be uploaded manually
