### ISSUE TITLE
How to use main/Poster image as thumbnail?

### ISSUE THREAD

**Issue by sarabhi92git** [WWBN/AVideo#2865]
Thumbnail generated on embed youtube videos is of very poor quality.
So, I want to use main image as thumbnail.
Please help me @DanielnetoDotCom @hersche @alexious where I can change in code to use poster image as thumbnail.

**Comment by DanielnetoDotCom** [comment]
Hi

from embed we do not generate thumbs, we import them.

for example if you embed a youtube video, we will try to get the thumbs from youtube. NOT generate them.

so right now there is nothing we can do, but you still can manually upload a better image.
