### ISSUE TITLE
HTTP to HTTPS autosigned

### ISSUE THREAD

**Issue by gamersalpha** [WWBN/AVideo#2867]
Hello, all

So i just installed all my youphptube and youphptubeencoder in http and works very cool

now i need a little https but with autosigned, do u now how do that  please ?

i have tried to change the config files in /var/www/html/YouPhpTube/configration.php

and i added a https

but the page show but some parts get link in htttp and other stuff in https tha'ts not good, do u hae a process please to change http to https i al link of youphptub thanks to all

**Comment by akhilleusuggo** [comment]
is this a bug ?

**Comment by gamersalpha** [comment]
i think because we can change to HTTPS without database or config files modification

no ?

**Comment by akhilleusuggo** [comment]
you can do it with apache2 or config ( both you can as well )
1) `/etc/apache2/sites-available/`
```
RewriteEngine on
RewriteCond %{SERVER_NAME} =yoursite.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
```

2) On /videos you have `configuration.php` . Remove this lines : 
```
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) {
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), FILE);
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
```

Read more about it here : 
https://github.com/WWBN/AVideo/wiki/Redirect-http-to-https

**Comment by gamersalpha** [comment]
Hello ok i tried tonight so :

Prerequis :

my avideo and encoder works perfectly with http 

now it's time to put https : 

First step create my auto signed certificat for my local server : 


```
cd  /etc/apache2/ && mkdir CertAvideo && cd CertAvideo
openssl genrsa -out avideo.key 2048
openssl req -new -key avideo.key -out avideo.csr
openssl x509 -req -days 365 -in avideo.csr -signkey avideo.key -out avideo.crt
cp avideo.crt /etc/ssl/certs
cp avideo.key /etc/ssl/private
```




`sudo nano /etc/apache2/sites-available/avideo.conf`

```
NameVirtualHost *:443
# Hôte virtuel qui écoute sur le port HTTPS 443

<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
	Redirect permanent / https://192.168.50.24

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>

<VirtualHost *:443>
          DocumentRoot /var/www/html
          
          SSLEngine On 
          SSLOptions +FakeBasicAuth +ExportCertData +StrictRequire
          
           SSLCertificateFile /etc/ssl/certs/avideo.crt
           SSLCertificateKeyFile /etc/ssl/private/avideo.key
</VirtualHost>


```
```
sudo -s
a2ensite avideo.conf
a2enmod ssl
apachectl configtest
service apache2 restart
```

**Comment by gamersalpha** [comment]
so i found to change conf u need  : 

1 -  reconfigure apache vhost 
2 - change configuration.php in videos folders
3 - change in admin pannel -- plugin -- advanced config the URL in https

with that i got audio working but not the video : 

audio works : 
![image](https://user-images.githubusercontent.com/32466950/79385539-0d521c00-7f69-11ea-9559-a97fd8cf7e1d.png)


But the video get error : 

missing photo of my video : 

![image](https://user-images.githubusercontent.com/32466950/79385583-22c74600-7f69-11ea-89d4-b259463a33b4.png)

in console we see this  : 

![image](https://user-images.githubusercontent.com/32466950/79385637-38d50680-7f69-11ea-9703-ef43289b9bdd.png)

i think that's means u have an other place to change http in https, but i can't found were ??

in my first page : 

![image](https://user-images.githubusercontent.com/32466950/79385717-573b0200-7f69-11ea-8f96-15b8179aefaa.png)

i think is samethings some http is still here : 

![image](https://user-images.githubusercontent.com/32466950/79385758-6621b480-7f69-11ea-9f87-9294bcc083ed.png)

**Comment by gamersalpha** [comment]
Hello ok i try this morning but same probléme, can't connect to my encoder site : 


![image](https://user-images.githubusercontent.com/32466950/79419569-592bb200-7fb7-11ea-9ffb-823182bb1c92.png)

this is my log encoder : 



```
stagiaire@srv-web-01:/var/www/html/YouPHPTube-Encoder/videos$ tail -f avideo.log
[15-Apr-2020 20:39:29 UTC] https://192.168.50.24/YouPHPTube/ == http://192.168.50.24/YouPHPTube/
[15-Apr-2020 20:39:29 UTC] https://192.168.50.24/YouPHPTube/ == http://localhost/AVideo/
[15-Apr-2020 20:39:29 UTC] https://192.168.50.24/YouPHPTube/ == http://127.0.0.1/AVideo/
[15-Apr-2020 20:39:29 UTC] https://192.168.50.24/YouPHPTube/ == https://localhost/AVideo/
[15-Apr-2020 20:39:29 UTC] https://192.168.50.24/YouPHPTube/ == https://127.0.0.1/AVideo/
[16-Apr-2020 05:47:28 UTC] https://192.168.50.24/YouPHPTube/ == http://192.168.50.24/YouPHPTube/
[16-Apr-2020 05:47:28 UTC] https://192.168.50.24/YouPHPTube/ == http://localhost/AVideo/
[16-Apr-2020 05:47:28 UTC] https://192.168.50.24/YouPHPTube/ == http://127.0.0.1/AVideo/
[16-Apr-2020 05:47:28 UTC] https://192.168.50.24/YouPHPTube/ == https://localhost/AVideo/
[16-Apr-2020 05:47:28 UTC] https://192.168.50.24/YouPHPTube/ == https://127.0.0.1/AVideo/
[16-Apr-2020 05:50:30 UTC] https://192.168.50.24/YouPHPTube/ == http://192.168.50.24/YouPHPTube/
[16-Apr-2020 05:50:30 UTC] https://192.168.50.24/YouPHPTube/ == http://localhost/AVideo/
[16-Apr-2020 05:50:30 UTC] https://192.168.50.24/YouPHPTube/ == http://127.0.0.1/AVideo/
[16-Apr-2020 05:50:30 UTC] https://192.168.50.24/YouPHPTube/ == https://localhost/AVideo/
[16-Apr-2020 05:50:30 UTC] https://192.168.50.24/YouPHPTube/ == https://127.0.0.1/AVideo/

```

what do u think please ?

**Comment by DanielnetoDotCom** [comment]
In the encoder, you allow the site http://192.168.50.24/YouPHPTube/ but you did NOT allow the https site https://192.168.50.24/YouPHPTube/

you may need to edit your configuration database, or you can reinstall the encoder.

**Comment by gamersalpha** [comment]
ok so now, i found the way without reinstall evrythink

so i m using this progrom to modifie data in database : 
https://www.adminer.org/

when u connect on database u have to modifie : 

![youphptuberecord](https://user-images.githubusercontent.com/32466950/79486584-329d6380-8017-11ea-8a46-dfea13d97799.gif)

configuration streamer

and that's works 

crazy!!!

to close this topics 

this is my youphptube on local server working with autosigned ssl  
![avideoDemoHttps](https://user-images.githubusercontent.com/32466950/79486909-b6efe680-8017-11ea-9845-de876a8c5e65.gif)

**Comment by akhilleusuggo** [comment]
I still don't know why would you want an self-signed certificate in localhost ...

**Comment by gamersalpha** [comment]
Any site should be secure even in LAN network, if you don't get into the habit of doing it even for local, it's a bad habit

so used to do your tutorials with https

**Comment by gamersalpha** [comment]
Ok just for record for me

u can use a let's encrypt ssl valid certificat on u lan server, without put the server on internet !!

U have to use DNS record with let's encrypt and get a local netwokr server with valid ssl  :)
that's very nice
