### ISSUE TITLE
Japaneseization of Avideo-Encoder menuAvideo-Encoder 

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#2868]
I'd like to change the part enclosed by the red line to Japanese, but please tell me which file I should edit.
![9](https://user-images.githubusercontent.com/46562199/79193294-4b661780-7e65-11ea-9f54-8fe099acbb7e.png)

**Comment by DanielnetoDotCom** [comment]
The encoder does not have a translation file yet.
the only way is to change the source code.

**Comment by hnagasawa** [comment]
Please tell me which name is  the source.

**Comment by DanielnetoDotCom** [comment]
If you are able to change the source code, you MUST be able to identify where the strings come from.

**Comment by hnagasawa** [comment]
I have been looking at all the php files of AVideo-Encoder since yesterday. Under which directory is the source code you speak of?
