### ISSUE TITLE
I am getting error in encoder while embedding youtube link to encoder.

### ISSUE THREAD

**Issue by sarabhi92git** [WWBN/AVideo#2869]
I am getting error in encoder while embedding youtube link to encoder.

> [14-Apr-2020 07:50:14 UTC] getTitleFromLink: Get Title Error: LC_ALL=en_US.UTF-8 /usr/local/bin/youtube-dl  --no-check-certificate --no-playlist --force-ipv4 --skip-download -e "https://www.youtube.com/watch?v=PbWlXbEF2bo" 
Array
(
    [0] => ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
)

> [14-Apr-2020 07:50:14 UTC] youtubeDl::addVideo We could not get the title () of your video (https://www.youtube.com/watch?v=PbWlXbEF2bo)

Please help me @DanielnetoDotCom @hersche @alexious

**Comment by sarabhi92git** [comment]
But when I use bulk embed option using API key it works perfectly.
What is understand that youtube is blocking when request sent as IPv4 through youtube-dl.
What is the solution for it.
Or if not any solution then how can I use youtube API key when embeding single video link.

![Capture](https://user-images.githubusercontent.com/58163405/79216002-13150800-7e6a-11ea-8344-c9d0b69c3e66.PNG)

**Comment by DanielnetoDotCom** [comment]
they are completely different things.

and the encoder error for me is clear.

`ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by sarabhi92git** [comment]
How can I resolve my issue? please help me

**Comment by DanielnetoDotCom** [comment]
This is an YouTube-dL error

I don’t think you can fix that, that is a YouTube limitation and you will have to wait for the next day. Try to google for that you may find something

**Comment by akhilleusuggo** [comment]
Try to upgrade youtube-dl , 
If you're upgraded and still getting this error , means you're **temporary banned**

**Comment by sarabhi92git** [comment]
**temporary banned** -> what is the time frame for this to lift the ban by YouTube

**Comment by akhilleusuggo** [comment]
depends of the ''quality IP''
Read more here . 
https://github.com/ytdl-org/youtube-dl#http-error-429-too-many-requests-or-402-payment-required

**Comment by sarabhi92git** [comment]
Which IP is getting blocked network IP or my server IP on which my website is hosted?

I have tried changing the internet connection but same error getting.

**Comment by DanielnetoDotCom** [comment]
@sarabhi92git you should google for that .

You are looking for answers in the wrong place.

**Comment by sarabhi92git** [comment]
Okay Thanks @DanielnetoDotCom and @akhilleusuggo for responding my query.

I'll find some solution for the same.
