### ISSUE TITLE
how to play m3u8 videos on my other websites

### ISSUE THREAD

**Issue by RajdipRoy** [WWBN/AVideo#2870]
Hi there , 

How to play m3u8 videos only on my websites e.g mydomain.com and domain.com but should not playable out side of my websites . do i need to change ipWhitelist with my domain name in videoHSL plugin ?  so i can play m3u8 link e.g https://mydomain.xyz/videos/_YPTuniqid_5e95fa56324af4.54612927/index.m3u8 .currently it is showing  ["127.0.0.1","localhost"] .. do i need to change this in order to play m3u8 videos only on my websites like mydomain.com and domain.com ?

**Comment by DanielnetoDotCom** [comment]
You are talking about this

![image](https://user-images.githubusercontent.com/18009293/79271241-db13c200-7e75-11ea-9a24-a9cae7484379.png)

this is for the download protection, usually, we use it to Whitelabel the encoder.

if you have the downloadProtection enabled you can not directly play the m3u8 file in other websites, but you can use an embed code from your site.

you can use the SecureVideosDirectory plugin to allow only some sites to embed your code.
![image](https://user-images.githubusercontent.com/18009293/79271499-478ec100-7e76-11ea-9a46-b3f5146f3e5a.png)

so for me, the best option is to leave the downloadProtection enabled and whitelist the site you want to embed a player.

![image](https://user-images.githubusercontent.com/18009293/79271705-a3f1e080-7e76-11ea-9410-a58a3faee25c.png)

**Comment by RajdipRoy** [comment]
Thanks . i got it now . thank you once again
