### ISSUE TITLE
Email configuration error 

### ISSUE THREAD

**Issue by shebanet** [WWBN/AVideo#2871]
Under email configuration, after inputting smtp information and testing it’s not working. Getting error message saying “Your message could not be sent!
Message could not be sent (SMTP connect() failed.”

**Comment by DanielnetoDotCom** [comment]
Make sure you follow this https://github.com/WWBN/AVideo/wiki/Setting-up-AVideo-Platform-to-send-emails

and if fails also check this https://github.com/WWBN/AVideo/issues/2797

**Comment by shebanet** [comment]
Do I have to use Gmail server? I can’t use any other email service provider?

Thanks,
Joseph

202.746.9674
________________________________

**Comment by DanielnetoDotCom** [comment]
you can use any, as long they provide the SMTP to you.

**Comment by fvlasie** [comment]
I found that my installation needed postfix installed before it could send email.

**Comment by DanielnetoDotCom** [comment]
a postfix is an option. But for myself, I always set up the Gmail SMTP without postfix

**Comment by shebanet** [comment]
Boss, you have to trust me here. I know how to setup smtp. I have setup smtp on numerous devices (phones, web apps ect.). However, I have tried hundreds of times to setup on this app and it is failing. I tried troubleshooting. I even tried other emails servers (I have several emails on different domains). It is still not working. I seriously believe there is a bug somewhere. Please trust me and dig a little further.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by shebanet** [comment]
Wait, so postfix installation is REQUIRED for the smtp settings to work?

**Comment by DanielnetoDotCom** [comment]
postfix is NOT necessary!!!!

what SMTP server are you using?

check your streamer log files.

**Comment by shebanet** [comment]
I am using Network Solutions

**Comment by DanielnetoDotCom** [comment]
I do not know them, check your streamer log files.

**Comment by shebanet** [comment]
Sorry, where do I find that?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by shebanet** [comment]
[15-Apr-2020 18:45:39 UTC] updateFilesize: Not updated, this filetype is embed
[15-Apr-2020 18:45:39 UTC] updateFilesize: Not updated, this filetype is embed
[15-Apr-2020 18:45:39 UTC] updateFilesize: Not updated, this filetype is embed
[15-Apr-2020 18:45:39 UTC] updateFilesize: Not updated, this filetype is embed
[15-Apr-2020 18:45:39 UTC] updateFilesize: Not updated, this filetype is embed
[15-Apr-2020 18:45:39 UTC] updateFilesize: Not updated, this filetype is embed
[15-Apr-2020 18:50:16 UTC] sendEmail: Message could not be sent (SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting)

**Comment by DanielnetoDotCom** [comment]
what is your SMTP server?

what ports are you using?

are you sure they are correct?

**Comment by abkiwi9** [comment]
I have a new install 2 days ago and have tried to add my SMTP account settings and the site can't send out any email "FAILED"

I use SMTP2go and have checked all setting and tested the account settings and it works but does not work in youPHP.Tube new install?

Regards
Aaron

**Comment by DanielnetoDotCom** [comment]
make sure your server can connect in the SMTP server. use telnet in the SMTP port.

**Comment by abkiwi9** [comment]
Hi Daniel, thanks, can you tell me how to do this?  I paid to have my server installed so it would be all working to save me some time having to learn all this extra stuff. :)

**Comment by DanielnetoDotCom** [comment]
@abkiwi9 what is your URL?

**Comment by abkiwi9** [comment]
reelBox.net

**Comment by shebanet** [comment]
I am in same situation as Aaron. Like I told you before I have numerous devices and web applications that are using the very same external SMTP settings. There’s nothing wrong with my settings. I spent eight hours yesterday fiddling and Tinkering and troubleshooting and I got nowhere. I eventually gave up. Just for curiosity I tried my personal Gmail and it worked. This is not what I expected. I certainly have no interest in using my personal Gmail account to run a business enterprise.

**Comment by DanielnetoDotCom** [comment]
@abkiwi9 what is your SMTP server? what port are you using?

please screenshot your configuration screen.

**Comment by abkiwi9** [comment]
SMTP Server:  mail.smtp2go.com
Port: 465. SSL

**Comment by DanielnetoDotCom** [comment]
@abkiwi9 yes, your smtp server is responding.

check the credentials, that is the only thing that may be failing.

**Comment by DanielnetoDotCom** [comment]
@shebanet your SMTP is also responding.

you guys may check your credentials, and if still fail look into your SMTP server log, to see why it is not authenticating.

also try to change the authentication method from SSL to TLS and vice versa.

**Comment by shebanet** [comment]
Nothing wrong with credentials as I’ve said multiple devices web apps are using the same credentials

**Comment by shebanet** [comment]
I think I figured out the great mystery. Stand by

**Comment by DanielnetoDotCom** [comment]
@shebanet I just look into your server and YES there is something on the log file that give us a clue

`sendEmail: Message could not be sent (SMTP Error: data not accepted.SMTP server error: DATA END command failed Detail: STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. 0.35250:FE0A0000, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:3F020000, 1.36674:0E000000, 1.61250:00000000, 1.45378:44020000, 1.44866:80010000, 16.55847:2A040000, 17.43559:0000000024020000000000000000000000000000, 20.52176:140F698B1800001000000000, 20.50032:140F698B8817001000000000, 0.35180:F1030000, 255.23226:0 SMTP code: 554 Additional SMTP info: 5.2.0)`

I am pretty sure it comes from your side

**Comment by DanielnetoDotCom** [comment]
@abkiwi9 you please double check your SMTP credentials and look for a log in your SMTP server

**Comment by shebanet** [comment]
I’ve narrow down the problem. Web client is using my personal email to send on behalf. Email server is rejecting because that personal email is not authorized to send on behalf. I have to either authorize that email in email server side or change sender email at web client side. I prefer the latter. Where can I update the senders email in the system?

**Comment by akhilleusuggo** [comment]
don't use port 465 , instead use 587 tls , and on google security enable '' allow less secure application '' , add your server ip to white listed .

**Comment by shebanet** [comment]
I’m not using Google. If you can just tell me where I can change the system email used during install I will be happy.

**Comment by shebanet** [comment]
In other words, I need to change the sender’s (From) email

**Comment by DanielnetoDotCom** [comment]
change the sender here 

![image](https://user-images.githubusercontent.com/18009293/79494327-34582e80-7ff9-11ea-89b4-41bb68a89b92.png)

**Comment by shebanet** [comment]
Oh sorry, I should have seen that. I was expecting to hardcode it. Fixed! Everything is working now.

**Comment by shebanet** [comment]
Conclusion: If SMTP user email is different then sender (from) email than sender (from) email needs to be authorized by email server to send on behalf

**Comment by abkiwi9** [comment]
Thanks, everyone for working this out and advising the best ports to use.  Something so simple, maybe add this to your support instruction page :) it took hours of testing.

Regards
Aaron

**Comment by DanielnetoDotCom** [comment]
@abkiwi9 does it works for you also?

what ports?

**Comment by abkiwi9** [comment]
Hi Daniel, Yes it works if you make the email address the same as the domain name and port 587 tls works but port 465 does not work.  I tested port 25 and 2525 with my first email address (different domain) and it does not work.

Hope this helps.

Regards
Aaron
