### ISSUE TITLE
Theme colour change

### ISSUE THREAD

**Issue by abkiwi9** [WWBN/AVideo#2872]
I need to change the default theme colours, how do I do this?

Is there a file I can copy the code to change the colour numbers?
(sidemenu, play button and video play line)

Thanks
Regards
Aaron

**Comment by DanielnetoDotCom** [comment]
Hi, this is a bootstrap 3 layout.

you can google for that to find what class you need to change to add customized colors.

once you have your customized CSS you can follow this https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css
