### ISSUE TITLE
live-stream to sitemap

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2873]
Adding live-stream to sitemap .
Search engines are not able to crawl the live stream urls

**Comment by DanielnetoDotCom** [comment]
Usually, live streams are temporary, are you sure it is a good idea?

when google crawl it, Google may fins something different with no video. so it will be a lost link on the search

**Comment by akhilleusuggo** [comment]
I've been reading the google crawling , but I'm not sure the sitemap script Avideo uses does have the proper properties when it comes to sitemap . Make errors on webmaster ( google ).
On the search result , the videos on left side ( look pic below ) , are crawled for some reason .
![image](https://user-images.githubusercontent.com/52116577/79401524-fecc2a80-7f91-11ea-91bc-4ab13652d6c1.png)
But crawled as description in many cases .

About live-streams , this is the right article : 
https://developers.google.com/search/apis/indexing-api/v3/quickstart
https://developers.google.com/search/docs/data-types/video#livestream-guidelines

But I don't know if that can be done .
Can you guide me to the source script of the sitemap creator ?

**Comment by DanielnetoDotCom** [comment]
Hi

I do not understand what error are you referring to.

that is the function that creates the sitemap

https://github.com/WWBN/AVideo/blob/10c48efed0b89307513384c06e5c94d422403c07/objects/functions.php#L1929

**Comment by akhilleusuggo** [comment]
check the email 👍
