### ISSUE TITLE
No stream key

### ISSUE THREAD

**Issue by fvlasie** [WWBN/AVideo#2875]
Platform: Ubuntu 19

**Screenshots**
<img width="572" alt="Screen Shot 2020-04-15 at 9 33 20 AM" src="https://user-images.githubusercontent.com/33334298/79364910-d21b0300-7efe-11ea-859f-a2250bc9be6a.png">

**Desktop:**
 - OS: MacOS 10.15.4 Catalina
 - Browser Chromium and Safari
 - Version Latest of both

There is no stream key showing, when I click Reset Key it just reloads the page. The only thing I am doing differently is running Apache with SSL (Let'sEncrypt).

Thank you!

**Comment by DanielnetoDotCom** [comment]
Looks like you are missing something in the database.

please check your streamer log files.

**Comment by fvlasie** [comment]
Thank you you for your quick answer!
I am not sure where the streamer logs are located. Am I looking for php logs?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by fvlasie** [comment]
Aha! We seem to have a problem:
```
[15-Apr-2020 16:32:59 UTC] [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'aVideo.live_transmitions' doesn't exist<br>
SELECT * FROM live_transmitions WHERE  users_id = ? LIMIT 1
[15-Apr-2020 16:32:59 UTC] Save error, table live_transmitions does not exists
```

**Comment by DanielnetoDotCom** [comment]
yes, your database was not correctly installed.

**Comment by fvlasie** [comment]
I found the problem thanks to your help. I just needed to click the "Install tables" button below:

<img width="915" alt="Screen Shot 2020-04-15 at 11 53 05 AM" src="https://user-images.githubusercontent.com/33334298/79376968-d1d73380-7f0f-11ea-9e75-4efc0c1edfe9.png">

**Comment by fvlasie** [comment]
Thank you Daniel for your help and a great software project!
