### ISSUE TITLE
Poster Image (JPG) Not Displaying

### ISSUE THREAD

**Issue by I-See-Ninjas** [WWBN/AVideo#2876]
**Describe the bug**
When I upload an MP4 video via the Direct Upload, then upload the Poster Images (JPG and GIF) as part of adding the video to the system, they are not displayed on any of the public pages. The PlaceHolder.jpg is the only image displayed. When you mouse over the video, my uploaded GIF image does display.

I have also Embedded 2 videos from YouTube and the same issue with those videos as well.

When you Edit any video, the Poster uploaded is properly displayed.

The videos are already encoded for Facebook and Instagram, which is why I am uploading them directly. I tried to use the Encode Video Link (public encoder) as part of my troubleshooting, but it came up and said that I don't have an account and didn't provide a link in which to open an account

AVideo is installed on a HostGater hosting account, so there is no access to any Linux Shell. My only access is via FTP and cPanel.

**Expected behavior**
The Poster Image should be displayed for the video and not the PlaceHolder image.

**Desktop (please complete the following information):**
 - OS: Win7 Pro, Win10 Pro, Ubuntu 16.04LTS
 - Browser: Firefox
 - Version: 70.0.1

**Smartphone (please complete the following information):**
 - Device: iPhone10, Samsung S9+
 - OS: Unsure of iOS version (friend's phone), Android 10
 - Browser: iPhone- likely Safari (friend's phone), Android- Firefox, DuckDuckGo, stock
 - Version: unkown

**Screenshots**
![20  04-15-20 @ 13,59,49_1920x1080_e](https://user-images.githubusercontent.com/63745856/79377728-c260e600-7f21-11ea-8a0a-f53dd53f098c.jpg)
![20  04-15-20 @ 14,00,20_1920x1080_e](https://user-images.githubusercontent.com/63745856/79377733-c3921300-7f21-11ea-820c-8e5a41007dbb.jpg)

**Comment by DanielnetoDotCom** [comment]
what version are you using?

check the log files.

**Comment by I-See-Ninjas** [comment]
AVideo v8.6. I just downloaded and installed it 2 days ago.

**Comment by DanielnetoDotCom** [comment]
Log files?

**Comment by I-See-Ninjas** [comment]
The log files don't show anything.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Me too I wanna know why this happens , even on the main website ( avideo ) , happens . Example : 
https://avideo.com/video/97/sample-from-beta-server?channelName=Julius

I've seen it today on my site as well . The files does exist , and on video's option the jpg, gif & webp display , but not on the page .

**Comment by I-See-Ninjas** [comment]
This is what I found in the avideo.log file that I pulled via FTP. 

This the the video that I uploaded just before submitting the bug report. This is an MP4 that was a Direct Upload. Once it was uploaded, I added the Poster IMages (JPG & GIF). The only error I see is because there are no Tags assigned to the video.

**---------- LOG SEGMENT BEGIN ----------**
[15-Apr-2020 12:00:12 America/Detroit] PHP Warning:  Invalid argument supplied for foreach() in /home/******/******/avideo-20/plugin/VideoTags/VideoTags.php on line 46
[15-Apr-2020 12:00:12 America/Detroit] getUsageFromFilename: start /home/******/******/avideo-20/videos/video_5e972f8c390b3
[15-Apr-2020 12:00:12 America/Detroit] updateFilesize: No need to update videos_id=5 filename=video_5e972f8c390b3 filesize=0
[15-Apr-2020 12:00:12 America/Detroit] getUsageFromFilename: start /home/******/******/avideo-20/videos/video_5e972f8c390b3
[15-Apr-2020 12:00:12 America/Detroit] updateFilesize: No need to update videos_id=5 filename=video_5e972f8c390b3 filesize=0
[15-Apr-2020 12:00:54 America/Detroit] decideMoveUploadedToVideos: THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339.mp4
[15-Apr-2020 12:00:54 America/Detroit] decideMoveUploadedToVideos: NOT ZIp file THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339.mp4
[15-Apr-2020 12:00:54 America/Detroit] decideMoveUploadedToVideos: Local THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339.mp4
[15-Apr-2020 12:00:54 America/Detroit] getUsageFromFilename: start /home/******/******/avideo-20/videos/THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339
[15-Apr-2020 12:00:54 America/Detroit] getUsageFromFilename: /home/******/******/avideo-20/videos/THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339.mp4 is File (10304387)
[15-Apr-2020 12:00:54 America/Detroit] updateFilesize: videos_id=5 filename=THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339 filesize=10304387
[15-Apr-2020 12:02:13 America/Detroit] PHP Warning:  Invalid argument supplied for foreach() in /home/******/******/avideo-20/plugin/VideoTags/VideoTags.php on line 46
[15-Apr-2020 12:02:24 America/Detroit] modeYoutube: session_id = gb7b6qq3fir4sj1tah10v4p1d5 IP = 98.156.226.84
[15-Apr-2020 12:03:34 America/Detroit] modeYoutube: session_id = gb7b6qq3fir4sj1tah10v4p1d5 IP = 98.156.226.84
[15-Apr-2020 12:05:45 America/Detroit] Try to move /home/******/******/avideo-20/videos/THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339.jpg 
 Video Object
(
    [id:Video:private] => 5
    [title:Video:private] => THJ- Student Video- Haas & Messan (Shenanigans)
    [clean_title:Video:private] => thj--student-video--haas-messan-shenanigans-
    [filename:Video:private] => THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339
    [description:Video:private] => 
<p>THJ- Student Video- Haas &amp; Messan (Shenanigans)- 02-29-20</p>

    [views_count:Video:private] => 1
    [status:Video:private] => a
    [duration:Video:private] => 0:00:42
    [users_id:Video:private] => 2
    [categories_id:Video:private] => 1
    [old_categories_id:Video:private] => 
    [type:Video:private] => video
    [rotation:Video:private] => 0
    [zoom:Video:private] => 1
    [videoDownloadedLink:Video:private] => 
    [videoLink:Video:private] => 
    [next_videos_id:Video:private] => 
    [isSuggested:Video:private] => 0
    [videoGroups:Video:private] => 
    [trailer1:Video:private] => 
    [trailer2:Video:private] => 
    [trailer3:Video:private] => 
    [rate:Video:private] => 0
    [can_download:Video:private] => 0
    [can_share:Video:private] => 0
    [only_for_paid:Video:private] => 0
    [rrating:Video:private] => 
    [externalOptions:Video:private] => {"videoStartSeconds":"00:00:00"}
    [sites_id:Video:private] => 
    [serie_playlists_id:Video:private] => 
    [video_password:Video:private] => 
    [encoderURL:Video:private] => 
    [filepath:Video:private] => 
    [filesize:Video:private] => 10304387
    [youtubeId:Video:private] => 
    [views_count_25] => 1
    [views_count_50] => 1
    [views_count_75] => 1
    [views_count_100] => 1
    [created] => 2020-04-15 12:00:12
    [modified] => 2020-04-15 12:03:20
    [order] => 1
)

[15-Apr-2020 12:06:24 America/Detroit] PHP Warning:  Invalid argument supplied for foreach() in /home/******/******/avideo-20/plugin/VideoTags/VideoTags.php on line 46
[15-Apr-2020 12:06:33 America/Detroit] Resize JPG /home/******/******/avideo-20/videos/THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339.jpg, /home/******/******/avideo-20/videos/THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339_thumbsV2.jpg
[15-Apr-2020 12:06:33 America/Detroit] Resize Small JPG /home/******/******/avideo-20/videos/THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339.jpg, /home/******/******/avideo-20/videos/THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339_thumbsSmallV2.jpg
[15-Apr-2020 12:08:26 America/Detroit] Try to move /home/******/******/avideo-20/videos/THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339.gif 
 Video Object
(
    [id:Video:private] => 5
    [title:Video:private] => THJ- Student Video- Haas & Messan (Shenanigans)
    [clean_title:Video:private] => thj--student-video--haas-messan-shenanigans-
    [filename:Video:private] => THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339
    [description:Video:private] => 
<p>THJ- Student Video- Haas &amp; Messan (Shenanigans)- 02-29-20</p>

    [views_count:Video:private] => 1
    [status:Video:private] => a
    [duration:Video:private] => 0:00:42
    [users_id:Video:private] => 2
    [categories_id:Video:private] => 1
    [old_categories_id:Video:private] => 
    [type:Video:private] => video
    [rotation:Video:private] => 0
    [zoom:Video:private] => 1
    [videoDownloadedLink:Video:private] => 
    [videoLink:Video:private] => 
    [next_videos_id:Video:private] => 
    [isSuggested:Video:private] => 0
    [videoGroups:Video:private] => 
    [trailer1:Video:private] => 
    [trailer2:Video:private] => 
    [trailer3:Video:private] => 
    [rate:Video:private] => 0
    [can_download:Video:private] => 0
    [can_share:Video:private] => 0
    [only_for_paid:Video:private] => 0
    [rrating:Video:private] => 
    [externalOptions:Video:private] => {"videoStartSeconds":"00:00:00"}
    [sites_id:Video:private] => 
    [serie_playlists_id:Video:private] => 
    [video_password:Video:private] => 
    [encoderURL:Video:private] => 
    [filepath:Video:private] => 
    [filesize:Video:private] => 10304387
    [youtubeId:Video:private] => 
    [views_count_25] => 1
    [views_count_50] => 1
    [views_count_75] => 1
    [views_count_100] => 1
    [created] => 2020-04-15 12:00:12
    [modified] => 2020-04-15 12:06:24
    [order] => 1
)

[15-Apr-2020 12:08:38 America/Detroit] PHP Warning:  Invalid argument supplied for foreach() in /home/******/******/avideo-20/plugin/VideoTags/VideoTags.php on line 46
[15-Apr-2020 12:08:46 America/Detroit] Resize JPG /home/******/******/avideo-20/videos/THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339.jpg, /home/******/******/avideo-20/videos/THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339_thumbsV2.jpg
[15-Apr-2020 12:08:46 America/Detroit] Resize Small JPG /home/******/******/avideo-20/videos/THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339.jpg, /home/******/******/avideo-20/videos/THJStudentVideoHaasMessanShenanigans022920sat120pmwtxtmp4_5e972fb641dda4.36410339_thumbsSmallV2.jpg

**---------- LOG SEGMENT END ----------**

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo https://avideo.com/ runs an older version. 

please check if you can reproduce it on the demo site.

I fixed something related to this, a few days ago, and it was about the cache. that is why I insist you to make sure if your site is updated.

after update try to edit the video to clear its cache.

I just sent an update to make sure it will clear images cache when you update the video

**Comment by I-See-Ninjas** [comment]
Update what? 

I do not understand what you are asking me to update. 

If you are asking to update the Video, I have done that many times over changing various aspects of the videos as well as the Posters (JPG, GIF). This was part of my preliminary testing.

**Comment by akhilleusuggo** [comment]
@I-See-Ninjas update the script `git pull `
more info : https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by I-See-Ninjas** [comment]
There have been updates since a few days ago?

I downloaded and installed at the beginning of this week from Github.

**Comment by I-See-Ninjas** [comment]
Thank you @akhilleusuggo 

I downloaded the master.zip and found the video.php file that was updated in the objects directory and got it updated in my system.

I will go in to each of the videos and replace the Poster for each of the videos to refresh the cache for that video unless there is a way to clear all of the system cache and let it rebuild when it loads the first time after the clear.

**Comment by I-See-Ninjas** [comment]
I have gone in and updated all of the videos by replacing all of the Posters (JPG, GIF) for each video. The Embeded videos from YoutTube, I have saved those JPGs, and created GIFs from them and uploaded them for those videos as well.

** Results **
No change from the original screenshots. Some of the Posters (JPG or GIF) for the perspective video did not update with the new images. I used new images for each of the videos to see if they were actually being updated or not.

The issue still remains as originally posted with the screenshots.

**Comment by akhilleusuggo** [comment]
@I-See-Ninjas check the log files when you upload the images and pressing save .
If there's any errors will be displayed on the log files .
Regarding the latest update : https://github.com/WWBN/AVideo/commit/a2d2ec467810199f88235ef4e74feb326d9fd421

Replace only the objects/video.php , the script should do the rest , no need to do anything else .

**Comment by DanielnetoDotCom** [comment]
@I-See-Ninjas I strongly recommend you use `git clone` command instead download the master.zip

are you using Ubuntu?

**Comment by I-See-Ninjas** [comment]
@akhilleusuggo 
I will check the logs and post what I see. I did extract the video.php from the master.zip and replaced that single file. it was easy to find on github because of the time stamps on the files/folders

@DanielnetoDotCom 
I do know that the server is a Linux machine. I don't know the details of that server because it belongs to my hosting provider. I don't have shell access to the server. I can only manipulate my web space through cPanel and FTP, so I can't run any Linux/Ubuntu commands.

**Comment by DanielnetoDotCom** [comment]
that may be the problem, we do NOT support cPanel, to make it work you must figure it out by yourself.

**Comment by akhilleusuggo** [comment]
that explains it

**Comment by I-See-Ninjas** [comment]
@DanielnetoDotCom 
@akhilleusuggo 

Updating the files manually via FTP shouldn't be any different than through using any git commands. The process of replacing a file/directory with an updated file/directory should shouldn't any effect on the functionality of the system or that file's ability to do it's job within the overall system. The host provider exceeds all of the requirements of the server in terms of MySQL Database and PHP Versions.

I have many other PHP Scripts and PHP Software running on my same domain and I have zero issues adding/updating/modifying any files in the system. I typically do file updates, such as this, via FTP. I can even make minor entry changes to the MySQL Databases via MyPHP with no issues.

To say that the issue I'm having is due to not being able to run a Linux command to get updated files when I can easily grab the files from GitHub and update them via FTP is not a very good response to this bug report. The process used to update the files in the script have no bearing on the functionality of the script.

Please don't take me a being combative. I love the software and love what you have built and I absolutely want to build it in to my services along with Subscriptions with Stripe and everything else. It's fantastic software and the work you have done to this point has been excellent. I am just trying to get this piece of functionality resolved.

If this is a site cache issue, then is there somewhere in the settings I can clear the cache and let it rebuild on it's own or a directory that I can go and clear out?

**Comment by akhilleusuggo** [comment]
Is not about the git or not git . It's about Cpanel .

**Comment by I-See-Ninjas** [comment]
@akhilleusuggo 
The only thing I use cPanel for is for creating email addresses, creating databases, updating my SSL Certs, updating PHP versions, creating/editing cron jobs, and accessing my hosting account (tech support, billing, etc). I have reached out to the hosting tech support people which distro is running on the server my domain is on. Here is the server information they provided.

Red Hat 4.8.2-15
Apache Version 2.2.31
Architecture x86_64
PHP Version 7.0.29
MySQL Version 5.6.41-84.1

My comment regarding cPanel was to say that it's really the only interface I have outside of using FTP. I primarily use FTP to pull files, edit them locally, the upload them. Any HTML, CSS, PHP edits I have done on any of my other stuff, it's been done via FTP Download > Edit Locally > FTP Upload.

**Comment by akhilleusuggo** [comment]
do you have direct access to the server ?
Can you use command lines ?

**Comment by I-See-Ninjas** [comment]
@akhilleusuggo 
I do not have any command line access. I really only have access to the file structure and MySQL databases. When I manually access the databases, it's through phpMyAdmin, which is very rare that I need to. My typical access to the file structure is via FTP, which is my choice. My PHP version used by xyz domain is done via the .htaccess file.

**Comment by akhilleusuggo** [comment]
that's the problem 
You can't change permission , you can't customize anything .

**Comment by I-See-Ninjas** [comment]
@akhilleusuggo 
The permission for my account (file structure) is full read/write. The script is housed and runs within the public_html section of my space, which also has read/write permissions. What other permissions would I need?

Right now, everything about the script/software runs with no problems. This is the only issue that I'm having, which is it NOT displaying the Poster and displaying the PlaceHolder instead. That doesn't seem like an issue outside of the script. It has no problems displaying the MouseOverPoster.

**Comment by I-See-Ninjas** [comment]
@DanielnetoDotCom 
@DanielnetoDotCom 

--- UPDATE & ADDITIONAL INFO ---

When I directly upload an MP4 video, then add the Poster (JPG) and Mouse Over Poster (GIF), then the VideoPlaceHolder.jpg image is shown for the video on any of the pages. When I Mouse Over the video, the Mouse Over Poster (GIF) will display, then it goes back to displaying the VideoPlaceholder.jpg image.

If I upload a copy of the VideoPlaceHolder.jpg image (landscape version), in to the Portrait Poster (JPG) position for the videos, then go back to the Home Page, the Poster (JPG) and Mouse Over Poster (GIF) I uploaded for each video displays properly.


![20  04-24-20 @ 20,32,59_1432x924_](https://user-images.githubusercontent.com/63745856/80268222-08792080-866b-11ea-8f35-887041b9bf77.jpg)
