### ISSUE TITLE
Password Control APP

### ISSUE THREAD

**Issue by abkiwi9** [WWBN/AVideo#2877]
I would like to suggest an APP or change to the main system for better password control for users.

The control to be set by the admin for users should contain the following:

1. Use upper case letters
2. Use lower case letters
3. Use numbers
4. User symbols such as: ! # $ % [ ] ( ) * etc...
5. Not use: admin to add any number, letter or text
6. Set password length:  a number

This would help a lot with security to the site for users that don't want to use social media login accounts, as I am one of them.

Regards
Aaron

**Comment by akhilleusuggo** [comment]
If you just wanna ''allow'' the use of 

> ! # $ % [ ] ( ) *

You can use utf8 or utf8mb4 on the database , and will have np
If you wanna make it as an ''requirement'' , then yes need to add some codes

**Comment by abkiwi9** [comment]
Thanks akhilleusuggo for the suggestion and this is working.

The most important part is to control users passwords so their accounts don't get hacked and make the site look bad.  With the way "they" want to start controlling the world and you don't have a very strong password, your information is going to get taken down.  I think this is very important these days so this would be a needed addon.

**Comment by akhilleusuggo** [comment]
@abkiwi9 That's not totally true , with captcha you already blocking brute force on password . 
First need username , then password + Resolving captcha . The hacking nowadays is more around database and bridges then brute forces

**Comment by abkiwi9** [comment]
Thanks, akhilleusuggo, and totally understand with what you are saying.  However, if someone has a username as there first name and a password 123 then this is much easier to hack, it just makes sense to make it harder to get in.

**Comment by akhilleusuggo** [comment]
I understand you perfectly , but that guy is saying LOUDLY : HERE I'M , PLEASE SOMEONE HACK ME!
But , I agree with you , this option could be good .
