### ISSUE TITLE
Subscription Plans

### ISSUE THREAD

**Issue by abkiwi9** [WWBN/AVideo#2878]
I am trying to set up Subscription Plans for my new site.

I can only see plans can be created based on days or groups only, but how to make Subscription Plans based on the number of uploads or data size uploaded?  The number of uploads or data size used makes it easier to control customers usage and to charge them the right cost to cover data storage and bandwidth.

I purchased the Subscription Plans APP but this is just for groups.  I was expecting something really great from this APP as I have tried others and all fail at this point.

Regards
Aaron

**Comment by DanielnetoDotCom** [comment]
the subscription plugin is to watch videos, NOT to control user uploads.

we are working in a new plugin to control users upload disk usage. but it is not ready yet and it may take some time to finish.

**Comment by abkiwi9** [comment]
Just another idea for this new plug-in is if you are able to make it link to the advertising APP so subscriptions could be made with no ADDS?

**Comment by DanielnetoDotCom** [comment]
ADDS? what is it?

**Comment by akhilleusuggo** [comment]
I think he means ads 
Premium users not to be disturbed with ads

**Comment by DanielnetoDotCom** [comment]
So I guess you are looking for this 

![image](https://user-images.githubusercontent.com/18009293/79603052-f96dfd80-80c1-11ea-9a7e-08da867a006f.png)

But for this, you must have the GoogleAds_IMA setup

**Comment by abkiwi9** [comment]
I was on the understanding that I can add paid video advertising to the starting and ending of a video.
If this is the case then Premium paid users need to be advertising free?
This is all new to me so picking it up as I go.

Good to know you are working on something.

Regards
Aaron

**Comment by DanielnetoDotCom** [comment]
@abkiwi9 you are correct.
