### ISSUE TITLE
SendRecordedToEncoder could not move file

### ISSUE THREAD

**Issue by djslmft** [WWBN/AVideo#2879]
We bought the SendRecordedToEncoder plugin and in the php-log i see this line:
on_record_done WARN: could not move the file /var/www/tmp/(filename).flv to /(wwwroot)/videos/(filename2), we will try to copy

It copies the file, makes the encoding but it leaves the original flv in the temp directory

The permission is set to 777 on the temp directory so i don't know why it cannot move the original.

The file was created by the Live plugin is owned by "nobody" and has permissons of 644

**Comment by DanielnetoDotCom** [comment]
I am not sure how to fix it on your side, but the Nginx is using a different user then Apache.

maybe you can google to find out how to change the Nginx user or make them on the same user group.

**Comment by djslmft** [comment]
To make clear: nginx makes the file as "nobody" that's why php cannot move it?

**Comment by djslmft** [comment]
excuse me, but i ran in another issue... now the encoding and the file moving works perfectly but after encoding it doesn't deletes the original video :/

**Comment by DanielnetoDotCom** [comment]
do you mean original files on encoder?

do you have the auto-remove option checked?

![image](https://user-images.githubusercontent.com/18009293/79687727-b4f87400-821f-11ea-9c57-5e96b8d83914.png)

**Comment by djslmft** [comment]
yes, it's on, but doesn't do the thing :/

**Comment by DanielnetoDotCom** [comment]
do you mean (with thing) it does not delete the file?

**Comment by djslmft** [comment]
yes, i mean, it doesn't delete the file

**Comment by DanielnetoDotCom** [comment]
I just send some updates, I found a bug that does not delete the "original" file on the Streamer videos directory. is that correct? is that the one you are talking about?

**Comment by djslmft** [comment]
Yes, it is...
How can I update?

**Comment by djslmft** [comment]
got it, made it, testing
