### ISSUE TITLE
Live streaming with group restriction shows all Live video on homepage

### ISSUE THREAD

**Issue by boom02456** [WWBN/AVideo#2880]
Hi,

I've test live streaming with group restriction,

however, when I restrict live to one group, other group can see the live video on homepage but cannot view it.

Can I know if this is a bug or any configuration to hide other group's live on homepage?

**Comment by DanielnetoDotCom** [comment]
the video will appear on the homepage to everyone.

but only the user group will be able to watch it.

**Comment by boom02456** [comment]
ow, do you have some suggestions how can I modify it to show only allowed group on homepage?

**Comment by DanielnetoDotCom** [comment]
this will require you to change the code, and I do not have it on the top of my mind. you probably will need to modify some files to make it work in that way.
