### ISSUE TITLE
how to remove temp files

### ISSUE THREAD

**Issue by karthikindia** [WWBN/AVideo#2881]
my server space is filling up fast even if i dont upload anyvideos and i am only streaming one stream, that recorded videos also i delete everyday
can any one help me how to clear the temp files if any

**Comment by DanielnetoDotCom** [comment]
you should not delete temp files. but you may find what is consuming space and create a strategy to delete it regularly.

check this to find what directory is consuming your space https://stackoverflow.com/questions/16030499/du-h-max-depth-1-takes-long-time
