### ISSUE TITLE
First page videos paginations reload entire page and go upper

### ISSUE THREAD

**Issue by Krystian95** [WWBN/AVideo#2882]
Hi, if I navigate category videos (eg. Trending or Most popular) in the first page using the pagination buttons, after clicked a page number, the entire page is reloaded and scroll up (or even saying better, doesn't scrolls down to the section). Is not loaded via ajax? And most important the URL ".../page/4" set the page "4" for all existing paginating. I've tried it in the demo site.

Many thanks,
Chris

<img width="1440" alt="Schermata 2020-04-16 alle 15 48 26" src="https://user-images.githubusercontent.com/24765669/79464707-b39a3200-7ffa-11ea-8285-e37ade5ee51a.png">

**Comment by DanielnetoDotCom** [comment]
I am not sure if I understand, but the pagination is global, if you paginate one category in the main page, all categories will be paginated

**Comment by Krystian95** [comment]
Yes, that's true, but is not more usable set the pagination locally to each section? 🙂 I know that's not urgent, it's only to talk how to improve this great software

**Comment by DanielnetoDotCom** [comment]
Ok, thanks, but it is NOT a bug
