### ISSUE TITLE
Encoder installation requests for github crendentials

### ISSUE THREAD

**Issue by tokunboajewole** [WWBN/AVideo#2883]
Dear sirs,

Still trying to setup my install:

I followed this tutorial to install the streamer:
https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x-For-AVideo-Platform-version-4.x-or-newer

Then Im following this one to install the encoder:
https://github.com/WWBN/AVideo-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x---For-AVideo-Encoder

However during the encoder installation, I get this prompt for login credentials:

Cloning into 'AVideo-Encoder'...
Username for 'https://github.com':

what credentials am I to use? pls advise...
regards
Tokunbo

**Comment by DanielnetoDotCom** [comment]
Hi, I am not sure where this comes from, I guess you are using the wrong command.

**Comment by tokunboajewole** [comment]
Hi,

I used the first command on the page: the one below "just copy and paste this":
https://github.com/WWBN/AVideo-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x---For-AVideo-Encoder

regards
Tokunbo

**Comment by tokunboajewole** [comment]
hi, I attached a screenshot:
![Screenshot from 2020-04-16 11-01-34](https://user-images.githubusercontent.com/30118228/79472374-c2b8ba00-7fd1-11ea-9d11-c968063dc6a0.png)

**Comment by DanielnetoDotCom** [comment]
really really strange.

what about if you type `git clone https://github.com/WWBN/AVideo-Encoder.git`

is the same output?

**Comment by tokunboajewole** [comment]
Hi Daniel,
Thanks. your command worked - installation is still going on.

will update you.
regards
Tokunbo

**Comment by tokunboajewole** [comment]
> Hi Daniel,
> Thanks. your command worked - installation is still going on (the upgrade)...
> 
> will update you.
> regards
> Tokunbo

thanks, installation completed. 
Where can I find a tutorial for the specific configurations required.

regards
tokunbo
