### ISSUE TITLE
File permissions of videos

### ISSUE THREAD

**Issue by theshm00** [WWBN/AVideo#2884]
Today I set up AVideo and an AVideo encoder on a freshly installed Debian 10. After the first attempts to upload a video it could not be played back. The player on the portal page reports the error "The media could not be loaded, either because the server or network failed or because the format is not supported. When I look at the files in the /Video directory, I see that all files were created with the right 644. Except the *.mp4 files. This one was created with 600.

Here is a listing from my video directory:

-rw-r--r--  1 webx408 webx408  82K Apr 16 16:10 _YPTuniqid_5e9867587c8997.64172158.gif
-rw-------  1 webx408 webx408 600K Apr 16 16:10 _YPTuniqid_5e9867587c8997.64172158_HD.mp4
-rw-r--r--  1 webx408 webx408 142K Apr 16 16:10 _YPTuniqid_5e9867587c8997.64172158.jpg
-rw-------  1 webx408 webx408 336K Apr 16 16:10 _YPTuniqid_5e9867587c8997.64172158_SD.mp4
-rw-rw-rw-  1 webx408 webx408 1.4K Apr 16 16:10 _YPTuniqid_5e9867587c8997.64172158_thumbsSmallV2.jpg
-rw-rw-rw-  1 webx408 webx408 2.1K Apr 16 16:10 _YPTuniqid_5e9867587c8997.64172158_thumbsV2.jpg
-rw-r--r--  1 webx408 webx408 493K Apr 16 16:10 _YPTuniqid_5e9867587c8997.64172158.webp

If I set the rights of the *.mp4 files to 644 via chmod I can watch videos in the portal. 

Is there a possibility to set the file rights of the videos automatically to 644? Only to avoid misunderstandings the mp4 file was created by the encoder.

**Comment by DanielnetoDotCom** [comment]
I guess it is some specific configuration in your apache. I have never seen any issues like that.

you should google to see something about your apache files creation permission.

**Comment by akhilleusuggo** [comment]
https://www.linuxquestions.org/questions/linux-desktop-74/applying-default-permissions-for-newly-created-files-within-a-specific-folder-605129/
