### ISSUE TITLE
Double the storage

### ISSUE THREAD

**Issue by joshuanoyce** [WWBN/AVideo#2886]
The videos seem to be using double the storage. I am using my own encoder and there are temporary files under YouTubePHP/Encoder/videos and there are the files under YouTubePHP/videos where all the videos are. I have checked and all the videos on under the main site. Could I delete the videos in the YouTubePHP/Encoder/videos to free up storage space on my server?

**Comment by akhilleusuggo** [comment]
The script should delete the videos for your automatically . Keeps them only when getting some errors . Check your log encoder , and make sure you have auto remove option selected .
![image](https://user-images.githubusercontent.com/52116577/79517387-b6c30b80-8056-11ea-9671-f0188198bb63.png)

**Comment by joshuanoyce** [comment]
Great thank you for your help. The Auto Remove was not checked.
