### ISSUE TITLE
Key stream and  Player URL

### ISSUE THREAD

**Issue by landydawood** [WWBN/AVideo#2887]
I have question regarding to key stream and  Player URL , theirs any way to customize it as we want for EXP: i can put key stream as i like ?

**Comment by akhilleusuggo** [comment]
The key-stream of NGINX is not really '' a secret key '' . It's a public key . Meaning that anyone can see it when watching your stream . Your actual ''secret key'' are the rtmp link .

**Comment by landydawood** [comment]
yes but i need to use name of the channel for key thats help to show it in the m3u link
