### ISSUE TITLE
Donation APP

### ISSUE THREAD

**Issue by abkiwi9** [WWBN/AVideo#2888]
I have been looking at a lot of other startup video sites and they all seem to have a donation system so customers can make donations to help support the running cost of the site.

I think it would be good if you are able to make such an APP that can have links throughout the site for customers to donate and with a list of ways we as site owners can select to receive the payment.

Regards
Aaron

**Comment by akhilleusuggo** [comment]
This option already exists .
![image](https://user-images.githubusercontent.com/52116577/79517900-3e5d4a00-8058-11ea-9739-48bf5f9061c1.png)

Check your plugins ( advanced customize )

**Comment by abkiwi9** [comment]
Ok, I can't find where to add it?  It is not in the plugins, Admin manual or any other setting in admin.

**Comment by DanielnetoDotCom** [comment]
Enable it in your plugins

![image](https://user-images.githubusercontent.com/18009293/79585387-1b598700-80a6-11ea-8804-de56ea5da8c1.png)

add the link in your profile

![image](https://user-images.githubusercontent.com/18009293/79585453-32987480-80a6-11ea-9804-f24b60fe19d9.png)

**Comment by heiress01** [comment]
The way the link is now each channel user can change the link to their own personal link. How can the donation link be locked to the site owner?

**Comment by DanielnetoDotCom** [comment]
you can create a top menu with the donation link.
