### ISSUE TITLE
 {"status":"error", "msg":["sh: ffprobe: command not found"] ,"return_val":127, "where":"getDuration", "cmd":"ffprobe -i 

### ISSUE THREAD

**Issue by woshka** [WWBN/AVideo#2889]
**Describe the bug**

**To Reproduce**
1. Go to avideo.log file
2. use tail -f for the latest logs
3. Scroll down to paste a youtube video for donloading on the encoder site
4. there is no error on the site
**Expected behavior**

**Error Logs**
 {"status":"error", "msg":["sh: ffprobe: command not found"] ,"return_val":127, "where":"getDuration", "cmd":"ffprobe -i 

the result of ffprobe on the server is as followes

 ffprobe
ffprobe version N-97357-g8e30502 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-39)
  configuration: --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --extra-libs=-lpthread --extra-libs=-lm --bindir=/root/bin --enable-gpl --enable-libfdk_aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      56. 42.102 / 56. 42.102
  libavcodec     58. 79.100 / 58. 79.100
  libavformat    58. 42.100 / 58. 42.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 77.101 /  7. 77.101
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Simple multimedia streams analyzer
usage: ffprobe [OPTIONS] [INPUT_FILE]

You have to specify one input file.
Use -h to get full help or, even better, run 'man ffprobe'.
[root@104-237-255-151-host videos]# which ffprobe
/root/bin/ffprobe
[root@104-237-255-151-host videos]#

**Comment by DanielnetoDotCom** [comment]
so you must find out why your PHP cannot execute it.

this is not a software bug, it is your PHP configuration that is wrong somewhere.

**Comment by woshka** [comment]
could you please send me a pure php script to execute it separately on my server to see the result

thx

**Comment by akhilleusuggo** [comment]
My question is : Did you installed ffmpeg with `apt-get install ffmpeg` , or have you `build it` ?
You need to give permission to apache to execute ffmpeg , if you have build it , only the builder can use it .

**Comment by woshka** [comment]
yes I have compiled it and all liberaries on Centos 7
it was ffmpeg-php extension some years ago

**Comment by akhilleusuggo** [comment]
@woshka I'll give you an asnwer but for Ubuntu users ( I'm not very familiar with Centos , but shouldn't be so different ) .
Ok , you will have to move ffmpeg and ffprobe from `~/bin` OR `/root/bin/ffprobe` to `/usr/local/bin` to allow all users access . In this case `www:data` user

You can use `cp` or `mv` command . This will fix the issue .

**Comment by woshka** [comment]
> @woshka I'll give you an asnwer but for Ubuntu users ( I'm not very familiar with Centos , but shouldn't be so different ) .
> Ok , you will have to move ffmpeg and ffprobe from `~/bin` OR `/root/bin/` to `/usr/local/bin` to allow all users access . In this case `www:data` user
> 
> You can use `cp` or `mv` command . This will fix the issue .

I moved the ffprobe from /usr/bin to /usr/local/bin and the duration is extracted from the video and every thing works fine thank you

**Comment by akhilleusuggo** [comment]
happy to help :)
