### ISSUE TITLE
Embed code for trailer doesn't work

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#2890]
Hey!

When you edit video on Myvideos -> metadata tab, embed code for trailer doesn't work. When I paste embed code and save, it doesn't do anything. And when I reopen the tab there isn't any input.

![image](https://user-images.githubusercontent.com/63721378/79573572-8a93a300-80c7-11ea-88fe-932c86f97357.png)

**Comment by DanielnetoDotCom** [comment]
check your log files

**Comment by tonuzo** [comment]
`[17-Apr-2020 15:42:37 UTC] PHP Notice:  Undefined index: videoTags in /var/www/YouPHPTube/plugin/VideoTags/VideoTags.php on line 237
[17-Apr-2020 15:42:37 UTC] PHP Warning:  Invalid argument supplied for foreach() in /var/www/YouPHPTube/plugin/VideoTags/VideoTags.php on line 46
[17-Apr-2020 15:42:37 UTC] getUsageFromFilename: start /var/www/YouPHPTube/videos/video_5e99a7ff8eb1f
[17-Apr-2020 15:42:37 UTC] updateFilesize: No need to update videos_id=7 filename=video_5e99a7ff8eb1f filesize=0
[17-Apr-2020 15:42:37 UTC] getUsageFromFilename: start /var/www/YouPHPTube/videos/video_5e99a2f12b8fd
[17-Apr-2020 15:42:37 UTC] updateFilesize: No need to update videos_id=5 filename=video_5e99a2f12b8fd filesize=0`

**Comment by DanielnetoDotCom** [comment]
the provided log has nothing to do with the error.

1. try this, delete your log file.
2. try to add the trailer.
3. share the entire log file

**Comment by DanielnetoDotCom** [comment]
In your log, I cannot see the saving attempt.

maybe your error is on the javascript. check your javascript console

**Comment by tonuzo** [comment]
I don't know what javascript. file..?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform#javascript-errors

**Comment by tonuzo** [comment]
I checked the javascript console, but there was nothing. 

I'm not sure how the trailers should work. I also tried to make a trailer from embed code on Avideo Full Access Demo Site, but it didn't work there either... Maybe I'm doing something wrong?

**Comment by DanielnetoDotCom** [comment]
Trailers work like this sample site https://flix.avideo.com/

**Comment by tonuzo** [comment]
Yes, I see, but I don't know how to make them because trailer embed form doesn't work...

**Comment by DanielnetoDotCom** [comment]
what exactly trailer link are you trying to save?

please screenshot your video form, so we can see what you are using

**Comment by tonuzo** [comment]
Here is an example. After this is saved, it surely don't appear anywhere 
![image](https://user-images.githubusercontent.com/63721378/79773880-ab176380-833a-11ea-91e4-cbc09dfcf8b1.png)

I suppose it should show up here, like in this sample site 
![image](https://user-images.githubusercontent.com/63721378/79774120-0e08fa80-833b-11ea-87c1-185ff5421b20.png)

Should I activate a plugin or something..?

**Comment by DanielnetoDotCom** [comment]
that is why! you are adding the whole iframe code, you must only put the youtube URL

**Comment by tonuzo** [comment]
Ofcourse...  Stupid me :D Thank you!
