### ISSUE TITLE
FTP Storage clear cache issue

### ISSUE THREAD

**Issue by woshka** [WWBN/AVideo#2894]
this is what I get when I click the clear cache button on ftp storage plugin

Warning: require_once(./Blackblaze_B2.php): failed to open stream: No such file or directory in /home/video2voshka/public_html/plugin/FTP_Storage/clearCache.php(14) : eval()'d code(1) : eval()'d code on line 3

Fatal error: require_once(): Failed opening required './Blackblaze_B2.php' (include_path='.:/opt/cpanel/ea-php56/root/usr/share/pear') in /home/video2voshka/public_html/plugin/FTP_Storage/clearCache.php(14) : eval()'d code(1) : eval()'d code on line 3

**Comment by DanielnetoDotCom** [comment]
Hi

I am not sure when you download the FTP plugin but it supposes to be fixed in 2018.
just to make sure it is fixed in the site version, I am sending the update again. please download the plugin from the plugins site again.

**Comment by woshka** [comment]
I downloaded it yesterday

**Comment by DanielnetoDotCom** [comment]
For some reason it was an old version, please download it again.

**Comment by woshka** [comment]
I re downloaded it again
the clear cache now show blank page

**Comment by DanielnetoDotCom** [comment]
do you mean a blank page when you asked to clear the plugin cache?

if yes, that is fine.
