### ISSUE TITLE
How to stream a video step by step

### ISSUE THREAD

**Issue by tokunboajewole** [WWBN/AVideo#2895]
Hello sirs,

Installation completed successfully - done on 2-virtual machines labelled as streamer and encoder.
- streaming URL added into Encoder.

I uploadeda video(.mp4), 2mins video into the encoder, after sometime I see the video in the 'my videos' section of the streamer. 

Can someone pls explain what is supposed to happen if I'm to stream a video, as in how do I get the streamer to 'stream'.

Or for example: If I import video(add yourtube URL) of a video into encoder, and the "sharing queue" tab "loads"(i assume thats what its doing) the video, showing a progress from 0-100%; then I check the "my videos" section of the streamer, I see the new video, from the encoder there, kindly, what next is supposed to happen.

Im assuming that as video is encoding from encoder, I should see it "streaming" in my streamer?

Note: The Live plugin is enabled. Is it supposed to turn GREEN if everything is working fine?

Pls help clarify what is missing in my setup.

regards
tokunbo

**Comment by akhilleusuggo** [comment]
you mixing too much concepts .
Are you talking about a live stream or a video upload ?
Video from youtube are downloaded and encoded 

About live-stream you need to configure it and set up NGINX server
https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

**Comment by tokunboajewole** [comment]
Hi there,
thanks for your reply.
Ok, lets start with a downloaded youtube video. What should happen after uploading it via the encoder?

regards
Tokunbo

**Comment by akhilleusuggo** [comment]
@tokunboajewole the video will be download with youtube-dl , then will start encoding .
