### ISSUE TITLE
PLaylist how create

### ISSUE THREAD

**Issue by gamersalpha** [WWBN/AVideo#2896]
Hello a simple question how create playlist please ?

**Comment by akhilleusuggo** [comment]
1) Enable playlist plugin

![image](https://user-images.githubusercontent.com/52116577/79619073-83df4d00-8114-11ea-9514-73adae282ab4.png)

2) Visit any video and add it to playlist ( create one )

![image](https://user-images.githubusercontent.com/52116577/79619119-a5403900-8114-11ea-8215-24b3bb09ee65.png)

**Comment by gamersalpha** [comment]
yes works fine thanks

**Comment by gamersalpha** [comment]
sorry i repon it, i can add video or audio on playlist, but where are the playlist ,

i can't found them ?

**Comment by DanielnetoDotCom** [comment]
yes, you can add video and audio, then you can find the playlists on your channel.

![image](https://user-images.githubusercontent.com/18009293/79638890-76e74b80-815e-11ea-9046-cd6da1ef4e40.png)

**Comment by gamersalpha** [comment]
u write thanks sorry
