### ISSUE TITLE
Theme Designs and colour changes

### ISSUE THREAD

**Issue by abkiwi9** [WWBN/AVideo#2898]
Is anyone designing and selling themes for youPHP?

If anyone can provide a service to do some colour changes and front-page layout design.

**Comment by vomoplay** [comment]
If anyone has an interest too.

**Comment by DanielnetoDotCom** [comment]
Hi, 

if it helps anyone that is interested in it. to create a new layout I recommend you create a new plugin for that instead modify the source code.

For example, just copy the gallery plugin and rename it. follow this https://github.com/WWBN/AVideo/wiki/How-to-code-a-AVideo-Platform-plugin
