### ISSUE TITLE
Admin Locked out

### ISSUE THREAD

**Issue by shebanet** [WWBN/AVideo#2899]
I previously set customuser plugin setting to require login with email. Afterwards when I try to log in as admin it requires my email. when I entere admin email credentials it does not recognize the admin email. Unable to log in as admin. Why does it not recognize admin email? What's the best way to access admin user credentials and correct the problem?

**Comment by akhilleusuggo** [comment]
Please read more about how to reset password here : 
https://github.com/WWBN/AVideo/wiki/Reset-a-Password

**Comment by shebanet** [comment]
Resetting the password is not a problem. The problem is the app is not recognizing the admins username which is supposed to be the admin email address. How can I access/change email address for admin?

Thanks,
Joseph

202.746.9674
________________________________

**Comment by DanielnetoDotCom** [comment]
try to truncate the plugins table to reset all the plugins configurations.

after that, change your username to an email and then enable the username as an email again.

**Comment by akhilleusuggo** [comment]
@shebanet you always can do the dirty work by going to database and change manually .

**Comment by shebanet** [comment]
Solved! Thanks to you both. Instead of running Truncate on plugins table, I went to users table and changed the admin username to equal the admins email address. Admin able to log back in now. 

Lesson: Be careful when you enable forceLoginToBeTheEmail in the CustomeUser plugin because, once you do, app will expect all usernames to be email addresses and it enforce this rule on new users as well as PREXISTING users including admins. So, in my case since there was only one admin and that admin still had original username as 'admin' (not email) system refused to login admin - admin locked out! Even resetting password will not help you. Only way back in is either execute TRUNCATE TABLE plugins; or go to USERS table and update admins username to match the email address.

**Comment by DanielnetoDotCom** [comment]
I just add a fix, that if the user is admin, it will not lock it out because of the email.

**Comment by ronaldod** [comment]
Maybe just fix this problem with changing the install page and add an email adres to the page. This solution can maybe open other security holes. As admin should have even more security then normal accounts.

**Comment by DanielnetoDotCom** [comment]
Good idea and I may add it in the future.
