### ISSUE TITLE
hls

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2901]
Why the plugin does use hls_time 15 , when the recommended duration should be a maximum of 6 ?
15 does not even feet with the keyframes .

Does that affect any performance ? Buffering reduction ? Speed up the encoding ?
Because on your default hls nginx setup is correct 6 , but on the encoder part it's 15 . Just asking .

**Comment by DanielnetoDotCom** [comment]
Hi, where are you talking about? is it from the source code? can you paste part of the code here os I can understand what do you mean?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I wanted to change it time ago with a pull request .
I'm talking about the encoder file on `/object/Format.php`

https://github.com/WWBN/AVideo-Encoder/blob/3e0fa55125ecf87cbadfd1caf252ccf1c284005f/objects/Format.php#L281

https://github.com/WWBN/AVideo-Encoder/blob/3e0fa55125ecf87cbadfd1caf252ccf1c284005f/objects/Format.php#L276

This 2 lines does create the hls , and I'm referring to `-hls_time 15` witch should be -hls_time 6
keyframes should be created every 2s , 15 can't do this .

The down side of hls is that need to load 3 segments before the video starts playing .
In this case need to load 15*3=45s before it's start . Lowering this value to 6 , will load only 18s.

Very low values will result in a huge stress of hardware ( IOPS )

**Comment by DanielnetoDotCom** [comment]
I use 15 because I read somewhere it will be better. I am not 

I will be happy if you recommend the optimal values and make the pull request

**Comment by akhilleusuggo** [comment]
done
