### ISSUE TITLE
10bytes only files after conversion

### ISSUE THREAD

**Issue by woshka** [WWBN/AVideo#2902]
all the files in the video directory are only 10bytes after the conversion
I used cat for the content inside it
Dummy File 
above line was inside it
what causes such issues?
thx

**Comment by DanielnetoDotCom** [comment]
It is not an issue.

if you are using any type of external storage like S3, B2, FTP, YPTStorage plugin you will have this file. but the real file will be stored in your storage.

check the options here https://github.com/WWBN/AVideo/wiki/Storage-Options

**Comment by woshka** [comment]
what if there was an issue such as connectivity issue for storing on the remote server?
will there be a commitment to check the files to have them store localy?

**Comment by DanielnetoDotCom** [comment]
what type of storage are you using?

**Comment by woshka** [comment]
ftp

**Comment by DanielnetoDotCom** [comment]
the thing is, it should not be any error.
check your log files to detect what error is that.

**Comment by DanielnetoDotCom** [comment]
let's follow here https://github.com/WWBN/AVideo/issues/2893
