### ISSUE TITLE
Can't install a plugin

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#2906]
When I upload a plugin, all the plugins on plugins page disappear. 

![image](https://user-images.githubusercontent.com/63721378/79682878-d3f60680-821d-11ea-8e77-404f23d6110c.png)

In file directory everything is okay and the new plugin directory is also there.

When I load the plugins page, browser cosole gives this error: 
![image](https://user-images.githubusercontent.com/63721378/79682848-985b3c80-821d-11ea-86b2-d523715f7b6b.png)

When I delete the new plugin folder ../plugins/[new plugin]/  everything comes back to normal and I can continue using plugins page.

**Comment by DanielnetoDotCom** [comment]
check your streamer log file.

**Comment by tonuzo** [comment]
Thanks. Figured it out!
