### ISSUE TITLE
I am trying to install streamer server and getting this error

### ISSUE THREAD

**Issue by sharad22gupta** [WWBN/AVideo#2907]
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php7.0-xml
E: Couldn't find any package by glob 'php7.0-xml'
E: Couldn't find any package by regex 'php7.0-xml'
E:: command not found
 
After i run this command 
sudo apt-get install build-essential libpcre3 libpcre3-dev libssl-dev php7.0-xml && sudo mkdir ~/build && cd ~/build && sudo git clone git://github.com/arut/nginx-rtmp-module.git && sudo wget http://nginx.org/download/nginx-1.12.0.tar.gz && sudo tar xzf nginx-1.12.0.tar.gz && cd nginx-1.12.0 && sudo ./configure --with-http_ssl_module --with-http_stub_status_module --add-module=../nginx-rtmp-module && sudo make && sudo make install && sudo mkdir /usr/local/nginx/ssl/ && sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /usr/local/nginx/ssl/nginx.key -out /usr/local/nginx/ssl/nginx.crt && sudo /etc/init.d/apache2 restart && sudo mkdir /HLS && sudo mkdir /HLS/live

What can i do? @akhilleusuggo @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
I guess you are using ubuntu 18

try this tutorial https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer

**Comment by sharad22gupta** [comment]
Instead of step 2. Install Nginx and Nginx-RTMP
i have used 
if you want to install both (encoder and streamer) use this compiled code:

sudo apt-get install apache2 php libapache2-mod-php php-mysql php-curl php-gd php-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube.git && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube-Encoder.git && sudo apt-get install python && sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl && sudo a2enmod rewrite
 then i should follow from step 3 or anything else 
@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
php7.0-xml is for ubuntu 16

if you are using Ubuntu 18, make sure you are using the correct link (the one I share above)

**Comment by akhilleusuggo** [comment]
@sharad22gupta Hello . You need `php7.0-xml` and `wget http://nginx.org/download/nginx-1.16.1.tar.gz`

**Comment by sharad22gupta** [comment]
i am using ubuntu 18 and i changed it to php7.2 and nginx-1.16.1 and i reached to step 7 
ubuntu@ec2-13-234-198-202:/usr/local/nginx/conf$ nohup php /www.MYWEBSITEADDRESS.COM/plugin/LiveChat/chat-server.php &
[1] 1563
ubuntu@ec2-13-234-198-202:/usr/local/nginx/conf$ nohup: ignoring input and appending output to '/home/ubuntu/nohup.out'
^C
[1]+  Exit 1                  nohup php /www.MYWEBSITEADDRESS.COM/plugin/LiveChat/chat-server.php
ubuntu@ec2-13-234-198-202:/usr/local/nginx/conf$ sudo /usr/local/nginx/sbin/nginx
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] still could not bind()

I got this response which is diiferent from the video tutorial can you please help me with this.
@akhilleusuggo @DanielnetoDotCom

**Comment by akhilleusuggo** [comment]
that means that your nginx is already running .

To stop `sudo /usr/local/nginx/sbin/nginx -s stop`
To start `sudo /usr/local/nginx/sbin/nginx`
Quick restart `sudo /usr/local/nginx/sbin/nginx -s stop && sudo /usr/local/nginx/sbin/nginx`

**Comment by sharad22gupta** [comment]
i ran the stop and start command got this error 
root@instance-1:/# sudo /usr/local/nginx/sbin/nginx 
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] still could not bind()
root@instance-1:/# sudo /usr/local/nginx/sbin/nginx -s stop
nginx: [error] open() "/usr/local/nginx/logs/nginx.pid" failed (2: No such file or directory)
root@instance-1:/# sudo /usr/local/nginx/sbin/nginx -s stop && sudo /usr/local/nginx/sbin/nginx
nginx: [error] open() "/usr/local/nginx/logs/nginx.pid" failed (2: No such file or directory)

also i am getting address as 0.0.0.0:8080, is that correct?  @akhilleusuggo  @DanielnetoDotCom

**Comment by akhilleusuggo** [comment]
```
root@instance-1:/# sudo /usr/local/nginx/sbin/nginx -s stop
nginx: [error] open() "/usr/local/nginx/logs/nginx.pid" failed (2: No such file or directory)
```
Means that nginx is already stopped . Now you need to start it 
`sudo /usr/local/nginx/sbin/nginx`

**Comment by sharad22gupta** [comment]
root@instance-1:/# sudo /usr/local/nginx/sbin/nginx -s stop
nginx: [error] open() "/usr/local/nginx/logs/nginx.pid" failed (2: No such file or directory)
root@instance-1:/# sudo /usr/local/nginx/sbin/nginx 
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] still could not bind()

i stopped it and started it again, got this

and cant access http://mywebsite.com:81 page @akhilleusuggo

**Comment by akhilleusuggo** [comment]
@sharad22gupta http://mywebsite.com:8080/stat

What do you see ?

**Comment by sharad22gupta** [comment]
I get this  @akhilleusuggo 
![Annotation 2020-04-23 015707](https://user-images.githubusercontent.com/15939963/80030443-d1d5c580-8505-11ea-9b2c-08f00157e73e.png)

**Comment by akhilleusuggo** [comment]
On your nginx config , what port are you using ?
The default one is 8080
```
http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
```

Make sure that your provider firewall is not blocking it . ( google cloud and aws ) does block it by default . You need to change the rules ( in case your provider does )

**Comment by akhilleusuggo** [comment]
So yes , you're using gcp .
You will need to go VPC network , firewall rules , add 8080 port tcp
Or you can delete all the rules and make no port blocked .
I've made an example to how it should look : 
![image](https://user-images.githubusercontent.com/52116577/80032065-48b59300-84f3-11ea-9cea-479a055bbe60.png)

Streamport is the demo ( for allow all )

**Comment by sharad22gupta** [comment]
yes i am using GCP
my nginx config is this
 http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/m$
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

i added the firewall rule with the name Streamer still cant access the stat page
![Annotation 2020-04-23 022756](https://user-images.githubusercontent.com/15939963/80033318-211df500-850a-11ea-86e7-7e08ecda7ae1.png)

@akhilleusuggo

**Comment by akhilleusuggo** [comment]
Then make it look like the picture I've posted and will work .
Also make sure that on your live stream plugin you're pointing to porn 8080

**Comment by sharad22gupta** [comment]
These are all the firewall rules and its same as yours
![Annotation 2020-04-23 040345](https://user-images.githubusercontent.com/15939963/80040343-77456500-8517-11ea-920e-f3e9d29a9df8.png)
and live plugin is pointing to 8080 
![Annotation 2020-04-23 040851](https://user-images.githubusercontent.com/15939963/80040650-2f730d80-8518-11ea-8216-838925760dc7.png)
 I ran windows network diagnostics and got this.
![Annotation 2020-04-23 041025](https://user-images.githubusercontent.com/15939963/80040781-7234e580-8518-11ea-93bb-c553aa967c00.png)

**Comment by akhilleusuggo** [comment]
On your rules , you will have to delete all of them ( and I mean all of them ) , or add a new rule for port 8080 . On your screen I don't see the 8080 , I see 8083

This is my test one , and it's working . I'm not hiding anything , anyway it's just for testing this issue .

![image](https://user-images.githubusercontent.com/52116577/80041013-ff217400-8503-11ea-833e-6e21b450f4a3.png)

**Comment by sharad22gupta** [comment]
![Annotation 2020-04-23 042801](https://user-images.githubusercontent.com/15939963/80041758-db1d5d00-851a-11ea-8db3-b9b5af99f008.png)
 
i added 8080  and ran this sudo ufw allow 8080/tcp

restarted apache2 and nginx, still not working, @akhilleusuggo

**Comment by akhilleusuggo** [comment]
I can assure you that the port 8080 is not open .
Try this : 
`Telnet YourIP 80` ( for port 80 ) it will work

Try this : 
`telnet YouIP 8080 `( for port 8080 ) will not work .

PS; when it works , the output should look like this : 
```
Connected to YourIP.
Escape character is '^]'.
```

This is how it should look , and make sure that other rules are not blocking your previous port . 
![image](https://user-images.githubusercontent.com/52116577/80048635-6695ee80-8519-11ea-9fbe-0c7557d1bcda.png)

Recommendation , remove all the rules , and add them by yourself, **_KNOWING_** what you're doing .

**Comment by sharad22gupta** [comment]
![Annotation 2020-04-23 143702](https://user-images.githubusercontent.com/15939963/80081101-201fae80-8570-11ea-912a-87016fb0f919.png)
![Annotation 2020-04-23 143813](https://user-images.githubusercontent.com/15939963/80081115-231a9f00-8570-11ea-93fe-c6843d5a3a0d.png)
 I have changed the rules exactly like yours and ran the commands , it's not connecting to port 8080, what else can i do to make it work.
@akhilleusuggo

**Comment by akhilleusuggo** [comment]
have you rebooted the server ?
`sudo reboot`

**Comment by sharad22gupta** [comment]
yes, I did and still can't connect. @akhilleusuggo

**Comment by DanielnetoDotCom** [comment]
I agree with @akhilleusuggo I guess the port is not open.

try to allow all the ports and see if it connect. also, check if you are not using a firewall in your local server.

also, try telnet on localhost `telnet localhost 8080`, if it works, means the problem your firewall or proxy
