### ISSUE TITLE
Publishing Video as unlisted

### ISSUE THREAD

**Issue by rielcomms** [WWBN/AVideo#2908]
**Describe the question**
I am looking for a way to publish a video as unlisted same way you can do on yt where only those with the direct URL of the video can view it, with or without signing up.
Ideally this can be used to publish paid content for patreons hosted on the site but with the URL only used to publish it on patreon.com

**Screenshots**
Please see attached screenshot
![visibility_1](https://user-images.githubusercontent.com/46077574/79694276-93ea5000-822c-11ea-93f3-416bf38780f4.PNG)

**Comment by akhilleusuggo** [comment]
there's no such option for now
There's only "makeVideosInactiveAfterEncode"

Plugins : CustomizeAdvanced (CustomizeAdvanced)

![image](https://user-images.githubusercontent.com/52116577/79696193-d0956600-8283-11ea-9e25-1f8227df73da.png)

**Comment by DanielnetoDotCom** [comment]
I just sent an update with this option. 
![image](https://user-images.githubusercontent.com/18009293/79698416-2c99c380-825f-11ea-9798-8f9abd32ff13.png)
