### ISSUE TITLE
Thumbnails not working

### ISSUE THREAD

**Issue by christianreiss** [WWBN/AVideo#2909]
**Describe the bug**
After upgrading from "phpmytube" to current avideo-git, version

```
commit a733058f83099803b5d508544b275626272fdc79 (HEAD -> master, origin/master, origin/HEAD)
Author: daniel <daniel@daniel-DC1A-S>
Date:   Sun Apr 19 16:46:36 2020 -0300

    https://github.com/WWBN/AVideo/issues/2908
    
    Option for unlisted after encode
```

Freshly uploaded videos do get uploaded, have all three quality levels, a jpeg, gif and webp:

```
-rw-r--r--  1 apache apache   80M Apr 20 01:57 _YPTuniqid_5e9cc776a637f9.63844164_Low.mp4
-rw-r--r--  1 apache apache  138M Apr 20 01:56 _YPTuniqid_5e9cc776a637f9.63844164_SD.mp4
-rw-r--r--  1 apache apache  205M Apr 20 01:56 _YPTuniqid_5e9cc776a637f9.63844164_HD.mp4
-rw-r--r--  1 apache apache  360K Apr 20 01:45 _YPTuniqid_5e9cc776a637f9.63844164.webp
-rw-r--r--  1 apache apache  864K Apr 20 01:45 _YPTuniqid_5e9cc776a637f9.63844164.gif
-rw-r--r--  1 apache apache  211K Apr 20 01:45 _YPTuniqid_5e9cc776a637f9.63844164.jpg
```
But the thumbnail is only a yellow circle with a white play icon in it. The video is playable however. 
Editing the video in "My Videos" shows a valid Poster, Mouse Over Poster (ok  for WebP and Gif) but the yellow circle with the play icon for Mouse of Potrait Poster (Gif) and Portrait Poster (jpg).

**Expected behavior**
After a conversion from the encoder the video is present, playable and has a thumbnail on the overview page.

**Error Logs**
No errors are written to any httpd or php error logs.

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 8.1.1911 (Core) 
 - Browser: Browser agnostic issue

**Comment by christianreiss** [comment]
Seems the thumbsSmallV2.jpg and thumbsV2.jpg are not generated on upload:

```
# ls -lha _YPTuniqid_5e9d5248d75962*
-rw-r--r-- 1 apache apache 776K Apr 20 11:21 _YPTuniqid_5e9d5248d75962.20191101.gif
-rw-r--r-- 1 apache apache 133M Apr 20 11:31 _YPTuniqid_5e9d5248d75962.20191101_HD.mp4
-rw-r--r-- 1 apache apache 338K Apr 20 11:21 _YPTuniqid_5e9d5248d75962.20191101.jpg
-rw-r--r-- 1 apache apache  37M Apr 20 11:32 _YPTuniqid_5e9d5248d75962.20191101_Low.mp4
-rw-r--r-- 1 apache apache  73M Apr 20 11:31 _YPTuniqid_5e9d5248d75962.20191101_SD.mp4
-rw-r--r-- 1 apache apache 500K Apr 20 11:21 _YPTuniqid_5e9d5248d75962.20191101.webp
```
creating them with

```
convert ${vid}.jpg -resize 96x96 ${vid}_thumbsSmallV2.jpg
convert ${vid}.jpg ${vid}_thumbsV2.jpg
```

yields correct thumbnails.

**Comment by DanielnetoDotCom** [comment]
check your log files for errors.

if is not generating the thumbsSmallV2.jpg and thumbsV2.jpg you may have a problem with your GD lib

**Comment by christianreiss** [comment]
Quite possible!
I moved from Centos7 to 8 for the upgrade, ImageMagic was installed, thus convert was working. php-gd was not installed. I assume this was it. Thanks! :)

(If not I will reopne this issue).

**Comment by sharad22gupta** [comment]
> Quite possible!
> I moved from Centos7 to 8 for the upgrade, ImageMagic was installed, thus convert was working. php-gd was not installed. I assume this was it. Thanks! :)
> 
> (If not I will reopne this issue).

Hey i am having the same issue, is yours  fixed @christianreiss

**Comment by christianreiss** [comment]
Yes, installing php-gd -which was missing- solved this for me.
