### ISSUE TITLE
Installation error: nginx: [emerg] mkdir() "/HLS/live" failed (2: No such file or directory)

### ISSUE THREAD

**Issue by tokunboajewole** [WWBN/AVideo#2911]
Hello sirs,

While following this: https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

So I get to step#7, "start nginx" with sudo /usr/local/nginx/sbin/nginx

I get this error:
`root@ubuntu16-server:~# sudo /usr/local/nginx/sbin/nginx
nginx: [emerg] mkdir() "/HLS/live" failed (2: No such file or directory)
root@ubuntu16-server:~# `

Im guessing this has something to do with the last part of the command at step#1 which says :
sudo mkdir /HLS && sudo mkdir /HLS/live

what should be the correct path where above directory is to reside in? 

regards,
Tokunbo

**Comment by DanielnetoDotCom** [comment]
try this

```
sudo mkdir /HLS/
sudo mkdir /HLS/live
sudo chmod 777 /HLS/live
```

**Comment by tokunboajewole** [comment]
thanks for the headsup.

regards
tokunbo
