### ISSUE TITLE
sitemap 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2914]
@DanielnetoDotCom Hello daniel 

Like I've said on the git pull
`<video:duration>PT1H17M57S</video:duration>` The value should be only in seconds , example 600
` <video:requires_subscription>1</video:requires_subscription>` The accepted values are `yes` and `no` . Other values will give errors 

The sitemap display still not looking good . ( even on demo site ) and my site as well 
![image](https://user-images.githubusercontent.com/52116577/79786000-77920480-834d-11ea-9fa9-4a5f6c063386.png)

In the other hand , my home test server works fine , and I don't get it 

![image](https://user-images.githubusercontent.com/52116577/79786130-9f816800-834d-11ea-96e1-1c1027beffa4.png)

**Comment by DanielnetoDotCom** [comment]
Hi

I just sent an update, please try again

**Comment by akhilleusuggo** [comment]
Errors : 
1) Because does not display well .
![image](https://user-images.githubusercontent.com/52116577/79786449-22a2be00-834e-11ea-9994-b5481948780a.png)

2)The date the video was first published, in W3C format. Supported values are complete date (YYYY-MM-DD) or complete date plus hours, minutes and seconds, and timezone (YYYY-MM-DDThh:mm:ss+TZD).

Example: 2007-07-16T19:20:30+08:00

![image](https://user-images.githubusercontent.com/52116577/79786498-39491500-834e-11ea-8724-e22d2b7337ea.png)

3)This is because the values are invalid ( `yes` and `no` ) , and time should be in `seconds` .
![image](https://user-images.githubusercontent.com/52116577/79786521-436b1380-834e-11ea-99d8-7d44b402f32a.png)

4)Should be the source of the video as my understanding . From google : 
A URL pointing to the actual video media file. Should be one of the supported formats.

HTML is not a supported format. Flash is allowed, but no longer supported on most mobile platforms, and so may be indexed less well.

Must not be the same as the <loc> URL.

This is the equivalent of VideoObject.contentUrl in structured data.

Best practice: If you want to restrict access to your content but still have it crawled, ensure that Googlebot can access your content by using a reverse DNS lookup.

![image](https://user-images.githubusercontent.com/52116577/79786599-6695c300-834e-11ea-8550-80196ce109df.png)

**Comment by DanielnetoDotCom** [comment]
is this report after my last update?

what is the link you are using to validate it?

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/79787821-fa9b6680-831d-11ea-845b-cb3ca446f529.png)

![image](https://user-images.githubusercontent.com/18009293/79788066-68e02900-831e-11ea-973e-8426de483810.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I mailed you

**Comment by DanielnetoDotCom** [comment]
Hi, email received. I am not sure if it is fixed not?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom the first error I fixed it . unaccepted characters ( on the links )
But `<video:publication_date>2019-12-15T12:06:47</video:publication_date>` should look this 
<video:publication_date>2019-12-15T12:06:47+08:00</video:publication_date>

`<video:content_loc> or <video:player_loc>` Should be ending by extension . In other words 
Should be this : `https://cdn.avideo.com/videos/_YPTuniqid_5e2b5d82b974e3.71299757/hd/index.m3u8`

Google's words : 

> A URL pointing to the actual video media file. Should be one of the supported formats. 
> Google can crawl the following video file types: .3g2, .3gp2, .3gp, .3gpp, .asf, .avi, .divx, .f4v, .flv, .m2v,, .m3u8, .m4v, .mkv, .mov, .mp4, .mpe, .mpeg, .mpg, .ogv, .qvt, .ram, .rm, .vob, .webm, .wmv, .xap

**Comment by DanielnetoDotCom** [comment]
`video:publication_date` fixed

`video:player_loc` I am pretty sure is correct, we should direct it to the player, so it must be a HTML page

`video:content_loc` I do not think I can do that. especially when we use a secure directory plugin or download protection. it will require a token that will expire when Google crawls it. so any link I put will be useless due to the token. I guess I should remove it, what do you think?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Only one error left .
![image](https://user-images.githubusercontent.com/52116577/79802646-03655a00-8369-11ea-9147-ae9ee02988e3.png)

Maybe <video:content_loc> or <video:player_loc> should be removed or pointing to https://cdn.avideo.com/videos/_YPTuniqid_5e2b5d82b974e3.71299757/hd/index.m3u8

**Comment by DanielnetoDotCom** [comment]
Removed, if we point it directly to the file, for sure, we will have problems.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 
![image](https://user-images.githubusercontent.com/52116577/79809586-8b536000-8379-11ea-8dc8-6b94868ce7c1.png)
👍

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 
> `video:player_loc` I am pretty sure is correct, we should direct it to the player, so it must be an HTML page
> 
> `video:content_loc` I do not think I can do that. especially when we use a secure directory plugin or download protection. it will require a token that will expire when Google crawls it. so any link I put will be useless due to the token. I guess I should remove it, what do you think?

But still , it's important to make google create thumbnails and other stufs .
In case in the future you way wanna add it , on the plugin HLS , need to create `UserAgentWhitelist` where can tell the script to allow google to play the video .

**Comment by DanielnetoDotCom** [comment]
If I add the user agent whitelist I will make easier for people to access the paid content .

Google will use not create images , it will use the image we provided in the tag

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom This way sound off topic , but now that we're talking about the HLS video protection . If I open VLC media player , I take the url .m3u8 and I try to play it , it will not play , BUT the video will be downloaded , and huge wast of bandwidth . You can try it

**Comment by DanielnetoDotCom** [comment]
what do you mean download? VLC will download the video?

Just to make sure, download the m3u8 file does not mean it download the video.

**Comment by DanielnetoDotCom** [comment]
also even if you download the .ts files you will not be able to play without the encryption.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Exactly , the video will not play without encryption , but the download are not blocked . If you leave VLC open with the m3u8 will be draining bandwidth infinitely , since it fails to play , and keep re-trying .

**Comment by DanielnetoDotCom** [comment]
I do not think I have a way to block any User Agent to make a request. the problem is the VLC that does not give up on trying to play.
