### ISSUE TITLE
Live streaming issues

### ISSUE THREAD

**Issue by 231603** [WWBN/AVideo#2915]
**Describe the question**
A clear and concise description of what is your question.
Hi. I am unable to live stream to my server. I think I did everything correctly. Any help would be appreciated greatly.
**Screenshots**
Provide some screenshots to help us understand and explain your problem.
![image](https://user-images.githubusercontent.com/33844020/79810345-70143080-8338-11ea-9d65-b7eb2835b0d5.png)

![image](https://user-images.githubusercontent.com/33844020/79810294-54108f00-8338-11ea-895f-5a06f0bd1fca.png)

**Comment by akhilleusuggo** [comment]
what port are you using ?
What about your plugin settings ?
Have you installed tables ?
Have you tried to reset the password ?

**Comment by 231603** [comment]
> What port are you using ?
> What about your plugin settings ?
> Have you installed tables ?
> Have you tried to reset the password ?

Everything was set up correctly, but in NGINX config the I filled out the paths as they were shown in the documents, but in the documents they did not have the subfolder that I had, so my paths were wrong, and I did not have an SSL certificate which the plugin appears to use by default.

**Comment by akhilleusuggo** [comment]
that's why I have asked what port are you using . If 444 then without SSL will not work .
