### ISSUE TITLE
What should I do NEXT?

### ISSUE THREAD

**Issue by ysxiecumt** [WWBN/AVideo#2916]
**Describe the question**
I USE the instruction LINK below

https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer

to install my streamer and encoder.

After I finished installation by paste the commands, What should I do to open the website.

My OS is ubuntu 18 on VPS. 
I use the http://myIP/YouPHPTube/ it does not work. even as http://myIP/YouPHPTube/ install/

Thanks for your help
**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by akhilleusuggo** [comment]
1)what error are you getting ?
2)open browser and just type your IP server address . Does it show you Apache html file ?

**Comment by ysxiecumt** [comment]
> 1)what error are you getting ?
> 2)open browser and just type your IP server address . Does it show you Apache html file ?

Thanks for your reply.
I try it again. It works with IE.
