### ISSUE TITLE
error stream 

### ISSUE THREAD

**Issue by landydawood** [WWBN/AVideo#2917]
Hi guys i have question do u have any idea what i got this error

![ccccc](https://user-images.githubusercontent.com/63321733/79817809-46690280-8354-11ea-9b56-0cae307a5c8d.JPG)

**Comment by akhilleusuggo** [comment]
Need more details to determine where the problem is coming from .
Is your streaming server installed on the same server ?
Because I see you didn't not even install the server : http://34.70.168.93/AVideo/

**Comment by landydawood** [comment]
i did but i change the file path to http://34.70.168.93/nohadra/

**Comment by akhilleusuggo** [comment]
did you changed that path as well on the nginx config ?
Did you indicated that path as well on plugin ?

https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

**Comment by landydawood** [comment]
if you mean this 
 on_publish http://localhost/YouPHPTube/plugin/Live/on_publish.php;
                    on_play http://localhost/YouPHPTube/plugin/Live/on_play.php;
                    on_record_done http://localhost/YouPHPTube/plugin/Live/on_record_done.php;
yes i did it

**Comment by DanielnetoDotCom** [comment]
please screenshot your stats page with the URL

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom http://34.70.168.93:8080/stat this is his stat page , what left if the plugin to check

**Comment by landydawood** [comment]
i reinstall  Nginx-RTMP but still the error valid

**Comment by landydawood** [comment]
I found the problem when I installed in different name but when I installed on this path /YouPHPTube is working fine

**Comment by akhilleusuggo** [comment]
@landydawood post here you plugin details

**Comment by landydawood** [comment]
im Sure is right same you did and i already copy it for you and past it but still not working

**Comment by akhilleusuggo** [comment]
You've said is working with YouPHPTube and not working with other names . This means your configuration with other names is not correct .

**Comment by landydawood** [comment]
dose there any other configuration that need to be done ?
