### ISSUE TITLE
Live Streaming vs Conference Call

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2918]
youPHPTube is an amazing platform for videos and live streaming but can it potentially be used to host meetings between users now we have the mediastream api?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Zoom is getting banned in most of the countries right now for breaking all type of privacy and huge security issues

**Comment by akhilleusuggo** [comment]
https://www.forbes.com/sites/quickerbettertech/2020/04/19/google-bans-zoom-amazon-now-allows-non-essential-productsand-other-small-business-tech-news/#1fdaaca92a50

**Comment by DanielnetoDotCom** [comment]
Humm, thanks for the info @akhilleusuggo I am building it because a customer is paying me to do. and now it is too late, I am 95% complete

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Yes I understand , just wanted to inform you . All the emails used on zoom were basically hacked or all attackers has access to them . Thats why google and other companies has to ban them .

**Comment by millzee01** [comment]
omg thank god i didnt look at integrating zoom into my platform! thanks for the heads up!
