### ISSUE TITLE
See videos inside a group

### ISSUE THREAD

**Issue by Krystian95** [WWBN/AVideo#2919]
Hi, is possible to a user, belonging of 3 groups (eg. "A", "B" and "C"), see the videos contained inside only group "A"? Like now happens for a category or tag.

Many thanks

**Comment by DanielnetoDotCom** [comment]
yes, you can add a video in more than one group. also for users, they can be in more than one group at the same time.

**Comment by Krystian95** [comment]
Yes, and that's great. But a user can see the videos contained in a specific group?

**Comment by DanielnetoDotCom** [comment]
It the user is on the same group, yes . 

check this https://github.com/WWBN/AVideo/wiki/Create-non-public-videos-and-deal-with-user-groups

**Comment by Krystian95** [comment]
Sorry @DanielnetoDotCom, maybe I had explained badly. Is it possible to have a page that displays videos belonging only to group A (as if it were a playlist) even if I'm also registered to groups B and C?

**Comment by DanielnetoDotCom** [comment]
I see, sorry we do not have this option yet. it would require code customization.
