### ISSUE TITLE
Live Stream proposal for multiple relays ...

### ISSUE THREAD

**Issue by tgd1973** [WWBN/AVideo#2921]
My suggestion is regarding the possibility of expanding the total number of users who can simultaneously watch a live stream ... If we think about it, a 1Gbps connection can transmit for up to 1000 users ... but lately I often see channels on YT with 2000 - 5000 users ... and this can be done only with the help of multiple live servers ... first the master and others with the push function of making slave ...

I propose an addition to nginx_rtmp from the first live streaming server an addition in nginx config with push:

```
rtmp{
       server {
                listen 1935;
                chunk_size 4096;

                application live {
                        live on;
                        record off;
                        push rtmp://<other streaming service rtmp url>/<slave/relay1_key>;
                        push rtmp://<other streaming service rtmp url>/<slave/relay2_key>;
                }
        }
}
```

 towards a second server (it could also be together with the encoder) or also to a third server that receiving rtmp from the first and can retransmit it as nginx_rtmp.

What is unknown is the automatic redirection counting system to the user who watches the live which should be carried out within the Live plug (Broadcast to RTMP) as a modification or addition of the code.

The idea would be to automatically switch users from one index to another when reaching a certain preset number of Live visitors ....

![Live](https://user-images.githubusercontent.com/15127860/79899688-6ad4e580-840d-11ea-81fe-dd3f665ebeb0.png)

Only problem I see is that the relay servers may have a transmission delay that can be adjusted with the time of buffer by the master and the slaves, then you have to rethink the LiveUser plug to give correct indications about the number of users who are watching the stream.

**Comment by akhilleusuggo** [comment]
you mean a load balancer basically

**Comment by tgd1973** [comment]
It could also be thought of in this way ( load balancing), but the load balancing function affects more in uniform load on all servers, with the number of live users ... which could complicate more the module, LIVE (plugin).

Insted i said that for example if you set 100 users in LIVE plug, for each server ... when filling with 100 on the first nginx_rtmp, automatically switches to the second and so on ...

**Comment by akhilleusuggo** [comment]
The load balancing is the way for this type of scaling like the https://github.com/WWBN/AVideo-Storage ( not a load balancer ) , but would be better to split the stream on different servers since if your server is hosted on europe , the americans will have a lot packet lost .

Anyway thumb up for the idea

**Comment by DanielnetoDotCom** [comment]
@tgd1973 Thanks for the info and I like the idea.
I guess it is totally possible. but I do not think we can control the views. unless they provide some API to do it.

**Comment by tgd1973** [comment]
So at this point we have to wait for a better implementation of the API.
