### ISSUE TITLE
Can you change resolution of the front page poster thumbnails?

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#2922]
Hey,

where are the resolution of front page's poster thumbnails defined? I increased the size of the posters on .css but the resolution is now poor...

**Comment by DanielnetoDotCom** [comment]
Hi, right now you can not change the thumbs, it is hardcoded.

**Comment by tonuzo** [comment]
Ok thanks, I'd really like to see this improvement. The thumbs are very low quality..

**Comment by akhilleusuggo** [comment]
They should be in low quality . If not , the pages gonna takes ages to load .
I would even consider to make them in lower quality , or change the extensions to webp

**Comment by tonuzo** [comment]
Well, if I take a look to YouTube or Netflix, etc.. the thumbnail resolution is much higher and I don't see problem with that. Maybe if there was an option to choose..

**Comment by akhilleusuggo** [comment]
You can't compare a world wide project , with a self hosted project .
The thumbs are in really good quality , maybe you're using some cdn that are making your images looks poor .

![image](https://user-images.githubusercontent.com/52116577/80202457-53287780-862e-11ea-9af7-60940e84d353.png)

I see perfect quality .

**Comment by tonuzo** [comment]
I'm not complaining, I'm just making a suggestion...

**Comment by vomoplay** [comment]
I would also like to suggest that. I understand that it is coded for better loading of the page. But what are the rewards to make the best possible? In the gallery plugin I'm using the following:

![rfdg](https://user-images.githubusercontent.com/63978203/80269150-81847200-8683-11ea-87f1-7c71c0177318.png)

**Comment by DanielnetoDotCom** [comment]
Hi, @vomoplay what do you mean "But what are the rewards to make the best possible" ??

**Comment by vomoplay** [comment]
I meant what the resolution setting is the best possible

**Comment by DanielnetoDotCom** [comment]
In my opinion, I like the default one, but it is customizable.

just remember that Bootstrap uses 12 columns, so I recommend you to use only numbers that can divide 12 without rest.

**Comment by DanielnetoDotCom** [comment]
FYI https://github.com/WWBN/AVideo-Encoder/issues/253#issuecomment-626903073

**Comment by vomoplay** [comment]
Não vejo essa opção no meu plugin

**Comment by DanielnetoDotCom** [comment]
Tem que atualizar o site.

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform
