### ISSUE TITLE
Installation blues

### ISSUE THREAD

**Issue by tokunboajewole** [WWBN/AVideo#2923]
Hello sirs,

1) I followed this tutorial: https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server 
to setup a 'stream server'

Setup went ok, no issues. I clicked on the LIVE button and got the stream URL and key.

I plugged the details into an OBS installation, chose the custom-service/URL option, and I get the error: "failed to connect to server".

My setup is via VBOX where the streamer is on a guest, and my OBS install is on my host. I get the same error. I have connectivity(ping) between guest and host, disabled firewall on streamer, googled issues relating to similar error such as recording-path, IP bind and configured my settings are correct.

My OBS setup works well coz I can stream to youtube, etc.

Can you pls point me in the right direction on what Im missing.

2) The encoder URL in https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server 
to setup a 'stream server' is  https://encoder2.avideo.com/
Q: is this free to use by anyone? as in is it a free service? Can I use this encoder to stream to my own publicly hosted streamer?

3) I want to ask: what is the difference between AVideo and YouPHPTube. Reason, in some of your tutorials, I see this: sudo git clone https://github.com/WWBN/AVideo.git and in others its https://github.com/DanielnetoDotCom/YouPHPTube.git

regards
tokunbo

**Comment by akhilleusuggo** [comment]
1) failed to connect to server

This means your nginx server is not running . To find out go to http://youraddress:8080/stat
Also running : `sudo /usr/local/nginx/sbin/nginx` ( to start nginx )

2) It's a public encoder ( it's free , but there's a queue ) . You can use it only if your server is hosted with DNS , if you're using 192.168 .. or any private IP , will not work .

3) Read about it here : https://github.com/WWBN/AVideo/wiki#about-the-re-brand

**Comment by tokunboajewole** [comment]
Hi,

Thanks for the support. I guess my nginx server wasnt started. Thanks for the clarification on the other two issues.

regards
Tokunbo
