### ISSUE TITLE
Error saving configurations on streamer

### ISSUE THREAD

**Issue by mauriciojafer** [WWBN/AVideo#2924]
Hi, I'm getting an error saving configurations, trying to save encoder URL. 
The alert is "Sorry! Your configurations has NOT been updated! 
I analyzed the file videos/avideo.log and i see this error:.
Error in writeSql : (1366) Incorrect integer value: '' for column 'authCanUploadVideos' at row 1

Can you help me?.
![22-04-2020 01-39-38 p m](https://user-images.githubusercontent.com/64112567/80026141-de730300-849e-11ea-9aae-42e1610bfb7e.jpg)
Avideo Log File
[avideo.log](https://github.com/WWBN/AVideo/files/4518649/avideo.log)

**Comment by akhilleusuggo** [comment]
Try by enabling and disabling this functions : 
![image](https://user-images.githubusercontent.com/52116577/80026979-b5c52a80-84eb-11ea-8eaf-f8f2c1365a61.png)

Then save

**Comment by mauriciojafer** [comment]
@akhilleusuggo Yes I saw it and I already tried before making the post, but it did not work, even with all the possible options in configurations, enabling and enabling options to see if something changed but the error was the same.

**Comment by akhilleusuggo** [comment]
Can you confirm if in your database does exist column 'authCanUploadVideos' under Configuration ?

**Comment by mauriciojafer** [comment]
Sure.
![22-04-2020 04-27-27 p m](https://user-images.githubusercontent.com/64112567/80039944-39fcbb00-84b6-11ea-949a-bbe72d0d47c4.jpg)

**Comment by akhilleusuggo** [comment]
Looks like is not saving and that where the error is coming  . Can you change the value from 0 to 1 ? ( manually )
What version are you running ?

**Comment by mauriciojafer** [comment]
Database server
Server: Localhost through UNIX socket
Server type: MySQL
Server version: 5.7.29-0ubuntu0.18.04.1 - (Ubuntu)
Protocol version: 10
User: root @ localhost
Server character set: UTF-8 Unicode (utf8)

Web server
Apache / 2.4.29 (Ubuntu)
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $ Id: 3591daad22de08524295e1bd073aceeff11e6579 $
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 7.2.24-0ubuntu0.18.04.4

Avideo Versión.
A Video Platform v8.6

**Comment by mauriciojafer** [comment]
I changed the value to 1 and i got the same error.

**Comment by akhilleusuggo** [comment]
@mauriciojafer can you convert that value to `NULL` ? This should fix the issue .

**Comment by mauriciojafer** [comment]
It was the same problem for 4 columns of the table.
authCanUploadVideos
authCanViewChart
authCanComment
session_timeout

i changed the value to null

ALTER TABLE aVideo MODIFY authCanUploadVideos;
ALTER TABLE aVideo MODIFY authCanUploadVideos;
