### ISSUE TITLE
Change "Private" Video Label and Tab Color

### ISSUE THREAD

**Issue by I-See-Ninjas** [WWBN/AVideo#2925]
**Describe the question**
I am trying to find out how to change the color and label of the "Private" video marker to read "Member Video" and have a different color. 

I have looked at the CSS via Firefox Developer Tools, but it's a CSS file that is found in the /videos/cache/css/(long cache file name.css). The Rule for the Label is ".label-warning {    background-color:". If I change the color here, will it hold across the system or is there a CSS file elsewhere that I need to look at?

I also can't find how or where to change the name from "Private" to "Member Video". I went to Admin Panel > Misc > Plugins > CustomizeAdvanced > Edit Parameters and looked at the paidOnlyShowLabels and the paidOnlyLabel and neither of those change the name of the Tab. Where can I go to change that?

**Screenshots**
This is a screenshot of the Label I am trying to alter the color and name of. 
![20  04-22-20 @ 15,16,07_581x398_](https://user-images.githubusercontent.com/63745856/80031088-d28f3d00-84ae-11ea-8e0f-4e6434961879.jpg)

**Comment by DanielnetoDotCom** [comment]
Sorry we do not have this option yet
