### ISSUE TITLE
AD_Overlay

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2926]
Can you change the size of the area of ads ?
Adsense does give error since the dimensions are not correct 
![image](https://user-images.githubusercontent.com/52116577/80068956-29e1eb80-8549-11ea-8c3f-3d9e5565ac50.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I guess it is related to your Adsense configuration.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Adsense does not have any ad with less then 250px wide .
Can you run ads ( with adsense ) with the AD_Overlay on your sites ?
Because I can't find any ad on adsense that could run it .

**Comment by DanielnetoDotCom** [comment]
Usually, I leave it auto-size for my ads.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom But can you confirm that it works on your sites ?
I just want 1 screen to see it and know what to do .
I would appreciate it !

**Comment by DanielnetoDotCom** [comment]
I cannot confirm it anymore, I cannot approve Adsense on my domain due to the demo site where I host youtube videos and not copyrighted videos.

But here is how it was set up in the past and works fine.

![image](https://user-images.githubusercontent.com/18009293/80281611-c986b180-86e2-11ea-98d9-674232976600.png)

Check the ads size

![image](https://user-images.githubusercontent.com/18009293/80281626-e15e3580-86e2-11ea-8b3b-b2db1bb09a63.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom that doesn't solve the problem .
I've tried it already , and did to today again . Same problem .

![image](https://user-images.githubusercontent.com/52116577/80693761-2d8ee880-8adc-11ea-8d10-16dbb34eaf20.png)

**Comment by DanielnetoDotCom** [comment]
I do not know what to tell you.

I had this working before. are you using the compressed layout (non-theater mode?)

I guess the video width on theater mode is larger that that

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/80710229-30e39d80-8af7-11ea-9485-73aedc94b792.png)

What should be done ?

**Comment by DanielnetoDotCom** [comment]
Just disable the theater plugin and test it.

I guess the compressed mode is too small to show ads, maybe that is why.

**Comment by akhilleusuggo** [comment]
I'm also getting some css issues ( looking ) 

![image](https://user-images.githubusercontent.com/52116577/80711330-dba88b80-8af8-11ea-943f-157c24bbadc2.png)

The ads are into each other

**Comment by DanielnetoDotCom** [comment]
Yes, I understand. the left column is position absolute.

FYI, the compressed layout is not the default layout. but in the future, I may find a way to avoid it.

**Comment by akhilleusuggo** [comment]
Well , still same error , cleared cache and everything .
Is there any option to have the Main Menu compressed by default ?

At the least when watching videos ?
![image](https://user-images.githubusercontent.com/52116577/80712221-532aea80-8afa-11ea-9d62-aa1bda30c411.png)

**Comment by DanielnetoDotCom** [comment]
Did you try to use the Gallery layout instead of Youtube one?

In my opinion Gallery works better

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I managed to fix the problem with the ads , by giving a fixed size ( 728x90 )
The main Menu compress by default idk what to do with it . But I'll take a look at that later .
