### ISSUE TITLE
Live streaming problems

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#2927]
Hey,

I have a problem setting up Live Stream. I have set up everything following the instructions here [https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server](url)

My Live plugin settins here: 

![image](https://user-images.githubusercontent.com/63721378/80073406-a53e9f80-853f-11ea-9ed6-00b68e4bef80.png)

the error i get in ../Live-page: 

> The media could not be loaded, either because the server or network failed or because the format is not supported. 

Nginx is running. 

This is my log:

`
[23-Apr-2020 07:41:55 UTC] PHP Fatal error:  Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:8888": Address already in use in /var/www/YouPHPTube/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php:164
Stack trace:
#0 /var/www/YouPHPTube/plugin/LiveChat/ratchet/react/socket/src/Server.php(31): React\Socket\TcpServer->__construct('tcp://0.0.0.0:8...', Object(React\EventLoop\StreamSelectLoop), Array)
#1 /var/www/YouPHPTube/plugin/LiveChat/ratchet/cboden/ratchet/src/Ratchet/Server/IoServer.php(59): React\Socket\Server->__construct('0.0.0.0:8888', Object(React\EventLoop\StreamSelectLoop))
#2 /var/www/YouPHPTube/plugin/LiveChat/chat-server.php(20): Ratchet\Server\IoServer::factory(Object(Ratchet\Http\HttpServer), '8888')
#3 {main}
  thrown in /var/www/YouPHPTube/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php on line 164
`

**Comment by DanielnetoDotCom** [comment]
this fatal error is not related to the livestream.

if you are using https, make sure your Nginx also use https
