### ISSUE TITLE
Manual user management

### ISSUE THREAD

**Issue by andrkac** [WWBN/AVideo#2928]
I  want to create internal youtube-like service for family kids. So privacy is very important.
I see userMustBeLoggedIn setting which is a must, but - may I constrain it only for only manual user registartion?
I see I can turn off all method of registration in "Social Login Settings" and then use user creation way in admin panel. Is this exactly what I need?

**Comment by DanielnetoDotCom** [comment]
Hi

you can disable the signup option and also check the userMustBeLoggedIn option. it would do the trick.
