### ISSUE TITLE
How to record video streams

### ISSUE THREAD

**Issue by tokunboajewole** [WWBN/AVideo#2929]
Dear sirs,

Is it possible to record video streams - the same way youtube does? as in after livestreaming, its saved on the server - into the users page/account/somewhere?

On the Live page, I see a green "save stream" button below-right, however after clicking it and later checking my video library, the streamed video is not there.

regards
Tokunbo

**Comment by DanielnetoDotCom** [comment]
yes, it is possible.

https://github.com/WWBN/AVideo/wiki/Record-Live-Stream

**Comment by tokunboajewole** [comment]
Hi,

1) at step#3,

error: nginx: [emerg] "record_max_size" directive invalid value in /usr/local/nginx/conf/nginx.conf:30

so I changed the value to 1024M

then tried to restart nginx again, I get this error: nginx: [error] open() "/usr/local/nginx/logs/nginx.pid" failed (2: No such file or directory)

3) theres no plugin with name as "SendRecordedToEncoder" listed in my plugin page.

regards
tokunbo

**Comment by akhilleusuggo** [comment]
you need to get it from https://youphp.tube/plugins/

**Comment by DanielnetoDotCom** [comment]
@tokunboajewole also looks like your Nginx installation is not correct.

**Comment by akhilleusuggo** [comment]
Ok no, is not the installation wrong. I stumbled on the same issue. On my raspberry pi having the same issue. Try lower value.
Example 1280M does work. Why is this happening? Good question, I'm investigating. 

Mostly has to do with the ram , had same issue with KVM.
