### ISSUE TITLE
Categories - unique and primary keys

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#2930]
Hi,

We have multiple users with the same clean name "dave smith" but different user_id's and email addresses.

I dave smith no.1  creates a category called "personal" then dave smith no.2 and no.3 cannot create the same category because the table fields are unique.

Can you see any issue if we turn off description as unique and primary and also turn off clean_name as unique as the id of the category is unique?

**Comment by akhilleusuggo** [comment]
But is good to not have repeated categories .
If the user 2 want to tag a video on the categorie , he should use the category from user 1

**Comment by millzee01** [comment]
they are creating private categories so i can't see why it would be a problem

**Comment by akhilleusuggo** [comment]
that would be the need the use of user group

**Comment by millzee01** [comment]
yeah each user get their own user group automatically when their account is created so when they upload videos they upload them to their own group by default.
