### ISSUE TITLE
HTML appears blank at base location and is broken in install screen

### ISSUE THREAD

**Issue by Temmie19** [WWBN/AVideo#2931]
When on the AVideo folder at 127.0.0.1/AVideo, the page is just blank. The install page is broken, and after installing the redirect doesn't work.

Running clean VM of Debian 10 with Xfce.

![Screenshot_2020-04-23_16-42-32](https://user-images.githubusercontent.com/7474105/80156963-6a119000-8582-11ea-8cda-b6db69808393.png)
![Screenshot_2020-04-23_16-49-18](https://user-images.githubusercontent.com/7474105/80156965-6aaa2680-8582-11ea-8681-8a3ba50ba13e.png)

**Comment by DanielnetoDotCom** [comment]
Looks like you are missing so many things.

try to fix all red and yellow alerts.

also, make sure your mod rewrite is enabled.

**Comment by Temmie19** [comment]
Nothing is missing at all. And mod rewrite is enabled, and the videos folder has 755, and it belongs to the apache account.

**Comment by DanielnetoDotCom** [comment]
So try to install it in a Ubuntu 18.04
