### ISSUE TITLE
Social Buttons

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#2932]
I would like to include vk.com in the social buttons.

**Comment by DanielnetoDotCom** [comment]
Add it is not complicated.

that is the file https://github.com/WWBN/AVideo/blob/master/view/include/social.php

also feel free so send a pull request.

**Comment by Donnerstein** [comment]
Thank you.
I added the following, it works.

```
$vkURL = "http://vk.com/share.php?url={$url}&title={$title}";

<li><a href="<?php echo $vkURL; ?>" target="_blank" class="icovk" title="VK"><i class="fab fa-vk"></i></a></li> 
```
