### ISSUE TITLE
I have questions on functionality

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#2933]
Hello I have questions

I am really sorry for my English

you have a site that I like very much with features that I like

there is the possibility of using a cdn for users who watch live live
Load balancing

for the rtmp server if I have 20 servers, will I have the same address for the 20 servers
rtmp: //mon.site/live

the site is compatible with cloudflare ?

it is possible to delete all APIs from youtube

I show you 2 picture one of your site

the one on your site that is really ugly
https://prnt.sc/s4yjab

a montage that I made (is it possible to have the same thing?)
https://prnt.sc/s4ypbt

the chat has its own server where it is integrated into the site

are you available quickly enough to do customization work?

**Comment by DanielnetoDotCom** [comment]
> there is the possibility of using a cdn for users who watch live live
> Load balancing

yes, but CDN and load balance are 2 different things. you are probably confusing things
 
> for the rtmp server if I have 20 servers, will I have the same address for the 20 servers
> rtmp: //mon.site/live

Sorry I have no Idea how to do it. but I guess you are looking for a CDN, you may need to ask directly to the CDN company how to do it.

> the site is compatible with cloudflare ?

yes

> it is possible to delete all APIs from youtube

I do not recommend you to change the main core code

> I show you 2 picture one of your site
> > the one on your site that is really ugly
> https://prnt.sc/s4yjab
> > a montage that I made (is it possible to have the same thing?)
> https://prnt.sc/s4ypbt

We are improving the chat2 plugin layout

> the chat has its own server where it is integrated into the site

It is integrated

> are you available quickly enough to do customization work?

For new features, yes you can hire us, we just do not Layout jobs
