### ISSUE TITLE
When do AVideo and AVideo-Encoder support Ubuntu20.04 LST ?

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#2934]
In Japan, Ubuntu20.04 LST release 24-Apr-2020(JST)

I tried to install AVideo and AVideo-Encoder next URL
https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer

But many modle not found.(For example php-txt)

When do AVideo and AVideo-Encoder support Ubuntu20.04 LST ?

**Comment by akhilleusuggo** [comment]
I've tested it just today , and works perfectly .
You can ignore : 
```
sudo apt install php-mbstring php-gettext
sudo phpenmod mbstring
sudo systemctl restart apache2
```
Work fine

**Comment by hnagasawa** [comment]
I installed AVideo fine.
But AVideo-encoder did not install finish.
![13](https://user-images.githubusercontent.com/46562199/80328725-23ba7a80-887b-11ea-94f7-a761bc032fa5.png)
I clicked "instal now"
![14](https://user-images.githubusercontent.com/46562199/80328782-506e9200-887b-11ea-999b-48b62cdac08c.png)
I wait long time but It did not finish.
What do I check ?

**Comment by akhilleusuggo** [comment]
the patch to AVideo maybe is not correct 
Isn't it http://192.168.1.155/Avideo ?

**Comment by hnagasawa** [comment]
Stream's URL http://192.168.1.155/AVideo
Encoder's URL http://192.168.1.155/AVideo-Encoder

**Comment by akhilleusuggo** [comment]
I'm talking about your picture of the installation !
https://user-images.githubusercontent.com/46562199/80328782-506e9200-887b-11ea-999b-48b62cdac08c.png

As you can see here , you're poiting your streamer site to be http://192.168.1.155/ ( and that's wrong )

Your streamer site should be http://192.168.1.153/AVideo not http://192.168.1.155/

**Comment by hnagasawa** [comment]
I am sory. I miss type streamer's URL. Please see next picture.
Stramer's URL http://192.168.1.155/AVideo
![15](https://user-images.githubusercontent.com/46562199/80346262-6e50ec80-88a5-11ea-9400-998d97b7f297.png)

**Comment by ronaldod** [comment]
Use that "http://192.168.1.155/AVideo" in the AVideo streamer Site URL" box on the encoder page. You filled in only "http://192.168.1.155/".

**Comment by hnagasawa** [comment]
@akhilleusuggo 
@ronaldod 
Thank you for your support.
