### ISSUE TITLE
When using mobile, BigVideo area off

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#2935]
Hey

When you use the (netflix-style) site from mobile, it would be nice if the "bigvideo" area was turned off. So you would only have the video categories carousel visible. Or can this be done already?

![image](https://user-images.githubusercontent.com/63721378/80203465-1d2fc700-861f-11ea-829c-7aa9f156aa24.png)

**Comment by DanielnetoDotCom** [comment]
Try to add this code in your site configuration -> Script Code -> Head Code


```
@media (max-width: 767px) {
    #bigVideo {
        display: none;
    }
}
```
