### ISSUE TITLE
Uploading videos into the video folder directly

### ISSUE THREAD

**Issue by tokunboajewole** [WWBN/AVideo#2936]
Hello sirs,

I have some videos on my external hard drive and I uploaded a couple into /var/www/html/AVideo/videos.

Is there a command that I can run so that it can be visible in my video list.

regards
tokunbo

**Comment by akhilleusuggo** [comment]
nop

**Comment by sipero** [comment]
If you really want to do it this way just follow the directions of how to do this but not in that folder you need to use a diiferent folder

**Comment by akhilleusuggo** [comment]
nor that could be done 
You will need to insert tables and write manually the videos's data .
If you just upload them to /videos , then when going to http://yourip/YouPHPTube/videos/Video_Name , will only download the video , not play it .

**Comment by DanielnetoDotCom** [comment]
Please check this https://github.com/WWBN/AVideo/wiki/Bulk-Upload-Videos

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I guess he wants without encoding them

**Comment by DanielnetoDotCom** [comment]
I see, sorry but I do not have any option without encoding it.

**Comment by tokunboajewole** [comment]
Hi
Can you pls clarify 'the directions' and what folder.
RegardsTokunbo
    On Friday, April 24, 2020, 03:17:11 PM UTC, sipero <notifications@github.com> wrote:  
 
 


If you really want to do it this way just follow the directions of how to do this but not in that folder you need to use a diiferent folder
