### ISSUE TITLE
Pagination on homepage was gone

### ISSUE THREAD

**Issue by boom02456** [WWBN/AVideo#2938]
I would like to ask for pagination on homepage, is there any settings to re-enable this? it's gone from my homepage and now all videos are full listed :(

p.s. it's page number section

**Comment by boom02456** [comment]
I can see that the Style Display
 has been set to none, but I cannot find any settings for this.

![Screen Shot 2563-04-24 at 21 41 16](https://user-images.githubusercontent.com/36606195/80224819-70803480-8674-11ea-9568-d50805d41998.png)

**Comment by DanielnetoDotCom** [comment]
why is it happening?

what exactly row is that?

**Comment by boom02456** [comment]
I checked in Inspect, and saw that it not show

**Comment by boom02456** [comment]
I just tested and I think it happen after I change folder name, could you please suggest what steps need to be done after change the folder name?

**Comment by DanielnetoDotCom** [comment]
I cannot see any relation to change the folder name.

can you reproduce it on demo site?

Right now I do not know where does it come from;

are you using the gallery layout?

**Comment by boom02456** [comment]
Yes, I'm using Gallery Layout

**Comment by boom02456** [comment]
If I reproduce to change the folder name, how can I done in the demo site?

**Comment by DanielnetoDotCom** [comment]
I cannot see any relation to change the folder name. so do not need to do it.

**Comment by boom02456** [comment]
ow, so how can I investigate it? I've checked in the config that I didn't enable permalink so it's not the previous issue.

**Comment by DanielnetoDotCom** [comment]
I do not think permalink has something to do with this issue. 

For me it looks like something related with some JavaScript

**Comment by boom02456** [comment]
so I need to check all the files that related to this Javascript right?
Could you please tell me which file does this Javascript be in?

**Comment by DanielnetoDotCom** [comment]
Is not that. Test on demo site. If the same happen the problem is on my code. If it is happen only in your site look if you made some customization and undo it

**Comment by boom02456** [comment]
ok, thanks Daniel, I will check all the mod I've done :)

**Comment by DanielnetoDotCom** [comment]
What was the problem?

**Comment by boom02456** [comment]
I found the problem now, and can replicate issue in Demo site,

If you try disabling the section before Trending/Date Added (I mean to disable the top section e.g. suggestion) the pagination in Trending/Date Date added will be missing

**Comment by DanielnetoDotCom** [comment]
Thanks, bug found and fixed.
