### ISSUE TITLE
Search Magnifier is hiding the Go Live Button kinda

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2939]
<img src="https://static.buddylist.co/x/download%20%281%29.png" style='width:100%;' border="0" alt="Null">

Full desktop view

**Comment by DanielnetoDotCom** [comment]
Hi, you probably have too many buttons and a small resolution.

we made it to avoid break lines

but maybe you need to clear your browser cache.

here is a screenshot of 1200px wide

![image](https://user-images.githubusercontent.com/18009293/80237088-80772480-8632-11ea-90cd-f29308a7f082.png)

**Comment by JoshWho** [comment]
I can see this using a different computer. it is not in the CACHE. I even removed a item from the top menu and it is still covered.

**Comment by DanielnetoDotCom** [comment]
What browser are you using? And what resolution?

**Comment by JoshWho** [comment]
Chrome 1280

**Comment by JoshWho** [comment]
I just added 3 spaces to the text Go Live Now I can see it

**Comment by DanielnetoDotCom** [comment]
I am also using chrome , and I could not reproduce. The last thing I Chan check is the browser version. I am away from pc now so I cannot check my version

**Comment by JoshWho** [comment]
MY Linux one is Version 71.0.3578.98 (Official Build) (64-bit)

My windows one is Version 80.1.3902.163 (Official Build) (64-bit)

**Comment by JoshWho** [comment]
The Magnify glass cuts off the Logo on Mobile View with Android

**Comment by akhilleusuggo** [comment]
works fine for me too 
![image](https://user-images.githubusercontent.com/52116577/80268699-3a61a580-86b2-11ea-926f-d3c84595d967.png)

You can always use ctrl + wheel button mouse scroll up and down to zoom

**Comment by JoshWho** [comment]
Of course it looks fine on a desktop.

**Comment by JoshWho** [comment]
I just got an email from a user on there that says he doesn't see the Live button at all. I think he uses safari.

**Comment by akhilleusuggo** [comment]
@JoshWho I've noticed that when using different themes . Daniel added some new feature ( that is not working for me ) and this things happened .

![image](https://user-images.githubusercontent.com/52116577/80274524-c63ff580-86e3-11ea-8693-f7ccb1bb80bb.png)

I don't know if also for others can't see what this feature provides .

**Comment by wetubeclub** [comment]
Hello,
download the new version of the plugin customize upload and you're ready I had the same problem and it was solved
![customize](https://user-images.githubusercontent.com/60543030/80277549-03aa8000-86f0-11ea-8e82-b6ed4fe9ae83.jpg)

**Comment by akhilleusuggo** [comment]
@wetubeclub what plugin ? customize upload ?
I see no plugin with such name .
https://youphp.tube/plugins/ ?

**Comment by akhilleusuggo** [comment]
Ok , I see what you're talking about , that's why the branding AVideo was back to bottom of the page.
Thanks for the info

**Comment by wetubeclub** [comment]
I mean This plugin, if you have purchased 
![customize1](https://user-images.githubusercontent.com/60543030/80278209-b846a080-86f4-11ea-81eb-694fb4a8268a.jpg)

**Comment by wetubeclub** [comment]
you are welcome!
I saw the same thing this morning and was wondering what happened
then i realized i had to upgrade the plugin!!

**Comment by DanielnetoDotCom** [comment]
@JoshWho I do not have a Linux to test it now. but the same is happening on Windows?

**Comment by wetubeclub** [comment]
yes daniel i have the same problem too
on google and microsoft edge
is covered by the search
google
![search](https://user-images.githubusercontent.com/60543030/80282752-885ac580-8713-11ea-8050-05d86368e380.jpg)

microsoft edge
![microsoft](https://user-images.githubusercontent.com/60543030/80282763-93155a80-8713-11ea-9e53-a72f31baf5ca.jpg)

**Comment by DanielnetoDotCom** [comment]
The problem was I was trying to minify the css, and it was messing up things.

I disable it for now (Need to update the code and clear the cache)

all looks fine now

**Comment by JoshWho** [comment]
I ran the update and it says I am already up to date

**Comment by JoshWho** [comment]
I see u already updated it. Works good now :) Thank you

**Comment by DanielnetoDotCom** [comment]
@JoshWho I updated for you, the message is for others that may also have this issue

**Comment by wetubeclub** [comment]
nothing happened to me it's the same!!

**Comment by DanielnetoDotCom** [comment]
make sure after the update, you clear your cache directory

**Comment by wetubeclub** [comment]
i did it many times,
to you it appears normally or not? i mean my site!

**Comment by DanielnetoDotCom** [comment]
I am looking into your site @wetubeclub

**Comment by DanielnetoDotCom** [comment]
@wetubeclub 

You had this enabled. that was also the reason for @JoshWho . but before the update, I was minimizing all CSSs (even if you do not check this). but I recommend disable it until we fix this bug.

![image](https://user-images.githubusercontent.com/18009293/80289700-b7bf0180-8716-11ea-8bd6-abbdf2497c39.png)

**Comment by wetubeclub** [comment]
working now!! Thank you very much Daniel for your time
Being always well
Ilias

**Comment by wetubeclub** [comment]
Working now!! Thank you very much Daniel  for your time!!
Being always well
