### ISSUE TITLE
The same thumbnail in big video section is much clear than the thumbnail in small videos

### ISSUE THREAD

**Issue by sharad22gupta** [WWBN/AVideo#2941]
the thumbnails are the same but clarity is different? @akhilleusuggo  @DanielnetoDotCom 
![Annotation 2020-04-25 004437](https://user-images.githubusercontent.com/15939963/80249918-5b190380-8690-11ea-95d8-9e008cce3465.png)

**Comment by akhilleusuggo** [comment]
The script use a resize to match the size of the thumbnails .
Is better not to change those things . It may make your site very lagy once you have over 50 videos on your welcome page ( www.example.com / )

**Comment by sharad22gupta** [comment]
in small video thumbnail, a black line comes on the right side of every video. can you tell me the script? is it on object/video.php page? @akhilleusuggo

**Comment by akhilleusuggo** [comment]
take a look here https://github.com/WWBN/AVideo-Encoder/blob/20299d62272e1bbd97dc1b480db8cbff92778c1c/objects/Encoder.php

**Comment by sharad22gupta** [comment]
I haven't downloaded avideo encoder so is it using it from there or for avideo its in avideo folder.
@akhilleusuggo

**Comment by DanielnetoDotCom** [comment]
To speed up your site we use small resolution images on the small thumbs and a larger resolution on the big video.

but for all videos, you have, in your server, about 3 different resolutions for each video. and display it depends on what is the needed resolution.

**Comment by sharad22gupta** [comment]
where do i change the thumbnail of small video @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
It is hardcoded. there is no option to change it.

if you want to change you will need to change the code in some places. probably on encoder and in the streamer

**Comment by DanielnetoDotCom** [comment]
FYI https://github.com/WWBN/AVideo-Encoder/issues/253#issuecomment-626903073
