### ISSUE TITLE
Any way to turn off Widescreen view for Live Stream on Desktop?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2942]
Would like to be able to disable the theater wide screen view of the live stream player so I can use the static layout for the chat and it will be next to the video.

That would be terrific and so many people will be excited over it. I get request for that all the time.

For Example
<img src="https://static.buddylist.co/x/staticchat.jpg" style='width:100%;' border="0" alt="">

**Comment by DanielnetoDotCom** [comment]
I am sending updates, also update the Chat2 plugin is required

**Comment by JoshWho** [comment]
FOr some reason now the chat is below the footer with Static Chat enabled.

<img src="https://static.buddylist.co/chatfooter.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
I forgot to mention. you need to update the plugins also.

I just did it for you.

**Comment by JoshWho** [comment]
Thank you Looks beautiful now. This is wonderful I can't wait for the others to see it now. Super sweet!!!!!!!!!!!!!!!!!!

**Comment by CROSSMediaNet** [comment]
Quick question: how to update the plugin?

**Comment by DanielnetoDotCom** [comment]
@CROSSMediaNet download and overwrite it in your site.
