### ISSUE TITLE
HTML leak in Un mute Message that pops up.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#2943]
<img src="https://static.buddylist.co/x/vishtml.png" style='width:100%;' border="0" alt="Null">

**Comment by akhilleusuggo** [comment]
Looks like you're outdated . 
A correction were send 7h ago

**Comment by JoshWho** [comment]
OK New Problem Text is in White font on White background

<img src="https://static.buddylist.co/x/media.png" style='width:100%;' border="0" alt="Null">

**Comment by akhilleusuggo** [comment]
have you updated to 8.7 ?
Clear the cache

**Comment by JoshWho** [comment]
Yes fully updated. Using Gallery theme

**Comment by JoshWho** [comment]
I fixed it by adding
<style>
body {
    font-family: "Roboto","Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 14px;
    line-height: 1.42857143;
    color: #2c2c2c;
    background-color: #2c2c2c;
}
</style>

to the custom header. CLosed.
