### ISSUE TITLE
Help for VAST Ad Server

### ISSUE THREAD

**Issue by vomoplay** [WWBN/AVideo#2945]
I have the following vast code to add: https://www.movcpm.com/watch.xml?key=1356586436d6c4f63ea89c9555fa7044

How to add it? The only option you have is to add the url of a mp4 video. And the ad code cannot be edited.

![01](https://user-images.githubusercontent.com/63978203/80269318-1a67bd00-8685-11ea-93a7-47cc62801fc0.png)
![02](https://user-images.githubusercontent.com/63978203/80269322-1d62ad80-8685-11ea-85db-4e8eee721528.png)

**Comment by JoshWho** [comment]
JUst start typing the name of the video you have uploaded and it will suggest it to be clicked on.

**Comment by vomoplay** [comment]
I want to add the ads ad partner code.

**Comment by DanielnetoDotCom** [comment]
do you mean you have a VAST code to add it?

if you do, you can use the GoogleAds_IMA plugin https://github.com/WWBN/AVideo/wiki/Plugin:-GoogleAds_IMA---Videos-Ads-on-your-page

please check this https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Advertising

**Comment by vomoplay** [comment]
OK thank you
