### ISSUE TITLE
When video is upluoad by default is visible

### ISSUE THREAD

**Issue by gamersalpha** [WWBN/AVideo#2946]
Hello all, when a video is added on Youphptube is public, how make all video upluoaded private adn let the user make it plublic

thanks

**Comment by akhilleusuggo** [comment]
`Plugin , CustomizeAdvanced `

![image](https://user-images.githubusercontent.com/52116577/80277818-5a1cbc00-86fa-11ea-8a5a-0e03dd6514a7.png)

**Comment by gamersalpha** [comment]
Hello look like works thanks

i can't found the makeVideosUnlistedAfterEncodr only the first

**Comment by DanielnetoDotCom** [comment]
@gamersalpha update your code.

the unlisted was release recently.

**Comment by gamersalpha** [comment]
i install like a week 
![image](https://user-images.githubusercontent.com/32466950/80290281-a2f96280-8744-11ea-988d-61f760457d2d.png)

i have to update

**Comment by DanielnetoDotCom** [comment]
yes, we are 8.7 now

**Comment by gamersalpha** [comment]
Hello

my avideo system says i got no update ?

![image](https://user-images.githubusercontent.com/32466950/80302320-9a874300-87a9-11ea-83a7-9989afb72239.png)

something i miss ?
