### ISSUE TITLE
Subtitle - Export video but no subtitle ?

### ISSUE THREAD

**Issue by gamersalpha** [WWBN/AVideo#2948]
Hello there, 

on my video how to get the subtitle please ?

i can't found him on the video :'(

EDIT :

ok i see it's a paid plugin :'( 

![image](https://user-images.githubusercontent.com/32466950/80289984-aab80780-8742-11ea-8aa6-58cb3684dbfc.png)
ok so i paid him but can i m sur it's works with my download video how to be sure it's works thanks

Edit II : 

ok i will bought the plugin, but how works with video  i download ?

when i download video the subtitle will come with the video automaticly ?

**Comment by akhilleusuggo** [comment]
no , you need to upload the subtitles manually

**Comment by akhilleusuggo** [comment]
go to demo site and test it

**Comment by gamersalpha** [comment]
Hello
ok so demo site is here : 

the admin pass is : 
admin
123

but when i try to upluoad my video i got this : 

![image](https://user-images.githubusercontent.com/32466950/80302229-1cc33780-87a9-11ea-87ec-78e4f8310d64.png)

and works on my avideo site 

![image](https://user-images.githubusercontent.com/32466950/80302277-4e3c0300-87a9-11ea-8197-eb6422255898.png)

???

**Comment by gamersalpha** [comment]
>  subtitles m

OO
thats will be hard

can i add the option directly in youtube-ddl command to addd all subtitles found evrytimes on downlaod ?

**Comment by akhilleusuggo** [comment]
maybe downloading a video from a non well known site , maybe youtube-dl does not recongnize it .
Look , try with youtube , if you have the same problem , then maybe worth taking a look . If not , this topic is useless .
Youtube-dl has nothing to do with this project

**Comment by gamersalpha** [comment]
Hello

avido is web interface of youtub-dll and u says me :

Youtube-dl has nothing to do with this project

if youtube-dll have new foncion that's means we can adding interfacing with avideo

**Comment by akhilleusuggo** [comment]
with respect , I think you have no idea what you're saying .
Please visit youtube-dl : https://github.com/ytdl-org/youtube-dl

I don't really understand you , but you are confusing many things . Youtube-dl and Avideo has nothing to do with each other .

**Comment by DanielnetoDotCom** [comment]
@gamersalpha you should check your encoder log for some clue.
