### ISSUE TITLE
Live stream; streaming limits

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#2950]
I have two users who have set up paid movie streaming sites using me as their streaming service and they haven't paid me.  I have to block them, but I know this will continue.  I think the best thing would be  having the ability to set streaming limits.  So, I don't have to watch 24 hours a day.

**Comment by DanielnetoDotCom** [comment]
Hi, sorry I do not understand.

are you talking about the paid subscription?

sorry I am confused of what is your goal

**Comment by heiress01** [comment]
The goal is to limit users from live streaming 24 hrs per day, for free.  I want to set up subscriptions based on streaming limits.  As it is right now, no matter what subscription level is set the same streaming limits apply to all.  I want to set levels: ie. level 1:  2 hours streaming.  Level 2:  8 hours streaming.  Level 3: 24 Hours streaming.

**Comment by DanielnetoDotCom** [comment]
this require some code and new plugin development.

if you want a quote, please send a detailed request to developer@youphptube.com

**Comment by ronaldod** [comment]
I would combine it then with also upload limits for video in hours.
Based on access/payment level there will be settings for the amount video time they can upload. Why not GB i prefer a platform with quality video then poor video.

**Comment by DanielnetoDotCom** [comment]
I see, but the video quality is defined by you in your encoders.
