### ISSUE TITLE
Trying to reset password 

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#2951]
Under the customize user plug in I turned force email log in. 
I am not getting user name or password word incorrect. 
So I  attempt to reset password and now I am getting. 
![62F0D7B2-6032-4057-9DA2-29169950BA95](https://user-images.githubusercontent.com/58601786/80299470-78f66f00-8749-11ea-8135-c5a27b525315.png)
![51EC8A77-524E-4F89-A7F4-ED54E1B1C4AC](https://user-images.githubusercontent.com/58601786/80299475-7c89f600-8749-11ea-8a0d-cacf545ae1b9.png)
The email setup is correct as  I get email verification notices.

**Comment by DanielnetoDotCom** [comment]
Hi 2 things ....

1. there is an error on the code due the captcha display, I just sent a fix for that. please update your site code.

2. looks like you do not have an email set up for this user. try to reset the password with this tutorial https://github.com/WWBN/AVideo/wiki/Reset-a-Password

**Comment by barrunning** [comment]
I can’t update the code as I can’t  log in. The user is myself so I know there is an email. This problem started after I turned on force email log in.

**Comment by barrunning** [comment]
I can't reset password via email due to the system saying user doesn't have an email. I can't log into system because of  the same problem ,

**Comment by barrunning** [comment]
This is a fresh install from yesterday. devbarrunnigmovement and barrunningmovement, cloudfront set up. The cloudfront is working great by the way.
