### ISSUE TITLE
AD-Server VAST ad SERVER plug-in is not working.

### ISSUE THREAD

**Issue by alexsodre1981** [WWBN/AVideo#2952]
![configuraçãocorreta](https://user-images.githubusercontent.com/64347872/80300001-58411000-876f-11ea-983c-bcf1b61e6c38.png)
![nao](https://user-images.githubusercontent.com/64347872/80300085-f03ef980-876f-11ea-9b5a-398324fc295c.png)
![anunciook](https://user-images.githubusercontent.com/64347872/80300141-722f2280-8770-11ea-87c0-6b92d80acacb.png)

AD-Server VAST ad SERVER plug-in is not working.
I made the correct settings but it doesn't look like the ads and the page shows an error in the xml

email alexsodre@msn.com
Thank you for your help

**Comment by akhilleusuggo** [comment]
have you installed the db tables ? ( re-try to install them )
For me it's working .

**Comment by alexsodre1981** [comment]
I re-installed the tables three times
vast_campaigns
vast_campaigns_has_videos
vast_campaigns_logs
installed in two different domains and in two databases
they all presented the same error

**Comment by alexsodre1981** [comment]
AdsForJesus (AdsForJesus)  
it's working normal

**Comment by alexsodre1981** [comment]
http://armybrasil.com/video/AVideo-master/
login admin
password qwer9875

I just re-packed everything again and have the same error

**Comment by akhilleusuggo** [comment]
I have to say you're right , is not playing the video in my case
And I'm not sure if it's because of the hls video protector and the tokens .
I've tried with an mp4 video and also not working .
No idea .

PS: Ok , found something : 

```
[26-Apr-2020 10:43:16 Europe/Helsinki] PHP Notice:  Undefined index: mp4_Low in /var/www/html/YouPHPTube/plugin/AD_Server/VAST.php on line 72
[26-Apr-2020 10:43:16 Europe/Helsinki] PHP Notice:  Undefined index: mp4_SD in /var/www/html/YouPHPTube/plugin/AD_Server/VAST.php on line 72
[26-Apr-2020 10:43:16 Europe/Helsinki] PHP Notice:  Undefined index: mp4_HD in /var/www/html/YouPHPTube/plugin/AD_Server/VAST.php on line 72

```

**Comment by alexsodre1981** [comment]
https://www.armybrasil.com/video/AVideo-master/plugin/AD_Server/VAST.php

**Comment by akhilleusuggo** [comment]
what the logs say ?
And why are you posting your login and password ? xD

**Comment by alexsodre1981** [comment]
if someone can do a test to help me, this domain is test is not the main
can access to test

**Comment by akhilleusuggo** [comment]
just post the logs when you click on advertise manager , because it's not loading .
Also try to delete the table from the database and re-install it .
Anyway without the logs , hard to say

**Comment by alexsodre1981** [comment]
![apresentouerro](https://user-images.githubusercontent.com/64347872/80302631-87607d00-8781-11ea-90b4-3ce4ed624c3d.png)

this error appeared, I don't know what can be

**Comment by alexsodre1981** [comment]
version="1.0" encoding="UTF-8"

delete this code and the page did not show any more error, but the video does not appear ads

**Comment by akhilleusuggo** [comment]
maybe that means you had enabled
![image](https://user-images.githubusercontent.com/52116577/80308846-e81ba400-87d9-11ea-9c61-7b721846faab.png)

**Comment by DanielnetoDotCom** [comment]
@alexsodre1981 the error is the `HTTP ERROR 500` correct?

if yes, this error must be in the log file.

**Comment by alexsodre1981** [comment]
is correct, how do I fix the log file?

**Comment by DanielnetoDotCom** [comment]
First, show the log file to us https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
