### ISSUE TITLE
Update - When we know when get new version ?

### ISSUE THREAD

**Issue by gamersalpha** [WWBN/AVideo#2954]
Hello evryone, 
do u have a newsletter or a discrod channel other ?

how we know a new release is available and need to update ?

because now the page of : 
https://192.168.50.24/YouPHPTube/update

don"t say it ?

thanks

EDIT 1 : 
For now i add a crontab like this : 

0 0 * * * cd /var/www/html/YouPHPTube/ && sudo git pull >/dev/null 2>&1

**Comment by ronaldod** [comment]
Not if that is a right way to go as there have been also database upgrades with version updates.

And there are daily fixes on the source whom are not always 100% tested for all installations. If you want to go for a production stable i would not update unless needed. And just update a test installation before bringing it into production.

**Comment by gamersalpha** [comment]
Hello

thanks for u responds, so i m using PROXMOX virtual machine, so before update i take a snapshoot

and if update failed i reload my snapshoot, i will see on the next release hope this works

**Comment by akhilleusuggo** [comment]
there's easier ways to revert updates , with a command line . No need to snapshot anything . 
Anyway if you snapshoot , and revert , all converted videos and new things that you install will be lost .

**Comment by ronaldod** [comment]
Best is to have second installation and test it from there. Never try it out on production. I have second installation that i can bring up in 12 minutes fresh from source using ansible. It is without video data but that is easy fixed.
