### ISSUE TITLE
Ratings translate 

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#2955]
**Describe the question**
please how can i change the description for the suitability of the movie on the side bar
I did the first two but I couldn't make tha other links  translate
give me an example please what i need to do to fix it i want it to appear in greek

**Screenshots**
![ratings](https://user-images.githubusercontent.com/60543030/80303194-f0121e80-87ae-11ea-8ef2-231f5106fa5a.jpg)

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
Hi

I do not think you can do it. it is hardcoded and also related to some filenames. https://github.com/WWBN/AVideo/tree/master/view/rrating
