### ISSUE TITLE
OLD aVideo APP from google store

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#2956]
Hi Daniel,

I am trying to login with the OLD aVideo APP and it hangs on the start saying please wait. Also my other members cannot seem to login as well. Is there an update for this APP? I have noticed there is a second updated aVideo app on GoogleStore but couldn't configure it to work with my site. I really want to have the video stream working an also the recording option to work for my users, but currently the App is not working well for us and using a mobile browser also doesn't work well. How and when can we expect the mobile app to work or how can I resolve those connection bugs.

**Comment by DanielnetoDotCom** [comment]
> I am trying to login with the OLD aVideo APP and it hangs on the start saying please wait. Also my other members cannot seem to login as well. Is there an update for this APP? 

I have updated the APP, please uninstall it and install again

> I have noticed there is a second updated aVideo app on GoogleStore but couldn't configure it to work with my site. I really want to have the video stream working an also the recording option to work for my users, but currently the App is not working well for us 

Please make sure your streamer site is Up to date

> and using a mobile browser also doesn't work well. How and when can we expect the mobile app to work or how can I resolve those connection bugs.

what is not working on the browser on mobile?

**Comment by guymass** [comment]
[26-Apr-2020 16:12:24 UTC] Start Login Request
[26-Apr-2020 16:12:24 UTC] redirectUri:
[26-Apr-2020 16:12:24 UTC] same redirectUri: https://fetube.flatearth.co.il/
[26-Apr-2020 16:12:24 UTC] User or pass empty on login POST: {"redirectUri":"https:\/\/fetube.flatearth.co.il\/"}
[26-Apr-2020 16:12:24 UTC] User or pass empty on login GET: []
[26-Apr-2020 16:12:24 UTC] User or pass empty on login Request: []
[26-Apr-2020 16:12:24 UTC] Start Login Request
[26-Apr-2020 16:12:24 UTC] redirectUri:
[26-Apr-2020 16:12:24 UTC] same redirectUri: https://fetube.flatearth.co.il/
[26-Apr-2020 16:12:24 UTC] user::login: noPass = , encodedPass = 1, this->user, guy 109.186.154.132
[26-Apr-2020 16:12:24 UTC] encryptPasswordVerify: do not encrypt
[26-Apr-2020 16:12:24 UTC] user::login: Do login without cookie
[26-Apr-2020 16:12:25 UTC] user::login: noPass = , encodedPass = , this->user, guy 109.186.154.132
[26-Apr-2020 16:12:25 UTC] encryptPasswordVerify: encrypt
[26-Apr-2020 16:12:25 UTC] user::login: Do login without cookie

**Comment by DanielnetoDotCom** [comment]
Why the logs?

**Comment by guymass** [comment]
maybe they will tell something

**Comment by guymass** [comment]
its like I see my site page but the Please Wait.. message is on top stuck.

**Comment by DanielnetoDotCom** [comment]
I am sending another update today. but please make sure your site is up to date. what version are you running?

**Comment by guymass** [comment]
OK I managed to login after clearing my mobile cache and restarting the app. So sorry the issue was with my phone. However I am going to test now the recording and streaming and that is the real issue for my users, so please leave this ticket open for a short while until I finish testing with couple of users.

**Comment by guymass** [comment]
The media could not be loaded, either because the server or network failed or because the format is not supported.

**Comment by DanielnetoDotCom** [comment]
?

**Comment by guymass** [comment]
I have this in logs.

  thrown in /var/www/html/YouPHPTube/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php on line 164
[26-Apr-2020 16:29:20 UTC] Start Login Request
[26-Apr-2020 16:29:20 UTC] redirectUri: https://fetube.flatearth.co.il/plugin/Live/?c=5df12a039b08f
[26-Apr-2020 16:29:20 UTC] same redirectUri: https://fetube.flatearth.co.il/plugin/Live/?c=5df12a039b08f
[26-Apr-2020 16:29:20 UTC] user::login: noPass = , encodedPass = , this->user, Freethinker 188.64.206.201
[26-Apr-2020 16:29:20 UTC] encryptPasswordVerify: encrypt
[26-Apr-2020 16:29:20 UTC] user::login: Do login with cookie (log in for next 10 years)!
[26-Apr-2020 16:29:21 UTC] PHP Fatal error:  Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:8888": Address already in use in /var/www/html/YouPHPTube/plugin/LiveChat/ratchet/react/socke$
Stack trace:
#0 /var/www/html/YouPHPTube/plugin/LiveChat/ratchet/react/socket/src/Server.php(31): React\Socket\TcpServer->__construct('tcp://0.0.0.0:8...', Object(React\EventLoop\StreamSelectLoop), Array)
#1 /var/www/html/YouPHPTube/plugin/LiveChat/ratchet/cboden/ratchet/src/Ratchet/Server/IoServer.php(59): React\Socket\Server->__construct('0.0.0.0:8888', Object(React\EventLoop\StreamSelectLoop))
#2 /var/www/html/YouPHPTube/plugin/LiveChat/chat-server.php(20): Ratchet\Server\IoServer::factory(Object(Ratchet\Http\HttpServer), '8888')
#3 {main}
  thrown in /var/www/html/YouPHPTube/plugin/LiveChat/ratchet/react/socket/src/TcpServer.php on line 164
[26-Apr-2020 16:29:26 UTC] PHP Fatal error:  Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:8888": Address already in use in /var/www/html/YouPHPTube/plugin/LiveChat/ratchet/react/socke$
Stack trace:

**Comment by guymass** [comment]
cannot stream or record from mobile, none of my mates can't, from android to iphone.

**Comment by guymass** [comment]
should something be running on this port 8888?

**Comment by guymass** [comment]
![streaming-error](https://user-images.githubusercontent.com/58882903/80313890-9df4eb80-87f6-11ea-9a86-d88c7de5b862.jpg)

This is the error we all get on our mobiles trying to start the video stream.

**Comment by guymass** [comment]
Now, I was able to initiate a connection to the server and the video was playing for me but nothing was streamed or recorded.

**Comment by DanielnetoDotCom** [comment]
the port 8888 is for the LiveChat, you can ignore it.

about your live, are you able to live from your desktop?

please screenshot your Live plugin parameters screen

![image](https://user-images.githubusercontent.com/18009293/80313975-bfd57a80-87c4-11ea-9dc2-a476e7e8db2a.png)

make sure you did not select the useAadaptiveMode

**Comment by DanielnetoDotCom** [comment]
Also be aware there is a latency delay, when you start the live stream and when it is available to watch.

**Comment by guymass** [comment]
![Screen Shot 2020-04-26 at 19 53 27](https://user-images.githubusercontent.com/58882903/80314100-055f6b00-87f8-11ea-80ac-1e01158a04f1.jpg)

**Comment by DanielnetoDotCom** [comment]
I cannot see any reason for that does not work.

please make sure it is not the latency.

wait like 30 seconds before you successful watch the movie

**Comment by guymass** [comment]
But even so, there should be a video recorded left after I close my stream and there is none. I also get the encoding error as you seen above, something about the video type. I am using my sumsang s7 mobile nothing special.

**Comment by DanielnetoDotCom** [comment]
the record is something else.

first, is your stream working?

**Comment by guymass** [comment]
Well yes the stream was showing a green blinking square when started and after I pressed the record. I streamed like 5 min and no one seen it on my channel, than I checked for a recording and nothing was recorded. I must add that uploading or getting videos from YT works perfectly.

**Comment by DanielnetoDotCom** [comment]
the record button in your mobile suppose to save in your mobile device (make sure you gave permission for that)

to record on the site you must have the recorder plugin https://github.com/WWBN/AVideo/wiki/Record-Live-Stream

**Comment by guymass** [comment]
![Screen Shot 2020-04-26 at 19 53 27](https://user-images.githubusercontent.com/58882903/80314358-ce8a5480-87f9-11ea-83f3-2f0f01c885fd.jpg)
![Screen Shot 2020-04-26 at 20 06 11](https://user-images.githubusercontent.com/58882903/80314359-cf22eb00-87f9-11ea-9f66-0fd04d5006ea.jpg)

**Comment by guymass** [comment]
![Screen Shot 2020-04-26 at 20 06 18](https://user-images.githubusercontent.com/58882903/80314366-dc3fda00-87f9-11ea-88a1-1a97a9646c38.jpg)
![Screen Shot 2020-04-26 at 20 06 11](https://user-images.githubusercontent.com/58882903/80314368-e1048e00-87f9-11ea-8588-cc4926ce671a.jpg)

**Comment by DanielnetoDotCom** [comment]
If it does not record, please check your streamer log and your encoder log file.

**Comment by guymass** [comment]
Where are those located?

**Comment by DanielnetoDotCom** [comment]
Here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

I just check and Still have access to the server I will check what is going on

**Comment by DanielnetoDotCom** [comment]
your plugin was not properly configured, you did not have the recorder part on the nginx.conf


                        recorder video{
                            record all;
                            record_path /var/www/tmp;
                            record_notify on;
                            record_max_size 2048M; 
                            #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
                            record_suffix -%d-%b-%y-%T.flv;
                        }

I just add it and, of course, I restart it

`sudo /usr/local/nginx/sbin/nginx -s stop && sudo /usr/local/nginx/sbin/nginx`

Also I notice this in your server

![image](https://user-images.githubusercontent.com/18009293/80314733-99660e00-87c9-11ea-8c48-67380004c13c.png)

I guess you changed something in your localhost and your IP 82.165.158.89 does not suppose to redirect to https.

If you want you can hire me for support and I can take a deeper look into those issues.

**Comment by guymass** [comment]
OK thank you very much I just might do that. As this is a site based on donations I will have to speak with the admins to see if they approve. I don't think I changed anything but i will also take a look. I will be on after my kid is asleep.

**Comment by guymass** [comment]
OK I am back. Firstly how much would you charge me for the service?
Also, do I need to configure anything in regards to the recording side on the aVideo app?

One thing is I notice now in my logs every min or so there is a login message about your user.

[26-Apr-2020 18:31:30 UTC] user::login: noPass = , encodedPass = 1, this->user, daniel 177.158.200.46
[26-Apr-2020 18:31:30 UTC] encryptPasswordVerify: do not encrypt
[26-Apr-2020 18:31:30 UTC] user::login: Do login with cookie (log in for next 10 years)!
[26-Apr-2020 18:31:30 UTC] user::recreateLoginFromCookie: do cookie-login: daniel   result: 0
[26-Apr-2020 18:31:30 UTC] success 12

**Comment by DanielnetoDotCom** [comment]
For the price please contact me at developer@youphptube.com

about the logs, do not worry.

about the recording, you are all set, but you need to fix the virtual host problem. I do not think anything will work if you do not fix.

**Comment by CROSSMediaNet** [comment]
Quick Question: does the AVideo app from Google Store streams live and records like OBS?

**Comment by DanielnetoDotCom** [comment]
@CROSSMediaNet you are Correct
