### ISSUE TITLE
Video Thumbnails

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#2957]
While the thumbnails are being created, the text appears on the timeline: 
"Creating images, pleas come back later"
I would like to translate it, but I haven't found anything.

**Comment by DanielnetoDotCom** [comment]
You will not be able to translate it. it is an image file in the encoder https://github.com/WWBN/AVideo-Encoder/blob/master/view/img/creatingImages.jpg

If I am in your shoes, I won't waste my time on that.

**Comment by akhilleusuggo** [comment]
@Donnerstein If you're using rss , you wont even see that img .
Since rss will visit your video , and request the encoder thumb . On that time , the thumb is already created

**Comment by Donnerstein** [comment]
Thanks for the information, I thought it was an image file, but I didn't look for it in the encoder.
