### ISSUE TITLE
Live stream?

### ISSUE THREAD

**Issue by PelleHanses** [WWBN/AVideo#2959]
**Installation for Live streaming**
Hi, I have installed YouPHPTube 8.7 and it is working (excpet for :8080/stats).
I used instructions from https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer and https://github.com/WWBN/AVideo-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x---For-AVideo-Encoder.
Now I want to get the Live streaming to work. **How should I set live streaming up?** I guess I should install nginx and rtmp-module. I have tried nginx as follows and I can send rtmp-stream from OBS Studio but I cannot see it anywhere. After I have installed nginx the site would be unavailable.
```
apt install nginx
apt install libnginx-mod-rtmp
vi /etc/nginx/nginx.conf
```
Added
```
rtmp {
        server {
                listen 1935;
                chunk_size 4096;

                application live {
                        live on;
                        record off;
                }
        }
}
```
And comment out http block
`systemctl restart nginx`
Comment out the port 80 bloc in sites-enabled to.

/PelleH

**Comment by akhilleusuggo** [comment]
Follow up with this guide : https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

**Comment by PelleHanses** [comment]
Thanks. I follwed that one but I still cannot show any live stream. After followed the instruction and installed Nginx the site will also be inaccessible.
I can stream from OSB Studio but nothing shows up in YouPHPTube.

**Comment by akhilleusuggo** [comment]
without logs , errors or screenshots , can't help

**Comment by sipero** [comment]
You need to provide much more information. Here is my working rtmp section and mine also makes a recording of the live stream that get converted to a video when the stream has finished. I am using the SendrecordedtoEncoder plugin to do that. I think you need the hls parts as that is what they are watching not the actual rtmp

    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://domain.com/AVideo/plugin/Live/on_publish.php;
                            on_play http://domain.com/AVideo/plugin/Live/on_play.php;
                            on_record_done http://domain.com/AVideo/plugin/Live/on_record_done.php;
                            recorder video{
                            record all;
                            record_path /var/www/tmp;
                            record_notify on;
                            record_max_size 2048M; 
                            #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
                            record_suffix -%d-%b-%y-%T.flv;
}
                    }
            }
    }

**Comment by PelleHanses** [comment]
Ok here are more info:
I can upload videos.
I can show videos.
I can stream video from OBS Studio installed on another machine.
I can not live stream.
![bild](https://user-images.githubusercontent.com/348286/80530054-bb61bb00-8998-11ea-9f4e-84ce49db2c61.png)
After clicking on "Save Stream" - nothing happens. 
Here are some info from nginx error.log

> 0�,�����'�#��	�(�$��"
2020/04/28 21:42:01 [info] 1912#0: *223 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "���o���wL�ı3o���}v��qA��<7#� �x"��c&�x^�T ȡ@Z�7�"5����o
             ��/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:01 [info] 1912#0: *224 client sent invalid method while reading client request line, client: 127.0.0.1, server: localhost, request: "�t��g��Wy^�_��4��7�g���� ���ұ�ں8�KIG|Dg�9�8����bE��!����/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:01 [info] 1912#0: *224 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "�t��g��Wy^�_��4��7�g���� ���ұ�ں8�KIG|Dg�9�8����bE��!����/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:06 [info] 1912#0: *225 client sent invalid method while reading client request line, client: 127.0.0.1, server: localhost, request: "�jd��m+%��	��sB1���S�J�\�\L��e L���N˃�Q�g~�g��_���m��Q<}���/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:06 [info] 1912#0: *225 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "�jd��m+%��	��sB1���S�J�\�\L��e L���N˃�Q�g~�g��_���m��Q<}���/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:06 [info] 1912#0: *226 client sent invalid method while reading client request line, client: 127.0.0.1, server: localhost, request: "��t
                                                                                                                                                         Lq�=�_"
2020/04/28 21:42:06 [info] 1912#0: *226 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "��t
                                                                                                                                                                            Lq�=�_"
2020/04/28 21:42:14 [info] 1912#0: *227 client sent invalid method while reading client request line, client: 127.0.0.1, server: localhost, request: "����E��!��^��ff��_��CN�m [�Y:aB�G�r�����bs���t'�K��L7�a��/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:14 [info] 1912#0: *227 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "����E��!��^��ff��_��CN�m [�Y:aB�G�r�����bs���t'�K��L7�a��/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:14 [info] 1912#0: *228 client sent invalid method while reading client request line, client: 127.0.0.1, server: localhost, request: "��^� |q��9`�5����w�������ގ A�i�����WX�fR45�TB@BypŞ��/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:14 [info] 1912#0: *228 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "��^� |q��9`�5����w�������ގ A�i�����WX�fR45�TB@BypŞ��/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:16 [info] 1912#0: *229 client sent invalid method while reading client request line, client: 127.0.0.1, server: localhost, request: "�(���tzĘm1�������R�|��P�T� �|���:k��v
                                                                                                                                                                                           "
2020/04/28 21:42:16 [info] 1912#0: *229 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "�(���tzĘm1�������R�|��P�T� �|���:k��v
                                                                                                                                                                                                              "
2020/04/28 21:42:16 [info] 1912#0: *230 client sent invalid method while reading client request line, client: 127.0.0.1, server: localhost, request: "���Ɋ�%���g������#���Ф����� ��}�$��+"
2020/04/28 21:42:16 [info] 1912#0: *230 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "���Ɋ�%���g������#���Ф����� ��}�$��+"
2020/04/28 21:42:16 [info] 1912#0: *231 client sent invalid method while reading client request line, client: 127.0.0.1, server: localhost, request: "��
                                                                                                                                                        �xSѻ��<�	p^1�����&ei�u�5j}�ܹ����� աѧ��-C'���֝��)E�����3���ȕ����/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:26 [info] 1912#0: *234 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "��<�	p^1�����&ei�u�5j}�ܹ����� աѧ��-C'���֝��)E�����3���ȕ����/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:29 [info] 1912#0: *235 client sent invalid method while reading client request line, client: 127.0.0.1, server: localhost, request: "��T*�YU��x	��C,f��};�$�/@T�� ����QTQj?���[���$�'��(���"
2020/04/28 21:42:29 [info] 1912#0: *235 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "��T*�YU��x	��C,f��};�$�/@T�� ����QTQj?���[���$�'��(���"
2020/04/28 21:42:29 [info] 1912#0: *236 client sent invalid method while reading client request line, client: 127.0.0.1, server: localhost, request: "�^N�m�ͼ(������&1��Y��O��d 7��J�]��*gYǀ[��*o?,�KLDY������/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:29 [info] 1912#0: *236 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "�^N�m�ͼ(������&1��Y��O��d 7��J�]��*gYǀ[��*o?,�KLDY������/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:31 [info] 1912#0: *237 client sent invalid method while reading client request line, client: 127.0.0.1, server: localhost, request: "���9��Ǔ!�������[�VoԄ@�>�1 抛Z/�-�mi\8��0���'���݆o8-�Q]�D��/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:31 [info] 1912#0: *237 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "���9��Ǔ!�������[�VoԄ@�>�1 抛Z/�-�mi\8��0���'���݆o8-�Q]�D��/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:31 [info] 1912#0: *238 client sent invalid method while reading client request line, client: 127.0.0.1, server: localhost, request: "���W����v���)�����8M����],6I5p͇$Nk�B��Q�o$0Ͱĥ/Jn��/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:31 [info] 1912#0: *238 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "���W����v���)�����8M����],6I5p͇$Nk�B��Q�o$0Ͱĥ/Jn��/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:36 [info] 1912#0: *239 client sent invalid method while reading client request line, client: 127.0.0.1, server: localhost, request: "�*��0�<o�KD����A�k��y�����(�w�Ze �/��t�����l��������굱bŉ@xy�̎��/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:36 [info] 1912#0: *239 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "�*��0�<o�KD����A�k��y�����(�w�Ze �/��t�����l��������굱bŉ@xy�̎��/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:36 [info] 1912#0: *240 client sent invalid method while reading client request line, client: 127.0.0.1, server: localhost, request: "���/l)eF��2���Ǵ�e��k� �巖`|> �M�5��اG��c/�>�B�.�\C
                                                                                                                                                                                                        ��2�ҹ��/�+�0�,�����'�#��	�(�$��"
2020/04/28 21:42:36 [info] 1912#0: *240 recv() failed (104: Connection reset by peer) while reading client request line, client: 127.0.0.1, server: localhost, request: "���/l)eF��2���Ǵ�e��k� �巖`|> �M�5��اG��c/�>�B�.�\C
        ��2�ҹ��/�+�0�,�����'�#��	�(�$��"

**Comment by DanielnetoDotCom** [comment]
In your nginx.conf check your **on_publish**  parameter

how is your stats page?

look the demo stats https://live.avideo.com:444/stats

**Comment by PelleHanses** [comment]
In the file /usr/local/nginx/conf/nginx.conf
`on_publish http://tube.tillvaxtanalys.se/plugin/Live/on_publish.php;`

https://tube.tillvaxtanalys.se:444/stats results in error message that Connection failed.
I cannot see in any config file thar any service listen on port 444. is it Nginx or Apache that should listen on that?

**Comment by DanielnetoDotCom** [comment]
Please check the ports here https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements#what-ports-do-i-need-to-open

in what URL is your Nginx installed?

**Comment by sipero** [comment]
As far as I can see I do not have port 444 configured for nginx https: Can you please share your nginx.conf to achieve this please?

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/issues/2650#issuecomment-588998936

**Comment by sipero** [comment]
@akhilleusuggo > Thank you
