### ISSUE TITLE
HLS token expires

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2960]
After the latest pull the HLS token does expire every 5mn .
`video.js:84 VIDEOJS: WARN: Problem encountered with the current HLS playlist. HLS request errored at URL:`
Status Code: 520 
![image](https://user-images.githubusercontent.com/52116577/80362425-4fddf780-888b-11ea-90f6-e92c0d677d46.png)

I've updated my hls plugin in case of you've made some changes regarding the hls , but didn't help

**Comment by DanielnetoDotCom** [comment]
Hi, I did not make any changes regarding the tokens and the HLS format.

can you please check if it is not a cache issue?

**Comment by akhilleusuggo** [comment]
I'm taking a look more on the demo site , and I have many missing options .
Is demo site up to date with this github project ? Or he's ahead of it ?
Example : 
![image](https://user-images.githubusercontent.com/52116577/80365213-e6141c80-888f-11ea-97bf-091af280cb1d.png)

![image](https://user-images.githubusercontent.com/52116577/80365415-37bca700-8890-11ea-85a4-747f86f68bb5.png)

![image](https://user-images.githubusercontent.com/52116577/80365491-59b62980-8890-11ea-84df-047e954e4c37.png)

![image](https://user-images.githubusercontent.com/52116577/80365649-9da92e80-8890-11ea-838f-ca3ce141b20f.png)

The disk quota maybe an ordered plugin , but the rest of option are on the plugins , but is missing on mine .

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom btw the problem was fixed . It's cloudflare **_Hotlink Protection_**
Fixed by disabling it .

**Comment by DanielnetoDotCom** [comment]
DiskQuota is not available yet.

the other plugins should be the same for you if you have the latest version for them.

try to redownload from the plugins site.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Most of them can not be downloaded .
CustomizeAdvanced (CustomizeAdvanced) this plugin is native and does not match mine

Live (Live) = this plugin is native and does not match mine

The send recorded stream to encoder , updated ( does now support to send to encoder even if streamer and nginx are not on the same server ? )

**Comment by akhilleusuggo** [comment]
On the code source : 
https://github.com/WWBN/AVideo/blob/master/plugin/Live/Live.php

```
$obj->stats = "{$scheme}://{$server['host']}:{$port}/stat";
        $obj->disableDVR = false;
        $obj->disableGifThumbs = false;
        $obj->useAadaptiveMode = false;
        $obj->experimentalWebcam = false;
        $obj->doNotShowLiveOnVideosList = false;
        $obj->doNotProcessNotifications = false;
        return $obj;
```

There's no use low resolution ( for example )

**Comment by DanielnetoDotCom** [comment]
If the native is different, yours is the correct one and the option was removed . 

Probably what you are seeing was some tests features that still remaining in the demo site

**Comment by akhilleusuggo** [comment]
Well , I was looking for this feature , because on the wiki we can find it but not in plugins !
https://github.com/WWBN/AVideo/wiki/Configure-NGINX-Stream-Resolutions

```
#creates the downsampled or "trans-rated" **mobile video** stream as a 400kbps, 480x360 sized video
                    exec ffmpeg -i rtmp://localhost:1935/$app/$name -acodec copy -c:v libx264 -preset veryfast -profile:v baseline -vsync cfr -vf scale=-2:360,setdar=16:9 -b:v 400k -bufsize 400k -threads 0 -r 30 -f flv rtmp://localhost:1935/low/${name};
```

```
#creates our "mobile" lower-resolution HLS videostream from the ffmpeg-created stream and tells where to put the HLS video manifest and video fragments
                application low {
                    allow play all;
                    live on;
                    hls on;
                    hls_nested on;
                    hls_path /HLS/low;
                    hls_fragment 10s;
                }
```
