### ISSUE TITLE
AD_Server (AD_Server) - Demo site not working

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2961]
I'm trying to see if the problem is from my site , by testing on demo site , but is not working .
The Ad_Server is not working as it should . Video not playing , it plays but you can't see it , and you can't pause the video playing or do anything .

**Comment by DanielnetoDotCom** [comment]
do you have a video setup on the ad_server ?

can you please add some screenshots?

is it a specific video?

**Comment by DanielnetoDotCom** [comment]
I guess I know your problem 

The AD_Server video MUST be MP4 and you choose an HLS

![image](https://user-images.githubusercontent.com/18009293/80366327-7e45dd80-885f-11ea-8b4b-d8362448e9fd.png)

![image](https://user-images.githubusercontent.com/18009293/80366366-8b62cc80-885f-11ea-86f7-def1c266cdd1.png)

**Comment by akhilleusuggo** [comment]
Yes , you can see it on the demo site 
![image](https://user-images.githubusercontent.com/52116577/80366141-6b4c0100-8891-11ea-8376-9636a5e20f3b.png)

![image](https://user-images.githubusercontent.com/52116577/80366200-83238500-8891-11ea-8a43-baaeccd721fa.png)

Playing any video : Nothing happens ( no ad block , nothing )
![image](https://user-images.githubusercontent.com/52116577/80366291-b49c5080-8891-11ea-9872-f9df19dcfb9c.png)

![image](https://user-images.githubusercontent.com/52116577/80366334-cc73d480-8891-11ea-9da1-41d201b11ab7.png)

You should take a look at it .

**Comment by akhilleusuggo** [comment]
holly ... So hls is not supported right ?

**Comment by DanielnetoDotCom** [comment]
Correct, you must use a MP4 video

**Comment by akhilleusuggo** [comment]
that explains the problem . Even webm is not accepted :(
