### ISSUE TITLE
youphptube "go live" function - Melchizadek

### ISSUE THREAD

**Issue by amelchizadek** [WWBN/AVideo#2964]
Per your request I installed the plugins for the pro pack 2 to be able to utilized the "go live" function of myphptube and I don't see the location where I can "go live" via a button or icon on my site to test of "go live" is working or not.  Please advise.

**Comment by DanielnetoDotCom** [comment]
Hi

when you say "Go Live" do you mean this button?

![image](https://user-images.githubusercontent.com/18009293/80488252-6d1ad080-8934-11ea-89c0-176ab9ec8d9f.png)

Please check here how to make a live stream https://tutorials.avideo.com/video/9/youphptube-video-stream-with-obs-and-vmix?channelName=yeshua

**Comment by amelchizadek** [comment]
Hello,

Yes.  I don't not see that button or option anywhere.

**Comment by DanielnetoDotCom** [comment]
Go to the plugin menu and enable this plugin 

![image](https://user-images.githubusercontent.com/18009293/80538902-df170800-897c-11ea-8950-aadb53b222b7.png)

**Comment by amelchizadek** [comment]
Hi yes,, I don't see that button from my cell or the desktop,, I do see it when I am logged in as admin on the desktop.  This option should be available to all of my users correct?  Am I to do the configuration first and then the go-live button will appear for all of my registered users or should the go-live button already be there?  Thanks!

V/r

Tony M.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by amelchizadek** [comment]
The camera does not have a go-live option.  It only has an encode and embed link options

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DanielnetoDotCom** [comment]
@amelchizadek that is correct, the live button is the red button with a circle.

FYI, you cannot go live using your browser cellphone. you MUST use an RTMP publisher like OBS, check this https://tutorials.avideo.com/video/9/youphptube-video-stream-with-obs-and-vmix?channelName=yeshua or the Android mobile app.

**Comment by amelchizadek** [comment]
Okay, I will look into it.  I tried to upload an mp4 video to the site from my cell and it doesn't seem to work.  Do you have a tutorial for that?

V/r

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DanielnetoDotCom** [comment]
first try the features from desktop, then we will have a clue if the error is on the mobile or in the server.

**Comment by amelchizadek** [comment]
Okay thanks

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by amelchizadek** [comment]
Hi I am able to upload videos from my desktop no problem

V/r

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DanielnetoDotCom** [comment]
I am confused. are you talking about video upload or Livestream?

please open a different issue for each problem, that way it will help us to focus on the problem

**Comment by amelchizadek** [comment]
I am talking about livestream and you answered that question that I need to copy and paste the code and for cell phones I need to use an app.  Is that correct?

V/r

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DanielnetoDotCom** [comment]
@amelchizadek please check here https://github.com/WWBN/AVideo/wiki/How-to-make-a-live-stream

**Comment by amelchizadek** [comment]
I have a question. I would like to be able to have links to news websites with a thumbnail and have the views incorporated as well.  Can we add the capability to add this functionality that would allow users see an article link and corresponding thumbnail that will take the user to the site so that he or she can read the article? So essentially the channels with have videos and articles.  Also can we add the functionality to upload photos to a users channel like facebook?

V/r

Tony Melchizadek

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DanielnetoDotCom** [comment]
If you share a link and people click it will go to your website and will count as a view.

if you use embed content, it also will count as a view.

**Comment by amelchizadek** [comment]
I was thinking of it the other way around.  I was thinking of embedding links that will take users to another site for them to read a news story.  For instance I see a news story on the star magazine site and I want others to see it from my site/channel via link.  Can we add the capability to embed a link and a thumb nail photo that will take the user from my site to the star magazine article via the link that I shared from my site.  I wouldn't mind adding this capability.

But please check the attached pic of a problem that I am having.  My preview motion thumbnails are bleeding over one another.  I don't want users of the site to experience this.

Thanks!

Tony M.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by amelchizadek** [comment]
Daniel I am thinking about standing up a new site. I want to do a news blog site with rss feed. They have templates on wordpress and I know of a few rss feed plugins. Can you help with that? If not can you refer me?

Tony M.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DanielnetoDotCom** [comment]
Hi

what do you need from me?

**Comment by amelchizadek** [comment]
I am trying to do a news website with rss feed

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by amelchizadek** [comment]
Check this out. This is what I mean.

wpdrudge.com

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DanielnetoDotCom** [comment]
Sorry, I cannot help you much about Word press

**Comment by amelchizadek** [comment]
Okay thanks,,

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by amelchizadek** [comment]
Daniel,

I need free up datanoop.com for another site. I created another domain name that I would like to use for the youphptube site. I need it switched to pocketnoop.com. Is there anything I need to do on my end? Thanks in advance.

V/r
Tony M.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by amelchizadek** [comment]
Daniel,

I need documentation or instructions on how to back up my site. Can you send this to me?

V/r

Tony M.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-make-a-backup

**Comment by amelchizadek** [comment]
Daniel,

Good morning. I would like to cancel my service. The site is not working out. Please advise.

V/r

Tony Melchizadek

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DanielnetoDotCom** [comment]
If you mean to cancel a dedicated server, please send an email to developer@youphptube.com
