### ISSUE TITLE
TWITTER Login not working

### ISSUE THREAD

**Issue by rielcomms** [WWBN/AVideo#2966]
Logging on with Twitter shows an error

**Screenshots**
![twitter_error](https://user-images.githubusercontent.com/46077574/80450949-ecca8000-88df-11ea-953e-0ce0b470a71a.png)

**Comment by ronaldod** [comment]
That is an error from twitter. Go to your  account in the [ dev webstie twitter](https://developer.twitter.com)  and setup in your app the callback URL. And after aproval it would be correct.
