### ISSUE TITLE
Donations with live chat

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#2967]
Is it possible to integrate donations with live chat similar to what youtube has as superchats.  or something similar to streamlabs donation alerts seen here: https://streamlabs.com/donations?  With this feature locked to the platform owners paypal or stripe account so we can take a fee off the donation similar to what youtube does.

**Comment by DanielnetoDotCom** [comment]
Please check here https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform#donations
