### ISSUE TITLE
Color don't save with color customizing 

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#2968]
Hi,

somehow custom colors don't work. When I customize colors and save, everything seems ok. But when I reload the page, the colors come back to default. Although new script is saved in Cuztomize plugin, I can see that /view/css/custom/default.css isn't updated. I have allowed rewrite on the file, but the file doesn't update.

**Comment by akhilleusuggo** [comment]
clear the cache , maybe it's a cache problem .

**Comment by tonuzo** [comment]
It didn't help..

**Comment by DanielnetoDotCom** [comment]
Sorry, I found the problem, please update your files and try again.

**Comment by tonuzo** [comment]
Still no... Updated, cleared the caches.

**Comment by DanielnetoDotCom** [comment]
Sorry but I triple checked and it is fixed.

look into your page HTML source code and look for this line

`<link href="https://yoursite.com/videos/cache/custom.css?1588080036" rel="stylesheet" type="text/css" id="pluginCustomCss" />`

if you update correctly you will see some tips/clues close to this line

**Comment by tonuzo** [comment]
I didn't find anything special. I think there might be something about I reinstalled Customize-plugin at some point, and I think after that the color save didn't work anymore...

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/80593969-82f1c980-89f8-11ea-8571-892662418ec7.png)

if you can, paste a screenshot here
