### ISSUE TITLE
RTMP stats showing URL then channel to make go offline/online

### ISSUE THREAD

**Issue by ChisdealHDYT** [WWBN/AVideo#2970]
I going put this in context much as i can

i started of follow the docs on wiki how to setup AVdeio with RTMP

then after i got all working and i had few issues with SSL with NGINX-RTMP didn't like it so i deside fix that part.

then after stream working fine and so much more then stream showing offline when it is online.

and now when i check stats and i seen lot people have this issue not just me. and to me no one cant find FIX so most tickets got closed down lack of not finding any details

i going leave screenshot and can you tell me what im doing wrong because been like this since was still YouPHPTube and i updated it and now i getting peoples on discord server saying showing offline not online

if can i send you preview of config to path /live on NGINX

but this what i got from docs copy over and changed url path to my server thats only changes added included have ability do low Quality too thats all it is.

![image](https://user-images.githubusercontent.com/18028479/80596000-8fd4e400-8a1d-11ea-8955-37be6d4bec89.png)

**Comment by ChisdealHDYT** [comment]
Heres config see changes, but i need simple awser fix for this.

`worker_processes  1;
error_log  logs/error.log debug;
events {
        worker_connections  1024;
}
rtmp {
        server {
                listen 1935;
                allow play all;
                #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                application live {
                    allow play all;
                    live on;
                    #record all;
                    #record_path /video_recordings;
                    #record_unique on;
                    hls on;
                    hls_nested on;
                    hls_path /HLS/live;
                    #hls_playlist_length 4s;
                    #hls_fragment 1s;
                    hls_fragment 10s;
                    on_publish http://my-ip/plugin/Live/on_publish.php;
                    on_play http://my-ip/plugin/Live/on_play.php;
                    on_record_done http://my-ip/plugin/Live/on_record_done.php;

                    #creates the downsampled or "trans-rated" mobile video stream as a 400kbps, 480x360 sized video
                    exec ffmpeg -i rtmp://localhost:1935/$app/$name -acodec copy -c:v libx264 -preset veryfast -profile:v baseline -vsync cfr -vf scale=-2:360,setdar=16:9 -b:v 400k -bufsize 400k -threads 0 -r 30 -f flv rtmp://localhost:1935/low/${name};

                    #recorder video{
                    #    record all;
                    #    record_path /tmp;
                    #    record_notify on;
                    #    record_suffix -%d-%b-%y-%T.flv;
                    #}
                }

                #creates our "mobile" lower-resolution HLS videostream from the ffmpeg-created stream and tells where to put the HLS video manifest and video fragments
                application low {
                    allow play all;
                    live on;
                    hls on;
                    hls_nested on;
                    hls_path /HLS/low;
                    hls_fragment 10s;
                }

        }
}
http {
        include       mime.types;
        default_type  application/octet-stream;
        server {
                listen 81;
                server_name localhost;
                #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                location /live {
                        # Disable cache
                        add_header 'Cache-Control' 'no-cache';

                        # CORS setup
                        add_header 'Access-Control-Allow-Origin' '*' always;
                        add_header 'Access-Control-Expose-Headers' 'Content-Length';

                        # allow CORS preflight requests
                        if ($request_method = 'OPTIONS') {
                                add_header 'Access-Control-Allow-Origin' '*';
                                add_header 'Access-Control-Max-Age' 1728000;
                                add_header 'Content-Type' 'text/plain charset=UTF-8';
                                add_header 'Content-Length' 0;
                                return 204;
                        }
                        types {
                                application/vnd.apple.mpegurl m3u8;
                        }
                        alias /HLS/live;
                }

                #creates the http-location for our mobile-device HLS stream - "http://my-ip/low/my-stream-key/index.m3u8"        
                location /low {

                    # Disable cache
                    add_header 'Cache-Control' 'no-cache';

                    # CORS setup
                    add_header 'Access-Control-Allow-Origin' '*' always;
                    add_header 'Access-Control-Expose-Headers' 'Content-Length';

                    # allow CORS preflight requests
                    if ($request_method = 'OPTIONS') {
                            add_header 'Access-Control-Allow-Origin' '*';
                            add_header 'Access-Control-Max-Age' 1728000;
                            add_header 'Content-Type' 'text/plain charset=UTF-8';
                            add_header 'Content-Length' 0;
                            return 204;
                    }
                    types {
                            application/vnd.apple.mpegurl m3u8;
                    }
                    alias /HLS/low;
                }  

                #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                #location /stats {
                #        stub_status;
                #}
                location /stat {
                        rtmp_stat all;
                        rtmp_stat_stylesheet stat.xsl;
                }
                location /stat.xsl {
                        root html;
                }
                location /control {
                        rtmp_control all;
                }
                #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                location / {
                        root   html;
                        index  index.html index.htm;
                }   
        }
}
`

**Comment by ChisdealHDYT** [comment]
i look into it, its trying push `http://[YouPHPTubeURL]/plugin/Live/on_publish.php` to https:// and im using cloudflare and no Automatic https directly so this why it gives me url because trying direct to https but when change it https getting error cant be that.


so this effects all websites has https and nginx directing to that not http://

i dont know exact fix but not cloudflare side, using sub domain on VMHost on apache2 and all set to https because `certbot` so there must way allow https on `on_publish` and `on_play` on NGINX far that what i getting

**Comment by DanielnetoDotCom** [comment]
check this https://github.com/WWBN/AVideo/issues/426

and especially this https://github.com/WWBN/AVideo/issues/1914#issuecomment-516090913

**Comment by ChisdealHDYT** [comment]
i fixed it,

this for note Everyone i found fix.

you need run this configs

For site

![image](https://user-images.githubusercontent.com/18028479/80719334-3f2fba80-8af3-11ea-92e7-9a6dd59b1344.png)

NGINX needs SSL

and not just that if using something like streams.domain.com you need path it on this folder with no SSL

so it can run 127.0.0.1

![image](https://user-images.githubusercontent.com/18028479/80719492-756d3a00-8af3-11ea-8b2c-a372f786b39f.png)


your sub domain can be SSL

this how i found out fix and was pain search up but semes works 127.0.0.1 with no SSL better then sub domain with SSL so now this works venchly

![image](https://user-images.githubusercontent.com/18028479/80719608-a0f02480-8af3-11ea-8cb1-10214e73c6a8.png)

**Comment by akhilleusuggo** [comment]
@ChisdealHDYT 
I don't get it . 
1) Are you running your server at home ? Or hosted for public use ?
2) You said that you're using cloudflare , but cloudflare does not support RTMP . I guess you're having a dedicated streaming server .
3) Have you checked your JavaScript logs ? Because what I'm understanding is that your making a self certified certificate , or you're making a half SSL way ( Flexible SSL ) .

**Comment by ChisdealHDYT** [comment]
> @ChisdealHDYT
> I don't get it .
> 
> 1. Are you running your server at home ? Or hosted for public use ?
> 2. You said that you're using cloudflare , but cloudflare does not support RTMP . I guess you're having a dedicated streaming server .
> 3. Have you checked your JavaScript logs ? Because what I'm understanding is that your making a self certified certificate , or you're making a half SSL way ( Flexible SSL ) .

its hosted Public but what was issue is didnt like SSL because keeps pointing to SSL and thats why URL showing on stats.xml because directing to ssl so i had to change to allow 127.0.0.1 to work

so all things working now jus ti need set 2 sites 1 127.0.0.1 and other 1 main sub domain.
