### ISSUE TITLE
Types of Programs (PlayLists) and how to hide/show videos in them

### ISSUE THREAD

**Issue by franranchito** [WWBN/AVideo#2971]
Scenario:

-Intranet AVideo
-no paid content
-some videos should only be available for certain groups (this is working)
-groups/users should not even see the thumbnail of videos they aren't allowed to watch ("hidePrivateVideos" is on)
-Private videos for users not allowed to see them are correctly hidden outside of PlayLists, but not inside of PlayLists.
-If a PlayList is public, non-allowed users are able to see the name and mini-preview (I need to disable this), although they can't see the full video (which is correct)

I have Programs (PlayLists) plugin working, but I need to know:

I) What is the difference between the three types?:

Globe:
![imagen](https://user-images.githubusercontent.com/19801224/80624253-b27df180-8a4b-11ea-96d1-1a88d922db83.png)
Lock:
![imagen](https://user-images.githubusercontent.com/19801224/80624276-bad62c80-8a4b-11ea-99cc-da3e86a4d4b7.png)
Slashed eye:
![imagen](https://user-images.githubusercontent.com/19801224/80624310-c4f82b00-8a4b-11ea-9bf0-99ac1e896929.png)

I found no practical difference between the Lock and the Slashed eye, both seem to hide the whole playlist to everyone (including other administrators) except the user.

II) I need users to be able to create playlists with fully restricted videos (not even mini-preview) to a certain group. But:

-If the PlayList "Globle" is used, the playlist is shown to ALL users and anonymous users. If they don't belong to the group with permissions, they can't see the full video, but they still can see the name and mini-preview

-If either the PlayList "Lock" or the "Slashed eye" are used, NOBODY can see the Playlist except the owner. Not even other administrators can see it.

Is it possible to get a PlayList with this config?:

-Fully hidden for everyone except the allowed group
-Even the name and mini-preview are hidden for everyone except the allowed group

Thank you

**Comment by akhilleusuggo** [comment]
I) What is the difference between the three types?:
Globe = Public Playlist
Lock = Private Playlist
Slashed eye = Unlisted ( You can't see it , but if you give the LINK , you will find it )
