### ISSUE TITLE
Is there an option to run multiple instances of aVideo and use the same nginx for live streaming

### ISSUE THREAD

**Issue by djslmft** [WWBN/AVideo#2972]
Hello,

We wanna make 3 different sites with your engine using the same server machine.
I tried to install a 2 instance but then i realised that nginx doesn't accept streams from either site (rtmp url and stream key), is there any option without creating multiple virtual machines and installation of apache and nginx to run multiple sites on a same machine?

Thanks for the reply!

**Comment by akhilleusuggo** [comment]
This question should be asked on nginx project . But as the script is written right now , the quick answer is no .

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo is correct.

I can say you can install multiple instances of the streamer and the encoder using virtual hosts. but I do not think you can do it with NGINX RTMP

**Comment by djslmft** [comment]
hi!

so... i got set up multiple instances without virtual host
there are 2 players configured in the nginx.conf

everything works fine except one thing!
stream goes in, rtmp server accepts it, i can see it in the stats
i can get it out via m3u8 with vlc on my desktop
i can view it in the preview window too
BUT it doesn't appear online


so 2 players let's call them live and live2... is it possible that the youphptube listens only for player live?
or is there anything i missed?

**Comment by akhilleusuggo** [comment]
what you saying can't be done , not on the way you want it for one reason .

```
on_publish http://localhost/YouPHPTube/plugin/Live/on_publish.php;
on_play http://localhost/YouPHPTube/plugin/Live/on_play.php;
on_record_done http://localhost/YouPHPTube/plugin/Live/on_record_done.php;
```

This lines are pointing to a single domain name / subdomain .
It doesn't mater how much application you gonna create , they will still point to the same streamer site.

What you're asking is something equivalent to vhost , but for nginx-rtmp .
And I guess will need some reverse proxy to do it . Having 2 nginx.conf , that points to different domain name.
I have no idea how to do it . That's why you should ask on nginx-rtmp project 
https://github.com/arut/nginx-rtmp-module

**Comment by djslmft** [comment]
but it's working :)

looks like it's an SSL problem, that it looks offline

i'll tell you the details later

**Comment by djslmft** [comment]
So I'm back

I'll tell you what I did and maybe we can figure out, how we can make it work

I made a 2. application let's call it live2 and I made a 2. http server on another port (8082, the other one is on the 8081 but I think it's unnecessary).
I set up the other site like this:
![Screenshot 2020-05-04 at 14 44 40](https://user-images.githubusercontent.com/62082745/80966946-d3f92780-8e15-11ea-83cf-1011f38e9011.png)

Everything works fine
I can see the stream in the preview, I can see the stream via the m3u8 link and I can see the stream accessing via the direct link in the LIVE setting menu

BUT it doesn't show up as an online stream, it shows offline and doesn't show up at the bell neither.

Do you have any idea what the problem could be?

Ps. I'm using signed SSL (not self signed)

**Comment by DanielnetoDotCom** [comment]
The online message is related to the stats page.

please check this https://github.com/WWBN/AVideo/issues/2995

**Comment by djslmft** [comment]
i checked these things

the second site-s configuration is the copy of the first
thats why i don't get why it doesn't work

on the stats page looks everything good

could you pls tell me what and how you are monitoring on the stats page?

**Comment by akhilleusuggo** [comment]
your idea is not gonna work without an reverse proxy

**Comment by DanielnetoDotCom** [comment]
@djslmft as I understand you will have 2 livestreams servers. so you will need 2 stats pages

**Comment by djslmft** [comment]
i dont need 2 stat pages...

just needed a coder and it's working now

**Comment by guymass** [comment]
Can you please share your config files so we can see how you got it to work on nginx?
I am struggling with mine and I wish I could only use nginx without apache.

**Comment by djslmft** [comment]
i use it with apache and nginx together never tried without apache, sry
just got multiple instances on the same server... a bit tweaed in some files but it works now

**Comment by guymass** [comment]
So can you share you apache config so at least I can revert and fix mine. for some reason I get all my URLs wrong. and how do I set them to run together? Please I am stuck and my site loads up with nginx but I cannot open any videos beyond the thumbnails which I see just fine.

**Comment by guymass** [comment]
If all my gif thumbnails are loading and showing that why wont the urls be fine as well? 
where does the URL get generated from? do you know?
