### ISSUE TITLE
Chat 2 plugin Cannot modify header information

### ISSUE THREAD

**Issue by djslmft** [WWBN/AVideo#2973]
Hello,

We cannot see the pictures in the Chat2 plugin and i found these lines in the php log

PHP Warning: Cannot modify header information - headers already sent in "DocumentRoot"/events/wp-content/plugins/wise-chat/src/dao/user/WiseChatUserSettingsDAO.php on line 89
PHP Warning:  session_start(): Cannot start session when headers already sent in "DocumentRoot"/events/wp-content/plugins/wise-chat/src/dao/user/WiseChatUserSessionDAO.php on line 95

It doesn't depend on device or browser.

And is there an option to see who logs into the chat?

Thanks forward

**Comment by DanielnetoDotCom** [comment]
Sorry but those logs have nothing to do with our app.

I guess it is a Wordpress chat.

**Comment by akhilleusuggo** [comment]
that's WordPress , I think you mistaking

**Comment by djslmft** [comment]
Sorry, my bad

is there an option to see who logs into the chat?

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by djslmft** [comment]
i didnt ask about finding some issues... ;)

**Comment by akhilleusuggo** [comment]
I see , my bad , to see the chat , you may find it on audit plugin .

**Comment by djslmft** [comment]
i think we are misunderstanding each other
we bought the chat2 plugin, we're using it, and i wanna know if the is a possibility to display aon the chat screen when somebody logs into the chat

**Comment by DanielnetoDotCom** [comment]
@djslmft sorry we do not have this option yet, but I agree it may be a good feature for the chat.
