### ISSUE TITLE
HLS not showing different resolutions.

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#2975]
**Describe the question**
I have the HLS plugin installed and i see only a Quality option when i want to select a resolution.

**Screenshots**
![image](https://user-images.githubusercontent.com/31585599/80698779-3b903980-8adb-11ea-8923-adb39b6b5c2d.png)

What is going wrong ?

**Comment by akhilleusuggo** [comment]
clear cache and refresh

**Comment by ronaldod** [comment]
I tried clear cache button on the admin page but still the same effect. 
Also tried different browser. Same thing.

**Comment by akhilleusuggo** [comment]
Try from another browser .

**Comment by ronaldod** [comment]
On Chrome, Firefox and Edge all the same

**Comment by DanielnetoDotCom** [comment]
check for JS errors and logs.

**Comment by ronaldod** [comment]
![image](https://user-images.githubusercontent.com/31585599/80715377-94210000-8af6-11ea-89f4-62033860f290.png)
Udifined. Checking where that is generated.

**Comment by ronaldod** [comment]
New pull that updated functions.php and it works now.

**Comment by ronaldod** [comment]
Issue has something to with loading plugins for videojs. I expect the problem what plugin gets loaded first. Going to place that in a test.
Plugin that is conflicting is VideoResolutionSwitcher and an other one i made.
Under investigation.

**Comment by ronaldod** [comment]
Found the problem:
In VideoHLS there are labels defined.
Those have to be equal to the labels you use in VideoResolutionSwitcher.

VideoHLS
![image](https://user-images.githubusercontent.com/31585599/80730132-7a3ce880-8b09-11ea-9427-b8255abea368.png)

VideoResolutionSwitcher
![image](https://user-images.githubusercontent.com/31585599/80730237-9b9dd480-8b09-11ea-8c0c-c4f3fc2f642b.png)

**Comment by akhilleusuggo** [comment]
I don't have the option of defaultRes 
If you're using HLS , the output should looks like this : 

![image](https://user-images.githubusercontent.com/52116577/80732830-875fd480-8b15-11ea-9432-a56863616ccf.png)

**Comment by akhilleusuggo** [comment]
I think I know what is the misunderstanding here : 
The plugin , VideoResolutionSwitcher is not needed for HLS video .
The HLS plugin already include the VideoResolutionSwitcher

**Comment by ronaldod** [comment]
> 
> 
> I think I know what is the misunderstanding here :
> The plugin , VideoResolutionSwitcher is not needed for HLS video .
> The HLS plugin already include the VideoResolutionSwitcher

That is correct. Only when you have still old files and move to HLS it is nice if it still would work correctly.
And that new layout will be pushed later this week to the plugun.

**Comment by ronaldod** [comment]
Issues is limited to FF when both plugins are enabled at the same time. HLS and VideoResolutionSwitcher.

**Comment by akhilleusuggo** [comment]
@ronaldod Hello , I think I have found the problem . I'm not sure if it was you who made the pull request , but I'm finding this same issue when VideoLandscapeFullscreen is enabled .
I had to disable it and clear the cache .

**Comment by ronaldod** [comment]
I see a double decleration of the player. That is not allways workiing correctly.

**Comment by DanielnetoDotCom** [comment]
@ronaldod what "double declaration" did you see?

so I can also look it here

**Comment by ronaldod** [comment]
![image](https://user-images.githubusercontent.com/31585599/83789016-67807b00-a696-11ea-8242-6628efcd718f.png)

**Comment by DanielnetoDotCom** [comment]
Hi

The latest version the VideoLandscapeFullscreen does not suppose to load on mobile, and it looks like you are getting it from a desktop. maybe it is some other code?

https://github.com/WWBN/AVideo/blob/6beb63f1f7c324c006e5c7eddab5538e7834dc8a/plugin/VideoLandscapeFullscreen/VideoLandscapeFullscreen.php#L33

**Comment by ronaldod** [comment]
Is from the "VideoResolutionSwitcher" Disabled the plugin and it was gone.

**Comment by DanielnetoDotCom** [comment]
I just sent an update to the streamer and to the VideoResolutionSwitcher plugin.

The plugin will not load anymore if it is an HLS video
