### ISSUE TITLE
the unzip process

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2976]
Can you tell me where is the script lines that execute the unzipping process of HLS after transferring to streamer ?

Here I can see only when received : 

```
$obj = new stdClass();
$obj->file = tempnam(sys_get_temp_dir(), 'YTPChunk_');

$putdata = fopen("php://input", "r");
$fp = fopen($obj->file, "w");

while ($data = fread($putdata, 1024 * 1024))
    fwrite($fp, $data);

fclose($fp);
fclose($putdata);
$obj->filesize = filesize($obj->file);
die(json_encode($obj));
```

But I need the script that runs the unzipping . Could you show me ?

**Comment by DanielnetoDotCom** [comment]
this line https://github.com/WWBN/AVideo/blob/578cae102247eb0e9de78bd841a5e738e4acc5cc/objects/functions.php#L1454

**Comment by akhilleusuggo** [comment]
I think this could be the issue that I'm having .
```
sleep(2);
    ini_set('memory_limit', '-1');
    ini_set('max_execution_time', 7200); // 2 hours
    $cmd = "unzip {$filename} -d {$destination}" . "  2>&1";
    _error_log("unzipDirectory: {$cmd}");
    exec($cmd, $output, $return_val);
```

The sleep and execution time could be causing the issue , getting stuck at /tmp also giving timeout to the db .
Is there more sleep and max_execution time ( not talking about php.ini ) , only on the script .
I want to experiment more with this values .

**Comment by DanielnetoDotCom** [comment]
the sleep is to make sure the file is available. if you remove it you may have permission issues.

**Comment by akhilleusuggo** [comment]
and the execution time ?
When does that timer starts ?

**Comment by DanielnetoDotCom** [comment]
not sure, but before that, I had problems to unzip the files, because the files were not ready

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Now is working better .
I changed the max execution time and sleep to 30 , and no problems anymore ( for now )
I'll keep tracking this .
I'm telling you this , in case in the future someone having the same problem , then you have a clue where the problem could be coming from .

**Comment by ronaldod** [comment]
Why not implement some checks before starting the next line. Sleep is a solution but is fixed, a test would better. 
Do you have any idea what makes it stuck ? Permission, file not complete ?

**Comment by akhilleusuggo** [comment]
I've done many test . I have an powefull home server ( for encoding large videos ) , GPU , iGPU and 16cores/32threads .
From home is not working . It does send to the streaming server , but the unzipping doesn't start .
![image](https://user-images.githubusercontent.com/52116577/80921556-d315b680-8d7f-11ea-96b3-8fb84de7111d.png)

**Comment by ronaldod** [comment]
Only the encoder or also the main video server? If not what is your speed between the 2 hosts?

**Comment by akhilleusuggo** [comment]
streamer site 250mb 
encoder 1gb

When the transfer is stuck on /tmp , the Sendnotify does not execute , and that makes the encoder on state of ''transferring'' endless . And ofc does not delete the zip file from encoder or anything .

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo this Friday I sent some updates to the streamer regarding permissions on the chunked transfer. can you please check if it makes any difference for you on the "endless transfer"??

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Still endless . Does not start unzipping .
So when the file is received , what line does tell the script that the zip file has been received ?

**Comment by DanielnetoDotCom** [comment]
The encoder sends the file information to this file 

https://github.com/WWBN/AVideo/blob/578cae102247eb0e9de78bd841a5e738e4acc5cc/objects/aVideoEncoder.json.php#L137

Then call the function 

https://github.com/WWBN/AVideo/blob/578cae102247eb0e9de78bd841a5e738e4acc5cc/objects/functions.php#L1442
