### ISSUE TITLE
Force login to be email not working 

### ISSUE THREAD

**Issue by sharad22gupta** [WWBN/AVideo#2977]
**Describe the bug**
when i try to login using email i get this error
![Annotation 2020-04-30 190051](https://user-images.githubusercontent.com/15939963/80716417-3c45c180-8b15-11ea-9b8c-c32b50f5fb4f.png)

and when i try to reset password for email i get this
![Annotation 2020-04-30 190129](https://user-images.githubusercontent.com/15939963/80716481-52ec1880-8b15-11ea-8d46-90c40f290694.png)
 works fine with user name but not with email 
@akhilleusuggo  @DanielnetoDotCom

**Comment by akhilleusuggo** [comment]
You can use only 1 way to log .
Login UserName or Email .
Plugins , CustomizeUser

![image](https://user-images.githubusercontent.com/52116577/80730699-92653580-8b12-11ea-9c4a-3077a7e20594.png)

@DanielnetoDotCom Maybe now that you've made email to be unique , you can make login works for email and username . UserName = Example = example@example.com

**Comment by sharad22gupta** [comment]
@akhilleusuggo  so email login is not present in the code yet.

**Comment by akhilleusuggo** [comment]
is present if you enable the ForceLoginToBeTheEmail
But that will desable login with UserName

**Comment by sharad22gupta** [comment]
i have enabled it and its not working its giving the errors i have mentioned above.
i checked avideo.log and this is what i got 
[30-Apr-2020 17:29:56 UTC] user::login: noPass = , encodedPass = , this->user, sharad22gupta@gmail.com 47.9.188.103
[30-Apr-2020 17:29:56 UTC] Password check new hash user not found
and the email id exists. @akhilleusuggo

**Comment by akhilleusuggo** [comment]
Password check new hash user not found
Maybe try to reset your password

**Comment by sharad22gupta** [comment]
when i try to reset password it says you do not have email. @akhilleusuggo

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/Reset-a-Password

**Comment by sharad22gupta** [comment]
Idid it asked me to enter username , idid and then entered the new password. again when i tried to login using email and new password it gave me the same error and forcelogintobemail is on @akhilleusuggo

**Comment by akhilleusuggo** [comment]
can you create a new account ?
When you do , can you log with it with email ? ( the email has to be different )
Btw , is your email unique ? The accounts created , do they have unique emails ?

**Comment by sharad22gupta** [comment]
when you turn on forcelogintobeemail and create account then it saves email as username and then you are not able to change username, like here whatever i save as username will be saved in email.
![Annotation 2020-05-01 152606](https://user-imagithubusercontent.com/15939963/80797753-4d97d800-8bc0-11ea-86da-887f53cdade4.png)
@akhilleusuggo  @DanielnetoDotCom

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/80801212-4cf94480-8bb4-11ea-9e7c-8800a1c0770d.png)

**Comment by DanielnetoDotCom** [comment]
if you check forceLoginToBeTheEmail you have to manually change the existent user's username to an email. otherwise, it will still use the username (Not Email) and password to proceed.

Right now I am deactivating the email verification in the login form. so when you check this option you will still be able to use the old usernames.
