### ISSUE TITLE
Trailer link or url

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#2978]
Hello,
the link for the trailer must be from youtube?
 i try another link and it doesn't show the trailer! 
from youtube it appears normaly i dont have problem,
I ask this because I want the trailers to be on my server if that can be done

Thank you
Ilias

**Comment by ronaldod** [comment]
@wetubeclub Please add some screenshots about what your looking for as i do not know in what context you mean with link and on what page.

**Comment by wetubeclub** [comment]
works normally I have no problem
what i ask is if i can use a trailer that is stored on my own server
from youtube when I place the url the trailer appears
if I put the url from another site the trailer does not appear
Thank you
![trailer](https://user-images.githubusercontent.com/60543030/80746614-77022680-8b22-11ea-822d-c58065da04df.jpg)

**Comment by ronaldod** [comment]
Also links from vimeo should work. Did you saw anything in the log files?

**Comment by DanielnetoDotCom** [comment]
@wetubeclub that is the function that parses the link https://github.com/WWBN/AVideo/blob/f78aed43abc5a616297013f0003e2a7bfd89ee7f/objects/functions.php#L564

we have many site sources there, including another AVideo site.

maybe if your site is not listed there you can directly use the embed code for the video.

**Comment by GodgivenButhelezi** [comment]
> 
> 
> @wetubeclub that is the function that parses the link
> 
> https://github.com/WWBN/AVideo/blob/f78aed43abc5a616297013f0003e2a7bfd89ee7f/objects/functions.php#L564
> 
> we have many site sources there, including another AVideo site.
> 
> maybe if your site is not listed there you can directly use the embed code for the video.

Greetings Sir i have the same problem, but when I tried to switch to YouPHPflix them the trailer showed up, but on the youtube theme it does not appear, what can I do, because i like my Youtube theme not the YouPHPflix ?

**Comment by DanielnetoDotCom** [comment]
Hi @GodgivenButhelezi right now the trailer works only on Netflix.

but just to understand, are you expecting a trailer button? so the user can play trailers? or a trailer background on the main video?

**Comment by GodgivenButhelezi** [comment]
I'm expecting a trailer Button below the movie , so the user can play trailers. The Movie and the trailer must be together.

**Comment by DanielnetoDotCom** [comment]
Check this update, this works to the gallery template.

please make sure you clear your cache
