### ISSUE TITLE
Image in article is not appearing

### ISSUE THREAD

**Issue by sharad22gupta** [WWBN/AVideo#2981]
**Describe the bug**
In big video section image appears but not in the small video section.

![Annotation 2020-05-01 162350](https://user-images.githubusercontent.com/15939963/80801109-06621500-8bc9-11ea-8996-9be5202b314e.png)

@DanielnetoDotCom @akhilleusuggo

**Comment by akhilleusuggo** [comment]
clear the cache 
Also check /videos and look if the img exists

**Comment by sharad22gupta** [comment]
I checked /video image is not there. i tried new article with image same happens. @akhilleusuggo 
what can i do to solve this.

**Comment by sharad22gupta** [comment]
i got it i had enabled useFFMPEGToGenerateThumbs, when i disabled it it was working 
but why this was happening when this option was enabled
