### ISSUE TITLE
Translation of pages

### ISSUE THREAD

**Issue by vomoplay** [WWBN/AVideo#2984]
Which pages do the text translation of menus and submenus

**Comment by ronaldod** [comment]
There are files in /locale/ that have translation tables. Instructions in the [AVideo wiki](https://github.com/WWBN/AVideo/wiki/How-to-translate-AVideo-Platform-to-your-idiom-using-google-translate)

**Comment by DanielnetoDotCom** [comment]
@vomoplay the @ronaldod response is correct, in your case you may want to edit this file ...

https://github.com/WWBN/AVideo/blob/master/locale/br.php

To make easier for you, I just add new translations into the br file, looks the new translations here https://github.com/WWBN/AVideo/commit/0c3d7afb197a55ac804a4a86e8f9c4aa624d2653 I guess it helps you to understand how to add new translations

**Comment by vomoplay** [comment]
After making the changes do you need to send the files or just notify?

**Comment by DanielnetoDotCom** [comment]
DO NOT update your file, follow this to update your code https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform
