### ISSUE TITLE
Fresh install still requires sql table update.

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#2985]
**Describe the bug**
Fresh install still wants an update tot 8.8.

**To Reproduce**
Clean install the site requires update tables.
![image](https://user-images.githubusercontent.com/31585599/80844345-b30eb780-8c06-11ea-9634-60008effdd39.png)

**Expected behavior**
Should be up to date..

**Comment by akhilleusuggo** [comment]
what type of installation are you using ?
Git ? Or zip ?

**Comment by ronaldod** [comment]
I use the https://github.com/WWBN/AVideo.git

**Comment by ronaldod** [comment]
checkconfiguration.php has still `$installationVersion = "8.7";`

**Comment by akhilleusuggo** [comment]
true

**Comment by DanielnetoDotCom** [comment]
Sorry you are right
Update sent
