### ISSUE TITLE
How to update or fix the Chat2 plugin

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#2986]
Quick question: how to update the plugin and how to modify it to fit the design for the platform?

**Comment by DanielnetoDotCom** [comment]
First, download the plugin again, and overwrite the files on your site.

Then check this 

![image](https://user-images.githubusercontent.com/18009293/80863493-3229dd00-8c53-11ea-882e-1f7b1b24d4d6.png)

**Comment by CROSSMediaNet** [comment]
Okay...I did follow the directions that you gave me...still having the same issues...it is not locating with the player at all. It is still at the bottom of the page

**Comment by DanielnetoDotCom** [comment]
Did you also update your streamer to 8.8?

**Comment by CROSSMediaNet** [comment]
No...how to update the streamer to 8.8

**Comment by DanielnetoDotCom** [comment]
here https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by CROSSMediaNet** [comment]
Got and it is working...thanks
