### ISSUE TITLE
speeding up initial page load by using minified video.js

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#2987]
**Is your feature request related to a problem? Please describe.**
At the moment the website is using video.js. This file is not minified.

**Describe the solution you'd like**
Solution is to replace all video.js with video.min.js (is already on the server).

**Describe alternatives you've considered**
Alternatives are compression. But better have it already small then to waste more resources.

**Additional context**
I also expect better load times on mobile devices.

**Comment by DanielnetoDotCom** [comment]
Hi

where did you see it is not minified?

I just made a search into the code and all references are the minified (unless test files)

![image](https://user-images.githubusercontent.com/18009293/80863210-1faea400-8c51-11ea-8fc0-fd9896cb0e2d.png)

**Comment by DanielnetoDotCom** [comment]
My Bad, I just saw it found only CSS files, I will search for the js

**Comment by DanielnetoDotCom** [comment]
Ok, thanks, I will send this update soon, got it.

**Comment by ronaldod** [comment]
Thanks for the fast response.
