### ISSUE TITLE
First Page Load Infinite Scroll

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#2988]
Can you add this feature to the first page ? ( welcome page `/` )
This will reduce a lot of hit load and improve the performance . Like you did on `/trending`

Thanks

**Comment by DanielnetoDotCom** [comment]
we have an infinite scroll for categories. what what do you want to use the infinite scroll for? for all rows?

**Comment by akhilleusuggo** [comment]
I don't see it anywhere
https://demo.avideo.com/

I'm having too many categories and channels that appears on the first page , and this takes a lot of resources to create cache and load page .

**Comment by DanielnetoDotCom** [comment]
what first-page style are you using?

If It is Gallery it should work.

Look into Josh's site, he has a lot categories https://www.joshwhotv.com/

**Comment by akhilleusuggo** [comment]
Oh , only gallery , I see . I'm using the youtube's one .

**Comment by akhilleusuggo** [comment]
I don't like gallery because the main menu is not integrated into the page it self . Goes on top of the main page , hiding content instead of resizing it to fit into it .

**Comment by DanielnetoDotCom** [comment]
I see. I may add it to the youtube layout in the future.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom CSS problems and description . Any tip ?
I never used this gallery , so I have no experience 

![image](https://user-images.githubusercontent.com/52116577/80864186-beef8d80-8c89-11ea-8e69-342101916eca.png)

**Comment by DanielnetoDotCom** [comment]
If you identify what character is breaking it, I can add a code to remove it.

**Comment by akhilleusuggo** [comment]
The option '' description '' is the cause of this error : 

When disabled , no problems , no css errors 
![image](https://user-images.githubusercontent.com/52116577/80864448-6620f480-8c8b-11ea-8b4e-9978f3f3c741.png)

This one breaks it

**Comment by wetubeclub** [comment]
Hello,
the same problem and to me, plugin gallery front page and netflix theme

thank you
![description](https://user-images.githubusercontent.com/60543030/80867260-a1bfbc80-8c93-11ea-89f9-8c112cdb95be.jpg)

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo what about this update related to use the gallery plugin

**Comment by akhilleusuggo** [comment]
Oh , you integrated it to be responsive . Nice !
BTW , I see that you changed things on the Youtube too . What have you added there ?
PS : still got this error when I enable description : 

![image](https://user-images.githubusercontent.com/52116577/80870249-e6585180-8cad-11ea-84be-e1c187e4dc66.png)

**Comment by DanielnetoDotCom** [comment]
About the description error, some character in the description is breaking, we need to detect what is it, so I will auto-remove it in the code.

**Comment by akhilleusuggo** [comment]
ok
