### ISSUE TITLE
I am trying to update users tabel body but coundnt find it in manageUsers_body.php

### ISSUE THREAD

**Issue by sharad22gupta** [WWBN/AVideo#2989]
Can you tell me where is that part coming from?
![Annotation 2020-05-02 194411](https://user-images.githubusercontent.com/15939963/80866629-56b2a300-8cad-11ea-8575-742bba065a32.png)
@akhilleusuggo 
@DanielnetoDotCom

**Comment by akhilleusuggo** [comment]
Are you talking about database?

**Comment by sharad22gupta** [comment]
no in the code in manageUsers_body.php 
i couldnt find the table body tag which is printing all the values.
![Annotation 2020-05-02 234206](https://user-images.githubusercontent.com/15939963/80872304-ad7ca480-8cce-11ea-9b79-aea8fe2fc804.png)
@akhilleusuggo

**Comment by akhilleusuggo** [comment]
What do you wanna do exactly ?

**Comment by sharad22gupta** [comment]
i have added some values in user database i want to see them in admin panel . so i have to add them here @akhilleusuggo

**Comment by ronaldod** [comment]
First you need to load the data from the database. Did not dived deep yet into this part of this script so i am not sure. But i would start with `static function getAllUsers` in the user.php.

**Comment by sharad22gupta** [comment]
table head is there which is forming the headings, i can't find the table body part to add the extra field i have added in users. @ronaldod

**Comment by ronaldod** [comment]
![image](https://user-images.githubusercontent.com/31585599/80881011-9cc33300-8cbc-11ea-876e-cff530236ce6.png)

gives me : 
![image](https://user-images.githubusercontent.com/31585599/80880630-81f0be80-8cbc-11ea-8b8e-a597df4c85eb.png)

Just the data is not there yet as i did not query the database.

**Comment by sharad22gupta** [comment]
so i just have to add that extra column in the table head and data in that column will appear @ronaldod

**Comment by ronaldod** [comment]
This is only the presenting part. You still need to pull the data out of the database. That is al done in user.php the class User is there defined. That needs to be extended and all related functions.
You should contact @DanielnetoDotCom for extended support. As this will be more then a easy change.

**Comment by akhilleusuggo** [comment]
I asked you what do you wanna do , because maybe what you wants is already there on the script .
![image](https://user-images.githubusercontent.com/52116577/80894966-b67a6f80-8ce8-11ea-8175-126472d0a977.png)

**Comment by sharad22gupta** [comment]
i want to display that extra column I have added in the users. @akhilleusuggo
