### ISSUE TITLE
Encoder doesnt import dailymotion videos via Youtube-DL

### ISSUE THREAD

**Issue by TurboAnonym** [WWBN/AVideo#2990]
**Describe the bug**
Puplic encoder doesnt import dailymotion videos via Youtube-DL

**To Reproduce**
1. Go to puplic encoders like https://network.avideo.com/
2. Try any encoder to Import a Video from dailymotion (random example: https://www.dailymotion.com/video/x7tlffx)
3. Click on "Share"

**Error Message**
Sorry!
We could not get the title of your video (https://www.dailymotion.com/video/x7tlffx) go to Update your Youtube-DL to fix it

**Screenshot**
![image](https://user-images.githubusercontent.com/63397666/80868401-92903d00-8c9a-11ea-9184-472f42f89bcf.png)

**Expected behavior**
Dailymotion should be supported by youtube-dl https://ytdl-org.github.io/youtube-dl/supportedsites.html

**Additional context**
It works with Youtube urls and it encounters the same Error when trying to import a Video from a non Video/ non existing site like https://foo.bar/

**Screenshot**
![image](https://user-images.githubusercontent.com/63397666/80868142-e568f500-8c98-11ea-8a15-b86b21517ee1.png)

**I know its not a major bug, but perhaps worth mentioning ;)**
**Thanks for the great programming!**

**Comment by akhilleusuggo** [comment]
try to run it manually on your server 
`youtube-dl -v https://www.dailymotion.com/video/x7tlffx`

**Comment by ronaldod** [comment]
Tested this video on a fresh installation and no problems. Please post the logs from the encoder.

**Comment by TurboAnonym** [comment]
I dont have an own server and therefore couldnt find any logs from the puplic server. I only encountered the bug on a puplic encoder like encoder1.avideo.com.

**Comment by DanielnetoDotCom** [comment]
I confirmed the bug in youtube-dl https://github.com/ytdl-org/youtube-dl/issues/20673.

The solution was to update it to Python3

`sudo apt-get update -y && sudo apt-get install python3-pip -y && sudo pip3 install youtube-dl && sudo pip3 install --upgrade youtube-dl`

now it is working fine.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom that's only if you running ubuntu 20.04

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo I am running Ubuntu 18.04 on encoder1 and the youtube-dl starts to fail with this Dailymotion link. after update it, the link starts to work. I guess is required to update it now.

**Comment by akhilleusuggo** [comment]
Working normal for me with the standard python . Having this issue with Ubuntu 20.04
Looks like you have upgrades some packages that are related with Ubuntu 20.04
But thanks for the information and sharing .
