### ISSUE TITLE
Slow Stream from mobile App and other issues

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#2991]
Hi Daniel,

When my users try to stream live video from the mobile APP on their mobiles whether they are using indoor or outdoor internet connections, the video is unviewable and no sound is recorded. So Main issue here is the slowness of the mobile stream.

Best Regards 
Guy.

**Comment by ronaldod** [comment]
Please split the issues in different topics.

**Comment by DanielnetoDotCom** [comment]
@guymass, @ronaldod is correct please split it, it will make easier for us to help you.

**Comment by guymass** [comment]
OK So lets just concentrate on the speed issue which is most important  and the other issues i will post in a separate topic.

**Comment by DanielnetoDotCom** [comment]
the speed problems only depend on your hardware and bandwidth, there is nothing I can do on software side.

**Comment by guymass** [comment]
Isn't there a way to maybe add more buffering time or give more memory to that stream? 
My server is very strong and bandwidth is no problem, also my connection at home is the highest they come in my city so I don't think this is just an hardware issue. It could be slow encoding or bad configuration as well. Please consider these or maybe there is a way to split this stream service to a separate server if possible.

**Comment by guymass** [comment]
Check this out, just recorded it from home. Now I can hear the sound but video is very bad.

https://fetube.flatearth.co.il/video/2846/empty-title-on-05-may-20-12-21-48

**Comment by DanielnetoDotCom** [comment]
sorry, I cannot see anything I can do for it. definitely there is something. 

If you try OBS on your PC is it fine? (I mean using cables)

try with another mobile hardware.

for example for myself. my 4G connection works better than my WiFi connection for live stream.
