### ISSUE TITLE
Can you stream from the AVideo app?

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#2992]
Quick Question: does the AVideo app from Google Store streams live and records like OBS?

**Comment by DanielnetoDotCom** [comment]
Yes, but only the Android app.

**Comment by CROSSMediaNet** [comment]
Okay...I tried it several times and it is not working somehow...do I need to update something for the mobile setting on the site to work on the app?

**Comment by DanielnetoDotCom** [comment]
First, your site must have Nginx RTMP properly installed. 

you can try to make a stream on the demo site.
