### ISSUE TITLE
when i save info in my account and dont select profile image a white png is saved as profile image

### ISSUE THREAD

**Issue by sharad22gupta** [WWBN/AVideo#2993]
i entered other fields in the form and didn't

 select profile image, so a white png image is saved as profile image
![Annotation 2020-05-03 143906](https://user-images.githubusercontent.com/15939963/80910485-5c5fc580-8d4d-11ea-950e-6dceb3fb2330.png)

i checked database a image is saved and that image is white blank png.
![Annotation 2020-05-03 145147](https://user-images.githubusercontent.com/15939963/80910541-b3659a80-8d4d-11ea-9bfc-7b05336fa076.png) @akhilleusuggo @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
can you please try again and check for JS errors?

**Comment by sharad22gupta** [comment]
when i create account and login tge image is there 
![Annotation 2020-05-04 165955](https://user-images.githubusercontent.com/15939963/80961674-0eb88b00-8e29-11ea-83ba-7749fe9a2573.png)

but when i save info in form and dont select image then a while blank png is saved 
and no js error
![Annotation 2020-05-04 170102](https://user-images.githubusercontent.com/15939963/80961736-30b20d80-8e29-11ea-80f9-d4e79d481d26.png)
@DanielnetoDotCom
