### ISSUE TITLE
Alerts for Mobile Streams not showing on Live stream page.

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#2995]
When a member starts a stream from Mobile phone there is no stream shown on the Live stream page. The stream is only viewable after it is finished and saved in the member channel page. There is no alert for Live streams to subscribed members of the channel who initiated the stream.

Other types of streams such as OBS are shown and working great.

**Comment by RisKatOr** [comment]
and I have such a problem.
![222](https://user-images.githubusercontent.com/4102352/80926922-dcfce100-8da2-11ea-845d-40dfbe2df492.png)

**Comment by DanielnetoDotCom** [comment]
If you have the notification plugin subscribers will receive an email when you start a live

![image](https://user-images.githubusercontent.com/18009293/80927957-a3fb4700-8d77-11ea-9b42-f495b1d9592f.png)


the bell button you must make sure you check the Publicly Listed option on desktop

![image](https://user-images.githubusercontent.com/18009293/80927971-c55c3300-8d77-11ea-8751-2ce9eb26ef29.png)

The offline message may be regarding your Nginx stats file, check this https://github.com/WWBN/AVideo/issues/2970

**Comment by RisKatOr** [comment]
Problem with online/offline and bell button is fixed after I canceled the redirects http to https in /etc/apache2/sites-available/000-default.conf and fixed the path of the ssl certificate in the /usr/local/nginx/conf/nginx.conf. Thank you... 
https://github.com/WWBN/AVideo/issues/1382#issuecomment-468976335
https://github.com/WWBN/AVideo/issues/1914#issuecomment-516090913

**Comment by guymass** [comment]
So these are my SS for the live stream from mobile. While it is streaming there is no alert for it anywhere on the site.

Not sure really what to do.

![Screen Shot 2020-05-05 at 15 19 41](https://user-images.githubusercontent.com/58882903/81065787-cfe80b00-8ee4-11ea-99f4-44855764ce1a.jpg)
![Screen Shot 2020-05-05 at 15 20 01](https://user-images.githubusercontent.com/58882903/81065799-d2e2fb80-8ee4-11ea-94de-2b5d42a329d8.jpg)

**Comment by DanielnetoDotCom** [comment]
@guymass 
are you saying if you do it from PC works?

even if you refresh the page does not work?

try on another page and check for javascript errors.

Just to make sure, can you put Latin characters on the username and titles, to make sure it is not that?
