### ISSUE TITLE
link in the description

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#2996]
As can be seen in the graphic, a display error occurs if too long links are placed in the description.

![image](https://user-images.githubusercontent.com/52116237/80928987-eb4dfb80-8da8-11ea-9a5a-d5bdeff78847.png)

**Comment by DanielnetoDotCom** [comment]
Please try with those changes.

**Comment by Donnerstein** [comment]
That's better. But it's still cut off.
That doesn't look good if you couldn't shorten the link title with points.

`<a href="https://demo.avideo.com/video/270/test-for-links-test-for-links-test-for-links-test-for-links-test-for-links-test-for-links-test-for-links-test-for-links-test-for-links-test-for-links-test-for-links-test-for-links-test-fo" target="_blank">https://demo.avideo.com/video/270/test-for-links-test-for...</a>`

![image](https://user-images.githubusercontent.com/52116237/81013295-345e8800-8e5b-11ea-8cf0-518851cce54b.png)

**Comment by DanielnetoDotCom** [comment]
But you post a long link, what do you expect?

**Comment by Donnerstein** [comment]
I don't think the whole link has to be shown.
![image](https://user-images.githubusercontent.com/52116237/81019358-c7e98600-8e66-11ea-9f68-1e7f516f37b7.png)
