### ISSUE TITLE
Block users, thumbs and comments per video?

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#2997]
It would be great if it were possible to have an option that uploaders could use to block individual users from writing comments and using thumbs.
Where there are many people, there are always people who are not friends.

At the same time, an uploader should be able to switch off the comments and thumbs for a video or all. Maybe that's a lot of work. You could possibly create a plugin for this.

Greetings Donnerstein

**Comment by akhilleusuggo** [comment]
Good idea , reminds me of youtube yep
