### ISSUE TITLE
Forbid sharing videos.

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#2998]
If an upoder prohibits sharing its videos, they can still be shared if you use the embed link to the video.

Greetings Donnerstein

**Comment by DanielnetoDotCom** [comment]
What do you mean, can you please provide more details?

**Comment by akhilleusuggo** [comment]
the forbit sharing videos I think is working only for the plugin ''SecureVideosDirectory Plugin''
Where you will have a token that will expire . You can't block a video from sharing really . But once it's shared , you can manage with tokens .

**Comment by DanielnetoDotCom** [comment]
you also have those options on the SecureVideosDirectory  plugin 

![image](https://user-images.githubusercontent.com/18009293/80985115-28e07200-8e05-11ea-980f-3bb5d255b635.png)

**Comment by Donnerstein** [comment]
I don't mean the video files themselves but the 
../ videoEmbed / ... 
links.

If you change the video ID of another embed link, you can use the embed link.
On other network sites, someone can use a script, for example, that creates the embedding link from the video link of a video, and then prohibiting sharing is useless.

**Comment by DanielnetoDotCom** [comment]
If you use the whitelist I mentioned above only those sites will be able to share your embed links

**Comment by akhilleusuggo** [comment]
@Donnerstein even if you embed the video , the player will not start . ( video will not play )

**Comment by Donnerstein** [comment]
If a video creator creates an Ecxlsives video that must not be embedded. In order to get users to their own site. Now the user can forbid embedding this video, but it can still be embedded because only the display of the embedding link is switched off, but not the embedding.

**Comment by DanielnetoDotCom** [comment]
@Donnerstein how your users are "user can forbid embedding this video"??

what option are you using for that?

**Comment by Donnerstein** [comment]
![image](https://user-images.githubusercontent.com/52116237/81069192-da54d580-8ee1-11ea-92a3-dac17f8091dc.png)

**Comment by DanielnetoDotCom** [comment]
what about this update?

**Comment by Donnerstein** [comment]
Very good yes it works, thank you
