### ISSUE TITLE
problem with the description in the video

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#2999]
Please, how can we fix this problem by activating the description in the plugin gallery that breaks the row
also appeared a bit code to popup description!

Thank you

![row](https://user-images.githubusercontent.com/60543030/80937419-4dbcf100-8dd5-11ea-8417-e3ea4ce73f8b.jpg)
![popup](https://user-images.githubusercontent.com/60543030/80937423-557c9580-8dd5-11ea-8cb4-5a94d9fd32e1.jpg)

**Comment by ronaldod** [comment]
Looks like one of the characters in the description is breaking it. Can you test it by trying out what character it is. And if found post it here so @DanielnetoDotCom can place it in a filter.

**Comment by wetubeclub** [comment]
Thank you for your response,
the same happens in the demo site
but I don't know what to do with code!!

**Comment by DanielnetoDotCom** [comment]
@wetubeclub try those changes, please.

**Comment by wetubeclub** [comment]
Hello,
the problem with the code in the description has been solved!!!!
but the other problem remains with breaking row

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
can you please share here all the description of the video with a broken button?

**Comment by wetubeclub** [comment]
Thank you Daniel but
there are many different videos each time
what to send to help you?
I would prefer you to connect to the site and see the problem in real time
click on page 2 after page 3 after page 4
on page 2 everything is normal
on the page everything is broken
on page 4 can 2 and 3 videos to be broken
I checked the videos that are broken and their descriptions are ok
I cleared the cache etc but I have the same results

Thank you
Ilias

**Comment by wetubeclub** [comment]
![row1](https://user-images.githubusercontent.com/60543030/80992115-547d4f80-8e39-11ea-9d0f-7b526d4067fd.jpg)

**Comment by wetubeclub** [comment]
so you have to be right
I delete her descriptions from the videos that present the problem and I see that there is a significant improvement
not to bother you anymore from your time
close the ticket and if there is something else I open again
thank you very much!!!

**Comment by wetubeclub** [comment]
one last question please,
how can I avoid this problem in the future?
I mean there is a solution for users
the description is usually copy paste, and I will definitely have a problem later

Thank you

**Comment by DanielnetoDotCom** [comment]
Yes, that is why I was asking you to paste here the description, I want to try to find the problem.

I wanna try to reproduce it locally and fix it.

next time please share the description with a problem.

**Comment by wetubeclub** [comment]
i find one i think take a look
this is the text with greek:

Ο Φρανκ Πάρτριτζ κι η γυναίκα του σχεδιάζουν να ξεγελάσουν την ασφαλιστική τους εταιρία για να εισπράξουν τα ασφάλιστα, κρύβοντας τη σύζυγο επί 7ετία για να κηρυχθεί σε αφάνεια. Όμως ένας επιθεωρητής έχει την έμμονη ιδέα ότι ο Φρανκ είναι δολοφόνος. Από τη σειρά Alfred Hitchcock Presents. Παίζουν Sidney Blackmer, Virginia Gregg.

and this is with source code

<!DOCTYPE html>
<html>
<head>
</head>
<body>
<p>&Omicron; &Phi;&rho;&alpha;&nu;&kappa; &Pi;ά&rho;&tau;&rho;&iota;&tau;&zeta; &kappa;&iota; &eta; &gamma;&upsilon;&nu;&alpha;ί&kappa;&alpha; &tau;&omicron;&upsilon; &sigma;&chi;&epsilon;&delta;&iota;ά&zeta;&omicron;&upsilon;&nu; &nu;&alpha; &xi;&epsilon;&gamma;&epsilon;&lambda;ά&sigma;&omicron;&upsilon;&nu; &tau;&eta;&nu; &alpha;&sigma;&phi;&alpha;&lambda;&iota;&sigma;&tau;&iota;&kappa;ή &tau;&omicron;&upsilon;&sigmaf; &epsilon;&tau;&alpha;&iota;&rho;ί&alpha; &gamma;&iota;&alpha; &nu;&alpha; &epsilon;&iota;&sigma;&pi;&rho;ά&xi;&omicron;&upsilon;&nu; &tau;&alpha; &alpha;&sigma;&phi;ά&lambda;&iota;&sigma;&tau;&alpha;, &kappa;&rho;ύ&beta;&omicron;&nu;&tau;&alpha;&sigmaf; &tau;&eta; &sigma;ύ&zeta;&upsilon;&gamma;&omicron; &epsilon;&pi;ί 7&epsilon;&tau;ί&alpha; &gamma;&iota;&alpha; &nu;&alpha; &kappa;&eta;&rho;&upsilon;&chi;&theta;&epsilon;ί &sigma;&epsilon; &alpha;&phi;ά&nu;&epsilon;&iota;&alpha;. Ό&mu;&omega;&sigmaf; έ&nu;&alpha;&sigmaf; &epsilon;&pi;&iota;&theta;&epsilon;&omega;&rho;&eta;&tau;ή&sigmaf; έ&chi;&epsilon;&iota; &tau;&eta;&nu; έ&mu;&mu;&omicron;&nu;&eta; &iota;&delta;έ&alpha; ό&tau;&iota; &omicron; &Phi;&rho;&alpha;&nu;&kappa; &epsilon;ί&nu;&alpha;&iota; &delta;&omicron;&lambda;&omicron;&phi;ό&nu;&omicron;&sigmaf;. &Alpha;&pi;ό &tau;&eta; &sigma;&epsilon;&iota;&rho;ά Alfred Hitchcock Presents. &Pi;&alpha;ί&zeta;&omicron;&upsilon;&nu; Sidney Blackmer, Virginia Gregg.</p>
</body>
</html>

I home this help!

**Comment by wetubeclub** [comment]
`<!DOCTYPE html>
<html>
<head>
</head>
<body>
<p>&Omicron; &Phi;&rho;&alpha;&nu;&kappa; &Pi;ά&rho;&tau;&rho;&iota;&tau;&zeta; &kappa;&iota; &eta; &gamma;&upsilon;&nu;&alpha;ί&kappa;&alpha; &tau;&omicron;&upsilon; &sigma;&chi;&epsilon;&delta;&iota;ά&zeta;&omicron;&upsilon;&nu; &nu;&alpha; &xi;&epsilon;&gamma;&epsilon;&lambda;ά&sigma;&omicron;&upsilon;&nu; &tau;&eta;&nu; &alpha;&sigma;&phi;&alpha;&lambda;&iota;&sigma;&tau;&iota;&kappa;ή &tau;&omicron;&upsilon;&sigmaf; &epsilon;&tau;&alpha;&iota;&rho;ί&alpha; &gamma;&iota;&alpha; &nu;&alpha; &epsilon;&iota;&sigma;&pi;&rho;ά&xi;&omicron;&upsilon;&nu; &tau;&alpha; &alpha;&sigma;&phi;ά&lambda;&iota;&sigma;&tau;&alpha;, &kappa;&rho;ύ&beta;&omicron;&nu;&tau;&alpha;&sigmaf; &tau;&eta; &sigma;ύ&zeta;&upsilon;&gamma;&omicron; &epsilon;&pi;ί 7&epsilon;&tau;ί&alpha; &gamma;&iota;&alpha; &nu;&alpha; &kappa;&eta;&rho;&upsilon;&chi;&theta;&epsilon;ί &sigma;&epsilon; &alpha;&phi;ά&nu;&epsilon;&iota;&alpha;. Ό&mu;&omega;&sigmaf; έ&nu;&alpha;&sigmaf; &epsilon;&pi;&iota;&theta;&epsilon;&omega;&rho;&eta;&tau;ή&sigmaf; έ&chi;&epsilon;&iota; &tau;&eta;&nu; έ&mu;&mu;&omicron;&nu;&eta; &iota;&delta;έ&alpha; ό&tau;&iota; &omicron; &Phi;&rho;&alpha;&nu;&kappa; &epsilon;ί&nu;&alpha;&iota; &delta;&omicron;&lambda;&omicron;&phi;ό&nu;&omicron;&sigmaf;. &Alpha;&pi;ό &tau;&eta; &sigma;&epsilon;&iota;&rho;ά Alfred Hitchcock Presents. &Pi;&alpha;ί&zeta;&omicron;&upsilon;&nu; Sidney Blackmer, Virginia Gregg.</p>
</body>
</html>`

**Comment by wetubeclub** [comment]
another example

`<!DOCTYPE html>
<html>
<head>
</head>
<body>
<p>&Omicron; &pi;&alpha;&tau;ή&rho; &Tau;&sigma;&alpha;&rho;&lambda;&sigmaf; "&Tau;&sigma;&alpha;&kappa;" &Omicron;'&Mu;ά&lambda;&epsilon;ϊ (&Mu;&pi;&iota;&nu;&gamma;&kappa; &Kappa;&rho;ό&sigma;&mu;&pi;&iota;), έ&nu;&alpha;&sigmaf; &alpha;&nu;&tau;&iota;&sigma;&upsilon;&mu;&beta;&alpha;&tau;&iota;&kappa;ό&sigmaf; &iota;&epsilon;&rho;έ&alpha;&sigmaf; &pi;&iota;ά&nu;&epsilon;&iota; &delta;&omicron;&upsilon;&lambda;&epsilon;&iota;ά &sigma;&tau;&omicron; &kappa;&alpha;&theta;&omicron;&lambda;&iota;&kappa;ό &sigma;&chi;&omicron;&lambda;&epsilon;ί&omicron; &tau;&eta;&sigmaf; &Alpha;&gamma;ί&alpha;&sigmaf; &Mu;&alpha;&rho;ί&alpha;&sigmaf; &pi;&omicron;&upsilon; &delta;&iota;&omicron;&iota;&kappa;&epsilon;ί&tau;&alpha;&iota; &alpha;&pi;ό &mu;&omicron;&nu;&alpha;&chi;έ&sigmaf; &kappa;&alpha;&iota; &beta;&rho;ί&sigma;&kappa;&epsilon;&tau;&alpha;&iota; &sigma;&tau;&alpha; ό&rho;&iota;&alpha; &tau;&eta;&sigmaf; &kappa;&alpha;&tau;ά&rho;&rho;&epsilon;&upsilon;&sigma;&eta;&sigmaf;. &Omicron; &Omicron;'&Mu;ά&lambda;&epsilon;ϊ &pi;&iota;&sigma;&tau;&epsilon;ύ&epsilon;&iota; ό&tau;&iota; &tau;&omicron; &sigma;&chi;&omicron;&lambda;&epsilon;ί&omicron; &theta;&alpha; &pi;&rho;έ&pi;&epsilon;&iota; &nu;&alpha; &kappa;&lambda;&epsilon;ί&sigma;&epsilon;&iota; &kappa;&alpha;&iota; &tau;&alpha; &pi;&alpha;&iota;&delta;&iota;ά &nu;&alpha; &sigma;&tau;&alpha;&lambda;&theta;&omicron;ύ&nu; &sigma;&epsilon; ά&lambda;&lambda;&omicron; &epsilon;&kappa;&pi;&alpha;&iota;&delta;&epsilon;&upsilon;&tau;&iota;&kappa;ό ί&delta;&rho;&upsilon;&mu;&alpha; &pi;&omicron;&upsilon; &nu;&alpha; &tau;&omicron;&upsilon;&sigmaf; &pi;&rho;&omicron;&sigma;&phi;έ&rho;&epsilon;&iota; ό&lambda;&alpha; &tau;&alpha; &alpha;&pi;&alpha;&rho;&alpha;ί&tau;&eta;&tau;&alpha; &epsilon;&phi;ό&delta;&iota;&alpha; &gamma;&iota;&alpha; &tau;&eta; &mu;ό&rho;&phi;&omega;&sigma;&eta;.</p>
<p>&Omicron;&iota; &alpha;&delta;&epsilon;&lambda;&phi;έ&sigmaf; ό&mu;&omega;&sigmaf; &epsilon;ί&nu;&alpha;&iota; &alpha;&nu;&tau;ί&theta;&epsilon;&tau;&epsilon;&sigmaf; &sigma;&epsilon; &alpha;&upsilon;&tau;ή &tau;&eta;&nu; ά&pi;&omicron;&psi;&eta; &kappa;&alpha;&iota; &pi;&iota;&sigma;&tau;&epsilon;ύ&omicron;&upsilon;&nu; ό&tau;&iota; &omicron; &theta;&epsilon;ό&sigmaf; &theta;&alpha; &tau;&omicron;&upsilon;&sigmaf; &beta;&omicron;&eta;&theta;ή&sigma;&epsilon;&iota; &nu;&alpha; &tau;&alpha; &kappa;&alpha;&tau;&alpha;&phi;έ&rho;&omicron;&upsilon;&nu;. &Eta; &eta;&gamma;&omicron;&upsilon;&mu;έ&nu;&eta;, &alpha;&delta;&epsilon;&lambda;&phi;ή &Mu;&alpha;ί&rho;&eta; &Mu;&pi;έ&nu;&epsilon;&nu;&tau;&iota;&kappa;&tau; (Ί&nu;&gamma;&kappa;&rho;&iota;&nu;&tau; &Mu;&pi;έ&rho;&gamma;&kappa;&mu;&alpha;&nu;) έ&chi;&epsilon;&iota; &epsilon;&nu;&alpha;&pi;&omicron;&theta;έ&sigma;&epsilon;&iota; &tau;&iota;&sigmaf; &epsilon;&lambda;&pi;ί&delta;&epsilon;&sigmaf; &tau;&eta;&sigmaf; &sigma;&tau;&eta; &beta;&omicron;ή&theta;&epsilon;&iota;&alpha; &tau;&omicron;&upsilon; &Chi;ό&rho;&alpha;&sigmaf; &Pi;&iota; &Mu;&pi;&omicron;&gamma;&kappa;ά&rho;&nu;&tau;&omicron;&upsilon;&sigmaf; (&Chi;έ&nu;&rho;&iota; &Tau;&rho;ά&beta;&epsilon;&rho;&sigmaf;), &epsilon;&nu;ό&sigmaf; &pi;&lambda;&omicron;ύ&sigma;&iota;&omicron;&upsilon; &kappa;&alpha;&iota; &tau;&sigma;&iota;&gamma;&kappa;&omicron;ύ&nu;&eta; &gamma;έ&rho;&omicron;&upsilon; &pi;&omicron;&upsilon; έ&chi;&epsilon;&iota; &sigma;&tau;&eta;&nu; &iota;&delta;&iota;&omicron;&kappa;&tau;&eta;&sigma;ί&alpha; &tau;&omicron;&upsilon; &tau;&omicron; &kappa;&tau;ί&rho;&iota;&omicron; &pi;&omicron;&upsilon; &beta;&rho;ί&sigma;&kappa;&epsilon;&tau;&alpha;&iota; &delta;ί&pi;&lambda;&alpha; &sigma;&tau;&eta; &mu;&omicron;&nu;ή.</p>
<p>&Omicron; &Omicron;'&Mu;ά&lambda;&epsilon;ϊ έ&chi;&epsilon;&iota; &epsilon;&pi;ί&sigma;&eta;&sigmaf; &delta;&iota;&alpha;&phi;&omicron;&rho;&epsilon;&tau;&iota;&kappa;ή &mu;έ&theta;&omicron;&delta;&omicron; &delta;&iota;&delta;&alpha;&sigma;&kappa;&alpha;&lambda;ί&alpha;&sigmaf; &sigma;&epsilon; &sigma;&chi;έ&sigma;&eta; &mu;&epsilon; &tau;&eta;&nu; &alpha;&delta;&epsilon;&lambda;&phi;ή &Mu;&pi;έ&nu;&epsilon;&nu;&tau;&iota;&kappa;&tau; &kappa;&alpha;&iota; &omicron;&iota; &delta;&upsilon;&omicron; &tau;&omicron;&upsilon;&sigmaf; &sigma;&upsilon;&chi;&nu;ά έ&rho;&chi;&omicron;&nu;&tau;&alpha;&iota; &sigma;&epsilon; &sigma;ύ&gamma;&kappa;&rho;&omicron;&upsilon;&sigma;&eta;. &Eta; &sigma;&chi;έ&sigma;&eta; &tau;&omicron;&upsilon;&sigmaf; &pi;&rho;ό&kappa;&epsilon;&iota;&tau;&alpha;&iota; &nu;&alpha; &delta;&omicron;&kappa;&iota;&mu;&alpha;&sigma;&tau;&epsilon;ί ό&tau;&alpha;&nu; &eta; &mu;&omicron;&nu;&alpha;&chi;ή &alpha;&rho;&rho;&omega;&sigma;&tau;&alpha;ί&nu;&epsilon;&iota; &alpha;&pi;ό &phi;&upsilon;&mu;&alpha;&tau;ί&omega;&sigma;&eta;.</p>
</body>
`</html>``

**Comment by wetubeclub** [comment]
how it appears

![rowb](https://user-images.githubusercontent.com/60543030/80997607-d83b3a00-8e41-11ea-89bd-62e48d283189.jpg)

**Comment by DanielnetoDotCom** [comment]
I could not reproduce it here, let me test in your site

**Comment by wetubeclub** [comment]
of course! I send you the link in your email with the video that comes with the problem
most of them have been deleted descriptions!!

**Comment by DanielnetoDotCom** [comment]
Got it, thanks, It is fixed, I already update your site.

**Comment by wetubeclub** [comment]
That's why I can't find the video that had the problem!!!!
I will not have the same problem again on descriptions?
Thank you Daniel
always polite and willing to serve!
Always be well

**Comment by DanielnetoDotCom** [comment]
Yes, this problem may not happen again. but if it happen, please open another issue.
