### ISSUE TITLE
i have added ssl to my website and on https i  am getting mixed content error

### ISSUE THREAD

**Issue by sharad22gupta** [WWBN/AVideo#3000]
**Describe the question**
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure stylesheet '<URL>'. This request has been blocked; the content must be served over HTTPS.

where do i change to correct this. @akhilleusuggo @DanielnetoDotCom

**Comment by akhilleusuggo** [comment]
share a screenshot of what content is not handled over https

**Comment by sharad22gupta** [comment]
![Annotation 2020-05-04 172225](https://user-images.githubusercontent.com/15939963/80963189-13327300-8e2c-11ea-855c-e7cb1ccfeb7c.png)
 if possible please access the portal www.fitnesscannon.fit and https://fitnesscannon.fit youll see the errors @DanielnetoDotCom

**Comment by akhilleusuggo** [comment]
1- ) First , make sure that you have changed the url on `/videos/configuration.php` to  https://fitnesscannon.fit

2 - ) `/etc/apache2/sites-available/`

Add this lines ( you can google for more information ) , replace yoursite.com by your domain name
```
RewriteEngine on
RewriteCond %{SERVER_NAME} =yoursite.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
```

3 - ) If you want that all request goes to https and remove http , delete this lines from your `/videos/configuration.php `

```
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) {
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), FILE);
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
```

**_Read more about this_** https://github.com/WWBN/AVideo/wiki/Redirect-http-to-https
