### ISSUE TITLE
Unable to Save Changes in Admin Panel

### ISSUE THREAD

**Issue by wahabzafar** [WWBN/AVideo#3001]
Hello dear i am facing problem since long i want to put analytic code but unable to save it facing below error.

![image](https://user-images.githubusercontent.com/60570245/80961142-b6cb5580-8e23-11ea-8f67-a974c9059e46.png)

and when I open error below file open.

<br />
<b>Notice</b>:  Undefined index: contactEmail in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>17</b><br />
<br />
<b>Notice</b>:  Undefined index: language in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>18</b><br />
<br />
<b>Notice</b>:  Undefined index: webSiteTitle in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>19</b><br />
<br />
<b>Notice</b>:  Undefined index: authCanComment in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>20</b><br />
<br />
<b>Notice</b>:  Undefined index: authCanUploadVideos in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>21</b><br />
<br />
<b>Notice</b>:  Undefined index: authCanViewChart in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>22</b><br />
<br />
<b>Notice</b>:  Undefined index: disable_analytics in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>24</b><br />
<br />
<b>Notice</b>:  Undefined index: disable_youtubeupload in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>25</b><br />
<br />
<b>Notice</b>:  Undefined index: allow_download in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>26</b><br />
<br />
<b>Notice</b>:  Undefined index: session_timeout in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>27</b><br />
<br />
<b>Notice</b>:  Undefined index: encoder_url in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>28</b><br />
<br />
<b>Notice</b>:  Undefined index: smtp in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>29</b><br />
<br />
<b>Notice</b>:  Undefined index: smtpAuth in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>30</b><br />
<br />
<b>Notice</b>:  Undefined index: smtpSecure in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>31</b><br />
<br />
<b>Notice</b>:  Undefined index: smtpHost in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>32</b><br />
<br />
<b>Notice</b>:  Undefined index: smtpUsername in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>33</b><br />
<br />
<b>Notice</b>:  Undefined index: smtpPassword in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>34</b><br />
<br />
<b>Notice</b>:  Undefined index: smtpPort in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>35</b><br />
<br />
<b>Notice</b>:  Undefined index: head in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>38</b><br />
<br />
<b>Notice</b>:  Undefined index: adsense in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>39</b><br />
<br />
<b>Notice</b>:  Undefined index: autoplay in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>42</b><br />
<br />
<b>Notice</b>:  Undefined index: theme in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>43</b><br />
<br />
<b>Notice</b>:  Undefined variable: response2 in <b>/home/moviqurb/public_html/objects/configurationUpdate.json.php</b> on line <b>112</b><br />
{"status":"1", "respnseLogo": [], "respnseFavicon": null}

and when i go on location see below screenshot please advise settings are in line?

![image](https://user-images.githubusercontent.com/60570245/80961266-090c7680-8e24-11ea-97df-489354a68b90.png)

**Comment by akhilleusuggo** [comment]
this is a permission issue .
Try by giving permission to `videos/userPhoto/` . I don't know how you set up the permission , but to start , try `chmod 777` to `videos/userPhoto/`

**Comment by wahabzafar** [comment]
@DanielnetoDotCom @akhilleusuggo please help.

**Comment by wahabzafar** [comment]
@akhilleusuggo now not facing error 404 but still unable to save anything like language.

![image](https://user-images.githubusercontent.com/60570245/80963988-7ff83e00-8e29-11ea-9d01-caa314e9ce35.png)

**Comment by akhilleusuggo** [comment]
go to your root directory of your site
`chown www-data:www-data -R *`

**Comment by DanielnetoDotCom** [comment]
As long as I saw the "Notice: Undefined index:" please check your javascript console log.
looks like the form does not submit the form fields.
