### ISSUE TITLE
SignUpAgreement plugin makes html code

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3003]
When published SignUpAgreement plugin shows only html code like this: 

![image](https://user-images.githubusercontent.com/63721378/80998076-3bc16980-8e3a-11ea-83ac-695756ac3c5f.png)

A bug maybe?

**Comment by DanielnetoDotCom** [comment]
Hi, can you please download this plugin again and overwrite the one you have?

I just sent an update to it.
