### ISSUE TITLE
Error while registering on index page

### ISSUE THREAD

**Issue by achodankar04** [WWBN/AVideo#3004]
I followed the steps given in https://github.com/YouPHPTube/youphptube-docker. 
I am trying to run the application using docker. I am also running mysql as docker service. After starting the service, i go to the index page and fill in the necessary information. as shown below
<img width="1495" alt="Screen Shot 2020-05-04 at 10 27 19 PM" src="https://user-images.githubusercontent.com/31866310/81030342-805afe00-8e56-11ea-91a2-1069980f5084.png">

When i click submit i get the following error
<img width="1680" alt="Screen Shot 2020-05-04 at 10 21 32 PM" src="https://user-images.githubusercontent.com/31866310/81030397-aed8d900-8e56-11ea-817b-930c7035bf77.png">

Please Help.

Thanks In advance.

**Comment by akhilleusuggo** [comment]
https://github.com/docker-library/wordpress/issues/313

https://github.com/docker-library/wordpress/issues/313#issuecomment-400836783

**Comment by ronaldod** [comment]
Check the default charset on the mysql server. Normally this error points to a charset error between client and server.
In the mysql prompt type `show variables like 'character%';`
This will give you an output and  it should tell you what charsets are in use on the mysql server.

**Comment by achodankar04** [comment]
> Check the default charset on the mysql server. Normally this error points to a charset error between client and server.
> In the mysql prompt type `show variables like 'character%';`
> This will give you an output and it should tell you what charsets are in use on the mysql server.

I was running MySql 8 . I had to downgrade to 5.7.30. Things started working. Thanks For the help everyone.
