### ISSUE TITLE
I can't continue my installtion always redirect to wrong url after confirm installation sucsessfully

### ISSUE THREAD

**Issue by amrkamal2025** [WWBN/AVideo#3005]
**Describe the question**
I put the AVideo on my host iam using Apache2 on Windows server 2016 datacenter after I confirm my installation and it gives me that I did it correctly and it asks me to delete the install directory and I did, after that, I press continue button I go always to this 

`http://myhost.comc/AppServ/www/videos/videos/configuration.php/`

Your Site = http://myhost.com/videos/
Your App path = C:/AppServ/www/videos/

and whenever I go to the http://myhost.com/videos/ after installation i got this

![Capture](https://user-images.githubusercontent.com/21142810/81036820-d05eb280-8ea0-11ea-9c81-dca762b9f185.PNG)

so what i did wrong?

**Comment by akhilleusuggo** [comment]
I think you don't have mod_rewrite enabled 
Also check on your apache config `/etc/apache2/apache2.conf`

```
<Directory /var/www/>
          Options Indexes FollowSymLinks
          AllowOverride All
          Require all granted
  </Directory>
```
Make sure you have AllowOverride **_All_**

**Comment by amrkamal2025** [comment]
the problem still the same I still redirect to this strange URL, is this one support windows? I have apache on windows, so iam not sure if it runs on windows, as when I search and checked the windows installation not supported but it was from 2018 so maybe the new version support it?

**Comment by akhilleusuggo** [comment]
this project does not support windows .
You need to find a fix by yourself
My tip to you is using MAMP and let it hand it for you .
