### ISSUE TITLE
Live

### ISSUE THREAD

**Issue by tiplovo** [WWBN/AVideo#3006]
Появится ли возможность транслировать с веб камеры не используя программы обс

**Comment by ronaldod** [comment]
Please post in English. But google translate helped me.

>Will it be possible to broadcast from a web camera without using obs

From the pc/website there is no option yet to stream directly to a rtmp endpoint. You need an encoder in between.  In the past there where some flash solution but as flash it out of support in  most of the web browsers this is not an option . So you need a program like obs in between or other programs. The Android app supports live streaming. But that is an app not from a web browser.

At the moment AVideo as far i know only supports RTMP. As soon there is WebRTC support then there is an option for for web browser supported live stream. 
Till then i expect no support.

**Comment by tiplovo** [comment]
webrtc is not difficult in my opinion to do,just an additional server will need to be installed, well, we will wait for something to be implemented

**Comment by ronaldod** [comment]
That is correct you need a module installed that is doing the WebRTC handling and implement some ICE protocols. But simple no. That it is not if you want to do it correct and stable. 
Ask @DanielnetoDotCom to place it on the roadmap or speed it up by hire him to program this module.

**Comment by DanielnetoDotCom** [comment]
If I can find a good WebRTC that works as an RTMP publisher, will be a pleasure to implement it.

I look at this in the past, but I still not found a good solution.

**Comment by ronaldod** [comment]
Maybe : [ant media community edition](https://github.com/ant-media/Ant-Media-Server/wiki) ?

**Comment by DanielnetoDotCom** [comment]
That is awesome @ronaldod  but not sure how it will be designed

is it a server that will convert the WebRTC to RTMP?

do they provide a WebRTC HTML5 client?

**Comment by ronaldod** [comment]
It has a basic client and it can [restream](https://github.com/ant-media/Ant-Media-Server/wiki/Publishing-Live-Streams)

**Comment by Criptos** [comment]
I have used the kurento media server, it implements Ice, and both examples one2one and one2many worked outside of the box. 
 
Then I moved to my server, and they didn't work, since is a nated vps and I need a stun server... 
 
That's is where I'm are...

**Comment by Criptos** [comment]
Kurento provides webrtc samble client and some node example codes...
