### ISSUE TITLE
Play Button Image Remains While Video is Playing

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#3007]
After clicking play button, it remains during playback.

<img width="968" alt="Screen Shot 2020-05-05 at 10 53 37 PM" src="https://user-images.githubusercontent.com/739391/81138872-8a9dfa80-8f31-11ea-856d-a13bdbab6fc7.png">

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Error Logs**
Provide the log files at the moment you found the issue.
If you are not sure how to find the log file, please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DanielnetoDotCom** [comment]
For some reason looks like for me you are using the AD_Overlay plugin without an image. 
disable the plugin and test again.

**Comment by willpower68** [comment]
The AD_Overlay plugin was diabled but I followed your direction and it still appears.

**Comment by DanielnetoDotCom** [comment]
Also, disable the VideoLogoOverlay plugin

**Comment by willpower68** [comment]
VideoLogoOverlay plugin being activated was the issue. I was looking for LogoOverlay.  thanks for you help today.
