### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3009]
`DevTools failed to load SourceMap: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

![image](https://user-images.githubusercontent.com/52116577/81176869-76e4a980-8fae-11ea-8fb2-8bfb7c6cca85.png)

Same on demo site

**Comment by ronaldod** [comment]
Ignore these error as this are generated in DevTools and related to you active plugins.
