### ISSUE TITLE
Plugins: Chat2 and User Control 

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#3010]
I notice two plugins that aren't showing up:
1. Chat2
2. User Control
Are the above the same as LiveChat and User_Location? 

If they are not, I don't have those plugins available.

**Comment by DanielnetoDotCom** [comment]
Hi

Those are paid plugins, you can purchase them here https://youphp.tube/plugins/

**Comment by willpower68** [comment]
Yes, I paid for all plug ins.  That is why I was wondering if they were they same.

**Comment by DanielnetoDotCom** [comment]
yes, they are the same, please email me at developer@youphptube.com I will fix this
