### ISSUE TITLE
How to add third-party JS code in VAST Ad Server

### ISSUE THREAD

**Issue by gujarraju** [WWBN/AVideo#3011]
Hi Mr. Daniel

How to add third-party JS code in VAST Ad Server

**Comment by DanielnetoDotCom** [comment]
I do not understand why does it have to be on VAST Ad Server plugin?

if is a global JS file add at the same way you add css files https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css

to add the code in the footer, you can use this 
![image](https://user-images.githubusercontent.com/18009293/81230510-ff237880-8fc7-11ea-865a-3cebccf72d87.png)
