### ISSUE TITLE
Async jobs

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3014]
Could you tell me the script location for generating the asyncjob file's cache ?

**Comment by DanielnetoDotCom** [comment]
This is spread around the code.

currently, I recommend you to disable it. it is generating too much disk IO

**Comment by akhilleusuggo** [comment]
That's not true . I have NVMe and I can assure you that the bottleneck was the CPU .
Something is wrong there for sure .

Also tested on RAMDisk , 11Gb/s , and the same problem . CPU usage really high ( basically all the cores get at 100% )

**Comment by DanielnetoDotCom** [comment]
Did You disable the asyncjobs?

I recommend it for now until we detect the problem

**Comment by akhilleusuggo** [comment]
No , I was talking about Enabling it .
Disabling it and using only the cache plugin , pages works fine and loads in between 0.25s up to 0.8s .

The problem comes into the Dashboard . Does not open the dashboard / admin page , since admin page load dashboard first . Error : ERR_RESPONSE_HEADERS_TOO_BIG

**Comment by DanielnetoDotCom** [comment]
I agree only the cache enable is the best option to speed up.

the Admin dashboard will be rebuilt.
