### ISSUE TITLE
Aparece en muchos videos.

### ISSUE THREAD

**Issue by 7veces7** [WWBN/AVideo#3016]
Hola.
¿Como puedo solucionar este problema?
Aparece este texto en videos y tambien en LIVE.
-----------------------------------
The media could not be loaded, either because the server or network failed or because the format is not supported.
----------------------------------
Gracias.

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/The-media-playback-was-aborted-or-The-media-could-not-be-loaded

**Comment by 7veces7** [comment]
Hi.
It happens with 5 different browsers.
I am attaching screenshots of different things that I have detected if it helps.
--------------------
![ENCODER Captura](https://user-images.githubusercontent.com/62806015/81303856-90542700-907c-11ea-8bcf-958755841264.JPG)
![ENCODER1Captura](https://user-images.githubusercontent.com/62806015/81303861-90ecbd80-907c-11ea-987b-b6f142806fe4.JPG)
![error 443](https://user-images.githubusercontent.com/62806015/81303863-921dea80-907c-11ea-9aca-676c80485981.JPG)
![ERROR GRAVE](https://user-images.githubusercontent.com/62806015/81303868-921dea80-907c-11ea-98be-2061950001e1.JPG)
![fechaerrorpromovervideos](https://user-images.githubusercontent.com/62806015/81303870-92b68100-907c-11ea-8d05-02c7756c75b3.JPG)

**Comment by DanielnetoDotCom** [comment]
You have multiple different issues here.

please open one issue for each problem. it will be a pleasure to help when you do so.

**Comment by 7veces7** [comment]
open the ones that I think are different.
--------------------------
I appreciate it, because what I need is for everything to work well and quickly so that I can start to really work with the web.
As you know a client does not return to a website that does not work well.
