### ISSUE TITLE
Videos in alphabetical order

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3017]
Hey,

is there a way to arrange videos in alphabetical order on categories?

**Comment by tonuzo** [comment]
Also I noticed that this menu doesn't work. It doesn't arrange in alphabetical order (A-Z or Z-A). 
![image](https://user-images.githubusercontent.com/63721378/81286348-98ef3200-9069-11ea-8420-4ddb9cc977c6.png)

**Comment by ronaldod** [comment]
What version of AVideo are you using ? As i can not reproduce this problem on the current version.

**Comment by tonuzo** [comment]
8.8

**Comment by akhilleusuggo** [comment]
just to make it clear . The arrange option works , but only to the top 10/20/30 or what every you have selected 

![image](https://user-images.githubusercontent.com/52116577/81288666-c2aa5800-906d-11ea-8b1e-ee0bc02d1890.png)

**Comment by tonuzo** [comment]
It doesn't work. I noticed that if I choose "Title (Z-A)" it returns the settings back to "TItle (A-Z)". And it shows videos in "Date Added (newest)" order. Though "Date Added (newest)" and "Date Added (oldest)" works as they should.

**Comment by ronaldod** [comment]
What are your setting for the overview/themes ?

**Comment by tonuzo** [comment]
I use netflix style front page.

**Comment by DanielnetoDotCom** [comment]
@tonuzo thanks, bug found and fixed.

**Comment by tonuzo** [comment]
Thank you, the problem is fixed! But now these three stopped working..

![image](https://user-images.githubusercontent.com/63721378/81674644-2fe73000-9456-11ea-8580-26ec0693af0e.png)

**Comment by DanielnetoDotCom** [comment]
Thanks, fixed
