### ISSUE TITLE
Netflix First Page 

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#3019]
The You PHPFlix2 (YouPHPFlix2) is noy working. To check if plugin were causing the issue, I check and verified and the plugins did not appear to be the problem. 
Additionally I also did the following:

1. cleared cash
2. checked on the following browsers: chrome, firefox, and IE
3. mobile devices
4. changed templates and switched back to netflix

I do not have the issue with the other templates only Netflix first page.  However, 'some media could not be loaded...'  occurs throughout with encoded video. 
See below

<img width="1794" alt="Screen Shot 2020-05-07 at 9 53 22 AM" src="https://user-images.githubusercontent.com/739391/81303352-97157680-9049-11ea-94a0-5dd3559bb81b.png">

when I play from homepage video it presents as this:
https://www.youtube.com/watch?v=6ljSbN0Pg28

Also some videos I get the 'some media could not be loaded..."
<img width="1413" alt="Screen Shot 2020-05-07 at 10 05 30 AM" src="https://user-images.githubusercontent.com/739391/81304015-7994dc80-904a-11ea-9d3f-e01f240ea35f.png">

**Comment by willpower68** [comment]
I thought this problem was solved but it's not working.

**Comment by DanielnetoDotCom** [comment]
can you please try to reproduce it on demo site?

what is this video error URL in your site?
