### ISSUE TITLE
Error en fecha promover videos.

### ISSUE THREAD

**Issue by 7veces7** [WWBN/AVideo#3022]
The completion calendar comes out in 1969 and does not allow jumping from year to year. Which requires hundreds of clicks
![fechaerrorpromovervideos](https://user-images.githubusercontent.com/62806015/81309516-51759f80-9083-11ea-898b-de7c83330613.JPG)

**Comment by akhilleusuggo** [comment]
if you click in time , will give you to jump were you want ( just don't fall xD )

![image](https://user-images.githubusercontent.com/52116577/81310033-48d59700-908c-11ea-8a17-7c8056828302.png)

**Comment by 7veces7** [comment]
This error has only occurred once. I tried it again later and it was going well. I don't know ... I would look at it and be on the lookout.

**Comment by 7veces7** [comment]
Sorry. That comment is for Daniel. thank you
