### ISSUE TITLE
Compare statement should be an = statement 

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#3029]
**Describe the bug**
Wrong statement in source.

objects/category.php

line 37
`$this->users_id == User::getId();`

I think you wanted :
`$this->users_id = User::getId();`

**Comment by DanielnetoDotCom** [comment]
You are amazing! you are right, this is wrong?

don't you want to send a pull request?

If you don't let me know, I will fix it.

**Comment by ronaldod** [comment]
It is included in #3027 There also other fixes in there.

**Comment by DanielnetoDotCom** [comment]
Thanks, for some reason I did not see this pull request before, thanks for showing me, it was awesome

**Comment by ronaldod** [comment]
Your welcome.
