### ISSUE TITLE
Clone site

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3030]
Is the clone site still not working for HLS ?
As far as I know the AVideo-Storage plugin does work with HLS , witch makes me wonder why not clone site with HLS .

**Comment by DanielnetoDotCom** [comment]
We cannot just transfer an HLS file, this is composed of hundreds of small files. the backup zips everything and submit, but the clone will not be able to do it.

But I have plans to improve the clone site using rsync command http://manpages.ubuntu.com/manpages/trusty/man1/rsync.1.html

when I do that it will work with HLS, and also will probably be the best backup tool we will have.

**Comment by akhilleusuggo** [comment]
So how the AVideo-Storage plugin works with HLS ? Does it also zip the hls_fragments ? 
I just don't see any difference .

I wanted to backup the site on my home server . If the AVideo-storage where going to work on private IPs (192xx. or 10.xx ) , but that's not possible . The close site does work .

It should be the same processes .

**Comment by ronaldod** [comment]
@akhilleusuggo You want to use the storage at home behind a router and then NAT to a private IP ?
Would be a nice use case to look at. I'm willing to give that a try. You can fix a lot by using a reverse proxy in the middle. For simplicity i use HAproxy 20 lines of config and it works.

**Comment by akhilleusuggo** [comment]
Yes reverse proxy should do the trick . And , and I have rcync as well , just for test purposes .
No idea what is HAproxy . The only reverse proxy I know is nginx . I'll take a look . I don't know how the security will be .

**Comment by DanielnetoDotCom** [comment]
Definitely I have to save some time to review this.

maybe a mix of rsync and rclone will be the best option.

**Comment by DanielnetoDotCom** [comment]
Hi

I guess the clone site plugin is ready to use and it is much faster now. and you can use it with HLS videos IF you use the rsync option

**Comment by akhilleusuggo** [comment]
Let me check , I'll leave a feedback .

**Comment by akhilleusuggo** [comment]
Not working for me . Could you take a look ?
Nothing on the logs 

On the streamer site I can see the logs ( and BTW it does show the password of the database ) , you should hide that .

**Comment by DanielnetoDotCom** [comment]
Hi

should have something in one of the sites.

make sure both are up to date

also, where did you see the database password?

**Comment by akhilleusuggo** [comment]
on the log files /videos/avideo.log
Both sites are up to date ( both with rsync option enabled )

**Comment by DanielnetoDotCom** [comment]
sorry, what is in the log files any error?

also check this log file `/videos/cache/clones/client.log`

**Comment by akhilleusuggo** [comment]
```
/videos/cache/clones# cat client.log
Clone: Clone Start
Clone (1 of 7): Asking the Server the database and the files
Clone: Server Unknow ERROR

```

**Comment by DanielnetoDotCom** [comment]
Hi

you fail at the begining

https://github.com/WWBN/AVideo/blob/aa32c52decc1abc9ef958ba2220b4282396999b8/plugin/CloneSite/cloneClient.json.php#L71

I guess your avideo.log file should tell you something.

this should respond you a json `$objClone->cloneSiteURL . "plugin/CloneSite/cloneServer.json.php?url=" . urlencode($global['webSiteRootURL']) . "&key={$objClone->myKey}&useRsync=" . intval($objClone->useRsync);`

did you put a slash at the end of your cloneSiteURL ?

**Comment by akhilleusuggo** [comment]
Yes did . Should I remove it ?

**Comment by DanielnetoDotCom** [comment]
No, do not remove

can you please check your streamer log file for some clue?

maybe your server does not have the mysqldump command. or maybe PHP cannot execute it.

**Comment by akhilleusuggo** [comment]
Master site : 
`Clone: Dump mysqldump -u user -pPASSWORD@ --host localhost youPHPTube > /var/www/html/YouPHPTube/videos/cache/clones/Clone_mysqlDump_5ec5d9c03992e.sql`

Like I've said before , does expose the user and password on the logs , this need to be removed !

PS : Now it's working , because I've removed the password and user SSH . ( You should have made it clear , that I had not to create a user , that the script will create it's own user and password ). Miss-leading information .

**Comment by akhilleusuggo** [comment]
the plugin did over write the key , also the password and userSSH
I managed the change them with the correct data and works for now 

The -avz I'm not sure it's the best flags , the download speed is slow ( the `z` to compress , not a problem for me , but what do you wanna compress ? mp4 ? hls ? png ? )

**Comment by DanielnetoDotCom** [comment]
Not sure, I just grab it from the Internet.

do you think remove z would be better?

**Comment by DanielnetoDotCom** [comment]
I removed the z and removed the password form the logs

**Comment by akhilleusuggo** [comment]
I've already started the sync , and I can't give a feedback soon , what I can say is that well , it's slow . Copying hls fragment 1 by 1 , so it's going to take a lot of time .

**Comment by DanielnetoDotCom** [comment]
I have a customer that is using it as well, it is transferring about 1tb a day.

the good thing is, it will be incremental, so next time it will only sync the new files.

**Comment by maxlinux2000** [comment]
Hi, for security reasons my server don't uses the default port (22) so rsync fail
```
root@s1:/var/www/html/cathotube.com/AVideo# tail -f videos/cache/clones/client.log
Clone: Clone Start
Clone (1 of 7): Asking the Server the database and the files
Clone: Good start! the server has answered
Clone (2 of 7): Geting MySQL Dump file
Clone: Nice! we got the MySQL Dump file
Clone (3 of 7): Overwriting our database with the server database
Clone: Great! we overwrite it with success.
Clone (4 of 7): execute rsync (sshpass -p '{password}' rsync -av -e 'ssh -o StrictHostKeyChecking=no' --exclude '*.php' --exclude 'cache' --exclude '*.sql' --exclude '*.log' pi@:/var/www/html/cathotube.com/AVideo/videos/ /var/www/html/cathotube.com/AVideo/videos/ --log-file='/var/www/html/cathotube.com/AVideo/videos/cache/clones/client.log' )
2020/09/02 20:46:11 [8747] rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
2020/09/02 20:46:11 [8747] rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
Clone (5 of 7): rsync finished
Clone (6 of 7): Notify Server to Delete Dump
Clone: Dump DELETED
Clone (7 of 7): Resotre the Clone Configuration
Clone: Complete, Database, 0 Videos and 0 Photos
Total Execution Time: 2.6168248812358 Minutes

```
Can You please add the field where set the ssh port (if empty set to 22)?

**Comment by DanielnetoDotCom** [comment]
What happens if you add the port on the cloneSiteSSHIP parameter?

![image](https://user-images.githubusercontent.com/18009293/92236704-4cd3c300-ee8c-11ea-920c-3a56089f8747.png)

**Comment by maxlinux2000** [comment]
it doesn't work. This occurs because the "port"  option must be declared before in the ssh section.

actually
`rsync -av -e 'ssh -o StrictHostKeyChecking=no' --exclude....`
must be
`rsync -av -e 'ssh -p 123456 -o StrictHostKeyChecking=no' --exclude`

here the log

```
tail: /var/www/html/cathotube.com/AVideo/videos/cache/clones/client.log: file truncated
Clone: Clone Start
Clone (1 of 7): Asking the Server the database and the files
Clone: Good start! the server has answered
Clone (2 of 7): Geting MySQL Dump file
Clone: Nice! we got the MySQL Dump file
Clone (3 of 7): Overwriting our database with the server database
Clone: Great! we overwrite it with success.
Clone (4 of 7): execute rsync (sshpass -p '{password}' rsync -av -e 'ssh -o StrictHostKeyChecking=no' --exclude '*.php' --exclude 'cache' --exclude '*.sql' --exclude '*.log' pi@s2.cathotube.com:123456:/var/www/html/cathotube.com/AVideo/videos/ /var/www/html/cathotube.com/AVideo/videos/ --log-file='/var/www/html/cathotube.com/AVideo/videos/cache/clones/client.log' )
2020/09/04 21:51:24 [31913] rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
2020/09/04 21:51:24 [31913] rsync error: unexplained error (code 255) at io.c(235) [Receiver=3.1.3]
Clone (5 of 7): rsync finished
Clone (6 of 7): Notify Server to Delete Dump
Clone: Dump DELETED
Clone (7 of 7): Resotre the Clone Configuration
Clone: Complete, Database, 0 Videos and 0 Photos
Total Execution Time: 2.3556192000707 Minutes
```

**Comment by maxlinux2000** [comment]
I'm trying to use the terminal directly, and...

in order to use a custom port for rsync we can add in ~/.ssh/config
```
Host AVideoServer.org
Port 123456
```
in the terminal (of client)

# sshpass -p 'MySecretPass' rsync -av -e 'ssh -o StrictHostKeyChecking=no' --exclude '*.php' --exclude 'cache' --exclude '*.sql' --exclude '*.log' pi@AVideoServer.org:/var/www/html/AVideo/videos/ /var/www/html/AVideo/videos/ --log-file='/var/www/html/AVideo/videos/cache/clones/client.log'

and it work perfectly

but when I try from AVideo UI pressing "Clone Now" green button there is the error.

I think that there is a permission problems.... when I press the green button i'm using the www-data user than don't have a shell.
...searching a solution

**Comment by DanielnetoDotCom** [comment]
Not tested but it was updated based on this https://stackoverflow.com/questions/4549945/is-it-possible-to-specify-a-different-ssh-port-when-using-rsync

**Comment by maxlinux2000** [comment]
ok, perfect! :+1:
