### ISSUE TITLE
video wont play

### ISSUE THREAD

**Issue by lookseek** [WWBN/AVideo#3032]
If i try to play a video i get "Not Found The requested URL was not found on this server."

mysite.com/video/5/turkey?page=1&channelName=Newuser

But if I remove the number in the path it plays

mysite.com/video/turkey?page=1&channelName=Newuser

  "RewriteEngine on"  is on and working
It seems a RewriteRule is wrong ?

**Comment by ronaldod** [comment]
Is this only with the new video's or with the old video's ?

**Comment by DanielnetoDotCom** [comment]
With this URL mysite.com/video/5/turkey?page=1&channelName=Newuser

Does it load the correct video?

try to check the Javascript console for some clue.

**Comment by lookseek** [comment]
It is a new installation I tried 4 different videos from different devices with the same outcome.
The URL with the number I get "The requested URL was not found on this server."
mysite.com/video/5/turkey?page=1&channelName=Newuser

remove the number in the path it plays
mysite.com/video/turkey?page=1&channelName=Newuser

**Comment by ronaldod** [comment]
And the encoder is that also fresh installed ? I tested it on mine daily build server and i could not reproduce the error.
Can you tell me the build version of the encoder and post/attach the log files from the encoder.
