### ISSUE TITLE
Fix for Rss Feed Title and description

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3035]
When you look a channels rss feed it show in the <title>RSS WEBSITENAME</title>

and it does not pull the description.

<img src="https://static.buddylist.co/x/rss.png" style='width:100%;' border="0" alt="Null">

Need to remove the "RSS" from the title  and add the channels description to the xml file

I am having issues with tuneine because of this. When I sendicate my feed to them it keeps changing my metadata to "**RSS #SeekingTheTruth Podcast**"

<img src="https://static.buddylist.co/x/tunine.png" style='width:100%' border="0" alt="Null">

**Comment by akhilleusuggo** [comment]
You can make your changes here 
https://github.com/WWBN/AVideo/blob/master/feed/index.php

**Comment by JoshWho** [comment]
Where would you grab the description from?

**Comment by akhilleusuggo** [comment]
<description>Rss Feed</description>

**Comment by DanielnetoDotCom** [comment]
This should do the trick

**Comment by JoshWho** [comment]
SHould I update it or is this a fix in the future?

**Comment by JoshWho** [comment]
I did a update and I do see the description now but it still shows RSS in the title. How do I remove that?

**Comment by JoshWho** [comment]
RSS description is showing the website description and not the channel description.

I am trying to achieve the RSS format to be

Channel Name = RSS Title without the letters RSS
RSS Description = Channel About description

So for my channel #SeekingTheTruth https://www.joshwhotv.com/channel/SeekingTheTruth/feed

I want it to show

<rss xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:wfw="http://wellformedweb.org/CommentAPI/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sy="http://purl.org/rss/1.0/modules/syndication/" xmlns:slash="http://purl.org/rss/1.0/modules/slash/" version="2.0">
<channel>
<atom:link href="https://www.joshwhotv.com/channel/SeekingTheTruth/feed" rel="self" type="application/rss+xml"/>
<title>SeekingTheTruth</title>
<description>
Learn What the Gov doesn't want you to know about ... We will headline the news that really deserves it unlike the MSM does. Nothing but the important facts and truth about what is really going on in our world today.
</description>
<link>https://www.joshwhotv.com/channel/SeekingTheTruth</link>
<sy:updatePeriod>hourly</sy:updatePeriod>
<sy:updateFrequency>1</sy:updateFrequency>
<image>
<title>SeekingTheTruth</title>
<url>
https://www.joshwhotv.com/videos/userPhoto/photo2.png?1589266518
</url>
<link>https://www.joshwhotv.com/channel/SeekingTheTruth</link>
<width>144</width>
<height>40</height>
<description>AVideo version rss</description>
</image>
<item>
<title>
Video of Biden Admitting He Was Arrested Following Female College Students into their Dorm
</title>
<description>
<![CDATA[
The newly resurfaced clip shows CNN reporting that Biden told a crowd in Ohio that he was “arrested” for following the group of young women to their dorms. https://www.joshwho.net/video-emerges-of-biden-admitting-he-was-arrested-for-following-female-college-students/ 📰 JoshWho News https://www.joshwho.net 📻Listen to JoshWho Radio https://www.joshwhoradio.net/ ✅Please Help Support the Channel: https://mytipjar.org/SeekingTheTruth 💻 Replace Windows OS for free with JoshWho OS and get your privacy back. https://www.joshwho.net/joshwho-os/ 💻50% Off Coupon for Life Torguard VPN Promo code: truth101 💻Torguard Offshore No Logs VPN Services: https://goo.gl/iBDGTj #SeekingTheTruth My YouTube Channel: https://www.youtube.com/seekingthetruth101 #seekingTheTruth Podcast: http://www.joshwhoradio.net/directory/joshwho-seekingthetruth-podcast/ Find me on JoshWho TV: https://www.joshwhotv.com/channel/SeekingTheTruth Steemit: https://steemit.com/@truthseeker101 Bitchute: https://www.bitchute.com/channel/seekingthetruth/ Buddylist: https://www.buddylist.co/members/837095 Minds: https://www.minds.com/SeekingTheTruth101
]]>
</description>
<link> https://www.joshwhotv.com/v/19751</link>
<enclosure url="http://static.joshwhotv.com/file/joshwhotv/_YPTuniqid_5eb9d651de1846.88743955_Low.mp4" length="10" type="video/mp4"/>
<pubDate>Mon, 11 May 2020 17:48:49 -0500</pubDate>
<guid>https://www.joshwhotv.com/v/19751</guid>
</item>
<item>
ETC.....

**Comment by akhilleusuggo** [comment]
This one is working

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo thanks for the pull request, I guess I missed that.
