### ISSUE TITLE
Logo cut off on Mobile view

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3036]
Still seeing the logo cut off after the latest update.

<img src="https://static.buddylist.co/x/mobile%20view.png" style='width:100%;' border="0" alt="Null">

**Comment by tonuzo** [comment]
This is the place to fix:

../include/navbar.php

![image](https://user-images.githubusercontent.com/63721378/81542161-1ff32180-936c-11ea-8b61-bfccc1e49bd4.png)

**Comment by DanielnetoDotCom** [comment]
please try this

**Comment by tonuzo** [comment]
This works for me: `text-align: left; margin-left: 10px`.

**Comment by tonuzo** [comment]
Just tested, this also works on Customize Advanced -plugin on menuBarHTMLCode:

<style>
  #mainNavBar .navbar-brand {
            width: 100% !important;
            text-align: left;
            margin-left: 10px;
            padding: 15px;
        }
}
</style>
