### ISSUE TITLE
Closed Captioning

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#3037]
Is it possible to add closed captioning for easy transcription of videos. This google cloud page, 
https://cloud.google.com/video-intelligence/docs/transcription
has information.

**Comment by ronaldod** [comment]
Voice transcription is one of the hardest things to do. It could be possible to integrate the google system into it. Just google is not a free system and costs around $0.006 per 15 seconds. Roughly 1,40 per hour of video.
Is that the integration you require ?

**Comment by heiress01** [comment]
Yes, I see, The Google Speech-To-Text API isn't free, however. It is free for speech recognition for audio less than 60 minutes. For audio transcriptions longer than that, it costs $0.006 per 15 seconds.  However, what about integrating with free and open source speech recognition tools?

**Comment by ronaldod** [comment]
> 
> 
> Yes, I see, The Google Speech-To-Text API isn't free, however. It is free for speech recognition for audio less than 60 minutes. 

The first 60 minutes per month. After that you need to pay. As far i know there so no (good) free speech to text.

**Comment by DanielnetoDotCom** [comment]
Yes, I agree with @ronaldod, in the past, I looked for some free speech to text and I did not like any.

**Comment by markginter31** [comment]
There might be a way through webcaptioner --> webcaptioner.com has a "channel" to interface with obs-studio and when obs-studio streams it (apparently) overlays the closed caption when people enable it client side (like in youtube).  I'm not a coder - but is there a way that avideo could accept that could show closed captioning that is generated by webcaptioner and displayed through the live stream?  https://webcaptioner.com --> go to settings and channels and it gives basic setup directions to create a channel to obs-studio.  https://webcaptioner.com/help/integrations/obs --> for an explanation of how it works (sort of).

**Comment by stevespaw** [comment]
https://github.com/ratwithacompiler/OBS-captions-plugin

**Comment by markginter31** [comment]
That's pretty cool.  What I'm asking for is a way for closed captions to appear on a Livestream and one way to do it utilizing available tools is the obs to webcaptooner to live stream pipe - but we would need a cc button that pops up on the video in avideo
