### ISSUE TITLE
Admin Users

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#3038]
Is there a way to create additional or sub-admins for an account, but with limited ability?  Just the ability to work on ads, or the ability to remove or block accounts, etc.  Basically each feature that the admin has can be individually turned on or off for sub-admins.

**Comment by ronaldod** [comment]
At the moment there is only an admin flag in the user setting. That means a User is admin or not. There is no Role Based Access Control (RBAC) option. If your good in coding you can add an extra flag to the tables and edit the some files and certain scripts to also check for that other flag. But as soon you update it will be broken again.
If really need this you can hire @DanielnetoDotCom to integrate this.

**Comment by heiress01** [comment]
Thank you.  I can't code at all.  It is a desired feature, but why not just make the feature as a plugin and sell it to any user that wants it?

**Comment by ronaldod** [comment]
Looks like a nice feature. If you could provide what you would like to see in total.
With RBAC you can define roles like:

- Site Admin
- Video Admin
- User Admin
etc etc.
For security purpose a user should only have one rol assigned to prevent conflicts.

But in the role can be like (User Admin) :
- Cannot assign role (only site admin can change from default user to higher)
+Can edit all users. Except users with admin status.

etc.

If you could write down we could look in to it.

**Comment by heiress01** [comment]
I don't want this to go stale.  

> Looks like a nice feature. If you could provide what you would like to see in total.
> With RBAC you can define roles like:
> 
> * Site Admin
> * Video Admin
> * User Admin
>   etc etc.
>   For security purpose a user should only have one rol assigned to prevent conflicts.
> 
> But in the role can be like (User Admin) :
> 
> * Cannot assign role (only site admin can change from default user to higher)
>   +Can edit all users. Except users with admin status.

All that you said above, where you can toggle all of the admin features on or off for a particular user.  Say If the person is a video admin or part of that team, they can only go into the admin side of the panel and have videos toggled on.  The ads manager can only see all of the ads plugin, but not the other plugins and have that feature only toggled on.  Basically, the site owner can determine the team member that manages a certain part of the site and decide how much access they have.  

There are some features that's not on the admin panel, like top menu, ads, ad overlay, and pay per view that are essential for admin use.

**Comment by DanielnetoDotCom** [comment]
maybe your idea is to be able to assign admin rights for some plugins correct?

this is hard work and may take some time to get it on the road. but can you please list all the plugins you think should have a special admin user?

**Comment by akhilleusuggo** [comment]
Non should have it . In case users has plugin access , we need to create a separated directory and table database for each one .

Idea could be good for : 
- `BulkEmbed (BulkEmbed)` = to each one it's own API key 
- Lite version of audit ? like history usage of users 

And that's it , I don't see much more usage for this feature . All the others not possible to give access , or in case they do , will require clearing the cache every time for every user and will end up making the site laggy .

**Comment by heiress01** [comment]
I agree non should have access to plugins.  Just referring to the features that are listed on admin dashboard.  Of particular interest are users and advertising.
