### ISSUE TITLE
Controlling the videojs controlbar

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#3039]
**Is your feature request related to a problem? Please describe.**
Videojs controlbar layout is not defined. If you make now a plugin for videojs and want to add a button you cannot influence the location on the toolbar correctly. You can add but not define the exact location.
Like the theater view plugin. Works great but the button is on the left. Not on the right next to the fullscreen button.

**Describe the solution you'd like**
I would like to have an option to centralize/registering the plugins. Like you make a plugin and with a command it register itself into an active plugin list (table/sql) with name and exact plugin.js name.

Second a place where i can select what button will be where on the layout and if it is active.

And the layout script should be used at the end of the script for defining VideoJS. Just by not mentioning the item in the controlBar array you disable it.

example of the script:

`var videojs = videojs('video-player', {
    techOrder:  ["youtube", "html5"],
    preload: 'auto',
    controls: video.player.controls,
    autoplay: video.player.autoplay,
    fluid: true,
    controlBar: {
        children: [
            "playToggle",
            "volumeMenuButton",
            "durationDisplay",
            "timeDivider",
            "currentTimeDisplay",
            "progressControl",
            "remainingTimeDisplay",
            "fullscreenToggle"
        ]
    },
    plugins: {
        videoJsResolutionSwitcher: {
            default: 'high',
            dynamicLabel: true
        }
    }`

**Comment by DanielnetoDotCom** [comment]
Do you mean add a custom option to the VideoJS?

**Comment by ronaldod** [comment]
Yes it is an custom option to have influence how the control bar is showing. To automate that correctly all the videoJS plugins should register them self centrally and use that as in put for that statement i posted above here.

**Comment by DanielnetoDotCom** [comment]
I guess it will do the job

In the PlayerSkin plugin, you have a parameter playerCustomDataSetup that will add the String (JSON) into the player options

**Comment by ronaldod** [comment]
That is nice and quick. Will add it to mine to play with list for tomorrow.
