### ISSUE TITLE
Issue with the Bulk Embed plugin

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#3040]
The bulk embed is not working.

1. enabled the YouTube Data API v3
2. Placed API key in plugin form
3. Placed query/youtube playlist url (list was about 20 videos)

<img width="899" alt="Screen Shot 2020-05-09 at 7 33 58 PM" src="https://user-images.githubusercontent.com/739391/81487697-c8e73280-922d-11ea-9454-7c7014ea31c8.png">

Is there something I am missing?

I would appreciate your help.

**Comment by akhilleusuggo** [comment]
you miss configured the API for sure in google console API
What I can tell you for sure is that the plugin is working for sure .

![image](https://user-images.githubusercontent.com/52116577/81488376-8dba2300-9270-11ea-8c90-65e361726f9f.png)

**Comment by willpower68** [comment]
Thank you.  I examined closer and found the mistake that was mad.  I am going add what action I took to correct.  Just in case someone who is had possible problem.

use this when setting up domain with wildcard. 

<img width="503" alt="Screen Shot 2020-05-10 at 1 18 45 PM" src="https://user-images.githubusercontent.com/739391/81505936-ea452e80-92c0-11ea-8b6e-ffb952c601cd.png">
