### ISSUE TITLE
Sound change at evry new song

### ISSUE THREAD

**Issue by gamersalpha** [WWBN/AVideo#3041]
Hello all, 
so i m using avideo to play my playlist video when i work, so what i need is tu put the sound to 5% but when the video change the sound come to high level, how to put the sound to 5% and when the video cahnge keep the sound to the same level thanks

**Comment by ronaldod** [comment]
This should already be normal behavior.

**Comment by DanielnetoDotCom** [comment]
@gamersalpha I guess the sound should keep the volume.

Just a question, is it regarding the autoplay alert?

maybe the unmute command makes the video audio 100%;

**Comment by ronaldod** [comment]
Can you test it with a plain clean browser without any plugins. As this also relies on local storage and then cookies. You can check with F12 and the console option for errors in your browser.
