### ISSUE TITLE
Chromecast plugin isn't working

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3042]
Chromecast plugin doesn't work. 

It connects to Chromecast as it should. 

On TV (=Chormecast) it indicates loading symbol, but after loading Chromecast shows only Chromecast logo and stays there. 

It shouldn't be related to my Chromecast because every other Chromecast application works normally. 

My videos are encoded to HLS.

**Comment by DanielnetoDotCom** [comment]
Try with a MP4 video, I am pretty sure HLS is not supported.
