### ISSUE TITLE
Swap video file

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3044]
Add an option , to allow all or only admin can swap .
Bad use of this feature could end up in misleading content

**Comment by DanielnetoDotCom** [comment]
But, he can only swap his own videos.

**Comment by JoshWho** [comment]
He is saying someone can change something they said in a video and no one would know it was changed because it still has the same likes and numbers. I would say put a history log on it if that was a big issue. THen people can see the video was updated.

**Comment by akhilleusuggo** [comment]
@JoshWho Well you understand me well . And yes the feature of upload crashes / fails is really cool .
But can end up missleading , also for the search results . 
@DanielnetoDotCom Just add an option for that please .

**Comment by DanielnetoDotCom** [comment]
Done, I guess it will give you the disable option 

advanced customize -> makeSwapVideosOnlyForAdmin

**Comment by akhilleusuggo** [comment]
Thank you
