### ISSUE TITLE
Live Steaming Issue  

### ISSUE THREAD

**Issue by ag433** [WWBN/AVideo#3045]
Live steaming saying live and GIF picking up content but no displaying content on main view. port 1935 as well as port 444 are open in firewall for tcp/udp 

![Capture12](https://user-images.githubusercontent.com/55261243/81616305-425b5e00-93b1-11ea-8198-fcbb94490112.JPG)

![Capture](https://user-images.githubusercontent.com/55261243/81615393-83eb0980-93af-11ea-8134-d3c14620a298.JPG)

**Comment by DanielnetoDotCom** [comment]
Looks like your SSL certificate is invalid 

https://adventureglobal.com:444/

try to run `certbot renew` in your server and check the output

**Comment by ganddser** [comment]
Hey Daniel,
I'm having a similar issue OBS connects but the video won't play
![sc1](https://user-images.githubusercontent.com/37193130/81736325-61ff8e80-9464-11ea-9909-2fcd181c97ba.jpg)

**Comment by DanielnetoDotCom** [comment]
@ganddser check your browser console for clues

**Comment by ag433** [comment]
can you please fix this being you set it up

**Comment by ag433** [comment]
also you have not install live sub count all of this was included in the
installation package i bought from you if i am correct.

**Comment by DanielnetoDotCom** [comment]
I just notice something happen with your Nginx installation. I had to reinstall it.

about "live sub" what is it?

**Comment by DanielnetoDotCom** [comment]
Try your live now

if it is missing some plugin, please email me at developer@youphptube.com

**Comment by ag433** [comment]
it works thank you but yes the sub count plugin is not installed.

**Comment by ganddser** [comment]
> 
> 
> @ganddser check your browser console for clues

[liveurestreaming.com-1589404341073.log](https://github.com/WWBN/AVideo/files/4629172/liveurestreaming.com-1589404341073.log)
This is the console error report any ideas?

**Comment by DanielnetoDotCom** [comment]
@ag433 please email me at developer@youphptube.com

@ganddser chek here https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

**Comment by ganddser** [comment]
> 
> 
> @ag433 please email me at [developer@youphptube.com](mailto:developer@youphptube.com)
> 
> @ganddser check here https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

I already got the console error report I'm asking how to fix the problem

**Comment by DanielnetoDotCom** [comment]
I just went to your site and I could see a live

![image](https://user-images.githubusercontent.com/18009293/82118243-3cb49e00-974c-11ea-87e8-7c99116f9508.png)


Is it fixed?

**Comment by ag433** [comment]
yes it is but how do i display this live stream on the home page?

**Comment by akhilleusuggo** [comment]
by default does show on home page . Clear the cache of the homepage .

**Comment by ag433** [comment]
no what i mean is i am trying to get a live stream to pop up not in most
popular or most watched. Not as a notification
[image: sceenshot1.JPG]

**Comment by akhilleusuggo** [comment]
Same answer Clear the cache of the homepage .

**Comment by ag433** [comment]
already cleared the cache live stream does not show up

**Comment by akhilleusuggo** [comment]
can you provide more details ?

**Comment by ag433** [comment]
Yes so i am trying to display live streams on the home page where import
Morosso palm beach video is or where the trending / featured section is.
But the issue is that nothing is showing up on the home page except the
notification tab saying i am streaming.
[image: Capture352wer.JPG]
[image: Capture.JPG]

[image: Capture4523.JPG]

**Comment by DanielnetoDotCom** [comment]
@ag433 what layout are you using?

FYI I recommend you to use the gallery. the Netflix layout does not show live thumbs on the home page.

**Comment by ag433** [comment]
do i need to embed it to display it on the home page

**Comment by DanielnetoDotCom** [comment]
The Netflix layout is more for VOD videos. 

it does have the bell alert on the menu. but it does not dynamically add live videos in its row

**Comment by ag433** [comment]
I have since switched to the youtube/gallery version but i love the look of
the Netflix version could i hire you to edit the Netflix theme and create a
version that can dynamically add live videos in its row? Also make the live
chat box look something like mixers
[image: Capture342.JPG]
[image: Capture352wer.JPG]

**Comment by ag433** [comment]
Also can you send me a folder with all the plugins i bought? i cant find
them anywhere and some of them are not installed

**Comment by DanielnetoDotCom** [comment]
Sure for the purchased plugins and to hire me/quote please email me at developer@youphptube.com
