### ISSUE TITLE
live stream not stop 

### ISSUE THREAD

**Issue by landydawood** [WWBN/AVideo#3046]
Hi , 

Im testing live stream , i found 2 issues 
1. if i stop the stream from ODB or Vmix or any other broadcast software , stream keep online about 10mins after that i can start again to stream if i want 

2. i found that the stream not going more then 14 days is cutting it self ,

**Comment by akhilleusuggo** [comment]
1- I'm not having this problem with OBS .
2- Maybe a connection lost or server got low resources .
Are you sure it's 14 days and not 20 days ?

**Comment by landydawood** [comment]
1- I'm not having this problem with OBS .
no what im saying is if i put stop stream will be stop but in the website it will keep showing is online 
2- Maybe a connection lost or server got low resources .
Are you sure it's 14 days and not 20 days ?
as i told more then 14 days im not sure exactly number but is after every two weeks 

can you please share with me the solution if you have it 

thanks

**Comment by DanielnetoDotCom** [comment]
@landydawood please share your nginx.conf

**Comment by landydawood** [comment]
@DanielnetoDotCom 

worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and te$
                    application live {
                            allow play all;
                            live on;

                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://*********/YouPHPTube/plugin/Live/on_publish.php;
                            on_play http://*********/YouPHPTube/plugin/Live/on_play.php;
                            on_record_done http://*********/YouPHPTube/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/liv$
                    location /live {
                            # Disable cache
add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
}
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/st$
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"
                    location / {
                            root   html;

index  index.html index.htm;
                    }
            }
    }

**Comment by akhilleusuggo** [comment]
If keeps showing that the live is online , is because of the cache . 
If when you stop , you clear the cache , will immediately show offline . 

That something that daniel need to implement . Do not cache live pages and status

**Comment by landydawood** [comment]
@akhilleusuggo 

can you tell me how i can make auto clear cache ?? or never keep ccache ??  or add stop button to the stream panel

**Comment by akhilleusuggo** [comment]
Not sure if that exists . Try by disabling the cache plugin .
My experience , even when disabling the cache plugin , the cache is still creating .

**Comment by landydawood** [comment]
@akhilleusuggo  but i dont have any cache plugin active ,

**Comment by DanielnetoDotCom** [comment]
@landydawood please check your stats page when you finish the live

also, check the directory /HLS/live, I guess the files already there. so if your user is watching the live he will still be watching it 

Check this https://stackoverflow.com/questions/53638341/auto-delete-ts-and-m3u8-files-once-client-receives-all-ts-files

> you can use hls_delete_threshold
> 
> "-hls_time 10",
> "-hls_list_size 3",
> "-hls_delete_threshold 3", 
> "-hls_flags delete_segments"
> 
> > hls_delete_threshold size
> > 
> > Set the number of unreferenced segments to keep on disk before hls_flags delete_segments deletes them. Increase this to allow continue clients to download segments which were recently referenced in the playlist. Default value is 1, meaning segments older than hls_list_size+1 will be deleted.

**Comment by landydawood** [comment]
@DanielnetoDotCom can you please explain more

**Comment by akhilleusuggo** [comment]
You need to add parameters that will delete the HLS stored .
That means when you end the stream , the HLS will be deleted , and none will be able to play them back , since they don't exist anymore .

**Comment by landydawood** [comment]
i did but today i had again same problem the stream stop but is showing is online and when im try to restream again is showing me this errors 


![99439972_245600376540527_3992583924571176960_n](https://user-images.githubusercontent.com/63321733/82718234-4ae44c00-9c6f-11ea-9f8f-2c9d595c8326.jpg)
![98731888_281136232933050_8603540279594582016_n](https://user-images.githubusercontent.com/63321733/82718237-50da2d00-9c6f-11ea-9fe9-1c9e6194c088.jpg)

**Comment by landydawood** [comment]
any answer ??

**Comment by akhilleusuggo** [comment]
@landydawood make screenshot of your plugin Live

**Comment by landydawood** [comment]
@akhilleusuggo  I'm not sure what you want exactly but dose this what you looking for ??? 
![ttttttttttt](https://user-images.githubusercontent.com/63321733/83184290-400a3b00-a0f7-11ea-907e-ae70ff760c3c.JPG)

**Comment by akhilleusuggo** [comment]
I mean this : 
![image](https://user-images.githubusercontent.com/52116577/83207585-35ce5800-a15c-11ea-8ec1-630902ed07d4.png)

**Comment by landydawood** [comment]
![tttttttttt](https://user-images.githubusercontent.com/63321733/83294510-685b6d80-a1bb-11ea-9550-050d6b074bda.JPG)

**Comment by akhilleusuggo** [comment]
Add this parameters to your nginx config ( under application live ) , then restart nginx : 

`push_reconnect 1s;`
`session_relay on;`
`hls_nested on;`

Also I would recommend you to play with on and off , depending on your issues . Try this to start .

**Comment by landydawood** [comment]
thanks for your help i will update you soon with any problem lol
