### ISSUE TITLE
after git pull

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#3047]
I access AVideo's Streamer after git pull.
Avideo displayed next.
![3](https://user-images.githubusercontent.com/46562199/81624928-6f9c2080-9432-11ea-89d3-14f51b3544d5.png)

Which files  do I change ?

**Comment by DanielnetoDotCom** [comment]
delete your cache dir.

also, review your configuration.php file, we made an update on it.

**Comment by hnagasawa** [comment]
I deleted /var/www/html/AVideo/videos/cache. but same.
ls -l /var/www/html/AVideo/videos/configuration.php
-rw-r--r-- 1 www-data www-data 1447  5月 12 09:18 /var/www/html/AVideo/videos/configuration.php
[configuration.zip](https://github.com/WWBN/AVideo/files/4612798/configuration.zip)
ls -l /var/www/html/AVideo/objects/configuration.php
-rw-r--r-- 1 root root 14761  5月 12 09:17 /var/www/html/AVideo/objects/configuration.php

[configuration.zip](https://github.com/WWBN/AVideo/files/4612808/configuration.zip)

Which file do we check ?

**Comment by DanielnetoDotCom** [comment]
I cannot see any problem if still, the problem check your HTML source code for wrong paths

**Comment by hnagasawa** [comment]
I do not edit HTML. I did git pull only.
Do we have to reinstall AVideo again ?

**Comment by DanielnetoDotCom** [comment]
I am not saying you edit your HTML, I am asking you to verify how is it being generated

can you share your site URL?

**Comment by hnagasawa** [comment]
This AVideo site is local IP. Can you use anydesk ? I send you AnyDesk ID developer@youphptube.com

**Comment by DanielnetoDotCom** [comment]
do this ...

Edit your configuration.php file, it is located inside your videos directory.

there you will find this 
![image](https://user-images.githubusercontent.com/18009293/81632613-1d7edf00-93e1-11ea-8490-0df13ccd49f9.png)

Remove the lines that are dynamically creating your variable $global['webSiteRootURL']

and force it to be the correct one (Not dynamic). then your code will look like this 


![image](https://user-images.githubusercontent.com/18009293/81632640-2bccfb00-93e1-11ea-923f-95c5d9829b45.png)

**Comment by hnagasawa** [comment]
Thank you for your support.
I corrected My Avideo.

Why do this trouble occure ?

**Comment by DanielnetoDotCom** [comment]
I still figuring out how to show free videos with ads.
