### ISSUE TITLE
embedded videos do not show a share button and right click is completely disabled on the player

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3048]
embedded videos do not show a share button and right click is completely disabled on the player. No menu showing.
I have the share button enabled in the customize plugin. 

I have a emebed here u can see https://www.joshwho.net/video-emerges-of-biden-admitting-he-was-arrested-for-following-female-college-students/

**Comment by DanielnetoDotCom** [comment]
Sorry I do not understand

**Comment by JoshWho** [comment]
Normaly you should be able to right click on the video and click copy video link or current time of video link etc...

Try right clicking on the video here https://www.joshwho.net/video-emerges-of-biden-admitting-he-was-arrested-for-following-female-college-students/

**Comment by ronaldod** [comment]
I think you refer that normal you have :
![image](https://user-images.githubusercontent.com/31585599/81721222-d7c52380-947f-11ea-87b6-8b7fd5107e30.png)

But now you have none, better said there is total no right click response.

**Comment by DanielnetoDotCom** [comment]
Please try this

**Comment by ronaldod** [comment]
I tested the new build and it worked for me. Tested the `</>Copy embed Code`. And that did not work. Removed the test till <iframe>  and then it worked correctly. 
Checked with an older installation and i see that now before the  <iframe>   this piece of code is added : `<div class="embed-responsive embed-responsive-16by9">`

**Comment by DanielnetoDotCom** [comment]
Hi, I dont understand .

I tried here and it works https://demo.avideo.com/video/242/avideo1080hd?channelName=TheAdminChannel

**Comment by DanielnetoDotCom** [comment]
For some reason it is not working o demo site, I have to check what is going on

**Comment by ronaldod** [comment]
Found the typo at paste 😨. Works now without any problems.  👍

**Comment by JoshWho** [comment]
Looks GOod. Thank you
