### ISSUE TITLE
Embed Podcast MP3s does not play

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3049]
just shows Network Error with the Gif of a Tape Player in the background.

 <img src="https://static.buddylist.co/43ab1e58-6faf-4468-b01e-3894d891b6cf.png" style='width:100%;' border="0" alt="Null">

**Comment by akhilleusuggo** [comment]
@JoshWho out of topic , but I was checking some security . Blocking to access to .git/* on my sites , checked yours , and you have added a ''ban'' to the once who access to them . But it's a troll right ?
Cause I were still able to browse the site . Or maybe not working cause i'm using VPN ?

I like the song btw xD

**Comment by JoshWho** [comment]
Yeah it was a honey pot forwarder it doesn't fully ban unless you did a big no no LOL

**Comment by DanielnetoDotCom** [comment]
@JoshWho can you please share a link so I can check?

also can you share a link I can test to embed myself and see what is going on?

**Comment by JoshWho** [comment]
Here https://www.joshwhotv.com/testing.php

**Comment by JoshWho** [comment]
DevTools failed to load SourceMap: Could not load content for http://localhost:8080/headless-content.js.map: Connection error: net::ERR_CONNECTION_REFUSED

**Comment by JoshWho** [comment]
Looks like it is not loading from my cdn address

**Comment by DanielnetoDotCom** [comment]
or maybe it is corrupted

are you sure this file exists?

**Comment by akhilleusuggo** [comment]
the file is corrupted for sure .
