### ISSUE TITLE
.mov videos are not working.

### ISSUE THREAD

**Issue by sharad22gupta** [WWBN/AVideo#3051]
when i upload iphone videos, its not playing. but mp4 videos are working fine. @akhilleusuggo @DanielnetoDotCom

**Comment by akhilleusuggo** [comment]
mov video's coded ( .mov extension ) is not supported on HTML5 

You need to re-encode them to mp4 or other html supported codecs . 
Take a look what codecs are supported on HTML5 ( mp4 / webm / hls , recommended )
