### ISSUE TITLE
After update , all video private ( userMustBeLoggedIn )

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3053]
After update , all video's requires to be logged in to view .

![image](https://user-images.githubusercontent.com/52116577/81758136-a5401880-94c9-11ea-8238-242d147d9b18.png)

I made sure that I have the option disabled . 

![image](https://user-images.githubusercontent.com/52116577/81758263-e801f080-94c9-11ea-9a62-53863b25c752.png)

**Comment by DanielnetoDotCom** [comment]
check the log file, usually, you can see there why is it private

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 
```
13-May-2020 03:58:35 Europe/Helsinki] User::userCanWatchVideoWithAds (No can not)  3845
[13-May-2020 03:58:35 Europe/Helsinki] User::canWatchVideo there is no usergorup set for this video but A plugin said user [] can not see (3845)
[13-May-2020 03:58:35 Europe/Helsinki] User::canWatchVideo (No can not) 3845

```

**Comment by DanielnetoDotCom** [comment]
Are you sure you do not have this checked for this video?

![image](https://user-images.githubusercontent.com/18009293/81760063-b161b100-949c-11ea-9edc-0629d298e9a4.png)

do you have PPV or Subscription plugin?

Usually, in the log file, we can see what plugins are denying the user to watch

**Comment by akhilleusuggo** [comment]
I don't have that plugin .

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/81760427-d28fc500-94cf-11ea-8975-2d27b309d1d6.png)

This same video I'll play it on logged out mode : 
```
[13-May-2020 04:12:42 Europe/Helsinki] User::userCanWatchVideoWithAds (No can not)  4303
[13-May-2020 04:12:42 Europe/Helsinki] User::canWatchVideo there is no usergorup set for this video but A plugin said user [] can not see (4303)
[13-May-2020 04:12:42 Europe/Helsinki] User::canWatchVideo (No can not) 4303

```

**Comment by akhilleusuggo** [comment]
Cleared the cache , didn't help , got some errors : 
```
[13-May-2020 04:14:54 Europe/Helsinki] Not authorized compile css
[13-May-2020 04:14:55 Europe/Helsinki] Not authorized compile css
[13-May-2020 04:14:55 Europe/Helsinki] Not authorized compile css
[13-May-2020 04:14:55 Europe/Helsinki] Not authorized compile css
[13-May-2020 04:15:00 Europe/Helsinki] Not authorized compile css

```

**Comment by praiseworld3d** [comment]
I just updated today and have the same issue. All videos require login/signup and says video is private. None of the videos by all users are private.

**Comment by akhilleusuggo** [comment]
Same here

**Comment by DanielnetoDotCom** [comment]
I sent an update, please check it now.

**Comment by akhilleusuggo** [comment]
Works !

Another question : 

`cd /var/www/html/YouPHPTube/plugin/User_Location/install && unzip ip2location_db1_ipv6.zip && mysql -u root -p youPHPTube <  /var/www/html/YouPHPTube/plugin/User_Location/install/ip2location_db1_ipv6.sql `

On the mysql -u root -p youPHPTube , the password has to be youPHPTube or the database and username password ?

And isn't it better to just delete the User_Location ( from plugins and database table ) , and fresh install of the new database ?

**Comment by praiseworld3d** [comment]
Thanks for the fix, all good now.

**Comment by DanielnetoDotCom** [comment]
> Works !
> 
> Another question :
> 
> `cd /var/www/html/YouPHPTube/plugin/User_Location/install && unzip ip2location_db1_ipv6.zip && mysql -u root -p youPHPTube < /var/www/html/YouPHPTube/plugin/User_Location/install/ip2location_db1_ipv6.sql `
> 
> On the mysql -u root -p youPHPTube , the password has to be youPHPTube or the database and username password ?
> 
> And isn't it better to just delete the User_Location ( from plugins and database table ) , and fresh install of the new database ?

youPHPTube  is the database name, you must edit this command to fit in your needs

**Comment by akhilleusuggo** [comment]
yes my bad , confused . Works thank you
