### ISSUE TITLE
Http2 performance boost

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#3054]
**Describe the question**
Speeding up the website.

I did some minimal speedtest with http2 on apache2 enable. And the difference is interesting.

**Screenshots**
before :
![image](https://user-images.githubusercontent.com/31585599/81780579-08946f80-94f7-11ea-96d1-302bc97a0889.png)

after: 
![image](https://user-images.githubusercontent.com/31585599/81780621-1f3ac680-94f7-11ea-969a-038fe3475efc.png)

It did lower the load time on the page from 3.4 seconds to 2 second. And the Time to be interactive from 6.2s to 4.7s.

Any other who looked into this and if they now drawbacks of enabling http2 ?

As for the settings i followed the instructions from [here](https://gist.github.com/GAS85/8dadbcb3c9a7ecbcb6705530c1252831)

Edit :

It only supports SSL connections

**Comment by ronaldod** [comment]
Bug 1 with http2 -At the moment encoder has some issues with http2 file upload. Going to investigate.

**Comment by akhilleusuggo** [comment]
have you cleared the cache after each test ?

**Comment by ronaldod** [comment]
With http2 yes. And i'm going to build 2 servers both 100% the same but one with http2 enabled and the other classic. They both going to run on the same vm host. Then i can create a test procedure and show the longer test results.

Just one thing HTTP2 is only usefull between outside connection and the fornted. Not between reverse proxy(frontend) and the backend.

**Comment by ronaldod** [comment]
Server 1 without http/2:
![image](https://user-images.githubusercontent.com/31585599/81849735-445f2180-9557-11ea-9095-08e9e52eecd8.png)

server 2 with http/2:

![image](https://user-images.githubusercontent.com/31585599/81849819-5f319600-9557-11ea-8851-470bdcf87a02.png)

Would be nice if someone else could confirm.

There is a non caching proxy in front of it who no special config for http/2 (HAproxy).

**Comment by akhilleusuggo** [comment]
I'll take a look at that . On my website I'm using cloudflare , and has http/2 already 
![image](https://user-images.githubusercontent.com/52116577/81855399-fd2d5c80-9567-11ea-9f1e-c16c6d94ede7.png)

**Comment by ronaldod** [comment]
@akhilleusuggo Nice. Cloudflare knows what makes a website fast. I'm just figuring it out for the "basic" install. If you run your site by chrome "lighthouse" what is then the rating ?

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/81868627-4d61ea00-957b-11ea-8dc8-9a31dd6fe64d.png)

This gonna depend a lot of how much videos you have on your first page I guess

**Comment by akhilleusuggo** [comment]
Other pages : 

![image](https://user-images.githubusercontent.com/52116577/81868768-8e59fe80-957b-11ea-93e9-e14291b7aa92.png)

**Comment by ronaldod** [comment]
The above metrics are from your site. Nice impressive speeds.

About preloading :
Yes it is doing a preload of the first video file. And load all the animated/moving gifs, those should be in future migrated to mp4. To lower the amount of data. So many thoughts..

**Comment by akhilleusuggo** [comment]
@ronaldod they should be webp ( they are already ) but need better compression .
Also I already asked daniel about something that youtube did on phones . Multiple gifs . Holding the mouse on the video , plays first gif , then , second etc ... ( video 10mn/5 , plays 5 gifs , 20% 40% etc )

**Comment by ronaldod** [comment]
yups first the low hanging fruit. But that is for later. So many options still.

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/81874305-4ab8c200-9586-11ea-9e2e-5207b523468e.png)

I've followed this guide : 
https://www.howtoforge.com/how-to-enable-http-2-in-apache/

**Comment by ronaldod** [comment]
And is the encoder uploading files ? I have some serious issues with that (integrated) setup.

**Comment by akhilleusuggo** [comment]
Just tested , and had problems . 
`The uploaded file exceeds the upload_max_filesize directive in php.ini`

This is because now I'm using the config on `/etc/php/7.2/fpm/php.ini`

You need to restart php-fpm and NOT apache2 
`/etc/init.d/php7.0-fpm restart`

You will also have to make all the modification that you have made to your default apache php.ini into the php-fpm .

After making the changes , everything worked fine 

One error that I have found , is the encoder /status ( the one reports to streamer site how much % is encoded and queue )

I'll dig more into it .

**Comment by ronaldod** [comment]
Yes those i also found. That last one on reporting status i did not seen yet but uploading an encoded file to the server give stream error. 
I downgraded curl to http1.1 with an extra option in php and it connects but it looks it is not authenticated even the authentication is in the curl session. 
See mine ticket in [the encoder](https://github.com/WWBN/AVideo-Encoder/issues/255#issuecomment-628274240) issue list.

**Comment by akhilleusuggo** [comment]
btw why http2 and not http3 ( HTTP-over-QUIC ) . Any idea ?
