### ISSUE TITLE
jquery is at 3.3.1 but has vulnerabilities

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#3055]
**Describe the bug**
jquery is at 3.3.1 but has vulnerabilities
[Link to report](https://snyk.io/vuln/SNYK-JS-JQUERY-567880)

**Expected behavior**
Upgrade the jquery to 3.5.1

**Comment by DanielnetoDotCom** [comment]
Thanks, Update sent

**Comment by ronaldod** [comment]
Tested and not issues seen.
