### ISSUE TITLE
Bootstrap 3.3.7 has vulnerabilities

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#3056]
**Describe the bug**
Bootstrap 3.3.7 has vulnerabilities
[Link](https://snyk.io/vuln/npm:bootstrap?lh=3.3.7&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit)

**To Reproduce**
Check version

**Expected behavior**
Upgrade to 4.5.0

**Comment by DanielnetoDotCom** [comment]
Unfortunately, I cannot upgrade to Bootstrap version 4.x.
there are a lot of differences in the CSS classes. we will stick on version 3 for a while 

But there is v3.4.1 that may fix this problem.

**Comment by ronaldod** [comment]
I think this need to go on a the roadmap.
