### ISSUE TITLE
Adding woff2 files to the caching policy

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#3057]
**Is your feature request related to a problem? Please describe.**
Improving the overall performance of the site.

**Describe the solution you'd like**
As far i know those woff2 files are static. And speed of the site can be slightly improved.
Editing the .htaccess  file and add the extension to the caching list.

previous :
![image](https://user-images.githubusercontent.com/31585599/81783582-da655e80-94fb-11ea-95cc-2e2ee30877dd.png)

After:
![image](https://user-images.githubusercontent.com/31585599/81783657-f0731f00-94fb-11ea-9c7d-881012c1d9d6.png)

**Comment by DanielnetoDotCom** [comment]
Can you please help with that? Is not clear to me how to do that

**Comment by ronaldod** [comment]
Woff2 files are font package used in .css. In mine opinion they are static like css files and should be cached in the same manner.

Is just for more compliancy and speed performance.

The pictures i show  above are from the lighthouse audit module in the chrome browser to compare the effect of changes. 

Adding to the .htaccess file in one of the exsisting rules or a new one:
```
    <filesMatch "\.(woff2|css)$">
        Header set Cache-Control "max-age=604800, public"
    </filesMatch>
```

I am now looking into things to make site working more optimal/faster and complaint to give the enduser a very snappy look and feel. Also these things give a better result in SEO results as google also count loading time of a page for their ranking.

**Comment by DanielnetoDotCom** [comment]
Like this?

**Comment by ronaldod** [comment]
Yes. If it save to cache then cache it.
