### ISSUE TITLE
Videos are shown multiple times in category view

### ISSUE THREAD

**Issue by SaliC-re** [WWBN/AVideo#3059]
Hey,

I'm using the YouTube skin and I deactived all rows except the categories. I want to have the videos shown on first page sorted in categories - which works fine at first.

The problem is that I have the videos in a subcategory. And on the first page the videos are shown in the main category AND the subcategory. I thinks it is more logical and userfriendly if the videos are shown ONLY in subcategory form. Do you have a quick fix for that? Or did I forget a checkbox somewhere.

PS: The same effect in "Gallery" theme, too

**Comment by DanielnetoDotCom** [comment]
Hi

can you please screenshot some pages to make clear what you mean?

**Comment by SaliC-re** [comment]
> Hi
> 
> can you please screenshot some pages to make clear what you mean?

![Anmerkung 2020-05-14 082830](https://user-images.githubusercontent.com/63057086/81900364-ebc26f80-95bc-11ea-8d98-6b74298d8044.jpg)

**Comment by DanielnetoDotCom** [comment]
I see, but you also can have videos on the main category, so I cannot remove it.

are you saying the videos from the subcategories are showing in the main category? (I could not see clearly from the image)

**Comment by SaliC-re** [comment]
> I see, but you also can have videos on the main category, so I cannot remove it.
> 
> are you saying the videos from the subcategories are showing in the main category? (I could not see clearly from the image)

Of course - you should be still able to have videos in the main cat. But all videos which are in the sub cat are shown in the main cat row, too. So you Always see the videos twice on the site. So you are right with your last sentence. In my logic the videos should only be in the sub cat

**Comment by DanielnetoDotCom** [comment]
@SaliC-re I guess the correct approach should be not to show the subcategory, only the main category. what do you think?

**Comment by SaliC-re** [comment]
> @SaliC-re I guess the correct approach should be not to show the subcategory, only the main category. what do you think?

In my opinion if you use a subcategory, you should see the subcategory - why should you use it though? :D Maybe you can add something like a hierarchy in the subcategory names.
Like in the admin-view.

Like "MainCat/Subcat" and then you see the videos only one time in the subcat row.

Good idea?
