### ISSUE TITLE
Upload error with the encoder

### ISSUE THREAD

**Issue by WGtechy** [WWBN/AVideo#3060]
**Describe the question**
Greetings.

i configured my encoder on a separate server but the encoder is not uploading the video to my streamer site, instead it sends the image
![Screenshot 2020-05-13 15 37 55](https://user-images.githubusercontent.com/55572107/81826692-f551c600-952f-11ea-9284-e82b6b7025ff.png)

please how can i work around this?

**Comment by ronaldod** [comment]
I see that the encoder tries to send it to mysite.com. How do you login into the encoder ?

**Comment by akhilleusuggo** [comment]
`php fatal error uncaught error call to undefined function utf8_encode()`

Try to update php . What version are you using ? What version of ubuntu are you using ?

`sudo apt-get install php-xml`
`sudo service apache2 restart`

**Comment by WGtechy** [comment]
> `php fatal error uncaught error call to undefined function utf8_encode()`
> 
> Try to update php . What version are you using ? What version of ubuntu are you using ?
> 
> `sudo apt-get install php-xml`
> `sudo service apache2 restart`

its still not working

**Comment by ronaldod** [comment]
undefined error is from that it cannot connect to the server as it tries to connect with the url mysite.com. Is the video site hosted under that domain ?

**Comment by WGtechy** [comment]
> undefined error is from that it cannot connect to the server as it tries to connect with the url mysite.com. Is the video site hosted under that domain ? Or is that to anonymize the logging ?

i have encoder on my streamer server and i setup another encoder on another server but i am having the same issue. when i share video with youtube link, it will only upload and get the images of the videos but it wont download the main videos to the streamer site.

Hope you understand the situation now?

Thanks i'm awaiting your quick response.

**Comment by ronaldod** [comment]
It reads now that @akhilleusuggo is correct. It is not finding that function. He sended function to restart apache in the idea your using standard php  
If you use FPM/FastCGI. The latest you also need to restart this service module. Based on your version you need to tweak the command `sudo service php7.4-fpm restart` To get the php-xml activated this service needs to be restarted.

**Comment by WGtechy** [comment]
> It reads now that @akhilleusuggo is correct. It is not finding that function. He sended an instruction to restart apache in the idea your using standard php.
> If you use FPM/FastCGI. Then you need to restart the php7.4-fm service module. Based on your version you need to tweak the command `sudo service php7.4-fpm restart` To get the php-xml activated this service needs to be restarted. And as it is just an external encoder just reboot the encoder if your not sure how to do it.

its still not working. I executed the commands sudo apt-get install php-xml
sudo service apache2 restart on both the streamer and encoder servers separately and restarted them but no changes.

**Comment by WGtechy** [comment]
![Screenshot 2020-05-14 17 15 22](https://user-images.githubusercontent.com/55572107/81958907-8eeba700-9606-11ea-8154-61644cd2b6c0.png)

Same issue after trying the steps. Ill really love it to work, please take a look at the log file again

**Comment by WGtechy** [comment]
> `php fatal error uncaught error call to undefined function utf8_encode()`
> 
> Try to update php . What version are you using ? What version of ubuntu are you using ?
> 
> `sudo apt-get install php-xml`
> `sudo service apache2 restart`
i am using version 7.0

**Comment by WGtechy** [comment]
> `php fatal error uncaught error call to undefined function utf8_encode()`
> 
> Try to update php . What version are you using ? What version of ubuntu are you using ?
> 
> `sudo apt-get install php-xml`
> `sudo service apache2 restart`

php7.0 on the streamer site

**Comment by WGtechy** [comment]
PHP 7.0.33-0ubuntu0.16.04.14 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0ubuntu0.16.04.14, Copyright (c) 1999-2017, by Zend Technologies

i tried `sudo apt-get update` it didnt update

**Comment by ronaldod** [comment]
Did you tried also with another video because the description 
![image](https://user-images.githubusercontent.com/31585599/81959670-1c7fc480-9610-11ea-892f-2c0acf333d63.png)
is having `{}` and those characters can messup.

**Comment by WGtechy** [comment]
> Did you tried also with another video because the description
> ![image](https://user-images.githubusercontent.com/31585599/81959670-1c7fc480-9610-11ea-892f-2c0acf333d63.png)
> is having `{}` and those characters can messup.

Yes i tried another video still the same

**Comment by WGtechy** [comment]
i aslo use this`sudo apt-get upgrade` to upgrade it and its php7.0

**Comment by ronaldod** [comment]
`sudo apt-get install php7.0-xml`
followed with `sudo service apache2 restart`

Interested in the answer of the first command.

**Comment by WGtechy** [comment]
> sudo service apache2 restart

i did for both server its still not working. Only the picture is sent to the streamer site but the video upload always fails

**Comment by ronaldod** [comment]
I need only the output from `sudo apt-get install php7.0-xml`

**Comment by WGtechy** [comment]
> `sudo apt-get install php7.0-xml`
> followed with `sudo service apache2 restart`
> 
> Interested in the answer of the first command.



`Reading package lists... Done
Building dependency tree       
Reading state information... Done
php7.0-xml is already the newest version (7.0.33-0ubuntu0.16.04.14).
The following package was automatically installed and is no longer required:
  grub-pc-bin
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`


thats the response

**Comment by WGtechy** [comment]
this is from the encoder server

`eading package lists... Done
Building dependency tree       
Reading state information... Done
php7.0-xml is already the newest version (7.0.33-0ubuntu0.16.04.14).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by ronaldod** [comment]
first you had :
![image](https://user-images.githubusercontent.com/31585599/81961934-530b0e80-9613-11ea-8873-3a6f4ee522c7.png)
now it is 
![image](https://user-images.githubusercontent.com/31585599/81962025-6cac5600-9613-11ea-806f-987e6798ca17.png)
Check rights and ownership of the maps.
Should be done like in the manual [Ubuntu 16 manual](https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x-For-AVideo-Platform-version-4.x-or-newer)
And check if all the listed packages are installed.

**Comment by WGtechy** [comment]
> this is from the encoder server
> 
> `eading package lists... Done Building dependency tree Reading state information... Done php7.0-xml is already the newest version (7.0.33-0ubuntu0.16.04.14). 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

should i do this on the streamer site or the encoder?
if its going to be on the streamer site, should i follow all the instructions again and if i do hope it wont affect my current site content?

**Comment by ronaldod** [comment]
encoder only.

**Comment by WGtechy** [comment]
> Encoder only. And if you want to rebuild request the latest ubuntu. go to 20. And allways have a backup or snapshot before upgrading. Or rent somewhere an other VPS to test on for $4.

Okay let me do it on encoder

**Comment by WGtechy** [comment]
But the link is not for encoder only. its for both encoder and streamer or only streamer 

if i use it that means im going to be installing streamer also on the encoder server.

Shoud i use the Encoder instructions instead ?

**Comment by ronaldod** [comment]
Just a question what did you change before this all happened ? New installation or an old one ?

**Comment by WGtechy** [comment]
old installation. lol i cant do new installation on my streamer server, i have good content on it already but i can format and reinstall the encoder server if its necessary

**Comment by ronaldod** [comment]
As this in an encoder issue do the encoder. But still weird as things do not break just by nothing happening.

**Comment by WGtechy** [comment]
so i should run `sudo git clone https://github.com/WWBN/AVideo-Encoder`

**Comment by ronaldod** [comment]
Depends only if you erased the old server. Else i would skip it.

**Comment by ronaldod** [comment]
If you have doubts dont do it and contact @DanielnetoDotCom by notification and mail developer@youphptube.com for some direct (paid) support. As an older installation upgrading can give issues.

**Comment by WGtechy** [comment]
okay

**Comment by WGtechy** [comment]
> If you have doubts dont do it and contact @DanielnetoDotCom by notification and mail [developer@youphptube.com](mailto:developer@youphptube.com) for some direct (paid) support. As an older installation upgrading can give issues.

see what i see when i tried this

`sudo apt-get install apache2 php7.2 libapache2-mod-php7.2 php7.2-mysql php7.2-curl php7.2-gd php7.2-intl mysql-server mysql-client ffmpeg git libimage-e
xiftool-perl php7.2-xml && cd /var/www/html && sudo git clone https://github.com/WWBN/AVideo-Encoder.git && sudo apt-get install python && sudo curl -L https://yt-dl.org/downl
oads/latest/youtube-dl -o /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package php7.2
E: Couldn't find any package by glob 'php7.2'
E: Couldn't find any package by regex 'php7.2'
E: Unable to locate package libapache2-mod-php7.2
E: Couldn't find any package by glob 'libapache2-mod-php7.2'
E: Couldn't find any package by regex 'libapache2-mod-php7.2'
E: Unable to locate package php7.2-mysql
E: Couldn't find any package by glob 'php7.2-mysql'
E: Couldn't find any package by regex 'php7.2-mysql'
E: Unable to locate package php7.2-curl
E: Couldn't find any package by glob 'php7.2-curl'
E: Couldn't find any package by regex 'php7.2-curl'
E: Unable to locate package php7.2-gd
E: Couldn't find any package by glob 'php7.2-gd'
E: Couldn't find any package by regex 'php7.2-gd'
E: Unable to locate package php7.2-intl
E: Couldn't find any package by glob 'php7.2-intl'
E: Couldn't find any package by regex 'php7.2-intl'
E: Unable to locate package php7.2-xml
E: Couldn't find any package by glob 'php7.2-xml'
E: Couldn't find any package by regex 'php7.2-xml'`

**Comment by WGtechy** [comment]
its readable this way: i run this installation code on the same encoder server 

```
sudo apt-get install apache2 php7.2 libapache2-mod-php7.2 php7.2-mysql php7.2-curl php7.2-gd php7.2-intl mysql-server mysql-client ffmpeg git libimage-e
xiftool-perl php7.2-xml && cd /var/www/html && sudo git clone https://github.com/WWBN/AVideo-Encoder.git && sudo apt-get install python && sudo curl -L https://yt-dl.org/downl
oads/latest/youtube-dl -o /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl
```

**Comment by WGtechy** [comment]
Reading package lists... Done

Building dependency tree       

Reading state information... Done

E: Unable to locate package php7.2

E: Couldn't find any package by glob 'php7.2'

E: Couldn't find any package by regex 'php7.2'

E: Unable to locate package libapache2-mod-php7.2

E: Couldn't find any package by glob 'libapache2-mod-php7.2'

E: Couldn't find any package by regex 'libapache2-mod-php7.2'

E: Unable to locate package php7.2-mysql

E: Couldn't find any package by glob 'php7.2-mysql'

E: Couldn't find any package by regex 'php7.2-mysql'

E: Unable to locate package php7.2-curl

E: Couldn't find any package by glob 'php7.2-curl'

E: Couldn't find any package by regex 'php7.2-curl'

E: Unable to locate package php7.2-gd

E: Couldn't find any package by glob 'php7.2-gd'

E: Couldn't find any package by regex 'php7.2-gd'

E: Unable to locate package php7.2-intl

E: Couldn't find any package by glob 'php7.2-intl'

E: Couldn't find any package by regex 'php7.2-intl'

E: Unable to locate package php7.2-xml

E: Couldn't find any package by glob 'php7.2-xml'

E: Couldn't find any package by regex 'php7.2-xml'

**Comment by ronaldod** [comment]
your running ubuntu 16 as far i remember  then only php  7.0 modules are possible. php 7.2 is for 18,  php 7.4 for 20.

**Comment by WGtechy** [comment]
okay

**Comment by WGtechy** [comment]
> your running ubuntu 16 as far i remember then only php 7.0 modules are possible. php 7.2 is for 18, php 7.4 for 20.

 i installed the Encoder on another ubuntu 18. server but its processing nonstop. Please what can i do since there are no logs in the server?


![Screenshot 2020-05-22 10 03 59](https://user-images.githubusercontent.com/55572107/82651605-45a5e380-9c14-11ea-806d-8f2af8a44001.png)

**Comment by ronaldod** [comment]
Biggest chance is that he can not reach your video server. Check the spelling of the url or that he can reach your video server.
 If your server is running https make sure your url starts with that.

**Comment by akhilleusuggo** [comment]
@WGtechy 

1) I'm confused , are you sure you're using ubuntu 18 ?
2) Are you using google cloud ? If yes , make sure to open the ports ( and configure the firewalls )
3) Make sure that the mod-rewrite is enabled 
4) I'll write for you the step you do , 1 by one , not all on one line 

1- `sudo apt-get install apache2 php libapache2-mod-php php-mysql php-curl php-gd php-intl mysql-server mysql-client git`  (Most of them may be ignore , since you have them already installed)
2- `cd /var/www/html`
3- `sudo git clone https://github.com/WWBN/AVideo-Encoder.git`
4- `sudo nano /etc/apache2/apache2.conf`
5- Find `<Directory /var/www/>` and make sure that `AllowOverride All` is set to **All**
6- `sudo a2enmod rewrite`
7- `service apache2 restart`
8- `cd /var/www/html`
9- `chown www-data:www-data -R *`

You should be able to run without problems .
About the firewall , since you will have problems later for NGINX for live-streams , this is a demo if you want to open all ports .

![image](https://user-images.githubusercontent.com/52116577/80041013-ff217400-8503-11ea-833e-6e21b450f4a3.png)

**Comment by WGtechy** [comment]
i did follw the instructions again but the encoder is still processing 

> @WGtechy
> 
> 1. I'm confused , are you sure you're using ubuntu 18 ?
> 2. Are you using google cloud ? If yes , make sure to open the ports ( and configure the firewalls )
> 3. Make sure that the mod-rewrite is enabled
> 4. I'll write for you the step you do , 1 by one , not all on one line
> 
> 1- `sudo apt-get install apache2 php libapache2-mod-php php-mysql php-curl php-gd php-intl mysql-server mysql-client git` (Most of them may be ignore , since you have them already installed)
> 2- `cd /var/www/html`
> 3- `sudo git clone https://github.com/WWBN/AVideo-Encoder.git`
> 4- `sudo nano /etc/apache2/apache2.conf`
> 5- Find `<Directory /var/www/>` and make sure that `AllowOverride All` is set to **All**
> 6- `sudo a2enmod rewrite`
> 7- `service apache2 restart`
> 8- `cd /var/www/html`
> 9- `chown www-data:www-data -R *`
> 
> You should be able to run without problems .
> About the firewall , since you will have problems later for NGINX for live-streams , this is a demo if you want to open all ports .
> 
> ![image](https://user-images.githubusercontent.com/52116577/80041013-ff217400-8503-11ea-833e-6e21b450f4a3.png)

**Comment by WGtechy** [comment]
> Biggest chance is that he can not reach your video server. Check the spelling of the url or that he can reach your video server.
> If your server is running https make sure your url starts with that.

Yes that is what i did and its still the same

**Comment by akhilleusuggo** [comment]
ok , let's try something different : 

Try to change your host name : 
`sudo hostnamectl set-hostname server.wgtechy.com`  **_Don't worry about this domain , is not for your site . Make sure is not the same as your domain name_** !!

sudo nano /etc/hosts
127.0.0.1 server.wgtechy.com

`cd /var/www/html && chown www-data:www-data -R *`

Try this , maybe you're issue is here .

**Comment by WGtechy** [comment]
i really want to thank  @akhilleusuggo  @ronaldod @DanielnetoDotCom for the timely concern and support. Encoder is working now perfectly. The next thing im dealing with now is the NGINX. 

when i tried to restart nginx i got this error: nginx: [emerg] invalid port in url "https://www.MYSITE/plugin/Live/on_publish.php" in /usr/local/nginx/conf/nginx.conf:24

**Comment by akhilleusuggo** [comment]
So the hostname was the issue ? I'll apreciate the feed back . So we can close this issue and tag it as closed , so in future someone is having a similar problem , we can redirect it here .
For your nginx problem , please open a new issue .

**Comment by WGtechy** [comment]
Funny enough i switched to ubuntu 18+ for my encoder while following the prescribed instructions you gave and i also worked on the hostname on the streamer site.

**Comment by WGtechy** [comment]
im not sure if the encoder can work on ubuntu 16+

**Comment by DanielnetoDotCom** [comment]
Encoder can work on Ubuntu 16

**Comment by akhilleusuggo** [comment]
we fixed this issue .

**Comment by WGtechy** [comment]
> we fixed this issue .

> Encoder can work on Ubuntu 16


Yes we fixed the issue but its on ubuntu 18+
I still have an encoder on same server with my streamer site that is still not working

**Comment by akhilleusuggo** [comment]
if you want a better support , don't bring 10 different issues into one . Open a new issue for each issue , so we can't help you better , and redirect users to your issue in case they're having the same . 

Not so hard to open a new issue , describing your details .
