### ISSUE TITLE
YouPHPFlix2-plugin playlists don't show up

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3062]
In YouPHPFlix2-plugin there is an option to show playlists on front page row, but when checked there isn't one on frontpage. 

![kuva](https://user-images.githubusercontent.com/63721378/81831197-bd557d80-9545-11ea-831f-f6a4a678b2ca.png)

**Comment by DanielnetoDotCom** [comment]
What front page theme are you using?

**Comment by DanielnetoDotCom** [comment]
I just inspect the code and looks like we did not implement this feature yet.
