### ISSUE TITLE
Ops! Sorry, this video is private

### ISSUE THREAD

**Issue by andersonmagildo** [WWBN/AVideo#3063]
Even though the video is public, this error appears for those who are not logged in.

Ubuntu 18.04 server

**Comment by DanielnetoDotCom** [comment]
I sent a fix for it today.

**Comment by andersonmagildo** [comment]
Now works.. 
Obrigado Daniel  ;)

**Comment by millzee01** [comment]
Hi Daniel,  did you update videoEmbeded.php to fix this? because i'm getting it now.

**Comment by DanielnetoDotCom** [comment]
I did update, but please check the log file, it may tell you the reason.

**Comment by millzee01** [comment]
yeah its a strange one,  the video is in a user group (so only the logged in usr can see the video)

However i'd like the videoEmbed to be able to view the video (even when its in a group)

Is there a way to bypass the check?

in the log I get:
[03-Jul-2020 19:07:22 Europe/London] User::canWatchVideo (No can not) 732 

which is exactly what I would expect.

**Comment by millzee01** [comment]
i'll create a new issue Daniel because i dont think my problem has anything to do with htis.
