### ISSUE TITLE
Bugs on Log file

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3064]
Too much changes , couldn't track them .

1) Bugs : Time log 
All the timings are wrong .
 `Page generated in 1589406534.0122 seconds. User: Not Logged `

2) HLS . I don't really know if now we can follow the logs of hls , but is not reported correctly when changing resolution . ( Or is it just to create thumbnails ? )

 `HLS.php: session_id = 6im7d8l6urj5co9sb6ftcc21ke IP = 192.168.X.XXX URL = http://192.168.X.XXX/YouPHPTube/videos/_YPTuniqid_5eb9dcab0a4338.41074711/res720/index.m3u8`

**Comment by DanielnetoDotCom** [comment]
hum, I did not find anything like this.

can you reproduce this? or it just happens once?

**Comment by akhilleusuggo** [comment]
nono , if you git pull ( on your server ) , you gonna see this . 
I tried it on my 3 servers , and same result .

**Comment by DanielnetoDotCom** [comment]
Hi, thanks for noticing it, I just sent a fix. please update it.
