### ISSUE TITLE
LDAP Plugin enhancement idea

### ISSUE THREAD

**Issue by SaliC-re** [WWBN/AVideo#3065]
hey there,

I had an idea for the LDAP plugin.
Is it possible that all users which come in with LDAP are default in a local group or even more groups?
I think about one more field in the LDAP plugin (like the profile photo field), which says "default group for LDAP-users" and there i can choose from usergroups.

This would create a "filter" to have internal and external videos without setting videos to private.

would love it!

**Comment by DanielnetoDotCom** [comment]
this require some code.

if you want you can send details for this email developer@youphptube.com for a quote.
