### ISSUE TITLE
image404.php always being called

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#3067]
Hi,

for some reason /view/img/image404.php?notFound=1 is always being called even when i just pop my profile image in the url:

This happens on your test site as well

On the demo site i changed the test user logo (to a liverpool fc one :-) )
now if i load up the image in a new tab
https://demo.avideo.com/videos/userPhoto/photo6.png
in the console i get 
status 200 GET demo.avide...  photo6.png?1589474771
status 302 GET demo.avide... fvicon.ico
status 404 GET demo.avide... image404.php?notfound=1

The image loads fine but this image404 call causes an issue when I want to dd my profile image to a video using ffmpeg.

How can I stop the image404.php from being called because its not really needed when the file exists.

**Comment by DanielnetoDotCom** [comment]
Hi, I did not understand your issue, can you please get some screenshots to illustrate it?

**Comment by millzee01** [comment]
To recreate the issue, simply open your console and pop this into your browser:
https://demo.avideo.com/videos/userPhoto/photo1.png?1589904045

even tho the image exists you still get this:
image404.php:1 GET https://demo.avideo.com/view/img/image404.php?notFound=1 404 (Not Found)

This happens browsing direct to all images in the video folder as well.

**Comment by DanielnetoDotCom** [comment]
Hi

For the image link from demo site you share here, it opens normally.

![image](https://user-images.githubusercontent.com/18009293/82434302-0b4c1300-9a69-11ea-83f6-eb8e4c08b236.png)
