### ISSUE TITLE
Question: Set up my own Stream Server

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#3068]
Are the 'Set up my own stream server' instructions current?

In step 4 I don't see anything that resembles what is below to edit.

<img width="796" alt="Screen Shot 2020-05-14 at 3 57 04 PM" src="https://user-images.githubusercontent.com/739391/81980056-f3edcf80-95fb-11ea-9eff-2fb1cca1068f.png">

Here is what I see:

![image001](https://user-images.githubusercontent.com/739391/81980833-5398aa80-95fd-11ea-89e5-08795dea6e47.png)

Any help would be appreciated.

**Comment by akhilleusuggo** [comment]
that means you missed something on step 3

**Comment by DanielnetoDotCom** [comment]
Probably miss that `sudo wget https://raw.githubusercontent.com/DanielnetoDotCom/YouPHPTube/master/plugin/Live/install/nginx.conf`
