### ISSUE TITLE
Lack of Organized documentation for plugins being sold

### ISSUE THREAD

**Issue by Fuquan999** [WWBN/AVideo#3069]
Daniel,

You have videos for YouPHPTube and AVideo many of the videos are well outdated and confusing.  with spill over tabs (for instance YouPHPTube you have settings that state AVideo making it all the more confusing) within any recent version of your app. More so despite no speech in your videos there is no consideration for subtitles either (given no spoken words just some distracting music) since people are contributing to your project in the way of "donations" and purchase of plugins it would make sense to provide some level of decent documentation service to the consumers of your product especially those that pay in one form or another. After all, proprietary software makers do just that so "Open (paid) Source" should also be held accountable to similar standards that proprietary software makers are  as the business model you operate is really in truth not as Open as Open Source used to be but rather just as costly in totality as proprietary so why should you be given preferential treatment?.

As you know we have just purchased quite a few of the plugins from you (as to make the application whole you need virtually all the sold plugins) and given the lack of documentation you are making us wonder why we should hold proprietary software to one set of standards and then make exceptions for Paid Open Source that neither makes sense nor leans towards fairness as it totals up to more in cost if you add on top the time and effort needed to chase you for Q&A for your product that should in truth be plug and play like any proprietary application  causes less stress and less time wasting. We may all detest Bill Gates for his "wanna play GOD"  behaviour but no one can take it away from him that as complete as "Office 360" is no one ever has a problem setting it up on their computer(s) let alone have endless headaches from it. during use

So could you point me to where you have proper (I repeat) proper documentation for your plugins and applications as like pointed out you application is not really "Free" as it takes both donations and payment for the bulk of the other parts that makes the product whole so we do expect similar standard of service from you like we do from the proprietary software makers out there as customer satisfactions should also be on your menu and not just payments.

Thus, kindly point us to your documentation especially as the paid products are what make the whole  so we would appreciate documentation rather than lock-in and constant manipulations for extra cashflow extraction techniques. As we purchased the plugins to make the application WHOLE and we did so being IT folks with the view that you would have some form of related organized documentation to guide consumers and not because we wanted you to start suggesting additional fees in payment for task that any system admin could do given documentation. We were aiming to get the remaining plugins to complete the picture but now we are considering a refund so kindly point us in the right documentation direction as we truly do not want to be spending our time chasing outdated videos and web pages/links many of which are broken links or no longer  existent pages. .

Thanks
Fuquan

**Comment by DanielnetoDotCom** [comment]
I do the documentation the best I can do. I know it is not good enough. but I only recommend the documentation in this GitHub wiki. there is a lot of documentation on the internet but. I can only respond and edit for the ones we have here.

For installation on Ubuntu 16.04 use this 
https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x-For-AVideo-Platform-version-4.x-or-newer

For Ubuntu 18.04 use this 
https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer

Usually, plugins do not require much configuration, but if it does, there is a help button on the plugin. if the help is not clear enough feel free to open an issue, we will be happy to help you and improve the documentation.

**Comment by Fuquan999** [comment]
Der Daniel,

Thanks for your feedback and I do understand that if you are the sole person handling everything it can be over-weighted thus moving forward one hopes you can draft in some help.

However, back to the issue at hand which may still relate to you probably having too much on your hands to properly read questions asked and answer questions asked as that is what makes documentation vital.  For instance in each email sent to you we vividly explained the problem being encountered and even where there was discrepancies in the available documentation/information (such as videos leading to confusion) each time you kept answering your own questions and not what we asked.

For instance again you send "Installation" of YouPHPTube info when we have informed you (and even cut and pasted images) that YouPHPTube is already installed as that is not the issue, but it is when setting up the video upload thing  (encoder stuff) and on the second occasion you told us that the video we referred for guidance was an old video as such out of date but again you did not supply a solution leaving us hanging. (only to seeize it as a window of "opportunity" to come back later with an email asking us to pay 50 bucks for remote help when we had just spent a few hundreds on plugins)

If you go back to the email my colleague  sent you labelled (image 1.jpg) you will actually visually see the problem. Since you created the application it should be familiar at which point that problem shows and also as to how to resolve it because in the past (as I have performed that encoder setup part roughly a year plus ago and it never had this problem when we tested the "Free YouPHPTube" version before this AVideo thing and its related plugins). If you look carefully at the image we sent [since you created the app] you should be able to immediately see if the set up  on the AVideo section is any different from what your video instructions shows and if so point out what needs to be corrected to permit the setup work (it is not a folder problem as that has write permissions and we even tried with Full rights (777) to to be double sure.

Since the video for setting this part up is "outdated" as you mentioned then you should have sent us the proper step-by-step written info to guide us. As then we can test timely as the only difference between how we did it last year (the last time we did it) is that we did not have the various AVideo plugins that we have just purchased and installed now then and it worked but now it just hangs as you see in the image.  

Also we asked for proper confirmation on the setup because your instructions has both Nginx and Apache on the same server in your instructions so we wanted to confirm that this is right before we spend time finding out the hard way as your instructions  makes no mention of separate ports etc. 

But anyway, kindly go back and take a look at the image we sent you (as it should be clear to you at which point that issue is happening as you developed the app) and provide an explanation as to what needs to be done to rectify it. We use a standalone bare-metal server for individual apps and this is no different so hardware is not the issue here either.

Once you go back and take a look at the images we sent you then do let us know in a timely manner so that we can get this issue behind us and move on to other things of importance.

Thanks
Fuquan

**Comment by DanielnetoDotCom** [comment]
Please all the support requests MUST be made on GitHub NOT email.

Open one issue for each problem. and all the issues support request MUST also include details of the server host (Like Ubuntu version, PHP version, etc), screenshots and log files, this will help us find the problem.

**Comment by Criptos** [comment]
@Fuquan999 let us help, at the end each user has their own issues, and software is as is. I believe you can also purchase hours from daniel or other devs if you want. 

To be hones, even with all the purchaes, avideo is a really affordable solution compared to others... I know is not a justifiacion, but help us to help you, adding your issues here :)

**Comment by GodgivenButhelezi** [comment]
> 
> 
> @Fuquan999 
Opening an issue here also Helped me a lot and saved me a lot of Headache I finally managed to install  everything perfect including encorder, ssl certificates, nginx& rtmp and my live stream is working fine. After opening and issue , I then recieved help check it out here https://live.meetmycraft.com/ I also bought some plugins like you maybe about four plugins and I'm happy
