### ISSUE TITLE
git pull fail

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#3070]
I ran "git pull" under /var/www/html/AVideo
Next messages displayed . git pull failed.
What do we fxi thisproblem ?
root@mysqltube-virtual-machine:/var/www/html/AVideo# git pull
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 23 (delta 18), reused 17 (delta 12), pack-reused 0
Unpacking objects: 100% (23/23), done.
From https://github.com/WWBN/AVideo
   2e45f816..d655f8ca  master     -> origin/master
Updating 2e45f816..d655f8ca
error: Your local changes to the following files would be overwritten by merge:
        plugin/Live/on_publish.php
Please commit your changes or stash them before you merge.
Aborting

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

`sudo git fetch --all && sudo git reset --hard origin/master`

Executing this command will over-write what ever change you have made into `plugin/Live/on_publish.php`

**Comment by hnagasawa** [comment]
sudo git fetch --all && sudo git reset --hard origin/master
Fetching origin
HEAD is now at d655f8ca

Is it OK ?

**Comment by akhilleusuggo** [comment]
yes , run `sudo git pull ` and you will see ''you're up to date"

**Comment by hnagasawa** [comment]
Thak you for your support
