### ISSUE TITLE
Chromecast plugin enabled so... where is it?

### ISSUE THREAD

**Issue by jfcolom** [WWBN/AVideo#3071]
Chromecast plugin is enabled, so I was expecting to see a button somewhere in the video player. Where is it?

The question has already been submitted in #1750 as a bug, and it provides screenshots.  The issue was closed by stating that it is not a bug, but the question remains unanswered.

**Comment by ronaldod** [comment]
Hi, I only have this button active if there is a cast object detected in Chrome. If it is off it will if it is not have the chrome cast device detected.
In MS Edge you need to enable it first : 
type in the URL bar : `edge://flags`
It opens a page that says : "Experiments"
paste in the search pane : `#load-media-router-component-extension`
It will give you something like : 
![image](https://user-images.githubusercontent.com/31585599/82086301-9a1a0200-96ee-11ea-97b7-35ae4b3227c1.png)
Change default to enabled. It will prompt to restart to activated the changes. 
Restart the browser and go to the three dots in right side top. and go to the following menu:
![image](https://user-images.githubusercontent.com/31585599/82086605-098ff180-96ef-11ea-9347-48fbd24c3ac2.png)
Search for your chrome cast and from that moment it is active after on the page.
![image](https://user-images.githubusercontent.com/31585599/82086702-32b08200-96ef-11ea-9b4b-5a51d83e8acc.png)
For firefox is as far i know no support for ChromeCast.

**Comment by jfcolom** [comment]
Thanks for your answer
I have just pulled the last version. In Chrome browser (81.0), the chromecast button is shown in youtube.com site. Unfortunately, it does not appear in AVideo platform.

**Comment by ronaldod** [comment]
Then try the next steps to determine if everything is correctly loaded.
- Look for lines with : `silvermine-videojs-chromecast.js` in the page.
- Check with the console (f12) for errors if everything is loaded.

If yes 
- Ask a 3th party to test your site  outside of your home network to be sure it is not a local pc/network or also other people have this problem.

**Comment by jfcolom** [comment]
Thanks for your answer

- The script ``silvermine-videojs-chromecast.js`` appears linked from the page's source code
- I see the following warnings in the js console, but I think they are not related to the plugin
```
video.min.js:12 VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead
(anonymous) @ video.min.js:12

DevTools failed to load SourceMap: Could not load content for http://gontube.com/AVideo/videos/cache/js/bootstrap-select.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
- Same problem with different clients inside my network. The chromecast device is shown in youtube.com videos. Unfortunately, I cannot test it from outside my network.
