### ISSUE TITLE
Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3072]
How can I fix this ?
![image](https://user-images.githubusercontent.com/52116577/82080697-b8333280-96ed-11ea-8eee-be5aa1286e54.png)

I'm not getting the status on streamer.com/videos , in the meanwhile , encoder.streamer.com/status does appear .

**Comment by DanielnetoDotCom** [comment]
Not sure, is it happening on the demo site?

**Comment by akhilleusuggo** [comment]
No idea because I'll need to add a video to encode . Demo site does not allow that .
This is only when needs to show the queue encoder on streamer site , when checking status .

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 

So this is the problem : 

`Dev tool : `
![image](https://user-images.githubusercontent.com/52116577/82131170-f65a5000-97da-11ea-9adb-6568c03a42c8.png)

`/view/status`
![image](https://user-images.githubusercontent.com/52116577/82131178-06722f80-97db-11ea-9aa4-64b208762157.png)

`.htaccess `
![image](https://user-images.githubusercontent.com/52116577/82131196-2f92c000-97db-11ea-9d58-8df821235538.png)

As the dev tool stated , only 1 Access-Control-Allow-Origin header "*" should be present .

**Comment by DanielnetoDotCom** [comment]
We had this problem in the past, I guess if you remove one of those you will start to have problems with the mobile app

**Comment by DanielnetoDotCom** [comment]
but from what page those errors raised?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom from the page My videos at /myvideos . When you encoding some videos , the progress encoding are not displayed . Can't pull information from the encoder status

**Comment by akhilleusuggo** [comment]
Commented the line `//header('Access-Control-Allow-Origin: *');` on `/view/status.php` fixed my problem .
