### ISSUE TITLE
disabling the standard google analytics

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#3074]
**Describe the question**
I see there is a standard analytics code.
How to disable it without modifying the code.

**Comment by DanielnetoDotCom** [comment]
Here 

![image](https://user-images.githubusercontent.com/18009293/82118461-feb87980-974d-11ea-91c9-b01491d1b19c.png)

**Comment by ronaldod** [comment]
Oh how can missed that option.  Could not find it in the wiki.  Thanks
