### ISSUE TITLE
API sign up

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3075]
Again does require confirmation ...
and even when confirming on the email 

![image](https://user-images.githubusercontent.com/52116577/82091457-10733000-9700-11ea-86f2-a607e4a3ab58.png)

**Comment by DanielnetoDotCom** [comment]
if this is the signup, are you sure the user does not exist already? can you please confirm is the user was created?

Maybe you suppose to use the sign in not the sign-up

**Comment by akhilleusuggo** [comment]
I meant sing in sorry
The email and user were created after confirming google API , but email not verified

**Comment by DanielnetoDotCom** [comment]
Hi, I was looking into the code, and I could not see any problem.

Is it happening even when you are not using the API? or only with the API?

did you receive the verification email?

how is it in the database, is the emailverified = 1?

**Comment by akhilleusuggo** [comment]
no , emailVerified=0

**Comment by DanielnetoDotCom** [comment]
so the email is not verified. the message is correct.

maybe something on the link on some error in the verification process.

**Comment by akhilleusuggo** [comment]
Daniel , please read what I've said . The users that sigh-in **_WITH_** Google API / Facebook API / Twitter API **_SHOULD_** automatically be verified .

**Comment by DanielnetoDotCom** [comment]
Agree

but let me ask you something,
the users you are facing this problem are from old users (before the update)?

or for new users?

Anyway, I am sending an update to make sure even old users that sign in using the social networks, they will be automatically emailVerified

**Comment by akhilleusuggo** [comment]
New users only , old users can log , since they do have already verified

**Comment by DanielnetoDotCom** [comment]
I just review the code and I really cannot see a reason for that happen.

there is something in your log file (for any clue) when a new user signs up from a social network?
