### ISSUE TITLE
deleting user

### ISSUE THREAD

**Issue by kalamake** [WWBN/AVideo#3078]
It seems there is no way to delete user at ui, only with sql command?
RIght?

**Comment by ronaldod** [comment]
Cleaning up a user with SQL should be done with caution as many objects are connected to the user_id.
Like video data, category ownership,

**Comment by akhilleusuggo** [comment]
But for tests porpuses this option should be added .
Giving one example . I've having issues with google API sign in . Is not making users automatically verified . I need to create everytime a new google account just to test if has been fixed or not ? 
@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Right now, delete a user from the table may rise a foreign key error
