### ISSUE TITLE
LTS branching

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#3079]
**Is your feature request related to a problem? Please describe.**
At the moment bug fixes and new features are released in one master. For stability this can give issues as to short time to test the new features what can give stability problems. And for sites who are running it professionally this can give issues when upgrading and getting downtime.

**Describe the solution you'd like**
A  branch (LTS - Long Time Service) for the stable release. Only hot fixes are applied.

A  branch (DEV) for the dev release with all the hot features and the hot fixes. 
And this one is pushed to the LTS branch every x amount of time. And as many want to use this will report the bugs of the new features.

**Describe alternatives you've considered**
A full blown GIT Flow plan but that is to much for this project. As this has a Release/DEV/feature/hotfix branch. And needs a good housekeeping on it else you will swamp in branches.

**Additional context**
This is just an idea to lower the load on problems that can arise when updating. Site owner who like to live on the edge go for the dev branch and the ones who want to keep the site safe and stable go for the LTS branch.

The release numbers in the dev branch should also be marked like DEV so when users are reporting bugs it is know what branch they used for the installation.

hot fixes - These are bug or security fixes. No cleanups or new features. Just things to keep the site stable and safe.

**Comment by akhilleusuggo** [comment]
Great idea , like linux distros 
I've done that on my home server for test purposes

**Comment by Criptos** [comment]
Yeah... I need to do a terrible effor to migrate from 3.x to current...

**Comment by ronaldod** [comment]
I think we really are going to need this. As we need to offer new users a working environment without the issues the new "features" are bringing. And pushing those to the LTS branch after a week of testing.

**Comment by DanielnetoDotCom** [comment]
I agree this is very important. right now what I have are the releases. I try to mark them before a major update

https://github.com/WWBN/AVideo/releases

**Comment by ronaldod** [comment]
Then the instructions should be updated to use a zip release for a "stable" release and that a git pull is a development release.

**Comment by ronaldod** [comment]
What about the next option. 
Master is the dev release. And there is a 8.8 or 8.9 branch that is stable. And just gets the fixes.
And all the instructions on the sites are pointing to that 8.9 branch and if people want to go for the unstable release they go for that master.

For stable :
like `git clone -b 8.9 --single-branch https://github.com/WWBN/AVideo.git`

And for dev the old instruction.

On this way the old systems stays working.

**Comment by ronaldod** [comment]
> 
> 
> I agree this is very important. right now what I have are the releases. I try to mark them before a major update
> 
> https://github.com/WWBN/AVideo/releases

And also patch those release with fixes. Not only patch the new but also patch mistakes that are not from the update itself.
