### ISSUE TITLE
Clear Home Page Cache

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3081]
When a livestream starts , after 10-15s clear the cache of the home-page to show up intermediately .

**Comment by DanielnetoDotCom** [comment]
Not sure what the relationship with the cache and the live stream.

I searched in the code and I did not find anything.

**Comment by akhilleusuggo** [comment]
The problem is , if I have the cache time set to 3600 , any livestream that starts , will display on the home page once the cache expires , after 3600s = 1h . That means maybe the livestream is already over .

**Comment by DanielnetoDotCom** [comment]
but the menu bell alert does not use the cache. 

and the videos on the first page are dynamically added. so does not need to remove the cache to make it appear.

are you facing a problem like that now? maybe it is something else
