### ISSUE TITLE
Dashboard page

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#3082]
Something is wrong with the statistics. The values on the main page do not match reality.
It's about the going

Video views
Total videos likes
Total videos dislikes
Total Duration Videos (Minutes)

It occurred after the update from version 7.8 to the latest.

Of course, I cannot repeat everything on the demo page
but videominutes are also wrong on the demo page. I tried the likes, neither did these voices on the demo page.

![image](https://user-images.githubusercontent.com/52116237/82130390-403b3a00-97cb-11ea-82ed-4281dad467e6.png)
![image](https://user-images.githubusercontent.com/52116237/82130397-4e895600-97cb-11ea-9212-a8e1fb91f982.png)

**Comment by akhilleusuggo** [comment]
yes that dashboard is bad . 
Also when other users does check the dashboard , will show them stats of other users . Just disable it .

**Comment by Donnerstein** [comment]
it was useful in the old versions.
Can it be repaired or can it be from an old version.

**Comment by JoshWho** [comment]
I hope it can either be repaired or a better one to replace it with. It was a very useful tool when it was working.

**Comment by akhilleusuggo** [comment]
`$global['limitForUnlimitedVideos'] = -1;`

This fixed many issues , but still far from perfect .

**Comment by Donnerstein** [comment]
What is actually the problem
The API GET videosViewsCount element shows the same incorrect values.
Shouldn't it only have to add up all the views from the table videos

@akhilleusuggo 
$global['limitForUnlimitedVideos'] = -1;
Where did they change that?

**Comment by akhilleusuggo** [comment]
`$global['limitForUnlimitedVideos'] = -1;` on `videos/configuration.php`
