### ISSUE TITLE
Rayzorpay Payment gateway issue

### ISSUE THREAD

**Issue by sharad22gupta** [WWBN/AVideo#3083]
**Describe the bug**
i have marked the video premium, but still when i am logged out i can read the article or watch the video.

**Expected behavior**
On click, it should open payment gateway

**Screenshots**
![pay](https://user-images.githubusercontent.com/15939963/82130669-172aa180-97eb-11ea-8380-b812ff06794b.png)

I have turned on rayzorpay plugin and in razorpay webhook is connected.
@DanielnetoDotCom @akhilleusuggo

**Comment by DanielnetoDotCom** [comment]
I am confused.

you marked "premium", can you please screenshot your video manager page?

are you sure you are not logged in as admin?

BTW, your layout looks different,

**Comment by sharad22gupta** [comment]
@DanielnetoDotCom
I am signed out and that article is marked premium.
![Annotation 2020-05-22 004607](https://user-images.githubusercontent.com/15939963/82597092-0fda0e00-9bc6-11ea-8361-ddc8fb3d3a59.png)
in videos manages also it says premium
![Annotation 2020-05-22 004750](https://user-images.githubusercontent.com/15939963/82597107-15cfef00-9bc6-11ea-9389-219c3c9a05d7.png)
I am signed out but still on clicking the article i can read it.
![Annotation 2020-05-22 004845](https://user-images.githubusercontent.com/15939963/82597116-1bc5d000-9bc6-11ea-97e0-df476eaf8c62.png)

**Comment by DanielnetoDotCom** [comment]
@sharad22gupta do you have a PPV or subscription plugin?

**Comment by sharad22gupta** [comment]
@DanielnetoDotCom  No i dont have either.

**Comment by DanielnetoDotCom** [comment]
you need one of those to be able to charge something

Check this https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform#paid-content
