### ISSUE TITLE
RE: Encoder Setup issue

### ISSUE THREAD

**Issue by Fuquan999** [WWBN/AVideo#3084]
ENCODER QUESTION
===================================================
Q1: You have this document: {https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer] here

a) which seems to show the installation of the AVideo platform included.

b) Then at the bottom paragraph of the same page you say this {The Encoder We recommend that you use an AVideo Encoder privately, it is also available for free and open source and you can download it here}

Thus for Question one does this mean we need to have TWO (2) servers prepared for this? As the installation process mentioned above seems to say both are on the same server
One has to ask what is then included in the AVideo Platform that was downloaded during the installation process  above? The download link on YouPHPTube agian takes on to GitHub to download AVideo so what exactly is one setting up YouPHPTube or AVideo or what? THis needs to be seperated or made absolutely clear

Q2: Where does YouPHPTube come in on all of this? As this ends up confusing things as the PLUGINS we downloaded are on the YouPHPTube website and the original videos that we see are all on and about YouPHPTube. Some clarity is needed on this whole thing as way too many things buzzing around to make it actually clear what is what! Hopefully now you see why you need a clear set of Documentations that outline what is what.

So to the Direct problem:
=================
Take a look at the images as you can see we installed YouPHPTUbe (image 1)
Also as you can see on image 1 when we click the button to Encode video and audio we get what you see in image 2
As you can also see image 2 shows a URL that has nothing to do with our installation (encoder2.avideo.com) which I assume is a link to your server.
Now the issue is were we then supposed to install the encoder on a "second" server  (as this needs to be well documented and guided for the consumer to follow) and if not then
Assuming during the installation (see the link mentioned earlier) that BOTH were installed on teh same server then what are we supposed to do at this stage of the setup? This too needs to be clearly documented. Thus, as you can see something is wrong in the whole installation and setup process that you have outlined as it is not clear. As a little clarity with images outlining the steps involved would go a long way in preventing "misunderstanding".

Finally, you also need to make very clear the difference between YouPHPTube and this AVideo thing as I install YouPHPTube and inside the admin area I see you having tabs for AVideo which then I see one installation for YouPHPTube and then I see another document for an installation of AVIdeo Platform...it all serves to confuse rather than clarify. Tyr to keep things streamlined and consistent.

Anyone running their own physical servers already does much of the things you mention (setting up Ubuntu, Apache, PHP, MySQL, FFmpeg, Youtube-dl, NGINX and RTMP Module, Firewalls, Email tools,  IDS, Monitoring etc..)  so they are familiar with all that:, 

The challenge is the "confusion" that your lack of clear documentation that also happens to be all over the place and outdated is causing as it ends up wasting busy peoples time just tracing/tracking things related to YouPHPTube. 

Even tracking down a help desk by you is a challenge (as we have to create a GitHub issue tracker)  you are making money from this product why not simply  set yourself up a proper trouble-ticket HD system by using any Open Source application such as iTop and connect it to your website  (let GitHub be for Bugs but let trouble-tickets be for trouble-tickets as that is more suited for consumers and users). At least that way it is easier or people buying your plugins/giving donations to reach you and follow their trouble tickets progress . In a modern world gone are the days when every individual was lazy as now people want to KNOW what is going on on their servers and not merely having outside people asking for money to JUMP in and "FIX" a problem (that may not even be a problem) that only ends up handicapping them because they never even learned from their experience/problem in the first place.

Thanks Fuquan & Lusjames

![1_ClickOnUploadVideo](https://user-images.githubusercontent.com/17571557/82140631-6e069a00-9830-11ea-82eb-515be2a212a3.JPG)
![2_StreamerDetails](https://user-images.githubusercontent.com/17571557/82140633-719a2100-9830-11ea-92d1-c80dc178b1d2.JPG)
![3_StreamerLogin](https://user-images.githubusercontent.com/17571557/82140635-73fc7b00-9830-11ea-8639-1fbdce203e5c.JPG)

**Comment by ronaldod** [comment]
You can run everything on one server. For test purpose or small setup this is not a problem. Why it is referring to install it separately is that the encoder will pull a lot of resources on CPU en Memory. This can have a performance effect on your website.
 
If you do not have your own encoder up and running you can use one of the public encoders.
[encoder1](https://encoder1.avideo.com)
[encoder4](https://encoder4.avideo.com)
[encoder5](https://encoder5.avideo.com)
As they are public there can be a waiting line for encoding.

[encoder2](https://encoder2.avideo.com) Is not public anymore. This should be changed in the reference as an public one. Good point.


If you want to change to one of the public encoders set your encoder settings under :
Site Configuration then the tab : Advanced Configuration. Change there your Encoder URL.

YouPHPTube rebranding reference [wiki](https://github.com/WWBN/AVideo/wiki) First page one the wiki. Read all about the rebrand. Also the place to find all the information you need to start from.

To avoid all these problems @DanielnetoDotCom offers a complete installation with common plugins and install them correctly with support. 

Please open per question one ticket/issue and only when it is a bug report as a bug else put them under question or enhancement. This is better for the overview.
