### ISSUE TITLE
"make sure the getvideosall will always has a limit"

### ISSUE THREAD

**Issue by JSY-Ben** [WWBN/AVideo#3085]
Hi there :) Thanks as usual for the project, it is great software.

A few weeks back you made the change that pressing the 'All' button in the Video Manager to show all videos will always limit the query to a certain number of videos.

I have thousands of videos on my installation, and it was helpful to have the 'All' option to make changes to all videos at once. I know it takes a very long time to submit that long query, but i knew that, so waiting was not a problem.

I've noticed since the change that the Video stats are incorrect as well. It shows the amount of videos correctly, but all the stats are wrong. Not sure if it's related because it's doing the same query?

<img width="1644" alt="Screenshot 2020-05-17 at 12 08 21" src="https://user-images.githubusercontent.com/13555701/82142862-70b8bd80-9837-11ea-9c1b-af4097ab3eec.png">

Could i perhaps suggest that the original 'All' query is reinstated, but perhaps with a warning that it will take time? Or perhaps a query selection more than 50, like 100, 1000, 10000 or whatever :)

Thanks again!
Ben

**Comment by DanielnetoDotCom** [comment]
Hi, please add this variable in your configuration.php file

`$global['limitForUnlimitedVideos'] = -1;`

this may make your query unlimited.

I will come up with a better solution later.

**Comment by JSY-Ben** [comment]
Wonderful. Thank you very much :)

**Comment by akhilleusuggo** [comment]
This update actually fixed all the bugs the dashboard had .
