### ISSUE TITLE
paypal

### ISSUE THREAD

**Issue by EnrOn-tv** [WWBN/AVideo#3086]
To Com Problema em cria api paypal para cartao de credito

**Comment by EnrOn-tv** [comment]
essa api para cartao nao aceita no brasil StripeYPT ai preciso de faz para paga no paypal

**Comment by DanielnetoDotCom** [comment]
Ola 

Da uma olhada em seu log de erros do seu streamer que deve ter uma pista lá , o por que está falhando

**Comment by DanielnetoDotCom** [comment]
Realmente no Brasil não aceita stripe a única opção por enquanto é o PayPal

**Comment by EnrOn-tv** [comment]
Tem como voce cria um plugin para mim com pagamento PagSeguro eu pago por voces

**Comment by DanielnetoDotCom** [comment]
solicitações de desenvolvimento e quotações tem que ser feito por email. developer@youphptube.com
