### ISSUE TITLE
MENU Nothing Happens When Clicked or even Right/Left Clicked

### ISSUE THREAD

**Issue by Fuquan999** [WWBN/AVideo#3088]
Firstly I am heading to sleep now as it is late in Europe so will follow up Tomorrow.  However just to let you know that the first thing we did (which is even a natural non technical reaction) is click the menu item then right and left click NOTHING happened.

Thus, we did not get this response as that is the expected response: I have created hundreds of menus in various CMS/Game Engines so I have a rough idea what to expect: If something did happen as your documentation states I would not have pointed it out!
Thanks
Fuquan...I will follow up tomorrow and t-shoot the logs to see if there is anything in there to point in the right direction as a bit drained tonight.
----------------------------------------------------------------------
Once you have a menu created you can click over it, on the list on the left side, and you will see few more option.

Edit Menu Items
Delete Menu
----------------------------------------------------------------------
![Nothing HappensWhenClicked](https://user-images.githubusercontent.com/17571557/82160366-18b0a400-9895-11ea-98a5-4c66b7394850.JPG)

**Comment by ronaldod** [comment]
Hi,

How did you fill in ?
Mine example : 
- The menu
![image](https://user-images.githubusercontent.com/31585599/82160537-5d890a80-9896-11ea-8664-a5fe10fde30d.png)

- The settings.
![image](https://user-images.githubusercontent.com/31585599/82160582-b22c8580-9896-11ea-94ff-2f66f4992e2c.png)

- the settings of the item.
![image](https://user-images.githubusercontent.com/31585599/82160565-8dd0a900-9896-11ea-8d82-5c27b1bf8c72.png)

After every edit an F5 to refresh the browser.

**Comment by ronaldod** [comment]
Yups i see the problem. Left menu is not always working like intended. It works depending on the security settings of the page you link to. 
I have always a change on the screen. But loading is depending on where i link to. Some sites are secured.
You see the same problem if you choose standard. I would advice first to start with "standard" as the error is more visible.

**Comment by Fuquan999** [comment]
Hi Daniel,

I was going to close this ticket but before that can I ask where do I go for "Feature Requests"? As the "Comments" section could do with a little more features even if it means having it as a paid plugin. If you can let me know where I need to go to place a "Feature Request" and then I shall close this ticket as this issue has long been resolved.

Thanks
Idris

**Comment by DanielnetoDotCom** [comment]
Hi

You can request new features/plugin opening an issue here on github, this feature may be made in the future .

But if you need the feature now you can sponsor the feature emailing me for a quotation at deceloper@youphptube.com
