### ISSUE TITLE
Chat2 is not functioning correctly

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3089]
You can see it here https://www.joshwhotv.com/video/20063/desktop-1589770791356

I can't click anything and chat will not submit.

**Comment by akhilleusuggo** [comment]
You need to update the chat plugin . I think this problem was fixed 2 days ago .

**Comment by JoshWho** [comment]
root@joshwhotv:/var/www/html/YouPHPTube/plugin/Chat2# git pull
Already up to date.
root@joshwhotv:/var/www/html/YouPHPTube/plugin/Chat2#

**Comment by JoshWho** [comment]
is there another way to update it?

**Comment by akhilleusuggo** [comment]
nononono , You need to re-download it from website .
Many plugins have been updated , try to redownload them all and upload them .

The settings will be kept

**Comment by JoshWho** [comment]
Not available for download for me.

**Comment by JoshWho** [comment]
I thought the plugins light up when then need to update and it can be done in the control panel.

**Comment by DanielnetoDotCom** [comment]
@JoshWho  I just update your site. 

also if you want to be able to download the plugins from the plugin site, please email me and let me know.

**Comment by JoshWho** [comment]
ok and thank you Daniel.
