### ISSUE TITLE
Take A Closer Look Something Clearly is Wrong With VIEWS

### ISSUE THREAD

**Issue by Fuquan999** [WWBN/AVideo#3090]
Dear Daniel,

If you take a closer look at what I send you (also see below) it is clear YOU are seeing something else and I am seeing something else. Probably What I have installed is different from what you have somehow.

I have highlighted a few things that are on YOUR version but are NOT on my version. As there is something different between the two versions. My Version seems NOT to be COMPLETE. Since there is only a full or no installation of the app I am wondering why my version is like a  "half face plastic surgery" and yours is a "Full Face" plastic surgery.

I do not have some of the TABS and BUTTONS I am seeing in your examples I am logged in as Admin so rights is not the problem I am sure it is the same issue that is causing ALL the other teething problems I am experiencing such as windows (chat) NOT closing when you click the "X" button nor windows collapsing etc. The version I have is seems different from what you show in your examples somehow. I have checked the browser settings and allowed all that was possible on all browsers yet the issue is the same.

To be honest this is the sort of thing you see in a CMS when there are  poorly written plugins causing plugin conflicts.

But since you are the creator of the application you should know your app better.

THIS IS WHAT YOU SEE:
====================
![YOUR VIEW](https://user-images.githubusercontent.com/17571557/82191271-8fc85580-98f2-11ea-9b89-c030fb0d7a26.JPG)

THIS IS WHAT I SEE:
---------------------------
![MyVIEW](https://user-images.githubusercontent.com/17571557/82191323-a40c5280-98f2-11ea-90bd-2b0f75e45c4d.JPG)

**Comment by ronaldod** [comment]
![image](https://user-images.githubusercontent.com/31585599/82205786-6665f480-9907-11ea-85cc-5da95e4f9ed8.png)
First pres on the red item and then on the green.

**Comment by ronaldod** [comment]
And you opened a second topic for the same problem. Please follow common guide lines.
The version i show from is allways a very recent build vanilla. If you view is different then your i advice to update your installation or have it installed by @DanielnetoDotCom for a small fee. The last option will save you a lot of frustration and time.

**Comment by Fuquan999** [comment]
Thanks for that as That is the missing piece of information. The below wiki part probably needs to be changed/reworded on the wiki so that the reader takes another action instead of ends up wasting valuable time pondering why things are not working:
-----------------------
i.e: (Example)
To Create a Menu follow these steps:
----------------------------------------------
1) From the left hand side menu select "Plugins"
2) Scroll till you see the "TopMenu" plugin then activate it
3) To the far right click on "Create Menu"
4) Fill in the details for your menu then click "Save Menu"
5) Next on the right side move your mouse and click on the name of your menu
6) Make the necessary changes to the Menu Items tab as required.
Etc. Etc. Etc.

I recognize that English may not be your first language but documentation when structured properly it provides clarity and saves a ton of trouble shooting time both for you and the customer as this really should not have even been a ticket if the documentation had been outlined properly.
===========================================
---------------------
Once you have a menu created you can click over it, on the list on the left side, and you will see few more option.

Edit Menu Items
Delete Menu
=======================

**Comment by DanielnetoDotCom** [comment]
@Fuquan999 I appreciate your help, and definitely I will use your reword suggestion.
