### ISSUE TITLE
Can't edit users

### ISSUE THREAD

**Issue by PrXenon** [WWBN/AVideo#3091]
unable to edit user profiles as admin.
![helper](https://user-images.githubusercontent.com/3627520/82213202-0fb2e780-9914-11ea-976c-91bcfe06031d.jpg)

edit and info will do nothing...

**Comment by ronaldod** [comment]
Please provide with screenshot, logging like mentioned in the template .[link to bug template]( https://github.com/WWBN/AVideo/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

This will help us better in supporting your issue.

**Comment by DanielnetoDotCom** [comment]
@PrXenon if nothing happens I am pretty sure you can find some clue on the JS Console window.

**Comment by PrXenon** [comment]
Unfortunately there is no hint in the JS console.
![helper2](https://user-images.githubusercontent.com/3627520/82218771-abe0ec80-991c-11ea-9e48-e7e9c9b7b00b.jpg)

**Comment by TLCReuver** [comment]
Same problem here without error. I restored backup from friday (15-05-2020)

**Comment by DanielnetoDotCom** [comment]
Sorry, fix sent

**Comment by PrXenon** [comment]
Thanks!
Fix confirmed... i can edit users again :-)
