### ISSUE TITLE
version check should show (payed) plugin updates

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#3092]
**Is your feature request related to a problem? Please describe.**
At the moment buyers of plugin do not know if there is an update for them available.

**Describe the solution you'd like**
That next to a version update (i would still like a LTS branch) it also shows if there updates for the plugins. And also if a plugin update requires also update of the Avideo framework.

**Describe alternatives you've considered**
Mail systems mean a lot of work. Pulling it from the admin panel is simpel.

**Additional context**
That means like:
LTS number is 8.7.1
8 - major release
7 - feature release
1 - bug fix release.

DEV release the same but those can go like 8.7.293 because of the many updates.

**Comment by ronaldod** [comment]
And of course every edit on the plugins also force a increase in version numbers.

**Comment by DanielnetoDotCom** [comment]
I agree, thanks

**Comment by ronaldod** [comment]
Maybe if you are going to implement this also put a check in that if a payed plugin is downloaded it requires a minimal version of the framework if needed. To prevent problems in expectation.
