### ISSUE TITLE
adsense

### ISSUE THREAD

**Issue by EnrOn-tv** [WWBN/AVideo#3093]
oi bom dia gostaria de saber onde coloco os link do adsense 
no youphptube para q a google adsense aprova o site

**Comment by ronaldod** [comment]
Please post in English. Thank you.

**Comment by DanielnetoDotCom** [comment]
Use aqui

![image](https://user-images.githubusercontent.com/18009293/82218750-bc7c6d00-98f2-11ea-8afe-b7b974cbaba9.png)


Se precisar de agdo no head use aqui

![image](https://user-images.githubusercontent.com/18009293/82218833-dddd5900-98f2-11ea-9c58-bab860520c9b.png)
