### ISSUE TITLE
Top menu: links to other websites need to loads in a new tab

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#3096]
**Is your feature request related to a problem? Please describe.**
At the moment if you add a link pointing to an other site is opens itself in the same tab. To avoid to send all your traffic to other sites it would be better to open the new site in a new page. In this way the visitor will stay on both sites. And some new sites are note allowing to be opened on the _self and only with _blank.

**Describe the solution you'd like**
I would like to add a target attribute _blank or _self. 

**Describe alternatives you've considered**
Nothing found yet

**Additional context**
If using the _blank attribute also the `rel=”noopener noreferrer"` must be set.

**Comment by Criptos** [comment]
You can offer bounty for this change...

**Comment by DanielnetoDotCom** [comment]
Right now, the script will auto-detect if the URL is for the same domain or an external domain.

if it is an external domain it will open in a new tab with the `rel="noopener noreferrer"`

**Comment by ronaldod** [comment]
Smart fix
