### ISSUE TITLE
Permanent Link

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#3097]
The URL (Seo) link contains the Video ID. I think that is not sensible and not so wanted.

![image](https://user-images.githubusercontent.com/52116237/82273591-2130d980-997e-11ea-864d-50fcc5959d79.png)

**Comment by akhilleusuggo** [comment]
Agree , but changing that now , will break all the search engine queries . All the clicks will be sent to 404 error page . Changing the links it's a thing that should be done at the start . 

But I have to say , that we need some code of redirect when users changes titles of videos , and the seo link changes as well . Redirect old SEO links to the new SEO links .

**Comment by Criptos** [comment]
The issue with historical is that it allow collisions... Is better not to change the title. My experience is less than 1% of videos change title after the first day... so for me is safe to use pretty links istead of permanent links

**Comment by DanielnetoDotCom** [comment]
I guess we can remove the ID as an option with the customizeAdvanced->useVideoIDOnSEOLinks

In the past, we did not use IDs on the links, but we start having problems when someone decide to change the video title. also with the notification right after the video encoding process.

**Comment by Donnerstein** [comment]
I understand

thank you for the change.
