### ISSUE TITLE
Can we do Premieres 

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#3098]
Just asking a general question.

I noticed that YouTube and Facebook allow you to schedule pre-record videos for a certain date, and this feature is pretty cool.

Can that be done on our platforms or is there a plugin that we have to purchase?

**Comment by ronaldod** [comment]
How do you see the premiere function ?

**Comment by CROSSMediaNet** [comment]
> How do you see the premiere function ?
> What are the requirements ?

Here are some articles that I found on YouTube and Facebook:
YouTube: https://support.google.com/youtube/answer/9080341?hl=en
Facebook (it says Facebook for Business, but it is the same for personal): https://www.facebook.com/business/help/580544922399103?id=214359809769375

**Comment by DanielnetoDotCom** [comment]
Right now we do not have this feature.
