### ISSUE TITLE
User login restriction

### ISSUE THREAD

**Issue by WGtechy** [WWBN/AVideo#3102]
Greetings, can user restriction be integrated into this application in such a way that a user can not login to his account with multiple device at the same time; if user tries to login with another device, user will be denied access.

Integrating this will help control users that are trying to send their login details to other users so that they will be able to have access to a scheduled premium content at the same time, especially when it is live stream.

What do you think about this?

**Comment by DanielnetoDotCom** [comment]
Hi

I understand, right now we do not have this option.

**Comment by WGtechy** [comment]
> Hi
> 
> I understand, right now we do not have this option.

Yes i notice, its a suggestion i think can add to the user restriction.

**Comment by WGtechy** [comment]
> Hi
> 
> I understand, right now we do not have this option.

Hello Dan, 
I raised an issue on my encoder few days ago and i sent you a direct mail but no reply from you yet
here is the issue https://github.com/WWBN/AVideo/issues/3060#issue-617506873

Please check it. 
Thank you

**Comment by DanielnetoDotCom** [comment]
Hi @WGtechy  I checked your issue and you got so many answers on that issue.

but what I can see the issue is a server configuration issue, NOT a software bug. you can try to find support here, but you also may Google for a solution

**Comment by WGtechy** [comment]
> Hi @WGtechy I checked your issue and you got so many answers on that issue.
> 
> but what I can see the issue is a server configuration issue, NOT a software bug. you can try to find support here, but you also may Google for a solution

oh okay!
i will configure the encoder on another server and give feedback 
But what could be wrong with the server ?
Thank you

**Comment by WGtechy** [comment]
> Hi @WGtechy I checked your issue and you got so many answers on that issue.
> 
> but what I can see the issue is a server configuration issue, NOT a software bug. you can try to find support here, but you also may Google for a solution

Greetings Daniel, i installed the Encoder on another ubuntu 18+ server but its processing nonstop. Please what can i do since there are no logs in the server?

**Comment by ronaldod** [comment]
Processing means in most of the time it can not contact the video server.
Try from the encoder with curl to see if you can reach the video server on that adres you typed in. And if the other server is using https:// use that as it can not follow a redirect at the moment.

**Comment by ganddser** [comment]
> 
> 
> Greetings, can user restriction be integrated into this application in such a way that a user can not login to his account with multiple device at the same time; if user tries to login with another device, user will be denied access.
> 
> Integrating this will help control users that are trying to send their login details to other users so that they will be able to have access to a scheduled premium content at the same time, especially when it is live stream.
> 
> What do you think about this?

Hey @DanielnetoDotCom any movement on this suggestion? This kind of restriction is absolutely necessary for premium content (pay per view/subscriptions).

**Comment by DanielnetoDotCom** [comment]
For now nothing yet, maybe I will find a sponsor to it and will be implemented soon;
