### ISSUE TITLE
Help with Live Stream Setup

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#3103]
Hi,

I can't seem to get Live Streaming to work.
I followed this setup from https://www.linuxbabe.com/ubuntu/install-youphptube-ubuntu-18-04-server using an Apache setup, do I need to have NginX installed to be able to live stream?
I can't seem to find instructions on how exactly set this up.

Thank you for any help...

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

**Comment by D-Spayre** [comment]
Thanks,

I got to this part.

9. in case you use a HTTPS connnection you may need to Enable secure WebSocket
sudo nano /etc/apache2/mods-available/proxy.conf

Change the plugin variables to {"websocket":"wss://[yourServer]/wss/"}

I'm not sure where to place this.

My stats work on http but not https.

Thank you

**Comment by akhilleusuggo** [comment]
You need to add your SSL `fullchain.pem` and `privkey.pem` location into the config file
Giving you one example : 

`sudo nano /usr/local/nginx/conf/nginx.conf`

```
http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;                                                                                                                                                                                                   
                    listen 444 ssl;
                    ssl_certificate /etc/letsencrypt/live/yoursitename/fullchain.pem;                                                                                                                                    
                    ssl_certificate_key /etc/letsencrypt/live/yoursitename/privkey.pem;
                    server_name yoursitename.com;                                                                                                                                                                            
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';
```

About the `{"websocket":"wss://[yourServer]/wss/"}` this is for the chat only . Mine looks like this : 

```
<IfModule mod_proxy.c>
        ProxyPass /wss/ ws://127.0.0.1:8888/
</IfModule>
```

**Comment by D-Spayre** [comment]
Thanks for the reply.  But still having issues. :(
On my router I have 80, 443, 444, 1935 & 8080 forwarded to my server.  
Does 1935 need to be forwarded?

https://www.MY-DOMAIN.ca:444/live/    -    403 Forbidden - / or no / doesn't matter
https://www.MY-DOMAIN.ca:444/stat     -    I can see the stats page as long as there's no trailing /
Should the "Live Plugin Form" be 444 or 8080?

Should the Server URL have a port attached?

Live URL: works fine
Player URL:     -     404 Not Found with port 8080 and 444

I can't access the "/etc/letsencrypt/live" folder permission denied.  So I think I have my domain set correctly but not 100%.
Attached are some screenshots and my nginx.conf.

Thank you,

[nginx.log](https://github.com/WWBN/AVideo/files/4659867/nginx.log)
![Plugin Form](https://user-images.githubusercontent.com/65576427/82508167-a03b2480-9ada-11ea-8776-1d53b16d99b2.png)
![Share Info](https://user-images.githubusercontent.com/65576427/82508170-a03b2480-9ada-11ea-9908-ca731e2a43a0.png)

**Comment by DanielnetoDotCom** [comment]
I guess if you are using the https you should change the ports to 444 on your live plugin parameter configuration

**Comment by D-Spayre** [comment]
Yep I did that now the Player and Stats use 444. Which seem to work fine.
When I try to send stream from OBS even on local IP I get "Failed to connect to any servers".
Testing locally with rtmp://192.168.0.6/live?p=NUMBER   and   Stream Key: NUMBER

Thanks

**Comment by akhilleusuggo** [comment]
your player URL and LiveURL are under SSL , but using port 8080 , should be using port 444

**Comment by D-Spayre** [comment]
Correct I have them on 444 now. But still having the same issue as my recent post. :(

I'm missing something but just can't figure it out.

**Comment by akhilleusuggo** [comment]
without more details it's hard to know
Are you using google cloud ? What about the ports ?

**Comment by D-Spayre** [comment]
No Google Cloud and all ports are forwarded.
I disabled the firewall.

Does the nginx.conf look correct from the above post? 

Thanks

**Comment by D-Spayre** [comment]
I noticed the live link is https://www.MY-DOMAIN.ca:444/live/5ec63189175b1/index.m3u8 but under /var/www/YouPHPTube/ the "Live" folder isn't there.

**Comment by D-Spayre** [comment]
Also should these be https if I'm using SSL?
on_publish http://www.MY-DOMAIN.ca/plugin/Live/on_publish.php;
on_play http://www.MY-DOMAIN.ca/plugin/Live/on_play.php;
on_record_done http://www.MY-DOMAIN.ca/plugin/Live/on_record_done.php;

**Comment by akhilleusuggo** [comment]
the push is on `/HLS/live`

Past here your config file . Also plugin .

**Comment by D-Spayre** [comment]
I noticed I don't have HLS folder or one is not being created.

 worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://www.MY-DOMAIN.ca/plugin/Live/on_publish.php;
                            on_play http://www.MY-DOMAIN.ca/plugin/Live/on_play.php;
                            on_record_done http://www.MY-DOMAIN.ca/plugin/Live/on_record_done.php;
                    }
            }
    }
     http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    listen 444 ssl;
                    ssl_certificate /etc/letsencrypt/live/www.MY-DOMAIN.ca/fullchain.pem;
                    ssl_certificate_key /etc/letsencrypt/live/www.MY-DOMAIN.ca/privkey.pem;
                    server_name www.MY-DOMAIN.ca;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }
            }
    }


Live Plugin
rtmp://www.MY-DOMAIN.ca/live
https://www.MY-DOMAIN.ca:444/live
https://www.MY-DOMAIN.ca:444/stat

**Comment by akhilleusuggo** [comment]
I recommend you to take a look once again the guide . You have skipped some steps : 
https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

`sudo mkdir /HLS && sudo mkdir /HLS/live` Maybe this one , one of them .

**Comment by D-Spayre** [comment]
Sorry I have the HLS folder located at the root of the drive, it's owned by root:root is that correct?
also /etc/letsencrypt/live is owned by root:root and I can't access it.  Permission denied.
So I'm not 100% sure if this is correct.
ssl_certificate /etc/letsencrypt/live/www.MY-DOMAIN.ca/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/www.MY-DOMAIN.ca/privkey.pem;
Also in nginx.conf where it says "server_name" should that be www.MY-DOMAIN.ca?

Thank you

**Comment by D-Spayre** [comment]
The ssl_certificate are correct.
ssl_certificate /etc/letsencrypt/live/www.MY-DOMAIN.ca/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/www.MY-DOMAIN.ca/privkey.pem;

**Comment by D-Spayre** [comment]
Ok I can't access any of these internally:
on_publish http://INTERNAL-IP/plugin/Live/on_publish.php;
on_play http://INTERNAL-IP/plugin/Live/on_play.php;
on_record_done http://INTERNAL-IP/plugin/Live/on_record_done.php;
I get Not Found
The requested URL was not found on this server.
Apache/2.4.29 (Ubuntu) Server at 192.168.0.6 Port 80

**Comment by D-Spayre** [comment]
Got live streaming to work, SSL issue.

Thanks for the help :)
