### ISSUE TITLE
How to access the playlists ?

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#3106]
**Describe the question**
Where can i access the "program" or the "playlist" link in the menu ? As i can not find the playlist setting except when editing mine own video's

**Screenshots**
I would expect that there would be a link.
![image](https://user-images.githubusercontent.com/31585599/82480378-fd7fa780-9ad3-11ea-94b9-1563d8d8f9f8.png)

**Comment by DanielnetoDotCom** [comment]
The playlists are on your channel.

what do you mean to access your playlists? a direct link to the channel/playlist tab?

**Comment by ronaldod** [comment]
I would expect self made playlists on the left menu.  Something like youtube has. If you mark something for watch later you should have easy access to that list.

**Comment by DanielnetoDotCom** [comment]
Can you please screenshot so I can have a better idea?

**Comment by ronaldod** [comment]
![image](https://user-images.githubusercontent.com/31585599/82694325-5df11f00-9c63-11ea-87b9-54c2cb2b6bdc.png)

Like the watch later should be prominent/TOP . And the rest of you playlist hidden under  show more. When you click that it will show all your play lists.

**Comment by ronaldod** [comment]
I would place it somewhere betweenc  channels and categories. OR maybe better just a stripe under Audio's 
An just place Watch later and then the show more. It is more an UX  (User experience thing).

**Comment by DanielnetoDotCom** [comment]
What about this now?

**Comment by akhilleusuggo** [comment]
Can you change the placement ? 
In my case is located under the menus ( left ) . Same happens to Channels . They should have the Order=0 or an option to customize it .

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo can you please screenshot so I can understand better?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 
![image](https://user-images.githubusercontent.com/52116577/82918480-7754dc80-9f7d-11ea-954f-b917cf32ee16.png)

**Comment by ronaldod** [comment]
What would be nicer. Like now and also on the menu right.
Or also add it inunder my My channel in or so in:

![image](https://user-images.githubusercontent.com/31585599/82921927-41155e00-9f79-11ea-93cd-43afdde83b4d.png)

It is good to split it and as it is only visible when a user logged in it could be nice to have "the watch later" button in the colored group. And the rest in the white menu.

**Comment by akhilleusuggo** [comment]
+

**Comment by ronaldod** [comment]
I like the implementation. To have one last option is to have place a remove button  on the list like:

![image](https://user-images.githubusercontent.com/31585599/82925684-593bac00-9f7e-11ea-9e6a-fb80f9c4098e.png)

This will make it more easy to maintain the list then to go to every video to remove it.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Now does appear inside the menu of other element .
![image](https://user-images.githubusercontent.com/52116577/82927942-197ac180-9f8a-11ea-9566-922b2bbe61fb.png)

**Comment by DanielnetoDotCom** [comment]
Buttons location updated.

Question @ronaldod : will this remove the video from the playlist or from favorite/watch-later?

**Comment by ronaldod** [comment]
Yes like the location not sure yet on the color schema but that is for later.
@DanielnetoDotCom : yes it just removes the video from the playlist.
