### ISSUE TITLE
AD_Server: Need Help with Setting Up Campaign 

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#3107]
Trying to activate a video campaign.  I followed the directions:

<img width="734" alt="AD Campaign Set Up" src="https://user-images.githubusercontent.com/739391/82487225-196f5300-9aac-11ea-8eae-5929ae572160.png">
However, it's not working.

I looked at the XML file and saw [ERRORCODE]

<img width="312" alt="Screen Shot 2020-05-20 at 2 59 51 PM" src="https://user-images.githubusercontent.com/739391/82487895-03ae5d80-9aad-11ea-94b2-cbee71b0e4b2.png">

I activated the AD_Sever and AD_Server_Location to see if that was the issue.  When they were turned on the videos would not play. 
<img width="625" alt="Screen Shot 2020-05-20 at 3 04 22 PM" src="https://user-images.githubusercontent.com/739391/82487506-6eab6480-9aac-11ea-9d82-80f9df02e633.png">

once the ad_server was turned off the videos would play with no issue.  So, I not sure what I am missing to get the ad campaigns to play.

the VMAP, Link it isn't clear to me what I should do with the link.

Hopefully you can help

**Comment by DanielnetoDotCom** [comment]
Hi

did you add videos on this campaign? are the videos MP4?

can you please show how your VMAP file looks like?

also how the VAST link looks like?

**Comment by willpower68** [comment]
Hello Daniel,

Thank you for responding.  I will do my best to answer your questions.

1.  Did you add video on this campaign?

I did add videos to the campaign by typing title in video field

<img width="795" alt="Screen Shot 2020-05-20 at 11 18 37 PM" src="https://user-images.githubusercontent.com/739391/82521271-329bf200-9af4-11ea-931d-e4638f967947.png">

I'm not sure where to upload video that should appear as Ad on videos listed. This I am sure is contributing to the issue.

2. Here is the VMAP Link:

<img width="745" alt="Screen Shot 2020-05-20 at 11 20 01 PM" src="https://user-images.githubusercontent.com/739391/82521449-b6ee7500-9af4-11ea-8d7c-eb99b626d9c1.png">

3.  what does the VAST Link look like?
https://vizo.tv/plugin/AD_Server/VAST.php?campaign_id=2

Did you need more than link itself?

**Comment by GodgivenButhelezi** [comment]
Did you install the database tables. I had a similar problem and went to install the database tables and now I'm Sorted. Check for yourself https://live.meetmycraft.com

**Comment by willpower68** [comment]
@GodgivenButhelezi  yes sir, I did.  It looks and works very well for you.  I'm sure it will get resolved.  My guess is the user (me) is causing the problem.  thank you very much for contributing.

**Comment by DanielnetoDotCom** [comment]
what type of videos are you adding on the Ads? It works only with MP4.

does not work with embed or HLS

**Comment by willpower68** [comment]
Question:
Are the video's listed below meant to be ADs?  Or are the video listed where the ADs will pre-roll? It wasn't clear to me after reading the instructions.

<img width="795" alt="Screen Shot 2020-05-21 at 11 12 35 PM" src="https://user-images.githubusercontent.com/739391/82627562-a7d0fb00-9bb8-11ea-98cc-030ee318aa71.png">

I did not see a place to upload .mp4 videos and added the above by selecting from drop down after typing title of video.

I understand the video ad can't be embeds or HLS.  What I don't understand is where do I upload the .mp4 video AD.

Thanks

**Comment by GodgivenButhelezi** [comment]
> Question:
> Are the video's listed below meant to be ADs? Or are the video listed where the ADs will pre-roll? It wasn't clear to me after reading the instructions.
> 
> <img alt="Screen Shot 2020-05-21 at 11 12 35 PM" width="795" src="https://user-images.githubusercontent.com/739391/82627562-a7d0fb00-9bb8-11ea-98cc-030ee318aa71.png">
> 
> I did not see a place to upload .mp4 videos and added the above by selecting from drop down after typing title of video.
> 
> I understand the video ad can't be embeds or HLS. What I don't understand is where do I upload the .mp4 video AD.
> 
> Thanks

Should be mp4 videos uploaded to your streamer site not from external source.

**Comment by willpower68** [comment]
they are video uploaded from streamer.

**Comment by DanielnetoDotCom** [comment]
the videos listed in the image above they meant to be the ads.

they will play in al videos on your site.

you can make sure about their formats here : 

![image](https://user-images.githubusercontent.com/18009293/82729799-b9a5c180-9cd0-11ea-85c2-df8f02fa9d9d.png)

**Comment by willpower68** [comment]
@DanielnetoDotCom I am testing now to see if it works.  I believe the problem was the videos were not .mp4.

**Comment by akhilleusuggo** [comment]
> what type of videos are you adding on the Ads? It works only with MP4.
> 
> does not work with embed or HLS

**Comment by willpower68** [comment]
@DanielForthman @akhilleusuggo 
Yes, I understand that it only works with .mp4.

I'm adding this additional information for anyone that may have same road block.

When upload a video that is for advertising purposes.  Chose low, SD or HD and the video to upload you .MP4 file.  

Please NOTE if you leave the Multi Bitrate HLS checked the file will be converted to HLS and video ad WILL NOT play.  
Again choose low, SD or HD when uploading your .MP4.

After making those changes, my video ad is now working properly.  
if the above is incorrect, please let me know.  

@DanielnetoDotCom @akhilleusuggo  This is a learning journey for me.  I appreciate your help.

**Comment by GodgivenButhelezi** [comment]
> Trying to activate a video campaign. I followed the directions:
> 
> <img alt="AD Campaign Set Up" width="734" src="https://user-images.githubusercontent.com/739391/82487225-196f5300-9aac-11ea-8eae-5929ae572160.png">
> 
> However, it's not working.
> I looked at the XML file and saw [ERRORCODE]
> 
> <img alt="Screen Shot 2020-05-20 at 2 59 51 PM" width="312" src="https://user-images.githubusercontent.com/739391/82487895-03ae5d80-9aad-11ea-94b2-cbee71b0e4b2.png">
> 
> I activated the AD_Sever and AD_Server_Location to see if that was the issue. When they were turned on the videos would not play.
> <img alt="Screen Shot 2020-05-20 at 3 04 22 PM" width="625" src="https://user-images.githubusercontent.com/739391/82487506-6eab6480-9aac-11ea-9d82-80f9df02e633.png">
> 
> once the ad_server was turned off the videos would play with no issue. So, I not sure what I am missing to get the ad campaigns to play.
> 
> the VMAP, Link it isn't clear to me what I should do with the link.
> 
> Hopefully you can help

I know what you done. i tried it yesterday. I linked a trailer from  youtube(embeded a video/did not upload) and I added it to my ads and it showed me the same message that you are seing. I then removed the embeded link and uploaded the mp4 file and it worked.
![ad 2](https://user-images.githubusercontent.com/59503924/82736738-d15a6580-9d23-11ea-826d-6d1f7985a866.png)
![ad 3](https://user-images.githubusercontent.com/59503924/82736742-d3bcbf80-9d23-11ea-8d41-95e6ba064d43.png)
![ad](https://user-images.githubusercontent.com/59503924/82736753-d6b7b000-9d23-11ea-90d5-e6d7c5459e0f.png)

I hope this will help
