### ISSUE TITLE
Email All Users error

### ISSUE THREAD

**Issue by GodgivenButhelezi** [WWBN/AVideo#3110]
greetings Mr Daniel. I have a Problem with the Email All Users. When I sent the email I get this message.

Sorry!
Message could not be sent Could not execute: /usr/sbin/sendmail -t -i

**Comment by akhilleusuggo** [comment]
are you using NGINX ?

**Comment by GodgivenButhelezi** [comment]
Yes

**Comment by GodgivenButhelezi** [comment]
You helped me resolve my problem on https://github.com/WWBN/AVideo/issues/3052#issue-616990413

**Comment by DanielnetoDotCom** [comment]
@GodgivenButhelezi please check this https://github.com/WWBN/AVideo/wiki/Setting-up-AVideo-Platform-to-send-emails

**Comment by GodgivenButhelezi** [comment]
![Email Live meet my craft](https://user-images.githubusercontent.com/59503924/82733793-6488a080-9d0e-11ea-9792-f32667446c5e.png)


> @GodgivenButhelezi please check this https://github.com/WWBN/AVideo/wiki/Setting-up-AVideo-Platform-to-send-emails

This i
![Email2 Meet my craft live](https://user-images.githubusercontent.com/59503924/82733798-6c484500-9d0e-11ea-94ba-1505d95de8cc.png)s what I'm talking about sir not the ones you are refering to.

**Comment by DanielnetoDotCom** [comment]
You need to configure your sendmail/SMTP to be able to send any type of email.

**Comment by GodgivenButhelezi** [comment]
> You need to configure your sendmail/SMTP to be able to send any type of email.


thanks sir let me do as you have instructed.

**Comment by GodgivenButhelezi** [comment]
![Mail](https://user-images.githubusercontent.com/59503924/82738491-d6251680-9d2f-11ea-8053-36d3079f8647.png)


> You need to configure your sendmail/SMTP to be able to send any type of email.

Still not working sir

**Comment by ronaldod** [comment]
Enable SMTP the screenshot shows it disabled and not even set the protocol TLS or SSL

**Comment by GodgivenButhelezi** [comment]
![mail 3](https://user-images.githubusercontent.com/59503924/82738831-a4617f00-9d32-11ea-856e-7ff381c9aa7d.png)


> TLS or SSL

It's now done like that but still loading for 15 minutes and showing a different error message

**Comment by ronaldod** [comment]
Example for google.

![image](https://user-images.githubusercontent.com/31585599/82738928-bd226280-9d3b-11ea-8bf9-dac8b7fb5c42.png)

**Comment by GodgivenButhelezi** [comment]
It's Showing the same message even after I done that
![mail error](https://user-images.githubusercontent.com/59503924/82739166-61ed7180-9d35-11ea-9bf5-fac073d76eb2.png)

**Comment by ronaldod** [comment]
In the tab before you have to write down where the mail is send from that has to match the email account you configured under advanced. As most SMTP relays are not allowing to use a different send from address:

![image](https://user-images.githubusercontent.com/31585599/82739254-78e49180-9d3e-11ea-8d80-6e538e7ec6a9.png)

**Comment by GodgivenButhelezi** [comment]
Still failed and showed the same message. I had it write before i installed the SSl certificates. Everything else is working fine except this one

**Comment by ronaldod** [comment]
Did you checked if you can reach the mail server ports with telnet ?

**Comment by GodgivenButhelezi** [comment]
yes i checked and  it works, just not here and i believe its something that has to do with NGINX

**Comment by DanielnetoDotCom** [comment]
@GodgivenButhelezi check this https://github.com/WWBN/AVideo/issues/2871#issuecomment-614813878
