### ISSUE TITLE
Video Swap stopped working

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3111]
Watch here: https://www.joshwhotv.com/video/20370/videoswapbroke

**Comment by akhilleusuggo** [comment]
the only thing I can say is that , both videos are empty . As you can see , there's nothing to swap , 2mb ( are the size of the images , thumbs / gifs , thumbs resized ) . Make sure that the videos **DOES** exists .

**Comment by JoshWho** [comment]
That is not the problem at all. I normal repair videos this way. This thing is not working at all. Usually a message pops up saying if it was swapped successfully nor if it failed. None of that is happening.

**Comment by akhilleusuggo** [comment]
**Edit :** try to update disk usage , then swap . ( what log file say ? )

**Comment by JoshWho** [comment]
I still have 4tb free

**Comment by akhilleusuggo** [comment]
I'm talking about this : 

![image](https://user-images.githubusercontent.com/52116577/82534081-34de6a80-9b4d-11ea-94b9-928b1567b3a5.png)

**Comment by JoshWho** [comment]
Nope, that did not work either.

**Comment by JoshWho** [comment]
That is what I did. I cant see the log. Folder it is in has too many inodes

**Comment by ronaldod** [comment]
I can confirm that this issues is is also in the latest pull. I can not swap the files.

**Comment by ronaldod** [comment]
proposed a fix #3113

**Comment by ronaldod** [comment]
Also the messages from the swapVideo.json.php are not send back to the page. So you never noticed what happened.
@DanielnetoDotCom Can you also look into that ?

**Comment by ronaldod** [comment]
Fix is merged. Let me know if it fixed it for you.

**Comment by JoshWho** [comment]
So is it fixed in the latest Pull request?

**Comment by ronaldod** [comment]
yups
