### ISSUE TITLE
Live Stream but says Offline

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#3115]
Everything seems to be working with live stream except it's shows Offline.  If I type it in manually it shows stream is offline but if I click the play button it plays the stream.

When I check that Stat it's showing the stream but the RTMP is "https://wwwMY-DOMAIN.ca/plugin/Live/on_publish.php"

I have a redirect in Apache to HTTPS, removed it but didn't help.

I tried everything I could find on the forum but no luck.

What should I be looking at?

Thanks

**Comment by DanielnetoDotCom** [comment]
the offline message most of the time is related to your stats page.

check this:

https://github.com/WWBN/AVideo/issues/2970

https://github.com/WWBN/AVideo/issues/426

https://github.com/WWBN/AVideo/issues/1914

**Comment by D-Spayre** [comment]
Thank you, I have everything working. :)
