### ISSUE TITLE
[URGENT] Serious security issues 

### ISSUE THREAD

**Issue by ahussam** [WWBN/AVideo#3117]
Heya, 

I found 2 high critical security issues:
* User with low privilege can take over the website
* Local File Include that exposes server files with DB credentials. 

Where I can report them? posting them here may lead to disaster for users. 

Best

**Comment by ronaldod** [comment]
You can contact @DanielnetoDotCom at developer@youphptube.com

**Comment by DanielnetoDotCom** [comment]
Hi

yes, please provide details

**Comment by ahussam** [comment]
@DanielnetoDotCom here?

**Comment by DanielnetoDotCom** [comment]
You can please email me, so I can fix it first.
developer@youphptube.com

**Comment by ahussam** [comment]
Done! check your email @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
The issue is confirmed and fixed. I am marking the secured version as 8.9

**Comment by DanielnetoDotCom** [comment]
@ahussam thanks for your help.

can you please confirm if it fixes the issue?

**Comment by ahussam** [comment]
Confirmed! I will request CVE from Mitre. 

@DanielnetoDotCom
