### ISSUE TITLE
Redirect deleted videos / Inactive 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3118]
When a video is not available , usually this page does appear .

![image](https://user-images.githubusercontent.com/52116577/82657399-f66cac80-9c2d-11ea-994a-0b8d55ee99b3.png)

On the plugins , we can customize it. I did , and made it looks like this. 

![image](https://user-images.githubusercontent.com/52116577/82657506-21570080-9c2e-11ea-8fbe-6723be1e735e.png)

The bad thing , is that this pages , are bad for the site in general . Make the site looks like not operational , in case a user visited your site first time , from search consoles . No videos appearing anywhere , nothing , like a blank site .

What I'm proposing is something like this . Redirect non found , inactive etc videos to something like . 

![image](https://user-images.githubusercontent.com/52116577/82658484-b8708800-9c2f-11ea-8412-af98638076a6.png)

The users will see that this video is not available , but the site is active and can view other videos related or from the same channel .
I managed to show this picture by uploading the img under `/view/img/this-video-is-not-available.jpg `with direct upload . ( sadly I see the Theater mode is not working with img/pdf )

OFC , I made some more progress , and with html/javascript redirect , can be easly made , but will be a redirect to the img link , not under the same video link : 
On plugins , videoNotFoundText: 
```
<html>
<body>
<script type="text/javascript">
    window.location.replace("http://127.0.0.1/YouPHPTube/video/40/video-automatically-booked");
</script>
</body>
</html>
```

Any inactive video link does redirect me to video not available . 

What I'm asking is , under the same link do show video , but if video does not exist , or private , load the player with the img .

**Comment by DanielnetoDotCom** [comment]
I like the idea. What about this update?

**Comment by akhilleusuggo** [comment]
perfect , like I designed it !
I'll look more if possible to insert texts into js , or something like , when the video is corrupted .
Is there anyway to use this as Theater compressed mode ?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Actually it does work only on inactive videos , but not deleted videos etc 
![image](https://user-images.githubusercontent.com/52116577/82730422-343e0380-9d08-11ea-8a39-32d93b332108.png)

**Comment by DanielnetoDotCom** [comment]
Not sure, I tested with this video (does not exists) and it appears correctly

https://demo.avideo.com/video/21121221/ 

do you have a sample on demo site so I can take a look?
