### ISSUE TITLE
deleteOrphanFiles.php

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3119]
Can't remove directory 

`../videos/_YPTuniqid_5dee66ae114d78.70871407 Directory Could Not be Deleted`

**Comment by DanielnetoDotCom** [comment]
not sure why and where does this error come from. did you try with command line?

**Comment by akhilleusuggo** [comment]
yes, with command line . 
on /install `php deleteThumbsFiles.php`
Does remove gifs, img etc , but not directories .

**Comment by DanielnetoDotCom** [comment]
I mean to delete it with the `rm -R videos/_YPTuniqid_5dee66ae114d78.70871407`

the deleteThumbsFiles.php should not even try to delete this folder.

this is only if you try to delete a video.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Omg , I typed wrong the file's name , I meant `php deleteOrphanFiles.php`

**Comment by DanielnetoDotCom** [comment]
I look into the code, the error on deleting the directory should be something related to the permission.
