### ISSUE TITLE
Plugin store overview not working

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#3121]
**Describe the bug**
If you go to the list of plugins and select the tab of the plugin store it is empty.

![image](https://user-images.githubusercontent.com/31585599/82701929-546eb380-9c71-11ea-92cf-ef06bb9d81b1.png)

**To Reproduce**
The page is empty only the button works

**Expected behavior**
That the list with payed plugins shows up.

![image](https://user-images.githubusercontent.com/31585599/82701883-3ef98980-9c71-11ea-9069-3fdbb35a24d9.png)

**Error Logs**
Log are empty but there is this one:

![image](https://user-images.githubusercontent.com/31585599/82702057-8bdd6000-9c71-11ea-8f5e-15990dbe044e.png)

and:

![image](https://user-images.githubusercontent.com/31585599/82702390-35bcec80-9c72-11ea-98a9-0bfdfa3611c4.png)

**Additional context**
I expect a redirect misfire on the site with the plugin list.

**Comment by DanielnetoDotCom** [comment]
Hi

Thanks, it was a cors error on the plugins site. it is fixed now.
