### ISSUE TITLE
Channel Name on videos Disappeared 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3123]
![image](https://user-images.githubusercontent.com/52116577/82732066-9f410780-9d13-11ea-9c66-0401e314e091.png)

![image](https://user-images.githubusercontent.com/52116577/82732083-b67ff500-9d13-11ea-82fa-326a0977b404.png)

**Comment by ronaldod** [comment]
And this is in the logging
`[23-May-2020 14:32:30 UTC] PHP Notice:  Undefined index: creator in /var/www/test.mytown.com/view/modeYoutubeBottom.php on line 83
`
Looks like the declaration of $video in modeYoutube.php is missing some options that are normally active in modeYoutubeBottom.php

**Comment by DanielnetoDotCom** [comment]
Sorry about that.

Fixed

**Comment by ronaldod** [comment]
Pulled it and it shows the button again.

**Comment by akhilleusuggo** [comment]
+
