### ISSUE TITLE
No video upload option available

### ISSUE THREAD

**Issue by MikMys** [WWBN/AVideo#3124]
Hi! I've just launched a virtual machine on Google Cloud Platform and set up a website using YouPHPTube script. Unfortunately, after installation and logging in, I can't upload any videos, because... there's no such option - I've got only encode and embed. Screen below:

![obraz](https://user-images.githubusercontent.com/65827264/82737805-dcb58d00-9d33-11ea-9912-53b8209af5fe.png)

I sing in as admin:

![screen2](https://user-images.githubusercontent.com/65827264/82737762-a7a93a80-9d33-11ea-8342-edd8e9292804.PNG)

Could you please help me? Where's the problem?
Nicolas

**Comment by ronaldod** [comment]
Encode is best done uploading the files by an encoder. If correctly setup in your `site configurations ` it should log you into your encoder or the a public one.

Or go for direct import you need to disable  `doNotShowUploadMP4Button` first in your plugin `CustomizeAdvanced`.

![image](https://user-images.githubusercontent.com/31585599/82738104-aa0c9400-9d35-11ea-9dd7-a9d56ca08543.png)

And press save.

Then this should be appearing.

![image](https://user-images.githubusercontent.com/31585599/82738142-e809b800-9d35-11ea-9fee-8e6ba4a200af.png)

Do not also to check the instructions and settings for upload privileges.

**Comment by MikMys** [comment]
Thanks, after making changes in CustomizeAdvance, the upload button is visible.
Are you suggesting it is better to encode rather than upload? Why is that?

**Comment by DanielnetoDotCom** [comment]
Encoder is better, but read this https://github.com/WWBN/AVideo/wiki/About-Video-Upload

**Comment by leonardochristo1** [comment]
Estou com o mesmo problema, qndo faço os procedimentos citados acima tenho o direct upload, mas eu gostaria de ter o botão upload para enviar meus videos. Eu usava a versão antes das mudanças e tudo funcionava perfeitamente na minha infra, instalei essa versão e não obtive sucesso.

**Comment by DanielnetoDotCom** [comment]
Não entendi.

o que exatamente nao funciona agora?
