### ISSUE TITLE
Sort by name Flix-page

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3126]
Hi, 

is it possible to implement "Sort by name" option on Flix style page? It's already on plugin form as an option so we'd love to see it working. Thanks!

![image](https://user-images.githubusercontent.com/63721378/82747973-d44a6a00-9da6-11ea-9795-699002ad4aef.png)

**Comment by DanielnetoDotCom** [comment]
Please check this

**Comment by tonuzo** [comment]
Thank you! It works.
