### ISSUE TITLE
Credit card payments broken

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3128]
Hi!

When try to pay subscription with credit card the page stops responding. 

How to reproduce:

1. Under plan, press "pay with credit card" 

Action:

Credit card payment form scrolls open and page freezes and you can't input card number, etc.. 
Buttons etc don't respond.  

Javaconsole: nothing
Avideo.log: nothing related

edit: I'm not sure after what pull this has stopped working, but before it has been working right.

![image](https://user-images.githubusercontent.com/63721378/82750079-7b82cd80-9db6-11ea-891d-1ca0bb0e74ea.png)

**Comment by DanielnetoDotCom** [comment]
What is the page URL so I can test myself ?

**Comment by DanielnetoDotCom** [comment]
Hi, I like your customization, but be careful that you may break some things

looks like your **position: fixed;** is breaking the card position.

/plugin/Wellness/view/css/style.css

![image](https://user-images.githubusercontent.com/18009293/82757023-2fcf2480-9db4-11ea-9d7a-4e0ff8d0afd1.png)

**Comment by tonuzo** [comment]
Thank you!

That does it. Sorry for the hassle, my bad. I'll be more careful... 

Br,T
