### ISSUE TITLE
Multi-Field Static Content 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3129]
I'm experimenting load balancing at my home server , and on CustomizeAdvanced I have only 1 field to add static website (videosCDN field) .

I don't understand very well this field . It should be hosting static content only ( I suppose videos )

The thing is this : Having only 1 field (videosCDN) ( 1 domain , will make me ending up by making at the least 3-4 server to start making a load balancing .  I did represent it with this img .

![image](https://user-images.githubusercontent.com/52116577/82754164-c828d180-9dd3-11ea-9698-b97b4431d824.png)

I'm not sure still how the field of videosCDN works , but if can accept multiple urls , could be like this . 

![image](https://user-images.githubusercontent.com/52116577/82754249-6452d880-9dd4-11ea-9b92-0c41f6e06191.png)

The thing is , does the static need to be **_hosted on the same server_** ?

Why did I started testing this ? Well , with the new feature of **rcync clone** , it's easier then ever , to have them sync all the stats the load balancer server , basically at every-video that is added to the main server , could be cloned into the other server immediately .

PS: For now only ideas and test purposes . ( ignoring the YPT Storage for now , since I don't know if the Clone Plugin does work or not )
I hope some feedback . Thank you

**Comment by ronaldod** [comment]
What is exactly you want to resolve ? Bandwidth, disk performance, redundancy or CPU. As disk space is not the part you limit your self to in this design.
I would play around with using YPT Storage and but then behind a load-balancer. As that is a great static option. If it for latency you can also use route53 by placing servers around the world.

**Comment by akhilleusuggo** [comment]
@ronaldod Disk performance ( IO ) and bandwidth obviously . At the end , a video website will end having bandwidth problems before storage . ( Storage it's a problem , but there's a solution ) . Bandwidth on the other hand is harder to solve .

As I've stated on the issue , it's for testing purposes on my local machine ( learning stuffs and fun )

**Comment by ronaldod** [comment]
Interesting experiment.  YPT storage looks also as good solution but would be nice to add some functionality to it like load balance. Moving over video files if requests goes above xxx requests per hour. And fill up equally based on % or real free space.

**Comment by akhilleusuggo** [comment]
the thing is , if only 1 video is getting a lot of views at the same time , the YPT Storage does help at all , even moving the video. The video need to be in 2 servers at the same time .

Reverse proxy is easy to configure on static sites ( blogs etc ) , even tho are not really needed . But on this specific project , for me it's not clear the CDN video field , and if possible to have more then 1

**Comment by ronaldod** [comment]
I meant that with load balancing that one file can be hosted by multiple servers. I case of x request it is making a copy to the other storage server(s). And the video is balancing the link to the videofile based on some metrics. That would be a great plugin. And of course a cleanup script after the file is below thresholds.

**Comment by DanielnetoDotCom** [comment]
Right now the videosCDN is deprecated. due to we can transfer files in chunks.

For performance improvement the best solution I can imagine is to use a Paid CDN that can cache the videos files.

As I know Netflix uses Akamai CDN

**Comment by akhilleusuggo** [comment]
Check your email , because this is a bad idea .

**Comment by DanielnetoDotCom** [comment]
what is a bad idea? use videosCDN or make it deprecated?

**Comment by akhilleusuggo** [comment]
So , to understand you well . The domain/subdomain that you type of the CDNVideo field , will stream the videos or only HTML/css etc .
Will it be hosted by cloudflare ? or should the IP point directly to the server ?

**Comment by DanielnetoDotCom** [comment]
It will replace the link for css, js and videos to the cloudflare domain
