### ISSUE TITLE
Can this script run 100% on Nginx server without apache?

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3130]
I wish to move all my sites to only work with NGINX, is it possible to run YouPGPTube script only with nginx? or do I must have apache installed as well?

**Comment by DanielnetoDotCom** [comment]
I do not use nginx for my self and I have never test it.

I cannot answer you that. But maybe with the correct tweak you may be able to run it

**Comment by guymass** [comment]
So ATMO I am running only NGINX and the site loads up but the URLs are not opening my videos. I am not sure really what to do. I see that the URLs are piting to:
https://fetube.flatearth.co.il/video/2786/wow-the-1587-map-fits?page=1&channelName=5df12a039b08f

Shouldn't it be /videos/ .

I have preview but no videos are playing just getting white screen.

**Comment by ronaldod** [comment]
A not supported install from [linuxbabe](https://www.linuxbabe.com/ubuntu/install-youphptube-ubuntu-18-04-server) i tested in the past to be working. (excluding the streaming as i did not tested that part).

nginx works on some points different and is not using .htaccess so you need to configure things different.

**Comment by guymass** [comment]
Thank you very much I will take a look.

**Comment by guymass** [comment]
I just noticed that this is the manual I was following. The site seems to be working, admin, encoding etc. but all the links to my videos are not pointing to the correct folder, and even if I change the folder name to the correct one they still do not open. I need help to understand what is wrong with the URLS. I am sure it is a minor configuration. I was using the exact code sample from that manual.
shoud there be a DOMAIN/video folder in the urls?

**Comment by ronaldod** [comment]
try to convert the .htaccess with [.htaccess converter ](https://winginx.com/en/htaccess) As there are many rewrite rules missing.

**Comment by guymass** [comment]
I can see my videos like so
https://fetube.flatearth.co.il/videos/_YPTuniqid_5ecac2e2a72db1.01476654_HD.mp4

Bu most my urls are now presented as such:

https://fetube.flatearth.co.il/video/1335/-21-?channelName=5df12a039b08f

I will try the htaccess converter and see how it goes.

**Comment by guymass** [comment]
Tried it and still same 500 error. URLs are not the same anymore and also now I get this on the Encoder.
![Screen Shot 2020-05-27 at 0 08 38](https://user-images.githubusercontent.com/58882903/82951174-602ee280-9faf-11ea-8d77-3158a099d6db.jpg)

**Comment by guymass** [comment]
[26-May-2020 21:37:55 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/video/1406/men-of-old-men-of-renown/" in /var/www/html/YouPHPTube/ob$
Stack trace:
#0 /var/www/html/YouPHPTube/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/YouPHPTube/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/YouPHPTube/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300

**Comment by guymass** [comment]
So Now I restored back my apache files and configs and now I still get the same errors. I am not sure really why those URLs are now completely pointing to some other directory or they are being created in the wrong way. I understand this would be the case when trying to run it mainly on NGINX, but now why this error persists in Apache as well?? This was working fine with its original config files you setup for me last time. Is there a proper config file,  with config examples I can use properly to setup this script? Just a straight forward  1,2,3 to setup the Apache side so it at least returns to normal. I cannot spend more money and time and honestly I haven't even been able to use it for what I really want it for. I was planning to get a better server to support video live streams properly but I want it to run mainly on an Nginx server without Apache. So I am kinda stuck here with a script that is only used for viewing videos and now that is somehow been screwed again. HTACCESS files are the same, all is as it was and still with Apache I get the same URL errors.

**Comment by guymass** [comment]
This file exists in my videos directory. Please help me understand the way this URL works. What is the additional numbmer in the end?

_YPTuniqid_5e0b4e309a33f7.62153103_thumbsSmallV2.jpg?1590532671

Now thumbs are not loading as they were before. Still all urls are pointing as an example to:

https://fetube.flatearth.co.il/video/2413/gmo-foods-glyphosate-autism-obesity-stephanie-seneff?page=1&channelName=5df12a039b08f

So I would like to know how this URL should work and what does the script expect after I click a thumbnail. Is it something to do with the way PHP is handles in NGINX?

**Comment by guymass** [comment]
My site is loading the GIf images and everything appears to be OK accept that none of the videos are opening. I think this URL is wrong and I don't know why as I don't know how the script create the links. Can someone please assist and explain what is the actual problem here?

**Comment by guymass** [comment]
NGINX PROBLEM SOLVED!!! All is fixed on my site. https://fetube.flatearth.co.il is now running 100% NGINX without apache server and it is very fast, soon to be even faster. You can close this issue now.

**Comment by ronaldod** [comment]
Could post your config changes? Then we can include it also for others in the future.
