### ISSUE TITLE
Chat2 display by username rather then personal name

### ISSUE THREAD

**Issue by bruinp8n** [WWBN/AVideo#3131]
Is there a way to adjust the username to appear in chat2 rather then the personal name?  Users on my site were requesting it as they don't want there personal name to appear.

**Comment by ronaldod** [comment]
Please label in the future these type of questions as an enhancement not as a bug.

**Comment by bruinp8n** [comment]
apologies

**Comment by akhilleusuggo** [comment]
@bruinp8n Plugins ; Customize User ;
![Screenshot from 2020-05-25 07-39-21](https://user-images.githubusercontent.com/52116577/82778864-4c726780-9e5b-11ea-8ab7-8d8a35ccb314.png)

Select what you want

**Comment by JoshWho** [comment]
That option wont change it.  Mine shows the channel name and if the user doesn't set one it just has the generic 5dwewkjwk   has thing as their name

**Comment by akhilleusuggo** [comment]
well , the user should has a name , that generic name is the channel ID

**Comment by DanielnetoDotCom** [comment]
this update should give a more friendly channel name

**Comment by bruinp8n** [comment]
Disabling the other names worked thank you
