### ISSUE TITLE
Translations on paid plugins?

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3134]
HI

Can you add translations on paid plugins e.g. Stripe, Paypal, etc.. 
Language translations don't affect when added on /locale/xx.php 

![image](https://user-images.githubusercontent.com/63721378/82798042-a76a8580-9e80-11ea-8170-1fdd189ae454.png)

![image](https://user-images.githubusercontent.com/63721378/82797690-1e534e80-9e80-11ea-9ecd-6dcca478b511.png)

**Comment by DanielnetoDotCom** [comment]
Hi

I just sent 2 updates to the core code and 1 update to the PPV plugin (if you are using it)

now you can add the translation $t['Submit Payment'] and you will be able to see the translation on the buttons.

**Comment by tonuzo** [comment]
Thanks, It works now. There's still some untranslatable texts here and there. I can collect them in another issue.

**Comment by tonuzo** [comment]
Actually I just noticed that in Subscription-plugin also has untranslatable texts when you go user profile and check your Subscriptions. 

![image](https://user-images.githubusercontent.com/63721378/83064546-9b421c00-a06a-11ea-8566-f907b2d194b7.png)

**Comment by DanielnetoDotCom** [comment]
Hi

I just sent some updates to the subscription plugin, you should be able to translate them now.
