### ISSUE TITLE
while generating site map i am getting permission denied error

### ISSUE THREAD

**Issue by sharad22gupta** [WWBN/AVideo#3135]
when i try to generate site map i get this error

[25-May-2020 10:04:40 UTC] PHP Warning:  file_put_contents(/var/www/html/sitemap.xml): failed to open stream: Permission denied in /var/www/html/objects/configurationGenerateSiteMap.json.php on line 22

what can i do 
i tried chmod 777 for both the files didnt work.
@DanielnetoDotCom @akhilleusuggo @ronaldod

**Comment by akhilleusuggo** [comment]
try starting by doing this : 
1- `cd /var/www/html/`
2- `chown www-data:www-data -R *`
3- `cd /var/www/html/`
4- `chmod 777 sitemap.xml`

I'm following the path you linked , looks like you have the project without a folder . Basically on the public directory on /html/* , if that the case , then the files above may work .

**Comment by sharad22gupta** [comment]
That worked thankyou
