### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3136]
I would like that we could have different logs , not only 1 log file where everything is written there .

avideo.log = for general logs ( login , requests etc )
avideo-error.log = [ Only errors ] , php error logs , etc 
avideo-process.log =  [ Debugging ] This is usefull for plugins , to see if they performed the actions that were required , for debugging . Example : 
https://github.com/WWBN/AVideo/blob/0c04daf578285d81d8bb2ea8f3faa7131f7a8881/objects/playListAddVideo.json.php#L40

Not very useful , but helps to understand and see if the process has done what were required .

PS : OFC the name of the log files , I made it just as example , does mater what name will have .

**Comment by ronaldod** [comment]
Sounds like a good idea.

A function like :  `log(type,severity,message);` So you keep one function that can split based on type into multiple log files and based severity level. From debug, Info, warn, error till fatal.
There for you can also set a log level to lower the load on the logging or increase when debugging.

And standardize the logging with something like log4j or log4php. These engines are optimized for logging. And the best thing is these log fields are compatible with logging parsers like morpheus or splunk.

**Comment by DanielnetoDotCom** [comment]
Hi

I agree, not there is an Object called AVideoLog, that has 3 static variables, that you can use to pass to the _error_log function.

this will tag the log line at the beginning with the type. all in the same file, but easier to filter with the grep command.

The default is AVideoLog::Debug, I replaced some in the code, but for sure there are a lot more to replace.

feel free to submit pull requests if you think som log should have a different classification.

**Comment by JoshWho** [comment]
I wish the log directory would be located in its own directory. I have way to many indoes in the video directory to keep searching for it.

**Comment by DanielnetoDotCom** [comment]
What about this ...

Now you can set up an absolute path to your log file in your configuration.php file

`$global['logfile'] = "/var/log/avideo.log"` for example

just make sure apache will be able to write in the log folder

**Comment by akhilleusuggo** [comment]
ohhh , this is great .
