### ISSUE TITLE
Categories do not showing files (PDF, PNG, etc)

### ISSUE THREAD

**Issue by OxequaTeam** [WWBN/AVideo#3137]
I'm testing the upload of different file formats like PDF, PNG, etc. These kinds of files are correctly imported but not showing up into the categories. Initially I was thinking it was a matter of cache but wasn't (tested on different browsers/different PC).

STEPS TO REPRODUCE:
1. upload a PDF
2. assign the file to a category (private or public doesn't matter)
3. go to the category, the file isn't displayed

Everything works fine with videos.

**Comment by akhilleusuggo** [comment]
Check your log files , I've tested and work . Does show on categories .
Make sure to clear the cache . If you're using some CDN , make sure also to clear that cache .

**Comment by akhilleusuggo** [comment]
![Screenshot from 2020-05-25 17-05-09](https://user-images.githubusercontent.com/52116577/82820025-15777280-9eaa-11ea-961c-8c0b60241885.png)

**Comment by akhilleusuggo** [comment]
![Screenshot from 2020-05-25 17-07-32](https://user-images.githubusercontent.com/52116577/82820179-625b4900-9eaa-11ea-99cf-c144f95dcb75.png)

**Comment by OxequaTeam** [comment]
@akhilleusuggo thanks for the feedback! I tried to clear the cache but it doesn't work, I'll check the logs. 

In your environment is it working also for private categories?

**Comment by akhilleusuggo** [comment]
if the user has access to the private categories then yes works .

**Comment by DanielnetoDotCom** [comment]
@OxequaTeam can you reproduce it in the demo site?
