### ISSUE TITLE
On clicking Clear first page cache and clear chache directory getting undefined function error

### ISSUE THREAD

**Issue by sharad22gupta** [WWBN/AVideo#3138]
[25-May-2020 19:26:34 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function clearCache() in /var/www/html/objects/configurationClearCache.json.php:17
Stack trace:
#0 {main}
  thrown in /var/www/html/objects/configurationClearCache.json.php on line 17

@akhilleusuggo @DanielnetoDotCom

**Comment by ronaldod** [comment]
I did a clean install with a fresh pull 1 hour ago and could not reproduce it.
What version are you running. Better said from what timestamp is your pull.

**Comment by akhilleusuggo** [comment]
what Ubuntu server ?

**Comment by sharad22gupta** [comment]
I am using 8.6 version of the platform and 16.4 ubuntu and 7.2 php @ronaldod @akhilleusuggo

**Comment by akhilleusuggo** [comment]
Ubtuntu 16.04 , requires php7.0 , not 7.2
We're at AVideo 8.9 not 8.6

You're having everything wrong .

**Comment by ronaldod** [comment]
It means if your running 8.6 and did not an update it means there where some changes. As the script calls that function indirectly by configurations.php and then functions.php. I would suggest to check what did you changed in the code.
