### ISSUE TITLE
 DataTables warning: table id=dt1 - Ajax error. 

### ISSUE THREAD

**Issue by videostuyo** [WWBN/AVideo#3139]
I get the following error on the Dashboard. 
 DataTables warning: table id=dt1 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

![image](https://user-images.githubusercontent.com/65920587/82839090-38028f00-9e9c-11ea-94bf-95ea4269394b.png)

I guess it did not create a table upon installation of a plugin. If you hit OK, it works fine after that.

I don't know what caused it. It seems to have happen after new version of software was installed.

**Comment by ronaldod** [comment]
Please send more details like described in the template. Log files and exact what you did you create this. Like what plugins you activated and such.

**Comment by DanielnetoDotCom** [comment]
Usually this is related to a not installed table.

the missing table should be revealed in the log file
