### ISSUE TITLE
The processing pop up gets stuck on deleting files and everywhere else it 

### ISSUE THREAD

**Issue by videostuyo** [WWBN/AVideo#3140]
The processing pop up gets stuck. See screenshot. It happens all the time. Anywhere Processing up happens. Most times including when I login, one can get around it by just refreshing page. But on many pages, like deleting videos it does not do action. 

![image](https://user-images.githubusercontent.com/65920587/82839260-ce36b500-9e9c-11ea-91d6-42704c046a15.png)

![image](https://user-images.githubusercontent.com/65920587/82839551-b7dd2900-9e9d-11ea-98d5-a203eff92221.png)

**Comment by ronaldod** [comment]
Take a look at [troubleshoot page](https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform) and if you find something you can post the data from the log file(s) here.

**Comment by akhilleusuggo** [comment]
I believe it's permissions issues .
`cd /var/www/html`
`chown www-data:www-data -R *`

**Comment by arizonal2014** [comment]
I am experiencing the same. @akhilleusuggo I do not think it has to do with permissions. @videostuyo have you find solution?

**Comment by ronaldod** [comment]
@arizonal2014 Assumption is a bad thing to do in IT world. The command that @akhilleusuggo gave is not optional but mandatory for this installation.

**Comment by arizonal2014** [comment]
@ronaldod Hehe You seems like a troublemaker. You must have done "chown www-data:www-data -R * " during installation. And I agreed Assumptions is bad.

**Comment by ronaldod** [comment]
One thing he also assumes your using Ubuntu and Apache. So replace that user and group with the correct one.
