### ISSUE TITLE
 getDataObject - JSON error (4) Customize c4fe1b83-8f5a-4d1b-b912-172c608bf9e3

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3142]
` getDataObject - JSON error (4) Customize c4fe1b83-8f5a-4d1b-b912-172c608bf9e3`

Every page I check , brings this error

**Comment by DanielnetoDotCom** [comment]
This is a recent log that I add. this checks when decoding the plugin parameters

is the customize plugin working?

**Comment by akhilleusuggo** [comment]
Does work yes
