### ISSUE TITLE
Help with stat.xls

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3143]
I'm having problems with the stats.xls
I downloaded the one that @DanielnetoDotCom gave , witch does not expose the data of the streamers . ( https://youphptube.com/docs/stat.xsl )
The thing is that is not doing any effect . Tested on home server and works .
1- I went to `/usr/local/nginx/html/` && `rm stat.xls`
2- checked the stats on the site yoursite.com:444/stat , and the stats are still showing ...

Where else the stat.xls is located that is taking effect ? How are the stats showing if the file does not exist anymore ? There's something I'm missing and I don't know what is .

nginx config for the stats : 

```
#allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                            
                    }
                    location /stat.xsl {
                            root html;
                            
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
```

**Comment by DanielnetoDotCom** [comment]
In my case the `stat.xsl` file is hosted in the folder `/usr/local/nginx/html`

**Comment by akhilleusuggo** [comment]
I had to disable entirely the stats page , because even removing all files on /html , the stats page still showing up
