### ISSUE TITLE
add to favorite , and watch later

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3144]
1- They appear ONLY when you're at the channel page . ( no other pages )
2- The ''Watch later'' is not clickable .

**Comment by JoshWho** [comment]
Mine keeps not working also. Just older accounts I notice have this bug. I cannot edit a playlist or create any new ones on one of my accounts.

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo 
1. Do not understand can you please screenshot for details?
2. is the same on demo site? on my side it is working.

@JoshWho  and @akhilleusuggo 

I found a bug from the older code. for some reason the script creates multiples favorites and watch later playlists for some users.
I made a script to remove the repeated playlists. please run it and check again.

https://github.com/WWBN/AVideo/blob/master/install/removeRepeatedPlaylists.php

go to the install folder and run

`php removeRepeatedPlaylists.php`

then try again

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 
1) Try to review the certificate of http://demo.youphptube.video/ , I'm getting mixed content on the demo.avideo.com site . 
![image](https://user-images.githubusercontent.com/52116577/83039444-db8fa300-a046-11ea-8bb2-ee665bb6edaf.png)

2) The bug does also exist on demo site . This button is not clickable : '' watch later ''
![image](https://user-images.githubusercontent.com/52116577/83039846-49d46580-a047-11ea-81cd-9c22f0e52807.png)

3) The buttons that you have added '' watch later " and "add to favorites '' does appear ONLY on the video under the section '' my channel '' .
PS : on demo site works , but not on my site .

![image](https://user-images.githubusercontent.com/52116577/83040402-e3037c00-a047-11ea-9cd7-ce4ff3e337cb.png)

In this case on demo site are missing because they belong to YouTube ( I think ) . But I don't know if this has to do with the thumb sizes or something with gallery .

**Comment by DanielnetoDotCom** [comment]
The youtube section will not have the buttons, they are random videos

The buttons should not appear if you are not logged it. (just sent a fix)

About the insecure content. thanks, it is fixed now.

I could click with no problem

![image](https://user-images.githubusercontent.com/18009293/83065070-39b58980-a039-11ea-99f0-3f60589d2b54.png)

try to clear your browser cache. to make sure you will get the latest css and js

**Comment by akhilleusuggo** [comment]
fixed . But still missing many places . Videos on side videos bar , ( play next , Big video on welcome page and categories , videos that are on playlaylist ( channel ) .Screens down to explain : 

![image](https://user-images.githubusercontent.com/52116577/83071426-c41bde80-a075-11ea-99a8-0acf7929aed3.png)

![image](https://user-images.githubusercontent.com/52116577/83071476-dd248f80-a075-11ea-88cd-731de185d673.png)

![image](https://user-images.githubusercontent.com/52116577/83071531-f1688c80-a075-11ea-90ad-13b81de4c449.png)

It doesn't maters those videos are hosted on the site or not ( png or not ) . I've tested it on normal videos on my home server , and they don't show up .

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by akhilleusuggo** [comment]
Perfect ! Works and well . Thank you
