### ISSUE TITLE
Cannot connect and watch live streams 

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#3145]
Unable to watch any live stream. OBS can connect, it says online but won't stream 
![screenshot](https://user-images.githubusercontent.com/37193130/82944197-c47a8380-9f68-11ea-8f86-b77bd31ddf8f.jpg)

**Comment by DanielnetoDotCom** [comment]
How is your livestream parameters?

Please screenshot and post it here

**Comment by ganddser** [comment]
![screenshot2](https://user-images.githubusercontent.com/37193130/82954057-f47e5280-9f79-11ea-96f9-2ce05645fc5b.jpg)

**Comment by akhilleusuggo** [comment]
@ganddser Ok , start by disabling "useAdaptiveMode"

If you have not set the ffmpeg parameters on nginx.conf , disable this option and should work .

**Comment by ganddser** [comment]
That worked thanks, Daniel Nato installed and configured our Avideo I'll have to check and see what he enabled.

**Comment by akhilleusuggo** [comment]
Yes , could be a mistake of Daniel , but I recommend you to take a look at https://github.com/WWBN/AVideo/wiki to have a better understanding of the functions

**Comment by ganddser** [comment]
Thanks. BTW any eta o the webcam feature?

**Comment by DanielnetoDotCom** [comment]
Hi, 


By default, I do not configure adaptative mode

If you want, you must follow this: https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream

be aware it will consume more your CPU

**Comment by ganddser** [comment]
Thanks Daniel appreciate your intervention

**Comment by ganddser** [comment]
The issue mentioned above seems to have somehow returned, I haven't changed anything since disabling useAdaptiveMode. But I'm back to not being able to play live steams

**Comment by DanielnetoDotCom** [comment]
please check your log and console.log

**Comment by ganddser** [comment]
Do you need the whole log?

**Comment by DanielnetoDotCom** [comment]
No, just the last logs right after you transmit and fail.

JS Console log and avideo.log

**Comment by ganddser** [comment]
I just checked the SSL status say SSL expired 7/4/2020. How to renew, or change certificate provider?

**Comment by akhilleusuggo** [comment]
Did daniel installed the server for you or by your own ?

**Comment by ganddser** [comment]
Daniel installed it

**Comment by ganddser** [comment]
Note after updated the LiveUsers plugin, I can connect and play the live stream but the status says it's offline. 0 live sreams

**Comment by DanielnetoDotCom** [comment]
@ganddser what is your site URL?

About the LiveUsers plugin, please update it. you need the version 2.0 for the new Live plugin (version 4.0)

**Comment by ganddser** [comment]
https://liveurestream.com. The SSL seems fine now I don't know what that earlier error was about.

**Comment by DanielnetoDotCom** [comment]
does not looks fine for me

![image](https://user-images.githubusercontent.com/18009293/87080208-a9549200-c1fd-11ea-8463-7bf4b11edf4c.png)

**Comment by DanielnetoDotCom** [comment]
Your correct domain is https://liveurestreaming.com/

maybe you are mixing domains

![image](https://user-images.githubusercontent.com/18009293/87080381-f6d0ff00-c1fd-11ea-9f01-a29fa452ff5e.png)

**Comment by DanielnetoDotCom** [comment]
But your nginx is not

![image](https://user-images.githubusercontent.com/18009293/87080501-27b13400-c1fe-11ea-9165-9b0a9089fd19.png)

Did you update something on Nginx?

**Comment by ganddser** [comment]
no didn't update anything

**Comment by DanielnetoDotCom** [comment]
Ok, I reinstall it and looks fine now

https://liveurestreaming.com:444/

![image](https://user-images.githubusercontent.com/18009293/87080689-76f76480-c1fe-11ea-866f-fa42e2805e06.png)

**Comment by ganddser** [comment]
Yeah. Still can't says 0 live streams. Any ideas on that? I know for sure there's at least 1 live stream

**Comment by DanielnetoDotCom** [comment]
FYI, you were running version 8.6, we are in version 9.1

I just update everything for you. try now

**Comment by ganddser** [comment]
Thanks Daniel, it's working now.
