### ISSUE TITLE
Category Selector in Uploadeder not syncing with Video manager

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3146]
Is anyone else having this issue? Seems like a global issue since i have 6 encoders and it is doing it on all of them. When I select a category for the video to be in it defaults back to the default category and not what I selected. All latest videos in the last week from every user keeps going to the Default directory.

**Comment by akhilleusuggo** [comment]
Same here , in my case it's going to another category , no mater what I choose .

**Comment by DanielnetoDotCom** [comment]
in what screen is this happening? on the encoder or streamer?

can you please screenshot so I can have a better idea?

**Comment by JoshWho** [comment]
Encoder

**Comment by akhilleusuggo** [comment]
encoder yes

**Comment by DanielnetoDotCom** [comment]
where do you select a category to be the default? please screenshot

**Comment by akhilleusuggo** [comment]
No , is not the case . If I select category '' Sport '' , the video on the streamer site will appear on other category , and that category could be ''default'' .

**Comment by DanielnetoDotCom** [comment]
Ok, but where did you select the category '' Sport ''? in what screen?

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/83069108-05aa8a80-a072-11ea-92ac-f2aa83daa024.png)

**Comment by DanielnetoDotCom** [comment]
I see, so it is not respecting the category you are selecting on the encoder correct?

whatever category you choose it will go to the default

**Comment by akhilleusuggo** [comment]
yep

**Comment by DanielnetoDotCom** [comment]
Not sure why I missed that setCategories_id. but now it is added on.

it should work now.

**Comment by vraghavans** [comment]
did not work for me,shd i reset some thing for it to work?

**Comment by JSY-Ben** [comment]
Are any of your categories set to private ? I had a similar problem, but it was because the categories were private and created by a user that was no longer an admin.

**Comment by vraghavans** [comment]
no  i checked ,all my categories are public

**Comment by vraghavans** [comment]
can anyone please help me on this please!

**Comment by ronaldod** [comment]
@vraghavans Did you updated the files following the [instructions](https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform) ?

**Comment by vraghavans** [comment]
thanks for the tip,i did the git pull and its working! this was my 1st time and greatful you could help me out!
