### ISSUE TITLE
Too many emails are sending at once when Live streams start and makes OBS take to long to connect and Disconnects

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3147]
Need some kind of a limiter or way to send the emails on their own cron for live streams and same goes for Message all Subscribers option as well.

**Comment by JoshWho** [comment]
This happens with users that have over 200 subscribers.

**Comment by akhilleusuggo** [comment]
I remember you have asked for this feature time ago . 
![image](https://user-images.githubusercontent.com/52116577/83243652-e5c8b300-a1a6-11ea-8b5f-20b1160b526b.png)

Have you played around this value ? 
I'm not sure , but if you lower the value, does it still lags the obs ?

**Comment by JoshWho** [comment]
I have that set already. It only works with the video upload notifications.

**Comment by JoshWho** [comment]
Message Subscribers and Notifications for Live Streams have not yet been integrated into the new email settings yet.

**Comment by akhilleusuggo** [comment]
I see .

**Comment by DanielnetoDotCom** [comment]
I have to update the notification to run in the background. the feature @JoshWho asked in the past just split the emails in multiple sendmail requests. 

but to start the live it has to wail all requests to finish. I will think in something as soon as I find some time.
