### ISSUE TITLE
360 Switch makes videos not viewable when video ads are enabled

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3148]
When 360 switch is enabled the videos are not watchable across the whole platform when the User ads are enabled. 

You hear the audio of the video but all you see is the thumbnail.

I use the b2 cloud storage and have it through a cdn. Not sure if that has anything to do with it.

**Comment by DanielnetoDotCom** [comment]
I am pretty sure you can not use the 360 plugin if the video is not hosted on the same domain.

check the js console. I guess there is a warning related to it.
