### ISSUE TITLE
player

### ISSUE THREAD

**Issue by EnrOn-tv** [WWBN/AVideo#3151]
gostaria de saber onde mudo o payer para eu coloca o sistema p2p

**Comment by DanielnetoDotCom** [comment]
o que é um sistema p2p?

o que é um payer?

**Comment by EnrOn-tv** [comment]
sim e um player ponta a ponta  https://github.com/cdnbye/P2P-DPlayer

Em qua., 27 de mai. de 2020 às 16:30, Daniel Neto <notifications@github.com>
escreveu:

**Comment by DanielnetoDotCom** [comment]
talvez isso funcionasse com um novo plugin so para tocar conteudo p2p

mas isso necessitaria de desenvolvimento em cima disso.

**Comment by EnrOn-tv** [comment]
outra pergunta como adiciono os anucios do adsense no meu videos

**Comment by DanielnetoDotCom** [comment]
Leia isso https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform 

E isso
https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Advertising
