### ISSUE TITLE
User group issues 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3152]
User group videos does show for even not logged in users .

We really need a LTS version . When things like this happens , breaks all the privacy of the video's owner , and expose them ( thumbnails etc to the public )

**Comment by DanielnetoDotCom** [comment]
where?

please provide details. can you reproduce it on demo site?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 
![image](https://user-images.githubusercontent.com/52116577/83067815-f9253280-a06f-11ea-9ddf-6d75f6195bea.png)

**Comment by DanielnetoDotCom** [comment]
You have to check this to hide it

![image](https://user-images.githubusercontent.com/18009293/83068865-5d7bce00-a03f-11ea-999c-157eae040947.png)

But I also detect a bug and I just sent an update.

**Comment by akhilleusuggo** [comment]
I have it already selected .
And yes , the problem fixed .
And really , the TLS is really important . Consider it for the future please .
