### ISSUE TITLE
2 problemas luego de actualización

### ISSUE THREAD

**Issue by cyrrusx** [WWBN/AVideo#3153]
Luego de actualizar a la última versión de la web, me ocurrieron 2 situaciones que necesito resolver y no se cómo...

1ra 
Cuando entro a la página principal, y voy al botón MENU y selecciono una categoría cualquiera donde existan vídeos, como video principal muestra el último que se subió a la página
![15906078566746359704124795962288](https://user-images.githubusercontent.com/65421482/83064041-23a2cb80-a02f-11ea-9b9c-9cb95c7d9e1f.jpg)

2do
En los dispositivos móviles, al presionar el botón MENU, no corre la vista. Solo se mueve la página principal. Debo dar un toque en él para que la vista corra hacia abajo y hacia arriba
![Screenshot_20200527_153535](https://user-images.githubusercontent.com/65421482/83064727-4386bf00-a030-11ea-867a-6c0d7a42bfed.jpg)

Estoy seguro que esto ocurre debido a mi inexperiencia. Espero que comprendan mi problema de la forma en que lo describí y me puedan dar solución.

Gracias!!!

**Comment by DanielnetoDotCom** [comment]
English, please.

**Comment by cyrrusx** [comment]
After updating to the latest version of the web, 2 situations occurred that I need to solve and I don't know how ... 1st When you enter the main page, go to the MENU button and select any category where there are videos, as the main video shows the last one uploaded to the page

2nd On mobile devices, pressing the MENU button does not move. Only the main page moves. I have to tap on it so that the view runs down and up.

I am sure this happens due to my inexperience. I hope you understand my problem as I described it and can give me a solution. 

Thank you!!!

**Comment by akhilleusuggo** [comment]
y cual es el problema aqui ? Esque no veo ninguno .
Que el ultimo video que hayas subido parezca el primero , no es un '' problema '' . 
Si lo que dices esque solo 1 video aparezca , entonces tienes un problema , pero yo no tengo ese problema . Creo que no has actualizado del todo el site . Qué version usas ?

**Comment by cyrrusx** [comment]
![15906163416278837254938305636160](https://user-images.githubusercontent.com/65421482/83076291-463edf80-a043-11ea-9d03-48b4dad6fa34.jpg)
En la versión anterior, era la v6.2 cuando yo accedía a una categoría, yo veía el primer video de esa categoría. No el último subido a la web. Y no se dónde restaurar esa opción.

In the previous version, it was v6.2 when I accessed a category, I saw the first video of that category. Not the last one uploaded to the web. And I don't know where to restore that option.

**Comment by cyrrusx** [comment]
![Uploading 15906172016383967881661369750927.jpg…]()

@akhilleusuggo 
Por ejemplo, al dar click en la categoría Chernobyl, debería verse en la foto de arriba. Si embargo, cuando doy click en Chernobyl aparece como video principal de esa categoría el último que se subió al sitio.

For example, clicking on the Chernobyl category should look like the photo above. However, when I click on Chernobyl, the last video uploaded to the site appears as the main video of that category.
![15906172916891301566808043658070](https://user-images.githubusercontent.com/65421482/83077267-0e389c00-a045-11ea-886b-7cc6e39509ef.jpg)

**Comment by cyrrusx** [comment]
![15906183729851485870537042006838](https://user-images.githubusercontent.com/65421482/83078416-9324b500-a047-11ea-863a-71a22d81df85.jpg)

Debe verse de esta forma.

It should be viewed in this way.

**Comment by akhilleusuggo** [comment]
Alli esta el problema . Tiene una version super antigua . Estamos en la 8.9 mientras tu aun estas en la 7.7 ( creo que tiene mas de 1 año de retraso ) . Tienes que actualizar , porque se han implementado muchisimas nuevas funciones , plugins y seguridad .

**Comment by cyrrusx** [comment]
Ohhh. Bueno
No sabía lo atrasado que estoy 😂
Donde pudiera descargar la versión más actualizada??? 
Vivo en Cuba y no tengo banda ancha disponible en casa. Solo datos móviles...
Muchas gracias

**Comment by akhilleusuggo** [comment]
no sé como lo has instalado , pero yo uso `git pull `
