### ISSUE TITLE
Subscription doesn't send thanksForSubscribe-email

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3154]
Hi

When Subscribed a plan with stripe, "thanks for subscribe" email doesn't send,
Email configuration is right. I can send test email. 
Nothing email related on log file,

EDIT:

2. Also I noticed something weird. When I checked the subscriptions on subscriptions page they expire on the same date and time when created:
![image](https://user-images.githubusercontent.com/63721378/83067410-48b72e80-a06f-11ea-946f-f65b50e25a4d.png)

3. When pressing "i" button on Plans tab (subscription page), it opens up a page with only script 
![image](https://user-images.githubusercontent.com/63721378/83068104-6a64e580-a070-11ea-9723-6c5ca47a6897.png)
![image](https://user-images.githubusercontent.com/63721378/83068350-e65f2d80-a070-11ea-8887-3d3617816a89.png)

**Comment by tonuzo** [comment]
@DanielnetoDotCom have you checked this?

**Comment by DanielnetoDotCom** [comment]
Hi

about the email does it send for paypal or just stripe?

2. about the info buttons it is basically a debug info.

if you want to make something valid for 1 day only, you should use PPV, subscription has a minimum of days (do not remember how many), and it is limited depends on the payment gateway platform. I guess 1 day is invalid on almost all of them.

**Comment by tonuzo** [comment]
Hi,

it happened again, user subscribed 30 day subscription and it was set automatically to expire same moment as subscribed. I had to manually set it right.. I don't know what to think...?!

**Comment by tonuzo** [comment]
There was another subscription with the same result. I checked the log file and both have been subscribed with Stripe. When I try to subscribe myself with wallet money it works.

**Comment by DanielnetoDotCom** [comment]
so the problem was with stripe?

what time does it happen?

**Comment by tonuzo** [comment]
Well I have seen it only with Stripe. 

What do you mean? What time?

**Comment by DanielnetoDotCom** [comment]
The time will help me find it in the log file

**Comment by tonuzo** [comment]
01-Jun-2020 10:10:00 UTC
01-Jun-2020 15:40:21 UTC

**Comment by tonuzo** [comment]
Payment interval on Stipe account seems right, so that's good. But anyway the automatic expire time on subscription is broken somehow, when using Stripe at least ( I haven't tested this with Paypal yet)

**Comment by DanielnetoDotCom** [comment]
Sorry for that delay. what is your domain? so I can check here

**Comment by DanielnetoDotCom** [comment]
Checking your code I found this 

```
[01-Jun-2020 15:40:27 UTC] AVideoLog::DEBUG: Stripe IPN sig_header [t=15*****5,v1=2df4a302fb525a341b05e29a9********bbaff3c69f10e4cee1f9]
[01-Jun-2020 15:40:27 UTC] AVideoLog::DEBUG: Stripe IPN endpoint_secret [sk_live_isYK***Fs*******Odf0******dk]
[01-Jun-2020 15:40:27 UTC] AVideoLog::DEBUG: Stripe IPN Invalid signature 
```

your parameter is something like **sk_live_......*
when suppose to be something like this  **whsec_....**

Check it here

![image](https://user-images.githubusercontent.com/18009293/83668950-2cebe500-a5a7-11ea-8696-d782216f92b2.png)

Check your plugin instructions here 

![image](https://user-images.githubusercontent.com/18009293/83669040-4d1ba400-a5a7-11ea-8de2-5dcbadf4a24f.png)


**The SigningSecret will be available after your first purchase attempt, Webhook will be created automatically.**

**Comment by tonuzo** [comment]
That's it! It works now. I had wrong SigningSecret key. 

Thank you so much for your help. I'm happy that it was my mistake and not the application problem. You've done a powerful application and your user support is excellent - and you keep on solving this kind of stupid user mistakes. :) I appreciate your work. 

all the best wishes,
T

**Comment by ronaldod** [comment]
Need to get a paypal donate link for @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
He is already a very good customer :)
