### ISSUE TITLE
SSL Implementation

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#3155]
Hi,

I have everything running smoothly even live stream.
I know how to install Let's Encrypt by using this for Apache
sudo apt install certbot
sudo apt install python3-certbot-apache
sudo certbot --apache --agree-tos --redirect --hsts --staple-ocsp --email you@example.com -d tube.yourdomain.com

I'm just not sure what all the files are I need to add 444 ssl and ssl_certificate to.
I know there's conf files and some sports in the Database.

Thanks

**Comment by DanielnetoDotCom** [comment]
Usually what I do for myself is install the certificate on apache with certbot. then I run certbot for Nginx I reinstall it with on Nginx (DO Not generate a new one).

then I replace the port 443 on nginx.conf to 444

**Comment by D-Spayre** [comment]
Great thank you
