### ISSUE TITLE
Active videos change to embed video

### ISSUE THREAD

**Issue by WGtechy** [WWBN/AVideo#3156]
Greetings, i just notice a bug on my site today. When i play a video it will show another video from youtube.

I further checked the tag in my video dashboard to troubleshoot then i noticed that the type  was changed from video to Embed.

So if i try to play other videos that have the error, they do the same

Please what could be the cause and what can i do to rectify this issue. My site is up to date

Thanks

**Comment by DanielnetoDotCom** [comment]
I need to be able to reproduce this error. not sure how is it happening.

**Comment by WGtechy** [comment]
> I need to be able to reproduce this error. not sure how is it happening.

I did more troubleshoot on the issue. I think the videos were affected because I deleted the categories i assigned them to during the time of encoding in the encoder. So the path to the files changed and the streamer can not play them anymore but the files are still on the server.  
 I hink that is the reason, or do you think something else might cause it

same issue with this case number #3125

**Comment by DanielnetoDotCom** [comment]
I see.

pretty hard to reproduce it. and does not make sense to me.

I review the code and I did not find a reason to replace the videoLink field.

**Comment by WGtechy** [comment]
> I see.
> 
> pretty hard to reproduce it. and does not make sense to me.
> 
> I review the code and I did not find a reason to replace the videoLink field.

More than 50 videos affected. everything was fine till yesterday when some of the videos were just redirecting to a youtube embed video. The affected videos are still taking space on the server but they show embed. So if the player tries to load the video it stops and load a youtube video instead.

**Comment by DanielnetoDotCom** [comment]
If you can tell me how to reproduce it, I will be happy to fix it.

**Comment by WGtechy** [comment]
> If you can tell me how to reproduce it, I will be happy to fix it.

i dont understand what you mean please explain what you mean.

**Comment by DanielnetoDotCom** [comment]
It is happening in your side, and I do not know how it is happening.

I must be able to reproduce it so I can find the error and fix, and make sure it will not happen anymore.
