### ISSUE TITLE
Issues with starting Nginx

### ISSUE THREAD

**Issue by WGtechy** [WWBN/AVideo#3158]
Greetings, I tried installing the Nginx following the instructions on: [https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server]

But when i tried to start the Ngnix with this code: `sudo /usr/local/nginx/sbin/nginx`

I got this error 👎 
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] still could not bind()

What can i do to solve this.

**Comment by akhilleusuggo** [comment]
that's not a problem , just means that your server is already running .
