### ISSUE TITLE
Nginx issue

### ISSUE THREAD

**Issue by WGtechy** [WWBN/AVideo#3159]
Greetings, I tried installing the Nginx following the instructions on: [https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server]

But when i tried to start the Ngnix with this code: sudo /usr/local/nginx/sbin/nginx

I got this error 
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] still could not bind()

What can i do to solve this.

**Comment by akhilleusuggo** [comment]
that's not a problem , just means that your server is already running .
Duplicated Issue https://github.com/WWBN/AVideo/issues/3158

**Comment by WGtechy** [comment]
> that's not a problem , just means that your server is already running .
> Duplicated Issue #3158

But my live chat an live stream is not working when i try to connect to obs

**Comment by DanielnetoDotCom** [comment]
should be something else.

check your Nginx log and also some screenshots to help us understand what is going on.

**Comment by WGtechy** [comment]
> should be something else.
> 
> check your Nginx log and also some screenshots to help us understand what is going on.

Here is the error log `/usr/local/nginx/logs/error.log`

![nginx error log](https://user-images.githubusercontent.com/55572107/83310558-5baf3780-a204-11ea-9c86-a2d491b35cb5.png)

**Comment by akhilleusuggo** [comment]
Your issue description : 

1- inaccurate 
2- Not descriptive 
3- You mixing things up 
4- Logs not showing ANY errors 
5- No screens or anything that helps to indentify any issues .

What's your issue ? Because really , I still don't get it .

`nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)`
Means only one thing : NGINX is Running without problems , and you're trying to start it again , when the file already running .

I see no issues .

**Comment by WGtechy** [comment]
The problem is i cant stream live and the chat is not working. If i try to connect to OBS after adding the server URL and streams key it returns error. Thats my issue
![Screenshot 2020-05-30 09 58 54](https://user-images.githubusercontent.com/55572107/83324386-dd32b400-a25c-11ea-80c1-f27275cf6375.png)

**Comment by akhilleusuggo** [comment]
past your config file , and plugin paramters ( Live )

**Comment by WGtechy** [comment]
![Screenshot 2020-05-30 16 04 40](https://user-images.githubusercontent.com/55572107/83332101-243a9c80-a291-11ea-9b66-31565d0b8271.png)
![Screenshot 2020-05-30 16 04 55](https://user-images.githubusercontent.com/55572107/83332111-2c92d780-a291-11ea-969a-5ccd98938f1f.png)

![Screenshot 2020-05-30 16 43 38](https://user-images.githubusercontent.com/55572107/83332810-30285d80-a295-11ea-8c06-652d5f0fac61.png)

> past your config file , and plugin paramters ( Live )

**Comment by akhilleusuggo** [comment]
lol
Why don't you take a look a wiki . Because you need to replace the [AvideoURL] with your url

https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

Read it carefully , and make it done what you have not done yet , then post the issue .

**Comment by WGtechy** [comment]
funny enough i did that several times but it still return back to AvideoURL. I have followed the wiki and did exactly what is to be done but after configuring it still doesnt work

**Comment by WGtechy** [comment]
its already changed but still doesnt work

**Comment by DanielnetoDotCom** [comment]
@WGtechy check your nginx log file, and also the streamer log and share it here
