### ISSUE TITLE
SecureVideosDirectory Plugin

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3160]
Does it work with YPT Storage ?
Does it work at all ? I mean , I've tested it and still I can download mp4 files . ( and OFC i did configured it , and moved files away from apache2 directory , in my case to another drive ) .

**Comment by DanielnetoDotCom** [comment]
It suppose to work.

Try from an incognito browser without the token

Once you use the token your browser will be whitelisted to watch that video

**Comment by akhilleusuggo** [comment]
but does not protect them from downloading .
I tested it with youtube-dl and works

**Comment by DanielnetoDotCom** [comment]
Download protection is only hls

**Comment by akhilleusuggo** [comment]
then it's somehow useless . Only for embedding , and you added an option for that already to block it .
And I guess does not work with YPT storage .

**Comment by DanielnetoDotCom** [comment]
Yes , it prevents only if someone grabs your video url and try to share somewhere 

The video url is useless outside your site.

For download protection, only the hls format is efective
