### ISSUE TITLE
unlisting a video is not working

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#3162]
**Describe the bug**
If i unlist a video the video is still shown

**To Reproduce**
Pressed the unlist button.
![image](https://user-images.githubusercontent.com/31585599/83189535-71076180-a131-11ea-819f-302d89304812.png)
Cleared also the caches

**Expected behavior**
Not showing up on any of the pages.

**Error Logs**
[28-May-2020 20:18:16 UTC] PHP Notice:  Trying to access array offset on value of type null in /var/www/test3.iwonit.nl/objects/playlist.php on line 328

**Additional context**
Latest pull.

**Comment by DanielnetoDotCom** [comment]
Are you using gallery mode?

Are you sure you are not logged in?

Ulthe expected behavior is that admin can see even unlisted videos . And you can view your own unlisted videos

**Comment by ronaldod** [comment]
It is a weird one. If it is the last in added and then placed in unlisted it is not showing. 
And i logged out it shows.

![image](https://user-images.githubusercontent.com/31585599/83191288-0dcafe80-a134-11ea-86b2-4f00f1c4dc9e.png)


But if i press categories it is not showing .

The error on 328 only appears if a user is not logged in.

I presume that `if ($res) {` on line 327 in playlist.php has to be `if ($data) {`

**Comment by DanielnetoDotCom** [comment]
Sorry I don’t understand.

Are you talking about playlists or in the main page?

**Comment by ronaldod** [comment]
Mainpage.

**Comment by DanielnetoDotCom** [comment]
I am trying to reproduce it here locally and I could not.

can you reproduce it on demo site?

**Comment by ronaldod** [comment]
[demo site](https://demo.avideo.com) admin not working and the test account is out of storage space.
Will take a look tomorrow. Its late here.

**Comment by ronaldod** [comment]
As you have a different layout set i used the direct link.

![image](https://user-images.githubusercontent.com/31585599/83195284-4ec61180-a13a-11ea-8697-075529b2ae8d.png)

**Comment by ronaldod** [comment]
And also more maybe unrelated error :
`[28-May-2020 21:30:02 UTC] PHP Notice:  Undefined variable: channelName in /var/www/test3.iownit.nl/objects/user.php on line 253`

Function is not correct it needs some attention.

**Comment by akhilleusuggo** [comment]
I think you need to disable the options from gallery ( or what ever you're using ) 
![image](https://user-images.githubusercontent.com/52116577/83207732-99588580-a15c-11ea-9108-b493cba34713.png)

**Comment by ronaldod** [comment]
This is found in a default installation. No changes on view. This has to work correctly from the start.

**Comment by akhilleusuggo** [comment]
That's not the case , because from the ''start'' there's no ''First Page Style'' selected .

**Comment by ronaldod** [comment]
Layout of youtube layout is okish but the following of the themes. Pretty messed up.

**Comment by DanielnetoDotCom** [comment]
@ronaldod what theme exactly are you using? no first-page theme?

**Comment by DanielnetoDotCom** [comment]
> And also more maybe unrelated error :
> `[28-May-2020 21:30:02 UTC] PHP Notice: Undefined variable: channelName in /var/www/test3.iownit.nl/objects/user.php on line 253`
> 
> Function is not correct it needs some attention.

thanks fixed

**Comment by ronaldod** [comment]
Then i think for easy purpose the gallery plugin should be enabled by default for privacy and security reason as unlisted is not working with the default settings.

**Comment by DanielnetoDotCom** [comment]
Agree, 

Fix sent
