### ISSUE TITLE
Does the share embed iframe video support the youtube Start= and End= URL extensions

### ISSUE THREAD

**Issue by RasZilan** [WWBN/AVideo#3163]
Hi,

I wonder if you can help me?

I have setup a YouPHPTube site that I was using to stream table tennis League matches.

I have hardware that takes 3 cameras and a scoring system and combines the videos into one live stream that I am broadcasting and archiving.

Our club has a message board and i use an iframe tag on the site to link the videos to my YouPHPTube hosting environment.

Because the video has to be recorded in one go the length can be quite long and so I was wondering if there was any way of using a embeded start and stop time like youtube in the iframe so that i can show individual games within the match without reprocessing the video????

Yours Hopefully
Michael Smith

**Comment by RasZilan** [comment]
Thanks for any help on this, this is an example of what i mean
https://www.youtube.com/watch?v=SZylUYtldno

**Comment by DanielnetoDotCom** [comment]
you can use ?t=10 to start the video in 10 seconds. we do not have an endpoint yet.


![image](https://user-images.githubusercontent.com/18009293/83261743-3b469500-a192-11ea-803f-f5e275310231.png)


![image](https://user-images.githubusercontent.com/18009293/83261782-4a2d4780-a192-11ea-93e2-76adadf2dc74.png)

It also works if you are embedding.

**Comment by RasZilan** [comment]
Hi,

Thanks for your help/response!
I was wondering what the t= extension was for?!?!?

on my setup right clicking a video and "copy video url at current time" always return t=0 no matter how far through the video i am.

using this i get:
https://video.forestrowfalcons.com/YouPHPTube/video/18/ttvideo64gbleft-videohd720p?channelName=5eb2aee48eb6f?t=0

If I inject a time into the URL eg
https://video.forestrowfalcons.com/YouPHPTube/video/18/ttvideo64gbleft-videohd720p?channelName=5eb2aee48eb6f?t=30
it is ignored! and starts at the beginning...

I have several plugins installed could one of these be causing the issue?

Yours
Michael Smith

**Comment by RasZilan** [comment]
This is what I have Installed/Enabled...:

API (API) - Version: @1.0
Chromecast (Chromecast) - Version: @1.0
Hotkeys (Hotkeys) - Version: @1.0
Live (Live) - Version: @3.0
LiveChat (LiveChat) - Version: @1.0
LiveUsers (LiveUsers) - Version: @1.0
MobileManager (MobileManager) - Version: @1.0
NextButton (NextButton) - Version: @1.0
SecureVideosDirectory (SecureVideosDirectory) - Version: @1.0
SeekButton (SeekButton) - Version: @1.0
SendRecordedToEncoder (SendRecordedToEncoder) - Version: @1.0
TheaterButton (TheaterButton) - Version: @1.0
VideoLandscapeFullscreen (VideoLandscapeFullscreen) - Version: @1.0
VideoResolutionSwitcher (VideoResolutionSwitcher) - Version: @1.0
VideoTags (VideoTags) - Version: @2.0
VideoThumbnails (VideoThumbnails) - Version: @1.0

**Comment by DanielnetoDotCom** [comment]
The correct URL is https://video.forestrowfalcons.com/YouPHPTube/video/18/ttvideo64gbleft-videohd720p?channelName=5eb2aee48eb6f&t=300

NOT https://video.forestrowfalcons.com/YouPHPTube/video/18/ttvideo64gbleft-videohd720p?channelName=5eb2aee48eb6f**?t=300**

try form an incognito browser. if you try it from the same browser it will show your last view time, not the time in the URL

**Comment by RasZilan** [comment]
Thanks!

https://video.forestrowfalcons.com/YouPHPTube/video/18/ttvideo64gbleft-videohd720p?channelName=5eb2aee48eb6f&t=300

works!!! , good to know!!

however I note that even in incognito browser the right clicking of the video and selecting :
Copy Video URL at current Time
always return a URL where t is =0
and the URL is wrong as it is ?t=0
ie
https://video.forestrowfalcons.com/YouPHPTube/video/18/ttvideo64gbleft-videohd720p?channelName=5eb2aee48eb6f?t=300
whilst I can get round this I though I should mention this!

Thanks for your help this has made my life a lot easier!

**Comment by DanielnetoDotCom** [comment]
Hi

first update your site to version 8.9

than check if this error disappear 
![image](https://user-images.githubusercontent.com/18009293/83438273-832a1e00-a417-11ea-913a-0b6fff7284d2.png)

this is probably what is causing the time update error.
