### ISSUE TITLE
How do I make a agreement

### ISSUE THREAD

**Issue by nsturtz2** [WWBN/AVideo#3165]
I want people who use my site https://video.sturtz.ml know that all videos pulled off of Youtube are the owner's property and that I do not claim any ownership of the videos on my site?

**Comment by tonuzo** [comment]
You can use SignUpAgreement paid plugin. Or maybe use TopMenu-plugin to make a new menu item.

**Comment by nsturtz2** [comment]
I found something
the show message on login and signup setting
