### ISSUE TITLE
Root Domain Redirect Issue

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#3166]
Hi,

If I go to www.DOMAIN.ca it directs to https://www.DOMAIN.ca - Perfect
If I go to DOMAIN.ca it directs to https://DOMAIN.ca - This site is not secure
I can not get it to redirect to https://www.DOMAIN.ca.
I tried redirects in the youphptube.conf and /var/www/YouPHPTube/.htaccess but nothings seems to work for me. 

Any ideas on how I can fix this?

Thank you

**Comment by akhilleusuggo** [comment]
This question has nothing to do with this project , but apache .
On this section there's a small guide .
https://github.com/WWBN/AVideo/wiki/Redirect-http-to-https

**Comment by D-Spayre** [comment]
Thank you
