### ISSUE TITLE
Share Buttons in the Right CLick Menu on Embedded Videos

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3167]
Add share Button to the menu u get when right clicking on a embedded video.

<img src="https://static.buddylist.co/richtclickembedshare.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
What exactly share button? like this?
![image](https://user-images.githubusercontent.com/18009293/83263060-5fa37100-a194-11ea-98ed-519034299888.png)

**Comment by akhilleusuggo** [comment]
Also if possible '' loop ''

**Comment by DanielnetoDotCom** [comment]
Improvements sent

make sure you clear your cache folder

**Comment by akhilleusuggo** [comment]
I see no difference at all .
I did clear the server cache and browser cache .

**Comment by DanielnetoDotCom** [comment]
you should have a difference. 

also, make sure the PlayerSkins plugin is enabled

**Comment by DanielnetoDotCom** [comment]
Tested on this embed link https://demo.avideo.com/videoEmbed/251/video-automatically-booked-1

![image](https://user-images.githubusercontent.com/18009293/83422045-5538df80-a3ff-11ea-8cdb-f97c561f8cb2.png)

![image](https://user-images.githubusercontent.com/18009293/83422118-700b5400-a3ff-11ea-80c1-40b362245895.png)

**Comment by DanielnetoDotCom** [comment]
New fancy updates, also the loop button on the video control bar

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/83444515-2f89f580-a454-11ea-8acc-81fc57c7501a.png)

Maybe this skin is not supported ?

**Comment by DanielnetoDotCom** [comment]
Hi

It should be supported in any skin

FYI, this update is for the embed code only 

but if you enable the PlayerSkins you can see the loop button on the control bar 
![image](https://user-images.githubusercontent.com/18009293/83445035-a908f000-a422-11ea-8f9c-af26b0addc8f.png)

**Comment by akhilleusuggo** [comment]
Yes I do . But where is the point to share an embed link , when it's already shared ( embedded )

The idea should be , to have it on the skin , so people could share it faster . Sharing a shared video starts to make less sense .

**Comment by DanielnetoDotCom** [comment]
No, 

I add the social media sharing, on embed, NOT the embed code

also I add the loop option.

but it is not clear for me what are you looking for. maybe I am misunderstanding you.

also what browser are you using? I am testing only on chrome for now.

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom  The Share buttons look great!!

The Purpose for Share Buttons? @akhilleusuggo 

So You can make it easy for others to put your video on their social post or embed it to a blog.

Your not sharing the Re embed code not even sure what u meant by that. 

The Right Click Menu Share Buttons are there so when you embed your video onto a website or blog post people can right click on it and add it to their stuff easier.

**Comment by akhilleusuggo** [comment]
I got you . Also would be cool to have this on the main streamer site . But I've got your point .
