### ISSUE TITLE
Set signed users automatically to user group? 

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3168]
Hi

Is it possible to set user automatically to a specific user group when signed up? 

E.g. if you want to give free videos but you have to be signed in..

edit: 

And don't want the whole site to be in behind the sign in gate.

Br,
T

**Comment by DanielnetoDotCom** [comment]
I just look into the code and we do not have a default user group yet.

it would be a good feature to add. and we may do it in the future. if you need this feature right the way and want to sponsor it you can hire us emailing me at developer@youphptube.com

**Comment by wetubeclub** [comment]
Hello
I'm interested too
I have sent you an email
Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
Hi

now you can set it up

![image](https://user-images.githubusercontent.com/18009293/83444555-f173de00-a421-11ea-8b9e-9d6b397b57e7.png)

**Comment by tonuzo** [comment]
Awesome! Thank you.
T

**Comment by tonuzo** [comment]
Hi!
I found a bug on this. If you Social Login (facebook), it doesn't set user group automaically. I hope this can be fixed.

T

**Comment by DanielnetoDotCom** [comment]
Hi, this may do the trick

**Comment by tonuzo** [comment]
Yes, it works now. Thank you!
