### ISSUE TITLE
move videos to another location

### ISSUE THREAD

**Issue by daoguey** [WWBN/AVideo#3170]
so i followed this: https://github.com/WWBN/AVideo/wiki/Can-I-store-my-videos-in-another-location

for moving my videos folder in AVideo and AVideo-encoder to a secondary hdd

Now when i do this my website starts to have missing links and breaks the whole website. I was looking online and it had to do with permissions for the drive. can you explain how and what kind of permissions it needs to run properly with a symbolic link for the videos folder?

thank you

**Comment by akhilleusuggo** [comment]
I think you need to give rights to apache2 to get access to it .
`chown www-data:www-data -R /yourdirectory
`
But I'm not sure , maybe you need the plugin SecureVideosDirectory (https://youphp.tube/plugins/)
But I'm not sure , but defenetly apache2 need the permissions

**Comment by DanielnetoDotCom** [comment]
@daoguey 

when this happens try this solution 
https://github.com/WWBN/AVideo/issues/3047#issuecomment-627074572

**Comment by daoguey** [comment]
closing as this was solved.
