### ISSUE TITLE
Plug in Sign up agreement

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#3171]
Hello,
displays a piece of code in the popup window in the plugin agreement we have some solution for that?
Thank you
Ilias
![agreements](https://user-images.githubusercontent.com/60543030/83321835-e880e200-a252-11ea-916c-f6209485df41.jpg)

**Comment by tonuzo** [comment]
I had the same problem and it was fixed. Download the plugin again and install.

**Comment by wetubeclub** [comment]
i did what you told me and it works normally now!!
thank you very much!!
