### ISSUE TITLE
Subscriptions plugin

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#3172]
Hello,
I think there is a problem with plugin subscription at least for me!!
and what I mean:
I have three different shots on the site,
after the time period of the plan expires, the renewal is done automatically but the plan is not renewed to the user and I have to do it manually after notifying the user that while he paid he does not have access
this happens in all three shots via paypal and stripe!

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
Please see if you can save the log file in the renew day. 

Also if you can get the time the renew was executed, so we can check if was any error using the time to filter the log

**Comment by wetubeclub** [comment]
Hello Daniel
I will send you the paypal log in your email if you agree!
I'm talking about May 28th

Thank you
Ilias

**Comment by wetubeclub** [comment]
about paypal  log files
I took a look everything looks normal
what I want to ask is:
when registering, the user gave the email test@test .com
made the renewal via paypal but his email to paypal is example@example .com different from the registration email
perhaps this is the reason why the user's subscription tab was not updated?

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
Yes on my email is fine, 

I mean the streamer log file.
do you know what time Paypal process the payment?

**Comment by wetubeclub** [comment]
Paypal transaction 
30 May 2020 at 13:34:24 CEST

now for the streamer log file it would help me if you could see it directly to my server
i dont now where is !

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
Was the value for 1.5 EUR? 

I found something, I will update your site and please keep your eyes open;

did you find the same issue on stripe?

**Comment by wetubeclub** [comment]
yes it is at 2.5 €
yes it is in the stripe I had the same problem from two users that while they paid their subscription was not renewed!

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
I see.

After this update please keep your eyes open and let me know about any issue like that.

**Comment by wetubeclub** [comment]
I will upgrade now
thank you very much daniel
you are the best professional I have ever met
with love for what you do responsibility and reliability
keep it up and the community will support you to be sure of that!!!

Thanks 
Ilias

**Comment by DanielnetoDotCom** [comment]
FYI, it is upgraded, I did it for you.

thanks for your words!

**Comment by wetubeclub** [comment]
we have been working together for a year now and more
when I needed you you were near me
This counts
be well!
Ilias
