### ISSUE TITLE
Mobile App Live Error

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#3173]
The apps seems to work except for the Live section.  I'm using version Apr.26, 2020.
When I click on Live it's just a Black screen, when I click on the video icon the camera comes on for a second then shows this error.
"Connection failed.  Connect error, failed to connect to www.DOMAIN.ca/External-IP (port 1935) from /192.168.1.177 (port 40582) after 3000ms: isConnected failed: ECONNREFUSED (connection refused)

Thanks

**Comment by DanielnetoDotCom** [comment]
maybe its not the app, maybe is your livestream server

can you test to make a live on the demo site?

**Comment by D-Spayre** [comment]
Tried the demo site, I get this error. "Connection failed. Error configure stream, publish permitted failed".
I'm using a Note 10.

Thanks

**Comment by D-Spayre** [comment]
Tried using a Samsung Galaxy Tab A 8, on site and demo site it just says Disconnected after a couple of seconds.

**Comment by DanielnetoDotCom** [comment]
Hi, on the demo site I detect a misconfiguration (probably someone edit the plugin erroneous)

but it is fixed now and should work.

can you please try again?

**Comment by D-Spayre** [comment]
Yep it works now.

So what would cause mine not to work.  My Live stream works just not when using the app.

Thanks

**Comment by DanielnetoDotCom** [comment]
Check your log files, streamer and nginx log

**Comment by D-Spayre** [comment]
This is what I'm seeing in youphptube.access.log.

127.0.0.1 - - [31/May/2020:21:57:26 -0300] "GET /plugin/Live/stats.json.php HTTP/1.0" 200 4494 "-" "-"
EXTERNAL-IP - - [31/May/2020:21:57:26 -0300] "GET /notifications.json?user=USER&pass=26847FE569524963185452D5E68E4523 HTTP/1.1" 200 1595 "http://localhost/" "Mozilla/5.0 (Linux; Android 10; SM-N975W Build/QP1A.190711.020; wv) Apple$

**Comment by D-Spayre** [comment]
Figured out that every time I reboot my server Nginx stops working.
I followed these instructions "https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server" then realized it doesn't get you to delete the default Nginx Config file located in /etc/nginx/conf.d and replace it with the new config.  After replacing the config file its all working.

Thanks
