### ISSUE TITLE
Email won't configure/send

### ISSUE THREAD

**Issue by 1tpg1** [WWBN/AVideo#3174]
![mail2](https://user-images.githubusercontent.com/16628564/83341417-3fb59f80-a2b1-11ea-89c4-50236d619f6e.jpg)

I've tried all combinations, changed my email, and still can't get the test to work.
Where can I see a log file of what's happening?

**Comment by akhilleusuggo** [comment]
did you read the mesage error ?
Did you visited the link on the error ???

PORT 587 is for tls and NOT ssl , you should change ssl to tls , and allow less secure application on gmail . 

https://github.com/WWBN/AVideo/wiki/Setting-up-AVideo-Platform-to-send-emails#allow-less-secure-apps-to-access-your-gmail-account

**Comment by 1tpg1** [comment]
I did all that. That screenshot was just the last combination I tried.
I will set it back to TLS/587, wait, and see what happens.
It won't work with my own mail server either.

**Comment by DanielnetoDotCom** [comment]
Hi

for Gmail, tls/587 is the correct setup

make sure you do not forget to Allow less secure apps to access your Gmail account

**Comment by 1tpg1** [comment]
Tried all that, still not working.

**Comment by akhilleusuggo** [comment]
did you white-listed the IP of your server ?
You should get an email : Something trying to access your gmail account ( a warning ) . You should tell gmail ''YES'' , it was me .
You wont be able to send email without white-listing the IP

**Comment by 1tpg1** [comment]
I got it working with my own mail server. Good to avoid Google.

**Comment by MyBlissIT** [comment]
> I got it working with my own mail server. Good to avoid Google.

Hi, how did you achieve this? I cannot seem to succeed and I do not want to use GMAIL

**Comment by DanielnetoDotCom** [comment]
For your site Gmail is just fine.

if you want to use your domain to send emails,  try this free solution https://forwardemail.net/
