### ISSUE TITLE
Wrong label issue

### ISSUE THREAD

**Issue by 1tpg1** [WWBN/AVideo#3175]
![google](https://user-images.githubusercontent.com/16628564/83341439-84413b00-a2b1-11ea-82a4-66f35d90a705.jpg)

Small error where it says facebook instead of Google.

**Comment by akhilleusuggo** [comment]
Not a bug , but a typo . And that section on admin is depricated . Use plugins instead . 
![image](https://user-images.githubusercontent.com/52116577/83343193-c5603c00-a2ff-11ea-920a-028e9516af9a.png)
