### ISSUE TITLE
Case sensitive VideoResolutionSwitcher

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3177]
Is there anyway to enable case sensitive for the quality selector ?
When indicate HD , the player does display hd . LQ = lq

Anyway to keep them on capital letter ?

**Comment by ronaldod** [comment]
It could be done it has to do with how he match the resolution  name with the directory's where the mp4 lives are created. Case sensitive. Can take a look at it later this week.

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo not sure if I understand.

are you using labels for VideoResolutionSwitcher?

It should show whatever you put on the label
![image](https://user-images.githubusercontent.com/18009293/83446067-7bbd4180-a424-11ea-833a-3a8310e45ddb.png)

**Comment by ronaldod** [comment]
In text it is in capitals but in the videojs it is lowercase.

**Comment by DanielnetoDotCom** [comment]
Videojs define it to be lowercase, but I sent an update that may fix it

![image](https://user-images.githubusercontent.com/18009293/83452382-f9864a80-a42e-11ea-852f-1e954ad02514.png)

**Comment by akhilleusuggo** [comment]
Not working for me . Cleared caches and nothing .

**Comment by DanielnetoDotCom** [comment]
did you download the plugin again?

**Comment by akhilleusuggo** [comment]
you haven't mentioned that . Downloaded and works .
You really should think about something when you release an update to the plugins . Email is more then enough , at the lease we know that the plugin has being updated.
