### ISSUE TITLE
on_publish ( online stream ) offline status

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3178]
https://github.com/arut/nginx-rtmp-module/issues/1186

This is could be a solution for all the people having the status OFFLINE while the stream is ON  ( me included ).
And I can't believe @DanielnetoDotCom does use redirect HTTPS on vhost . Definitely you have added some exceptions to some paths , or you're having different configuration .

And this explains why . http://live.avideo.com:444/live/
You do not redirect your demo.avideo.com to https only . You having diferent server , that does accept http and have no auto-redirect to https .

I hope you can take a look once more into this

**Comment by DanielnetoDotCom** [comment]
Yes, that way makes it easier.

the main problem with this is if you use Cloudflare it will not allow you to connect in your RTMP port.

so if you create a subdomain and do not enable the Cloudflare proxy you should be able to connect into the RTMP

and for live.avideo.com I use the lets encrypt SSL

**Comment by akhilleusuggo** [comment]
I'm not using cloudflare .
I have setup a new server . stream.fkldjs.com
Still the same problem . the problem is on `on_publish`

The thing is the stream DOES work , but showing offline if apache does the https redirect .
Removing it does fix the issue , but why should I not redirect it .

**Comment by DanielnetoDotCom** [comment]
You cannot redirect for Nginx

and the on_publish MUST be HTTP, NOT HTTPS

**Comment by akhilleusuggo** [comment]
yes , but that the call , but receiving the data is on https 
I'm talking about demo.avideo.com/plugin/Live/on_publish.php

**Comment by DanielnetoDotCom** [comment]
I am not sure what you mean and what you are looking for but here is my demo site nginx.conf

```
worker_processes  1;
error_log  logs/error.log debug;
events {
        worker_connections  1024;
}
rtmp {
    server {
        listen 1935;
        allow play all;to put the HLS video manifest and video fragments
        application live {
                allow play all;
                live on;
                hls_fragment 10s;
                on_publish http://live.avideo.com/plugin/Live/on_publish.php;
                on_play http://live.avideo.com/plugin/Live/on_play.php;
                on_record_done http://live.avideo.com/plugin/Live/on_record_done.php;


        exec ffmpeg -i rtmp://localhost/live/$name 
                -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:240 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1200k -b:a 96k -r 20 -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_low  
                -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:480 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 2400k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_mid;  

        }

        application adaptive {
            live on; 
            hls on; 

            hls_path /HLS/live;
            hls_nested on;

            allow play all;
            allow publish 127.0.0.1;
            deny publish all;

            hls_variant _low BANDWIDTH=400000;
            hls_variant _mid BANDWIDTH=2100000;
        }
    }
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    server {
        listen 8080;
        server_name localhost live.avideo.com;
        my-stream-key/index.m3u8"      
        location /live {
            add_header 'Cache-Control' 'no-cache';
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length';
            if ($request_method = 'OPTIONS') {
                    add_header 'Access-Control-Allow-Origin' '*';
                    add_header 'Access-Control-Max-Age' 1728000;
                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                    add_header 'Content-Length' 0;
                    return 204;
            }
            types {
                    application/vnd.apple.mpegurl m3u8;
            }
            alias /HLS/live;
        }
        location /stat {
                rtmp_stat all;
                rtmp_stat_stylesheet stat.xsl;
        }
        location /stat.xsl {
                root html;
        }
        location /control {
                rtmp_control all;
        }    
        location / {
                root   html;
                index  index.html index.htm;
        }   
    
        listen 444 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/live.avideo.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/live.avideo.com/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    }
}

```

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I still don't get 
```
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
```

Are you using apache to host the streamer site ? or nginx only ?

**Comment by DanielnetoDotCom** [comment]
I am using the same files that certbot created for apache on Nginx. I do not deploy a new certificate.

**Comment by DanielnetoDotCom** [comment]
> hls_fragment 10s; , useless with the transcoding -hls_time

can you explain it more?

another thing, I am trying to set up a DVR on a live , but for some reason, it does not work. any idea?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom the `hls_fragment 10s;` is usefull only when you're not transcoding , since the file will be received not fragmented . On this way you're making it `#EXTINF:10.000,`

But since you're transcoding , the hls_fragment are already set on the encoder . `-hls_time 6` .
If you remember I've made already a pull request and put 6s for each fragment , so the server doesn't have to wait extra 2 seconds to join multiple fragment to get served .

The DVR should work if you add `hls_playlist_length 10m;` This should play the last 10mn ( or get saved and ready to play ) . But honestly I don't know if you have added this option into the player .

Also will need the option `hls_nested on;` to not over-write other index.ts from other streamers .
Take a look here . https://github.com/arut/nginx-rtmp-module/wiki/Directives#hls_playlist_length

It's good idea the DVR , will store the files . I've tested it , and not working because of the video.js player . I don't now much about how it works , but I don't see the player bar to get back or forward in time .

**Comment by DanielnetoDotCom** [comment]
FYI we already have the videojs-dvrseekbar https://github.com/WWBN/AVideo/tree/master/plugin/Live/videojs-dvr

**Comment by DanielnetoDotCom** [comment]
I added the DVR info, looks like I can pause but there is no progress bar

**Comment by akhilleusuggo** [comment]
there's something that I've being reading , that those files should be kept on tmps but I didn't understood well .

BTW , this is actually interesting , reminds me of how twitch work .
https://github.com/arut/nginx-rtmp-module/wiki/Directives#relay

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Advancing !! 

![image](https://user-images.githubusercontent.com/52116577/83790415-d662d180-a6a0-11ea-9fbc-796cff351425.png)

Defenetly something missing .

What I did is : 
![image](https://user-images.githubusercontent.com/52116577/83790462-eaa6ce80-a6a0-11ea-979f-df63c2b3f605.png)

But I'm still not able to click on it . The player field is missing .

**Comment by DanielnetoDotCom** [comment]
Looks like does not need an extra plugin 
https://stackoverflow.com/questions/53876500/how-to-implement-videojs-dvrseekbar-plugin-correctly

**Comment by DanielnetoDotCom** [comment]
Looks awesome now :)

![image](https://user-images.githubusercontent.com/18009293/83796796-fa5ded00-a677-11ea-8ba6-4c060d67b9c5.png)

**Comment by akhilleusuggo** [comment]
really awesome !
Next to do is with adaptive steam .
since does create directories /low /SD /HD , those could be concatenated and send to streamer site ( without re-encoding them ) , as hls folders 

![image](https://user-images.githubusercontent.com/52116577/83797533-7b82a780-a6ab-11ea-9460-11f4ffeb57fa.png)

The only thing needed is to give a prefix name as on the AVideo hls platform ( index1.ts , index2.ts , instead of 1.ts 2.ts )

That gonna make the videos basically be able to playback in few seconds after the stream has finished .

**Comment by DanielnetoDotCom** [comment]
I tested with adaptative and it works also

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I'm sure you did't understood well my proposition .
I'm talking about SendStream to Streamer site . 

> since does create directories /low /SD /HD , those could be concatenated and send to streamer site ( without re-encoding them ) , as hls folders
> The only thing needed is to give a prefix name as on the AVideo hls platform ( index1.ts , index2.ts , instead of 1.ts 2.ts )
> 
> That gonna make the videos basically be able to playback in few seconds after the stream has finished .

**Comment by DanielnetoDotCom** [comment]
I am not sure yet what you mean.

**Comment by akhilleusuggo** [comment]
ok , the dvr does save the files on a directory . /HLS/Live/ID/Quality ( low , sd , HD ) , right ?
Those folders could be transferred to AVideo/videos/ without the need of a transcode .

The only function that need to be added is , when stream goes online , create an ID video / title ( from stream ) / Description ( from stream ) etc etc , exactly like if a video is being transferred from encoder .
It's what all the platforms does .

**Comment by akhilleusuggo** [comment]
A quick request before I start looking at other things ( I'm in love with nginx ) .

Can you add the timer ?
![image](https://user-images.githubusercontent.com/52116577/83799287-41ff6b80-a6ae-11ea-9b8c-cf9a81edf516.png) timer missing 

Something like this should be ok . 
![image](https://user-images.githubusercontent.com/52116577/83799444-796e1800-a6ae-11ea-9322-891a13669a7b.png) Something like this OR 

![image](https://user-images.githubusercontent.com/52116577/83799482-87bc3400-a6ae-11ea-8592-a52b465eae5d.png)


One last thing : Can you remove the playback speed on livestreams? I just don't know what is the purpose of it . 

![image](https://user-images.githubusercontent.com/52116577/83799762-f600f680-a6ae-11ea-8759-266fec6d5ea4.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I am not sure how to add a timer, I will research

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Also enable if possible SeekButton (SeekButton) ( to go back and forward ) . 
![image](https://user-images.githubusercontent.com/52116577/83806899-de2f6f80-a6ba-11ea-991f-ba440637b356.png)
