### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#3179]
Hello 
To my channel the playlists do not appear
any help for this?

Thank you
Ilias
![playlists](https://user-images.githubusercontent.com/60543030/83362999-23d7f980-a396-11ea-9703-42dd100e8d96.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, can you please update your website and try again?

I released a fix related to it today.

let me know if it resolves.

**Comment by wetubeclub** [comment]
thank you Daniel working now!!

**Comment by DanielnetoDotCom** [comment]
Awesome !

Thanks for letting me know
