### ISSUE TITLE
Limit video quality

### ISSUE THREAD

**Issue by 1tpg1** [WWBN/AVideo#3180]
I only want the lowest quality of video - that way I can save space.
As I understand it, when I upload a video, it creates 3 different versions/files.
How can I limit the uploads to only the lowest quality?

**Comment by ronaldod** [comment]
Yes there is an option. You can find those in the customize Advanced.
![image](https://user-images.githubusercontent.com/31585599/83375779-4d157b80-a3d0-11ea-9fd4-2f8705584219.png)

**Comment by 1tpg1** [comment]
Thanks...for those who didn't know where that was, it's under plugins/CustomizeUser (CustomizeUser)/edit parameters

**Comment by ronaldod** [comment]
@1tpg1 
nope it is in the:
![image](https://user-images.githubusercontent.com/31585599/83395077-f7ee5f80-a3f9-11ea-9e6f-f6f7e0fd97c9.png)
In the CustomizeUser plugin are User settings.

**Comment by 1tpg1** [comment]
Whoops Thanks.
