### ISSUE TITLE
1st page filtering to a specific channel!

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3181]
The 1st page always has a default channel filter applied,ideally there should not be any filter as the video randomization is lost.

If not atleast we should have the same category videos filter.
Please look into it
If i have an option to remove the default filter,please guide me

**Comment by ronaldod** [comment]
You can use some plugins for first page options like Gallery. Do not use the youtube as first page  that one is going to be removed. In the Gallery there are settings to test and play with.

**Comment by vraghavans** [comment]
thanks for the tip!!
Looks much better actually.
Cheers!

**Comment by vraghavans** [comment]
Hi!Do we have a solution for this please

**Comment by DanielnetoDotCom** [comment]
@vraghavans I do not understand what is the current issue.

**Comment by vraghavans** [comment]
Dear Daniel,
the video we choose to play from the home screen is selected as the default channel,and only videos of the encoder are shown in the auto play.Ideally the play next should be all related videos from any encoder.plese find below screen shot.

![image](https://user-images.githubusercontent.com/65802024/85630294-00e8ee80-b691-11ea-81c4-d2a634051073.png)

**Comment by DanielnetoDotCom** [comment]
Not sure but try uncheck addChannelNameOnLinks

![image](https://user-images.githubusercontent.com/18009293/85902510-93e17000-b7da-11ea-97cc-21d5b4c54214.png)

**Comment by vraghavans** [comment]
yup,that did the trick,thanks! a lot!!
