### ISSUE TITLE
Sharing to Instagram and downloading from instagram

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#3182]
I had someone try and embed videos from instagram and the error message says that instagram refused to connect.  So I noticed that we don't have a share with instagram button under share, and was wondering is that's whats causing instagram to refuse to connect. 

I've never tried to embed a video, is it possible to embed from other platforms or is that just available from youtube?

**Comment by DanielnetoDotCom** [comment]
No, it is not related.

about download from Instagram, we use youtube-dl https://github.com/ytdl-org/youtube-dl .

Looks like they do not support instagram
