### ISSUE TITLE
On some browsers, the share button below the videos is not displayed.

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#3183]
On some browsers, the share button below the videos is not displayed.

I tested it with the Epic Bwoser and with Firefox on Linux Mint

While the page is loading, it is displayed but then disappears

![image](https://user-images.githubusercontent.com/52116237/83449192-79bea700-a453-11ea-83a7-c2660e8a3a99.png)

![image](https://user-images.githubusercontent.com/52116237/83449216-83480f00-a453-11ea-8979-241e85841c12.png)

**Comment by DanielnetoDotCom** [comment]
the thing is, share a video is an option

![image](https://user-images.githubusercontent.com/18009293/83534348-1bcba700-a4c7-11ea-9a42-7e2b65698943.png)

### userCanAllowFilesShare
![image](https://user-images.githubusercontent.com/18009293/83534478-40278380-a4c7-11ea-8f1b-e85eced0f4a0.png)

### userCanAllowFilesShareSelectPerVideo
![image](https://user-images.githubusercontent.com/18009293/83534578-69481400-a4c7-11ea-95c7-012b7e7fa0a0.png)

**Comment by akhilleusuggo** [comment]
how can we make the share videos automatic by default , when creating account .
default = share video

**Comment by Donnerstein** [comment]
I do not mean that. Sharing enabled, it only affects some browsers.

**Comment by DanielnetoDotCom** [comment]
@Donnerstein sorry it is not clear to me what is the issue.

@akhilleusuggo right now it is not possible, it will require some code change.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom that would be great if it were possible .

What he means , is that the share button is not compatible with all browsers .

**Comment by Donnerstein** [comment]
@DanielnetoDotCom 
It is often difficult for me to explain in English.
@akhilleusuggo is right.
I try to explain it with pictures.

Google Chrome, Windows 7
![image](https://user-images.githubusercontent.com/52116237/83654898-05544700-a5be-11ea-9b83-3036e27eebae.png)


Firefox Windows 7
![image](https://user-images.githubusercontent.com/52116237/83654999-2452d900-a5be-11ea-9ec3-479c9dfdec70.png)


Epic Browser Windows 7
![image](https://user-images.githubusercontent.com/52116237/83655114-4c423c80-a5be-11ea-8da5-fb3d1882030f.png)

Firefox Ubuntu
![image](https://user-images.githubusercontent.com/52116237/83656436-d5a63e80-a5bf-11ea-89a7-d0c00e09bd20.png)

Firefox Linux Mint
![image](https://user-images.githubusercontent.com/52116237/83656547-fa021b00-a5bf-11ea-8ff8-45bd85104b61.png)


The page settings have not been changed. Video sharing is enabled. But the button is not available in Firefox, for example on Linux mint.

**Comment by Donnerstein** [comment]
@DanielnetoDotCom 
It seems to be the case with all versions.
![image](https://user-images.githubusercontent.com/52116237/83914293-43de3300-a771-11ea-8085-0d850603da07.png)

**Comment by Donnerstein** [comment]
@DanielnetoDotCom

**Comment by Donnerstein** [comment]
In the following combination
Linux mint 19 MATE 64 bit and firefox 72.0.1 (64 bit)

**Comment by DanielnetoDotCom** [comment]
Hi

As I can see the resource was blocked by your browser (client)

and a JS error (intercept.js) from something that I have no idea where it comes from.

you must investigate both problems on your side. looks like both are problems created by your client.

![image](https://user-images.githubusercontent.com/18009293/84075111-fa2c5d00-a9a9-11ea-8a36-d3972b6a3630.png)
