### ISSUE TITLE
Live stream to a user group don't show up on navbar

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3185]
Hi

1. I can't get live streaming to show up on a user group. 

On live stream page I activate a user group and save. It doesn't show up on navbar icon to users in the user group.

When I make it public, it works. But of course it's public and that's not what I want.

![image](https://user-images.githubusercontent.com/63721378/83488197-1b2a1500-a4b5-11ea-92f8-75fb8b65ed37.png)

edit:
2. Also you can go to live URL and watch LIVE Stream even though the live stream has set NOT Public. I'm quite sure this has been working right before..

**Comment by DanielnetoDotCom** [comment]
Not sure, can you reproduce it on demo site?

what is your site URL?

**Comment by tonuzo** [comment]
Yes, I reporduced it in your demo site.

1. I set admin to Premium Group.

2. Started live stream. 

3. Saved live stream Premium Group on

--- > Live not visible on navbar

4. Saved live stream public. 

--- > Live visible on navbar

**Comment by DanielnetoDotCom** [comment]
I just try on the demo site and it works

![image](https://user-images.githubusercontent.com/18009293/83637438-036a9380-a57e-11ea-84e8-80ac926e2a7a.png)

**Comment by tonuzo** [comment]
Yes it works if you have set it public as seen on pic.


![image](https://user-images.githubusercontent.com/63721378/83638024-31b59680-a5b1-11ea-87c1-35e787315dbe.png)

**Comment by tonuzo** [comment]
Ok it works. I was unlisting it incorrectly.. Thank you!
