### ISSUE TITLE
Force login to be EMail doesn't work

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3186]
![image](https://user-images.githubusercontent.com/63721378/83488698-f71b0380-a4b5-11ea-8c81-72eb40bf8f4f.png)

When I check the ForceLoginToBeTheEmail in CusitomizeUser-plugin it doesn't change the login behavior. Email login doesn't work but when I fill the field with Username, it works.

![image](https://user-images.githubusercontent.com/63721378/83488955-5bd65e00-a4b6-11ea-94d9-f11298aae1c4.png)

**Comment by DanielnetoDotCom** [comment]
if you are admin you can do everything. even create any type of username

**Comment by tonuzo** [comment]
Yes. But I try to set users to use email as login. It´s more common way to log in and easier to remember than your user name.

**Comment by DanielnetoDotCom** [comment]
@tonuzo I do not understand...

Users should only be able to use emails to signup. only admins can use emails and usernames

**Comment by tonuzo** [comment]
Not signUP but Login.

T

**Comment by DanielnetoDotCom** [comment]
Yes, I had to keep this, because if enable this option later or by mistake you will be not able to connect into the site anymore

**Comment by tonuzo** [comment]
Ok, I see. Thanks.
