### ISSUE TITLE
Supported video formats

### ISSUE THREAD

**Issue by jimhtwong** [WWBN/AVideo#3188]
What video and audio file formats can support?

Can we say the video formats suppported by FFmpeg are supported by YouPHPtube?

**Comment by akhilleusuggo** [comment]
Is not what format are supported by FFmpeg or YouPHPTube , the question is : 
What format does the HTML5 supports ?

This has nothing to do with the script it self , but the device you're using and the supported format on HTML5 and your browser . Device to decode the codecs (formats/extensions) and HTML5 supports on the browser.
Also the version of the browser will play a big roll .

You can google for more information .
