### ISSUE TITLE
How do I CHANGE http://ipserver/YouPHPTube to http://mydomain.com 

### ISSUE THREAD

**Issue by kemoi-kiptoo** [WWBN/AVideo#3189]
How do I do this? I purchased a domain name.. kindly give me step by step instructions if possible I am kind of new in this

**Comment by akhilleusuggo** [comment]
google about apache2 vHosts

**Comment by kemoi-kiptoo** [comment]
@akhilleusuggo What do I do afterwards? I am  not even getting relevant procedures there.

**Comment by akhilleusuggo** [comment]
this is the easiest and simpliest tutorial I've got for you . ( Something that you could have done yourself ) 
https://www.ostechnix.com/configure-apache-virtual-hosts-ubuntu-part-1/

Issues here are related to AVideo script and issues , not how to use apache2 basics . Follow the guide , and you should have your domain name setup 💯

**Comment by kemoi-kiptoo** [comment]
@akhilleusuggo I am not sure if you understood my question. I said I already purchased a domain name but I do not know how to change VPS IP address to domain name so that I can access my youphptube using domain name. http://ipserver/YouPHPTube to http://mydomain.com

**Comment by akhilleusuggo** [comment]
Your VPS from daniel ? Or by your self ?

If by yourself , then read at the least what I've linked to you : 

> this is the easiest and simpliest tutorial I've got for you . ( Something that you could have done yourself )
> https://www.ostechnix.com/configure-apache-virtual-hosts-ubuntu-part-1/
> 
> Issues here are related to AVideo script and issues , not how to use apache2 basics . Follow the guide , and you should have your domain name setup 💯

If you can't read , non can help you rly .

**Comment by GodgivenButhelezi** [comment]
kemoi-kiptoo this is what I done and it worked for me 

Apache
If you prefer Apache, create a virtual host file for YouPHPTube with a command line text editor like Nano.

sudo nano /etc/apache2/sites-available/youphptube.conf
Put the following text into the file. Replace the red-colored text with your actual data. I use a subdomain in this tutorial. You can use your main domain name if you prefer. Don’t forget to set DNS A record for the domain name in your DNS record manager. Also note that the document root directory is case-sensitive and you should not add a forward slash at the end.

<VirtualHost *:80>
    ServerName tube.yourdomain.com
    DocumentRoot /var/www/YouPHPTube

    <Directory /var/www/YouPHPTube>
       DirectoryIndex index.php
       Options +FollowSymLinks
       AllowOverride All
       Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/youphptube.error.log
    CustomLog ${APACHE_LOG_DIR}/youphptube.access.log combined

</VirtualHost>
Save and close the file. Then enable this virtual host.

sudo a2ensite youphptube.conf
We need to enable the rewrite module.

sudo a2enmod rewrite
Restart Apache for the changes to take effect.

sudo systemctl restart apache2
