### ISSUE TITLE
SendRecordedToEncoder is inducing audio offsync in 20% cases

### ISSUE THREAD

**Issue by debjit-biswas** [WWBN/AVideo#3190]
**Describe the bug**
While going live we notice no lipsync issue, however, in the recorded media from SendRecordedToEncoder plugin there is about 20% of the live content we have audio off sync. 

**To Reproduce**
Live shows in quick succession. 

**Expected behavior**
Live shows in quick succession produce this off sync. 

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
- Version: Latest

**Comment by DanielnetoDotCom** [comment]
How is your hardware?

I can only think it a Hardware that cannot handle your live.

**Comment by debjit-biswas** [comment]
My hardware is AWS t2.2xlarge. 32GB RAM 8 vCPU. During live htop shows load to be less than 5%

**Comment by akhilleusuggo** [comment]
It's about the packet-loss to the nginx server . If you're not transcoding your hardware doesn't make much difference . But the packet loss are the issue here . Make sure that your nginx server does have enough bandwidth to your HOME . It doesn't mater how much speed does show on a speedtests .

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo thanks for that info. it was really helpful

@debjit-biswas your hardware looks good, but @akhilleusuggo info is really important.
