### ISSUE TITLE
Customizable Linked Logo for video player

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#3192]
Can a customizable logo be added to the video player that functions like a button. When the logo is clicked the  embedded video will  show on the website platform,  Just like youtube videos do.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot this idea?

**Comment by heiress01** [comment]
![image](https://user-images.githubusercontent.com/58334322/83695575-55d0a200-a5c8-11ea-9004-2d175075d1c2.png)

When you click on the word youtube it takes you back to the platform.

**Comment by DanielnetoDotCom** [comment]
Like this ?

![image](https://user-images.githubusercontent.com/18009293/83777668-10f84a00-a660-11ea-8909-2e8b57d68e2d.png)

**Comment by DanielnetoDotCom** [comment]
Be aware you will need to finetune your logo position and size.
it depends on what player skin you are using

![image](https://user-images.githubusercontent.com/18009293/83780038-09867000-a663-11ea-8cd9-59af23896eb5.png)

**Comment by akhilleusuggo** [comment]
Also when clicking on the logo , what is does is enable / disable looping . Nothing more .

**Comment by DanielnetoDotCom** [comment]
> @DanielnetoDotCom
> ![image](https://user-images.githubusercontent.com/52116577/83780762-4455cb80-a696-11ea-94fe-ed6e983b40e0.png)
> 
> Infinite looping

It not suppose to be there, it is something I still working on it. I will remove it soon

**Comment by akhilleusuggo** [comment]
thanks

**Comment by heiress01** [comment]
> Be aware you will need to finetune your logo position and size.
> it depends on what player skin you are using
> 
> ![image](https://user-images.githubusercontent.com/18009293/83780038-09867000-a663-11ea-8cd9-59af23896eb5.png)

My plugin form doesn't look like that.  It only has two features. Which player skin will allow you to do that? 
![image](https://user-images.githubusercontent.com/58334322/83809576-ac9bb180-a684-11ea-82f6-61df9968b291.png)

**Comment by akhilleusuggo** [comment]
I use youtube2 , I don't know witch one uses daniel

**Comment by heiress01** [comment]
ok I see, I needed to update to get the player skins plugin form.  I did and I tried it and when I clicked on the logo, it stayed on the page and in the same frame size, and showed an ad thats running on the channel and half of the video but it didn't go to the platform and continue playing the video like youtube does.

**Comment by DanielnetoDotCom** [comment]
update your code again please.
