### ISSUE TITLE
NGinx running and not able to start! cant understand,please help!!

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3193]
when i check the running status of nginx its running,however when i want to use sudo /usr/local/nginx/sbin/nginx ,i get the 1935 and 8080 port already use error.

Pleae help
![nginx not starting](https://user-images.githubusercontent.com/65802024/83618690-725ce200-a5a8-11ea-941a-dbd7153f808d.png)
![nginx runing](https://user-images.githubusercontent.com/65802024/83618700-7557d280-a5a8-11ea-854e-1b5b37887584.png)

**Comment by tonuzo** [comment]
I think it's already running..

**Comment by akhilleusuggo** [comment]
that's not an error , means that the port is already in use by nginx ( that means it's running )

**Comment by vraghavans** [comment]
okies thanks!for the help
