### ISSUE TITLE
Upload videos from Google Drive

### ISSUE THREAD

**Issue by NAndras95** [WWBN/AVideo#3194]
We have more than 200 videos on Google Drive.
Can we sync it to the encoder easily?

**Comment by akhilleusuggo** [comment]
Youtube-dl does not support google drive

**Comment by ronaldod** [comment]
It supports google drive.
[bunny](https://drive.google.com/file/d/0ByeS4oOUV-49Zzh4R1J6R09zazQ)

**Comment by akhilleusuggo** [comment]
@ronaldod No , youtube-dl does not support google drive files .
You can test it by yourself on console .

**Comment by ronaldod** [comment]
Sorry forgot that i had private build: https://github.com/ytdl-org/youtube-dl/pull/24689
Comming soon tm...

**Comment by ronaldod** [comment]
Fix for downloading can als be manual insterted.
Ubuntu 20 install. Depending on your python install it can be different:
`sudo nano /usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/googledrive.py`
insert under ` 'unicode_escape').split('=')[-1]` on line 266 the next code:
`self._downloader.cookiejar.clear(domain='.google.com', path='/', name='NID')`

Save it and happy downloading.
