### ISSUE TITLE
please help me with detecting the live streaming error-attached nginx error log

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3196]
I have followed wiki guide for live streaming ,but the status is still offline.
attached is 
[nginxerrorlog.txt](https://github.com/WWBN/AVideo/files/4726577/nginxerrorlog.txt)
the nginx error log file
Please assist

**Comment by akhilleusuggo** [comment]
Does the stream plays and showing offline ? Or does not work at all .

Past here your nginx.conf , also screen the plugin ( live )

**Comment by vraghavans** [comment]
Thanks for your reply.
Actually i have 2 nginx.conf files,i dont know why but the content is same which i have put here.
Also stream screen and the plugin screen.
Please advise
![2 nginx files](https://user-images.githubusercontent.com/65802024/83792638-f0a8a980-a6b8-11ea-9fbd-0f0fcce9a093.png)
![live stream screen](https://user-images.githubusercontent.com/65802024/83792642-f1d9d680-a6b8-11ea-9507-6af085690371.png)
[nginx.conf.txt](https://github.com/WWBN/AVideo/files/4731807/nginx.conf.txt)
![plug in screen](https://user-images.githubusercontent.com/65802024/83792648-f4d4c700-a6b8-11ea-8403-c3b2e4d73d8b.png)

**Comment by akhilleusuggo** [comment]
1- remove the useAdaptiveMove ( I think you're not transcoding ). Clear the cache , and start a stream. If not working past the config here .
2- nginx config is located on `/usr/local/nginx/conf/nginx.conf `

**Comment by vraghavans** [comment]
Thanks for your reply-
1) i have removed the adaptive mode and cleared the cache.
2) Noted,please find the nginx.conf file from the above location
[nginxconf1.txt](https://github.com/WWBN/AVideo/files/4734504/nginxconf1.txt)

**Comment by akhilleusuggo** [comment]
ok , I found your problem : 

1 :  Remove https ( use http ) , nginx does not know what is https  


                            on_publish https://seafarerstube.com/plugin/Live/on_publish.php;
                            on_play https://seafarerstube.com/plugin/Live/on_play.php;
                            on_record_done https://seafarerstube.com/plugin/Live/on_record_done.php;


2: to install ssl , make it look like this : 

You need to add your SSL `fullchain.pem` and `privkey.pem` location into the config file
Giving you one example : 

`sudo nano /usr/local/nginx/conf/nginx.conf`


```
http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;                                                                                                                                                                                                   
                    listen 444 ssl;
                    ssl_certificate /etc/letsencrypt/live/yoursitename/fullchain.pem;                                                                                                                                    
                    ssl_certificate_key /etc/letsencrypt/live/yoursitename/privkey.pem;
                    server_name yoursitename.com;                                                                                                                                                                            
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';
```


I use port 444 , but you use 8443 ( so replace 444 by 8443 )
Find your ssl path , and indicate it . In my case is located on /etc/letsencrypt/live/

3- I don't know why , but you have some useless lines at the bottom : 

```
rtmp {
    server {
         listen 1935;
         chunk_size 4096;

         application live {
                 live on;
                 record off;
                 on_publish https://seafarerstube.com/plugin/Live/on_publish.php;
         }
    }
 }
```

What I recomend you is deleting your configuration file , and download it again . And don't mess-up things if you don't know what you're doing .

To delete your config : 
`cd /usr/local/nginx/conf/`
`sudo rm nginx.conf`

Now download a clean config : 
`cd /usr/local/nginx/conf/ && sudo wget https://raw.githubusercontent.com/DanielnetoDotCom/YouPHPTube/master/plugin/Live/install/nginx.conf`

And now make sure that you do everything correctly .

**Comment by vraghavans** [comment]
Good Day,
Many thanks for the detailed instruction and am greatful.
I have done exactly like your guidance,however still to able to make it online
my new nginx.conf file is attached.Also i have many other nginx.conf file-should i delete these files
![varous nginx conf files](https://user-images.githubusercontent.com/65802024/83937645-53e72880-a7ec-11ea-9b87-0b83c42969ee.png)
[new nginx conf.txt](https://github.com/WWBN/AVideo/files/4739436/new.nginx.conf.txt)

**Comment by akhilleusuggo** [comment]
I don't believe that 1.14.2 it's gonna work for you . You would need to install or change something else .

I use the version 1.16.1 . I would recommend to purge that installation , and install the 1.16.1 
When you get to the step to `make` , pay attention to the errors that may appear .
Also `make install ` . After that keep the installation normal .

**Comment by vraghavans** [comment]
Good Day,
thanks for the inputs,it was an important one as i noticed,none of the guides installs 1.16 all are still at 1.14,anyway installed 1.19 now however getting the error that port 80 is used by apache,i use apache for streaming,please advise how do i change the port for nginx
Thanks! so much for your help and guidance.
![nginx start error](https://user-images.githubusercontent.com/65802024/83949644-a6ebca80-a842-11ea-951f-98e20842e0ff.png)

**Comment by akhilleusuggo** [comment]
1.19 is not gonna work .
You need to stop nginx and purge the files .

**Comment by vraghavans** [comment]
Okies noted,
Have installed 1.17.1,was not able to find 1.16.1.
Now the challenge is i can't start nginx and throwing error that port 80 is already used by apache, I have tried many ways to start nginx but failed

**Comment by akhilleusuggo** [comment]
You should not find any issue with 
https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

Take a look

**Comment by vraghavans** [comment]
thanks this guide was perfect! it installed without any error,

however i was not able to go online,have tried all permutation combination.
Please advise if i can do a fresh installation only for the live streaming as the streamer is working fine and already have videos,so dont want to touch the streamer.

Please advise.Also is there a debugger or something which can actually pinpoint where is the error?

Thanks

**Comment by akhilleusuggo** [comment]
You can install rtmp server on a different server yes .
The log file are on `/usr/local/nginx/log/`

**Comment by vraghavans** [comment]
Thanks for the below message!
I would prefer to keep it in the same server.
Please advise to remove the whole live streamer and install again please.

Further the attachement is the error log for the latest session,i can see a ssl error-is it something we need to be worried about-cant see any other errors though,please advise.
[nginx log.txt](https://github.com/WWBN/AVideo/files/4750144/nginx.log.txt)

**Comment by akhilleusuggo** [comment]
it's a debug , nothing more . I see no errors .
The debug tool will be removed soon , may be misleading for some users
