### ISSUE TITLE
Subtitle Switcher plugin

### ISSUE THREAD

**Issue by GodgivenButhelezi** [WWBN/AVideo#3198]
i would like to upload subtitles, but it says Invalid extension for file "ratatouille.zip". Only "vtt, srt" files are supported.

**Comment by ronaldod** [comment]
That is normal a zip is compressed file not a srt or vtt file. What exactly do you have in the zip file ?
Multiple languages ?

**Comment by GodgivenButhelezi** [comment]
no I have one Language, but I finally made it thanks so much for helping
