### ISSUE TITLE
After latest pull Channel #channelHome tab

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3202]
Hi

after latest pull in MyChannel page there is now #channelHome -tab.
Can it be disabled somehow (CSS maybe)? It´s useless for us and it makes the channel look bad when using Flix-style page. 

Before the pull there was only #channelVideos and #channelPlaylists visble on MyChannel. That was just fine.

Br,
T

**Comment by DanielnetoDotCom** [comment]
Uncheck this 

![image](https://user-images.githubusercontent.com/18009293/83874261-9553d700-a70b-11ea-91fb-8e14033671ae.png)

**Comment by tonuzo** [comment]
Suberb! Thanks.

T
