### ISSUE TITLE
Video's are not show. First page is empty

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#3203]
**Describe the bug**
No video are shown.

**To Reproduce**
1. clean install
2. upload video by encoder
3. look at video default page.

**Expected behavior**
I would expect a notification no video found if i just installed it. And i uploaded a video and still no video listings

**Error Logs**
No errors in the logs except for common message:
`[05-Jun-2020 18:53:20 UTC] PHP Notice:  Trying to access array offset on value of type bool in /var/www/test3.myownsite.nl/plugin/Plugin.abstract.php on line 162`

**Screenshots**
![image](https://user-images.githubusercontent.com/31585599/83913042-2e680980-a76f-11ea-8a31-94f2e5f29ce6.png)

**Desktop (please complete the following information):**
 - OS:  W10
 - Browser [chrome, firefox and edge]
 - Version [latest]

**Additional context**
Also disabled gallery and activated youtube still no change.

**Comment by DanielnetoDotCom** [comment]
I guess the gallery plugin is enabled by default.

but no message about the empty videos

**Comment by akhilleusuggo** [comment]
The videos will start to show only when you have more then 3 videos .

**Comment by ronaldod** [comment]
Is this something new ?
I had this not with previous installs.

**Comment by akhilleusuggo** [comment]
Don't talk about the manual . The wiki and manual needs a real `apt-get update && apt-get upgrade` .
Most of the issue on this project are coming from the Wiki , super outdated .
Just take a look at this one : https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server#2-install-nginx-and-nginx-rtmp

Everybody knows that ubuntu 18.04 is not gonna work with nginx-1.12.0 ( not out of the box )
Needs at the least 14.x ( I'm using 1.16.01 )

And many other things
