### ISSUE TITLE
HLS quality selector not showing 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3204]
Not showing the quality selector 
![image](https://user-images.githubusercontent.com/52116577/83923511-1d2cf600-a78b-11ea-97f4-f2450d7bffdf.png)
![image](https://user-images.githubusercontent.com/52116577/83923525-2322d700-a78b-11ea-85c9-419842ae0a59.png)
![image](https://user-images.githubusercontent.com/52116577/83923662-62e9be80-a78b-11ea-9a0b-ce5d5518b69b.png)
![image](https://user-images.githubusercontent.com/52116577/83923707-77c65200-a78b-11ea-95ae-c3bd3cb242a5.png)

**Comment by wetubeclub** [comment]
Hello
and for me the same problem

Thank you
Ilias
