### ISSUE TITLE
RE: Searching for where to Increase the comment entry characters

### ISSUE THREAD

**Issue by Fuquan999** [WWBN/AVideo#3206]
Dear Daniel,

Just a quick question as I can not seem to find any "Comments Plugin" so I am unable to figure out where to manage and make changes to the amount of Characters/Words that comments can have. Presently 200 characters is way too small as we would like to increase this number but I cannot find the right location to make changes to comments. 

If you would be kind enough to point us where we need to look to find the location where we can increase the comment character size as we do urgently need to increase the amount of characters/words that people can have to make proper comments.

Thanks
Fuquan Idris

![CommentCharactersToSmall](https://user-images.githubusercontent.com/17571557/83931038-d7782980-a79a-11ea-8da7-eb6f5f9b65be.JPG)

![image](https://user-images.githubusercontent.com/17571557/83930929-4ef98900-a79a-11ea-97ab-151b4fe7130a.png)

**Comment by akhilleusuggo** [comment]
Plugins : CustomizeAdvanced

![image](https://user-images.githubusercontent.com/52116577/83931538-f334fd00-a7a5-11ea-8555-5e8cbf6131f4.png)

**Comment by Fuquan999** [comment]
akhilleusuggo Thanks a Million for the pointer as that is the precise location.
