### ISSUE TITLE
Live stream not working 

### ISSUE THREAD

**Issue by gamersalpha** [WWBN/AVideo#3207]
Hello evrybody, now i m using Avideo like a BOSS :)
thanks to u

so now i want get the live stream to my avideo portal, i want record diretcly my gaming in avideo, and put them in youtube if i like the game.

so now i follow the guide here : 
https://github.com/WWBN/AVideo/wiki/Configure-your-Live-stream-server---Nginx---RTMP
and i folow this step to start nginx on my serveur : 

```
 sudo mkdir /HLS/
 sudo mkdir /HLS/live
 sudo chmod 777 /HLS/live

```
so now on my avideo i got this page : 

like u see evrything look good : 
![image](https://user-images.githubusercontent.com/32466950/83939842-4cba1d80-a7e0-11ea-9893-4f438f5003c8.png)

so on my obs studio i configure the strem with my keyx : 
![image](https://user-images.githubusercontent.com/32466950/83939858-6196b100-a7e0-11ea-95b1-7792c1f11a3f.png)

andi start my streamm and look like data is sending : 

![image](https://user-images.githubusercontent.com/32466950/83939867-72dfbd80-a7e0-11ea-92d0-a28c11645dd4.png)

ok so now i go on my avideo website  : 

i look rtmps stats  :
again look like date comming on my avideo serveur : 

![image](https://user-images.githubusercontent.com/32466950/83939876-8ee35f00-a7e0-11ea-9e42-0d2fb7e0a841.png)

now i m go on my avideo website : 
that's said no live ??
![image](https://user-images.githubusercontent.com/32466950/83939882-aa4e6a00-a7e0-11ea-80c9-1f014306bad7.png)

i go on my live page same things : 

![image](https://user-images.githubusercontent.com/32466950/83939895-bd613a00-a7e0-11ea-8d8a-847cbbc984c9.png)

![image](https://user-images.githubusercontent.com/32466950/83939905-ce11b000-a7e0-11ea-8d73-9f686c2be39d.png)

can please tell me what i m doing wrong thanks all

**Comment by akhilleusuggo** [comment]
Can you past here your config and plugin settings ?
Also a self certified certificate could be the issue here . But first we need to see the config and plugin Live parameter
