### ISSUE TITLE
external m3u8 link schedule not recording??

### ISSUE THREAD

**Issue by praiseworld3d** [WWBN/AVideo#3208]
I was able to get this working, however the stream was not recorded. Is there a way to do this?

_Originally posted by @praiseworld3d in https://github.com/WWBN/AVideo/issues/1307#issuecomment-640100708_

**Comment by akhilleusuggo** [comment]
How do you wanna record something that you're not hosting ?
Quick Answer : No

You need to download it by your own .

**Comment by praiseworld3d** [comment]
> How do you wanna record something that you're not hosting ?
> Quick Answer : No
> 
> You need to download it by your own .

Ok, got it. Thanks for the quick reply.
