### ISSUE TITLE
install Sorry! Unknow error! 

### ISSUE THREAD

**Issue by hamelinmultimedia** [WWBN/AVideo#3209]
Hello, I have been installing YouPHPtube on a vps ubuntu 20.04 and for some reason I could not... now I have the vps with ubuntu 18.04 and these installation steps.

1- apt-get update && apt-get upgrade -y
2- sudo apt-get install -y apache2 php libapache2-mod-php php-mysql php-curl php-gd php-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl
3- cd /var/www/html
4- sudo git clone https://github.com/WWBN/AVideo.git
5- sudo git clone https://github.com/WWBN/AVideo-Encoder.git
6- sudo apt-get install python
7- sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
8- sudo chmod a+rx /usr/local/bin/youtube-dl
9- sudo a2enmod rewrite
10- sudo service apache2 restart
11- sudo apt install php-mbstring php-gettext
12- sudo phpenmod mbstring
13- sudo service apache2 restart
14- sudo mysql
15- ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'MYPASSWORD'; (replace MYPASSWORD with your password's for database, then exit by typing ''quit or exit''
16- sudo nano /etc/apache2/apache2.conf
17- Find <Directory /var/www/> then change AllowOverride None to AllowOverride All
18- sudo a2enmod rewrite
19- sudo service apache2 restart
20- cd /var/www/html
21- sudo chown www-data:www-data -R *

Go and finish your installation on the browser http://YourIP/AVideo
If you followed the instruction , you should have no problems .

all well ...- but when you finish Sorry!

![image](https://user-images.githubusercontent.com/53911390/83954608-62473b80-a810-11ea-88f2-cfaffc180edc.png)

I've tried several options but I can't find the problem
although the error.log has an undefinined variable

error log

[Sat Jun 06 15:24:29.116982 2020] [mpm_prefork:notice] [pid 16555] AH00169: caught SIGTERM, shutting down
[Sat Jun 06 15:24:29.265844 2020] [mpm_prefork:notice] [pid 16589] AH00163: Apache/2.4.29 (Ubuntu) configur$[Sat Jun 06 15:24:29.265947 2020] [core:notice] [pid 16589] AH00094: Command line: '/usr/sbin/apache2'
[Sat Jun 06 15:24:36.694405 2020] [php7:notice] [pid 16591] [client 108.162.210.252:47568] PHP Notice:  Und$[Sat Jun 06 15:39:29.039860 2020] [php7:notice] [pid 16592] [client 162.158.123.211:59278] PHP Notice:  Und$[Sat Jun 06 15:40:11.220959 2020] [mpm_prefork:notice] [pid 16589] AH00169: caught SIGTERM, shutting down
[Sat Jun 06 15:40:11.375798 2020] [mpm_prefork:notice] [pid 16777] AH00163: Apache/2.4.29 (Ubuntu) configur$[Sat Jun 06 15:40:11.375972 2020] [core:notice] [pid 16777] AH00094: Command line: '/usr/sbin/apache2'
[Sat Jun 06 15:41:10.179107 2020] [php7:notice] [pid 16778] [client 162.158.123.211:31760] PHP Notice:  Und$[Sat Jun 06 15:53:20.267413 2020] [mpm_prefork:notice] [pid 16777] AH00169: caught SIGTERM, shutting down
[Sat Jun 06 15:53:20.482363 2020] [mpm_prefork:notice] [pid 17219] AH00163: Apache/2.4.29 (Ubuntu) configur$[Sat Jun 06 15:53:20.482480 2020] [core:notice] [pid 17219] AH00094: Command line: '/usr/sbin/apache2'
[Sat Jun 06 15:55:39.899029 2020] [mpm_prefork:notice] [pid 515] AH00163: Apache/2.4.29 (Ubuntu) configured$[Sat Jun 06 15:55:39.899781 2020] [core:notice] [pid 515] AH00094: Command line: '/usr/sbin/apache2'
[Sat Jun 06 15:56:53.329733 2020] [php7:notice] [pid 524] [client 162.158.123.85:30522] PHP Notice:  Undefi$

thank you for your help and for your app

**Comment by hamelinmultimedia** [comment]
Don't worry 
I'll try to install it one more time.... from scratch

**Comment by DanielnetoDotCom** [comment]
The problem here is because your site is https and the domain in the input is HTTP;

make both https and it will work.

![image](https://user-images.githubusercontent.com/18009293/84075464-93f40a00-a9aa-11ea-9d1d-d6d5b1fd5967.png)
