### ISSUE TITLE
Video not showing in app

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3210]
This video was showing, now it's not?

![Screenshot_20200606-182459_AVideo](https://user-images.githubusercontent.com/66537018/83955883-d04a2d80-a825-11ea-82f1-be8a3bad6650.jpg)

**Comment by DanielnetoDotCom** [comment]
Are you saying this does work before?
And stops after some update?

Can you please share the video link so we can test it?

**Comment by fakeologist** [comment]
Here's the [link](https://fakeotube.com/video/76/2-buffalo-cops-suspended-after-staged-event?channelName=Fakeologist).
The video showed fine in app before.
It's also the most viewed video on my site - yet it doesn't show on the top of the trending page.

**Comment by DanielnetoDotCom** [comment]
Hi

that is the thing ....

it is an unlisted video. it does not suppose to show on the app.

I guess I need to submit a fix to the streamer to now show unlisted videos on the app

**Comment by fakeologist** [comment]
Ok that's my error - although I have no idea how I unlisted it by mistake. The app acted properly if it didn't show an unlisted video.

**Comment by fakeologist** [comment]
Video gone again. It shows listed.

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that.

It was an error on the API, it is fixed now.

@fakeologist  I also update your site.
