### ISSUE TITLE
how does trending measure?

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3211]
Is the trending feature actually working?
I have a video with 300 views in a few hours, yet it doesn't float to the top of trending.
[Here's the link](https://fakeotube.com/video/76/2-buffalo-cops-suspended-after-staged-event) of the video.
[Here's](https://fakeotube.com/trending) my trending page.

**Comment by akhilleusuggo** [comment]
Not working properly . Actually it is measured by ''likes/comments'' and not views .

**Comment by fakeologist** [comment]
Should I submit this as a bug?

**Comment by akhilleusuggo** [comment]
I don't think it's gonna be easy to fix . Because this will require some type of algorithm .
A balance between time_watch/views/likes/comments/subs then , rank them .

**Comment by DanielnetoDotCom** [comment]
Correct is not views.

But it may be improved soon.

**Comment by fakeologist** [comment]
Look forward to that. 
How about a most viewed page?
