### ISSUE TITLE
Wrong video showing 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3213]
https://fakeotube.com/video/75-year-old---100-staged-fall...end-of-story

The above link is showing the link below in the avideo app.
https://fakeotube.com/video/facemask-exemptions-facemask-science---dr-tim-o-shea
Everything works normally in the website.

**Comment by DanielnetoDotCom** [comment]
Hi

where did you get those links from?

those are the same problem as the API problem

**Comment by 1tpg1** [comment]
I got the links from the website.

**Comment by fakeologist** [comment]
Got them from site. All good now. Thanks.
