### ISSUE TITLE
PHP Keeps Crashing

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#3215]
Hi,

PHP keeps crashing my site, I think when it's more when a video is playing.
When it crashes if I run **sudo systemctl restart php7.2-fpm** it starts right back up.

[Mon Jun 08 16:05:40.056821 2020] [proxy_fcgi:error] [pid 1638] (70007)The timeout specified has expired: [client 192.168.0.6:64076] AH01075: Error dispatching request to : (polling), referer: https://www.MYDOMAIN.ca/
[Mon Jun 08 16:05:46.813192 2020] [proxy_fcgi:error] [pid 2058] (70007)The timeout specified has expired: [client 192.168.0.6:64081] AH01075: Error dispatching request to : (polling), referer: https://www.MYDOMAIN.ca/
[Mon Jun 08 16:06:36.625923 2020] [proxy_fcgi:error] [pid 2059] (70007)The timeout specified has expired: [client 192.168.0.6:64123] AH01075: Error dispatching request to : (polling), referer: https://www.MYDOMAIN.ca/
[Mon Jun 08 16:06:41.774862 2020] [proxy_fcgi:error] [pid 2067] (70007)The timeout specified has expired: [client 192.168.0.6:64124] AH01075: Error dispatching request to : (polling)
[Mon Jun 08 16:06:57.286458 2020] [proxy_fcgi:error] [pid 2069] (70007)The timeout specified has expired: [client 192.168.0.6:64126] AH01075: Error dispatching request to : (polling), referer: https://www.MYDOMAIN.ca/
[Mon Jun 08 16:07:24.396541 2020] [proxy_fcgi:error] [pid 1640] (70007)The timeout specified has expired: [client 72.143.210.213:30536] AH01075: Error dispatching request to : (polling)
[Mon Jun 08 16:07:27.552827 2020] [proxy_fcgi:error] [pid 1641] (70007)The timeout specified has expired: [client 192.168.0.6:64128] AH01075: Error dispatching request to : (polling), referer: https://www.MYDOMAIN.ca/
[Mon Jun 08 16:07:28.427698 2020] [proxy_fcgi:error] [pid 1639] (70007)The timeout specified has expired: [client 192.168.0.6:64129] AH01075: Error dispatching request to : (polling), referer: https://www.MYDOMAIN.ca/
[Mon Jun 08 16:07:33.430535 2020] [proxy_fcgi:error] [pid 1642] (70007)The timeout specified has expired: [client 192.168.0.6:64130] AH01075: Error dispatching request to : (polling), referer: https://www.MYDOMAIN.ca/
[Mon Jun 08 16:07:33.628884 2020] [proxy_fcgi:error] [pid 2057] (70007)The timeout specified has expired: [client 192.168.0.6:64131] AH01075: Error dispatching request to : (polling), referer: https://www.MYDOMAIN.ca/
[Mon Jun 08 16:07:38.433182 2020] [proxy_fcgi:error] [pid 2068] (70007)The timeout specified has expired: [client 192.168.0.6:64132] AH01075: Error dispatching request to : (polling), referer: https://www.MYDOMAIN.ca/
[Mon Jun 08 16:07:43.423776 2020] [proxy_fcgi:error] [pid 2112] (70007)The timeout specified has expired: [client 192.168.0.6:64133] AH01075: Error dispatching request to : (polling), referer: https://www.MYDOMAIN.ca/
[Mon Jun 08 16:08:10.430949 2020] [proxy_fcgi:error] [pid 2118] [client 192.168.0.6:64316] AH01067: Failed to read FastCGI header
[Mon Jun 08 16:08:10.431010 2020] [proxy_fcgi:error] [pid 2118] (104)Connection reset by peer: [client 192.168.0.6:64316] AH01075: Error dispatching request to :
[Mon Jun 08 16:08:10.588257 2020] [proxy:error] [pid 2067] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.sock (*) failed
[Mon Jun 08 16:08:10.588292 2020] [proxy_fcgi:error] [pid 2067] [client 192.168.0.6:64319] AH01079: failed to make connection to backend: httpd-UDS, referer: https://www.MYDOMAIN.ca/

Thanks

**Comment by ronaldod** [comment]
assuming your using apache2 and assuming  your using ubuntu 18.04. Asuming you followed the installation guidelines.
And assuming your not running plesk. You should set the setting `ProxyTimeout 1800` to your apache2 config.

Why assume. You did not fill out the form.

**Comment by akhilleusuggo** [comment]
The default installation ( on the wiki ) does not support php-fpm .
You need to find solution to your issue on forums ( google is your friend )

Anyway your logs are not relevants . You need to find your actual issue on /var/log/php7.2-fpm.log

**Comment by D-Spayre** [comment]
Sorry, yes Apache2, PHP7.2, 18.04, MariaDB 10.4.

Ya I read that PHP7.2-fpm was a little faster, didn't realize that it would cause an issue.

Thanks I'll try the ProxyTimeout and do a little more digging.

Thanks again,
