### ISSUE TITLE
Live stream andriod app not showing other live stream under live tab

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#3216]
i have a live stream running in app but it is not showing on other apps when they click live 
![Screenshot_20200608-173526_FreeDomShare Live](https://user-images.githubusercontent.com/60738260/84090468-ed1a6880-a9bf-11ea-9f4c-928ffd883d88.jpg)

also will live stream chat show up when live? in app?

**Comment by DanielnetoDotCom** [comment]
Hi

I guess you fixed this already with your freelancer correct?

**Comment by freedomshare** [comment]
Yes but still haven't got send to encoder to work yet tho

**Comment by DanielnetoDotCom** [comment]
Are you using Cloudflare?

if yes, update your Encoder and Streamer. we recently sent an update that may help you identify the issue.

then if still fail, check your log file.

**Comment by freedomshare** [comment]
No but I have reuploaded the send to encoder file yesterday

**Comment by DanielnetoDotCom** [comment]
We sent updates today. Make sure you update the streamer and the encoder

**Comment by freedomshare** [comment]
could this be the issue  to why it is not sending to endcoder? 
![image](https://user-images.githubusercontent.com/60738260/84333717-8f705280-ab5e-11ea-9d8e-d1c3d1812ad9.png)

should there be this many files in this folder or should it only be one?

**Comment by freedomshare** [comment]
and i have done the set up 
![image](https://user-images.githubusercontent.com/60738260/84334981-bb410780-ab61-11ea-9e49-e951662fcb06.png)

**Comment by freedomshare** [comment]
as you can see it looks like it is trying to save the files as pdfor txt doc files if you look at the lighted file it was the most recent stream from in app thati was tetsting and the way the image looks it looks like pdf file..

![image](https://user-images.githubusercontent.com/60738260/84335357-a7e26c00-ab62-11ea-8d7b-185d8347abc6.png)

**Comment by freedomshare** [comment]
think i found it but not sure what to do to fix this 
![image](https://user-images.githubusercontent.com/60738260/84344673-6315ff80-ab79-11ea-8969-f2e8fd134336.png)

**Comment by DanielnetoDotCom** [comment]
Looks like your recorder is configured correctly.

but also looks like you enabled the encoder network while you do not have one.

![image](https://user-images.githubusercontent.com/18009293/84392278-8324dd80-abd0-11ea-990e-06dd73fd5fb4.png)


Make sure you do not use the Network

**Comment by freedomshare** [comment]
i have encoder network...

**Comment by freedomshare** [comment]
could it be my SSL when i have https on the streams dont like to show i trun SSL off and stream showon site could this have the same issue with sending to encoder?
as seen here:https://github.com/WWBN/AVideo-Encoder/issues/119

**Comment by DanielnetoDotCom** [comment]
What is your encoder Network URL? just for checking.

can you please copy the whole line of error of getBestEncoder.php?

**Comment by freedomshare** [comment]
https://enc.freedomshare.net/
![image](https://user-images.githubusercontent.com/60738260/84423817-123fee80-abed-11ea-9f60-6fe6963f5ec2.png)

**Comment by freedomshare** [comment]
![image](https://user-images.githubusercontent.com/60738260/84424130-a316ca00-abed-11ea-9d7a-60771dcf7f2a.png)

**Comment by akhilleusuggo** [comment]
I'm not sure if you even have the network encoder or not .
If you have it , maybe the server is not able to ping to determine the best server . 
`/getBestEncoder.php' not found or unable to stat`

The other thing is , where did you get `/view/getBestEncoder.php` ??
I don't see it on the script . https://github.com/WWBN/AVideo-Encoder/tree/master/view , it should be on the network-encoder . 

`sudo apt-get install -y ping`

**Comment by freedomshare** [comment]
it was in the error log file

**Comment by DanielnetoDotCom** [comment]
@freedomshare we cannot make sure if it is an Encoder or an Encoder Network

can you screenshot the screen after the login on https://enc.freedomshare.net/?

**Comment by freedomshare** [comment]
I have tried turning off the network and made no difference

**Comment by freedomshare** [comment]
![Screenshot_20200612-102952_FreedomShare](https://user-images.githubusercontent.com/60738260/84507764-b7170600-ac97-11ea-840f-be9a3ecb76f6.jpg)

**Comment by DanielnetoDotCom** [comment]
Ok, confirmed. it is an encoder NOT a network

we should have a difference at least at the log files.

try to run a live video now and check your log files again so see what happens.

please copy and paste the text here instead of a screenshot of the logs.

**Comment by freedomshare** [comment]
I can't copy and past as I log in from another server

**Comment by DanielnetoDotCom** [comment]
I can see you are using Ubuntu Desktop. use the Desktop browser to open GitHub and then the copy/paste should work

**Comment by freedomshare** [comment]
it the same error just the time and date change

**Comment by DanielnetoDotCom** [comment]
sorry, but are you sure you disabled the network?

can you screenshot your CustomizeAdvanced plugin configuration?

**Comment by freedomshare** [comment]
![image](https://user-images.githubusercontent.com/60738260/84509054-36eda200-ac91-11ea-89f8-aaf7918f93a8.png)

that file is not in that folder at all that it is calling for..
not sure whats's going on

**Comment by freedomshare** [comment]
![image](https://user-images.githubusercontent.com/60738260/84509685-1245fa00-ac92-11ea-9fb2-51417c06f5f5.png)

**Comment by DanielnetoDotCom** [comment]
Ok,fine, now try again and share the logs

**Comment by freedomshare** [comment]
they are the same errors nothing has changed..

**Comment by freedomshare** [comment]
im just going to buy your install service, i cant get this to work and wasting money on freelancers time,
what all do i need to provide you to do so? you will have the payment in 10 mins

**Comment by freedomshare** [comment]
i just sent payment

**Comment by DanielnetoDotCom** [comment]
Thanks, I guess you are all set now.
