### ISSUE TITLE
How do you delete a user? 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3218]
I don't see any option under users.

**Comment by akhilleusuggo** [comment]
users can not be deleted ( not recommended ) , you will end up with errors .
Recommended to ban them ( disable accounts ) User_Controll Plugin ; https://youphp.tube/plugins/

**Comment by fakeologist** [comment]
Gotcha. What does one do for spam comments? Can comments go to moderation automatically?

**Comment by akhilleusuggo** [comment]
Not for now . BUT , you have the option allow only verified emails to comments : 

CustomizeUser 
![image](https://user-images.githubusercontent.com/52116577/84457416-44903100-ac6b-11ea-97d1-7795d2d4b324.png)

**Comment by fakeologist** [comment]
Excellent thank you.
