### ISSUE TITLE
Social Share Buttons - Pinterest- Missing Java File

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3219]
I had to add this to make Pinterest work in /var/www/html/YouPHPTube/view/include/social.php

<script type="text/javascript" async defer src="//assets.pinterest.com/js/pinit.js"></script>

**Comment by DanielnetoDotCom** [comment]
does this should be add on the social.php file?
https://github.com/WWBN/AVideo/blob/master/view/include/social.php

would you like to make a pull request?

**Comment by DanielnetoDotCom** [comment]
Hi

I sent an update, I hope it works

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom
