### ISSUE TITLE
FTP

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3220]
Hello I am a test site,
I have a problem with the configuration of the ftp, as you can on the image
https://prnt.sc/swo58j

https://prnt.sc/swob3k

- I have the impression that SecureVideo Directory does not work

**Comment by akhilleusuggo** [comment]
I'm not using this plugin , and I'm not sure about what you're trying to do , but using ssl , and port 21 doesn't look good to me

**Comment by syldri** [comment]
hello, i disabled ssl and passive mode nothing changes.

I have two other sites that work very well, with AVIDEO the ftp plugin does not want to connect

**Comment by syldri** [comment]
hello 
I only have a txt file

hello i tested with 4 different ftp it's still the same problem nothing works
I sent the link of avideo.log by e-mail

**Comment by DanielnetoDotCom** [comment]
what is the URL to access your txt file?

and what is the URL to access your video (even if it is wrong)?

**Comment by syldri** [comment]
hello i have that in the txt file


<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

**Comment by DanielnetoDotCom** [comment]
If you share the requested links we may be able to help you

**Comment by syldri** [comment]
hello i'm emailing you
