### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3221]
hello i stayed a day looking for this little bug i can't find if someone has already had this problem can tell me what to do thank you

https://prnt.sc/swsv31

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/Redirect-http-to-https

**Comment by syldri** [comment]
hello, 
the problem comes from chat2 when I deactivate it I no longer have a problem

**Comment by akhilleusuggo** [comment]
Is the same , the back-group picture is over http , need a redirect to https .
Just follow the guide I've linked you .

**Comment by syldri** [comment]
hello the problem is solved
