### ISSUE TITLE
Livestreaming not working

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3223]
Trying to livestream from Avideo.
Phone says it's connected and broadcasting, website not showing anything except the image below.
![livestream](https://user-images.githubusercontent.com/66537018/84216589-f70f9a80-aa97-11ea-9617-39a0e7069d29.jpg)

**Comment by akhilleusuggo** [comment]
1 . Check the stats page
2. Make sure you have adaptive stream option disabled 
3- Take a minute and read this guide https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

**Comment by fakeologist** [comment]
ok it works OK from desktop. There is a 22 second delay, which seems excessive.
The problem is now just from AVIDEO android app. It connects, but doesn't stream it seems.

**Comment by akhilleusuggo** [comment]
I can't help you with the APP ( only @DanielnetoDotCom )

About the delay , take a look here https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server#11-extra-settings--nginxconf-

You need to set keyframe to 2 ( on your transcoding ) , hls_fragment 2s; 
This one should give you 4-8 delay seconds . 
You can go lower , but that will require some good hardware ( not worth it )
