### ISSUE TITLE
Where is the stream url and key?

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3224]
Where is this found? I know I've seen it but can't find it.

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/84218373-f2b6a200-aad6-11ea-8094-777c55ace758.png)

![image](https://user-images.githubusercontent.com/52116577/84218409-0235eb00-aad7-11ea-8752-534b9ca21863.png)
