### ISSUE TITLE
Question about using google Firebase with Avideo 

### ISSUE THREAD

**Issue by TakeAchance365** [WWBN/AVideo#3225]
I’ve noticed that there is a folder for Firebase on this project and I was wondering how and if there was a way to be able to use Google Firebase to host my Avideo site and add users that way  @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
I am not using it. it comes with the Google API. maybe Google API uses it for something.

**Comment by TakeAchance365** [comment]
Ok thank you
