### ISSUE TITLE
How to change the loading image in the center of the video player

### ISSUE THREAD

**Issue by Kambiz-Homayouni** [WWBN/AVideo#3227]
How to change the loading image in the center of the video player?

@DanielnetoDotCom
![Loading Logo](https://user-images.githubusercontent.com/33898229/84356883-10206480-abda-11ea-89f3-5211be8c96d1.png)

**Comment by DanielnetoDotCom** [comment]
I do not know, but you may find the answer if you google for that.

search for videojs player.
