### ISSUE TITLE
Cant login as admin for first time?

### ISSUE THREAD

**Issue by mrkglk** [WWBN/AVideo#3230]
I have it installed correctly but I can not login as admin and password for the first time? May be simple but I am stumped. Any help would be appreciated. Thanks!

**Comment by akhilleusuggo** [comment]
in the instalation you should have introduced a password . Just go to login ; admin , and type your password .

If you don't remember it , try to reset it : https://github.com/WWBN/AVideo/wiki/Reset-a-Password

**Comment by mrkglk** [comment]
It was the password to the script Avideo, not sure what happened? Thanks
 
 
 
-----Original Message-----

**Comment by akhilleusuggo** [comment]
did you fixed it ?
