### ISSUE TITLE
Videos not showing

### ISSUE THREAD

**Issue by heiress01** [WWBN/AVideo#3231]
I'm not sure entirely if it's a bug.  But, I've had two users try to upload videos and they don't play.  I can't tell if they were direct uploads or if they tried to embed the videos.  
![image](https://user-images.githubusercontent.com/58334322/84449505-9f9a3780-ac1b-11ea-9221-94782832c7e3.png)
![image](https://user-images.githubusercontent.com/58334322/84449747-467ed380-ac1c-11ea-8595-b63f54790302.png)

**Comment by akhilleusuggo** [comment]
Maybe they're still encoding . Maybe the encoding failed , maybe maybe maybe ...

provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by DanielnetoDotCom** [comment]
@heiress01 what browser is that?

it looks like an embed or a non HTML5 player
