### ISSUE TITLE
$xml .= '<!-- Live -->';

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3232]
I'm not able to make it work , does mix things up with

**Comment by DanielnetoDotCom** [comment]
Hi

where does it come from?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I'm talking about the sitemap .

**Comment by DanielnetoDotCom** [comment]
I am confused. 
Not sure what are you trying to do.

**Comment by akhilleusuggo** [comment]
I'm trying to add live links to the sitemap .

New section for live only .

```
$xml .= '<!-- Live -->';

<loc>THE LIVE URL</loc>
         <video:video>
                <video:title>LIVE TITLE</video:title>
                 <video:description>LIVE DESCTIPTION</video:description>
                 <video:family_friendly>yes</video:family_friendly>
                 <video:live>yes</video:live>
          </video:video>
</url>
            ';
```

Something like this .

**Comment by DanielnetoDotCom** [comment]
Try this:

$xml .= '<loc>THE LIVE URL</loc>
         <video:video>
                 <video:title>LIVE TITLE</video:title>
                 <video:description>LIVE DESCTIPTION</video:description>
                 <video:family_friendly>yes</video:family_friendly>
                 <video:live>yes</video:live>
          </video:video>
</url> ';

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 

ok , made it work differently .

```
$xml .= ' 
        <!-- Live -->
        ';
    $_POST['rowCount'] = $advancedCustom->siteMapRowsLimit;
     {
        $xml .= '
        <url>
        <loc>THE LIVE URL</loc>
         <video:video>
                 <video:title>LIVE TITLE</video:title>
                 <video:description>LIVE DESCTIPTION</video:description>
                 <video:family_friendly>yes</video:family_friendly>
                 <video:live>yes</video:live>
          </video:video>
</url> ';


    }
```

Now I wanna know where the streams description is stored , and how do I get the video location . 
Example : http://192.168.0.250/AVideo/plugin/Live/?c=Unknown+User

The only way I believe I can do that is 

`' . $global['webSiteRootURL'] . 'plugin/Live/?c=' . User::getChannelName($value['id']) . '`
But I'll have to add more to it , 
```
$users = User::getAllUsers(true);
    foreach ($users as $value) {
```

Any advice ? The idea is let the search results ( google and others ) to know the livestreams links.
![image](https://user-images.githubusercontent.com/52116577/84579739-29dbca80-add9-11ea-809a-86965df1cb11.png)

Something like this

**Comment by DanielnetoDotCom** [comment]
Hi the description is on the database.

the Link URL is correct for the HTML page, but do you want to put an HTML page (recomended) or an m3u8 link?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom It's for google search , if you provide the m3u8 url , the users will be redirected to something like this : https://live.avideo.com:444/live/5c6007fb1880e/index.m3u8

And that not playable ( not on browser )

**Comment by DanielnetoDotCom** [comment]
I agree, so the page is better and you are in the right direction.
