### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3233]
hello I would like to have information I saw that there are many words or sentences which are not translated.

![image](https://user-images.githubusercontent.com/39193219/84524381-2f062000-acda-11ea-9480-5b828247ccd6.png)

** I did a test by adding the sentence in English and French **

![image](https://user-images.githubusercontent.com/39193219/84524913-05012d80-acdb-11ea-824d-a13abe9c4462.png)

when I look on the site https: // my-site.com/locale/

I can't find the sentence 
( **If you have blocked a user and want to grant them access again, don't forget that even if their name is no longer there, they can be inactive.** )

![image](https://user-images.githubusercontent.com/39193219/84526845-244d8a00-acde-11ea-8ecf-3dcf5ebfa1ca.png)

I want to translate everything on the site

can you tell me how to do this
Thank you a lot

**Comment by DanielnetoDotCom** [comment]
Hi

you are correct.
Translate all is possible but will be a hard job.

those words are basically for admin only. that is why it may not be translated.

If you really need to translate it all I can quote it for you.

please email me at developer@youphptube.com
