### ISSUE TITLE
doNotShowEncoderHLS

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3237]
This feature is not working , cleared the cache and nothing .
![image](https://user-images.githubusercontent.com/52116577/84580912-7aa4f080-ade4-11ea-856d-1aa261ec996c.png)
![image](https://user-images.githubusercontent.com/52116577/84580916-88f30c80-ade4-11ea-9164-5f64815302cc.png)

**Comment by DanielnetoDotCom** [comment]
This was because you had the VideoHLS plugin enabled. but here is a fix

**Comment by akhilleusuggo** [comment]
yes , but I wanna keep the VideoHLS active ( for old video encoded on HLS ) , but not to opt from now to encode on HLS ( as example )

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I think the thing is here : 

`ffmpeg -y -ss 3 -t 6 -i \"{$url}\" -vcodec libwebp -lossless 1 -vf fps=10,scale=-2:360 -q 80 -compression_level 6 -preset default -loop 0 -an -vsync 0 {$destination}`

`\"{$url}\"` the url is not the same for mp4 as for HLS ( m3u8 ) .
On mp4 you have to tell the exact mp4 url . There's no automatic selection .

Uppon encoding it's easy , since there's only 1 file , but on getwebp.php , there is more then 1 file .

**Comment by DanielnetoDotCom** [comment]
Sorry for the late reply.

with the update I sent could you do not show the HLS option on the encoder and keep the HLS active?
