### ISSUE TITLE
streamer site fails to update

### ISSUE THREAD

**Issue by GodgivenButhelezi** [WWBN/AVideo#3238]
Greetings. My streamer site failed to update or upgrade today and showed me this error message.

From https://github.com/DanielnetoDotCom/YouPHPTube
   5d014bd2c..331b83e89  master     -> origin/master
Updating b194cca81..331b83e89
error: Your local changes to the following files would be overwritten by merge:
        .htaccess
Please commit your changes or stash them before you merge.
Aborting
. Please help!!!!!!!

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform
