### ISSUE TITLE
VideoThumbnails Not generating thumbs

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3239]
After the last commits , too many bugs .
The encoder does request the videos , but the thumbs does not get saved . No errors on logs

Encoder

```
CreateSpirits: ffmpeg -i "https://YZW.com/videos/_ID_Low.mp4?globalToken=JUcUNsMmpDalZuWXphSHAzcVdlcFNhV2EvdFY5NzNpNFl4RVE9PQ==" -map 0:v:0 -vf fps=1/0.53 -s 200x112 /var/www/html/YouPHPTube-Encoder/videos/thumbs_ID/out%03d.png
[14-Jun-2020 02:56:23 Europe/Helsinki] CreateSpirits:  removing directory /var/www/html/YouPHPTube-Encoder/videos/thumbs_ID/
```

Streamer : 

```
AVideoLog::DEBUG: createStprits: created old=[147137] new=[147137] /var/www/html/YouPHPTube/videos/_ID_thumbsSprit.jpg
[14-Jun-2020 03:15:03 Europe/Helsinki] AVideoLog::WARNING: Warning: The plugin [VideoThumbnails::getHeadCode] takes 0.1271 seconds to complete. 
[14-Jun-2020 03:15:03 Europe/Helsinki] AVideoLog::WARNING: /var/www/html/YouPHPTube/view/index.php
```

Notes , the videos does work perfectly . Not an issue related to videos

**Comment by DanielnetoDotCom** [comment]
Please try to update again. we had a problem regarding the tmp dir in non Ubuntu installations.

please let me know if it still persist

**Comment by DanielnetoDotCom** [comment]
I found something that may be related to it.

**Comment by akhilleusuggo** [comment]
yes , so it looks like everything solved .
Since the thumbs did existed , nothing has trascoded after the update . 

Thanks
