### ISSUE TITLE
need Help! few issue afteri paid for fresh install

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#3240]
hello i paid for the fresh install serivce, after the install was done there are still a few issu's with ir 
1. user's are coming up with channel name "unknown user" when admin try to change channel name
it stays as Unknow user.

2. when using obs on a users account it get reconnecting error

3. smtp is not wroking it fails to send the email i have follow the steps  including gmail setting
i even made a new gmail account  to try it and still not working.

i need at least 1 and 2 fix asap

you can test these issue 1 and 2 by making a new account at https://freedomshare.net

or by clicking a video on site you will see issue #1

**Comment by DanielnetoDotCom** [comment]
You paid for the installation and it was done. the support is a
separate price (50 USD/hour).
Now is easier to help you as long as I have access to the server.


> user's are coming up with channel name "unknown user" when admin try to
> change channel name
> it stays as Unknow user.
>

there is a configuration for that, I can guide you on Github


> when using obs on a users account it get reconnecting error
>

does not make sense, also I tested it before delivery
I guess is some misconfiguration in your side or you changed something on
the server or network


> smtp is not wroking it fails to send the email i have follow the steps
> including gmail setting
> i even made a new gmail account to try it and still not working.


Not sure about Gmail, you should try another SMTP provider as I guide here
https://github.com/WWBN/AVideo/wiki/Setting-up-AVideo-Platform-to-send-emails#alternatives-smtp-providers



Atenciosamente

Daniel Neto

Master in Systems and Computing (2009)
Specialist in WEB Systems and Applications (2005)
http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4252385T9

PHP ZEND 4/5 Certified Engineer
PHP Zend Certification - Authentication
http://zend.com/zce.php?c=ZEND001318&r=209210010

Programming in HTML5 with JavaScript and CSS3 Specialist (MCP 70-480)
https://mcp.microsoft.com/authenticate/ValidateMCP.aspx
Transcript ID (1040640) and the Access Code (danielNeto)

**Comment by freedomshare** [comment]
i have not even logged in to the server at all since you have been done i sent you screen shots of obs not working in email.. 

i am talking about the users account not the admin

This is the info to a users account not admin, and all it say is reconnecting this is the info the site provied and i copy and pasted in to obs and dont work
 Stream name/key:
rtmp://freedomshare.net/live?p=f321d14cdeeb7cded7489f504fa8862b/5ee4e15c09296
5ee4e15c09296

**Comment by freedomshare** [comment]
also i am not putting more money out ive spent alot and had no return on the money ive spent and my site been up for over 6 months i just spent another $500 with in the last few days and this is after i paid for all the plugsin already and ...  so paying for emails is not and opistion for me at all at this current time, for email iv tested my gamil account on other sites and works fine just dont work here... 

and after spend that much i was expecting my site to work like your site do...

**Comment by freedomshare** [comment]
whta setting is i need to config for the user name?

**Comment by freedomshare** [comment]
i can run the sudo git pull to fix this now right?

**Comment by DanielnetoDotCom** [comment]
First I apologize now I notice this issue is already on GitHub, I thought it was something from the email.

> user's are coming up with channel name "unknown user" when admin try to change channel name it stays as Unknow user.

I just sent an update that fix this problem

> when using obs on a users account it get reconnecting error

I just made a live from OBS and works fine. maybe is something in your internal network

![image](https://user-images.githubusercontent.com/18009293/84596751-ea8f9700-ae35-11ea-8a18-a3308be0aa51.png)

> smtp is not wroking it fails to send the email i have follow the steps including gmail setting

You are getting this from GMAIL

```
[14-Jun-2020 06:35:02 Asia/Chongqing] AVideoLog::ERROR: SMTP ERROR 2; message: SERVER -> CLIENT:
[14-Jun-2020 06:35:02 Asia/Chongqing] AVideoLog::ERROR: SMTP ERROR 1; message: SMTP NOTICE: EOF caught while checking if connected
[14-Jun-2020 06:35:02 Asia/Chongqing] AVideoLog::ERROR: SMTP ERROR 3; message: Connection: closed
[14-Jun-2020 06:35:02 Asia/Chongqing] AVideoLog::ERROR: SMTP ERROR 3; message: SMTP Error: Could not authenticate.
[14-Jun-2020 06:35:02 Asia/Chongqing] AVideoLog::ERROR: SMTP ERROR 3; message: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
```

For sure something regarding your credentials. try another SMTP provider, there are a lot of free ones on the internet.

**Comment by DanielnetoDotCom** [comment]
> i can run the sudo git pull to fix this now right?

I already did in your site.

**Comment by freedomshare** [comment]
ok i will try one from my web hosting  bussiness and see if that helps

**Comment by freedomshare** [comment]
also thanks for updating it :)

**Comment by freedomshare** [comment]
one more thing and you test obs on mobile see if that works to this is theone i tryed on also just to confirm 
rtmp://freedomshare.net/live?p=f321d14cdeeb7cded7489f504fa8862b/5ee4e15c09296
is the right link i have to use for obs and add tehe key right?

**Comment by DanielnetoDotCom** [comment]
First careful showing your credentials here (I edit it for you)

OBS on mobile? I am not aware of it. the OBS I have is desktop.

what app are you using on Mobile? the Whitelabel? the Whitelabel APP does not require the RTMP credentials, it is automatic

That is how to use the keys on OBS

![image](https://user-images.githubusercontent.com/18009293/84598286-0bf58080-ae40-11ea-8527-c5c1fae6560f.png)

**Comment by freedomshare** [comment]
sorry streamlabs is the app i use it worked on the old server, is there any way to set tthe settings up so it dont put the / 343242 

ill try stream labs app again in a few mins

**Comment by DanielnetoDotCom** [comment]
Screenshot the streamlabs option settings

**Comment by freedomshare** [comment]
cant right now not logged in to github on my phone

**Comment by freedomshare** [comment]
the reason i am trying to get it to work is so that they do not have to stream from app and they can still watch the live chat in my andriod app 
streamlab app allows run in background  and this would allow them to use both app at the same time and also be able to read the live stream chat at the same time

**Comment by freedomshare** [comment]
![Screenshot_20200614-171233_Streamlabs](https://user-images.githubusercontent.com/60738260/84603176-613e8b80-ae5a-11ea-9d05-064173708590.jpg)
![Screenshot_20200614-171339_Streamlabs](https://user-images.githubusercontent.com/60738260/84603177-626fb880-ae5a-11ea-8475-f99fa7c4f961.jpg)
![Screenshot_20200614-171349_Streamlabs](https://user-images.githubusercontent.com/60738260/84603181-63a0e580-ae5a-11ea-85e5-ca1c82b49a28.jpg)
![Screenshot_20200614-171354_Streamlabs](https://user-images.githubusercontent.com/60738260/84603184-64d21280-ae5a-11ea-9616-d3dff2772200.jpg)
![Screenshot_20200614-171412_Streamlabs](https://user-images.githubusercontent.com/60738260/84603187-669bd600-ae5a-11ea-92f4-e3479d739540.jpg)

**Comment by freedomshare** [comment]
and it will say "retrying  to reconnect"
it as if server rejecting the auth

**Comment by freedomshare** [comment]
![Screenshot_20200614-172147_Streamlabs](https://user-images.githubusercontent.com/60738260/84603304-589a8500-ae5b-11ea-8575-e454a7344948.jpg)

**Comment by freedomshare** [comment]
![Screenshot_20200614-172345_Streamlabs](https://user-images.githubusercontent.com/60738260/84603321-8384d900-ae5b-11ea-969d-6ea2469500b6.jpg)

**Comment by DanielnetoDotCom** [comment]
Looks like streamlab send the parameters differently.

I sent a fix, please try it again.

**Comment by freedomshare** [comment]
it is still the same when i turn old server on streamlabs works on there this is very odd

**Comment by DanielnetoDotCom** [comment]
sorry, please try again. I found the problem

**Comment by freedomshare** [comment]
same issue you can also download stream labs on iphone too

**Comment by DanielnetoDotCom** [comment]
I could make the streamlab publish on the site

but detect it is live and record the file is not possible due to the stream lab that sends variables differently from any other RTMP publisher.

the Live name should be the Live key. and Streamlab always send the word (live) what is the application name, NOT the live key

![image](https://user-images.githubusercontent.com/18009293/84650078-f5056b80-aedd-11ea-9f2a-8cf14396406b.png)

## The recorder Plugin

Files from any other publisher
```
-rw-r--r-- 1 www-data www-data 424K 6月  14 01:59 5ee4e15c09296-14-Jun-20-01:59:08.flv
-rw-r--r-- 1 www-data www-data 216K 6月  14 15:16 5ee5c42a8fb9a-14-Jun-20-15:16:20.flv
```

Files from Streamlab
```
-rw-r--r-- 1 www-data www-data 165K 6月  15 18:43 live-15-Jun-20-18:43:15.flv
-rw-r--r-- 1 www-data www-data 729K 6月  15 18:44 live-15-Jun-20-18:43:28.flv
-rw-r--r-- 1 www-data www-data 3.9M 6月  15 18:55 live-15-Jun-20-18:52:17.flv
```


![image](https://user-images.githubusercontent.com/18009293/84650208-2b42eb00-aede-11ea-9a16-81c7fcce970c.png)

`[15-Jun-2020 18:55:21 Asia/Chongqing] AVideoLog::DEBUG: on_record_done ERROR: Pattern does not match /.*\/5ee6365d0db94-(.*).flv$/`

**Comment by freedomshare** [comment]
ok thanks for trying it must be a new thing they did it was working on youphptube 8.6 i use to stream mobile legends with streamlabs
