### ISSUE TITLE
Manage video tags

### ISSUE THREAD

**Issue by jimhtwong** [WWBN/AVideo#3241]
Hi Daniel,

I found that there is a plugin - video tag. I tried to install it and create some tags. I edit a video and input a value and save. But I found that the value is seen in other videos. Any idea?

Jimmy

**Comment by DanielnetoDotCom** [comment]
Can you please detail what did you see and what you expect?

**Comment by jimhtwong** [comment]
I want to give some hashtags to a video. I can click to show the hashtag. Adding hashtags allows me to search a video easily.

For example, I can give "Dog", "Anmial", "Wild Animal" to a video. When I search "Wild Animal", I can find out the video.

**Comment by DanielnetoDotCom** [comment]
I guess that is what video tags plugins suppose to do

https://github.com/WWBN/AVideo/wiki/Tags-and-Keywords

**Comment by akhilleusuggo** [comment]
Well , it's supposed to work on this way
