### ISSUE TITLE
Don't allow user to pause or stop a video

### ISSUE THREAD

**Issue by jimhtwong** [WWBN/AVideo#3242]
Hi Daniel,

Can we have a feature to disallow a user to pause or stop a video with autoplay?

Jimmy

**Comment by akhilleusuggo** [comment]
It could be , but I don't see the goal ...

Need to disable clicks on the page , and use an invisible layer on the video

**Comment by DanielnetoDotCom** [comment]
Hi @jimhtwong 

If you are willing to sponsor that feature I can add.

please send an email to developer@youphptube.com for a quote

**Comment by jimhtwong** [comment]
Yes i can be the sponsor
