### ISSUE TITLE
Update your Youtube-DL NOT Working

### ISSUE THREAD

**Issue by jimmyk1** [WWBN/AVideo#3244]
Site not encoding keep getting update Youtube-DL error, thumbnails not loading when embed video, duration reads EE:EE:EE. Been trying to update DL with no luck for 400th time error logs say:

PHP Warning:  Module 'curl' already loaded in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'gd2' (tried: /usr/lib/php/20170718/gd2 (/usr/lib/php/20170718/gd2: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/gd2.so (/usr/lib/php/20170718/gd2.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'openssl' (tried: /usr/lib/php/20170718/openssl (/usr/lib/php/20170718/openssl: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/openssl.so (/usr/lib/php/20170718/openssl.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

I may be missing a library on my Ubuntu 18 server, not sure.

Can anyone help?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Error Logs**
Provide the log files at the moment you found the issue.
If you are not sure how to find the log file, please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DanielnetoDotCom** [comment]
Looks like too many errors for me.

Those errors are server/installation errors. you should google to fix all of them first. then test again.

**Comment by ronaldod** [comment]
your php path is troubling: `/usr/lib/php/20170718/`  It say it can not find a module. Check if those modules even exists and are accessible.
These errors are not caused by AVideo but by your php installation.
