### ISSUE TITLE
ENCODER GIVING ERROR 

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#3245]
**Describe the bug**
Used to work perfectly but now is not working i bought the plug in to record live stream but now i cannlt upload anything. Also i am not that tech on how to get logs so i can post them here so you know what is wrong is someone can give me the codes will be helpful. 
![Screenshot_20200615-151356_Chrome](https://user-images.githubusercontent.com/63973045/84696698-e1c4c100-af1a-11ea-9cc3-670ab3122834.jpg)

**Comment by DanielnetoDotCom** [comment]
Check your encoder log files https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by LATINMIXMASTERS** [comment]
Sorry i have check all that , but still confused on how to check that sorry for my ignorance. O have read so many problems but never can find right language to detect the issue. I installed as instructed and was functioning correctly and have my own encoder but i just need example.of commands. If you can provide thanks.

**Comment by DanielnetoDotCom** [comment]
First, share your log here. we may help you to find the issue.

**Comment by LATINMIXMASTERS** [comment]
I would love to but a little confusing lets see if i find the way  to get them.

**Comment by LATINMIXMASTERS** [comment]
Sorry i am installing again everything so i can learn but now where is the github for ngnix now i cannot find it anywhere i can install the first part but missing the second live streaming. if i get the same issue i had here let you know.

**Comment by LATINMIXMASTERS** [comment]
Now all file are not there correctly like a few days ago and now qith password i was trying to set it up again to see if i will get the same error of encoding but i cannot do anything. 
![20200622_004511](https://user-images.githubusercontent.com/63973045/85249408-adbd3480-b421-11ea-8f0b-85b45a946cc0.jpg)

**Comment by akhilleusuggo** [comment]
try not to copy/past everything , go step by step . Defenetly the issue is coming from you : 

![image](https://user-images.githubusercontent.com/52116577/85251621-70c56200-b462-11ea-847b-103eed157d9f.png)

**Comment by LATINMIXMASTERS** [comment]
I did both and the got same error and also the nginx code is not there anymore i erased everything to start all over again but now on github cannot find the nginx set up , i will do again one by one but got same error twice and then i copied the whole thing too.

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

**Comment by LATINMIXMASTERS** [comment]
Ok thank you daniel for the Installation, i will test now everything let you know if any issue we can close this for now.
