### ISSUE TITLE
can't upload video to encoder

### ISSUE THREAD

**Issue by josefsj3m** [WWBN/AVideo#3246]
I have installed Avideo and the encoder. The installations where smoothly, but when I try to upload a video to the encoder I get an error due to mixed content, as I am using https chrome is saying that the javascript library is requested using http.
Am I missing some config? Do I need to adjust the code to use https?
Thanks in advance.

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by josefsj3m** [comment]
As you can see the issue is related to the request to jquery.fileupload.css and jquery.fileupload-ui.css.
To reproduce the issue you need to log in the encoder. 

![screenshot](https://user-images.githubusercontent.com/5265061/84784972-4dfa0000-afc1-11ea-983b-8681058e28d5.png)

**Comment by akhilleusuggo** [comment]
ok , try this out : https://github.com/WWBN/AVideo/wiki/Redirect-http-to-https

Remember to restart apache2

**Comment by josefsj3m** [comment]
Thanks, it works now.
