### ISSUE TITLE
Plug in support Ver9.1

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#3247]
Do we use AD plugin and customer's Plugin under AVideo Ver9.1 ?

**Comment by DanielnetoDotCom** [comment]
Sorry what plugin?

**Comment by hnagasawa** [comment]
LoginLDAP and LoginLDAP_DYNA (LoginLDAP_DYNA)

**Comment by DanielnetoDotCom** [comment]
It suppose to work

**Comment by hnagasawa** [comment]
Thank you for your support
