### ISSUE TITLE
Transfer issues after update ( duplicated transfers )

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3248]
The videos are transferred to the streamer server , as 3 different videos .

![image](https://user-images.githubusercontent.com/52116577/84863557-c0301a80-b07d-11ea-9474-4f3f21339a50.png)

Each one correspond for 1 quality ( Low,SD,HD )

Also getting error for thumbnails and webps . 

```
AVideoLog::WARNING: Warning: The plugin [User_Controll::onUserSignIn] takes 0.1597 seconds to complete. 
[17-Jun-2020 07:31:40 Europe/Helsinki] AVideoLog::WARNING: /var/www/html/YouPHPTube/objects/aVideoEncoderReceiveImage.json.php
[17-Jun-2020 07:31:40 Europe/Helsinki] AVideoLog::DEBUG: ReceiveImage: Permission denied to edit a video: Array
```

**Comment by DanielnetoDotCom** [comment]
Hi

The problem is here 

`ReceiveImage: Permission denied to edit a video: Array`

But I do not know what is causing it in your side 

Does this happen Once or is happening all the time?

**Comment by akhilleusuggo** [comment]
Only after update

**Comment by DanielnetoDotCom** [comment]
I mean, if you upload a video now will it happen?

I am saying this because this error may happen if you change the user password. but if you logout the encoder and login again the error may dissapear.

**Comment by akhilleusuggo** [comment]
I found why . The videos that were on the encoder queue , were the ones with this issue . That means , I had to reset 67 videos on the encoder queue .
