### ISSUE TITLE
Home cannot show images

### ISSUE THREAD

**Issue by jimhtwong** [WWBN/AVideo#3249]
Hi Daniel,

My home is not showing images. Do you know why?

![2020-06-17 22_35_38-Streaming](https://user-images.githubusercontent.com/31052247/84911587-eb9d1e80-b0ea-11ea-8657-8a62676340cf.png)

**Comment by DanielnetoDotCom** [comment]
Depends on how you are uploading.

is it direct upload or are you using the encoder?

please read those links

https://github.com/WWBN/AVideo/wiki/About-Video-Upload

https://github.com/WWBN/AVideo/wiki/Automatic-Thumbs-(JPG-GIF)-on-direct-uploaded-MP4-videos

**Comment by jimhtwong** [comment]
We saw from the videos folder. There are no thumbnails created. It seems there is a problem in creating thumbnails. How can we fix it?

**Comment by jimhtwong** [comment]
Hi Daniel, we got it solved.

**Comment by DanielnetoDotCom** [comment]
Please tell us how did you resolve it
