### ISSUE TITLE
How do I install the video dir into a different hard drive?

### ISSUE THREAD

**Issue by nsturtz2** [WWBN/AVideo#3250]
I have a hard drive that I have just for this, how do set it to put all the video there?

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/Can-I-store-my-videos-in-another-location#store-to-another-driver-on-the-same-server

Make sure to backup first

**Comment by nsturtz2** [comment]
that dose not work for me

**Comment by akhilleusuggo** [comment]
if you move them and create a symbolicLink should work .

**Comment by nsturtz2** [comment]
I get this 
![image](https://user-images.githubusercontent.com/56239895/85073524-90b60680-b180-11ea-84cf-f0984a1f2e06.png)

**Comment by nsturtz2** [comment]
Never mind I went with someone else,
