### ISSUE TITLE
BigVideo in Gallery are blurred

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#3252]
BigVideo in Gallery are blurred when scrolling to the next BigVideo accept the first one,
Only the pictures are blurred, the GifOnBigVideo are okay.

![Snap1](https://user-images.githubusercontent.com/39981177/84949943-5865e800-b0ee-11ea-8796-7d03ed53712f.jpg)

![Snap2](https://user-images.githubusercontent.com/39981177/84949962-60258c80-b0ee-11ea-90a4-6a8cb6b107eb.jpg)

**Comment by DanielnetoDotCom** [comment]
Check your js console.

this is probably a Javascript error

**Comment by TLCReuver** [comment]
This 'Carousel'_problem displayed in 4 webbrowsers & on 3 browsers om smartphone:

The only errors what i found are:


Failed to load resource:
net::ERR_BLOCKED_BY_CLIENT


DevTools failed to load SourceMap: 
Could not load content for https://www/myhomepage.nl/videos/cache/js/bootstrap-select.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by DanielnetoDotCom** [comment]
that means your browser is blocking the script. ERR_BLOCKED_BY_CLIENT

maybe if you provide a screenshot of the console will help more.

**Comment by TLCReuver** [comment]
Snapshot 1:
![Snap1](https://user-images.githubusercontent.com/39981177/85037863-31f38b80-b186-11ea-947f-ee58df5d8798.jpg)

Further a noticed an other error in Firefox that is not in Chrome:
![Snap2](https://user-images.githubusercontent.com/39981177/85038005-5ea7a300-b186-11ea-971c-8b10af169c4a.jpg)

https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects

**Comment by DanielnetoDotCom** [comment]
definitely I cannot see any problem.

is your site accessible from a public network? can you share your link?

**Comment by TLCReuver** [comment]
Yes on https://media.beesel-reuver.nl

I disabled all addblocker for all browsers an it show only the *_thumbsSmallV2.jpg and *.gif

**Comment by TLCReuver** [comment]
Found also an error in htacess.log:

GET /videos/cache/js/bootstrap-select.js.map HTTP/1.1 (Error 404)

**Comment by DanielnetoDotCom** [comment]
Ok, problem confirmed.

please try this fix.

**Comment by TLCReuver** [comment]
Updated footer.php by github
Cleared cache website & browsers but still see *_thumbsSmallV2.jpg and *.gif

**Comment by TLCReuver** [comment]
Unfortunately no.

**Comment by DanielnetoDotCom** [comment]
If you modify some files you may review them

![image](https://user-images.githubusercontent.com/18009293/85058226-2a2cea80-b178-11ea-9470-a6e5358b4fdb.png)

https://github.com/WWBN/AVideo/blob/345f5eea26275e722143935b8890481a87c18a06/plugin/Gallery/view/mainArea.php#L102

**Comment by TLCReuver** [comment]
Sorry for late reaction:

I changed in BigVideo.php @ line 73 $images->thumbsJpgSmall into $images->poster and everything is perfect now.

Thanks 
![Snap3](https://user-images.githubusercontent.com/39981177/85304190-c07c4b80-b4ab-11ea-819e-97ce2da07742.jpg)
