### ISSUE TITLE
Chat2 Plugin Login Issue

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#3253]
**Describe the bug**
On my Samsung Note 10 when I try to Login to Chat, I click on Login and click in for the username it just goes back to the Chat window.

**To Reproduce**
1. Go to 'Chat when not logged in'
2. Click on 'Login'
3. Click on 'where to type either username or password'
4. As soon as you click on username or password it reverts back to chat window.  If you login through the other sign in options though the menu or icon top right corner.  As soon a you click in the chat section, keyboard pops up for a split second.  I think iPhone is fine except I'm told when you click on to chat the video disappears.
Tried different mobile browsers (Chrome, Internet, Safari) on iPhone and Android with issues.

![Chat](https://user-images.githubusercontent.com/65576427/84962509-72e39580-b0dd-11ea-991e-55e75d313040.jpg)

**Comment by akhilleusuggo** [comment]
same here

**Comment by D-Spayre** [comment]
I also noticed when you type something in the chat on computer and when you add an emoji it sometimes adds the emoji to the start of the sentence even though the cursor is at the end.  If you click the end of the sentence then add an emoji it will add it to the end. 
Also with iPhone the chat window will float even though it's set to static in the Chat menu.

Feature if possible:
Allow pictures right from the mobile camera, without having to leave the chat window and maybe short video clips like 3sec. :)

Thanks

**Comment by DanielnetoDotCom** [comment]
Hi regarding the "As soon as you click on username or password it reverts back to chat window"

I try it on the demos site and I could not reproduce it.

maybe you have to update your site and the chat2 plugin. can you please download the chat and update it to make sure we are in the same page?

**Comment by D-Spayre** [comment]
Hi

I tried the demo site and it's doing the same thing.

https://streamable.com/p2f8nt
This is on a Note 8 tried different browsers.

**Comment by DanielnetoDotCom** [comment]
what exactly browsers did you notice those behaviors?

**Comment by D-Spayre** [comment]
Chrome
Internet 
Firefox 

All three had the same issue. 

Thanks

**Comment by DanielnetoDotCom** [comment]
Can I test it directly on your site?
I cannot reproduce it here

**Comment by D-Spayre** [comment]
I can send you the site link to and email if that works?

But I'm having the same issue on the demo site.  Had some users having issues with iPhone using safari.  The chat was over the video.  I don't have an iPhone to test but here's a screen shot.

![file_15924387675eeaafef88bb5 1](https://user-images.githubusercontent.com/65576427/85345092-e7487b00-b4c7-11ea-858d-eaf7c4d55520.jpg)

**Comment by DanielnetoDotCom** [comment]
@D-Spayre I am confused what is the issue.

is the site over the video or when you click in the login fields it redirects you?

lets comment 1 at a time. maybe open a new issue if you have others.

so the same happens on the demo site when you try to login?

**Comment by D-Spayre** [comment]
Sorry I'm throwing a couple of different issues at you.

Main one is that I can't login using login on the chat window. As per this post https://github.com/WWBN/AVideo/issues/3253#issuecomment-646117368

Thanks

**Comment by DanielnetoDotCom** [comment]
Ok but the login issue can you reproduce it in demo site?

**Comment by D-Spayre** [comment]
When I click the login button on the chat window. As soon as I click in to put the user name it closes the login window and doesn't allow login from the chat window. 

Trying to login
https://streamable.com/tkhhvb

Thanks

**Comment by DanielnetoDotCom** [comment]
Ok, thanks I can see you are having this issue on mobile.
does the same happen on PC web browser?

**Comment by D-Spayre** [comment]
No just mobile. I think iPhone maybe ok but I tried 2 note 10s and both do the same on 3 different browsers.

**Comment by syldri** [comment]
hello @DanielnetoDotCom  
I confirm it's a bug I have the same problem on samsung galaxy note 10 and on samsung galaxy note 9

**Comment by DanielnetoDotCom** [comment]
Looks like the virtual keyboard is reloading the iframe.

I still not found any solution for that.

**Comment by DanielnetoDotCom** [comment]
Hi, I guess I found a solution for that. you will need to update your streamer and also the Chat2 plugin

**Comment by syldri** [comment]
Hallo @DanielnetoDotCom   thank you very much I tested everything is ok
