### ISSUE TITLE
cannot login to the website misconfigured credentials

### ISSUE THREAD

**Issue by NAndras95** [WWBN/AVideo#3254]
**Describe the question**
I installed the application successfully, and then configured, but accidentally the only authentication mode is LDAP which is not correctly configured. Now Im unable to login and change a settings. I tried change this from database but I don't know what is the value the enable. As you see I tried 1 which is not working.
<img width="833" alt="Screenshot 2020-06-18 at 11 40 29" src="https://user-images.githubusercontent.com/29740675/85005011-854ee500-b158-11ea-8fcb-57de8ac57c52.png">

Any idea?

**Comment by DanielnetoDotCom** [comment]
Try truncate the plugins table and all plugins will return to default.

then you will have access again and will need to reconfigure it

**Comment by NAndras95** [comment]
> Try truncate the plugins table and all plugins will return to default.
> 
> then you will have access again and will need to reconfigure it

Thanks, worked.
