### ISSUE TITLE
stmp is not working i have try gmail outlook even my domain name host

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#3256]
hello i can not get stmp to work for the life of me i have followed all guys i have tryed 
gmail
outlook 
hotmail 
my own server mail
my domain host... 

non of the stmp will work...

**Comment by freedomshare** [comment]
is there a port i have to open on my server or something?

**Comment by GodgivenButhelezi** [comment]
did you come right ? if you did not i can help you out.
