### ISSUE TITLE
When Video Plays it Alway starts Muted in app and on site

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#3257]
hello not sure if a bug or a setting but on app and in site when u click on a  video all the videos start muted is there a way to turn this off or is it a bug?

**Comment by akhilleusuggo** [comment]
That's called autoplay policy . 
https://github.com/WWBN/AVideo/wiki/Autoplay-and-Browser-Policies

**Comment by freedomshare** [comment]
ok but whydose it happen in app?

**Comment by freedomshare** [comment]
can i turn auto play off?

**Comment by akhilleusuggo** [comment]
You can do it

**Comment by freedomshare** [comment]
how? also would anyone  be intrested in getting the mute working on all browsers? 
id be will to pay, im not the great with linux

**Comment by akhilleusuggo** [comment]
It's the policy , is not you like it or not .

If you don't wanna autoplay the video , there's a better solution without changing the code . 

Disable this option : 
![image](https://user-images.githubusercontent.com/52116577/85131273-22844900-b23f-11ea-8c21-45b93a49fe0f.png)

It's under `Site Configuration - Regular Configuration ` You need to be logged as admin

**Comment by freedomshare** [comment]
okay thank you that work! 
id also still be willing to pay to change the code to have it working  if anyone intrested

**Comment by DanielnetoDotCom** [comment]
Hi

the app works with html5 embed player. that is why reflect the policies

**Comment by freedomshare** [comment]
oh how much would it cost to change it

**Comment by DanielnetoDotCom** [comment]
change it means to build a whole new app.

I do not think it worth;

**Comment by freedomshare** [comment]
oh  one more question how do user add video to playlist in app

**Comment by DanielnetoDotCom** [comment]
Right now we only have support to it on the website.

**Comment by freedomshare** [comment]
ok, will you be adding on to the mobile app api key to be able access admin panel and  channels , access to users settings? in future updates?

**Comment by DanielnetoDotCom** [comment]
Yes we will for sure.

we want to add more features on the mobile but right now we are focused on the site.

**Comment by freedomshare** [comment]
ok great thats good to hear thank you was just woundering keeo up the good work
