### ISSUE TITLE
all your plugins don't work

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3258]
Hello ,
it's starting to do a lot all your plugins i buy don't work there are bugs everywhere

when a person buys a product it should work without problem with you the 6 plugins buy there is shit everywhere

I'm not going to spend my time sent messages to get answers without solution

I send you an email with my problem give a solution or I request a refund on everything I bought

don't forget with paypal i will be reimbursed i am not an individual 

the worst all your plugins encrypt if you want to solve a problem it is impossible

**Comment by DanielnetoDotCom** [comment]
If you provide the informations we requested in the issues you have opened, for sure we can help you make all your plugins work
