### ISSUE TITLE
Warning! We have not found any videos or audios to show

### ISSUE THREAD

**Issue by josefsj3m** [WWBN/AVideo#3259]
I installed the avideo media and the encoder in a fresh Ubuntu installation. Both installations finished successfully.
I uploaded a video using my private avideo encoder and I can see the video when I'm logged in as an admin. But, I can't see it on the home page, the message that is shown is "Warning! We have not found any videos or audios to show". It is a public video on default category.
Am I forgetting some setting to show it on the home page?

Thanks,

**Comment by ronaldod** [comment]
After 2-3 video's uploaded it will shows. One video will show you message.

**Comment by josefsj3m** [comment]
Thanks, after 3 videos it hows the videos.
