### ISSUE TITLE
Opção de Upload não aparece!

### ISSUE THREAD

**Issue by brunomsk9** [WWBN/AVideo#3260]
**Describe the question**
A clear and concise description of what is your question.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

Boa noite, a opção de Upload não aparece no painel de administração.

**Comment by DanielnetoDotCom** [comment]
Veja aqui como fazer upload https://github.com/WWBN/AVideo/wiki/About-Video-Upload
