### ISSUE TITLE
Encoder Video

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3262]
I did some tests I do not find I would like to do so that the encoder chooses only HD for recording

I did a 40 minute live video the video was 2.9 G

is there a possibility to compress the video a little more but to keep a good resolution?

**Comment by DanielnetoDotCom** [comment]
The compress and the resolution depend on your FFMPEG command. you can customize it in your encoder -> configuration tab.

the best results for you I am not sure, maybe you can make some tests with different configurations.

**Comment by ronaldod** [comment]
This is tested before by someone. Has also good graphics as it is a trade of between speed of encoding and the compression it can do. And of course the resolution.
You can find the results of that [here](https://write.corbpie.com/ffmpeg-preset-comparison-x264-2019-encode-speed-and-file-size/)

**Comment by akhilleusuggo** [comment]
The thing I would recommend you is switching from mp4 to webm if your concern is the quality/disk space used . libvpx-vp9 is the best right now and is compatible with HTML5 ( it is very very slow , but if you have intel quicksync , than you are fine !
