### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3265]
hello 

i have a question i created a plugin

the plugin is in the folder plugin

when i'm in administration in plugin I don't see him

there is a very specific thing to do so that the plugin is visible

I would like to know
 what is this function i saw each plugin has a different number
`public function getUUID() { `

**Comment by DanielnetoDotCom** [comment]
Just make sure it is a unique number

**Comment by syldri** [comment]
@DanielnetoDotCom  

thank you very much the plugin works perfectly

**Comment by DanielnetoDotCom** [comment]
Awesome congrats
