### ISSUE TITLE
/status

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3266]
https://demo.avideo.com/status

Why do we need a /status for streamer site ? And why is revealing informations ? Is for the search.avideo.com to track ? 

`{"max_file_size":"6.00GB","file_upload_max_size":6442450944,"videoStorageLimitMinutes":0,"currentStorageUsage":0,"webSiteLogo":"videos\/userPhoto\/logo.png?1592683272","webSiteTitle":"AVideo Platform Demo","PHPSESSID":"aaa8tl41b6uavddf7jkvgqpm9v","version":"9.0","mobileSreamerVersion":2,"reportVideoPluginEnabled":false,"oauthLogin":[{"type":"Facebook","status":false},{"type":"Google","status":false},{"type":"Twitter","status":false},{"type":"LinkedIn","status":false}],"plugins":{"Chat2":{"showOnMobile":true},"Notifications":{"oneSignalEnabled":false,"oneSignalAPPID":"","oneSignalFIREBASE_SENDER_ID":"","oneSignalDebugMode":false}}}`

![image](https://user-images.githubusercontent.com/52116577/85211907-4f774f80-b356-11ea-8480-1df5b1137ff5.png)

**Comment by DanielnetoDotCom** [comment]
mobile app and encoder use it.

**Comment by akhilleusuggo** [comment]
but should be somehow restricted .

**Comment by DanielnetoDotCom** [comment]
do you see some sensitive information that should not be there?
