### ISSUE TITLE
Can streamer and encoder be on the same window

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3267]
please advise how to go about it if possible.

Thanks in advance!

**Comment by ronaldod** [comment]
What do you mean with the same window ? Same machine. Yes. It is all about correct sizing.

**Comment by vraghavans** [comment]
Hi,Thanks for the reply,My meaning was that in windows machine,once we click upload,the encoder window opens in another tab of the browser.can it open in the same tab was my question.
Thanks in advance!

**Comment by akhilleusuggo** [comment]
you mean the TAB . For now no . But you have create a submenu .

Here is one example from homeserver : You're required to have Menu plugin enabled 

![image](https://user-images.githubusercontent.com/52116577/85251049-f3e5b880-b460-11ea-8356-92a1f98855b7.png)

This one will open it on the same page .
If you customize it , could be open on the same page , and on the same streamer site .

**Comment by vraghavans** [comment]
Excellent !Thanks so much for guidance.it worked!
