### ISSUE TITLE
RMTP/Live Streaming add-on with Docker Config

### ISSUE THREAD

**Issue by lordforbes** [WWBN/AVideo#3268]
Hi there - I'm using the Ronaldod fork of Avideo for Docker. It's great and works beautifully, but I want to enable Live Streaming and enable RTMP and this doesn't work without adding to the configuration. Is this really as difficult as it seems? I mean can't we simply add an nginx-rtmp docker instance to the original package and provide everything in one set? I've tried to deploy a few docker flavours of nginx-rtmp (JasonRivers/Docker-nginx-rtmp, alqutami/rtmp-hls) and although I get the RTMP listener up, I'm not clever enough to know how to link it to avideo.   
If I need to donate something, let me know.
Great, great job though and I appreciate the effort this takes!

**Comment by ronaldod** [comment]
Will fix this week a flaw in the encoder source so it can use the original source from AVideo. After that i could look into an RTMP instance.

**Comment by lordforbes** [comment]
Great - thanks - look forward to it!

Good job

**Comment by lordforbes** [comment]
Hi there -  Appreciate you've had other things to take care of ... any news on  the RTMP instance ...? 

Thanks
