### ISSUE TITLE
A question on the dashboard

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3269]
Hello,
it would be good to also add the number of live that has on the site

do you plan to add this option?

![image](https://user-images.githubusercontent.com/39193219/85227093-6a3fd780-b3db-11ea-91ff-486f614afc96.png)

**Comment by DanielnetoDotCom** [comment]
Yes that is a good idea. The statistics and the dashboard will be rebuilder in the future

**Comment by syldri** [comment]
hello @DanielnetoDotCom  just a quick reminder to remember
