### ISSUE TITLE
question about AD_Server Plugin

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#3272]
AD_Server is there a way to add this in to the wallet system 
so user's can start there own video ad's? 
with out having to conact admin and having admin start the video ads?
also is there a link users can use to buy video ad space with this plugin?

just not too sure how this plugin works
my current under standing is that i have to set up the video ads via admin
also i have to try to find the customers off site 
and have the payment sent diectly to my paypal 
video has to be uploaded to my site etc
this is my current understanding

**Comment by akhilleusuggo** [comment]
There's something like that : 
![image](https://user-images.githubusercontent.com/52116577/85250525-7c635980-b45f-11ea-8a55-a4ab9be6fc9a.png)

But you need to approve it with admin . This is good to have to approve it with admin , you never know what customers may want to advertise

**Comment by freedomshare** [comment]
im looking for videos ads so user can submit them to admin and they can approve the video ads
could  this be done with the current vast plugin?

**Comment by DanielnetoDotCom** [comment]
@freedomshare we do not have this feature yet.

But it is a good idea, we may improve it in the future or if you want to sponsor it you can request a quote from us at the email developer@youphptube.com
