### ISSUE TITLE
YPTStorage plugin information

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3273]
@DanielnetoDotCom  hello 

if we bought the YPT Storage plugin  
with this server we can install a cdn to make the video faster 

why not also transfer the images to the YPTStorage plugin 

![image](https://user-images.githubusercontent.com/39193219/85244673-ac056800-b445-11ea-8ac3-70dfc4ed8213.png)

we can relieve the site server, and keep more bandwidth

**Comment by akhilleusuggo** [comment]
I asked daniel for something similar , a YPTStorage only for images , to git it a different subdomaine , and host it on the CDN .

This is a greate idea , but I don't know why daniel doesn't want to do it .

**Comment by DanielnetoDotCom** [comment]
Hi

Is not tested, but I guess your storage can be under a CDN
