### ISSUE TITLE
Am trying to update the site map and its telling file not created.Any help on why

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3274]
I had just now created a menu.not sure if its because of that

**Comment by akhilleusuggo** [comment]
please provide a screenshot or logs .

provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by vraghavans** [comment]
![image](https://user-images.githubusercontent.com/65802024/85258340-f823cd00-b484-11ea-9325-e4ea0dffe918.png)
![image](https://user-images.githubusercontent.com/65802024/85258894-d545e880-b485-11ea-8f68-1f43443cefd1.png)
Error logs from java and video folder.

Kindly advise
thanks in advance!

**Comment by akhilleusuggo** [comment]
I need the error on the moment you trying to create the sitemap . Not random logs 

Try to create the sitemap , and show the logs that correspond to the issue

**Comment by vraghavans** [comment]
Hi,Thanks for your reply.
Thats exactly what i did,
I was not able to see any errors.
thanks in advance!

**Comment by akhilleusuggo** [comment]
`chmod 777 /var/www/html/YouPHPTube/sitemap.xml`

Try this command line , and let me know

**Comment by vraghavans** [comment]
![image](https://user-images.githubusercontent.com/65802024/85272824-5018fe80-b49a-11ea-87d7-023770cc396f.png)
I put this command line
then went to website,again tried to create site map
still same error,this is the latest log file

**Comment by akhilleusuggo** [comment]
What error ?????????
I need to see the error , make a screen . No error on the logs , show the error, the actual error .

WinScp is not the best for this things , try `tail -f /var/www/html/YouPHPTube/videos/avideo.log`

**Comment by vraghavans** [comment]
![image](https://user-images.githubusercontent.com/65802024/85282035-a68d3980-b4a8-11ea-9a0c-c33f58ce3f35.png)
![image](https://user-images.githubusercontent.com/65802024/85282352-392dd880-b4a9-11ea-9dd9-a07f27d8d919.png)

These are the screen shot,Sorry for my ignorance
Thanks in advance!

**Comment by akhilleusuggo** [comment]
1 - `cd /var/www/html/YouPHPTube`
2 - `echo > sitemap.xml`
3 - `chmod 777 /var/www/html/YouPHPTube/sitemap.xml`
4 - `cd /var/www/html/`
5 - `chown www-data:www-data -R *`

**Comment by vraghavans** [comment]
Hi,thanks for you comment! and sorry for delayed reply,i still can make it work..same error.

**Comment by akhilleusuggo** [comment]
could you confirm that the sitemap.xml exists ?

`cd /var/www/html/YouPHPTube`
`ls -la `

Could you screenshot what you see after executing this command lines ?

**Comment by vraghavans** [comment]
hi thanks for your reply!
this is what i see
![image](https://user-images.githubusercontent.com/65802024/85392452-2bd82300-b569-11ea-9679-2d603a7456be.png)

**Comment by akhilleusuggo** [comment]
I see no reason not to create the sitemap . Make sure you don't see this : 

![image](https://user-images.githubusercontent.com/52116577/85393998-96339800-b556-11ea-9b2b-05b120c29e65.png)

![image](https://user-images.githubusercontent.com/52116577/85394101-b82d1a80-b556-11ea-99b6-131362efcf63.png)

**Comment by vraghavans** [comment]
![image](https://user-images.githubusercontent.com/65802024/85400517-23d2b000-b576-11ea-957d-18d1b1615e5a.png)
No,its all clean!

**Comment by DanielnetoDotCom** [comment]
@vraghavans are you still facing this problem?

**Comment by vraghavans** [comment]
yes,still saying the same error :(

**Comment by akhilleusuggo** [comment]
try 

`cd /var/www/html/YouPHPTube/`
`rm sitemap.xml`
`wget https://raw.githubusercontent.com/WWBN/AVideo/master/sitemap.xml`
`chmod 777 sitemap.xml`
`chown www-data:www-data -R *`


I'm doing this because your sitemap show 0kb . Hope this one could fix it

**Comment by vraghavans** [comment]
Hi Daniel,

Thanks,did this,still the same error

Rgds
Vijay

**Comment by KenRHill** [comment]
We are actually experiencing the same thing on our site.  I too have made a drop down custom menu. Not sure if it is related, but noticed it was in this thread. Tried all the above to resolve and it does not work.  Same "Sorry, file not created." error message appears.

**Comment by DanielnetoDotCom** [comment]
Fixed, @vraghavans had a character breaking the preg replace function.

but now should be fine

**Comment by vraghavans** [comment]
Thanks!,
Checked and working fine!
