### ISSUE TITLE
Missing words in translation file for Hebrew

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3275]
Here is a screen shot of the left side menu. Some words are not being translated and they are missing from the il.php file. Such as "Watch Later" and "Favorites".

How can I complete those words?
![Screen Shot 2020-06-22 at 10 42 28](https://user-images.githubusercontent.com/58882903/85261935-a9bb0200-b475-11ea-8630-80af29f4156c.jpg)

**Comment by ronaldod** [comment]
in /local are the translation tables.

**Comment by guymass** [comment]
As I pointed out in my post, the il.php file in /locale is missing those tanslations, even is I add myself the string Favorite and give it a translation this will not effect the front page, even after clearing cache etc... I cannot fined those specifics terms in the file.

**Comment by DanielnetoDotCom** [comment]
If the word is not there you can add the words just like is in the other translation files.
