### ISSUE TITLE
Always display a message  "we will back soon" how to fix.

### ISSUE THREAD

**Issue by GRNHACKER** [WWBN/AVideo#3277]
We’ll be back soon!
Sorry for the inconvenience but we’re performing some maintenance at the moment.

— The Team

**Comment by akhilleusuggo** [comment]
disable the plugin ! 

![image](https://user-images.githubusercontent.com/52116577/85394198-e1e64180-b556-11ea-97c8-69feb3e84e1e.png)

This one should fix your issue . Clear the cache afterwards .

**Comment by DanielnetoDotCom** [comment]
Actually this message is when you do not have database connection.

check your log files.

**Comment by GRNHACKER** [comment]
> Actually this message is when you do not have database connection.
> 
> check your log files.

thanx man its working

**Comment by askir56** [comment]
![image](https://github.com/WWBN/AVideo/assets/101177434/0e0e6bd5-44cb-4d81-9146-10f58cb642cb)

**Comment by DanielnetoDotCom** [comment]
It is probably your MySQL
