### ISSUE TITLE
Can't verify my Email on the Avideo Tutorials website 

### ISSUE THREAD

**Issue by TakeAchance365** [WWBN/AVideo#3279]
**Describe the question**
When i signup and try to verify my email i get this error message @DanielnetoDotCom 

**Screenshots**
![Annotation 2020-06-23 183631](https://user-images.githubusercontent.com/45086315/85478002-0f47e500-b581-11ea-8f54-6187d9f34bea.png)

**Comment by DanielnetoDotCom** [comment]
Hi

does it still a problem?
I check the log and I did not find anything related to it

**Comment by TakeAchance365** [comment]
Yes it's Still there when i go to the My Account page and i click the verify email i still get that error

**Comment by TakeAchance365** [comment]
@DanielnetoDotCom as a test you could make an account that the email is not verified and then Go to the my account page and verify the email like i did by clicking the verify email button but my guess is the site is having a problem talking to the Email server you setup in your site config just a thought

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by TakeAchance365** [comment]
![Annotation 2020-07-13 132231](https://user-images.githubusercontent.com/45086315/87341465-4ae62700-c50f-11ea-800c-d1e4e8fb2d82.png)


this is all i can see

**Comment by TakeAchance365** [comment]
![my test site](https://user-images.githubusercontent.com/45086315/87341729-b7f9bc80-c50f-11ea-9458-370a3610655d.png)

but on my website that i have on mine that works those errors are not there don't know if they are related too the problem or not though
