### ISSUE TITLE
Update to 9.1 received error 

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#3280]
I'm having an issue with updating to 9. 1.  I received the following at putting in sudo git pull command

error: Your local changes to the following files would be overwritten by merge:
        plugin/AVideoPlugin.php
        plugin/PlayLists/PlayLists.php
        plugin/Plugin.abstract.php
        view/include/navbar.php
        view/managerVideos_body.php
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by akhilleusuggo** [comment]
that means you have made changes on those files .
To over-write those files and update : 
`sudo git fetch --all && sudo git reset --hard origin/master`

**Comment by willpower68** [comment]
@akhilleusuggo 
thank you for responding.  should i right the commands exactly? 

sudo git fetch --all && sudo git reset --hard origin/master   

should this appear as one command then hit enter to execute the commands?

**Comment by akhilleusuggo** [comment]
Yes , you can copy/past

**Comment by willpower68** [comment]
@akhilleusuggo @DanielnetoDotCom 

I am still having an issue with update.   received this fatal error:  **fatal: ambiguous argument 'original/master': unknown revision or path not in the working tree.**

root@Empty:~# cd /var/www/html/YouPHPTube_
root@Empty:/var/www/html/YouPHPTube_# sudo git fetch --all && sudo                                                                     git reset --hard original/master
Fetching origin
remote: Enumerating objects: 78, done.
remote: Counting objects: 100% (78/78), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 67 (delta 38), reused 48 (delta 19), pack-reused 0
Unpacking objects: 100% (67/67), done.
From https://github.com/DanielnetoDotCom/YouPHPTube
   985b642..82b4cb9  master     -> origin/master
fatal: ambiguous argument 'original/master': unknown revision or path not in the                                                         working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
root@Empty:/var/www/html/YouPHPTube_memoriachannel# sudo git fetch -- all
fatal: 'all' does not appear to be a git repository
fatal: Could not read from remote repository.

**Please make sure you have the correct access rights
and the repository exists.**

**Comment by DanielnetoDotCom** [comment]
I am not sure about this error, maybe you can find a solution on google.

alternatively what you can do is, 

1. clone it somewhere else, for example to the directory YouPHPTube_memoriachannel_new
2. move the videos directory from the to the YouPHPTube_memoriachannel  new cloned directory YouPHPTube_memoriachannel_new
3. move the YouPHPTube_memoriachannel to YouPHPTube_memoriachannel_old
4. move the YouPHPTube_memoriachannel_new to YouPHPTube_memoriachannel

after that, you should have all brand new files, and also all your videos and database with the newest files.

**Comment by jengajenga** [comment]
OR, do what I did

Download a copy of each file that you modified.
Update and overwrite all the files.
Before each re-upload, rename the NEW FILE e.g., "navbar.php" can be "_navbar_.php" or whatever.
Re-upload each downloaded copy of the files one by one back to their respective directories.

You're welcome :)

**Comment by willpower68** [comment]
@akhilleusuggo  thanks for your help.  I was able update my site.  Thank you very much. 

@DanielnetoDotCom do the update direction still apply?  Is step 2 still required to complete update?
**"2 - Download and Upload files
Use your favorite file transfer to download a master copy of AVideo and upload it to your site."**
