### ISSUE TITLE
Pulling video from Youtube ,showing the attached error,please help

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3281]
![image](https://user-images.githubusercontent.com/65802024/85516866-4d461700-b61c-11ea-9eee-0ca6345699b1.png)

**Comment by akhilleusuggo** [comment]
provide the logs on the encoder site .
This should provide some clue , what on the script should be changed .
Because I saw that @DanielnetoDotCom has removed the Download Channel . Also sometimes the description or the title is not compatible .

**Comment by vraghavans** [comment]
This is the log for the error
![image](https://user-images.githubusercontent.com/65802024/85534956-660bf800-b62f-11ea-89a2-03c3d9a38aae.png)

**Comment by akhilleusuggo** [comment]
As you can see . The uploader has made this video not available in your country . ( remember , your country means the VPS/Dedicated server's country ) 

You can try to download it from home , and re-upload it to your platform .

**Comment by vraghavans** [comment]
Okies,noted! thanks for the help!!
