### ISSUE TITLE
play in background setting for mobile?

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#3282]
hi is there a setting for play in background on mobile phones?
for videos hosting on my site? (not embeded videos this i already know the answer to)
i have a webview app and if i remember correcetly it use it play in background for videos that where uploaded on site
back in 8.6V 

i also have the paid app for android too

**Comment by DanielnetoDotCom** [comment]
Hi

there is nothing changed regarding play on the background. If it plays in the past it may be something in your OS or browser.

but to make the mobile play on the background may require some changes in the mobile app. I am not sure what must be changed yet. but I can look for it if you really want it and want to sponsor that change.

**Comment by freedomshare** [comment]
i figured what it was sound cloud embeded videos play in background on all apps and mobile 

play in background can be really use full for the apps for all the videos tho.

look in to it and let me know on it

**Comment by DanielnetoDotCom** [comment]
what do you mean? sound is always in background?

**Comment by freedomshare** [comment]
yes let say you have the app open and wanted to share the video it will take you to your social media app the video stops at the current time, but if you had play in background the video and sound still plays even if your phone screen locks 

witch helps save battery power for user that just want to listen to music etc

**Comment by freedomshare** [comment]
all it really dose is allows that app to keep play well minimized and using other apps etc

**Comment by DanielnetoDotCom** [comment]
@freedomshare above you said when you embed a SoundCloud link it plays in the BG, is that correct?

**Comment by freedomshare** [comment]
Yes  soundcloud embed plays in BG

**Comment by DanielnetoDotCom** [comment]
Good to know, I will try to find out how they do.

can you please share a link that you confirm can play on the background? so I can test it?

**Comment by freedomshare** [comment]
I just testing again on my web view app 
Here video link I'm listening to the song well I type this https://freedomshare.net/video/2421/filling-feat.-goldy-boy?channelName=FreeDomShare+Live

**Comment by freedomshare** [comment]
If you download my web view app on Google play u can test it there too it work fine with soundcloud

**Comment by freedomshare** [comment]
https://play.google.com/store/apps/details?id=com.freedomshare.music

**Comment by freedomshare** [comment]
As a side note soundcloud embed even works in bg on your android app too

**Comment by DanielnetoDotCom** [comment]
Something is strange.

Are you sure that is the link? https://freedomshare.net/video/2421/filling-feat.-goldy-boy

this link is an MP4 self-hosted file

![image](https://user-images.githubusercontent.com/18009293/86031192-e3f34900-ba0b-11ea-9cfa-820a71e56bbf.png)

**Comment by freedomshare** [comment]
That the right link it from soundcloud I use the encoder

**Comment by freedomshare** [comment]
I even played it from the app u made and bg play works only for that video

**Comment by freedomshare** [comment]
So only mp4 play in bg?

**Comment by DanielnetoDotCom** [comment]
Not sure I did not test it. but if it works with the link you provided it should work with any MP4 video
