### ISSUE TITLE
when i use the avideo encoder, site goes to Maintenance break

### ISSUE THREAD

**Issue by GRNHACKER** [WWBN/AVideo#3283]
when i encode any video, site goes to Maintenance break , how to fix it?

**Comment by DanielnetoDotCom** [comment]
Your server is probably not able to handle the encoder process and the MySQL connections. 

upgrade the hardware

**Comment by GRNHACKER** [comment]
> Your server is probably not able to handle the encoder process and the MySQL connections.
> 
> upgrade the hardware

oh that's the reason, thanks for your reply <3
