### ISSUE TITLE
 Is installing CentOS 7 possible ? Some way improved?

### ISSUE THREAD

**Issue by aclucena** [WWBN/AVideo#3286]
Dear, Good afternoon. All right? I am Brazilian and my English is complete "googles".
Let's go to the report:
I have a local test server with CWP running with CentOs 7 and pre-configured. And it runs on it in a BR domain master-sti.com.br (https://netflix.master-sti.com.br/)
Try to install youphptube  with the name netflix.master-sti.com.br to no avail, with the error "Internal Server Error 500". I found no solution. I thank you for your help.

Att,

Cesar

**Comment by akhilleusuggo** [comment]
This project does not support Centos/Windows/NGINX , but that doesn't mean can not work . You need to find a solution by your own .
Also is not recommended to use any panel , this will give many permissions errors .

https://github.com/WWBN/AVideo/issues/1779

**Comment by aclucena** [comment]
Sorry for the question: Do you know a similar one that works in Centos? I am grateful.

**Comment by akhilleusuggo** [comment]
Similar what exactly ?

**Comment by aclucena** [comment]
One that has the same features nearby. But that works in the CentOs 6 or 7.

**Comment by akhilleusuggo** [comment]
I don't know

**Comment by aclucena** [comment]
👍

**Comment by partystreamsk** [comment]
Im using it on CENTOS 7 and works well.. I dont know why this project is based on ubuntu and not centos. Centos is more stable and powerful.
