### ISSUE TITLE
MyVideos /tags to pull

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3287]
Can we add an option to enable/disable what data do we wanna pull on my video's section ?
I can see too many useless data that need to be processed ( pulled from DB ) , and the load time become a problem .

Example : 

- Source
- Encoder
- Format
- Paid Content
![image](https://user-images.githubusercontent.com/52116577/85730127-12b6aa00-b702-11ea-8175-6e6c138da1d3.png)

This functions should be visible only to admin ( in case are needed for debugging purposes )

In case this function will not be added , I would like to know where to disable this functionalities ( source code )

PS : I know that we could remove them from here ( screen bellow ) , but what if you don't wanna expose the data , or just optimize the data to pull .

![image](https://user-images.githubusercontent.com/52116577/85730474-590c0900-b702-11ea-980a-4b5ff7527c46.png)

**Comment by DanielnetoDotCom** [comment]
Hi

It may be an option, but needs to be carefully implemented, some of them we can hide, but we always have to get it.

Not sure if its implementation worth to do now.

**Comment by akhilleusuggo** [comment]
but for example the encoder thing , it's something that you have implemented yet recently .
So removing it is possible .

**Comment by DanielnetoDotCom** [comment]
Is the issue only display the info?

not display is possible, the problem is to remove it from the query

**Comment by akhilleusuggo** [comment]
I just don't understand why are we pooling data that we are not even using ( useless ) . 
Useful only for admin , for debugging .

And yes for now I'd like to hide it at the least
