### ISSUE TITLE
MySQL bug during installation

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3288]
I did an installation 5 times I re download the files again I always have this error

![image](https://user-images.githubusercontent.com/39193219/85732494-b6e92280-b6fb-11ea-8287-77dae1ce15b8.png)

 Apache/2.4.18 (Ubuntu) is Present
 PHP 7.2.31-1+ubuntu16.04.1+deb.sury.org+1 is Present

**Comment by akhilleusuggo** [comment]
I was about to say that php 7.2 is for 18.04 , but your error is from MySQL
That error means that you need to lower the varchar to 190 , deppending encoding char you're using , you will be limited . Explanation : 

UTF8 can have a maximum of 255 on VARCHAR
UTF8MB4 on innobd can have a maximum of 191 on VARCHAR

utf8 uses 3 bytes per char (3x255 = 765)
utf8mb4 uses 4 bytes per char (4x191 = 764)

**Comment by syldri** [comment]
hello @akhilleusuggo thank you very much for this information I will resolve this problem
