### ISSUE TITLE
livelink

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3289]
hello 
why did you put livelink the users don't need to know it's a link

why we don't have the number of users who watch live like the others

![image](https://user-images.githubusercontent.com/39193219/85803743-25ec6880-b748-11ea-8a90-0d9797294442.png)

**Comment by akhilleusuggo** [comment]
Because they're not connected to your server basically , that would require another type of plugin .

**Comment by DanielnetoDotCom** [comment]
Hi

I just add the doNotShowLiveLinksLabel option on the plugin parameters

**Comment by syldri** [comment]
hello 
this is good news more than the number of online users is missing

**Comment by DanielnetoDotCom** [comment]
we do not have online viewers for livelinks
