### ISSUE TITLE
Videotags does not show any content

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#3290]
Since one of the last updates 'Videotags' does not show any content.

The number of 'found videos' are showing but hitting that tag-button i got a blank page.
No errors found in log.

![Snap1](https://user-images.githubusercontent.com/39981177/85847904-8ad7ab00-b7a8-11ea-9d54-e6297a3d858a.jpg)

**Comment by akhilleusuggo** [comment]
I confirm the bug

**Comment by wetubeclub** [comment]
the same to me also!

**Comment by DanielnetoDotCom** [comment]
Strange, it works fine on my side. 

can you please reproduce it on the demo site?

**Comment by TLCReuver** [comment]
Reproduced on DemoSite and it have the same bug.

![Snap1](https://user-images.githubusercontent.com/39981177/85915332-cfb21f00-b846-11ea-8d96-bc6154f76ee8.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, I guess I find the problem

**Comment by wetubeclub** [comment]
yes you found the problem!
it works for me now
Thank you

**Comment by wetubeclub** [comment]
Hello again,
I think there is a small problem
I mean when we click on the label:  example
the tag has 2 videos displays the videos but also displays the number of pages that may confuse users when there is a large number of videos on the tag
Thank you

![tag](https://user-images.githubusercontent.com/60543030/85942814-04e46d00-b92c-11ea-9fc8-0bb8eb6bbdbc.jpg)
![tag1](https://user-images.githubusercontent.com/60543030/85942817-09108a80-b92c-11ea-9373-5c3037eca1cb.jpg)

**Comment by TLCReuver** [comment]
Works for me too

Indeed WeTubeClub
First page with tag 'Sport' referred to www.website.com/tag/186/Sport
Second page is referring to the standard
**www.website.com/page/2**
this had to be like
**www.website.com/tag/186/Sport/page/2**
or something like that

**Comment by DanielnetoDotCom** [comment]
What about now?

**Comment by wetubeclub** [comment]
Hello,
For me now it's totally okay as it should be!!!!

Thank you Daniel!

**Comment by TLCReuver** [comment]
Hi Daniel,
The update fixed the count of pages but when clicking on page 2 it load the startup page 2 and not page 2 with the selected tag.

Example tag 'Carnaval':

https://media.beesel-reuver.nl/tag/235/Carnaval shows 114 videos

![Carnaval 1](https://user-images.githubusercontent.com/39981177/86090701-d8a32a80-baaa-11ea-934c-b947264f4915.jpg)

114 videos are 4 pages with 30 videos on 1 page thats correct
![Carnaval 2](https://user-images.githubusercontent.com/39981177/86090806-11430400-baab-11ea-8fe2-ddb94bd8db33.jpg)

But clicking on page 2 it jumps to startup (root) page 2 in this case:
https://media.beesel-reuver.nl/page/2
this had to be:
https://media.beesel-reuver.nl/tag/235/Carnaval/page/2 or something like that
