### ISSUE TITLE
Personal Information Breach

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3294]
right clicking on the live broadcasts
click inspect
click sources

![breach](https://user-images.githubusercontent.com/65451390/85928757-18ee8700-b8b8-11ea-83bf-23d17feac82f.png)

what i have coloured off are email addresses of my users. What option are available for either hiding this, or using a different identifier?

**Comment by akhilleusuggo** [comment]
That means your users does not use a UserName !
Also if you're logged as admin , you will receive more information , **_try inspecting logged out_** 
They have indicated their username to be the email, basically what should be exposed there is the username , or channel name . On demo site example : 

![image](https://user-images.githubusercontent.com/52116577/85930014-a2568700-b8c1-11ea-946c-d5f4c1c1f3aa.png)

Make sure that have everything as you wanted on the plugin section ( advanced custom and advanced user )

**Comment by jengajenga** [comment]
Thank you. I've tried all the options in the CustomiseUser and CustomiseAdvanced and still nothing.
Below is the first 25 lines of the getimage.php file. Is there something I can change to make it pick from another table other than UserName? Thanks.

<?php
require_once '../../videos/configuration.php';
session_write_close();
$filename = $global['systemRootPath'] . 'plugin/Live/view/OnAir.jpg';

require_once $global['systemRootPath'] . 'objects/user.php';
require_once $global['systemRootPath'] . 'objects/subscribe.php';
require_once $global['systemRootPath'] . 'objects/functions.php';
require_once $global['systemRootPath'] . 'plugin/Live/Objects/LiveTransmition.php';

if(!empty($_GET['c'])){
    $user = User::getChannelOwner($_GET['c']);
    if(!empty($user)){
        $_GET['u'] = $user['user'];
    }
}

$livet =  LiveTransmition::getFromDbByUserName($_GET['u']);
if (empty($_GET['format'])) {
    $_GET['format'] = "png";
    header('Content-Type: image/x-png');
} else if ($_GET['format'] === 'jpg') {
    header('Content-Type: image/jpg');
} else if ($_GET['format'] === 'gif') {
    header('Content-Type: image/gif');

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/85955691-02fcc700-b989-11ea-962d-556cac6e2f99.png)

Your users definitely has not added a channel name on account settings

**Comment by jengajenga** [comment]
Ok man. Thank you. I'll have them add their names and see how it turns out.
