### ISSUE TITLE
Please help me configure ,Live streamin for user-cant see the option in plug in screen

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3295]
![image](https://user-images.githubusercontent.com/65802024/85933099-b9f93400-b8f0-11ea-8101-dd635d43f4cb.png)

**Comment by akhilleusuggo** [comment]
What is the issue ?

**Comment by vraghavans** [comment]
Hi!
Actually am the admin and want to allow encoders to live stream but am not able to activate it for the users.
hence wanted the guidance on how to activate the same

**Comment by akhilleusuggo** [comment]
I don't really understand what do you mean why ''let encoders live-stream''
What do you mean with encoders ? users ? the encoder server ? Provide some details if possible , even if the information is fake .
site : example.com   ;   encoder: encodeR.example.com         ( something like this , so we can understand you right )

**Comment by vraghavans** [comment]
Okies,sorry

Iam the website admin for seafarerstube.com and i have registered users who want to live stream their videos.I have enable the live plugin and have configured and it works for me,but i want the users who are registered on the website also to be able to live stream,which i am not able to configure,thats why i ahd posted the screen shot in the earlier post where i needed guidance if there is a option i can tick and the users who have registered on the site can also live stream.

Hope i have given some clarity of what iam looking.forgive my ignorance please.

**Comment by akhilleusuggo** [comment]
First : Create an account ( non-admin ) like a fake account .
Second : Try to stream , and report the issue .

**Comment by jengajenga** [comment]
try going to Users, then edit, then click User can stream.
Also is the plugins-CustomizeUser - look for newUsersCanStream and say yes

**Comment by vraghavans** [comment]
excellent!thanks was searching in the wrong place for the option.
