### ISSUE TITLE
We can show 10% of the video as preview for the user to buy the rest

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3298]
**Is your feature request related to a problem? Please describe.**
When a user has to buy a video from the platform,he is not sure of the quality of the video,he should not feel cheated after buying the video,which might be lost reputation for the encoder and the platform and the user will not buy another video from the platform

**Describe the solution you'd like**
We can show a 5 to 10% of the length of the video to the viewer before he buys the video,so that he knows the quality of content and the quality of the video file.
during PPV video selection we can give the encoder a option to choose what percentage of the video he wants to show to the user as preview

**Describe alternatives you've considered**
Alternately may be we can play only the audio in the video ,masking the video and ask the viewer to pay if he wants to see the video,again this is some ind of preview to assist the viewer in making the decision to buy

**Additional context**
This is the same technique used by News websites,to show just the starting of the article and later to subscribe to read the full article-it increases the chances of buying.

**Comment by DanielnetoDotCom** [comment]
Why dont you create trailers?

you can host your own trailers

![image](https://user-images.githubusercontent.com/18009293/85934682-d11e2e80-b8bc-11ea-8b66-27afbd77df4a.png)

**Comment by vraghavans** [comment]
can you guide me where i can get this screen please,cant seem to find it

**Comment by DanielnetoDotCom** [comment]
This is the video manager. edit a video and scroll down

**Comment by vraghavans** [comment]
Okies,thanks got it ,but however it say embed code for the trailer.is it a seprate video uploaded? can you please explain this?

**Comment by vraghavans** [comment]
Can some one open me on the code for the trailer please

**Comment by DanielnetoDotCom** [comment]
Yes, it will be a separate video. or a video from youtube (if you prefer)
