### ISSUE TITLE
white-label version app

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#3299]
On the white-label version app, you can live stream from any mobile (Android and iOS), correct? Also, a suggestion, I have a lot of people who want to leave YouTube and come to my video platform, but they want the same features that YouTube has. Are there any more updates and features that are coming for our platforms?

**Comment by DanielnetoDotCom** [comment]
Hi, for now, due a technical limitation, you can live only from the Android app

**Comment by HazteFama** [comment]
Hi guys! I tried since my iphone with Larix app using credentials from demo website. It's different when you broadcast since your white label version?

**Comment by DanielnetoDotCom** [comment]
@HazteFama sorry I do not understand your question.
