### ISSUE TITLE
Not able to add funds to wallet configured with stripe

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3300]
**Describe the question**
I have an encoder account and i have configured PPV plan with my stripe account details.
Now i want to promote my video and want to pay the admin with my wallet,iam trying to add funds to my wallet with my dummy card as per stripe website however it is not accepting-the configuration in PPV is also the dummy keys

**Screenshots**
when i add i get 2 options pay with pay pal and pay with card-i choose card and it gives me a sorry error after i add the credentials

**Comment by DanielnetoDotCom** [comment]
The PPV for users pays directly to the user and you cannot use the wallet money for it.
the wallet money goes to the site admin (so you need to have the stripe for the site properly configured)

you can disable the wallet on the top here.

![image](https://user-images.githubusercontent.com/18009293/86018647-04b3a280-b9fc-11ea-9610-d7753c7ffa28.png)

**Comment by vraghavans** [comment]
Dear Daniel,

Thanks for your reply,

there are 3 scenarios here

1) Encoder need to pay the admin for promoting his videos-He has to pay through wallet only-so he has to add money to vallet if he does not have the amount-thats where it thowing the error
2) viewer is paying to encoder for PPV-This understood the user will directly pay tothe encoders stripe account
3) Admin is paying to encoder for views-Admin will be paying the encoder for views through wallet,if  i hide the wallet-how will the encoder be able to use the money in the wallet,Also if reaches the threshold of withdrawing,he should be able to with draw to his bank

Please advise
4)

**Comment by DanielnetoDotCom** [comment]
> Encoder need to pay the admin for promoting his videos-He has to pay through wallet only-so he has to add money to vallet if he does not have the amount-thats where it thowing the error

If does not have the amount he can add the amount thru PayPal or Stripe

> viewer is paying to encoder for PPV-This understood the user will directly pay tothe encoders stripe account

Correct, using the "encoder" stripe account

> Admin is paying to encoder for views-Admin will be paying the encoder for views through wallet,if i hide the wallet-how will the encoder be able to use the money in the wallet,Also if reaches the threshold of withdrawing,he should be able to with draw to his bank

Correct, for withdraw feature you cannot hide the wallet. maybe It needs a new option to show the wallet only for admins and "encoders" (the ones with upload rights)

**Comment by vraghavans** [comment]
Dear Daniel,

Thanks for the reply,. 
Point 1-the encoder is unable to add funds for the promotion to the wallet, 
Please advise

**Comment by DanielnetoDotCom** [comment]
The problem is, you are trying to mix site money and encoder money.

The way it is developed now or the site owner or the "encoder" supposes to get paid.

Mix that can cause unpredicted problems.

**Comment by vraghavans** [comment]
Dear Daniel,

Any solution for this please

**Comment by DanielnetoDotCom** [comment]
I need to update many things to be able to resolve this, I need more time.
