### ISSUE TITLE
1 video having 2 different PPV plans

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3301]
**Describe the bug**
I was trying to assign 2 different PPV plans to the same video and it accepted which should not be possible

**To Reproduce**
![image](https://user-images.githubusercontent.com/65802024/85939581-5f81c700-b934-11ea-9203-b1dfdb89f6e8.png)

**Expected behavior**
if one video is selcted for a PPV plan it has to ecome inactive for other PPV plans

**Error Logs**
Provide the log files at the moment you found the issue.
If you are not sure how to find the log file, please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
There was no error where actually it should have shown the error

**Screenshots**

attached on top

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] Version 83.0.4103.116

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DanielnetoDotCom** [comment]
I think it should be possible. 

for example, you can create a PPV plan that expires in 24 hours and charge 1 USD and also create a plan that expires in 1 month and charge 5 USD 

so the user will choose what best fits to him

**Comment by vraghavans** [comment]
Okies that good tat this is handled, i was think it will throw a error on the viewer side when he tries to buy he video,now isee he can see both option and he can choose,this is genius!
