### ISSUE TITLE
The platform uses real time money in wallets in accounts and tied to payment gateways-hence 2-factor authentication may give users more confidence

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3302]
**Is your feature request related to a problem? Please describe.**

This is related to the security of the login of the systems where as there is money transaction,it is preferable to have a 2 factor authentication to the users to be more secure and encoders coming on board more confidently

**Describe the solution you'd like**
We can have a 2nd level authentication like an email password or a authorisation App or a phone password,so that just by using the password,no one can gain access to the account.
Also this would be an optional feature which the user can select however recommend all to have the same

**Describe alternatives you've considered**

not able to think of other ways of achiving this

**Additional context**

All platform having financial and data security requirements have 2 factor authentication and hence here as we have both,it makes it important to have 2 factor authentication

**Comment by DanielnetoDotCom** [comment]
I have plans to create a 2FA plugin in the future.

**Comment by vraghavans** [comment]
okies noted thanks! please do keep us updated so that we could use that feature
