### ISSUE TITLE
HLS streaming in LAN problem

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#3305]
**Describe the question**
A clear and concise description of what is your question.

Hi,

I setup the AVideo server in LAN.
And when I try use the demo URL https://nimble.dashstreams.net/onestudio/americanclassictv/playlist.m3u8?fluxustv.m3u8 add in Live Link.  It working normal.

But When I use Video streaming hardware that support HLS streaming to the AVideo server.
It can show thumbnail in the Live section and then I click it to playback. 
It can't playback.

So, I try open the URL like this http://192.168.1.113:1935/hls/live.m3u8 on my PC via VLC.
It can playback normal.

Is the AVideo support HLS streaming in the LAN?

Thanks & BR,
Pond

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

![1593415898844](https://user-images.githubusercontent.com/57282919/85985786-692f2b80-ba15-11ea-82e6-9be94be57ed8.jpg)

![1593415935855](https://user-images.githubusercontent.com/57282919/85985802-70563980-ba15-11ea-9969-c58533b8149c.jpg)

**Comment by akhilleusuggo** [comment]
It's working for me .
Just make sure you clear the cache , and add the **_right_** `Start date and End date `

**Comment by DanielnetoDotCom** [comment]
@guitarpound I can see your site is HTTPS and your link is HTTP, so this will raise a security block by the browser.

You have 2 options:

1. make the m3u8 URL an HTTPS URL with a valid certificate 
2. downgrade your site to HTTP instead of HTTPS

**Comment by guitarpound** [comment]
Hi Daniel,

My Local Server is HTTP and the Encoder also HTTP.
And I also clear cache and then check the right start date and end date already.
It still not working.

I tried inspect element on the google chrome and found error in below picture.

![inspec2](https://user-images.githubusercontent.com/57282919/86081778-59b8ec80-bac0-11ea-91a6-c51b89ca2923.jpg)

Thanks & BR,
Pond

**Comment by akhilleusuggo** [comment]
I'm sure you have put your hand on the code OR on apache2.conf 
https://stackoverflow.com/questions/20035101/why-doesn-t-postman-get-a-no-access-control-allow-origin-header-is-present-on

**Comment by guitarpound** [comment]
Hi akhilleusuggo, 

Thank you for your reply.

Now I can playback the video by install Chrome extensions -> Moesif Origin & CORS changer.
And I found Safari can playback the video without any plugin.

Only Firefox Browser can't playback the video.

I found Article recommend to edit code on Server side.

**In the Article said,** 

If use PHP code 
add this code
_<?php 
header('Access-Control-Allow-Origin: *');
?>_

If use Apache 
add this code in .htaccess
_<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
</IfModule>_

If use Nginx
edit nginx.conf
_server {
    ...
    location / {
        proxy_pass   http://127.0.0.1:8080;
        add_header   Access-Control-Allow-Origin *;
    }   
}_

But I'm not sure the "Server side" in the Article mean **Streaming Hardware box** or **AVideo Server**.
Because I tried edit code on AVideo Server already.  But It still can't playback on Firefox & Chrome without extension.

Thanks & BR,
Pond
