### ISSUE TITLE
Default player message when no video is available

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#3306]
Anyone knows how to change the message shown to users when the load a live channel that's offline?
"The media could not be loaded, either because the server or network failed or because the format is not supported."

I'd prefer it simply say OFFLINE or something.

**Comment by akhilleusuggo** [comment]
On videojs library . Not recommended , since it's the same message that appears when a video ( not livestream ) is not found or corrupted .

**Comment by DanielnetoDotCom** [comment]
Maybe you can try to create a translate file and add it on the header

https://docs.videojs.com/docs/guides/languages.html

**Comment by ganddser** [comment]
@akhilleusuggo 
@DanielnetoDotCom 

Thanks
