### ISSUE TITLE
Bug when clicking on a playlist video on site from a channel

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#3308]
When I click a video on a channel playlist with clicking play all I get this 
![Screenshot_20200629-151526_FreedomShare](https://user-images.githubusercontent.com/60738260/86041146-9e3e7c80-ba1b-11ea-8b2b-45fa6ffc738a.jpg)

If you go to freedomshare.net channel freedomshare live click play list tab then click a video and you get this

![Screenshot_20200612-141800_FreedomShare_1](https://user-images.githubusercontent.com/60738260/86041425-fecdb980-ba1b-11ea-8b89-5b3fa83d4c24.png)

**Comment by DanielnetoDotCom** [comment]
can you please share the playlist Link?

**Comment by freedomshare** [comment]
It is all playlist on site

**Comment by freedomshare** [comment]
https://freedomshare.net/channel/FreeDomShare+Live/

Click on any video do not click play all

**Comment by DanielnetoDotCom** [comment]
Bug found, Please update your code
