### ISSUE TITLE
a little suggestion came in my mind during lockdown....

### ISSUE THREAD

**Issue by GRNHACKER** [WWBN/AVideo#3309]
you should make a plugin for conferencing to use at the time of live stream if streamer allow that. Because in this lockdown many schools want to setup a online class using own server. so while online class if student have any doubt then he/she can conference at same time while streaming using some button and turn off the conference after his/her doubt cleared with same button. conference only accept when streamer will allow them and at a time only 1 student allowed for conference and for other student they should be under the queue list.

**Comment by akhilleusuggo** [comment]
there's something called user group . Take a look here 
https://github.com/WWBN/AVideo/wiki/Create-non-public-videos-and-deal-with-user-groups

**Comment by GRNHACKER** [comment]
> there's something called user group . Take a look here
> https://github.com/WWBN/AVideo/wiki/Create-non-public-videos-and-deal-with-user-groups

but where is the conferencing option, i did not saw there.

**Comment by akhilleusuggo** [comment]
You can create a usergrp .
This will allow you to select what usergrp are allowed to watch the live-stream.

**Comment by GRNHACKER** [comment]
> You can create a usergrp .
> This will allow you to select what usergrp are allowed to watch the live-stream.

i already know this things, but there should me a video calling option(using plugin) as i said for clearing doubt for students.

**Comment by akhilleusuggo** [comment]
You can email developer@youphptube.com for new plugins

**Comment by DanielnetoDotCom** [comment]
Hi

for a conference solution what we have now is the Zoom plugin https://github.com/WWBN/AVideo/wiki/ZoomMeetingRecorder-Plugin

Live stream HLS is not a good solution for the conference due to the latency, but it is very useful if you want to broadcast your meeting.

**Comment by GRNHACKER** [comment]
> Hi
> 
> for a conference solution what we have now is the Zoom plugin https://github.com/WWBN/AVideo/wiki/ZoomMeetingRecorder-Plugin
> 
> Live stream HLS is not a good solution for the conference due to the latency, but it is very useful if you want to broadcast your meeting.

what about jitsi?

**Comment by DanielnetoDotCom** [comment]
jitsi is awesome, but I took a quick look into it and I did not find any API to use webhooks as Zoom has

to do the same jitsi must be able to record meetings and notify a webhook with a download link when the meeting is done.

**Comment by GRNHACKER** [comment]
> jitsi is awesome, but I took a quick look into it and I did not find any API to use webhooks as Zoom has
> 
> to do the same jitsi must be able to record meetings and notify a webhook with a download link when the meeting is done.

what about this :- 
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe

**Comment by GRNHACKER** [comment]
> jitsi is awesome, but I took a quick look into it and I did not find any API to use webhooks as Zoom has
> 
> to do the same jitsi must be able to record meetings and notify a webhook with a download link when the meeting is done.

and jitsi support recording

**Comment by heiress01** [comment]
Jitsi, has an add on call jibri that allows for the recordings Jibri provides services for recording or streaming a Jitsi Meet conference.  It works by launching a Chrome instance rendered in a virtual framebuffer and capturing and encoding the output with ffmpeg. It is intended to be run on a separate machine (or a VM), with no other applications using the display or audio devices. Only one recording at a time is supported on a single jibri.  Heres; the github page: https://github.com/jitsi/jibri

**Comment by DanielnetoDotCom** [comment]
I was looking into it.

looks like recording on jitsi is a problem, especially when you connect thru a phone.

but we can record the meeting if we restream the meeting to our NGINX server.

I know we can restream the meeting to youtube. does anyone know how to restream to a custom RTMP server?

**Comment by DanielnetoDotCom** [comment]
@GRNHACKER I just add a Meet plugin, what is an integration with Jitsi
