### ISSUE TITLE
Plugin Customize for  footer  

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3310]
hello @DanielnetoDotCom 
when a person buys this plugin why not add a button if we want nothing that appears in the footer and the description tag

![image](https://user-images.githubusercontent.com/39193219/86141153-019ade00-baf2-11ea-81aa-fcfad5ce4ff1.png)

I bought the plugin  I don't like to see this line

**Comment by akhilleusuggo** [comment]
edit it . type a space ( blank with space ). Should disappear .

**Comment by syldri** [comment]
hello @akhilleusuggo  I'm not talking about what's written

i'm talking about deleting all lines   footer

![image](https://user-images.githubusercontent.com/39193219/86144635-3741c600-baf6-11ea-923c-e03f2e5aa1b1.png)

**Comment by akhilleusuggo** [comment]
Have you tried what I've told you ??
Because it's working for me .

**Comment by syldri** [comment]
I only have the text that disappears 
the rest does not disappear

![image](https://user-images.githubusercontent.com/39193219/86149686-9c98b580-bafc-11ea-8f38-2b9ef6157d14.png)

**Comment by akhilleusuggo** [comment]
I see what you mean .
@DanielnetoDotCom May do something 

On meantime , you can go to customize colors , and make the ''white blank space'' be the blue/grey color that you have by default on your site .

**Comment by DanielnetoDotCom** [comment]
Hi, this looks like for me a CSS proble. you can add a custom CSS for the footer.

Check here https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css
