### ISSUE TITLE
Logo Error

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3312]
Why is my logo looking like this? I have changed it to different versions but this is all i get.

1. I have cleared browser cache
2. I have cleared both first page cache and cache directory

Version 9.1. It was fine until i tried to change it now it won't change.

![logo_error](https://user-images.githubusercontent.com/65451390/86163618-33736b00-bb19-11ea-9941-19922f4d8154.png)

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong
