### ISSUE TITLE
A question the display

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3313]
I have  questions

 or I put the red arrows I would like to know which part of the administration which manages it is this part
I want to be able to choose what should be visible or not on the main page

![image](https://user-images.githubusercontent.com/39193219/86173788-cfed3b80-bb20-11ea-950f-51372e1674b8.png)

**Comment by akhilleusuggo** [comment]
On Gallery ( categories )

**Comment by syldri** [comment]
hello @akhilleusuggo  thank you very much i had never watch this plugin

**Comment by akhilleusuggo** [comment]
Is the most compatible right now .

**Comment by syldri** [comment]
@akhilleusuggo   I have a question when I update the page all videos go into play mode at the same time 

normally it is that you pass the smile on a video it passes in reading mode gif 
 

![image](https://user-images.githubusercontent.com/39193219/86181899-26617680-bb2f-11ea-8c57-cc64ebe44839.png)

**Comment by akhilleusuggo** [comment]
Do you mean Gifs are not working ?

**Comment by syldri** [comment]
works very well it activates all at the same time

**Comment by akhilleusuggo** [comment]
I believe you're talking about infinite-scroll.pkgd.min.js
@DanielnetoDotCom You may wanna take a look here
