### ISSUE TITLE
Create 60 second or 30 second clips

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3314]
hello @DanielnetoDotCom  it would be nice to be able to create  60 second or 30 second clips 

add the option that the clip will be deleted automatically in 15 days

![image](https://user-images.githubusercontent.com/39193219/86175526-c913f800-bb23-11ea-88ed-6fc0d2fb699e.png)

**Comment by DanielnetoDotCom** [comment]
Why not use trailers?

**Comment by syldri** [comment]
The clips allow viewers to quickly share the most exceptional moments of the broadcasts they are watching while allowing broadcasters to grow their channels through social networks!


- When you see a highlight during a broadcast, click the Clip button. By default, this captures about 25 seconds of the broadcast before you click the button, and five seconds after.


- A new tab will open, and the video will be ready to play in just a few seconds. You can pause the clip and resume playback, or - - play it repeatedly.
 
- If you want, you can give your clip a unique name. Otherwise, the clip name will be created automatically from the title of the - 
 broadcast. Do not forget to click on "Save" for your changes to be taken into account.
 
- Did you fail to capture the perfect moment? No problem. With the clip editing function, you can click on the “Edit clip” button to shorten the clip, to a minimum of ten seconds, or do it for a maximum of sixty seconds. Plus, while you're editing, you get the last 90 seconds of broadcast or video, allowing you to better see when to clip.
 
- If you have finished editing the clip, click the "Publish" button to save your changes, and you will be redirected to the playback page.
 
- Click on the share buttons to copy the link or share the clip directly on various social networks. Once the video is shared, your friends can watch the recorded broadcast from the moment the clip ends, or go directly to the broadcast and join you in the chat.
 
- To delete a clip you have created, click the gear on any clip view page, then click Delete Clip.

- On the clips page, you will see your identifier displayed at the top, and there will be under the video the name of the broadcaster, the game he was playing, and the title of his broadcast.

- Clips are also integrated into chat, channel feed, and Pulse, so that when you share a clip, the URL is displayed as a thumbnail with additional information about the clip. You can also create clips using a shortcut keyboard (Alt + X on PC, or Option + X on Mac).

**Comment by heiress01** [comment]
I like that suggestion.
