### ISSUE TITLE
NOT ABLE TO PAY FOR THE PPV 

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3315]
**Describe the question**
i have created 2 user accounts one is for the encoder and other for viewer.Have created different stripe account for both these accounts and have created a PPV in one of the account.
iam try to pay for the video from the other account and it is giving me a sorry error
Cant see any errors in the error log

i have kept the price as 2 usd for 24 hours

Please help me solve this mystery

**Screenshots**
the error is just a sorry with the red cross

**Comment by vraghavans** [comment]
can anyone help me on this please

**Comment by DanielnetoDotCom** [comment]
Check your JS console to see if you can see any error.

but also should be something on the PHP log file

**Comment by vraghavans** [comment]
Dear Daniel,

Thanks for the reply,however i have been beaking my head to find out hwere are these files,can you please elaboarate a little more,so that i can find out the error please.
Rgds

**Comment by DanielnetoDotCom** [comment]
Please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by vraghavans** [comment]
my PHP log
[06-Jul-2020 14:13:15 UTC] PHP Warning:  It looks like the mbstring extension is not enabled. UTF-8 strings will not properly be encoded. Ask your system administrator to enable the mbstring extension, or write to support@stripe.com if you have any questions. in /var/www/html/YouPHPTube/plugin/StripeYPT/lib/Util/Util.php on line 183
[06-Jul-2020 14:13:16 UTC] AVideoLog::DEBUG: StripeYPT::setUpPayment 200 , USD, A Tube for Seafarers! Payment (https://seafarerstube.com/v/49)
[06-Jul-2020 14:13:16 UTC] AVideoLog::DEBUG: StripeYPT::setUpPayment error 
[06-Jul-2020 14:13:16 UTC] AVideoLog::DEBUG: #0 /var/www/html/YouPHPTube/plugin/StripeYPT/lib/ApiRequestor.php(173): Stripe\ApiRequestor::_specificAPIError('{\n  "error": {\n...', 400, Object(Stripe\Util\CaseInsensitiveArray), Array, Array)
#1 /var/www/html/YouPHPTube/plugin/StripeYPT/lib/ApiRequestor.php(473): Stripe\ApiRequestor->handleErrorResponse('{\n  "error": {\n...', 400, Object(Stripe\Util\CaseInsensitiveArray), Array)
#2 /var/www/html/YouPHPTube/plugin/StripeYPT/lib/ApiRequestor.php(126): Stripe\ApiRequestor->_interpretResponse('{\n  "error": {\n...', 400, Object(Stripe\Util\CaseInsensitiveArray))
#3 /var/www/html/YouPHPTube/plugin/StripeYPT/lib/ApiOperations/Request.php(57): Stripe\ApiRequestor->request('post', '/v1/charges', Array, Array)
#4 /var/www/html/YouPHPTube/plugin/StripeYPT/lib/ApiOperations/Create.php(23): Stripe\ApiResource::_staticRequest('post', '/v1/charges', Array, NULL)
#5 /var/www/html/YouPHPTube/plugin/StripeYPT/StripeYPT.php(103): Stripe\Charge::create(Array)
#6 /var/www/html/YouPHPTube/plugin/PayPerView/Stripe/requestPayment.json.php(14) : eval()'d code(1) : eval()'d code(38): StripeYPT->setUpPayment('200', 'USD', 'A Tube for Seaf...')
#7 /var/www/html/YouPHPTube/plugin/PayPerView/Stripe/requestPayment.json.php(14) : eval()'d code(1): eval()
#8 /var/www/html/YouPHPTube/plugin/PayPerView/Stripe/requestPayment.json.php(14): eval()
#9 {main}
[06-Jul-2020 14:13:16 UTC] AVideoLog::DEBUG: RequestPayment.json (2), (USD), (A Tube for Seafarers! Payment (https://seafarerstube.com/v/49))
[06-Jul-2020 14:13:16 UTC] AVideoLog::DEBUG: RequestPayment.json payment is empty

My Java console 
DevTools failed to load SourceMap: Could not load content for https://seafarerstube.com/videos/cache/js/bootstrap-select.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by DanielnetoDotCom** [comment]
Do not worry about SourceMap

but the _specificAPIError you should concern.

what did you try to do to get this error?

did you change any parameter?

Are you allowed to receive payments in USD? or you have to use your local currency?

**Comment by vraghavans** [comment]
1) what did you try to get this error? Ans-i as a viewer tried to buy a PPV using the stripe dummy card for US-as my server sits in US.when i enter the credit card details and hit enter-this error comes
2) did you change any parameters-I did the standard thing in the plugin parameters and nothing specific.any specific area i should be checking?
3) Are you allowed to receive payments in USD? or you have to use your local currency?-Yes,i can use USD ,i went through the Stripe documentation for Stripe and it says i can accept payment in 135 currencies.

Please advise

**Comment by DanielnetoDotCom** [comment]
Hi, I just sent an update to the streamer to try to get some clue what is happening,.

can you please update your streamer and try to do it again and check the error log?

**Comment by vraghavans** [comment]
Hi ,did the git pull and got updated,shd i do something else?
still the same cross error and below is the code
[12-Jul-2020 07:18:25 UTC] AVideoLog::DEBUG: Page generated in 0.0991 seconds. User: Not Logged - No Cache (/v/1?vmap_id=0b2a7db57daedeb01d076b94cded0234) F$
[12-Jul-2020 07:18:25 UTC] AVideoLog::DEBUG: Page generated in 0.1059 seconds. User: Not Logged - No Cache (/v/1?vmap_id=0b2a7db57daedeb01d076b94cded0234) F$
[12-Jul-2020 07:18:25 UTC] AVideoLog::DEBUG: Page generated in 0.1068 seconds. User: Not Logged - No Cache (/v/1?vmap_id=0b2a7db57daedeb01d076b94cded0234) F$
[12-Jul-2020 07:21:41 UTC] PHP Warning:  It looks like the mbstring extension is not enabled. UTF-8 strings will not properly be encoded. Ask your system ad$
[12-Jul-2020 07:21:41 UTC] AVideoLog::DEBUG: StripeYPT::setUpPayment 200 , USD, A Tube for Seafarers! Payment (https://seafarerstube.com/v/49)
[12-Jul-2020 07:21:41 UTC] AVideoLog::DEBUG: StripeYPT::setUpPayment error As per Indian regulations, export transactions require a customer name and addres$
[12-Jul-2020 07:21:41 UTC] AVideoLog::DEBUG: #0 /var/www/html/YouPHPTube/plugin/StripeYPT/lib/ApiRequestor.php(173): Stripe\ApiRequestor::_specificAPIError($
#1 /var/www/html/YouPHPTube/plugin/StripeYPT/lib/ApiRequestor.php(473): Stripe\ApiRequestor->handleErrorResponse('{\n  "error": {\n...', 400, Object(Stripe\$
#2 /var/www/html/YouPHPTube/plugin/StripeYPT/lib/ApiRequestor.php(126): Stripe\ApiRequestor->_interpretResponse('{\n  "error": {\n...', 400, Object(Stripe\U$
#3 /var/www/html/YouPHPTube/plugin/StripeYPT/lib/ApiOperations/Request.php(57): Stripe\ApiRequestor->request('post', '/v1/charges', Array, Array)
#4 /var/www/html/YouPHPTube/plugin/StripeYPT/lib/ApiOperations/Create.php(23): Stripe\ApiResource::_staticRequest('post', '/v1/charges', Array, NULL)
#5 /var/www/html/YouPHPTube/plugin/StripeYPT/StripeYPT.php(103): Stripe\Charge::create(Array)
#6 /var/www/html/YouPHPTube/plugin/PayPerView/Stripe/requestPayment.json.php(14) : eval()'d code(1) : eval()'d code(38): StripeYPT->setUpPayment('200', 'USD$
#7 /var/www/html/YouPHPTube/plugin/PayPerView/Stripe/requestPayment.json.php(14) : eval()'d code(1): eval()
#8 /var/www/html/YouPHPTube/plugin/PayPerView/Stripe/requestPayment.json.php(14): eval()
#9 {main}
[12-Jul-2020 07:21:41 UTC] AVideoLog::DEBUG: RequestPayment.json (2), (USD), (A Tube for Seafarers! Payment (https://seafarerstube.com/v/49))
[12-Jul-2020 07:21:41 UTC] AVideoLog::DEBUG: RequestPayment.json payment is empty

**Comment by DanielnetoDotCom** [comment]
There is an error in your log
You did not paste the full line but we can see this ....


`As per Indian regulations, export transactions require a customer name and addres`

Probably you are missing informations in your account

**Comment by vraghavans** [comment]
Dear Daniel note, the fulle statement was this
 As per Indian regulations, export transactions require a customer name and addres$address.. More info here: https://stripe.com/docs/india-exports
The regulation says ,individual cannot export products,but my server is sitting in USof A and i was using a US card ie 4242424242424242 ,then where is hte question of me exporting product?
Will it help if i disable the location plugin? is it right?

Please advise

**Comment by DanielnetoDotCom** [comment]
I do not think it will help. 

maybe you need to update your account and add the address or something.
actually you need to see on stripe what you need to do to approve it.

**Comment by vraghavans** [comment]
Hi Daniel!
Have been chatting with Stripe people all these days and there were some requirements related to tax which i have now ful filled.below are the summary points after that 
1) for Users in India-they can pay me only in INR,from a local address and local card
2) for Users out side india-they cannot pay me in inr ,and they need to give me a name and address field for payment. and the address to be outside india and an non indian card.
so the payment page need to have 2 things
1) take a name and an address field also for the payments to pass for any Indian stripe account.
2) currency switcher based on location of the user-cause my invoicing is in USD for the major users outside India
Can you help with this requirement please.

**Comment by DanielnetoDotCom** [comment]
I cannot see any easy solution to that. 
what I can see now is for you to use INR instead of USD. there is not an auto exchange of different currencies prices on the wallet or PPV.

**Comment by vraghavans** [comment]
Dear Daniel,

My website is more for ppl outside India ie 90 %

Hence I would be losing a big chunk of my customers.. 

Is there any other way please 
Rgds 
Vijay

**Comment by vraghavans** [comment]
Hi,Daniel,
Is it possible,we can atleast add name and address filed in the payment page please

**Comment by DanielnetoDotCom** [comment]
Do you mean to submit the address to Stripe?

**Comment by vraghavans** [comment]
Dear Daniel,
Yes,if we can take name and address and pass to stripe when payment.that would solve the issue
i.e. i can have USD as currency then
Rgds
Vijay
