### ISSUE TITLE
want to reset wallet for a specific user-added test funds

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3317]
**Describe the question**
Could you please guide me on resetting the wallet for a specific useras i had created dummy funds from stripe and want to use it live.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by vraghavans** [comment]
can anyone help me on this please

**Comment by DanielnetoDotCom** [comment]
Try to truncate some tables wallet and wallet_log

**Comment by vraghavans** [comment]
Cant get to do it ,could you please elaborate a little more please!

**Comment by DanielnetoDotCom** [comment]
Login into MySQL and run

```
TRUNCATE wallet;

TRUNCATE wallet_log;
```

**Comment by vraghavans** [comment]
Thanks Daniel!
I have the following databases
mysql> SHOW DATABASES;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| aVideo-Encoder     |
| mysql              |
| performance_schema |
| stube              |
| sys                |
+--------------------+
i changed the database to stube which is my database name and run the command
===================
mysql> TRUNCATE wallet_log;
Query OK, 0 rows affected (0.01 sec)

mysql> TRUNCATE wallet;
ERROR 1701 (42000): Cannot truncate a table referenced in a foreign key constraint (`stube`.`wallet_log`, CONSTRAINT `fk_wallet_log_wallet1` FOREIGN KEY (`wallet_id`) REFERENCES `stube`.`wallet` (`id`))
mysql>
====================
wallet_log worked but wallet gave me this error
Please advise

**Comment by DanielnetoDotCom** [comment]
Please make sure you first delete the wallet_log, then the wallet

```
TRUNCATE wallet_log;

TRUNCATE wallet;
```

**Comment by vraghavans** [comment]
Dear Daniel,

Thanks for the prompt reply,

Yes ,i did exactly as you had instructed

Thanks
rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
If it does not work, try to delete instead truncate

```
DELETE FROM wallet_log where id >0;

DELETE FROM wallet where id >0;
```

**Comment by vraghavans** [comment]
This worked!

Thanks!
rgds
Vijay
