### ISSUE TITLE
Which is the best way to add a new URL in the site?

### ISSUE THREAD

**Issue by leonidaswilliams** [WWBN/AVideo#3318]
Hi!

I want to add a new URL to my site (mysite.com/mysamplevideos) to show a page with a special logic to show the videos sort to the user.

Which is the best way to do it? To add a new folder (mysamplevideos) in the root with all my needed code or is it better to create a plugin?

In my code, I want to use as much logic as possible of the platform

Do you have some sample of this?

Thanks in advance

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by akhilleusuggo** [comment]
I don't really understand you question , but categories is the way to go .
