### ISSUE TITLE
Encoder hanging the command for cleanering Encoder queue

### ISSUE THREAD

**Issue by Wavekiller** [WWBN/AVideo#3319]
How would i go about resetting Encoder queue as the Encoder is hanging the hole time even after restarting the server.

I have not been able to fined the command for clearing the Encoder queue

![image](https://user-images.githubusercontent.com/67739398/86350471-06cb6a80-bc63-11ea-89cd-28badba71056.png)

if anyone can help thanks

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by Wavekiller** [comment]
what happen is i restarted the server well it was encoding the file i upload from there on  the pic it just stays at the same place and dose not move or goes to the next video

**Comment by akhilleusuggo** [comment]
Go to Queue Log , and press re-encode icon
