### ISSUE TITLE
HLS quality selector

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3320]
For some reason , the HLS quality selector does not always load : 
![image](https://user-images.githubusercontent.com/52116577/86407314-7e2de800-bcbd-11ea-8b14-a8be38cd2815.png)

![image](https://user-images.githubusercontent.com/52116577/86407408-a6b5e200-bcbd-11ea-8770-02ac7d8c45a8.png)

Cleared the cache multiple times , also changed browser . No results . ( nothing on the log files )

**Comment by Donnerstein** [comment]
@DanielnetoDotCom 

I have this problem too.
