### ISSUE TITLE
I cannot upload an 870MB file

### ISSUE THREAD

**Issue by Kaljamam** [WWBN/AVideo#3321]
Hello, we have increased the max_upload and max_post_size in the php.ini of our Apache QNAP NAS server to 1500M. YouPhpTube recognizes this too, but unfortunately I cannot upload an 870MB file. What could still be the matter?

![Bild 23](https://user-images.githubusercontent.com/28004920/86452981-5ec6a780-bd1d-11ea-841d-900288278be7.png)

**Comment by akhilleusuggo** [comment]
`post_max_size` you need to increase . then you need to restart apache .
Then should work .

**Comment by Kaljamam** [comment]
Sorry my first thread was not spelled correctly. But these values ​​were already set to 1500 MB. It has to be something else.

![Bild 28](https://user-images.githubusercontent.com/28004920/86563045-f9b0c300-bf63-11ea-9d77-c0706c482029.jpg)

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by DanielnetoDotCom** [comment]
FYI direct upload is not in chunks yet. So if you are using a CDN or proxy you are limited to a 100 mb file or less
