### ISSUE TITLE
saving the Ad code for Ad Overlay is asking to enter the password 2nd time

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3322]
**Describe the bug**
When an encoder wants to Add a Ad code for the Ad over lay is his account,he needs to add the code and click the Save Ad code button.

There is one more save button "save" which when clicked shows an error " password do not match" what it actually wants is for the user to enter the password 2nd time in the "basic info page" which is incorrect.

**To Reproduce**
1. Go to 'profile image on the right and go to My account'
2. Click on 'Ad overlay .'
3. Scroll down to 'the second save button at the bottom....'
4. See error-Password do not match

**Expected behavior**
there are 2 options
1) remove the second save button so that the user does not see
2) if we need the second save button then unlink this button to check data on the basic info page

**Error Logs**
Provide the log files at the moment you found the issue.
If you are not sure how to find the log file, please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
not required

**Screenshots**
not required

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by akhilleusuggo** [comment]
This is because the user has saved the password on the browser . So it does display as if he wanted to change it .
Is not the password that he needs to confirm actually . You must leave the password field blank ( empty ) 

This is how it looks when you have saved the password on your browser 
![image](https://user-images.githubusercontent.com/52116577/86465204-e0c4c980-bd39-11ea-898f-7b79ac88d522.png)

If you leave it blank should work .

**Comment by vraghavans** [comment]
Dear Daniel,
Yes i did leave it balank and i cannot click the second save button.
it shows the following error 

![image](https://user-images.githubusercontent.com/65802024/86522457-abc09000-be7b-11ea-8216-6218eea9bf86.png)

**Comment by GodgivenButhelezi** [comment]
This is Because you are on user information of profile. This has nothing to do with the ad overlay plugin, but you are somewhere else. Simply type your password twice and then save.

**Comment by vraghavans** [comment]
Hi,thanks for your comment,

However please do try once and advise as the screen automaticaly comes to this screen from the Ad code screen

**Comment by GodgivenButhelezi** [comment]
In your Plugins you enable ads overlay plugin.
![ad 1](https://user-images.githubusercontent.com/59503924/87246350-c4fda980-c444-11ea-87f3-27a1535ec9f2.png)
and then edit your ad overlay settings pasting your Code, but I created a code that you can use as an example to test.Copy and past it in your plugin code space.
<a target="_&quot;blank&quot;" class="ps-advads__image" href="https://www.radioairplay.ggpproductions.co.za">
            <img src="https://www.meetmycraft.com/wp-content/uploads/2020/07/GGP-Radio-Airplay-Ad.jpg" alt="image" height="60" width="540">
        </a>
![ad2](https://user-images.githubusercontent.com/59503924/87246409-34739900-c445-11ea-8835-739bef28f858.png)
if this code works then you are good to go. you can let me know if you need to create ads like adsense for yourself in your website .

**Comment by vraghavans** [comment]
yes ,can you help me with the Ad creation please?

**Comment by GodgivenButhelezi** [comment]
Hallo Vraghavans Here is a Solutions that may help you with ad creation https://meetmycraft.com/ads/create/
