### ISSUE TITLE
can not login Encoder

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#3323]
I changed Server IP.
I see next movie.
https://tutorials.avideo.com/video/18/fix-youphptube-url-after-move-server-location-and-ip?channelName=yeshua
I edit configuration.php under /var/www/html/AVideo/videos and /var/www/html/AVideo-Encoder/videoes
I change encoder address steamer's Web GUI.
But I can not login AVideo-Encoder.
Do we have to change other files ?
![av](https://user-images.githubusercontent.com/46562199/86467757-f3a6c080-bd70-11ea-8af8-08a267afde83.png)

**Comment by akhilleusuggo** [comment]
You need to add the new URL to allowed streams site .
If you are not able to log for now , you should add it manually on the database .

From my home server should look like this 
![image](https://user-images.githubusercontent.com/52116577/86468739-bb878980-bd40-11ea-94a8-d5b1dad2d61a.png)

**Comment by hnagasawa** [comment]
The configuration menu does not appear when I log in with admin at http://localhost/AVideo-Encoder.
I think I need to change the database manually.
Please tell me the name of the tool for your image.

**Comment by akhilleusuggo** [comment]
Is not recommended ( it's phpmyadmin ) 
I'm running it from home . In case you have no idea how to manage database ( with command line ) , phpmyadmin can do the trick . Try to restrict IP address for your home IP only , or remove it after you're done .

**Comment by hnagasawa** [comment]
Thank you for your support
