### ISSUE TITLE
plugin WWBN

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3324]
hello 
I would like to know what is this plugin  this?  WWBN

![image](https://user-images.githubusercontent.com/39193219/86483671-d3690880-bd54-11ea-8b6d-4364decacfe5.png)

**Comment by julzxcapz** [comment]
Hi @syldri !

This is for indexing your AVideo Platform to WWBN site, but we're currently working on that and still on beta testing. We will let you know in commit message or on this thread when its ready. Thank you

**Comment by syldri** [comment]
Hello @julzxcapz 

did you stop updating the site if we are not registered on your new site?

**Comment by julzxcapz** [comment]
Sorry are you still referring to WWBN plugin ? If yes; the answer is no, registering is not required if you don't like to index your AVideo Platform/Site to WWBN site.

**Comment by syldri** [comment]
there is a problem i cannot update the site

I have to be registered on WWBN

**Comment by akhilleusuggo** [comment]
how do you usually update the site ?
git pull ?

What is the output ?
