### ISSUE TITLE
getRemoteFile (getRecordedFile.php)

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3325]
I can't see it anywhere . Where should this option be added ?

Also the /plugin/Live/view/editor.php is not working  ; HTTP ERROR 500

https://github.com/WWBN/AVideo/wiki/Live-Plugin#record-a-video-on-a-remote-server

**Comment by DanielnetoDotCom** [comment]
Hi, I sent a fix, it is inside the Live plugin

**Comment by akhilleusuggo** [comment]
$record_path = "/var/www/tmp/"; //update this URL ??

What url should be there ?  My understanding is that , the encoder will be able to download the stream from external live-stream server . ( on a different server ) 

> Hi, I sent a fix, it is inside the Live plugin

```
git pull
Already up to date.
```

example.com is currently unable to handle this request.
**HTTP ERROR 500**

plugin/Live/view/editor.php

**Comment by DanielnetoDotCom** [comment]
Anything on log files?

**Comment by akhilleusuggo** [comment]
PHP Fatal error:  Uncaught Error: Class 'PayPerview' not found in /var/www/html/YouPHPTube/plugin/Live/view/editor.php:4
Stack trace:
#0 {main}
  thrown in /var/www/html/YouPHPTube/plugin/Live/view/editor.php on line 4

**Comment by DanielnetoDotCom** [comment]
Sorry my bad

**Comment by akhilleusuggo** [comment]
thanks
