### ISSUE TITLE
Sorry, this video is private

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#3328]
When user embeds their video on their own pages using the iframe embed, 
i.e https://mydomain.com/videoEmbed/735/video-automatically-booked-11

the following message appears:
Ops!
Sorry, this video is private

on the avideo platform the video is in a group so only the user can see and manage it.

They do however want to be able to embed the video on their own pages
(the video itself is not set to private) 

Is this normal behavior?

Or can we bypass the check for videos that are embedded in the iframe?

**Comment by akhilleusuggo** [comment]
I don't think that's possible the configuration that we have right now .
I mean , makes non sense what your users are asking for . If they want to hide the videos and be able to embed them , they can just put the videos on Unlisted then embed them .

If it's more private probably the password is not a bad choice ( you can add a password ). Recommended unlisted + embed .

Also why would you hide something that you're going to embed . Anyway .

**Comment by millzee01** [comment]
Anything is possible. 
My platform inst just a video hosting platform,  My members create documents that they need to embed their videos into (hence why we have to use user groups).    

Password protecting videos that will be displayed in documents is a bad idea.

So like you see, its important that their video content is group based so no nub can do any damage.

**Comment by millzee01** [comment]
Ok, i've sorted this.
I just had to mod getModeYouTube() inside plugins/customizeUser.php

if( $RequestUrl[1] == "videoEmbed" ){ 
     $cansee = true;
 }  

So basically, when videoEmbed is used, the video plays fine.
I suspect you can also set canWatchVideoWithAds to true if you use the ad engine in the config (which I dont)

**Comment by DanielnetoDotCom** [comment]
Modify the main source is not recommended.

are you sure you did not block the embed access on the SecureVideosDirectory plugin?

![image](https://user-images.githubusercontent.com/18009293/86515560-1f1cc000-bdf0-11ea-885c-87449e8c40de.png)
