### ISSUE TITLE
From embed to main video website

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3330]
You can click the title of an embedded youtube to jump to the youtube web page.
I don't see that available from the embed code I copy from the mvideo page.
Is this possible?

**Comment by DanielnetoDotCom** [comment]
can you please screenshot what place do you mean to click?

**Comment by fakeologist** [comment]
Sure.
The top link takes you to YouTube (app on phone). 
The play button plays embedded. 
![Screenshot_20200707-090507_Chrome](https://user-images.githubusercontent.com/66537018/86786295-d3f1ef80-c031-11ea-9bfc-bb16420fa684.jpg)

**Comment by DanielnetoDotCom** [comment]
What about this?

**Comment by fakeologist** [comment]
See first message. The AVN scripts don't do this. Can you make it happen?

**Comment by DanielnetoDotCom** [comment]
I saw the image, but I sent updates so you have a title (like youtube) on the embed videos

**Comment by fakeologist** [comment]
I copy the script from myvideos area click and copy icon. Where did you put the script update?

**Comment by DanielnetoDotCom** [comment]
Follow this to update your site

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by fakeologist** [comment]
Ok it's almost like youtube - the only way to get the title to display is to press the play button. Youtube embeds show the title when you hover. It's a minor point but overall great work.

**Comment by fakeologist** [comment]
Any update?

**Comment by DanielnetoDotCom** [comment]
Yes, didnt you see?

Check this embed video https://demo.avideo.com/videoEmbed/242/avideo1080hd

![image](https://user-images.githubusercontent.com/18009293/87583756-d4822a00-c6b2-11ea-9ac1-105e19f17f92.png)

**Comment by fakeologist** [comment]
Yup I saw it - it only shows up once you've clicked start. It's a minor issue, on youtube the embed shows the title on click the embed or even hover.

**Comment by fakeologist** [comment]
Please check this video to see what I am talking about. I want it to behave like Youtube if possible.
http://somup.com/cYjbIu6CM4

**Comment by fakeologist** [comment]
https://vm.tiktok.com/ZS567RGc/

Maybe this video will clarify.

**Comment by fakeologist** [comment]
Any update

**Comment by DanielnetoDotCom** [comment]
Yes, it is done.

I guess Android was released with a copy link icon on the video. but it will need to be remade. the Meet fail. I am still work on it.

**Comment by fakeologist** [comment]
This is a desktop issue. The link on the embed needs to go to video website.

**Comment by DanielnetoDotCom** [comment]
Sorry, I just checked, and looks fine for me,. and look like it was released 9 days ago

![image](https://user-images.githubusercontent.com/18009293/93634338-d32cf080-f9c6-11ea-9249-c7077de621a4.png)

**Comment by fakeologist** [comment]
I just checked too. If I click on the url link at the top of the desktop embedded video, it doesn't go to the video on the main website. It goes to my main blog site, and I can't find where I put that link in the config.

**Comment by DanielnetoDotCom** [comment]
Can you please share your blog site here so I can check?

**Comment by fakeologist** [comment]
Hi-
the title link has disappeared again, so you can't click the title of the video in the embed to bring you to the main video page.

**Comment by DanielnetoDotCom** [comment]
@fakeologist can you please share the link where are you using the embed? 
I want to check a few things

**Comment by fakeologist** [comment]
https://fakeologist.com/fak750-anounceofsaltperday/

**Comment by DanielnetoDotCom** [comment]
please try now
