### ISSUE TITLE
API RTMP servers

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3335]
Hello @DanielnetoDotCom I want to congratulate you for this nice update we can have several RTMP servers

@DanielnetoDotCom   why not create an API with a single RTMP address the 10 server forms a server with L'API

users will be randomly directed to one of 10 servers

**Comment by akhilleusuggo** [comment]
The idea would be better to stream to 1 server . But viewers will be able to watch it from different server with Multi-worker live streaming and Push

https://github.com/arut/nginx-rtmp-module/wiki/Directives#multi-worker-live-streaming
https://github.com/arut/nginx-rtmp-module/wiki/Directives#push

**Comment by syldri** [comment]
@akhilleusuggo   with a server you will saturate very quickly
after all, depends on your server

I already talked about this topic for Push  :  it's a very good thing for the user to look on multiserver 

we can have multiple server RTMP  with API system

**Comment by akhilleusuggo** [comment]
No , 1 server will not be saturated . Let's say you have ONLY 100mb/s , that's enough for 20 users to stream with 5mb/s ;
The server will the stream across other servers that will distribute the streams ( push )

**Comment by syldri** [comment]
when a user starts a live and they configure OBS with 2500 Kbps   100 user gives  250000 kB = 250 MB 

you have 250MB of bandwidth only for users who launch a live

don't forget the server CPU and RAM  ( hence it is important to have another server ) 


it should not be forgotten that the RTMP server uses bandwidth for HLS  ( for the time being ) 

or we both agree that it is important to have other separate servers for HLS

**Comment by akhilleusuggo** [comment]
I think you have a bit of missunderstanding how rtmp works under NGINX . 
One thing that is great about nginx-rtmp , doesn't use RAM and CPU . I've runned 12 simultanious streams on a server with 1 core 2.0ghz and 750mb RAM ( those 3$/month server ) , and the cpu ( 1vcore ) was barely hitting 30% , ram at 620mb .

> it should not be forgotten that the RTMP server uses bandwidth for HLS ( for the time being )

I don't know what you mean with this . Probably you mean IO ?

**Comment by syldri** [comment]
Hello @akhilleusuggo  I said that for the moment when the user watches the live he uses the bandwidth of the rtmp server

I did tests yesterday with 6 live at the same time, I confirm what you say 

the encoder is not on the same server where there is a saving on the RAM and the CPU

you need bandwidth to have more users for the rtmp server

if we want 5000 users to create a live, we need several servers or the importance of an API to group all the servers

on another site I have this push and load balancer system 

![image](https://user-images.githubusercontent.com/39193219/86531504-24e2d600-bec2-11ea-856c-ee13f7e63042.png)

![image](https://user-images.githubusercontent.com/39193219/86531536-70957f80-bec2-11ea-97a9-a501fec55ef4.png)

@DanielnetoDotCom 
I can give access to the server so that he can see how it is done with ngnix and the files of the push and load balancer

**Comment by DanielnetoDotCom** [comment]
> Hello @DanielnetoDotCom I want to congratulate you for this nice update we can have several RTMP servers
> 
> @DanielnetoDotCom why not create an API with a single RTMP address the 10 server forms a server with L'API
> 
> users will be randomly directed to one of 10 servers

The problem with it is because the connection have to be made on an RTMP server and then redirect it. 

I did not find this option on NGINX to allow me dynamically direct the server

**Comment by DanielnetoDotCom** [comment]
> The idea would be better to stream to 1 server . But viewers will be able to watch it from different server with Multi-worker live streaming and Push
> 
> https://github.com/arut/nginx-rtmp-module/wiki/Directives#multi-worker-live-streaming
> https://github.com/arut/nginx-rtmp-module/wiki/Directives#push
> 
> This would be like a load balancer

Yes, I agree, we can call like Wowza does, the origins and edges servers.

this will require some configurations on NGINX. maybe on the streamer site we just have to determine to what player we should direct the client

**Comment by DanielnetoDotCom** [comment]
If you are restreaming to multiple servers, I think I have to find a way to determine the best server for your client connect. **(any idea how to do it?)**

any idea how to restream it dynamically without the need to change the nginx.conf each time you have new edges.

I am open to ideas on how to do it.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom On reverse proxy server it's called ''upstream backend''
So will need a main server with Nginx that will work as load balancing , that will redirect to multiple server's .
Basically stream1 , stream2 and stream3 will all have the stream re-streamed , but the proxy will re-direct each viewer to a different m3u8 url .

On apache2 there's something like this , but I'm not familiar .

Some source info:

https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/
https://upcloud.com/community/tutorials/configure-load-balancing-nginx/

But this one will require an entire server to do that , it's complicated . 

This second example is using target JSON

https://www.youtube.com/watch?v=cGJlcR3Qf9A

**Comment by syldri** [comment]
hello , 
on my first site everything is installed with several servers 
 there is a load balance 
@akhilleusuggo     @DanielnetoDotCom    I can give you access to all the servers to see how it was configured


there is even a load balancer for RTMP and HLS

**Comment by DanielnetoDotCom** [comment]
Hi

On the reference above it was a load balance for HTTP, but there is a load balance for RTMP?

**Comment by DanielnetoDotCom** [comment]
Also as I notice we can have an Nginx load balancer pointing to an apache server, correct?

**Comment by akhilleusuggo** [comment]
Yes , Nginx is used to do that in most of the servers ( load balancing , proxy , caching etc )

**Comment by syldri** [comment]
@akhilleusuggo  on the video you sent I already have all the files, on one of my servers

I am telling you that I give you access to the server to see how it is configured No one answered me on this subject

@DanielnetoDotCom  ask me and I'll send you the info :   you save a lot of time

![image](https://user-images.githubusercontent.com/39193219/87234807-0c4c5180-c3d5-11ea-8802-1c7d2d5d59c5.png)

**Comment by qome** [comment]
Here is another video demonstrating load balancing with NGINX and RTMP: https://www.youtube.com/watch?v=xbFBjvUT-k0
