### ISSUE TITLE
Android and IOS APP 

### ISSUE THREAD

**Issue by GodgivenButhelezi** [WWBN/AVideo#3336]
Greetings Mr Daniel. I would like to inquire that if I purchase both the IOS and Android App ,Do you also give the source code for modification Purposes ? For instance if I would like to hire someone else to make changes in it, Because I don't want mine to be the same as others.

**Comment by DanielnetoDotCom** [comment]
Sorry for the late reply

Please send the purchase questions for developer@youphptube.com
