### ISSUE TITLE
sitemap.xml

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3338]
@DanielnetoDotCom Is there anyway to limit the line bellow to 28880 ? Meaning , even if the video is longer then 8h ( 28800 seconds ) , will show 28800 no more . Because this gives errors on google webmaster when submitting sitemap .

https://github.com/WWBN/AVideo/blob/f9af7e11ad919d943fa0756d97ab08c5459f7b6b/objects/functions.php#L2172

probably :

`$duration = min(28880, ($video['duration']);` ? Is this correct ?
I'm not able to make it work .

**Comment by DanielnetoDotCom** [comment]
Thanks, I will send an update for it soon

**Comment by akhilleusuggo** [comment]
I'm not able to make it work with this line , but you may help

**Comment by DanielnetoDotCom** [comment]
What exactly is the error? Are you sure is regarding the video duration?

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/86786511-c6a62680-c06c-11ea-8a5a-f232bc09ed91.png)

Another thing is the description : 

![image](https://user-images.githubusercontent.com/52116577/86786657-e9383f80-c06c-11ea-8023-02717771c09b.png)

**Comment by akhilleusuggo** [comment]
thanks !
