### ISSUE TITLE
suppress others' streams on channels

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3339]
hello 
I would like to know how to deactivate this element on the channels

![image](https://user-images.githubusercontent.com/39193219/86533080-cc660580-bece-11ea-905e-67fddfae8ccc.png)

**Comment by akhilleusuggo** [comment]
I'm not sure if possible to disable it from channels , but you can unlist them from all ( and keep only the notification bell )

![image](https://user-images.githubusercontent.com/52116577/86533181-e0623500-bed7-11ea-8611-f31dedbd4550.png)

**Comment by syldri** [comment]
Hello @akhilleusuggo  thank you i tested it doesn't work

**Comment by akhilleusuggo** [comment]
clear the cache

**Comment by syldri** [comment]
it does not work when it is activated I no longer have live activity on the index page

**Comment by syldri** [comment]
I found the problem I created a script code with a display: none

**Comment by syldri** [comment]
display: none it is not a good idea to delete the live on the home page 

@DanielnetoDotCom  you will have a solution for that

**Comment by DanielnetoDotCom** [comment]
Why it is not a good idea?

**Comment by syldri** [comment]
I show you pictures when I put displayed: none for the channel page, on the home page the live also disappears

**- Before**

![image](https://user-images.githubusercontent.com/39193219/88387224-5c062200-cdb2-11ea-8a11-d611fe62acd8.png)

 **and after**

![image](https://user-images.githubusercontent.com/39193219/88387178-43960780-cdb2-11ea-8b6c-fa559bf1c602.png)



I just want to remove this party the channel of one of a user it is personal no information of other user on a channel


![image](https://user-images.githubusercontent.com/39193219/88387790-899f9b00-cdb3-11ea-840c-edd72f9113af.png)

**Comment by syldri** [comment]
I found the code,

I performed several tests to undo this div in CSS or JS

it does not work for the moment


![image](https://user-images.githubusercontent.com/39193219/88388037-029ef280-cdb4-11ea-9f7f-9b52a53c40e7.png)

**Comment by DanielnetoDotCom** [comment]
Hi, 

you should just add the CSS

```
#extraVideos{
  display: none;
}
```

**Comment by syldri** [comment]
I tested with what you gave me it doesn't work

**Comment by DanielnetoDotCom** [comment]
Sorry, it was a wrong CSS. the correct one is 

```
.extraVideos{
  display: none;
}
```

**Comment by syldri** [comment]
@DanielnetoDotCom  the css code also removes the live thumbnail from the home page  

the css code must remove the thumbnails of the live only for the channels
 
![image](https://user-images.githubusercontent.com/39193219/88412413-d26a4a80-cdd9-11ea-9b08-b3cda2b2653e.png)

**Comment by DanielnetoDotCom** [comment]
Try this then

```
.liveVideo{
  display: none;
}
```

**Comment by syldri** [comment]
@DanielnetoDotCom   this code remove the live Live Link on the home page  

and he removes Live Link in the Chanel  

in the channel we still have live rtmp display


![image](https://user-images.githubusercontent.com/39193219/88417619-84a61000-cde2-11ea-87bf-93ae41dcd804.png)

**Comment by DanielnetoDotCom** [comment]
Let me see if I understand correctly.

you have LiveLinks and RTMP Live.

you want only to remove the RTMP live

but you do not want to remove the RTMP live from the main page, just from the player page.

is that correct?
