### ISSUE TITLE
PHP7.4 error on upload for plugin

### ISSUE THREAD

**Issue by daoguey** [WWBN/AVideo#3340]
This is what i get when i try to upload a plugin (customize in specific) PHP7.4v used: 
![image](https://user-images.githubusercontent.com/15695109/86557126-7d41c400-bf12-11ea-8a50-7fe4328ee747.png)

**Comment by DanielnetoDotCom** [comment]
I cannot see any error in your log file 
Also I am not aware of any  incompatibility regarding PHP 7.4

**Comment by daoguey** [comment]
Last two lines in the log

**Comment by DanielnetoDotCom** [comment]
What plugin are you talking about here?

**Comment by daoguey** [comment]
any, any plugin. they used to upload and tell you it is done but now they just spin and nothing hapens: 
![image](https://user-images.githubusercontent.com/15695109/86697522-b25e1d00-bfcb-11ea-89af-3727411bda0c.png)

**Comment by daoguey** [comment]
sorry, only the customize plugin, the rest of them were fine.

**Comment by DanielnetoDotCom** [comment]
The log file did not tell me much.

can you please delete your log file, delete the customize plugin folder (if exists). upload the plugin and share your log again!

questions:

does the plugin folder is created?

**Comment by daoguey** [comment]
i found out that it does create it and does it but kind of weird why it should take this long. you are set I was able to install it without no issue.
