### ISSUE TITLE
New Upload Video Will Not Play

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#3341]
I'm getting this wired message with "...jordanbroadcastingnetwork.com..."  does anyone know what that is and do I fix it?

![image](https://user-images.githubusercontent.com/739391/86599050-16e98f80-bf6c-11ea-86e4-ec88647687e1.png)

**Comment by DanielnetoDotCom** [comment]
Please check the console log and the php error log for some clue

**Comment by willpower68** [comment]
Thanks, @DanielnetoDotCom Daniel I always forget that I should do that first.

these are the two statements I believe are related to the video.  Unfortunately, I'm not sure what all this means. If anyone is willing to take a look.  I welcome the opportunity to learn.


UPDATE videos SET title = Tony Mobley Trailer,clean_title = tony-mobley-trailer, filename = _YPTuniqid_5f028114012d89.51285972, categories_id = 1, status = a, description = , duration = 00:01:24, type = video, videoDownloadedLink = , youtubeId = , videoLink = , next_videos_id = NULL, isSuggested = 0, users_id = 23, trailer1 = , trailer2 = , trailer3 = , rate = 0, can_download = 0, can_share = 0, only_for_paid = 0, rrating = , externalOptions = , sites_id = NULL, serie_playlists_id = NULL , video_password = , encoderURL = , filepath = , filesize = 132240330 , modified = now() WHERE id = 81n


UPDATE videos SET title = Tony Mobley Trailer,clean_title = tony-mobley-trailer, filename = _YPTuniqid_5f028114012d89.51285972, categories_id = 1, status = a, description = , duration = EE:EE:EE, type = video, videoDownloadedLink = , youtubeId = , videoLink = , next_videos_id = NULL, isSuggested = 0, users_id = 23, trailer1 = , trailer2 = , trailer3 = , rate = 0, can_download = 0, can_share = 0, only_for_paid = 0, rrating = , externalOptions = , sites_id = NULL, serie_playlists_id = NULL , video_password = , encoderURL = , filepath = , filesize = 1165458 , modified = now() WHERE id = 81n

**Comment by DanielnetoDotCom** [comment]
please provide the full log including those statements. 

we can not do much only with them.
