### ISSUE TITLE
How to use the Articles plug in?

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3344]
**Describe the question**
A clear and concise description of what is your question.

I have enabled the plugin but iam not sure how to write a article and publish it in the website,iam not able to seem to find a place for it.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by akhilleusuggo** [comment]
it's to upload an article ( .pdf extension , etc )

**Comment by vraghavans** [comment]
okies,noted thanks but from where to upload from?

**Comment by akhilleusuggo** [comment]
from your computer , on video's section ( on the streamer site )

**Comment by vraghavans** [comment]
hi,i have enabled the menu from customizeuser plugin,but still am not able to find it.Am so dumb,Can you please show me how

rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
Make sure you have this uncheked
![image](https://user-images.githubusercontent.com/18009293/87060325-c4fd6f80-c1e0-11ea-914a-eb4b923037b7.png)

Create an article here

![image](https://user-images.githubusercontent.com/18009293/87060124-85cf1e80-c1e0-11ea-8c4c-85a5afacf810.png)

you will have a form like that 

![image](https://user-images.githubusercontent.com/18009293/87060508-ff670c80-c1e0-11ea-8e80-1738a2cbc192.png)

**Comment by DanielnetoDotCom** [comment]
For other media types

![image](https://user-images.githubusercontent.com/18009293/87060669-30dfd800-c1e1-11ea-847d-1c2433229a27.png)

**Comment by vraghavans** [comment]
Thanks Daniel!You are an angel!
Got it
