### ISSUE TITLE
Donate Button

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#3345]
The "Donate button" title is currently global. Is there a way to make it so each profile can change the button title to whatever they wish?

**Comment by akhilleusuggo** [comment]
It is not global , each user can change it on my account section 
![image](https://user-images.githubusercontent.com/52116577/86795368-27862c80-c076-11ea-936d-8cdc8860feef.png)

**Comment by ganddser** [comment]
Yeah they can add their link, that's fine. I'm talking about the button title 
![screenshot](https://user-images.githubusercontent.com/37193130/86799081-841a2500-c03f-11ea-846f-ee08321472f3.jpg)
Some users might, want the button to say, Donate, or something else
