### ISSUE TITLE
Sendmail file?

### ISSUE THREAD

**Issue by HazteFama** [WWBN/AVideo#3346]
**Describe the question**
I'm trying to set email using Gmail SMTP acording the [guide](https://github.com/WWBN/AVideo/wiki/Setting-up-AVideo-Platform-to-send-emails), but when I try, server says a parameter or command on user/sbin/sendmail is not seted. I searched in the folder and I couldn't find this file. Is a hidden file or I'm searching in a wrong place or something in the configuration I made is wrong?

**Screenshots**
First screenshot is popup error and you can see config and second is the folder in the path I share in past line. 
![Anotación 2020-07-07 130803](https://user-images.githubusercontent.com/67669228/86822400-9739ee80-c059-11ea-8358-e571f58f88f3.png)
![Image 1](https://user-images.githubusercontent.com/67669228/86822402-986b1b80-c059-11ea-9888-88a23829edf9.jpg)

**Comment by DanielnetoDotCom** [comment]
Did you clicked on save before test it?

**Comment by HazteFama** [comment]
Yes, you're right!  I made it but maybe I changed something after that... so, I went again saved config and try again and a new error was showed:

Your message could not be sent!
Message could not be sent (SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting)

I think I have to go to hosting  and cloudflare and add a MX register and wait... it's true?

**Comment by DanielnetoDotCom** [comment]
If you are using google SMTP it has nothing to do with the MX records

Please make sure you allow less secure apps

If you already did it. please disable and enable it again (It is a know google configuration bug)
