### ISSUE TITLE
Live stream stopped working

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#3347]
Live stream playback is failing again. Encoder connected streaming, says online but play won't connect to and play video. Adaptive stream option is disabled. 

2. Why do I have to sign in to see if there's a live stream? When browsing the site signed out it shows 0 live broadcasts if I log in it shows the number of active streams.

**Comment by DanielnetoDotCom** [comment]
Hi

if you are using LiveUsers plugin you need to update this plugin for the new Update we have for the site.
