### ISSUE TITLE
How to Change Video Download Resolution Label

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#3349]
**Describe the question**
Hi,

I changed video resolution in the Encoder Configuration to 360p, 720p, 1080p.
**Screenshots**
![1594201012086](https://user-images.githubusercontent.com/57282919/86903830-10107780-c13a-11ea-9038-e1c3133c817e.jpg)

And I changed the resolution label to Low, HD, Full HD
**Screenshots**
![1594201191639](https://user-images.githubusercontent.com/57282919/86903924-33d3bd80-c13a-11ea-9f04-ff038a5cce8f.jpg)

After encode the video I can get the correct video resolution.
But the Label 2 position below pictures is not change.
So, Could you please kindly suggest.  How can I change the label 2 position here?

**Screenshots**
![1593680112889](https://user-images.githubusercontent.com/57282919/86904264-a0e75300-c13a-11ea-8a7e-fe9d345f8b3b.jpg)

![1593680229380](https://user-images.githubusercontent.com/57282919/86904271-a5ac0700-c13a-11ea-84d0-d26e143b3805.jpg)

Thanks
Pond

**Comment by akhilleusuggo** [comment]
The labels that you change on the plugin are the labels that correspond to the video switch resolution ( on the video player ) , and NOT on the video's file_name . 
To change that , you want to change the source-code ( hard-coded ) .
And if I'm not wrong , does correspond to this line : 
https://github.com/WWBN/AVideo/blob/48c30be472af7aee1684ffa01510892f1f1b02bb/objects/functions.php#L1054

**Comment by guitarpound** [comment]
Hi akhilleusuggo,

I already change the code from you suggestion.
But when I upload new video clip.
It show only Low & HD format.

**Screenshot**
![1593680112889](https://user-images.githubusercontent.com/57282919/86927145-254acd80-c15d-11ea-82e6-c844eca81b5a.jpg)

**Comment by akhilleusuggo** [comment]
past here what line you have changed

**Comment by guitarpound** [comment]
Hi akhilleusuggo,

I changed this line.
![1594268622999](https://user-images.githubusercontent.com/57282919/86996965-30424400-c1d7-11ea-8fe4-9048da3f4381.jpg)

Thanks

**Comment by akhilleusuggo** [comment]
ok , you need to change the encoder one too

https://github.com/WWBN/AVideo-Encoder/blob/f5ade0e6a12a13a6589988a8bcc7b1228786d0ce/objects/Format.php#L83
https://github.com/WWBN/AVideo-Encoder/blob/f5ade0e6a12a13a6589988a8bcc7b1228786d0ce/objects/Format.php#L77
https://github.com/WWBN/AVideo-Encoder/blob/f5ade0e6a12a13a6589988a8bcc7b1228786d0ce/objects/Format.php#L89

**Comment by guitarpound** [comment]
Hi akhilleusuggo,

I changed the /Encoder/objects/Format.php
**Screenshot**
![1594358210625](https://user-images.githubusercontent.com/57282919/87119288-c2198200-c2a7-11ea-8636-e93fb21da9d2.jpg)

And try upload new clip.  But it still show only Low (360p) & HD (1080p) format.
**Screenshot**
![1594358248072](https://user-images.githubusercontent.com/57282919/87119305-cba2ea00-c2a7-11ea-8100-5c4477a69b0d.jpg)

**Comment by akhilleusuggo** [comment]
check the /video's directory if the files does exist
check if they have the ''FullHD'' at the end .
Check that when you click on the video does play

**Comment by guitarpound** [comment]
Hi akhilleusuggo,

The files does exist.  
But the files name still not change to "_FullHD" at the end.
I can download and playback the video files.

![1594365389762](https://user-images.githubusercontent.com/57282919/87134168-7de7ab00-c2c2-11ea-9f94-832e42d85d95.jpg)

**Comment by boom02456** [comment]
Hi @akhilleusuggo @DanielnetoDotCom 
I've done changing the name of file, however right now the ResolutionSwitcher shows only 2 resolution instead of 3
Could you please guide me what's wrong with this?

<img width="820" alt="Screen Shot 2020-07-12 at 02 23 16" src="https://user-images.githubusercontent.com/36606195/87232100-ab2d7980-c3e6-11ea-9496-5040cfa4a4bf.png">
![Screen Shot 2020-07-12 at 02 21 21](https://user-images.githubusercontent.com/36606195/87232103-acf73d00-c3e6-11ea-94fd-96304e0b730f.png)
![Screen Shot 2020-07-12 at 02 21 15](https://user-images.githubusercontent.com/36606195/87232104-af599700-c3e6-11ea-8bf9-8f209dcf93c4.png)

**Comment by boom02456** [comment]
![Screen Shot 2020-07-12 at 02 21 21](https://user-images.githubusercontent.com/36606195/87232113-c13b3a00-c3e6-11ea-96c8-5fe175e93e08.png)

**Comment by boom02456** [comment]
![Screen Shot 2020-07-12 at 02 21 15](https://user-images.githubusercontent.com/36606195/87232120-cc8e6580-c3e6-11ea-9066-452902797b33.png)

**Comment by boom02456** [comment]
Plugins I set like this
![Screen Shot 2020-07-12 at 02 25 52](https://user-images.githubusercontent.com/36606195/87232160-10816a80-c3e7-11ea-8186-6625c95e5ef2.png)

**Comment by boom02456** [comment]
@DanielnetoDotCom 
And when I tried to remove SD and put in FullHD Label instead, it adds SD again and again
![Screen Shot 2020-07-12 at 02 32 11](https://user-images.githubusercontent.com/36606195/87232306-03b14680-c3e8-11ea-8ebb-e720d8c12868.png)

**Comment by akhilleusuggo** [comment]
for me looks like you're outdated .

**Comment by boom02456** [comment]
hmm, seems like I need to update YPT again and then update this plugins
Thanks @akhilleusuggo

**Comment by boom02456** [comment]
Hi @akhilleusuggo 
I've tried update the version of both AVideo and Plugins to latest (9.1) and (1.1)
But seems like it getting worse, now the download file not show the FullHD file and Resolution Switcher shows only 2 same as before update.
![Screen Shot 2020-07-12 at 10 43 06](https://user-images.githubusercontent.com/36606195/87238457-db980680-c42c-11ea-8f1f-3054c10f8b01.png)

![Screen Shot 2020-07-12 at 10 43 11](https://user-images.githubusercontent.com/36606195/87238459-dfc42400-c42c-11ea-9622-b93f73714cd4.png)

![Screen Shot 2020-07-12 at 10 43 53](https://user-images.githubusercontent.com/36606195/87238460-e2bf1480-c42c-11ea-8a62-278027f2ef49.png)

<img width="829" alt="Screen Shot 2020-07-12 at 10 44 04" src="https://user-images.githubusercontent.com/36606195/87238462-ea7eb900-c42c-11ea-9547-908c7c05b20c.png">

**Comment by boom02456** [comment]
@akhilleusuggo @DanielnetoDotCom Could you please suggest how to fix this? is it a bug?

**Comment by akhilleusuggo** [comment]
I just don't see any reason why wouldn't show up .
This is a template answer , but this is how we debug things : 

provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong
