### ISSUE TITLE
When one live stream is active cpu runs at 24% how can i fix this?

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#3350]
When one live stream is active cpu runs at 24% how can i fix this?

I have 4 scores 60gb ram 

When livestreaming it take up 24%, for one live stream and the stream Is choppy https://freedomshare.net/video/2812/neverwinter-tomm-run-ps4-tr-on-07-jul-20-09-56-08?channelName=FreedomShare

This was a stream using obs 

Also I had a stream from mobile app doing the same thing

**Comment by DanielnetoDotCom** [comment]
If you are using the adaptive mode this is expected.

please read this https://github.com/WWBN/AVideo/wiki/Live-Plugin#more-simultaneous-connected-users-adaptive-mode

also, please read the option for the (non-adaptive)[https://github.com/WWBN/AVideo/wiki/Live-Plugin#more-simultaneous-lives-non-adaptive]

**Comment by freedomshare** [comment]
I am not sure I had you do the install, could you turn it off it is for me.

**Comment by DanielnetoDotCom** [comment]
Done, please check now

**Comment by freedomshare** [comment]
cpu ia 2% now but i have this issue 
![image](https://user-images.githubusercontent.com/60738260/86938949-01f93180-c10f-11ea-8cb3-6d7822476ce8.png)

when  trying to watch from web browser

**Comment by freedomshare** [comment]
https://freedomshare.net/plugin/Live/?live_servers_id=undefined&c=FreeDomShare%20Live

**Comment by freedomshare** [comment]
is there a command line i have to run after retsrating server this happen the other day ater restarting

**Comment by DanielnetoDotCom** [comment]
As long as we are not transcoding now you have to tweak your RTMP publisher

something is wrong in your transmission 

![image](https://user-images.githubusercontent.com/18009293/86939659-39b8a700-c118-11ea-8d5d-3eb81c08ad45.png)


Below I am placing some images from my configuration that is working...

![image](https://user-images.githubusercontent.com/18009293/86939961-9a47e400-c118-11ea-98ba-d47f48e988ed.png)


![image](https://user-images.githubusercontent.com/18009293/86939893-80a69c80-c118-11ea-947f-fabb2ace8c8b.png)

**Comment by freedomshare** [comment]
i am live streaming from the mobile app

**Comment by DanielnetoDotCom** [comment]
I see, not sure, then. it should work, I will try from here.

I just put my android to charge the battery, I will update you soon.

**Comment by freedomshare** [comment]
ok thank you

**Comment by DanielnetoDotCom** [comment]
Hi, it was a misconfiguration on Nginx, please try again now

For future reference was missing the parameters

```
hls_playlist_length 8s;
hls_fragment 2s;
```

**Comment by freedomshare** [comment]
cpu still runs high on livestreaming 
and lags bad should i maybe restinstall my server witch isn;t on linux desktop os  could it be a os probelm

**Comment by freedomshare** [comment]
cpu still runs high could it be a os issue where i use linux desktop os

should i reinstall on a non desktop os verison

i feel like my server should be perfoming better then this

**Comment by akhilleusuggo** [comment]
if you don't transcode , there's no reason to have the CPU busy . 
Take a look on htop what is consuming that much CPU . ( how many cores do you have ? ) , it should not matter really , I have tried it on 1vcore cpu ( 2.0Ghz , and without problems )

**Comment by freedomshare** [comment]
4 cores 2.ghz 60ram  my cpu stays at 0% 
till i stream then it spikes up to 15-30% and then the lag happens
it gets all fuzzy i used the same setting as said up top for desktop streaming

**Comment by freedomshare** [comment]
https://freedomshare.net/plugin/Live/?live_servers_id=undefined&c=FreedomShare 


here is current stream

**Comment by freedomshare** [comment]
![image](https://user-images.githubusercontent.com/60738260/86956325-e6018a00-c126-11ea-832b-8cd52dd2c51b.png)
it was at 25 before screen shot

**Comment by DanielnetoDotCom** [comment]
Maybe is not the CPU is the disk I/O
try SSD disks.

I just change your parameters to 

hls_playlist_length 18s;
hls_fragment 6s;

Lets see if it will reduce the disk I/O

**Comment by freedomshare** [comment]
![image](https://user-images.githubusercontent.com/60738260/86956571-498bb780-c127-11ea-9777-2122ef37db8c.png)

**Comment by DanielnetoDotCom** [comment]
But is the livesrtream fluid?

**Comment by freedomshare** [comment]
https://freedomshare.net/plugin/Live/?live_servers_id=undefined&c=FreedomShare

**Comment by freedomshare** [comment]
still lags

**Comment by DanielnetoDotCom** [comment]
Looks fluid for me

**Comment by freedomshare** [comment]
it clear but it is not actully loading everything in the place i am at moves

**Comment by DanielnetoDotCom** [comment]
I am almost sure is your Disk that cannot handle it.

are they SSD?

**Comment by freedomshare** [comment]
no

**Comment by freedomshare** [comment]
it just disk connected the stream all together too

**Comment by DanielnetoDotCom** [comment]
You should get the advantage of the new configuration we release this week. where you can have multiple Live servers. 
https://github.com/WWBN/AVideo/wiki/Live-Plugin#livestream-server-balance

Install one separated server just for the live. get a fast disk for it and you will notice a good difference.

**Comment by freedomshare** [comment]
maybe it just my pc obs say it using 87% of my pc cpu 

i will order SSD hard drive this month

can i pay you to set up 2nd server?

**Comment by DanielnetoDotCom** [comment]
Sure no problem, it will be a pleasure.

**Comment by freedomshare** [comment]
how much SSD space do i need?

**Comment by freedomshare** [comment]
also this could be the issue it don't look like the server OS is responding well it self 
![image](https://user-images.githubusercontent.com/60738260/86981308-304d3000-c154-11ea-9ae5-03bfe074adb3.png)


them dots on the screen is the loading bar and that loading bar never gose away. 
Maybe i should install the OS with out desktop?

**Comment by DanielnetoDotCom** [comment]
For Live only 20 GB is fine.

And yes I recommend without desktop

**Comment by freedomshare** [comment]
okay ill have my server host install the ssd tomorrow when they are in.

**Comment by DanielnetoDotCom** [comment]
I guess you can move your VMs with no problem. 

If you will make a new installation without VM, directly into the Hardware (Recommended). it will require a new installation and, if you want to keep your videos, will require files and database move between servers.

**Comment by freedomshare** [comment]
oh i need with out VM? dont think that possable :(

**Comment by DanielnetoDotCom** [comment]
you can use VM, but without it is better and faster
