### ISSUE TITLE
Upload Poster Image

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3351]
Hello @DanielnetoDotCom  

nice update a question how to remove the image and return to normal mode?

you can add the option to add a photo offline

**Comment by DanielnetoDotCom** [comment]
I will upload the remove option soon

**Comment by DanielnetoDotCom** [comment]
Hi, it was a misconfiguration on Nginx, please try again now

For future reference was missing the parameters

```
hls_playlist_length 8s;
hls_fragment 2s;
```

**Comment by DanielnetoDotCom** [comment]
Sorry about the wrong message, it should work now

**Comment by awistudio** [comment]
ERROR
Upload Poster Image
![2020-07-09_12-31-06](https://user-images.githubusercontent.com/60708776/87029253-2a049580-c1e0-11ea-9e7f-a3e6394e90ed.png)

**Comment by DanielnetoDotCom** [comment]
Please check your log file

**Comment by awistudio** [comment]
where is this log file

**Comment by DanielnetoDotCom** [comment]
please check this https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by awistudio** [comment]
[avideo.log](https://github.com/WWBN/AVideo/files/4898044/avideo.log)
I still can't change this picture

**Comment by akhilleusuggo** [comment]
I've just tested and work file , make sure you update the code .

**Comment by awistudio** [comment]
I can't do it.

AVideo 9.1! 
AVideo Encoder version 3.0!

**Comment by DanielnetoDotCom** [comment]
@awistudio please update your code again.

I found something that may be causing this.

**Comment by awistudio** [comment]
"please update your code again"

what should I do? which code

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by awistudio** [comment]
thank you very much . it works
