### ISSUE TITLE
Ajude-me a entender e sanar alguns probleminhas 

### ISSUE THREAD

**Issue by gabrielbartelega** [WWBN/AVideo#3352]
Cara poderia me falar eu comprei quase todos os plugs, eu não entendi ainda pq não esta salvando na S3 e sim ela esta configurada normal pois a utilizo em outra plataforma tudo esta colocado corretamente porem ainda nada vai para o s3.

Como uma pessoa cria a conta e já aparece para ela o level suficiente para ela upar um vídeo e fazer uma stream.

Na stream foi feito tudo conforme os seus vídeos e o git, está funcionando mas tipo a tela fica congelada.

Quando a pessoa vai encodar um vídeo tem que aparecer toda hora site de encode login e senha de permissão para o encode? queria deixar isso restrito.

**Comment by DanielnetoDotCom** [comment]
Faz o seguinte captura umas telas para eu saber de que tela vc se refere, copia e cola aqui.

compartilha tambem, seu log de erro, https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
