### ISSUE TITLE
Chat2 no longer works since the update

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3355]
I have the same problem on my demo site

![image](https://user-images.githubusercontent.com/39193219/86968069-d35d7400-c16b-11ea-82b8-aa05361d92e7.png)

![image](https://user-images.githubusercontent.com/39193219/86968462-83cb7800-c16c-11ea-85ff-536f83d3a446.png)

**Comment by akhilleusuggo** [comment]
Same here ! Bug confirmed !

**Comment by DanielnetoDotCom** [comment]
Sorry about that. 

here is a fix

**Comment by CROSSMediaNet** [comment]
Where is the fix for the CHAT2?

**Comment by DanielnetoDotCom** [comment]
@CROSSMediaNet please download the Chat plugin again here https://youphp.tube/marketplace/

Just use the same user, you used when you purchase it.
