### ISSUE TITLE
Any way to hide the ypt wallet from the top nav?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3356]
I thought I seen a switch for it awhile back in the customize advance module but not sure.  would be kewl to make it a left nav feature if possible.

 <img src="https://static.buddylist.co/9994b8e9-b1ec-462a-8e48-f93f43e04a3f.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
Check this

![image](https://user-images.githubusercontent.com/18009293/87040431-0e40c580-c1c7-11ea-88a2-97e16d83552b.png)
