### ISSUE TITLE
How to change static images for Ads module

### ISSUE THREAD

**Issue by jsappo** [WWBN/AVideo#3358]
I was just wondering how to change the default sample pictures of the Ads module (728*90, etc.)

The system indicates a path accessible through a folder. Do we need to connect by FTP or is there a module for this?

Thank you

**Comment by jsappo** [comment]
Does someone know where to change those images?

**Comment by DanielnetoDotCom** [comment]
you not suppose to replace them, you suppose to use your own images.

the images can be hosted somewhere else or from an AD company provider
