### ISSUE TITLE
unparsable error from Google-please help

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3360]
got  the following message from google,please advise

Unparsable structured data issues detected on https://seafarerstube.com/

To the owner of https://seafarerstube.com/:

Search Console has identified that your site is affected by 1 Unparsable structured data issues:

Top Errors

Errors can prevent your page or feature from appearing in Search results. The following errors were found on your site:

Parsing error: Missing ',' or '}'

We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search.

**Comment by DanielnetoDotCom** [comment]
It looks like a javascript error.

I need a lot more details, code and screenshots about it if you want me to take a look.

**Comment by akhilleusuggo** [comment]
Same here daniel  , got 5 errors too

**Comment by DanielnetoDotCom** [comment]
where do I check demo site?

**Comment by akhilleusuggo** [comment]
it's on webmaster . Actually now that I'm checking my site there's many errors that happened in this last updates .

1- Many of my description are like this : 
![image](https://user-images.githubusercontent.com/52116577/87062487-c4cb9700-c215-11ea-8b46-f2951711fb45.png)

2- Same with titles , but only when it's the `'` , for example Don't = 
![image](https://user-images.githubusercontent.com/52116577/87062595-ed539100-c215-11ea-9aa3-00861d1bc43f.png)

**Comment by DanielnetoDotCom** [comment]
In what menu do you see that?

![image](https://user-images.githubusercontent.com/18009293/87062855-f9bef600-c1e3-11ea-9d79-20257f752be3.png)

**Comment by akhilleusuggo** [comment]
You don't have it , probably low ranked/Low number of pages or new site  , that's why .

Mine looks like this : 
![image](https://user-images.githubusercontent.com/52116577/87063029-79fe4f00-c216-11ea-8379-691b6c29afdc.png)

I'm still missing some too

**Comment by DanielnetoDotCom** [comment]
Maybe you are talking about this, but I do not have this section. maybe is something specific in your site.

![image](https://user-images.githubusercontent.com/18009293/87063159-5ae6c980-c1e4-11ea-95b2-794e890d1dda.png)

I can see there is an error but is not a relevant error.

**Comment by akhilleusuggo** [comment]
No daniel , as I've stated before . You don't have it because : 
1- Probably low ranked website ( yours ) 
2- Low number of pages
3- Or your site is new

**Comment by DanielnetoDotCom** [comment]
Not sure 

![image](https://user-images.githubusercontent.com/18009293/87063687-0e4fbe00-c1e5-11ea-9203-6d51a8b3986a.png)

But try to check for more details where those errors come from.

**Comment by akhilleusuggo** [comment]
Some changes on the structure with last updates broke it .

Look at how the description look ( red highlighted by google ) . 
![image](https://user-images.githubusercontent.com/52116577/87063984-c5fdc380-c217-11ea-85cf-06c63632fdf3.png)

**Comment by DanielnetoDotCom** [comment]
can you grab more from this source?

I need to know where this comes from.

**Comment by akhilleusuggo** [comment]
Daniel , check your email in 2mn .
I have found a way to check without having the option on your webmaster .

**Comment by akhilleusuggo** [comment]
sent

**Comment by DanielnetoDotCom** [comment]
Thanks, try this update

**Comment by vraghavans** [comment]
i have updated the site and tried validate fix,it again failed saying the page source is https://seafarerstube.com/channel/Admin
[code.txt](https://github.com/WWBN/AVideo/files/4899693/code.txt)

**Comment by DanielnetoDotCom** [comment]
Sorry those informations does not help much 

You need to provide some screenshots of the error and the code
