### ISSUE TITLE
How do i change the content of Help Menu?

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3363]
**Describe the question**
A clear and concise description of what is your question.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by akhilleusuggo** [comment]
it's hardcoded , manually only for now
https://github.com/WWBN/AVideo/blob/master/view/help.php

**Comment by vraghavans** [comment]
thanks for the reply!! got it!
