### ISSUE TITLE
Mobile usability issues-Google Says!!

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3364]
[mobile friendly code.txt](https://github.com/WWBN/AVideo/files/4899914/mobile.friendly.code.txt)

![image](https://user-images.githubusercontent.com/65802024/87098879-f8361200-c265-11ea-95bc-0ef20fe81e08.png)

**Comment by DanielnetoDotCom** [comment]
Not sure what you add in your page, but channels are good on demo site

![image](https://user-images.githubusercontent.com/18009293/87100982-2eeb3880-c224-11ea-93ba-846e890264ab.png)

If you want to have a good result on google inspector, try to disable the home

![image](https://user-images.githubusercontent.com/18009293/87100851-cb610b00-c223-11ea-8c57-f2351ef90543.png)
