### ISSUE TITLE
modeYoutubeBottomContentDetails - hide

### ISSUE THREAD

**Issue by awistudio** [WWBN/AVideo#3366]
how to hide a description under the video.
I don't want a link to the category
I was looking for options but I can't find it. (CustomizeAdvanced)
![hide category](https://user-images.githubusercontent.com/60708776/87133253-57f8e100-c297-11ea-8bdb-2fb15e20f497.png)

**Comment by DanielnetoDotCom** [comment]
If you cannot find an option you may try use CSS to hide it.
