### ISSUE TITLE
How can increase meta data field and genres?

### ISSUE THREAD

**Issue by anshuld977** [WWBN/AVideo#3367]
Hello Sir,

I want to increase the data field show the content to the user. like Artists in a video, director of video, comapny of video like this. and i also want to add genres in the video. Can you please tell me how can i increase the field?

**Comment by DanielnetoDotCom** [comment]
what data field are you talking about?

please screen shot

**Comment by anshuld977** [comment]
I want to add more fields in this metadata popup, Like Genres, Artists in video, Director of video, Company of video etc.

![image](https://user-images.githubusercontent.com/64984525/87270695-88868800-c4ee-11ea-8151-91522104e139.png)

**Comment by akhilleusuggo** [comment]
enable plugin Tags

**Comment by anshuld977** [comment]
@akhilleusuggo  Thanks for this.

I want to add some dropdowns also, which will be related to the video category. Like Genres of the category. I want to give dropdown to select the genre.

**Comment by anshuld977** [comment]
Hi @akhilleusuggo 
I am not able to get the video tag in the API response also how can I add the video language in a dropdown to choose the langauge,

**Comment by anshuld977** [comment]
Hello @DanielnetoDotCom ,

Can you please reply me for the above queries and also if want to change the encoder url in the advance configuration but it always sets the https://encoder1.avideo.com/
but i want to change to http://167.71.230.113/upload.

I tried to change it but it always reset for the https://encoder1.avideo.com/

**Comment by akhilleusuggo** [comment]
On the panel ( when logged as admin ) , go to configuration , advanced configuration . Change the encoder url , save

**Comment by anshuld977** [comment]
Hi @akhilleusuggo ,

I tried the same but it always reset, can I send you a video?

**Comment by anshuld977** [comment]
You can check the video in this link 
I done the same what you suggested

https://www.loom.com/share/69da95e7a0cd4985b92122c6ac5c1832

**Comment by akhilleusuggo** [comment]
Interesting ... Could you show the logs at the moment when you try to save the configuration ? Should give some clue .

Before you proceed , do this : 

`cd /var/www/html`
`chown www-data:www-data -R *`
`sudo service apache2 restart`

If still the issue persists , please share the logs .

**Comment by anshuld977** [comment]
Thanks for this, It is working now..

Can you please for my above query how can get the video tags in the video API?

**Comment by akhilleusuggo** [comment]
I'll close this issue since it's fixed . Open a new issue to get better support .
