### ISSUE TITLE
Live stream thumbnails will not upload

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3369]
after clicking upload it just shows a error that says true

<img src="https://static.buddylist.co/thumbnail%20upload%20error.png" style='width:100%;' border="0" alt="Null">

**Comment by akhilleusuggo** [comment]
I think you haven't updated . This issue as been fixed already .
https://github.com/WWBN/AVideo/issues/3351

**Comment by JoshWho** [comment]
Daniel just updated everything for me yesterday. When did this update happen?

**Comment by JoshWho** [comment]
It is fixed.
