### ISSUE TITLE
VideoDocument plugin problem

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#3371]
**Describe the question**
Hi Daniel,

I found problem about VideoDocument plugin.
When I upload document file size more than 12MB.
It will show error below picture.

**Screenshots**
![screencapture-192-168-1-5-mvideos-2020-07-11-16_47_32](https://user-images.githubusercontent.com/57282919/87221837-544d8300-c399-11ea-9b9b-f49d08d90172.png)

**Comment by DanielnetoDotCom** [comment]
Please provide the log file

**Comment by guitarpound** [comment]
Hi Daniel,

Here is log file.
https://drive.google.com/file/d/1PwtN-ufs-SrQGJgum1Qt-LjPssYKAQnQ/view?usp=sharing

Thanks

**Comment by DanielnetoDotCom** [comment]
you should share only the log file at the moment the error appears, not a 150 MB text file

**Comment by guitarpound** [comment]
Hi Daniel,

So sorry for my misunderstand.

[11-Jul-2020 22:54:49 Asia/Krasnoyarsk] PHP Warning:  Error while sending STMT_PREPARE packet. PID=10319 in /var/www/html/macrocare/objects/mysql_dal.php on line 84
[11-Jul-2020 22:54:49 Asia/Krasnoyarsk] Array
[11-Jul-2020 22:54:49 Asia/Krasnoyarsk] [sqlDAL::writeSql] Prepare failed: (2006) MySQL server has gone away<br>
INSERT INTO documents ( `id`,`filename`,`description`,`is_public`,`created`,`modified`,`videos_id`,`status`,`data`,`link`,`price` ) VALUES ( NULL ,  'wanca2020.pdf' ,  NULL ,  '1' ,  now() ,  now() ,  '178' ,  'a' ,  'JVBERi0xLjQNJeLj.......

Thanks

**Comment by DanielnetoDotCom** [comment]
Ok, that is your problem.

This is not a code problem, it is a server problem. try to google for a solution.

I bet you are using mariadb instead mysql!

**Comment by boom02456** [comment]
Hi Daniel, this is the server that you installed for us. so it should be MySQL and I still using MySQL to store the data

**Comment by DanielnetoDotCom** [comment]
how much ram does it have it?

are you running the latest version?

**Comment by DanielnetoDotCom** [comment]
Again, it is a server problem, please read this

https://stackoverflow.com/questions/53469793/e-warning-error-while-sending-stmt-prepare-packet-pid

**Comment by boom02456** [comment]
Ah okay, I will look into that. Thank you so much Daniel ;)
