### ISSUE TITLE
Title of the tags

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#3372]
Hello
it is possible to display the title of the tags  in the plugin gallery
as shown in YouPHPFlix2 ?

Thank you
Ilias

![flix1](https://user-images.githubusercontent.com/60543030/87227588-6250d300-c39c-11ea-9889-efbb3f7b039b.jpg)
![flix](https://user-images.githubusercontent.com/60543030/87227590-65e45a00-c39c-11ea-8e0c-f99a80fbf29c.jpg)

**Comment by DanielnetoDotCom** [comment]
It is hardcoded, so to add it it will require some code.

currently, there is no option to show this text.

**Comment by wetubeclub** [comment]
OK! Thank you Daniel
