### ISSUE TITLE
I Dont see the Tip Icon on Chat2

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#3373]
Here you can see the Tip Icon and works great on the deml i want to have it on mine after the proper installation from you i dont see that Tip bottom with the Chat2 please let me know how to add it. That a nice thing to have. 
![Screenshot_20200711-105727_Chrome](https://user-images.githubusercontent.com/63973045/87228036-a1ffc680-c36c-11ea-8265-908cd6712fe8.jpg)

**Comment by DanielnetoDotCom** [comment]
Please check this

https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform#donations

**Comment by syldri** [comment]
Hello @DanielnetoDotCom   you could have created a real donation system it is the owner of the site who manages everything

**Comment by LATINMIXMASTERS** [comment]
Thank you Daniel atleast this will help the streamer to get some money to pay for subscription on my web to be able to use the live stream. Thank you. Again. Also.have another issue related with the chat. Using the static set on the chat2 you cannot type or do anything on mobile devices so i have to set it with static so it will appear at the bottom the little icon amd if you press it then it works good but when is always open on mobile device is impossible to write.

**Comment by DanielnetoDotCom** [comment]
@LATINMIXMASTERS can you please screenshot the type issue?

**Comment by LATINMIXMASTERS** [comment]
Daniel is hard to post a Photo because wont show the issue since is a problem when typing but what i did was change the aize of the chat2 and make it as pop up because when is open at all times wont let me write on mobile phone.

**Comment by syldri** [comment]
Hello @DanielnetoDotCom   this is a very big problem that has been mentioned several times for mobile phones
it would be really nice if you look at this problem

**Comment by unconservo** [comment]
this is not fixed. Still problem
