### ISSUE TITLE
Information about this is error

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3374]
hello  i don't know if it's a bug when i look in the video.log there is a lot of ERROR

when I watch the video was in the YPTStorage plugin

![image](https://user-images.githubusercontent.com/39193219/87251552-d35fbb80-c46c-11ea-8b1a-9ba2150a0a5e.png)

there is errore 404 when I click on the link in question I have

![image](https://user-images.githubusercontent.com/39193219/87251826-db205f80-c46e-11ea-84aa-1353a869127d.png)

Link 

![image](https://user-images.githubusercontent.com/39193219/87252010-238c4d00-c470-11ea-9394-915117f16f4b.png)

video.log

![image](https://user-images.githubusercontent.com/39193219/87251949-b11b6d00-c46f-11ea-87c4-8812f4a33d12.png)

**Comment by DanielnetoDotCom** [comment]
basically you can ignore all those errors.

also, the wget empty error will not appear anymore if you update your streamer
