### ISSUE TITLE
Delete video currently encoding

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3375]
I want to delete this file from the encoder.

![enco](https://user-images.githubusercontent.com/65451390/87254045-55111280-c488-11ea-959c-a5aacdcc2182.png)

this is a livestream that is currently being encoded.

How do you delete it?

**Comment by akhilleusuggo** [comment]
Quick Answer : You can't .
Even if you log as admin , and delete it , the ffmpeg process keeps alive .
You need to delete it as admin , then kill the ffmpeg's PID process .

**Comment by jengajenga** [comment]
thank you man. i appreciate the response.
