### ISSUE TITLE
Choosing A Host Provider 

### ISSUE THREAD

**Issue by MyBlissIT** [WWBN/AVideo#3376]
1. Let us assume that on my platform 500GB worth of video content is uploaded per month.

2. Let us also assume that an average of 2000 concurrent users view live streaming events, and an average of 5 live streaming takes place each day....

This gives us 10 000 live streams a day and 300 000 live streams a month

3. All videos in HD

Can this Dedicated hosting be sufficient?

N.B when I used the AWS calculator it seemed that it would be expensive....

![Screenshot_20200713-000324_Samsung Internet](https://user-images.githubusercontent.com/34719141/87257594-74199f80-c49c-11ea-9ad6-856149a119e6.jpg)

**Comment by akhilleusuggo** [comment]
by the 10TB bandwidth I guess no
