### ISSUE TITLE
S3 Storage and BackBlaze

### ISSUE THREAD

**Issue by MyBlissIT** [WWBN/AVideo#3377]
I am new to this platform and look forward to making use of it.

I just have an issue I need clarity on.

If I have a Dedicated VPS with 500GB disk space + 1TB traffic/bandwidth and 16GB Ram with 4 CPUs..... 

1. Can this handle daily live streaming instances viewed by at least 5000 concurrent users?

2. With this much storage, do I still need BackBlaze or S3? How really does this external storage thing work? How are videos sent to this storage and then streamed via the website whilst I would be havin a hosting plan with another provider?

**Comment by akhilleusuggo** [comment]
the issue I see right now is your 1TB traffic/bandwidth

That one can't even handle a single day of lifestreams 
[ 5000 users * 5mb/s *2h/stream ]  = 17TB traffic/day

You will need to transcode the streams , but that's impossible with your hardware .

**Comment by MyBlissIT** [comment]
> the issue I see right now is your 1TB traffic/bandwidth
> 
> That one can't even handle a single day of livestreams
> 
> **[ 5000 users * 5mbps/stream * 2h/stream ] = 17TB traffic/day**
> 
> You will need to transcode the streams , but that's impossible with your hardware .

1. Doesn't the platform (AVideo/YouPHPTube) transcode live streams? I had installed the transcode that comes with the install package...

2. Would purchasing additional hosting plan with extra bandwidth per live stream instance do the trick?

3. The S3 and B2 storage, with 500GB disk space on a hosting plan, will I need the s3/B2 storage?

**Comment by DanielnetoDotCom** [comment]
> Doesn't the platform (AVideo/YouPHPTube) transcode live streams? I had installed the transcode that comes with the install package...

the transcode is a configuration in your Nginx. if your server can handle it feel free to use it.

> Would purchasing additional hosting plan with extra bandwidth per live stream instance do the trick?

You can do that

> The S3 and B2 storage, with 500GB disk space on a hosting plan, will I need the s3/B2 storage?

This question is confusing, but if you will need S3 or B2 it is up to you, depends how much videos you want to host
