### ISSUE TITLE
Setup disk quota

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3378]
I would like to have information about this plugin

I would like to know if it is an installation on another server like the YPTStorage plugin 

I would like to know if it takes into account the recording of the streaming videos ?

I have the YPT Storage plugin, it is compatible ?

I would like to know if the user is informed in real time how much he has left

**Comment by DanielnetoDotCom** [comment]
> I would like to have information about this plugin
> I would like to know if it is an installation on another server like the YPTStorage plugin

No, it will be installed into the streamer server

> I would like to know if it takes into account the recording of the streaming videos ?

The recording live plugin is another one

> I have the YPT Storage plugin, it is compatible ?

yes

> I would like to know if the user is informed in real time how much he has left

Yes

**Comment by syldri** [comment]
if it is compatible the recording of the videos is done on the YPTStorage plugin ?

**Comment by DanielnetoDotCom** [comment]
yes it is

**Comment by syldri** [comment]
thank you very much i will buy it
