### ISSUE TITLE
Cannot save live streaming

### ISSUE THREAD

**Issue by daoguey** [WWBN/AVideo#3379]
I installed the plugin and followed the WIKI and guide but this is the 3rd time i am not able to save the link in chrome i get this issue: 
![image](https://user-images.githubusercontent.com/15695109/87272871-c1920e80-c494-11ea-8c12-b53474667062.png)

my: tail -n 200 -f /var/www/AVideo/videos/avideo.log

gives me this: 
![image](https://user-images.githubusercontent.com/15695109/87275269-f99c5000-c49a-11ea-8986-594193893bac.png)

my nginx.conf file is: 
  worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            allow publish 127.0.0.1;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://live.qerotv.com/plugin/Live/on_publish.php;
                            on_play http://live.qerotv.com/plugin/Live/on_play.php;
                            on_record_done http://live.qerotv.com/plugin/Live/on_record_done.php;
                            recorder video{
                             record all;
                             record_path /var/www/tmp;
                             record_notify on;
                             record_max_size 2048M; 
                             #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
                             record_suffix -%d-%b-%y-%T.flv;
                            }
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    listen 444 ssl;
                    server_name localhost live.qerotv.com;
                    ssl_certificate /etc/letsencrypt/live/live.qerotv.com/fullchain.pem;
                    ssl_certificate_key /etc/letsencrypt/live/live.qerotv.com/privkey.pem;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   
            }
    }

Can you guys tell me what i am doing wrong? i followed the tutorial and i have ubuntu 20.04

**Comment by akhilleusuggo** [comment]
This should be removed 

`allow publish 127.0.0.1;`

Restart rtmp after removing it

**Comment by daoguey** [comment]
tried that no dice. any direction that can be given please that would be great.

**Comment by akhilleusuggo** [comment]
we need the logs of nginx on `/usr/local/nginx/log`

**Comment by daoguey** [comment]
[error.log](https://github.com/WWBN/AVideo/files/4945655/error.log)
[access.log](https://github.com/WWBN/AVideo/files/4945656/access.log)

those are the files for logs: error.log and access.log

logs for AVideo

[avideo.log](https://github.com/WWBN/AVideo/files/4945661/avideo.log)

Config for Nginx.conf:

[nginx.txt](https://github.com/WWBN/AVideo/files/4945672/nginx.txt)

let me know what have i done wrong

ubuntu 18.04 with PHP7.4 
encoder in same place
OBS from server connects and send signal but cannot save either offline status persists.
stats loaded but live i get error: 403 forbidden
![image](https://user-images.githubusercontent.com/15695109/87903254-cc125200-ca18-11ea-81fa-f11099aae208.png)


setup adaptative: https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream
setup nginx: https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

Recomend updating those two to be on par with current configuration.
Recomend to do a all in one setup in order to avoid typos or other issues.

thank you all for this tutorial and help figuring out what i am doing wrong

**Comment by akhilleusuggo** [comment]
I don't see any issue 
https://live.qerotv.com:444/stats is working 

> Recomend updating those two to be on par with current configuration.
> Recomend to do a all in one setup in order to avoid typos or other issues.
> 
> thank you all for this tutorial and help figuring out what i am doing wrong

We can't do that because not everybody want adaptive-streams , nor they have HLS plugin . Without HLS plugin the adaptive stream does not work . If you have the config of adaptive and you're not using it , the stream will not work .

**One last thing** , make a screenshot of your Live Plugin configuration .

**Comment by akhilleusuggo** [comment]
Ok , I just took a look on your nginx config . It's wrong .

Try this one instead : 
[nginx.txt](https://github.com/WWBN/AVideo/files/4945850/nginx.txt)

**Comment by daoguey** [comment]
tried that and i have the online and offline still going on in AVideo

**Comment by daoguey** [comment]
even with HLS i am not able to put it in online, i streamed a video without HLS and i still get offline.

is there any other log to find out why i get the online and offline or even finishing status trying to change every 3seconds?

**Comment by akhilleusuggo** [comment]
does the stream work ? Yes or No ?
If yes , Is your issue ONLY the stream Status ( Online/Offline )?
Where is the screenshot of your plugin Live ?

Your issue is not clear

**Comment by daoguey** [comment]
stream works.
one of the issues yes stream status, the other issue is saving the stream
![image](https://user-images.githubusercontent.com/15695109/88145078-1d584800-cbb7-11ea-8896-83b0379c3be8.png)

and this is the error when i go into live:
![image](https://user-images.githubusercontent.com/15695109/88145129-34973580-cbb7-11ea-9dd1-c454edca64c1.png)

my issues is simple. 1) i cannot save the stream it loads then nothing.

This is the 7th time i reinstall it and still same issue.

**Comment by akhilleusuggo** [comment]
If you're using adaptive stream , then on your plugins , you need to have enabled adaptive stream !

![image](https://user-images.githubusercontent.com/52116577/88158658-fd577180-cc14-11ea-859f-8a5cdc988cf5.png)


The url https://live.qerotv.com:444/live SHOULD ALWAYS GIVE forbidden path . This path should be secured , because it's on /HLS/Live/
What comes after /live is what should be public .

**Comment by DanielnetoDotCom** [comment]
Hi

there is any file saved on `/var/www/tmp` ??

if there is not, check the directory permission (`chmod 777 /var/www/tmp`) and restart Nginx.

Also this URL is redirecting to https `http://live.qerotv.com/plugin/Live/on_record_done.php`
It MUST be http, try to use the IP or create a subdomain to all 

```
on_publish http://live.qerotv.com/plugin/Live/on_publish.php;
on_play http://live.qerotv.com/plugin/Live/on_play.php;
on_record_done http://live.qerotv.com/plugin/Live/on_record_done.php;
```

**Comment by daoguey** [comment]
ok so i found an error in the NGINX.conf file:
![image](https://user-images.githubusercontent.com/15695109/88373169-94771300-cd54-11ea-8b22-617a57fb513a.png)

@DanielnetoDotCom  i did had files in tmp (i have it as in chmod 777 already)

in regards to MUST be HTTP for : http://live.qerotv.com/plugin/Live/on_record_done.php

please explain either trying to use IP (example please) or creating a subdomain in either apache or NGINX.config file.

I think i might have let's encrypt is redirecting all Port 80 to 443.

now, question why can we not redirect and be over TLS as is RTMPS? that would put at risk my website if i do non HTTPS.

**Comment by akhilleusuggo** [comment]
RTMPS is not implemented yet , but the streams will be over HTTPS ( but the stream from your computer to the server will not be encrypted , but once it reaches the server , from the server to the users WILL be encrypted . )

Now that I see on your config , you're missing the record options .... 

https://github.com/WWBN/AVideo/wiki/Record-Live-Stream

**Comment by daoguey** [comment]
ok, can you guys give me some direction, the recording i need to purchase the plugin, and i do not need it yet. what i need is my streams to work for this time.

if you guys can point me in the right direction that would be better. thank you.

**Comment by DanielnetoDotCom** [comment]
Open a new issue regarding make your live stream to work.

An working livestream is a requirement to record it .

**Comment by daoguey** [comment]
ok thank you. i just purchased the last plugin now. thank you.
