### ISSUE TITLE
How can i update LiveUsers plugin to version 2.0 or greater

### ISSUE THREAD

**Issue by PrXenon** [WWBN/AVideo#3380]
My LiveUser is v1 at the moment.

![image](https://user-images.githubusercontent.com/3627520/87281801-e1a4ea80-c4f3-11ea-8cb5-2474f7f63a75.png)

**Comment by akhilleusuggo** [comment]
Download the plugin from the youphp.tube again

**Comment by PrXenon** [comment]
We have "Custom Plan 3"
i cant download Plugins comes with this Plan again..

**Comment by DanielnetoDotCom** [comment]
Hi

You can download the plugin from the marketplace https://youphp.tube/marketplace/

If you purchase it and you are having problems to download, you can email developer@youphptube.com

**Comment by PrXenon** [comment]
> Hi
> 
> You can download the plugin from the marketplace https://youphp.tube/marketplace/
> 
> If you purchase it and you are having problems to download, you can email [developer@youphptube.com](mailto:developer@youphptube.com)

thanks! Now i can download and update all :-)
