### ISSUE TITLE
Video Resolution Switcher Plugin

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3382]
Does the above plugin work with Live Videos? I have installed and I cannot see it on the player.

Is there something I need to do?

**Comment by DanielnetoDotCom** [comment]
Hi

to change resolutions on live videos you may want to use this https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream

**Comment by jengajenga** [comment]
thank you. however I have followed that link

1. i edited the nginx.conf file as stated. i switched on adaptive mode. this did not work.

2. i put back the original nginx.conf and removed the # on the "exec ffmpeg". it also did not work

in both cases, i got this error

![error](https://user-images.githubusercontent.com/65451390/87395162-96eda600-c5b9-11ea-9457-a7b294361539.png)

the error goes away when I switch off adaptive mode.

**Comment by jengajenga** [comment]
Any assistance here? Thank you.

**Comment by DanielnetoDotCom** [comment]
Hi, 

Just to make clear, the adaptive will automatically change the resolution.

1. put the adaptive configuration back into the nginx.conf
2. enable it on the Live plugin
3. start a live stream 
4. try to play on the site (will probably fail)
5. share your JS console
6. share your nginx.conf
7. share your Nginx stat page
8. check if there are files in your Nginx hls_path (probably /HLS/live)

**Comment by jengajenga** [comment]
I have done as stated above. Error and JS Console in the screenshot

![js_con](https://user-images.githubusercontent.com/65451390/87481283-b4615500-c637-11ea-87a2-182e6761865f.png)

**Comment by jengajenga** [comment]
==code for nginx.conf===

`user    www-data;    
worker_processes  1;

    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
        server {
                listen 1935;
                chunk_size 4000;
                application live {
                        live on;
                        on_publish http://localhost/YouPHPTube/plugin/Live/on_publish.php;
                        on_play http://localhost/YouPHPTube/plugin/Live/on_play.php;
                        on_record_done http://localhost/YouPHPTube/plugin/Live/on_record_done.php;
                        exec ffmpeg -i rtmp://localhost/live/$name 
                            -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:240 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1200k -b:a 96k -r 20 -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_low  
                            -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:480 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 2400k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_mid  
                            -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:720 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 4200k -bufsize 100000k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi;
                }

                application adaptive {
                    live on; 
                    hls on; 

                    #hls_path /HLS/live;
                    hls_nested on;

                    allow play all;
                    allow publish 127.0.0.1;
                    deny publish all;

                    hls_variant _low BANDWIDTH=400000;
                    hls_variant _mid BANDWIDTH=2100000;
                    hls_variant _hi  BANDWIDTH=4200000;
                }
        }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    #listen 8443 ssl;
                    #listen [::]:8443 ssl;
                    #include /usr/local/nginx/snippets/self-signed.conf;
                    #include /usr/local/nginx/snippets/ssl-params.conf;
                    listen 8080;
                    server_name localhost live.jengadj.co.ke;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }               
			
			
    listen 8443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/live.jengadj.co.ke/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/live.jengadj.co.ke/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
    }`

**Comment by jengajenga** [comment]
===nginx stat page===

![stat](https://user-images.githubusercontent.com/65451390/87481755-a52ed700-c638-11ea-9df7-f153b3381ddc.png)

**Comment by jengajenga** [comment]
hls path files are available

![path](https://user-images.githubusercontent.com/65451390/87481897-f9d25200-c638-11ea-929c-51927546e831.PNG)

**Comment by DanielnetoDotCom** [comment]
Hi

what I am expecting to see in the console JS was the source m3u8 file source path.

I need to see if the file exists or it is something else.

did you enable the adaptive mode in the plugin?
