### ISSUE TITLE
Copy text to clipboard

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3383]
it will be good to add a button Copy text to clipboard

if we are on a laptop and we had no smile it would be good and for the mobile too

I did a little montage picture

![image](https://user-images.githubusercontent.com/39193219/87337454-b9dd7300-c543-11ea-8965-0b8a48f52346.png)

**Comment by DanielnetoDotCom** [comment]
Try this new Update

**Comment by syldri** [comment]
Hello  @DanielForthman  it's perfect thank you very much
