### ISSUE TITLE
Livestreaming not Playing 

### ISSUE THREAD

**Issue by Deepankar1993** [WWBN/AVideo#3384]
Hello, 
 I have installed the Youphptube on ubantu 18.* 
Everything working except the when I live stream I can't view it 
![image](https://user-images.githubusercontent.com/1295862/87338122-41d27580-c562-11ea-807e-a5f9c6ccd8b7.png)

It keeps loading However In obs I am not seeing any error  
here is the rtmp stat
![image](https://user-images.githubusercontent.com/1295862/87338215-6cbcc980-c562-11ea-8c7c-17a5a3048fe8.png)

Any Suggestion what I am missing

**Comment by CROSSMediaNet** [comment]
I am having the same problem as well

**Comment by vikramjb** [comment]
Have you tried configuring VLC to use the live URL and see if VLS is able to consume the feed ?

**Comment by Deepankar1993** [comment]
I want it to play on the site not in VLC

**Comment by Deepankar1993** [comment]
It seems like I found the problem but not the solution 
I have added SSL to the site bur it seems that the ngnix rtmp and the player is still not using it if 
https is added to the player its giving the error 
![image](https://user-images.githubusercontent.com/1295862/87382960-df0ac980-c5b5-11ea-98bd-69affd151b47.png)

Also the player shows  
![image](https://user-images.githubusercontent.com/1295862/87382977-ea5df500-c5b5-11ea-9b99-a0100b3439af.png)


Solution?

**Comment by vikramjb** [comment]
Try connecting your VLC Media Player to the RMTP link. This is to simply test if the RMTP server is actually streaming or not.

With regard to SSL, how did you add SSL to the site. Maybe you can disable it.

**Comment by Deepankar1993** [comment]
@vikramjb can you explain how we can do in in VLC?

**Comment by jengajenga** [comment]
Go to Admin -> Content -> Live Stuff -> Remove useAdaptiveMode
Click save
Restart nginx : "sudo usr/local/nginx/sbin/nginx -s stop && sudo usr/local/nginx/sbin/nginx" (without the quotes)

see if that works

**Comment by DanielnetoDotCom** [comment]
If your site is HTTPS your live MUST also be HTTPS, it you disable it and made it http it will fail for sure.

**Comment by Deepankar1993** [comment]
> If your site is HTTPS your live MUST also be HTTPS, it you disable it and made it http it will fail for sure.

What you mean ?

> Go to Admin -> Content -> Live Stuff -> Remove useAdaptiveMode
> Click save
> Restart nginx : "sudo usr/local/nginx/sbin/nginx -s stop && sudo usr/local/nginx/sbin/nginx" (without the quotes)
> 
> see if that works

Tried it didn't work

**Comment by DanielnetoDotCom** [comment]
I mean I read above you are playing with the SSL.

Make sure the apache and Nginx are on HTTPS, otherwise, it will not work

**Comment by Deepankar1993** [comment]
Yeah I did that before but now I have removed the SSL completely 
As I was using the SSL from Cloudflare{Full (strict)} it was working fine with apache but 
was giving error with ngnix so now the site is only http

**Comment by DanielnetoDotCom** [comment]
If your nginx is NOT HTTPS, you MUST use http on both, Apache and Nginx

FYI, Cloudflare can encrypt Nginx on port 8443

**Comment by Deepankar1993** [comment]
> If your nginx is NOT HTTPS, you MUST use http on both, Apache and Nginx
> 
> FYI, Cloudflare can encrypt Nginx on port 8443

Yes currently both Apache and Nginx are running on http
Thank for the port but for now I want everything to work on HTTP then I will try SSL again 

The only problem is the player is not playing the live stream its just loops between
 please wait >online >please wait...

**Comment by DanielnetoDotCom** [comment]
check your JS console panel.
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Looks like your stat file is fine.

share your nginx.conf

**Comment by Deepankar1993** [comment]
`user www-data www-data;
worker_processes  auto;
    #worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://myip/AVideo/plugin/Live/on_publish.php;
                            on_play http://myip/AVideo/plugin/Live/on_play.php;
                            on_record_done http://myip/AVideo/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name live.wichtv.com;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
		            autoindex on;
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   
            }
    }
`

I have removed the IPs as its public

**Comment by Deepankar1993** [comment]
When I am streaming with obs 
this is how it looks 
![image](https://user-images.githubusercontent.com/1295862/87424009-e0111a80-c5f8-11ea-9be0-eb06185c94e7.png)

**Comment by Deepankar1993** [comment]
Just to update I did a complete fresh install on a new server and I am getting the same behavior with the player 
Well yes I followed the steps with on the installation guide in github wiki  
I did one installation for one of my friend about 2 months ago it worked and this time same issue everytime

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/87441810-ed62e080-c5c9-11ea-9b14-dc7bc67806c1.png)

**Comment by Deepankar1993** [comment]
Hi there are no error on the JS console however I guess I have found the error its issue in the latest update to the 
Live Plugin which reloads the Player very aggressively i.e every 0.5 sec
Function : reloadVideoJS(); 
File : Plugin/Live/View/onlineLable.php

I have updated the script and now it's working 

![live1](https://user-images.githubusercontent.com/1295862/87452847-57f23b80-c61f-11ea-92da-5707ec16f76a.jpg)
![live2](https://user-images.githubusercontent.com/1295862/87452855-5a549580-c61f-11ea-8d1c-fd27de5551f9.jpg)

**Comment by DanielnetoDotCom** [comment]
this is not what I am talking about

I am talking about this 

![image](https://user-images.githubusercontent.com/18009293/87454036-d1ffd180-c5d9-11ea-8d5e-b6b21fdfd099.png)

**Comment by Deepankar1993** [comment]
yeah I Know 
I have post the console window before also 
![image](https://user-images.githubusercontent.com/1295862/87454394-883ad980-c621-11ea-9400-991911f50156.png)


This is after now that the video is running 
![image](https://user-images.githubusercontent.com/1295862/87454206-490c8880-c621-11ea-9ada-ff5db3652061.png)

**Comment by DanielnetoDotCom** [comment]
Not from this page, from the main player page.

maybe you should just share your page link so I can check myself.

**Comment by Deepankar1993** [comment]
Sure  
URL : http://wichtv.com/
id : admin2
pass : admin123

**Comment by DanielnetoDotCom** [comment]
I just edit your post, please do not share the credentials here

**Comment by Deepankar1993** [comment]
> I just edit your post, please do not share the credentials here

Thanks, and you can login and check it

**Comment by DanielnetoDotCom** [comment]
It works for me on my first attempt to live

![image](https://user-images.githubusercontent.com/18009293/87457749-4ab55c80-c5df-11ea-8c31-22c0bd2c0f4c.png)

![image](https://user-images.githubusercontent.com/18009293/87457800-5acd3c00-c5df-11ea-8448-792c9214b967.png)

**Comment by Deepankar1993** [comment]
Surprising yes it working now 
And on the same page, it was now 1hr ago.
did you update anything?  
And is there a way to reduce the stream delay?

**Comment by DanielnetoDotCom** [comment]
I did not update anything.
and to reduce the delay, you may want to try google for that.

BTW say hi, to Luke, he is a really nice guy.

**Comment by Deepankar1993** [comment]
Yeah he is,
As for ssl  with cloudflare is this config ok ? 
![image](https://user-images.githubusercontent.com/1295862/87462610-d6ee7080-c62d-11ea-8265-746582036686.png)

or Do I need to change the on_Publish on_Play and on_record_done to https links ?

**Comment by DanielnetoDotCom** [comment]
on_Publish on_Play and on_record_done cannot be https, they MUST be http

**Comment by Deepankar1993** [comment]
yeah its working Thanks I will go-ahead close this issue now
