### ISSUE TITLE
PPV For Live Stream

### ISSUE THREAD

**Issue by MyBlissIT** [WWBN/AVideo#3385]
Hi @DanielnetoDotCom,

1. Can a PPV instance be set up for a Live Stream event set to take X number of days in the future? Can the price of the view be changed?

2. Once PPV is set, can other users be manually given permission to watch the live stream without the user having processed any payment?

3. Do you only support PayPal?

4. Once a video is set as PPV, does the Right Click option that shows "copy url.." still show? - I asking this as a security measure against illegal downloads using video download sites

**Comment by DanielnetoDotCom** [comment]
> Can a PPV instance be set up for a Live Stream event set to take X number of days in the future? Can the price of the view be changed?

Yes it can

> Once PPV is set, can other users be manually given permission to watch the live stream without the user having processed any payment?

Yes

> Do you only support PayPal?

Also Stripe

> Once a video is set as PPV, does the Right Click option that shows "copy url.." still show? - I asking this as a security measure against illegal downloads using video download sites

If you enable the live protection it will not be possible

![image](https://user-images.githubusercontent.com/18009293/87424252-0495d400-c5b2-11ea-9133-71c2fb60eded.png)

**Comment by hamelinmultimedia** [comment]
as exactly it should work with protectLive enabled please
