### ISSUE TITLE
what is the comand line to update streamer?

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#3387]
hello i am not sure what the command line is to update streamer

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by freedomshare** [comment]
sorry already did that one, i asked the wrong question 
![image](https://user-images.githubusercontent.com/60738260/87429196-673aa000-c5b1-11ea-84eb-4db2e24bed3a.png)

how do i update liveplugin 
that was my bad.

**Comment by DanielnetoDotCom** [comment]
Hi

You have to download it again from the marketplace site
If your plugin is not available please email me at developer@youphptube.com

**Comment by freedomshare** [comment]
i have done that and uploaded it and it did not update

**Comment by DanielnetoDotCom** [comment]
Manually delete the LiveUsers plugin directory and upload the plugin again

**Comment by freedomshare** [comment]
whats the command line to delete?

**Comment by DanielnetoDotCom** [comment]
Google can help on this https://askubuntu.com/questions/217893/how-to-delete-a-non-empty-directory-in-terminal
