### ISSUE TITLE
VideoThumbnails not moved to video<dir>

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#3388]
Since one of the last updates (10 days) VideoThumbnails are created in YouPHPTube-Encoder/videos/sprit_3d2a55e6f514928fbd383b21cdd00c25.jpg but not moved to video(dir). 

When playing the video  instead of moving sprit_3d2a55e6f514928fbd383b21cdd00c25.jpg to video(dir) it creates a new one.

Both aVideo.log show no errors.

All plugins are updated

**Comment by DanielnetoDotCom** [comment]
May not show an error but may show a clue

First please make sure your encoder and streamers are up to date.
also, update your plugin.

also, check the videos directory/files permission.

**Comment by TLCReuver** [comment]
Encoder, streamer & plugins are updated. Files permission are not modified and still on 777
VideoTumbnails are created by encoder but not moved. 

The  backup from 04-07-2020 have not this (move)problem.

[avideo 1.log](https://github.com/WWBN/AVideo/files/4920705/avideo.1.log)
[avideo 2.log](https://github.com/WWBN/AVideo/files/4920706/avideo.2.log)

**Comment by DanielnetoDotCom** [comment]
I guess it is regarding the wget download command.

Can you please make sure you are running the latest streamer?
Also, update your VideoThumbnails plugin to version 1.1 (Download it again in the site https://youphp.tube/marketplace/) 
the get command should rise some logs that may help us to find the problem

**Comment by TLCReuver** [comment]
Last update fixed the problem.

Thanks
