### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3392]
Does not update . I created new categories and they don't show ( On the encoder does show , but not on the streamer site )

**Comment by D-Spayre** [comment]
I'm also having the same issue. Site is updated to 9.1
Categories also don't show up under PredefinedCategory plugin.

To see the category you created, you need to change the view from 10 to something else and it will show up.  Also if you add videos to your new category it shows as 0 under the category section.

**Comment by DanielnetoDotCom** [comment]
The category is cached.

did you guys try to clear the cache?

**Comment by D-Spayre** [comment]
I did still not working.

**Comment by DanielnetoDotCom** [comment]
Try this update and clear your cache when you make changes on the category (edit or add a video)

otherwise, it will only update when the session time out

**Comment by D-Spayre** [comment]
Sorry when you say try this update, how do I do the update?
Also how do I tell when there is plugin updates?

Thanks

**Comment by akhilleusuggo** [comment]
Works .
