### ISSUE TITLE
PHP Warning:  Declaration of Chat2

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3393]
when I watch the video.blog there are errors

![image](https://user-images.githubusercontent.com/39193219/87540139-70a23600-c69f-11ea-9467-cef7e51d95df.png)

**Comment by syldri** [comment]
hello @DanielnetoDotCom I have my video.log which makes 150 MB with this problem


![image](https://user-images.githubusercontent.com/39193219/87675128-4328bb80-c777-11ea-9f37-815f9295abd1.png)

**Comment by DanielnetoDotCom** [comment]
Please update your Streamer and Chat2 plugin.

**Comment by syldri** [comment]
I updated there is another bug 

I am live on my test site it remains offline



![image](https://user-images.githubusercontent.com/39193219/87678875-c3e9b680-c77b-11ea-8d7a-7acb133e37f5.png)





![image](https://user-images.githubusercontent.com/39193219/87679226-35296980-c77c-11ea-8a69-8bd77f20c525.png)

**Comment by DanielnetoDotCom** [comment]
Please open a separated issue for each different bug

**Comment by syldri** [comment]
I created for the other problem
