### ISSUE TITLE
What is going on with live streaming

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#3394]
I have been looking for a solution to the problem with live streaming. Since I update the website, I'm having issues with the live streaming and I don't how to update it with the updated website. 

I do need some help to resolve this matter...I just need direction on how to do it and I can go from there.

Thanks

**Comment by vikramjb** [comment]
You haven't mentioned what the issue is. Any crashes or console.log errors ?

**Comment by CROSSMediaNet** [comment]
Here's what it is doing since the last update for the site:

![image](https://user-images.githubusercontent.com/62782361/87507854-be815480-c633-11ea-81aa-5d3af6d50cdc.png)
 
It can record the video, but it doesn't stream at all

**Comment by DanielnetoDotCom** [comment]
please check your js console log and your php log

**Comment by CROSSMediaNet** [comment]
How to find the js log and php log?

**Comment by CROSSMediaNet** [comment]
I did try to stream again, but I don't how to find the js log and PHP log, however, here's the error message that I saw while streaming: 
![image](https://user-images.githubusercontent.com/62782361/87748301-1c8c7400-c7bb-11ea-879d-5a4a817a3bcf.png)

**Comment by DanielnetoDotCom** [comment]
Here is how to find errors

https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
