### ISSUE TITLE
Does Avideo have API for integration with other systems 

### ISSUE THREAD

**Issue by Zonalds** [WWBN/AVideo#3396]
**Describe the question**
A clear and concise description of what is your question.

Does Avideo have APIs (and documentations) for integrating into an existing solution.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
Hi

I have costumers that develop their own mobile app and backend systems with the API

**Comment by Zonalds** [comment]
Thank you very much for your reply. I am new to PHP. How do I identify the API endpoints? Is there a sort of documentation I can refer to to successfully understand the API?

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/AVideo-Platform-API
