### ISSUE TITLE
rtmp_server_control_url

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3397]
I would like to know what is the address

rtmp_server_control_url

to finish the configuration of statistics

![image](https://user-images.githubusercontent.com/39193219/87560377-aa813580-c6bb-11ea-8a77-d9c917f7a3e1.png)

**Comment by DanielnetoDotCom** [comment]
Nice panel !!!

this address is used to stop live streams from banned users

**Comment by syldri** [comment]
it's the same address in the User_Controll plugin 

thank you so much
