### ISSUE TITLE
AD_server/VAST Error

### ISSUE THREAD

**Issue by HazteFama** [WWBN/AVideo#3399]
Hi! I was trying to set a campaign and when I push the link button, show me that error. I had never used that function before, so I don't know what specifically that make.
![error link2](https://user-images.githubusercontent.com/67669228/87477911-f0c09100-c5f6-11ea-860f-adf40c9dce5a.png)
![error link](https://user-images.githubusercontent.com/67669228/87477920-f28a5480-c5f6-11ea-98a9-9eee81ba2f3a.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Error Logs**
Provide the log files at the moment you found the issue.
If you are not sure how to find the log file, please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GodgivenButhelezi** [comment]
Go to your ad server/vast plugin settings and install database files

**Comment by HazteFama** [comment]
Thanks for your help sir. @DanielnetoDotCom explained me that is not a issue, it just a code to paste in another page. I will close this issue
