### ISSUE TITLE
option to record user streaming

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3400]
hello, @DanielnetoDotCom   it is possible to have the option if the user does not wish the recording of this is streaming video

and also the administrator can prohibit the recording of video streaming to users of his choice

**Comment by DanielnetoDotCom** [comment]
We will probably add it in the future

**Comment by ganddser** [comment]
Exactly the question I was about to ask, this is definitely a need for us. We don't want everyone to record.
