### ISSUE TITLE
Live Stream Issue after v9.1 update

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#3401]
I can't seem to stream from OBS after v9.1 update.  OBS connects and streams, Stats look normal.  Just can't view it, it says "The is no streaming now".

My /var/log/apache2/error.log is filling up with:
```
--2020-07-15 19:20:48--  https://www.DOMAIN.ca:444/stat
Resolving www.DOMAIN.ca (www.DOMAIN.ca)... 127.0.1.1
Connecting to www.DOMAIN.ca (www.DOMAIN.ca)|127.0.1.1|:444... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2377 (2.3K) [text/xml]
Saving to: '/tmp/YPTurl_get_contents/e4124fbced2945dfb2ce835e84eeacfb'

     0K ..                                                    100%  373M=0s

2020-07-15 19:20:48 (373 MB/s) - '/tmp/YPTurl_get_contents/e4124fbced2945dfb2ce835e84eeacfb' saved [2377/2377]
```
Thanks

**Comment by SaliC-re** [comment]
*push*

**Comment by DanielnetoDotCom** [comment]
Please update your site with the latest version.

Screenshot your JS console and check your streamer log

**Comment by D-Spayre** [comment]
When I check for update it says v9.1 is the latest.
How do I check for Plugin updates?

JS Console

`DevTools failed to load SourceMap: Could not load content for https://www.DOMAIN.ca/videos/cache/js/bootstrap-select.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
(index):1 Mixed Content: The page at 'https://www.DOMAIN.ca/' was loaded over HTTPS, but requested an insecure element 'http://www.DOMAIN.ca/videos/_YPTuniqid_5f0f284ada2a27.66335869_HD.mp4'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
video.min.js:12 VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead
(anonymous) @ video.min.js:12
n.warn @ video.min.js:12
rs.plugin @ video.min.js:19
(anonymous) @ c309183ecb1a529ff9d5d5ed728aa36a.js?1594849384:123
(anonymous) @ c309183ecb1a529ff9d5d5ed728aa36a.js?1594849384:18
(anonymous) @ c309183ecb1a529ff9d5d5ed728aa36a.js?1594849384:21
(index):1 A cookie associated with a cross-site resource at http://pinterest.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
DevTools failed to load SourceMap: Could not load content for https://www.DOMAIN.ca/videos/cache/js/bootstrap-select.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
(index):1 Mixed Content: The page at 'https://www.DOMAIN.ca/' was loaded over HTTPS, but requested an insecure video 'http://www.DOMAIN.ca/videos/_YPTuniqid_5f0f284ada2a27.66335869_HD.mp4'. This content should also be served over HTTPS.`

Thanks

**Comment by DanielnetoDotCom** [comment]
Certainly, there are some changes.

9.1 means you have the latest database, but not the latest files.

FYI we have updates almost every day.

**Comment by D-Spayre** [comment]
Oh wow good to know, so what steps should be taken everyday to update?

Plugins too?

Thanks

**Comment by DanielnetoDotCom** [comment]
I do not think you should update everyday .

You should update only when there is a fix or a new feature that you need

**Comment by D-Spayre** [comment]
To upgrade do I do this?  https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

How do you tell if there are updates for site and plugins?  Is there a change log or somewhere to check?

Thanks
