### ISSUE TITLE
add live streaming to a category

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3402]
hello

We need to be able to add items to the category, like text or images in the header

 it is possible to add the possibility that we can add live streaming in a category : in the owner's chain

at any time he can edit and change the category as he wishes

where I put in red it is a search area I put that 3 letter it already finds me the information of the category has selected

![image](https://user-images.githubusercontent.com/39193219/87625603-d5ef3900-c72a-11ea-8b12-936ac8b6b70a.png)

- As you can see in the second image where I put in red we find the name of the selected catagory

![image](https://user-images.githubusercontent.com/39193219/87626263-38950480-c72c-11ea-9f08-3f6d6ef857c2.png)

- I did a little picture montage

![image](https://user-images.githubusercontent.com/39193219/87667313-6c8f1a80-c76a-11ea-8ab0-f698e834e01f.png)

**Comment by syldri** [comment]
Hello @DanielnetoDotCom  for the category you think you make a big change or not ?

there are several people who requested a change 

for the moment the category is not good it deserves a real change

**Comment by DanielnetoDotCom** [comment]
This will probably request a database change, so yes I guess it is not an easy change. but it is possible.

As soon as I find a sponsor, I may create this update.
