### ISSUE TITLE
"Video is private" picture in channels

### ISSUE THREAD

**Issue by SaliC-re** [WWBN/AVideo#3405]
Hey,

since our update to 9.1 we see a picture in the homescreen of all channels

![image](https://user-images.githubusercontent.com/63057086/87664608-d5c05f00-c765-11ea-867b-1ab9351f0d25.png)

You know how to fis that?

**Comment by DanielnetoDotCom** [comment]
You can disable it on customizeUser -> showChannelHomeTab

![image](https://user-images.githubusercontent.com/18009293/87666000-3cca1d80-c73e-11ea-850b-df9730bbfc5a.png)

**Comment by SaliC-re** [comment]
thanks!
