### ISSUE TITLE
live streaming PPV And Password - confirmVideoPassword.

### ISSUE THREAD

**Issue by hamelinmultimedia** [WWBN/AVideo#3407]
@DanielnetoDotCom 

hola daniel:
I made this change in confirmVideoPassword.php added lines 86 and 87 
                                        <div class="form-group">
                                            <label for="video_password"><?php echo __("This Video Requires a Password"); ?></label>

  86                                      <div class="row">
  87                                     <label for="video_password"><?php echo __("You can get it here"); ?></label>
![image](https://user-images.githubusercontent.com/53911390/87740722-85b6bc00-c7a8-11ea-991c-f4be495166bb.png)

but I think it would be very good for Avideo to have it as an option in the user's settings and ideally it can be done with live streams.
each user decides if they put their own donation button and password the each transmission they make... Thank you

![image](https://user-images.githubusercontent.com/53911390/87717136-8c780b80-c775-11ea-8580-622b99893dea.png)

![image](https://user-images.githubusercontent.com/53911390/87717365-e2e54a00-c775-11ea-973e-0e196ef2618c.png)

**Comment by hamelinmultimedia** [comment]
it would also be important if you can insert the payment button of any bank in different formats... Url 
but also <form action"https://www.paypal.com/..... or <iframe

**Comment by hamelinmultimedia** [comment]
or qr links

**Comment by jengajenga** [comment]
this looks good.

**Comment by DanielnetoDotCom** [comment]
The only way I can see if a user makes a donation to the producer will be if the donation comes from the wallet.

so the links donations are undetectable

**Comment by hamelinmultimedia** [comment]
in Colombia we cannot use paypal within the country. so we could only receive from other countries. that's why it would be good to be able to include buttons or qr horboyically... I already did and if you can, thank you very much for answering

**Comment by hamelinmultimedia** [comment]
> The only way I can see if a user makes a donation to the producer will be if the donation comes from the wallet.
> 
> so the links donations are undetectable

wallet is not viable in Colombia... because it would come out very... money from Colombia would go to the cloud in dollars and the change is 3 times more for dollar... the really good thing and not just for Colombia would be the possibility that the user could create a room to stream live. to the option to sell your tickets or charge to watch live with some payment buttons from each country ...as you already tell him for example paypal does not work in Colombia..
Additionally if you are integrating meet de jitsi this would be great... I'm already doing tests and it can be
Thank you

**Comment by DanielnetoDotCom** [comment]
@hamelinmultimedia I just add a Meet plugin, what is an integration with Jitsi

**Comment by hamelinmultimedia** [comment]
good...I'm learning from webrtc because what I need most is live streaming with webcams and cell phones... and the flash option I think is no longer good.
also install a jitsi server and it works quite well... I think something like janus or kurento can be good.
parece que tengo que hacer todo para mi proyecto.
gracias

**Comment by hamelinmultimedia** [comment]
it seems I have to do everything for my project.
Thank you
