### ISSUE TITLE
Chat bug on phones or mobile devices

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#3408]
Several of our users have reported not been able to use the chat on any phone or mobile device. I just confirmed logged in and you tap inside the message window to bring up your device keyboard it pops-up and immediately closes. This began happening after the last update [liveurestreaming.com]. 

Additionally social logins are only working in Chrome.

**Comment by DanielnetoDotCom** [comment]
Hi, I guess I found a solution for that. you will need to update your streamer and also the Chat2 plugin
