### ISSUE TITLE
My videos are always buffering and not playing smmothly,same video in youtube is flawless,what can be the issue

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3410]
All the vidoes in the platform are always buffering and not playing smoothly,same video in youtube is flawless,what can be the issue

**Comment by akhilleusuggo** [comment]
could you provide a link so we could check ?

**Comment by vraghavans** [comment]
hi!
the website link is https://www.seafarerstube.com,you can check out any of the latest uploaded videos

**Comment by akhilleusuggo** [comment]
I see no issues , plays smoothly .

**Comment by vraghavans** [comment]
Thanks for testing,
Can there be a issue with a cache? as latest videos create more issues than the older videos,and still my new videos always keep buffering,i have a decent speed of 20mbps,trust this is a good enough speed for playing the videos

**Comment by akhilleusuggo** [comment]
doesn't mater how much gb/s you have . Is not about the server , it's about your location and ISP , packet lost etc .
Probably the issue is coming from you ! Try some CDN

**Comment by vraghavans** [comment]
thanks so much for the tip!

 i have added cloudflare and i see a marked improvement!

Thank you and Daniel who provide excellent support for ignorant users like us!

Rgds
Vijay

**Comment by akhilleusuggo** [comment]
Carefully with that , you may get banned .
You need at the least Pro Plan .  You can read more about cloudflare fair usage ( for free plans )

MP4 can not be cached

**Comment by vraghavans** [comment]
thanks again!
will take care!
