### ISSUE TITLE
Stripe account changes invoice from USD 2 to USD 200

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3411]
**Describe the question**
I tried paying for an PPV which was usd 2 however the stripe account received a payment query of USD 200,

Kindly advise if its aissue with stripe or Avideo

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

![stripe screen shot for usd 200](https://user-images.githubusercontent.com/65802024/87752216-70c84000-c81d-11ea-89a9-feeed9cd959f.png)
![usd 2 invoice](https://user-images.githubusercontent.com/65802024/87752219-72920380-c81d-11ea-854f-ee39249b7b54.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, but are you sure?

please read the Stripe documentation and you will understand.

**Comment by vraghavans** [comment]
Dear Daniel,
Thanks and i did search the strip documnetation,couldnt find any co relation to USD 200,except in the log i could see s a statement of YPT setup of USD 200,any relation there?

Please guide me
thanks!
Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
Sorry I cannot explain to teach you how the programming works. but you can also this on Stripe forum

But this time I will explain ...

the 200 value is correct if you mean 2.00. on stripe you must send the value without "."
If you want to send $ 200 USD in the POST body you will send 20000

so 200 does NOT mean $ 200.00 , it means $ 2.00

**Comment by vraghavans** [comment]
Dear Daniel,
Yours well noted.
Many thanks for taking out the time for me and clarifying the same 
Appreciate!
Rgds
Vijay
