### ISSUE TITLE
Uploaded Video not appear on streamer 

### ISSUE THREAD

**Issue by khoiron81** [WWBN/AVideo#3412]
hallo 
Thank you for the great job for this app. 
I have done installation for both streamer and encoder, but i have an issue when upload video once the encoder 100% done the video doesn't appear on streamer.

Please advise what would be the cause of the problem!
Thanks in advance

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by khoiron81** [comment]
Hi Akhi,

Thank you for your kind respond, please find attached the avideo streamer log as per requested.
[avideo.log](https://github.com/WWBN/AVideo/files/4940672/avideo.log)

and encoder log bellow
[youphptube.log](https://github.com/WWBN/AVideo/files/4940680/youphptube.log)

**Comment by khoiron81** [comment]
And attached is the responses and activities of the AVideo Platform service I use the following command: 
`tail -n 200 -f /var/www/AVideo/videos/avideo.log`

[log-run-from-command.txt](https://github.com/WWBN/AVideo/files/4940722/log-run-from-command.txt)

**Comment by akhilleusuggo** [comment]
We need the encoder log , not the streamer log

**Comment by khoiron81** [comment]
encoder log attached
[youphptube.log](https://github.com/WWBN/AVideo/files/4941462/youphptube.log)

**Comment by akhilleusuggo** [comment]
Doesn't look for me to be the encoder logs . 
Are you up to date ? Did you updated ?
Are you using Linux Ubuntu distro ? What distro are you using ? Looks like windows server to me .

**Comment by khoiron81** [comment]
I am using ubuntu server 16.04 LTS, I reinstall the Avideo and encoder fresh from beginning without error and now everything look good. Thanks for your kind respond.
