### ISSUE TITLE
Who is hosting my website??

### ISSUE THREAD

**Issue by amelchizadek** [WWBN/AVideo#3414]
I would like to know who is hosting my website datanoop.com.  Please advise.

**Comment by DanielnetoDotCom** [comment]
It is on OVH, if you need more details regarding the server please email directly to me developer@youphptube.com

**Comment by Starr888** [comment]
hot to get domain name for PHPtube?

**Comment by DanielnetoDotCom** [comment]
Try Godaddy

**Comment by amelchizadek** [comment]
Daniel,

Several of videos in the list are blurred and when I click I am getting the message. The media could not be loaded, either because the server or network failed or because the format is not supported.

I can't afford to not have the videos load. Please advise.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by amelchizadek** [comment]
I am not subscribed to godaddy for hosting.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by amelchizadek** [comment]
Daniel,

If you are not going to take a look at it let me know.

V/r

Tony Melchizadek

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by amelchizadek** [comment]
Daniel,

You know what you're right. I will look for the price quote that you gave me to migrate the site and the videos to have you move my site elsewhere. Give me a few days to find a hosting company. Thanks bro.

V/r

Tony Melchizadek

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by DanielnetoDotCom** [comment]
I went to your site and I took a look.

Looks like your plugins are misconfigured, I am not sure where.

If you send the site admin credentials to developer@youhphtube.com I can take a deeper look into it and fix it.
