### ISSUE TITLE
separate chat server

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3415]
I'm testing a separate chat server
do we need to install apache2?
for configuration can give an example please

is there a command to activate the chat?

for the chat what is needed as a server, it requires a lot in CPU in RAM?

here i put what

![image](https://user-images.githubusercontent.com/39193219/87832149-9721c600-c885-11ea-936b-07f3d61c7118.png)

**Comment by syldri** [comment]
I have everything insatiable he does not want to connect to the site

**Comment by syldri** [comment]
@DanielnetoDotCom  

hello you can answer me i did everything nothing works 

I did it with apache it doesn't work, I did it without apache it doesn't work.

you can tell me how you manage to install the chat on another server with your explanation it doesn't work

thank you for your reply

**Comment by DanielnetoDotCom** [comment]
Hi, 


sorry for the late reply ....

I am trying to explain it here https://github.com/WWBN/AVideo/wiki/Chat2-Plugin#stand-alone-chat-server

Also here ...

https://demo.avideo.com/plugin/Chat2/standAlone/instructions.php

![image](https://user-images.githubusercontent.com/18009293/87940078-6309f900-ca6f-11ea-94ec-8df1530d9ec7.png)

**Comment by DanielnetoDotCom** [comment]
Here is a config sample

![image](https://user-images.githubusercontent.com/18009293/87940633-4cb06d00-ca70-11ea-97f3-e0f18f9641c7.png)

**Comment by syldri** [comment]
hello  @DanielnetoDotCom   you do not answer all my questions

you test it on a real site?
for I do not see anything on the demo site


the mysql table has been created


I followed all the steps you sent me it doesn't work

![image](https://user-images.githubusercontent.com/39193219/87958728-2c090700-cab2-11ea-84a5-c579fbeb174c.png)



![image](https://user-images.githubusercontent.com/39193219/87961377-e6e6d400-cab5-11ea-85e6-2422660c3d6c.png)



![image](https://user-images.githubusercontent.com/39193219/87961522-172e7280-cab6-11ea-888c-50fee20a72e7.png)





![image](https://user-images.githubusercontent.com/39193219/87961925-b6536a00-cab6-11ea-867f-1d6ea9bf74b7.png)

**Comment by DanielnetoDotCom** [comment]
Hi

yes it was tested in real sites.

For me is clear the chat is not there due to the 404 error on the last image.

are you sure you did not install it in a subdirectory like https://chat.yoursite.com/Chat2/?

on my sample, I install it on the domain root.

**Comment by syldri** [comment]
I did a new installation on another server I have the same problem

I made all the possible combinations
https://chat.yoursite.com/Chat2/
https://chat.yoursite.com/ 


it's not a ssl problem when I test I'm A +


May when I look at the log I have this

![image](https://user-images.githubusercontent.com/39193219/87988934-6fc73500-cae1-11ea-8248-3340cd219c1d.png)


my .conf file


![image](https://user-images.githubusercontent.com/39193219/87989122-c16fbf80-cae1-11ea-8f7f-51e651b25761.png)

**Comment by syldri** [comment]
Hello @DanielnetoDotCom 
 I did tests on 3 different servers, I have the same problem,
in my first message I asked you questions that you didn't even take the time to answer,

I think you have an instation problem with the plugin

I have been looking for a solution to this problem for 4 days

make a video with all the installation steps,

it starts to do a lot 4 days the problem is still not solved




the streamer's log
avideo.log

```
PHP Notice:  Undefined variable: isStandAlone in /var/www/html/AVideo/plugin/Chat2/index.php(14) : eval()'d code(1) : eval()'d code on line 673
[21-Jul-2020 13:34:03 Europe/Berlin] PHP Notice:  Undefined variable: isStandAlone in /var/www/html/AVideo/plugin/Chat2/index.php(14) : eval()'d code(1) : eval()'d code on line 673
```
the streamer's log  Apache

`[Tue Jul 21 13:32:53.486306 2020] [core:error] [pid 5696] [client 90.15.138.233:50236] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: https://demo.web.tv/plugin/Chat2/?room_users_id=1&iframe=1&noFade=1`

**Comment by syldri** [comment]
Hello @akhilleusuggo   Have you already installed the chat server?

**Comment by akhilleusuggo** [comment]
@syldri Hello ! To be honest , I use the chat but on the same server . I don't see ANY use for the API , unless you have 1000 of users who are writing at the same time .

My server has 16 Cores , 32GB RAM 256GB SSD / 8TB HDD . I don't see any need for that . Only bandwidth issues .
I don't think even a small server of 2 vCores and 4gb ram would have an issue with the chat . Unless you have, as I've said thousands of users sending at the same time .

**Comment by syldri** [comment]
hello @akhilleusuggo  thank you very much for your answer I am taking the lead
so as not to have any problem if there are many users at the same time

for the bandwidth with a CDN the problem is solved

I would like to know if the cat is very resource intensive like for the CPU or RAM
for for bandwidth I have a CDN for that 

I still have no answer 

I cannot connect the chat to the site, nothing works and @DanielnetoDotCom  does not respond


@akhilleusuggo  you want me to pass you a server to test?

**Comment by akhilleusuggo** [comment]
@syldri I'll give it a try once I'm back home . ( I have a free google cloud to test ) .
CDN will not solve the issue . If your badtwhith is 100mbps , the CDN will be 100mbps , not more , not less .
And does not cache mp4 or hls videos . ( at the least not cloudflare )

**Comment by DanielnetoDotCom** [comment]
Hi

I just make this video installing the Chat on a separated server, please check it out https://tutorials.avideo.com/video/81/chat-external-server-installation

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom merry christmas ( xD , too early for that music :)

**Comment by syldri** [comment]
Hello @DanielnetoDotCom 
I was able to get him to connect he stays like that and it doesn't clog

![image](https://user-images.githubusercontent.com/39193219/88108978-02330b80-cbaa-11ea-80d9-de7b1e14ec0e.png)



```
[Tue Jul 21 23:22:28.158316 2020] [php7:warn] [pid 26404] [client 90.15.138.233:54583] PHP Warning:  mysqli::prepare(): Couldn't fetch mysqli in /var/www/html/standAlone/mysql_dal.php(14) : eval()'d code(1) : eval()'d code on line 77, referer: https://demo.SITE.tv/plugin/Live/
[Tue Jul 21 23:22:28.158324 2020] [php7:warn] [pid 26404] [client 90.15.138.233:54583] PHP Warning:  sqlDAL::writeSql(): Couldn't fetch mysqli in /var/www/html/standAlone/mysql_dal.php(14) : eval()'d code(1) : eval()'d code on line 78, referer: https://demo.SITE.tv/plugin/Live/
[Tue Jul 21 23:22:28.158330 2020] [php7:warn] [pid 26404] [client 90.15.138.233:54583] PHP Warning:  sqlDAL::writeSql(): Couldn't fetch mysqli in /var/www/html/standAlone/mysql_dal.php(14) : eval()'d code(1) : eval()'d code on line 78, referer: https://demo.SITE.tv/plugin/Live/
[Tue Jul 21 23:22:28.158348 2020] [php7:notice] [pid 26404] [client 90.15.138.233:54583] AVideoLog::ERROR: Array\n(\n    [0] => Array\n        (\n            [file] => /var/www/html/standAlone/mysql_dal.php(14) : eval()'d code(1) : eval()'d code\n            [line] => 78\n            [function] => log_error\n            [args] => Array\n                (\n                    [0] => [sqlDAL::writeSql] Prepare failed: () <br>\nINSERT INTO chat_users (`id`, `user`, `email`, `name`, `identification`, `photoURL`, `channelName`,`status`, `created`, `modified`, donationLink)  VALUES ('4', 'demo', 'contact@SITE.tv', 'demo', 'demo', 'https://demo.SITE.tv/videos/userPhoto/photo4.png?1594458715', 'demo','a', now(), now(), '');\n                )\n\n        )\n\n    [1] => Array\n        (\n            [file] => /var/www/html/standAlone/User.php(14) : eval()'d code(1) : eval()'d code\n            [line] => 185\n            [function] => writeSql\n            [class] => sqlDAL\n            [type] => ::\n            [args] => Array\n                (\n                    [0] => INSERT INTO chat_users (`id`, `user`, `email`, `name`, `identification`, `photoURL`, `channelName`,`status`, `created`, `modified`, donationLink)  VALUES ('4', 'demo', 'contact@SITE.tv', 'demo', 'demo', 'https://demo.SITE.tv/videos/userPhoto/photo4.png?1594458715', 'demo','a', now(), now(), '');\n                )\n\n        )\n\n    [2] => Array\n        (\n            [file] => /var/www/html/standAlone/User.php(14) : eval()'d code(1) : eval()'d code\n            [line] => 45\n            [function] => createUser\n            [class] => User\n            [type] => ::\n            [args] => Array\n                (\n                    [0] => stdClass Object\n                        (\n                            [id] => 4\n                            [user] => demo\n                            [name] => demo\n                            [email] => contact@SITE.tv\n                            [created] => 2020-07-06 15:27:14\n                            [modified] => 2020-07-20 16:03:43\n                            [isAdmin] => 0\n                            [status] => a\n                            [photoURL] => videos/userPhoto/photo4.png\n                            [lastLogin] => 2020-07-20 14:55:53\n                            [backgroundURL] => \n                            [canStream] => 1\n                            [canUpload] => 1\n                            [canViewChart] => 1\n                            [about] => \n                            [channelName] => demo\n                            [emailVerified] => 1\n                            [analyticsCode] => \n                            [externalOptions] => YTo1OntzOjE0OiJoYXNPcHRpb25zVGVzdCI7czo1OiJmYWxzZSI7czo5OiJ5ZXNJdERvZXMiO3M6NToiZmFsc2UiO3M6MTA6ImNoZWNrbWFyazEiO3M6NDoidHJ1ZSI7czoxMDoiY2hlY2ttYXJrMiI7czo0OiJ0cnVlIjtzOjEwOiJjaGVja21hcmszIjtzOjQ6InRydWUiO30=\n                            [donationLink] => \n                            [groups] => Array\n                                (\n                                )\n\n                            [identification] => demo\n                            [photo] => https://demo.SITE.tv/videos/userPhoto/photo4.png?1594458715\n                            [background] => https://demo.SITE.tv/view/img/background.png\n                            [tags] => Array\n                                (\n                                    [0] => stdClass Object\n                                        (\n                                            [type] => default\n                                            [text] => Utilisateur r\xc3\xa9gulier\n                                        )\n\n                                    [1] => stdClass Object\n                                        (\n                                            [type] => success\n                                            [text] => Actif\n                                        )\n\n                                    [2] => stdClass Object\n                                        (\n                                            [type] => success\n                                            [text] => E-Mail Verifi\xc3\xa9e\n                                        )\n\n                                )\n\n                            [isEmailVerified] => 1\n                            [hasOptionsTest] => 0\n                            [yesItDoes] => 0\n                            [checkmark1] => 1\n                            [checkmark2] => 1\n                            [checkmark3] => 1\n                            [nameIdentification] => demo\n                        )\n\n                )\n\n        )\n\n    [3] => Array\n        (\n            [file] => /var/www/html/standAlone/User.php(14) : eval()'d code(1) : eval()'d code\n            [line] => 79\n            [function] => getUserDb\n            [class] => User\n            [type] => ::\n            [args] => Array\n                (\n                    [0] => 4\n                )\n\n        )\n\n    [4] => Array\n        (\n            [file] => /var/www/html/functions.php(14) : eval()'d code(1) : eval()'d code\n            [line] => 22\n            [function] => getPhoto\n            [class] => User\n            [type] => ::\n            [args] => Array\n                (\n                    [0] => 4\n                )\n\n        )\n\n    [5] => Array\n        (\n            [file] => /var/www/html/index.php(14) : eval()'d code(1) : eval()'d code\n            [line] => 267\n            [function] => listItem\n            [args] => Array\n                (\n                    [0] => 4\n                    [1] => \n                )\n\n        )\n\n    [6] => Array\n        (\n            [file] => /var/www/html/index.php(14) : eval()'d code\n            [line] => 1\n            [function] => eval\n        )\n\n    [7] => Array\n        (\n            [file] => /var/www/html/index.php\n            [line] => 14\n            [function] => eval\n        )\n\n)\n, referer: https://demo.SITE.tv/plugin/Live/
[Tue Jul 21 23:22:28.158384 2020] [php7:notice] [pid 26404] [client 90.15.138.233:54583] AVideoLog::ERROR: [sqlDAL::writeSql] Prepare failed: () <br>\nINSERT INTO chat_users (`id`, `user`, `email`, `name`, `identification`, `photoURL`, `channelName`,`status`, `created`, `modified`, donationLink)  VALUES ('4', 'demo', 'contact@SITE.tv', 'demo', 'demo', 'https://demo.SITE.tv/videos/userPhoto/photo4.png?1594458715', 'demo','a', now(), now(), '');, referer: https://demo.SITE.tv/plugin/Live/

```

**Comment by DanielnetoDotCom** [comment]
Did you create the separated database and tables on the chat server?

**Comment by syldri** [comment]
hello @DanielnetoDotCom   I installed the mysql server and I created a table (chat)


![image](https://user-images.githubusercontent.com/39193219/88308907-e9436b00-cd0d-11ea-8098-d8e24779a675.png)

**Comment by DanielnetoDotCom** [comment]
Please provide a more complete log.

also, try to run this in your MySQL command line terminal 

`INSERT INTO chat_users (`id`, `user`, `email`, `name`, `identification`, `photoURL`, `channelName`,`status`, `created`, `modified`, donationLink)  VALUES ('4', 'demo', 'contact@SITE.tv', 'demo', 'demo', 'https://demo.SITE.tv/videos/userPhoto/photo4.png?1594458715', 'demo','a', now(), now(), '');`

this is the SQL that rises an error

**Comment by syldri** [comment]
I found the problem

I had created a user he did not have all the rights

everything works when I have activated the rights for the user  MySQL

it made me waste a lot of time I completely forgot to activate the rights of the user of the mysql



![image](https://user-images.githubusercontent.com/39193219/88311767-99ff3980-cd11-11ea-8860-2558c5ada98f.png)

**Comment by syldri** [comment]
I'm really happy, not all css changes have been changed
