### ISSUE TITLE
display bug on ip ban

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3418]
I'm doing tests there is a display bug

there are users who change ip often the list becomes very long

some of the elements are missing

![image](https://user-images.githubusercontent.com/39193219/87877171-09f18500-c9dd-11ea-93bc-7bdfaaebafba.png)

**### this part is missing**

![image](https://user-images.githubusercontent.com/39193219/87877254-8ab08100-c9dd-11ea-859c-5a65264b12c2.png)

**Comment by DanielnetoDotCom** [comment]
Fix it on User_Controll ver 1.1

**Comment by syldri** [comment]
Hello Thank you very much it's perfect now
