### ISSUE TITLE
Job for nginx.service failed because a timeout was exceeded

### ISSUE THREAD

**Issue by ashrafpro** [WWBN/AVideo#3419]
streaming stops, then I can't connect to ubunto server

I try the command: sudo systemctl restart nginx
it says:
Job for nginx.service failed because a timeout was exceeded.
See "systemctl status nginx.service" and "journalctl -xe" for details.

systemctl status nginx.service

● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Sun 2020-07-19 16:44:25 CEST; 4s ago
     Docs: man:nginx(8)
  Process: 1281 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 1280 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)

Jul 19 16:42:55 ******.com systemd[1]: Starting A high performance web server and a reverse proxy server...
Jul 19 16:42:55 ******.com systemd[1]: nginx.service: Can't open PID file /run/nginx.pid (yet?) after start: No such file or directory
Jul 19 16:44:25 ******.com systemd[1]: nginx.service: Start operation timed out. Terminating.
Jul 19 16:44:25 ******.com systemd[1]: nginx.service: Killing process 1282 (nginx) with signal SIGKILL.
Jul 19 16:44:25 ******.com systemd[1]: nginx.service: Killing process 1283 (nginx) with signal SIGKILL.
Jul 19 16:44:25 ******.com systemd[1]: nginx.service: Killing process 1284 (nginx) with signal SIGKILL.
Jul 19 16:44:25 ******.com systemd[1]: nginx.service: Failed with result 'timeout'.
Jul 19 16:44:25 ******.com systemd[1]: Failed to start A high performance web server and a reverse proxy server.

I think the issue in NGINX, how can this be fixed?

**Comment by akhilleusuggo** [comment]
`nginx -t `

past here the output .

**Comment by ashrafpro** [comment]
nginx: the configuration file /usr/local/nginx/conf/nginx.conf syntax is ok
nginx: configuration file /usr/local/nginx/conf/nginx.conf test is successful

**Comment by jengajenga** [comment]
sudo systemctl restart nginx doesn't work on this system.
to restart your nginx, copy and paste this command (or type it out - either is fine)

/usr/local/nginx/sbin/nginx -s stop && usr/local/nginx/sbin/nginx

**Comment by ashrafpro** [comment]
> sudo systemctl restart nginx doesn't work on this system.
> to restart your nginx, copy and paste this command (or type it out - either is fine)
> /usr/local/nginx/sbin/nginx -s stop && usr/local/nginx/sbin/nginx

I've no experience with ubunto or nginx, I used the installation service when setting it up AVideo
I get this error:

**-bash: usr/local/nginx/sbin/nginx: No such file or directory**

**Comment by ashrafpro** [comment]
Yes, it is working 

**/usr/local/nginx/sbin/nginx -s stop && /usr/local/nginx/sbin/nginx**

thank you,

**Comment by frankhhuo** [comment]
@jengajenga  Thanks very much, it worked for me too,  on ubuntu 20.04.  Got exactly
 the same error when using sudo systemctl start Nginx.    wonder why it does not work on ubuntu 20.04?

**Comment by osvaldolivondeni** [comment]
> sudo systemctl restart nginx doesn't work on this system. to restart your nginx, copy and paste this command (or type it out - either is fine)
> 
> /usr/local/nginx/sbin/nginx -s stop && usr/local/nginx/sbin/nginx

It worked for me too. I just had to run it as sudo, and added a "/" in the begining of the second path:
sudo /usr/local/nginx/sbin/nginx -s stop && /usr/local/nginx/sbin/nginx

Thank you very much @jengajenga
