### ISSUE TITLE
Editing video setting from ZoomMeetingRecorder

### ISSUE THREAD

**Issue by DrDracula** [WWBN/AVideo#3420]
Is there a way to edit video settings such as private or public video, for videos come from ZoomMeetingRecoder plugin?

If there is not, is there a chance to add that feature?

**Comment by DanielnetoDotCom** [comment]
What about PredefinedCategory plugin?

![image](https://user-images.githubusercontent.com/18009293/87935193-030f5480-ca67-11ea-93a7-671acdfa7953.png)


![image](https://user-images.githubusercontent.com/18009293/87935130-de1ae180-ca66-11ea-8e69-666d9f8a3822.png)

**Comment by DrDracula** [comment]
I was looking for that. Thank for your help @DanielnetoDotCom
