### ISSUE TITLE
Ban an inactive user

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3422]
When I try and ban an inactive user, I get the processing screen and it hangs.
Anyone else try this?

**Comment by DanielnetoDotCom** [comment]
Please check your log file

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Daniel can you add an option for the ban users to make all their videos inactive as well ?

**Comment by DanielnetoDotCom** [comment]
When I user is banned, his videos should not appear as well.

are they still visible after ban?

**Comment by akhilleusuggo** [comment]
Looks like has been fixed . My issue right now is that I can not unban the users .

![image](https://user-images.githubusercontent.com/52116577/88555310-4d2ca300-d030-11ea-9fd7-cee1c3f60a8c.png)

**Comment by akhilleusuggo** [comment]
ok , my bad , need to activate it manually again . I see

**Comment by fakeologist** [comment]
Banned/Inactive users still get emails if they're subscribed to a channel. 
Can this be stopped?

**Comment by DanielnetoDotCom** [comment]
Email on new videos?

what event did you notice emails?

**Comment by fakeologist** [comment]
For new videos posted notifications

**Comment by DanielnetoDotCom** [comment]
Please update your code, it should fix the inactive subscribers
