### ISSUE TITLE
How to "can Upload Videos" LDAP NEW user

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#3423]
LDAP user login first. This User can not upload videos.
Administartor must change Can Upload Videos ON.
Please tell me How to set New LDAP user "Can Upload Videos ON first login .

**Comment by DanielnetoDotCom** [comment]
Please read this https://github.com/WWBN/AVideo/wiki/Users-Permissions#upload-rights

**Comment by hnagasawa** [comment]
Dear Daniel

Thank you for your e-mail.

We hope Automatically

Do you support your plugin ?

If your plugin not support,
We hope support .

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
I can add this option to your custom plugin.
I sent you details on the email

**Comment by hnagasawa** [comment]
+
Dear Daniel

Thank you for e-mail.

> I sent you details on the email 

>>Please read this https://github.com/WWBN/AVideo/wiki/Users-Permissions#upload-rights

detail above ?

If so, We want to add your plugin.

Do not forget cc

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
Check your email h_n***@ne*****dy**.co.jp
