### ISSUE TITLE
 First Page Style

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3426]
Hello
among all the First Page Style the best is the Gallery

I would like to have the left tab always display without having clicked on the button

a bit like YouTube's First Page Style

do you think it's possible to create a plugin to do this?

![image](https://user-images.githubusercontent.com/39193219/88057762-d17bb380-cb62-11ea-9568-c5644858e10c.png)

by default

![image](https://user-images.githubusercontent.com/39193219/88057900-07209c80-cb63-11ea-95ed-16e7e24e7eb1.png)

where I put in red I would like it to always display by default

![image](https://user-images.githubusercontent.com/39193219/88058045-3a632b80-cb63-11ea-8f35-337a85024e0c.png)

**Comment by DanielnetoDotCom** [comment]
Hi, yes it is possible, but for me to add it I need an sponsor.

**Comment by syldri** [comment]
hello, @DanielnetoDotCom  I didn't understand  (sponsor)

**Comment by DanielnetoDotCom** [comment]
Hi, 

I mean, I can only have a release date when I have someone paying for the development. otherwise, it will be possible only when I find some time.

**Comment by syldri** [comment]
hello @DanielnetoDotCom  how much will it cost to do it?

**Comment by DanielnetoDotCom** [comment]
Hi

for a quotation please use this email developer@youphptube.com
