### ISSUE TITLE
Share Button Not showing 

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#3427]
The share and download buttons ain't showing up on any videos even if they're on in the users' settings.

![sc1](https://user-images.githubusercontent.com/37193130/88071798-48ed1b00-cb42-11ea-90ad-89134b6a4b0e.jpg)
![sc2](https://user-images.githubusercontent.com/37193130/88071801-4985b180-cb42-11ea-8ffd-099afba15671.jpg)
![sc3](https://user-images.githubusercontent.com/37193130/88071802-4985b180-cb42-11ea-8728-4734e5835eb9.jpg)

**Comment by ganddser** [comment]
Update: I realized the share button fails to show up when a video is uploaded but shows up for live video @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
First, check your log file, you may find some information on it.

![image](https://user-images.githubusercontent.com/18009293/88549805-22722880-cff7-11ea-8bcf-c6595b952cd5.png)

Then check how is the option **disableShareAndPlaylist** on the CustomizeAdvanced Plugin

![image](https://user-images.githubusercontent.com/18009293/88549958-55b4b780-cff7-11ea-99b4-b5cefefd64b2.png)

**Comment by ganddser** [comment]
DiableShareAndPlaylist if not enabled
![scr1](https://user-images.githubusercontent.com/37193130/88597825-1f4a5d00-d036-11ea-9941-472ff4a2ed8b.jpg)

**Comment by ganddser** [comment]
Anything?

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/88917871-df09fb00-d23e-11ea-949f-43a1bc26e259.png)
