### ISSUE TITLE
Upgrading to 9.2 breaks compatibility with php-fpm

### ISSUE THREAD

**Issue by jyrihovila** [WWBN/AVideo#3428]
OS: Ubuntu 20.04
Apache version: 2.4.43
PHP version: 7.2

AVideo version 9.1 was working fine on the same server, running through PHP-FPM.

After upgrading to 9.2, the whole site broke down. Apache gives error 500, and the following error messages are recorded to Apache's error log:

[proxy_fcgi:error] [pid 1234] [client 1.2.3.4:12345] malformed header from script 'index.php': Bad header:
[proxy_fcgi:error] [pid 1234] [client 1.2.3.4:12345] AH01070: Error parsing script headers

Any of the logs available do not reveal exactly which index.php it is that's causing the error.

Switching to mod_php "fixes" the problem -- but it's not a real fix since mod_php has much poorer performance than PHP-FPM.

**Comment by DanielnetoDotCom** [comment]
Hi

I guess one of those lines is breaking your code.

try to comment them and let me know

https://github.com/WWBN/AVideo/blob/91abad67cf55479205d9ce2d99895e8f12f0c774/objects/functions.php#L2283
https://github.com/WWBN/AVideo/blob/91abad67cf55479205d9ce2d99895e8f12f0c774/objects/functions.php#L2284

**Comment by jyrihovila** [comment]
> Hi
> 
> I guess one of those lines is breaking your code.
> 
> try to comment them and let me know
> 
> https://github.com/WWBN/AVideo/blob/91abad67cf55479205d9ce2d99895e8f12f0c774/objects/functions.php#L2283
> 
> 
> https://github.com/WWBN/AVideo/blob/91abad67cf55479205d9ce2d99895e8f12f0c774/objects/functions.php#L2284

Daniel, I will try this fix as soon as I can (within a day or two) and report back to this thread.

**Comment by daoguey** [comment]
> Hi
> 
> I guess one of those lines is breaking your code.
> 
> try to comment them and let me know
> 
> https://github.com/WWBN/AVideo/blob/91abad67cf55479205d9ce2d99895e8f12f0c774/objects/functions.php#L2283
> 
> 
> https://github.com/WWBN/AVideo/blob/91abad67cf55479205d9ce2d99895e8f12f0c774/objects/functions.php#L2284

When I change those two i can access my website over IP not Domain, so i wonder if the initial configuration of the website broke my files that were modified by Git pull overwrite my config files.

I will leave this not commented in the mean time. 

After running over your error you got mine did not had the same @jyrihovila  so i am going to look at the config files and check my website if it has lost the initial config.

if you guys can provide me with the locations of this and manually change the setting would be much appreciated.

thank you.

**Comment by jengajenga** [comment]
I'm having the same problem. I have commented the lines but no change. My website is just blank. White page, no text no videos no pictures. Nothing.

Any other solution?

**Comment by DanielnetoDotCom** [comment]
what exactly is your OS, web server and PHP Version?

**Comment by jengajenga** [comment]
Ubuntu 18.04
Apache 2.4.29
PHP 7.2.24

THough I realise I have not updated the database.

**Comment by DanielnetoDotCom** [comment]
@jengajenga so it is working for you?

**Comment by jengajenga** [comment]
Yes. Whether I comment or uncomment the lines in function.php, it is working

**Comment by jengajenga** [comment]
did the update. i confirm db 9.2 is working.

Ubuntu 18.04
Apache 2.4.29
PHP 7.2.24

**Comment by jyrihovila** [comment]
Same here, problem fixed by installing the latest update.
