### ISSUE TITLE
UX User Checkout experience

### ISSUE THREAD

**Issue by mbbisoned** [WWBN/AVideo#3429]
Could you please share a  print screen or print screens of what the checkout process looks like for someone who is subscribing to a group/channel?

**Comment by DanielnetoDotCom** [comment]
Hi

You can check the plugin on the demo site but here is how looks like

![image](https://user-images.githubusercontent.com/18009293/88306971-c3a06c80-cce1-11ea-93a5-146f95f12efb.png)

![image](https://user-images.githubusercontent.com/18009293/88308941-0ebb7f00-cce4-11ea-8207-5a5af94aa492.png)

![image](https://user-images.githubusercontent.com/18009293/88309587-e8e2aa00-cce4-11ea-9d6e-095fbd14d5db.png)

**Comment by mbbisoned** [comment]
It looks pretty nice. Thank you.

**Comment by mbbisoned** [comment]
If I may ask, one more question, what would the screen look like if there were a basic plan, standard plan and a premium plan, would they be one on top of the other?

**Comment by DanielnetoDotCom** [comment]
Hi, do you mean like this?

![image](https://user-images.githubusercontent.com/18009293/88545885-f99b6480-cff1-11ea-9573-b70d3a9a719b.png)


![image](https://user-images.githubusercontent.com/18009293/88545924-0750ea00-cff2-11ea-8923-19b0a11e32a1.png)

**Comment by mbbisoned** [comment]
Exactly. Thank you for letting me see what it would be like.
