### ISSUE TITLE
Docker image/support

### ISSUE THREAD

**Issue by ethancedwards8** [WWBN/AVideo#3430]
**Is your feature request related to a problem? Please describe.**
I think it would be super useful to have a Docker image for AVideo, I've found one [here](https://hub.docker.com/r/ronaldod/avideo) but I'm not sure if it's up to date/supported

**Describe the solution you'd like**
Docker image creation 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jyrihovila** [comment]
This is a good idea indeed!

The problem is, maintaining the image requires time, and I don't think Daniel has too much of it available currently.

Let's see what we can do. Maybe I could donate some of my time to the Docker image operation.

**Comment by ethancedwards8** [comment]
@jyrihovila I'm willing to help too, I was actually going to start creating one. But I have no experience creating Dockerfiles so I was holding off until I learn a bit more. If you start one I'd be more than happy to help!

**Comment by daoguey** [comment]
See post #3034

This was already started.
