### ISSUE TITLE
Some Styling Issue & Chat Issues

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#3431]
On the live stream page you'll see a line through the User's Photo and Name.

When you click on Login in the Chat window it takes you to the login page but doesn't give the option to Login with FB only "Sign In", it does if you click on menu and login but just not through the chat window.  It's fine on PC just mobile.

Also with live viewers you'll see 1 viewer but 10 views, where are those 10 views coming from as I'm the only one there.

Everything is updated until today, I'm using a Note 10 with Chrome.

Thank you

![Screenshot_20200722-175326_Chrome](https://user-images.githubusercontent.com/65576427/88230600-0feb9e00-cc49-11ea-980f-3ea4626e2af9.jpg)

![Screenshot_20200722-175412_Chrome](https://user-images.githubusercontent.com/65576427/88230611-1417bb80-cc49-11ea-9338-5e76555f7366.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi

Just sent a fix for the layout.

make sure you clear your cache after update it.

**Comment by DanielnetoDotCom** [comment]
Regarding the login, are you using Chat servers?

**Comment by D-Spayre** [comment]
Thanks that fixed it.

Nope no Chat server.

Also when not logged in there is some more formatting issues.

![Screenshot_20200723-201251_Chrome](https://user-images.githubusercontent.com/65576427/88347945-798bab00-cd22-11ea-8bad-f682e7ceda0c.jpg)

Thanks

**Comment by DanielnetoDotCom** [comment]
Hi, I sent a fix to the layout above.

clear your cache and refresh the page.

Regarding the login, looks like social media does not allow you to log in from an iframe. I will need to send an update for that.

**Comment by DanielnetoDotCom** [comment]
The login should work now. it will require pop up a window

**Comment by D-Spayre** [comment]
> The login should work now. it will require pop up a window

Is this meant for the FB login?

Thanks
