### ISSUE TITLE
Backup Plugin can't download backup file after change directory

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#3432]
**Describe the question**
Hi Daniel,

I found problem after change path directory in the Backup Plugin.
It can create the backup file in the new directory and I can click delete & restore button.
But I can't download the backup file from the download button.
I saw the path directory on the download button still point to the old directory.
Please kindly help.

Thx.

**Screenshots**
![1595480800196](https://user-images.githubusercontent.com/57282919/88253810-6a363e80-ccdd-11ea-9a9c-6e6aaa72dd30.jpg)

![1595479524306](https://user-images.githubusercontent.com/57282919/88253794-5ee31300-ccdd-11ea-8d70-6cfb701abff6.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi

was the backup made on the directory you specify on the configuration or in the other directory?

But FYI, I do not think you can download files from `/videos/backup` dir. is possible Apache cannot read this directory.

Change the directory is good if you use an internal routine to get the files. if you want to be able to download you should use the default path.

**Comment by akhilleusuggo** [comment]
Yes , you need to add a readable directory for apache2
You can do that by adding /videos/backup on /etc/apache2/apache2.conf
You also need to give permissions and user grp .

All this not recommended if you're not sure how to configure it .
Usually backups are on /var/backup ( but also not a readable directory )
