### ISSUE TITLE
Error in installing in virtual host

### ISSUE THREAD

**Issue by khoiron81** [WWBN/AVideo#3433]
HI Sir, 
Please guide me what to do. I am able to install in apache default host. But when i try to re-install in virtual host i got this error screenshot attached 
![error](https://user-images.githubusercontent.com/58836894/88274348-c3b26380-cd05-11ea-9304-6b98562f4877.PNG)

Please advise.
Thanks

**Comment by akhilleusuggo** [comment]
If you understand english , all you have to do is read . Follow the instructions .

**Comment by khoiron81** [comment]
Thanks for your advise

**Comment by khoiron81** [comment]
I know ehre is the problem, the file htaccess are not uploaded that is why cause the error

**Comment by jyrihovila** [comment]
> I know ehre is the problem, the file htaccess are not uploaded that is why cause the error

This can easily happen.

So did you get your installation work now?

**Comment by khoiron81** [comment]
The installation is work now. but video is not appear after upload. I will find out the issue :) 
learning by  doing :)

**Comment by jyrihovila** [comment]
> The installation is work now. but video is not appear after upload. I will find out the issue :)
> learning by doing :)

Would you like to share what's recorded in the log file of the Streamer and the Encoder during and after the upload? The log file is located in the videos folder of both the Streamer and the Encoder.
