### ISSUE TITLE
Chat2 does not load the content, controls do not work [SOLVED]

### ISSUE THREAD

**Issue by jyrihovila** [WWBN/AVideo#3435]
Version information:
- OS: Ubuntu 20.04
- Apache: 2.4.43
- PHP: 7.2.32-1
- AVideo: 9.2

Chat2 pop-up window opens up properly, but the contents remain empty. My numerical user ID is shown instead of the actual user name. The controls do not work; even closing the Chat2 pop-up does not work. A screen capture of the pop-up window is available here: https://ibb.co/tJTm82C

If I try and open the chat in a separate window (using address similar to https://myserver.foo/plugin/Chat2/?room_users_id=11&iframe=1&noFade=0#) then I can see other users listed properly on the left. But no other content is there, and my own user ID is still shown in the numerical instead of human-readable format.

The only related error message I can find is this line in Apache's error log:

`AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.`

The error above is recorded when the client (browser) attempts to fetch the favicon.

**Comment by jyrihovila** [comment]
Maybe a duplicate of this: https://github.com/WWBN/AVideo/issues/3089

**Comment by DanielnetoDotCom** [comment]
this is a problem for sure.

maybe something regarding your HTTP to https redirect

**Comment by jyrihovila** [comment]
Updating the plugin to the latest version fixed the issue. 👍
