### ISSUE TITLE
MEus plugins sumiram

### ISSUE THREAD

**Issue by gabrielmais** [WWBN/AVideo#3437]
![image](https://user-images.githubusercontent.com/7960434/88422038-f4ef6a00-cdbf-11ea-9e91-6fb11f521f20.png)

meu plugins sumiram

**Comment by DanielnetoDotCom** [comment]
Aparentemente algum erro no script.

verifique seu avideo.log

deve ter algo lá.

tambem verifique seu console JS, para ver se foi algum erro do Javascript

**Comment by gabrielmais** [comment]
![image](https://user-images.githubusercontent.com/7960434/88422410-98407f00-cdc0-11ea-9086-68c5d772aaaf.png)
Aqui esta dando erro nos pluginsAvailable

**Comment by DanielnetoDotCom** [comment]
Vc não mostrou o tipo de erro no console JS nem compartilhou o avideo.log
