### ISSUE TITLE
bug API chat2

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3438]
I do tests when I want to send a message in the chat it does not work

there is the same problem on the demo.avideo site

![image](https://user-images.githubusercontent.com/39193219/88447964-1b052080-ce39-11ea-94cb-c5b15efa7299.png)

**Comment by jyrihovila** [comment]
@syldri are you sure you're using the latest version of the Chat2 plugin?

I had a similar issue and it was fixed simply by installing the latest version of the plugin.

**Comment by syldri** [comment]
Hello @jyrihovila   I have the last version, before before I post a message I look on the demo.avideo site if there is the same problem, and the photo I posted is on the demo.avideo site, so the problem is not only on my site.

**Comment by DanielnetoDotCom** [comment]
Can you please screenshot on the demo site where exactly you did the bug?

**Comment by syldri** [comment]
hello @DanielnetoDotCom   in the administration when I go to chat2 and click on API

it's when i want
Send a public message to the channel or privately

![image](https://user-images.githubusercontent.com/39193219/88457408-5aa62980-ce86-11ea-922e-6acf8955a131.png)

**Comment by DanielnetoDotCom** [comment]
`error: false` means there is no error

**Comment by syldri** [comment]
I do tests and it works, when I did it didn't work yesterday 

thank you for the answer @DanielnetoDotCom
