### ISSUE TITLE
Site error 500 after update from 8.8 to 9.2 with git pull

### ISSUE THREAD

**Issue by br0kenlink** [WWBN/AVideo#3439]
Hi,
I did git pull update and site won't load anymore it seems.

> [25-Jul-2020 08:08:13 Europe/London] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'YouPHPTube.extraConfig' doesn't exist<br>
SELECT * FROM extraConfig WHERE  id = ? LIMIT 1
[25-Jul-2020 08:08:13 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreatefrompng() in /var/www/YouPHPTube/objects/functions.php:1459
Stack trace:
#0 /var/www/YouPHPTube/objects/functions.php(2464): convertImage('/var/www/YouPHP...', '/var/www/YouPHP...', 100)
#1 /var/www/YouPHPTube/objects/configuration.php(251): convertImageToOG('/var/www/YouPHP...', '/var/www/YouPHP...')
#2 /var/www/YouPHPTube/objects/functions.php(2488): Configuration::getOGImage()
#3 /var/www/YouPHPTube/view/include/head.php(158): ogSite()
#4 /var/www/YouPHPTube/plugin/YouPHPFlix2/view/modeFlix.php(22): include('/var/www/YouPHP...')
#5 /var/www/YouPHPTube/view/index.php(27): require('/var/www/YouPHP...')
#6 {main}
  thrown in /var/www/YouPHPTube/objects/functions.php on line 1459 <

I tried to change version in mysql but it dont seem to be working.
Help, please

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform
Follow the steps ,
Did you updated from the site ? If not , you may have to update it manually

**Comment by br0kenlink** [comment]
I did follow these, steps, maybe except manual update of files, git pull seemed to update successfully. I actually used it before to update and it worked fine.
Should I try manual install?

**Comment by akhilleusuggo** [comment]
You skipped many updates , that's why probably you're getting 500 error ( internal error )

**Comment by br0kenlink** [comment]
Well, I found files i used for update in May, unpacked it, site started working right after. Went to the update page and funny enough, it actually shown me UPDATE button, before it was just saying versions.
Anywho, all works and no more errors :)
Will close this now :)
