### ISSUE TITLE
broken website error https 500

### ISSUE THREAD

**Issue by daoguey** [WWBN/AVideo#3440]
Just updated website with Git pull and now i cannot access it.

website has SSL and HSTS enabled. 

version updated from 9.1 to git pull i suspect 9.2.

What logs you guys need?

**Comment by akhilleusuggo** [comment]
probably the apache2 once in this case /var/log/apache2/error.log

**Comment by jyrihovila** [comment]
> Just updated website with Git pull and now i cannot access it.
> 
> website has SSL and HSTS enabled.
> 
> version updated from 9.1 to git pull i suspect 9.2.
> 
> What logs you guys need?

Do you run PHP-FPM?

If you do, there's a problem with 9.2 that makes it incompatible with PHP-FPM.

I experienced the same issue just couple of days ago and was forced to move back to using mod_php instead of PHP-FPM.

This issue noes need a real solution since mod_php has very poor performance compared to PHP-FPM, but until the fix is published, you can use mod_php as a temporary solution.

**Comment by daoguey** [comment]
[error.log](https://github.com/WWBN/AVideo/files/4977854/error.log)
There you go but my other website live.qerotv.com is working fine in the latest version so i wonder if my SSL is currently the issue.

thank you.

**Comment by jyrihovila** [comment]
> [error.log](https://github.com/WWBN/AVideo/files/4977854/error.log)
> There you go but my other website live.qerotv.com is working fine in the latest version so i wonder if my SSL is currently the issue.
> 
> thank you.

SSL/TLS should not cause error 500 problems. I'll check your log for further clues, just a moment. Apache error log would also be useful.

**Comment by daoguey** [comment]
I have PHP-fpm enabled yes.
![image](https://user-images.githubusercontent.com/15695109/88483854-db693200-cf27-11ea-916d-352fe4670e47.png)

there you go.

**Comment by daoguey** [comment]
> Hi
> 
> I guess one of those lines is breaking your code.
> 
> try to comment them and let me know
> 
> https://github.com/WWBN/AVideo/blob/91abad67cf55479205d9ce2d99895e8f12f0c774/objects/functions.php#L2283
> 
> 
> https://github.com/WWBN/AVideo/blob/91abad67cf55479205d9ce2d99895e8f12f0c774/objects/functions.php#L2284

When I change those two i can access my website over IP not Domain, so i wonder if the initial configuration of the website broke my files that were modified by Git pull overwrite my config files.

I will leave this not commented in the mean time. 

After running over your error you got mine did not had the same @jyrihovila  so i am going to look at the config files and check my website if it has lost the initial config.

if you guys can provide me with the locations of this and manually change the setting would be much appreciated.

thank you.

**Comment by daoguey** [comment]
Restored version 9.1 back. Please fix 9.2 broken path http error 500 when doing git pull.

Will leave version 9.1 as my main website till we get an update on why it breaks at 9.2.

Thank you

**Comment by jyrihovila** [comment]
> Restored version 9.1 back. Please fix 9.2 broken path http error 500 when doing git pull.
> 
> Will leave version 9.1 as my main website till we get an update on why it breaks at 9.2.
> 
> Thank you

Good that you got it working for now. The issue really must be fixed though. I hope @DanielnetoDotCom has the time to handle it for 9.3. It would help a lot if we can provide him with more specific debug information, though.

**Comment by DanielnetoDotCom** [comment]
Anyway, you guys can give me any clue what may be the problem?

I do not have any PHP FPM to test it.

also, can you guys describe what exactly is your OS, web server and PHP Version?

**Comment by daoguey** [comment]
Os: ubuntu 20.04
Php: php7.3-fpm
Web server: apache 2.4.39 i think

**Comment by jyrihovila** [comment]
> Anyway, you guys can give me any clue what may be the problem?
> 
> I do not have any PHP FPM to test it.
> 
> also, can you guys describe what exactly is your OS, web server and PHP Version?

All the info I could find from my logs is in this ticket: https://github.com/WWBN/AVideo/issues/3440#issuecomment-664401712

Unfortunately the logs do not specify which index.php and which line is causing the problem.

**Comment by jyrihovila** [comment]
> Os: ubuntu 20.04
> Php: php7.3-fpm
> Web server: apache 2.4.39 i think
> 
> When updating to 9.2 from 9.1 over git pull we get http error 500. Ssl and apache web server configuration still the same.
> Letsencrypte config works fine and shows all configuration working.

Yes, the changes between 9.1 and 9.2 brought in something that causes php-fpm not to be able to digest the code.

9.1 was working just fine with exactly the same server configuration.

**Comment by TLCReuver** [comment]
I can't update using git pull with the same http error 500.

Using:
Ubuntu 18.04
Apache/2.4.29 (Ubuntu)
Php: php7.3-fpm

I have to stay on older version and waiting for a fix.

**Comment by DanielnetoDotCom** [comment]
This should work now with the latest push

**Comment by TLCReuver** [comment]
Yipz, problem fixed here. Th@nkz

**Comment by jyrihovila** [comment]
Same here, problem fixed! Great work, @DanielnetoDotCom! <3

**Comment by jyrihovila** [comment]
@daoguey please update to the latest version and if it solves the issue, report here and mark this thread closed. :)

**Comment by daoguey** [comment]
Tested and working 9.2 version is working now.

thank you @DanielnetoDotCom
