### ISSUE TITLE
Encoder won't go past this stage

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3442]
Whenever I, or a client, tries to upload a video, this happens. The encoder stays here adn doesn't move.

I click upload
I get to encoder
I select file
I give it a title or description (sometimes not)
I say extract webm (sometimes not)
I click start upload
File uploads properly
Then gets stuck here.

![encol](https://user-images.githubusercontent.com/65451390/88635822-d1c70200-d0c0-11ea-9a74-7b11dcc9b519.png)

What is the problem? I have not made any back end changes to any files.

Error log under videos directory says nothing.

Thanks.

**Comment by akhilleusuggo** [comment]
check Queue Log , what is the status

**Comment by jengajenga** [comment]
> check Queue Log , what is the status
> PS , you hided the icon, and url , but you forgot the mail browser url xD

haha i failed! my brain must be tired. 

anyway, queue log says this

![queue_log](https://user-images.githubusercontent.com/65451390/88591685-66037b80-d065-11ea-9728-ab061d033c17.png)

still no movement

**Comment by jyrihovila** [comment]
Hi!

Please check the text log file in the video folder of your YouPHPTube Encoder. By default, it's named avideo.log.

**Comment by jengajenga** [comment]
> Hi!
> 
> Please check the text log file in the video folder of your YouPHPTube Encoder. By default, it's named avideo.log.

hi thanks. however the log doesn't say anything about the encoder.

when I try to import, this is what i get.

![import](https://user-images.githubusercontent.com/65451390/88635263-2027d100-d0c0-11ea-8ac6-235272581751.png)

when i do the update instructions, this is what i get

![import2](https://user-images.githubusercontent.com/65451390/88635341-3afa4580-d0c0-11ea-9dfe-745ad4cc62b4.PNG)


@DanielnetoDotCom @akhilleusuggo  

thanks

**Comment by jengajenga** [comment]
still cannot import.

**Comment by akhilleusuggo** [comment]
I think you're checking the wrong logs . Do not check the streamer log , but the encoder logs .
In case you're trying to import a YouTube Channel , then this will not work . In any case , the errors should be located on /`var/www/html/AVideo-Encoder/videos/avideo.log` ( by default )

**Comment by jengajenga** [comment]
> I think you're checking the wrong logs . Do not check the streamer log , but the encoder logs .
> In case you're trying to import a YouTube Channel , then this will not work . In any case , the errors should be located on `/var/www/html/AVideo-Encoder/videos/avideo.log` ( by default )

thank you. i have seen the problem and fixed it.

during a security exercise, i had disabled some php functions in the .ini file. exec() was among them. after enabling it, it has worked. i am now closing this.

thank you for your assistance. i am grateful.
