### ISSUE TITLE
Change font size and family of footer links

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3444]
Good Day,

I have few links in my footer for which i want increase the font,
I have gone to customize plugin and tried changing the custom CSS setting ,but the footer font doesnt change,Also i went to the footer box-and have included the hyperlink html tag ,for which when i edit the html code,its not taking the custom style i want to add.
Please help .
I want font size 13 and font-family-helvetica for the link in the footer.

Website-www.seafarerstube.com

**Comment by DanielnetoDotCom** [comment]
Will be easier if you share what CSS are you using

**Comment by vraghavans** [comment]
Dear Daniel,
Thanks for your reply,

PLease find below the CSS

<style type="text/css">

        
h3   {color: DodgerBlue;margin: 25px;font-family: Helvetica, Verdana, Arial;font-size: 21px;}
h2   {color: DodgerBlue;margin: 25px;font-family: Helvetica, Verdana, Arial;font-size: 36px;}
p    {margin: 40px;font-family: Helvetica, Verdana, Arial;font-size: 13px;}

    </style>

**Comment by DanielnetoDotCom** [comment]
It really depends on how you set it up, but try to use like this ...
```

<style type="text/css"> h3 {color: DodgerBlue;margin: 25px;font-family: Helvetica, Verdana, Arial;font-size: 21px;} h2 {color: DodgerBlue;margin: 25px;font-family: Helvetica, Verdana, Arial;font-size: 36px;} footer, footer li, footer btn
, footer p {margin: 40px;font-family: Helvetica, Verdana, Arial;font-size: 13px;} </style>
```

**Comment by vraghavans** [comment]
Dear Daniel,
Actually i tried but the CSS style is not accepted in the footer when i try to insert the code.
Even if i can use the controls in the footer customize box,that will do,which am not as the screen freezes.Please find the video of the error-asks me to add link and then blacksout.

https://youtu.be/W7xwUkLg3PQ -url of the video for the error

**Comment by DanielnetoDotCom** [comment]
Hi, 

When I sent you the CSS, I mean you to use it on the head code section 

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css

![image](https://user-images.githubusercontent.com/18009293/89188481-1a753400-d575-11ea-8113-096a11e83489.png)

**Comment by vraghavans** [comment]
oops got it ,Daniel,

Thanks for helping me with the titbits.I know these would be time wasters for you.
Appreciate!

Rgds
Vijay
