### ISSUE TITLE
LiveUsers plugin : live counter and views counter  are blocked to 0

### ISSUE THREAD

**Issue by olivierDM40** [WWBN/AVideo#3446]
Hi, i have a problem with the LiveUser plugin installation. 
Before installing plugin, i have upgraded the Avideo to latest release 8.9.1
The installation of the new version and plugin was OK, installation of tables were ok and activation of the plugin was ok.
Live stream works fine, counter are displayed on the left top of the video windows, but stay blocked to 0

I have a error in avideo.log file, /tmpxxxxxxx : Permission Denied with the class Objects/function.php line 3404 

Maybe just a permission missing but all my folders are in 777 mode. 
My installation is on VMWare, based on a Redhat 7 os

Thank you for your help 
Olivier

**Comment by jyrihovila** [comment]
> Before installing plugin, i have upgraded the Avideo to latest release 8.9.1

The latest release is 9.2. Please make sure you have the latest version of both AVideo and the plugins.

**Comment by olivierDM40** [comment]
Hi, 
  The only release i saw for downloding is the 8.9.1 (https://github.com/WWBN/AVideo/releases/tag/8.9.1) that is tagged "latest".
  After installing this release, the footer of me Avideo installation is marked as 9.1  ? 

Thank you

**Comment by olivierDM40** [comment]
![YouPHPRelease](https://user-images.githubusercontent.com/68920351/88768051-c89a6b80-d17a-11ea-9f61-bdbf231563a7.jpg)

**Comment by olivierDM40** [comment]
Exact error log extract  ==> many many Warning of this type in the log file 
[29-Jul-2020 07:04:39 UTC] PHP Warning:  file_put_contents(/tmp5f211f87626d4): failed to open stream: Permission denied in /var/www/html/YouPHPTube/objects/functions.php on line 3404

**Comment by DanielnetoDotCom** [comment]
@olivierDM40 please use the Master branch from GitHub, not the releases

![image](https://user-images.githubusercontent.com/18009293/88925434-e9ca8d00-d24a-11ea-8f50-51223310ab80.png)

**Comment by olivierDM40** [comment]
Thank you, i will do this upgrade and check it when i will go back from my summer hollidays that start today.
You can freeze or close the issue, i will re-open it (or a create new one) if the problem is still here after this upgrade  done end of august
Thanks

**Comment by jyrihovila** [comment]
> Thank you, i will do this upgrade and check it when i will go back from my summer hollidays that start today.
> You can freeze or close the issue, i will re-open it (or a create new one) if the problem is still here after this upgrade done end of august
> Thanks

It would be great if you could report back to this thread when you know the results. It will make it easier for others with the same problem to find the solution. Happy holidays!
