### ISSUE TITLE
NGINX RTMP

### ISSUE THREAD

**Issue by daoguey** [WWBN/AVideo#3447]
Mentioning this Ticket  #3384 

I still have issues when I Open Live streaming

when using:  tail -n 200 -f /usr/local/nginx/logs/error.log
i get this: 
![image](https://user-images.githubusercontent.com/15695109/88748791-23967900-d10f-11ea-91c8-368611e19730.png)

Kind of odd even if i changed the HLS\Live to 777 (don't worry i reverted this back to 755)
My OBS system connects to it no problem but now it seems that i cannot even show some video in the screen after I made some changes to nginx.conf to enable adaptative. 
[nginx (2).txt](https://github.com/WWBN/AVideo/files/4992104/nginx.2.txt)

I of course did follow this: https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

Console from Edge: 
![image](https://user-images.githubusercontent.com/15695109/88749444-88060800-d110-11ea-853a-e8316ce408a6.png)

I am out of ideas after looking throught all the logs and systems.

AJAX logs:
![image](https://user-images.githubusercontent.com/15695109/88749686-1084a880-d111-11ea-8c31-8095627b0ab6.png)

**Comment by akhilleusuggo** [comment]
your configuration is wrong .
The output should be `/HLS/live/yourIDstream/index.m3u8` not `/HLS/live/yourIDstream.m3u8`

**Comment by akhilleusuggo** [comment]
1- Under application live ( the first app )
```
allow play all;
live on;
```

2- On adaptive application should work : 

`hls_nested on;` should do the work .

**Comment by jyrihovila** [comment]
@daoguey can you please confirm if the solution above by @akhilleusuggo worked for you. :)

**Comment by daoguey** [comment]
Will do whwn i get home i am in mdt time in utah.

**Comment by daoguey** [comment]
Can any of you point me where this change has to be made?

**Comment by daoguey** [comment]
can any of you send me their config so i can compare? now i just need to show in my test box and to be able to put it in online. Still cannot save.

**Comment by daoguey** [comment]
this is the config:

 worker_processes  1;

    error_log  logs/error.log debug;

    events {
            worker_connections  1024;
    }

    rtmp {
            server {
                    listen 1935;
                    chunk_size 4000;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                        allow play all;
                        live on;
                        on_publish http://live.qerotv.com/avideo/plugin/Live/on_publish.php;
                        on_play http://live.qerotv.com/avideo/plugin/Live/on_play.php;
                        on_record_done http://live.qerotv.com/avideo/plugin/Live/on_record_done.php;
                        
                       recorder video{
                          record all;
                          record_path /var/www/tmp;
                          record_notify on;
                          record_max_size 2048M; 
                          #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
                          record_suffix -%d-%b-%y-%T.flv;
                        }

                        exec ffmpeg -i rtmp://live.qerotv.com/live/$name 
                            -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:240 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1200k -b:a 96k -r 20 -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_low  
                            -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:480 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 2400k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_mid  
                            -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:720 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 4200k -bufsize 100000k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi;
                    }

                    application adaptive {
                        live on; 
                        hls on; 

                        hls_path /HLS/live;
                        hls_nested on;

                        allow play all;
                        allow publish 127.0.0.1;
                        deny publish all;

                        hls_variant _low BANDWIDTH=400000;
                        hls_variant _mid BANDWIDTH=2100000;
                        hls_variant _hi  BANDWIDTH=4200000;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    listen 444 ssl;
                    server_name live.qerotv.com;
                    ssl_certificate /etc/letsencrypt/live/live.qerotv.com/fullchain.pem;
                    ssl_certificate_key /etc/letsencrypt/live/live.qerotv.com/privkey.pem;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   
            }
    }

now this is the error I get:
![image](https://user-images.githubusercontent.com/15695109/88877845-b7d21000-d1e3-11ea-83fd-966e16affd7c.png)

**Comment by akhilleusuggo** [comment]
Can you share your plugin config ?

**Comment by daoguey** [comment]
I can't this time. But can i get an idea of what plugins are needed for this to work properly.

**Comment by akhilleusuggo** [comment]
not plugins ... Only Live Plugin , need screen of it's options .

**Comment by daoguey** [comment]
I am not sure what this will solve. But there it is: 
![image](https://user-images.githubusercontent.com/15695109/89093322-9b1a1180-d376-11ea-96be-e43a03988da9.png)

OK after installing it 8 times now and following to the line all the settings and KBs you guys put I am out of words to describe my frustration. 

An option is creating a script that would do this for you, install the different parts of the file, including nginx and hls plugin and send to encoder.

Can any of you provide me with their working file? and tell me what they followed so i can check an replicate this?

As you see from my config file I had one mistake in my config but still not working, why? and i keep scratching my head and recreating my VMs.

can any of you provide a step by step for live, send to recorder, and hls/adaptative?

Now even with your change @akhilleusuggo  this still shows:
![image](https://user-images.githubusercontent.com/15695109/89093521-7aeb5200-d378-11ea-8144-492c0bae62f5.png)


I include another image of something that seems odd because it shows without the streaming ID:
![image](https://user-images.githubusercontent.com/15695109/89093464-eed92a80-d377-11ea-82db-d98a37fa7a76.png)


I also made a change in my config to match the RTMP location:
![image](https://user-images.githubusercontent.com/15695109/89093490-3c559780-d378-11ea-81b0-a81aedf9ffd6.png)

all 4 have the URL as i am not going with localhost.
UFW is disabled at this point so all ports are open.

this is again the Nginx file: 
[nginx-with HLS.txt](https://github.com/WWBN/AVideo/files/5009809/nginx-with.HLS.txt)

**Comment by akhilleusuggo** [comment]
Before we proceed . When you start live , can you open the terminal and CONFIRM that ffmpeg is working ?
I think that's your issue .

**Comment by daoguey** [comment]
sorry for the delay there it is:
![image](https://user-images.githubusercontent.com/15695109/89357237-2a783b00-d67d-11ea-9aea-93328737fea6.png)
and this is what appears now:
![image](https://user-images.githubusercontent.com/15695109/89357305-5398cb80-d67d-11ea-8663-cd14eda1ce32.png)


We are making progress now it is the error again with the index.m3u8 that is broken again.

but now it shows Online and changes. 

what else I am missing in this setup?

**Comment by akhilleusuggo** [comment]
The issue is your ffmpeg definitely 

PS : I found the issue . You did not follow up with the guide very well . On your nginx config , you should not change the local host , or it will not find it . Here is the issue : 

`exec ffmpeg -i` **rtmp://live.qerotv.com/live/$name** 
                  
`-c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:240 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1200k -b:a 96k -r 20 -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_low  
                        -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:480 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 2400k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_mid  
                        -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:720 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 4200k -bufsize 100000k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi;
                }`

Replace **rtmp://live.qerotv.com/live/$name** with `rtmp://localhost/live/$name`

If you look at your FFMPEG lines , all of them ends with `rtmp://localhost/adaptive/$name_hi` , `rtmp://localhost/adaptive/$name_mid` , `rtmp://localhost/adaptive/$name_low` . This is to point basically to the /HLS/ location .

What you're trying to do requires extra code , and is used more on APIs , not for this case .

Now it should work properly .

restart nginx afterward .

**Comment by daoguey** [comment]
OK, after so many issues, and after so many attempts this is finally working fine. 

for all of you that are having the same issue make sure all your configs are setup properly I will attach what i have so you can reuse it again: 
[nginx.txt](https://github.com/WWBN/AVideo/files/5025538/nginx.txt)

This will require SSL setup, sendtoencoder, videoHLS and Live plugins.

Will be closing now as all is working. thank you for all your help.

**Comment by akhilleusuggo** [comment]
@daoguey I assure you that the wiki has been updated a month ago with the perfect config . Take a look here .
https://www.youphptube.com/docs/nginx.conf  ( this is the config )

https://github.com/WWBN/AVideo/wiki/Live-Plugin#nginx-only-installation
