### ISSUE TITLE
marketplace

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3448]
Add notification of updates/modifications to the market place . Something like this : 

![image](https://user-images.githubusercontent.com/52116577/88808562-bb51a100-d1bb-11ea-8f19-45e973cd3105.png)

**Comment by DanielnetoDotCom** [comment]
I am thinking to notify the plugins in your site plugins page, I will release in the future a tool that compares your plugin with the ones we have on the site.
