### ISSUE TITLE
Record a video on a remote server

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3449]
I remember before were deleting the file from the NGINX server . Now it does not delete the file after has been sent to encoder .

**Comment by DanielnetoDotCom** [comment]
It may happen due to a permission problem.

are you using a separated live server?

**Comment by akhilleusuggo** [comment]
Yes , separated .

**Comment by DanielnetoDotCom** [comment]
I see, 

Please make sure you uncomment this line
https://github.com/WWBN/AVideo/blob/9cb75d99a49e8b908e739f0487a35242988f3188/plugin/Live/getRecordedFile.php#L39

or you can add the crontab so to auto-delete files older than 7 days, and make sure all the videos were processed and do not lose them in case of an error.

`@daily root find /var/www/tmp/*.flv -mtime +6 -type f -delete`

**Comment by akhilleusuggo** [comment]
On my Nginx server need instan delete , because it's a server with 100gb NVME ( 2100mb/s ) , 1gb network .
So if I wait 7 days , this will be already full ..

I'll uncomment the line and let you know .  ( also comment the description function for php with `//` [ I'm not that noob xD ]  )

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom The fix does work perfectly ! BUT when it's transferred to the streamer site , the files stuck at /videos 

![image](https://user-images.githubusercontent.com/52116577/89324899-ac259400-d690-11ea-8596-0d275ebfd3dc.png)

**Comment by akhilleusuggo** [comment]
Ok , I think it's stuck until the video is received back to the streamer site .

**Comment by DanielnetoDotCom** [comment]
Hi

I do not get it, is it a problem or you already figure it out?

**Comment by akhilleusuggo** [comment]
Yes , the original file got deleted after the streamer is uploaded back from encoder . 
I just don't understand why they don't follow the same structure file names like the rest of the files . 
File names are basically the same name as the titles ... But the issue is FIXED
