### ISSUE TITLE
LiveUsers 

### ISSUE THREAD

**Issue by ricasht** [WWBN/AVideo#3451]
I bought the plugin. when active it live is offline and disappears from the live list ...

**Comment by DanielnetoDotCom** [comment]
Please share your log file and also some screenshots.

Also please make sure you are running the latest version

**Comment by ricasht** [comment]
Ok, my verson is 8.9
which log do you need?

**Comment by akhilleusuggo** [comment]
we're at 9.2

**Comment by ricasht** [comment]
what is the process to update?

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by akhilleusuggo** [comment]
after updating , redownload the plugin and upload it .

**Comment by ricasht** [comment]
I have this error after procedures
malformed header from script 'index.php': Bad header: Access-Control-Allow-Methods

**Comment by DanielnetoDotCom** [comment]
@ricasht try to update your site code, I just sent an update for php-fpm servers

**Comment by ricasht** [comment]
obrigado, tudo funcionou.
