### ISSUE TITLE
Ad Server not showing showing clips

### ISSUE THREAD

**Issue by chuynh812** [WWBN/AVideo#3452]
Followed Ad Server instructions and after setting up campaign with added video clip.  I see the Yellow marker but the ad is not playing at the beginning of the video clip.  Also, is there a way to designate which videos ads are shown on?

**Comment by DanielnetoDotCom** [comment]
Yes.

First, make sure you are using MP4 videos on your ads campaigns.

please share some links so I can check how it looks like and how are the VMAP/VAST links

also please share some screenshots from your ADs editor

**Comment by chuynh812** [comment]
Yup - I wasn't using MP4s for the Ad Videos - that is working now Thx!  How do I select which videos ads should play on?

**Comment by DanielnetoDotCom** [comment]
Right now you cannot choose what video will play ads, this configuration is site-wide, but you can select videos to NOT play ads with PPV and Subscription plugins.

That is what you can do 

https://github.com/WWBN/AVideo/wiki/PayPerView-Plugin#allowfreeplaywithads

and you can do the same with subscriptions

![image](https://user-images.githubusercontent.com/18009293/89311363-444d5a00-d64c-11ea-9aa6-620f63d618b6.png)

**Comment by chuynh812** [comment]
Sounds good - I'll work it that way. Thx.
