### ISSUE TITLE
CAPTCHA not showing

### ISSUE THREAD

**Issue by dbmasters** [WWBN/AVideo#3453]
We did a more manual install of the system, setting directory permissions, running the sql script, etc, since the automated install was being flakey...seems to work, but the CAPTCHA login image isn't showing up and the admin login does work.

Planned to just reset the admin password, but I need captcha to do so...is there any quick work around to turn that off or other way to reset admin password?

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by DanielnetoDotCom** [comment]
Just a guess, usually when this happens, is because you are missing the php-gd lib

**Comment by dbmasters** [comment]
Ahhhhh, good call. We are doing a ground up build in Google Cloud, we have been slowly going thru all necessary libraries, I'll have to ask devops if he put that in...thanks, that would totally make sense.
