### ISSUE TITLE
updated site to 9.2 and all the pages have zoomed and become big!!

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3457]
![image](https://user-images.githubusercontent.com/65802024/89125225-88304a00-d4fa-11ea-8e2a-44cd551d59c8.png)
please advise

**Comment by vraghavans** [comment]
just changed the theme and it got corrected,

**Comment by vraghavans** [comment]
There is an issue with the default theme,other theme are good

**Comment by akhilleusuggo** [comment]
same issue here

**Comment by DanielnetoDotCom** [comment]
Not sure, on the demo is fine, can you guys provide some link so I can check?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom https://demo.avideo.com/channel/TheAdminChannel

Look at your page ... The CSS it's just wide ... Was not like this before . Now has no borders practically 

![image](https://user-images.githubusercontent.com/52116577/89189446-a5bbed00-d5a8-11ea-8f1a-507dbbf546db.png)

**Comment by DanielnetoDotCom** [comment]
that is the new look of the channel (you can disable the channel home on the customizeUser)

that is how I see the page 

![image](https://user-images.githubusercontent.com/18009293/89189922-14805280-d577-11ea-9671-bbaf82838ebd.png)

**Comment by akhilleusuggo** [comment]
I think you don't understand what I mean . I'm not talking about the HOME feature ( from netflix )
I'm talking about the CSS structure . I'm gonna compare with google so you could understand me .

![image](https://user-images.githubusercontent.com/52116577/89190718-84f49700-d5aa-11ea-867f-4860a7e3d0f4.png)

Right now we have like the page on our faces ...

**Comment by DanielnetoDotCom** [comment]
do you mean, you want the page with the lateral spaces?

I guess if you upload an image smaller then the recommended, it will display an old-style page, with the lateral spaces

**Comment by akhilleusuggo** [comment]
I see ... so the issue here is the poster size . Then we need to add a resize for the poster ( like thumbnails ) .
![image](https://user-images.githubusercontent.com/52116577/89213119-44f2db80-d5cd-11ea-8eab-823fc5038bfd.png)

Small poster does work as should .

**Comment by vraghavans** [comment]
Hi,could you please put it in words ,a simple person like me can understand?

What shd i do to get it back to the page like before please
rgds
vijay

**Comment by DanielnetoDotCom** [comment]
@vraghavans based on your screenshot, I think your problem is something else.

There is no reason from the code to this happen.

The reason may be something specific in your side:

1. For me looks like you zoom tour page, try to press crtl+0 in your browser, so see if it will back to the normal size
2. If you include any custom CSS in the head code, try to remove it, clear the cache and check the results.
