### ISSUE TITLE
Remove the select row counts in Video manager and other places that allows it

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3459]
I am trying to make page loads use the least amount of get requests per page load before the folds.

Allowing users to be able to select in their video manager how many videos per page needs to have a option for admins to disable.

Some users select all not caring how many videos they have and this really stresses the server and also triggers my firewall security thinking it is a DoS attack because of thousands of get requests in just a few seconds from a single IP.

**Comment by akhilleusuggo** [comment]
I've asked the same thing before , and also about the tags . Daniel say it's hard to do ... :( 
https://github.com/WWBN/AVideo/issues/3287

**Comment by akhilleusuggo** [comment]
And the worst thing about this , if a user have for example 500 videos , and start loading all , even closing the windows wont kill the proccess . If multiple does this at the same time , or opens the same thing on multiple tabs = R.I.P

**Comment by JoshWho** [comment]
It is a vulnerability to the CPU and should be addressed. I was doing some test with it and yeah when the user selects all videos to view you better have a big dedicated server and even that will spike to 100% load until the page loads.

My security bans users doing that but it sucks explaining to them why they got banned and then they say, "Then why is it a option to view it like that?"

**Comment by akhilleusuggo** [comment]
Agree . Should be 10/20/30/40

Just in case in the future we will have a bulk description change / title etc ...  Displaying all the videos on small server could crash it with 2-3 windows open .

**Comment by JoshWho** [comment]
I'm totally fine with disabling the selector completely. 10 vids per page is fine. There is no need to load more than that in the video manager.

**Comment by JoshWho** [comment]
People clicking the refresh button repeatedly also is not good but I see people doing it all the time waiting for their video to upload.

The refresh tool needs a weight feature in it to only be clicked once every so many seconds or minutes.

**Comment by akhilleusuggo** [comment]
or a delay of 15s

**Comment by DanielnetoDotCom** [comment]
Hi

What exactly page is that? the manageVideos?

**Comment by JoshWho** [comment]
Yes the video manager.

**Comment by DanielnetoDotCom** [comment]
I just sent this commit 

https://github.com/WWBN/AVideo/commit/a5b4afd66761417129dc7b775a0581f127eb5797


Add rowCount option on the customize advanced for the video manager

The value must be an Array of Integer which will be shown in the dropdown box to choose the row count. Default value is [10, 25, 50, -1]. -1 means all. When passing an Integer value the dropdown box will disappear.

**Comment by JoshWho** [comment]
Sweet. I will run the update now. Thank you

**Comment by DanielnetoDotCom** [comment]
I just sent you a fix for the videos not showing

**Comment by JoshWho** [comment]
k Running it now

**Comment by JoshWho** [comment]
Success. WOrks great. Thank you so much Daniel.
