### ISSUE TITLE
the home page of Youphptube is blank

### ISSUE THREAD

**Issue by yasiriqbal1** [WWBN/AVideo#3461]
After executing sudo rm /var/www/YouPHPTube/upload/install/ -r
the home page is blank

Am is missing smething.
server: ubuntu 18.04LTS
web server: apache

**Comment by jyrihovila** [comment]
We need more details in order to be able to help, particularly the error log from Apache and the YouPHPTube log (videos/avideo.log).

**Comment by yasiriqbal1** [comment]
Thanks the issue has been resolved through log file avideo.log
