### ISSUE TITLE
Update Disk Usage

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3462]
This feature is stuck at 1000 videos . If the platform does have more then 1000 videos , only the first 1000 will be updated , the rest wont

```
php updateDiskUsage.php 
...................
..................
994/2555 (success) [1110] *******
995/2555 (success) [1111]  *******
996/2555 (success) [1112]  *******
997/2555 (success) [1113]  *******
998/2555 (success) [1114]  *******
999/2555 (success) [1115]  *******
1000/2555 (success) [1116]  *******
```

**Comment by DanielnetoDotCom** [comment]
What exactly feature are you talking about?

the command line?

**Comment by akhilleusuggo** [comment]
Both the command line and the button ( for admin to update disk usage ) , get stuck at 1000 videos . I can't find where you have put the limit .

**Comment by DanielnetoDotCom** [comment]
Now you can setup $global['rowCount'] in your configuration.php file;
it may increase your max rows, for example

`$global['rowCount'] = 10000;`

your max rows will be 10k rows

**Comment by akhilleusuggo** [comment]
Thank you , i'm updating and let you know if it works . The issue Daniel , is that you HAVE TO create a wiki page with all this hidden `$global['whatever'] = whatever;`

This issue , https://github.com/WWBN/AVideo/issues/3456 , was fixed with one of this ''hidden'' parameters , but I'm not able to find it .

**Comment by DanielnetoDotCom** [comment]
The $global['rowCount'] = 10000; I just created based on your issue :)

but definitely I have to add it to the wiki.

**Comment by akhilleusuggo** [comment]
We need to add all this options . And yes you created another one for the issue ERR_RESPONSE_HEADERS_TOO_BIG , and now it's ''lost'' 

I'll do it .

Regarding this issue is not fixed ... 

```
997/2555 (success) [1113]  *******
998/2555 (success) [1114]  *******
999/2555 (success) [1115]  *******
1000/2555 (success) [1116]  *******
```

![image](https://user-images.githubusercontent.com/52116577/89212630-7323eb80-d5cc-11ea-9e14-048da7e0dcfa.png)

**Comment by jyrihovila** [comment]
> We need to add all this options . And yes you created another one for the issue ERR_RESPONSE_HEADERS_TOO_BIG , and now it's ''lost''
> 
> I'll do it .
> 
> Regarding this issue is not fixed ...
> 
> ```
> 997/2555 (success) [1113]  *******
> 998/2555 (success) [1114]  *******
> 999/2555 (success) [1115]  *******
> 1000/2555 (success) [1116]  *******
> ```
> 
> ![image](https://user-images.githubusercontent.com/52116577/89212630-7323eb80-d5cc-11ea-9e14-048da7e0dcfa.png)
> 
> ![image](https://user-images.githubusercontent.com/52116577/89212690-951d6e00-d5cc-11ea-8178-0193534fbe83.png)

I agree: getting the documentation up to date is very important. I think this is something where us the community must lend a hand, since @DanielnetoDotCom has more than enough work in maintaining and developing the code.

**Comment by DanielnetoDotCom** [comment]
OMG, I just found another hidden variable

https://github.com/WWBN/AVideo/blob/9461d1e8d5e47eb56b6231a47449f918bee50279/objects/video.php#L1057

It is specific for videos 

`$global['limitForUnlimitedVideos'] = 10000;`

**Comment by DanielnetoDotCom** [comment]
I just sent an update that will use the `$global['rowCount'] `mentioned above in case `$global['limitForUnlimitedVideos']` does not exists

**Comment by akhilleusuggo** [comment]
WORKS ! 

I though this would fix my old issue , but still no luck 
![image](https://user-images.githubusercontent.com/52116577/89326357-d11b0680-d692-11ea-8222-149dab5d8b74.png)
