### ISSUE TITLE
Option to edit the view row count on the video watch page to reduce the get requests

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3464]
just like the option in the video manager you just recently added need one for the video view page as well.

<img src="https://static.buddylist.co/vidmod.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
Try now

**Comment by DanielnetoDotCom** [comment]
You should have the option videosListRowCount on customizeAdvanced plugin

**Comment by JoshWho** [comment]
Works great. Thank you @DanielnetoDotCom
