### ISSUE TITLE
Cannot import videos from YouTube even though I updated youtube.dll

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#3465]
For about a week now nobody can share videos from YouTube. I have updated the server. Rebooted the server. Installed upgrades. Removed and installed youtube.dll and updated it repeatedly. Yet it will still not work.

When I enter a YouTube url in the encoder site and click "share" a popup window shows up saying "we could not get the title of your video" and gives me a link to github. I followed the instructions there many times along with server reboots but keep getting the same error.

Sharing videos from other sites works fine though.

**Comment by The-Do-It-Yourself-World** [comment]
![DIY Tube Uploader Error](https://user-images.githubusercontent.com/45924889/89232645-dd7d6180-d5b5-11ea-8b2d-ffb0ca96c01c.jpg)

**Comment by akhilleusuggo** [comment]
please share the link you're trying to download/share

**Comment by The-Do-It-Yourself-World** [comment]
I dont know how or why but I finally got it to work. I kept following the instructions on github and rebooting the server. Finally it works. I will close this now. Thanks.
