### ISSUE TITLE
Chat2 Plugin

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#3466]
**When Posting a Image**  Having lots of issues with images showing up sideways.
When Posting an image in Portrait it shows as Landscape.  It would be nice to have an option to rotate the image before posting it.

**Liking someone Post**
It would be nice to add an emoji to someones post.

**Take Selfie or 3sec Video Clip**
Like to see an option to take a selfie or quick video clip and post it to Chat.

Thanks

**Comment by DanielnetoDotCom** [comment]
can you please screenshot the image issue?

**Comment by D-Spayre** [comment]
Here's is an image i took, then posted it.  You'll see it changes orientation.  Also is there a way that when someone clicks on the image it takes them out of the live feed.  Can the image just open over the feed instead of opening a new page.

![20200803_201849](https://user-images.githubusercontent.com/65576427/89236702-aca62800-d5c7-11ea-9cb9-88fcd66d37a3.jpg)
![Screenshot_20200803-202110_Chrome](https://user-images.githubusercontent.com/65576427/89236705-ae6feb80-d5c7-11ea-857b-39244e468518.jpg)

Thank you...

**Comment by DanielnetoDotCom** [comment]
I just sent a fix. You will need to update your streamer site.

When you take a picture your phone saves any rotation metadata in EXIF headers. When you upload the image to your server, that metadata is still sitting there but The EXIF data is probably being ignored by this basic script.

**Comment by D-Spayre** [comment]
When you say update streamer site I did "sudo git pull" is that correct?
Image is still displaying sideways when I post a Portrait image.

Thanks

**Comment by DanielnetoDotCom** [comment]
Yes I mean git pull.

but it will work only for newly uploaded images.

**Comment by D-Spayre** [comment]
Tried multiple images and still sideways.  Is there anything else I need to do?

Thanks

**Comment by D-Spayre** [comment]
Seems to work on PC, but not on mobile.  Using a Note 10.

**Comment by DanielnetoDotCom** [comment]
Should not be any difference

are you testing with the same image?

maybe the problem is the image.

also check your logs for something like...

`"Make sure you install the php_mbstring and php_exif to be able to rotate images"`

you can only detect rotated images with those modules installed.

**Comment by D-Spayre** [comment]
Different images, taking a new pic with my phone in Portrait and when I attache it, it rotates it sideways.  
Tested multiple images on mobile.

Both mbstring & exif are installed.

Thanks

**Comment by D-Spayre** [comment]
Actually it's only happening with photo's taken with my phone.  Saved images from download or off the web are fine.

**Comment by DanielnetoDotCom** [comment]
yes, maybe your server does not have those libs installed

are you using the external chat?

if you do you will need to update the chat plugin, then update the files on the external server too.

**Comment by D-Spayre** [comment]
When I do "php -m" it shows that they are installed.

No external chat it's running on the same server.

How can I tell where there are updates for the plugins?  Right now I just keep downloading them and comparing the file size.

Thanks

**Comment by DanielnetoDotCom** [comment]
Hi

I just sent some updates that will help you find what plugin is outdated, please read this

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform#plugins-update
