### ISSUE TITLE
Chat2 error: Table 'avideo.chat_channels' doesn't exist

### ISSUE THREAD

**Issue by jyrihovila** [WWBN/AVideo#3467]
Running YouPHPTube version 69fdeb8

The following error is recorded in the YouPHPTube log file:

`(
    [0] => Array
        (
            [file] => /var/www/html/YouPHPTube/objects/mysql_dal.php
            [line] => 134
            [function] => log_error
            [args] => Array
                (
                    [0] => [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'avideo.chat_channels' doesn't exist<br>
SELECT * FROM chat_channels WHERE  users_id = ? LIMIT 1
                )

        )

    [1] => Array                                                                                                                [223/333]
        (
            [file] => /var/www/html/YouPHPTube/plugin/Chat2/Objects/Chat_channels.php(14) : eval()'d code(1) : eval()'d code
            [line] => 113
            [function] => readSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => SELECT * FROM chat_channels WHERE  users_id = ? LIMIT 1
                    [1] => i
                    [2] => Array
                        (
                            [0] => 2
                        )

                )

        )

    [2] => Array
        (
            [file] => /var/www/html/YouPHPTube/plugin/Chat2/Chat2.php(14) : eval()'d code(1) : eval()'d code
            [line] => 133
            [function] => getFromUsersId
            [class] => Chat_channels
            [type] => ::
            [args] => Array
                (
                    [0] => 2
                )

        )

    [3] => Array                                                                                                                [189/333]
        (
            [file] => /var/www/html/YouPHPTube/plugin/Chat2/Chat2.php(14) : eval()'d code(1) : eval()'d code
            [line] => 121
            [function] => roomHasServer
            [class] => Chat2
            [type] => ::
            [args] => Array
                (
                    [0] => 2
                )

        )

    [4] => Array
        (
            [file] => /var/www/html/YouPHPTube/plugin/Chat2/Chat2.php(14) : eval()'d code(1) : eval()'d code
            [line] => 112
            [function] => getChatRoomFromUsersID
            [class] => Chat2
            [type] => ::
            [args] => Array
                (
                    [0] => 2
                )

        )

    [5] => Array
        (
            [file] => /var/www/html/YouPHPTube/plugin/AVideoPlugin.php
            [line] => 164
            [function] => getFooterCode
            [class] => Chat2
            [object] => Chat2 Object
                (
                )

            [type] => ->
            [args] => Array
                (
                )

        )

    [6] => Array
        (
            [file] => /var/www/html/YouPHPTube/view/include/footer.php
            [line] => 95
            [function] => getFooterCode
            [class] => AVideoPlugin
            [type] => ::
            [args] => Array
                (
                )

        )

    [7] => Array
        (
            [file] => /var/www/html/YouPHPTube/plugin/Live/view/modeYoutubeLive.php
            [line] => 144
            [args] => Array
                (
                    [0] => /var/www/html/YouPHPTube/view/include/footer.php
                )

            [function] => include
        )

    [8] => Array
        (
            [file] => /var/www/html/YouPHPTube/plugin/Live/index.php
            [line] => 26
            [args] => Array
                (
                    [0] => /var/www/html/YouPHPTube/plugin/Live/view/modeYoutubeLive.php
                )

            [function] => include
        )

)

[04-Aug-2020 14:34:22 Europe/Berlin] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'avideo.chat_channels' do
esn't exist<br>
SELECT * FROM chat_channels WHERE  users_id = ? LIMIT 1
[04-Aug-2020 14:34:22 Europe/Berlin] AVideoLog::ERROR: Array                                                                    [102/333]
(
    [0] => Array
        (
            [file] => /var/www/html/YouPHPTube/objects/mysql_dal.php
            [line] => 134
            [function] => log_error
            [args] => Array
                (
                    [0] => [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'avideo.chat_channels' doesn't exist<br>
SELECT * FROM chat_channels WHERE  users_id = ? LIMIT 1
                )

        )

    [1] => Array
        (
            [file] => /var/www/html/YouPHPTube/plugin/Chat2/Objects/Chat_channels.php(14) : eval()'d code(1) : eval()'d code
            [line] => 113
            [function] => readSql
            [class] => sqlDAL
            [type] => ::
            [args] => Array
                (
                    [0] => SELECT * FROM chat_channels WHERE  users_id = ? LIMIT 1
                    [1] => i
                    [2] => Array
                        (
                            [0] => 0
                        )

                )

        )

    [2] => Array
        (
            [file] => /var/www/html/YouPHPTube/plugin/Chat2/Chat2.php(14) : eval()'d code(1) : eval()'d code
            [line] => 139
            [function] => getFromUsersId
            [class] => Chat_channels
            [type] => ::
            [args] => Array
                (
                    [0] => 0
                )

        )

    [3] => Array
        (
            [file] => /var/www/html/YouPHPTube/plugin/Chat2/Chat2.php(14) : eval()'d code(1) : eval()'d code
            [line] => 121
            [function] => roomHasServer
            [class] => Chat2
            [type] => ::
            [args] => Array
                (
                    [0] => 2
                )

        )

    [4] => Array
        (
            [file] => /var/www/html/YouPHPTube/plugin/Chat2/Chat2.php(14) : eval()'d code(1) : eval()'d code
            [line] => 112
            [function] => getChatRoomFromUsersID
            [class] => Chat2
            [type] => ::
            [args] => Array
                (
                    [0] => 2
                )

        )

    [5] => Array
        (
            [file] => /var/www/html/YouPHPTube/plugin/AVideoPlugin.php
            [line] => 164
            [function] => getFooterCode
            [class] => Chat2
            [object] => Chat2 Object
                (
                )

            [type] => ->
            [args] => Array
                (
                )

        )

    [6] => Array                                                                                                                  [8/333]
        (
            [file] => /var/www/html/YouPHPTube/view/include/footer.php
            [line] => 95
            [function] => getFooterCode
            [class] => AVideoPlugin
            [type] => ::
            [args] => Array
                (
                )

        )

    [7] => Array
        (
            [file] => /var/www/html/YouPHPTube/plugin/Live/view/modeYoutubeLive.php
            [line] => 144
            [args] => Array
                (
                    [0] => /var/www/html/YouPHPTube/view/include/footer.php
                )

            [function] => include
        )

    [8] => Array
        (
            [file] => /var/www/html/YouPHPTube/plugin/Live/index.php
            [line] => 26
            [args] => Array
                (
                    [0] => /var/www/html/YouPHPTube/plugin/Live/view/modeYoutubeLive.php
                )

            [function] => include
        )

)

[04-Aug-2020 14:34:22 Europe/Berlin] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'avideo.chat_channels' do
esn't exist<br>
SELECT * FROM chat_channels WHERE  users_id = ? LIMIT 1
`

**Comment by DanielnetoDotCom** [comment]
Hi

Did you install the Chat2 plugin tables?

please click on this button and try again...

![image](https://user-images.githubusercontent.com/18009293/89296654-02ff7f00-d639-11ea-9cd2-a5574c4051e8.png)

**Comment by akhilleusuggo** [comment]
the DB tables are missing

**Comment by jyrihovila** [comment]
> Did you install the Chat2 plugin tables?
> 
> please click on this button and try again...
> 
> ![image](https://user-images.githubusercontent.com/18009293/89296654-02ff7f00-d639-11ea-9cd2-a5574c4051e8.png)

I did -- a long time ago, when the plugin was initially installed. Since then it's been updated (several times) and I think I've skipped installing the tables for a long time. Re-installed them, no errors are being logged any more.
