### ISSUE TITLE
The file system transfer is the worst rly

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3468]
I don't really understand what is happening here . The VOD feature is ignored ( it's fine ) 
But what I don't understand is this . I live-stream to a [server1] , the stream is saved and transferred to streamer site [Server2] , this server does send it to encoder [Server3] , then the encoder when it's done , does send it back to streamer site [Server2] , and from this server got sent to Avideo-Storage [Server4] .

I am the only one that really thinks this is madness?  xDDDD ( I'm not angry , just LOL )
Can we just Send from Live-stream to encoder , and encoder to storage server ?

This is the representation of what we're doing right now .. wast of bandwidth and a lot of resources IO etc .

![represent](https://user-images.githubusercontent.com/52116577/89309148-b8532680-d67b-11ea-99b8-95aa44d3d505.jpg)

If the VOD is not an option ,then a the lease , can you add an option where we can INDICATE to witch server do we wanna sent to saved stream ? In this way I can create a `-c copy -movflags +faststart ` to begin with . Later later add some other option that I've mentioned here : https://github.com/WWBN/AVideo/issues/3436

PS : This file system transfer is usable ONLY if all the server are hosted on the same provider with a private network , if not then it's too much data wasted .

**Comment by DanielnetoDotCom** [comment]
Hi @akhilleusuggo the VOD option is not ignored, I just do not have time right now, I think it is a really good option.

I agree the communication can be and must be improved. but think that way ... 

the streamer is the brain, so everything that happens on live server, or storage or encoder MUST ask the streamer.
All of them only communicate with the streamer, they do not talk with each other. that way makes easier to control access and permissions. also share resources with multiple streamers.

I am not sure hot to do yet, but yes we can avoid data transfer between them but not avoid the requests. this will request code modification in all of them.

I am not ready to make that change yet, but I will for sure, I agree with you it will improve a lot the performance.

maybe start with the VOD, then think about the communication. observing your diagram I think the first modification should be allow the encoder send videos directly to the storage.

I can see 2 main points here, (let me know if I understand correctly)

1. Live will use VOD to convert the files and send them directly to the storage (I guess we still can use encryption keys for HLS)
2. The encoder must send files directly to the storage.

**Comment by akhilleusuggo** [comment]
Yes . You understood me well .
That's why ( at the least , the payed plugins , must have some advantages with the APIs ) . With APIs the requests should be made easily to request for example the Video's ID , and skip the extra go back and forth the streamer site . In fact , the streamer site should not be really the one with the requests , but the database . The DB should be the core of everything with APIs from the streamer site .

I appreciate that you took a look .
Greetings
