### ISSUE TITLE
Send stream to encoder

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3471]
We need an option to chose to witch server we wanna send the recorded stream .
Also an option to enable or disable HLS/MP4 formats from the configuration.php 

For example since I can not predict in witch resolution the stream is , I can not encode it with mp4 . HLS does detect it automatically . But I don't wanna store the rest of the videos on mp4 , only streamed ones .

We have really no control over this .

**Comment by DanielnetoDotCom** [comment]
Hi

I guess I do not understand your requirements.

Usually, we have only one Streamer connected to a Live server. and that is where we will send the recorded file.

But you want to choose what encoder each user will use by default correct?

are you using an encoder Network?

We do not have this feature yet, but it is an idea, instead get the most available encoder we will get a specific encoder for each user.

is that the idea?

**Comment by akhilleusuggo** [comment]
This could be a solution yes . The idea is , to specify witch encoder we want our live-stream recorded to be sent . Right now , the default encoder is the one on here : 

![image](https://user-images.githubusercontent.com/52116577/89651351-7967df80-d8cc-11ea-9dc0-ee03558a3a46.png)

And we have no control over if we want the streams to be on HLS or MP4 .

**Comment by DanielnetoDotCom** [comment]
I guess if you have the encoder network it will decide what encoder will send your recorded videos

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom if for once read what is the goal of this . But it's fine .

> We need an option to chose to witch server we wanna send the recorded stream .
> Also an option to enable or disable HLS/MP4 formats from the configuration.php
> 
> For example since I can not predict in witch resolution the stream is , I can not encode it with mp4 . HLS does detect it automatically . But I don't wanna store the rest of the videos on mp4 , only streamed ones .
> 
> We have really no control over this .

I'm done
