### ISSUE TITLE
Changing the domain name (my website name)on my VPS-what changes should i make in the application if at all-please advise

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3472]
**Describe the question**
A clear and concise description of what is your question.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by akhilleusuggo** [comment]
there's an option that simplify thing .
`/var/www/html/AVideo/install`
`php php updateStreamerURL.php`

**Comment by vraghavans** [comment]
[updateStreamerURL1.txt](https://github.com/WWBN/AVideo/files/5032219/updateStreamerURL1.txt)
this is my file ,i have added the new domain maritimeplatform.com under the new url,
Please advise if its correct as still i cant see my website and still showing the default apache page
Please advise,
thanks!
Rgds
Vijay

**Comment by akhilleusuggo** [comment]
I think you misunderstand the options ...
This is a command line to update easly your site domain name .
Just execute the command line and enter your new domain name url 


`cd /var/www/html/AVideo/install`
`php updateStreamerURL.php`

**Comment by vraghavans** [comment]
thanks! it worked

sorry for my ignorance!!
Rgds
Vijay

**Comment by akhilleusuggo** [comment]
hm ? not working ?

**Comment by vraghavans** [comment]
Hi,can you pls guide me,what shd i do

**Comment by akhilleusuggo** [comment]
I've already guided you , and you said it's working

**Comment by DanielnetoDotCom** [comment]
Check this 

https://tutorials.avideo.com/video/18/fix-youphptube-url-after-move-server-location-and-ip?channelName=yeshua

This is old but it may help you

**Comment by vraghavans** [comment]
Dear Daniel,

thanks for your reply,please note, the configuration file already has the new domain ,still its showing only the apache page in VPS.Please advise.

I have written an email to you for assistance also.Please help
rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
If you follow the guide and it is not working yet, please check/share your log files and the HTML source code from your browser for some clue

**Comment by vraghavans** [comment]
Dear Daniel,

Thanks for your reply,

Please find attached the html source code and the last part of the log.

Kindly advise
[avideo log.txt](https://github.com/WWBN/AVideo/files/5054681/avideo.log.txt)
[html of home page.txt](https://github.com/WWBN/AVideo/files/5054682/html.of.home.page.txt)

**Comment by DanielnetoDotCom** [comment]
What is the problem now?

I cannot see any problem on the files you sent

**Comment by vraghavans** [comment]
Dear Daniel,

Yes actually all the files are pointing to my old domain which is seafarerstube.com,i want to change the domain to maritimeplatform.com where it is showing only the apache page and not the website.

Thanks so much for your time.
Please assist
Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
How is your configuration.php file?

after change it, make sure you clear the cache

**Comment by vraghavans** [comment]
I tried that too,configure file i change the domain from seafaerstube.com to maritimeplatform.com,
however no luck,seafarerstube.com only takes me to site.

Attached is my configuration.php file
[configuration.txt](https://github.com/WWBN/AVideo/files/5069721/configuration.txt)

**Comment by DanielnetoDotCom** [comment]
this is your encoder configuration.php

we need the streamer configuration.php

**Comment by vraghavans** [comment]
Dear Daniel,

Thanks for your message
Please find attached the php file
[config php.txt](https://github.com/WWBN/AVideo/files/5078615/config.php.txt)

**Comment by akhilleusuggo** [comment]
@vraghavans this is the line you need to modify : 

`$global['webSiteRootURL'] = 'maritimeplatform.com/';`

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo is correct 

`$global['webSiteRootURL'] = 'https://www.maritimeplatform.com/';`

or

`$global['webSiteRootURL'] = 'https://maritimeplatform.com/';`

**Comment by vraghavans** [comment]
Thanks so much @DanielnetoDotCom and @akhilleusuggo !
You are always there when i make silly errors also:)
I have got through to hte website but it says the SSL is for seafarerstube,we need to change something in Avideo or shd i check with VPS please.

![image](https://user-images.githubusercontent.com/65802024/90322439-b0479080-df71-11ea-8afe-9b422e19d86e.png)

**Comment by DanielnetoDotCom** [comment]
now you have to reinstall the SSL, each domain has a different SSL certificate.

try to use letsencrypt for it. Google to learn how to do it.

**Comment by vraghavans** [comment]
Thanks Daniel and done!
now the new domain is ssl protected!

but the encoder is still using seafarerstube.com domain,i did change the encoder configuration file ,pls find attached.

![image](https://user-images.githubusercontent.com/65802024/90327631-26b8b280-dfb3-11ea-83f0-da31f373d7ce.png)
[configuration.txt](https://github.com/WWBN/AVideo/files/5080062/configuration.txt)

**Comment by akhilleusuggo** [comment]
@vraghavans You need to add the new streamer site to the encoder allowed streams .

![image](https://user-images.githubusercontent.com/52116577/90327908-a4bf8e00-dfa0-11ea-9450-30eb3912baf7.png)

1- You need to be logged in as Admin 
2- If you can't , you need to add it manually to the database .
3- If you don't know how to use it , you can use phpmyadmin 
4- phpmyadmin not well configured , will bring vulnerability . You can still re-install the encoder site .


----------------------------------------------------------------

@DanielnetoDotCom You may add in the future the feature to add from /install directory `newdomain.php`  and `makeAdmin.php` like the feature on network encoder and streamer site .

**Comment by vraghavans** [comment]
thanks! @akhilleusuggo for your advise,

could you pls give me an hint how do i reach this screen please.

thanks!
rgds
vijay

**Comment by akhilleusuggo** [comment]
You need to be logged in as Admin

**Comment by vraghavans** [comment]
Dear @akhilleusuggo ,yes i have looged in as Admin,

But not sure how do i reach this screen you have mentioned.

Thanks for your tiem
Rgds
Vijay

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/90330353-d6425480-dfb4-11ea-8bea-c0d3b552c5ac.png)

**Comment by vraghavans** [comment]
Dear @akhilleusuggo ,

Iam so sorry,i still cant seem to figure out as i have logged into the admin account of the streamer site and am not able to login to the encoder site with any of the domain names.

rgds
Vijay

**Comment by akhilleusuggo** [comment]
Please read again this : 

> @vraghavans You need to add the new streamer site to the encoder allowed streams .
> 
> ![image](https://user-images.githubusercontent.com/52116577/90327908-a4bf8e00-dfa0-11ea-9450-30eb3912baf7.png)
> 
> 1- You need to be logged in as Admin
> 2- If you can't , you need to add it manually to the database .
> 3- If you don't know how to use it , you can use phpmyadmin
> 4- phpmyadmin not well configured , will bring vulnerability . You can still re-install the encoder site .
> 
> @DanielnetoDotCom You may add in the future the feature to add from /install directory `newdomain.php` and `makeAdmin.php` like the feature on network encoder and streamer site .


All what I saying here is ON THE ENCODER SITE , _**not**_ the streamer site

**Comment by vraghavans** [comment]
hi @akhilleusuggo i cant login as admin anymore so i tried changing the table data manually as below
![image](https://user-images.githubusercontent.com/65802024/90334282-2e477e00-dfea-11ea-9029-090f0ae1ff93.png)

but still icant see the login allowed

![image](https://user-images.githubusercontent.com/65802024/90334291-415a4e00-dfea-11ea-9916-79a5f5afc432.png)

**Comment by vraghavans** [comment]
finally figured it out !!
@akhilleusuggo and @Daniel,
 I had to change the configurations table data to add the new urls,in the database aVideo-Encoder
Thanks for your patience!!
Rgds
Vijay
