### ISSUE TITLE
youtube upload

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3473]
trying to configure youtube auto upload
When I type in an API key into developer_key: into the plugin, I get an error that it's looking for the next developer_key: 1.

What am I missing?

**Comment by akhilleusuggo** [comment]
youtube have updated the API
For now nobody took a look on that .

**Comment by fakeologist** [comment]
So the feature is dead? Should I deactivate the plugin?

**Comment by akhilleusuggo** [comment]
I can't confirm that . I'm don't use this feature .
But I've received this email ( all users should )

![image](https://user-images.githubusercontent.com/52116577/89487332-d456e500-d7ad-11ea-9909-80f93ad0143b.png)


I'm not sure if this is what making the issue .

**Comment by fakeologist** [comment]
Seems dead to me.

**Comment by DanielnetoDotCom** [comment]
Any idea what needs to verify the API project?
