### ISSUE TITLE
Subscriber list

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3474]
Looking at my subscribers, it says showing 1-21 subscribers, but only 10 show.
Changing options and browsers makes no difference.
Going to next page does nothing.

**Comment by fakeologist** [comment]
still not working

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

Also attach a screenshot to understand you better

**Comment by fakeologist** [comment]
http://somup.com/cYjQIo6vFb

there's a video of me trying to change the pages.
I'll see how to get logs uploaded soon.

**Comment by DanielnetoDotCom** [comment]
@fakeologist you were right, here is a fix

**Comment by fakeologist** [comment]
Where's the fix?  Update via github?

**Comment by akhilleusuggo** [comment]
git pull

**Comment by fakeologist** [comment]
fixed thanks Daniel!
