### ISSUE TITLE
Adding Adsense code to Atube

### ISSUE THREAD

**Issue by rielcomms** [WWBN/AVideo#3475]
**Describe the question**
Please how do I add adsense code to my site
It says this and I cant seem to add the code.

We couldn’t find the code on your site. This is because the code is either missing or incomplete, or because the URL of your site is incorrect. Learn more.

Copy and paste this code in the HTML of your site, between the <head> and </head> tags.
**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by jengajenga** [comment]
1. There's a paid plugin for Adsense
2. There's a free adcode spot in the plugins. activate it and edit where you want the ads to appear.

**Comment by DanielnetoDotCom** [comment]
Adsense you should be able to add it or in the head section 
Just go to site configuration menu -> in the section Script Code -> Head Code, you will find a text area to place your code

![image](https://user-images.githubusercontent.com/18009293/89651924-11e56c00-d89b-11ea-880c-861717ac7adc.png)


Or you can use the ADs plugin to add it in a specific place

![image](https://user-images.githubusercontent.com/18009293/89651850-f1b5ad00-d89a-11ea-87fa-54e180de28b1.png)
