### ISSUE TITLE
Add original source url

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3476]
When importing videos, can the original url be added to the video description?

**Comment by akhilleusuggo** [comment]
It's added to the database ( in case you're looking for the url )

**Comment by fakeologist** [comment]
I need everyone's be able to see it on the web page.

**Comment by fakeologist** [comment]
Hopefully Daniel can add this.

**Comment by DanielnetoDotCom** [comment]
do you mean the original download URL? for example a Youtube URL?

**Comment by fakeologist** [comment]
Yes please
