### ISSUE TITLE
User_Controll

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3477]
![image](https://user-images.githubusercontent.com/52116577/89570935-884c8480-d82f-11ea-9915-9b8dee823e86.png)

After updating the warning is still there . Probably because you have not included a version ( to click update ) ( example @1.1)

**Comment by DanielnetoDotCom** [comment]
That means you can download the new version on the market place.

please check this https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform#plugins-update

**Comment by akhilleusuggo** [comment]
xD , daniel ...
I did it 3 times ...

**Comment by DanielnetoDotCom** [comment]
Try delete the plugin folder first then upload it

**Comment by akhilleusuggo** [comment]
yes , now requested to update . ( FIXED )
Why is that ?
Should I delete everytime the folder ? Is this what we should everytime when we want to update a plugin ?

**Comment by DanielnetoDotCom** [comment]
I guess was a permission issue.

Not sure. and yes It supposes to overwrite the files
