### ISSUE TITLE
Searching in Android app

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3478]
As I search in app, each character I type in search invokes the search.
This is frustrating, as it causes a delay in keyboard input.
Is this a feature or bug?

**Comment by akhilleusuggo** [comment]
feature

**Comment by fakeologist** [comment]
Makes it hard to search. Please make it option.

**Comment by akhilleusuggo** [comment]
As far as I know , you need to have the plugin to make use of it .
I'm not sure if we're talking about the same thing . But the plugin that takes care of that is Livesearch

**Comment by fakeologist** [comment]
Are we talking about the android app still? Didn't know it had plugins.

**Comment by akhilleusuggo** [comment]
I'm not sure , but I believe the free version will have some default configuration

**Comment by DanielnetoDotCom** [comment]
The key press has a timeout time, if you stop to type for 1 second it will request the search for you. It is very common to save you some clicks . So the search will happen without need to click on the search button

**Comment by fakeologist** [comment]
I thought so. Can this be toggled on and off in future updates or increase the time to 3 seconds?

**Comment by DanielnetoDotCom** [comment]
Right now it is hard coder, cannot be changed.
