### ISSUE TITLE
Is there new files for Chat2?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3479]
I wanted to try the remote CHat2 thing and I am not sure if all the instructions are here.

All I see is 

`Chat2` must be enabled
API must be enabled
Copy all files from the Chat2 plugin to a new server. Feel free to use any transfer tool, for example you can use Filezilla or Winscp
Create a database for the Chat2. sudo mysql -u username -p -e "CREATE DATABASE database_name;"
Edit the file /path/to/Chat2/standAlone/config.php with the following code
```
<?php 
$mysqlHost = '[localhost]';
$mysqlUser = '[username]';
$mysqlPass = '[password]';
$mysqlDatabase = '[database_name]';
$global['systemRootPath'] = '[Edit with your server path, I.E. /var/www/html/Chat2/]';
$global['serverName'] = '[Edit with your server name, can be any string]';
$global['webSiteRootURLStandAlone'] = '[Edit with your chat server URL, I.E. https://chat.mysite.com/]';
$global['webSiteRootURL'] = '[streamerSiteURL]';
$APISecret="[get it in your API `Plugin]";`
```

I watched the video and It shows a page that I do not even have. https://www.joshwhotv.com/plugins/Chat2/view/editor.php
 
on my Chat2 is this something different?

**Comment by akhilleusuggo** [comment]
I'm not sure IF there was a modification on the last update . But your URL should be with CAPITAL ''V'' . Try this one : 

https://www.joshwhotv.com/plugins/Chat2/View/editor.php

**Comment by JoshWho** [comment]
View directory doesn't even exit in the Chat2 floder

**Comment by akhilleusuggo** [comment]
try to update the plugin . 

![image](https://user-images.githubusercontent.com/52116577/89619634-f5dfcb80-d896-11ea-8090-0d5b48587dd9.png)

**Comment by JoshWho** [comment]
There is no update option for me. I ran a Git Pull and it grabbed what it thinks is the latest which is still version 1. There is a image saying update available but when I click it it just takes me to the store and wants me to buy it.

**Comment by akhilleusuggo** [comment]
I believe your server was installed by @DanielnetoDotCom , witch mean you don't own the plugins on the store .
I think Daniel should give one account so you can make updates ... 
I'm talking about updating it from here : https://youphp.tube/marketplace
![image](https://user-images.githubusercontent.com/52116577/89620872-f9745200-d898-11ea-9ee2-10375cbe719b.png)

**Comment by JoshWho** [comment]
I have a store account I just do not have all the plugins since the full install listed on the store to download.

<img src="https://static.buddylist.co/4231.png" style='width:100%;' border="0" alt="Null">

**Comment by akhilleusuggo** [comment]
Yeh , I see . Time to wait for daniel to fix it for you I guess .

**Comment by JoshWho** [comment]
All updated now.
