### ISSUE TITLE
cannot delete FTPAutoImport

### ISSUE THREAD

**Issue by boom02456** [WWBN/AVideo#3480]
![Screen Shot 2020-08-07 at 18 06 34](https://user-images.githubusercontent.com/36606195/89639983-cb166700-d8d8-11ea-8210-3aaa3558cfd3.png)

I cannot delete FTP from the list, once I've clicked it, it shows error in console inspect like this
But Edit and List works normally,

Could you please help?

**Comment by boom02456** [comment]
seems like code in rmDir is incorrect, I commented all and use only ajax to delete, and it can delete

`function rmDir(dirName) {
   /* 
                swal({
                    title: "<?php echo __("Are you sure?"); ?>",
                    text: "<?php echo __("You will not be able to recover!"); ?>",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "<?php echo __("Yes, delete it!"); ?>",
                    closeOnConfirm: false
                },
                        function () {
                            swal.close();
                            modal.showPleaseWait();
                            $.ajax({
                                url: '<?php echo $global['webSiteRootURL']; ?>plugin/FTPAutoImport/deleteDir.json.php?dir=' + encodeURI(dirName),
                                type: 'post',
                                success: function (response) {
                                    modal.hidePleaseWait();
                                    if (response.error) {
                                        setTimeout(function () {
                                            swal("<?php echo __("Sorry!"); ?>", response.msg, "error");
                                        }, 500);
                                    } else {
                                        table.ajax.reload();
                                    }
                                }
                            });
                        });
    */
`

**Comment by boom02456** [comment]
@DanielnetoDotCom could you please check on this?

**Comment by boom02456** [comment]
another page that's not working too is DocumentUpload plugins, maybe you need to update the code to newer version of php usage, this old command is deprecated

**Comment by DanielnetoDotCom** [comment]
Seems like this plugin needs an update to be able to work on the new version of the swal.

as long as it is a custom plugin, I will require you to email directly to developer@youphptube.com
