### ISSUE TITLE
Upload video option not available

### ISSUE THREAD

**Issue by daptim** [WWBN/AVideo#3481]
I salute you @DanielnetoDotCom and his team for providing this opportunities.

I have just finished installed AVideo instance and observed that **Upload Video** option is is not available on my account after login.

I login as admin but i can't see the **Upload Video** option, I only saw **Encode Video and Audio**, **Embed Video** in the menu there is no option to upload video. 
At I though am missing something at first installation so, wipe and reinstalled a new instance but still got the same things. kinldy see image below.

Please help what am i missing

Regards 
Timothy
![Capture](https://user-images.githubusercontent.com/21238283/89641114-e1a4ca00-d8a8-11ea-8d62-630c5c718a5a.PNG)

**Comment by akhilleusuggo** [comment]
Encode video = upload videos ( with encoding , recommended for bitrate and browser compatibility )
If you insist on direct upload , go to plugins CustomizeAdvanced , and customize your site . In this particular case , you wanna touch this section : 

![image](https://user-images.githubusercontent.com/52116577/89647987-26d7f480-d8c7-11ea-8f4c-0c2b2b083ebd.png)

Greetings

**Comment by daptim** [comment]
Thank you for your quick response. I can now do direct upload.

Regards 

Timothy
