### ISSUE TITLE
Notify Admin email for Ad code submissions

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3482]
Just something to tell us when a user has submitted an ad code for their channel so we can approve it faster.

**Comment by akhilleusuggo** [comment]
+

**Comment by DanielnetoDotCom** [comment]
@JoshWho what exactly ad code are you talking about?
can you please screenshot?

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/89794543-df07d600-db2f-11ea-99e3-951c10731419.png)

**Comment by DanielnetoDotCom** [comment]
Please check this

**Comment by JoshWho** [comment]
Check what?

**Comment by DanielnetoDotCom** [comment]
@JoshWho the update I just sent

**Comment by JoshWho** [comment]
O ok just a sec

**Comment by JoshWho** [comment]
OK just ran the update. Is there anything I need to turn on or is it just automatic email now?

**Comment by DanielnetoDotCom** [comment]
when someone updates the ad_overlay code you will be notified

**Comment by JoshWho** [comment]
Sweeeeeeeeet. Thank you Daniel.
