### ISSUE TITLE
Chat2 External showing 500 page on remote server 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3483]
https://ww2.joshwhotv.com/plugin/Chat2/

**Comment by DanielnetoDotCom** [comment]
Did you install the tables?

check the apache error log.

**Comment by JoshWho** [comment]
Where is the sql file so a can manually add them? Terminal wont let me input it because of some mail serve deal.

**Comment by DanielnetoDotCom** [comment]
is the same as the Chat2

![image](https://user-images.githubusercontent.com/18009293/89679759-1ecc8480-d8c8-11ea-804b-bbcd03997519.png)

**Comment by JoshWho** [comment]
kk

**Comment by JoshWho** [comment]
OK they r installed and still showing a 500 page

**Comment by DanielnetoDotCom** [comment]
and the apache logs, what is there?

**Comment by JoshWho** [comment]
No error being recorded

**Comment by JoshWho** [comment]
[https @ 0x55c0efaea300] HTTP error 404 Not Found
https://live.joshwhotv.com:444/live/5e61a0f4eedf3.m3u8: Server returned 404 Not Found

**Comment by DanielnetoDotCom** [comment]
must be something, error 500 must raise something

the 404 is regarding something else.

**Comment by JoshWho** [comment]
"GET /plugin/Chat2/?room_users_id=1160&user=JoshWhoNews&pass=0932c751ad7c41a0a86fd99d5a07a112&iframe=1&noFade=1 HTTP/1.1" 500 1598 "https://www.joshwhotv.com/plugin/Live/?c=5d06e49951db9" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.x.4x.1x5 Safari/537.36"

**Comment by JoshWho** [comment]
too much vulnerable stuff shows in the log to post on here

**Comment by JoshWho** [comment]
Turns out it was a cors issue and needed apache Mod_header enabled to work correctly. Thank you Daniel works great now.
