### ISSUE TITLE
Photos not uploading in external Standalone Chat2

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3485]
Not sure why I created the videos directory and gave it 777 chmod is there another place that needs this?

<img src="https://static.buddylist.co/83d1de97-daef-4f97-a12b-a26aea797391.png" style='width:100%;' border="0" alt="Null">

**Comment by JoshWho** [comment]
bump

**Comment by DanielnetoDotCom** [comment]
I just sent an update to chat2, please download the plugin again and update your standalone server.

**Comment by JoshWho** [comment]
Works good now. Thank you
