### ISSUE TITLE
Non existing video redirects to random video , also user pages .

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3486]
Some time ago we added an option to redirect non existing videos to a page that said this videos doesn't exist or removed .
This works only if what you're trying to type is something like this : flkjds.example.com/video/what-every-what-ever

But when trying to access videos with flkjds.example.com/v/99999 , does not work .
Example : https://demo.avideo.com/v/99999999   , this url will redirect to a random video ( in my case , does redirect to latest uploaded video ) .

Same happens to non-existing users , example : https://demo.avideo.com/channel/dqsdqsdqdfsdfsdfsdfsdfsdfsdfsdfs

**Comment by DanielnetoDotCom** [comment]
I am sending a fix for that

**Comment by akhilleusuggo** [comment]
The channels does redirect to /channels 
Can it redirect to 404 error page ?

**Comment by DanielnetoDotCom** [comment]
I have to build a page for that, right now I do not have one, but in the future, it can be a 404 page.

**Comment by akhilleusuggo** [comment]
thanks for that .
We could for now redirect it to the 404 page that we already have : 

![image](https://user-images.githubusercontent.com/52116577/89809507-4f205700-db44-11ea-8340-d71256d82784.png)

with status 404

**Comment by DanielnetoDotCom** [comment]
This is an option, but I think would be better to have a nice friendly page.

I keep this 404 page for the unpredictables URLs.
