### ISSUE TITLE
will pay for someone to: need purchase button on a video and website links on a channel 

### ISSUE THREAD

**Issue by whoalive** [WWBN/AVideo#3487]
new system i am owner and have full admin.  building a system but need some php and im a little busy and lite on the sites structure. so will pay a little for someone to code this small thing.
 
would like a button on videos under the subscribe for purchase. can be a link to a home  url of a web store, no need for detail location just getem to a storefront.  can be theYouPHPTube sites url with username as subdomain. easy    setting up a subdomain website for a user allows a shopping cart and payment system in house.  

need button under user picture on channel page with linked to users website.
need a second button with setable link to a webpage ie patrone.  for donations

might need a mysql table to store website urls in. 

reply to jmjandebeur@gmail.com if interested

**Comment by DanielnetoDotCom** [comment]
Hi

If you need us to develop, please email at developer@youphptube.com for a quote

**Comment by dayceegiordan** [comment]
<div>
 <button value=Subscribe>
</div>
<div>
<form name=purchase action=process.php method=post>
 <input type=hidden name=user value="<?php echo $_SESSION['user_'id];?>">
<input type=submit value=purchase>
</form>
</div>

process.php
<?php
 /* assuming a database, table and field was already made */
$user_id=@mysql_real_escape_string('$_POST('user');
@mysql_query("INSERT purchase_table SET user_id='user_id'");
mysql_close();
?>

dayceegiordan@yahoo.com

**Comment by dayceegiordan** [comment]
Channel page
<div>
<img src=user_picture.jpg>
</br>
<button value="Visit Web" onclick="window.location.href='www.userwebsite.com';">
</br>
<form action=set_link.php method=post>
<input type=text name=link>
<input type=submit value="Input Link">
</form>
</div>

set_link.php
<?php
$link=@mysql_real_escape_string($_POST['link']);
@mysql_query("INSERT website SET link='$link', user='".$_SESSION['user']."');
@mysql_close();
?>

**Comment by whoalive** [comment]
Little confused, are these pages you made? Or pages insite to edit?
Mike

**Comment by dayceegiordan** [comment]
My apology, the comment should display the sample codes I wrote but I guess It wasn't the case. Here is the supposed comment: SUBSCRIBE</br>    <input type=button value=Purchase onclick="window.location.href='www.website.com';">
Channel page<img src=userpicture.jpg></br><input type=button value="Visit Website" onclick="window.location.href='www.userwebsite.com"></br><form action=link.php method=post><input type=text name=link><input type=submit value="Add Web Link"></form>
link.php<?php$link=@mysql_real_escape_string($_POST['link']);@mysql_query("INSERT INTO weblinks SET link='$link', user='".$_SESSION['user']."');?>

    On Sunday, 9 August 2020, 02:35:21 am GMT+8, whoalive <notifications@github.com> wrote:  
 
 

Little confused, are these pages you made? Or pages insite to edit?
Mike

**Comment by whoalive** [comment]
So am I editing a page or making new one? Still little confused.

**Comment by dayceegiordan** [comment]
Edit the existing one and perhaps add a similar php code I have provided. You can either create new file or modify your existing one. If you can provide me your existing file maybe I can provide much specific details.
    On Sunday, 9 August 2020, 03:20:10 am GMT+8, whoalive <notifications@github.com> wrote:  
 
 

So am I editing a page or making new one? Still little confused.
