### ISSUE TITLE
Video upload not working in latest version even after allowed changes

### ISSUE THREAD

**Issue by armornet** [WWBN/AVideo#3488]
Hello,
    After including mov, mpeg, avi file types in the  file objects/include_config.php in global allowed extension still i am unable to upload mov or avi file...

Please let me know how to rectify the issue so that users can upload file types which i allow as my server is ffmpeg enabled

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by armornet** [comment]
I am using the direct upload..

**Comment by DanielnetoDotCom** [comment]
If you want to play mov, mpeg, avi on the browser, I strongly recommend you to use the encoder.

**Comment by armornet** [comment]
I want users be allowed to upload .mov, .avi. mpeg files which should be processed by the encoder and be live on the video platform.. I already have encoder site and main avvideo site... 
please see the screenshot for your understanding..
![error](https://user-images.githubusercontent.com/54991415/90040828-115b3400-dce6-11ea-8aa4-03a70147d408.png)
