### ISSUE TITLE
Promoted videos not dislaying on app btu only on website

### ISSUE THREAD

**Issue by GodgivenButhelezi** [WWBN/AVideo#3489]
greetings. I would like to report a problem that I discovered that the promoted videos are not showing on the app but only on the website , I was using the avideo platform testing app.

**Comment by GodgivenButhelezi** [comment]
And also my ads are not displaying on the App

**Comment by DanielnetoDotCom** [comment]
do you mean the videos ads?

the banner ads are not supported on the app yet. but video ads should be fine.

**Comment by GodgivenButhelezi** [comment]
the  promoted videos and promoted channels are not showing on top or anywhere else.

**Comment by DanielnetoDotCom** [comment]
yes, they are not integrated with the mobile app yet.

**Comment by GodgivenButhelezi** [comment]
what about the overlayed ads, Are they also not integrated in the app ?
I want to pay for the app but I'm worried.

**Comment by DanielnetoDotCom** [comment]
Overlay ads should work

**Comment by DanielnetoDotCom** [comment]
Test it with the demo ones

**Comment by GodgivenButhelezi** [comment]
I Tested but it's not showing
