### ISSUE TITLE
Features not working after update

### ISSUE THREAD

**Issue by praiseworld3d** [WWBN/AVideo#3491]
Hello All...
1st, I have 2 users that have external streams pre-scheduled to our youphptube platform https://praiseworld3d.tv
 Prior to the recent update those streams stayed in the "live now" area just below the homepage feature video slider, and now they do not. See image attached.
![scheduled-external-pw3dtv](https://user-images.githubusercontent.com/63332630/89794757-7ef43e00-daf5-11ea-8110-fefa6bcb4b26.JPG)
2nd, a user's live broadcast via a cell phone to their channel did not show in the same "live now" area. It did show on his channel once encoded. This user has admin status.

3rd, the ad videos no longer play at the beginning when users view posted videos.
Plugins are not up to date???
Any assistance is greatly appreciated, and thanks in advance.
P.S.
Compensation for extended/personal assistance will be considered.
God bless...

**Comment by DanielnetoDotCom** [comment]
I cannot see many clues here, I will need the admin site user to be able to check, please send it to developer@youphptube.com

but I can see may errors in your log regarding the Chat

`AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'aVideo.chat_channels' doesn't exist`

You are probably missing some updates in the Chat2 plugin. I cannot see any relation, but it is a start to try to make things work.
