### ISSUE TITLE
SendRecordedToEncoder

### ISSUE THREAD

**Issue by ricasht** [WWBN/AVideo#3492]
hello, I intend to get this plugin, but first I would like more details.
does it automatically record my live?
do I need to do any specific process?

**Comment by DanielnetoDotCom** [comment]
You need the Live server and Encoder properly working.

and follow this: https://github.com/WWBN/AVideo/wiki/Record-Live-Stream

**Comment by ricasht** [comment]
data as the number of live viewers are recorded?

**Comment by DanielnetoDotCom** [comment]
sorry what?

**Comment by akhilleusuggo** [comment]
No , not recorded

**Comment by guymass** [comment]
I have the same problem no recording when streaming from OBS, here is my nginx.conf:

rtmp {
    server {
        listen 1935;
        allow play all;
        #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video f>
        application live {
            allow play all;
            live on;
            #record all;
            #record_path /video_recordings;
            #record_unique on;
            hls on;
            hls_nested on;
            hls_path /HLS/live;
            #hls_playlist_length 4s;
            #hls_fragment 1s;
            hls_fragment 10s;
            on_publish http://159.65.85.96/plugin/Live/on_publish.php;
            on_play http://159.65.85.96/plugin/Live/on_play.php;
            on_record_done http://159.65.85.96/plugin/Live/on_record_done.php;
            recorder video{
                record all;
                record_path /var/www/tmp;
                record_notify on;
                record_max_size 2048M;
                #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
                record_suffix -%d-%b-%y-%T.flv;
            }
        }
    }
}

**Comment by akhilleusuggo** [comment]
@guymass open a new issue , the topic here is about some information regarding the plugin , not an issue
