### ISSUE TITLE
Configure Live Stream

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3493]
After upgrading to latest version I found I need to reconfigure my Live stream RTMP server. I currently cannot record anything. Here is a SS of the confige screen.
![Screen Shot 2020-08-11 at 1 17 46](https://user-images.githubusercontent.com/58882903/89837083-e3a0ae80-db70-11ea-86f4-1facbb3a2458.jpg)

Mobile can start streaming but it doesn't show on front page Live and doesn't record. Streams from OBS work ok with a 5-6sec delay.

**Comment by guymass** [comment]
I also Updated the SendRecorderToEncoder plugin, however it still shows the orange button indicating there is an update. Note sure if the update worked or not but it seemed to update the plugin. I also have this error connecting with mobile:

2020/08/10 21:45:58 [error] 7128#7128: *3 open() "/HLS/live/5df1736d9cbb7/index.m3u8" failed (2: No such file or directory), client: 109.186.126.180, server: fetube.flatearth.co.il, request: "GET /live/5df1736d9cbb7/index.m3u8 HTTP/2.0", host: "fetube.flatearth.co.il", referrer: "https://fetube.flatearth.co.il/plugin/Live/?c=5df12a039b08f"

note sure how to fix this issue, could realy use your assitance here.

**Comment by akhilleusuggo** [comment]
Try deleting the plugin's directory and re-uploading .
Happens to me too .

**Comment by CROSSMediaNet** [comment]
I am having the same issues when I update to 9.4. How to delete the plugin directory and re-uploading it?

**Comment by akhilleusuggo** [comment]
@CROSSMediaNet 
1- Browse to your root AVideo directory ( default : `cd /var/www/html/AVideo` )
2- Go to your plugin folder ( `cd plugin` )
3- Delete the Plugin folder ( `sudo rm -r SendRecordedToEncoder` )

Now the plugin is delete , re-upload it .

**Comment by DanielnetoDotCom** [comment]
Keep the websiteRootURL empty on the SendRecorderToEncoder  plugin

**Comment by CROSSMediaNet** [comment]
Okay, so basically, remove the SendRecordedtoEncoder folder and re-upload it with the plugin from the plugin store afterward, correct?

**Comment by akhilleusuggo** [comment]
yes

**Comment by CROSSMediaNet** [comment]
Okay...I try that...nothing happen...I can't stream at all and another issue, some people can't login unless they right-tick to "Remember Me"
Do I have to pay each time a problem occurs?

**Comment by DanielnetoDotCom** [comment]
@CROSSMediaNet please check your logs

for me looks like you are out of space on your drives.

**Comment by CROSSMediaNet** [comment]
I am so sorry for this, but I am dumb a little...so how to check the logs to find out that I am out of space

**Comment by DanielnetoDotCom** [comment]
you can go to the terminal and type

`du -h`

then share a screenshot here

**Comment by CROSSMediaNet** [comment]
Okay...I went a got some more HDD space and I think that I did something wrong. On one end, it is streaming, but no streaming output is coming through it...it looks like that I will have to pay for you to fix these issues

**Comment by CROSSMediaNet** [comment]
Here's the screenshot that is going: 
![image](https://user-images.githubusercontent.com/62782361/90836988-5ac70700-e316-11ea-84cf-ffdb848b9e45.png)

But here's the screenshot that is no output:  
![image](https://user-images.githubusercontent.com/62782361/90837052-7fbb7a00-e316-11ea-8922-295045d72fa4.png)

**Comment by CROSSMediaNet** [comment]
Sorry for the green screen...I was working on someone's commercial

**Comment by CROSSMediaNet** [comment]
![image](https://user-images.githubusercontent.com/62782361/90837190-e80a5b80-e316-11ea-84b7-f7f7c8c9f85f.png)

**Comment by CROSSMediaNet** [comment]
Here's what it is doing:  
![image](https://user-images.githubusercontent.com/62782361/90837260-29027000-e317-11ea-90db-a417119e685c.png)

And here's no output:  
![image](https://user-images.githubusercontent.com/62782361/90837299-40415d80-e317-11ea-8f5c-8446f40e0001.png)

Here what I got from the server:  
![image](https://user-images.githubusercontent.com/62782361/90837340-5f3fef80-e317-11ea-8e93-dfd76d00cc1c.png)

**Comment by DanielnetoDotCom** [comment]
I guess I gave you the wrong command 

the correct command is `df -h` NOT `du -h`

**Comment by CROSSMediaNet** [comment]
![image](https://user-images.githubusercontent.com/62782361/90837473-c2ca1d00-e317-11ea-936c-ec79286d9e9a.png)

**Comment by akhilleusuggo** [comment]
you need to provide logs . Is not a space disk issue . 

provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by CROSSMediaNet** [comment]
Here's what I did by using the console for errors:  
![image](https://user-images.githubusercontent.com/62782361/90849981-367b2280-e336-11ea-9221-9dc328f3dd2e.png)

I am still learning how to actually look up errors on the AVideo Platform...it is not straight forward to me

**Comment by akhilleusuggo** [comment]
..... lol

---

`cd /var/www/html/AVideo/videos`  ( go to logs directory )
`cat avideo.log`  ( this will show all the logs )
`tail -f avideo.log` ( will stream the logs , as it happens )
`cat -n 200 avideo.log` ( will display the last 200 lines of logs )

---

I recommend you to cat the last 200 lines , after you issue a live stream , so we can debug and see the issue .
Start a live stream for few seconds , then stop it . past here the logs .

good luck .
