### ISSUE TITLE
Seperating Cache and Video storage

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3494]
My server is getting full and I wish to move videos which are not watched as much to a separate storage and leave on the main server only those most watched videos and where the cache can retrieve from a remote storage the needed files in case those are asked for. Can you provide some insight on this matter and would one approach the correct way to achieve this. I would like to have a script that can check videos based on their dates and move the video with its thumbnails to a separate storage space where it will be stored until it is searched for and than it a copy is moved to a local cache.

This will help to dynamically manage storage spaces and a good caching system to manage older content and make room to newer content.

Thank you for all the hard work.

**Comment by akhilleusuggo** [comment]
You're asking for too many things . You may want a reverse proxy ( with load balancing ) server for that to help you ''balance'' the storage and bandwidth .
But you still need the AVideo-Storage plugin .
The thumbnails should not move from the  /videos , anyway they weigh less then 5-50kb/each .

The other thing to work with is API development to move videos and host thumbnails on other server , for example on nextcloud or chevereto
