### ISSUE TITLE
Is there a way to track/record which users login and at what time?

### ISSUE THREAD

**Issue by timbo-la** [WWBN/AVideo#3496]
hope this is the correct place to the ask this question.

Is there a way to track/record which users login and at what time?

i know this could raise some privacy issues but i run a website for teaching nursery schools and have allocated them all login and password details anyway.

thanks for the help

Tim

**Comment by akhilleusuggo** [comment]
enable plugin audit

**Comment by timbo-la** [comment]
> enable plugin audit

thank you very much. 

Tim
