### ISSUE TITLE
Getting following error on my server

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3498]
Trying to see the stat of the server on http://fetube.flatearth.co.il/stat shows the following error:

Error loading stylesheet: Parsing an XSLT stylesheet failed
![Screen Shot 2020-08-11 at 21 40 59](https://user-images.githubusercontent.com/58882903/89935819-772eb980-dc1b-11ea-9142-70000013d79a.jpg)

**Comment by guymass** [comment]
Still getting this error:
Error loading stylesheet: Parsing an XSLT stylesheet failed.

**Comment by DanielnetoDotCom** [comment]
where?

![image](https://user-images.githubusercontent.com/18009293/93795831-542af880-fc10-11ea-8cd0-cc953a78042f.png)
