### ISSUE TITLE
Is there a setting to make the Title of videos on Embed to disappear?  

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3499]
I do not know if there is a option for this already I have not found it. Seems like all embedded videos show the Video Title at the top of the video and does not fade away.

Is it suppose to be static and if so will there in the future be a switch to change that?

<img src="https://static.buddylist.co/111111111.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
Suppose to go away on video play, check your JS console for errors.
or maybe you want to add a Custom CSS on the head to get away from it.

**Comment by JoshWho** [comment]
It is only on embed videos on other sites. works fine on the main website.

**Comment by DanielnetoDotCom** [comment]
what do you mean, sorry I do not understand.

This is only for embed videos. but it supposes to go away when it is playing as I mention.

**Comment by JoshWho** [comment]
Look on here for example https://www.joshwho.net/5-year-old-boy-executed-point-blank-by-criminal-thug-silence-from-national-media/

**Comment by DanielnetoDotCom** [comment]
I guess some JS on your page is breaking the JS that removes the top title.

but you can permanently remove it here 
![image](https://user-images.githubusercontent.com/18009293/90016828-002c0c00-dc81-11ea-94a8-5fe343b6e9ef.png)
