### ISSUE TITLE
Manually added subscription doesn't inactivate automatically

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3502]
Hey,

I noticed when you add a subscription plan manually for a user, it doesn't inactivate automatically when the plan is expired. you have to inactivate the plan manually. 

Thanks

**Comment by DanielnetoDotCom** [comment]
It does not suppose to activate or deactivate any user groups.

It will dynamically add user groups on its account if the subscription is active.

So in my opinion, the user should not have a user group active, the subscription plugin will handle the permission.

**Comment by tonuzo** [comment]
Ok, I see. So if a plan is expired it doesn't matter if it is still active... ?

**Comment by DanielnetoDotCom** [comment]
If the group is active, the user will remain in the group.
if you want the user to pay to be able to use the group, it should be inactive by default.

**Comment by tonuzo** [comment]
I noticed that user can't deactivate his/her subscription anymore. I remember that there was an option to do it on My Account > Subscription tab. This is important!

Br,
T

**Comment by DanielnetoDotCom** [comment]
why can't you deactivate the subscription?

I do not get it.

**Comment by tonuzo** [comment]
I mean if a user wants to cancel the subscription. It can't be done at the moment...

**Comment by DanielnetoDotCom** [comment]
Do you mean the recurrent payment?

It can be done on the payment gateway (PayPal)

For stripe, you can cancel on the My Account page

![image](https://user-images.githubusercontent.com/18009293/90519642-ade66180-e13e-11ea-971e-5fec99b6fe37.png)

**Comment by tonuzo** [comment]
I see. Thank you for the help..
