### ISSUE TITLE
delete an addition following the update

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3505]
hello @DanielnetoDotCom  i just updated can you tell me how to remove that

it's really horrible on the homepage

![image](https://user-images.githubusercontent.com/39193219/90029639-633a9480-dcbb-11ea-9e3d-bb710eeb4ddf.png)

**Comment by DanielnetoDotCom** [comment]
You can remove using a custom CSS

**Comment by syldri** [comment]
when I put that on it doesn't chew

.pagination {

    display: none;
}
