### ISSUE TITLE
duplication of videos

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3506]
I do tests on my demo site

when you scroll the page all videos are duplicated

![image](https://user-images.githubusercontent.com/39193219/90045655-a3a40d80-dccf-11ea-8ec1-9ae57836c11e.png)

**Comment by DanielnetoDotCom** [comment]
Can you reproduce it on demo site?

**Comment by syldri** [comment]
I show you two pictures

look where I got the red arrow

when I scroll the page

![image](https://user-images.githubusercontent.com/39193219/90049814-a9045680-dcd5-11ea-9acc-8f9f63b846b6.png)



![image](https://user-images.githubusercontent.com/39193219/90050014-eb2d9800-dcd5-11ea-8ca1-f67c86d8bb1f.png)

**Comment by akhilleusuggo** [comment]
I confirmed it yesterday . Duplication , even error on non existing categories

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by syldri** [comment]
I show you two pictures

some videos are missing in the default section

![image](https://user-images.githubusercontent.com/39193219/90061925-22587500-dce7-11ea-894e-73344f8d0f5a.png)

<br>
![image](https://user-images.githubusercontent.com/39193219/90062664-4d8f9400-dce8-11ea-9a37-5d2740e770e0.png)

**Comment by DanielnetoDotCom** [comment]
Thanks I found the bug

**Comment by syldri** [comment]
everything is working fine now

**Comment by akhilleusuggo** [comment]
Is not working fine . You fixed the first page , and broke the pages of the the videos ..
On all the pages /video/ID , shows all videos ( if your platform got 3k videos , then it will show 3000 videos )

**Comment by DanielnetoDotCom** [comment]
Is it fixed now?
