### ISSUE TITLE
Suggestion: FFMPEG HW Encoding on RaspberryPi4

### ISSUE THREAD

**Issue by maxlinux2000** [WWBN/AVideo#3509]
Hi, I just found out that the stock version of ffmpeg on RaspberryOS (debian 10 buster) has support for hardware encoding of h264 videos. It is specifically h264_omx.

I am testing it by automatically encoding hundreds of hours of videos, and the CPU does not reach 75º (in August in Spain with temperatures of 35º) and the speed is x2.5 - x3.5.

So, for those who have AVideo on a RaspberryPi4, I suggest you, to modify in AVideo-Encoder/Configuration MP4-LOW - MP4-SD - MP4-HD, the parameter,  from "`-c:v libx264`"  to "`-c:v h264_omx `".

![Captura de pantalla de 2020-08-13 11-38-22](https://user-images.githubusercontent.com/5683921/90119838-5f118400-dd5a-11ea-93f0-b463f48b7182.png)

regards
MaX

**Comment by akhilleusuggo** [comment]
yes , it's like quicksync
But the quality is potato compared to libx264 . 
Also the rate controller is bad . But yes , the HW is good ( for live-streaming only )

**Comment by maxlinux2000** [comment]
well, but it depends on the quality you want to achieve. For my audience, HD quality (1280x720) is the top of the range. For me a quality of 360p is normal.
And with ffmpeg the h264_omx encoder is regulated with the bitrate. The quality that is obtained is more than enough to watch videos on mobile phones. Clearly if you are talking about 4k movies, this encoder is insufficient ... but 4k on a raspberry exposed on the internet? :-)

**Comment by maxlinux2000** [comment]
but you are right... omx is no good enought for video resize, and reducing size.
But I have found another way

`nice -19 ffmpeg -i $pathFileName  -vf scale=-1:360  $destinationFile -y`

this simple and easy ffmpeg command can encode the video from 720p to 360p at 2.5X using ARMv6 NEON.

`    frame=64529 fps= 62 q=28.0 size=   84480kB time=00:44:48.83 bitrate= 257.4kbits/s dup=2 drop=0 speed=2.57x  `

**Comment by akhilleusuggo** [comment]
Yes , I have RaspberryPi4 and I can tell you that the best use of it , it's transcoding live-streams

**Comment by maxlinux2000** [comment]
Do you think that the RPI4 can be enough for hls in nginx-rtsp in a configuration similar?

            exec ffmpeg -i rtmp://localhost:1935/stream/$name
              -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 2500k -f flv -g 30 -r 30 -s 1280x720 -preset superfast -profile:v baseline rtmp://localhost:1935/hls/$name_720p2628kbs
              -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 1000k -f flv -g 30 -r 30 -s 854x480 -preset superfast -profile:v baseline rtmp://localhost:1935/hls/$name_480p1128kbs
              -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 750k -f flv -g 30 -r 30 -s 640x360 -preset superfast -profile:v baseline rtmp://localhost:1935/hls/$name_360p878kbs
              -c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 400k -f flv -g 30 -r 30 -s 426x240 -preset superfast -profile:v baseline rtmp://localhost:1935/hls/$name_240p528kbs
              -c:a libfdk_aac -b:a 64k -c:v libx264 -b:v 200k -f flv -g 15 -r 15 -s 426x240 -preset superfast -profile:v baseline rtmp://localhost:1935/hls/$name_240p264kbs;
        }

```
        application hls {
            live on;
            hls on;
            hls_fragment_naming system;
            hls_fragment 5;
            hls_playlist_length 10;
            hls_path /opt/data/hls;
            hls_nested on;

            hls_variant _720p2628kbs BANDWIDTH=2628000,RESOLUTION=1280x720;
            hls_variant _480p1128kbs BANDWIDTH=1128000,RESOLUTION=854x480;
            hls_variant _360p878kbs BANDWIDTH=878000,RESOLUTION=640x360;
            hls_variant _240p528kbs BANDWIDTH=528000,RESOLUTION=426x240;
            hls_variant _240p264kbs BANDWIDTH=264000,RESOLUTION=426x240;
        }
    }
}


```

**Comment by akhilleusuggo** [comment]
NOT with libx264 , but with h264_omx

**Comment by maxlinux2000** [comment]
IMPRESSIVE!! The ARMv6 NEON encoding from 720p to 360p at 3x with 75º of temperature after 16 hours  (with a little fan on the cpu...fan at 12V powered a 5V)

![Captura de pantalla de 2020-08-17 10-34-07](https://user-images.githubusercontent.com/5683921/90375647-89728280-e075-11ea-889f-af02a2d35df2.png)

**Comment by akhilleusuggo** [comment]
If you're live-streaming , you should not transcode at x3
Just add `-re` before `-i ` to set the speed at x1

I have a small cluster of RaspberryPi4 ( 3 of them ) , learning some new stuff from youtube , and I got to tell you that little thing can do a lot .

I got a dedicated '' server '' , it's a RaspberryPi4 ( 8GB RAM ) , tested the trascoding stuff and it's impressive  .

**Comment by maxlinux2000** [comment]
No, at the moment I'm doing live without multi-resolution hls.
As the data flow comes in, it goes out.
The live ones are in HD 25fps and bitrate at 1000kbs, a little low, but enough to have a decent quality.

What I'm experimenting with is AVideo-Encoder. I allow only HD videos to be uploaded, and with a "ffmpeg -c copy" I get the video to be available after a few seconds.
Then at night the raspberry takes care of compressing the videos to the other 2 resolutions (360p and 480p in my case).

The time will also come that I take care of live in hls with various resolutions. :-)
