### ISSUE TITLE
Application does not show images and the error in the file type

### ISSUE THREAD

**Issue by ricasht** [WWBN/AVideo#3513]
print the phone screen with the bug

**Comment by ricasht** [comment]
[https://drive.google.com/file/d/10QzWnDkWzGnbJ9r3GCrinlu2G1umycvz/view?usp=sharing](url)
[https://drive.google.com/file/d/1ITiRJkfTubsr6T37FFAjbbxCJD70Yr45/view?usp=sharing](url)

**Comment by DanielnetoDotCom** [comment]
Is the website working or just the app?

**Comment by ricasht** [comment]
on the website by the browser the videos already uploaded are working normally. but the app doesn’t show the images or touch the video, says the format is not supported

**Comment by DanielnetoDotCom** [comment]
Share your site URL here

**Comment by ricasht** [comment]
http://tchevideos.com.br/

**Comment by DanielnetoDotCom** [comment]
I can see your videos and images are unsecured

![image](https://user-images.githubusercontent.com/18009293/90313824-d889ad80-dee5-11ea-8f0f-04f155898e6a.png)

![image](https://user-images.githubusercontent.com/18009293/90313831-ea6b5080-dee5-11ea-8775-debc2db9feab.png)


Check your configuration.php or your customizeAdvanced plugin for any HTTP reference. replace it with HTTPS

**Comment by ricasht** [comment]
hello, where do I find this file?

**Comment by DanielnetoDotCom** [comment]
I am not sure how you configure it. but you must make sure it is all HTTPS

**Comment by ricasht** [comment]
I got it, thank you
