### ISSUE TITLE
Error in update

### ISSUE THREAD

**Issue by ricasht** [WWBN/AVideo#3514]
SoftException in Application.cpp:350: UID of script "/home/videos/public_html/view/index.php" is smaller than min_uid

**Comment by ricasht** [comment]
please, I have the platform stopped.

**Comment by DanielnetoDotCom** [comment]
Hi

I have no idea what is application.ccp

**Comment by ricasht** [comment]
Ok, I will update

**Comment by ricasht** [comment]
it worked, thank you very much.
