### ISSUE TITLE
Sorry! Your user has NOT been created!

### ISSUE THREAD

**Issue by ChisdealHDYT** [WWBN/AVideo#3515]
i moved over Website Server Provider to shared hosting and i have 2 sided, 1 encorder Server and other 1 mainly site hosting

but issue is when new user created i dont know what im doing wrong, because its not letting people creating accounts anymore when was working before.

any ideas what i messed up ended up stopping creating accounts.

![image](https://user-images.githubusercontent.com/18028479/90168197-a9aff200-dd94-11ea-8232-54eb20231703.png)

**Comment by DanielnetoDotCom** [comment]
Please update your code, I recently (hours ago) sent an update regarding this error

**Comment by ChisdealHDYT** [comment]
ah ok no worreis
