### ISSUE TITLE
encoder upload error

### ISSUE THREAD

**Issue by ricasht** [WWBN/AVideo#3516]
The conversion process is apparently ok, but the videos are not being added.

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by ricasht** [comment]
in the upload / videos folder, create the temporary files, the files disappear and nothing happens

**Comment by DanielnetoDotCom** [comment]
check encoder and streamer log files

**Comment by ricasht** [comment]
I checked the file avideo.log and youphptube.log in the plugin / videos folder, would these be log?

**Comment by ricasht** [comment]
![15978649787512397004933662718609](https://user-images.githubusercontent.com/69056431/90680480-47456e80-e238-11ea-82cf-14377d4f148f.jpg)

**Comment by ricasht** [comment]
it creates temporary files as shown in the image above, then it deletes the files and does not add to the final videos

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

You may have ffmpeg issues , or transfer issues . But without pasting here the logs , nobody can help you .
Upload the logs ( hide the sensitive information ) , or copy-past the latest logs when the error happens .
