### ISSUE TITLE
OG image is not large enough for Facebook to use

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3522]
Look at this link in the facebook debugger.

https://www.joshwhotv.com/video/24876/shadowgate-documentary---film-by-millie-weaver

https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.joshwhotv.com%2Fvideo%2F24876%2Fshadowgate-documentary---film-by-millie-weaver

```
<meta property="og:image" content="https://www.joshwhotv.com/videos/_YPTuniqid_5f382222e382f0.84407186.jpg?1597521264" />
--
  | <meta property="og:image:secure_url" content="https://www.joshwhotv.com/videos/_YPTuniqid_5f382222e382f0.84407186.jpg?1597521264" />
  | <meta property="og:image:type" content="image/jpeg" />
  | <meta property="og:image:width" content="336" />
  | <meta property="og:image:height" content="188" />
  | <meta property="fb:app_id" content="774958212660408" />
  | <meta property="og:title" content="SHADOWGATE DOCUMENTARY - film by Millie Weaver" />
  | <meta property="og:description" content="Millie Weaver was finishing her documentary #ShadowGate about the deep state when a grand jury decided to indict her for “burglary.” Here is the trailer #FreeMillie" />
  | <meta property="og:url" content="https://www.joshwhotv.com/video/24876/shadowgate-documentary---film-by-millie-weaver" />
  | <meta property="og:type" content="video.other" />
  | <meta property="og:video" content="https://www.joshwhotv.com/video/24876/shadowgate-documentary---film-by-millie-weaver" />
  | <meta property="og:video:secure_url" content="https://www.joshwhotv.com/video/24876/shadowgate-documentary---film-by-millie-weaver" />
  | <meta property="video:duration" content="4929" />
  | <meta property="duration" content="4929" />
```

The image is too small for facebook to use it so it picks a random one to use.

**Comment by DanielnetoDotCom** [comment]
I notice this some time ago, and now if your image is smaller then 200px it will be resized, so it will attend the FB minimum size.

FYI, I could not detect this message in your link, and also there is no small image on it. Check the image directly, it is a large one https://www.joshwhotv.com/videos/_YPTuniqid_5f382222e382f0.84407186.jpg

I do not think FB is expecting an image larger than that

![image](https://user-images.githubusercontent.com/18009293/90321330-fcb5b080-df1e-11ea-8368-210c28c0aa5c.png)

**Comment by JoshWho** [comment]
The direct image doesn't look large https://www.joshwhotv.com/videos/_YPTuniqid_5f382222e382f0.84407186.jpg?1597521264

**Comment by DanielnetoDotCom** [comment]
We are not seeing the same image, please try another browser.
I just opened and it is a large one.

and now in case of an image with 180px on any side, it will be resized.

**Comment by JoshWho** [comment]
post the image link you are looking at. I just tried on 2 seperate computers shows the same

**Comment by DanielnetoDotCom** [comment]
so why is it showing 1500x850 for me?

Tested on Firefox and Chrome

![image](https://user-images.githubusercontent.com/18009293/90321632-ebba6e80-df21-11ea-993c-b9af69faed7d.png)

**Comment by JoshWho** [comment]
Because that is not where the OG image tag is. Look at the image link for OG

**Comment by JoshWho** [comment]
Still shows this in the meta


```
<meta property="og:image" content="https://www.joshwhotv.com/videos/_YPTuniqid_5f382222e382f0.84407186.jpg?1597521264" />
--
  | <meta property="og:image:secure_url" content="https://www.joshwhotv.com/videos/_YPTuniqid_5f382222e382f0.84407186.jpg?1597521264" />
  | <meta property="og:image:type" content="image/jpeg" />
  | <meta property="og:image:width" content="336" />
  | <meta property="og:image:height" content="188" />

```

**Comment by JoshWho** [comment]
Just noticed. WHen I upload a new thumb it still keeps the same URL. That is not good when caching

**Comment by JoshWho** [comment]
I just purged the cache and now I can see the new thumbnail

**Comment by JoshWho** [comment]
I thought images uploaded with unique URLs?

**Comment by DanielnetoDotCom** [comment]
Maybe FB is seeing a cached page.

Make sure it is uncheked

![image](https://user-images.githubusercontent.com/18009293/90321821-c9c1eb80-df23-11ea-8f5e-bfc69792cb5a.png)

**Comment by JoshWho** [comment]
I have that enabled. It has been enabled for 3 months now.

**Comment by DanielnetoDotCom** [comment]
Maybe is showing a 3 months old image.

disable and request to examine it again on FB

**Comment by JoshWho** [comment]
It is showing the one I added after purging. 

Images need to all be unique or I cannot fight bots with caching. THis is going to be an issue every time a user wants to change their thumbnail I am going to have to purge the CDN and the site.

**Comment by DanielnetoDotCom** [comment]
what makes them unique is the timestamp at the end 

https://www.joshwhotv.com/videos/_YPTuniqid_5f382222e382f0.84407186.jpg?**1597521264**

**1597521264** is the timestamp that changes every time you update.

**Comment by JoshWho** [comment]
I changed the image 3 times keeps the same time stamp.

**Comment by JoshWho** [comment]
My server caching ignores query strings.

**Comment by DanielnetoDotCom** [comment]
To change the timestamp you must clear the cache.

**Comment by JoshWho** [comment]
how would a normal user do this without me doing it?

**Comment by DanielnetoDotCom** [comment]
I do not know how your Cloudflare cache works, but the browser cache and the Streamer cache can handle that when an image is updated

**Comment by JoshWho** [comment]
I currently now have it set for clear cache on images every 30 minutes is a low as I can put it. People will just have to wait for the update. Would be kewl in the future if you can add a random string before the file name and that will completely bypass the cache.

**Comment by DanielnetoDotCom** [comment]
I really do not think you need to reduce that cache.

If it does not change the timestamp is because you are caching the page HTML, not the image. the time stamp change force the image to update

**Comment by JoshWho** [comment]
it updates now every 30 minutes. Has to do something with the cache. I only cache images for the video directory Objects and everything I have on a different cache rule.
