### ISSUE TITLE
Send Stream to Encoder

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3523]
I don't know why I'm having this , but when stream is over , is sent to the streamer site . The streamer site does downloads it , but into the RAM . If the stream is too large , I guess it should give a fatal error memory . Instead , it gives this error : 

```
[Sun Aug 16 04:20:19.575890 2020] [php7:notice] [pid 27921] [client IP:44226] PING ==> fileAge = 787 AND lifetimeSeconds = 30
[Sun Aug 16 04:20:20.202923 2020] [php7:notice] [pid 27920] [client IP:44230] PING ==> fileAge = 787 AND lifetimeSeconds = 30
[Sun Aug 16 04:20:20.787906 2020] [php7:notice] [pid 27928] [client IP:44236] PING ==> fileAge = 786 AND lifetimeSeconds = 30
[Sun Aug 16 04:34:56.908057 2020] [php7:notice] [pid 27947] [client IP:50198] SCORE ==> fileAge = 876 AND lifetimeSeconds = 60
[Sun Aug 16 04:34:56.965694 2020] [php7:notice] [pid 27918] [client IP:16208] PING ==> fileAge = 877 AND lifetimeSeconds = 30
[Sun Aug 16 04:34:57.641274 2020] [php7:notice] [pid 27958] [client IP:21084] PING ==> fileAge = 878 AND lifetimeSeconds = 30
[Sun Aug 16 04:34:58.292646 2020] [php7:notice] [pid 27916] [client IP:54218] PING ==> fileAge = 878 AND lifetimeSeconds = 30
[Sun Aug 16 04:34:58.909229 2020] [php7:notice] [pid 27956] [client IP:52088] PING ==> fileAge = 878 AND lifetimeSeconds = 30

Fatal error: Maximum execution time of 30+2 seconds exceeded (terminated) in /var/www/html/AVideo/objects/functions.php on line 1922
```

I'm not sure if there were some modifications on the on the way the streamer site gets the files now , but I don't remember it was dumping it on the RAM .

And the execution time , I don't understand it .

PS : I've changed the max_execution time to something higher , but still , the RAM thing , I would like to understand better how the getRecordedFile.php sends the streams

**Comment by DanielnetoDotCom** [comment]
It is a file_get_contents command, how big is the expected file?

but maybe the live server is taking a too long time to respond, I do not think this function times out if is receiving content.

does your getRecordedFIle.php has this?

https://github.com/WWBN/AVideo/blob/a9175082ab0c98d63fe9d08c0c1bc362549a456c/plugin/Live/getRecordedFile.php#L37

I mean the 

```
$fp = fopen($filename, 'rb');
fpassthru($fp);
```

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom yes , does have . I remember when it didn't had it , the RAM just blows up the server yes . Not anymore .
```
$fp = fopen($filename, 'rb');
fpassthru($fp);
```

The issue is not on the live-stream server , I have them hosted on different servers .
Is only when sending to stream server . So the stream server got basically full usage of RAM . ( NOT the live-stream server , but the stream server ( the local ) )

> how big is the expected file?

Depends , but usually between 6GB-15GB files .

**Comment by DanielnetoDotCom** [comment]
Ok, I just sent an update to the serdRecordedToEncoder plugin v2.1, the timeout was not set, but I guess it is required for larger files.

Not we have a longer time out on the download process.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I need you to help me debug some thing here : 

If the stream is too large , the transfer fails : 

rtmp-nginx logs : 

```
2020/08/28 15:16:51 [info] 9045#0: *15065 notify: record_done recorder=video path='/var/www/tmp/ID-28-Aug-20-12:42:18.flv' url='example.com/plugin/Live/on_record_done.php'
*15087 FastCGI sent in stderr: "PHP message: getRecordedFile: Start
PHP message: getRecordedFile: /var/www/tmp/ID-28-Aug-20-12:42:18.flv 10588347986" while reading response header from upstream, client: IP, server: example.com, request: "GET /getRecordedFile.php?file=ID-28-Aug-20-12%3A42%3A18 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "examplecom:8443"
2020/08/28 15:16:52 [warn] 9045#0: *15087 an upstream response is buffered to a temporary file /usr/local/nginx/fastcgi_temp/7/00/0000000007 while reading upstream, client: IP, server: example.com, request: "GET /getRecordedFile.php?file=ID-28-Aug-20-12%3A42%3A18 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "example.com:8443"
*15087 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too (104: Connection reset by peer) while reading upstream, client: IP, server: example.com, request: "GET /getRecordedFile.php?file=ID-28-Aug-20-12%3A42%3A18 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "example.com:8443"
```

Apache2 logs ( nothing ! ) : 

```
[Fri Aug 28 15:21:31.504046 2020] [php7:notice] [pid 8423] [client IP:29970] SCORE ==> fileAge = 811 AND lifetimeSeconds = 60
[Fri Aug 28 15:21:31.624208 2020] [php7:notice] [pid 26363] [client IP:40654] PING ==> fileAge = 813 AND lifetimeSeconds = 30
[Fri Aug 28 15:21:32.324408 2020] [php7:notice] [pid 8566] [client IP:20896] PING ==> fileAge = 813 AND lifetimeSeconds = 30
[Fri Aug 28 15:21:33.000928 2020] [php7:notice] [pid 10128] [client IP:21790] PING ==> fileAge = 813 AND lifetimeSeconds = 30
```

Avideo.log : 

```
[28-Aug-2020 15:16:51 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/plugin/Live/on_record_done.php) FROM: IP Browser:  SCRIPT_NAME: /plugin/Live/on_record_done.php
[28-Aug-2020 15:16:51 UTC] AVideoLog::DEBUG: Record Finish SCRIPT_NAME: /plugin/Live/on_record_done.php
[28-Aug-2020 15:16:51 UTC] AVideoLog::DEBUG: NGINX on_record_done POST: {"app":"live","flashver":"FMLE\/3.0 (compatible; FMSc\/1.0)","swfurl":"rtmp:\/\/example.com\/live?p=hashedpass","tcurl":"rtmp:\/\/example.com\/live?p=hashedpass","pageurl":"","addr":"IP","clientid":"ID","call":"record_done","recorder":"video","name":"ID","path":"\/var\/www\/tmp\/ID-Aug-20-12:42:18.flv","redirectUri":""} SCRIPT_NAME: /plugin/Live/on_record_done.php
[28-Aug-2020 15:16:51 UTC] AVideoLog::DEBUG: NGINX on_record_done GET: [] SCRIPT_NAME: /plugin/Live/on_record_done.php
[28-Aug-2020 15:16:51 UTC] AVideoLog::DEBUG: NGINX on_record_done php://inputapp=live&flashver=FMLE/3.0%20(compatible%3B%20FMSc/1.0)&swfurl=rtmp://example.com/live%3Fp=hashedpass&tcurl=rtmp://example.com/live%3Fp=hashedpass&pageurl=&addr=IP&clientid=ID&call=record_done&recorder=video&name=ID&path=/var/www/tmp/ID-28-Aug-20-12:42:18.flv SCRIPT_NAME: /plugin/Live/on_record_done.php
[28-Aug-2020 15:16:51 UTC] AVideoLog::DEBUG: user::login: noPass = 1, encodedPass = , this->user, USER IP SCRIPT_NAME: /plugin/Live/on_record_done.php
[28-Aug-2020 15:16:51 UTC] AVideoLog::DEBUG: user::login: onUserSignIn Done SCRIPT_NAME: /plugin/Live/on_record_done.php
[28-Aug-2020 15:16:51 UTC] AVideoLog::DEBUG: on_record_done: File (/var/www/tmp/ID-28-Aug-20-12:42:18.flv) does not exists get it remotely (https://example.com:8443/getRecordedFile.php?file=ID-28-Aug-20-12%3A42%3A18)  SCRIPT_NAME: /plugin/Live/on_record_done.php
[28-Aug-2020 15:16:51 UTC] AVideoLog::DEBUG: url_get_contents: Start example.com:8443/getRecordedFile.php?file=ID-28-Aug-20-12%3A42%3A18, , 3600 SCRIPT_NAME: /plugin/Live/on_record_done.php
[28-Aug-2020 15:16:51 UTC] AVideoLog::DEBUG: url_get_contents: no timout https://example.com:8443/getRecordedFile.php?file=ID-28-Aug-20-12%3A42%3A18 SCRIPT_NAME: /plugin/Live/on_record_done.php
[28-Aug-2020 15:16:51 UTC] AVideoLog::DEBUG: url_get_contents: allow_url_fopen https://example.com:8443/getRecordedFile.php?file=ID-28-Aug-20-12%3A42%3A18 SCRIPT_NAME: /plugin/Live/on_record_done.php
```

**Comment by DanielnetoDotCom** [comment]
Basically this is what I see strange:

`epoll_wait() reported that client prematurely closed connection`

check this: https://stackoverflow.com/questions/36488688/nginx-upstream-prematurely-closed-connection-while-reading-response-header-from

Looks like you may need to increase the timeout

```
location / {
    proxy_read_timeout 300s;
    proxy_connect_timeout 75s;
    proxy_pass http://localhost:3000;
}
```

**Comment by akhilleusuggo** [comment]
I can asure you that it's related to the RAM . How can I make the transfer go thru wget ?
Because with your method , the transfer is dumping into the ram . You can try it by yourself . Try to send to the stream site something bigger then the RAM , will give this same issue .

But with wget , the files will be downloaded on the disk , no issues will happens .

**Comment by DanielnetoDotCom** [comment]
Are you sure you are using the fpassthru ?

https://github.com/WWBN/AVideo/blob/f9bbbdb375aeb518417ca2ed55bacaa77ecc14ab/plugin/Live/getRecordedFile.php#L37

If yes, I am not sure if it supposes to consume your RAM like this

https://stackoverflow.com/questions/432713/serving-large-files-with-php

Based here this is the best method

https://www.garfieldtech.com/blog/readfile-memory


Wget does not apply here because we need to secure the files. so PHP must handle if the file will be delivered or not

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom What do you mean secure the file ? I'm able to download it from the browser by just acceding to example.com:8443/getRecordedFile.php?file=ID-28-Aug-20-12%3A42%3A18 . Why the script can't do it ?

This is my file conf . 

```
<?php
//die("Remove the line ".__LINE__." to use this script "); // remove this line so the script will work
error_log("getRecordedFile: Start ");
$record_path = "/var/www/tmp/"; //update this URL

if (empty($_REQUEST['file'])) {
    error_log("getRecordedFile: file not found {$_REQUEST['file']} ");
    die('file not found');
}
$file = preg_replace("/[^0-9a-z_:-]/i", "", $_REQUEST['file']);

ini_set('memory_limit', '-1');
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$filename = $record_path . $file . ".flv";
if(!file_exists($filename)){
    error_log("getRecordedFile: file does not exists {$filename} ");
    die('file does not exists');
}
$size = filesize($filename);
error_log("getRecordedFile: $filename ". filesize($filename));

header('Content-Description: File Transfer');
header('Content-Disposition: attachment; filename=' . $file . ".flv");
header('Content-Transfer-Encoding: binary');
header('Connection: Keep-Alive');
header('Expires: 0');
header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
header('Pragma: public');
header('Content-Type: video/x-flv');
header('Content-Length: ' . $size);

// stream the file
$fp = fopen($filename, 'rb');
fpassthru($fp);
error_log("getRecordedFile: $filename finish ");
unlink($filename); // uncomment this for autodelete, or create a crontab to delete old files
// Auto delete files older than 7 days
//@daily root find /var/www/tmp/*.flv -mtime +6 -type f -delete
```

What should I add or remove ?

**Comment by DanielnetoDotCom** [comment]
> What do you mean secure the file ? 

Like the nginx will not record the file in a public folder

> I'm able to download it from the browser by just acceding to example.com:8443/getRecordedFile.php?file=ID-28-Aug-20-12%3A42%3A18

If this is happening the issue is on your streamer side, NOT in the Storage.


But to have a better idea is important to see what happen after the log line 

`[28-Aug-2020 15:16:51 UTC] AVideoLog::DEBUG: url_get_contents: allow_url_fopen`

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 

> If this is happening the issue is on your streamer side, NOT in the Storage.

What do you mean with streamer ? Live-Stream server ?
And what do you mean with Storage ? streamer ( AVideo ) or YTP-Storage ?

> But to have a better idea is important to see what happen after the log line
> 
> [28-Aug-2020 15:16:51 UTC] AVideoLog::DEBUG: url_get_contents: allow_url_fopen

Nothing happens . No logs at all ... I mean , where should the error be ? /var/logs/apache2/error.log ( empty )
On AVideo.log aparently the log file does not cover in case of failure .

**Comment by DanielnetoDotCom** [comment]
> What do you mean with streamer ? Live-Stream server ?
> And what do you mean with Storage ? streamer ( AVideo ) or YTP-Storage ?

I mean the AVideo site, that is the one that supposes to transfer the file

> Nothing happens . No logs at all ... I mean , where should the error be ? /var/logs/apache2/error.log ( empty )
> On AVideo.log aparently the log file does not cover in case of failure .

Maybe the error is not right after the line I told you. some times takes several minutes before rising an error

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Is there any command line tool to request a live-stream to be sent to the encoder ?
In this way I can ask the live-stream server every time to have more opportunities to debug ?

https://github.com/WWBN/AVideo/blob/master/plugin/Live/commandLineSendAllRecordedToEncoder.php

So , replacing ( what should be replaced ) , how to execute ? Like the files hosted on /install ? with php blabla.php ?
Probably you should move this file to the /install directory .

**Comment by DanielnetoDotCom** [comment]
Humm, this should work with the recorder files.

I forgot about it but definitely looks correct. I guess you can copy it in your Live server and execute it with `php blabla.php`

**Comment by akhilleusuggo** [comment]
From any directory ? Or it should be on html folder ?
BTW , I didn't even knew that it should be on the live-stream server .

**Comment by DanielnetoDotCom** [comment]
Yes, put in on the Live server

make sure you add the correct paths here, let me correct the comment so it will be clear for you

```
$record_path = "/var/www/tmp/";
$liveServerURL = "live.avideo.com"; // your live server domain
$streamerServerURL = "https://demo.avideo.com/"; // your streamer server URL
$secretRecorderKey = "4cbcfa558757b9593f9b0d0778385828"; // must match with the plugin parameter
```

![image](https://user-images.githubusercontent.com/18009293/91625478-225ea300-e97e-11ea-86c0-6559e871e1c7.png)

**Comment by akhilleusuggo** [comment]
Very strange , nothing happens at all ...
Nothing on logs neither .
btw , are you sure about the `$liveServerURL = "live.avideo.com"; // your live server domain`

No port specification ? No protocol ? Because on the logs it's showing with protocols and port .
`on_record_done: File (/var/www/tmp/ID-28-Aug-20-12:42:18.flv) does not exists get it remotely (https://example.com:8443/getRecordedFile.php?file=ID-28-Aug-20-12%3A42%3A18)  SCRIPT_NAME: /plugin/Live/on_record_done.php` This is from previous logs .

PS :  I've tried with port and protocol and nothing .

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/blob/f9bbbdb375aeb518417ca2ed55bacaa77ecc14ab/plugin/Live/commandLineSendAllRecordedToEncoder.php#L24

Following with this line , no port or protocol should be specified , since the line will generate it .

**Comment by DanielnetoDotCom** [comment]
If there are files on `$record_path = "/var/www/tmp/"; ` and your filenames are in the format  `5cf513d058960-25-Aug-20-23:29:58.flv`
it should return something. 

this is your domain `$liveServerURL = "live.avideo.com";`
![image](https://user-images.githubusercontent.com/18009293/91625948-9a7a9800-e981-11ea-9178-5fc4e38853d8.png)

On this `$streamerServerURL = "https://demo.avideo.com/";` make sure you have the last slash
