### ISSUE TITLE
Categories editing doesn't work anymore

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3524]
Hey,

I noticed that categories editing option is broken. You can edit categories but the changes do not save. Also you cant set parent category. 

Categories don't work on demo site either.

![image](https://user-images.githubusercontent.com/63721378/90332025-359e6580-dfb1-11ea-945a-1948fbc79585.png)

**Comment by akhilleusuggo** [comment]
I confirm

**Comment by akhilleusuggo** [comment]
also the add playlist ( favorite and watch later not working ) 

```
SCRIPT_NAME: /objects/playListAddVideo.json.php
[18-Aug-2020 05:58:22 UTC] AVideoLog::ERROR: Error in writeSql : (1048) Column 'playlists_id' cannot be null, SQL-CMD:INSERT INTO playlists_has_videos ( playlists_id, videos_id , `order`) VALUES (?, ?, ?)  SCRIPT_NAME: /objects/playListAddVideo.json.php
```

**Comment by tonuzo** [comment]
More info about Categories: when you edit and save it doesn't do much, but later I checked again the edits have taken place.  That's odd, but can there be something about database connection.. I don't know, just a guess..

**Comment by DanielnetoDotCom** [comment]
Sorry for that, here is a Fix

**Comment by tonuzo** [comment]
Ok thanks.
