### ISSUE TITLE
For performance reasons, max rows cannot be null or greater then 100

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#3526]
After latest update, when I login as "Admin" I get this message.  If I sign in as a user it doesn't show this message.
Happens on PC and Mobile.

![Up-Next](https://user-images.githubusercontent.com/65576427/90337512-62567b00-dfb9-11ea-95eb-5637436c45aa.png)

Thanks

**Comment by akhilleusuggo** [comment]
It appears only on admin , it's not a bug 

https://github.com/WWBN/AVideo/issues/3517#issuecomment-673783181

**Comment by DanielnetoDotCom** [comment]
It will be removed soon.

**Comment by D-Spayre** [comment]
Thank you
