### ISSUE TITLE
Video is not added on Encoder

### ISSUE THREAD

**Issue by yasiriqbal1** [WWBN/AVideo#3528]
Dear All,
Our youphptube working perfectly fine till i have chanaged the stream IP. After changing the IP address of the server old videos are playing fine but we cannot upload video on the encoder. The issue os very strange, when we click on the add files button and select the video file , the video cannot be added in the uploading area. I have seen all the logs but their is not error shown in the streamer logs as well as encoder aviadeo.log and youphptube.errro.log.

Please help to solve the issue.

**Comment by DanielnetoDotCom** [comment]
check the configuration.php from the encoder

**Comment by yasiriqbal1** [comment]
Dear
I have not seen any configuration error on the encoder file. File is given below

<?php
$global['configurationVersion'] = 2;
$global['webSiteRootURL'] = 'http://172.16.2.14/upload/';
$global['systemRootPath'] = '/var/www/YouPHPTube/upload/';
$global['webSiteRootPath'] = '';

$global['disableConfigurations'] = false;
$global['disableBulkEncode'] = false;
$global['disableImportVideo'] = false;
$global['disableWebM'] = false;

$mysqlHost = 'localhost';
$mysqlUser = 'encoder';
$mysqlPass = 'pof@123';
$mysqlDatabase = 'YouPHPTubeEncoder';

$global['allowed'] = array('mp4', 'avi', 'mov', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv', 'mpg', 'mpeg', 'f4v', 'm4v', 'm4a', 'm2p', 'rm', 'vob', 'mkv', '3gp');
/**
 * Do NOT change from here
 */
if(empty($global['webSiteRootPath'])){
    preg_match('/https?:\/\/[^\/]+(.*)/i', $global['webSiteRootURL'], $matches);
    if(!empty($matches[1])){
        $global['webSiteRootPath'] = $matches[1];
    }
}
if(empty($global['webSiteRootPath'])){
    die('Please configure your webSiteRootPath');
}


require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by yasiriqbal1** [comment]
<?php
$global['configurationVersion'] = 2;
$global['webSiteRootURL'] = 'http://172.16.2.14/upload/';
$global['systemRootPath'] = '/var/www/YouPHPTube/upload/';
$global['webSiteRootPath'] = '';

$global['disableConfigurations'] = false;
$global['disableBulkEncode'] = false;
$global['disableImportVideo'] = false;
$global['disableWebM'] = false;

$mysqlHost = 'localhost';
$mysqlUser = 'encoder';
$mysqlPass = 'pof@123';
$mysqlDatabase = 'YouPHPTubeEncoder';

$global['allowed'] = array('mp4', 'avi', 'mov', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv', 'mpg', 'mpeg', 'f4v', 'm4v', 'm4a', 'm2p', 'rm', 'vob', 'mkv', '3gp');
/**
 * Do NOT change from here
 */
if(empty($global['webSiteRootPath'])){
    preg_match('/https?:\/\/[^\/]+(.*)/i', $global['webSiteRootURL'], $matches);
    if(!empty($matches[1])){
        $global['webSiteRootPath'] = $matches[1];
    }
}
if(empty($global['webSiteRootPath'])){
    die('Please configure your webSiteRootPath');
}


require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by yasiriqbal1** [comment]
> Dear
> I have not seen any configuration error on the encoder file. File is given below

<?php
$global['configurationVersion'] = 2;
$global['webSiteRootURL'] = 'http://172.16.2.14/upload/';
$global['systemRootPath'] = '/var/www/YouPHPTube/upload/';
$global['webSiteRootPath'] = '';

$global['disableConfigurations'] = false;
$global['disableBulkEncode'] = false;
$global['disableImportVideo'] = false;
$global['disableWebM'] = false;

$mysqlHost = 'localhost';
$mysqlUser = 'encoder';
$mysqlPass = 'pof@123';
$mysqlDatabase = 'YouPHPTubeEncoder';

$global['allowed'] = array('mp4', 'avi', 'mov', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv', 'mpg', 'mpeg', 'f4v', 'm4v', 'm4a', 'm2p', 'rm', 'vob', 'mkv', '3gp');
/**
 * Do NOT change from here
 */
if(empty($global['webSiteRootPath'])){
    preg_match('/https?:\/\/[^\/]+(.*)/i', $global['webSiteRootURL'], $matches);
    if(!empty($matches[1])){
        $global['webSiteRootPath'] = $matches[1];
    }
}
if(empty($global['webSiteRootPath'])){
    die('Please configure your webSiteRootPath');
}


require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by yasiriqbal1** [comment]
> Dear
> I have not seen any configuration error on the encoder file. File is given below

**Comment by yasiriqbal1** [comment]
[configuration.txt](https://github.com/WWBN/AVideo/files/5088939/configuration.txt)

**Comment by DanielnetoDotCom** [comment]
You should share your log, NOT your configuration.php (with your pass)

**Comment by yasiriqbal1** [comment]
Dear,
When I click on '+ Add files' green button; then, selecting the files and click 'open', the dialog box closes and no files show under the form for uploading. I looked at the console for errors and I found the following, can someone direct me to where I can find the cause of this issue.

jQuery.Deferred exception: Cannot read property 'createObjectURL' of undefined TypeError: Cannot read property 'createObjectURL' of undefined at $.<computed>.<computed>.loadVideo (http://10.10.1.123/encoder/view/jquery-file-upload/js/jquery.fileupload-video.js:89:37) at $.<computed>.<computed>.func (http://10.10.1.123/encoder/view/jquery-file-upload/js/jquery.fileupload-process.js:84:65) at j (http://10.10.1.123/encoder/view/js/jquery-3.2.0.min.js:2:29999)

**Comment by yasiriqbal1** [comment]
Dear,
I am facing this issue on the pc which have no internet. We have to deployed this setup on a network which is not part of internet.

**Comment by DanielnetoDotCom** [comment]
Please check your JS console for errors.

FYI, I saw an error like this before, and the problem was a wrong URL on the configuration.php file

In your case the `$global['webSiteRootURL']` must be visible even without Internet connection.

**Comment by yasiriqbal1** [comment]
Dear,
I have verified the configuration and thier is no issue in it.

**Comment by DanielnetoDotCom** [comment]
If you want you can share with us, so we can try to help you.

**Comment by yasiriqbal1** [comment]
Dear,
How you will help me, means can i give you the server access and most important will you charge for this or not.

**Comment by DanielnetoDotCom** [comment]
If you want to direct support, you need to hire us, you can email us at developer@youphptube.com

Otherwise, you will need to share the information (log NOT credentials) here on Github

**Comment by yasiriqbal1** [comment]
Dear,
I have access the same server from the client which have internet and every this working fine. Can you please help why the same server is not uploading the video when i access it from the client which do not have internet access.

**Comment by yasiriqbal1** [comment]
Please check my JS console for errors.

GET https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css net::ERR_NAME_RESOLUTION_FAILED
?justLogin=1:311 GET https://blueimp.github.io/JavaScript-Templates/js/tmpl.min.js net::ERR_NAME_RESOLUTION_FAILED
?justLogin=1:313 GET https://blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js net::ERR_NAME_RESOLUTION_FAILED
?justLogin=1:315 GET https://blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js net::ERR_NAME_RESOLUTION_FAILED
?justLogin=1:317 GET https://blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js net::ERR_NAME_RESOLUTION_FAILED
jquery-3.2.0.min.js:2 jQuery.Deferred exception: Cannot read property 'createObjectURL' of undefined TypeError: Cannot read property 'createObjectURL' of undefined
    at $.<computed>.<computed>.loadVideo (http://172.16.2.14/upload/view/jquery-file-upload/js/jquery.fileupload-video.js:89:37)
    at $.<computed>.<computed>.func (http://172.16.2.14/upload/view/jquery-file-upload/js/jquery.fileupload-process.js:84:65)
    at j (http://172.16.2.14/upload/view/js/jquery-3.2.0.min.js:2:29999)
    at k (http://172.16.2.14/upload/view/js/jquery-3.2.0.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery-3.2.0.min.js:2 k @ jquery-3.2.0.min.js:2
setTimeout (async)(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2 add @ jquery-3.2.0.min.js:2
(anonymous) @ jquery-3.2.0.min.js:2 Deferred @ jquery-3.2.0.min.js:2
then @ jquery-3.2.0.min.js:2 (anonymous) @ jquery.fileupload-process.js:90
each @ jquery-3.2.0.min.js:2
_processFile @ jquery.fileupload-process.js:78
(anonymous) @ jquery.ui.widget.js:148
func @ jquery.fileupload-process.js:153
j @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2

**Comment by yasiriqbal1** [comment]
dear problem solved by copying the files on local server
