### ISSUE TITLE
support for webm ( gifs ) ?

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3529]
Hello , how can I add support to the webm for gifs ?
I wanna replace the webp ( they are too heavy and low quality ) . I wanna use vp9 lib , the resaults are greate ( it is slow , but reduces the size by 50-70% with 30FPS ( instead of 10 that we have ) .

But I need to change or add the webm gif support . Like this : 

`<source src="mygif.webm" type="video/webm">`

The question is where ? Can anyone point me to do this right ?

---

On the encoder I just have to change some few lanes like ; 

`$exec ="ffmpeg -y -ss 3 -t 3 -i \"{$url}\" -vcodec libwebp -lossless 1 -vf fps=10,scale=640:-1 -q 60 -preset default -loop 0 -an -vsync 0 {$destination}";`

**Comment by akhilleusuggo** [comment]
This is an example of comparison between the webp ( the one we're using ) , and the webm gif 

![image](https://user-images.githubusercontent.com/52116577/90373414-8c23a680-e07a-11ea-92b8-8cd4de26dc3f.png)

Basically 4 times less space , at x3 times more fps

here I uploaded so you can take a look . 

WEBM : https://cdn.discordapp.com/attachments/675957893530517509/744831230335516742/test.webm (184KB , 480p-30FPS)
WEBP : https://cdn.discordapp.com/attachments/675957893530517509/744831493959843880/test.webp ( 829KB , 480p-10FPS)

**Comment by DanielnetoDotCom** [comment]
Humm, but this will use a video tag instead of an image tag?

I like that, but it will require encoder change and many places on the streamer to change.

Unfortunately, it is not that easy, but I will add it to my notes.

If you want you can start adding support to the encoder to create and transfer this file to the streamer.

then need to change the streamer to recognize the file and then add it to the layouts.

**Comment by akhilleusuggo** [comment]
I've already worked it out on my home server , but no luck . The webm are generated , but are not reproduced . Error 403 , file not found

**Comment by DanielnetoDotCom** [comment]
As I understand, the webm has to be played in a video tag.

We already have webm support for videos, but it takes a long time to encode

**Comment by akhilleusuggo** [comment]
the webm takes longer yes .
it's like the x264 ( but supported on HTML )
But there's some tunes and presets to make it faster . As for me , i'll go when the slowest to safe space , so the CDN can cache everything and very quick load pages .

**Comment by akhilleusuggo** [comment]
Can you indicate me where on the script is the tag page ?

**Comment by akhilleusuggo** [comment]
so the problem is that , it detects it as a video , not as a gif 

![image](https://user-images.githubusercontent.com/52116577/90397720-f3545180-e0a0-11ea-9b48-edac6aaeebb7.png)

**Comment by DanielnetoDotCom** [comment]
You are right.

I can see at least 3 steps to make it work. (probably more)

1. maybe you can use a different file name for the webm (if you want to use it as a thumbs), for example, {filename}_thumbs.webm

2. change the method Video:getImageFromFilename_() to be able to detect your new files https://github.com/WWBN/AVideo/blob/e999074bb37bfea7abb1e80d688b35c021b9ce1d/objects/video.php#L2766

3. you will need to change the Plugin (Gallery/YouPHPFlix2 ) to recognize this file as a thumbs and use a video tag on it instead a IMG tag
