### ISSUE TITLE
sitemap timeout

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3530]
Every time someone visits the /sitemap ( usually a bot ) , it starts generating the sitemap . This is not a problem for small sites , but when you have +5000k videos , it starts taking a lot of time .

Anyway to avoide re-creating the sitemap every visit ? Can we add a 6h delay of recreating , mean-time it shows a static sitemap from the last generated , or when we manually generate it ?

**Comment by DanielnetoDotCom** [comment]
Hi

The sitemap has a 12 hours cache.
maybe you are not creating the sitemap that is why it is trying to recreate every visit.

First, make sure your sitemap.xml is writable

You can see it here

![image](https://user-images.githubusercontent.com/18009293/90514215-424cc600-e137-11ea-9ae5-c0b224a43db2.png)

Then you can try to reduce the total of rows in your sitemap `siteMapRowsLimit`

![image](https://user-images.githubusercontent.com/18009293/90514381-7de79000-e137-11ea-8f1d-782d9e9f91d3.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom All that set correctly already .

I'll change the cache time and see if it's really working . Also i'll add it to cloudflare .
