### ISSUE TITLE
Play Sign On Video Display

### ISSUE THREAD

**Issue by MyBlissIT** [WWBN/AVideo#3534]
I noticed that all my videos have the "press play" icon on the top left, mobile and desktop view, how can I remove this?

There's also that shaded blue block header which I do not know where it comes from..

![image](https://user-images.githubusercontent.com/34719141/90456612-b8cad300-e0f9-11ea-832a-3ccb31ce0f6b.png)

**Comment by DanielnetoDotCom** [comment]
This is a missing image.

you probably enable a plugin but did not complete the configuration.

It looks like the VideoLogoOverlay plugin, try to disable it.

If you enable the plugins and do not complete the configuration or misconfigure it,  you may find some problems on the platform
