### ISSUE TITLE
Searching of videos not working for me

### ISSUE THREAD

**Issue by Joelp** [WWBN/AVideo#3536]
**Describe the question**
What is needed to have working searching? It find no video anytime. 

**Screenshots**

![obrazek](https://user-images.githubusercontent.com/19979522/90511692-222ffd80-e15d-11ea-9038-e0c19a0f6946.png)

**Comment by DanielnetoDotCom** [comment]
can you reproduce it on demo site?

**Comment by akhilleusuggo** [comment]
No offense Daniel , but you always asking people to reproduce things on demo , when demo is NEVER updated .
![image](https://user-images.githubusercontent.com/52116577/90518967-18fc5c00-e170-11ea-8868-b04ac1ac03b4.png)

Demo site is 2 version below , and no mater how much time you click update , it doesn't  . I believe you're using some freezer so users doesn't abuse the demo site , and everything goes back to what is was . But demo site is not really for testing at the moment if it's not ALWAYS up to date with some crontab

**Comment by Joelp** [comment]
Yes, it works on demo. But this is why I asking. What can by wrong on my site? I think that, I installed all what was needed.

**Comment by DanielnetoDotCom** [comment]
check the log files for some clue.

maybe you are missing some tables or plugin tables.

**Comment by Joelp** [comment]
I made a new installation and it works now.
