### ISSUE TITLE
Import tiktok

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3539]
Any chance of direct import from tiktok?

**Comment by DanielnetoDotCom** [comment]
Do you mean embed or download and encode videos?

**Comment by fakeologist** [comment]
Yes import directly from tiktok to youphptube.

**Comment by DanielnetoDotCom** [comment]
If [youtube-dl](https://github.com/ytdl-org/youtube-dl) supports it, the encoder will handle it with no problem

**Comment by CROSSMediaNet** [comment]
Question: can this be possible to import Facebook videos?

**Comment by akhilleusuggo** [comment]
it is hard to give it a try ? Quick answer : Yes
