### ISSUE TITLE
how do i update the plugin i already purchased?

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3541]
how do i update the plugin i already purchased?

**Comment by akhilleusuggo** [comment]
1- Visit the website 
2- Log in 
3- Re-download the plugin 
4 - Log on your website 
5- Plugins , and upload it .

PS : If your plugin requires update , you should be able to see it on the plugin dahsboard like this : 

![image](https://user-images.githubusercontent.com/52116577/90722903-64c01a00-e2c4-11ea-8716-c100de25579d.png)

If you click on the orange boutom , should take you to the market place .

**Comment by DanielnetoDotCom** [comment]
You should be able to download all the purchased plugin from the same account you made the payment on the marketplace site. https://youphp.tube/marketplace/

Just go back there and log in again, you will see the download button.

If you are facing any problem please email developer@youphptube.com and inform your User # (the one below your Log off button)

![image](https://user-images.githubusercontent.com/18009293/90776102-0c8f1500-e2d0-11ea-843d-f65966598238.png)

**Comment by DanielnetoDotCom** [comment]
Hi

If you still having a problem on update your paid plugins, please email billing@youphptube.com
