### ISSUE TITLE
Page_load_time increased since update

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#3542]
SInce one of the last update the page_load_time is increased (also on clone).

All plugins are updated, checked MySQL_log but the only error found in avideo.log is

[20-Aug-2020 09:25:57 Europe/Berlin] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1129 takes 0.7799 seconds to complete. //var/www/html/archief.beesel-reuver.nl/view/index.php SCRIPT_NAME: /view/index.php

[20-Aug-2020 10:14:04 Europe/Berlin] AVideoLog::DEBUG: Not authorized compile css SCRIPT_NAME: /view/index.php 

All plugins and other scripts are disabled but it does not increased Page_load_time.
  
Checked https://github.com/WWBN/AVideo/wiki/Speed-up-your-page without any result

Testing is possible on: https://archief.beesel-reuver.nl  user: test password: test

![Snap1](https://user-images.githubusercontent.com/39981177/90747867-bb802080-e2d1-11ea-80f1-eb940514eab3.jpg)

**Comment by DanielnetoDotCom** [comment]
First, please make sure you update your site with the latest.

then check your log file for some clue what is taking time to load.

**Comment by TLCReuver** [comment]
I'm using the latest update with the latest plugins.

I disabled all plugins (also remove from plugin-dir) except SecureVideosDirectory and stripped all other stylesheet etc, but have still long page_load_time. When i click on the pages where i am pointing at in the attachment pages are showing **very fast**.

Cache_log shows the long page_load_time:

[23-Aug-2020 19:02:56 Europe/Berlin] AVideoLog::DEBUG: Page generated in **6.8757** seconds. User.....
[23-Aug-2020 19:02:56 Europe/Berlin] AVideoLog::DEBUG: Page generated in **6.8828** seconds. User.....
[23-Aug-2020 19:03:02 Europe/Berlin] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach]....
[23-Aug-2020 19:03:08 Europe/Berlin] AVideoLog::DEBUG: Page generated in **7.7724** seconds. User.....
[23-Aug-2020 19:03:08 Europe/Berlin] AVideoLog::DEBUG: Page generated in **7.7791** seconds. User.....

![Snap1](https://user-images.githubusercontent.com/39981177/90984270-323c4880-e574-11ea-869a-9e7848f496bb.jpg)

**Comment by DanielnetoDotCom** [comment]
First, make sure you are running the latest (updated this weekend)

then share your logs so we can see what plugin is slowing you down.

**Comment by TLCReuver** [comment]
I updated with: 

sudo git fetch --all
sudo git reset --hard origin/master

The plugin "Customize" is the only one what is slowing down:

-->AVideoLog::WARNING: The plugin [**Customize**::getStart] takes **3.9564** seconds to complete. URL: https://
    AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1127 takes 0.7272 seconds

**Comment by DanielnetoDotCom** [comment]
if you provide the log we may be able to help you

**Comment by TLCReuver** [comment]
Here are my access.log & avideo.log 

[access.log](https://github.com/WWBN/AVideo/files/5118101/access.log)
[avideo.log](https://github.com/WWBN/AVideo/files/5118104/avideo.log)

**Comment by DanielnetoDotCom** [comment]
According to your logs, this is what is consuming  time to load 

https://github.com/WWBN/AVideo/blob/4bd4312c3b9d37700e9029de5e9434c584a7fc76/objects/video.php#L1127

But looks like the logs are incomplete, there is a specific page where it is slow?

**Comment by TLCReuver** [comment]
The  videodemo on youtube is showing the slow pages 

https://youtu.be/vhL4NLwrYmY

Clicking on the pages in the middle of the video are fast.

I have to use PHP-FPM 7.3 for different webpages on vhosts , maybe that is slowing down ?

**Comment by DanielnetoDotCom** [comment]
I see you are talking about pagination.

Just curious, can you please disable the Livelink plugin and test it again?

**Comment by TLCReuver** [comment]
Disabled Livelink but pagination  did'nt speedup.

But i've got sometimes a 'Zero' in pagination, maybe there is the problem ?!

![Snap4](https://user-images.githubusercontent.com/39981177/91192304-0f39a200-e6f6-11ea-8648-619d644e47ea.jpg)

**Comment by DanielnetoDotCom** [comment]
Are you sure you are running the latest?

I cannot see the zero on my version.

Also how is your hardware? how many videos do you have?

**Comment by akhilleusuggo** [comment]
I also did see the 0 . Try to clear the cache . For it disappeared .

**Comment by TLCReuver** [comment]
Hi Daniel

I made a screen record with page **zero** with cleared cache on:
https://youtu.be/eIO4fUW630g
 
**My specs:**
Processor: AMD A4-4000 3.00 Ghz Dual Core
SSD: 1tB

Oracle Virtual Box 6.01
Ubuntu 18.04
Apache/2.4.29
PHP-FPM 7.3

Only for Server usage (no extra software)

Total 1355 Videos

I did yesterday the last update.
But for sure i restored the backup from one week ago and did a forced update:

**Fetching origin**
remote: Enumerating objects: 177, done.
remote: Counting objects: 100% (134/134), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 89 (delta 75), reused 69 (delta 57), pack-reused 0
Unpacking objects: 100% (89/89), done.
From https://github.com/DanielnetoDotCom/YouPHPTube
   4b98296ea..4bd4312c3  master     -> origin/master
Checking out files: 100% (13376/13376), done.
HEAD is now at 4bd4312c3 Fixing the rowCount

sudo git pull
Already up to date.

**Comment by DanielnetoDotCom** [comment]
@TLCReuver I am not sure exactly what you are saying is slowing down.
From your videos, the server seems normal to me.

But I notice one thing you can make to help the page load faster. reduce the total video per category in the Gallery plugin

![image](https://user-images.githubusercontent.com/18009293/91219447-06929d00-e6f1-11ea-93ca-f3d2f461df1a.png)
