### ISSUE TITLE
Video's description

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3548]
Any video , with description is ignoring the lines ( for paragraphs etc ) ... Something with the database communication .
From my debugging is missing the `<a> TEXT <a/> '\n' <a> TEXT <a/> '\n' ` , instead , it's writing the thing on the database as a text file .

I though I'm the only one having this issue , but I visited other sites , like josh , and the same . 
https://www.joshwhotv.com/v/24793

Any video's description is ignoring the paragraphs because is missing the `<a> '\n' <a/>`

Sometimes , the `'\n'` that should be on the database , instead is on the video's description 
![image](https://user-images.githubusercontent.com/52116577/90950475-79361b00-e45a-11ea-8cf2-c72b336453e5.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Sorry for opening this issue again . The fix works only for live-stream sent to encoder .
But doesn't work when someone uploads to the encoder .

**Comment by DanielnetoDotCom** [comment]
I do not get it.

can you please share a screenshot?

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/91050743-c74c4980-e627-11ea-9ffc-16a8ef4f8f90.png)

Everything is together , it's not recognizing the paragraphs .

**Comment by DanielnetoDotCom** [comment]
How is it in the database? there are HTML tags on the value saved on Database?

How is your disableHTMLDescription? is it checked or unchecked?

![image](https://user-images.githubusercontent.com/18009293/91053130-c819b700-e5f8-11ea-9779-f46aa1526e48.png)

Can you reproduce it on the demo? I tried it and works, maybe I am doing something different than you.

**Comment by akhilleusuggo** [comment]
unchecked . On demo site we can't upload files ( as far as I know , so I can't reproduce it )

On the database is missing some important things . First look at the example : 

1- Description : 

![image](https://user-images.githubusercontent.com/52116577/91063010-18633a00-e636-11ea-8372-217ff38071f4.png)

2- When encoded & uploaded : 

![image](https://user-images.githubusercontent.com/52116577/91063250-6d06b500-e636-11ea-820f-d973b5aba505.png)

3- Database text : 

`Description test\\n\\nLorem Ipsum is simply dummy text of the printing and typesetting industry. \\n\\nLorem Ipsum has been the industry\\\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries,\\n\\nWhere does it come from?\\nContrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur,\\n\\n\\n\\nThe standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from \\\"de Finibus Bonorum et Malorum\\\" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.`

It's missing what i've said before : 



> Any video's description is ignoring the paragraphs because is missing the `<a> '\n' <a/>`
> 
> Sometimes , the `'\n'` that should be on the database , instead is on the video's description
> ![image](https://user-images.githubusercontent.com/52116577/90950475-79361b00-e45a-11ea-8cf2-c72b336453e5.png)

**Comment by DanielnetoDotCom** [comment]
I see it is when the description comes from the encoder.

I will check it

**Comment by DanielnetoDotCom** [comment]
I tested in so many ways and combinations here and it always works.

But I realize you may have the magic quotes enabled https://stackoverflow.com/questions/220437/magic-quotes-in-php

can you please confirm?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I don't know what is that . But this post is 12years old , and that issue has been fixed on php +6.0
Is not only happening to me , here latest video from josh . 

https://www.joshwhotv.com/v/10097


Where have you tested it ? 

I'm not sure if you changed something . But now , it's from the description ( streamer site ) . Try to upload a video without any description , then copy the video's description of the this video ( for example ) into the description ; https://www.youtube.com/watch?v=-6G6CZT7h4k

No logs output when updating description sadly . 

Importing a video from youtube , like this one : https://www.youtube.com/watch?v=-6G6CZT7h4k , will work perfectly .
But if you copy the description and past it , wont work .


From youtube , works greate : 

![image](https://user-images.githubusercontent.com/52116577/91311251-88e79380-e7bb-11ea-9106-93c925ac78ce.png)

BUT , look at the description : 

![image](https://user-images.githubusercontent.com/52116577/91311292-98ff7300-e7bb-11ea-8f14-b4a1d57c0ab3.png)

Now , if I edit the description manually , everything breaks .

![image](https://user-images.githubusercontent.com/52116577/91311399-b6ccd800-e7bb-11ea-8f48-ed0e892040c3.png)

![image](https://user-images.githubusercontent.com/52116577/91311498-d532d380-e7bb-11ea-805a-36bec0bf836a.png)

**Comment by DanielnetoDotCom** [comment]
I test it locally, but I see now what may be the reason.

I am sending an update

**Comment by akhilleusuggo** [comment]
updated , and still not working . 

Now , even on the description it does invert it ... 

1- What a past : 
![image](https://user-images.githubusercontent.com/52116577/91331919-1d5df000-e7d4-11ea-934d-67b7976263a9.png)

2- Trying to edit : 
![image](https://user-images.githubusercontent.com/52116577/91331963-2b137580-e7d4-11ea-8e9c-241b0d947317.png)

3- How it looks : 
![image](https://user-images.githubusercontent.com/52116577/91331998-39fa2800-e7d4-11ea-9f12-a2c8a49e36a2.png)

**Comment by DanielnetoDotCom** [comment]
Hold on ...

**Comment by DanielnetoDotCom** [comment]
Tested again and I cannot reproduce it.

magic_quotes is something old from PHP, but may be enabled on your side.

can you please copy and paste here how exactly is this in your database?

I will try to manually add this text to mine and see the behavior.

**Comment by akhilleusuggo** [comment]
Can't past it here .  Github does eat the html tags . I'm uploading it .

[description.txt](https://github.com/WWBN/AVideo/files/5131256/description.txt)

**Comment by DanielnetoDotCom** [comment]
I download the file you sent and I renamed it to .html, open it in a browser and I guess the editor is displaying the file as expected

![image](https://user-images.githubusercontent.com/18009293/91334985-26d06380-e7a6-11ea-9551-91bb69abcd07.png)

**Comment by akhilleusuggo** [comment]
Then why when I try to edit the description does look like this : 

![image](https://user-images.githubusercontent.com/52116577/91338285-60709100-e7dd-11ea-83f1-ed229eaac08a.png)

**Comment by DanielnetoDotCom** [comment]
Yes, that is what I mean. that is how is supposes to looks like. 

at least for this text. maybe it was messed up before. can you please try a new one?
