### ISSUE TITLE
it still showing " There is no streaming " after 3 running live streams

### ISSUE THREAD

**Issue by GRNHACKER** [WWBN/AVideo#3549]
i started live stream from three different account and make all the live streams publicly but it still "showing there is no streaming".
how can i fix that??

**Comment by GRNHACKER** [comment]
> You're all set correctly . The issue is here :
> http://115.96.133.150/AVideo//plugin/Live/stats.json.php?Menu
> 
> But I don't get it . So the issue is only the notification field . Not that the stream is playing on the page .
> When you visit the page ( where the stream plays ) does it show OFFLINE ?
> 
> Last question , are you up to date ? A similar issue I opened it here , right after the update .
> But this issue has been fixed 8 days ago . #3517

yeah over the online player the status isl offline but it play the live streams....

**Comment by GRNHACKER** [comment]
> THis is a new bug after the last update. I can confirm it. I can watch my notification bell with it dropped down for about 30 seconds and then it refreshes and you see nothing anymore and it never comes back until you refresh the page..
> 
> You can see it here https://www.joshwhotv.com/video/25147/live-notifiaction-bug

i visited your site, its great...

and yeah i experience the bug it show the total no. of live stream but now display which live stream. It work after refresh but this is irritating enough.

**Comment by DanielnetoDotCom** [comment]
Is it happening only after 3 lives?
