### ISSUE TITLE
Help me with sendtorecored  to save on 2nd drive

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#3551]
Hello everyone I have gotten a 2and SSD drive for freedomshare.net

I only want live streams to save on SSD
How do I do  this?
I only have a 250gb drive for saving 

Also after it has saved  could I move my file back to the main drive?

Reason why I am doing this is when Live streaming everything works fine no lag no spinning circle etc 
But when the Live sends to encoder when you play the video after encoded every 3 secs you get a spinning circle 
As if the video is a buffing 

I was told saving SSD drive  would fix this 

But my space is low on the SSD 

If anyone could help me figure these thing out would be great

**Comment by freedomshare** [comment]
What is the command line to edit the config?

**Comment by freedomshare** [comment]
I have done everything up to 6 but I do not see the getrecoredfile  any where on sever

**Comment by freedomshare** [comment]
![15982396238788430067543649017037](https://user-images.githubusercontent.com/60738260/91000886-937a1100-e5a0-11ea-9af6-a6b8f22b7618.jpg)
I have edit the thing and edited the Live plugin admin settings to the path but the stream do not go on SSD drive

**Comment by akhilleusuggo** [comment]
ARE you sure you have mounted the SSD ?

**Comment by freedomshare** [comment]
It is mounted  on /mnt

**Comment by freedomshare** [comment]
The streams are still going to the other hard driver

**Comment by freedomshare** [comment]
![15982710501429076880670719189092](https://user-images.githubusercontent.com/60738260/91043291-bb419700-e5e9-11ea-9a70-705a523377bc.jpg)
![15982710792422764670676944693666](https://user-images.githubusercontent.com/60738260/91043340-cd233a00-e5e9-11ea-9ae2-5a9ec05b6a07.jpg)

**Comment by freedomshare** [comment]
Is there  any more file to config  even after making all changes  listed above the Live go to the HLS folder that is on sata  drive not the SSD drive

**Comment by akhilleusuggo** [comment]
run this command line , I need to see the output : 
`dh -h`

Also `fdisk -l`

I don't understand what /var is doing there

**Comment by freedomshare** [comment]
I made /var by mistake 
She command is not installed

**Comment by freedomshare** [comment]
Anyone wanna want to earn a $ for one optimizing my server and two having hls on SSD drive???

**Comment by akhilleusuggo** [comment]
I can do it for free .

**Comment by freedomshare** [comment]
> I can do it for free .

That would be great can you email me at cyber4hits@gmail.com 


Thank you so much!

**Comment by freedomshare** [comment]
@DanielnetoDotCom can you help with this we have changed all setting for SSD drive but stream will no longer play when we use HLS on the SSD Drive what could we be missing?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Only saving works , but the hls_path , can't not read it from the new location .
Permission issue . ( ts files are created )

**Comment by akhilleusuggo** [comment]
ok , done . Issue I believe was related to alias and on script to located a different directory that is not /HLS/live;

```
}
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /Your/Complete/New/Path;
```

**Comment by freedomshare** [comment]
> ok , done . Issue I believe was related to alias and on script to located a different directory that is not /HLS/live;
> 
> ```
> }
>                             types {
>                                     application/vnd.apple.mpegurl m3u8;
>                             }
>                             alias /Your/Complete/New/Path;
> ```

Nice thank you for doing this 👍

**Comment by freedomshare** [comment]
Thank you so much!
