### ISSUE TITLE
Using FTP storage

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#3553]
Videos upload to FTP server with no problem,  but won't play after encoding buffers indefinitely.

**Comment by DanielnetoDotCom** [comment]
Hi


First please check [this](https://github.com/WWBN/AVideo/wiki/The-media-playback-was-aborted-or-The-media-could-not-be-loaded)

**Comment by DanielnetoDotCom** [comment]
Then check this https://github.com/WWBN/AVideo/issues/2680

**Comment by ganddser** [comment]
Platform and all plugins are up to date. I've checked the above and still can't get videos uploaded to the FTP storage to play. What am I missing?

**Comment by DanielnetoDotCom** [comment]
Can you please share your HTML source code?

Specially the <source> tag inside the <video> tag

**Comment by ganddser** [comment]
Happy to: ` <video playsinline webkit-playsinline="webkit-playsinline" 
                                       preload="auto"
                       poster="https://liveurestreaming.com/videos/_YPTuniqid_5f4528eab82ee0.00799194.jpg?1598367988" controls class="embed-responsive-item video-js vjs-default-skin vjs-16-9 vjs-big-play-centered" id="mainVideo">
                                                   
                        <source src="https://tdnnetwork.com/tdnnetwork.com/serve_YPTuniqid_5f4528eab82ee0.00799194_Low.mp4" type="video/mp4"><source src="https://tdnnetwork.com/tdnnetwork.com/serve_YPTuniqid_5f4528eab82ee0.00799194_SD.mp4" type="video/mp4"><source src="https://tdnnetwork.com/tdnnetwork.com/serve_YPTuniqid_5f4528eab82ee0.00799194_HD.mp4" type="video/mp4">                    <p>If you can&apos;t view this video, your browser does not support HTML5 videos</p>
                    <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that                        <a href="http://videojs.com/html5-video-support/" target="_blank" rel="noopener noreferrer">supports HTML5 video</a>
                    </p>
                </video>`

**Comment by DanielnetoDotCom** [comment]
In the SRC you have this 

https://tdnnetwork.com/tdnnetwork.com/serve_YPTuniqid_5f4528eab82ee0.00799194_Low.mp4

And looks like you suppose to have this 

https://tdnnetwork.com/tdnnetwork.com/serve/_YPTuniqid_5f4528eab82ee0.00799194_Low.mp4

I guess you miss a slash in the FTP endpoint 
![image](https://user-images.githubusercontent.com/18009293/91193028-0aacc380-e6cd-11ea-94e3-27d240cff443.png)

So instead of this `https://tdnnetwork.com/tdnnetwork.com/serve`

make sure you have this `https://tdnnetwork.com/tdnnetwork.com/serve/`

**Comment by ganddser** [comment]
It always takes a fresh pair of eyes to see simple mistakes. Thanks @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
LOL, I am glad it is working now
