### ISSUE TITLE
letsencrypt

### ISSUE THREAD

**Issue by bitrupter-cmd** [WWBN/AVideo#3555]
Updated cert for ssl using letsencrypt encoder is in upload folder. so address is irelandlive.online/notube that takes me to my youphptube then when i click encode it syas
![fault](https://user-images.githubusercontent.com/70169705/91085271-1a80c500-e645-11ea-90a9-386a71df0087.png)
Can anyone help....  sites available 000-default.conf, default-ssl.conf, 000-default-le-ssl.conf

**Comment by daoguey** [comment]
you might have to  remove the install of the encoder and reloaded again. Pull git again for encoder. I remember getting this in the past and the way to solve it was to re-configure it.

**Comment by DanielnetoDotCom** [comment]
I cannot see a reason for that but check your encoder logs.

Reinstall as @daoguey is an alternative, and maybe a faster solution

**Comment by ronaldod** [comment]
What about the permission set in the database of the encoder. You upgraded from http to https..

**Comment by bitrupter-cmd** [comment]
Thanks sorted

**Comment by bitrupter-cmd** [comment]
sorry yes I have solved issu thanks
David lenegan
