### ISSUE TITLE
Subtitle Switch not showing for regular users

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3556]
I have the plugin enabled and removed the check mark in the parameter that says disable subtitles. 

I can see the upload subtitle buttons in video manager when logged in as admin but not on normal accounts.

How does a user use the subtitle upload?

**Comment by DanielnetoDotCom** [comment]
Hi

I just checked the plugin and the button supposes to show for regular users also.

can you reproduce it on demo site?
