### ISSUE TITLE
limit the number of live shows on the home page

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3557]
hello @DanielnetoDotCom  I did a test I added several live I am looking for the limit on the number of live we want to display on the home page

![image](https://user-images.githubusercontent.com/39193219/91107536-cfcb7100-e675-11ea-8e99-2a352c0c3579.png)

I do not find for 

![image](https://user-images.githubusercontent.com/39193219/91107872-a5c67e80-e676-11ea-978b-551c070d0bfd.png)

**Comment by DanielnetoDotCom** [comment]
I see, I agree it should be limited.

Question: Are most of those Livelinks or Lives?

**Comment by syldri** [comment]
hello @DanielnetoDotCom  there should be a limit on both like the Gallery plugin for videos

**Comment by DanielnetoDotCom** [comment]
There is a new property on the Live plugin (limitLiveOnVideosList)

this will limit how many videos it will add on the first page.
