### ISSUE TITLE
cannot change Media Owner anymore 

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#3560]
Anyone else unable to change media owner. After last update if I upload a video for a client I can't load users in the Media Owner field to change the owner.

**Comment by DanielnetoDotCom** [comment]
Please check for js errors

Or maybe php errors

**Comment by ganddser** [comment]
Still can't change media owner, clearing the field doesn't list existing users as before. Checked the logs can't find anything Media Owner errors.

**Comment by DanielnetoDotCom** [comment]
Sorry about that.

I guess this should fix

**Comment by ganddser** [comment]
Thanks @DanielnetoDotCom Hope this is fixed soon but it's secondary to my issue with YPTStorage see the emails I sent you last night and this morning if you haven't yet.

**Comment by DanielnetoDotCom** [comment]
Hi, please open an issue regarding the YPTStorage
