### ISSUE TITLE
meet

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3561]
This meet plugin , is a self hosted ? or are we hosting our ''meeting'' on a external server ?

**Comment by DanielnetoDotCom** [comment]
External server.

**Comment by akhilleusuggo** [comment]
will have in the future the self-hosted one ? https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart

This could be done with API I believe , on the same server of live-streaming site for privacy and control .

**Comment by hamelinmultimedia** [comment]
If you have jitsi self hosted it is very easy to include it in avideo or HTML file... I think the plugin might have the option to use different addresses

**Comment by syldri** [comment]
@DanielnetoDotCom    when i look at your demo site and my site i dont have the same things what is the difference

![image](https://user-images.githubusercontent.com/39193219/91325640-bdf7e400-e7c3-11ea-8209-dcda2ee9f3bb.png)


![image](https://user-images.githubusercontent.com/39193219/91328585-6c515880-e7c7-11ea-8d77-15ee689723df.png)

**Comment by DanielnetoDotCom** [comment]
I am using a modified version of jitsi.

the regular jitsi will not work on it.

regarding the live stream services (for jitsi) we still studying how to make it available, because currently, it consumes a good amount of resources (CPU) from the server

**Comment by syldri** [comment]
ah ok thanks for the information @DanielnetoDotCom

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I don't know what tweaks you're using to make it use that much resources . It's a server on nginx server . with 1gb ram should do much more then needed . 1-2 cores should be able to hosts more then 10 users .

https://jitsi.org/jitsi-videobridge-performance-evaluation/

**Comment by DanielnetoDotCom** [comment]
The problem is not to host users, it to use the Jibri to live transmit.

Users we can handle a lot more

**Comment by akhilleusuggo** [comment]
Yes , but that is for recording or streaming to the nginx the meet conference . 
What is using the CPU is the transcoding process that you're using . 

`ffmpeg -y -v info -f x11grab -draw_mouse 0 -r 30 -s 1280x720 -thread_queue_size 4096 -i :0.0+0,0 -f alsa -thread_queue_size 4096 -i plug:bsnoop -acodec aac -strict -2 -ar 44100 -c:v libx264 -preset veryfast -maxrate 2976k -bufsize 5952k -pix_fmt yuv420p -r 30 -crf 25 -g 60 -tune zerolatency -f flv rtmp://..........`

We better get a serious GPU for this . Or we just use `ffmpeg -re -i '$input' -c copy -f flv rtmp://..........`

This last line is what I've being asking you for months to add to our NGINX live-stream plugin HLS ( for adaptive mode) 

```
exec ffmpeg -i rtmp://localhost/live/$name
          -c:a aac ....... rtmp://localhost/adaptive/$name_low
          -c:a aac ....... rtmp://localhost/adaptive/$name_mid
          -c:a aac ....... rtmp://localhost/adaptive/$name_hi
          -c copy -f flv rtmp://localhost/adaptive/$name_original;

```

This way , we don't need to re-transcode a stream and keep the original quality at the same bitrate , in case any user want to watch the original quality . This requires only an option to add on the HLS plugin .

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo you are correct.

but the original size for the x11grab is 640x480 px, it is a very low resolution. to get the 720p we need to transcode it. so the `ffmpeg -re -i '$input' -c copy -f flv rtmp://..........` will not work.

I hope we find a way to save some CPU, otherwise the meet cut some parts of the screen

**Comment by akhilleusuggo** [comment]
This is very bad idea . What you're trying is to create dimension , that is not possible . You're going to make the video look worse .
It's like having a video at 20FPS , and you're voice the encoder to be 60FPS . You're duplicating frames , but NOT creating frames .

**Comment by DanielnetoDotCom** [comment]
Sorry, what is a bad idea? where am I duplicating frames?

**Comment by akhilleusuggo** [comment]
Taking a video at 240p , and encoding it to be 1080p is impossible . You're creating fake pixels , nothing more .
The encode will proceed , but the quality will be trash as it supposed to be .

**Comment by DanielnetoDotCom** [comment]
No, the x11grab is like a screen resize, it will rerender the whole screen in realtime.

you can test it on demo site, it works pretty good

that is the FFMPEG command

`ffmpeg -y -v info -f x11grab -draw_mouse 0 -r 30 -s 1280x720 -thread_queue_size 4096 -i :0.0+0,0 -f alsa -thread_queue_size 4096 -i plug:bsnoop -acodec aac -strict -2 -ar 44100 -b:a 128k -af aresample=async=1 -c:v libx264 -preset veryfast -maxrate 2976k -bufsize 5952k -pix_fmt yuv420p -r 30 -crf 25 -g 60 -tune zerolatency -f flv rtmp://....`

**Comment by akhilleusuggo** [comment]
> I mean, the only way to not transcode is to use the default 640x480 resolution

That what must be . But , I'm not sure if the x11grab is 640x480 . Are you sure about that ??
This value should be the value of the user's screen , not of the software . Maybe your screen is 640x480

I grabed my screen with ffmpeg , this is the output with ffprobe : 

 ```
Duration: 00:00:34.55, start: 0.000000, bitrate: 352 kb/s
    Stream #0:0: Video: h264 (High 4:4:4 Predictive), yuv444p(progressive), 1920x1080, 60 fps, 60 tbr, 1k tbn, 120 tbc (default)
```

**Comment by DanielnetoDotCom** [comment]
> > I mean, the only way to not transcode is to use the default 640x480 resolution
> 
> That what must be . But , I'm not sure if the x11grab is 640x480 . Are you sure about that ??
> This value should be the value of the user's screen , not of the software . Maybe your screen is 640x480

I already research about that and I found no other way.
FYI x11grab is a virtual screen, this is related to the [Jibri](https://github.com/jitsi/jibri) project. I appreciate it if you can find another way to use it.

**Comment by akhilleusuggo** [comment]
https://github.com/jitsi/jibri/blob/12b3bd81c7a29be53139ca0a628772358718ef8a/src/main/kotlin/org/jitsi/jibri/capture/ffmpeg/FfmpegCapturer.kt#L41

For me , I would leave it to 640x480 ( if that's really the resolution ) . Think about it . If only 2 users are sharing the screen , it doesn't mater it's 720p or 480p . The screens will look so small , that makes non sense at all . What is the point to have 4K videos if the screens gonna look like this : 

![image](https://user-images.githubusercontent.com/52116577/91347068-6a4cc100-e7ea-11ea-9fed-56453b91787e.png)

**Comment by DanielnetoDotCom** [comment]
I tried before with a 480px resolution, and it was really poor quality.

I guess jitsi has a minimum size, and the mining was cut off when I ran it without transcoding. It was like the meet cameras could not fit on the screen.

**Comment by hamelinmultimedia** [comment]
I'd like to try my jitsi server. how I can set it up

**Comment by DanielnetoDotCom** [comment]
You can use your own jitsi with some limitations

Now I can remember you will have no Moderation (I guess all users are moderators), and no direct Livestream

Make sure you set up the correct parameters

![image](https://user-images.githubusercontent.com/18009293/91379226-8d7e6d00-e7f8-11ea-8045-65a446f045f1.png)

**Comment by hamelinmultimedia** [comment]
perfect thanks I'm already starting to do tests

**Comment by hamelinmultimedia** [comment]
I like it...
my server worked, I have to do more tests.
then try to switch to another server and it tells you that server is not ready... delete the data from my server and keep coming into my server ...
![Anotación 2020-08-26 224701](https://user-images.githubusercontent.com/53911390/91381939-2fe52300-e7ee-11ea-9004-64b3fa8d0bb6.png)

**Comment by syldri** [comment]
@hamelinmultimedia   hello tell me where did you find this information

![image](https://user-images.githubusercontent.com/39193219/91382216-83289700-e829-11ea-8ae7-b510eff89204.png)

**Comment by hamelinmultimedia** [comment]
hello ...here https://github.com/WWBN/AVideo/issues/3561#issuecomment-681315573

**Comment by hamelinmultimedia** [comment]
update the plugin

**Comment by DanielnetoDotCom** [comment]
> I like it...
> my server worked, I have to do more tests.
> then try to switch to another server and it tells you that server is not ready... delete the data from my server and keep coming into my server ...
> ![Anotación 2020-08-26 224701](https://user-images.githubusercontent.com/53911390/91381939-2fe52300-e7ee-11ea-9004-64b3fa8d0bb6.png)

The server takes about 2 min to get ready the first time

**Comment by syldri** [comment]
what i mean where i find them
JWT_APP_ID: and

JWT_APP_SECRET:

**Comment by hamelinmultimedia** [comment]
each jitsi server can be assigned an id and password.

**Comment by hamelinmultimedia** [comment]
you can look at this link in from point 6
https://www.linuxbabe.com/ubuntu/install-jitsi-meet-ubuntu-20-04

**Comment by hamelinmultimedia** [comment]
> > I like it...
> > my server worked, I have to do more tests.
> > then try to switch to another server and it tells you that server is not ready... delete the data from my server and keep coming into my server ...
> > ![Anotación 2020-08-26 224701](https://user-images.githubusercontent.com/53911390/91381939-2fe52300-e7ee-11ea-9004-64b3fa8d0bb6.png)
> 
> The server takes about 2 min to get ready the first time

in my case it wasn't 2 minutes ... it was a lot less than a minute

**Comment by DanielnetoDotCom** [comment]
FYI, for myself I am using jitsi on docker, it is a pretty easy installation.

https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker

**Comment by hamelinmultimedia** [comment]
in my case i install on ubuntu 20.04 vps ...no docker
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-manual
