### ISSUE TITLE
/view/index.php?v=

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3562]
It is normal that people/bots can browse from there and be able to find videos/pictures ?

This is making it for me harder , having to add more rules to block all possible paths to block some videos/thumbnails to be shown.

Here is an example of structure : https://demo.avideo.com/view/index.php?v=249?channelName=TheAdminChannel

**Comment by DanielnetoDotCom** [comment]
Sorry I do not get what is the question.

**Comment by akhilleusuggo** [comment]
Is the `/view/index.php?v=` necessary ? Or can be removed ?

If I add a rule , to https://demo.avideo.com/v/249?channelName=TheAdminChannel can be watched only by IP 1.1.1.1 , users can still access to it by https://demo.avideo.com/view/index.php?v=249?channelName=TheAdminChannel 

The question is , why do we have the `/view/index.php?v=` . Is this essential for the site to work ?

**Comment by DanielnetoDotCom** [comment]
Yes, it is.

actually the rewrite rule will translate this `https://demo.avideo.com/v/249?channelName=TheAdminChannel` to this  `https://demo.avideo.com/view/index.php?v=249&channelName=TheAdminChannel`

and the second one is what really matters for the script.

**Comment by akhilleusuggo** [comment]
Thanks for explanation .
