### ISSUE TITLE
What is the difference between network encoder and installing my own

### ISSUE THREAD

**Issue by dbmasters** [WWBN/AVideo#3566]
There are UI/UX differences between using the stock network encoder vs installing my own...are there (well, there obviously are) major differences between hosting my own vs piggy-backing on the network encoder, I'd rather use my own and manage server resources and such myself.

**Comment by akhilleusuggo** [comment]
1- **Public encoder** ( is hosted by @DanielnetoDotCom / AVideo ) . You'll be on the queue encoder , and you have no control over the quality or anything .
2- Private encoder ( self hosted ) . You have control over everything , and you can pick the hardware that you want , and the right ffmpeg parameters .
3- Network-Encoder it's used only when you own 2 or more Private encoders . On this way , will pick automatically the encoder with less encoding queue , to speed up the users queue . ( based on ping/queue ) . The browser will open with URL that has better ''algorithm'' .

**Comment by dbmasters** [comment]
OK, appreciate that, I just found it unusual that the public encoder seemed to look differently and have a different experience than a self-hosted...so, I got mine up and installed, all permissions are proper and all that...now I uploaded a video file and an audio file, watched it go thru it's process of encoding and all that, refreshed the directory via filezilla and watched the file be made, change sizes and all that, it's finished, the files disappear (as I have set in config) but they never move to the streamer site, that directory remains empty.

**Comment by akhilleusuggo** [comment]
the encoder is not the host of files . The streamer site is the file host .
Anyway try to upload a shot video , and past the logs RELATED to the issue . You may see error or something .
Logs much be from the encoder and streamer to debugg .

**Default answer related to the debugging process**

provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by dbmasters** [comment]
OK, thanks for those links. My DevOps partner said that this latest install (we have installed and re-installed a few times learning much along the way) the logs were much more verbose...not sure what setting was different. But our last install the files uploaded and moved as I expected (meaning sitting in the encoder to process, then moving to streamer)...I have been digging thru configs and can't see what is different.

Appreciate the time and info, thank you.
