### ISSUE TITLE
Fresh Install of YouPHPTube on ubuntu server

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#3567]
1, I am able to log in from my server and everything looks ok, I try to log in from another computer or phone and I am greeted with a page that is not loading properly. Only see the search and it too is not in the correct position or size.

**Comment by DanielnetoDotCom** [comment]
I am not sure, but the way you describe sounds like you are mixing your internal network and your public one.

**Comment by milehighkaraoke** [comment]
Internal network and external network relay from my internal DNS. I have no problem connecting from both internal and external. When I connect internally or externaly  result the same on phone and PC. Everything views fine from installed machine [Image]



Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________
