### ISSUE TITLE
YPTStorage not working 

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#3569]
Installed YPTStorage plugin configured storage server, select a file and transfer it to new storage loction it says congratulations we're processing the transfer, but transfer never takes place. Video remains on Local drive. 
Setting YPTStorage as default location doesn't make any difference. Tried as admin and as user with upload access.

Not sure what this means "On the first access you will be requested for your streamer address. the installation script will try to create your videos directory and your configuration.php file. (This didn't occur at anytime)

The script will create a Storage site for you on your streamer site, but this site will be inactive, you will need to activate it (On the YPTStorage plugin) before proceed."

No such request came up.

Sent @DanielnetoDotCom my avideo logs via email

**Comment by DanielnetoDotCom** [comment]
Hi

basically you need another server and you need to run this installation https://github.com/WWBN/AVideo-Storage#copy-and-paste

Did you accomplish it?

If yes, how is your log files?

**Comment by ganddser** [comment]
I've done all of this Daniel that's what I'm saying

**Comment by ganddser** [comment]
Yes I setup a server installed the required services then added the server to YPTStorage

**Comment by DanielnetoDotCom** [comment]
Ok

Please share your log here at the moment you tried to transfer a file 

Also please share the storage log file ( the storage log is the apache2 log)

**Comment by ganddser** [comment]
[transfer_log.txt](https://github.com/WWBN/AVideo/files/5143970/transfer_log.txt)

Getting  No such file or directory error trying to get apache2 log

**Comment by DanielnetoDotCom** [comment]
The Apache log should be on /var/logs/apache2/error.log

**Comment by DanielnetoDotCom** [comment]
Also please provide a more complete log. The one you provided does not help much

**Comment by ganddser** [comment]
> 
> 
> Also please provide a more complete log. The one you provided does not help much

Sent you full log in your email this morning

**Comment by DanielnetoDotCom** [comment]
I checked your log, you sent thru email

I found 3 things...

1. ftp_delete (do you have the FTP plugin enabled? if yes, disable it)
2. storage1.avideo.com (are you using the Storage plugin with the demo storage site?? you do not suppose to do that)
3. server1.telenative.net (this server is not reachable thru the internet. are you using it locally?)

Based on your log, I guess you have some misconfiguration.

Please share a screenshot of your YPTStorage plugin parameters panel 

Also please share the Storage address

**Comment by ganddser** [comment]
Hold I reinstalled the server and everything else 
1. FTP Plugin is disabled
2. No not using storage1.avideo
3. I'm re configuring server

**Comment by DanielnetoDotCom** [comment]
Ok, when you do, please share the log here

**Comment by ganddser** [comment]
@DanielnetoDotCom  A couple hours ago I reinstalled the server and then tried to transfer a video of course it didn't work. Here's the storage server error: 
[Sun Aug 30 00:04:06.111161 2020] [php7:error] [pid 61238] [client 111.11.110:47728] PHP Fatal error:  require_once(): Failed opening required './configuration.php' (include_path='.:/usr/share/php') in /var/www/html/AVideo-Storage/fileinfo.json.php on line 2

It's there's no configuration file I can confirm no Config file has been created, according to this "On the first access you will be requested for your streamer address. the installation script will try to create your videos directory and your configuration.php file."
When I enter the streamer URL and click register it doesn't go anywhere just reloads the register page.

[Sun Aug 30 00:04:06.405021 2020] [php7:warn] [pid 61239] [client 0:47730] PHP Warning:  require_once(./configuration.php): failed to open stream: No such file or directory in /var/www/html/AVideo-Storage/post.json.php on line 3

**Comment by DanielnetoDotCom** [comment]
I guess for the storage you need to manually create the configuration file.

did you do that?

**Comment by akhilleusuggo** [comment]
go to /var/www/html/
`chown www-data:www-data -R *`

I had the same issue , but you still can create it manually . Nothing hard or special . Copy/Past , then replace the url and key

**Comment by ganddser** [comment]
This is what the error shows [Sun Aug 30 13:27:27.298042 2020] [php7:notice] [pid 41938] [client :53938] inputURL: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL was not found on this server.</p>\n<hr>\n<address>Apache/2.4.29 (Ubuntu) Server at ing.com Port 443</address>\n</body></html>\n, referer: http://tive.net/AVideo-Storage/

**Comment by ganddser** [comment]
> 
> 
> I guess for the storage you need to manually create the configuration file.
> 
> did you do that?

How do I manually create the config file? I mean what goes into the file and where is it saved?

**Comment by ganddser** [comment]
I added an empty configruaration file to AVideo-Storage/ and got in response Your Streamer Answer an error!
NULL

**Comment by akhilleusuggo** [comment]
Your domain name itself does not exist . tive.net/
I'm not sure what you're trying to do , but your issue is on the server config / apache2 config . Not on the script itself .
I don't know if you're sharing the actual data or ...

How do I manually create the config file? I mean what goes into the file and where is it saved? Create the file on /videos directory .

**Comment by DanielnetoDotCom** [comment]
I just made a video Installing YPTStorage and configuring the YPTStorage plugin

https://tutorials.avideo.com/video/86/installing-yptstorage-and-configuring-the-yptstorage-plugin

Definitely the cache issue is something I will correct in a future update.

**Comment by ganddser** [comment]
Thanks @DanielnetoDotCom. Your video helped with creating the configuration file manually it would have been impossible to guess what's needed in the file. The strange thing is after creating the file and manually activating the the storage site trying to load it in the browser  still results in "Your Streamer Answer an error!
NULL"
However I tried transferring a small file anyway and it did get transferred. Trying another file to see what happens, and I'm gonna try setting the storage as default a user and see if i can upload to it. Here's to hoping.

**Comment by ganddser** [comment]
This transfer completed and the video is playing fine but the error log shows a new error [Mon Aug 31 00:12:36.242447 2020] [php7:notice] [pid 34345] [client 30:33982] post.json.php: response {"error":false,"msg":"","aVideoStorageURL": Any idea this means?

**Comment by akhilleusuggo** [comment]
Is the cache issue . I gave up on it . https://github.com/WWBN/AVideo/issues/3403
I'm using cloudflare to fix this issue rly annoying

**Comment by DanielnetoDotCom** [comment]
Regarding` {"error":false,"msg":"","aVideoStorageURL"` this is not an issue, this mean all was fine  **"error":false**

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom yes but keeps repeating

**Comment by DanielnetoDotCom** [comment]
Can you please paste the full message so I can find it here

**Comment by akhilleusuggo** [comment]
can't reproduce it because I've fixed it in other ways , and I don't wanna bring this bug back tbh

**Comment by DanielnetoDotCom** [comment]
The storage tag update is resolved on this issue.

**Comment by ganddser** [comment]
OK, guys after enabling ssl on the storage server I can't get videos from there to play infiniate load no buffer
- updated the configuration file to match the https URL, move video to storage works, can upload with encoder, I can send to the storage i just can't get video to playback

AH01071: Got error 'PHP message: Storage xsendfile https://example.com/YouPHPTube/plugin/YPTStorage/canWatchVideo.json.php?token=eyJzYWx0IjoiaHR0cHM6XC9cL2xpdmV1cmVzdHJlYW1pbmcuY29tXC8iLCJ0b2tlblRpbWVPdXQiOjIxNjAwLCJmaWxlbmFtZSI6Il9ZUFR1bmlxaWRfNWY0ZGJlMzYwMGU3MDYuNzQxMDk4MjlfSEQiLCJ0aW1lIjoxNTk4OTMwNjcwfQ==&filename=_YPTuniqid_5f4dbe3600e706.74109829_HD => <!DOCTYPE html>\n<html>\n    <head>\n        <style>\n            @import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300);\n\n            body {\n                background-color: #335B67;\n                background: -ms-radial-gradient(ellipse at center,  #335B67 0%, #2C3E50 100%) fixed no-repeat;\n                background: -moz-radial-gradient(ellipse at center,  #335B67 0%, #2C3E50 100%) fixed no-repeat;\n                background: -o-radial-gradient(ellipse at center, #335B67 0%, #2C3E50 100%) fixed no-repeat;\n                background: -webkit-gradient(radial, center center, 0, center center, 497, color-stop(0, #335B67), color-stop(1,...', referer: https://example.com/video/233/stop-text-stop-recks

**Comment by DanielnetoDotCom** [comment]
If you install SSL into your streamer, your storage, MUST BE SSL too

from your error log, I could not detect anything.

check your JS console for errors.

**Comment by ganddser** [comment]
It took awhile but I figured out why the videos on the external storage refused to play. They were being blocked by .htaccess when iI set .htaccess in AVideo-Storage to .htaccess.old (disabled) the videos play. 

I have SecureVideosDirectory installed and configured on the streaming site the .htaccess file from the streamer is the same as the one on the storage server. Do I use the same .htaccess file on AVideo-Storage server or what I need to change?

**Comment by DanielnetoDotCom** [comment]
Hi

do you mean without the .htaccess the videos play?

I have it working here with the .htaccess, I guess it maybe something else. if you want, you can share your JS console here for some clue

**Comment by ganddser** [comment]
> do you mean without the .htaccess the videos play? Correct.

htacess disabled: [console-with-htaccess-disabled.log](https://github.com/WWBN/AVideo/files/5163729/console-with-htaccess-disabled.log)
htaccess enabled: [console-withhtaccessenabled.log](https://github.com/WWBN/AVideo/files/5163730/console-withhtaccessenabled.log)

**Comment by DanielnetoDotCom** [comment]
Did you install the xsendfile module?

https://github.com/WWBN/AVideo/wiki/SecureVideosDirectory-Plugin#install-apache-xsendfile

If you disable the .htaccess your files will not be protected

**Comment by ganddser** [comment]
@DanielnetoDotCom I already had  xsendfile module? installed and enabled. I tried to edit the htaccess file from command line but it said the file doesn't exist (don't know why because it does exist). So I copied the htaccess file from the streamer and replaced the one on the storage server with it and the videos from the storage are playing now. But the videos are still not actually protected.

From the Page Source once I find the video source I can play by clicking on the link  <source src="https://site.com/AVideo-Storage/videos/_YPTuniqid_5f4c3853f13013.64922292_Low.mp4?token=eyJzYWx0IjoiaHR0cHM6XC9cL2xpdmV1cmVzdHJlYW1pbmcuY29tXC8iLCJ0b2tlblRpbWVPdXQiOjIxNjAwLCJmaWxlbmFtZSI6Il9ZUFR1bmlxaWRfNWY0YzM4NTNmMTMwMTMuNjQ5MjIyOTJfTG93IiwidGltZSI6MTU5OTIzMTczMn0=" type="video/mp4"><source src="https://site.com/AVideo-Storage/videos/_YPTuniqid_5f4c3853f13013.64922292_SD.mp4?token=eyJzYWx0IjoiaHR0cHM6XC9cL2xpdmV1cmVzdHJlYW1pbmcuY29tXC8iLCJ0b2tlblRpbWVPdXQiOjIxNjAwLCJmaWxlbmFtZSI6Il9ZUFR1bmlxaWRfNWY0YzM4NTNmMTMwMTMuNjQ5MjIyOTJfU0QiLCJ0aW1lIjoxNTk5MjMxNzMyfQ==" type="video/mp4"><source src="https://site.com/AVideo-Storage/videos/_YPTuniqid_5f4c3853f13013.64922292_HD.mp4?token=eyJzYWx0IjoiaHR0cHM6XC9cL2xpdmV1cmVzdHJlYW1pbmcuY29tXC8iLCJ0b2tlblRpbWVPdXQiOjIxNjAwLCJmaWxlbmFtZSI6Il9ZUFR1bmlxaWRfNWY0YzM4NTNmMTMwMTMuNjQ5MjIyOTJfSEQiLCJ0aW1lIjoxNTk5MjMxNzMyfQ==" type="video/mp4">


Clicking this from the page source plays the video

**Comment by DanielnetoDotCom** [comment]
Hi, do not replace the .haccess one for others.

each one has a specific .htaccess file.

the xsendfile have to be enabled on both, Storage and Streamer. if it is showing you red, does not mean is not set up. you can just ignore it and test your storage.


can you please put all the files as the default ones and test again.

please share some JS console logs, AVideo logs, and screenshots here so we will be able to figure out what is going on

**Comment by ganddser** [comment]
The image above shows what happens when htaccess is enabled on the storage server. The 2 logs above show what happens both when htaccess is enabled and disabled on the same.

htacess disabled: console-with-htaccess-disabled.log
htaccess enabled: console-withhtaccessenabled.log

This is from AVideoLog I removed Location information i.e IP addresses but this is the result for 5:30 pm today. And what occurred when htaccess is enabled, and xsendfile is upto date and enabled on both servers

[04-Sep-2020 17:34:06 America/New_York] AVideoLog::DEBUG: userCanWatchVideo: **No plugins approve you to watch the video (10)  SCRIPT_NAME: /view/index.php**
[04-Sep-2020 17:34:07 America/New_York] AVideoLog::DEBUG: Page generated in 0.1948 seconds. User: Not Logged - No Cache (/video/10/tdn-tv?channelName=TDN+TV) FROM: .135 Browser: Mozilla/5.0 (Linux; Android 10; Redmi Note 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/.81 Mobile Safari/537.36 SCRIPT_NAME: /view/index.php
[04-Sep-2020 17:34:07 America/New_York] AVideoLog::DEBUG: Page generated in 0.2255 seconds. User: Not Logged - No Cache (/video/10/tdn-tv?channelName=TDN+TV) FROM: .135 Browser: Mozilla/5.0 (Linux; Android 10; Redmi Note 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/.81 Mobile Safari/537.36 SCRIPT_NAME: /view/index.php
[04-Sep-2020 17:34:07 America/New_York] AVideoLog::DEBUG: Page generated in 0.2283 seconds. User: Not Logged - No Cache (/video/10/tdn-tv?channelName=TDN+TV) FROM: .135 Browser: Mozilla/5.0 (Linux; Android 10; Redmi Note 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/.81 Mobile Safari/537.36 SCRIPT_NAME: /view/index.php
[04-Sep-2020 17:34:11 America/New_York] AVideoLog::DEBUG: User::canWatchVideo Video is empty () SCRIPT_NAME: /view/index.php

[04-Sep-2020 17:34:41 America/New_York] AVideoLog::DEBUG: userCanWatchVideo: No plugins approve you to watch the video (15)  SCRIPT_NAME: /view/index.php
[04-Sep-2020 17:34:41 America/New_York] AVideoLog::DEBUG: CustomizeUser::canShareVideosFromVideo canShareVideosFromUser(6) = false SCRIPT_NAME: /view/index.php
[04-Sep-2020 17:34:41 America/New_York] AVideoLog::DEBUG: CustomizeUser::canShareVideosFromVideo canShareVideosFromUser(6) = false SCRIPT_NAME: /view/index.php
[04-Sep-2020 17:34:41 America/New_York] AVideoLog::DEBUG: Page generated in 0.2214 seconds. User: Not Logged - No Cache

**Comment by DanielnetoDotCom** [comment]
The logs does not help much as long as you removed the URLs

I need to test if the files were moved , if your site and the storage have the ssl correctly setup, what source urls is your streamer site generating , etc.

I understand you are concerned about privacy, but the way you are providing the logs is really hard to check what is going on
