### ISSUE TITLE
Send recorded to encoder plugin update request

### ISSUE THREAD

**Issue by GodgivenButhelezi** [WWBN/AVideo#3571]
Greetings Mr D Neto I would like to request for a feature on the send recorded to encorder plugin. i would like to enable premium users to record their stream and none premium users cannot record videos. This may help even for the video conference to record meetings only for premium users since it records for everyone now. All users should be able to enable or disable the send recorded to encoder plugin especially the radio broadcasters since they may be broadcasting 24/7 and we don't want their stream to be recorded.

**Comment by DanielnetoDotCom** [comment]
Hi

I understand, but this will require some code. definitely it will be made and improved, but I cannot give you a timeline for it.

If you want this to be on the road to be made not you can hire us for development. if you want a quote please email me at developer@youphptube.com
