### ISSUE TITLE
Website name Image link on top left directing to the old website

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3572]
Good day,

Please note the name image on the left is redirecting to seafarerstube.com rather than the new website maritimepatform.com.

Can you please advise where should i change the setting for this.

![image](https://user-images.githubusercontent.com/65802024/91646770-439fbc00-ea70-11ea-94fd-bde1ad375c9a.png)

**Comment by vraghavans** [comment]
good day,

further to below
even the email verification mail has the old domain name

Please advise to change the same

**Comment by DanielnetoDotCom** [comment]
Check this

![image](https://user-images.githubusercontent.com/18009293/91661078-32769f80-eab0-11ea-86a5-a8466603a123.png)
