### ISSUE TITLE
Clickable links 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3573]
Please add clickable links in video description section.

**Comment by fakeologist** [comment]
Please add in the android app too. You can't even highlight the url to copy it.

**Comment by DanielnetoDotCom** [comment]
Hi

transform URLs into links is something that the place you are sharing should do.

But if you can screenshot and detail your problem I may be able to give you a better solution/advice

**Comment by fakeologist** [comment]
Desktop urls don't linkify in any browser.
Android app doesn't even allow you to copy the text, let alone click it.

**Comment by DanielnetoDotCom** [comment]
sorry, the fix is not easy.

actually nothing on the APPs are easy, but for sure we will improve it
