### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#3574]
Question: How to migrate your entire video hosting site to another server, without interruption of services, if it is possible, or you will have to put the site to maintenance mode to migrate

**Comment by akhilleusuggo** [comment]
rsync plugin 

![image](https://user-images.githubusercontent.com/52116577/91717710-b4db8e00-eb9a-11ea-83ab-c0e0b51b60c3.png)

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo is correct, Just make sure you do not upload any video while you are transferring it.

then when you done, you can move the DNS.
