### ISSUE TITLE
Avideo and openLDAP

### ISSUE THREAD

**Issue by elahehab** [WWBN/AVideo#3575]
We are using avideo (youphp.tube) and we want to activate LDAP authentication method by purchasing loginLDAP plugin. We want to make sure that this plugin works with openLDAP as well as LDAP. I searched in documents and issues but I didn't find any related issues or docs. I guess it should work but because we want to purchase I want to make sure.

**Comment by DanielnetoDotCom** [comment]
I confirm I never had any issue related to the open LDAP

To make it clear we use the PHP LDAP functions https://www.php.net/manual/en/ref.ldap.php

I cannot see any limitation related to openLDAP

**Comment by patriclougheed** [comment]
Works great with my OpenLDAP server.
