### ISSUE TITLE
Plugins page shows no results

### ISSUE THREAD

**Issue by br0kenlink** [WWBN/AVideo#3577]
Hi,
just noticed after my last update to 9.* plugins page shows no plugins.
When I try to upload one of paid plugins, the website gets 500 Error right after upload.
Any help would be appreciated, Thanks

**Comment by DanielnetoDotCom** [comment]
check your log file

**Comment by br0kenlink** [comment]
So I downloaded zip file from git and uploaded to www root, website loads but its dark, nothing on it, just blank dark thing.
Avideo.log has this error:

[31-Aug-2020 17:28:14 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreatefrompng() in /var/www/YouPHPTube/objects/functi$
Stack trace:
#0 /var/www/YouPHPTube/objects/functions.php(2560): convertImage('/var/www/YouPHP...', '/var/www/YouPHP...', 100)
#1 /var/www/YouPHPTube/objects/configuration.php(251): convertImageToOG('/var/www/YouPHP...', '/var/www/YouPHP...')
#2 /var/www/YouPHPTube/objects/functions.php(2584): Configuration::getOGImage()
#3 /var/www/YouPHPTube/view/include/head.php(158): ogSite()
#4 /var/www/YouPHPTube/plugin/YouPHPFlix2/view/modeFlix.php(22): include('/var/www/YouPHP...')
#5 /var/www/YouPHPTube/view/index.php(27): require('/var/www/YouPHP...')
#6 {main}
  thrown in /var/www/YouPHPTube/objects/functions.php on line 1554

**Comment by DanielnetoDotCom** [comment]
Please google for that `PHP Fatal error: Uncaught Error: Call to undefined function imagecreatefrompng` and you will find the solution

**Comment by br0kenlink** [comment]
Ok, seems everything back to normal. Thanks
