### ISSUE TITLE
HLS Plugin

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3578]
Daniel is there anyway to make a separated HLS plugin for live-streaming only ?
The labels that I want to show on HLS are not what I wanna show on normal videos .

Also , I would like to add a new tab ( source ) , for the live-stream . Because for now we have only 3 options ...

Is it possible ?

**Comment by DanielnetoDotCom** [comment]
Hi

Is not clear to me what exactly you need, can you please place some screenshots?

**Comment by akhilleusuggo** [comment]
1-The quality selector on the live-streaming ( with transcoding ) does take the same labels as the normal videos . I would like to separate them .
2-For live-streaming , I would like a new label ( instead of 3 labels , to have 4 ) . Something like this ( only for live-streaming )

![image](https://user-images.githubusercontent.com/52116577/91990444-636a0500-ed3a-11ea-8bb6-bc6a9c5fc97a.png)


On the nginx config ; The source label will correspond to the last line ;

```
exec ffmpeg -i rtmp://localhost/live/$name 
                            -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:240 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1200k -b:a 96k -r 20 -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_low  
                            -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:480 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 2400k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_mid  
                            -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:720 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 4200k -bufsize 100000k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi
                            -c copy -f -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_src;
```

**Comment by DanielnetoDotCom** [comment]
Hi

I review the code.

Currently we are limited to 3 resolutions on the live.
Change it will require change many things in the code, including the stats from live

So right now it is. It possible
