### ISSUE TITLE
live streaming password and pay button

### ISSUE THREAD

**Issue by hamelinmultimedia** [WWBN/AVideo#3579]
Daniel. 
what possibility is to add an option in live streamin to ask for password and be able to put donation or payment button

**Comment by DanielnetoDotCom** [comment]
> what possibility is to add an option in live streamin to ask for password and be able to put donation or payment button

Definally this is something we will add in the future, we do not have it right now

**Comment by hamelinmultimedia** [comment]
ok Daniel. just keep in mind that this may be the best time to do so.
I take time to do it while I know Avideo well.
thank you.

**Comment by DanielnetoDotCom** [comment]
If you are willing to pay, we can put a timeline on it.

if you want please email developer@youphptube.com
