### ISSUE TITLE
webm thumb generation

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#3580]
Hi, 

When i direct upload a webm file, should it be creating a thumb automatically?

I can play the video when its uploaded, however the jpg is generated but i see the popcorn image
![webm-img-issue](https://user-images.githubusercontent.com/28105720/91839617-486a9880-ec47-11ea-9674-8f4babfa8b6e.jpg)

I can see the jpg is created, however its not the popcorn image.

I have the MP4ThumbsAndGif plugin enabled.

**Comment by ronaldod** [comment]
Check the encoder log file. I assume (log file needed to confirm) a package is missing for generating the file.
