### ISSUE TITLE
Download Archives

### ISSUE THREAD

**Issue by praiseworld3d** [WWBN/AVideo#3583]
Hello All,
Once a live stream is encoded, how do I download it for post editing? Do I have to do something before streaming? Is there a way to access archived live streams via ssh to server? Please help, and thanks in advance.

**Comment by akhilleusuggo** [comment]
If you followed up with the wiki https://github.com/WWBN/AVideo/wiki/Record-Live-Stream , you should be able to find the video on your live-streaming server on `/var/www/tmp`

In case you want the server to automatically send it to the encoder , to save it later on the main site you need the plugin . https://youphp.tube/marketplace/ SendRecordedToEncoder

If your live-streaming server and your main site are not hosted on the same site , you need to follow up with this guide . https://github.com/WWBN/AVideo/wiki/Live-Plugin#record-a-video-on-a-remote-server
