### ISSUE TITLE
verification email body uses the old domain,not changed to new domain-Please advise

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3584]
**Describe the question**
A clear and concise description of what is your question.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.
![image](https://user-images.githubusercontent.com/65802024/91917095-9da4b980-ecdc-11ea-8f88-9afe984e13da.png)
Please help!

Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
Check your **Web site title**

![image](https://user-images.githubusercontent.com/18009293/91991264-102b8e80-ed09-11ea-8628-cb1089f1675f.png)

**Comment by vraghavans** [comment]
thanks!done!
