### ISSUE TITLE
Chat 2 plug in for support

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3585]
**Describe the question**
Hi,i have purchased the chat 2 plug in but not able to see the support chat option,can you guide me how to make it visible on the home page please
**Screenshots**
Provide some screenshots to help us understand and explain your problem.
![image](https://user-images.githubusercontent.com/65802024/91917285-199f0180-ecdd-11ea-8921-4565fa05bfca.png)

**Comment by DanielnetoDotCom** [comment]
Hi 

this is not the Chat2

this is https://www.tawk.to/

**Comment by vraghavans** [comment]
Dear Daniel,

thanks for the reply,then what is this chat 2 used for?how is it used for interacting with the viewers of the site please?

Also kindly advise ,how do i incorporate the tawk.to in my website please

**Comment by DanielnetoDotCom** [comment]
Hi, the same way I did on demo.

Signup on https://www.tawk.to/

grab the code and add on the header code

![image](https://user-images.githubusercontent.com/18009293/92767372-6cc42480-f36d-11ea-979b-ceccc4360a73.png)

**Comment by vraghavans** [comment]
thanks!got it

Can you please explain the use of the Chat plugin i had purchased from the plugin store please

**Comment by DanielnetoDotCom** [comment]
With Chat 2 you will be able to talk with your subscribers and also the people that are watching the same video/livestream as you.

**Comment by vraghavans** [comment]
Thanks Daniel!!
