### ISSUE TITLE
I ran git pull

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#3586]
**Describe the question**
A clear and concise description of what is your question.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by hnagasawa** [comment]
I ran git pull. Next messages display. I could not update
root@avideo-virtual-machine:/var/www/html/AVideo# git pull
error: object file .git/objects/90/867b995ca1acffd513445c3ae4adceedd09ce3 is empty
error: object file .git/objects/90/867b995ca1acffd513445c3ae4adceedd09ce3 is empty
fatal: loose object 90867b995ca1acffd513445c3ae4adceedd09ce3 (stored in .git/objects/90/867b995ca1acffd513445c3ae4adceedd09ce3) is corrupt
fatal: The remote end hung up unexpectedly

**Comment by DanielnetoDotCom** [comment]
I am not sure what that means, but you can clone the project somewhere else,

`cd /tmp && git clone https://github.com/WWBN/AVideo.git`

 then move the videos directory to the cloned folder, 

`mv /var/www/html/AVideo/videos /tmp/AVideo/videos`

double-check your folder was moved 

`ls /tmp/AVideo/videos`

then delete the old folder and move the new cloned on his place 

`rm -R /var/www/html/AVideo && mv /tmp/AVideo /var/www/html/AVideo`

this should do the trick

**Comment by hnagasawa** [comment]
Dear Daniel

I did your sugesstion.
It scuess But LoginLDAP_DYNA and LoginLDAP deleted.
Do we reinstall both plugins ?

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
Correct
