### ISSUE TITLE
User (admin) Not found

### ISSUE THREAD

**Issue by kenharad** [WWBN/AVideo#3591]
The following error occurred when logging in as admin from the website.
"Wrong user or password!"
I don't remember changing the password, but when I ran the following script to reset the password, the following error occurred.

$ cd /var/www/YouPHPTube/install
$ sudo php recoverPassword.php

Enter the username or press enter to skip:
admin
User (admin) Not found

Until a few days ago, I was able to log in as admin without any problems.
What are the possible causes and actions?

log file
```
/var/www/YouPHPTube/videos/avideo.log
82853 [03-Sep-2020 05:02:26 UTC] AVideoLog::DEBUG: Start Login Request SCRIPT_NAME: /objects/login.json.php
82854 [03-Sep-2020 05:02:26 UTC] AVideoLog::DEBUG: redirectUri: http://XXXXX/mvideos SCRIPT_NAME: /objects/login.json.php
82855 [03-Sep-2020 05:02:26 UTC] AVideoLog::DEBUG: same redirectUri: http://XXXXX/mvideos SCRIPT_NAME: /objects/login.json.php
82856 [03-Sep-2020 05:02:26 UTC] AVideoLog::DEBUG: user::login: noPass = ,codedPass = ,this->user, admin XXX.XXX.XXX.XXX SCRIPT_NAME: /objects/login.json.php
82857 [03-Sep-2020 05:02:26 UTC] AVideoLog::DEBUG: Password check new hash user not found SCRIPT_NAME: /objects/login.json.php
82858 [03-Sep-2020 05:02:26 UTC] AVideoLog::DEBUG: Error: Username and password required to register SCRIPT_NAME: /objects/login.json.php
 ```

**Comment by DanielnetoDotCom** [comment]
did you change your configuration.php for any reason?

Is your disk full?
