### ISSUE TITLE
How to use HLS plugin to encode in VP9 inplace of h264?

### ISSUE THREAD

**Issue by rkdoshi** [WWBN/AVideo#3592]
I , tried to replace format table entry of HLS configuration in yophptube and encoder databases, did not work.  How to modify encoder configuration?

**Comment by akhilleusuggo** [comment]
VP9 in HLS not gonna work ( not on the way the HLS plugin on this project is configured ) .
I've said many times to @DanielnetoDotCom about the VOD , but for now nothing . Without the VOD / Dash , not much is possible to achieve .

I know that VP9 MPEG-DASH is supported , I don't know about HLS

**Comment by akhilleusuggo** [comment]
Will not work . 100%

**Comment by rkdoshi** [comment]
Yes,checked,
Please understand that it is not about about hls+vp9 it is about ingestion
,  with vp9 it will be dash , standard installation of ffmpeg does not code
in vp9 it is vp8, have recompiled ffmpeg and started using vp9.

Our target is to reach good quality with minimum bitrate due to mobile
network internet quality in india. We are going to target regional content
which is grossly ignored till now for billion + mobiles.

We have sets of 2x4xeon cpu (40 core) servers with 10TB ssds and 128 GB Ram
each present in 3 IXs for delivery.

With your support we can make it reality. As we are not from coding side
some understanding prolems are there. Appreciate your support.

**Comment by rkdoshi** [comment]
Can you please guide how to configure encoder settings? I tried to edit
values in tables format, replacing libvpx with libvpx-vp9 does not work.
Output is still vp8.

If same ffmpeg commands are used on cli, output is vp9 encoded.

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo-Encoder/issues/289#issuecomment-685293781
