### ISSUE TITLE
Statistics not showing correctly after recent upgrade from 9.2 to 9.5

### ISSUE THREAD

**Issue by TooMeg** [WWBN/AVideo#3593]
After single step upgrade from 9.2 to 9.5 the total statistics of videos stored, viewed and length are inconsistent throughout my streaming site. For example: (These figures are all as me, Admin, and there are actually 1050 videos total, which I can browse through manually, and all of them play correctly when clicked.)

Dashboard:
 Total Videos: 1049
 Total Views: 384
 Total Duration: 4424

My Channel:
 Total Videos: 1
 Total Views: ?
 Total Duration: 202353 minutes, 20 seconds
 Disk Space: 356.82GB
 
I actually upgraded the site (9.2 to 9.3, 9.3 to 9.4, etc) using the 'Update Version' button, and did not reboot between versions. It was once I had updated to the current version that I noticed the statistics weren't showing correctly or consistently. I then tried a 'Git-Pull' as described elsewhere in the wiki, but still exactly the same. I did have to reset the permissions again within the YouPHPTube folder, but again, no difference.

If I log in as a standard user all of their statistics seem correct, although no one else has uploaded as many videos as I have, with the next highest count being 90 compared to my 1050!

Also, I have noticed that since updating when I click to use the encoder it will sometimes fail to connect to 'https://website.org/upload' but when I manually change the URL in the browser address bar to 'http://website.org/upload' it works. This isn't consistent, happening once or twice out of 10 attempts.

My site is running on one of my own VMware 5 box's on Ubuntu 18.04, has 4*vCPUs, 8GB vRAM, 40GB HDD with 2TB FC for video storage.

I have tried various browsers on CentOS, Ubuntu, Debian and windows, and the stats are being shown consistently wrong across all of them.

Please let me know if you need more info - I've checked the logs and nothing jumps out at me, but that's not to say there isn't something there you might find.

Thanks 

TooMeg

Additional:

I have removed a fair number of videos and the figures match a little better now. I wonder is there a limit of 1000 (1024) videos on the opensource version?

**Comment by DanielnetoDotCom** [comment]
Hi

By default, the returned rows are limited to 1000

check this https://github.com/WWBN/AVideo/wiki/Configuration.php-variable-(-some-are-hidden-)

> $global['rowCount'] = {1-100000}; // https://github.com/WWBN/AVideo/issues/3462 ; Default 10000

You can add the variable $global['rowCount'] in your configuration file to limit it in a different value

$global['rowCount'] = 50000; // Limit it to 50k
