### ISSUE TITLE
meet  not work on iphone 6s

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3594]
Hello @DanielnetoDotCom  I did some tests on my iphone 6s when I connect, I am disconnected within 15 seconds
I have a screen like that
![image](https://user-images.githubusercontent.com/39193219/92132751-d8574080-ee07-11ea-8214-8590579eb99a.png)

**Comment by DanielnetoDotCom** [comment]
I am having problems with chrome on the iPhone, but it works on Safari.

I guess is regarding camera access permissions.

**Comment by syldri** [comment]
I tested with safari I see my face for 2 seconds and it disconnects

![image](https://user-images.githubusercontent.com/39193219/92190633-f487cb80-ee61-11ea-96dc-50970edb0b45.png)

**Comment by DanielnetoDotCom** [comment]
Please test again, the servers were in maintenance today.

make sure you update your streamer, from 1 hour ago.
