### ISSUE TITLE
restream

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3595]
The ffmpeg line does not die after stopping the stream . That mean , nobody can start a stream before killing the PIDs manually , because the rtmp is already in use  .

**Comment by DanielnetoDotCom** [comment]
This line suppose to kill the running process

https://github.com/WWBN/AVideo/blob/8ee922efbdabfdaf37e75f7afc6a9c76bfe5a109/plugin/Live/standAloneFiles/restreamer.json.php#L150

Do you have it in your file?

**Comment by DanielnetoDotCom** [comment]
It was tested on Ubuntu, if you are running a different OS, maybe it is not returning as expected

**Comment by akhilleusuggo** [comment]
I'm on Ubuntu 18.04 too .

This is something new I believe , because I didn't updated , and I didn't even had the standAloneFiles

**Comment by akhilleusuggo** [comment]
Now the question is , only the restreamer.json.php should be moved to the restream server ? Or all the folder ?

**Comment by akhilleusuggo** [comment]
Ok , I see you have added many things ...
You may wanna give a video or something to explain . So the StandAloneFiles , should all be moved the Live-Streaming server ( in case we want also the restream ) to be on the same one .

**Comment by DanielnetoDotCom** [comment]
Correct, I separate them to make it easier to find.

I am still working on it. I will make a documentations as soon as I finish

**Comment by akhilleusuggo** [comment]
The thing daniel , can you hide some details that you're showing on restreamer.json.php and control.json.php . You're exposing some locations etc

**Comment by DanielnetoDotCom** [comment]
What details exactly?

Just to make clear what make the process secure is the token that needs to be validated on the streamer site

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/92178514-686aa980-ee4b-11ea-9220-85ddfe4c8b7f.png)
It is necessary ?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom btw , live-stream page not working ( the player probably )

`$(document).ready(function () { if (typeof player === 'undefined') { player = videojs('mainVideo',{errorDisplay: false,html5: {nativeAudioTracks: false,nativeVideoTracks: false,hls: {overrideNative: true}},liveui: true}); } player.ready(function () { var err = this.error(); if (err && err.code) { $('.vjs-error-display').hide(); $('#mainVideo').find('.vjs-poster').css({'background-image': 'url(https://www.example.com/plugin/Live/view/Offline.jpg)'}); } setTimeout(function(){ $('#cbb').click(function() { $('.vjs-overlay').fadeOut(); $('#mainVideo .vjs-control-bar').removeClass('vjs-hidden'); $('#mainVideo .vjs-control-bar').addClass('vjs-fade-out'); }); },1000); setTimeout(function(){ $('#mainVideo .vjs-control-bar').removeClass('vjs-hidden'); $('#mainVideo .vjs-control-bar').addClass('vjs-fade-out'); },3000); player.overlay({ content: $('#adOverlay').html(), debug: true, showBackground:false, attachToControlBar:false, overlays: [{ start: 'play', end: 3600, align: 'bottom-left' }] }); }); player.persistvolume({ namespace: 'AVideo' });setTimeout(function(){playerPlay(0);},500);})`

**Comment by DanielnetoDotCom** [comment]
I probably can remove those details from the response .

Regarding the player . It is working on my side .

There is something on JS console?

Did you clear your cache

**Comment by akhilleusuggo** [comment]
I cleared the cache . On the Js I see nothing .
The only thing in red are 
**:path:** `/plugin/Chat2/getRoom.json.php?room_users_id=5&lower_then_id=0&`

**Comment by DanielnetoDotCom** [comment]
Can you reproduce it on demo?

**Comment by akhilleusuggo** [comment]
The issue is coming from 
![image](https://user-images.githubusercontent.com/52116577/92179856-46265b00-ee4e-11ea-9336-6afae3f843af.png)

**Comment by DanielnetoDotCom** [comment]
Why is it printing as a text not as an HTML?

There is something on avideo log?

**Comment by akhilleusuggo** [comment]
```
[03-Sep-2020 22:32:23 UTC] AVideoLog::WARNING: The plugin [Customize::getStart] takes 1.4994 seconds to complete. URL: https://www.example.com/plugin/Live/stats.json.php?Menu IP: XXXX SCRIPT_NAME: /plugin/Live/stats.json.php
[03-Sep-2020 22:32:56 UTC] AVideoLog::WARNING: The plugin [Customize::getStart] takes 1.5105 seconds to complete. URL: https://www.example.com/plugin/Live/stats.json.php?Menu IP: XXXX SCRIPT_NAME: /plugin/Live/stats.json.php

[03-Sep-2020 22:33:55 UTC] PHP Notice:  Undefined variable: isStandAlone in /var/www/html/AVideo/plugin/Chat2/index.php(14) : eval()'d code(1) : eval()'d code on line 673
[03-Sep-2020 22:33:55 UTC] PHP Notice:  Undefined variable: isStandAlone in /var/www/html/AVideo/plugin/Chat2/index.php(14) : eval()'d code(1) : eval()'d code on line 673
```

**Comment by DanielnetoDotCom** [comment]
I found the problem, it was on the AD_Overlay plugin

**Comment by akhilleusuggo** [comment]
BTW , this line does kill the restream : 
https://github.com/WWBN/AVideo/blob/8ee922efbdabfdaf37e75f7afc6a9c76bfe5a109/plugin/Live/standAloneFiles/restreamer.json.php#L150

But it takes a long time . How much did you made it retries before killing ? I see 10 retries , but how much delay between them ? 

https://github.com/WWBN/AVideo/blob/8ee922efbdabfdaf37e75f7afc6a9c76bfe5a109/plugin/Live/standAloneFiles/restreamer.json.php#L153

**Comment by akhilleusuggo** [comment]
BTW even disabling the plugin still the error
![image](https://user-images.githubusercontent.com/52116577/92180500-dc0eb580-ee4f-11ea-98eb-e6b914014ee2.png)

**Comment by akhilleusuggo** [comment]
Ok , I see you've sent a fix , let me try it

**Comment by DanielnetoDotCom** [comment]
Regarding the kill, it will kill next time you try to restream.

The problem is I still could not detect when you interrupt the live

**Comment by akhilleusuggo** [comment]
Works , but I can't see the bare player  : 

![image](https://user-images.githubusercontent.com/52116577/92180613-26903200-ee50-11ea-8576-e05c2312810b.png)

Without the bare player the stream always show online . Usually shows offline when users tries to play the video ( stream ) and the stream is off .

> Regarding the kill, it will kill next time you try to restream.
> 
> The problem is I still could not detect when you interrupt the live

When the stream is off ( when the `on_done.php` gives a response )

**Comment by DanielnetoDotCom** [comment]
I will check the on_done.php later.

regarding the button, it will be available when you have a stream. otherwise only the poster image

**Comment by akhilleusuggo** [comment]
Good to know . Thank you :)

**Comment by JoshWho** [comment]
I solved this problem a year ago with this parameter

drop_idle_publisher 10s;

include it in the top on Nginx conf

  ```
  worker_processes  auto;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            
            
            server {
                    listen 1935;
                    ##allow play all;
		    chunk_size 4000;
                    drop_idle_publisher 10s;
                    buflen 10s;
                    idle_streams off;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            ##allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            hls_playlist_length 300s;
                            #hls_fragment 1s;
                            hls_fragment 5s;
                            on_publish http://localhost/YouPHPTube/plugin/Live/on_publish.php;
                            on_play http://localhost/YouPHPTube/plugin/Live/on_play.php;
                            on_record_done http://localhost/YouPHPTube/plugin/Live/on_record_done.php;
```

**Comment by akhilleusuggo** [comment]
@JoshWho It's about restream . Not the stream in nginx .

**Comment by JoshWho** [comment]
I understand that. This was a trick YT had to do to fix that hangup SIGKILL issue.   Sometimes the API doesn't broadcast it.

As soon as it sees not stream it starts counting 10 seconds if nothing happens restream will get a dc and then in turn shuts down the stream on restream.

**Comment by akhilleusuggo** [comment]
Thanks for the info , i'll give it a try

**Comment by DanielnetoDotCom** [comment]
Hi, I created this tutorial

https://github.com/WWBN/AVideo/wiki/Restream

@akhilleusuggo if the @JoshWho info works as expected will be a good idea improve it in the restream tutorial

**Comment by br0kenlink** [comment]
Hi, so I tried to restream to Mixcloud.
Used this link to set things up: https://github.com/WWBN/AVideo/wiki/Restream
Running on Debian Buster.
Now even though OBS is connecting, nothing shows in AVideo.
Any help would be appreciated

**Comment by DanielnetoDotCom** [comment]
If you do not restream does it work?

check the logs in your live server and also on the server where your restream file is
