### ISSUE TITLE
there is a redirect when you click on LIVE

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3596]
hello @DanielnetoDotCom 

I have the same problem on my site
I'm on your demo site, when I click the live button I have this

![image](https://user-images.githubusercontent.com/39193219/92190142-9efeef00-ee60-11ea-89e8-112e5b7b332a.png)

**Comment by DanielnetoDotCom** [comment]
The servers were in maintenance.

please try again.

**Comment by syldri** [comment]
hello, when the meet server is under maintenance, i can't access the info when i click live ?

**Comment by DanielnetoDotCom** [comment]
Probably because you have the meet enabled.

I will release an update to avoid this happen again.
