### ISSUE TITLE
Uncaught (in promise) DOMException

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3597]
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause() 

Does redirect to a link from google dev :  https://developers.google.com/web/updates/2017/06/play-request-was-interrupted

This issue happens on HLS videos . When you jump to the middle of a long video , and does load the hls_fragment , but the video does not play . It's stuck , you need to pause and play , or move back/forward to make the video play .

**Comment by DanielnetoDotCom** [comment]
Maybe a chrome issue?

On the player, there is no reference to Google.

**Comment by akhilleusuggo** [comment]
No , it's a bug that happens in last updates .

**Comment by DanielnetoDotCom** [comment]
maybe this is related with VideoJS player?

Is possible to reproduce it on the demo?

**Comment by akhilleusuggo** [comment]
on demo you have no long HLS videos .

**Comment by DanielnetoDotCom** [comment]
how long do you mean? what resolution? I can try to add one similar to yours

**Comment by akhilleusuggo** [comment]
Can I mail you with one of my videos ? I'll mail you . I don't think you wanna upload a 4h stream to a demo site ;

**Comment by DanielnetoDotCom** [comment]
I notice one thing (not sure if it is an issue), your m3u8 files have different sizes. I guess they suppose to be all the same size

![image](https://user-images.githubusercontent.com/18009293/92599870-30b39580-f281-11ea-8663-b2704d6b23f2.png)

And then when fails I notice this 

![image](https://user-images.githubusercontent.com/18009293/92600120-82f4b680-f281-11ea-93ad-bf3677742d5b.png)
![image](https://user-images.githubusercontent.com/18009293/92600376-e252c680-f281-11ea-96e1-1a68644b2377.png)


Something regarding rocket-loader https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js

Isn't it something about Cloudflare cache? can you try it without Cloudflare?

**Comment by akhilleusuggo** [comment]
I tried without cache , nothing . I'm also poiting my /etc/hosts to the main IP server , so cloudflare doesn't affect me . 
But you're right about the size HLS , and I have to fix the keyframes .

```
#EXTINF:8.333333,
index2360.ts
#EXTINF:4.166667,
index2361.ts
#EXTINF:4.166667,
index2362.ts
#EXTINF:8.333333,
index2363.ts
#EXTINF:4.166667,
```
