### ISSUE TITLE
display problem in a live plugin

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3599]
hello @DanielnetoDotCom  

i show you pictures, when i click to copy rtmp link

there is a displacement on the left side

![image](https://user-images.githubusercontent.com/39193219/92291957-46d8f300-ef1b-11ea-86aa-d6da754ea5b8.png)

![image](https://user-images.githubusercontent.com/39193219/92292119-dda5af80-ef1b-11ea-995e-4796abd6f806.png)

**Comment by DanielnetoDotCom** [comment]
Update, make sure you clear the cache, and the problem should be gone.

**Comment by syldri** [comment]
thank you so much
