### ISSUE TITLE
Reply to comment 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3604]
Not working.
Here's the video.
https://fakeotube.com/v/517?channelName=Fakeologist

**Comment by JoshWho** [comment]
I have another user that also is complaining about she is not able to reply back to her video comments.

**Comment by JoshWho** [comment]
I can also confirm i Just tested it myself. Video owner can not reply back to comment

**Comment by DanielnetoDotCom** [comment]
Sorry about that, the error should be fixed now
