### ISSUE TITLE
Backblaze/Wasabi, HLS and SecureVideosDirectory plugins

### ISSUE THREAD

**Issue by gosoaps** [WWBN/AVideo#3605]
Has the issue with Wasabi been resolved? Last year, it would fail to upload about 10% of the time.

Has the video playback issue that occurs when using the Backblaze plugin been resolved now with the HLS plugin?

Also, would the SecureVideosDirectory plugin conceal the video address of my Backblaze- or Wasabi-stored videos?

Thanks,

GOsoaps

**Comment by DanielnetoDotCom** [comment]
Hi

No HLS still not compatible with S3 or B2.

and the SecureVideosDirectory is useless if you are using one of them. but you must make the bucket private then the script will handle the token generation to access the stored file.
