### ISSUE TITLE
Seeking Ahead or back is not working anymore

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3606]
I can no longer use the seek or skip ahead 10 seconds without it restart the video.

Try here

https://www.joshwhotv.com/v/25673

**Comment by JoshWho** [comment]
Seems to work on an external site that has a video embedded but not working on the direct platform. https://www.joshwho.net/blm-mob-terrorizes-restaurant-goers-by-flipping-tables-breaking-dishes-and-throwing-chairs/

**Comment by ronaldod** [comment]
Confirmed this problem on Chromium type browsers. Not on Firefox.

**Comment by JoshWho** [comment]
ahhhhhh

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by JoshWho** [comment]
Works great now. THank you @DanielnetoDotCom

**Comment by JoshWho** [comment]
https://www.joshwhotv.com/v/25673?channelName=Rizzo

**Comment by JoshWho** [comment]
It is doing it for this video to https://www.joshwhotv.com/v/826

I was hoping it was just a cache or cloudflare issue but still does the same without cloudflare so not sure what is causing this on certain videos.

**Comment by DanielnetoDotCom** [comment]
I guess the problem is in your HD video itself.

try a direct link to the file 

https://static.joshwhotv.com/file/joshwhotv/_YPTuniqid_5c7310683ba5f0.14047177_HD.mp4

**Comment by akhilleusuggo** [comment]
probably missing the `movflags faststart`

**Comment by JoshWho** [comment]
How strange is that. Not sure why that would happen.  One thing I do know is both videos have been repaired using Swap

**Comment by JoshWho** [comment]
Also I noticed still it is skippable with firefox but not with chrome. Have we discovered a new censorship with Chrome?

**Comment by JoshWho** [comment]
Might be an answer here something about headers  https://stackoverflow.com/questions/10583931/cant-seek-html5-video-or-audio-in-chrome

**Comment by JoshWho** [comment]
Seems like it only happens to large files. SOmething is stopping Chrome from wanting to pre buffer the video.

**Comment by JoshWho** [comment]
I just manually downloaded that video https://static.joshwhotv.com/file/joshwhotv/_YPTuniqid_5c7310683ba5f0.14047177_HD.mp4 

and it works fine. Just analyzed it and nothing is broke with it.  583mb downloaded in 18 seconds

**Comment by JoshWho** [comment]
Here is another thing on it https://stackoverflow.com/questions/35751736/seeking-in-html5-video-with-chrome

**Comment by JoshWho** [comment]
It saying Chrome does not download the entire file like firefox does. How can we force chrome to buffer the file?

**Comment by akhilleusuggo** [comment]
Actually your last statement is not accurate . I have tested it on Firefox , does jump , but only to the point where the download has reached . Definitely is the movflags faststart .

Just run a `ffmpeg -i _YPTuniqid_5c7310683ba5f0.14047177_HD.mp4 -c copy -movflags +faststart -map_metadata -1 -f mp4 output.mp4` , then remove the original video and rename the video . `mv output.mp4 _YPTuniqid_5c7310683ba5f0.14047177_HD.mp4 && chown www-data:www-data _YPTuniqid_5c7310683ba5f0.14047177_HD.mp4`

**Comment by JoshWho** [comment]
Can't do that not hosted on the same server

**Comment by JoshWho** [comment]
This is the configs I use

`ffmpeg -threads 1 -i {$pathFileName} -vf scale=-2:480 -movflags +faststart -preset veryfast -vcodec h264 -acodec aac -strict -2 -max_muxing_queue_size 1024 -y {$destinationFile}`

**Comment by akhilleusuggo** [comment]
Actually this happens only on your site . Not in mine , and I've downloaded your video , and does have the movflags . ( debugged with `qtfaststart` ) . Must be something else that you've changed . 

I even uploaded the same video to my site , and work fine .

**Comment by JoshWho** [comment]
I bet it is cloudflare they are not using byte data all of a sudden

**Comment by JoshWho** [comment]
I got it fixed. Had something to do with cache everything on the static. I cache normally now and it works great.

**Comment by akhilleusuggo** [comment]
Thanks for sharing . I didn't knew that was possible to cache mp4 videos honestly .

**Comment by DanielnetoDotCom** [comment]
Hi, was it a Cloudflare issue?

I have some costumers using https://bunnycdn.com/, they never complain about it. any idea if it really works well with videos?

**Comment by DanielnetoDotCom** [comment]
> Thanks for sharing . I didn't knew that was possible to cache mp4 videos honestly .

On premium plans they can
