### ISSUE TITLE
PHP Errors

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#3609]
Hi

I'm getting a lot of PHP Notices and Warning in my AVideo.log
Any idea how to fix this?

PHP Notice:  Undefined index: rowCount in /var/www/AVideo/view/channels.php on line 30
PHP Warning:  Division by zero in /var/www/AVideo/view/channels.php on line 30

PHP Notice:  Undefined index: current in /var/www/AVideo/objects/comments.json.php on line 32
PHP Notice:  Undefined index: rowCount in /var/www/AVideo/objects/comments.json.php on line 32

Thanks

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by D-Spayre** [comment]
Thank you that fixed it...
