### ISSUE TITLE
Av video streaming working - but users can't see 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3610]
I streamed from av video android app, and it works, and it saves and publishes the video.

Problem is no one can see the video, even if I set it to public.

Here's what the user sees. ![IMG-20200907-WA0001.jpg](https://user-images.githubusercontent.com/66537018/92416174-3a76b500-f12a-11ea-9ed9-7beaf1be9fd9.jpg)

**Comment by DanielnetoDotCom** [comment]
How is the Live panel?

Did you select any user group there?

![image](https://user-images.githubusercontent.com/18009293/92645322-0f6f9b00-f2bb-11ea-92ce-ddac65ce4765.png)

**Comment by fakeologist** [comment]
Thanks that's probably it.
