### ISSUE TITLE
How does the Backblaze plugin work

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#3617]
Hi 

Newbie on Backblaze Plugin

How does the plugin work regarding backups ?   Does it automatically backup the videos once a day ?

I have setup the config in youPHPtube..

Regards

**Comment by DanielnetoDotCom** [comment]
Hi

Backblaze probably offer his own backup services https://www.backblaze.com/blog/b2-for-beginners-inside-the-b2-web-interface/

But you still need to backup your streamer videos directory and your database.

Maybe the best option for you is to use the Clone plugin https://github.com/WWBN/AVideo/wiki/Clone-Site-Plugin
