### ISSUE TITLE
Can I re-upload videos saved from my crashed server

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#3618]
Hi 

Is it possible to reload videso to this server from a previous crashed server.

Is it just ossible to put them in the Video folder of the server ?

Thanks

**Comment by DanielnetoDotCom** [comment]
If you have the database you can do that. otherwise, you will need to reprocess them to get the metadata.

I could create a script to read your videos dir and auto add the videos in the database, but you will still miss the title, description, etc. basically main metadata. I am not sure if it worth

**Comment by kollossus55** [comment]
Hi

Yes I have the database backups as well..

Do I just copy to the directories ?



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by DanielnetoDotCom** [comment]
Yes, it will probably work.
