### ISSUE TITLE
have uploaded an mp3 file-the file loads fully (53 mb) before it starts playing..

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3620]
https://www.maritimeplatform.com/v/157

Please try to listen to the above link-it does not start playing immediately.

Kindly advise

**Comment by akhilleusuggo** [comment]
You need to add something equivalent to -movflags +faststart but for audio , if your container is pure audio .
That would be `-strict -2`

**Comment by vraghavans** [comment]
Hi! Thanks for your reply.

Kindly advise what information would you require and where should I insert the above instruction please 
Thanks for support

**Comment by vraghavans** [comment]
Good Day!

Can you pls help me on this please

Thanks in advance
Rgds
Vijay
