### ISSUE TITLE
Embed is forbidden

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3622]
I am pasting my embed code in my wordpress site and I get not an error regarding Embed is forbidden.

I recently moved my WP to the same server where aVideo is located and the embeds should be fast and available.

Not sure if its a NGINX config.

Any thoughts?

https://www.flatearth.co.il/%d7%94%d7%9e%d7%90%d7%95%d7%a8%d7%95%d7%aa/%d7%9b%d7%95%d7%9b%d7%91-%d7%a1%d7%99%d7%a8%d7%99%d7%95%d7%a1-%d7%9e%d7%a9%d7%a0%d7%94-%d7%a6%d7%95%d7%a8%d7%94/

**Comment by akhilleusuggo** [comment]
make sure you don't block embed from plugin ( customize advanced , and customize user ) . Make sure you don't block them from there . Also that your don't have the SecureVideosDirectory enabled for debugging .
