### ISSUE TITLE
git pull throws error to commit or stash a file,please help

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3623]
Updating a9175082a..28b043ea6
error: Your local changes to the following files would be overwritten by merge:
        view/help.php
Please commit your changes or stash them before you merge.
Aborting

This is the message i get-I have made changes to the help file and want to retain my changes.

Kindly advise

**Comment by akhilleusuggo** [comment]
`sudo git fetch --all && sudo git reset --hard origin/master

`

**Comment by vraghavans** [comment]
its done,thanks!!
