### ISSUE TITLE
subtitles plugin

### ISSUE THREAD

**Issue by lahaj** [WWBN/AVideo#3624]
Hello  subtitles plugin is not working and please do not tell me I do such-and-such because I have used all means to solve this problem, but unfortunately it has not been solved. You offer the script for free, but most of the important bling is not free. Paid because of his previous experience, fearing that most of the blues will not work. See the pictures well to make sure that all methods of using video subtitles 
![33](https://user-images.githubusercontent.com/71000399/92566058-b8eb6800-f28c-11ea-9eae-fc2249f011e2.JPG)
![44](https://user-images.githubusercontent.com/71000399/92566065-ba1c9500-f28c-11ea-91c0-81ffe4bd4565.JPG)
![55](https://user-images.githubusercontent.com/71000399/92566066-bab52b80-f28c-11ea-92f1-2b4cdaca1f27.JPG)

 have been used, but to no avail.
I ask you to give me a final solution to do this plan in the right way so that I can have a good impression because the beginning is the basis of every good or bad transaction
Thank you very much
Accept my respect

**Comment by DanielnetoDotCom** [comment]
What AVideo version are you using?

Note here the plugin is working with the latest version https://demo.avideo.com/video/275/subtitle-test?channelName=TheAdminChannel

If you are in the latest AVideo version please provide your JS Console screenshot

**Comment by lahaj** [comment]
Thank you for your reply
But where do I find the JS Console

**Comment by DanielnetoDotCom** [comment]
Here https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Also please check your AVideo version. make sure you are running the latest: https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by lahaj** [comment]
Thank you very much. I failed in all attempts. It is not a problem. I will delete the script from the server, and I thought as soon as I bought the plugin it would work, but this issue bothered me a lot
And for your information, I bought 2 bling and the other works for video resolution even though I was thinking of subscribing to your server whose value is 120 dollars, but after all this I do not want anything
Dear sir, you can close this ticket and I am sorry for the inconvenience
This is 3 times when I was deceived by everything I buy a video player or PLANE in which I find a problem and after that the help is not provided to me in an understandable and easy way
And the only JW player that worked for me
Excellent and without any problems
Sir, you can close this ticket even though I paid for this bill. Thank you very much

**Comment by DanielnetoDotCom** [comment]
I hope you change your mind and give one more try on AVideo

**Comment by lahaj** [comment]
Pelagin is worth $ 19 in order to solve the problem. Technical support requires fifty dollars an hour
What is this logic on the gloom. I am one of your clients withdrawing and I will advise my friends not to add this complex script
Thank you very much, and you can leave the ticket

**Comment by lahaj** [comment]
I asked for a solution, and I knew that this issue will end. There is no solution, so I will go here and go there and do such-and-such

**Comment by DanielnetoDotCom** [comment]
Sorry, look like to me you do not want support. you do not want to provide information to help you resolve that problem

**Comment by lahaj** [comment]
How do I not want the solution? I want the easiest solution and not a complicated solution. I liked the script and installed it on the server. I decided to buy several add-ons. Indeed, I bought two add-ons, the first that works and the second does not work. I swear to you.
Why do I not want a solution? I definitely want a solution

**Comment by DanielnetoDotCom** [comment]
sorry, there is no easy or complicated solution, there is only the correct solution. without the requested information, there is nothing I can do.

**Comment by lahaj** [comment]
I told you about the problem and brought you some pictures that prove what the problem is, and I am with you until you find me a solution

**Comment by DanielnetoDotCom** [comment]
I cannot find you a solution from some pictures, sorry.

**Comment by DanielnetoDotCom** [comment]
> Here https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors
> 
> Also please check your AVideo version. make sure you are running the latest: https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

Here is what I need, if you cannot provide this because is too complicated, you should hire someone else to do.

**Comment by DanielnetoDotCom** [comment]
FYI, you must make sure you are running AVideo 9.5 (current version)

If you are not, the first step is to upgrade it.

**Comment by lahaj** [comment]
Dear sir I am using v9.5

**Comment by DanielnetoDotCom** [comment]
Ok, good, then check your JS console. screenshot and place here

**Comment by lahaj** [comment]
![66](https://user-images.githubusercontent.com/71000399/92652689-559a1e00-f2fe-11ea-90b0-308d6aff884f.JPG)

**Comment by DanielnetoDotCom** [comment]
Or, give here the link for the video that supposes to have a subtitle I will check the console log

**Comment by lahaj** [comment]
https://mrtet.com/video/2/mulan.2020.1080p.webrip.x264.aac5_.1-mixtime.net__hd

**Comment by lahaj** [comment]
This video is for a trial and I have added subtitles to it and the subtitles are not working

**Comment by DanielnetoDotCom** [comment]
I am checking already, hold on

**Comment by lahaj** [comment]
ok sir

**Comment by DanielnetoDotCom** [comment]
Is this an embed video?

the subtitle requires a self-hosted video. please read this https://github.com/WWBN/AVideo/wiki/About-Video-Upload

**Comment by lahaj** [comment]
I previously uploaded the same video and tried to translate it, and it didn't work
I have read everything, but sir, to no avail

**Comment by DanielnetoDotCom** [comment]
Anyway, I cannot see a reason why not load the subtitles on the embed videos.
please try this update.

**Comment by lahaj** [comment]
Everything updated, I understand from your response that there is no solution even though the bowling is paid and not free

**Comment by DanielnetoDotCom** [comment]
I am pretty sure there is a solution and I am trying to help you, if you keeping being rude like this I will stop. (last warning)

**Comment by lahaj** [comment]
thank you

**Comment by DanielnetoDotCom** [comment]
can you update your streamer site now? I just sent updates

**Comment by lahaj** [comment]
Thank you, dear sir. I am working on updating the code. I will get back to you, sir

**Comment by lahaj** [comment]
Thank you, dear sir, I tried to update the file, but unfortunately it was not set with me. I appreciate your patience and thank you for your interest.
And I did not understand these numbers because the file on the server has one number
And the code in which you sent me two lines for numbers I did not understand
I feel that after changing these codes, the translation will work
I am asking you to request that if you do not mind, can you send me the two files with full codes, or I will upload them to the server if you please, and please

**Comment by DanielnetoDotCom** [comment]
Hi, sorry what do you mean numbers?

Is highly recommended you use the git pull command to update, otherwise, you may face problems

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by lahaj** [comment]
![77](https://user-images.githubusercontent.com/71000399/92666756-2e9e1500-f31b-11ea-8655-0d7a6e2f7f66.JPG)
![Uploading 88.JPG…]()

**Comment by lahaj** [comment]
![88](https://user-images.githubusercontent.com/71000399/92666796-45446c00-f31b-11ea-885f-de293bcfb70b.JPG)

**Comment by lahaj** [comment]
You are a wonderful person. Thank you very much and for your patience. In the end, we want to come up with its results, and this is what I mean, my dear brother. I tried to update the codes, but unfortunately I failed

**Comment by DanielnetoDotCom** [comment]
Ok, first you have to make sure you have all the files up to date

then the subtitle plugin was designed to self-hosted videos. you were using an MP4 video hosted on another site.

try to upload an MP4 or encode.

**Comment by lahaj** [comment]
Thank you very much and thank you for your patience. The problem was solved because I deleted the script and installed another script from the page that you sent to me. There is a link and I downloaded the script and installed it and the translation is working now, but there is a translation problem only. In the picture, my dear brother, and I repeat my thanks a lot to you
And on your understanding and patience as you see what is the solution to these confused symbols
![99](https://user-images.githubusercontent.com/71000399/92668743-baff0680-f320-11ea-824f-c3eafd258b1b.JPG)

**Comment by DanielnetoDotCom** [comment]
I am glad we had some progress

Try to check this option, then you will need to save the file again.

![image](https://user-images.githubusercontent.com/18009293/92668878-60e14f80-f2e6-11ea-84f6-6a326fd2966e.png)

**Comment by lahaj** [comment]
Thank you for your help. Now the program works perfectly only in a form and does not work in a form. I thank you, my brother, for this wonderful cooperation and attention. The problem has been solved. Can I ask about this plugin? Does it support external links or only supports self-uploaded files
And how many video resolutions
![100](https://user-images.githubusercontent.com/71000399/92669864-c3a50c00-f323-11ea-92b4-d59643a2b471.jpg)

**Comment by lahaj** [comment]
only srt  no vtt file

**Comment by lahaj** [comment]
Everything works fine, but I have a note please if you put the video on another site
Embed this way
There is no translation option at all Is there a solution to this problem because I am in the process of buying a full server and I want to make sure everything is good
I thank you because you helped me a lot today

**Comment by DanielnetoDotCom** [comment]
Yes, the subtitle suppose to work on embed videos as well

**Comment by lahaj** [comment]
Hello dear sir
how are you
Everything is ok
 the subtitle does not work if Embed a Video on another site
But it works if I upload the video encod via either.

**Comment by lahaj** [comment]
I mean, if I Embed it on another website
