### ISSUE TITLE
Search not working 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3628]
I can't get the search to find the simplest title in app or browser. 

Check here.

https://vm.tiktok.com/ZS56uLqv/

**Comment by DanielnetoDotCom** [comment]
Can you please enable the gallery plugin then try again?

**Comment by fakeologist** [comment]
Done no difference.

**Comment by DanielnetoDotCom** [comment]
I just tested in your site and it works

for example this https://fakeotube.com/?search=australian

**Comment by fakeologist** [comment]
I tried "you can't" and it switched it to "you cant" (it removed the apostrophe) resulting in a failed search.

**Comment by DanielnetoDotCom** [comment]
the quote is removed to prevent SQL injection and XSS attacks, I am not sure if I can NOT remove it now.

**Comment by fakeologist** [comment]
No problem. I will take them out of future titles. Please fix the search in the app to wait for a search or return key press.

**Comment by DanielnetoDotCom** [comment]
I am adding an update on the mobilemanager plugin 

check the option doNotAutoSearch and the next Mobile version will search only after press enter

**Comment by fakeologist** [comment]
> 
> 
> I am adding an update on the mobilemanager plugin
> 
> check the option doNotAutoSearch and the next Mobile version will search only after press enter

I clicked this, and it's still autosearching.

**Comment by DanielnetoDotCom** [comment]
I still need to update the mobile apps to make it work, I hope some update by next week
