### ISSUE TITLE
Unable to Change Password - Permission Denied as Admin 

### ISSUE THREAD

**Issue by DYOR-app** [WWBN/AVideo#3629]
Hi there,

My new server has just been set up. 

As a security measure one of the first things it is necessary to do is to change the admin user password. However the "Update Your User" panel is not allowing me to do this. Every time I try and change the password, I get logged out at the same time as an error message pops up that says I'm not logged in. See screenshots.

![Screenshot 2020-09-09 at 21 20 18](https://user-images.githubusercontent.com/55331515/92649506-0b577380-f2e3-11ea-99ab-3b61cb387138.png)

![Screenshot 2020-09-09 at 21 21 07](https://user-images.githubusercontent.com/55331515/92649507-0bf00a00-f2e3-11ea-98de-bd6a83f8ab89.png)

![Screenshot 2020-09-09 at 21 20 18](https://user-images.githubusercontent.com/55331515/92649461-f5e24980-f2e2-11ea-8704-3872eba88fd9.png)

Also, when I try and change the password in 'Users' under the admin menu, I get a "permission denied" message. As the admin I should have permissions to do whatever I like in the backend, but this is not the case.

Any help resolving this issue would be very much appreciated as I can't go any further until this security issue / bug is resolved.

-I'm using a MAC desktop 
-MAC os v 10.14.6
-Brave Browser

Many thanks
Allan

**Comment by DanielnetoDotCom** [comment]
Can you please check if your server disk is full?

**Comment by DYOR-app** [comment]
I certainly hope not, because it's a brand new server that's supposed to have 2TB of space and I haven't even started yet? It was only setup today.

**Comment by DYOR-app** [comment]
no, the server is not full. There are only 4 videos totalling about 200mb

**Comment by DanielnetoDotCom** [comment]
then check your log files.

**Comment by DYOR-app** [comment]
Hi, 
I have what I believe is the relevant entries of the log file, but I don't want to publish that here for obvious security reasons. So, it is ok if i send it to you via email?
Hopefully you can help me get this issue resolved so I can move forward. 
Many thanks

**Comment by DanielnetoDotCom** [comment]
Please remove what you think may be a security issue then share it here

**Comment by DYOR-app** [comment]
Sep  9 19:39:53 ubuntu sshd[14992]: pam_unix(sshd:session): session opened for user root by (uid=0)
Sep  9 19:39:53 ubuntu systemd-logind[1022]: New session 38 of user root.
Sep  9 19:41:00 ubuntu sshd[15097]: Invalid user user from 195.54.160.183 port 59289
Sep  9 19:41:00 ubuntu sshd[15097]: pam_unix(sshd:auth): check pass; user unknown
Sep  9 19:41:00 ubuntu sshd[15097]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=195.54.160.183
Sep  9 19:41:02 ubuntu sshd[15097]: Failed password for invalid user user from 195.54.160.183 port 59289 ssh2
Sep  9 19:41:02 ubuntu sshd[15097]: Received disconnect from 195.54.160.183 port 59289:11: Client disconnecting normally [preauth]
Sep  9 19:41:02 ubuntu sshd[15097]: Disconnected from invalid user user 195.54.160.183 port 59289 [preauth]
Sep  9 19:41:02 ubuntu sshd[15099]: Invalid user admin from 195.54.160.183 port 7975
Sep  9 19:41:02 ubuntu sshd[15099]: pam_unix(sshd:auth): check pass; user unknown
Sep  9 19:41:02 ubuntu sshd[15099]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=195.54.160.183
Sep  9 19:41:04 ubuntu sshd[15099]: Failed password for invalid user admin from 195.54.160.183 port 7975 ssh2
Sep  9 19:41:04 ubuntu sshd[15099]: Received disconnect from 195.54.160.183 port 7975:11: Client disconnecting normally [preauth]
Sep  9 19:41:04 ubuntu sshd[15099]: Disconnected from invalid user admin 195.54.160.183 port 7975 [preauth]
Sep  9 19:41:05 ubuntu sshd[15101]: Invalid user admin from 195.54.160.183 port 14995
Sep  9 19:41:05 ubuntu sshd[15101]: pam_unix(sshd:auth): check pass; user unknown
Sep  9 19:41:05 ubuntu sshd[15101]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=195.54.160.183
Sep  9 19:41:07 ubuntu sshd[15101]: Failed password for invalid user admin from 195.54.160.183 port 14995 ssh2
Sep  9 19:41:07 ubuntu sshd[15101]: Received disconnect from 195.54.160.183 port 14995:11: Client disconnecting normally [preauth]
Sep  9 19:41:07 ubuntu sshd[15101]: Disconnected from invalid user admin 195.54.160.183 port 14995 [preauth]
Sep  9 19:41:21 ubuntu sshd[14992]: pam_unix(sshd:session): session closed for user root
Sep  9 19:41:21 ubuntu systemd-logind[1022]: Removed session 38.
Sep  9 19:42:17 ubuntu sshd[15103]: Accepted password for root from 90.241.94.191 port 53626 ssh2
Sep  9 19:42:17 ubuntu sshd[15103]: pam_unix(sshd:session): session opened for user root by (uid=0)
Sep  9 19:42:17 ubuntu systemd-logind[1022]: New session 39 of user root.
Sep  9 19:43:45 ubuntu sshd[15103]: pam_unix(sshd:session): session closed for user root
Sep  9 19:43:45 ubuntu systemd-logind[1022]: Removed session 39.
Sep  9 19:50:43 ubuntu sshd[854]: Received disconnect from 90.241.94.191 port 53149:11: disconnected by user
Sep  9 19:50:43 ubuntu sshd[854]: Disconnected from user root 90.241.94.191 port 53149
Sep  9 19:50:43 ubuntu systemd-logind[1022]: Removed session 29.
Sep  9 19:50:43 ubuntu sshd[854]: pam_unix(sshd:session): session closed for user root
Sep  9 19:58:43 ubuntu sshd[15172]: Connection closed by 49.235.83.136 port 35774 [preauth]
Sep  9 20:09:01 ubuntu CRON[15177]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep  9 20:09:01 ubuntu CRON[15177]: pam_unix(cron:session): session closed for user root
Sep  9 20:11:01 ubuntu CRON[15251]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep  9 20:11:01 ubuntu CRON[15251]: pam_unix(cron:session): session closed for user root
Sep  9 20:34:15 ubuntu sshd[15259]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=23.98.158.108  user=root
Sep  9 20:34:17 ubuntu sshd[15259]: Failed password for root from 23.98.158.108 port 58908 ssh2
Sep  9 20:34:17 ubuntu sshd[15259]: Connection closed by authenticating user root 23.98.158.108 port 58908 [preauth]
Sep  9 20:39:01 ubuntu CRON[15262]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep  9 20:39:01 ubuntu CRON[15262]: pam_unix(cron:session): session closed for user root
Sep  9 20:41:48 ubuntu sshd[15337]: Connection closed by 180.71.58.82 port 45419 [preauth]
Sep  9 21:02:44 ubuntu sshd[15342]: Connection closed by 185.132.1.52 port 60710 [preauth]
Sep  9 21:07:04 ubuntu sshd[15344]: Connection closed by 192.241.236.162 port 39378 [preauth]
Sep  9 21:09:01 ubuntu CRON[15361]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep  9 21:09:01 ubuntu CRON[15361]: pam_unix(cron:session): session closed for user root
Sep  9 21:11:01 ubuntu CRON[15440]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep  9 21:11:01 ubuntu CRON[15440]: pam_unix(cron:session): session closed for user root
Sep  9 21:14:24 ubuntu sshd[15455]: Did not receive identification string from 85.209.0.102 port 56170
Sep  9 21:14:26 ubuntu sshd[15456]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=85.209.0.102  user=root
Sep  9 21:14:28 ubuntu sshd[15456]: Failed password for root from 85.209.0.102 port 55256 ssh2
Sep  9 21:14:33 ubuntu sshd[15456]: Connection closed by authenticating user root 85.209.0.102 port 55256 [preauth]
Sep  9 21:14:33 ubuntu sshd[15457]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=85.209.0.102  user=root
Sep  9 21:14:35 ubuntu sshd[15457]: Failed password for root from 85.209.0.102 port 55212 ssh2
Sep  9 21:14:35 ubuntu sshd[15457]: Connection closed by authenticating user root 85.209.0.102 port 55212 [preauth]
Sep  9 21:39:01 ubuntu CRON[15484]: pam_unix(cron:session): session opened for user root by (uid=0)

**Comment by DanielnetoDotCom** [comment]
This is the syslog I meant the avideo log.

**Comment by DYOR-app** [comment]
Cn you please tell me the path where to find the avideo log?

**Comment by DanielnetoDotCom** [comment]
Sure , please check this https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by DYOR-app** [comment]
Ok, I located the log file, but now I can't access it!
![Screenshot 2020-09-10 at 12 57 29](https://user-images.githubusercontent.com/55331515/92726291-47331d00-f365-11ea-9440-69141f9ce4ca.png)

**Comment by DanielnetoDotCom** [comment]
That is what I mean on the email I sent to you.

Did you turn on the firewall?

Or changed something on the ssh?

I also cannot connect anymore

**Comment by DYOR-app** [comment]
No, I'm not aware of any firewall. 
I didn't change anything, I just tested to see if I could login using SSH yesterday. 
Today I was accessing files via filezilla.

**Comment by DanielnetoDotCom** [comment]
Ok, no worries, I will hard reboot the server and see if something changes, if I still cannot connect do you authorize a full reinstallation? (format and reinstall all over)

**Comment by DYOR-app** [comment]
Yes please, that's fine. 
Please do a full reinstallation if necessary.
Thank you

**Comment by DanielnetoDotCom** [comment]
FYI, it look like an Network error, the ticket is opened and our team of technicians on site (operational 24/7), has been informed
of the fault and will intervene on your machine.

Please be aware that other interventions may currently be in progress and
an intervention lasts on average 30 minutes per machine.

We are therefore not able to give you more details on the starting time
of the intervention.

**Comment by DYOR-app** [comment]
Ok, thank you.

**Comment by syldri** [comment]
I confirm that I have the same problem I cannot change a user's passwords

![image](https://user-images.githubusercontent.com/39193219/92771732-706ea000-f39b-11ea-8870-4e99ff156f91.png)

**Comment by DanielnetoDotCom** [comment]
Sorry bug found

**Comment by syldri** [comment]
thank you so much @DanielnetoDotCom
