### ISSUE TITLE
Live STream Login Error Message

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3630]
Could this please be changed to "Sorry, You must be logged in,  to use the LIve Stream Dashboard"

<img src="https://static.buddylist.co/liveerror.png" style='width:100%;' border="0" alt="Null">

Some users see that message and feel like they been banned or do not have the privilege to stream.

**Comment by DanielnetoDotCom** [comment]
I will send an update where you will be able to customize this message with streamDeniedMsg parameter
