### ISSUE TITLE
Tooltip over option

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#3634]
The tooltip for the multilanguage menu selector must have avoid down orientation. With fewer language options, the first one always is impossible to select because the tooltip covers it:

![Screen Shot 2020-09-10 at 13 13 17](https://user-images.githubusercontent.com/12404245/92769985-7fd3f600-f367-11ea-9551-093bf25bfced.jpg)

I can change it into my own code, but it might be wise to change in the source...

**Comment by mhajder** [comment]
@DanielnetoDotCom It already looks fixed in the code. Feel free to close it.
