### ISSUE TITLE
Hello how do I access the source code?

### ISSUE THREAD

**Issue by desenvolvedoranonny** [WWBN/AVideo#3636]
Sorry but could someone help me please! the platform is great but it is very complicated to customize it. How can I do to put more personalis; 'when I want to put a Carousel, change the NAVbar to put a righsidebar. but I don’t find the files to be able to do that.

**Comment by DanielnetoDotCom** [comment]
First, download the code, then you will find the files.

FYI, I do not think this will be as easy as you expect.
