### ISSUE TITLE
Short code for url links 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3638]
Any way I can to have urls look like this Fakeotube.com/efg3xy

**Comment by DanielnetoDotCom** [comment]
Did you try to use the permalink?

For example this https://fakeotube.com/v/375

![image](https://user-images.githubusercontent.com/18009293/92941258-85dcdc00-f426-11ea-9cad-2948da5447a5.png)

**Comment by fakeologist** [comment]
Where is that link in the sharing menu? All the ones I see are longer with the channel name.

**Comment by DanielnetoDotCom** [comment]
Uncheck the CustomizeUser->addChannelNameOnLinks

![image](https://user-images.githubusercontent.com/18009293/92943357-0dc3e580-f429-11ea-8be5-f30182c312c3.png)

**Comment by fakeologist** [comment]
So many hidden settings thanks!
