### ISSUE TITLE
Please  add auto play off feature to ad_server plugin

### ISSUE THREAD

**Issue by freedomshare** [WWBN/AVideo#3639]
Please auto play off to ad server plugin 
When  you load a video with a video ad it will auto play and then browser policy kicks in should have a feature that you can turn auto play off till someone clicks play 

Other wise the ads will ask for mute settings an can stop youtube videos from working with sound on browsers

**Comment by akhilleusuggo** [comment]
you need to disable auto-play on site configuration : 

![image](https://user-images.githubusercontent.com/52116577/92872524-ca5c7d80-f40e-11ea-8f2f-35678ccbc376.png)

**Comment by freedomshare** [comment]
> you need to disable auto-play on site configuration :
> 
> ![image](https://user-images.githubusercontent.com/52116577/92872524-ca5c7d80-f40e-11ea-8f2f-35678ccbc376.png)

It is off video ad still auto play soon as  page loads with out click play
