### ISSUE TITLE
How to encode mp4-videos in fullhd?

### ISSUE THREAD

**Issue by hubsi-k** [WWBN/AVideo#3640]
Sorry guys, maybe I'm a dummy, but can someone tell me detailed which settings I have to make to encode mp4-videos in fullhd.
Thank you and greetings

**Comment by akhilleusuggo** [comment]
On the encoder , you need to set the resolution that you want .
Change the ffmpeg command line as you need : 
![image](https://user-images.githubusercontent.com/52116577/92888085-afddd080-f41d-11ea-955a-8b7d1769fb1b.png)

**Comment by hubsi-k** [comment]
Sorry, but can you please send me some more detailed informations how to change the ffmpeg command line for a fullhd-resolution. I'm a newbie and my system engineer has no time. So it's time für DIY ...

**Comment by akhilleusuggo** [comment]
with full resolution I understand 1080p , you need to change the `scale=-2:720` to , `scale:-2:1080`
