### ISSUE TITLE
Live Stream auto starts in 9.5

### ISSUE THREAD

**Issue by SimpleMinion** [WWBN/AVideo#3641]
After upgrading from 8.x to 9.5 we noticed this behavior on a live stream. When connecting to a live stream now, both direct or embedded, the stream automatically starts. Is it possible to disable this feature and require that the end user click on play to start their stream? I have changed the "Autoplay Video on Load Page" option from disabled to enabled and back to disabled and the behavior doesn't change.

**Comment by DanielnetoDotCom** [comment]
Please check here https://github.com/WWBN/AVideo/wiki/Autoplay-and-Browser-Policies#autoplay-behaviors

**Comment by DanielnetoDotCom** [comment]
Or check this

![chrome-capture (1)](https://user-images.githubusercontent.com/18009293/92963187-72426d00-f448-11ea-884f-b36128affbc9.gif)

**Comment by SimpleMinion** [comment]
I did try this, and they continued to start automatically on both settings (mine is set to not autoplay). I also looked into the autoplay & browser policies and I assume that that is the issue. I had our web designer from outside my domain/ip address area check, and theirs did not autoplay. I was just hoping that there was a way of disabling it that I couldn’t find.

Thanks

**Comment by DanielnetoDotCom** [comment]
Hi I will send some updates soon that the live autoplay will respect the autoplay set for VOD videos
