### ISSUE TITLE
Chat2 Getting 404

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#3642]
Updated Chat2 plugin but when I activate feature.  It shows 404.

[
![404-Chat](https://user-images.githubusercontent.com/739391/92987100-64630b00-f48d-11ea-9766-060758615942.png)
](url)

**Comment by DanielnetoDotCom** [comment]
Can you please screenshot your Chat2 plugin parameters?

**Comment by willpower68** [comment]
@DanielnetoDotCom  yes of course
![Chat Parameter 1](https://user-images.githubusercontent.com/739391/93002657-8056c300-f506-11ea-94c8-110b82e4b3e2.png)
![Chat Parameter 2](https://user-images.githubusercontent.com/739391/93002658-8056c300-f506-11ea-8fe3-f927b2363fb2.png)

**Comment by DanielnetoDotCom** [comment]
Please make sure you update your streamer site

**Comment by willpower68** [comment]
@DanielnetoDotCom I am running version 9.5

**Comment by DanielnetoDotCom** [comment]
Can you please share some links? 

Also the fail chat link?

Please check if your chat is version 3.1

**Comment by willpower68** [comment]
@DanielnetoDotCom 

I sent the wrong chat2 parameters.  This site is running version 9.5.  Below is linke  

https://videolist.it/video/home-for-sale-summerlin-679k-pool-bbq-outdoor-living-2-879-sqft-4-beds-4-5-baths-3c/page/1?channelName=5d8271521c761

https://videolist.it/video/free-car-july-clearance-sale-classic-cars-for-sale-250-3850-2/page/1?channelName=5d8271521c761



![videolist-chat-parameters-1](https://user-images.githubusercontent.com/739391/93004955-55766a00-f51a-11ea-8d8f-981815d77759.png)
![videolist-chat-parameters-2](https://user-images.githubusercontent.com/739391/93004956-560f0080-f51a-11ea-8f15-5bca752437f2.png)

**Comment by DanielnetoDotCom** [comment]
I accessed the links from my mobile and I did not see any chat

**Comment by willpower68** [comment]
showChatOnlyForLoggedUsers was enabled.  You should be able to see the issue with Chat2

https://videolist.it/video/sold-vegas-luxury-real-estate-for-sale---360-e.-desert-inn-road-penthouse-1902-las-vegas-nv-89109/page/1?channelName=5d8271521c761

**Comment by DanielnetoDotCom** [comment]
Your iframe has this address 

**videolist.it/chat-realtors**?room_users_id=1&iframe=1&noFade=1

where does it come from?

I guess you set up an external server and you did it wrong

![image](https://user-images.githubusercontent.com/18009293/93006379-d68d2b80-f531-11ea-90b4-0bbfb7119693.png)

this is the correct way https://github.com/WWBN/AVideo/wiki/Chat2-Plugin#stand-alone-chat-server

**Comment by willpower68** [comment]
@DanielnetoDotCom  ahhh yes.  Thanks.  I was trying out the new features and forgot that I did that.   Thank you.
