### ISSUE TITLE
Meet can't live stream

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#3643]
I am trying to test the live streaming for an upcoming meeting.  Here are some issues that I am seeing

![image](https://user-images.githubusercontent.com/62782361/92988588-83b06700-f492-11ea-96cd-e40b67ec5ab8.png)
The live stream has failed over several attempts to live stream. Both servers are working at this time.

![image](https://user-images.githubusercontent.com/62782361/92988619-d25e0100-f492-11ea-972e-f684b97983c3.png)
It still not streaming at all, so I noticed this on Meet
![image](https://user-images.githubusercontent.com/62782361/92988639-f883a100-f492-11ea-94ba-3dd439104541.png)
It says to enter your YouTube stream key here...what does that mean?

Also, there's no way to invite anyone to Meet

What's going on...I updated everything that I know of

**Comment by DanielnetoDotCom** [comment]
Hi

you must use our Meet premium servers to live stream, it will not work with the regular Jitsi

please check here https://github.com/WWBN/AVideo/wiki/Meet-Plugin#types-of-servers

**Comment by DanielnetoDotCom** [comment]
Also I notice your live is offline https://impstreams.com:444/stat

**Comment by CROSSMediaNet** [comment]
Okay...got the live stream up and running and I do have the premium servers to stream live.  Thanks!!! Quick question: how to invite people to your meeting? It was an option beforehand and it is gone.

**Comment by DanielnetoDotCom** [comment]
No, the premium servers are for the Meet

you should see a meet link in the live, or you may want to share the meet link itself

**Comment by CROSSMediaNet** [comment]
Okay...let me ask the question another way...how to invite a guest to join to Meet...it was there beforehand

**Comment by CROSSMediaNet** [comment]
Or this is the place to invite a guest to Meet: 
![image](https://user-images.githubusercontent.com/62782361/93000168-26e19a80-f4ec-11ea-9887-fb59d7fc6c01.png)

**Comment by DanielnetoDotCom** [comment]
Yes you can invite from this panel but I will improve it . You may have some updates this week

**Comment by CROSSMediaNet** [comment]
Okay...also, we did the meeting, however, the live stream shut down at 9 seconds:
![image](https://user-images.githubusercontent.com/62782361/93007486-04bd3c00-f52f-11ea-9ca6-a1e5bac3f496.png)
I did live stream again after we were done with the meeting:
![image](https://user-images.githubusercontent.com/62782361/93007499-3209ea00-f52f-11ea-8ce9-7d49e962eefe.png)
It works when it is just me for live streaming, now I did had the meeting, but it was not able to stream live at all...could it be that the stream was private, or the server in Europe was not reachable?

**Comment by DanielnetoDotCom** [comment]
Hi, 

thanks for the report.

I notice when you first deploy the server the first live transmission is weird. then you refresh the browser and wait couple minutes and try again, then all goes good.

but I do not understand, are you saying you cannot make lives now?

**Comment by CROSSMediaNet** [comment]
It can, but beforehand, it was a problem

**Comment by DanielnetoDotCom** [comment]
As I mention, the first one usually is a problem, but can you please try again and check if is working?

**Comment by CROSSMediaNet** [comment]
Sure...give me a few minutes

**Comment by CROSSMediaNet** [comment]
We are good!!!!
![image](https://user-images.githubusercontent.com/62782361/93007931-561bfa00-f534-11ea-8f66-b1608592df9c.png)
