### ISSUE TITLE
Postfix Email Setup - Email Send Command Syntax Error

### ISSUE THREAD

**Issue by DYOR-app** [WWBN/AVideo#3645]
Hi,

I've been working my way through the instructions to setup email on my server by installing Postfix. 

But I keep getting the following error when it comes to sending the first test email:

**Step 7: Initialize the Maildir and Test the Client**
$ echo 'init' | mail -s 'init' -Snorecord sammy

results in:

**mail: invalid option -- 'S'**

It doesn't seem to recognise the -s option?
Really struggling with this, I've spent about 7 hours trying to get email installed and setup which is now driving me nuts!

Any help would be appreciated.
Thanks

**Comment by DanielnetoDotCom** [comment]
Sorry I cannot help you much on it . I strongly recommend you to use a SMTP provider
