### ISSUE TITLE
VideoThumbnails do not appear

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#3646]
Hello,
when the video is encoded in Multi Bitrate HLS format the thumbnails are not displayed
while when encoding in HD format the thumbnails are displayed normally
I have the latest version of the plugin VideoThumbnails 

Any help??

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
I guess you need to whitelist your encoder on your VideoHLS plugin or disable the download protection 

Check your log you will get some clue there 

I additional Please confirm me if you recompile your FFMPEG for restream?

If you did compile it again with the updated instructions 

https://github.com/WWBN/AVideo/wiki/Restream#compile-ffmpeg-with-openssl-support

The first compile version was missing the webp support

**Comment by ganddser** [comment]
@DanielnetoDotCom having the same issue VideoHLS plugin not installed download protection not enabled. Recompiled FFMPEG but it's still not working...

**Comment by DanielnetoDotCom** [comment]
Please check your log files, the streamer and the encoder log files.

**Comment by ganddser** [comment]
What do I need to look for in the logs?

**Comment by DanielnetoDotCom** [comment]
Not, sure, I am asking to share so we can try to find a clue

**Comment by ganddser** [comment]
The avideo log has all sensitive information in there

**Comment by DanielnetoDotCom** [comment]
before share you can try to find and replace your domain
