### ISSUE TITLE
problem with the footer

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3647]
hello @DanielnetoDotCom  this code distorts the footer

![image](https://user-images.githubusercontent.com/39193219/93009772-10d3e880-f585-11ea-9254-9b3d590d4042.png)

![image](https://user-images.githubusercontent.com/39193219/93009867-31507280-f586-11ea-906f-cbbe12eb594f.png)

there is a problem when you scroll the page, the whole page is shaking
see the video

https://www.youtube.com/watch?v=-_lUt-gUCuE

**Comment by JoshWho** [comment]
Footer seems to be really high up for some reason It is covering the body

**Comment by JoshWho** [comment]
Any temp solutions for now?

**Comment by tonuzo** [comment]
Same problem here..

**Comment by tonuzo** [comment]
`footer style="position: relative; `

This works, but still footer "auto hides" from the bottom of the page. 

Can "auto hide" be removed somehow?

**Comment by JoshWho** [comment]
@DanielnetoDotCom will fix it soon. I would just let it stay hidden for now just for a few more hours

**Comment by DanielnetoDotCom** [comment]
@tonuzo what features is it hiding?

**Comment by JoshWho** [comment]
The whole footer is showing in the bottom of the body of the website

**Comment by DanielnetoDotCom** [comment]
@JoshWho can you please screenshot?

also if you disable the menu autohide it will also not autohide the footer

**Comment by JoshWho** [comment]
I didn't know autohide was a thing LOL

**Comment by DanielnetoDotCom** [comment]
Hoo I see, you do not have the autohide active. hold on

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/93016055-bb9fd300-f594-11ea-8b7b-09bd98f69511.png)

**Comment by JoshWho** [comment]
<img src="https://static.buddylist.co/footererror.png" style='width:100%;' border="0" alt="Null">

**Comment by tonuzo** [comment]
when footer position is fixed, it will hide things. But it should be relative so it works right.

Autohide deactive works.

**Comment by JoshWho** [comment]
Body just needs to be little more taller

**Comment by syldri** [comment]
hello how ugly on your site @JoshWho

**Comment by JoshWho** [comment]
IKR

**Comment by syldri** [comment]
@JoshWho  if @DanielnetoDotCom  does not solve this problem with each update it will be necessary to edit the file

I don't understand why he added this code

**Comment by JoshWho** [comment]
He is working on it. Im sure it will be fixed soon.

**Comment by DanielnetoDotCom** [comment]
Please check if it is better now

**Comment by JoshWho** [comment]
My footer seems bouncy now.

**Comment by JoshWho** [comment]
sometimes it disappears sometimes it doesn't. I liked it when it was static.

**Comment by JoshWho** [comment]
The footer just seems like it is to high up when it is visible

**Comment by syldri** [comment]
I looked at @JoshWho  website the problem has not been changed 
look where the footer is

![image](https://user-images.githubusercontent.com/39193219/93017293-b90aa100-f5c7-11ea-9133-2f4d75731e4f.png)

**Comment by DanielnetoDotCom** [comment]
Added 2 options

footerStyle =  remove the default style, so you can put back the old style
autoHideFooter = you can disable the autohide feature

**Comment by JoshWho** [comment]
I disabled the Auto hide look where the footer shows.

**Comment by JoshWho** [comment]
How do I lower that down? SHould I just add a whole bunch of `<br>`on top to make it go below the body?

**Comment by DanielnetoDotCom** [comment]
if you disable it you MUST edit the style

at least put position relative

**Comment by JoshWho** [comment]
I changed it to this

`position: relative;bottom: 0;width: 100%; z-index: -1;`

**Comment by syldri** [comment]
I confirm from my side too

**Comment by DanielnetoDotCom** [comment]
Sorry, I forgot to send one file to the commit

**Comment by JoshWho** [comment]
Now it is perfect. Thank you @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Awesome, I also just send a new update, that the autohide does not exist anymore.

I am trying to keep the footer on the bottom even in small height pages.

I guess the last update does that, and do not need to change the style anymore

**Comment by JoshWho** [comment]
Sweeeeeeeeeeeet

**Comment by syldri** [comment]
hello, @JoshWho  if you want to withdraw or I put a red  

![image](https://user-images.githubusercontent.com/39193219/93024373-48c74400-f5f6-11ea-8362-76771fe20932.png)


/var/www/html/AVideo/view/bootstrap/css/ bootstrap.min.css

research  .list-group-item   
who should this find on line 88937 

add

margin-top: -29px;

![image](https://user-images.githubusercontent.com/39193219/93024440-d7d45c00-f5f6-11ea-8305-d013b520df18.png)





I took an example from your site look at the end result

![image](https://user-images.githubusercontent.com/39193219/93024449-e91d6880-f5f6-11ea-9b83-071e4173febc.png)
