### ISSUE TITLE
password

### ISSUE THREAD

**Issue by lahaj** [WWBN/AVideo#3649]
Hello
I subscribed to your server yesterday
Everything I changed on the site
But the password is not changed, I have tried many times without benefit
And the second thing if you put an external link to the video, the picture in the video is not
But if you uploaded it through the site, a picture will be in the video

**Comment by DanielnetoDotCom** [comment]
What is the site domain are you talking about?

**Comment by lahaj** [comment]
ooogel.com

**Comment by DanielnetoDotCom** [comment]
I see, do you mean you are not able to change the site user pass?

What external link are you trying to add? I would like to test it here

**Comment by lahaj** [comment]
No, sir, I do not want to add a path or link. I received the server yesterday and changed the settings on the site
And I was able to change the email and everything, but the password was not able
Refuses to change the password, but I can access the old password that you put through the site settings
![1010](https://user-images.githubusercontent.com/71000399/93023452-25a19200-f600-11ea-9b38-c68ac8a57f4d.JPG)

**Comment by DanielnetoDotCom** [comment]
I guess I found the problem, can you please try to change your pass again?

**Comment by lahaj** [comment]
I tried 3 times and refuses to change the password

**Comment by lahaj** [comment]
Now I can not log in at all, even with the old password

**Comment by DanielnetoDotCom** [comment]
I just sent you the last update now, please try again

**Comment by lahaj** [comment]
Very excellent. I entered and changed the password very easily. Thank you very much, sir
Why do I put an external video link? The video is not in image. I searched through all the options but did not find it
And if you uploaded the video through the same site, the image will be with the video
![1111111](https://user-images.githubusercontent.com/71000399/93023917-7d8dc800-f603-11ea-9507-3f7e0c5293e7.JPG)

**Comment by DanielnetoDotCom** [comment]
The image issue is not clear to me, please describe exactly what you did. What link you add?

Where did you add?

**Comment by lahaj** [comment]
I mean, sir, the background image for the video is Thumbnail
For example, if i put the mp4 link for a video from any other site where you do not view Thumbnail
If I upload the video to my site and Encoder creates the picture for it, it looks normal, that's what I mean

**Comment by DanielnetoDotCom** [comment]
So it does work with a regular video (selfhosted), only fails with a video link?

**Comment by lahaj** [comment]
Yes sir only works with a self host
As for if I put an external MP4 link, the picture is not shown
I thought there was an option to upload the image and put it on the video, but I did not find this option

**Comment by DanielnetoDotCom** [comment]
I guess you will need to detail step by step what you did.

I just test it on the demo site and it works https://demo.avideo.com/video/279/file_example_mp4_480_1_5mg

It is an external MP4 link and then I upload an image file

**Comment by lahaj** [comment]
Very excellent sir
But where is the option to upload the picture?
I searched the whole site and couldn't find an option to upload the picture to put it on the video

**Comment by DanielnetoDotCom** [comment]
Edit the video and click in the images tab

![image](https://user-images.githubusercontent.com/18009293/93024514-8e234b80-f5cd-11ea-9194-434143449f3a.png)

**Comment by lahaj** [comment]
I tried it before on the demo site
It won't work, but I will try it now. Thank you very much, sir

**Comment by lahaj** [comment]
What is the image size required to upload because it gives me an error

**Comment by DanielnetoDotCom** [comment]
Any size. What is the error?

**Comment by lahaj** [comment]
Image upload error
![101010](https://user-images.githubusercontent.com/71000399/93024896-b7160180-f60a-11ea-8ca2-926a9004d749.JPG)

**Comment by lahaj** [comment]
I have two sites, the same script, a site on the server that belongs to you, and a site on another server, the site that is on your server. The image is OK, it does not work an error and it works well
But the site that is on another server is the one that does not lower the image and gives an error

**Comment by DanielnetoDotCom** [comment]
Sorry but I do not understand if the server that I installed is working or not

**Comment by lahaj** [comment]
Yes sir
The server you subscribed to from your company is perfectly functional
But I installed the same script on another server previously before I did not buy a server from you that does not work

**Comment by DanielnetoDotCom** [comment]
You need to check the log files then

**Comment by lahaj** [comment]
sorry i mean subscribed to from your company is perfectly functional
But I installed the same script on another server previously before I did not buy a server from you that does not work

**Comment by lahaj** [comment]
If you don't mind, sir, could you share the log file code with me?

**Comment by DanielnetoDotCom** [comment]
You must get it in your server 

Here is how to get it https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by lahaj** [comment]
Thank you very much, sir. Have a great time
And thanks for this beautiful help, please accept my respect

**Comment by lahaj** [comment]
Hello. Password problem is back. I cannot log in to the site

**Comment by lahaj** [comment]
The problem was solved. The reason was to change the language. Now I can log in. Sorry for inconveniencing sir
