### ISSUE TITLE
Live Stream Embed Link page view links blank

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3650]
<img src="https://static.buddylist.co/livestreamlinks.png" style='width:100%;' border="0" alt="Null">

Embed code shows this

`<iframe width="640" height="480" style="max-width: 100%;max-height: 100%;" src="&embed=1" frameborder="0" allowfullscreen="allowfullscreen" ></iframe>`

**Comment by DanielnetoDotCom** [comment]
Sorry is it a livelink?

If yes, how did you open a livelink on the Live menu?

**Comment by JoshWho** [comment]
No it is a regular live stream

**Comment by JoshWho** [comment]
The field Live URL: is blank and so is the spot in the embed code for the url.

**Comment by DanielnetoDotCom** [comment]
Hi, I guess I found the bug, please update

**Comment by alielastal** [comment]
Can I Ask?
How to update? In order to fix the bug. I am new here?

**Comment by DanielnetoDotCom** [comment]
Here https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by alielastal** [comment]
Thanks.

**Comment by JoshWho** [comment]
ALl fixed. Thank you @DanielnetoDotCom
