### ISSUE TITLE
Connecting another Cloud Storage to existing Cloud Server

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#3651]
I am brainstorming so I can see if this will work. I will need to see if it is possible to connect to a cloud server, that has 10TB of storage to a cloud server that I am currently running the platform. Will that interrupt services with the platform because it will be attached to the server, or I will have to migrate the files that run the platform?

I am willing to hear from anyone that has done this and what steps that you did to accomplished this. Also, please give me some suggestions that will be good solutions for the way to accomplish this project.

**Comment by DanielnetoDotCom** [comment]
Hi, did you see that? https://github.com/WWBN/AVideo/wiki/Storage-Options
