### ISSUE TITLE
meet live streaming mirrored screen

### ISSUE THREAD

**Issue by hamelinmultimedia** [WWBN/AVideo#3652]
@DanielnetoDotCom 
hello daniel congratulations goes very well the integration of jitsi... Thanks a lot.
testing the live streaming with meet, it looks mirrored or upside down. 

![Captura de pantalla 2020-09-13 230928](https://user-images.githubusercontent.com/53911390/93045064-dd906880-f61b-11ea-9466-95e7c9aadf8d.png)

 fortunately it looks good on the live player.

![Captura de pantalla 2020-09-13 231025](https://user-images.githubusercontent.com/53911390/93045092-ebde8480-f61b-11ea-80bd-1a5efd7d598a.png)

also when I want to switch microphones or cameras. the box can't show all the devices ... it would be lacking to scroll

![Captura de pantalla 2020-09-13 233210](https://user-images.githubusercontent.com/53911390/93045107-f567ec80-f61b-11ea-9697-ef29de522fe1.png)

I've been studying how to run my jitsi self hosting server and I think something is missing... I can't stream.
I already have it and I'd like to use it. how i can configur it. Thank you in advance

**Comment by hamelinmultimedia** [comment]
It also seems that live streaming has a time limit... where I can change it

**Comment by hamelinmultimedia** [comment]
show the logo could be optional

**Comment by DanielnetoDotCom** [comment]
Hi.

Regarding the mirror, it may be some configuration in your side, I am not sure where. maybe something in your camera configuration.

Regarding the lacking to scroll, you are right, I may add some option to make this panel bigger. optionally you can try to use the Meet to file stream directly from there

Regarding the time limit, we are in the Beta Test phase, soon we will release some plans options to increase limits, but the limits we have now will be part of the free plan.

**Comment by hamelinmultimedia** [comment]
thank you very much for your response... I'm checking the camera and I can't find anything ... what I'm doing is from obs sending a video or image from the captured camera. In obs it looks good to the right but on the screen of the live plugin you see the opposite. and in the live url 
player looks good.
I will continue to review possible causes.

and I'll keep watching how I can run my jitsi self hosting, thank you very much

**Comment by hamelinmultimedia** [comment]
so that my jitsi self hosting I have to install jibri?

**Comment by hamelinmultimedia** [comment]
![Captura de pantalla 2020-09-14 083338](https://user-images.githubusercontent.com/53911390/93092907-a8106d00-f665-11ea-86b0-a99744dfb284.png)
obs side
![Captura de pantalla 2020-09-14 083513](https://user-images.githubusercontent.com/53911390/93092940-b52d5c00-f665-11ea-8358-b7b7ab21aa8c.png)
player on avideo streaming
![Captura de pantalla 2020-09-14 083616](https://user-images.githubusercontent.com/53911390/93092979-c37b7800-f665-11ea-9846-285cffd7a165.png)
live plugin
![Captura de pantalla 2020-09-14 083713](https://user-images.githubusercontent.com/53911390/93093023-d2622a80-f665-11ea-90a3-4ccba410e751.png)
meet live plugin

**Comment by hamelinmultimedia** [comment]
I'm not sure.... it may be when I use the virtual camera of obs...

**Comment by hamelinmultimedia** [comment]
opinion of the image quality of the stream in meet vs rtmp... I think meet is of better quality. but the sound of meet's transmission is of poor quality.

**Comment by hamelinmultimedia** [comment]
on obs virtual camera plugin i found vertical flip option...

**Comment by DanielnetoDotCom** [comment]
> so that my jitsi self hosting I have to install jibri?

No It will not work

**Comment by DanielnetoDotCom** [comment]
Sorry, I cannot.

**Comment by hamelinmultimedia** [comment]
I could pay for something

**Comment by DanielnetoDotCom** [comment]
Right now we are on the test phase.

What you have now is the free layer. I can increase your rates if you want to test, like live time limit and simultaneous live streamers services.

soon we will release some plans to keep those limits permanent.

**Comment by hamelinmultimedia** [comment]
I would still be interested only if I can use my two servers one for Avideo and one for jitsi... because of the kind of project I'm doing I have to have everything covered

**Comment by hamelinmultimedia** [comment]
I already have them installed and tested...

**Comment by DanielnetoDotCom** [comment]
I do not have anything right now, but I will think about it

**Comment by hamelinmultimedia** [comment]
I understand, this makes me make decisions quickly to continue my project... Thanks a lot
