### ISSUE TITLE
Subscription plugin arrange by user, arrange by plan and search don't work

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3653]
Hi,

In subscription plugin on subscriptions tab arrange by user, arrange by plan and search don't work

![image](https://user-images.githubusercontent.com/63721378/93081040-4a951400-f697-11ea-904c-fe6972f0b81a.png)

When trying to arrange it gives this error: 

![image](https://user-images.githubusercontent.com/63721378/93081230-9c3d9e80-f697-11ea-9eb9-ee88827fa9c2.png)

If there is many subscriptions it will be time consuming to scroll through them if you want to view or edit.

Hope this can be fixed.

**Comment by DanielnetoDotCom** [comment]
Thanks for notice, I will send an update to this in version 3.8
