### ISSUE TITLE
Playlist Title Are Blurred

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#3655]
@DanielnetoDotCom 

My playlist are showing up blurred.  Have you seen this before 

- Running 9.5
![blurred playlist titles ](https://user-images.githubusercontent.com/739391/93154878-c6f91880-f6d2-11ea-9371-630e848a3f7c.png)

**Comment by akhilleusuggo** [comment]
maybe cache issues

**Comment by willpower68** [comment]
@akhilleusuggo thank you sir.  That was it.  learned something new is always good and appreciate you taking the time to help.
