### ISSUE TITLE
subtitles problem

### ISSUE THREAD

**Issue by lahaj** [WWBN/AVideo#3657]
Dear Sir
Regarding the subtitles added for the video, everything is fine, but there is a problem
I do not know what is the solution
If I add subtitles to the video and I embed the video to another site, the subtitles will not work
As I tried several times from your script that I added to my server
And I tried it again, and it is from your script that you installed on my server that
I subscribed to you.
The subtitles works on the video while embedding the video to another site in one case
If the video I have encoded from the script, the subtitles is working on another site
I hope to find a solution, sir

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by lahaj** [comment]
I have updated now the video only works in the main site
As for another site, it does not work during embedding
![444444](https://user-images.githubusercontent.com/71000399/93247492-697ecd80-f79f-11ea-9a9f-e90300b843f5.jpg)

**Comment by DanielnetoDotCom** [comment]
Please share here the embed code

**Comment by lahaj** [comment]
<div class="embed-responsive embed-responsive-16by9"><iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="https://mrtet.com/vEmbed/2" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no">iFrame is not supported!</iframe></div>

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/93248756-aed2d900-f766-11ea-93c1-c872db7e4b98.png)

**Comment by DanielnetoDotCom** [comment]
It has nothing to do with subtitle plugin

**Comment by lahaj** [comment]
It does not work because the code and the update that you gave me I put it for this reason does not work
And now I retrieved the old code before the update and now it works, but the subtitle does not work Please enter again to the link and you will see the video working, but with the code that you told me I update it does not work
Please enter the link, and it works without subtitle   https://mrtet.com/vEmbed/2

**Comment by DanielnetoDotCom** [comment]
I am pretty sure I told you this before .

You CANNOT copy files  you must use `git pull` command

**Comment by lahaj** [comment]
This thing, sir, is difficult for me because the script is beautiful and has very beautiful features. You thank for this wonderful work. As for me, I am not used to doing orders because I am afraid to waste everything
I want to find ready-made commands to copy and download
And the script, when this problem is imposed, works normally, and what is the solution now, sir

**Comment by DanielnetoDotCom** [comment]
Then try to download and upload and overwrite all the files . Otherwise only git pull

**Comment by lahaj** [comment]
I can ask you a question, sir, why is the translation not accompanying when the video is being embedded
I tried many methods and even on my server that I took from you, there is the same problem and you are the ones who installed it on the server that I bought from you and the domain name is
ooogel.com
It might be wrong with me if I installed the script
But how would the mistake be if you installed the script?

**Comment by lahaj** [comment]
I think, sir, that you did not answer my question
That there is no solution

**Comment by DanielnetoDotCom** [comment]
If you go to the ooogel.com server and make a `git pull` I am sure it will work.

and there is a solution, is to use the correct code.

**Comment by lahaj** [comment]
Dear sir, I assure you that this is a picture I met from the site ooogel.com and the video subtitles is working
This is the video embedding link and the video subtitles will not work ------ https://ooogel.com/vEmbed/11
![y1](https://user-images.githubusercontent.com/71000399/93277792-d01dde80-f7d3-11ea-9fce-05378cbcea73.JPG)

This is at the site where you installed the script

**Comment by DanielnetoDotCom** [comment]
Did you update with `git pull` like I already request you a couple of times to do?

**Comment by DanielnetoDotCom** [comment]
I just update the site, with `git pull`, for you, please try again

**Comment by lahaj** [comment]
I tried it and the problem still exists sir

**Comment by DanielnetoDotCom** [comment]
can you please make the site public so I can test?

what video are you testing?

**Comment by lahaj** [comment]
Sir, the Subtitle works for the videos that have been uploaded via script, and they have been Encode. These videos have no problem.
The problem is when I put an external video link for the script, the Subtitle  works only in script, and when I include the video that I put the translation for
Subtitles do not work when I include the video. I have opened the site to the public

**Comment by DanielnetoDotCom** [comment]
Hi, I found the problem the ooogel.com site is updated now.

**Comment by lahaj** [comment]
Thank you very much, sir
Yes, now the Subtitle works and it has no problem. I thank you very much for your wonderful services
And if you do not have any objection, you can tell me what the problem is and which file
As I have another site with the same problem
If you don't mind, tell me sir

**Comment by DanielnetoDotCom** [comment]
Was a wrong code
https://github.com/WWBN/AVideo/commit/4c24d04cd6b226798fe06e4fd275cc7aaa52e57b

**Comment by lahaj** [comment]
I will try to update it. Thank you very much, sir
I wish you an enjoyable and happy time
Thank you a thousand times
Accept my respect
Mohammed
