### ISSUE TITLE
VideoResolutionSwitcher Does not working for me

### ISSUE THREAD

**Issue by alielastal** [WWBN/AVideo#3658]
**VideoResolutionSwitcher**
This Plugin is not working probably, i am already installed a fresh copy from the script and added the plugin.

**Screenshots**
This is a screenshot

![image](https://user-images.githubusercontent.com/2826050/93213798-fd837180-f76c-11ea-9fef-9a5936feea88.png)

**Comment by akhilleusuggo** [comment]
that's a live ... on live that doesn't work lol
https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream

**Comment by alielastal** [comment]
Do I follow the instructions in the link? Is it possible to work properly?

**Comment by akhilleusuggo** [comment]
Not with the plugin VideoResolutionSwitcher . This one is for mp4/webm videos

**Comment by alielastal** [comment]
OK. What I want is to play the live broadcast with several qualities, what is the appropriate plugin to do that?

**Comment by akhilleusuggo** [comment]
You need HLS plugin .

**Comment by DanielnetoDotCom** [comment]
also you need tho use the adaptive mode https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream
