### ISSUE TITLE
Stale video on encoder queue

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#3659]
Hi,

is there a way I can delete a stale uploaded video that still shows on my encoder queue?

![image](https://user-images.githubusercontent.com/28105720/93226328-18ed7d00-f76b-11ea-9f02-bfa2b76cf416.png)

Wash Spirit Att & Def Set Pieces - copy was deleted some time ago, but till shows on my queue.

Thanks

**Comment by akhilleusuggo** [comment]
On queue log . If it's your video , you can delete .
Remember if the encoding has already started , you need to kill the PID from terminal .

**Comment by millzee01** [comment]
its not my video.

is there a way to find what the pid is associated to the video the encoder thinks is on the queue?

**Comment by akhilleusuggo** [comment]
htop
