### ISSUE TITLE
userMustBeLoggedIn

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#3660]
Hi,

when playing a video on another site with eembedded player, i'm getting:

[15-Sep-2020 17:08:24 Europe/London] User::userCanWatchVideoWithAds (No can not)  848
[15-Sep-2020 17:08:24 Europe/London] User::canWatchVideo You are not logged so can not see (848)
[15-Sep-2020 17:08:24 Europe/London] User::canWatchVideo (No can not) 848

I dont have the ads set, and i allow everyone to view.

and this is what i get in the console:
HTTP "Content-Type" of "text/html" is not supported. Load of media resource https://vid.kwiktactix.com/videoEmbed/848/creative-skills-in-football-2020- failed.

All candidate resources failed to load. Media load paused. 

Cannot play media. No decoders for requested formats: text/html

Is there something I need to change to allow the embed player to bypass this check?

The issue only seems to effect embedded youtube videos

**Comment by DanielnetoDotCom** [comment]
those are only debugs logs, it does not indicate any problem.

what is the problem you are facing? what do you want to do?
