### ISSUE TITLE
Can I change defauly audio pic/thumbnail

### ISSUE THREAD

**Issue by dbmasters** [WWBN/AVideo#3661]
Can I change the default audio thumbnail that displays in the front page or detail page, the default is somewhat annoying, I'd like to just put a sine wave or something.

**Comment by akhilleusuggo** [comment]
On the encoder you can create shockwave .

**Comment by dbmasters** [comment]
Care to elaborate on that? I have poked around and not found anything like that.

**Comment by DanielnetoDotCom** [comment]
I guess @akhilleusuggo is talking about this https://tutorials.avideo.com/video/1/how-to-create-an-audio-spectrum-from-any-video?channelName=yeshua

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Yes correct , on ffmpeg is called shockwave
