### ISSUE TITLE
website stalls!!!-urgent help

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3662]
the website loads very fast however as soon as i click any video,the whole website stalls.i have removed the tawk.to script and chat2 plugin recently installed.
This has started recently,i have updated the website and have git pulled to keep the website updated.
No errors in the log files

browser-chrome-inspect-network-is just blank-nothing is shown!
Any help would be highly appreciated
Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
Check the log files

**Comment by vraghavans** [comment]
Dear Daniel ,
As i mentioned in the post, i checked both log files,both in the videos and encoder-its normal and nothing out of place,no errors

Pls help
Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
If is the script that is slowing you down you may see some clue on the log

**Comment by vraghavans** [comment]
Dear Daniel

This is the log for last 3 days,can you please check and advise
[https://drive.google.com/file/d/1dlHFIwr7QBjQchsNZ_bJzVJ_NQgBPIFA/view?usp=sharing](url)

Thanks for your help

rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
Based on the log file your site is fast, maybe you are having a network problem

also I opened it here and looks good for me https://www.maritimeplatform.com/

what page do you think is slow?

**Comment by vraghavans** [comment]
Dear Daniel,
Yes the website loads fast and once you click any video the video doesnt load atall.

If you allow browser cache-slowly even the loading stalls.
Once you clear browser cache-it agains become fast.

Also again my generate sitemap is not working.

All the pages load very fast except the actual videos..

Please assist
Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
Your site is not slow, the problem is your videos that are not playing at all.

check this for example https://www.maritimeplatform.com/videos/_YPTuniqid_5f5ef1d1403095.95247093_SD.mp4

of the file do not exist, or is corrupted or your webserver is not delivering the correct video. you have to check it in your side.

**Comment by vraghavans** [comment]
Dear Daniel,
Well noted and thanks.atleast we know where is the issue.
the cahllenge now is the file is there in the server and am able to download the file from the server-the same file you mentioned above.
however when i try to download the file from the website from "my videos" menu-the file is not there and downloads a 0kb file.
the file is there but the website is not able to pull the video from the server,pls advise what could be the issue please.

Thanks in advance
rgds
vijay

**Comment by DanielnetoDotCom** [comment]
I do not know what is the issue, it depends how did you install the server. you may find this answer on google as long as it is not related to AVideo script

**Comment by vraghavans** [comment]
Dear Daniel,

Yours well noted. 
You only have installed last after that I have not made any changes. 
Except a recent git pull and upgrade to 9.5
Please help me out in finding the error pls 

Rgds 
Vijay

**Comment by DanielnetoDotCom** [comment]
Sorry but I do not know what is the problem, it never happen with me.

you can hire me to take a look, but I really have no idea what it may be.

**Comment by vraghavans** [comment]
Dear Daniel,

Yes please, when can we schedule the call please

Rgds 
Vijay

**Comment by DanielnetoDotCom** [comment]
Hi

It is 22:44 now here we can do it tomorrow morning. Please email me at developer@youphptube.com

**Comment by vraghavans** [comment]
Sure thanks

**Comment by vraghavans** [comment]
fixed in live chat,there was a issue with security for downloading the video not transferred with configuration to new domain name
