### ISSUE TITLE
Lost password

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3663]
I tried to retrieve a lost password, and I get the error message you do not have an email.
All the accounts I tried DO have an email.
Also the captcha code doesn't change when pressing the refresh captcha.
![email](https://user-images.githubusercontent.com/66537018/93279144-7e099880-f794-11ea-93b4-c0a34851f39b.jpg)

Please advise.

**Comment by DanielnetoDotCom** [comment]
Hi, 

Yes, if you do  not have an email setup you cannot recover that way, check this please https://github.com/WWBN/AVideo/wiki/Reset-a-Password

also, please make sure you update your site. we recently fix an bug regarding the change password.

**Comment by fakeologist** [comment]
Admin password is fine - it's for any user I tried. I get the same message for all of them.
Site is updated daily.

**Comment by DanielnetoDotCom** [comment]
Are you sure they do have email on their profile?

**Comment by fakeologist** [comment]
ok it seems to work. the one guy had a special character in his name and I was trying the Name field and not the User field to access database.

**Comment by DanielnetoDotCom** [comment]
Any idea what charactere was that? what was the username? I want to prevent this happen again

**Comment by fakeologist** [comment]
It was an i with two dots on top (French)

**Comment by DanielnetoDotCom** [comment]
But was it regarding the email?

can you please write here a sample that may fail so I can create here and prevent it to happen?

**Comment by fakeologist** [comment]
I was typing in the name field, not a selection from the user field.
A better error message should read: user not found.

**Comment by DanielnetoDotCom** [comment]
I see, the thing is, a message like that is a good tip for hackers.
for example we do not say the user is wrong or password is wrong, we say the user and pass does not match.

otherwise it will make easier if some one wants to hack you.

**Comment by fakeologist** [comment]
I see. No issues then. Case closed.
