### ISSUE TITLE
Embed Stream Does Not Work

### ISSUE THREAD

**Issue by alielastal** [WWBN/AVideo#3665]
**Describe the question**
I am already installed a fresh copy from the script and Live work probably.
I wonder why the Embed Stream CODE does not work in other sites.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.
![image](https://user-images.githubusercontent.com/2826050/93327598-3aaa3b00-f823-11ea-8cc4-7f0a3b4b640b.png)

**Comment by DanielnetoDotCom** [comment]
I do not understand what you mean,

**Comment by alielastal** [comment]
I mean, when i take the embedded code, and paste it in other sites, it does not work.

**Comment by alielastal** [comment]
when i take the link in the embedded code and paste it in the browser, it works fine .. !!

**Comment by DanielnetoDotCom** [comment]
I do not know why, for this you have to share the code you are using and also the site you are pasting it and it is failing

also share a link where your embed code does not work

**Comment by alielastal** [comment]
This link is LIVE now
http://5.189.169.27/AVideo/live/0/Fastlive

 Embed Stream
<iframe width="640" height="480" style="max-width: 100%;max-height: 100%;" src="http://5.189.169.27/AVideo/live/0/Fastlive&embed=1" frameborder="0" allowfullscreen="allowfullscreen" ></iframe>

Let me if you have any thing else.

**Comment by alielastal** [comment]
![image](https://user-images.githubusercontent.com/2826050/93347334-a0a3bc00-f83d-11ea-8e94-aac9c40e0bf4.png)

**Comment by DanielnetoDotCom** [comment]
but in what page are you embeding this?

**Comment by alielastal** [comment]
Use This
https://www.blogger.com/u/1/blog/posts/1292530600277085228?hl=ar&tab=jj
User: akkmm9044@gmail.com
Pass: ab080180

you will see

![image](https://user-images.githubusercontent.com/2826050/93350353-3856d980-f841-11ea-8ffa-e3b73523206f.png)

click this you will see the embedded code.

**Comment by DanielnetoDotCom** [comment]
You should not share your credentials here, this is a public forum.

but without open your site I can already tell you you cannot embed http content inside an https site

https://www.tinywebgallery.com/blog/iframe-do-not-mix-http-and-https

**Comment by alielastal** [comment]
Thank you very much.

**Comment by danieljaber** [comment]
Hi, i have the same problem: I've create AVideo in http page and was trying to embed in https page. Is there any option? I'm asking because when I create the machine and try to use https protocol and Ubuntu OS It was not possible to access my site. It was possible only when I use http protocol. Can you help me?

**Comment by DanielnetoDotCom** [comment]
@danieljaber is not possible to embed http into an https site
