### ISSUE TITLE
Live vs Meet

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3666]
hello @DanielnetoDotCom it starts to get boring because if the Meet server is not online it is impossible to access live

I am redirected directly to Meet I already told you about this problem

![image](https://user-images.githubusercontent.com/39193219/93328267-cf109f80-f81b-11ea-8768-8f7f0919d806.png)

**Comment by DanielnetoDotCom** [comment]
Sorry about this, can you please try this new update?
