### ISSUE TITLE
Page Won't Load

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3667]
My front gallery has stopped loading. I am getting this error in dev tools

![wget-err0r_2](https://user-images.githubusercontent.com/65451390/93368496-be314f80-f856-11ea-8768-d988e778e41b.PNG)

I am getting this WGET ERROR in the log.

![Inkedwget-err0r_LI](https://user-images.githubusercontent.com/65451390/93368714-fe90cd80-f856-11ea-964a-6bd69acedf1d.jpg)

Am I missing something? We we removing and unlisting old videos then this happened. DB 9.2.

@akhilleusuggo and @DanielnetoDotCom and others please assist...

Thank you

**Comment by akhilleusuggo** [comment]
We're at 9.5 version .

**Comment by jengajenga** [comment]
I have 9.5 locally but we are still running 9.2 on the live site. I haven't made any updates.

All was working well until we unlisted some old uploaded videos.

**Comment by jengajenga** [comment]
And it only affects Gallery. All other first page "Default" and "Netflix" are fine.

**Comment by DanielnetoDotCom** [comment]
I cannot see a reason to stop work. at least not in your log files.

can you please make sure the videos folder and the cache folder are writable?
