### ISSUE TITLE
Performance Recommendations & Tuning

### ISSUE THREAD

**Issue by SimpleMinion** [WWBN/AVideo#3669]
I have been streaming some live content on our site with no problems until the last couple of weeks. We are seeing greater traffic and users and have had some issues. Are there any suggestions for Apache, Nginx, & SQL performance on a VM running with 16 GB ram & 4+ processors that will allow 500+ (Potentially 1000) concurrent streams with 2 to 3 live encoding sessions @ around 3mb/s? I have tweaked the worker processes in Nginx & prefork limits in Apache.

**Comment by akhilleusuggo** [comment]
when you say 4+ processors you mean CPUs or cores ?

**Comment by SimpleMinion** [comment]
It is on a Hyper-V VM and is allocated 16 Virtual Processors right now. It was at 4 before.
