### ISSUE TITLE
Live & LiveUpdate plugin failed to upgrade.

### ISSUE THREAD

**Issue by SimpleMinion** [WWBN/AVideo#3670]
After upgrade to 9.5 from 8.x, the "Live" plugin says "You MUST update your LiveUsers plugin to version 2.0 or greater" and the LiveUsers plugin says that "Update Available: v2.0" The upgrade did not automatically upgrade the LiveUsers plugin, so I deactivated it and and reactivated it, deactivated it and redownloaded the LiveUsers plugin and reinstalled it, but that version is the same version that I already had. How do I get the LiveUsers plugin and therefore the Live plugin upgraded. Thanks.

**Comment by DanielnetoDotCom** [comment]
Try to manually delete the LiveUsers plugin folder and then upload the new one again.

**Comment by SimpleMinion** [comment]
I did do that, but the version that I just redownloaded the file and the LiveUsers.php file still says version 1.0

**Comment by DanielnetoDotCom** [comment]
from where did you download it?

**Comment by SimpleMinion** [comment]
From https://youphp.tube/marketplace/. This is where I purchased it. Is there a different place?

**Comment by DanielnetoDotCom** [comment]
You are in the right place, but it should download for you the 2.0

But did you delete the plugin/LiveUsers folder before upload the new one?

**Comment by SimpleMinion** [comment]
I did delete it, but it didn't work. I just did it again and it is working now. Thanks.
