### ISSUE TITLE
DiskUploadQuota Plugin Endpoint not working

### ISSUE THREAD

**Issue by julzxcapz** [WWBN/AVideo#3671]
Hi,

Can you help me on my issue please, I follow the description on the plugin and fill-up the **Publishablekey** and **Restrictedkey** correctly then tried the plugin so it generates an endpoint (**SigningSecret** - added this too on the form). Now the endpoint has been disabled automatically and encountered errors like this;

![image](https://user-images.githubusercontent.com/61785146/93502813-d1711780-f949-11ea-8cfb-d5fd6adc1989.png)

Thank you

**Comment by DanielnetoDotCom** [comment]
Is the endpoint accessible from outside?

If is not they will probably disabled

**Comment by julzxcapz** [comment]
no, I've check that the endpoint is HTTP ERROR 500, but it's the generated endpoint

Sorry, did I miss something ? like another plugin for that to work

Thank you

**Comment by DanielnetoDotCom** [comment]
if is HTTP ERROR 500 you have to find and fix it.

that is why it was canceled
