### ISSUE TITLE
Copy CHat Bubble no Bubble showing code now 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3672]
When you click on Copy CHat Bubble or No Bubble you get something like this in your clipboard.

`<div class="embed-responsive embed-responsive-16by9"><iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="https://chat.joshwhotv.com/Chat2/?room_users_id=3031&iframe=1&noFade=1&bubblesOnly=1" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no"></iframe></div>`

This doesn't work for OBS it has to be a URL

**Comment by DanielnetoDotCom** [comment]
Hi

I just sent an update to Chat that may help you (Chat2 version 3.3)

![image](https://user-images.githubusercontent.com/18009293/93628638-3ca80180-f9bd-11ea-81fc-2e11eaa77781.png)

**Comment by JoshWho** [comment]
After the update chat no longer shows anymore

**Comment by JoshWho** [comment]
I rolled it back to the old version and that one loads. Not sure what the problem is with new version

**Comment by JoshWho** [comment]
should I download it again?

**Comment by DanielnetoDotCom** [comment]
Sorry for the late reply, I just tried on demo and it works.

what is the error exactly?

did you update your site and redownload the plugin?

**Comment by JoshWho** [comment]
I updated the site and uploaded the new version on both the main site and standalone file on the other server

**Comment by JoshWho** [comment]
I only rolled back Stand alone part on the smaller server.

Also you can't really see the chat menu in the live dashboard it gets cut off.

 <img src="https://static.buddylist.co/chatmenu.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
that is how looks on my side 

![image](https://user-images.githubusercontent.com/18009293/93709365-2496c600-fb14-11ea-9ba1-d0c9020c4018.png)

@JoshWho what is the problem when you update the plugin, can you please provide a screenshot and logs?

**Comment by JoshWho** [comment]
500 error

<img src="https://static.buddylist.co/bbb.png" style='width:100%;' border="0" alt="Null">

**Comment by JoshWho** [comment]
Looks good now. Just needed the update on the chat server side and now all good. Thank you @DanielnetoDotCom
