### ISSUE TITLE
AVideo vs InternetExploer11

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#3674]
I accessed AVideo Ver9.5 from Internet exploer11 under Windows10.
I moved login page, I entered admin/admin (local user) and sign in.
But I could not login AVideo, retured login page.
Does AVideo Ver9.5 support Internetexploer 11 under Windows10 ?

**Comment by DanielnetoDotCom** [comment]
Not sure, not tested. but you can try demo page on it

**Comment by hnagasawa** [comment]
Please tell me you demo sit url.
If same torabule occure,do you support us(I thnk i will think we pay)

**Comment by DanielnetoDotCom** [comment]
Hi

Here is the demo site https://demo.avideo.com/

I am not sure what needs to be fixed (if needs to be fixed)
and not sure if can be fixed. IE11 is an old browser with a little use

That is what we have on our analytics

![image](https://user-images.githubusercontent.com/18009293/93685941-64649b80-fa89-11ea-9337-a3f039c8704f.png)

IE11 is the less used browser on the list

**Comment by hnagasawa** [comment]
Dear Daniel

End users are only allowed to use IE11 due to their policy.
I really want to use AVideo with IE11.
Also
End users plan to migrate their system WEB to Edge on 2021/7.
Until then, you have to use IE11.
I want you to find out how to support IE11 and make it work with IE11.

If necessary, we also consider paying you a bonus.

**Comment by DanielnetoDotCom** [comment]
Please send an email to developer@youphptube.com

List exactly what pages you detect missing features, then I can quote the development to you.

**Comment by hnagasawa** [comment]
Dear Daniel

I installed AVideo and AVideo-Encoder (both Version 23-OCT-2020 
3:AM(JST) in our enviroment
I could login encoder from AVideo in our enviroment.
But I installed AVideo and AVideo-Encoder (both Version 23-OCT-2020 
3:AM(JST) in our customer's envuriment.
But I could not login encoder from AVideo in our customer's enviroment.
(could not automatic login encoder)
23-Oct-2020, Your demo site coulld not access).

Today, Our customer login your demo site from his enviromey using IE11
No problem.

What do you change from Versiom 23-OCT-2020 to now version ?

Please inform us soon.

Regards
Hiroshi Nagasawa
