### ISSUE TITLE
Can not upload mp4 file

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#3675]
AVideo-Encoder Ver3.2 under Ubuntu18.04.
I click Add files and I selected mp4.
preview this mp4 file on chrome.
What do we check ?

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong
