### ISSUE TITLE
Create thumbnail

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#3676]
Hi,

Sometimes, when videos are uploaded or embedded, the thumbnail isn't generated.  Yet the video uploads and plays fine.

So on the video list, the thumb is just a white background.

Rather than my users having to create a thumb themselves and upload it to their video.   It would be really handy to be able to have a button near edit/activate etc that allows the thumbnail's to be regenerated.

if this is a common issue of course.

**Comment by akhilleusuggo** [comment]
direct upload or from encoder ?
