### ISSUE TITLE
Live plugin problem

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#3677]
Hi Daniel,

I found problem when live streaming 19-20 users at the same time to my Server in LAN.
The homepage will load slowly when clicking between the live viewing page and the first page.
Sometime In the Live viewing page load slowly too.
And sometime when I click to watch the Live video.  The Live list in the bottom of viewing page disappear and the Live notification on the menu bar become to 0 too.  So, I try to check the RTMP stat pages the live is gone too.  
But when I click back to the home page.  The Live thumbnail still showing and I can click to watch it too.

You can see the video below link.
https://drive.google.com/file/d/1Jg1e4QK14L4MZ8_0Y9YOCKm55AXQMUu8/view?usp=sharing

I use AVideo version 9.5 & Encoder 3.2 & Live plugin v5.2

My Server spec below.
Dell PowerEdge R440
Intel Xeon Silver 4208 2.1G, 8C/16T, 9.6GT/s, 11M Cache Turbo, HT
DDR4 2400 32GB
HDD 960GB SSD SAS Read Intensive 12Gbps

**Comment by akhilleusuggo** [comment]
maybe IOps issues . nvme would give better results .

**Comment by DanielnetoDotCom** [comment]
I could see you have about 30 lives at the same time. so @akhilleusuggo is right, the I/O may be a problem

To resolve this you can try to use separated live servers https://github.com/WWBN/AVideo/wiki/Live-Plugin#livestream-server-balance

Another thing is the script will try to generate Live thumbs for each Live. they are generated on the encoder (maybe the encoder is also on the same server) if the encoder takes time to respond, it will slow down your page.

You can also separate the encoder into a different server.

And to try to speed up your first page try to disable the Gif from the live
![image](https://user-images.githubusercontent.com/18009293/93631352-ceb20900-f9c1-11ea-8fd7-cd4a13ca674f.png)

**Comment by guitarpound** [comment]
Hi @DanielnetoDotCom & @akhilleusuggo,

In the video clip.
I already disableGifThumbs.
And I disable recorder function in nginx.conf below to prevent I/O problem issue.

#recorder video{
      #   record all;
      #   record_path /var/www/tmp;
      #   record_notify on;
      #   record_max_size 2048M; 
      #   will produce files of the form yourUserKey-24-Apr-$
      #   record_suffix -%d-%b-%y-%T.flv;
#}

But it still have the same problem.

So, Today I tried checkbox doNotShowLiveOnVideoList below picture.  The webpage loading fast normal.  

![1600494507932](https://user-images.githubusercontent.com/57282919/93660204-8a347500-fa76-11ea-9f29-18ad539d91f6.jpg)

But sometime when clicking between the live viewing page and the first page.
The Live notification on the menu bar become to 0.  I have to waiting a while until the number showing.
It looks like pending something.

Video clip
https://drive.google.com/file/d/18mFkDWTJnX--V3q8_6F6BHKEzgSaL3tS/view?usp=sharing

**Comment by DanielnetoDotCom** [comment]
yes, as I told you the server will try to extract thumbs from all the lives.

we do not have an option to stop the thumbs now and use the default poster. we may add it in the future
