### ISSUE TITLE
Share video for private group, can show in public ?

### ISSUE THREAD

**Issue by gamersalpha** [WWBN/AVideo#3679]
Hello there, 

so  i create some groupe on my avideo site, but when i share a video in private for my group, even it u not connected u can see it, how totaly hide the video when only a group of user have right to see it please

thanks

**Comment by DanielnetoDotCom** [comment]
Try this 

![image](https://user-images.githubusercontent.com/18009293/94013858-16011680-fd81-11ea-9265-635f57aaf76e.png)
