### ISSUE TITLE
PlayList fixDuplicatePlayList Log errors

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3680]
I keep seeying this in my logs:
AVideoLog::DEBUG: PlayList::fixDuplicatePlayList

![Screen Shot 5781-01-01 at 16 14 58](https://user-images.githubusercontent.com/58882903/93668175-9ed33600-fa93-11ea-8d96-577d24632a9e.jpg)
![Screen Shot 5781-01-01 at 16 15 39](https://user-images.githubusercontent.com/58882903/93668177-a2ff5380-fa93-11ea-9b19-83d600a49cc1.jpg)

**Comment by DanielnetoDotCom** [comment]
What AVideo version are you running?
