### ISSUE TITLE
Mobile Phone Live Stream

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3681]
When trying to stream live from mobile I now get a "Go Live" orange button and when clicked it tells me:
"This feature is not available on this device"

My site is fully updated and I never had this issue before.

**Comment by DanielnetoDotCom** [comment]
Hi, This weekend I submit a new version of the mobile, it you should go live with the Meet , and works on iOS and Android, can you please double check you are running the latest version of the mobile?

**Comment by mapleblade21** [comment]
Hi , is  using meet the only way to live stream from mobile currently ?

**Comment by DanielnetoDotCom** [comment]
Yes, mobile requires the Meet
