### ISSUE TITLE
How does this configuration needs to be set?

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3683]
![Screen Shot 5781-01-02 at 0 10 18](https://user-images.githubusercontent.com/58882903/93689760-3a879500-fada-11ea-95ea-d86a44c1c29b.jpg)
Can you please provide with a small guide on how the RTMP configuration and stat url should be set. Here is a screen shot of how I have mine setup. I am ugins NGINX 18

**Comment by DanielnetoDotCom** [comment]
Please check this https://github.com/WWBN/AVideo/wiki/Live-Plugin
