### ISSUE TITLE
On the "My Channel" page

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#3684]
Hello,
I would like to encourage improvement in how I think.
On the "My Channel" page
it would be good if the number of videos on a channel was also displayed in the Videos tab. It would also be good if "About" was available on its own tab; that makes it clearer. In the "About" information, links are not converted into hyperlinks either, which would probably also make sense.

greetings
![image](https://user-images.githubusercontent.com/52116237/93751243-107ac380-fbfd-11ea-8f05-59314b8ea939.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I like the total videos idea, it may be added soon.

regarding the about, it shows on the main channel page
