### ISSUE TITLE
A separate page for the subscribing channels

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#3685]
I would like to suggest that there is an option with which the channels that you have subscribed to are displayed on a separate page instead of on the start page. It is clearer if the subscribed channels have their own page. And it shrinks the homepage. If you have subscribed to many channels, then the start page causes a lot of inquiries from registered users.

**Comment by akhilleusuggo** [comment]
not really if you have gallery mode . There's infinitscroll that hides that content , unless you scroll down .
