### ISSUE TITLE
Avideo start meet doesn't work 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3687]
Tried to start a stream or meet, start  button does nothing. No response.

**Comment by DanielnetoDotCom** [comment]
@fakeologist I will update your site soon, due the Mobile apps.

when I update I need you to test again. I am pretty sure you are outdated.

**Comment by fakeologist** [comment]
Ok I updated this morning. I update almost daily.

**Comment by DanielnetoDotCom** [comment]
For the records, you miss to install the tables for the Meet plugin

![image](https://user-images.githubusercontent.com/18009293/93804960-63fd0980-fc1d-11ea-9547-ea9016dae720.png)

**Comment by fakeologist** [comment]
I forgot that part. Thanks works now.
Meet is a whole new plugin I see replacing mobile?

**Comment by DanielnetoDotCom** [comment]
Correct, it will be used to live stream from iOS and Android
