### ISSUE TITLE
this update is a disaster

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3690]
hello, @DanielnetoDotCom  
several weeks of work have passed in 2 seconds

if you have made any changes to css and js; and
you only have one site, don't update you will cry

all modification carried in Script code does not work

before update

![image](https://user-images.githubusercontent.com/39193219/93814494-e3f29600-fc54-11ea-8bd4-59e9d6b0a025.png)

<br>
<br>
---------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/39193219/93814804-5794a300-fc55-11ea-9a5b-4ac8651f6090.png)

<br>
<br>

after the update

![image](https://user-images.githubusercontent.com/39193219/93814611-0c7a9000-fc55-11ea-9192-e2a8654d5aa1.png)

<br>
<br>

![image](https://user-images.githubusercontent.com/39193219/93814899-798e2580-fc55-11ea-9f4c-d293d5286e7b.png)

**Comment by DanielnetoDotCom** [comment]
Make sure you clear the site cache after the update, yes there are JS and CSS updates.

**Comment by syldri** [comment]
I made a lot of changes to css and js all changes are made in the Script code

when i updated everything is distorted

![image](https://user-images.githubusercontent.com/39193219/93816305-a17e8880-fc57-11ea-8c89-fd54402c6520.png)

**Comment by DanielnetoDotCom** [comment]
So you have to fix your code, the update will not delete it, but if you want to follow the updates you will need to fix your side.

**Comment by syldri** [comment]
watch on your demo site

the problem does not come only from my site

![image](https://user-images.githubusercontent.com/39193219/93816856-63ce2f80-fc58-11ea-8129-00469faaef7b.png)

**Comment by DanielnetoDotCom** [comment]
what is the problem exactly?

what page?

**Comment by syldri** [comment]
the cat covers the player

**Comment by syldri** [comment]
I am on mobile

**Comment by DanielnetoDotCom** [comment]
I see now, I will bring a fix soon

**Comment by DanielnetoDotCom** [comment]
please make sure you clear your cache again

**Comment by DanielnetoDotCom** [comment]
you will need to download the new Chat2 v3.4

**Comment by syldri** [comment]
the chat
 problem is solved

**Comment by DanielnetoDotCom** [comment]
great!

**Comment by syldri** [comment]
@DanielnetoDotCom    why not add this for the rest of the players  
it can be good to enlarge the player

![image](https://user-images.githubusercontent.com/39193219/93828448-aa795500-fc6b-11ea-892b-d16397a74195.png)

**Comment by DanielnetoDotCom** [comment]
You already have it as a theater button  (plugin)

![image](https://user-images.githubusercontent.com/18009293/93828915-c6b4cc00-fc42-11ea-9796-eb8a2927715b.png)

**Comment by syldri** [comment]
what I mean when I choose or I put in red

this could greatly improve the presentation of the player and the discussion



![image](https://user-images.githubusercontent.com/39193219/93829105-2aec8580-fc6d-11ea-8bd8-e82ac4a8cfa7.png)

<br>
<br>
<br>

![image](https://user-images.githubusercontent.com/39193219/93829180-5a02f700-fc6d-11ea-9bbe-c6c9037c307e.png)
<br>
<br>
<br>
when I click on live by clicking on the button it changes a lot and it is really very beautiful like that
it would be good to do it on all players

![image](https://user-images.githubusercontent.com/39193219/93829704-7f443500-fc6e-11ea-81af-5795190d37f9.png)

**Comment by DanielnetoDotCom** [comment]
check show switch button

**Comment by syldri** [comment]
@DanielnetoDotCom  I have the feeling that you don't understand, ou don't want to understand

I want the player to be next to the chat

**Comment by syldri** [comment]
your update to remove weeks of work

**Comment by syldri** [comment]
you saw what you did here

![image](https://user-images.githubusercontent.com/39193219/93832844-3e045300-fc77-11ea-9eed-5487a6a8300a.png)


why not reproduce the same things with the compress_is_default button


![image](https://user-images.githubusercontent.com/39193219/93829105-2aec8580-fc6d-11ea-8bd8-e82ac4a8cfa7.png)

to have this final result

![image](https://user-images.githubusercontent.com/39193219/93833189-36917980-fc78-11ea-9dae-ce1e049b5401.png)

**Comment by syldri** [comment]
@DanielnetoDotCom  tell me how much it will cost to do it so everyone can enjoy it
I think it won't even take you 1 hour to make this change

**Comment by DanielnetoDotCom** [comment]
Are you looking for this?

![image](https://user-images.githubusercontent.com/18009293/93838579-819f9280-fc60-11ea-9d28-385c1a5fd459.png)

If yes this is the TheaterButton plugin, if not, you can email me at developer@youphptube.com for a quotation.

**Comment by syldri** [comment]
Hello @DanielnetoDotCom  e-mail sent
