### ISSUE TITLE
Something weird with Viewport resizing on desktop

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3691]
I did the latest update and my website looked like at had Zoom Out enabled on my google chrome at 30%.

I rolled back the update issuing the command `git reset --keep HEAD@{1}` and that seemed to get my website back to normal again.

**Comment by DanielnetoDotCom** [comment]
What was the issue exactly?

last update require you to clear the cache, due CSS and JS updates

**Comment by akhilleusuggo** [comment]
Same here , very weird on google chrome . Like zooming out . Cleared cache multiple times

**Comment by DanielnetoDotCom** [comment]
can you please screenshot?

I do not get what you mean.

**Comment by JoshWho** [comment]
It made everything tiny like I had Zoom out to 30%

**Comment by DanielnetoDotCom** [comment]
please I screenshot

**Comment by JoshWho** [comment]
<img src="https://static.buddylist.co/squish.png" style='width:100%;' border="0" alt="Null">

**Comment by JoshWho** [comment]
go look here that is this page https://www.joshwhotv.com/v/10400

**Comment by DanielnetoDotCom** [comment]
@JoshWho  your css is different then the one on GItHub 

This is yours
https://www.joshwhotv.com/plugin/TheaterButton/style.css

This is the correct one
https://github.com/WWBN/AVideo/blob/master/plugin/TheaterButton/style.css

![image](https://user-images.githubusercontent.com/18009293/94043673-9cc6eb00-fda3-11ea-87a4-04f4fe5aba13.png)


I am pretty sure is some cache (probably cloudflare and you have to purge)

I also just add something on the code to add a timestamp on the css link to try to bypass the cache when I modify it

**Comment by JoshWho** [comment]
That looks good. I just did an update looks better now more formal.
