### ISSUE TITLE
Live and Meet Plugin

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#3693]
There are available updates for Live and Meet plugin.  However, I don't see them in the plugin store to download updates.  Can someone provide me information where to download plugins or how to update?

Thanks

**Comment by syldri** [comment]
hello, 

Just use the git pull as described here

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by willpower68** [comment]
@syldri 
thank you very much.
