### ISSUE TITLE
Test environment

### ISSUE THREAD

**Issue by Kaljamam** [WWBN/AVideo#3694]
Hello, 

i would like to create a test environment from my existing YouPHPTube installation on my QNAP.

I have copied the database in myphpadmin and created a new one under YouPHPTubeTest.

![grafik](https://user-images.githubusercontent.com/28004920/93982991-44cbbc80-fd82-11ea-9ae3-5135b49ebdfb.png)

Then I copied the complete directory and uploaded it under YouPHPTubeTest

![grafik](https://user-images.githubusercontent.com/28004920/93983915-742ef900-fd83-11ea-82cb-d998046fd215.png)

Unfortunately I don't know how to edit the configuration.php from the video folder.  Which entry should I make at WebSiteRootUrl? 

![grafik](https://user-images.githubusercontent.com/28004920/93983523-f834b100-fd82-11ea-9a9a-a1d421da4a7f.png)

Greetings from Lake Constance
Chris

**Comment by DanielnetoDotCom** [comment]
WebSiteRootUrl is the URL you use to access your site.

maybe you will need to create a virtual host for it.
