### ISSUE TITLE
How can I add subtitles

### ISSUE THREAD

**Issue by awistudio** [WWBN/AVideo#3695]
how to solve the problem? please help
adding subtitles by any user

the user wants to add subtitles. this message appears

![2020-09-22_21-33-16](https://user-images.githubusercontent.com/60708776/94006927-e235e900-fda0-11ea-8862-f5fc455f98b2.png)

**Comment by DanielnetoDotCom** [comment]
Can you reproduce it on the demo site? 

What exactly steps are you making?

**Comment by awistudio** [comment]
this is on my site 
user logged in> my video> create subtitles
this message appears
![2020-09-22_21-33-16](https://user-images.githubusercontent.com/60708776/94010255-f9c3a080-fda5-11ea-87da-0bbd676c1e53.png)

**Comment by awistudio** [comment]
tvpowiatowa.pl

**Comment by DanielnetoDotCom** [comment]
For any user including the admin?

did you try it on the demo site? https://demo.avideo.com/

I need to know if the problem is specific for your site or is a bug for everyone else.

**Comment by awistudio** [comment]
as admin - no problem

**Comment by awistudio** [comment]
I have my own serer

**Comment by awistudio** [comment]
the problem arises for ordinary users

**Comment by DanielnetoDotCom** [comment]
I just confirm it on demo site, I will work on it and notify here an fix update.

**Comment by DanielnetoDotCom** [comment]
I am sending the new SubtitleSwitcher version 2.0, please download it again and overwrite your plugin. this issue may be fixed.

**Comment by awistudio** [comment]
:( all add-ons have disappeared

**Comment by awistudio** [comment]
Houston, we have a problem
all plugins disappeared after installation

**Comment by awistudio** [comment]
I also updated the LIVE user

**Comment by DanielnetoDotCom** [comment]
Please also update your Streamer site with `git pull` command

**Comment by awistudio** [comment]
ok I have the plugs back. I'll check if it works

**Comment by awistudio** [comment]
looks okay. Thank you very much as always
