### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#3696]
Setting up pay per view works fine up to actually paying for it, configured Stripe but only part of the payment form loads, cc fields fail to appear 
![Untitled-8](https://user-images.githubusercontent.com/37193130/94035424-0ab5e700-fd91-11ea-8b77-cd7978f450be.jpg)
The logs show no errors relating to this

**Comment by DanielnetoDotCom** [comment]
I guess it is a JS error, please check your JS console for clues

**Comment by ganddser** [comment]
Console error:

Uncaught IntegrationError: Please call Stripe() with your publishable key. You used an empty string.
    at new r (https://js.stripe.com/v3/:1:6155)
    at new pc (https://js.stripe.com/v3/:1:182408)
    at dc (https://js.stripe.com/v3/:1:183458)
    at https://domain/plugin/PayPerView/subscribePlanPerUser.php?plans_id=4&videos_id=336:1181:26

**Comment by DanielnetoDotCom** [comment]
That explains what you are missing:

Please call Stripe() with your **publishable key**. You used an empty string

**Comment by ganddser** [comment]
I have all the keys in their matching field

**Comment by DanielnetoDotCom** [comment]
please clear the cache and try again. 

also can you check your avideo.log file for some error?

**Comment by ganddser** [comment]
> 
> 
> please clear the cache and try again.
> 
> also can you check your avideo.log file for some error?

I've cleared the cache plenty of times today and the avideo shows no errors for stripe

**Comment by DanielnetoDotCom** [comment]
can you use your Stripe test account and reproduce it on demo site?

**Comment by ganddser** [comment]
Tried on demo site with test key, fields showed up but it wouldn't process the test payment 500 internal server error
