### ISSUE TITLE
Chaptermaker - WEBVTT

### ISSUE THREAD

**Issue by Kaljamam** [WWBN/AVideo#3697]
Hello everyone,

we use this ingenious video platform for our intranet for tutorials. Many tutorials are 10 minutes long, in which for example 8 different points are explained. Not every point interests everyone. So the employee could switch directly to what he needs via the chapter. So it would be great if there were chapters ( not only one playlist ). 

I have found the following possibility:

http://thenewcode.com/977/Create-Interactive-HTML5-Video-with-WebVTT-Chapters

In the directory

YouPHPTube/www/view/js/video.js/examples/elephantsdream/index.html

you can also find chapters.vtt. 

Is there already a possibility to include this? 
Is there a plugin (gladly also a payment plugin)? 
 
Greetings from Lake Constance
Chris

**Comment by Kaljamam** [comment]
I found a way to incorporate the chapter jump labels.
The decisive factor for this is to adapt the script file in the Codepen example above as follows.

`var url = $("#videovtt source").prop("src");`  
`url = url.replace('mp4', 'vtt')`   
`$("video").append("<track kind=\"chapters\" label=\"Locations\" src='"+ url + "' srclang=\"en\" default type=\"text/vtt\">")`

And adjustments have to be made in the video.php.
But it works fine! We are happy!

![grafik](https://user-images.githubusercontent.com/28004920/94549883-27e82b00-0253-11eb-8179-9c5e3c434b1c.png)

**Comment by DanielnetoDotCom** [comment]
This is a nice feature, definally I will take a look on it in the future.
