### ISSUE TITLE
VIdeos are autoplaying again

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3699]
I turned this feature off a few months ago and it is still off in the Configuration setting but for some reason now all videos just start playing and have to be unmuted.

**Comment by freedomshare** [comment]
i have this same issue some times on mobile and for me i think it the fact that the ad_server auto plays ads soon as video loads forcing unmute settings and if you dont click the unmute when asked for youtube videos they will not play sound at all. at least this is what i have found

**Comment by DanielnetoDotCom** [comment]
If the autoplay button is checked the video will autoplay

![image](https://user-images.githubusercontent.com/18009293/94137543-ee6f8400-fe3c-11ea-8d4a-00e3e582f174.png)

**Comment by JoshWho** [comment]
The auto is not checked and also axajx auto is disabled in custom advanced. THis just started happening after the last update.

**Comment by JoshWho** [comment]
I see other video sites that still have videos auto play without being muted. I have a feeling this has something to do with the ads system as well.

**Comment by freedomshare** [comment]
I have tested it and when ad_server plugin is off auto play will not happen the ad server auto play as soon as page loads no matter if you turn auto play setting on or off. 

Autoplay has never been on with my site but soon as ad server plugin is on that when it will happen it like ad serve r plugin over rides the auto play settings

**Comment by JoshWho** [comment]
I thank that narrows this down pretty good. Have to sync the ad server with the autoplay switch some how.

**Comment by freedomshare** [comment]
a a side not the way the video ads work is auto play so kinda make scene as to why it would happen the ad is a video it self and the way the ads work is to start playing when ever they pop up so start mid end etc..

**Comment by JoshWho** [comment]
Has to be a way to do it and still allow the ad server to function.

**Comment by DanielnetoDotCom** [comment]
@freedomshare are you using the latest version?

I guess I did not understand what is the issue. I enabled the ad_server on my side and it still working fine (as expected)

can you please record a video with the issue? also please make sure you are running the latest version.

**Comment by JoshWho** [comment]
No video ad is getting triggered. I have mine set to play at the end of all video plays.

https://static.buddylist.co/No%20video%20ad%20triggererd.mp4

**Comment by DanielnetoDotCom** [comment]
@JoshWho how is your loop option (right click)

Also I just sent an update to notify if the loop is active

**Comment by JoshWho** [comment]
I am still not seeing any ad play at the end of videos

**Comment by DanielnetoDotCom** [comment]
Josh in your side, I try to play a video and what I see was the VMAP request always pending

![image](https://user-images.githubusercontent.com/18009293/94150977-34821300-fe50-11ea-8071-9e2ffd17b364.png)

**Comment by JoshWho** [comment]
WHat would cause that?

**Comment by JoshWho** [comment]
This was working to updates ago now it is not

**Comment by JoshWho** [comment]
Not logged in sees the adds and autoplays still

**Comment by DanielnetoDotCom** [comment]
I am not sure what caused that. I cannot reproduce it here.
I tested Not logged and the VMAP was pending.

I am sending some updates soon regarding autoplay/loop, I am trying to make clear what is happening.

**Comment by JoshWho** [comment]
YAY it is working again. Thank you!!! @DanielnetoDotCom
