### ISSUE TITLE
Channel Home page not showing correctly

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3700]
<img src="https://static.buddylist.co/scrunch.png" style='width:100%;' border="0" alt="Null">

https://www.joshwhotv.com/channel/Whats+New

**Comment by DanielnetoDotCom** [comment]
Mine looks fine

![image](https://user-images.githubusercontent.com/18009293/94134856-f9c0b080-fe38-11ea-8387-5887e2cf5e49.png)

**Comment by JoshWho** [comment]
Is that Chrome?

**Comment by DanielnetoDotCom** [comment]
Yes tested on chrome and FF, maybe you need to clear your browser cache.

**Comment by JoshWho** [comment]
I manually purged the site and it fixed it but the footer background not showing. it is just the black background only

**Comment by DanielnetoDotCom** [comment]
What footer background? I do not understand

**Comment by JoshWho** [comment]
Can you read the footer links?

**Comment by DanielnetoDotCom** [comment]
those?

![image](https://user-images.githubusercontent.com/18009293/94137156-5f626c00-fe3c-11ea-8255-3d6101822063.png)

**Comment by JoshWho** [comment]
Yes. I also noticed they r not clickable

**Comment by DanielnetoDotCom** [comment]
Go to your customizeAdvanced plugin and make sure your parameter footerStyle does not have the `z-index: 1`, it is only `position: fixed;bottom: 0;width: 100%;`

**Comment by JoshWho** [comment]
Got it updated. THank you @DanielnetoDotCom Looks great now.
