### ISSUE TITLE
Turn off autoplay 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3701]
How do I turn off auto-play in the embed code?  It wasn't there before and popped in during an update this past week or so.

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/WWBN/AVideo/wiki/Autoplay-and-Browser-Policies#enable-or-disable-the-autoplay

**Comment by JoshWho** [comment]
I bet this is regarding the last update same problem I am still seeing. In incognito non logged watches video then it sometimes will show video ad then go to next video when autoplay is turned off.

**Comment by DanielnetoDotCom** [comment]
Autoplay/nextvideo/loop

I was playing with it and my last update (few minutes ago) may resolve that.

But ads this is new for me. I guess it is something in your side that is blocking the VMAP

**Comment by fakeologist** [comment]
Mine is set to off. The sharing embed code has it set to on. Autoplay is the scourge of the internet. It must always be off by default.

**Comment by JoshWho** [comment]
Ads is working fine now. Everything looks good now after the latest git pull.

**Comment by fakeologist** [comment]
Still there ![Screenshot_20200924-103038_WordPress.jpg](https://user-images.githubusercontent.com/66537018/94158970-04873f80-fe51-11ea-863a-58a2c88aa7aa.jpg)

**Comment by JoshWho** [comment]
Turn off the master switch in the main configurations

<img src="https://static.buddylist.co/turnoffmasterswitch.png" style='width:100%;' border="0" alt="Null">

**Comment by fakeologist** [comment]
Mine is off.

**Comment by JoshWho** [comment]
What about Ajax Auto Switch in Advance Config

<img src="https://static.buddylist.co/ajaxswitch.png" style='width:100%;' border="0" alt="Null">

**Comment by JoshWho** [comment]
Do not forget to purge the sites cache after turning those off also purge cloudflare if you are using that as well

**Comment by fakeologist** [comment]
> What about Ajax Auto Switch in Advance Config
> 
> <img src="https://static.buddylist.co/ajaxswitch.png" style='width:100%;' border="0" alt="Null">

Sorry where is that setting?

**Comment by JoshWho** [comment]
<img src="https://static.buddylist.co/advconfig.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
@fakeologist I just update your streamer, check it now.

**Comment by fakeologist** [comment]
Still has autoplay. Literally all 6 videos on my blog page start playing at once, with audio. I have to manually take out the autoplay from code. I copy the iframe link from the my videos menu.

**Comment by DanielnetoDotCom** [comment]
I see you are talking about embed content.

you need to update your streamer and clear your cache with this new update

**Comment by fakeologist** [comment]
Yes the embed. Sorry how to update streamer - cache is cleared on browser.

**Comment by DanielnetoDotCom** [comment]
this is how to update https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by fakeologist** [comment]
Autoplay is still in the embed code. Can you please get it out or make it an option to turn off.
![image](https://user-images.githubusercontent.com/66537018/94424209-dad35e80-0157-11eb-8f42-804f2036ed95.png)

**Comment by DanielnetoDotCom** [comment]
If you want to remove it you can do it here 
![image](https://user-images.githubusercontent.com/18009293/94429866-61dd0280-0169-11eb-819f-f0cf1915878f.png)

**Comment by fakeologist** [comment]
Thank you.

**Comment by fakeologist** [comment]
Changed that setting and it still shows.

**Comment by DanielnetoDotCom** [comment]
Did you clear the cache?

**Comment by fakeologist** [comment]
Browser cache clear.

**Comment by fakeologist** [comment]
> Do not forget to purge the sites cache after turning those off also purge cloudflare if you are using that as well

How to purge site cache?

**Comment by DanielnetoDotCom** [comment]
@fakeologist did you update your site with git pull?

**Comment by fakeologist** [comment]
Just now. Autoplay still there. How do I purge the site cache?

**Comment by DanielnetoDotCom** [comment]
> If you want to remove it you can do it here
> ![image](https://user-images.githubusercontent.com/18009293/94429866-61dd0280-0169-11eb-819f-f0cf1915878f.png)

I just went to your site and I removed the autoplay form the plugin above

Clear the cache and now the autoplay is removed from the iframe instructions.

**Comment by fakeologist** [comment]
Thank you. I also removed the autoplay but did not know how to clear the site cache.
