### ISSUE TITLE
Submit comment hangs on Android app 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3702]
It is stuck after submit button, but comment goes through. ![Screenshot_20200924-094458_Fakeotube.jpg](https://user-images.githubusercontent.com/66537018/94153425-c424c300-fe4a-11ea-82cc-f1c2996b042e.jpg)

**Comment by DanielnetoDotCom** [comment]
Does the comment work on the site?

**Comment by fakeologist** [comment]
Yes. Now I can't comment on any video on app.

**Comment by DanielnetoDotCom** [comment]
Thanks, it is fixed, but you only be able to comment after the approval process
