### ISSUE TITLE
Uploading mp3s

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3706]
When I uploaded mp3 audios in the past, the graphic was a static radio audio image.

Now it's a black screen.
Can this be brought back?

**Comment by DanielnetoDotCom** [comment]
It suppose to have the radio. can you please share the link with black screen?

**Comment by fakeologist** [comment]
https://fakeotube.com/v/1015

Black screen

**Comment by DanielnetoDotCom** [comment]
I just update your site with this new release, and seems to work now

**Comment by fakeologist** [comment]
Works. My viewers are already happy.
