### ISSUE TITLE
Videos do not play with SecureVideosDirectory-plugin

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#3708]
After the update from 19-09 videos do not play with SecureVideosDirectory-plugin. Only the pictures are shown.

SecureVideosDirectory-plugin is updated

I restored backup from 19-09 that is working perfect.

Error in **Avido.log**
[25-Sep-2020 17:45:04 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function apache_get_modules() in /var/www/html/archief.beesel-reuver.nl/view/xsendfile.php:40
Stack trace:
#0 {main}
  thrown in /var/www/html/archief.beesel-reuver.nl/view/xsendfile.php on line 40 

**xsendfile.php** line 40
if(preg_match("/(mp4|webm|m3u8|mp3|ogg)/i", $path_parts['extension'])){
        if(empty($_GET['ignoreXsendfilePreVideoPlay'])){
            AVideoPlugin::xsendfilePreVideoPlay();
        }
        if (empty($advancedCustom->doNotUseXsendFile)) {
            //_error_log("X-Sendfile: {$path}");
            header("X-Sendfile: {$path}");
        }
    }else{
        $advancedCustom->doNotUseXsendFile = true;
    }

**Comment by DanielnetoDotCom** [comment]
Are you running Apache?

Probably the Server is running PHP as FPM or some kind of (f)CGI . It might even be a different web server like nginx. Anyway it doesn't run in apache's context and thus the apache_* functions aren't available.

I guess this plugin will not work properly in your environment anyway

**Comment by TLCReuver** [comment]
I'm running php7.3-fpm with Apache with vHost and it always worked perfect until 19-09.

This mean that i can't update anymore ?

**Comment by DanielnetoDotCom** [comment]
please try this update

**Comment by TLCReuver** [comment]
Problem is fixed Daniel.

Thank you very much.
