### ISSUE TITLE
VIDEOJS: WARN: Problem encountered with the current HLS playlist. Trying again since it is the only playlist.

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3712]
Getting this warning what do I need to do?

**Comment by akhilleusuggo** [comment]
You need to provide more details . At the least what browser you're using . 
Usually this issue is from the server's settings , connection issues or corrupted data .

Anyway it's a warning , it is working well ? What is the real issue here ?

**Comment by guymass** [comment]
The real issue is trying to configure the script to only work with NGINX. I took out the Apache and setup the rewrite rules, however now my problem is figuring out how to configure the Live plugin for streaming and recording.
I am not sure how the server urls should be for the server to receive my OBS stream request.

![Screen Shot 5781-01-15 at 12 06 46](https://user-images.githubusercontent.com/58882903/94987709-f9c75b80-0570-11eb-866a-f38417d7d2f7.jpg)

for example this is how my server is configured but I know its wrong as this script was written to work with apache. So I am trying to solve this puzzle.
