### ISSUE TITLE
Server Configuration

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3713]
I am trying to live stream. I see my stream on the RTMP stat page but I cannot see the stream playing on the live page.

I am not sure if my Live plugin is configured correctly. Here is a screenshot of the RTMP and configuration page.
![Screen Shot 5781-01-08 at 2 00 52](https://user-images.githubusercontent.com/58882903/94323469-9781c000-ff9e-11ea-94a2-548c4fe078ed.jpg)
![Screen Shot 5781-01-08 at 2 15 10](https://user-images.githubusercontent.com/58882903/94323470-99e41a00-ff9e-11ea-9071-b9417d6ea421.jpg)

This is my nginx config:
user www-data www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 2048;
    # multi_accept on;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    # server_tokens off;

    server_names_hash_bucket_size 128;
    # server_name_in_redirect off;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
    ssl_prefer_server_ciphers on;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    gzip on;

    include /usr/local/nginx/conf.d/*.conf;
    include /usr/local/nginx/conf/default.conf;
    include /etc/nginx/conf.d/*.conf;
#    include /var/www/html/YouPHPTube/rewrites.conf;
#    include /var/www/html/YouPHPTube/rewrites-encoder.conf;

 server {

        listen      8080;

        # This URL provides RTMP statistics in XML
        location /stat {
            rtmp_stat all;

            # Use this stylesheet to view XML as web page
            # in browser
            rtmp_stat_stylesheet stat.xsl;
	    allow all;
	    add_header Refresh "3; $request_uri";

        }

        location /stat.xsl {
            # XML stylesheet to view RTMP stats.
            # Copy stat.xsl wherever you want
            # and put the full directory path here
            root /var/www;
        }

        location /hls {
            # Serve HLS fragments
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /tmp;
            add_header Cache-Control no-cache;
        }

        location /dash {
            # Serve DASH fragments
            root /tmp;
            add_header Cache-Control no-cache;
        }
    }
}

rtmp {
    server {
        listen 1935;
        chunk_size 4000;
	allow play all;
        #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
        application live {
            allow play all;
            live on;
            #record all;
            record_path /var/www/tmp;
            record_unique on;
            record_max_size 100M;
            record all;
            record_notify on;
            record_suffix -%d-%b-%y-%T.flv;
            hls on;
            hls_nested on;
            hls_path /HLS/live;
            #hls_playlist_length 4s;
            #hls_fragment 1s;
            hls_fragment 10s;
            allow publish all;
	    allow play all;
            deny publish all;
            on_publish http://fetube.flatearth.co.il/plugin/Live/on_publish.php;
            on_play http://fetube.flatearth.co.il/plugin/Live/on_play.php;
            on_record_done http://fetube.flatearth.co.il/plugin/Live/on_record_done.php;

	}
    }
}

Please help me resolve this.

**Comment by akhilleusuggo** [comment]
This issue is duplicated of many other issues related .
You're misconfiguring the redirect ( or forcing the redirect to https )

Try to add exception of https to `on_play.php` `on_record_done.php` and `on_done.php`
Nginx does not support https on it's config . As you can see here : 

> on_publish http://fetube.flatearth.co.il/plugin/Live/on_publish.php;
> on_play http://fetube.flatearth.co.il/plugin/Live/on_play.php;
> on_record_done http://fetube.flatearth.co.il/plugin/Live/on_record_done.php;

Those URLs should be accessible for nginx via http and not https

**Comment by guymass** [comment]
But they are configured with http so I don't get what you mean? I was researching this issue and sure it is allover with bits and pieces scattered. Would be nice to have a complete install guide.
