### ISSUE TITLE
Plugins not updating!

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3714]
After updating plugins on my site I notice those two do not change the status to updated with the new version number even after uploading them.
![Screen Shot 5781-01-08 at 3 17 13](https://user-images.githubusercontent.com/58882903/94325524-7ffb0500-ffa7-11ea-9545-4bd5911d761d.jpg)

**Comment by DanielnetoDotCom** [comment]
For the Meet plugin you must make a git pull in your server

For the MP4Thumbs you need to download it again on the marketplace site
