### ISSUE TITLE
Market place bug

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3717]
![image](https://user-images.githubusercontent.com/52116577/94341279-a1dca200-0010-11eb-9fbc-ff90552f7c44.png)

Can't login with facebook account ( like usually )

**Comment by DanielnetoDotCom** [comment]
I can see now, I am blocked from Facebook again. (third time)

Can you please create an account on the https://tutorials.avideo.com/ and use it to login?

than please send me you facebook email and your new account # and I will transfer your purchases to it.

**Comment by akhilleusuggo** [comment]
Sent

**Comment by DanielnetoDotCom** [comment]
Please check now

**Comment by akhilleusuggo** [comment]
yep nice
