### ISSUE TITLE
LiveUsers Not Working

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3719]
Live_Users plugin not working . Nothing on logs , just not displaying anywhere .

**Comment by DanielnetoDotCom** [comment]
is the plugin up to date?

It is working on demo.

**Comment by akhilleusuggo** [comment]
I had to completely delete it and upload it . I'm sure is not a permission issue , but something got corrupted into it .
Anyway fixed by manual delete . Thanks .

**Comment by ganddser** [comment]
@DanielnetoDotCom Liveusers hasn't been working for a while 
 [12-Dec-2020 09:55:18 America/Chicago] PHP Warning:  require_once(path/to/my/streamer/site/plugin/LiveUsers/Objects/LiveOnlineUsers.php): failed to open stream: No such file or directory in path/to/my/streamer/site/plugin/LiveUsers/LiveUsers.php(14) : eval()'d code(1) : eval()'d code on line 5

**Comment by DanielnetoDotCom** [comment]
Looks like you have the plugin in the database but you do not have the files in the plugin directory

**Comment by ganddser** [comment]
The files are in the plugin directory I assure you

**Comment by DanielnetoDotCom** [comment]
maybe a permission 

path/to/my/streamer/site/plugin/LiveUsers/Objects/LiveOnlineUsers.php

check on the real log file what is the complete path, and make sure the file is available.

**Comment by ganddser** [comment]
@DanielnetoDotCom Sent you an email 2 days ago

**Comment by DanielnetoDotCom** [comment]
Can you please post here?

I guess I missed that email.

**Comment by ganddser** [comment]
It's a job bro. check again I just resent it

**Comment by DanielnetoDotCom** [comment]
I checked and I did respond to you yesterday. but I have never heard back from you.

**Comment by ganddser** [comment]
I haven't seen a reply to that email from you

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/102622384-b320e080-411f-11eb-8128-9df7d7528f69.png)
