### ISSUE TITLE
youtube / Meet

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3720]
hello @DanielnetoDotCom , I have a question I don't understand, why with meet you have to use youtube to create a live

![image](https://user-images.githubusercontent.com/39193219/94352707-e300a080-0068-11eb-828b-e24efacd6e0f.png)

**Comment by DanielnetoDotCom** [comment]
I guess you are using your own jitsi, NOT the servers we provide.

check the differences here https://github.com/WWBN/AVideo/wiki/Meet-Plugin#types-of-servers

**Comment by syldri** [comment]
there is the same thing on your demo site

I don't have a server installer for jitsi,

I use what you provided

**Comment by DanielnetoDotCom** [comment]
I see , thanks for the info

What browser are you using?

Can you please share your JS console screenshot?

**Comment by syldri** [comment]
I'm on google chrome


![image](https://user-images.githubusercontent.com/39193219/94353681-33313000-0074-11eb-81cc-bd7d1456f115.png)

![image](https://user-images.githubusercontent.com/39193219/94353700-59ef6680-0074-11eb-9e14-227489da6a15.png)

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by syldri** [comment]
hello, it's much better now thank you
