### ISSUE TITLE
Apache2.4 .htaccess 'order allow, deny' issue

### ISSUE THREAD

**Issue by wiperawa** [WWBN/AVideo#3723]
**Describe the bug**
Install on apache2.4 results in 500 server error, because apache 2.4 dont know 'order allow, deny' derictive

**To Reproduce**
1. get Apache 2.4 
2. clone master branch of AVideo
3. run it

**Expected behavior**
Normal installation routine.

**Error Logs**
/.htaccess: Invalid command 'Order', perhaps misspelled or defined by a module not included in the server configuration

**Comment by wiperawa** [comment]
Pull request that fix this issue: https://github.com/WWBN/AVideo/pull/3722

**Comment by DanielnetoDotCom** [comment]
thanks accepted
