### ISSUE TITLE
Doesn't stay logged in

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3724]
In the last week I can't stay logged in to the site.
Even if I click "remember me" I get logged out and have to re-login.

**Comment by DanielnetoDotCom** [comment]
I could not detect it, also could not reproduce. but I am sending some updates to try to prevent it to happen. please confirm me if makes any difference .

you will need to make a git pull in your server. make sure you logoff and login again.

**Comment by JoshWho** [comment]
I can confirm this. I was just going to open another topic. Something keeps expiring the cookie sessions

**Comment by JoshWho** [comment]
So far since my last message I ran a git pull and have stayed logged in for a couple hours now. Looks like it is fixed.

**Comment by freedomshare** [comment]
mine also will do the same also forgets the user when you check remember me

**Comment by DanielnetoDotCom** [comment]
@freedomshare did you make a git pull from the last couple days?

**Comment by JoshWho** [comment]
This is still happening with me too. Not sure how long it takes but everytime I leave for about 4 5 hours and come back home I have to log back in. Something keeps eating the cookies LOL

**Comment by akhilleusuggo** [comment]
It's something related to one of the updates . Session ID expiration (cookie) . I bet it's something related to this : 
https://github.com/WWBN/AVideo/commit/13e6dde5e8177c55535a719a1aaed5b21e31ccb7

This line : 

https://github.com/WWBN/AVideo/blob/7b98dc0f9b7bea4772baaf7a0f79bf06f49a230c/objects/user.php#L811

**Comment by freedomshare** [comment]
i do git pull daily, still have the issue just take longer to happen,

**Comment by fakeologist** [comment]
Me too still happening.

**Comment by DanielnetoDotCom** [comment]
I will send an update soon, I hope it resolves.

**Comment by freedomshare** [comment]
Mine still logs out after update

**Comment by DanielnetoDotCom** [comment]
Please make sure you logout and login again, then you keep the eyes opened

**Comment by freedomshare** [comment]
i logged back after the update and logged me out again but ill see what happens now that i relogged in again

**Comment by JoshWho** [comment]
It still loggs me out

**Comment by freedomshare** [comment]
Still happens.to me.

**Comment by akhilleusuggo** [comment]
I don't use this feature , but why not just add some ridiculous number here ?

![image](https://user-images.githubusercontent.com/52116577/94923200-240f0f80-04c4-11eb-8945-d2d379e4ff38.png)

**Comment by JoshWho** [comment]
I forgot about that. I will do that

**Comment by DanielnetoDotCom** [comment]
> I don't use this feature , but why not just add some ridiculous number here ?
> 
> ![image](https://user-images.githubusercontent.com/52116577/94923200-240f0f80-04c4-11eb-8945-d2d379e4ff38.png)

is it working?

maybe this is overwriting the cookies lifetime?

**Comment by DanielnetoDotCom** [comment]
I am setting multiple cookies to see if one of them will work

**Comment by fakeologist** [comment]
still not staying logged in.

**Comment by akhilleusuggo** [comment]
I tested it , and does work if you add a lot of time in session timeout .

**Comment by fakeologist** [comment]
where is that again?

**Comment by akhilleusuggo** [comment]
logged as admin . site configuration  , advanced configuration

**Comment by fakeologist** [comment]
thank you will try.

**Comment by fakeologist** [comment]
Still logging me out.

**Comment by DanielnetoDotCom** [comment]
@fakeologist can you please make. `git pull` in your site?

**Comment by fakeologist** [comment]
I'll report back.
