### ISSUE TITLE
Meet  /room deletion problem

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3725]
hello @DanielnetoDotCom  when i want to delete a room, i stay in Processing ... i need to refresh the page and delete again

I tested it on your demo site

![image](https://user-images.githubusercontent.com/39193219/94424611-c9f01080-018a-11eb-9de9-e3b02647ddd7.png)

**Comment by DanielnetoDotCom** [comment]
Hi

It does work on my side. not sure what is missing, but I could not reproduce it.

can you check your avideo.log?
