### ISSUE TITLE
Youtube thumbnail not showing

### ISSUE THREAD

**Issue by Vdriod** [WWBN/AVideo#3727]
After installing the software I noticed some of the embedded youtube thumbnail refused to display on the homepag. Small size files from youtube displays thumbnails but big size did not.
![IMG_20200928_192524](https://user-images.githubusercontent.com/55185473/94471029-65e83f00-01c0-11eb-9a97-f5f4037b1ae1.jpg)

**Comment by Vdriod** [comment]
No need I got it figured

**Comment by DanielnetoDotCom** [comment]
can you please share what was?
