### ISSUE TITLE
Empty plugin list

### ISSUE THREAD

**Issue by Joelp** [WWBN/AVideo#3729]
After last update, I'm on commit 0573a276549fe5a88ae4c4c1d22b63c786ec71a0, list of plugins disappeared.
![obrazek](https://user-images.githubusercontent.com/19979522/94517129-90b9ae00-0227-11eb-902c-dd7017a8ffe2.png)

**Comment by DanielnetoDotCom** [comment]
check your avideo.log file

**Comment by Joelp** [comment]
Looks like this is root problem:

`[sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'aVideoWeb.ip2location_db3' doesn't exist<br>
SELECT * FROM ip2location_db3 WHERE INET_ATON(?) <= ip_to LIMIT 1 - format=s values=["W.X.Y.Z"]`

And there is also:
`PHP Notice:  Undefined index: country_code in /path-to-avideo/objects/Object.php on line 329`

**Comment by DanielnetoDotCom** [comment]
you did not install the user_location tables and you have it enabled.

I will send an update to avoid this error

**Comment by Joelp** [comment]
After update, plugins list is back. But I have no activated user location plugin:
![obrazek](https://user-images.githubusercontent.com/19979522/94646859-7f3bd900-02ef-11eb-8e57-0d0b53a77a76.png)

Even if I enable this plugin, there is no button to install tables

**Comment by DanielnetoDotCom** [comment]
Click on the plus (+) button for more instructions

**Comment by Joelp** [comment]
But I do not use the User_Location addon

**Comment by DanielnetoDotCom** [comment]
So do not worry about it.
