### ISSUE TITLE
cache directory named '' - ''

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3730]
Can you change the cache directory with name `-` , giving some errors when deleting .

![image](https://user-images.githubusercontent.com/52116577/94547367-db531e80-0257-11eb-9ca0-613ff72a209a.png)

**Comment by DanielnetoDotCom** [comment]
Sorry I am confused, do we have a directory called `-` ??
If we do it is a mistake

**Comment by DanielnetoDotCom** [comment]
I am sending an update to make sure the `-` symbol will not be on the directory name

**Comment by akhilleusuggo** [comment]
thank you 👍
