### ISSUE TITLE
This entry is totally clogging my avideo.log

### ISSUE THREAD

**Issue by dbmasters** [WWBN/AVideo#3731]
AVideoLog::DEBUG: CustomizeUser::canShareVideosFromVideo canShareVideosFromUser(2) = false SCRIPT_NAME: /view/index.php

Is a LARGE percentage of my logs. What is this from, I am trying to debug the encoder (it's not moving files back to the streaming site...it's impossible to weed thru with all this noise. Any tips on getting rid of those?

For now I simply commented out the error log line in the plugin to get rid of the noise, but, is there a better solution? Perhaps this is something related to the differences of newer PHP versions like a couple other log errors I have been fixing?

**Comment by DanielnetoDotCom** [comment]
add this in your configuration.php file 

`$global['noDebug'] = 1;`

**Comment by dbmasters** [comment]
Oh, just that easy, awesome, thanks much.
