### ISSUE TITLE
Blank page after update

### ISSUE THREAD

**Issue by eZweblogic** [WWBN/AVideo#3732]
Hello,
Whole website went blank after update. I started the update process with git then when I tried to login to admin panel to complete the update everything went blank both on front end and back end.
**Expected behavior**
to start the update process from the control panel

**Error Logs**
require_once $global['systemRootPath'].'objects/include_config.php'; require_once $global['systemRootPath'].'objects/include_config.php'; require_once $global['systemRootPath'].'objects/include_config.php'; require_once $global['systemRootPath'].'objects/include_config.php'; require_once $global['systemRootPath'].'objects/include_config.php'; require_once 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DanielnetoDotCom** [comment]
your logs does not say much, please provide a more complete info

**Comment by eZweblogic** [comment]
Hi Daniel

This is the last error message repeated hundreds of time

[Tue Sep 29 15:56:21.643664 2020] [:error] [pid 21513] [client 185.191.171.22:65426] PHP Fatal error:  require_once(): Failed opening required 'objects/include_config.php' (include_path='.:/usr/share/php') in /var/www/html/YouPHPTube/view/index.php on line 19

Also when I tried updating ubuntu I got the following message

After this operation, 18.1 MB of additional disk space will be used.
E: You don't have enough free space in /var/cache/apt/archives/.


Filesystem      Size  Used Avail Use% Mounted on
udev            5.9G     0  5.9G   0% /dev
tmpfs           1.2G  114M  1.1G  10% /run
/dev/sda2       295G  280G   38M 100% /
tmpfs           5.9G     0  5.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           5.9G     0  5.9G   0% /sys/fs/cgroup
/dev/sda1       922M   52M  807M   7% /boot

I guess this is because of no space on the server.
Can you install or move to another server?

**Comment by DanielnetoDotCom** [comment]
For sure you did not update it correctly, and it was probably because of your disk is full

**Comment by eZweblogic** [comment]
Alright Daniel

I just got a new server with Ubuntu 18.04 Minimal (can use any other version if needed)

Can you move files from old server to new one and how much it costs?

Do I need to change dns record now or better wait until you’re done?

Thanks

**Comment by DanielnetoDotCom** [comment]
Hi, for services and quotations please email developer@youphptube.com
