### ISSUE TITLE
pb with changing domain name

### ISSUE THREAD

**Issue by ekc-fr** [WWBN/AVideo#3733]
hi,

my youphptube was on a domain which change.

before: http://youphptube.olddomain.fr
now: https://youphptube.newdomain.fr

some parts of the site are always referenced on the old domain: the js scripts files
I clean the cache (server and browser)

I have a look on all the configuration (yaml, .htaccess, web.config, database) i'don't find anay reference to the urls.

what did i missed ?

**Comment by DanielnetoDotCom** [comment]
Check the customizeAdvanced plugin

![image](https://user-images.githubusercontent.com/18009293/94686895-dc408a80-0301-11eb-85c8-2abb300a3b6d.png)

**Comment by ekc-fr** [comment]
nothing found in plugin sonfiguration (i just use cache and gallery plugins )

**Comment by DanielnetoDotCom** [comment]
what parts are you seeing referring the old domain?

**Comment by ekc-fr** [comment]
the javascript files ( jquery, script.js, ... )

**Comment by DanielnetoDotCom** [comment]
where? please screenshot

**Comment by ekc-fr** [comment]
evrerything is taken from the old url (for security reasons the js files are blocked)

![image](https://user-images.githubusercontent.com/44778782/94813830-cd88cf00-03f8-11eb-8558-85788faea9cc.png)

**Comment by DanielnetoDotCom** [comment]
are you sure you clear the cache?

**Comment by ekc-fr** [comment]
I use the button in the admin page

**Comment by DanielnetoDotCom** [comment]
try to manually delete it from the cache directory.

**Comment by ekc-fr** [comment]
i delete the cache's files
always the same errors

**Comment by DanielnetoDotCom** [comment]
Please make sure you follow this https://github.com/WWBN/AVideo/wiki/Change-the-URL-of-your-installation
