### ISSUE TITLE
Streamkey

### ISSUE THREAD

**Issue by kevinschreiber** [WWBN/AVideo#3734]
Good morning, I have already reported the incident by e-mail. And it is not possible for the site to give me a streamkey, I have already tried to install my own encoder, to no avail. Does anyone have any tips? 
Screenshot:
https://www.directupload.net/file/d/5957/5kt4hs8n_png.htm

Log:
https://pastebin.com/PsvqW37v

Desktop:
Chrome and Explorer

Device:
Laptop Win 10 newest update

Best regards,
Kevin

**Comment by DanielnetoDotCom** [comment]
Your logs did not open

**Comment by kevinschreiber** [comment]
How do you mean that?
You can open the log with the pastebin link!

Best regards,
Kevin

**Comment by DanielnetoDotCom** [comment]
Now it open, and I can see some missing tables.

make sure you install the tables before enable the plugin.

**Comment by kevinschreiber** [comment]
How I install the tables?

**Comment by kevinschreiber** [comment]
Ah okay, i got it.
But now if i want to teststream with the OBS-Software it couldn't connect and don't stream.
Here the pictures:
![image](https://user-images.githubusercontent.com/67086693/94652610-99c77f80-02fa-11eb-81a3-cbce73cf9cef.png)
![image](https://user-images.githubusercontent.com/67086693/94652742-cf6c6880-02fa-11eb-9165-2a7f58647003.png)

Best regards,
Kevin

**Comment by kevinschreiber** [comment]
So i activated all options what can i do that it works?
![image](https://user-images.githubusercontent.com/67086693/94666961-6f7fbd00-030e-11eb-8a5f-aa475b2baa87.png)
In the nginx.conf the parameters got changed.

**Comment by DanielnetoDotCom** [comment]
Check your nginx log

**Comment by kevinschreiber** [comment]
Where i find the log?

**Comment by kevinschreiber** [comment]
???
Please help don’t find the Logs

**Comment by DanielnetoDotCom** [comment]
Did you install nginx? what is the location?
