### ISSUE TITLE
Quick question regarding mp3 encoding

### ISSUE THREAD

**Issue by dbmasters** [WWBN/AVideo#3735]
So if I want ALL mp3's to be encoded thru the spectrum visual generator, how do I set that up, simply move the command in the database to the mp3 row from the spectrum row, or, is there elsewhere, or some plugin, that controls that?

**Comment by akhilleusuggo** [comment]
On your encoder ( as admin ) , you have configuration . You can set ip up from there .

**Comment by dbmasters** [comment]
I understand that, I see the encoding options, and the MP3 to Spectrum.MP4 configuration command, but that does tell me HOW to set it up...that is what I am asking. Do I take that command line and paste into the MP3 file type or what? What I am asking is how specifically to make it happen for every mp3 that is uploaded.

**Comment by akhilleusuggo** [comment]
you do nothing . You just set it up one time , and you're done ... Every modification you make under configuration is saved on the database . 

If you're asking about custom option , then you should take a look at ffmpeg documentation in case you wanna implement some new type of spectrum ( shockwave etc  ).

The only thing that you need to do , is indicate to the encoder that the file you're uploading is an audio . So just click here , and you're done . No configuration is required .

![image](https://user-images.githubusercontent.com/52116577/94733782-ee0d4680-0370-11eb-89f4-9507a1cc4952.png)

**Comment by dbmasters** [comment]
That is the problem, Create Video Spectrum is not visible in my encoder, and I can't see where to enable it.

**Comment by akhilleusuggo** [comment]
Only after you click Extract Audio , will give you the option if just audio , or audio with Spectrum .

**Comment by dbmasters** [comment]
Ahhhhhhhhhhh, thanks!

Not very intuitive, but now I can document it! Thanks!
