### ISSUE TITLE
Cache Purge Logs me out

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3736]
Everytime I click Purge Cache I get a message saying 

Sorry!
Your cache has NOT been cleared!

THen I get logged out

**Comment by akhilleusuggo** [comment]
maybe permissions issue . `/var/www/html/AVideo` ( or where ever you have it )
`chown www-data:www-data -R *`

**Comment by JoshWho** [comment]
No that is not the issue.

**Comment by JoshWho** [comment]
I can click CLear Cache for First Page button but not the whole cache for some reason

**Comment by DanielnetoDotCom** [comment]
Maybe you have too many files in the cache.

try to delete the cache folder using the command line

**Comment by JoshWho** [comment]
Not exactly sure how to do that it being a sym link tied to a ssd
