### ISSUE TITLE
Connect Error (1045) Access denied for user ''@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by jovemempresario** [WWBN/AVideo#3737]
está ocorrendo esse error quando clico em install now 
Connect Error (1045) Access denied for user ''@'localhost' (using password: NO)
já tentei resolver mais não consigo 
https://prnt.sc/uq5359 aqui está o link

espero que possa me ajudar o mais rápido possível

**Comment by akhilleusuggo** [comment]
on your database host , you have a `space` between` sql311 .epizy.com` . Try this one `sql311.epizy.com`

**Comment by jovemempresario** [comment]
na verdade não estou com os mesmo problema não tem nenhum espaço

**Comment by jovemempresario** [comment]
continua com o mesmo erro

**Comment by jovemempresario** [comment]
> on your database host , you have a `space` between` sql311 .epizy.com` . Try this one `sql311.epizy.com`

continua com o erro não tem nenhum espaço

**Comment by DanielnetoDotCom** [comment]
Nao sei o que é exatamente mas parece que o formulario nao enviou seu usuário do banco de dados.

**Comment by jovemempresario** [comment]
> Nao sei o que é exatamente mas parece que o formulario nao adicionou seu usuário do banco de dados.

tem como resolver?

**Comment by jovemempresario** [comment]
bom conseguir resolver o problema e que só fica na tela verde dizendo que tudo está correto diz para eu esperar mais não sai daquela tela

**Comment by DanielnetoDotCom** [comment]
olhe os logs do apache
