### ISSUE TITLE
Clickable video title leads to video site 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3738]
http://somup.com/cYQvlMl6fT

Please watch above video.

titles in video embeds should lead to video site entry, not to site reference .

**Comment by DanielnetoDotCom** [comment]
Hi, I just fix and update your site, can you please confirm?

**Comment by fakeologist** [comment]
Works! That's service!
Can you tell me where the setting is to the main blog - I can't find it anywhere in the config. It must be somewhere.

**Comment by DanielnetoDotCom** [comment]
Sorry settings to what?

it was a fix on the code, NOT a setting.

**Comment by fakeologist** [comment]
I realise that - somewhere there was a link to the blog that your code found to go to the main website. Where did it find that link?

**Comment by DanielnetoDotCom** [comment]
was not a link, it was an empty href that was redirecting you to the top host site (browser default behavior )

**Comment by fakeologist** [comment]
Got it thanks.
