### ISSUE TITLE
SEO Correction for Channel Pages

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3740]
Currently right now when viewing any channel page the first thing that shows in the title is the website name. Should be the channel name.

Look here for example https://www.joshwhotv.com/channel/SirMarkFrederickMcKinney

```
<html lang="us">
--
  | <head>
  | <title>JoshWho TV \| Vlogs, Podcasts, Rants, You... :: Channel :: SirMarkFrederickMcKinney SirMarkFrederickMcKinney </title>
  | <meta charset="utf-8">
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | <meta name="viewport" content="width=device-width, initial-scale=1">
  | <meta name="description" content="Alternative Free Speech Live Streaming Video Platform with Monetization for Creators. Start having fun creating content without suppression of your free speech.  JoshWho TV -  Channel - SirMarkFrederickMcKinney SirMarkFrederickMcKinney">
  | <script src="/cdn-cgi/apps/head/njKtWM2y5Go_EYFZq-ToQwmatYM.js"></script><link rel="apple-touch-icon" sizes="180x180" href="https://www.joshwhotv.com/videos/favicon.png?1601477003">
  | <link rel="icon" type="image/png" href="https://www.joshwhotv.com/videos/favicon.png?1601477003">
  | <link rel="shortcut icon" href="https://www.joshwhotv.com/videos/favicon.ico?1601477003" sizes="16x16,24x24,32x32,48x48,144x144">
  | <meta name="msapplication-TileImage" content="https://www.joshwhotv.com/videos/favicon.png?1601477003">


```

It should just be the plane "channel name" and thats it or "Channel name's | Channel" so people see the difference in search

**Comment by akhilleusuggo** [comment]
@JoshWho Can I ask you I question not related to this , but to SEO .
When google does crawl your site , how many videos does it crawl per video page ? In my case , does always crawl the next video to play , and does display the preview and the thumbnail wrong .

PS : I see you having the same problem . The main video is considered to be the secondary. 

https://search.google.com/test/rich-results

URL : https://www.joshwhotv.com/v/27201

![image](https://user-images.githubusercontent.com/52116577/94712868-babbbf00-0352-11eb-947a-3e3ef92cdbc4.png)



Google search results : 

![image](https://user-images.githubusercontent.com/52116577/94712521-44b75800-0352-11eb-95fe-daa5365fc96a.png)

The thumbnail is not correct . 
![image](https://user-images.githubusercontent.com/52116577/94712618-687a9e00-0352-11eb-8e4f-c0bbd66a464b.png)

Also not always picking the right url ...

I've broke my head with this , can't figure out how to stop google from crawling the lateral video-list .

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo are you saying google is always picking the next video?

I will remove the `itemprop="thumbnail"` and `itemprop="thumbnailUrl"` from all the videos in the list, maybe it make it stop

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom It's always picking the wrong one yes . Only very very old videos after many time , google is able to guess the right thumbnail . I'll give it a try .

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I'm about to cry , you made it !! FINALLY !! ONLY ONE VIDEO SHOWING NOW !!!!!!

**Comment by DanielnetoDotCom** [comment]
LOL, I guess too many itemprop on the same page confuses google

**Comment by DanielnetoDotCom** [comment]
BTW, how do you test it?

**Comment by akhilleusuggo** [comment]
https://search.google.com/test/rich-results

**Comment by JoshWho** [comment]
Looks good now THank you
