### ISSUE TITLE
Video/s not playing

### ISSUE THREAD

**Issue by julzxcapz** [WWBN/AVideo#3741]
Hi,

The videos on my site are working fine before, after updating my repo the video keeps loading and not playing. I tried uploading new video but still the same, Is there a plugin required now for the video to play ?

**Here's my log:**
![image](https://user-images.githubusercontent.com/61785146/94736679-32afd680-039f-11eb-8c92-708fc6f977db.png)

Thank you in advance!

**Comment by DanielnetoDotCom** [comment]
Check the AVideo log at the moment you try to play the video. also check the JS console log.

on the log you share here there is not much to help

**Comment by julzxcapz** [comment]
That's the log generated when loading/playing the page/video.

For **console log** :
![image](https://user-images.githubusercontent.com/61785146/94738137-93401300-03a1-11eb-8a0f-b09804d8371e.png)

**Comment by DanielnetoDotCom** [comment]
I cannot see any error regarding to play

check if the file exists and if the file is playing directly, check inside the <video><source>

**Comment by julzxcapz** [comment]
Sorry where can I can check -  if the file is playing directly ?

File exist : 
![image](https://user-images.githubusercontent.com/61785146/94739592-cbe0ec00-03a3-11eb-8061-92c8e4373973.png)

**Comment by DanielnetoDotCom** [comment]
To check if the file is playing directly, copy the URL in the <source src="URL"> and paste it in the browser

**Comment by julzxcapz** [comment]
This when copy the source url in the browser :
![image](https://user-images.githubusercontent.com/61785146/94740525-6beb4500-03a5-11eb-821b-579ad197c9cf.png)

And this when downloaded the file (working) :
![image](https://user-images.githubusercontent.com/61785146/94740641-963d0280-03a5-11eb-808c-5282a85a6226.png)

**Comment by DanielnetoDotCom** [comment]
Ok, I guess you do not have the xsendfile properly configured

check this https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

**Comment by julzxcapz** [comment]
I will check and try that one. Thank you

**Comment by julzxcapz** [comment]
Thank you! that solved my problem, videos are now working fine 💯
