### ISSUE TITLE
Videos are not listed on the homepage

### ISSUE THREAD

**Issue by angelawong** [WWBN/AVideo#3743]
**Describe the question**
I have a video that is both public and active. It is viewable when I click directly from My Videos but it is not listed on the homepage.

When I go to the homepage, I see the following error message:

_Warning! We have not found any videos or audios to show.
This video is not available
Sorry about that._

Please advise. Thanks so much!

**Screenshots**
<img width="820" alt="homepage" src="https://user-images.githubusercontent.com/1007028/94759162-2a3ea800-036d-11eb-9e5d-98126ca55ea0.png">

**Comment by JoshWho** [comment]
Could you provide a link so we can see what it is doing?

**Comment by JoshWho** [comment]
Could be a cache issue

**Comment by akhilleusuggo** [comment]
@angelawong I bet you just started your site , you need AT THE LEAST to have 4 videos to be able to see them displayed on the main page . Upload 4 shot videos then let us know .

**Comment by angelawong** [comment]
akhilleusuggo Yes. It was my bad. I accidentally posted it in the avideo-encoder forum instead of this one.

**Comment by angelawong** [comment]
@akhilleusuggo Yes, you are right. I just started my site. I am going to post more videos to see if that were the case. Will keep you all posted.

**Comment by angelawong** [comment]
@akhilleusuggo After adding a few more videos, they are now showing up on my home page. Thanks so much!
