### ISSUE TITLE
Where are the instructions for setting up an encoder network

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#3746]
After many days of searching, I cannot find any instructions for setting up an encoder network. I am looking for how to install and set it up.

Can someone please send me a link to the proper instructions.

Thank you

**Comment by JoshWho** [comment]
Here https://github.com/WWBN/AVideo-Encoder-Network

**Comment by The-Do-It-Yourself-World** [comment]
It says "We have created a similar installer as AVideo installer. on the first time you tried to access the page you will be directed to the installation page."

But can I install this on the main server? Separate server?

Are there no SSH commands or do I have to use FTP to upload the files manually and then click on "install"?

That one line is too vague for me.

Thank you

**Comment by akhilleusuggo** [comment]
You can use command line , and can be done on the same server or separated server .
Go to your public directory 
* git clone https://github.com/WWBN/AVideo-Encoder-Network.git
* configure your apache2 webserver or browser with IP/AVideo-Encoder-Network ( not recommended ) . 
* follow with the installation process 
* You're done , if you wanna add or remove , can be done from database or from /AVideo-Encoder-Network/install directory , you will find a file named `encoders.php` . You can execute it with `php encoders.php` , and read the options .
