### ISSUE TITLE
VideoHLS plugin update bug

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3747]
Doesn't gives the option to select qualities .

**Comment by DanielnetoDotCom** [comment]
Do you mean the new version I submit today?

It is working on demo

![image](https://user-images.githubusercontent.com/18009293/94871852-64698180-0421-11eb-9bd5-639a3a8eb788.png)

**Comment by akhilleusuggo** [comment]
Maybe some cache issues that I had . Is working now .
Since I have opened this issue , can you tell me what does this option exactly do on the HLS plugin ?
![image](https://user-images.githubusercontent.com/52116577/94873139-0c4d7200-0457-11eb-9c08-3c0065798dce.png)

**Comment by DanielnetoDotCom** [comment]
It enable this option = true 

https://github.com/videojs/http-streaming#overridenative

**Comment by akhilleusuggo** [comment]
Actually there are a lot of useful options that could be implemented . Thank you for the information !!

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom btw , I see where the issue was coming from . The place of the HLS quality selection does change of places ... I don't know why , but happens also on the mp4 videos .

![image](https://user-images.githubusercontent.com/52116577/94914662-1b164200-04b4-11eb-9bb6-6ec0a4150835.png)

**Comment by DanielnetoDotCom** [comment]
Can you also confirm this on demo site?

**Comment by akhilleusuggo** [comment]
it happens randomly ... Is not something to prove or not . Just happens , and other videos here for example normally showing . 

![image](https://user-images.githubusercontent.com/52116577/94915912-5fa2dd00-04b6-11eb-83e1-21b68b797e9c.png)

Also is hard to test this type of things when you having 10-20 videos ( that are actually hosted on the site ) and not booked
