### ISSUE TITLE
PayPerViewLive

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3748]
Hello @DanielnetoDotCom  what is this plugin

 PayPerViewLive

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/94902758-5fe4ad80-04a1-11eb-9bf3-72a2818cf4ba.png)

Similar to PayPerView , but this one for live-streams

**Comment by syldri** [comment]
@akhilleusuggo  
I don't know if there is a demand for this plugin.

there are a lot of things to do to improve the site,
very important plugins to do

I don't understand @DanielnetoDotCom  priorities

**Comment by akhilleusuggo** [comment]
@syldri I believe the priorities are based on people who pays for them

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo you are correct
