### ISSUE TITLE
signIn API

### ISSUE THREAD

**Issue by julzxcapz** [WWBN/AVideo#3750]
Hi,

I'm using the signIn API then redirects to the AVideo Platform after signIn success but what happens is the account used didn't login to the Platform after redirected. I think it's needs modification on how to set the cookie, need help on this. Thank you!

**Comment by DanielnetoDotCom** [comment]
how exactly are you using? if is inside an iframe cross domain it will probably not work due security reasons

check this https://stackoverflow.com/questions/3342140/cross-domain-cookies

the solution is to pass the user and the encrypted pass every request.

**Comment by julzxcapz** [comment]
I'm using ajax request same as the first answer on that thread, the cookie still not saving when I checked but when I tried to customizing the cookie before on the signIn API it works.

**Comment by DanielnetoDotCom** [comment]
yes, if you request from another domain it will not save cookies.

again, cross domain cookies are not allowed.

what do you mean with "I tried to customized the method on saving cookie"?

**Comment by julzxcapz** [comment]
$cookie_options = array(
       'expires' => time() + 60*60*24*30,
       'path' => '/',
       'domain' => $_SERVER['HTTP_HOST'], 
        'secure' => true,
        'httponly' => false, 
        'samesite' => 'None'
 );

setcookie("name", $cookie, $options);

----------------------

I think I made it like this before passing options

**Comment by DanielnetoDotCom** [comment]
you can try to modify it in your files, I do not think it will work, also this code rise errors in some PHP Versions.

if works please let me know, I will modify the main code.

**Comment by julzxcapz** [comment]
ok, I will inform you when I make it work again, thank you

**Comment by DanielnetoDotCom** [comment]
great thanks

**Comment by julzxcapz** [comment]
hello I tried again and it's working

Can we do something like this ?? 
`if (version_compare(phpversion(), '7.2', '>')) {
                $cookie_options = array(
                    'expires' => $expires,
                    'path' => '/',
                    'domain' => $_SERVER['HTTP_HOST'],
                    'secure' => true,
                    'httponly' => false,
                    'samesite' => 'None'
                );

                //_error_log("user::login: set cookies {$cookie}");
                setcookie("rememberme", $rememberme, $cookie_options);
                setcookie("user", $user['user'], $cookie_options);
                setcookie("pass", $user['password'], $cookie_options);
            } else {
                _setcookie("rememberme", $rememberme, $expires);
                _setcookie("user", $user['user'], $expires);
                _setcookie("pass", $user['password'], $expires);
            }`

**Comment by DanielnetoDotCom** [comment]
this is how was before.

so are you saying with this works cross domain?

**Comment by julzxcapz** [comment]
yes, same ajax request and no changes needed for the header on backend/signin api for my case

**Comment by DanielnetoDotCom** [comment]
Check this update, but next time please make a pull request.

**Comment by julzxcapz** [comment]
Sorry not too familiar with pull request, will do that next time, I will pull now your changes wait a sec.

**Comment by DanielnetoDotCom** [comment]
No problem, but it is good to learn

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by julzxcapz** [comment]
**$cookie_options** not used on the update

**Comment by DanielnetoDotCom** [comment]
Sorry you were right. here is another update

**Comment by julzxcapz** [comment]
Working fine now, thank you!
