### ISSUE TITLE
PLay at current Timestamp no longer works

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3753]
?t=53

Time stamps r not working anymore.

https://www.joshwhotv.com/vEmbed/27438?t=53

This starts at the beginning

**Comment by akhilleusuggo** [comment]
Interesting , but does work on normal videos , the one you're linking is vEmbed . The controls are not applied ( as far as I know )

https://www.joshwhotv.com/v/9591?t=50  ( does work )

If you try to share it ( with right click ) , will send you to the main page , not the embed one .

![image](https://user-images.githubusercontent.com/52116577/94967373-9e14b800-0507-11eb-87e9-1a0cbbc8aa09.png)

https://www.joshwhotv.com/video/27438/chris-wallace-hits-back-at-criticism-of-his-debate-moderation?t=230

**Comment by JoshWho** [comment]
They use to be. This is how I embed all my news videos. Now it no longer works.,
