### ISSUE TITLE
I'm looking for information for the video on the home page

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#3754]
hello @DanielnetoDotCom  hello how to activate this feature when the video change
i'm looking i can't find
![image](https://user-images.githubusercontent.com/39193219/94959187-0efca580-04f1-11eb-82f8-a70aec7ce4fc.png)

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/94960572-ceeef000-04fb-11eb-83de-cb4148684d39.png)

On gallery . But you need to select 2 or more video as suggested . To suggest a video , you need to star them on the '' my videos '' section as admin . 

![image](https://user-images.githubusercontent.com/52116577/94960712-0198e880-04fc-11eb-9122-83808f483ebb.png)

**Comment by syldri** [comment]
@akhilleusuggo  Thank you a lot
