### ISSUE TITLE
Login panel

### ISSUE THREAD

**Issue by awistudio** [WWBN/AVideo#3755]
disableNativeSignIn > on 

I changed the setting by mistake

now I do not have a login panel
how to recover login panel in the browser

**Comment by akhilleusuggo** [comment]
Try yoursite.com/user , if is not working then you may have to change it from the database ( manually )

**Comment by awistudio** [comment]
what setting should I change in the base?
I changed in
/var/www/html/AVideo/plugin/CustomizeUser
but it didn't help

**Comment by akhilleusuggo** [comment]
nono , you need to go to your database , and under plugins , find the advanced , disableNativeSignIn , and make it off ( value 0 , false )

**Comment by awistudio** [comment]
data base>plugins

"disableNativeSignUp":true,"disableNativeSignIn":false,"disablePersonalInfo":true,"userCanChangeUsername":true,"signInOnRight":false,

**Comment by akhilleusuggo** [comment]
so ? This should fix your issue , in case you did not missed up anything at 

> what setting should I change in the base?
> I changed in
> /var/www/html/AVideo/plugin/CustomizeUser
> but it didn't help

**Comment by awistudio** [comment]
unfortunately it did not help

CustomizeUser.php
   $obj->disableNativeSignUp = !isset($advancedCustom->disableNativeSignUp) ? false : $advancedCustom->disableNativeSignUp;
        $obj->disableNativeSignIn = !isset($advancedCustom->disableNativeSignIn) ? false : $advancedCustom->disableNativeSignIn;
        $obj->disablePersonalInfo = !isset($advancedCustom->disablePersonalInfo) ? true : $advancedCustom->disablePersonalInfo;

**Comment by awistudio** [comment]
how can i install the default settings?

**Comment by akhilleusuggo** [comment]
`cd /var/www/html/AVideo/plugin/CustomizeUser`
`rm CustomizeUser.php`
`wget https://raw.githubusercontent.com/WWBN/AVideo/master/plugin/CustomizeUser/CustomizeUser.php`
`chown www-data:www-data -R *`

**Comment by awistudio** [comment]
unfortunately still missing
what else can I do?
the website works, but I don't have a login panel

![2020-10-03_00-30-26](https://user-images.githubusercontent.com/60708776/94974764-d15b4500-050f-11eb-914a-b3efd82b5746.jpg)

**Comment by akhilleusuggo** [comment]
can you give your website url ?

**Comment by awistudio** [comment]
online.tvpowiat.pl

**Comment by akhilleusuggo** [comment]
https://online.tvpowiat.pl/user

**Comment by akhilleusuggo** [comment]
What do you see ?

**Comment by awistudio** [comment]
![2020-10-03_00-30-26](https://user-images.githubusercontent.com/60708776/94975758-f0a7a180-0512-11eb-9e8c-710a559ca8f0.jpg)

**Comment by awistudio** [comment]
![2020-10-03_00-59-18](https://user-images.githubusercontent.com/60708776/94975979-b5f23900-0513-11eb-87b9-88be75c7d13a.jpg)

**Comment by akhilleusuggo** [comment]
It's your browser then . To avoid future issue . Open a new browser ( different then the one you're using now ) . And go to https://online.tvpowiat.pl/user

It's your browser issue , most likely cache issues .

It's working for me . 

![image](https://user-images.githubusercontent.com/52116577/94976169-b93df280-051c-11eb-8820-dd772080f832.png)

**Comment by awistudio** [comment]
very strange. I ran it on my phone and it doesn't work.

**Comment by awistudio** [comment]
thank you very much for your help.

I'll check it tomorrow

**Comment by akhilleusuggo** [comment]
purge the cache of your browser and site .
change the browser to avoid doubts .
Testing random things : 

![image](https://user-images.githubusercontent.com/52116577/94976564-0e2e3880-051e-11eb-8735-b6adc05e4c9c.png)

**Comment by awistudio** [comment]
it's very strange,
unfortunately, I still do not have a panel,
I checked on a different browser and on a different computer

**Comment by awistudio** [comment]
![2020-10-03_10-06-34](https://user-images.githubusercontent.com/60708776/94986573-3474c800-0560-11eb-89c1-68095e02f150.jpg)

**Comment by DanielnetoDotCom** [comment]
I just created a tool to help you reset the plugins.

just go to the install folder using the terminal command line and type `php resetPlugins.php`

you will be prompted for more options

1 - Reset all plugins Parameters
2 - Reset CustomizeUser Plugin Parameters only
3 - Reset all plugins (Will also inactivate the plugins)

choose the proper option and press enter

**Comment by awistudio** [comment]
this is a new installation.
won't it spoil your work?

**Comment by DanielnetoDotCom** [comment]
What do you mean?

BTW this will not delete any video or user. It will just reset the plugins parameters

**Comment by awistudio** [comment]
can you do it for me?
because maybe I'll do something wrong again

**Comment by DanielnetoDotCom** [comment]
I already did for you

**Comment by awistudio** [comment]
ok i try it

**Comment by awistudio** [comment]
Daniel, can you do this on my server?

because you've already installed other add-ons
I don't want to spoil it

**Comment by DanielnetoDotCom** [comment]
Did you try to login already?

It is already done

**Comment by awistudio** [comment]
I deleted the cache
still not there
![2020-10-03_12-57-42](https://user-images.githubusercontent.com/60708776/94989883-259a0f80-0578-11eb-8fb7-9ea3e01eb34e.jpg)

**Comment by awistudio** [comment]
I have already checked on several devices - there is no panel

**Comment by DanielnetoDotCom** [comment]
It is working for sure. I am on mobile now.

Try to clear your cookies 

![A4C2B00A-6236-4B59-850A-8C4D28A423FE](https://user-images.githubusercontent.com/18009293/94990075-af81b280-054f-11eb-836d-6b4626f3b95d.png)

**Comment by awistudio** [comment]
I don't know why, but it does
maybe there is a problem in Poland

try to log in

**Comment by awistudio** [comment]
friend checked in another city. there is also a problem

**Comment by DanielnetoDotCom** [comment]
Please clear your cookies

**Comment by awistudio** [comment]
log in, add a new user

for my  - test

unfortunately there is no panel.

I deleted cookie

**Comment by awistudio** [comment]
please log in to my panel.
check the settings.

**Comment by DanielnetoDotCom** [comment]
Sorry but now there is nothing I can do. 

It is working but for some reason you are getting a different page then mine.


I just force to clear your cache folder . Also please clear your cookies again . If the problem persist you may need to contact your server and domain provider or maybe your internet provider . And try to find some cache

**Comment by awistudio** [comment]
is. I have regained access

what was the problem?

**Comment by DanielnetoDotCom** [comment]
Not sure, I just force to delete the cache folder.

**Comment by awistudio** [comment]
Daniel I have suggestions

clear options
disableNativeSignIn

**Comment by awistudio** [comment]
caused many problems

**Comment by DanielnetoDotCom** [comment]
disableNativeSignIn is necessary if you use LDAP or third parties logins

**Comment by awistudio** [comment]
I marked it by mistake - I think with other users it may also happen

**Comment by awistudio** [comment]
disableNativeSign
I will avoid it.
it's a dangerous option :)
Thank you, I can't do it without you.

**Comment by akhilleusuggo** [comment]
Try via VPN , but I'm sure it's a cache issue . Try to PURGE all data . If you believe that the issue is your ISP ( doesn't really make sense ) , then try via VPN
