### ISSUE TITLE
Configuration Updates Don't Save

### ISSUE THREAD

**Issue by NemoNiente** [WWBN/AVideo#3756]
Hi,

I just had a new install of AVideo performed. But whenever I try to save the website configurations, it says it saves but it doesn't. And when I browse away from the page and back to it, the old values remain.

I was told this might be a permission issue on the /var/www/html/AVideo/videos folders and all files in it. But, I don't know what the permissions should be. I've tried to give full permissions to all users, but that doesn't seem to have helped.

Thanks in advance for any help!

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by NemoNiente** [comment]
[avideo.log](https://github.com/WWBN/AVideo/files/5320250/avideo.log)

It says something about the site being offline, and bad credentials. Where would I update those?

**Comment by akhilleusuggo** [comment]
`service mysql restart`
`service apache2 restart`

Try to restart mysql , because looks like your database is not online

**Comment by NemoNiente** [comment]
I restarted those, same issues. The log didn't update though, is there another one I can send? I'm getting this on the console;

DevTools failed to load SourceMap: Could not load content for https://www.mysite.com/videos/cache/js/bootstrap-select.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by NemoNiente** [comment]
[NGINX.txt](https://github.com/WWBN/AVideo/files/5320279/NGINX.txt)
Here is the output from running the NGINX command.

**Comment by akhilleusuggo** [comment]
`ERROR: used credentials: mysqlHost = localhost; mysqlUser = youphptube; mysqlPass = youphptube; mysqlDatabase = AVideoStreamer;`

Make sure you're using the right password and database user on your `/videos/configuration.php`

When you make sure it's right , go to your root directory ; `cd /var/www/html && chown www-data:www-data -R *`

**Comment by NemoNiente** [comment]
Password was correct in the configuration.php file.
I ran that command and it didn't throw any errors, but I'm still getting the same results.
I don't see any new errors in the log files either. Is there a way I can test logging into the database directly?

**Comment by akhilleusuggo** [comment]
what about the database user and the database name ? Following the error logs, something on your database is wrong .

**Comment by NemoNiente** [comment]
They are all what I was given after it was setup. It was working at one point, as the information in there isn't the default data. And the only thing I did was move the videos folder on to a different drive as per; 
https://github.com/WWBN/AVideo/wiki/Can-I-store-my-videos-in-another-location

But that kept throwing an error on the compatibility check, so I moved it back and removed the symbolic link. Helpful?

**Comment by NemoNiente** [comment]
Everything on the site appears to be working. Can setup new users and update them. Can upload, view and delete videos. Just nothing will take for the site configuration.

**Comment by akhilleusuggo** [comment]
If you don't give details , nobody will be able to help you . Not mentioning that your video's directory is not on apache2 default location is crucial !

Go to your new location , run : 

`chown www-data:www-data -R *`
AND
`chmod 777 videos/userPhoto/`    userPhoto need to have read and write permissions ( where ever you have it )

**Comment by NemoNiente** [comment]
I moved it back to the default location to make the site work again, as mentioned above.
I just set the permissions on the userPhoto folder, but the issue persists.

**Comment by akhilleusuggo** [comment]
`cd /var/www/html/AVideo/videos/userPhoto/ && chmod 777 *`

I'm sure it's permission issue 

JUST TO SKIP unnecessary steps , check https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Error will show up , will let you know what is wrong . Find the file , and the line on the log file that is causing the issue

**Comment by NemoNiente** [comment]
I think it is too. I ran that command, no change. The only Console Error I'm getting I posted above. It's here;

DevTools failed to load SourceMap: Could not load content for https://www.caconvocation.com/videos/cache/js/bootstrap-select.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by akhilleusuggo** [comment]
I don't know if you REALLY read ... Please read things above . Your issue is fixed .

https://www.caconvocation.com/user

**Comment by NemoNiente** [comment]
That takes me to my user page... No issue with users.
The issue is with the;
siteConfigurations page
Basic Email won't update. And on the Advanced Configuration Page, none of the SMTP email stuff will save either.

**Comment by NemoNiente** [comment]
FireFox console;
Cookie “84b11d010cced71edffee7aa62c4eda0” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Don't think that is relevant though.

**Comment by akhilleusuggo** [comment]
OMG , I'm on multiple issue and I confused your issue with another one , I wanna apologize .

I'm not asking you to see the console , but the XHR

![image](https://user-images.githubusercontent.com/52116577/94974742-226f3700-0518-11eb-8093-eee3f807c6e9.png)

**Comment by NemoNiente** [comment]
This is configurationUpdate.json.php that shows when I hit save;

{status: "1", respnseLogo: {status: "success", url: "/var/www/html/AVideo/videos/userPhoto/logo.png"},…}
respnseFavicon: {status: "success", url: "/var/www/html/AVideo/videos/favicon.png"}
status: "success"
url: "/var/www/html/AVideo/videos/favicon.png"
respnseLogo: {status: "success", url: "/var/www/html/AVideo/videos/userPhoto/logo.png"}
status: "success"
url: "/var/www/html/AVideo/videos/userPhoto/logo.png"
status: "1"

This is from stats.json.php?Menu;
{error: false, msg: "OFFLINE", nclients: 0, applications: [], hidden_applications: [],…}
applications: []
countLiveStream: 0
disableGif: false
error: false
hidden_applications: []
msg: "OFFLINE"
name: "undefined"
nclients: 0
total: 0

**Comment by NemoNiente** [comment]
![Capture](https://user-images.githubusercontent.com/17752042/94975027-959f8b80-04cd-11eb-83bc-64507975c0d1.PNG)

This is from FireFox, looked more useful. Are these what you are looking for?

**Comment by akhilleusuggo** [comment]
Under network !

**Comment by NemoNiente** [comment]
![Capture](https://user-images.githubusercontent.com/17752042/94975519-32aef400-04cf-11eb-9a7c-eac82a0ec9c0.PNG)

**Comment by akhilleusuggo** [comment]
I mean ,keep it open , while you press save configuration , to see where is stuck ( the error will show on red )

**Comment by NemoNiente** [comment]
![Capture](https://user-images.githubusercontent.com/17752042/94975707-c1237580-04cf-11eb-8976-51059b978de1.PNG)

Sorry, here you go. But it doesn't throw an error. I even get a popup that says Congratulations! Your configurations has been updated!

**Comment by akhilleusuggo** [comment]
`chmod 777 /var/www/html/AVideo/videos/userPhoto/logo.png && chmod 777 /var/www/html/AVideo/videos/favicon.png `

Try this .

**Comment by NemoNiente** [comment]
Executed that. Same issue. /cry
I'm sorry for being a pain.

**Comment by akhilleusuggo** [comment]
I can't believe it .
I've seen this before with permissions and cloudflare . But something with your database is not right , and I don't know what is .
If you're not able to find a solution , you can still change those settings manually from the database .

Your site doesn't looks like is using cloudflare

**Comment by NemoNiente** [comment]
Cleared the cache, still no good. /sad. Not cloudflare.

I've been using all the browsers. Even IE... /shudder

I'm a little timid to edit the database directly, but if you could point me in the right direction to get in and do the edits I'd really appreciate it. Do you have a link or something I can use to work from?
