### ISSUE TITLE
Unable to add a custom thumbnail image to the video

### ISSUE THREAD

**Issue by angelawong** [WWBN/AVideo#3757]
**Describe the question**
I used to be able to add a thumbnail image to the video. For some reason, the latest version no longer allows me to do so. Is there a plugin I need to turn on or something? When I go to Edit > Images and try to browse for an image to add to my video, all my image files (jpg, png) are greyed out which means that I cannot choose them. Am I missing something? Please advise. Thanks so much.

**Comment by DanielnetoDotCom** [comment]
That is new for me, there was no change on this.

try another browser

**Comment by angelawong** [comment]
@DanielnetoDotCom You are right. It worked on another browser. I could not get it to work in Firefox but I could in Chrome. Thank you very much.
