### ISSUE TITLE
Accessing from Local Network

### ISSUE THREAD

**Issue by khoiron81** [WWBN/AVideo#3758]
I have done the the installation in local server with static public IP and domain and everything is working fine. 
Now I would like to access this AVideo from the local network directly to the private IP on the server.
Question:-
Is it possible to access AVideo from local network without an internet connection?

Thanks

**Comment by DanielnetoDotCom** [comment]
Yes it is.

but you will for sure not be able to use SSL

check this https://github.com/WWBN/AVideo/wiki/Change-the-URL-of-your-installation

**Comment by khoiron81** [comment]
Alright, thanks for your quick response. Then just leave it as it's
