### ISSUE TITLE
plugins site facebook-login broken

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3759]
Hey,

I tried to facebook login https://plugins.avideo.com/ site. It doesn't work anymore.

**Comment by DanielnetoDotCom** [comment]
Correct.

Facebook ban me again.

please create an account on https://tutorials.avideo.com/ and use it to login on https://youphp.tube/marketplace/

then let me know BY EMAIL developer@youphptube.com your FB email and the new account #

the account # is below the logoff button.
