### ISSUE TITLE
how can you stop backup process?

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3760]
I accidentally started backup process with "BACKUP ALL" option instead of "BACKUP DATABASE". There was´t enough disk space to backup all the videos so I had to stop my VM (I didn't know any other way to stop the process once started).

After starting the VM, the process is still ON, though it doesn't do copying anymore. Is there a way to reset the process? 

At the moment I can't backup anything, because of the "running" process..

![image](https://user-images.githubusercontent.com/63721378/94990982-e9ff4580-0577-11eb-8272-91a74ab0898c.png)

**Comment by DanielnetoDotCom** [comment]
Not sure, maybe if you reboot

**Comment by akhilleusuggo** [comment]
kill the PID

**Comment by tonuzo** [comment]
Thanks for your help. The process was a "ghost", so I was not able to see it. Plugin reinstall worked for this one.
