### ISSUE TITLE
How can I have the video and sound come on when I hit the play button?

### ISSUE THREAD

**Issue by angelawong** [WWBN/AVideo#3761]
**Describe the question**
I have turned off autoplay and my videos are not playing automatically which is what I want. However, I have noticed that even when I click play, I have to unmute the video. Before upgrading to 9.5, I noticed that when I hit play, both video and sound comes on together. Now, when I click play, the video plays but I have to manually unmute the sound. How do I have the video and sound come on when I click play? Please advise. Thanks so much.

**Comment by pchelferlein** [comment]
Modern Browsers have implemented a media-engagement statistic.
Took me some sessions to get mine trained.

Chrome for example: 
chrome://media-engagement/

check what the rating of your site is. Maybe the browser hasn't learned yet that this is a from you wanted behavior?
