### ISSUE TITLE
Not recording live through streams

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#3764]
Good Afternoon...I have a question about SendRecordToEncoder and Meet. One of our users was using Meet, but they didn't see their video on their profile account. So, I did a test last night and nothing happened. Do you think that I will need to re-install the SendRecordToEncoder plugin? This happens after the migration from one server to the new one.

**Comment by DanielnetoDotCom** [comment]
When you use the Meet and you start a livestream if you have the SendRecordToEncoder  it suppose to be recorded in your videos page.

**Comment by CROSSMediaNet** [comment]
Well, I do have SendRecordToEncoder plugin and it doesn't record at at all

**Comment by DanielnetoDotCom** [comment]
If it does not record when you make a livestream please check the nginx.conf

Does your site installed by me? 

What is your domain?

**Comment by CROSSMediaNet** [comment]
Yes, it was installed by you and the domain is https://impsteams.com
