### ISSUE TITLE
recoverFilesToVideos.php

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3765]
recoverFilesToVideos.php

What it does ?

```
php recoverFilesToVideos.php 
*** Total filenames 36565
*** Total filenames 36565 Will be created
*** Confirm Create Them? y/n: n
```

What 36000 new files will be created ?

**Comment by DanielnetoDotCom** [comment]
It suppose to scan your videos directory and create in your database videos related to what was found on it.

so that means, you have 36565 videos on the videos directory and they were not found on the database. is that correct?

**Comment by akhilleusuggo** [comment]
I'm looking at the code , and maybe because my videos does not have `_YPTuniqid_`

**Comment by DanielnetoDotCom** [comment]
`_YPTuniqid_ ` should not make any difference

**Comment by akhilleusuggo** [comment]
Then the script is not correct .
Because it may taking `_low` `_SD` `_HD` as different videos ...

Because I don't have 36000 videos ... I have around 12k videos .
