### ISSUE TITLE
My site working fine without https but problems with https

### ISSUE THREAD

**Issue by alielastal** [WWBN/AVideo#3766]
I Already Installed the script from the links below. It is works fine with http, and don't stream on https protocol.

[Link 1](https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer) 
[Link 2](https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server)

Can Help?

**Comment by akhilleusuggo** [comment]
What do you mean , ''don't stream on https protocol'' ?
What https are you talking about ? The nginx config ? The main site https ? or the notification is not showing only ?

provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by alielastal** [comment]
I follow the logs, i got this,

RTMP Server (http://aboodtv.space:8080/stat) is NOT responding we will wait less from now on live_servers_id = (0)  SCRIPT_NAME: /AVideo/plugin/Live/stats.json.php

**Comment by alielastal** [comment]
Is this an issue?

**Comment by alielastal** [comment]
In Nginx, I pick this 

client sent invalid host header while reading client request headers, client: 191.232.211.54, server: aboodtv.space, request: "GET /manager/html HTTP/1.1", host: ""

**Comment by akhilleusuggo** [comment]
aboodtv.space it's a empty apache welcome page . ( /manager/html ) . 
Make sure you read carefully the guides on the wiki . Just by doing copy/past , everything works perfectly .

( ubuntu 18.04 ) I can confirm it .

**Comment by alielastal** [comment]
I am using **ubuntu 18.04** and **copy/past** every line
the home page is empty
I install the script as the docs. In AVideo path, and the encoder in AVideo-Encoder path

**Comment by pchelferlein** [comment]
I may be able to provide a hint.
My vfreshly installed page was empty also on https.
I found that some "file_get_contents" have been equipped with an "error Handling" for SSL and some not.

By Adding the already existing fix:

`if (empty($ctx)) {
        $opts = array(
            "ssl" => array(
                "verify_peer" => false,
                "verify_peer_name" => false,
                "allow_self_signed" => true,
            ),
        );
        if (!empty($timeout)) {
            ini_set('default_socket_timeout', $timeout);
            $opts['http'] = array('timeout' => $timeout);
        }
        $context = stream_context_create($opts);
    } else {
        $context = $ctx;
    }` 

in the function call of 
"file_get_contents"
by adding two parameters:
`(THAT_PART_LEFT_UNTOUCHED, false, $context)`

My page instantly came online with no more errors.
I wanted to make a fix suggestion but haven't had the time yet to completely document it yet.
Hopefully that givesyou a hand

**Comment by alielastal** [comment]
Thanks for your time,

But can you till me where the files is?

specially the function **file_get_contents**? where is it ?

**Comment by alielastal** [comment]
Any Help?

**Comment by akhilleusuggo** [comment]
@alielastal My question is , what is the issue ? 

> Is this an issue?

What is not working properly ? I can see that is not working via https , and it's normal if your main site is over https and not your nginx server . Both have to be via https .

Read carefully : 

https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server#10-configure-ssl-certificate-for-the-nginx-config

I wanna quote a line : 

> I'm assuming that you already having a signed certificate

 Now you need to include it on the nginx.conf

**Comment by alielastal** [comment]
I have a signed certificate for the  domain **aboodtv.space**, should I us it in "**nginx.conf**"? and replace the path "**etc/letsencrypt/live/demo.avideo.com/**"

 I want to this with you step by step to solve the problem.

Thank again for your time/

**Comment by akhilleusuggo** [comment]
you should create a certificate for the nginx , not using the same as your main domain name site .
Your nginx server , must have a different domain name , or subdomain , with it's separated ssl sertificate .
On the path , you indicate the new path to your ssl certificate , and add it to the nginx.conf

**Comment by alielastal** [comment]
How to create a certificate for nginx ? Is it in the tutorials ? or in this link
**https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server#10-configure-ssl-certificate-for-the-nginx-config**

**Comment by akhilleusuggo** [comment]
This is something you need to google . Has nothing to do with the project itself . Actually the streaming RTMP-NGINX issues , should be asked on rtmp-nginx project .

You can use cerbot , or manual let's encrypt ( also a project on github )

**Comment by alielastal** [comment]
Thanks a lot, now I but my hand on the issue, There nothing wrong  with my installation. All what I want to google, is to setup SSL for RTMP-NGINX.

Thanks.

**Comment by akhilleusuggo** [comment]
We do have how to implement , all you need is a valid certificate . I don't wanna guide you , because I may break your server in case you install the nginx cerbot . You may have a problem over port 80 .
