### ISSUE TITLE
Seperate chat embed code from player embed

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#3767]
Is there are way to separate the chat embed code from the player embed? 
When a user embeds their account player into their own website the manner in which the chat is included causes problems. In some cases if the the chat is set to use useStaticLayout or inPlayerLayout it covers part of the player. 
Uncheck those layouts and the bubble will block the mute button when using positionOnLeft. And the it also messes with the footer where you can't click anything.

**Comment by DanielnetoDotCom** [comment]
Hi, 

are you talking about Live content or VOD content?

**Comment by ganddser** [comment]
Live content see this site for example, [https://www.sxmflavorradio.com/live-stream](url)

**Comment by DanielnetoDotCom** [comment]
Hi

can you please make sure you are running Chat version 3.4?

I tried to reproduce it here and it does not appear for me on embeds.
