### ISSUE TITLE
Remove creator and site information displayed at the top of my embedded videos

### ISSUE THREAD

**Issue by angelawong** [WWBN/AVideo#3769]
**Describe the question**
Is there a way I could remove creator (photo and name) and site information displayed at the top of an embedded video? Before I upgraded to 9.5, that information did not show up in any of my embedded videos. Is there a way I could turn this off in 9.5? Please advise. Thanks so much

**Comment by DanielnetoDotCom** [comment]
can you please screenshot what are talking about?

**Comment by angelawong** [comment]
@DanielnetoDotCom Please see attached. I don't want my photo or text showing up at the top on an embedded video (indicated by the red box)
![video1](https://user-images.githubusercontent.com/1007028/95096777-b4cf3080-06fa-11eb-98af-724b2a616fdb.png)

**Comment by DanielnetoDotCom** [comment]
try check this 
![image](https://user-images.githubusercontent.com/18009293/95100688-c2d77e00-0707-11eb-95ec-3c3b1dcb3dc2.png)

**Comment by angelawong** [comment]
@DanielnetoDotCom you are awesome! Thank you so much! That did the trick! Cheers! :-)
