### ISSUE TITLE
monetize users-not working,credit not happening in encoder wallet

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3772]
Good Day,

I have set up monetize users for video views however the user wallet is not getting credited with the amount defined in the plug in.

video log files are ok and no errors

Please advise

Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
can you please reproduce it on demo site?

**Comment by vraghavans** [comment]
Hi daniel,

Demo site seems to be down.

Also please advise ,how do i create the scenario? should i activate the monetize user pluginand upload video for an user and then login as another user and check?
Please advise
Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
The demo is working 

But that is the problem I have to be able to reproduce the exact same scenario you have to confirm the problem.

To start you can update your files to make sure we are on the same page

**Comment by vraghavans** [comment]
Hi Daniel,

http://demo.avideo.com/ -this link is not opening for me.
Am i using the wrong demosite?
Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
The one you provided works for me 

But try the https directly https://demo.avideo.com/

**Comment by vraghavans** [comment]
Hi Daniel,
Yes https works
And yes this feature works in demo but not working on my site. and my YPT wallet config page is different from demo site
manualAddFundsTransferFromUserId is a check box in demo site but in my site we can put number(user IDs)

![image](https://user-images.githubusercontent.com/65802024/95384765-b53e1600-090a-11eb-8d86-67fd067d9ba2.png)

![image](https://user-images.githubusercontent.com/65802024/95384833-cb4bd680-090a-11eb-9e4b-7b383a584279.png)


Please advise
Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/95385797-d67c1380-08c4-11eb-98e5-3446dddb8930.png)

Then you can copy the demo configurations if you want.

**Comment by vraghavans** [comment]
Hi,Daniel,

I copied the code,did git pull still not working.What else i can check please

Rgds
Vijay

**Comment by vraghavans** [comment]
Dear Daniel,
okies i see this line,so it means as admin,i should have funds in my wallet 1st to give is it?
![image](https://user-images.githubusercontent.com/65802024/95409118-9d808500-093e-11eb-9765-fb2ab5d816d2.png)
pls advise
rgds
Vijay

**Comment by vraghavans** [comment]
okies that was the error,the admin login didnt have funds,hence was not getting transferred.Now working after i added funds into admin account
