### ISSUE TITLE
update system

### ISSUE THREAD

**Issue by daoguey** [WWBN/AVideo#3775]
This is the second time my website breaks because i update with Git pull.
Error 500 of HTTP setup with Apache2 and php7.3-fpm
![image](https://user-images.githubusercontent.com/15695109/95133342-6895e780-071e-11eb-9dd3-f1da3b5c804e.png)

can you guys tell me I also have a error with cache i wonder if this is related
![image](https://user-images.githubusercontent.com/15695109/95133494-a4c94800-071e-11eb-9c2c-2dbf3183551c.png)

**Comment by daoguey** [comment]
Commenting those lines made my website again work, but if i am logged in i still get error 500
![image](https://user-images.githubusercontent.com/15695109/95134163-9def0500-071f-11eb-9169-48a6c42c214a.png)
This change was made inside .htaccess file as i found out that php_value cannot have those mods inside of this file according to: https://www.a2hosting.com/kb/developer-corner/php/500-internal-server-error-while-running-php#:~:text=ERROR%20500%20below!-,HTTP%20Error%20500%20Resolution,and%20directories%20are%20set%20incorrectly.&text=htaccess%20file.

if i am not logged in all videos work fine. Kind of odd.

**Comment by akhilleusuggo** [comment]
Yes , I was about to write it too you .
We were talking about this before , since has been added without a warning , and it shocked me with the uploads errors .

**Comment by daoguey** [comment]
I am able to have my users come and check my website now after i made those changes but now inside my session as admin i get error 500 but in AJAX it shows error 404.

thank you for letting me know

**Comment by daoguey** [comment]
i see the last 4hrs an update was made. did we resolve this? or is there still something broken?

**Comment by DanielnetoDotCom** [comment]
Hi

I am not aware about those errors as long as I cannot reproduce . And I cannot fix something that is not happening with me .

I do not use PHP fpm for myself , so I guess this error is related to it.


If you can make a working solution and make a git pull we can add it in the main branch and you can keep following the updates

**Comment by DanielnetoDotCom** [comment]
Maybe this works

https://stackoverflow.com/a/51535081

**Comment by daoguey** [comment]
will be checking now. thank you.

**Comment by daoguey** [comment]
I just discovered in my logs and AJAX and chrome F12 developer, that the website is looking for the cache option that is not found. I cleared the cache and everything and under a user logged in it will error out. removed cached folder and i am reloading plugins for cache.

**Comment by daoguey** [comment]
@DanielnetoDotCom that broke also my website. So i commented out php in .htaccess file.

**Comment by daoguey** [comment]
This seems to be affecting admins only for some reason. The rest of the users accounts work fine.

**Comment by daoguey** [comment]
ok, my previous issue is now solved from the php_values in .htaccess are now corrected.

I followed this tutorial to build my websites but i found out that using CGI and FMP did indeed break my website
tutorial: https://www.linuxbabe.com/debian/install-lamp-stack-debian-10-buster

After i disabled also the mods: Sudo a2dismod proxy_fcgi setenvif, my website now works with the lines of code in .htaccess

Now it has to do with the cache plugin giving me grief but will open a new Ticket on this one.
