### ISSUE TITLE
Always Hide YouTube sidebar menu

### ISSUE THREAD

**Issue by p5web** [WWBN/AVideo#3776]
Hello:

On some screens sizes, the YouTube menu is open covering the other page elements.  Looking for a way to have the YouTube sidebar menu always hidden on page load, regardless if it was open on the previous page.  How would I go about having that sidebar menu always hidden on page load?

Thank you.

--John

**Comment by DanielnetoDotCom** [comment]
YouTube layout is deprecated, you should use the Gallery instead

![image](https://user-images.githubusercontent.com/18009293/95197294-c1619080-07af-11eb-827c-4e7731ce8bce.png)

**Comment by p5web** [comment]
Thanks for the tip - for whatever reason, the "Depreciated" tag is not showing in my plugin page - must need to update to the latest version.

Blessings.

--John

**Comment by DanielnetoDotCom** [comment]
I guess you need to update your site.

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform
