### ISSUE TITLE
Fatal error: require_once(): Failed opening required '../videos/configuration.php'

### ISSUE THREAD

**Issue by vikramuvs** [WWBN/AVideo#3777]
Hello Team,

I tried installing the application as per the instructions provided in your wiki, but am facing issues with respect to the installation of the application from the configuration window which appears when we first open the application webpage. I have provided proper information as well but the application throws an unknown error. I have atteched the error log of my apache2 server. Please have a look at it and suggest any solutions if you can. 

Thank You

```
[Tue Oct 06 11:08:35.332549 2020] [php7:notice] [pid 2234] [client 172.1.2.35:51908] PHP Notice:  Undefined variable: global in /var/www/html/AVideo/install/index.php on line 29
[Tue Oct 06 11:08:35.332595 2020] [php7:notice] [pid 2234] [client 172.1.2.35:51908] PHP Notice:  Trying to access array offset on value of type null in /var/www/html/AVideo/install/index.php on line 29
[Tue Oct 06 11:08:35.477014 2020] [php7:warn] [pid 2234] [client 172.1.2.35:51908] PHP Warning:  require_once(../videos/configuration.php): failed to open stream: No such file or directory in /var/www/html/AVideo/view/error.php on line 4, referer: http://172.1.2.45/AVideo/install/index.php
[Tue Oct 06 11:08:35.477047 2020] [php7:error] [pid 2234] [client 172.1.2.35:51908] PHP Fatal error:  require_once(): Failed opening required '../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/html/AVideo/view/error.php on line 4, referer: http://172.1.2.45/AVideo/install/index.php
```

**Comment by akhilleusuggo** [comment]
What distro ? What php version ?

**Comment by vikramuvs** [comment]
Distro: Ubuntu Server 20.04 FF 
PHP Version: 7.4.3

**Comment by akhilleusuggo** [comment]
What I can see on the logs , is that your config file was not created . 
Make sure you have rewrite module enabled , and proper permissions .

**Comment by vikramuvs** [comment]
I enabled the rewrite module by running 'sudo a2enmod rewrite' command and restarted the apache2 server, while installing itself since it was mentioned in the guide to install. I enabled write permissions by making www-data as the owner of the Videos file  which you can see in the ouput of ls-la command below  
`
drwxr-xr-x  8 www-data www-data  4096 Oct  5 18:03 .git
drwxr-xr-x  3 www-data www-data  4096 Oct  5 18:03 .github
-rw-r--r--  1 www-data www-data  1570 Oct  5 18:03 .gitignore
-rw-r--r--  1 www-data www-data 15578 Oct  5 18:03 .htaccess
-rw-r--r--  1 www-data www-data    23 Oct  5 18:03 CNAME
-rw-r--r--  1 www-data www-data  1144 Oct  5 18:03 LICENSE
-rw-r--r--  1 www-data www-data 11722 Oct  5 18:03 README.md
drwxr-xr-x  3 www-data www-data  4096 Oct  5 18:03 admin
-rw-r--r--  1 www-data www-data   414 Oct  5 18:03 composer.json
drwxr-xr-x  2 www-data www-data  4096 Oct  5 18:03 feed
-rw-r--r--  1 www-data www-data   452 Oct  5 18:03 git.json.php
drwxr-xr-x  9 www-data www-data  4096 Oct  5 18:03 google
-rw-r--r--  1 www-data www-data  3939 Oct  5 18:03 index.php
drwxr-xr-x  2 www-data www-data  4096 Oct  6 11:50 install
drwxr-xr-x  2 www-data www-data  4096 Oct  5 18:03 locale
drwxr-xr-x  8 www-data www-data  4096 Oct  5 18:03 objects
drwxr-xr-x 64 www-data www-data  4096 Oct  5 18:03 plugin
-rw-r--r--  1 www-data www-data    43 Oct  5 18:03 rtmp.code-workspace
-rw-r--r--  1 www-data www-data 33153 Oct  5 18:03 sitemap.xml
drwxr-xr-x  2 www-data www-data  4096 Oct  5 18:03 updatedb
drwxr-xr-x  2 www-data www-data  4096 Oct  5 18:30 videos
drwxr-xr-x  9 www-data www-data  4096 Oct  5 18:03 view
-rw-r--r--  1 www-data www-data   911 Oct  5 18:03 web.config`

**Comment by akhilleusuggo** [comment]
What about this : 

![image](https://user-images.githubusercontent.com/52116577/95465606-09391100-0984-11eb-8aae-6748f267535a.png)

**Comment by akhilleusuggo** [comment]
and also , if the issue persists , go to .htaccess and comment the php values at the bottom .

**Comment by vikramuvs** [comment]
I commented the php values at the bottom of the .htaccess file of AVideo folder and tried installing the application again, to which the application again threw an error saying "Sorry, unknown error occured". But the application is accesible now when i hit the application page in the browser. But when i see the error logs of apache it still says it cannot find the /videos/configuration.php file. Please have a look at the error log (I have replaced the values with ***** for anonymity purposes in the installation json line)

````
[Fri Oct 09 11:53:53.079979 2020] [php7:notice] [pid 16087] [client 172.1.2.35:59352] PHP Notice:  Undefined index: bodyClass in /var/www/html/AVideo/install/index.php on line 29
[Fri Oct 09 11:53:54.279988 2020] [php7:warn] [pid 16087] [client 172.1.2.35:59352] PHP Warning:  require_once(../videos/configuration.php): failed to open stream: No such file or directory in /var/www/html/AVideo/view/error.php on line 4, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:53:54.280026 2020] [php7:error] [pid 16087] [client 172.1.2.35:59352] PHP Fatal error:  require_once(): Failed opening required '../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/html/AVideo/view/error.php on line 4, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.310279 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 9 {"webSiteRootURL":"http:\\/\\/***********\\/AVideo\\/","systemRootPath":"\\/var\\/www\\/html\\/AVideo\\/","webSiteTitle":"**********","databaseHost":"localhost","databasePort":"3306","databaseUser":"*****","databasePass":"********","databaseName":"aVideo","mainLanguage":"us","systemAdminPass":"********","contactEmail":"***********","createTables":"2"}, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.310344 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 20, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.311036 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 33, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.314236 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 45, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.314265 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 55, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.314276 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 57, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.314307 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 66, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.315068 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 74, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.573701 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 96, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.573717 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 99, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.579228 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 109, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.579881 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 117, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.580175 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 125, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.580671 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 133, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.582092 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 141, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.582772 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 151, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.583256 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 160, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.583291 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 212, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.583373 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 216, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.583377 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 227, referer: http://172.1.2.45/AVideo/install/index.php
[Fri Oct 09 11:54:52.583389 2020] [php7:notice] [pid 16091] [client 106.51.8.242:59360] Installation: 231, referer: http://172.1.2.45/AVideo/install/index.php
````
Kindly have a look at the logs and tell me whether the installation was succesfull or not. I am able to access the application both on the intranet as well as internet, but i dont want the application to be installed half baked (which will create more problems than it is trying to solve).

**Comment by vikramuvs** [comment]
After working with the application for 3 days, I do not find any issues in its working. Thank You @akhilleusuggo for your kind help.

**Comment by akhilleusuggo** [comment]
@vikramuvs So how did you fixed it ? Would be great to leave a feedback just in case this issue persist , or at the least could be added in the code .

Was it the rewrite module ?

**Comment by vikramuvs** [comment]
Your above suggestion to comment/remove the php directives of the .htaccess file worked! It seemed the application had 'presumed' that the php.ini values of max_post_size and max_upload_size were taken to be above the requirement, while that was not the case. This 'refresh' happened because i chose to comment out the last lines of php directives in .htaccess file, which forced the application to check for those values again, leading to the red cross signs in front of max_post_size and max_upload_size on the left hand side of the installation screen, which i then suitably changed. But again as i mentioned, the application threw an error saying unknown error occurred. But when i hit the page of the application again, i was greeted with the login screen(which was why i had posted earlier). But nonetheless, the famous saying 'Dont fix it if it ain't broken' goes well in my case and i chose to follow it, since the application allowed me to login and upload videos. It wasn't the rewrite module, as i had mentioned earlier i had already installed it. The issue was with the application presuming the php.ini values to be above the requirement. Thank you once again. I shall now proceed to installing the encoder on to the server.

**Comment by akhilleusuggo** [comment]
Thank you for the feed back !

**Comment by vikramuvs** [comment]
I had one more query: I have a setup of a server which the users of the intranet can access it with the local ip. This server is exposed to the public as well, who will view the videos. The videos will be uploaded by the intranet. What should be the url in the case of encoder as well as the streamer sites?

**Comment by vikramuvs** [comment]
@akhilleusuggo kindly suggest
