### ISSUE TITLE
Change the affiliate link of the logo

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#3778]
I want to change the link of the logo, but where can I change the drawing. Thanks

![td](https://user-images.githubusercontent.com/50126312/95168900-35b22900-07dc-11eb-8331-79d8321afc5c.png)

**Comment by p5web** [comment]
Hello: The logo image itself can be changed from the Site Configurations menu and the link that is associated with the logo can be changed from the Customized Advanced plugin.  Remember to log in as an admin.

**Comment by XemTube-TV** [comment]
Tks !
