### ISSUE TITLE
search function and livesearch plugin are not working.

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#3779]
search function and livesearch plugin are not working.

![image](https://user-images.githubusercontent.com/50126312/95203572-23041800-080d-11eb-95ff-2fb3ae7ae139.png)

**Comment by akhilleusuggo** [comment]
They work fine , maybe you're outdated .
Make sure to git pull , and update the plugin .

**Comment by DanielnetoDotCom** [comment]
Clearly @XemTube-TV is missing VideoTags plugin table installation 

![image](https://user-images.githubusercontent.com/18009293/95259962-57bca300-07fe-11eb-9e02-fe6d01b6c2a9.png)
