### ISSUE TITLE
Videos watched by specific user functionality

### ISSUE THREAD

**Issue by tuchiii** [WWBN/AVideo#3780]
Hello, 
I understand that the question is maybe strange considering the main goal of the platform. However with current COVID-19 situation we needed to find a platform for educational purposes for relatively small group of users. So far AVideo is seeming to be great platform and providing needed functionality. However I'm having difficulties to find a way to see which users watched, liked and or commented which videos. It would greatly help the tutor to monitor the progress of the students. Is there embedded functionality for that or maybe plugin from the market place?

And one unrelated question: On the github page https://github.com/WWBN/AVideo the latest release is stated as 8.9.1, but if I check from the platform for update it states that the latest is 9.5. Why is there such a difference. And is there a place where I can find the differences and changes between versions i.e. 8.9 to 9.5. is there any braking changes, different requirements in terms of software versions or is it safe to update.

Thank you in advance

**Comment by akhilleusuggo** [comment]
There are huge changes between 8.9 and 9.5 yes
You can not really monitor what they watch , but you can check the logs of the user on the plugin ( Audit ) . Is the easiest way to check , when they logged in , and what video they watched .

**Comment by tuchiii** [comment]
Thank you for your answer. It would be difficult to be online at the same time as all of the students in order to be able to monitor the progress.


Could you direct me to a source where I can read more about the changes between 8.9 and 9.5?

Thank you in advance

**Comment by akhilleusuggo** [comment]
> Could you direct me to a source where I can read more about the changes between 8.9 and 9.5?

There is really no table for such thing .

> It would be difficult to be online at the same time as all of the students in order to be able to monitor the progress.

Audit does store all the activities on the database . After you enable it , click check logs , and you will be able to see all the activities . All of them will be stored , until you decide to drop the database table .

**Comment by tuchiii** [comment]
OK, I understood.

It's a shame that such great project suffers from lack of documentation.

Thank you
