### ISSUE TITLE
Great Day:

### ISSUE THREAD

**Issue by ha2tim** [WWBN/AVideo#3781]
**Describe the question**
A clear and concise description of what is your question.
I am having several problems with my site.
1. I or anyone that I have given permission to stream can not stream. everytime we push the stream button "server not found" I went in to "edit live server" and tried to enter info but I could not find a "get remote file url"
2. My group is also having problems using the meet function, when we send out the link the person that receives it is asked for a domain & passcode. we sign in and it don't work.
3. do you have a place where I can learn how to use the ad functions or a place where i and my tribe can learn and master the use of the site?
My site is https://gnj.media/
**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
This is duplicated, maybe triplicated, lets focus in one topic only
