### ISSUE TITLE
Using Avideo to stream through and restream to all my social media platforms

### ISSUE THREAD

**Issue by ha2tim** [WWBN/AVideo#3783]
**Describe the question**
A clear and concise description of what is your question.
I am currently using the product and my goal is to be able to stream all my media through my avideo platform https://gnj.media
I also would like to be able to stream my personal commercials before each video on the platform. currently I am having problems streaming out of the platform, but I can send streams through it from restream.io. My goal is to reverse that situation i want to stream to my AVideo platform, and restream it through restream.io.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
You can do that

make sure you follow the instructions here

https://github.com/WWBN/AVideo/wiki/Restream
