### ISSUE TITLE
problems with emailing users & meeting service

### ISSUE THREAD

**Issue by ha2tim** [WWBN/AVideo#3784]
**Describe the question**
A clear and concise description of what is your question.
I am having a problem sending out messages to my users on our Avideo platform, just need to know what steps I have to complete to make this possible. Also their is also no verification email being sent out, and I believe that if I solve one of these problems both will be resolved
Most importantly I am having problems using the meeting app provided on the service. As me and my tribe experiment with it, we are finding it almost impossible to get on it. when we send the link people can't get on because it request "user@domain.net" & "user password" even when we opt not to put a code on it. when we enter our loggin info for the site it just says connecting.
can you help me
**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
> I am having a problem sending out messages to my users on our Avideo platform, just need to know what steps I have to complete to make this possible. Also their is also no verification email being sent out, and I believe that if I solve one of these problems both will be resolved

Please check this
https://tutorials.avideo.com/video/82/setup-gmail-smtp-with-2fa

> Most importantly I am having problems using the meeting app provided on the service. As me and my tribe experiment with it, we are finding it almost impossible to get on it. when we send the link people can't get on because it request "[user@domain.net](mailto:user@domain.net)" & "user password" even when we opt not to put a code on it. when we enter our loggin info for the site it just says connecting.

We recently release an update so the meets are public by default.

if your meet is not public you can change it here 

![image](https://user-images.githubusercontent.com/18009293/95258533-51c5c280-07fc-11eb-90ea-0160d21fe834.png)
