### ISSUE TITLE
Unable to connect as a live streamer, plugin disabled

### ISSUE THREAD

**Issue by s7ntax** [WWBN/AVideo#3785]
I have installed AVideo version 9.5 and AVideo encoder on centos 7. I followed this guide https://www.linuxbabe.com/centos/install-avideo-youphptube-centos-8-server although as it is for centos 8 I worked around it. I could not find anything on here for centos 7 install.

I've also setup nginx following this guide, also not for centos 7 but I managed to work around it. https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

I try to connect as a live streamer using AVideo Platform iOS app and i get an error - "We got an error: plugin disabled"

When I go to plugins, (Live) plugin is enabled, when i go to [Edit Live Servers] it says at the top in red "Live Servers is Disabled, if you want to use it, enable it on the (Live) Plugin "

I did have an issue when installing AVideo encoder, it would not see ffmpeg so i figured i would just continue and fix it later if it caused an issue, I suspect it is.

Any good guides for centos 7 that i could follow and try to resolve the issue? Any ideas whats wrong?

**Comment by DanielnetoDotCom** [comment]
Sorry I do not support Centos Installation. I strongly recommend Ubuntu

**Comment by s7ntax** [comment]
OK  I am going to get another VPS running Ubuntu, any particular version you recommend for running AVideo, that is all that this server will be used for.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 18.04

**Comment by wakozuka** [comment]
i get same error as this, plugiin enable but says disabled

**Comment by akhilleusuggo** [comment]
you're following foreign outdated guides.

**Comment by wakozuka** [comment]
> 

do you have the link for the latest guide

**Comment by akhilleusuggo** [comment]
Check the wiki:

**Ubuntu 20.0X** => https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x-for-AVideo-Platform-version-11.x-or-newer
**Ubuntu 18.0X** => https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer

**Comment by wakozuka** [comment]
thanks man

**Comment by sirdaddits** [comment]
hello
I have same problem on debian 11
Live Servers is Disabled, if you want to use it, enable it on the (Live) Plugin
