### ISSUE TITLE
l10n - unable to translate javascript strings

### ISSUE THREAD

**Issue by Joelp** [WWBN/AVideo#3787]
I cannot translate strings that are in javascript. It will be nice to have a way to be able to localize it too.

like this:
![obrazek](https://user-images.githubusercontent.com/19979522/95292751-617fee00-0872-11eb-8e01-a3d41b2fcd39.png)

**Comment by Joelp** [comment]
Is any chance to have solution for this in the future?

**Comment by DanielnetoDotCom** [comment]
Hi, I just release an update that allows you to add translations on the PlayerSkins plugin

For example, I add the BR translation https://github.com/WWBN/AVideo/tree/master/plugin/PlayerSkins/allowAutoplay/locale/br

**Comment by Joelp** [comment]
Still cannot translate header and buttons:
![obrazek](https://user-images.githubusercontent.com/19979522/102345471-bdb36c80-3f9d-11eb-8e22-fc7d22732be6.png)
