### ISSUE TITLE
Linkify timestamps in description and comments 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3789]
This is one of the most powerful features of YouTube . Could you implement it here?

**Comment by DanielnetoDotCom** [comment]
Can you please details what you mean with some screens shots?

**Comment by fakeologist** [comment]
https://fakeotube.com/v/906

**Comment by akhilleusuggo** [comment]
deleted or private video

**Comment by fakeologist** [comment]
please try now.

**Comment by DanielnetoDotCom** [comment]
Ho, I see, this is an awesome feature, but for right now we have no way to do it.

but it was a live content?

does it also works for vod content?

**Comment by fakeologist** [comment]
Not for live.
For final videos.

**Comment by fakeologist** [comment]
Daniel can you fix up the android app so you can click links and copy text from the description?  It also needs time and rewind features in player.
