### ISSUE TITLE
A problem with Live Stream when converting an IP to a domain with an SSL certificate

### ISSUE THREAD

**Issue by abed-ahmed** [WWBN/AVideo#3790]
I want to solve the Live Stream problem
Live Stream works properly and without a problem on the server IP
As you can see in the attached picture
![11](https://user-images.githubusercontent.com/72515889/95383291-9da76300-08f3-11eb-9ec5-8f09652092ef.jpg)
But when I convert the server IP to a domain with an SSL certificate, Live Stream does not work
As you can see in the attached picture, it shows off line
I want to define the problem and thank you
![222](https://user-images.githubusercontent.com/72515889/95383366-bdd72200-08f3-11eb-877f-6db3f1b5da9b.jpg)

**Comment by DanielnetoDotCom** [comment]
if your streamer is HTTPS, your nginx MUST be https too

**Comment by abed-ahmed** [comment]
How I can make Nginx HTTPS?

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server#10-configure-ssl-certificate-for-the-nginx-config

**Comment by abed-ahmed** [comment]
you make the link that you sent and the problem is not resolved?

**Comment by akhilleusuggo** [comment]
I don't understand , what do you mean ?
