### ISSUE TITLE
Facebook Login on Plugin purchase failing

### ISSUE THREAD

**Issue by JSY-Ben** [WWBN/AVideo#3791]
Hi there :)

I have purchased a number of plugins from the Plugins page. I used my Facebook account to login to purchase them. However, trying to download them again as there are updates, and Facebook login is failing, saying it is in development mode. Any ideas?

Many thanks,
Ben

<img width="533" alt="Screenshot 2020-10-07 at 22 53 04" src="https://user-images.githubusercontent.com/13555701/95391960-df360f00-08ef-11eb-8cbe-3566de8ee7c1.png">

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/issues/3717

**Comment by akhilleusuggo** [comment]
> DanielnetoDotCom commented 11 days ago
> I can see now, I am blocked from Facebook again. (third time)
> 
> Can you please create an account on the https://tutorials.avideo.com/ and use it to login?
> 
> than please send me you facebook email and your new account # and I will transfer your purchases to it.

**Comment by JSY-Ben** [comment]
Many thanks for that :) Ill send my details to Daniel
