### ISSUE TITLE
How to stop a specific user from streaming

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3792]
I would like to stop a specific user from streaming. This is what I have done

1. I have removed the ability to stream from the user account. However he can still stream.
2. I have made user inactive. However on stat page, I can see stream still coming to the server
3. I open the SSH and I can see that inside the HLS folder, the stream is still being processed by the server.

How do I completely stop the stream from reaching the server WITHOUT resetting the stream key?

@DanielnetoDotCom @akhilleusuggo please assist. 

Thank you

EDIT: I have reset the stream key but it is STILL publishing via the old stream key to the HLS folder. There is no way to shut down a user's stream??

**Comment by akhilleusuggo** [comment]
If you have set up your stream correctly ( control.json.php ) , you should be able to drop any stream . You just have to log as admin , and drop it .

Something like this : 

![image](https://user-images.githubusercontent.com/52116577/95402563-b8d89980-0918-11eb-9978-cc6d1a32f2e5.png)

As you can see , you have options as admin .

**Comment by jengajenga** [comment]
> If you have set up your stream correctly ( control.json.php ) , you should be able to drop any stream . You just have to log as admin , and drop it .
> 
> Something like this :
> 
> ![image](https://user-images.githubusercontent.com/52116577/95402563-b8d89980-0918-11eb-9978-cc6d1a32f2e5.png)
> 
> As you can see , you have options as admin .

Thank you. 

Is this a new feature in 9.5? Because I have 9.2.

**Comment by jengajenga** [comment]
> If you have set up your stream correctly ( control.json.php ) , you should be able to drop any stream . You just have to log as admin , and drop it .
> 
> Something like this :
> 
> ![image](https://user-images.githubusercontent.com/52116577/95402563-b8d89980-0918-11eb-9978-cc6d1a32f2e5.png)
> 
> As you can see , you have options as admin .

Also, if I disconnect his stream, will he be able to stream again or do I have to give him permission again?

**Comment by akhilleusuggo** [comment]
I thing you don't have the plugin . 
![image](https://user-images.githubusercontent.com/52116577/95466080-9ed4a080-0984-11eb-9218-d8bf4b184217.png)

**Comment by jengajenga** [comment]
> I thing you don't have the plugin .
> ![image](https://user-images.githubusercontent.com/52116577/95466080-9ed4a080-0984-11eb-9218-d8bf4b184217.png)

Thank you pal. I'll make sure I get it.
