### ISSUE TITLE
transfer funds-from user to admin -not working

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#3794]
Good Day,

trying to transfer funds from one user to Admin for promoting videos but throwing error

![image](https://user-images.githubusercontent.com/65802024/95414815-67e29880-094c-11eb-95a2-87a60a2ef747.png)

Checked the log and this is what it says

![image](https://user-images.githubusercontent.com/65802024/95414842-7630b480-094c-11eb-8a1e-915f7985a99d.png)

Please advise
Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
can you reproduce it on demo site?

**Comment by vraghavans** [comment]
Dear Daniel,

Yes reproduced in demo website and same error
![image](https://user-images.githubusercontent.com/65802024/95516402-ceaf9280-09dc-11eb-935e-1936b9c6e2bb.png)

Kindly advise
Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
Please try this.

the user must appear for selection when you start to type

**Comment by vraghavans** [comment]
Dear Daniel,

Yes correct.It happened and fixed.

thanks!!

Rgds
Vijay
