### ISSUE TITLE
Can't set video free anymore

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3795]
Hi

There is problem when trying to set video free (Public media). 

I had a video assigned into a user group. When I changed it to a public media, it doesn't change to public. 

It shows free on My Videos page, but it's not.

When you try to watch the video, you are redirected to "subscribe or ppv" page (as it was not free to watch)

I cleared cache(s). Same thing.

**Comment by DanielnetoDotCom** [comment]
but the videos were really removed from groups?

check your logs for clues
