### ISSUE TITLE
CustomizeUser (CustomizeUser)

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3797]
The plugin does not save the settings .
Tested on demo , same issue .

**Comment by DanielnetoDotCom** [comment]
can you please check again?

**Comment by akhilleusuggo** [comment]
Tested again on demo site , and still not working .
For example , try to enable this feature . 

![image](https://user-images.githubusercontent.com/52116577/95867954-64974480-0d72-11eb-88db-ce4cdf3c3b7a.png)
