### ISSUE TITLE
Add Song to Playlist issue

### ISSUE THREAD

**Issue by pchelferlein** [WWBN/AVideo#3798]
This may be a bug and I am not sure if I am correct with my suggested fix.

**Describe the bug**
Adding a song to a Playlist results in all switches getting activated although the database only receives one entry.

**To Reproduce**
1. Go to video
2. Click on add to
3. Trigger a switch

**Expected behavior**
Only the thrown switch gets green

I was able to track the error down to the footer.php in the playlist plugin folder in the footer.php

I suggest to change line 119

From:
`$(".playLists_is" + videos_id).prop("checked", isChecked);`

To:
`$(".playLists_id" + videos_id).prop("checked", isChecked);`

Reason:
The data array earlier has the following information:
`            method: 'POST',
            data: {
                'videos_id': videos_id,
                'add': isChecked,
                'playlists_id': playlists_id
            },`

If I am correct the posted value should match the expected data.
If I am wrong please feel free to delete the Issue 

Cheers

**Comment by DanielnetoDotCom** [comment]
Not sure what you mean, do you mean the MP3 player auto switch the autoplay button?

**Comment by pchelferlein** [comment]
If you have several "programs/playlists" and you add the video to one all of the playlist/program switches enable at the same time although only one playlist receives the entry in the database as added.
I am sure that was not intended to happen so I tried to get it fixed.
Try add a video to a self made playlist if you have more than one and all the seitches flip to the added position. If you want I will setup a clone of my page with a fresh install so you can test it for yourself.
Cheers

**Comment by DanielnetoDotCom** [comment]
I remember this issue fixed a couple of weeks ago. are you up to date?

**Comment by pchelferlein** [comment]
I can Confirm that this Bug has been fixxed in the latest download
 https://github.com/issues/3832
The fix is 13 days old my report 20. you can consider this one as closed

Please feel free to contact me if you want Access to my test site for an extended playground on a default webserver to eliminate Deprecated Warning/Error Messages
