### ISSUE TITLE
iPad RTMP streaming app recommendation

### ISSUE THREAD

**Issue by gseiki** [WWBN/AVideo#3799]
Does anyone have a good app recommendation for RTMP streaming from iPad to YouPHPTube server? I want to stream live video from an iPad.  I used to use NabiLive, which worked great.  However, I updated the app, which is now called RTMP Live, and now I can't get my streams to work.  I've quadruple checked that  the Server Url and Stream Name are correct, but still no luck.   On my iPhone, I still have the old version of the app, NabiLive.  I can still stream to my YouPHPTube server from my iPhone, just not from my iPad with the new version of the app.

**Comment by JoshWho** [comment]
There are several apps that already work with rtmp. Try Streamlabs. It works great
