### ISSUE TITLE
Why is adaptive not working

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3800]
These are my settings. Have I done something wrong?

![LIVE_1](https://user-images.githubusercontent.com/65451390/95514432-9439fb80-09c4-11eb-9dee-7e9f8746b032.png)

next..

![LIVE_3](https://user-images.githubusercontent.com/65451390/95514466-a451db00-09c4-11eb-9d6b-229232b6b7e3.png)

I get the error that there is corruption or some features used aren't supported by my browser.

What could be the problem?

Thank you

**Comment by akhilleusuggo** [comment]
Try by adding `allow play all;` on application live segment . ( restart nginx )

**Comment by DanielnetoDotCom** [comment]
one thing I notice on adaptive. your hardware have to be good enough to handle the process.

so make sure you have CPU and disk I/O

**Comment by jengajenga** [comment]
Thanks guys, I will try it out later tonight and give you feedback.
