### ISSUE TITLE
How subscriptions work

### ISSUE THREAD

**Issue by gabrielmais** [WWBN/AVideo#3801]
**Describe the question**
Hello, I would like to know how subscriptions work.

Can each channel have its subscribers?
I have the subscriber plug-in I purchased. But I can't see subscribers on a channel other than the administrator's!
In addition, the demo.avideo.com user menu has more options than I have at my location, but my version is the most current one follows the image.

**Screenshots**
![01 ask](https://user-images.githubusercontent.com/7960434/95543822-e59bb800-09cf-11eb-8783-19483601d7ec.png)

![02 ask](https://user-images.githubusercontent.com/7960434/95544191-d1a48600-09d0-11eb-97ea-32530baa26b6.png)

as you can see in the images, although the version is 9.5 on my website, I don't have all the options you have in the video.

I would like to know how to set it up so that each user sees your dashboard, your subscribers and your videos.

**Comment by akhilleusuggo** [comment]
I believe that the user on your local web is not admin . That means you need to enable it from users : 

![image](https://user-images.githubusercontent.com/52116577/95544486-e64e4180-0a03-11eb-975b-05352070369e.png)

Enable what you want : 

![image](https://user-images.githubusercontent.com/52116577/95544518-ff56f280-0a03-11eb-855d-f7bb172df1a3.png)

**Comment by gabrielmais** [comment]
You is brazilian ?

**Comment by gabrielmais** [comment]
Wouldn't it have an explanation of how subscribers work?

**Comment by akhilleusuggo** [comment]
Here you have it in brazilian : 

![image](https://user-images.githubusercontent.com/52116577/95546622-bd30af80-0a09-11eb-9569-22123b3ab451.png)

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/95546701-f832e300-0a09-11eb-9058-d718cfada23e.png)

To have favorites and all that stuff , you need to add at the least 1 video to favorite ...
