### ISSUE TITLE
uploading video form local 

### ISSUE THREAD

**Issue by aliceglitch** [WWBN/AVideo#3803]
hi there, i have a problem, i cannot upload videos from my local host and i cant click on video url.
![Untitled](https://user-images.githubusercontent.com/72448881/95563058-ccbff080-0a29-11eb-957c-a20207d0dde9.png)

**Comment by DanielnetoDotCom** [comment]
this is not to upload, on this page you must select a previews uploaded video.

**Comment by aliceglitch** [comment]
debugging one error in youphptube

Hi, I am a problem about this error, when I click on the install now button, I get this error. How can I solve this error?
thank u.

![photo_2020-11-07_02-50-29](https://user-images.githubusercontent.com/72448881/98424879-80a7b080-20a8-11eb-83ca-9cc0053f629c.jpg)
