### ISSUE TITLE
Email configuration not working

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#3804]
Hi Folks 

Trying to set my email configuration in Avideo site, but it doesn't like it.

Tried using gmail, hotmail, and the postfix setup but not sure what I am missing in the main.cf file in postfix.

Help ?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Setting-up-AVideo-Platform-to-send-emails

https://tutorials.avideo.com/video/82/setup-gmail-smtp-with-2fa
