### ISSUE TITLE
Content Getting Cloned by jordanbroadcastingnetwork.com

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#3805]
I noticed in my search console and GA that this domain (jordanbroadcastingnetwork.com) is showing up in my reports but I don't own this domain.  I did a 'site' search command.  I found that all the their content is identical to my own:

![image](https://user-images.githubusercontent.com/739391/95622534-b4f46680-0a41-11eb-81be-f8f4f43d439a.png)

My sitemap also in 121 cases has the JordanBroadcastingNetwork.com domain on my sitemap that I generated from the AVideo platform.  WHY?

Can someone tell me why and how this happened?  I deleted 95% of my videos  but how do it prevent this?  Anyones help is appreciated.

Thanks

**Comment by akhilleusuggo** [comment]
Ask google

**Comment by jengajenga** [comment]
could b that they're generating it using your sitemap. switch off the sitemap.
or maybe you need to enhance security. there are some apache arguments that you can implement to stop content sniffing.

(honestly I don't know why it's happening but try those two and give it some time and see how that goes)

**Comment by DanielnetoDotCom** [comment]
Hi

they just have their domain pointing to your IP

you can create an index page on your /var/www/html folder redirecting permanently everything to your domain.

google will ignore his domain

To permanently redirect a page via PHP, place this code before all other content (i.e., at the very top of the document):

```
<?php // Permanent 301 Redirect via PHP
	header("HTTP/1.1 301 Moved Permanently");
	header("Location: http://domain.tld/new/location/");
	exit();
?>
```

Alternately, this snippet may be consolidated into a single line as follows:

`<?php header("Location: http://domain.tld/new/location/", true, 301); ?>`


Once in place, this code (either method) will redirect the visitor to the address specified in the third line. Edit that address to match the redirect target and you’re all set.

**Comment by willpower68** [comment]
@DanielnetoDotCom thanks I will work on this over the weekend.
