### ISSUE TITLE
Video player

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3808]
1- Click on the video player no longer pause the video
2- Double click no longer full-screen the video 

Can't reproduce on demo , since looks like the videos are down .

**Comment by akhilleusuggo** [comment]
Something related to https://github.com/WWBN/AVideo/commit/3b1bf6ca257b972fc85018121c34e72b74338b49

**Comment by DanielnetoDotCom** [comment]
the seek button now handle the clicks on the player. you can disable the SeekButton plugin and you will have these features back
