### ISSUE TITLE
Installing on a fresh Ubuntu 18.04 server

### ISSUE THREAD

**Issue by s7ntax** [WWBN/AVideo#3809]
I just want to make sure I'm following the correct instructions for my server and the latest version of avideo and avideo encoder. I have a fresh Ubuntu 18.04 server with no LAMP setup yet and I want to install AVideo and AVideo encoder for live streaming so I believe I will also need to install nginx over apache2 for this. Can someone please point me to the best instructions for my tasks so that I can get things done in the right order and with the least hassle. 

TIA!

This is the wiki i was looking at https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer

This is the wiki i was looking at for the encoder https://github.com/WWBN/AVideo-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x---For-AVideo-Encoder

This is the nginx setup i found https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

So if i work through these in that order I will have a working live streaming platform? Anything else I need to look at first or anything missing from those wikis?

**Comment by daoguey** [comment]
so i follow this one: https://www.linuxbabe.com/debian/run-your-own-video-sharing-website-youphptube-debian-10-buster

i do not setup php-fpm (do not set it up) and there you an choose the best way of installing it.  NGINX (experimental) or apache2. 

Up to you. I have my website setup by that www.qerotv.com

**Comment by s7ntax** [comment]
Well I prefer apache2 but I'm sure I read somewhere that to do live streaming you need nginx.

**Comment by akhilleusuggo** [comment]
@s7ntax There's NGINX and rtmp-nginx . Two different things , but can work together .

**Comment by daoguey** [comment]
yup as @akhilleusuggo mentioned you can use both.
