### ISSUE TITLE
Live Streaming

### ISSUE THREAD

**Issue by s7ntax** [WWBN/AVideo#3812]
I've installed avideo, avideo encoder successfully on Ubuntu and everything seemed to go perfectly on setup.

I've enabled the (live) plugin and installed tables.

When I try to stream from obs i get an error - Failed to connect to servers.
Also when i go into the plugins -> (live) -> edit live servers. I get a notice at the top in red.

Live Servers is Disabled, if you want to use it, enable it on the (Live) Plugin 

Live is enabled so why does it say it is disabled? I'm sure this is the reason i cannot connect but i don't know why it is saying it is disabled. Any ideas?

Edit.

Actually I've just found this, so I need to setup nginx? https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

**Comment by akhilleusuggo** [comment]
of course you do have to . Is the live-server

**Comment by s7ntax** [comment]
It's all done and letting me connect now, but the video is not good. I think it may be my 12 year old macbook maxing out on the cpu though and a very old version of OBS so I will test again with a better setup.

**Comment by s7ntax** [comment]
Tested and working perfectly. All I need to know now is how do I set it to record live stream videos onto the server so that they can be archived and played back at a later date.

**Comment by akhilleusuggo** [comment]
the plugin should grab them from the /var/ww/tmp and automatically send them to the encoder .

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by s7ntax** [comment]
Few issue's I'm having now are the offline stays offline when it's live, also got a blank page on admin login but can navigate to rest of the site, also the live player sometimes starts off with a still image until you click it again and also it's muted, is there a way to make the live video player automatically play and with sound.

tail -n 200 -f avideo.log 
`#2 /var/www/arpradiolive.com/YouPHPTube/plugin/ReportVideo/Objects/videos_reported.php(55): sqlDAL::readSql()
#3 /var/www/arpradiolive.com/YouPHPTube/plugin/ReportVideo/ReportVideo.php(252): VideosReported::getAllReportedUsersIdFromUser()
#4 /var/www/arpradiolive.com/YouPHPTube/objects/user.php(2034): ReportVideo::isBlocked()
#5 /var/www/arpradiolive.com/YouPHPTube/view/modeYoutube.php(331): User::hasBlockedUser()
#6 /var/www/arpradiolive.com/YouPHPTube/view/index.php(28): require('/var/www/arprad...')
#7 {main}
  thrown in /var/www/arpradiolive.com/YouPHPTube/objects/mysql_dal.php on line 368
[23-Oct-2020 21:54:59 Europe/Berlin] AVideoLog::DEBUG: Start Login Request SCRIPT_NAME: /objects/login.json.php
[23-Oct-2020 21:54:59 Europe/Berlin] AVideoLog::DEBUG: redirectUri: https://arpradiolive.com/ SCRIPT_NAME: /objects/login.json.php
[23-Oct-2020 21:54:59 Europe/Berlin] AVideoLog::DEBUG: same redirectUri: https://arpradiolive.com/ SCRIPT_NAME: /objects/login.json.php`

These are from the web console

![Screen Shot 2020-10-23 at 22 02 47](https://user-images.githubusercontent.com/17967657/97054003-e14cce80-157b-11eb-8a96-ca7bee03f9b7.png)
![Screen Shot 2020-10-23 at 22 03 47](https://user-images.githubusercontent.com/17967657/97054005-e3169200-157b-11eb-9099-fcf84778c89a.png)

**Comment by s7ntax** [comment]
Too much on here now that i have worked out how to fix myself. Will close and create a new thread.
