### ISSUE TITLE
Streamer + Encoder setup for LAN and Internet

### ISSUE THREAD

**Issue by vikramuvs** [WWBN/AVideo#3816]
Hello Team,

I have a server setup with a local IP which is accessible via LAN(Intranet) and a public IP(Internet) mapped to it. How would you suggest me to install the application with the URL .i.e, I want the users who would upload videos to upload them via LAN(intranet) and also the encoder to be present and accessed via LAN itself (including its uploading of videos to the streamer site, after it is finished with encoding). But i would want the application itself to be accessed via Internet for the other viewers of the videos. 

Suppose if i put the public IP as the URL of the streamer, even when i access the application via LAN it gets redirected towards the public IP, which i do not want.

**Comment by akhilleusuggo** [comment]
Your question has nothing to do with the project honestly .
But I'll tell you what you have to do . First , you did not gave any details about how you have set up your intranet .

The easiest way , is to add a DNS record that points your intranet to the LAN IP . 
If you don't do this , ask your users to add on their hosts config file , the LAN IP address of your site .

**Comment by vikramuvs** [comment]
OK so the setup is like this: 
Server with a LAN IP - 192.168.10.21 ---> mapped to Public IP 102.108.108.11x (has AVideo Streamer with the URL given as 102.108.108.11x/Avideo in the app configuration)
Now, if i hit the IP 192.168.10.21 from my Intranet, it does hit the index page identified by the local IP at the beginning, but the if i do any other activity(such as click a link or go to the sign in option) i am redirected to the public IP 102.108.108.11x (since that is what i gave in the initial configuration). 

I require the users to use their intranet, to login to the application and upload their videos (since this happens faster on LAN than through Internet). But the users will not be able to do it over Intranet since the site redirects to the public IP which goes through the internet. 

Now, since I plan to install the encoder too, I want the encoder to be accessed via a local IP and the encoder should use the Intranet itself to upload the encoded videos to the Streamer site. 

I hope I made myself clear. Sorry if the question posted did not give a clear picture.

**Comment by akhilleusuggo** [comment]
Like I've said before , you may wanna add a customized DNS ( for intranet IP ) that does match the public IP

**Comment by vikramuvs** [comment]
But please help me understand how would that work?

**Comment by vikramuvs** [comment]
The main requirement is to not utilize the internet at all to upload and encode the videos. But still it should be accessible by the public.

**Comment by akhilleusuggo** [comment]
I know . My question is , how did you set up the intranet ? Is it a router ? or a server with software like pfsense , etc etc ?
You need to add a dns to on the software you're using . Your DNS does resolves the IPs . You need to alter the DNS IP to of your site ( domain name ) . Before you change , try it locally .

What OS are you using ? Linux or windows ?

**Comment by vikramuvs** [comment]
The intranet is of the Router configuration with a physical firewall (SOPHOS) blocking unwanted traffic. So there is an DHCP server too, which spews out local IPs for the machines connected through switches. Since the server is setup with a static local IP, the DHCP doesnt mess with its address. So the main internet is connected to the Firewall-cum-Router(i.e. SOPHOS). Here the mapping is made to the public IP with the local IP. 

Since the server with the streamer application is configured with the global IP(public IP), whatever resources the application accesses, it accesses with the $global['webSiteRootURL'] variable, which has public IP stored in it. So the requests are made through the internet. For eg., to access the jquery file, the app makes a request to 102.10x.10x.10x/AVideos/... (which is a global IP)

So, when the users upload their videos, i want them to access the application with the local IP. I also want the other set of users to view the videos by accessing the public IP (who are outside of the local network).

I am using linux (Ubuntu Server 20.04 FF).

Hope this explanation makes it clear?!

**Comment by akhilleusuggo** [comment]
Have you tried what I've said or not ?
If you have ubuntu desktop , add on /etc/hosts ( use nano ) , your private IP address pointing to your site . Start with that

**Comment by vikramuvs** [comment]
I am hesitant to try your suggestion because i know its not going to work. Let me explain my side of things, as to why I think it will not work:

Server configuration- local ip=172.1.x.x ----->mapped to global ip=102.10x.10x.10x. This mapping is done at the router/firewall level(ie., whatever requests that come for 102.10x.10x.10x, i am telling the firewall/router to forward it to my ubuntu server machine). This is for the users outside our LAN to access the server's content. 

Now the application is configured to use the URL 102.10x.10x.10x/AVideo . So the global['webSiteRootURL'] has the value 102.10x.10x.10x/AVideo in it.

Look at this scenario:
1. Users in the LAN will access the application by typing the local ip of the server like this 172.1.x.x/AVideo and they will be shown the landing page of the application. So far so good. Now, when they click on the sign in button, they are redirected to 102.10x.10x.10x/AVideo/login page. Now the subsequent operations also are all carried out on through the global ip itself, coz the variable global['webSiteRootURL'] is getting utilized to build the links(if i am right). 

Now coming to the /etc/hosts configuration. Lets say i write 172.1.x.x    102.10x.10x.10x in it. Now the local machine will know that whatever requests coming to 172.1.x.x should be rewritten as 102.10x.10x.10x, which it does and straight away takes the user to the internet (which is what i DO NOT want, since they will be uploading videos and i want them to strictly use the LAN only, as it is faster), but how will editing the /etc/hosts configuration work for other machines.

2. Lets say i change the configuration of the app to use the local ip as the app URL 172.1.x.x/AVideo. Now the users key in 172.1.x.x/AVideo in the URL bar and they get the app page. Now if they try to sign in, they will be taken to the server on the local ip itself i.e 172.1.x.x/AVideo/login . Now they will upload all the videos, which happens over LAN. Now I am happy. BUT!
The issue is here! Now the users who want to access the videos outside the LAN will key in 102.10x.10x.10x/AVideo and they will be greeted with the landing page. So far so good! The minute they try to sign in (to view the private videos) or click on any other links, they are taken to 172.1.x.x which is the local IP (far far away hidden in the dungeons for them). This local IP, the ubuntu server machine will know that it should be translated to 102.10x.10x.10x, but how will the global DNS / ISP's DNS know that this address should be translated to 102.10x.10x.10x ? 

P.S: To work around the issue, i edited the configuration.php file from "http://102.10x.10x.10x/AVideo" to "./AVideo" . This way whatever  be the IP the app is being accessed from, it should be traversing its internal directory and all the links that are generated by using global['webSiteRootURL'] will be translated to IP/AVideo ,be it local ip or global ip. This worked for the initial pages. But the issue comes when the videos are clicked on. The video pages are not working, like how they should.

**Comment by akhilleusuggo** [comment]
@vikramuvs is it really hard to create a VM or give it a try ? Hard to if it doesn't work , just remove the line ? There's no security issue here . Just resolving an IP address .

**Comment by vikramuvs** [comment]
If i edit the /etc/hosts file on the server, only the serve's browser will understand that the global ip must be mapped to local ip. How will other systems on the network or outside the network(in internet) know that the global ip must be mapped to local ip.

**Comment by akhilleusuggo** [comment]
Not on the server , on your local machine ....... Your local machine needs to know where to point , not your server .

**Comment by vikramuvs** [comment]
If that's the case, then all the machines which upload videos must be configured with /etc/hosts...which in my case turns out to be more than a 100 machines ..

**Comment by akhilleusuggo** [comment]
that's why I've said , you need a router that will do that job for all the machines that are connected to it .
You need a second layer router , that will connect the machines with a modified DNS . This also will help on security and isolate your traffic .

**Comment by akhilleusuggo** [comment]
First , give it a try from 1 machine , if it works , then it's worth configuring a second router .

**Comment by vikramuvs** [comment]
Ah! That will surely complicate the existing system. Besides purchasing is not my department. I was just wondering, all this can be solved by modifying the code underlying..i.e the way the links are built in the pages must be looked at. I am sure that decision was taken with some reasoning, but also do keep this in mind too, since the application which is supposed to work both on the intranet as well as internet. All the applications work like this, ie if i try to access the application with intranet ip, the application (usually will not redirect to the internet ip) will work within the intranet ip itself. This can be achieved by using '.' (dot notation) while using addressing. I tried using this notation. Initial pages with login screen and landing page works fine, even the videos listing page also works fine. But the problem comes when the videos is clicked. Please look into the codes for accessing the videos. (Just a suggestion).

**Comment by akhilleusuggo** [comment]
> Please look into the codes for accessing the videos. (Just a suggestion).

That's something that @DanielnetoDotCom may do .

There are many ways , one of them I've already told you (changing the host )  . The other way are  , setting a secondary vhost ( if you're using apache ) , for the intranet . 

The other is reverse proxy. Where the $global['webSiteRootURL'] = Your-IP . And from there to the internet via a custom port .

Anyway maybe daniel can add some option on the configuration file .

**Comment by akhilleusuggo** [comment]
@vikramuvs witch one did work ?

**Comment by vikramuvs** [comment]
Actually i did not try any, since any of the above suggested solutions did not invoke confidence in me to try them on a production server. Since i do not have my hands on to other servers, i cannot try your solutions. The problem is the server is behind a NAT (where the mapping from a global ip to static intranet ip is happening). So all your solutions will not work for my requirement  and thats why they did not give me enough confidence to try them out.

**Comment by vikramuvs** [comment]
I am thinking some sort of a FTP solution to this (for the time being). Lets see this scenario. The uploaders of the videos use the local ip to transfer the videos to a folder, using local FTP. Then, a script can be written to encode those uploaded videos (a cron job that keeps executing the job regularly) and to transfer these encoded videos to the videos folder of the streamer application, which the users (in the internet) can then access these videos. Can you help me out in writing such a script ? @akhilleusuggo

**Comment by vikramuvs** [comment]
Or would you want me to open one more question thread and carry on our discussions there ? @akhilleusuggo

**Comment by vikramuvs** [comment]
> @vikramuvs witch one did work ?

I just found out about NAT hairpinning. I am going to try that, as it might just work! What do you think @akhilleusuggo ?

**Comment by akhilleusuggo** [comment]
You mean the NAT lookback ? Should work . All the solution above should work , it's just about how you wanna set up your server .
For me , no doubt , the easiest is the hosts , because will be handled by the router anyway .

Example , you have a fully proxies cloudflare site . That mean all request _SHOULD_ go trough the new IP ( proxy ) from cloudflare . But if on your hosts you indicate the origin IP of your server , you will bypass cloudflare proxy . This is the idea that I'm telling .

Point your IP to the domain . The NAT lookback is more advanced , but give it a try . But ''maybe'' you may need another router . As I've said , you know how you made it , and you should know what you want and what you expect .
