### ISSUE TITLE
Live constantly loading

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3817]
Hello. I keep seeing this in my console. I have no idea what it is or why it keeps doing that.

![live_not playing](https://user-images.githubusercontent.com/65451390/95742699-119d8e80-0c99-11eb-9774-add977138e35.png)

I have also just seen this

![live_not playing_2](https://user-images.githubusercontent.com/65451390/95743430-6f7ea600-0c9a-11eb-98b6-bfdee9aab527.png)

On mobile it works PERFECTLY but when it is desktop, it just keeps trying to no end.

Please assist @akhilleusuggo , @DanielnetoDotCom 

Thanks

**Comment by akhilleusuggo** [comment]
I think the link is not right .
Have you tried to access the m3u8 url with VLC or ffplay ? 

Also try another browser ( just not edge explorer )

**Comment by jengajenga** [comment]
> I think the link is not right .
> Have you tried to access the m3u8 url with VLC or ffplay ?
> 
> Also try another browser ( just not edge explorer )

Every browser - chrome, edge and firefox - does the same thing

I normally test my streams with vlc and the stream is excellent. no frame drops.
Testing on castr.io/hlsplayer and the stream is perfect.
On mobile it plays so well.

Guests on my website aren't able to watch either. They get there and they say all it does is load and spin the circle on the player but there isn't any movement.

**Comment by DanielnetoDotCom** [comment]
you may want to check and share a screenshot of your network tab on the JS console.

also please share your nginx.conf

**Comment by jengajenga** [comment]
> you may want to check and share a screenshot of your network tab on the JS console.
> 
> also please share your nginx.conf

Daniel hi. Thanks.

So here are the screenshots. This is the network tab.

![Inkedlive_loading_network_1_LI](https://user-images.githubusercontent.com/65451390/95856105-2a25ab80-0d62-11eb-9803-209cd732124e.jpg)

When I click on the red one saying cancelled, this is what I see

![live_loading_network_2](https://user-images.githubusercontent.com/65451390/95856157-40336c00-0d62-11eb-87bb-11c6f927cfe4.png)

And then here is a screenshot of my conf file

![live_loading_network_nginxconf_1](https://user-images.githubusercontent.com/65451390/95856193-4fb2b500-0d62-11eb-80ce-f6f722742a3e.png)

**Comment by akhilleusuggo** [comment]
the url request ID seems wrong . Are you using useLiveServers ?

**Comment by jengajenga** [comment]
> the url request ID seems wrong . Are you using useLiveServers ?

yes i'm using liveServers.  ?live_servers_id=1 in my URL. 

In my settings it is also used.

**Comment by DanielnetoDotCom** [comment]
click on the m3u8 file and check what is the response

**Comment by jengajenga** [comment]
> click on the m3u8 file and check what is the response

this is what i see

![m3u8_1](https://user-images.githubusercontent.com/65451390/95870204-e8523080-0d74-11eb-8f0e-aa8d67d81070.png)
![m3u8_2](https://user-images.githubusercontent.com/65451390/95870215-ea1bf400-0d74-11eb-844c-0f776f0f2d02.png)

**Comment by DanielnetoDotCom** [comment]
you did not click in the response tab you screenshot the headers

**Comment by jengajenga** [comment]
> you did not click in the response tab you screenshot the headers

sorry about that Dan. Here it is.

![response_1](https://user-images.githubusercontent.com/65451390/95902351-5e6a8d80-0d9d-11eb-8cfb-8708079d14a2.png)

When I click on it, i get a string saying

RESPONSE PAYLOAD. 

But I cannot post. When i try to post the reponse here, Github says no.

![esp_1](https://user-images.githubusercontent.com/65451390/95902947-2f085080-0d9e-11eb-9ab6-8b5491a9dd06.png)

**Comment by DanielnetoDotCom** [comment]
m3u8 file

![image](https://user-images.githubusercontent.com/18009293/95909063-44688500-0d74-11eb-99bf-ade2d628bc12.png)

**also check your .enc file (this file is important to check)**

**Comment by jengajenga** [comment]
where do i find.enc file?

**Comment by DanielnetoDotCom** [comment]
sorry my bad, NOT .enc I mean .key

![image](https://user-images.githubusercontent.com/18009293/95919707-7550b600-0d84-11eb-9856-6d756a486cb0.png)

also m3u8

![image](https://user-images.githubusercontent.com/18009293/95919768-90232a80-0d84-11eb-86c3-72b2257292d2.png)

**Comment by jengajenga** [comment]
@DanielnetoDotCom 

HEre are the screenshots. These are what I get.

When I click one of the m3u8 links

![sc_3](https://user-images.githubusercontent.com/65451390/95970885-26a12b80-0e19-11eb-883f-a7eecbdc91e7.PNG)

when I search for m3u8 i do not get index. I only get this list.

![sc_1](https://user-images.githubusercontent.com/65451390/95970987-433d6380-0e19-11eb-8e20-a40dc4d6afe6.PNG)

When I search for key, I get nothing

![sc_2](https://user-images.githubusercontent.com/65451390/95971025-52241600-0e19-11eb-9ffb-7e5c28b164d2.PNG)

**Comment by DanielnetoDotCom** [comment]
Is that happening on the server you have with me?

if yes, please email me the domain and the admin credentials I will review. but I will need to update you to the latest version, so you will loose the modifications you made on the PHP files

**Comment by jengajenga** [comment]
> Is that happening on the server you have with me?
> 
> if yes, please email me the domain and the admin credentials I will review. but I will need to update you to the latest version, so you will loose the modifications you made on the PHP files

It is with you. Feel free to access. This code I have highlighted is the one i removed. When I removed it, all the live in the first page gallery disappeared as well.

![code](https://user-images.githubusercontent.com/65451390/95998832-ed2ee700-0e3d-11eb-8f66-e6467ec0bc0d.PNG)

**Comment by jengajenga** [comment]
> Check the code you removed.
> 
> there is an option to not show the lives, without need to touch the code.
> 
> ![image](https://user-images.githubusercontent.com/18009293/95999393-3bc38d80-0e0c-11eb-98ca-7f20c31d2f68.png)
> 
> I will update you to make sure you have the latest of everything.
> 
> then we talk about issues

you are the main man!!

thanks Dan!
