### ISSUE TITLE
Move chat in mobile window

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3818]
The chat should be collapsed in the mobile web site version.
Please see this video:
https://fakeotube.com/vEmbed/995

**Comment by DanielnetoDotCom** [comment]
Hi this is a good idea, I may add this in the future. thanks

**Comment by fakeologist** [comment]
Great. Can you at least move the comments out of the way in mobile for now?

**Comment by DanielnetoDotCom** [comment]
please screenshot what you mean

**Comment by fakeologist** [comment]
https://fakeotube.com/v/1016

**Comment by fakeologist** [comment]
Any update on this?  My users say it's hard to navigate on mobile with the chat in the way.

**Comment by DanielnetoDotCom** [comment]
I just sent an update to the Chat2 (version 3.5)
It is collapsible now

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/97448563-8ca8ab00-190f-11eb-906b-baccb9715af4.png)

![image](https://user-images.githubusercontent.com/18009293/97448604-97634000-190f-11eb-8367-a46ca633f6d1.png)

**Comment by fakeologist** [comment]
This is well done. Can this be added to the android app too?
Also can the android app have clickable links and selectable text?
