### ISSUE TITLE
Old version in Updatedb file

### ISSUE THREAD

**Issue by Joelp** [WWBN/AVideo#3820]
in file updateDb.v9.6.sql is:
`UPDATE configurations SET  version = '9.5', modified = now() WHERE id = 1;`

should be:
`UPDATE configurations SET  version = '9.6', modified = now() WHERE id = 1;`

**Comment by akhilleusuggo** [comment]
True ;

https://github.com/WWBN/AVideo/blob/63036334774d4a6219e19ce9c8b195084f4cba9f/updatedb/updateDb.v9.6.sql#L3

**Comment by DanielnetoDotCom** [comment]
Hi, sorry I am not sure how I mix that. but anyway, I just sent the 9.6 update
