### ISSUE TITLE
Encoding videos from ZoomMeetingRecoder plugin

### ISSUE THREAD

**Issue by DrDracula** [WWBN/AVideo#3821]
ZoomMeetingRecorder plugin is working well. The plugin gets all files of meeting such as speaker view video, gallery view video. But the problem is, encoder is encoding each video for each resolution while encoding process. That makes several copy of same video.  What is best practice to solve this issue?
![Capture123](https://user-images.githubusercontent.com/4419061/95836332-fd649a80-0d47-11eb-941f-d695179be7e1.PNG)

**Comment by akhilleusuggo** [comment]
doesn't look to me that they're the same video . Each one of them got a different unique_id_name

**Comment by DanielnetoDotCom** [comment]
Hi, 

@akhilleusuggo is correct, they have different unique_id and also you can see the creation time
this plugin only respond the zoom webhook, it does not work without zoom ask it to do something, maybe is something on the webhook/zoom side you may want to check with them

**Comment by akhilleusuggo** [comment]
This are the option you have to take a look at : 

![image](https://user-images.githubusercontent.com/52116577/96014884-903c2c80-0e4f-11eb-92a6-41e7865c8a24.png)

If you want only HD , then disable everything exept , Do not show encoder resolution HD

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo is correct, but I think your problem is something else.

all 3 resolutions suppose to be on the same video. NOT create 3 instances of the video.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Ok , I know what is the problem . Is the same issue I reported before . The plugin that send the recorded stream to encoder should be improved . For now , we have no control over to witch format will be encoded . HLS ? MP4 ? Webm ? Audio ? The plugin does decide by itself .

We need control over , what format will it be encoded , and witch server we want to send them to . This way , we can decide the parameters we want to use for the recorded video . Maybe we just want a `-c copy` or more complex encoding .

I understand the network-encoder is fine , but does not give you any control over streams .

**Comment by DrDracula** [comment]
How can I cancel encoding process for other resolutions in configuration options? @DanielnetoDotCom @akhilleusuggo

**Comment by akhilleusuggo** [comment]
you can't . manually kill the PID from terminal .....
