### ISSUE TITLE
Sub-Categories in the first page

### ISSUE THREAD

**Issue by r0xmachine** [WWBN/AVideo#3822]
Hi,
maybe it's only my mistake anyway, I have created 3 categories A,B and C, inside A I have 10 sub-categories.
Now in the first page usng the Gallery style pluing when I select the category view also all subcategories are automatically
displayed. I tryed also netflix and default style, obviously the subcategory display is not selected inside the plug-in.
Any suggestions to remove the sub-category from the first page ?

**Comment by DanielnetoDotCom** [comment]
can you please screen shot to illustrate what you mean?

**Comment by akhilleusuggo** [comment]
@r0xmachine Disable this option , AND clear the cache ( mandatory )

![image](https://user-images.githubusercontent.com/52116577/95868301-bf30a080-0d72-11eb-8583-e05a89d5e7f1.png)

**Comment by r0xmachine** [comment]
Youphptube v.9.5 , this is the code :

{"hidePrivateVideos":false,"BigVideo":true,"useSuggestedVideosAsCarouselInBigVideo":false,"GifOnBigVideo":true,"Description":false,"CategoryDescription":false,"Suggested":false,"SuggestedCustomTitle":"","SuggestedRowCount":"12","Trending":false,"TrendingCustomTitle":"","TrendingRowCount":"12","DateAdded":false,"DateAddedCustomTitle":"Novita'","DateAddedRowCount":"12","MostWatched":false,"MostWatchedCustomTitle":"I Piu' Visti","MostWatchedRowCount":"12","MostPopular":false,"MostPopularCustomTitle":"","MostPopularRowCount":"12","SortByName":false,"SortByNameCustomTitle":"","SortByNameRowCount":"12","SubscribedChannels":false,"SubscribedChannelsRowCount":"12","Categories":true,"CategoriesCustomTitle":"Cinema","CategoriesRowCount":"3","sortReverseable":false,"SubCategorys":false,"showTags":false,"searchOnChannels":false,"searchOnChannelsRowCount":"12","playVideoOnFullscreen":false,"playVideoOnBrowserFullscreen":false,"filterUserChannel":false,"screenColsLarge":"6","screenColsMedium":"3","screenColsSmall":"2","screenColsXSmall":"1"}

**Comment by r0xmachine** [comment]
Hi, I replicated the issue in the demo page : https://demo.avideo.com/
Subcategoriies view is disabled but displayed in the first page :

https://demo.avideo.com/

**Comment by DanielnetoDotCom** [comment]
the problem was because you are only displaying the categories section.

I am sending an update to the gallery layout that will display the category in case you did not select any other section to display

**Comment by r0xmachine** [comment]
Daniel, the issue is present also If I displayed MostWatched or Trending, the subcategories are displayed.
You can check this issue in your demo site.

**Comment by DanielnetoDotCom** [comment]
Hi, maybe I am missing understanding you.

are you saying the subcategory are not suppose to appear?

**Comment by r0xmachine** [comment]
Hi, the issue is simple, in the first page I want to see the categories but when I enable the categoriy view with o without other like trending or mostwatched, the subcategories are always displayed (subcategory view disabled). I have 30 subcategories for earch category (5 categories) the first page ibecame too long.
