### ISSUE TITLE
Error in locale/ru.php

### ISSUE THREAD

**Issue by itdoka** [WWBN/AVideo#3823]
Hi, I am trying to edit the translation for the new version of AVideo on site https://my.site/locale/. When saving, I only get a blank white page, I found an error in this file ru.php, in the form of an extra character \ , looks like (two slash) `\\'`    . I remove one slash, the site works
![bandicam 2020-10-13 21-42-39-510](https://user-images.githubusercontent.com/52359603/95869065-8f4ac280-0d9d-11eb-8a86-0dc98537fdbf.jpg)
![bandicam 2020-10-13 21-43-06-262](https://user-images.githubusercontent.com/52359603/95869194-b5706280-0d9d-11eb-8268-55f8f9821c3e.jpg)
![bandicam 2020-10-13 21-43-34-401](https://user-images.githubusercontent.com/52359603/95869220-ba351680-0d9d-11eb-8e1b-1087f2f19b9d.jpg)

**Comment by DanielnetoDotCom** [comment]
try to manually edit the file and search and replace the `\\` for `\`

**Comment by itdoka** [comment]
Thanks, I did just that, there were only 5 errors

**Comment by SergejGrin** [comment]
Hi, I am attaching an updated and corrected version of the translation into Russian, compatible with the 10.X version.

[ru.php.zip](https://github.com/WWBN/AVideo/files/6135093/ru.php.zip)

Изначально в файле перевода всё было "по-фэншую" - без косых черточек. Видимо кто-то проявил активность и перестарался. Вот прикладываю дополненную и исправленную версию перевода совместимую с 10.Х версией.
