### ISSUE TITLE
Can't Subscribe in Storage Plan

### ISSUE THREAD

**Issue by julzxcapz** [WWBN/AVideo#3824]
Hi, 

Can you assist me on this? I'm using test api keys and trying to subscribe a plan but stuck at processing. 

![image](https://user-images.githubusercontent.com/61785146/95907476-2fb8db00-0dce-11eb-9b25-7c7cf54c8abd.png)

here's what on the log:
![image](https://user-images.githubusercontent.com/61785146/95907906-d8ffd100-0dce-11eb-9e9b-732e8a34f281.png)

**Comment by DanielnetoDotCom** [comment]
if you read what they say on the log.

you will need to delete the plan and create another one.
you created the plan on test mode, and now you are trying to use it on live mode.

**Comment by julzxcapz** [comment]
thanks :)
