### ISSUE TITLE
Problems with cache 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3825]
Every new video uploaded , does not load before clearing the cache . Like when the video is missing video's files .
Also after every editing on the video's description , the video show the thumbnail when a thumbnail is missing .

Updating the disk usage , does not help , only clearing the cache .

**Comment by DanielnetoDotCom** [comment]
Do you have this update? 

https://github.com/WWBN/AVideo/blob/4a8177ceefa4b2e78ce96bcf2e17b204c8a0222e/objects/functions.php#L1406

I added this line to make sure if something happen and the video does not have sources it will auto clear the cache for that video

**Comment by akhilleusuggo** [comment]
This is crazy , is not working and thanks to this , I found that the issue that I have reported here : https://github.com/WWBN/AVideo/issues/3797 is actually not an issue , just the cache . 

Every time I wanna do something I need to clear the cache . ( is not cloudflare ) .

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Still the same problem , I did updated and nothing .

![image](https://user-images.githubusercontent.com/52116577/96116157-afd76180-0ef0-11eb-9cea-a6a4fea2d584.png)

**Comment by DanielnetoDotCom** [comment]
can you please update and try again?

I just made a test and it works fine.

**Comment by JoshWho** [comment]
You cant tell cloudflare to use the origin cache headers and the Avideo Cache headers will auto clear CF cache.

**Comment by DanielnetoDotCom** [comment]
Hi, I just sent a bunch of updates regarding the cache.

I hope it fixes something

**Comment by wildmaster84** [comment]
while using the cache plugin, when a user logs out then the page is blank, I disabled the plugin and it fixed everything.

**Comment by DanielnetoDotCom** [comment]
@wildmaster84 is this after my last update?

please check the logs

**Comment by wildmaster84** [comment]
im not sure but ill reupload the cache plugin and see

**Comment by DanielnetoDotCom** [comment]
not just cache plugin, you must update everything

**Comment by wildmaster84** [comment]
I just tested it and yes even after the the updates it still happens

![image](https://user-images.githubusercontent.com/46942741/96355589-1d31f080-10b1-11eb-9a38-0391a37e47b8.png)

**Comment by DanielnetoDotCom** [comment]
Are you sure you update everything?

check your log files

**Comment by wildmaster84** [comment]
I cleared the log and followed the steps to cause the issue and all it says in the log is the following.

[17-Oct-2020 20:15:53 America/New_York] AVideoLog::DEBUG: plugin::setCurrentVersionByUuid 10573225-3807-4167-ba81-0509dd280e06, 1.0 SCRIPT_NAME: /objects/pluginSwitch.json.php


![image](https://user-images.githubusercontent.com/46942741/96355924-b105bb80-10b5-11eb-8442-ce9e057bedcc.png)

**Comment by wildmaster84** [comment]
[https://siggnal.ga/logs/error.log](Live Nginx Log)

**Comment by akhilleusuggo** [comment]
@JoshWho Can you give me more details ? I'm still having this problem . I'm thinking to never update again , until some really big thing comes out .

> You can tell cloudflare to use the origin cache headers and the Avideo Cache headers will auto clear CF cache.
