### ISSUE TITLE
How to remove this list

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3826]
I would like to remove the list of live under the video but keep the one in the navbar.

I have tried in the menuRight file but they seem to be linked. How to do it? Thanks.

![remove](https://user-images.githubusercontent.com/65451390/95993529-e604da80-0e37-11eb-9600-880f3c460b7f.png)

**Comment by jengajenga** [comment]
Never mind. I got it.

I removed all the php code in line 216.

**Comment by DanielnetoDotCom** [comment]
Hi, 

I recommend you do not change the PHP code. otherwise you will have problems to follow the updates

may have an option for that

**Comment by jengajenga** [comment]
Funny you've said that I have just seen that the first page is now completely blank after doing that. Kindly help with a fix.

**Comment by jengajenga** [comment]
> Hi,
> 
> I recommend you do not change the PHP code. otherwise you will have problems to follow the updates
> 
> may have an option for that

did you find the option to remove it?

**Comment by DanielnetoDotCom** [comment]
> > Hi,
> > I recommend you do not change the PHP code. otherwise you will have problems to follow the updates
> > may have an option for that
> 
> did you find the option to remove it?

https://github.com/WWBN/AVideo/issues/3817#issuecomment-708422167

**Comment by jengajenga** [comment]
seen it. thank you.

**Comment by jengajenga** [comment]
well, sorry about closing and reopening.

@DanielnetoDotCom , the fix you sent is also connected to the front page live gallery. When i select it and click save, the live videos in my front page ALL disappear.

I want the front page to remain as it is. what i want to remove is the long list under individual pages.

**Comment by DanielnetoDotCom** [comment]
There is no option to hide only the videos on the player.

maybe you can use CSS for that

Probably something like this

```
#modeYoutubeBottomContent .extraVideos{
   display: none;
}
```

you can add it like this https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css

**Comment by jengajenga** [comment]
That didn't work for me. I opted to block out a line number 166-169 in the modeYoutubeLive.php file. So far so good. 
That list is very heavy on resource. I think it is what was causing my live to constantly load without playing. When I would remove it, it would play very well and very quickly.
I will monitor and see how it goes.
Thanks again Dan.

**Comment by syldri** [comment]
hello @jengajenga  I had the same problem I asked @DanielnetoDotCom  for all the css code he gave me did not work

I directly delete the line

/AVideo/plugin/Live/view/modeYoutubeLive.php

![image](https://user-images.githubusercontent.com/39193219/96067273-a373ea00-0e99-11eb-8c9c-995de1c26a5e.png)

**Comment by jengajenga** [comment]
> hello @jengajenga I had the same problem I asked @DanielnetoDotCom all the css code he gave me did not work
> 
> I directly delete the line
> 
> /AVideo/plugin/Live/view/modeYoutubeLive.php
> 
> ![image](https://user-images.githubusercontent.com/39193219/96067273-a373ea00-0e99-11eb-8c9c-995de1c26a5e.png)
> 
> if the plugin is up to date you should edit the file again
> 
> * for the Link plugin
> 
> /AVideo/plugin/Lick/view/Live.php
> 
> ![image](https://user-images.githubusercontent.com/39193219/96067832-df5b7f00-0e9a-11eb-8a05-c0ce721710d2.png)

thank you syldri. i had already deleted the first one. i've just now removed the second as i didn't know it was also there.
thanks.
