### ISSUE TITLE
Transfer videos to another channel?

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3828]
Hi

is there a way to transfer videos from a channel to another channel? 

E.g. if I want to make a new user and a channel (not only a category) for certain type of videos, but I don't want to upload the videos again..

**Comment by jengajenga** [comment]
I think there is a SWAP option which you can enable under Plugins>Customise Advanced.
Then you will seen the option under your videos page.

**Comment by tonuzo** [comment]
Thanks, but I think you can use it to swap videos inside your channel, not between different channels.

**Comment by akhilleusuggo** [comment]
As admin , you can go and changer video's owner .

**Comment by tonuzo** [comment]
> As admin , you can go and changer video's owner .

Thanks! I just can't find the the option anywhere... Can you give little more details please?

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/96119949-67bb3d80-0ef6-11eb-82cb-ee6d30c23070.png)

On media owner , start typing the channel name , will list you what you need .

**Comment by tonuzo** [comment]
Of course. Thank you very much!
