### ISSUE TITLE
Change  resolution?

### ISSUE THREAD

**Issue by patrickwienecke** [WWBN/AVideo#3829]
It's possible to change resolution for the categorie SD,HD.... Maybe it's a Setting for the Encodermodul?

**Comment by tonuzo** [comment]
Do you mean this on encoder?:

![image](https://user-images.githubusercontent.com/63721378/96132322-2de83800-0ef2-11eb-8057-7f1906a6c02d.png)

**Comment by patrickwienecke** [comment]
That is what I mean. But when I go to the encoder side using SSO, I don't see a configuration tab. Direct login does not seem possible or rich does not know the user for avideo-encoder

**Comment by tonuzo** [comment]
Are you logged in as admin?

**Comment by tonuzo** [comment]
Check this issue [(https://github.com/WWBN/AVideo-Encoder/issues/58)]

**Comment by patrickwienecke** [comment]
Great! This solve my Problem. Thank You
