### ISSUE TITLE
Add to playlist favorite broken

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3832]
Hi

just noticed that add to + favorite doesn't work anymore. Can be reproduced on demo site.

1. choose a video and click "add to +"
2. select favorite
3. go to your favorites, the video isn't visible on the playlist. 
4. go back to video and click "add to +" - to see that the favorite is inactive.

**Comment by DanielnetoDotCom** [comment]
Not sure if is the same error, but here is a fix
