### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#3836]
Hi Daniel,

I found problem after upgrade to v.9.6
I can't login anymore when logout.  It always need to clear Browser cache.
I tryout on the demo site.  It's the same problem.

**Comment by DanielnetoDotCom** [comment]
Thanks for the info, try this new update

**Comment by JoshWho** [comment]
I cant login neither and I updated

**Comment by JoshWho** [comment]
WHat happend No one can log in

**Comment by JoshWho** [comment]
I log in as soon as I go to another page I am logged out. This is horrible My support ticket system is overwhelmed. WHy would changes like this go in production?

**Comment by JoshWho** [comment]
Login is working great now. Even the logout works good again.
