### ISSUE TITLE
Add to Watch Later and Favorites

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3838]
I have a bug when users are tying to add videos to the Watch Later list what happens is that clicking the Watch Later buttong will also set the Favorites as well, but when the popup disappears and I click the same Add to link, Only the Watch Later is marked. The problem is that the Watch Later Page will only show the last selected Add to video. It doesn't add the videos to the list for some reason. Here are the screenshots of the popup before and after selection as well as the Watch Later page after adding few videos to the list.

![Screen Shot 5781-01-28 at 17 26 59](https://user-images.githubusercontent.com/58882903/96271469-9bb96000-0fd5-11eb-834e-780fa47f5b3b.jpg)
![Screen Shot 5781-01-28 at 17 27 07](https://user-images.githubusercontent.com/58882903/96271477-9d832380-0fd5-11eb-8acc-457618bf45a4.jpg)
![Screen Shot 5781-01-28 at 17 27 23](https://user-images.githubusercontent.com/58882903/96271481-9e1bba00-0fd5-11eb-80bb-19d257fa246d.jpg)

Cannot see anything specific in the logs but I will post more info if I find something related.

**Comment by DanielnetoDotCom** [comment]
yesterday I sent some updates regarding playlists. can you please confirm if you have the latest and the problem persists?

**Comment by guymass** [comment]
You are right, thank you, I did git pull and updated and it fixed this issue.
