### ISSUE TITLE
Deleting Videos Keeps the Processing Bar Stuck On screen never goes away

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3841]
When deleting videos from the mvideos page the processing bar stays frozen at the top and never goes away.

**Comment by akhilleusuggo** [comment]
This last update brought some caching issues , and daniel can't find it .
I'm having similar issue . Also when new video is uploaded , the video does not play when the encoding finishes , need to manually clear the cache ...

**Comment by JoshWho** [comment]
I haven't had that issue yet but I have seen some videos upload and not have time stamps. I had to manually update it in the sql tables.

**Comment by DanielnetoDotCom** [comment]
@JoshWho make sure you also update your encoders

**Comment by JoshWho** [comment]
OK I updated the encoders. I do not use webm but it is now showing on them

**Comment by DanielnetoDotCom** [comment]
try this

![image](https://user-images.githubusercontent.com/18009293/96335218-8e3fbc80-104d-11eb-8c66-595697ba72a0.png)

**Comment by JoshWho** [comment]
Sweet. Will do.
