### ISSUE TITLE
Ad Server Not working - No VIdeo ads are showing anymore

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3842]
I have mine setup to play an ad after every video playback but it is no longer working. Now videos just keep autoplaying to the next video when I have that turned off.

**Comment by DanielnetoDotCom** [comment]
Sorry what is exactly the problem?

The post roll video is not working?

**Comment by JoshWho** [comment]
Correct. No video ads are playing

**Comment by DanielnetoDotCom** [comment]
what plugin are you using for it?

Ads server or GoogleAds_IMA?

only post rolls or any ad is failing?

**Comment by JoshWho** [comment]
The regular Ad Server with my personal video ads.
