### ISSUE TITLE
wwbn youphptube loads in localhost only

### ISSUE THREAD

**Issue by yottadaadmin** [WWBN/AVideo#3845]
Hi Everyone

i have setup a wwbn Youphptube/Avideo server on ubuntu 18 in a virtualbox 6.1 environment, it seems to be working fine on the local host i can access the gui in a browser just fine on the local machine but when i try to access the url from my desktop computer the graphics will not load right and the page looks all out of place.

![from the local ubuntu host](https://user-images.githubusercontent.com/73024926/96337815-ab8e7e00-1081-11eb-9aa1-7d49ac0d708a.png)

![the same page on my desktopPC](https://user-images.githubusercontent.com/73024926/96337784-6f5b1d80-1081-11eb-89d7-943b6a2701a3.png)

any help or advice will me much appreciated.

**Comment by DanielnetoDotCom** [comment]
Check your browser html source code and your configuration.php

It looks like an unreachable url path

**Comment by yottadaadmin** [comment]
Hi Daniel


Thank you for your help above, I just wanted to know does Avideo have a live streaming option without having to use OBS something like YouTube.


Kind regards


Get Outlook for Android

**Comment by DanielnetoDotCom** [comment]
yes, you can use the meet plugin

**Comment by yottadaadmin** [comment]
Hi Daniel


Thank you sir you are fantastic ☺️


Kind regards

Hassan


Get Outlook for Android

**Comment by yottadaadmin** [comment]
worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://10.101.1.97/AVideo/plugin/Live/on_publish.php;
                            on_play http://10.101.1.97/AVideo/plugin/Live/on_play.php;
                            on_record_done http://10.101.1.97/AVideo/plugin/Live/on_record_done.php;
                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   
            }
    }

**Comment by yottadaadmin** [comment]
Hi Daniel
  
  
   
  
  
   does AVideo have a page like the below and if not how can i get one. i don't want to use obs.
  
  
   
  
  
   
   
  
  
   
    On 22/10/2020 00:36 Daniel Neto <notifications@github.com> wrote:
   
   
    
   
   
    
   
   
   yes, you can use the meet plugin
