### ISSUE TITLE
Stream Not Showing 

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#3846]
Greetings. Please help my Stream is not Showing but it does show the live button, just not showing the ectual video.

Please See my Nginx logs

![Meet my craft](https://user-images.githubusercontent.com/72950503/96339535-3bb0d100-104a-11eb-97ae-7aa4f2d662f0.png)
![Meet my craft](https://user-images.githubusercontent.com/72950503/96339693-2b4d2600-104b-11eb-9f21-ae17be7d6c94.png)
live/5f7753760abc7/https://live.meetmycraft.com:444/live/5f7753760abc7/18.ts HTT                                                                                        P/1.1", host: "live.meetmycraft.com:444"
2020/10/17 13:53:54 [info] 108745#0: *1019 client 105.12.6.126 closed keepalive                                                                                         connection
2020/10/17 13:53:55 [error] 108745#0: *1022 open() "/HLS/live/5f7753760abc7/http                                                                                        s:/live.meetmycraft.com:444/live/5f7753760abc7/18.ts" failed (2: No such file or                                                                                         directory), client: 105.12.6.126, server: live.meetmycraft.com, request: "GET /                                                                                        live/5f7753760abc7/https://live.meetmycraft.com:444/live/5f7753760abc7/18.ts HTT                                                                                        P/1.1", host: "live.meetmycraft.com:444"
2020/10/17 13:53:55 [info] 108745#0: *1022 client 105.12.6.126 closed keepalive                                                                                         connection
2020/10/17 13:54:05 [info] 108745#0: *1052 client closed connection while waitin                                                                                        g for request, client: 140.82.0.58, server: 0.0.0.0:444
2020/10/17 13:54:06 [info] 108745#0: *1053 client closed connection while waitin                                                                                        g for request, client: 140.82.0.58, server: 0.0.0.0:444
2020/10/17 13:54:07 [info] 108745#0: *1056 client 140.82.0.58 closed keepalive c                                                                                        onnection
2020/10/17 13:54:07 [info] 108745#0: *1065 client closed connection while waitin                                                                                        g for request, client: 89.248.172.90, server: 0.0.0.0:8080
2020/10/17 13:54:07 [error] 108745#0: *1067 open() "/usr/local/nginx/html/azenv.                                                                                        php" failed (2: No such file or directory), client: 89.248.172.90, server: live.                                                                                        meetmycraft.com, request: "GET http://httpheader.net/azenv.php HTTP/1.1", host:                                                                                         "httpheader.net"
2020/10/17 13:54:07 [info] 108745#0: *1067 client 89.248.172.90 closed keepalive                                                                                         connection
2020/10/17 13:54:08 [info] 108745#0: *1068 client sent invalid method while read                                                                                        ing client request line, client: 89.248.172.90, server: live.meetmycraft.com, re                                                                                        quest: "P3OU▒0"
2020/10/17 13:54:08 [info] 108745#0: *1069 client sent invalid method while read                                                                                        ing client request line, client: 89.248.172.90, server: live.meetmycraft.com, re                                                                                        quest: "P3OU▒0"
2020/10/17 13:54:08 [info] 108745#0: *1070 client sent invalid method while read                                                                                        ing client request line, client: 89.248.172.90, server: live.meetmycraft.com, re                                                                                        quest: ""
2020/10/17 13:54:54 [info] 108745#0: *27 deleteStream, client: 192.99.13.58, ser                                                                                        ver: 0.0.0.0:1935
2020/10/17 13:54:54 [info] 108745#0: *27 notify: record_done recorder=video path                                                                                        ='/var/www/tmp/5f7753760abc7-17-Oct-20-13:47:15.flv' url='live.meetmycraft.com/p                                                                                        lugin/Live/on_record_done.php', client: 192.99.13.58, server: 0.0.0.0:1935
2020/10/17 13:54:54 [info] 108745#0: *27 disconnect, client: 192.99.13.58, serve                                                                                        r: 0.0.0.0:1935
2020/10/17 13:54:54 [info] 108745#0: *27 deleteStream, client: 192.99.13.58, ser                                                                                        ver: 0.0.0.0:1935
2020/10/17 13:54:59 [info] 108745#0: *1201 client closed connection while waitin                                                                                        g for request, client: 140.82.0.58, server: 0.0.0.0:444
2020/10/17 13:55:00 [info] 108745#0: *1210 client 140.82.0.58 closed keepalive c                                                                                        onnection
PuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTY2020/10/17 13:58:32 [info] 108745#0: *1778 client closed connection while waiting for request, client: 140.82.0.58, server: 0.0.0.0:444
2020/10/17 13:58:33 [info] 108745#0: *1780 client 140.82.0.58 closed keepalive connection
2020/10/17 13:59:13 [error] 108745#0: *1888 open() "/HLS/live/5f7753760abc7/https:/live.meetmycraft.com:444/live/5f7753760abc7/22.ts" failed (2: No such file or directory), client: 140.82.0.58, server: live.meetmycraft.com, request: "GET /live/5f7753760abc7/https://live.meetmycraft.com:444/live/5f7753760abc7/22.ts HTTP/1.1", host: "live.meetmycraft.com:444"
2020/10/17 13:59:13 [info] 108745#0: *1888 client 140.82.0.58 closed keepalive connection
2020/10/17 13:59:13 [error] 108745#0: *1889 open() "/HLS/live/5f7753760abc7/https:/live.meetmycraft.com:444/live/5f7753760abc7/23.ts" failed (2: No such file or directory), client: 140.82.0.58, server: live.meetmycraft.com, request: "GET /live/5f7753760abc7/https://live.meetmycraft.com:444/live/5f7753760abc7/23.ts HTTP/1.1", host: "live.meetmycraft.com:444"
2020/10/17 13:59:13 [info] 108745#0: *1889 client 140.82.0.58 closed keepalive connection
2020/10/17 13:59:13 [error] 108745#0: *1890 open() "/HLS/live/5f7753760abc7/https:/live.meetmycraft.com:444/live/5f7753760abc7/24.ts" failed (2: No such file or directory), client: 140.82.0.58, server: live.meetmycraft.com, request: "GET /live/5f7753760abc7/https://live.meetmycraft.com:444/live/5f7753760abc7/24.ts HTTP/1.1", host: "live.meetmycraft.com:444"
2020/10/17 13:59:13 [info] 108745#0: *1890 client 140.82.0.58 closed keepalive connection

**Comment by DanielnetoDotCom** [comment]
Can you please screenshot your live plugin parameters?

Also your nginx.conf


FYI this looks very wrong, probably a wrong redirect 

`
2020/10/17 13:59:13 [error] 108745#0: *1888 open() "/HLS/live/5f7753760abc7/https:/live.meetmycraft.com:444/live/5f7753760abc7/22.ts" failed (2: No such file or directory), client: 140.82.0.58, server: live.meetmycraft.com, request: "GET /live/5f7753760abc7/https://live.meetmycraft.com:444/live/5f7753760abc7/22.ts HTTP/1.1", host: "live.meetmycraft.com:444"`

**Comment by mrgodgiven** [comment]
![Nginx 1](https://user-images.githubusercontent.com/72950503/96368849-41bab680-110b-11eb-8629-3a8ab1c41b91.png)
![Nginx 2](https://user-images.githubusercontent.com/72950503/96368850-44b5a700-110b-11eb-8a9c-0ec25be12261.png)
Here is my Nginx Parameters

**Comment by mrgodgiven** [comment]
![live 1](https://user-images.githubusercontent.com/72950503/96368960-d9200980-110b-11eb-94ec-38ff4f01b33c.png)
H
![Live 2](https://user-images.githubusercontent.com/72950503/96368963-db826380-110b-11eb-9a3d-bd9423a81295.png)ere is m
![Live 3](https://user-images.githubusercontent.com/72950503/96368965-dc1afa00-110b-11eb-8849-d2fa27bbeff3.png)y Live plugin settings.

**Comment by mrgodgiven** [comment]
I noticed that my ssl parameters were incorect as well and I fixed it as you can see, but now it shows the stream, just not recording it and shows 00 after encording it

**Comment by mrgodgiven** [comment]
![Error Encorded](https://user-images.githubusercontent.com/72950503/96369046-8c88fe00-110c-11eb-8888-8ecdf880c588.png)
Please See this error after live recording, but uploaded content it very fine except for live recorded.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom The protect live_stream I'm not sure if it does work or not . But following your settings how did set it up , should not work . What key are you using to protect it ? The self made ? or the ssl let's encrypt ? Or is it generating a tocken ?

@mrgodgiven Can you try disabling protect live_stream and clear the cache ? Note, rtmp does not work with cloudflare .

**Comment by mrgodgiven** [comment]
Ok Thanks will  do now

**Comment by mrgodgiven** [comment]
Still doing the same thing. I think perhaps the sendrecorded to encoder plugin has settings problem, but I followed instructions as usual 
![Live video error](https://user-images.githubusercontent.com/72950503/96370400-767e3c00-1112-11eb-891c-71b5ad908313.png)

**Comment by mrgodgiven** [comment]
![Encorder](https://user-images.githubusercontent.com/72950503/96371120-091fda80-1115-11eb-967d-c2e7b9b954cc.png)
I only enabled mp4 on my encorder and i don't know if that could be a problem.

**Comment by DanielnetoDotCom** [comment]
Hi sorry for the late reply

please inspect your code and check what the m3u8 files are returning.

for example, this is what I get from the demo site.

![image](https://user-images.githubusercontent.com/18009293/96586154-f7763880-12b6-11eb-9fd6-24d5577f5d22.png)

**Comment by mrgodgiven** [comment]
![Live 3u8](https://user-images.githubusercontent.com/72950503/96599744-14a20b80-12a5-11eb-9f9f-5333ccfe37ec.png)
Here is mine. Sad part is that now After uploading the latest sendrecorded to encoder plugin it then stopped even recording.

**Comment by DanielnetoDotCom** [comment]
based on the image I do not see a problem at all.

can you please share the site link so I can check the URL?

**Comment by mrgodgiven** [comment]
After today's update it works again like always problems automatically stopped and I don't know how and the errors dissapeared from my log file as well, Thanks for the update.
