### ISSUE TITLE
What is it and why is it there?

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3847]
I have this in my player. Am I the only one with it? Why is it there anyway? it is there on live videos.

![player_](https://user-images.githubusercontent.com/65451390/96339804-7e50c880-109f-11eb-8f34-59523aca7350.png)

**Comment by DanielnetoDotCom** [comment]
Can you please share a link to it?

**Comment by jengajenga** [comment]
Can i send the link privately to your public email in your profile dan***.com@gmail.com?

**Comment by DanielnetoDotCom** [comment]
yes please

**Comment by jengajenga** [comment]
Daniel did you manage to figure this one out?

**Comment by DanielnetoDotCom** [comment]
Did you send me the link?

I did not see that

**Comment by DanielnetoDotCom** [comment]
I do not have it on my browser, try to clear your browser cache.

![image](https://user-images.githubusercontent.com/18009293/97561446-f338d200-19be-11eb-8853-e12638f9a22f.png)
