### ISSUE TITLE
change adpatative to 1080,720 and 480

### ISSUE THREAD

**Issue by daoguey** [WWBN/AVideo#3848]
can you tell me how to configure this to have those 3 resolutions correctly setup?

![image](https://user-images.githubusercontent.com/15695109/96355570-18187580-10a0-11eb-94db-03b8704ce223.png)

I was able to change it in the settings before but i cannot find where now.

![image](https://user-images.githubusercontent.com/15695109/96355636-f79ceb00-10a0-11eb-991a-fd4b0b3df9df.png)

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/issues/3831

**Comment by akhilleusuggo** [comment]
Duplicate of #3831

**Comment by daoguey** [comment]
@akhilleusuggo This is also different, I am requesting the change information for those resolutions not only to fix the issue of not syncing.

**Comment by akhilleusuggo** [comment]
What you need is a fix . You've already changed it . On your nginx config I see 480,720,1080 . Now what you need is a fix to HLS plugin to display 480,720,1080 labels . ( it is working ) , just the layout(label) is not working . When you select 720 , it's actually 1080 , when you select 540 it's 720 etc etc ...

**Comment by daoguey** [comment]
I am not sure if it works as i can see the stream going but not from HLS.
![image](https://user-images.githubusercontent.com/15695109/96396799-3d32e400-1185-11eb-9f05-1bdec38e6276.png)

**Comment by akhilleusuggo** [comment]
It works , if you need more details about nginx , you should ask on nginx-rtmp project . https://github.com/arut/nginx-rtmp-module

But it works . If you wanna know if your stream is really 1080p , inspect the js on your browser .

**Comment by daoguey** [comment]
perfect thank you
