### ISSUE TITLE
In the categories the animations run constantly.

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#3852]
Hello,

i think it's a mistake.
If you add the categories to the start page, all animated thumbnails are played. In the columns "Suggested, Trending, Sort by name, Date added" etc. the animation is only started during the mousover. But in the categories the animations run constantly. This makes the page extremely slow when scrolling when you are on the move with little computing power, e.g. B. Mobile devices or laptops, etc. And it is also not very nice to look at, it seems restless and intrusive when all the animations run at the same time.

[Video.zip](https://github.com/WWBN/AVideo/files/5397410/Video.zip)

**Comment by akhilleusuggo** [comment]
Yes , and for very long time this issue is up . The issue is coming from the `infinite-scroll.pkgd` , only after loading new videos , they start playing non-stop ( looping )

**Comment by DanielnetoDotCom** [comment]
is it happening on demo?

**Comment by DanielnetoDotCom** [comment]
Nevermind I just saw the video
