### ISSUE TITLE
Video Resolution Switcher Automatic switch goes off your Internet Speed and ping time

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3854]
This feature will base off your connection speed and ping time and will auto switch for best performance.

Make it an optional selection in the res chooser on the player but make it the default option.

**Comment by DanielnetoDotCom** [comment]
I already thought about it for MP4, but I did not find any efficient way to merge the performance from the client and the server with JS.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Can you add at the least on the plugin switch resolution , a default resolution for the new type of MP4 ?
Because (for me ) , all videos starts with 720p resolution .

**Comment by DanielnetoDotCom** [comment]
I guess the default resolution already exists and you can use 720

![image](https://user-images.githubusercontent.com/18009293/96641304-e5b68480-12fa-11eb-9189-e9505d2bdb5a.png)

**Comment by akhilleusuggo** [comment]
then what will happens to the old type MP4 videos ? Low , SD , HD ?
That is my question . Can we add variantes with comas ? Like `[HD, 720]`

**Comment by JoshWho** [comment]
I see 3 places to put low Sd and HD. Looks good and you can select what u want as default.

**Comment by JoshWho** [comment]
> I already thought about it for MP4, but I did not find any efficient way to merge the performance from the client and the server with JS.

It doesn't necessarily has to be the play, just a component to load with it will be efficient.  Like a image file that is 3 mb or something and compares the dl speed from that.

**Comment by akhilleusuggo** [comment]
@JoshWho I'm talking about the automatic MP4 ( the new encoder option ) . Probably you don't use it .
