### ISSUE TITLE
Tipping option for chat2/live 

### ISSUE THREAD

**Issue by partystreamsk** [WWBN/AVideo#3855]
Time ago when you do a chat 2 i saw tha option that during a live stream users was able to tip streamer, send gift (transfer funds to streamer) . But now i cannot find this. you removed it? thanks

**Comment by DanielnetoDotCom** [comment]
Did you try this https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform#donations

**Comment by partystreamsk** [comment]
Thanks, yes i checked this but the idea is something like transfer funds. For example "User A" is doing live stream and "User B" is watching live stream. If "User B" press donation link button , then he will get an popup where he can put amount of money and after he press Send button, than this amount of money will be transfered to "User A". Will be cool so everything can be inside a site. Thanks

**Comment by DanielnetoDotCom** [comment]
I guess we already have that.

**Comment by partystreamsk** [comment]
ok, how can i set it? Did you understand what i mean? I know that there is an option to transfer money on site but i mean add function to DONATE button. I see that i can only put custom link to donation.

**Comment by partystreamsk** [comment]
Can you tell me how can i do that please? thanks
