### ISSUE TITLE
No videos are saving to my cloud storage WHat CHanged now with the encoders????????????

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3857]
I can't stand this. What got changed this time? WHy does working things keep getting updated when they r not broke and now I have nothing that works?

**Comment by JoshWho** [comment]
I dont get it. IT WAS WORKING BEFORE THE UPDATES WHY IS IT BROKE NOW

**Comment by JoshWho** [comment]
jhpdfjhoierdhike0ohieo-at5ijho-dtojhkrotkjh-o]jthfs

**Comment by JoshWho** [comment]
I have to literally to tests on my site daily I never find out about these changes until after all my users and potential new users tell me that the site doesn't work

**Comment by JoshWho** [comment]
I just went one day without watching my site now I got a website full of videos not playable

**Comment by JoshWho** [comment]
I vote to have a production release of Avideo and do all the experiments on a beta version or something. This can't keep happening to live productions this is terrible.

**Comment by JoshWho** [comment]
Every minute of downtime is disastrous.

**Comment by DanielnetoDotCom** [comment]
this update requires you to update the B2 plugin as well

**Comment by JoshWho** [comment]
B2 has been updated 4 4 days. This just happened  in the last update

**Comment by JoshWho** [comment]
Just did the newest update still doesn't work

**Comment by JoshWho** [comment]
Now the encoder just tried to upload this under someone else user name

**Comment by JoshWho** [comment]
It doesn't even show file sizes when encoding

 <img src="https://static.buddylist.co/encoding.png" style='width:100%;' border="0" alt="Null">

**Comment by JoshWho** [comment]
Anyone here??????????????

**Comment by JoshWho** [comment]
Ahhhhhh WHat the hell Now CHat2 stopped working

**Comment by JoshWho** [comment]
What is going on????????????????????????????

**Comment by akhilleusuggo** [comment]
I don't know what has broke , but I can feel your anger of updates . Because 3 months ago , the YTP-Storage update , literally deleted my /video directory , will all the videos on it , including the configuration.php  , WAS A DISASTER ! 

After 2 weeks , daniel added an update to not delete the /videos directory ...

**Comment by JoshWho** [comment]
He has it working again. SOme bug with the cloud but all seems to be good now.
