### ISSUE TITLE
Separate Production version of Avideo  

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3858]
I really would like a STable Production Release of Avideo without any experiments or anything happening until it is 100% bug free. My Live Production is always broke because of some bug in a new update and that impacts me terribly. 

I can not try to make a website popular if it is always broke.

**Comment by akhilleusuggo** [comment]
I remember we discussed this time ago , but no action . We asked about TLS version . The beta updates for home testing only .

https://github.com/WWBN/AVideo/issues/3079

**Comment by jengajenga** [comment]
this would be a very good thing to have. i personally stay some editions behind as i test the new ones on my server first before i deploy it in full.

**Comment by itdoka** [comment]
It is very necessary for the site to work all the time. Installing the update is like playing roulette, lucky or unlucky
