### ISSUE TITLE
Interrupt/ New Load Request

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3859]
![interrupt_](https://user-images.githubusercontent.com/65451390/96444475-00afc880-1217-11eb-930f-ca5992cbf467.png)

The screenshot is from the demo site. I also still have the same problem. 

What file is causing the interrupt?
Is it the async jobs function in the settings?
What can we do so that every time we open a live video the video loads as a priority?
Can we re-examine the file stats.json.php and see if it is causing the error?

That cancel thing is making the site unreliable because a viewer expects to see something play but is left wondering. Because of that he closes and goes away and says the site is slow.
Is there something that can be done?
Thanks.

**Comment by DanielnetoDotCom** [comment]
this is not a problem.

it depends on your connection. HLS format always updates their playlists so it may happen if you do now download the playlist fast enough.

**Comment by jengajenga** [comment]
Ok. 

Is there any way that the connection can keep trying until it succeeds? On mine, it just shows the player with the loading circle and someone who doesn't know can think it's still trying to load but it has already given up.

What options do we have?

**Comment by DanielnetoDotCom** [comment]
I just made some improvements to the player.

I also update your site, can you please check and let me know if you see any progress?
