### ISSUE TITLE
Protect LiveURL Bug

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3860]
There is a bug with the encrypted live urls.

On VLC, when you open a livestream, the encrypted URL will only play one chunk. By good luck it will play the second chunk. Then after that, it will stop completely.
-Encrypted key example from Demo Site : https://demo.avideo.com/plugin/Live/m3u8.php?live_servers_id=0&uuid=enhMNnIwcDdERFZGQVdxQzFzUkVtdz09

With the normal url, it plays full time all the time.
-Normal url example from Demo Site : https://live.avideo.com:444/live/5c6007fb1880e/index.m3u8

**Comment by DanielnetoDotCom** [comment]
Do you have this option checked?

![image](https://user-images.githubusercontent.com/18009293/96583475-268aab00-12b3-11eb-9080-603f71b81bde.png)

Also you must add some usergroup to the live

![image](https://user-images.githubusercontent.com/18009293/96583644-6a7db000-12b3-11eb-8f3d-9757fe7208bb.png)

with this VLS is not suppose to play

**Comment by jengajenga** [comment]
![live_](https://user-images.githubusercontent.com/65451390/96584876-800ccd00-12e7-11eb-8267-8f3f975571a0.png)

i have option checked. I do not have user groups enabled.

**Comment by DanielnetoDotCom** [comment]
try to enable the user group and then try VLC again.

they do not suppose to play it.
