### ISSUE TITLE
BLOB request

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3863]
![blob_2](https://user-images.githubusercontent.com/65451390/96473579-7ed19680-123a-11eb-9d49-5890345e8ce2.PNG)

What is this blob file? I only see it on chrome-based browsers but it isnt there on FFX. and my site loads faster on ffx.

is it really a necessary file?

**Comment by DanielnetoDotCom** [comment]
the blobs do not come from me, it is the browser

**Comment by jengajenga** [comment]
ok. thanks Dan.
