### ISSUE TITLE
CHAT2 Stopped Working

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#3864]
What is going on? FIrst my encoders broke now Chat2

 <img src="https://static.buddylist.co/chat2error.png" style='width:100%;' border="0" alt="Null">

**Comment by DanielnetoDotCom** [comment]
Can you please check the log file?

**Comment by JoshWho** [comment]
Not sure where the log is. It is the external standalone chat I do not see a log folder in the plugin

**Comment by JoshWho** [comment]
Internal chat server works fine, it is the external saying it is disabled even when I enable it.

**Comment by akhilleusuggo** [comment]
you need to check the logs on `/var/log/apache2/access.log` & `/var/log/apache2/error.log`

**Comment by JoshWho** [comment]
those logs are a mess what am I looking for exactly?

**Comment by akhilleusuggo** [comment]
check the error log when you try to access to it

**Comment by JoshWho** [comment]
I really wish it had its own log. Apache is filling fast right now do to a large scale attack on all my servers.

**Comment by JoshWho** [comment]
Is it working on your site?

**Comment by JoshWho** [comment]
I don't see anything useful here. Looks like it connects fine, still doesn't answer why it is saying it is disabled.

```
[21/Oct/2020:00:46:07 -0500] "GET /Chat2/?room_users_id=1&user=admin&pa              ss=65cf505df77caec079ed6856e8d76885&iframe=1&noFade=1 HTTP/1.1" 200 4350 "https://www.joshwhotv.com/" "Mozilla/5.0               (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
2601:248:8300:67a0:a75f:cd2c:97d9:4b7c - - [21/Oct/2020:00:46:08 -0500] "GET /Chat2/?room_users_id=1&user=admin&pa              ss=65cf505df77caec079ed6856e8d76885&iframe=1&noFade=1 HTTP/1.1" 200 4286 "https://www.joshwhotv.com/" "Mozilla/5.0               (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"

```

**Comment by akhilleusuggo** [comment]
that's the access , what about the error log ?

**Comment by JoshWho** [comment]
--2020-10-21 01:20:42--  https://www.joshwhotv.com/plugin/API/get.json.php?APIName=plugin_parameters
Resolving www.joshwhotv.com (www.joshwhotv.com)... 104.31.87.238
Connecting to www.joshwhotv.com (www.joshwhotv.com)|104.31.87.238|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
get.json.php?APIName=plugin_parameters: Permission denied

Cannot write to 'get.json.php?APIName=plugin_parameters' (Success).
[Wed Oct 21 01:20:42.927706 2020] [php7:notice] [pid 26495] [client 2601:248:8300:67a0:a75f:cd2c:97d9:4b7c:38952] AVideoLog::DEBUG: wget: ERROR the url does not download https://www.joshwhotv.com/plugin/API/get.json.php?APIName=plugin_parameters&APISecret=6fc62ec69b08fa735ac516b595c951b6&plugin_name=Chat2, /var/www/html/YouPHPTube/Chat2/videos/cache/YPTurl_get_contents/2ec1595306a0455da14e7df7f33227aa, referer: https://www.joshwhotv.com/
[Wed Oct 21 01:20:43.124273 2020] [php7:notice] [pid 26495] [client 2601:248:8300:67a0:a75f:cd2c:97d9:4b7c:38952] AVideoLog::DEBUG: Error on getAPI(plugin_parameters, plugin_name=Chat2)(https://www.joshwhotv.com/plugin/API/get.json.php?APIName=plugin_parameters&APISecret=6fc62ec69b08fa735ac516b595c951b6&plugin_name=Chat2), referer: https://www.joshwhotv.com/
[Wed Oct 21 01:20:43.124320 2020] [php7:notice] [pid 26495] [client 2601:248:8300:67a0:a75f:cd2c:97d9:4b7c:38952] PHP Notice:  Trying to get property 'response' of non-object in /var/www/html/YouPHPTube/Chat2/standAlone/AVideoPlugin.php(14) : eval()'d code(1) : eval()'d code on line 12, referer: https://www.joshwhotv.com/
[Wed Oct 21 01:20:43.124550 2020] [php7:notice] [pid 26495] [client 2601:248:8300:67a0:a75f:cd2c:97d9:4b7c:38952] AVideoLog::DEBUG: getObjectData(Chat2) onlineSecondsTolerance: null, referer: https://www.joshwhotv.com/
sh: 1: -O: not found
--2020-10-21 01:20:43--  https://www.joshwhotv.com/plugin/API/get.json.php?APIName=plugin_parameters
Resolving www.joshwhotv.com (www.joshwhotv.com)... 104.31.87.238
Connecting to www.joshwhotv.com (www.joshwhotv.com)|104.31.87.238|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
get.json.php?APIName=plugin_parameters: Permission denied

Cannot write to 'get.json.php?APIName=plugin_parameters' (Success).
[Wed Oct 21 01:20:43.323329 2020] [php7:notice] [pid 28326] [client 2601:248:8300:67a0:a75f:cd2c:97d9:4b7c:30210] AVideoLog::DEBUG: wget: ERROR the url does not download https://www.joshwhotv.com/plugin/API/get.json.php?APIName=plugin_parameters&APISecret=6fc62ec69b08fa735ac516b595c951b6&plugin_name=Chat2, /var/www/html/YouPHPTube/Chat2/videos/cache/YPTurl_get_contents/2ec1595306a0455da14e7df7f33227aa, referer: https://www.joshwhotv.com/
[Wed Oct 21 01:20:43.516648 2020] [php7:notice] [pid 28326] [client 2601:248:8300:67a0:a75f:cd2c:97d9:4b7c:30210] AVideoLog::DEBUG: Error on getAPI(plugin_parameters, plugin_name=Chat2)(https://www.joshwhotv.com/plugin/API/get.json.php?APIName=plugin_parameters&APISecret=6fc62ec69b08fa735ac516b595c951b6&plugin_name=Chat2), referer: https://www.joshwhotv.com/
[Wed Oct 21 01:20:43.516686 2020] [php7:notice] [pid 28326] [client 2601:248:8300:67a0:a75f:cd2c:97d9:4b7c:30210] PHP Notice:  Trying to get property 'response' of non-object in /var/www/html/YouPHPTube/Chat2/standAlone/AVideoPlugin.php(14) : eval()'d code(1) : eval()'d code on line 12, referer: https://www.joshwhotv.com/
[Wed Oct 21 01:20:43.516921 2020] [php7:notice] [pid 28326] [client 2601:248:8300:67a0:a75f:cd2c:97d9:4b7c:30210] AVideoLog::DEBUG: getObjectData(Chat2) onlineSecondsTolerance: null, referer: https://www.joshwhotv.com/

**Comment by JoshWho** [comment]
api secret is not so secret now why I hate putting logs in public view

**Comment by JoshWho** [comment]
No clue what it is calling for apiname=parameters or whatever. Doesn't show it like that when looking at the api docs

**Comment by JoshWho** [comment]
Thank you working good. Daniel figured out a bug with the Stop Bots on cache plugin. Disabled that feature on the cache plugin and now it works good. Thank you @DanielnetoDotCom
