### ISSUE TITLE
Urgent my videos will not load and cant log into encoder network

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#3865]
I recently paid Daniel to set up a second encoder for me and then a network. There was a problem logging into the new encoder but it seems that he fixed it.

But today I could not log into my encoder network at all. Not even manually with my user name and password.

And now "my videos" will not load. This means that nobody can edit or make a video live.

We are essentially dead right now.

I have not done any programming at all myself in over half a year. Daniel was the only one to update anything recently.

I restarted the server and the encoder network is logging in automatically again. But "my videos" never loads so nobody can process new videos or edit existing ones at all.

![My-Videos-Wont-Load](https://user-images.githubusercontent.com/45924889/96482240-be33bf00-1209-11eb-83ed-a58b92e8bc50.jpeg)

**Comment by The-Do-It-Yourself-World** [comment]
Looking at the database, it appears that some videos that were uploading never finished either. They show a "duration" of EE:EE:EE

Daniel, did you update our database the other day?  Because it looks a lot different.

**Comment by The-Do-It-Yourself-World** [comment]
I am checking my server. The videos file folder contains 99,484,407,734 bytes.

I know that I can delete some files in there but I do not know which ones.

This may be the cause of my issues. Maybe. If the hard drive is too full.

Can someone please tell me what files under the "videos" folder I can safely delete?

**Comment by jengajenga** [comment]
according to me, anything that starts with the word "original" is safe to remove. that is a previous livestream segment.

**Comment by The-Do-It-Yourself-World** [comment]
Thanks. I have not had live stream activated yet.

I found the "avideo.log" file which is 1.2GB is size. Can I safely delete that file?

**Comment by DanielnetoDotCom** [comment]
Yes, you can delete the avideo.log

> Thanks. I have not had live stream activated yet.
> 
> I found the "avideo.log" file which is 1.2GB is size. Can I safely delete that file?

Yes you can

> Also there are a lot of ".webp" files. Can I remove them?

No

> There is a thumbnails.tar.gz file that is 41.4 GB in size

Yes, and I am not sure what is it

> There is also youphptube.log file that is 3 GB in size

Yes this is useless now

**Comment by The-Do-It-Yourself-World** [comment]
Thank you. I am deleting these files.

But the site is still not working. "my videos" is still broken so no more videos can be made live or edited.

I tried multiple server resets but it still does not work.

**Comment by DanielnetoDotCom** [comment]
what is in your log file?

did you update or something?

**Comment by The-Do-It-Yourself-World** [comment]
The last thing done was you adding the encoder network. I have not done anything in 6 months at all myself. Where is the log file?

**Comment by The-Do-It-Yourself-World** [comment]
I may be wrong but I think you may have updated the database??? If so, I am using old code with a new database?

**Comment by DanielnetoDotCom** [comment]
I did not touch your streamer

check here for the streamer log
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by The-Do-It-Yourself-World** [comment]
[avideo.log](https://github.com/WWBN/AVideo/files/5405696/avideo.log)


I cant find anything in the log files that may help. I still cannot load "my videos" at all.

**Comment by DanielnetoDotCom** [comment]
Good morning 

I did not check your log yet but I just realize I saw in the past it happening when in the video title or description has some unconventional characters 

You probably can search for a video and you get results.

Not sure the solution but I guess it does not happen anymore on the newest versions . I guess It filter the result now.

Maybe you will need to edit it directly in the database

**Comment by DanielnetoDotCom** [comment]
Hi

I checked your log. I saw a bunch of errors that may  resolve with an update.

I cannot track those errors anymore as long they are not present on the current version.

**Comment by The-Do-It-Yourself-World** [comment]
Yes, I did see in the log file that a video had a mess of unconventional characters in the title. Today, "my videos" is loading but that may be because that video is way down on the list since someone uploaded a mess of videos.

I will update. Thanks.
