### ISSUE TITLE
Configure LIVE plugin

### ISSUE THREAD

**Issue by angry999** [WWBN/AVideo#3866]
Hello, How are you?
I am installing Nginx and Nginx-RTMP but I got the error when running this command.
sudo make && sudo make install
I attached the screenshot.
![error](https://user-images.githubusercontent.com/55845113/96531846-8bfd7e00-1258-11eb-8ad8-f222694353c4.png)
Please let me know how to fix this issue.
Thanks in advance

**Comment by akhilleusuggo** [comment]
You're not following the instruction of the installation . If you don't follow , please write your issue on the nginx-rtmp project .

**Comment by angry999** [comment]
I am following the instruction of the installation.

sudo apt-get install -y build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev php7.4-xml
sudo mkdir ~/build && cd ~/build && sudo git clone git://github.com/arut/nginx-rtmp-module.git
sudo wget http://nginx.org/download/nginx-1.18.0.tar.gz && sudo tar xzf nginx-1.18.0.tar.gz
cd nginx-1.18.0 && sudo ./configure --with-http_ssl_module --with-http_stub_status_module --add-module=../nginx-rtmp-module
sudo make && sudo make install

But getting error on sudo make

**Comment by jengajenga** [comment]
> I am following the instruction of the installation.
> 
> sudo apt-get install -y build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev php7.4-xml
> sudo mkdir ~/build && cd ~/build && sudo git clone git://github.com/arut/nginx-rtmp-module.git
> sudo wget http://nginx.org/download/nginx-1.18.0.tar.gz && sudo tar xzf nginx-1.18.0.tar.gz
> cd nginx-1.18.0 && sudo ./configure --with-http_ssl_module --with-http_stub_status_module --add-module=../nginx-rtmp-module
> sudo make && sudo make install
> 
> But getting error on sudo make

what error? it may be you have not installed the make function. install make
sudo apt-get update -y
sudo apt-get install -y make

**Comment by akhilleusuggo** [comment]
Where have you seen those configs ? Not on the wiki that I'm aware of ...
Follow this , the issue to start with is your version 1.18 ....

https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

If you follow will work . 

If you wanna use the config that you're using  , open issue on RTMP-NGINX project if the issue persists .

**Comment by angry999** [comment]
It is resolved. thank you
