### ISSUE TITLE
User/ Account Control Options

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3868]
Please look into having an option for an admin to create different types of users e.g,
User 1 - has access to options ABC
User 2 - has access to options ABCDE
User 3 - has access to options ABCDEFGHIJ

That way when we want to move our users, we can move them as we wish. Some examples would be:
USER 1 can be Tech Support but not Admin. 
USER 2 can be Client but without PlayerURL. 
USER 3 can be Client with RESTREAM capability etc.

User control should be based on
1. Paid or not paid
2. Admin elevation of users manually for whatever reason he chooses

**Comment by DanielnetoDotCom** [comment]
the type of users you described are very specific.

we do not have it right now. I am not saying it is impossible but it will require a lot of code.

**Comment by jengajenga** [comment]
User groups sorted this issue out for me.
