### ISSUE TITLE
verify function phoning home to youphptube.com

### ISSUE THREAD

**Issue by dbmasters** [WWBN/AVideo#3869]
what is the purpose for the phone home in Streamer.php in the encoder? My error logs hit that verify, it does, but then processing stops in the encoder...

**Comment by DanielnetoDotCom** [comment]
"phone home in Streamer.php"?? what?

**Comment by dbmasters** [comment]
function verify() {
            ini_set('default_socket_timeout', 5); 
            $url = $this->getSiteURL();
            $cacheFile = sys_get_temp_dir() . "/" . md5($url) . "_verify.log";
            $lifetime = 3600; //1 hour
            error_log("Verification Start {$url}");
            $verifyURL = "";
            if (!file_exists($cacheFile) || (time() > (filemtime($cacheFile) + $lifetime))) {
                error_log("Verification Creating the Cache {$url}");
                $verifyURL = "https://search.youphptube.com/verify.php?url=" . urlencode($url);
                $result = url_get_contents($verifyURL);
                file_put_contents($cacheFile, $result);
            } else {
                error_log("Verification GetFrom Cache {$url}");
                $result = file_get_contents($cacheFile);
            }
            error_log("Verification Response ($verifyURL): {$result}");
            return json_decode($result);
        }

**Comment by DanielnetoDotCom** [comment]
it verifies the streamer status so you can use the public features, encoder, meet, and others

**Comment by dbmasters** [comment]
OK, cool, thanks. Just saw it in some error logs and got to wondering...now everything is uploading, but it dies when it tries to move the video from encoder to streamer...trying to figure that one out now...this is a really neat system, but some issues are very difficult to debug.

**Comment by jengajenga** [comment]
but why is it phoning home? phone homes are used to guard against piracy.
can it phone my own domain rather than phone your domain?

**Comment by DanielnetoDotCom** [comment]
I have no idea what "phoning home" means
