### ISSUE TITLE
Question about features

### ISSUE THREAD

**Issue by wildmaster84** [WWBN/AVideo#3872]
Are we no linger able to submit feature requests or am i missing something while trying to write the request? The button is not clickable to submit the feature request.

**Comment by akhilleusuggo** [comment]
It does work for me . Try a new browser or clear the browser cache

**Comment by wildmaster84** [comment]
i tried a new browser and clearing my cache but i still can't submit the request

**Comment by akhilleusuggo** [comment]
oh , I see what you're talking about . Happens to me too , my bad , saving the request is not working . 
I don't know to be honest . Maybe @DanielnetoDotCom disabled it .

**Comment by DanielnetoDotCom** [comment]
I did not, where did you see that?

on my side, as soon as I add a title the button enable

**Comment by wildmaster84** [comment]
ok nev im just a complete idot x.x
