### ISSUE TITLE
Front page shrinked small and words 

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#3873]
Greetings, I have a problem with my since this white background started showing with home written on top and even if i change the theme but the white  background remains with small words. How to I remove this error?
![screen shrinked](https://user-images.githubusercontent.com/72950503/96706227-2938df00-134b-11eb-9d8c-63ee31077e98.png)

**Comment by DanielnetoDotCom** [comment]
Disable the combine sites plugin

**Comment by mrgodgiven** [comment]
thanks it worked
