### ISSUE TITLE
How to clean uninstall AVideo and AVide-encoder

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#3874]
**Describe the question**
A clear and concise description of what is your question.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by hnagasawa** [comment]
Please tell me how to clean unistall AVideo and AVideo-Encoder

**Comment by akhilleusuggo** [comment]
`sudo rm -r /var/www/html/AVideo & sudo rm -r /var/www/html/AVideo-Encoder`

Then you need to delete the databases that have been created . 
Done

**Comment by JoshWho** [comment]
Simply deleting it and the database is all you need to do.
