### ISSUE TITLE
Email smtp setup shows code error

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#3876]
Greetings . I see this error that says code Error when I try to test my mail or send emails.
![email error](https://user-images.githubusercontent.com/72950503/96727272-b9851d00-1367-11eb-8142-ec835527a53f.png)

**Comment by JoshWho** [comment]
Either your SMTP is not using the correct port or you have the wrong username and pass.

**Comment by DanielnetoDotCom** [comment]
try this https://tutorials.avideo.com/video/82/setup-gmail-smtp-with-2fa

**Comment by mrgodgiven** [comment]
![Email error Google](https://user-images.githubusercontent.com/72950503/96906801-33440600-144f-11eb-849a-ae0a71dfc6c6.png)
I recieve this error from google

**Comment by mrgodgiven** [comment]
I figured that I had to enable twofactor and then see the option for App password.
