### ISSUE TITLE
Using a video card to encode video

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#3877]
I want to use a video card instead of a processor for faster video encoding, tell me how to change FFMPEG. And what else needs to be done to make the video encoded faster.

**My server:** Xeon e5 2420 processor (6 cores, 12 threads), 24 GB of ddr3 RAM (works in three-channel mode), video card radeon rx 570 8gb
I can add a second Xeon e5 2420 processor

**Comment by akhilleusuggo** [comment]
just change the ffmpeg line from libx264 to what ever codec you wanna be using . No idea about radeons . You may wanna ask on some ffmpeg/amd projects .

**Comment by palich91** [comment]
> You may wanna ask on some ffmpeg/amd projects .

amd will be able to encode video faster than CPU?
Or should you buy NVIDIA?
If amd can handle this, how do I set up FFMPEG? I have not encountered this and I need help

**Comment by akhilleusuggo** [comment]
Read what I've said before . This question should be somewhere in an AMD topic . I have 3 Nvidia GPU's . I could have gave you a tip about AMD , but I have no idea . 

The encoder is called `hevc_amf` for sure GPU ( for x265 ) , and  `h264_amf` ( for x264 ) .
To start , try somthing like ; `ffmpeg -i input.mp4 -c:v h264_amf -usage transcoding -quality balanced -f mp4 output.mp4`

More info : `ffmpeg -h full`

**Comment by palich91** [comment]
I plan to buy an Nvidia video card, tell me which one is better to choose for encoding video in HLS.
And tell me how it should look in the ffmpeg encoder setting
