### ISSUE TITLE
Live Streaming Stuck at Processing

### ISSUE THREAD

**Issue by Coder1512** [WWBN/AVideo#3878]
When I go to my broadcast live video, it's stuck at processing. Any solutions? 
https://ibb.co/K6RfkfS

**Comment by JoshWho** [comment]
download it from the tmp folder and reupload it.

**Comment by Coder1512** [comment]
> download it from the tmp folder and reupload it.

Can you give me some instructions on how to do that?

**Comment by JoshWho** [comment]
In your web directory right before your www you should see a tmp folder.  All live recordings go there to be encoded. 

usually in /var/www/tmp

Just look for the most recent file and download it to your computer.

**Comment by Coder1512** [comment]
> In your web directory right before your www you should see a tmp folder. All live recordings go there to be encoded.
> 
> usually in /var/www/tmp
> 
> Just look for the most recent file and download it to your computer.

got it thank you. Is there anyway to make this process happen automatically so if another user who doesnt have access to my tmp directory can still live stream?

**Comment by Coder1512** [comment]
So it seems like my video isn't even being broadcasted when looking from another device.

**Comment by Coder1512** [comment]
It seems that the processing thing was for the live chat, but my stream is still appearing offline even though I entered everything correctly into OBS.
