### ISSUE TITLE
How do I access my user's live page

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3881]
I would like to access this page AS a client for support purposes. I have realised there is no way to edit stream info in a user account without the specific user having to log in.

Is there anyway?

![stream_page](https://user-images.githubusercontent.com/65451390/96777165-a703f580-13f2-11eb-9b74-139f477bf8c2.png)

I want to access this page. Now the URL i can put in https://mydomain/plugin/Live/?users_id=USERIDNUMBER and still enter,, but if I edit any info, and press save, then it saves it under the ADMIN name rather than under the USER'S name. Is there a way?

@akhilleusuggo @DanielnetoDotCom 

Thanks guys,

**Comment by DanielnetoDotCom** [comment]
Correct, each user has to edit his own page

**Comment by jengajenga** [comment]
thank you Dan.
