### ISSUE TITLE
Auto Plugin Updater

### ISSUE THREAD

**Issue by wildmaster84** [WWBN/AVideo#3883]
It would help a lot of there was a way to update the plugins from the admin panel or maybe a button that says theres an update available.

**Comment by TLCReuver** [comment]
".... maybe a button that says theres an update available." ---> does exist in one of the last updates.
![Snap2](https://user-images.githubusercontent.com/39981177/96891099-9bfba480-1488-11eb-967d-638547d6151f.jpg)
