### ISSUE TITLE
Change of Channel Name

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3884]
@DanielnetoDotCom @akhilleusuggo 

There seems to be a change in the Channel Name which is affecting the embedding. I see my channel looks like this

THIS IS MY CHANNEL
now looks like 
THISISMYCHANNEL

It has broken ALL the embeds. When I try to edit it, it says save but it doesn't make any change. Kindly assist as my users are going to bother me today.

I'm on latest version,

Thanks

**Comment by DanielnetoDotCom** [comment]
what exactly embed link are you talking about?
