### ISSUE TITLE
AVideo Hangs When Clicking "LIVE" button.

### ISSUE THREAD

**Issue by ZandercraftGames** [WWBN/AVideo#3885]
**Describe the bug**
After following the wiki on how to install the live RTMP plugin and it's systems, with the stat page working, the site will hang and become fully inaccessible without an apache service restart.

**To Reproduce**
1. Follow instructions at https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer
2. Follow instructions at https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server
3. Leave plugin options as preconfigured
4. Reload the page and click the "LIVE" button.
5. Whole site hangs.

**Expected behavior**
Should go to the live plugin's page that shows stream key and url along with stream setup.

NOTE: The configuration page for the plugin (http://192.168.2.206/AVideo/admin/plugin/Live/view/editor.php) does not freeze the site.

**Error Logs**
```
[21-Oct-2020 23:32:18 America/New_York] AVideoLog::DEBUG: Live::getStatsObject RTMP Server (http://192.168.2.206:8080/stat) is NOT responding we will wait less from now on => live_servers_id = (0)  SCRIPT_NAME: /AVideo/plugin/Live/stats.json.php
[21-Oct-2020 23:32:18 America/New_York] AVideoLog::DEBUG: Live::getStatsObject RTMP Server (http://192.168.2.206:8080/stat) is respond again => live_servers_id = (0)  SCRIPT_NAME: /AVideo/plugin/Live/stats.json.php
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 86.0.4240.111 (Official Build) (64-bit) (cohort: 86_Win_111)

**Comment by DanielnetoDotCom** [comment]
the error log explains

make sure you have your nginx running here http://192.168.2.206:8080/stat

**Comment by ZandercraftGames** [comment]
@DanielnetoDotCom I reinstalled the system on a VPS and it worked. The issue, however, was that that page actually was fully accessible and worked.
