### ISSUE TITLE
Can not open AVideo-Encoder from AVideo(Streamer)

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#3886]
Can not open AVideo-Encoder from AVideo(Streamer)
![stearmer1](https://user-images.githubusercontent.com/46562199/96839643-6b197080-1484-11eb-966a-a6b07ee8b1e9.png)
I close this tab and I open new tab
![steramer2](https://user-images.githubusercontent.com/46562199/96839846-ac118500-1484-11eb-9f0a-f90b03ea590d.png)
I enter "http://150.23.145.10/AVideo-Encoder/"
![steamer3](https://user-images.githubusercontent.com/46562199/96840133-04488700-1485-11eb-9793-8d0fd0927448.png)
I can login AVideo-Encoder 
I checked AVideo-Encoder's log
no error
I tried 22-OCT-2020 about 16:20
[avideo.log](https://github.com/WWBN/AVideo/files/5420962/avideo.log)
AVideo Ver 9.6
AVideo-ENcoder Ver3.3

**Comment by DanielnetoDotCom** [comment]
Can you reproduce it on demo site?

**Comment by hnagasawa** [comment]
Dear Daniel

 > Can you reproduce it on demo site?
Yes. I access your demo site form IE11.(I tried 22-Oct-2020 19:53-19:55 JST)

I can reproduce it on your demo site

Please inform us soon.

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
I just sent an update to the encoder. try now

**Comment by hnagasawa** [comment]
Dear Daniel

 > I just sent an update to the encoder. try now
  It works.

**Comment by hnagasawa** [comment]
Dear Daniel

When you upload update new encoder, Please inform us.
Our customer's enviroment can not access github.
Please tell me how to update.

For example you teach me 2-Sep-2020
To WWBN/AVideo, hnagasawa, Author

I am not sure what that means, but you can clone the project somewhere else,

cd /tmp && git clone https://github.com/WWBN/AVideo.git

then move the videos directory to the cloned folder,

mv /var/www/html/AVideo/videos /tmp/AVideo/videos

double-check your folder was moved

ls /tmp/AVideo/videos

then delete the old folder and move the new cloned on his place

rm -R /var/www/html/AVideo && mv /tmp/AVideo /var/www/html/AVideo

this should do the trick

Reagards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
the update is already on github

**Comment by hnagasawa** [comment]
Dear Daniel

Do you recommand to update both AVideo and AVideo-Encoder ?

Regards
Hiroshi Nagasawa

**Comment by hnagasawa** [comment]
Dear Daniel

By the way, Please send me latest Version LoginLDAP_DYNA.
Because My PC's HDD Crashed 30-Sep-2020(JST)

Reagrds
Hiroshi Nagasawa

**Comment by hnagasawa** [comment]
Dear Daniel

I upload mpeg file AVideo-Encoder our AVideo and AVideo-encoder.
mpeg file size 23.6MB
file name is "Whitesnake - Is This Love (Official Music Video)"
Its status is encoding
Do not finish encode.
I tried your demo site
Same error occured
(I tried 22-Sep-2020 about 23:55 (JST)

Please check soon.

Regards

**Comment by hnagasawa** [comment]
Dear Daniel

I upload mpeg file AVideo-Encoder our AVideo and AVideo-encoder after 
fix version #3886.
mpeg file size 23.6MB
file name is "Whitesnake - Is This Love (Official Music Video)"
Its status is encoding
Do not finish encode.
I tried your demo site
Same error occured
(I tried 22-Sep-2020 about 23:55 (JST)

Please check soon.

Regards

**Comment by hnagasawa** [comment]
Dear Daniel

I check your change our AVideo and your demo site.
I think fix almost bugs fix.
Please check contine.
I will run git clone 23-Oct-2020 8:00(JST)

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
Hi, I think you are mixing problems here.

If you have a problem encoding a specific file please open a new issue with the problem.

**Comment by hnagasawa** [comment]
Dear Daniel

I checked your change our AVideo and your demo site (23-OCT-2020 about
3:00(JST).

I ran "git clone" both.

I checked your change our AVideo and your demo site (23-OCT-2020 about
8:00(JST) and 9:00AM(JST).

I can not login encoder from AVideo  both our AVideo(I ran git pull both
about 7:30(JST) and your demo site.
Please attached pic.

You updated both about 4 hours ago(Japan time is 5:00 AM)

Please check soon.

Regards
Hiroshi Nagasawa

2020年10月23日(金) 4:37 Daniel Neto <notifications@github.com>:
