### ISSUE TITLE
upload file with paid content

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#3888]
When uploading an mp4 file from AVideo-encoder, the paid cotent is not displayed as free. Please tell me which parameter to operate.

**Comment by hnagasawa** [comment]
![stereamer4](https://user-images.githubusercontent.com/46562199/96856739-38c63e00-1499-11eb-8e3b-ac5be6021ca8.png)

**Comment by akhilleusuggo** [comment]
change the label , and clear the cache .
Plugins, CustomizeAdvanced (CustomizeAdvanced) , 

![image](https://user-images.githubusercontent.com/52116577/96863213-318a3a80-146f-11eb-8fe7-15fd6d7fb22e.png)
