### ISSUE TITLE
Where is the upload button?

### ISSUE THREAD

**Issue by qome** [WWBN/AVideo#3889]
**Describe the question**
I only have a "encode" button and an "embed" button.

**Screenshots**
![image](https://user-images.githubusercontent.com/58382620/96864937-d6385800-142e-11eb-867a-bcda45fee742.png)

**Comment by mrgodgiven** [comment]
The Encode is your upload Button, Some of us has an upload button because we customized it and and whilst installing changed encoder to upload or rather renamed encorder, so don't be confused you got it.
