### ISSUE TITLE
Error trying to create Live from playlist

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3890]
When clicking the Play Live button I get the following error/

{"error":false,"msg":"","videosListToLive":"https:\/\/fetube.flatearth.co.il\/Encoder\/videosListToLive?playlists_id=722&APISecret=6fc62ec69b08fa735ac516b595c951b6&webSiteRootURL=https%3A%2F%2Ffetube.flatearth.co.il%2F&user=streamer&pass=1b922a8a80ef117d0d79bdcacd29f943&liveKey=5f81a39c93c6a&rtmp=rtmp%3A%2F%2Ffetube.flatearth.co.il%2F"}

![Screen Shot 5781-02-04 at 15 43 57](https://user-images.githubusercontent.com/58882903/96873405-8fbe1a00-147d-11eb-9c3e-0c04391a84b1.jpg)

**Comment by DanielnetoDotCom** [comment]
The play live button is not working yet. please ignore it for now or disable it on the Playlist plugin parameters
