### ISSUE TITLE
Can not encode mpg file

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#3891]
I upload mpeg file AVideo-Encoder our AVideo and AVideo-encoder after Update AVideo and AVideo-encoder

mpeg file size 23.6MB
file name is "Whitesnake - Is This Love (Official Music Video)"
Its status is encoding
Do not finish encode.
I tried your demo site
Same error occured
(I tried 22-Sep-2020 about 23:55 (JST)
![steamer7](https://user-images.githubusercontent.com/46562199/96894725-c8361600-14c6-11eb-8142-57f9a8c26f02.png)

**Comment by DanielnetoDotCom** [comment]
Make sure the video filename does not have special characters.

If the error persists, share the file so we can test
