### ISSUE TITLE
sitemap error

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3892]
```
siteMap: done  SCRIPT_NAME: /objects/configurationGenerateSiteMap.json.php
[22-Oct-2020 15:25:43 UTC] AVideoLog::DEBUG: siteMap: pregreplace1 fail  SCRIPT_NAME: /objects/configurationGenerateSiteMap.json.php
```

I'm not enable to generate the sitemap .Also when the process finishes , doesn't say anything . Just keep looping the process bar.

![image](https://user-images.githubusercontent.com/52116577/96895039-a6bc3680-1494-11eb-9e8c-8bfbfd90a270.png)

**Comment by Donnerstein** [comment]
This happens when quotation marks appear in the title or description of a post. I think there is a problem with the masking.

**Comment by akhilleusuggo** [comment]
Oh , I see . Thanks for the feedback . Need to take a look at that .

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Any fix to this ? I'm not able to find what @Donnerstein said . I mean , too many video to check manually impossible .

That's why I've asked about this ; https://github.com/WWBN/AVideo/issues/3856

At the least will show the error log .

**Comment by DanielnetoDotCom** [comment]
If the sitemap is generated and it keeps the process bar, it is a JS error.

check the JS console, and also the response from the XHR request
