### ISSUE TITLE
Enable Restream per User

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3895]
@DanielnetoDotCom 

Is it possible to enable Restream per user?

I see an admin can allow a user to create meet, and also can allow a user to stream, and to upload. But restream is enabled for every user by default. Can you add a commit to that one kindly please? This will save us some server resources.

Thank you.

**Comment by DanielnetoDotCom** [comment]
> Is it possible to enable Restream per user?
> I see an admin can allow a user to create meet, and also can allow a user to stream, and to upload. But restream is enabled for every user by default. Can you add a commit to that one kindly, please? This will save us some server resources.

I see, you do not want to enable restream for all users, you want to select them.

currently, we do not have this option and it will require some code to make it work,

we can add it in the future, but remember you can remove the right to the user to use your livestreamer server.

![image](https://user-images.githubusercontent.com/18009293/97001044-14f10f80-150e-11eb-8ad6-9a6ed94f0372.png)

**Comment by jengajenga** [comment]
> > Is it possible to enable Restream per user?
> > I see an admin can allow a user to create meet, and also can allow a user to stream, and to upload. But restream is enabled for every user by default. Can you add a commit to that one kindly, please? This will save us some server resources.
> 
> I see, you do not want to enable restream for all users, you want to select them.
> 
> currently, we do not have this option and it will require some code to make it work,
> 
> we can add it in the future, but remember you can remove the right to the user to use your livestreamer server.
> 
> ![image](https://user-images.githubusercontent.com/18009293/97001044-14f10f80-150e-11eb-8ad6-9a6ed94f0372.png)

Exactly. I would want to select them so that selected clients can restream. I know I can restrict but all my users are able to stream. i just don't want all of them to restream.

looking forward to this addition. :-)
