### ISSUE TITLE
Log File 404 Page

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#3897]
When I try to access log file from the menu I get a 404. 
Updated to 9.6 and plugins are updated as well.

Any suggestions on how I can correct this issue?

![logfile](https://user-images.githubusercontent.com/739391/97017055-79ff3200-151b-11eb-9f39-80aeb87a224f.png)

![logfile-404](https://user-images.githubusercontent.com/739391/97017091-84b9c700-151b-11eb-9a20-07b5b37daf7f.png)

**Comment by DanielnetoDotCom** [comment]
mod_rewrite not installed, or wrong .htaccess

**Comment by DanielnetoDotCom** [comment]
Hi

If the site is hosted by me , there is no cost to fix it.

If it is not you can hire me for 1 hour support and I will fix it. Please email me at developer@youphptube.com

**Comment by willpower68** [comment]
@DanielnetoDotCom 

Yes, the site is hosted by you.  I will email you.
