### ISSUE TITLE
Since Latest Update, Audio pages play audio twice at once

### ISSUE THREAD

**Issue by JSY-Ben** [WWBN/AVideo#3899]
Hi there. Thanks as usual for the great software.

I have just updated my AVideo installation, and since i have, when i open pages with audio-only content, the audio seems to play twice. If you press pause, the second audio stops, but the first audio carries on.

Example here:

https://hightube.highlands.ac.uk/streamer/v/1476?channelName=5b469395ef810

Many thanks 👍

**Comment by DanielnetoDotCom** [comment]
Hi

I test your link here and it works fine.

can you please make sure you clear your browser cache and also the system cache?

**Comment by JSY-Ben** [comment]
Hey. Thanks for quick reply.

Have done. I seem to be able to recreate it on Mac Safari, Chrome and PC Edge, but Mac Firefox seems ok. All caches and such cleared, including first page and AVideo cache itself.

**Comment by DanielnetoDotCom** [comment]
Maybe I did not understand what is wrong.
I am using chrome and I did not see anything wrong.

**Comment by JSY-Ben** [comment]
If you leave the clip play for about 10 seconds, it starts to play a second time, and when you press stop, one of them continues to play no matter what.

**Comment by DanielnetoDotCom** [comment]
I go this to happen only once (no idea why)

But could not make it happen again.

**Comment by crishyj** [comment]
Hello, DanielnetoDotCom.
I have the same issues.
I upload the Audio file from the encoder.
But it plays twice when I click it on my own AVideo platform.
When I pause the playing audio, I can hear the original audio.
But I can hear the duplicated sound when playing the audio file on the player.
Please let me know the solution.
Here is an example:
https://embellisherstream.com/video/11/telling-your-course-as-a-story?channelName=Publisher_5fa66e9f1aeb3
![2020-11-09_14-06-57](https://user-images.githubusercontent.com/45354657/98502316-10aa4d80-2295-11eb-8f31-07fd12e69f38.png)
Best regards.

**Comment by JSY-Ben** [comment]
I've noticed it doesn't do it if you enable the wavesurfer plugin, but I keep wavesurfer disabled because it can be very slow to load long Audio files.

**Comment by crishyj** [comment]
Thanks for your quick reply.
But I can't find the above wavesurfer plugin.
How can I find it?
Please let me know.

**Comment by JSY-Ben** [comment]
Hi there.

It is already installed, just go to the customizeAdvanced plugin in the Plugins section, and the option enableWavesurfer should enable it. However i've noticed that its quite slow to load, especially with long form audio like podcasts, but worth testing.

**Comment by DanielnetoDotCom** [comment]
I am trying to improve the autoplay, please check if this update made any difference

**Comment by DanielnetoDotCom** [comment]
I guess I found the issue. it should be good now.

**Comment by JSY-Ben** [comment]
Working a treat now, thank you :)
