### ISSUE TITLE
YouTube-dl has received a DMCA takedown from RIAA

### ISSUE THREAD

**Issue by DanielnetoDotCom** [WWBN/AVideo#3900]
https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md/

Youtube-DL is down from Github, I am not sure yet what will be the future of this wonderful tool that help us to get some content.

https://yt-dl.org/downloads/latest/youtube-dl

https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md/

**Comment by ethancedwards8** [comment]
I got the archives off of archive.org, I'm currently working on getting them to a self hosted gitea instance. Hopefully we can pull something together to revive this project. @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
https://pypi.org/project/youtube_dl/

[youtube_dl-2020.9.20.tar.gz](https://github.com/WWBN/AVideo/files/5431732/youtube_dl-2020.9.20.tar.gz)

**Comment by ethancedwards8** [comment]
https://gitea.althatech.com/eedwards/youtube-dl-HEAD

**Comment by ethancedwards8** [comment]
https://code.hackerspace.pl/q3k/youtube-dl It appears someone has did the job for us, here's a 6 day old repo. It's the most up to date one I've found. You can also find the release zips and tarbells on archive.org.

**Comment by JoshWho** [comment]
The only thing wrong is they list copyrighted names. This is the same case Utorrent and EMule faced. It is a tool for all not just YT and lots of legit users use it for their own videos. The IRAA case will not hold.
