### ISSUE TITLE
Some of the HLS videos don't work

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3902]
After updating VideoHLS plugin, some of my HLS videos keep repeating error in console and the videos won't start:

![image](https://user-images.githubusercontent.com/63721378/97077783-623cb200-15de-11eb-95db-00f60f7d0bda.png)

Also the resolution switcher button is missing on video bar..

**Comment by tonuzo** [comment]
I'm sorry, I cleared the cache and videos started playing normally. 

But the resolution switcher button is still missing..

**Comment by DanielnetoDotCom** [comment]
Please update the streamers and the plugins
