### ISSUE TITLE
OFFLINE badge on live player when online, videos do not autoplay since update to 9.6, cannot save sitemap.

### ISSUE THREAD

**Issue by s7ntax** [WWBN/AVideo#3903]
When a stream is live the player still shows OFFLINE in the top left corner of the video player. 

Also I had "Autoplay Video on Load Page" turned on but since updating to 9.6 it no longer auto plays the videos.

I have cleared the first page cache and cache directory which complete but when i try to generate the sitemap it gives an error "We could not save the sitemap"

Some logs

tail /var/www/arpradiolive.com/YouPHPTube/videos/avideo.log

`[24-Oct-2020 13:16:03 Europe/Berlin] PHP Warning:  file_put_contents(/var/www/arpradiolive.com/YouPHPTube/sitemap.xml): failed to open stream: Permission denied in /var/www/arpradiolive.com/YouPHPTube/objects/configurationGenerateSiteMap.json.php on line 27
[24-Oct-2020 13:16:23 Europe/Berlin] AVideoLog::DEBUG: siteMap: start SCRIPT_NAME: /objects/configurationGenerateSiteMap.json.php
[24-Oct-2020 13:16:23 Europe/Berlin] PHP Notice:  Undefined index: rowCount in /var/www/arpradiolive.com/YouPHPTube/objects/functions.php on line 2524
[24-Oct-2020 13:16:23 Europe/Berlin] AVideoLog::DEBUG: siteMap: rowCount   SCRIPT_NAME: /objects/configurationGenerateSiteMap.json.php
[24-Oct-2020 13:16:23 Europe/Berlin] AVideoLog::DEBUG: siteMap: getAllUsers 2 SCRIPT_NAME: /objects/configurationGenerateSiteMap.json.php
[24-Oct-2020 13:16:23 Europe/Berlin] AVideoLog::DEBUG: siteMap: getAllCategories 2 SCRIPT_NAME: /objects/configurationGenerateSiteMap.json.php
[24-Oct-2020 13:16:23 Europe/Berlin] AVideoLog::DEBUG: siteMap: getAllVideos 1 SCRIPT_NAME: /objects/configurationGenerateSiteMap.json.php
[24-Oct-2020 13:16:23 Europe/Berlin] AVideoLog::DEBUG: siteMap: done  SCRIPT_NAME: /objects/configurationGenerateSiteMap.json.php
[24-Oct-2020 13:16:23 Europe/Berlin] PHP Warning:  file_put_contents(/var/www/arpradiolive.com/YouPHPTube/sitemap.xml): failed to open stream: Permission denied in /var/www/arpradiolive.com/YouPHPTube/objects/configurationGenerateSiteMap.json.php on line 27
[24-Oct-2020 13:16:46 Europe/Berlin] AVideoLog::DEBUG: im_resizeV2: /var/www/arpradiolive.com/YouPHPTube/videos/cache/_jpg_5f940d1e5c827.jpg, /var/www/arpradiolive.com/YouPHPTube/videos/cache/og_200X200.jpg, 200, 200, 100 SCRIPT_NAME: /view/configurations.php`

tail -n 200 -f /usr/local/nginx/logs/error.log

`2020/10/24 13:05:20 [error] 37616#0: *1 open() "/HLS/live/5f833948ec2a7/index.m3u8" failed (2: No such file or directory), client: 86.29.76.152, server: arpradiolive.com, request: "GET /live/5f833948ec2a7/index.m3u8 HTTP/1.1", host: "arpradiolive.com:444", referrer: "https://arpradiolive.com/live/0/ARPRadioLive&embed=1"
2020/10/24 13:05:27 [error] 37616#0: *1 open() "/HLS/live/5f833948ec2a7/index.m3u8" failed (2: No such file or directory), client: 86.29.76.152, server: arpradiolive.com, request: "GET /live/5f833948ec2a7/index.m3u8 HTTP/1.1", host: "arpradiolive.com:444", referrer: "https://arpradiolive.com/live/0/ARPRadioLive&embed=1"
2020/10/24 13:05:34 [error] 37616#0: *1 open() "/HLS/live/5f833948ec2a7/index.m3u8" failed (2: No such file or directory), client: 86.29.76.152, server: arpradiolive.com, request: "GET /live/5f833948ec2a7/index.m3u8 HTTP/1.1", host: "arpradiolive.com:444", referrer: "https://arpradiolive.com/live/0/ARPRadioLive&embed=1"
2020/10/24 13:05:41 [error] 37616#0: *1 open() "/HLS/live/5f833948ec2a7/index.m3u8" failed (2: No such file or directory), client: 86.29.76.152, server: arpradiolive.com, request: "GET /live/5f833948ec2a7/index.m3u8 HTTP/1.1", host: "arpradiolive.com:444", referrer: "https://arpradiolive.com/live/0/ARPRadioLive&embed=1"
2020/10/24 13:05:48 [error] 37616#0: *1 open() "/HLS/live/5f833948ec2a7/index.m3u8" failed (2: No such file or directory), client: 86.29.76.152, server: arpradiolive.com, request: "GET /live/5f833948ec2a7/index.m3u8 HTTP/1.1", host: "arpradiolive.com:444", referrer: "https://arpradiolive.com/live/0/ARPRadioLive&embed=1"
2020/10/24 13:05:55 [error] 37616#0: *1 open() "/HLS/live/5f833948ec2a7/index.m3u8" failed (2: No such file or directory), client: 86.29.76.152, server: arpradiolive.com, request: "GET /live/5f833948ec2a7/index.m3u8 HTTP/1.1", host: "arpradiolive.com:444", referrer: "https://arpradiolive.com/live/0/ARPRadioLive&embed=1"
2020/10/24 13:06:02 [error] 37616#0: *1 open() "/HLS/live/5f833948ec2a7/index.m3u8" failed (2: No such file or directory), client: 86.29.76.152, server: arpradiolive.com, request: "GET /live/5f833948ec2a7/index.m3u8 HTTP/1.1", host: "arpradiolive.com:444", referrer: "https://arpradiolive.com/live/0/ARPRadioLive&embed=1"
2020/10/24 13:06:09 [error] 37616#0: *1 open() "/HLS/live/5f833948ec2a7/index.m3u8" failed (2: No such file or directory), client: 86.29.76.152, server: arpradiolive.com, request: "GET /live/5f833948ec2a7/index.m3u8 HTTP/1.1", host: "arpradiolive.com:444", referrer: "https://arpradiolive.com/live/0/ARPRadioLive&embed=1"
2020/10/24 13:06:16 [error] 37616#0: *1 open() "/HLS/live/5f833948ec2a7/index.m3u8" failed (2: No such file or directory), client: 86.29.76.152, server: arpradiolive.com, request: "GET /live/5f833948ec2a7/index.m3u8 HTTP/1.1", host: "arpradiolive.com:444", referrer: "https://arpradiolive.com/live/0/ARPRadioLive&embed=1"
2020/10/24 13:06:22 [info] 37616#0: *35 client connected '86.29.76.152'
2020/10/24 13:06:22 [info] 37616#0: *35 connect: app='live' args='p=694c321d9867164cc654bec6304444df?authmod=adobe&user=ARP' flashver='FMLE/3.0 (compatible; Larix/1.0' swf_url='' tc_url='rtmp://arpradiolive.com:1935/live?p=694c321d9867164cc654bec6304444df?authmod=adobe&user=ARP' page_url='' acodecs=1028 vcodecs=128 object_encoding=0, client: 86.29.76.152, server: 0.0.0.0:1935
2020/10/24 13:06:22 [info] 37616#0: *35 createStream, client: 86.29.76.152, server: 0.0.0.0:1935
2020/10/24 13:06:22 [info] 37616#0: *35 publish: name='5f833948ec2a7' args='' type=live silent=0, client: 86.29.76.152, server: 0.0.0.0:1935
2020/10/24 13:06:22 [info] 37616#0: *35 notify: publish 'arpradiolive.com/plugin/Live/on_publish.php', client: 86.29.76.152, server: 0.0.0.0:1935
2020/10/24 13:06:22 [info] 37616#0: *35 notify: publish redirect to 'https://arpradiolive.com/plugin/Live/on_publish.php', client: 86.29.76.152, server: 0.0.0.0:1935
2020/10/24 13:06:23 [error] 37616#0: *1 open() "/HLS/live/5f833948ec2a7/index.m3u8" failed (2: No such file or directory), client: 86.29.76.152, server: arpradiolive.com, request: "GET /live/5f833948ec2a7/index.m3u8 HTTP/1.1", host: "arpradiolive.com:444", referrer: "https://arpradiolive.com/live/0/ARPRadioLive&embed=1"
2020/10/24 13:06:29 [error] 37616#0: *1 open() "/HLS/live/5f833948ec2a7/index.m3u8" failed (2: No such file or directory), client: 86.29.76.152, server: arpradiolive.com, request: "GET /live/5f833948ec2a7/index.m3u8 HTTP/1.1", host: "arpradiolive.com:444", referrer: "https://arpradiolive.com/live/0/ARPRadioLive&embed=1"
2020/10/24 13:06:34 [error] 37616#0: *1 open() "/HLS/live/5f833948ec2a7/index.m3u8" failed (2: No such file or directory), client: 86.29.76.152, server: arpradiolive.com, request: "GET /live/5f833948ec2a7/index.m3u8 HTTP/1.1", host: "arpradiolive.com:444", referrer: "https://arpradiolive.com/live/0/ARPRadioLive&embed=1"
2020/10/24 13:07:00 [info] 37616#0: *1 client 86.29.76.152 closed keepalive connection
2020/10/24 13:07:44 [info] 37616#0: *43 client 86.29.76.152 closed keepalive connection
2020/10/24 13:08:01 [info] 37616#0: *49 client closed connection while waiting for request, client: 86.29.76.152, server: 0.0.0.0:444
2020/10/24 13:08:01 [info] 37616#0: *48 client closed connection while waiting for request, client: 86.29.76.152, server: 0.0.0.0:444
2020/10/24 13:14:57 [info] 37616#0: *96 client 86.184.79.121 closed keepalive connection
2020/10/24 13:15:07 [info] 37616#0: *98 client 86.184.79.121 closed keepalive connection
2020/10/24 13:15:27 [info] 37616#0: *101 client 86.184.79.121 closed keepalive connection
2020/10/24 13:15:37 [info] 37616#0: *103 client 86.184.79.121 closed keepalive connection
2020/10/24 13:15:47 [info] 37616#0: *106 client 86.184.79.121 closed keepalive connection
2020/10/24 13:15:57 [info] 37616#0: *107 client 86.184.79.121 closed keepalive connection
2020/10/24 13:16:07 [info] 37616#0: *109 client 86.184.79.121 closed keepalive connection
2020/10/24 13:16:17 [info] 37616#0: *112 client 86.184.79.121 closed keepalive connection
2020/10/24 13:16:27 [info] 37616#0: *113 client 86.184.79.121 closed keepalive connection
2020/10/24 13:16:37 [info] 37616#0: *115 client 86.184.79.121 closed keepalive connection
2020/10/24 13:16:47 [info] 37616#0: *117 client 86.184.79.121 closed keepalive connection
2020/10/24 13:16:57 [info] 37616#0: *121 client 86.184.79.121 closed keepalive connection
2020/10/24 13:17:08 [info] 37616#0: *124 client 86.184.79.121 closed keepalive connection
2020/10/24 13:17:18 [info] 37616#0: *126 client 86.184.79.121 closed keepalive connection
2020/10/24 13:17:28 [info] 37616#0: *129 client 86.184.79.121 closed keepalive connection
2020/10/24 13:17:38 [info] 37616#0: *131 client 86.184.79.121 closed keepalive connection
2020/10/24 13:17:48 [info] 37616#0: *133 client 86.184.79.121 closed keepalive connection
2020/10/24 13:17:58 [info] 37616#0: *135 client 86.184.79.121 closed keepalive connection
2020/10/24 13:18:18 [info] 37616#0: *138 client 86.184.79.121 closed keepalive connection
2020/10/24 13:18:28 [info] 37616#0: *140 client 86.184.79.121 closed keepalive connection
2020/10/24 13:18:38 [info] 37616#0: *142 client 86.184.79.121 closed keepalive connection`

Web Console

![Screen Shot 2020-10-24 at 12 21 12](https://user-images.githubusercontent.com/17967657/97080473-717a2a80-15f3-11eb-9252-d1a8a2586ba1.png)

**Comment by jengajenga** [comment]
I also am not able to Autoplay despite the setting being on.

**Comment by s7ntax** [comment]
The OFFLINE badge also flicks briefly to "Finishing Live" then goes back to OFFLINE. If it can't be fixed I'd be happy to just hide it.

**Comment by jengajenga** [comment]
> The OFFLINE badge also flicks briefly to "Finishing Live" then goes back to OFFLINE. If it can't be fixed I'd be happy to just hide it.

You may want to remove autoplay and see if that helps. I have everything working - online is online, offline is offline - only autoplay doesn't autoplay. try remove it and see.

**Comment by s7ntax** [comment]
I have tried both, i've had the OFFLINE thing since installing 9.5

**Comment by s7ntax** [comment]
Fixed the save sitemap issue, was a permissions problem since updating.

**Comment by s7ntax** [comment]
OK I'm not getting anywhere asking here for help, I've hacked the css to hide the OFFLINE badge and the total views counter as it never resets and cannot be manually reset. 

I can only assume that the other issue regarding autoplay is a bug as it only occurred since I updated so I'm hoping this will get fixed in the next update.

**Comment by morbificagent** [comment]
@s7ntax can you provide how to hide the offline/online badge?

**Comment by DanielnetoDotCom** [comment]
@morbificagent  can you screenshot where do you mean that?

**Comment by morbificagent** [comment]
![image](https://user-images.githubusercontent.com/50199132/111628968-15f24880-87f1-11eb-99c2-44d8b9599bf2.png)

**Comment by morbificagent** [comment]
Is hideable now (https://github.com/WWBN/AVideo/issues/4730), thx to Daniel
