### ISSUE TITLE
Cannot access plugin store using FB login

### ISSUE THREAD

**Issue by sipero** [WWBN/AVideo#3904]
When I try to access my purchased plugins via the plugin store I can no longer login as it says the app is in development mode. Please fix ASAP Thanks

**Comment by DanielnetoDotCom** [comment]
I am blocked from Facebook again. (third time)

Can you please create an account on the https://tutorials.avideo.com/ and use it to login?

than please send me you facebook email and your new account # and I will transfer your purchases to it.

**Comment by sipero** [comment]
Hi,

I created the account as suggested with email john@sipero.com and the username sipero

My facebook email is john@sipero.com.


Jonathan Hamon


-------- Original Message --------

**Comment by DanielnetoDotCom** [comment]
You must signup on the marketplace site and inform your user # so I will be able to transfer the purchases.

**Comment by sipero** [comment]
Hi,

When you say the marketplace site what do you mean. What is the url aas right now I do not see that

-------- Original Message --------

**Comment by sipero** [comment]
Try #2895

**Comment by DanielnetoDotCom** [comment]
When you login you will see that

**Comment by DanielnetoDotCom** [comment]
Done to user # 2895  try now.

**Comment by sipero** [comment]
The only one I don't see is the ZoomMeetingRecorder

**Comment by DanielnetoDotCom** [comment]
Please try now

**Comment by sipero** [comment]
Perfect thanks
