### ISSUE TITLE
/plugin/Live Hangs

### ISSUE THREAD

**Issue by ashrafpro** [WWBN/AVideo#3906]
Hi,
I just received my server setup service, when I try to open /plugin/Live, it keeps load and loads, for ever.
what could be the issue?

**Comment by DanielnetoDotCom** [comment]
not sure, but you can check the logs

**Comment by ashrafpro** [comment]
please guide me, I got the setup service because my experience is little in this :)

I can see in log: 

Connecting to ca1.ypt.me (ca1.ypt.me)|2606:4700:3030::ac43:caea|:443... failed: Connection timed out.
Cannot write to 'checkMeet.json.php?webSiteRootURL=https:%2F%2Fwww.XXXXXXX.com%2F' (Success).
[Sun Oct 25 08:01:52.297373 2020] [php7:notice] [pid 1524] [client 41.36.XX.XX:63384] AVideoLog::DEBUG: wget: ERROR the url does not download https://ca1.ypt.me/api/checkMeet.json.php

AVideoLog::DEBUG: wget: ERROR the url does not download https://ca1.ypt.me/api/checkMeet.json.php1.ypt

**Comment by DanielnetoDotCom** [comment]
Looks like your server cannot resolve/connect to our meet server.

I just disabled the Meet plugin and seems the Live plugin is loading fine now.

I guess it is a DNS problem (maybe related to IPV6)

That is what I found in your server

```
--2020-10-25 12:06:32--  https://ca1.ypt.me/api/checkMeet.json.php?webSiteRootURL=https%3A%2F%2Ffilgoan.com%2F
Resolving ca1.ypt.me (ca1.ypt.me)... 2606:4700:3037::681f:535c, 2606:4700:3030::ac43:caea, 2606:4700:3035::681f:525c, ...
Connecting to ca1.ypt.me (ca1.ypt.me)|2606:4700:3037::681f:535c|:443... [Sun Oct 25 12:07:36.910404 2020] [php7:notice] [pid 12289] [client 177.30.53.81:56025] AVideoLog::DEBUG: Start Login Request SCRIPT_NAME: /objects/login.json.php, referer: https://filgoan.com/user
[Sun Oct 25 12:07:36.910460 2020] [php7:notice] [pid 12289] [client 177.30.53.81:56025] AVideoLog::DEBUG: redirectUri: https://filgoan.com/ SCRIPT_NAME: /objects/login.json.php, referer: https://filgoan.com/user
[Sun Oct 25 12:07:36.910516 2020] [php7:notice] [pid 12289] [client 177.30.53.81:56025] AVideoLog::DEBUG: same redirectUri: https://filgoan.com/ SCRIPT_NAME: /objects/login.json.php, referer: https://filgoan.com/user
failed: Connection timed out.
Connecting to ca1.ypt.me (ca1.ypt.me)|2606:4700:3030::ac43:caea|:443... failed: Connection timed out.
Connecting to ca1.ypt.me (ca1.ypt.me)|2606:4700:3035::681f:525c|:443... [Sun Oct 25 12:11:12.809933 2020] [php7:notice] [pid 1521] [client 177.30.53.81:56149] AVideoLog::DEBUG: plugin::setCurrentVersionByUuid meet225-3807-4167-ba81-0509dd280e06, 2.0 SCRIPT_NAME: /objects/pluginSwitch.json.php, referer: https://filgoan.com/plugins

```
