### ISSUE TITLE
MYSQL database folder location?

### ISSUE THREAD

**Issue by loso20p** [WWBN/AVideo#3907]
Can you please tell me in which folder db records are stored in your script? I need access to mysql database info but i forgot them n If I create sql with another password then will i still connect it with your script? or get an error?

**Comment by syldri** [comment]
hello @loso20p  when you connect in ssh go here

/var/lib/mysql

**Comment by loso20p** [comment]
> hello @loso20p when you connect in ssh go here
> 
> /var/lib/mysql

There is no DB password stored in mentioned path

**Comment by syldri** [comment]
hello  look at this file (  configuration.php ) 

/var/www/html/AVideo/videos/

![image](https://user-images.githubusercontent.com/39193219/97104611-7f907f80-16b5-11eb-8c33-7537441b53c4.png)

**Comment by loso20p** [comment]
> hello look at this file ( configuration.php )
> 
> /var/www/html/AVideo/videos/
> 
> ![image](https://user-images.githubusercontent.com/39193219/97104611-7f907f80-16b5-11eb-8c33-7537441b53c4.png)

thanx alot
