### ISSUE TITLE
Does AVIDEO and Avideo Encoder work with Ubuntu 20.x

### ISSUE THREAD

**Issue by sipero** [WWBN/AVideo#3908]
Can you please tell me whether AVIDEO should work with Ubuntu 20.x or should I stick to 18.04?

**Comment by DanielnetoDotCom** [comment]
Ubuntu 20.04 is fine.

**Comment by sipero** [comment]
The reason I ask is I just got a new dedicated server and used the instructions for Ubuntu 18.04 and version 4 or later and had many problems

**Comment by DanielnetoDotCom** [comment]
you may need a different PHP version on Ubuntu 20

you can google to see what exact versions you need.

in the future, I will update the tutorials for Ubuntu 20

**Comment by milehighkaraoke** [comment]
you will need php 7.4

**Comment by sipero** [comment]
Hi,

Yes I noticed php 7.4 but php gettext is not availble
