### ISSUE TITLE
Disconnect Stream

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3909]
Greetings @akhilleusuggo @DanielnetoDotCom 

Is there a way to disconnect a stream without resetting the stream key? Can it be reset without changing the stream key? 

Thanks

**Comment by DanielnetoDotCom** [comment]
we still improving the live controls to record and disconnect. but you to guarantee the user will not connect again we need to reset the key. otherwise the live can auto-reconnect even after we drop it.

but maybe if you inactivate the user it will also block the reconnection.
