### ISSUE TITLE
on_publish.php 401 error

### ISSUE THREAD

**Issue by ashrafpro** [WWBN/AVideo#3910]
Hi,
I am getting 401 error on the on_publish.php, and OBS refused to connect
http://mydomain.com/plugin/Live/on_publish.php

nginx.conf
on_publish http://localhost/AVideo/plugin/Live/on_publish.php;

**Comment by jengajenga** [comment]
> Hi,
> I am getting 401 error on the on_publish.php, and OBS refused to connect
> http://mydomain.com/plugin/Live/on_publish.php
> 
> nginx.conf
> on_publish http://localhost/AVideo/plugin/Live/on_publish.php

what?? http://mydomain/actual_folder_name/plugin/Live/on_publish.php

And why are you directing obs to connect to that page?

**Comment by DanielnetoDotCom** [comment]
Error 401 is expected, sorry but it is not a bug 

https://github.com/arut/nginx-rtmp-module/wiki/Directives#on_play
