### ISSUE TITLE
SendRecordedToEncoder issues

### ISSUE THREAD

**Issue by sipero** [WWBN/AVideo#3911]
I have done a fresh install of AVideo and the Encoder on my dedicated server with Ubuntu 18.04

I have added the SendRecordedToEncoder and the VideoHLS plugins which are the latest versions 2.1 and 5.2

When I do a Livestream I see the video is recorded and saved in /var/www/tmp but it seems that this is never sent to the encoder.

I noticed in the SendRecorded plugin there is now a secret recording key that was not in an earlier version. Do I need to add this somewhere else.

**Comment by DanielnetoDotCom** [comment]
Hi, the SendRecordedToEncoder you should only enable it.

how is your Live parameters, please screenshot

**Comment by sipero** [comment]
Hi,

Here is the screen shot https://nimb.ws/E0S8Qa

**Comment by DanielnetoDotCom** [comment]
check your Streamer log, and also your nginx log files.

**Comment by bbyrdhouse** [comment]
I also have SendRecordedToEncoder enabled but livestreams are not being recorded and sent to the encoder. 
I remember reading that the "Record" feature was not yet working, is this still the case?

<img width="742" alt="Screen Shot 2020-12-02 at 3 41 20 PM" src="https://user-images.githubusercontent.com/7376298/100935078-410c9280-34b5-11eb-8c56-16c9379fad20.png">
<img width="647" alt="live-record" src="https://user-images.githubusercontent.com/7376298/100935086-45d14680-34b5-11eb-8a38-8ffc1f1b3ac3.png">
<img width="603" alt="live1" src="https://user-images.githubusercontent.com/7376298/100935106-4cf85480-34b5-11eb-84e3-b3d263e9ac61.png">

**Comment by DanielnetoDotCom** [comment]
Your recorder was not enabled on the nginx.conf as described here https://github.com/WWBN/AVideo/wiki/Record-Live-Stream#step-3

![image](https://user-images.githubusercontent.com/18009293/101022477-33f0b180-3550-11eb-9710-92f4b9f1f400.png)

I just enabled for you, please try again.
