### ISSUE TITLE
install Sorry! Unknow error!

### ISSUE THREAD

**Issue by maherenez** [WWBN/AVideo#3912]
im install in ubuntu 18.0.4  i finish but when i click install now i see error install (Sorry! Unknow error!)

Sun Oct 25 21:27:20.283592 2020] [php7:error] [pid 4697] [client 185.255.44.98:10294] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/AVideo/install/checkConfiguration.php:22\nStack trace:\n#0 {main}\n  thrown in /var/www/html/AVideo/install/checkConfiguration.php on line 22, referer: http://myserver/AVideo/install/index.php

**Comment by DanielnetoDotCom** [comment]
please google for your error.

**Comment by pchelferlein** [comment]
Checkby creating a test.php file with the content:
`<?php
if (!function_exists('mysqli_init') && !extension_loaded('mysqli')) {
    echo 'We don\'t have mysqli!!!';
} else {
    echo 'Phew we have it!';
}?>`

If not installed on a default Ubuntu you can add the appropriate Moduls using
sudo apt-get install *correct Module name for your PHP and Server e.g. php-mysqlnd*
Cheers
