### ISSUE TITLE
OBS won't accept stream URL or key

### ISSUE THREAD

**Issue by qome** [WWBN/AVideo#3913]
**Describe the question**
I have set up NGINX and the Live/LiveChat plugins and entered the given stream URL and key into OBS but OBS produces an error as though the stream key was invalid. The logs seem to indicate the stream key was accepted.

**Screenshots**
![image](https://user-images.githubusercontent.com/58382620/97152955-b612dc80-173f-11eb-9ab3-f37f608f5253.png)

```
$ tail -fn0 /usr/local/nginx/logs/error.log
2020/10/26 08:58:42 [info] 19067#0: *145 client connected '192.168.0.134'
2020/10/26 08:58:42 [info] 19067#0: *145 connect: app='live' args='p=cabafdc5bd07126cfc7a64e41153ac35' flashver='FMLE/3.0 (compatible; FMSc/1.0)' swf_url='rtmp://avideo.qome.localdomain/live?p=cabafdc5bd07126cfc7a64e41153ac35' tc_url='rtmp://avideo.qome.localdomain/live?p=cabafdc5bd07126cfc7a64e41153ac35' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 192.168.0.134, server: 0.0.0.0:1935
2020/10/26 08:58:42 [info] 19067#0: *145 createStream, client: 192.168.0.134, server: 0.0.0.0:1935
2020/10/26 08:58:42 [info] 19067#0: *145 publish: name='5f968d7fca173' args='' type=live silent=0, client: 192.168.0.134, server: 0.0.0.0:1935
2020/10/26 08:58:42 [info] 19067#0: *145 notify: publish 'avideo.qome.localdomain/plugin/Live/on_publish.php', client: 192.168.0.134, server: 0.0.0.0:1935
2020/10/26 08:58:42 [info] 19067#0: *145 disconnect, client: 192.168.0.134, server: 0.0.0.0:1935
2020/10/26 08:58:42 [info] 19067#0: *145 deleteStream, client: 192.168.0.134, server: 0.0.0.0:1935
```

**Comment by DanielnetoDotCom** [comment]
share your nginx.conf and also your streamer.log

**Comment by qome** [comment]
Where is the streamer.log file located?

**Comment by qome** [comment]
I can't even load the Live page now.

**Comment by JoshWho** [comment]
This is just a crappy new setting in the latest OBS. All you have to do is go to advance then change the Network card to: **Default**

<img src="https://static.buddylist.co/bind.png" style='width:100%;' border="0" alt="Null">

They added this feature for TV networks that use multiple networks cards but all u have to do is just switch it back to default and click apply and u should be all good.

**Comment by DanielnetoDotCom** [comment]
@qome on the latest version you can find the log file here

![image](https://user-images.githubusercontent.com/18009293/97434859-64fd1700-18fe-11eb-90d9-32d51293f576.png)

**Comment by qome** [comment]
Thanks. I don't know what happened after a re-install but it's working now.
