### ISSUE TITLE
 function to automatically play next video does not work

### ISSUE THREAD

**Issue by XemTube-TV** [WWBN/AVideo#3916]
function to automatically play next video does not work.It is stuck in the state as attached picture

![image](https://user-images.githubusercontent.com/50126312/97176636-d1c1c580-17c7-11eb-9c12-99ccfc51d887.png)

**Comment by DanielnetoDotCom** [comment]
check for JS errors

**Comment by XemTube-TV** [comment]
It shows the error playNext ajax fail. How to fix this


![image](https://user-images.githubusercontent.com/50126312/97583135-2d3ebe00-1a29-11eb-9d6b-859203b1efde.png)

**Comment by DanielnetoDotCom** [comment]
I do not know this widget.api on your page.

maybe it is crashing the script.
