### ISSUE TITLE
Plugin Live Search Not Working

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3918]
The plugin is not working . Nothing really on the chat log .

_TESTED_ on demo site , and _NOT_ working

**Comment by DanielnetoDotCom** [comment]
Thank, I just sent a fix

**Comment by akhilleusuggo** [comment]
Are you sure ? I don't see any update ... I see an update plugin on chat , but not on Live Search's plugin .
Also on the code source , no fix for this issue .

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/97561949-ab667a80-19bf-11eb-9bab-b5458b019a58.png)


![image](https://user-images.githubusercontent.com/18009293/97561894-9853aa80-19bf-11eb-8b65-83186d855966.png)

**Comment by akhilleusuggo** [comment]
so what have you updated ? The plugin ? Because I got no notification about uploading it

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/97563204-635d4d00-19eb-11eb-9714-197869d5b60d.png)

![image](https://user-images.githubusercontent.com/52116577/97563264-740dc300-19eb-11eb-885c-71fe99b1d0f3.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom ok , on the source code of the plugin , you forgot to add 

```
public function getPluginVersion() {
        return "1.1";
```

**Comment by DanielnetoDotCom** [comment]
Correct, my bad, I just sent an update with the version in it.
