### ISSUE TITLE
Version 9.7 installation error

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3919]
I updated version to 9.7 

After update I got this error on update page: 

![image](https://user-images.githubusercontent.com/63721378/97183495-8814b300-17a6-11eb-88bc-f3416ad23bb3.png)

I'm a little bit concerned now what will this bring along...

**Comment by tonuzo** [comment]
My email password was changed and I hadn't changed it into the email configuration. 

I guess maybe that was the error?

**Comment by DanielnetoDotCom** [comment]
Hi, 

I think you got the updates to early.
I changed this 10 min later. it is not a mandatory update but you can manually rin the SQL from the file 
https://github.com/WWBN/AVideo/blob/master/updatedb/updateDb.v9.7.sql

**Comment by tonuzo** [comment]
Ok. I'm sorry I'm not familiar with this. How do you do it exactly?

**Comment by DanielnetoDotCom** [comment]
you need to be able to run SQL commands in your database

you also can do this https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform#rollback-the-update

**Comment by tonuzo** [comment]
Thanks, got it!
