### ISSUE TITLE
Getting HTTP 500 error when clicking on Upload Test

### ISSUE THREAD

**Issue by gregk63** [WWBN/AVideo#3920]
**Describe the question**
Just downloaded S3 Plugin and configured it as much as I thought I need to but I am guessing maybe not. When I click on the Upload Test button I am getting a HTTP 500 button. I entered Region, Bucket Name, Key, Secret from my S3 configuration. Am I missing something?

Thanks!

Greg

**Screenshots**
Provide some screenshots to help us understand and explain your problem.
This page isn’t working35.192.9.139 is currently unable to handle this request.
HTTP ERROR 500

**Comment by DanielnetoDotCom** [comment]
check your log file.

**Comment by gregk63** [comment]
This is showing up in avideo.log

GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: ex4kaiserclix.s3..amazonaws.com (see h
ttp://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/YouPHPTube/plugin/AWS_S3/aws/GuzzleHttp/Handler/
CurlFactory.php:186

I removed the AWS region as a test so that is why there is two dots after S3 in the about url. With the region defined in the parameter file it still fails with the same error. 

I am seeing that the region shouldn't be part of the url. The urls that AWS comes up for an asset doesn't have it in it.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot the AWS_S3 parameters screen?

FYI, if you are using Amazon S3 the endpoint  must be blank

**Comment by gregk63** [comment]
Attached requested screenshot.
![S3 parameters part1](https://user-images.githubusercontent.com/72754374/97436272-b9e56100-18ef-11eb-9be4-ce02e7f15f05.png)
![S3 parameters part2](https://user-images.githubusercontent.com/72754374/97436274-ba7df780-18ef-11eb-9b54-f45f95c69ea5.png)

**Comment by DanielnetoDotCom** [comment]
can you also please screenshot your amazon bucket configuration page?

FYI, when we finish please change your S3 keys on amazon

**Comment by gregk63** [comment]
![S3 buckets](https://user-images.githubusercontent.com/72754374/97439823-aab4e200-18f4-11eb-89bb-b4086abbec63.png)

S3 buckets.

**Comment by DanielnetoDotCom** [comment]
Based on this doc, your region parameter suppose to be us-east-1

https://docs.aws.amazon.com/general/latest/gr/s3.html

**Comment by gregk63** [comment]
That worked! Thank you! 

I am now getting a permissions message. I think I should be able to resolve that. 

Since I have you could you direct me to any documentation on how to prevent users from seeing each others videos? I have tried making videos private and that doesn't seem to help. I may be missing something and I haven't found any docs.

I am looking to use YouPHPTube to host family VHS tapes converted to digital so of course one family wouldn't want other family looking at their videos.

**Comment by DanielnetoDotCom** [comment]
you may need to create user groups for each user(s)

an then make the video available only for that usergroup

![image](https://user-images.githubusercontent.com/18009293/97452016-1148f880-1913-11eb-9adf-529913149469.png)

**Comment by gregk63** [comment]
Great! Thank you!

I will try that!

I'll leave you alone now! :-)

**Comment by gregk63** [comment]
That is working.

Thank you!
