### ISSUE TITLE
First video on page

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#3922]
I have the same video stuck on the top of the[ first page.](https://fakeotube.com)
How do I change this to the latest video or random video?
fakeotube.com

**Comment by fakeologist** [comment]
Apparently it was accidentally starred here.
![image](https://user-images.githubusercontent.com/66537018/97243039-c96b8980-17cb-11eb-962b-480fdd64e0e6.png)

There's no way to unstar the video unless you find it in the list of videos.
![image](https://user-images.githubusercontent.com/66537018/97243099-edc76600-17cb-11eb-9d54-1dba28870bd9.png)

Is there a way to unsuggest the video easily without trying to find it in the list of videos? I don't see the option in the edit video area.

**Comment by DanielnetoDotCom** [comment]
I see what you mean.

I agree with that, we need an easier way to un suggest. I will add it in a future update.
