### ISSUE TITLE
Problem To conect with database. Access denied for user root

### ISSUE THREAD

**Issue by danieljaber** [WWBN/AVideo#3927]
Hi.
I used "https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer" to set up a server and followed all the steps in detail.

The page was created correctly, the entire checklist was fulfilled, but when I try to install the error appears: Connect Error (1698) Access denied for user 'root'@'localhost'. 

Can you help to fix it?
![image](https://user-images.githubusercontent.com/73574002/97395859-9e189580-18c4-11eb-8968-d2cc2cf3040d.png)

**Comment by DanielnetoDotCom** [comment]
the error is written on the screen.

try to google for a solution

**Comment by danieljaber** [comment]
Hi Daniel,

Sorry for ignorant question.
It is fixed. Thank you very much.
