### ISSUE TITLE
No me Esta Funcionado el Video en Vivo

### ISSUE THREAD

**Issue by amadomora** [WWBN/AVideo#3928]
**Describe the question**

excuse my english, i'm using google traslator ..

#Greetings I made the Configuration according to Daniel Neto's github manual, to configure my site and broadcast live through rtmp, apparently everything is fine but the video DOES NOT SHOW on my site

**Screenshots**
Provide some screenshots to help us understand and explain your problem.
*mi configuración de nginx
![nginx1](https://user-images.githubusercontent.com/44752480/97447814-f6b85480-18fd-11eb-9a4a-2daf77b3f434.png)
![nginx2](https://user-images.githubusercontent.com/44752480/97447821-f750eb00-18fd-11eb-9ce3-273627f703e2.png)
![nginx3](https://user-images.githubusercontent.com/44752480/97447823-f750eb00-18fd-11eb-88b5-c410551d17f8.png)
![nginx4](https://user-images.githubusercontent.com/44752480/97447825-f750eb00-18fd-11eb-9e83-61f3f65068f3.png)
![nginx5](https://user-images.githubusercontent.com/44752480/97447826-f7e98180-18fd-11eb-8a3e-40c795d691ed.png)

*mi emision d eobs-phptube
![emision](https://user-images.githubusercontent.com/44752480/97447938-18194080-18fe-11eb-9fcd-c17ad73384e2.png)
![phptube](https://user-images.githubusercontent.com/44752480/97447940-18b1d700-18fe-11eb-97d4-ec15c6f5b4c6.png)

*mi obs emitiendo

![obs](https://user-images.githubusercontent.com/44752480/97448016-2bc4a700-18fe-11eb-9489-d23178b21fc8.png)
 logs de phptube

*Logs de nginx

![logsnginx](https://user-images.githubusercontent.com/44752480/97448248-73e3c980-18fe-11eb-8036-dbf9db12ca43.png)

**Comment by DanielnetoDotCom** [comment]
Is your site HTTPS?

does your nginx has a valid HTTPS as well?

**Comment by amadomora** [comment]
No, My site is http, I have a vps and it is http

**Comment by DanielnetoDotCom** [comment]
share your site link here

**Comment by amadomora** [comment]
I have the live plugin active, 
![live1](https://user-images.githubusercontent.com/44752480/97710031-365f7780-1a89-11eb-9362-5eed79c95d68.png)

but if I click on "edit live server" the next window gives me a message saying that it is not active

![live2](https://user-images.githubusercontent.com/44752480/97710185-69a20680-1a89-11eb-8c43-3e477947a02e.png)

**Comment by DanielnetoDotCom** [comment]
lease a live stream running so we can test it

**Comment by amadomora** [comment]
now in active,  but
![3](https://user-images.githubusercontent.com/44752480/97741571-ef857800-1ab0-11eb-8629-c86ba20afcb7.png)
![4](https://user-images.githubusercontent.com/44752480/97741585-f7451c80-1ab0-11eb-8d28-70d01a63357d.png)

**Comment by DanielnetoDotCom** [comment]
this is blank http://hug.vps.co.ve:8080/stats

and this is not found http://hug.vps.co.ve:8080/live/5f9b613418650/index.m3u8
