### ISSUE TITLE
LIVE Servers configuration

### ISSUE THREAD

**Issue by angry999** [WWBN/AVideo#3929]
Hello, I am going to use serveral Live servers, so I installed the RTMPs on the local server and another server.
But not sure what should I set the parameters for "Get Remote File URL".
Please let me know.
Thank you
![image](https://user-images.githubusercontent.com/55845113/97458838-6436a600-193b-11eb-98ba-83df527bafd2.png)

**Comment by DanielnetoDotCom** [comment]
That is the file https://github.com/WWBN/AVideo/blob/master/plugin/Live/standAloneFiles/getRecordedFile.php

you must have a copy of it on your server.

even better you can copy the whole standAloneFiles directory into your live server.
