### ISSUE TITLE
Plugin 'Seekbutton' doesn't show in videoplayer

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#3930]
Since one of the last updates the plugin 'Seekbutton' doesn't show in the videoplayer.
![Snap1](https://user-images.githubusercontent.com/39981177/97497418-bf33c180-196a-11eb-915a-1a972fb1daa8.jpg)

**Comment by DanielnetoDotCom** [comment]
It is showing on my browser (demo site)

![image](https://user-images.githubusercontent.com/18009293/97561098-655ce700-19be-11eb-959a-9d03389dc551.png)

**Comment by TLCReuver** [comment]
Strange, in last Chrome_version for windows it doesn't show it.
![Snap2](https://user-images.githubusercontent.com/39981177/97564901-9ac8fb00-19e5-11eb-8f9d-501445bf2c11.jpg)

**Comment by DanielnetoDotCom** [comment]
try to clear your browser cache and delete cookies.

**Comment by TLCReuver** [comment]
Cache & cookies are always delete when closing the browser. Only Edge & Pale Moon shows the seekbutton and landscapemode on mobile phone. IE, Firefox & Chrome didn't show the seekbutton. The desktop resolution here is 1600x900 so there is enough space to show these buttons. Very strange.

**Comment by DanielnetoDotCom** [comment]
please check for JS errors, also try an incognito window

**Comment by TLCReuver** [comment]
Incognito windows shows no seekbutton on demosite

Only warning on demosite is:
VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead

**Comment by DanielnetoDotCom** [comment]
I just realize, the seek button will be hidden on mobiles but will work the DoubleClick on the sides of the video may reproduce the seek behavior.

maybe for some reason, it is recognizing your browser as a mobile. do you have any specific add-on in your browser that may be is doing this behavior?

**Comment by TLCReuver** [comment]
I have disabled all chome-addons and on desktopview in full screen-mode it doesn't show also.
Only MS Edge & Pale Moon shows the seekbutton under windows.
I tried firefox in Ubuntu and there is alo no seekbutton
Very strange....

**Comment by DanielnetoDotCom** [comment]
I use chrome and Firefox on windows and mac, they both work on my side

also works on Safari (Mac)

are you using them on Ubuntu? what exactly OS and browser version are you using?

**Comment by TLCReuver** [comment]
I use the latest version of Chrome  under Windows 10 with desktop screen resolution 1600x900
and there are no external plugins installed in Chrome.

![Snap3](https://user-images.githubusercontent.com/39981177/98004995-dc481480-1df0-11eb-96bc-92fb6922b97a.jpg)

**Comment by DanielnetoDotCom** [comment]
can you please access this page https://demo.avideo.com/about

and screenshot what you see here 

![image](https://user-images.githubusercontent.com/18009293/98016790-2a531d00-1ddd-11eb-9e38-344a53077da3.png)

**Comment by TLCReuver** [comment]
Snapshot https://demo.avideo.com/about

![Snap5](https://user-images.githubusercontent.com/39981177/98026383-54bbcf00-1e0b-11eb-9e72-5d7f324dd4f6.jpg)

**Comment by DanielnetoDotCom** [comment]
this is frustrating.

I have no clue, and I cannot reproduce it here. it is working in all my browsers.

**Comment by TLCReuver** [comment]
Yes, i know its very frustating when you can't reproduce it.

I did the same test on another PC (Laptop) to check if there is something wrong on Desktop-PC but with the same result :(

![Snap1](https://user-images.githubusercontent.com/39981177/98108621-8f217c80-1e9c-11eb-8d31-70f98ff68e21.jpg)
![Snap2](https://user-images.githubusercontent.com/39981177/98108622-8fba1300-1e9c-11eb-80b8-8ba18e0d907c.jpg)
![Snap3](https://user-images.githubusercontent.com/39981177/98108623-9052a980-1e9c-11eb-8792-3303db388f36.jpg)

**Comment by DanielnetoDotCom** [comment]
Just curious, is possible for you to test it from another network?

maybe there is something blocking the script?

**Comment by TLCReuver** [comment]
Hi Daniel,

I connect the laptop to 4G (Hotspot/Tethering) but also without any result.

Because it worked in the past i restored the backup from 16-10
![Snap8](https://user-images.githubusercontent.com/39981177/98136439-39ab9680-1ec1-11eb-82e2-a2465df6b9d6.jpg)

with AVideo 9.6
![Snap7](https://user-images.githubusercontent.com/39981177/98136520-5051ed80-1ec1-11eb-9eca-17a4b7319daf.jpg)

At that time the seekbuttons are visible that makes it indeed very frustating for you... sorry :(

![Snap6](https://user-images.githubusercontent.com/39981177/98136804-9b6c0080-1ec1-11eb-8c69-f67326391d5f.jpg)

**Comment by DanielnetoDotCom** [comment]
Just confirming, it is also not showing to you on the demo site correct?

**Comment by TLCReuver** [comment]
Correct, the demo site is not showing the seekbuttons.
