### ISSUE TITLE
Auto play video is not working

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#3931]
On the demo site.  I found Autoplay video is not working.

**Comment by TLCReuver** [comment]
Here too after update from 23-10-2020.

**Comment by guitarpound** [comment]
Anybody know how to solve this problem.

**Comment by DanielnetoDotCom** [comment]
It supposes to be working now. can you please point to a video that is not working?

**Comment by guitarpound** [comment]
Hi @DanielnetoDotCom 
The problem is Browser cache.  I working after clear all browser cache.
Thank you so much.
