### ISSUE TITLE
Max. Concurrent users

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#3932]
Hi,

I know this question maybe more than it is a AVideo question but I think this community has experience with the matter.

I have local server spec below.
**Dell PowerEdge R440**
CPU  Intel Xeon Silver 4208 2.1G, 8C/16T, 9.6GT/s, 11M Cache, Turbo, HT (85W)
RAM DDR4 32GB
1x HDD 960GB SSD SAS Read Intensive 12Gbps & 1x 8TB 7.2K RPM NLSAS.
10Gbps LAN port

I setup AVideo v9.5 with Encoder in the same server.

And then use Jmeter + BlazeMeter HLS plug-in v3.0 to testing request HTTP & HLS Live streaming start from 500 concurrent users in my Local network that there are 1 Gbps bandwidth.

![rpviewer (7)](https://user-images.githubusercontent.com/57282919/97556751-72082c00-1a0c-11eb-98f9-7f9e94bedf4f.png)

![rpviewer (6)](https://user-images.githubusercontent.com/57282919/97556673-5ac93e80-1a0c-11eb-9a6c-08406b09fb89.png)

The report on Jmeter no any error.

![rpviewer (8)](https://user-images.githubusercontent.com/57282919/97556365-f0b09980-1a0b-11eb-8019-c0278675181b.png)

And The CPU, Memory & Network Bandwidth still enough for 500 Users.

![rpviewer (9)](https://user-images.githubusercontent.com/57282919/97556498-28b7dc80-1a0c-11eb-967d-5d32c0109a4b.png)

But during the test.  I use another PC to watch Live streaming.  it can't playback the video.

![Oct-29-2563 17-03-26](https://user-images.githubusercontent.com/57282919/97554744-c827a000-1a09-11eb-8658-f717b727e5ad.gif)

So, I gradually reduced the request volume down until 180 users got it back.

I think It should be work fine at least 500users.
How can I check? What is not enough for this.

Please kindly help share your experience.

Thanks

**Comment by DanielnetoDotCom** [comment]
Check your apache max connections/workers

also check the mysql log and apache log

**Comment by guitarpound** [comment]
Hi Daniel,

I already changed apache2 mpm_prefork config to below.

/etc/apache2/mods-enabled/mpm_prefork.conf

`<IfModule mpm_prefork_module>
        StartServers                     5
        MinSpareServers          25
        MaxSpareServers          50
        MaxRequestWorkers         1024
        MaxConnectionsPerChild   2000
</IfModule>`

And try to request data again at 500users.  But the problem still there. 
So, I check apache error log & mysql error log not found any abnormal.

/var/log/apache2/error.log
`[Fri Oct 30 14:46:31.221569 2020] [core:warn] [pid 63] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache run?
[Fri Oct 30 14:46:31.224493 2020] [mpm_prefork:notice] [pid 63] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Fri Oct 30 14:46:31.224516 2020] [core:notice] [pid 63] AH00094: Command line: '/usr/sbin/apache2'
[Fri Oct 30 15:00:30.952533 2020] [mpm_prefork:notice] [pid 63] AH00169: caught SIGTERM, shutting down
[Fri Oct 30 15:00:32.068413 2020] [mpm_prefork:notice] [pid 624] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Fri Oct 30 15:00:32.068444 2020] [core:notice] [pid 624] AH00094: Command line: '/usr/sbin/apache2'`

/var/log/mysql/error.log
`2020-10-30T07:46:43.075862Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
2020-10-30T07:46:43.076688Z 0 [Warning] CA certificate ca.pem is self signed.
2020-10-30T07:46:43.076751Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
2020-10-30T07:46:43.076838Z 0 [Note] Server hostname (bind-address): '127.0.0.1'; port: 3306
2020-10-30T07:46:43.076870Z 0 [Note]   - '127.0.0.1' resolves to '127.0.0.1';
2020-10-30T07:46:43.076970Z 0 [Note] Server socket created on IP: '127.0.0.1'.
2020-10-30T07:46:43.247345Z 0 [Note] InnoDB: Buffer pool(s) load completed at 201030 14:46:43
2020-10-30T07:46:43.256814Z 0 [Note] Event Scheduler: Loaded 0 events
2020-10-30T07:46:43.279962Z 0 [Note] /usr/sbin/mysqld: ready for connections.
Version: '5.7.29-0ubuntu0.18.04.1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  (Ubuntu)`

But on nginx config error.log 
I found below start at this line.  **2020/10/30 16:52:34 [info] 533#0 ....** below.
I don't know what is meaning.

`2020/10/30 16:52:31 [info] 533#0: *3185 client 192.168.1.8 closed keepalive connection
2020/10/30 16:52:32 [info] 537#0: *3175 client 192.168.1.8 closed keepalive connection
2020/10/30 16:52:33 [info] 533#0: *3161 client 192.168.1.8 closed keepalive connection
2020/10/30 16:52:33 [info] 537#0: *3177 client 192.168.1.8 closed keepalive connection
2020/10/30 16:52:34 [info] 537#0: *3192 client 192.168.1.8 closed keepalive connection
**2020/10/30 16:52:34 [info] 533#0**: *3432 client prematurely closed connection (104: Connection reset by peer) while sending response to client, client: 192.168.1.8, server: localhost, request: "GET /live/5e83308eb639d/127.ts HTTP/1.1", host: "192.168.1.7:8080"
2020/10/30 16:52:34 [info] 537#0: *3345 client prematurely closed connection (104: Connection reset by peer) while sending response to client, client: 192.168.1.8, server: localhost, request: "GET /live/5e83308eb639d/127.ts HTTP/1.1", host: "192.168.1.7:8080"
2020/10/30 16:52:34 [info] 533#0: *3229 client prematurely closed connection (104: Connection reset by peer) while sending response to client, client: 192.168.1.8, server: localhost, request: "GET /live/5e83308eb639d/126.ts HTTP/1.1", host: "192.168.1.7:8080"
2020/10/30 16:52:34 [info] 537#0: *3442 client prematurely closed connection (104: Connection reset by peer) while sending response to client, client: 192.168.1.8, server: localhost, request: "GET /live/5e83308eb639d/126.ts HTTP/1.1", host: "192.168.1.7:8080"
2020/10/30 16:52:34 [info] 537#0: *3328 client prematurely closed connection (104: Connection reset by peer) while sending response to client, client: 192.168.1.8, server: localhost, request: "GET /live/5e83308eb639d/126.ts HTTP/1.1", host: "192.168.1.7:8080" .........  `

Here are my nginx config.

`  worker_processes  auto;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            #on_publish http://localhost/YouPHPTube/plugin/Live/on_publish.php;
                            #on_play http://localhost/YouPHPTube/plugin/Live/on_play.php;
                            #on_record_done http://localhost/YouPHPTube/plugin/Live/on_record_done.php;
                            on_publish http://localhost/plugin/Live/on_publish.php;
                            on_play http://localhost/plugin/Live/on_play.php;
                            on_record_done http://localhost/plugin/Live/on_record_done.php;

                        #recorder video{
                        #    record all;
                        #    record_path /var/www/tmp;
                        #    record_notify on;
                        #    record_max_size 2048M; 
                            #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
                        #    record_suffix -%d-%b-%y-%T.flv;
                        #}


                    }
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   
            }
    }
`

**Comment by DanielnetoDotCom** [comment]
can you check in the JS/Network console what file is failing to get?

if is the .ts or .m3u8 file? or maybe something else

**Comment by guitarpound** [comment]
Hi Daniel,

I found this error below but I don't know meaning.

![error](https://user-images.githubusercontent.com/57282919/97776842-45841980-1b9e-11eb-9860-b2e44b845fba.jpg)

**Comment by DanielnetoDotCom** [comment]
Is your live server running?

If is not disable the live plugin

**Comment by guitarpound** [comment]
Yes, The Live plugin is running.
When I stop jmeter.  The Live working normal.
