### ISSUE TITLE
How to show all playlists in each My Channel -> Playlists?

### ISSUE THREAD

**Issue by franranchito** [WWBN/AVideo#3937]
How to show all playlists in each user **My Channel -> Playlists** ?

No matter which options in the Playlists plugin or Site config, I only get a maximum 2 playlists shown, like in the demo site:
https://demo.avideo.com/channel/5f8721ada524f_5f8722da559ef_5f872405#channelPlayLists

- If there is only 1 playlist, it is correctly shown as 1 playlist
- If there are 2 playlists, it is correctly shown as 2 playlists
- If there are 3 or more playlists, **only the 2 oldest** playlists are shown

Thank you

**Comment by DanielnetoDotCom** [comment]
Hi

I am not sure what is the issue, please provide some screenshots to help me understand.

**Comment by franranchito** [comment]
From your demo site, if your demo site was my site, considering "Trailers" as the oldest playlist and "YPT Tutorials" as the second oldest playlist, I can't get any more recent playlist to be shown, even if there are more

![imagen](https://user-images.githubusercontent.com/19801224/97979871-3389bd00-1dd0-11eb-8cb0-0d45d00a1d26.png)

I know it is a problem of showing and not a problem of existing, because if I delete one of the two shown playlists (in this case, if I would delete "Trailers" or "YPT Tutorials"), the next older playlist takes its place

**Comment by DanielnetoDotCom** [comment]
Understood and confirmed.

Thanks for notice that. I just sent a fix.

**Comment by franranchito** [comment]
Thank you
