### ISSUE TITLE
Plugins Not Showing Up After Updating

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#3938]
I was updating the plugins to the latest version.  I usually update using FTP and that has not been an issue in the past.

However, this time after updating. No plugins will appear.  Any ideas how or why this occurred.

if anyone has a better method for updating plugin, I would be grateful if you could share it with me.

![plugin no results found](https://user-images.githubusercontent.com/739391/97767255-6e9aa080-1af1-11eb-9e31-e5b71ef3c4c0.png)

**Comment by akhilleusuggo** [comment]
do you see Upload a Plugin ? On the left up corner ?
Why would you need to use FTP ?

**Comment by DanielnetoDotCom** [comment]
@willpower68 check the log file

**Comment by willpower68** [comment]
@akhilleusuggo I tried uploading the file in left corner and it has never worked for me.

**Comment by willpower68** [comment]
@DanielnetoDotCom here log file.

I have tried updating by uploading zip files but it did not update the plugins.

<img width="1560" alt="logfile" src="https://user-images.githubusercontent.com/739391/97769016-d525bb80-1afd-11eb-855f-6a17cb1f80c6.png">

**Comment by akhilleusuggo** [comment]
this means your rtmp nginx server is off . Try to turn it on .

`sudo /usr/local/nginx/sbin/nginx`

**Comment by willpower68** [comment]
@akhilleusuggo Wow I had no idea. Thanks I will do that and hope I can figure out why the plugins aren't showing up in plugin section.

**Comment by akhilleusuggo** [comment]
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

The logs you provided , does not really represent the ''issue'' .
Make sure to clear the cache . If not , just past here the logs [ Hide sensitive data if there is any , IP , passwords ]

**Comment by willpower68** [comment]
@akhilleusuggo thanks.  I will do that. I appreciate you help.

**Comment by willpower68** [comment]
@DanielnetoDotCom @akhilleusuggo 

I appreciate you help.  Please understand my knowledge is not as deep as yours regarding the information you gave me about nginx server.  I added sudo /usr/local/nginx/sbin/nginx

I do not have screen shot but it said failed and it was in use.  I'm sure it's because of my lack of knowledge.  
I did a git pull and the plugins are now loading but it would be great to update plugins through the platform.  It never worked for me.

**Comment by akhilleusuggo** [comment]
you need to provide some logs or issues . we can't just guess .

**Comment by willpower68** [comment]
@DanielnetoDotCom   @akhilleusuggo Does this give you information you need?

![logfile](https://user-images.githubusercontent.com/739391/97792763-07482380-1bb9-11eb-9a7b-897190a1eda7.png)

**Comment by DanielnetoDotCom** [comment]
@willpower68 I guess you are mixing things here 

You did upload a zip file for what? if you are updating, make sure you use the `git pull` command, otherwise, you can break your installation.
you must provide the log files at the moment you try to access the plugins page.

**Comment by willpower68** [comment]
@DanielnetoDotCom @akhilleusuggo 

Problem:  Not able update plugins from website


![Screenshot 2020-11-03 162606](https://user-images.githubusercontent.com/739391/98049086-056ea200-1dfd-11eb-86f0-e7edd32fe5e4.png)


 
![upload](https://user-images.githubusercontent.com/739391/98049137-1a4b3580-1dfd-11eb-91d6-ad2e5e8c2686.png)


After uploading the zip file.  There is no indication that I can update plugin.  It still says update available
![upload-available-now-what](https://user-images.githubusercontent.com/739391/98049209-3b138b00-1dfd-11eb-8d3b-7f24eed91bb9.png)

Log Files;

![log-file-3](https://user-images.githubusercontent.com/739391/98049340-79a94580-1dfd-11eb-8f26-0bda12b337cc.png)

![log-file 2](https://user-images.githubusercontent.com/739391/98049360-862d9e00-1dfd-11eb-8da2-9664c0e0ef15.png)

![log file 1](https://user-images.githubusercontent.com/739391/98049377-8e85d900-1dfd-11eb-8be4-e713e8275f13.png)

**Comment by DanielnetoDotCom** [comment]
try to manually delete the plugin folder then upload again

**Comment by willpower68** [comment]
@DanielnetoDotCom @akhilleusuggo 

deleted plugin folder and upload again.  Plugin still does not update when uploading zip file.

**Comment by DanielnetoDotCom** [comment]
So, when you upload it keeps the same version?

are you sure you are uploading the correct file?

if it is not uploading it may be a permission problem or a missing zip lib for PHP (you must check the logs)

**Comment by willpower68** [comment]
@DanielnetoDotCom 

Yes, it keeps the same version when I upload plugin zip file.  Yes, I am uploading the correct file.  
I will check log file again.

**Comment by DanielnetoDotCom** [comment]
You need to download the plugin again from https://youphp.tube/marketplace/

**Comment by willpower68** [comment]
@DanielnetoDotCom 

I always get the updated plugin from the marketing place.
