### ISSUE TITLE
Video quality issues.

### ISSUE THREAD

**Issue by ZandercraftGames** [WWBN/AVideo#3939]
**Describe the question**
Even though videos are uploaded in 1080p and all resolutions are available from the encoder (higher and lower), it always seems to show a very low resolution regardless of connection speed and ability. I do not have the VideoQualitySelector plugin, but that shouldn't be needed for the quality to run higher, only to give a selection of quality. How do I fix this?

**Screenshots**
![image](https://user-images.githubusercontent.com/28664144/97784224-5ec3a080-1b73-11eb-9b38-3f8222c229d6.png)

**Comment by DanielnetoDotCom** [comment]
you need the VideoResolutionSwitcher plugin

you can get it on https://youphp.tube/marketplace/

**Comment by ZandercraftGames** [comment]
@DanielnetoDotCom As I already stated, it shouldn't default to the lowest resolution simply because I haven't paid $27 for the option to add a user-sided button for changing the resolution. There should either be a backend option allowing for a default resolution to be shown, or it should default to the highest resolution instead of making the platform seem quite unappealing since the upload resolution doesn't matter and it only shows the lowest resolution. This seems like a bit of oversight or like there is a bug in the backend currently making it default to the lowest possible resolution.

**Comment by ZandercraftGames** [comment]
May also be Cloudflare causing it to interpret the connection as having a poor speed (or caching). Could that be the issue?

**Comment by akhilleusuggo** [comment]
if you're not going for the plugin , the on the encoder , disable the rest of resolutions , and keep only the higher to encode . This will result in faster time encoding , and no issues .

**Comment by DanielnetoDotCom** [comment]
Make sure you uncheck **showOnlyEncoderAutomaticResolutions**

than check **doNotShowEncoderResolutionLow** and  **doNotShowEncoderResolutionSD**, so you will have only the HD resolution 

![image](https://user-images.githubusercontent.com/18009293/97977108-72a51780-1daa-11eb-9bb3-6de653f922fb.png)

**Comment by ZandercraftGames** [comment]
@DanielnetoDotCom @akhilleusuggo To the both of you, thank you very much for your replies. I appreciate you taking the time out of your days to help me. Dont get me wrong, I would love to support the AVideo project, I just dont think that a paid plugin should be required for the platform to show high resolution video. I will try the options you suggested, I already have the one that Daniel suggested enabled. Thanks guys!
