### ISSUE TITLE
Move Main Menu to right side

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3940]
I would really like to move the main menu to the right side so my RTL menu will be displayd in the correct side. Also I would like the menu to remain open all the time. The RTL template is still not complete including the tranlations. I will work on those to complete them, however I would like the template to be more RTL friendly. Which files I should work with and what classes should I concentrate on.

Best Regards,

**Comment by DanielnetoDotCom** [comment]
This requires some CSS knowledge, maybe some code change. I do not know how-to guide you on this.

**Comment by guymass** [comment]
OK  thanks I will try on a development copy. I also edited the Hebrew translation a bit, if you want I will email you the update so you can edit yours, just minor fixes in translation.

**Comment by DanielnetoDotCom** [comment]
> OK thanks I will try on a development copy. I also edited the Hebrew translation a bit, if you want I will email you the update so you can edit yours, just minor fixes in translation.

that will be awesome, try to make a git pull request


https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by guymass** [comment]
Can you point me to where are the translation files for the menu item Add Article and those small info on hover popups so I can translate them as well.

![Screen Shot 5781-02-17 at 17 55 18](https://user-images.githubusercontent.com/58882903/98134118-15eb4f00-1ec7-11eb-8168-585b2cd5e3f1.jpg)

**Comment by DanielnetoDotCom** [comment]
Add article should be 

$t['Add Article'] = 'heb_value';

https://github.com/WWBN/AVideo/blob/c1943c661711299bdd78ee0376c21c2d7a34086d/view/include/navbar.php#L443

Make sure your key is case sensitive

**Comment by guymass** [comment]
OK thank you very much!
