### ISSUE TITLE
acessing /plugin/Live when using nginx + php-fpm makes php-fpm crash

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3942]
When trying to:

Access /plugin/Live when using nginx + php-fpm makes php-fpm crash! Have you been able to solve this issue or do you know what might be the reason for php-fpm not liking nginx? The Live plugin will only work with apache for some reason and we would like to understand why we cannot simply use only NGINX.

**Comment by guymass** [comment]
![Screen Shot 5781-02-14 at 21 04 37](https://user-images.githubusercontent.com/58882903/97811912-41cbc200-1c86-11eb-9499-2d61a2003648.jpg)

Any suggestion regarding those errors?

**Comment by DanielnetoDotCom** [comment]
Disable the livechat plugin, this is deprecated and if it is not correctly configured may slow down your site a lot.
