### ISSUE TITLE
Social Media Embeds

### ISSUE THREAD

**Issue by qome** [WWBN/AVideo#3948]
**Is your feature request related to a problem? Please describe.**
It would be nice if a player was included when linking to a video in Discord, Facebook, Twitter, etc.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/58382620/97861867-14086c80-1cca-11eb-9c22-595132aa49ce.png)

**Describe alternatives you've considered**
I'm unaware of any alternatives, except writing my own plugin.

**Additional context**
I know there's something about a Twitter player in the settings but I do not believe it satisfies this requirement for other sites. I believe this is oEmbed territory: https://oembed.com/

**Comment by palich91** [comment]
I support, it is really necessary

**Comment by DanielnetoDotCom** [comment]
If you want to have a player you have to request it on Discord, Facebook, Twitter, etc

there is nothing we can do on our side.

**Comment by qome** [comment]
You're incorrect. Discord, Facebook, and Twitter all support the oEmbed standard. Web developers have to implement it on their websites.

**Comment by DanielnetoDotCom** [comment]
So what is the correct standard?

**Comment by qome** [comment]
See https://oembed.com/#section5

An example is provided that shows you can expose HTML (the existing embedded player) to sites.

**Comment by DanielnetoDotCom** [comment]
I will check

**Comment by qome** [comment]
Hopefully I'm correct and this doesn't require Discord et al to support it. Best of luck.

**Comment by DanielnetoDotCom** [comment]
It is not clear to me, how do we specify the API endpoint for oembed?

**Comment by DanielnetoDotCom** [comment]
Not sure if it will work, but now we have oembed links on the HTML

**Comment by DanielnetoDotCom** [comment]
Look like works here http://debug.iframely.com/

**Comment by qome** [comment]
Perhaps Discord etc do need to support the feature on their end. At this time a player doesn't appear in Discord or Facebook. Thank you for looking into it and sorry for being incorrect.
