### ISSUE TITLE
Live Stream constantly Buffering

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3949]
Hi Daniel how are you?

I have been trying to install a new server to move my old one to a stronger server. I have installed everything fresh and clean however I have an issue that prevents the Live stream from playing on the site channel page and it doesn't matter what configuration I use or even what nginx version I use as I even downgraded the script to an older AVideo version.

![Screen Shot 5781-02-15 at 13 28 18](https://user-images.githubusercontent.com/58882903/97863849-5785c980-1d10-11eb-94a5-05be045bb894.jpg)
![Screen Shot 5781-02-15 at 1 02 51](https://user-images.githubusercontent.com/58882903/97863874-5fde0480-1d10-11eb-9c35-904bbf9db674.jpg)
![Screen Shot 5781-02-15 at 13 32 25](https://user-images.githubusercontent.com/58882903/97863922-75532e80-1d10-11eb-8dcd-2a0596f0d3cb.jpg)

I can connect with OBS, Stream and record the stream, but no one is able to view my live stream unless its on VLC with the m3u8 url and very choppy and constantly buffering.

its like something is choking the stream from being sent back to the livestream player.

Any suggestions into what this might be or what to look for? maybe I need to use specific NGINX version?

This is a fresh clean install on a 32GB DDR4 very strong server with 3Gbit uplink connection so resources are not the issue here.

**Comment by DanielnetoDotCom** [comment]
if you click on the index.m3u8 file what is the response?

**Comment by guymass** [comment]
Here are my config files:

Nginx.conf:

user www-data www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 2048;
}

http {
        include mime.types;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        server_names_hash_bucket_size 128;
        client_max_body_size 2048M;
        default_type application/octet-stream;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        gzip on;
        include avideohttp.conf;
        include /etc/nginx/conf.d/*.conf;
        #include /etc/nginx/sites-enabled/*;
}

include avideolive.conf;

# avideolive.conf: We were trying all sorts of config parameter!

rtmp {
    access_log /var/log/nginx/rtmp_access.log;
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incomi>
                    application live {
                            allow play all;
                            live on; #

                     # COMMENT HLS FOR ADAPTATIVE MODE
						                hls on;
                            hls_type live; # guy added
                            #hls_fragment_naming system;
                            hls_nested on;
                            hls_path /HLS/live;
                            hls_playlist_length 60m;
                            hls_fragment 10s;

                        # Guy adding configurations for tests
                            hls_sync 100ms;
                            hls_cleanup on;


														interleave off;
														meta on;
														wait_key on;
														wait_video on;
														idle_streams off;
														sync 300ms;
														session_relay on;
														allow publish all;
														allow play all;
														max_connections 1000;


                ## == DASH == ##
                dash off;
                # dash_nested on;
                # dash_path /var/livestream/dash;
                # dash_fragment 10s;
                # dash_playlist_length 60s;
                # dash_cleanup on;


                        on_publish http://localhost/plugin/Live/on_publish.php;
                        on_play http://localhost/plugin/Live/on_play.php;
                        on_record_done http://localhost/plugin/Live/on_record_done.php;

										#ADAPTATIVE MODE
                   #     exec ffmpeg -i rtmp://localhost/live/$name 
                   #         -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:240 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1200k -b:a 96k -r 20 -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_low  
                   #         -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:480 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 2400k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_mid  
                   #         -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:720 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 4200k -bufsize 100000k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi;

                           recorder video{
                                record all;
                                record_path /var/www/tmp;
                                record_notify on;
                                record_max_size 2048M;
                                record_suffix -%d-%b-%y-%T.flv;
                            }
                    }


						#ADAPTATIVE MODE
#            application adaptive {
#										live on;
#                    hls on; 
#
#                    hls_path /HLS/live;
#                    hls_nested on;
#
#                    allow play all;
#                    allow publish 127.0.0.1;
#                    deny publish all;
#										hls_type live; # guy added
#										hls_playlist_length 60m;
#										hls_fragment 10s;
#
#								# Guy adding configurations for tests
#										hls_sync 100ms;
#										hls_cleanup on;
#
#
#                    hls_variant _low BANDWIDTH=400000;
#                    hls_variant _mid BANDWIDTH=2100000;
#                    hls_variant _hi  BANDWIDTH=4200000;
#                }
            }
    }


avideohttp.conf:

server {
    listen 127.0.0.1:8880;
    client_max_body_size 2048M;
location /live {
            add_header 'Cache-Control' 'no-cache';
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length';

            if ($request_method = 'OPTIONS') {
                    add_header 'Access-Control-Allow-Origin' '*';
                    add_header 'Access-Control-Max-Age' 1728000;
                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                    add_header 'Content-Length' 0;
                    return 204;
            }
            types {
                    application/vnd.apple.mpegurl m3u8;
            }
            alias /HLS/live;
    }
    location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
    }
    location /stat.xsl {
            root html;
    }
    location /control {
            rtmp_control all;
    }
    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
    location / {
            root   html;
            index  index.html index.htm;
    }   

    location ~ \.php$ {
           include /etc/nginx/snippets/fastcgi-php.conf;
           fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
    }
}

**Comment by guymass** [comment]
> if you click on the index.m3u8 file what is the response?

When I calick the m3u8 file it asks to save a file on my computer.

**Comment by DanielnetoDotCom** [comment]
I am not seeing any .ts files in your log

I am asking you to share this 

![image](https://user-images.githubusercontent.com/18009293/97896927-830ab300-1d14-11eb-82c6-cfeda94689b6.png)

**Comment by guymass** [comment]
![Uploading Screen Shot 5781-02-15 at 22.09.46.jpg…]()

**Comment by DanielnetoDotCom** [comment]
No image

**Comment by guymass** [comment]
I am going to stream constantly for the next couple of hours to test. My stream is at this url:
https://live.ahava528.com/live/1/Admin

please let me know if you are able to view it and maybe you can help me solve this issue.

**Comment by DanielnetoDotCom** [comment]
I went there, it starts to play and then stops.

I notice it plays only 0.ts and 1.ts and stops.


try to stop Nginx, delete the folder /HLS/Live/5f9d30318c88f/ and start again. or maybe just recreate the stream key.

If still not working, I can only imagine it is a network problem.

I cannot see any other reason

![image](https://user-images.githubusercontent.com/18009293/97915632-8d3aaa80-1d30-11eb-82cc-46904634ac0a.png)

**Comment by guymass** [comment]
Also try to play any video and you will see none play well and some don't play at all. There is an issue with the way the player buffers the video is not working well. I am not sure if its a Java or PHP or NGINX or APACHE issue to be honest.

It would be helpful to know what is the best nginx version to use and if there are other version dependent issues we need to watch for when installing this script. We could help contribute more if we knew more about how the script is doing its work.

**Comment by guymass** [comment]
I don't think its network because the page loads very fast and starts the video very fast and it is buffering but it just not continuing to play. I can see the video is completely loaded and the player still doesn't return to play the stream. This is not a network nor a resources problem, this is either the script itslef or the configuration.

**Comment by guymass** [comment]
OK I have also involved the hosting support and we are going to try and resolve this also from our end, however we also need to consider other options.

**Comment by guymass** [comment]
This is my server specification:

![Screen Shot 5781-02-15 at 23 06 43](https://user-images.githubusercontent.com/58882903/97919225-1e754580-1d60-11eb-9b54-757c7d7b5f2d.jpg)

I think this should be good enough to run the script, am I wrong?

**Comment by DanielnetoDotCom** [comment]
the hardware looks very good to me

**Comment by guymass** [comment]
we are trying now to set a reverse proxy for those .ts files and maybe that is the fix we needed or missed.

**Comment by guymass** [comment]
OK proxy didn't work!

we tried to play out index.m3u8 on the following site to test the file and the stream works very well!
https://castr.io/hlsplayer

This was the stream url:
https://rtmp.ahava528.com:8443/live//5fa079d83a500/index.m3u8

So this tells us the problem is with the player or the script itself.

**Comment by guymass** [comment]
A second test was made with another HLS player called mpv and it also ran the stream very good.
mpv https://rtmp.ahava528.com:8443/live//5fa079d83a500/index.m3u8

This can only mean that the Javascript player has issues with playing the stream. We need a  fix here which only you can do.

**Comment by DanielnetoDotCom** [comment]
Try change this parameters in your nginx.conf

change the key restart nginx and try again

hls_playlist_length 15m;
hls_fragment 4s;

**Comment by DanielnetoDotCom** [comment]
If you can leave the live running I will make some tests

**Comment by DanielnetoDotCom** [comment]
I can see one of the reasons why it is buffering...

you are transmitting in 1920X1080 you cannot guarantee a fluid live with this.

try the adaptive bitrate https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream

**Comment by guymass** [comment]
OK we have adaptive setup and also tested 
hls_playlist_length 15m;
hls_fragment 4s;

with adaptive its not playing, without adaptive its playing.

**Comment by DanielnetoDotCom** [comment]
when you add the adaptive on the nginx.conf, make sure you also check the adaptive option in the plugin parameters and then clear the cache.

**Comment by guymass** [comment]
I have done this of course. I have testes all three stream for low, medium and hires with mpv and they all work great.

**Comment by DanielnetoDotCom** [comment]
then do reduce the stream resolution, do not use 1080p

try 720p

**Comment by guymass** [comment]
So we have got to the point where everything is working good most of the time. We are still testing the limits, however I must say that during our tests and investigations we have come to conclude that there is something wrong with the player you are using and that some other players were working much better. Maybe you should take it into consideration to see how it can be improved or maybe how to fine tube those configuration parameters to get the best results. I will keep posting any new data but for now have at least overcome our main issue so thank you very much for your help.

God bless,

**Comment by DanielnetoDotCom** [comment]
all web players tested, include the ones you suggested buffer for me.

the problem is your resolution, or you go to the adaptive mode or you reduce the resolution.

**Comment by guymass** [comment]
I am using now adaptive mode, the resolution is being handled there. Currently, as I said it is working fine, but we will have to see how it works under stress.

**Comment by DanielnetoDotCom** [comment]
The adaptive stress more the server then the way you were transmitting.

the resolution you were transmitting stress the client/browser but not the server (maybe only bandwidth) that is why it was buffering, a web client cannot handle that resolution.

**Comment by akhilleusuggo** [comment]
There's 2 things that will buffer a stream from NGINX .
Disk ; Low IOps ( can't generate that much hls_fragments constantly = buffering 
IPS ; It doesn't mater how much GB/s your IPS does offer you , if the routing sucks , then you will buffer ./

**Comment by guymass** [comment]
Disk ; Low IOps:
 
 $ sudo hdparm -Tt /dev/sda

/dev/sda:
 Timing cached reads:   22548 MB in  1.99 seconds = 11330.02 MB/sec
 Timing buffered disk reads: 1590 MB in  3.00 seconds = 529.39 MB/sec

$ sudo hdparm -Tt /dev/sdb

/dev/sdb:
 Timing cached reads:   23760 MB in  1.99 seconds = 11942.57 MB/sec
 Timing buffered disk reads: 1626 MB in  3.00 seconds = 541.34 MB/sec

Speeds for each disks

CPU clock speed:  $  lscpu | grep MHz 
CPU MHz:                         1214.199
CPU max MHz:                     3500.0000
CPU min MHz:                     1200.0000

3.5GHz

"IPS ; It doesn't mater how much GB/s your IPS does offer you , if the routing sucks , then you will buffer "./  —> You mean ISP I suppose. Thats what We are using adaptive mode for, for slower routes we have the lower quality but smaller transfer sizes.


Here is how we configured NGINX:

rtmp {
    access_log /var/log/nginx/rtmp_access.log;
            server {
                    listen 1935;
                    chunk_size 4000;
                    #creates our "live" full-resolution HLS videostream from our incomi>
                    application live {
                            allow play all;
                            live on; #

														interleave off;
														meta on;
														wait_key on;
														wait_video on;
														idle_streams off;
														sync 300ms;
														session_relay on;
														allow publish all;
														allow play all;
														max_connections 1000;


                ## == DASH == ##
                dash off;
                # dash_nested on;
                # dash_path /var/livestream/dash;
                # dash_fragment 10s;
                # dash_playlist_length 60s;
                # dash_cleanup on;


                        on_publish http://localhost/plugin/Live/on_publish.php;
                        on_play http://localhost/plugin/Live/on_play.php;
                        on_record_done http://localhost/plugin/Live/on_record_done.php;

										#ADAPTATIVE MODE
                            exec ffmpeg -i rtmp://localhost/live/$name 
                                -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:240 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1200k -b:a 96k -r 20 -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_low  
                                -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:480 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 2400k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_mid  
                                -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:720 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 4200k -bufsize 100000k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi;

                           recorder video{
                                record all;
                                record_path /var/www/tmp;
                                record_notify on;
                                record_max_size 2048M;
                                record_suffix -%d-%b-%y-%T.flv;
                            }
                    }


                #ADAPTATIVE MODE
                application adaptive {
                    live on;
                    hls on;
                    hls_type live; # guy added
                    #hls_fragment_naming system;
                    hls_nested on;
                    hls_path /HLS/live;
                    hls_playlist_length 15m;
                    hls_fragment 4s;

                    # Guy adding configurations for tests
                    hls_sync 100ms;
                    hls_cleanup on;


                    allow play all;
                    allow publish 127.0.0.1;
                    deny publish all;

                    hls_variant _low BANDWIDTH=400000;
                    hls_variant _mid BANDWIDTH=2100000;
                    hls_variant _hi  BANDWIDTH=4200000;
                }
            }
    }

**Comment by guymass** [comment]
I don't want to open another issue but there's a bug not displaying the correct amount of videos on my server.
![Screen Shot 5781-02-19 at 0 27 36](https://user-images.githubusercontent.com/58882903/98303620-11a65b00-1fc7-11eb-8b1b-34feab2809c8.jpg)

I assure you I have more than 1 video ;-)

**Comment by akhilleusuggo** [comment]
You're opening too many things at once , and I'm confused . Can't you stay at one thing ? 
On your first config , you're using adaptive mode , but you're comenting the FFMPEG line , witch mean you're _NOT_ transcoding ( just consuming more IO )  . On your second one , you're using adaptive and transcoding  . Witch one are you using ?

**Comment by guymass** [comment]
I was trying both configurations that is why some are commented out. Currently I am using adaptive which works better when streaming to different resolutions and network connection speeds.

**Comment by guymass** [comment]
Hi Daniel,

We've been trying to integrate jitsi into the site, but we are having
issues with jibri for recording and streaming the conference. Any chance
you get give us a clue into how this can be done? Is it an nginx config?
Please, we really need this feature and currently we can only use it as a
video chat.
Just a push in the right direction into where we should concentrate our
efforts or maybe what specific version to install perhaps?

My best regards, thank for all the hard work!

Guy.
