### ISSUE TITLE
Video Resolution Converter does not work on Live Stream

### ISSUE THREAD

**Issue by abed-ahmed** [WWBN/AVideo#3950]
I have a problem. I bought the addition of the quality adapter in the attached picture, but I ran into a problem that adding a quality adapter works well on the video, but it does not work on the Live Stream?
Is there an additional other working on the Live Stream?
![التقاط](https://user-images.githubusercontent.com/72515889/97878165-f1587100-1d26-11eb-89e4-cfa9e5d47d12.JPG)

**Comment by DanielnetoDotCom** [comment]
If you have the VideoHLS and you use the [adaptive Live](https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream), you may see a resolution switcher.

The VideoResolutionSwitcher is for VOD only
