### ISSUE TITLE
Disable Wallet Transfer

### ISSUE THREAD

**Issue by qome** [WWBN/AVideo#3951]
**Describe the question**
Is it possible to disable the "transfer" feature of the wallet plugin?

I'm concerned this feature would open my site up to regulation as a financial institution. I would prefer to only allow users to add funds, not withdraw or transfer to another user.

**Comment by DanielnetoDotCom** [comment]
uncheck this option 
![image](https://user-images.githubusercontent.com/18009293/97908403-67f46f00-1d25-11eb-967f-4a6076d7e37d.png)

there is no option to disable the transfer between users.
