### ISSUE TITLE
How to make Encoder use MariaDB via Unix socket?

### ISSUE THREAD

**Issue by jyrihovila** [WWBN/AVideo#3952]
Hi!

I had to transfer an already existing and fully working installation of AVideo/YouPHPTube to another server. On this new server, the database (MariaDB) is only accessible via a Unix socket.

The main site is working properly with the socket connection when I simply comment out the line $mysqlHost in the avideo configuration file. Obviously, I have the parameter mysqli.default_socket defined properly at php.ini: it's pointing to the appropriate mysql.sock file.

However, the Encoder is not working even though I've similarly commented out the line $mysqlHost in the encoder configuration file. After typing in the username and the password (to the encoder login page), the "Processing" pop-up just hangs on the screen until finally Apache gives a time out since the PHP back-end is not responding.

In the avideo encoder log I can only see this:

login.json: Login::run
Login::run (username, ***, https://my.domain/, false)
isLogged: false false

Apache error log has this to say:

[proxy_fcgi:error] [pid xxxxxx:tid xxxxxxxxxx] (xxxxx)The timeout specified has expired: [client xxx.xxx.xxx.xxx:12345] AH01075: Error dispatching request to : (polling)

I noticed there is a small difference in how YouPHPTube and YouPHPTube-Encoder initiate the database connections:

YouPHPTube: $global['mysqli'] = new mysqli($mysqlHost, $mysqlUser, $mysqlPass, $mysqlDatabase, @$mysqlPort);
YouPHPTube-Encoder: $global['mysqli'] = new mysqli($mysqlHost, $mysqlUser,$mysqlPass,$mysqlDatabase);

As you can see, in the main software the connection initialization includes the fifth parameter, @$mysqlPort.

I tried the obvious and added @$mysqlPort to the database connection initialization of YouPHPTube-Encoder (objects/include_config.php) but that didn't do anything.

I also tried adding a line $mysqlPort = ''; to the encoder configuration file, which (after trying to log in) results in the following error displayed in the browser: SELECT f.*, e.* FROM encoder_queue e LEFT JOIN formats f ON f.id = formats_id WHERE (status = 'encoding' OR status = 'downloading' OR status = 'queue' OR status = 'error') ORDER BY priority ASC, e.id ASC \nError : ()

Any ideas how to make the encoder use the database socket connection properly?

**Comment by jyrihovila** [comment]
Hi!

I still haven't found a solution to this problem, and it's blocking us from using the Encoder on a server that only allows connections to the database over a Unix socket.

**Comment by Miriup** [comment]
For everyone's reference: One option is setting `default_socket` in `mysqli` section of `php.ini` (see https://www.php.net/manual/en/mysqli.construct.php).
