### ISSUE TITLE
MariaDB - "Error deleting user: Table '[mydbname].users' doesn't exist

### ISSUE THREAD

**Issue by TinglyTube** [WWBN/AVideo#3953]
Trying to install on a fresh LAMP stack with MariaDB, and can't get past the install screen without the following error regarding the database, I enter the DB info and it does create it, but gives this error "Error deleting user: Table '[mydbname].users' doesn't exist"

**Comment by DanielnetoDotCom** [comment]
Make sure your database user can create tables.

**Comment by TinglyTube** [comment]
> Make sure your database user can create tables.

It's connecting as the root user, which has all privileges.

**Comment by DanielnetoDotCom** [comment]
for some reason, your table was not created, check on the apache logs

**Comment by TinglyTube** [comment]
> for some reason, your table was not created, check on the apache logs

There's quite a lot of SQL errors :/ but the first is
`Installation: SQL ERROR Invalid default value for 'created'` I think this may be the one describing the issue? 

Thanks.

**Comment by DanielnetoDotCom** [comment]
I do not know what error is this, try to google or provide more logs

**Comment by webbymaster** [comment]
> > по какой-то причине ваша таблица не была создана, проверьте журналы apache
> 
> Ошибок SQL довольно много: / но во-первых,
> `Installation: SQL ERROR Invalid default value for 'created'`я думаю, это может быть та, которая описывает проблему?
> 
> Спасибо.

My friend! If you decided to, help, tell me how!!! I have the same problem ((

**Comment by TinglyTube** [comment]
> > > for some reason, your table was not created, check on the apache logs
> > 
> > 
> > There's quite a lot of SQL errors :/ but the first is
> > `Installation: SQL ERROR Invalid default value for 'created'` I think this may be the one describing the issue?
> > Thanks.
> 
> **My friend! If you decided to, help, tell me how!!! I have the same problem ((**

Hi, we weren't able to fix this sadly, we went ahead and instead developed our own platform in-house. Hope you're able to resolve the/your problem.

**Comment by DanielnetoDotCom** [comment]
Hi

I am not sure what is this problem, but again, it looks like a bad MySQL configuration (probably the user), If you want you can hire us to install it for you. https://www.youphptube.com/services
If you want to hire us you MUST provide a clean Ubuntu server without any type of control panel

**Comment by Maagiiix** [comment]
Hi there

I am straggling with this error "Error deleting user: Table 'aVideo.users' doesn't exist" when trying to installon NAS Syno

Many thanks for any help

**Comment by TinglyTube** [comment]
New Ticket Created
--------------------------------------------------

Hello Maagiiix,

This email confirms your new support ticket: #60392-8a7348

Subject: Re: [WWBN/AVideo] MariaDB - "Error deleting user: Table '[mydbname].users' doesn't exist (#3953)
Department: General Support
Priority: Low

Email notification will follow when this ticket has been updated by a member of staff.

To view your tickets at any time log into your account portal:
https://www.tinglytube.com/support/

Kind regards,

--------------------------------------------------
TinglyTube
https://www.tinglytube.com/support

Free HelpDesk System Powered by Maian Support
https://www.maiansupport.com
