### ISSUE TITLE
User control plugin error

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#3954]
After the update to the latest version, the tables should be reinstalled, although the Plgun was already present. But it creates an error.

![image](https://user-images.githubusercontent.com/52116237/97923249-f97fd300-1d5d-11eb-8260-939463516add.png)

**Comment by DanielnetoDotCom** [comment]
your database user does not have permission to create tables.

**Comment by Donnerstein** [comment]
Yes, I thought so too, but it's not.
![image](https://user-images.githubusercontent.com/52116237/97946360-8476c280-1d8a-11eb-80b6-766b92d0a04d.png)

**Comment by DanielnetoDotCom** [comment]
Hi, please download the User_controll plugin again.

I guess it is an error that is already fixed.
