### ISSUE TITLE
White background on dark themes. (Articles Plugin)

### ISSUE THREAD

**Issue by ZandercraftGames** [WWBN/AVideo#3955]
**Describe the bug**
When using dark themes, the articles written using the articles have a white background behind their text.

**To Reproduce**
1. Use the Netflix theme
2. Enable articles plugin
3. Write text and publish
4. Go to the article and see the issue.

**Expected behavior**
The background of the text should be transparent or follow that of the selected option in the rich-text article editor.

**Screenshots**
![image](https://user-images.githubusercontent.com/28664144/97924050-0afcb700-1d2d-11eb-8d7e-99b34382bdc7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86.0.4240.111 (Official Build) (64-bit) (cohort: Stable)

**Additional context**
Likely just a simple CSS fix.

**Comment by DanielnetoDotCom** [comment]
Hi, you can add a custom CSS like this https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css

**Comment by ZandercraftGames** [comment]
I think the main issue is it's using the default for the element
