### ISSUE TITLE
Video Resolution Switcher not appear on HLS Video When I use YPTStorage

### ISSUE THREAD

**Issue by zauklian** [WWBN/AVideo#3958]
I upload HLS Video to YPTStorage, Video Resolution Switcher not appear.
![image](https://user-images.githubusercontent.com/538670/98100745-408bd680-1ecc-11eb-94cb-6d402006ee5b.png)

When I move from YPTStorage to Local Storage, Video Resolution Switcher is appear.
![image](https://user-images.githubusercontent.com/538670/98101089-b6903d80-1ecc-11eb-8582-ecd4deb3ec6d.png)

Please help me!
Thanks

**Comment by DanielnetoDotCom** [comment]
Yes, it does not support yet, but it will work. I am aware of it and we will have an update in the future to resolve that.
