### ISSUE TITLE
I get an error when encoding a file

### ISSUE THREAD

**Issue by amadomora** [WWBN/AVideo#3959]
**Describe the bug**

I am trying to encode a video to upload it to my streamer but I vote for this error
**To Reproduce**

**Expected behavior**

**Error Logs**
Provide the log files at the moment you found the issue.
If you are not sure how to find the log file, please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Screenshots**
![encoder1](https://user-images.githubusercontent.com/44752480/98128556-0ef01c80-1e86-11eb-97ea-7ec8cc9e6a88.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DanielnetoDotCom** [comment]
Look like your encoder is a old one.

try to install the latest. (version 3.3)

![image](https://user-images.githubusercontent.com/18009293/98133460-64372880-1e9c-11eb-92f7-98b8af0a81e9.png)

**Comment by amadomora** [comment]
I download the version that is in github   >>>  https://github.com/WWBN/AVideo-Encoder/archive/master.zip,  and That version doesn't tell me how I update it, where do I get a link to download version 3.3?

**Comment by DanielnetoDotCom** [comment]
do not download the zip, use the `git clone` command.

**Comment by amadomora** [comment]
I downloaded it from git clone but it votes me a 500 error
![encoder2](https://user-images.githubusercontent.com/44752480/98147060-06a1dc80-1e9a-11eb-932d-4a5a86a39d9a.png)

**Comment by amadomora** [comment]
Hi I had to mount the "encoder" on the same server that I have streaming ", first I left an active encoder in my server but other people are encoding videos
![encoder1](https://user-images.githubusercontent.com/44752480/98268105-1f71c700-1f5a-11eb-91a8-6ac7e1a67587.png)
The option to add other encoders does not appear so the one of my vps added it through the database
![encoder2](https://user-images.githubusercontent.com/44752480/98268238-47f9c100-1f5a-11eb-8a52-060df3739e93.png)
but, it tells me that my vps server has my encoder offline and I install it according to the manual
![encoder3](https://user-images.githubusercontent.com/44752480/98268353-6790e980-1f5a-11eb-8ef3-8ffe12bc2c31.png)
que estare haciendo mal ???
