### ISSUE TITLE
Cannot setup Meet

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#3960]
I am trying to setup a Meet conference. When I creat a new room I can join in but when I share the url people cannot access it as it is requesting a password I didn't set.Also when I do set a password it doesn't work for them or they are stuck at connecting...

![Screen Shot 5781-02-17 at 18 49 08](https://user-images.githubusercontent.com/58882903/98141184-01ab5000-1ecf-11eb-974f-1f8d6271de86.jpg)

Another issue is that trying the Europe Jitsi server I get "You are not allowed to be here" message.

Here are some screenshots but I am not sure what they could say. I am not sure what is wrong and I really need that service.

**Comment by DanielnetoDotCom** [comment]
Where did you grab this share link from?

Make sure you share the links from here 
![image](https://user-images.githubusercontent.com/18009293/98141581-88e3ce00-1ea5-11eb-85f9-02844ad1e97c.png)

**Comment by guymass** [comment]
Yes I shared them from there and also from within the session itself it provides the links. I also asked the other admins to enter through that green button but they couldn't get pass a login page. When I switched to north america it was working for me but they couldn't join at all.
