### ISSUE TITLE
If the "EnableMinifyJS" function is activated, the theme setting is no longer used

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#3966]
It's a bug, the error also occurs on the demo page.
If the "EnableMinifyJS" function is activated, the theme setting is no longer used

**Comment by DanielnetoDotCom** [comment]
I do not recommend you to use EnableMinifyJS, it still experimental

**Comment by Donnerstein** [comment]
all right. it had only worked without problems until now.

greetings
