### ISSUE TITLE
Pre existing nginx rtmp

### ISSUE THREAD

**Issue by djirving82** [WWBN/AVideo#3967]
Is it possible to use an existing installation of a nginx rtmp server for AVideo live streaming? Suggestions for how to link the two?

**Comment by akhilleusuggo** [comment]
I wrote something about this on wiki . I though I was the only one looking for something like this , but maybe useful for you too .

https://github.com/WWBN/AVideo/wiki/One-NGINX-RTMP-Server-for-Multiple-AVideo-platforms

Just to make things clear . Let's say 2-3 friends have an AVideo platform , and they don't wanna hosts 3 separated rtmp-nginx servers . They can use only 1 server for unlimited AVideo platform . (limit = hardware/ bandwidth ) .

For now does not support adaptive mode ( it does , but need change things on plugins manually )
