### ISSUE TITLE
Can not login from AVideo to AVideoEncoder (using IE11) part2

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#3970]
I installed our customer's LAB. AVideo Ver9.7 and Avideo-Encoder(Ver3.3). I get both 4-Nov-2020(JST).
I login AVideo (using IE11) and I login AVideo-Encoder form AVideo.
But Processing messages displayed. I could not login.

I used our customer's PC (IE11), I access AVideo demo site. I could login AVideo and AVideo-Enconder.

What do I check ?
![AVideo](https://user-images.githubusercontent.com/46562199/98365992-9d2af500-2076-11eb-88f4-db8681a4d711.jpg)

**Comment by DanielnetoDotCom** [comment]
Make sure you have the latest encoder.
