### ISSUE TITLE
Can we update smartly ?

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3972]
Every time I update , I feel regret .
I'm getting error and issues from google , witch does hurt the SEO . Now all the channel / Video / and tags on the videos are getting changed , because for some reason you decided to add the channel ID to the channel name ...

![image](https://user-images.githubusercontent.com/52116577/98432906-279d4400-20cb-11eb-95de-ca43f7551232.png)

This makes google ignore all the videos that had the old channel name , and all channel and videos who were on the search , like www.example.com/channel/TESTER removed . Even direct access via URL to the old link gives error on the platform , since the channel doesn't exist anymore . giving error like they don't exist ... All videos related to them same error . This is starting to be unprofessional . To fix a minor problem we break the entire SEO site ...

EDIT ; Same on demo site . 

![image](https://user-images.githubusercontent.com/52116577/98433206-7cda5500-20cd-11eb-848b-00050110ba82.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I am also not sure how is it changing. I also notice that and I want to fix it.

but first I need to identify how does this happens.

**Comment by DanielnetoDotCom** [comment]
Hi, I guess I found the problem
