### ISSUE TITLE
WARNING TO NOT UPDATE TO mariadb 10.2.35

### ISSUE THREAD

**Issue by Social-Loafer** [WWBN/AVideo#3973]
WARNING TO NOT UPDATE TO mariadb 10.2.35
I just spent most my day trouble shooting why my sites would not pull up.
There is something with the new revision of mariadb that completely messed up my sites.
Rolling back to 10.2.33 fixed everything but it is a real pain in the &%^ to do so.
I didnt know where to post this but i just wanted to forewarn anyone thats using avideo/youphptube, that if your site mysteriously stops working after updating your server this most likely is the cause.  

Thanks to all that support avideo!

**Comment by DanielnetoDotCom** [comment]
Any idea what was the warnings or errors?

**Comment by Social-Loafer** [comment]
[06-Nov-2020 20:18:44 America/Denver] AVideoLog::DEBUG: Error in readSql (mysqlnd): (1835) Malformed communication packet, SQL-CMD:SELECT * FROM configurations WHERE id = 1 LIMIT 1 SCRIPT_NAME: /YouPHPTube/view/index.php
../videos/avideo.log:            [function] => log_error
../videos/avideo.log:                    [0] => Error in readSql (no mysqlnd): (1835) Malformed communication packet, SQL-CMD:SELECT * FROM configurations WHERE id = 1 LIMIT 1
../videos/avideo.log:[06-Nov-2020 20:18:44 America/Denver] AVideoLog::DEBUG: Error in readSql (no mysqlnd): (1835) Malformed communication packet, SQL-CMD:SELECT * FROM configurations WHERE id = 1 LIMIT 1 SCRIPT_NAME: /YouPHPTube/view/index.php
../videos/avideo.log:[06-Nov-2020 20:18:44 America/Denver] PHP Fatal error:  Uncaught Error: Call to a member function close() on null in /var/www/html/YouPHPTube/objects/mysql_dal.php:212
../videos/avideo.log:            [function] => log_error
../videos/avideo.log:                    [0] => Error in readSql (mysqlnd): (1835) Malformed communication packet, SQL-CMD:SELECT * FROM configurations WHERE id = 1 LIMIT 1

**Comment by DanielnetoDotCom** [comment]
Looks like it may fix if you update your PHP

https://stackoverflow.com/a/64689988/2478180
