### ISSUE TITLE
natsort trying to sort videos that are numbered.

### ISSUE THREAD

**Issue by Social-Loafer** [WWBN/AVideo#3974]
Modifying this file to get a sort order to display videos by numerical episodes.
/var/www/html/YouPHPTube/view/channelBody.php
 $_POST['sort']['clean_title'] = "ASC";
This works for the most part but it sorts like this 1,10,11,12,13,14,15,16,17,18,19,2,20,21,22,23,24 and so on,
I need it to sort 1,2,3,4,5,6,7,8,9,10 etc.
I tried replacing 'sort' with 'natsort' and it didnt do anything at all, any ideas on how i can get this to work?

Much appreciation.

**Comment by qome** [comment]
You'll have to label the videos differently: 01, 02, 03, 04, etc.

**Comment by Social-Loafer** [comment]
Thats disappointing....
I have to many videos to relable.

**Comment by DanielnetoDotCom** [comment]
Why don't you use playlists for the episodes? Then you will be able to sort them as you want.

For example here https://demo.avideo.com/viewProgram/16/YPT+Tutorials/

![chrome-capture (1)](https://user-images.githubusercontent.com/18009293/98575743-53b9f000-2298-11eb-94f5-a8f6981eff53.gif)

you can drag and drop them, then play them here https://demo.avideo.com/program/16

Also you have the autosort option 
![image](https://user-images.githubusercontent.com/18009293/98575915-8d8af680-2298-11eb-913b-2fed508e44a1.png)

Also please read this https://github.com/WWBN/AVideo/wiki/Program-(Playlist)-to-series

**Comment by Social-Loafer** [comment]
Reason being is because I'm using the netflix skin and I keep my version at 351905a6c for various reasons...
Appreciate your reply.
