### ISSUE TITLE
Custom Jitsi Meet Connection Error

### ISSUE THREAD

**Issue by crishyj** [WWBN/AVideo#3975]
![2020-11-07_22-48-12](https://user-images.githubusercontent.com/45354657/98442926-683ca200-214b-11eb-974b-5f6c4f081ac7.png)
When I connect to custom Jitsi Meet, it shows the Authentication Failed Error.
I am running my own Jitsi Meeting Platform.
So I selected the Custom Jitsi on Plug in.
And added the domain name of my own Jitsi Platform.
My Jitsi platform already implemented the authentication function.
If you know about the issues, please help me.
Best regards.

**Comment by awistudio** [comment]
HI, 
I have such an error:
502 Bad Gateway
nginx/1.14.0 (Ubuntu)

maybe I should change something here?
my settings.

![2020-11-07_20-44-55](https://user-images.githubusercontent.com/60708776/98450125-44249500-213a-11eb-82ad-228651840d1a.jpg)

**Comment by crishyj** [comment]
I think you need to change the domain name in the Custom_Jitsi_domain field.

**Comment by tonuzo** [comment]
@crishyj https://github.com/WWBN/AVideo/issues/3975#issue-738244335 did you solve the problem? I have the same issue..

**Comment by DanielnetoDotCom** [comment]
This is based on Jitsi docker installation. 

if you use it may be easier to configure.
