### ISSUE TITLE
Chat doesn't display

### ISSUE THREAD

**Issue by qome** [WWBN/AVideo#3976]
**Describe the bug**
The chat doesn't appear anywhere on the live stream page, but does appear on the live stream control panel page.

**To Reproduce**
1. Go to https://video.site.me/plugin/Live/
2. The chat is present
3. Go to https://video.site.me/live/0/User
4. The chat is not present

**Expected behavior**
I would expect the chat to be present until it is fully removed from AVideo.

**Error Logs**
I don't see any errors for the Live or LiveChat plugin at this time. I also don't see any errors in the browser console.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86.0.4240.183

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 10
 - Browser: Stock Chrome
 - Version: 86.0.4240.185

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/98448267-a31de600-2109-11eb-8700-548ee240c565.png)

**Comment by qome** [comment]
Are you willing to provide it for free like the LiveChat plugin?
