### ISSUE TITLE
Playlist Translation Watsch Later an Favorite

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#3978]
Hello, is it possible to translate the names of the playlists Watsch Later and Favorite?
I have seen that the corresponding entries are already stored in the database. In theory, all database entries could be changed, but when a new user account is created, they will be named again.

**Comment by DanielnetoDotCom** [comment]
I guess it is possible.

For example, we have it here in br

https://github.com/WWBN/AVideo/blob/2cc8612149c2286394e2785edc5709932104894c/locale/br.php#L495

Make sure you add this to your translation file

$t['Watch Later'] = "....";
$t['Favorite'] = "...";

If you see it not translating somewhere after add in the file, please screenshot it for me.

**Comment by Donnerstein** [comment]
Yes, it works in the menus and the icons on the preview image, just not on the channel page and in the video management and when selecting on the playback page

You are welcome to add the translation to DE

$t['Watch Later'] = "Merkliste";
$t['Favorite'] = "Favoriten";

![image](https://user-images.githubusercontent.com/52116237/98659067-0c893900-2344-11eb-8169-5367e707fa26.png)


![image](https://user-images.githubusercontent.com/52116237/98657886-ab149a80-2342-11eb-986d-04f693b70b81.png)

![image](https://user-images.githubusercontent.com/52116237/98658284-2aa26980-2343-11eb-841e-2ade5b1140a2.png)

**Comment by tonuzo** [comment]
Hey,

I have the same problem. Webui-popover Favorite and Watch Later are untranslatable... Is it possible to fix?

**Comment by DanielnetoDotCom** [comment]
Yes, I will send an update soon
