### ISSUE TITLE
Liveservers and the Notification Bell

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3979]
On using live servers, the streams on the second live server do not show up on the bell.

in the initial server there is no bell notification and in the 2nd live server there is no bell notification. both say zero.

this is something to look into.

thank you.

**Comment by akhilleusuggo** [comment]
1- The stream must be public
![image](https://user-images.githubusercontent.com/52116577/98458300-c7280880-2197-11eb-9986-b7a3e013e5d9.png)


2- Setting on Live Plugin 
![image](https://user-images.githubusercontent.com/52116577/98458320-e757c780-2197-11eb-9b32-aebc91d03ef0.png)

**Comment by jengajenga** [comment]
> 1- The stream must be public
> ![image](https://user-images.githubusercontent.com/52116577/98458300-c7280880-2197-11eb-9986-b7a3e013e5d9.png)
> 
> 2- Setting on Live Plugin
> ![image](https://user-images.githubusercontent.com/52116577/98458320-e757c780-2197-11eb-9b32-aebc91d03ef0.png)

Thanks. I realised that an update fixed it. From 9.6 to 9.7. Thanks man.
