### ISSUE TITLE
No playback for live stream video's

### ISSUE THREAD

**Issue by Progressed36** [WWBN/AVideo#3981]
HI,

I bought the SendRecordedToEncoder plugin, but am unable to play the file that is my video's page. Also the file is not in the Encoder queue.

After activating the recorded video it just doesnt play. No Errors are displayed in console nor avideo.log.

**Comment by Progressed36** [comment]
PS the files are in /var/www/tmp with decent sizes...

**Comment by DanielnetoDotCom** [comment]
please check the log files

**Comment by Progressed36** [comment]
Hi Daniel,

I did. all debug notices are about other things and no errors.

**Comment by DanielnetoDotCom** [comment]
FYI, SendRecordedToEncoder has nothing to do with video play.

I am pretty sure if your videos are not playing is something else, NOT the SendRecordedToEncoder plugin.

I can only help you if I can see some logs.

**Comment by Progressed36** [comment]
I totally understand about the logs.. perhaps I can pay you to look through my testing environment?

Were currently testing this software if its what we are looking for and that's basically only streaming but we need the video's after :)

**Comment by DanielnetoDotCom** [comment]
Sure, I can look.

Please email me at developer@youphptube.com for more details
