### ISSUE TITLE
Change My Avideo from http://192.168.1.110/AVideo to http://mydomain/AVideo But...

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#3982]
I changed  My Avideo from http://192.168.1.110/AVideo to http://mydomain/AVideo.
I edited /var/www/html/Avideo/videos/configra
configuration.php
$global['webSiteRootURL'] = 'http://192.168.1.110/AVideo/';
-> $global['webSiteRootURL'] = 'http://Mydomain/AVideo/';
I ran "systemctl restart apache2"
I access http://Mydomain/AVideo/ but next displayed.
(firefox,chrome,IE11 same)
![av1](https://user-images.githubusercontent.com/46562199/98539596-f5a8ff00-22cf-11eb-9a34-22bb1ad366b4.png)
But I access  http://Mydomain/
no problem.
![av2](https://user-images.githubusercontent.com/46562199/98539732-2b4de800-22d0-11eb-9f9c-064818da2224.png)

Where do I  have to edit ?

or 

Do I have to clean installation ?

**Comment by DanielnetoDotCom** [comment]
This is old but may help you https://tutorials.avideo.com/video/18/fix-youphptube-url-after-move-server-location-and-ip

**Comment by hnagasawa** [comment]
Dear Daniel

Thank you for your e-mail.

I tried yesterday. But this problem did not fix.
I see /var/www/html/AVideo/videos/configuration.php
I found next.

"
$mysqlHost = 'localhost';
$mysqlUser = 'avideo';
$mysqlPass = 'your-password';
$mysqlDatabase = 'Avideo';

"
I think I must edit Mysql.Because when I install AVideo and AVideo-Encoder,
I must set your site URL.

What do you think ?

**Comment by etcy** [comment]
Hi hnagasawa

Not sure if this will help you. I actually moved my server yesterday to a different IP. 
Basically I tried to follow the tutorial video and recommended by Daniel.

For me, 
I could follow the video tutorial up to 2:55, for which my case, [configurations] was not available after logging into the encoder site. 

I have to follow apart of this thread:
https://github.com/WWBN/AVideo/issues/238

where I got into mysql and set isAdmin=1 to my admin logging into 127.0.0.1.

Afterwhich I was able to change the IP address through configurations as the original video depicted.

**Comment by hnagasawa** [comment]
I found the root of cause about this my #problem.
Today I reinstall AVideo.
I access http://mydomain/AVideo/
This is normal
I stop apache2.
I move from /var/www/html/AVideo/videos to /home1
I run 
#cd /var/www/html/AVideo
#ln -s /home1/vioes  /var/ww/html/AVideo/videos
(I referred to this URL
https://github.com/WWBN/AVideo/wiki/Can-I-store-my-videos-in-another-location)
I run "systemctl restart apache2"
I access htpp://mydoamin/AVideo,
Same error occured.

What file do we edit ?
