### ISSUE TITLE
1 stream 4 times

### ISSUE THREAD

**Issue by Joelp** [WWBN/AVideo#3984]
After last git pull (today), I see 1 stream 4 times:

![obrazek](https://user-images.githubusercontent.com/19979522/98633886-9cb68680-2322-11eb-8f17-6b6970e12f7a.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I am not sure how this happens.

can you reproduce it on GitHub?

**Comment by Joelp** [comment]
Sorry for late answer. I saw that, it's fixed in #3985. And it's fixed for me too.
