### ISSUE TITLE
[Fixed] For some reason I am seeing 4 live streams I have check nginx to all  OK but still same problem

### ISSUE THREAD

**Issue by antuk21** [WWBN/AVideo#3985]
For some reason I am seeing 4 live streams I have check nginx to all  OK but still same problem

![download (2)](https://user-images.githubusercontent.com/74247098/98676277-4ca3e800-2353-11eb-9980-1e19c36a13f8.png)

**Comment by DanielnetoDotCom** [comment]
I could not reproduce it on my side

can you reproduce it on demo site?

**Comment by antuk21** [comment]
Fixed it now  sweet

**Comment by antuk21** [comment]
Was fixed but came bk agen lol

**Comment by antuk21** [comment]
I turn off live plugin bk on worked for  a min said 1   now bk to 4 so must be the plugin maybe

**Comment by DanielnetoDotCom** [comment]
what is bk?

can you reproduce it on demo site?

**Comment by antuk21** [comment]
OK I fixed this problem now     for those who still have it in your nginx config  you may have 2  line off codes so same 

https://ibb.co/tJhshpt

**Comment by antuk21** [comment]
Only problem is now have trouble off stream showing up on vid player lol

**Comment by antuk21** [comment]
Soon I put uncheck live on on adaptive live works but theres 4 agen   so its the adaptive thing

**Comment by antuk21** [comment]
the 4  thumbs

**Comment by DanielnetoDotCom** [comment]
I guess I found the problem. please update your site

**Comment by antuk21** [comment]
OK thanks
