### ISSUE TITLE
users_login_history database

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#3987]
The table users_login_history becomes a real Mosnter over time. For most Internet connections, the IP address changes every 24 hours. I think it makes sense to remove these entries after 24 hours. There is no good reason to keep them forever.

![image](https://user-images.githubusercontent.com/52116237/98678386-c2618100-235e-11eb-8e34-9fd20a2ff0d6.png)

**Comment by akhilleusuggo** [comment]
then it will remove the login history .
should be an option to disable only the logs (like audit) , or keep them .

**Comment by DanielnetoDotCom** [comment]
how come do you have about a billion logins attempts?

maybe something is wrong on the recording saving or in your side.

any idea where most of those attempts come from?

**Comment by akhilleusuggo** [comment]
same here daniel .
All this attempts are coming mostly from encoder's IP

![image](https://user-images.githubusercontent.com/52116577/98684979-81be3380-236f-11eb-9ac0-93658baeedc1.png)


Some of them also mine . Basically when login timeout ( I guess )

**Comment by DanielnetoDotCom** [comment]
But if you are running the latest encoder and streamer it should not log encoder attempts 

https://github.com/WWBN/AVideo/blob/6ca23ab163833e3b6af384940aa7f297aea27b1c/plugin/LoginControl/LoginControl.php#L92

**Comment by Donnerstein** [comment]
Much comes from Encoder, it seems as if there is a separate registration for each resolution, as well as for each preview image.
But there is also a noticeable number of subnets, and regular
163.172.167.225
81.68.129.2
185.36.81.62.

These IPs are blocked again and again by fail2ban on ssh, presumably they are bots. I don't think it's a bug on the site. The Ban option in the user management is extremely slow, I think this option uses the users_login_history. If the table is that big, it's no wonder. Can I just empty the table, or will it cause problems?

**Comment by DanielnetoDotCom** [comment]
yes you can empty

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Successful attempt are reported as failed attempts .

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo this is expected if you are not using 2FA.

but the encoder should not register any login attempt

**Comment by akhilleusuggo** [comment]
> @akhilleusuggo this is expected if you are not using 2FA.

Well, it shouldn't because is not a failed attempt

**Comment by DanielnetoDotCom** [comment]
I know, this is just the message, it will be updated in the future
