### ISSUE TITLE
Chat2 3.6 not showing up in live stream

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#3989]
Chat 2 and 3.6 not showing up in live stream. And when I refresh my connection on my samsung S8 (Unable to connect. The site could be temporarily unavailable or too busy. Try again later.

**Comment by DanielnetoDotCom** [comment]
looks like a network problem

Share your URL so we can test.

**Comment by Lordblanca** [comment]
http://62.151.177.251/YouPHPTube/live/0/Lordblanca

**Comment by Lordblanca** [comment]
Still in testing phase... making sure Everything that I want to work works.
Before going live
http://62.151.177.251/YouPHPTube/live/0/Lordblanca

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/98810975-d65cbf80-23fe-11eb-9c6c-6b845b2a1cae.png)

but anyway the error described seems to be a network problem.
