### ISSUE TITLE
VideoResolutionSwitcher Plugin not working

### ISSUE THREAD

**Issue by foobarzap** [WWBN/AVideo#3991]
Plugin crashes when installed with aVideo v8.5 when listing available plugins:

`uncaught Error: Class 'PluginTags' not found in /var/www/AVideo/plugin/VideoResolutionSwitcher/VideoResolutionSwitcher.php(14) : eval()'d code(1) : eval()'d code:10
Stack trace:
#0 /var/www/AVideo/objects/plugin.php(198): VideoResolutionSwitcher->getTags()
#1 /var/www/AVideo/objects/pluginsAvailable.json.php(9): Plugin::getAvailablePlugins()
#2 {main}
  thrown in /var/www/AVideo/plugin/VideoResolutionSwitcher/VideoResolutionSwitcher.php(14) : eval()'d code(1) : eval()'d code on line 10`

**Comment by DanielnetoDotCom** [comment]
Please make sure you are running the latest avideo.

**Comment by foobarzap** [comment]
Thank for the instant response!

Just checked - we are running branch 8.6. Frankly, I am a bit hesitant of upgrading our production system. Is there any other chance to get it working (e.g. older an version of the plugin)?

**Comment by DanielnetoDotCom** [comment]
Sorry, I can only make sure it works if you run the latest.

**Comment by foobarzap** [comment]
Thank you - so I'll got for the update!
