### ISSUE TITLE
Listed Live

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#3994]
I set one channel to not show up in the list of channels live.

This is what I got.

![still_on_air](https://user-images.githubusercontent.com/65451390/98943717-f5dc1100-2500-11eb-8cef-e3b60cb8aaf6.PNG)

Fix?

Thanks

**Comment by DanielnetoDotCom** [comment]
This is an Admin message, only admins will see that.

regular users do not see it.

**Comment by jengajenga** [comment]
Ok. Thank you Daniel.
