### ISSUE TITLE
SMTP Sendmail Error Message ...

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#3995]
I have SMTP setp up on my domain registrar and I know that it works because I can send email on any client that set it up on.
I am trying to set up the SMTP feature so that users can register and confirm email addreses.

This is the error message I am getting:

```
Your message could not be sent!
Message could not be sent (Could not execute: /usr/sbin/sendmail -t -i )
```

**Enable SMTP** = check
**Enable SMTP** Auth = check
**SMTP Secure** = tls
**SMTP Port** = 587
**SMTP Host** = smtp.ionos.com
**SMTP Username** = my username
**SMTP Password** = my password

**Screenshots**
<img width="567" alt="email_issue1" src="https://user-images.githubusercontent.com/7376298/98983718-d2a46800-24e6-11eb-9fd4-a24956e41e02.png">
<img width="477" alt="email_error2" src="https://user-images.githubusercontent.com/7376298/98983736-d637ef00-24e6-11eb-87e1-0b88a9c1d8cb.png">

I have tried with Google Gmail and also Mailgun and none of the smtp settings from any host will work, its always the same error.

I wonder if, there is something that needs to be enabled on the server first ... if so, would you have any recommendations.

**Comment by bbyrdhouse** [comment]
Looking at this thread from StackOverflow a few people are saying that you need to comment out or delete the .IsSendMail 
Does that sound accurate?

https://stackoverflow.com/questions/4393724/phpmailer-reports-could-not-execute-usr-sbin-sendmail

**Comment by bbyrdhouse** [comment]
Also, some are saying that if safemode is on then PHPMail will fail, would that be the scenario in my case?

**Comment by DanielnetoDotCom** [comment]
Please make sure you saved the configurations before test it.

Atenciosamente

Daniel Neto

Master in Systems and Computing (2009)
Specialist in WEB Systems and Applications (2005)
http://buscatextual.cnpq.br/buscatextual/visualizacv.do?id=K4252385T9

PHP ZEND 4/5 Certified Engineer
PHP Zend Certification - Authentication
http://zend.com/zce.php?c=ZEND001318&r=209210010

Programming in HTML5 with JavaScript and CSS3 Specialist (MCP 70-480)
https://mcp.microsoft.com/authenticate/ValidateMCP.aspx
Transcript ID (1040640) and the Access Code (danielNeto)

**Comment by bbyrdhouse** [comment]
That was it ... thnx
