### ISSUE TITLE
Custom Template(s) for Verification & Notification emails

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#3996]
I've read a couple of previous posts (issues). where folks where asking about being able to customize email templates, but those threads have gone stale.

So my question is, can I use custom html to create my own email templates for email verification for new users and also for notifications for when a content creator uploads a video and an email gets sent to subscribers.

This is what the current email verification looks like ... just plain text
<img width="677" alt="email-1" src="https://user-images.githubusercontent.com/7376298/99005589-b31d3780-2506-11eb-9846-2290976982cb.png">

This is what the email verification looks like from another site I admin 
<img width="806" alt="email2" src="https://user-images.githubusercontent.com/7376298/99005680-d2b46000-2506-11eb-9844-a38da1fcf675.png">

So, is it possible? If so, please point me to the correct place.

**Comment by DanielnetoDotCom** [comment]
Hi

I just sent a new update that may give you a better look on emails.
