### ISSUE TITLE
YPTStorage ... Request More Information About It

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#3997]
I'd like to know a little more about the YPTStorage plugin before purchasing it.

What is it?
What is its purpose?
How would it help my server/setup (live streaming + vod)
Does it work with or conflict with the HLS plugin?

**Comment by akhilleusuggo** [comment]
> What is it?

https://github.com/WWBN/AVideo-Storage#avideo-storage

> What is its purpose?

https://github.com/WWBN/AVideo-Storage#benefits

> How would it help my server/setup (live streaming + vod)

If you read the description up , for now it doesn't help , unless you decide to install the livestream there . Does store the VOD .

> Does it work with or conflict with the HLS plugin?

Does store HLS videos without problem .

**Comment by bbyrdhouse** [comment]
Thnx ... I can now see the benefit to this over Backblaze
