### ISSUE TITLE
Channel missing video's page

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#3998]
On the user's channel , at the bottom the feature to browse video's pages is missing .

![image](https://user-images.githubusercontent.com/52116577/99025354-45f2bc00-2571-11eb-9a8a-b5e662024047.png)

Before it was something like this : 

![image](https://user-images.githubusercontent.com/52116577/99025375-560a9b80-2571-11eb-9a8f-a6c462789b85.png)

**Comment by tonuzo** [comment]
I confirm bug

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that, please check this update
