### ISSUE TITLE
Live Stream Horizontal Scaling

### ISSUE THREAD

**Issue by qome** [WWBN/AVideo#3999]
**Is your feature request related to a problem? Please describe.**
The number of live stream viewers a site can support is limited by the server's bandwidth and there is currently no way to scale horizontally (as far as I can tell.)

**Describe the solution you'd like**
I would like to be able to add NGINX `/live` nodes just like we can add encoder and storage nodes.

**Describe alternatives you've considered**
Simply buying bigger and bigger pipes on the server, which becomes cost prohibitive.

**Additional context**
I was considering something like this:
![image](https://user-images.githubusercontent.com/58382620/99111246-62164d80-25b1-11eb-94c8-aadce8f3bf40.png)

1. First the viewer connects to AVideo which has the video.js player
2. Second the viewer's video.js player requests the playlist from HTTP `/live` (running NGINX)
3. The NGINX responds with an HTTP 302 redirect to the edge NGINX server in a round-robin way.

Here is an example NGINX configuration to round-robin HTTP 302 redirects to different edge servers:
```
split_clients "${remote_addr}${http_user_agent}${date_gmt}" $variant {
  50% edge1;
  50% edge2;
}

server {
  # Listen on port 80
  listen 80;
  server_name localhost 127.0.0.1;

  # Declare domains based on keys
  if ($variant = edge1) {
    set $redirect_url https://edge1.avideo.com;
  }
  if ($variant = edge2) {
    set $redirect_url https://edge2.avideo.com;
  }

  # Redirect to our domain
  location /live {
    return 302 $redirect_url/$request_uri;
  }
}
```

I do not know how this impacts recording live streams as it seems the files *must* be stored on the same server as AVideo.

**Comment by qome** [comment]
load balancer nginx.conf add to the http section and comment out `alias /HLS/live;`:
```
    http {
            include       mime.types;
            default_type  application/octet-stream;
# Add this section
            split_clients "${remote_addr}${http_user_agent}${date_gmt}" $variant {
              50% edge1;
              50% edge2;
            }

            server {
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
# Add this section
                    if ($variant = edge1) {
                      set $redirect_url http://edge1.avideo.com:8080;
                    }
# Add this section
                    if ($variant = edge2) {
                      set $redirect_url http://edge2.avideo.com:8080;
                    }

                    # Redirect to our domain
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
# Comment out this line
#                      alias /HLS/live;
# Add this section
                      return 302 $redirect_url$request_uri;
                    }
```
Substitute in your own edge server protocol (HTTP/HTTPS), hostname, and port for each edge server. This configuration uses two.

edge server nginx.conf comment out:
```
on_publish http://avideo.com/plugin/Live/on_publish.php;
on_play http://avideo.com/plugin/Live/on_play.php;
on_record_done http://avideo.com/plugin/Live/on_record_done.php;
```
otherwise it is a standard NGINX stream server setup.

@DanielnetoDotCom , @akhilleusuggo what are your thoughts about adding this to the wiki? I can furnish full configuration files if what I've posted doesn't make sense.

**Comment by syldri** [comment]
Hello, I really can't wait to have their answer
