### ISSUE TITLE
Updating Process ???

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4001]
I tried watching the video here to learn how to update but the video will not load/play.
[https://tutorials.avideo.com/video/24/how-to-update-your-youphptube-version](https://tutorials.avideo.com/video/24/how-to-update-your-youphptube-version)

I've searched the Git repository for:

- How to update
- Updating
- Update instructions

but nothing that comes up is relative ... I know there is bound to be some instructions somewhere but I'll be danged if I can find them.

Please point me to the instructions to update from one version to the next.

Thnx

**Comment by syldri** [comment]
hello 

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by bbyrdhouse** [comment]
tnx ... why it didn't come up in a search, I can't answer.

**Comment by bbyrdhouse** [comment]
So this is not recommended?
<img width="362" alt="Screen Shot 2020-11-14 at 10 31 49 AM" src="https://user-images.githubusercontent.com/7376298/99152005-bdedde80-2664-11eb-9bc9-a9708673b415.png">

**Comment by DanielnetoDotCom** [comment]
Hi, I just made a 1 min video showing how I Update the https://videos.forjesus.tv/ site

https://tutorials.avideo.com/video/103/making-a-git-pull-and-updating-the-streamer
