### ISSUE TITLE
Clicking Record disconnects user's stream

### ISSUE THREAD

**Issue by qome** [WWBN/AVideo#4002]
**Describe the bug**

**To Reproduce**
1. Start streaming
2. Click on Record
3. Stream is disconnected and reconnects after a few seconds

**Expected behavior**
I expected NGINX to begin recording the stream to disk.

**Error Logs**
None that I can see.

I do not have any paid plugins at this time. Automatic recording works fine.

**Comment by bbyrdhouse** [comment]
Hi,

Same thing happened to me in the exact same order.
I came here looking for possible solutions and found your post, so I am confirming your issue.

**Comment by DanielnetoDotCom** [comment]
Hi

the controls are not working yet.

But it will work in the future
