### ISSUE TITLE
How disabe Infinite Scroll in Categories & All video_gifs are playing without hover

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#4005]
How can you disable Infinite Scroll from categories (in menu) back to pages ?

The system slow down when you've lots of video's (350+) in the categories. 
Most users are interested in the last videos (date added) and with infinite scroll lots of data is useless and billing on 4/5G network of the users,

All video_gifs are loaded & playing without hovering and this slowing down the website too.

**Comment by DanielnetoDotCom** [comment]
We do not have the disable option, but are you talking about the main page of the gallery layout?

**Comment by TLCReuver** [comment]
No, the main page have thank god seperate pages.

The category layout had before also seperate pages but since one of the last updates it has Infinite Scroll and i become lots of complains about it (slow & unnecessary data (>=350 videos)).

**Comment by TLCReuver** [comment]
I restored backup from 2020-11-12 and stay on that version because of to many bugs in Categories.

- Infinite Scroll does  only 1 time scrolling so not all videos in Categorie are showing (missing videos in Category).
- All video_gifs are loaded & playing without hovering
- No settings available for rowcount before infinite scroll (t0o many videos in 1 page)

**Comment by DanielnetoDotCom** [comment]
Try to change the CategoriesRowCount

![image](https://user-images.githubusercontent.com/18009293/99808895-4ca8a280-2b20-11eb-98ff-f68fcfd9abc2.png)

**Comment by TLCReuver** [comment]
Descreasing CategoriesRowCount is better now but still Catogeries does NOT show all videos.

 Infinite Scroll works only 1 time.

Category https://archief.beesel-reuver.nl/cat/reuver-diverse- have 372 videos but Avideo is only showing 24 Videos !

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by TLCReuver** [comment]
It's working perfect now... Many thanks.
