### ISSUE TITLE
Is it possible to remove the options for Import video and Bulk Encode?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4006]
Hi,
I'd like to remove the option for Import Video and Bulk Encode from the Encoder page. Is there a setting for this, if so, where is it?

<img width="551" alt="a_bulk" src="https://user-images.githubusercontent.com/7376298/99187863-a410d200-271e-11eb-8bfb-29ea7d56f0a9.png">

**Comment by DanielnetoDotCom** [comment]
Hi, you cannot remove the **Import video** tab, but you can remove the **Bulk Encode**

edit your configuration.php and add this

`$global['disableBulkEncode'] = 1;`

**Comment by bbyrdhouse** [comment]
ugh ... I won't be able to make any edits until I get permission granted
<img width="973" alt="Screen Shot 2020-11-16 at 1 23 21 PM" src="https://user-images.githubusercontent.com/7376298/99298167-e9143180-280e-11eb-8c4f-204b2c3225cd.png">

**Comment by DanielnetoDotCom** [comment]
Try now, I just changed the permissions with the command line

**Comment by qome** [comment]
You can "disable" the import functionality by just not having youtube-dl installed, correct?

**Comment by DanielnetoDotCom** [comment]
you will still be able to see the option, but it will not work.
