### ISSUE TITLE
Can't login via facebook to marketplace 

### ISSUE THREAD

**Issue by forsmartworld** [WWBN/AVideo#4009]
Hello i can't login via Facebook on marketplace to have access to purchased plugins. 
Facebook user : facebook.com/viktor.seby
mail adress: venom2seby@yahoo.com

**Comment by akhilleusuggo** [comment]
> I can see now, I am blocked from Facebook again. (third time)
> 
> Can you please create an account on the https://tutorials.avideo.com/ and use it to login?
> 
> than please send me you facebook email and your new account # and I will transfer your purchases to it.

By @DanielnetoDotCom https://github.com/WWBN/AVideo/issues/3717

**Comment by forsmartworld** [comment]
Create new user and now is ok. Thanks
