### ISSUE TITLE
youtube-dl channel import

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4010]
Trying to import url from YT channel only works for a single url. When trying to import a channel I choose a range, than I get an OK pop up twice, the second pop up come 2-3 sec after the first indicating the urls have been imported successfully, however there are no files in the queue and no error message I currently see indicating an error. I know about the youtube-dl issue but figured if its back to work with single urls why wouldn't it work with the channel import.

**Comment by DanielnetoDotCom** [comment]
It is not working anymore, I guess it is due to the youtube-dl takedown  https://github.com/WWBN/AVideo/issues/3900
