### ISSUE TITLE
Trying To Update To Chat2 3.7 .... 

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4012]
I see that there is an update to Chat2 from 3.6 to 3.7. Whenever I select the yellow update button it takes me to the marketplace.
When I re-download the chat2 plugin and upload it via the plugin page, it still says I have version 3.6.

What am I doing wrong?

Clicking on this ... 
<img width="926" alt="Screen Shot 2020-11-15 at 8 29 40 PM" src="https://user-images.githubusercontent.com/7376298/99206728-c851ca80-2781-11eb-9210-de76f49cb1d5.png">

Takes me here ... 
<img width="1417" alt="Screen Shot 2020-11-15 at 8 30 24 PM" src="https://user-images.githubusercontent.com/7376298/99206766-d9024080-2781-11eb-9f09-279497428fdc.png">

**Comment by DanielnetoDotCom** [comment]
Hi, it is probably a folder permission issue.

try to manually delete the Chat2 folder and then upload the plugin again.

**Comment by bbyrdhouse** [comment]
will do and then report back

**Comment by bbyrdhouse** [comment]
I can't delete anything because I don't have permission ... (this is what I emailed you about over the weekend)
<img width="845" alt="Screen Shot 2020-11-16 at 1 17 42 PM" src="https://user-images.githubusercontent.com/7376298/99297671-2fb55c00-280e-11eb-8231-cb38eb04b0bd.png">

**Comment by DanielnetoDotCom** [comment]
Hi

this is because this folder was created using the sudo command with the command line.

You may want to connect using the SSH and change the owner of the folders with ` sudo chown -R ubuntu /var/www/html/AVideo/plugin` than you will probably be able to delete them with filezilla or others

**Comment by DanielnetoDotCom** [comment]
BTW, I just did that for you, please try again

**Comment by bbyrdhouse** [comment]
fixed the chmod error ... but I need to have "permission" for the entire site.

I avoid the command line as much as possible, I am much more at home with Espresso than Terminal.
Can you please give me the command that I can run in terminal using ssh that will give me permission to edit files via Transmit/Espresso.

**Comment by DanielnetoDotCom** [comment]
I sent you an email with the SSH credentials.

your server was installed and compiled using the root user, that is why you are having permissions conflicts.

you can give permissions manually or you can google how to create a user with root permissions for SSH, I know it is possible but I am not sure how.
