### ISSUE TITLE
Video does not play

### ISSUE THREAD

**Issue by Powerstar7** [WWBN/AVideo#4014]
I have this question on the site, which at the beginning opened the videos normally, but now the screen is blank.

Marcos
![atar](https://user-images.githubusercontent.com/55261051/99258366-bec77180-2818-11eb-99de-b339e0a5901d.png)
![star1](https://user-images.githubusercontent.com/55261051/99258375-bff89e80-2818-11eb-86f5-a044594c47e5.png)

**Comment by DanielnetoDotCom** [comment]
First looks like you have some plugins misconfigured. for example you looks like have a deprecated FBTube plugin enabled.

please make sure you disable it.

to resolve that please check your log file https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
