### ISSUE TITLE
Categories Won't Accept either & or &amp; 

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4015]
**Describe the bug**
When creating categories you are not able to use either the & or the &amp;

**To Reproduce**
1. Go to Categories and create a new category
2. Add a title that includes & (Cats & Dogs)
3. Save
4. Notice that after saving the & is removed and replaced with a blank space

**Expected behavior**
I would expect the & to display as intended.

**Comment by akhilleusuggo** [comment]
I believe it's a cache problem . Try cleaning the cache  , and reload

**Comment by bbyrdhouse** [comment]
No ... that doesn't do anything ... I am pretty sure that it is an oversight. I've tried on a couple of browsers and cleared the cache of the script and of the browsers and its the same.

**Comment by DanielnetoDotCom** [comment]
For security reasons, we remove some characters, but we could enable the & to appear with this new update

**Comment by bbyrdhouse** [comment]
Excellent! Thank you
