### ISSUE TITLE
iPhone & Android Browsers Video & Live Chat

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4016]
I happen to have quite a few people who view my live streams on their smartphone, so the user experience on mobile browsers is of interest to me.
Currently when someone tunes into a live stream using the browser on their phone, they can see the livestream but if they want to participate in the live chat they have to scroll the page to the comments all the way at the bottom and then scroll back up to see the video. This makes for a tedious user experience constantly scrolling back and forth from video to chat and back again.

My question .... Is there something I can do on my end to make the chat comment box (the part where the user types his comment) fixed to the bottom of the screen ... is there a setting in a plugin?
I suppose I could try to sort out some css wizardry to try to force it, but a native solution would be better.

It is the same user experience across mobile devices (Android and iPhone) with either Chrome or Safari browsers.

Thanx

**Comment by DanielnetoDotCom** [comment]
can you please provide some screenshots so I can understand the idea better?

**Comment by bbyrdhouse** [comment]
Here is a brief video showing what I mean
https://thepatriot.network/video/42/livestream-chatbar

**Comment by DanielnetoDotCom** [comment]
I see, your video is very helpful to understand.

I am not sure what I can do, but I agree with you, the input box on the bottom would be nice.

I will try something and if works I will release an update in the future.

**Comment by DanielnetoDotCom** [comment]
Chat2 version 3.8 should have an update for that

**Comment by bbyrdhouse** [comment]
Nice!
