### ISSUE TITLE
AVideo App from the App Store Will Not Show Live Streams

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4017]
In an effort to provide my viewers with the option of having a native app that can be used to participate in website and live streams, I downloaded the AVideo app from the App Store.
It was easy enough to change the site to my site and log into my account. 
However, I could not find the livestream that was indeed running. When I clicked on the "LiveStream" button it simply said "No live streams at the moment" but there was definitely a live stream going because I was doing it on my desktop browser.

I assume that the app is intended to play a live stream if it exists, so is there a setting that I need to select on the admin or plugins section?

Thnx

**Comment by DanielnetoDotCom** [comment]
Hi

It supposes to have a camera on the top left that allows you to use the Meet to make a livestream

**Comment by DanielnetoDotCom** [comment]
Please check here I updated with some images 
https://github.com/WWBN/AVideo/wiki/How-to-make-a-live-stream#from-mobile

**Comment by bbyrdhouse** [comment]
I thinnk you may have misunderstood my question:

1. I start a livestream from my desktop 
2. A user opens up the AVideo app to participate in that live stream
3. They are presented with a message saying that there is no live streams

Note: Yes, the user has already changed the app's website to match my url.

**Comment by DanielnetoDotCom** [comment]
Did you make your livestream listed?

![image](https://user-images.githubusercontent.com/18009293/99405981-21c61080-28cc-11eb-81ae-1ad8f4374dd6.png)

**Comment by bbyrdhouse** [comment]
No, because I was doing testing, I had it set to private. I assumed that because I was logged in as the admin who was doing the live-streaming that I would be able to see it.

**Comment by bbyrdhouse** [comment]
Here is a brief video showing it
https://thepatriot.network/v/43

**Comment by DanielnetoDotCom** [comment]
Question if you connect whit this app on the demo site does the same happens?
