### ISSUE TITLE
disable encoding at 240p and 360p

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#4018]
Tell me how to prevent video from being encoded at 240p and 360p? (see screenshot)
<a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/11/17/d9003302d4cf70705a14bd039e489874-full.jpg" border="0"/></a>

**Comment by DanielnetoDotCom** [comment]
It is not that easy, it requires code change or rolls back to the old encoder style

**Comment by palich91** [comment]
then I think to leave it as it is
