### ISSUE TITLE
PayPerView for a series or playlist

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#4019]
I 'd like to have an option to rent a series with PayPerView. 

Is it possible to implement? 

At the moment there is possibility to set a series to PayPerView, but you can't include the videos in that particular PayPerView series. I mean if you pay for the series, it doesn't unlock the videos inside the playlist.

**Comment by DanielnetoDotCom** [comment]
Hi

the latest payperview allows you to use user groups instead of select a specific video.

if all the videos in the series are on the same usergroup it should work fine
