### ISSUE TITLE
Help where to add the video format

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#4020]
Faced such a problem (see screenshot).
Where do I need to add the .mkv format?
<a href="https://savepice.ru/full/2020/11/18/8bb75bef4b4752523b1c6bcf6cc56e49-full.jpg.html" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/11/18/8bb75bef4b4752523b1c6bcf6cc56e49-full.jpg" border="0"/></a>

**Comment by palich91** [comment]
Who can tell?
How can I allow uploading .mkv files

**Comment by DanielnetoDotCom** [comment]
This is hardcoded, but even if you allow it, this will be useless. mkv does not play natively on HTML5 players

**Comment by palich91** [comment]
.avi format is also not playable on HTML5? 

### File extension error [Video.avi], we allow only (webm,mp4,mp3,ogg,pdf,jpg,jpeg,gif,png,webp,zip)

**Comment by akhilleusuggo** [comment]
Is not . Don't try other extensions that are not webm or mp4 . Even if some are supported , very browsers will support them .
