### ISSUE TITLE
ERROR: chown www-data:www-data /var/www/html/AVideo/plugin && chmod 755 /var/www/html/AVideo/plugin

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4021]
I log in to upload the Chat2 3.7 update and I am presented with this error:
<img width="611" alt="Screen Shot 2020-11-17 at 8 51 55 AM" src="https://user-images.githubusercontent.com/7376298/99405463-69d83980-28b2-11eb-8567-c941da33bfd3.png">

I suspect it has something to do with this issue:
https://github.com/WWBN/AVideo/issues/4012

**Comment by bbyrdhouse** [comment]
NOTE: I fixed it, I was just passing along the information

**Comment by DanielnetoDotCom** [comment]
yes, now you want apache to upload to this folder.

this is something you need to deal, who is the folder owner, Apache or your SSH user
