### ISSUE TITLE
Set a video to Private Mode where only users with a link can view

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4022]
Currently you can make a video set to private and select user groups who can view that video.
I would like to see an option to set a video as private, meaning that it does not show up on the front page, the uploader's channel, or appear in the search, but anybody who has the link will be able to view it.

USE CASE
Suppose that you are helping a customer troubleshoot an issue with something and you make them a video tutorial. Maybe you make and upload the video but its not appropriate to let everyone see it and the person the video is intended for may or may not be a user of the site and you certainly do not know if they are part of a user group ... a private link would be very helpful in such cases.

I am sure there are a number of other reasons for private links ... 

Please consider.
Thanks

**Comment by DanielnetoDotCom** [comment]
Did you try to use unlisted videos (gray eye)?

![image](https://user-images.githubusercontent.com/18009293/99549271-3c65bb80-2998-11eb-854f-277891ab786b.png)

or maybe protect them with passwords?

![image](https://user-images.githubusercontent.com/18009293/99549342-4daec800-2998-11eb-8023-0e95f2e33262.png)

**Comment by akhilleusuggo** [comment]
Private video ( does disable the video completally ) 

What you need is to set-up "user groups" . Only those who belong to a user group will be able to access the video .
Just a reminder , there's no ''real'' private video . People can still pull the mp4 url ( root ) , and playback the video . HLS is the way.

**Comment by bbyrdhouse** [comment]
@akhilleusuggo - I am not sure yo understand the issue .... 

1. I create a video
2. I do not want that video to show up anywhere on the front page, on my channel page or in the search
3. I want to take the link to that video and share it with people in my Discord group so that they can go watch it

I do not care about people downloading ro finding the video root, I just don't want the video available to the general public and only to those people, groups its that I say "hey, check out this video"

It does not make sense to create a user group for this purpose because that defeats the point of sharing with people a url that all they have to do is click on. If I have never met them then how can I add them to a user group? Makes no sense.

Password protecting a video is not what I am looking for. I am looking for a feature similar to Youtube where I can 
1. create a video
2. set it to private
3. It will not appear the home page
4. it will not appear on my channel page and
5. it will not appear in search results
6. but anybody who has the url can watch the video

**Comment by akhilleusuggo** [comment]
Ok , let me explain 👍 

1- Private video will COMPLETALLY disable the video page . ( not what you want )
2- Unlisted , is like the unlisted option ( on youtube ) , anyone with the link can watch it .
2.1- How to protect it then ? Set a password as @DanielnetoDotCom stated above .
3- How do you hide it from front pages and all pages ? On plugin theme ( gallery in my case , yours probably too ) .
This will hide all videos in UserGroup / Private / Unlisted . Also will not be generated on the sitemap if you indicate it !

_**Gallery Plugin :**_ 
![image](https://user-images.githubusercontent.com/52116577/102792046-964f0c00-43b0-11eb-8511-ff902d32314c.png)


_**CustomizeAdvanced Plugin :**_ 
![image](https://user-images.githubusercontent.com/52116577/102792247-eb8b1d80-43b0-11eb-865c-8c3435773316.png)

4- UserGroup . This option would be equal to Private on YouTube . Any user that belongs to that private group can watch those videos . If the user is not logged in with the account belonging to that UserGroup can NOT watch the video , even if it has a link.

Hope you have everything clear now !

**Comment by DanielnetoDotCom** [comment]
@bbyrdhouse you should try the unlisted option, make sure you have the grey eye icon

![image](https://user-images.githubusercontent.com/18009293/102878512-2760ca00-4427-11eb-8d8c-316325a714cd.png)
