### ISSUE TITLE
Live Chat2 (vs 3.7) Links are not active Plus they need word-wrap: break-word;

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4024]
When posting a link in the Live Chat, the link is not active. (See picture)
There should be an option to turn this on or off ... or better yet, to turn this feature on for user groups. 
This way if I created a user group who I wanted to serve as moderators of live chat they would have the ability to boot users and post links.

Youtube LiveChat allows "wrenches" (moderators) to be able to post url's

Also, I noticed that when I post a url, the text goes off the screen ... I assume that a css rule will do the trick ...

```
.message{
overflow-wrap: break-word;
  word-wrap: break-word;
}
```
<img width="442" alt="Screen Shot 2020-11-17 at 3 42 29 PM" src="https://user-images.githubusercontent.com/7376298/99454557-34e8d880-28ec-11eb-9588-00a364ba1389.png">

**Comment by DanielnetoDotCom** [comment]
Chat2 v3.9 will cover this
