### ISSUE TITLE
Notices are being Sent To Subscribers Of Livestreams That Are Set To Private ... 

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4025]
I have discovered a bug that IMO, needs to be addressed soon.

As a matter of testing features of the script in general and particularly the Live Streaming and Live Chat I will do a live stream that is set to private. I have discovered that even if the live stream is set to private, people that have subscribed to the channel with notifications will receive an email telling them that I am live. Even though it is a private stream they still get a link to the stream and and watch it. 

This is something that should be addressed as soon as able.

Note here the email notice:
<img width="712" alt="Screen Shot 2020-11-17 at 4 11 37 PM" src="https://user-images.githubusercontent.com/7376298/99456868-ac6c3700-28ef-11eb-8953-f4cc896bba8f.png">
<img width="536" alt="Screen Shot 2020-11-17 at 4 11 49 PM" src="https://user-images.githubusercontent.com/7376298/99456877-af672780-28ef-11eb-8b5b-cc1a772bf2a8.png">

**To Reproduce**
1. In another account, subscribe to an account that can do livestreaming
2. Go back to your livestream account and begin a private livestream
3. Go anc check your email for a notice alerting you that the livestreaming account has gone live
4. Click on the link in the email and be taken to the livestream

**Expected behavior**
Nobody should get a notice of a private livestream

**Error Logs**
N/A

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: macOS v. 10.15.7
 - Browser: Safari Version 14.0.1
 - AVideo Version 9.7

**Comment by DanielnetoDotCom** [comment]
Hi

I am not sure what is the right behavior 

Did you made the live unlisted or you select user groups for it?

also, we may want to notify users about your private stream so they can $ubscribe/(pay) to watch your live.

**Comment by bbyrdhouse** [comment]
The livestream was set to unlisted, in Youtube when you set it to unlisted nobody gets an alert that you are doing a live stream. This is what you want for any number of reasons ... one might be that I might be doing a test of a new feature and sitting there with no shirt on having no idea that people got a notice and are sitting there watching me.

If a live stream is set to "Not listed" then nobody should be notified. 

OR another option would be, allow for a 3rd setting, that would allow for "practice live streaming" or "developer live streaming" that would allow an admin or site admin to be able to test new features or such without everyone getting a notice.

In my Specific Example: I do news broadcasts every day via a live stream. It is not unusual for me to do breaking news, also as a live stream. BUT I am also the site admin, who will do alot of testing for a lot of things and I might necessarily need to do a livestream to test something out. In the current scenario, all of my subscribers get an email saying "Hey Gary is dooing a live broadcast" they assume I have breaking news so they tune in, only to find me drinking a RedBull and eating Sugar babies on screen running tests and I've no idea they are watching.

**Comment by DanielnetoDotCom** [comment]
Thanks, you are correct. 

I just submit the Notifications plugin version 2.1 that may follow these instructions. and not notify unlisted lives and videos.
