### ISSUE TITLE
/var/www/html/AVideo/videos in another location But...

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#4026]
I install AVideo under Ubuntu18.04.
I access http://mydoamin/AVideo.
It fine.
I stop apache2"systemctl stop apache2"
I move from /var/www/html/AVideo/videos to /home1
I run
#cd /var/www/html/AVideo
#ln -s /home1/vidoes /var/ww/html/AVideo/videos
(I referred to this URL
https://github.com/WWBN/AVideo/wiki/Can-I-store-my-videos-in-another-location)
I run "systemctl restart apache2"
I access http://mydaomain/AVideo. But Next result.
![faildisplay](https://user-images.githubusercontent.com/46562199/99469768-cefd5f00-2986-11eb-90ee-b893f19aaf49.png)
Firefox and Chrome and new edge IE11 are same.

Is this bug ?

**Comment by DanielnetoDotCom** [comment]
In your configuration.php where you see this ...


```
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], >
    // get the subdirectory, if exists
    $file = str_replace("\\", "/", __FILE__);
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), $file);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'https://yourdomain.com/';
}
```

replace with this 

```
$global['webSiteRootURL'] = 'https://yourdomain.com/';
```

then your configuration will not try to dynamically create the URL
