### ISSUE TITLE
Error loading video

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#4027]
Hello!
Need help!
When I download a video in .mkv format, it gives me an error:

### File extension error [Maks Korzh - Maloletka.mkv], we allow only (webm,mp4,mp3,ogg,pdf,jpg,jpeg,gif,png,webp,zip)

<a href="https://savepice.ru/full/2020/11/18/8bb75bef4b4752523b1c6bcf6cc56e49-full.jpg.html" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/11/18/8bb75bef4b4752523b1c6bcf6cc56e49-full.jpg" border="0"/></a>

What do I need to do so that there are no mistakes?

**Comment by DanielnetoDotCom** [comment]
duplicated https://github.com/WWBN/AVideo/issues/4020
