### ISSUE TITLE
Chat2 position and users login question

### ISSUE THREAD

**Issue by br0kenlink** [WWBN/AVideo#4029]
Hi,
I just bought Chat2 plugin but it's not really exactly the way I wish it to end up.
1. Any chance I can position it on the side of the video stream, not on it or below it?
 I need viewers to be able to watch and chat without scrolling up/down.
 2. No login chat, just type in your nick and click ok for chatting.
 Our viewers don't want to regsiter etc, just to tell live DJ how great music goes on.

Otherwise I would most likely ask for a refund, I already run video stream and KiwiIRC webchat below,
so paying for your plugin makes no sense for me..
Thanks,
Tom

**Comment by DanielnetoDotCom** [comment]
Hi, sorry I cannot refund digital contents. you can test/check all the plugins before purchasing them on the demo site.

> Any chance I can position it on the side of the video stream, not on it or below it?
> I need viewers to be able to watch and chat without scrolling up/down.

try to switch the static layout option 
![image](https://user-images.githubusercontent.com/18009293/99572416-67a9d400-29b3-11eb-808a-66cece6fe81d.png)


> No login chat, just type in your nick and click ok for chatting.
> Our viewers don't want to regsiter etc, just to tell live DJ how great music goes on.

Signup and login is required

**Comment by br0kenlink** [comment]
Yeah, should have checked it before buying indeed. Well, won't be using it for sure, so enjoy my money.
Actually while creating issue, came up with an idea how to move my own webchat to be next to live video iframe on my website.
Expensive thought, but here we are.

**Comment by DanielnetoDotCom** [comment]
You can try to use javascript to move things (onload)

**Comment by br0kenlink** [comment]
Position won't help, if users have to login anyway, it's just to many steps and many p[eople dislikes it.
Thanks, maybe one day plugin will be useful for something anyway.
