### ISSUE TITLE
max online users

### ISSUE THREAD

**Issue by ashrafpro** [WWBN/AVideo#4030]
Hi,
I have a dedicated server
Intel Xeon E5-1650V3, 256 GB RAM, NIC 1 Gbit - Intel I210

the server hardly handle few hundreds online visitors, after this everything hangs.
What setting should I have to set on the server to handle this number?

**Comment by DanielnetoDotCom** [comment]
This is a really good server, but are you sure it is dedicated or you have a VM or docker in it sharing resources with other systems?

you can try to inspect the log files and see what is the bottle neck.
