### ISSUE TITLE
Uploading Video - Way too slow!

### ISSUE THREAD

**Issue by Khaled4** [WWBN/AVideo#4031]
Greetings! I am new to Avideo so veterans' help would be highly appreciated. Is there a way to speed up the video upload process? I uploaded a 45 second very short video but it is still moving from one queue to another since 22 hours and has now reached queue position 37 and on the sharing queue it is on Priority 5 (whatever this means!).
This cannot be the practical way of doing this task.
Any suggestions?
God Bless You.

**Comment by JoshWho** [comment]
You must be using the external encoder. You can install your own encoder and not have to wait. Look up the Avideo Encoder here https://github.com/WWBN/AVideo-Encoder

The one that comes by default is a public one that people all over the world so it will get very full at times.

**Comment by Khaled4** [comment]
@JoshWho Thank you so much for your assistance. Now I need to figure out how to install this. I am not techie!
