### ISSUE TITLE
User images no longer picking from social media

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4032]
User profile  images are not being picked dynamically from social media. I use Google to log in and my user image is empty as well as for other users.

Please look into it.

Thank you

![us_img](https://user-images.githubusercontent.com/65451390/99598586-ce0e1100-2a0a-11eb-9190-5b692ccea60b.PNG)

**Comment by jengajenga** [comment]
hello @akhilleusuggo , @DanielnetoDotCom  .... some assistance please friends.

Thanks

**Comment by DanielnetoDotCom** [comment]
does the same happen on demo site?

**Comment by jengajenga** [comment]
> does the same happen on demo site?

@DanielnetoDotCom 

On the demo site there is no option to login with social media so i am not able to make it happen there.

any other fix?
