### ISSUE TITLE
Logo overlay doesn't keep place in different screen resolution

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#4034]
A minor bug, but when logo overlay is set to top right it doesn't keep the place when using different screen resolutions. E.g. when using phone..  

![image](https://user-images.githubusercontent.com/63721378/99636324-f1a57b80-2a4b-11eb-889b-ef06e833578e.png)

**Comment by akhilleusuggo** [comment]
Not a bug , you need to match the correct ffmpeg to be _responsive_

**Comment by tonuzo** [comment]
Ok thanks, but I'm sorry I don't get it what should I change...?

**Comment by Progressed36** [comment]
follow
