### ISSUE TITLE
Choice of quality during livestream

### ISSUE THREAD

**Issue by Progressed36** [WWBN/AVideo#4035]
Hi,

I would love to know if its possible to have a choice of quality and perhaps auto-change the quality (ex 240/480/720/1080) like youtube in a livestream? i saw a payed plugin but think thats only for uploaded video's.

**Comment by akhilleusuggo** [comment]
HLS plugin , check the market place and read more about it here : 

Plugin : https://github.com/WWBN/AVideo/wiki/VideoHLS-Plugin
And hardware requirements : https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements
