### ISSUE TITLE
Chat 3.9 - Links Open In Chat Area Should Open To A New Page

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4036]
In Chat 3.9 urls can be added to chat, however when someone clicks on a link it opens the page in the chat window when it should open in a new page. 
The only way to get back to the chat is to refresh the browser.

Expected behavior is to open the link in a new page
<img width="410" alt="Screen Shot 2020-11-19 at 6 27 12 AM" src="https://user-images.githubusercontent.com/7376298/99666437-a2058680-2a30-11eb-911d-7d1a07228806.png">
<img width="362" alt="Screen Shot 2020-11-19 at 6 27 37 AM" src="https://user-images.githubusercontent.com/7376298/99666453-a631a400-2a30-11eb-83f3-738897c3a488.png">

**Comment by DanielnetoDotCom** [comment]
You are correct again, 

I just sent an update for the streamer and an update to the Chat2 plugin
