### ISSUE TITLE
On "My Channel" page

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4038]
I would like the first tab to show on the channel page, the channel videos.

How can I set the second tab to display first or change the order of the tabs?

This is the Channel Home:

![Screen Shot 5781-03-03 at 17 48 58](https://user-images.githubusercontent.com/58882903/99689368-94331e00-2a8f-11eb-96dc-156a869eeaf0.jpg)

I would like it to look like this instead:

![Screen Shot 5781-03-03 at 17 49 07](https://user-images.githubusercontent.com/58882903/99689375-97c6a500-2a8f-11eb-9b74-bcece8169ce9.jpg)

**Comment by DanielnetoDotCom** [comment]
Try to remove the Home tab

![image](https://user-images.githubusercontent.com/18009293/99708274-65f81300-2a7c-11eb-86a9-d8d4ed8a788b.png)

**Comment by guymass** [comment]
That did the trick however now the about tab is missing. can we just use drag and drop to switch order of tabs? could be a nice feature.

**Comment by DanielnetoDotCom** [comment]
Sorry we do not have that

**Comment by guymass** [comment]
Thank you, did notice this was controlling it.
