### ISSUE TITLE
Automatically Generate Thumbnails for direct upload's

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4039]
I am beginning to get users to upload videos and some people are using the direct upload feature instead of the HLS feature.
I have noticed that when using the direct upload feature a thumbnail image does not get created and the user has to add an image.

Is there any way we can fix this?

ALSO, not sure if I need to open a new issue or not but can we also make it to where PNG's can be accepted instead of ONLY jpg's.

I can't speak for Windows users, but for Mac users the default screenshot app takes png's ... same for Skitch.

Even myself, have to take an extra step of opening up the png into an image application and then saving as a jpg ... it would be so much easier for all users if they could use a png for a thumbnail.

Thnx

**Comment by JoshWho** [comment]
That is because the direct uploader is not a encoder. It is only uploading the file. The reason why thumbnails get generated on other platforms is because they are encoding the video. That is were the thumbnail gets grabbed from.

There is no auto thumbnail for direct upload.

**Comment by bbyrdhouse** [comment]
I think the "reason" that so many are dong the "Direct Upload" vs. the HLS is because they have no idea what HLS means ... it is possible for me to alert uploader that they should use HLS and explain why?

I do not see anywhere to add a message on the Encoder page ...

**Comment by JoshWho** [comment]
YOu can disable the direct upload. You would have to hard code the message in the page if u want one there.

**Comment by bbyrdhouse** [comment]
I've just edited the AVideo/Encoder/index_formats.php page to include a message about why it is preferable to use HLS over MP4.
I left the option for MP4 upload because there may be a reason why some would choose that option.

**Comment by JoshWho** [comment]
Sounds good. Now at least they know to just generate one and upload it. Do you have the Thumbnail plugin? It is in the store and will help by adding a button in the video dashboard to get thumbnail image.

**Comment by akhilleusuggo** [comment]
> That is because the direct uploader is not a encoder. It is only uploading the file. The reason why thumbnails get generated on other platforms is because they are encoding the video. That is were the thumbnail gets grabbed from.
> 
> There is no auto thumbnail for direct upload.

Direct upload can generate Thumbnails and gifs automatically . For that you need to buy the plugin from the market place .
I don't have it , I don't use direct upload . But the description is clear ;

![image](https://user-images.githubusercontent.com/52116577/99792483-d3b14700-2b2f-11eb-8229-70a6aae797e7.png)

**Comment by bbyrdhouse** [comment]
@JoshWho @akhilleusuggo - I have that plugin and have it activated but it still doesn't generate a thumbnail ... keep in mind I am only talking about direct uploads and not the HLS uploads.

**Comment by DanielnetoDotCom** [comment]
@bbyrdhouse I just test it locally and it works.

what kind of video are you direct uploading?

MP4?

what size they are?

can you test it on demo site?

can you share a video sample so I can test?

can I test in your site?

**Comment by geoasher023** [comment]
My direct upload is also not working and I also purchased the plugin, i get this error in  the log

[04-Dec-2020 23:41:00 America/New_York] Error on get jpeg poster: Video URL does not exists /videos/gerr_5fcb0f5c257d15.56648340.mp4

website is torahjudaism.com
(but i check and that file does exist)
Please help

**Comment by akhilleusuggo** [comment]
I think yeh , on the script is missing the site url ( or is ignoring it )

**Comment by DanielnetoDotCom** [comment]
@geoasher023 please provide a more complete log
