### ISSUE TITLE
color code

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#4040]
hello @DanielnetoDotCom  it would be possible to have the possibility to add the color code

![image](https://user-images.githubusercontent.com/39193219/99728784-3cf67300-2aba-11eb-9a49-ac9b3a255427.png)

**Comment by DanielnetoDotCom** [comment]
Looks like it had a bug, can you please check now.

**Comment by syldri** [comment]
Hello @DanielnetoDotCom  nothing has changed it's always the same things i can't add the color code, i looked at the demo site it's the same things

**Comment by DanielnetoDotCom** [comment]
You need to update the customize plugin on the market place

I just update the demo site

![chrome-capture (2)](https://user-images.githubusercontent.com/18009293/99813558-972d1d80-2b26-11eb-9439-fe1cbd8942c6.gif)

**Comment by syldri** [comment]
thank you so much
