### ISSUE TITLE
Email Notification Limits PLEASE

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4041]
I brought this up a year ago and thought this would become a future problem and is now a huge problem. Email notifications are sending out to everyone even when they unsubscribe and now Amazon blocked my emailing because if it. 

Need a rate limit for email notifications.

CHannels should only be able to send out x amounts of notifications per day no matter how many videos they upload. 

There really needs to be a hard limit or this is going to be impossible to maintain and will keep getting email providers flagged.

**Comment by bbyrdhouse** [comment]
+1

**Comment by JoshWho** [comment]
I have video notifications right now disabled until there is a limit put on.

Every channel needs a limit like 5 emails per day or something like that. If it just goes unfiltered and someone mass uploads 200 videos it will send out hundreds to thousands of emails depending how many people subscribe.
