### ISSUE TITLE
All video gifs are playing without hover

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#4042]
Hello,
when the homepage loads all the gif thumbnails play without hover
is the same on demo page also,
Any help??

Thank you
Ilias

**Comment by TLCReuver** [comment]
Here also in categories.  Categories does not show all videos (Stops scrolling after 1 time).

**Comment by wetubeclub** [comment]
Hello,
to display all videos from the category check this  ShowAllVideosOnCategory
![all category videos](https://user-images.githubusercontent.com/60543030/99842970-0fb8cc00-2b71-11eb-83a1-dfad346c057c.jpg)

**Comment by TLCReuver** [comment]
Bugfix 'all videos in categories' was made today. Works perfect now.

https://github.com/WWBN/AVideo/commit/44c8277ff6f3ad584b07b44287da6f3b97b62c68
