### ISSUE TITLE
Bug in Safari tha grays out JPG's when selecting Thumbnails for Videos (Drag & Drop works)

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4043]
This is a bug, that so far as I can tell only effects Safari on Mac (no idea if Safari on Windows is also affected).

Basically, whenever a user selects the "Browse file" option when selecting a thumbnail image for their video, jpg's are grayed out and unselectable. However, you can still drag and drop a jpg and it works, but people will assume that if it is unselectable from the "Browse Files" that the drag n drop option wouldn't work either.

**To Reproduce**
1. Use Safari on Mac
2. Upload a video using MP4 (not HLS)
3. Try to add your own Poster image by selecting "Browse" (not drag and drop)
4. You are unable to select a jpg, but you will be able to drag and drop a jpg

**Expected behavior**
I expect for jps to be not grayed out and selectable.

**NOTE**: I have used other scripts that have encountered this bug and I know it can be overcome, but I am not exactly sure what needs to be addressed.

**Screenshots**
<img width="1886" alt="Screen Shot 2020-11-20 at 1 51 39 AM" src="https://user-images.githubusercontent.com/7376298/99777140-80aba580-2ad7-11eb-86c4-42cfaf30bf84.png">

 - OS: macOS 10.15.7
 - Browser Safari Version 14.0.1

**Comment by DanielnetoDotCom** [comment]
Try this update
