### ISSUE TITLE
Uploaded Video says "Uploaded 5 Hours Ago" even if it was 1 minute ago

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4044]
**Describe the question**
I need some help. Whenever I upload a new video it says that it was uploaded 5 hours ago even if it was 1 minute ago.
Then several hours later it will say uploaded 2 hours ago or 1 hour ago or something that doesn't make sense.

In "Customize Advanced" the timezone is set to America/Chigaco (Central time)

I have also made sure that the server clock is set to the same time (America/Chicago)

`$ sudo timedatectl`
`Local time: Fri 2020-11-20 06:59:03 CST `
`Universal time: Fri 2020-11-20 12:59:03 UTC`
`RTC time: Fri 2020-11-20 12:59:03   `
`Time zone: America/Chicago (CST, -0600)`
`System clock synchronized: yes`
`NTP service: active  `
`RTC in local TZ: no `

**If I run the comman**d
`sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"`
**I get**
`Fri Nov 20 07:07:50 CST 2020`

Which is correct ... I am not sure what else to check, any ideas?

**Screenshots**

<img width="602" alt="Screen Shot 2020-11-20 at 7 05 10 AM" src="https://user-images.githubusercontent.com/7376298/99803845-b5335780-2aff-11eb-858c-0a08b6e7a5ec.png">

<img width="1267" alt="upload" src="https://user-images.githubusercontent.com/7376298/99803891-c7ad9100-2aff-11eb-9932-5003a9bf48ed.png">

<img width="637" alt="terminal_time" src="https://user-images.githubusercontent.com/7376298/99804237-4c001400-2b00-11eb-9130-208c4d409ad0.png">

**Comment by DanielnetoDotCom** [comment]
Can you please edit your configuration.php file and replace `$global['disableTimeFix'] = 0;` to this `$global['disableTimeFix'] = 0;`

Then please upload a new video and let me know.

**Comment by bbyrdhouse** [comment]
Ok, I've changed the config file as instructed, cleared the cache etc... uploaded a new video and it still says "5 hours".
<img width="331" alt="time-off" src="https://user-images.githubusercontent.com/7376298/99806912-4d334000-2b04-11eb-8ec8-adc3bf6dc81b.png">

**Comment by DanielnetoDotCom** [comment]
I am not sure what is happening.

can you please check what time do you have here?

![image](https://user-images.githubusercontent.com/18009293/99818602-305f3280-2b2d-11eb-9b98-e961ce685a68.png)


and what time does it suppose to be?

Probably you cannot see the full time, I just sent an update to increase width of the "created" column

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Hello Daniel , what really is happening is this :

You upload a video to the encoder . The encoder send the API request to the main server , and register the video ( AT THE UPLOAD MOMENT ) , not when the encoding process finishes . 

In the example that @bbyrdhouse gave , he most-likely uploaded a video 5h ago , and took him 5h to encode .
This happens to me all the time , when I upload many videos , and the queue is long , may even show ''1 day ago or 2 )

**Comment by bbyrdhouse** [comment]
@akhilleusuggo - no ... The encoder is on my server and I literally uploaded a video 1 minute ago ... it took about 10 seconds to upload and about 30 to encode and then I refresh the main page and it says 5 hours ago.

**Comment by bbyrdhouse** [comment]
@DanielnetoDotCom - your image looks a little different than mine ... I use Safari on Mac and the date and time are not fully visible like they are in your screenshot .... see how they are covered up?
![Screen Shot 2020-11-20 at 5 18 11 PM](https://user-images.githubusercontent.com/7376298/99859029-7ed3f780-2b54-11eb-981a-8a52c727a860.png)

**Comment by akhilleusuggo** [comment]
ok , I think I may know the reason .

Go to Plugins , CustomizeAdvanced (CustomizeAdvanced) , 

![image](https://user-images.githubusercontent.com/52116577/99863142-7b1c9100-2ba5-11eb-9fdc-58c47a93b04f.png)

at the bottom , change the time zone to where you are . 
Also make sure that the encoder does have the same timer . 

This is new , and I didn't tested it yet /

**Comment by bbyrdhouse** [comment]
@akhilleusuggo - If you look at the op, I have a picture of that and it is set to the same thing as my server America/Chigaco

What seems to be happening is that when I upload a video it says "5 hours" then 1 hour later it says "4 hours" then 2 hours later it says "3 hours" etc ... 5 hours later it say "1 minute ago" then the time starts counting upwards.

Basically, it appears that it starts off minus 5 hours counts down to zero and then starts counting up like it should.

**Comment by akhilleusuggo** [comment]
Sorry , my bad , didn't saw . Then I really don't know .
I just tested it with a clip , and you're right .

![image](https://user-images.githubusercontent.com/52116577/99863585-81ac0800-2ba7-11eb-9e67-a63414bce87e.png)

Definitely has something to do with the new commits ( about the time zone ) .

The solution that @DanielnetoDotCom gave `$global['disableTimeFix'] = 1;` should work , but again , from my point of views is wrong , and related to what I've said before ; 

> You upload a video to the encoder . The encoder send the API request to the main server , and register the video ( AT THE UPLOAD MOMENT ) , not when the encoding process finishes .

This option `$global['disableTimeFix'] = 1;` should be on the encoder , not on the streamer site .
Maybe later Daniel could take a look .

**Comment by bbyrdhouse** [comment]
@akhilleusuggo - in my case the encoder is on the same server as the streamer and `$global['disableTimeFix'] = 1;` didn't change anything for me.

I am sure Daniel will investigate and hopefully fix in a coming update.

**Comment by akhilleusuggo** [comment]
it doesn't mater if the server and encoder are on the same server . It's the request that is sent what really making this thing .
Even before the encoding have ended , the date is recorded .

**Comment by DanielnetoDotCom** [comment]
@bbyrdhouse can you please run a` git pull` and tell me the video creation date on the database?

I need to know if the database is registering at the wrong time or if is the PHP that has the wrong time.

FYI, git pull will update your files to the latest I have, I have fixed the problem on the created column that was hiding the date.

**Comment by bbyrdhouse** [comment]
I've got a livestream coming up in a bit, it will have to be later in the day. Plus, I'll need to read up on how exactly to do a git pull ... I told you, I hate working in terminal

**Comment by JoshWho** [comment]
SYSTEM time and Server Time are 2 different things on Ubuntu. Need to set both time zones.

**Comment by elias2k1** [comment]
Hello @DanielnetoDotCom, I have the same problem as **@bbyrdhouse**  mentioned. My admin panel shows the correct creation time but streaming site shows it 5 hours ago from the creation time. :(

**Comment by elias2k1** [comment]
My issue resolved by changing the value to $global['disableTimeFix'] = 1;

Thanks
