### ISSUE TITLE
HLS Accepted File Types?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4045]
**Describe the question**
When users upload a video file using HLS, what file types are accepted?
I already know that both .mov and .mp4 are accepted but what about:

- .m4v
- .avi
- .mkv
- others?

**Comment by DanielnetoDotCom** [comment]
HLS means you want to upload an m3u8 file plus hundreds of .ts files?

I do not think this is useful;

but I guess if you have a public m3u8 link you can import the video here 
![image](https://user-images.githubusercontent.com/18009293/99819250-fe9a9b80-2b2d-11eb-9b9d-11ad574f3df2.png)

**Comment by akhilleusuggo** [comment]
Your question is not clear . There's no way to upload HLS video .
If what you mean is , that you transcode it INTO hls , then any codec is supported , as long as you have compiled correctly FFmpeg .
By default on Debian ( sudo apt-get install ffmpeg ) already has most of the codecs supported , except those who belong to third party software , or are not under the same license .

I never found any issues to transcode any format into HLS .

**Comment by bbyrdhouse** [comment]
Huh?

When I go to upload a file and have HLS selected I can upload, I know, .mp4 and .mov files ... I want to know what other files are accepted.

![Screen Shot 2020-11-20 at 5 10 18 PM](https://user-images.githubusercontent.com/7376298/99858794-efc6df80-2b53-11eb-8acd-f87c5c1c2db0.png)

**Comment by bbyrdhouse** [comment]
@DanielnetoDotCom - I didn't ask about uploading HLS files, I asked while file types are accepted when a user goes to upload their video when HLS is selected.

**Comment by akhilleusuggo** [comment]
I you wanna know or add, just go to your config file . ( On the encoder ) 

You should see something like this : 

`$global['allowed'] = array('mp4', 'avi', 'mov', 'flv', 'mp3', 'wav', 'm4v', 'webm', 'wmv', 'mpg', 'mpeg', 'f4v', 'm4v', 'm4a', 'm2p', 'rm', 'vob', 'mkv', '3gp');`

Those are the extensions allowed . You can add others if you want , and that ffmpeg will be able to transcode into hls/mp4/webm or whatever you are planning to do .

**Comment by bbyrdhouse** [comment]
Excellent ... Thanx
