### ISSUE TITLE
Video Adverts only - Best Option ?

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#4046]
Hi Folks

Question. I have a number of  video adverts that I only want show as adverts and not on the website / video stream. 

Whats the best way to do this.. I had a look at plugins and various options, but can't see a guide..

Thanks

**Comment by DanielnetoDotCom** [comment]
Sorry I do not understand what do you mean.

**Comment by kollossus55** [comment]
Ok.. How do you do adverts in the in the video adverising manager ?

Do you have to upload the vdeo you want to use for the advert ?

Regards

**Comment by jengajenga** [comment]
I'd like to understand this too.

**Comment by DanielnetoDotCom** [comment]
Please check this

**Comment by kollossus55** [comment]
Hi All 

I have done mine this way. 
I have marked the videos as "inactive", so they don't show up on the Website. 

I have also placed them in a category called "Adverts", and marked that category as Private. So its only visible to me as admin.
This seems to work for now until I find a better option.

Hope that helps.. 

Let me know if you have a better way too. Thanks
