### ISSUE TITLE
Make it optional if Video starts always from beginning or from last spot

### ISSUE THREAD

**Issue by pchelferlein** [WWBN/AVideo#4047]
Good evening,
it may be an valuable option for people using several PC's if they would hae an Option in their user profile to decide, if they want the videos to be resumed at the last known spot, or if they always would start from the beginning. 

Since I am using several pc's and plattforms, it would be a real benefit if I could decide how the System would handle those.

It also would reduce Server load if such informations would not always have to be stored.

Please consider it an option to leave the user the decision if he wants the resume from last spot feature or not.

Kind regards

**Comment by DanielnetoDotCom** [comment]
It supposes to work just the way you described but was a bug on it.

Now, with this update, It always resumes from the last spot. but you can use the progress bar to change the resume position

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Daniel is there anyway to store the quality selection preferences ?
Like if my last choice was 720p , then next video will auto-select 720p and so on

**Comment by pchelferlein** [comment]
Like I laybeled:
enhancement - not bug, but glad you could kill a problem just because I proposed an enhancement *laughs*
