### ISSUE TITLE
Blank Page After Logout.  Blank Page has no source code or errors in log files.

### ISSUE THREAD

**Issue by fiberalien** [WWBN/AVideo#4048]
**Describe the bug**
Blank Page After Logout.  Blank Page has no source code or errors in log files.

**To Reproduce**
1. Clean install on ubuntu 16 VM
2. git pull from repo to update build
3. login as admin or any other created user.
4. See error: a.k.a blank page rendered after logging out and clicking the home button upper left corner, meaning the Avideo logo graphic, or by clicking the 3 bars upper left menu, then click Home.

**Expected behavior**
It should be returning to the login screen  / main site screen and showing videos etc

**Error Logs**
No errors generated in apache2 logs

**Screenshots**

**Desktop (please complete the following information):**
 - Device: MACBOOKPRO
 - OS: MAC 10.15.6
 - Browser:  Firefox 
 - Version [82.0.3 (64-bit)]

**Smartphone (please complete the following information):**
samsung galaxy phone shows same condition when rendering page from behind a proxy or a NAT, i.e. meaning, any setup, direct, NAT, Bridged or anything.

**Additional context**

The server has 1 NAT interface to connect to the public internet and the second interface is a private network interface to serve up the website itself locally for development purposes.

**Comment by hostquota** [comment]
Try clearing your browser cache. Worked for me.

**Comment by fiberalien** [comment]
> Try clearing your browser cache. Worked for me.

So you replicated the problem and it worked for you?   I have cleared the chache and used several different devices.  Same problem across multiple devices.   iphone, ipad, samsung galaxy, PC and MAC.

Thoughts?

**Comment by fiberalien** [comment]
> Try clearing your browser cache. Worked for me.

Thanks.  I just did a new GIT PULL and the bug is gone.  Clearing the browsers on all devices previously did not work.  

Cheers.
