### ISSUE TITLE
anyone placing /login   at the end of the website domain url gets exposed info.

### ISSUE THREAD

**Issue by fiberalien** [WWBN/AVideo#4049]
**Describe the bug**
anyone placing /login   at the end of the website domain URL gets exposed info.

**To Reproduce**
1. open any browser
2. type in the URL to your AVideo website prefix such as http or https://Avideo.com/login
3. See error

**Expected behavior**
should generate a 404 or the error should be handled better.

**Error Logs**
no error logs.

**Screenshots**
attached
![Screen Shot 2020-11-20 at 6 02 15 PM](https://user-images.githubusercontent.com/74799635/99861057-8c8c7b80-2b5a-11eb-8033-4a973116d704.png)

**Desktop (please complete the following information):**
ANY

**Smartphone (please complete the following information):**
ANY

**Additional context**
NONE

**Comment by DanielnetoDotCom** [comment]
What are you talking about?

what info is exposed?

Do you know what code 404 is for?

**Comment by bbyrdhouse** [comment]
This is what I get ... 
![Screen Shot 2020-11-20 at 6 43 31 PM](https://user-images.githubusercontent.com/7376298/99862689-4df9bf80-2b60-11eb-9c43-c553a90f7471.png)

**Comment by fiberalien** [comment]
Hi Daniel, Everything in the image above.   Is this considered a normal feature of the operation of the website?    Exposing the JSON, Headers and Data info when random words like /login  are type without anything?    In most cases java or php con handles errors when pages are not found or when invalid input is detected.  In this case a JSON Menu Page comes up.
I can go to anyone's Avideo site and get the same results. Dunno if you designed it this way on purpose or not.

**Comment by fiberalien** [comment]
> This is what I get ...
> ![Screen Shot 2020-11-20 at 6 43 31 PM](https://user-images.githubusercontent.com/7376298/99862689-4df9bf80-2b60-11eb-9c43-c553a90f7471.png)

Do you get a JSON Menu?  Instead of displaying a JSON Menu and ERROR Page shouldn't this be handled at the page where the invalid data was entered?

**Comment by DanielnetoDotCom** [comment]
Please do not throw random questions and information here. we have a lot of requests and information to handle here, I cannot spend time talking about no sense.

Sorry but I need to close this
