### ISSUE TITLE
Trying to Record a LiveStream, presented with "can't verify token" message

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4051]
I am trying to record a livestream and when I select the "Start Record" I am presented with an error message that says "Cna't Verify Token" (image below)

<img width="478" alt="Screen Shot 2020-11-21 at 8 18 04 AM" src="https://user-images.githubusercontent.com/7376298/99879402-74f0d980-2bd2-11eb-8ceb-4d50a1fb8c2a.png">

What does this mean and how can I fix it?

- Yes. I do have the SendRecordedToEncoder plugin (vs. 2.1) and it is turned on below are the parameters:

<img width="595" alt="liveb" src="https://user-images.githubusercontent.com/7376298/99882291-e89be200-2be4-11eb-8c62-aac1ec3864f9.png">

Here are the parameters for my "Live" plugin:
<img width="602" alt="live-1" src="https://user-images.githubusercontent.com/7376298/99882231-9064e000-2be4-11eb-9ec4-b2d382ed93ec.png">
<img width="600" alt="live2" src="https://user-images.githubusercontent.com/7376298/99882236-92c73a00-2be4-11eb-82a4-fae436cd6847.png">

I'll be happy to pull the logs if someone can provide me the path of where to find them.

Thanks

**Comment by bbyrdhouse** [comment]
**NOTE**: the/var/log/nginx "**access**" and "error" **logs** are below .... but they are both **empty**

[access.log.zip](https://github.com/WWBN/AVideo/files/5577785/access.log.zip)
[error.log.zip](https://github.com/WWBN/AVideo/files/5577786/error.log.zip)

**Comment by jengajenga** [comment]
Dude, be careful about posting such personal deets. Colour them out. You could compromise your site.

**Comment by bbyrdhouse** [comment]
@jengajenga - thnx ... I always assume that people want to help and not hurt, but you are correct, I should've hidden some of the data ... fixed.

**Comment by DanielnetoDotCom** [comment]
Hi, the controls are not working yet, they will be implemented in the future version.

to auto-record a Livestream you must follow this. but this will record all your live streams
https://github.com/WWBN/AVideo/wiki/Record-Live-Stream
