### ISSUE TITLE
Urgent Pay Per Views Stopped After Last Update

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#4052]
I am still fixing a mess of things since I did the last update. Granted, I had not updated in a year so there was a lot of change to the software.

Payments for video views and comments stopped the day I did the update. A member just told me and sure enough they stopped on the 16th.

I have the custom mod called "DIY" which Daniel wrote for me years ago. And I am using the YPTWallet mod.

Please help me get payments going again.

Thanks

**Comment by DanielnetoDotCom** [comment]
As long it is a support in your custom plugin, you may need to go to the paid support.

**Comment by The-Do-It-Yourself-World** [comment]
I have no idea. The YPTWallet is what runs everything from my understanding. Is this not supported? You have to tell me. Thanks

**Comment by DanielnetoDotCom** [comment]
I have no idea what is the problem, but this is something on your specific plugin, the only way for me to look at it is thru paid support

**Comment by The-Do-It-Yourself-World** [comment]
My site worked perfect before the update, which crashed my site. I paid you $50 to fix my site already.

Are you saying that mods that crash due to updates will cost me money to fix them? Even if they worked perfect before the update?

**Comment by DanielnetoDotCom** [comment]
Sorry but yes, I cannot work for free.

**Comment by The-Do-It-Yourself-World** [comment]
Most of my issues stem from one or two mods that have been giving me trouble since the beginning. YPTWallet and DIY. I paid you to develop DIY 3 years ago but it needs fixing because it never worked right.

Please give me a quote for the following and please be merciful.

1. payments stopped working due to the update on Nov 16, please fix this.

2. set payments to be based on a percentage of watch time. This will stop people from making bots to get fake views with 0 seconds watched to simply get full payment. (This was in my original requirements back when I paid you to develop the mod but it never got done right). Currently if someone simply clicks on a video for a fraction of a second they get full pay. This should not be.

3. Stop paying people for watching their own videos to prevent abuse. This also should never have been allowed. This is heavily abused.

3. Stop database entries with payments of "0" which is cluttering the database. Each day there are thousands of payment entries of 0 made into the database. If someone does not get a payment, there should be no database entry. This causes 100s of thousands of entries which I have to manually remove from time to time.

Please give me a quote for the above. Please be merciful and consider the original terms of the mod 3 years ago.

Thank you

**Comment by DanielnetoDotCom** [comment]
For quotes please email me at developer@youphptube.com

**Comment by The-Do-It-Yourself-World** [comment]
I will copy and past this into an email immediately.

**Comment by The-Do-It-Yourself-World** [comment]
I left you an email. Please reply. I urgently need this fixed. People are complaining that their payments stopped.
