### ISSUE TITLE
Download Videos?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4053]
Is it possible for users to be able to download videos?

I see that there is a download button under the video but all that seems to do is to let you download thumbnails but not the actual video.

Is there a setting I could set or is it not possible?

**Comment by DanielnetoDotCom** [comment]
Is possible to download if the videos are MP4, is not possible to download HLS videos.

**Comment by bbyrdhouse** [comment]
ah ... HLS has pros and cons

**Comment by akhilleusuggo** [comment]
I wouldn't call it a ''cons'' . It's a good way to protect your videos from being downloaded .
For now the script is not complete , but on the future ( if daniel wishes to ) , should be possible to download HLS videos .
With simple script , you can convert HLS into MP4 on the fly .

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo I know we talked about this before, but how do we convert HLS/MP4 instantly (on the fly)

**Comment by akhilleusuggo** [comment]
I may wanna correct , we actually not ''converting'' , but we're joining the fragments , doing something like concat ( in fact is the same tactic , a playlist follow ) , but in a different way .

**Comment by bbyrdhouse** [comment]
That would be well received, if it gave each content creator the control to determine if their videos were downloadable or not

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo thanks this solution is probably possible.

Maybe I will add this in the future

**Comment by Donnerstein** [comment]
@akhilleusuggo 
Do you have an example of such a script?
