### ISSUE TITLE
Left hand menu ... can I add buttons via the plugins parameters?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4054]
Is it possible for me to add buttons to the left hand menu .. currently there is only "Home" and "Trending" I would like to add "Latest Uploads" and maybe "Categories"

<img width="487" alt="buttons" src="https://user-images.githubusercontent.com/7376298/99886029-0aa25e00-2bff-11eb-9338-fede1ca83801.png">

**Comment by DanielnetoDotCom** [comment]
The only way to add a button there is by building a custom plugin.

right now there is no such option.

**Comment by bbyrdhouse** [comment]
I have biult a lot of plugins over the years utilizing html, javascript, css, xml, and php ... do you have a plugin api I could look at, I'd love to see if it something worth pursuing

**Comment by DanielnetoDotCom** [comment]
Sure,

For the API please check this https://github.com/WWBN/AVideo/wiki/AVideo-Platform-API

To code a plugin please use this https://github.com/WWBN/AVideo/wiki/How-to-code-a-AVideo-Platform-plugin

I recommend you to get an already made plugin as a sample and rename it. feel free to make questions here
