### ISSUE TITLE
When Selecting Categories All You See Is A List With No Way To See The Videos

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4055]
When in the Left hand menu, you select "Categories", all it does it take you to a list of categories but no way to see all the videos in that category.

Expected behavior would be to see the categories with a row of videos from that category under it ... or something that gave a visual of the videos that are in a category .... 
<img width="1594" alt="category3" src="https://user-images.githubusercontent.com/7376298/99886134-d7140380-2bff-11eb-9923-001835b0b9d4.png">

Youtube does something like this:
<img width="963" alt="Screen Shot 2020-11-21 at 1 44 44 PM" src="https://user-images.githubusercontent.com/7376298/99886146-e1ce9880-2bff-11eb-80ae-a7b8bd7ae06a.png">

Newtube does it like this:
<img width="1492" alt="category" src="https://user-images.githubusercontent.com/7376298/99886174-222e1680-2c00-11eb-8ea9-319d4ad092e4.png">

**Comment by DanielnetoDotCom** [comment]
Did you try to click on the category title on the gallery front page?

![image](https://user-images.githubusercontent.com/18009293/99962746-7dcae200-2d6f-11eb-83cb-f97601275074.png)

**Comment by bbyrdhouse** [comment]
hum ... my front page doesn't have that, maybe I have turned something off along the way

**Comment by DanielnetoDotCom** [comment]
Check this 

![image](https://user-images.githubusercontent.com/18009293/99973365-73641480-2d7e-11eb-8959-b7782c658678.png)
