### ISSUE TITLE
Menu Goes OffScreen

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4056]
**Describe the bug**
When using Safari and you go to the left hand menu and select "Categories"  and then select the button to rearrange??? the menu flies off the screen and you cant see it even if you resize your browser. Note the image below:
<img width="1571" alt="categories1" src="https://user-images.githubusercontent.com/7376298/99886284-e778ae00-2c00-11eb-9527-ee1c970ef99d.png">

**To Reproduce**
1. Log in to your account
2. Click to open the menu on the left hand side of the page
3. Select Categories
4. Then select the button to the right of the number (look at the attached image) these buttons do not have a tooltip when hovering over them to identify them
5. Notice the menu flies off the screen
6. The SAME issue happens when you select on the little number just to the left of the button I have highlighted in the attached image

**Expected behavior**
The menu should fly out to the center of the page instead of to the left and off the screen

**Error Logs**
N/A

**Desktop (please complete the following information):**
 - OS: [macOS 10.15.7]
 - Browser [Safari 14.0.1]
 - AVideo Version [9.7]

**Comment by DanielnetoDotCom** [comment]
I see, I guess this is a safari only problem

O FF and chrome the menu is here 

![image](https://user-images.githubusercontent.com/18009293/99962884-b074da80-2d6f-11eb-9525-976d1b22c79b.png)

**Comment by bbyrdhouse** [comment]
Yeah, that is much better ... even though they all share Webkit lineage, Chrome forked off of that some time back and FF uses Chrome's fork.

There is probably a css rule that needs to either be added or edited to fix this

**Comment by bbyrdhouse** [comment]
It looks like the search bar needs to be give a definite width because it assumes 100% width
