### ISSUE TITLE
Server suddenly stops streaming

### ISSUE THREAD

**Issue by rielcomms** [WWBN/AVideo#4057]
The Server suddenly stopped streaming. Nochanges were made to it. 
On rebooting the server, the system now says its on Maintenance

We’ll be back soon!
Sorry for the inconvenience but we’re performing some maintenance at the moment.

**Comment by qome** [comment]
It will say it's in maintenance mode for a few seconds to minutes after a reboot, depending on your server.

**Comment by rielcomms** [comment]
It has remained in maintenance mode for over 6 Hours so something must be wrong

**Comment by jengajenga** [comment]
There is a misconfiguration in your configuration.php file under the videos folder. Either your dB name or pass doesn't match. Confirm with your database that the parameters are correct.
