### ISSUE TITLE
Filesize is alsways 0,01 KB using 'Direct upload' (also on demosite)

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#4058]
Filesize is always **0,01 KB** using 'Direct upload' (also on **demosite**)

![Snap1](https://user-images.githubusercontent.com/39981177/99909792-d86e2a80-2cea-11eb-992d-9b5891ed32a9.jpg)

**Comment by DanielnetoDotCom** [comment]
The demo site had a problem this weekend, please try again.

**Comment by TLCReuver** [comment]
I uploaded a new video on demosite --->  Still 0,01 KB. 

![Snap3](https://user-images.githubusercontent.com/39981177/99972070-5d664c00-2d9e-11eb-9e5c-1fdd5d0bca9a.jpg)

**Comment by DanielnetoDotCom** [comment]
I clicked on this button and now shows correctly


![image](https://user-images.githubusercontent.com/18009293/99972691-9a6e1680-2d7d-11eb-8c86-3a80198fd353.png)


I will try to make sure it updates after the upload

**Comment by TLCReuver** [comment]
That would be fine. Thank you.
