### ISSUE TITLE
connection problem on the site to buy a plugin

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#4059]
helle @DanielnetoDotCom  there is a problem when I want to connect to the site with google, when I choose my email address the connection does not work

![image](https://user-images.githubusercontent.com/39193219/99958504-c42d3a80-2d89-11eb-9396-a9d74eb05c02.png)

**Comment by DanielnetoDotCom** [comment]
We had a problem on the server this weekend, please try again.
