### ISSUE TITLE
Audio Only Streaming

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4061]
Is it possible to have audio only streaming similar to something like Icecast? 

Some of my clients don't want to stream video they want to do something like online radio. 

Is this anywhere in plan?

Thank you.

**Comment by bbyrdhouse** [comment]
This would be a really nice feature ... sort of like Spreaker

**Comment by qome** [comment]
Honestly you'd be better off just streaming at a low resolution and bitrate with a static image as your background, rather than changing the entire platform.

**Comment by DanielnetoDotCom** [comment]
I agree with @qome 

also, a static image will consume a very low bandwidth.

**Comment by jengajenga** [comment]
> Honestly you'd be better off just streaming at a low resolution and bitrate with a static image as your background, rather than changing the entire platform.

I don't mean changing the platform, just an addition to.

**Comment by bbyrdhouse** [comment]
@jengajenga - maybe a 3rd party plugin solution

**Comment by bbyrdhouse** [comment]
Oddly enough, the most requested "feature" to implement into my site is the ability to stream only the audio.
I sort of take for granted the amount of data bandwidth that I have at my disposal and forget that a lot of people do not have the "unlimited" data plans that I have. Those are people that would appreciate an audio only stream ... 

I wonder if the "Restream" feature could be used to simulcast the audio to a 3rd party service ... dunno though, I am researching options.

**Comment by DanielnetoDotCom** [comment]
Any idea what is the format for audio only live streams?

is it MP3?

It must be HTML5 compatible

**Comment by DanielnetoDotCom** [comment]
I guess that is the answer what do you guys think?

https://gist.github.com/somoso/00eb8cd7c4e68c02c58448f3cbb5af78

**Comment by jengajenga** [comment]
> I guess that is the answer what do you guys think?
> 
> https://gist.github.com/somoso/00eb8cd7c4e68c02c58448f3cbb5af78

hmmm... interesting... 

the question now is how to integrate it to AVideo. let me look into that. i'll try implement it on my test server.
