### ISSUE TITLE
Article URLs say video currently

### ISSUE THREAD

**Issue by qome** [WWBN/AVideo#4064]
**Is your feature request related to a problem? Please describe.**
It would be nice if article URLs said article instead of video.

**Describe the solution you'd like**
This may be possible with a new rewrite rule.

**Additional context**
![image](https://user-images.githubusercontent.com/58382620/100047033-21031200-2dd7-11eb-9deb-a6b98155d177.png)
![image](https://user-images.githubusercontent.com/58382620/100047071-2f512e00-2dd7-11eb-9f5f-a5530611b475.png)

**Comment by DanielnetoDotCom** [comment]
You are right, I may add this in a soon release.
thanks
