### ISSUE TITLE
LiveChat2 Code to fix the issue where text would randomly break in the middle of a word

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4066]
Line 112 in the style.css file of the plugin LiveChat2 needs to be changed and then a new rule added.

Line 112 currently reads:
```
.bubble{
    overflow: hidden;
    word-break: break-all;
}
```

What this does is target everything in the bubble including words that you don't want broken. You end up having words broken and going to a new line when it doesn't make sense.
What you want to do is target the url inside of the bubble without effecting the text.
If you change line 112 to this, it will be better.

`.bubble {overflow: hidden; word-break: normal; }`

and then add a new rule to target anchors like this:

`.bubble a {overflow: hidden; word-break: break-all; !important; }`

**NOTE**: The "!important" may not be necessary if you remove the current rule for the class .bubble from line 112

**Comment by DanielnetoDotCom** [comment]
Hi, chat2 v4.0 should follow this.

I will update it later today
