### ISSUE TITLE
AVideo-Storage

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4067]
An option to be able to see storage usage from the main site ( plugins/video page ) , without the need to log into the server or login on each avideo storage website .

Also , when logging into AVideo-storage website , it takes a lot of time to display ( if you have a lot of videos ) . Would be good to add infinit-scrolling there , to speedup the things . Or will take forever to be able to change tab .

**Comment by DanielnetoDotCom** [comment]
You are right.

the file explorer on the first page is a third party app.

I will probably build something on the streamer site to navigate on it.

**Comment by qome** [comment]
It would be nice if there was an interface to the storage network similar to the interface for the encoder network so I could quickly identify usage and queuing.
