### ISSUE TITLE
How can I reduce the number of files with multiple resolutions?

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#4069]
Hi Daniel,

After update AVideo to the latest version today.
I found the encoder will encode video to many resolution.

![1606282561118](https://user-images.githubusercontent.com/57282919/100187843-8d872980-2f1b-11eb-9943-979569a4c7e9.jpg)

How can I reduce the number of files with multiple resolutions to show only 360, 720, 1080?

**Comment by bbyrdhouse** [comment]
I would like to see the content creator be able to decide if their videos are downloadable and also select what resolutions are downloadable. 
This way they upload a high quality video on the site but only allow lower quality to be downloaded.
or vice versa

**Comment by DanielnetoDotCom** [comment]
@guitarpound uncheck **showOnlyEncoderAutomaticResolutions** and you will have the old encoder style

![image](https://user-images.githubusercontent.com/18009293/100259018-7bf74f00-2f26-11eb-8f7e-6b3709cbab12.png)

**Comment by guitarpound** [comment]
Thanks

**Comment by guitarpound** [comment]
Hi @DanielnetoDotCom 

I already uncheck the showOnlyEncoderAutomaticResolution.
But It still there is one more resolution here.  
And it can't playback the video too.
How can I remove this one too?

![1606381227861](https://user-images.githubusercontent.com/57282919/100329834-c51bd180-3000-11eb-82e9-d2f686d2c0c4.jpg)

**Comment by DanielnetoDotCom** [comment]
can you please put this link here?I fount the error, and it is fixed now
