### ISSUE TITLE
Advice on External Storage Solution (YPTStorage)

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4072]
I am quickly seeing that I will need more storage. I do not yet have the YPTStorage plugin, but will happily buy it if need be.

I want to know:
1. Does the YPTStorage work seamlessly with the rest of the site including the HLS plugin?
2. Is it easy to set up? ... or I should probably ask, would someone be willing to walk me through it?
3. What other costs are involved besides the price for the YPTStorage plugin? I currently utilize Backblaze for some other projects I manage and their costs are really low for what you get.

4. Where does the YPTStorage actually store files? Amazon? Backblaze? or somewhere else? Will I need to create an account there if I don't have one already?

**Comment by akhilleusuggo** [comment]
1. Yes , but for me ( the long videos are a pain to transfer ) , it's using bzip2 compression , and it's really slow . No point using this compression . If you are going to stream 1-2h , and send it to encoder , expect ( encoding time ) , + zipping , + transfer to main site , unzipping + zipping again ( with bzip2 very slow ), transfer + unzipping bzip2 ...
2. It's really ez to setup .
3. You have full control of your server . And you can host other things there . If it's powerful , you can even have an additional encoder there , or host whatever you want .
4. On your own dedicated server / VPS .

**Comment by bbyrdhouse** [comment]
RE: 3 & 4

3. I don't have control over my server, or I should say I don't feel as if I do ... I rented from AVideo a server but am told that I can't get access to the database unless it is through Terminal. The server is dedicated for ONLY AVideo script. I have other vps and vpc servers for my other projects.

By "other costs" ... I mean, I know that there must be a monthly cost involved for all the extra TB's of space that the YPTStorage plugin uses ... surely, its not that you pay $59 for the plugin and then get a bunch of space for free.

4. I asked where are the files that utilize YPTStorage plugin actually stored and you answered on my server ... Forgive me, I am a little confused by that.
The server I am renting has a little less than 2 TB os space, so I need to plan for more storage. I want to use the YPTStorage plugin. Where does that space come from ... It has to come from somewhere, what is the cost of that? Where can I find the ongoing costs of renting the extra server/storage space?

**Comment by DanielnetoDotCom** [comment]
@bbyrdhouse the plugin is just the software to handle the file transfer between encoder/streamer/storage .

the host space/speed/bandwidth is up to you. you can use an Ubuntu server (Dedicated or VPS)

**Comment by bbyrdhouse** [comment]
Ok, but on this page https://github.com/WWBN/AVideo-Storage/wiki/AVideo-Platform-Storage-Scenario-Description

You give a scenario where a guy has a 100Gb server but need 30Tb os space so he gets 2 servers for US at 12Tb each and a 3rd for Asia at 12Tb each ... 

Where did he get those servers from? 
We already know that the YPTStorage doesn't work with Backblaze and Amazon S3 ... Where does someone go to get a server with 12Tb os space?

Example: I've got a server that runs AVideo that costs roughly $1200 a year for roughly 2Tb of storage.
To get 12TB of storage on a server must cost thousands of $ a year, right? I am having trouble even finding companies that have that much storage available in a server ... 

What company(s) will work with the plugin and roughly how much money are we talking about?

**Comment by akhilleusuggo** [comment]
@bbyrdhouse Man , you need your own server . You can buy/rent a private server . Just google it , dedicated server or VPS , you will find a list of thousands of providers . Pick the one on the location you want ( with the specs that you want , number of cores , storage space , RAM , bandwidth , operating system . Everything that you want . You can customize it to your will . And you have full control over it ( if dedicated ) .

**Comment by bbyrdhouse** [comment]
@akhilleusuggo - I have a few dedicated servers and have had dozens through the years, I have never had on that had 12TB of storage that was anywhere near a price range I was willing to pay.
I currently have a dedicated server from @DanielnetoDotCom 
I have searched and looked at, roughly 20-24 companies over the last couple hours and havn't found one that offers that kind of storage

**Comment by akhilleusuggo** [comment]
If you just want me to give you an example , take a look here ; https://www.ovhcloud.com/en-ie/bare-metal/storage/prices/

48TB for 95€ . ( But you will need RAID 1 or 5 for redundancy in case of disk failure ) . Also 12TB , is a bit over-killed for a starter website . 48TB , idk how many videos you gonna be uploading everyday , but that's a LOT .

There are many many providers that does have hundreds of TB to offer , maybe you're not looking on the right place .

**Comment by bbyrdhouse** [comment]
@akhilleusuggo - my website has been up for about 1 month and I have purposefully not advertised it simply because I don't want to run out of room.
I have a total of 4 users who are uploading videos right now and have used roughly 50-60Gb os storage. That may seem small, but I have a customer list of over 100k that I will be advertising to.

2TB will be used rather quickly with even 20 content creators uploading videos.
2 of my users are currently uploading 2 hour podcasts each day ... which is cool but you can see my dilema. I need to think ahead.

Since my last post I have learned that there are companies that will have "Storage Servers" as opposed to a regular server ... from what I understand they are equipped with less powerful processors and focus more on storage than performance. Does that sound correct?
I was finding dedicated servers for anywhere from $1200 per year to $5000 per year that had less than  2TB of space wich is just crazy expensive. 
I only referenced the 12TB of space because it is what Daniel used in his example. I would probably only be looking at 5TB as a first storage server.

Therefore, if you run across any good deals for a storage server with 4-6TB of storage please reach out and let me know.

It would be awesome if we could use Google Drive Enterprise with this plugin (super cheap) sort of like people do with Plex and Google Drive ... they are getting 25TB Google Drives that they use as a media server for Plex server.

**Comment by DanielnetoDotCom** [comment]
I see, buit is not possible to use google drive to host your videos

**Comment by akhilleusuggo** [comment]
Google drive even if you manage to trick it , you'll get banned . Is against the policy .
The storage is not really an issue . I can give you providers with 2TB , for only 9$/month , but the bandwidth is only 100mb/s , and no raid ( it means , if the drive fails , everything lost ) .

For 15$ , you can have a 4 TB ( only 2TB usable , since the it's 2TBx2 , second drive used for redundancy ) , but again only 100mb/s . Hosting 2TB requires good bandwidth or you gonna be struggling . 

For me is more about the internet speed then storage space . You can have only 1 video hosted ( let's stay 2gb ) , but got a lot of views ( 20-50 simultaneously ) , you need at the least 200mb/s for smooth playback .

Price will play a roll on quality/quantity . OVH is a good provider to take a look at right now . But if you're from US , I bet there are much better offers over there . Since I'm living in Europe regions , US servers will lead to slow speed/packet lost .
Google is your ''friend'' . Just ask .

**Comment by helpgizmo** [comment]
@bbyrdhouse Have you found a solution for the storage and speed?
