### ISSUE TITLE
Separate page with broadcasts .m3u8

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#4073]
I think that a separate page with .m3u8 broadcasts will be very helpful.
When you have a lot of broadcasts in the LiveLinks plugin, it is inconvenient that they are all on the main page, it is better for them to make a separate page and display the necessary ones on the main

For instance:

<a href="https://radikalno.ru/full/2020/11/25/ce904278e49f2a8a45c87de2abb18f1c-full.jpg.html" target="_blank"><img src="https://cdn1.radikalno.ru/uploads/2020/11/25/ce904278e49f2a8a45c87de2abb18f1c-full.jpg" border="0"/></a>

**Comment by jengajenga** [comment]
I agree. With categories also.

**Comment by palich91** [comment]
@DanielnetoDotCom, please comment on this suggestion. This is a good offer for many

**Comment by palich91** [comment]
I understand that this is not interesting to anyone?

**Comment by DanielnetoDotCom** [comment]
I am working on something like this, a "TV" page with some live content on it. I will release it in a soon feature.
