### ISSUE TITLE
How to display resolution on Video_page

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#4075]
Maybe a simple question but how do you enable to dispay the Resolution (_SD/HD/Low_ etc) on the videopage.

Doesn't find it in the plugins '_Gallery_' & '_CustomizeAdvanced_' ?!

![Snap4](https://user-images.githubusercontent.com/39981177/100249489-e7e4b200-2f3c-11eb-8ffa-b5164de6e847.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, do you have any FHD video?

![image](https://user-images.githubusercontent.com/18009293/100260789-9af6e080-2f28-11eb-94dd-ad334d835962.png)

It should auto appear on the gallery

**Comment by TLCReuver** [comment]
No, i don't FHD but i use it for example.

I see on demosite that you can enable it somewhere but i can't find the setting for this feature
![Snap5](https://user-images.githubusercontent.com/39981177/100264242-de644580-2f4e-11eb-9bd4-191435ace9d7.jpg)

**Comment by DanielnetoDotCom** [comment]
Is this unchecked on your site?

![image](https://user-images.githubusercontent.com/18009293/100349608-7b62c500-2fc7-11eb-9ab4-4c4cf0a95fcf.png)


What AVideo version are you running?

**Comment by TLCReuver** [comment]
I have '**_disableVideoTags_**' enabled because of https://github.com/WWBN/AVideo/issues/3936 very slow page load after update)

![Snap7](https://user-images.githubusercontent.com/39981177/100380310-e5568b00-3016-11eb-9feb-94a57b58e890.jpg)

When i disable '**_disableVideoTags_**' the screenresolution are visisble but i got a very slow page load.

**Comment by DanielnetoDotCom** [comment]
Hi, the tags suppose to create cache files. it may be slow on the first access, but then suppose to work well.

maybe the cache is not working, check your logs for permission issues, or maybe some clue to see what is slowing down.

how many videos do you have hosted?

**Comment by TLCReuver** [comment]
There are 1511 videos hosted Daniel and indeed there are some errors:

#1492 [23-Nov-2020 19:27:40 Europe/Amsterdam] PHP Warning:  chmod(): Operation not permitted in /var/www/html/www.mysite.com/objects/functions.php on line 1839

#1504 [23-Nov-2020 19:27:06 Europe/Amsterdam] AVideoLog::ERROR: Error in writeSql : (1062) Duplicate entry '1518' for key 'categoryId', SQL-CMD:INSERT INTO `category_type_cache` (`categoryId`, `type`) VALUES (?, ?); SCRIPT_NAME: /objects/videoAddNew.json.php

#1505 [23-Nov-2020 19:27:06 Europe/Amsterdam] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/www.mysite.com\/objects\/mysql_dal.php","line":98,"function":"log_error","args":["Error in writeSql : (1062) Duplicate entry '1518' for key 'categoryId', SQL-CMD:INSERT INTO `category_type_cache` (`categoryId`, `type`) VALUES (?, ?);"]},{"file":"\/var\/www\/html\/www.mysite.com\/objects\/video.php","line":470,"function":"writeSql","class":"sqlDAL","type":"::","args":["INSERT INTO `category_type_cache` (`categoryId`, `type`) VALUES (?, ?);","ii",[1518,99]]},{"file":"\/var\/www\/html\/www.mysite.com\/objects\/video.php","line":329,"function":"autosetCategoryType","class":"Video","type":"::","args":[1518]},{"file":"\/var\/www\/html\/www.mysite.com\/objects\/video.php","line":1225,"function":"save","class":"Video","object":{"created":"2020-11-23 19:27:05","modified":"2020-11-23 19:27:05","order":1,"views_count_25":0,"views_count_50":0,"views_count_75":0,"views_count_100":0},"type":"->","args":[false,true]},{"file":"\/var\/www\/html\/www.mysite.com\/objects\/video.php","line":779,"function":"updateFilesize","class":"Video","type":"::","args":[1518]},{"file":"\/var\/www\/html\/www.mysite.com\/objects\/videoAddNew.json.php","line":134,"function":"getVideo","class":"Video","type":"::","args":[1518,"",true]}] SCRIPT_NAME: /objects/videoAddNew.json.php

#1547 [23-Nov-2020 18:47:32 Europe/Amsterdam] PHP Warning:  rmdir(//var/www/html/www.mysite.com/videos/cache/): Directory not empty in /var/www/html/www.mysite.com/objects/functions.php on line 2769

#1548 [23-Nov-2020 18:47:32 Europe/Amsterdam] PHP Warning:  rmdir(//var/www/html/www.mysite.com/videos/cache//YPTObjectCache): Directory not empty in /var/www/html/www.mysite.com/objects/functions.php on line 2769

**Comment by DanielnetoDotCom** [comment]
try to give some permissions 

first make sure you removed the cache 

`sudo rm -R /var/www/html/www.mysite.com/videos/cache`

than add write permission on videos dir

`sudo chmod -R +w /var/www/html/www.mysite.com/videos/`

**Comment by TLCReuver** [comment]
Sorry, all videos are stored on a NTFS SSD-drive (that is slowing down also)

But indeed, when videos are for the first time are cached the page_load_time is very fast.

Is it possible to cache all videos with a command or button because if you have lots of videos it take a while before they are cached.

**Comment by DanielnetoDotCom** [comment]
No, it is not

can your NTFS server host a ubuntu/web server?
if it does the YPTStorage may be a good solution for you.

**Comment by TLCReuver** [comment]
I run VBox 6.1 under Windows 10 with Ubuntu 18.04. The NTFS-drive is mounted in Ubuntu and with plugin 'SecureVideosDirectory' i have access to the video directory and it work perfectly. Under Windows i make every 2 days a backup from Vbox and Videosmap (hexcheck) by cron. But i will try to  use  YPTStorage instead.
