### ISSUE TITLE
OneSignal

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4076]
Is there anyway to enable one signal on notify when new video upload ONLY to the people who are subscribed to a channel . Because the notification is sent to everybody , no mater they're subscribed to the channel or not . This is becoming a spam , rather then notification . ( same for live stream )

![image](https://user-images.githubusercontent.com/52116577/100292066-26538e80-2f88-11eb-8b67-bedeb309591c.png)

And what is the difference between the first option and the second/third option ?
If only the first one is enabled , what type of notification will be send ? ( Nothing ? )

**Comment by JoshWho** [comment]
That is possible but not with this setup how it is right now.

Currently the way it is setup is to notify for all uploads no matter what channel it is.

One signal has limits in place I think it is like 10k Push per transaction before they want you to buy a subscription from them to send out more.

**Comment by akhilleusuggo** [comment]
That's exactly the point to avoid , and also the spam . I had to disable it , because notifying all the users about a every new video , it's crazy . It's spam ...

**Comment by JoshWho** [comment]
What would be neat to see, is a option for individual channels to use their own onesignal account.  Just add the fields for one signal in the my account settings. That way it would be seperated and now everyone can use the feature for their own audience.
