### ISSUE TITLE
Channel Art

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4077]
Not able to change the channel art after the first upload . I made sure it's not a permission issue ( chmod the directory to 777 ) .

If we're able to fix this , I would like to ask something . Since the ''Channel Art'' is supposed to be ''responsive'' , we should use ffmpeg to make that responsiveness by recommending uploads of 2560x1440 . After this point , the script should resize the picture to the dimensions recommend to each device . Only this way we can achieve responsiveness .

Flowing with your recommendations ; https://github.com/WWBN/AVideo/blob/master/view/img/sampleGuide.png

TV : 2560x1440
Desktop Max : 2560x423
Tablet : 1855x423
Desktop mini and mobile : 1546x423

Should look like this ; 

`ffmpeg -i $input -vf scale=2560x1440 channel_art_2560x1440.jpg -vf scale=2560x423 channel_art_2560x423.jpg -vf scale=1855x423 channel_art_1855x423.jpg -vf scale=1546x423 channel_art_1546x423.jpg`

Then depending on the device , should use one of the background generated 

**Edit :** 

The ffmpeg wouldn't work as expected actually . Since the dimensions recommended does not scale properly . The other way is to have an option like on site configuration , to zoom and select the part to show . This way , no resizing is required ;

![image](https://user-images.githubusercontent.com/52116577/100300227-370eff00-2f9e-11eb-978e-fd3e8fc1f6be.png)

**Comment by DanielnetoDotCom** [comment]
Hi

I do not understand why to use FFMPEG? will we extract it from a video?

If it is just an image upload FFMPEG is not necessary

**Comment by DanielnetoDotCom** [comment]
Regarding the file upload it works here, maybe it was a browser cache issue

**Comment by akhilleusuggo** [comment]
> I do not understand why to use FFMPEG? will we extract it from a video?
> 
> If it is just an image upload FFMPEG is not necessary

Because is not responsive
