### ISSUE TITLE
Front page 2 Users Uploads are showing up like Categories

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4079]
On my front page (the Gallery page) there is the "Latest uploads" and "Most Watched Videos" then after that, strangely, it show the video uploads from two users (just two) and then it lists the categories. 
Any idea why it does this and how I can make it stop?

<img width="440" alt="Screen Shot 2020-11-26 at 4 56 40 PM" src="https://user-images.githubusercontent.com/7376298/100395974-c8b35680-3008-11eb-9da2-0249f71006a0.png">
<img width="576" alt="Screen Shot 2020-11-26 at 4 56 46 PM" src="https://user-images.githubusercontent.com/7376298/100395976-cbae4700-3008-11eb-9596-2e41f39e4fd7.png">

**Comment by DanielnetoDotCom** [comment]
Hi, sorry I do not understand what is the issue.
