### ISSUE TITLE
Add Parler SHare Button to the share buttons u have already

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4080]
Could you please add this to the share buttons script @DanielnetoDotCom  It is the social network Parler's Share button.

Please and thanks.

```
<script>
	function parlerSHARE() {
  window.open("https://parler.com/new-post?message="+ window.location.href);
    }
</script>

<button type="button" style="background-color: rgba(255, 0, 0, 0);
border: none; cursor: pointer; display: inline; outline: none" onclick="parlerSHARE()">
<img src=" https://image-cdn.parler.com/A/Z/AZClHZZyBW.png" alt="P" width="45">
</button>
```

**Comment by CROSSMediaNet** [comment]
Also with Gab.com as well

**Comment by bbyrdhouse** [comment]
+1 on both of these platforms ... I prefer either of them over other, more well known platforms ;-)

**Comment by DanielnetoDotCom** [comment]
Hi, I sent an update that includes Parler on the share option, but ...

1. there is no parler icon on font-awesome
2. I do not want to include any external js to share links, but I guess the direct link works fine
3. regarding the Gab.com @CROSSMediaNet request, I could not find on google how the share link looks like. also, there is no icon for Gab.com on  font-awesome

**Comment by CROSSMediaNet** [comment]
Do you want me to send it to you if possible? Google will not have Gab.com images nor links to the site from Google.

**Comment by DanielnetoDotCom** [comment]
I mean, should be a link to use for a share button.

for example for parler I can use `https://parler.com/new-post?message=My Message`

I do not know how is the gab.com link

**Comment by CROSSMediaNet** [comment]
Okay...I can contact the web developer on that

**Comment by JoshWho** [comment]
I am looking everywhere for a share button script for gab and I cannot find one. Not sure if Andrew Torba made one. He banned me years ago so I have no way to talk with him.

**Comment by walt93** [comment]
Can we re-open this? I've coded a gab share and am trying to work around the font awesome issue. I found a solution involving injecting some svg into font awesome from javascript at runtime, but, its offsetting the icon and not rendering, so still working it out.

**Comment by JoshWho** [comment]
Not sure if I can reopen this Might have to just start a new thread

**Comment by DanielnetoDotCom** [comment]
Hi, we used to have that button but I am a bit lost about what happened, I guess parler was shut down. is it back?

**Comment by JoshWho** [comment]
Yes they r back online

**Comment by DanielnetoDotCom** [comment]
Do you have a sample link to share it?
