### ISSUE TITLE
Article Images Upload Area is Whack on Safari (macOS)

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4081]
**Describe the bug**
When adding an article using Safari (14.0.1 ) you click on the images tab, the tab window never opens up completely, it is too compressed to see anything.

**To Reproduce**
1. Using Safari 14.0.1
2. Go to add an article
3. Select Images
4. Note that the window never fully opens

**Expected behavior**
You should be able to see the contents of the window fully

**Error Logs**
N/A

**Screenshots**
<img width="1408" alt="Screen Shot 2020-11-27 at 9 01 22 AM" src="https://user-images.githubusercontent.com/7376298/100462301-ae708b80-308f-11eb-8549-91b99d8fdbc1.png">

**Desktop (please complete the following information):**
 - OS: [macOS 11.0.1 ]
 - Browser [Safari]
 - Version [14.0.1]

**Comment by DanielnetoDotCom** [comment]
I tried to reproduce it on my safari on Mac and it works fine.
