### ISSUE TITLE
Articles Should Be Given Their Own Container Instead of Sharing "videoContainer"

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4082]
Currently, Articles share the dive container id "videoContainer" and therefore inherit css rules intended for videos that do not really look good for articles.

#1 - Articles should be full length and inside of a scrollable iframe. I understand if they have to use an iframe, but it needs to be full width and not have a max-height applied.

#2 - The black border that gets applied to "#videoContainer" looks really out of place wrapped around an article. There should be no background applied to the wrapping container and therefore should inherit the background color of the page. (In my case #ffffff)

#3 - Further in the DOM tree, you have id="videoContainer" > id="main-video" and you have applied a fontsize of 1.5em to that container ... this may be necessary for videos, it isn't for articles ... this should be a feature that the site admin can set and apply universally to all articles. 

I like the idea of being able to add articles but the implementation needs some tweaking IMO 

<img width="977" alt="Screen Shot 2020-11-27 at 9 10 21 AM" src="https://user-images.githubusercontent.com/7376298/100463528-9a2d8e00-3091-11eb-9a22-ec90f4f6221e.png">

Thanks for considering
Gary

**Comment by DanielnetoDotCom** [comment]
With this update, you have a CSS class `.ypt-article ` and `.ypt-article-container` and `.ypt-main-article` that you can use to direct and customize your CSS specific for articles


![image](https://user-images.githubusercontent.com/18009293/100624639-6efda580-3302-11eb-92e6-50fc2c9b9c32.png)

**Comment by bbyrdhouse** [comment]
Great! ... Thank you!
