### ISSUE TITLE
Are Content Creators Allowed To Mark Their Content (some or all) To Be Available Only To Subscribers?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4083]
**Describe the question**
Is it possible for content creators to charge for access to their videos or articles? 

As a site admin, I want to avoid as much as possible being a collector of funds and then be responsible for disbursing those funds to content creators, it would be much better to have them collect their own funds.

Maybe this can be accomplished by adding a new role called "content_creator" that give them some more permissions that regular users do not get.

IF this is already possible please tell me how I can achieve this.

**Comment by DanielnetoDotCom** [comment]
I guess you are looking for that https://github.com/WWBN/AVideo/wiki/PayPerView-Plugin#userscansetppv
