### ISSUE TITLE
Is tinyMCE used for page creation? 

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4084]
I use tinyMCE for several other websites I have built and maintain and it appears that AVideo also uses tinyMCE for those parts of the script that allow for page creation (Article & TopMenu/Page).

The toolbars for these areas is lacking some things that I feel they need. I would like to edit the script or html where the toolbar is built/called (don't worry, I am a professional and do this all the time on numerous websites for many many years).

I just need to know the path for where those toolbars are called.

For instance, if you crack open the TopMenu and take a look at the page/editor.php file, it doen't seem to be creating a toolbar there, so I would presume, it is simply using a default toolbar. I want to customize that.

Thanks

**Comment by JoshWho** [comment]
Look here /var/www/html/YouPHPTube/view/js/tinymce

**Comment by JoshWho** [comment]
In your case /YouPHPTube/ will probably be /Avideo/   or something like that.

**Comment by bbyrdhouse** [comment]
Actually, after digging around I found where the toolbar is created. It it located in AVideo/view/managerVideos_body.php beginning on line 703.

I change the plugins to the following:

`plugins: 'print preview paste importcss searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern noneditable help charmap quickbars emoticons',`

and the toolbar to: 
`toolbar: 'formatselect fontselect fontsizeselect forecolor backcolor | code | removeformat codesample pagebreak | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | insertfile image media link anchor | numlist bullist | undo redo',`

This gives a better toolbar for editing video descriptions and for writing articles.
