### ISSUE TITLE
API Error for live stream in my Other php script

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#4086]
Greetings Mr D.Neto.  I have a problem with the API.. I used it in my PHP Script other than You
![Meet My Craft live](https://user-images.githubusercontent.com/72950503/100489602-01673480-30ca-11eb-9afb-5f061223dac7.png)
PHPTUbe for live streaming.. The live stream sshowed up but when i clicked go live it showed an error providedd in the screen shot.

**Comment by DanielnetoDotCom** [comment]
Sorry I do not know this error
