### ISSUE TITLE
Bulk embed link showing

### ISSUE THREAD

**Issue by gujarraju** [WWBN/AVideo#4087]
Dear Daniel
I don't know why showing bulk embed link in every video header side

Please check attached picture
![Screenshot yoo](https://user-images.githubusercontent.com/35865505/100498842-0681bd80-3176-11eb-9b64-ee7ce321a957.jpg)

**Comment by gujarraju** [comment]
Please help me someone

**Comment by DanielnetoDotCom** [comment]
Hi, I guess I fix it some time ago, can you please make sure you have the latest?

**Comment by gujarraju** [comment]
Yes currently I am using 9.7

**Comment by DanielnetoDotCom** [comment]
can you reproduce it on demo

**Comment by gujarraju** [comment]
Demo site working fine

But before fine in my site after I update I am getting this error

**Comment by DanielnetoDotCom** [comment]
But did you make a git pull yesterday?

I guess it is already fixed.

**Comment by gujarraju** [comment]
Yes now fixed...
Thank you
