### ISSUE TITLE
Watch folder for encoder

### ISSUE THREAD

**Issue by ololax123** [WWBN/AVideo#4088]
Hi, 

First of all, thanks for an awesome project.

Onto the feature request, I would love the feature to have a "watch folder" which the encoder checks periodically.

1.  Media gets placed in the watch folder
2.  If the media size is not changed within say 5minutes start processing media.
3. Media is encoded by encoder (same as bulk upload)
4. When media is encoded and done, move the original file from "watch folder" to "completed" (or optionally delete if original file is not needed to be saved)

Media is now encoded, and added to site from the watch folder.

I feel this is useful for content creators to be able to just save their project to a specific folder when the video is done and then processed automatically. If you have a script that saves video / streams they can save to the watch folder and when the clip is done it will be added.

Hopefully you can see why this could be useful for certain use cases and consider looking into adding the feature. I don't think it would be too difficult since bulk import is a big part of the work.

**Comment by DanielnetoDotCom** [comment]
Do you mean you will have a folder in the server, and whenever you have a new file the encoder will auto process it?

Did you see this ?
https://github.com/WWBN/AVideo/wiki/Bulk-Upload-Videos

**Comment by ololax123** [comment]
Yes exactly, a folder that it auto processes all files in if the file hasn't changed in like 5 minutes (to make sure the transfer / whatever is complete). One way would be to be able to have multiple "watch folders" that you assign categorys to, or just have a default category for content from the watch folder.

When the file in the watchfolder is encoded and done it would either move the file, or delete it.

Bulk-upload is what I do now, but since I have automated the process to get the files to the folder, it would be lovely to have them automatically encoded also, to make the process from create media to distribution faster and more automated.

**Comment by DanielnetoDotCom** [comment]
This is an interesting tool. but it will not be developed in a soon feature.
if you need that you can develop by yourself or you can hire us to do it.

**Comment by akhilleusuggo** [comment]
@ololax123 I have this feature on my Unraid server . I know what you mean and what you talking about . The thing is , I see no benefit of it , because you still need to upload the video to the server .

In this case will be more difficult . You want the videos to be encoded automatically . Under witch user ? How does the encoder know that ? What title ? ( let's say the default one ) ; But not a big benefit .

**Comment by ololax123** [comment]
Upload to the server can easily be automated, espec if you save streams etc. Either a directory per user (set to default category) or something like that. Title  from filename
