### ISSUE TITLE
Using YPTStorage locally

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4090]
I have a second drive on my server, it has 240GB free space which I would like to add to the site. How do I expand the videos directory to use my second drive with the plugin we purchased for this purpose. I need a solution that will allow to expand the videos folder or allow to use another videos2 folder.
If this plugin is made to work with local mounts than how do I configure it to do so?

**Comment by DanielnetoDotCom** [comment]
I guess you can make a new installation of the YPTStorage in a subdomain on the same server, and use the videos directory of this new installation on this new drive. and then you can just add a new server in your plugin

**Comment by guymass** [comment]
Sounds good I will try that thanks/

**Comment by guymass** [comment]
How do I get the secret for the subdomain?

![Screen Shot 5781-03-17 at 8 38 14](https://user-images.githubusercontent.com/58882903/101055965-21e43280-3593-11eb-867c-a7a8554e0e53.jpg)

**Comment by guymass** [comment]
Is there a way to have multiple selections of users to set their storage location instead of going one by one?

This is too hard when we have many users.

![Screen Shot 5781-03-17 at 19 10 58](https://user-images.githubusercontent.com/58882903/101063320-56f48300-359b-11eb-9a18-67d28f347465.jpg)

**Comment by DanielnetoDotCom** [comment]
do you mean each user will setup his own storage?

we do not have that. It must be made by the site admin.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I don't know if that what he meant , but I would like to recommend taking advantage of the Location_plugin .
Based on the uploader account creation IP , assigned him a storage site automatically .

**Comment by guymass** [comment]
Well there is the option to set it to be the new default storage for everyone, but if I wanted to divide storage location per user I need to select each user in the list and than set its storage. It would be nice if there was a checkbox of some sort where I can select multiple users and set the storage for them. Also the idea of assigning storage under the user edit page is very good too.

**Comment by guymass** [comment]
![Screen Shot 5781-03-18 at 13 57 16](https://user-images.githubusercontent.com/58882903/101161082-b0f75600-3638-11eb-9d1d-7ec2567e2212.jpg)

Getting this error on the YPTStorage server. I currently cannot see any uploads going to the storage location.

Any idea what this means?

**Comment by DanielnetoDotCom** [comment]
the phpSysinfo is a third party software. but I do not think it has something to do with the file transfer

you can look for errors on the storage log file and streamer log file.

**Comment by guymass** [comment]
I cannot see where the storage.log is and now all videos that were made after setting the storage plugin are not working and are not located in the new videos folder. I hope all the streaming we made yesterday is not lost. Not sure how this plugin should work but its not doing its job and it is not clear what is going on with it. If you take a look at live.ahava528.com all the latest videos are not playing at all.

**Comment by guymass** [comment]
All new uploads get this!

New streams are not showing as well.

![Screen Shot 5781-03-19 at 9 54 24](https://user-images.githubusercontent.com/58882903/101237270-05094580-36e0-11eb-8360-3a4e7bc76990.jpg)

**Comment by guymass** [comment]
Storage plugin screwed up all videos and streams made after it was setup.
No files are moved to new storage and although they are listed in the
videos list no of them are playing! I am not sure what is going on with the
plugin but even disabling it, clearing caches doesn't work.
Is there a manual or a readme file for this plugin installation and
configuration? Where exactly does its log file is created?

**Comment by guymass** [comment]
Also not sure what this should be configured?

![Screen Shot 5781-03-19 at 10 31 04](https://user-images.githubusercontent.com/58882903/101237902-05f0a600-36e5-11eb-810d-39b93bc5999b.jpg)

**Comment by guymass** [comment]
Note that you Avideo Storage configuration screen image is missing from you git hub page.
![Uploading Screen Shot 5781-03-19 at 21.50.20.jpg…]()

**Comment by guymass** [comment]
So here is my main problem. In short I upload a video, than I set its storage location to the new storage1, I get an OK pop up indicating the file is being prepared for transfer. Once that is done, I cannot see realy anything else happening, I try to open the file url to view it and all I get is the error above in the browser. AVideo log shows :

![Screen Shot 5781-03-20 at 22 39 13](https://user-images.githubusercontent.com/58882903/101291774-e7d59380-3813-11eb-88f6-b8cd5b9be62f.jpg)

No point in trying to set the video storage back to local as now the file is rendered missing and I am not sure really what is going on because the YPTStorage videos folder remains always empty!

**Comment by guymass** [comment]
Hi Daniel,

Can you please respond to our issue with the storage plugin on this post. I
cannot seem to get it to work as expected and while everything seems to be
properly configured, files are being rendered broken and unviewable one
move to the new storage location. System is updated.

https://github.com/WWBN/AVideo/issues/4090

Regards,
Guy.

**Comment by guymass** [comment]
I have done that server install and still the plugin doesn't move the files properly and once I get this pop up
![Screen Shot 5781-03-20 at 23 35 03](https://user-images.githubusercontent.com/58882903/101293075-0b9cd780-381c-11eb-8c93-7e00540a4106.jpg)

The file is basically not playing any more, which means that any recording is lost.

**Comment by guymass** [comment]
![Screen Shot 5781-03-21 at 19 34 05](https://user-images.githubusercontent.com/58882903/101384533-3a21bd80-38c3-11eb-95aa-00cc24cae29d.jpg)

This error occures for every file I chose to transfer to the storage1 location. Any suggestions?

**Comment by guymass** [comment]
I have no idea why my installation which is just like you video doesn't work the same way like in your tutorial video:
https://tutorials.avideo.com/video/86/installing-yptstorage-and-configuring-the-yptstorage-plugin

**Comment by guymass** [comment]
Update Solution!

The problem I think was the way the secondary drive was mounted as the videos folder under AVideo-Storage/

I created a folder /media/storage1
and mounted /dev/sd? to it
Than I created a videos directory under storage1 and ran on it chown www-data:www-data -R
also chmod 644
Finally I created a symbolic link to it in AVideo-Storage
and it worked!
