### ISSUE TITLE
What Exactly Is The Difference in AVideo-Storage & YPTStorage

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4091]
The **YPTStorage** is a plugin that takes advantage of external storage servers ... that right?

From what I gather about **AVideo-Storage** is, it seems to be a "service" that also works with AVideo based websites. Is that correct?

Assuming that **AVideo-Storage** is a service, where can I find pricing for it?

I read from here, https://git-storage.avideo.tube the following:

> AVideo Simple Storage is a Storage Service for the AVideo Platform Instances.
> 
> It is designed to make web-scaleble storage.
> 
> ie with this service you will have unlimited storage capacity and low cost.
> 
> For example when one of your storage is full, just plug in one more storage and your videos will continue to be saved to the new storage.
> 
> This service is designed to replace our current S3, BackBlaze B2 and FTP plugins, but with much more integration with our services, besides you will have no restriction on the amount of storages used.
> 
> You can install as many storage nodes as you want, without any geographical restrictions.

It also says: 

> Minimal start up investment and cost

But it never mentions any sort of pricing ....

**Comment by DanielnetoDotCom** [comment]
Hi

I sent you an email with some server prices.

**Comment by bbyrdhouse** [comment]
Thank you
