### ISSUE TITLE
What Benefits or Drawbacks Might I See In Using AVideo-Encoder-Network over the Local AVideo/Encoder

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4092]
I am using AVEncoder on the local server where the AVideo script runs. So far it seems to do fine ... it actually does great for videos smaller than 200Mb ... reasonable time. On videos larger than 500Mb, encoding will naturally take a lot longer.

I've been reading about the AVideo-Encoder-Network here: https://github.com/WWBN/AVideo-Encoder-Network
and it looks really interesting.

It appears that it may benefit me by removing the burden of encoding on my server and sharing that burden across a public network of encoders ... but I might be completely reading it wrong.

Can anyone who is using the AVideo-Encoder-Network describe how it is better or worse than using the local encoder?

Thanks

**Comment by JoshWho** [comment]
Encoder network is designed to have multiple encoders to auto select from when uploading.

If you have a busy website it is nice to have more than 1 encoder so lost of people can  upload fast without waiting for a open cue.
