### ISSUE TITLE
Trying To Update youtube-dl and presented with this message ... 

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4093]
Trying to update the youtube-dl and am using this command:
`sudo pip install --upgrade youtube-dl`
When doing so I am presented with the following: 
`sudo: pip: command not found`

The reason I am updating the youtube.dl is because when I tried to inport a video from rumble I was presented a message telling me to update the youtube-dl (see image below)
<img width="480" alt="Screen Shot 2020-11-28 at 1 09 09 PM" src="https://user-images.githubusercontent.com/7376298/100524111-f15b5d80-317a-11eb-8ad7-5e58264e0bd3.png">

**Comment by TLCReuver** [comment]
Maybe 

https://www.xda-developers.com/youtube-dl-riaa-dmca/

Try google for solutions.

**Comment by bbyrdhouse** [comment]
Well, since I was using **AVideo** when the error message happened and since it was **AVideo** that told me to update youtube-dl and gave the the command to run that produced the error, then I thought I would come to the **AVideo** git to ask for help.

**Comment by JoshWho** [comment]
That message is just a generic default message for broken files. Youtube protects certain files from being downloaded with that script. 

Only major channels cause that error and sometimes restricted videos like age gate also can cause that error or if the yt channel is on a Network it will also cause that message.

**Comment by bbyrdhouse** [comment]
A Youtube file was not attempting to be downloaded ... it was a Rumble video.

**Comment by akhilleusuggo** [comment]
`sudo: pip: command not found` 

This error means you don't have python installed . What distro are you using ? And what version ? Try `pip3` 
`sudo pip3 install --upgrade youtube-dl`
