### ISSUE TITLE
Videos That Get Uploaded Using The Encoder Network Are Unplayable On My Site

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4094]
**Describe the bug**
Whenever a video is uploaded using the Encoder Network instead of the local AVideo/Encoder the resulting video is unplayable and an error is presented in the inspector.

**To Reproduce**
1. Go to 'https://thepatriot.network'
2. Add a video but select the Encoder network
3. Wait for the video to finish uploading and then be added to the site
4. Click on the video to play it and then try to play it and it just sits there ... 
5. Right click to open Dev Inspector tools to see the error
`VIDEOJS: – "ERROR:" – "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" – "No compatible source was found for this media."`

**Expected behavior**
The video should play

<img width="807" alt="Screen Shot 2020-11-28 at 6 37 38 PM" src="https://user-images.githubusercontent.com/7376298/100529134-dc49f300-31a9-11eb-8584-7c0d2ebae2b8.png">
<img width="1554" alt="Screen Shot 2020-11-28 at 6 38 01 PM" src="https://user-images.githubusercontent.com/7376298/100529135-e0761080-31a9-11eb-8e37-d6931e86682c.png">

NOTE: Until I can get this sorted, I have turned off the ability to use the encoder network

**Comment by JoshWho** [comment]
Does the video have its downloadable links in the Video List page?

**Comment by bbyrdhouse** [comment]
@JoshWho  

#1 - I can't answer that ow because I have deleted the videos because I was getting emails about them not playing

#2 - Yes

#3 - No. What folders need what permissions? 

Your #3 is a little confusing to me ... If I use the AV Encoder Network (not the one that is on my server) ... I will still need to change permissions on my server?

**Comment by DanielnetoDotCom** [comment]
Hi, @bbyrdhouse if you can leave a sample video that does not work on your site, will help us to detect the error.

you can make the video unlisted.

**Comment by bbyrdhouse** [comment]
@DanielnetoDotCom - I just uploaded this using the encoder network and it doesn't play (on Safari or Chrome) I don't know about other browsers or OS's.

https://thepatriot.network/video/162/sample-video-unlisted-using-encoder-network

**Comment by DanielnetoDotCom** [comment]
Hi, as I can see this video is not found and the file does not exist.
I also notice the avideo.log file does not have write permissions for www-data (apache user), so there is no record for what happened on the transfer, I cannot detect what was the issue.

![image](https://user-images.githubusercontent.com/18009293/100740419-703cda00-33b7-11eb-9a54-0775d06b6b2f.png)

I just changed the permission again in your server, please try to upload again and let me know the results.

**Comment by bbyrdhouse** [comment]
@DanielnetoDotCom - I just uploaded a video here: https://thepatriot.network/video/172/test
and it still doesn't play.

**Comment by DanielnetoDotCom** [comment]
I do not know what is going on.
To make more tests I need to update your site with the latest modifications
I tried to make a git pull and I could not update you due to multiple modified files

![image](https://user-images.githubusercontent.com/18009293/100766312-44c9e780-33d7-11eb-8b90-b354e5596a20.png)

Do you approve me overwriting them all?

**Comment by bbyrdhouse** [comment]
I've only over written 3 files and I have those changes saved here locally so I can go back and make them once you get done.
most all of those files in your image ... I've never touched, except to change permissions for many of them.

**Comment by DanielnetoDotCom** [comment]
I just update your site overwriting all the files (including permissions) and it works with a local video

https://thepatriot.network/video/175/youphptubeintro

please try again and let me know

**Comment by bbyrdhouse** [comment]
Seems to work now ... what was the problem you reckon?

**Comment by DanielnetoDotCom** [comment]
I am not sure if was an outdated file, or file permission, or the modification you have made.

I have made sure you have the latest version and now is working
