### ISSUE TITLE
Friendly URL for Live Links

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4095]
Currently all live links are not a real link but a query and certain scrappers and search bots do not understand how to view it properly.

For example this is one of my live 24/7 streams https://www.joshwhotv.com/plugin/LiveLinks/view/Live.php?link=34

Could this be made into a more friendly url like example: https://www.joshwhotv.com/LiveLinkName

**Comment by bbyrdhouse** [comment]
This would be a welcome addition

**Comment by DanielnetoDotCom** [comment]
This update should do the trick

**Comment by syldri** [comment]
it's much better, because live it's more readable



 
- I think the owner's name has no place on the video link

 https://demo.avideo.com/video/220/nextcloud?channelName=TheAdminChannel

- for videos it's better like that

https://demo.avideo.com/video/220/nextcloud

**Comment by DanielnetoDotCom** [comment]
On the demo site that is the new livelink URL 

https://demo.avideo.com/liveLink/1/American+Classic

**Comment by syldri** [comment]
Hello @DanielnetoDotCom   I'm not talking about the live links, I'm talking about the videos

when you click on a video , look where I put in red

i think it should be deleted and keep as the name of the video


![image](https://user-images.githubusercontent.com/39193219/100767046-97b49680-33f9-11eb-81b4-6c6ac97cb709.png)

**Comment by DanielnetoDotCom** [comment]
this is an option to keep the user on the same channel when he is watching your videos.

try to uncheck this

![image](https://user-images.githubusercontent.com/18009293/100768004-29f87280-33d9-11eb-8045-ddfb75296e4d.png)

**Comment by syldri** [comment]
I tested on my site and on the demo site, nothing changes, look at you

**Comment by syldri** [comment]
it's good everything works perfectly

**Comment by JoshWho** [comment]
@DanielnetoDotCom I want to run the update but worried if it will break my video links. I ran a update 4 days ago and none of my static.  video links were showing after that so I had to do a roll back. Was there any changes with that in the last 4 days?

**Comment by JoshWho** [comment]
All good now. Thank you @DanielnetoDotCom
