### ISSUE TITLE
follower button

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#4097]
Hello @DanielnetoDotCom  it's for when we can have, the follower button, and a page to find out how many followers we have with an API that goes with it

![image](https://user-images.githubusercontent.com/39193219/100548134-0a433c00-326b-11eb-87ec-c98ed661dcf2.png)

**Comment by DanielnetoDotCom** [comment]
Hi, what is the difference between subscribers and followers

**Comment by syldri** [comment]
In a way, this means that in a "subscription" dynamic, the one in control of the relationship is the one being subscribed to. Whereas when you follow something or someone, it's up to the follower to control the interaction and delivery of the content. Twitter for example has always called it Followers.

**Comment by DanielnetoDotCom** [comment]
hi, so basically they are the same thing, you just want to rename it?
