### ISSUE TITLE
two domains, two platforms on one server

### ISSUE THREAD

**Issue by kylemogli** [WWBN/AVideo#4100]
I am new in this space and I am not sure where my starting point is.

I have a dedicated server and a working Youphptube website/plateform purchased through the full pack pro package @DanielnetoDotCom . I have a domain and my Youphptube site is up and running. I have pointed a second domain to the same server and I want to get a Wordpress website also running off of the same server. I have been trying to achieve this with Filezilla but I am not succeeding. 

I have a Macbook (IOS) and I understand that this is going to be a long journey.

**Comment by DanielnetoDotCom** [comment]
Hi

for dedicated servers without a control panel, the best is to use the command line, but you can also use FileZilla as SFTP **(NOT FTP)**

On the SFTP use the same SSH credentials. keep in mind usually your SSH user is not root and cannot write in the /var/www/html folder, but you can upload what you want to your home folder and move it to the html folder.

`sudo mv /home/ubuntu/wordpress-folder /var/www/html/wp-site`

also you may need to create an apache vhost. Google is your friend on this, but here is a good start https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-18-04-quickstart

**Comment by JoshWho** [comment]
You have to create a virtual host directory for the domain. Ubuntu 18 uses Apache 2.4 which makes it a easier process than the old way. My advice is install Webmin and it makes it easy to create virtual hosts using that.

**Comment by kylemogli** [comment]
thanks for the tips. Im not winning. I have two domains but the only difference is the .com and .co.za (e.g example.com and example.co.za) could this be an issue? 

I have tried downloading putty, Webmin and Ubuntu software but I am still struggling to piece the puzzle together. FileZilla I have probably had the most success with but still I am not navigating my server, web pages and domains successfully. 

I am doing online courses and they are great for step by step progress. I will have to follow those and their recommended softwares and platforms and hopefully I can come back to my Youphptube services.
