### ISSUE TITLE
LDAP not authenticating 

### ISSUE THREAD

**Issue by veljkostanar** [WWBN/AVideo#4105]
I installed the ldap plugin but when i attempt to authenticate on the login screen nothing happens. 

the rdn i have is 'uid={$user},OU=Users,OU=NWSC,DC=narre-warren-south-p12,DC=edu,DC=vic,DC=gov,DC=au'

i checked the logs and i see this. 

[02-Dec-2020 14:33:25 Australia/Melbourne] PHP Fatal error:  Uncaught Error: Class 'AVideoPlugin' not found in /var/www/html/nws/plugin/LoginLDAP/view/loginForm.php(14) : eval()$
Stack trace:
#0 /var/www/html/nws/plugin/LoginLDAP/view/loginForm.php(14) : eval()'d code(1): eval()
#1 /var/www/html/nws/plugin/LoginLDAP/view/loginForm.php(14): eval()
#2 /var/www/html/nws/view/userLogin.php(86): include('/var/www/html/n...')
#3 /var/www/html/nws/view/user.php(89): include('/var/www/html/n...')
#4 {main}
  thrown in /var/www/html/nws/plugin/LoginLDAP/view/loginForm.php(14) : eval()'d code(1) : eval()'d code on line 2

even if i try locally created accounts i can't authenticate with ldap enabled

**Comment by DanielnetoDotCom** [comment]
Looks like you are using an old version

please update your AVideo

**Comment by veljkostanar** [comment]
I am running version 7.8
You are running YouPHPTube version 7.8

what version should i be running?

**Comment by veljkostanar** [comment]
Also i seem to have another complication when i copy the LoginLDAP folder into plugins all other plugins disappear on the pluginlist and some LDAP fields are uneditable 'Server' &  LDAP_OPT_PROTOCOL_VERSION
If i delete the folder all the plugins come back.

**Comment by DanielnetoDotCom** [comment]
We are in version 10.0

you must update with the git pull command

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by veljkostanar** [comment]
Thanks for that
i performed the update but now i have a new issue

I have a blank page and can't navigate anywhere 
The ribbon shows at the top but no buttons work and the main page is blank 

i think something is not pointing somewhere which error log should i be looking at to find more information?

**Comment by DanielnetoDotCom** [comment]
Please check this https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by veljkostanar** [comment]
Thanks for that 
i had a look at the two log files an i think i now have database issues. I'm getting allot of MySQL errors I'm at a lost on how to resolve them any ideas?

[uploader log.txt](https://github.com/WWBN/AVideo/files/5632839/uploader.log.txt)
[streamer log.txt](https://github.com/WWBN/AVideo/files/5632840/streamer.log.txt)

**Comment by DanielnetoDotCom** [comment]
Are you sure you have done the updates one by one?

look like you skipped some table updates. I have no idea how.

For example this 

`[03-Dec-2020 00:06:29 Africa/Abidjan] AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: (1054) Unknown column 'order' in 'order clause' (SELECT * FROM categories c WHERE 1=1 AND parentId = 0  ORDER BY `order`, name ASC  LIMIT 0, 1000 ) - format=() values=[] SCRIPT_NAME: /nws/view/index.php`

this table should come with the main installation.

the way you are showing me the logs, I recommend you to make a fresh installation.

Your installation looks like is not good.

**Comment by veljkostanar** [comment]
I've reinstalled the program, now the plugin works but i've reached a new hurdle. 

LDAP BIND fail: 49: Invalid credentials SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php
MY AD requires authentication, i don't see anything in the plugin i can enter user details. 
is there anywhere i can accommodate this?

**Comment by veljkostanar** [comment]
Hi i got ldap working 
I had to use a user account and not a binded service account for reasons that are beyond me one suggestion that might save time for people who are new or not experience system admin 

add this tip that you mentioned here . [https://github.com/WWBN/AVideo/issues/1239]

"Note there is a {$user} on the RDN string. This will be replaced with your typed username "

It will save allot of hours searching and trial and error.
