### ISSUE TITLE
Download the HLS videos

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#4108]
I know that this function does not exist. But maybe you can help me. Is there maybe a Java script with which the HLS pieces can be written back into a file.
I have seen there are innumerable open source projects with HLS and Javscript, but I think I don't know enough.
Do you have any suggestion what could be used?

best regards

**Comment by DanielnetoDotCom** [comment]
I do not think it is possible with JS.

**Comment by Donnerstein** [comment]
Well, I thought e.g. to hls.js here on github. It just needs to be written to a file. If you are looking for a solution with ffmpeg, then the users would have to wait until the file is created. In addition, this naturally consumes performance on the server. I think if you have a big site it can quickly cause problems. Imagine you have 10,000 users and 100 of them want to download a video. It would of course be very convenient if the user could select which one he wants to download for each HLS trigger. But keeping all videos as files uses too many resources.

I would prefer to use your own download server.
So if you were to install a corresponding script on your own server, which then downloads and converts the videos. Perhaps you could use a modified form of the encoder, or add a corresponding option to the encoder.
With a get instruction you could transfer the HLS list and the SEO URL as a file name. This download server could then keep the files for a certain period of time if they are downloaded again so that they do not have to be recreated as often. That would then also relieve the web server. But you shouldn't use youtube-dl for this, we don't know whether youtube-dl will come back.

**Comment by DanielnetoDotCom** [comment]
I guess it is possible if you keep the resolution and the codec.

It will not consume many resources.

If you are willing to pay I can build that

If you are interested email me at developer@youphptube.com

**Comment by Donnerstein** [comment]
ok, you have received an email

**Comment by DanielnetoDotCom** [comment]
Added new option to download

![image](https://user-images.githubusercontent.com/18009293/101660270-bfbd7e80-3a25-11eb-8838-9f6e2db54a90.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Hello daniel . I haven't tested it yet ( I'm a bit away this last days ) . But I see you're using the same example as in out last discoussion .

Remember to change the installation method on AVideo-Storage page . You will need to add ffmpeg to the packages list to be installed , or this is not gonna work . ( basically ffmpeg is now needed for every project , except network-encoder , and I believe is just for now, before something new comes in )

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I know , I meant that you need to update this ; https://github.com/WWBN/AVideo-Storage#ubuntu-1604

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I'm not using this feature , but I tested it on the old streams stored on HLS , and it doesn't work .

**Comment by DanielnetoDotCom** [comment]
Hi, 

you need FFMPEG and [XSendFIle](https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle) properly configured.

**Comment by akhilleusuggo** [comment]
I see . I'll try it and leave a feedback . My question is , why are we targeting the root directory ? Why not 
`XSendFilePath /var/www/html/YouPHPTube/videos`

**Comment by akhilleusuggo** [comment]
idk , HTTP ERROR 500

```
[Tue Dec 15 13:31:33.066022 2020] [:error] [pid 4847] [client IP] PHP Fatal error:  Uncaught Error: Call to undefined function _error_log() in /var/www/html/AVideo-Storage/functions.php:434\nStack trace:\n#0 /var/www/html/AVideo-Storage/xsendfile.php(49): downloadHLS('/var/www/html/A...')\n#1 {main}\n  thrown in /var/www/html/AVideo-Storage/functions.php on line 434, referer: https://www.example.com/
[Tue Dec 15 13:31:33.255275 2020] [:error] [pid 1462] [client IP] Storage xsendfile https://www.example.com/plugin/YPTStorage/canWatchVideo.json.php?token=0&filename=title_YPTuniqid_5f6f72e62acfb7.25958298 => {"authorization":true,"msg":"SecureVideosDirectory NOT enabled"}, referer: https://www.example.com/
[Tue Dec 15 13:31:33.964427 2020] [:error] [pid 1462] [client IP] PHP Fatal error:  Uncaught Error: Call to undefined function _error_log() in /var/www/html/AVideo-Storage/functions.php:434\nStack trace:\n#0 /var/www/html/AVideo-Storage/xsendfile.php(49): downloadHLS('/var/www/html/A...')\n#1 {main}\n  thrown in /var/www/html/AVideo-Storage/functions.php on line 434, referer: https://www.example.com/
[Tue Dec 15 13:33:05.024124 2020] [:error] [pid 773] [client IP] Storage xsendfile https://www.example.com/plugin/YPTStorage/canWatchVideo.json.php?token=0&filename=title_YPTuniqid_5f6f72e62acfb7.25958298 => {"authorization":true,"msg":"SecureVideosDirectory NOT enabled"}
[Tue Dec 15 13:33:05.712751 2020] [:error] [pid 773] [client IP] PHP Fatal error:  Uncaught Error: Call to undefined function _error_log() in /var/www/html/AVideo-Storage/functions.php:434\nStack trace:\n#0 /var/www/html/AVideo-Storage/xsendfile.php(49): downloadHLS('/var/www/html/A...')\n#1 {main}\n  thrown in /var/www/html/AVideo-Storage/functions.php on line 434
[Tue Dec 15 13:33:12.878365 2020] [:error] [pid 774] [client IP] Storage xsendfile https://www.example.com/plugin/YPTStorage/canWatchVideo.json.php?token=0&filename=title_YPTuniqid_5f6f625d0696b7.96502037 => {"authorization":true,"msg":"SecureVideosDirectory NOT enabled"}, referer: https://www.example.com/
[Tue Dec 15 13:33:13.671850 2020] [:error] [pid 774] [client IP] PHP Fatal error:  Uncaught Error: Call to undefined function _error_log() in /var/www/html/AVideo-Storage/functions.php:434\nStack trace:\n#0 /var/www/html/AVideo-Storage/xsendfile.php(49): downloadHLS('/var/www/html/A...')\n#1 {main}\n  thrown in /var/www/html/AVideo-Storage/functions.php on line 434, referer: https://www.example.com/

```

**Comment by DanielnetoDotCom** [comment]
thanks for noticing this error, here is a fix

please update and try again, and check your logs

**Comment by akhilleusuggo** [comment]
What I can see now , is that you added an option for each quality . But when downloading , does download the index.m3u8 , not the mp4 .

![image](https://user-images.githubusercontent.com/52116577/102318659-5e942e80-3f82-11eb-87a1-c453144edc59.png)

![image](https://user-images.githubusercontent.com/52116577/102318740-7e2b5700-3f82-11eb-9ed3-f97c66d70c09.png)

**Comment by akhilleusuggo** [comment]
I've sent a fix , and now works ( at the least the process to download from storage AVideo )
But is not all fixed . All those HLS to MP4 on the pictures above doesn't work . Only the first one does work . When clicking it , does create a mp4 

![image](https://user-images.githubusercontent.com/52116577/102320730-61dce980-3f85-11eb-9e33-33a2501d7b10.png)

**Comment by DanielnetoDotCom** [comment]
Hi, the links on the videos manager are correct.

the m3u8 link is used for those who want to grab the m3u8 link and use it somewhere else, on an external player or livelinks for example.

the HLS => MP4 is the download link.

I understand it is confused, I will work on something to improve the usability and update it soon

**Comment by DanielnetoDotCom** [comment]
I guess it is better now

![image](https://user-images.githubusercontent.com/18009293/102509815-bce60d80-4065-11eb-8472-324a23df7ecb.png)

**Comment by akhilleusuggo** [comment]
Yes , thanks for the update . But this ones are still not working .

![image](https://user-images.githubusercontent.com/52116577/102520862-d787a900-409c-11eb-9432-9e2bf63941af.png)

What the script should do ( or suppose to ) grab the hls that correspond to the directory , and create the mp4 .

Example is it's 360 , then the ffmpeg converter line should looks like this , `ffmpeg -allowed_extensions ALL -y -i https://www.example.com/videos/video_title/res360/index.m3u8 -c:v copy -c:a copy -bsf:a aac_adtstoasc -strict -2 {$outputpath}";`

the {$filepath} , should consider all the directories .
Also , when downloading , doesn't respect the file name .

**Comment by DanielnetoDotCom** [comment]
why this is required?

`-bsf:a aac_adtstoasc -strict -2`

this will not slow down the conversion?

**Comment by akhilleusuggo** [comment]
Without it you can not transmux hls into mp4 ( and no , doesn't slow down ) . FFmpeg calls it a experimental fix . If you don't add those flags , you will get an error ( try it )

**Comment by DanielnetoDotCom** [comment]
Hi, I will add the` -bsf:a aac_adtstoasc -strict -2` option soon.

regarding the quality, we already have a quality selector on the download menu

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Hello .

I don't think you have added this option . ( at the least not working with AVideo-Storage ) .
I hope you have read the video mapping that I've explained above with examples .

When I try to download for example the quality 360p , it does download only the index.m3u8 , not the mp4 converted .

PS : I have just updated , and I can't see anymore the download 

![image](https://user-images.githubusercontent.com/52116577/102839691-c080e800-4409-11eb-91bc-6a3d1414631d.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, I am sending the Storage Update soon

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Could you please read the last commend that I have added ?
Also could you please take a look at what I have explained to you here ? 



> Without it you can not transmux hls into mp4 ( and no , doesn't slow down ) . FFmpeg calls it a experimental fix . If you don't add those flags , you will get an error ( try it )
> 
> EDIT : It will not slow down , because we're actually making a `-c:v copy` and `-c:a copy` , but making ffmpeg understand that we're demuxing different formats with the same ( compatible codec ) , and no transcoding is required .
> 
> EDIT2: So , Daniel ( I know you're good on php ) , but if you don't wanna mess things up and complicate , we can use a different way to generate those videos ; Mapping . Giving you one example ;
> 
> Your index.m3u8 video : https://demo.avideo.com/videos/_YPTuniqid_5d9378f639c875.77047133/index.m3u8?token=eyJzYWx0IjoiaHR0cHM6XC9cL2RlbW8ueW91cGhwdHViZS5jb21cLyIsInRva2VuVGltZU91dCI6IjIxNjAwIiwiZmlsZW5hbWUiOiJfWVBUdW5pcWlkXzVkOTM3OGY2MzljODc1Ljc3MDQ3MTMzIiwidGltZSI6MTYwODMxMDM5NX0=
> 
> This one is global ( the quality will be automatic depending on the program playlist bandwidth ) . since we're downloading locally , will always select the higher .
> 
> mapping ; `-map 0:p:1` ; where `-p` is the playlist ( program ) number ;
> 
> ![image](https://user-images.githubusercontent.com/52116577/102641239-6b707800-4164-11eb-82a5-a8f7397fb2f5.png)
> 
> Now let's try to download another quality that is not the highest ( or default ) .
> 
> If you execute this command line ( on the terminal ) , you should be able to download ONLY the quality Low :
> 
> `ffmpeg -i https://demo.avideo.com/videos/_YPTuniqid_5d9378f639c875.77047133/index.m3u8?token=eyJzYWx0IjoiaHR0cHM6XC9cL2RlbW8ueW91cGhwdHViZS5jb21cLyIsInRva2VuVGltZU91dCI6IjIxNjAwIiwiZmlsZW5hbWUiOiJfWVBUdW5pcWlkXzVkOTM3OGY2MzljODc1Ljc3MDQ3MTMzIiwidGltZSI6MTYwODMxMDM5NX0= -c:v copy -c:a copy -map 0:p:0 -bsf:a aac_adtstoasc -strict -2 test_low.mp4`
> 
> So , only the `-p` is needed for change the quality selector downloader .
> 
> For Low,SD,HD , `-p` would be 0,1,2 respectively .
> For 240,360,480,720,1080,1440,2160 , `-p` would be 0,1,2,3,4,5,6 respectively .
> 
> This is really the easiest way , without having to change much on the code .
> I've made a commit like this one before , to speed-up thumbnails creation and save resources .
> [WWBN/AVideo-Encoder@53b56c8](https://github.com/WWBN/AVideo-Encoder/commit/53b56c8cd2c6a2fc032a8d8829e775da822bd80d) , mapping to 0 to select the lowest quality , and it works !

**Comment by DanielnetoDotCom** [comment]
> @DanielnetoDotCom Could you please read the last commend that I have added ?
> Also could you please take a look at what I have explained to you here ?
> 
> > Without it you can not transmux hls into mp4 ( and no , doesn't slow down ) . FFmpeg calls it a experimental fix . If you don't add those flags , you will get an error ( try it )
> > EDIT : It will not slow down , because we're actually making a `-c:v copy` and `-c:a copy` , but making ffmpeg understand that we're demuxing different formats with the same ( compatible codec ) , and no transcoding is required .

the `copy -bsf:a aac_adtstoasc -strict -2` is already added on streamer and storage.
make sure you use git pull

> > EDIT2: So , Daniel ( I know you're good on php ) , but if you don't wanna mess things up and complicate , we can use a different way to generate those videos ; Mapping . Giving you one example ;
> > Your index.m3u8 video : https://demo.avideo.com/videos/_YPTuniqid_5d9378f639c875.77047133/index.m3u8?token=eyJzYWx0IjoiaHR0cHM6XC9cL2RlbW8ueW91cGhwdHViZS5jb21cLyIsInRva2VuVGltZU91dCI6IjIxNjAwIiwiZmlsZW5hbWUiOiJfWVBUdW5pcWlkXzVkOTM3OGY2MzljODc1Ljc3MDQ3MTMzIiwidGltZSI6MTYwODMxMDM5NX0=
> > This one is global ( the quality will be automatic depending on the program playlist bandwidth ) . since we're downloading locally , will always select the higher .
> > mapping ; `-map 0:p:1` ; where `-p` is the playlist ( program ) number ;
> > ![image](https://user-images.githubusercontent.com/52116577/102641239-6b707800-4164-11eb-82a5-a8f7397fb2f5.png)
> > Now let's try to download another quality that is not the highest ( or default ) .
> > If you execute this command line ( on the terminal ) , you should be able to download ONLY the quality Low :
> > `ffmpeg -i https://demo.avideo.com/videos/_YPTuniqid_5d9378f639c875.77047133/index.m3u8?token=eyJzYWx0IjoiaHR0cHM6XC9cL2RlbW8ueW91cGhwdHViZS5jb21cLyIsInRva2VuVGltZU91dCI6IjIxNjAwIiwiZmlsZW5hbWUiOiJfWVBUdW5pcWlkXzVkOTM3OGY2MzljODc1Ljc3MDQ3MTMzIiwidGltZSI6MTYwODMxMDM5NX0= -c:v copy -c:a copy -map 0:p:0 -bsf:a aac_adtstoasc -strict -2 test_low.mp4`
> > So , only the `-p` is needed for change the quality selector downloader .
> > For Low,SD,HD , `-p` would be 0,1,2 respectively .
> > For 240,360,480,720,1080,1440,2160 , `-p` would be 0,1,2,3,4,5,6 respectively .
> > This is really the easiest way , without having to change much on the code .
> > I've made a commit like this one before , to speed-up thumbnails creation and save resources .
> > [WWBN/AVideo-Encoder@53b56c8](https://github.com/WWBN/AVideo-Encoder/commit/53b56c8cd2c6a2fc032a8d8829e775da822bd80d) , mapping to 0 to select the lowest quality , and it works !

I understand but there is no need for that as long as you can directly click on the resolution you want to download.

![image](https://user-images.githubusercontent.com/18009293/103230122-6903e000-4913-11eb-8794-8fa02f679519.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom None of them works ...

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo I found the problem with the storage.

Please update the storage and streamer and you should be fine

**Comment by akhilleusuggo** [comment]
I had to rollback the update , because server is goin crazy .....

```
[29-Dec-2020 00:10:32 Europe/Kiev] PHP Warning:  feof() expects parameter 1 to be resource, bool given in /var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(14) : eval()'d code(1) : eval()'d code on line 244
[29-Dec-2020 00:10:32 Europe/Kiev] PHP Warning:  fgets() expects parameter 1 to be resource, bool given in /var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(14) : eval()'d code(1) : eval()'d code on line 245
[29-Dec-2020 00:10:32 Europe/Kiev] PHP Warning:  feof() expects parameter 1 to be resource, bool given in /var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(14) : eval()'d code(1) : eval()'d code on line 244
[29-Dec-2020 00:10:32 Europe/Kiev] PHP Warning:  fgets() expects parameter 1 to be resource, bool given in /var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(14) : eval()'d code(1) : eval()'d code on line 245
[29-Dec-2020 00:10:32 Europe/Kiev] PHP Warning:  feof() expects parameter 1 to be resource, bool given in /var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(14) : eval()'d code(1) : eval()'d code on line 244
[29-Dec-2020 00:10:32 Europe/Kiev] PHP Warning:  fgets() expects parameter 1 to be resource, bool given in /var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(14) : eval()'d code(1) : eval()'d code on line 245
[29-Dec-2020 00:10:32 Europe/Kiev] PHP Warning:  feof() expects parameter 1 to be resource, bool given in /var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(14) : eval()'d code(1) : eval()'d code on line 244
[29-Dec-2020 00:10:32 Europe/Kiev] PHP Warning:  fgets() expects parameter 1 to be resource, bool given in /var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(14) : eval()'d code(1) : eval()'d code on line 245
[29-Dec-2020 00:10:32 Europe/Kiev] PHP Warning:  feof() expects parameter 1 to be resource, bool given in /var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(14) : eval()'d code(1) : eval()'d code on line 244
[29-Dec-2020 00:10:32 Europe/Kiev] PHP Warning:  fgets() expects parameter 1 to be resource, bool given in /var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(14) : eval()'d code(1) : eval()'d code on line 245
[29-Dec-2020 00:10:32 Europe/Kiev] PHP Warning:  feof() expects parameter 1 to be resource, bool given in /var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(14) : eval()'d code(1) : eval()'d code on line 244
[29-Dec-2020 00:10:32 Europe/Kiev] PHP Warning:  fgets() expects parameter 1 to be resource, bool given in /var/www/html/AVideo/plugin/VideoHLS/VideoHLS.php(14) : eval()'d code(1) : eval()'d code on line 245
```

the disk is going a full speed write or errors .

**Comment by DanielnetoDotCom** [comment]
I just sent an update to the VIdeoHLS plugin v3.8

I guess for some reason your m3u8 file was not readable or does not exists.

if the error persists, uncheck the option returnAllSources on the plugin parameters

**Comment by akhilleusuggo** [comment]
same error ... but god sake , that option of "returnAllSources" is the only reason I went back to use HLS

**Comment by akhilleusuggo** [comment]
and now no video is working at all . return error 404 ( m3u8 ) and 500 (mp4 )

**Comment by DanielnetoDotCom** [comment]
did you update the Storage as well?

**Comment by akhilleusuggo** [comment]
yes I did.

**Comment by DanielnetoDotCom** [comment]
I cannot check now, but if you can send me a link so I can inspect and see what is going on.

regarding the error 500 what is the log for that?

**Comment by akhilleusuggo** [comment]
I fixed it . And yes, I found the issue on .htaccess ( only for me ) . Look like you changed something on the htaccess and broke something .

Just the "returnAllSources" to fix . When enabled , throws those lines . I hope you can fix it when you got the time .

**Comment by akhilleusuggo** [comment]
and btw , the issue is not fixed from https://github.com/WWBN/AVideo/issues/4237

![image](https://user-images.githubusercontent.com/52116577/103250901-efa1d700-497e-11eb-9d69-0d69230d02a6.png)

**Comment by akhilleusuggo** [comment]
Idk man , on the demo site is working . But it doesn't on my site . Maybe you added something on the advanced customize or something .

**Comment by akhilleusuggo** [comment]
For me looks like we're running the same version . Many missing things . Example . I'll not update for now , until it's fixed .
![image](https://user-images.githubusercontent.com/52116577/103251089-dea59580-497f-11eb-8ff0-21d3ce680dda.png)

**Comment by DanielnetoDotCom** [comment]
I sent some updates to the YPTStorage plugin and server

**Comment by elias2k1** [comment]
I am not seeing any download option in video manager in Ubuntu Server which I installed yesterday. But Video download options available on CentOS server which I installed a month earlier. 
![Video Download](https://user-images.githubusercontent.com/75417257/103279639-6c24cc00-49f8-11eb-9990-f33f5827add4.JPG)
![Video Download Issue Ubuntu](https://user-images.githubusercontent.com/75417257/103279642-6d55f900-49f8-11eb-8f12-90adc639b568.JPG)

**Comment by DanielnetoDotCom** [comment]
This new update will give you a button on the videos manager that will tell you why you cannot download the file 

![image](https://user-images.githubusercontent.com/18009293/103296693-581ba300-49d5-11eb-8567-7eb9d44f766f.png)

**Comment by Donnerstein** [comment]
I installed the git pull update today. Now the download button under the videos is gone again.
The download buttons work in the video management. But the button isn't under the videos.

In addition, I can no longer log into the memory and the videos on the memory cannot be called up.

![image](https://user-images.githubusercontent.com/52116237/103426996-ef434f00-4bbd-11eb-8772-300078b99c20.png)

![image](https://user-images.githubusercontent.com/52116237/103426999-fa967a80-4bbd-11eb-998f-bf234219339f.png)

The memory shows 404. and nginx?
But this is an Apache server!

**Comment by DanielnetoDotCom** [comment]
Why Nginx not apache?

is it the Streamer or the storage?

I guess it has nothing to do with the git pull but with your webserver

**Comment by Donnerstein** [comment]
It's the memory.

Well, it worked until I did git pull on the storage and streamer.

The memory is an Apache2 server, so I was very surprised at this message.

**Comment by Donnerstein** [comment]
But I think that's another problem, the download button has also disappeared with the videos that are saved locally.

**Comment by DanielnetoDotCom** [comment]
make sure your plugins are also up to date

check the logs

**Comment by akhilleusuggo** [comment]
@Donnerstein did you tried this params ?

![image](https://user-images.githubusercontent.com/52116577/103430757-f70bef00-4bcf-11eb-8f1f-d2bdff48aef0.png)

**Comment by Donnerstein** [comment]
Es wird für keine Option angezeigt, selbst wenn Sie den Bilddownload im erweiterten Plugin aktivieren.

**Comment by Donnerstein** [comment]
There is nothing in the log

![image](https://user-images.githubusercontent.com/52116237/103432655-13fded80-4be3-11eb-9d9b-8b5d1ea1edb7.png)

**Comment by akhilleusuggo** [comment]
I believe you're right , I can't make it work ( to show the download at the bottom of the video )

**Comment by akhilleusuggo** [comment]
Actually I'm not sure if it works or not , but I believe , will need a lot of time to make sure work or not . When I enabled it , this is the output I'm getting ; 


```
[01-Jan-2021 09:03:33 Europe/Kiev] AVideoLog::DEBUG: getSourceFile /var/www/html/AVideo/videos/_ID_....39545/index.m3u8 SCRIPT_NAME: /view/index.php
[01-Jan-2021 09:03:33 Europe/Kiev] AVideoLog::DEBUG: getSourceFile /var/www/html/AVideo/videos/_ID_....39545/index.m3u8 SCRIPT_NAME: /view/index.php
[01-Jan-2021 09:03:34 Europe/Kiev] AVideoLog::DEBUG: getSourceFile /var/www/html/AVideo/videos/_ID_....39545/index.m3u8 SCRIPT_NAME: /view/index.php
[01-Jan-2021 09:03:35 Europe/Kiev] AVideoLog::DEBUG: getSourceFile /var/www/html/AVideo/videos/_ID_....39545/index.m3u8 SCRIPT_NAME: /view/index.php
[01-Jan-2021 09:03:35 Europe/Kiev] AVideoLog::DEBUG: getSourceFile /var/www/html/AVideo/videos/_ID_....39545/index.m3u8 SCRIPT_NAME: /view/index.php
[01-Jan-2021 09:03:35 Europe/Kiev] AVideoLog::DEBUG: getSourceFile /var/www/html/AVideo/videos/_ID_....39545/index.m3u8 SCRIPT_NAME: /view/index.php
[01-Jan-2021 09:03:36 Europe/Kiev] AVideoLog::DEBUG: getSourceFile /var/www/html/AVideo/videos/_ID_....39545/index.m3u8 SCRIPT_NAME: /view/index.php

```

**Comment by Donnerstein** [comment]
I have deactivated DEBUG in the conf file, I don't need it if everything works. Otherwise the log file will be large.

I had 22 days ago. The last update was installed. After asking Daniel with the HLS download function.
Everything worked, including the download from the storage. On the storage I only had mp4 files.
However, I had to deactivate the tokens in the SecureVideosDirectory plugin in order to be able to download the HLS videos, because the download would otherwise be canceled after a few minutes. That wasn't a problem for me. Maybe this information can help.

I have listened to this discussion here. A lot has changed since then and so I wanted to be up to date. The download function is important to me. The HLS videos can be downloaded in the video management. I have activated the video downloads in general.
The functions UserCanAllow .. I don't need any of them.


Can't I just change something in ModeYoutubeButton.php so that the download option is always displayed. I don't have any Zip, JPG or PDF files and I don't use Articles either, only videos mp4 and HLS.

Unfortunately I understand too few of them. But maybe you can tell me what I just have to change for myself.

I discovered another error in the log file since this morning, but I don't think it has anything to do with this problem.
![image](https://user-images.githubusercontent.com/52116237/103438058-f22a5800-4c2e-11eb-9192-471fd525f16e.png)

**Comment by Donnerstein** [comment]
@DanielnetoDotCom 
![image](https://user-images.githubusercontent.com/52116237/103438386-11c37f80-4c33-11eb-81e7-c534fe4df278.png)

I think there is a typo in the path

**Comment by Donnerstein** [comment]
I changed the folder name. the e-mails arrive. But this error message occurs.

![image](https://user-images.githubusercontent.com/52116237/103439843-bef0c480-4c40-11eb-9bc5-0d8e4c3d8d65.png)

**Comment by DanielnetoDotCom** [comment]
Hi, the PHPMailer was just fixed.

regarding the download, I have no clue why you cannot see the button, you need [this update](https://github.com/WWBN/AVideo/issues/4108#issuecomment-752133978) to tell you why there is no button

**Comment by Donnerstein** [comment]
I have all the updates. On the /mvideos page, the buttons will appear and the download will also work.

Just not under the videos. Neither with HLS nor with MP4

![image](https://user-images.githubusercontent.com/52116237/103445172-4eae6700-4c71-11eb-835f-48ea8605c23d.png)

![image](https://user-images.githubusercontent.com/52116237/103445177-5bcb5600-4c71-11eb-81ed-2dee9c7dfc65.png)

**Comment by Donnerstein** [comment]
I also found the problem with the storage.
The variables have changed but the configuration file has not been adapted.

![image](https://user-images.githubusercontent.com/52116237/103446606-d2704f80-4c81-11eb-9e69-df35ab168a8e.png)

![image](https://user-images.githubusercontent.com/52116237/103446704-e8cadb00-4c82-11eb-9928-8f7faecad6bd.png)

**Comment by DanielnetoDotCom** [comment]
humm, I see, sorry about that, looks like we made a replacement and I didn't realize that.

could you fix the issue updating the variables name?

**Comment by Donnerstein** [comment]
Yes, I changed the variables in the conf file. so it works again.

**Comment by Donnerstein** [comment]
Regarding the download function.
I think there is a problem with the function "nonAdminCannotDownload"

For testing purposes, I switched off the download function on the whole site to see this tool. As can be seen in the picture. It says "Options" are in the way of downloading. As I said, I stopped the first one. But I have not activated the "nonAdminCannotDownload", but it is still said there.

![image](https://user-images.githubusercontent.com/52116237/103461690-87594980-4d20-11eb-8652-f56a9e3616db.png)


![image](https://user-images.githubusercontent.com/52116237/103461701-9a6c1980-4d20-11eb-9478-d369a03216ac.png)

**Comment by Donnerstein** [comment]
If I activate "nonAdminCannotDownload" and allow the download on the page.
Downloading doesn't work for admins either. Instead, this no longer appears.

![image](https://user-images.githubusercontent.com/52116237/103461819-6f35fa00-4d21-11eb-9b45-ce171ff93c32.png)

![image](https://user-images.githubusercontent.com/52116237/103461831-7e1cac80-4d21-11eb-8893-3abc640eca85.png)

**Comment by Donnerstein** [comment]
If you are not logged in as an admin. However, the download is not possible. Which is actually correct if the option "nonAdminCannotDownload" is active. However, the tool shows that non-admin can download.

![image](https://user-images.githubusercontent.com/52116237/103462046-dc965a80-4d22-11eb-82e7-383099cba8c7.png)

**Comment by akhilleusuggo** [comment]
Yes , go to this Site Configuration and enable ''Allow download video'' ; 

![image](https://user-images.githubusercontent.com/52116577/103467456-ea1a0780-4d57-11eb-9978-e5f87cf14f97.png)

And yes , I agree with you . Non admin users shouldn't see this message . Only admin should be able to see it . Non admin should see only '' You're not allowed to download this video "

**Comment by Donnerstein** [comment]
Yes, I understood that. I only switched off to see the tool in the video management. When I activate it. Then I can download the videos in the video management, but the download button is still not displayed under the videos, not for users and not for administrators.

I now have the following configuration.

![image](https://user-images.githubusercontent.com/52116237/103469882-fd829e00-4d6a-11eb-8e4c-0140ad2b9ce2.png)

![image](https://user-images.githubusercontent.com/52116237/103469885-05424280-4d6b-11eb-9d05-ef586321a9eb.png)


Then it looks like this in the video management for administrators and users.

![image](https://user-images.githubusercontent.com/52116237/103469898-2dca3c80-4d6b-11eb-821b-d69d492c15ef.png)

Downloading works here too. But it is not shown on the videos. I suspected that there was a connection. Because even the administrator in the video management cannot download even if "nonAdminCannotDownload" is activated.

So if "nonAdminCannotDownload" is activated, the administrator cannot download in the video management and the tool will be displayed instead.

but if "nonAdminCannotDownload" is deactivated, everyone in the video management can download.

But never on the videos.

**Comment by Donnerstein** [comment]
It's the same on the demo side. It can be downloaded in the video management but not in the videos.
I cannot test the "nonAdminCannotDownload" option on the demo page. The setting is not saved. '

But even on the demo page I didn't get the download button activated. The function "showImageDownloadOption" does not work either

![image](https://user-images.githubusercontent.com/52116237/103470041-53584580-4d6d-11eb-87cc-eb71da470db1.png)

![image](https://user-images.githubusercontent.com/52116237/103470044-5eab7100-4d6d-11eb-93a2-6503eaa0feaf.png)

**Comment by akhilleusuggo** [comment]
Yes , you're right . It's bugged

**Comment by DanielnetoDotCom** [comment]
I see you are talking about the video page download, not the video manager

I found an error on the checker, can you please check again?

Also I keep the check button so you can check when the user did not enable the download 

![image](https://user-images.githubusercontent.com/18009293/103540383-5ee46300-4e78-11eb-8ef6-da1daeef1d5a.png)

**Comment by Donnerstein** [comment]
Yes, it works again now.

Many Thanks.

**Comment by Donnerstein** [comment]
Sorry to have to open it again.

The change you have made has resulted in the videos no longer playing on Firefox.
Download yes, play no.

But it works with Goggle Chrome, for example.

![image](https://user-images.githubusercontent.com/52116237/103652513-82380c80-4f63-11eb-937e-8306d0bc7932.png)

**Comment by Donnerstein** [comment]
Sorry to have to open it again.

The change you have made has resulted in the videos no longer playing on Firefox.
Download yes, play no.

But it works with Goggle Chrome, for example.

![image](https://user-images.githubusercontent.com/52116237/103652513-82380c80-4f63-11eb-937e-8306d0bc7932.png)

**Comment by DanielnetoDotCom** [comment]
Error 500 MUST be something in your log file. I do not think has anything to do with the browser

**Comment by Donnerstein** [comment]
The problem exists with Firefox but not with Chrome e.g. and it only occurred after yesterday's update.

The subdirectory /res1080/index.m3u8 is missing from the Videourl

The memory is referenced in the log file. but it affects videos that are local

![image](https://user-images.githubusercontent.com/52116237/103661779-63d80e00-4f6f-11eb-8ec6-cf9b15f78667.png)

**Comment by DanielnetoDotCom** [comment]
It is probably cached on chrome, that is why you do not see the error.

Please update your YPTStorage plugin

**Comment by Donnerstein** [comment]
Yes ok thanks. With the update of the plugin the problem is gone.
