### ISSUE TITLE
Are Other People Using The Encoder on My Server?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4110]
**Describe the question**
This morning I decide to upload yesterday's program to my AV site ... I uploaded a file (1.6Gb) and then it started encoding. I go make a cup of coffee and come back to see that there are four other videos being "imported" but they are not going to my site but to a site called "**training.irmflorida.com**"

My question is, are other people using the resources of my server to encode their videos and then send them to their site?

**Screenshots**
<img width="638" alt="encode1" src="https://user-images.githubusercontent.com/7376298/100882972-65e11580-3475-11eb-981d-9ad6673f996c.png">
<img width="1484" alt="encode5" src="https://user-images.githubusercontent.com/7376298/100883449-f6b7f100-3475-11eb-8850-f170d158a929.png">

<img width="989" alt="encode3" src="https://user-images.githubusercontent.com/7376298/100883005-6f6a7d80-3475-11eb-826a-6e9f43a08bba.png">

**Comment by antuk21** [comment]
Is a demo encoder you need to driect the encoder to your site so  EXSAMPLE > https://prnt.sc/vuffc0
and check this spot to and do the same  in this section 2  https://prnt.sc/vufhln

**Comment by DanielnetoDotCom** [comment]
@bbyrdhouse looks like you are using the public encoder, NOT your built-in encoder.

If you use the public you will see other sites tasks
