### ISSUE TITLE
rtsp Ip Camera Streming?

### ISSUE THREAD

**Issue by mikweb2017** [WWBN/AVideo#4111]
is it possible to somehow implement live stremig of an ip camera through the protokolle rtsp?

**Comment by akhilleusuggo** [comment]
I believe you will need to replace nginx with some other open source . Take a look here , http://www.live555.com/

Source : https://stackoverflow.com/questions/4544157/what-alternatives-do-i-have-for-open-source-rtsp-streaming-player
