### ISSUE TITLE
Ad_Server ... Is There A Place That Serves These Ads?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4112]
**Describe the question**
Forgive my ignorance on this topic. The Ad_Server plugin is really a great plugin that I'd like to take advantage of but am not sure where to go to get ads that would work with this platform.

The Ad_Server basically work similar to Youtube where there is an ad that plays at the beginning, ending, and places in-between ... 
I realize that you don't get rich by playing ads on a niche site, but it would be nice to help offset recurring costs.
Does anyone have recommendations of places that will have video ads that will work with this platform?

**Screenshots**
<img width="693" alt="Screen Shot 2020-12-02 at 4 00 46 PM" src="https://user-images.githubusercontent.com/7376298/100936854-bf6a3400-34b7-11eb-8bde-081ed184009e.png">
<img width="595" alt="ad_server" src="https://user-images.githubusercontent.com/7376298/100936861-c1cc8e00-34b7-11eb-9df4-cea35c1cf3ef.png">

**Comment by palich91** [comment]
I am also wondering which ad company is providing this as Google Adsense does not currently provide it.
I found such a service https://videonow.ru, but my site was not moderated.
Who can recommend other similar services for site monetization

**Comment by DanielnetoDotCom** [comment]
[AD_Server](https://github.com/WWBN/AVideo/wiki/Ad-Server-Plugin) you will host and play your own ads, you will not be connected to a company.

If you want to play videos from an AD company you will need the [GoogleAds_IMA](https://github.com/WWBN/AVideo/wiki/Plugin:-GoogleAds_IMA---Videos-Ads-on-your-page), this plugin works with any VAST company

Regarding companies, I found [this link](https://www.adglare.com/top-ad-server-list), maybe it helps

**Comment by bbyrdhouse** [comment]
Thank you @DanielnetoDotCom ... that is helpful :)

**Comment by techiesces** [comment]
My thought, and I could be wrong, but it is what I am working on building is using REVIVE AD SERVER on my other server so that I can sell advertising to companies and then push them to the video site and my other sites I run.  I believe I can incorporate Revive into the YPT server.

**Comment by mrgodgiven** [comment]
I know how to create Like Google to pop up on your website. but you must have atleast ads or websites that you would like to advertise on your website. visit https://live.meetmycraft.com to check it out. Can Charge you $5 per ad once off

**Comment by techiesces** [comment]
@DanielnetoDotCom  Can you sell ads directly from Ad_Server somehow or do I have to use GoogleAds_IMA and my own ad server to do this?  Just curious, because if I don't need to setup a whole other server for ads that would be great and I want to check before I put all that working into an ad server just to push ads to the video site.  Thanks for being awesome btw.

**Comment by DanielnetoDotCom** [comment]
@techiesces we do not have a payment system integrated into AD_server yet
