### ISSUE TITLE
User can't view available meets 

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#4114]
![image](https://user-images.githubusercontent.com/63721378/101016559-a2923700-3571-11eb-9846-1adf10e94c67.png)

if user settings "can create meet" is disabled, the user can't view available meets. If the user click meet link from top bar, "Meetings you can attend" table shows the front page of the site.  See picture and you can test it on demo site.

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that.

Here is a fix

**Comment by tonuzo** [comment]
Thanks. It works.
