### ISSUE TITLE
Big Disparity In File Sizes

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4117]
**Describe the question**
When I do a LiveStream, I simulcast (using Restream.io) to Youtube and some other platforms. Each broadcast is roughly 2 hours long. At the end of the day, I will download that file from Youtube and then upload it to my AVideo site.

The Youtube file is typically 1.5Gb. After I upload it to AVidoe it grows to over 3Gb sometimes over 5Gb.
Today, for the first time, I recorded the broadcast inside of AVideo and sent it to the encoder and the file is over 7Gb.

That is a really big disparity. Is there something I can do that will make for a smaller file when recording and sending to encoder that will result in a smaller file.
Note images below:

<img width="735" alt="1_4Gb" src="https://user-images.githubusercontent.com/7376298/101087798-657d7300-3578-11eb-9cdc-e678c8cae421.png">
I uploaded the file above to AVideo and it it now 3.27Gb
<img width="1243" alt="3_27gb" src="https://user-images.githubusercontent.com/7376298/101087818-6c0bea80-3578-11eb-9bb9-2f4edcb00a3f.png">

Today's broadcast was roughly the same length (a few minutes less) and it was recorded and sent to encoder and is over 7Gb file size.
<img width="1214" alt="7_3gb" src="https://user-images.githubusercontent.com/7376298/101088009-a9707800-3578-11eb-9367-eb8c86ef91e8.png">

**Comment by DanielnetoDotCom** [comment]
this is because from youtube you download only 1 file with one resolution.

the file size displayed is the sum of all converted resolutions (minimum 3) plus generated images

**Comment by akhilleusuggo** [comment]
Exactly , you're transcoding the file into 4 resolutions in your case ( 240,360,480,720 ) . So it's normal to have the file size bigger then the original size .

**Comment by bbyrdhouse** [comment]
Ok ... well that makes sense. Is that the same for the one that was recorded and then sent to encoder? (7.3Gb)

If so, is there a setting to prevent the recording from making al those copies? ... I'd like to just find a happy medium ... maybe 590p or something like that.

**Comment by bbyrdhouse** [comment]
@akhilleusuggo - The encoder is only doing 2 resolutions (Low & High) no standard

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/101091876-72728480-35c1-11eb-94e4-bca4320a7c9c.png)

**Comment by bbyrdhouse** [comment]
Geez ... I have it set to Low and High, why is it making all those ...

**Comment by bbyrdhouse** [comment]
<img width="564" alt="enc1" src="https://user-images.githubusercontent.com/7376298/101092105-b98b5600-357e-11eb-9980-9144738e4847.png">

**Comment by akhilleusuggo** [comment]
I've reported this before , but those setting DOES NOT work with the plugin ''send video to encoder" .
Sadly , if you have the HLS Plugin , will ALWAYS encode the streams in hls , and you don't have control over it .
That's why I disabled the HLS plugin , was giving me too many issues .

Also on the second picture , looks like you video was encoded into HLS and MP4 .

**Comment by bbyrdhouse** [comment]
I see ... The best course of action might be to turn HLS off then ... I will run out of space real fast if each video is gonna eat up 5-8 Gb of storage.

Thanks

**Comment by akhilleusuggo** [comment]
Also try to change some ffmpeg command lines . 
I'm asking daniel for some features about bitrate control and fps . You can follow up here if you want more control ( as I do ) .

https://github.com/WWBN/AVideo-Encoder/issues/294

**Comment by bbyrdhouse** [comment]
@akhilleusuggo - YIKES!... I turned off HLS and all of the previous videos that had been uploaded using HLS are now not playable ... I had to turn HLS back on ... looks like I am gonna be stuck with using it now unless there is a way to continue to play those videos even after turning hls off ...
