### ISSUE TITLE
Error 524

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#4119]
when I typed my URL this came up
![willbeback](https://user-images.githubusercontent.com/739391/101109008-e140e500-35a3-11eb-94a4-090c279c85ed.png)

Rebooted YouTube server and everything appeared to work but it took a long time for my site to load.  Now an Errow 524 appears.

![errow524](https://user-images.githubusercontent.com/739391/101109136-27964400-35a4-11eb-9676-f1f5d23965ad.png)

I can't log into site to check the logs

**Comment by DanielnetoDotCom** [comment]
I suspect your disk is full.

please check it.

**Comment by willpower68** [comment]
This is extremely frustrating.

1. The disc isn't full.  I looked at that last week and have not added any new video.  I actually deleted several a few weeks ago.
2.  I can't log into the website(s) 
3.  server.youphptube.com times out.  so I can't log in server to accurately answer your question.
![servers youphptube-cantbereached](https://user-images.githubusercontent.com/739391/101531109-cdf59700-3960-11eb-9348-19fdda0948b2.JPG)

I followed the direction below to try an correct the Err Connection Timed Out but obviously it did not.  I review other articles that provided alternative instruction.  They did not work.
kinsta.com/blog/err_connection_timed_out/

any help or insight would be helpful because it's disheartening

**Comment by DanielnetoDotCom** [comment]
To know if the disk is full you need to login using SSH into your server and type

`df -h`

**Comment by DanielnetoDotCom** [comment]
FYI

![image](https://user-images.githubusercontent.com/18009293/101549810-11fe9100-398d-11eb-86b4-64588a131ea5.png)

**Comment by DanielnetoDotCom** [comment]
as I told you, I login into your server and your disk is full

![image](https://user-images.githubusercontent.com/18009293/101549988-5d18a400-398d-11eb-8bde-a2f74a8c9d77.png)

**Comment by willpower68** [comment]
when it is full, does that prevent me from logging into the website to delete videos files?

**Comment by DanielnetoDotCom** [comment]
yes it does.

**Comment by willpower68** [comment]
How do I delete the videos to decrease the size?

**Comment by willpower68** [comment]
since I can't login to the website

**Comment by DanielnetoDotCom** [comment]
not sure, first you may need to identify what you can delete. 

If I am in your shoes you should try to make about 100 MB free then login and delete what you can

maybe delete tmp file, or backup or uninstall something.

**Comment by willpower68** [comment]
@DanielnetoDotCom I was able delete files to free up space and login

while updating I did step 2 first (download & upload master copy of Avideo)
I tried step 1 git pull and got the following 

![gitpull](https://user-images.githubusercontent.com/739391/101587025-38cebe80-39b1-11eb-80aa-0962dc2cb59a.png)

How should I proceed to correct?

**Comment by willpower68** [comment]
@DanielnetoDotCom I noticed you provided direction for the issue above.  I was able to figure it out.  Thanks

**Comment by willpower68** [comment]
@DanielnetoDotCom 
I was able to free up space
