### ISSUE TITLE
How To Reset The Total Views For Livestreams

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4120]
**Describe the question**
Each day when I start a new livestream it still has the "total views" up even though its a new livestream. How do I clear this to zero with each new livestream?

<img width="245" alt="Screen Shot 2020-12-03 at 7 34 34 PM" src="https://user-images.githubusercontent.com/7376298/101110613-fb2bf900-359e-11eb-8880-72ea3aceac29.png">

**Comment by JoshWho** [comment]
change streamkey on the channel

**Comment by bbyrdhouse** [comment]
pfft ... ok. Having to do that every day for each stream sort of sux but it is what it is, I'll make the most of it.
Thnx 👍
