### ISSUE TITLE
The Meet (Jitsi) Feature No Longer Works

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4121]
**Describe the question**
At one point the jitsi Meet feature was working, I had tested it out and pleasantly surprised to learn it was built-in because I had just recently deployed a jitsi instance on a different server. However, I go to use it tonight and was surprised to see that it is no longer working.
Included it the screenshot of my parameters in the Meet plugin and the error that appears when I try to use it.

<img width="602" alt="jitsi" src="https://user-images.githubusercontent.com/7376298/101111352-a25d6000-35a0-11eb-934b-77cb618f9467.png">

  
  
<img width="684" alt="jitsi2" src="https://user-images.githubusercontent.com/7376298/101111363-a8534100-35a0-11eb-8f25-a1e3cc769c80.png">

<img width="779" alt="jitsi3" src="https://user-images.githubusercontent.com/7376298/101111369-aab59b00-35a0-11eb-85d5-d4a3748947c1.png">

**Comment by DanielnetoDotCom** [comment]
If you wait a couple of minutes does it work?

**Comment by bbyrdhouse** [comment]
No sir ... it just says the North America server is offline and the server is not ready.

<img width="1102" alt="jitsi_1" src="https://user-images.githubusercontent.com/7376298/101175248-88586780-360a-11eb-8c1a-95d68d89f1b9.png">

<img width="1355" alt="jitsi_3" src="https://user-images.githubusercontent.com/7376298/101175503-da998880-360a-11eb-886c-c768f67e9e23.png">

**Comment by DanielnetoDotCom** [comment]
I notice the Cache plugin was treating the Meet as a Bot, I sent a fix for that


While looking at this issue I found this in your logs


```
[04-Dec-2020 09:25:41 America/Chicago] AVideoLog::DEBUG: wget: ERROR the url download but is empty https://encoder.......com/view/getBestEncoder.php, /var/www/html/AVideo/videos/cache/YPTurl_get_contents/2c32cf8ef31cd7f9cb49227f019635d0 SCRIPT_NAME: /plugin/Meet/index.php
[04-Dec-2020 09:25:41 America/Chicago] Configuration::getEncoderURL ERROR your network (https://encoder......com/) is not configured properly This slow down your site a lot, disable the option useEncoderNetworkRecomendation in your CustomizeAdvanced plugin

```

The first thing I did was disable the network configuration because it seems to not be ready yet

Just a TIP. looks like you are using an old Network version, please make sure you download the latest or use `git clone` (preferred)

you need to update your files because I could not due to your changes

**Comment by bbyrdhouse** [comment]
@DanielnetoDotCom - I downloaded what you have on Git last night ... that is what I used in the encoder site.

**Comment by DanielnetoDotCom** [comment]
So should I overwrite you again?

**Comment by bbyrdhouse** [comment]
Hi @DanielnetoDotCom - I did the update myself ... I also just pulled from the git directly to the new encoder site ... it does look different.

**Comment by bbyrdhouse** [comment]
NOTE: I've just uploaded and encoded using the new encoder site and it seemed to worked except the video doesn't appear on my gallery front page when finished.

1. I upload using the encoder network with is encoder.patriotreload.com
2. Video uploads and then encodes
3. I can go back to thepatriot.network and see the video in "My Videos" but the video does not appear on the front page of the gallary

**Comment by bbyrdhouse** [comment]
Scratch that ... I had to clear the cache and now it shows up ... this is really sweet once you get it all working.

**Comment by DanielnetoDotCom** [comment]
I just found your cache blocking another script. it is fixed now. and your meet is online

**Comment by bbyrdhouse** [comment]
Thanx
