### ISSUE TITLE
All Video Uploads Fail Since Latest Update

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#4124]
Since my last update of the software you cannot upload videos. It goes through the process and looks good but when you play a video, it cuts off at about one minute. The video starts to play but you cannot scroll forward or backward and the video suddenly ends playing at about a minute although the timeline shows the full video length.

Here is an example video I uploaded this morning: https://diytube.video/video/38014/worked-a-full-day-getting-wood-for-the-off-grid-homestead

Press play and watch for a minute. Then it stops suddenly.

All along I have been uploading my daily videos and they were not working.

Also the thumbnails sometimes fail since the last update. You can see this on the recent upload videos on my site. Some thumbnails are missing.

And often there is just a complete failure with no messages or warnings. It just fails to upload and in the queue list on the encoder you can see that it says failed.

My site worked perfectly well before the last update.

**Comment by bbyrdhouse** [comment]
Hi,
I just want to confirm. I just checked out your video on both Safari and Chrome and the video plays to about 1:12 and then the counter keeps counting (like it is still playing) but the video is stopped and the sound is stopped.

I had a similar thing happen to me when I turned off HLS and used only direct upload. Thumbnails would not be created adn the video would stop after about a minute ... I ended up having to delete the video and re-upload the video using more than one resolution.

Not sure if that info will help someone out who is will be able to offer guidance.

**Comment by Fawzi47222** [comment]
Hello everyone,since you have an experience with this prohect, I would like to know where we can find professional hosting for these kind of sites?
And do these kinds of sites require special hosting that has a special name? Who has a lot of ssd storage or what?

Thank you for taking the time to read my question
cordially

**Comment by DanielnetoDotCom** [comment]
@Fawzi47222 you should open a new issue, your post has nothing to do with this issue

**Comment by The-Do-It-Yourself-World** [comment]
Is there any update here? Not a single video has uploaded properly and all formatting in the description is stripped when you save it. No paragraph breaks, nothing. It gets stripped out.

When you upload a video, it all looks fine. But when you try to play the video, it cuts off at about 1 minute every single time.

This happened on my last update on Nov 16th and nothing has worked since then. I am losing money here. Please help.

**Comment by DanielnetoDotCom** [comment]
Your encoders were outdated (I am pretty sure that was the problem)

also, I enabled the headers apache module on your streamer, does not cause this problem but encoders work better with this enabled
`sudo a2enmod headers`

I submit those 3 videos (both encoders tested)

https://diytube.video/video/38024/scarlet-witch-and-vision-vs-black-order---fight-scene-%7C-avengers-infinity-war-2018-movie-clip-4k

https://diytube.video/video/38026/bonnie-tyler---god-gave-love-to-you-die-pyramide-11.9.1993-vod

https://diytube.video/video/38027/black-panther-vs-bucky---rooftop-fight---chase-scene-%7C-captain-america-civil-war-2016-movie-clip

**Comment by The-Do-It-Yourself-World** [comment]
All good, thank you very much.
