### ISSUE TITLE
Software removes all formatting in video editor since last update

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#4125]
When you edit a video description in "my videos" everything looks fine. But when you save it, all formatting is stripped out.

This started since I last updated the software. It worked perfect before that.

Here is an example: https://diytube.video/video/38015/worked-a-full-day-getting-wood-for-the-off-grid-homestead-1

Scroll down and see the description. Its a mess. This happened during the last software update. Before that it was fine.

**Comment by DanielnetoDotCom** [comment]
I cannot see a problem in your description, but I can see your texts are aligned to the center, and it does not suppose to happen.

I inspect your code and I found this comparing with the demo site

![image](https://user-images.githubusercontent.com/18009293/101180727-b2218680-362a-11eb-9794-9ac4efd0def3.png)


where does the user agent stylesheet come from? I have no idea. I guess it is something in your webserver

**Comment by The-Do-It-Yourself-World** [comment]
I have no idea. The only software I have is from you and from updates. Now, remember, my site is 3 years old now so there may be some old residual stuff left over from the "old days".

**Comment by DanielnetoDotCom** [comment]
I found your alignment problem. it was a missing <center> tag

![image](https://user-images.githubusercontent.com/18009293/101224829-94761080-366e-11eb-97bd-e0071d4ff94b.png)

It took me a while to find, and definitely, it was not my fault and it was not a software bug

**Comment by The-Do-It-Yourself-World** [comment]
The issue is that the paragraph breaks were vanishing and all text was jumbled together. The <center> issue I did not even notice, but thanks for pointing that out.

**Comment by The-Do-It-Yourself-World** [comment]
All formatting is still being stripped out of the video description. Daniel updated my site and that must have removed the fix he made earlier.

**Comment by The-Do-It-Yourself-World** [comment]
This went stale but I am still experiencing problems. All formatting gets stripped when I upload a video from another site. Or when I edit a video that already exists. No paragraph breaks or other types of formatting. It is all jumbled together.

Here is an example of a video I copied from my YouTube channel: https://diytube.video/v/38315

Notice the video description is all jumbled together. No spaces between paragraphs. Its hard to read. Also links get jumbled together and joined onto sentences due to no breaks between them and text.

The original video on YouTube was all neat and tidy.

**Comment by The-Do-It-Yourself-World** [comment]
This is still a problem for me and it is quite annoying. When I edit a video description, all formatting and blank space between sentences get removed.

**Comment by The-Do-It-Yourself-World** [comment]
![Video-Description-Formatting-Removed](https://user-images.githubusercontent.com/45924889/147619587-67a893a5-9ecb-46e7-a93c-3d48d556ae2d.jpg)


Here is an example of a video I had already fixed once before. I open the video editor under "My Videos" and then the formatting is all stripped out. So I edit and save it. All is well. But if I open the video to edit anything in the future again under my videos, the description is stripped out again and all formatting and spaces are removed between sentences. Its all jumbled together.

**Comment by The-Do-It-Yourself-World** [comment]
![Video-Description-Formatting-Redone](https://user-images.githubusercontent.com/45924889/147619898-0573c1df-32fe-42b0-9748-71f16bbb2554.jpg)

Here I am editing and adding the correct paragraph returns and spacing between sentences.

**Comment by The-Do-It-Yourself-World** [comment]
![Video-Description-Formatting-Fixed](https://user-images.githubusercontent.com/45924889/147619921-f646ab97-688b-4c1e-8b15-7bbcbe7e5c9b.jpg)


I check and it has saved correctly.

**Comment by The-Do-It-Yourself-World** [comment]
![Video-Description-Formatting-Removed-Again](https://user-images.githubusercontent.com/45924889/147619972-c08929ea-cdc4-47e2-b0b8-e06ba3970830.jpg)


I open the video to edit something again and all formatting is removed once more. I can repeat this cycle forever. It strips out all formatting every time I open a video to edit something.

**Comment by The-Do-It-Yourself-World** [comment]
![Video-Description-Formatting-Messed-Up](https://user-images.githubusercontent.com/45924889/147620054-110df932-02c1-47eb-adf1-58d2f9978d0e.jpg)


If I do not notice or fix things and save the data, this is what I see on the video play page. Its all jumbled together.

This happens no matter what I am editing in the video editor. If I open any video to edit, all formatting is removed from the description every single time. It is a lot of work to redo it all.

**Comment by The-Do-It-Yourself-World** [comment]
I can manually rewrite all the paragraph returns and spacing between sentences and save my work and it is fine and looks good. But next time I open any video to edit something, all formatting is removed once more and I have to start all over again.

Can you imagine opening the description to edit a single spelling error? I have to redo it all again.

**Comment by DanielnetoDotCom** [comment]
Make sure you have this unchecked 

![image](https://user-images.githubusercontent.com/18009293/147665654-2351221c-41b3-494f-ba52-9fe9cc50d3f3.png)

**Comment by The-Do-It-Yourself-World** [comment]
Ok, that worked. Thanks.
