### ISSUE TITLE
StripeYPT Plugin Says and Update is Ready But It's Not On Plugin Site

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4126]
**Describe the question**
The plugin StripeYPT says there is an update to version 2 but when you click on it to go to the plugin store to download the new version, it does not appear in the plugin store.

<img width="943" alt="stripeYPT" src="https://user-images.githubusercontent.com/7376298/101177812-d884f900-360d-11eb-94cf-78305e79bb8c.png">

**Comment by tonuzo** [comment]
It's a free plugin. I think you need to update.
