### ISSUE TITLE
Live Streaming will not start .... 

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4127]
**Describe the bug**
I am attempting to do a livestream right now and it simply will not start. I've done nothing different than any other day.

I can really look into it right now because I am doing a livestream for the next 2 hours, I will have to look at it after I am through.

**Comment by DanielnetoDotCom** [comment]
You enabled the adaptive mode in your nginx.conf

![image](https://user-images.githubusercontent.com/18009293/101187779-8eaf0980-3633-11eb-889e-e1bbfc522a62.png)


but you did not check the option in the plugin

![image](https://user-images.githubusercontent.com/18009293/101187741-848d0b00-3633-11eb-88d8-db7233bdee69.png)

I just checked it for you, you should be fine now

**Comment by bbyrdhouse** [comment]
Enabling adaptive mode will disable livestreaming? 

I need to start writing this down, I didn't not see that information anywhere. 
So, disabling adaptive will let me livestream again?

**Comment by DanielnetoDotCom** [comment]
You should be good now.

but if you change the nginx.conf you also need to change the plugin parameters.

If I am in your shoes I wouldn't touch anything. you are good now
