### ISSUE TITLE
ROKU

### ISSUE THREAD

**Issue by techiesces** [WWBN/AVideo#4128]
I am not sure if this exists or not as I know of the feeds url but it does not seem to work for roku.

It seem that in order to setup a roku channel I need an rss feed that is called an MRSS feed that matches their requirements.  Does this already exist or is there a way to make such a thing?  https://developer.roku.com/docs/specs/direct-publisher-feed-specs/mrss-dp-spec.md

I included the spec doc for roku for guidance.

I have bought a few plugins and plan on buying more fyi.  I have built my own server located at https://viewys.com as an alternative to YouTube.  Thanks for all your help!

**Comment by bbyrdhouse** [comment]
I'd also like more info on this ... I've been exploring developing a Roku app to accompany the website. If anyone has any experience or advice ...

**Comment by techiesces** [comment]
In order to have an MRSS feed the following components must be there:

        Item
            guid*
            pubDate*
            media:title*
            media:description*
            media:category*
            media:keywords*
            media:thumbnail*
            media:content*

Currently I feel some of the elements are missing from the feed url, like Category and Content.  Atleast that is the error reports I get from my roku test channel.  Also I am not sure if any ports need to be open or not in order to supply the feed to roku.  I would be happy to pay for assistance or a plugin to make this work.  Thanks.

**Comment by DanielnetoDotCom** [comment]
MRSS updated, but you should use https://viewys.com/mrss/

**Comment by DanielnetoDotCom** [comment]
For example, this is the site MRSS
https://demo.avideo.com/mrss

this is a channel MRSS
https://demo.avideo.com/channel/TheAdminChannel/mrss

**Comment by techiesces** [comment]
Ah yes, nice.  Thank you sooooo much! Is there a update or refresh I need to do on my end to create this file.  The mrss feed file does not yet exist on my website.  using https://viewys.com/mrss/ brings me to a 404 error page not found.

**Comment by DanielnetoDotCom** [comment]
Here https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by techiesces** [comment]
Oh ok, I thought the internal update version would work.   My folder name is AVideo instead of Youphptube... or atleast I do not have a directory by that name.  Do I pull into the AVideo folder instead?  cd /var/www/html/AVideo/

**Comment by techiesces** [comment]
***UPDATE***

Two errors from ROKU Dashboard regarding mrss feed.

Required content duration missing or invalid. Duration must be greater than 0.
and 
Thumbnail must be 16x9 aspect ratio, at least 800w x 450h, and either in JPG or PNG format.

**Comment by techiesces** [comment]
***UPDATE***   BTW, works perfect with the Amazon Creator for FireTV.  Added mrss feed into creator and it pulled everything perfectly and works well.  Have not checked appleTV yet.   Not sure why ROKU being so stubborn with the duration issue.

**Comment by techiesces** [comment]
***UPDATE***

So apparently for ROKU the duration is not optional part of the media content.

url | Required | The URL of the video file
duration | Required | The duration of the video (in seconds)
bitrate | Optional | The bitrate of the file. Must be provided if multiple single bitrate (e.g., MP4) files are provided.
lang | Optional | The original language of the video

Here is an example below

media:content
   url="https://example.org/videos/your-video-id.mp4"
   duration="74.74" />

So one of my feed entries are 
<media:content url="https://viewys.com/videos/_YPTuniqid_5fcedd1a218052.16892734_720.mp4" fileSize="24184446" bitrate="128" type="video/mp4" expression="full">
<media:title type="plain">Merry Christmas</media:title>
<media:description type="html">
<p>Video From tommyvideo <a href="https://pixabay.com/users/tommyvideo-3092371/?tab=videos">https://pixabay.com/users/tommyvideo-3092371/?tab=videos</a><br /><br />Christmas Rap by Kevin MacLeod<br />Link: <a href="https://incompetech.filmmusic.io/song/3505-christmas-rap">https://incompetech.filmmusic.io/song/3505-christmas-rap</a><br />License: <a href="http://creativecommons.org/licenses/by/4.0/">http://creativecommons.org/licenses/by/4.0/</a></p>
</media:description>
<media:thumbnail url="https://viewys.com/videos/_YPTuniqid_5fcedd1a218052.16892734.jpg?1607392543"/>
</media:content>

Would have to add duration I am guessing sourced from length variable you already have.

<media:content url="https://viewys.com/videos/_YPTuniqid_5fcedd1a218052.16892734_720.mp4" ***duration="5364148"*** fileSize="24184446" bitrate="128" type="video/mp4" expression="full">
<media:title type="plain">Merry Christmas</media:title>
<media:description type="html">
<p>Video From tommyvideo <a href="https://pixabay.com/users/tommyvideo-3092371/?tab=videos">https://pixabay.com/users/tommyvideo-3092371/?tab=videos</a><br /><br />Christmas Rap by Kevin MacLeod<br />Link: <a href="https://incompetech.filmmusic.io/song/3505-christmas-rap">https://incompetech.filmmusic.io/song/3505-christmas-rap</a><br />License: <a href="http://creativecommons.org/licenses/by/4.0/">http://creativecommons.org/licenses/by/4.0/</a></p>
</media:description>
<media:thumbnail url="https://viewys.com/videos/_YPTuniqid_5fcedd1a218052.16892734.jpg?1607392543"/>
</media:content>

**Comment by DanielnetoDotCom** [comment]
Please check this update and share the results

**Comment by bbyrdhouse** [comment]
@techiesces - could I ask, are you using a ROKU template or are you simply using the their API?

**Comment by techiesces** [comment]
@DanielnetoDotCom Duration issue solved.  Still having a weird issue with thumbnails.  I need to look into it a little more to see what it is asking for... it's claiming it can't download the thumbnails of most of the videos.  Not sure why it says that.  I will get back to you on that, but at-least the duration issue is solved.

@bbyrdhouse It is direct publishing using their template allowing you to simply feed a mrss url to them.  Amazon's FireTV has the same thing.  They are easy to setup and once set there is nothing else you need to do as everything is injected via your mrss feed.  Here is the link to Roku channel management https://developer.roku.com/developer-channels/channels and here is the FireTV app creator, just select rss feed.  https://creator.amazon.com/projects/new

I have not checked out appleTV yet to see if they have something similar.

**Comment by techiesces** [comment]
@DanielnetoDotCom Yeah something changed overall with thumbnails because they are not pulling into FireTV either anymore either.  I checked and for some reason the thumbnails are all missing except the first video on the list, which would have been the last one uploaded.  Maybe the url changed in directory?  When I go into the mrss feed and directly goto each thumbnail they are blank. Like this https://viewys.com/videos/_YPTuniqid_5fd2e67ccb7b56.53419641_roku.jpg

Is there a way to refresh all these?

**Comment by DanielnetoDotCom** [comment]
The images are rollback for mrss.

I guess roku needs a specific feed, try this https://tutorials.avideo.com/roku.json as a roku feed

**Comment by techiesces** [comment]
@DanielnetoDotCom Sorry, what I mean is that the images are missing completely.  Even on your website.  The references to the thumbnails don't exist. https://tutorials.avideo.com/videos/_YPTuniqid_5fd22e74199722.29706653_roku.jpg  Check it and see for yourself.  It is not a mrss versus json issue...

**Comment by DanielnetoDotCom** [comment]
Please check now

**Comment by techiesces** [comment]
***ALL WORKING***  I checked both roku and amazon firetv and everything is syncing perfectly.  Roku may error in future if any new video thumbnails come through not in 16:9 format.  That is all, but otherwise we are good to go!  Thanks!

**Comment by DanielnetoDotCom** [comment]
Please delete all of your roku.jpg files; 

the files generated in the previous version were wrong. now it should be fine

**Comment by techiesces** [comment]
👍🏻 Thanks!

**Comment by techiesces** [comment]
Reopening for a small issue that requires a manual fix.

I had three videos uploaded from a phone that did not match the 16:9 format and therefore the thumbnails that generated were not in 16:9.  While it does not interfere with the FireTV channel, it does throw an error to the Roku channel.  Here is the error for your reference.

***3 items have error: Thumbnail must be 16x9 aspect ratio, at least 800w x 450h, and either in JPG or PNG format.***

I can manually go in and make 16:9 jpeg thumbnails myself and clear the errors, but was hoping or wondering if there is a way to push a 16:9 formatted thumbnail automatically when a video is uploaded.

Thanks.

**Comment by DanielnetoDotCom** [comment]
It should be automatically converted.

can you please check your roku image size?
