### ISSUE TITLE
how to prevent video from being converted to 240p and 360p

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#4129]
Tell me what should I do to prevent video conversion to 240p and 360p

<a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/12/5/9c087351046996633e16be263c3122aa-full.jpg" border="0"/></a>

**Comment by DanielnetoDotCom** [comment]
You cannot remove it from automatic resolution detection.

**Comment by palich91** [comment]
are there any alternatives?
