### ISSUE TITLE
Playlist TAB is empty

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4130]
How do I create and list my playlists on my profile page under the playlist TAB. I set every video to a playlist but those do not show on my profile.

![Screen Shot 5781-03-19 at 11 48 24](https://user-images.githubusercontent.com/58882903/101239405-fdea3380-36ef-11eb-9bfd-8a02430fc89b.jpg)

**Comment by DanielnetoDotCom** [comment]
If you do have some playlist with videos in it. check your streamer log file and also the JS console.log

**Comment by guymass** [comment]
What should I look for in the streamer log file?

This is what browser JS console shows:

![Screen Shot 5781-03-21 at 18 59 35](https://user-images.githubusercontent.com/58882903/101380794-a2ba6b80-38be-11eb-872c-0e331ff2dc99.jpg)
![Screen Shot 5781-03-21 at 19 00 18](https://user-images.githubusercontent.com/58882903/101380800-a5b55c00-38be-11eb-8b13-52419808ba99.jpg)

Other than that I am not sure why playlists are not showing. Users create their own playlists right? and than assign their videos to those lists to be displayed in their tab.

**Comment by guymass** [comment]
This is from the streamer logs, not sure if its related or not.

![Screen Shot 5781-03-21 at 19 17 54](https://user-images.githubusercontent.com/58882903/101382702-f0d06e80-38c0-11eb-8c01-30f7923a28eb.jpg)

**Comment by guymass** [comment]
Well now its working! problem was a user wrongly creating playlists as categories and he told me his lists are empty. After connecting to his profile from TeamView I noticed he was setting his playlists wrongly.

Sorry for the hassle.
