### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by Fawzi47222** [WWBN/AVideo#4131]
Hello everyone, I would like to know where we can find professional hosting for these kind of sites?
And do these kinds of sites require special hosting that has a special name? Who has a lot of ssd storage or what?

Thank you for taking the time to read my question
cordially

**Comment by palich91** [comment]
For AVideo, you need a minimum of VPS, or better a dedicated server

**Comment by akhilleusuggo** [comment]
@Fawzi47222 Please take a look at the wiki ; You can find helpful information . Take a look here : https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements

**Comment by hostquota** [comment]
Deducated servers can be quite expensive if your site is new and userbase low, so I would reccommend low cost dedicated servers from Kimsufi.com.
You may have to wait a few days for their lowest cost servers, but those from around £10 pm and above usually come quick.
