### ISSUE TITLE
Live plugin stats URL still mysite.com

### ISSUE THREAD

**Issue by djslmft** [WWBN/AVideo#4133]
hey,

I moved our server to ubuntu server 20.04 and I keep getting this error in AVideo log:
 AVideoLog::ERROR: Live::getStatsObject RTMP Server (https://www.mysite.com:1443/stat) is OFFLINE, we could not connect on it => live_servers_id = (0)  SCRIPT_NAME: /plugin/Live/stats.json.php

in the plugin settings i set up the good url for stats

if i remove the url I get this:
AVideoLog::ERROR: Live::getStatsObject RTMP Server () is OFFLINE, we could not connect on it => live_servers_id = (0)  SCRIPT_NAME: /plugin/Live/stats.json.php

everything works fine, this is the only error i got

**Comment by DanielnetoDotCom** [comment]
you probably did not install NGINX + RTMP
