### ISSUE TITLE
Changing port stops videos playing

### ISSUE THREAD

**Issue by henry88g** [WWBN/AVideo#4135]
I have followed the solution which worked in the now-closed issue #1624 to add a port number to URLs created within the application, and so can successfully move from page to page, do admin tasks, etc.  That is, I edited videos/configuration.php:

//if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { 
    // get the subdirectory, if exists
    $file = str_replace("\\", "/", __FILE__);
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), $file);
   // $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
//}else{
    $global['webSiteRootURL'] = 'http://goldstein88r.no-ip.org:8044/AVideo/';
//}
(The code in the current version is slightly different from that in 2019, it seems)
However, the videos do not play.

Similar code is in objects/configuration.php and install/checkConfiguration.php

Might I have to make similar changes in either of those files to enable the videos to play - or might my issue be something completely different.
[This is not an urgent matter - I can adapt my port forwarding so as to avoid the need for referencing a port in the URL - but I would like to keep my URLs consistent over all the applications on this server, if possible - I am running Wordpress websites and Zoneminder, too]

Any suggestion would be appreciated.

Regards,
Henry

**Comment by akhilleusuggo** [comment]
to avoided this things , you will need to make a reverse proxy nginx . By default , all browsers will hit port 80 and 443 . Unless you want your users to manually type every time the port number . Is just a bad idea .

You haven't specified why do you wanna change the port ? You can run hundreds of webserver on the same server , using the same port . 

PS : I visited your site , and does for me . But when browsing , does change back to port 80 . 
Make sure to change your site also on plugins , CustomizeAdvanced for logo .

Later I'll try this on my local server , but the config file is really old , yes .

**Comment by henry88g** [comment]
Thanks for your quick reply.

AVideo is working well (as you can see).  goldstein88r.no-ip.org, without a specified port (and so using port 80), is sent by port redirection in my router to port 80 on my main server computer.  

[I think you can see that my technical knowledge is limited, and my network set-up is more complicated than it should be for a hobbyist like me.  I operate a few small websites, designed for a small audience. ]

My ISP gives me a single, dynamic, IP address, and I use no-ip.org to make sure that all traffic to any of the hostnames I use is directed to that IP address.  I then use port redirection in my router to direct incoming traffic to port 80 on one of a number of computers acting as servers.  For example, goldstein88r.no-ip.org:xxxx goes to port 80 on computer A and goldstein88r.no-ip.org:yyyy goes to port 80 on computer B.  This works well with Wordpress, where I have a number of sites on computer A and 'emergency backup sites' on computer B.  So - it's always port 80 as far as the servers are concerned.

I use either bit.ly (as in [bit.ly/constantbear](url) or a separate hostname at no-ip ([handhvideos.ddns.net)](url) to avoid users having to type port numbers in their browsers. 

My method has worked ok with other applications on the same computer, Wordpress, and  Zoneminder, both of which seem to include the entire URL, including port numbers, in every URL that they generate for pages and images, and so I was concerned when AVideo didn't work the same way, and searched around to see what was happening - hoping to find a 'solution' that wouldn't involve anything too technical for me.  

It would be a bonus, although certainly not necessary, if a simple change would make AVideo work in the same way.  It appears not.

I need to learn about reverse proxies - that may be a better way to achieve my aim - rather than having both main and backup computers always accessible from the internet.  Thanks for pointing this out.  I use apache2, but that should work as well as nginx.

Again, thanks very much for your attention.  For now, I'll leave things as they are - working.

One other thing - an unrelated topic.  I wanted to store my actual videos on a separate drive from the application, and have seen a number of discussions on the web.  I decided to try something simple - creating a bind mount of the directory with the videos onto /var/www/html/AVideo/videos.  That seems to work.  Do you think this will be a problem in the future?

Regards,
Henry

**Comment by akhilleusuggo** [comment]
Reverse proxy is the way . Hosting a site from home is a huge risk and you will eventually get hacked by attackers .
Reverse proxy is a layer of security on top of your firewall . Will hide your home IP address , and cache multiple requests , improving the pages speed and heavy loads .

Talking about ports , I don't really understand your setup , but 1 port is enough for what you describe . Also you can use SSL ( let's encrypt ) , it's free . With this you can achieve the site to load on port 443 ( and secured ) . Non would register to your site , since the user name and password are sent/requested on blank text .

**Comment by henry88g** [comment]
Thanks again.

I will try to learn about reverse proxy.  There was some reason I have 
not used let's encrypt, but I can't remember now.  I shall look into 
that again.

I take your point about hacking.

By the way, the handhvideos site is by invitation only.  No personal 
information.  No commerce.  No self-registration.   Just a way to 
provide a bit of information and links to videos to my existing 
students.  Most of the videos are hosted on YouTube, but I wanted to see 
if I could use a self-hosted alternative.  I have some spare time during 
the Covid-19 time, and like (maybe too much) playing around with 
software.  No questionable content - just me doing taichi.

AVideo is probably over-kill for what I want.  Still, it's been fun.  
And thanks again.


My website for the general public - taichiclapham.com - is hosted at 
Wordpress.


Regard,
Henry

-- 
Henry Goldstein
88 Rodenhurst Road
London  SW4 8AP
Tel / Fax: +44 20 8678 7273
Mob:       +44 77 8577 1717
