### ISSUE TITLE
Error loading administration pages because of update-check

### ISSUE THREAD

**Issue by SaliC-re** [WWBN/AVideo#4136]
Hey there,
after update to 9.6 and 10 from 9.4 we had some site loading problems after login.
(see #3861 )
We have a white-list firewall in our company so all new connections are blocked by default.
I saw that after login to administration the site tries to connect to IP 5.180.25.128 (which resolves into the youphptube site after typing in into browser)
I think this is something like an update check.

We opened this connection via firewall and the site was fast and stable again.

Is this IP fix so we can make one firewall rule - or is it dynamic that the IP is always different.

Can we put in proxy info for this update check?

Thanks!

**Comment by DanielnetoDotCom** [comment]
Hi, it is a fixed IP but we changed servers recently. that may be the issue.
