### ISSUE TITLE
Embed - Video is Private

### ISSUE THREAD

**Issue by julzxcapz** [WWBN/AVideo#4139]
I want to know what other option I need to make the video viewable. Please see the screenshots. Thank you. 

![image](https://user-images.githubusercontent.com/61785146/101351496-a1437000-38cb-11eb-8875-88480582e5a9.png)
![image](https://user-images.githubusercontent.com/61785146/101351523-abfe0500-38cb-11eb-97c4-f3ffbe5dda3b.png)
![image](https://user-images.githubusercontent.com/61785146/101351557-b6b89a00-38cb-11eb-97e6-14b1dab4f9e0.png)

**Comment by DanielnetoDotCom** [comment]
It supposes to work, are you sure you are up to date?

usually in the streamer log file, you can see the reason why access was denied to the video.

**Comment by julzxcapz** [comment]
Yes, I updated to version 10.0.

This is what listed on the log
![image](https://user-images.githubusercontent.com/61785146/101502651-2900ab80-39ac-11eb-881b-a56f8f3bff94.png)

**Comment by DanielnetoDotCom** [comment]
Always read the logs

![image](https://user-images.githubusercontent.com/18009293/101503076-7cdda700-3950-11eb-9706-638f8f3d0879.png)

![image](https://user-images.githubusercontent.com/18009293/101503214-9f6fc000-3950-11eb-9370-3f4630492749.png)

**Comment by julzxcapz** [comment]
But it should be viewable even without account, right ? because its public

**Comment by julzxcapz** [comment]
ohh that option is enabled, I will try to disable it first. thanks

**Comment by julzxcapz** [comment]
So that option applied for other users/guest only

**Comment by DanielnetoDotCom** [comment]
disable this plugin and check if it works, then enable again and play with the options, 

if necessary look at the code
