### ISSUE TITLE
Time advance / go back 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#4142]
Could the Web and app video interface have back and forward times, ie. Advance 30 seconds or go forward 30 seconds?
Also, the time slider bar should be bigger and easier to use to advance or go back in the video.

**Comment by DanielnetoDotCom** [comment]
If you enable the seekbutton plugin and double-tap over the video it may advance/go back

**Comment by fakeologist** [comment]
Didn't know about the double tap. Was it always that way or did it have an icon like youtube and bitchute?

**Comment by DanielnetoDotCom** [comment]
I just sent an update to it, please update your streamer

I am not sure what icon are you talking about

**Comment by fakeologist** [comment]
I don't see a time counter either.

**Comment by fakeologist** [comment]
![Screenshot_20201208-121619_bitslide.jpg](https://user-images.githubusercontent.com/66537018/101517843-363b7d00-394f-11eb-9ff4-14ff49a14edd.jpg)

A screen like this on touch is best.

**Comment by DanielnetoDotCom** [comment]
time counter?

FYI on mobile due to the small screen, we hide some information. otherwise, they may overlap each other.

**Comment by fakeologist** [comment]
Check above screenshot. Can you add that?

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by fakeologist** [comment]
Ok I see seek 10/30 in landscape but not portrait. It needs to be the same in both like the overlay screenshot above. One touch should bring up the menu too, not pause it.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot how do you see it?

**Comment by fakeologist** [comment]
![Screenshot_20201209-093037_Chrome.jpg](https://user-images.githubusercontent.com/66537018/101642679-44e26c80-3a01-11eb-9a3c-e8a5023474a7.jpg)![Screenshot_20201209-093050_Chrome.jpg](https://user-images.githubusercontent.com/66537018/101642689-46ac3000-3a01-11eb-9a29-c873aa134d36.jpg)

**Comment by DanielnetoDotCom** [comment]
I guess this is because a cached css
try this ne update

**Comment by fakeologist** [comment]
Well done thanks. Now for the app and background playing!

**Comment by fakeologist** [comment]
It's gone. The overlay window isn't showing. Can you also add the second count to the advance / rewind icons?

**Comment by DanielnetoDotCom** [comment]
What do you mean "It's gone. The overlay window isn't showing. "??

>  Can you also add the second count to the advance / rewind icons?

maybe in the future

**Comment by fakeologist** [comment]
Full screen mode doesn't have working advance rewind. The jumbo rewind button doesn't work. ![Screenshot_20201219-174914_Chrome.jpg](https://user-images.githubusercontent.com/66537018/102701216-a20cc800-4222-11eb-92ce-b5655b0a3daa.jpg)

**Comment by DanielnetoDotCom** [comment]
thanks for notice that, please try this new update
