### ISSUE TITLE
API usage question: Ability to call javascript from localhost and queue encoding from URL vs file

### ISSUE THREAD

**Issue by BlkWolfLH** [WWBN/AVideo#4144]
I have reviewed the API documentation as well have been searching for others who may have solved this issue/question.

**Description**
  I am looking to trigger the Avideo Encoder from command line vs web UI triggered from the local Unix host where the tool is running. From reading I have found the documentation on the use of the mobile upload API which defines using a file.mp4 as a source.  
 
  What I have not been able to find on this site or any other is options to pass into the API/or call to the encoder URL direct, which uses a URL as source vs a file to use for encoding. I do see from the source code on the encoder page where itself accepts URL as a form source, as well the encoder support. 

**Assistance Request**
 As I'm running this via local network (Javascript using xmlhttprequest) where can either:

    1. Get guidance on where I can find details on which arguments the API will accept for upload types other then file?
    2. Has anyone solved this using a javascript/xmlhttprequest that they are willing to share? 

References check so far: 
   https://github.com/WWBN/AVideo/wiki/About-Video-Upload 
   https://github.com/WWBN/AVideo/wiki/AVideo-Platform-API
   
What would be probably very simple to make (I'm coming from a server background vs a developer background) is ability to call the encoder via shell and pass in the URL and info. If you would a simple shell interface that can run either on the encoder or in a separate node. 

Appreciate the help. If I get this one figured out Ill share back for others looking to do the same.

**Comment by DanielnetoDotCom** [comment]
Hi, I guess you are looking for this https://github.com/WWBN/AVideo/wiki/Upload-videos-from-third-party-applications

**Comment by BlkWolfLH** [comment]
Thank you for your time and reply. 

I have also looked at the above in reference which identifies how to upload if the source is a file.

  <input name="upl" type="file"  accept="video/mp4"  /><br>

What if the source is a URL vs a file to pass in? Is there a list of supported types and what it would take to replace the "file" w/ a source URL?

**Comment by BlkWolfLH** [comment]
Sorry. I have been looking for a reply which still escapes me. My question is about passing in a URL vs a file. The documentation shared has example I could find for a file. I am assuming this is a capability but I am unable to find the API documentation which shows which options are available to pass. This is the core of my question still pending assistance.

**Comment by DanielnetoDotCom** [comment]
Hi, 

I guess the example is with an HTML form so the browser will submit the file.

but you also can submit a file with the curl function. try to google for that

a quick google search I found this: https://stackoverflow.com/questions/21905942/posting-raw-image-data-as-multipart-form-data-in-curl

**Comment by BlkWolfLH** [comment]
Thank you. 
  So the only supported method for uploading is from file alone? Is that correct? I do see and appreciate the examples (all very valuable in helping for a file), but want to confirm that the only supported input method is by file alone and not by a source URL in replacement of the file. Is this a correct statement and understanding for myself?

**Comment by DanielnetoDotCom** [comment]
Maybe you can place the URL directly into the encoder, I have not tested it but I guess it will work

**Comment by BlkWolfLH** [comment]
Thank you. That is the original question that I have. I understand that file is possible to load in. It is clear that via the encoder that it is possible to pass in a URL instead of a file. I however would like to find the API docs which provide what options there are to use. My option (is as you shared above) seams to use something like Curl to interface w/ the local encoder URL.

What I think would be a fantastic solution would be to provide the above or a way to pass a URL call to one of the server php scripts. The team here is working to crack this one and make it work. Appropriate all your time and assistance.

**Comment by DanielnetoDotCom** [comment]
It may require some code for now, if you want you can hire me to create a code sample and the necessary updates to submit a URL to the encoder

If you are interested, please submit the details to developer@youphptube.com
