### ISSUE TITLE
Collapse description content

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#4145]
I suggest finalizing: collapse the content of the description. see screenshot
and here is the link: https://demo.avideo.com/video/220/nextcloud

<a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/12/8/c5738521993e9f094c7c8017ec8ec4aa-full.jpg" border="0"/></a>

**Comment by akhilleusuggo** [comment]
Asked for same thing , and was ignored 👎 
https://github.com/WWBN/AVideo/issues/2528

**Comment by palich91** [comment]
there is a problem, see for yourself: https://demo.avideo.com/video/242/avideo1080hd

**Comment by DanielnetoDotCom** [comment]
what problem?

I do not see any

**Comment by palich91** [comment]
the text is displayed not all and crooked
<a href="https://savepice.ru" target="_blank" title="хостинг картинок"><img src="https://cdn1.savepice.ru/uploads/2020/12/8/9e3ca225151fe6d3991f7d81dc122706-full.jpg" border="0"/></a>

**Comment by DanielnetoDotCom** [comment]
Of course, 

there is no space in the text.
what behaivor do you expect?

can you test it on youtube and see how they do?

if they do differently we will follow it

**Comment by palich91** [comment]
you need to make a spoiler (collapse - expand the text)

**Comment by DanielnetoDotCom** [comment]
I sent an update to it 

![image](https://user-images.githubusercontent.com/18009293/101494487-29fef200-3946-11eb-8dc8-7e242a120e32.png)

The demo is not up to date yet, but you already have **show more/less**

**Comment by palich91** [comment]
thanks

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Sorry for the late reply . Works as expected . Thank you.

**Comment by riton75** [comment]
@DanielnetoDotCom show more/less button is a nice enhancement.
It is not possible to translate the button text ? is it possible to add texts in translation files ?

**Comment by akhilleusuggo** [comment]
@riton75 

https://github.com/WWBN/AVideo/blob/7c13cebea7141d013367cd8d747126f5635620f4/view/modeYoutubeBottom.php#L282

https://github.com/WWBN/AVideo/blob/7c13cebea7141d013367cd8d747126f5635620f4/view/modeYoutubeBottom.php#L283

**Comment by riton75** [comment]
Thank you for your answer @akhilleusuggo.
I had those 2 lines at the end of /locale/fr.php (French)
`$t['Show More'] = "Voir plus";
$t['Show Less'] = "Voir moins";`

**Comment by akhilleusuggo** [comment]
Is it working or not ?

**Comment by riton75** [comment]
> Is it working or not ?
@akhilleusuggo Yes it is working fine,

**Comment by akhilleusuggo** [comment]
nice 👍
