### ISSUE TITLE
Meeting plugin

### ISSUE THREAD

**Issue by karthikindia** [WWBN/AVideo#4146]
Need to know if there is any meeting plugin or screenshare plugin compatible with youphptube.
I saw a.zoom cloud recording fetching plugin is there.
Will this plugin satisfy my requests.

**Comment by DanielnetoDotCom** [comment]
Please check this

![image](https://user-images.githubusercontent.com/18009293/101492892-0d61ba80-3944-11eb-942c-7b20faa0f7d2.png)

**Comment by karthikindia** [comment]
This is customised jitsi
But I am looking for an option of rtmp with such meeting tool

**Comment by karthikindia** [comment]
This supports only youtube will it support custom rtmp?

**Comment by DanielnetoDotCom** [comment]
If you are using our meet servers, you will RTMP to your AVideo site 

![image](https://user-images.githubusercontent.com/18009293/101498883-5d904b00-394b-11eb-951c-e7d48c6da921.png)

**Comment by karthikindia** [comment]
1. Can i see a demo.
2. What is the price of the plugin

**Comment by DanielnetoDotCom** [comment]
If you are running the latest AVideo you already have it

https://github.com/WWBN/AVideo/wiki/Meet-Plugin

![image](https://user-images.githubusercontent.com/18009293/101505654-5705d180-3953-11eb-8ef0-4a07a8923a15.png)

**Comment by karthikindia** [comment]
![image](https://user-images.githubusercontent.com/6324834/101586039-12d40900-3a07-11eb-98f8-a98d7b92db76.png)
unable to start live stream.
do i need to configure any parameters ?

**Comment by karthikindia** [comment]
![image](https://user-images.githubusercontent.com/6324834/101586457-fab0b980-3a07-11eb-96db-37ae6c44e297.png)
when we embed iframe its prompting for username and password 
what should i give here ?
i tried avideo portal user and password does not work ?

**Comment by DanielnetoDotCom** [comment]
> unable to start live stream.

Is your livestream server working properly?

> when we embed iframe its prompting for username and password

what link are you embeding?
I am not sure if it works

**Comment by karthikindia** [comment]
Live stream working in my avideo portal channel only not starting from
meeting plugin

Embed code is already in the settings pop-up menu. That is causing the
login prompt

**Comment by karthikindia** [comment]
![Screenshot_20201210_010658_com android chrome](https://user-images.githubusercontent.com/6324834/101678847-8831ef00-3a84-11eb-9edf-a934c09de4ad.jpg)

**Comment by DanielnetoDotCom** [comment]
This embed code will not work, I will remove this button in the future

**Comment by karthikindia** [comment]
live streaming working fine after restart nginx service
you can close the thread, if none others have any questions
thanks

**Comment by karthikindia** [comment]
thanks to all
