### ISSUE TITLE
Turn off chat in app? 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#4147]
Can this be turned off in android app?
![Screenshot_20201208-122803_Fakeotube.jpg](https://user-images.githubusercontent.com/66537018/101519208-e78ee280-3950-11eb-9ccb-d7af2701f1fd.jpg)

**Comment by DanielnetoDotCom** [comment]
Sorry for the late reply

DId you try this?

![image](https://user-images.githubusercontent.com/18009293/102629694-3b0be800-412a-11eb-9198-3dba2c65a3c3.png)
