### ISSUE TITLE
Encoder 1080p

### ISSUE THREAD

**Issue by lahaj** [WWBN/AVideo#4148]
Hello, I subscribe with you and I took a server from you and everything is fine. I am a committed customer with you, but I have two comments and I hope you will solve it
1- I upload videos in 1080 format, and when Encoder creates several formats for the video, it has a higher resolution of 720, and this thing I bothered about frankly because I expected otherwise that the Encoder will convert it to the highest resolution 720 and I discovered this thing in a short time, please solve this thing

[
![Encoder](https://user-images.githubusercontent.com/71000399/101568095-76e8d400-39eb-11eb-9c49-0a723d1b63e8.jpg)
](url)

2- Concerning Embed for the video, I want to hide the video title, hide the title, and share while pressing the mouse button from the right.
Thank you very much, wait for the response, Muhammad bin
The site is ooogel.com

**Comment by tonuzo** [comment]
If you have your own encoder, you can change the parameters in configurations tab:

![image](https://user-images.githubusercontent.com/63721378/101613521-8597b100-3a14-11eb-8c8f-3ca94ed8623a.png)

**Comment by DanielnetoDotCom** [comment]
If you are using the latest encoder version you have the option for With the automatic resolution encoding, we will automatically convert the video to the following resolutions.

- 2160p
- 1440p
- 1080p
- 720p
- 480p
- 360p
- 240p

But, to make sure we will not waste disk space and bandwidth we will examine the file source, before encoding, and we will not upconvert the video.

for example, if you upload a 720p video, we will only convert it into 720p, 480p, 360p, and 240p so it will guarantee the best experience for your users. even a slower connection will be able to play a 240p video and also we will not waste your resources.

**Comment by lahaj** [comment]
Thank you very much for your response. Previously, I told you that my experience is very weak in the Ubuntu server to the point that I did not know how to update the script, so I updated it through the commands that you placed and regarding the encoder as shown in the pictures that I used and I looked for what you said, but I did not find the options in encode
![Encoder1](https://user-images.githubusercontent.com/71000399/101652395-9f0e1c80-3a57-11eb-849b-6a77255dbda0.jpg)
![Encoder2](https://user-images.githubusercontent.com/71000399/101652401-a03f4980-3a57-11eb-9901-a5b751f01929.jpg)


I ask you to clarify more so that I can solve this issue, or if you do not mind that you help me in that because of my lack of experience, please help

**Comment by DanielnetoDotCom** [comment]
we are in encoder v 3.3

you can update the encoder with the same `git pull` command into the encoder directory

**Comment by lahaj** [comment]
I will try, but if I don’t succeed I will come back to you, thank you very much
Please do not close the ticket
Regarding my second question
How can I hide the video embed and the URL's URL, knowing that I went to the settings and did not succeed
![Encoder3](https://user-images.githubusercontent.com/71000399/101655864-87d12e00-3a5b-11eb-8f2b-3ab621065651.jpg)

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/101658405-bf23e880-3a23-11eb-8650-a64bb9cfd2d2.png)

**Comment by lahaj** [comment]
Thank you very much for this help. The update succeeded for me and everything is fine, but I have a note
I uploaded a 1080p video
But after converting it was in 720p resolution and tried several times to change the video, but the same thing
And the videos that they tried were all in 1080p, and after the conversion it changed to 720p

**Comment by lahaj** [comment]
I'm sorry for the discomfort
Please respond to me about what I wrote above

**Comment by DanielnetoDotCom** [comment]
It depends on your encoder configuration. If you are not using the automatic resolution encoding this is expected.

share some screenshots (encoder and streamer) to help us understand.

**Comment by lahaj** [comment]
These are two pictures for illustration
The first image from my website, which I took from you, and after I updated the script and encoder
I tried several times to upload a 1080p video to the original version
Encoder converts 720p video at the highest resolution, not 1080p
Note that the video is 1080p
And I did another experiment on Google Drive and Google Drive converted the video to its original resolution of 1080p as you can see 
which is the same video that I uploaded on my site and uploaded it to Google Drive
![Encoder4](https://user-images.githubusercontent.com/71000399/101932410-27292900-3bf4-11eb-82e9-83db5710686a.jpg)
![Encoder5](https://user-images.githubusercontent.com/71000399/101932419-2b554680-3bf4-11eb-9adc-98d4d5714509.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi


I guess the encoder is not detecting your video as 1080.

the encoder will not up convert videos

**Comment by lahaj** [comment]
So what is the solution for the encoder to encode a video with the same resolution?

**Comment by lahaj** [comment]
Because as far as I know, any encoder encrypts the video according to the video. If the video is 1080 resolution, it encodes it to the same resolution and then encodes it to the lowest resolution.

**Comment by DanielnetoDotCom** [comment]
We use ffprobe to get the video resolution before decide what resolution to encode

https://github.com/WWBN/AVideo-Encoder/blob/56929ae3e5042cbef862c1e6e49067a4950c7394/objects/Format.php#L298

You may want to upload this video to your server and use this command to see why is it returning a version lower then 1080

Use this command: `ffprobe -v quiet -print_format json -show_format -show_streams '$pathFileName'`

**Comment by lahaj** [comment]
Frankly, I did not understand any of this. Please help me
![Encoder6](https://user-images.githubusercontent.com/71000399/101944516-46c94d00-3c06-11eb-87f3-8b4c6e747e90.jpg)

**Comment by DanielnetoDotCom** [comment]
you should replace $pathFileName with your video path.

**Comment by lahaj** [comment]
And where to change it, the script is very complex, although it is very easy for others, and the reason for that is that I do not understand the Ubuntu server. I know that the solution is very simple, but I do not understand it sir

**Comment by DanielnetoDotCom** [comment]
you should not change the script.

I suspect your video is not 1080p or your ffprobe is detecting it wrong. I need to see the result.

You also can share your video here, so I can download it and check

**Comment by lahaj** [comment]
This link is the original version of the 1080 video, which I uploaded to my site

https://mixsoug.com/videos/Mariah.Careys.Magical.Christmas.Special.2020.1080p.WEBRip.x264.AAC5.1.mp4     

This is the second video link that Encoder encrypted

https://ooogel.com/videos/_YPTuniqid_5fd1bcbc615ad2.70365469_720.mp4

**Comment by DanielnetoDotCom** [comment]
As I suspect, this video is NOT 1080p

![image](https://user-images.githubusercontent.com/18009293/101951235-7449d280-3bd5-11eb-82b8-2f11b4402124.png)

**Comment by lahaj** [comment]
I will give it a try and think it will work
Thank you very much for your patience with me and I will get back to you soon
