### ISSUE TITLE
Videos stop playing after a few hours

### ISSUE THREAD

**Issue by ermitchell78** [WWBN/AVideo#4150]
When I upload videos they play as they should for only a couple hours. When they are idle for more than 6 hours they will no longer play. New videos will play until they have sat idle then they refuse to play as well. I am using the AWS s3 plugin, The only error I can see in the log that could be associated with the issue is this:
 [09-Dec-2020 09:08:45 Africa/Abidjan] PHP Warning:  Division by zero in path/to/my/streamer/site/plugin/AWS_S3/AWS_S3.php(14) : eval()'d code(1) : eval()'d code on line 212

I am not sure if this has anything to do with it or not. Could someone point me in the right direction to get this resolved.

**Comment by DanielnetoDotCom** [comment]
Hi, this log has nothing to do with the issue

try to clear your cache and play again.

If it does not play provide a more complete log file

**Comment by ermitchell78** [comment]
The cache seemed to fix it. Thanks for the help
