### ISSUE TITLE
Short Term Solutions To Accommodate More Viewers

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4151]
I am not currently able to add more servers into the mix (financial constraints), but I would like to know what I can do to accommodate ore viewers to my AVideo setup.

I am currently able to accommodate 8-10 viewers and then people start reporting that they can not connect to the stream.
I am currently using Restream.io to broadcast to Facebook, Youtube, Dlive, Perscope, and Twitch, but a large part of the reason I setup an AVideo server was to allow people to congregate together ... keeping up with all of the those chats while streaming is quite difficult ... I had hoped that I could stream to a couple hundred people at a time and assumed that to be the case. I am disappointed that the max I can get in a stream is 8-10 people.

I want to know, is there anything I can do that would accommodate more viewers for a livestream ... I do have access to a VPS in the event that it would be helpful in this scenario.

Thanks in advance for any guidance or advice.

**Comment by DanielnetoDotCom** [comment]
Hi

what resolution are you streaming?
you can try to use the [adaptive bitrate](https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream), I guess with it on you should be able to handle a lot more. also, you can set up the max resolution to be 480p instead of 720p

**Comment by DanielnetoDotCom** [comment]
Another important thing is to tune your apache

https://github.com/WWBN/AVideo/wiki/Speed-up-your-page#tuning-your-apache-server

I can do it for you if you want.

**Comment by bbyrdhouse** [comment]
I have a lot of people that watch on their TV and streaming at 480 is not an option for me. I might be willing to stream at 590 but I don't want to do lower, simply because the quality of video is too poor at 480.

I will look into the Apache tuneup and report back if I need your help.

Thanks

**Comment by bbyrdhouse** [comment]
Here is what it told me ... 

```
Settings considered for this report:
	Your server's physical RAM:                                   15913 MB
	Remaining Memory after other services considered:             15464 MB
	Apache's MaxRequestWorkers directive:                         150      <--------- Current Setting    
	Apache MPM Model:                                             prefork
	Largest Apache process (by memory):                           24 MB
[ !! ] 	Your MaxRequestWorkers setting is too low.
	Your recommended MaxRequestWorkers setting is between 567 and 630.     <-- Acceptable Range (90-100% of Remaining RAM)
	Max potential memory usage:                                   3681 MB
	Percentage of TOTAL RAM allocated to Apache:                  23.14  %
	Percentage of REMAINING RAM allocated to Apache:              23.81  %
```
based on that ... what changes should or could be made?

**Comment by DanielnetoDotCom** [comment]
yes, increase it to at least 600

you will be able to handle a lot of more requests

make sure you restart apache when you finish

**Comment by bbyrdhouse** [comment]
It tells me that 
`[ File '/etc/apache2/mods-enabled/mpm_prefork.conf' is unwritable ]`

I don't know how to fix that

**Comment by DanielnetoDotCom** [comment]
It must be made by command line, I will do it for you

**Comment by bbyrdhouse** [comment]
I was doing it in terminal
<img width="570" alt="Screen Shot 2020-12-09 at 1 51 46 PM" src="https://user-images.githubusercontent.com/7376298/101679999-af0d0880-3a25-11eb-937e-070fa9e19581.png">

**Comment by DanielnetoDotCom** [comment]
I just did for you.

you must add sudo before the command.

for example `sudo nano /etc/apache2/mods-enabled/mpm_prefork.conf`

**Comment by bbyrdhouse** [comment]
Ok ... thanks
Do I still need to restart Apache?

**Comment by DanielnetoDotCom** [comment]
No, you are all set.

Now just take care of your live stream output

**Comment by bbyrdhouse** [comment]
Out of curiosity ... how many viewer can I realistically expect with my current setup at 720 and then at 590?
I am sure there is a formula where i could figure it out on my own, but I don't know what that would be.

**Comment by DanielnetoDotCom** [comment]
Should be a formula, but I definitely do not know

**Comment by bbyrdhouse** [comment]
LOL ... ok thanks

**Comment by syldri** [comment]
Hello @DanielnetoDotCom 

![image](https://user-images.githubusercontent.com/39193219/101681324-45f7b600-3a62-11eb-8efb-358a54505e51.png)


and I put that tell me this is it good?



![image](https://user-images.githubusercontent.com/39193219/101681581-a5ee5c80-3a62-11eb-9498-ec55420735f3.png)

**Comment by DanielnetoDotCom** [comment]
@syldri make your` MaxRequestWorkers 15000`

Currently, you made only 1500

**Comment by syldri** [comment]
Thank you very much
