### ISSUE TITLE
index.m3u8 - 404 Not Found [Live]

### ISSUE THREAD

**Issue by julzxcapz** [WWBN/AVideo#4152]
Hi!

I'm having issue where live (not working), the file is continuously running. Any help please, Thanks!

![plugin_live_page](https://user-images.githubusercontent.com/61785146/101653639-7fd4b680-3a7a-11eb-9990-e8223b6517b4.PNG)

avideo.log
![avideo_log](https://user-images.githubusercontent.com/61785146/101653645-8105e380-3a7a-11eb-8b88-5444fa83fa0c.PNG)

**Comment by DanielnetoDotCom** [comment]
Please again read your logs

![image](https://user-images.githubusercontent.com/18009293/101655351-4a02e400-3a20-11eb-928c-b11c1bb746d4.png)

Currently, you are not transmitting anything so I cannot confirm, but make sure you are using the correct live

for example if your **RTMP Server URL** = rtmp://avideo.com/**live2**

your **Player URL** parameter into the Live plugin must be https://avideo.com:444/**live2**

![image](https://user-images.githubusercontent.com/18009293/101655881-e0370a00-3a20-11eb-81d3-a2ecc18acca1.png)

**Comment by julzxcapz** [comment]
This is working before. I haven't done anything yet on this aside from updating the version. Also I have another new setup that have the same issue but no logs generated

**Comment by julzxcapz** [comment]
Sorry. It's working now I did clear cache too. Thank you!

**Comment by DanielnetoDotCom** [comment]
So try to restart nginx, also check the folder permissions in the /HLS/live

**Comment by julzxcapz** [comment]
Yes, thank you again!
