### ISSUE TITLE
Encoder Version?

### ISSUE THREAD

**Issue by willpower68** [WWBN/AVideo#4154]
How do you check the Encoder version and how do you update Encoder?

  

![image](https://user-images.githubusercontent.com/739391/101709058-b8659780-3a5c-11eb-826f-445643fc761f.png)

**Comment by DanielnetoDotCom** [comment]
Looks like you are not admin

Please check this video https://tutorials.avideo.com/video/109/make-an-encoder-administrator-user

**Comment by willpower68** [comment]
@DanielnetoDotCom I am admin.  maybe this is why I can't upload new videos.

**Comment by willpower68** [comment]
@DanielnetoDotCom 
/var/www/html/YouPHPTube-Encoder/install$ php makeAdmin
it returns "no such file or director".  

It tried this as well
 /var/www/html/YouPHPTube-Encoder/install/makeAdmin.php: Permission denied

**Comment by DanielnetoDotCom** [comment]
you suppose to type

`php makeAdmin.php`

NOT

`php makeAdmin`

**Comment by willpower68** [comment]
Hi @DanielnetoDotCom thanks for replying.  I made correction and still getting 'no such file or directory


![image](https://user-images.githubusercontent.com/739391/101937820-5d44b980-3bb0-11eb-9286-b8e1e8f43a71.png)

**Comment by willpower68** [comment]
@DanielnetoDotCom thanks for replying.  I'm still getting the same response.
![makeAdmin](https://user-images.githubusercontent.com/739391/101938421-4bafe180-3bb1-11eb-80fb-a6b6c800d494.png)

**Comment by DanielnetoDotCom** [comment]
That means your encoder is outdated.

make a `git pull`

then run the makeAdmin command

**Comment by willpower68** [comment]
@DanielnetoDotCom 
I want to make sure I understand.  I'm currently running 10.0 and still need to do a git pull for the encoder?

is this correct or is there another command for the encoder?
cd /var/www/html/YouPHPTube/ && sudo git pull

**Comment by DanielnetoDotCom** [comment]
Encoder is version 3.3 now

Streamer is version 10.0

For the encoder I guess your command is 

`cd /var/www/html/YouPHPTube/Encoder && sudo git pull`

**Comment by willpower68** [comment]
@DanielnetoDotCom 
There is no Encoder directory

**Comment by DanielnetoDotCom** [comment]
It should be somewhere, you must find it.

**Comment by willpower68** [comment]
@DanielnetoDotCom ok, I will check all the folder

**Comment by willpower68** [comment]
@DanielnetoDotCom 
I did not find Encoder directory in YouPHPTube site 1 but YouPHPTube site 2 (they are not sharing encoder) has Encoder directory.  Should copy that file to site 2?

**Comment by DanielnetoDotCom** [comment]
try on the site 2

**Comment by willpower68** [comment]
@DanielnetoDotCom 
site 2 encoder is up to date however not able to create the _**'admin'**_


cd /var/www/html/YouPHPTube-Encoder/install$ php makeAdmin.php
not file or directory

I noticed the _install directory does not have **'$'** but I tried with and without and got the same response _not file or directory_

**Comment by DanielnetoDotCom** [comment]
I just notice, you should make a git pull in your YouPHPTube-Encoder dir

`cd /var/www/html/YouPHPTube-Encoder/ && sudo git pull`

**Comment by willpower68** [comment]
@DanielnetoDotCom 

Problem:  Encoder not up to date.  

Solved:
![image](https://user-images.githubusercontent.com/739391/101955758-63489380-3bcc-11eb-8603-e3085641b580.png)

Problem: Admin can not upload video file to encoder.

![image](https://user-images.githubusercontent.com/739391/101955231-73ac3e80-3bcb-11eb-816a-e1440b34929f.png)


![image](https://user-images.githubusercontent.com/739391/101955484-e87f7880-3bcb-11eb-9464-cdc23e1967af.png)



not clear on what git pull for YouPHPTube-Encoder dir is going to to but it gave me same results.  Admin is not able to upload video to encoder

![image](https://user-images.githubusercontent.com/739391/101955025-11ebd480-3bcb-11eb-8f0d-1d57dbd26c81.png)

**Comment by akhilleusuggo** [comment]
that mean you haven't install AVideo via git , maybe ftp/sftp .
And for sure this is an old installation . New installation are under the name AVideo-Encoder and not YouPHPTube-Encoder .

**Comment by willpower68** [comment]
@akhilleusuggo 
thanks!  I didn't know.  Hopefully, I can figure out how to update encoder.

**Comment by willpower68** [comment]
@DanielnetoDotCom 
@akhilleusuggo 

I am not sure what to do at this point.  I assume the git pull for Avideo-Encoder was  cd /var/www/html/Avideo-Encoder/ && sudo git pull

Obviously that not going work because I don't have any Avideo-Encoder directories.  
Where do I download the Avideo-Encoder directory?  Can you also provide link on installation?

**Comment by willpower68** [comment]
@DanielnetoDotCom  Will this link provide information I need for latest encoder?  is it best to use sftp or git pull?
https://github.com/WWBN/AVideo-Encoder

**Comment by DanielnetoDotCom** [comment]
Hi, I am pretty sure you already have it, you just need to update with the "git pull"

**Comment by willpower68** [comment]
@DanielnetoDotCom I'm sure you are correct.  My lack of knowledge in this are is frustrating.  I looked for AVideo-Encoder directory and I only have YouPHPTube-Encoder

Should rename YouPHPTube-Encoder directory to AVideo-Encoder and add updated AVideo-Encoder files to directory via sftp?

**Comment by willpower68** [comment]
@DanielnetoDotCom 
@akhilleusuggo 

**What am I doing incorrectly?**

Last login: Mon Dec 14 14:48:08 2020 from 
root@:~# cd /var/www/html/AVideo-Encoder/ && sudo git pull
fatal: Not a git repository (or any of the parent directories): .git
root@ :/var/www/html/AVideo-Encoder#

**Comment by DanielnetoDotCom** [comment]
Correct looks like it is not a git repository

you must install it using `git clone` command

**Comment by willpower68** [comment]
@DanielnetoDotCom 
is this it?
cd /var/www/html/AVideo-Encoder/ && git clone
and then do  git pull command?
cd /var/www/html/AVideo-Encoder/ && git pull

**Comment by akhilleusuggo** [comment]
you need to clone the repository . Please check the wiki guide of the installation process

**Comment by willpower68** [comment]
@DanielnetoDotCom  @akhilleusuggo 
is this tutorial video still valid today?

https://tutorials.avideo.com/video/streamer-and-encoder

**Comment by DanielnetoDotCom** [comment]
Probably yes

**Comment by willpower68** [comment]
@DanielnetoDotCom 

will this tutorial help me solve my problems with encoder?
https://tutorials.avideo.com/video/streamer-and-encoder

**Comment by akhilleusuggo** [comment]
Those are the basics . But if you're not willing to dedicate 5mn to read the wiki , I don't think you will have a great experience with this project .

Take a look , it's a copy/past https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer

**Comment by willpower68** [comment]
@DanielnetoDotCom @akhilleusuggo 
thank you for the advice.  I have been reading wiki for the past 2 days to get a better understanding.

**Comment by willpower68** [comment]
@DanielnetoDotCom @akhilleusuggo 
I am attempting to set up the encoder but I got these errors.  Can you tell me what they mean?


Err:20 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 libp                                                                                                                                                             ostproc55 amd64 7:4.3-2~16.04.york1
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:21 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 liba                                                                                                                                                             vformat58 amd64 7:4.3-2~16.04.york1
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:22 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 liba                                                                                                                                                             vcodec58 amd64 7:4.3-2~16.04.york1
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:23 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 libs                                                                                                                                                             wresample3 amd64 7:4.3-2~16.04.york1
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:24 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 liba                                                                                                                                                             vutil56 amd64 7:4.3-2~16.04.york1
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Get:25 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 libs                                                                                                                                                             rt1-gnutls amd64 1.4.1-5~16.04.york0 [242 kB]
Get:26 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 libm                                                                                                                                                             ysofa1 amd64 1.0~dfsg0-2~14.04.york0 [38.8 kB]
Get:27 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 libx                                                                                                                                                             265-192 amd64 3.4-0york0~16.04 [1097 kB]
Fetched 4047 kB in 6s (634 kB/s)
E: Failed to fetch http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu/pool/main/                                                                                                                                                             f/ffmpeg/ffmpeg_4.3-2~16.04.york1_amd64.deb  404  Not Found [IP: 2001:67c:1560:8                                                                                                                                                             008::19 80]

**Comment by akhilleusuggo** [comment]
My question is , what guide are you following ? Because for me this looks like you're following some external guide . if it's the case , open the support ticket there .

Related to your issue , your host is not able to solve the repository of ffmpeg . Apt-get install ffmpeg should server most of the needs . If not compile it by yourself ( follow guide on official website of ffmpeg ).

You need to remove the custom repository that you have added ( ffmpeg 4.x ) , then try to install ffmpeg in a normal way . Or update the repository .

Also looks like you're trying to solve the IP via IPv6 . Try with IPv4 .

404 Not Found [IP: 2001:67c:1560:8 008::19 80]

**Comment by willpower68** [comment]
@akhilleusuggo thank you.  I will submit a support ticket.  This is beyond my skill set.
