### ISSUE TITLE
Removing foreign languages

### ISSUE THREAD

**Issue by dbmasters** [WWBN/AVideo#4155]
I want to disable everything except US English and remove the selection box. Is there a configuration option to do that, or is it hacking the theme?

**Comment by DanielnetoDotCom** [comment]
As long as you will only use one language you may want to set it up here 

![image](https://user-images.githubusercontent.com/18009293/101784510-5d728580-3ada-11eb-9c77-2d946b7b1802.png)

then hide the lang dropdown switcher with CSS

```
#navBarFlag{
    display:none;
}
```

![image](https://user-images.githubusercontent.com/18009293/101784845-cce87500-3ada-11eb-9c67-729eb8993ee6.png)

**Comment by dbmasters** [comment]
Awesome, just wanted to make sure it wouldn't break something else.

Much appreciated.
