### ISSUE TITLE
Security Issues and Warnings from Log ... Need Advice

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4156]
**Describe the question**
Starting on yesterday, I noticed that I was having trouble with a video file where i would upload it and it would never play. I would delete it and then re-upload it and the same thing. I did this several times using both direct upload and encoding.
So I decide to go look at the error logs and saw that I had **649 errors that need attention** ... plus 22 PHP warnings ... (images attached).

Further down, where you can expand or collapse the errors ... here is a typical message:

``` [10-Dec-2020 06:24:39 America/Chicago] AVideoLog::DEBUG: Bot stopped SCRIPT_NAME: /view/robots.txt.php
#2 [10-Dec-2020 06:24:39 America/Chicago] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/robots.txt) FROM: 54.236.253.7 Browser: Mozilla/5.0 (compatible; proximic; +http://www.proximic.com/info/spider.php) SCRIPT_NAME: /view/robots.txt.php
#3 [10-Dec-2020 06:24:39 America/Chicago] AVideoLog::DEBUG: Bot stopped SCRIPT_NAME: /view/robots.txt.php
#4 [10-Dec-2020 06:24:39 America/Chicago] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/robots.txt) FROM: 54.236.253.7 Browser: Mozilla/5.0 (compatible; proximic; +http://www.proximic.com/info/spider.php) SCRIPT_NAME: /view/robots.txt.php 

 [09-Dec-2020 22:12:39 America/Chicago] AVideoLog::SECURITY: ddosProtection:: progressive timeout timeoutReal = (5) active_connections = (40) maxCon = (40)  SCRIPT_NAME: /view/xsendfile.php```

[09-Dec-2020 22:05:17 America/Chicago] AVideoLog::DEBUG: isTokenValid: rawToken eyJzYWx0IjoiaHR0cHM6XC9cL3RoZXBhdHJpb3QubmV0d29ya1wvIiwidG9rZW5UaW1lT3V0IjoyMTYwMCwiZmlsZW5hbWUiOiJfWVBUdW5pcWlkXzVmY2FiNzE4MDgzMTEwLjM0MjQ4Mzc4X0hEIiwidGltZSI6MTYwNzU2OTIxMH0=?download=1 SCRIPT_NAME: /view/xsendfile.php
#416 [09-Dec-2020 22:05:17 America/Chicago] AVideoLog::DEBUG: isTokenValid: Incorrect Salt SCRIPT_NAME: /view/xsendfile.php
[09-Dec-2020 22:05:12 America/Chicago] AVideoLog::SECURITY: ddosProtection:: progressive timeout timeoutReal = (5) active_connections = (40) maxCon = (40)  SCRIPT_NAME: /view/xsendfile.php
[09-Dec-2020 22:05:04 America/Chicago] AVideoLog::SECURITY: ddosProtection:: progressive timeout timeoutReal = (5) active_connections = (40) maxCon = (40)  SCRIPT_NAME: /view/xsendfile.php
[09-Dec-2020 22:04:50 America/Chicago] AVideoLog::SECURITY: ddosProtection:: progressive timeout timeoutReal = (5) active_connections = (40) maxCon = (40)  SCRIPT_NAME: /view/xsendfile.php
```

There are hundreds of these ... ALSO, the ip address mentioned in the first couple of logs (54.236.253.7) is already in a blacklist registry.

<img width="725" alt="Screen Shot 2020-12-10 at 6 25 42 AM" src="https://user-images.githubusercontent.com/7376298/101772967-bbd73e00-3ab1-11eb-9bd5-c0b75f0dc054.png">
<img width="564" alt="Screen Shot 2020-12-10 at 6 25 55 AM" src="https://user-images.githubusercontent.com/7376298/101772979-c0035b80-3ab1-11eb-92c1-d7481b07ecf1.png">

**Comment by bbyrdhouse** [comment]
About 20 of these:
`[08-Dec-2020 17:03:35 America/Chicago] PHP Fatal error:  Uncaught Stripe\Exception\SignatureVerificationException: No signatures found matching the expected signature for payload in path/to/my/streamer/site/plugin/StripeYPT/lib/Exception/SignatureVerificationException.php:28`

a few of these:
` [09-Dec-2020 14:18:36 America/Chicago] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":98,"function":"log_error","args":["Error in writeSql : (1062) Duplicate entry '239' for key 'category_type_cache.categoryId', SQL-CMD:INSERT INTO `category_type_cache` (`categoryId`, `type`) VALUES (?, ?);"]},{"file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":470,"function":"writeSql","class":"sqlDAL","type":"::","args":["INSERT INTO `category_type_cache` (`categoryId`, `type`) VALUES (?, ?);","ii",[239,99]]},{"file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":329,"function":"autosetCategoryType","class":"Video","type":"::","args":[239]},{"file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1225,"function":"save","class":"Video","object":{"views_count_25":0,"views_count_50":0,"views_count_75":0,"views_count_100":0,"created":"2020-12-09 14:18:36","modified":"2020-12-09 14:18:36","order":1},"type":"->","args":[false,true]},{"file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":779,"function":"updateFilesize","class":"Video","type":"::","args":[239]},{"file":"\/var\/www\/html\/AVideo\/objects\/videoAddNew.json.php","line":134,"function":"getVideo","class":"Video","type":"::","args":[239,"",true]}] SCRIPT_NAME: /objects/videoAddNew.json.php
`

**Comment by DanielnetoDotCom** [comment]
Hi, 


1. as long as you are using HLS format I have to ignore the xsendfile.php on DDOS detection.
this is not a security issue, this behavior is expected. I will send an update soon.

2. About SignatureVerificationException
if you are using stripe, please make sure you get the correct Signing secret on the webhooks 

![image](https://user-images.githubusercontent.com/18009293/101777640-8d695b00-3ad1-11eb-8969-27aca85f80bb.png)

3. regarding MySQL error for category_type_cache I recently have submitted a fix for that.

**Comment by bbyrdhouse** [comment]
Thanks for the feedback.

WRT Stripe, I've been using them for more than 10 years now and the Signing Secret is relatively new, as a matter of fact, this is the first website I have had to create a signing secret for (always before the public and private keys were enough)

I did create a signing secret and so far as I know I have used it properly ... 

![stripe-sign-secret](https://user-images.githubusercontent.com/7376298/101781034-ee3a6880-3abc-11eb-8ef5-d4f440b73196.png)
![sign-secret-2](https://user-images.githubusercontent.com/7376298/101781076-fe524800-3abc-11eb-8dac-da7a612cf40e.png)

**Comment by DanielnetoDotCom** [comment]
We need the webhook so Stripe will tell the site the transaction happen, and the key is the way we have to validate this comes from Stripe.

so make sure this is correct.
