### ISSUE TITLE
Avideo Screen problems

### ISSUE THREAD

**Issue by mario-evangelista-silva** [WWBN/AVideo#4157]
I'm using avideo with docker and letsencrypt-nginx-proxy-companion image. When I access the video, the image is unformatted. With F12 I see a message that "Blocked loading of merged active content" and the message "Loading mixed (unsafe) content". 
Any tips on how to solve this problem?
In my docker-compose I applied the directives VIRTUAL_HOST, LETSENCRYPT_HOST and LETSENCRYPT_EMAIL.

**Screenshots**
![image](https://user-images.githubusercontent.com/75388764/101781007-0b2f6580-3ad6-11eb-8009-eb05b54a8f3b.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I am not aware of avideo docker.

but check your source code. maybe is something you will need to edit in your configuration.php file.

**Comment by mario-evangelista-silva** [comment]
You're right.
I changed the configuration.php file in the docker image directory at /var/www/avideo/videos/configuration.php and changed from "http" to "https" in the following excerpt

  $ global ['webSiteRootURL'] = **http** ".! empty ($ _ SERVER ['HTTPS'])?" s ":" ").": // ". $ _ SERVER ['SERVER_NAME']. $ subDir;
for
  $ global ['webSiteRootURL'] = **https** ".! empty ($ _ SERVER ['HTTPS'])?" s ":" ").": // ". $ _ SERVER ['SERVER_NAME']. $ subDir;

Congratulations, you are really good

**Comment by DanielnetoDotCom** [comment]
great, I am glad it is working

**Comment by mario-evangelista-silva** [comment]
Problem solved.
thanks to @DanielnetoDotCom
