### ISSUE TITLE
Insert html code on sites

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#4158]
I offer a simple but useful function for AVideo: insert html code into sites

Here's a simple but useful feature for AVideo: embed html code into websites.
**For example:** here is a video https://demo.avideo.com/video/242/avideo1080hd?page=1
 **we take a screenshot from it:** `<img src="https://demo.avideo.com/videos/_YPTuniqid_5df930488b13b8.76092593.jpg?1607605307" alt="avideo1080hd" class="img img-responsive  rotate0" height="130" itemprop="thumbnail">`
**Title:** avideo1080hd
**and link** https://demo.avideo.com/video/242/avideo1080hd?page=1
**we get the code:** `<a href="https://demo.avideo.com/video/242/avideo1080hd?page=1"><img src="https://demo.avideo.com/videos/_YPTuniqid_5df930488b13b8.76092593.jpg?1607605307" alt="avideo1080hd" class="img img-responsive  rotate0" height="130" itemprop="thumbnail"><br>avideo1080hd</a>`

Now it is possible to share html-code for sites

You can use it here:
![555555](https://user-images.githubusercontent.com/54632469/101781906-bde5df00-3b3b-11eb-8004-da50fefea4f7.jpg)

**on third-party sites it will look like this:**
![77777](https://user-images.githubusercontent.com/54632469/101782184-0ac9b580-3b3c-11eb-82bb-581e8e0dba84.jpg)

**Comment by palich91** [comment]
@DanielnetoDotCom, I also recommend using the BB code:

`[url=https://demo.avideo.com/video/242/avideo1080hd?page=1][img]https://demo.avideo.com/videos/_YPTuniqid_5df930488b13b8.76092593.jpg?1607605307[/img]avideo1080hd[/url]`

The principle of operation is the same as html code

**Comment by palich91** [comment]
Do you think it doesn't matter?
how can I make such an update myself?
how can I make changes so that everyone can use it

**Comment by DanielnetoDotCom** [comment]
@palich91 I am already working on it

**Comment by DanielnetoDotCom** [comment]
Please check now
