### ISSUE TITLE
Footer and other elements not match themes

### ISSUE THREAD

**Issue by techiesces** [WWBN/AVideo#4160]
I use the customize plugin and the user agreements plugin and they do not follow or take in consideration the themes or custom colors being used within the site.

For example, the footer remains white background with light gray or in some case white font which makes customizing the footer pointless as it is unreadable.  While white font is great if the background color matched the black background of the theme it does not however.

Same for user agreement inline or as a popup.  The background is white and the font is white which makes the dialogue invisible and unreadable.  Attempting to change the text color within the editor has no effect either on the text color within any of the plugins mentioned.

My guess is that the background is remaining white and not following the theme or custom color codes but the font color is changing with the theme, but also ignoring any editor changes.

I personally tried to alter the code within the plugins myself but as a layman when it comes to programming I failed, haha.

**Comment by DanielnetoDotCom** [comment]
you are probably using some hardcoded inline css

It is based on Bootstrap so you can use Bootstrap classes on the tags if you want
