### ISSUE TITLE
OBS won't accept stream URL or key new issue

### ISSUE THREAD

**Issue by mikweb2017** [WWBN/AVideo#4162]
![Bildschirmfoto 2020-12-10 um 22 51 35](https://user-images.githubusercontent.com/30271757/101834287-7579f180-3b3a-11eb-8620-a6f8f2a60692.png)

![Bildschirmfoto 2020-12-10 um 22 53 15](https://user-images.githubusercontent.com/30271757/101834356-8b87b200-3b3a-11eb-89da-299f6048a378.png)

nginx logs

"GET /live/5fd2971d1b8bf.m3u8 HTTP/1.1", host: "my.site.com::444", referrer: "https://my.site.com:/"
2020/12/10 22:46:26 [error] 13740#0: *36 open() "/HLS/live/5fd2971d1b8bf.m3u8" failed (2: No such file or directory), client: 91.6, server: my.site.com:, request: "GET /live/5fd2971d1b8bf.m3u8 HTTP/1.1", host: "my.site.com:444", referrer: "https://my.site.com/"
2020/12/10 22:46:27 [error] 13740#0: *36 open() "/HLS/live/5fd2971d1b8bf.m3u8" failed (2: No such file or directory), client: 91., server: my.site.com:, request: "GET /live/5fd2971d1b8bf.m3u8 HTTP/1.1", host: "my.site.com::444", referrer: "https://my.site.com/"
2020/12/10 22:46:28 [error] 13740#0: *36 open() "/HLS/live/5fd2971d1b8bf.m3u8" failed (2: No such file or directory), client: 91...., server: my.site.com, request: "GET /live/5fd2971d1b8bf.m3u8 HTTP/1.1", host: "my.site.com:444", referrer: "https://my.site.com/"
2020/12/10 22:46:31 [error] 13740#0: *36 open() "/HLS/live/5fd2971d1b8bf.m3u8" failed (2: No such file or directory), client: 91........, server: my.site.com:, request: "GET /live/5fd2971d1b8bf.m3u8 HTTP/1.1", host: "my.site.com::444", referrer: "https://my.site.com/"
any idea i have check ngnix.conf again but i find any error.

**Comment by DanielnetoDotCom** [comment]
check the streamer log at the time you try to connect.

**Comment by akhilleusuggo** [comment]
@mikweb2017 reset your stream-key

**Comment by mikweb2017** [comment]
@akhilleusuggo already done several times
@DanielnetoDotCom there is nothing about it

**Comment by mikweb2017** [comment]
@DanielnetoDotCom with a new installation works then Nginx configuration is correct is there a possibility to delete the tables of the live plugin?

**Comment by DanielnetoDotCom** [comment]
If there is nothing in your streamer log, should be something blocking (or wrong URL) on the on_publish request.

check your nginx.conf

**Comment by mikweb2017** [comment]
??@DanielnetoDotCom with a new installation works then Nginx configuration is correct is there a possibility to delete the tables of the live plugin?

**Comment by DanielnetoDotCom** [comment]
do you mean works on the same nginx?

how can you make the same nginx.conf works in more the one installation?

It is possible, but few people use it.

If you are using the same nginx.conf it is an important information

**Note: I do not teach how to use the same nginx.conf for more than one streamer**

**Comment by mikweb2017** [comment]
yes los same nginx of course I changed the domain and commented the other to test quickly

**Comment by DanielnetoDotCom** [comment]
I guess that means you have a problem in the domain.

**Comment by mikweb2017** [comment]
I don't know I've always done the update via Git pull I think something went wrong in the update I've installed everything on a new domain as mentioned by editing nginx.conf and it works

**Comment by DanielnetoDotCom** [comment]
Make sure you are not redirecting http to https on the on_publish URL

**Comment by mikweb2017** [comment]
no it is not redirect there is however something that does not return in the SSL config I must understand also I have never changed anything...control tomorrow with calm

**Comment by mikweb2017** [comment]
I don't know what happened, I reinstalled everything with a new database and it's working again.
