### ISSUE TITLE
FFMPEG Path

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4163]
@DanielnetoDotCom , @akhilleusuggo greetings

Can you please tell me where in the code I can change the path to ffmpeg please? i recompiled my own and the Encoder won't convert. How can i tell it where to find the new installation?

Thanks guys

**Comment by DanielnetoDotCom** [comment]
I guess the correct way is for you to copy your compiled `ffmpeg ` into `/usr/local/bin/` dir

**Comment by akhilleusuggo** [comment]
you have to move ffmpeg from ( where ever you compiled it )  to /usr/local/bin/ffmpeg so every user could be able to use ( specially apache2 ) .

**Comment by jengajenga** [comment]
Thanks guys. On my test server, I compiled ffmpeg before I started installing the platform. It is working perfectly.
