### ISSUE TITLE
Would a Custom Branded iOS and Android App(s) be Under the Umbrella of AVideo?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4164]
**Describe the question**
I am wondering if a custom branded mobile app be completely ours, meaning that we have to get the $99 Developer account with Apple + whatever Google charges or would they be under the umbrella of AVideo?

There are advantages to both scenarios ... I am just curious

**Comment by DanielnetoDotCom** [comment]
For publishing your app we have 3 options:

1. We can publish for you using our YouPHPTube developer account, (we will charge 1-hour support for each App)
2. You can publish for yourself, for this you would need to acquire/buy with Apple and Google their own developer accounts. If you wish to publish using your developer account, we can send you the Android studio and the XCode (iOS) projects. (No Fee)
3. We can publish for you using your developer account, just share your credentials with us (also extra  1-hour support each App)

Apple iTunes Developer Program is $99 per year, [check here](https://developer.apple.com/programs/),

Android Developer Program is a one-time fee of $25, [check here](https://play.google.com/apps/publish/)

**Comment by bbyrdhouse** [comment]
Wonderful!
I have noticed that using the AVideo app on iOS is a much better experience for the user than using a mobile browser. I will definitely be moving in that direction in the near future.

Thanks
