### ISSUE TITLE
The Plugin Store Only Has Facebook and Google+ Login Now?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4165]
I did not use Facebook or Google plus to create my account at the Plugin store and I have always just logged in using my email address.
Today, however, I noticed that that option is no longer there. How can I access my account on the Plugin Store?

<img width="639" alt="plug_login" src="https://user-images.githubusercontent.com/7376298/101915185-e21cdc80-3b8a-11eb-8108-65a868c213dd.png">

**Comment by DanielnetoDotCom** [comment]
Hi, try this site https://youphp.tube/marketplace/

It supposes to redirect you to there. I will check

**Comment by bbyrdhouse** [comment]
Thnx
