### ISSUE TITLE
Can't upload 667 MB file directly

### ISSUE THREAD

**Issue by mario-evangelista-silva** [WWBN/AVideo#4169]
I am not able to "direct upload" a 667 MB file. I managed to upload files with 12MB and 66MB. 
My php.ini file is configured with 10GB:
post_max_size = 10G
upload_max_filesize = 10G
I don't get any error messages.
Any suggestion?

**Comment by DanielnetoDotCom** [comment]
I am pretty sure you are using Cloudflare

https://github.com/WWBN/AVideo/wiki/About-Video-Upload#cloudflare

**Comment by mario-evangelista-silva** [comment]
I am not using cloudfire. My host is VPS with full root access, with no blocking rules.
I can upload via ssh or ftp normally without problems. Only Avideo's direct upload is not working. I've already done a mapping of the / tmp directory to another directory with 17 GB of disk space.
Do you have any other suggestions?

**Comment by DanielnetoDotCom** [comment]
Check your JS console and network tab

**Comment by mario-evangelista-silva** [comment]
**Problem successfully solved.**

I'm using **avideo with docker** and I also use a nginx proxy with letsencrypt in docker, so I had to change the file **nginx.conf** or **default.conf** or **nginx.tmp**l to the same 10G configuration made in **php.ini**.

In my nginx.conf file I changed all entries with the parameter "client_max_body_size" to 10 GB, making it like this:
**client_max_body_size 10G;**

Remembering that in php.ini I also put:
**file_uploads = On;
post_max_size = 10G;
upload_max_filesize = 10G;
allow_url_fopen = On;
allow_url_include = On;
max_execution_time = 7200**

**_These settings are necessary for avideo with proxy nginx and letsencrypt running in a DOCKER environment._**

**Comment by jengajenga** [comment]
> **Problem successfully solved.**
> 
> I'm using **avideo with docker** and I also use a nginx proxy with letsencrypt in docker, so I had to change the file **nginx.conf** or **default.conf** or **nginx.tmp**l to the same 10G configuration made in **php.ini**.
> 
> In my nginx.conf file I changed all entries with the parameter "client_max_body_size" to 10 GB, making it like this:
> **client_max_body_size 10G;**
> 
> Remembering that in php.ini I also put:
> **file_uploads = On; post_max_size = 10G; upload_max_filesize = 10G; allow_url_fopen = On; allow_url_include = On; max_execution_time = 7200**
> 
> **_These settings are necessary for avideo with proxy nginx and letsencrypt running in a DOCKER environment._**

How have you implemented the platform in a docker environment? can you provide some tips please? 
thanks in advance.
