### ISSUE TITLE
AVideo Thumbnail Image Aspect Ratio & Roku Direct Publisher Requirements

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4170]
I am creating a Roku Channel of my AVideo channel and one of the errors is that it can not download the thumbnails. Researching the Roku docs, it says that thumbnails need to be 16x9 ratio with minimum of 800 x 450.

My question is, what aspect ratio does AVideo use when a user either uploads a video or sends to encoder a recorded video?

If it is something other than 16x9, I wonder if there would be any way that admins could change the aspect ratio to one that would be 16x9 or perhaps a "Roku" plugin could be created that would create an mrss feed with all the necessary things.

https://developer.roku.com/docs/specs/direct-publisher-feed-specs/json-dp-spec.md

**Comment by DanielnetoDotCom** [comment]
Hi, please make sure you have the latest version.

delete all your *roku.jpg and let AVideo recreate it. it was fixed on friday

**Comment by bbyrdhouse** [comment]
I will give it a go ... thanks

**Comment by bbyrdhouse** [comment]
When you say "delete all your *roku.jpg" ... where do you mean specifically? In the videos where I added thumbnails?

**Comment by DanielnetoDotCom** [comment]
The command should be

`rm /var/www/html/AVideo/videos/*roku.jpg`
