### ISSUE TITLE
Discord bot

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#4171]
Daniel can you make a bot like [Fredboat](https://fredboat.com/) so I can play my video audio in discord?

**Comment by DanielnetoDotCom** [comment]
Any idea of how this works?

I have never use discord before. 

can you please make a video of how this works?

**Comment by akhilleusuggo** [comment]
you actually can't do that .
Is something that discord have to implement , not other sources .

**Comment by fakeologist** [comment]
Discord bots are done by independent programmers like Daniel. Fredboat is a bot for youtube videos to be played on its platform. Daniel could make a bot for avideo sites.

**Comment by akhilleusuggo** [comment]
Seems like you don't understand . What you asking ( what you describe ) is not a bot . Is integrating the videojs on discord , to be able to playback videos from discord , without opening them on browser . That is not possible . 
Will be possible only if Discord does integrates that .
Discord bot already exist ( you can check your plugins ) , but will not open a videojs playback .
