### ISSUE TITLE
How to add webpage into YouPHPtube

### ISSUE THREAD

**Issue by techiesces** [WWBN/AVideo#4172]
I would like to add an adserver into my website.  Is there a way to add my adserver to lets say, www.[URL]/ads and where could I load this into my server.

Normally in a webserver you can simply drop files into a folder with respect to the url page name but with this I am not as familiar what to do.  Maybe some guidance would be helpful.

**Comment by akhilleusuggo** [comment]
you can add plugin 'Menu'

**Comment by DanielnetoDotCom** [comment]
For my last customer I suggest hem,  to create hot pages with WordPress. and use AVideo just to host and process videos

**Comment by techiesces** [comment]
@akhilleusuggo I will check that out... thanks for the suggestion!

@DanielnetoDotCom I passionately hate wordpress... haha  Used to use it but everytime there was a php update or wordpress update everything broke.. haha  I hate updates.  Thanks for the suggestion though.  Hopefully the topmenu option is what I am looking for.
