### ISSUE TITLE
Video Uploads Failing Since Last Update

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#4174]
Since November 16th most video uploads are failing. One person complained that he has not managed to get one single video to upload yet. He tried 5 more videos last night and they all failed and left an error in the encoder page.

I paid Daniel to set up my 2nd encoder and it has never worked right yet. He has since updated the original encoder which also no longer works. Before the update I had no errors anywhere for 10 months straight.

If an upload works, often the thumbnails fail to be generated making a mess of the homepage.

Since Nov 16 when the site was updated I went from 350,000 views per month to under 4,000. I am literally losing money now because I was starting to get ads running.

![uploads all messed up](https://user-images.githubusercontent.com/45924889/102102567-f7e40900-3df9-11eb-8dd5-dcb050ffde52.jpeg)

Above is a screen shot of the missing thumbnails.

My site worked perfect before the update and has not worked since.

**Comment by The-Do-It-Yourself-World** [comment]
Update. Another person has had all his videos fail today. Below is a screen shot that he sent me with an error saying that it failed to write to the disk.

![DIYT encoder - failed to write file to disk](https://user-images.githubusercontent.com/45924889/102105377-552d8980-3dfd-11eb-8a44-92c872446419.jpg)

**Comment by DanielnetoDotCom** [comment]
Check if your disk is not full

![image](https://user-images.githubusercontent.com/18009293/102126388-c5ea9b00-3e29-11eb-900f-bf52755dc49a.png)

check your encoder log file

also I try to google for this error https://www.google.com/search?q=upload+fail+to+write+file+to+disk

**Comment by The-Do-It-Yourself-World** [comment]
Its a brand new install I paid you do set up for me. There is a total of 3 GB on the hard drive right now. I have an 80 GB hard drive on that server.

I cannot download the log file and send it to you. Its 320 MB in size and my internet at home is 10 - 200 KB. Yes, KB. It would take me days to get you that file. I can let you have access to the server to get it yourself if you need.

**Comment by DanielnetoDotCom** [comment]
I just login into your encoder, and as I told you, your server is full.

Please if you want me to help you, you must provide honest and precise responses.

![image](https://user-images.githubusercontent.com/18009293/102139235-55994500-3e3c-11eb-8a2d-6d0dc8fe56d1.png)

I can see you deleted the videos that were hanging, that explains why you have 5 GB of space free now

**Comment by The-Do-It-Yourself-World** [comment]
I am not trying to lie to you. I checked and only found 3 GB of files. On an 80 GB hard drive, what is taking up all the space? I cannot find it.

**Comment by DanielnetoDotCom** [comment]
Your /tmp directory is using a lot of space, I do not know why, but a server restart should free this space

![image](https://user-images.githubusercontent.com/18009293/102144182-cee86600-3e43-11eb-873c-d9f8cca15fb3.png)

Something on apache, I guess it was a youtube-dl cache

![image](https://user-images.githubusercontent.com/18009293/102144275-f8a18d00-3e43-11eb-84c8-44a1c8769d8b.png)

**Comment by The-Do-It-Yourself-World** [comment]
Thank you very much. That helps a lot.

**Comment by The-Do-It-Yourself-World** [comment]
Just to show I was not trying to lie to you, here is a screen shot of my listing of the entire HTML directory on the encoder site:

![filezilla](https://user-images.githubusercontent.com/45924889/102152762-b2e4c480-3e43-11eb-909e-90bce81db709.jpeg)


Notice on the bottom right, 3GB total files. That is all I could find.

Thanks.

**Comment by DanielnetoDotCom** [comment]
But it is not the correct way to see your disk usage.

Next time you may want to google

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom When you download things from Youtube or what-ever site via youtube-dl , those files are stored on /tmp , and they're not automatically cleaned , until you restart apache or the server . 

I had to create a crontab on each encoder , to skip this issue .

**Comment by The-Do-It-Yourself-World** [comment]
Thank you. That is something new I guess. I will have to do the same.
