### ISSUE TITLE
Need the label to be translate-able for plugins

### ISSUE THREAD

**Issue by tazus** [WWBN/AVideo#4175]
I have purchased plugins: Customize, LoginLDAP, User_Controll, VideoResolutionSwitcher, and VideoHLS.

During the setup and testing, I have to translate the interface label, text... for my local language.  However, there is no related locale file in any of the plugin's zip file.  

I try to add some of the label to Avidoe/locale file, some of them work, but some of them not.  From my experience, I have to edit couple of original Avideo, files to patched some "labels" with enclosed  with <?php echo __("...") ?> to make it translate-able.  But for the encrypted plugins, I cannot. 

Current, I only testing Customize and User_Control.  The identified text is attached screenshots.

The rest of plugins, if needed, I will do the follow-up.  But, it is possible to distribute with each plugin with individual locale/en.php without encryption for purchaser to translate their own language as needed.

Thnaks.

![CustomizePlugin01](https://user-images.githubusercontent.com/79111/102157155-f11ccb00-3eb9-11eb-88fe-b5da6f6cc7a4.png)
![CustomizePlugin02](https://user-images.githubusercontent.com/79111/102157156-f2e68e80-3eb9-11eb-9cf8-824022452359.png)
![UserControl01](https://user-images.githubusercontent.com/79111/102157157-f2e68e80-3eb9-11eb-86a2-4043b8249de2.png)
![UserControl02](https://user-images.githubusercontent.com/79111/102157160-f37f2500-3eb9-11eb-8676-eba52ebc3244.png)

**Comment by akhilleusuggo** [comment]
Why would you need to translate it ? Only admins can see this .
If you understand the meaning of those words , you are good to go .

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo is right, but anyway. the Customize plugin version 1.1 has those translations

**Comment by tazus** [comment]
Generaly, it is true we website builders will know all of those English.
But sometimes we have to hand it over to the website maintainer who may not
know English.

Daniel Neto <notifications@github.com> 於 2020年12月16日 週三 19:30 寫道：

**Comment by tazus** [comment]
OK, I download the new version, but what text can be translated?  
Can you provide a list of text to be put into the translation file?

Thanks!!

**Comment by akhilleusuggo** [comment]
Translate what you need to translate ( basically what will be displayed as html text ) , not what will execute a function .

**Comment by tazus** [comment]
I did it before. For regular file, I can find the code to see what text
inside __(" ") to be translated. But for encrypted plugins, I cannot.
It will be real handy, if the translate-able text can be listed.

Tks.

akhilleusuggo <notifications@github.com> 於 2020年12月24日 週四 04:14 寫道：
