### ISSUE TITLE
HLS quality selection not showing

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4176]
The HLS quality selector not working for me anymore . I'm not sure why . Everything up to date ( plugins and source code )
Errors js

Same issues on chrome/Mozilla 

![image](https://user-images.githubusercontent.com/52116577/102224099-34912c80-3eee-11eb-865f-a72d622182c3.png)

**Comment by DanielnetoDotCom** [comment]
Please try the VideoHLS v3.8 (Just released)

If your files are hosted on a Storage, this may resolve

**Comment by akhilleusuggo** [comment]
Thank you , it's fixed now . And yes , finally you added an option that I asked you about 1 year ago ; To reload sources when changing quality , this way is instantly switched . Now finally I may get back to use HLS plugin .
