### ISSUE TITLE
Missing 1080p Resolution

### ISSUE THREAD

**Issue by HESSEBO** [WWBN/AVideo#4178]
**Hello guys and thanks you for your great efforts and continuous developing.** 
When I encode my video files that is less than 500M, it appears on my site with FHD 1080 res., but when I upload any file that exceeds 1.5G I see only 720 Res. I don't understand where's the problem at? 

I see this log line and it interest me somehow!

Thanks

 [15-Dec-2020 14:18:13 Africa/Abidjan] AVideoLog::DEBUG: Warning: Slow process detected [Video::updateFilesize 91] On  Line 1225 takes 1.1777 seconds to complete, Limit (0.7). path/to/my/streamer/site/objects/aVideoEncoderNotifyIsDone.json.php SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
![err1](https://user-images.githubusercontent.com/43477304/102232002-ade54b00-3eff-11eb-9466-79ad8310c7a2.PNG)
![err2](https://user-images.githubusercontent.com/43477304/102232007-ae7de180-3eff-11eb-9010-e8b4d4b8b55b.PNG)

**Comment by akhilleusuggo** [comment]
Well maybe because the files are not 1080 ?

**Comment by HESSEBO** [comment]
I uploaded multiple files and I am pretty sure they are in 1080p resolution. I installed the encoder on a different server  the issue still the same, any file that exceeds one Gig appears on the site as 720p as maximum resolution. I did all the configuration on php.ini files right where it meet my size need . but I still don't understand where's the problem at. 
Also one more thing; is there a way that I can group multiple local encoders into one local server?

**Comment by akhilleusuggo** [comment]
Yes , https://github.com/WWBN/AVideo-Encoder-Network

Only if you past here the ffprobe of the file you're trying to upload . Or the **_logs related_** to the ffprobe and encoding process we may know where the issue is coming from .

Quick note , If the file have a resolution of 1920x1079 , this file is counted as 720P not 1080 !

**Comment by HESSEBO** [comment]
Yes you were right buddy! my previous uploaded files where in 1920 by 1072, I uploaded 1920 by 1080 it worked perfectly. I hope the developers can consider this matter in the near future  so that we don't convert it into 1080 and then uploaded to the encoders. 
Thanks a lot for your help and I appreciate your kind responses.

**Comment by akhilleusuggo** [comment]
That would take many changes on the code . But my feedback would be make a some if statements ,

If resolution higher then 720 and lower then 1080 , ( example 1072 ) , convert it $resolution in this case 1072 and brand it as 1080 .

With ffmpeg is easy , it's called `vfr` ; Basically not static resolution , but with a resolution limiter . This is good in case you don't wanna have multi resolutions and you can't guess the resolution of the uploader . If the file he uploads if higher then 1080 , then will be encoded to 1080 . If it's 720 , then will be encoded to 720 .
