### ISSUE TITLE
Missing Videos or Videos Not Playable

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4179]
It was pointed out to me today that I have several videos on my site that are not playable when I know that they were playable at one time. In the image below you can see that they have some views but there is no accompanying video.

I know that I have not deleted any videos, so this tells me I must have selected or deselected a setting that affected these videos. Does anyone have any idea what that might be?

![missing_video](https://user-images.githubusercontent.com/7376298/102259495-cbe98600-3ed4-11eb-976f-8e7d72c332c3.jpg)

**Comment by DanielnetoDotCom** [comment]
can you please share a link to a non-playable video?

**Comment by bbyrdhouse** [comment]
Sure, here are several (there are dozens)

https://thepatriot.network/video/40/tutorial-2---how-to-upload-your-first-video?channelName=TheTutorialChannel
https://thepatriot.network/video/51/changing-your-channel-name-profile-pic?channelName=PatriotReload
https://thepatriot.network/video/85/an-introduction-to-live-streaming-on-the-patriot-network?channelName=PatriotReload
https://thepatriot.network/video/19/tutorial---create-an-account?channelName=PatriotReload
https://thepatriot.network/video/203/holiday-2020-theme--one-voice-childrens-choir---
https://thepatriot.network/video/204/a-very-moving-christmas-hymn-2014
https://thepatriot.network/video/205/maybe-we-should-invite-elena-parent-in

There are a lot more, but here are several ....

**Comment by DanielnetoDotCom** [comment]
This is because you disabled the VideoHLS plugin. and those videos are HLS

**Comment by DanielnetoDotCom** [comment]
Try this update, it may get your HLS videos even if the plugin is disabled

do not forget to clear your cache

**Comment by bbyrdhouse** [comment]
You talking about a git pull?  `cd /var/www/html/AVideo/ && sudo git pull`

I just did that last night, you want me to do it again?

**Comment by bbyrdhouse** [comment]
Update seemed to work ... videos are playing again.
Thanks

**Comment by DanielnetoDotCom** [comment]
Yes, do again now, I just sent the update
