### ISSUE TITLE
bug chat with text

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#4182]
hello jean as you can see on the chat i did a test with (123456789azertyuiopqsdfghjklmwxcvbn123456789)

when you look at the picture there are missing numbers

![image](https://user-images.githubusercontent.com/39193219/102350859-d9227580-3fa5-11eb-80c3-0e5b29d98a13.png)

**Comment by DanielnetoDotCom** [comment]
This is not a bug.

There is no space in the word to break it, it will be hidden

**Comment by syldri** [comment]
actually I put a space and it goes to the line

**Comment by DanielnetoDotCom** [comment]
Seems fine to me 

![image](https://user-images.githubusercontent.com/18009293/102352601-b765c600-3f86-11eb-8e64-2f06e34ef614.png)
