### ISSUE TITLE
request for information on double identification

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#4183]
there is a problem on the site with the address

when I connect with https://demo.com

and I open a new tab with https://www.demo.com

you have to identify again

when put the www. it's a new connection to the site

**Comment by DanielnetoDotCom** [comment]
Correct, www and non www are different domains, so they are different cookies and sessions

**Comment by syldri** [comment]
what are the consequences ?

**Comment by ronaldod** [comment]
Best to forward the user to the domain you prefer and not multi home your site.

**Comment by syldri** [comment]
hello, I made redirect changes in the .conf file or in the .htaccess file
I even created a file htaccess.txt

 RewriteEngine on
RewriteCond %{HTTP_HOST} ^www.demo.com$
RewriteRule ^(.*) https://demo.com/$1 [QSA,L,R=301]



nothing works

**Comment by akhilleusuggo** [comment]
I usually do it from vhost . I create 2 vhosts . one for www and other non-www

The www redirects to https
The non-www redirects to www

**Comment by syldri** [comment]
hello @akhilleusuggo   you can show me your two vhost files please

you are using this code for the activated file
```
# Activate the VirtualHost present in "sites-available"
a2ensite vhost-name-ssl
```
