### ISSUE TITLE
Gallery Front Page Order

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#4184]
Hi,

How can I change the order of the video categories on the front page.
Example: I would like Date Added before Trending. I just can't seem to find where to change it.

Thank you,

**Comment by akhilleusuggo** [comment]
I don't think there's such option . I remember have seen some update related to this , but can't really remember .

**Comment by DanielnetoDotCom** [comment]
Date Added and Trending is not categories, we may call them sections.

But you can sort categories.

![image](https://user-images.githubusercontent.com/18009293/102537499-c6816c80-4089-11eb-99c9-e118353e0898.png)

**Comment by D-Spayre** [comment]
Thanks,

I tried and created a category, but now it won't let me delete the category.
When I try and delete the empty category I get "Sorry! Your category has NOT been deleted!".

Thanks

**Comment by DanielnetoDotCom** [comment]
Hi, I sent a lot of updates all day yesterday regarding categories.

please update and check if still a problem.

If still do not delete, please check your logs.

**Comment by D-Spayre** [comment]
Thanks its fixed.
