### ISSUE TITLE
GPU encode

### ISSUE THREAD

**Issue by spike21** [WWBN/AVideo#4185]
Hello, 

I have set up my computer to use GPU with ffmpeg. 
I have no problem using encode from shell command line. 
Yet, when I upload video and use AVideo encoder, encode fail.

Is there any way to fix ?

Thank you

**Comment by akhilleusuggo** [comment]
Without details , can't help .
What GPU ? 
What file ( extension ) are you encoding ?
What commend line are you using ?
Are you decoding with CPU or GPU ?
h264_nvenc ? or h264_cuvid ?

GPU is not the best option for video storage , doesn't provide any compression . HTML5 doesn't support x265 ( where you could see the benefit ) . 

I use GPU for live-streaming , is what it dame for .

**Comment by spike21** [comment]
Sorry for not giving more details, I was in a rush.

Here are the log from the encoder :

`ffmpeg version 4.1.4-1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/var/www/AVideo-Encoder/videos/3_tmpFile.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2019-11-08T22:59:36.000000Z
    encoder         : Google
  Duration: 00:10:02.51, start: 0.000000, bitrate: 2126 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 1994 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2019-11-08T22:59:36.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 11/08/2019.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2019-11-08T22:59:36.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 11/08/2019.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
  Stream #0:0 -> #1:0 (h264 (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #1:1 (aac (native) -> aac (native))
  Stream #0:0 -> #2:0 (h264 (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #2:1 (aac (native) -> aac (native))
  Stream #0:0 -> #3:0 (h264 (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #3:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[h264_nvenc @ 0x56234ff2b880] OpenEncodeSessionEx failed: out of memory (10)
[h264_nvenc @ 0x56234ff2b880] No NVENC capable devices found
Error initializing output stream 3:0 -- Error while opening encoder for output stream #3:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
`

Here are the log from the command line :
`
ffmpeg -i 3_tmpFile.mp4 -vf scale=-2:720 -movflags +faststart -vcodec h264_nvenc -acodec aac -strict -2 -b:a 128k  -max_muxing_queue_size 1024 -y test.mp4
ffmpeg version 4.1.4-1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '3_tmpFile.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2019-11-08T22:59:36.000000Z
    encoder         : Google
  Duration: 00:10:02.51, start: 0.000000, bitrate: 2126 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 1994 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2019-11-08T22:59:36.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 11/08/2019.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2019-11-08T22:59:36.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 11/08/2019.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, mp4, to 'test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf58.20.100
    Stream #0:0(und): Video: h264 (h264_nvenc) (Main) (avc1 / 0x31637661), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], q=-1--1, 2000 kb/s, 30 fps, 15360 tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2019-11-08T22:59:36.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 11/08/2019.
      encoder         : Lavc58.35.100 h264_nvenc
    Side data:
      cpb: bitrate max/min/avg: 0/0/2000000 buffer size: 4000000 vbv_delay: -1
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2019-11-08T22:59:36.000000Z
      handler_name    : ISO Media file produced by Google Inc. Created on: 11/08/2019.
      encoder         : Lavc58.35.100 aac
[mp4 @ 0x5563264ccec0] Starting second pass: moving the moov atom to the beginning of the file
frame=18075 fps=177 q=22.0 Lsize=  153824kB time=00:10:02.51 bitrate=2091.5kbits/s speed=5.91x
video:143860kB audio:9464kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.325732%
[aac @ 0x5563264cdb00] Qavg: 310.415

`

**Comment by akhilleusuggo** [comment]
You haven't answer any of my questions . Sorry , can't help you .

**Comment by spike21** [comment]
I have nvidia quadro.
I encode mp4.

**Comment by akhilleusuggo** [comment]
You don't want help . I'm not with you at home to look at all this . There are many quadros ... Do you expect someone to guess witch one ? 

Anyway taking a look at your logs : 

`OpenEncodeSessionEx failed: out of memory (10)`

This means you have hit the limit on simultaneous encoding . You probably don't have a quadro , or your quadro is really really old .
With gtx , you can encode only 2 simultaneous encodes . Quadros ( depends witch ) , you can do 2-3 or up to 18 .

If you check nvidia , you gonna see your card is listed as ''non-qualified'' .

https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new#Encoder

**Comment by spike21** [comment]
It's a Quadro K420.
It's a 5 years old card.
I was thinking I was block at 2 simultanous encode. 
Is there a way to limit encode to two simultanous tasks or set it to the only two best quality (disable 240, 480 quality) ?

**Comment by akhilleusuggo** [comment]
Just do normal encoding . The one resulting in Low,SD,HD

![image](https://user-images.githubusercontent.com/52116577/102690777-72ed5b00-4210-11eb-8304-300835593de9.png)

And use 2 encoders . This way you have 2

**Comment by spike21** [comment]
Thanks for the reply.
How enable the CustomizeAdvanced plugin ?
I don't have the sliding button under it.

**Comment by akhilleusuggo** [comment]
on the main site , plugins , CustomizeAdvanced
