### ISSUE TITLE
Payment For Video Views Not Working Since Nov 16

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#4186]
Since November 16th when I updated my site the last time, payments for video views has not worked anymore.

My site uses DIY and YPTWallet plugins.

DIY is a custom plugin made by Daniel. After I discovered the error, I paid Daniel to fix the problem.

Since then, oddly, a very few sites get some payment but most are not getting any payments at all. Most have not been paid at all, not one single day, since November 16th.

Here are some screen shots:

![no-payouts](https://user-images.githubusercontent.com/45924889/102404701-0e36c400-3fb6-11eb-8bb2-f77162fbe04c.jpeg)

![ddsolar-no-pay](https://user-images.githubusercontent.com/45924889/102404741-1989ef80-3fb6-11eb-8af2-ebc13ce26083.jpeg)

The images show that one channel which I have chosen as an example has not been paid at all since Nov 16th. I have personally watched some of his videos and the views are counting but he is not getting paid at all.

I have many people complaining about not being paid.

My channel owners are supposed to be paid for video views, writing comments and for thumbs up (minus thumbs down) on a daily basis. Everything worked before the update.

**Comment by The-Do-It-Yourself-World** [comment]
I forgot to add that payment for writing comments and payments for thumbs up (minus thumbs down) vanished and never worked again since November 16th. Not at all.

**Comment by The-Do-It-Yourself-World** [comment]
Anything? Anyone?

On November 23 I paid Daniel $100 to fix my payment processor. It is still not working.

People are getting angry. This is real money we are talking about.

It worked fine for the last three years but the recent update killed it.

Is there anyone out there who I can pay to fix my payment processor please? Its a custom mod Daniel wrote for me 3 years ago. Its a small mod which ties into YPTWallet.

Please get me a quote.

Thank you

**Comment by The-Do-It-Yourself-World** [comment]
Rewards for video views, comments and likes are not working. Yes this is a custom job I paid Daniel to write three years ago. The last time I updated our site it killed my payments and has not worked since.

Daniel has all the source files since he wrote them.

If I can find someone to help, I can provide the files as well.

**Comment by palich91** [comment]
I think you need to contact Daniel, this is his job and he will make it faster

**Comment by The-Do-It-Yourself-World** [comment]
I cannot reach him. He always tells me to use github. Members are getting angry with me so this is a problem. Its been over a month now and it is still not resolved.

At this point I would call it an emergency and I am asking anyone out there who may be willing to help.

I realize it is a custom job and will have to be paid. Please get me a quote. Thanks.

**Comment by DanielnetoDotCom** [comment]
This is not true, your users are rewarded every day. look at the table

![image](https://user-images.githubusercontent.com/18009293/102541598-5bd32f80-408f-11eb-84d6-84a933e54d6a.png)

But the specific user DDSolar (id=1860) did not. maybe because of the rules you have added on the last update

![image](https://user-images.githubusercontent.com/18009293/102541860-b8364f00-408f-11eb-9f9d-2f2518846184.png)

**Comment by The-Do-It-Yourself-World** [comment]
Why do you always start your answer to me by calling me a liar in some form or another? My original remark included these lines "Since then, oddly, a very few sites get some payment but most are not getting any payments at all. Most have not been paid at all, not one single day, since November 16th."

This is quite true and can be seen by the fact that a lot of people are getting views but not being paid. I have tested it myself over the past few days before letting you know.

I have not made any changes at all. The only change was the update of your software onto my site. Then the payments did not work at all anymore. I paid you to fix it. But now, oddly only some work but most are not being paid anymore. If you go back before Nov 16th, many many people got paid daily. Now its a handful although site wide views are increasing. And no comments or thumbs up are being paid at all anymore. Not one single one in a month.

I am attaching a screen shot of just a few comments that have been made today. There have been comments made every day for a month and not one has been paid.

![New-Comments](https://user-images.githubusercontent.com/45924889/102551220-1f063900-408d-11eb-99e0-44b73d078792.jpeg)

The same goes for thumbs up and down.

**Comment by DanielnetoDotCom** [comment]
I am not calling you a liar, I just say the way you are asking for help, seems rude to me.

But anyway, I may know what is happening, there is a query limit since some time ago.
I guess the limit is 1000 if you do not specify one. so your script maybe is getting only the first 1000 users.

I can update your script to make sure you will get them all, and you tell me if you notice some change

**Comment by DanielnetoDotCom** [comment]
Confirmed you have more than 1000 valid users, so that is probably what happens

I sent you a fix, check if users are being rewarded now

**Comment by The-Do-It-Yourself-World** [comment]
Ok, that is odd. I never saw anywhere where I can set a limit of any kind.

Will this also fix comment and thumbs up payments? I have not seen a single one since November 16th in the payment history. They all used to show up.

**Comment by The-Do-It-Yourself-World** [comment]
Yes, the comment rewards are showing up. Thank you.
