### ISSUE TITLE
App issue -  "Error on Save Message" error 

### ISSUE THREAD

**Issue by Ernoldvb** [WWBN/AVideo#4187]
When using the app Ios/Android and try to add a comment on a video "Error on Save Message"  appears.
Please see screenshot (Error message below) however its only possible when you have " Admin" rights.

![IMG_912B35CCDD9B-1](https://user-images.githubusercontent.com/76129662/102406161-199fe480-3fe2-11eb-9bb3-7c1311200104.jpeg)

**Comment by DanielnetoDotCom** [comment]
Can you use the same user and save comments on the site?

**Comment by Ernoldvb** [comment]
Just tested, however, all user that is no admin, are not able to add a comment and the error appear.

**Comment by DanielnetoDotCom** [comment]
Make sure your streamer is up to date.
make sure you have the latest version from yesterday.
