### ISSUE TITLE
How To Prevent Users From Extracting Audio?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4188]
Hi,
Currently some users are uploading videos and extracting the audio which uses a lot of resources (as I understand it). I would like to turn this feature off so that it does not even show as an option.

I have selected the "doNotShowEncoderAutomaticAdio" option in the Custom Advanced plugin but it does not remove that option.

![audio](https://user-images.githubusercontent.com/7376298/102421919-311fa300-3fcb-11eb-81ca-681f3108439a.jpg)
![audio2](https://user-images.githubusercontent.com/7376298/102421924-35e45700-3fcb-11eb-9c58-c043c390a74c.jpg)

**Comment by akhilleusuggo** [comment]
Go to encoder directory /videos

Change make this lines took like this : 

```
$global['disableImportVideo'] = true;
$global['disableWebM'] = true;
```

**Comment by bbyrdhouse** [comment]
@akhilleusuggo - what about the extract audio part?

**Comment by akhilleusuggo** [comment]
If you disable it from the site , and CLEAR the cache , should work .
Make sure you logout the encoder before you clear the cache . If you use cloudflare or cdn , also clear the cache . Ctrl+F5 to clear browser cache of current page .

**Comment by akhilleusuggo** [comment]
You can also force people to not upload audio content by removing mp3 extension , and all related to audio .

![image](https://user-images.githubusercontent.com/52116577/102608702-f9cc0600-4132-11eb-8f12-108450f72cf5.png)

**Comment by bbyrdhouse** [comment]
I am not talking about uploading audio, I am talking about them uploading a video and it automatically encoding the video and another file that just has the audio.

How do I remove the "Extract Audio" option?

**Comment by akhilleusuggo** [comment]
I repeat : 

> 
> If you disable it from the site , and CLEAR the cache , should work .
> Make sure you logout the encoder before you clear the cache . If you use cloudflare or cdn , also clear the cache . Ctrl+F5 to clear browser cache of current page .

**Comment by bbyrdhouse** [comment]
@akhilleusuggo - to my knowledge, I have it disabled, that is why I have come here asking how to really make it be disabled.

Go back and look at the images I posted in my original post, you can clearly see that I have it disabled and yet people are still extracting audio.

Either, I am not pushing a button just right or the feature is broken and needs to be fixed.

**Comment by akhilleusuggo** [comment]
No you don't . I just tested it and look : 


![image](https://user-images.githubusercontent.com/52116577/102791404-a2869980-43af-11eb-95a1-3765666d6128.png)

No audio extract , no webm audio extract , nothing but mp4

**Comment by bbyrdhouse** [comment]
I don't know what you are looking at but this is what I see ... 
![audio](https://user-images.githubusercontent.com/7376298/102818682-c50cb880-4397-11eb-9f98-01c0dde74857.jpg)

**Comment by bbyrdhouse** [comment]
I just checked my alternate encoder and it also shows "Extract Audio" ... I am not sure where you are looking

![audio2](https://user-images.githubusercontent.com/7376298/102819018-554afd80-4398-11eb-85c1-2f569960fbc0.jpg)

**Comment by akhilleusuggo** [comment]
I don't know , maybe you believe in magic , but you're looking at is hard-coded . In other words , you need to change the code ( MANUALLY ) , **_on each encoder that you own_** .

**1-**


> Go to encoder directory /videos
> 
> Change make this line took like this :
> 
> ```
> $global['disableWebM'] = true;
> ```

**2-**

Make sure you have disabled audio on Customized Advanced plugin ;
![image](https://user-images.githubusercontent.com/52116577/102820744-6cacd980-43de-11eb-853e-122047b1787b.png)

**3- CLEAR THE CACHE !**
**4-** Log again on the encoder .


Note , for me looks like your encoder also is really outdated . The audio extraction is not anymore on the bottom as you indicate , but at the top . But disabling it from /video/configuration should work . If it's working for me , that means you're doing something not right .

Update and clear the cache ( including cloud flare if you're using )

**Comment by bbyrdhouse** [comment]
Audio encoders are straight from the git pull ... 

but, I've no use for smart asses ... thnx

**Comment by akhilleusuggo** [comment]
Pardon ?

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo always gives us good help and share his awesome knowledge on this project.

Currently, we do not have an option to disable the "extract audio", I just checked into the code

But I am sending an update that will allow you to disable it

I just added 2 options on CustomizeAdvanced plugin

doNotShowExtractAudio
doNotShowCreateVideoSpectrum

To be able to use it you need to update Streamer and Encoder

I will submit the changes soon
