### ISSUE TITLE
How to use the Live Program Play Streamer?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4189]
I see a option now on programs to go live but it says I need to update my encoder. What encoder is it referring because I have external encoders.

**Comment by DanielnetoDotCom** [comment]
Sorry for the late reply

It is working but still under development. I will create some documentation as soon as it is stable

**Comment by JoshWho** [comment]
KK Sounds good. This looks really kewl, can't wait to try it.

**Comment by DanielnetoDotCom** [comment]
BTW, check this https://github.com/WWBN/AVideo/issues/4128

**Comment by JoshWho** [comment]
Looks interesting. I was wondering about how to get on Roku. I will wait for a full plan rolled out with some documentation. This is really going to change everything once this is complete. Super excited.

**Comment by JoshWho** [comment]
![c9923f9d-15ee-4d4a-bc99-528791dcd59f](https://user-images.githubusercontent.com/39392449/102841158-00c07600-43ca-11eb-940b-5816a3180bbc.png)

**Comment by DanielnetoDotCom** [comment]
is your encoder up to date?

**Comment by JoshWho** [comment]
Yes

**Comment by DanielnetoDotCom** [comment]
I am not sure, try to update to see if there is any missing update.

**Comment by JoshWho** [comment]
Does it recognize external encoders?  I re installed a encoder on my main server hoping it was just looking for that, I am not sure what encoder it is trying to use I have 7 now.

**Comment by JoshWho** [comment]
you updated me just last week.

**Comment by JoshWho** [comment]
Is there any configs I have to fill out for it to connect to my encoder?

**Comment by JoshWho** [comment]
I just updated all encoders including the one I recently installed on the main server still shows the same error.

![1dfbc921-52ba-4d2f-89db-178177ddabd9](https://user-images.githubusercontent.com/39392449/103084840-9cf2a480-45a5-11eb-996f-c066f521c1bf.png)

**Comment by JoshWho** [comment]
I really wanted to have some holiday streams playing for today and tommarow but I can't get this to work.

**Comment by JoshWho** [comment]
Does this have anything to do with uses external Live Sers @DanielnetoDotCom 

I still use my regular Live Stream server on the main server.

**Comment by DanielnetoDotCom** [comment]
Hi, @JoshWho regarding your encoder error can you please check your encoder for something like this?

http://encoder1.avideo.com/status

this feature will not use the encoder network, it will use the encoder you setup here 

![image](https://user-images.githubusercontent.com/18009293/103224585-af9f0d80-4906-11eb-9a15-06ff6b314d5c.png)

**Comment by JoshWho** [comment]
I thought the Encoder network changes that? I never see it showing the same encoder when I look at that box.

**Comment by JoshWho** [comment]
also just noticed when encoder network tries to pul upl6 it thinks the url is www.joshwhotv.com/upl6/

It suppose to be ww2.joshwhotv.com/upl6/    

I looked in the encoder network add list and it is showing it there correctly with ww2. Not ure what is causing that. ALl the other encoders show the correct url.

![12c96cc5-d8af-4a1f-bd50-7d6c846ec500](https://user-images.githubusercontent.com/39392449/103227089-2cc08780-48f3-11eb-8cd6-e087edc46086.png)

**Comment by JoshWho** [comment]
After last update live stream playlist is working now :)
