### ISSUE TITLE
Layout and cache

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4190]
The new plugin Layout not installing .
![image](https://user-images.githubusercontent.com/52116577/102494604-96cc6780-407d-11eb-825e-24a3419ec804.png)

```
AVideoLog::DEBUG: plugin::getPluginByUUID Layout layout84-8f5a-4d1b-b912-172c608bf9e3 this plugin is On By Default we will install it (SELECT * FROM plugins WHERE uuid = ? LIMIT 1) SCRIPT_NAME: /objects/playlists.json.php
[17-Dec-2020 14:36:02 Europe/Berlin] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/AVideo/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /objects/playlists.json.php
```

And the cache is not working properly .

`PHP Warning:  file_put_contents(/var/www/html/AVideo/videos/cache/YPTObjectCache/US/index.html): failed to open stream: No such file or directory in /var/www/html/AVideo/objects/Object.php on line 398`

**Comment by TLCReuver** [comment]
Same problem here...
![Snap3](https://user-images.githubusercontent.com/39981177/102528385-c3dd4200-409e-11eb-9d05-049c098b2f80.jpg)

**Comment by DanielnetoDotCom** [comment]
Sorry for that, here is a fix

**Comment by syldri** [comment]
hello @DanielnetoDotCom  the problem is still present

**Comment by DanielnetoDotCom** [comment]
Please try now

**Comment by tonuzo** [comment]
Hi, there's no activation slider available.

![image](https://user-images.githubusercontent.com/63721378/102595817-eb74ee80-4120-11eb-82e7-7b764951bd78.png)

**Comment by akhilleusuggo** [comment]
true , neither to disable ( I don't even know for what is tbh )

**Comment by DanielnetoDotCom** [comment]
There are some required plugins, you cannot disable them. they are enabled by default.

For now, those are enabled by default

- CustomizeUser
- CustomizeAdvanced
- Layout
- PlayerSkins
- Permissions
