### ISSUE TITLE
no connection when i on_publish

### ISSUE THREAD

**Issue by silent2017** [WWBN/AVideo#4191]
hello i hope someone can help me.
as soon as I get the on_publish /plugin/Live/on_publish.php
I can no longer connect to OBS.
someone has a solution.
Server Ubuntu 18.04
Nginx and Nginx stat works fine

**Comment by DanielnetoDotCom** [comment]
the on_publish MUST be an URL to with HTTP protocol

**HTTPS does not work**

`on_publish http://yoursite.com/AVideo/plugin/Live/on_publish.php;`

**Comment by silent2017** [comment]
I have already entered it without https.
but the website runs on https
don't know if that plays a role.

**Comment by baardove** [comment]
I also have a problem with on_publish. Everything runs fine, I set up http on localhost through apache, and checked it can access the script, but it will not authorize the stream. Removing the on_publish from nginx rtmp config will allow streaming just fine (but then of course it is not picked up by avideo).

**Comment by silent2017** [comment]
It is exactly the same with me

**Comment by DanielnetoDotCom** [comment]
maybe it is never reaching the Streamer server.

check nginx log and also streamer log for some clue

**Comment by silent2017** [comment]
That doesn't say much just connected and disconnected directly.
I'll post lied later.
