### ISSUE TITLE
Please Consider Adding Ability To Add Custom Page

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4193]
I would like to ask for an option to add a custom page(s) to the site.
Creating a link to an external page is clunky at best and ideally you want to keep your viewers on your site.

Example: I'd like to have a page, where I could offer as an extra $ervice to create a Roku channel for content creators. I'd want this to be within the site and not to an external location.

Thanks

**Comment by DanielnetoDotCom** [comment]
Thanks, definitely we will improve it in the future.

For now, what about creating an HTML page, upload it to your site, and add it as an IFrame on the top menu?

![image](https://user-images.githubusercontent.com/18009293/102614119-6b478c80-4112-11eb-8011-fb024609501c.png)
