### ISSUE TITLE
How Can I make my livestream show up on my channel?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4194]
**Describe the question**
Currently when doing a livestream, it will show up on the gallery page, which is fine, but I also want it to show up on my channel page. How can I make this happen?

**Comment by JoshWho** [comment]
It is a future thing eventually it will be on there. It has to get coded into the core. Not sure on when but it is in the idea list.

**Comment by bbyrdhouse** [comment]
@JoshWho - ok, that is good to know.

**Comment by syldri** [comment]
@bbyrdhouse  / @JoshWho  if you look there has been an update

soon you can add the live directly in the category you want

![image](https://user-images.githubusercontent.com/39193219/102556059-4f1efd80-40c8-11eb-8166-a0cd1c59eb10.png)
