### ISSUE TITLE
How to link Categories and Usergroup

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#4196]
Currently, when uploading a file, select the category and user group to upload. When uploading a file by registering a user group in the category in advance, I want to be able to watch the file in the user group registered in advance just by selecting the category. Can I do it with the current version? If you need a new plugin, please develop it. If you have a fee, please let me know

**Comment by DanielnetoDotCom** [comment]
Hi, this feature is not clear to me yet. I need bore details

I guess we do not have this feature yet, but definitely, we can quote that. feel free to email me requesting a quote.

**Comment by hnagasawa** [comment]
Dear Daniel

When uploading a file with AVideo-Encoder, now select the file, category and user group to upload.
I want to upload a file to AVideo just by registering a user group in the category first and selecting the category when uploading the file.
Example
Suppose you have sample1 and sample2 in your category.
Suppose you have naga, mine and take in your user group.
Register the user groups naga and mine in smaple1.
Register the user groups take and mine in sample2.
When uploading an mp4 file whitesnake to AVideo with AV-encoder, select category sample1 and load it to whitesnake.
Upload it so that it can only be played to the user groups naga and mine.

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
Why not just select the user groups on the encoder?

![image](https://user-images.githubusercontent.com/18009293/102771742-2f583580-4365-11eb-8a50-b92a59c13d66.png)

**Comment by hnagasawa** [comment]
Dear Daniel

This is because there are too many user groups and video viewing control 
(access rights) is performed by category.

Regrads
Hiroshi Nagasawa

**Comment by hnagasawa** [comment]
Hi Daniel,

Do you have update?

If you need to create new plug in for our request,we will pay

Regards
Hiroshi Nagasawa
