### ISSUE TITLE
AVideo first page

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#4197]
I want to make it like an attachment without turning on userMustBeLoggedIn of CustomizeUser of plugin.
Please tell me

**Comment by DanielnetoDotCom** [comment]
What?

**Comment by hnagasawa** [comment]
Dear Daniel

I want to have only the login screen when I access the top page of AVideo.
I want to see the sample video after logging in like youtube. Only for user groups that have viewing privileges. May have something to do with isuue # 4196

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
Can you please provide some screenshots?

I am not understanding.

**Comment by hnagasawa** [comment]
Dear Daniel

 > Can you please provide some screenshots?
 >
 > I am not understanding.

Please see attached pptx.

In the current AVideo, it is necessary to turn on userMustBeLoggedIn of 
customize user of plug in. I want to make the top page of AVideo look 
like 2page of pptx without turning this on.

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
you are on GItHub, there is no attachment

**Comment by hnagasawa** [comment]
![スライド1](https://user-images.githubusercontent.com/46562199/102887266-f4a3e980-4499-11eb-9f2e-481f17ee1844.PNG)
![スライド2](https://user-images.githubusercontent.com/46562199/102887275-fa99ca80-4499-11eb-9fb7-93141105dd48.PNG)

**Comment by DanielnetoDotCom** [comment]
Check this 

![image](https://user-images.githubusercontent.com/18009293/102890339-0a35f680-443b-11eb-8b34-841a59c7567f.png)

**Comment by hnagasawa** [comment]
Dear Daniel

I know this option of plug in

I hope not check this option

**Comment by DanielnetoDotCom** [comment]
I am not understanding what you mean and I do not know what you want

**Comment by hnagasawa** [comment]
Hi Daniel,

Do you have update?

RGDS
Kazu Toyoda

**Comment by DanielnetoDotCom** [comment]
Hi, what you need still not clear to me

**Comment by akhilleusuggo** [comment]
@hnagasawa I think I know what he means . Try enabling Gallery Plugin .

@DanielnetoDotCom When he's not logged in , he got the first page as video , after login , same page video .
I believe he wants the first page , to be something else rather then a video .

**Comment by hnagasawa** [comment]
Dear akhilleusuggo

You is right.

Do you understand " How to link Categories and Usergroup" too ?

Regards
Hiroshi Nagasawa

**Comment by akhilleusuggo** [comment]
Create a user group and link it to a category .
But most importantly maybe , is that you need to make sure that the videos does belong to the user group . Also , on gallery plugin , select : 

![image](https://user-images.githubusercontent.com/52116577/103309441-bbc9be80-4a1d-11eb-86d0-5cf38a62526d.png)

**Comment by hnagasawa** [comment]
Hi Daniel,

Now Nagasawa requested 2 items.
We want fix of one of item urgently.
We want add link of category and groups.
For example,
When Category videoA are link to group aa and bb,
group aa and bb's user can see Category videoA's movies.
it need some of group need to link Category.

Please check and inform about it  asap.

RGDS
Kazu Toyoda

**Comment by DanielnetoDotCom** [comment]
For this feature request, I recommend you to send details about it to developer@youphptube.com for a quotation
