### ISSUE TITLE
RE User Steps on How To Setup The "LIVE" and the "Live Link" sections on YouPHPTube

### ISSUE THREAD

**Issue by Fuquan999** [WWBN/AVideo#4198]
Dear Daniel,

Are there now any clear steps on how to setup the "Live" section of YouPHPTube? Once we tried (see old case: Chat and Webcam Issues #3087) but we never really got anywhere as then you said it was "experimental".

However, we would now like to try again especially given this COVVID stuff as getting this section working would be helpful.

The areas of concern are simply clear directives as to what many of the settings are actually referring to  for instance  under the "Devices Stream Info" what exactly is the application to have as input under things like "Server URL" are you talking about the external media server or are you talking about the local server. For instance we have an "external" server that runs ffmpeg and streams media but if I recall the server on which YouPHPTube is running on also has ffmpeg. so which do we point to?

Since there is no "Pop Up" help when you hover your mouse over where it says "Server URL" it is hard to figure out what exactly needs to be placed as input in this field. Same for the other fields on the page .

The same for the parameters on the "Add a Live Link" a "Pop Up" descriptive guide would help tremendously as not every body is a Media Streaming Guru and they should not need to be to use it, after all you do not need to be a motor mechanic in order to drive a car.thus these parameters could do with a little pop-up descriptive.

We would like to get this section working so that we can atleast use it to stream LIVE so any guidance to make this happen would be appreciated. We do have a separate server that already streams via OBS but for this YouPHPTube we would like to simply use the "WEBCAM" to stream visuals and audio and the rtmp server could be our external server so how would we go about doing this using YouPHPTube?

These settings are of concern: Do yo have proper working examples of what should go there and a little explanation?
=================
Player URL:
Live URL:
Server URL:
Stream name/key:
==================

Aslo on the l"Live Stuff" under "CONTENT in the Admin Panel 
what goes in these fields below thus what is referred to as the "PlayerServer" woudl that be YouPHPTube server or our external server that already streams content that we can use as an rtmp server? Or is that even our desktop where the Webcam is located? Then what shoudl go in the "SERVER" section? The YouPHPTube server ? Also what "FORMAT" shoudl the entry into the field be for instance rtmp://MyYOuPHPTubeServer/live or http://MyYOuPHPTubeServer/live etc. etc. All these thigns need some pop up help or info.
-------------
SERVER
PLAYERSERVER

When you click the red "LIVE" button nothing happens even though we have a webcam on our PC so how do we get the server YOuPHPTube to recognize our webcam and to actually stream form it?
 All these steps do need guidance so if you could help that would be appreciated:

Thanks
Lusjames/Fuquan
[](url)

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/Live-Plugin

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/LiveLinks-Plugin

**Comment by Fuquan999** [comment]
akhilleusuggo

Thanks for the pointers we will read up on his hopefully it will help

Thanks

**Comment by Fuquan999** [comment]
Hi Daniel,

I have taken a look at the information provided but there are a few caveats which probably you can provide some guidance of workarounds.
1) The server on which YouPHPTube is installed already runs APache2 and not NGINX. 
2) Thus our option is now to point to an external server but to point to an external server where should we look as in the plugins "LIVE" and  "LIVE LINKS" we do not see anywhere we can point to the remote media server as the options we see on "LIVE" are "server:" and "playerServer" as we have tried the "server" option to point that to our media server that has nginx/ffmpeg but that does not work so where exactly do we need to go to do this as the video guide that was sent in one of the previous links also does not really guide us on using an external server.

That said, if we cannot get it working without nginx on the same server we could allocate/create another Ubuntu server with nginx and the rtmp module but still how would we point the YouPHPTube server to use that server so it uses it?

Thanks
Fuquan/Lusjames

**Comment by akhilleusuggo** [comment]
You're not clear on what **_you_** want .

Do you wanna stream ? Or do you wanna copy an m3u8 url from where else and make it play on your site ?

If you wanna stream , you need the LIVE .
If you wanna add an url LiveLinks-Plugin

Different things . If you need information about how to set up a working rtmp-nginx server : https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

If you read the wiki , you will avoid many already answered question tens of times .

**Comment by Fuquan999** [comment]
Dear akhilleusuggo 

Thanks for your update but I am not sure why you would send me a link you already sent of which I already read and I am familiar with Nginx. What I clearly stated is that the server on which YouPHPTube is on is an Apache one (and has to stay that way) hence why I asked how to use an "external" server. I also stated that if  "NEED BE" I can always setup an external Nginx server to achieve this result (as the current stream server we have is its own entity).

So my question was simply how to setup (or use if you prefer) an external stream/media server for the rtmp as where exactly do I need to put the details of the external server as if you read carefully my last comment I pointed out that certain fields needed more clarity as, for example,  where does the "external" servers stream key go etc. It is the very two things you mentioned that the "INPUT FIELDS" need clarification as (for example again) both LIVE and "live Links" have two input fields each but both (it seems) are input boxes for the local server and NOT for any external server. If you do not understand a question maybe try ask the person who asked to rephrase their question as that is a more prudent approach to save going round in circles.

Thanks and enjoy the Xmas
Fuquan Idris

**Comment by akhilleusuggo** [comment]
Maybe you're not familiar with NGINX or with HLS .

OK , let me explain it again . 
1-live Links , you copy/past any on-going live-stream URL ( .m3u8 extrension ) and you past it . You're NOT hosting the video stream , you're only allowing people to watch it via your player ( NO resources consumed what so ever, you only generated a page ) 
2-Can you set up external rtmp-nginx servers ? 
+Yes
3-How many per server ?
+Unlimited ( your hardware/bandwidth ) will be the limiter . And you can add as many as you want . ( external server )
4-How to setup external server ? 
+The same way you did with the internal . You may want to add some modification in case you have the plugin ''send stream to encoder" . https://github.com/WWBN/AVideo/wiki/Live-Plugin#livestream-server-balance
5- In case you're sharing with partners a server with rtmp-nginx and you want to add new application ( I'm using this ) , take a look here . https://github.com/WWBN/AVideo/wiki/One-NGINX-RTMP-Server-for-Multiple-AVideo-platforms

**Comment by Fuquan999** [comment]
Hi akhileusuggo,

Thanks for your response  but I am not sure where you got the below "QUESTIONS" from as I never asked those as it seems you are ANSWERING YOUR OWN QUESTIONS and not what has been asked!
===================
WHERE DID THESE QUESTIONS COME FROM?????
-------------------------------------------------------
1-live Links , you copy/past any on-going live-stream URL ( .m3u8 extrension ) and you past it . You're NOT hosting the video stream , you're only allowing people to watch it via your player ( NO resources consumed what so ever, you only generated a page )
2-Can you set up external rtmp-nginx servers ?
+Yes
3-How many per server ?
+Unlimited ( your hardware/bandwidth ) will be the limiter . And you can add as many as you want . ( external server )
5- In case you're sharing with partners a server with rtmp-nginx and you want to add new application
=========================

The answer on questions number "4" is what comes close to the question we asked! And having read the answer you gave to question "4" it provides some usefulness. Which as a pointer we can use in the troubleshooting  process....so thanks for Q4 as that is a useful pointer.

That said when YOU habituate the  pattern of "asking YOUR own questions" and Answering them  such a behavior does not help the troubleshooting process so it may be wise in future to avoid doing this as it does not augur well on both your side or on the client side of things as the bottom line is to "solve" problems not aggravate them. Why you would manufacture your own questions to a problem beats my stretch of imagination.

Anyway, given the festive period do have your self a splendid Xmas and New Year in advance

Peace
Fuquan Idris

**Comment by akhilleusuggo** [comment]
good luck

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo always provide us an awesome help, I am sure he is kindly doing the best he can (even if he does not need to do it)

@Fuquan999 Are you trying to set up multiple live servers?

if yes just fill the information with each specific server info. if you only have a single live server you should not enable the live servers option and use the default configuration (it is a lot easier)

If you are going to use an external server it MUST be an Nginx server with our configuration.

If you will choose any other RTMP server you may be able to use LiveLinks only providing the m3u8 URL

**Comment by Fuquan999** [comment]
Dear Daniel.

Thanks for the update info when free we shall follow up on it.
As for the "other" top comment  you added we do understand that you feel a need to intervene in the contributors defense but  being a christian I am sure you will recognize and appreciate that "IF" one decides to offer "Help" it should then be 'help' that one offers and not illusions of help as keeping things as pure as possible is a far better habit to cultivate especially as the omniscient is also omnipresent.

Do have a pleasant New Year
Fuquan

**Comment by akhilleusuggo** [comment]
@Fuquan999 Don't bring God into your mess , and use it as an excuse for what ever illusion you're trying to create . 

I gave you the best help I could . When I saw that I'm not helpful enough for you , I told you good luck .

> As for the "other" top comment you 

Shame on people like you .

You stated above _you're familiar with NGINX_ , but also asking question such '' what should go where " .
RTMP Server URL , Player URL , Stats Page URL .

Anyone familiar with NGINX knows what goes where . Above I linked you the URL that explains exactly what you needed .

> Different things . If you need information about how to set up a working rtmp-nginx server : https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

![image](https://user-images.githubusercontent.com/52116577/103510453-f7291a80-4e6d-11eb-874a-8d3816c66460.png)

PS: I'm not gonna be able to read your next comment , I blocked you . God bless you
