### ISSUE TITLE
progressing bar

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4199]
How can I edit the progressing bar ?

![image](https://user-images.githubusercontent.com/52116577/102607979-d8b6e580-4131-11eb-8997-928426a48dae.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure what you want, but you may be able to change it a lot with CSS

**Comment by akhilleusuggo** [comment]
but where ? I just don't like the loading/processing looking ( very old school ) .

Could you indicate on the code where have been implemented ?

**Comment by DanielnetoDotCom** [comment]
It is here https://github.com/WWBN/AVideo/blob/c7399f8608ac7dafcd54418615d593225d3eca85/view/js/script.js#L932
