### ISSUE TITLE
Upon enabling Live functionality all dashboard menus become unavailable.

### ISSUE THREAD

**Issue by lordtenteth** [WWBN/AVideo#4202]
Whenever i do a fresh install and enable live stream ability, the menus on the admin dashboard and all drop down menus break.

Done it a few times and same result over and over. it stops me from being able to remove the livestream option after enabling it.

**Comment by DanielnetoDotCom** [comment]
I do not understand, please screenshot

**Comment by markginter31** [comment]
I noticed something similar - once live is enabled, I browse to my site and I can't click on any menu options until I am able to click the little shadow x that appears up near the login area.  You can see the x in the screenshot.  I noticed this behavior after I did a git pull to the latest.
![shadow_x](https://user-images.githubusercontent.com/7345618/102979609-4b2e1980-44d4-11eb-95e6-cf5da99ca2ee.png)

**Comment by DanielnetoDotCom** [comment]
please update it again, it should be fixed.

if persist please share the link here

**Comment by markginter31** [comment]
Thank you!  Is there a central place for nginx help?

**Comment by DanielnetoDotCom** [comment]
Try to contact nginx project directly

**Comment by markginter31** [comment]
Thanks :) -- I did a git pull and used a fresh Firefox (nothing cached) -- and the X was still there along with the inability to click on the top items until I clicked the x

**Comment by DanielnetoDotCom** [comment]
Hi

share with me a link where it is happening

**Comment by markginter31** [comment]
video.oakhillcog.info

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by markginter31** [comment]
That worked. Thanks!

**Comment by markginter31** [comment]
Spoke too soon -- the X disappeared from the main page before I log in -- and then it won't disappear once I login no matter how many times I click the X

**Comment by DanielnetoDotCom** [comment]
I am not sure where it does come from.

can you reproduce it on demo site?

**Comment by markginter31** [comment]
Did a fresh/clean install and it went away.
