### ISSUE TITLE
PHP Fatal error - getTotalToday()

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#4203]
Hi there,

I am seeing the following error in my avideo.log
PHP Fatal error:  Uncaught Error: Call to undefined method Video::getTotalToday() in /var/www/html/objects/getTotalTodayAsync.php:13

Is this something i can ignore?

thanks

**Comment by Maikuolan** [comment]
@millzee01 This should be fixed now since the latest commits. :-)
