### ISSUE TITLE
Plugin Descriptions

### ISSUE THREAD

**Issue by techiesces** [WWBN/AVideo#4205]
This is kind of a general question or request.

I don't feel like there is enough information about each plugin to truely understand what each one is for exactly and how and why it is needed or not needed.  I am finding it difficult to understand most of the plugins uses, or I will make assumptions that turn out incorrect as a result.

Is there anyway to add more descriptive content to both the paid and unpaid plugins so I can make better informed decisions?

**Comment by akhilleusuggo** [comment]
Check the wiki in first place .
And what plugin specifically do you need more information about ?

**Comment by techiesces** [comment]
@akhilleusuggo  Well many of them as I am guessing on what they do...  But right now I am trying to figure out if I need the subscription plugin for $59 or the Pay per view plugin for $59.  Not sure the differences and how they are used exactly... also not sure if they have dependents in order to function like what gateways or anything and if there is anything else needed or setup.  Like which one is for giving users the ability to pay for ad free content, etc.

Like I said the lack of info makes me shoot in the dark and hope for the best, lots of time spent with trial and error and in some cases not seeing any changes when plugins are active or not which are head scratchers.  No descriptions makes this a challenging game, but i would rather just know what I am doing haha

**Comment by techiesces** [comment]
@akhilleusuggo So the wiki helped... however, now I have the pay per view plugin but it sets the time based on hours and I am not sure if this unlocks only one video or all of them.  I am concerned I have a plugin that is not exactly what fits my needs.  I have to do a test to see.  this is why better descriptions are important.  the wiki was helpful though.

**Comment by DanielnetoDotCom** [comment]
Hi

you can check all the plugins before purchase on the demo site.
If you want, open an issue with your question and please some screenshots to help us understand

FYI, 

Subscription is based on usergroups
PayPerview, can be based on usergroups or per video

if you choose usergroups only videos on that usergroups will be available

![image](https://user-images.githubusercontent.com/18009293/102772806-e608e580-4366-11eb-806c-2850dafc15a0.png)

**Comment by techiesces** [comment]
@DanielnetoDotCom OK, so here is my confusion regarding the Pay Per Video plugin.

It says you can make all the content only available with ads.  I would like to have all videos play ads unless user decides to buy an ad free for a month.  Then all videos from all users will be ad free during this time.  All uploads from any user automatically default to this setting. Not clear how to make this happen.  Hopefully the pay per view plugin I bought can do this.  Thanks.

**Comment by DanielnetoDotCom** [comment]
to use the "play with ads" you need the GoogleAds_IMA and a VAST ad company providing you with ads

**Comment by techiesces** [comment]
@DanielnetoDotCom Oh I see... I was trying to use the internal VAST system.  So that system does not work, I have to use the GoogleAds_IMA system instead??  I have my own ad server I can use, if need be, but was not aware that the internal VAST system does not work the same.  Please confirm.  Thanks

**Comment by akhilleusuggo** [comment]
VAST you're hosting the ads on your server . Must be mp4
ads_IMA are hosted by google ( google AdSense linked ) . You should first get approved on IMA program . This happens after 2weeks up to 2months after reaching 500k-2kk views .

It's hard to get accepted on IMA , unless they changed something .

**Comment by DanielnetoDotCom** [comment]
There is a trick ...

you can use your Internal VAST, and place your vast link into GoogleAds_IMA

this also works with your own ads.

**Comment by akhilleusuggo** [comment]
Oh yeh , I've updated it yesterday and I saw that you implemented it . But where is the point doing this ?
First you have to create and ENABLE the VAST plugin . 
So basically what we're doing is looping and making additional requests for what reason ?

**Comment by DanielnetoDotCom** [comment]
Google IMA can play third parties VAST links

the AD_Server plays only his own VAST, but allow you to share his VAST outside. so you can use this combination to play it
