### ISSUE TITLE
 Broadcast recording problem.

### ISSUE THREAD

**Issue by Proton-people** [WWBN/AVideo#4206]
Broadcast recording problem. There is no recording in the / var / www / tmp folder and the broadcast is not recorded. Please help me figure it out.
![nginx-conf1](https://user-images.githubusercontent.com/48072457/102724553-d5864a00-4329-11eb-97d5-32d4210e49bc.jpg)
![nginx-conf2](https://user-images.githubusercontent.com/48072457/102724563-e46cfc80-4329-11eb-959a-91228f68401c.jpg)
![nginx-conf3](https://user-images.githubusercontent.com/48072457/102724568-e9ca4700-4329-11eb-89ad-4518830d5fe0.jpg)
![nginx-conf4](https://user-images.githubusercontent.com/48072457/102724572-f353af00-4329-11eb-9880-d219d9c68d86.jpg)
Streamer during broadcast:
![live-avideo-log_LI](https://user-images.githubusercontent.com/48072457/102724674-a2908600-432a-11eb-8782-45de7045c142.jpg)
Encoder during broadcast:
![live-coder-log_LI](https://user-images.githubusercontent.com/48072457/102724700-cf449d80-432a-11eb-8cc2-43cb2f298880.jpg)
Nginx error log:
![bandicam 2020-12-20 22-46-49-583](https://user-images.githubusercontent.com/48072457/102724724-23e81880-432b-11eb-80e9-c1759e4b3dcd.jpg)
Plugin included:
![bandicam 2020-12-20 22-44-40-108](https://user-images.githubusercontent.com/48072457/102724752-54c84d80-432b-11eb-85d3-e8e970a3e58d.jpg)
What could be the reason? Tell me please.

**Comment by DanielnetoDotCom** [comment]
Uncomment the `recorder video ` section in your nginx.conf

Please check here https://github.com/WWBN/AVideo/wiki/Record-Live-Stream

**Comment by Proton-people** [comment]
Thank you so much. Everything is working.
