### ISSUE TITLE
Strange Bug, Site not loading!

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4207]
Suddenly since yesterday my site is loading wrongly and complains there is a mix content where I am quite sure there isn't.

This is the error I see on the browser. The logs indicate nothing meaningful. 

![Screen Shot 5781-04-06 at 0 51 42](https://user-images.githubusercontent.com/58882903/102726390-16309400-4327-11eb-8ba1-fd7066c6b441.jpg)

not sure what to do really.

**Comment by DanielnetoDotCom** [comment]
this means you have http and https content into your site.

make sure it is all https

**Comment by guymass** [comment]
but I don't have any http, site was working fine one day and next day this. No content was added or changed. Anyway of checking where this content resides?

**Comment by guymass** [comment]
Done a test on this site, besides those two first files all the test is green.

![Screen Shot 5781-04-06 at 19 48 49](https://user-images.githubusercontent.com/58882903/102806550-c3f28000-43c5-11eb-8b3b-43f9b82d14a6.jpg)
![Screen Shot 5781-04-06 at 19 48 57](https://user-images.githubusercontent.com/58882903/102806560-c7860700-43c5-11eb-8f39-fd8d9c209d3b.jpg)

Everything seems normal. I am not sure how and where to look for those bad urls if they exists. I think its either nginx or maybe .htacess. IDK, please help.

**Comment by guymass** [comment]
Also when I try to search in the folder with grep, under cache I see my urls are generated as http and not https.

![Screen Shot 5781-04-06 at 20 05 05](https://user-images.githubusercontent.com/58882903/102807786-f8673b80-43c7-11eb-8715-3608934c3568.jpg)

**Comment by akhilleusuggo** [comment]
Google is your friends . How to redirect all requests to https ( vhost ). This has nothing to do with the project really .

Answers I've provided before ; 

#####################

1- ) First , make sure that you have changed the url on `/videos/configuration.php` to  https://yoursite.com

2 - ) `/etc/apache2/sites-available/yoursite.conf`

Add this lines ( you can google for more information ) , replace yoursite.com by your domain name
```
RewriteEngine on
RewriteCond %{SERVER_NAME} =yoursite.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
```

3 - ) If you want that all request goes to https and remove http , delete this lines from your `/videos/configuration.php `

```
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) {
// get the subdirectory, if exists
$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), FILE);
$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
```

**_Read more about this_** https://github.com/WWBN/AVideo/wiki/Redirect-http-to-https

**Comment by DanielnetoDotCom** [comment]
@guymass also check your configuration.php file.

make sure there is no http there

**Comment by guymass** [comment]
Thank you very much that solved he issue, was hard to figure out.
