### ISSUE TITLE
Top Bar inactive in video play screen

### ISSUE THREAD

**Issue by techiesces** [WWBN/AVideo#4209]
![image](https://user-images.githubusercontent.com/75285261/102787959-7d6e3880-4367-11eb-9e4b-853818534ce0.png)

Top bar not active to click in video play screen.  I highlighted the top bar and unclickable items.

**Comment by DanielnetoDotCom** [comment]
Is it an embedded video?

please make sure you have an update from yesterday. if the problem persists, please share a link here

**Comment by techiesces** [comment]
@DanielnetoDotCom No this is not embedded, this is actually on the website itself when you play a video.  I will update now and recheck.  If it persists I will share a link here.

**Comment by techiesces** [comment]
@DanielnetoDotCom Ok looks like it is resolved, no updates from the pull.  My guess is that it may have been a plugin I had activated possibly?  I had theater button plugin activated but turned it off.  Not sure if having that on with my setup may have caused it or not.

I was also experimenting with Payperview plugin as well at the same time so maybe there is a conflict somewhere hidden.  SOrry I wish I could tell you why this issue existed.  But it is gone for now.  Thanks.
