### ISSUE TITLE
User recommended videos to tags they subscribe to.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4210]
Would be kewl to recommend videos to users not only including who they subscribe to but also what tags they subscribe to as well.   

For example put somewhere in the Profile section a tag selection to what videos they would like to see recommended to them.
EG:   News, Comedy, Reviews, History, etc...

**Comment by techiesces** [comment]
Like user created algorithms... would be unique to the overloads deciding what we see, haha

**Comment by JoshWho** [comment]
Exactly. It would be a stitch to the big tech world. People would love it.
