### ISSUE TITLE
Not Sure what this error means

### ISSUE THREAD

**Issue by techiesces** [WWBN/AVideo#4211]
PHP Warning:  file_put_contents(path/to/my/streamer/site/videos/cache/YPTWget/ad6c2663e89a82bedfb6e24b7b608f09.lock): failed to open stream: No such file or directory in path/to/my/streamer/site/objects/functions.php on line 4030

Any idea what this means?  Thanks

**Comment by akhilleusuggo** [comment]
I believe it's some cache from database . Probably some url/keyword changed , and couldn't find it from cache .
Anyway is not an error , just a warning . Clear the cache directory , and you may not see this ''issue" again .

**Comment by DanielnetoDotCom** [comment]
Also make sure the videos directory is writable

**Comment by techiesces** [comment]
@DanielnetoDotCom I would assume the videos directory is writable or I wouldn't already have videos there right?  Or am I wrong there?  Maybe the reference to that particular directory is incorrect?  I have noticed my file system isn't always exactly like your references.  Like my video directory is actuall /var/www/AVideo/videos  not /var/www/html/AVideo/videos   Could this be an issue as well?

Thanks.

**Comment by DanielnetoDotCom** [comment]
I do not think this is the issue.
Maybe this is not an error, but keep your eyes open if this happens contantly.
