### ISSUE TITLE
Options for Hide Media Owner Tag

### ISSUE THREAD

**Issue by elias2k1** [WWBN/AVideo#4212]
Is there any option to hide Media Owner Tag from Video? And also need to hide Free/Paid tag from video.

**Comment by akhilleusuggo** [comment]
What do you mean by hiding media owner ? So what should be displayed as the owner of the video ?
Free/Paid from pages ? I think there's no such option , but you can leave it blank .

Go to Customize Advanced plugin , look for the text dispel for Free Label and Payed Label , and changed to be empty ( type a space ) , and save .

**Comment by elias2k1** [comment]
I just want to hide the highlighted part from the non admin user (or all user):
![media Owner1](https://user-images.githubusercontent.com/75417257/102857287-58a2bf80-4452-11eb-9647-d6d5899b9422.JPG)
![media Owner2](https://user-images.githubusercontent.com/75417257/102857291-59d3ec80-4452-11eb-81d1-b054d5dc8fb2.JPG)

**Comment by DanielnetoDotCom** [comment]
@elias2k1 we do not have the option to hide the video owner

**Comment by elias2k1** [comment]
@DanielnetoDotCom Thanks for your reply. Do you have any future plan on this?

**Comment by DanielnetoDotCom** [comment]
Not now, but you can sponsor this feature,

If you want, ask for a feature quotation on this email developer@youphptube.com

**Comment by elias2k1** [comment]
Thanks for your suggestion.
