### ISSUE TITLE
live users and views counter

### ISSUE THREAD

**Issue by awistudio** [WWBN/AVideo#4213]
![kax](https://user-images.githubusercontent.com/60708776/102864394-57fb3080-4434-11eb-8a5e-5d5a4dc2a8cd.jpg)
total views  bad result. I tested several times

Avideo 10.0!

**Comment by DanielnetoDotCom** [comment]
what do you mean?

**Comment by awistudio** [comment]
1444
shows 1444 views.
new transmission and the same 1444
I don't have that many views

**Comment by DanielnetoDotCom** [comment]
Reset the stream key
