### ISSUE TITLE
Hiding encoder options

### ISSUE THREAD

**Issue by dbmasters** [WWBN/AVideo#4214]
How can I hide the import and bulk upload options in the encoder? I have looked thru all the options in config, and I can't find any unique class or id options to hide them with CSS.

Is there a dynamic option so I don't have to hack core code?

**Comment by DanielnetoDotCom** [comment]
In your encoder configuration.php try to add `$global['disableBulkEncode'] = true;`

**Comment by dbmasters** [comment]
Well, that didn't work, nor does it address the importing issue.

Also, encoder is still referencing youPHPTube* in a spot or two and erroring out, encoder isn't properly moving files to the streamer site. I've changed one difference (to pictureReceived.php) from youPHPTube to aVideo, still not working...not sure what's wrong, but something is wrong in the distributed encoder. Any updates coming soon?

**Comment by akhilleusuggo** [comment]
what version are you running ?
Also make sure to clear the streamer cache , or will not update the new config .
