### ISSUE TITLE
Bug backgroud image category

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#4215]
hello @DanielnetoDotCom  I show you images as you can see I am on the demo site, I added two images there is one that does not appear

![image](https://user-images.githubusercontent.com/39193219/102949856-92fb7380-44c9-11eb-94d7-f35e6fc454c8.png)

![image](https://user-images.githubusercontent.com/39193219/102949928-bf16f480-44c9-11eb-9eeb-9b3d9a2e6ba2.png)

**Comment by DanielnetoDotCom** [comment]
try clear the cache.

**Comment by syldri** [comment]
just to know that there is an option to enable or disable the display this is two image?

I updated the site, delete the caches there is nothing in the category

**Comment by DanielnetoDotCom** [comment]
Check the customizeAdvanced ->  showCategoryTopImages

**Comment by syldri** [comment]
hello jean i did a new installation of the site, there are a lot of bugs i will start with this him

I have the site cache and my browser nothing works

![image](https://user-images.githubusercontent.com/39193219/104107135-7b3e3080-52ba-11eb-9436-5f3592931bff.png)

![image](https://user-images.githubusercontent.com/39193219/104107414-47fca100-52bc-11eb-93f0-5dca637411e8.png)


![image](https://user-images.githubusercontent.com/39193219/104107527-19cb9100-52bd-11eb-906c-65ded0f55f04.png)

**Comment by DanielnetoDotCom** [comment]
> hello @DanielnetoDotCom i did a new installation of the site, there are a lot of bugs i will start with this him

what bug?

> I have the site cache and my browser nothing works

what is not working?
