### ISSUE TITLE
Can ZoomMeetingRecorder Plugin check finished process recordings ? 

### ISSUE THREAD

**Issue by DrDracula** [WWBN/AVideo#4216]
When the Processing Zoom Recordings take a long time, ZoomMeetingRecorder Plugin cant transfer video. Can ZoomRecorderPlugin check recordings again, if the process is done?

**Comment by DanielnetoDotCom** [comment]
The process comes from zoom, zoom have to request to AVideo to grab its recorded meet using Zoom webhook

**Comment by DrDracula** [comment]
I see now. I got my answer. Thank you for your help.
