### ISSUE TITLE
Social Login and ID's

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4217]
Step by step

1. I enabled Google as a social login
2. I put in my client ID and secret
3. I logged out and tried to login via Google. Failed.
4. I went back to confirm my ID/secret but this is what i get

![no_id](https://user-images.githubusercontent.com/65451390/102996262-d68ac780-4533-11eb-9bd7-bf0d382415a4.PNG)

5. I updated the site today. Still no change.

Doesn't matter what I do, I cannot edit the 2 parametres. @DanielnetoDotCom , @akhilleusuggo , is there something I'm doing wrong?

**Comment by DanielnetoDotCom** [comment]
On the code tab, delete all code and save it.

It will reset it to default

![Uploading image.png…]()

**Comment by jengajenga** [comment]
> On the code tab, delete all code and save it.
> 
> It will reset it to default
> 
> ![image](https://user-images.githubusercontent.com/18009293/103042736-5f682a00-4559-11eb-8f5f-16101604ca26.png)

Thanks. Let me try!

**Comment by jengajenga** [comment]
> On the code tab, delete all code and save it.
> 
> It will reset it to default
> 
> ![image](https://user-images.githubusercontent.com/18009293/103042736-5f682a00-4559-11eb-8f5f-16101604ca26.png)

Dan, it has worked. I have succeeded. Thank you very much. I'm closing this one.
