### ISSUE TITLE
oEmbed

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4218]
Hello do we have oEmbed on this project ?
When we embed videos on third party sites , oEmbed is requested , but returns with 404 error .

I think if we add oembed we may be able to embed videos on social media , such discord and others .

issues related ; https://github.com/WWBN/AVideo/issues/4171 and others

**Comment by DanielnetoDotCom** [comment]
where are you testing the oembed?

**Comment by akhilleusuggo** [comment]
For example discord . I Believe this is the solution for all the requests made until today to be able to embed videos on other sites ( including the playback ) without having to redirect them to the site , but right on the app .

Discord does requests ( reading from feedbacks ) and others .
<link type="application/json+oembed" href="where-the-oembed-info-is.json" 

But still I'm not sure if this gonna fix it , but if you have time you may take a look here https://oembed.com/

**Comment by DanielnetoDotCom** [comment]
Hi, I did look to oembed before, and I guess I already implemented it. but I have never found a place to test it

**Comment by DanielnetoDotCom** [comment]
where can I test the oembed?

**Comment by ronaldod** [comment]
Do you have a rest api for this defined somewhere ?

**Comment by akhilleusuggo** [comment]
I don't have . Teorically does wotk , but it's looking for it on the wrong location .

log file say : `AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/oembed/?format=json&url=https%3A%2F%2Fwww.example.com%2Fview%2FvideoEmbeded.php%3Fv%3D1061) FROM: 35.227.62.178 Browser: Mozilla/5.0 (compatible; Discordbot/2.0; +https://discordapp.com) SCRIPT_NAME: /view/oembed.php`

This is a discord example . It is a working example with a confusing result , `">iFrame is not supported!<\/iframe><\/div>"}`

**Comment by DanielnetoDotCom** [comment]
If I find somewhere to test it I probably can give some more progress

**Comment by ronaldod** [comment]
will this help ?  

- [link 1](https://embed.ly/providers/validate/oembed) 
- [link 2](http://debug.iframely.com/) 
- [link 3](https://jsfiddle.net/bcmoney/pG6Zt/)

**Comment by DanielnetoDotCom** [comment]
I tested and seems to be fine for me 

http://debug.iframely.com/?uri=https%3A%2F%2Fdemo.avideo.com%2Fvideo%2F242%2Favideo1080hd%3Fpage%3D1

https://demo.avideo.com/oembed/?format=xml&url=http%3A%2F%2Fdemo.avideo.com%2Fview%2F%3Fv%3D242%26page%3D1

https://demo.avideo.com/oembed/?format=json&url=http%3A%2F%2Fdemo.avideo.com%2Fview%2F%3Fv%3D242%26page%3D1

I sent an update to make sure this one will validate
https://embed.ly/providers/validate/oembed?endpoint=https%3A%2F%2Fdemo.avideo.com%2Foembed%2F&url=https%3A%2F%2Fdemo.avideo.com%2Fvideo%2F242%2Favideo1080hd%3Fpage%3D1

![image](https://user-images.githubusercontent.com/18009293/103814269-268f8100-5040-11eb-81bd-f47e96dfbe90.png)

**Comment by ronaldod** [comment]
Did a test from mine servers. Also could not see a problem. Facebook was showing it properly.

**Comment by akhilleusuggo** [comment]
@ronaldod Discord showing the video ?
Could you make a screenshot ?

**Comment by ronaldod** [comment]
![image](https://user-images.githubusercontent.com/31585599/103870105-8bdc8400-50cb-11eb-8677-ddf0a5e526db.png)

**Comment by ronaldod** [comment]
If you look in the debug links you see a note that says "no iframe support".  So the  "basic" works just need to add iframe support.

**Comment by akhilleusuggo** [comment]
> I tested the youtube link and that is diffent. And is embedding the video.
> So that is then the difference.

Exactly ... Because this option does not differ from **Link (HTML):** , picture pointing to url .
![image](https://user-images.githubusercontent.com/52116577/103872920-b2a0b780-50d7-11eb-9979-23c145ee8a0d.png)

> If you look in the debug links you see a note that says "no iframe support".

Well , that's the only usefulness of the iframe , isn't it ?

> This is a discord example . It is a working example with a confusing result , ">iFrame is not supported!<\/iframe><\/div>"}

It's basically iframe option that doesn't support iframe . That is my understanding , and maybe I'm wrong . I'm not sure where the issue is coming from . And yes , twitch , youtube and all the social media can playback the video from discord browser without issues .

**Comment by DanielnetoDotCom** [comment]
Good news: I figure out how to embed players on discord. it also may work in other platforms

To embed it requires the SecureVideosDirectory plugin to be disabled and the videos to be MP4 or you allow the download to your files (for HLS)

**Comment by akhilleusuggo** [comment]
WOWOW , nice , let me try .

**Comment by akhilleusuggo** [comment]
Hmmm , still not working for me ( tested algo on demo site )

Does this has something to do with YTP-Storage ?

**Comment by akhilleusuggo** [comment]
The source file does work ( from source link )

I'm not sure what you did exactly , but how will discord or others determine what quality to chose ?

**Comment by DanielnetoDotCom** [comment]
Hi

the demo was not updated, I just did update it, please try again with demo

I just tried this link https://demo.avideo.com/video/242/avideo1080hd?page=1

I also updated the code so now there is a comment why the source video file was not shared

**Comment by DanielnetoDotCom** [comment]
Now I disable the secure plugin it shows the video but for some reason converted HLS files are not playing 

![image](https://user-images.githubusercontent.com/18009293/103930508-9f084780-50fd-11eb-90a9-62530e48285f.png)

**Comment by DanielnetoDotCom** [comment]
Also, I just sent some updates so you can use videos on the HLS YPTStorage as well

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Still doesn't work for me . I do have apache2 XsendFile enabled on apache2 conf ( to download HLS into mp4 ) . Should I disable it ?

And where did you inspected this ? 

![image](https://user-images.githubusercontent.com/52116577/103942245-c6c8d100-5138-11eb-88ac-46f94f2a5cf2.png)

**Comment by akhilleusuggo** [comment]
So I need to enable '' get tags " ?
![image](https://user-images.githubusercontent.com/52116577/103942566-48b8fa00-5139-11eb-846d-66938f369e00.png)

![image](https://user-images.githubusercontent.com/52116577/103942658-67b78c00-5139-11eb-9997-71ea482e1d72.png)

**Comment by DanielnetoDotCom** [comment]
Hi, 

I guess the get tags have nothing to do with it.

Is the file you are trying to share HLS or MP4?

can you check if works with MP4?

**Comment by akhilleusuggo** [comment]
Checked the mp4 , and not working

**Comment by DanielnetoDotCom** [comment]
what is the message on MP4 videos? (I mean HTML commend)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 
![image](https://user-images.githubusercontent.com/52116577/104026786-19ed6300-51cf-11eb-9f6c-a1f752c1be2e.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure why it is not returning the source file on your side.

there is anything on the log file regarding the Video::getSourceFile method?

**Comment by akhilleusuggo** [comment]
`AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/oembed/?format=json&url=https%3A%2F%2Fwww.zzzz.com%2Fview%2F%3Fv%3D2689%26channelName%3DKekurazo) FROM: 35.227.62.178 Browser: Mozilla/5.0 (compatible; Discordbot/2.0; +https://discordapp.com) SCRIPT_NAME: /view/oembed.php`

![image](https://user-images.githubusercontent.com/52116577/104038162-98e99800-51dd-11eb-974b-f96971ff1a75.png)

Like i've said , do you think this has something to do with apache XSendFile ?
On apache2 conf I have ; 

```
<Directory /var/www/html/AVideo/>
    Options Indexes FollowSymLinks
    XSendFile on
    XSendFilePath /var/www/html/AVideo/
    AllowOverride All
    Require all granted
    Order Allow,Deny
    Allow from All
</Directory>
```

**Comment by DanielnetoDotCom** [comment]
Hi, I do not think it has something to do with XSendFile.

For some reason, it starts to happen with me on the tutorials site and I guess I found the issue please update and try again

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom It work , I just have some questions ,

What quality does select by default on the mp4 ( NOT HLS to MP4) .
Anyway to record +1 view on play ?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Any option to disable this function since it's not working properly ?
Also enabled the HLS download protector and is not working .

**Comment by DanielnetoDotCom** [comment]
> @DanielnetoDotCom It work , I just have some questions ,
> 
> What quality does select by default on the mp4 ( NOT HLS to MP4) .

Probably the highest resolution

> Anyway to record +1 view on play ?

Not yet but maybe in the future

> I don't really understand how this work . The video is uploaded somewhere . Where the videos does uploads . Can't really find anything on the code .
> Actually it's uploaded permanently on discord ... This is bad approach . Even deleting the video ( from site ) , keeps it on the discords .

the video does not upload, it plays the MP4 directly from your site

**Comment by DanielnetoDotCom** [comment]
> @DanielnetoDotCom Any option to disable this function since it's not working properly ?

disable what? what is not working?

> Also enabled the HLS download protector and is not working .

why it is not workin? because of the MP4 conversion?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom It is not working as should be . We're just tricking the server , not making it work .
The video is uploaded to discord , nothing else . When you embed a video to discord , even if you delete it from your site , is still playbackable . You can see this since playing any video does not consuming bandwidth or any resources . Also not making any request .

**Comment by DanielnetoDotCom** [comment]
> @DanielnetoDotCom It is not working as should be . We're just tricking the server , not making it work .
> The video is uploaded to discord , nothing else . When you embed a video to discord , even if you delete it from your site , is still playbackable . You can see this since playing any video does not consuming bandwidth or any resources . Also not making any request .

It is working and it is not a trick, maybe discord cache the video locally that is why still playable, but if you do not want to share it you can enable the SecureVideosDirectory plugin

**Comment by akhilleusuggo** [comment]
Yes , that's what I'm doing . Is not about sharing , but we're not really embedding the videos ( the player is not real )
There is not video player , no quality selection , basically nothing . Like reading the video from 1 of it source files .

**Comment by DanielnetoDotCom** [comment]
correct, discord needs to access the MP4 video directly, otherwise, it will not embed it.

**Comment by akhilleusuggo** [comment]
The only question remaining before closing this issue is , why other platforms can embed the videos with videojs ? such youtube,twitch etc without having to do all this stuff ? Twitch and youtube both are in DASH/HLS

**Comment by DanielnetoDotCom** [comment]
please give me a link sample where they can embed a player with videojs, if it does exist I probably can do the same.

I think they treat youtube, twitch, vimeo, etc differently

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 

![image](https://user-images.githubusercontent.com/52116577/104130347-d0d91280-5378-11eb-9e57-2ce040f67975.png)

I'm not sure if that gonna solve it .

Reading forums , I understood that only via API is possible to integrate iframes ( for security reasons )

So maybe we should revert back the changes .

**Comment by DanielnetoDotCom** [comment]
I can imagine should be something else to use iframes, but I do not think to revert the changes, let oembed play/cache the videos is fine for me.

if you want to protect just enable the SecureVideosDirectory plugin

**Comment by akhilleusuggo** [comment]
Yes , but that means that users who want to embed the videos on other sites , have to write every time the site-names ...

I'll revert  the changes for myself , because at the least my users does embed a lot on discord , and with this way of caching/storing/downloading is killing it , and low quality on top of it ( discord does re-render it in most cases to save space to 480p low bitrate )

**Comment by akhilleusuggo** [comment]
thanks for the time and effort 👍

**Comment by DanielnetoDotCom** [comment]
do you mean the whitelist thing?

just uncheck them and you should be fine to embed it anywhere and the oembed will not use your file direct access

![image](https://user-images.githubusercontent.com/18009293/104132610-433bf980-535d-11eb-85ac-b2cff0bcebfd.png)

**Comment by heme007** [comment]
Hello, I don't have the SecureVideosDirectory plug-in, if I buy it can I solve my Oembed problems? I can't share videos on any platform, I have the same problems as the others on this topic.

**Comment by DanielnetoDotCom** [comment]
@heme007 are you running the latest version?

**Comment by heme007** [comment]
Olá @DanielnetoDotCom , sim estou usando a nova versão.
![fundo](https://user-images.githubusercontent.com/49640083/105840543-ed4c9000-5fb1-11eb-8703-aacc8a456d68.png)

**Comment by DanielnetoDotCom** [comment]
Mesmo assim faça o `git pull` pra ter certeza que voce tem os arquivos mais recentes

**Comment by heme007** [comment]
Olá @akhilleusuggo , Did you manage to solve the problem with Oembed?

**Comment by akhilleusuggo** [comment]
@heme007 The video does work, but not as expected.

Discord ( in my use case ), will download your video ( literally ), then re-host it for you. 

This is not bad, but also very bad. Reasons:
 ### Cons:
1- You don't get any statistics who watched your videos or anything at all.
2- You don't have control at all over the video. If happens that you delete the video, the video does not get deleted on Discord or other social media, since it is downloaded.
3- The resolution if very random, and depends on the bandwidth.

 ###Pros:
1- You saving some bandwidth.
