### ISSUE TITLE
Top menu Problem

### ISSUE THREAD

**Issue by peterflitz** [WWBN/AVideo#4219]
Hello,

for a few days I have had an X in the top right corner of the top menu (see image attachment)
This means that the top menu no longer has any function.

Where can I change that ?
The latest updates are installed.

greeting
peterflitz
![what_is_this](https://user-images.githubusercontent.com/76056428/103017055-54a29a80-4543-11eb-8642-c0200ff66ec7.png)

**Comment by DanielnetoDotCom** [comment]
Update your code again. It should be already fixed

**Comment by peterflitz** [comment]
Hi Daniel,

Thank you for your prompt reply.

I performed the update again, no new update available.
Cache emptied via siteConfiguration.
Bwosercache emptied and various browsers tested.

The problem is still there.

What can I do?

**Comment by DanielnetoDotCom** [comment]
can you reproduce it on demo site so I can test?

**Comment by peterflitz** [comment]
Hello,

which function is causing this, can I deactivate it?

Everything is ok on the home page.
When I click on a video, this X comes up and the top menu is deactivated.
If I click on the X, I come back to the home page and the X remains, the top menu remains deactivated.

I didn't make any changes, the X suddenly appeared.
With an update?

**Comment by DanielnetoDotCom** [comment]
As long as I cannot reproduce, I do not know where it comes from

**Comment by peterflitz** [comment]
hmmh,

this show the element:
`<a href="https://www.site.com/video/803/videoname?channelName=username" id="closeBtnFull" class="pull-right">
        <i class="fas fa-times"></i>
    </a>`

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I confirm , the issue persists after update .

**Comment by DanielnetoDotCom** [comment]
How can I reproduce it?

can it be done on demo?

**Comment by peterflitz** [comment]
i cant post server-logins and page-logins here from my demo-site ...

**Comment by DanielnetoDotCom** [comment]
I mean you need to reproduce on my demo site https://demo.avideo.com/

for me to look into your server i need to charge for support

**Comment by peterflitz** [comment]
I have a main page and 2 different demo pages with different settings.
I have just performed an update on one of the demo sites, and the problem was there right after the update.
Before, before the update, everything was fine.

This has just been done as an update, see picture in the attachment
![updateprob](https://user-images.githubusercontent.com/76056428/103027149-9dfbe580-4555-11eb-977f-eddd9e1a5935.png)

**Comment by peterflitz** [comment]
The problem is probably with the caregories, or channels

**Comment by peterflitz** [comment]
For my main page it would be important how I can undo the update, I think 3 updates back

**Comment by DanielnetoDotCom** [comment]
I could reproduce it on demo, I am checking now

**Comment by DanielnetoDotCom** [comment]
please try this new update

**Comment by peterflitz** [comment]
It works very well as far as I can see.
Thank you Daniel
