### ISSUE TITLE
UTF8 on sitemap

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#4220]
Hi,

I noticed that sitemap does not support UTF8 characters.

**Comment by DanielnetoDotCom** [comment]
It does suppose to work, but maybe you have some other character that is breaking the XML

**Comment by akhilleusuggo** [comment]
mine is broke too .. but there's nothing on the logs . Can you add some log error so we can fix the titles ?

**Comment by DanielnetoDotCom** [comment]
can you identify what work is breaking it so I can test on my side?

**Comment by tonuzo** [comment]
You can try these characters at least äääääÄÄÄÄÄ öööööÖÖÖÖÖÖ.

I tried to reproduce on demo site, but sitemap couldn't be created (error).

**Comment by DanielnetoDotCom** [comment]
It works on the demo site 

![image](https://user-images.githubusercontent.com/18009293/103239740-3ff04900-492d-11eb-8231-d4267cea1950.png)

**Comment by akhilleusuggo** [comment]
```
AVideoLog::DEBUG: siteMap: getAllVideos 19927 SCRIPT_NAME: /objects/configurationGenerateSiteMap.json.php
AVideoLog::DEBUG: getVideosURL_V2: do NOT recreate lifetime = 0 SCRIPT_NAME: /view/index.php
AVideoLog::DEBUG: getVideosURL_V2: do NOT recreate lifetime = 0 SCRIPT_NAME: /view/index.php
AVideoLog::DEBUG: getVideosURL_V2: do NOT recreate lifetime = 0 SCRIPT_NAME: /view/index.php
AVideoLog::DEBUG: getVideosURL_V2: do NOT recreate lifetime = 0 SCRIPT_NAME: /view/index.php
AVideoLog::DEBUG: getVideosURL_V2: do NOT recreate lifetime = 0 SCRIPT_NAME: /view/index.php
AVideoLog::DEBUG: getVideosURL_V2: do NOT recreate lifetime = 0 SCRIPT_NAME: /view/index.php
AVideoLog::DEBUG: getVideosURL_V2: do NOT recreate lifetime = 0 SCRIPT_NAME: /view/index.php
AVideoLog::DEBUG: getVideosURL_V2: do NOT recreate lifetime = 0 SCRIPT_NAME: /view/index.php
...............................
```

Is not working . Also in your screen, you can see that the description is broken .
Can you please add some error log , to be able to track what URL/videoID is breaking the sitemap . I'm not saying that is not generating the sitemap , but it's looping .
![image](https://user-images.githubusercontent.com/52116577/103241319-7b097100-495b-11eb-83cc-c771e30b5247.png)

Also I wanna say , that is not about the sitemap limit ; 

```
AVideoLog::DEBUG: siteMap: start SCRIPT_NAME: /objects/configurationGenerateSiteMap.json.php
AVideoLog::DEBUG: siteMap: rowCount 50000  SCRIPT_NAME: /objects/configurationGenerateSiteMap.json.php
AVideoLog::DEBUG: siteMap: getAllUsers 197 SCRIPT_NAME: /objects/configurationGenerateSiteMap.json.php
AVideoLog::DEBUG: siteMap: getAllCategories 41 SCRIPT_NAME: /objects/configurationGenerateSiteMap.json.php
```

rowCount 50000

**Comment by tonuzo** [comment]
The description is the problem. Those characters don't print but normal characters do.

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo  It removes the non-English chars to avoid XML problems.

So it is generating the site map but is not printing the UTF8 chars correct?

**Comment by tonuzo** [comment]
correct

**Comment by DanielnetoDotCom** [comment]
Try this update.

It will try to preserve the UTF8, in case it fails you can revert it by checking the option siteMapUTF8Fix on the Customize advanced plugin

**Comment by tonuzo** [comment]
This works now. Thanks!
