### ISSUE TITLE
ThumbsSprit 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4221]
Some files fails to generate the ThumbsSprit.jpg , is there anyway to determine ( automatically ) witch one of them , instead of checking all the videos ?

Also can you change the name of the failed ones to something like , FailedThumbsSprit.jpg

![image](https://user-images.githubusercontent.com/52116577/103025263-1c5a8680-455a-11eb-94e1-0514a6f6ae04.png)

**Comment by DanielnetoDotCom** [comment]
if it generates a wrong ThumbsSprit it supposes to try again on the next request.

you may want to check on the logs why it is failing.

**Comment by akhilleusuggo** [comment]
No , it doesn't generate . I refreshed the page and cache multiple times , and nothing happens .
Also there's nothing on the page except normal logs

`Page generated in 0.2197 seconds. User: Not Logged - No Cache (/v/ID?channelName=whatever) FROM: IP Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 SCRIPT_NAME: /view/index.php`

**Comment by DanielnetoDotCom** [comment]
I am detecting a wrong spirit based on the image filesize. 
maybe yours has a different filesize.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 

> I am detecting a wrong spirit based on the image filesize.
> maybe yours has a different filesize.

This is a wrong way ... You can't compare a video of 1h with a clip of 30s . Each will have a huge difference on size , even if both are correctly generated .

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I think I have found another issue ; I've never seen this before . It when I try to get to the source file of the video , because I though it was corrupted or something .

![image](https://user-images.githubusercontent.com/52116577/103047636-ceaf3f80-4594-11eb-9200-e786b198d255.png)

**Comment by akhilleusuggo** [comment]
Ok , I see what is wrong here . The plugin does make the request to 5fc31805b15689.30654193.mp4 and it's skipping the resolution . It's treating the file as if it was hls .

Debugging and sending a fix

**Comment by akhilleusuggo** [comment]
Yeh , the problem is on the encoder side . The video url sent/requested is wrong .

**Comment by akhilleusuggo** [comment]
I need to see how the request is made , tomorrow i'll take a look hopefully . For now I'm disabling this plugin .
