### ISSUE TITLE
Problem with the update disabling the PlayerSkins component

### ISSUE THREAD

**Issue by abed-ahmed** [WWBN/AVideo#4222]
When I updated the version, I passed a problem with the PlayerSkins plugin, as shown in the attached screenshot ?
![22](https://user-images.githubusercontent.com/72515889/103032156-0d7ad080-4568-11eb-9137-e5a999516dd6.JPG)

**Comment by akhilleusuggo** [comment]
Why would you disable it ?
This plugin is for videojs skin ( layout )

**Comment by abed-ahmed** [comment]
I did not understand what you mean ?

**Comment by akhilleusuggo** [comment]
This plugin can not be disabled because it's essential . Without it the videos wouldn't play , or would looking like this ; 

![image](https://user-images.githubusercontent.com/52116577/103032816-abbb6600-4569-11eb-8385-d37acbfb470b.png)


Also you won't be able to select quality.
And HLS wont work .

**Comment by abed-ahmed** [comment]
I mean, how do I activate this component

**Comment by akhilleusuggo** [comment]
It is activated by default ( like many other plugin ) , customize advanced , customize users and other . You don't need to do anything .

Just customize ( choose ) what layout you want , and it's done .

**Comment by abed-ahmed** [comment]
It is activated by default before new updates when I updated I encountered this problem

**Comment by DanielnetoDotCom** [comment]
I do not see any problem on the screenshot

**Comment by akhilleusuggo** [comment]
@abed-ahmed I think what you don't understand is 👍 

If you don't see that you can activate it , that mean it is activated by default
If you see that you can enable/disable , that mean you can do it .

To debug if there's any problem , go to Edit Parameters , change the skin to for example twitch , facebook or any on the list , clear the cache , and see if it works .

![image](https://user-images.githubusercontent.com/52116577/103033633-95aea500-456b-11eb-86f9-238a38b0dfc6.png)

![image](https://user-images.githubusercontent.com/52116577/103033696-b971eb00-456b-11eb-9302-1c689f55a1d4.png)

**Comment by abed-ahmed** [comment]
Good friend, things are so good
But I am facing another problem with live broadcasting which is the inability of the ios phone to full screen mode؟

**Comment by DanielnetoDotCom** [comment]
I am. It aware about iOS problem please open a new issue and provide some screenshots and more details
