### ISSUE TITLE
The live broadcast is offline and opens the broadcast you previously posted

### ISSUE THREAD

**Issue by abed-ahmed** [WWBN/AVideo#4223]
I am facing a problem with the new version which is that the live broadcast is not connected to the internet and opens the broadcast that opens the video that I broadcast previously, and this did not happen in the previous version. You can also see the difference between the old and the new version in the attached video ?

https://user-images.githubusercontent.com/72515889/103043156-930c7980-4584-11eb-940b-b78ebba6f2e8.mp4

**Comment by DanielnetoDotCom** [comment]
If you do not want that you have to change something on your nginx.conf
I am not sure what to change, you may want to ask it on the [nginx rtmp github repository](https://github.com/arut/nginx-rtmp-module)

**Comment by abed-ahmed** [comment]
But when you change the broadcast key it becomes normal?

**Comment by akhilleusuggo** [comment]
Remove the `hls_playlist_lengh` from nginx.conf

**Comment by abed-ahmed** [comment]
I will do that

**Comment by abed-ahmed** [comment]
Thank you, brother, you did it and the operation worked

**Comment by akhilleusuggo** [comment]
happy to help .
