### ISSUE TITLE
Unlisted video is displayed as first ?

### ISSUE THREAD

**Issue by peterflitz** [WWBN/AVideo#4225]
Hello,

if the most recently uploaded video is unlisted, it will not appear in the Recent Videos list.
But it will appear as the first/newest video.

Not listed means, only visible in the channel?

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/Videos-Privacy-Options-:-Private-,-Public-,-Unlisted-&-UserGroup

**Comment by peterflitz** [comment]
Hello,

it was meant as a suggestion.

If a user posts their video as unlisted, should it still be listed as "newest video"?

The detour for the user:
Deactivate video until another video is uploaded and listed as the newest video.

Listed or not listed ;-)

**Comment by DanielnetoDotCom** [comment]
Unlisted videos may appear for admin.

**Comment by peterflitz** [comment]
Everyone sees the latest video, whether listed or unlisted.

**Comment by DanielnetoDotCom** [comment]
can you reproduce it on demo?

**Comment by peterflitz** [comment]
Your Demo different ...

See picture -> newest video.
![default](https://user-images.githubusercontent.com/76056428/103245380-49df6f80-4960-11eb-9d13-074b5d6d48e5.png)

**Comment by akhilleusuggo** [comment]
https://user-images.githubusercontent.com/52116577/102792046-964f0c00-43b0-11eb-8511-ff902d32314c.png

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/102792046-964f0c00-43b0-11eb-8511-ff902d32314c.png)

**Comment by DanielnetoDotCom** [comment]
@peterflitz are you sure you are not logged as admin?

**Comment by peterflitz** [comment]
@DanielnetoDotCom

i've tested it on multiple devices, including different connections.

Look, you know my url, if you see an article as the first video, this article is as "not listed"

**Comment by akhilleusuggo** [comment]
clear the cache . If you have selected HidePrivateVideos , should work after clearing the cache .
