### ISSUE TITLE
Jibri integration: Live stream option is missing from meet  plugin (jitsi)

### ISSUE THREAD

**Issue by matheusfillipe** [WWBN/AVideo#4226]
The default jitisi web client features this broadcast option that you can use to stream to any rtmp server really, even though it is written youtube key there. The interface that meet currently has doesn't have this button even though I am connected to a server that I set up with jibri and has it. I intent to use this to broadcast conferences with other users on the site in an easy way.

From the jitsi site:

![image](https://user-images.githubusercontent.com/24435787/103068280-952e0280-459b-11eb-8d8d-a911adcbf043.png)

From avideo's meet plugin:

![image2](https://user-images.githubusercontent.com/24435787/103068291-98c18980-459b-11eb-87a4-d1a8263fb981.png)

Or is there a better way to go about this problem already?

**Comment by DanielnetoDotCom** [comment]
We use a modified jitsi with a modified jibri.

the source code for this is not opensource. if you want to use this feature integrated with AVideo you must use one of our servers.

**Comment by guymass** [comment]
Can't you at lease create a plugin or point us in the right direction on how to get that feature working? We are willing to pay a one off fee to get it working on our site.
