### ISSUE TITLE
Unable to edit user data or register new users.

### ISSUE THREAD

**Issue by lordtenteth** [WWBN/AVideo#4227]
I try to add new users or alter the admin user but constantly errors saying unable to edit user.

**Comment by DanielnetoDotCom** [comment]
share the logs

**Comment by lordtenteth** [comment]
How do i copy them and where from

**Comment by DanielnetoDotCom** [comment]
ctrl+c then ctrl+v

check this https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

and this 

![image](https://user-images.githubusercontent.com/18009293/103442182-ae395200-4c32-11eb-8c2a-54a69ebe0533.png)

**Comment by lordtenteth** [comment]
************ ******** *************** ***************** ****************** ******* ******* ****** ******* ****** *************** ** ****** ***** ******* ***** *** **** * ** ******** * ** ***** * ** **** * ** ******* * *********** * *********** * *************** * ************** * ** ****** * ** ******** * ** ************* * ** *********** * ** ***** * **  *********** * ** ************* * * * ************* * ** *************** * * *  ********** * * * ********* * * * ******* * * * ******** * * * ******* * * * ****** * * * **** * * * ************ * * *  ******** * ***** ***** ** * ** ************ **************************** - password

 ************ ******** *************** ***************** ***** ****** ****************************************************************************************************************** ******* ******* ****** ******* ****** *************** ** ****** ***** ******* ***** *** **** * ** ******** * ** ***** * ** **** * ** ******* * *********** * *********** * *************** * ************** * ** ****** * ** ******** * ** ************* * ** *********** * ** ***** * **  *********** * ** ************* * * * ************* * ** *************** * * *  ********** * * * ********* * * * ******* * * * ******** * * * ******* * * * ****** * * * **** * * * ************ * * *  ******** * ***** ***** ** * *********************************************************************************************************************************** ***** *** **** * ** ******** * ** ***** * ** **** * ** ******* * *********** * *********** * *************** * ************** * ** ****** * ** ******** * ** ************* * ** *********** * ** ***** * **  *********** * ** ************* * * * ************* * ** *************** * * *  ********** * * * ********* * * * ******* * * * ******** * * * ******* * * * ****** * * * **** * * * ************ * * *  ******** * ***** ***** ** * ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************* ********************************* ********************************** ************ **************************** - password

 [25-Dec-2020 07:21:16 UTC] PHP Warning:  fclose() expects parameter 1 to be resource, bool given in path/to/my/streamer/site/objects/configuration.php on line 393

 [25-Dec-2020 07:21:16 UTC] PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in path/to/my/streamer/site/objects/configuration.php on line 392

 [25-Dec-2020 07:21:16 UTC] PHP Warning:  fopen(path/to/my/streamer/site/videos/configuration.php): failed to open stream: Permission denied in path/to/my/streamer/site/objects/configuration.php on line 391

 [25-Dec-2020 07:20:57 UTC] PHP Warning:  fclose() expects parameter 1 to be resource, bool given in path/to/my/streamer/site/objects/configuration.php on line 393

 [25-Dec-2020 07:20:57 UTC] PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in path/to/my/streamer/site/objects/configuration.php on line 392

 [25-Dec-2020 07:20:57 UTC] PHP Warning:  fopen(path/to/my/streamer/site/videos/configuration.php): failed to open stream: Permission denied in path/to/my/streamer/site/objects/configuration.php on line 391

 [25-Dec-2020 07:20:52 UTC] PHP Warning:  fclose() expects parameter 1 to be resource, bool given in path/to/my/streamer/site/objects/configuration.php on line 393

 [25-Dec-2020 07:20:52 UTC] PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in path/to/my/streamer/site/objects/configuration.php on line 392

 [25-Dec-2020 07:20:52 UTC] PHP Warning:  fopen(path/to/my/streamer/site/videos/configuration.php): failed to open stream: Permission denied in path/to/my/streamer/site/objects/configuration.php on line 391

 [25-Dec-2020 07:20:52 UTC] PHP Warning:  fclose() expects parameter 1 to be resource, bool given in path/to/my/streamer/site/objects/configuration.php on line 393

 [25-Dec-2020 07:20:52 UTC] PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in path/to/my/streamer/site/objects/configuration.php on line 392

 [25-Dec-2020 07:20:52 UTC] PHP Warning:  fopen(path/to/my/streamer/site/videos/configuration.php): failed to open stream: Permission denied in path/to/my/streamer/site/objects/configuration.php on line 391

 [25-Dec-2020 07:20:50 UTC] PHP Warning:  fclose() expects parameter 1 to be resource, bool given in path/to/my/streamer/site/objects/configuration.php on line 393

 [25-Dec-2020 07:20:50 UTC] PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in path/to/my/streamer/site/objects/configuration.php on line 392

 [25-Dec-2020 07:20:50 UTC] PHP Warning:  fopen(path/to/my/streamer/site/videos/configuration.php): failed to open stream: Permission denied in path/to/my/streamer/site/objects/configuration.php on line 391

**Comment by DanielnetoDotCom** [comment]
Hi

what didn't you understand from the log?

`PHP Warning: fopen(path/to/my/streamer/site/videos/configuration.php): failed to open stream: Permission denied in path/to/my/streamer/site/objects/configuration.php on line 391`

**Comment by lordtenteth** [comment]
ajusted the permissions on the file and it still didn't fix the issue

**Comment by DanielnetoDotCom** [comment]
check your logs again

**Comment by lordtenteth** [comment]
Checked them again, still not allowing me to change users and this is all the logs are showing now.


************ ******** *************** ***************** ****************** ******* ******* ****** ******* ****** *************** ** ****** ***** ******* ***** *** **** * ** ******** * ** ***** * ** **** * ** ******* * *********** * *********** * *************** * ************** * ** ****** * ** ******** * ** ************* * ** *********** * ** ***** * **  *********** * ** ************* * * * ************* * ** *************** * * *  ********** * * * ********* * * * ******* * * * ******** * * * ******* * * * ****** * * * **** * * * ************ * * *  ******** * ***** ***** ** * ** ************ **************************** - password

 ************ ******** *************** ***************** ***** ****** ****************************************************************************************************************** ******* ******* ****** ******* ****** *************** ** ****** ***** ******* ***** *** **** * ** ******** * ** ***** * ** **** * ** ******* * *********** * *********** * *************** * ************** * ** ****** * ** ******** * ** ************* * ** *********** * ** ***** * **  *********** * ** ************* * * * ************* * ** *************** * * *  ********** * * * ********* * * * ******* * * * ******** * * * ******* * * * ****** * * * **** * * * ************ * * *  ******** * ***** ***** ** * *********************************************************************************************************************************** ***** *** **** * ** ******** * ** ***** * ** **** * ** ******* * *********** * *********** * *************** * ************** * ** ****** * ** ******** * ** ************* * ** *********** * ** ***** * **  *********** * ** ************* * * * ************* * ** *************** * * *  ********** * * * ********* * * * ******* * * * ******** * * * ******* * * * ****** * * * **** * * * ************ * * *  ******** * ***** ***** ** * ******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************* ********************************* ********************************** ************ **************************** - password


    


...

 ************ ******** *************** ***************** ****************** ******* ******* ****** ******* ****** *************** ** ****** ***** ******* ***** *** **** * ** ******** * ** ***** * ** **** * ** ******* * *********** * *********** * *************** * ************** * ** ****** * ** ******** * ** ************* * ** *********** * ** ***** * **  *********** * ** ************* * * * ************* * ** *************** * * *  ********** * * * ********* * * * ******* * * * ******** * * * ******* * * * ****** * * * **** * * * ************ * * *  ******** * ***** ***** ** * ** ************ **************************** - password

 ************ ******** *************** ***************** ***** ****** ****************************************************************************************************************** ******* ******* ****** ******* ****** *************** ** ****** ***** ******* ***** *** **** * ** ******** * ** ***** * ** **** * ** ******* * *********** * *********** * *************** * ************** * ** ****** * ** ******** * ** ************* * ** *********** * ** ***** * **  *********** * ** ************* * * * ************* * ** *************** * * *  ********** * * * ********* * * * ******* * * * ******** * * * ******* * * * ****** * * * **** * * * ************ * * *  ******** * ***** ***** ** * *********************************************************************************************************************************** ***** *** **** * ** ******** * ** ***** * ** **** * ** ******* * *********** * *********** * *************** * ************** * ** ****** * ** ******** * ** ************* * ** *********** * ** ***** * **  *********** * ** ************* * * * ************* * ** *************** * * *  ********** * * * ********* * * * ******* * * * ******** * * * ******* * * * ****** * * * **** * * * ************ * * *  ******** * ***** ***** ** * ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************ ********************************* ********************************** ************ **************************** - password


    


...

 ************ ******** *************** ***************** ****************** ******* ******* ****** ******* ****** *************** ** ****** ***** ******* ***** *** **** * ** ******** * ** ***** * ** **** * ** ******* * *********** * *********** * *************** * ************** * ** ****** * ** ******** * ** ************* * ** *********** * ** ***** * **  *********** * ** ************* * * * ************* * ** *************** * * *  ********** * * * ********* * * * ******* * * * ******** * * * ******* * * * ****** * * * **** * * * ************ * * *  ******** * ***** ***** ** * ** ************ **************************** - password

 ************ ******** *************** ***************** ***** ****** ****************************************************************************************************************** ******* ******* ****** ******* ****** *************** ** ****** ***** ******* ***** *** **** * ** ******** * ** ***** * ** **** * ** ******* * *********** * *********** * *************** * ************** * ** ****** * ** ******** * ** ************* * ** *********** * ** ***** * **  *********** * ** ************* * * * ************* * ** *************** * * *  ********** * * * ********* * * * ******* * * * ******** * * * ******* * * * ****** * * * **** * * * ************ * * *  ******** * ***** ***** ** * *********************************************************************************************************************************** ***** *** **** * ** ******** * ** ***** * ** **** * ** ******* * *********** * *********** * *************** * ************** * ** ****** * ** ******** * ** ************* * ** *********** * ** ***** * **  *********** * ** ************* * * * ************* * ** *************** * * *  ********** * * * ********* * * * ******* * * * ******** * * * ******* * * * ****** * * * **** * * * ************ * * *  ******** * ***** ***** ** * ************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************ ********************************* ********************************** ************ **************************** - password

**Comment by lordtenteth** [comment]
Okay after digging around the logs i found out when updating the software to version 10 it has skipped adding a SQL update (9.4) which adds in the canCreatMeet table. that was stopping me from editing or adding users.
