### ISSUE TITLE
Videos stuck loading on Mobile Devices

### ISSUE THREAD

**Issue by techiesces** [WWBN/AVideo#4228]
For some reason the past few days on various mobile devices the videos will not load... Like they are stuck not playing the ad or something.  On PC works fine, no issues.  Only on any mobile device.  Some devices video will play once and no longer play any other videos.

If I restart server videos will play once on mobile devices and then not load videos any longer after first one.

Nothing in logs for today to report as errors that I can see.

**Comment by DanielnetoDotCom** [comment]
If you clear the cache does it resolve?

can you reproduce it on demo site?
