### ISSUE TITLE
how to save videos to mega storage using ftp

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#4229]
Greetings I would like to know how to save videos on mega storage via ftp

**Comment by DanielnetoDotCom** [comment]
what is mega storage?

**Comment by mrgodgiven** [comment]
Its a storage platform like Dropbox

**Comment by mrgodgiven** [comment]
Mr D Neto Did you find a solution for me sir ?

**Comment by DanielnetoDotCom** [comment]
Hi, I do not think it is a good idea.

For example, GDrive will slow you down if you use their platform.

but anyway if you trust this mega storage and they allow you to use FTP to submit files. you may be able to use the FTP plugin
https://youphp.tube/marketplace/

![image](https://user-images.githubusercontent.com/18009293/103225492-c8102780-4908-11eb-9234-684be894bec6.png)
