### ISSUE TITLE
Videos not playing after update

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4234]
I am not sure if its related to the git pull I made last night, but since than I get the following error on every video.
![Screen Shot 5781-04-11 at 17 31 46](https://user-images.githubusercontent.com/58882903/103154671-8e70dc80-47a1-11eb-947d-37c3021bc96f.jpg)

not sure why as everything seems to be the same in my config files.

**Comment by akhilleusuggo** [comment]
The file itself if corrupted .
https://fetube.flatearth.co.il/videos/_YPTuniqid_5fbad240934cc7.65441878_240.mp4

**Comment by guymass** [comment]
all files?
 each and every one? how is this possible? would that have anything to do with YPTStorage plugin?

**Comment by syldri** [comment]
hello @guymass 

I saw that the left column is activated by default on his site 

You can share the information of the changes you made please


![image](https://user-images.githubusercontent.com/39193219/103157279-93d62300-47b1-11eb-9990-d755e3d985b1.png)

**Comment by akhilleusuggo** [comment]
I'm not sure , you need to debug things . 
Make sure you have enabled apache XSendFile . Also maybe you customized your site with something and after update you over-written it .

I can't really tell . What's on the log file ?

**Comment by akhilleusuggo** [comment]
Owww , I see . You're actually using NGINX
