### ISSUE TITLE
Nginx service not working

### ISSUE THREAD

**Issue by eZweblogic** [WWBN/AVideo#4235]
Trying to use live-streaming but it fails with an error message from OBS that streaming key is wrong and can't open channel etc..

Then I discovered that nginx server is not running. There's no error log as well. Everything else seems to work just fine
System is Dedicated Ubuntu 18.04 server

I tried starting Nginx but it failed many times

**Comment by akhilleusuggo** [comment]
without logs we can't help . 
You have to check logs on 2 location 

1- avideo.log
2- nginx logs ( `/usr/local/nginx/logs/error.log` ) or ( access.log )

**Comment by eZweblogic** [comment]
here's the error log
Appreciate your help
[AVideo-nginx-error.log](https://github.com/WWBN/AVideo/files/5744484/AVideo-nginx-error.log)

**Comment by akhilleusuggo** [comment]
Make sure you have the directory created ; `/HLS/live`

And could you page here your nginx config , is located on `/usr/local/nginx/conf/nginx.conf` ( there's no critical data ) . You can hide your domain name if you don't wanna share .

**Comment by eZweblogic** [comment]
HLS directory was created and it's writable (755)
here's my nginx conf.

user    www-data;    
worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 1s;
                            hls_fragment 10s;
                            on_publish http://localhost/YouPHPTube/plugin/Live/on_publish.php;
                            on_play http://localhost/YouPHPTube/plugin/Live/on_play.php;
                            on_record_done http://localhost/YouPHPTube/plugin/Live/on_record_done.php;

                            #exec ffmpeg -i rtmp://localhost/live/$name 
                            #    -c:a aac -strict -2 -b:a 96k -c:v libx264 -vf scale=-2:240 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1200k -b:a 96k -r 20 -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_low  
                            #    -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:480 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 2400k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_mid  
                            #    -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:720 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 4200k -bufsize 100000k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi;


                            recorder video{
                                record all;
                                record_path /var/www/tmp;
                                record_notify on;
                                record_max_size 2048M; 
                                record_suffix -%d-%b-%y-%T.flv;
                            }
                    }

                    #application adaptive {
                    #    live on; 
                    #    hls on; 

                    #    hls_path /HLS/live;
                    #    hls_nested on;

                    #    allow play all;
                    #    allow publish 127.0.0.1;
                    #    deny publish all;

                    #    hls_variant _low BANDWIDTH=400000;
                    #    hls_variant _mid BANDWIDTH=2100000;
                    #    hls_variant _hi  BANDWIDTH=4200000;
                    #}
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    #listen 8443 ssl;
                    #listen [::]:8443 ssl;
                    #include /usr/local/nginx/snippets/self-signed.conf;
                    #include /usr/local/nginx/snippets/ssl-params.conf;
                    listen 8080;
                    server_name localhost abbrak.live  www.abbrak.live ;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   
            
    listen 8443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/abbrak.live/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/abbrak.live/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
    }

**Comment by akhilleusuggo** [comment]
This installation is made by Daniel right ?

Could you show the Live-plugin parameters ?

**Comment by eZweblogic** [comment]
Yes installation done by Daniel

`{"button_title":"مباشر","server":"rtmp://abbrak.live/live","playerServer":"https://abbrak.live:8443/live","stats":"https://abbrak.live:8443/stat","restreamerURL":"https://abbrak.live/plugin/Live/standAloneFiles/restreamer.json.php","controlURL":"https://abbrak.live/plugin/Live/standAloneFiles/control.json.php","disableRestream":false,"disableDVR":false,"disableGifThumbs":false,"disableLiveThumbs":false,"hideTopButton":false,"useAadaptiveMode":false,"protectLive":false,"experimentalWebcam":true,"doNotShowLiveOnVideosList":false,"limitLiveOnVideosList":"12","doNotProcessNotifications":false,"useLiveServers":false,"disableMeetCamera":false,"playLiveInFullScreen":false,"hls_path":"/HLS/live","requestStatsTimout":"4","cacheStatsTimout":"15","requestStatsInterval":"15","streamDeniedMsg":"You can not stream live videos","doNotShowGoLiveButton":false,"useLowResolution":true}`

**Comment by akhilleusuggo** [comment]
1- Disable DVR
2- Disable restream
3- Disable useLowResolution

Restart rtmp-nginx ; `sudo /usr/local/nginx/sbin/nginx -s stop && sudo /usr/local/nginx/sbin/nginx`

**Comment by eZweblogic** [comment]
Thank you akhilleusuggo
It works now.
I had to change the on_publish and on_play etc.. to parameters on edit Live servers because old nginx file was pointing to YouPHPtube and localhost.

Things are back to normal. Thanks for your help

**Comment by akhilleusuggo** [comment]
you're welcome .
