### ISSUE TITLE
infinite-scroll first page , gallery theme 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4236]
I've changed the number of category to show when scrolling down the first page , to speed up the process to 5
https://github.com/WWBN/AVideo/blob/164c31dd6160a35f9b39523b52f53fab00e154ba/plugin/Gallery/view/modeGalleryCategory.php#L10

But what I want now really is to start pre-loading the page , before users reaches the bottom of the page . What I mean is , how to start loading ( infinite-scroll.pkgd.min.js ) , when users are scrolling down , and 1 or 2 categories are left before they reach the bottom ( footer ) , and start waiting the page to generate .

This way , the page will load faster ( from the user's experience )
Increasing the `rowCount` is good , but is heavy and still will make users wait for the page to generate . But if we make a preload , won't make the users wait .

Any idea ?

**Comment by DanielnetoDotCom** [comment]
I already try to preload it before the user reaches the bottom. but the codes I found does not work
