### ISSUE TITLE
Download Video Buttons missing from Video Manager

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4237]
After last update I no longer see the Download Low and HD in the video Manager

![89e0ad82-dc37-4d3d-8a6c-0cd1d511e5aa](https://user-images.githubusercontent.com/39392449/103167452-db2fd400-47f0-11eb-8428-9504b8e42f4b.png)

**Comment by sipero** [comment]
I had the same issue and managed to revert pack my Video to the previous git pull version

**Comment by akhilleusuggo** [comment]
reported this to Daniel after the new update of downloading HLS videos ( into mp4 automatically ). But aparently he didn't understand me , or ignored it . https://github.com/WWBN/AVideo/issues/4108

**Comment by DanielnetoDotCom** [comment]
@JoshWho it appears for me are you sure you are running the latest version?

![image](https://user-images.githubusercontent.com/18009293/103229947-e713b700-4912-11eb-8996-d1f7da3459fb.png)

**Comment by sipero** [comment]
I updated to the latest version yesterday and I then had the same issue. I reverted to the version that I think was about 1 week ago and then I got the image and download icons back again

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Daniel , I'm sure you're not on the latest version on the demo site . It's always outdated .

Maybe you could add a crontab to the demo-site ? Every 1h to git pull --hard-reset .

**Comment by DanielnetoDotCom** [comment]
I just update the demo to the latest

**Comment by DanielnetoDotCom** [comment]
Do you have this checked?

![image](https://user-images.githubusercontent.com/18009293/103254001-5795f480-4962-11eb-8cc8-fa4341f9c27a.png)

**Comment by akhilleusuggo** [comment]
No , because I don't want to make it public .
But I see that the description is misleading . Before I had it disabled , and videos did show the download bouton , now not anymore .

Works if I enable it , but it wasn't like this before .

**Comment by DanielnetoDotCom** [comment]
Please give me more details on what you mean by "description is misleading"

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom This description is misleading . For my understanding , this should give a download botton at the video's footer player ( new tab near share option , add playlist option etc) 

![image](https://user-images.githubusercontent.com/52116577/103291330-2534d780-49f4-11eb-9d24-12532f63c322.png)

**Comment by DanielnetoDotCom** [comment]
This new update will give you a button on the videos manager that will tell you why you cannot download the file 

![image](https://user-images.githubusercontent.com/18009293/103296693-581ba300-49d5-11eb-8567-7eb9d44f766f.png)
