### ISSUE TITLE
Text not Visible in Subscribes Message Box Gallery Theme

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4239]
The font looks to be white and it is on a white background.  Only way to see it is when you highlight the text.

![textnotvis](https://user-images.githubusercontent.com/39392449/103169530-171f6500-4802-11eb-8f9a-b8c6cab3bcf5.png)

**Comment by DanielnetoDotCom** [comment]
You have something changing your editor color, maybe some javascript

![image](https://user-images.githubusercontent.com/18009293/103227221-94370100-490c-11eb-8cf2-a7d231f2c3e9.png)

I do not know where this comes from but you probably can use this CSS fo make sure the text will be black

```
.wysihtml5-editor{
   color: #000 !important;
}
```

Add it to the configuration tab

**Comment by JoshWho** [comment]
I just added that to the header code on configurations cleared cache and still shows white text.

**Comment by DanielnetoDotCom** [comment]
I see now, it will not work, wysihtml5-editor is loading inside an iframe. so I have no control over it. and the CSS will not work. you can remove it

How are you changing the background to black?

I guess that is what is causing the white letters

**Comment by JoshWho** [comment]
From this code in the header script also

```
<style>

body {
  background-image: url("https://www.joshwhotv.com/242424.jpg");
  background-repeat: no-repeat;
  background-attachment:fixed;
  background-size:     cover; 
}

</style>
```

**Comment by DanielnetoDotCom** [comment]
Where this comes from?

`<script src="/cdn-cgi/apps/head/Bm0eT9eDa3fRO_ad29BtA00olrI.js"></script>`

I removed your ads script and it still appears.

I am not sure how did you inject this script into it.

maybe Cloudflare? there is a way for you to test it without Cloudflare?

**Comment by JoshWho** [comment]
live.joshwhotv.com maybe

**Comment by DanielnetoDotCom** [comment]
not working.

**Comment by JoshWho** [comment]
I need the 16 gig rebooted. I have no access it is locked up.

**Comment by DanielnetoDotCom** [comment]
Hey, does it still a problem?

**Comment by JoshWho** [comment]
It still shows white text on white background.

**Comment by DanielnetoDotCom** [comment]
The problem is, I do not know where your CSS comes from

**Comment by JoshWho** [comment]
The only css I ss it grabbing is the wys editors I have nothing set for text fields in css

**Comment by DanielnetoDotCom** [comment]
This does not happen on demo site, I am not sure where it comes from

![image](https://user-images.githubusercontent.com/18009293/103657618-de416780-4f48-11eb-9209-8da616efb316.png)

**Comment by JoshWho** [comment]
Could you please force this on that page's static file header? This will force the correct css for it but it cant be global.

```
<style>
element.style {
    background-color: rgb(255 255 255 / 0%);
    color: rgb(0 0 0);
    cursor: text;
    font-family: Roboto, "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 14px;
    font-style: normal;
    font-variant: normal;
    font-weight: 400;
    line-height: 20px;
    letter-spacing: normal;
    text-align: start;
    text-decoration: none solid rgba(0, 0, 0, 0);
    text-indent: 0px;
    text-rendering: auto;
    word-break: normal;
    overflow-wrap: break-word;
    word-spacing: 0px;
}
</style>
```

**Comment by DanielnetoDotCom** [comment]
This page is not created by me, it is auto created by wysihtml5 plugin. I do not know where to change it and where it comes from

But I got a solution for you.

Add this script into your head
```
<script>
$('.wysihtml5-sandbox').contents().find('body').focus(function() {
 $(this).css("color", "black");
});
$('.wysihtml5-sandbox').contents().find('body').focusout(function() {
 $(this).css("color", "black");
});
$('.wysihtml5-sandbox').contents().find('body').blur(function() {
 $(this).css("color", "black");
});
</script>
```

FYI this is not a good solution, the best solution is for you to find what is changing the iframe.body color

**Comment by JoshWho** [comment]
That did not work either. I have no clue what is overriding this. I removed anything in the header that even comes close to changing font colors to white and I do not have any custom scripts being used it is all exact files from the repo. Not sure what is going on.
