### ISSUE TITLE
Admin Section Not Loading

### ISSUE THREAD

**Issue by hustler203** [WWBN/AVideo#4241]
fresh install after enabling any plugin admin or main pages don't load

**Comment by bbyrdhouse** [comment]
I wonder if you have or had your site in "Maintenance" mode?

**Comment by DanielnetoDotCom** [comment]
@hustler203 check your log file

**Comment by NAndras95** [comment]
My admin page not working too.
https://URL/admin/

log says:
```
10.131.0.1 - - [06/Jan/2021:09:36:32 +0000] "GET /admin/ HTTP/1.1" 200 13354 "https://URL/ " "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:84.0) Gecko/20100101 Firefox/84.0"
```

But the browser says:
502 Bad Gateway
The server returned an invalid or incomplete response. 

installed plugins:
CustomizeAdvanced (CustomizeAdvanced)
UUID: 55a4fa56-8a30-48d4-a0fb-8aa6b3f69033
Version: @1.0

CustomizeUser (CustomizeUser)
UUID: 55a4fa56-8a30-48d4-a0fb-8aa6b3fuser3
Version: @1.0

LoginGoogle (LoginGoogle)
UUID: 15240814-8c31-4f15-a355-48715fac13f3
Version: @1.0

PlayerSkins (PlayerSkins)
UUID: e9a568e6-ef61-4dcc-aad0-0109e9be8e36
Version: @1.0

ShareSocialButtonsOnEmbed (ShareSocialButtonsOnEmbed)
UUID: c63ae9e3-bf01-4f76-9d7e-b3ad7fd92e3e
Version: @1.0

YouTube (YouTube)
UUID: youu05bf-3570-4b1f-977a-fd0e5cabtube
Version: @1.0

Any idea what could be the problem?
