### ISSUE TITLE
BigVideo selection

### ISSUE THREAD

**Issue by Fnaxx** [WWBN/AVideo#4244]
Hello, 

I would like to know if there is a way to select the id of the BigVideo of the first page to be seen by all users (authenticated or not authenticated).
If not, maybe we could have always the latest uploaded video as the BigVideo of the first page? (currently the BigVideo seems to be choosen randomly depending on users). 

For information I'm using AVideo 9.7 and the First Page Style "Gallery". 

Thank you in advance for your help on this. 

Regards.

**Comment by akhilleusuggo** [comment]
Hello ,

You can "Star" the video to show on the first page . Go to videos ( as admin ) , and start the video .

![image](https://user-images.githubusercontent.com/52116577/103179920-4c2ac680-4899-11eb-8404-bd54eaca6095.png)


Clear the cache before reloading .

**Comment by Fnaxx** [comment]
Thank you for your quick answer! I did not see that suggested could be used as bigvideo.
