### ISSUE TITLE
Changing Directions With My Site, Several Questions Before I Do ... 

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4245]
Currently my site is sort of a c"clone" of Youtube but I'd like to make it more like the Gab TV model. Part of this change would be utilizing BackBlaze for the storage (I already have the plugin and use B2 for several years). I would like to ask the following questions before I make this change:

1. If I move away from HLS and go to Backblaze, I want to make sure that all previously uploaded videos will still be Bothe viewable by the site visitors and editable by the person who uploaded the file.

Next, I will be moving to a "paid" site, meaning that content creators will need to become "pro" users that will enable several features like: 
- ability to upload content
- ability to put some or all of their content behind a paywall or PPV
- ability to promote their channel by allowing their videos to be embedded onto other sites (via the iframe)

So question 2 is: Is it possible for me (site admin) to create a subscription model where
- regular users can view videos (that are not PPV)
- register at the site if they want to watch a PPV video
- content creators will have to become a paid subscriber if they want to upload content to the site
- content creators will have the ability to make each of their videos free or PPV

3. I, the site admin, will still be able to Live stream, but this feature will be turned off for everyone else

Some of these might seem like silly questions, and I apologize in advance if they are, but I need to sort out how I can start making $ off this script and these answers will help me out.

**Comment by DanielnetoDotCom** [comment]
> 1. If I move away from HLS and go to Backblaze, I want to make sure that all previously uploaded videos will still be Bothe viewable by the site visitors and editable by the person who uploaded the file.

if the HLS is stored locally I am pretty sure it will still work

> Next, I will be moving to a "paid" site, meaning that content creators will need to become "pro" users that will enable several features like:
> 
> * ability to upload content
> * ability to put some or all of their content behind a paywall or PPV
> * ability to promote their channel by allowing their videos to be embedded onto other sites (via the iframe)
> 
> So question 2 is: Is it possible for me (site admin) to create a subscription model where

I guess this plugin may help you with that. 
![image](https://user-images.githubusercontent.com/18009293/103227597-7fa73880-490d-11eb-805f-4c4b3ce6cfa1.png)

It will allow your user to pay by file stored size.


> * regular users can view videos (that are not PPV)
> * register at the site if they want to watch a PPV video
> * content creators will have to become a paid subscriber if they want to upload content to the site
> * content creators will have the ability to make each of their videos free or PPV
 
PPV plugin may help you with that as well


> 1. I, the site admin, will still be able to Live stream, but this feature will be turned off for everyone else

Yes no problem


Just be aware you can check all the plugins on the demo site before purchase them
