### ISSUE TITLE
Problem Activating Adaptive mode

### ISSUE THREAD

**Issue by abed-ahmed** [WWBN/AVideo#4246]
I checked the "Adaptive mode" and update the nginx config file as in the link "https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream". Now what is the sign to know that it is working correctly?

**Comment by akhilleusuggo** [comment]
start a live-stream , and see if you get the quality selector .

**Comment by abed-ahmed** [comment]
I have been broadcasting live and the quality selector is not showing up
