### ISSUE TITLE
Small Problem With Sign-up Agreement Modal

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4252]
**Describe the bug**
When creating a signup agreement page/modal there does not seem to be a way to align the text to the left. It is given a "text-align:center;" rule to follow and it does not look good on the page (note the image).

I have added manual CSS to try to override the rule but it is ignoring that (cleared cache on the site and in my browser(s))

There needs to be a way to let an admin set the alignment of the content. 
Also, the modal is ignoring font-size rules and instead uses a default "medium" which is (IMO) just too small.

![modal-agreement](https://user-images.githubusercontent.com/7376298/103215985-85cff180-48da-11eb-9078-7e4a03e44051.jpg)

**Comment by DanielnetoDotCom** [comment]
can you please share a link where I can see this popup?

**Comment by DanielnetoDotCom** [comment]
Try this CSS


```
.swal-modal span div p {
    text-align: center !important;
}
```

**Comment by bbyrdhouse** [comment]
You should see it on https://thepatriot.network when you first try to visit the page after having cleared your browser cache

**Comment by DanielnetoDotCom** [comment]
Did you try the CSS?
