### ISSUE TITLE
Unable to Get Back To Plugins Page After Being In Maintenance Mode

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4253]
**Describe the bug**
I put the site into maintenance mode on yesterday afternoon (Sunday, Dec. 27, 2020). I could still access the plugins page and made some changes to some options from the plugin's parameters. 

**This morning**, I cleared the cache to the site and also on my browser because I was troubleshooting a css issue with the Sign-up Agreement plugin modal.

After I had cleared the cache on the site and also on my browser, I am no longer able to get back to the plugins page ... or rather I can get there but it presents a blank page (Note the attached images)

It isn't just the plugins page it is also the "users" and "categories"

**To Reproduce**
1. Put site in maintenance mode
2. Clear the cache of the site and then on your browser
3. Try to go back to plugins to take the site out of maintenance mode
4. See blank page where the plugins should be listed

**NOTE**: I should also point out that I set the maintenance period to last until midnight last night, **so the maintenance period had expired by the time I tried to access it this morning**.

**UPDATE**: I've also noticed an issue (I presume to be related) in the Admin Menu where the collapsable menu items on the left will not open (image attached below others).

![plug-maint](https://user-images.githubusercontent.com/7376298/103218057-a5b5e400-48df-11eb-8494-e19d5ff348d4.jpg)

![cat-maint](https://user-images.githubusercontent.com/7376298/103218061-a9496b00-48df-11eb-8848-254bdde417c2.jpg)

![user-maint](https://user-images.githubusercontent.com/7376298/103218079-b36b6980-48df-11eb-81ed-eaa3033d6e88.jpg)

**ADMIN MENU**
![amin-maint](https://user-images.githubusercontent.com/7376298/103218572-f7ab3980-48e0-11eb-9806-83d97cdd75c5.jpg)

**Comment by DanielnetoDotCom** [comment]
I could not reproduce it on my side, but I found this on your site.

![image](https://user-images.githubusercontent.com/18009293/103238155-91e2a000-4928-11eb-897e-0d7e34e5d353.png)

I guess you enabled the EnableMinifyJS option. I just sent an update to force disable it.

also, I already update your site and cleared the cache. it should be back now
