### ISSUE TITLE
ftp

### ISSUE THREAD

**Issue by lahaj** [WWBN/AVideo#4262]
Hi
I am having trouble uploading files to FTP
Example
All I create a new file in FTP to put it on the server via FTP
Fails.
  As shown in the pictures
Whenever I upload a file via FTP
Example
When I upload the MP4 file or image, I see that it was successfully uploaded, but the file is not present on the server

![88](https://user-images.githubusercontent.com/71000399/103245324-3ab8eb80-4979-11eb-9d65-223947df4162.jpg)
![99](https://user-images.githubusercontent.com/71000399/103245326-3bea1880-4979-11eb-9889-0c41e79df385.jpg)

Secondly, how to delete this word  ((AVideo)) from the video, since I am subscribed to you on 2 servers.
The other server is very good, except for this one

![77](https://user-images.githubusercontent.com/71000399/103245345-4e645200-4979-11eb-8d92-2fd4a4ab085e.jpg)

Please help me solve these two problems

**Comment by lahaj** [comment]
![777](https://user-images.githubusercontent.com/71000399/103245433-96837480-4979-11eb-895c-e8390ea3e546.jpg)

**Comment by akhilleusuggo** [comment]
this has nothing really to do with the project .
You're having a permission issue . Fix that first .
Make sure the video you're uploading is compatible with HTML5
Instead of FTP , make a direct upload .

**Comment by lahaj** [comment]
I took this server several days ago, and today I just worked on it and saw this problem even though the video file is compatible and it has no problem
The proof is: I have another server that works well and a good FTP that works well

**Comment by lahaj** [comment]
![777](https://user-images.githubusercontent.com/71000399/103246141-e400e100-497b-11eb-8ab5-c6074064497e.jpg)

The second thing, sir, how to delete this word from the video

**Comment by akhilleusuggo** [comment]
idk how you setup the videos , but you should be able to delete from Video Manager

**Comment by lahaj** [comment]
Where can I find the video manager please? Because the first time I encounter these notes, even though your servers and programming are very excellent, because the other server I did not find these notes on, please help me

**Comment by akhilleusuggo** [comment]
I didn't wrote this , @DanielnetoDotCom did , I'm just here to help

![image](https://user-images.githubusercontent.com/52116577/103247403-73ec5e00-496f-11eb-8b4d-4f6539c62b58.png)

![image](https://user-images.githubusercontent.com/52116577/103247427-89618800-496f-11eb-9fd5-7d9b33f2680e.png)

**Comment by lahaj** [comment]
Thank you very much and for helping me, sir. I did everything to delete this word, but it did not delete it
See photos please

![1010](https://user-images.githubusercontent.com/71000399/103247744-663fd400-4981-11eb-9512-2155b2298d72.jpg)
![1111](https://user-images.githubusercontent.com/71000399/103247751-69d35b00-4981-11eb-9012-70c43e78cb48.png)

**Comment by DanielnetoDotCom** [comment]
Try to check this 

![image](https://user-images.githubusercontent.com/18009293/103283668-f6990b80-49b7-11eb-8c11-40bafcfc54de.png)

**Comment by DanielnetoDotCom** [comment]
For the records, I could make the SFTP work with this...

Add the Ubuntu SSH user into apache group

`sudo usermod -aG www-data ubuntu`


Make sure everything inside the /var/www/html/ directory belongs to apache

`sudo chown -R www-data:www-data /var/www/html/`

Give write permission to the group

`sudo chmod -R 775 /var/www/html/`
