### ISSUE TITLE
Meet is missing a file

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4266]
Created a test meet and when loading the page https://www.joshwhotv.com/meet/4/z-test420?

shows me it is calling for a file https://www.joshwhotv.com/plugin/Meet/external_api.min.map

Which does not exist. Is there something i need to generate?

**Comment by DanielnetoDotCom** [comment]
I do not think it is a problem

Is your meet working?

**Comment by JoshWho** [comment]
No it shows a error page when going to https://www.joshwhotv.com/meet/4/z-test420

**Comment by DanielnetoDotCom** [comment]
I see

I think I found the bug on the meet side (ports conflicts), it should be fixed now

**Comment by JoshWho** [comment]
Yes works good now. Thank you @DanielnetoDotCom
