### ISSUE TITLE
Video not streaming while any changes happen in server.

### ISSUE THREAD

**Issue by elias2k1** [WWBN/AVideo#4267]
While I change any kind of configuration change or upload new videos, videos failed to load from public network and mobile devices. It only resolves after clearing the cache. Is it a bug or its by design?

**Comment by DanielnetoDotCom** [comment]
if you just refresh the page without a clear cache does it resolve?

does this only happen on mobile or also on the desktop?

are you running the latest git pull?

**Comment by elias2k1** [comment]
# if you just refresh the page without a clear cache does it resolve?
- Refresh doesn't resolve
# does this only happen on mobile or also on the desktop?
- It happen from both mobile and desktop. Now I am facing another issue: When I clear the cache it work from local network but not from internet. If I clear it twice and browse from internet first then it work from internet but not from local network and vise versa.
# are you running the latest git pull?
- I am using the latest git pull

**Comment by akhilleusuggo** [comment]
are you using cloudflare ?

**Comment by elias2k1** [comment]
No. Site is hosted in our on premise server.

**Comment by DanielnetoDotCom** [comment]
how is your cache plugin parameters? can you screenshot the parameters screen?

**Comment by elias2k1** [comment]
![Cache](https://user-images.githubusercontent.com/75417257/103394918-a2c42900-4b55-11eb-97bc-453a9812ff13.JPG)

**Comment by DanielnetoDotCom** [comment]
I cannot see anything wrong.

can you reproduce it on demo site?
