### ISSUE TITLE
Video discription editor goes to blank page

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4268]
Hi hi. When i go to an uploaded video and try to add description it takes me to a blank page. So cannot update or create descriptions on videos.
![20201229_150620](https://user-images.githubusercontent.com/76112286/103285386-b00ed580-49e6-11eb-92ed-4273672dd15d.jpg)
![20201229_150635](https://user-images.githubusercontent.com/76112286/103285393-b56c2000-49e6-11eb-99ca-8db56b6be8fe.jpg)

Am I missing something?

Regards

**Comment by DanielnetoDotCom** [comment]
I have never seen this before

can you try in another browser?

does this happen on demo site?

**Comment by unconservo** [comment]
Hi. Thanx for reply. It seems dsme on demo site. Tested on my android phone in chrome. Weird

**Comment by unconservo** [comment]
I tested it on firefox and same thing.. nothing shows

**Comment by unconservo** [comment]
I disabled the html description check mark under customizeadvanced plugin and now atleast i can add descriptions 👍

**Comment by unconservo** [comment]
Hi. I found that when i set browser to desktop view i can edit descriptions using htmldescription. Can you please look at this issue on mobile. I do not think the html description is compatible with native android modes.

Regards

**Comment by DanielnetoDotCom** [comment]
what mobile browser are you using?

**Comment by unconservo** [comment]
Hi. I tried chome and firefox. Same thing in both

**Comment by DanielnetoDotCom** [comment]
Try this update

**Comment by unconservo** [comment]
Which update?

**Comment by unconservo** [comment]
Hi hi. I reloaded AVideo and the new update is working. Thank you :)

Regards
