### ISSUE TITLE
PHP Warning...Unlink.. video lock.

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4272]
Hi. I'm getting loads of errors like this in log file. Is it an permission problem?

Regards

PHP Warning:  unlink(path/to/my/streamer/site/videos/cache/getImageFromFilenameAsync/__YPTuniqid_5fe9d1e3aa4b50.33403287_video.lock): No such file or directory in path/to/my/streamer/site/objects/getImageFromFilenameAsync.php on line 18

**Comment by akhilleusuggo** [comment]
Duplicate of https://github.com/WWBN/AVideo/issues/4211

Quick answer , is not an issue .
Also disable AsyncJobs , is not working properly .

**Comment by unconservo** [comment]
Ok. Thanx
