### ISSUE TITLE
git pull error Avideo

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#4274]
I ran "git pull" under AVideo Directory.
Next error Ocuured.

#sudo git pull
remote: Enumerating objects: 181, done.
remote: Counting objects: 100% (181/181), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 256 (delta 160), reused 163 (delta 143), pack-reused 75
Receiving objects: 100% (256/256), 799.54 KiB | 1.02 MiB/s, done.
Resolving deltas: 100% (168/168), completed with 41 local objects.
From https://github.com/WWBN/AVideo
   164c31dd6..8150f2478  master     -> origin/master
Updating 164c31dd6..8150f2478
error: Your local changes to the following files would be overwritten by merge:
        sitemap.xml
Please commit your changes or stash them before you merge.
Aborting
#

I tried "git add"command.
#git add *
The following paths are ignored by one of your .gitignore files:
videos
Use -f if you really want to add them.
I tried "git 

Please tell me how to slove this problem

**Comment by DanielnetoDotCom** [comment]
Run this

`sudo git fetch --all && sudo git reset --hard origin/master`

**Comment by sizious** [comment]
This is related to https://github.com/WWBN/AVideo/issues/4261. The important information is:
```
error: Your local changes to the following files would be overwritten by merge:
sitemap.xml
```
It means your `sitemap.xml` doesn't match the one in the Git repository which is normal as this file should be generated by your own AVideo Platform instance. So the best thing you have to do is:
```
rm sitemap.xml
git pull
```
Then after you need to regenerate your `sitemap.xml` file.

**Comment by DanielnetoDotCom** [comment]
usually, we need to give permission to this file to be able to write on it.

that is why I keep it.

the sitemap.xml does not suppose to update, this update was a mistake

**Comment by sizious** [comment]
This is now solved, this issue can be closed.
