### ISSUE TITLE
Chat2 Image Attachment Error

### ISSUE THREAD

**Issue by djirving82** [WWBN/AVideo#4277]
When in live video chat (Chat2 Plugin) certain images will not post and give an error. It was NOT the file format. Are there resolution or file size limits? It appears that any image over 2mb will cause an error. Can this be changed? Is there any way to decrypt the files so they can be edited or at least viewed?

**Comment by DanielnetoDotCom** [comment]
how is your PHP max upload size?

I do not have any limitations on the code. it may be your server limitation.

**Comment by djirving82** [comment]
8gb for my php max upload size. I resized the same image a bunch of times. Any that were over 2mb caused an error. Any other ideas?

**Comment by DanielnetoDotCom** [comment]
Not sure, check errors in your streamer log, also inspect your JS panel for some errors

can you try it on demo site?

**Comment by djirving82** [comment]
Ok, finally figured it out. I updated to PHP-fpm and that changes the default php.ini file. Also, after changing the proper php.ini file I had to restart PHP-fpm specifically, not just Apache. All is working fine again.

**Comment by ejb1123** [comment]
@djirving82 checkout [this issue](https://github.com/WWBN/AVideo/issues/4637) there is a solution to derypt the plugins there.
