### ISSUE TITLE
Schedule livestream

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4278]
Hi. Is there a way to schedule a livestream at a certain time? I could not find anything except with Meet. Maybe im looking at wrong place?

I want to setup a livestteam and then promote it to users beforehand like in youtube.

Regards

**Comment by DanielnetoDotCom** [comment]
We still working to improve it.

with the PPV live plugin, you can schedule, but there are no notifications yet.

also with the playlist to live feature (under development), you also can schedule a live.

**Comment by unconservo** [comment]
Thank you :). I will then buy ppv plugin also.

**Comment by DanielnetoDotCom** [comment]
Just to let you know you can check this plugin before buy on the demo site. :)

**Comment by unconservo** [comment]
Hi. Thank you. On the demo site i created a free plan and then clicked on
live stream... set the ppv and save stream but where does it show the up
coming stream at scheduled time?. I checked front page but nothing.

Regards

**Comment by DanielnetoDotCom** [comment]
there is no automatic Livestream, you have to connect it by yourself.

the schedule idea is that your payers will only be able to join the live stream at the scheduled time.

**Comment by unconservo** [comment]
Ok. So no way even with the plug in to promote livestream beforehand?

**Comment by DanielnetoDotCom** [comment]
What do you expect to promote?

why don't you create an ad? [AD_Server plugin](https://github.com/WWBN/AVideo/wiki/Ad-Server-Plugin)

**Comment by unconservo** [comment]
If im a content creator with my channel and i have a live stream 4 hours
from now i want the live stream showing as live in 4 hours and counting
down so that users can see that a live stream will start at a certain time
and bookmark it or add in their program.

Hope you understand what i mean :)

**Comment by DanielnetoDotCom** [comment]
You can start to stream now and put a countdown video on it

**Comment by unconservo** [comment]
Playlist is different than program?. Or same thing?.

**Comment by DanielnetoDotCom** [comment]
same thing
