### ISSUE TITLE
Tried to setup restreming and now Live don't work

### ISSUE THREAD

**Issue by br0kenlink** [WWBN/AVideo#4280]
Hi, running Debian Buster.
I tried to restream to Mixcloud.
Used this link to set things up: https://github.com/WWBN/AVideo/wiki/Restream
Now even though OBS is connecting, nothing shows in AVideo.
It was working just fine before.
Getting this error now:
[error] 464#0: *3 open() "/HLS/live/5fee3d7643a71/index.m3u8" failed (2: No such file or directory)
Any help would be appreciated

**Comment by akhilleusuggo** [comment]
We need more details/logs to debug .

**Comment by br0kenlink** [comment]
Which logs exactly should I provide? nginx and ?

**Comment by br0kenlink** [comment]
Here's nginx error.log, I have to say, I created new file yesterday, cos old one was opening too long. It's massive since yesterday evening. I removed a lot from it to pastebin.
https://pastebin.com/A2VsxMj5
Will look to pastebin other logs but I start to think, fresh install might be a good idea

**Comment by br0kenlink** [comment]
ok, avideo.log has 55MB as is full of mysql errors, like A LOT.
seems things started with latest update.
https://pastebin.com/Hggm7T43
This is when nothing is trying to connect.
Should I just reinstall on Ubuntu?

**Comment by DanielnetoDotCom** [comment]
@br0kenlink check this https://github.com/WWBN/AVideo/wiki/Restream#restream-to-rtmps

**Comment by br0kenlink** [comment]
yeah, I did follow this and nothing, also no log. Could be directory permissions?
my live stream shows on AVideo page but nothing on facebook

**Comment by DanielnetoDotCom** [comment]
not sure check your logs and try to restream manually to see what happen
