### ISSUE TITLE
Description popup does not show picture attached to article

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4282]
Hi. When clicking on article description the picture does not show but it shows in big video description nect to article. It also shows whrn clicking on article and slso editing the article.

Regards
![20210101_110634](https://user-images.githubusercontent.com/76112286/103436089-a96ba280-4c20-11eb-9aa4-232d501b38a6.jpg)

**Comment by DanielnetoDotCom** [comment]
how did you add the image?

inspect the code and check the `<a href` from the image

**Comment by unconservo** [comment]
Hi. I uploaded it through htmldescription in desktop mode on android -
chrome

**Comment by DanielnetoDotCom** [comment]
I do not think we have any image upload method for it. 

please screenshot where did you upload and how did you do it.

**Comment by unconservo** [comment]
On this circled :)
