### ISSUE TITLE
Only hd encoding

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4285]
Hi. How do i set the encoder to only encode hd or sd?. Atm its encoding all sizes which makes encoder slow.

Regards

**Comment by DanielnetoDotCom** [comment]
Check your customizeAdvanced plugin like this 

![image](https://user-images.githubusercontent.com/18009293/103441545-97443100-4c2d-11eb-9e75-e722d6cfe299.png)

**Comment by unconservo** [comment]
Hi. I changed it like your pic but now all my videos under my videos
dissapeared even if it says i have 16 uploaded.

**Comment by unconservo** [comment]
I then get the following ...

**Comment by unconservo** [comment]
The last error is for youtube so thats ok but all my videos under "My Videos" dissapeared

**Comment by unconservo** [comment]
All admin "my videos" dissspeared. All normsl users can access their videos

**Comment by DanielnetoDotCom** [comment]
It does not make sense to disappear all your videos.
check the log files

**Comment by unconservo** [comment]
Lots of these errors in log file

[01-Jan-2021 20:40:09 Africa/Johannesburg] PHP Fatal error: require_once():
Failed opening required
'path/to/my/streamer/site/objects/james-heinrich/getid3/getid3.php'
(include_path='.:/usr/share/php') in
path/to/my/streamer/site/objects/video.php on line 1988

**Comment by DanielnetoDotCom** [comment]
Hi, I guess I fixed it this weekend

**Comment by unconservo** [comment]
I reloaded the whole server

**Comment by unconservo** [comment]
Awesome 👏👏👏. Welldone. It is working now.

Regards
