### ISSUE TITLE
Manually changed subscription plan's ending date doesn't deactivate the subscription  

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#4286]
Hi

If  you need or want to change (e,g, extend) subscription plan's ending time. The plan doesn't deactivate automatically anymore. 

So here's an example case: 

1. I have created a subscription plan valid for 30 days. 
2. I add the plan for a user manually via Edit Subscriptions. 
3. I don't want it to end after 30 days but I want to extend it to be valid for 40 days. 
4. I change the ending time 10 days ahead.
5. after 41 days the subscription is still active, not deactivated as it should be (It will never deactivate automatically). 
6. I have to deactivate it manually.

If I don't change the ending time manually but use the plan's native ending time, it works correct.

![image](https://user-images.githubusercontent.com/63721378/103438761-40dfee00-4c3f-11eb-8e63-33125af40206.png)

best regards and Happy New Year!

**Comment by DanielnetoDotCom** [comment]
I am not sure how this is possible. you must check the server date to make sure the expiration is expected

**Comment by tonuzo** [comment]
Server date is ok. Today I noticed the problem again.

**Comment by DanielnetoDotCom** [comment]
You must show me a sample that supposes to expire and did not.

I need to check it directly into your server as long as I could not reproduce it here
