### ISSUE TITLE
a question about updating the site

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#4287]
hello @DanielnetoDotCom  every time i do a sudo git pull   I still have the same files,

![image](https://user-images.githubusercontent.com/39193219/103442846-d8ead100-4c59-11eb-89d7-edcdbd383ca7.png)

**Comment by DanielnetoDotCom** [comment]
try this instead of a `git pull`

`sudo git fetch --all && sudo git reset --hard origin/master`
