### ISSUE TITLE
Videos not moving to storage (HLS)

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4289]
**Describe the bug**
When encoding videos ( hls ) , after sending the video to streamer site , unzip to /videos folder 
Before some updates , automatically moved to Avideo-storage .
This works fine on mp4 videos. It happens only on hls.

Another problem is when moving the video to storage , force clear cache of the video. Because if not , the previuous url video is the one traying the playback ( but has been moved ) .

**To Reproduce**

Encode hls video , and see if does transfer automatically to storage .

**Comment by akhilleusuggo** [comment]
Ok , I found that only when doing ''retry download" doesn't send to storage automatically .

**Comment by DanielnetoDotCom** [comment]
Hi

I just tested MP4 and HLS on my side and they automatically move.

can you please check the logs?

**Comment by akhilleusuggo** [comment]
Like I've stated , only when the first download fails , the re-try is the one not moving it .

**Comment by DanielnetoDotCom** [comment]
Sorry, what you mean retry?

I also tested click on the move button it also works on my side.

can you detect something on the log?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Sometimes the transfer fails , so makes a retry transfer . Right ?

If the transfer does get success at the first try , then videos will automatically go to storage server
If not ; second retry will get stuck at the global streamer site ( local ). 

That's what I've got from debugging on logs

**Comment by DanielnetoDotCom** [comment]
Hi, do you mean the second retry starts but do not complete? and there is no log?

**Comment by akhilleusuggo** [comment]
Yes , the second retry start , and completes ( to the local only ) , and stops ( the video is working , but do not automatically moves to storage )

**Comment by DanielnetoDotCom** [comment]
Any idea why the first attempt stops?

**Comment by akhilleusuggo** [comment]
The first attempt for some reason is storing on the RAM 
The second attempt does store on the disk 

My main site , does have only 16gb ram ( no need more ) . If streams are long , and I'm using already 8-9gb ram , then it fails .
Only HLS has this issue .

BTW , thank you for changing the compression ( zipping ) method .

**Comment by DanielnetoDotCom** [comment]
I guess the problem may be the compressing. maybe is exhausting your ram
