### ISSUE TITLE
VR360 is on by default and I want to make it "off" by default

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4291]
Any way we can make the VR360 switch default to off?
![8456670a-a6c7-4dc4-9465-ce16a76de2db](https://user-images.githubusercontent.com/39392449/103452673-7dd7cf00-4c97-11eb-80b9-4910911faf2d.png)

**Comment by DanielnetoDotCom** [comment]
I guess by default it is off

**Comment by JoshWho** [comment]
No I had it enabled and guest users was seeing the setting on so I disabled the plugin for now.

**Comment by JoshWho** [comment]
Any way this can get changed so I can re enable it? I have users wanting to try the 360 view.
