### ISSUE TITLE
Ads for the Video play page are not centered anymore

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4292]
The ad slot for the top right corner ad place is not centered anymore. 

![a4c4ca1c-16f2-4373-a654-82228ed318c6](https://user-images.githubusercontent.com/39392449/103455716-db2e4900-4cb4-11eb-98a5-d9be3f07757b.png)

**Comment by DanielnetoDotCom** [comment]
try this update

**Comment by JoshWho** [comment]
Yes Did the trick, thank you @DanielnetoDotCom
