### ISSUE TITLE
Footer on VIdeo CHart is to tall

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4294]
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/39392449/103461934-7b9d6100-4ce7-11eb-9eed-594c3a3da9d5.gif)

**Comment by DanielnetoDotCom** [comment]
as long as you are using a custom footer you may want also to use a custom CSS to add some padding or margin on the bottom

**Comment by JoshWho** [comment]
This never was an issue until u made the footer float. This is the paid plugin footer not the custom advance one.

**Comment by DanielnetoDotCom** [comment]
I went to check it on your site and looks like you fixed it. 
would you like to share your solution, it looks good

**Comment by JoshWho** [comment]
I changed the theme. It was on the default theme

**Comment by DanielnetoDotCom** [comment]
To what theme?
