### ISSUE TITLE
Meet Live Recording Time Limit

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4295]
I noticed it is set to only allow recording and live streaming for 1 hour, is there any way to increase that?

**Comment by akhilleusuggo** [comment]
Only if self-hosted 
( or you're premium account )

**Comment by JoshWho** [comment]
I think I am self hosted. Not really sure. I didn't set it up so I do not know. If not I can be.

**Comment by mrgodgiven** [comment]
> Only if self-hosted
> ( or you have premium account )

I'm self hosted but have the same issue please let me know how to increase the limit to more than one hour.

**Comment by akhilleusuggo** [comment]
I don't think you're self hosted .
If you're using the script as it is , Daniel is hosting you . ( That's my understanding ) . 

You can check older issues related to this .

**Comment by mrgodgiven** [comment]
Please link m to the old issues if you remember.
