### ISSUE TITLE
444/stat working on https but getting this error

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4299]
Hi. Im getting this error but if i go to browser i can access it

myMySQLDatabaseLog::ERROR: Live::getStatsObject RTMP Server (https://www.mysite.com:444/stat) is OFFLINE, we could not connect on it => live_servers_id = (0)  SCRIPT_NAME: /plugin/Live/stats.json.php

**Comment by unconservo** [comment]
And still this php warning...

PHP Warning:  file_put_contents(path/to/my/streamer/site/videos/cache/YPTWget/e5ef2bd1ce5f7801a1fae5e0d45cafb7.lock): failed to open stream: No such file or directory in path/to/my/streamer/site/objects/functions.php on line 4105

**Comment by akhilleusuggo** [comment]
maybe because you're offline ?
what the stat page showing when you streaming

**Comment by unconservo** [comment]
Thanx for reply. Nginx started without any errors. Stat shows accepted 3 but no data streaming. I used nginx step by step install located here. Worked before but had to reload because all my videos dissapeared from view. Now im struggling

**Comment by DanielnetoDotCom** [comment]
@unconservo I am pretty sure you are redirecting 

and your error is like those 

https://github.com/WWBN/AVideo/issues/3964
https://github.com/WWBN/AVideo/issues/3052
https://github.com/WWBN/AVideo/issues/1914

**Comment by unconservo** [comment]
Hi hi Thank you. Will try the suggested solutions :). Will let you know

Regards

**Comment by unconservo** [comment]
Thank you. It is working now. As i run all on one server i made live and
stat page go to https://localhost:444/live and /stat

I am happy now :)
