### ISSUE TITLE
Issues with "Categories"

### ISSUE THREAD

**Issue by sparisot38** [WWBN/AVideo#4300]
Hello,
I post 2 issues that I have reproduced on the demo platform as well with categories. (see Full access demo site - category called "test")

1. I click on Categories and create a new category called "test"
2. I fill in the form 

Issue #1 :  I cannot save the category unless I click on the image folder and click save.
Issue #2 : When I want to link this category as a subcategory of a parent one, and save, I cannot see the new category appears in the menu Category in the left column.

Do I miss something in the process to create a category ?
Many thanks

**Comment by DanielnetoDotCom** [comment]
I could not reproduce it on the demo site.


![chrome-capture (1)](https://user-images.githubusercontent.com/18009293/103540902-40cb3280-4e79-11eb-8a36-f15c1ff3dbb1.gif)

**Comment by sparisot38** [comment]
Thanks @DanielnetoDotCom 
In fact, I have the issue only on Safari (Mac version). Not on Chrome.
