### ISSUE TITLE
"No Video to Show" on first page

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4301]
I am getting this problem. Everything is setup correctly. Why do i have no videos yet I am streaming?

@DanielnetoDotCom  , @akhilleusuggo , may you assist please?

Thank you

![novid](https://user-images.githubusercontent.com/65451390/103476586-44eb4780-4dc8-11eb-9afd-dec2f61480e1.PNG)

**Comment by akhilleusuggo** [comment]
You need at the least to have 4 videos uploaded before anything starts to show up .
Upload 4 random videos , clear the cache .

**Comment by jengajenga** [comment]
> You need at the least to have 4 videos uploaded before anything starts to show up .
> Upload 4 random videos , clear the cache .

Ok I will try that.

What about the Live Videos? Will they show up?

**Comment by akhilleusuggo** [comment]
Upload 4 videos in first place , then if the issue persists you can post the issue .

**Comment by jengajenga** [comment]
@DanielnetoDotCom , @akhilleusuggo , i still don't have live videos on the first page. What are the requirements exactly? I have them on one server but not on my dev server.

All settings on the dev server are similar to the original one so I am confused.

Please help.

**Comment by akhilleusuggo** [comment]
@jengajenga Did you upload 4 videos ? Do they appear on the first page ?

Make sure that you haven't selected any of this options ;

![image](https://user-images.githubusercontent.com/52116577/104120852-ae2c0700-5342-11eb-8a5f-baffb7eceec1.png)

And one last thing , when you're live . Do you see '' ONLINE " status ?
Could you share the status page ?

**Comment by jengajenga** [comment]
> @jengajenga Did you upload 4 videos ? Do they appear on the first page ?
> 
> Make sure that you haven't selected any of this options ;
> 
> ![image](https://user-images.githubusercontent.com/52116577/104120852-ae2c0700-5342-11eb-8a5f-baffb7eceec1.png)
> 
> And one last thing , when you're live . Do you see '' ONLINE " status ?
> Could you share the status page ?

To be honest, I didn't upload the videos because it didn't make sense. But since you mentioned it again, I figured I would try. And it has worked :-) 

I'm grateful and sorry for doubting you at the beginning. Thank you again.
