### ISSUE TITLE
Paypal YPT subscriptions don't renew date

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#4302]
Hey,

I have noticed that paypal subscriptions don't update the renewed subscription dates. I have to continue the subscriptions manually. This has been happening now at least couple of months.

Client ID and secret key are correct on Paypal YPT plugin.

I'm wondering should there be also Webhook available?

**Comment by DanielnetoDotCom** [comment]
yes, the webhook is required to be able to renew the subscription. but we use the PayPal IPN 

You may be able to check the IPN history here https://www.paypal.com/us/cgi-bin/webscr?cmd=_display-ipns-history

Also, check your streamer log file. it should have all IPN records there.

your IPN should be this address {$global['webSiteRootURL']}plugin/PayPalYPT/ipn.php

**Comment by tonuzo** [comment]
Ok, thanks. My IPN was not active. I activated it, hope it solves the problem.
