### ISSUE TITLE
Error deleting user: Table 'aVideo.users' doesn't exist

### ISSUE THREAD

**Issue by Maagiiix** [WWBN/AVideo#4303]
Hi there
I am straggling with this error "Error deleting user: Table 'aVideo.users' doesn't exist"
when trying to installon NAS Syno
Many thanks for any help

**Comment by akhilleusuggo** [comment]
delete the entire database , then retry
Another solution is giving a different name to database during the installation

**Comment by Maagiiix** [comment]
> delete the entire database , then retry
> Another solution is giving a different name to database during the installation

Thanks for your return. I tried those solutions but not fixed yet. I deleted the entire data relating to AVideo but not the entire mariadb database

Still wanting any input. Many thanks

**Comment by akhilleusuggo** [comment]
Honestly never tested on MariaDB 
In any case , check the log file of MySQL/MariaDB 

NAS Syno is not what you need for this project . You should use it for storage , but you not sure how it's gonna do as main server.

**Comment by Maagiiix** [comment]
> Honestly never tested on MariaDB
> In any case , check the log file of MySQL/MariaDB
> 
> NAS Syno is not what you need for this project . You should use it for storage , but you not sure how it's gonna do as main server.

Many thanks. The former version youphptube worked. but I will check

**Comment by zenalien** [comment]
Hi there, 

we are facing exactly the same problem, apparently mysql/phpmyadmin won't create tables named "users" because it looks to be reserved..

Any advice on this ?

**Comment by maghuro** [comment]
> Hi there,
> 
> we are facing exactly the same problem, apparently mysql/phpmyadmin won't create tables named "users" because it looks to be reserved..
> 
> Any advice on this ?

Same problem here.

**Comment by DanielnetoDotCom** [comment]
I cannot imagine a database server that will reserve the word users so we cannot create tables with this name.

users are the most common name for a table.

in my opinion, this is impossible. your error MUST be something else
