### ISSUE TITLE
Mobile and live - webcam

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4305]
Hi hi. Just want to ask if the folliwing are bugs or still in development :).

When I use my cellphone (android-s9note) to broadcast live and click on Webcam/Meet to use mobile cam i get the folliwing if im not in landscape. It brings up a block under go live and cut cam off or overlaps it. If i change to landscape it is fine.
![20210104_204508](https://user-images.githubusercontent.com/76112286/103568184-ced10880-4ecd-11eb-8b93-a993b1e5655d.jpg)

Also i have chat 2 installed. If i set it as stating it goes under stream info. So its hard to see when someone is typing as you have to scroll down.

If i set it to hover it shows the balloon
![20210104_203821](https://user-images.githubusercontent.com/76112286/103568239-e3150580-4ecd-11eb-9250-6b1e93fa18ff.jpg)

If i go full screen the chat balloon dissapears and chat not available.

Also what is this chat on the left for? It is not working properly. Is there a way to disable it?
![20210104_204905](https://user-images.githubusercontent.com/76112286/103568303-fe801080-4ecd-11eb-99fe-c4f542832b3a.jpg)

Regards

**Comment by DanielnetoDotCom** [comment]
Mobile layout resolved

> chat 2 

We may improve it in future releases

> chat on the left

It does work, but this is the meet chat. only for people in the meet

**Comment by unconservo** [comment]
Awesome :). Thank you for your quick reply. Do i need to update anything?

Regards

**Comment by DanielnetoDotCom** [comment]
yes, you need to update the streamer

**Comment by unconservo** [comment]
Done. Thank you. I will test :)

Regards
