### ISSUE TITLE
Donation link not saving

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4306]
Hi hi. My donation link is user account is not saving. I enabled donations in customiseuser. I add it in and click save but when i go bavk its not there.

Any recomendations?. Did i miss anything?

Regards

**Comment by unconservo** [comment]
Also user pic not saving but shows whhen uploaded. The channel pic save

**Comment by DanielnetoDotCom** [comment]
you must check your log files

**Comment by unconservo** [comment]
Thank you. On ubuntu what is the path to the log files please :)

Regards

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by akhilleusuggo** [comment]
@unconservo I was running into the same issue .
I solved mine , and I had 2 issues .
1- permissions issues . Fixed , but still had problem .
2- It was a cache issue .

I'm still not fully able to fix it , but uploading , and clearing the cache after saving , does prove that I'm having a cache issues .

**Comment by unconservo** [comment]
Ok. 

The log file does not record anything about the user pic when saved. 

Weird as it saves one part but ignore another

Regards

**Comment by akhilleusuggo** [comment]
Yes , same issue here

**Comment by DanielnetoDotCom** [comment]
I do not know what to tell you, I just tested on demo site, and works fine

![image](https://user-images.githubusercontent.com/18009293/103700296-09e14380-4f83-11eb-9fcc-04f0a0906936.png)

The only thing i notice is the Channel Art that is cached and did not update when I refreshed the first time.

**Comment by DanielnetoDotCom** [comment]
This update should resolve the Gallery Art issue

**Comment by unconservo** [comment]
Thank you Daniel. After update pic saved and donation link saved :)

Regards
