### ISSUE TITLE
Can I Use Existing Website I purchased Elsewhere

### ISSUE THREAD

**Issue by jamesrhenry** [WWBN/AVideo#4308]
Can I use an existing website I already purchased and edit the DNS for the new server? Thanks!

**Comment by akhilleusuggo** [comment]
Could you explain better what do you mean ?
If you have a domain name , you're ready to go . Even if you don't have one , you can still install the server and enter via IP

**Comment by jamesrhenry** [comment]
You answered my question, thanks. I wasn't sure if I was supposed to also get a domain from you guys, because I have one already. I've installed youPHPTube on a few sites already, but I'd like to cancel one and use your service and a dedicated server. I'm on a Shared hosting now, but I can't use Live or Encoder. Thanks!

**Comment by jamesrhenry** [comment]
I went ahead & purchased. I'll be purchasing the plugins individually though, I know it's more, but it's easier. Thanks!

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo and @jamesrhenry thanks for the notifications.

I guess @jamesrhenry already contact me, if you do not, feel free to send me an email at developer@youphptube.com

**Comment by jamesrhenry** [comment]
Yes, that's me with the domain loyaltymod.com. I have a number of email addresses...hahaha
