### ISSUE TITLE
Live streaming sort of working

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4309]
Hi. I tested the site after the new reload streaming from obs. Nginx is getting streaming data. The live icone on the front page apears with a gif from the video streaming but not streaming anything to site if i click on it. Stat show data streaming.
![20210105_163922](https://user-images.githubusercontent.com/76112286/103658412-da770a80-4f73-11eb-9e1f-714dd629e678.jpg)

Could it be the default player not correctly selected?

**Comment by unconservo** [comment]
Ok. I have changed the player to the domain name and left stats on localhost. All working now :)

**Comment by unconservo** [comment]
I see delay is like 34 seconds between obs and site. Is this normal?

**Comment by DanielnetoDotCom** [comment]
Yes it is normal

**Comment by unconservo** [comment]
Ok :). Thanx
