### ISSUE TITLE
VAST not working

### ISSUE THREAD

**Issue by Zoe8338** [WWBN/AVideo#4310]
**Describe the bug**
I try to turn VAST video ads

**To Reproduce**
1. Go to Admin PAnel
2. Click on Advertising and VAST video ads
3. Fill fields of ad creation
4. Save

**Expected behavior**
SAve the ad and I am not sure what else.

**Error Logs**
I don't know if it's an error, it just keeps processing

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Brave
 - Version Latest (Jan 5 2021)

**Comment by DanielnetoDotCom** [comment]
if keeps processing check your log files.

also please provide some screenshots to make clear where is the error
