### ISSUE TITLE
getAllWebp and sitemap issues after update

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4311]
Error after update ; /install `php getAllWebp.php`
logs : `AVideoLog::DEBUG: {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"} SCRIPT_NAME: getAllWebp.php`

Same with sitemap.xml

![image](https://user-images.githubusercontent.com/52116577/103743703-46558380-5005-11eb-911e-efd54a2e7500.png)

Update ; Fixed after deleting all webp files from the server . ( now recreating all again )

Sitemap , not fixed for now .

**Comment by DanielnetoDotCom** [comment]
I could not reproduce any of those errors, maybe it is already fixed.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I'm getting too many errors anyway in last updates .

`AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed again return false SCRIPT_NAME: /view/index.php`

`AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":135,"function":"log_error","args":["[sqlDAL::readSql] trying close and reconnect"]},{"file":"\/var\/www\/html\/AVideo\/objects\/category.php","line":606,"function":"readSql","class":"sqlDAL","type":"::","args":["SELECT count(id) as total FROM livelinks v WHERE 1=1 AND categories_id = ?  AND `type` = 'public' ","i",[8]]},{"file":"\/var\/www\/html\/AVideo\/objects\/category.php","line":563,"function":"getTotalLiveLinksFromCategory","class":"Category","type":"::","args":[8,false,false]},{"file":"\/var\/www\/html\/AVideo\/objects\/category.php","line":541,"function":"getTotalFromCategory","class":"Category","type":"::","args":[8]},{"file":"\/var\/www\/html\/AVideo\/view\/include\/navbar.php","line":1166,"function":"getChildCategories","class":"Category","type":"::","args":[3]},{"file":"\/var\/www\/html\/AVideo\/view\/include\/navbar.php","line":1223,"function":"mkSub","args":[3]},{"file":"\/var\/www\/html\/AVideo\/view\/modeYoutube.php","line":384,"args":["\/var\/www\/html\/AVideo\/view\/include\/navbar.php"],"function":"include"},{"file":"\/var\/www\/html\/AVideo\/view\/index.php","line":28,"args":["\/var\/www\/html\/AVideo\/view\/modeYoutube.php"],"function":"require"}] SCRIPT_NAME: /view/index.php`

And many others . The only thing I can say is , you updated some database , but you forgot to include it on the plugin section , to be able to click update plugin .

Like this one ; 

`MySQL ERROR: [{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":134,"function":"log_error","args":["[sqlDAL::readSql] (mysqlnd) Prepare failed: (1146) Table 'AVideoHomeTest.livelinks' doesn't exist (SELECT count(id) as total FROM livelinks v WHERE 1=1 AND categories_id = ?  AND `type` = 'public' ) - format=(i) values=[13]"]},{"file":"\/var\/www\/html\/AVideo\/objects\/category.php","line":606,"function":"readSql","class":"sqlDAL","type":"::" ..............`

PS : I don't even have the livelinks plugin enabled ( I don't use it )

**Comment by DanielnetoDotCom** [comment]
Install the tables or update the livelinks plugin

**Comment by DanielnetoDotCom** [comment]
this update will avoid this error in the future

**Comment by akhilleusuggo** [comment]
> Install the tables or update the livelinks plugin

Native plugins can not be updated . ( I don't see update bouton or anything )
![image](https://user-images.githubusercontent.com/52116577/103910421-7ab46700-510d-11eb-8b17-e99347f035e8.png)

btw , looks like it fixed after update

**Comment by DanielnetoDotCom** [comment]
if there is no button, there is nothing to update.

**Comment by akhilleusuggo** [comment]
thanks ( but was broken before the update , but couldn't even access the website )
