### ISSUE TITLE
Quality of one embedded video link differs to the other embedded video link

### ISSUE THREAD

**Issue by IREBS** [WWBN/AVideo#4312]
Hello,

I have the following problem: when I encode videos I have the following phenomenon that the quality of one embedded video link differs to the other embedded video link, although HD is set. 
However, when I open the video link "mp4_1080" under download file the quality is consistently good.

Is there a logical connection, is it depending on the performance of my server?

**Comment by akhilleusuggo** [comment]
play it in full screen

**Comment by IREBS** [comment]
There is no difference whether in fullscreen or in window mode (halfscreen).

**Comment by akhilleusuggo** [comment]
> Is there a logical connection, is it depending on the performance of my server?

No , is the same source file . My only guess was that you were comparing them not both at full screen .

Also one thing , you stated that the video you playing is mp4_1080 , but the video player shows HD .
Maybe you're double encoding the video , and the quality selector is confused between Low,SD,HD and 240p,360p.....1080p

You should see this , if you want to compare the quality under 

> "mp4_1080" under download file

![image](https://user-images.githubusercontent.com/52116577/103763247-3bf5b280-5022-11eb-8687-bf4ae1602f1e.png)

FHD is the one standing for 1080 .

**Comment by IREBS** [comment]
![pic](https://user-images.githubusercontent.com/73329882/103764667-3006f200-501c-11eb-8746-56ecdee3ef8c.png)

**Comment by akhilleusuggo** [comment]
I mean , the quality selector on the embedded video .

**Comment by IREBS** [comment]
See, there is no selector on the embedded video, maybe I am also blind

![picture2](https://user-images.githubusercontent.com/73329882/103768231-70696e80-5022-11eb-8896-14521a7820ac.png)

**Comment by akhilleusuggo** [comment]
That is the point I'm traying to make. How do you embed the video ?

The embed comparison should look like this ;

Original video : https://demo.avideo.com/video/306/1
Embed video : https://demo.avideo.com/videoEmbed/306/1     ( the embed video DOES have the quality selector )

More options here : 

![image](https://user-images.githubusercontent.com/52116577/103769435-eb378700-502c-11eb-9c3b-d24d0fa863a6.png)

**Comment by IREBS** [comment]
Sorry, but I don't have or maybe don't see those options on the embedded video. Here is the embedded code:
![picture3](https://user-images.githubusercontent.com/73329882/103775584-8846ef80-502e-11eb-9b90-dd82e65e1964.png)

**Comment by IREBS** [comment]
Sorry, but I don't have or maybe don't see those options on the embedded video. Here is the embedded code:
![picture3](https://user-images.githubusercontent.com/73329882/103775725-c3492300-502e-11eb-8b54-a6c2f80ef377.png)


May

**Comment by akhilleusuggo** [comment]
I think all you need is to not have selected this option ( Plugin advanced user )

![image](https://user-images.githubusercontent.com/52116577/103779924-00b4ad00-503d-11eb-83cf-ab5ba4fafa6e.png)


I switched to DE ( german ) and I have no issues . Did you try to update ? Also , I don't have this getButtonCopyToClip .
I'm not sure what's wrong . But embedding should give the same quality . In your case , try this URL .

yoursite.com/videoEmbed/607/03_3.... and see if the quality is the same .

**Comment by DanielnetoDotCom** [comment]
maybe @IREBS is looking for the resolution plugin, what you do not have yet

**Comment by akhilleusuggo** [comment]
owww ...

**Comment by IREBS** [comment]
@akhilleusuggo: I have unselected the two options -> nothing has changed

@DanielnetoDotCom: My main problem is that when I upload the same video twice or three times in a row, the quality is sometimes good, sometimes OK and sometimes bad.

**Comment by akhilleusuggo** [comment]
But do you have the plugin quality selector ?
