### ISSUE TITLE
Save stream and a few questions 

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4314]
Hi hi :)

What does Save Stream do?.  It does not save under My Channel or anything whete users can see you created a stream?. 

Is it possible to add it to a channel with a date and time when stream will go live with some text stating "Upcoming Event" or "Upcoming Stream"?.  Then when stream go live and it finish then the recorded stream can be saved on My Channel as a video via encoder and delete origional Stream entry(Save Stream entry)?.

**Comment by akhilleusuggo** [comment]
To save streams you need plugin from marketplace ; 

![image](https://user-images.githubusercontent.com/52116577/103944033-c120ba80-513b-11eb-840d-805f0d681042.png)

And configure it properly with rtmp-nginx ; 

If { 
Both rtmp-nginx and your site are on the server server , follow up this guide ; https://github.com/WWBN/AVideo/wiki/Record-Live-Stream

if else ; 
follow up this guide ; https://github.com/WWBN/AVideo/wiki/Live-Plugin
}

**Comment by unconservo** [comment]
Hi. But tgat does not answer the question. That will only encode the
finished live stream and save it to you channel..ir is that what save
stream does? Snd only save with the plugin installed?

**Comment by DanielnetoDotCom** [comment]
It will only encoder when you finish the livestream. while you stream the file is saved on the live server.

**Comment by akhilleusuggo** [comment]
@unconservo You can also playback it temporally if you have increase the hls_playlist .

**Comment by unconservo** [comment]
I bought the plugin.. and was working and then i started getting these errors

[09-Jan-2021 23:33:28 Africa/Johannesburg] PHP Warning:  filectime(): stat failed for path/to/my/streamer/site/videos/Testingstreamagainon09Jan21233114_YPTuniqid_5ffa20c7408ba8.53873689_thumbsSprit.jpg in path/to/my/streamer/site/plugin/VideoThumbnails/VideoThumbnails.php(14) : eval()'d code(1) : eval()'d code on line 74

**Comment by DanielnetoDotCom** [comment]
@unconservo This is not an error it is just a warning

**Comment by unconservo** [comment]
Okidoki. Thanx. Will monitor it.
