### ISSUE TITLE
Playlist to live feature

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4315]
Hi hi. I cannot find this function after i updated. Where do I find it? :)

Regards

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/103943880-84ed5a00-513b-11eb-830b-d8234c56ad09.png)

**Comment by unconservo** [comment]
Thank you. But that only gives adminustrators rights to create scheduled
playlists?. Arnt it available when a serup a live stream?

**Comment by DanielnetoDotCom** [comment]
The play playlist live still under development, it is published only for testing propose

**Comment by unconservo** [comment]
O ok :)
