### ISSUE TITLE
The encoder Shows no Quality Change

### ISSUE THREAD

**Issue by s-maisch** [WWBN/AVideo#4317]
Hello, 

i have installes the encoder, when i upload a movie i cant change the setting. I will only Upload in 1 quality (HD).

what can i do ? Sorry for my bad english.

![quality](https://user-images.githubusercontent.com/77123746/103937490-1b645000-5129-11eb-9b07-d12b84f94499.jpg)

**Comment by akhilleusuggo** [comment]
Go to plugins , CustomizeAdvanced 

Disable all this options , leave only the selected in red one ;

![image](https://user-images.githubusercontent.com/52116577/103943712-3b047400-513b-11eb-9dc6-20265a7b6e6e.png)
