### ISSUE TITLE
upload video link

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4318]
**Describe the question**
Hi i have a new install of the avideo software, i can upload via http://link/upload but not from the main site.
The video audio upload link on the top/right goes to the start site , why ? 

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by 01123581321345589144233** [comment]
https://image.linuxhus.dk/01123581321345589144233/images/1c7cbdd489bf4d990e513587cf7f054f.png

**Comment by DanielnetoDotCom** [comment]
did you set up an encoder?

![image](https://user-images.githubusercontent.com/18009293/104020588-36bc7300-519c-11eb-8abb-691de7196589.png)

also, check this https://github.com/WWBN/AVideo/wiki/Private-Encoder

**Comment by 01123581321345589144233** [comment]
yes the ecncoder is the same machine, must the link have /upload ?

**Comment by DanielnetoDotCom** [comment]
I still do not understand what is happening with you

**Comment by 01123581321345589144233** [comment]
ok i found the issue :-) the link for the encoder was without /upload.
I have changed this to https://mywebsite/upload and it works
