### ISSUE TITLE
Play embedded video with user group

### ISSUE THREAD

**Issue by SaliC-re** [WWBN/AVideo#4321]
Hey there, happy new year to all.

I have a question for embedding videos which are tagged in a user group.
Following scenario:
Our video site has 2 areas - public und internal
We set a user group which we called "INTERNAL" and if we activate that, all users who have the user group "INTERNAL" too, can see this video. All users who come from public, cannot see it.
This works fine.

But the problem is when embedding a video:
![image](https://user-images.githubusercontent.com/63057086/104002022-c6fcb700-51a0-11eb-9b6e-c84d2825fd80.png)
How can I embed a private/grouped video? You know any workarounds?

The solution with untagging the group, setting the video to unlisted and then embed is known, but if someone has the direct link to the video, he can view it.

Our embedding should be limited to one or more specific internal sites.

**Comment by akhilleusuggo** [comment]
Is not gonna work , since the users are not connected ( from my understanding ) .
You need to be connected to be able to watch . Since you're embedding the video , the main site can not check if the user is allowed or not . 

This is a bad idea .

Try embedding with password ' never tried it ' . But I don't think there are much options .

**Comment by DanielnetoDotCom** [comment]
Did you try this?

![image](https://user-images.githubusercontent.com/18009293/104020239-a7af5b00-519b-11eb-8af7-626e24097ba3.png)

So you do not have to worry about usergroups and you can control access on the site you will embed the videos.

**Comment by SaliC-re** [comment]
> Did you try this?
> 
> ![image](https://user-images.githubusercontent.com/18009293/104020239-a7af5b00-519b-11eb-8af7-626e24097ba3.png)
> 
> So you do not have to worry about usergroups and you can control access on the site you will embed the videos.

This seems nice i'll try it on monday an give reply

**Comment by SaliC-re** [comment]
sorry for the delay - but still some questions.
I saw that this plugin is a paid plugin which we dont have.
But nevertheless if we activate it we are not able to play videos on the site itself

So which way is easier to customize? 
The whitelist plugin which should allow playing the videos on the site?
Or do we have other options to activate embedding WITH groups?

**Comment by DanielnetoDotCom** [comment]
You must whitelist all the domains you want to use to embed your videos.

all non-whitelisted domains will get a forbidden page

**Comment by SaliC-re** [comment]
> You must whitelist all the domains you want to use to embed your videos.
> 
> all non-whitelisted domains will get a forbidden page

thats ok - but will we be able to play videos on the video site itself? without embedding?

**Comment by DanielnetoDotCom** [comment]
Yes you will

**Comment by SaliC-re** [comment]
Hi there again. 
I need a bit of help with using the SecureVideosDirectly plugin correctly.
I bought it now to secure my site from playing videos outside of my own website.

1. I installed it and restarted apache but my old videos still have no token and are able to play with the direct URL
Is it only for new uploaded videos now?

2. @DanielnetoDotCom you said that if I active "play only whitelisted" I will still be able to play the videos on my AVideo-website itself. But here you said:

> correct it will not play even on the website.
> 
> it is usable if you want to share your videos in a paywall (another website with iframes). so even if the user has the direct link to it, it will not play
> 
> again, your videos will only play inside iframe
> 
> _Originally posted by @DanielnetoDotCom in https://github.com/WWBN/AVideo/issues/4334#issuecomment-757480481_

what is correct now? I can't test it because all videos are still playable.

3. My target is to prevent unlisted videos from playback via direct URL but all other public videos should still be playable on AVideo site. Is it possible with this plugin?

**Comment by SaliC-re** [comment]
> Hi there again.
> I need a bit of help with using the SecureVideosDirectly plugin correctly.
> I bought it now to secure my site from playing videos outside of my own website.
> 
> 1. I installed it and restarted apache but my old videos still have no token and are able to play with the direct URL
>    Is it only for new uploaded videos now?
> 2. @DanielnetoDotCom you said that if I active "play only whitelisted" I will still be able to play the videos on my AVideo-website itself. But here you said:
> 
> > correct it will not play even on the website.
> > it is usable if you want to share your videos in a paywall (another website with iframes). so even if the user has the direct link to it, it will not play
> > again, your videos will only play inside iframe
> > _Originally posted by @DanielnetoDotCom in [#4334 (comment)](https://github.com/WWBN/AVideo/issues/4334#issuecomment-757480481)_
> 
> what is correct now? I can't test it because all videos are still playable.
> 
> 1. My target is to prevent unlisted videos from playback via direct URL but all other public videos should still be playable on AVideo site. Is it possible with this plugin?

info: I logged myself out an in and now I got the message "not whitelisted" - which is OK

**Comment by DanielnetoDotCom** [comment]
test it from an incognito browser, if you are an admin and test from the same browser (even different tabs), the video will always play

**Comment by SaliC-re** [comment]
question 1 solved, thanks.

question 2 and 3 still open

**Comment by DanielnetoDotCom** [comment]
> you said that if I active "play only whitelisted" I will still be able to play the videos on my AVideo-website itself. But here you said:

Disable embed mode, so only the whitelisted sites will play 
![image](https://user-images.githubusercontent.com/18009293/108349035-45e20800-71c1-11eb-9ca5-8461c68c4a81.png)

> My target is to prevent unlisted videos from playback via direct URL but all other public videos should still be playable on AVideo site. Is it possible with this plugin?

Also, check the Play Only Whitelisted, so the videos will only play if they are embedded

Again: test it on an incognito browser, if you log in as admin you will be able to play any video

![image](https://user-images.githubusercontent.com/18009293/108349217-7b86f100-71c1-11eb-90a0-bc92b50ef0b7.png)

**Comment by SaliC-re** [comment]
Hi again,

status update:
I installed and configured the SVD plugin correctly.
All whitelisted sites are now able to play the videos which are embedded.

Question 1:
Can you not put in an optional field in the plugin like "Enable play videos on site itself" ?
Because all videos on site have now this:
![image](https://user-images.githubusercontent.com/63057086/109968807-73679f00-7cf3-11eb-960a-69e953b61ed1.png)

Question 2:
We want to have 2 video-worlds with only one site. With the SVD plugin we created now the second world of embedded videos which are save from external play. But now we closed the first world (site itself) for playing videos. 
Let's say you dev in this flag from question 1 - then we have another problem.

I activated a group "company internal" for internal videos. But if we embed them, following happens:
![image](https://user-images.githubusercontent.com/63057086/109970378-44eac380-7cf5-11eb-8756-ee1f683dddf9.png)
Maybe here is some dev again? Like "ignore this group for embedding" ?

**Comment by DanielnetoDotCom** [comment]
Hi, those requirements are not clear to me. maybe we need a consulting meet and probably it requires some dev.
