### ISSUE TITLE
ports for the streamer/live

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4322]
**Describe the question**
Hi, i will setup a extra streamer with your howto.
Witch ports are required for the streamer ?
I can see the nginx has 8443

Are there  other ports ?

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by akhilleusuggo** [comment]
on a separated server could be anyone ( the 8443 is to avoid conflict with apache/nginx ssl )
8080 ( non-ssl port for rtmp-nginx ) , 8443 ( ssl rtmp-nginx )

**Comment by 01123581321345589144233** [comment]
ok thanks, what is the remote file url ? in the live servers config
https://image.linuxhus.dk/01123581321345589144233/images/6f30e7b1144cc6be090782881c5b1149.png

**Comment by DanielnetoDotCom** [comment]
Usually, the file is the one you have on the plugin https://github.com/WWBN/AVideo/blob/master/plugin/Live/standAloneFiles/getRecordedFile.php

but only makes sense if you have the SendRecordedToEncoder plugin

**Comment by 01123581321345589144233** [comment]
ok så i can copy the file to /var/www/AVideo/plugin/Live
and the url are https://link/live/getRecordedFile.php

is this correct ?

**Comment by akhilleusuggo** [comment]
anywhere that is public .

It's useful in remove rtmp-nginx
In my case , I have it on /usr/local/nginx/html/getRecordedFile.php

so the url is live.example.com:8443/getRecordedFile.php

**Comment by 01123581321345589144233** [comment]
ah ok thanks

**Comment by 01123581321345589144233** [comment]
must i change lines in this file ?

**Comment by 01123581321345589144233** [comment]
ok i have a teststream, is this stream saved/recorded in my channel ?

**Comment by 01123581321345589144233** [comment]
ok i have also setup this one:
https://github.com/WWBN/AVideo/wiki/Record-Live-Stream
and i can see the recordet file are in the tmp, but there is nothing in the encoder.

**Comment by akhilleusuggo** [comment]
you need to buy the plugin from the market place ; https://youphp.tube/marketplace/
SendRecordedToEncoder

**Comment by 01123581321345589144233** [comment]
Ok i have buy the plugin and the script is also online under live.example.com:8443/getRecordedFile.php
but the video is not sendet to the encoder

**Comment by 01123581321345589144233** [comment]
[Sat Jan 16 15:13:36.010478 2021] [proxy_wstunnel:error] [pid 10473] [client ****:54840] AH02452: failed to make connection to backend: 127.0.0.1
[Sat Jan 16 15:13:43.351259 2021] [proxy:error] [pid 19591] (111)Connection refused: AH00957: WS: attempt to connect to 127.0.0.1:8888 (127.0.0.1) failed

**Comment by DanielnetoDotCom** [comment]
Is the live server in a separate server or on the same server as the streamer?

**Comment by 01123581321345589144233** [comment]
is the same server, but i will also setup other servers

**Comment by 01123581321345589144233** [comment]
when i go to my encoder and make a bulk encode from /var/www/tmp i can see all the recordings, and i can encode them

**Comment by 01123581321345589144233** [comment]
my recordet file look like this:
https%3A%2F%2Ftube.011235813213455.dk%2Fplugin%2FLive%2Fon_publish.php-16-Jan-21-17:56:39.flv

**Comment by akhilleusuggo** [comment]
That is because you have issues related to redirect .
Also this means that your stat page does not dispel the stream key .
Also mean that when you streaming doesn't show that you're online . Without the key stream , the script can't tell to witch streamer ( user ) the video file does belong .

Related issues ;  
https://github.com/WWBN/AVideo/issues/3964 
https://github.com/WWBN/AVideo/issues/4299
https://github.com/WWBN/AVideo/issues/3052  ( this one exactly like you )
https://github.com/WWBN/AVideo/issues/1945


### Template solution answer 

Just to add some very important detail . I know why @DanielnetoDotCom does not have this issues on his installations . And that because the HTTPS redirect works ONLY if your nginx.conf is pointing to LOCALHOST . In other words , if you streamer site , and nginx-rtmp are hosted on the same server , you can use `http://localhost/Avideo/plugin/Live/on_publish.php` instead of your domain name , and will work without the need or any type of redirect , since it's locally hosted under the SAME SSL . 

If you're pointing to a domain name , or your nginx-rtmp is hosted somewhere else , this will not work !! 
My solution was this : 

```
RewriteEngine on
# Go to https if not on /plugin/Live/

RewriteCond %{SERVER_PORT} =80
RewriteCond %{THE_REQUEST} !/plugin/Live/ [NC]
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# Go to http if on /for on_connect.php, on_done.php, on_play.php , on_publish.php , on_record_done.php /

RewriteCond %{SERVER_PORT} !=80
RewriteCond %{THE_REQUEST} /plugin/Live/* [NC]
RewriteRule ^(.*)$ http://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

</VirtualHost>
```

Adding this lines to the /etc/apache2/sites-available/yoursite.conf , or .htaccess will fix the issue .

This issue in known https://github.com/winshining/nginx-http-flv-module/issues/130
This would require the support on RTMPS if we want to use httpS://localhost/Avideo/plugin/Live/on_publish.php

Conclusion : **If you pointing your on_done , on_publish , on_record , with http , your site url MUST be accessible with http, and not redirecting to https !**

**Comment by 01123581321345589144233** [comment]
ok thanks it works i have also removed the http to https forwarding. So now i can see my livestream in my account and its under transcoding, why take this so long time ? that was only a 2 min livestream

**Comment by 01123581321345589144233** [comment]
hm the teststream is still on transcoding ?

**Comment by akhilleusuggo** [comment]
idk , it's your server . You should know what is happening there . Check the log files

**Comment by 01123581321345589144233** [comment]
2021/01/17 10:53:55 [error] 11154#0: *82 open() "/HLS/live/60002c504467d/index.m3u8" failed (2: No such file or directory), client: 5.206.193.172, server: tube.011235813213455.dk, request: "GET /live/60002c504467d/index.m3u8 HTTP/1.1", host: "tube.011235813213455.dk:8443", referrer: "https://tube.011235813213455.dk/plugin/Live/"
2021/01/17 10:53:55 [error] 11154#0: *82 open() "/HLS/live/60002c504467d/index.m3u8" failed (2: No such file or directory), client: 5.206.193.172, server: tube.011235813213455.dk, request: "GET /live/60002c504467d/index.m3u8 HTTP/1.1", host: "tube.011235813213455.dk:8443", referrer: "https://tube.011235813213455.dk/plugin/Live/"
2021/01/17 10:54:05 [error] 11154#0: *82 open() "/HLS/live/60002c504467d/index.m3u8" failed (2: No such file or directory), client: 5.206.193.172, server: tube.011235813213455.dk, request: "GET /live/60002c504467d/index.m3u8 HTTP/1.1", host: "tube.011235813213455.dk:8443", referrer: "https://tube.011235813213455.dk/plugin/Live/"
2021/01/17 10:54:17 [info] 11154#0: *85 client connected '5.196.91.25'
2021/01/17 10:54:17 [info] 11154#0: *85 connect: app='live' args='p=388ebb3827c62ccb07e3f63ff7b996d3' flashver='FMLE/3.0 (compatible; Lavf57.56' swf_url='' tc_url='rtmp://tube.011235813213455.dk:1935/live?p=388ebb3827c62ccb07e3f63ff7b996d3' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 5.196.91.25, server: 0.0.0.0:1935
2021/01/17 10:54:18 [info] 11154#0: *85 createStream, client: 5.196.91.25, server: 0.0.0.0:1935
2021/01/17 10:54:18 [info] 11154#0: *85 publish: name='60002c504467d' args='' type=live silent=0, client: 5.196.91.25, server: 0.0.0.0:1935
2021/01/17 10:54:18 [info] 11154#0: *85 notify: publish 'tube.011235813213455.dk/plugin/Live/on_publish.php', client: 5.196.91.25, server: 0.0.0.0:1935
2021/01/17 10:54:45 [info] 11154#0: *82 client 5.206.193.172 closed keepalive connection
2021/01/17 10:55:10 [error] 11154#0: *103 access forbidden by rule, client: 127.0.0.1, server: tube.011235813213455.dk, request: "GET /control/drop/publisher?app=live&name=60002c504467d HTTP/1.0", host: "localhost:8080"
2021/01/17 10:55:58 [error] 11154#0: *111 access forbidden by rule, client: 127.0.0.1, server: tube.011235813213455.dk, request: "GET /control/drop/publisher?app=live&name=60002c504467d HTTP/1.0", host: "localhost:8080"
2021/01/17 10:56:00 [info] 11154#0: *85 deleteStream, client: 5.196.91.25, server: 0.0.0.0:1935
2021/01/17 10:56:00 [info] 11154#0: *85 notify: record_done recorder=video path='/var/www/tmp/60002c504467d-17-Jan-21-10:54:18.flv' url='tube.011235813213455.dk/plugin/Live/on_record_done.php', client: 5.196.91.25, server: 0.0.0.0:1935
2021/01/17 10:56:00 [info] 11154#0: *85 disconnect, client: 5.196.91.25, server: 0.0.0.0:1935
2021/01/17 10:56:00 [info] 11154#0: *85 deleteStream, client: 5.196.91.25, server: 0.0.0.0:1935

**Comment by 01123581321345589144233** [comment]
the apache logfile:

[hls,applehttp @ 0x558afa3f6e00] Opening 'https://tube.011235813213455.dk:8443/live/60002c504467d/2.ts' for reading
Input #0, hls,applehttp, from 'https://tube.011235813213455.dk:8443/live/60002c504467d/index.m3u8':
  Duration: N/A, start: 10.475600, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720, 30 tbr, 90k tbn, 60 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[swscaler @ 0x558afae781e0] deprecated pixel format used, make sure you did set range correctly
Output #0, image2, to '/tmp/312b41bb8a538a9ee00a99725290afe0.jpg':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: mjpeg, yuvj420p(pc), 400x225, q=2-31, 200 kb/s, 30 fps, 30 tbn, 30 tbc
    Metadata:
      variant_bitrate : 0
      encoder         : Lavc57.107.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=    1 fps=0.0 q=4.7 Lsize=N/A time=00:00:00.03 bitrate=N/A dup=1 drop=1 speed=0.662x    
video:13kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

**Comment by 01123581321345589144233** [comment]
ok i go back to the localhost config, when ist done i go forward to the domain config in the nginx config.
I have chenged the config to http://localhost/live.....
and i have startet a livestream with manuel recording.

2021/01/17 12:00:57 [info] 5110#0: *67 createStream, client: 5.196.91.25, server: 0.0.0.0:1935
2021/01/17 12:00:57 [info] 5110#0: *67 publish: name='5ff764d482ab4' args='' type=live silent=0, client: 5.196.91.25, server: 0.0.0.0:1935
2021/01/17 12:00:57 [info] 5110#0: *67 notify: publish 'localhost/plugin/Live/on_publish.php', client: 5.196.91.25, server: 0.0.0.0:1935
2021/01/17 12:01:22 [error] 5110#0: *71 access forbidden by rule, client: 127.0.0.1, server: tube.011235813213455.dk, request: "GET /control/drop/publisher?app=live&name=5ff764d482ab4 HTTP/1.0", host: "localhost:8080"

**Comment by 01123581321345589144233** [comment]
ok it works with the localhost configuration, but when i change this back to domain config in the nginx, change the ssl redirect:

RewriteEngine on
# Go to https if not on /plugin/Live/

RewriteCond %{SERVER_PORT} =80
RewriteCond %{THE_REQUEST} !/plugin/Live/ [NC]
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# Go to http if on /for on_connect.php, on_done.php, on_play.php , on_publish.php , on_record_done.php /

RewriteCond %{SERVER_PORT} !=80
RewriteCond %{THE_REQUEST} /plugin/Live/* [NC]
RewriteRule ^(.*)$ http://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

it hangs on transcoding.

**Comment by 01123581321345589144233** [comment]
ok now after i have changed the main url in the SendRecordedToEncoder to the site url, it works perfekt.

**Comment by akhilleusuggo** [comment]
nice to know . Because on the first logs you didn't changed the redirect ; https://tube.011235813213455.dk/plugin/Live/on_publish.php still pointing to https redirect . Anyway good luck . 

Glad it helps
