### ISSUE TITLE
Live stream on static video ID

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4323]
The idea is to give to each stream a static video ID ( like normal videos ) , having likes , ( probably comments ) , and views counts .
When the stream is over , is sent to the encoder , and moved back to the streamer site under the same ID video that was streaming. This way it keeps the statistics ( views/likes/ etc )

**Comment by DanielnetoDotCom** [comment]
Right now it is a lot of changes, what about auto-renew the publish key when the live is finished?

**Comment by akhilleusuggo** [comment]
But that will force users to change every time the key , or they can't stream .
The idea is to get views from live + video recorded . Also improve the video SEO .

It is just an idea . I know this will need a ton of change .
