### ISSUE TITLE
phpmailer.php

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4324]
`PHP Warning:  require_once(/var/www/html/AVideo/objects/include_phpmailer.php): failed to open stream: No such file or directory in /var/www/html/AVideo/objects/functions.php on line 532`

`PHP Fatal error:  require_once(): Failed opening required '/var/www/html/AVideo/objects/include_phpmailer.php' (include_path='.:/usr/share/php') in /var/www/html/AVideo/objects/functions.php on line 532`

**Comment by akhilleusuggo** [comment]
this line is wrong , there no such file named `objects/include_phpmailer.php` on the branch .

https://github.com/WWBN/AVideo/blob/f80d45a63e9d0ec48d8674b273258e72bc835bd2/objects/functions.php#L532

**Comment by DanielnetoDotCom** [comment]
As long as we are using the composer this line is not required anymore, thanks for noticing that

**Comment by akhilleusuggo** [comment]
👍
