### ISSUE TITLE
Chromecast

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4329]
**Describe the question**
Hi in the plugins directory is a plaugin named Chromecast, i have try this but its not working.
Are there any configs ?

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by akhilleusuggo** [comment]
There's an option on HLS plugin

![image](https://user-images.githubusercontent.com/52116577/104120579-9489c000-5340-11eb-9cf1-0403bc6c088d.png)

**Comment by 01123581321345589144233** [comment]
you meen the videohls on https://youphp.tube/marketplace/

**Comment by akhilleusuggo** [comment]
Yes . I never used Chromecast , but I can see the option . Before you buy , try it on demo site ; https://demo.avideo.com/
