### ISSUE TITLE
Video not streaming from internal network without internet connection of the streamer server.

### ISSUE THREAD

**Issue by elias2k1** [WWBN/AVideo#4333]
Is there any requirements of internet connection of the streamer or encoder server (both installed in same server)? I don't want to open internet for those server as its only server for internal network user. But when I close internet for the host IP, steaming stops and the web server performance degrade. Any suggestion?

**Comment by akhilleusuggo** [comment]
The the streams stops is not normal . ( maybe you've misconfigured something ) . Check log files and your config IP 

> and the web server performance degrade

I've noticed that too . I believe is related to some extra requests made externally for confirmations .

**Comment by elias2k1** [comment]
Sample Error collected from Error Log of webserver:
======================================
[Sun Jan 10 11:09:45.779742 2021] [proxy_fcgi:error] [pid 109998] [client _Server_IP_:36560] AH01071: Got error 'Primary script unknown'
[Sun Jan 10 11:09:45.789767 2021] [proxy_fcgi:error] [pid 110398] [client _Server_IP_:36562] AH01071: Got error 'Primary script unknown'
[Sun Jan 10 11:09:45.793864 2021] [proxy_fcgi:error] [pid 110066] [client _Server_IP_:36564] AH01071: Got error 'Primary script unknown'

**Comment by unconservo** [comment]
Are you using ubuntu?. Have you changed the hostfile?.  Make sure your hostfile is set correctly else internal devices will not see server :)

**Comment by elias2k1** [comment]
The server is behind the firewall with only internal network IP address like my other web server. And it resolved from internal network. It work properly when I gave internet access to this IP but not working if I revoke the internet access. Moreover performance reduced radically. 
I am using Ubuntu and configure the hostfile properly.

**Comment by akhilleusuggo** [comment]
This issue is more likely related to apache2/php

`Got error 'Primary script unknown'`

**Comment by unconservo** [comment]
Yes or routing on firewall

**Comment by elias2k1** [comment]
From internal network, we don't need to go through firewall. We can directly communicate with the streaming server. I am also using ubuntu for different web service in another server. That never cause problem. That's why I am really worried about this service to bring it on in production environment for this peculiar behavior.

**Comment by elias2k1** [comment]
[Tue Jan 12 11:09:33.180352 2021] [proxy_fcgi:error] [pid 131526] (70007)The timeout specified has expired: [client _Client_pc_ip_:3580] AH01075: Error dispatching request to : (polling), referer: http://_streamin_server_ip_/video/33/video-name?channelName=xyz
[Tue Jan 12 11:09:46.264393 2021] [proxy_fcgi:error] [pid 131864] (70007)The timeout specified has expired: [client _Client_PC_IP_:3746] AH01075: Error dispatching request to : (polling)

**Comment by akhilleusuggo** [comment]
@elias2k1 As I've said before , your issues are not related to the script , but you're having server management issues .
Google is your friend ; `The timeout specified has expired`

Issue as I've stated above , related to apache/php configuration. 
What PHP are you using ? PHP-FPM ?

Consider increasing the `max_execution_time` , but most importantly `Timeout` . 
Longer video playback , requires higher timout and encoding requires higher max_execution_time .

All the issues you're linking , are not from avideo.log , but from the global `syslog` / `error.log` under your apache/php logs .

**Comment by elias2k1** [comment]
Ok. I will dig down more for the issue. BTW I am using PHP-FPM. But I still can't understand why its working properly when it have internet access.
