### ISSUE TITLE
SecureVideosDirectory

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4334]
Some question and lack of documentation about .

1- When I enable this 2 option , the videos does not play anymore ( not even from streamer site ) . I tried to whitelist my own site ( url ) , but it doesn't work . Does the protocols also interferers ? http & https ? Or I can leave it as www.example.com

![image](https://user-images.githubusercontent.com/52116577/104122989-171a7b80-5351-11eb-8a58-0a6590848d73.png)

2- Trying to have direct access to mp4 does deny the access ( that's good ) .

![image](https://user-images.githubusercontent.com/52116577/104123044-6a8cc980-5351-11eb-90e8-f380edffe5c5.png)

But with inspection you can get that token , and accessing with token does allow me to playback the video .
Is there any option to renew to generate a new token to each request ? And give to each of them a lifetime but for multiple of them ?

I just don't understand well how this works . Because people will still be able to embed your video for the next 21600s (6h) . 
Making this number smaller can give playback issues , with the need to reload the page to be able to continue .

**Comment by DanielnetoDotCom** [comment]
To be able to play when you select "Play Only Whitelisted" your videos must be in an iFrame inside the whitelisted site.

**Comment by akhilleusuggo** [comment]
But why is it disabled even on my website . Tested on demo site , and no video is working ;
Getting this error ; 

![image](https://user-images.githubusercontent.com/52116577/104124085-5f3c9c80-5357-11eb-9c82-b4fccd3db7a7.png)

**Comment by DanielnetoDotCom** [comment]
correct it will not play even on the website.

it is usable if you want to share your videos in a paywall (another website with iframes). so even if the user has the direct link to it, it will not play

again, your videos will only play inside iframe

**Comment by akhilleusuggo** [comment]
I see . Thanks
