### ISSUE TITLE
Chat 2 on channels

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4337]
Hi. Chat 2 fills all of the screen on mobile if enabled for view in channel. It is set to static. If i take static off and click baloon it does the same thing..
![20210111_084430](https://user-images.githubusercontent.com/76112286/104152514-75466d80-53e8-11eb-924a-ea85a3d26d4f.jpg)

**Comment by unconservo** [comment]
Also when selecting mote chatroom and thrn selecting chat it takes away the site header

**Comment by DanielnetoDotCom** [comment]
try to select this option

![image](https://user-images.githubusercontent.com/18009293/104220765-bb1e2880-541e-11eb-9426-cde6be658371.png)

**Comment by unconservo** [comment]
I did. Same thing.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot where exactly are you clocking to get this ?

**Comment by unconservo** [comment]
Hi. I click on a channel name.
1st pic is without static checked with bubble...
![20210111_211723](https://user-images.githubusercontent.com/76112286/104227764-8f1c9a80-5452-11eb-9c2e-01f2c7170047.jpg)

So if i click bubble i get this screen over the channel...
![20210111_211803](https://user-images.githubusercontent.com/76112286/104227828-a78cb500-5452-11eb-84d1-caca8ced8b13.jpg)

Then i changed to the static ... checked it.. i go back to channel. Chat2 minimized.
![20210111_211952](https://user-images.githubusercontent.com/76112286/104227934-cf7c1880-5452-11eb-98d7-e57416dc15fd.jpg)

Opening chat it also goes over channel info...
![20210111_212041](https://user-images.githubusercontent.com/76112286/104228005-e91d6000-5452-11eb-8a7c-51bd5ad26b0e.jpg)

Chat2 settings :
![20210111_211817](https://user-images.githubusercontent.com/76112286/104228045-f9353f80-5452-11eb-86b5-f700dd5d824c.jpg)
![20210111_211849](https://user-images.githubusercontent.com/76112286/104228083-03573e00-5453-11eb-84be-46d5ee9f2238.jpg)
