### ISSUE TITLE
Email logo?

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#4341]
My Avideo-website default logo is white. It doesn't show on notifications emails because the email background is white. 

I tried to change the logo in this field on Notifications plugin: 

![image](https://user-images.githubusercontent.com/63721378/104293601-d80e3680-54c6-11eb-834e-9f4c84d47429.png)

The emails are still using website default logo. I cleared the caches but no work.

How can I change the email logo?

**Comment by akhilleusuggo** [comment]
You need to add a public link , preferred to be hosted on your site . 
Default logo should be here : www.example.com/videos/userPhoto/logo.png
You could upload a picture to your site or other sites and past there link on the blank field;

**Comment by tonuzo** [comment]
I did it I uploaded the logo on my site and tried to add the link on the field. The field is empty on the picture above just to show you what field I tried to use. It just doesn't work..

**Comment by akhilleusuggo** [comment]
try to access your img from the browser .
It works fine for me .
Also make sure to give the right permissions to folder and user-group .

If you're changing the codes , writing etc . You wanna make sure that all files belongs to www-data user/group

```
cd /var/www/html
chown www-data:www-data -R *
```
 Clear the cache , and try again to upload

**Comment by tonuzo** [comment]
I can see from the notification email that the "invisible" logo refers to:
videos/userPhoto/logo.png

I'm talking about signUpAutoResponseMessage, but I guess notifications are using same email template..?
