### ISSUE TITLE
Windows 7 with IE 11

### ISSUE THREAD

**Issue by Fnaxx** [WWBN/AVideo#4342]
Hello,

I know that IE11 on Windows 7 is not supporting the HLS protocol for streaming feature. I have seen that to make it works with video.js it requires to use the video.js flash version.
Did you already address such issue? (I know that it is now well support OS and browser anymore but we saddly still have users in that configuration)

Best regards

**Comment by DanielnetoDotCom** [comment]
we are using videojs ver 7.

maybe for this, you need an older version.
