### ISSUE TITLE
video title (words) as tags

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4343]
Anyway to include the title ''words'' as tags for search ?

I mean , if the title of a video is , _guide for AVideo installation_  , and you search for _guide installation_ , nothing will show up . 
Only if you type exactly the same title and words in order , or you have tags created with **guide**, **installation**

**Comment by DanielnetoDotCom** [comment]
I will send this update on ver 10.1

**Comment by akhilleusuggo** [comment]
Thank you , this will help to find videos on search ( on streamer site at the least )

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom anyway to have an option to disable description to be pulled ?

This may be misleading . Specially if you have default descriptions .

**Comment by DanielnetoDotCom** [comment]
what do you mean?

do you mean search on description?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom we need to remove search from description yes . It's misleading and wrong search-results

**Comment by DanielnetoDotCom** [comment]
To be honest, I think the search in the description is important, but maybe the title search should be more important.

I agree the full-text search should be on the title only

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom It's really misleading , and I wasn't even able to search on video section to swap video .

I'm still not able to solve this problem . Just nothing is correct ; Demo site .

![image](https://user-images.githubusercontent.com/52116577/104747567-5da91500-5759-11eb-8a00-a7578b885ac7.png)

Showing categories randomly 
Wrong users ( if you're logged in ) , copy of the home-page
Showing videos that doesn't have anything to do with my search .

![image](https://user-images.githubusercontent.com/52116577/104747978-d90ac680-5759-11eb-96be-718c587d2a29.png)


Your idea , is good ( like YouTube ) . But YouTube has advanced algorithms . Also they take keywords ranked ;

1- title
2- Subtitles
3- Maybe description ( only if related ) . They have AI working 24/7

**Comment by DanielnetoDotCom** [comment]
Lets take demo site as an example, those videos were returned from the search "test" because they have the word la**test** in the description (it always return that, even before the update).

We search in 4 places

1. video title
2. video description
3. category title
4. category description

maybe on the description, we should only return if there is the word "test" but NOT "latest"? I am still not sure what would be the best combination

Also, I am not sure how to rank it and yes for sure Google has an algorithm thousands of times better than mine

**Comment by akhilleusuggo** [comment]
I'll rollback version, because this one is unusable for my experience . I can't even search on video page .
Adding description is just horrible . That's why I asked about : **title** (words) as **tags**


![image](https://user-images.githubusercontent.com/52116577/104753540-d2338200-5760-11eb-8904-23b98e5792d4.png)

result , basically all videos ...

**Comment by DanielnetoDotCom** [comment]
if you rollback it will still searching on the description, it was always like that. 

But I will make the description search more strict

**Comment by DanielnetoDotCom** [comment]
Ok, on description fields you MUST have the full word to be returned on the search

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Can you add an option to allow user the choice ? I want to completely remove the description .

> if you rollback it will still searching on the description, it was always like that.

No , it was really never description involved .

**Comment by DanielnetoDotCom** [comment]
Sorry, but the description was always there. but please try this new update. add an option is more complicated.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom , this wasn't like this before . If I write test , I'm expecting videos with words on the title to be ''**test** something'' or '' something **test** somethong'' . But now , is completely irrelated . It's hard to find even your own videos .

![image](https://user-images.githubusercontent.com/52116577/104764093-918f3500-576f-11eb-89f6-b7833057c1f9.png)

**Comment by DanielnetoDotCom** [comment]
The demo site was not updated when you tested

![image](https://user-images.githubusercontent.com/18009293/104765693-0e0e1d80-5748-11eb-9edb-8619232441b5.png)

This video returns because of this word on the description

![image](https://user-images.githubusercontent.com/18009293/104765754-2847fb80-5748-11eb-9bd4-46230d085cc9.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom But you said , you have removed the descriptions .

This is new . Never was before . How to find a video by title then ? I have 15k video , if only 1% of them got a word that I type , this is crazy .

This new update is what causing this issues ;

https://github.com/WWBN/AVideo/blob/5405abaa11992428f394933c03386c765bcb3201/install/database.sql#L86

**Comment by DanielnetoDotCom** [comment]
Description removed from search

**Comment by DanielnetoDotCom** [comment]
I notice something, it was also searching the full text into the categories, so I put the description back into the search, but I removed the category from the fulltext search

**Comment by akhilleusuggo** [comment]
Works !

Just noticed that doesn't work with non-latin characters . 
Tested with Russian characters , and it pulls all videos with Russian letters .

**Comment by DanielnetoDotCom** [comment]
Yes, it ignores the special chars, for example, **Ö** also means **O** or **o**

**Comment by akhilleusuggo** [comment]
I see. Thanks .
