### ISSUE TITLE
PayPerViewLive upcoming events

### ISSUE THREAD

**Issue by esurov** [WWBN/AVideo#4344]
**PayPerViewLive buy page**
I don't get how visitors get the live event Buy page (see screenshot below). Is there any way to list upcoming live streams?
There's a column `start_sell_in` in `ppvlive_schedule` which seems to not have effect to anything. 
How can I include the future live streams into the list of live events?

**Screenshots**
![image](https://user-images.githubusercontent.com/1679357/104345375-f136d780-5506-11eb-9198-9122477e1f5b.png)
![image](https://user-images.githubusercontent.com/1679357/104345770-61ddf400-5507-11eb-8397-b5a5f854aacb.png)

**Comment by DanielnetoDotCom** [comment]
Hi

we display notifications only for live streams. 

but you can publish your live link manually (on Facebook for example) then people will be directed to your PPV purchase page
