### ISSUE TITLE
project SECURITY and Chat2

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4345]
Hi hi. I bought project SECURITY and installed it on my youphptube server. I added 

include_once "security/config.php";
include_once "security/project-security.php"; 

to th configuration.php files and it is working great. I enabled bad words and it censors words in comments.

Hoever in Chat2 it does not work and file in Chat2 folder are encrypted. 

Where can I add these lines so that Chat2 comments also gets scanned?

Regards

**Comment by DanielnetoDotCom** [comment]
what is "project SECURITY"??

**Comment by JoshWho** [comment]
Project Security is a Web Application Firewall. https://codecanyon.net/item/project-security-website-security-antivirus-firewall/15487703

My suggestion @DanielnetoDotCom is to make a spot somewhere for a include file for the Chat2 that can be injected into the plugin. 

That way he could just add his include lines without it changing the main code.

**Comment by unconservo** [comment]
I also saw if i add the includes in the sreamer configuration then the encoder does not pick up the streamer site. Whete can i add those on main site that wont affect the connection between streamer and encoder?

Regards

**Comment by unconservo** [comment]
https://codecanyon.net/item/project-security-website-security-antivirus-firewall/15487703

**Comment by JoshWho** [comment]
Im kinda curious to know if you could include it by .htaccess file maybe?

**Comment by unconservo** [comment]
Yes that correct.

**Comment by JoshWho** [comment]
Add a line to your site's root .htaccess file..

`php_value auto_prepend_file "/full/real/server/path/to/WAFEXAMPLE.php"`

           ..replacing the path with the full, real path to project-security.php

Let me know if this woks for ya

**Comment by unconservo** [comment]
Thanx. It does the same. Comments under videos get censored. But not Chat2 and it also does not pick up streamer site from encoder :)

**Comment by JoshWho** [comment]
Put the .htaccess file also in the directory that you have your encoder.

Just copy and paste it in all the directories you need for the WAF to work.

**Comment by unconservo** [comment]
Ok. Thanx. Will try that and revert back to you :)

**Comment by unconservo** [comment]
Hi.I tried the .htaccess file in streamer and encoder site but the encoder still does not see streamer site if i add that
