### ISSUE TITLE
Just realized Icons for Live Stream Watchers is wrong. Eyeball and the People Icon  

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4346]
Now I see why people r asking me why their live watch viewers number never goes down.

The Icons are backwards.    The Eyeball icon suppose to be for currently watching.

Any way You can put the Eyeball in the blue Background for the current live viewer count. Really do not need a total count that just confuses people.

![download](https://user-images.githubusercontent.com/39392449/104386018-e0cc3000-54f9-11eb-96f3-f4aaec2e0de1.png)

**Comment by tonuzo** [comment]
It would be nice if you could choose to disable total count.

**Comment by DanielnetoDotCom** [comment]
@tonuzo I will add this option on LiveUsers ver 2.1

**Comment by JoshWho** [comment]
Where did u add the disable total count feature at? 

I see the Eyeball now in the correct place. Thank you @DanielnetoDotCom

**Comment by akhilleusuggo** [comment]
@JoshWho On the live-users plugin

**Comment by JoshWho** [comment]
What is the option called?

**Comment by DanielnetoDotCom** [comment]
I just released the new LiveUsers plugin

you must update it to version 2.1 and then check the option **doNotDisplayTotal**

**Comment by JoshWho** [comment]
I just updated and I found it. Thank you @DanielnetoDotCom  Works great and looks good.
