### ISSUE TITLE
File plugin/Live/droplive.json.php missing

### ISSUE THREAD

**Issue by esurov** [WWBN/AVideo#4347]
**Describe the bug**
It seems Live plugin is missing a file /plugin/Live/droplive.json.php
When I go online with Meet plugin it fails and I see 404 in web inspector.

**To Reproduce**
1. Go to Meet
2. Click on New Meet
3. Click Go Live button (planet icon in bottom)
4. See error:  GET https://privy.live/plugin/Live/droplive.json.php?live_transmition_id=1&live_servers_id=2 404 jquery-3.5.1.min.js:2
5. Meet stream is waiting for a minute and then says: Live Streaming Has Stopped.

**Screenshots**
![image](https://user-images.githubusercontent.com/1679357/104418711-069c1800-5580-11eb-9d74-e44d747311b6.png)

**Comment by DanielnetoDotCom** [comment]
Correct we do not have this file yet. the controls to record or stop are not working yet
