### ISSUE TITLE
Promote plugin

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4349]
Hi hi. How cannI as an administrator promote a video without adding funds to test the plugin?

Regards

**Comment by DanielnetoDotCom** [comment]
try to suggest them 
![image](https://user-images.githubusercontent.com/18009293/104457680-1ec46500-5589-11eb-8b65-c8685978413b.png)

**Comment by unconservo** [comment]
Is suggest same as promote?. Does a video go to suggest if a user pays to
promote his video?

Regards

**Comment by DanielnetoDotCom** [comment]
If you mean the PromoteVideos plugin

this plugin will create a row at the first position on your site with the paid promoted videos in a random position

**Comment by unconservo** [comment]
Ok. so how can admin add videos to the promoted?. atm admin must also pay to promote. and cant even test the plugin?

Regards

**Comment by DanielnetoDotCom** [comment]
Correct, Admin also must pay. But admin can change/edit the wallet balance

![chrome-capture (2)](https://user-images.githubusercontent.com/18009293/104816270-d8753d00-57f8-11eb-91ad-fbc2a371c05e.gif)

![chrome-capture (3)](https://user-images.githubusercontent.com/18009293/104816271-dc08c400-57f8-11eb-969c-ce0c24974d45.gif)

**Comment by unconservo** [comment]
Ahhh. Cool. Thank you
