### ISSUE TITLE
Username and Name

### ISSUE THREAD

**Issue by Donnerstein** [WWBN/AVideo#4350]
Isn't that a mistake?
The username is also displayed as the name under the videos.

![image](https://user-images.githubusercontent.com/52116237/104450837-052f1780-55a1-11eb-9f22-495c0e98a229.png)

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/104458797-96df5a80-558a-11eb-9cc2-00c5abd783ea.png)

**Comment by Donnerstein** [comment]
yeah ok, i thought that was related to the login.
Thanks.
