### ISSUE TITLE
Live Stream Live Offline Icon goes on and off through out the stream.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4351]
This has been a issue for a long time and I have no clue what or why it happens, but the Icon on live screams that shows when you go live Bright Green just randomly shows offline then goes back to online again over and over through the whole stream no matter how long it is.

![f0d22d44-7e1e-4057-8f8a-d51ade88845d](https://user-images.githubusercontent.com/39392449/104454670-d480bb00-556b-11eb-84c4-9ad61b11ff1b.png)

**Comment by morbificagent** [comment]
Same here... searching for a solution...
