### ISSUE TITLE
The site is very slow 

### ISSUE THREAD

**Issue by lahaj** [WWBN/AVideo#4352]
Hi
The site is very slow and the videos are slow and choppy
I am subscribed to 2 servers. The old one is fast and working well, but the other server is very slow. Please help
mrvod.net
![1001](https://user-images.githubusercontent.com/71000399/104454807-d5dbd300-55bf-11eb-8e03-8c74ef721371.jpg)

**Comment by DanielnetoDotCom** [comment]
I tested your server and some videos on your site and seems fine on my side

maybe was your internet connection?

also, make sure you use the encoder to submit videos. maybe your videos are not optimized for web

**Comment by lahaj** [comment]
Thank you, sir, for responding and very sorry for the delay
Sir, I have a server which is very fast and there are no problems with it. I have subscribed to you for several months, which is ooogel.com But this server mrvod.net 
![789](https://user-images.githubusercontent.com/71000399/104514627-fed58580-560a-11eb-9b05-4e3fb0963bd8.jpg)
 is really slow and I have no problem connecting to the Internet and the Internet connection is very fast

**Comment by DanielnetoDotCom** [comment]
But the thing is your connection between the server and your location.

but also may not be that. there is a specific page that is slow? or it is slow on every page?

there is some specific action you do before you notice the slowness problem?

**Comment by lahaj** [comment]
Sir, this site is indeed  mrvod.net very slow and I cannot upload videos on it because of the slow, even though I have another site subscribed to it and I took it from you ooogel.com but it is very good and from yesterday I tried more than one computer, but the problem is still there. Please solve this the problem

**Comment by DanielnetoDotCom** [comment]
Hi, I got the site, but the problem is to upload or watch or navigate?

On my side, I am navigating into your site with no problem. if you help me reproduce the slow process I may be able to help you

**Comment by akhilleusuggo** [comment]
@lahaj You're from dubai ( from the IP you linked ) , and your server is at France . It is expected that it should lag for you .
It's like if someone from Europe buy a VPS at USA and complain that the site is slow . ( Ofc it's gonna be slow ).

You should download a file from your server to test your internet speed .
Your internet speed of 300mb is not representative , you're testing it to your own country . You need to see a test to your server , that is thousands of kilometers ahead .

I tested your site , and works really fast for me .

**Comment by lahaj** [comment]
Sir, the technician visited me from Etisalat and checked the internet at my house
And everything is perfect
I would like to show you the site ooogel.com
It works perfectly and this server I took from you and is very excellent and the videos are fast
I have never complained about this server
But server  mrvod.net
I swear the videos are very, very, very slow
And the servers I took from you. Why is the server that I took before working so well?
Why is the server that I temporarily taken so slow, and I have not yet benefited from it?
please help

**Comment by DanielnetoDotCom** [comment]
Hi, 

the server's hardware and infrastructure are the same, so I only can assume is the connection.

the only difference I see is ooogel.com is behind Cloudflare proxy and mrvod.net is not

It is 7:12 PM here now, I will change it as soon as I can and I will notify you here so you can test.

**Comment by lahaj** [comment]
Thank you very much, sir, and I will wait for you because I notice even the site does not work. I repeat my heartfelt thanks to you

**Comment by DanielnetoDotCom** [comment]
now it is behind Cloudflare, not sure if it will make any difference for you.

on my side, Cloudflare makes no difference.

but I notice you are not sending your videos using the encoder. I think you will gain some performance if your videos are processed by the encoder instead just a direct upload

**Comment by lahaj** [comment]
Thank you very much. Now, much better. The videos are working well. Thank you very much

**Comment by DanielnetoDotCom** [comment]
Humm, looks like Cloudflare makes a good difference in your location. Good to know.

**Comment by lahaj** [comment]
Yes, a big difference has happened, and now the site has become faster than the speed of the missile. I thank you very much and give you seven stars for this interest and solving the problem. Allow me to raise my hat to you, out of respect for you.
I repeat my thanks to you
Sorry, I just have a very simple question
How can I activate the download option because I have updated the script to the latest version and the download option has become disabled
![donlwad](https://user-images.githubusercontent.com/71000399/104693988-f58c0c00-5723-11eb-930a-0f5d3a6edbf1.jpg)

**Comment by lahaj** [comment]
Excuse me, I came back with a reason
This is another mistake, I updated the script to the latest version 10.1, and this happened on the two sites, not one site as you can see in the pictures
I went to give the 777 permit, but it refused

![error](https://user-images.githubusercontent.com/71000399/104696409-ab0c8e80-5727-11eb-8fde-db9fe4d0c247.jpg)

![error2](https://user-images.githubusercontent.com/71000399/104696426-b19b0600-5727-11eb-80f7-4365bce93155.jpg)

**Comment by DanielnetoDotCom** [comment]
> Excuse me, I came back with a reason
> This is another mistake, I updated the script to the latest version 10.1, and this happened on the two sites, not one site as you can see in the pictures
> I went to give the 777 permit, but it refused
> 
> ![error](https://user-images.githubusercontent.com/71000399/104696409-ab0c8e80-5727-11eb-8fde-db9fe4d0c247.jpg)
> 
> ![error2](https://user-images.githubusercontent.com/71000399/104696426-b19b0600-5727-11eb-80f7-4365bce93155.jpg)

I did it for you

**Comment by DanielnetoDotCom** [comment]
> Yes, a big difference has happened, and now the site has become faster than the speed of the missile. I thank you very much and give you seven stars for this interest and solving the problem. Allow me to raise my hat to you, out of respect for you.
> I repeat my thanks to you
> Sorry, I just have a very simple question
> How can I activate the download option because I have updated the script to the latest version and the download option has become disabled
> ![donlwad](https://user-images.githubusercontent.com/71000399/104693988-f58c0c00-5723-11eb-930a-0f5d3a6edbf1.jpg)

You must click on the button and check what is wrong.

**Comment by lahaj** [comment]
Hello, regarding the download, the problem has been solved, because in the options there is an activation of the download, and I did it
But the problem is about what I told you, as shown in the pictures, and I tried very hard, but I did not succeed, and this thing happened after I updated the site to the new update which is 10.1, and this problem occurred in two sites as you can see in the picture, and I was given permission 777 but it did not work

![error2](https://user-images.githubusercontent.com/71000399/104745547-a9fb5180-5767-11eb-9ecf-4585a5631cbf.jpg)

![error](https://user-images.githubusercontent.com/71000399/104745589-b1baf600-5767-11eb-8d01-2c5a50f2489b.jpg)

**Comment by lahaj** [comment]
Hello, regarding the download, the problem has been solved, because in the options there is an activation of the download, and I did it
Yes, a site mrvod.net the problem has been solved, but a site ooogel.com the problem is still there, as after updating to version 10.1, this thing happened and the site is still ooogel.com the problem exists

![error3 jpg](https://user-images.githubusercontent.com/71000399/104747228-b5e81300-5769-11eb-94db-3e49a13baa28.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, I missed the oogel fix, please try again now.

**Comment by lahaj** [comment]
Thank you very much, sir. Yes, now everything is excellent. I am grateful to you for this interest. Greetings and respect

**Comment by lahaj** [comment]
Hello, I'm so sorry for inconveniencing sir
But I cannot see the changes that I make to the site, please see the pictures
When I change the settings and then save them, the settings that I have saved will return as before
Do not save, I do not know why there are many mistakes in this site ...... only, but a site .... very excellent and there are no mistakes in it since I subscribed

![eroor33](https://user-images.githubusercontent.com/71000399/104820197-b3121e80-584c-11eb-8b01-1b5d50ce2fec.png)

![error34](https://user-images.githubusercontent.com/71000399/104820208-c45b2b00-584c-11eb-9d45-e325985d0dbf.png)

**Comment by lahaj** [comment]
Hi
Dear Sir, I tried to upload a video several times, but it fails and previously it did not fail, and this happened after the new update 10.1 in two sites, not one site ...... and one site ..... I tried to search in the settings in order to solve the problem of uploading the video I chose Option to hide this login page in the site ..... Previously, I had no problem with the previous update, and if I had known I would not have updated the site to the new update
Please help me

![upload](https://user-images.githubusercontent.com/71000399/104840173-295f6100-58df-11eb-97ef-e3c35cbe8001.jpg)

![login](https://user-images.githubusercontent.com/71000399/104840179-311f0580-58df-11eb-8346-a4c930c843f5.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi

I can see 2 new issues here, please open one new issue for each problem.
