### ISSUE TITLE
Going Live on the Android or IOS APP

### ISSUE THREAD

**Issue by rielcomms** [WWBN/AVideo#4353]
Does anyone know how to go live on the Apps?
When I try this, there is no option to go live even after logon
On the Android when I touch the Camera it turns to On Air then Save Info and Start Meet show and nothing else.
The IOS App does not show any option to Go Live!!!

**Comment by DanielnetoDotCom** [comment]
On the site, the user you are trying to use has stream rights?

also, check if it has meet rights

![image](https://user-images.githubusercontent.com/18009293/104630686-d33db400-5679-11eb-8020-a1f4ac7648ec.png)

**Comment by rielcomms** [comment]
Even after setting the options circled, I still cant go live on Android or IOS and on any account on the server at all.

**Comment by DanielnetoDotCom** [comment]
what version of AVideo are you running?
can you go live on demo site?
is your live working fine when you use OBS to connect?

**Comment by rielcomms** [comment]
Running Version 10.1
It works from OBS but does not work on Android or IOS apps
Not sure what the issue is

Thanks

**Comment by DanielnetoDotCom** [comment]
Are you using the meet right?
is your meet running well? can you go live from the meet using the browser?
