### ISSUE TITLE
Video Description

### ISSUE THREAD

**Issue by rielcomms** [WWBN/AVideo#4354]
After upload, the video description does not get to be saved.
When I try to do this manually, it tells me it is not saved unless I reduce it to about a few lines.
Does it have a limit and if yes, what is the limit?

**Comment by akhilleusuggo** [comment]
I believe it's something related to the database .

**Comment by DanielnetoDotCom** [comment]
@rielcomms check the logs for some clue

**Comment by DanielnetoDotCom** [comment]
Looks like you are missing some database update

make sure you have all your plugins up to date

**Comment by rielcomms** [comment]
I have updated all the plugins but still no luck. Also if I upload a video in High Definition, SD and LD, I will need to add the video description on each individually.

**Comment by DanielnetoDotCom** [comment]
But is your LiveLinks up to date?

![image](https://user-images.githubusercontent.com/18009293/104917587-5e68c380-5972-11eb-9bd5-f6245da5d8c9.png)
