### ISSUE TITLE
Switch video

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4355]
Switch video not working when upgrading from MP4 to HLS , or from HLS to MP4 .
In my case test , from mp4 (low,SD,HD) , can't switch with newer updated video version with DynamicHLS .

Not working .

**Comment by DanielnetoDotCom** [comment]
Hi

Is not clear for me what is not working and what you mean with "when upgrading from MP4 to HLS , or from HLS to MP4"

this is not working for any format? can you reproduce on demo so I can see?

**Comment by akhilleusuggo** [comment]
I mean , I re-uploaded some old videos , and wanted them to be on HLS
After encoding the video into HLS , when I switch from old MP4 to new HLS , does not work .

Clear cache + updated disk , nothing works .

PS : I can try on demo , only if you allow upload some clips ( 10-15s clip enough for me )

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Ok , I was able to reproduce it on demo site ( last 2 uploaded videos ) .

Looks like the issue is happening only when you have videos hosted on different Storage Severs

You can check that they're not working after I switched them . ( if you switch back , they will work )

**Comment by DanielnetoDotCom** [comment]
Yes, correct. I guess the swap tool is not updating the sites ID, I will make an update to it

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by akhilleusuggo** [comment]
WORKS ! Thanks for the fix . 
Now finally I can update the old videos.
