### ISSUE TITLE
Registration email

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4356]
**Describe the question**
Hi, i have a new user on my site but the regitration email are not coming to the emailaccount.
The site has email enabled and the test is ok.
So the user cannot confirm there account.
I have checket my mailserver an the email is not on the server. 

Are there other configurations ?

**Comment by DanielnetoDotCom** [comment]
check the spam folder

also check for yourself. email delivery is nothing we can help you.

if we send the email and it never arrived you have to check with your email provider

**Comment by 01123581321345589144233** [comment]
there is nothing in the spam folder, the email are not send from the system.
Must i buy the plugin notifikation ?

**Comment by DanielnetoDotCom** [comment]
check your log file.

what exactly email are you expecting to receive?

**Comment by 01123581321345589144233** [comment]
when a new user are register on my site, the email confimmail for the new user.
