### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by DemonRem** [WWBN/AVideo#4357]
**Describe the bug**

i have a php error said "Non-static method Video::getBlockedUsersIdsArray() should not be called statically in F:\laragon\www\objects\video.php on line 1455"

**Error Logs**
Error log attached

[avideo.log](https://github.com/WWBN/AVideo/files/5814151/avideo.log)

**Screenshots**

![!!!!](https://user-images.githubusercontent.com/29927382/104586259-eba7d180-566d-11eb-9976-4fd6474d4412.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 8.9.1

**Comment by akhilleusuggo** [comment]
Actually there's no support for Windows 
Only linux Ubuntu . Anything else you will need to google it and find a way to make it work .
