### ISSUE TITLE
Playlist/Program plugin not working properly

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4362]
I've noticed some error messages from google search , about the program/playlist plugin .
If you having this plugin enabled , bots/crawlers can generate randomly content . ( also is super lagy , because the server start looping )

For example , this program doesn't exist , but still works . https://demo.avideo.com/playlist/316/12
You can replace any number by any other one , example ; https://demo.avideo.com/playlist/999/999 and still works ... 

It shouldn't

**Comment by DanielnetoDotCom** [comment]
now it will return a 404 page

**Comment by akhilleusuggo** [comment]
thanks
