### ISSUE TITLE
How do I upgrade to 10.1?

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#4365]
Clicking all the links, can't figure it out.
Thanks.
![image](https://user-images.githubusercontent.com/66537018/104670682-537c0d80-56aa-11eb-9f98-878bc6147d51.png)

**Comment by eZweblogic** [comment]
Login to terminal (SSH)
Paste this cd /var/www/html/AVideo/ && sudo git pull
and then press Enter

Then go to your admin panel to update

This is the standard way but when I tried it few minutes ago it didn't work and kept on taking me to the same update page. Try it it may work for you.

**Comment by fakeologist** [comment]
I don't have an Avideo directory

**Comment by eZweblogic** [comment]
Use this instead
cd /var/www/html/YouPHPTube/ && sudo git pull

You have an older installation

**Comment by fakeologist** [comment]
Did that - still no mas. Daniel can you fix please?

**Comment by DanielnetoDotCom** [comment]
Please confirm if you are up to date now

**Comment by fakeologist** [comment]
It's fine. What needed to be done?

**Comment by DanielnetoDotCom** [comment]
You are all set
