### ISSUE TITLE
Rss feed has non ssl link causing mix content when using in ssl enabled sites

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4369]
the mp4 link is http and not https

This is causing mix content issues when using the rss feed on other websites.

![49a359d2-98e0-4848-b08f-41f268cde3cc](https://user-images.githubusercontent.com/39392449/104743008-cc15b500-5710-11eb-955a-cfc22121c7bf.png)

**Comment by DanielnetoDotCom** [comment]
where does the static.joshwho... link comes from?

**Comment by JoshWho** [comment]
the cloud storage it is the cdn link

**Comment by DanielnetoDotCom** [comment]
but where does this link come from? some plugin configuration?

check if the cdn link contains the https://...

**Comment by DanielnetoDotCom** [comment]
ok I found the bug, sorry about that

**Comment by JoshWho** [comment]
Looks great now. Thank you
