### ISSUE TITLE
Length of time to stream.

### ISSUE THREAD

**Issue by sstech2** [WWBN/AVideo#4370]
How do I make the length of the stream longer than 1:12:22. It stops the stream just after an hour?

**Comment by DanielnetoDotCom** [comment]
what do you mean?

can you please provide more details about what you are doing?

**Comment by akhilleusuggo** [comment]
@sstech2 there's no real limit . Make sure you have enough space on the server if you're recording .

**Comment by sstech2** [comment]
We are live streaming from obs to the server, we had a 3 hour event, after the 1 hour 12 min mark, it started to created videos and they were all black I think it was 10 or so, and spent the night and into this morning rendering the videos which never completed.  There is plenty of space on the server and CPU and Ram was all normal.

**Comment by akhilleusuggo** [comment]
again , check the config file . here , 

```
recorder video{
    # record all manual; # Use this line if you want to use the controls
    record all;
    record_path /var/www/tmp;
    record_notify on;
    record_max_size 2048M; 
    #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
    record_suffix -%d-%b-%y-%T.flv;
}
```

If you're going to stream long stream , you may wanna increase to `20000M`;
Maybe more if you want . Once you hit 2048M ( the one you see by default ) , the video will be sent to the encoder .
