### ISSUE TITLE
Update plugin User Customize V1 to V3 Error

### ISSUE THREAD

**Issue by sstech2** [WWBN/AVideo#4371]
I am getting this error when I try to update the CustomizeUser plugin.
In the log it is giving this.

Plugin | setCurrentVersionByUuid | update plugins set pluginversion=3.0 where uuid=55a4fa56-8a30-48d4-a0fb-8aa6b3fuser3n
-- | -- | --

**Comment by DanielnetoDotCom** [comment]
I am not sure what exactly are you doing

please make sure you follow this.

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by sstech2** [comment]
I updated the server using the steps in the above post. this is under the admin, Miscellaneous , Plugins 
![image](https://user-images.githubusercontent.com/77501072/104759874-ca9eb980-571d-11eb-861b-b1d6936bffa7.png)
 Click on update, says Run Update Script, Click on that, screen goes blank hen reloads saying it needs to be updates still.

**Comment by DanielnetoDotCom** [comment]
clear the cache and check again, please

**Comment by sstech2** [comment]
No change, same issue. with different computer and different browser.

**Comment by DanielnetoDotCom** [comment]
please check your logs for errors.

**Comment by akhilleusuggo** [comment]
permissions issues most likely
