### ISSUE TITLE
Advance and rewind in browser app

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#4372]
Can you add advance rewind pause as an overlay in browser window as in app?

**Comment by DanielnetoDotCom** [comment]
can you please screenshot what you mean?

**Comment by fakeologist** [comment]
https://linksharing.samsungcloud.com/bArFmkNDlpA2

**Comment by DanielnetoDotCom** [comment]
Thanks, this is a lot clear to me. do you have the SeekButton plugin enabled?

Looks similar on demo site for me

![chrome-capture (6)](https://user-images.githubusercontent.com/18009293/104916803-4f354600-5971-11eb-93e1-6e371743c1f4.gif)

**Comment by fakeologist** [comment]
Still have the plugin active. Tried in two browsers as well.

**Comment by DanielnetoDotCom** [comment]
I can see it on your site

![image](https://user-images.githubusercontent.com/18009293/104920299-5743b480-5976-11eb-9bfd-756539dc620d.png)

Am I misundertandting you?

**Comment by fakeologist** [comment]
shows up in firefox (which I won't use), but chrome based browsers like Google's and Brave browser no show.

**Comment by DanielnetoDotCom** [comment]
The screenshot is from chrome.

maybe you have something blocking the script in your chrome
