### ISSUE TITLE
Where upload resolution setting? 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#4373]
Where can you limit the upload resolution to low? I can't this setting and latest update removed it.

**Comment by akhilleusuggo** [comment]
Select or remove what ever you see appropriate for your site ; Plugin ; CustomizeAdvanced
You must clear the cache and reload encoder page to see new options or removed options .

![image](https://user-images.githubusercontent.com/52116577/104782226-88f92780-578c-11eb-8c48-5191b28df44e.png)

**Comment by fakeologist** [comment]
Thanks.
