### ISSUE TITLE
To use separate encoders 1 for uploading and another just for restreaming and Live Programs

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4374]
I am using external encoders for my site but would like to use a built in encoder on my main server for restreaming and Program Live plays.

My main server is designed to handle gigabits of data while the external encoders only have 100mb uplink. I would love to be able to manually tell restream and other Live broadcasting tools to use my internal encoder instead of the same ones I use for uploading video.

**Comment by DanielnetoDotCom** [comment]
Definitely we will add this option in the future

**Comment by JoshWho** [comment]
That will be terrific.
