### ISSUE TITLE
YPTStorage not moving files to storage

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4375]
My plugin for some reason has stopped working and now I cannot move files anymore. I don't see any errors in logs nor does the browser complain on any. The process for selecting a file and choosing the storage location to move it seems to work just fine. I can see my storages listed on the videos page and I can select them, but just as far as it goes.

It was working just fine couple of day ago.
I have made the latests updates.

Plugin is also updated.
The folder has the correct permissions, user and group ids, basically besides the update I have mad to the site I haven't changed anything. I can access my storages also directly through their given domain names.

Just to clarify, I believe my site is the edge version of aVideo and I am managing a second aVideo site which has the stable version and also is updated and there the plugin works well.

Here some screen shots of my logs while trying to "Move Storage" a video file.

![Screen Shot 5781-05-03 at 0 58 23](https://user-images.githubusercontent.com/58882903/104810903-8801dd80-5800-11eb-802c-721aa84c6363.png)
![Screen Shot 5781-05-03 at 0 53 51](https://user-images.githubusercontent.com/58882903/104810904-8afcce00-5800-11eb-9166-8a31e38100db.png)
![Screen Shot 5781-05-03 at 0 44 52](https://user-images.githubusercontent.com/58882903/104810905-8b956480-5800-11eb-8e71-b47a560e4620.jpg)
![Screen Shot 5781-05-03 at 0 26 18](https://user-images.githubusercontent.com/58882903/104810906-8c2dfb00-5800-11eb-8eec-00ca504528e1.jpg)

**Comment by DanielnetoDotCom** [comment]
can you please also make sure your storage is up to date?

must be something in your avideo.log file on the streamer, can you please check?

also, check your storage apache error log

**Comment by guymass** [comment]
Plugin is V3
I don't see any transfers or file locks, it seems like its trying to start but than it hangs somehwere.


![Screen Shot 5781-05-04 at 0 00 48](https://user-images.githubusercontent.com/58882903/104824235-b14e5800-5858-11eb-8671-c33319c917ac.jpg)

![Screen Shot 5781-05-04 at 0 10 26](https://user-images.githubusercontent.com/58882903/104824226-adbad100-5858-11eb-9ed8-89043c659c56.jpg)

**Comment by DanielnetoDotCom** [comment]
Please provide the log at the time the transfer error happens.

the provided log has nothing related to the transfer

**Comment by guymass** [comment]
Those are the logs at the time of the transfer.

**Comment by DanielnetoDotCom** [comment]
so you need to provide more from your log

**Comment by guymass** [comment]
Sorry this issue has been resolved.
