### ISSUE TITLE
hls weird bug

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4376]
![image](https://user-images.githubusercontent.com/52116577/104810917-9f40cb00-5800-11eb-80b3-01ee42fcf34c.png)

I'm getting this video playback on some videos .

The m3u8 is pointing to ; `/plugin/Live/view/loopBGHLS/enc_xxxxx35xxx5d.key?token=bxxxxxxxxxxxxxxxxxxxxxVp4aGxxxxxxHajdtMw==`

`plugin/Live/view/loopBGHLS/res720/index0.ts`

**Comment by DanielnetoDotCom** [comment]
this is not a bug, this means the file was not found

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Actually a cache problem . After clearing the cache , the video started to play . 
Maybe auto clear the selected cache video to solve it .

Thanks for the info , never seen this before .
