### ISSUE TITLE
script in a script

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4377]
HI. I want to install a micro bog script inside AVideo like www.aa.com/micro/
It installs but as soon as it gets to where I need to access the admin page to create a admin user the AVideo script comes up and says it cannot find the page /install/index?page_in=create_admin

Is there rewrites or something i have to add to get this to work with AVideo?

Regards

**Comment by DanielnetoDotCom** [comment]
are you using **git clone** to copy the project?

if you are uploading using FTP you may be missing some files

**Comment by unconservo** [comment]
Hi. Its s script i bought and it syas i must copy it to a folder and run
install. I have installed it on a test domain and it works.

**Comment by DanielnetoDotCom** [comment]
I cannot support you on how to install a third-party script.

**Comment by unconservo** [comment]
Hi. Its not the script thats the problem. Its avideo's rewrites that stops
the script from completing.

**Comment by DanielnetoDotCom** [comment]
you should install your script in another directory, NOT inside AVideo dir

**Comment by unconservo** [comment]
HI. It is installed inside its own folder but inside AVideo. I do not want
to add mote virtual directories or is this the only way?

Regards
