### ISSUE TITLE
Can The Restream Feature Be Spun Off Into Its Own Separate App Running From another Server Similar to Encoder

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4379]
Hi,
I am asking if it is possible for the Restream feature to be able to operate on a separate server similar to the way that Encoder does? 
Seems to me that this would make a good feature request ...

**Comment by DanielnetoDotCom** [comment]
Looks like this request https://github.com/WWBN/AVideo/issues/4374
