### ISSUE TITLE
Question About Restream Feature

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4380]
I would like to know how I can figure out how much resources get used when using the restream feature.

I have not been using it to date because I use a service called Restream.io but that costs $19 a month. I would like to use the restream feature built in to AVideo but I fear that if you restream to multiple sources then the system won't be able to keep up.

As it stands now, I can only have about 5-10 people watching my AVideo stream and have to send everyone else to Youtube or Facebook because my server just simply can not handle more.

Is it possible to use ONLY the restream feature without the livestream feature?

**Comment by DanielnetoDotCom** [comment]
you can make your live unlisted, so it will restream it without showing it to the public

![image](https://user-images.githubusercontent.com/18009293/104816420-cc3daf80-57f9-11eb-98b2-d83b4200e293.png)

**Comment by bbyrdhouse** [comment]
How many sources could I potentially stream to?

**Comment by DanielnetoDotCom** [comment]
There is no limit, all depends on the hardware
