### ISSUE TITLE
Update I think has stopped showing video formats?

### ISSUE THREAD

**Issue by mdent123** [WWBN/AVideo#4383]
The Video formats that show to the right of the video seems to have disapeared 
![videoformats](https://user-images.githubusercontent.com/51091120/104820725-bac2ca80-582e-11eb-92a2-8bb7ee854574.JPG)

**Comment by DanielnetoDotCom** [comment]
the video on the screenshot is not even completed or it fails.

also, you should click on the button and read what it say

**Comment by mdent123** [comment]
All the videos are the same , and it had completed, 
![videoformats](https://user-images.githubusercontent.com/51091120/104970582-e89d4000-59e3-11eb-93d0-a45b0718e614.JPG)

**Comment by akhilleusuggo** [comment]
Go to site configuration , and enable this option ;

![image](https://user-images.githubusercontent.com/52116577/104971072-45a1f180-59f6-11eb-9c2c-023cd6d1f66f.png)

**Comment by mdent123** [comment]
FIXED thanks
