### ISSUE TITLE
I have built my own jitsi server, where do I get the info required in the Meet plugin ?

### ISSUE THREAD

**Issue by mdent123** [WWBN/AVideo#4384]
![jitsiCapture](https://user-images.githubusercontent.com/51091120/104820755-007f9300-582f-11eb-9be8-e612e64ed265.JPG)

**Comment by DanielnetoDotCom** [comment]
It is on the meet configuration. 

try to use Jitsi docker it will be clear for you.

**Comment by JoshWho** [comment]
How do you add other its servers to the config? Im curious about this myself. I also have a Jitsi server running as well on my main server.

**Comment by DanielnetoDotCom** [comment]
I only have tested with [Jitsi (Docker)](https://github.com/jitsi/docker-jitsi-meet)

on Jitsi (Docker) you have parameters with the same name you have on the plugins
