### ISSUE TITLE
LoginLDAP Plugin doesn't follow link when logged in

### ISSUE THREAD

**Issue by JSY-Ben** [WWBN/AVideo#4385]
Hi! Thanks again as usual for the great software, really appreciate it.

We use the LoginLDAP Plugin and disable the native sign in for our AVideo site. We noticed that a while back you added the feature that if you sent a link to the video and the user needed to login, it would then redirect the user to the video after the login was complete. Unfortunately this only seems to work for native sign in and not for the LoginLDAP plugin. If you have gallery enabled, it sends you straight to the homepage. Any chance this could be fixed?

Many thanks

**Comment by DanielnetoDotCom** [comment]
I am not sure, but it supposes to work with LDAP also.

I cannot see any reason for that to not work

**Comment by JSY-Ben** [comment]
I can recreate the issue with a link shared from the 'Share' section of a video.

If i reenable the native sign-in, enabled 'usermustbeloggedin'. open the shared video link, it will ask me to login, i do so and it then goes to the video. If I do the same using the LoginLDAP login form, it just ignores the link and goes to the homepage.

**Comment by DanielnetoDotCom** [comment]
I see

I just submit the LoginLdap v2.0 that may do the expected

**Comment by JSY-Ben** [comment]
Working perfectly now, thank you for the quick fix :)
