### ISSUE TITLE
New platform installed. NGINX stopped and won't start again.

### ISSUE THREAD

**Issue by helpgizmo** [WWBN/AVideo#4387]
**Describe the question**
I have a fresh install of the video platform. Everything worked for a couple of days and then the NGINX stopped. I tried to start it again and it fails. Any suggestions?

**Screenshots**
![nginx-failed](https://user-images.githubusercontent.com/66783135/104844930-cd75e780-58a0-11eb-95ef-0b39a385fa7c.png)

**Comment by antuk21** [comment]
Try this  sudo /usr/local/nginx/sbin/nginx -s stop    to stop nginx then this to run again 
sudo /usr/local/nginx/sbin/nginx

**Comment by helpgizmo** [comment]
I tried your suggestion.

> Try this sudo /usr/local/nginx/sbin/nginx -s stop to stop nginx then this to run again
> sudo /usr/local/nginx/sbin/nginx

It did not start, but I did get a 0.0.0.0 binding message.

![nginx-UnableToBind](https://user-images.githubusercontent.com/66783135/104846124-02853880-58a7-11eb-96f7-da0de6b3c825.png)

**Comment by antuk21** [comment]
Means its running here is  mine   its same   
![sssddss](https://user-images.githubusercontent.com/74247098/104846460-8e608a00-58d2-11eb-9b15-2462189aa6d6.png)

**Comment by antuk21** [comment]
All you need to do is reset your stream key copy and paste new one should let you go live

**Comment by antuk21** [comment]
If you have issue still try running this may need a update    cd /var/www/html/AVideo/ && sudo git pull
if your directory is youphptube use this:  cd /var/www/html/YouPHPTube/ && sudo git pull

**Comment by helpgizmo** [comment]
It seems the stream is connecting, but when I go to the website it now says Connection Refused.

![nginx-loaded](https://user-images.githubusercontent.com/66783135/104846683-bedffe00-58a9-11eb-8bbb-66e3d018ea7e.png)
![err_connection_refused](https://user-images.githubusercontent.com/66783135/104846744-13837900-58aa-11eb-9cb5-f259b012cf35.png)

**Comment by antuk21** [comment]
Make sure your server ip has not changed  on your gateway  do ifconfig see if ip matches where you have open the ports

**Comment by akhilleusuggo** [comment]
Without sharing your config file , we can't really say what's going on .
Also your logs are confusing . Error should say that IP 1935 ( rtmp ) and 8080 are in use . But on your case sometimes also 8443 shows this error .

Share your config file . Also check the firewall and ports . `sudo ufw status` ( firewall ONLY if enabled ) ; `sudo netstat -tunlp` ( ports in use )
