### ISSUE TITLE
Can't Update The Avideo

### ISSUE THREAD

**Issue by jamesrhenry** [WWBN/AVideo#4388]
I've tried both Putty and Filezilla, and neither are allowing me to update AVideo to 10.1. Thanks!

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by jamesrhenry** [comment]
I tried both options, and both seemed to be blocked. I couldn't upload the files with Filezilla, kept telling me that upload failed. And Putty just kept giving me issues, saying there was a directory there, but every time I tried git pull, would tell me not git.

**Comment by jamesrhenry** [comment]
Looks like I almost had it with another app called JuiceSSH.

![Screenshot_20210118-195852](https://user-images.githubusercontent.com/5248534/104986386-ca294b80-59c7-11eb-8d4f-8ad1709c66cd.png)
![Screenshot_20210118-192553](https://user-images.githubusercontent.com/5248534/104986391-cb5a7880-59c7-11eb-884c-204750a8e701.png)

**Comment by jamesrhenry** [comment]
Finally did it. I did the same on Putty but it wasn't working. Finally did the exact same thing I was doing, but on JuiceSSH, and now it's updated. Thank you!

**Comment by DanielnetoDotCom** [comment]
You must make **sudo git pull**

the SSH client should not make any difference

**Comment by jamesrhenry** [comment]
That could've been what I wasn't doing. Putty didn't allow me to copy and paste but JuiceSSH did, so I copied everything and just changed the YouPHPTibe to AVideo and it worked. Thanks!
