### ISSUE TITLE
cache plugin

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4389]
Hi again, i have stored my videos an a shared storage, but i can see the cache folder is also stored under videos.
I have try to change the cache path to a lokal cache mount like this /videos/cache, but its not changed when i deaktivate and aktivate the plugin.

When the cache its also on the shared storage ist not so optimal so i think the best is that is on the system under a ssd or nvme drive.

**Comment by akhilleusuggo** [comment]
Where is your configuration file stored ?
Same folder where your config file is stored you'll have the cache directory by default .

In case you wanna change that , you can do it from plugin . If is not working , then from the config file itself .

This is the default location , but you can change it ; `$global['logfile'] = '/var/www/html/AVideo/videos/avideo.log';`
