### ISSUE TITLE
upload- login

### ISSUE THREAD

**Issue by lahaj** [WWBN/AVideo#4392]
Hi
Dear Sir, I tried to upload a video several times, but it fails and previously it did not fail, and this happened after the new update 10.1 in two sites, not one site ooogel.com and one site mrvod.net I tried to search in the settings in order to solve the problem of uploading the video I chose Option to hide this login page in the site mrvod.net Previously, I had no problem with the previous update, and if I had known I would not have updated the site to the new update
Please help me

![upload](https://user-images.githubusercontent.com/71000399/104935613-e24b9b80-59c4-11eb-8fea-10372411a249.jpg)

![login](https://user-images.githubusercontent.com/71000399/104935659-ee375d80-59c4-11eb-9206-3889bf020d9c.jpg)

**Comment by DanielnetoDotCom** [comment]
I will need to reset your plugins, looks like you misconfigured the customizeUser.

I will check them for you

**Comment by DanielnetoDotCom** [comment]
FYI, I just realize what is the problem with the upload.

you are using Cloudflare now. Cloudflare limits the max upload file size to 100 MB, so if you want to submit larger files you MUST use the encoder https://github.com/WWBN/AVideo/wiki/About-Video-Upload#know-problems **Direct uploads will not work**

you can login into your site https://mrvod.net/ now

You have those encoders

https://mrvod.net/Encoder/
https://ooogel.com/Encoder/

**Comment by lahaj** [comment]
Thank you very much for your help always, and this good thing I will never forget, thank you
I have a simple question, how do I upload the video via encoder without the video being multi-resolution with one accuracy only? How, sir

**Comment by DanielnetoDotCom** [comment]
Setup your Plugin like this

![image](https://user-images.githubusercontent.com/18009293/104954527-28920200-59a7-11eb-8a28-76eb68fd5b6e.png)

You will have only HD resolution

**Comment by lahaj** [comment]
Everything is excellent and I understand, but sir some options do not work for me as in the picture
All I save the options that I changed do not save will return as before

![1](https://user-images.githubusercontent.com/71000399/104955694-07033b80-59e4-11eb-9be3-69d11c13decd.png)

![2](https://user-images.githubusercontent.com/71000399/104955702-0bc7ef80-59e4-11eb-900b-7924b02e9900.png)

**Comment by DanielnetoDotCom** [comment]
Instead, use the admin panel please use the plugin menu.
![image](https://user-images.githubusercontent.com/18009293/104960955-17032700-59b4-11eb-9bc0-42cbdefa638c.png)

**Comment by lahaj** [comment]
aftarAnd after that?

**Comment by DanielnetoDotCom** [comment]
You will find the same options on customizeUser plugin 

![image](https://user-images.githubusercontent.com/18009293/104962557-6f87f380-59b7-11eb-9df4-14c9201f1b5d.png)

**Comment by lahaj** [comment]
Everything is fine, but after I uploaded the video via the video encoder, it does not work
You can check for yourself and this video link is uploaded by encoder

https://mrvod.net/video/23/grudge.match

**Comment by lahaj** [comment]
Hello sir, I solved the video problem that is not working Thank you very much for your help always
