### ISSUE TITLE
non autorized users can search on all videos hosted

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4394]
Any user is able to search under ''My Videos" for any video , as if the were admins .
The bug/bridge ( depends what they can do ) , is from the search .

To reproduce  : 

**Create a new user** ( no privileges required )
**Go to search** ( and look for some video title ) , like you would do in SQL injection 

![image](https://user-images.githubusercontent.com/52116577/104939387-073a1180-59b9-11eb-993f-cc45973c54c4.png)

**Videos will show up** , even that the user just registered and he's hosting nothing .

 I've confirmed that he can't edit videos or delete them . Permissions issues . But this should not happen .

**Comment by DanielnetoDotCom** [comment]
Can you please give me a search query sample?

I could not reproduce it here

**Comment by DanielnetoDotCom** [comment]
I created a user with no upload right and it could not even go to the mvideos page

**Comment by akhilleusuggo** [comment]
Yes but that's not what you do on production . Create a user with right to upload , go to My Videos , and search for a video that you're hosting with another account , could be the admin himself

**Comment by DanielnetoDotCom** [comment]
Hi, I guess I could find the bug, can you please confirm?

**Comment by akhilleusuggo** [comment]
Fixed , and now it's much more smooth the search , because doesn't have to filter the others ( I guess )
Thanks
