### ISSUE TITLE
network encoder

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4395]
i have installed a network encoder under domain.com/network.
The install was also done and i can acces thye page example.com/network so i can see the 2 encoders.
But when i go to upload example.com/upload then i have this one:

SELECT f.*, e.* FROM encoder_queue e LEFT JOIN formats f ON f.id = formats_id WHERE (status = 'encoding' OR status = 'downloading' OR status = 'queue' OR status = 'error') ORDER BY priority ASC, e.id ASC \nError : (1146) Table 'network.encoder_queue' doesn't exist

the login for the mysql table is correct

i have added a new encoder: the same
https://tube.011235813213455.dk/network/

**Comment by DanielnetoDotCom** [comment]
check if the database was created

**Comment by 01123581321345589144233** [comment]
it is createt

**Comment by DanielnetoDotCom** [comment]
You are missing something for sure, this message comes from MySQL

`Error : (1146) Table 'network.encoder_queue' doesn't exist`

it the network database (case sensitive) exists check your mysql user permission

**Comment by 01123581321345589144233** [comment]
yes the table encoder_queue is ther not

**Comment by 01123581321345589144233** [comment]
https://image.linuxhus.dk/01123581321345589144233/images/2b785193b1bf0aad15755d4c6f4c895b.png

**Comment by 01123581321345589144233** [comment]
the encoder_queue table is not in yourdatabase.sql

**Comment by DanielnetoDotCom** [comment]
encoder_queue is for the encoder, NOT for the network, I guess you are mixing the script.

**Comment by 01123581321345589144233** [comment]
ah ok sorry for this :-)
i try to understand how yopu system works, so now i am working with the network encoders.
I will setup more encoders.

**Comment by 01123581321345589144233** [comment]
ah ok so i can now see when i upload a video i can take another encoder, i have take my encoder and i upload and google says:

413. That’s an error.
Your client issued a request that was too large. That’s all we know.

**Comment by 01123581321345589144233** [comment]
also when i will upload a video, when i klick on the button start uplouad the video is not uploading
https://image.linuxhus.dk/01123581321345589144233/images/650e8c70b446537929fb247b189a7eb1.png

**Comment by 01123581321345589144233** [comment]
when i try to upload a video it will be forwadet to https://jquery-file-upload.appspot.com/
with error code:
413. That’s an error.
Your client issued a request that was too large. That’s all we know.

**Comment by DanielnetoDotCom** [comment]
check your encoder configuration.php, you should have a wrong URL variable in it.

**Comment by DanielnetoDotCom** [comment]
> when i try to upload a video it will be forwadet to https://jquery-file-upload.appspot.com/
> with error code:
> 413. That’s an error.
> Your client issued a request that was too large. That’s all we know.

You are probably using Cloudflare, please read this.
https://github.com/WWBN/AVideo/wiki/About-Video-Upload#cloudflare

**Comment by 01123581321345589144233** [comment]
encoder or network ?

**Comment by 01123581321345589144233** [comment]
i dont understand whats wrong,pleas can you help me

**Comment by 01123581321345589144233** [comment]
thats my $global['webSiteRootURL'] = 'http://tube.011235813213455.dk/';
for the encoder

**Comment by DanielnetoDotCom** [comment]
So does this work in your internal network??
http://tube.011235813213455.dk/

certanly it does not work outside your network

the webSiteRootURL MUST be a public URL and if your streamer is HTTPS your encoder also MUST be HTTPS

**Comment by 01123581321345589144233** [comment]
its a public url, you ca try this

**Comment by 01123581321345589144233** [comment]
you can register a account so you can try this

**Comment by DanielnetoDotCom** [comment]
Ok, but it is a URL to your streamer
and $global['webSiteRootURL'] MUST be your encoder URL

**Comment by DanielnetoDotCom** [comment]
It should be  `$global['webSiteRootURL'] = 'https://tube.011235813213455.dk/upload/';`

**Comment by 01123581321345589144233** [comment]
in the network config

**Comment by 01123581321345589144233** [comment]
ah ok, the upload must have /upload and the network /network

**Comment by 01123581321345589144233** [comment]
why filetyp is not allowed ?

**Comment by DanielnetoDotCom** [comment]
what filetype?

**Comment by 01123581321345589144233** [comment]
i can not upload a mp4 to the encoder

**Comment by 01123581321345589144233** [comment]
i have uploadet this video successfully for 3 days

**Comment by 01123581321345589144233** [comment]
there is nothing disabled in the CustomizeAdvanced plugin

**Comment by 01123581321345589144233** [comment]
how can i change this or whats wrong

**Comment by 01123581321345589144233** [comment]
please can any help me

**Comment by 01123581321345589144233** [comment]
you can have a login to my server so you can check the files.

**Comment by DanielnetoDotCom** [comment]
I am not sure exactly.

If you want you can hire me per hour and I can help you.

otherwise, you must provide a clear log file and we can try to help you from here

**Comment by 01123581321345589144233** [comment]
ok i have sen a email to billing@youphptube.com

**Comment by DanielnetoDotCom** [comment]
Got it, I have responded to you.
