### ISSUE TITLE
View count cheating on embed mode

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4397]
When a video is embedded on a site or somewhere else ( not on AVideo ) , the views are counted every page refresh .
This is an issue for sites with monetization/view enabled .

I took your video as example , as I'm writing this post , this video got 169 views ; When you gonna check it , you will see at the least +1000

https://demo.avideo.com/video/242/avideo1080hd

![image](https://user-images.githubusercontent.com/52116577/104972178-a1ba4500-59f9-11eb-848b-07af1d8f82d3.png)

**Comment by DanielnetoDotCom** [comment]
The problem is ....

we save cookies and sessions to avoid multiple views count.

on the external URL, we have the cross-domain CORS problem, and we cannot save cookies or sessions. 
I think will be a good idea to not count views from cross-domain embed contents

**Comment by akhilleusuggo** [comment]
Yes , I know this is an issue related cookies sessions .
Would be a good idea to add an option on plugin UserAdvanced , to enable or disable counter from external .

We could also add records by IP . Multiple sessions from same IP do not count ( until session restarts , at the least for non online users ) . This would at the least limit the refresh count fraud .
