### ISSUE TITLE
"download" button does not update.

### ISSUE THREAD

**Issue by mario-evangelista-silva** [WWBN/AVideo#4398]
In the video module the "download" button does not update, it is always **"download disabled"**, even if all the settings are ok. In addition, just above there is another download button **"mp4_HD"** that is working normally, so we have 2 download buttons, one working and the other with problems, when we only need one.
I attach the figures of the buttons.

![image](https://user-images.githubusercontent.com/75388764/105032591-bc121400-5a35-11eb-8bf2-3cb5fa65ed01.png)

when I press the download button with problems, the screen appears saying that everything is ok, but the button does not update the information.

![image](https://user-images.githubusercontent.com/75388764/105032881-25922280-5a36-11eb-9811-5bb722643b74.png)

I am using Docker environment updated with version 10.1 of AVideo.

**Comment by akhilleusuggo** [comment]
You shouldn't use the second download bouton . That's for other users (non admins ) or those without the permission to download .

Just ignore it .
