### ISSUE TITLE
Live streams are not saving to the selected category

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4401]
I have Category: "Podcast" selected in my live dashboard but when the live stream ends it just goes tot the sites default category.

![363292f2-4725-48d1-89c4-ee8c2070c4a6](https://user-images.githubusercontent.com/39392449/105050406-5d4b9b00-5a33-11eb-83b1-49ab9ffe30cb.png)

![3fb179c4-13bc-4a40-8c94-ea637e53d589](https://user-images.githubusercontent.com/39392449/105050432-63417c00-5a33-11eb-9d4f-918bda0db056.png)

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/issues/4330

**Comment by DanielnetoDotCom** [comment]
@JoshWho your question makes sense.

But, right now it respects the predefined category plugin.

the category on the live is just for display while you are transmitting it.

I may add more options in the future regarding it
