### ISSUE TITLE
Duplicate Videos

### ISSUE THREAD

**Issue by rielcomms** [WWBN/AVideo#4402]
When I upload a Video with the different resolutions like HD, SD and LD, they appear as 3 different Videos on the list of videos. Is there a way to prevent this? I thought the resolution switcher handles this and not for it to result in duplicates or Triplicates.
Thank you

**Comment by JoshWho** [comment]
Not normal at all. Sounds like you have 3 instances of the encoder going at the same time. 

This should not make 3 separate video pages and sounds like a really tricky issue.

**Comment by DanielnetoDotCom** [comment]
@rielcomms maybe you are running incompatible versions of encoder and streamer.

make sure both are the latest version.

**Comment by akhilleusuggo** [comment]
I had this problem because of wrong hostname .
I was encoding from home server behind firewall . Wrong hostnames will cause issues .

**Comment by rielcomms** [comment]
> I had this problem because of wrong hostname .
> I was encoding from home server behind firewall . Wrong hostnames will cause issues .

Its still happening. I use cloudflare, but the hostname is right but I will check again

**Comment by rielcomms** [comment]
> I had this problem because of wrong hostname .
> I was encoding from home server behind firewall . Wrong hostnames will cause issues .

I tried this again and even used the Avideo Streamer and same issue. However I did notice that it does not happen on all Videos and intermittent. Not sure what else I can try?
