### ISSUE TITLE
Search function does not execpt # or , anymore !

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#4405]
Since one of the last updates  the search function does not find hits with # ,% or , in it.

I have lots of #words in the description like #Top, #A73 etc
Searching with %23Top is giving also no results.

**Comment by DanielnetoDotCom** [comment]
For security reasons those characters were removed

**Comment by TLCReuver** [comment]
Okay, but which php file i have to modifu this because all of my videos uses # and , for search option (1530 videos). 
I can modifu this php_file  in a script to handle the future updates.
Thanks.

**Comment by akhilleusuggo** [comment]
idk what type of search you're using , but the `#` does work for me

**Comment by TLCReuver** [comment]
I'm using lines like Tags: #112, #Reuver, #Ongeval, #Personenbus, #Vrachtauto, #A73 in every video.

The search functions does not find these, i also tried %23112%2C for #112.

The main problem is that there is a bug in 'tags" because it show only the first page with the selected tags.
The next page it shows the second page of **all videos** (not tags related)

So the first page show https://archief.beesel-reuver.nl/tag/1/112 and
the second page shows https://archief.beesel-reuver.nl/page/2 (second page of all videos -->no second page of tags)
   this must be: https://archief.beesel-reuver.nl/tag/1/112/page/2 
   
Because 'tags' does not display the content of page 2/3/4/5/etc i used a search #112, from a menu instead that worked perfectly untill one of the last updates.

**Comment by TLCReuver** [comment]
@akhilleusuggo there are 361 videos with #112 in the description but https://archief.beesel-reuver.nl/?search=%23112 does't find any hit.

**Comment by akhilleusuggo** [comment]
Hmmm , I see . I'm using actually the plugin search , maybe that's why I haven't faced this problem .
But yes , I also have hashtags , and the search in general is not working well . I agree
