### ISSUE TITLE
Reset update

### ISSUE THREAD

**Issue by peterflitz** [WWBN/AVideo#4409]
How can I reset the last two updates?
I have the database updates, but the files?

Many problems since the last updates, including the video views no longer work.

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform#rollback-the-update

**Comment by peterflitz** [comment]
thanks.

Not working with option1

option2 ERROR:
ERROR 1060 (42S21) at line 5: Duplicate column name 'rrating'
