### ISSUE TITLE
Video length only shows EE EE EE

### ISSUE THREAD

**Issue by mdent123** [WWBN/AVideo#4410]
[](url)
![videolenth](https://user-images.githubusercontent.com/51091120/105208598-c53bd780-5b40-11eb-8840-661f2ed73b46.JPG)

**Comment by akhilleusuggo** [comment]
check the logs ( encoder and streamer )
probably the encoder or transfer failed

**Comment by daoguey** [comment]
Same here since I updated to 10.1.
![image](https://user-images.githubusercontent.com/15695109/105444542-41aae500-5c2b-11eb-9000-0201325f0fd8.png)

This only happens with videos that are 1hr long. it just fails and i suspect we get this too.
