### ISSUE TITLE
Restart Of Nginx Not Working

### ISSUE THREAD

**Issue by jamesrhenry** [WWBN/AVideo#4412]
I uploaded the SendRecordedToEncoder plugin and called the directions at https://github.com/WWBN/AVideo/wiki/Record-Live-Stream. Everything seems good now, except the fact that I couldn't restart the Nginx, as it says, I believe, there's an extra } somewhere. I couldn't see where though!

**Comment by akhilleusuggo** [comment]
Provide some logs ( error logs at the least )

**Comment by jamesrhenry** [comment]
![Uploading Screenshot_20210121-150542.png…]()

**Comment by jamesrhenry** [comment]
![Screenshot_20210121-150542](https://user-images.githubusercontent.com/5248534/105423439-5a4ed700-5bfa-11eb-8652-da8a959dd3b3.png)

**Comment by akhilleusuggo** [comment]
then do what is asking you to do .

Remove `}` from line 33

**Comment by jamesrhenry** [comment]
I did, and it says it again. I'm not thinking that removing them all will be a good idea though!

**Comment by jamesrhenry** [comment]
And # at the beginning of what?

**Comment by akhilleusuggo** [comment]
Past your config here ;
Hashtag (#) is to comment the line ( to ignore , exclude )

Your error is clear , your config is ending by `}` , but you don't have an open directive to close it in first place .
Remove the } or comment it out . Must be the one on the line 33 . If not , just past here your config .

**Comment by jamesrhenry** [comment]
Sonic did that, and it gave the next line with the same }, and then the next, until I removed all 4. The problem is that now I have open { and nothing closing them }. After there's another error on another line that says I'm missing ; however, that line has http {

I don't believe you end that line with ;. So it keeps giving another line as an error when trying to restart the Nginx.

**Comment by akhilleusuggo** [comment]
You just don't know how nginx works I think .
At the end of every line you need to close with `;` , at the start of every application ( block control ) you should open and close {}

Just past here your config , you can hide sensitive information (actually there isn't any ) , except the domain that you use .

**Comment by unconservo** [comment]
Here is my nginx conf. Just change the servername and letsencrypt to your details and the IP of your local server. I have optimized it a bit and is working pretty well atm with added security. Hope this helps

user    www-data;    
worker_processes  auto;
worker_rlimit_nofile 100000;
    error_log  logs/error.log debug;
    events {
            worker_connections  4000;
            use epoll;
            multi_accept on;
    }
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    application live {
                            allow play all;
                            live on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            hls_playlist_length 60m;
                            hls_fragment 4s;
                            on_publish http://localhost/plugin/Live/on_publish.php;
                            on_play http://localhost/plugin/Live/on_play.php;
                            on_record_done http://localhost/AVideo/plugin/Live/on_record_done.php;
                            recorder video{
                                record all;
                                record_path /var/www/tmp;
                                record_notify on;
                                record_max_size 2048M; 
                                record_suffix -%d-%b-%y-%T.flv;
                            }
                    }
            }
    }
    http {
            open_file_cache max=200000 inactive=20s;
            open_file_cache_valid 30s;
            open_file_cache_min_uses 2;
            open_file_cache_errors on;
            access_log off;
            sendfile on;
            tcp_nopush on;
            tcp_nodelay on;
            reset_timedout_connection on;
            client_body_timeout 10;
            send_timeout 2;
            keepalive_timeout 30;
            keepalive_requests 100000;
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8080;
                    listen 444 ssl;
# Change key paths                    
		    ssl_certificate /etc/letsencrypt/live/youkeyfolder/fullchain.pem;
                    ssl_certificate_key /etc/letsencrypt/live/yourkeyfolder/privkey.pem;
# Change servername 
                    server_name yourservername;
                    location /live {
                            add_header 'Cache-Control' 'no-cache';
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
# Replace this with the IP of your AVideo site (I use my local IP of my server)
                            allow 192.168.1.3;
                            deny all;
                            rtmp_control all;
                    }
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   
   add_header X-Frame-Options "SAMEORIGIN" always;
   add_header X-XSS-Protection "1; mode=block" always;
   add_header X-Content-Type-Options "nosniff" always;
   add_header Referrer-Policy "no-referrer-when-downgrade" always;
   add_header Content-Security-Policy "default-src * data: 'unsafe-eval' 'unsafe-inline'" always;
   add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
            }
    }
