### ISSUE TITLE
Channel Home Tab shows Under Maintanance

### ISSUE THREAD

**Issue by iVrata** [WWBN/AVideo#4413]
**Describe the bug**
We have updated to 10.1 on portal and if we turn on "ShowChannelHomeTab" under CustomizeUsers plugin then the Channel Home Tab shows "Under Maintanance" with Gear icons

**To Reproduce**
turn on "ShowChannelHomeTab" under CustomizeUsers plugin then the Channel Home Tab shows "Under Maintanance" with Gear icons

**Expected behavior**
Show the Home Tab for channels
see [](url)

**Screenshots**
see  [https://video.americonictv.com/channel/Americonic_TV](https://video.americonictv.com/channel/Americonic_TV)
 

**Desktop (please complete the following information):**
Windows 10, Chrome

**Comment by DanielnetoDotCom** [comment]
I fount the error, I will release an update soon

**Comment by DanielnetoDotCom** [comment]
Hey, are you modifying the file?

your file is different than mine. please make sure you have the latest release. otherwise, I cannot help you

**Comment by syldri** [comment]
hello, @DanielnetoDotCom  I have the same problem when I launch a live

I show you the errors that I have

![image](https://user-images.githubusercontent.com/39193219/105355977-1ad0bc80-5bf3-11eb-8f38-de1c15cc8a9e.png)


![image](https://user-images.githubusercontent.com/39193219/105356121-4ce21e80-5bf3-11eb-8edc-8dbef4a18696.png)

![image](https://user-images.githubusercontent.com/39193219/105357151-aeef5380-5bf4-11eb-8ccc-1058e28632ad.png)

**Comment by DanielnetoDotCom** [comment]
@syldri looks like you enabled the Socket when we still not ready

I also can see some fatal errors, I am not sure where they come from

**Comment by iVrata** [comment]
> Hey, are you modifying the file?
> 
> your file is different than mine. please make sure you have the latest release. otherwise, I cannot help you

You did the update on this server with my support ticket.  Can you direct me to the correct files for 10.1 to use?

**Comment by DanielnetoDotCom** [comment]
Try to run this https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform#problems

**Comment by iVrata** [comment]
It states Already up to date

 

 

  _____  

 

Todd Bryant
CTO
iVrata – iVrata.com

C: (512) 633-0220
Skype: todd.c.bryant

**Comment by DanielnetoDotCom** [comment]
I mean run this inside your AVideo folder

`sudo git fetch --all && sudo git reset --hard origin/master`

**Comment by iVrata** [comment]
I did.  I found the issue.  We had modified the front page to list the channels and used the channels.php library of the code but it was causing the issue.   We removed the code and it is fine.  We then rebuilt the front end with new code and did not rely on your libraries.

 

  _____  

 

Todd Bryant
CTO
iVrata – iVrata.com

C: (512) 633-0220
Skype: todd.c.bryant
