### ISSUE TITLE
Is there a way to get rid of the owner info that shows when the embeded code is used?

### ISSUE THREAD

**Issue by gregk63** [WWBN/AVideo#4421]
I want to link to videos using the embed code. Can it be done in such a way the video owner info is not shown?
![embed code](https://user-images.githubusercontent.com/72754374/105409031-713efa80-5bf5-11eb-91b6-0928141dd35c.png)

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
Try this
![image](https://user-images.githubusercontent.com/18009293/105534444-4378b500-5ccc-11eb-81a7-202a5e9693b8.png)

**Comment by gregk63** [comment]
Perfect! Thank you!!
