### ISSUE TITLE
DiskUploadQuota Paypal payment

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4424]
Hi, i can see in the DiskUploadQuota is only the option kreditcard, is ther a option for paypal or via YPTWallet in the future ?

**Comment by DanielnetoDotCom** [comment]
Yes, just enable the PayPal payment on the wallet and you should see it

**Comment by 01123581321345589144233** [comment]
tha paypal wallet is activatet

**Comment by DanielnetoDotCom** [comment]
Check those

The plugin 
![image](https://user-images.githubusercontent.com/18009293/105609448-2dc8c580-5d88-11eb-9d97-fffb43e70935.png)

And the Wallet
![image](https://user-images.githubusercontent.com/18009293/105609467-4fc24800-5d88-11eb-8ee4-ff2e004340bb.png)

**Comment by 01123581321345589144233** [comment]
ah ok is it only working with the YPTStorage plugin ? Not with local storage

**Comment by 01123581321345589144233** [comment]
PayPalYPT is aktivatet also in the wallet

**Comment by DanielnetoDotCom** [comment]
Sorry I circulate the wrong plugin, I mean to circulate the YPTWallet

**Comment by 01123581321345589144233** [comment]
Yes YPTWallet is also installed and activated

**Comment by 01123581321345589144233** [comment]
Have you find out anything?

**Comment by DanielnetoDotCom** [comment]
Hi, 

I just checked into the code and it is Stripe only

![image](https://user-images.githubusercontent.com/18009293/105727452-dce0da80-5f09-11eb-9f68-906dba96cf94.png)

**Comment by 01123581321345589144233** [comment]
Ok but can you make this also working with paypal in the future ?
It will be nice :-)

**Comment by 01123581321345589144233** [comment]
There are many users there have no credit card
