### ISSUE TITLE
500 (Internal Server Error) after last git pull update

### ISSUE THREAD

**Issue by PrXenon** [WWBN/AVideo#4425]
something wrong with one of the last 3 commits ?
![image](https://user-images.githubusercontent.com/3627520/105556981-755d3c00-5d0b-11eb-8f78-cce6046d9690.png)

![image](https://user-images.githubusercontent.com/3627520/105557018-8dcd5680-5d0b-11eb-9f5d-02c6bedb7b83.png)

**Comment by DanielnetoDotCom** [comment]
Check your logs, it is probably related to some paid plugin that you need to update.

**Comment by PrXenon** [comment]
thanks for the fix... and i updated the LiveUser Plugin
