### ISSUE TITLE
Socket / chat

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#4429]
how you can see it in the picture there are two and this him on the chat cannot be removed

![image](https://user-images.githubusercontent.com/39193219/105578257-16d1a580-5d7f-11eb-8b15-b5a5d36f6a91.png)

**Comment by DanielnetoDotCom** [comment]
Hi

Chat has its own socket connection, you can use the minimize button or you can remove the debugger here 

![image](https://user-images.githubusercontent.com/18009293/105580625-3f9c6f80-5d6c-11eb-8e9c-ceae94e95934.png)
