### ISSUE TITLE
Livestream not working

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4431]
in the last few days my livestream stops working.
I have maked updates on avideo and systemupdates.
So when i start a webcammeet, after i have apceptet the microfon and webcam its not starting.

I have a 404 in the web console.
I can access https://tube.gomntu.space:8443, but not the dir /live/600c2dc86f61e/index.m3u8
Seems like the steram key and index.m3u8 are not saved.

**Comment by 01123581321345589144233** [comment]
https://image.linuxhus.dk/01123581321345589144233/images/dbee285cf4fcf520839d89b326910fb8.png

**Comment by unconservo** [comment]
Hi hi. I had the same problem. HLS/live lost its permissions. You have to set permissions again so that YouPHPTube can same the m3u8 files again. Hope this helps

**Comment by 01123581321345589144233** [comment]
i have changed theperms to 777 but its not working

**Comment by unconservo** [comment]
On /HLS/live ?. Normally in your rout folder. Inspect your page... click on console and post screenshot here :)

**Comment by unconservo** [comment]
#4378

**Comment by unconservo** [comment]
In your terminal...

cd
sudo rm -R /HLS
sudo mkdir HLS
cd /HLS
sudo mkdir live

Try it like that

**Comment by 01123581321345589144233** [comment]
i have try this, also i have recompiled the nginx and reinstalled, but not helps.

**Comment by unconservo** [comment]
Inspect page andcpost fibdings here

**Comment by unconservo** [comment]
#4412 hss my nginx conf that works. Try it maybe

**Comment by 01123581321345589144233** [comment]
i have chaged alot of the config, but is still not working.
I have also try to chage the hls dir to the nginx dir under /usr/local/nginx/html but its the same, 
the file is not generated

**Comment by 01123581321345589144233** [comment]
So now i have changed the config to the /tmp/hls but its the same issue

2021/01/23 19:16:34 [error] 2844#0: *1 open() "/tmp/hls/600c42bf49a36/index.m3u8" failed (2: No such file or directory), client: 5.206.193.172, server: tube.gomntu.space, request: "GET /live/600c42bf49a36/index.m3u8 HTTP/1.1", host: "tube.gomntu.space:8443", referrer: "https://tube.gomntu.space/plugin/Live/"
2021/01/23 19:16:35 [error] 2844#0: *1 open() "/tmp/hls/600c42bf49a36/index.m3u8" failed (2: No such file or directory), client: 5.206.193.172, server: tube.gomntu.space, request: "GET /live/600c42bf49a36/index.m3u8 HTTP/1.1", host: "tube.gomntu.space:8443", referrer: "https://tube.gomntu.space/plugin/Live/"
2

**Comment by unconservo** [comment]
Still looks like a file permission problem

**Comment by unconservo** [comment]
Can you see the stat page?

**Comment by 01123581321345589144233** [comment]
yes https://tube.gomntu.space:8443/stat

**Comment by akhilleusuggo** [comment]
Same issue here , I believe is due to the updates .
With the new socks plugin , things stops working properly . Same issues here . I need to debug more .

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo any output in your Nginx or streamer log?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 

"/HLS/live/600c962bad3f3/index.m3u8" failed (2: No such file or directory), client: SERVER'S IP ( NOT client ), server: live.xxxx.com, request: "GET /live/600c962bad3f3/index.m3u8 HTTP/1.0", host: "live.xxxx.com:8443"

The thing is that is taking the server's IP not the client IP

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo it is correct, the stream server now tries to check if the Live is really running 
But this is only needed if you have the sockets enabled. so I disabled it for now with this new update, can you please check if makes any difference

**Comment by akhilleusuggo** [comment]
Works ! perfect !

For me the socket doesn't work . I don't know if has something to do with cloudflare ( I do have the option of Allow Sockets enabled ) , but still not working .

I changed the pôrt that came by default ( I'm not sure if it's the one that causing this issues )  , Open the ports ( ufw enable CustomPort/tcp ) , checked the port , is open . but still not working .

So for this socket , we don't use apache proxy mode ?

**Comment by DanielnetoDotCom** [comment]
Correct Cloudflare does not work the cache, but you can set up a different domain without Cloudflare proxy

I also tested on myself with the SSL certificates issued by letsencrypt and it works fine

![image](https://user-images.githubusercontent.com/18009293/105616966-ad22bd00-5db9-11eb-9461-297fd06fbcb1.png)

**Comment by akhilleusuggo** [comment]
But the connection made is only internal or also external ?
If it's internal changing IP on /etc/hosts should solve the problem . But if it's external , then you maybe right .

Also , will the HostWithoutCloudflare be installed as vhost and pointing to the same directory ? AVideo on html folder ?

Can you try this feature before I make changes and test ?

![image](https://user-images.githubusercontent.com/52116577/105617898-f17a8100-5dea-11eb-8e1b-ae83f7274095.png)

**Comment by DanielnetoDotCom** [comment]
> But the connection made is only internal or also external ?
> If it's internal changing IP on /etc/hosts should solve the problem . But if it's external , then you maybe right .

External

> Also , will the HostWithoutCloudflare be installed as vhost and pointing to the same directory ? AVideo on html folder ?

correct

> Can you try this feature before I make changes and test ?
> 
> ![image](https://user-images.githubusercontent.com/52116577/105617898-f17a8100-5dea-11eb-8e1b-ae83f7274095.png)

Where is this feature?

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/105618099-3e128c00-5dec-11eb-9a9b-76e60d04a89a.png)
 Network on cloudflare dashboard , scroll down a bit ( it's present on free plans too )

**Comment by DanielnetoDotCom** [comment]
NVM I found it on Cloudflare, it was enabled and did not work for me.

**Comment by akhilleusuggo** [comment]
Ok , I see , thank you .
So new host , also will require new SSL certificate , and will have to point to the new ssl certificate to avoid issues , correct ?

This is too much work xD

**Comment by DanielnetoDotCom** [comment]
The SSL from letsencrypt works fine

**Comment by akhilleusuggo** [comment]
Yes , but that certificate path must be the one from HostWithoutCloudflare  ? or from the streamer site ?

**Comment by DanielnetoDotCom** [comment]
> Yes , but that certificate path must be the one from HostWithoutCloudflare ? or from the streamer site ?

HostWithoutCloudflare and the domain should go to your streamer site

**Comment by 01123581321345589144233** [comment]
Hi have you found a solution ?

**Comment by smartweekend** [comment]
Can i run it main website on 1 server and on another server is encoder only with nginx rtmp..  
but after setting it all..  get blank page..

**Comment by DanielnetoDotCom** [comment]
> Hi have you found a solution ?

I cannot reproduce your problem

**Comment by DanielnetoDotCom** [comment]
> Can i run it main website on 1 server and on another server is encoder only with nginx rtmp..
> but after setting it all.. get blank page..

check your log file and open a new issue

**Comment by 01123581321345589144233** [comment]
The nginx socket issue ? I can still not stream it the same issue.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I did what you suggested , but is not working .

I changed the port , I opened it on the firewall . (I'm not sure if changing the port does break things )
New subdomain without cloudflare reverse proxy ( HostWithoutCloudflare is on the host field )
The SSL path , is pointing to HostWithoutCloudflare

Not working


![image](https://user-images.githubusercontent.com/52116577/106607954-8bb99200-656c-11eb-945e-8955cb09df24.png)

**Comment by DanielnetoDotCom** [comment]
Did you start the socket server using sudo?

**Comment by 01123581321345589144233** [comment]
My socket stops workin after 31.01.2021, there are no logs after 31.01 in nopup.php
This is the output when i stat the socket:

Output from command nohup php /var/www/AVideo/plugin/YPTSocket/server.php & ..

Searching for port: 2053
sh: 1: findstr: not found
Killing, PID 11498
Starting AVideo Socket server version 2.2 on port 2053
Your socket server uses a secure connection
Parameter [local_cert]: /etc/letsencrypt/live/***/fullchain.pem 
Parameter [local_pk]: /etc/letsencrypt/live/***/privkey.pem 
Parameter [allow_self_signed]: 1 
Parameter [verify_peer]:  
Parameter [verify_peer_name]:  
Parameter [security_level]: 0 
2021-02-02 18:19:05 Construct
