### ISSUE TITLE
Live Users not counting Watching tab

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4433]
Hi hi. I have done the newest update and now the Watching Now does not count
![image](https://user-images.githubusercontent.com/76112286/105606558-cbc98980-5da2-11eb-9869-4f8978aa7ece.png)

Regards

**Comment by PrXenon** [comment]
#4390

**Comment by unconservo** [comment]
Ok. Thanx :). So not fixed yet :)

**Comment by PrXenon** [comment]
is fixed
