### ISSUE TITLE
Change Log Time

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#4434]
Is there a way to change the Log Time?  It doesn't match my server time.  It's 6hr ahead.

Thanks

**Comment by DanielnetoDotCom** [comment]
Check your PHP timezone or check this

![image](https://user-images.githubusercontent.com/18009293/105611592-f44a8700-5d94-11eb-8137-d669b3313b10.png)

**Comment by D-Spayre** [comment]
Thank you that worked...
