### ISSUE TITLE
Can't login to my site

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#4436]
Greetings I can't login to my site isee this error

The authorization state [state=HA-ZMI81HOKWBVNRJA3PGD27TU0F6Q59CXYL4SE] of this page is either invalid or has already been consumed.

**Comment by DanielnetoDotCom** [comment]
What kind of login is that?
 
google? Facebook?

**Comment by mrgodgiven** [comment]
I have 50 gig of storage left but when I check on my ssh terminal it says
no disk space after uploading a 3 gig video. I deleted it from root and
again saw 50 gig free and when I tried uploading it the 3rd time it's says
disk full I suppose that's whay I can't login. What do you think is the
cause of this?

On 24 Jan 2021 03:52, "Daniel Neto" <notifications@github.com> wrote:

What kind of login is that?

google? Facebook?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/WWBN/AVideo/issues/4436#issuecomment-766274141>, or
unsubscribe

**Comment by DanielnetoDotCom** [comment]
Check your /tmp folder location. it this get full your system will freeze

**Comment by mrgodgiven** [comment]
Could you please give me the command code to check

**Comment by DanielnetoDotCom** [comment]
try `df -h`

then share it here

**Comment by mrgodgiven** [comment]
Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G     0  2.0G   0% /dev
tmpfs           395M  628K  394M   1% /run
/dev/vda1        78G   75G  2.5G  97% /
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/vda15      105M  3.6M  101M   4% /boot/efi
tmpfs           395M     0  395M   0% /run/user/0

**Comment by DanielnetoDotCom** [comment]
I see now, this is your main dir

/dev/vda1 78G 75G 2.5G 97% /

you cannot store too many files on this.

this space is recommended only to the system, your storage/videos directory requires more space 

check this https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements#disk-storage

**Comment by mrgodgiven** [comment]
I have now deleted the one video file and have so much video storage again please see what i mean sir
Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G     0  2.0G   0% /dev
tmpfs           395M  632K  394M   1% /run
/dev/vda1        78G   30G   48G  38% /
tmpfs           2.0G     0  2.0G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/vda15      105M  3.6M  101M   4% /boot/efi
tmpfs           395M     0  395M   0% /run/user/0

**Comment by mrgodgiven** [comment]
48G is available but once I upload a 3gig video all my storage gets full same time and i don't understand that if iam making a mistake from my side or what

**Comment by mrgodgiven** [comment]
Videos Directory: 21.67GB (28.02%) Other Files: 29.39GB (9.97%) Free Space: 47.97GB (62.01%)

**Comment by DanielnetoDotCom** [comment]
I just wrote this, https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements#disk-storage

this may help you understand what is happening
