### ISSUE TITLE
Upload API - webm videos and b2 plugin

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#4438]
Hi,

If i use the upload video api and post a form with the user/pass and file, if the file is a webm and we use b2 storage plugin.  Will the file automatically be uploaded to the b2 storage bucket like the encoder does?

**Comment by DanielnetoDotCom** [comment]
Suppose to

**Comment by millzee01** [comment]
hi, 
I am trying to post a mediarecorder blob to the mobile upload to see if i can automatically add videos

I can play the video in a video element, hwoever when I try and upload it to avideo i dont get an error output but on the log i get:
[26-Jan-2021 16:59:44 UTC] MOBILE UPLOAD: Starts
[26-Jan-2021 16:59:44 UTC] MOBILE UPLOAD: File Not exists - {"file":{"name":"blob","type":"video\/webm","tmp_name":"\/tmp\/phpUcr1qh","error":0,"size":4411151}}

is this because the mobile upload doesn't accept a blob?

**Comment by millzee01** [comment]
doh,

silly error,  the filename didnt have the ext (.webm).

having changed this, the file uploaded to encoder and worked gr8!
