### ISSUE TITLE
Watch later a Favourites

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4440]
Hi hi. When I go into Watch Later or Favourites it automatically plays. Is there a way to set it to view your lists without playing them. Then select one from your list to play?

Regards

**Comment by DanielnetoDotCom** [comment]
It depends on what you choose last on the Autoplay option

![image](https://user-images.githubusercontent.com/18009293/105750001-f2163300-5f22-11eb-938d-6e35dec4c7ad.png)

If you choose to autoplay, it will autoplay the playlists

**Comment by unconservo** [comment]
Thank you

Regards
