### ISSUE TITLE
Pay per view plugin

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4441]
Hi hi. I have a few questions.

1. Where do you see pay per view schedules?.  If you start selling a live stream whete do you see where to buy access as an user?
2. Can each user schedule pay per view on their own channels or must the scheduling go through admin only?.  Does not make sense if only admins can schedule pay per view live scheduling.

Regards

**Comment by DanielnetoDotCom** [comment]
> 1. Where do you see pay per view schedules?.  If you start selling a live stream whete do you see where to buy access as an user?

When you access the LiveURL the payment screen will popup

![image](https://user-images.githubusercontent.com/18009293/105751635-0eb36a80-5f25-11eb-90ef-f4b8b347bb65.png)


![image](https://user-images.githubusercontent.com/18009293/105750589-b334ad00-5f23-11eb-8691-52198a696db0.png)


![image](https://user-images.githubusercontent.com/18009293/105750496-939d8480-5f23-11eb-998b-8eb530dfe97a.png)


> 2. Can each user schedule pay per view on their own channels or must the scheduling go through admin only?.  Does not make sense if only admins can schedule pay per view live scheduling.

Each user can schedule his own lives, but can only use the plans created by the admin

**Comment by unconservo** [comment]
Thank you for your response. I will try that

Is there a tab or category that shows all ppv streams so users can select
from?.

Regards

**Comment by DanielnetoDotCom** [comment]
Not yet, but we will add it in the future

**Comment by unconservo** [comment]
Awesome. Thanx
