### ISSUE TITLE
Socket shows Disconnected

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#4442]
I can't seem to get the socket to connect.  I activated the plugin ran `nohup php /var/www/AVideo/plugin/Socket/server.php &`.
When I run the command I do get this:
```
[6] 20937
user@ubuntu:/var/www/AVideo$ nohup: ignoring input and appending output to '/home/user/nohup.out'
```
When I press Enter I get this:
`[6]-  Killed                  nohup php /var/www/AVideo/plugin/Socket/server.php`

When I check the process it shows running.
`php       20449          user    3u  IPv4 344940      0t0  TCP *:2053 (LISTEN)`

I opened the port on the firewall and forwarded it on the router.

Log:
```
[24-Jan-2021 14:24:43 America/Halifax] myMySQLDatabaseLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime path/to/my/streamer/site/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /objects/pluginSwitch.json.php
 [24-Jan-2021 14:24:43 America/Halifax] myMySQLDatabaseLog::DEBUG: plugin::setCurrentVersionByUuid Socket-5ee8405eaaa16, 1.0 SCRIPT_NAME: /objects/pluginSwitch.json.php
 [24-Jan-2021 14:24:37 America/Halifax] myMySQLDatabaseLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime path/to/my/streamer/site/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /objects/pluginSwitch.json.php
 [24-Jan-2021 14:24:37 America/Halifax] myMySQLDatabaseLog::DEBUG: plugin::setCurrentVersionByUuid Socket-5ee8405eaaa16, 1.0 SCRIPT_NAME: /objects/pluginSwitch.json.php
 [24-Jan-2021 14:22:54 America/Halifax] myMySQLDatabaseLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime path/to/my/streamer/site/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /objects/pluginAddDataObject.json.php
```

PHP version 7.2.24

Thanks

**Comment by DanielnetoDotCom** [comment]
Check this https://unix.stackexchange.com/questions/420594/why-process-killed-with-nohup

**Comment by DanielnetoDotCom** [comment]
Try the command without nohup

`php /var/www/AVideo/plugin/Socket/server.php`

**Comment by D-Spayre** [comment]
That got me a little farther, but still shows disconnected.

After running `php /var/www/AVideo/plugin/Socket/server.php` I get the following.
```
[1] 24724
user@ubuntu:/var/www/AVideo$ AVideoLog::DEBUG: Starting Socket server at port 2053 SCRIPT_NAME: /var/www/AVideo/plugin/Socket/server.php
Searching for port: 2053
sh: 1: findstr: not found
No Need to kill, port NOT found
Starting AVideo Socket server version 2.2 on port 2053
Your socket server uses a secure connection
Parameter [local_cert]: /etc/letsencrypt/live/www.DOMAIN.ca/fullchain.pem
Parameter [local_pk]: /etc/letsencrypt/live/www.DOMAIN.ca/privkey.pem
Parameter [allow_self_signed]: 1
Parameter [verify_peer]:
Parameter [verify_peer_name]:
Parameter [security_level]: 0
AVideoLog::SOCKET: Construct SCRIPT_NAME: /var/www/AVideo/plugin/Socket/server.php
2021-01-24 18:24:59 Construct
```

Thanks

**Comment by DanielnetoDotCom** [comment]
Ok, and now check the JS console log

**Comment by D-Spayre** [comment]
Sorry where do I find the JS console log? I cleared the avideo.log and then ran the `php /var/www/AVideo/plugin/Socket/server.php` but nothing shows back up in that log.

Thanks

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

**Comment by D-Spayre** [comment]
```
Getting webSocketToken ...
script.js?1611510008:184 Getting webSocketToken SUCCESS  {error: false, msg: "", webSocketToken: "QmJQYzFhQkUxZ09WYVdJSWlJRTR0TENFK3VVZ0RVSUZKd3ZxWG…iSzIyQllrdEFmMnhvd0NRUWlwVWpoeDFtL241c1VWdFNIaw==", webSocketURL: "wss://www.DOMAIN.CA:2053?webSocketToken=QmJQYzFhQk…vd0NRUWlwVWpoeDFtL241c1VWdFNIaw==&isCommandLine=0"}
script.js?1611510008:9 Trying to reconnect on socket... 
script.js?1611510008:10 WebSocket connection to 'wss://www.DOMAIN.CA:2053/?webSocketToken=QmJQYzFhQkUxZ09WYVdJSWlJRTR0TENFK3VVZ0RVSUZKd3ZxWG5ZSURJcGNibVZOYmxZNXpwcnZjQ3poR1pBdVJ3cXlMVTFEaTVaT0NJb2FnMEZjU0hWYnFMUExLRXdlWXJVaHpDRWh1VUMxUnl4U0lMT1hESDVjQlZrZkI0V04vUTZHaWdOTzhrdUE0ZVA5c2NKZDZjVjhSREx5MThLR2FtdCt0YmNicGNpeFN5S25UaUVvSUVtbUdERlo5MnJuTSsvWnQ2UStXbXNGY2xldFpiOGFoa2tHcHp6YXBiL2ZCRjNneVFWbUszamx2VXdPRjJZZkFNbmdmRDc0VFlVYXRzL21BQllEVDM3WGhpMmZTcVpNQnlMT0tYQzhQT2VzS2s4aElkajNUaGZ6MDV4MzZ4RXpjdkVKczlGc3k3VHd5dzEwRy9kSUJSZDd6WG5yVThEZHI2Y21vbEFCbStRc29vRHNtMXFrZUxqbjBrYWRpU2tZUzV3SjVXNEpWa3Iram9wL2gwaDdBaUo4ZUx2Qk5mS0xkUEVlUkNUOU56Rmlqd3dFaU9mT3VNSEUrTWIyTDJOWTA0Vk42ZmhSUDZobWV3VUtwZTJrd2xCUCttNGVlT3NoRHdmVXlLaXBkMDVMVXhGanZrYTc3YWpXSVZsMUdtMFdXeWc3ZFYzUmJCcGFkbDNUdnUwVjlMQVJCdzlYUFRkeEhuOE1mK2xNZW5zM1F3UEgxNk5hM3Ayd2k2bERlc2czS1kySjR3Smpuamk5VURybFR1L0plZlhQMXU5WmVxMmd1bE5GVGZ0SlRiSzIyQllrdEFmMnhvd0NRUWlwVWpoeDFtL241c1VWdFNIaw==&isCommandLine=0&page_title=Home%20%B7%Test' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
socketConnect @ script.js?1611510008:10
success @ script.js?1611510008:187
c @ jquery-3.5.1.min.js:2
fireWith @ jquery-3.5.1.min.js:2
l @ jquery-3.5.1.min.js:2
(anonymous) @ jquery-3.5.1.min.js:2
script.js?1611510008:59 Socket encountered error:  undefined Closing socket
conn.onerror @ script.js?1611510008:59
error (async)
socketConnect @ script.js?1611510008:57
success @ script.js?1611510008:187
c @ jquery-3.5.1.min.js:2
fireWith @ jquery-3.5.1.min.js:2
l @ jquery-3.5.1.min.js:2
(anonymous) @ jquery-3.5.1.min.js:2
load (async)
send @ jquery-3.5.1.min.js:2
ajax @ jquery-3.5.1.min.js:2
(anonymous) @ script.js?1611510008:177
e @ jquery-3.5.1.min.js:2
t @ jquery-3.5.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.5.1.min.js:2
c @ jquery-3.5.1.min.js:2
fireWith @ jquery-3.5.1.min.js:2
fire @ jquery-3.5.1.min.js:2
c @ jquery-3.5.1.min.js:2
fireWith @ jquery-3.5.1.min.js:2
ready @ jquery-3.5.1.min.js:2
B @ jquery-3.5.1.min.js:2
script.js?1611510008:51 Socket is closed. Reconnect will be attempted in 1 second. 
script.js?1611510008:9 Trying to reconnect on socket... 
```

**Comment by D-Spayre** [comment]
Here are a couple of errors that popped up in the logs not sure if they are related.

`[24-Jan-2021 21:16:11 America/Halifax] myMySQLDatabaseLog::ERROR: Could not connect: Connection to www.mysite.com:2053 failed: Last error for IPv4: Connection to tcp://127.0.0.1:2053?hostname=www.mysite.com failed: Connection refused. Previous error for IPv6: DNS query for www.mysite.com did not return a valid answer (NOERROR / NODATA) wss://www.mysite.com:2053?webSocketToken=QmJQYzFhQkUxZ09WYVdJSWlJRTR0Q0dkd25HMGsyZC9rRGl4SFhNNm1oRXpIWXJJVWxHKzBpZTVOOEFpVS8zNFdUZ05iZlVXZTY4NCtUU29EanBuNHBudVFxeHVPZHFFNmhOaGIzVGZMOU9zVEMyTjhhNzJjcm9DRUVGS1ZQRHpVMzh1eTdMVGRIeERtUENWVWJFczdDeUZGV24zb1cwOFNXWEd3RkJoanNEOEhNeFZRUDJpU0NxcWlzblgxRU9hNWNrU2J4ZXE3SnVUaXZNN2dtRCtpeFM3QTNINmpOdGpvQkdPc2Z6N3ZlU0QralBHZmtUd1BiUC8vR3h1dXczMnhScDhURFJvMUZseXNMb0J5dmJqa2R6QlVmbUpac2cwalI1RElrUFBINEgxYUhtRXV2WlU5UXlRT2c4eEcrWmFJbmZlcGNROENoYkJnM3pLcnhhenFKNXRCazNic2t2VWR4TkFScTI2a2hNNVN3ZmsxajZWMHI2VktMUzBxQWJueVZTQkpvRUxVQUJldC9qS1U4a1F1ZXlpN0Y1NTd5WlpkTnkvajJGZVV1UmxyamVDdXZ4R2NURmJPNldYdExzTEMxWFhYaFkwaXpkai9JUm5VSUxlVmtyeCtvem1yckM3L2ZTQXRyK2YwMEwxbXpkUHBoTXI5VHY5UWpMMVF1Y3VFNFFTeDlhRWwrQkNmZHFLQ0RXcmdrdEVVQS9XcUxCdFdVaGlzQW9Ubk0yb3BsQUxiN3A0WGhwamdUc1FuckxaWkVOYS8wR3pUMzBueWtIU1BFN0Irc1IxdEdQMFFrS2Q1c3RsS3ozbnNCa0N5d2QyVW9pRmZlOTlWaDM2MGhaVHhzaVFpa1ZqZDZDaG1iaXcrelJOSDNzRkJQZFlRb1BBc25JdlpDcjA1UURzcjZFYUdQWTNBWVZkTEdhZXV5VWg0V2lUcWZnUDQ2Q2NueUNNcXZncmZMNG84MzA1R3p5KzdNZGtaZ0NhZTQ0PQ==&isCommandLine=1 SCRIPT_NAME: /plugin/LiveUsers/view/beat.json.php`

` [24-Jan-2021 21:16:11 America/Halifax] myMySQLDatabaseLog::ERROR: sendSocketMessage  SCRIPT_NAME: /plugin/LiveUsers/view/beat.json.php
`

**Comment by DanielnetoDotCom** [comment]
I guess it means something. but it is something specific to your network

If you google for that you get a lot of answers 
https://www.google.com/search?q=Connection+refused.+Previous+error+for+IPv6%3A+DNS+query+for+did+not+return+a+valid+answer+(NOERROR+%2F+NODATA)&oq=Connection+refused.+Previous+error+for+IPv6%3A+DNS+query+for++did+not+return+a+valid+answer+(NOERROR+%2F+NODATA)&aqs=chrome..69i57.3751j0j7&sourceid=chrome&ie=UTF-8

**Comment by D-Spayre** [comment]
Thanks for that I'll look into it.

Just an FYI.
The new YPTSocket doesn't show the debugger for admin at all.  Also same issue as above.

Thanks

**Comment by D-Spayre** [comment]
The Debugger did show up after a little bit but still shows disconnected.

Thanks

**Comment by DanielnetoDotCom** [comment]
I just sent a few more updates related to Sockets, please update and test it.

**Comment by D-Spayre** [comment]
Updated and still doing the same thing.

`nohup php /var/www/AVideo/plugin/YPTSocket/server.php &` gives me this:
`[1] 27061
user@ubuntu:/var/www/AVideo$ nohup: ignoring input and appending output to '/home/user/nohup.out'
`

`php /var/www/AVideo/plugin/YPTSocket/server.php` gives me this:
`AVideoLog::DEBUG: Starting Socket server at port 2053 SCRIPT_NAME: /var/www/AVideo/plugin/YPTSocket/server.php
Searching for port: 2053
sh: 1: findstr: not found
Killing, PID 27061
Starting AVideo Socket server version 2.2 on port 2053
Your socket server uses a secure connection
Parameter [local_cert]: /etc/letsencrypt/live/www.DOMAIN.ca/fullchain.pem
Parameter [local_pk]: /etc/letsencrypt/live/www.DOMAIN.ca/privkey.pem
Parameter [allow_self_signed]: 1
Parameter [verify_peer]:
Parameter [verify_peer_name]:
Parameter [security_level]: 0
AVideoLog::SOCKET: Construct SCRIPT_NAME: /var/www/AVideo/plugin/YPTSocket/server.php
2021-01-26 16:00:27 Construct
`

`Getting webSocketToken ...
script.js?1611690597:188 Getting webSocketToken SUCCESS  Object
script.js?1611690597:9 Trying to reconnect on socket... 
script.js?1611690597:10 WebSocket connection to 'wss://www.DOMAIN.CA:2053/?webSocketToken=QmJQYzFhQkUxZ09WYVdJSWlJRTR0TENFK3VVZ0RVSUZKd3ZxWG5ZSURJcGNibVZOYmxZNXpwcnZjQ3poR1pBdVJ3cXlMVTFEaTVaT0NJb2FnMEZjU0hWYnFMUExLRXdlWXJVaHpDRWh1VUMxUnl4U0lMT1hESDVjQlZrZkI0V04vUTZHaWdOTzhrdUE0ZVA5c2NKZDZjVjhSREx5MThLR2FtdCt0YmNicGNpeFN5S25UaUVvSUVtbUdERlo5MnJuTSsvWnQ2UStXbXNGY2xldFpiOGFoa2tHcHp6YXBiL2ZCRjNneVFWbUszamx2VXdPRjJZZkFNbmdmRDc0VFlVYXRzL21BQllEVDM3WGhpMmZTcVpNQnlMT0tYQzhQT2VzS2s4aElkajNUaGNPZHNKS29zdlhsMDRqeWZrR1ZEMGZpUnRwY3Q4ZHJqWkg3dzgwV2lqVjZMd05jM0JFc1ZjeHVyQVhwcE0zaGpuTnF5RzRqUDlFRzVjaEE0VU9pZ0J4QjF5ZytzSURIdkV3a1RWZFpiOC9rYVBUUmRuSVdsc0tUaEZnMUFyL2xsNzVkdXhKeDl2VjZ5UDNPSi9uVzRkakdQbUJjSDhuTFFXdmdaTUpjMEFYU2FINldsSGEyNUpLTjVRNUZ5Qk9nM2hVMmNuZ2hDaE1iNXh1eFQ3U2IydTNwWG9pZGJ1b3dyeTFoZWlsNVFib0pQY2l5M29teEdkU0hzY2doMWhWYTRwZEFpTHhIK0laK2xUcFh1TElNdldwVkk1U3JtaXJ1dEhlZUUwbWJ4MktOVjRYcDdVUWQzTm95S3NoT09kNjJNTElkQ21hOXhuTzlxSFAzSGZ0eXBwcg==&isCommandLine=0&page_title=Home%20%B7%20TEST' failed: Error in connection establishment: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH
socketConnect @ script.js?1611690597:10
script.js?1611690597:59 Socket encountered error:  undefined Closing socket
conn.onerror @ script.js?1611690597:59
script.js?1611690597:51 Socket is closed. Reconnect will be attempted in 1 second. 
`

Thanks

**Comment by DanielnetoDotCom** [comment]
Your certificates do not match with the socket host

**Comment by D-Spayre** [comment]
Hi,

The certificates do match, it's the same certificates that are in the Nginx config file and avideo-le-ssl.conf file.
SSL works on my site, I'm not sure what I'm missing.

Thanks

**Comment by DanielnetoDotCom** [comment]
this is NOT what you browser is saying 

`failed: Error in connection establishment: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH socketConnect `

**Comment by D-Spayre** [comment]
Is there anything else I can check, doesn't make sense as my SSL seems to work fine.

Thanks

**Comment by DanielnetoDotCom** [comment]
you can google for it

**Comment by D-Spayre** [comment]
Ya that's what I've been doing but I can't seem to find anything that helps.
I'll keep searching.

**Comment by DanielnetoDotCom** [comment]
did you run the server command as root?

try `sudo php /var/www/AVideo/plugin/YPTSocket/server.php`

**Comment by D-Spayre** [comment]
Frig that did it. 
Both commands work

Thank you
