### ISSUE TITLE
Chat2 On premise without internet

### ISSUE THREAD

**Issue by Fnaxx** [WWBN/AVideo#4443]
Hello,

I have an internal installation of aVideo On premise without direct Internet connection. I bought and installed the Chat2 plugin but it does'nt work. 
The chat aera is appearing correctly but I'm not able to enter text to send a message (I'm logged in with a user):
![image](https://user-images.githubusercontent.com/50245882/105639738-3b5e7800-5e7a-11eb-8b66-078aeac92bd4.png)

I have seen in the browser log the following error:
![image](https://user-images.githubusercontent.com/50245882/105639821-93957a00-5e7a-11eb-8107-8829611796ea.png)

So I suppose the browser is trying to get the emojione JS online but I have not internet connection on this computer. Do you think the issue that I don't have the "writting text zone" to write a message is coming from this error not loading this JS? If yes is there a way not to have the plugin searching for online JS but more locally on the serveur?

Thank you for you help.

**Comment by DanielnetoDotCom** [comment]
I will update the Chat2 soon 

the version 4.2 the emojione error will not happen anymore, but it will still require an internet connection

**Comment by Fnaxx** [comment]
Hello,
In the emojionearea i have seen this
```
EmojioneArea uses awesome Emojione emojis.
So when emojionearea.js loads, it's require to emojione.js loaded too, but if it not loaded in the page then EmojioneArea loads it from CDN.
For avoiding this behavior you can add emojione.js and emojione.css into your page.
```
Maybe it is possible to use that or maybe a properties to enable the _standalone_ mode of the library or the _useInternalCDN_ but maybe I miss understand those library options.
