### ISSUE TITLE
error login

### ISSUE THREAD

**Issue by houssem2055** [WWBN/AVideo#4444]
error login
http://ayoub-kirouane.atwebpages.com/view/index.php

https://user-images.githubusercontent.com/65106630/105642801-5cc85f80-5e8c-11eb-89c0-a9c31b9eab52.mp4

help

**Comment by DanielnetoDotCom** [comment]
I guess you do not have the mod-rewrite enabled
https://www.digitalocean.com/community/tutorials/how-to-set-up-mod_rewrite

**Comment by houssem2055** [comment]
There is a problem with a version that I tried to install in localhost several times and this problem remained and the older versions work normally
