### ISSUE TITLE
Subscription Plan "Create your accout"

### ISSUE THREAD

**Issue by D-Spayre** [WWBN/AVideo#4445]
Hi,

We only use "Sign Ups" from FB, when using the Subscription plugin and when you click on a private video it will take you to the show plan page (attached image).  If your not logged in you get the "Create your account" button.  I have disableNativeSignUp enabled.  Is there a way to remove the "Create you account" button and have just the "Sign In" buttons or have the "Create your account" button as the FB button?

I hope that makes sense. :)

Thank you,

![SignUp](https://user-images.githubusercontent.com/65576427/105642881-e2cfb080-5e62-11eb-9cf7-4c969095d7fa.png)

**Comment by DanielnetoDotCom** [comment]
Hi

You are correct, Soon I will send updates to this plugin and also to some others with the same issue.

also, you will need to update the streamer

**Comment by D-Spayre** [comment]
Thanks the update worked.

When you say update the streamer is that `sudo git pull` command your referring too?

Thanks

**Comment by DanielnetoDotCom** [comment]
Correct
