### ISSUE TITLE
Why Is My Encoder Page Extremely Low Response Time, Even Before Uploading, When No Other Activity?

### ISSUE THREAD

**Issue by dailafing** [WWBN/AVideo#4447]
With a fresh install of AVideo, and it's encoder, everything is nice and fast. Such as when navigating the admin and setting pages.

However, when I navigate to my.site/upload, everything in here is slow at responding.

When I first enter my.site/upload, I am greeted with the log in page, with is prefilled from being already logged in to main site. This then automatically begins to log my into the encoder page, and I am presented with the "Processing..." pop up box.

This pop up box is the first instance of the encoder area behaving really really slowly.
This takes nearly 20 seconds to log in, despite a fresh install, with only 2 users. (default admin, and a normal reg user)

My next step is to upload a file.
Once the file is selected (handled by my browser on the client), I press start upload.
I see that every step in the process, has a long gap of 5-10 seconds, where it feels as though the server is extremely sluggish.

And just to be clear, I am not including the times where ffmpeg is converting the video file, since that all depends on hardware, and video length.

During all of this i am closely monitoring htop, to see for any processes that are hogging the CPU.
Nothing... the only time cpu ramps up, is when the encoder process gets to the actual ffmpeg command.

And also, just to be clear.... The main site is extremely fast, everything is literally instant.... everything loads so fast, and literally no buffering time whatsoever, im really really impressed.

Please let me know what i can do to help diagnose this strange long response time for the encoder page, thanks.

Ps. I believe the encoder log in page, should not display the first input box "Streamer Site". I cannot imagine why a user would need to be able to change anything there, they just need to log in? Can this be disabled? Thanks.
![laggy encoder page](https://user-images.githubusercontent.com/58471820/105658711-f446a600-5ebe-11eb-8d4e-4e68c88bb7d7.PNG)

**Comment by houssem2055** [comment]
I also had this problem

**Comment by DanielnetoDotCom** [comment]
check the log files, encoder and streamer
