### ISSUE TITLE
ypt storage not deleting videos after transfer .

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4450]
After moving files from a storage to another , ( or even locally ) , the files are not deleted from the destination after finishing the transfer . Some of them just keeps looping .

Now I have many duplicated videos on both storages 

edit: Those files that made it , the size where triplicated . ( files of 100mb , became 300+ mb )

test transfer between 2 Avideo storage ;

**Storage destination (Storag1) ;** 
![image](https://user-images.githubusercontent.com/52116577/105796073-b2892e80-5f96-11eb-89bc-8d22e7a54495.png)

**Storage Origin (Storage2) ;**
![image](https://user-images.githubusercontent.com/52116577/105795967-748c0a80-5f96-11eb-8f34-56e6d6f3b4cd.png)

EDIT2 : I found where the issue is coming from ; is downloading the video on the `AVideo-Storage/` instead of `AVideo-Storage/videos` . After 6 retries , finally gets the last one into `/videos` directory .

![image](https://user-images.githubusercontent.com/52116577/105833754-5217e280-5fd2-11eb-95fd-95a54f6e0e7c.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom the output location is missing when plugin secure directory is enabled .
When it's enabled , videos are downloaded with wget , but nothing more .

Usually `wget $input -o $output` , but in this case , I see no output . I believe is a database issue , due to the length of the URL . But not sure .

This is a transfer that is nor working properly . Doesn't even display the secret=key nor the destination , this is how the execution ends

![image](https://user-images.githubusercontent.com/52116577/106242041-bb386980-620f-11eb-8282-73037a84c174.png)


This one is working properly ;

![image](https://user-images.githubusercontent.com/52116577/106242463-6517f600-6210-11eb-9d67-6734fd4669db.png)

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo I will check that, I just need some time.

but thanks for the info
