### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by esaitbd** [WWBN/AVideo#4453]
:  Uncaught Error: Call to undefined function imagecreatefrompng() in C:\xampp\htdocs\AVideo\objects\functions.php:1643
Stack trace:
#0 C:\xampp\htdocs\AVideo\objects\functions.php(2908): convertImage('C:/xampp/htdocs...', 'C:\\Users\\Esaitb...', 100)
#1 C:\xampp\htdocs\AVideo\objects\configuration.php(251): convertImageToOG('C:/xampp/htdocs...', 'C:/xampp/htdocs...')
#2 C:\xampp\htdocs\AVideo\objects\functionogSite.php(16): Configuration::getOGImage()
#3 C:\xampp\htdocs\AVideo\objects\functions.php(2948): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\AVideo\view\include\head.php(176): ogSite()
#5 C:\xampp\htdocs\AVideo\plugin\Gallery\view\modeGallery.php(10): include('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\AVideo\view\index.php(30): require('C:\\xampp\\htdocs...')
#7 {main}
  thrown in 

> 

- [ ]  @[](url)

**Comment by akhilleusuggo** [comment]
you're running this in windows OS I guess 
There's no support for windows , you need to find a solution by yourself ( google is your best friend )
