### ISSUE TITLE
API issue: PHP Fatal error:  Out of memory

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#4454]
Hi,

When i use the api to upload a video blob, using FireFox it uploads fine.

With a chromium browsers (chrome/edge/opera) I am getting the following error:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

in the log i get
[26-Jan-2021 21:29:42 UTC] MOBILE UPLOAD: Starts
[26-Jan-2021 21:29:42 UTC] PHP Fatal error:  Out of memory (allocated 4194304) (tried to allocate 72057594037927968 bytes) in /var/www/html/objects/getid3/getid3.php on line 1703

does fread() have any issues  reading blob data from chromium?

because the video is only 4mb, and in firefox I get "video has been sent to the encoder" and also get a video_id

**Comment by DanielnetoDotCom** [comment]
please update your code and tell me if this persist

**Comment by millzee01** [comment]
hi, i updated as my getid3 was out of date.

I still however get the issue when uploading from chromium browsers.  looking into it, the format of the generated webm on chrome isn't 100% complete so i have to use seekableblob function with ts-ebml to add seek info.

**Comment by millzee01** [comment]
i've tried testing my upload script to your avideo demo site and get:
status: 200 
error uploading video to channel

this happens in firefox and chrome.  Should i be able to upload using the api to the demo site?

I used the admin link that is generated when you click "info" on the api plugin.

**Comment by DanielnetoDotCom** [comment]
what code are you using?

**Comment by millzee01** [comment]
The blobData is just a playable webm.

			var formData = new FormData();
			formData.append('upl', blobData, "test-carl.webm");
			formData.append("title", "test-carl");
			formData.append("description", "session planner animation"); 
			formData.append("categories_id", "1"); 			
			$.ajax({
			    url: 'https://demo.avideo.com/plugin/MobileManager/upload.php?user=admin&pass=f321d14cdeeb7cded7489f504fa8862b',
			    data: formData,
			    contentType: false,
			    processData: false,
			    type: 'POST',
		        headers: {
		            'Content-Type': 'multipart/form-data'
		        },			    
			    success: function(response) {
			        if (response === 'success') {
			            console.log('successfully uploaded recorded blob');
			       } else {
			           console.log(response);
			        }
			    },
				error: function(a) {
				  console.log("error uploading video to channel");
				  console.log(a);
				}			    
	 		});


This code works fine on my server with firefox,  however i thought i would try it on yours and see if i get the same results.

when i post the file using chrome on my server, it gets to: $duration = Video::getDurationFromFile($_FILES['upl']['tmp_name']);

and no further. but shows the PHP ERROR.

**Comment by DanielnetoDotCom** [comment]
Hi, sorry for the delay.

I see now your code is a Javascript code, and the problem is related to the browser NOT the PHP code itself.
you should google for the browser compatibility of your code.

**Comment by millzee01** [comment]
i agree, it's down to a malformed video file.  chromium browsers don't write the meta data correctly and as such the duration is infinity.

Firefox and Safari are fine.

**Comment by millzee01** [comment]
Hi,

I got to the bottom of the issue.  

https://bugs.chromium.org/p/chromium/issues/detail?id=642012#c24

Becuase i am using mediarecorder to record the video, there is no effective way of adding the "segment" info into the video.

When getid3 tries to analyze the file, it runs out of memory because the video is "infinite".

So, 
How do i go about running ffmpeg on the server, via upload.php?

Do i need to hook in the encoder?
