### ISSUE TITLE
Issue with URL encoding

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4455]
My URLs are always presented like that whenever I paste them on Telegram or other places I want to share the video link.
Can this be resolved to make the URL appear in a more readable manner?

![Screen Shot 5781-05-14 at 6 30 10](https://user-images.githubusercontent.com/58882903/105944280-ade27a00-606b-11eb-8801-49b1a53bf228.jpg)

**Comment by akhilleusuggo** [comment]
This is because most likely the titles are not in latin character

**Comment by guymass** [comment]
Well they are Hebrew chars, but I am not sure if this is an AVideo issue of other Apps issue with translating and displaying the link with a readable URL.

**Comment by DanielnetoDotCom** [comment]
what exactly characters is the title of this video?
paste it here so I can make some tests

**Comment by guymass** [comment]
Those are Hebrew characters, for examle this URL:

https://live.ahava528.com/video/1559/%D7%9C%D7%94%D7%A2%D7%99%D7%A8-%D7%90%D7%AA-%D7%94%D7%97%D7%99%D7%95%D7%A0%D7%99%D7%95%D7%AA-%D7%A2%D7%9D-%D7%99%D7%95%D7%97%D7%90%D7%99-%D7%93%D7%95%D7%A8-%7C-%D7%A2%D7%9E%D7%95%D7%93-%D7%94%D7%A9%D7%93%D7%A8%D7%94-%D7%95%D7%9E%D7%95%D7%97-%D7%94%D7%A2%D7%A6%D7%9D-4-on-28-jan-21-09-19-38

In the browsers appear  like so:
![Screen Shot 5781-05-15 at 13 49 08](https://user-images.githubusercontent.com/58882903/106134784-b328ed00-616f-11eb-9e49-c2ff2d378914.jpg)

Even when I paste it here in this textbox it converts them to this string.

**Comment by DanielnetoDotCom** [comment]
Can you please paste some Hebrews chars here so I can try myself?

**Comment by guymass** [comment]
אבגדהוזחטיכאלמנסעפצקרשתףץם

The whole alphabet

**Comment by DanielnetoDotCom** [comment]
I guess it was fixed in some recent update 

![image](https://user-images.githubusercontent.com/18009293/109150710-0169e580-7748-11eb-92fd-cdeea43b9d74.png)

**Comment by guymass** [comment]
Yes the URL is now fixed an we can see them properly, however now I see another issue with this and it is when for example I wish to copy a URL from one site and import it through the encoder import video, the URL in the field is turned back to a long string like so:

https://live.ahava528.com/video/1249/%D7%9E%D7%98%D7%A8%D7%99%D7%A7%D7%A11--%D7%A8%D7%A9%D7%AA-%D7%97%D7%91%D7%A8%D7%AA%D7%99%D7%AA-%D7%97%D7%93%D7%A9%D7%94-%D7%A4%D7%A8%D7%98%D7%99%D7%9D-%D7%91%D7%AA%D7%99%D7%90%D7%95%D7%A8-%D7%94%D7%A1%D7%A8%D7%98%D7%95%D7%9F

Which than give a mysql errot:

AVideoLog::ERROR: Error in writeSql : (1406) Data too long for column 'videoDownloadedLink' at row 1

**Comment by guymass** [comment]
This field also needs to be able to handle RTL Hebrew characters in the URL, otherwise it gets tool long for the mysql fields value. It wont allow me to imports those type of urls.

![Screen Shot 5781-06-15 at 22 34 18](https://user-images.githubusercontent.com/58882903/109399564-465e6980-794c-11eb-94bd-7458ed04b1fa.jpg)

**Comment by DanielnetoDotCom** [comment]
This is an unconventional URL, I guess a size over 255 is already a very long URL.
I am limiting now the max length, it should make any difference on AVideo links, so feel free to use AVideo URLS what ever length it is

![image](https://user-images.githubusercontent.com/18009293/109501155-f976b200-7a75-11eb-90ae-83a607a5c028.png)

**Comment by guymass** [comment]
Well I am using those URLs, but the problem is when I copy a url that has Hebrew characters in it and I than paste it in the import field, that field converts those letters into that very long string of % and numbers. If the field would not change the url it would be fine, the problem is in the way that field is encoding those letters.

**Comment by wildmaster84** [comment]
![image](https://user-images.githubusercontent.com/46942741/110059605-8baade80-7d32-11eb-83e4-12d1ae1441f9.png)
is there an options to make the url random characters instead of using the video id?

I would like to use something like "/video?p=UIJDOji_iwdaE883".
