### ISSUE TITLE
Server crashing unknow issue!

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4456]
My server has started either chocking or crashing for some reason. I need to SSH and restart APACHE. I am seen some unknown errors in logs but not sure what they mean. Here are the logs screenshots.

![Screen Shot 5781-05-14 at 5 56 40](https://user-images.githubusercontent.com/58882903/105981128-64f7e900-609e-11eb-801f-2e3e977d9cfb.jpg)
![Screen Shot 5781-05-14 at 5 29 07](https://user-images.githubusercontent.com/58882903/105981144-6aedca00-609e-11eb-8257-7fe99435fb1e.jpg)

**Comment by DanielnetoDotCom** [comment]
I do not think you are running the latest version

**Comment by guymass** [comment]
![Screen Shot 5781-05-15 at 1 37 51](https://user-images.githubusercontent.com/58882903/106068607-7d511d80-6109-11eb-9472-fdccc1b10958.jpg)
![Screen Shot 5781-05-15 at 1 38 00](https://user-images.githubusercontent.com/58882903/106068618-7fb37780-6109-11eb-9d88-b0750db791e9.jpg)

**Comment by guymass** [comment]
I think my server hangs because of too much workload. The problem is handling the streaming while it is also encoding some videos. I opened an help issue here.
https://github.com/WWBN/AVideo/issues/4457

**Comment by guymass** [comment]
Issue moved to #4457
