### ISSUE TITLE
What Could Be The Issue Here? Unable To Upload Plugins

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4458]
I am trying to upload updated plugins, the same way that I always have, and I am getting error messages each time I try. Note the images.

The process I follow is always the same:

1. I temporarily chmod the plugin folder to 777 so that I can delete the old plugins
2. I then use the plugins upload to upload zipped plugins that were downloaded forms he plugin store
3. I then go to the plugins page and "update" each plugin
4. I then change the plugin folder back to 755

This process has always worked previously, not sure why its not working this morning.

<img width="587" alt="Screen Shot 2021-01-28 at 6 32 53 AM" src="https://user-images.githubusercontent.com/7376298/106139560-36781d80-6133-11eb-87eb-5778e06784a2.png">
<img width="581" alt="Screen Shot 2021-01-28 at 6 33 15 AM" src="https://user-images.githubusercontent.com/7376298/106139578-3c6dfe80-6133-11eb-9ab7-6689d268c492.png">
<img width="588" alt="Screen Shot 2021-01-28 at 6 33 57 AM" src="https://user-images.githubusercontent.com/7376298/106139588-3ed05880-6133-11eb-91cc-72a99f64ccfd.png">
<img width="586" alt="Screen Shot 2021-01-28 at 6 34 11 AM" src="https://user-images.githubusercontent.com/7376298/106139595-409a1c00-6133-11eb-85ad-0bf587ead350.png">
<img width="591" alt="Screen Shot 2021-01-28 at 6 34 37 AM" src="https://user-images.githubusercontent.com/7376298/106139602-42fc7600-6133-11eb-8877-cea37c5c685f.png">
<img width="583" alt="Screen Shot 2021-01-28 at 6 34 52 AM" src="https://user-images.githubusercontent.com/7376298/106139613-455ed000-6133-11eb-9f7f-d72fe4cfc416.png">

**Comment by DanielnetoDotCom** [comment]
Check the log file

**Comment by bbyrdhouse** [comment]
Please tell me the path to the log file

**Comment by bbyrdhouse** [comment]
The answer to #4459 also solved this problem ... although I would still like to make a record of where the log files are stored on the server ...

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
