### ISSUE TITLE
I Get An "Aborting" Message When Trying To Do A Git Pull, Now I Get A Blank White Page

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4459]
I just now tried to do a git pull to update things and it started off ok and then ended with an Abort message.
When I go to my site now, all I get is a blank white page.

<img width="730" alt="abort" src="https://user-images.githubusercontent.com/7376298/106140766-ccf90e80-6134-11eb-86ac-55ecae68ceca.png">

**Comment by DanielnetoDotCom** [comment]
Instead of git pull, try this 

`sudo git fetch --all && sudo git reset --hard origin/master`

**Comment by bbyrdhouse** [comment]
This is what I get when I do that:
`fatal: not a git repository (or any of the parent directories): .git`

**Comment by bbyrdhouse** [comment]
this worked `cd /var/www/html/AVideo/ && sudo git fetch --all && sudo git reset --hard origin/master` or at leased it seemed to work, I suppose that you might also have done something in the background that I don't know about.

That allowed me to update both the system and the plugins
