### ISSUE TITLE
 Plugins - YouPHPFlix2 

### ISSUE THREAD

**Issue by Erreur1978** [WWBN/AVideo#4463]
I want to know how to put the autoplay video on the Plugins - YouPHPFlix2 on the first page in the background

**Comment by DanielnetoDotCom** [comment]
Check the trailer

![image](https://user-images.githubusercontent.com/18009293/106299970-a4583e00-6234-11eb-9396-a59ba8db0ce6.png)

**Comment by Erreur1978** [comment]
thx
