### ISSUE TITLE
Blockonomics YPT requires a secret and a redirect URL

### ISSUE THREAD

**Issue by iamflorencejay** [WWBN/AVideo#4466]
**Describe the question**
Blockonomics requires an API secret and a redirect URI. For some reason, I can't see the API secret for some reason.

**Screenshots**
![Screenshot_2021-01-30-21-49-19-678_com brave browser](https://user-images.githubusercontent.com/24932514/106358120-11f38f80-6345-11eb-931c-4b8dba48aba3.jpg)

**Comment by iamflorencejay** [comment]
Oh dear

**Comment by DanielnetoDotCom** [comment]
Hi, basically you only need to provide the APIKey, the secret is automatically generated
