### ISSUE TITLE
YPTSocket not connecting

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4467]
Here are screen shots from two servers on one its working and on the other it doesn't. Not sure what is causing this.

![Screen Shot 5781-05-17 at 18 23 25](https://user-images.githubusercontent.com/58882903/106362097-b23bbb00-6329-11eb-90be-841ec2ddf347.jpg)
![Screen Shot 5781-05-17 at 18 24 09](https://user-images.githubusercontent.com/58882903/106362099-b4057e80-6329-11eb-8f26-06f7ab3c4438.jpg)

**Comment by JoshWho** [comment]
I am having the same issue

**Comment by JoshWho** [comment]
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8084 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8084 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8084 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8084 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8084 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] still could not bind()

**Comment by JoshWho** [comment]
After running command 

`sudo nohup php /var/www/html/YouPHPTube/plugin/YPTSocket/server.php &`

5 times it started working. No clue y

**Comment by JoshWho** [comment]
Needs to be some kind of persistence for this that detects when it disconnects and restarts it.

**Comment by akhilleusuggo** [comment]
Works fine for me . After reboot connects automatically

**Comment by JoshWho** [comment]
It did this twice for me all ready. Guess it depends how busy your site is. I am not gonna have my server reboot everytime this script stops, needs to be some kind of service on it or something.

**Comment by akhilleusuggo** [comment]
No , you don't have to reboot . But for testing purposes I rebooted my server and works perfectly .

In fact I rebooted it 4 days ago and the sockets never dropped ; 
![image](https://user-images.githubusercontent.com/52116577/107133184-2f4cce80-68ee-11eb-95c4-c024dd41a5bc.png)
