### ISSUE TITLE
SecureVideosDirectory - Unable to get working alrternative Video Directory and Break the Main Page

### ISSUE THREAD

**Issue by albramord** [WWBN/AVideo#4469]
Hi everybody. I hope that somebody can help me.

Im trying to get full working service with Plugin SecureVideosDirectory. I followed pass to pass the tutorial. My config is as follow:

Debian 10.3
Apache2
PHP 7.4
XSendFile
MySQL

User: plataformasoberana
Domain: https://plataformasoberana.net/YouPHPTube

File: /etc/apache2/apache2.conf

`<Directory /home/plataformasoberana/public_html/YouPHPTube/>`
`    Options Indexes FollowSymLinks`
`    XSendFile on`
`    XSendFilePath /home/plataformasoberana/public_html/YouPHPTube/`
`    AllowOverride All`
`    Require all granted`
`    Order Allow,Deny`
`    Allow from All`
`</Directory>`

File: /home/plataformasoberana/public_html/YouPHPTube/.htaccess

`<IfModule mod_xsendfile.c>`
`RewriteRule    ^videos/([^!#$&'()*+,\/:;=?@[\]]+(\.(mp4|webm|m3u8|mp3|ogg)))$ view/xsendfile.php?f$`
`</IfModule>`

The destination folder is located on /raid/servicios/YouPHPTube/videos.

`sudo chown www-data:www-data videos`
`sudo chmod 755 videos & sudo chmod -R 777 videos`

This commands were done on the original and destination of symbolic link.

The symbolic link is on /home/plataformasoberana/public_html/YouPHPTube/videos and goes to /raid/servicios/YouPHPTube/videos.

I followed the config on Plugin to change the destination forlder and I gets on commands to execute on Green after press Check Button and then Save. Restarting the system the YouPHPTube main site breaks.

With developer tools on browser I saw that there are files that they could not loading because are files on this url that obviously, doesnt exists:

`https://plataformasoberana.net/raid/servicios/YouPHPTube/view/js/jquery-ui/jquery-ui.min.css`
`https://plataformasoberana.net/raid/servicios/YouPHPTube/view/bootstrap/css/bootstrap.min.css`
`https://plataformasoberana.net/raid/servicios/YouPHPTube/view/css/flagstrap/css/flags.css`

etc...

Looks like that there is a problem with Rewrite rule or some likes it, the correct URL to load that files is `https://plataformasoberana.net/YouPHPTube/view.... `and whatever, not `https://plataformasoberana.net/raid/servicios/...`.

How I make to fix the calling to that files that are on YouPHPTube folder but the SecureVideoDirectory plugin activated and configured doesnt break my website.

![YouPHPTube-error](https://user-images.githubusercontent.com/28808167/106363940-f0d27500-632b-11eb-92f7-1a812492200d.PNG).

Thanks you very much.

**Comment by DanielnetoDotCom** [comment]
Try this https://github.com/WWBN/AVideo/issues/3066#issuecomment-629240169

**Comment by albramord** [comment]
This is my current configuration.php file:

`<?php`
`$global['configurationVersion'] = 3.1;`
`$global['disableAdvancedConfigurations'] = 0;`
`$global['videoStorageLimitMinutes'] = 0;`
`$global['disableTimeFix'] = 0;`
`$global['logfile'] = '/home/plataformasoberana/public_html/YouPHPTube/videos/avideo.log';`
`if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], ``FILTER_VALIDATE_IP)) { `
`    // get the subdirectory, if exists`
`    $file = str_replace("\\", "/", __FILE__);`
`    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), $file);`
`    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;`
`}else{`
`    $global['webSiteRootURL'] = 'https://plataformasoberana.net/YouPHPTube/';`
`}`
`$global['systemRootPath'] = '/home/plataformasoberana/public_html/YouPHPTube/';`
`$global['salt'] = '6015606c59451';`
`$global['disableTimeFix'] = 0;`
`$global['enableDDOSprotection'] = 1;`
`$global['ddosMaxConnections'] = 40;`
`$global['ddosSecondTimeout'] = 5;`
`$global['strictDDOSprotection'] = 0;`
`$global['noDebug'] = 0;`
`$global['webSiteRootPath'] = '';`
`if(empty($global['webSiteRootPath'])){`
`    preg_match('/https?:\/\/[^\/]+(.*)/i', $global['webSiteRootURL'], $matches);`
`    if(!empty($matches[1])){`
`        $global['webSiteRootPath'] = $matches[1];`
`    }`
`}`
`if(empty($global['webSiteRootPath'])){`
`    die('Please configure your webSiteRootPath');`
`}`
`/**`
` * Do NOT change from here`
` */`
`require_once $global['systemRootPath'].'objects/include_config.php';`

I´ve notice that

`$global['logfile'] = '/home/plataformasoberana/public_html/YouPHPTube/videos/avideo.log';`

appoints to videos folder like original installation. Changed to

`$global['logfile'] = '/raid/servicios/YouPHPTube/videos/avideo.log';`

and restarting apache2 not works. Same result. Checking permises on videos folder, cache folder and content is root owned arent?

I forguet to tell that I have a Wordpress Multisite on the server. The sites are on folders, not subdomains. This is my .htaccess of Wordpress  Root Folder:

/home/plataformasoberana/public_html/.htaccess

`# BEGIN WordPress`
`# Las directivas (líneas) entre «BEGIN WordPress» y «END WordPress» son`
`# generadas dinámicamente y solo deberían ser modificadas mediante filtros de WordPress.`
`# Cualquier cambio en las directivas que hay entre esos marcadores serán sobrescritas.`
`RewriteEngine On`
`RewriteBase /`
`RewriteRule ^index\.php$ - [L]`
`# add a trailing slash to /wp-admin`
`RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]`
`RewriteCond %{REQUEST_FILENAME} -f [OR]`
`RewriteCond %{REQUEST_FILENAME} -d`
`RewriteRule ^ - [L]`
`RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]`
`RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]`
`RewriteRule . index.php [L]`
`# END WordPress`

The root Website is `https://plataformasoberana.net`, and the YouPHPTube service is `https://plataformasoberana.net/YouPHPTube`. Can the .htaccess on root folder (for Wordpress) with REWRITE RULES create conflict with a .htaccess within on a subfolder that not is named on root .htaccess?

Thank you.

**Comment by albramord** [comment]
A question:

If I pay the Basic Custom Plan Service on https://www.youphptube.com/services... Can they help me with my inusual installation of YouPHPTube (only I need to configure sucessfully the plugins)? Instead to make a FULL INSTALLATION on my system, only I need that my YouPHPTube folder on my apache server works fine. My server runs Debian, not Ubuntu.

**Comment by DanielnetoDotCom** [comment]
Hi, to help you with installation it must be paid by the hour. I am not sure how is your configuration, so I cannot guarantee it will work at the expected time.

In your configuration, replace this 
```

if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) {
	// get the subdirectory, if exists
	$file = str_replace("\\", "/", __FILE__);
	$subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), $file);
	$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
	$global['webSiteRootURL'] = 'https://plataformasoberana.net/YouPHPTube/';
}

```
for this 

`$global['webSiteRootURL'] = 'https://plataformasoberana.net/YouPHPTube/';`

**Comment by albramord** [comment]
I followed your instructions and now I get an Error 500 on website. I think that the key is .htaccess policy overlap.  On this week I hire 1 hour with you to help me. Thanks very much.

**Comment by DanielnetoDotCom** [comment]
I guess you edit your configuration.php wrong

**Comment by albramord** [comment]
It works!! I forget remove a } character after 
`	$global['webSiteRootURL'] = `'https://plataformasoberana.net/YouPHPTube/';`
`}`

Thanks very much. Now, how I configure the Encoder? The Main Site works but encoder doesnt encode the file. Appears upload but the encoder doesnt work.
