### ISSUE TITLE
Longer comments

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4472]
Is it possible to make comments longer than 256 chars?

![Screen Shot 5781-05-18 at 3 24 02](https://user-images.githubusercontent.com/58882903/106372003-edfb7280-6373-11eb-9b43-232ced24af8b.jpg)

**Comment by wetubeclub** [comment]
Plugin Customize Andvanced
![comments](https://user-images.githubusercontent.com/60543030/106377166-688bb880-639b-11eb-8dc6-0ce69c887db6.jpg)

**Comment by guymass** [comment]
Wow I was looking in there but totally missed it. Thanks!
