### ISSUE TITLE
How can I just show latest videos on front page? 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#4473]
I had this before, but cannot figure out how to configure this after last update.

**Comment by fakeologist** [comment]
Bump

**Comment by akhilleusuggo** [comment]
Disable everything on hallery plugin ( treding/categories/subcategories...) , leave only what you wanna show

**Comment by fakeologist** [comment]
The key is to clear the cache after every change, Clearing first page cache doesn't seem to make a difference.

**Comment by DanielnetoDotCom** [comment]
If you changed the plugin parameter, it requires you to clear the cache (Not the first page only)

**Comment by fakeologist** [comment]
Everything is fixed now thanks.
