### ISSUE TITLE
OBS cant connect to server

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4480]
Not sure what has happened and whether this has anything to do with my latest update, but now I cannot connect anymore to the server with OBS. Also my STATS page is now white, not showing the RTMP server info.
https://rtmp.ahava528.com:8443/stat

![Screen Shot 5781-05-19 at 12 09 03](https://user-images.githubusercontent.com/58882903/106445645-f644d200-6487-11eb-997e-801c230eb21b.jpg)
![Screen Shot 5781-05-19 at 12 18 57](https://user-images.githubusercontent.com/58882903/106445656-f9d85900-6487-11eb-97c6-0810156e1a7b.jpg)

Nginx logs shows only these messages:

![Screen Shot 5781-05-19 at 12 22 48](https://user-images.githubusercontent.com/58882903/106446041-73704700-6488-11eb-9106-5ede07ab481b.jpg)
![Screen Shot 5781-05-19 at 12 23 32](https://user-images.githubusercontent.com/58882903/106446050-766b3780-6488-11eb-9874-2ab6c7a8b177.jpg)

**Comment by guymass** [comment]
This is on the second server also can't connect. I am not sure if it is a local or remote issue as some are able to connect.

![Screen Shot 5781-05-19 at 16 21 29](https://user-images.githubusercontent.com/58882903/106470817-a119b800-64a9-11eb-8563-521b28da1df1.jpg)

**Comment by smartweekend** [comment]
check nginx server. seems its stopped working.. and is the privatekey for live the same?

**Comment by akhilleusuggo** [comment]
reset the stream key and clear the cache .

If the issue persists , copy/paste here your config file .

**Comment by guymass** [comment]
Sorry for late update, all has been resolved on this issue. The problem was a bad reverse proxy which was fixed.
