### ISSUE TITLE
Stream Post details are not saved

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4481]
One of my subs claimed that whenever he starts a new stream, even if he changes the stream details, tile etc... and saves, he still gets in the end of the encoding process a title of an older post he made and also his stream URL still retains the old post name. I am attaching two screenshots of the post being saved and how it actually appears after starting the stream.

![photo_2021-02-01 16 34 16](https://user-images.githubusercontent.com/58882903/106472532-703a8280-64ab-11eb-9885-0405712b7f1a.jpeg)

This is how the details appear when he shares his URL, I marked the text to show what should be changed:

![Screen Shot 5781-05-19 at 16 34 55](https://user-images.githubusercontent.com/58882903/106472635-89dbca00-64ab-11eb-9c04-cc5d032ee716.jpg)

**Comment by JoshWho** [comment]
I bet he is not clicking save after titleing his live stream.
