### ISSUE TITLE
Streaming Playlists issue duplicate streams

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4482]
Not sure how to address this. I click on a playlist I have to set the streaming and it caused a stream duplication, running the same lists on three places. Could this has anything todo with adaptive encoding?

![Screen Shot 5781-05-19 at 18 10 59](https://user-images.githubusercontent.com/58882903/106485342-2a84b680-64b9-11eb-8432-62d3b282aff7.jpg)

This is the list I was playing:

![Screen Shot 5781-05-19 at 18 13 37](https://user-images.githubusercontent.com/58882903/106485402-3bcdc300-64b9-11eb-9f6f-079fa4c168a8.jpg)

**Comment by JoshWho** [comment]
I seen that bug as well when trying to stream a playlist. Also it doesn't play the whole videos entirety seems like it keeps cutting the videos in half and always advancing to the next one.

**Comment by guymass** [comment]
Maybe it will be resolved in the next updates.
