### ISSUE TITLE
Low res only?

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#4484]
My video uploads are now encoding for all resolutions. This latest version seems to have reset many settings.
Where can I limit it to LOW res only?

**Comment by fakeologist** [comment]
I want only lowest res only. It is giving many options.
https://i.imgur.com/8dn7S0b.png

**Comment by fakeologist** [comment]
![image](https://user-images.githubusercontent.com/66537018/106544929-624e2700-64d6-11eb-8170-28b62400c2ae.png)

**Comment by akhilleusuggo** [comment]
on plugin advanced user ; I've answered your question before ;

https://github.com/WWBN/AVideo/issues/4373

Select all ( to disable ) , keep only "Show encoder resolution Low"

**Comment by fakeologist** [comment]
Ok I did this.
I uploaded a file that is 435mb.
There are 5 versions of it - and the total file size is now over 1 gig!
I only wanted the one low res version.
What am I missing?
![image](https://user-images.githubusercontent.com/66537018/106607935-d9fd6f80-6531-11eb-9056-498a37abf201.png)

**Comment by akhilleusuggo** [comment]
I just tested , and actually you're right , looks like it's bugged
