### ISSUE TITLE
Progress Bar stopped displaying

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4485]
The video upload and encoding progress bar bow look like this on the videos page throughout the entire process.

![Screen Shot 5781-05-21 at 0 01 25](https://user-images.githubusercontent.com/58882903/106668631-2a68e180-65b3-11eb-8a17-84bed700534c.jpg)

On the encoder it shows fine:

![Screen Shot 5781-05-21 at 0 01 16](https://user-images.githubusercontent.com/58882903/106668705-42d8fc00-65b3-11eb-9eea-fc357f308e6c.jpg)

**Comment by JoshWho** [comment]
Yes I can confirm this also with the latest encoder update

**Comment by DanielnetoDotCom** [comment]
Please update and try again

**Comment by guymass** [comment]
I have updated but still on video page this is what I see.

![Screen Shot 5781-06-05 at 0 07 53](https://user-images.githubusercontent.com/58882903/108127709-53f63280-70b4-11eb-8ccd-986f0edd3841.jpg)

**Comment by guymass** [comment]
Fixed!

![Screen Shot 5781-06-05 at 2 30 16](https://user-images.githubusercontent.com/58882903/108139157-24e9bc00-70c8-11eb-98ef-a8c142eb3f64.jpg)
