### ISSUE TITLE
Make Video Tab on Channel Page Default or Choosable. I want videos to show first

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4488]
I get questions all the time from new users and they ask how can they make their channel just show their videos first instead of a playlist.

I would love to be able to change the default page for it to videos if it is possible.

![ezgif-3-259edb0aeb10](https://user-images.githubusercontent.com/39392449/106702057-57b29100-65ad-11eb-8dd0-25101683d7b6.gif)

**Comment by unframeofmind** [comment]
From the perspective of new users, they'll be coming through a link expecting to see a video that was shared. Instead, what they see makes no sense from a user-interface perspective. The "about" information should be tabbed separately for those who actually want to know more about the creator of the video.

Anything that can be done to make the experience similar to YouTube interface is a huge help in retention. 

No point reinventing the wheel.

**Comment by akhilleusuggo** [comment]
@JoshWho why don't you just disable the home page ?

**Comment by JoshWho** [comment]
Not the home page we are talking each user channel on the platform.  Also yes there should be a Expand option on the description so it doesn't take the whole page

![download (2)](https://user-images.githubusercontent.com/39392449/106795367-9aad4c80-661f-11eb-98e7-73a692eb49d3.png)

**Comment by akhilleusuggo** [comment]
If you disable the home page ; videos will show first .

![image](https://user-images.githubusercontent.com/52116577/107133249-d7629780-68ee-11eb-80b1-f59d69d6763e.png)

regarding the info , I think we need a new tab called "About"

**Comment by JoshWho** [comment]
Where is that option located?

**Comment by akhilleusuggo** [comment]
I never use home page . It's bugged, it's using netflix style , not responsive at all .

![image](https://user-images.githubusercontent.com/52116577/107139254-810f4c00-6922-11eb-8375-c8ccae77bf1f.png)

**Comment by JoshWho** [comment]
Sweet got it changed.
