### ISSUE TITLE
XSS vulnerability on searchPhrase parameter

### ISSUE THREAD

**Issue by darwinit** [WWBN/AVideo#4491]
**Describe the bug**
An external vulnerability test has revealed a XSS vulnerability on the searchPhrase parameter

**To Reproduce**
1. https://[host]/channels?searchPhrase=%22%3E%3Cimg%20src=x%20onerror=alert(%271%27)%3E
2. Alert is generated in user browser appearing to be a message from our site

**Expected behavior**
XSS to be blocked

 - Browser Chrome, Edge, Safari
 - AVideo Server Version 10.2

**Comment by DanielnetoDotCom** [comment]
Thanks, here is a fix

**Comment by darwinit** [comment]
Good one! Pulled and now just produces a non-alerting error. Thanks!
