### ISSUE TITLE
CloudFlare Bot Fight Mode and Your streamer site could not be found issue

### ISSUE THREAD

**Issue by baoang** [WWBN/AVideo#4493]
**Describe the question**
As raised by quite a few AVideo users/sites that occasionally/randomly they cannot log in to the encoder sites, I also encounter this problem, and for some time. Today I seem to have find some possible reasons for reference, and I guess my findings may be of help to those who are stuck in the middle of addressing it.

I've been AVideo user for one year (and more). Originally I found nothing wrong with the platform, and I prefer to use AVideo's official Encoder sites, from encoder1 to encoder5 that have been providing stable and high-quality services. Several months ago I suddenly found that I was somewhat refused access by one of AVideo encoder sites, so I tried another one, also failed. The sites all reported something like **Sorry, we couldn't found/find your streamer site**. 

I tried several ways, including setting up my own encoder site on the same server. It's a success, but due to resource limitation, I cannot use it too often. I then searched AVideo/Encoder github issues and got several solutions, including

```
allow_url_fopen = On
allow_url_include = On
```
These solutions just don't work in my case.

Yesterday I just came across an idea, as one of the [posts](https://github.com/WWBN/AVideo/issues/2940#issuecomment-619305254) mentioned the encoder site would send request to streamer site for validation/authentication. Since my streamer site adopts CloudFlare CDN technology, I make a guess that my problem could be caused some mis-configuration of Cloudflare firewall/security setting.

After a few rounds' testing, here is my solution for those alike, who use Cloudflare and similar tech and who couldn't have the streamer sites found. Go into Cloudflare website control panel - Firewall - Tools, and disable **Bot Fight Mode**. 

I also tried disabling (in DNS section) proxied, changing **proxied** to **DNS only** for domain A/CNAME before disabling Bot Fight Mode, and it also worked.

So, in my case, the CANNOT FIND YOUR STREAMER SITE issue is related to some security measures implemented by CloudFlare. I am not a tech guru/developer, and know nothing about coding or web site scripts security. There maybe room for adjustment or improvement for AVideo/Encoder authors/team to address the bot combating issue.

**Comment by JoshWho** [comment]
Whitelisting your server Ip addresses will solve that issue in Cloudflare.
