### ISSUE TITLE
No plugins will update after last streamer update

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4494]
HI. After last streamer update none of my plug ins wants to update. I have downloaded the updated and installed it but it still says i need to upgrade... All the last plugins I cannot get upgraded. I have cleared all cache but still same issue

regards

**Comment by DanielnetoDotCom** [comment]
the ones that need to update are the paid ones?

**Comment by unconservo** [comment]
Yes the paid ones. But i ran permissions again on folders and gave www
access again. So it is working :).
