### ISSUE TITLE
Restream Is buggy after socket change - Have to start stop start a stream to make it work right

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4495]
Literally as the title says, in order for my other channels from the restream to connect I have to start a broadcast then stop it and quickly start it again in order to make it work.

Seems like when the publish triggers first the restream start waking up and then waits for a command so I have to stop and start and boom everything connects.

**Comment by akhilleusuggo** [comment]
Yeh , experiencing same issue for almost a month . Before needed to wait almost 5-10mn before starting to stream again , now is looping . ( busy restreaming nothing )

**Comment by DanielnetoDotCom** [comment]
Hi, I just sent some updates related to the restream, can you guys check if it resolves?

**Comment by JoshWho** [comment]
I think my biggest issue is it is using my encoders on my smaller server. Any way to get it to use my main dedicated for it?

**Comment by DanielnetoDotCom** [comment]
Did you try to change this?

![image](https://user-images.githubusercontent.com/18009293/108357444-33b99700-71cc-11eb-8c85-c6fe52c4e122.png)

**Comment by JoshWho** [comment]
Im not sure if that is what I am talking.  I know when people use it it is uses my 16 gig smaller net connection and not my main dedicated server with the gig net.

I want to still be able to use my other encoders for uploads but use a local encoder for the restream.

**Comment by DanielnetoDotCom** [comment]
I guess you can change only the restreamer
