### ISSUE TITLE
Install issuse

### ISSUE THREAD

**Issue by gittestin** [WWBN/AVideo#4496]
<img width="949" alt="1" src="https://user-images.githubusercontent.com/78536208/106877349-9f532d00-6713-11eb-81ca-69ed301186b6.png">
As you can see, I am using Ubantu 1.8, and everthing goes fine, just can not continue to progress.
Thank you for you help.

**Comment by JoshWho** [comment]
Check to make sure you have the correct password for your sql root account

Also make sure your mysql server is accessible and not blocked by firewall.
