### ISSUE TITLE
Problem with chromecast

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#4497]
Hi,

I noticed that chromecast doesn't work for me. It worked on demo site, but not in my site. Everything is updated and no entries on log file.  I even checked that my HLS configuration is same as on the demo site. 

Can you help with this? Is there something else that should be configured? It has worked before but I don't know when it stopped working..

the connection to chromecast works, but it doesn't show the video. I only can see the chromecast logo on TV-screen.

**Comment by tonuzo** [comment]
Mp4 works, but not HLS...

**Comment by tonuzo** [comment]
It's a bug @DanielnetoDotCom 

I noticed if a video is free, Chormecast plays it, but if it's paid content it doesn't work - even if you have purchased the video. Please, can you check this?

**Comment by KamillaPup** [comment]
I don't even see the Chromecast button the video player. Where is it?

**Comment by tonuzo** [comment]
You have to activate it from plugins.

**Comment by tonuzo** [comment]
@DanielnetoDotCom is it possible to add more log information to see whats happening on this?

**Comment by KamillaPup** [comment]
> You have to activate it from plugins.

lol c'mon I'm not that stupid. It is activated.
