### ISSUE TITLE
Meet is not pulling Avatars from channel anymore now using Gravatars 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4498]
Meeting was working fine with the channel avatar and now noticed just a day ago it is forcing the Gravatars now which sucks because a lot of people have no clue what that even is.

How to switch it back to the channel avatars?

**Comment by DanielnetoDotCom** [comment]
Please update and check again. it was a Cors issue.

**Comment by JoshWho** [comment]
Updated. Thank you
