### ISSUE TITLE
Meeting rooms now are really zoomed in and cuts off camera and u have to scroll down. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4500]
I dont know what recently has been changed but meetings now looks awful and is extremely zoomed in. 

I have to zoom out to 25% just to make the cameras fit my monitor.

![1904889e-9c9e-4b48-9e14-404ea027e6b7](https://user-images.githubusercontent.com/39392449/106978156-4be7db80-6721-11eb-86bc-f411d6821113.png)
![download (3)](https://user-images.githubusercontent.com/39392449/106978168-51ddbc80-6721-11eb-86df-201a895eae62.png)

**Comment by DanielnetoDotCom** [comment]
I did not change anything. maybe something on jitsi side.

**Comment by DanielnetoDotCom** [comment]
Does it still persist?

If you switch servers?

**Comment by JoshWho** [comment]
Yes. It is only if it is 3 to 4 windows are going. once a 5th member joins it looks fine again
