### ISSUE TITLE
H.265 MP4 videos only play audio

### ISSUE THREAD

**Issue by KamillaPup** [WWBN/AVideo#4501]
I was surprised that all the default ffmpeg encode settings use H.264. Since I'm mainly working with only 1080P and 1440P, I want to use H.265 due to better compression. I only get errors in the encoder after editing the ffmpeg string so I tried running the conversion locally then did a direct MP4 upload and only audio plays... not the video.

Does AVideo not support H.265 yet?
![image](https://user-images.githubusercontent.com/26353056/107016589-bae62400-6763-11eb-92a4-aaa7a91c9ddd.png)
![image](https://user-images.githubusercontent.com/26353056/107016755-ef59e000-6763-11eb-9c29-c3c9ccd36e0b.png)

The ffmpeg command I built using Axiom on my Windows box:

```
"C:\Program Files (x86)\Axiom\ffmpeg\bin\ffmpeg.exe" 

-y 

-hwaccel auto 

-i "M:\Furry\_furry\Movies\DJ Klubbingman - Love Message_2.00x_2560x1440_thf-4.mp4" 

-c:v libx265 
-preset fast -crf 24 
-tune animation -profile:v main10 -level 3.1 
-vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" 
-map 0:v:0? 

-c:a copy 
-map 0:a? 
-sn 

-map_chapters 0 

-map_metadata 0 

-f mp4 

-threads 4 

"M:\Furry\_furry\Movies\DJ Klubbingman - Love Message_RT.mp4"
```

**Comment by akhilleusuggo** [comment]
x265/H265 is not supported on any browser .

Related issue ; https://github.com/WWBN/AVideo/issues/3602

**Comment by KamillaPup** [comment]
Woooow I'm an idiot haha. Thank you.

I'm trying to figure out the best settings for 2K video that won't upscale 1080P video.

**Comment by KamillaPup** [comment]
Because I hate it when someone says they found a solution without posting it, I wanted it to share with everyone.

So if you don't have any paid plugins and you need stuff to work in the best quality possible, mobile users be damned, here's what do.

In encoder, change MP4 HD to this
`ffmpeg -i {$pathFileName} -c:a copy -bsf:a aac_adtstoasc -c:v libx264 -crf 28 -preset fast -movflags +faststart -strict -2 -max_muxing_queue_size 1024 -y {$destinationFile}`
Now make sure ONLY HD is selected.

Convert! That's it. The resolution of the video you upload will not change the size stays small for the most part. Also the audio stream is passed through and isn't reconverted. I'm doing it that way because I know that the stream is indeed AAC. No need to reconvert it.

On my server, it takes about 2 minutes to convert a 5 minute video. Not bad at all! And the quality is nice.
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/26353056/107111716-c135d800-6817-11eb-9014-a577d3a3e741.png">

**Comment by akhilleusuggo** [comment]
@KamillaPup You can also limit the max resolution ( don't confuse it with resizing ) . What I'm suggesting is a hard limiter .

If your hard limiter is 1080p ( for example ) ;
1- and if the video uploaded is 720 ; No resize applied .
2- if the video uploaded is 4K ; will resize to 1080 since it's the limit by the encoder .


The traditional way , will resize to 1080p whatever is a 240p or 4k .

`-c:v libx264 -crf 28 -preset fast` crf 28 is too low . Also preset fast is not a good choice when going with low constant rate factor.
crf 23 is the default . Balanced I would say .

I'm saying this based on your answer ; 

> you need stuff to work in the best quality possible
