### ISSUE TITLE
adaptive streaming not showing quality selector

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4504]
As the title describes . The quality selection now showing , but the quality is changing depending on the bandwidth .

HLS plugin ;

![image](https://user-images.githubusercontent.com/52116577/107034854-fa425e00-67bf-11eb-87ae-fe8a16826845.png)

Live Plugin 

![image](https://user-images.githubusercontent.com/52116577/107034903-0c240100-67c0-11eb-832e-c42bf2902242.png)

Console ; 

![image](https://user-images.githubusercontent.com/52116577/107035170-6ae97a80-67c0-11eb-9f82-03e14be5840f.png)

On HLS directory I have an m3u8 ( witch I don't remember was there before ) . Maybe standing for automatic quality detection , but doesn't allow to select . I'm transcoding only to 2 resolutions ;

![image](https://user-images.githubusercontent.com/52116577/107036007-a173c500-67c1-11eb-9619-a9423a577c66.png)

Cat : 

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=900000
601d3948d570f_low/index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3500000
601d3948d570f_hi/index.m3u8
```

**Comment by abed-ahmed** [comment]
I want to explain how adaptive broadcast works ؟؟
