### ISSUE TITLE
Live User Count is not very accurate 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4506]
Seems like it works when u first join the live video u see the number go up but after a few minutes goes by your number goes away. No heartbeat is keeping it counted.

**Comment by JoshWho** [comment]
Maybe a new way of counting would be not the video page but the chat maybe instead.

**Comment by DanielnetoDotCom** [comment]
Hi, are you using sockets?

if yes, it should be precise.

**Comment by JoshWho** [comment]
Yes i am  using the sockets. Not sure what it is. Maybe some browsers do not register the java heartbeat

**Comment by DanielnetoDotCom** [comment]
Can you please check if you have the on_publish_done in your nginx.conf?

https://github.com/WWBN/AVideo/blob/02ea4700552dbf888beb0eabf76376e5c8ddf27c/plugin/Live/install/nginx.conf#L22
