### ISSUE TITLE
encoder not encoding videos longer than 5min

### ISSUE THREAD

**Issue by daoguey** [WWBN/AVideo#4507]
my VM is 48gb 6 core 170gb (90% free space)

It starts and all fine, then i go to my website and i see nothing just the images created and EE:EE:EE:EE under storage and nothing moves. this is odd, as this used to not happen whtn i had 3.2v with encoder in 3.4 seems to have broken something. Nothing has changed in my setup except the update that has broken my encoding. This is only in HLS with this setup:

-c:v h264 -vf scale=-2:{$resolution} -r 24 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -minrate {$minrate}k -crf 23 -maxrate {$maxrate}k -bufsize {$bufsize}k -c:a aac -b:a {$autioBitrate}k -f hls -hls_time 6 -hls_list_size 0 -hls_key_info_file {$destinationFile}keyinfo {$destinationFile}res{$resolution}/index.m3u8

![image](https://user-images.githubusercontent.com/15695109/107103437-db9d9080-67da-11eb-93ca-501f99c167a5.png)

**Comment by akhilleusuggo** [comment]
man , we can't help you with a screenshot that we can't even fully see .

Copy/past the logs here ( the full lines )

`ERROR, File (/var/.... ) `  Is the information required and the screenshot doesn't show it .

**Comment by baoang** [comment]
guess you need modify max_upload_var(s) and etc. in your php.ini?

**Comment by daoguey** [comment]
@baoang  yeah that was setup since the beginning so in the process of updating the encoder it stopped working. 
@akhilleusuggo the image if you clock on it i can read it and see it, i am not sure what you mean.
