### ISSUE TITLE
email setup with google

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4508]
Hi i have trobble with the setup with a google account.
So i have setup the emailsending with ssl port 465 username=goggle email and a app password.
The server is smtp.gmail.com

The first try is ok, it say ok and the testmessage was send.
I save my config and try again to send a testmessage, but there is coming a

(SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting)

So what why ? the testmessage was send on the first try but not later.
When i send a message to all users its the same error.

**Comment by akhilleusuggo** [comment]
try port 587 tsl

And confirm your server ( if google has detected abnormal activities based on the IP , actually it should ) .

**Comment by 01123581321345589144233** [comment]
i have also try port 587 but its the same

**Comment by 01123581321345589144233** [comment]
ok i have dropet the config eith google ist working with my own email server.
