### ISSUE TITLE
API uploaded videos to B2 question

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#4511]
Hi,

when a video is uploaded via the api, it is transferred to the videos folder as original_$filename.

The B2 plugin then transfers the file to backblaze

What happens to the original_ file? is it automatically deleted after a period of time?

or do we need to setup a cron job to delete these every night?

**Comment by DanielnetoDotCom** [comment]
it is uploaded to B2 with the same file name it would be on the streamer.
note the streamer file is a 10 bytes file, it is just a dummy file, do not delete it.

**Comment by millzee01** [comment]
hmm,

if I upload a file called "anim2.webm"

The dummy file gets created fine as normal, and it's transferred to b2 fine.

however what i'm left with in the video folder is::
original_anim2webm_YPTuniqid_60227395c8de16.46474578

At the end of the transfer process, shouldn't original_anim2webm_YPTuniqid_60227395c8de16.46474578 be deleted?

**Comment by DanielnetoDotCom** [comment]
Is it on the encoder or direct upload?
