### ISSUE TITLE
file title - ex. Empty Title on 28-Jan-21-12:58:48

### ISSUE THREAD

**Issue by awistudio** [WWBN/AVideo#4512]
Empty Title on 28-Jan-21-12:58:48

where to delete "on"
Empty Title - 28-Jan-21-12:58:48

please help

**Comment by awistudio** [comment]
it is about automatic saving of the stream

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/blob/780097472d034d1cb8c145c9176f946bede37162/plugin/Live/install/nginx.conf#L37

**Comment by awistudio** [comment]
this is just a date format
 record_suffix -%d.%m.%Y-%T.flv;

I just want to delete "on"
Empty Title "xxxxxon" 28-Jan-21-12:58:48

eg
my title - date

**Comment by akhilleusuggo** [comment]
I cant check it right now , but i bet its hard coded on the plugin side

**Comment by DanielnetoDotCom** [comment]
Are you running SendRecordedToEncoder version 2.1?
I just checked into the code and it supposes to have the "on" on the title

**Comment by awistudio** [comment]
Yes
 SendRecordedToEncoder version 2.1

so how can i change it?

**Comment by DanielnetoDotCom** [comment]
It is hardcoded, sorry
