### ISSUE TITLE
Notification Plugin test fails

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4513]
**Describe the bug**
The test is not working
I have addet the logo.

**To Reproduce**
1. i go to the plugin config and try a test
2. string(0) ""  is the reply in the webbrowser

**Comment by DanielnetoDotCom** [comment]
Make sure you setup OneSignal

https://github.com/WWBN/AVideo/wiki/Notifications-Plugin#onesignal
