### ISSUE TITLE
Packagist Registration.

### ISSUE THREAD

**Issue by Maikuolan** [WWBN/AVideo#4516]
So, considering that AVideo now has Composer support, but hadn't yet been submitted to Packagist, I've [submitted it now](https://packagist.org/packages/wwbn/avideo), so that AVideo can now be easily found by Composer (beforehand, I searched Packagist for "AVideo", "WWBN", "YouPHPTube", etc; could not find anything related registered yet, so I'm reasonably certain, nobody has tried registering it yet).

@DanielnetoDotCom If you, or anyone else at WWBN, has an account with Packagist, please let me know which usernames, so that I can list those usernames as the maintainers for the package, and delist myself (Packagist automatically lists whoever submits the package as the maintainer, but it would be better to list the real maintainers instead). Cheers. :-)

**Comment by DanielnetoDotCom** [comment]
Sorry for the late reply, I am traveling, I will take a deeper look at that when I come back
