### ISSUE TITLE
Playlist play live stops

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4517]
Hi, i have startet a playlist to steram live, so it starts and the stream is also recorded in the tmp folder.
But after 1 minute the live icon on the start page are not shown anymore.
When i start over, the stream starts over but the live icon on the startpage are not shown.
And how can i stop the live play list stream ?

**Comment by 01123581321345589144233** [comment]
so after i have startover the playlist livestream the nginx take huge ram on my server, i have stopet the nginx and startet again. But is stille the same

**Comment by JoshWho** [comment]
It is still in beta stage at the moment and has some bugs that need to be ironed out before using it in live production.

**Comment by 01123581321345589144233** [comment]
ok how cn i disable this for my users ?

**Comment by JoshWho** [comment]
GO into the Programs plugin and disable show live

**Comment by 01123581321345589144233** [comment]
ok thanks
