### ISSUE TITLE
Annoying bug in Chat2

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4518]
When trying to type RTL the text will continue to go off screen and cut it so I cannot see what I am typing anymore.

TextArea should be either dynamic or larger or the text should continue to next line.

![Screen Shot 5781-05-25 at 15 48 18](https://user-images.githubusercontent.com/58882903/107148561-88534b80-695c-11eb-9186-fd809535da63.jpg)

**Comment by JoshWho** [comment]
that sucks you have to write backwards in your lang. It would have to be a completely different design for it to work right.

**Comment by guymass** [comment]
Yeah, much of this script is not considering the RTL side of this world which also includes Arabic.
