### ISSUE TITLE
encoder remember login

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#4523]
Last big update removed remember me on encoder login.
Can we get  this back?
![image](https://user-images.githubusercontent.com/66537018/107233934-1da01f80-69f1-11eb-993a-ce0941eb3201.png)

**Comment by DanielnetoDotCom** [comment]
Hi, we never had the remember me on the encoder, only on the streamer.

**Comment by fakeologist** [comment]
Can it be added?

**Comment by DanielnetoDotCom** [comment]
It can be added in the future, right now it is not on the road yet
