### ISSUE TITLE
AVideo question

### ISSUE THREAD

**Issue by Erreur1978** [WWBN/AVideo#4524]
can you put more than 50 in the side?

![blabla](https://user-images.githubusercontent.com/49293735/107237220-80df8100-69f4-11eb-9c48-aa5e17e34dc8.png)

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/108082113-7bb3af00-7050-11eb-88e2-ed8c907a4935.png)
