### ISSUE TITLE
Stream Play List requesting Encoder version 3.2

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4525]
I am receiving this message when trying to stream a play list. This was working before and my encoder version is >3.2
I am all updated and don't see any issues on the site.

![Screen Shot 5781-05-26 at 17 33 52](https://user-images.githubusercontent.com/58882903/107242300-7fce4400-6a34-11eb-81af-1fef851c7952.jpg)

**Comment by DanielnetoDotCom** [comment]
This feature still in beta, it is not ready yet
