### ISSUE TITLE
Video Resolution Switcher not work on Programs/Series

### ISSUE THREAD

**Issue by lerd2805** [WWBN/AVideo#4527]
**Describe the bug**
I made a playlist and generated a series from it when I click to play it sent me to the playlist page but the player that appears there does not have to change the video resolutions

**To Reproduce**
1. Go to 'dremax.tv'
2. Click on 'DAKAR 2021 - Completo'
3. Video player dont have Video Resolution Switcher icon

**Expected behavior**
Enable changing resolutions in the playlist series player.

Playlist/Series
![image](https://user-images.githubusercontent.com/31492754/107259162-ad9e9300-6a0a-11eb-8267-6f5bf2ded02b.png)

Another video in home page
![image](https://user-images.githubusercontent.com/31492754/107259409-f3f3f200-6a0a-11eb-9c27-6eb1f2b94ee4.png)

**Comment by lerd2805** [comment]
Any solution for this? 

Could you check if the subtitle switcher works in the playlist / series? I already have bought both plugins and I'm starting with the site but I don't know if, as with the resolution switcher, it doesn't work in this player too

**Comment by DanielnetoDotCom** [comment]
Hi, 

to make sure all your player features works you MUST make sure the page refresh on every movie, try to check this

![image](https://user-images.githubusercontent.com/18009293/108071405-76e8fe00-7044-11eb-8b04-674e3b0e2c72.png)

**Comment by DanielnetoDotCom** [comment]
I just sent some updates to the plugin and streamer. 

the resolution should work in all cases.

**Comment by lerd2805** [comment]
Awesome @DanielnetoDotCom thanks for the updates.
