### ISSUE TITLE
Video only plays with window focused.

### ISSUE THREAD

**Issue by muramasatheninja** [WWBN/AVideo#4528]
Video only plays with the window is focused and not in the background. Tried in both Chrome and Firefox on the desktop. Basically i hit play, I then select another window and the video automatically pauses. Doesn't do it in picture-in-picture mode. I'm pretty sure this worked before, and am wondering what settings to check that could affect this.

**Comment by JoshWho** [comment]
Most browsers are now doing that. Not sure much can be done about this unless it is a app u can control.

**Comment by muramasatheninja** [comment]
I don't think it's the browser in this case. At least on firefox I have autoplay enabled for my site which doesn't seem to make a difference. It also doesn't affect my playing youtube or odysse.
