### ISSUE TITLE
Encoder adding slashes when using hyphen in RTL

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4529]
At time when we use the ' - hyphen in Hebrew like so: אג'נדה the word will become something like אג'\\\\\נדה

as in the following screen shot.
![Screen Shot 5781-05-27 at 2 50 25](https://user-images.githubusercontent.com/58882903/107300302-ecbbfb00-6a81-11eb-8c3c-71463b961060.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, I found a bug, I fixed it but you will need to save the user again. I mean fix it manually and save your profile again.

**Comment by guymass** [comment]
OK thank you I will save the profile again and hopefully this will be resolved.
