### ISSUE TITLE
Youtube-dl

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4531]
Now i seems the feature are nice to have.
I have posted a other post here it will not work, the import direktly from the server disk.

So i have try the again and it works with one video, so i download the video with 
# cd /playlist
# youtube-dl url to the video
# ls video.mp4

so now i go to the gui and make a direktly import from the disk.
I can find the video and make the import.
So the video are importet and i can find the video in my video list.
But the video are not encoded and i have only one resolution, this from the original video.
But it plays and its listet online.

Are there any other there can try this ?

**Comment by DanielnetoDotCom** [comment]
youtube-dl is already on the encoder
