### ISSUE TITLE
Add different resolutions after upload?

### ISSUE THREAD

**Issue by KamillaPup** [WWBN/AVideo#4533]
To get around the lowest resolution automatically streaming, I started encoding ONLY HD versions but then after realizing how great this script is, I invested in VideoResolutionSwitcher. Unfortunately, now I need to add lower bitrates to switch between. I went to the videos folder and ran ffmpeg manually to transcode the video to SD and Low. In example:
`ffmpeg -i _YPTuniqid_601caf30a18d98.43710484_HD.mp4 -vf scale=-2:480 -movflags +faststart -preset veryfast -vcodec h264 -acodec aac -strict -2 -max_muxing_queue_size 1024 -y _YPTuniqid_601caf30a18d98.43710484_SD.mp4`
I checked the mysql database and it only references _YPTuniqid_601caf30a18d98.43710484 as the filename. So I thought it would detect the other resolutions.

(When I first encoded all variants, I saw I could just delete the other resolutions and it wouldn't break anything)

So now I have:
_YPTuniqid_601caf30a18d98.43710484_HD.mp4 (source, 2K)
_YPTuniqid_601caf30a18d98.43710484_SD.mp4 (720P)
_YPTuniqid_601caf30a18d98.43710484_Low.mp4 (480P)

I made sure they have the same permissions and owner as the other files. But I still don't see the video switcher
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/26353056/107404769-39c4bf00-6acc-11eb-86c9-cd4ad68f21b1.png">

I would test it with a whole new video, but my encoder isn't working now, as posted here. https://github.com/WWBN/AVideo-Encoder/issues/336

Thank you all! <3

**Comment by KamillaPup** [comment]
Okay I think I got it. I had to change to the default player skin. But shouldn't all player skins work? Leaving issue open due to this.

**Comment by DanielnetoDotCom** [comment]
Do you have the VideoResolutionSwitcher plugin?
