### ISSUE TITLE
Mobile view video dashboard does not show time stamps

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4534]
Any way to include time stamp view on mobile?
Desktop
![1c2280fa-22a1-4168-9aab-5f6b05a85318 (1)](https://user-images.githubusercontent.com/39392449/107413011-dd669d00-6ad5-11eb-9a94-ca117299dfe4.png)
Mobile
![Screenshot_2021-02-09-13-14-18](https://user-images.githubusercontent.com/39392449/107413028-e2c3e780-6ad5-11eb-999a-bc7583c44f38.png)

**Comment by DanielnetoDotCom** [comment]
What about this ?
![image](https://user-images.githubusercontent.com/18009293/108078849-eb279f80-704c-11eb-9c32-2ab9cb2cf14a.png)
