### ISSUE TITLE
Unable to Stream To AVideo Site After a Two Week Break from Streaming

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4535]
I Haven't done a live stream for a couple of weeks now and I just tried out a live stream to make sure everything is still working properly before I do a stream tomorrow.

My site is not receiving a stream. I have tried using 4 different software (ecammLive, mimoLive, Wirecast, & OBS) and each one is telling me that they can not stream to this site.

I can stream to all other platforms and two weeks ago I was streaming to my site as well with no issues.

I can stream to Restream.io and even they are not able to stream to the site.

I suspect that a port might be closed, but I do not know ... I am not really sure where to begin troubleshooting. The only thing I have done to the site in the last two weeks is a git pull to update the site and plugins.

I don't really know if this is a bug or user error, any guidance would be greatly appreciated.

**Error Logs**
Attached are the error logs from AVideo/videos/avideo.log

[avideo.log.zip](https://github.com/WWBN/AVideo/files/5953805/avideo.log.zip)

Here is the last line from the log
`[09-Feb-2021 13:20:21 America/Chicago] AVideoLog::ERROR: Live::getStatsObject RTMP Server (https://thepatriot.network:8443/stat) is OFFLINE, timeout=(2) we could not connect on it => live_servers_id = (0)  SCRIPT_NAME: /plugin/Live/stats.json.php`

**Comment by DanielnetoDotCom** [comment]
can you please run this in your terminal?

`sudo /usr/local/nginx/sbin/nginx`

this will start your live server that looks like is stopped

**Comment by bbyrdhouse** [comment]
Looks like that did the trick ... thnx
