### ISSUE TITLE
User Advertisement on Avideo Site

### ISSUE THREAD

**Issue by rielcomms** [WWBN/AVideo#4536]
Is there a way for users to submit their own Advertisement Video and files same way they can do on youtube on Avideo? if yes, what rights should users be assigned to have that or which pluggins can do that? The AD server is enable but users dont see it
Thanks

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Ad-Server-Plugin#how-to-use-the-plugin
