### ISSUE TITLE
category filter 

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4537]
i to all, sems like the category filter in the video user page are not workeing
I have more categorys and will filter them so i can search a video but when i click on a filter the site reloads but its not filtered

**Comment by DanielnetoDotCom** [comment]
can you please screenshot what you mean?

**Comment by 01123581321345589144233** [comment]
![Bildschirmfoto 2021-02-11 um 11 11 28](https://user-images.githubusercontent.com/31387258/107623618-e84a3a80-6c59-11eb-98a3-601c85e0e8de.png)

**Comment by 01123581321345589144233** [comment]
also the status are not working

**Comment by DanielnetoDotCom** [comment]
This is not a filter, this is a bulk update, you can check all the videos you want to change the property and they will be updated
