### ISSUE TITLE
Plugin page takes FOREVER to load

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4543]
My plugin page takes forever to load. I have 4 instances of the streamer on 4 different servers and all are taking forever to load when and if the do.

Steps
1. Login
2. Click plugins
3. Enters plugins
4. Page says "loading" for minutes and minutes
or 
1. Enter pluging
2. Activate/deactivate/save settings
3. Page says "loading" for minutes and minutes

One site is up to date the other ones are not far behind but the response is all the same.

@DanielnetoDotCom @akhilleusuggo please assist.

Thanks

**Comment by DanielnetoDotCom** [comment]
check your log files

**Comment by mrgodgiven** [comment]
same here and my encorder even stopped importing youtube videos after upgrading.

**Comment by DanielnetoDotCom** [comment]
can you please check if the plugins page still having problems loading?

if does check the logs.

regarding the encoder please check the logs and open a new issue.

**Comment by jengajenga** [comment]
> same here and my encorder even stopped importing youtube videos after upgrading.

I thought I was doing something wrong with installation! I'm glad to see it's not me only. 
The logs don't say anything AT ALL about the refusal to import.

**Comment by DanielnetoDotCom** [comment]
I have sent an update to the encoder, please check it

**Comment by jengajenga** [comment]
i can confirm it is working fine at least on my end.
