### ISSUE TITLE
Don`t run Docker of AVideo

### ISSUE THREAD

**Issue by pirri87** [WWBN/AVideo#4545]
**Describe the question**
I tried to use AVideo with docker but it isn't run. I fixed 3 thing but now I'm stucking.

Fixed:

    When executing it I get the error that you did not make the folder "/var/www/avideo/videos" and therefore I created the folder "/var/www/avideo/videos"
    git diff
    --- a/Dockerfile
    +++ b/Dockerfile
    @@ -33,6 +33,7 @@ RUN apt-get -y -f install php7.4 php7.4-common php7.4-cli php7.4-json php7.4-mbs
     
     COPY  . /var/www/avideo
     WORKDIR /var/www/avideo
    +WORKDIR /var/www/avideo/videos
     
     # Set Permision
     RUN chown www-data:www-data /var/www/avideo/videos && chmod 755 /var/www/avideo/videos

    Changed post_max_size is 8M to post_max_size is 100M (Changed manually in the file of docker when is running)
    Changed upload_max_filesize is 2M to upload_max_filesize is 100M (Changed manually in the file of docker when is running)

Now the check list is green but pushed te botom "install now" and it's not working.
**Screenshots**
![AVideo](https://user-images.githubusercontent.com/67344887/107756943-d382ab00-6d1c-11eb-9fc2-33f060cecf72.png)
Questión:
- Is it the correct channel to put my improvements and my doubt? I ask it because until it doesn't work properly I don't consider it a fix.
- Could you help me with the image error? I don't know what file it refers to or I can't find the error in more detail.

P.S. I am new to github and sorry if the formatting is wrong or I tagged it wrong.

**Comment by yegnev** [comment]
I have the same issue... Installed using "sudo docker-compose up --build -d"

I made the suggested fix to the Dockerfile, but still get a "404 page not found" when I try to access the avideo server.  https://servername/.

**Comment by pirri87** [comment]
I'm honestly at the same point as you and I don't know how to move forward.
Hope someone helps us.

**Comment by yegnev** [comment]
Please try changing the "Database Host" to point to avideo_db and use "root" for Database username and Database password respectively.

**Comment by pirri87** [comment]
I tried but it doesn't work, in "Database Host" for trying I put 172.20.0.3, 0.0.0.0 and localhost. If I use 172 .20.0.3 I get this error "Connect Error (2002) php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"
P.S. Sorry for taking time to respond, I did not realize that you had responded and thank you for your help.
