### ISSUE TITLE
Encorder failes to import youtube videos after upgrade, it fails even to upload.

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#4548]
greetings. I just upgraded and my encorder stopped importing youtube videos and to upload as well

**Comment by jengajenga** [comment]
mine too. i installed it almost 5 times thinking i was doing something wrong. i hope @DanielnetoDotCom will look into this.

**Comment by DanielnetoDotCom** [comment]
check the log files

**Comment by DanielnetoDotCom** [comment]
I have sent an update to the encoder, please check it

**Comment by jengajenga** [comment]
Sorry Dan but the logs really don't say anything specific about the encoder. It captures everything else apart from that specific issue of not importing videos.

Let me install the commit and I'll let you know.

**Comment by DanielnetoDotCom** [comment]
Just make a git pull and you should be fine
