### ISSUE TITLE
Import CSV User list into database

### ISSUE THREAD

**Issue by fxp66** [WWBN/AVideo#4550]
Is it possible to import a list of users e.g. csv-file into the database within the admin panel?

**Comment by DanielnetoDotCom** [comment]
You probably need to build a code for that

**Comment by fxp66** [comment]
ok, that´s simple, but maybe this would be a nice-to-have.
Thanks for quick response.

**Comment by joho1968** [comment]
@fxp66 Did you make any progress with writing code to handle this?
