### ISSUE TITLE
How to shorten live stream delay?

### ISSUE THREAD

**Issue by smartweekend** [WWBN/AVideo#4553]
How to shorten live stream delay.   as it takes from 30sec to 1min
?

**Comment by akhilleusuggo** [comment]
You should take a look on the git repository of rtmp nginx

**Comment by smartweekend** [comment]
Thanks..  and @DanielnetoDotCom Have u thinked about the sub zero seconds rtmp streaming delay and forking and integrating into this project? - seems vey promissing..  story: https://www.airensoft.com/post/review-ome-russia
and github: https://github.com/AirenSoft/OvenMediaEngine/

**Comment by DanielnetoDotCom** [comment]
This project seems to be really good but seems like do not have many adepts 

Nginx RTMP seems to be a lot more popular, must be a reason for that

![image](https://user-images.githubusercontent.com/18009293/108347864-d28bc680-71bf-11eb-846f-cb9dd01438c0.png)

**Comment by smartweekend** [comment]
who knows, maybe it's so good coded, that no more updates are needed ;-) if it's only an engine, like nginx - what to code more...
