### ISSUE TITLE
Default search only searches titles and tags but not description (as designed?)

### ISSUE THREAD

**Issue by KamillaPup** [WWBN/AVideo#4555]
So I'm having no real problems with AVideo since i bought a couple plugins and everything is working great. My mild annoyance is that the search seems to only search in titles and tags.

Is this as designed? Is the LiveSearch plugin required to search in descriptions too?

**Comment by akhilleusuggo** [comment]
The problem with the latest updates , is that when you search on myvideos section to monitor videos , does also pick what is written on description . This is ofc simple and easy when you have a site with few videos , but you starting to have +1000 videos it becomes almost impossible to find the video youre looking for , specially if you have a template for default description , will pull all videos with word "a" , "and" and all common used words . Doest follow phrases's order .

**Comment by DanielnetoDotCom** [comment]
@KamillaPup the search searches in multiple places. can you please give samples of what are you searching for and where is the expected word (title, description, category, tags, etc)?
