### ISSUE TITLE
AVideo mobile app

### ISSUE THREAD

**Issue by fxp66** [WWBN/AVideo#4556]
I have downloaded install the mobile app and it is working well with the tutorial site. Logged in to my treamer works, but no videos are shown.
Mobile plugin is activated, so do i miss any further configuration?
Thx for reply

**Comment by DanielnetoDotCom** [comment]
Hi, make sure your streamer is up to date and also the API plugin is enabled.

**Comment by fxp66** [comment]
I'm running vers. 10.1, after active the API plugin everthing is running well. Is it possible to brand the mobile app and to change predefined URL of the streamer?
Thx for quick reply

**Comment by DanielnetoDotCom** [comment]
Yes, you can have your own mobile app here https://www.youphptube.com/mobile/

You also should update to ver 10.2

**Comment by fxp66** [comment]
Thank you!
