### ISSUE TITLE
encoder configuration menu not showing 

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4557]
Hi hi. I logged into the encoder with admin user (same as streamer site) but only getting Sharing Queue and Queue log. Im not seeing the Configuration menu or Advanced. 

How can I see who is admin on the encoder site?. Is it not the same admin user on the streamer site?

**Comment by baoang** [comment]
I've encountered this situation, but when I git pulled the latest update, that was addressed. Guess you can try this.

**Comment by unconservo** [comment]
All streamers and encoders up to date. I reinstalled the encoder and it is now fixed :). Weird. Thank you for the response.
