### ISSUE TITLE
Search not working 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#4558]
I've tried simple searches for "Chris Sky" on my site Fakeotube.com and find nothing.

I do a search via qwant and find everything.

Try for yourself

**Comment by TLCReuver** [comment]
Since 10.0 the search function doesn't find often no hits also with simple requests like 'car' 'vroeger' 'sport' etc.

I have decided to stay on 10.0 and don't update anymore on the main_server.  Seperate from the main_server i do updates on a local_server and i confirm that the bug still exist.

**Comment by DanielnetoDotCom** [comment]
> Chris Sky

Is it a video title? the search should work even better now.

**Comment by fakeologist** [comment]
Works well now thanks.

**Comment by TLCReuver** [comment]
![Snap3](https://user-images.githubusercontent.com/39981177/108367590-e5bb8800-71f9-11eb-8d4f-9e22e2023bb3.jpg)

I tried to find the words injection, invest, rilling or sleeve but **FakeOTube** says here "This video is not available".

https://fakeotube.com/video/3003/%F0%9F%92%89-must-watch-%F0%9F%92%89
![Snap4](https://user-images.githubusercontent.com/39981177/108368375-a7729880-71fa-11eb-8a2d-0761d2692370.jpg)

**Comment by fakeologist** [comment]
I clicked on the link and got the video.

**Comment by TLCReuver** [comment]
The link works and the video is playing but finding the words in that video (injection, invest, rilling or sleeve) can't be found in the searchbar. Did you try to search for these words ? because i couldn't find the videos for these words in your searchbar @ your site
.

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by TLCReuver** [comment]
It is working perfect now, many thankz.
