### ISSUE TITLE
Successful install?

### ISSUE THREAD

**Issue by DCIPRO** [WWBN/AVideo#4559]
Upon presumably successful install on a local test site, the message to remove install directory pops up and then I click "go to the main page" and get errors. What am I missing here?

![image](https://user-images.githubusercontent.com/10525171/107886629-f94fb180-6ece-11eb-976e-fb7c13ddb959.png)

**Comment by DanielnetoDotCom** [comment]
We do not support windows.

**Comment by DCIPRO** [comment]
Makes sense, will do a linux install.

Thank you!

**Comment by DCIPRO** [comment]
Thank you!
