### ISSUE TITLE
Send Recorder Plugin, Meet Plugin &Restream

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#4561]
I have some questions

1. Why does Send Recorder split the videos when it is over an hour and 30 minutes?
2. Can each user change the login of their channel within Meet Plugin?
3. Restream: It is not connecting to the channels to stream to. Is it something wrong?

**Comment by jengajenga** [comment]
> I have some questions
> 
> 1. Why does Send Recorder split the videos when it is over an hour and 30 minutes?
> 2. Can each user change the login of their channel within Meet Plugin?
> 3. Restream: It is not connecting to the channels to stream to. Is it something wrong?

I can help with question 1. It is because it is set that way in the .conf file. You can change it from 2gb to whatever other size you so wish.

For 2 and 3, I currently haven't used those functions so i cannot say.

**Comment by CROSSMediaNet** [comment]
> > I have some questions
> > 
> > 1. Why does Send Recorder split the videos when it is over an hour and 30 minutes?
> > 2. Can each user change the login of their channel within Meet Plugin?
> > 3. Restream: It is not connecting to the channels to stream to. Is it something wrong?
> 
> I can help with question 1. It is because it is set that way in the .conf file. You can change it from 2gb to whatever other size you so wish.
> 
> For 2 and 3, I currently haven't used those functions so i cannot say.

Okay...for question 1: How to access it from the server so I can change it? The server is remote and I can access it with the right code to access it to change the file

**Comment by jengajenga** [comment]
> > > I have some questions
> > > 
> > > 1. Why does Send Recorder split the videos when it is over an hour and 30 minutes?
> > > 2. Can each user change the login of their channel within Meet Plugin?
> > > 3. Restream: It is not connecting to the channels to stream to. Is it something wrong?
> > 
> > 
> > I can help with question 1. It is because it is set that way in the .conf file. You can change it from 2gb to whatever other size you so wish.
> > For 2 and 3, I currently haven't used those functions so i cannot say.
> 
> Okay...for question 1: How to access it from the server so I can change it? The server is remote and I can access it with the right code to access it to change the file

if you have ssh to your server, or cpanel access, usr/local/nginx/conf/nginx.conf and make the changes.

**Comment by DanielnetoDotCom** [comment]
> 1. Why does Send Recorder split the videos when it is over an hour and 30 minutes?

You can increase the file size limit on nginx.conf
Change the parameter **record_max_size** on the file ` /usr/local/nginx/conf/nginx.conf`

> 2. Can each user change the login of their channel within Meet Plugin?

What do you mean?

> 3. Restream: It is not connecting to the channels to stream to. Is it something wrong?

You must check the logs and give more details about what you are doing

**Comment by CROSSMediaNet** [comment]
> > 1. Why does Send Recorder split the videos when it is over an hour and 30 minutes?
> 
> You can increase the file size limit on nginx.conf
> Change the parameter **record_max_size** on the file ` /usr/local/nginx/conf/nginx.conf`
> 
> > 1. Can each user change the login of their channel within Meet Plugin?
> 
> What do you mean?
> 
> > 1. Restream: It is not connecting to the channels to stream to. Is it something wrong?
> 
> You must check the logs and give more details about what you are doing

Okay...I will need to know where to get the logs to see the issues with the Restream, that is why it is a broad question. Secondly, most of my clients what to know to change the logo within Meet to make their channels unique. If it is possible, show me where that any user can change it.

**Comment by CROSSMediaNet** [comment]
> > > 1. Why does Send Recorder split the videos when it is over an hour and 30 minutes?
> > 
> > 
> > You can increase the file size limit on nginx.conf
> > Change the parameter **record_max_size** on the file ` /usr/local/nginx/conf/nginx.conf`
> > > 1. Can each user change the login of their channel within Meet Plugin?
> > 
> > 
> > What do you mean?
> > > 1. Restream: It is not connecting to the channels to stream to. Is it something wrong?
> > 
> > 
> > You must check the logs and give more details about what you are doing
> 
> Okay...I will need to know where to get the logs to see the issues with the Restream, that is why it is a broad question. Secondly, most of my clients what to know to change the logo within Meet to make their channels unique. If it is possible, show me where that any user can change it.

Also, Permission was denied when I try to access the file /usr/local/nginx/conf/nginx.conf to change the parameter

**Comment by CROSSMediaNet** [comment]
I am still having issues accessing the nginx.conf
![image](https://user-images.githubusercontent.com/62782361/108314131-0397d700-717f-11eb-8242-2156f02483ea.png)
I really do need to increase the record_max_size, quickly.

Also, I am not as technical as I should, but I do need to know what's going on with Restream because it is not going to the place that we have in place to restream to

**Comment by DanielnetoDotCom** [comment]
Hi, I can see your server is hosted by me, I will make the change/update for you.

**Comment by DanielnetoDotCom** [comment]
I just double the limit. please try now

**Comment by CROSSMediaNet** [comment]
It is still doing it...the videos that go to over an hour still split up into two videos that are not together when broadcasting live. Also, what is going on with Restream?

**Comment by CROSSMediaNet** [comment]
I hope that someone responds, but here's the dilemma with the videos
![Videos not together](https://user-images.githubusercontent.com/62782361/108950465-e0ac6d80-762b-11eb-87ad-f7f514404310.jpg)

How to fix this issue and Restream for the other channels

**Comment by DanielnetoDotCom** [comment]
Hi, regarding the file split it should not happen anymore. I guess I forgot to restart your live server to get the new configurations. please try again.

regarding the restream what is the problem?

**Comment by DanielnetoDotCom** [comment]
FYI in your logs, I found this

[rtmp @ 0x563ee6f9e380] Server error: Already publishing
rtmp://us.vi**.tv/live/reeltv?key=4w25*********T9jtgxC0S: Operation not permitted
