### ISSUE TITLE
Livestream Sidebar

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4563]
@DanielnetoDotCom , hi

When I watch a stored video, I get a sidebar with my list of live videos - like this one.

![live-sidebar](https://user-images.githubusercontent.com/65451390/107976579-db677700-6fca-11eb-9e70-1eb22f8dc692.PNG)

However, I don't have the same for live videos. I just have a full screen - like this one

![fullscreen](https://user-images.githubusercontent.com/65451390/107976727-123d8d00-6fcb-11eb-972d-3df037641ec9.PNG)

How can I get the list of live videos on the sidebar?

Thanks.

**Comment by DanielnetoDotCom** [comment]
Hi, on live we do not show VOD videos, but we can show the chat

**Comment by jengajenga** [comment]
> Hi, on live we do not show VOD videos, but we can show the chat
> 
> ![image](https://user-images.githubusercontent.com/18009293/108059002-9af01380-7033-11eb-84bd-ba23defb8b78.png)

Hi @DanielnetoDotCom ,

Instead of the chat can we show the live videos? Or can we show the live videos under or above the chat?

**Comment by DanielnetoDotCom** [comment]
Only with some code. it requires some development to allow show live videos on the side.
