### ISSUE TITLE
Nginx Reverse Proxy config

### ISSUE THREAD

**Issue by stevezemlicka** [WWBN/AVideo#4564]
I am having trouble getting AVideo to work behind an nginx reverse proxy.  I've dug through a bunch of posts and see that others have this working so this is clearly a gap in my knowledge/understanding.  I just setup a basic reverse proxy site in nginx like i've done for other services but when accessed through the proxy, all I get is broken image icons and text.

My nginx reverse proxy for this site is as follows (minus the let's encrypt stuff)
```
server {

        server_name extdns.dns.com;

        allow   [int-IP-space];
        deny    all;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        location / {
                proxy_pass http://internalname.internaldomain.net;
                     proxy_redirect off;
                     proxy_set_header X-Forwarded-Host $host;
                     proxy_set_header X-Forwarded-Server $host;
                     proxy_set_header X-Real-IP $remote_addr;
                     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_fo$

        }
```
Does anyone have an example of a working nginx reverse proxy config or suggestions on what I'm missing to get this working?  I've tried this with both apache and nginx on the AVideo server itself but I just can't seem to get it going through a reverse proxy (no troubles getting it to work on the server directly though so kudos to the devs).  I'm wondering if the rewrite stuff necessary to make AVideo work natively with nginx are also necessary in the reverse proxy config but I just don't know nginx enough

**Comment by jengajenga** [comment]
+1 on this. I'm seeking help on the same. 

@akhilleusuggo , might you have some knowledge on this?

Thanks.

**Comment by stevezemlicka** [comment]
I added the rewrite option from the man page with no change:
```
server {

        server_name extdns.dns.com;

        allow   [int-IP-space];
        deny    all;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        location / {
                proxy_pass http://internalname.internaldomain.net;
                try_files $uri $uri/ /index.php?$query_string;
                     proxy_redirect off;
                     proxy_set_header X-Forwarded-Host $host;
                     proxy_set_header X-Forwarded-Server $host;
                     proxy_set_header X-Real-IP $remote_addr;
                     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_fo$

        }
```

**Comment by akhilleusuggo** [comment]
Hello , im traveling , and i have no access to computer right now .

I setup 1 month ago a reverse proxy with load balancing and worked as expected , true that my config file looked way different .

I would loke to know the allow/deny is for what exactly ? 

Also remember that there maybe some files that are hosted on some external cdn , and may need access to them too .

Is this server internal ( only testing on local host / home lab envirement ) or is public ?

One of the things i clearly dont see is the `http` section and `port` .

To start , try it on a test server without ssl/https.
Set a basic reverse proxy server config example listening on port 80 , then start adding new locations section/server section /encryption acording to your needs .

Debug and google issues on log file .

I heard that daniel also is traveling 😥

**Comment by stevezemlicka** [comment]
Thank you for your response.  I am doing the initial setup internally so that I get all the bugs worked out before opening up to the internet.  The allow/deny prevents external access but allows access from internal IPs.  Note that this only applies to web access through the reverse proxy, the target server does have internet access itself.

Understood, the avideo server itself should be able to reach external resources as it has internet access independent of the reverse proxy.

Internal server but will make public at some point.

I don't have a port because it is using 443.  Like my other nginx reverse proxied services, I don't think https/http is necessary for the servername.  The target server is designated with http because backend traffic is not ssl (yet, i'll make a self-signed cert and update that when I get it working).

Unfortunately I cannot even get a basic config to relay the full avideo homepage.  The location is just / because it's a reverse proxy. 

Good point about the logs.  I am, unfortunately not getting any errors in my error log but I am seeing the access happening (no errors on that either).  I've added the debug option to my error log but, while I still don't see any errors, I don't really understand the output so it looks like I might have some homework to do on that.

**Comment by stevezemlicka** [comment]
@akhilleusuggo I think you were on to something with regards to stepping back.  I looked at the console (F12 in chrome) and noticed that it was complaining of unsecured resources over the secure connection.  So I cut a cert from my internal CA and updated the apache instance of AVideo with a certificate.

Unfortunately this sort of broke AVideo in that just about the only thing that now comes up s the logo.  But on the plus side, it looks the same when accessed either directly or through the reverse proxy.  Now I have to figure out what's wrong with my apache config (unfortunately i'm even worse at apache than I am nginx).

At the risk of being presumptuous, I think my issue was with running my nginx proxy with ssl outwardly and non-ssl on the backend.

**Comment by stevezemlicka** [comment]
I think it just took a few moments to get its bearings because it seems to be working now.  The only think I've noticed so far is that the menu icons are missing.  They show up normally when accessing the server directly but when accessing through the reverse proxy, they just show as empty squares.  This is occurring on the Menu button itself as well as all the menu options (Videos, Browse Channels, Play a Link, Help, About, Etc.).  Any ideas on why just those icons wouldn't get passed through properly?

**Comment by jengajenga** [comment]
> I think it just took a few moments to get its bearings because it seems to be working now. The only thing I've noticed so far is that the menu icons are missing. They show up normally when accessing the server directly but when accessing through the reverse proxy, they just show as empty squares. This is occurring on the Menu button itself as well as all the menu options (Videos, Browse Channels, Play a Link, Help, About, Etc.). Any ideas on why just those icons wouldn't get passed through properly?

hi. congratulations.

what code are you using? are you putting that code in nginx.conf?

**Comment by stevezemlicka** [comment]
@jengajenga So it turns out it wasn't quite so simple but after having posted a couple of comments so closely together, I thought I was at risk of composing a saga and didn't think everyone hear wanted play-by-play commentary.  So to directly answer your question, my nginx configs for my reverse proxy are in /etc/nginx/sites-available/servername.conf with a link to /etc/nginx/sites-enabled/servername.conf.

And I discovered that whenever I clicked on a link, the url would shift to the actual servername.  So if my proxy address is https://proxy.domain.com.  Going to that address brought up AVideo just fine.  But clicking on any link would take me to https://servername.domain.com/users (or whatever the link target was) instead of https://proxy.domain.com/users.

I'm sure there's a more eloquent way to deal with this, but the way I'm working on dealing with it now is to adjust the apache config on the avideo server to be https://proxy.domain.com and will be resolved with internal DNS.  My nginx proxy will also respond to public hits to https://proxy.domain.com from the internet and direct to internal https://proxy.domain.com.  I'm hoping with that, it won't matter that the links don't get rewritten since they should work internally via direct access to the server or externally through the reverse proxy.  Hopefully that makes sense.

My bet is, as stated earlier, it isn't that simple and this may not work...but I figured the only way i'll learn is to try.

**Comment by stevezemlicka** [comment]
Ok, so it turns out, much to my surprise, that this strategy worked.  Heck, I guess even a broken clock is right twice a day huh.

So, the solution for me was to give up trying to make it work the way I wanted and sort of change the architecture to work with nginx.  The key here is to have the public side servername configured in the nginx reverse proxy be the same as the servername configured on the AVideo server (in my case in apache).  Also key here seems to be ensuring that if you have https on the public side of the reverse proxy, also setup https on the target avideo server.

Beyond that, I did discover that a basic nginx config won't work.  You do seem to need some additional attributes.  My nginx reverse proxy config is as follows:
```
server {

        server_name proxy.domain.com;


        access_log /var/log/nginx/proxy.domain.com.log;
        error_log /var/log/nginx/proxy.domain.com.log;

        location / {
                proxy_pass https://proxy.domain.com;
                     proxy_redirect off;
                     proxy_set_header X-Forwarded-Host $host;
                     proxy_set_header X-Forwarded-Server $host;
                     proxy_set_header X-Real-IP $remote_addr;
                     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/proxy.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/proxy.domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = proxy.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot



        listen 80;

        server_name proxy.domain.com;
    return 404; # managed by Certbot
	

}
```

As I indicated earlier, i'm sure there's a more eloquent way to deal with this rather than having the internal and external names needing to be the same, but this seemed to be the easiest solution for me.  I did try messing around with proxy_redirect internalservername.domain.com externalservername.domain.com; but that also didn't work to overcome the issues with the dissimilar names.  So if someone who knows more about webservers wants to chime in on better ways of doing this, I'm happy to entertain them...but I suppose my janky workaround is enough to get me going.

**Comment by stevezemlicka** [comment]
Thanks @akhilleusuggo for the suggestions earlier.  I'll close this out because it seems to be working well now.

**Comment by markginter31** [comment]
I know this issue is closed - but I'm in a similar situation and everything is working except for trying to upload (through the proxy) videos to encode.  I can access the local ip and upload videos just fine.  I also notice that I didn't need many of the options you used in order to get the proxy to work.   Here's my config:

server {
server_name  external.server.name;

        access_log /var/log/nginx/reverse-access.log;
        error_log /var/log/nginx/reverse-error.log;

location / {
##Remember to set address/name to other server in /etc/hosts
        proxy_pass https://internal_same_as_external.server.name;
}
##This is the encoder location
location /uploads {
        proxy_pass https://internal_same_as_external.server.name/uploads;
}

    listen 443 ssl; # managed by Certbot
    ssl_certificate  hidden # managed by Certbot
    ssl_certificate_key hidden # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = external.server.name) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


server_name  external.server.name;
    listen 80;
    return 404; # managed by Certbot
}
/etc/nginx/sites-available/videooak (END)

I tried using the options shared in your config -- and it didn't make a difference.  I was just wondering if you're able to upload videos to your encoder (if you're hosting it internally).

**Comment by markginter31** [comment]
And - I just answered my own question -- the     client_max_body_size xxM; needs to be set -- I added that right before the log entries in my nginx config file and it works.

**Comment by markginter31** [comment]
Turns out I was wrong -- are you able to upload videos through your reverse proxy?  I tried with my settings and with yours and can't seem to make it work....

**Comment by markginter31** [comment]
And - I figured it back out -- in the uploads line I had used the fqdn instead of the internal ip address -- that was a mistake.  In order for the uploads to proxy correctly I put the internal ip back in and now it works.

**Comment by stevezemlicka** [comment]
To get around this and use the name, make sure your internal dns is setup
to resolve to the internal IP and that your NGINX system is pointed to that
as the DNS.  Alternatively, if you do not have internal DNS, you can setup
a host record locally on the nginx server
https://linuxize.com/post/how-to-edit-your-hosts-file/

**Comment by guymass** [comment]
Can anyone please help me setup my server also behind a proxy using reverse tunnel to a proxy server.

My setup is like this:

I am using a remote server I setup as proxy with apache server, it is handling several sites. I connect to it using an autossh tunnel, for example using a 8989 port to proxy to local VM server on port 80.

The proxy handles the SSL termination. Now I have the site running well on my local VM on this domain tube.feisafe.com

Now I want to setup the NGINX to allow streaming and here is where I get stuck.

**This is my proxy config:**

<IfModule mod_ssl.c>
<VirtualHost *:443>
	ServerName tube.feisafe.com
	ErrorLog /var/log/apache2/tube.feisafe.com_error.log
  	CustomLog /var/log/apache2/tube.feisafe.com_access.log combined

	SSLEngine On
	ProxyRequests Off
	ProxyPreserveHost On
	RequestHeader set X-Forwarded-Proto "https"
	ProxyPass / http://127.0.0.1:8989/
	ProxyPassReverse / 127.0.0.1:8989/

# From here I am just trying to open ports for the stats.xsl, rtmp and socket

        ProxyPass / http://127.0.0.1:8443/
        ProxyPassReverse / 127.0.0.1:8443/

        ProxyPass / http://127.0.0.1:8444/
        ProxyPassReverse / 127.0.0.1:8444/

        ProxyPass / ws://127.0.0.1:2053/
        ProxyPassReverse / ws://127.0.0.1:2053/  

        ProxyPass / wss://127.0.0.1:2053/
        ProxyPassReverse / wss/ http://127.0.0.1:2053/

        ProxyPass / https://127.0.0.1:1935/
        ProxyPassReverse / https://127.0.0.1:1935/

    Header add Access-Control-Allow-Origin "*"
    Header add Access-Control-Allow-Origin "localhost"
    Header add Access-Control-Allow-Origin "feisafe.com"
    Header add Access-Control-Allow-Origin "tube.feisafe.com"

Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/tube.feisafe.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/tube.feisafe.com/privkey.pem
</VirtualHost>
</IfModule>

**My local Apache config is this:**

<VirtualHost *:80>
    ServerName tube.feisafe.com
    DocumentRoot /var/www/html/AVideo
    ErrorLog /var/log/apache2/tube.feisafe.com_error.log
    CustomLog /var/log/apache2/tube.feisafe.com_access.log combined


<Directory /var/www/html/AVideo/>
    Options Indexes FollowSymLinks
    XSendFile on
    XSendFilePath /var/www/html/AVideo/
    AllowOverride All
    Require all granted
    Order Allow,Deny
    Allow from All

Header add Access-Control-Allow-Origin "*"
Header add Access-Control-Allow-Origin "localhost"
Header add Access-Control-Allow-Origin "feisafe.com"
Header add Access-Control-Allow-Origin "tube.feisafe.com"


    </Directory>

ProxyPass /ws/ ws://tube.feisafe.com:2053/
ProxyPassReverse /ws/ ws://tube.feisafe.com:2053/

</VirtualHost>


<IfModule mod_ssl.c>
<VirtualHost *:8443> 
RewriteEngine On
ProxyPreserveHost On
ServerAdmin support@feisafe.com
DocumentRoot /var/www/html/AVideo/
ServerName tube.feisafe.com 
ProxyPass "/"  "http://127.0.0.1:8443/"
ProxyPassReverse "/"  "http://127.0.0.1:8443/" 

ErrorLog     /var/log/apache2/live-error_log 
CustomLog          /var/log/apache2/live-access_log common 
 

Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/tube.feisafe.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/tube.feisafe.com/privkey.pem
</VirtualHost>
</IfModule>


<IfModule mod_ssl.c>
<VirtualHost *:8444>
RewriteEngine On
ProxyPreserveHost On
ServerAdmin support@feisafe.com
DocumentRoot /var/www/html/AVideo/
ServerName tube.feisafe.com
ProxyPass "/"  "http://127.0.0.1:8444/"
ProxyPassReverse "/"  "http://127.0.0.1:8444/"


ErrorLog     /var/log/apache2/live-error_log
CustomLog          /var/log/apache2/live-access_log common


Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/tube.feisafe.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/tube.feisafe.com/privkey.pem
</VirtualHost>
</IfModule>

**My Nginx config is:**

server {
    listen *:8444;
    server_name tube.feisafe.com;   
    client_max_body_size 4196M;
    location /live {
#            add_header 'Cache-Control' 'no-cache';
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length';

            add_header 'Cache-Control' 'max-age=31536000, public';

            if ($request_method = 'OPTIONS') {
                    add_header 'Access-Control-Allow-Origin' '*';
                    add_header 'Access-Control-Max-Age' 1728000;
                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                    add_header 'Content-Length' 0;
                    return 204;
            }
            types {
                    application/vnd.apple.mpegurl m3u8;
            }

    alias /HLS/live;
    }
    location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
    }
    location /stat.xsl {
            root /var/www/html;
    }
    location /control {
            #allow 127.0.0.1;
            #allow 127.0.0.1;
            deny all;
            rtmp_control all;
    }    
    location / {
  root   html;
            index  index.html index.htm;
    }
                location ~ \.php$ {
                        include /etc/nginx/snippets/fastcgi-php.conf;
                        fastcgi_pass unix:/run/php/php7.4-fpm.sock;                                        
                }

  }


server {
    listen 8443 ssl http2;
    ssl_certificate /etc/letsencrypt/live/tube.feisafe.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/tube.feisafe.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 
#
    error_log /var/log/nginx/debug.log debug;
    server_name tube.feisafe.com;   
    client_max_body_size 4196M;
    location /live {
            add_header 'Cache-Control' 'no-cache';
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length';
            if ($request_method = 'OPTIONS') {
                    add_header 'Access-Control-Allow-Origin' '*';
                    add_header 'Access-Control-Max-Age' 1728000;
                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                    add_header 'Content-Length' 0;
                    return 204;
            }
            types {
                    application/vnd.apple.mpegurl m3u8;
            }
alias /HLS/live;
    }
    location /signup {
        alias   /var/www/html/;
        index  index.php;

        location ~ ^/signup/(captcha\.php|index\.php) {
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                        fastcgi_pass unix:/run/php/php7.4-fpm.sock;                                        
            include fastcgi_params;
        }
        location ~ ^/signup/static/.*(\.html|\.css|\.js)$ {
            root /var/www/html/;
            try_files $uri =404;
        }
        location  ~ ^/ {
            rewrite ^ /signup/index.php; 
        }
    }
    location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
    }
    location /stat.xsl {
            root /var/www/html;
    }
    location /control {
            #allow 194.233.174.32;
            #allow 127.0.0.1;
            deny all;
            rtmp_control all;
    }    

        location / {
                proxy_pass https://tube.feisafe.com;
                     proxy_redirect off;
                     proxy_set_header X-Forwarded-Host $host;
                     proxy_set_header X-Forwarded-Server $host;
                     proxy_set_header X-Real-IP $remote_addr;
                     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

}    
location ~ \.php$ {
                        include /etc/nginx/snippets/fastcgi-php.conf;
                        fastcgi_pass unix:/run/php/php7.4-fpm.sock;                                        
                }


}
server {
    if ($host = tube.feisafe.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot



        listen 80;

        server_name tube.feisafe.com;
    return 404; # managed by Certbot
 

}


I know its a mess, been trying all sorts of configs with no success.

**Comment by guymass** [comment]
Following site is 100% behind a reverse proxy SSH tunnel also using HAProxy. Everything works, Socket, Streaming, Network Encoders. https://tube.feisafe.com
