### ISSUE TITLE
MediaInfo displayed on frontend

### ISSUE THREAD

**Issue by KamillaPup** [WWBN/AVideo#4565]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that I can't see MediaInfo stats of videos within AVideo

**Describe the solution you'd like**
I would like a tab by description to show technical details, such as format, file size, codec, bitrate, etc. Basically everything that MediaInfo shows from terminal.

**Describe alternatives you've considered**
If this only shows in the admin dashboard, that's fine too. But it would be better to have it viewable by all.

Has anyone made a plugin to display this info?

**Comment by baoang** [comment]
*stats for nerds* as provided by Youtube, am I correct?

**Comment by DanielnetoDotCom** [comment]
This feature is not on the road, if it is really important for you you may want to sponsor this feature. or maybe it will be developed in the future.

If you want to sponsor it you may want to contact us for a quotation at  develope@youphptube.com

**Comment by KamillaPup** [comment]
Oh maybe! Is the email developer@youphptube.com or develop@youphptube.com? Probably the one I've talked to you on as Sangie. Money is dire right now, but I might be open for that later.

Is there a quick way to get the unique ID of the video so I can use MediaInfo over ssh? I know I can go through MySQL to get it but wondering if there is a quicker method.

**Comment by DanielnetoDotCom** [comment]
Sorry, the correct email is developer@youphptube.com

no, to get the file you must query the database
