### ISSUE TITLE
doNotShowExtractAudio option reversed

### ISSUE THREAD

**Issue by baoang** [WWBN/AVideo#4566]
**Describe the bug**
setting **doNotShowExtractAudio** in `plugin - CustomizedAdvanced` to be **checked** has a reversed effect in Encoder Advanced section, ie. disappeared.

**To Reproduce**
1. Go to 'Control Panel - plugin - CustomizedAdvanced'
2. Scroll down to **doNotShowExtractAudio**
3. check/uncheck it
4. See Encoder (self-hosted, but git pulled to the latest)

**Expected behavior**
If checked, in Encoder's Advanced section on the right side, there should be a line of **Extract Audio**
if unchecked, in Encoder's Advanced section on the right side, there should be no **Extract Audio**

**Error Logs**
no Error logs for this.

**Screenshots**
![checked](https://i.imgur.com/KSuHWLt.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux Debian Buster 64
 - Browser [e.g. chrome, safari] FireFox on Windows 10 Pro
 - Version [e.g. 22] git pulled to the latest

**Smartphone (please complete the following information):**
Not tried smartphone because I couldn't connect to streamer site

**Additional context**
N/A

**Comment by DanielnetoDotCom** [comment]
Thanks, I sent a fix for that
