### ISSUE TITLE
QUESTION: How to Change url 

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#4567]
How can i change the url for a new one. On both areas streamer and website. 

Thank you.

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Change-the-URL-of-your-installation

**Comment by LATINMIXMASTERS** [comment]
> https://github.com/WWBN/AVideo/wiki/Change-the-URL-of-your-installation

A question , i have already a domain is just i want to put a new one so is same process to update domain? I am just want to make sure i dont do anything wrong.
