### ISSUE TITLE
Watching count not counting on frontpage

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4568]
Hi hi. Watching not counting on front page but is counting on stream...
![watch1](https://user-images.githubusercontent.com/76112286/108092651-981e0e80-7085-11eb-9e3d-4698fc45b03a.png)
![watch2](https://user-images.githubusercontent.com/76112286/108092676-9c4a2c00-7085-11eb-8c33-355ddf951772.png)

**Comment by DanielnetoDotCom** [comment]
are you using sockets? https://github.com/WWBN/AVideo/wiki/Socket-Plugin

**Comment by jengajenga** [comment]
I'm also having a problem with this. I am using sockets.

1. Click a channel
2. Channel says 1 viewer
3. Drops to zero after a few seconds

I had to drop the total live viewers because in 2 days i had a channel with 12000 views but i know for a fact that it impossible.

how exactly is this calculated? I noticed the code is protected.

**Comment by unconservo** [comment]
Yes im using sockets :)

**Comment by DanielnetoDotCom** [comment]
I forgot to mention something.

@unconservo please make sure you have the on_publish_done in your nginx.conf

https://github.com/WWBN/AVideo/blob/02ea4700552dbf888beb0eabf76376e5c8ddf27c/plugin/Live/install/nginx.conf#L22

**Comment by DanielnetoDotCom** [comment]
@jengajenga are you using the live in an iframe?

**Comment by unconservo** [comment]
Thanx Daniel. Will check and test it tonight. Will revert back to you. I'm not using live in iframe.

**Comment by jengajenga** [comment]
> @jengajenga are you using the live in an iframe?

No I'm not. Sorry I'm only just seeing this.

**Comment by unconservo** [comment]
Still does not show on frontpage. Counter stays 0

**Comment by unconservo** [comment]
> I forgot to mention something.
> 
> @unconservo please make sure you have the on_publish_done in your nginx.conf
> 
> https://github.com/WWBN/AVideo/blob/02ea4700552dbf888beb0eabf76376e5c8ddf27c/plugin/Live/install/nginx.conf#L22

When I add this to my nginx config my live broadcast stops working. The nginx does not fail to load

**Comment by jengajenga** [comment]
> > I forgot to mention something.
> > @unconservo please make sure you have the on_publish_done in your nginx.conf
> > https://github.com/WWBN/AVideo/blob/02ea4700552dbf888beb0eabf76376e5c8ddf27c/plugin/Live/install/nginx.conf#L22
> 
> When I add this to my nginx config my live broadcast stops working. The nginx does not fail to load

change the localhost to your normal ip/domain.
mine is working just fine after I did that. 

but total views (the black one) doesn't show on the first page.

**Comment by DanielnetoDotCom** [comment]
It is working on demo site

![image](https://user-images.githubusercontent.com/18009293/109149639-9c61c000-7746-11eb-964b-2ddbe658959e.png)

**Comment by unconservo** [comment]
So what can it be?. mine not counting on front page

**Comment by DanielnetoDotCom** [comment]
do you have the socket enabled?

https://github.com/WWBN/AVideo/wiki/Socket-Plugin

**Comment by unconservo** [comment]
Yes, I do.  Socket is running. Counter is working on the live stream but
not on the front page

**Comment by DanielnetoDotCom** [comment]
Then check your JS console for JS errors

**Comment by unconservo** [comment]
i see that if another account view content and i use another account to go to front page, on that content it also does not show count on watching now
