### ISSUE TITLE
Rename/Remove rating options

### ISSUE THREAD

**Issue by KamillaPup** [WWBN/AVideo#4569]
I was wondering if there is an easy way to remove or rename the ratings options. Currently there's G, PG, PG-13, R, NC-17, and MA. That's a lot! If I could limit it to General, Mature, Adult or something similar would be better in my case. Is there an easy way to do this without breaking anything? (Also what is the difference between NC-17 and MA?)

Also, having a birthdate requirement on registration? Also, is there a way to make the rating warning only come up for guests?

Thanks!

**Comment by DanielnetoDotCom** [comment]
Currently, the rating is hard coded
