### ISSUE TITLE
Do not display 

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#4570]
I do not check "doNotShowEncoderResolutionLow and doNotShowEncoderResolutionSD and doNotShowEncoderResolutionHD" in CustomizeAdvanced plug in
I open encoder page. But not display Low , SD , HD button. new Edge Chrome and Firefox same.
Where do I wrong ?
(AVideo Ver10.2 ENcoder Ver3.6)

**Comment by DanielnetoDotCom** [comment]
Uncheck **showOnlyEncoderAutomaticResolutions**

![image](https://user-images.githubusercontent.com/18009293/108348540-ae7cb500-71c0-11eb-94b2-b940c848aca5.png)
