### ISSUE TITLE
HTML links in About page

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4571]
Hi. Can you please change the text editor for About page under user profiles so that users can add links to different pages like Facebook etc.

Also can you please tell me where Extra info is displayed. Is it only for Admin use?. I enabled it but does not show on User channel with entered data'

Regards

**Comment by DanielnetoDotCom** [comment]
Can you please screenshot of what exactly pages are you talking about?

**Comment by unconservo** [comment]
About on user profile
![image](https://user-images.githubusercontent.com/76112286/108356688-1d740100-71f5-11eb-82bd-b07176c3a54b.png)
![image](https://user-images.githubusercontent.com/76112286/108356758-354b8500-71f5-11eb-9447-400c5d1fe115.png)
Extra Info:
![image](https://user-images.githubusercontent.com/76112286/108356818-4ac0af00-71f5-11eb-86bd-13777b25564f.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I do not want to enable the HTML code for users, otherwise, they can mess up the HTML code and include XSS attacks .

Extra info:

![image](https://user-images.githubusercontent.com/18009293/108357750-9b6fe200-71cc-11eb-8302-4866d6e9887c.png)

**Comment by JoshWho** [comment]
This is actually possible but should be done with Java and not user html input.

I currently have it done using java u can see here. https://www.joshwhotv.com/channel/Unframeofmind

![b1ac7b08-0a31-4a88-9655-fdb8030a4e88](https://user-images.githubusercontent.com/39392449/108358396-4cb64e00-71b4-11eb-93b2-5f31e74a8076.png)

Example using Java and Regex https://stackoverflow.com/questions/29747733/auto-link-url-with-javascript-regex

**Comment by DanielnetoDotCom** [comment]
I do not think you need it, the latest version already converts links into tags.
but we do not allow tags on the about.

**Comment by JoshWho** [comment]
THis is just auto converting plain text. Even if it doesn't start with https://     it just looks for a domain and makes it a hyperlink

**Comment by JoshWho** [comment]
No need to change the editor with that script

**Comment by unconservo** [comment]
Ok. Thanx. But it did not convert any of my internet links. Its just text :)
