### ISSUE TITLE
Does Avideo provide an embed-code like Youtube?

### ISSUE THREAD

**Issue by fxp66** [WWBN/AVideo#4573]
I want to publish videos via Avideo on another website (Typo3) using an extension for the CMS.
This works fine with Youtube embed codes.
Does Avideo provide an code similiar to this, and where can I find it?
Thx for reply

**Comment by mhajder** [comment]
Hi,
Try right-clicking on the video.
![image](https://user-images.githubusercontent.com/6783135/108280073-e9112e00-717d-11eb-9392-008f80a2e064.png)

**Comment by fxp66** [comment]
Thank you, that's great!

**Comment by fxp66** [comment]
Ok, I've to setup the SecureVideosDirectory-plugin, now everythings works fine.
