### ISSUE TITLE
Pin Channel/Livestream

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4575]
Hello @DanielnetoDotCom 

Is it possible to pin a channel or a livestream 

1. In the notification bar so that pinned livestreams are always first? So if I have 3 or 4 livestreams I would like to pin them up and then every other livestream is arranged as usual

![pin-me-here](https://user-images.githubusercontent.com/65451390/108337887-ae8fab80-71e6-11eb-997c-0708c25e8274.png)

2. For gallery/Big Video, can we have option to put some livestreams there instead of only a stored video? 

Thank you.

**Comment by mhajder** [comment]
It already looks fixed in the code. Feel free to close it.

**Comment by DanielnetoDotCom** [comment]
Sorry, there is no such option for both questions.
