### ISSUE TITLE
Automatic Reprodution 

### ISSUE THREAD

**Issue by ricasht** [WWBN/AVideo#4578]
good afternoon, i realized that an automatic reproduction pair for no reason.

**Comment by jengajenga** [comment]
what??

**Comment by ricasht** [comment]
even set to play automatically, it stops and does not play the next video

![TcheVideos](https://user-images.githubusercontent.com/69056431/109054167-54965680-76bc-11eb-9c54-991a88be83b4.png)

**Comment by DanielnetoDotCom** [comment]
@ricasht is it an embed or self-hosted video?

**Comment by ricasht** [comment]
Good morning, I will explain the whole process.
We have a content producer, we produce it in live format and send it to the platform with a user account.

Problems reported by the user or found by:
in descktop stop the playback and sometimes goes into a small loop, showing the same videos.
on mobile phones by the browser does not stop, but it also creates a small loop.

**Comment by DanielnetoDotCom** [comment]
maybe you are facing the autoplay policy issue
check this: https://github.com/WWBN/AVideo/wiki/Autoplay-and-Browser-Policies
