### ISSUE TITLE
Error 404 videos clicked from categories.

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4584]
Videos clicked from first page categories , provides error 404 ( video not found ).

I believe it's a htaccess issue .

When clicked from categories , the url string adds `=NameCategory` and breaks the url path to video .

**Comment by DanielnetoDotCom** [comment]
Hi, can you please provide me a link on demo site so I can test

**Comment by akhilleusuggo** [comment]
Sorry for late reply , but has been fixed in some of the latest releases .
