### ISSUE TITLE
i dont know what im doing video directoy

### ISSUE THREAD

**Issue by andrewchadsey** [WWBN/AVideo#4586]
my video directory needs to be writable 
whenever i put in 

chown www-data:www-data /var/www/html/AVideo/videos && chmod 755 /var/www/html/AVideo/videos 

i get operations not permitted 
i have no clue what im doing so if you could help that would be greatly appriated

**Comment by walt93** [comment]
(Just another user here) this is likely because you need root permissions to do this. Your user account is probably already in the sudo group. Try prefixing your command with "sudo " as in "sudo chown....."

**Comment by andrewchadsey** [comment]
> (Just another user here) this is likely because you need root permissions to do this. Your user account is probably already in the sudo group. Try prefixing your command with "sudo " as in "sudo chown....."

thank you
