### ISSUE TITLE
After soft linking videos directory, site seems fairly borked.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4587]
**Describe the bug**
Followed the instructions on https://github.com/WWBN/AVideo/wiki/Can-I-store-my-videos-in-another-location. 
Now the site seems non-functional. Videos directory is linked to /mnt/md0/videos. URLs are redirecting to places with /mnt/md0 in the URL. Example: enter url tube.mysite.tv/upload and get a 404 not found on tube/mysite.tv/mnt/md0/user
 
**To Reproduce**
1. Follow these instructions https://github.com/WWBN/AVideo/wiki/Can-I-store-my-videos-in-another-location
2. Load your uploads page at https://tube.mysite.tv/upload
3. Watch browser redirect to https://tube.mysite.tv/mnt/md0/user and display 404 error

**Expected behavior**
Expected the site to function as normal, and files to be stored at /mnt/md0/videos

**Screenshots**
#1 loading the upload page from a browser that has a login cookie for the admin account. Notice it doesn't render the CSS
![Screen Shot 2021-02-21 at 4 32 39 PM](https://user-images.githubusercontent.com/11711050/108644725-13f0d000-7465-11eb-8722-919b52a6748f.png)
#2 clicking on the logout link from page #1 above
![Screen Shot 2021-02-21 at 4 32 53 PM](https://user-images.githubusercontent.com/11711050/108644740-20752880-7465-11eb-9d10-51afc9cfd825.png)
#3 loading the upload page from the brave browser in a private window so it doesn't use the cached login cookie
![Screen Shot 2021-02-21 at 4 52 50 PM](https://user-images.githubusercontent.com/11711050/108644780-51edf400-7465-11eb-8206-90301bd3d52a.png)
#4 and it redirects to a URL that oddly contains the path to the videos directory (it's mounted at /mnt/md0/videos)
![Screen Shot 2021-02-21 at 4 53 14 PM](https://user-images.githubusercontent.com/11711050/108644798-6631f100-7465-11eb-9229-e99b2f691fa0.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X Catalina 10.15.7
 - Brave 1.20.108 Chromium 88.0.4324.182 (official build)
 -Firefox 85.0.2 also exhibits the redirect issue, as does Safari 14.0.2, and Opera 74.0.3911.75 (I don't think its the browser either)

***Question***
What else can I do to convince YouPHPTube to use a different directory? Env vars? Source code mods? I can't get going until I get the storage off the boot volume, I haven't got much space there but do have 11TB of Raid 5 waiting...

**Comment by DanielnetoDotCom** [comment]
Hi, check this https://github.com/WWBN/AVideo/issues/4026#issuecomment-729611103
