### ISSUE TITLE
Disable Update Popup

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#4590]
Is it possible to disable **Update Popup** that is very annoying because i can't update to the latest version due issue https://github.com/WWBN/AVideo/issues/4558#issuecomment-781366192

![Snap1](https://user-images.githubusercontent.com/39981177/108689036-e48ba300-74f8-11eb-9efb-37fee4a08009.jpg)

**Comment by DanielnetoDotCom** [comment]
I guess in a recent update this popup does not appear anymore unless you make a git pull

**Comment by TLCReuver** [comment]
Thank you.
