### ISSUE TITLE
Server sizing - host 4gb videos

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#4592]
Hi there,

Currently I am using b2 Backblaze and have a very stable platform with videos limited to 100mb.

I'm now looking to host videos up to 4gb in size and wondered if anyone else allows their users to upload videos as large as 4gb??

If so, can you recommend a decent server spec for this?

**Comment by DanielnetoDotCom** [comment]
4gb is not an issue if you are self-hosting it.
