### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4597]
I am attaching a SS. I am trying to translate the work PLAYLISTS with no avail. It just wont take the new value in my language.
I have set it as follows:
$t['PLAYLISTS'] = 'רשימות ניגון';

But that doesn't effect the Title for the playlists tab.

![Screen Shot 5781-06-11 at 22 20 52](https://user-images.githubusercontent.com/58882903/108903376-ebfc9a80-7625-11eb-9d60-2232525003c7.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, please, update the streamer
