### ISSUE TITLE
RTL template

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4598]
We are mostly using in my country the Hebrew and Arabic languages and both of them are RTL. When a user selects his language the template should reflect the way the page is displayed. I have noticed that even though we have an Hebrew translation, most of the site is still displayed in a LTR manner which deems the site to appear not really nice.

Do you have a complete RTL version of the site or can you at least set the video page to appear correctly in RTL if those languages are chosen?

Or do we need to create a new template?
For example this area on the video page is displayed on the left instead of right.

![Screen Shot 5781-06-11 at 22 32 56](https://user-images.githubusercontent.com/58882903/108904420-2286e500-7627-11eb-8ce0-ab81ac2ccdec.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, sorry I am not very expert on RTL langs, can you please point me where are the errors and how it should look like?

**Comment by guymass** [comment]
well basically its simple, everything should float to the right side, text wise I mean. I think it will be as simple a text direction RTL or floating the titles and text fields and areas to the right side.

On the image above for example I would leave the comment button on the left but the areas above and below it should be displays on the right side of the row. The icons for delete and edit should be moved to the left and the user details to the right side.
