### ISSUE TITLE
Playlist Stream not working

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4599]
I have tried streaming a playlist after the encoder update and it shows it preparing the streaming and going Live, but the stream is not shown on front page or anywhere, its just blinking live.

![Screen Shot 5781-06-11 at 22 40 16](https://user-images.githubusercontent.com/58882903/108905639-9ecdf800-7628-11eb-8279-7033727fcceb.jpg)
![Screen Shot 5781-06-11 at 22 44 15](https://user-images.githubusercontent.com/58882903/108905745-be652080-7628-11eb-9fec-7fb17dac0de1.jpg)

Is it still not working or is this a bug?

**Comment by unconservo** [comment]
HI. I have found that you have to first go into Live Broadcast. Setup all your stream info there and make it public and save. Then go to your playlist and select live :)
