### ISSUE TITLE
Scheduling Livestreams for users

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4601]
Hi hi. This is what we need for users when they livestream. To add a schedule for when their livestream will start. This will make this script absolutely stand out from all the other clone scripts

![image](https://user-images.githubusercontent.com/76112286/108978637-78dd3d80-7692-11eb-8cb7-82e15cbd088c.png)

**Comment by DanielnetoDotCom** [comment]
We will have this feature in the future for sure.
