### ISSUE TITLE
Video files vanish after it converted them

### ISSUE THREAD

**Issue by jakesullyneytiri** [WWBN/AVideo#4603]
I'm having a problem with my copy of your script, i upload a video it converts but once it's done all 3 converts the files just vanish and main site still shows 0 videos and no uploaded videos.

So i have no clue whats wrong??

Both encoder and main site is meeting requirements.

Is there something i have missed like a chmod on some path some where or something??

**Comment by jakesullyneytiri** [comment]
Update: I think i found problem, script is submitting to domain.com/youPHPTubeEncoder.json but my copy of this AVideo does not have such file named youPHPTubeEncoder.json which it cannot then submit file to my site.

So how do i solve this??

**Comment by walt93** [comment]
FWIW I had the same symptom, encoder encodes, no video shows up, and I was trying to get things stable under Nginx. Switching to Apache this issue went away. YMMV.

**Comment by jakesullyneytiri** [comment]
> FWIW I had the same symptom, encoder encodes, no video shows up, and I was trying to get things stable under Nginx. Switching to Apache this issue went away. YMMV.

Well that wasn't my problem. Problem was Json files where  not renamed to new ones. Since script was named YouPHPTuber in first place but was then renamed to AVideos so then 2-3 json files where still named same in a file on encoder which when it converted the videos it was submitting to one of old json files that didn't exists on AVideo. So I looked up new name and corrected this in a php file from encoder and after that my videos got submitted to my AVideo script.

**Comment by DanielnetoDotCom** [comment]
You have to make sure encoder and streamers are the latest

**Comment by jakesullyneytiri** [comment]
> You have to make sure encoder and streamers are the latest

Both are latest. Since I got both from github source page. Yet encoder had wrong names on json files. It was pointing to old json files and not new ones. But I corrected it manually.

**Comment by DanielnetoDotCom** [comment]
@jakesullyneytiri did you use `git pull` on both to get the latest?

**Comment by jakesullyneytiri** [comment]
> @jakesullyneytiri did you use `git pull` on both to get the latest?

I went to github page and selected latest as build and clicked download as zip on both.

**Comment by DanielnetoDotCom** [comment]
You MUST use `git clone` command to get the latest
