### ISSUE TITLE
Creating a new user and trying to log in with that user are failing with bad credentials.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4606]
**Describe the bug**

Passwords with seemingly anything more complex than alphanumeric fail.

**To Reproduce**
Create new user. Let OS () pick a "strong password". Try to log in. Get denied with bad credentials.
Create new user. Type in a reasonable password which includes characters such as hyphens and underlines. Same.
Create new user. Type in "password". Log in. It works.

**Expected behavior**
This to work.

**Error Logs**
Didn't look.

**Screenshots**
Probably unnecessary.

**Best Guess**
Character encoding configuration somewhere? Apache?

**Comment by DanielnetoDotCom** [comment]
On my side it works, can you try on demo site?
