### ISSUE TITLE
No way to delete users

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4607]
**Is your feature request related to a problem? Please describe.**
My site config is fsck'ed. When a user tries to create a new account, unless the password is trivial like "password123", you get a user that can't log in.

**Describe the hack you've used to work around**
Go in to each zombie user account and replace the name/email with gibberish.

**Describe the solution you'd like**
I'd like to be able to delete these zombie users once I am finished un-fsck'ing the site configuration.

**Comment by jengajenga** [comment]
i support the ability to delete user accounts. it is tiresome have to go to the database directly to delete a user.

**Comment by DanielnetoDotCom** [comment]
Correct, you cannot delete users

**Comment by jengajenga** [comment]
> Correct, you cannot delete users

Is this something that you will add? We cannot delete users and we cannot view user accounts. Supporting users and cleaning the database is a lot of work.

**Comment by DanielnetoDotCom** [comment]
No, I do not have plans to allow it

https://github.com/WWBN/AVideo/issues/3078
https://github.com/WWBN/AVideo/issues/1983

**Comment by jakesullyneytiri** [comment]
> No, I do not have plans to allow it
> 
> #3078
> #1983

Why not? Alot of scripts have delete function. Would be useful if you have to much inactive users and those who do not verify their e-mail would be great to delete as well.
