### ISSUE TITLE
Encoder-Network view gives multiple encoders 

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4609]
Hi hi. I installed the Encoder Network and it works fine except that I have 2 encoders running but the Encoder network is duplicating the 2 to 6. Where can I change this?. I have checked the configuration.php but there are no settings for this.

![image](https://user-images.githubusercontent.com/76112286/109120398-8eb03880-774e-11eb-8833-adeb8a226fab.png)

**Comment by DanielnetoDotCom** [comment]
Hi, you can add/remove encoders thru the command line

https://github.com/WWBN/AVideo-Encoder-Network/blob/master/install/encoders.php

Try ...

`cd /var/www/html/NetwotkDir/install`

`php encoder.php`

you will see something like this ...

![image](https://user-images.githubusercontent.com/18009293/109153433-aafea600-774b-11eb-9e42-8b76ad3dd30e.png)

**Comment by unconservo** [comment]
Thanx. Will check and revert back to you :)

**Comment by unconservo** [comment]
Thank you. That worked perfectly :)
