### ISSUE TITLE
Fresh install. Soft link videos directory to /mnt/md0 raid array. Site fails with 404 with /mnt/md0 in the URLs.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4610]
**Describe the bug**
Fresh install. Create the videos directory as a soft link to somewhere (e.g. /mnt/md0). Try to load the index page. Observe the URL is redirected to tube.site.com/mnt/md0

**To Reproduce**
1. Fresh install
2. Create the videos directory as a soft link to somewhere (e.g. /mnt/md0)
3. Try to load the index page
4. Observe the 404 error and the URL ends with the directory you linked to

**Expected behavior**
Videos to be able to be stored through a soft link as per https://github.com/WWBN/AVideo/wiki/Can-I-store-my-videos-in-another-location

**Comment by DanielnetoDotCom** [comment]
Hi, I guess you have the videos directory in the non-standard place

Check this https://github.com/WWBN/AVideo/issues/3066#issuecomment-629240169
