### ISSUE TITLE
Paypal and Site wallet gives same name

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4611]
Hi hi. I have enabled the Paypal and site wallet. When I go to a user's video to donate it is giving the same name for both. How can I change it so one will say Donate with Site Wallet and other Donate with Paypal or whatever the user use in donation link on account details?

![image](https://user-images.githubusercontent.com/76112286/109153215-47896e00-7775-11eb-8155-ae860c58a6b4.png)

**Comment by DanielnetoDotCom** [comment]
Where exactly did you enable those buttons?

**Comment by unconservo** [comment]
Via the Donation link under account and then the YPTWallet

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that now there is an option donationWalletButtonLabel

**Comment by unconservo** [comment]
Awesome. I will check it out :)
