### ISSUE TITLE
Dark Themes side scroll bar

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4612]
Hi hi. On all the Dark themes the scroll bar is very difficult to see. Can I make it a lighter grey or something?. I tried custom colors but that changes to default theme with change of colors.

![image](https://user-images.githubusercontent.com/76112286/109167167-22e9c200-7786-11eb-87e0-154b48ec9dc9.png)

**Comment by DanielnetoDotCom** [comment]
This should change it

![image](https://user-images.githubusercontent.com/18009293/109303635-d9e34d80-7819-11eb-926e-c7a27e84a4ba.png)

**Comment by unconservo** [comment]
What should change it?

**Comment by unconservo** [comment]
What im asking is where do I change so that the scrollbar looks like that on all the dark themes?. You only posted a picture showing it was changed but not how to change it :)

**Comment by DanielnetoDotCom** [comment]
You must update your code

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by unconservo** [comment]
The streamer site is up to date. Is there a color bar entry that I can
change?
