### ISSUE TITLE
Plesk does not like having Operation All where it is

### ISSUE THREAD

**Issue by jakesullyneytiri** [WWBN/AVideo#4614]
In the .htaccess file for this script it has this line

# Disable directory browsing
Options All -Indexes

At row 49 & 50 and that causes 500 internal server error. When i check server logs it tells me "Option All not allowed here" So where can i move this code to so it still works and won't cause error?

My fault, it also has not got anything to do with this script. I just didn't think properly, i fixed this by disabled something in plesk so now it works fine.

**Comment by DanielnetoDotCom** [comment]
Sorry I do not support control panels

![image](https://user-images.githubusercontent.com/18009293/109304477-1cf1f080-781b-11eb-8c5c-616b45889a76.png)
