### ISSUE TITLE
Space filling up but for videos

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4618]
Hi hi. What doe AVideo save other than videos and picture / gif. The more videos i upload the more "other files" are increasing... more than videos.

![Screenshot_20210226-084155_Chrome](https://user-images.githubusercontent.com/76112286/109265306-00e85200-780f-11eb-8666-b7da229779f5.jpg)

**Comment by walt93** [comment]
FYI I observed when using the S3 plugin to store videos that my AVideo/videos directory still grows proportional to the number of videos encoded. The encoder sprays out multiple encodes at different resolutions, and the .webm files get stored in AVideo/videos, while the larger .mp4 files go on the bucket store volume. This may be unrelated.

**Comment by DanielnetoDotCom** [comment]
Is the encoder on the same server?

is it deleting the files correctly?

check if in your streamer videos folder the video dummy files are 10 b only

**Comment by unconservo** [comment]
Encoder is on the same server. Must i delete the dummy files?

**Comment by unconservo** [comment]
Hi. Yes the wncoder is on the same server
Here is a screenshot of files in videos folder of streamer
![Screenshot_20210226-184731_Termius](https://user-images.githubusercontent.com/76112286/109329595-72ea8680-7863-11eb-8e74-57c96a183a4c.jpg)

**Comment by jakesullyneytiri** [comment]
Other files are mostlikely everything else stored on drive, not just videos. So yeah encoder is reporting these as well or the script itself.

**Comment by unconservo** [comment]
All that's installed is the os and AVideo with encoder. a 2gb video cant have 3gb of jpg's and associated files?

**Comment by DanielnetoDotCom** [comment]
maybe the files still in your encoder. check the Encoder videos folder
