### ISSUE TITLE
Remove dark part of sidebar

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4619]
Hi @DanielnetoDotCom 

Can we have the video fill up the player instead of seeing these black sidebars?

![sidebar](https://user-images.githubusercontent.com/65451390/109295288-897ee680-783f-11eb-923a-c1b7f280df86.png)

**Comment by jengajenga** [comment]
@DanielnetoDotCom .. is there any way?

**Comment by DanielnetoDotCom** [comment]
With CSS you probably can. but first, you MUST know how to handle CSS.

I do not have this solution on the top of my mind, but anyone with good CSS skills may be able to do it.

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css
