### ISSUE TITLE
No Thumbnails with embed video

### ISSUE THREAD

**Issue by akorsonsky** [WWBN/AVideo#4620]
Hello,
I have a problem when i use the embed video. I don't have any thumbnail who are generate. All is working for upload video, i have the thumbnail for this, the problem is only for embed video.

![image](https://user-images.githubusercontent.com/44197940/109308615-8a654780-7842-11eb-8598-fcef33dbdf99.png)

video i use to test from here : https://www.youtube.com/watch?v=0gWudWJhRII

in my log of the encoder i have this : 

`
[26-Feb-2021 08:39:04 America/New_York] getTitleFromLink: Get Title: LC_ALL=en_US.UTF-8 /usr/local/bin/youtube-dl  --no-check-certificate --no-playlist --force-ipv4 --skip-download -e "https://www.youtube.com/watch?v=0gWudWJhRII" `
`Array
(
    [0] => WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
    [1] => Star citizen ISC -  Le pleins d'infos sur la 3.13 !
)`
`[26-Feb-2021 08:39:07 America/New_York] getThumbsFromLink: /usr/local/bin/youtube-dl  --no-check-certificate --no-playlist --force-ipv4 --write-thumbnail --skip-download  -o "/tmp/thumbscOPnJB.jpg" "https://www.youtube.com/watch?v=0gWudWJhRII"`
`[26-Feb-2021 08:39:07 America/New_York] getThumbsFromLink: Error: ["WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.","[youtube] 0gWudWJhRII: Downloading webpage","[youtube] Downloading just video 0gWudWJhRII because of --no-playlist","[youtube] 0gWudWJhRII: Downloading thumbnail ...","[youtube] 0gWudWJhRII: Writing thumbnail to: \/tmp\/thumbscOPnJB.jpg.jpg"]
[26-Feb-2021 08:43:39 America/New_York] getTitleFromLink: Get Title: LC_ALL=en_US.UTF-8 /usr/local/bin/youtube-dl  --no-check-certificate --no-playlist --force-ipv4 --skip-download -e "https://www.youtube.com/watch?v=0gWudWJhRII" `
`Array
(
    [0] => Star citizen ISC -  Le pleins d'infos sur la 3.13 !
)`

`[26-Feb-2021 08:43:42 America/New_York] getThumbsFromLink: /usr/local/bin/youtube-dl  --no-check-certificate --no-playlist --force-ipv4 --write-thumbnail --skip-download  -o "/tmp/thumbsCdWLEz.jpg" "https://www.youtube.com/watch?v=0gWudWJhRII"`
`[26-Feb-2021 08:43:42 America/New_York] getThumbsFromLink: Error: ["WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.","[youtube] 0gWudWJhRII: Downloading webpage","[youtube] Downloading just video 0gWudWJhRII because of --no-playlist","[youtube] 0gWudWJhRII: Downloading thumbnail ...","[youtube] 0gWudWJhRII: Writing thumbnail to: \/tmp\/thumbsCdWLEz.jpg.jpg"]
`

i try to configure the LC_ALL with dpkg-reconfigure locales
i put only en_US.UTF-8, then only fr_FR.UTF-8 (encoding from my country), and the twice en_US and fr_FR.
Always same problem.

Is the thumbnail problem i have is because encoding problem or i have to do something else to correct this problem ?

thanks for your help

**Comment by jakesullyneytiri** [comment]
Just so you know thumbnails are not done by ffmpeg or so. Usually thumbnails are generated via GD extension or ImageMagick. So make sure you have 1 of these and see if it generates a thumbnail then.

**Comment by akorsonsky** [comment]
Thanks @jakesullyneytiri for your response !

i have Imagemagick

![image](https://user-images.githubusercontent.com/44197940/109393894-8578c480-7924-11eb-8da6-9fd5ade31750.png)

how i can verify that Avideo can use it without error ?

**Comment by jakesullyneytiri** [comment]
i see your problem here it says following error `Error: ["WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this."`

at end it tells you to set the LC_ALL environment variable to fix this seems to be way to fix your problem but idk how exactly.

**Comment by DanielnetoDotCom** [comment]
if the youtube-DL does not provide thumbs for embed videos we cannot grab it.

**Comment by akorsonsky** [comment]
thanks @jakesullyneytiri and @DanielnetoDotCom for the response.
For  The LC_ALL as i say ;

i try to configure the LC_ALL with dpkg-reconfigure locales
i put only en_US.UTF-8, then only fr_FR.UTF-8 (encoding from my country), and the twice en_US and fr_FR.
Always same problem.

Daniel i understand that if youtubedl can't grab i have nothing but when i add by myself the 5 picture in editing the video (the 2 jpg, the 2 gif and the webP) i always have nothing not any picture. i have buy the module MP4ThumbsAndGif and i can't make it working too :(
