### ISSUE TITLE
Add category 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#4621]
Please add a "add category" to this selection menu.
![Screenshot_20210226-145744_Brave.jpg](https://user-images.githubusercontent.com/66537018/109349507-0f9d2c00-7844-11eb-83ca-e1e23c0d7f5c.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, what page is that?

**Comment by fakeologist** [comment]
That's the category page that pops up in the drop down menu from add video from url in encoder.

**Comment by fakeologist** [comment]
bump

**Comment by DanielnetoDotCom** [comment]
But is that an encoder or streamer?

please provide a screenshot/url of where did you get this screen

**Comment by fakeologist** [comment]
Check this
https://linksharing.samsungcloud.com/gpgVsbUpyDZd

**Comment by DanielnetoDotCom** [comment]
Hi I am still seeing only the list, I need to see what form/page this list come from

**Comment by fakeologist** [comment]
it's from the encoder page.

**Comment by fakeologist** [comment]
Thanks for that - but it won't let me as admin add a category.
![image](https://user-images.githubusercontent.com/66537018/110946697-33b14080-830d-11eb-9960-868a638f034a.png)

**Comment by DanielnetoDotCom** [comment]
I test it on demo site and it is working.

also tested on your and it works

![image](https://user-images.githubusercontent.com/18009293/110952288-cd381c80-8324-11eb-8e46-f870532097c7.png)


Please make sure you are using the admin user.

**Comment by fakeologist** [comment]
https://streamable.com/z83uo9

**Comment by DanielnetoDotCom** [comment]
Hi, 

looks like you are using safari?

I tested it on chrome windows.

**Comment by fakeologist** [comment]
I use Brave (chrome engine) and Google chrome to test.
