### ISSUE TITLE
User Extra Information

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4623]
Hi hi. can you add a user's extra information to his channel?. Maybe in a new tab

![image](https://user-images.githubusercontent.com/76112286/109381335-7c670380-78e2-11eb-9a4c-91ccd8ac3059.png)

At the moment only admin can see extra information.

**Comment by DanielnetoDotCom** [comment]
If you want to display extra info, add it on the user about area

![image](https://user-images.githubusercontent.com/18009293/109495777-7b62dd00-7a6e-11eb-819f-ef3549c6fc5c.png)

![image](https://user-images.githubusercontent.com/18009293/109495817-8a498f80-7a6e-11eb-939c-448f53d0de1d.png)

**Comment by unconservo** [comment]
Hi hi. Its just easier to have a tab with extra information. Then we can
add different custom fields to display like links to user's linked in
accounts etc. If you add all information to about then about get very long.
