### ISSUE TITLE
Different encoders show up to date but they are not

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4624]
HI. I have 2 encoders installed and also using the AVideo Encoder Network. Encoders give different version numbers but shows up to date. How do I update it if it does not give option to update?

![image](https://user-images.githubusercontent.com/76112286/109381878-99510600-78e5-11eb-839d-fbcf4ed9cb5b.png)

![image](https://user-images.githubusercontent.com/76112286/109381895-b08ff380-78e5-11eb-8e61-c0b4609ec871.png)

**Comment by DanielnetoDotCom** [comment]
First, update the source

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by unconservo** [comment]
Hi. The source (Streamer site) is up to date

**Comment by DanielnetoDotCom** [comment]
Make sure you did a `git pull` command on the encoder and streamer
