### ISSUE TITLE
Views on Live streams

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4625]
Hi hi :)

I see if I livestream a new livestream the views do not reset to 0. It keeps the previous stream view counts

![image](https://user-images.githubusercontent.com/76112286/109382139-46784e00-78e7-11eb-8ca1-7389ab772f56.png)

**Comment by DanielnetoDotCom** [comment]
Reset the key, it will reset the counter.

![image](https://user-images.githubusercontent.com/18009293/109496254-2ecbd180-7a6f-11eb-8ac0-48979a9f5fa9.png)

**Comment by unconservo** [comment]
Thanx :). I will try it and revert back to you
