### ISSUE TITLE
Usergroups cannot see live streams

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4626]
Hi hi :)

When I add a user to a usergroup "Subscribers" and set live stream to not show public and select the "Subscribers" group, Save,, users that are in the group cannot see the live stream. No users can except for the streaming user

![image](https://user-images.githubusercontent.com/76112286/109383655-7546f200-78f0-11eb-9a0c-7386bdb352f6.png)

![image](https://user-images.githubusercontent.com/76112286/109383679-9f98af80-78f0-11eb-8d0b-3d083aaa90c6.png)

**Comment by DanielnetoDotCom** [comment]
Hi 

if it is not publicity listed it will not be displayed on the notification menu.

But if the user has the link to the live they still can watch it.

![image](https://user-images.githubusercontent.com/18009293/109496821-eeb91e80-7a6f-11eb-9ac2-59e60fb69131.png)


the user group option allows only those user groups to join the live.

**Comment by unconservo** [comment]
Hi hi. Thanx. So they wont see it on frontpage if they are part of the
group?

**Comment by DanielnetoDotCom** [comment]
Only if you make it listed

**Comment by unconservo** [comment]
listed?

**Comment by DanielnetoDotCom** [comment]
Nevermind, I could confirm if they are for have a group they do not appear on the notification.

I will review those options.
