### ISSUE TITLE
LDAP Plugin

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4627]
Hi Daniel,

We are trying now to connect all our services through an LDAP server which will include AVideo, NextCloud and Matrix Element. We want a single account to be able to access them all, however we face the following issue. We already have almost 1000 users registered on the AVideo site and now we wish to move to using LDAP, so how will this move effect the accounts already created on the site?

Will they need to register again? would they loose their channels and videos?
What would be the best way to integrate LDAP without loosing all those accounts and data in case this is what will happen if we switch to LDAP.

Best Regards,

**Comment by DanielnetoDotCom** [comment]
Hi, if the LDAP username is the same as the AVideo username you should have no problem

**Comment by guymass** [comment]
OK thank you we will be testing and hopefully the current users wont be effected.
