### ISSUE TITLE
SecureVideoDirectory not working?

### ISSUE THREAD

**Issue by jakesullyneytiri** [WWBN/AVideo#4628]
Bought the addon SecureVideoDirectory but i did what it wanted me to do and it shows green status.

But when i do direct visit to mp4 file it loads up still it isn't rejecting the access like it should be doing.

So am i missing something? since i got xsendfiles installed and when i pasted required code and restarted apache and then clicked check button it went from red to green color and that i assume it means it can detect that it is working if so then why am i still being able to access the mp4 on direct link viewing? 

Wasn't this supposto block that and make so it can only be played via the website  but no direct access?

If so then did i miss something since it isn't blocking it.

Okay after checking logs i'm getting this: Your XSEND File is not enabled. so how do i enable it?

I guess it's nagging about xsend file module isn't enabled, but i have enabled in plesk under apache section and i ran a install command so now i'm clueless?? it still won't detect that it is installed.

install command that i ran is sudo apt-get install libapache2-mod-xsendfile && sudo a2enmod xsendfile but it isn't helping still.

Update: After doing apachectl -M it it gives me loaded modules in apache and xsendfile is loaded. So idk why plugin is throwing error about it isn't enabled?? makes no sense.

Update 2: Okay after digging more i think i found actual problem, i checked this page https://github.com/WWBN/AVideo/wiki/SecureVideosDirectory-Plugin and there it told me to uncomment following code .htaccess file:

`<IfModule mod_xsendfile.c>
    RewriteRule    ^videos/([A-Za-z0-9-_.]+)$ view/xsendfile.php?file=$1    [NC,L]
</IfModule>`

I found diffirent code that looks like this instead:
`    <IfModule mod_xsendfile.c>
        RewriteRule    ^videos/([^!#$&'()*+,\/:;=?@[\]]+(\.(mp4|webm|m3u8|mp3|ogg)))$ view/xsendfile.php?file=$1    [QSA]
    </IfModule>`

That was already uncommented and i thought maybe it's old one so i commented it and added same one from link and that threw XSEND FILE is not enabled error tons of times, but once i commented new code and un-commented old code and saved the script stopped spamming about XSEND FILE is not enabled. So idk why guide is showing wrong code. It needs updating i guess.

But addon is still not protecting mp4 files. Like if i copy direct link open a another browser with proxy use and i paste url in, it opens file and plays it anyway. it doe not stop direct access to file :/

**Comment by DanielnetoDotCom** [comment]
You MUST enable the xsend module to be able to protect your files

https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

**Comment by jakesullyneytiri** [comment]
> You MUST enable the xsend module to be able to protect your files
> 
> https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

Did you even read through my comment? It is enabled yet I can still access files on direct link. It won't block direct access.

**Comment by DanielnetoDotCom** [comment]
Probably is possible to make it work, but the thing is I cannot support you on Plesk

![image](https://user-images.githubusercontent.com/18009293/109424069-e81f9e00-79c0-11eb-90df-eb4e1b170e1e.png)

**Comment by DanielnetoDotCom** [comment]
Try to remove teh `<IfModule mod_xsendfile.c>` from the .htaccess

`RewriteRule ^videos/([^!#$&'()*+,\/:;=?@[\]]+(\.(mp4|webm|m3u8|mp3|ogg)))$ view/xsendfile.php?file=$1 [QSA] `

If you remove it do not work properly you must find a way to enable the XSEND or try a clean Ubuntu without plesk

**Comment by jakesullyneytiri** [comment]
> Try to remove teh `<IfModule mod_xsendfile.c>` from the .htaccess
> 
> `RewriteRule ^videos/([^!#$&'()*+,\/:;=?@[\]]+(\.(mp4|webm|m3u8|mp3|ogg)))$ view/xsendfile.php?file=$1 [QSA] `
> 
> If you remove it do not work properly you must find a way to enable the XSEND or try a clean Ubuntu without plesk

well again module is enabled to what status i said i wrote in ssh that executes module list from apache itself and xsendfile module is listed in that loaded module list. So module is loaded and enabled, but direct access to mp4 is still accessible without a token or so.

**Comment by DanielnetoDotCom** [comment]
Make sure you try it from an incognito browser

If still allowing you to see the video I can only suppose your xsendfile is not enabled, even if you are saying it is.

**Comment by jakesullyneytiri** [comment]
> Make sure you try it from an incognito browser
> 
> If still allowing you to see the video I can only suppose your xsendfile is not enabled, even if you are saying it is.

well it is, since a command such as apachectl -M wouldn't lie about what modules are uploaded. 

Ever heard fault could be in plugin itself?

Here is a picture of proof that module is loaded and enabled according to apache itself!
![cmd_K0IS3gNh69](https://user-images.githubusercontent.com/4062640/109427222-a824df00-79f1-11eb-9283-92333720b1eb.png)

**Comment by DanielnetoDotCom** [comment]
It is working on demo site and hundreds of other sites.

did you at least have tried this https://github.com/WWBN/AVideo/issues/4628#issuecomment-787470813 ??

**Comment by DanielnetoDotCom** [comment]
I just realize one thing ...

are you using B2??

if your bucket is public all your videos are public. you must make it private.

**Comment by DanielnetoDotCom** [comment]
Also make sure the customizeadvanced->doNotUseXsendFile is unchecked
