### ISSUE TITLE
Directory /var/www/html/YouPHPTube/objects/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777

### ISSUE THREAD

**Issue by GBANA** [WWBN/AVideo#4629]
When i click direct upload button 
this error occur how can i solve it :(
Directory /var/www/html/YouPHPTube/objects/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777

**Comment by DanielnetoDotCom** [comment]
On the terminal type


`sudo chmod 777 -R var/www/html/YouPHPTube/objects/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer`
