### ISSUE TITLE
backblaze b2 storage not working

### ISSUE THREAD

**Issue by jakesullyneytiri** [WWBN/AVideo#4630]
So i bought this addon but problem is i follow tutorial video exactly but i still cannot get damn addon working.

In the log file it keeps accessing some php file where it only recives that it is in maintenance every time. So what is point of this addon if it cannot submit any files to backblaze b2 storage???

Even it's test.php does same message that it is under maintenance.

So how do i fix this?

**Comment by DanielnetoDotCom** [comment]
check the log file

**Comment by jakesullyneytiri** [comment]
> check the log file

i have done that but it isn't giving me much but message that it's getting the maintenance message.

**Comment by jakesullyneytiri** [comment]
Update: Okay i finally got it to work,

Next question is it uploads mp4 files but how come it does not upload thumbnails?

**Comment by DanielnetoDotCom** [comment]
Only the videos will be stored on B2, all other metadata will be stored on your local server

**Comment by jakesullyneytiri** [comment]
> Only the videos will be stored on B2, all other metadata will be stored on your local server

well problem is site cdn even thumbnails so it must store thumbnails on blackblaze too then.

**Comment by DanielnetoDotCom** [comment]
Use this for your thumbs CDN

![image](https://user-images.githubusercontent.com/18009293/109426399-5a49b000-79cc-11eb-9659-23d6f7e2819f.png)

**Comment by jakesullyneytiri** [comment]
> Use this for your thumbs CDN
> 
> ![image](https://user-images.githubusercontent.com/18009293/109426399-5a49b000-79cc-11eb-9659-23d6f7e2819f.png)

that is what i got, but problem is thumbnails aren't being uploaded to backblaze b2 storage. So it cannot find thumbnail.

**Comment by DanielnetoDotCom** [comment]
It will NOT be uploaded

![image](https://user-images.githubusercontent.com/18009293/109426999-1906cf80-79cf-11eb-943a-ad6c14fc1a92.png)

**Comment by jakesullyneytiri** [comment]
> It will NOT be uploaded
> 
> ![image](https://user-images.githubusercontent.com/18009293/109426999-1906cf80-79cf-11eb-943a-ad6c14fc1a92.png)

Again it must be or how else is new uploaded videos going to get their thumbnail?

**Comment by DanielnetoDotCom** [comment]
Did you try to see if a new video will get the thumbnail?

I guess you did not try

**Comment by jakesullyneytiri** [comment]
> Did you try to see if a new video will get the thumbnail?
> 
> I guess you did not try
> 

Yes I did and it did not get the thumbnail. It gave 404 image not found. Since there is only mp4 files there and no gif or jpg.

**Comment by DanielnetoDotCom** [comment]
It supposes to work and it has nothing to do with the images on B2 or not.

I guess there is a misconfiguration somewhere

If I understand you are using the customizeAdvanced to add a CDN in your Backblaze, what is wrong.

For your Backblaze files setup the CDN here 

![image](https://user-images.githubusercontent.com/18009293/109429904-2cb93280-79dd-11eb-8d59-334fa5ddd72b.png)

For all self-hosted media also your thumbnails (if you are using a CDN for it) set it up here

![image](https://user-images.githubusercontent.com/18009293/109430306-6e4add00-79df-11eb-8918-d4574072384e.png)

**Comment by jakesullyneytiri** [comment]
> It supposes to work and it has nothing to do with the images on B2 or not.
> 
> I guess there is a misconfiguration somewhere
> 
> If I understand you are using the customizeAdvanced to add a CDN in your Backblaze, what is wrong.
> 
> For your Backblaze files setup the CDN here
> 
> ![image](https://user-images.githubusercontent.com/18009293/109429904-2cb93280-79dd-11eb-8d59-334fa5ddd72b.png)
> 
> For all self-hosted media also your thumbnails (if you are using a CDN for it) set it up here
> 
> ![image](https://user-images.githubusercontent.com/18009293/109430306-6e4add00-79df-11eb-8918-d4574072384e.png)

your tutorial video told me to use custom advanced CDN and not one in backblaze. But i still would like to use thumbnails on backblaze since it would be great to have them there too with videos, secondly i want to move existing videos to backblaze which is another reson.

**Comment by DanielnetoDotCom** [comment]
Again, we will not upload thumbs to Backblaze, there is too much io to make it remotely.

We do not have a script to upload the current movies

**Comment by jakesullyneytiri** [comment]
> Again, we will not upload thumbs to Backblaze, there is too much I/O to make it remotely.
> 
> We do not have a script to upload the current movies

well maybe you guys can add switch in plugin for users who has plugin to be able to have thumbnails there if they like. So then you can choose.
