### ISSUE TITLE
Not so much an issue but more an odd observation

### ISSUE THREAD

**Issue by ustoopia** [WWBN/AVideo#4633]
I've been using AVideo / YouPHPTube for several years now. I think it's an awesome package. Of course I've seen the message from the Dev about how the hard work they had on the site wouldn't have been possible without their beliefs. I can respect that. I think it's their right to ask users not to use the script for any bad or negative things. I always interpreted it in such a way that building a porn site would go against the wishes of the creators. Like I said, I totally respect that, and it makes total sense to me. I even salute your efforts in doing so because by disallowing things like I just mentioned, you're setting boundaries, and more importantly, you're indirectly communicating a message out to the world that there are still people who prioritize to "do good" and help other people to "do less bad". Being very outspoken about this specific thing and communicating it may seem weird or odd to other people, but even those other people DO respect these choices. Basically what I'm trying to say that I see the whole thing as a very positive thing. 

Having said that...... I found it a bit odd that when I was looking at how the index,php in root folder is built up, I noticed a URL. I got curious and tried to open this url but got some generic error response. Still curious at what it was I opened the url but I left out the gif file it is linked to but page could not be found. So then I just opened the url just by using the top-level domain name. The results being... a bit strange... . It showed me a very colorful page with mostly chinese characters, and an overkill of banners containing animated gifs that clearly belong to pornographic websites. I'm a big boy so I wasn't bothered by this , but it did make me put the beliefs of the devs and this experience together and felt I had to share it.  Perhaps there's an explanation why there is a link to such a network in the index.php file? Or perhaps nobody has ever noticed that the gif it is linked to is not behaving properly, or perhaps... and i literally just though of this, maybe I've been hacked? (I checked and the URL is in the github so I'm less likely to think that it was a hack. 

So many words for such a minor, odd, little observation?? Enough said... 

Regards,
André 

![Image3](https://user-images.githubusercontent.com/28495625/109477209-0bf1eb00-7a78-11eb-9cd5-ed46830c7085.png)

**Comment by DanielnetoDotCom** [comment]
Hi, where exactly did you find it?

**Comment by ustoopia** [comment]
https://github.com/WWBN/AVideo/blob/master/index.php

 

line 49

**Comment by DanielnetoDotCom** [comment]
Hi

you may have a virus or a spyware in your PC. The image opens fine here

**Comment by ustoopia** [comment]
No. It was just me. I tried it again just now and an image does get loaded, I just couldnt see it the previous time because it blends with the background on my end. But, who cares, right?
My post wasn’t about the image loading or not loading.. did you see the website that the image belongs to? With the pornographic gifs and all the banners..  If I was you i’d copy the image elsewhere, to make sure nobody else finds their way to that (perhaps malicious?) website. 

Just my two cents 🧐. Don’t take it, or me for that matter, too seriously 😶🙄

Grtz

Verstuurd vanaf mijn iPhone

**Comment by DanielnetoDotCom** [comment]
Hi, 

what I mean is this

![image](https://user-images.githubusercontent.com/18009293/109527174-220ca500-7a92-11eb-974e-ff2827f15dbb.png)

The image loads fine. but I will remove that anyway. we do not need it, thanks
