### ISSUE TITLE
Videos not uploading after encoding 100mb CF limit again.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4634]
For some reason after the last 3 encoder updates videos do not make it to the website anymore if they r too large. 

What happened to it downloading the video instead of uploading it to bacblaze?

**Comment by JoshWho** [comment]
This seems like the time when it use to not upload in chunks and kept triggering cloudflare file upload limit,

**Comment by DanielnetoDotCom** [comment]
Hi, just confirming it is encoding but is not transferring to the streamer?

**Comment by JoshWho** [comment]
Correct. I am not seeing it listed in the video dashboard. Some files if small I will see the Low Mp4 but the HD never shows. If it is a long video none of them show.

**Comment by JoshWho** [comment]
https://www.joshwhotv.com/v/37400

**Comment by baoang** [comment]
how about TLS setting? TLSv1.3 might be higher, and try to lower it to, say CF default 1.0. if it worked, then could turn to 1.1/1.2
