### ISSUE TITLE
Stripe subscription cannot be cancelled 

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#4635]
A user couldn't cancel his subscription by clicking the cancel subscription. 

I tried to cancel it manually from Stripe plugin -> list subscriptions -> cancel. It didn't work - nothing happened. 

There was no log entries. 

This has worked before for sure. 

edit:

when I deleted the subscription from Stripe site it deleted it from mysite. So the connection between Stripe and mysite works. So there is something wrong with the plugin.

**Comment by DanielnetoDotCom** [comment]
maybe it's because you tried to cancel an already canceled subscription?

maybe the error is on the stripe side?

we really need the logs at the time you tried to cancel even if there is no error.

**Comment by tonuzo** [comment]
I made test subscription and then tried to cancel it, I got this error:

ERROR!
Empty Stripe Customer ID

**Comment by tonuzo** [comment]
I got same error on flix.avideo.com site. Can't cancel.

**Comment by DanielnetoDotCom** [comment]
Hi, I have an idea why it may be, after I changed the code to attend Strong Customer Authentication (SCA), it may be broken, I need some time to review.

I guess cancel will not be possible anymore as long as we do not create a customer on Stripe anymore, but I will review it.

**Comment by tonuzo** [comment]
Ok, thanks. Hope you'll find a way. Of course there must be a possibility for a user to cancel the subscription..

**Comment by tonuzo** [comment]
> I guess cancel will not be possible anymore as long as we do not create a customer on Stripe anymore, but I will review it.

I don't know what you mean by this? But creating Stripe customer works normally through this plugin. Only cancellation doesn't work.

**Comment by tonuzo** [comment]
Hi @DanielnetoDotCom 

have you reviewed this yet?

**Comment by DanielnetoDotCom** [comment]
Sorry I did not yet

**Comment by DanielnetoDotCom** [comment]
Hi, the update to let you cancel was sent.
you will need to update the streamer with git pull

and the Subscription plugin to v4.1

**Comment by tonuzo** [comment]
Hi, thanks for this! 

Only now the problem is that I still can't cancel and the error says "Subscription not found" instead of "Empty Stripe Customer ID"

here's the log line it generated (nothing else):

[26-Mar-2021 12:19:34] AVideoLog::DEBUG: StripeYPT::getSubscriptions ERROR cus_J3OFCw7rr33DHuXex, 8 {"id":"cus_J3OFCw7rr33DHuXex","object":"customer","address":null,"balance":0,"created":1614865436,"currency":"eur","default_source":"card_1IR4GX23mwT5IGSrc","delinquent":false,"description":"Customer [2] myemail@mydomain.com SCRIPT_NAME: /plugin/StripeYPT/subscriptionCancel.json.php

**Comment by DanielnetoDotCom** [comment]
Hi

you probably already delete this subscription on stripe panel .
I have tested locally and it is working 

can you please try with a new subscription?

**Comment by tonuzo** [comment]
The subscription is still active. The same error appears when I try to click STRIPE-button from subscription-plugin panel.

![image](https://user-images.githubusercontent.com/63721378/112621057-faf78800-8e31-11eb-9aa4-c54df57e8d35.png)

**Comment by tonuzo** [comment]
[26-Mar-2021 12:49:53] PHP Warning:  Invalid argument supplied for foreach() in path/to/my/streamer/site/plugin/StripeYPT/StripeYPT.php on line 315

**Comment by tonuzo** [comment]
[26-Mar-2021 12:55:33] AVideoLog::DEBUG: getSubscription: {"id":17,"users_id":8,"subscriptions_plans_id":5,"created":"2020-06-01 10:09:58","modified":"2021-02-26 13:12:23","good_until":"2021-03-28 10:45:00","status":"a","**agreement_id":""**,"stripe_costumer_id":"cus_HNwvLUkJAr","gateway":"Stripe","gateway_subscriptions_id":""} - [8,5,true,"a"] - SELECT * FROM  subscriptions WHERE users_id=? AND subscriptions_plans_id=?  AND good_until > now()   AND status = 'a'  SCRIPT_NAME: /plugin/StripeYPT/listSubscriptions.php

Should there be something inside agreement_id? I can see it's empty here in the log file if I list subscriptions on subscriptions-plugin.

**Comment by tonuzo** [comment]
Didn't work with new subscription either.

**Comment by DanielnetoDotCom** [comment]
agreement_id is for PayPal

did you check the Customer's subscription cus_HNwvLUkJAr in your Stripe panel?

the error means we could not find on stripe the subscription you are trying to cancel

For example, you will be able to see the customer code here 

![image](https://user-images.githubusercontent.com/18009293/112684749-40c44880-8e52-11eb-9697-ad3cbbdb4013.png)

Then you can see all the subscriptions 

![image](https://user-images.githubusercontent.com/18009293/112684677-1ecac600-8e52-11eb-983a-6e7f24f1b81f.png)


maybe this customer was deleted?? I am pretty sure this do not exists anymore, the info is showing a canceled one

**Comment by tonuzo** [comment]
Unfortunately it's not the case... 


![image](https://user-images.githubusercontent.com/63721378/112713980-c55da800-8ee0-11eb-87a2-0ac2ae6a9632.png)

**Comment by tonuzo** [comment]
This is very hard to figure out. I have everything set as they should be. 
What is your stripe endpoint version? 

I have: 
![image](https://user-images.githubusercontent.com/63721378/112748405-08dd1280-8fc4-11eb-8bae-c5e58d991866.png)

**Comment by tonuzo** [comment]
Subscription creations and updates works as they should so there must be subscription information somewhere available.

**Comment by tonuzo** [comment]
I made a little investigation and if your API version is different than mine it probably is the problem. Stripe doesn't allow to downgrade the API version from Stripe side - as far as I understood.

**Comment by tonuzo** [comment]
Is this any helpful?
https://stripe.com/docs/api/versioning?lang=php

**Comment by DanielnetoDotCom** [comment]
Hi, I may need to look it directly into your server, it is working on my side.

please contact me so we can schedule a meet and a screenshare.
