### ISSUE TITLE
Site Combine issue

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4636]
I am trying to combine a third site to the list but I get this error, this is our same EDU server that its encoder doesn't appear on the Network Encoder, maybe those issues are related. Here is the screen shot when I try to view the site from the other Live site.

![Screen Shot 5781-06-21 at 0 24 15](https://user-images.githubusercontent.com/58882903/110039174-8442ff80-7d49-11eb-8ecb-67e9d6e9221b.jpg)

**Comment by guymass** [comment]
Having the same issue on EDU trying to get the list form Live

![Screen Shot 5781-06-21 at 11 54 58](https://user-images.githubusercontent.com/58882903/110099166-a9fff100-7da9-11eb-8192-3058f07df55c.jpg)

**Comment by DanielnetoDotCom** [comment]
This feature is not working properly yet. I will back on this development in the future

**Comment by guymass** [comment]
OK Thanks

**Comment by maxlinux2000** [comment]
+1
