### ISSUE TITLE
Simply Plugin Decryption

### ISSUE THREAD

**Issue by ejb1123** [WWBN/AVideo#4637]
I am having issues extending the plugins that I have bought from you. I have quickly worked out how some of the encryption is handled. If you take look at [this Gist](https://gist.github.com/ejb1123/55986144a8aa84990abd719e8defbe7e) you will find that the obfuscation is somewhat lacking. 

To save everyone some time and effort in the future, Do you have ability to help out the community by writing a tool so we can effortlessly extend AVideo and grow the platform.

**Comment by DanielnetoDotCom** [comment]
Hi, you may are looking for that

https://github.com/WWBN/AVideo/wiki/How-to-code-a-AVideo-Platform-plugin

**Comment by ejb1123** [comment]
For anyone who is looking for a solution to this problem please checkout [this gist](https://gist.github.com/ejb1123/e8fca34474fa1ec64cfc2d7ae8719064).

**Comment by DanielnetoDotCom** [comment]
FYI

the encryption is just to make harder the edition . Is forbidden to share it . Including publish helping how to do it. I need to ask you to remove the posts you have made offering help to decrypt it. Thanks

**Comment by ejb1123** [comment]
So I can better understand the situation can you show where that is defined at Daniel?

**Comment by DanielnetoDotCom** [comment]
Please check here https://youphp.tube/marketplace/

![image](https://user-images.githubusercontent.com/18009293/110181413-8315df00-7dea-11eb-9932-18bd024aae57.png)

**Comment by ejb1123** [comment]
While I have no intention on redistributing your plugins. I have no intention on taking it down. Please post a DMCA request to GitHub.
QZLm9Fpu

**Comment by DanielnetoDotCom** [comment]
I think the policy is very clear, please remove the posts.
