### ISSUE TITLE
Restream, I can't...

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4638]
@DanielnetoDotCom , @akhilleusuggo hello guys

I'm having a problem with my restreamer. I have set it up accordingly but no restreaming is taking place

![rs4](https://user-images.githubusercontent.com/65451390/110176946-31367e80-7e15-11eb-8663-c5cf67352aa3.PNG)
^ is my restreamer file

![rs3](https://user-images.githubusercontent.com/65451390/110176977-3eec0400-7e15-11eb-88a7-867ed96e8333.png)
^ is my attempt to restream to youtube. yes i have also tried youtube-rtmp but no success

![Inkedrs2_LI](https://user-images.githubusercontent.com/65451390/110177229-b15ce400-7e15-11eb-9bfa-96b7cdb3de43.jpg)
^ is my live server setup. i am able to stream to it successfully.

![rs5](https://user-images.githubusercontent.com/65451390/110182609-2af8d000-7e1e-11eb-9987-2a077cea097f.PNG)
^is the error i get when i access the restreamer from the browser, yet i have set 2 restream destinations

--------------------------
AVideoLog::DEBUG: NGINX Live::on_publish end SCRIPT_NAME: /plugin/Live/on_publish.php
AVideoLog::DEBUG: Live:restream (https://www.mysite.com:9998/restreamer.json.php) {"m3u8":"https:\/\/www.mysite.com:9***\/live\/60******ce\/index.m3u8","restreamerURL":"https:\/\/www.mysite.com:9***\/restreamer.json.php","restreamsDestinations":["https:\/\/a.upload.youtube.com\/http_upload_hls?cid=*****-b48b-ebjg-*****&copy=0&file=\/*****-b48b-ebjg-****","https:\/\/b.upload.youtube.com\/http_upload_hls?cid=*****-b48b-ebjg-***&copy=1&file=\/*****-b48b-ebjg-****"],"token":"Uk9UOXg1REtGRmNMOXl**********SWjQrcDk3K0R3Y0Ewc0hOZExLenc5djNKY0VjNWE3R2dIMmN0U2paWGo***********==","users_id":1} SCRIPT_NAME: /plugin/Live/on_publish.php
AVideoLog::DEBUG: NGINX Live::on_publish start SCRIPT_NAME: /plugin/Live/on_publish.php
AVideoLog::DEBUG: NGINX ON Publish success SCRIPT_NAME: /plugin/Live/on_publish.php
AVideoLog::DEBUG: NGINX ON Publish deciding ... SCRIPT_NAME: /plugin/Live/on_publish.php
AVideoLog::DEBUG: NGINX ON Publish saved LiveTransmitionHistory SCRIPT_NAME: /plugin/Live/on_publish.php
AVideoLog::DEBUG: NGINX ON Publish saving LiveTransmitionHistory SCRIPT_NAME: /plugin/Live/on_publish.php
AVideoLog::DEBUG: NGINX ON Publish get LiveTransmitionHistory SCRIPT_NAME: /plugin/Live/on_publish.php
AVideoLog::DEBUG: NGINX ON Publish new User(1) SCRIPT_NAME: /plugin/Live/on_publish.php
AVideoLog::DEBUG: NGINX ON Publish key exists return myemail@mydomain.com 00:31:40","modified":"2021-03-05 16:25:33","isAdmin":1,"status":"a","photoURL":null,"lastLogin":"2021-03-06 00:53:24","backgroundURL":null,"canStream":1,"canUpload":1,"canCreateMeet":1,"canViewChart":1,"about":"","channelName":"GOLIVEAFRICA","emailVerified":1,"analyticsCode":"","externalOptions":"*********cmsxIjtzOjU6ImZhbHNlIjtzOjEwOiJjaGVja21hcmsyIjtzOjU**************","first_name":null,"last_name":null,"address":null,"zip_code":null,"country":null,"region":null,"city":null,"donationLink":"","extra_info":null,"title":"*****TEST","public":1,"saveTransmition":0,"key":"60********ce","description":"*****-TEST","users_id":1,"categories_id":1,"showOnTV":0} SCRIPT_NAME: /plugin/Live/on_publish.php
--------------------------

^ my logs

Is there something I am missing?

1. I have rebuilt and recompiled ffmpeg
2. I also have the latest update as well.

Please help
Thanks.

**Comment by jengajenga** [comment]
@DanielnetoDotCom , @akhilleusuggo  some help please guys... thanks

**Comment by akhilleusuggo** [comment]
@jengajenga check this url ; looks wrong for me ; 

If I'm not wrong should be an RTMP url , not a upload something .

![image](https://user-images.githubusercontent.com/52116577/110246172-31e32800-7f6f-11eb-8ad4-ee5ea9aa078c.png)

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo is correct, it should look like something like this

## External server
![image](https://user-images.githubusercontent.com/18009293/110328080-9ea30480-7ff9-11eb-8fb7-5a573f86263f.png)


## Restreamer
![image](https://user-images.githubusercontent.com/18009293/110327923-63083a80-7ff9-11eb-97a7-140b46776b4f.png)

**Comment by jengajenga** [comment]
Thanks guys. Let me try tonight and I'll get back.

**Comment by DanielnetoDotCom** [comment]
yes they must have https

**Comment by akhilleusuggo** [comment]
@jengajenga Well , in your case you don't need https . You're running on local ip ranges ( 192.X.X.X )
Also you're using port 8080 ( not for encryption ) . RTMP ( is not encrypted either ) .

It should work with what you've linked on the screen .

**Comment by DanielnetoDotCom** [comment]
> @jengajenga Well , in your case you don't need https . You're running on local ip ranges ( 192.X.X.X )
> Also you're using port 8080 ( not for encryption ) . RTMP ( is not encrypted either ) .
> 
> It should work with what you've linked on the screen .

@akhilleusuggo I guess @jengajenga is using https, the screenshots with http://encoder.gdrive.local/ are mine

**Comment by jengajenga** [comment]
I have tried everything I possibly can. 

I've used http and also https - nothing
I have stopped and started and refreshed my streams - nothing
I have used the youtube-rtmp - nothing

I don't know what else to do.

**Comment by jengajenga** [comment]
Let me ask, the way to set the live server, should it be another server? i am currently using my streaming server as the live server. should i use another instance as the live server instead?

**Comment by DanielnetoDotCom** [comment]
Use the streamer being also the live server I cannot see a problem on it.

**Comment by jengajenga** [comment]
i got it to work.
