### ISSUE TITLE
When using the YPTStorage plugin, the update disk usage button in my video's section always resets the file size to 10kb

### ISSUE THREAD

**Issue by jurgenmahn** [WWBN/AVideo#4639]
Issue seems to be here 

Ajax call triggered by the update disk usage button:

_/plugin/CustomizeAdvanced/updateDiskUsage.php'_

**objects/functions.php**
_Function function globVideosDir($filename, $filesOnly = false) {_

Line 5319: $dir = getVideosDir(); is always refering to the original video folder instead of the YTPStorage folder:

See function here: 
objects/video.php

        public static function getStoragePath(){
            global $global;
            $path = "{$global['systemRootPath']}videos/";
            return $path;
        }
        
        
So video files cannot be found and result in "empty" filesize

I can't easily debug the YPTStorage plugin since its encrypted and i'm too lazy to try decrypting it.

**Comment by DanielnetoDotCom** [comment]
On storage, I am not able to get video size for HLS, but it supposes to work for MP4 if you are running the latest Storage and Streamer/plugins.

can you please confirm what file format are you using?

**Comment by jurgenmahn** [comment]
Hi Daniel,

im using video's in MP4 format. Yes im running the latest versions, i did a
fresh clone from github on saturday and also bought the storage plugin
saturday.

But if you're sure everything should work related to this, i will try to do
some more debugging the next few days and see whats going on.

Thanks,
Jurgen
