### ISSUE TITLE
Signup Agreement plugin and More

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4640]
I am trying to create a signup agreement but when I save the entry it wouldn't save the new agreement, so I tried to just create the entry with the title in Hebrew and after refreshing this is what happens. I believe this is causing us many issues trying to enter Hebrew letters in any field on AVideo platform will produce all those long string with %%% which will be rejected by mysql for being too large.

This issue should be handle site wide on all fields in all plugins that have to consider those RTL characters. I currently cannot create anything with this plugin unless I use really short titles which is not a solution and will still convert those letters into those long unreadable strings. Those fields need to be able to decode as well as encode I guess.

![Screen Shot 5781-06-22 at 20 34 57](https://user-images.githubusercontent.com/58882903/110217211-87f69380-7ebb-11eb-87ab-e8bf44fbe30f.jpg)

**Comment by DanielnetoDotCom** [comment]
Can you please paste here what exact text are you trying to use?

**Comment by guymass** [comment]
IT basically any of the Hebrew alphabet characters
אבגדהוזחטיכלמנסעפצקרשתףךםץ

**Comment by DanielnetoDotCom** [comment]
Hi, the plugin v2.0 should be able to handle that
