### ISSUE TITLE
Sourcecode not saved in Doc_type (360 Panorama picture_viewer)

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#4641]
Hi,

When i insert source-code in a doc_type article some elements are not saved.
I have to **save the source-code** into **PhpMyAdmin** to let it work.

Demo on: https://archief.beesel-reuver.nl/article/1587/2021-panorama-reuver---de-witte-stein

![Snap1](https://user-images.githubusercontent.com/39981177/110232659-544d5500-7f1f-11eb-9b48-8319d342d0d0.jpg)
![Snap2](https://user-images.githubusercontent.com/39981177/110232732-df2e4f80-7f1f-11eb-8b67-d900bec800cd.jpg)
![Snap3](https://user-images.githubusercontent.com/39981177/110232742-eead9880-7f1f-11eb-9845-d0b71aa4e009.jpg)

**Comment by DanielnetoDotCom** [comment]
Correct we must clean up the HTML code to avoid mess up the layout 

Currently, we only use the default TinyMCE valid elements list

https://www.tiny.cloud/docs-3x/reference/configuration/Configuration3x@valid_elements/#defaultruleset

**Comment by TLCReuver** [comment]
Thankz for info and indeed the default TinyMCE is the best choice to avoid messing up the layout.
