### ISSUE TITLE
Cannot load video files from PC to Website

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#4645]
Hi 

I seem to be having problems loading video files to website through the "From File" Option in the encoder. I get the following error.

{"files":[{"error":"File is too big","type":"video/mp4","name":"Kollossus ad Flash Light Logo.mp4","size":1015936}]

Tried various sizes but same thing. I have it on the MP4 option....Please advise

**Comment by DanielnetoDotCom** [comment]
what page exactly are you getting it and how are you uploading?

**Comment by kollossus55** [comment]
Hi

I log on to encoder and take the option files
Then press button to choose files, i then look on my local drive in windows, select video file required, then press to upload.. it worked fine before I updated the website.
Please advise..

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DanielnetoDotCom** [comment]
Are you running the latest encoder?

![image](https://user-images.githubusercontent.com/18009293/110338345-a9fc2d00-8005-11eb-9e04-208e1732ff25.png)

**Comment by kollossus55** [comment]
Hi

Yes i upgraded very recently..

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kollossus55** [comment]
Hi

I just logged on again and saw the encoder is 3.1 is that meant to be correct ?

Regards

________________________________

**Comment by DanielnetoDotCom** [comment]
Make a `git pull` and update it to the latest

also please make sure your streamer is up to date.

**Comment by kollossus55** [comment]
Hi
 I am a bit of a novice, need guidance on this.

How do I do all this..

Regards

________________________________

**Comment by kollossus55** [comment]
Hi

Done a git pull, but I cannot find info to update streamer..

Please advise..

________________________________

**Comment by DanielnetoDotCom** [comment]
to update the streamer is also a git pull inside its folder

**Comment by kollossus55** [comment]
Hi

whats the path for the streamer update..

Thanks

________________________________

**Comment by kollossus55** [comment]
Is there a plugin that updates everything automatically..

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kollossus55** [comment]
Hi

Whats the path ?

Thanks

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by kollossus55** [comment]
Thanks

Sorted..
________________________________

**Comment by SergejGrin** [comment]
I got a similar problem:
Updated site to version 11.0 and encoder to 3.8
Now, when you try to add a video, the file is uploaded to the server, but the encoding process does not start and does not go. There is an error message in the logs. What is the problem and how can I fix it?
<img width="2557" alt="Снимок экрана 2021-05-15 в 19 54 30" src="https://user-images.githubusercontent.com/59236880/118373810-ff7e2880-b5b8-11eb-84e8-3ebd4df85749.png">
