### ISSUE TITLE
Unable to Install - Error in JS during page load of install/index.php

### ISSUE THREAD

**Issue by spurgeonbj** [WWBN/AVideo#4646]
**Describe the bug**
On Ubuntu 18.04, when attempt fresh install, console shows internal server error.

**To Reproduce**
Turn on Browser Dev Tools 
Load Install/Index page
Fill in the values
Clicking 'Install button hangs'
Even page load, without filling in install details, throws same 500 http code 

**Expected behavior**
Installer should go to next screen

**Error Logs**
`[08/Mar/2021:20:45:39 +0530] **"GET /view/js/sweetalert/sweetalert.css** HTTP/1.1" **500** 3821 "https://example.org/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36"`

**Screenshots**
![avideo-install-loading-error](https://user-images.githubusercontent.com/6739161/110341602-83171880-8050-11eb-927f-30b6ba1dc7be.png)

**Desktop:**
 - OS: Windows
 - Browser [Chrome]
 - Version [e.g. 89]

**Comment by spurgeonbj** [comment]
Got past the first error -

Took the sweetalert.css from `avideo-encoder/view/js/seetalert/sweetalert.css` and copied it to `/view/js/seetalert/sweetalert.js`

However, there is a new issue that has cropped up ... 

Guess some JS  is not getting loaded...

![avideo-install-loading-error-2](https://user-images.githubusercontent.com/6739161/110345677-dab78300-8054-11eb-908a-b69bb5bbf51f.png)

**Comment by morbificagent** [comment]
Same here on 20.04... :-(

**Comment by spurgeonbj** [comment]
@morbificagent Thanks for your kind update.

Guess that the plugin Layout.php needs to be invoked through install/index.php or one of it's required files...

script.js, has the undefined avideoLoader object...

Pray Daniel will look into this and help...

**Comment by morbificagent** [comment]
@spurgeonbj looks like he has done it already :-) The js is updated and the installation is running...
@DanielnetoDotCom Many thanks

**Comment by spurgeonbj** [comment]
@DanielnetoDotCom God bless you abundantly in all that concerns you dear Daniel!!

@morbificagent Amen to you too!!

Thank you!!
