### ISSUE TITLE
It can't play video on Chromium, but it work on Chrome

### ISSUE THREAD

**Issue by bobken** [WWBN/AVideo#4648]
**Describe the question**
It can't play video on Chromium, but it work(play) on Chrome.

**Screenshots**
The chromium console show error message on below screenshot
![image](https://user-images.githubusercontent.com/1924671/110414390-bb5b3d00-80ca-11eb-86ad-209cd892d2a6.png)

Thanks

**Comment by DanielnetoDotCom** [comment]
Not sure, we need more details, it may be a network problem

**Comment by bobken** [comment]
> Not sure, we need more details, it may be a network problem

Thanks for your reply it.
I try AVideo on IE , Chrome, Firfox and Chromium.
Only the Chromium can't play video, it may be viedo.js (format) problem.
