### ISSUE TITLE
FTP-Plugin: Videos cant be played or deleted

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4650]
Hi together,

installed AVideo yesterday (git clone) and trying to connect it via FTP to a Server.

But at the moment the videos cant be played.

Have bought the plugin and configured it like this:

![ftp](https://user-images.githubusercontent.com/50199132/110477020-f6696a80-80e2-11eb-9add-f42d6023eea6.PNG)

The encoded files are uploaded correctly:
![upload](https://user-images.githubusercontent.com/50199132/110477171-21ec5500-80e3-11eb-8c6c-0beb74bc4701.PNG)

and the files are on the ftp after that:
![files](https://user-images.githubusercontent.com/50199132/110477288-45170480-80e3-11eb-8047-d8e8ce874dd9.PNG)

But if i try to play one i get:
![error](https://user-images.githubusercontent.com/50199132/110477403-6677f080-80e3-11eb-9964-9bed8dce6d54.PNG)

Here is the source:

![source](https://user-images.githubusercontent.com/50199132/110477599-a63ed800-80e3-11eb-8a0b-46fd27cf634b.PNG)

(the dummy files in local filesystem are there)

When i now try to delete the files nothing happens. Only some error-messages in the ftp-log:

![delete](https://user-images.githubusercontent.com/50199132/110478165-5c0a2680-80e4-11eb-889f-3b29d612e6ce.PNG)

The files which where created have different filenames (720 ... 1080 ...) as the once it try to delete (SD ... HD)
Eventually the link between the local dummy-files and the ftp-files is broken?

**Comment by DanielnetoDotCom** [comment]
what is the URL you have into the HTML <source> tag?

Please copy and paste here

**Comment by DanielnetoDotCom** [comment]
No I mean jut the tag, but it works

anyway, check this 

https://video.bit-link.de/videos/_YPTuniqid_60477aa1a4ba07.26716025_1080.mp4
https://video.bit-link.de/videos/_YPTuniqid_60477aa1a4ba07.26716025_720.mp4
https://video.bit-link.de/videos/_YPTuniqid_60477aa1a4ba07.26716025_240.mp4

Those are the links for one of your videos I checked them and they are the dummy files

Did you manually copy them?

not sure how does this happen

**Comment by morbificagent** [comment]
@DanielnetoDotCom no, i didnt copied anything manual...

And the problem is reproduceable. Upload Files to Encoder -> It creates the versions -> it copies the versions to the ftp-server -> it creates dummy files in my local ./videos dir.

If i play the video via the webinterface i get the errormessage i posted and nothing plays. And no FTP-Request is made.

If i try to delete the Video via Webinterface i get an endless waiting-time and it tries to delete the SD, HD,... files which doesnt exist under this name. The existing files arent deleted.

**Comment by morbificagent** [comment]
As you mentioned the webinterface links to the dummy-files as source and i thought inside of them there should be some "internal redirect" to the files on the ftp server?

(dont know the technology behind the ftp plugin)

**Comment by morbificagent** [comment]
If its not so easy to resolve i am searching for an alternative for my scenario.

I am using the ftp plugin on the same server like the rest of AVideo only to put files in an other dir on which www-data doesnt have permissions.

Would be the YPTStorage plugin installed on the same server allow me to put the videos in another dir without giving www-data permissions on that?

**Comment by DanielnetoDotCom** [comment]
So is this your streamer site?

https://video.bit-link.de/videos/_YPTuniqid_60477aa1a4ba07.26716025_240.mp4


what is your FTP site URL (endpoint)? I am pretty sure that is what you are missing.

**Comment by morbificagent** [comment]
Yes, thats the streamer Site.

The FTP is only listening on localhost because its on the same server. And so the plugin is configured like on the first picture...

So the endpoint entered here looks good to me, or not?

**Comment by DanielnetoDotCom** [comment]
Your endpoint MUST be the FTP URL, I mean, the HTTP URL you use to access your files on the FTP server

**Comment by morbificagent** [comment]
Ah ok, so the FTP-Server must have an HTTP-Server on it to serve the files?

Than i misunderstood the Technic behind the plugin as i thought that the Avideo-Server would re-download the files from the ftp-server dynamically for serving it...

**Comment by DanielnetoDotCom** [comment]
> Ah ok, so the FTP-Server must have an HTTP-Server on it to serve the files?

Correct

> Than i misunderstood the Technic behind the plugin as i thought that the Avideo-Server would re-download the files from the ftp-server dynamically for serving it...

This would consume too much from the server and network

**Comment by morbificagent** [comment]
OK, as i have misunderstood this, would it be possible to give the plugin back? ;-)

If not, ok, it was my fault...

**Comment by DanielnetoDotCom** [comment]
Sorry is not possible to return digital contents

**Comment by morbificagent** [comment]
No problem.

A bit more money for this great project cant be bad ;-)
