### ISSUE TITLE
this bug is annoying me any one help me

### ISSUE THREAD

**Issue by antuk21** [WWBN/AVideo#4654]
every time i go live the gallery dose not work proper and i keep getting a error here my log!
soon i start obs and go live the category that are suppose to show the live it dont its just vanish stange

**Comment by antuk21** [comment]
right so wen i set my perms to sudo chmod -R 777 /var/www/html/AVideo/view/configurations.phpvideos
every thing works but cant save as this comand came up agen  any way i can fix that 
https://prnt.sc/10hr0ai  soon i put the perms back to  this  chown -Rf ant:www-data /var/www/html

the gallery works normal i dno

**Comment by jengajenga** [comment]
hi. for security purposes, you should mask or redact some important data.
