### ISSUE TITLE
The Chat2 plugin don't wont on Chat Stand Alone mode

### ISSUE THREAD

**Issue by bobken** [WWBN/AVideo#4655]
**Describe the question**
I try to setup and use Chat2 (version 5.0) plugin, and reference https://github.com/WWBN/AVideo/wiki/Chat2-Plugin,
but it show php errror on error log, please see screenshots.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.
![image](https://user-images.githubusercontent.com/1924671/110587519-c2f41200-81ae-11eb-819d-e864f4446e43.png)

**Comment by DanielnetoDotCom** [comment]
I guess you are getting this error because your sys_get_temp_dir is not writable.

this is very common on a shared host

**Comment by bobken** [comment]
> I guess you are getting this error because your sys_get_temp_dir is not writable.
> 
> this is very common on a shared host
The sys_get_temp_dir setting is '/tmp'
It permission mode is 777 (writable)

**Comment by DanielnetoDotCom** [comment]
The permission does not mean you can write.

also, I guess you are using some type of control panel, this is probably restricting you to use the temp folder

that is one of the reasons we recommend you to NOT use any type of control panel

**Comment by bobken** [comment]
I don't use control panel (I don't know what is control panel).

**Comment by akhilleusuggo** [comment]
like Cpanel and others 

Also on your error , your apache2 home directory is `/var/www/?` have you changed it ? Because by default is `/var/www/html`
Before further debugging , try reaching ( accessing ) to the chat from the browser .

**Comment by bobken** [comment]
> like Cpanel and others
> 
> Also on your error , your apache2 home directory is `/var/www/?` have you changed it ? Because by default is `/var/www/html`
> Before further debugging , try reaching ( accessing ) to the chat from the browser .
Thank you.
No, my apache2 home directory is /var/www/Chat2 (<= it's only for Chat2 server).
and the below image is a test page(php info) on /var/www/Chat2 directory
![image](https://user-images.githubusercontent.com/1924671/111096751-2f8a5a80-857b-11eb-8a17-771928626a32.png)

**Comment by morbificagent** [comment]
Same problem here :-(

my /tmp dir is writeable and its a dedicated root server and nothing shared...

**Comment by DanielnetoDotCom** [comment]
I just update Chat2 v5.4 to allow you to use the folder `standAlone/tmp/` as a temp folder in case your sys_get_temp_dir() fails

**Comment by morbificagent** [comment]
Not sure if its the same at my site:

![image](https://user-images.githubusercontent.com/50199132/111161246-388b2400-859b-11eb-9133-1d4eb5024c2e.png)

**Comment by DanielnetoDotCom** [comment]
@morbificagent looks like the same, please update the Chat2

**Comment by morbificagent** [comment]
OK, updated it on Streamer and Chat-Server.
First it was saying i have to create the standalone/tmp dir and give 777 permissions and after that the index.php gave me the page which was shown in the tutorial:

![image](https://user-images.githubusercontent.com/50199132/111168832-b868bc80-85a2-11eb-86d5-d8d5cb160dd9.png)


But if i enter a site on the streamer hopefully with a chat i get:

![image](https://user-images.githubusercontent.com/50199132/111168994-dfbf8980-85a2-11eb-8fb9-cacff788ebcf.png)

**Comment by morbificagent** [comment]
The browser says:
![image](https://user-images.githubusercontent.com/50199132/111170592-64f76e00-85a4-11eb-8455-f9303a392241.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I just sent a new fix for that v5.5

But you know what...
Since the sockets plugin, the local version of chat2 has better performance than the Chat2 in a separate server. I guess you should try to stick on the local Chat2 + YPTSocket

**Comment by morbificagent** [comment]
so i will try out v 5.5...

how do i install the local Chat2 + YPTSocket?

Any Howto for that?

**Comment by DanielnetoDotCom** [comment]
It is easier than in another server.

Just enable the plugin and install the database and for the Socket check this https://github.com/WWBN/AVideo/wiki/Socket-Plugin

**Comment by morbificagent** [comment]
OK, updated to 5.5:

![image](https://user-images.githubusercontent.com/50199132/111175730-fff24700-85a8-11eb-9be8-c8c837ec3b83.png)

I will try to install the YPTSocket...

**Comment by morbificagent** [comment]
> Just enable the plugin and install the database and for the Socket check this https://github.com/WWBN/AVideo/wiki/Socket-Plugin

ok, did so... but how do i configure the connection between the chat-plugin on the streamer and the chat-db?
In the config.php on the  streamer?

And if yes whats whis these lines?

$global['systemRootPath'] = '/var/www/AVideoChat';
$global['serverName'] = 'Chatserver 1';
$global['webSiteRootURLStandAlone'] = 'https://chat.bit-link.de/';
$global['webSiteRootURL'] = 'https://video.bit-link.de/';
$APISecret="0af9

**Comment by DanielnetoDotCom** [comment]
You do not need to edit the chat standalone, it will work directly from the plugins folder and grab all the site configuration directly

the standalone folder is useless if you run it from the plugin itself

**Comment by DanielnetoDotCom** [comment]
Just make sure you delete all chat servers

![image](https://user-images.githubusercontent.com/18009293/111179692-14bfe200-858b-11eb-87af-03b7c378af3d.png)

**Comment by morbificagent** [comment]
hm... YPTSocket-test responded with:

** Testing wss://127.0.0.1:2053?webSocketToken=ei8rUUxUUzJZM0svQW1UNXJGMjZXNjBvNFlvRXg3QjE4cUlyZG5FL0ZMWCs0WWxRNHo5V25JNTdHenFJYTBmYlREazgxTm81bXZzcFF2Z3gxbzFuUjgxaUlaSElUYTBDWHBXODhkeUN0b1R0eTJJdWVNaCtwK29xeVZCS05LdzIxSjZ0UjB1Y1Y3SVluVFcvUnhoOXBVbm9WTko2NFZ1OUlhQ1E0Ull6bXZobXZMVDhVMWdKNU9makhuR0xUU2twbzdrbmdTUnNkM1JJeTIva0NpQ3lmWkcydmNSQ29hVzVSZnRFV0ZXeE50QklwcUkyN0hIbkR1TlhjRXlOYXVZb1hhbmI3bVJqclVuQkFpeWs5cUtCZkhuZmpmVEx6UG95Q2t2M21lVFhMNlQ3dlBwVVRYL3dpRWUza1FMeDdZdmZEcU50MHh2T2ZkMnhFSDFHY0lyUTMraTBDelBzSjhKZUNVT2lGd21YYTJoVStwOE14R2MxU2JVZHFNMkRVT1VDVm9VcHhIdmVqT2h2enRiN0M3SEpJRzF4cWZkQkwreURHVHhvSTNMTWhZUnh0V3MxV3BmWjhhQWs0eU16MU5KL3JySk9WQkdCTkhGSCtIcXJWY1dzTnhwMWI1VytNaVlwcGZwb3dWRlh5a2owN1FQcTNMNlFrSDJZT2JNWE5UaE1SRGxvRlRJWWV3UW52NUpLMUZRamZDRXhMaG9kOTA5cDFaZHZsNTFXOVpRPQ== [wss]
Could not connect: Connection to tcp://video.bit-link.de:2053 failed: Last error for IPv4: Connection to tcp://188.40.137.85:2053?hostname=video.bit-link.de failed: Connection refused. Previous error for IPv6: DNS query for video.bit-link.de did not return a valid answer (NOERROR / NODATA)
Could not connect: Connection to video.bit-link.de:2053 failed: Last error for IPv4: Connection to tcp://188.40.137.85:2053?hostname=video.bit-link.de failed: Connection refused. Previous error for IPv6: DNS query for video.bit-link.de did not return a valid answer (NOERROR / NODATA)
Could not connect: Connection to tcp://localhost:2053 failed: Last error for IPv4: Connection to tcp://127.0.0.1:2053?hostname=localhost failed: Connection refused. Previous error for IPv6: Connection to tcp://[::1]:2053?hostname=localhost failed: Connection refused
Could not connect: Connection to localhost:2053 failed: Last error for IPv4: Connection to tcp://127.0.0.1:2053?hostname=localhost failed: Connection refused. Previous error for IPv6: Connection to tcp://[::1]:2053?hostname=localhost failed: Connection refused
Could not connect: Connection to tcp://127.0.0.1:2053 failed: Connection refused
Could not connect: Connection to tcp://127.0.0.1:2053 failed: Connection refused

**Comment by morbificagent** [comment]
Did that.... but the YPTSocket-test responded with:

Could not connect: Connection closed before handshake
Could not connect: Connection to video.bit-link.de:2053 failed during TLS handshake: Connection lost during TLS handshake
Could not connect: Connection closed before handshake
Could not connect: Connection to localhost:2053 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
Could not connect: Connection closed before handshake
Could not connect: Connection to 127.0.0.1:2053 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

**Comment by morbificagent** [comment]
Found out that it tries to use an old certificate i was using some time ago:

Starting AVideo Socket server version 2.4 on port 2053
SSL ERROR, we could not access the CRT file /etc/letsencrypt/live/video.bit-link.de/fullchain.pem, try to run this command as root or use sudo
SSL ERROR, we could not access the KEY file /etc/letsencrypt/live/video.bit-link.de/privkey.pem, try to run this command as root or use sudo

This doesnt exist anymore and another is established in another dir...

Where can i say the socket-server where the ssl-cert is?

**Comment by morbificagent** [comment]
Well, its connected:

![image](https://user-images.githubusercontent.com/50199132/111183543-4b5c2380-85b0-11eb-8257-b7b97104a054.png)

All Chat Servers are deleted.

But i cant chat as its empty and no type... send... button is visible.

![image](https://user-images.githubusercontent.com/50199132/111183434-31224580-85b0-11eb-9dc6-27754fc79a6b.png)

BTW, as you said, the database was installed manually like on the chat-server with some username, some password and some databasename... not sure how the streamer should know these things without telling him...

**Comment by DanielnetoDotCom** [comment]
Hi, just to confirm, I just update one last version of the Chat2, it is tested and works on a remote server. but I still recommend you to stay on the socket local version.

When you pass the mouse over, nothing appears?

how are your parameters, can you please screenshot the parameters screen?

**Comment by morbificagent** [comment]
No, when i pass the mouse over nothing appears...

Shouldent i eventually dump the .sql file for the chat-tables to the Streamer-DB instead of creating a new one like the standalone howto says?

It confuses me to create a new db for the chat with a random password and enter it nowhere...

But i will send the screenshots when im @ home and have some time.

**Comment by DanielnetoDotCom** [comment]
To run it locally you do not need to manually create the database, you just need to click on the create database button on the plugin

**Comment by morbificagent** [comment]
Jeeeeehaaaa with the last modifications from you the chat2 is working on a seperate server in standalone mode!

Many thanks!

And i will take a look in my socket config tomorrow.
Enough for today ;-)

**Comment by morbificagent** [comment]
OK, the responsetimes from chat2 as standalone server are..... not so great ;-) Messages arriving 10sec after pressing send...

Is this normal?

So i tried to get the local/socket-version running and even if there is a strange behavior with the socket (See https://github.com/WWBN/AVideo/issues/4711 ) the socket is now connected.

But the chat remains empty without send-button :-(

![image](https://user-images.githubusercontent.com/50199132/111229362-0eab1f00-85e6-11eb-9d72-8be08f0f0cce.png)


![image](https://user-images.githubusercontent.com/50199132/111229088-93496d80-85e5-11eb-9509-86d9c946cd52.png)

**Comment by DanielnetoDotCom** [comment]
what is in your log file?

BTW,  I just sent another update for the chat v5.7

**Comment by morbificagent** [comment]
![image](https://user-images.githubusercontent.com/50199132/111231517-b83fdf80-85e9-11eb-8e2d-470b1df2c8e1.png)

> BTW, I just sent another update for the chat v5.7

Adressing this problem?

**Comment by DanielnetoDotCom** [comment]
Is that standalone or the local?

**Comment by morbificagent** [comment]
thats the local

**Comment by DanielnetoDotCom** [comment]
So you do not have the latest streamer, that is why.

make sure you run a git pull

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/blob/2c3efe752ea31dc1e15c006be02be8b036795e68/plugin/Live/Live.php#L813-L815

**Comment by morbificagent** [comment]
That was it!
Many many thanks!

Now i can sleep like a baby ;-)
Have a nice rest of the day Daniel

**Comment by bobken** [comment]
Thank help this.
But, I had upgrade to chat 5.7, and the system Stand Alone Server is show error like below messages
--------
[Tue Mar 16 10:36:58.543816 2021] [php:notice] [pid 1790974] [client 10.86.146.14:62388] AVideoLog::DEBUG: getAdvancedCustom: request a new one, referer: http://10.86.100.19/
[Tue Mar 16 10:36:58.554312 2021] [php:error] [pid 1790974] [client 10.86.46.214:62388] PHP Fatal error:  Uncaught Error: mysqli object is already closed in /var/www/html/standAlone/functions.php(18) : eval()'d code(1) : eval()'d code:331\nStack trace:\n#0 /var/www/html/standAlone/functions.php(18) : eval()'d code(1) : eval()'d code(331): mysqli->ping()\n#1 /var/www/html/standAlone/functions.php(18) : eval()'d code(1) : eval()'d code(144): _mysql_connect()\n#2 /var/www/html/standAlone/functions.php(18) : eval()'d code(1) : eval()'d code(357): url_get_contents()\n#3 /var/www/html/standAlone/standAloneConfigurations.php(18) : eval()'d code(1) : eval()'d code(23): getAdvancedCustom()\n#4 /var/www/html/standAlone/standAloneConfigurations.php(18) : eval()'d code(1): eval()\n#5 /var/www/html/standAlone/standAloneConfigurations.php(18): eval()\n#6 /var/www/html/index.php(18) : eval()'d code(1) : eval()'d code(8): require_once('...')\n#7 /var/www/html/index.php(18) : eval()'d code(1): eval()\n#8 /var/www/html/index.php(18): eval()\n#9 {main}\n  thrown in /var/www/html/standAlone/functions.php(18) : eval()'d code(1) : eval()'d code on line 331, referer: http://10.86.100.19/

**Comment by DanielnetoDotCom** [comment]
v5.8 will avoid this error

**Comment by bobken** [comment]
> v5.8 will avoid this error

Thank you for your quick response .
I had upgrade to v6.0, but it show error message like belong
***
[Wed Mar 17 10:24:03.424994 2021] [php:error] [pid 1815608] [client 10.86.46.214:61322] PHP Fatal error:  Uncaught Error: Call to undefined function isMobile() in /var/www/html/index.php(18) : eval()'d code(1) : eval()'d code:31\nStack trace:\n#0 /var/www/html/index.php(18) : eval()'d code(1): eval()\n#1 /var/www/html/index.php(18): eval()\n#2 {main}\n  thrown in /var/www/html/index.php(18) : eval()'d code(1) : eval()'d code on line 31, referer: http://10.86.100.19/

**Comment by DanielnetoDotCom** [comment]
Got it, I am sending a fix (must update streamer and the plugin)

But again, I recommend you to use the socket+chat2

**Comment by bobken** [comment]
> Got it, I am sending a fix (must update streamer and the plugin)
> 
> But again, I recommend you to use the socket+chat2

Thanks for your advice , I also use the socket+chat2 on the same server.

But, where I update the steamer server 10.5 (git pull) it show php error (like below message),
![image](https://user-images.githubusercontent.com/1924671/111597860-9755d500-8809-11eb-8ce4-33c224c18e28.png)
So, I try to fix that to
 **public static function getMediaTag($filename, $htmlMediaTag = false) {**
![image](https://user-images.githubusercontent.com/1924671/111598096-cd935480-8809-11eb-9f06-4fc2f5d1d620.png)

And I also try Chat Stand Alone mode (v6.1) , it show the other error ~~
![image](https://user-images.githubusercontent.com/1924671/111599104-e51f0d00-880a-11eb-8801-095719c880da.png)

**Comment by DanielnetoDotCom** [comment]
Got it, sending updates soon.
