### ISSUE TITLE
YPTStorage on same Server

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4656]
I am using the ftp plugin on the same server like the rest of AVideo only to put files in an other dir on which www-data doesnt have permissions.
Actually i have technical problems with it (issue open here).

As an alternative: Would be the YPTStorage plugin installed on the same server allow me to put the videos in another dir without giving www-data permissions on that?
And are the videos saved as files or is the YPTStorage plugin using some sort of DB?

Thanks for the help

**Comment by DanielnetoDotCom** [comment]
Why dont you just create a symbolic link replacing the videos directory

for example: 


```
sudo mv /var/www/html/AVideo/videos/ /mnt/md0/videos_streamer 
sudo ln -s /mnt/md0/videos_streamer /var/www/html/AVideo/videos 
```

**Comment by morbificagent** [comment]
I have tried it but the storage which i want to use for the videos is very slow in reading many small files but ok for big files.

So moving the whole dir to it results in very bad response times of the website as the config, the cache, an all these things from the videos-dir is now on this slow storage

**Comment by DanielnetoDotCom** [comment]
I see, if the mounted drive is slow, I guess it will be also slow if you use the storage. I am not sure if it is a good idea

**Comment by morbificagent** [comment]
I have buyed and tested this with the YPTStorage on the same server installed on the slow drive this morning and it runs really great!
The requests on the YPTStorage installation seems to be very much less than on the videos-dir.

So the Website runs quick (on fast storage) and the load-time of the videos (via YPTStorage on slow storage) is ~1sec whats great compared with putting the videos-dir on that slow storage.

For all who wants to try this too:

I was searching hours to solve the problem of not-playing-videos after installing xsendfile on the same machine which is serving the AVideo Website.
I needed to comment out some lines in the AVideo-.htaccess file

![image](https://user-images.githubusercontent.com/50199132/110778048-23905700-8262-11eb-9b6c-3762a432ef55.png)

**Comment by DanielnetoDotCom** [comment]
The only thing if you comment out those lines is that you will not be able to use tokens to protect your files 

but everything else should work fine

**Comment by morbificagent** [comment]
Do you mean the password-protection which i can configure for specific videos?

Or what are these "tokens"?

**Comment by DanielnetoDotCom** [comment]
No, I mean if you try to grab a video URL for example:

Check this video https://demo.avideo.com/video/220/nextcloud
This video source file has a token (check the HTML code) and this is valid only for some time (defined on the secure directory plugin)
https://demoavideo.b-cdn.net/videos/Nextcloud_5da47efea67558.74943281.mp4?token=eyJzYWx0IjoiaHR0cHM6XC9cL2RlbW8ueW91cGhwdHViZS5jb21cLyIsInRva2VuVGltZU91dCI6IjIxNjAwIiwiZmlsZW5hbWUiOiJOZXh0Y2xvdWRfNWRhNDdlZmVhNjc1NTguNzQ5NDMyODEiLCJ0aW1lIjoxNjE1NDY4MjM1fQ==

Once the token is expired the URL will not work anymore, or you can try to access it from an incognito browser without the token https://demoavideo.b-cdn.net/videos/Nextcloud_5da47efea67558.74943281.mp4

to be able to control this token you MUST have the XSendFIle properly configured https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

**Comment by morbificagent** [comment]
Ok, understood it.

Thanks for all these information and have a nice rest of the week!
