### ISSUE TITLE
Move configuration.php out of videos folder

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4657]
Actually i am trying to move the videos folder to a different location.
This location is slow so i want to move the configuration.php out of this folder.

Btw i dont understand why its in tis dir...

Anyway. Is there any way of moving this file out of videos?

Many thanks

**Comment by DanielnetoDotCom** [comment]
I do not think it will be a good idea, it will be a lot of code change

**Comment by morbificagent** [comment]
Ok, thanks...
