### ISSUE TITLE
just installed everything fine untill i try upload a mp4 

### ISSUE THREAD

**Issue by ukdomainers** [WWBN/AVideo#4658]
progress file out of the upload folder any help would be appreciated 

ffmpeg version 4.3.1-4ubuntu1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10 (Ubuntu 10.2.0-9ubuntu2)
  configuration: --prefix=/usr --extra-version=4ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, matroska,webm, from '/var/www/AVideo/upload/videos/4_tmpFile.mp4':
  Metadata:
    encoder         : Google
  Duration: 00:12:56.29, start: 0.000000, bitrate: 496 kb/s
    Stream #0:0: Video: vp8, yuv420p(progressive), 640x360, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1: Audio: vorbis, 44100 Hz, stereo, fltp (default)
[mp4 @ 0x5574333d60c0] Could not find tag for codec vp8 in stream #0, codec not currently supported in container
Could not write header for output file #1 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (vp8 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (vorbis (native) -> aac (native))
  Stream #0:0 -> #1:0 (copy)
  Stream #0:1 -> #1:1 (copy)
    Last message repeated 1 times

**Comment by ukdomainers** [comment]
thanks for the reply tried the search looks like ffmpeg problem so started fresh all up n running somehow ?:)

**Comment by akhilleusuggo** [comment]
I don't see where the issue is coming from . VP8 does require `--enable-libvpx` witch you do have .
But what I see is that you're trying to decode a webm file ( vp8 codec ) , then transcode it into mp4 file format .

Can you link the ffmpeg line you're trying to run to achieve the conversion ? It's required .

Also I see that the build does contain `--enable-nvenc` , but nvenc does require `--enable-nonfree` when compiling (`./configure`) and your build is missing it . For me looks like a messed up ffmpeg build , but without the ffmpeg line that is giving you this issue , it's gonna be just guessing stuff .

**Comment by ukdomainers** [comment]
> build does co

it sure was a mess dunno how i did it lol but hey everythings working so far so good
