### ISSUE TITLE
Plugin API - possibility to edit the video tag

### ISSUE THREAD

**Issue by WitchRecipe** [WWBN/AVideo#4662]
Is there any plugin API function that I can use while writing a plugin to be able to extract the HTML "video" tag from the page where the movie is displayed. I mean the ability to extract and edit as it is done in the "VideoResolutionSwitcher" plugin.

In short, I would like to overwrite this function with a plugin:
https://github.com/WWBN/AVideo/blob/d4c91a399491f0860596fdfb8606c2d135c58ced/objects/functions.php#L1369-L1433

**Comment by DanielnetoDotCom** [comment]
I think the only way is to update the core code.
