### ISSUE TITLE
What controls the size of the video description? Really long descriptions fail to save.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4663]
**Describe the question**
I have complete transcripts for videos, when pasted into the description field the page fails to save. We're talking about 40-50 pages of text.

What configuration can be altered to increase the size here?

**Screenshots**
<img width="1485" alt="Screen Shot 2021-03-11 at 12 03 38 AM" src="https://user-images.githubusercontent.com/11711050/110754985-489eae80-81fd-11eb-90b3-5254369f6183.png">

**Comment by DanielnetoDotCom** [comment]
Please check the log file for some clue

**Comment by walt93** [comment]
Just getting back to this... "Error in writeSql : (1406) Data too long for column 'description' at row 1"

So a quick fix, then.

**Comment by walt93** [comment]
Ok I see the issue is that description is a TEXT field with a max length of 65,535.

Is it possible to upgrade this in-place to a MEDIUMTEXT?

I.e. how badly am I going to screw up my database if I run a

`ALTER TABLE `videos` MODIFY `description` LONGTEXT;
`

Should I consider backing up everything beforehand? Prayer?

Please advise, thanks.

**Comment by DanielnetoDotCom** [comment]
Hi, I do not know, I have never upgraded the description.

if you update the database, it should require no change on the PHP code.
