### ISSUE TITLE
Can't log in after update , also automatic redirect not working .

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4664]
###Streamer site ###

Login to the site , does not automatically redirect to other pages . Does keep looping . Requires a refresh page to make the redirect happens (F5) .

###Encoder side###

Sorry!
We could not find your streamer site!

Other info 
I have updated everything ( streamer / encoder / network-encoder ) and that caused the issue . 

Nothing on logs , except the errors that I have stated above .

**Comment by DanielnetoDotCom** [comment]
> ###Streamer site ###
> 
> Login to the site , does not automatically redirect to other pages . Does keep looping . Requires a refresh page to make the redirect happens (F5) .

Check the Console log, also the network tab what is the response

![image](https://user-images.githubusercontent.com/18009293/110778619-58d87d00-8241-11eb-85c5-c945f9dc35ad.png)


> ###Encoder side###
> 
> Sorry!
> We could not find your streamer site!
> 
> Other info
> I have updated everything ( streamer / encoder / network-encoder ) and that caused the issue .
> 
> Nothing on logs , except the errors that I have stated above .

Probably the encoder error comes from the same problem

**Comment by akhilleusuggo** [comment]
Code error : 500

```
<!DOCTYPE html>
<html>
    <head>
        <title>Under Maintanance</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            html, body{
                margin: 0 auto;
                font-family: 'Roboto', sans-serif;
                height: 100%;
                background: #EEEEF4;
                font-weight: 100;
                user-select: none;
            }

            main{
                height: 100%;
                display: flex;
                margin: 0 20px; 
                text-align: center;
                flex-direction: column;
```

The drive does have over 200 gb free space and usable .

**Comment by DanielnetoDotCom** [comment]
> Code error : 500
> 
> ```
> <!DOCTYPE html>
> <html>
>     <head>
>         <title>Under Maintanance</title>
>         <meta charset="UTF-8">
>         <meta name="viewport" content="width=device-width, initial-scale=1.0">
>         <style>
>             html, body{
>                 margin: 0 auto;
>                 font-family: 'Roboto', sans-serif;
>                 height: 100%;
>                 background: #EEEEF4;
>                 font-weight: 100;
>                 user-select: none;
>             }
> 
>             main{
>                 height: 100%;
>                 display: flex;
>                 margin: 0 20px; 
>                 text-align: center;
>                 flex-direction: column;
> ```
> 
> The drive does have over 200 gb free space and usable .

This means an error 500

check the apache error log file

**Comment by akhilleusuggo** [comment]
Nothing at all ... Until I refresh .
/var/log/apache2/error.log , also checked access.log ( nothing  )

**Comment by DanielnetoDotCom** [comment]
It MUST be somewhere, it is an error 500

If you want, make sure you are displaying all errors on your server (php.ini and apache)

and comment out this line 
https://github.com/WWBN/AVideo/blob/3198c88a5c082ac7bb815e420b37e484b342092e/objects/functions.php#L4945

**Comment by akhilleusuggo** [comment]
`//register_shutdown_function('avidoeShutdown'); `

Added , and nothing shows . 
Have you tried the new version ? Because this didn't happened only after update .

The site itself does work as expected with the exception of having to refresh the browser after login , and the encoder does just not allow login .

**Comment by akhilleusuggo** [comment]
`"POST /objects/login.json.php HTTP/1.1" 500 4456 "https://www.example.com/user" "Mozilla/5.0 (xx) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.197 Safari/537.36"`

**Comment by DanielnetoDotCom** [comment]
> `//register_shutdown_function('avidoeShutdown'); `
> 
> Added , and nothing shows .
> Have you tried the new version ? Because this didn't happened only after update .
> 
> The site itself does work as expected with the exception of having to refresh the browser after login , and the encoder does just not allow login .

After you comment out the line, what appears in your login.json.php request/response (check the console)?

**Comment by DanielnetoDotCom** [comment]
I just update the demo site and tutorials site to the latest, and both are working

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 


![a](https://user-images.githubusercontent.com/52116577/110784238-1ed39f00-8272-11eb-8bb2-a77d85de254f.png)

**Comment by DanielnetoDotCom** [comment]
So it is an error 500

![image](https://user-images.githubusercontent.com/18009293/110784351-5af20a00-8248-11eb-8083-c4370bf46cfb.png)


the error MUST be somewhere in your server.

try the syslog

**Comment by DanielnetoDotCom** [comment]
Also, I can see you are NOT displaying errors (what is fine on production).

But display errors will help if you cannot find the logs

**Comment by akhilleusuggo** [comment]
Actually the error were displaying before I commented the lines .

I'm going to remove the comments , and post again ;

Results ; 

![b](https://user-images.githubusercontent.com/52116577/110785060-28113b80-8273-11eb-82ba-ad2d5181b062.png)

Seems like the lines are not working as intended .

**Comment by akhilleusuggo** [comment]
Ok , seems like I found some error . Related to chat .

```
Start Login Request SCRIPT_NAME: /objects/login.json.php
[11-Mar-2021 14:05:52 Europe] AVideoLog::DEBUG: redirectUri: https://www.fffffffff.com/ SCRIPT_NAME: /objects/login.json.php
[11-Mar-2021 14:05:52 Europe] AVideoLog::DEBUG: same redirectUri: https://www.fffffff.com/ SCRIPT_NAME: /objects/login.json.php
[11-Mar-2021 14:05:52 Europe] PHP Fatal error:  Uncaught Error: Call to undefined method Chat2::getChatRoomLink() in xxxx/objects/login.json.php:240
Stack trace:
#0 {main}
  thrown in xxxx/objects/login.json.php on line 240
[11-Mar-2021 14:05:52 Europe] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined method Chat2::getChatRoomLink() in \xxxxx/objects\/login.json.php:240\nStack trace:\n#0 {main}\n  thrown","file":"\/xxxxx/login.json.php","line":240} SCRIPT_NAME: /objects/login.json.php
```


Disabling the chat , FIXED THE ISSUE . ENCODER ALSO GOT FIXED .

Issue related to Chat Plugin .

**Comment by DanielnetoDotCom** [comment]
Please update your Chat2 plugin

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Hello Daniel , issue fixed , but logs are confusing .

```
Verification Start https://www.ffff.com/
[12-Mar-2021 01:24:55 Europe/Berlin] Verification GetFrom Cache https://www.ffff.com/
[12-Mar-2021 01:24:55 Europe/Berlin] Verification Response (): {"msg":["Start","https:\/\/www.fffff.com\/ Site does not exist"],"verified":true,"status":"i"}
```

Site does not exist , but allow to connect , I don't get it . and status ''i'' ( inactive for my understanding ( from database )
