### ISSUE TITLE
Error messages in log after fresh install of latest version

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4665]
**Describe the bug**
Error messages in the log file, invalid PHP and invalid filenames

**To Reproduce**
Install fresh

**Expected behavior**
No error messages :-)

**Error Logs**
2021/03/11 10:41:33 [error] 39982#39982: *18 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: global in /var/www/AVideo/install/index.php on line 29PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/AVideo/install/index.php on line 29" while reading response header from upstream, client: 213.89.130.66, server: my.avideo.server.com, request: "GET /install/index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "my.avideo.server.com"

2021/03/11 10:41:33 [error] 39982#39982: *18 open() "/var/www/AVideo/view/js/seetalert/sweetalert.css" failed (2: No such file or directory), client: 213.89.130.66, server: my.avideo.server.com, request: "GET /view/js/seetalert/sweetalert.css HTTP/1.1", host: "my.avideo.server.com", referrer: "https://my.avideo.server.com/install/index.php"

**Additional context**
Ubuntu 20.04.LTS with Nginx, MariaDB, and PHP 7.4-FPM.

The file "sweetalert.css" does not exist, but "sweetalert.min.css" exists. But that does not cure the first problem (install..)

**Comment by DanielnetoDotCom** [comment]
Those are only warnings but I am sending fixes for them

Check the Apache error log

**Comment by joho1968** [comment]
The first log entry contains "Undefined variable: global", which is an error and not a warning :-)
