### ISSUE TITLE
Error messages in log when trying to install encoder in latest version

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4666]
**Describe the bug**
There are (fatal) error messages in the various log files (PHP and web server) when trying to install the encoder locally.

**To Reproduce**
1. Go to your.video.site/upload/
2. You're automatically re-directed to your.video.site/upload/install/index.php?
3. Fill in your credentials
4. You simply stay on index.php with no progress

**Expected behavior**
For the installation to complete

**Error Logs**
2021/03/11 11:32:08 [error] 74659#74659: *117 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/var/www/AVideo/upload/view/../videos/configuration.php): failed to open stream: No such file or directory in /var/www/AVideo/upload/view/index.php on line 18PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/AVideo/upload/view/../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/AVideo/upload/view/index.php on line 18" while reading response header from upstream, client: 213.89.130.66, server: your.video.site, request: "GET /upload/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "your.video.site"

2021/03/11 11:32:08 [error] 74659#74659: *117 open() "/var/www/AVideo/upload/view/bootstrap/js/bootstrap.min.js" failed (2: No such file or directory), client: 213.89.130.66, server: your.video.site, request: "GET /upload/view/bootstrap/js/bootstrap.min.js HTTP/1.1", host: "your.video.site", referrer: "https://your.video.site/upload/install/index.php"
2021/03/11 11:32:08 [error] 74659#74659: *100 open() "/var/www/AVideo/upload/view/js/seetalert/sweetalert.min.js" failed (2: No such file or directory), client: 213.89.130.66, server: your.video.site, request: "GET /upload/view/js/seetalert/sweetalert.min.js HTTP/1.1", host: "your.video.site", referrer: "https://your.video.site/upload/install/index.php"
2021/03/11 11:32:08 [error] 74659#74659: *117 open() "/var/www/AVideo/upload/view/bootstrap/js/bootstrap.min.js" failed (2: No such file or directory), client: 213.89.130.66, server: your.video.site, request: "GET /upload/view/bootstrap/js/bootstrap.min.js HTTP/1.1", host: "your.video.site", referrer: "https://your.video.site/upload/install/index.php"

**Additional context**
Ubuntu 20.04.LTS, PHP 7.4-FPM

**Comment by DanielnetoDotCom** [comment]
Where is the fatal error?

**Comment by joho1968** [comment]
In the first block. And the error message is correct, there are no such file(s).

**Comment by joho1968** [comment]
As for the "missing" bootstrap.min.js, there is one in "/view/bootstrap/js/bootstrap.min.js", but not in "/upload/view/bootstrap/js/bootstrap.min.js". So I'm not sure if it's a case of an incorrectly specified path or if the encoder is supposed to have its own set of /js/ files.

**Comment by DanielnetoDotCom** [comment]
Update the encoder and you should see the bootstrap.

regarding the fatal error, you must install it before accessing any other page

**Comment by joho1968** [comment]
OK. I did a new clone of the repo and the installation seem to have completed now. Great :+1:
