### ISSUE TITLE
Issues with local encoder ("This streamer site is not allowed")

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4667]
**Describe the bug**
Getting an error message "This streamer site is not allowed"

**To Reproduce**
Simply trying to login to my.video.site/upload (which is where the encoder is installted)

**Expected behavior**
Possibly a somewhat more detailed error message (in a PHP log for example).

**Additional context**

1. I go to my.video.site/upload
2. I enter https://my.video.site as "Streamer site"
3. I fill in my credentials
4. And then I get the error message

This may, perhaps, be due to misconfiguration; in which case it'd be nice with some detailed instructions :-)

I'm guessing there's a mismatch in configuration fields.

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/WWBN/AVideo/issues/3893

It does not work try this https://github.com/WWBN/AVideo-Encoder-Network/issues/30#issuecomment-785873924

**Comment by joho1968** [comment]
OK, so now I can "login" to the encoder, but am instead faced with this in the logs:

2021/03/12 08:17:47 [error] 118726#118726: *181 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: x.x.x.x, server: your.video.site, request: "GET /view/getBestEncoder.php HTTP/1.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "your.video.site"

2021/03/12 08:17:47 [error] 118726#118726: *183 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: x.x.x.x, server: your.video.site, request: "GET /view/getBestEncoder.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "your.video.site"

2021/03/12 08:17:52 [error] 118726#118726: *185 open() "/var/www/AVideo/view/js/tinymce/langs/sv.js" failed (2: No such file or directory), client: 213.89.130.66, server: your.video.site, request: "GET /view/js/tinymce/langs/sv.js HTTP/1.1", host: "your.video.site", referrer: "https://your.video.site/mvideos"

2021/03/12 08:18:03 [error] 118726#118726: *189 open() "/var/www/AVideo/status" failed (2: No such file or directory), client: 213.89.130.66, server: your.video.site, request: "GET /status HTTP/1.1", host: "your.video.site", referrer: "https://your.video.site/upload/?justLogin=1&PHPSESSID=uflq0gvi19oo55evu2qte43ps3"

**Comment by joho1968** [comment]
Well, I've switched to Apache now and things seems to work better. Probably an issue with one or more of the Nginx rewrite rules. I understand Nginx support is experimental, so.
