### ISSUE TITLE
Incorrect flag for SV language (if SV is meant to mean SV_SE, Swedish)

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4668]
**Describe the bug**
It seems like choosing the language 'sv' is intended to mean "Swedish" (sv_SE). Which I believe is correct. At least I'm getting some strings in Swedish.

But the flag for 'sv' is wrong :-)

**Comment by DanielnetoDotCom** [comment]
sv suppose to be Swedish

I am using flagstrap http://www.blazeworx.com/flagstrap/

Seems like they use 

SE for Sweden flag and 
SV is El Salvador flag

**Comment by joho1968** [comment]
Well, the full code for Swedish is sv_SE, so perhaps that's were the confusion comes from. 

But: https://en.wikipedia.org/wiki/Flag_of_Sweden

**Comment by DanielnetoDotCom** [comment]
Check now

![image](https://user-images.githubusercontent.com/18009293/110937375-0b2b4580-8311-11eb-9186-e79e3adaa827.png)

**Comment by DanielnetoDotCom** [comment]
Actually is all refactored based on this https://stackoverflow.com/a/28357857/2478180

your filename should be sv_SE

**Comment by joho1968** [comment]
So, just to be clear, you want me to fetch it/clone it, again? :-)

**Comment by DanielnetoDotCom** [comment]
Just a `git pull` is enough
