### ISSUE TITLE
Security files

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#4670]
Hello,
I try to download the Chat 2 plugin but I can not because the system detected a virus in the file
any help?

Thank you

**Comment by DanielnetoDotCom** [comment]
Probably because it is encrypted and you cannot read.

you must disable the antivirus and try again.

**Comment by wetubeclub** [comment]
I tried again now and the file was downloaded without doing anything else
all good thanks

Thank you Daniel
Ilias
