### ISSUE TITLE
Help with Swedish translation

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4676]
The Swedish (sv_SE) translation needs "a lot of work", which is understandable :-)

Do you have a preferred way for me to assist with this? If you want help with it, that is.

**Comment by DanielnetoDotCom** [comment]
Sure, you can send a pull request when you add the translations.

BTW, the file name now is se.php I had to change it to get the correct flag

**Comment by 01123581321345589144233** [comment]
is there also a option for danish translation ?

**Comment by DanielnetoDotCom** [comment]
danish?

**Comment by 01123581321345589144233** [comment]
yes

**Comment by DanielnetoDotCom** [comment]
Here is a google translate for danish, feel free to improve it
