### ISSUE TITLE
Disable background or static background image on login form

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4677]
It would be nice if a static background could be chosen (and customized) rather than this ... animated thing :-)

**Comment by DanielnetoDotCom** [comment]
If you want you can disable that and use a custom CSS to add a background

![image](https://user-images.githubusercontent.com/18009293/110965974-8bfb3900-8333-11eb-8714-89d527a138ad.png)

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css
