### ISSUE TITLE
Somewhat more friendly "no content available"

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4678]
**Describe the solution you'd like**
The default "nothing is available" looks a bit ... like a danger alert. It could be a perfectly normal situation and I don't think it warrants a "WARNING" sign with a not-so-happy-smiley. A simple "No videos seem to be available at the moment" or "No content seems to be available in this category" or ... whatever. (If you use "No content seems to be available..." you don't have to say videos or audios or ...)
![AVideoWarningNoVideos](https://user-images.githubusercontent.com/3135227/110916483-2437f480-8319-11eb-9b4a-d08477a66d24.png)

**Comment by DanielnetoDotCom** [comment]
Thanks, I agree with you. I may improve it in the future
