### ISSUE TITLE
"Play a link" allows external videos

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4679]
**Describe the bug**
I'm not sure this is a bug, it may be WAD.

**To Reproduce**
Choose to play a link, specify an external URL like: https://youtu.be/qC0mnGprbeM

**Expected behavior**
I would expect it not to be allowed/played. Instead a friendly message could be displayed to the effect of "The link you've specified is not for an item on this site."

**Comment by DanielnetoDotCom** [comment]
Sorry, I do not understand what you mean. can you please provide some screenshots?

**Comment by joho1968** [comment]
Click on "Play a link" (you can do this even without being logged in) in the menu.

Enter the URL of a YouTube video (or whatever you want).

The video plays.

Maybe I'm misunderstanding this feature, but I don't quite understand why I would want to play an external video.

**Comment by DanielnetoDotCom** [comment]
Just disable it

![image](https://user-images.githubusercontent.com/18009293/111152483-8ab65000-856f-11eb-8c38-23b32be7f7a3.png)

**Comment by joho1968** [comment]
Fair enough :smiley:
