### ISSUE TITLE
Rewrite rules for Nginx (2021)

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4680]
**Describe the question**
Does anyone have a **complete** set of **working** rewrite rules for Nginx that are up-to-date anno 2021?

**Comment by patriclougheed** [comment]
I just updated my gist of my NginX config I use on my site which is using 10.2:

https://gist.github.com/patriclougheed/706677ffe2459df3b6587e54fd4a0923

I have removed all the certbot redirect stuff at the bottom.
