### ISSUE TITLE
Plugin list empty

### ISSUE THREAD

**Issue by fxp66** [WWBN/AVideo#4681]
Hi,
after update to vers. 10.5 the list of plugins is empty.
How can I fix this issue?
Thx for quick response

**Comment by DanielnetoDotCom** [comment]
Please check the log file

**Comment by fxp66** [comment]
Log says:
PHP Fatal error:  Cannot declare class SocketMessageType, because the name is already in use in /var/www/vhosts/fpdo.de/video.fpdo.de/plugin/YPTSocket/functions.php on line 76

**Comment by DanielnetoDotCom** [comment]
The problem is, I cannot reproduce it

did you copy the YPTSocket plugin folder somewhere?

**Comment by fxp66** [comment]
no, I did not. But maybay I should test it with a copy from another instance

**Comment by fxp66** [comment]
Ok, I took a copy of a fresh new installation and the prob seems to be fixed.
