### ISSUE TITLE
SendRecordedToEncoder and makeVideosInactiveAfterEncode

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4682]
Hi together,

actually i try to make use of the setting makeVideosInactiveAfterEncode in the CustomizeAdvanced Plugin.

It is working good for uploaded files but the great problem is the live-streaming.

I have bought the plugin SendRecordedToEncoder which works great too but the resulting files arent preserve the group on which the Stream was published and much more critical the setting "makeVideosInactiveAfterEncode".

As result i go live for my friends, in the group of my friends, talking some shit ;-) and the live-stream is some sort of "private".
After that the stream is automatically encoded an published as public and active!!!

Could be not so funny.

Am i missing some configuration or isnt this implemented?
Or is it possible to configure the encoder (on my server too) to make everything inactive or unlisted after the encoding?

Many thanks

**Comment by DanielnetoDotCom** [comment]
Hi, I am working on SendRecordedToEncoder v3.1

When it is ready just update your streamer and download the new plugin and it may preserve the usergroups

**Comment by morbificagent** [comment]
Great!

Do you have an idea when it is ready to download?

Only that i have an idea if i have to build a workaround until that.

And will it be possible to make recorded files inactive or unlisted automatically too?

Many thanks for all of your work

**Comment by DanielnetoDotCom** [comment]
Probably on Monday

**Comment by DanielnetoDotCom** [comment]
The recorded files should follow the global visibility rules

**Comment by morbificagent** [comment]
Wow, great... Then i will try to shut my mouth and let you code ;-)

**Comment by morbificagent** [comment]
Wow, great... Then i will try to shut my mouth and let you code ;-)

**Comment by morbificagent** [comment]
Any news about this?

**Comment by DanielnetoDotCom** [comment]
The latest should do that, but anyway, I am sending the SendRecordedToEncoder v3.1 now

**Comment by morbificagent** [comment]
Great, i will try it :-)
