### ISSUE TITLE
Encoded media plays back on desktop; fails to play on mobile (spin/loading animation forever)

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4683]
**Describe the question**
I've let my encoder run for 24 hours and I'm checking the encoded videos to see how things are proceeding.

I'm finding that I have videos which play on desktop, and not on mobile.

Looking for strategy to diagnose/debug.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
not sure, can you please share the video link here?

**Comment by walt93** [comment]
I had bunches of files with errors. I’ve deleted the lot and so far subsequently encoded files are looking good.
