### ISSUE TITLE
Subscribe and the bell

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4687]
Hi together,

Actually i am confused whats the difference between the subscribe and the bell button next to it.

Ok, i can subscribe the channel of the user. But do i get mails (notification plugin is enabled) if the bell is crossed out? Or if its not crossed out?

And why can i change the bell without clicking on subscribe?

So i can get mail on new videos without beeing a subscriber?

Confusing. ;-)

**Comment by DanielnetoDotCom** [comment]
It supposes to receive emails only if you check the bell, it may need a correction if is not working properly

**Comment by morbificagent** [comment]
@DanielnetoDotCom i will doublecheck if its working...

But the problem that i can click it even if i havent subscibed the channel is there in my case.

**Comment by DanielnetoDotCom** [comment]
I see, this also have  to be reviewed
