### ISSUE TITLE
Live-Stream permissions 

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4688]
And again me, (im sorry for so many questions)

I am trying to understand the difference between the permission settings for videos and for livestreams.

For the videos i can set public OR a specific usergroup.
For livestreaming i can set public AND a specific usergroup.

But why should i say the stream is public and only for a usergroup?

**Comment by DanielnetoDotCom** [comment]
No

public means everyone can watch, user group means only the selected user groups can watch.

listed means, it will appear on the firsts page so people can find it, unlisted means you need a link to find the video because it will not appear on the first page

**Comment by morbificagent** [comment]
Hi Daniel,

i understand that for Video-Files. That is how the webinterface let me configure it.

But for live-streams i can configure it like this:

Enable one usergroup:

![image](https://user-images.githubusercontent.com/50199132/111155527-d92a1580-8594-11eb-9eb3-0ba2fb449d31.png)

AND enable "public":

![image](https://user-images.githubusercontent.com/50199132/111155633-fc54c500-8594-11eb-8e97-1df1c83bc718.png)

Is it a bug or is there any sense behind that?

**Comment by DanielnetoDotCom** [comment]
If you do that everyone will be able to see the live notification, but only the selected group will be able to watch.

**Comment by morbificagent** [comment]
Ah OK, thanks for the explaination.

Because there is no hint on the button that it will have something to do with the notifications it was very confusing.
