### ISSUE TITLE
VR 360 plugin not working

### ISSUE THREAD

**Issue by fxp66** [WWBN/AVideo#4689]
Hi,
I think this issue has been mentioned before, the VR 360 plugin is not working for me. Is this a bug, or are there special requiremnts to the media?  I have a lot of 360 degree media, so it would be nice, to have it.
Thx for quick response

**Comment by morbificagent** [comment]
Hi there, im using it and its working  generally.

But i found some limitations too:

- for me the media MUST be on local storage. Moving them to YPTStorage make the videos unplayable for me.

- the videos must be in the format in which it looks like a panorama-video... I am searching for the right word for that ;-)
So i have to export the "fisheye-version" from my 360 camera, render it with the software from the manufacturer for output this "panorama-like" format.
Eventually some Mobile apps make this happend "on the fly"

- you have to enable VR360 for the specific video after you have uploaded it.

Here is an example:

https://video.bit-link.de/video/9/heimfahrt-360grad-1?channelName=_60493cfac4885

**Comment by fxp66** [comment]
The word you're looking for is equirectangular, which means a planar picture with a ratio of 2:1 is projected into a sphere. Some video.js players seem to have problems, if the media has a wrong resolution.
Do you use the plugin shipped with the installation routine or do you use it from another source?

**Comment by fxp66** [comment]
Probably I miss some configuration?

**Comment by morbificagent** [comment]
Ah thanks for the missing word ;-)

No, i am using the shipped version and i havent configured anything...

**Comment by fxp66** [comment]
You're wright, everthing is working very well, I only have to change resolution on player skin.
Thx for being patient with stupid questions
