### ISSUE TITLE
Questions: A lot of them

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#4691]
1. When will the MRSS and ROKU JSON be ready for our networks?
2. How to fix this: ![image](https://user-images.githubusercontent.com/62782361/111060384-1d68c900-8462-11eb-93a0-0c847f863fc9.png) The top section on our sites.
3. How to make the live playlist work. I know that you are working on it, but I am having a lot of questions about it, especially the TV part on our sites?
4. What are the new features, which I suggest to let us know about so that we can be aware of it and how to use them to support our clients.
5. Back to the live playlist, can any user be able to broadcast with their playlist?
6. If it is possible, can we make some of our channels broadcast like a 24/7 channel?

Thanks

**Comment by DanielnetoDotCom** [comment]
> 1. When will the MRSS and ROKU JSON be ready for our networks?

I guess so, there are some users using it with success

> 2. How to fix this: ![image](https://user-images.githubusercontent.com/62782361/111060384-1d68c900-8462-11eb-93a0-0c847f863fc9.png) The top section on our sites.

![image](https://user-images.githubusercontent.com/18009293/111148960-0530a100-856b-11eb-8aef-bcc6ad2bce08.png)


> 3. How to make the live playlist work. I know that you are working on it, but I am having a lot of questions about it, especially the TV part on our sites?

This feature is not done yet

> 4. What are the new features, which I suggest to let us know about so that we can be aware of it and how to use them to support our clients.

Sorry I do not have a list but usually, I comment them on the updates

> 5. Back to the live playlist, can any user be able to broadcast with their playlist?

In the future for sure

> 6. If it is possible, can we make some of our channels broadcast like a 24/7 channel?

Yes with the playlist live working

**Comment by CROSSMediaNet** [comment]
1. When will the MRSS and ROKU JSON be ready for our networks?

I guess so, there are some users using it with success

Here's my problem and if it is something that needs to be fixed:
[image: image.png] The MRSS Feed
[image: image.png] The ROKU JSON

**Comment by DanielnetoDotCom** [comment]
I cannot see your images

**Comment by CROSSMediaNet** [comment]
![1615822437435_image](https://user-images.githubusercontent.com/62782361/111179529-2b117200-857a-11eb-93a2-0acf6b61032a.png)
![image](https://user-images.githubusercontent.com/62782361/111179569-32388000-857a-11eb-8da7-3c8603fc0aeb.png)

**Comment by DanielnetoDotCom** [comment]
The images look correct to me, what is the problem?

did you see that? https://github.com/WWBN/AVideo/issues/4128#issuecomment-743224493

**Comment by CROSSMediaNet** [comment]
How to use it. I am confused and on the front page of the site, no one is
able to see if it is a live broadcast

**Comment by DanielnetoDotCom** [comment]
The live boradcast do not appear on the Roku or Amazon yet, only VOD videos

**Comment by CROSSMediaNet** [comment]
Ok, I'll check it out. There's a problem with the live indicator on the
site that doesn't show that any broadcasts. When I went outside of my
network I can see the video from the embedded player.

**Comment by CROSSMediaNet** [comment]
Here's the problem with the live indicator: 
![image](https://user-images.githubusercontent.com/62782361/111245627-ef56c680-85d2-11eb-95ff-86eda1585255.png)

Here's another example that it is not working (plus the second streaming is not showing that it is online): 
![image](https://user-images.githubusercontent.com/62782361/111247445-f92df900-85d5-11eb-8723-6d9780a315a7.png)

**Comment by DanielnetoDotCom** [comment]
your m3u8 files still on the server, that is why it still playing, I guess you have the Nginx DVR feature enabled https://github.com/WWBN/AVideo/blob/3827a28274dff2da119df7bb0ed6f1cb7b307e3e/plugin/Live/install/nginx.conf#L19

The default is 60 minutes

**Comment by CROSSMediaNet** [comment]
Ok, I'll check it out. But it doesn't explain to me why the live stream
indicator (live stream bell) doesn't work anymore

**Comment by DanielnetoDotCom** [comment]
It supposes to work, are you talking about impstream site?

I can check that for you

**Comment by DanielnetoDotCom** [comment]
Anyway impstreams is up to date and I could confirm 2 simultaneous livestreams and the correct notification

**Comment by CROSSMediaNet** [comment]
Okay...great...quick question...are they supposed to linger for a period
of time? Just asking

**Comment by CROSSMediaNet** [comment]
Nevermind...I got it...thanks

**Comment by CROSSMediaNet** [comment]
Got a question about the channels. Why are the channels appears to be like this:
![image](https://user-images.githubusercontent.com/62782361/111575059-a42be780-877b-11eb-9c8e-87c5fd9384a0.png)
even when going through different browsers?

**Comment by DanielnetoDotCom** [comment]
Sorry what?

**Comment by CROSSMediaNet** [comment]
Look at the channel page. It have ever video from other channels

**Comment by DanielnetoDotCom** [comment]
Sorry you were right, here is a fix

**Comment by CROSSMediaNet** [comment]
I don't see the fix

**Comment by CROSSMediaNet** [comment]
Nevermind...I did update the site
