### ISSUE TITLE
video resolution

### ISSUE THREAD

**Issue by lahaj** [WWBN/AVideo#4692]
Hello sir
I hope you are fine and in a good health
I have a question regarding the video resolution
When I upload the video, encoder processes the video, and after that the video is in several resolutions
I just want it to be only 3 resolutions. Is there a way to disable it and only be 3 resolutions is an example
1080p
720p
480p
I hope you find this solution for me
Thank you very much, sir

![ooogel1](https://user-images.githubusercontent.com/71000399/111061043-a875ad80-84ba-11eb-8481-f538cd4027cd.jpg)

**Comment by tonuzo** [comment]
![image](https://user-images.githubusercontent.com/63721378/111065342-d3173480-84c1-11eb-9854-4cb3c7baa075.png)

**Comment by lahaj** [comment]
Thanks sir for the response
But I don't have these options

![ooogel2](https://user-images.githubusercontent.com/71000399/111065462-5725e800-84d3-11eb-827e-5f1fd14899c7.jpg)

**Comment by tonuzo** [comment]
Is your encoder up to date?

**Comment by lahaj** [comment]
It's AVideo Encoder version 3.3!

**Comment by tonuzo** [comment]
I have 3.7

**Comment by lahaj** [comment]
Okay, please, tell me how to update, or give me a page that has the update code
Because I have 2 shared servers from you, not from anywhere else
Please help me to update the encoder
thank you very much

**Comment by lahaj** [comment]
Okay, please, tell me how to update, or give me a page that has the update code
Because I have 2 servers subscribed to them on a monthly basis, which I took from you, not from another place
Please help me so that I can update the encoder
thank you very much

**Comment by lahaj** [comment]
Okay, please, tell me how to update, or give me a page that has the update code
Because I have 2 servers subscribed to you on a monthly basis, which I took from you, not from another place
Please help me so that I can update the encoder
thank you very much

**Comment by tonuzo** [comment]
If you can SSH your server, go to your encoder folder and do git pull. 

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by lahaj** [comment]
Sir, I previously updated the platform. I want to update the encoder and encoder. It did not happen when I updated the form. Give me the page on which the code is in. What is the code? Where can I find it?
![3333](https://user-images.githubusercontent.com/71000399/111076074-3d50c900-8504-11eb-80f7-371e6edd57fa.jpg)

**Comment by lahaj** [comment]
I have two servers that I took from you, and I pay a monthly subscription, please understand me
I am your customer
I am not a secret composite on an external server
You are installing the script on the Ubuntu system. I want the encoder update code, not the Form Plat, so I have updated it

**Comment by tonuzo** [comment]
I'm not familiar to update any other way than SSH to server and typing "git pull" and then click update from Encoder. 
Maybe @DanielnetoDotCom can help you, if you are a customer.

**Comment by lahaj** [comment]
Thank you very much, sir. We have successfully updated to the latest version. Have a good day

**Comment by lahaj** [comment]
Hi
After updating the platform option, the subtitles in the video player is like this
I updated SubtitleSwitcher but to no avail
![8888](https://user-images.githubusercontent.com/71000399/111079990-d63c1000-8515-11eb-9297-7de9c845c40e.jpg)

**Comment by DanielnetoDotCom** [comment]
Try to update your subtitle plugin as well

**Comment by lahaj** [comment]
Hello Mr. Daniel, how are you? I hope you are well
I updated yesterday, and today I downloaded and uploaded it as you can see in the problematic pictures, still there, my dear.

![sub](https://user-images.githubusercontent.com/71000399/111152602-557b2380-85aa-11eb-9afc-80e64343939d.jpg)
![sub2](https://user-images.githubusercontent.com/71000399/111152622-5b710480-85aa-11eb-9934-8c830474d91e.jpg)

**Comment by DanielnetoDotCom** [comment]
I see, what do you see when you edit the subtitle on this movie?

**Comment by lahaj** [comment]
I see that I can add the subtitle as normal and I see all the languages and when I add the subtitle the language is as it is in the pictures
This is an example

![sub3](https://user-images.githubusercontent.com/71000399/111158284-4a77c180-85b1-11eb-8d19-d1bae138cd7a.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, I just submit an update to you, I found the issue, please confirm

**Comment by lahaj** [comment]
Thank you very much. Yes, thanks to you, the problem has been solved, and this is a confirmation from me and everything works well and is better than before
Thank you, sir, regarding the size of the subtitle font that appears in the video player. How can it be like before and a little bigger, not small

![Uploading 8989.jpg…]()

**Comment by DanielnetoDotCom** [comment]
You can try this CSS

```
<style>
    .vjs-button.vjs-resolution-button .vjs-menu-item-text{
        font-size: 1.2em;
    }
</style>
```

Add the CSS like this https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css

**Comment by lahaj** [comment]
Excellent sir, the font has been enlarged a little and this is fine. I want the word "HD" to be in the same row, not below the numbers.
Example
720 HD    Like This
Not Like this
720
HD

**Comment by DanielnetoDotCom** [comment]
Try this

```
<style>
    .vjs-button.vjs-resolution-button .vjs-menu-item-text{
        font-size: 1.5em !important;
        min-width: 150px;
    }
</style>
```

**Comment by lahaj** [comment]
I put the code in and it didn't
I want the word HD next to the numbers and not below

![cood](https://user-images.githubusercontent.com/71000399/111218831-b3325e80-85f0-11eb-976f-3ff79cd6e70c.jpg)

**Comment by DanielnetoDotCom** [comment]
What about this?

```
<style>
    .vjs-control.vjs-button.vjs-resolution-button.vjs-hover > div > ul{
        min-width: 150px !important;
    }
    .vjs-button.vjs-resolution-button .vjs-menu-item-text{
        font-size: 1.5em !important;
    }
</style>
```

**Comment by lahaj** [comment]
Thank you very much. Now very excellent. This is how I wanted it. I wish you pardon because I bothered you so much. I wish you good luck, happiness, success and good health.
Sir, you can close the ticket now, everything is excellent, thanks to you
Accept my greetings
Muhammad bin

![coood00](https://user-images.githubusercontent.com/71000399/111224209-8a619780-85f7-11eb-8806-f21810b5a1bd.jpg)
