### ISSUE TITLE
user categories on categories

### ISSUE THREAD

**Issue by unconservo** [WWBN/AVideo#4695]
Hi hi. When I create subscribers user group and want the users under the subscriber group see specific categories which public cannot see I cannot do this. If I select Private on the category only I can see it and not the selected user group. Is this possible?

selected content works fine but i want to select a category only for subscribers(or specific usergroup) to see the content of.

Regards

**Comment by DanielnetoDotCom** [comment]
This option will not make your videos private, this option is for other users not to be able to include their videos in this category. to make your videos private use the user groups feature.

**Comment by unconservo** [comment]
Thanks for the reply. But this will not make the category linked to the specific user groups?. Are categories always public?

**Comment by DanielnetoDotCom** [comment]
No, this is linked with the user who creates it.

![image](https://user-images.githubusercontent.com/18009293/111472785-144d5580-8709-11eb-8504-f6c210daf0b5.png)
