### ISSUE TITLE
How to delete a video

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#4697]
As admin, how can I delete a video when looking at the main display screen?

**Comment by DanielnetoDotCom** [comment]
Delete from what page are you talking about?

**Comment by fakeologist** [comment]
https://streamable.com/znt02c

**Comment by DanielnetoDotCom** [comment]
Now you have this button

![image](https://user-images.githubusercontent.com/18009293/111177009-9b26f480-8588-11eb-801d-7bdaefc9a6a5.png)

**Comment by fakeologist** [comment]
Thanks great work.
