### ISSUE TITLE
The reader takes the entire width of the page 

### ISSUE THREAD

**Issue by JeanDavis91** [WWBN/AVideo#4699]
Hello

Very good job I really appreciate it works very well on a synology DS-216 + II server
What I can not have this aspect like the photo below

![pas ok](https://user-images.githubusercontent.com/61474191/111105329-0229b680-8553-11eb-9442-16914bb79ae2.jpg)

![ok](https://user-images.githubusercontent.com/61474191/111105328-01912000-8553-11eb-877b-30a8df41bcf8.jpg)

Thank you

**Comment by DanielnetoDotCom** [comment]
Try this

![image](https://user-images.githubusercontent.com/18009293/111152230-44f98780-856f-11eb-99eb-6aa9e4af1e1a.png)

**Comment by JeanDavis91** [comment]
Hello DanielnetoDotCom

Thank you it works but after I had 2 black bands (black frame behind the video) on each side of the video that I deleted now it's correct

thank you for your work

before
![bande noire](https://user-images.githubusercontent.com/61474191/111227612-1f0dca80-85e3-11eb-9f9f-6fa0c08e61da.jpg)

after
![sup bande noire](https://user-images.githubusercontent.com/61474191/111227659-30ef6d80-85e3-11eb-9c9c-a8a5bdd4db6e.jpg)

Jfr
