### ISSUE TITLE
Purpose of doNotIdentifyBy... settings

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4700]
What is the purpose of these settings:

doNotIndentifyByUserName
doNotIndentifyByEmail
doNotIndentifyByName

I have "doNotIdentifyByUserName" enabled, but I'm not sure where or if this has any effect?

**Comment by DanielnetoDotCom** [comment]
You can control what will appear as a video owner

![image](https://user-images.githubusercontent.com/18009293/111152792-e5e84280-856f-11eb-932e-3debeb49d1d3.png)

**Comment by joho1968** [comment]
OK. Thank you. In a user enumeration context, one issue is that most (all?) links have usernames in them.
