### ISSUE TITLE
Made videos “unlisted”. They still appear on the site while logged out. 

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4701]
**Describe the question**
I have videos marked as Unlisted and Private, that is, belonging to a user group. 

While not logged in I can navigate to the users page and see all of the metadata for the “Unlisted” videos. 

How do I configure this for unlisted videos which are truly hidden behind the paywall?

**Comment by DanielnetoDotCom** [comment]
do you mean on the channel? you can see unlisted videos?

**Comment by walt93** [comment]
Yes. On the user page for the account I can see all of the unlisted videos and so can web crawlers.

**Comment by DanielnetoDotCom** [comment]
Admins can see unlisted.

you can see with a regular user?

can you please screenshot?

**Comment by walt93** [comment]
I'm not logged in, looking at the account page. All of the videos I can see
 here I've marked as Unlisted and belonging to a group called Members. See below.

<img width="1333" alt="Screen Shot 2021-03-16 at 3 43 08 PM" src="https://user-images.githubusercontent.com/11711050/111389700-a6ece680-866e-11eb-8e24-a0ce84512b62.png">

<img width="1181" alt="Screen Shot 2021-03-16 at 3 44 59 PM" src="https://user-images.githubusercontent.com/11711050/111389719-b10ee500-866e-11eb-874e-3fb35347f488.png">

**Comment by DanielnetoDotCom** [comment]
Those are playlists, I must display the unlisted videos on the playlist, otherwise it will not play

**Comment by walt93** [comment]
So the playlist is causing all of the videos to appear? I have the playlist set to Private/Unlisted as well. If I remove the playlist, assume the videos will go to being private?

**Comment by DanielnetoDotCom** [comment]
The unlisted videos will only appear inside the playlist, but will not appear on the videos page or search

**Comment by walt93** [comment]
Got it, thank you.
