### ISSUE TITLE
Invalid channel name for manually added users

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4703]
When I create a user manually, and leave the channel name field empty, some things are not going as expected:

- It should probably warn me and not allow me to save the user record, if the channel name is required
- It should probably **NOT** use the currently logged in user's display name as the channel name

I was logged in as "Video Support" (username: videosupport), which is an admin user. When I created a new user manually, I left the channel name empty. When I saved the new user, the channel name was set to "Video Support" ... (?)

**Comment by DanielnetoDotCom** [comment]
You are right, I am sending a fix
