### ISSUE TITLE
Should it not be possible to disable the /locale translation interface?

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4704]
**Describe the bug**
It doesn't seem to be possible to disable the /locale translation interface.

**To Reproduce**
1. Go to my.video.site/locale, as a guest

**Expected behavior**
"Only logged in administrator accounts may access this resource"

I tested to "Save" as well, which (thankfully) generates an "access denied" message, but I really don't think the translation stuff should be available to guests, and further think it should be locked for anyone but administrators.

(I realize I can remove index.php and save.php from the /locale directory, but ...)

**Comment by DanielnetoDotCom** [comment]
I think I recently forbid this already 

![image](https://user-images.githubusercontent.com/18009293/111153700-09f85380-8571-11eb-9172-e4aef00cbc1e.png)
