### ISSUE TITLE
Disable sharing link (and menu) for embedded videos when login is required

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4705]
It would be nice if the SHARE button and right-click menu on embedded videos is removed when the platform is set to require users to be logged in. I tried finding a setting for this, but nothing I change seem to change this :-)

**Comment by DanielnetoDotCom** [comment]
Did you try that?

![image](https://user-images.githubusercontent.com/18009293/111153864-3ca24c00-8571-11eb-922d-c97b1c210a92.png)

or that

![image](https://user-images.githubusercontent.com/18009293/111153929-52b00c80-8571-11eb-90f5-ad2586d801fd.png)

**Comment by joho1968** [comment]
No, I did not. Thank you. Your response in #4706 actually does the job in this case, though it may be nice with some automatic logic for embedded videos if the site is set to require login (IMHO, of course).
