### ISSUE TITLE
Chat2 config not possible or manpage wrong

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4707]
Today i bought the Chat2 plugin trying to configure it now. As the "manual" says i should edit the config.php on the chatserver.

But mine looks like this:

![image](https://user-images.githubusercontent.com/50199132/111146822-29e84100-858a-11eb-9481-5406173c44b1.png)

In the tutorial this isnt crypted?

Should i delete all the crypted content and enter the lines from the tutorial/manpage?

**Comment by morbificagent** [comment]
OK, have deleted the crypted content and replaced it with the config from the tutorial (edited with my vars of course).

But now i am running in the same problem like:

https://github.com/WWBN/AVideo/issues/4655

**Comment by DanielnetoDotCom** [comment]
Please lets follow the other issue
