### ISSUE TITLE
Various embedding methods and their parameters

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4709]
There are a number of ways to embed videos from an AVideo instance. That's great.

* Is there a complete list of the various ways (i.e. the correct URLs and so on)? Or do they all start with "https://my.video.site/videoEmbed"?
* Is there a complete list of the various URL/parms parameters and what they mean?
* Is there a way to talk json to AVideo, like an API? I'm thinking being able to browse videos to embedd, etc. Possibly supplying user credentials too of course.

The reason I ask is for a WordPress plugin.

Also, is there a reason the permalinks contain the channelname?

**Comment by DanielnetoDotCom** [comment]
> * Is there a complete list of the various ways (i.e. the correct URLs and so on)? Or do they all start with "https://my.video.site/videoEmbed"?

No I do not have a complete list

> * Is there a complete list of the various URL/parms parameters and what they mean?

You can find here https://github.com/WWBN/AVideo/blob/master/.htaccess

> * Is there a way to talk json to AVideo, like an API? I'm thinking being able to browse videos to embedd, etc. Possibly supplying user credentials too of course.

https://github.com/WWBN/AVideo/wiki/AVideo-Platform-API

> Also, is there a reason the permalinks contain the channelname?

To keep you inside the same channel when you are watching a video
