### ISSUE TITLE
this is the error in apache

### ISSUE THREAD

**Issue by GoAirrit** [WWBN/AVideo#4710]
malikawan135
Mar 15, 10:52 AM
ReportSpam
[Mon Mar 15 09:47:44.697577 2021] [php7:error] [pid 31029] [client 111.119.177.16:6970] script '/var/www/AVideo/plugin/Live/droplive.json.php' not found or unable to stat, referer: https://live.goairrit.com/plugin/Live/
![7 Screenshot from 2021-03-15 19_48_06](https://user-images.githubusercontent.com/80485736/111173556-23070180-857d-11eb-82ae-b91af7f8cc4f.png)

**Comment by DanielnetoDotCom** [comment]
The drop live is not working yet, but try to live using OBS, if works, the problem may be on the meet server.
