### ISSUE TITLE
YPTSocket disconnected

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4711]
Once more me ;-)

trying to get YPTSocket running but without luck.
Eventually you can help again Daniel.

The Server is up and running:

![image](https://user-images.githubusercontent.com/50199132/111224370-a60c7400-85de-11eb-972b-4ced1870c9dd.png)

The port is bound, a firewall isnt in place:

![image](https://user-images.githubusercontent.com/50199132/111224536-e0761100-85de-11eb-9486-eb4e1a5402f2.png)

But the Socketconnection isnt estabished:

![image](https://user-images.githubusercontent.com/50199132/111224660-10251900-85df-11eb-94fe-85810d544455.png)

And the browser reports:

![image](https://user-images.githubusercontent.com/50199132/111224967-6f832900-85df-11eb-9787-9faa82f06880.png)

**Comment by morbificagent** [comment]
Found out that if i use another public ip of the same server in the configuration of the plugin, the connection can be established... strange.... because it listens on 0.0.0.0

But the reason why i trying to use the sockets is the chat2. Which doesnt work even when the socketconnection over the wrong ip+dns name is established.

The question is:

Can the chat2 over socket work if the socketconnection is established via an ip/dns-name which isnt part of avideo?

**Comment by DanielnetoDotCom** [comment]
FYI it will fail if you are using cloudflare

**Comment by morbificagent** [comment]
No i dont use cloudflare
