### ISSUE TITLE
YPT Socket Conneted but returning error when upon test

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#4712]
Testing wss://127.0.0.1:2053?webSocketToken=cVNUdVpqNk1mcVZlRVJKNzRkbC9WaUNxaVpGOHdoamJOR0diRUlaM2RVRTJLaG13YklpK3VJMmUxRkZKeFBLMzkweWRSVGkrSjN3TjNGSzYyV0szWHA3NklZVzhvOElLOHBqeDVJQWk0OWEvb01kZUNRUW1nTmN6cTRCZDRndW92bndhSkZqYTdLdGZ5ejUzZzI2Q1F0Qjd4TXVBSzVNRnVoengwUndWMmkyWC8zblhVNjRlWjhCSWg5WkhvWlB5R1F4aFVMYVMxajBzTVY2OTRTSWVoTlNGMDRGY1ltS0ZJaVJXOThhRWVJaG93eFhRc2NVWkw2d1NWa3QrMmhsb3FhSHRKK0FJZXN6ZkZRT3NEU0RXYjQxNjFLTVZpRFM5d1kzL3R0ZldMM1A2UHJrWi9BR085emkrWDBaa3lKd3lOeWtyaWV3aXNBdDVlTXBNVlhnR3lwY2pPVFM4Q0hhRkIyaktBckhNeUZxVGQzVWVIeUZEZVcrUDhlTUJSWmhVbDdXSElDLzY1ZnlxOUNybytnNDdQTFh4ODdWcTZidkpuTG1uek1SMktnU0gyd2ZQUzBOMVBzUGxNY3ZwOWtzUmFmTWMreVBRRXNiVHJUQjJoY1pYRllLSGpDS2xRaXJBUHNQT202S3dPYVlkaEVVNWJ6ZnN0MVJZWTZRNXdqdUdaRkRDblNQQ3hIbTNseEhQTm1pdmdpUGMvOUFwU2Z4enQydXlHdGQ3c0prPQ== [wss]
Could not connect: Connection closed before handshake
Message received {}
Could not connect: Connection closed before handshake
Could not connect: Connection to localhost:2053 failed during TLS handshake: Unable to complete TLS handshake: Peer certificate CN=`www.mhktube.com' did not match expected CN=`localhost'
Could not connect: Connection closed before handshake
Could not connect: Connection to 127.0.0.1:2053 failed during TLS handshake: Unable to complete TLS handshake: Peer certificate CN=`www.mhktube.com' did not match expected CN=`127.0.0.1

**Comment by akhilleusuggo** [comment]
`Unable to complete TLS handshake`

Check the validity of your SSL certificate .

**Comment by milehighkaraoke** [comment]
SSL Cert is valid just not sure if i have to point the socket to the cert and if so how?

**Comment by milehighkaraoke** [comment]
Sent from my T-Mobile 5G Device
Ssl is good


-------- Original message --------
From: akhilleusuggo ***@***.***>
Date: 3/16/21 12:04 AM (GMT-07:00)
To: WWBN/AVideo ***@***.***>
Cc: milehighkaraoke ***@***.***>, Author ***@***.***>
Subject: Re: [WWBN/AVideo] YPT Socket Conneted but returning error when upon test (#4712)


Unable to complete TLS handshake

Check the validity of your SSL certificate .

**Comment by ukdomainers** [comment]
@milehighkaraoke did you sort this as i have the same problem
