### ISSUE TITLE
Live no longer disconnects when I stop straming

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#4713]
After doing latest git pull there seems to be a few problems within the live streaming and the YPT Socket. Live Stream stays connected after i stop streaming and the live embedded no longer plays on my web page although it is showing the correct view count.

**Comment by DanielnetoDotCom** [comment]
Your issue is not clear to me, but please make sure you have the nginx.conf on_publish_done parameter

https://github.com/WWBN/AVideo/blob/3827a28274dff2da119df7bb0ed6f1cb7b307e3e/plugin/Live/install/nginx.conf#L22

**Comment by milehighkaraoke** [comment]
To get the live stream to shut off in youphptube I have to shut off broadcast in OBS. That should be it, we'll that was how I did it until the last gift pull. Now after I shut off broadcasting in OBS it still shows live in youphptube. To get it to stop I have to go to site settings and clear cach, only then does it stop showing the broadcast.



Sent from my T-Mobile 5G Device



-------- Original message --------
From: Daniel Neto ***@***.***>
Date: 3/16/21 5:28 AM (GMT-07:00)
To: WWBN/AVideo ***@***.***>
Cc: milehighkaraoke ***@***.***>, Author ***@***.***>
Subject: Re: [WWBN/AVideo] Live no longer disconnects when I stop straming (#4713)


Your issue is not clear to me, but please make sure you have the nginx.conf on_publish_done parameter

https://github.com/WWBN/AVideo/blob/3827a28274dff2da119df7bb0ed6f1cb7b307e3e/plugin/Live/install/nginx.conf#L22

**Comment by DanielnetoDotCom** [comment]
@milehighkaraoke do you have the on_publish_done in your Nginx conf?

do not forget to restart Nginx and clear the cache after adding it.

**Comment by milehighkaraoke** [comment]
#
![20210316_205714](https://user-images.githubusercontent.com/70327833/111408201-8b97d080-869a-11eb-88f2-f84bcffdaf34.jpg)
 
Everything worked perfectly for the past 2 months and after the latest git pull I have to always clear cache in the Youphptube site settings to get the broadcast to stop.

**Comment by milehighkaraoke** [comment]
This is giving me anxiety lol.  It showes as stopped on the account but it shows as live up top. It is sending to encoder when I stop OBS. Please help this is beyond frustrating 😫

![20210316_235426](https://user-images.githubusercontent.com/70327833/111421816-3e742880-86b3-11eb-9ec3-af26ecf13e99.jpg)
![20210316_235445](https://user-images.githubusercontent.com/70327833/111421817-3f0cbf00-86b3-11eb-863d-df0051482c21.jpg)

**Comment by akhilleusuggo** [comment]
Are you referring to the notification or the socket ?

**Comment by milehighkaraoke** [comment]
The notification..... [cid:storage_emulated_0_DCIM_Camera_20210316_235426_jpg_1615965447626]



Sent from my T-Mobile 5G Device



-------- Original message --------
From: akhilleusuggo ***@***.***>
Date: 3/17/21 1:12 AM (GMT-07:00)
To: WWBN/AVideo ***@***.***>
Cc: milehighkaraoke ***@***.***>, Mention ***@***.***>
Subject: Re: [WWBN/AVideo] Live no longer disconnects when I stop straming (#4713)


Are you referring to the notification or the socket ?

**Comment by DanielnetoDotCom** [comment]
@milehighkaraoke I can see you do not have the on_publish_done in your nginx.conf

https://github.com/WWBN/AVideo/blob/94cf448fade9d4be9b59757daca150cde73324ba/plugin/Live/install/nginx.conf#L22

**Comment by milehighkaraoke** [comment]
Thank you so much...... That was it..... I was so flustered I did not breath for a second and focus..... thank you again....
