### ISSUE TITLE
Please correct Turkish flag on Navbar.

### ISSUE THREAD

**Issue by RisKatOr** [WWBN/AVideo#4716]
I can't Pull Request, please correct...

https://github.com/WWBN/AVideo/blob/d5a98f3b644e3f931a0efed5d7e597b61b7a7de9/objects/bcp47.php#L420
must be 'flag'=>'**tr**'

https://github.com/WWBN/AVideo/blob/d5a98f3b644e3f931a0efed5d7e597b61b7a7de9/objects/bcp47.php#L421
must be 'flag'=>'**tr**'

**Comment by DanielnetoDotCom** [comment]
Done, thanks
