### ISSUE TITLE
design  player 

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#4717]
Hello @DanielnetoDotCom , I have been asking you for this design for 1 years : you always refused it

I show you your current design

![image](https://user-images.githubusercontent.com/39193219/111299894-c5dc8000-8650-11eb-8878-f517e001ddb8.png)

I think you need to go much deeper into your reflection 

I just made a change on the browser 

I think the player must be like I show you on the photo

it is bigger and more pleasant to look at

![image](https://user-images.githubusercontent.com/39193219/111299515-4d75bf00-8650-11eb-86e0-01e616e12961.png)

![image](https://user-images.githubusercontent.com/39193219/111299575-62525280-8650-11eb-9554-da87013a9d63.png)

**Comment by DanielnetoDotCom** [comment]
Try this on the new update

![image](https://user-images.githubusercontent.com/18009293/111322967-3a5ef100-8648-11eb-9283-284d8a7cf19c.png)

**Comment by syldri** [comment]
thank you very much
and he fails to make the adaptations for any type of screen

I test on a MacBook pro laptop PC

![image](https://user-images.githubusercontent.com/39193219/111390359-e3423600-86b2-11eb-8fc6-18e533fe8e64.png)

**Comment by DanielnetoDotCom** [comment]
It is not a fail, if you move the mouse out the chat will slide out the screen 

that is the way I found to not occupy the screen.

your screen must be 1400px with minimum to have a static chat on side

**Comment by syldri** [comment]
@DanielnetoDotCom  it's not  professional 

I'm on the same screen, look at the Twitch site

I show you two pictures

the first picture is normal you see the cat and the player

When you look at the second image where I have the red arrow that you click on button, the screen gets bigger

Remember that all screens are not the same size and that the right site can be adapted to all screens automatically


![image](https://user-images.githubusercontent.com/39193219/111393922-f86e9300-86b9-11eb-8152-e2aa438866ff.png)

picture 2

![image](https://user-images.githubusercontent.com/39193219/111394785-b0507000-86bb-11eb-808c-dd802335f54b.png)

**Comment by DanielnetoDotCom** [comment]
I agree, twitch is the best in this case, I will review it when I get some free time.

**Comment by morbificagent** [comment]
@syldri eventually this small change of when the static layout jumps to the crazy one ( 😉 ) can help you until this is "redesigned":

https://github.com/WWBN/AVideo/issues/4720#issuecomment-803076997
