### ISSUE TITLE
Cache the feed root site

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4718]
Sites with high number of videos , if you try to retrieve the feed page from root website (https://avideo.com/feed/) ; it may take hours .
Also it does consume a lot of memory , and takes longer then generating the sitemap .

Feature request ; 

Option to disable feed generator
Option to cache the feed generator ( X Minutes ) .

Users keeps requesting the feed pages again and again , and memory server get bumped .

**Comment by DanielnetoDotCom** [comment]
What about set the `$global['rowCount']` in your configuration.php file?



of if you control the feed, pass in the URL the ?rowCount=100 for example

`https://avideo.com/feed/?rowCount=10`

**Comment by akhilleusuggo** [comment]
The idea is not to limit users from getting all the feeds . Is to optimize the feed page . Caching is required . Would also be good to create it along with the sitemap . This way the server doesn't have to fetch the entire database twice .

The sitemap cache time is 10h ( by default ) . Is good to have the same thing for the feed .

Using `https://avideo.com/feed/?rowCount=10` Will pick randomly 10 feeds . This one just kills the goal of rss feed . Users won't be getting the news/ newer videos uploaded .

$global['rowCount'] this one the same thing , and will affect all functions that does obey this function . Example sitemap ; browsing videos and count . 
```
sitemap
videosManegerRowCount
videosListRowCount
```
And maybe other functions that I'm not aware of .

**Comment by DanielnetoDotCom** [comment]
Cache enabled now

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Thank you for taking the time .

I still can't give you a feedback since I'm not able to generate the feed page . It's taking 30-40mn then breaks . 
Sitemap takes around ~5mn . I'll keep trying , then I'll leave a feedback . Thank you 🥇

**Comment by DanielnetoDotCom** [comment]
Currently, the main problem is I guess your feed cannot generate it from all your videos. also it may create a huge XML/JSON file.

It is too big I guess the sites will reject it.

**Comment by akhilleusuggo** [comment]
yes , it's 20.000 videos
