### ISSUE TITLE
meet are not working after last update

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4719]
Hi, i have a server with ubuntu 18.06 and the latest Avideo .
i create a meet and will join the meet but the site is black.
Its a public meet without password.

**Comment by 01123581321345589144233** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)
The external api are not loaded
https://domain/plugin/Meet/external_api.min.map

**Comment by DanielnetoDotCom** [comment]
try to switch servers, go to europe or NA

**Comment by 01123581321345589144233** [comment]
i have changed the servers but is the same result

**Comment by DanielnetoDotCom** [comment]
Strange, do we have a meet today? I will review that for you

**Comment by 01123581321345589144233** [comment]
yes
