### ISSUE TITLE
Chat2 Latest Version (5 something) Floats Off Screen In Small Windows And Floats Back On Hover

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4720]
**Describe the bug**
When using the latest version of the Chat2 plugin on a small screen, the Chat window floats almost off the screen and only floats back when hovered over.
This is a very annoying thing. 
I have disabled hover effects in the settings but it does not help.
It seems to only do it when you make the browser window narrow.

**To Reproduce**
1. Go to do a Live Stream with Chat enabled
2. Shrink the width of your browser to approximate size of a smartphone
3. Notice how the chat floats off to the right of the screen and floats back on hover

**Expected behavior**
Stay put.

**Screenshots**
<img width="515" alt="Screen Shot 2021-03-16 at 9 48 46 AM" src="https://user-images.githubusercontent.com/7376298/111330030-983a0b80-863d-11eb-8a58-39164414a20c.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 14.03

**Comment by DanielnetoDotCom** [comment]
I just sent a new update Chat2 v6 it should be working good now

**Comment by bbyrdhouse** [comment]
thnx ... will update it now and let you know

**Comment by bbyrdhouse** [comment]
No ... this seems to have made things worse.

Now the chat window on a full size browser window is off to the right and not in its usual place and then when you shrink your browser window to be thin the chat floats off screen and only appears when hovered over.

Would it be possible for me to revert back to pre-version 5 of the plugin?

<img width="591" alt="Screen Shot 2021-03-17 at 8 41 44 AM" src="https://user-images.githubusercontent.com/7376298/111477447-1e695700-86fd-11eb-9b96-d50ccb37d845.png">
<img width="561" alt="chat2" src="https://user-images.githubusercontent.com/7376298/111477899-8fa90a00-86fd-11eb-8cb1-5b4b58eb5ac7.png">

**Comment by DanielnetoDotCom** [comment]
To make it available on the bottom you must change the layout 

![image](https://user-images.githubusercontent.com/18009293/111485308-46fd4b00-8715-11eb-88ef-de230d52e397.png)

Select static under video

**Comment by morbificagent** [comment]
Hi together,

in my opinion it should be possible to configure the chat to be static most of the time and eventually go to the small "bubble" like it is displayed on mobile-devices.
This layout of the chat on mid-screen devices (my surface for example) is confusing:

** V1 Good i think:**
![image](https://user-images.githubusercontent.com/50199132/111644948-98363900-8800-11eb-9b6a-6ea67a13d453.png)

** V2 I think this is strange:**
![image](https://user-images.githubusercontent.com/50199132/111645226-ca479b00-8800-11eb-8ca9-e6603a70f15b.png)

**V3 after clicking on "close chat"... its strange too:**
![image](https://user-images.githubusercontent.com/50199132/111645674-3fb36b80-8801-11eb-93f7-d4de97a1751c.png)


**V4 Good i think**
![image](https://user-images.githubusercontent.com/50199132/111645572-1db9e900-8801-11eb-98f9-4daac7ecc1eb.png)

If i would have a wish for that i would only use V1 and jump to V4 if the screen becomes to small. 
On V4 a red "Counter" for the unread Messages would be great ;-)

But The versions between that are confusing me.
I played around with the config (staticLayout, Left, Right, disableHoverEffect) but many of these settings dont change anything for me and i cant get rid of V2 and V3

**Comment by morbificagent** [comment]
BTW the screenshots are con Chat2 v 6.1

**Comment by DanielnetoDotCom** [comment]
Yes, it may be a good idea, I will improve this layout when I get some free time.

**Comment by morbificagent** [comment]
That would be great.
I know there is much to do (like every day ;-) ) But this strange chat window things are directly affect the enduser experience.

Avideo is a great project and im happy to use it and love your work.
And so i feel offended when my viewers frown when they see the chat which hangs out of the viewable screen ;-)

**Comment by JoshWho** [comment]
Switching it to Static under video will fix it back the way it use to be.

**Comment by morbificagent** [comment]
Ok, was looking at the staticRight.css in Chat2 and changed line 29:

@media (max-width: 1400px)

to

@media (max-width: 800px)

This let the static right chat be there most of the time for me.

Its not all that i whished but a quick workaround until Daniel has time to look at the layout of the Chat.
