### ISSUE TITLE
Deleting users

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#4721]
I must have overlooked something, but where do I delete users? I tried first moving some test users to the inactive tab, but cannot find an option to remove them permanently.

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/issues/4607

**Comment by joho1968** [comment]
OK. Fair enough. This will, however, create GDPR issues. A person/user has the right to be "forgotten". Without the possibility to delete users, this is impossible. I would kindly suggest you reconsider this decision. When a user is deleted, any associated channels, comments, likes, etc should also be removed. It'd be nice with an option, in that case, to transfer the ownership of the deleted user's videos to another user (or to have them removed).

**Comment by DanielnetoDotCom** [comment]
Agree, I may add this feature in future updates
