### ISSUE TITLE
Fresh install stuck in maintanance

### ISSUE THREAD

**Issue by zanetta** [WWBN/AVideo#4722]
Hello,

I made a fresh install on a ubuntu server 20.04. However i followed ever step and everything goes fine, even i remove the install dir it no shows the site, just the mantance page.

any help pls?

**Comment by DanielnetoDotCom** [comment]
check the apache log and streamer log

**Comment by maxz2008** [comment]
Same error with mine, Pleas help. 
No error in the apache logs.

<a href="https://ibb.co/7gJSqG0"><img src="https://i.ibb.co/tZMH9b1/error.png" alt="error" border="0"></a>

**Comment by maxz2008** [comment]
I found the problem is due to install directory still exist.
After removing the install folder, then i can load.

Seems the script is checking for this condition.
