### ISSUE TITLE
subtitles not added

### ISSUE THREAD

**Issue by lahaj** [WWBN/AVideo#4723]
Hello, subtitles not added on the video, I tried too much
Previous subtitles already exist, and when I add subtitles to a new video, it is not added
Even though the plugin for subtitle is updated for me
Thank you very much

**Comment by DanielnetoDotCom** [comment]
In what site?

can you share the subtitle file and what video it is so I can test?

**Comment by lahaj** [comment]
Hello Mr. Daniel, I am pleased with your presence and your response. I hope you are well
The two sites have the same problem
ooogel.com
mrvod.net
Subtitles to be added to the video
On site  mrvod.net
The subtitle is in the video player option for double subtitle, as you can see in the picture, dear sir

![sub titile](https://user-images.githubusercontent.com/71000399/111377346-f6a4cf80-86b9-11eb-834c-5052759ee6f5.jpg)

**Comment by DanielnetoDotCom** [comment]
Can you please share the video link here so I can check?

**Comment by lahaj** [comment]
This is the link for the video, but not only in one video. I cannot add subtitles to all the videos
And in both sites

https://ooogel.com/video/272/sas-red-notice-2021-720p-webrip-5.1-mixtime.net?channelName=Mixtime&catName=

**Comment by DanielnetoDotCom** [comment]
Hi, I found the problem, sorry for the confusion. please check now

**Comment by lahaj** [comment]
Sorry for being late
Yes, sir, the problem is solved and everything is fine
Do not regret the technical error that occurs, and this is not a problem
You are dear and I have all the respect and appreciation for you
Thank you very much, sir, and I am sorry for bothering you
Accept my greetings
