### ISSUE TITLE
Always English menu

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#4725]
17-Mar-2020 8:00AM(JST) I run git pull AVideo and AVideo-Encoder.
I access AVideo. Menu and other all engish.
I tried firefox new edge and IE11 same.
This problem does not occured till Yesterday. I want to alway display japanes menu 

![AV1](https://user-images.githubusercontent.com/46562199/111468870-645c0480-8769-11eb-8801-36b1cdf55544.png)

**Comment by DanielnetoDotCom** [comment]
The same did not happen on the demo site.

![image](https://user-images.githubusercontent.com/18009293/111482668-e1a85a80-8712-11eb-97f4-ef169f800c06.png)


please make sure your site is up to date

check what do you have selected in your configuration

![image](https://user-images.githubusercontent.com/18009293/111482865-0d2b4500-8713-11eb-8a13-71ca54d67e7b.png)

**Comment by gmtabatinga** [comment]
Hi!

The same short list of 13 expressions is always displayed on the www.mydomain/locale page, no matter what language is selected: 

     Congratulations!
     Original words found
     Paste here the translated words, one each line
     Permission denied
     Save File
     Sorry!
     Translate AVideo
     Translated Array
     Unable to open file!
     Word Translations
     You need to make your locale folder writable
     Your %slocale dir is not writable
     Your language has been saved!


Please evaluate what's going on.

Thanks 

![LOCALE_page_error](https://user-images.githubusercontent.com/68403809/111841246-71e5cb80-88dc-11eb-9597-7e9313055150.png)
