### ISSUE TITLE
Encoder is giving me plain login screen  and qill not let mw log in

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#4726]
Another issue since latest git pull.  I can not access my encode
![20210317_083432](https://user-images.githubusercontent.com/70327833/111485911-a733c300-86fc-11eb-8cc7-0f80b328dc7d.jpg)
r. I get a munimul login screen that does not accept my credentials.

**Comment by DanielnetoDotCom** [comment]
Make sure the streamer and encoder are up to date.

just in case check your HTML source code and see what is the CSS URLs in it

**Comment by milehighkaraoke** [comment]
Both were recently updated via git pull. I get up to date when I do git pull on both streamer and encoder. Where do I find the html source code?

**Comment by DanielnetoDotCom** [comment]
I checked for you

Looks like your encoder has as the main site http://tube.mhktube.com/ 

![image](https://user-images.githubusercontent.com/18009293/111490569-e6244180-8719-11eb-8cc1-dd69bcbbf787.png)


Your encoder is **HTTPS** and your site is **HTTP**, browsers do not allow you to use the assets from a non-secure source

![image](https://user-images.githubusercontent.com/18009293/111490500-d73d8f00-8719-11eb-9498-8ff1b66b3fb1.png)

I suggest you reinstall your Encoder. delete the configuration.php file, drop the encoder database and install it again.

**Comment by milehighkaraoke** [comment]
By dropping the encoder database  will I lose reference to any files on the site when I reinstall and rename the encoder database

**Comment by JoshWho** [comment]
I am having the same issue after updating my encoders

Can't log in keeps forcing different domain

**Comment by JoshWho** [comment]
doing a rollbaCK now

**Comment by JoshWho** [comment]
I left my local Encoder alone so u can see what it is doing on the other ones when I update them.

https://www.joshwhotv.com/Encoder/

My normal encoders are the ww2. ones I have setup in my encoder network. I just rolled them back until this gets fixed using command in the encoder directory.

git reset --keep HEAD@{1}

**Comment by milehighkaraoke** [comment]
I will give this a try in the morning :)



Sent from my T-Mobile 5G Device



-------- Original message --------
From: JoshWho ***@***.***>
Date: 3/18/21 1:22 AM (GMT-07:00)
To: WWBN/AVideo ***@***.***>
Cc: milehighkaraoke ***@***.***>, Author ***@***.***>
Subject: Re: [WWBN/AVideo] Encoder is giving me plain login screen and qill not let mw log in (#4726)


I left my local Encoder alone so u can see what it is doing on the other ones when I update them.

https://www.joshwhotv.com/Encoder/

My normal encoders are the ww2. ones I have setup in my encoder network. I just rolled them back until this gets fixed using command in the encoder directory.

git reset --keep HEAD@{1}

**Comment by milehighkaraoke** [comment]
Josh, I believe we are behind on our approach with websockets. I went ahead and dropped my database in mysql deleted encoder folder and then proceeded to reinstall encoder making sure I am at my https address when installing I also am making sure that  https address is first in allowing streamer sites....   all done and it's working perfectly now. Oh yes you must also clear your site cach at the end.



Sent from my T-Mobile 5G Device



-------- Original message --------
From: JoshWho ***@***.***>
Date: 3/18/21 1:22 AM (GMT-07:00)
To: WWBN/AVideo ***@***.***>
Cc: milehighkaraoke ***@***.***>, Author ***@***.***>
Subject: Re: [WWBN/AVideo] Encoder is giving me plain login screen and qill not let mw log in (#4726)


I left my local Encoder alone so u can see what it is doing on the other ones when I update them.

https://www.joshwhotv.com/Encoder/

My normal encoders are the ww2. ones I have setup in my encoder network. I just rolled them back until this gets fixed using command in the encoder directory.

git reset --keep HEAD@{1}

**Comment by JoshWho** [comment]
I am not understanding what your fix or solution was. Could u explain it a little more please?

**Comment by milehighkaraoke** [comment]
1 Google how to drop your mysql encoder database
2 Drop Database
3 delete Encoder Folder
4 git clone new encoder
5 create new encoder Database Mysql
6 go to your site via https and reinstall your encoder.
7 clear your site cach
8 get back to business

Hope this helps



Sent from my T-Mobile 5G Device



-------- Original message --------
From: JoshWho ***@***.***>
Date: 3/18/21 5:45 PM (GMT-07:00)
To: WWBN/AVideo ***@***.***>
Cc: milehighkaraoke ***@***.***>, Author ***@***.***>
Subject: Re: [WWBN/AVideo] Encoder is giving me plain login screen and qill not let mw log in (#4726)


I am not understanding what your fix or solution was. Could u explain it a little more please?

**Comment by milehighkaraoke** [comment]
Ok, this fix is no longer working I am back to a white screen. DAN what is next
![20210319_044949](https://user-images.githubusercontent.com/70327833/111769410-d36f5100-886e-11eb-833b-f74a8af55418.jpg)
![20210319_044812](https://user-images.githubusercontent.com/70327833/111769414-d407e780-886e-11eb-8c4c-3ff849322ef6.jpg)

**Comment by milehighkaraoke** [comment]
I went ahead and went through reinstalling the encoder again and now it's working  again. This is frustrating

**Comment by DanielnetoDotCom** [comment]
The only reason I can imagine is if your streamer went offline

**Comment by JoshWho** [comment]
So how is this fixable?

**Comment by milehighkaraoke** [comment]
https://mhktube.com/upload 
It's fixed. Those steps  work and add to them 1 step
Make sure all reference site urls are as follows  https:// your domain.com    and also in advanced site settings and General settings  you will find reference urls that have to be identical.

**Comment by JoshWho** [comment]
I want to know what is breaking it though so I can manually just fix it.

**Comment by milehighkaraoke** [comment]
Misconfiguration is the problem what worked beforeweb socket implementationno longer works for security

**Comment by milehighkaraoke** [comment]
Did you check your encoder source url and make sure it's http?



Sent from my T-Mobile 5G Device



-------- Original message --------
From: JoshWho ***@***.***>
Date: 3/19/21 7:35 AM (GMT-07:00)
To: WWBN/AVideo ***@***.***>
Cc: milehighkaraoke ***@***.***>, Author ***@***.***>
Subject: Re: [WWBN/AVideo] Encoder is giving me plain login screen and qill not let mw log in (#4726)


I want to know what is breaking it though so I can manually just fix it.

**Comment by milehighkaraoke** [comment]
View-source:http://www.joshwhotv.com/Encoder/

**Comment by milehighkaraoke** [comment]
Here is your problem. You must install your encoder without  the www 

![Screenshot_20210319-074633_Samsung Internet](https://user-images.githubusercontent.com/70327833/111790258-a0858700-8887-11eb-8a28-d3236901b6ec.jpg)

**Comment by milehighkaraoke** [comment]
Like this  but first you have to reinstall your encoder  from 
https://joshwhotv.com/Encoder/ 
Instead of https://www.joshwhotv.com/Encoder/

![Screenshot_20210319-075140_Samsung Internet](https://user-images.githubusercontent.com/70327833/111790649-08d46880-8888-11eb-9a31-d742122ecf2d.jpg)
![Screenshot_20210319-075117_Samsung Internet](https://user-images.githubusercontent.com/70327833/111790650-096cff00-8888-11eb-821f-df6c3dee7bd8.jpg)

**Comment by JoshWho** [comment]
not a solution but it is a workaround. I want it to work like it did before.

**Comment by DanielnetoDotCom** [comment]
Josh, your domain https://jwtv.joshwhotv.com/ has SSL problems

this update may resolve the bad streamers issues.

**Comment by JoshWho** [comment]
i dont use jwtv it suppose to be www

**Comment by JoshWho** [comment]
Yes that update did fix it though. It looks good now.

**Comment by JoshWho** [comment]
And I can also confirm it works on all my other encoders as well.
