### ISSUE TITLE
Video stuck in encode

### ISSUE THREAD

**Issue by ccarlile1** [WWBN/AVideo#4728]
Is there a way to clear the encoder queue? We had a live stream that seems to have gotten stuck in the encoder. It has been sitting at 61% since January. It only shows in the sharing queue and not the queue log so I can't delete it. I can't encode anything else because it just goes to next in line and will never encode because of the one that is stuck.

![1](https://user-images.githubusercontent.com/80840738/111503581-7e1b2e80-870c-11eb-9980-8047a7e95632.PNG)
![2](https://user-images.githubusercontent.com/80840738/111503583-7e1b2e80-870c-11eb-8b59-bbd06c19ead9.PNG)

**Comment by DanielnetoDotCom** [comment]
Is that your encoder?

if yes you should be able to login as encoder admin (different than site admin) and remove it.

**Comment by ccarlile1** [comment]
Yes, this is our own encoder. How do I log in as encoder admin. We paid for
the installation of this so we didn't set up an encoder admin account.

**Comment by DanielnetoDotCom** [comment]
Try this

https://github.com/WWBN/AVideo/issues/238#issuecomment-720449518
