### ISSUE TITLE
Mobile App Subscibers Issue

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4729]
When I try to view the list of subscribers I get the following message:

"Sorry! We are unable to find a subscriber for you."

Is this list suppose to show the users who are subscribed to my channel or the channels to whom I am subscribed to. In anycase the list is not showing.

I can't screenshot my mobile to show but basically its the subscribe button on the bottom of the mobile app.

**Comment by DanielnetoDotCom** [comment]
Hi, this update may show you who subscribed to you.

In the next app update, I will display who you subscribed to.
