### ISSUE TITLE
Offline Badge on live Videos

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4730]
Hi together,

Is there any way to hide the Online/Offline Badge on live streams?

Sometimes it goes offline at some streams but i can watch them pretty well without a problem.

So the people watching the stream get panic for nothing and i hear the voices: "what is this? Inside a live Stream an offline overlay even when the stream is running? Dont you have your System under control?"

Of course eventually that is the point as my config could be wrong at some point but when the stream is running this is nothing the watching people must see i think...

**Comment by DanielnetoDotCom** [comment]
Please update and try to check the doNotShowOnlineOfflineLabel option

**Comment by morbificagent** [comment]
@DanielnetoDotCom you are the best :-)

Its working 👍
