### ISSUE TITLE
Please allow me to disable the footer on the Charts page

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4732]
This floating footer is not working right with the charts page on my site no matter what we tried so is there a way to just not show the footer on the charts page PLEASE???

![download (7)](https://user-images.githubusercontent.com/39392449/111589964-89656d00-8793-11eb-8007-f68fe1ff3c47.png)

**Comment by DanielnetoDotCom** [comment]
This is what I am seing on your page now

![image](https://user-images.githubusercontent.com/18009293/111657391-2521c800-87ea-11eb-9bd7-fbabee00f594.png)



where do you enable the floating footer?

**Comment by JoshWho** [comment]
In Chrome it does not look like that.

**Comment by DanielnetoDotCom** [comment]
This was a chrome screenshot

**Comment by JoshWho** [comment]
that is not what I am seeing and others been reporting to me.

**Comment by JoshWho** [comment]
https://user-images.githubusercontent.com/39392449/111710867-86f92680-8818-11eb-863f-f4f19cea3700.mp4

**Comment by DanielnetoDotCom** [comment]
Can you please check for JS errors?

**Comment by JoshWho** [comment]
It is only that page it is doing it to. all other paged look fine

**Comment by JoshWho** [comment]
If you could just change the bottom px  to -300 it looks great. 

What it is now
`<footer style="position: fixed; bottom: 100px; width: 100%; background-color: rgb(242, 242, 242);" id="mainFooter" data-iceapc="6" data-iceapw="8">`


What is should be to fix it.
`<footer style="position: fixed; bottom: -300px; width: 100%; background-color: rgb(242, 242, 242);" id="mainFooter" data-iceapc="6" data-iceapw="8">`

**Comment by JoshWho** [comment]
I just found that in CustomizeAdvance
