### ISSUE TITLE
Static layout for Chat2 is broken

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4733]
Chat was working good in the static layout now it is seperated after the latest update. How to get it back to the old design right next to the player?

![49f643ee-b825-4a65-a4a3-1e9a78d4ee04](https://user-images.githubusercontent.com/39392449/111591896-0d205900-8796-11eb-9b3c-eb4e33bdb8f6.png)

**Comment by bbyrdhouse** [comment]
Likely related to this issue https://github.com/WWBN/AVideo/issues/4720

The fix was to grab the latest version and then to reset the settings of the chat plugin.

Hope this helps

**Comment by JoshWho** [comment]
what do u mean by reset the settings?

**Comment by JoshWho** [comment]
I see what you mean. I now set it to static under video and it is back the way i want it. Thank you.
