### ISSUE TITLE
Plugin-Website Login with Mail gone :-(

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4734]
Hi Daniel,

wanted to take a look on my buyed plugins but i cant login to your plugin-website anymore.

Only facebook and google+ is available but i had an account with mail address...

**Comment by DanielnetoDotCom** [comment]
Hi, we had a server problem yesterday.
can you please try again?

**Comment by morbificagent** [comment]
Ah ok, found it out... The Link in the actual Streamer-Version to the pluginstore redirects to:

https://plugins.avideo.com/

this one isnt working with mail-login.

But this one is ok:

https://youphp.tube/marketplace/
