### ISSUE TITLE
Meetings Quality is no longer good. THe recordings are so pixelated

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4735]
Live meetings quality is very low and pixelated now. Making the recordings of the meetings not readable. Even the live in real time looks like this now. I have my personal settings on HD Quality in the Options on it but this is what everyone including the live streaming encoder sees. 

![1a94a6e4-ce6a-42ac-9645-4f3818fd0f81](https://user-images.githubusercontent.com/39392449/111598997-cdf60600-879d-11eb-958a-a19366116e7e.png)

**Comment by DanielnetoDotCom** [comment]
Hi

maybe the server is too busy at this time.

can you try to switch the server?

I am aware the NA server is busier than the EU server

**Comment by JoshWho** [comment]
I had complaints since the last update when it had to go reinstalled last weak It has been the same quality the last 4 days now that I have used it. Seems like the bitrate got really lowered

**Comment by DanielnetoDotCom** [comment]
I just reduce the total amount of simultaneous meets on the same server, I hope it resolves the performance.

but still looks to me a connection issue, because I am doing lives and they work fine. check the connection/performance of your live server.
