### ISSUE TITLE
How To I Reset The Livestream Server?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4737]
Hi,
On Tuesday of this week I updated to the latest version and since then (yesterday and today) I have been unable to do a livestream using 3rd party software or apps.

Seems like this happened once before and I had to reboot the streaming server but I can't seem to find the thread that gave those instructions.

Could someone provide me the terminal command to restart the live-streaming server and see if that fixes things.

NOTE: On Tuesday, I also rebooted the whole server, so I am not sure if that had anything to do with it.

EDIT: Seems like I recall it had something to do with NGNX ... I could be wrong though.

**Comment by peterflitz** [comment]
Hi,

on the fly:
sudo /usr/local/nginx/sbin/nginx -s reopen

The live streams have a problem with the cache.
Before and after, empty the main cache until that is fixed.

greeting

**Comment by bbyrdhouse** [comment]
Using that command it returns this:
`nginx: [alert] kill(766, 10) failed (3: No such process)`

**Comment by bbyrdhouse** [comment]
Still unable to livestream to my sever ... I think the livestreamer just needs to be restarted but I am not sure ...

**Comment by DanielnetoDotCom** [comment]
Try to stop 

`sudo /usr/local/nginx/sbin/nginx -s stop`

then start 

`sudo /usr/local/nginx/sbin/nginx `
