### ISSUE TITLE
Uploading files to the streamer

### ISSUE THREAD

**Issue by reuvygroovy** [WWBN/AVideo#4738]
I am using the latest version just downloaded today.

When trying to upload a .mp4 file to the streamer it is stuck at uploading.

In the php-fpm error log I see:

[18-Mar-2021 16:08:09 UTC] PHP Fatal error:  Uncaught ValueError: Path cannot be empty in /var/www/AVideo/upload/objects/Encoder.php:947
Stack trace:
#0 /var/www/AVideo/upload/objects/Encoder.php(947): get_headers()
#1 /var/www/AVideo/upload/objects/Encoder.php(704): Encoder::getDurationFromFile()
#2 /var/www/AVideo/upload/view/upload.php(75): Encoder::sendFile()
#3 {main}
  thrown in /var/www/AVideo/upload/objects/Encoder.php on line 947

Running on CentOS 8. 

What's the problem here?

**Comment by reuvygroovy** [comment]
BTW - the same error happened when I tried to upload from the files which I copied to the server

**Comment by DanielnetoDotCom** [comment]
Our line 947 is totally different than the one in your error

https://github.com/WWBN/AVideo-Encoder/blob/9c4a8e69464c7ee111c84c3732c31a7cc2b7c509/objects/Encoder.php#L947

You did not get the newest version (make sure you use the `git clone` command)

**Comment by reuvygroovy** [comment]
Thanks. Strange, since I downloaded the latest version.

Can you explain to me if I already have an MP4 video, do I need to use the encoder, or can I just upload directly to AVideo videos that I have? Not clear what the job of the encoder is.

**Comment by DanielnetoDotCom** [comment]
Check here https://github.com/WWBN/AVideo/wiki/About-Video-Upload

**Comment by reuvygroovy** [comment]
Thanks!
