### ISSUE TITLE
problems after upgrading the plugins and script

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#4739]
on the home page the drop-down menus do not work
I get this message in the footer see the photo
![footer](https://user-images.githubusercontent.com/60543030/111663138-cf144b00-8810-11eb-998a-4cb02b7dc3da.jpg)

cache clearing links do not work
the thumbnails are blurred
I have downloaded the latest git pull and the latest plugins
some help??

Thank you
Ilias

**Comment by wetubeclub** [comment]
the problem is found in the plugin gallery if I disable it all the links on the home page work normally
when activated the above problems I mentioned earlier are created

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that, it is fixed now.

**Comment by wetubeclub** [comment]
is ok now workining 
Thank you Daniel
Ilias
