### ISSUE TITLE
Record controls useable?

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4741]
Hi Daniel,

I am actually using the live recording plugin and its working good.

But at the moment i use record all in nginx.conf as i read the manual controls arent implemented...

Is this the case today too or does the manual recording controls working?

**Comment by DanielnetoDotCom** [comment]
No, but the controls will work in a future update

**Comment by morbificagent** [comment]
No problem, the scrumbled Chat Layout is more important to me ;-)
