### ISSUE TITLE
Letting the encoder rip MP3s produces video files with waveform images, but no audio?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4742]
**Describe the bug**
See linked. Files appear to be correct length and have waveform visualizations, but no audio.

**To Reproduce**
1. Go to encoder
2. Add MP3 files
3. Check the output

https://conspyre.tv/video/1611/david-hudson-lecture---ormus
https://conspyre.tv/video/1614/ormus-the-philosopher-s-stone-an-interview-with-barry-carter-23
https://conspyre.tv/video/1616/the-unbelievable-powers-of-monatomic-gold

**Expected behavior**

Expected an audio track.

**Error Logs**
If requested I'll run some more and catch a log.

**Comment by DanielnetoDotCom** [comment]
I can hear the audio from your videos

if you want an MP3 instead of a video, use the direct upload for MP3

**Comment by walt93** [comment]
Nah I like the waveforms but I just double checked and I'm not hallucinating. It's Safari and its fawking dainbread (Version 14.0.3 (16610.4.3.1.7), latest, Mac OS X Big Sur). 

I just checked and it plays in Brave, Opera and Firefox. Should have known it was a bad ...

**Comment by walt93** [comment]
Update: files also fail to play on all browsers on iPhone, iPod, iPad, and presumably if there was a browser on Apple TV it would fail to play audio there as well because Safari is the only browser allowed on the platform. Half the available market can’t play audio from files encoded this way. Please fix or remove this feature it’s rather a LARGE PAIN IN THE (ahem).

**Comment by DanielnetoDotCom** [comment]
Hi, 

Just to make clear, are you saying only Apple dos not play the audio on those files?

**Comment by walt93** [comment]
Yes, this is correct. Seems to be a bug in Safari, or an issue with the tooling producing the videos. On iOS there is only ever going to be one web engine and that is - you guessed it - the one that Apple makes - so when you run "Chrome" etc on iOS you're getting Google skin over Apple browser.

**Comment by walt93** [comment]
Where can I disable this feature so my users don't create these incompatible files?

**Comment by DanielnetoDotCom** [comment]
I am not sure what incompatible file types are you referring to. 

are you always using the encoder?

**Comment by walt93** [comment]
Yes. The issue the encoder renders video files from audio files. Those files do not play audio on Safari. For iOS, WebKit is the only rendering engine allowed on the platform (e.g. Chrome, Firefox etc. are all window dressing on top of Safari). Ergo, these files do not render on iOS.

I would like to disable this feature site wide so my users don't need to be instructed not to use it.

Possible?

**Comment by DanielnetoDotCom** [comment]
Hi, do you mean the spectrum does not play the audio on safari?

**Comment by walt93** [comment]
Yes, that's right.

**Comment by DanielnetoDotCom** [comment]
I just tested here and works for me.

maybe your video source had a bad audio because we are not transcoding the audio
![image](https://user-images.githubusercontent.com/18009293/117351266-e45a3d00-ae83-11eb-9723-a1cd3ed1564c.png)

try to submit another file or change your ffmpeg command to transcode the audio

**Comment by walt93** [comment]
I had not changed the configs from the defaults, will check and re-run some files & let you know the results.
