### ISSUE TITLE
Question About A VPS & the Streaming Server ... 

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4743]
Initially I purchased a yearly server from Daniel that runs Ubuntu 20.4 that does both LiveStreaming and encoding of videos. However, I soon found out that the server I am using can really only accommodate about 10 simultaneous viewers before it starts buffering for everyone. So I am considering all solutions with the priority being on many more people being able to watch a livestream.

Simply using a restreaming service to simulcast on other platforms is cool and all but it is not unusual for Facebook to put me jail for 30 days or Youtube to take me down for a week or two weeks (DLive has been pretty good) ... so I really want to rely less on the major platforms and rely more on my own service.

So I came across this VPS that offers 30Gb of Ram, 8 core CPU, and unlimited bandwidth for $20 a month. 

What I want to know is, if I moved my live-streamed to that server and used another server to do the encoding of videos etc ... would I be able to accommodate more viewers .... if so, approximately how many more?

BTW, I broadcast at 960 x 600 at 30fps 

Thank you in advance for advice and feedback

**Comment by morbificagent** [comment]
I think it for the live-viewing part souldnt be such necessary how many Ram or cpu-power you have.
The bandwith/network-speed would be the most important part of that.

So if you say "unlimited bandwidth for $20 a month" the information of 100Mbit/s or 1Gbit/s Upload-speed is missing.

To do a sample calculation: Streaming with 5Mbit x 15 Viewers = ~75Mbit
If the VPS has only 100Mbit there should be the limit.

If you have 1Gbit Upload there should be ~150 Viewers possible when streaming with 5Mbit

But keep in mind that these VPS with "Unlimited traffic for 20 bucks a month most of the time dont guarantee the specified Upload-rates.
I had some of them in the past (Contabo) and the Upload was vary between 70Mbit and 500Mbit even they were writing "1Gbit/s" on the website.

**Comment by bbyrdhouse** [comment]
Hi,
Thanks for the info ... looks like 600Mbit/s

<img width="269" alt="Screen Shot 2021-03-19 at 5 35 58 AM" src="https://user-images.githubusercontent.com/7376298/111767785-21875300-8875-11eb-9dfd-812f02f2f625.png">

**Comment by morbificagent** [comment]
OK, but as i said this is probably not guaranteed. So if i would have to estimate i would calculate with half of the showed Mbit/s

-> 300Mbit -> ~60 watching users when streaming @ 5Mbit

**Comment by DanielnetoDotCom** [comment]
Hi

I am studying a solution to use a CDN to delivery the live content but they are very strict on the copyright issues.

@bbyrdhouse if you want I probably can get you approved for use. I am pretty sure it will be more efficient than another server .

BTW your server should be able to handle a lot more than 10 user

**Comment by bbyrdhouse** [comment]
I am totally open to ideas about increasing the # of simultaneous viewers, I've just not had good luck with more that 10-12 people watching at the same time, people get frustrated go back to the YouTube stream.

**Comment by titolindj** [comment]
> Hi
> 
> I am studying a solution to use a CDN to delivery the live content but they are very strict on the copyright issues.
>

Woow that would be incredible !!

**Comment by DanielnetoDotCom** [comment]
@bbyrdhouse I just add the CDN for your VOD and live videos, please make some tests and let me know if you fell it is better now

**Comment by DanielnetoDotCom** [comment]
@bbyrdhouse also I noticed you do not have the socket not running, I just enabled it for you. It will help you not overload your server.
