### ISSUE TITLE
Are These Install Instructions For Ubuntu 18.04 Still Goof For Ubuntu 20.04?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4744]
Installing the LiveStreamer on a fresh Ubuntu 20.04 ... will these instructions still work from 18.04?

https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer

**Comment by DanielnetoDotCom** [comment]
Probably you will need to change the PHP version.

**Comment by milehighkaraoke** [comment]
Yes, just reference all php versions in all the configuration files as php 7.4

**Comment by milehighkaraoke** [comment]
It also works on Groovy Gorilla  20.10
