### ISSUE TITLE
Groups are not shown Video details

### ISSUE THREAD

**Issue by fxp66** [WWBN/AVideo#4745]
The previous versions displays the associated groups of the video.
Now there is only a group symbol
![screent-1](https://user-images.githubusercontent.com/40458047/111761868-a9cf1d80-88a0-11eb-82a7-3ae259936b45.jpg)
Is this a bug or a feature or did I miss a configuration?
Thx for quick reply

**Comment by DanielnetoDotCom** [comment]
Thanks, here is a fix

**Comment by fxp66** [comment]
Thanks, it fixed the problem
