### ISSUE TITLE
Search by User

### ISSUE THREAD

**Issue by karlkunc** [WWBN/AVideo#4746]
**Describe the question**
When using the search bar on top, Are we suppose to be able to search for a users name? I know you can go to browse channels and search there but I believe the mobile app doesn't have the browse channel feature. I am not sure that is why I am asking. Thanks.

**Comment by DanielnetoDotCom** [comment]
Hi, the tor search is for videos search only, does not search for usernames or channel name

**Comment by DanielnetoDotCom** [comment]
actually, the search does return the channel name 

First you need to activate it here 

![image](https://user-images.githubusercontent.com/18009293/112003953-1d229a80-8b00-11eb-9944-ee32844ca1fa.png)


then the search may return it

![image](https://user-images.githubusercontent.com/18009293/112004055-362b4b80-8b00-11eb-89d6-3455fbc87efe.png)
