### ISSUE TITLE
Errors using Live Streaming Servers

### ISSUE THREAD

**Issue by friendsincode-offical** [WWBN/AVideo#4747]
**Describe the bug**
When using live servers share and live urls are not correct.
**To Reproduce**
1. Add a Live servers configured correctly.
2. Enable Live Servers
3. Go to live.
4.  Go to share  Player url is not formatted correctly. example https://stream1.somethingelse.com/live/604fed39b74dc.m3u8

**Expected behavior**
I expect the url to be built correctly:
https://stream1.somethingelse.com/live/604fed39b74dc/index.m3u8

I also expect to see the stream that I am streaming not errors saying it can not find
https://stream1.somethingelse.com/live/604fed39b74dc.m3u8 in the console.

**Comment by akhilleusuggo** [comment]
> Go to share Player url is not formatted correctly. example https://stream1.somethingelse.com/live/604fed39b74dc.m3u8

For me your shared url looks wrong .
Are you using server live plugin or directly live plugin ( your main site is it hosted on the same server as rtmp  )?
Share your configuration file here .

**Comment by friendsincode-offical** [comment]
The share url is wrong.

I want the live to be on another server not the same as main site.  With the local live server everything is fine there seems to be something up when you hook it to external live server.

**Comment by friendsincode-offical** [comment]
Also I have a paid server from Avideo that does the exact same thing.  There is a bug in the live servers plugin that does not format the URI's correctly for watching the streams from remote LIVE STANDALONE streaming server.

**Comment by friendsincode-offical** [comment]
The adaptive mode causes this type of uri to be presented.

**Comment by DanielnetoDotCom** [comment]
Hi, I still do not understand what you mean.

what exactly URL do you have and what URL did you expect?

can you share a demo link so I can check?
