### ISSUE TITLE
meeting video quallity

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4748]
My servers have a 1GB connection up and download and the harware are a 6core with 8Gb ram.
So i start a meeting with 3 users and the meeting video quallity is very low. the setting i the meeting is high quallity.
When i check the trafik on the server when the meeting runs he has only 1000kbs.
On the fullscreen is the video very pixel
Why is the quallity so bad ?

**Comment by DanielnetoDotCom** [comment]
I just sent some updates to the meet server, I hope it improves the quality

can you please confirm if makes any difference?

**Comment by 01123581321345589144233** [comment]
it makes no differrence

**Comment by 01123581321345589144233** [comment]
i have setup my own jitsi it works fine, kan i config avideo to use my own jitsi ?

**Comment by trutube-live** [comment]
Having the same issue quality is bad on both servers I have with you.

**Comment by DanielnetoDotCom** [comment]
I just sent a new update, can you please check if makes any difference?

**Comment by trutube-live** [comment]
So the code I see on github was updated yesterday not 10mins ago... Am I missing something?

**Comment by DanielnetoDotCom** [comment]
Hi

I updated the meet server not GitHub

**Comment by trutube-live** [comment]
How does that work with on premise paid hosting?

**Comment by DanielnetoDotCom** [comment]
Hoo, I see, sorry @trutube-live, I will update yours as well.

**Comment by DanielnetoDotCom** [comment]
@trutube-live your servers are up to date, can you please confirm if makes any difference?

**Comment by 01123581321345589144233** [comment]
the quallity is ok
