### ISSUE TITLE
Question: Strategy to integrate authentication

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4749]
**Describe the question**
I want to add some additional services and am exploring how to do that. 

Is it a reasonable strategy to piggyback on AVideo's authentication? I want to add features for users that have paid for subscriptions.

**Comment by DanielnetoDotCom** [comment]
Hi, you can use our API

https://github.com/WWBN/AVideo/wiki/AVideo-Platform-API

Or create a new plugin

https://github.com/WWBN/AVideo/wiki/How-to-code-a-AVideo-Platform-plugin
