### ISSUE TITLE
Warning: unlink(/var/www/AVideo/videos/cache/_jpg

### ISSUE THREAD

**Issue by reuvygroovy** [WWBN/AVideo#4751]
When opening up the home page I get this error on the top of the page:

Warning: unlink(/var/www/AVideo/videos/cache/_jpg_6056f8e8ea9e7.jpg): No such file or directory in /var/www/AVideo/objects/functions.php on line 3006

Every time I refresh the name of the cache .jpg file changes.

**Comment by akhilleusuggo** [comment]
just ignore it , it's a warning .
What this said basically is that some files on the cache have changed , and since it can't find them it will _unlink_ them . Later may create a new cached one .

Just make sure that the image does exist . Also clear the cache to remove confusions .

**Comment by reuvygroovy** [comment]
The image doesn't exit. Also it is annoying since this appears on the home page.
