### ISSUE TITLE
English not available as new site language

### ISSUE THREAD

**Issue by reuvygroovy** [WWBN/AVideo#4753]
When running the installed and selecting the default new-site language, English isn't listed:

![image](https://user-images.githubusercontent.com/1325158/111899626-8b028f80-8a36-11eb-8ab7-61e3469d5c08.png)

**Comment by reuvygroovy** [comment]
Also, the last item ("zh") is missing a flag/icon

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that, here is an update
