### ISSUE TITLE
logincontrol_history directory not exists

### ISSUE THREAD

**Issue by baoang** [WWBN/AVideo#4754]
**Describe the question**
After going to plugin page and clicking *LoginControl (LoginControl)* (now updated to v2.0) **Edit** button, there is no logs, and then switch to AVideo platform's log section at https://my.domain.ltd/i/log, there are some error messages saying

>  [21-Mar-2021 21:49:16 Asia/Shanghai] PHP Warning:  include(): Failed opening 'path/to/my/streamer/site/plugin/LoginControl/View/logincontrol_history/index_body.php' for inclusion (include_path='.:/usr/share/php') in path/to/my/streamer/site/plugin/LoginControl/View/editor.php on line 33

 >[21-Mar-2021 21:49:16 Asia/Shanghai] PHP Warning:  include(path/to/my/streamer/site/plugin/LoginControl/View/logincontrol_history/index_body.php): failed to open stream: No such file or directory in path/to/my/streamer/site/plugin/LoginControl/View/editor.php on line 33

 >[21-Mar-2021 21:49:12 Asia/Shanghai] PHP Warning:  include(): Failed opening 'path/to/my/streamer/site/plugin/LoginControl/View/logincontrol_history/index_body.php' for inclusion (include_path='.:/usr/share/php') in path/to/my/streamer/site/plugin/LoginControl/View/editor.php on line 33

> [21-Mar-2021 21:49:12 Asia/Shanghai] PHP Warning:  include(path/to/my/streamer/site/plugin/LoginControl/View/logincontrol_history/index_body.php): failed to open stream: No such file or directory in path/to/my/streamer/site/plugin/LoginControl/View/editor.php on line 33

I checked the real path inside AVideo dir, ie. plugin/LoginControl/View/, only to find there's *LoginControl/View/Users_login_history* instead of *LoginControl/View/logincontrol_history*. 

Can I manually change the dir name to *logincontrol_history* from *Users_login_history*?

**Screenshots**
no screenshots

Also, there are some red lines to error message, by which I guess they are relevant and they occurred almost the same time when I git pulled the latest version and did the update.

```
 [21-Mar-2021 20:19:54 Asia/Shanghai] myMySQLDatabaseLog::ERROR: [sqlDAL::writeSql] Prepare failed: (1065) Query was empty () SCRIPT_NAME: /objects/pluginRunUpdateScript.json.php

 [21-Mar-2021 20:19:54 Asia/Shanghai] myMySQLDatabaseLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/myMySQLDatabase\/objects\/mysql_dal.php","line":89,"function":"log_error","args":["[sqlDAL::writeSql] Prepare failed: (1065) Query was empty ()"]},{"file":"\/var\/www\/html\/myMySQLDatabase\/plugin\/LoginControl\/LoginControl.php","line":460,"function":"writeSql","class":"sqlDAL","type":"::","args":[""]},{"file":"\/var\/www\/html\/myMySQLDatabase\/plugin\/myMySQLDatabasePlugin.php","line":898,"function":"updateScript","class":"LoginControl","object":{},"type":"->","args":[]},{"file":"\/var\/www\/html\/myMySQLDatabase\/objects\/pluginRunUpdateScript.json.php","line":18,"function":"updatePlugin","class":"myMySQLDatabasePlugin","type":"::","args":["LoginControl"]}] SCRIPT_NAME: /objects/pluginRunUpdateScript.json.php
```

**Comment by baoang** [comment]
an update for this issue.

I switched back to an old ver of 10.2 and saw this problem still exist, so I tried to see if some small adjustment could do the job.

First I turned to `my/streamer/site/plugin/LoginControl/View/editor.php`, in line 33 to change `plugin/LoginControl/View/logincontrol_history/index_body.php` to `plugin/LoginControl/View/Users_login_history/index_body.php` where *Users_login_history* is the real directory. 
Then after refreshing the URL(https://my.streamer.site/plugin/LoginControl/View/editor.php), the site log didn't show the PHP warning messages as before (the above post). However, there is a prompt saying that "DataTables warning: table id=logincontrol_historyTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7". Following the instructions of datatables.net, I pressed F12 and turned on Chrome's developer tool and saw there was another line of error that is related to the path error (plugin/LoginControl/View/logincontrol_history/). Seems that the pather/dir of logingcontrol_history, perhaps as a variable or sth. is set somewhere else. So I had to go back and revert the editor.php to its original and change the dir of *Users_login_history* accordingly, that is, to *logincontrol_history*. 

This time, there is no PHP warning messages, nor prompts/alerts, and more importantly, User Login History page/tab doesn't show blank page, instead, it reflects dozens of pages of login info.

There is still another error at URL https://my.streamer.site/plugin/LoginControl/View/editor.php by pressing F12 in the console section.
> DevTools failed to load SourceMap: Could not load content for https://my.streamer.site/view/css/DataTables/pdfmake.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

HTTP 404 indicates there is no such file, that pdfmake.min.js.map, and I tried to locate that file but failed.

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that.

 I just sent a fix, but to let you know, you should not update the records on this table.

**Comment by baoang** [comment]
> 
> 
> Thanks for notice that.
> 
> I just sent a fix, but to let you know, you should not update the records on this table.

Thank you, @DanielnetoDotCom for the quick fix. I'll keep the loginhistory table intact.
