### ISSUE TITLE
Uploading Videos

### ISSUE THREAD

**Issue by reuvygroovy** [WWBN/AVideo#4755]
I have enabled this option in the settings to allow video uploading:
![image](https://user-images.githubusercontent.com/1325158/111908199-ffeabf00-8a60-11eb-8bd0-068f0a420fbd.png)

But I don't see the button as mentioned in this video: https://tutorials.avideo.com/video/2/upload-a-mp4-file-with-out-encode
![image](https://user-images.githubusercontent.com/1325158/111908229-1d1f8d80-8a61-11eb-9bd3-1aa1a0e2580b.png)

How can I show this button and/or upload a file without encoding?

**Comment by akhilleusuggo** [comment]
this option is not the definitive option .

If you want to allow users to upload mp4 videos ( without encoding ) , then you must enable it from plugin _CustomizeAdvanced_ 

![image](https://user-images.githubusercontent.com/52116577/111908927-c5365600-8a63-11eb-9b22-381f60f15678.png)


Clear the cache to see immediately the result .

**Comment by karlkunc** [comment]
its also located in the admin panel>settings>general settings>upload   toggle off "doNotShowUploadMP4Button" "doNotShowImportMP4Button"

**Comment by reuvygroovy** [comment]
So what's the difference between these two:
admin panel>settings>general settings>upload toggle off "doNotShowUploadMP4Button" "doNotShowImportMP4Button"
and
![Uploading image.png…]()

**Comment by karlkunc** [comment]
Same things, just different locations that you can access them from.

**Comment by akhilleusuggo** [comment]
There's a difference . From admin panel is bugged and deprecated ( Not recommended ) .
