### ISSUE TITLE
Player throws html code on mobile

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4756]
![IMG-20210321-WA0002.jpg](https://user-images.githubusercontent.com/50199132/111910401-81dae800-8a61-11eb-9f68-0332e9b6c747.jpg)

When viewing a video on a small screen device the player sometimes moves out of the screen and some html code is shown...

**Comment by karlkunc** [comment]
I have seen that also. videoresolutionswitcher plugin issue?

**Comment by morbificagent** [comment]
Yes i think so...

**Comment by morbificagent** [comment]
Yes... If i disable the resolution switcher the code doesnt come back.

But i like the switcher (and have payed for it) so @DanielnetoDotCom it would be great if you could take a look at it.

Mobile devices are trending i think ;-)

**Comment by DanielnetoDotCom** [comment]
What device was that??

I just tested it on Android, iOS (chrome and safari) all works fine

![image](https://user-images.githubusercontent.com/18009293/112009849-89ec6380-8b05-11eb-9f77-db0c9d2dbd1b.png)

**Comment by morbificagent** [comment]
Hi Daniel,

have tested it on two devices. 

Sony XZ3 Android 9 in Chrome Browser v 89.0.4389 (actual version from Appstore)
Samsung Note 20, Android 11 in Chrome Browser v 89.0.4389 (actual version from Appstore)

Sometimes it works but every ~second time the html-code is shown. It can be forced when changing between horizontal and vertical layout.

**Comment by morbificagent** [comment]
https://video.bit-link.de/video/105/test-stream-on-20-mar-21-18-58-02?channelName=SmkyPlayZ

![Screenshot_20210322-164523_Chrome.jpg](https://user-images.githubusercontent.com/50199132/112017906-5a058600-8b2e-11eb-8cfb-190cb1732b3f.jpg)

**Comment by DanielnetoDotCom** [comment]
I see, so it maybe is regarding some JS error?

so it only happens sometimes?

**Comment by morbificagent** [comment]
Yes it only happens sometimes... In my case ~every third video play.

And only when the resolution switch plugin is active.

And the 720 displayed here seems to be my selected default resolution.

**Comment by morbificagent** [comment]
Played on the touch screen to get more of the message:

![Screenshot_20210322-200256_Firefox.jpg](https://user-images.githubusercontent.com/50199132/112044344-02751380-8b4a-11eb-945b-869e4a55d40c.jpg)

**Comment by morbificagent** [comment]
More information:

![image](https://user-images.githubusercontent.com/50199132/112057217-4ae7fd80-8b59-11eb-90ca-7374722306f8.png)

**Comment by DanielnetoDotCom** [comment]
can you please share a link so I can try to reproduce this error?

**Comment by morbificagent** [comment]
@DanielnetoDotCom i did so a few comments ago:

https://video.bit-link.de/video/105/test-stream-on-20-mar-21-18-58-02?channelName=SmkyPlayZ

And doesnt show the last screenshot the exact place with the code?

**Comment by morbificagent** [comment]
OK, eventually this helps:

It could be that is it a timeout-problem insight of the plugin.

I noticed that it mostly happened if my server took relatively long to load the video-file.
As i said somewhere in the past the videos are on very slow storage here and sometimes it needs some seconds to get the file.

Anyway.

But i noticed the combination of a long loading time and the happening of this case here.

After the file is loaded it is cached by my server for a time on fast storage and this would explain why this problem is showing up only sometimes.

@DanielnetoDotCom is there any timer in the script of the resolution-switcher-plugin which could expire while generating the resolution-gui-elements?

**Comment by DanielnetoDotCom** [comment]
This executes at the end, when the script is ready

**Comment by morbificagent** [comment]
Any idea how to resolve this?

I would love to use the resolution switcher I have payed for but I can't enable it it throws this code on mobile devices often.

**Comment by DanielnetoDotCom** [comment]
The problem is, I cannot reproduce it.

I also tested in multiple mobile devices and it works

**Comment by DanielnetoDotCom** [comment]
Also just tested on iPhone Chrome and Safari

![64E054A6-507B-48C3-A811-02CEFB524D73](https://user-images.githubusercontent.com/18009293/112472917-741caf80-8d4c-11eb-92c9-2293dc5fca3b.PNG)
![D35E4DC2-1F46-415F-AF88-6F00FE23AE89](https://user-images.githubusercontent.com/18009293/112472923-754ddc80-8d4c-11eb-9d9d-2b52d97a4834.PNG)

**Comment by morbificagent** [comment]
hm.... these problems which arent there "every time" are great :-(

OK, i hope that i can produce a reproduceable situation... even if im not knowing how at the moment.
But the problem is sometimes there as you can see.

And not only in my mobile. My friends have said to me yesterday: "hey look at this, there is a bug" and they are showing me exacly this!

Would it be possible to get a version from the plugin without this "label-danger"-part i have screenshoted here: https://github.com/WWBN/AVideo/issues/4756#issuecomment-804388161

So i could test it?

**Comment by DanielnetoDotCom** [comment]
I saw the screenshot, it seems to me a JS error.
I need to be able to reproduce it, make any change now is use less

**Comment by morbificagent** [comment]
OK, seams like I solved it by changing two timeout values in script.js of the plugin from 1000 to 10000...:

![](https://i.imgur.com/5brJ9VX.jpg)

**Comment by morbificagent** [comment]
Will test it a few more days but looks god for now

**Comment by morbificagent** [comment]
OK, was trying a little bit and found a "solution" by commenting out the part in code which drops this codefragment inside of my player... Didn't found the cause of it and I'm not sure if I am breaking something other with this but for the moment it helps for me:

![](https://i.imgur.com/XYriNH7.jpg)

In the situation where my error is there the controls of the player are getting a black background instead of transparent and doesn't fade out automatically like they should. This isn't solved by my change. But as the code fragment isn't shown anymore its usable now.

**Comment by morbificagent** [comment]
Because i had problems with it even with my changes i decided to disable the changeresolution plugin and:

![Screenshot_20210408-233727_Chrome.jpg](https://user-images.githubusercontent.com/50199132/114100103-1a77c180-98c4-11eb-805f-6546453f45c9.jpg)

The problem is still there... So it looks like the problem isnt the plugin as i thought.

Will try to find out whats going on there. Ideas are welcome!

**Comment by morbificagent** [comment]
Workaround for me:

Using the HLS plugin.
As i mentioned i think the loadingtime of the mp4 videos is part of the problem.
So i had the problem much more often on long Videos of several hours.

Because of the faster loading time by using the small HLS fragments the problem isnt there anymore.

HLS is much nicer in general so im ok with this.
