### ISSUE TITLE
LiveLinks plugin and user rights problem

### ISSUE THREAD

**Issue by peterflitz** [WWBN/AVideo#4757]
if a user has the rights to post LiveLinks, this user can edit and delete all LiveLinks from all other users.

In the plugin you can set the permission for LiveLinks "only admin".

This means that the LiveLinks plugin cannot be used by members.
Is it possible to also make the plugin available to members?
The member is then actually only allowed to edit and delete his own LiveLinks.

**Comment by DanielnetoDotCom** [comment]
You are right,  thanks for that

**Comment by DanielnetoDotCom** [comment]
For now, the user can only see his own links, in the future we may add permission for specific users only

**Comment by peterflitz** [comment]
great !
thank you very much daniel
