### ISSUE TITLE
Matomo Tracking Code

### ISSUE THREAD

**Issue by reuvygroovy** [WWBN/AVideo#4758]
Is there a way to append Matomo Tracking code into the header of the site? I can't copy/paste in the Site Settings -> Script Code section, only type manually.

**Comment by akhilleusuggo** [comment]
What do you mean ? I'm using matomo and no problems . 

siteConfigurations | Script code | Copy/Past

Maybe you're having an issue with your browser .

**Comment by reuvygroovy** [comment]
Thanks!
