### ISSUE TITLE
Live-Stream with HLS but SendRecordedToEncoder as mp4

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4760]
Hi together,

i have changed my live-configuration yesterday to use the adaptive HLS via live-streams.

Now the plugin "SendRecordedToEncoder" sends the files to the encoder and produces HLS too. But i want that mp4 files are falling out of the recorded livestream...

Is this possible?

**Comment by DanielnetoDotCom** [comment]
Sorry, it is not clear?

Do you want to save your live streams in MP4?

**Comment by morbificagent** [comment]
Yes right,

Before i changed the nginx and live-plugin config (like written in your wiki) for using hls adaptive the SendRecordedToEncoder plugin created mp4 files... 

Now it creates hls files which arent such nice to work with in post.

So i would love to change my config to use the adaptive hls for the live streams like it does now but the recorded files should be converted to mp4 automatically like it was before.

**Comment by morbificagent** [comment]
Not sure where the decision is made which format is outputed from the encoder when using the SendRecordedToEncoder plugin... Nginx recorder config?
Somewhere in the pluginconfig?
Not possible?

Hmmmmm

**Comment by DanielnetoDotCom** [comment]
> Before i changed the nginx and live-plugin config (like written in your wiki) for using hls adaptive the SendRecordedToEncoder plugin created mp4 files...
> 
> Now it creates hls files which arent such nice to work with in post.
> 
> So i would love to change my config to use the adaptive hls for the live streams like it does now but the recorded files should be converted to mp4 automatically like it was before.

Sorry I am not sure if it ever was like that 

it uses the default format in your streamer, and it converts to HLS only if you have the HLS plugin enabled if you do not have or it is not enabled it will convert to MP4

**Comment by morbificagent** [comment]
Do i need the hls plugin enabled to use HLS for live-streaming or is it only for playing the static files?

**Comment by DanielnetoDotCom** [comment]
No, you do not need it, the HLS is only for VOD videos.

Live videos are HLS by default. not sure but I guess the HLS plugin provide you a resolution switcher on adaptive livestreams

**Comment by morbificagent** [comment]
Thanks for that info,

now i know that i buyed the HLS Plugin without need ;-)

OK, some money for you to have more fun in developing this :-)

**Comment by akhilleusuggo** [comment]
@morbificagent HLS is only for 

- adaptive live-streaming ( with live-transcoded into 3 qualities )
- encode videos on HLS format ( with automatic quality selector )
