### ISSUE TITLE
Unable to Perform Livestream (NGINX Will Not Start ... Error)

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4761]
After the last round of updates that I did I've not bee able to do any live-streaming. The NGINX service is unable to start and I m stuck at finding how to start it.

`systemctl restart nginx` doesn't work
and 
`systemctl status nginx` produces the following:

```
 nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: timeout) since Mon 2021-03-22 06:03:38 CDT; 54s ago
       Docs: man:nginx(8)
    Process: 1230 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, sta>
    Process: 1231 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUC>
      Tasks: 0 (limit: 19055)
     Memory: 3.1M
     CGroup: /system.slice/nginx.service
```
This is the same ticket as #4737 but I think that post got lost in the shuffle

**Error Logs**
I am not sure of the location of the error logs on this server otherwise I would produce them here.

**Comment by akhilleusuggo** [comment]
To start : `sudo /usr/local/nginx/sbin/nginx`
To stop : `sudo /usr/local/nginx/sbin/nginx -s stop`

To reload ( Works ONLY if nginx already started ) : `sudo /usr/local/nginx/sbin/nginx -s stop && sudo /usr/local/nginx/sbin/nginx`

If you get error saying that `blind :IP failed ` means NGINX is already running ( you need to stop and start again )

**Comment by bbyrdhouse** [comment]
? .... I do live-streaming on 2 other servers that do not use AVideo and NGINX is required on both of them ... I assumed that NGINX was used on AVIdeo as well ...

**Comment by akhilleusuggo** [comment]
what is required is rtmp-nginx module , not nginx web-server .
But keep it , if you consider it required for other things . Maybe was installed by the guide of @DanielnetoDotCom to generate ssl certificate , not how I do it . You can generate it with `certonly` , without any web-server .

**Comment by SirFiChi** [comment]
I have also problems with the LiveStream... #4613 

For your NGINX Problem:
Can you start it and when it failes execute "journalctl -xe" directly.
You should see the failure there...

**Comment by akhilleusuggo** [comment]
@SirFiChi this has nothing to do with live-stream . Nginx does not live-stream . Fail or not , this is not part of the rtmp .

**Comment by bbyrdhouse** [comment]
@akhilleusuggo -in my nginx.conf file I have all my rtmp streaming directions so forgive me if I referred to it as nginx ... I suppose that its a common mistake.
