### ISSUE TITLE
head

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4762]
What file does affect the global head of the website ? https://github.com/WWBN/AVideo/blob/master/view/include/head.php ?
I want to add a custom html/css on the top of the navigation bar ( appearing on all pages )

**Comment by DanielnetoDotCom** [comment]
try this https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css
![image](https://user-images.githubusercontent.com/18009293/112020724-59a9c280-8b0f-11eb-8cdd-b4fddb9c337f.png)

or maybe this 

![image](https://user-images.githubusercontent.com/18009293/112020594-3c74f400-8b0f-11eb-913c-eea77ddc80e1.png)

**Comment by akhilleusuggo** [comment]
Yes I've thought about it , I don't don't see where the css goes , and I don't wanna break the site .

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom The header appears under the navigation bar . Anyway to make it on the top of the nav.bar ?

**Comment by DanielnetoDotCom** [comment]
If you use the head code it will be included in the <head> tag

![image](https://user-images.githubusercontent.com/18009293/112196963-50d9ef00-8bea-11eb-9d41-8d0623737e0e.png)
