### ISSUE TITLE
Live (HLS) doesnt play on mobile Chrome (Android)

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4763]
As i have buyed and configured the HLS plugin  i am trying to use it with a live-stream...

On a desktop-browser everything works good (Chrome/Firefox tested) but on my mobile Chrome (Android) the stream plays only 2sec and than stops:

https://video.bit-link.de/live/0/Admin/101643

Any ideas? HLS should be compatible with mobile Chrome too, or not?

**Comment by akhilleusuggo** [comment]
Does work , no issue on my phone ( android v9 ) .

**Comment by morbificagent** [comment]
What? stange... ok, i will get more users to test it...

**Comment by morbificagent** [comment]
OK, tested it on other devices and on most of them are playing it

Sony, Chome, Android 10 = OK
Samsung Chrome, Android 10 = OK
Samsung Chrome, Android 11= not Playing
iPhone (model not clear) = OK

So eventually a problem with Android 11... will try to find someone with 11 too... anyone here who could try it?

**Comment by morbificagent** [comment]
Nobody with Android 11 here?

If not i think i have to accept that my mobile cant play the stream at the moment... eventually a bug in Android 11 or i did something with my device which results in this.

Waiting a day if someone can test it and will close this then.

**Comment by DanielnetoDotCom** [comment]
Android emulator with android 11
![image](https://user-images.githubusercontent.com/18009293/112195904-3e12ea80-8be9-11eb-9727-721edf4845c0.png)
![image](https://user-images.githubusercontent.com/18009293/112196190-8d591b00-8be9-11eb-8fc5-b0bb57bbdb24.png)

**Comment by morbificagent** [comment]
Ok, eventually it is my device only

**Comment by morbificagent** [comment]
As I was not able to get my hls live streams running on my android mobile I was searching for a solution yesterday.

I found out that the problem happens when the player tries to switch the layer to another bitrate in hls.

And I found out that on some devices there is a native hls implementation which could cause problems.
So it looks like everywhere it is recommended to use these three lines in the player hls config to prevent this:

    nativeAudioTracks: false,
    nativeVideoTracks: false,

overrideNative: true

I would like to test this but don't know where to put this in the avideo files... There are several files with player configs and I'm not very good in Php,html,js....

Has someone an idea where to put this options for testing them with my live hls stream ?

Many thanks

**Comment by milehighkaraoke** [comment]
I believe this would go in the nginx config under HLS

**Comment by morbificagent** [comment]
@milehighkaraoke 

i dont think so because it looks like it is an video.js setting.

Here a snippet from another site which explains it:

> The solution is to tell the player to use the Media Source Extensions (if the platform supports it) for HLS playback instead of playing it natively. You can do this with VideoJS by setting the overrideNative property to true. If you view the source for this page, you’ll see this:

> videojs.options.hls.overrideNative = true;
> videojs.options.html5.nativeAudioTracks = false;
> videojs.options.html5.nativeTextTracks = false;

> var player = videojs('example-video');
> player.src('https://s3.eu-west-2.amazonaws.com/net.hlsbook/prog_index.m3u8');

**Comment by DanielnetoDotCom** [comment]
Hi, @morbificagent we already use that, check this ...
https://demo.avideo.com/plugin/VideoHLS/downloadProtection.js

What made me wonder, are you using the download protection option?
if you disable it makes any difference?

**Comment by morbificagent** [comment]
@DanielnetoDotCom no i didnt use the downloadprotection and as i didnt needed the hls plugin for live streaming in hls i disabled it.

So i am wondering now too because i dont understand what this lines are for in the download protection as they are hls "compatipility" options i think and should be used for the normal player...

**Comment by DanielnetoDotCom** [comment]
I see the problem is on the live stream only. not the HLS VOD videos.

question, can you play HLS VOD videos from demo site?

**Comment by morbificagent** [comment]
Have tested it and yes I can. But the procedure of playing is another here I think.

Its a little bit problematic to debug on the smartphone but it looks like the VOD HLS files on your demo site are starting in "HD" and keeping this layer because the bandwidth is OK for that.
So there is no "layer switch" which is the point where my problem happens.

In my "live-hls-problem-case" the starting resolution is the lowest quality and after a few seconds it tries to switch the layer upwards. That's the point of breaking
