### ISSUE TITLE
Restream Feature Does Not Work (or I haven't been able to get it to work)

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4764]
I'd like to Restream my livestream to a couple of destinations but so far have not been successful in getting it to work.

I know for a fact that all three of these destinations work because I can stream directly to them using OBS, ecammLive, and any other software I use.

but they are not being pushed from my AVideo server ... what could I be doing wrong, or what steps have I failed to take?
Is there another setting somewhere that I have to turn on or something?

<img width="496" alt="restyream2" src="https://user-images.githubusercontent.com/7376298/112004329-ad0c1880-8aef-11eb-83b8-6515fa503d47.png">

**Comment by akhilleusuggo** [comment]
tprshow is your site ? Or is the site where you gonna be restreaming ?

**Comment by bbyrdhouse** [comment]
tprshow is a ramp server that I can broadcast to directly if I want (I mean straight out of OBS) and I can also view the stream there ... 

The ramp stream works, no problem when streaming to it from OBS ... or even if I send a stream to it from a service like Restream.io or Castr.io ... 

I would like to save the $19 a month I pay Restream.io and simply use my AVideo site to stream out to the other destinations.

Currently I do the following:

1. I stream out from my computer to Restream.io
2. Restream.io send the stream to (my AVideo site, Youtube, Facebook, Live, Vaugh, VK, and Periscope)
3. I want to cut out Restream,io and replace them with my AVIdeo site and stream directly to it and then send the stream to those other places ... or perhaps to a free their of Restream.io ... 

Problem is that I can not get the AVideo site to push the stream anywhere.

**Comment by DanielnetoDotCom** [comment]
check your logs usually, there is a file specific for the restream 

Search for this in your log

`Restreamer.json.php startRestream, check the file (/path/to/logFile) for the log`

**Comment by bbyrdhouse** [comment]
Where does AVideo store the log files please?
What directory can I expect to find the Restreamer.json.php file?

**Comment by bbyrdhouse** [comment]
This is all I could find ... 
` [22-Mar-2021 14:55:32 America/Chicago] AVideoLog::ERROR: sendSocketMessage  SCRIPT_NAME: path/to/my/streamer/site/plugin/Live/on_publish_socket_notification.php`

**Comment by bbyrdhouse** [comment]
Also this ... 

` [22-Mar-2021 10:00:01 America/Chicago] AVideoLog::ERROR: Could not connect: Connection to www.mysite.com:2053 failed: Last error for IPv4: Connection to tcp://192.99.2.39:2053?hostname=www.mysite.com failed: Connection refused. Previous error for IPv6: DNS query for www.mysite.com did not return a valid answer (NOERROR / NODATA) wss://www.mysite.com:2053?webSocketToken=YWJNV2hzS3poRVF5QTV5WFI0SmNzckZUOU9MZXNPTHNxeUNmVmNCbTlod05XbG5XVThJUVNQK2JWSDdNL25qYXNIcjZTTXBRbUhMUDh3b1dodnRka0x6cG13WC9WczI3Q0x0cGVybklCaGkvc2dnT2pwdElkODlNYXRWandCTiszbkZuU1cvMUlLc2g5bDBMdW1TRUZYQldtbWZWSjcvZlArQlEyS3RXZW5YbFR4cXdOUDVsQmtIVjI3dXZhODc2WVVWUm1pc2hVUGpMWjIrOU5COUdBL1dZM3U3UWhiQUJhbEhGeUlkRU1iMXNVNFpzWUltNDkzMkg1WlFITGg0NUd6MjVUWkx6RW95dFVTa3lhNmVLVTMwZkdWVzNZZUg2dm1UeVVETlRDaU5Id2FPajVvZTh0Z2dJcTRwYzBSZEx2dGpRVWdZU2xKYzhCRTJ0WWxxeExKKzBtQzdCbHdTNklseWxQT2FSYlJIbjBtRnZ2d3BiT3NST1RscFVtK0hvV2lYNDhIZnJTOC9SR1lacU5XWGVOL3plNk81Q2hKT25YU1V4Yi94eW1TdDFWSWdOcmx1RDdBTEFnZWkxZHp0QjhyYWZvU0hKMk14cjF2a3puYzhaYmZEQ0NYcmNob0JvNzBJYURBb3hpalhvRnlmZkZTV1huRHNUUlRCbUQxU0Z2ZURScTZtMG5aTFVxeXB0MHg0bnNMd2wxRFJ0RFMzY050ZnoraEZpbVBaTnFPejdFeXhPblVwckVkc2FWeVNOeVV4ZldBS2ZjamsyZTdidEdXMmpid1lsU3ZQdHlwZW5wZ1pjYlBadmxNTFpYaWdicnNDM1ZVQ3hXK0s3ajBNb003c0pFaGx3ZUZDTmx4NklsUjNzdjNVZklnN2RRUGZiQ2l2b2JPUGxUUUxDU3Jka3pkUEUrRUlOUVh6UFRNMVJzdWt3OTJmSTEzdDJWWTBjTDVzeDFlOERuSHJJVlZJU3F2ZkQ4RHY3UjN0RThjMGpTSHFubWZ2ekFIenpYN24zd2JOMzYzWGU4UFFJSlJDMUhxLzN6dytuNnU5TFkyS25nUEkxNDZRTVpqRT0=&isCommandLine=1 SCRIPT_NAME: /plugin/Chat2/sendMessage.json.php`

**Comment by titolindj** [comment]
Looks to my that you need to change "mysite.com" to whatever your domain is...

**Comment by bbyrdhouse** [comment]
This is not something done via the GUI, I suppose?

There needs to be some instructions somewhere that tell us what file needs to be edited being left to guess is taxing.
<img width="491" alt="restream" src="https://user-images.githubusercontent.com/7376298/112122902-b9937e00-8b8e-11eb-9848-38a945addbae.png">

**Comment by DanielnetoDotCom** [comment]
In your log search for the word "Restreamer.json.php"

you may find the information related to the restream

I made a search in your logs

```
[23-Mar-2021 10:00:39 America/Chicago] Restreamer.json.php php://input {"m3u8":"https:\/\/***.***.***\/live\/60535fda5a4e1-091243.m3u8","restreamerURL":"https:\/\/***.***\/plugin\/Live\/standAloneFiles\/restreamer.json.php","restreamsDestinations":["rtmp:\/\/live.newtube.app:1935\/live\/\/PatriotReload?key=***Qs6mZzicYfRBl","rtmp:\/\/live.tora3.com\/***cMzCZ1e\/***7c1719a54e","rtmp:\/\/tprshow.com\/live\/stream"],"token":"***VXl3dGJZR3FxeDJkZzBBY2VCQTV6cmRrZDR2bXJTWkFqemswV09iV1d5TVFOMWN1bXM1UVhqUmwzcmJCNDI1TjRWU3c9PQ==","users_id":1}
[23-Mar-2021 10:00:39 America/Chicago] Restreamer.json.php Found 3 destinations: ["rtmp:\/\/live.newtube.app:1935\/live\/\/PatriotReload?key=***Qs6mZzicYfRBl","rtmp:\/\/live.tora3.com\/***cMzCZ1e\/***7c1719a54e","rtmp:\/\/tprshow.com\/live\/stream"]
[23-Mar-2021 10:00:39 America/Chicago] Restreamer.json.php verifying token https://***.***/plugin/Live/verifyToken.json.php?token=***VXl3dGJZR3FxeDJkZzBBY2VCQTV6cmRrZDR2bXJTWkFqemswV09iV1d5TVFOMWN1bXM1UVhqUmwzcmJCNDI1TjRWU3c9PQ==
[23-Mar-2021 10:00:39 America/Chicago] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/plugin/Live/verifyToken.json.php?token=*****Xl3dGJZR3FxeDJkZzBBY2VCQTV6cmRrZDR2bXJTWkFqemswV09iV1d5TVFOMWN1bXM1UVhqUmwzcmJCNDI1TjRWU3c9PQ==) FROM: **** Browser:  SCRIPT_NAME: /plugin/Live/verifyToken.json.php
[23-Mar-2021 10:00:39 America/Chicago] AVideoLog::DEBUG: Bot stopped SCRIPT_NAME: /plugin/Live/verifyToken.json.php
[23-Mar-2021 10:00:39 America/Chicago] Restreamer.json.php verification respond content
[23-Mar-2021 10:00:39 America/Chicago] Restreamer.json.php ERROR Could not verify token (https://***.***/plugin/Live/verifyToken.json.php?token=***VXl3dGJZR3FxeDJkZzBBY2VCQTV6cmRrZDR2bXJTWkFqemswV09iV1d5TVFOMWN1bXM1UVhqUmwzcmJCNDI1TjRWU3c9PQ==)

```

So the problem was that `Bot stopped SCRIPT_NAME: /plugin/Live/verifyToken.json.php`

Your cache plugin is probably stopping bots, I will send an update to whitelist the verifyToken.json.php, so it should work even with the block bots option

**Comment by bbyrdhouse** [comment]
@DanielnetoDotCom - Is this a feature that was not included in the initial setup of the server? If so, its ok, I just need to know where the instructions are.

I think with some of the replies I get for help they are based on the assumption that I did the install myself and either forgot or didn't set something up properly. But on my end, I didn't do any of the setup and have only been working with the front-facing options. 
So when someone says to "you need to change xyz in your abc file, I am stuck because I am looking at the front-end and they are referencing the backend.

I can do these things, but my unfamiliarity with the codebase that makes up the script makes have to ask the same question a bunch of different way and then piece together the answers so that I can hopefully sort things out.

So, when you say "search the log for "Restreamer.json.php" ... I go to the log page but I do not see a search function .... this is what I see.

<img width="1373" alt="Screen Shot 2021-03-23 at 3 04 13 PM" src="https://user-images.githubusercontent.com/7376298/112210814-2a678400-8be9-11eb-92c0-0b338328b1f9.png">

**Comment by DanielnetoDotCom** [comment]
Done your site is up to date.

feel free to try the restream again.

**Comment by bbyrdhouse** [comment]
@titolindj - "mysite.com" is found in the log.php file here `/AVideo/view/log.php`
on lines 278-282
```
<?php
                $outputText = str_replace(array(parse_url($global['webSiteRootURL'], PHP_URL_HOST), $global['systemRootPath'], $global['salt'], $mysqlPass, $mysqlUser, $mysqlHost, $mysqlDatabase), array("www.mysite.com", "path/to/my/streamer/site/", "mySalt", "myMySQLPass", "myMySQLUser", "myMySQLHost", "myMySQLDatabase"), $outputText);

                echo $outputText;
                ?>
```

Are you saying that I need to change that to the url of my site?

**Comment by DanielnetoDotCom** [comment]
@bbyrdhouse I am not sure what you are looking for, you should not change those files.

you are all set, please try to restream and let me know if works

**Comment by bbyrdhouse** [comment]
@DanielnetoDotCom - thank you for clearing out the errors. I would have had to ask a bazillion questions to clear those out. I am sure everyone else is grateful too :)

I just tried the restreaming feature but now I can't get the live-streaming to work.
I see the notice that there is a live stream but when I try to view the livestream it just sort of spins ...

**Comment by DanielnetoDotCom** [comment]
FYI

Your restream logs are here /var/www/tmp/ffmpeg_*

I used this command line in your terminal

`tail -n 9999 /var/www/html/AVideo/videos/avideo.log | grep -i 'Restreamer.json.php startRestream, check the file'`

this command return this:


```
[23-Mar-2021 15:33:17 America/Chicago] Restreamer.json.php startRestream, check the file (/var/www/tmp/ffmpeg_1_2021-03-23-03-33-14.log) for the log
[23-Mar-2021 15:39:37 America/Chicago] Restreamer.json.php startRestream, check the file (/var/www/tmp/ffmpeg_1_2021-03-23-03-39-34.log) for the log
```

Those are the files I need to check what is going on with your restream

I have checked this one /var/www/tmp/ffmpeg_1_2021-03-23-03-33-14.log

```
[tcp @ 0x5620dc6b7bc0] Connection to tcp://live.newtube.app:1935 failed: Connection refused
[rtmp @ 0x5620dc6c8480] Cannot open connection tcp://live.newtube.app:1935
rtmp://live.newtube.app:1935/live//PatriotReload?key=***kDlQs6mZzicYfRBl: Connection refused
```

**Comment by bbyrdhouse** [comment]
I see that it is recording me fine but I can't actually see the stream as it is live ... all I see is this
<img width="1063" alt="Screen Shot 2021-03-23 at 3 42 04 PM" src="https://user-images.githubusercontent.com/7376298/112215553-7e289c00-8bee-11eb-99fe-4e8690c7381a.png">

**Comment by DanielnetoDotCom** [comment]
> I see that it is recording me fine but I can't actually see the stream as it is live ... all I see is this

Checking

**Comment by DanielnetoDotCom** [comment]
Can you please stay online? or do you allow me to go online on your site?

**Comment by bbyrdhouse** [comment]
you can do what you need ...

**Comment by bbyrdhouse** [comment]
I see your stream

**Comment by DanielnetoDotCom** [comment]
Please try again, I guess we just miss a clear cache

**Comment by bbyrdhouse** [comment]
k

**Comment by bbyrdhouse** [comment]
I am live streaming now but the site says there is no live streaming now ...

**Comment by DanielnetoDotCom** [comment]
Hold on ...

**Comment by DanielnetoDotCom** [comment]
Got it, you had a missing on_publish_done

It is fixed now, I had to restart your nginx server

**Comment by DanielnetoDotCom** [comment]
Hold on, do not stop the stream, I got something else

**Comment by bbyrdhouse** [comment]
ok ...

**Comment by bbyrdhouse** [comment]
The restreamer is sending out the proper signal but the main site still just has the poster image

**Comment by DanielnetoDotCom** [comment]
Please stop and start again the stream and check the restreamer

**Comment by bbyrdhouse** [comment]
ok

**Comment by DanielnetoDotCom** [comment]
It is working on your site, but I got something to your restream
hold on please

**Comment by bbyrdhouse** [comment]
k

**Comment by bbyrdhouse** [comment]
I got disconnected ...

**Comment by DanielnetoDotCom** [comment]
can you please restart your stream once more?

**Comment by bbyrdhouse** [comment]
yes

**Comment by bbyrdhouse** [comment]
Now it is failing to connect to the server ...

**Comment by DanielnetoDotCom** [comment]
checking

**Comment by DanielnetoDotCom** [comment]
please try again

**Comment by bbyrdhouse** [comment]
k

**Comment by DanielnetoDotCom** [comment]
Seems to me your live and restreamer is working

**Comment by bbyrdhouse** [comment]
Restreamer is not working

**Comment by DanielnetoDotCom** [comment]
you do have something in progress to rtmp://tprshow.com/live/stream

**Comment by DanielnetoDotCom** [comment]
But there are no keys or credentials there, maybe is going nowhere and it is lost

**Comment by bbyrdhouse** [comment]
its about 5 minutes behind and it is part of the previous stream from 15-20 minutes ago

**Comment by DanielnetoDotCom** [comment]
I mean, I can see in your server you are restreaming this key 60535fda5a4e1

**Comment by bbyrdhouse** [comment]
Yeah ... but is not in synch or something. way behind. plus the restreamer wasn't getting a signal. It did for about 30 seconds or so then stopped.

**Comment by bbyrdhouse** [comment]
The site says I am live-streaming right now but I stopped streaming about 5 minutes ago

**Comment by DanielnetoDotCom** [comment]
On my side, you are not live
but does the restream work?
can you try again?

**Comment by bbyrdhouse** [comment]
Sorry about the delay ... Just started a new stream and it is working on the main site and looks like it is working but the restream starts for a few seconds and then it stops.

**Comment by bbyrdhouse** [comment]
I know you have spent a lot of time on this and it is not a critical feature today, but I would like to use it in the coming weeks.

**Comment by DanielnetoDotCom** [comment]
For me seems to be working, try to reset your live keys and try again.

**Comment by bbyrdhouse** [comment]
ok

**Comment by bbyrdhouse** [comment]
No, the restreamer is not working

**Comment by DanielnetoDotCom** [comment]
Please try again

**Comment by bbyrdhouse** [comment]
turn the stream off and on?

**Comment by bbyrdhouse** [comment]
No ... it starts and runs for about 10-12 seconds and then stops.

**Comment by DanielnetoDotCom** [comment]
In your log files seems to be running

**Comment by bbyrdhouse** [comment]
every destination I try gets the stream for about 10 seconds and then no more data comes through

**Comment by DanielnetoDotCom** [comment]
Are you saying it starts to restream than stops?

**Comment by bbyrdhouse** [comment]
Yes it starts and then stops about 10 seconds in.

This issue has not been resolved and still persists. I just attempted to use the re-streaming feature and it simply will not work.

**Comment by DanielnetoDotCom** [comment]
I am sending some updates that may help with this, but just to warn you, the restream is an experimental feature, it is not well tested yet.
