### ISSUE TITLE
Live Stream Shows on Home Page Even When Not Live

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4766]
**Describe the bug**
When I close a livestream, it still shows up on the front page even though in the parameters I have told it to not show up.

<img width="447" alt="new2" src="https://user-images.githubusercontent.com/7376298/112051469-f96f4c80-8b1f-11eb-9d33-d7180456e18c.png">

<img width="506" alt="live" src="https://user-images.githubusercontent.com/7376298/112051507-01c78780-8b20-11eb-8a42-b2140d2f3518.png">

**Comment by akhilleusuggo** [comment]
it's a cache issue I believe .
Have you tried to clear the cache after the stream has ended ?

**Comment by milehighkaraoke** [comment]
It is a configuration issue.Please check that you have on publish stop in your NGINX Configuration

**Comment by bbyrdhouse** [comment]
@milehighkaraoke - where is this setting? 
This is a new issue that started on its on and not the result of something I did. It began doing this immediately after the lat update.

@akhilleusuggo - I don't think its a cache issue ... I clear the cache quite often ... sometimes 10-12 times a day

**Comment by milehighkaraoke** [comment]
Post your NGINX configuration. This same thing happened to me after last git pull. It's going all web socket and that requires more configuration

**Comment by DanielnetoDotCom** [comment]
I just sent some updates that may resolve some issues related to online/offline notification

**Comment by milehighkaraoke** [comment]
Git pull fixed it  up.
