### ISSUE TITLE
What Is This, Why Is Showing Up, And How Do I Remove It?

### ISSUE THREAD

**Issue by bbyrdhouse** [WWBN/AVideo#4767]
Today, a floating sort of stats modal started showing up when I log in.

I have never seen this before. I did turn anything on ... all I did was update the Chat2 plugin and the PayPerViewLive plugins and do a git pull this morning.

How do I get rid of it, it is distracting.

<img width="298" alt="new" src="https://user-images.githubusercontent.com/7376298/112051900-76022b00-8b20-11eb-96f0-3b7b2ee7f478.png">

**Comment by morbificagent** [comment]
Its the debugger from the YPTSocket-Plugin.
You can/should uncheck these boxes if you whant it to go away...

But the good news: The debugger says everything is fine ;-)

![image](https://user-images.githubusercontent.com/50199132/112059183-d06cad00-8b5b-11eb-9a17-9108ca437b7d.png)

**Comment by bbyrdhouse** [comment]
I am noticing more and more things being "turned on" or "turned off" after the last update that I have never purposefully turned on.

I'd be willing to say that I have never even opened that plugin ... 

Thanks for the info

**Comment by DanielnetoDotCom** [comment]
@bbyrdhouse sorry but I did that for you, [on the other issue I told you](https://github.com/WWBN/AVideo/issues/4743) I updated your server regarding let you handle more simultaneous user,
