### ISSUE TITLE
WEB Socket Not seeing correct Certificate  

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#4768]
I am lost with this one Dan any help on this one would be greatly appreciated as i do not think my soket is full functional like this. 

wss://127.0.0.1:2053?webSocketToken=eG5yTGM0YmpGWUNtcXFtTW9DV2FENjlJMXhRVUlnTWN5TVFJOEVWRWRUYi9CUTBzaHI2TFhRT2xkS3Zyd1RYb2VrZklQUkg0YXY5YU1lU0d1M3NxQWh0YkYwVXdxQmU2TWVQVlZNU09MNEJGSG1Tck14cEhFSmJBYkxHMk12M0VseWtDSmtFZmNMa3NTY2hkVTgzZkRGWVQ3WUI4RHB0Zk5pR201ZEVkVm9vbTBHQjhRZWNxMHRPMXppSmxpV1RvSDNBQm9sbjI0ME1aUmwvZUJtOVM0TWJBbVpKYUU3b1hHdzhUVDMvL2tnR0s1UERwajNLRy9iMm9oWkJxNExRdk1BOVJGcFVlbmxaU3NZUzBnVUl0bVZ0eklwSDBtRXl5NDd3SFlOWG5iWE9NeUQyayt6bWVHTFY0MTFqTVQ4THh1UGgyYjU1NFJWQng1bGlHT2ltclh5QmwvK05NYkNmZ2lpcDRNVWtaajU0TExKZ3phdmN5dCtyMW5uaklhVXNwRjhOd0RleFc4NmJXTkIxVDVnR3VlV1U1dGlLK2N1V1IzMkUxT29XNW4ya3d4MUFJNU0vRWZrZjNhK0FUbi9aUWhGdWVYZ3lKUlY0NjhBUjdtODhEeXdnUDVWV1ZETUovcGtjTUFYS1pzbUFNY0phZTUwMlNsYTF6T0ZhcU83N1d1OGFoaWFBTUxpZ0V0VHlDN3ZYUkJSREVoaUV3QUpzbWxieCsxb0Y2RGVBPQ== [wss]
Could not connect: Connection closed before handshake
Message received {}
Could not connect: Connection closed before handshake
Could not connect: Connection to localhost:2053 failed during TLS handshake: Unable to complete TLS handshake: Peer certificate CN=`mhktube.com' did not match expected CN=`localhost'
Could not connect: Connection closed before handshake
Could not connect: Connection to 127.0.0.1:2053 failed during TLS handshake: Unable to complete TLS handshake: Peer certificate CN=`mhktube.com' did not match expected CN=`127.0.0.1'

**Comment by DanielnetoDotCom** [comment]
Hi
first, check if those paths are correct

![image](https://user-images.githubusercontent.com/18009293/112139166-35062700-8bb1-11eb-993e-40feb7d2a00c.png)

if it is make sure you run the socket as sudo

**Comment by milehighkaraoke** [comment]
I do believe the paths are correct 
![20210323_053831](https://user-images.githubusercontent.com/70327833/112140881-35df8e80-8b9a-11eb-84e9-0d0424c4a5e1.jpg)
![20210323_053634](https://user-images.githubusercontent.com/70327833/112140884-36782500-8b9a-11eb-8d81-bc7d1261d64d.jpg)

**Comment by milehighkaraoke** [comment]
Yes I am sudo for rhe nohup

![20210323_061617](https://user-images.githubusercontent.com/70327833/112146871-b1910980-8ba1-11eb-9ef7-dcf69d587b26.jpg)

**Comment by DanielnetoDotCom** [comment]
Try to run without nohup and the last &

for example, instead of `sudo nohup php /var/www/html/plugin/YPTSocket/server.php &`

try `sudo php /var/www/html/plugin/YPTSocket/server.php`

So you will be able to see the socket output and it may give you some clue

**Comment by milehighkaraoke** [comment]
Here is what it is returning
![16165154473609950300588599986](https://user-images.githubusercontent.com/70327833/112178119-245cad80-8bbf-11eb-8f03-df38d12c74da.jpg)

**Comment by DanielnetoDotCom** [comment]
Check the Apache error log then.

it should hang on the socket command

**Comment by DanielnetoDotCom** [comment]
@milehighkaraoke first disable the combine sites plugin. it does not work properly yet

**Comment by milehighkaraoke** [comment]
Ok, now it is off. I will retest now and post results

**Comment by milehighkaraoke** [comment]
Here is what it is returning now..... and the apache log for the pas 40 minutes or si

![20210323_144310](https://user-images.githubusercontent.com/70327833/112215634-33a32180-8be6-11eb-8581-7dc54c6ca26b.jpg)
![20210323_143359](https://user-images.githubusercontent.com/70327833/112215637-343bb800-8be6-11eb-842b-c70b181c56b1.jpg)

**Comment by milehighkaraoke** [comment]
Here is test.php

![20210323_145514](https://user-images.githubusercontent.com/70327833/112217750-81208e00-8be8-11eb-86af-9b6b571b6644.jpg)

**Comment by DanielnetoDotCom** [comment]
your socket is clearly not running

try to change the port

**Comment by milehighkaraoke** [comment]
What port do you suggest?

**Comment by milehighkaraoke** [comment]
Open port check is giving me  open status on port 2053

**Comment by milehighkaraoke** [comment]
![Screenshot_20210323-163022_Samsung Internet](https://user-images.githubusercontent.com/70327833/112227364-28a3bd80-8bf5-11eb-8373-8140739d40d6.jpg)

**Comment by DanielnetoDotCom** [comment]
Maybe another service is using the port, that is why I suggest you to change it

**Comment by milehighkaraoke** [comment]
Ok, is there a specific port I should terminate

**Comment by DanielnetoDotCom** [comment]
you can use any port, just change it on the plugin parameters and clear the cache

**Comment by milehighkaraoke** [comment]
This is returning same response. 

![Uploading 20210323_164358.jpg…]()

**Comment by milehighkaraoke** [comment]
This is confusing  this is showing its connected 
![16165399179689135148578698237118](https://user-images.githubusercontent.com/70327833/112229244-373fa400-8bf8-11eb-982a-b6a950f625e5.jpg)

**Comment by akhilleusuggo** [comment]
ok , can you try adding your IP and domaine name to your hosts ?

`sudo nano /etc/hosts`

Reboot , and re-enable socket

**Comment by milehighkaraoke** [comment]
Ok, I did that. I will restart services and let you know the outcome

![20210324_033349](https://user-images.githubusercontent.com/70327833/112287271-d2189c80-8c51-11eb-9ebb-de25bef8f797.jpg)

**Comment by milehighkaraoke** [comment]
Ok, I did that. I will restart services and let you know the outcome

![20210324_033349](https://user-images.githubusercontent.com/70327833/112287271-d2189c80-8c51-11eb-9ebb-de25bef8f797.jpg)

**Comment by akhilleusuggo** [comment]
So you're behind a firewall ?
Well maybe that's the issue . If you're behind a firewall ( router / switch ) , you will need to open the ports also on the firewall , not only on the OS . The OS will be the secondary firewall . 

Making the IP points directly to the site , will ignore the DNS and routing . But if it doesn't work , you may need to open the ports on the firewall too .

**Comment by milehighkaraoke** [comment]
Port forwarding is open to the required ports from my router to my server

**Comment by akhilleusuggo** [comment]
Does it work in the first place ?

For socket you may need _port forwarding bidirectional_

**Comment by milehighkaraoke** [comment]
Same outcome

![20210324_035046](https://user-images.githubusercontent.com/70327833/112290094-83203680-8c54-11eb-8dca-b0caacbabc28.jpg)
![20210324_034731](https://user-images.githubusercontent.com/70327833/112290100-83b8cd00-8c54-11eb-8ace-5f58d65f623d.jpg)

**Comment by milehighkaraoke** [comment]
Where am I to be launching the terminal to start the socket? Will it work from the desktop or do I need to be in the socket directory when I launch terminal?

**Comment by milehighkaraoke** [comment]
![20210324_040105](https://user-images.githubusercontent.com/70327833/112291308-9e3f7600-8c55-11eb-9875-3b5b55688061.jpg)

**Comment by milehighkaraoke** [comment]
It is showing connected but test .php  states otherwise 
![Uploading 20210324_035856.jpg…]()

**Comment by DanielnetoDotCom** [comment]
Hi @milehighkaraoke the test.php tries different combinations, and some of them may fail.
but you will be able to see what combination is working. and reaching the socket server.

before make sure it is working in a separate terminal run this https://github.com/WWBN/AVideo/issues/4768#issuecomment-805007151

also try to change the socket port

**Comment by milehighkaraoke** [comment]
I tried different porr with same result. No handshake 
![20210324_034731](https://user-images.githubusercontent.com/70327833/112306557-8bcd3880-8c65-11eb-8c4c-7008c44bff80.jpg)

**Comment by milehighkaraoke** [comment]
Where or how do I change the 127.0.0.1  to mhktube.com

**Comment by milehighkaraoke** [comment]
Ok, is this what I am looking for? It is scrolling with activity now. 

![Uploading 20210324_062053.jpg…]()
![20210324_061927](https://user-images.githubusercontent.com/70327833/112309631-2b3ffa80-8c69-11eb-81a6-97445a808182.jpg)

**Comment by milehighkaraoke** [comment]
![Uploading 20210324_062053.jpg…]()

**Comment by milehighkaraoke** [comment]
![20210324_062053](https://user-images.githubusercontent.com/70327833/112311650-8bd03700-8c6b-11eb-87c4-eecaf157da85.jpg)

**Comment by milehighkaraoke** [comment]
Can I crontab this command in root after my nginx

**Comment by milehighkaraoke** [comment]
When I open up second terminal and do a test it still is showing that is is failed handshake. What on earth am I missing? # #
![20210324_064056](https://user-images.githubusercontent.com/70327833/112312203-2af52e80-8c6c-11eb-877d-72502b410558.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, as I can see your socket is working.

the test tools may return some errors, it is just to direct you what address you should use
