### ISSUE TITLE
Live stream not shutting off dispite having proper on publish done

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#4769]
OK, this is now happening after latest git pull despite having on publish done in my nginx. Only way to get it to stop is to again clear the site cashe
![16164652354925037872516767717196](https://user-images.githubusercontent.com/70327833/112082027-3ea87400-8b4a-11eb-9d2f-9226b1ddf65d.jpg)
che

**Comment by DanielnetoDotCom** [comment]
Please make a git pull and check it again

**Comment by milehighkaraoke** [comment]
Great work my friend. That fixed it!!!!

**Comment by milehighkaraoke** [comment]
Now to get it to show the live streams I have to clear site cache and refresh the page.

**Comment by milehighkaraoke** [comment]
New errors after installing updated plugins

![Screenshot_20210323-102749_Samsung Internet](https://user-images.githubusercontent.com/70327833/112182670-1b6ddb00-8bc3-11eb-95c7-7b9379805659.jpg)
![Screenshot_20210323-102801_Samsung Internet](https://user-images.githubusercontent.com/70327833/112182672-1c067180-8bc3-11eb-9aea-72f4f1c861ab.jpg)
![Screenshot_20210323-102837_Samsung Internet](https://user-images.githubusercontent.com/70327833/112182675-1c067180-8bc3-11eb-8fae-22d245f6f231.jpg)
![Screenshot_20210323-102850_Samsung Internet](https://user-images.githubusercontent.com/70327833/112182676-1c9f0800-8bc3-11eb-8aea-f1f96ee6709d.jpg)
![Screenshot_20210323-102856_Samsung Internet](https://user-images.githubusercontent.com/70327833/112182677-1c9f0800-8bc3-11eb-8411-21158dc92c62.jpg)
![Screenshot_20210323-102904_Samsung Internet](https://user-images.githubusercontent.com/70327833/112182678-1d379e80-8bc3-11eb-93f1-13459d0eb007.jpg)
![Screenshot_20210323-102913_Samsung Internet](https://user-images.githubusercontent.com/70327833/112182680-1d379e80-8bc3-11eb-9f48-1b2701d72094.jpg)

**Comment by DanielnetoDotCom** [comment]
Here is a fix

**Comment by milehighkaraoke** [comment]
I don't see the fix?

**Comment by milehighkaraoke** [comment]
Now after this git pull  the cache now has to be cleared to get the live counter to start working.....

**Comment by DanielnetoDotCom** [comment]
So is it working now?

**Comment by milehighkaraoke** [comment]
No, I have to now clear the cache to get it to start showing the live stream.

**Comment by milehighkaraoke** [comment]
If I am broadcasting a stream it now will go back to 0 when I shut the stream off but unfortunately if I restart this stream I then have to clear the cache to get the live stream to show in the counter

**Comment by milehighkaraoke** [comment]
Mhktube.com.  you may feel free to make account and stream to see its behavior

**Comment by milehighkaraoke** [comment]
It now seems to be working.  Very strange. I will keep you posted ... thanks for your help

**Comment by DanielnetoDotCom** [comment]
Make sure your socket is running

**Comment by milehighkaraoke** [comment]
Issue's on 4768 not resolved. Apache showed only a local host error that I corrected. Still unable to get the socket test to handshake. Socket is green and connected in plugin

**Comment by milehighkaraoke** [comment]
Localhost works
![20210323_124210](https://user-images.githubusercontent.com/70327833/112211069-1455c580-8be1-11eb-876b-b94aba92f5d8.jpg)

**Comment by milehighkaraoke** [comment]
![Screenshot_20210323-141314_Samsung Internet](https://user-images.githubusercontent.com/70327833/112211993-12d8cd00-8be2-11eb-8669-26d5b95874db.jpg)

**Comment by DanielnetoDotCom** [comment]
Lets keep it on issue https://github.com/WWBN/AVideo/issues/4768
