### ISSUE TITLE
l10n - How to translate reporting mails?

### ISSUE THREAD

**Issue by Joelp** [WWBN/AVideo#4770]
I am wondering how to translate aVideo emails. For example, reporting ones from file ReportVideo.php:
`The {videoName} video was reported as inapropriate`

There is a missing `__(` part.

**Comment by DanielnetoDotCom** [comment]
In this case, I could add the __(

**Comment by Joelp** [comment]
thanks, but this bring another problem. HTML from string is not interpreted in mail. Example what I see in mail:

`
Video, od Testing user, <a href='https://play.testdomain.cz/v/4?channelName=TestChannel'>Test video Name - 16.07.2020</a> bylo nahlášeno jako nevhodné 
`
