### ISSUE TITLE
Superchat

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#4774]
Could you improve chat to include a superchat feature for super easy donating?

**Comment by DanielnetoDotCom** [comment]
Please detail superchat feature

**Comment by fakeologist** [comment]
It allows you to tip the website via a connect paypal account.
It highlites the comment with a color so the livestreamer can read it easily.
https://www.youtube.com/watch?v=sQkFaPUJIQY

**Comment by syldri** [comment]
hello this is a very good thing, remember that the owner of the site take a percentage of every donation the user receives

**Comment by JoshWho** [comment]
This feature is already implemented.  You add your Pay page link or Paypal whatever u want to use in your account settings and it will show on all your videos and also in the live chat.

![a2d2d666-8ac3-460c-81ea-8128dac17d96](https://user-images.githubusercontent.com/39392449/113389676-0a0c9780-9356-11eb-92a6-d05607cc10dc.png)
![1b6d8156-f915-4299-bfda-8d654d620f4b](https://user-images.githubusercontent.com/39392449/113389683-0da01e80-9356-11eb-8605-b4ccc429aa33.png)
![59d1b138-289a-430b-9591-79c1f48f0c52](https://user-images.githubusercontent.com/39392449/113389684-10027880-9356-11eb-835c-44b382c87cd3.png)

**Comment by syldri** [comment]
@JoshWho  I know there is this information
when you watch another streaming site, the site owner earns a percentage on each donation and subscription

**Comment by JoshWho** [comment]
Ahhh I see u want to split shares. That will have to be something new. @DanielnetoDotCom  could work on something for you, just set up a deal and he will give u a price.
