### ISSUE TITLE
Live broken after git pull from today

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4775]
After your changes on the live part today this is very broken for me.

Onpublish.php and the other once dont work anymore:

![Screenshot_20210323-193404_Chrome.jpg](https://user-images.githubusercontent.com/50199132/112200255-572e9200-8c0f-11eb-9dcd-84881e07436d.jpg)

![Screenshot_20210323-190958_Chrome.jpg](https://user-images.githubusercontent.com/50199132/112200294-60b7fa00-8c0f-11eb-964d-0c7384ec45c2.jpg)

![Screenshot_20210323-191027_Chrome.jpg](https://user-images.githubusercontent.com/50199132/112200317-67df0800-8c0f-11eb-872c-a8d077778f1a.jpg)

![Screenshot_20210323-193535_Chrome.jpg](https://user-images.githubusercontent.com/50199132/112200371-74636080-8c0f-11eb-8ea6-1b6f7e65978c.jpg)

**Comment by morbificagent** [comment]
As result the stream only shows offline :-(

**Comment by 01123581321345589144233** [comment]
seems like this one
https://github.com/WWBN/AVideo/issues/4773

**Comment by 01123581321345589144233** [comment]
i have the same after the livestream is startet the stream is not showing on the startpage

**Comment by morbificagent** [comment]
In my case its showing on the start page but only with a big OFFLINE picture.
When i click on it rhe stream is playing fine but the big OFFLINE Image doesnt go away, no preview pictures are extracted, and so i think like the errormessages indicates:

All onpublish.php etc scipts which are called from nginx for the stream arent working with the updated version of the live part from today...

@DanielnetoDotCom help?

**Comment by 01123581321345589144233** [comment]
try to clear the cache

**Comment by morbificagent** [comment]
Done already... And restarted apache and nginx... Nope

**Comment by DanielnetoDotCom** [comment]
Seems to me your socket is not working

**Comment by morbificagent** [comment]
Its up and running:

![image](https://user-images.githubusercontent.com/50199132/112216229-8d750d00-8c21-11eb-9648-fbb1a0a7a3ae.png)

![image](https://user-images.githubusercontent.com/50199132/112216314-a251a080-8c21-11eb-8223-8f08a4e97706.png)

have restarted the socket plugin and the server.php but makes no difference

**Comment by morbificagent** [comment]
Here everything in one screenshot. 

- server.php is running on :2053 and looks fine
- Website/Socket-plugin says "Connected"
- And the errormessage in the log when starting a stream

![image](https://user-images.githubusercontent.com/50199132/112219412-3a9d5480-8c25-11eb-96c3-00e9ab100f96.png)

BTW the chat2 via the socket is running fine too... so its really working

**Comment by karlkunc** [comment]
I also did the git pull, and I just tested the live stream and it is working. I tested from my mobile android browser to a pc. I have not tested the app.

**Comment by morbificagent** [comment]
while the socket-errors filling my logs this is what happens on the Website:

Even if my log shows these onpublish.php/socketConnect-errors the site is informed about a starting stream somehow.
OK, its shown as OFFLINE again...hm...:

![image](https://user-images.githubusercontent.com/50199132/112223490-4d665800-8c2a-11eb-8d80-d9717349a29f.png)

when i reload the page now all information about the running stream is gone:

![image](https://user-images.githubusercontent.com/50199132/112223921-dc737000-8c2a-11eb-9fd2-48fd2e0a921f.png)

**Comment by 01123581321345589144233** [comment]
i have make ap git pull now, no differrence
avideo.error.log:
[Tue Mar 23 23:50:55.771517 2021] [php7:error] [pid 16287] [client ***:54810] script '/var/www/AVideo/plugin/Live/droplive.json.php' not found or unable to stat, referer: https://****/meet/191/011235-media-danmarkvaagner

**Comment by 01123581321345589144233** [comment]
[23-Mar-2021 22:51:02 Europe/Dublin] PHP Fatal error:  Uncaught Error: Call to undefined method LiveTransmitionHistory::isAdaptive() in path/to/my/streamer/site/plugin/Live/Objects/LiveTransmitionHistory.php:131

**Comment by morbificagent** [comment]
Clearing the cache "first site cache" helps for a moment as the Stream is shown online after that.
But i have to do this all the time manually after starting a stream.

So as you said in another thread the "on_publish etc.. -files" are doing a cache clean normally and my log shows errors with these files i have to repeat my guess:

**Something with these files or the things they try to do is wrong**

**Comment by morbificagent** [comment]
For reminding (and as we know the socket is up and running, and displays connected):

![image](https://user-images.githubusercontent.com/50199132/112272501-921adf00-8c7c-11eb-9b01-4da62c0c7602.png)

**Comment by milehighkaraoke** [comment]
do a git pull again  mine was doing the same thing. most recent Git Pull Fixed it.

**Comment by morbificagent** [comment]
![image](https://user-images.githubusercontent.com/50199132/112287697-ed54cd80-8c8c-11eb-929c-7d53121ae09f.png)

**Comment by milehighkaraoke** [comment]
Ok, Dan will look at this for you.....

**Comment by morbificagent** [comment]
Eventually this is part of the problem!?
![image](https://user-images.githubusercontent.com/50199132/112291653-98b35180-8c90-11eb-8574-497193067739.png)

When i start to stream nginx logs an error that he couldnt open the .m3u8 from that stream.
But if i do a cat on this it works without problems and i can request it from external via browser too...

**Comment by 01123581321345589144233** [comment]
> When i start to stream nginx logs an error that he couldnt open the .m3u8 from that stream.
same here

**Comment by DanielnetoDotCom** [comment]
@morbificagent I just notice, are you using a nonsecure socket?

If your site is HTTPS you MUST use the secure one, so make sure it is unchecked 
![image](https://user-images.githubusercontent.com/18009293/112305562-9b587b80-8c7d-11eb-979b-07ff6dde5ade.png)

regarding it could not open, it always tries to access your server thru the public domain, you can try to add this into your hosts file and point it directly to 127.0.0.1

https://websiteforstudents.com/how-to-edit-the-local-hosts-file-on-ubuntu-18-04-16-04/

**Comment by morbificagent** [comment]
![image](https://user-images.githubusercontent.com/50199132/112307373-29922900-8ca1-11eb-8a79-c95adc3651fb.png)

Its all https in my config...

**Comment by morbificagent** [comment]
and as it listens on 0.0.0.0, the certs are used properly and i can connect to it via my avideo https website  i cant find any problem.

![image](https://user-images.githubusercontent.com/50199132/112308409-66125480-8ca2-11eb-95ad-f3a1192884db.png)

**Comment by morbificagent** [comment]
Only the nginx calls for on_publish etc. are http because nginx doesnt can use https here:

![image](https://user-images.githubusercontent.com/50199132/112313990-c86e5380-8ca8-11eb-964d-e3b305b7bbaf.png)

**Comment by peterflitz** [comment]
> Only the nginx calls for on_publish etc. are http because nginx doesnt can use https here:
> 
> ![image](https://user-images.githubusercontent.com/50199132/112313990-c86e5380-8ca8-11eb-964d-e3b305b7bbaf.png)

did you also test with your server ip?

**Comment by morbificagent** [comment]
No i didnt because my nginx-config is hostheader-based. So it needs the FQDN of the server to route the request to the right site...

**Comment by 01123581321345589144233** [comment]
Thats my nginx, why you have on_publish_done ?

on_publish http://localhost/plugin/Live/on_publish.php;
on_play http://localhost/plugin/Live/on_play.php;
on_record_done http://localhost/plugin/Live/on_record_done.php;

**Comment by morbificagent** [comment]
The howto from Daniel is outdated i think.
At some points he said we should use this:

https://github.com/WWBN/AVideo/issues/4713#issuecomment-800178662

**Comment by morbificagent** [comment]
Found out a interesting part:

My Site is serverd by https and by http because it was nessesary for the on_publish.php's in nginx.

As i was playing and searching for the problem with the disappearing livestreams i mentiond that this seams only be a problem on the https-version of my site.
**If i use the http version the problem isnt there!!!**

**Comment by DanielnetoDotCom** [comment]
Hi,

Regarding the notification, I got a customer with a similar problem, and I could look directly into his server.
I am pretty sure it is fixed now, please update and try again.

**Comment by morbificagent** [comment]
Hallelujah...... Its working!

Daniel, thank you for your hard work!

**Comment by 01123581321345589144233** [comment]
hm i have updatete the notification to 2.2 and make a git pull, så i am live but the message on the startpage are not shown

**Comment by 01123581321345589144233** [comment]
so i can see the message 2sec also under the streaming puldown.

**Comment by 01123581321345589144233** [comment]
[25-Mar-2021 11:17:08 Europe/Dublin] AVideoLog::DEBUG: Video:clearCache(528) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [25-Mar-2021 11:17:08 Europe/Dublin] AVideoLog::DEBUG: Video:clearCacheFromFilename(EmptyTitleon25Mar21121404_YPTuniqid_605c70edc68780.51556706_360.mp4) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [25-Mar-2021 11:17:08 Europe/Dublin] AVideoLog::DEBUG: NGINX Live::on_publish_socket_notification end SCRIPT_NAME: path/to/my/streamer/site/plugin/Live/on_publish_socket_notification.php

 [25-Mar-2021 11:17:08 Europe/Dublin] AVideoLog::DEBUG: decideMoveUploadedToVideos: destinationFile path/to/my/streamer/site/videos/EmptyTitleon25Mar21121404_YPTuniqid_605c70edc68780.51556706_360.mp4 filesize=3088577 (2.95MB) SCRIPT_NAME: /objects/aVideoEncoder.json.php

 [25-Mar-2021 11:17:08 Europe/Dublin] AVideoLog::DEBUG: NGINX Live::on_publish_socket_notification SocketMessageToAll END SCRIPT_NAME: path/to/my/streamer/site/plugin/Live/on_publish_socket_notification.php

 [25-Mar-2021 11:17:08 Europe/Dublin] AVideoLog::ERROR: sendSocketMessage  SCRIPT_NAME: path/to/my/streamer/site/plugin/Live/on_publish_socket_notification.php

**Comment by DanielnetoDotCom** [comment]
Hi, the notification plugin has nothing to do with the Live notification.

you need to update the streamer
