### ISSUE TITLE
Admin Controls Encoder Missing. 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#4778]
Admin controls missing. Unable to remove streamer que that is invalid 
![16165735121282159251044269649991](https://user-images.githubusercontent.com/70327833/112276411-5533f580-8c46-11eb-84a4-75598fc2bd45.jpg)
![16165735309474084546838155632435](https://user-images.githubusercontent.com/70327833/112276443-5ebd5d80-8c46-11eb-985f-1dc8979960e0.jpg)

.

**Comment by DanielnetoDotCom** [comment]
Please check this https://tutorials.avideo.com/video/109/make-an-encoder-administrator-user

**Comment by milehighkaraoke** [comment]
Thank you, that fixed it
