### ISSUE TITLE
Live dont  work 

### ISSUE THREAD

**Issue by antuk21** [WWBN/AVideo#4779]
**Describe the bug**
LIVE still says playing up 

i ent even live still says live  its a cache issue soon i clear cash works but shouldnt be like that 

and wen i go live sometimes says 0 and live dont even load i havent changed nothing since your team installed it   so    since i updated to your updates nothing but issues

**Comment by morbificagent** [comment]
It scares me too... actual im starting with my site and a day or two with such problems is not great but possible...

But for use it in production it looks like i definitly need a testing-system for the updates so such things dont crash my site everytime when the code is changed...

-> Live is down here too :-(

**Comment by morbificagent** [comment]
@DanielnetoDotCom sorry for interrupt you while "try to fix infinite scroll" but as i can read we now have more and more users with the same problem: Livestream is popping up once and after that it is hidden until we make a manually "cache clear"

**So Live-Streaming is broken at the moment on several installations (like on my site too)**

**Comment by morbificagent** [comment]
@antuk21 please try this if your site is reachable via http too:

https://github.com/WWBN/AVideo/issues/4775#issuecomment-805971871

**Comment by DanielnetoDotCom** [comment]
Hi,

Regarding the notification, I got a customer with a similar problem, and I could look directly into his server.
I am pretty sure it is fixed now, please update and try again.

**Comment by morbificagent** [comment]
Hallelujah...... Its working!

Daniel, thank you for your hard work!

**Comment by peterflitz** [comment]
thanks Daniel.

please don't forget the LiveLink ;-)

**Comment by morbificagent** [comment]
And dont forget to drink a beer at the end of today (or whatever you do after a hard day ;-)

**Comment by DanielnetoDotCom** [comment]
@peterflitz what is the Livelink issue?

**Comment by peterflitz** [comment]
> @peterflitz what is the Livelink issue?

Ad a Live Link plugin

Another mistake here is that it doesn't start until I empty the firstpage cache.
It also ends only, when I empty the cache again.

Then i tested together, Live Plugin and Ad A Live Link Plugin.
If I quit the live, then the live link will be also terminated.
So the fix that was built into the live plugin is missing in the Ad a Live Link, so i think :-)

Thanks for your work Daniel

**Comment by DanielnetoDotCom** [comment]
This update should clear the stats cache when save a livelink

**Comment by peterflitz** [comment]
> This update should clear the stats cache when save a livelink

@DanielnetoDotCom 
"Ad a Live Link" notifikation still not working.
The live is still only displayed when I empty the "First Page Cache"

**Comment by DanielnetoDotCom** [comment]
I see what you mean.

You are right, please check this

**Comment by peterflitz** [comment]
> I see what you mean.
> 
> You are right, please check this

The "Ad a Live Link" problem is unchanged.
The notification only works when I empty the "First Site Cache"

**Comment by DanielnetoDotCom** [comment]
on notification save, the first page is cleared.

how is your cache plugin parameters setup?

**Comment by peterflitz** [comment]
The cache is deactivated on my test page and nothing has been changed in the settings.

The cache is activated on my official website, in the standard setting

**Comment by DanielnetoDotCom** [comment]
Hi, I just made a bunch of cache improvements

please try now

**Comment by peterflitz** [comment]
Hi Daniel,

I see all the work and all the changes.

Have you tied the preview of the lives to the socket ;-)
If the socket is on, much better.

On my main page, the socket causes jerking up from 200 users online, but it is a different issue.

The "Ad a Live Link" is still the problem of the display / display / notification, only works when I empty the "First Site Cache". In addition, since the last update I have to reload the page so that the notification of the live is gone.

This problem is independent of whether the socket server is active or deactivated.

It doesn't matter, always a big THANK YOU for your work.

**Comment by DanielnetoDotCom** [comment]
Here is some more work on the Livelinks

**Comment by peterflitz** [comment]
> Here is some more work on the Livelinks

Still no notification.
Now i must clear the FirstSiteCache and must reload the page.
