### ISSUE TITLE
playerFullHeight only on Lives

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4781]
Hi Daniel,

i know, you have enough to do but if there wold be time to implement "playerFullHeight" Setting separate for Live Streams that would be great!

Background:

If a user wants to look "youtube-style" some videos and zapping over the site its good without "playerFullHeight".
If a user wants to look a Live-stream the "playerFullHeight"-Setting looks much better as he can focus on the stream:

![image](https://user-images.githubusercontent.com/50199132/112451170-7800ff80-8d55-11eb-9804-2119cd03f52c.png)

**Comment by DanielnetoDotCom** [comment]
What about the TheaterButton plugin?

https://user-images.githubusercontent.com/18009293/112474563-91527d80-8d4e-11eb-8e16-52140ac1dea1.mp4

**Comment by morbificagent** [comment]
I have configured the Theater-Mode as default already.... its better than without but as you can see using it gives a way smaller picture like on "playerFullHeight":

![image](https://user-images.githubusercontent.com/50199132/112492530-a1378500-8d81-11eb-9744-6c88ffa193f2.png)

**Comment by DanielnetoDotCom** [comment]
I do not understand what you mean

**Comment by morbificagent** [comment]
Compare my first and my second picture.
The first is a lifestream with "playerFullHeight" enabled.
It looks great in my opinion and uses the full height.

The second is with the Theater mode enabled.
There the video is much smaller as the full height isn't used. Under it there is white space and the description and all this things.

So as I said it would be great to have the possibility of choosing the playerFullHeight option for live streams only and the theater mode for the vod files.

**Comment by DanielnetoDotCom** [comment]
I see, I will may add this option in the future

**Comment by morbificagent** [comment]
That would be great :-)
