### ISSUE TITLE
Request to add Live Streams to the Channel Page

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4782]
I requested this a while back and it idling out with no answer but is it possible to be able to make users live streams appear on their channel page?

**Comment by DanielnetoDotCom** [comment]
It is possible and also a great idea. I will implement it as soon as I find some free time or a sponsor for it

**Comment by JoshWho** [comment]
Sweeeeeeeeeeeet, Looking forward to it 😃

**Comment by morbificagent** [comment]
Would love to have it too as i could say: 

here is your own store (channel). You only have to give ONE link or QR to your customers and they can see you live and you can sell media there.

At the moment this isnt possible.
