### ISSUE TITLE
any one help me with this error please

### ISSUE THREAD

**Issue by antuk21** [WWBN/AVideo#4786]
https://prnt.sc/10vk0lv

i have  try everything on github to fix this and i am still seeing the offline poster 2 any help would be much thankful! thanks

just another error frew 
https://prnt.sc/10vkml1

**Comment by DanielnetoDotCom** [comment]
Make sure your socket is running

**Comment by antuk21** [comment]
yes it is  just see offline  now 

wen im  live  https://prnt.sc/10wh36q

**Comment by DanielnetoDotCom** [comment]
Did you just update the code?
I sent updates 40 min ago

**Comment by antuk21** [comment]
yep

**Comment by antuk21** [comment]
https://prnt.sc/10wiy2c  
https://prnt.sc/10wiygc

**Comment by DanielnetoDotCom** [comment]
I see, I will work in something about it

**Comment by antuk21** [comment]
ok thanks brother
