### ISSUE TITLE
Starting web socket at boot

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#4787]
Is there a way to automatically start the websocket at boot. Nginx is in crontab and starts automatic at boot.  I tried following it with another crontab for the websocket without success.  Any help with this would be greatly appreciated as manually starting services everytime I reboot is annoying.

**Comment by antuk21** [comment]
https://github.com/WWBN/AVideo/wiki/Socket-Plugin    this will help you

**Comment by milehighkaraoke** [comment]
I tried this without success. The only way it starts for me is to manually run the command. 

![Screenshot_20210325-195131_Samsung Internet](https://user-images.githubusercontent.com/70327833/112565892-98f04180-8da3-11eb-92dd-c426b2da173d.jpg)

**Comment by antuk21** [comment]
witch verson off ubuntu do you use  did you open port 2053 in your gate way that will be why need to allow it try that get back to me

**Comment by milehighkaraoke** [comment]
2053 is open I am using Ubuntu 20.04

**Comment by antuk21** [comment]
@reboot /usr/local/nginx/sbin/nginx && nohup php /var/www/html/AVideo/plugin/Li$
@reboot nohup php /var/www/html/AVideo/plugin/YPTSocket/server.php &
0 2 * * * php /var/www/html/AVideo/plugin/cache/crontab.php

dose your eu crontab config look like this at end off blue code

**Comment by antuk21** [comment]
been few updates today so do a git pull maybe 

cd /var/www/html/AVideo/ && sudo git pull

cd /var/www/html/YouPHPTube/ && sudo git pull

**Comment by antuk21** [comment]
https://mediapuller.com/videos/mood-24kgoldn-ft-iann-dior-cover

**Comment by milehighkaraoke** [comment]
Root crontab is identical.Gitpull is complete.....Nginx starts on boot but the websocket has to still be manually started.

**Comment by akhilleusuggo** [comment]
I'll update the wiki that @DanielnetoDotCom wrote . The script is missing the most important thing at boot ( Sleep time ).
The socket can not start at boot before giving Apache few seconds to load modules , so the script fails .

Replace your crontab with this ;

`@reboot sleep 60;nohup php /var/www/html/AVideo/plugin/YPTSocket/server.php &`

The script will start 60s after boot ( is enough time and recommended to avoid issues )

Wiki updated ; https://github.com/WWBN/AVideo/wiki/Socket-Plugin

**Comment by milehighkaraoke** [comment]
Perfect 🥰

**Comment by milehighkaraoke** [comment]
I am getting the same results. Waited 5 minutes and socket is still disconnected. Updated crontab to 120 seconds did a reboot and still will not connect with a crontab command

![20210327_143454](https://user-images.githubusercontent.com/70327833/112734395-1da99f80-8f0b-11eb-95fa-e10e5e0623e7.jpg)
![20210327_144257](https://user-images.githubusercontent.com/70327833/112734397-1e423600-8f0b-11eb-8523-3720b2332eab.jpg)

**Comment by milehighkaraoke** [comment]
I think k it might be a permissions issue. When I log off of my Ubuntu user account , i just noticed that the socket disconnects

**Comment by akhilleusuggo** [comment]
@milehighkaraoke it's not . Look at what you wrote . Must be a space between `php` and `/var/ww.....`

**Comment by milehighkaraoke** [comment]
Thank you that was the problem
