### ISSUE TITLE
Live "Starts in..."

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4788]
Have seen this on a screenshot from you...

how can i get this "Starts in ..."???

![image](https://user-images.githubusercontent.com/50199132/112614775-f1feba80-8e21-11eb-8153-2ff1b6b0f442.png)

**Comment by antuk21** [comment]
your lucky mine dont even work  and i dont ever get help  sucks

**Comment by jengajenga** [comment]
> Have seen this on a screenshot from you...
> 
> how can i get this "Starts in ..."???
> 
> ![image](https://user-images.githubusercontent.com/50199132/112614775-f1feba80-8e21-11eb-8153-2ff1b6b0f442.png)

it's a paid plugin which you must buy

**Comment by morbificagent** [comment]
Whats the Name of it?

**Comment by jengajenga** [comment]
> Whats the Name of it?

PayPerView Live

**Comment by morbificagent** [comment]
Ah ok, i thought that its only for paying for events but didnt know that it makes this nice cowntdown...

So you can plan events with it and they are shown until they are starting?

Do i have to enter a price and a paying process or can i use it only for the planing part?

**Comment by DanielnetoDotCom** [comment]
For now, the schedule is only on the PPV Live plugin.

I may create an option for free lives in the Future

**Comment by morbificagent** [comment]
ok, but if i would buy it, could i use it to schedule Live without the need that a user pays?

or is the process of paying forced?

**Comment by DanielnetoDotCom** [comment]
At the moment they must Pay, but in the future I will add a free option

**Comment by jengajenga** [comment]
Is it compatible with PayPal as well or still only Stripe?

**Comment by DanielnetoDotCom** [comment]
This plugin uses the wallet balance, so you can use PayPal to add balance into your wallet
