### ISSUE TITLE
How to allow or restrict the download of videos per user, as before AVideo v10

### ISSUE THREAD

**Issue by franranchito** [WWBN/AVideo#4789]
Before updating to AVideo Streamer v10, when still in v9, I could restrict the permission to download videos to only certain non-admin (regular) users. In that way, those certain regular users could download the videos which had permission to be downloaded, but the other regular users couldn't, even when trying to download a video which could be downloaded.

This way, for a video configured to allow download:

-**Admin user**: Can download it (always can)

-**Regular user WITH permission to download videos**: Can download it, because although he is a regular user, he is allowed to download videos

-**Regular user WITHOUT permission to download videos**: Cannot download it

But now I see there was a rework of those permissions, because there is a new site-wide policy to prevent non-admin from downloading videos at all. If you disable it, then ALL regular users can download.

Is there a way now to keep allowing the download of videos to ONLY certain regular users?

I tried to use the Customize User plugin, but it is somehow bugged or unfinished, because I can't create anything there.

Thank you

**Comment by DanielnetoDotCom** [comment]
Have we ever had the option for only "certain regular users" to download?

I think we never had this option. but you can use user groups to control who can see the video and who cannot
