### ISSUE TITLE
Direct Uploads pane supports single file and open through the filesystem open panel - yet - I have seen the version that supports multiple file and drag-and drop. How?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4796]
**Describe the question**
How do you do drag-and-drop in the "Direct Uploads" pane?

The workflow is single-file per upload cycle, taking 10-12 seconds up front to create an empty file slot, and 3-5 seconds after the upload - and occasionally more like 2-3 minutes to save the file after upload - this for 1-2 MB PDFs.

NOTE: In January I installed AVideo and this same UI had a different look-and-feel and supported drag-and-drop from the filesystem, and multiple files could be queued right here in the Direct Uploads pane. I corrupted that install, and after reinstalling it haven't seen this version of the pane again.

How do I recover this wonderful feature that I saw and used for about 3 days in January? I have thousands of files to upload and this is a blocker for me, I've only got time to do a very small handful through this interface

**Screenshots**
This screenshot is of the single-file-at-a-time-non-drag-nor-drop interface that is causing me to have nightmares
![Screen Shot 2021-03-27 at 8 48 52 PM](https://user-images.githubusercontent.com/11711050/112743841-a4806b80-8f4f-11eb-8191-dcde55e3b9ff.png)

I don't have another screenshot of your other interface that supports multiple file drag-and-drop from the filesystem.  I didn't think it was going to disappear like that...

**Comment by walt93** [comment]
Note: this feature was much faster on first install, now at 2,988 files uploaded its performance is notably degraded. Correlation != causation but it seems a fair assumption.

**Comment by DanielnetoDotCom** [comment]
This feature is a direct upload (not in chunks)

so CDN and proxies may break it.

**Comment by walt93** [comment]
The problem of the interface being slow has corrected itself. Speculating that the database needed to run its optimizer.

More important question. Where did the drag-and-drop version of the direct uploads pane go?

**Comment by DanielnetoDotCom** [comment]
The drag and drop suppose to still there.

can you check if you can reproduce it on demo site?

**Comment by walt93** [comment]
(fat fingered the close issue button...)

**Comment by walt93** [comment]
Is this feature going to come back?
