### ISSUE TITLE
Sometimes the site is unable to load even after browser restart. Top shows apache instance stuck at 100%. ps kill -9'ing the instance fixes it.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4798]
**Describe the bug**
Sometimes I find myself doing an action, for instance uploading a PDF file that yields a progress/spinner animation for several minutes. Attempting to reload the page, quit/restart the browser all fail. SSH into the machine and check top reveals an apache process stuck at 100%. Killing this process unsticks the box.

**To Reproduce**
1. Go File upload
2. One at a time, upload PDF files
3. Eventually, you save a file that seems to bring the system to its knees
4. After which, apache never recovers

**Expected behavior**
It not to do that

**Error Logs**
Will catch them the next time this occurs, this report is post-mortem. Bug likely data driven will append with more data next time I catch it.

**Comment by akhilleusuggo** [comment]
Without the logs , could be anything . 
If you're sure about how to reproduce , just reproduce it and upload the logs .

Another thing to keep in mind , your user are the only one that are getting stuck . To make sure of this information , when you get ''stuck'' , open a _new incognito window_ , and access to your site , should be responsive .
