### ISSUE TITLE
Subscription plugin - translations

### ISSUE THREAD

**Issue by fxp66** [WWBN/AVideo#4799]
How can I manage to have a full translation of the plugin into german?
![screen-1](https://user-images.githubusercontent.com/40458047/112760644-13b19a80-8ff8-11eb-9cb5-326a1b72c12f.png)
How can I change currency notation from 2,000.00 to 2.000,00 (european)?
Thx for quick reply

**Comment by DanielnetoDotCom** [comment]
On subscription, V4.2 and add the` $v['Auto renew on'] `in your translation file.

currently is not possible to change the currency notation.
