### ISSUE TITLE
How to create my own jitsi custom server ?

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#4801]
Greetings . Please help I would like to learn how to create my own jitsi custom server.

**Comment by fxp66** [comment]
For testing purposes try docker version of jitsi, see [here >>](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker)

**Comment by fxp66** [comment]
You can customize docker version as well as full installation of jitsi

**Comment by mrgodgiven** [comment]
How ?

**Comment by fxp66** [comment]
[Like this for](https://root101.net/How-to-customize-docker-compose-based-Jitsi-installation) e.g 
But there are better ways... you have to google.
If you're looking for the config files take a look into root, there is a hidden directory
