### ISSUE TITLE
Clean installation without database tries to install anyway

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#4803]
I'm doing a fresh AVideo installation and althought I've selected "Do not create any, I will import the scripts manually" at the option "Do you want to create database and tables?", the script try to install the database and tables anyway:

![Screen Shot 2021-03-28 at 20 19 42](https://user-images.githubusercontent.com/12404245/112779236-7f4d3500-9003-11eb-90f3-a30c607f3c0c.jpg)

![Screen Shot 2021-03-28 at 20 19 55](https://user-images.githubusercontent.com/12404245/112779244-83795280-9003-11eb-8869-33b7f7d09126.jpg)

The database and user already exist.

**Comment by jengajenga** [comment]
Delete the database and user and try again

**Comment by swimitup** [comment]
I've changed the options to a database and user that do not exist:

![Screen Shot 2021-03-29 at 09 32 37](https://user-images.githubusercontent.com/12404245/112861273-e43f7400-9071-11eb-84ac-d1d201536b5e.jpg)

Did not work.

**Comment by DanielnetoDotCom** [comment]
The script needs to create an admin user

but looks to me your user cannot connect to the database

**Comment by swimitup** [comment]
So clarifying: even though you select "do not create any databases and tables, i will import the scripts manually", the installation process still will create the database and tables enough to have the admin user on it.
