### ISSUE TITLE
What is the purpose of the item "Play a Link"

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#4804]
Fresh new installation and I'm trying all resources. One that I couldn't find any support or explanation is the "Play a Link" menu item:

![Screen Shot 2021-03-28 at 20 42 09](https://user-images.githubusercontent.com/12404245/112780482-2af78480-9006-11eb-81dc-e44ff7db558d.jpg)

I tried the obvious and put a Youtube link, which did not work.

What is the purpose and limitations of this menu item?

**Comment by swimitup** [comment]
Also, please note the title of the page "playLink" is showing - maybe incorrectly - "Categories":

![Screen Shot 2021-03-28 at 20 47 36](https://user-images.githubusercontent.com/12404245/112781052-5b8bee00-9007-11eb-9213-d88516aab47d.jpg)

**Comment by akhilleusuggo** [comment]
I believe it must be a m3u8 url or mp4 ( source file , not link to page file )

**Comment by swimitup** [comment]
Nope, I've tried a mp4:
https://go.swim.com.br/wp-content/uploads/2020/08/julianromero.mp4
And it didn't even load any player.

**Comment by akhilleusuggo** [comment]
I actually mistaken this one with "live link" plugin .

Is does work for me ( just pasted youtube video and works ). The youtube URL must be the original video url , not always does match the one on your browser . Try right click on the video , and click copy URL . Example : https://www.youtube.com/watch?v=a5uQMwRMHcs

For me the page does load , but not the video . Anyway I also don't see use of this feature , even if the video loaded .

**Comment by swimitup** [comment]
Hi @akhilleusuggo , indeed, if I paste the Youtube URL, the page loads but no video appears: the video.js file did not recognize any video file, if there is one:

The screen:
![Screen Shot 2021-03-28 at 22 13 27](https://user-images.githubusercontent.com/12404245/112786207-fa6a1780-9012-11eb-9144-f4e94f703232.jpg)

The console:
![Screen Shot 2021-03-28 at 22 13 38](https://user-images.githubusercontent.com/12404245/112786227-0655d980-9013-11eb-95a9-08e615eb8d4f.jpg)

Anyway, I'll still wait for anyone to explain why this option exists...

**Comment by swimitup** [comment]
It seems that this tool needs other plugins to work. I activate the YouTubeAPI and now it shows a screen, but no videos playing yet.
