### ISSUE TITLE
TinyMCE language package incomplete

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#4805]
The AVideo master code doesn't have the complete language package, which triggers a javascript error if your site is using a language like pt_BR in pages which depends on the TinyMCE plugin, e.g. "myvideos" page:

![Screen Shot 2021-03-28 at 22 21 26](https://user-images.githubusercontent.com/12404245/112786646-f68ac500-9013-11eb-981a-31fcb3f06f06.jpg)

All languages package is available at https://www.tiny.cloud/get-tiny/language-packages/

Following is the zip file which you may unzip to the view/js/tinymce/langs directory.

[tinymce4x_languages.zip](https://github.com/WWBN/AVideo/files/6219175/tinymce4x_languages.zip)

**Comment by DanielnetoDotCom** [comment]
Thanks
