### ISSUE TITLE
VR360 Cross-Origin Error

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4807]
![image](https://user-images.githubusercontent.com/50199132/112799705-01bf0e80-906f-11eb-8848-c55faa5c05fc.png)

At the moment my 360-Videos wont play because of an "Cross-Origin-Error" which the plugin returns... (i am using YPTStorage)
Non-360 videos which are on the yptstorage are played correctly.

It is a problem in my configuration or from the plugin itself?

**Comment by DanielnetoDotCom** [comment]
the 360 MUST be on the same domain.

**Comment by morbificagent** [comment]
On the same subdomain?

Because my subomains are video. For the streamer and videostorage. For the yptstorage...

**Comment by DanielnetoDotCom** [comment]
I know, but this is a browser limitation. the limitation does not come from me.

**Comment by morbificagent** [comment]
No Problem you than cant do anything against this...

I was only wondering because for the normal videos I can use yptstorage but not for the vr360 files... 

It doesn't make sense in my head that's a browserlimitation as both situations seams to be the same for me.
