### ISSUE TITLE
General Settings showing users settings 2 times

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#4812]
In Admin Panel > Settings > General Settings, it shows twice the same box with same options, different titles ("Users" and "Sign In/Up"). Is it a bug? Because I couldn't understand why there are same options for different actions:

1st box:
![Screen Shot 2021-03-29 at 11 15 33](https://user-images.githubusercontent.com/12404245/112874803-9aaa5580-9080-11eb-8d50-c60a13340dad.jpg)

2nd box:
![Screen Shot 2021-03-29 at 11 15 46](https://user-images.githubusercontent.com/12404245/112874830-a138cd00-9080-11eb-8279-4964dd9f5256.jpg)

**Comment by swimitup** [comment]
Definetily a bug: if you change an option in "Users" box, when page is reloaded, the same option change in "Sign In/Up" box...

**Comment by DanielnetoDotCom** [comment]
Try to use the plugin menu instead of the admin panel.

![image](https://user-images.githubusercontent.com/18009293/112983879-90e22a00-9134-11eb-96ec-0f353a86b6ad.png)

**Comment by swimitup** [comment]
Actually I think it is better to correct the "General Settings" page... If you recommend using the plugins page, what's the point of having other page with problems during display...
