### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#4816]
Is this from debugging? 
How can I turn this on or off?
![image](https://user-images.githubusercontent.com/66537018/112926163-0b815a00-90e1-11eb-82a4-2f268b55a8b1.png)

**Comment by DanielnetoDotCom** [comment]
this is your socket plugin, for some reason, it is stopped.

I recommend you keep it running and enabled.

you can remove this widget here

![image](https://user-images.githubusercontent.com/18009293/112987985-b0c81c80-9139-11eb-91c5-fb893e6158fa.png)

**Comment by fakeologist** [comment]
where is that menu

**Comment by DanielnetoDotCom** [comment]
YPTSocket plugin

**Comment by fakeologist** [comment]
Please restart it. It says disconnected. How can I restart it?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Socket-Plugin#run-the-websocket-server
