### ISSUE TITLE
space on $global in FirstPageChannelList plugin

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#4817]
There's a space in the $global variable inside the FirstPageChannelList.php file, which causes the warning message:

` [29-Mar-2021 22:03:41 America/Edmonton] PHP Warning:  filectime(): stat failed for plugin/Gallery/style.css in /var/www/www.mysite.com/public_html/plugin/FirstPageChannelList/FirstPageChannelList.php on line 40
`
The code at line 38:
```
    public function getHeadCode() {
        global $global;
        echo "<link href='{$global['webSiteRootURL ']}plugin/Gallery/style.css?". filectime("{$global['systemRootPath ']}plugin/Gallery/style.css")."' rel='stylesheet' type='text/css'/>";
        return false;
    }

```
Must remove the space after "webSiteRootURL" and "systemRootPath" and it's fixed.

**Comment by DanielnetoDotCom** [comment]
Thanks, you were right
