### ISSUE TITLE
Internet Exploer11 can not login AVideo

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#4820]
Today I update AVideo Ver10.3-Ver10.4->Ver10.5 and AVideo-Encoder Ver3.6->Ver3.7-Ver3.8.
I tried to login AVIdeo from IE11.But I could not login AVIideo.
(I was able to login to AVideo with IE11 when I was using version 10.3.)
I had the same problem around November last year.
What changes have you made?　
Please let me know how to avoid it.

![AVideotoppage](https://user-images.githubusercontent.com/46562199/112972193-f3feab80-918a-11eb-9d25-2362f374c5b8.png)
![AVideologinpage](https://user-images.githubusercontent.com/46562199/112972211-fc56e680-918a-11eb-865b-5c9cfb7a4e5d.png)

**Comment by jengajenga** [comment]
Use a modern browser. Ditch Ex 11.

**Comment by hnagasawa** [comment]
Dear jengajenga

We need to use IE11 until August this year.
I would like to know the cause.

Do you think we need to send ***@***.***" about this issue ?

Regards
Hiroshi Nagasawa

**Comment by DanielnetoDotCom** [comment]
Check your videos directory permissions.

looks like it could not create the cache.

also, check on the HTML source code the CSS paths URL

**Comment by hnagasawa** [comment]
> looks like it could not create the cache.

I clear cache before I ran git pull

 > also, check on the HTML source code the CSS paths URL

I ran git pull only. I do not edit them.

**Comment by DanielnetoDotCom** [comment]
It is working on my side

![image](https://user-images.githubusercontent.com/18009293/113174920-412d5c80-9221-11eb-8c36-b20b441887c9.png)

Please check and share the CSS paths, also I am pretty sure it happens on any browser not only on IE

**Comment by hnagasawa** [comment]
> Please check and share the CSS paths,
Is  CSS path AVideo side  or Customer side ?

 >also I am pretty sure it happens on any browser not only on IE

This issue occure IE11 only.
I try chrome and Edge. Not ocure.

**Comment by DanielnetoDotCom** [comment]
I mean check this ...

![image](https://user-images.githubusercontent.com/18009293/113286430-93728a00-92c2-11eb-8d21-db21856bd99f.png)


check if the paths are valid
