### ISSUE TITLE
Plug in userMustbeLoggedIn On

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#4821]
When Plug in userMustbeLoggedIn On
Foe example
There are users Bob and Cherry in AVideo.
User Bob uploads a video file to AVideo with permission to share it with user Cherry.
User Bob gives the URL of this video file to user Cherry via email.
When user Cherry enters this URL into his browser, he sees
A logging screen was displayed. User Cherry logged in to AVideo with his ID and password.
User Cherry logged in to AVideo with his ID and password, but the video displayed in his browser was not the one User Bob had given him, but a different one.
This does not happen with the admin user.
Why is this?

**Comment by DanielnetoDotCom** [comment]
Does Cherry have the right to see Bob's video?

**Comment by hnagasawa** [comment]
> Does Cherry have the right to see Bob's video?

Yes

**Comment by DanielnetoDotCom** [comment]
Do you mind giving a sample URL and user so I can test and see the behavior?
