### ISSUE TITLE
Video not found if multiple dashes in name

### ISSUE THREAD

**Issue by janbiedermann** [WWBN/AVideo#4826]
**Describe the bug**
If video name is something like:
"bla-bla---bla"
the video cannot be found, if clicked from the gallery. (^cat/.../video/...)
It can be found via direct link. (^video/...)
Video name is automatically generated with multiple dashes from UI when editing video and typing something like:
"bla bla - bla bla"

**To Reproduce**
Edit video name, type soemthig like "bla bla - bla bla"
See link generated with multiple dashes
Go to gallery, click video, video not found

**Expected behavior**
Video will be found.

**Error Logs**
na

**Screenshots**
na

**Desktop (please complete the following information):**
does not matter

**Smartphone (please complete the following information):**
does not matter

**Additional context**
Problem is in objects/security.php Line 89 which mangels $_GET['videoName'] when requesting the video via ^cat/.../video/...
security.php is obviously skipped when requesting the video directly via ^video/...

**Comment by DanielnetoDotCom** [comment]
Please give a URL sample

**Comment by janbiedermann** [comment]
https://bla.tld/something/cat/important/video/bla-test---bla?channelName=Mine

**Comment by janbiedermann** [comment]
So from this example video name should be "bla-test---bla" but instead is mangled to "bla-test-bla" and db lookup by name fails.

**Comment by DanielnetoDotCom** [comment]
First, where did you get this URL from?

you suppose to have the video ID on the URL

**Comment by janbiedermann** [comment]
Thats the link from the gallery.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot on demo site where do I get a link like that?
