### ISSUE TITLE
Live-Page never shows the stream

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4828]
Tested and recorded on your demo-site which has the same problem as mine.

The stream never shows up on the live-page of the user but when he opens the link to the stream you can see it is playing...

As result the person who starts the stream thinks something isnt working as he cant see the stream on the stream-setting-page.

https://user-images.githubusercontent.com/50199132/113101038-80958200-91fc-11eb-9d4e-dceebf43a119.mp4

**Comment by DanielnetoDotCom** [comment]
BTW I am aware this player is not updating, I will fix it in future updates

**Comment by morbificagent** [comment]
OK, thanks Daniel, ti thought it was a bug...
