### ISSUE TITLE
The problem with adding ads to the site.

### ISSUE THREAD

**Issue by Proton-people** [WWBN/AVideo#4830]
**Describe the question**
A clear and concise description of what is your question.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.
Friends! please help me figure it out. My site is not verified by Google AdSense. I copied the code and added it to the ADs plugin and to the site config in the admin panel and it hasn't been working for a week now. Tell me what I did wrong. Many thanks.
![bandicam 2021-03-31 15-02-42-523](https://user-images.githubusercontent.com/48072457/113149816-79926200-9244-11eb-9a57-bdc097f98fa0.jpg)
![bandicam 2021-03-31 15-05-30-308](https://user-images.githubusercontent.com/48072457/113149837-7eefac80-9244-11eb-9aee-e5441ef479e6.jpg)
![bandicam 2021-03-31 15-03-30-583](https://user-images.githubusercontent.com/48072457/113149934-9b8be480-9244-11eb-8233-5e1fd03dc7d2.jpg)
All three options don't work. My site is not validating.

**Comment by DanielnetoDotCom** [comment]
Not sure, 

did you clear the cache?

check into the HTML source code if the script is in the correct place.

**Comment by Proton-people** [comment]
I constantly clear the cache. Here is the instruction. Am I adding this code in the right place?
![bandicam 2021-03-31 22-00-26-276](https://user-images.githubusercontent.com/48072457/113204453-57b5d100-927e-11eb-9e29-e1b5d82d0dd3.jpg)
![bandicam 2021-03-31 22-02-09-790](https://user-images.githubusercontent.com/48072457/113204509-669c8380-927e-11eb-93d3-d05f9b8f14c9.jpg)
![bandicam 2021-03-31 22-05-03-140](https://user-images.githubusercontent.com/48072457/113204556-75833600-927e-11eb-9443-92fb75e7f383.jpg)
![bandicam 2021-03-31 22-06-02-557](https://user-images.githubusercontent.com/48072457/113204570-7a47ea00-927e-11eb-9997-9d4021a56357.jpg)
If not correctly, please tell me where to add it. My site is not passing Google Adsense validation. Thanks.
