### ISSUE TITLE
For all who wants to use vaapi for the adaptive live-streams

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4831]
As i am not so good in ffmpeg but wanted to use hardware acceleration (vaapi in my case) to encode the adaptive part for the live-streams i have worked for several hours now to get a version which is running well.

So eventually this someone helps.

For sure you need hw-support for that and put www-data in the render-group so it gets access to vaapi.
Thats how i do it on ubuntu.

Then comment out the original ffmpeg-part in nginx and replace it with this one:

`exec ffmpeg -init_hw_device vaapi=foo:/dev/dri/renderD128 -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device foo -i rtmp://localhost/live/$name -c:a aac -strict -2 -b:a 128k -filter_hw_device foo -vf 'format=nv12|vaapi,hwupload,scale_vaapi=w=854:trunc(ow/a/2)*2' -c:v h264_vaapi -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 2400k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_low -c:a aac -strict -2 -b:a 128k -vf 'format=nv12|vaapi,hwupload,scale_vaapi=w=1280:trunc(ow/a/2)*2' -c:v h264_vaapi -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 4200k -bufsize 5200k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_mid -c:a aac -strict -2 -b:a 128k -vf 'format=nv12|vaapi,hwupload,scale_vaapi=w=1920:trunc(ow/a/2)*2' -c:v h264_vaapi -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 4800k -maxrate 8400k -bufsize 100000k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi;`

-> because of the hardware acceleration my cpu load goes from 70% -> 15% -> nice ;-)

BTW as you can see i am using 1920, 1280, 854 as resolutions at my site...

**Comment by jengajenga** [comment]
I will try this on my test server tonight. Thank you for this adaptation.

**Comment by jengajenga** [comment]
How did you add www:data to the render group?

**Comment by morbificagent** [comment]
You have to make sure that your hardware supports hardware acceleration for encode h264...
That's in my case the i7 CPU.

You can check with vainfo on console if vaapi is availible as it should list the encoding types which are available via acceleration.

Than add www-data to renderer group:

 usermod -aG render www-data
