### ISSUE TITLE
Backblaze issue

### ISSUE THREAD

**Issue by karlkunc** [WWBN/AVideo#4832]
**Describe the bug**
Unable to view videos on cell phone when connected to mobile network. This is a weird issue if I'm connected up to Wi-Fi on my cell phone I can upload and view videos without an issue. If I am connected to just the mobile network I can upload but I can't view videos that are up on backblaze. 
 If I turn off the back blaze plug in I can upload and view videos via my cell phone mobile Network and via Wi-Fi. But the minute I turn the plug in back on and upload a video I can only view it when I'm connected to Wi-Fi I have done this on numerous devices with the same outcome. I've even activated a mobile hotspot and connected my phone to the mobile hotspot and still I am unable to view a video that resides on backblaze. It doesn't launch the player All the time and when the player does get launched there's just a spinning working icon. I have connected to numerous cell towers and tested my speed connection both directions have at least 10mbps. Also there is a clear cash button associated with the app and when I click on it it just brings me to a blank screen. 

**To Reproduce**

**Expected behavior**

**Error Logs**
Provide the log files at the moment you found the issue.
If you are not sure how to find the log file, please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DanielnetoDotCom** [comment]
It seems to be a network/mobile problem, not a Backblaze problem

if you provide a video link here I can test it from my phone

**Comment by karlkunc** [comment]
https://tellaversion.com/video/72/01a608dc3c821f0531c38725f552bb2b?page=1&channelName=_605529b3b0c1c

Pretty much anything from this channel. But it works on Wi-Fi. And it works
when I turn off back blaze and upload locally then try to view the locally
uploaded video.

**Comment by DanielnetoDotCom** [comment]
Tested on wifi and non-wifi and works in both.

maybe something in your device

![4AB91D37-09A4-4242-85E1-D3A965F8447B](https://user-images.githubusercontent.com/18009293/113283943-4d67f700-92bf-11eb-8726-3f1fc15b0e04.PNG)
![F868E3A3-C4B4-4264-BFF6-FA8330B68BF6](https://user-images.githubusercontent.com/18009293/113283947-4e992400-92bf-11eb-93ff-ff23c70f9314.PNG)

**Comment by karlkunc** [comment]
That is truly buzzard. 3 different cell phones and one ipad mini on cell
will not play a video. Maybe it is something to do with verizon. I will dig
further on my end. Thanks.

Karl Kunc u06825M
truck 22K-682
4405509792

**Comment by karlkunc** [comment]
Thank you for your time looking into this It is not an issue with the system or with backblaze. It is something to do with Verizon I believe. Because when I turn my VPN on I can access everything on the system that is up on backblaze, But with my VPN off I cannot.

**Comment by DanielnetoDotCom** [comment]
Thanks for the update, yes, it may be something between Verizon and Backblaze network
