### ISSUE TITLE
Plugins deleted

### ISSUE THREAD

**Issue by joshuanoyce** [WWBN/AVideo#4834]
I recently purchased the video resolution switcher plugin and when I went to upload it to my site it seems to have removed all of the other plugins that were there in addition to not installing the video resolution switch plugin. How can I fix this.

**Comment by DanielnetoDotCom** [comment]
Your OS is removing it.

sorry, I do not know how to fix it, it is something you need to investigate in your server, check the syslogs.

probably is removing because it is encrypted

**Comment by JoshWho** [comment]
No that is a new glitch happening with the cache. I too have ran into this issue but just realized it wasn't loading the plugin table correctly. Once I force the site to flush all cache the plugins r visible again. 

This is a bug with cacheing

**Comment by JoshWho** [comment]
The physical files r not being deleting in other words. It is just a cache glitch
