### ISSUE TITLE
Lots of Failed Login Attempt

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#4838]
While using the encoder uploading and processing a video, the Login History tab under My Account shows a lot of "Failed Login Attempt" from the server:

![Screen Shot 2021-03-31 at 18 22 30](https://user-images.githubusercontent.com/12404245/113226753-26251180-924e-11eb-8f86-bd8f50196b30.jpg)

Is it suppose to happen or be this way?

**Comment by DanielnetoDotCom** [comment]
you can ignore the "Failed Login Attempt"

this is just a wrong message. this is regarding the email 2FA what is not complete yet.
