### ISSUE TITLE
subscription plans "planId string cannot be empty"

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#4843]
I've created a example plan. I'm not sure what suppose to be the outcome, but if you click on the "i" icon, it opens a new window with an error message.

![Screen Shot 2021-03-31 at 22 00 56](https://user-images.githubusercontent.com/12404245/113241924-eb7ea180-926c-11eb-8d78-8fac48fb4807.jpg)

object(InvalidArgumentException)#113 (7) { ["message":protected]=> string(29) "planId string cannot be empty" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(128) "/var/www/videos.nadar.tv/public_html/plugin/PayPalYPT/vendor/paypal/rest-api-sdk-php/lib/PayPal/Validation/ArgumentValidator.php" ["line":protected]=> int(28) ["trace":"Exception":private]=> array(5) { [0]=> array(5) { ["file"]=> string(108) "/var/www/videos.nadar.tv/public_html/plugin/PayPalYPT/vendor/paypal/rest-api-sdk-php/lib/PayPal/Api/Plan.php" ["line"]=> int(331) ["function"]=> string(8) "validate" ["class"]=> string(35) "PayPal\Validation\ArgumentValidator" ["type"]=> string(2) "::" } [1]=> array(5) { ["file"]=> string(67) "/var/www/videos.nadar.tv/public_html/plugin/PayPalYPT/PayPalYPT.php" ["line"]=> int(111) ["function"]=> string(3) "get" ["class"]=> string(15) "PayPal\Api\Plan" ["type"]=> string(2) "::" } [2]=> array(5) { ["file"]=> string(119) "/var/www/videos.nadar.tv/public_html/plugin/Subscription/page/plansInfo.json.php(18) : eval()'d code(1) : eval()'d code" ["line"]=> int(20) ["function"]=> string(14) "getPlanDetails" ["class"]=> string(9) "PayPalYPT" ["type"]=> string(2) "->" } [3]=> array(3) { ["file"]=> string(100) "/var/www/videos.nadar.tv/public_html/plugin/Subscription/page/plansInfo.json.php(18) : eval()'d code" ["line"]=> int(1) ["function"]=> string(4) "eval" } [4]=> array(3) { ["file"]=> string(80) "/var/www/videos.nadar.tv/public_html/plugin/Subscription/page/plansInfo.json.php" ["line"]=> int(18) ["function"]=> string(4) "eval" } } ["previous":"Exception":private]=> NULL }

**Comment by DanielnetoDotCom** [comment]
I guess this info is only for PayPal payments
