### ISSUE TITLE
Live Users Not saving views 

### ISSUE THREAD

**Issue by antuk21** [WWBN/AVideo#4846]
views won't save I have saved them on to any help please thanks

**Comment by DanielnetoDotCom** [comment]
Hi, it now resets in any live.

every time you start a new live the counter resets;

is that what you mean?

**Comment by antuk21** [comment]
they are not showing at all. only the view counter works  not total views

**Comment by antuk21** [comment]
got a lot off error to for some reason 
![error  logs](https://user-images.githubusercontent.com/74247098/113316346-2254c600-9306-11eb-8a1e-8c62e843890f.png)

**Comment by antuk21** [comment]
![ffddfg](https://user-images.githubusercontent.com/74247098/113316556-5fb95380-9306-11eb-93b3-53725394d974.png)

**Comment by antuk21** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/74247098/113317116-f554e300-9306-11eb-96b7-42f7ddadf06d.png)

**Comment by DanielnetoDotCom** [comment]
Restart your socket server

**Comment by antuk21** [comment]
i restart it and now my socket wont work at all says cant find the ssl  this error below

ant@ant:~$ php /var/www/html/AVideo/plugin/YPTSocket/server.php
AVideoLog::DEBUG: Starting Socket server at port 2053 SCRIPT_NAME: /var/www/html/AVideo/plugin/YPTSocket/server.php
Searching for port: 2053
sh: 1: findstr: not found
No Need to kill, port NOT found
Starting AVideo Socket server version 2.5 on port 2053
SSL ERROR, we could not access the CRT file /etc/letsencrypt/live/www.mrsweeney.live/fullchain.pem, try to run this command as root or use sudo
SSL ERROR, we could not access the KEY file /etc/letsencrypt/live/www.mrsweeney.live/privkey.pem, try to run this command as root or use sudo
Your socket server uses a secure connection
Parameter [local_cert]: /etc/letsencrypt/live/www.mrsweeney.live/fullchain.pem
Parameter [local_pk]: /etc/letsencrypt/live/www.mrsweeney.live/privkey.pem
Parameter [allow_self_signed]: 1
Parameter [verify_peer]:
Parameter [verify_peer_name]:
Parameter [security_level]: 0

**Comment by antuk21** [comment]
Notice: Undefined offset: 1 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76

Notice: Undefined offset: 3 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76

Notice: Undefined offset: 2 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76
[2021-04-01 22:50:12]  NOT SECURE CONNECTION  CONNECTION FAIL ://:0 Connection closed before handshake

Notice: Undefined offset: 1 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76

Notice: Undefined offset: 3 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76

Notice: Undefined offset: 2 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76
[2021-04-01 22:50:12]  NOT SECURE CONNECTION  CONNECTION FAIL ://:0 Connection to localhost:2053 failed during TLS handshake: Connection lost during TLS handshake

Notice: Undefined offset: 1 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76

Notice: Undefined offset: 3 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76

Notice: Undefined offset: 2 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76
[2021-04-01 22:50:12]  NOT SECURE CONNECTION  CONNECTION FAIL ://:0 Connection closed before handshake

Notice: Undefined offset: 1 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76

Notice: Undefined offset: 3 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76

Notice: Undefined offset: 2 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76
[2021-04-01 22:50:12]  NOT SECURE CONNECTION  CONNECTION FAIL ://:0 Connection to 127.0.0.1:2053 failed during TLS handshake: Connection lost during TLS handshake

Notice: Undefined offset: 1 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76

Notice: Undefined offset: 3 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76

Notice: Undefined offset: 2 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76
[2021-04-01 22:50:12]  NOT SECURE CONNECTION  CONNECTION FAIL ://:0 Connection closed before handshake

Notice: Undefined offset: 1 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76

Notice: Undefined offset: 3 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76

Notice: Undefined offset: 2 in /var/www/html/AVideo/plugin/YPTSocket/test.php on line 76
[2021-04-01 22:50:12]  NOT SECURE CONNECTION  CONNECTION FAIL ://:0 Connection to www.mrsweeney.live:2053 failed during TLS handshake: Unable to complete TLS handshake: SSL operation failed with code 1. OpenSSL Error messages: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
[2021-04-01 22:50:12]  We found 0 possible configurations:

**Comment by antuk21** [comment]
fixed

**Comment by partystreamsk** [comment]
how you fixed it? i have the same problem but no errors in log.
