### ISSUE TITLE
How to translate the rating of videos?

### ISSUE THREAD

**Issue by fxp66** [WWBN/AVideo#4848]
Is it possible to tranlate the rating terms of videos?
Thx for quick reply

**Comment by DanielnetoDotCom** [comment]
Can you please screenshot from where exactly you are talking about?

**Comment by fxp66** [comment]
Excuse me for beeing unclear, her is a screenshot
![screen-1](https://user-images.githubusercontent.com/40458047/113317426-a5c6e500-930f-11eb-91f4-e5dee5edd5d4.jpg)
I have to translate it into german

**Comment by DanielnetoDotCom** [comment]
If you are looking to only translate the "Not Rated"

add this in your translation/locale file...

$t['Not Rated'] = 'Your translation';

**Comment by fxp66** [comment]
Excuse me for asking silly questions, you answered this qustion already in a thread before.
Works great! Thx
