### ISSUE TITLE
Found strange behavior when transcoding and publishing video

### ISSUE THREAD

**Issue by SergejGrin** [WWBN/AVideo#4849]
I congratulate everyone on the upcoming holidays and wish you good Easter days!

Found strange behavior when transcoding and publishing video:
I add video to the encoder and start the encoding process. 
<img width="1863" alt="Снимок_экрана_2021-04-01_в_15_00_50" src="https://user-images.githubusercontent.com/59236880/113307710-bb371180-9305-11eb-9d8a-d43d5e772199.png">
The encoder works without errors and the video is published, but after transcoding and transfer to the "My Videos" section.
<img width="1863" alt="Снимок экрана 2021-04-01 в 15 01 18" src="https://user-images.githubusercontent.com/59236880/113307910-ed487380-9305-11eb-99b3-c4cd3bfb5664.png">
On the previous version (before updating the version to 10.5), in this section I could immediately observe the process of processing the video file - now no.
<img width="1880" alt="Снимок_экрана_2021-04-01_в_15_22_15" src="https://user-images.githubusercontent.com/59236880/113309027-0aca0d00-9307-11eb-8bdf-cbc84f6b21d7.png">
After transcoding the video, instead of one title with different resolution files, I get THREE separate publications. In this case, the encoder does not add an image file and a GIF file to the video file. For some reason, the name of the video being published is taken from the original file, and not what I write when filling out the task to the encoder.
<img width="1880" alt="Снимок_экрана_2021-04-01_в_15_23_57" src="https://user-images.githubusercontent.com/59236880/113308188-37c9f000-9306-11eb-8fdc-1c86929aa92f.png">
I ask for advice and clarification - why is this happening and what is it connected with?

**Comment by DanielnetoDotCom** [comment]
Please check the encoder and streamer logs.

**Comment by SergejGrin** [comment]
I'll try to add this video again. The previous three attempts gave the result indicated in the question.

**Comment by SergejGrin** [comment]
Miracles! Found on the network another similar file in mp4 And the encoding process is now displayed in the 'My Videos' section. Apparently the problem was in the quality of the encoding of the source file. Is that possible?
<img width="1880" alt="Снимок экрана 2021-04-01 в 17 10 06" src="https://user-images.githubusercontent.com/59236880/113315700-d9087480-930d-11eb-8893-a7c80ff7c679.png">

**Comment by SergejGrin** [comment]
Here are the encoder and streamer logs.
What was the problem there?
[avideo-encoder.log](https://github.com/WWBN/AVideo/files/6245285/avideo-encoder.log)
[avideo.log](https://github.com/WWBN/AVideo/files/6245287/avideo.log)

**Comment by DanielnetoDotCom** [comment]
The only error I can see is that you have a misconfigured encoder network

If you want to use the encoder network you must use this https://github.com/WWBN/AVideo-Encoder-Network

**Comment by SergejGrin** [comment]
Thank you for your reply. I installed the Avideo version according to this manual - this is the second server on which your wonderful platform is installed.
https://www.linuxbabe.com/ubuntu/install-avideo-youphptube-ubuntu-20-04-server 
But now I am at a loss - what and how to fix ... How to fix this problem? Remove and reinstall the encoder?
Or are there other options?

**Comment by DanielnetoDotCom** [comment]
@SergejGrin what is the problem?

anyway, remove and install the encoder is easy

**Comment by SergejGrin** [comment]
Thank you Daniel. Is there any manual (preferably in detail and step by step) how to correctly remove the existing encoder and install a new one? As I understand it, the task here will concern the database.

**Comment by DanielnetoDotCom** [comment]
Drop the database and delete the configuration.php file.

that is it, run the installer again.

**Comment by SergejGrin** [comment]
Thank you Daniel, did everything as you recommended. I noticed an interesting thing:
I am trying to edit the file name of a video, as it somehow abbreviated with ellipses instead of letters. But when I try to save the changes, the save process happens without error, but the file name does not change. Are there any restrictions on the length of the file name? Or is it somehow related to the use of the Cyrillic alphabet?
1.  <img width="1105" alt="Снимок экрана 2021-04-04 в 20 31 54" src="https://user-images.githubusercontent.com/59236880/113518322-f3e51e00-9585-11eb-9e74-a88e7bb50aec.png">
2.  <img width="1389" alt="Снимок экрана 2021-04-04 в 20 33 25" src="https://user-images.githubusercontent.com/59236880/113518431-9e5d4100-9586-11eb-8a78-1c5c77c9279a.png">
3.   <img width="1786" alt="Снимок экрана 2021-04-04 в 20 34 37" src="https://user-images.githubusercontent.com/59236880/113518443-af0db700-9586-11eb-8fd9-a660a818f819.png">
4.   <img width="1105" alt="Снимок экрана 2021-04-04 в 20 31 54" src="https://user-images.githubusercontent.com/59236880/113518452-bc2aa600-9586-11eb-846e-c896893996c3.png">

**Comment by DanielnetoDotCom** [comment]
Correct, there is a limit on the title length.

I do not have it on the top of my mind, but I guess it is 255 chars (special chars consume more than one char per letter)

**Comment by SergejGrin** [comment]
Thanks for the quick reply, I will take this limitation into account.
