### ISSUE TITLE
Restrict playlist / programs by geoip location?

### ISSUE THREAD

**Issue by lerd2805** [WWBN/AVideo#4850]
Hi dear friend @DanielnetoDotCom god bless you,

There is the possibility to restrict playlist / programs or videos by geo IP location?

If this functionality exists, how I do it?

And if you haven't thought about adding it soon?

**Comment by DanielnetoDotCom** [comment]
No, but I can develop one.

If you are interested, send an email to developer@youphptube.com for a quote
