### ISSUE TITLE
Who is notified?

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4851]
As I often don't understand who is notified when I have configured this and that (while using the Notification plugin too) it would be great to list the possibilities and the configuration that has to made.
I think I have understood some scenarios but eventually I don't ;-) 

So it would be great of Daniel or someone else can explain it to me and others:

**LIVE** :
1. Configuration: User goes on his live-config-page and says "Make stream Public" and starts streaming.
   1.1 the stream is shown on the first page for all users
   1.2 a mail notification is sent to all who subscribed him
   1.3 oneSignal pushes a notification to all users (or only to the one who subscribed?)

2. Configuration: User goes on his live-config-page and says "Make stream Public" and he selects a specific usergroup and starts streaming
   2.1 the stream is shown where? Eventually only on the first site of the users inside the group?
   2.2 a mail notification is sent do all who subscribed him, or only to the users inside the usergroup?
   2.3 oneSignal pushes a notification to all users (or only to the one who subscribed? Or only to the users in the group?)

3. Configuration: User goes on his live-config-page and says NOT "Make stream Public" and he selects a specific usergroup and starts streaming
   2.1 the stream is shown where? Eventually only on the first site of the users inside the group?
   2.2 a mail notification is sent do all who subscribed him, or only to the users inside the usergroup or to nobody?
   2.3 oneSignal pushes a notification to all users (or only to the one who subscribed? Or only to the users in the group? Or to nobody?)

Very confusing I think....

**Comment by JoshWho** [comment]
It is not a complex notification system yet will be in the future. For now Emails will send out to the correct subscriber for what they subscribed to.

OneSignal push notifications right now at the moment only does sitewide notifications for every channel to all users. So the Push notify would not be recommended if you allow others to upload because they too will send out push notifications to everyone.

**Comment by morbificagent** [comment]
@Josh thanks for Thema info...

But like I understood from another thread I need to set a live-stream to "make stream public" even if I select a group which has the rights to view it for make any notification happen...

So it looks like "Emails will send out to the correct subscriber for what they subscribed to" is not always true of do I misunderstood this?

**Comment by JoshWho** [comment]
If Live stream is not set public meaning just Viewable then it will not send out a notification
