### ISSUE TITLE
Live Links Stream Always says offline

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4853]
![62ff6383-748c-4bb5-bb09-fc2914fe4eef](https://user-images.githubusercontent.com/39392449/113385716-4805bd80-934e-11eb-9b09-e379141495b2.png)

**Comment by DanielnetoDotCom** [comment]
Hi, please get the last commit from yesterday night and let me know again

**Comment by JoshWho** [comment]
Just ran the git pull and cleared all the cache still showing offline
![543ac860-aa22-48dd-ac4c-de4d0324cac5](https://user-images.githubusercontent.com/39392449/113419854-e7967080-938d-11eb-9831-dd64c3072686.png)

**Comment by JoshWho** [comment]
This is live links not the regular live

**Comment by DanielnetoDotCom** [comment]
If you allow me I will check it directly into your site
Can I update you on everything?

**Comment by JoshWho** [comment]
kk and yes please

**Comment by DanielnetoDotCom** [comment]
I see it is a livelink, livelinks should be always online, I am sending a fix

**Comment by JoshWho** [comment]
Looks great now.  Thank you
![4e702d63-62f8-4c74-ab67-2544ffc7c0c7](https://user-images.githubusercontent.com/39392449/113421673-1feb7e00-9391-11eb-8adf-85d264e0761b.png)
