### ISSUE TITLE
Chat under video on mobile only

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4854]
Hi Daniel,

The chat2 plugin with a static right layout works great on Desktop computers for me as they often have 16:9 screen ratios...

But on mobile we normally have 9:16 ratios so it should be possible to configure the plugin that the chat is under the video in the case of mobile.

But it looks like all settings in the plugin I make arent reflected/working on mobile... And a separate layout setting like "under video on mobile" isn't there too.

So I only can get this default minimized bubble layout:

![Mobile Chat](https://i.imgur.com/3zJqeKb.jpg)

Would it be possible to make a button for "under video on mobile" and make the button to NOT "start minimized on mobile work again?

So we would have the possibility to use the "static right" for desktop and "under the video" for mobile.

**Comment by DanielnetoDotCom** [comment]
this for sure will be a new development, but what you are expecting is not clear to me

**Comment by morbificagent** [comment]
The benefit would be that my users could use the chat while they are looking at the stream on mobile.

At the moment they have to touch on the chat-bubble and the chat window expands over the video. So they can decide to chat or to watch the stream.
But if the chat would be under the video on mobile (and the space for this is there while using it the normal 9:16 way) they could use it while watching.

**Comment by morbificagent** [comment]
Looked how twitch does it and its exactly the same like my whish.

The chat is static right at desktops and under the video on mobile so its usable while watching:

![Twitch chat under Video](https://i.imgur.com/V8uKOnl.jpg)

**Comment by DanielnetoDotCom** [comment]
Twitch has a really nice look, I may try to improve our plugin later in future updates

**Comment by morbificagent** [comment]
That would be great Daniel :-)

Have a nice day!
