### ISSUE TITLE
Live Links Default Thumbnail

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4855]
Would like to replace the live generated thumbs with a static thumb. I do not display most live links because they have issues generating thumbs some times. This would solve that.

**Comment by DanielnetoDotCom** [comment]
try this new update, I sent 10 min ago

**Comment by DanielnetoDotCom** [comment]
BTW, you will need to update the LiveUsers plugin

**Comment by JoshWho** [comment]
Updated and Looks terrific Daniel. Love it 😃😃😃😍 Thank you

![7b8542c7-1c65-44dc-ba89-17e4f197f00a](https://user-images.githubusercontent.com/39392449/113444392-6b198700-93b9-11eb-80e5-1a2613096db2.png)

**Comment by morbificagent** [comment]
@JoshWho can see you have NASA live on you page... Can't find an m3u8 of that... Do you have one? :-)
