### ISSUE TITLE
Add Live Links to the TV Guide just make it show 24/7 stream all hours

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4856]
I want to normalize the use of live links by also including it in the TV module and just show its channel tv guide as 24/7

**Comment by DanielnetoDotCom** [comment]
It should work, do you have any sample link that does not work?

**Comment by JoshWho** [comment]
I am talking about the new EPG that is still being developed and the TV app.

**Comment by JoshWho** [comment]
That way the Live Links can also be selected channels users can watch in the TV lineup.
