### ISSUE TITLE
Playlist/Program Play-As-Live bug

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4858]
1. I select some videos
2. I put them in a playlist i created
3. I click play as live.
4. Doesn't play
5. Error is _"127.0.0.1 - - [02/Apr/2021:11:58:17 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f (internal dummy connection)"_

Because dummy connection cannot talk to SSL, it needs to be non-SSL.

How can we resolve?

Thanks.

**Comment by DanielnetoDotCom** [comment]
This feature is not finished yet

**Comment by jengajenga** [comment]
ok
