### ISSUE TITLE
Button "Show More" missing in description

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#4862]
Hi
Sometimes  the button "Show More" is missing in description. Is it possible to disable this button ?
Thanks.

![Snap1](https://user-images.githubusercontent.com/39981177/113470323-1592b800-9455-11eb-8465-02725de9b824.jpg)

**Comment by DanielnetoDotCom** [comment]
I could not reproduce it here, can you reproduce it on demo site?
