### ISSUE TITLE
MP4ThumbsAndGif

### ISSUE THREAD

**Issue by Social-Loafer** [WWBN/AVideo#4863]
I just updated my server from 8.2, plus updated the plugins, and now all the "mouse over poster (WebP)" are created from the same spot at the beginning of the videos which do not show anything worth seeing, how can i change the timings for the auto creation of the posters?
or is there a way to change the site to display the "mouse over poster (GIF)" instead of the (WebP) version, those ones seem to be working as they were before.

Thanks for your time.

**Comment by DanielnetoDotCom** [comment]
All the images are created at the time you use the encoder to process the video.

**Comment by Social-Loafer** [comment]
Yes I understand that , but  before, the "mouse over poster" was of content that was 20 or seconds into the video, now  its content of the very beginning of the video which is not useful. 
can it be fixed? can i modify that myself?

**Comment by Social-Loafer** [comment]
I found a work around. Deleted all the .webp files in the video directory so the site is forced to use the .gif files for the "mouse over poster". Would be nice if i didn't have to do this though.
