### ISSUE TITLE
after last git pull a can no longer access plugins

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4865]
plugins is no longer viewable for me after last update

**Comment by jengajenga** [comment]
site no longer accessible for me

**Comment by JoshWho** [comment]
ran it and it seems like the cpu shot up and i have no clue what iot is doing

**Comment by DanielnetoDotCom** [comment]
Check the streamer logs

**Comment by DanielnetoDotCom** [comment]
Josh, I can see too many redirects on your page (the jquery.js file). 

now the CDN is also used on the js and CSS files

**Comment by DanielnetoDotCom** [comment]
Josh I just sent some update to the code and add this in your configuration file:

`$global['ignoreCDN'] = 1;`

Check if it is loading faster now.

if $global['ignoreCDN'] = 0 it will use the CDN for all static files, looks for me you had some misconfigured redirects.

**Comment by DanielnetoDotCom** [comment]
I am not sure what happen but everything is smoother now on @JoshWho site

**Comment by DanielnetoDotCom** [comment]
I have noticed you had a bunch of videos upload at that time. and seems to me it consume most of your bandwidth and resources 

Just guessing, that may be the reason

**Comment by JoshWho** [comment]
No I turned off al CDN and it still does it. seems like there is open compilation of php going on and not serving the cache anymore

**Comment by JoshWho** [comment]
I see a lot of traffic with websockets going on when I have everything in full operation

**Comment by JoshWho** [comment]
This has been my cpu status ever since the last git pull 

![bd49fa12-d166-4d16-abfe-4062d9dd6c89](https://user-images.githubusercontent.com/39392449/113502809-234b4a80-94f4-11eb-9ffc-5c2ef8d28ff7.png)

**Comment by DanielnetoDotCom** [comment]
So if you stops the socket does the CPU goes down?

**Comment by JoshWho** [comment]
It wont let me switch it off I just get stuck on the loading page.

![e6773061-1f7c-4f06-9f17-5ce8ecbadce3](https://user-images.githubusercontent.com/39392449/113507891-b1cec480-9512-11eb-8fb5-b46949e6084a.png)

**Comment by DanielnetoDotCom** [comment]
I mean kill the pid using the socket port

**Comment by DanielnetoDotCom** [comment]
Just turnoff the plugin is not enough

**Comment by JoshWho** [comment]
Ok yup seemed to be a problem non related to the update. Had other sites causing the issue wordpress related.
