### ISSUE TITLE
PHP FATAL ERROR

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4866]
Hi @DanielnetoDotCom , @akhilleusuggo 

could you kindly urgently help with this?

[Sat Apr 03 20:06:55.593582 2021] [proxy_fcgi:error] [pid 2426403:tid 139726132594432] [client xxx.xxx.xxx.xxx:53284] AH01071: Got error 'PHP message: PHP Warning:  require_once(../../videos/configuration.php): failed to open stream: No such file or directory in /var/www/xxx/plugin/Live/m3u8.php on line 3PHP message: PHP Fatal error:  require_once(): Failed opening required '../../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/xxx/plugin/Live/m3u8.php on line 3'

Currently my site says UNDER MAINTENANCE which means it cannot see/access/use the configuration file.

I've restarted apache2, php as well but nothing and there are no solutions online anywhere.

**Comment by DanielnetoDotCom** [comment]
Please update to this push

**Comment by jengajenga** [comment]
> Please update to this push

Done.

Still seeing the same error.

**Comment by DanielnetoDotCom** [comment]
Can you please copy and paste the new errors here?

should be something new
