### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#4868]
Response when trying to download a video. "downloadHLS was not possible" 
No Console output

**Comment by DanielnetoDotCom** [comment]
Check your log file, it will tell you the reason why you could not download

**Comment by swimitup** [comment]
same problem of https://github.com/WWBN/AVideo/issues/4889#issuecomment-816191080

**Comment by DanielnetoDotCom** [comment]
The @ganddser problem was because he was using the YPTStorage, and this feature requires FFMPEG installed on the storage as well.

**Comment by swimitup** [comment]
> The @ganddser problem was because he was using the YPTStorage, and this feature requires FFMPEG installed on the storage as well.

Good to know. So maybe my #4889 problem is also related to encoder location, is it not possible?

**Comment by DanielnetoDotCom** [comment]
The encoder has FFMPEG by default, but I guess in your case it is trying to use the streamer, what also will need FFMPEG to allow the HLS download
