### ISSUE TITLE
Site is sluggish even with no users, and sometimes changing a videos featured status breaks things badly

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4869]
**Describe the bug**
Manipulating metadata, sometimes we find the spinning animation for long periods of time doing things like toggling the "featured" star.

Sometimes, toggling that thing causes the site to spin lock - even closing down that browser window all subsequent attempts from the same browser are failing until I kill the apache process. (Yes, launching a different browser can open a session - it's the instance of Apache that gets locked)

**To Reproduce**
1. Go to My Videos
2. Click on a ⭐️
3. Sometimes, you watch the spinner
4. Occasionally you have to reload the page because you assume after 30-60 seconds that it's not coming back...
5. But the page never reloads
6. You have to log into the box
7. Run top
8. and look for the stuck apache process
9. sudo kill -9 it
10. then, that computer will be able to connect to the site again
11. otherwise you're just waiting for the browser to timeout - repeatedly

**Expected behavior**
It not do that

**Comment by DanielnetoDotCom** [comment]
Check the log files for the apache process hanging.
