### ISSUE TITLE
Status oft CDN Integration :-)

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4870]
@DanielnetoDotCom 

Because im very interested in your cdn integration i wanted to ask how is the state of that...

In another thread i saw that you have enabled this for an other user so it looks like you arent so far away from "its working" ;-)

And which cdn do you use at the moment? A free one?

Thanks for the info

**Comment by DanielnetoDotCom** [comment]
Hi, will not be a free one. we have a partner provider but I am still under development.

**Comment by morbificagent** [comment]
OK, thanks for the info and have a nice evening

**Comment by morbificagent** [comment]
As i was reading a little bit here i saw that the use of a CDN is possible since last year like i was reading in the wiki...

But you speaking about "under development" so whats the difference to the possibilities which seams to be already there?

**Comment by DanielnetoDotCom** [comment]
The one I am developing will be basically a one-click configuration, just signup and enable it. it will work for VOD videos (including S3, B2, FTP, and YPTStorage) and live VIdeos

**Comment by morbificagent** [comment]
Sounds good! Waiting for it...

So its possible to use a CDN for VOD and Live Videos at the moment too but not with "one click" right?

**Comment by akhilleusuggo** [comment]
CDN with Live stream no. Very few CDN does accept rtmp. You can make yours with reverse proxy. I tried make mine , it works on my home server, but having issues with setting a proper ssl certificate setup.

**Comment by DanielnetoDotCom** [comment]
If you notice on the demo site, the lives over there are already on a CDN

**Comment by morbificagent** [comment]
@akhilleusuggo did you mean the way OBS -> AVideo? Because this would be the rtmp-part.

But for the viewers the live isnt rtmp as it is hls (in my case).

**Comment by DanielnetoDotCom** [comment]
also, OBS,  if you start an OBS stream it will go to the origin (the live server) and you will have the edge CDNs. check the source URL, you will see it is the CDN.
In the future, I will have more details.

**Comment by morbificagent** [comment]
Tested it a few minutes ago.

Changed my site to using cdn for all aspects: mainsite, yptstorage and live and its working great!

**Comment by morbificagent** [comment]
@DanielnetoDotCom or anybody else: 

how did you solved the problem with the CDN-caching from adaptive live streams?

The problem is:
All viewers are requesting the newest hls-fragment at the same time. Of course because otherwise it wouldnt be live.
Therefore the cache control is set to "none" in nginx like in the wiki.

Result:
The CDN doesnt cache the stream because of this.
For sure its working but it makes no sense if the cdn cant cache.
The networkload on my server isnt better with using a cdn for live.

Was reading some articles about an "Origin-Assist CDN-Prefetch" but thats a little bit to high for me at the moment.

So, has anybody a solution for this? Do i miss something?

**Comment by akhilleusuggo** [comment]
@morbificagent yes I meant that. But also , few CDN providers ( usually expensive ) does cache `.ts` files.
It's just a question of time for me to make it work, and open a new repository for people who may wanna try it. Is not the type of dream CDN, but for RTMP is fine. Obviously I'm having issues with the Server Live ( plugin section ).

I'm trying to make it work without changing anything on the AVideo code, just pure nginx, rtmp-nginx and reverse proxy nginx.

**Comment by morbificagent** [comment]
@akhilleusuggo havent tried much cdn's but the one i have selected a few days ago (bunny) isnt expensive and has no problem with serving .ts files.
On top there is a video optimization option for free which saves longer videos in 5mb chunks for better handling by the cdn.

And the configuration with avideo was easy and i havent changed anything in the avideo code.
Done in 15min ;-)

**Comment by akhilleusuggo** [comment]
I would be interested to see the config ( for my reverse proxy ). My entire goal is learning and deployment purposes for now. 

Reverse proxy the YPT-storage would be the easiest for sure , specially if they're `.ts` files. No idea if it's possible to cache the mp4 ( specially if they're heavy ). An entire download of the file would be required to cache ( like clustering ) , rather then just caching the portion that have been requested/downloaded by the client.

**Comment by DanielnetoDotCom** [comment]
Hi, you guys are right, in my case I had to enable the DVR feature with `hls_playlist_length`

and also make sure you ONLY DO NOT CACHE the m3u8 file

check the  `location ~ \.m3u8$`  section


                  location /live {
                            location ~ \.m3u8$ {
                                # Disable cache
                                add_header 'Cache-Control' 'no-cache';

                                # CORS setup
                                add_header 'Access-Control-Allow-Origin' '*' always;
                                add_header 'Access-Control-Expose-Headers' 'Content-Length';
                            }

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }

**Comment by morbificagent** [comment]
;-) My Config looks the same.

For a little bit better hit-rate i have set the hls-fragments to a higher value (18s) so the viewers need mor time to load them. With this extra-time the cdn has more possibilities to use his cache.

For the complete configuration look here:
[https://video.bit-link.de/video/621/avideo-make-use-of-a-cdn-bunny?channelName=TakeALookAt](url)

**Comment by DanielnetoDotCom** [comment]
Agree, increase the hls-fragments may be better, but why 18s not 20s or 30s?

**Comment by morbificagent** [comment]
Thats because of the keyframes and my ffmpeg-config.

Every fragment needs to have a keyframe at the beginning for sure and it looks like its done right in your encoder too.
There everything is configured for 6sec... so if i cut my fragments at 6, 12, 18,... i dont have to change much of your original-config.
If i would cut on 30s the keyframes would be somewhere in every fragment and i could get problems with playing them well.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Something I've explained here and requested, but sadly ignored :(
It's crucial for HLS plugin and live-stream. Without it any HLS will be broken , buffer or playlist loop. 

The key-frames and hls fragment  time without them the stream breaks.

@morbificagent No, the key-frame is not limited by time only , and you're not forced to use 18. A stream with 18s gonna have a delay of over 30s. You can have keyframes inside of hls_fragments. 

Example if you want to have 30s of hls_fragment with _low_ keyframes. ( create key-frame every 2s )

`ffmpeg -i source -c:v libx264 ........ -r 30 -g 60 -hls_time 30 ............`

Example if you want 30s hls_fragment with _high_ keyframe .

`ffmpeg -i source -c:v libx264 ........ -r 30 -g 150 -hls_time 30 ............ ( create key-frame every 5s )`

`ffmpeg -i source -c:v libx264 ........ -r 30 -g 300 -hls_time 30 ............ (create key-frame every 10s )`

Note, lowering the key-frames will increase the video size. We could create a key-frame/s but the size would almost double. 

I made one git pull to be followed but it has been ignored.
`-hls_time` is really bad on most of the script encoder that we have in this project . I think developers doesn't understand it well . This value has no meaning what so ever and the script will give errors on playlist and in cases completely ignore it.
1- You can't set hls_time without indicating a valid GOP ( `-g` )
2- GOP must be your output frame rate * 2
3- The hls_time must be **_GOP/FrameRates=hls_time_**

Example ;  
-r 60 -g 120 -hls_time 2  ( valid values )
-r 60 -g 240 -hls_time 4 (valid value , _HIGH_ latency stream )
-r 30 -g 30 -hls_time 1 ( valid value , _LOW_ latency stream )

-r 20 -g 48 -hls_time 6 ( wrong values , a lot of buffering and weird/unstable hls_playlist , if not completely ignored . The seek bar gonna just be confused , and you can't seek the playlist anymore).

**Comment by DanielnetoDotCom** [comment]
Hi @akhilleusuggo 

did you make a pull request regarding this? Your knowledge is quite valuable to me. please show me where is it.


I loved your samples, let say we want to do the Low latency

-r 30 -g 30 -hls_time 1 won't this increase the Disk IO too much?

what values are you using for your own?

**Comment by morbificagent** [comment]
@akhilleusuggo thanks for the explanations, looks like you have much more knowledge than me in configuring ffmpeg/hls.

I will review my config now ;-)
