### ISSUE TITLE
When enabling CHat2 on CHannels it doesn't appear right.  Needs a different place holder for channel page

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4872]
I have the static template where live chat is built into the right side of the live stream video playing.

When I enable CHat on CHannels it just keeps chat at the top. Is there a way to make chat go to bottom right or something on channel page for desktop While still keeping it set in the static template?

![ee18a04d-c33b-4431-ad50-2dd9ae3369f8](https://user-images.githubusercontent.com/39392449/113521920-444a8480-9562-11eb-804e-3532f2ff9ca2.png)

**Comment by DanielnetoDotCom** [comment]
weird, what type of layout are you using?

![image](https://user-images.githubusercontent.com/18009293/113573476-9803af00-95f0-11eb-8437-085ba25462a6.png)

**Comment by JoshWho** [comment]
Static Fixed on RIght
