### ISSUE TITLE
In My Videos list, I'd like an indicator of which files I've added subtitles to, and which ones I have not

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4873]
**Is your feature request related to a problem? Please describe.**
It would be super helpful in workflow to have an indicator of which files I've added subtitles to, and which ones I haven't

**Describe the solution you'd like**
Adding subtitles to long series, you can forget where you were and have to click around to find where you left off.
A column indicating presence/absence/(numerical quantity?) would be helpful, as would sorting on this column.

**Comment by DanielnetoDotCom** [comment]
When you have subtitles you can see this

![image](https://user-images.githubusercontent.com/18009293/113573927-7820bb00-95f1-11eb-876f-894894819b11.png)

and this 

![image](https://user-images.githubusercontent.com/18009293/113573957-8a025e00-95f1-11eb-9483-b20652c6459c.png)

**Comment by walt93** [comment]
Yes. I have thousands of videos. I'm trying to subtitle a subset of them.

I need a workflow to group things together by attributes, such as "has/doesn't have CC" 

Example, I have a series of 60 programs. Not uploaded at the same time, they appear scattered throughout. I did a handful on one day. On the next I want to come in and continue where I left off. The application is a hindrance to this workflow.

Thanks for listening.

**Comment by DanielnetoDotCom** [comment]
I guess will not be possible to filter by Subtitle. 

Subtitles are requested only after the video is loaded. there is not subtitle information saved on the database.
