### ISSUE TITLE
In My Videos list, I'd like a column to indicate Group Membership, and a column to indicate Status

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4874]
**Is your feature request related to a problem? Please describe.**
Problem is I have a lot of videos that have been put into different categories and would be great for reasons related to I didn't know that the effect of my marking 800 videos unlisted would be so they disappeared into the aether and I that I have to page through thousands of videos trying to deal with each of these individually is a drag…

**Describe the solution you'd like**
Extra columns we can toggle on and off, default them to off is fine.

**Describe alternatives you've considered**
A more powerful search with options to find all in group, all visible/unlisted/etc would be the killer workflow app!

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/113574094-c9c94580-95f1-11eb-9ec0-ff47e405ffb5.png)

**Comment by walt93** [comment]
Yes, this gives me the ability to see what is assigned to a group for an individual video. 

I have 3,800 videos and want to find 300 of them by group. How to do this? There is no workflow, only paging through hundreds of pages looking for, and trying to edit individually. It would *almost* be easier to delete every video from the site and re-upload (what I'm saying - this workflow is giving me nightmares)

1) Promote this to a column. Let me sort by it so all videos are grouped together by it. 
2) Better: let me filter by it.

**Comment by DanielnetoDotCom** [comment]
Currently, we do not have a filter by user group. we may add this in the future.
