### ISSUE TITLE
Site "sluggishness" comes and goes, seemingly cyclical - related to DB?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4875]
**Describe the question**
I'm in the process of mass encoding, editing metadata, direct importing mp3s and PDFs, occasionally finding I've uploaded duplicates and deleting, adding descriptions, tags, subtitles, setting up next video, etc.

What I find is that at times doing any of these operations normally takes milliseconds and will get increasingly slower - such that when you're doing a manual file upload that has four steps your workflow goes from a couple of seconds to 30-40.

I'm speculating this is a database issue, and its running its own optimizer to dig itself out of its hole every few hours?

Is there anything we can do to help it? It's really struggling sometimes..

**Comment by JoshWho** [comment]
U have to calculate ram usage to as big as the file is for example, if you upload a 10 gig video file then you need at least 10 gigs of ram for this to process. Almost the same as the IO process but it is with ram.

**Comment by milehighkaraoke** [comment]
Fixed mine by updating to Groovy gorilla Ubuntu 20.10 and php 8.3 along with updated nginx module 1.7.6  I believe that's the numbers
