### ISSUE TITLE
Favorites can't be viewed

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#4876]
Hi,

Favorites and Watch later doesn't redirect you to page where you can view your favorites.

You can reproduce it on demo site:

https://demo.avideo.com/favorite

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that, here is an update

**Comment by tonuzo** [comment]
Thanks it works, but you can't add favorites any more. If you click the heart (favorite) symbol it doesn't add the video to favorites.

**Comment by tonuzo** [comment]
Sorry, I noticed the favorites playlist was updated anyway. So it works, there might still be some cache issue because the playlists wasn't updated immediately.  But thanks again.
