### ISSUE TITLE
S3 plugin throwing Uncaught Error: Class 'Aws\\\\S3\\\\S3CLIENT' not found. 

### ISSUE THREAD

**Issue by trutube-live** [WWBN/AVideo#4878]
**Describe the bug**
When testing S3 plugin I get the following error:

 AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Class 'Aws\\\\S3\\\\S3Client' not found in \\/DATA\\/website\\/html\\/YouPHPTube\\/plugin\\/AWS_S3\\/AWS_S3.php(18) : eval()'d code(1) : eval()'d code:197\\nStack trace:\\n#0 \\/DATA\\/website\\/html\\/YouPHPTube\\/plugin\\/AWS_S3\\/test.php(18)

**To Reproduce**
1. Go to Marketplace buy S3 plugin
2. Go to Plugins on the site and upload S3 zip plugin.
3. Configure the plugin to use wasabi per instructions.
4. Click on the test button and see "Under Maintanance(misspelled in webpage) Sorry for the inconvenience."
5. See error in apache error log file.

**Expected behavior**
I expect the plugin to work or give better failure instructions on how to fix.  
Encrypted plugin so I can not see where it breaking other than there is a call to class that is not present in either of my systems.  The self hosted and the paid hosting sites both show this error.  

**Error Logs**
AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Class 'Aws\\\\S3\\\\S3Client' not found in \\/DATA\\/website\\/html\\/YouPHPTube\\/plugin\\/AWS_S3\\/AWS_S3.php(18) : eval()'d code(1) : eval()'d code:197\\nStack trace:\\n#0 \\/DATA\\/website\\/html\\/YouPHPTube\\/plugin\\/AWS_S3\\/test.php(18)

**Comment by DanielnetoDotCom** [comment]
Hi, please check the logs around this error, must be some clue.

usually, this is related to some misconfiguration with the credentials.

**Comment by trutube-live** [comment]
That is an unacceptable error report for bad creditials...if the creditials
fail you should report failed to login ...not uncaught error..

And you like to blame other products..
