### ISSUE TITLE
ffmpeg -re flag do not create adaptive streams

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#4879]
There are some configuration conflicts in nginx.conf available in this repository.

From https://raw.githubusercontent.com/WWBN/AVideo/master/plugin/Live/install/nginx.conf found in https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server, we have this:

```
exec ffmpeg -re -i rtmp://localhost/live/$name 
    -c:a aac -strict -2 -b:a 96k -c:v libx264 -vf scale=-2:240 -re 20 -g 40 -keyint_min 40 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1400k -b:a 96k -f hls -hls_time 2 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_low  
    -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:480 -re 30 -g 60 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 4200k -b:a 128k -f hls -hls_time 2 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_mid  
    -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:720 -re 30 -g 60 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 3000k -bufsize 6000k -b:a 128k -f hls -hls_time 2 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi;

```

From adaptive bitrates, https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream, we have this:

```
                        exec ffmpeg -i rtmp://localhost/live/$name 
                            -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:240 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1200k -b:a 96k -r 20 -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_low  
                            -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:480 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 2400k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_mid  
                            -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:720 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 4200k -bufsize 100000k -b:a 128k -f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi;

```

Was struggling for many hours trying to make adaptive bitrate works. And when I copy and paste a nginx.conf file from other issue (#3447), it worked. So I start debugging the nginx.conf file and found out if you remove the -re flag, the adaptive stream works.

From FFMPEG documentation (https://trac.ffmpeg.org/wiki/StreamingGuide):

_The -re flag
The FFmpeg's "-re" flag means to "Read input at native frame rate. Mainly used to simulate a grab device." i.e. if you wanted to stream a video file, then you would want to use this, otherwise it might stream it too fast (it attempts to stream at line speed by default). My guess is you typically don't want to use this flag when streaming from a live device, ever._

So I'm not sure if it is a hardware problem (streaming device and/or server) or the correct exec string is indeed without "-re"...

**Comment by DanielnetoDotCom** [comment]
I am not sure why you do not support -re 

on my side it works fine
