### ISSUE TITLE
Total video count no longer displays after latest gitpull

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#4881]
Latest git pull reset my total video count and now no longer displays total video count 
![Screenshot_20210405-222528_Samsung Internet](https://user-images.githubusercontent.com/70327833/113658919-3e39ce00-965e-11eb-9ab5-0ca280491f57.jpg)

**Comment by DanielnetoDotCom** [comment]
Please update the streamer (again) also the LiveUsers plugin
