### ISSUE TITLE
LiveLinks are not played while using http->https proxy.php

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4882]
Hi together/Daniel,

trying to add a Stream to my https-site which is http on the source...
So the proxy.php should be used as i havent disabled it in the plugin-settings.

But it wont connect:
![image](https://user-images.githubusercontent.com/50199132/113674816-e8474380-96ba-11eb-93ff-fd83d0ef1907.png)

**Comment by morbificagent** [comment]
OK, found it...:

![image](https://user-images.githubusercontent.com/50199132/113677330-bf747d80-96bd-11eb-8387-058083f67489.png)

So the proxy.php servers the m3u8 but dont serve the .ts files which are inside. So they are accessed without using the proxy.php and so without using https and the desktop browser reject this for sure.

But i dont understand

A) Why its working on my mobile as there should be the same problem
B) Why the proxy in LiveLinks only serve the m3u8 but not the .ts files as it would be useless like that

**Comment by DanielnetoDotCom** [comment]
Make sure your m3u8 link is also https, otherwise it will not play
