### ISSUE TITLE
Purchased like 3-5 plugins which i now only can download 1?

### ISSUE THREAD

**Issue by jakesullyneytiri** [WWBN/AVideo#4883]
Noticed i lost around 3-4 plugins after purchaseing 3-5 plugins at https://youphp.tube/marketplace/

I would like to have access to download ones i paid for! Not going to re-purchase since that would be rip off if you have to purchase again.

So please give me other plugins back!

Update: strange after refreshing the page it brought the plain login back, so now i was able to login to old account where i had these paid plugins on. So it seems to be solved for now.

**Comment by DanielnetoDotCom** [comment]
Hi, yes you can download them, maybe you log in with a different account.

please send your email and username to developer@youphptube.com also your User# and I may find your purchases and transfer them to one account
