### ISSUE TITLE
livestream quallity bad

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#4885]
Hi i have startet a livestream and shared my screen but the quallity is bad.
Also via webcam is the quality bad the users can not see the documnet i have shared.

Ubuntu 18.4 all latesst updates

**Comment by DanielnetoDotCom** [comment]
Hi, is it using meet or OBS?

**Comment by 01123581321345589144233** [comment]
meet

**Comment by DanielnetoDotCom** [comment]
The meet depends on your connection for the resolution. try to switch servers (NA/EU).

I have my eyes open on jitsi to whenever they improve their quality. I depend on them for this.

**Comment by tonuzo** [comment]
I have noticed the same problem. The video resolution lowered in some point. Now the max resolution on meet is 320x200px. Weeks ago it was at least 3x better...

**Comment by 01123581321345589144233** [comment]
when i stream with obs the resolution is ok when i stream with the meeting the resolution is bad, @DanielnetoDotCom i have setup my own jitsi is there a option for i can use my own jitsi in the avideo ?

**Comment by DanielnetoDotCom** [comment]
@01123581321345589144233 the jitsi to work with avideo must be customized on the source code.
sorry but this Jitsi/Avideo is not opensource

**Comment by tonuzo** [comment]
I noticed when there is more than 2 people on the same meet, the resolution drops from 1280x720px to 320x180px.
