### ISSUE TITLE
What is "Live Info" for?

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4886]
![image](https://user-images.githubusercontent.com/50199132/113871279-06906a80-97b3-11eb-9398-bdf5ac9a11d6.png)

If i click on it i  only get to the normal live-publish-page...
But its under every video so it looks like there was another idea with that.

**Comment by swimitup** [comment]
I have the same curiosity.
For all videos, the button only show for admins. And all onclick action are the same:

`document.location = 'http://your-site/plugin/Live/?users_id=1';`

which leads to the live streaming control page. Seems not correct.

**Comment by akhilleusuggo** [comment]
@morbificagent it takes you to the streamer page of the uploader . This way you can edit or check rtmp url , key of the users .

> If i click on it i only get to the normal live-publish-page...
> But its under every video so it looks like there was another idea with that.

**Comment by morbificagent** [comment]
Ah its the live page of the uploader! Thanks I missed that.
