### ISSUE TITLE
Paid videos can be viewed freely if you are not logged in!

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#4887]
Hi

I have a BIG problem. Videos can be viewed even they are in behind PPV or Subscription. 

You can view them if you are not logged in. If you are logged in you can't view them.

Please help!

**Comment by tonuzo** [comment]
Can reproduce on Flix site

**Comment by DanielnetoDotCom** [comment]
WOW, thanks for notice that is was a problem with the cache system
I just sent an update that the admin's cache, logged users and non logged users will have their caches separated

**Comment by tonuzo** [comment]
Thanks but I'm sorry, It's still broken.  Same result.

**Comment by DanielnetoDotCom** [comment]
Sorry, once more you were correct, please update now.

**Comment by tonuzo** [comment]
Now the problem is fixed, but it brought along a new problem. 

When trying to watch a purchased PPV video it redirects you to "choose a plan" page (plugin/Subscription/showPlans.php) 
And the video can't be viewed.

**Comment by tonuzo** [comment]
https://github.com/WWBN/AVideo/issues/4161

It's similar to this old issue

**Comment by DanielnetoDotCom** [comment]
Please try this new update

**Comment by tonuzo** [comment]
It works thanks! 

Still I don't know if it's related but some videos don't start after play. Console gives this looping warning. After I clear the cache it works but when i try to load the page again this happens: 

![image](https://user-images.githubusercontent.com/63721378/114088741-003ae500-98be-11eb-941a-e83eef81d0de.png)

**Comment by DanielnetoDotCom** [comment]
this looks an encode problem on this video

**Comment by tonuzo** [comment]
Ok. This happens occasionally with some videos. After cache clear it works again for a while...
