### ISSUE TITLE
cant live stream on localhost

### ISSUE THREAD

**Issue by antuk21** [WWBN/AVideo#4888]
is there a way to stream from my  domain on Nginx  some days it works on localhost other times I get server not found  bit annoying 
https://prnt.sc/116p9u3

**Comment by 5tubb0rn** [comment]
I have a similar issue. OBS says that it's connected but I still can't see the stream.

**Comment by antuk21** [comment]
try yours on localhost may work when I try my domain it works but don't show live any where same as you

**Comment by DanielnetoDotCom** [comment]
this means the nginx could not access the on_publish.php

or maybe the keys ar invalid
