### ISSUE TITLE
Notification Plugin notifies on inactive videos

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4893]
Hi @all 

actually i am using the notifications-plugin and would love to inform the subscribers when there is a new Video:

![image](https://user-images.githubusercontent.com/50199132/113992138-70605100-9853-11eb-844c-4d0787ca0502.png)

But i have configured that new videos (and so live-recordings too) are disabled after upload so that i have the possibility to write descriptions, change poster-images and make the article looks good before i mark it as "Active".

As result if i enable the notification and upload a video the subscribers are notified that there is a new video online but if they klick on the link they get the errormessage that it is inactive (for sure because it is).

So i think it is nessesary to change the notification plugin to only notify after i have set the video to "active" and not if its inactive...

Has someone an idea how i can reach this at the moment and @DanielnetoDotCom is it possible to change that behavior as it makes no sense like it is at the moment.

**Comment by DanielnetoDotCom** [comment]
You are 100% correct, in the future, I may add a button to manually notify all subscribers
