### ISSUE TITLE
How to disable ''watching now" ?

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4895]
I would like to disable watching now . I don't find it useful , since they're not live-stream , and doesn't bring any information . Could be useful only for admins logged in .

Also in late updates , it does make ( specially the home page ) load really slow compared to how it was before .
I understand that now does give accurate results , and it's not cached anymore , and that's why I'm asking if there's anyway to complexly disable this option . ( **disable** , _not hide_ )

**Comment by DanielnetoDotCom** [comment]
Try this

![image](https://user-images.githubusercontent.com/18009293/114087859-bdabe500-988a-11eb-8127-13d03d3bc672.png)

**Comment by akhilleusuggo** [comment]
sadly it does only hide , does not disable it . I didn't knew that this feature was part of a plugin . 
For now I'll disable it . Too heavy .

![image](https://user-images.githubusercontent.com/52116577/114101887-0eddc800-98cf-11eb-8bbe-98342978138f.png) loading ...

**Comment by morbificagent** [comment]
> EDIT : Actually it doesn't work . Doesn't even hide . I though it was cache issue , but it's not .

Can confirm: am not able to disable that for VOD videos too

**Comment by DanielnetoDotCom** [comment]
Hi

This update + LuveUsrs v3.3 may resolve that

**Comment by morbificagent** [comment]
@DanielnetoDotCom 
Jep its gone from the home page.
But inside the VOD videos its there...

So like the option is named it should be removed there too:

![Screenshot_20210410-230230_Chrome.jpg](https://user-images.githubusercontent.com/50199132/114284627-77ed4900-9a51-11eb-831c-ae0dcbe17840.jpg)

**Comment by akhilleusuggo** [comment]
like I've said before , one of the things that I hate about plugin developments on this projects and feature , is that you can NOT disabled them . All this features inside of plugins they just ''hide'' the feature from the public , they don't disable them . Still consuming server's resources for no reason .

**Comment by DanielnetoDotCom** [comment]
Sorry, you were right, I am sending version 3.4 that should resolve that

**Comment by morbificagent** [comment]
Its optical gone.

Thank you Daniel!
