### ISSUE TITLE
Plugin Customize , under maintenance 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4897]
After adding some custom css ( most likely the wrong ones ) , the site goes under-maitenance .
1- Reseting the `php resetPlugins.php` doesn't work when site under maintenance ;
2- I was forced to manually delete the plugin directory under `/plugins/customize/`
3- I can't reset just this plugin , I'm forced to reset all plugins .

```
install$ sudo php resetPlugins.php 
1 - Reset all plugins Parameters
2 - Reset CustomizeUser Plugin Parameters only
3 - Reset all plugins (Will also inactivate the plugins)
Choose an option:
```

How do I remove the lines that I've added ? Because definitely they're not stored on the AVideo directory , must be on the database side . But I don't know where exactly that value is . On the install side ;

```
CREATE TABLE IF NOT EXISTS `extraConfig` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `about` TEXT NULL,
  `description` VARCHAR(255) NULL,
  `footer` TEXT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
```
On the database side ; 

```
mysql> SHOW COLUMNS from extraConfig;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| about       | mediumtext   | YES  |     | NULL    |                |
| description | varchar(255) | YES  |     | NULL    |                |
| footer      | mediumtext   | YES  |     | NULL    |                |
| created     | datetime     | YES  |     | NULL    |                |
| modified    | datetime     | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
6 rows in set (0.00 sec)
```

**Comment by DanielnetoDotCom** [comment]
try 

`truncate extraConfig`

**Comment by akhilleusuggo** [comment]
so basically drop it , is the only solution .

**Comment by akhilleusuggo** [comment]
Edit , didn't help .  Still under maintenance .

**Comment by akhilleusuggo** [comment]
Can you tell me how to manually disable a plugin ? Any command line ?

**Comment by akhilleusuggo** [comment]
I had to run a backup , but this is really bad ...

**Comment by DanielnetoDotCom** [comment]
Sorry, I just see the last massage. of was under maintenance, it was a 500 error, it should be on the log file, or maybe apache log file, if reset the customize plugin does not work, I do not know what was that

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom If you wanna give it a try on a VM , you can go and add wrong code css on the customize css file. Save clear the cache. You gonna be stuck.

**Comment by DanielnetoDotCom** [comment]
Can you please give me a sample of a "wrong CSS code"?

**Comment by akhilleusuggo** [comment]
I just added a normal css code. But I believe it does not accept css like in wordpress or normal scripts, since it's bootstrap and I have no experience with that. I just wanted to customize some colors, such as background. The plugin is not very descriptive since you gave weird names to some elements.

But the reason why I wanted to change the css, is because I like one of the pre-made themes, but not the color itself.
Maybe the issue is coming from a static theme + customization. Maybe not supported?

**Comment by DanielnetoDotCom** [comment]
I see, I will try

regarding the names, they use bootstrap names
