### ISSUE TITLE
Pageload_time first page for mobile users slow ?

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#4899]
The pageload_time of the first page only is slow on mobile devices with slow internet.
It can be a visual effect of the white page from the last update that is no showing images.
Users told me so i tried the latest update with the update before with limited internet speed with
both cleared browser cache. Running on a fast Intel i7 with Virtual Box. 
I don't know but could the pageload_time being speed up skipping the *_thumbsSmallV2.jpg files
so users see directly the image. They can click on the video_image instead of waiting untill the page is loaded ?
I tried https://github.com/WWBN/AVideo/issues/4693 but i see no changes.

**First video**: BEFORE updating Avideo

https://user-images.githubusercontent.com/39981177/114155930-4fb2fc80-9922-11eb-9a87-c40d0512daf0.mp4

**Second video**: AFTER updating Avideo

https://user-images.githubusercontent.com/39981177/114157665-2b581f80-9924-11eb-83e6-12192463c492.mp4

Testing with **SLOW** internet speed

https://user-images.githubusercontent.com/39981177/114158149-aae5ee80-9924-11eb-821c-49ad9987a6d8.mp4

**Comment by morbificagent** [comment]
![image](https://user-images.githubusercontent.com/50199132/114164493-a83ac780-992b-11eb-800d-d2ac169b4547.png)

![image](https://user-images.githubusercontent.com/50199132/114164593-c4d6ff80-992b-11eb-8d47-ad152a672891.png)

As you have a download-rate of about ~1Mbyte/s its clear why its loading such long...

The first one is you Background which is about 10MB -> 10sec then there are several other gif's with about 2MB per file...
I dont know how you got this background-video as i am relatively new to avideo... is there a config-possibility for that?

![image](https://user-images.githubusercontent.com/50199132/114164923-27c89680-992c-11eb-8311-46ad52fd1a0c.png)

And if i compare it with my site there are .webp-files instead of .gif-files which are much smaller... dont know why i have .webp and you .gif but i would remove the Background-Video first.

**Comment by TLCReuver** [comment]
I tested it also with *.gifs disabled but there is only a litlle difference for the first view to select a video (not for full loading_page).
Indeed, the background.gif of 10mb can be changed in webp which is smaller. 
I create the *.gifs by hand to select the hotspot of that video whicht i upload for that video. Converting to webp files would be better.

But the difference of page_load between the last version en the version before is tested under the same conditions.
Therefore my question...can "pageload_time being speeding up skipping the *_thumbsSmallV2.jpg files
so users see directly the image. They can click on the video_image instead of waiting untill the page is loaded" ?
Maybe there is a good reason doing this way,

Thanks for your reply

**Comment by TLCReuver** [comment]
I tested it also with *.gifs disabled but there is only a litlle difference for _the first view_ to select a video (not for full loading_page).
Indeed, the background.gif of 10mb can be changed in webp which is smaller. 
I create the *.gifs by hand to select the hotspot of that video whicht i upload for that video. Converting to webp files would be better.

But the difference of page_load between the last version en the version before is tested under the same conditions.
Therefore my question...can "pageload_time being speeding up skipping the *_thumbsSmallV2.jpg files
so users see directly the image. They can click on the video_image instead of waiting untill the page is loaded" ?
Maybe there is a good reason doing this way,

For the background_video i put little script in "Website configuration/Scriptcode" in your left Menu

```
<style type="text/css">
* {
  box-sizing: border-box;
}
body {
  margin: 0;
  font-family: Arial;
  font-size: 14px;
  background: url(/images/Video_13.gif) no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}

```
Thanks for your reply.

**Comment by morbificagent** [comment]
Thanks for the info as it looks nice with a (small) video behind ;-)

But i dont know why it loads longer after the update. I think Daniel has changed the way of displaying the thumbs in the last days like i saw in the commits. Lets see what he says...

**Comment by morbificagent** [comment]
![Screenshot_20210410-154837_Firefox.jpg](https://user-images.githubusercontent.com/50199132/114271953-443ffe00-9a14-11eb-9e9f-7698429e0624.jpg)

Whats about this setting? Have you enabled that?

**Comment by TLCReuver** [comment]
With this script you can play a background video but old browsers have problems with this snippet.

```
<style type="text/css">
* {
  box-sizing: border-box;
}
body {
  margin: 0;
  font-family: Arial;
  font-size: 14px;
}

#myVideo {
  position: fixed;
  right: 0;
  bottom: 0;
  min-width: 100%; 
  min-height: 100%;
 z-index: -100;
}
</style>

<video autoplay muted loop id="myVideo">
  <source src="/images/Video_13.mp4" type="video/mp4">
  Your browser does not support HTML5 video.
</video>
<script>
var video = document.getElementById("myVideo");
</script>

```

**Comment by TLCReuver** [comment]
Thanks for your snapshot, i didn't find it in the update_before

![Snap1](https://user-images.githubusercontent.com/39981177/114294479-3be0d500-9a9f-11eb-8a42-4bc5245f60ae.jpg)

In the new update it is present and when enabled it feels that pageload_time is 5x faster when you have slow internet and the website is not cached in the browser before.

I think when there there was an option to disable the blur_effect then it feels more faster on the first page because you can see the picture. You don't have to wait until the full page is loaded and how often do you have slow internet on mobile devices. 

I see Daniel is working on it  and maybe this would be a nice feature.

**Comment by TLCReuver** [comment]
Since the last update everything is smooth now.
Th@nkz
