### ISSUE TITLE
Watermark doesn't work

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#4905]
The watermark item from the SecureVideosDirectory plugin does not work, if I chose one video to be dinamically watermarked, the video does not load; if I deactivate the option "watermark it" from the myvideos page, the video does play.

Chrome inspection:

![Screen Shot 2021-04-10 at 21 08 03](https://user-images.githubusercontent.com/12404245/114291040-60a65f80-9a41-11eb-9f73-707e77483a23.jpg)

Options from the plugin:

![Screen Shot 2021-04-10 at 21 09 47](https://user-images.githubusercontent.com/12404245/114291042-6a2fc780-9a41-11eb-86e2-fe2419f2d325.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, the watermark should work, but it still experimental. I really recommend you to use only for testing propose.

check your encoder logs, the files are watermarked there.

**Comment by swimitup** [comment]
But I only use the dynamic watermark, I'm not using the encoder for hard-watermarkering the video.

**Comment by DanielnetoDotCom** [comment]
dynamic watermark requires a good encoder

**Comment by swimitup** [comment]
As I could see in browser console, dynamic watermark simply added a CSS/JS code to prompt briefly the user IP/ID every x seconds on top of the video...

**Comment by DanielnetoDotCom** [comment]
I see, there are 2 types of watermarks.

one that uses CSS and another one that will dynamically encode some HLS segments with the client IP (more secure)

![image](https://user-images.githubusercontent.com/18009293/114703090-3f709800-9cfb-11eb-8a69-5e3957cd1f79.png)

The CSS one is pretty simple and supposes to work easily. but the encoder one still experimental.
