### ISSUE TITLE
After using the site for some time, I am finding many videos are pointing to the wrong one and can't be fixed. Help!!!

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4908]
**Describe the bug**
So far I have found a number of videos that have all been swapped behind the scenes to point to one video lets call them ABCD and E. Every time I click on another video, in fact, I am finding that it points to this same video - lets call this video "F".

The first two, I attempted to upload a fresh copy of the same video, and swap them. After the swap? The original file remains pointing to "F".  None of the files ABCD or E can be fixed by swapping.

In frustration, I deleted "F". Now I'm continuing to go through the list of 3,800 videos that I've uploaded, and I keep finding more and more videos that are in this state.

[NOTE: I'm finding this because the encoder has so many issues, at least 5% of my files won't play despite that they generate previews and thumbnails - Work flow is: I'm going through the top videos that my users are trying to watch on my broken site looking for files that won't play - and I'm finding so far now a dozen of these files with broken database entries]

**To Reproduce**
No idea what we did to get here

**Expected behavior**
It not do this. 

HOW DO I GET OUT OF THIS MESS?!?

**Comment by DanielnetoDotCom** [comment]
I am not sure what is happening with you, but I can tell you if you swap videos while the encoder still transferring you will have problems.

before swap, check if the video is not transferring on the encoder side

**Comment by DanielnetoDotCom** [comment]
BTW, I checked your videos here https://conspyre.tv/ and they play to me.

**Comment by walt93** [comment]
I'm not sure what I did, I had about 30 videos in total that were all swapped and pointing at, about 2/3 pointing to one file, and the rest pointing at another. The files that suffered weren't ones that I had explicitly tried to swap. Not sure what happened...

**Comment by DanielnetoDotCom** [comment]
I am not sure too, just make sure you do not swap videos while they are being transferred on encoder

**Comment by walt93** [comment]
I've got another one. I've never tried to swap this video. I have not tried to swap videos for a while now (once burned, twice shy...)

I just noticed when I load the page, that it's rendering the poster frame from another video. It doesn't play. It used to play, I verified it when I uploaded it. I verify them all when I upload them now.  It's got 19 page views, don't know if it played for the other 18 users or not.

If I go to this videos page from an admin account, I can download the MP4 and WEBP and they play correctly.

Here is the page for the video in question.

https://conspyre.tv/video/4898/democrats

I keep finding these. My site is not stable. I do not know what to do. 

Please advise.

**Comment by DanielnetoDotCom** [comment]
I just send some updates for the encoder and streamers. I could fix multiple bugs regarding file transfer.

please update and try again

**Comment by walt93** [comment]
With some trepidation, done. The above referenced file is still broken, linked to the wrong file. Deleted. Re-uploaded. Seems to work for now. For the last file, the damage occured some time after uploading/metadata'ing/verifying playback and uploading a number more files.

After updating, I uploaded a video, went add one English subtitle file, and on saving - here's a fresh regression for you. I'm super bummed, my current workflow involves subtitles.

Where do I find release notes, list of tags, releases, named branches, something so I can back out to a stable revision?

![Screen Shot 2021-04-29 at 9 21 11 PM](https://user-images.githubusercontent.com/11711050/116648344-a0ba7d00-a931-11eb-8c9a-afee8e15eff6.png)
![Screen Shot 2021-04-29 at 9 22 38 PM](https://user-images.githubusercontent.com/11711050/116648356-a912b800-a931-11eb-9ef4-1fef65ad5630.png)

**Comment by DanielnetoDotCom** [comment]
Hi, please make sure you are running the latest AVideo (v10.8) and SubtitleSwitcher (v2.8) plugin version

**Comment by walt93** [comment]
I've downloaded the latest plugins from the plugins page. From the plug-ins page I've uploaded them. I've restarted apache2. What am I missing?

**Comment by walt93** [comment]
Also I've recently upgraded via git pull - where in the app do I see the version?

**Comment by DanielnetoDotCom** [comment]
can you please share the link with the wrong subtitle here so I can inspect it?

**Comment by walt93** [comment]
Sure, it seems that I cannot fix this problem, but maybe you can answer another question, I can't also seem to find how to update plugins. I can go to the download page. I can upload the plug-in again. But they remain stuck at the old version.

I just added subs to this one, it's showing an [ARRAY] https://conspyre.tv/video/4956/04-water-1280x720

**Comment by DanielnetoDotCom** [comment]
THis is what I see in your subtitle

![image](https://user-images.githubusercontent.com/18009293/117349421-bd9b0700-ae81-11eb-9788-448d5f49b3b5.png)

**Comment by walt93** [comment]
Yes. When you look at the contents of that subtitle it shows this: 
![Screen Shot 2021-05-06 at 2 59 39 PM](https://user-images.githubusercontent.com/11711050/117370762-bb35ae80-ae7b-11eb-9f1d-06e81683cf36.png)

Also, note that Safari is not rendering that as [CC].

Did you see my question?

How do I update plug-ins?

**Comment by DanielnetoDotCom** [comment]
To update the plugin you need to download it and uplaod again
https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin

**Comment by walt93** [comment]
Done, and updated, and done. 😅
