### ISSUE TITLE
Finding more and more videos that have corrupted database entries - pointing to the wrong file. HELP!

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#4909]
**Describe the bug**
Clicking to load the page for a video is loading a page which contains the expected metadata, but is pointing at the wrong video.

When you find these, they cannot be fixed by "Swap video", you simply have to delete them and note the number of views from your frustrated users trying to watch this.

**To Reproduce**
1. Decide to commit thousands of dollars on your hobby project of creating a video site
2. Spend every spare moment over two months uploading videos
3. Go through the painstaking process of checking thousands of videos - I've probably checked <300
4. We are up to over 30 that won't play at all (encoder bugs)
5. So far we are up to 13 videos that are swapped, the first 12 were all pointing at the same file, call it "F"
6. video #13 in this category is swapped with a different file, not the same as the first 2

**Expected behavior**
It not do that.

**Error Logs**
Log files were multi-gigabyte, then whacked and subjected to rotation. Whatever damage caused this is lost.

PLEASE HELP!!!

**Comment by DanielnetoDotCom** [comment]
This looks related, lets keep on that https://github.com/WWBN/AVideo/issues/4908
