### ISSUE TITLE
Download files

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#4911]
Hello,
is there any way to stop downloading videos from this downloader?
**1DM: Fastest Video, Torrent Downloader & Browser**
https://play.google.com/store/apps/details?id=idm.internet.download.manager&hl=el&gl=US

Thank you
Ilias

**Comment by jakesullyneytiri** [comment]
you could try adding secure folder plugin or use so called backblaze b2 plugin and enable private mode, that shall hopefully block download of videos with an app since app does not have auth key to access the video.

**Comment by DanielnetoDotCom** [comment]
If you use HLS format they should not be able to download.

**Comment by wetubeclub** [comment]
Hello,
thank you for your answers
all videos are in HLS format only some are in .mp4 I will look at it better and come back with an update!

Thank you
Ilias
