### ISSUE TITLE
Webp files giving vanguard clip

### ISSUE THREAD

**Issue by jakesullyneytiri** [WWBN/AVideo#4912]
How do i get rid of VANGUARD short video in webp? since it is causing all videos to show this VANGUARD shit and not gif or correct preview clip of video when mouse hovering over a video.

**Comment by DanielnetoDotCom** [comment]
Are you talking about VOD videos or live videos?

**Comment by jakesullyneytiri** [comment]
> Are you talking about VOD videos or live videos?

none, these are appearing on plain videos, for example when i upload mkv or mp4 it puts this VANGUARD preview clip on mosue over. Which is making it awful.

**Comment by DanielnetoDotCom** [comment]
They can be only VOD, or Live or embed, I will assume you are talking about VOD

if you are uploading to the encoder and you are getting the vanguard image, you may have problems with the encoder process

**Comment by jakesullyneytiri** [comment]
> They can be only VOD, or Live or embed, I will assume you are talking about VOD
> 
> if you are uploading to the encoder and you are getting the vanguard image, you may have problems with the encoder process

encoding process are fine, only webp are ones not willing to work and gives vanguard. rest works fine video and such.

**Comment by DanielnetoDotCom** [comment]
check your encoder logs, maybe your FFmpeg does not support webp conversion.

check what FFmpeg version are you running

**Comment by jakesullyneytiri** [comment]
> check your encoder logs, maybe your FFmpeg does not support webp conversion.
> 
> check what FFmpeg version are you running

i got following ffmpeg version 4.2.4
