### ISSUE TITLE
Incomplete Code Sharing embeded

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#4916]
When I try to embed my stream from the embedded share the final code is missing the stream number so I have to manually type in the stream number after I copy and paste the code. The stream is online when I try to share the code and still I have to manually enter the stream number. I highlighted on the picture where the stream number is missing
![20210412_212807](https://user-images.githubusercontent.com/70327833/114493800-6da98700-9bd8-11eb-816d-4fdbd05c3690.jpg)

**Comment by milehighkaraoke** [comment]
This is what it should look like. I am also up to date 10.7 on streamer and encoder is also up to date. 
![20210412_214821](https://user-images.githubusercontent.com/70327833/114494115-fd4f3580-9bd8-11eb-872d-162437aa85f2.jpg)

**Comment by DanielnetoDotCom** [comment]
This update should fix that

**Comment by milehighkaraoke** [comment]
This did add a stream number but it's not the correct  number. I have to manually change the number to get the embedded site to work.

**Comment by milehighkaraoke** [comment]
This is what it propagates 
![20210413_160035](https://user-images.githubusercontent.com/70327833/114626943-a77a9c00-9c71-11eb-9eda-63ad9e1da62f.jpg)

**Comment by milehighkaraoke** [comment]
This is what I have to use for it to work
![20210413_160054](https://user-images.githubusercontent.com/70327833/114627002-c2e5a700-9c71-11eb-87a7-d4125d5cd627.jpg)

**Comment by milehighkaraoke** [comment]
I am getting this number 170532 by clicking directly on the live stream link and looking at the url.
![Screenshot_20210413-160654_Chrome](https://user-images.githubusercontent.com/70327833/114627381-66cf5280-9c72-11eb-9a51-787f3da77ed7.jpg)

**Comment by milehighkaraoke** [comment]
Also is there a way to hide that broadcast number from showing in the live stream . It should only show the broadcasting title......

**Comment by milehighkaraoke** [comment]
And by streaming live with this url it does not send it to the encoder after broadcast is over. It does send it to encoder with the other number but you can not view it live.

**Comment by milehighkaraoke** [comment]
Fixed this entire issue by turning off the multi stream in live user plugin
