### ISSUE TITLE
Live User Plugin total user not calculating 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#4917]
Total user not calc
![Screenshot_20210412-215442_Firefox](https://user-images.githubusercontent.com/70327833/114494822-3b992480-9bda-11eb-8361-c443829e1ef6.jpg)
ulating live user plugin 3.3
Live plugin  7.1

**Comment by DanielnetoDotCom** [comment]
Please update the live users to V3.4 also make sure your socket is running

**Comment by milehighkaraoke** [comment]
Update to 3.4 plugin did the trick.
