### ISSUE TITLE
Restream per user

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4919]
@DanielnetoDotCom hi,

How far along are you with making restream for each user like meet, stream and upload? Is it something you are working on?

Also can there be how many restream sites per user? So that i can limit my users to only 1 or 2 sites and if they want more maybe i can add as well.

Thanks.

**Comment by DanielnetoDotCom** [comment]
Hi

I did not understand your question. the restream is per user

**Comment by jengajenga** [comment]
> Hi
> 
> I did not understand your question. the restream is per user

@DanielnetoDotCom , what I mean is this, see the screenshot. no restream for individual user. restream is for all users. can we have so that we can activate it for each individual user?

![per-user](https://user-images.githubusercontent.com/65451390/114569553-c1ba7700-9c7d-11eb-9799-49305f9b6235.png)

**Comment by jengajenga** [comment]
@DanielnetoDotCom ... what do you say?

**Comment by DanielnetoDotCom** [comment]
Hoo, I see, 

you want the option to tell who can restream and who cannot. it makes sense to me.
It may be developed in the future but we do not have it right now.

If you want to develop it now you can hire our services directly on my email developer@youphptube.com
