### ISSUE TITLE
Restream and Multiple Live

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4920]
@akhilleusuggo , @DanielnetoDotCom  hi

I have a question about this

If I have 3 livestreams going on from the same account, and I also decide to do a restream, which livestream out of the three will go to the restreamer?

Is there a way to separate them or differentiate them say by doing restream per livestream per user?

**Comment by DanielnetoDotCom** [comment]
Hi, 

all 3 livestream will restream to the same server.
to stream to a different one you need another acocunt

**Comment by jengajenga** [comment]
Thanks. 

What will it take to separate them? Is it something you can put in the development pipeline?

**Comment by milehighkaraoke** [comment]
Separate them by creating a user account for every stream and turn off multiple streams in live user plug-in

**Comment by DanielnetoDotCom** [comment]
> Thanks.
> 
> What will it take to separate them? Is it something you can put in the development pipeline?

It may be added in the future, but I do not have this option yet

**Comment by jengajenga** [comment]
> Separate them by creating a user account for every stream and turn off multiple streams in live user plug-in

i know that's how it works the normal way. for the sake of the thread, it defeats the purpose of something we are working towards doing with. in the future i will need it.
