### ISSUE TITLE
False

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4921]
I'm having a weird issue . Sometimes randomly when I reload the page , or logout , appears a blank page stating ''false"

Nothing on the logs ( nothing on apache and nothing on avideo.log )

**Comment by DanielnetoDotCom** [comment]
Hi, I guess I found the issue, can you please update and check

**Comment by akhilleusuggo** [comment]
Thank you Daniel . I if I see it happening again I'll reopen the issue .
