### ISSUE TITLE
Chat2 Plugin

### ISSUE THREAD

**Issue by tbryantAE** [WWBN/AVideo#4922]
So issue is that we have the Chat2 plugin and the API you can open up and see the tabs but exactly what is the endpoint for the 1st and 2nd tabs?

**Comment by DanielnetoDotCom** [comment]
Hi, what do you mean "endpoint for the 1st and 2nd tabs"??

**Comment by ljmatan** [comment]
Hi @DanielnetoDotCom 

On [this](https://portal.ivrata.com/admin/plugin/Chat2/api.html) website you'll see 5 different tabs.

Sadly, however, within [this](https://video.ivrata.com/admin/plugin/API/info.php) documentation there does not appear to be the endpoint and other necessary info for the function which provide functionality displayed in the first two tabs from the linked website. 

I would need this info in order to implement a custom chat functionality.

**Comment by DanielnetoDotCom** [comment]
Sorry I still do not understand what you want/need

can you please provide some screenshots and codes as samples?

**Comment by ljmatan** [comment]
I need to: 

1) Get list of all current chats (both users and channels)
2) Get list of users I can send a message to

**Comment by DanielnetoDotCom** [comment]
basically all users/channels can have chats and send messages. you probably need to list all active users and you will use the user's ID to connect the chats

- room_users_id = the channel general Chat
- to_users_id = a private message to a specific user

**Comment by ljmatan** [comment]
How do I list users? With your GET User function I must specify an ID. 

Also, how do I see users chat messages? Example: I sent a message to someone yesterday, I login to a new device and want to see this chat. How do I do that?

**Comment by DanielnetoDotCom** [comment]
Hi, 

I just sent an update where you can call the users_list API

![image](https://user-images.githubusercontent.com/18009293/114924609-8eeebb00-9e04-11eb-87ba-514e1c8ac1cc.png)

**Comment by ljmatan** [comment]
All right. Still something thing left.

When I enter (example) messenger, I get this list: 
![screen-facebook-mess-enger-01](https://user-images.githubusercontent.com/73232684/114926724-fd497280-9e30-11eb-9d13-abdc1bf0f10b.jpg)

So it's a list of all of my conversations. How do I get this list from the API? For both other users and channels.

**Comment by DanielnetoDotCom** [comment]
Sorry, I am not understanding what do you need.

**Comment by ljmatan** [comment]
Please don't apologise, I know you've worked hard on this. 

So, for example, I send 5 messages to you. I log in to a different device, how do I see these 5 messages? How do I even see I have chat with you? Or anyone else? 

On [this](https://portal.ivrata.com/admin/plugin/Chat2/api.html) website your first two tabs ("List private Chat messages" and "List public (Channel) Chat Messages") provide this functionality, but these 2 endpoints are not included in the documentation.

**Comment by DanielnetoDotCom** [comment]
Hi, 

that is the trick. probably that is not the best solution but I save on a session/cookie the last chat message-id per user, that is why you can send  

* ['lower_then_id'] Chat message ID to filter the message search. will only return messages before that chat id
* ['greater_then_id'] Chat message ID to filter the message search. will only return messages after that chat id

So you will only retrieve new messages if you pass the `greater_then_id=[latest message_id ]`

**Comment by ljmatan** [comment]
Hey @DanielnetoDotCom 

It seems you haven't enabled the list_users API on the ivrata.com website. Can you please do so?

**Comment by DanielnetoDotCom** [comment]
If it is not present you are probably not running the latest.

make a git pull in your server.

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by tbryantAE** [comment]
We have done a complete update on portal and everything is up to date.  Chat2 still does not work.  Do you have full API documentation on this?  Also when on the portal, how do you send a private message to another user?

**Comment by ljmatan** [comment]
You send a POST request to `https://portal.ivrata.com/admin/plugin/API/set.json.php?APIName=chat2_message&users_id=` with the user's ID. 

I'd like to know however, how to retrieve messages from a single user? For example, user has had 5 chats with 5 different users, how do I see these 5 chats?

**Comment by DanielnetoDotCom** [comment]
I understand, so you must check the last message-id  and in the API URL add the greater_then_id parameter

For example, let's say the last message you received was id=10 and your users_id = 1 **(to_users_id)** 

If you want to get all the new messages that were sent to you you can do this

`https://portal.ivrata.com/admin/plugin/API/get.json.php?APIName=chat2_chat&greater_then_id=10&to_users_id=1&user=admin&pass=***&encodedPass=true`

if you want to get all the new messages sent to your channel chat (the public one) use this  **(room_users_id)**

`https://portal.ivrata.com/admin/plugin/API/get.json.php? APIName=chat2_chat&greater_then_id=10&room_users_id=1&user=admin&pass=***&encodedPass=true
`

**Comment by ljmatan** [comment]
Can you try this with user ID 89 on video.ivrata.com? Username is "myusername" and password is "Zaporka1!". It doesn't work i.e., it doesn't return the messages from this user.

**Comment by DanielnetoDotCom** [comment]
the provided credentials are not correct, I cannot try

https://portal.ivrata.com/plugin/API/get.json.php?APIName=signIn&user=myusername&pass=Zaporka1!&encodedPass=false

**Comment by DanielnetoDotCom** [comment]
Also, I notice you are running version 10.5, please update it to version 10.8+ this may make some difference

**Comment by tbryantAE** [comment]
We have updated version to latest and greatest 10.8 but Chat2 API just does not work.  Is there anyone using Chat2 API that have gotten it to work?  Willing to pay for assistance.

**Comment by tbryantAE** [comment]
The livelinks do not update and when you click on it, it sends you to the plugins store but this is a free plugin.

Signupagreement is a paid plugin that I purchased so the issue is in the original plugin.

**Comment by DanielnetoDotCom** [comment]
livelinks is free, which means you need to make a git pull

Signupagreement  you need to download again and upload the new plugin

https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin

**Comment by tbryantAE** [comment]
so I updated everything again.  Running everything updated.  log file still shows SignUpAgreement error which is in the original Plugin.    Chat2 api still does not work.

**Comment by tbryantAE** [comment]
Can you at least explain to all of us how to send a private message to another user on the portal?  There seems to be no way to do that.  Also, how to you get all of your chats to populate into another app using your API?

**Comment by ljmatan** [comment]
On [this](https://portal.ivrata.com/admin/plugin/Chat2/api.html) website you can send a message but sending POST request to chat2_chat&to_users_id=89 does outside of the website does not work. There needs to be info on how to resolve this.

**Comment by DanielnetoDotCom** [comment]
Please remind me this on Monday I will review the Chat2 API
