### ISSUE TITLE
Livestreams

### ISSUE THREAD

**Issue by tbryantAE** [WWBN/AVideo#4923]
so using the API for Livestreams we see there is a map with key "0".  What is that related to?  Seems to be a bug.  If you try and access via API even with Livestreams that show up on Website, it shows "Offline".   Please see screen capture.
![image_2021_04_10T15_34_12_031Z](https://user-images.githubusercontent.com/50838005/114583059-d3ccf300-9c46-11eb-8941-5b8eddf0dcc6.png)

**Comment by milehighkaraoke** [comment]
Thank you for better explanation of my same exact problem

**Comment by milehighkaraoke** [comment]
I have also noticed today that the stream key changes when you refresh the page. That takes embedded web page offline.  Embedded number is also diffrent than live stream url live number. Embedded number does not work at all.

**Comment by milehighkaraoke** [comment]
![Screenshot_20210413-211536_Samsung Internet](https://user-images.githubusercontent.com/70327833/114651213-c7758400-9ca0-11eb-981d-624153bc26aa.jpg)
![20210413_204544](https://user-images.githubusercontent.com/70327833/114651214-c80e1a80-9ca0-11eb-8421-020889b36a8a.jpg)
![20210413_204529](https://user-images.githubusercontent.com/70327833/114651217-c8a6b100-9ca0-11eb-86f6-09d419d1833a.jpg)
![20210413_204402](https://user-images.githubusercontent.com/70327833/114651222-c93f4780-9ca0-11eb-947f-c0d7d78fc86e.jpg)
![20210413_204356](https://user-images.githubusercontent.com/70327833/114651225-c9d7de00-9ca0-11eb-903b-c52c607d2e3d.jpg)
![20210413_204346](https://user-images.githubusercontent.com/70327833/114651227-c9d7de00-9ca0-11eb-9ca3-33f975f85bcd.jpg)

**Comment by DanielnetoDotCom** [comment]
look this is an array of objects that also include some arrays

$json[0] = server 1

if you have another server you may have 

$json[1], $json[2] , $json[3] ...

this is saying offline because you did not query any stream name (key), if you pass a key it will tell you if it is online or offline

the application property is where your lives are. that is the one you should care about.

`$json[0]->applications `

**Comment by ljmatan** [comment]
Hi @DanielnetoDotCom 

What about the "msg" parameter though? It says offline but the stream is active.

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/114777027-8ab19780-9d49-11eb-91f1-dbb4a6157c5d.png)

**Comment by ljmatan** [comment]
What do you mean by that? Where do I put this key parameter? This is the documentation: 

![Screenshot_2021-04-15_14-16-25](https://user-images.githubusercontent.com/73232684/114867519-36fc8800-9df5-11eb-8201-8c07c686b7dd.png)

**Comment by DanielnetoDotCom** [comment]
You right, it is not documented, I will add this. but try this on the demo site

This will show offline 
https://demo.avideo.com/plugin/API/get.json.php?APIName=livestreams

![image](https://user-images.githubusercontent.com/18009293/114888750-e6c6fb00-9ddf-11eb-9801-97dc992d5261.png)

With this, I specify a key (name), and then you will see the online message
https://demo.avideo.com/plugin/API/get.json.php?APIName=livestreams&name=603bcd6c86a79

![image](https://user-images.githubusercontent.com/18009293/114888690-dca4fc80-9ddf-11eb-83b2-30537c866341.png)

this ONLINE message is only for a specific key, but all keys on the applications parameter are ONLINE, we do not list offline streams

I hope it is clear now

**Comment by ljmatan** [comment]
All right, offline streams are not listed - got it. Thank you.
