### ISSUE TITLE
Watch_Later API issue

### ISSUE THREAD

**Issue by tbryantAE** [WWBN/AVideo#4924]
So whichever username and password I call to "watch_later" api we get this.  
![Screenshot_2021-04-09_18-43-26](https://user-images.githubusercontent.com/50838005/114583537-4d64e100-9c47-11eb-9aa7-89b0d29b9e5b.png)

No list of Watch Later videos

For favorite api we do get a list.

**Comment by DanielnetoDotCom** [comment]
When you test it, use an incognito browser, make sure you are not logged in.

also if you are using user and password, do not use the API secret
