### ISSUE TITLE
Logo and Favicon gets removed

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#4925]
After updating site configuration , for example smtp or anything on the section , the Logo and Favicon images gets deleted/removed .

Requires uploading them again . I though it was a cache issue , but it's not .

**Comment by DanielnetoDotCom** [comment]
Not suppose to be removed, they customized favicon (the one you upload) is on the videos folder

You should see those 
`videos/favicon.png`
and 
`videos/favicon.ico`
