### ISSUE TITLE
Groovy Gorilla 20.10  php 8.0, Nginx Module 1.19.10 (Astonishingly Quick)

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#4926]
I just installed this combination and it pretty much makes this site run like a speeding bullet. This is not for first timers only those with experience installing. Well worth the days investment. Anyone giving it a go I will be glad to guide you through a fresh install if you have any questions.

**Comment by DanielnetoDotCom** [comment]
Just to make clear, you are using Nginx instead of apache?

**Comment by JoshWho** [comment]
I am very curious please detail a little more what u mean.

**Comment by milehighkaraoke** [comment]
I am using Apache with the newest nginx module and php 8

**Comment by JoshWho** [comment]
PHP 8 is faster im guessing?

**Comment by milehighkaraoke** [comment]
Yes, that and the new nginx module seems to be alot more efficient

**Comment by jengajenga** [comment]
> I am using Apache with the newest nginx module and php 8

is 1.7.6 really the latest? a quick search shows it being discussed back in 2018.

i believe - correct me if i'm wrong - that their numbering of versions is 1.7, 1.8, 1.9, 1.10, 1.11 ... right now on 1.19...

I'm currently using 1.18

**Comment by milehighkaraoke** [comment]
Newer, sorry I did say newest

**Comment by jengajenga** [comment]
> Newer, sorry I did say newest

1.7.6 is from 2014. you're using a very old version of nginx.

**Comment by milehighkaraoke** [comment]
Correct, just not as old as the one in the install script provided

**Comment by jengajenga** [comment]
![newnginx](https://user-images.githubusercontent.com/65451390/115278518-36922300-a14e-11eb-8319-335b6921f24d.png)

i don't know how else to say it but your version is OLD. the 1.16 in the installer is much much newer than 1.7.6. 

anyway, as long as your seeing results with it i guess it's ok. i'll withdraw from this at this point.

**Comment by milehighkaraoke** [comment]
Groovy Gorilla 20.10 php 8.0, Nginx Module 1.19.10 (Astonishingly Quick

And it is now my production box......  here it is https://mhktube.com

**Comment by milehighkaraoke** [comment]
![Screenshot_20210420-033451_Outlook](https://user-images.githubusercontent.com/70327833/115374209-d7ea9a80-a189-11eb-949d-9bbdebcb5934.jpg)
