### ISSUE TITLE
Encoder isn't working after switching to https: 

### ISSUE THREAD

**Issue by gregk63** [WWBN/AVideo#4927]
I recently turned on https: I updated the configuration.php and it seemed like everything was working. Just yesterday I tried uploading a .mp4 file and I received the attached error and have been since there. I did update .htaccess with statements suggested here and it doesn't seem to have helped.

Am I still missing another step? Also, it is weird that the error message mentions the streamer site not being available since I never set it up.

Thanks,

Greg
![streamer error](https://user-images.githubusercontent.com/72754374/114602039-c9692400-9c5b-11eb-9a8d-be9a758539a1.png)

**Comment by milehighkaraoke** [comment]
Drop your encoder database and reinstall your encoder from your https:// address.......   your encoder is currently installed at http://

**Comment by gregk63** [comment]
Thank you! I was able to drop my encoder database but I am unsure what commands I need to do to reinstall the encoder. 
 
I issued the following commands which I am pretty sure I followed to do the original install.
sudo git clone https://github.com/WWBN/AVideo-Encoder.git # only for encoder
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl # only for encoder
sudo chmod a+rx /usr/local/bin/youtube-dl # only for encoder

But now I am getting the following when clicking on Encode a video and audio
![2021-04-13](https://user-images.githubusercontent.com/72754374/114644520-4963ae00-9c9d-11eb-8c86-2c1d72243e96.png)

**Comment by milehighkaraoke** [comment]
You need to now goto the folder where you want your encoder. Open that folder and then open terminal from inside that folder. Run this command 
sudo git clone https://github.com/WWBN/AVideo-Encoder.git

**Comment by milehighkaraoke** [comment]
Then set up encoder by typing https://your site url.com/encoder

**Comment by milehighkaraoke** [comment]
You also have to create database again in mysql

**Comment by gregk63** [comment]
Thank you very much! Very much appreciated. That appears to have worked! 

I don't remember doing all of this on the initial setup but, it was a while ago.

**Comment by milehighkaraoke** [comment]
Make sure to also add https://www.your-site.com in the list of available streaming sites allowed. Unless of course you are using it as public than that field is left blank. 
You can do this with the administrator account by going to your advanced tabs that are available for the admin only on your encoder site.

**Comment by gregk63** [comment]
Not understanding your last suggestions? Currently on the encoder site on the advanced tab I am unable to add my www address.

Also, there are a lot items on the Sharing queue. I am not sure where they came from and would like to get rid of them as a video I uploaded for processing is behind these and the that appears to be the one the encoder is working on is hung.

**Comment by milehighkaraoke** [comment]
Your admin account will let you delete those that are hung. If you don't have admin right on encoder user you will not have those options

**Comment by milehighkaraoke** [comment]
Here is the advanced tabs you are looking for logged into encoder as admin

![20210414_161040](https://user-images.githubusercontent.com/70327833/114786966-3a800880-9d3c-11eb-8bf3-d1984c0e3f4f.jpg)
![20210414_161049](https://user-images.githubusercontent.com/70327833/114786968-3bb13580-9d3c-11eb-83d0-1db2d9344da1.jpg)
![20210414_161116](https://user-images.githubusercontent.com/70327833/114786970-3bb13580-9d3c-11eb-804a-fa26a401efaa.jpg)
@

**Comment by milehighkaraoke** [comment]
![20210414_161049](https://user-images.githubusercontent.com/70327833/114787109-74510f00-9d3c-11eb-8e25-25509f21d6d3.jpg)

**Comment by milehighkaraoke** [comment]
If you do not see these tabs you have to add user to your encoder as admin.

**Comment by gregk63** [comment]
Thank you for hanging in with me. I don't think I had all the configuration for the encoder correct. Once I figured that out items on the queue went away. Things seem to be working better but when the encoder finishes there aren't any converted videos. Just a .jpg, a gif. Looking in the encoder log it looks like it might be an incorrect password for the streamer. Any ideas on that?

My configuration before I added https and now is that the encoder and the streamer are running on the same server and I don't have a www address. Just https: 

https://myurl.com/AVideo - streamer
https://myurl.com/AVide-Encoder- encoder

**Comment by milehighkaraoke** [comment]
Git pull both your stream and your encoder. Make sure both are up to date via the terminal not the gui

**Comment by DanielnetoDotCom** [comment]
Maybe an easiest solution is to delete the configuration.php file and drop the database and reinstall the encoder

**Comment by gregk63** [comment]
Ok. Thank you! Do I have to do an uninstall? Not seeing how to do that.

I did sudo git clone https://github.com/WWBN/AVideo-Encoder.git without an uninstall earlier as suggested earlier in this thread. Is this what you mean when you say re-install?

**Comment by DanielnetoDotCom** [comment]
if you delete the whole encoder folder you will need to do the git clone again

**Comment by gregk63** [comment]
Deleted the encoder folder, dropped the database and did the the git clone again.

No videos produced. Just the .jpg and .gif.

**Comment by gregk63** [comment]
Here are the last few lines of the encoder avideo.log
[15-Apr-2021 11:56:46 America/Chicago] Encoder::sendFileToDownload sending file to https://videos.kaiserclix.com/AVideo/aVideoEncoder.json
[15-Apr-2021 11:56:46 America/Chicago] Encoder::sendFileToDownload reading file from /var/www/html/AVideo-Encoder/videos/avideoTmpFile_1_streamers_id_1__720.mp4
[15-Apr-2021 11:56:47 America/Chicago] AVideo-Streamer answer 2 {"error":false,"video_id":139}
[15-Apr-2021 11:56:47 America/Chicago] {"error":false,"format":"mp4","file":"\/var\/www\/html\/AVideo-Encoder\/videos\/avideoTmpFile_1_streamers_id_1__720.mp4","resolution":"720","videoDownloadedLink":"","target":"https:\/\/videos.kaiserclix.com\/AVideo\/aVideoEncoder.json","postFields":12,"videoFileSize":"42.36MB","response_raw":"{\"error\":false,\"video_id\":139}","response":{"error":false,"video_id":139}}
[15-Apr-2021 11:56:47 America/Chicago] Encoder::save id=(1) title=(Stan)
[15-Apr-2021 11:56:47 America/Chicago] Encoder:sendFileChunk no need, we could download
[15-Apr-2021 11:56:47 America/Chicago] Encoder::save id=(1) title=(Stan)
[15-Apr-2021 11:56:47 America/Chicago] getReturn_vars {"videos_id":139}
[15-Apr-2021 11:56:47 America/Chicago] AVideo-Encoder sending confirmation to https://videos.kaiserclix.com/AVideo/objects/aVideoEncoderNotifyIsDone.json.php
[15-Apr-2021 11:56:49 America/Chicago] AVideo-Streamer confirmation answer {"error":false,"video_id":139}
[15-Apr-2021 11:56:49 America/Chicago] {"error":false,"target":"https:\/\/videos.kaiserclix.com\/AVideo\/objects\/aVideoEncoderNotifyIsDone.json.php","postFields":{"videos_id":139,"user":"admin","password":"b0a0090b5a3fff7c756f0a61079c0ea2","fail":0},"response_raw":"{\"error\":false,\"video_id\":139}","response":{"error":false,"video_id":139}}
[15-Apr-2021 11:56:49 America/Chicago] Encoder::save id=(1) title=(Stan)

**Comment by DanielnetoDotCom** [comment]
We need more logs, also check streamer logs

**Comment by gregk63** [comment]
Thanks to both of you! It is really appreciated!

I updated the streamer to the current level and everything is working!!!
