### ISSUE TITLE
Playlist disappears from "Organize program" if hidden

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4929]
Hi Daniel,

There is a bug in the "Organize program" section:

If you create a playlist and mark it as hidden it disappeares from the "Organize program"-List.

The first two screenshots you can see its fine if all is set to "public/active":
![Screenshot_20210413-223957_Chrome.jpg](https://user-images.githubusercontent.com/50199132/114621029-84211280-9cac-11eb-8de0-d611f296c435.jpg)
![Screenshot_20210413-223946_Chrome.jpg](https://user-images.githubusercontent.com/50199132/114621248-c185a000-9cac-11eb-83a7-620c55d67759.jpg)

After selecting "hidden" for the playlist its not in the "Organize program"-List anymore:

![Screenshot_20210413-223635_Chrome.jpg](https://user-images.githubusercontent.com/50199132/114621365-e5e17c80-9cac-11eb-80ff-866ce4cd09f8.jpg)![Screenshot_20210413-223835_Chrome.jpg](https://user-images.githubusercontent.com/50199132/114621380-ea0d9a00-9cac-11eb-8bf4-cd95578d3f9a.jpg)

**Comment by DanielnetoDotCom** [comment]
Thanks for noticing it, please try this

**Comment by morbificagent** [comment]
Thanks, its working 👍
