### ISSUE TITLE
Option to disable main menu itens

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#4931]
Is it possible to add in the CustomizeAdvanced or CustomizeUser plugin options that can disable the help, contact and about pages from the main menu?
The current help page seems to me only valid for the website owner, with informations about managing the system.

**Comment by jengajenga** [comment]
> Is it possible to add in the CustomizeAdvanced or CustomizeUser plugin options that can disable the help, contact and about pages from the main menu?
> The current help page seems to me only valid for the website owner, with informations about managing the system.

it is already there. go through CustomizeAdvanced line by line. you'll see it.

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/114708645-00921080-9d02-11eb-8d89-97dcf2270314.png)

**Comment by swimitup** [comment]
I'm sorry, I really did not pay attention... All set.
