### ISSUE TITLE
Thumbnail image for Youtube/Vimeo/DailyMotion videos from link

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#4932]
If you use "embed videos in your site", is it normal to NOT have any thumbnail image for them at myvideos page?

![Screen Shot 2021-04-13 at 16 22 45](https://user-images.githubusercontent.com/12404245/114629686-43a6a200-9c76-11eb-8dab-46453f5eb357.jpg)

**Comment by DanielnetoDotCom** [comment]
I am pretty sure if you have the MP4ThumbsAndGif it suppose to work

**Comment by swimitup** [comment]
Indeed it works, unless the video is on private/unlisted mode. The video above was unlisted. A little odd, but ok.
