### ISSUE TITLE
Live Stream Key changes when you refresh page

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#4934]
Live stream key changes everytime you refresh the page. This is troublesome to say the least as it makes it impossible to get correct live address when you click on any of the share links or embedded links.

![20210413_204402](https://user-images.githubusercontent.com/70327833/114646734-0b648b00-9c99-11eb-9dcd-9a27ff784a6f.jpg)
![20210413_204356](https://user-images.githubusercontent.com/70327833/114646738-0b648b00-9c99-11eb-9be3-7b7d8abbaa02.jpg)
![20210413_204346](https://user-images.githubusercontent.com/70327833/114646739-0bfd2180-9c99-11eb-9b84-2edfa0a7901f.jpg)

**Comment by milehighkaraoke** [comment]
![20210413_204544](https://user-images.githubusercontent.com/70327833/114646854-4d8dcc80-9c99-11eb-84ea-32bdec87b5bd.jpg)
![Uploading 20210413_204529.jpg…]()

**Comment by milehighkaraoke** [comment]
![20210413_204529](https://user-images.githubusercontent.com/70327833/114646883-5d0d1580-9c99-11eb-95b6-292ade07c26f.jpg)

**Comment by milehighkaraoke** [comment]
I disabled multiple streams under live encoder.... problem solved

**Comment by DanielnetoDotCom** [comment]
The option to disable should be this one

![image](https://user-images.githubusercontent.com/18009293/114707543-b9efe680-9d00-11eb-8f24-45876ac47997.png)
