### ISSUE TITLE
Missing Version 10.6 and Error SQL

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#4935]
Try to update but missing Version 10.6 and SQL-error.
 I restored back to v10.5
  
![Snap1](https://user-images.githubusercontent.com/39981177/114674362-6df47000-9d07-11eb-9581-e0cceaa092b1.jpg)

![Snap2](https://user-images.githubusercontent.com/39981177/114674473-8d8b9880-9d07-11eb-90b3-645ac2691ef8.jpg)

Here is missing 10.6

![Snap3](https://user-images.githubusercontent.com/39981177/114674492-92e8e300-9d07-11eb-896d-ccd1cc4a391f.jpg)

After updating to Version 10.7 the following error

**{"error":"Error performing query '\r\nALTER TABLE `users_extra_info` \r\nADD COLUMN `order` INT NOT NULL DEFAULT 0;\r\n': Duplicate column name 'order'"}** 

![Snap4](https://user-images.githubusercontent.com/39981177/114674846-efe49900-9d07-11eb-9490-208c74eaaa3e.jpg)

![Snap6](https://user-images.githubusercontent.com/39981177/114675071-24f0eb80-9d08-11eb-9e35-bc34d6334cc2.jpg)

**Comment by DanielnetoDotCom** [comment]
10.6 was removed on purpose due to an error in the update.

10.7 this error is expected in some installations

https://github.com/WWBN/AVideo/blob/506f26b19edb675d11bb734454fd4eaf4830292f/updatedb/updateDb.v10.7.sql#L1-L2
