### ISSUE TITLE
Network Encoder Bug

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4936]
Trying to set the network encoder url doesn't save it and keeps reverting to this "1/" error. This is occuring on another site we have for testing stuff edu.ahava528.com. No matter what I do I cannot save that encoder URL.

![Screen Shot 5781-08-02 at 13 01 12](https://user-images.githubusercontent.com/58882903/114692760-94270980-9d21-11eb-8f50-8e2c8cee7334.jpg)

There is a problem with this field maybe idk,

![Screen Shot 5781-08-02 at 13 06 07](https://user-images.githubusercontent.com/58882903/114693388-37781e80-9d22-11eb-8cb6-b8594d965fc5.jpg)

**Comment by jengajenga** [comment]
you can either put a url or leave the url there but remove it from the customizedadvaanced setting.

**Comment by guymass** [comment]
if I do that I cannot than access my network encoders. I have the same settings on other sites and I have no issues, only with this installation for some strange reson.

**Comment by DanielnetoDotCom** [comment]
@guymass use a full URL on this field

look at demo site 
![image](https://user-images.githubusercontent.com/18009293/114774427-8e8fea80-9d46-11eb-9201-d95141808e0b.png)

**Comment by guymass** [comment]
I have used full URL, but it doesn't get saved, it keeps reverting back to this /1 value.

**Comment by DanielnetoDotCom** [comment]
try to edit it from the plugin menu (NOT from the admin menu)

**Comment by guymass** [comment]
Now that field is missing altogether. It comes and goes if I refresh the page few times. Cleared cache, history, but this issue persists on this installation. I am not sure if maybe some other dependency might be effecting it.

![Screen Shot 5781-08-04 at 2 09 44](https://user-images.githubusercontent.com/58882903/114949041-e585e480-9e58-11eb-9df0-60e443bdd625.jpg)

![Screen Shot 5781-08-04 at 2 09 57](https://user-images.githubusercontent.com/58882903/114949037-e3238a80-9e58-11eb-8470-e893e38d594e.jpg)

**Comment by DanielnetoDotCom** [comment]
I am not sure what happened, you may need to reset the customize advanced parameters, 

1. click on the code tab, delete all the code and save it. 
2. refresh your plugins page and try again

![image](https://user-images.githubusercontent.com/18009293/115019402-8d1e0980-9e8f-11eb-922c-021bc16f32f2.png)

**Comment by guymass** [comment]
The field is gone! doesn't show on plugin now. This is the issue I was referring to and maybe also why it doesn't save.

![Screen Shot 5781-08-04 at 19 22 13](https://user-images.githubusercontent.com/58882903/115054612-17df2280-9ee9-11eb-8990-c0956e44319b.jpg)

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/115069623-37b31e00-9eca-11eb-8eb1-646c1262a9ff.png)

**Comment by guymass** [comment]
Thank you! that cleared that problem, now I have access to my network encoder finally!
