### ISSUE TITLE
Last 2 times I tried I "git Pull" I keep getting  Broken Homepage

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4937]
![a9f2d143-727d-40f0-ae86-e84acefdffd4](https://user-images.githubusercontent.com/39392449/114695395-31158280-9ce1-11eb-8fa8-dba119200cd4.png)

**Comment by JoshWho** [comment]
Had to run a roll back using 

`git reset --keep HEAD@{1}`

**Comment by DanielnetoDotCom** [comment]
This should fix that

**Comment by JoshWho** [comment]
Yes I can confirm it is fixed. Thank you
