### ISSUE TITLE
Notification keeps dropping to 2

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4938]
@DanielnetoDotCom , @akhilleusuggo 

DB: 10.5

I have some 30 streams going on but every other time the notification drops to 2. 

For the numbers to return, I have to reset my stream key.

Logs aren't saying anything about that error but the audit shows that every time there's an update to the transmition history table, the numbers drop. The one in blue circle is me resetting my streamkey.

It also affects the gallery page. But it does not affect the stats.xml file.

![Inkedupdate_stream_LI](https://user-images.githubusercontent.com/65451390/114697507-aa839400-9d26-11eb-8051-c8774ecd5004.jpg)

**Comment by jengajenga** [comment]
I can confirm that it happens everytime this takes place


LiveTransmitionHistory | finishFromTransmitionHistoryId | UPDATE live_transmitions_history SET finished = now() WHERE id = 15925 n
-- | -- | --

**Comment by jengajenga** [comment]
@DanielnetoDotCom will you please look at this?

**Comment by DanielnetoDotCom** [comment]
I have a customer that also has about 30 lives at the same time and the notifications show fine.

when this happens clear the cache and check if the number comes back.
