### ISSUE TITLE
Meet quality low with more than 2 attenders 

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#4940]
How to reproduce:

- Create a meet. 
- Attend with another instance (different browser or machine) 
- Now there's two participants. Quailty is 1280x720px. 
- Join with another instance (different browser or machine)
- Now there's three participants. Quality lowers to 320x180px 
- Exit some of the participants. Quality returns to 1280x720px.

**Comment by JoshWho** [comment]
Yah the FPS I think needs to be just a little more than what it is like at least 20 to 30 frames. I know your trying to find the Goldilocks of QoS but seems like when I watch the recording of the streams everything is hard to read if there is text displayed.
