### ISSUE TITLE
Top-Menue, Logo and Search sometimes not there

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4941]
Hi Daniel,

since a few days the Logo and Menue on top isnt there. This can happen on every page. Main-Page or inside a Video:

![Unbenannt](https://user-images.githubusercontent.com/50199132/114728956-d8290700-9d3f-11eb-9b5f-6720e428de7a.PNG)

Clicking around a little bit, switching sites and it comes back...

**Comment by tonuzo** [comment]
I can confirm the issue. It also happens to me occasionally. Menu bar disappears and the left drop down menu goes to right corner, but isn't accessible (when clicked -> 404)
