### ISSUE TITLE
How to fix titles of live streams

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#4946]
Just a general question. How to fix the titles of the live broadcasts that come from another place that has a different title from the original content?

Example: 
![image](https://user-images.githubusercontent.com/62782361/114820532-bf8f1000-9d84-11eb-951e-dd84971ffc6e.png)
If you look at the channel (REEL TV) that has the same title, except for the date and time makes it difficult when the feed (MRSS) captures it when people are watching or looking for the title of the content.

Is there a way to fix it, or we have to manually edit the titles from each live stream?

**Comment by DanielnetoDotCom** [comment]
Hi, 

I cannot think in any way to automatically add titles. where the titles should be pulled from?

we always use the title from here 

![image](https://user-images.githubusercontent.com/18009293/114871425-a5c6ea80-9dcf-11eb-86ec-27de87d0cc19.png)
