### ISSUE TITLE
New field-type "Link" for the User Extra Info

### ISSUE THREAD

**Issue by SirFiChi** [WWBN/AVideo#4947]
Is it possible to add the field-type "Link" to the User Extra Info settings?
URL: https://MY-SITE.COM/plugin/CustomizeUser/View/editor.php

It would be cool that the users can add links to there website, social-media accounts and micropayment services.

Thanks.

**Comment by DanielnetoDotCom** [comment]
Question why not just use the type text?

**Comment by SirFiChi** [comment]
Because the type text generates a not clickable text.
But after some tests: How can I get the User Extra Info to the Channel of a User?

**Comment by DanielnetoDotCom** [comment]
Currently, you cannot, 

the extra info is basically something the admin may need about the user. for example, if you need to make a payment to him and you need to check some documents.

**Comment by SirFiChi** [comment]
So I have to change the topic to: Link fields for user profiles? (;

Are there any plans to extend the user info page?

**Comment by DanielnetoDotCom** [comment]
Not right now, but I can do it as a paid customization.

If you are interested send me an email at developer@youphptube.com
