### ISSUE TITLE
Top menu plugin user access

### ISSUE THREAD

**Issue by amaljithbroad** [WWBN/AVideo#4948]
I had added new menu item on 'Top Menu' plugin using the link 'https://github.com/WWBN/AVideo/wiki/How-to-use-TopMenu-Plug-in' .I want to show that newly added menu item for 'Premium member' user group only.

How i can configure that.Please advise asap.

**Comment by DanielnetoDotCom** [comment]
Sorry we do not have that option

**Comment by amaljithbroad** [comment]
Ok thankYou.

**Comment by amaljithbroad** [comment]
Hi Daniel,
Is there any chance we can implement via code edit ,if so please share thee changes to be made.
ThankYou
Amaljith

**Comment by DanielnetoDotCom** [comment]
Sure, the source code is here https://github.com/WWBN/AVideo/tree/master/plugin/TopMenu

you should have it on your site. after the implementation, feel free to submit a pull request, so it can be part of the main project.

**Comment by amaljithbroad** [comment]
By using which keyword we can identify the user as premium group member?. Do you know?.

**Comment by DanielnetoDotCom** [comment]
keyword???

the way I am thinking you need to change the plugin database and use primary and foreign keys on it.

**Comment by amaljithbroad** [comment]
Hi Daniel,
I want to show that newly added menu item for 'Premium member' user group only in my web app which uses the plugin 'Top Menu'.

How i can configure that by code edit in my web app.
How we can identify an user which belongs to the group 'Premium Member' and display the menu item accordingly via code edit.
ThankYou
Amaljith

**Comment by DanielnetoDotCom** [comment]
First, you need to know how to code in PHP and deal with databases.

If you have those backgrounds you should be able to figure out looking into the source code.

I am sorry I cannot teach how to code.

**Comment by amaljithbroad** [comment]
Ok Daniel,
I got that.
Thankyou
Amaljith
