### ISSUE TITLE
Contact form return an error

### ISSUE THREAD

**Issue by frgds** [WWBN/AVideo#4949]
Hello when i try the contact form i have an error : (Could not execute: /usr/sbin/sendmail -t -i )
and the captcha chain display alway the same string (admin) is it normal ?
but The email user verification in working .
Thank

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/WWBN/AVideo/wiki/Setting-up-AVideo-Platform-to-send-emails

**Comment by akhilleusuggo** [comment]
> and the captcha chain display alway the same string (admin) is it normal ?
It is normal if you're logged as admin . Try a different user or a logged out user , you will see different captcha .
