### ISSUE TITLE
Meet-Server Offline

### ISSUE THREAD

**Issue by peterflitz** [WWBN/AVideo#4950]
The meet servers go offline after a short time.
Since last update to 10.7

![meet-down](https://user-images.githubusercontent.com/76056428/114958605-a0b37b00-9e63-11eb-8f6b-224a9d677bb2.png)

**Comment by DanielnetoDotCom** [comment]
Please make a` git pull` again and let me know.

**Comment by peterflitz** [comment]
Looks good, thank you Daniel.

**Comment by peterflitz** [comment]
Edit, still same problem.
I cleared the cache after the update, the servers were available.
But offline again after 1-2 minutes, there is still an error.

**Comment by DanielnetoDotCom** [comment]
I mean, did you notice I sent an update 5 min ago?

**Comment by peterflitz** [comment]
Yes Daniel, I was still wondering what the meet problem has to do with the Turkish language.
Now you have secretly added /view/info.php to it :-)

Thank you, now it seems to be working.
