### ISSUE TITLE
Live category mismatch

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4955]
@DanielnetoDotCom , see this

I only have around 30 streams but the category is showing a totally different number - 49. it's causing much confusion. 

It should say live-currently-playing  or something.

![category-data](https://user-images.githubusercontent.com/65451390/115011832-c4081580-9eb7-11eb-9896-1e4e42a7bc32.png)

what can you do about it? where are the extra numbers coming from? 

![category-data2](https://user-images.githubusercontent.com/65451390/115013649-fdda1b80-9eb9-11eb-86bf-80e542d0fd04.png)

Whether this setting is on or off, it doesn't make a difference. it only does the same thing.

**Comment by DanielnetoDotCom** [comment]
the categories use a separated cache. try from an incognito browser and clear the site cache.

**Comment by jengajenga** [comment]
@DanielnetoDotCom, I've done that and still no change. 
Cleared front page cache, directory cache, browser cache, used incognito from brand new browser, still no difference.
any other fixes?

**Comment by jengajenga** [comment]
@DanielnetoDotCom , any other solution?

**Comment by jengajenga** [comment]
@DanielnetoDotCom , do you have another solution for this since it isn't working?

or anyone else?

**Comment by DanielnetoDotCom** [comment]
can you reproduce that on the demo site?
