### ISSUE TITLE
Restream Key

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#4956]
@DanielnetoDotCom  hi

Is it possible to mask or hash stream keys so that we don't see the keys of our restreamers? 

![restream-key](https://user-images.githubusercontent.com/65451390/115015516-74781880-9ebc-11eb-8bad-7a537832a83b.png)

**Comment by DanielnetoDotCom** [comment]
Do you mean just hide it with ***??

**Comment by DanielnetoDotCom** [comment]
Anyway, the key is NOT a secret, the ?p= that must be hidden

**Comment by jengajenga** [comment]
> Anyway, the key is NOT a secret, the ?p= that must be hidden

this is for the restream, not the main stream. the key given by facebook or youtube is exposed. hiding it with ****** would be good so that we also don't run the risk of exposing user data.

**Comment by DanielnetoDotCom** [comment]
even if you hide with *** it is not secured, so in my mind it still useless.

**Comment by jengajenga** [comment]
> even if you hide with *** it is not secured, so in my mind it still useless.

alright. as you develop the platform, i hope you will find a useful way :)
