### ISSUE TITLE
Where to insert an HTML file into the server

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#4957]
I would like to know how to insert a link after creating a Terms of Agreement html page.
My platform is: https: sharknetwork24.net

I don't know where to put the html file on my server in order to be called up via a link link.

This is an example of what I wish I could do:
http://soappirat.es/page.php?name=terms-toa
![dd3](https://user-images.githubusercontent.com/82677269/115082923-f2f9a800-9f06-11eb-9ba6-2cb9523ca247.JPG)

**Comment by sharknetwork24** [comment]
Can anyone kindly answer me?
I was told to sign up and report the issues here.

**Comment by akhilleusuggo** [comment]
are you sure about that ?

**Comment by DanielnetoDotCom** [comment]
@sharknetwork24 did you try the TopMenu?

https://github.com/WWBN/AVideo/wiki/How-to-use-TopMenu-Plug-in
