### ISSUE TITLE
Link in Description isnt working

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4959]
If i create a html-link inside a description it does work when i open the Video-page itself and click on the link.

But if i click on the small "description popup" the link inside of the description redirects to a broken url.

![Screenshot_20210417-013232_Chrome.jpg](https://user-images.githubusercontent.com/50199132/115094161-e8e2a400-9f1c-11eb-8925-7b81d5e37622.jpg)

![Screenshot_20210417-013247_Chrome.jpg](https://user-images.githubusercontent.com/50199132/115094176-eed88500-9f1c-11eb-82e0-097ef1266dbf.jpg)

![Screenshot_20210417-013312_Chrome.jpg](https://user-images.githubusercontent.com/50199132/115094179-f26c0c00-9f1c-11eb-9923-46794e0a4a5f.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, I am a bit confused, can you please provide more details on what exactly do you have in your description?

if you can please share the description HTML source code

**Comment by morbificagent** [comment]
In the description there is only an html-link.
You can click on it but the url is malformed as you can see with these %60%60 and missing slashes.

**Comment by DanielnetoDotCom** [comment]
Please try this update
