### ISSUE TITLE
Ldap login is not working

### ISSUE THREAD

**Issue by matheusfillipe** [WWBN/AVideo#4960]
I have set up ldap in a way that is working for an existing user but it does not for new ones I add on ldap. I have this error trying to log in:

``` 
[17-Apr-2021 05:23:57 Asia/Jerusalem] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.p
hp","line":98,"function":"log_error","args":["Error in writeSql : (1452) Cannot add or update a child row: a foreign key con$
traint fails (`eduVideos`.`users_has_users_groups`, CONSTRAINT `fk_users_has_users_groups_users_groups1` FOREIGN KEY (`users_
groups_id`) REFERENCES `users_groups` (`id`) ON DELETE CASCADE ON UPDATE CASCADE), SQL-CMD:INSERT INTO users_has_users_groups
 ( users_id, users_groups_id) VALUES (?,?)"]},{"file":"\/var\/www\/html\/AVideo\/objects\/userGroups.php","line":225,"functio
n":"writeSql","class":"sqlDAL","type":"::","args":["INSERT INTO users_has_users_groups ( users_id, users_groups_id) VALUES (?
,?)","ii",[14,0]]},{"file":"\/var\/www\/html\/AVideo\/plugin\/LoginLDAP\/LoginLDAP.php(18) : eval()'d code(1) : eval()'d code
","line":124,"function":"updateUserGroups","class":"UserGroups","type":"::","args":[14,["0"],true,true]},{"file":"\/var\/www\
/html\/AVideo\/plugin\/LoginLDAP\/view\/login.json.php(18) : eval()'d code(1) : eval()'d code","line":12,"function":"login","class":"LoginLDAP","type":"::","args":["streamer",2053733545]},{"file":"\/var\/www\/html\/AVideo\/plugin\/LoginLDAP\/view\/lo
gin.json.php(18) : eval()'d code","line":1,"function":"eval"},{"file":"\/var\/www\/html\/AVideo\/plugin\/LoginLDAP\/view\/log
in.json.php","line":18,"function":"eval"}] SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php
[17-Apr-2021 05:23:57 Asia/Jerusalem] AVideoLog::ERROR: Error in writeSql : (1452) Cannot add or update a child row: a foreign key constraint fails (`eduVideos`.`users_has_users_groups`, CONSTRAINT `fk_users_has_users_groups_users_groups1` FOREIGN KE
Y (`users_groups_id`) REFERENCES `users_groups` (`id`) ON DELETE CASCADE ON UPDATE CASCADE), SQL-CMD:INSERT INTO users_has_us
ers_groups ( users_id, users_groups_id) VALUES (?,?) SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php
[17-Apr-2021 05:23:57 Asia/Jerusalem] AVideoLog::DEBUG: Sending SMTP Email SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php
[17-Apr-2021 05:23:57 Asia/Jerusalem] AVideoLog::DEBUG: sendVerificationLink Error Info: You must provide at least one recipi
ent email address. SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php


```

![image](https://user-images.githubusercontent.com/24435787/115099358-b67c7b00-9f0b-11eb-8649-2fc938f6cfb6.png)

**Comment by DanielnetoDotCom** [comment]
can you please check this update?

**Comment by matheusfillipe** [comment]
Still not working. I am testing the same accounts with this script: https://github.com/anthony-b/simple-php-LDAP-Authentication/blob/master/ldap.php and they work there.

From avideo now there are no logs besides:

```
[20-Apr-2021 04:35:38 Asia/Jerusalem] AVideoLog::DEBUG: Sending SMTP Email SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php
[20-Apr-2021 04:35:38 Asia/Jerusalem] AVideoLog::DEBUG: sendVerificationLink Error Info: You must provide at least one recipient email address. SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php

```
And from the login screen "Wrong password"
![image](https://user-images.githubusercontent.com/24435787/115324142-c12f4e00-a15f-11eb-9783-64200f732e65.png)

But the same credentials work for that other script. Interestingly i can still login in avideo for the first test user i had but then never worked anymore for new ldap users. Also I tried on both the latest commit and on the commit that referenced this issue.

**Comment by DanielnetoDotCom** [comment]
You have shared logs regarding your SMTP email, which has nothing to do with LDAP

look at your log for something related to LDAP

**Comment by matheusfillipe** [comment]
I am aware. Nothing related of ldap displays when I try to login now. Just that smtp thing

**Comment by DanielnetoDotCom** [comment]
I will assume your SMTP is not properly configured. 

maybe you have enabled some verification, can you please make sure you disable all email verification?  

![image](https://user-images.githubusercontent.com/18009293/115408039-ea36f980-a1c6-11eb-971c-a4f887dbe53b.png)

anyway, LDAP logins should be verified by default.

I just sent LoginLDAP v2.5 that will handle that.

if you want just update your LDAP plugin that I will upload in 30 min, so you may be able to log in even if you do not disable the email verification.

Also, make a git pull in your installation

**Comment by guymass** [comment]
I have done all updates and can confirm that I was able to login with a created ldap user and was able to edit its credentials. This is great, thank you for the update. 
I wish to ask couple of things as I don't know what this plugin really can do, however:

1. how can I convert all my current users to ldap users?
2. how do i handle registrations for ldap? Can our registration also create an ldap user?

I would like to see it a bit more user friendly as I think using a single sign on account for multiple sites is a great idea and should allow users much ease of access to services.

**Comment by DanielnetoDotCom** [comment]
Hi, sorry but we do not add information on your LDAP server. we only read information from it.

**Comment by guymass** [comment]
Would it be possible to pay for development service  to add the ability to also write the info to the ldap? We are looking for a way to register users from our site to ldap.

**Comment by DanielnetoDotCom** [comment]
Hi, I am not 100% but I am pretty sure it is not possible.

also, it will depend a lot on your LDAP environment. each LDAP is different. maybe it can be done from some one from your company, because it will require to be tested internally

**Comment by guymass** [comment]
Ok thank you very much for your answer.
