### ISSUE TITLE
Some Security Issue

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4963]
I don't know where to put this info so I hope Daniel or someone will read this. I have received a private message from a security hacker in one of our telegram groups claiming our site/script is very unsecure, specially on the login page as there is no encryption on the site. I am not sure really what to do with this info, but he claimed it will be about 5min to hack it and cause major damages. 

So my question is, how can we make it more secure?

He says we have many bots and network activity trying to get information from the site either on users or other info and I see google bot constantly running on our site and others as well, how can I block them?

How can we make the site more secure for us and our users?

**Comment by DanielnetoDotCom** [comment]
I believe he is bluffing

what he can do is a ddos attack on your page. then your server provider have to be able to handle it.

Cloudflare also claim to be able to handle it , but I do not like it .

in my case OVH solves this very well

**Comment by guymass** [comment]
OVH? What is that? like cloudflare?

**Comment by DanielnetoDotCom** [comment]
https://www.ovh.com/
