### ISSUE TITLE
YPTSocket plugin not working!

### ISSUE THREAD

**Issue by Proton-people** [WWBN/AVideo#4964]
The test shows the following:
![bandicam 2021-04-17 18-08-35-564](https://user-images.githubusercontent.com/48072457/115119568-1d586d80-9fba-11eb-8921-e6fcbd98be49.jpg)
Running shows the following:
![bandicam 2021-04-17 18-08-15-235](https://user-images.githubusercontent.com/48072457/115119595-4678fe00-9fba-11eb-80f0-b18a2d7a9a3f.jpg)
The path to the certificate is correct.
![bandicam 2021-04-17 18-15-07-612](https://user-images.githubusercontent.com/48072457/115119655-8d66f380-9fba-11eb-9c16-9906d12817e9.jpg)
I tried changing the port and it didn't help.
I tried changing 127.0.0.1 to the server IP and it didn't help.
The broadcast is in progress but not playing!
![bandicam 2021-04-17 18-12-17-685](https://user-images.githubusercontent.com/48072457/115119810-580ed580-9fbb-11eb-8c7a-b6876f580562.jpg)
![bandicam 2021-04-17 18-12-30-593](https://user-images.githubusercontent.com/48072457/115119816-5e04b680-9fbb-11eb-945c-169fb6b0d8c7.jpg)
My nginx:
![bandicam 2021-04-17 18-34-18-767](https://user-images.githubusercontent.com/48072457/115120013-32ce9700-9fbc-11eb-9592-051866713139.jpg)
![bandicam 2021-04-17 18-38-07-140](https://user-images.githubusercontent.com/48072457/115120066-8b059900-9fbc-11eb-978a-d4dbdd455efe.jpg)
Please tell me what to do?

**Comment by Proton-people** [comment]
![bandicam 2021-04-17 18-13-24-628](https://user-images.githubusercontent.com/48072457/115120242-88f00a00-9fbd-11eb-904b-ad24441f4853.jpg)
My log file

**Comment by milehighkaraoke** [comment]
You need to expand the log at the + 
Off hand try a different port for the socket

**Comment by milehighkaraoke** [comment]
Your ssl path looks suspect 

![Screenshot_20210418-011359_Samsung Internet](https://user-images.githubusercontent.com/70327833/115137459-75f03080-9fe3-11eb-9941-8eb0c2ed8a93.jpg)

**Comment by milehighkaraoke** [comment]
Should look like this but
![Screenshot_20210418-011800_Samsung Internet](https://user-images.githubusercontent.com/70327833/115137583-278f6180-9fe4-11eb-8192-fb51067042bf.jpg)
 with your site name

**Comment by milehighkaraoke** [comment]
You also have to make sure you installed the letsencrypt certificates with certbot

**Comment by Proton-people** [comment]
> Вы также должны убедиться, что вы установили сертификаты letsencrypt с помощью certbot

Certification authority must be necessarily Letsencrypt? Or is it enough to rename the folder with the certificate?

**Comment by Proton-people** [comment]
> Должно выглядеть так, но с именем вашего сайта с именем вашего сайта
> ![Скриншот_20210418-011800_Samsung Internet](https://user-images.githubusercontent.com/70327833/115137583-278f6180-9fe4-11eb-8192-fb51067042bf.jpg)

![bandicam 2021-04-18 18-24-53-389](https://user-images.githubusercontent.com/48072457/115152876-19911d80-a084-11eb-8cd8-b27d8946a018.jpg)
Did not help.

**Comment by milehighkaraoke** [comment]
Use this to install let's encrypt

![Screenshot_20210418-130958_Samsung Internet](https://user-images.githubusercontent.com/70327833/115157627-889c5100-a047-11eb-865a-37416f5638c0.jpg)

**Comment by Proton-people** [comment]
> Используйте это для установки давайте зашифровать
> 
> ![Скриншот_20210418-130958_Samsung Internet](https://user-images.githubusercontent.com/70327833/115157627-889c5100-a047-11eb-865a-37416f5638c0.jpg)
I am using a different certification authority. Everything works with these certificates. Only this plugin does not work. Are you a problem that I do not use Letsencrypt?

**Comment by milehighkaraoke** [comment]
I only use let's encrypt  I would have no idea  how to support your certificate

**Comment by milehighkaraoke** [comment]
For your certificate the only thing I can think of is bad path or insufficient privilege to read the certificate

**Comment by Proton-people** [comment]
> Я использую только Let's encrypt, я бы понятия не имел, как поддерживать ваш сертификат

I installed Let's Encrypt and the problem remains the same.
![bandicam 2021-04-20 01-05-38-249](https://user-images.githubusercontent.com/48072457/115314094-524bf800-a153-11eb-999a-3f8e927e7a04.jpg)
![bandicam 2021-04-20 01-07-50-789](https://user-images.githubusercontent.com/48072457/115314114-5b3cc980-a153-11eb-8c44-dcad633cd4d4.jpg)

**Comment by milehighkaraoke** [comment]
Did you run the nohop command?

**Comment by Proton-people** [comment]
> Убедитесь, что 2053 - это порт, перенаправляющий на ваш сайт, и если это так, попробуйте изменить порт на 12053 в розетке.

I changed the port but nothing has changed.

**Comment by milehighkaraoke** [comment]
Test your ports. Make sure they are open

https://www.yougetsignal.com/tools/open-ports/

**Comment by Proton-people** [comment]
> Проверьте свои порты. Убедитесь, что они открыты
> 
> https://www.yougetsignal.com/tools/open-ports/

All ports are open. I can take a picture if needed.

**Comment by milehighkaraoke** [comment]
Please post the root crontab

**Comment by Proton-people** [comment]
> Выложите пожалуйста корневой crontab

![bandicam 2021-04-20 12-05-43-471](https://user-images.githubusercontent.com/48072457/115378382-42620180-a1af-11eb-99aa-e4df5694579a.jpg)

**Comment by milehighkaraoke** [comment]
Your NGINX crontab is missing ad that with a sleep 10 at reeboot

**Comment by milehighkaraoke** [comment]
Do a sudo git pull  on the site and encoder

**Comment by Proton-people** [comment]
> В вашем crontab NGINX отсутствует объявление, которое со сном 10 при перезагрузке

Do you have a sample of this ad? Or please tell me where I can copy and add this ad. Thank you for helping me.

**Comment by milehighkaraoke** [comment]
Web sockets are being implemented in 10.5 and that requires some more configuration

**Comment by milehighkaraoke** [comment]
One minute  I will get that for you

**Comment by milehighkaraoke** [comment]
@reboot sleep 10;  /usr/local/nginx/sbin/nginx

**Comment by milehighkaraoke** [comment]
If this does not work I will need to take a look at your nginx config file,  please attach your nginx config if last step does not resolve issue

**Comment by Proton-people** [comment]
> Если это не сработает, мне нужно будет взглянуть на ваш файл конфигурации nginx, пожалуйста, прикрепите свою конфигурацию nginx, если последний шаг не решает проблему.

![bandicam 2021-04-20 12-35-42-447](https://user-images.githubusercontent.com/48072457/115382660-b3a3b380-a1b3-11eb-92c1-a2f0e8475bb7.jpg)
![bandicam 2021-04-20 12-36-00-491](https://user-images.githubusercontent.com/48072457/115382674-b6060d80-a1b3-11eb-90b7-9d873ca4b68e.jpg)
![bandicam 2021-04-20 12-36-29-278](https://user-images.githubusercontent.com/48072457/115382688-b8686780-a1b3-11eb-86c7-c11e951b0310.jpg)
![bandicam 2021-04-20 12-37-05-596](https://user-images.githubusercontent.com/48072457/115382696-bb635800-a1b3-11eb-8863-f142c9eb6e38.jpg)
![bandicam 2021-04-20 12-29-53-645](https://user-images.githubusercontent.com/48072457/115382734-c6b68380-a1b3-11eb-81d8-b949168a3a1d.jpg)

**Comment by DanielnetoDotCom** [comment]
as long as works with localhost check if you have a firewall or proxy blocking it.

**Comment by Proton-people** [comment]
> пока работает с localhost, проверьте, есть ли у вас брандмауэр или прокси-сервер, блокирующий его.

ufw disabled

**Comment by DanielnetoDotCom** [comment]
are you using apache?

there are any proxy?

**Comment by Proton-people** [comment]
> вы используете apache?
> 
> есть какие-нибудь прокси?

Yes I am using Apache. I did not include a proxy.

**Comment by DanielnetoDotCom** [comment]
Sorry I really do not know.

Just to make sure, you need to open 2 terminals

one you will run the socket server command

on the other one you will run the test script

**Comment by Proton-people** [comment]
> > Извините, я действительно не знаю.
> > На всякий случай нужно открыть 2 терминала
> > один вы запустите команду сервера сокета
> > на другом вы запустите тестовый скрипт
> 
> ОК. Я попробую сделать это сейчас.

![bandicam 2021-04-20 16-30-19-297](https://user-images.githubusercontent.com/48072457/115413762-35a3d480-a1d4-11eb-8ad8-e7b07a56abd8.jpg)

**Comment by Proton-people** [comment]
> > > Извините, я действительно не знаю. 
> > > На всякий случай нужно открыть 2 терминала 
> > > один вы запустите команду сервера сокета 
> > > на другом вы запустите тестовый скрипт
> > 
> > 
> > ОК. Я попробую сделать это сейчас.
> 
> ![Bandicam 2021-04-20 16-30-19-297](https://user-images.githubusercontent.com/48072457/115413762-35a3d480-a1d4-11eb-8ad8-e7b07a56abd8.jpg)
AAAA entry made

**Comment by Proton-people** [comment]
> Извините, я действительно не знаю.
> 
> На всякий случай нужно открыть 2 терминала
> 
> один вы запустите команду сервера сокета
> 
> на другом вы запустите тестовый скрипт

Can it interfere with your work?
![bandicam 2021-04-20 16-46-17-351](https://user-images.githubusercontent.com/48072457/115416396-84526e00-a1d6-11eb-8950-19e460954df9.jpg)

**Comment by DanielnetoDotCom** [comment]
> > Извините, я действительно не знаю.
> > На всякий случай нужно открыть 2 терминала
> > один вы запустите команду сервера сокета
> > на другом вы запустите тестовый скрипт
> 
> Can it interfere with YPTSocket?
> ![bandicam 2021-04-20 16-46-17-351](https://user-images.githubusercontent.com/48072457/115416396-84526e00-a1d6-11eb-8950-19e460954df9.jpg)

forget about this, this is deprecated

**Comment by DanielnetoDotCom** [comment]
Definitely it is not working. looks like you are having DNS problems

try to google for this 
![image](https://user-images.githubusercontent.com/18009293/115418523-ee1b4980-a1cf-11eb-81a3-ed376952cd1c.png)

**Comment by Proton-people** [comment]
I'll close this thread. I have not found a solution.
