### ISSUE TITLE
Cant get past setup

### ISSUE THREAD

**Issue by 7figurefortune** [WWBN/AVideo#4965]
http://7figurefortune.com/youPHPtube/

When going to my website its telling me "It appears that either something went wrong or the mod rewrite configration is not correct.
If you don't use apache, just let .htaccess stay or create a empty file - then this check will pass."

.htaccess stay or create a empty file - then this check will pass....

What does this ^^^^^ mean. How do i set this up on a normal server withOUT apache servers.

**Comment by milehighkaraoke** [comment]
The site is not recommended with nginx instead of apache. Use nginx module and apache

**Comment by milehighkaraoke** [comment]
![Screenshot_20210420-040035_Samsung Internet](https://user-images.githubusercontent.com/70327833/115377600-0453e600-a18d-11eb-943b-779e57ed4db3.jpg)
