### ISSUE TITLE
PayPal button For Donations

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#4967]
Is it possible to add this feature as shown in the photo?
PayPal button
For Donations
![nnn](https://user-images.githubusercontent.com/82677269/115126012-5d285080-9fcc-11eb-9d1b-0ddeb52f24e0.JPG)

**Comment by akhilleusuggo** [comment]
Feature on channel already exist. Add your donation link to your channel.

![image](https://user-images.githubusercontent.com/52116577/115227722-83a7d200-a119-11eb-9e19-6e10663ca4e3.png)

In first page you can create a menu or ( in plugins ) or add it as you showed by inserting custom html. But this will be global and not for each user.

![image](https://user-images.githubusercontent.com/52116577/115228146-13e61700-a11a-11eb-8dee-5578183d3fd4.png)

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform#donations

**Comment by sharknetwork24** [comment]
> Feature on channel already exist. Add your donation link to your channel.
> 
> ![image](https://user-images.githubusercontent.com/52116577/115227722-83a7d200-a119-11eb-9e19-6e10663ca4e3.png)
> 
> In first page you can create a menu or ( in plugins ) or add it as you showed by inserting custom html. But this will be global and not for each user.
> 
> ![image](https://user-images.githubusercontent.com/52116577/115228146-13e61700-a11a-11eb-8dee-5578183d3fd4.png)

Can you tell me which plugin is this in?
Thank you

https://user-images.githubusercontent.com/52116577/115228146-13e61700-a11a-11eb-8dee-5578183d3fd4.png

**Comment by DanielnetoDotCom** [comment]
CustomizeAdvanced

**Comment by sharknetwork24** [comment]
Thanks I solved
