### ISSUE TITLE
Unable to write Facebook ID and KEY

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#4972]
I want to know why it is not possible to write anything.
I cannot enter ID and Key.
Daniel tell me why it is not possible to do this with Facebook.
With Goole I succeeded without problems.
I'm waiting for your answer.
Thank you
![22224](https://user-images.githubusercontent.com/82677269/115162097-caf27c00-a0a1-11eb-86e1-5ebde7d6a7d3.JPG)

**Comment by akhilleusuggo** [comment]
Don't setup your site from admin configuration, is depricated. Instead , setup from plugin section.

**Comment by DanielnetoDotCom** [comment]
@sharknetwork24 edit your plugins from here

![image](https://user-images.githubusercontent.com/18009293/115239818-8395db00-a0f5-11eb-92d4-bca8341b5ec3.png)


In case the plugin is  corrupted already delete the code from the parameters, save, refresh the page and try again

![chrome-capture (2)](https://user-images.githubusercontent.com/18009293/115240066-c5bf1c80-a0f5-11eb-9fe5-308ca55b3de2.gif)

**Comment by sharknetwork24** [comment]
Perfect I solved everything.
Thank you
