### ISSUE TITLE
Live Stream Share shows offline line jpeg 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#4973]
**Describe the bug**
When I share my live stream it propagates offline jpeg instead of my custom jpg

**Expected behavior**
Share stream it shows current snippet in the share instead of off line 
![Screenshot_20210418-195001_Samsung Internet](https://user-images.githubusercontent.com/70327833/115189376-9a134680-a0a3-11eb-94ef-3c7163070c1a.jpg)

.

**Comment by DanielnetoDotCom** [comment]
With this new update. if there is a poster setup it will return the poster instead of the offline image

**Comment by milehighkaraoke** [comment]
Thank you Sir
