### ISSUE TITLE
Would like to add privacy and Terms and Condition Pages to sites

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#4975]
Hi 
Hopefully mines a simple query.. I would like to add privacy page and a Terms and conditions Page to my site for the general public.  Whats the best way to do this ? Not sure if you have plugins or I have to setup an html page.

Please advise.

Thanks

**Comment by akhilleusuggo** [comment]
Plugins, Menu

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-use-TopMenu-Plug-in

**Comment by kollossus55** [comment]
Thanks.. thats just the answer.. Can I amend it to be at the bottom of the page on the Left.. Would like it after all the other options.
Thanks

**Comment by DanielnetoDotCom** [comment]
You can add links at the bottom with the customize plugin

![image](https://user-images.githubusercontent.com/18009293/115393412-08492d80-a1b8-11eb-893c-2dcf832c8095.png)

**Comment by kollossus55** [comment]
Thanks

**Comment by kollossus55** [comment]
thanks for help..
