### ISSUE TITLE
Color (and some more) not changeable in descriptions

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4976]
In the editor for the descriptions you can select text-color for example...

After selecting a color it looks right in the editor but when you click on "save" the text-color isnt saved.

Same with several other parts in the description editor.

Tested on your demo-site which has the same problem.

**Comment by DanielnetoDotCom** [comment]
What do you mean, allow more colors on the editor?

Just to make clear, to avoid users mess up the site we remove most of the tags from the description. we really discourage allowing users to add any custom tag/color.

**Comment by morbificagent** [comment]
No i dont mean MORE colors but the one which are selectable at the moment arent working!

I cant make any text red for example.
