### ISSUE TITLE
Please redirect to the video i have bought...

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4977]
Workflow at the moment when buying a video with yptwallet and paypal:

1. A new user/customer comes to the site
2. He click on the pay-per-view video
2. Notice comes up that he have to buy it (but he have not enough money in his yptwallet because he is new)
3. Notice comes up that he has to put money in the wallet via paypal
4. He pays the money
5. **After the process the user is redirected to the yptwallet success-site and not back to the video where the process of buing started -> He is confused**

It would be very helpful if the user would be redirected back to the video from which he started the buying-process described!!!

**Comment by DanielnetoDotCom** [comment]
I understand and agree with you. I will review it.

**Comment by morbificagent** [comment]
As an selectable option this would be ok i think if the ppv user has entered his paypal adress in his profile (there isnt a field for it yet right?)

But this would only work for 1:1 transactions so the site owner hasnt the possibility to get something from the transaction.
The wallet seems to be the only way for 1:n transactions i think...

**Comment by morbificagent** [comment]
@DanielnetoDotCom 

Is there any changelog where we could see what new when you release an update of the plugins?

Like today i saw that there is 3.8 from ppv but i couldnt find out whats new there.
Eventually the correction of my described buying process? 😬

**Comment by DanielnetoDotCom** [comment]
Hi, no your buying process is not there yet, but it is probably a bug correction.

also, I guess it has the date expiration instead of the hours

**Comment by morbificagent** [comment]
No, the expiration date instead of hours isnt there too.

**Comment by morbificagent** [comment]
@DanielnetoDotCom 

Any news about this?
