### ISSUE TITLE
Remove Import video

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#4979]
how do i disable this?
I managed to remove Webm, but I can't remove Import video
![ssswq](https://user-images.githubusercontent.com/82677269/115268212-53bcf680-a13a-11eb-9132-c5bcb2118cf5.JPG)

**Comment by sharknetwork24** [comment]
I added the line you told me to add but it didn't go away.
Why?
Do I have to restart the server for the changes to take effect?
![dani45](https://user-images.githubusercontent.com/82677269/115316497-c6999200-a179-11eb-82e9-6014e6416ee8.JPG)

**Comment by sharknetwork24** [comment]
I tried to restart the server but it doesn't go away.
What should I do?

**Comment by DanielnetoDotCom** [comment]
What is the Encoder URL you are using?

can you please make sure you are using your own encoder? NOT the public one?

**Comment by DanielnetoDotCom** [comment]
Nevermind, I can see your parameter is overwrited ;

remove the line where is 

`$global['disableImportVideo'] = false;`

**Comment by sharknetwork24** [comment]
Perfect this way I solved.
Thanks Daniel

**Comment by sharknetwork24** [comment]
It's been a while since I disabled this feature and I don't remember the steps.
Daniel to restore everything first what should I do?
I want to put the Webm and Import Video button back
Can you kindly point me to the steps?
Thank you

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/issues/4979#issuecomment-823260771

**Comment by sharknetwork24** [comment]
This is the file that I need to modify but I noticed that the domain is the old one.
Why?
Tell me how to edit?
![Cattura](https://user-images.githubusercontent.com/82677269/119724646-48629680-be6f-11eb-99dd-1b909a39d37a.PNG)

**Comment by DanielnetoDotCom** [comment]
You are right regarding the domain, I should update it, please feel free to update it.

**Comment by sharknetwork24** [comment]
Can you tell me if everything is correct?
Can I make these changes?

![Cattura](https://user-images.githubusercontent.com/82677269/119733209-7b118c80-be79-11eb-93b0-145506aa9186.PNG)

**Comment by sharknetwork24** [comment]
![Cattura](https://user-images.githubusercontent.com/82677269/119733719-35a18f00-be7a-11eb-8175-d98f22bb3788.jpg)

**Comment by DanielnetoDotCom** [comment]
Domain seems to be right 

the disable import need to be = true

**Comment by sharknetwork24** [comment]
Can you take a screenshot for me?
Why does it have to be True?

**Comment by sharknetwork24** [comment]
Daniel one last thing,
I don't remember how to make the Webm button appear.
Can you tell me?
After this I can close the discussion.

![Cattura](https://user-images.githubusercontent.com/82677269/119735577-d6914980-be7c-11eb-8779-8828aa9f970f.PNG)

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/119822037-9ad0a100-bec9-11eb-9961-604ac3439a81.png)
