### ISSUE TITLE
Missing data from my videos uploaded to the platform?

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#4980]
Can you tell me why I can't see the data of my videos uploaded to the platform?
I've always seen the default videos uploaded by Daniel.
Can you help me solve this problem?
Thank you
![yyree](https://user-images.githubusercontent.com/82677269/115273226-91704e00-a13f-11eb-8b23-2b3e0646b1e7.JPG)

**Comment by DanielnetoDotCom** [comment]
Are the videos uploaded with the same user you are accessing the panel?


BTW, This panel is deprecated and will be replaced in the future.

**Comment by sharknetwork24** [comment]
Videos are uploaded by different users.
Why is it obsolete?
Which one should I use?

**Comment by milehighkaraoke** [comment]
Run this command, open a terminal inside your site folder

 sudo git pull

**Comment by milehighkaraoke** [comment]
Do the same inside your encoder folder

**Comment by milehighkaraoke** [comment]
This will bring you to the latest version. Update your plugins and enjoy

**Comment by DanielnetoDotCom** [comment]
> Videos are uploaded by different users.
> Why is it obsolete?
> Which one should I use?

I mean it will be replaced for another panel

**Comment by sharknetwork24** [comment]
I did as you told me.
I went to this directory:
cd / var / www / html / AVideo sudo git pull

Then:
cd / var / www / html / AVideo / Encoder sudo git pull

But despite all of this he hasn't made any changes.
It remained as before.
Can you explain what I have to do to view correctly?
Maybe I need to restart the server?
![mmmkl](https://user-images.githubusercontent.com/82677269/115415022-d905e100-a1f6-11eb-8db4-152c6e3485e2.jpg)

**Comment by jengajenga** [comment]
try run this command in the terminal. copy and paste it. it should change your permissions for the files and hopefully it'll work.

chown www-data:www-data  /var/www/html/AVideo/ -R

**Comment by sharknetwork24** [comment]
Nothing to do still doesn't work.
But is it possible to find out from Daniel why it doesn't work?

**Comment by DanielnetoDotCom** [comment]
@sharknetwork24 as I could see you have made the update correctly. as I told you the panel is obsolete and will be replaced in the future, there is no update on it.

**Comment by sharknetwork24** [comment]
I hope the update will be released as soon as possible because it is essential to understand which are the most viewed routes
