### ISSUE TITLE
PPV in Days

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4982]
I want to grant the ppv for a year but in hours it looks not so great.

Could you make it possible that it auto-changes the time-display to days if the value is > 48h

![Screenshot_20210419-202211_Chrome.jpg](https://user-images.githubusercontent.com/50199132/115284683-465d3780-a14d-11eb-858e-0887d7d4322b.jpg)

**Comment by DanielnetoDotCom** [comment]
I will release PPV V3.9 that will show an expiration date instead of the total hours, what do you think?

**Comment by morbificagent** [comment]
Yes that would be great!

**Comment by morbificagent** [comment]
Hi Daniel, any idea when you can release 3.9?

**Comment by DanielnetoDotCom** [comment]
Releasing now, please check in 30 min

**Comment by morbificagent** [comment]
Great!

Could you eventually correct the spelling?

It says: "Expires in 2021-05-23 14:51:09"
But it should be: "Expires at 2021-05-23 14:51:09"

(as i am german and not a native speaker correct me if im wrong ;-)

**Comment by DanielnetoDotCom** [comment]
I am Brazilian and also I am not sure.
But now you said that I guess the correct is "Expires on 2021-05-23 14:51:09"

**Comment by DanielnetoDotCom** [comment]
But based on this looks like "expires in" is correct

https://lingohelp.me/preposition-after-verb/expire-in-or-expire-on-or-expire-at/

**Comment by morbificagent** [comment]
Ok, than i havent said anything.

Like i said im not native so if there is nobody who sayes something against this we can leave it like that and i say many thanks!

**Comment by morbificagent** [comment]
@DanielnetoDotCom 

Have you changed it to "on" now?
Would be great so i can update my plugin and close the issue here.

Thanks

**Comment by DanielnetoDotCom** [comment]
The PPV version 4.0 should have "expires on"

**Comment by morbificagent** [comment]
Many Thanks Daniel
