### ISSUE TITLE
How to change the auto gen thumbnail width and height? 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4986]
Is there a setting that lets me tell the Thumbnail gen on ffmpeg to make it 1280x720?

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/115402658-fc626900-a1c1-11eb-85d1-e536dfd12217.png)

**Comment by JoshWho** [comment]
Thank you found it
