### ISSUE TITLE
Suggested videos for channels

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4987]
Hi Daniel,

At the moment it is possible to suggest a video as admin with the star so it is displayed in the big video carrousel on the first site.

The user has such an big video too in his channel.
But he hasnt the possibility to select a video from his files for displaying here:

![Screenshot_20210420-063325_Chrome.jpg](https://user-images.githubusercontent.com/50199132/115338409-117bcf80-a1a3-11eb-8f7d-223289673791.jpg)

Wouldnt it be nice if he could make a suggestion like the admin with this star only for his channel?

So he could promote Videos he finds really great.

**Comment by DanielnetoDotCom** [comment]
You are right, I may add this in a future update.

thanks for the idea
