### ISSUE TITLE
ZoomMeetingRecorder owner match dont work

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4988]
In the Wiki there is written:

"If you set the parameter to 0 (zero) and the Zoom hoster's email matches any AVideo user's e-mail we will use this user as the owner."

But this doesnt work. Here the parameter is set to 0, the zoom-user and the avideo-user have the same e-mail configured but everytime the recorded videos are owned by admin.

Its very frustrating. Every plugin i buy needs to be debugged first.
They should be working if i have to spend money for them.
If there is a problem here and there... ok... no problem... But i think i have opened tonns of bug reports here in the last weeks for payed plugins :-(

It would be really great Daniel if you would consider make something free for the users here which are helping with their reports to make your payed plugins work like they should do. 
I know you are working hard on this project but its our time too and we spent money for reporting bugs, testing, and all this.

**Comment by morbificagent** [comment]
Sorry for that. Was a little bit frustrated because of the next problem to work on.

**Comment by DanielnetoDotCom** [comment]
"If you set the parameter to 0 (zero) and the Zoom hoster's email matches any AVideo user's e-mail we will use this user as the owner."

are you sure you have only one user with that email?

emails may be duplicated between users.

**Comment by morbificagent** [comment]
Yes i am.
there are only two users with @bit-link.de in my avideo install. admin and alex.
In zoom there is only alex:

<img width="505" alt="Screenshot at Apr 20 15-53-30" src="https://user-images.githubusercontent.com/50199132/115408139-eae48580-a1f0-11eb-989d-b53e27795e90.png">

And here in avideo:
<img width="672" alt="Screenshot at Apr 20 15-55-37" src="https://user-images.githubusercontent.com/50199132/115408158-ef10a300-a1f0-11eb-841a-bb43155d5454.png">

But the recordings are going to admin instead of alex

**Comment by DanielnetoDotCom** [comment]
can you please screenshot how your ZoomMeetingRecorder looks like?

**Comment by morbificagent** [comment]
<img width="600" alt="Screenshot at Apr 20 16-11-14" src="https://user-images.githubusercontent.com/50199132/115410604-0ea8cb00-a1f3-11eb-96b8-627c02891134.png">

**Comment by DanielnetoDotCom** [comment]
can you please check in your logs where there is something like this

`ZoomMeetingRecorder ....`

**Comment by DanielnetoDotCom** [comment]
Ok, I have some updates for ZoomMeetingRecorder, please try version 2.0

**Comment by morbificagent** [comment]
Here is the log in which you can see the hoster adress and the wrong user:

<img width="1141" alt="Screenshot at Apr 20 16-21-25" src="https://user-images.githubusercontent.com/50199132/115412366-875c5700-a1f4-11eb-96b1-ee5777bb6b9c.png">

Will try the update now...

**Comment by DanielnetoDotCom** [comment]
The update was sent, please try that version 2.0

**Comment by morbificagent** [comment]
<img width="1144" alt="Screenshot at Apr 20 16-30-44" src="https://user-images.githubusercontent.com/50199132/115413805-c939cd00-a1f5-11eb-9995-225a1674f80f.png">

Now it is broken

**Comment by DanielnetoDotCom** [comment]
Make a `git pull`

you are not running the latest

**Comment by morbificagent** [comment]
OK, with a pull its working again but the problem is still there.
admin gets the owner:

![image](https://user-images.githubusercontent.com/50199132/115430835-02c60480-a205-11eb-92fc-e273ea235626.png)

**Comment by DanielnetoDotCom** [comment]
can you please screenshot a bit above that? about 10 lines above

**Comment by morbificagent** [comment]
there is nothing im the log from the zoom plugin before:

![image](https://user-images.githubusercontent.com/50199132/115442289-22175e80-a212-11eb-9d7f-9f1c732dca16.png)

**Comment by morbificagent** [comment]
And the last commit with the trim doesnt help too... Have tested it some minutes ago.

**Comment by DanielnetoDotCom** [comment]
Hi, sorry about that, I think I found the problem, please download the plugin version 2.1

**Comment by morbificagent** [comment]
👍👍👍

Looks god

Thank you Daniel
