### ISSUE TITLE
CDN in Custom Advance is changing live player stream m3u8 address

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#4989]
i am trying to use another domain for cdn and thought i had it successfull but now the live streams r trying to generate a m3u off the cdn and not my website domain

i have https://joshwho-cdn.com setup in the cdn field in custom advance

Error when trying to watch a live stream

`Access to XMLHttpRequest at 'https://joshwho-cdn.com/601ae8cac2465/index.m3u8' from origin 'https://www.joshwhotv.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by JoshWho** [comment]
![cdnhelp](https://user-images.githubusercontent.com/39392449/115390107-7e8f6500-a1a3-11eb-8aa5-6b7548d12322.jpg)

**Comment by JoshWho** [comment]
When I disable the cdn in the Custom advance it makes the m3u8 link https://live.joshwhotv.com:444/live/601ae8cac2465/index.m3u8

**Comment by DanielnetoDotCom** [comment]
I have sent you some update and your CDN is enabled now, please confirm

**Comment by JoshWho** [comment]
Yes works great now. Thank you
