### ISSUE TITLE
bug CDN

### ISSUE THREAD

**Issue by syldri** [WWBN/AVideo#4990]
I wanted to do a test to activate the cdn
you can see it the site is distorted and i can't delete the cdn

![image](https://user-images.githubusercontent.com/39193219/115407750-98a36480-a1f0-11eb-9370-f0e8a09c0f70.png)

![image](https://user-images.githubusercontent.com/39193219/115408522-36972f00-a1f1-11eb-932d-87bb71bc1f28.png)

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/115410550-1ce1f180-a1c9-11eb-9a53-5e8c8e48410f.png)


if you can please delete the plugin line from your database

`DELETE FROM `plugins` WHERE (`name` = 'CDN');`

**Comment by syldri** [comment]
this is where I added the cdn


![image](https://user-images.githubusercontent.com/39193219/115416884-701f6880-a1f8-11eb-9949-d909aefc804b.png)

**Comment by syldri** [comment]
I have not activated the cdn plugin
I have been in CustomizeAdvanced 
and I added the cdn link

![image](https://user-images.githubusercontent.com/39193219/115419028-48310480-a1fa-11eb-8bd7-ddd70d2ff02a.png)

**Comment by DanielnetoDotCom** [comment]
Ok, but the CDN link in the image is for the demo site.

and yes that is the correct place to add the CDN

**Comment by syldri** [comment]
when I add them my site is distorting

**Comment by DanielnetoDotCom** [comment]
what exactly are you adding?

**Comment by syldri** [comment]
i can't go back to delete it 

![image](https://user-images.githubusercontent.com/39193219/115420217-40be2b00-a1fb-11eb-8565-8597b4c5bfae.png)

**Comment by syldri** [comment]
I put
 the cdn link https://cdn.*****.tv/

**Comment by DanielnetoDotCom** [comment]
where did you get https://cdn.*****.tv/ from??

what company are you using?

**Comment by syldri** [comment]
https://bunny.net/

**Comment by DanielnetoDotCom** [comment]
ok, so it should work

access https://cdn.*****.tv/ and see if you can see your site (even with the siteCDN blank). if you can you should be fine

**Comment by syldri** [comment]
I want to remove the link of the cdn impossible to go to the administration

**Comment by DanielnetoDotCom** [comment]
add this in your configuration.php

`$global['ignoreCDN'] = 1;`

**Comment by syldri** [comment]
thank you so much :;)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom another global hidden option ... Just added to the wiki
