### ISSUE TITLE
LiveUsers Update procedure

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#4991]
I was able to update almost everything.
The only plugin I couldn't update is Live user, which I don't know how to update.
![rrt6](https://user-images.githubusercontent.com/82677269/115415982-a5778680-a1f7-11eb-9041-688c49096471.JPG)

Can you explain me the correct procedure to update?
Thank you

**Comment by sharknetwork24** [comment]
![54jju](https://user-images.githubusercontent.com/82677269/115416300-f12a3000-a1f7-11eb-9b0b-d2ed522683e2.JPG)

**Comment by DanielnetoDotCom** [comment]
LiveUsers is a paid plugin, you will need to download it again from the market place
https://youphp.tube/marketplace/

If you do not have a user yet, make sure you create an account, and email me your user #.

I will enable your plugins to download

**Comment by sharknetwork24** [comment]
I have already downloaded and copied inside the LiveUsers folder and then launched the update.
I succeeded perfectly.
Thanks Daniel
