### ISSUE TITLE
PPV Questions 

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#4994]
Can anybody explain for what this menue is?

![Screenshot_20210421-180503_Chrome.jpg](https://user-images.githubusercontent.com/50199132/115589156-d1663b00-a2cf-11eb-9346-d1374f9c27a4.jpg)

Looks like i can add a user to a plan... Dont understand that as i add videos to a plan normally.

And the payed value?

What is this

**Comment by morbificagent** [comment]
And second question:

Is there any possibility to see how many people have bought a specific PPV Object?

Cant find any possibility. In the yptwallet where the money comes in there is no information from where it comes... Was hoping there is something like 

"+ 5 USD because userX bought PPV VideoX"

So no way to get this simple information?

**Comment by DanielnetoDotCom** [comment]
> Looks like i can add a user to a plan... Dont understand that as i add videos to a plan normally.

This is in case if you want to manually add a user to s aplan

> Is there any possibility to see how many people have bought a specific PPV Object?

Not yet, also because users can PPV a user group (for a bunch of videos)
but I guess it is necessary and it will be added in the future. at least an option to get some reports

> Cant find any possibility. In the yptwallet where the money comes in there is no information from where it comes... Was hoping there is something like

Also it may be a good option, Agree it may be added as well

> Or eventually a little counter next to the video under "My Videos" which counts Up if someone bought.

Agree

**Comment by morbificagent** [comment]
Hi Daniel,

thanks for the info...

Could you explain what the "payed value" is for? i can enter some value there but is it used anywhere for anything?

**Comment by DanielnetoDotCom** [comment]
"payed value" if just for the records, for future control
