### ISSUE TITLE
Missing delete and refresh buttons on encoder

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4996]
The Queue Log doesn't show the encoded file and I cannot delete or refresh files. This encoder is running on the live server, it doesn't have a site on it, just a remote rtmp server. When I access the encoder either directly or through the Network Encoder
I do not see those options anymore as I do with all encoders. It is not opened from any site but all sites can see the encoder on the list and use it.

![Screen Shot 5781-08-10 at 0 33 14](https://user-images.githubusercontent.com/58882903/115627639-08f0d980-a308-11eb-929c-6d5995e3e308.jpg)

![Screen Shot 5781-08-10 at 1 10 00](https://user-images.githubusercontent.com/58882903/115627428-a5ff4280-a307-11eb-9fdf-f526c46435b8.jpg)

**Comment by milehighkaraoke** [comment]
Log into encoder as an encoder administrator

**Comment by guymass** [comment]
I have, I think. The problem is which streamer site do I put in? as there is no site attached to it, I can login from any of my sites but only one will display all the tabs, which appears to be the admin panel, but I cannot view the queue or manage it.
![Screen Shot 5781-08-10 at 11 36 05](https://user-images.githubusercontent.com/58882903/115683295-f786ec00-a35e-11eb-9dfa-8c6cc35b9ebe.jpg)

Do Encoders must also have a site setup with them? because I only setup an encoder on that server where other sites/servers connect to it to live stream or encode a file.

**Comment by milehighkaraoke** [comment]
You will have to make admin account  by going to your encoder/install  open terminal in install and run the  sudo php make admin

**Comment by guymass** [comment]
Fixed, I reinstalled and now it seems to work fine.
