### ISSUE TITLE
Live stream not playgin - Access to xmlHttpRequest

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#4999]
So I closed and solved the encoder issue on my test server. Everything is ok with the encoder, I can stream and the file is being created, how ever it doesn't connect to the player due to this error regarding cross site security.

I think I need to add something in the nginx/apache config header section but im not sure. Here are the screen shots of my browser.

![Screen Shot 5781-08-10 at 12 14 06](https://user-images.githubusercontent.com/58882903/115689478-c9a4a600-a364-11eb-8bc4-f166d8ee75ce.jpg)
![Screen Shot 5781-08-10 at 12 13 51](https://user-images.githubusercontent.com/58882903/115689495-cdd0c380-a364-11eb-9e25-635013d5309b.jpg)

would the configuration need to be on the remote test server or the local one or both?

**Comment by guymass** [comment]
This is how my server CORS is configured:

server {
                    listen 8443 ssl;
                    ssl_certificate /etc/letsencrypt/live/rtmp.flatearth.co.il/fullchain.pem;
                    ssl_certificate_key /etc/letsencrypt/live/rtmp.flatearth.co.il/privkey.pem; # managed by Certbot
                    #include /etc/letsencrypt/options-ssl-nginx.conf;
                    #ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 

                    #listen [::]:8443 ssl;
                    #include /usr/local/nginx/snippets/self-signed.conf;
                    #include /usr/local/nginx/snippets/ssl-params.conf;
                    listen 8080;
                    server_name rtmp.flatearth.co.il;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stre>
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }

**Comment by guymass** [comment]
I am getting these errors again after working on another site and creating some new nginx configs and cerbot ssl certificated, and now suddenly again the player doesn't want to play the stream.

This is very frustrating!

![Screen Shot 5781-08-13 at 2 22 31](https://user-images.githubusercontent.com/58882903/115975392-207ccc00-a56d-11eb-8a9e-520ca14f2ae4.jpg)

**Comment by guymass** [comment]
It keeps using a wrong key and although I can see now the stream on my channel, I cannot see it on the live stream page.
It is showing on front page.

It looks like the stats page is sometimes not passing the correct url with the correct key. Whenever I change settings it will change the key and I think this is not getting cleared properly on every change. When I start streaming sometime it shows the old key like in the following screenshot:


![Screen Shot 5781-08-13 at 2 50 48](https://user-images.githubusercontent.com/58882903/115975916-88cdac80-a571-11eb-9cc2-7e8ed78acb8e.jpg)

**Comment by akhilleusuggo** [comment]
maybe it's a URL issue ( where it's pointing ).
I had this issue too. But if you browse your live from the notification should bring the right URL

**Comment by DanielnetoDotCom** [comment]
I guess the option allowMultipleLivesPerUser are confusing people.

I just sent a version that will handle the keys better and reuse them in case they are offline.

**Comment by akhilleusuggo** [comment]
Still same issue. I just installed a new installation to test things out, and the issue persists

**Comment by DanielnetoDotCom** [comment]
Sorry, this morning I sent also new updates.

@akhilleusuggo what issue are you having?

**Comment by akhilleusuggo** [comment]
Hi @DanielnetoDotCom I've updated , but still same issue.
`Access to XMLHttpRequest at 'http://192.168.0.125:8080/live/6087020122f50-181009/0.ts' from origin 'http://192.168.0.125' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by guymass** [comment]
This is the error I get, but could be my own config not sure yet.

![Screen Shot 5781-08-15 at 19 39 34](https://user-images.githubusercontent.com/58882903/116279599-65cd1380-a790-11eb-9cf4-300de6ed623d.jpg)

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo this is the config I am using 

https://github.com/WWBN/AVideo/blob/fe8f097620b5521cfade904e0f9f43e7e9d8f7fd/plugin/Live/install/nginx.conf#L69-L82

@guymass your error is something else, it looks like a plugin missconfiguration

**Comment by guymass** [comment]
Ok I managed to find my configuration error and now I have both sites local and remote as live server and are working, I simply forgot to edit the files for getRemoteFile.php to point to the correct server from live server. However I do not have restream working and I see this new PHP message showing in logs.

![Screen Shot 5781-08-16 at 16 57 30](https://user-images.githubusercontent.com/58882903/116416511-13006400-a843-11eb-8c9a-2de523e435c0.jpg)

**Comment by DanielnetoDotCom** [comment]
Update the git pull from 1 hour ago, the error may not happen anymore

**Comment by guymass** [comment]
Cool Great! Restream is working now! Gonna leave it open till we do some more testing.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I fixed my issue by commenting out this line; 

https://github.com/WWBN/AVideo/blob/e749b660085fa7be5a0719cc3dcb1fd384c75939/plugin/Live/install/nginx.conf#L70

**Comment by DanielnetoDotCom** [comment]
not sure what is the error on this line, but we will need a way to tell the CDN to not cache .m3u8 files and cache the .ts files

**Comment by guymass** [comment]
Well restream stopped working again for some reason, idk yet why, we've been testing and it was ok after last pull and than again some errors on log.

![Screen Shot 5781-08-18 at 14 55 45](https://user-images.githubusercontent.com/58882903/116691987-51715c80-a9c4-11eb-8a2f-5e072d80b425.jpg)

**Comment by guymass** [comment]
Ok seen the new update. Made the update only on our edu/test server for now. I can restream from one site to the next. I will keep testing with other team members as I do not use FB not any other platform to stream to. I will ask those who do and update if restream is working as well for other sources such as FB, YT etc...

**Comment by guymass** [comment]
> @DanielnetoDotCom I fixed my issue by commenting out this line;
> 
> https://github.com/WWBN/AVideo/blob/e749b660085fa7be5a0719cc3dcb1fd384c75939/plugin/Live/install/nginx.conf#L70

I don't this we use this file or file path in our config but you think the whole block should be removed?

**Comment by guymass** [comment]
I stopped my live stream test over an hour ago, I was restreaming from our main site to edu/test site and it stills shows the live stream stuck on the edu site. Cleared cache, I am not streaming currently, this should have stopped I think.

![Screen Shot 5781-08-18 at 15 21 35](https://user-images.githubusercontent.com/58882903/116699894-ccd80b80-a9ce-11eb-8ba2-3be29dd38656.jpg)

**Comment by akhilleusuggo** [comment]
I believe that the implementation of CDN plugin gonna break the installation of most people. I would like to request care when implementing this plugin @DanielnetoDotCom , not everybody gonna use it, each has a custom installation and this feature doesn't work on localhost, intranet & private network installations.

At this point it's like obligating users to enable the plugin.

@guymass It's because you have an outdated config. The config does't automatically update, only manual changes takes effect ofc. For automatic updates, maybe a symbolic link would be required , also overwrite your changes.

https://github.com/WWBN/AVideo/blob/master/plugin/Live/install/nginx.conf

**Comment by guymass** [comment]
akhilleusuggo is correct, we also have our own unique config which we don't want to break, but it seems we must update in order to fix bugs so sometimes those updates can take us offline for some time.

**Comment by DanielnetoDotCom** [comment]
@akhilleusuggo the CDN plugin still in development and I do not recommend doing it right now.

but in all cases to use CDN on the Livestream we need to allow cache on the .ts (ONLY) files and do not cache the .m3u8 files., do you have any suggestion?

if we do not add this live we will not be able to use a CDN on the livestream. a CDN on the livestream will increase a lot the capacity of the total concurrent users on it.

also, I do recommend for a CDN a hls_playlist_length parameter

why is the `location ~ \.m3u8$ {` is not working for you?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Probably because it keeps requesting it over and over again. 
The `.ts` files gives errors and the video doesn't load. Commenting out this line fixed my issue.

For my understanding the location is wrong. `~ \.m3u8$` Where is that pointing ? to my knowledge the location should be something like this `~.*\.m3u8$` or `~.*\.m3u8\$`

Another thing we can do is adding it on the m3u8 file. Not sure if it's still supported.

```
#EXTM3U
#EXT-X-TARGETDURATION:X
#EXT-X-ALLOW-CACHE:NO
#EXT-X-MEDIA-SEQUENCE:XX
```

**Comment by DanielnetoDotCom** [comment]
I just add some more cache info, that is needed for CDNs

https://github.com/WWBN/AVideo/blob/9d81c1262afa9906522ff2013a795fce1a8225cc/plugin/Live/install/nginx.conf#L88-L103

I guess `~ \.m3u8$` means anything that ends with m3u8, same as `~.*\.m3u8$`

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom sync 500ms;

Will fix and make sure that the audio and video are synchronized by the end user. Some servers with low frequency can't keep up the audio encoding due to lack of support for multi-threading tasks for audio. Also bandwidth plays a roll.
Default is actually 300ms, but it's too heavy for the server. 500 is good since we need a GOP of 2, so the fix will be checked every keyframe.

Officlal description from rep ;

Synchronize audio and video streams. If subscriber bandwidth is not enough to receive data at publisher rate, some frames are dropped by server. This leads to synchronization problem. When timestamp difference exceeds the value specified as sync argument an absolute frame is sent fixing that. Default is 300ms.
