### ISSUE TITLE
Change background in Meet?

### ISSUE THREAD

**Issue by peterflitz** [WWBN/AVideo#5000]
Is it possible to overwrite the background in Meet?
Color or image.

**Comment by peterflitz** [comment]
@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Probably yes, but this requires some code. we may add this in the future.

**Comment by peterflitz** [comment]
ok, thanks for the answer.

I think it's important to be able to match the color of the meet to the website :-)
