### ISSUE TITLE
Ads plugin causing videos to hang

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5001]
This is an issue with the ADs plugin. We have ads setup to be shown every few videos however on the mobile app once the ad is loaded it hangs the video and its stuck on buffering circle. Whether we setup the adds to be show every 1, 3 or 5 videos, once the ad starts it hangs the video so you need to exit the page and open the video again for it to start playing.

This is happening only in mobiles, for both the app and mobile browser.

On desktop it works fine.

**Comment by DanielnetoDotCom** [comment]
maybe you add on the ADs plugin some javascript that is breaking your videos.

**Comment by guymass** [comment]
no code added, we have simply used the plugin options, but I will keep testing more this week to see if there are any log messages.
