### ISSUE TITLE
Some unknown error on browser console

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5002]
Not sure where this goes but here is a screenshot, idk what it effects but could be the article plugin.
![Screen Shot 5781-08-10 at 21 27 33](https://user-images.githubusercontent.com/58882903/115767437-d26f9900-a3b1-11eb-9fb0-14afe6378e8c.jpg)

**Comment by DanielnetoDotCom** [comment]
from what page does this come from?

**Comment by guymass** [comment]
Home page
