### ISSUE TITLE
robots.txt missing Live Links to allow

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5003]
Need to add

Allow: /plugin/LiveLink/?*

 to robots.txt  OG image is blocked by robots according to twitterbot.

Tested on LiveLink https://www.joshwhotv.com/liveLink/36/nasa-tv

**Comment by DanielnetoDotCom** [comment]
Done, added.

also now you can customize your robots.txt here

![image](https://user-images.githubusercontent.com/18009293/116079903-c8c68980-a66e-11eb-95bb-32c1d61cd9ba.png)

**Comment by JoshWho** [comment]
O kewl did not see that, Thank you
