### ISSUE TITLE
Like Meet can we ingest zoom in Avideo platform

### ISSUE THREAD

**Issue by nikstream** [WWBN/AVideo#5005]
Hi Daniel,

Can Avideo platform be coded to ingest zoom instead of   Meet.

**Comment by DanielnetoDotCom** [comment]
Sorry, we cannot do it.

but you can save zoom meetings record
https://github.com/WWBN/AVideo/wiki/ZoomMeetingRecorder-Plugin

**Comment by morbificagent** [comment]
Yes its working good for autoimporting Zoom-Meetings which are recorded with the Zoom-Buildin Cloudrecording.
But keep in mind that the quality of the zoom recording isnt great and far away from FullHD when using their cloudrecording.
But thats nothing Daniel can do against this.

But eventually i can ask a question at this point:

Is it possible to connect more than one Zoom-Account to Avideo via the plugin or would this make the plugin goes crazy?

**Comment by DanielnetoDotCom** [comment]
Thanks, but currently there is a place for only one zoom key
maybe we allow users to add their own zoom keys so we will also be able to get their recorded files
