### ISSUE TITLE
Subtitle plugin to support embedded subtitles and the .ass extension.

### ISSUE THREAD

**Issue by Social-Loafer** [WWBN/AVideo#5006]
All videos I have, already have embedded subtitles of which are the .ass extension.
Would be very nice to have the Subtitle plugin support embedded subtitles and to support the .ass extension as well.

Having to upload subtitles for many videos is very time consuming.

Also for some reason even the ones for .srt .vtt show up as Closed caption 'CC' instead of as a subtitle after upload and show the black bar on playback which is very annoying.

**Comment by DanielnetoDotCom** [comment]
Hi, I do not know .ass

can you please give a video and subtitle file sample so I can check

**Comment by Social-Loafer** [comment]
Its also known as .ssa
Here is the wiki on it: https://en.wikipedia.org/wiki/SubStation_Alpha

Really I'd be more interested in having the plugin support embedded subtitles as I could convert to .srt and re-embed them to the videos via scripting & ffmpeg. Saves alot of time only having to upload video files that have the embedded subtitle.

**Comment by DanielnetoDotCom** [comment]
but does the embed subtitle works on HTML 5 players?

I do not think so.

**Comment by Social-Loafer** [comment]
I think you are correct on that, but it seems that uploading a .srt file, that the plugin is converting that to a .vtt file from what i see in the logs, seems if that's the case, maybe when uploading a video file you could have the plugin check to see if its embedded with subtitles and if its there then extract the subtitles? 
I don't want to cause you too much work, but it would be awesome.

**Comment by DanielnetoDotCom** [comment]
Maybe we add it in the future
