### ISSUE TITLE
Issue on Mobile iPhone App when playing videos

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5007]
I am receiving the following user experience issue from one of our members. As I have no way to show screenshots, as most of them do not know how to pass that info to us, I can only describe what they are experiencing.

This issue as far as I know occurs on the iphone version. This happens on any video they wish to view. When they start the video if during the play time they need to answer a call or leave the app to another window, when they get back to the video they need to start is again from the beginning.

**Comment by guymass** [comment]
This video was stream from the mobile app, as you can see in the end it is encoded as "other" and it is now unavailable for viewing on the site as we get an error indicating the file is doesn't exist.

This is a main feature and must be fixed.

![Screen Shot 5781-08-13 at 21 40 28](https://user-images.githubusercontent.com/58882903/116005315-101d2d80-a60f-11eb-8f0a-80747d005a95.jpg)

**Comment by DanielnetoDotCom** [comment]
as long as the video is on your streamer and has the correct file length and size I only can assume the problem is between your encoder/streamer. you may want to check the logs
