### ISSUE TITLE
Option to start live from the beginning of the hls-playlistlenght

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#5008]
It would be very great itlf there were the possibility to start the live stream at his beginning like the VOD Hls Videos!

Would it or is it possible somehow?

I know its possible manually to select a time before in the player but i mean as default if selected in the options.

**Comment by morbificagent** [comment]
Have found something which sounds like the function i am asking for.

But as i cant write php i am not able to make a test-implementation...



![Screenshot_20210424-194843_GitHub.jpg](https://user-images.githubusercontent.com/50199132/115973934-f8836d80-a558-11eb-901d-807e4fa97d3c.jpg)

@DanielnetoDotCom would it be possible to make an option under the live plugin options out of that?

**Comment by DanielnetoDotCom** [comment]
It may be able to be done but require some code for sure.

If you are willing to pay for that change you can email me at developer@youphptube.com for this customization.

 I need to make clear to you everything I develop I will keep the rights to incorporate on the main project or resell it.

**Comment by morbificagent** [comment]
OK, i will do so, Thanks Daniel
