### ISSUE TITLE
LDAP Plugin issue

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5010]
We are using the LDAP plugin so we can eventually have a central authentication point for our users. Currently LDAP plugin onyl allows authentication however this create a problem, because a user that registers to our site will only be registered on that site and the registration process doesn't take ldap into account.

Also I am not sure how it works if an ldap user that didn't register to the site is logging in and how does his profile and user is created in the AVideo database. I presume that it creates one as the main login does.

We would consider paying to extend the plugin to include registration to ldap if this is possible.

**Comment by DanielnetoDotCom** [comment]
All registrations must be made on your LDAP side.

if you want to centralize the users, you will need to disable the site signup and allow users to signup only into your LDAP enviroment.

**Comment by guymass** [comment]
Can this signup be from AVideo? or do we need to setup something of our own?  I think that if you added that feature that would make the ldap plugin more complete.

**Comment by DanielnetoDotCom** [comment]
LDAP is a different product, that can be used for multiple applications.
currently, I have no plans to write into LDAP server.
