### ISSUE TITLE
Enabling downloads for users? Can it be done?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5011]
**Describe the question**
I'm following the steps that I believe will enable downloads for users. It's not working out.

**Screenshots**
I believe I have things enabled so that users can download files. Either I'm not understanding the intent, or something is lying to me. Let's review.

Admin panel -> Site Settings -> Advanced -Configuration >  -> Allow download video is ON

![Screen Shot 2021-04-25 at 2 53 37 PM](https://user-images.githubusercontent.com/11711050/116010769-07f4cc00-a5d6-11eb-9db1-b8ed7dfa4cc0.png)

Plugins -> CustomizeUser ->  userCanAllowFilesDownload -  Placebo has more effect than these controls, they simply do not work at all.

https://user-images.githubusercontent.com/11711050/116011042-acc3d900-a5d7-11eb-8e85-4afc11359ec7.mov

But all right, let's check the file anyway and see if we can download it.

![Screen Shot 2021-04-25 at 2 49 34 PM](https://user-images.githubusercontent.com/11711050/116010935-e34d2400-a5d6-11eb-9d61-13a22c4d612f.png)

Here, we can download from the admin UI, but it says that download is disabled. Let's click here and see what it says?

![Screen Shot 2021-04-25 at 2 49 41 PM](https://user-images.githubusercontent.com/11711050/116010953-fe1f9880-a5d6-11eb-9648-ab3f02c7ffd2.png)

Well that's odd. It says that it can be downloaded. Surely one of these two pieces of UI are lying?

![Screen Shot 2021-04-25 at 3 01 57 PM](https://user-images.githubusercontent.com/11711050/116010981-345d1800-a5d7-11eb-8ce1-39b88f16ee78.png)

User has no controls for download. Ergo, I assume the dialog box claiming the file can be download is lying. 

How do you enable downloads for files? Please advise.

**Comment by milehighkaraoke** [comment]
Admin panel/settings/ site settings.   Authenticated users can upload

**Comment by DanielnetoDotCom** [comment]
This also confuses me.

did you try to clear the cache?

**Comment by walt93** [comment]
If by clear the cache, you mean the three-step ritual of clearing the first page cache, clearing the cache directory, and generate sitemap - yes, I hit those placebo buttons all the time.

Do they do anything?

I've tried every which way to enable downloads? I have no idea what any of these controls do?

Some controls you can change. Some controls you can't change. The site was whacked when I installed it myself. I reformatted the site and paid an expert to install it. I still have these problems.

I've tried to update the plugins as recommended. I've uploaded them. Nothing happens. From the plug-ins page there is a link that says "update me" and it takes you to the plugins page. Where you download the plugin again. and upload the plugin again. hoping the system will notice it the second or third time. But no...

Please advise. Thanks.

**Comment by milehighkaraoke** [comment]
Yes, I also have had update issues with the plugins. I found it helps to do update directly from the server and logged in as Admin

**Comment by milehighkaraoke** [comment]
Also sometimes doing a git pull after you download and install plugin helps.

**Comment by walt93** [comment]
It seems that after uploading the plug-ins, if you come back to the site several hours later, the plug-ins appear to be updated. I didn't think to take screenshots before and after to know from version numbers.

Lets try a basic question. Is it possible to enable downloads, or is this feature a placebo? 

If it works for anyone at all, where does enabling of downloads manifest? Can someone post a screenshot of what I'm supposed to be looking for? I'm 99% sure that either this feature never worked at all, or, my site is broken and won't let me enable what needs to be enabled, but, can someone *please* tell me what I'm *supposed* to do here?

**Comment by walt93** [comment]
![Uploading Screen Shot 2021-05-02 at 5.15.24 PM.png…]()

I've gotten as far as this. I'm not sure who is supposed to be able to download, or where they do that, but this seems like progress.

**Comment by milehighkaraoke** [comment]
Yes that is the only button that you should need to slide over to enable downloads. I do have it working on my site

**Comment by milehighkaraoke** [comment]
Everybody is able to download and the download button should be below the video

**Comment by walt93** [comment]
Checking some hours later, the plug-ins appear to be updated.

Can you drop a screenshot of where downloads are enabled? What am I supposed to be looking for?

**Comment by milehighkaraoke** [comment]
![20210502_182837](https://user-images.githubusercontent.com/70327833/116832995-5bd25880-ab74-11eb-90a7-9f4a06994032.jpg)
![20210502_182854](https://user-images.githubusercontent.com/70327833/116832996-5c6aef00-ab74-11eb-8540-2ed5e8bca86e.jpg)

**Comment by walt93** [comment]
Ok I had the main one in site settings. I just got downloads enabled. Thanks for your help.

The TL;dr is my site is behaving super strange, changing settings in places like CustomizeUser plugin - don't take effect immediately but do change after some time - its enough to drive one mad.

**Comment by milehighkaraoke** [comment]
It is definitely work in progress, We all try and help others on here with things we have learned along the way  so Dan can stay focused on the main development and bugs.......

**Comment by walt93** [comment]
I was mistaken earlier, for some reason I wasn't seeing the upgrade messages. They're all still there. How do you upgrade plugins? 
![Screen Shot 2021-05-02 at 8 37 42 PM](https://user-images.githubusercontent.com/11711050/116839219-54b44600-ab86-11eb-89b9-cd519806ee82.png)

Clicking the Update Available takes one to the downloads page. Downloading that zip file, and uploading it here:

![Screen Shot 2021-05-02 at 8 38 58 PM](https://user-images.githubusercontent.com/11711050/116839257-7f060380-ab86-11eb-8e12-bcbf16ce3ff9.png)
![Screen Shot 2021-05-02 at 8 39 04 PM](https://user-images.githubusercontent.com/11711050/116839259-80cfc700-ab86-11eb-96a3-3b2bcad3240b.png)

does not update the plug-in. Where do you go to update plugins?

**Comment by DanielnetoDotCom** [comment]
Maybe you need to manually delete the plugin and upload it again.

or maybe change the plugins folders permissions

**Comment by akhilleusuggo** [comment]
We have also duplicated options on multiple places.

**Comment by walt93** [comment]
After an inordinate amount of messing with settings, it's working. It seems that I had turned on some setting in CustomizeUser that enabled per-video toggling of sharing.
