### ISSUE TITLE
Top Navbar edit/delete? How To

### ISSUE THREAD

**Issue by RememberForgottenHits** [WWBN/AVideo#5013]
Hi gays! 

First of all, many thanks for the great platform! I've only been using it for about a week and just getting acquainted and setting it up! But this is the best solution I have tested among many!

Simple question, how can i change or delete this menu? 

There are currently options in the menu:
 Text 1 = https://yahoo.com
 Text 2 = https://google.com
 
 Avideo installed version is 10.5

![TOP-NAV-BAR](https://user-images.githubusercontent.com/34457020/116086205-3b079000-a6a8-11eb-83aa-9abe6f963ec1.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure where this comes from, try to disable some plugins and clear the cache.

Maybe the Notification plugin

**Comment by RememberForgottenHits** [comment]
Thanks for replying! ;)

I have tried to disable plugins and cleared the cache, it has not helped. 

This seems to be some kind of menu with no notifications. Clicking on the bell will open a drop-down menu with the options "text 2" and "text 1" with links as I wrote in the first post.

**Comment by DanielnetoDotCom** [comment]
Definitely, this is something you configure in some plugin. I do not remember where it comes from. 

If you cannot find where does it come from, you can truncate the plugins table, it will reset all the plugins, and you can start again.

**Comment by RememberForgottenHits** [comment]
This problem only affects me. I just installed AVideo platform on the another test server and there is no this menu and choises. If I later find the cause of this problem, I will write it here

Thank you for thinking along.
