### ISSUE TITLE
Hide the information of who uploaded the video and how long ago?

### ISSUE THREAD

**Issue by lerd2805** [WWBN/AVideo#5015]
Hi @DanielnetoDotCom,

Is it possible to hide the information of who uploaded the video and how long ago?

![image](https://user-images.githubusercontent.com/31492754/116116268-92920580-a680-11eb-8fb4-934f4218f948.png)

**Comment by DanielnetoDotCom** [comment]
Currently we do not have this option

**Comment by lerd2805** [comment]
Hi @DanielnetoDotCom,

Can you add it? Or at least you could tell me how I could hide it manually?

**Comment by DanielnetoDotCom** [comment]
you can try to use CSS to hide it
