### ISSUE TITLE
Search Not finding simple things anymore

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5019]
This was a support ticket I received.

`Good Day!

I was just wondering what I need to do to get my channel name to actually show up when BLUE is entered into the search bar.
When I first started my channel, it would come up when searched but now it instead of BLUE coming up when BLUE is searched,
channels that don't even have BLUE in the name come up instead.
(The first hing to come up is a channel "z" , followed by other random channels that don't even have BLUE in the names....)
I have added BLUE tags to everything, and not sure why it used to come up and now all the other channels come up instead.
Can you please help me correct this?

Thanks for your help!
Blue`

I have also tried the search "blue" and his channel no longer shows and I see old channels like the Z account showing.

**Comment by morbificagent** [comment]
Can confirm as i havent any search results at the moment.

Sometimes i find a searchterm which is working but in generally the search isnt working.
(the live search pluging is doing well)

**Comment by DanielnetoDotCom** [comment]
I do not understand, are you trying to search for channel names?

**Comment by JoshWho** [comment]
Can we randomize the channel order? I do not like the Z account always listed first

**Comment by JoshWho** [comment]
Or Even Better Just Display the Search Bar kinda like a google page

Do not show any channels until they search for something please

![downloa4245454564d](https://user-images.githubusercontent.com/39392449/116352090-44811d00-a7ba-11eb-9126-5d2d89aed938.png)

**Comment by JoshWho** [comment]
> I do not understand, are you trying to search for channel names?
> 
> BTW, the channel search is here https://demo.avideo.com/channels

Any way to include channel searches in the regular search?

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/116408770-9309d800-a809-11eb-9c8f-92fe806a4138.png)

**Comment by JoshWho** [comment]
Sweet. Thank you Daniel

**Comment by JoshWho** [comment]
Channel Z always shows no matter what the search is

![15cfe11c-ac30-4059-8fd4-1fd23231d4e2](https://user-images.githubusercontent.com/39392449/116488736-b90a9900-a858-11eb-8350-94d1a62de2e0.png)

**Comment by JoshWho** [comment]
I am not seeing the Chanel Blue still when I search "Blue" in the regular search. It does show up in the channel search but not the regular one.

**Comment by DanielnetoDotCom** [comment]
Hi, please first disable the CombineSites plugin, it is not working well.

I guess you are subscribed to this channel, that is why it always return it

also I just found this 

![image](https://user-images.githubusercontent.com/18009293/116580332-a55b4300-a8e9-11eb-8458-367da7ccaff2.png)

**Comment by JoshWho** [comment]
What does that do?

**Comment by DanielnetoDotCom** [comment]
try to switch (check/uncheck), clear the cache, and check if it changes the results.

**Comment by JoshWho** [comment]
I did that and the z channel goes away but "blue" still never shows. something seems to be keeping that word from being found in search.

**Comment by DanielnetoDotCom** [comment]
When I search on the channel page I can see the blue channel

![image](https://user-images.githubusercontent.com/18009293/116870852-a93cdd00-abe9-11eb-921f-3373ed810521.png)


I probably cannot see it on the main page because you do not have the "searchOnChannels" checked

![image](https://user-images.githubusercontent.com/18009293/116870955-dd180280-abe9-11eb-8872-700fc9da6e25.png)
