### ISSUE TITLE
Sitemap error

### ISSUE THREAD

**Issue by gujarraju** [WWBN/AVideo#5021]
Dear Mr. Daniel,
Please check below image I cant access my sitemap file.

![Untitled](https://user-images.githubusercontent.com/35865505/116240143-8e471480-a774-11eb-9ac9-0abf4d1cb446.jpg)

**Comment by DanielnetoDotCom** [comment]
Any way for you to check what do you have on between lines 8375 and 8385?

**Comment by gujarraju** [comment]
Please guide where I can check

**Comment by akhilleusuggo** [comment]
This is a commun error when there are not supported characters. Happens to me often. I ended up changing the video's titles.

Before you proceed , check "siteMapUTF8Fix" on CustomizeAdvanced.
