### ISSUE TITLE
YPTSocket with nginx proxy doesn't want to work

### ISSUE THREAD

**Issue by djslmft** [WWBN/AVideo#5023]
#4964 
Have the same issue, cant get working with ssl, could you please help me?

**Comment by milehighkaraoke** [comment]
Please attach your nginx config

**Comment by djslmft** [comment]
pid     /run/nginx.pid;
    worker_processes  1;
    error_log  logs/error.log debug;
    user www-data;
    #group apache;
        events {
            worker_connections  1024;
    }
    rtmp {
                server {
                listen [::]:1935 ipv6only=off;
                    chunk_size 4096;
                        buflen 2s;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                        application eventlive {
                            allow play all;
                            live on;
                            #drop_idle_publisher 10s;
                            #push_reconnect 3s;
                            #session_relay off;
                            #sync 100ms;
                            #record all;
                            #record_path /video_recordings;
                            #record_unique on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            #hls_playlist_length 4s;
                            #hls_fragment 4s;
                            #hls_sync 100ms;
                            hls_fragment 4s;
                            #play_restart on;
                            #idle_streams off;
                            #hls_base_url https://eventstream.hu/eventlive;
                            on_publish http://eventstream.hu/plugin/Live/on_publish.php;
                            on_publish_done http://eventstream.hu/plugin/Live/on_publish_done.php;
                            on_play http://eventstream.hu/plugin/Live/on_play.php;
                            on_record_done http://eventstream.hu/plugin/Live/on_record_done.php;
                                recorder video{
                                    record all;
                                    record_path /var/www/tmp;
                                    record_notify on;
                                    record_max_size 10240M; 
                            #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
                                    record_suffix -%d-%b-%y-%T.flv;
                                }
                        }
                }
        }
         http {
            include       mime.types;
            default_type  application/octet-stream;
                client_max_body_size 100G;
           server {
                listen 80 default_server; 
                listen [::]:80 default_server;
                listen 443 ssl default_server;
                 listen [::]:443 ssl default_server;
                    server_name eventstream.hu www.eventstream.hu;
                        ssl_certificate /etc/certs/eventstream_hu-ca-bundle.crt;
                        ssl_certificate_key /etc/certs/eventstream_hu.key;
                        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
                        ssl_ciphers HIGH:!aNULL:!MD5;

                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /eventlive {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                            }

                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    location /stats {
                            stub_status;
                    }
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                location / {
                                proxy_pass https://eventstream.hu:1443;
                                proxy_set_header Host $host;
                                proxy_set_header X-Real-IP $remote_addr;
                                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                                proxy_set_header X-Forwarded-Proto $scheme;
                                #proxy_redirect off;
                        }
                       #location ~ /\.ht {
                                #deny all;
                       #}
                }

**Comment by milehighkaraoke** [comment]
Try changing port on socket

**Comment by djslmft** [comment]
already did, without any success

**Comment by milehighkaraoke** [comment]
Check the logs there should be an error

**Comment by milehighkaraoke** [comment]
There was a problem with a commit yesterday  that caused the socket to disconnect  but the new commit has fixed it. If you have not done a gitpull tonight please do so on both encoder and site.

**Comment by djslmft** [comment]
updated, got these errors :(

test.php:
Notice: Undefined offset: 1 in /var/www/html/eventstream_hu/plugin/YPTSocket/test.php on line 76
Notice: Undefined offset: 3 in /var/www/html/eventstream_hu/plugin/YPTSocket/test.php on line 76
Notice: Undefined offset: 2 in /var/www/html/eventstream_hu/plugin/YPTSocket/test.php on line 76

avideo log:
AVideoLog::ERROR: Could not connect: Connection to www.mysite.com:2053 failed during TLS handshake: Connection lost during TLS handshake wss://www.mysite.com:2053?webSocketToken=ODFYdFhmTzJPSDVtcUpranFwMTFQK1VOWWVEMHEzUWNpbzFxQ1h3TXlLQkRWWEJMdUc1NzBWbVVvcWFyWHF6OUlYK2ppZHRpUjV1MmZ2bmlyenBmTEVoUVNEMjRDc0lldVBOZDUwb0lvMzA3NWk1MjZ2VkFocHdybFk2QTJSYnNxU21FTXd4d2hJTnQ4dUNCQVNOWjVySExuYzZMQ0JuRXZPNEFpNkdFVTNwMGVsdzJRK1NiWU0wU29tUmVpVVdjL0xqa2h4WldMVzNnb1pDakh1d2FSZXZobFhHZjBCNTZIYnMxa0RzZ0tmMDFZbzlrbXY1UEVoT0ZwcDJJbTVYdVVsWU1nd2liRFNPZGltUTJIOUdmK1BpVVo2M0Y3d1JpYUtveFFzc3lCUll0ckJ4dlQvY1U3QlF0UHdlWDRNbzZkSGlQVzlmRkRPZE9uSXBVd3pyeTE5SHFDdkZKeXlMMXpkSWZXc01FM2tDcWpiNmpvKzh4VWM5MVpQSU1SdXdlWWwzTnl3ZkUzK0QvcTd6TlZ6QlRTOVI0cHZZMW40OWFnc1BJSEphaVgwVTl1Zy9YK0x4ZkwzY0tIMHZrdXNUT0hLNXowbWFYQXlNdWVVekJEaGpkNDhRblovTzlyM28rWUViaEVJVjBwNUIxZUc5SFJQNDZSeXcrSVY1UWYwWnFDeElnWkU4Y1dCMDg3MlFPenZ0V0MyaEhXSVhWenFoSXJTS05JSU1LT2RJNjE1b2J4ZndUYXpJSTFJeW9aZVhxNnkrWUJrS3FmSzg4NFlDa0R6cnM2cjZrR0w0WWRFdS93MTlXSzU3cExpOGk3bElkQnUzSUUzMENXZWJGLzkvU0ZTSjZla1IxcVB3YWVPYjFxcCtlSENQdlpyWTNmSXVXVTRYeEJxNnhQNGM9&isCommandLine=1 SCRIPT_NAME: /objects/login.json.php

**Comment by DanielnetoDotCom** [comment]
Are you running it on Ubuntu?

**Comment by djslmft** [comment]
yupp
20.04

**Comment by DanielnetoDotCom** [comment]
Please get this update and run the test again and share the results here

**Comment by djslmft** [comment]
with ssl on:

root@eventstream:/var/www/html# php /var/www/html/eventstream_hu/plugin/YPTSocket/test.php
[2021-04-29 20:31:43] ** Starting socket test **
[2021-04-29 20:31:43] Testing connection with [0]: ws://localhost:2053 on 2021/04/29 20:31:43
[2021-04-29 20:31:43] Testing connection with [1]: wss://localhost:2053 on 2021/04/29 20:31:43
[2021-04-29 20:31:43] Testing connection with [2]: ws://127.0.0.1:2053 on 2021/04/29 20:31:43
[2021-04-29 20:31:43] Testing connection with [3]: wss://127.0.0.1:2053 on 2021/04/29 20:31:43
[2021-04-29 20:31:43] Testing connection with [4]: ws://eventstream.hu:2053 on 2021/04/29 20:31:43
[2021-04-29 20:31:43] Testing connection with [5]: wss://eventstream.hu:2053 on 2021/04/29 20:31:43
[2021-04-29 20:31:43]  NOT SECURE CONNECTION  CONNECTION FAIL ws://localhost:2053 Connection to tcp://localhost:2053 failed: Last error for IPv4: Connection to tcp://127.0.0.1:2053?hostname=localhost failed: Connection refused. Previous error for IPv6: Connection to tcp://[::1]:2053?hostname=localhost failed: Connection refused
[2021-04-29 20:31:43]  NOT SECURE CONNECTION  CONNECTION FAIL ws://127.0.0.1:2053 Connection to localhost:2053 failed: Last error for IPv4: Connection to tcp://127.0.0.1:2053?hostname=localhost failed: Connection refused. Previous error for IPv6: Connection to tcp://[::1]:2053?hostname=localhost failed: Connection refused
[2021-04-29 20:31:43]  NOT SECURE CONNECTION  CONNECTION FAIL ws://127.0.0.1:2053 Connection to tcp://127.0.0.1:2053 failed: Connection refused
[2021-04-29 20:31:43]  NOT SECURE CONNECTION  CONNECTION FAIL ws://127.0.0.1:2053 Connection to tcp://127.0.0.1:2053 failed: Connection refused
[2021-04-29 20:31:43]  NOT SECURE CONNECTION  CONNECTION FAIL ws://eventstream.hu:2053 Connection to tcp://eventstream.hu:2053 failed: Last error for IPv4: Connection to tcp://127.0.1.1:2053?hostname=eventstream.hu failed: Connection refused. Previous error for IPv6: DNS query for eventstream.hu (AAAA) did not return a valid answer (NOERROR / NODATA)
[2021-04-29 20:31:43]  NOT SECURE CONNECTION  CONNECTION FAIL ws://127.0.1.1:2053 Connection to eventstream.hu:2053 failed: Last error for IPv4: Connection to tcp://127.0.1.1:2053?hostname=eventstream.hu failed: Connection refused. Previous error for IPv6: DNS query for eventstream.hu (AAAA) did not return a valid answer (NOERROR / NODATA)
[2021-04-29 20:31:43]  We found 0 possible configurations:


without ssl:

root@eventstream:/var/www/html# php /var/www/html/eventstream_hu/plugin/YPTSocket/test.php
[2021-04-29 20:32:04] ** Starting socket test **
[2021-04-29 20:32:04] Testing connection with [0]: ws://localhost:2053 on 2021/04/29 20:32:04
[2021-04-29 20:32:04] Testing connection with [1]: ws://127.0.0.1:2053 on 2021/04/29 20:32:04
[2021-04-29 20:32:04] Testing connection with [2]: ws://eventstream.hu:2053 on 2021/04/29 20:32:04
[2021-04-29 20:32:04]  NOT SECURE CONNECTION  Good news, your localhost connects, that means your port [2053] is open ws://localhost:2053
[2021-04-29 20:32:04]  NOT SECURE CONNECTION  Good news, your localhost connects, that means your port [2053] is open ws://127.0.0.1:2053

Notice: Undefined property: stdClass::$test_msg in /var/www/html/eventstream_hu/plugin/YPTSocket/test.php on line 63

Notice: Undefined offset: 2 in /var/www/html/eventstream_hu/plugin/YPTSocket/test.php on line 64

Notice: Undefined offset: 1 in /var/www/html/eventstream_hu/plugin/YPTSocket/test.php on line 64
[2021-04-29 20:32:04]  NOT SECURE CONNECTION  CONNECTION SUCCESS ://:0
[2021-04-29 20:32:04]  We found 1 possible configurations:

               NOT SECURE CONNECTION
-------------------------------------------------------
*** Force not to use wss (non secure): Unchecked
*** Server Port: 0
*** Server host:
-------------------------------------------------------


[2021-04-29 20:32:04]  NOT SECURE CONNECTION  CONNECTION SUCCESS ws://eventstream.hu:2053


but it doesn't connect

**Comment by DanielnetoDotCom** [comment]
looks like you have a firewall or something else.

sorry I cannot support your Nginx configuration.

**Comment by djslmft** [comment]
there is no firewall, all ports are open, you can check it, everything else works fine
and they are on the same hardware (that's why i have to use reverse proxy - our clients cannot connect to unusual ports)
