### ISSUE TITLE
On latest commits, the stream keys are being displayed wrong 

### ISSUE THREAD

**Issue by matheusfillipe** [WWBN/AVideo#5024]
I have two configured and working rtmp servers. The second added one working fine but the first doesn't work with the stream key/name indicated on the `/Live/` page. It works if i remove the two last characters though.

I think it is because of multiple rtmp servers. The stream keys on both the "Stream key + Site Url" and "Stream name/key" have a termination like `-1` or `-2`. They are also repeated, both servers get -1 or -2 simultaneously so I am not sure what this is for since is not the rtmp server index or something.

The thing is, if I remove that termination it works for both server. My "server 2" works fine both with or without it. For now Im patching it so that is removed. What is that termination anyway?

**Comment by DanielnetoDotCom** [comment]
Hi, I have changed the way the keys are created. 

if the key is not online we will reuse the last key so the shared links will still be working.

also, feel free to change the -1 or -2 to anything (letters and numbers)

**Comment by matheusfillipe** [comment]
Well the bug was that , even after cleaning cache, the site was trying to use the keys without the -1, -2 termination on the live server, which returned 404, while the ones with that ending were the valid actual ones, but you can still stream without that termination and then it will work on the site. 

It also shows the status online but the video wont load because it will 404. Anyway, I am not able to reproduce right now again but maybe it is a caching problem?

**Comment by DanielnetoDotCom** [comment]
I am not sure about your issue, but are you sure you are not mixing the adaptive mode?
