### ISSUE TITLE
SendRecordedToEncoder

### ISSUE THREAD

**Issue by djslmft** [WWBN/AVideo#5025]
Just installed a fresh installation of the site, when i try to upload a video it works fine, when i use your encoder it gets the video, but when it try to use the installed encoder i get this error:

[28-Apr-2021 09:59:31 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function videosHashToID() in /var/www/html/eventstream_hu/encoder/objects/security.php:32
Stack trace:
#0 /var/www/html/eventstream_hu/encoder/objects/include_config.php(15): require_once()
#1 /var/www/html/eventstream_hu/encoder/videos/configuration.php(37): require_once('/var/www/html/e...')
#2 /var/www/html/eventstream_hu/encoder/view/queue.php(3): require_once('/var/www/html/e...')
#3 {main}
  thrown in /var/www/html/eventstream_hu/encoder/objects/security.php on line 32

**Comment by milehighkaraoke** [comment]
I believe it is the latest commits to the project that is causing this as I also have this same issue after doing the latest updates. I would wait a few hours and try a git pull on bothe stream and encoder. Dan is pretty good at fixing these issues

**Comment by DanielnetoDotCom** [comment]
Please update the encoder again, I sent an update 1 hour ago

**Comment by djslmft** [comment]
got it, working! thanxalot!
