### ISSUE TITLE
Live notifications

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#5027]
Can you add notifications for live broadcasts on the AV Video Android app please? It's absolutely essential in this age of censorship that people have access to live broadcasts via your software.

**Comment by DanielnetoDotCom** [comment]
if you have the sockets running you may receive the notification.

if you mean receive a notification with the phone on the blocked screen, I may need to review it with onesignal

**Comment by fakeologist** [comment]
Yes I mean on the smartphone.

**Comment by milehighkaraoke** [comment]
That function is already available on the mobile ap. 
![Screenshot_20210501-035850_AVideo Platform](https://user-images.githubusercontent.com/70327833/116778944-c8910a00-aa31-11eb-975f-4eae02a07f4a.jpg)
![Screenshot_20210501-035843_AVideo Platform](https://user-images.githubusercontent.com/70327833/116779024-cd55be00-aa31-11eb-9f72-b2f3b2f29c87.jpg)

**Comment by fakeologist** [comment]
Did it pop up as an android notification?

**Comment by milehighkaraoke** [comment]
Yes this is on Android  and it notifies with the live icon on bottom

**Comment by fakeologist** [comment]
Does it pop up on the phone like instagram?

**Comment by DanielnetoDotCom** [comment]
I am pretty sure if you setup the Onesignal it will 
https://github.com/WWBN/AVideo/wiki/Notifications-Plugin#onesignal
