### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5029]
There is an issue when translating to Hebrew and then switching to English language we still have couple of menu items which are not translated back to English and remain in Hebrew. This is an issue for our english users.

Also the Organize Playlist translation is somehow  buggy, it looks like there is a space there or you need to use two words idk.

How should we edit the language file properly to include our menus in the English translation file.

Notice the language is set in US.

![Screen Shot 5781-08-16 at 17 39 01](https://user-images.githubusercontent.com/58882903/116423327-434b0100-a849-11eb-9756-99a9a516af7e.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, all lang files are here https://github.com/WWBN/AVideo/tree/master/locale

you may find your file edit/add the variables.

after that feel free to make a pull request so we can keep your changes on the main branch.

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by DanielnetoDotCom** [comment]
I see what you mean now, and you are correct this is 2 words. one is the "Organize" translation and the other one is whatever you define how you want to call your playlist. (some people wants to call playlists other wants to call it programs, etc)

but I just sent an update the "playlist name" will also be translated

![image](https://user-images.githubusercontent.com/18009293/116694208-5ec32280-a995-11eb-99aa-ef9fe0025356.png)

https://github.com/WWBN/AVideo/blob/ebebf747cdd294714e6f90770d94e29f7b701a10/plugin/PlayLists/PlayLists.php#L302

**Comment by guymass** [comment]
Same should be done for all button such as Live Stream and Publish Live URL, also for Categories menu items.

**Comment by guymass** [comment]
OK figured it out, I need to create my menus in English first and than give them my own translation.

**Comment by guymass** [comment]
OK so didn't figure it out. I though that if I reset all button names to english I would be able later to create theHebrew translation for them, however the Live button doesn't get translated including all the menu items for the encoder menu.

Also any menu I create do I need to create in English and than create a translation for it?

I think currently there are few places where the translation doesn't take place like on the top menu for start and category names.

![Screen Shot 5781-08-23 at 16 23 49](https://user-images.githubusercontent.com/58882903/117172295-583d0c80-add4-11eb-95d4-027a7cf021f9.jpg)


Audios don't translate as well. 
I also noticed that some times the english translation must be specific for Capital words, but maybe im wrong, idk.
We need to understand how to better translate and make it a complete RTL.

**Comment by DanielnetoDotCom** [comment]
I guess you need to add the $['Audios'] = ...; on your translation file

**Comment by guymass** [comment]
I did it doesn't do anything and nither my menus or the Live button, publish live url, Upload menu etc..

![Screen Shot 5781-08-25 at 9 12 22](https://user-images.githubusercontent.com/58882903/117405563-8164b680-af14-11eb-8b90-70aa7f903fc7.jpg)

**Comment by guymass** [comment]
I cannot translate any of the TOP MENU buttons unless I explicitly change them to Hebrew on the plugin.

**Comment by DanielnetoDotCom** [comment]
The "Audios" is translated, may a cache is not changing it or maybe you have something wrong in your translation file.
https://github.com/WWBN/AVideo/blob/1e1ff44a0f7172251de462576c5c4a311cfffa6a/view/include/navbar.php#L1132

I am sending an update to the TopMenu that may let you translate it

**Comment by guymass** [comment]
Well I did the update but still translation doesn't work for Audios or audios or AUDIOS and string I try. I think there is that tab space which is effecting the translation as if it expects to get some space before and after the word.

Also still top menu translation doesn't word for LIVE/PUBLISH/UPLOAD menu items.
