### ISSUE TITLE
Missing HLS

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5030]
Can anyone tell me why I don't have this HLS functionality?
If it must be activated, tell me how to do it?
Thank you

![HLS](https://user-images.githubusercontent.com/82677269/116459957-bfa00d00-a866-11eb-8d0f-2e746d27b309.JPG)

**Comment by sharknetwork24** [comment]
This is what appears to me.
Thank you
![44](https://user-images.githubusercontent.com/82677269/116460148-00982180-a867-11eb-9e04-0ac004648763.JPG)

**Comment by DanielnetoDotCom** [comment]
You need the VideoHLS plugin

**Comment by sharknetwork24** [comment]
OK thanks Daniel
