### ISSUE TITLE
"Suggested" list randomizes its play order on page load. Paging through this has no meaning.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5031]
**Describe the bug**
Clicking on the next/previous page, or page selection buttons always produce a new random list of videos.

Seems like it's randomizing on page load, not on new session.

**Comment by walt93** [comment]
Any thoughts here?

**Comment by akhilleusuggo** [comment]
yes because the requests are not cached

**Comment by walt93** [comment]
It seems that a different implementation is in order. Believe this could be solved, for one example, by playing games with seeding the random number generator. Another way, a &page=N parameter work. That would be best because you could have a &suggestedPage=N, &categoryABCPage=N, etc. and would be great for the user.

This way of doing it is broken.
