### ISSUE TITLE
Install of AVideo no longer working on Ubuntu 18.04 or 20.04 with latest Chrome and Firefox browser

### ISSUE THREAD

**Issue by sipero** [WWBN/AVideo#5033]
I cannot installed AVideo as when I have everything setup and click the install button nothing happens

I have over the past couple of years setup AVideo at least 100 times. For some unknown reason the installation no longer works and I have tried it at least 6 times today for both Ubuntu 18.04 and 20.04

See this short 77 second video https://www.loom.com/share/d4f0b4f8fa9b462089569c45996c5ebb

**Comment by AnestisK** [comment]
I was just going to leave this exact same issue.
The following error messages appear in the console of the web server:

Unchecked runtime.lastError: The message port closed before a response was received.

(Apologies, for some reason I can't mark these as code blocks)

jquery-3.5.1.min.js:2 jQuery.Deferred exception: Cookies is not defined ReferenceError: Cookies is not defined
    at HTMLDocument.<anonymous> (http://media.diversityarrays.com/view/js/script.js:1125:5)
    at e (http://media.diversityarrays.com/view/js/jquery-3.5.1.min.js:2:30005)
    at t (http://media.diversityarrays.com/view/js/jquery-3.5.1.min.js:2:30307) undefined
S.Deferred.exceptionHook @ jquery-3.5.1.min.js:2
t @ jquery-3.5.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.5.1.min.js:2
c @ jquery-3.5.1.min.js:2
fireWith @ jquery-3.5.1.min.js:2
fire @ jquery-3.5.1.min.js:2
c @ jquery-3.5.1.min.js:2
fireWith @ jquery-3.5.1.min.js:2
ready @ jquery-3.5.1.min.js:2
B @ jquery-3.5.1.min.js:2

jquery-3.5.1.min.js:2 Uncaught ReferenceError: Cookies is not defined
    at HTMLDocument.<anonymous> (script.js:1125)
    at e (jquery-3.5.1.min.js:2)
    at t (jquery-3.5.1.min.js:2)
(anonymous)	@	script.js:1125
e	@	jquery-3.5.1.min.js:2
t	@	jquery-3.5.1.min.js:2
setTimeout (async)		
S.readyException	@	jquery-3.5.1.min.js:2
(anonymous)	@	jquery-3.5.1.min.js:2
e	@	jquery-3.5.1.min.js:2
t	@	jquery-3.5.1.min.js:2
setTimeout (async)		
(anonymous)	@	jquery-3.5.1.min.js:2
c	@	jquery-3.5.1.min.js:2
fireWith	@	jquery-3.5.1.min.js:2
fire	@	jquery-3.5.1.min.js:2
c	@	jquery-3.5.1.min.js:2
fireWith	@	jquery-3.5.1.min.js:2
t	@	jquery-3.5.1.min.js:2
setTimeout (async)		
(anonymous)	@	jquery-3.5.1.min.js:2
c	@	jquery-3.5.1.min.js:2
fireWith	@	jquery-3.5.1.min.js:2
fire	@	jquery-3.5.1.min.js:2
c	@	jquery-3.5.1.min.js:2
fireWith	@	jquery-3.5.1.min.js:2
ready	@	jquery-3.5.1.min.js:2
B	@	jquery-3.5.1.min.js:2

index.php:211 Uncaught TypeError: Cannot read property 'showPleaseWait' of undefined
    at HTMLFormElement.<anonymous> (index.php:211)
    at HTMLFormElement.dispatch (jquery-3.5.1.min.js:2)
    at HTMLFormElement.v.handle (jquery-3.5.1.min.js:2)
(anonymous) @ index.php:211
dispatch @ jquery-3.5.1.min.js:2
v.handle @ jquery-3.5.1.min.js:2

**Comment by RememberForgottenHits** [comment]
I just installedon ubuntu 20.04 the AVideo streaming website yesterday and had no problems. There are currently problems with encoder installation https://github.com/WWBN/AVideo-Encoder/issues/377

**Comment by sipero** [comment]
I switched my jquery to CDN version of 3.5.1 and latest 3.6.0 and seem to be seeing the same error in the console
jquery-3.6.0.js:4050 jQuery.Deferred exception: Cookies is not defined ReferenceError: Cookies is not defined
    at HTMLDocument.<anonymous> (https://us04.instantstream.club/view/js/script.js:1125:5)
    at mightThrow (https://code.jquery.com/jquery-3.6.0.js:3766:29)
    at process (https://code.jquery.com/jquery-3.6.0.js:3834:12) undefined
jQuery.Deferred.exceptionHook @ jquery-3.6.0.js:4050
jquery-3.6.0.js:4059 Uncaught ReferenceError: Cookies is not defined
    at HTMLDocument.<anonymous> (script.js:1125)
    at mightThrow (jquery-3.6.0.js:3766)
    at process (jquery-3.6.0.js:3834)
index.php:211 Uncaught TypeError: Cannot read property 'showPleaseWait' of undefined
    at HTMLFormElement.<anonymous> (index.php:211)
    at HTMLFormElement.dispatch (jquery-3.6.0.js:5430)
    at HTMLFormElement.elemData.handle (jquery-3.6.0.js:5234)

Thanks for the reminder to always check the console for errors

**Comment by sipero** [comment]
When I just use the installed version of jquery 3.5.1 this is what I see in the console on both Firefox and Chrome

**Comment by DanielnetoDotCom** [comment]
Hi, sorry about that, I just found the issue

**Comment by sipero** [comment]
I have just done 2 installs one for Ubuntu 18.04 and the other one 20.04 and both worked fine. Thank you.
