### ISSUE TITLE
Verification-Mail Subject malformed

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#5036]
The subject of the verification-mails sent arent formated well and i havent found the possibility to change the subject of them.

At the moment its like this: (german)
"Bitte bestätige deine E-Mail AdresseBit-Link Video"

But it should be like this:
"Bitte bestätige deine E-Mail Adresse bei Bit-Link Video"

Can i change it by myself or do i need your help Daniel?

**Comment by DanielnetoDotCom** [comment]
This should fix

**Comment by morbificagent** [comment]
Thanks Daniel
