### ISSUE TITLE
Can't stream - NGINX error

### ISSUE THREAD

**Issue by ccarlile1** [WWBN/AVideo#5041]
When trying to stream I get a cannot connect error. After looking at the status of nginx I get    nginx: [emerg] unknown directive "rtmp" in /etc/nginx/nginx.conf:8

**Comment by akhilleusuggo** [comment]
Maybe your config is wrong you haven't compiled rtmp-nginx correctly.

Can you copy/past your config here ?

**Comment by ccarlile1** [comment]
user    www-data;
worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    pid /run/nginx.pid;
    rtmp {
            server {
                    listen 1935;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream
from our incoming encoder stream and tells where to put the HLS video
manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            hls_fragment 2s;
                            on_publish
http://localhost/AVideo/plugin/Live/on_publish.php;
                            on_play
http://localhost/AVideo/plugin/Live/on_play.php;
                            on_record_done
http://localhost/AVideo/plugin/Live/on_record_done.php;

                            #exec ffmpeg -i rtmp://localhost/live/$name
                            #    -c:a aac -strict -2 -b:a 96k -c:v libx264
-vf scale=-2:240 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2
-b:v 400k -maxrate 700k -bufsize 1200k -b:a 96k -r 20 -f hls -hls_time 6
-hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_low
                            #    -c:a aac -strict -2 -b:a 128k -c:v libx264
-vf scale=-2:480 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2
-b:v 1200k -maxrate 2100k -bufsize 2400k -b:a 128k -f hls -hls_time 6
-hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_mid
                            #    -c:a aac -strict -2 -b:a 128k -c:v libx264
-vf scale=-2:720 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2
-b:v 2400k -maxrate 4200k -bufsize 100000k -b:a 128k -f hls -hls_time 6
-hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi;


                            #recorder video{
                            #    record all;
                            #    record_path /var/www/tmp;
                            #    record_notify on;
                            #    record_max_size 2048M;
                            #    record_suffix -%d-%b-%y-%T.flv;
                            #}
                    }

                    #application adaptive {
                    #    live on;
                    #    hls on;

                    #    hls_path /HLS/live;
                    #    hls_nested on;
                    #    hls_playlist_length 10m;
                    #    allow play all;
                    #    allow publish 127.0.0.1;
                    #    deny publish all;

                    #    hls_variant _low BANDWIDTH=400000;
                    #    hls_variant _mid BANDWIDTH=2100000;
                    #    hls_variant _hi  BANDWIDTH=4200000;
                    #}
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    #listen 8443 ssl;
                    #listen [::]:8443 ssl;
                    #include /usr/local/nginx/snippets/self-signed.conf;
                    #include /usr/local/nginx/snippets/ssl-params.conf;
                    listen 8081;
                    server_name localhost diggertv.sugarsalem.org;
                    #creates the http-location for our full-resolution
(desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            # Disable cache
                            add_header 'Cache-Control' 'no-cache';

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*'
always;
                            add_header 'Access-Control-Expose-Headers'
'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header
'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age'
1728000;
                                    add_header 'Content-Type' 'text/plain
charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx
site using a URL like: "http://my-ip/stats"
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our
videos: "http://my-ip/my-page.html"
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }

                    location ~ \.php$ {
                           include /etc/nginx/snippets/fastcgi-php.conf;
                           fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
                    }


    listen 8443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/
diggertv.sugarsalem.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/
diggertv.sugarsalem.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
    }

**Comment by DanielnetoDotCom** [comment]
For sure you do not have the rtmp module.

**Comment by ccarlile1** [comment]
Would this come from an update? We paid for the install and it was working
fine. Not sure when it stopped working but we did an update a little while
back.

**Comment by milehighkaraoke** [comment]
This should help you
https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server
