### ISSUE TITLE
Under Maintenance after Installation (WAS now Installation not working - "Unknown Error")

### ISSUE THREAD

**Issue by AnestisK** [WWBN/AVideo#5043]
After pulling the latest version down from Git (see Issue #5033), I ams till unable to install.

I get an "Unknown Error" pop up when I click the "Install Now" button.

OS: Debian Buster (10).
Latest version of Chrome and Firefox.

Browser Console Message:

`POST https://media.domain.com/install/checkConfiguration.php 500 (Internal Server Error)
send @ jquery-3.5.1.min.js:2
ajax @ jquery-3.5.1.min.js:2
(anonymous) @ index.php:224
dispatch @ jquery-3.5.1.min.js:2
v.handle @ jquery-3.5.1.min.js:2`

Apache error log:
 `[Fri Apr 30 09:01:08.521731 2021] [php7:notice] [pid 4587] [client 10.92.16.95:58048] Installation: 20, referer: https://media.domain.com/install/index.php
[Fri Apr 30 09:01:08.521785 2021] [php7:error] [pid 4587] [client 10.92.16.95:58048] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/YouPHPTube/install/checkConfiguration.php:22\nStack trace:\n#0 {main}\n  thrown in /var/www/YouPHPTube/install/checkConfiguration.php on line 22, referer: https://media.domain.com/install/index.php`

**ADDENDUM**
After install php-mysqli it looked like it was installing, but now I am getting "Please configure your webSiteRootPath".

I have SSL enabled and my Apache conf file is as follows:

```
<VirtualHost *:80>
    ServerName media.domain.com
    Redirect permanent / https://media.domain.com/
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>

<VirtualHost *:443>
     ServerAdmin media@domain.com
     DocumentRoot /var/www/YouPHPTube/
     ServerName media.domain.com
     ServerAlias www.media.domain.com

    <Directory /var/www/YouPHPTube>
       DirectoryIndex index.php
       Options +FollowSymLinks
       AllowOverride All
       Require all granted
    </Directory>

     ErrorLog ${APACHE_LOG_DIR}/media.error.log
     CustomLog ${APACHE_LOG_DIR}/media.access.log combined

     SSLCertificateFile /etc/ssl/certs/star_domain_com.pem
     SSLCertificateKeyFile /etc/ssl/private/star_domain_com.key
</VirtualHost>
```

**Comment by AnestisK** [comment]
After some reconfiguring and redownloading, am now getting:

```
[Fri Apr 30 10:54:26.891255 2021] [php7:warn] [pid 14710] [client 10.92.16.95:62076] PHP Warning:  require_once(/var/www/AVideo/view/img/../../videos/configuration.php): failed to open stream: No such file or directory in /var/www/AVideo/view/img/image404.php on line 3, referer: https://media.diversityarrays.com/info.php
[Fri Apr 30 10:54:26.891343 2021] [php7:error] [pid 14710] [client 10.92.16.95:62076] PHP Fatal error:  require_once(): Failed opening required '/var/www/AVideo/view/img/../../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/AVideo/view/img/image404.php on line 3, referer: https://media.diversityarrays.com/info.php

```

**Comment by AnestisK** [comment]
Never mind.  The issue was it was picking up the Install directory as part of the site URL.  Working now.

Can be closed.

**Comment by AnestisK** [comment]
And not fixed.  It says it installed but going to the main site gives an "Under Maintenance" page.

No error message in Apache error logs.

**Comment by DanielnetoDotCom** [comment]
check your apache and avideo errors log

**Comment by AnestisK** [comment]
I did.  No errors.

**Comment by AnestisK** [comment]
Apache (after log rotation).
```
[Sun May 02 00:00:02.026412 2021] [mpm_prefork:notice] [pid 18006] AH00163: Apache/2.4.38 (Debian) OpenSSL/1.1.1d configured -- resuming normal operations
[Sun May 02 00:00:02.026540 2021] [core:notice] [pid 18006] AH00094: Command line: '/usr/sbin/apache2'
```
Avideo log is blank. (after log rotation)

**Comment by AnestisK** [comment]
Also, not the only one having this issue - see https://github.com/WWBN/AVideo/issues/5048

**Comment by DanielnetoDotCom** [comment]
So lets keep tracking this issue on https://github.com/WWBN/AVideo/issues/5048
