### ISSUE TITLE
YPTStorage default storage doesnt work anymore

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#5044]
Actually the selection of the default storage at the YPTStorage plugind isnt working anymore.
Was looking at my Video-List and noticed that all the last videos are on the wrong storage...

Clicking on "move storage" is working. they are transfered and played from it after that well.
But even if my config sayes "Defaultstorage is videostorage.bit-link.de" all new files are on local after upload.

![grafik](https://user-images.githubusercontent.com/50199132/116673053-32160780-a9a3-11eb-8e69-6511728b2f90.png)

i dont have any exception per user too. Everyone is configured for useinusing "default storage"

**Comment by DanielnetoDotCom** [comment]
there are any error in your streamer log?

**Comment by morbificagent** [comment]
Couldnt find any... as it wouldnt even try it...

**Comment by DanielnetoDotCom** [comment]
I just tested on demo and seems to work.

can you please make sure you have the latest streamer/encoder/storage ?

also the plugins?
