### ISSUE TITLE
Disrupted Live stream not sending to encoder

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5045]
After latest Update if the live stream gets interrupted by loss of internet or OBS improperly getting shut down the stream is not sent to encoder.  
![20210429_163853](https://user-images.githubusercontent.com/70327833/116681927-d4fe5f80-a96a-11eb-84f5-2b05ed5da35a.jpg)

**Comment by DanielnetoDotCom** [comment]
I am not sure what would be the problem, but if this happens is because Nginx is not telling the streamer the live is done.

this is an Nginx/RTMP problem. maybe you should contact their project and open an issue.

**Comment by milehighkaraoke** [comment]
Will do.... thank you for your knowledge and appreciated input

**Comment by akhilleusuggo** [comment]
@milehighkaraoke If you take a look at the latest update that I've proposed , you can achieve it. 
https://github.com/WWBN/AVideo/pull/5040/

`ping_timeout 30s` and most importantly `drop_idle_publisher 30s`

Drop idle publisher should do the job. If no data stream is received during the next 30s, the module should consider the stream over. This will force the sent.
