### ISSUE TITLE
UNDER MAINTENANCE

### ISSUE THREAD

**Issue by Natanaelvieira2765** [WWBN/AVideo#5048]
![asasasa](https://user-images.githubusercontent.com/83473472/116745918-2beb4f80-a9d2-11eb-930f-f14c4afa5ef9.JPG)
**After I finished installing the youphptube, this maintenance message appeared! I contacted support and was informed that I should open a project here on github, can someone help me?**

**Comment by AnestisK** [comment]
Same issue I am having - see https://github.com/WWBN/AVideo/issues/5043 .
I've checked the Apache and Avideo logs. No errors.

**Comment by DanielnetoDotCom** [comment]
It is an error 500, it must be something on the log file. if there is nothing I cannot help you.

**Comment by akhilleusuggo** [comment]
@AnestisK 
I believe that you both are not following the default AVideo installation. 
You're using YouPHPTube.

I mean, it's confusing... You're using a mix between the 2. Your Apache2 host config does contain YouPHPTube

```
<VirtualHost *:443>
     ServerAdmin media@domain.com
     DocumentRoot /var/www/YouPHPTube/
     ServerName media.domain.com
     ServerAlias www.media.domain.com
..............
```

But your log files does contain AVideo ....
```

[Fri Apr 30 10:54:26.891255 2021] [php7:warn] [pid 14710] [client 10.92.16.95:62076] PHP Warning:  require_once(/var/www/AVideo/view/img/../../videos/configuration.php): failed to open stream: No such file or directory in /var/www/AVideo/view/img/image404.php on line 3, referer: https://media.domain.com/info.php
[Fri Apr 30 10:54:26.891343 2021] [php7:error] [pid 14710] [client 10.92.16.95:62076] PHP Fatal error:  require_once(): Failed opening required '/var/www/AVideo/view/img/../../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/AVideo/view/img/image404.php on line 3, referer: https://media.domain.com/info.php

```

Also you're using Debian, not Ubuntu, something worth mentioning. You should take a look here for debian installations ( old guide tho, I don't recommend it) !  https://github.com/WWBN/AVideo/wiki/Install-AVideo-Platform-in-Debian-9.3

**Comment by sam-cts** [comment]
I am having same issue, below is my `videos/avideo.log`
`[02-May-2021 04:24:46 Africa/Abidjan] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined function imagecreatefrompng() in \/var\/www\/AVideo\/objects\/functions.php:1690\nStack trace:\n#0 \/var\/www\/AVideo\/objects\/functions.php(2966): convertImage()\n#1 \/var\/www\/AVideo\/objects\/configuration.php(251): convertImageToOG()\n#2 \/var\/www\/AVideo\/objects\/functionogSite.php(17): Configuration::getOGImage()\n#3 \/var\/www\/AVideo\/objects\/functions.php(3006): include('\/var\/www\/AVideo...')\n#4 \/var\/www\/AVideo\/view\/include\/head.php(176): ogSite()\n#5 \/var\/www\/AVideo\/plugin\/Gallery\/view\/modeGallery.php(10): include('\/var\/www\/AVideo...')\n#6 \/var\/www\/AVideo\/view\/index.php(30): require('\/var\/www\/AVideo...')\n#7 {main}\n  thrown","file":"\/var\/www\/AVideo\/objects\/functions.php","line":1690} SCRIPT_NAME: /view/index.php`

I commented out the following lines in `objects/functions.php ln1708 - ln1709` and it works
`
        // } elseif ($imagetype == IMAGETYPE_PNG || preg_match('/png/i', $ext)) {
        //     $imageTmp = imagecreatefrompng($originalImage);
`

**Comment by AnestisK** [comment]
Actually, I went back, deleted the YouPHPTube files, and downloaded the Master git repo from the Avideo GitHub repo.

I already mentioned all this in my original issue which you closed and redirected me to here.

I also mentioned I was using Debian in the original issue I made which was closed.

I am getting the same error message in the avideo.log file as @sam-cts:

```
ww\/AVideo\/objects\/functions.php:1709\nStack trace:\n#0 \/var\/www\/AVideo\/objects\/functions.php(3039): convertImage('\/var\/www\/AVideo...', '\/var                                                                                                                                             \/www\/AVideo...', 100)\n#1 \/var\/www\/AVideo\/objects\/configuration.php(251): convertImageToOG('\/var\/www\/AVideo...', '\/var\/www\/AVideo...')\n#2                                                                                                                                              \/var\/www\/AVideo\/objects\/functionogSite.php(17): Configuration::getOGImage()\n#3 \/var\/www\/AVideo\/objects\/functions.php(3079): include('\/var\/w                                                                                                                                             ww\/AVideo...')\n#4 \/var\/www\/AVideo\/view\/include\/head.php(181): ogSite()\n#5 \/var\/www\/AVideo\/plugin\/Gallery\/view\/modeGallery.php(11): inclu                                                                                                                                             de('\/var\/www\/AVideo...')\n#6 \/var\/www\/AVideo\/view\/index.php(38): require('\/var\/www\/AVideo...')\n#7 {main}\n  thrown","file":"\/var\/www\/AVid                                                                                                                                             eo\/objects\/functions.php","line":1709} SCRIPT_NAME: /view/index.php
```
Like I said.  it installed successfully, told me to remove the install directory, which I did, and once I did and went to the main page the Under Maintenance Screen was showing.

As I said, I repeat, this was a git clone of the latest Master repo from here (Avideo) repo, not the YouPHPTube one.

And, again, Apache shows no errors.

Apache config file is fine:

```

<VirtualHost *:80>
    ServerName media.domain.com
    Redirect permanent / https://media.domain.com/
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>

<VirtualHost *:443>
     ServerAdmin media@domain.com
     DocumentRoot /var/www/AVideo
     ServerName media.domain.com
     ServerAlias www.media.domain.com

    <Directory /var/www/AVideo/>
       DirectoryIndex index.php
       Options +Indexes +FollowSymLinks
       AllowOverride All
       Require all granted
    </Directory>

     ErrorLog ${APACHE_LOG_DIR}/media.error.log
     CustomLog ${APACHE_LOG_DIR}/media.access.log combined

     SSLCertificateFile /etc/ssl/certs/star_domain_com.pem
     SSLCertificateKeyFile /etc/ssl/private/star_domain_com.key
</VirtualHost>
```

**Comment by akhilleusuggo** [comment]
@AnestisK I gave the guide believing that you're still using the YouPHPTube script installation from linuxbabe. Since it's an old installation, the guide would work.

**Comment by akhilleusuggo** [comment]
@AnestisK @sam-cts Ok , the issue may be related to the php-gd extension. 
`sudo apt-get install php-gd`

Can you confirm if it works ?

**Comment by AnestisK** [comment]
Ah-ha.  That was the issue.  php-gd was not installed because I rolled back to a snapshot where it hadn't been installed.

It seems to be working now.  At least I am getting the "We have not found any videos" page.

Someone needs to write an up-to-date step by step process for installing AVideo, starting from requirments and installation of required packages, etc etc.

**Comment by akhilleusuggo** [comment]
> Someone needs to write an up-to-date step by step process for installing AVideo, starting from requirements and installation of required packages, etc etc.

Done.

I'll write an updated installation step by step for Debian once I can.
@AnestisK Don't take it personal, I was just for confused by what I have read.

**Comment by akhilleusuggo** [comment]
Guide for Debian 10.x : https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Debian-10.x-for-AVideo-Platform-version-10.8-or-newer
