### ISSUE TITLE
Total video Count no longer displayed 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5053]
![Screenshot_20210501-061600_Samsung Internet](https://user-images.githubusercontent.com/70327833/116782238-2713b380-aa45-11eb-9a7b-d0c6d5cf7033.jpg)
![Screenshot_20210501-061707_Samsung Internet](https://user-images.githubusercontent.com/70327833/116782243-2d099480-aa45-11eb-8da4-558f2de60ae0.jpg)
![Screenshot_20210501-061742_Samsung Internet](https://user-images.githubusercontent.com/70327833/116782250-34c93900-aa45-11eb-8f97-539b26e1afdd.jpg)

**Comment by akhilleusuggo** [comment]
I'm not sure what you're looking for. 
If number of views ( I can see 17 views )
If you mean live_users watching the video you need setting from live_user plugin , and not from socket plugin.

![image](https://user-images.githubusercontent.com/52116577/116794528-30009580-aad6-11eb-9b6e-6789a755d4ac.png)

**Comment by milehighkaraoke** [comment]
Live user is displaying in pictures above but there is no total user in that picture.  That is what I am referring to

**Comment by DanielnetoDotCom** [comment]
@milehighkaraoke can you please screenshot your LiveUsers parameters?

**Comment by milehighkaraoke** [comment]
![Screenshot_20210503-060445_Samsung Internet](https://user-images.githubusercontent.com/70327833/116873804-830d4200-abd5-11eb-8edc-0b2b49f4dc28.jpg)

**Comment by DanielnetoDotCom** [comment]
I cannot see a reason to not show the total viewers. can you please share the link of one live video that is not showing the total?

FYY, this plugin does not support livelinks to show the total viewers

**Comment by milehighkaraoke** [comment]
It was random so I am thinking it was a cach issue on my phone and computer as it is fine now. Thank you....
