### ISSUE TITLE
Is there a way to install select versions. The latest version is not working with live stream. Version 5 works perfect

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5055]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akhilleusuggo** [comment]
Version 5? We're at +10 right now ( 10.7 )

By default you can't. You may wanna rollback on git, and rollback the database. **Make a backup before you proceed.**  https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform#rollback-the-update

Also I recommend that you to open a new issue, and post the logs of the errors/issues you're having.

**Comment by Lordblanca** [comment]
Ok can't get the 10.5 version back. is there a way to transfer my 10.5 from one server to my other server. Or maybe I should just give you a copy of the log and you can tell me what to do from there. everything works except my live streaming

**Comment by akhilleusuggo** [comment]
Past only the logs related to the live-stream.
When you start the live-stream , past the logs related. Remove/hide the sensitive data ( passwords etc , if any )

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/issues/5058
