### ISSUE TITLE
Total disaster

### ISSUE THREAD

**Issue by peterflitz** [WWBN/AVideo#5056]
After the last update, many videos can no longer be accessed ...

I'm not sure if it can work that way.
Where is the development going?

Examples (parts only):
AdALiveLink no longer works since 10.0 (notification as well as autostart and automatic termination).
More and more entries in the / Videos / folder mean that the video cannot be found.
Videos can no longer be played, all videos must be checked and, if no longer playable, uploaded again.
Please, how and who should check and re-upload 50000 videos ????

My suggestion:
A proper list of the versions and updates and a clear indication of whether an update is total junk or whether you can run an update during operation (stable)

I always use several test pages for all updates, but there is a very big difference whether a website with AVideo is very quiet or has operation / access.
Also as a beta tester, how is that supposed to work when so many errors have happened from v.10.0 to v.10.8 that you actually have to delete everything and start again?
It doesn't work that way and soon there will be no more beta testers ...

What a shame about the project!

I can get headwinds now, no problem, I'll say how it is.

I saw something in one of the last updates:
reencodeall-php, or similar.
Very nice that I saw it, only the documentation is missing, did this file come to fix this problem (many videos can no longer be played), or was it simply built in to destroy videos?

This project can work if the documentation and the classification of the updates (beta or stable) are communicated correctly.

All other ways lead to the fact that nobody can really use this project anymore.

An example:
I have an almost working 10.5 version with a lot of videos in operation, the categories and the AdALivelink are broken, as well as other small errors.
The way I see it, there will now be very big problems with an update, which means that it can no longer be updated. Rollback does not work, I already asked for it here, it was closed without an answer, great ...

Strategy must definitely be changed !!!!!

**Comment by DanielnetoDotCom** [comment]
First, check why are your videos not playing.
check your logs. without details about your issue, I cannot help you

**Comment by peterflitz** [comment]
Daniel, the problem is that no one comes after.
Before a version is stable, there are 10 new updates and 2 new versions.
Look, how long have the user rights of Meet been totally wrong, a user without rights to use Meet can still see the list of all the meetings, etc.

Error videos, I have a lot of them on the test page, but before that the videos were playable:
[01-May-2021 23:56:09 Europe / Amsterdam] AVideoLog :: DEBUG: Video :: getSourceFile (_YPTuniqid_607de2e2d23bc9.98908389_426, .mp4,) ERROR video not found (_YPTuniqid_607de2e2d23bc9.98908389 / .pTuniqid_607de2e2d23bc9.98908389 /

53 Erros within 10 minutes, on various test pages, including the live problem that has existed since the 10.4 version:
function: _error_log_debug Line: {691} File: {path / to / my / streamer / site / plugin / Live / Live.php}
I had raised the problem many weeks ago.

I propose to make a stable version and only then continue with the beta version, where the users can see right away that it is not a stable version, this is extremely important.

Then when I do an update on my big website, it costs me thousands of dollars to you.
I have no problem giving you small mistakes as work, but a large construction site is beyond the scope of the finances ...

**Comment by peterflitz** [comment]
Encoding also not working, please check your own Logfile from now:
-> encoder1.avideo.com

**Comment by peterflitz** [comment]
The Adserver / Campaigns is starting automatic, without autoplay.

Encoder not working, only direct-upload is possible (not with all files).

**Comment by peterflitz** [comment]
A few minutes later and after deleting the first page cache and cache, the video can no longer be used by registered users, the video does not play, log file says, no video is available, but the video is running as a guest.

Adserver / campaigns do not run on directly uploaded videos

**Comment by peterflitz** [comment]
Meet:
I already mentioned above, it seems to be the problem, which was previously also with AdALiveLink, because of the user rights.
A registered member who has no rights to use Meet can still look at the Meet list, see ALL meetings, etc. ...

This is also the case with users who are allowed to use Meet, EVERYONE sees all meetings, etc.

**Comment by peterflitz** [comment]
AdALiveLink (notification):
Some problems have been fixed, makeshift?

If I create a Livelink that is sent at a later time, the live appears immediately and you can see that the live will only start in x hours / minutes.
OK Good.
But when the live then starts, the first error is, the timer runs into positive and continues to show any minutes / hours. It would be correct if it says: -> LIVE
But the live doesn't start, you have to click on it, that's, well, ok.

If the live has ended, it will continue to run until the cache is cleared and the page is updated. Updating the page without clearing the cache beforehand is of no use, the live continues to be displayed.

**Comment by DanielnetoDotCom** [comment]
For me looks like you did not update it correctly.

first, try to reproduce it on the demo site.

if the error persists on the demo site open a new issue for each error.

if works the problem may be on your side

**Comment by milehighkaraoke** [comment]
Did you git pull from your encoder and your site?
