### ISSUE TITLE
Meet permission

### ISSUE THREAD

**Issue by peterflitz** [WWBN/AVideo#5057]
https://github.com/WWBN/AVideo/issues/5056#issuecomment-830709706

Every user can use the Meet administration:
What meetings were held.
Can copy the invitation including the password.

This can also be done by users who are not authorized to open a meeting, even without email confirmation.

![meet-test1](https://user-images.githubusercontent.com/76056428/116798721-e70b0a00-aaf2-11eb-96b0-ec59ebcd5e01.png)
![meet-admin](https://user-images.githubusercontent.com/76056428/116798723-e7a3a080-aaf2-11eb-9cf2-b9fc7e3d014d.png)
![meet-test](https://user-images.githubusercontent.com/76056428/116798724-e83c3700-aaf2-11eb-80d6-dba4bdbfdf8c.png)

**Comment by DanielnetoDotCom** [comment]
Hi, you are right.

now the users still can copy the meet link but the password only Admins and meet owners can copy them
