### ISSUE TITLE
Restream doesn't work - Error in logs

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5059]
Although I setup few restream urls it seems I can only get my restream to our second AVideo site. None of the other resream urls work and I see this in logs indicating there are no restream urls:

![Screen Shot 5781-08-20 at 20 44 27](https://user-images.githubusercontent.com/58882903/116822440-719d4900-ab87-11eb-83b0-061f5ac48584.jpg)
![Screen Shot 5781-08-20 at 20 48 29](https://user-images.githubusercontent.com/58882903/116822501-c771f100-ab87-11eb-91d2-b470036cdf16.jpg)

I have two restreams for test however some of my users have 7 even, but currently resream doesn't work.

**Comment by guymass** [comment]
Could there be an effect on the user streaming if he enters the site through the ldap login and not the main login, assuming it is the same user name and the same password? Would that by any chance effect the way that user stream key is used or created? or maybe other more inner workings of the system idk.

Some restream configs like for FB it doesn't restream. Maybe the "disable restream" is inverted? or doesn't effect the selection.

**Comment by guymass** [comment]
Well I tried from both logins and it seems the stream key and URL are the same on both. Stream works fine, restreaming from one AVideo site to another also works. FB urls for restreams don't work for me. Haven't tested yet YT.

**Comment by DanielnetoDotCom** [comment]
To use FB restream you need to recompile your FFMPEG

https://github.com/WWBN/AVideo/wiki/Restream#restream-to-rtmps

**Comment by guymass** [comment]
OK thanks I will try that.

We have testing to YT so i guess it is what you recommend we should do, I will keep updating how it goes.

**Comment by jengajenga** [comment]
> OK thanks I will try that.
> 
> We have testing to YT so i guess it is what you recommend we should do, I will keep updating how it goes.
> 
> How difficult would this process be assuming my ffmpeg is already compiled? is it just recompile and that's it?

try going to the ffmpeg folder and type "sudo unmake"
then delete the folder
then recompile using the instructions

**Comment by guymass** [comment]
OK thank you I have compiled the ffmpeg as the instruction showed, I can currently restream to FB again thank you.
