### ISSUE TITLE
Get New Video Image

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5060]
I have some videos not creating their GIF/JPEG images and animations.

![Screen Shot 5781-08-20 at 22 29 58](https://user-images.githubusercontent.com/58882903/116825137-977e1a00-ab96-11eb-9e10-bc2cfb23dacd.jpg)

Trying to click the Get JPEG/GIF button give the following error:

2-May-2021 22:36:13 Asia/Jerusalem] AVideoLog::ERROR: setTimeZone: DateTimeZone::__construct(): Unknown or bad timezone (undefined) SCRIPT_NAME: /objects/videoAddViewCount.json.php
[02-May-2021 22:36:14 Asia/Jerusalem] AVideoLog::DEBUG: wget: ERROR the url download but is empty https://rtmp.flatearth.co.il/getImageMP4/aHR0cHM6Ly9saXZlLmFoYXZhNTI4LmNvbS92aWRlb3MvXzYwOGVmNWRkNDFkZjAzLjMxOTM5ODY2Lm1wNA==/gif/536, /var/www/html/AVideo/videos/cache/YPTurl_get_contents/f7f3415f2e6ae81bda762bb0e3ae6a09 SCRIPT_NAME: /plugin/MP4ThumbsAndGif/get.php
[02-May-2021 22:36:14 Asia/Jerusalem] AVideoLog::DEBUG: MP4ThumbsAndGif: (_608ef5dd41df03.31939866), webp SCRIPT_NAME: /plugin/MP4Thum

I see a lot of this as well:
DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1157 takes 0.3117 seconds to complete, Limit (0.2). /var/www/html/AVideo/view/index.php SCRIPT_NAME: /view/index.php

I don't know why it is not returning those files and for now I have disabled our remote live test server so we are using the local RTMP server for now. Could this be because of a previous encoding done on the remote server?

And if that server is now down, how would I recreate those images again? does it need to be done from the encoder it was originally encoded with?

**Comment by DanielnetoDotCom** [comment]
I just sent a fix for the DateTimeZone issue, but I do not think this is related to the image issue.

are you using an encoder for those videos with image problems?

get more logs around this ` [02-May-2021 22:36:14 Asia/Jerusalem] AVideoLog::DEBUG: MP4ThumbsAndGif:`

**Comment by guymass** [comment]
yes I was, but we took it down, so I guess it remembers from which encoder and tries to use the same encoder. I recommend to separate that function to allow to recreate those thumbnails from any available encoder. Mean while I uploaded images to replace the thumbnails as I couldn't recreate them once that encoder was down.

**Comment by guymass** [comment]
Closing this issue as this is more of a design issue and hopefully in the future AVideo will allow to generate thumbnails from ay encoder.
