### ISSUE TITLE
Imagens em tamanho diferente

### ISSUE THREAD

**Issue by Natanaelvieira2765** [WWBN/AVideo#5062]
Gostaria de deixar minha plataforma igual a netflix com as imagens largas, porem estão quadradas ! Na demonstração no site oficial do Avideo estão igual a netflix ! 
![tranding](https://user-images.githubusercontent.com/83473472/116882793-3b99ac80-abfb-11eb-9737-33a6ec00fa62.JPG)

como deixo assim?

**Comment by Natanaelvieira2765** [comment]
Na minha plataforma as imagens estão quadradas assim!

![foto](https://user-images.githubusercontent.com/83473472/116882927-608e1f80-abfb-11eb-8fc5-031a3a3d0c69.JPG)

**Comment by DanielnetoDotCom** [comment]
Desmarque isso

![image](https://user-images.githubusercontent.com/18009293/116885188-fcb92600-abfd-11eb-9f78-f77890cbc518.png)

**Comment by Natanaelvieira2765** [comment]
Não encontrei essa opção para desmarcar, em  qual seção fica?

**Comment by DanielnetoDotCom** [comment]
setá circulada
