### ISSUE TITLE
Strange readings of the statistics panel

### ISSUE THREAD

**Issue by SergejGrin** [WWBN/AVideo#5063]
I have a question about the statistics panel.
Before the program was updated, the statistics panel (screen # 1 as of 03/22/2020) had 14269 minutes of video and 179,482 views. During the year, the videos was watched a little more - there were about 860,000 views.

![tube-22 03 2020](https://user-images.githubusercontent.com/59236880/116885004-af51ae80-ac27-11eb-9179-417cb71576af.png) 
Recently I upgraded to the latest version (now it costs 10.5) Now the statistics panel shows - 6139 minutes of video and 29 642 views. (screen # 2 as of 03/22/2021).  But on the home page, some videos have more than 80,000 views, which is clearly more than 29,642. 
<img width="2155" alt="tube-22-03-2021" src="https://user-images.githubusercontent.com/59236880/116885074-c2fd1500-ac27-11eb-8d24-68b39cedb828.png">
<img width="730" alt="Снимок экрана 2021-05-03 в 15 55 52" src="https://user-images.githubusercontent.com/59236880/116885398-22f3bb80-ac28-11eb-8b68-fe560e6333a3.png">
<img width="2169" alt="Снимок экрана 2021-05-03 в 15 42 47" src="https://user-images.githubusercontent.com/59236880/116885514-40288a00-ac28-11eb-8072-a36b3c246246.png">
Actually, the question is: what numbers can you trust? Is this a stats panel issue or something else? How can this be corrected?

**Comment by DanielnetoDotCom** [comment]
this panel will be replaced, and I cannot count fake views on it.
fake views are not part of the statistics.

O am calling fake views when you edit the total views on the videos manager.

**Comment by SergejGrin** [comment]
Thanks for the quick response Daniel!
We will wait for the statistics panel to update. Fayk views are certainly not needed.
Also, pay attention to the video minutes counter - for some reason it also does not work correctly. There are 115 videos on my site now and their total duration is about 13,000 minutes. But the panel only shows half ...
