### ISSUE TITLE
REPETINDO TITULOS

### ISSUE THREAD

**Issue by Natanaelvieira2765** [WWBN/AVideo#5064]
Conforme eu adiciono os vídeos ele fica repetindo os vídeos em varias categorias, como controlar qual vídeo deve aparecer?
![aaaa](https://user-images.githubusercontent.com/83473472/116891758-7a346480-ac05-11eb-930f-26a5a89ec01b.JPG)

Gostaria de ajustar para não aparecer varias vezes o mesmo vídeo !

**Comment by DanielnetoDotCom** [comment]
remova algumas linhas.

a medida que voce for adicionando novos videos isso nao vai mais se repetindo

![image](https://user-images.githubusercontent.com/18009293/116892360-24ac8780-ac06-11eb-982a-db8e830dcabe.png)
