### ISSUE TITLE
Run 2 fully automatic commands every hour.

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5065]
I would like some help how to run these two commands fully automatically every hour.
It is used to activate the server for live shows.
The commands are these:
/ usr / local / nginx / sbin / nginx

sudo nohup php var / www / html / AVideo / plugin / YPTSocket / server.php

Whenever I always often find the server offline.
I ask Daniel for help in making this procedure automatic.
Maybe it would be possible to do this with the Crontab command which I don't know how to use.
I await a reply.

**Comment by milehighkaraoke** [comment]
You have to put your @boot commands in your root crontab

**Comment by sharknetwork24** [comment]
Can you explain to me how to do it?
Thank you

**Comment by milehighkaraoke** [comment]
Locate your socket plugin and click on help. Your crontab directions are listed there

**Comment by sharknetwork24** [comment]
Can you help me set up this procedure kindly?
I would be very grateful.
On the YPTSocket plugin I found the crontab.php file but I need your help on how to set it up with the correct parameters.
I attach the file in question.


<?php
require_once dirname(__FILE__) . '/../../videos/configuration.php';

if(!isCommandLineInterface()){
    //die("Command line only");
}

**Comment by milehighkaraoke** [comment]
Mine looks like this. You need to put your path in there instead of mine.  Your path is located on your yptsocket plu
![20210504_062350](https://user-images.githubusercontent.com/70327833/117003053-97b70c00-aca1-11eb-82ff-40b35ca1a286.jpg)
gin help

**Comment by sharknetwork24** [comment]
My file is this:

![crontab](https://user-images.githubusercontent.com/82677269/117007830-5dbe2800-acea-11eb-96bd-25fe6be3b101.PNG)

Can you tell me which file should I use inside my YPTSocket?

![YPTSocket](https://user-images.githubusercontent.com/82677269/117008399-f6ed3e80-acea-11eb-8590-d33a06307157.PNG)

**Comment by sharknetwork24** [comment]
I can't find the file like your image.

**Comment by milehighkaraoke** [comment]
Terminal   is how you access it

**Comment by sharknetwork24** [comment]
Can you kindly tell me step by step what to do?
What should I write on the terminal?
In which file should I open?
Please help me.
Thank you

**Comment by milehighkaraoke** [comment]
![Screenshot_20210504-084228_Samsung Internet](https://user-images.githubusercontent.com/70327833/117021734-d73b2380-acb4-11eb-95c5-a2b949787a52.jpg)

**Comment by milehighkaraoke** [comment]
![20210504_062350](https://user-images.githubusercontent.com/70327833/117021881-fafe6980-acb4-11eb-9d1f-9872ab93233c.jpg)

**Comment by milehighkaraoke** [comment]
Add both lines at the bottom of the crontab and save it. Make sure it's your path and not mine

**Comment by akhilleusuggo** [comment]
`sudo crontab -e`  ; Add this 2 lines.

```
@reboot sleep 60;nohup php /var/www/html/projects/itube/plugin/YPTSocket/server.php &
@reboot /usr/local/nginx/sbin/nginx
```

**Comment by sharknetwork24** [comment]
I hope I have done everything correctly.
What do you think?
Thank you so much

![aaa](https://user-images.githubusercontent.com/82677269/117025515-4176b700-acfb-11eb-93c8-2ca100f65721.PNG)

**Comment by sharknetwork24** [comment]
![aaa](https://user-images.githubusercontent.com/82677269/117025753-78e56380-acfb-11eb-9ae0-7886786852ad.PNG)
 
Bug fixed

**Comment by milehighkaraoke** [comment]
Please close if it 100 resolved. Thank you
