### ISSUE TITLE
Is there a way to root crontab the git pulls on site and encoder

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5066]
Looking to automate the git pulls, any suggestions and or solutions would be greatly appreciated.

**Comment by akhilleusuggo** [comment]
Not reocmmended , but if you want it ; would be like this ( git pull every 1h , when timer is xx:00 )

`sudo crontab -e`

```
0 * * * * cd /var/www/html/AVideo && sudo git pull
0 * * * * cd /var/www/html/AVideo-Encoder && sudo git pull
```

**Comment by milehighkaraoke** [comment]
Awesome  thank you. I have a test box that I am gonna use as a daily pre check for update issues.  When that box is running properly I know it's safe to do a pull on my production site....... thanks again
