### ISSUE TITLE
Meet expiring after 30 minutes

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5067]
I would like to know why when you do a MEET, after 30 minutes it closes automatically.
I have to make a new one which always lasts 30 minutes.
What I want to know, is it possible to increase the duration?
Thank you

![rrrr](https://user-images.githubusercontent.com/82677269/117044809-244be380-ad0f-11eb-9750-b9b41d45e45e.PNG)

![kkk](https://user-images.githubusercontent.com/82677269/117044866-2e6de200-ad0f-11eb-9fad-c8b339160107.PNG)

**Comment by DanielnetoDotCom** [comment]
Hi, 

the meet time is unlimited but to livestream it there is a 30 min limit. 

to increase that you need to have your own live meet server. It only works with our customized live server and you have to pay a monthly fee for that.

- 100 USD if you provide the dedicated server for the meet server
- 120 USD I will provide the dedicated server 

in both cases above the only limit is the hardware for simultaneous lives but there is no time limit anymore.
