### ISSUE TITLE
API to Get Videos has stopped working.  We get the string for the video but upon opening it, the video does not play

### ISSUE THREAD

**Issue by tbryantAE** [WWBN/AVideo#5069]
API GetVideos gives us a list of videos by that user and the URL of those videos.  When we pass the URL string over to the player, the video does not play.  The same video will play online.  Have checked AWS_S3 bucket plugin and it appears to be working fine.  We are running on the latest v10.8 and we have updated all plugins.

**Comment by DanielnetoDotCom** [comment]
Can you please provide a sample of the API you are using?

**Comment by ljmatan** [comment]
When accessing an mp4 URL [from video.ivrata.com](https://video.ivrata.com/plugin/API/get.json.php?APIName=video) videos play fine. Example URL:  https://video.ivrata.com/videos/_YPTuniqid_5fdbd6d805d649.93800101_Low.mp4?token=eyJzYWx0IjoiaHR0cHM6XC9cL3ZpZGVvLml2cmF0YS5jb21cLyIsInRva2VuVGltZU91dCI6MjE2MDAsImZpbGVuYW1lIjoiX1lQVHVuaXFpZF81ZmRiZDZkODA1ZDY0OS45MzgwMDEwMSIsInRpbWUiOjE2MjAzMzAyNDB9 

When accessing a URL from [dev.ivrata.com](https://dev.ivrata.com/plugin/API/get.json.php?APIName=video) videos do not work.

**Comment by DanielnetoDotCom** [comment]
Hi, so this is not the API, this is the URL itself

I can see you have a toke on the URL, did you try to disable the securevideosdirectory plugin?

FYI the dev.ivrata.com will have a different token then video.ivrata.com

**Comment by ljmatan** [comment]
Can you click on "from video.ivrata.com" or on "from dev.ivrata.com"? That's the API endpoint. 

BTW I agree I also think it's authentication problem, but I'm not a developer.

**Comment by ljmatan** [comment]
APIName=video

**Comment by DanielnetoDotCom** [comment]
> APIName=video

I need to see the query sample that you are using, so I can check

**Comment by ljmatan** [comment]
Please click links from here https://github.com/WWBN/AVideo/issues/5069#issuecomment-833811520

**Comment by DanielnetoDotCom** [comment]
> Please click links from here [#5069 (comment)](https://github.com/WWBN/AVideo/issues/5069#issuecomment-833811520)

again the link on the comment has nothing to do with the API

please read my answer

**Comment by ljmatan** [comment]
There are 3 links in the comments. 

1. is an API call from video.ivrata.com where you can get videos response. 
2. is the example of a response you should be looking for
3. is an API call from dev.ivrata.com where you can also get videos response

What more do you want? 

Videos from video.ivrata.com are working and the ones from dev.ivrata.com are not.

**Comment by ljmatan** [comment]
Again: 1, 2, and 3. 

![Screenshot_2021-05-07_20-18-15](https://user-images.githubusercontent.com/73232684/117492221-97549480-af71-11eb-9b9b-0b1f8d89f2b6.png)

**Comment by matheusfillipe** [comment]
@DanielnetoDotCom 
Seems to be a real issue. I am also not able to search videos or get any reply from the api on these links:
`https://live.ahava528.com/plugin/API/get.json.php?APIName=video&catName=default&rowCount=10`
`https://live.ahava528.com/plugin/API/get.json.php?APISecret=xxxxxx&APIName=video&catName=default&rowCount=10&searchPhrase=ני&channelName=RaisingTheFrequency`

Where I replaces the APISecret to put it here for obvious reasons. The responses are empty.
Other api's are working though. The rows are always empty on this one.
```json
{
    "error": false,
    "message": "",
    "response": {
        "rowCount": 10,
        "searchPhrase": "ני",
        "totalRows": 0,
        "rows": []
    }
}
```

Or is something missing there? I see nothing logged as error or anything during the request.

**Comment by DanielnetoDotCom** [comment]
> https://live.ahava528.com/plugin/API/get.json.php?APIName=video&catName=default&rowCount=10

In your case you need to add a valid catname

https://live.ahava528.com/plugin/API/get.json.php?APIName=video&catName=agenda-21&rowCount=10

**Comment by DanielnetoDotCom** [comment]
Hi, I do not understand the issue

there is no video on the dev site

what answer are you expecting?

![image](https://user-images.githubusercontent.com/18009293/117657561-157e8a00-b170-11eb-8737-c2773b142ff3.png)

**Comment by DanielnetoDotCom** [comment]
I still do not understand
