### ISSUE TITLE
Speedup my slow site

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5070]
Our site is getting very slow at times where it will take the home page to load up to 25sec. I did a speed test online an here are the results. My question is, how can we speed things up? We have a very strong server that this slowness shouldn't occur at all.

Also we currently have no more than couple of hundreds of people online at any given time.

I did notice that Google bot is constantly checking our site and maybe there are also other issues I am not aware of. Would you please give us some guidelines to follow to make sure the site is secure and works as it should.

Our domain is live.ahava528.com

![Screen Shot 5781-08-23 at 13 01 29](https://user-images.githubusercontent.com/58882903/117126117-016b0f00-ada3-11eb-81d4-9ba5afe65820.jpg)
![Screen Shot 5781-08-23 at 13 01 50](https://user-images.githubusercontent.com/58882903/117126126-03cd6900-ada3-11eb-9b10-6f38d681c175.jpg)
![Screen Shot 5781-08-23 at 13 02 09](https://user-images.githubusercontent.com/58882903/117126132-0465ff80-ada3-11eb-8fd8-b0a126884b4b.jpg)
![Screen Shot 5781-08-23 at 13 02 18](https://user-images.githubusercontent.com/58882903/117126135-04fe9600-ada3-11eb-8202-555e252485d8.jpg)
![Screen Shot 5781-08-23 at 13 02 23](https://user-images.githubusercontent.com/58882903/117126141-05972c80-ada3-11eb-8f5c-ce1bdcc434c5.jpg)

**Comment by milehighkaraoke** [comment]
Do you have Cache enabled? If so, try a purge of your site cache. Also that internet speed is not very fast if you users on at the same time

**Comment by morbificagent** [comment]
Where is the Server and where are the viewers with the slow speed? Same Country? As i see the site-sped-test was made from Frankfurt here in germany?

**Comment by morbificagent** [comment]
![grafik](https://user-images.githubusercontent.com/50199132/117138729-b6a1c500-adab-11eb-8b50-8d76294515f7.png)

Have tested it from germany too and the shown image loads in about 8sec...

**Comment by guymass** [comment]
Thank you very much for the test, wow this is a large image I haven't notices.

**Comment by peterflitz** [comment]
What does the server load say?

**Comment by guymass** [comment]
Well server seems fine, however I found that removing the Categories from Home Page will load much faster now.

![Screen Shot 5781-08-23 at 21 07 30](https://user-images.githubusercontent.com/58882903/117188756-15843000-ade6-11eb-85a8-5f228776a6c9.jpg)
![Screen Shot 5781-08-23 at 21 09 06](https://user-images.githubusercontent.com/58882903/117188840-2b91f080-ade6-11eb-8bef-b7f4fcc3da9c.jpg)

**Comment by akhilleusuggo** [comment]
Actually I'm not sure if the "Total Different Devices" works as expected. Because 128 users with only 12 different devices ?

In my case I see the same stuff. Multiple users , few devices.

**Comment by akhilleusuggo** [comment]
About server load, database optimization is required yeh. Without it, it's useless to have 32 cores if they're running at ~2ghz ~2.5.

MySQL and Apache are not multi-threaded . Don't understand me wrong, they will not use more then 1 core for the same query/request/user . If multiple requests then yes more cores gonna be used. But each request is limited to 1 core. 

High CPU close speed is the way to go right now.

**Comment by guymass** [comment]
Thank you for the information, well if its something that I need to do on my server I would be interested in learning what should I do. Other than that I guess it is up to AVideo to probably implement those optimizations.

**Comment by akhilleusuggo** [comment]
Sadly yes, and the project is heavy, serving many images/gifs/webp/videos in every page loaded.
As you can see on your htop screenshot , one core is used at 100% , while others are at 1-5%...

@guymass Also I would recommend you to disable swap. Use Zram or something instead. You have 120Gb ram, swap may only slow down more your system. Tweak MySQL , provide more ram to innoDB buffer pool, query_cache , memcached and other settings buffer-related.
Create a Ram disk for your AVideo/cache directory , this will store cache on ram instead of disk, speed up a lot the page loads and recursiveness. Same can apply to log files.

Play around a bit , you have enough resources to boost performance drastically.

**Comment by peterflitz** [comment]
What bandwidth does the server have and how many views per hour (under load)?

**Comment by guymass** [comment]
Thank you for all the suggestions I will for sure do those. I have 10Gbps LAN with two IPs.

**Comment by guymass** [comment]
Well seems that site is now running much better with recent updates and some tweeks we made to the home page. This can be closed.
