### ISSUE TITLE
How to add custom scripts in footer of all pages?

### ISSUE THREAD

**Issue by kardoqadir** [WWBN/AVideo#5071]
**Custom scripts in the footer of all pages**
I have some javascript scripts and I want to put them on all pages.  How is it possible?

**Comment by DanielnetoDotCom** [comment]
Try this 

![image](https://user-images.githubusercontent.com/18009293/117345311-c89f6880-ae7c-11eb-8f1b-3f038fd98563.png)

**Comment by kardoqadir** [comment]
Thanks, Where I can find this section dear?

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/117367483-9e5ba400-ae98-11eb-9c8b-54f1233dc3b2.png)
