### ISSUE TITLE
Strange "False" text on every channel page!

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5072]
I am seeing this on each channel page, not sure where it comes from but here are some screenshots:

![Screen Shot 5781-08-23 at 19 16 23](https://user-images.githubusercontent.com/58882903/117175419-7fe1a400-add7-
11eb-8141-07309af3c057.jpg)

This is the top one:

![Screen Shot 5781-08-23 at 19 25 33](https://user-images.githubusercontent.com/58882903/117175706-cd5e1100-add7-11eb-854a-353f249caf6f.jpg)

This is to the right side of the first video below it:

![Screen Shot 5781-08-23 at 19 25 53](https://user-images.githubusercontent.com/58882903/117175716-ce8f3e00-add7-11eb-88e8-69d010bf21f6.jpg)

**Comment by guymass** [comment]
Once I removed this checkbox the issue was gone so there is a bug with this checkbox for bigVideoCarousel!

![Screen Shot 5781-08-23 at 19 33 46](https://user-images.githubusercontent.com/58882903/117176811-f632d600-add8-11eb-89fc-dbc116870a35.jpg)

**Comment by DanielnetoDotCom** [comment]
Do you have the ADs plugin enabled?

**Comment by guymass** [comment]
Yes we found it was something left on the plugin we didn't notice, this is fixed now!
