### ISSUE TITLE
Broadcast problem from a remote server.

### ISSUE THREAD

**Issue by Proton-people** [WWBN/AVideo#5073]
I configured a remote server according to this tutorial: https://github.com/WWBN/AVideo/wiki/Live-Plugin#nginx-only-installation
 The broadcast page works but offline. The broadcast section does not work at all. There is no broadcast notification on the homepage either. Can I not include something or did it wrong? Please help with advice on how to fix it. Thank you.

![bandicam 2021-05-05 18-44-58-062](https://user-images.githubusercontent.com/48072457/117187636-e3a9a400-adba-11eb-85cb-98dccc60cb1d.jpg)
![bandicam 2021-05-05 18-57-50-007](https://user-images.githubusercontent.com/48072457/117187646-e73d2b00-adba-11eb-845c-d2926e220136.jpg)
![bandicam 2021-05-05 18-40-04-279](https://user-images.githubusercontent.com/48072457/117187688-f15f2980-adba-11eb-92bf-a55368cd4563.jpg)
![bandicam 2021-05-05 18-54-25-389](https://user-images.githubusercontent.com/48072457/117187730-fd4aeb80-adba-11eb-8a1d-c36c851b091e.jpg)
![bandicam 2021-05-05 19-03-29-723](https://user-images.githubusercontent.com/48072457/117187758-0471f980-adbb-11eb-987d-c4b644ed5a0f.jpg)
![bandicam 2021-05-05 19-04-12-027](https://user-images.githubusercontent.com/48072457/117187786-0d62cb00-adbb-11eb-8323-0056e7e6419c.jpg)
![bandicam 2021-05-05 19-05-29-660](https://user-images.githubusercontent.com/48072457/117187811-15226f80-adbb-11eb-83dc-fe8b840cff9c.jpg)
![bandicam 2021-05-05 19-07-47-594](https://user-images.githubusercontent.com/48072457/117187840-1eabd780-adbb-11eb-934e-b86b6284faa7.jpg)
![bandicam 2021-05-05 18-53-22-969](https://user-images.githubusercontent.com/48072457/117187856-223f5e80-adbb-11eb-9525-421965cc6d86.jpg)

**Comment by guymass** [comment]
I don't think that on your PlayerServer URL you need to add the .m3u8 after the /live, try maybe without.

**Comment by Proton-people** [comment]
> Я не думаю, что на вашем URL-адресе PlayerServer вам нужно добавить .m3u8 после / live, попробуйте, может быть, без.
> Также ваш getRecordedFile должен находиться по тому же пути, что и другие, и убедитесь, что вы редактируете этот файл, чтобы он содержал имя вашего сервера.
> 
> Также убедитесь, что у вас есть каталог / HLS / live и что у пользователя www-data есть доступ к нему с разрешениями.

I have two servers. One has Apache with ports 80 and 443 and the other has Nginx and Nginx-RTMP with ports 8080, 1935, 444. The file is located here /usr/local/nginx/html/getRecordedFile.php. I did all your recommendations and unfortunately it didn't help.
![bandicam 2021-05-05 21-05-46-229](https://user-images.githubusercontent.com/48072457/117197130-33da3380-adc6-11eb-93a6-0bf35c0c0382.jpg)
![bandicam 2021-05-05 21-06-41-899](https://user-images.githubusercontent.com/48072457/117197149-38065100-adc6-11eb-9240-a810ceed4f64.jpg)

**Comment by Proton-people** [comment]
> I don't think that on your PlayerServer URL you need to add the .m3u8 after the /live, try maybe without.
> Also your getRecordedFile should be under the same path as the others and make sure you edit that file to contain your server name.
> 
> Also make sure you have an /HLS/live directory and that www-data user has access to it permission wise.

Can you show which line in this file needs to be edited and enter the server name? Thank you.
