### ISSUE TITLE
Language Button Menu Alignment

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5074]
In recent weeks the language bar suddenly went a bit above the rest of the menu items and I cannot find how to fix it. Not sure really why it appears like that.

![Screen Shot 5781-08-23 at 21 32 04](https://user-images.githubusercontent.com/58882903/117191635-73fedd80-ade9-11eb-83e5-a060af8292c8.jpg)

How or where would I fix this in CSS.

**Comment by DanielnetoDotCom** [comment]
This update may fix, but first check this before update 
https://github.com/WWBN/AVideo/issues/5075

**Comment by guymass** [comment]
Cool, well I updated today everything including all plugins we have but still this menu item for language is moved up not sure why.

**Comment by DanielnetoDotCom** [comment]
make sure you clear the cache also the browser cache

**Comment by guymass** [comment]
Cleared cache and cleared also browser cache but still menu is offside.

![Screen Shot 5781-08-27 at 11 37 34](https://user-images.githubusercontent.com/58882903/117565679-27eabc00-b0bb-11eb-875b-d5916d7caeb7.jpg)

**Comment by guymass** [comment]
Yes I see it translated as well on my menu now so its fixed, however what do I do regarding the other menu Items on TopMenu which are not translated anymore.

**Comment by DanielnetoDotCom** [comment]
Can you please screenshot again the TopMenu where it is not translated?

**Comment by guymass** [comment]
Seem to be all those Titles in the plugin for CustomizeUser and I think also Live.

![Screen Shot 5781-09-05 at 1 25 13](https://user-images.githubusercontent.com/58882903/118379756-97920700-b5e5-11eb-9c13-732d0c36fc23.jpg)

**Comment by DanielnetoDotCom** [comment]
This update may resolve some translations

**Comment by guymass** [comment]
Yeap! that fixed my issue, everything is translated fine now, closing this issue.

Much thanks!

**Comment by guymass** [comment]
Sorry I needed to reopen this as I forgot to mention how do we translate the Categories?
We currently created them in Hebrew, however this is not good for our english speaking, so I need to create them in English and than being able to translate them to Hebrew. So categories should be part of the translation system.

![Screen Shot 5781-09-07 at 21 42 28](https://user-images.githubusercontent.com/58882903/118706384-fb087880-b821-11eb-92f3-f52dfd176424.jpg)

**Comment by DanielnetoDotCom** [comment]
please try now

**Comment by guymass** [comment]
Awesome!! seems to work now. Just to clarify to anyone who doesn't know, you must first create the english string in the EN file like this for example:

$t['Live Conference'] = "Live Conference";

And then you can translate it on the other files just copy the same line of code and change the right side for translation.

**Comment by guymass** [comment]
Need to add also Live Links Title.

**Comment by guymass** [comment]
Need to add also Live Links Title.

**Comment by DanielnetoDotCom** [comment]
On the next update I will fix it

**Comment by guymass** [comment]
this is fixed
