### ISSUE TITLE
Next Update

### ISSUE THREAD

**Issue by DanielnetoDotCom** [WWBN/AVideo#5075]
One of the main reasons for slowness I notice on AVideo is the way the videos are stored.

Here I am trying to explain what I see:
- Currently, the video files are all in the same folder (videos dir) and they are all mixed
- each video has multiple files, I can say each video has about 6 to 8 files. 
- even HLS files have their own folder but the images, subtitles, etc are mixed with all other videos.
 
In other words, if you have 1000 videos you will have at least 6k+ files on your videos folder. this causes the script to require a lot of disk IO when you clear the cache for example. another example is if you upload a new image and the script needs to search for new updates on the file system. When this happens, the script needs to search all 6K files for new images/updates.

To try to resolve that on the next update, I will create one folder for each video, and the script will automatically move each video content to his specific folder. it will reduce the total files on the videos folder and also speed up a lot when we need to do something on the videos. After the next update, I am expecting some performance progress, for example, if the script needs to search for new images on a video, the script will only need to search inside its own folder. so instead of search in 6k files, the script will only search on 6 to 8 files only. this will make a lot of difference.

This is already tested locally and seems to be working fine, tomorrow I will probably release it, but I still need to test with B2, S3, FTP, and YPTStorage but on those external storages nothing changes, they still hosting the files the same way as before.

Most of the plugins will be impacted by that and will require an update.

**Comment by JoshWho** [comment]
Sounds awesome and looking forward to this update. Cheers @DanielnetoDotCom 🍻😎😎

**Comment by Rolandhun74** [comment]
I look forward to this update 🤞🤜🤛

**Comment by morbificagent** [comment]
Im a little bit scared about such a big change but it would be great ;-)

**Comment by DanielnetoDotCom** [comment]
I tested multiple times here and it seems fine, but I recommend you to backup the videos folder and the database.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom this is awesome, but would have been better if every file type had it's own dir for easier management for cdn and reverse-proxy.

This approach will still create many folders , like HLS videos. But it's definitely a game changer if each video will have it's files in separated directories.

**Comment by DanielnetoDotCom** [comment]
I thought about it, but it would get me into trouble with xsendfile.

**Comment by DanielnetoDotCom** [comment]
Demo site, tutorials and flix updated.

I could confirm it works with the YPTStorage, it is not tested yet with FTP, S3 and B2

is recommended after the update go to the install directory you will find 2 interesting scripts, moveFilesToFolder.php and deleteOrphanFiles.php

First run the moveFilesToFolder.php  (it will move all the files to its specific folder)

```
cd /var/www/html/AVideo/install
php moveFilesToFolder.php
```

Then remove the unused files (it will free some space)

```
cd /var/www/html/AVideo/install
php deleteOrphanFiles.php
```

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I'm trying to test it out on local environment on a new install , getting errors from encoder.

```
[06-May-2021 19:12:44 UTC] getReturn_vars {"videos_id":0,"video_id_hash":""}
[06-May-2021 19:12:44 UTC] try [1] return_vars->videos_id is empty {"videos_id":0,"video_id_hash":""}
[06-May-2021 19:12:44 UTC] getReturn_vars {"videos_id":0,"video_id_hash":""}
[06-May-2021 19:12:44 UTC] {}
```

`try [1] Error on return_vars->videos_id`

**Comment by DanielnetoDotCom** [comment]
this is an log only, not really an error. but I recommend to update the streamer and encoder

**Comment by DanielnetoDotCom** [comment]
BTW, I just confirm it is working now with YPTStorage, B2 and S3

Still need to test with FTP Storage

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom it's an error;

![image](https://user-images.githubusercontent.com/52116577/117408873-35684080-af19-11eb-8292-cf0f186f7069.png)

**Comment by JoshWho** [comment]
It is working for me

**Comment by morbificagent** [comment]
@DanielnetoDotCom you say its working with yptstorage... This has the same filestructure with /videos right?

With "its working" do you mean the yptstorage is working without changes like before or is the new better filestructure copied to it so there is a benefit too?

**Comment by milehighkaraoke** [comment]
Unable to login after recent gitpull and  successful merge of the video folder. 
Still receive this and no way to log in. 
![20210506_203335](https://user-images.githubusercontent.com/70327833/117414421-58243600-aed4-11eb-92e9-a560a8cdb8bd.jpg)

**Comment by milehighkaraoke** [comment]
https://mhktube.com

**Comment by milehighkaraoke** [comment]
Also did a php reset of the plugins  I'm stuck like chuck.

**Comment by DanielnetoDotCom** [comment]
> @DanielnetoDotCom you say its working with yptstorage... This has the same filestructure with /videos right?
> 
> With "its working" do you mean the yptstorage is working without changes like before or is the new better filestructure copied to it so there is a benefit too?

The storage structure was not changed, only the streamer one

**Comment by DanielnetoDotCom** [comment]
> @DanielnetoDotCom it's an error;
> 
> ![image](https://user-images.githubusercontent.com/52116577/117408873-35684080-af19-11eb-8292-cf0f186f7069.png)

The encoder and streamer must be updated

**Comment by DanielnetoDotCom** [comment]
> @DanielnetoDotCom I'm trying to test it out on local environment on a new install , getting errors from encoder.
> 
> ```
> [06-May-2021 19:12:44 UTC] getReturn_vars {"videos_id":0,"video_id_hash":""}
> [06-May-2021 19:12:44 UTC] try [1] return_vars->videos_id is empty {"videos_id":0,"video_id_hash":""}
> [06-May-2021 19:12:44 UTC] getReturn_vars {"videos_id":0,"video_id_hash":""}
> [06-May-2021 19:12:44 UTC] {}
> ```
> 
> `try [1] Error on return_vars->videos_id`

I found a bug on the videoHLS plugin, please update it to version 5.1

**Comment by wetubeclub** [comment]
The update for the HLS plugin is ready??  because I have the same problem

![](https://user-images.githubusercontent.com/52116577/117408873-35684080-af19-11eb-8292-cf0f186f7069.png)

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
Yes update the VideoHLS plugin to version 5.1

**Comment by DanielnetoDotCom** [comment]
Also update the encoder and streamer

**Comment by wetubeclub** [comment]
I downloaded it 5 minutes ago but it is in version 5.0

**Comment by wetubeclub** [comment]
sorry my mistake!!!

**Comment by wetubeclub** [comment]
is ok now working!!

Thank you Daniel

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I hope you could change the file-structure also on ypt-storage. Because it's taking hours to load the pages on the browser and the server side. All videos are on the same dir, and with automatic mp4, each file creates 4-5 files. Maybe in future releases would be appreciated.

**Comment by milehighkaraoke** [comment]
@akhilleusuggo  update to 11.0 and run the commands in this thread to merge the files into their own individual folders

**Comment by akhilleusuggo** [comment]
@milehighkaraoke I'm talking about YPT-Storage, not the main site. The main site is done. But the YPT-storage has been unchanged. It was a request only.

I've changed a bit my comment , maybe I didn't express well what I wanted to say.

**Comment by DanielnetoDotCom** [comment]
> @DanielnetoDotCom I hope you could change the file-structure also on ypt-storage. Because it's taking hours to load the page* on the browser and the server side ( when login into the storage via browser ). All videos are on the same dir, and with automatic mp4, each file creates 4-5 files. Maybe in future releases would be appreciated.

YPT storage is not changed yet

**Comment by GreggShimokura** [comment]
Hi. 
I am curious if this is an update to avideo version 8.2 to say 8.3 ?

Also I am wondering if there are any PHP version dependencies or testing for different versions such as 7.3.x or 7.4.x ?

I am currently running avideo with PHP version 7.3.11 and all is fine.

However, I would like to run avideo with PHP version 7.3.28 or 7.4.19 and when I try to do so, in both versions I strange behaviour and in my case becomes unuseable.

Thank you,

Gregg

**Comment by milehighkaraoke** [comment]
Greg 11.0 is the newest version. I am running it on php 8  and Ubuntu 20.10 with absolutely no problem 
![Screenshot_20210514-043230_Samsung Internet](https://user-images.githubusercontent.com/70327833/118259054-e452d200-b46d-11eb-8121-298cacce2b60.jpg)

**Comment by milehighkaraoke** [comment]
You can only pull the newest release and that is 11.0  
sudo git pull   your AVideo directory and your encoder directory to get the latest version

**Comment by GreggShimokura** [comment]
Whoa.. I am quite far behind.   When I click Update Version it says I am up to date as well... but with Version 8.2.

Will try to update.  Unfortunately it seems I did not make my original install with git so git pull does not work from my installation directory.  

Gregg

**Comment by milehighkaraoke** [comment]
https://youphptube.readthedocs.io/en/latest/howto/update.html

**Comment by milehighkaraoke** [comment]
And don't forget this step
cd /var/www/html/AVideo/install php moveFilesToFolder.php
cd /var/www/html/AVideo/install php deleteOrphanFiles.php

**Comment by GreggShimokura** [comment]
Hi again,
Thank you for the quick replies.. I was able copy over the files and get it partially working.

In both AVideo and the AVideo-Encoder I am not able to login.. either as a user or as an Admin so in AVideo I see my videos as a browser but I cannot get to the Update Version button and in the Encoder I am blocked from getting in at all.

Are there steps related to porting over my existing account/user/admin credentials  into the updated versions?

Thanks again,

Gregg

**Comment by GreggShimokura** [comment]
To clarify further on the Login issues I am having:
AVideo:
- Clicking on 'Sign-In' I see "Welcome Back" but no entry form for Username/Password

AVideo-Encoder:
- I land on the Sign-in page, but it does not recognize any username/password I enter

Gregg

**Comment by milehighkaraoke** [comment]
I will have to get some input from @DanielnetoDotCom  as I am not sure what your solution is.

**Comment by DanielnetoDotCom** [comment]
@GreggShimokura check if your server disk is not full

**Comment by GreggShimokura** [comment]
Hi.  49% available.. (1TB or so).. 

On my end I will trying moving forward my Apache version.

Just curious if there is a way to move my videos directory into a freshly cloned avideo installation directory.. and keep all the accounts/categories/user settings?

Gregg

**Comment by DanielnetoDotCom** [comment]
if you move the videos dir and the database it should work

**Comment by GreggShimokura** [comment]
Thanks. To clarify from the source/previous installation directory on the command line:

**videos**: mv videos <destination installation directory>

**database**: mv ???  <destination installation directory>

Or in other words how can I be sure to move the **database** correctly?

Gregg

**Comment by DanielnetoDotCom** [comment]
sorry, but you will need to google for that.

**Comment by GreggShimokura** [comment]
I will be trying on the same server, so if the account etc information is stored in my mysql database it will remain accessible.

But I am wondering if there are any mysql configuration or other database setup files that should be moved over to the new installation directory?

**Comment by DanielnetoDotCom** [comment]
If the mysql credentials are different you just need to update the configurations.php file

**Comment by GreggShimokura** [comment]
FYI - After updating my Apache version, my PHP segmentation faults disappeared so I have resolved my issues and in reality do not need to upgrade AVideo.   I did try to upgrade anyway but could not so I am currently staying on version 8.2.

I did try to make a new installation but got stuck with a "Unknown error" message:  In my Apache log it stated:

`[php7:warn] PHP Warning:  require_once(../videos/configuration.php): failed to open stream: No such file or directory in .../avideo/view/user.php on line 4, referer: 
[php7:error] PHP Fatal error:  require_once(): Failed opening required '../videos/configuration.php' (include_path='.:/usr/local/Cellar/php@7.4/7.4.19/share/php@7.4/pear') in .../avideo/view/user.php on line 4, referer: `

**Comment by DanielnetoDotCom** [comment]
you should open a new issue for that.

also looks like you are not using Ubuntu as is recommended

**Comment by GreggShimokura** [comment]
I have just migrated to Mac OS Catalina (10.15).. from Yosemite (10.10). No possibility of Ubuntu at my end.  May have to reconsider use of AVideo for the future.

**Comment by JoshWho** [comment]
Disable SElinux and rebuild PHP-Mysql

**Comment by GreggShimokura** [comment]
Ok thanks.  Not sure if/when I'd get the opportunity to try this out.  I am on MacOS Catalina which has different security features from previous MacOS versions (and not called SElinux) so it might be complicated for me to debug but likely the source of my problems.
