### ISSUE TITLE
Purchasing plugins

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#5081]
Hi,

how do i access previously purchased plugins? also I want to purchase some others however it's saying I have no account on the tutorials site?

I then created an account however when I go to pay for the plugin it asks me to login but doesn't recognise me.

What site do i actually need to log into?

Many thanks

**Comment by akhilleusuggo** [comment]
https://youphp.tube/marketplace/

**Comment by millzee01** [comment]
thx, i had to create a new account and logged in then brought the plugin i wanted but cannot see my previous ones.  nm

**Comment by DanielnetoDotCom** [comment]
@millzee01 you must use the same user that you used before .

if you still have the PayPal receipts for the previous plugins email me the receipt and your user # and I will enable the plugins for you

**Comment by millzee01** [comment]
its ok, i managed to find the plugins i purchased on my google drive :-)  thanks anyway

**Comment by DanielnetoDotCom** [comment]
You may need ot update them with the new version

**Comment by millzee01** [comment]
hmm, i'll try and dig out which account i used to buy the b2 backblaze and mp4thumbs plugin.  I suspect they both will need updating.

**Comment by DanielnetoDotCom** [comment]
Correct they do

if you did the PayPal receipt send it to my email developer@youphptube.com and I will enable it in your new account 

also send me your user #

**Comment by millzee01** [comment]
All sorted, thanks for the support!

**Comment by LievreAI** [comment]
i buy the plugin from https://youphp.tube/marketplace/
the question then how i install it on my website
as i see its diffrent site so how i pu the plugin in my website?

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin
