### ISSUE TITLE
streamer and encoder permissions

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#5083]
Does anyone know if there is a document anywhere that shows me what file permissions should be set on the folders and files for the streamer and encoder?

I ftp'd my html folder to another server but need to properly set the permissions back.

Thanks

**Comment by DanielnetoDotCom** [comment]
I strongly recommend you to use git clone. do not FTP

**Comment by millzee01** [comment]
Re-cloned and all good!
