### ISSUE TITLE
Congratulations!!

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#5084]
Daniel,
I want to thank you publicly   for the latest version of the script, it works much faster than before and there we have  about 3500 videos
Thanks again for your work!

Ilias

**Comment by DanielnetoDotCom** [comment]
Thank you, I am glad about your feedback

**Comment by RememberForgottenHits** [comment]
Thanks too for this nice code and it really works faster now !!! Many big thanks !!!
