### ISSUE TITLE
updating AVideo version and plugins

### ISSUE THREAD

**Issue by graphiclion** [WWBN/AVideo#5091]
I am trying to update AVideo and some plugins but I am missing the first 1-2 steps to find where i should do so. I know to go to my AVideo dir and do a Git Pull but where do i go to find the Avideo dir? Sorry I am a retard on this part

**Comment by milehighkaraoke** [comment]
Var/www/avideo

**Comment by akhilleusuggo** [comment]
on the default apache2 location ( and installation by the wiki ) is under `/var/www/html/AVideo`

The install/ dir is on `/var/www/html/AVideo/install/`
