### ISSUE TITLE
UNDER MAINTENANCE

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5096]
After updating these plugins:
Backup
Chat2
Customize
MP4ThumbsAndGif
SendRecordedToEncoder
VideoResolutionSwitcher
VideoThumbnails

I get this problem.
But after disabling the VideoThumbnails plugin, the problem goes away.
Can you tell me how to solve this problem?

When I open any video I get this warning:
UNDER MAINTENANCE
Sorry for the inconvenience.
Can you tell me what's going on?
Depends on what?
Thank you

![hh](https://user-images.githubusercontent.com/82677269/117555244-d8c26e00-b05d-11eb-9451-936437c53249.PNG)

**Comment by DanielnetoDotCom** [comment]
you are not running AVideo version 11 (https://github.com/WWBN/AVideo/issues/5075)

make a git pull

Then run the moveFilesToFolder.php (it will move all the files to its specific folder)

```
cd /var/www/html/AVideo/install
php moveFilesToFolder.php
```

Then remove the unused files (it will free some space)

```
cd /var/www/html/AVideo/install
php deleteOrphanFiles.php
```

**Comment by sharknetwork24** [comment]
![rfj](https://user-images.githubusercontent.com/82677269/117557149-568f7500-b070-11eb-83e1-cc9367cff5d5.PNG)

SendRecordedToEncoder doesn't work either

Daniel can you tell me the commands I need to execute?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/117557691-1c13e100-b04c-11eb-9746-6bdcd307a227.png)

**Comment by sharknetwork24** [comment]
The procedure tell me if it is correct.
I update all plugins and then give the git pull command.
Right Daniel?

**Comment by DanielnetoDotCom** [comment]
you can update the plugins before or after, as long as you make both procedures

**Comment by sharknetwork24** [comment]
is this command correct?

cd /var/www/html/AVideo/ && sudo git pull

or I have to do something else

**Comment by DanielnetoDotCom** [comment]
> is this command correct?
> 
> cd /var/www/html/AVideo/ && sudo git pull
> 
> or I have to do something else

Probably that is the command, if you are not sure read here
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

and do not forget this https://github.com/WWBN/AVideo/issues/5096#issuecomment-835554317
