### ISSUE TITLE
API has small iframe box and huge white boarder.  Very hard to look at API info.

### ISSUE THREAD

**Issue by tbryantAE** [WWBN/AVideo#5097]
if you click on the API info in Plugins this iFrame pops up with a huge white boarder and it is very difficult to look at API info.  See picture.

![image](https://user-images.githubusercontent.com/50838005/117555662-afd2b680-b026-11eb-8125-b6dfa2c8b94c.png)

**Comment by DanielnetoDotCom** [comment]
This looks different on my side

![image](https://user-images.githubusercontent.com/18009293/117667672-7d869d80-b17b-11eb-9cf2-9a78bc8dbce0.png)

Make sure you are up to date and try to clear your browser cache

**Comment by tbryantAE** [comment]
It is fixed with v11.0 update
