### ISSUE TITLE
Default background?

### ISSUE THREAD

**Issue by tbryantAE** [WWBN/AVideo#5098]
so now when you open a video, it shows this large default background?  How do you get rid of this?  See picture.

![image](https://user-images.githubusercontent.com/50838005/117555836-2fad5080-b028-11eb-9eb9-466da449978b.png)

**Comment by DanielnetoDotCom** [comment]
Try this

![image](https://user-images.githubusercontent.com/18009293/117667514-5334e000-b17b-11eb-882d-5372a7a1a9c0.png)
