### ISSUE TITLE
Issues with mysterious "Swapped videos" persists.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5099]
**Describe the bug**
Videos are randomly being swapped at some point after uploading/metadata'ing/verifying playback.

**To Reproduce**
Embed (YouTube) video A, edit its metadata, verify playback.
Upload video B, edit its metadata, verify playback.
In the future, load video B's page - observe, video B's metadata, and video B's poster frame. Video B doesn't play properly - on Safari/mobile (tablet) it doesn't play at all. On Safari/Desktop the video doesn't play but the audio does. 

Video A:
https://conspyre.tv/video/4980/i-wear-my-face-mask-in-the-car

Video B: 
https://conspyre.tv/video/4977/they-don-t-want-to-see-people-like-us---the-highwire?channelName=Conspyre

**Expected behavior**
It not do that

**PLEASE**
Look at what you can to debug and let me know that you did so I can delete both of these before video "A" continues to infect further uploads.

**Comment by walt93** [comment]
PLS let me know asap I'm already seeing attempted page views of the affected files in my anaytics.

**Comment by DanielnetoDotCom** [comment]
The swap video is to swap selfhosted (encoded/uploaded) videos not embed ones.

if you want to change the embed code you just need to edit the video Link

![image](https://user-images.githubusercontent.com/18009293/117669709-94c68a80-b17d-11eb-8904-50db39359e46.png)

**Comment by walt93** [comment]
Yes, unfortunately this isn't from my swapping the videos, it seems that it may be related to #5107, after I do an embed from Youtube I'm finding these damaged videos

Not tracking what you mean by embed code/video link - I'm looking into this
