### ISSUE TITLE
IPTV doesn't like portrait mode aspect ratio

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5100]
**Describe the bug**
Add a video that someone clownishly recorded in portrait orientation to IPTV
Playback is stretched.

**To Reproduce**
1. Add a video that someone clownishly recorded in portrait orientation to IPTV
2. Observe it

**Expected behavior**
To not do that

**Comment by DanielnetoDotCom** [comment]
IPTV still under development

**Comment by walt93** [comment]
I see that. :-) Just filing issues for your list.
