### ISSUE TITLE
Up Next is displaying the poster frame for the current image 

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5106]
**Describe the bug**
After updating to 11.0, On video page, Up Next is displaying the poster frame for the current video 

**To Reproduce**
1. Click on video page
2. Observe play next poster frame

**Expected behavior**
Play next video renders correct poster frame

**Screenshots**
![Screen Shot 2021-05-08 at 11 32 14 PM](https://user-images.githubusercontent.com/11711050/117562715-df4ce780-b055-11eb-875b-dbc3af31d0ea.png)

**Comment by DanielnetoDotCom** [comment]
thanks for notice that, here is a fix
