### ISSUE TITLE
CRITICAL: Embed from YouTube is blowing out a random number of videos DB entries

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5107]
**Describe the bug**
Finding many videos pointing at the wrong file, where the video page loads correct metadata and video/stillframe are pointing at the wrong video. The pattern is detected: Video A.....W were created and working. Video X is an embed from YouTube. Videos A...W are now pointing at X.

**To Reproduce**
1. Embed a YouTube video
2. For each of more than 120 videos, load the video page and verify if the correct poster frame loads.
3. 6/120 videos checked 
4. note: 120 videos selected were spot checked; top videos from several categories i.e. not consecutive 120 IDs)

**Expected behavior**
Embedding a video from YouTube not to spray the video randomly all over the site.

**Pain points, and downstream bugs**
Files broken by "Embed video" cannot be repaired by "Swap video". _(resulting in hours of work and dead inbound links)_
**>3,000 files to hand check, many hours… Would appreciate a script to look for damage**

**Data for analysis, please report back ASAP when I may delete these files!**
Here is video X. It is a YouTube embed.
https://conspyre.tv/video/4904/the-demonic-truth-behind-emojis😵

Here is a PDF file A, it is pointing at X, came from direct upload. 
https://conspyre.tv/video/4894/transcripts-of-william-coopers-mystery-babylon-series---the-history-the-dogma-and-the-identity-of-mystery-babylon

Here is video B, it is pointing at X. It came from social media, was a direct upload.
https://conspyre.tv/video/4889/how-to-end-the-mask-mandate-in-your-area?channelName=VeritasWorldNews

videos 4890...4898 are pointing at the correct video

Here is video C, it is pointing at X. It came from social media, was a direct upload.
https://conspyre.tv/video/4899/build-back-better-montage

Here is a video D, it is pointing at X. I downloaded it from social media, uploaded with direct upload.
https://conspyre.tv/video/4900/insight-from-an-ikea-insider

Here is video E, it is pointing at X don't recall if was direct upload or encoder.
https://conspyre.tv/video/4901/making-up-your-mind

Here is PDF F, it is pointing at X. It was a direct upload.
https://conspyre.tv/video/4902/edmond-paris---the-secret-history-of-the-jesuits---pdf-tkrg?channelName=VeritasWorldNews

*** Videos A-E display the correct poster frame on the index. PDF F is displaying an empty video frame. It is an exception

--
Here is video Q, it is another YouTube embed
https://conspyre.tv/video/4980/i-wear-my-face-mask-in-the-car

Here is video P, it is pointing at video Q. This is a separate stream of swapped videos that I already purged, missed this one.
https://conspyre.tv/video/4977/they-don-t-want-to-see-people-like-us---the-highwire

PATTERN DETECT: embedding a YouTube is jamming a random number of videos that were encoded behind it. How many is unknown, I am only testing perhaps 120 videos out of 3300. There is very likely more damage that I have yet to find.

**Comment by DanielnetoDotCom** [comment]
I am not sure what is going on but can you please give me the result from this mysql query

`SELECT id, title, status, type, filename, videoLink FROM videos WHERE id IN(4904, 4894, 4889,4899,4900,4901,4902,4980,4977);`

**Comment by walt93** [comment]
mysql> SELECT id, title, status, type, filename, videoLink FROM videos WHERE id IN(4904, 4894, 4889,4899,4900,4901,4902,4980,4977);
    +------+---------------------------------------------------------------------------------------------------------------------+--------+-------+----------------------------------------------------------------------------------------------------------------------------+------------------------------+
    | id   | title                                                                                                               | status | type  | filename                                                                                                                   | videoLink                    |
    +------+---------------------------------------------------------------------------------------------------------------------+--------+-------+----------------------------------------------------------------------------------------------------------------------------+------------------------------+
    | 4889 | How to END the mask mandate in your area                                                                            | a      | embed | b68fa136a8273db0_6081cc49ecc0f3.69916334                                                                                   | https://youtu.be/Nmg9D7c4iEc |
    | 4894 | Transcripts of William Coopers Mystery Babylon Series - The History, the Dogma, and the Identity of Mystery Babylon | a      | embed | TranscriptsofWilliamCoopersMysteryBabylonSeriesTheHistorytheDogmaandtheIdentityofMysteryBabylonpdf_608463141bd7f0.68247782 | https://youtu.be/Nmg9D7c4iEc |
    | 4899 | Build Back Better montage                                                                                           | a      | embed | BuildBackBettermontage_6087a512391e69.87372832                                                                             | https://youtu.be/Nmg9D7c4iEc |
    | 4900 | Insight from an IKEA Insider                                                                                        | a      | embed | InsightfromanIKEAInsider_6087a6e0b86c39.02020943                                                                           | https://youtu.be/Nmg9D7c4iEc |
    | 4901 | Making Up Your Mind                                                                                                 | a      | embed | MakingUpYourMind720pH265AAC_6087afb4cdd613.78483755                                                                        | https://youtu.be/Nmg9D7c4iEc |
    | 4902 | Edmond Paris - The Secret History of the Jesuits - pdf TKRG                                                         | a      | embed | EdmondParisTheSecretHistoryoftheJesuitspdfTKRG_6087b00b503381.18392832                                                     | https://youtu.be/Nmg9D7c4iEc |
    | 4904 | The Demonic Truth Behind EmojisðŸ˜µ                                                                                 | a      | embed | _YPTuniqid_6087b2df9f66e3.62958872                                                                                         | https://youtu.be/Nmg9D7c4iEc |
    | 4977 | They Don't Want To See People Like Us - The Highwire                                                                | a      | embed | video_210508010135_a4c1                                                                                                    | https://youtu.be/2DDXG-dHugc |
    | 4980 | I Wear My Face Mask in the Car                                                                                      | a      | embed | v_210508130610_dbe8                                                                                                        | https://youtu.be/2DDXG-dHugc |
    +------+---------------------------------------------------------------------------------------------------------------------+--------+-------+----------------------------------------------------------------------------------------------------------------------------+------------------------------+
    9 rows in set (0.00 sec)

**Comment by DanielnetoDotCom** [comment]
Hi, that is the thing, I do not know how this happen. but look at the videoLink, only embed videos should have that

if you remove the videoLink make it = '' and make type = 'video' you should be able to see all your videos again

maybe worth for you to run a query to remove all the video links and change the type of the videos. then you may want to embed the videos again.

if you can detect how this happen I may be able to improve the script to avoid this happen again in the future

**Comment by walt93** [comment]
Ok, making some sense, I need to figure out the right SQL command so I don't blow apart the database - not an expert here... Let me see if I can connect to it with Valentina Studio or some other GUI editor and fix it that way. 

Thanks for taking a look. If I find any further clues will drop them back here.

**Comment by walt93** [comment]
I was able to fix those, and found the rest that had been wiped with those two YouTube embeds.

Searching the DB  I'm noticing a different kind of damaged entry. I've got about 75 rows where the filename got wiped out, so I don't think they're going to be as easy to repair. Just FYI.

    | 1910 | 1 Edgar Cayce Search for the Hall of Records, Egypt (Part 1) | a      | embed | _YPTuniqid_6053bd019ec438.05915993 | https://youtu.be/TbMuuMJ7IRg |
    | 1911 | 2 Edgar Cayce Search for the Hall of Records, Egypt (Part 2) | a      | embed | _YPTuniqid_6053bd02b6bb77.49755712 | https://youtu.be/TbMuuMJ7IRg |
    | 1912 | Edgar Cayce's Tour of Egypt                                  | a      | embed | _YPTuniqid_6053bd0e1d5e59.53970066 | https://youtu.be/TbMuuMJ7IRg |
    | 1914 | Edgar Cayce's Hall of Records Revealed                       | a      | embed | _YPTuniqid_6053bd0fc29811.42278294 | https://youtu.be/TbMuuMJ7IRg |
    | 1916 | 3 Edgar Cayce Search for the Hall of Records, Egypt (Part 3) | a      | embed | _YPTuniqid_6053bd2568bd60.07126074 | https://youtu.be/TbMuuMJ7IRg |
    | 1919 | Remembering Egypt - An Edgar Cayce Video                     | a      | embed | _YPTuniqid_6053bd2b0477e5.63939018 | https://youtu.be/TbMuuMJ7IRg |

**Comment by DanielnetoDotCom** [comment]
I need to figure out how is it happening.
