### ISSUE TITLE
v11.0 is randomly signing out the user after not very much time

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5112]
**Describe the bug**
After updating to v11.0 I am finding myself being signed out while performing routine tasks

**To Reproduce**
1. Sign in
2. Do stuff
3. After a short time, 5, 10, 15 minutes, get an error that you can't perform that operation
4. Observe that you're now logged out

I can't pinpoint an exact sequence to recreate it - but it's happened a dozen times in a day since updating to v11.0

**Expected behavior**
It not do that.

**Comment by akhilleusuggo** [comment]
> 3. After a short time, 5, 10, 15 minutes, get an error that you can't perform that operation

Can you post the logs or a screenshot ?
