### ISSUE TITLE
Run YPTSocket for two sites on the same server

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5114]
Can this command be run for another site on the same server? can a separate port be used?
I need to run it for two sites I have on my main server, one of which is just for separating content.

 sudo nohup php /var/www/html/AVideo/plugin/YPTSocket/server.php &

 sudo nohup php /var/www/html/AVideo2/plugin/YPTSocket/server.php &

Can this be done?

**Comment by akhilleusuggo** [comment]
Just change the port. If the first one is using port 2053 , make sure the second are using a port **different** ; example 2054.

**Comment by guymass** [comment]
OK thanks I will try that. 
I also see this when I run the test.php command, however the socket seems to be connected fine.

![Screen Shot 5781-08-28 at 14 02 45](https://user-images.githubusercontent.com/58882903/117649748-92255e80-b198-11eb-9b50-b05844ac3943.jpg)
![Screen Shot 5781-08-28 at 14 02 55](https://user-images.githubusercontent.com/58882903/117649760-95204f00-b198-11eb-93f9-47caa36bd824.jpg)

**Comment by guymass** [comment]
Trying on ports 2054 gives this error, firewall is configured, anything else I should check?

![Screen Shot 5781-08-28 at 14 13 03](https://user-images.githubusercontent.com/58882903/117650861-e4b34a80-b199-11eb-8abb-9a0990235090.jpg)

**Comment by akhilleusuggo** [comment]
because they require a valid SSL certificate for **each**
