### ISSUE TITLE
ad server and ad server location

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#5115]
I have activated the ad server and the ad server location to create a campaign after filling in the fields required for the campaign I click on the save button and the page crashes showing that it is loading
the same goes for the demo as well

Any help??
Thank you
Ilias
![ads](https://user-images.githubusercontent.com/60543030/117653927-563cca00-b195-11eb-80eb-d48d440c3823.jpg)

**Comment by DanielnetoDotCom** [comment]
Please check the log files.

**Comment by wetubeclub** [comment]
I just tried it and this is the last log

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
I could not see anything in your log file.

check also the js console for errors

https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors
