### ISSUE TITLE
Unable to upload image or edit article 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5116]
@DanielnetoDotCom  do I need to chmod a directory and if so what directory?

Getting error of no permissions when I try to edit articles or upload image into an article

**Comment by DanielnetoDotCom** [comment]
what exactly is the error?

**Comment by milehighkaraoke** [comment]
This is not a video it is strictly an article that I was trying to attach an image.

**Comment by DanielnetoDotCom** [comment]
But did you save the article first?

I need you just to test save it before add any image

**Comment by DanielnetoDotCom** [comment]
that is what I need you to clarify me, did you saved it first then open again and edit?
if you did do not that way, please try

**Comment by DanielnetoDotCom** [comment]
nevermind, I just tried on my side and it upload images fine.

should be something in your log file

**Comment by milehighkaraoke** [comment]
Ok, it works if I add articles first, save them, reopen them and then upload the images

**Comment by milehighkaraoke** [comment]
This is all under an administrative account
