### ISSUE TITLE
youtube plugin

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#5117]
Hi,

i've just updated to v11, and notice that the layout has changed due to the youtube plugin being depricated.

One of the reasons I used the youtube plugin was to slide the main menu in from the left (which shrinks the content window accordingly)

with the new version i notice the menu slides in but is shown over the content.

Does anyone know a way to get this functionality back?

**Comment by DanielnetoDotCom** [comment]
Use the gallery instead.

the Youtube was deprecated. you still can download it and manually upload it from older versions, but I do not recommend

**Comment by millzee01** [comment]
Thanks, 

Is there a way to make the menu expanded by default?  so when i click my videos or my channel the menu stays active until I close it?
