### ISSUE TITLE
v11.0 update, now Videothumbnails are not being produced.  It just uses the previously made one.

### ISSUE THREAD

**Issue by tbryantAE** [WWBN/AVideo#5119]
v11.0 update, now Videothumbnails are not being produced.  It just uses the previously made one. All of the thumbnails are exactly the same.

**Comment by DanielnetoDotCom** [comment]
The thumbs are genetate only onetime. to generate again you must delete it and the script will create again.

I could not notice that on my side.

did you also update this plugin to version 3.0?

**Comment by tbryantAE** [comment]
VideoThumbnails v3.0  I delete the thumbnail but it remains even after I delete the video that the thumbnails belongs to

**Comment by DanielnetoDotCom** [comment]
It is up to you, but I think the issue comes from somewhere else. maybe from the encoder.
