### ISSUE TITLE
Chossen Resolution not showing correctly

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5123]
Choose resolution is not what showing correctly. Here I chose 480 but 240 is showing on the video even though resolution switcher. switched to 48
![Screenshot_20210510-211015_Samsung Internet](https://user-images.githubusercontent.com/70327833/117752807-a9823d00-b1d4-11eb-8d14-f3d03792853e.jpg)
0

**Comment by DanielnetoDotCom** [comment]
How do you know is showing 240p instead of 480p?

**Comment by milehighkaraoke** [comment]
I'm not the one asking one of the people viewing my page sent that screenshot to me. I am sure they do not know how to use the JS console they probably can not even access it as a regular user

**Comment by DanielnetoDotCom** [comment]
Probably visually you cannot detect the resolution differences.

To use the console inspector you do not need special access

**Comment by milehighkaraoke** [comment]
Visually I believe it's playing in the correct Resolution. I'm just wondering why it showing me that it's into 240 when I pick 360

**Comment by milehighkaraoke** [comment]
![20210511_231338](https://user-images.githubusercontent.com/70327833/117921836-a9ef0680-b2ae-11eb-9f82-a28b04907806.jpg)
Not seeing the resolution in th console

**Comment by DanielnetoDotCom** [comment]
You need to use the network tab

![image](https://user-images.githubusercontent.com/18009293/117980665-93769880-b30a-11eb-9ffd-96f6f9917500.png)

**Comment by milehighkaraoke** [comment]
Thank you
