### ISSUE TITLE
Another Under Maintanance issue

### ISSUE THREAD

**Issue by redilee** [WWBN/AVideo#5125]
**Describe the bug**
A clear and concise description of what the bug is:
I don't know if it's a BUG. It might just be broken. I ran updates/upgrades and now I have the "Maintenance Mode screen. Can't get to any login screen. I've searched this site and followed all the instructions I can find. I've git pulled everything I know to do, and several upgrades ran. I've run "apt get update" and  "apt get upgrade" after the problem arose. Several upgrades installed. I've tried to reload and restart, plus stop and start, nginx, and that fails, nginx won't stop. 

1.  I would like to get a copy of the nginx.conf file as originally installed to check if I broke something there. 
2.  I'd like to know how to get the plugin.zip files for the plugins I bought and the free ones so I can try installing them again if necessary.  
3. what am I missing?

**Comment by DanielnetoDotCom** [comment]
Under Maintenance means you have an error 500. and the answer MUST be on the apache/avideo log files;

I belive you need to update your streamer, encode and paid plugins to get away of this error.
check this https://github.com/WWBN/AVideo/issues/5075#issuecomment-833764155

**Comment by redilee** [comment]
Thanks, Daniel. I've done those steps in #5075 (comment) before posting. Do I need to git pull each plugin to upgrade them? Can't login with any browser to click upgrade links.Thanks,LeeSent from my Galaxy
-------- Original message --------From: Daniel Neto ***@***.***> Date: 5/11/21  6:47 AM  (GMT-06:00) To: WWBN/AVideo ***@***.***> Cc: redilee ***@***.***>, Author ***@***.***> Subject: Re: [WWBN/AVideo] Another Under Maintanance issue (#5125) 
Under Maintenance means you have an error 500. and the answer MUST be on the apache/avideo log files;
I belive you need to update your streamer, encode and paid plugins to get away of this error.
check this #5075 (comment)

**Comment by DanielnetoDotCom** [comment]
Paid plugins you need to download them again and upload 

the free plugins do not need a specific git pull

if it persists check your log files

**Comment by redilee** [comment]
It appears that since I didn't buy the plugins individually, but as a bundle, the site does not provide a download link for each one, only a purchase link. What am I missing?

**Comment by redilee** [comment]
Still down. 
Why 2 nginx.conf? 
1. /usr/local/nginx/conf/nginx.conf 
2. /etc/nginx/nginx.conf 
What should be in them? 

Is there a plugin I need to disable or remove? 
What all should be "git pull"ed? I think did all that, but what do I know? 
What else? 
Thanks!

**Comment by DanielnetoDotCom** [comment]
you only use /usr/local/nginx/conf/nginx.conf

if still down, check your log files, apache and avideo
