### ISSUE TITLE
QUESTIION : list of link for embed video 

### ISSUE THREAD

**Issue by ralbator** [WWBN/AVideo#5126]
Is it possible in the embed video link, to allow the loading a list of links and not only one by one ?

<img width="1302" alt="Capture d’écran 2021-05-11 à 10 46 23" src="https://user-images.githubusercontent.com/84009775/117788154-6ad99a80-b247-11eb-8179-fba8673a2709.png">

**Comment by ralbator** [comment]
Hello Daniel that awesome and very convinent for youtube playlist.
But my problem is that I have to migrate a video list from an old home-made system. And I just have a list (xml) of a thousand links that I have to enter one by one

**Comment by DanielnetoDotCom** [comment]
For that you may need to build a custom script.
