### ISSUE TITLE
Socket hogging resources

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#5127]
Hi @DanielnetoDotCom ,

Attached are 2 screenshots on different occasions. Socket takes 100% cpu. 

It normally happens when open the homepage (gallery page) on the browser

![nohup-hog](https://user-images.githubusercontent.com/65451390/117800166-89499100-b25b-11eb-8d08-778f0a2b57dc.PNG)

==

![nohup-hog-2](https://user-images.githubusercontent.com/65451390/117800537-e7767400-b25b-11eb-92cf-ca2788a23139.PNG)

**Comment by DanielnetoDotCom** [comment]
I am checking a customer website with 54 users online now and his socket is fine

![image](https://user-images.githubusercontent.com/18009293/117853641-09bdc100-b25f-11eb-8883-f2df5d14c545.png)

maybe some misconfiguration in your server

**Comment by millzee01** [comment]
What command are you using to get this output? I wouldn't mind using this in my checks.

**Comment by DanielnetoDotCom** [comment]
The command `sudo nohup php G:\GDrive\htdocs\YouPHPTube\plugin/YPTSocket/server.php &` will hide the output and the server will run on the background.

if you run `sudo php G:\GDrive\htdocs\YouPHPTube\plugin/YPTSocket/server.php` you will see the output on your terminal. but the server will finish if you close the terminal
