### ISSUE TITLE
Cancelling direct upload

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#5128]
Hi,

When i click "direct Upload" the modal appears fine, however if I just cancel i get the spinning rotator for about 20/30 seconds before the untitled row is removed and the model dissapears.

Is there a way to improve the speed of this so it removes it straight away?

I'm using websockets, but don't think it has any impact.

**Comment by DanielnetoDotCom** [comment]
I am not sure why it is hanging for 20/30 seconds.

we may find the reason. there anything on the log acusing why is it slow?

**Comment by DanielnetoDotCom** [comment]
Are you using S3 or B2?
I guess this is the problem, the script is trying to delete files from your bucked and they are taking a long time to respond

**Comment by millzee01** [comment]
What I don't understand is it trying to delete something that doesn't exist yet?

**Comment by millzee01** [comment]
is S3 better?

**Comment by millzee01** [comment]
to be honest, i've used b2 for 3 years and the speed is really good as I restrict videos sizes to 100mb.

So the uploader when cancelled deletes the file it would of copied to b2?

**Comment by millzee01** [comment]
Hi, i'm thinking about switching to S3.

I have 10gb of videos and the usage isnt huge so i suspect it'll be only a few $ a month.

If I migrate over to S3 then is there anything I need to do locally? or do i just switch plugins and transfer the data over manually?

**Comment by DanielnetoDotCom** [comment]
The S3 and B2 are basically the same. (Only host videos), the images and metadata will stay locally.

to be honest, if B2 is working for you, you should stay with it. the only difference is the upload and delete process. the rest is the same.

**Comment by DanielnetoDotCom** [comment]
I think the speed will not change . because we do not make searches on B2

**Comment by millzee01** [comment]
@DanielnetoDotCom I am noticing more and more folders appear after I cancel a direct upload:

video_210511165646_a721
video_210511165404_766a
video_210511165213_e9e5
etc...

inside these files is a hidden file called ".move_v1.lock"

The permissions on the existing videos are 
drwxrwxr-x+ www-data:www-data which are set on the already existing video folders.

If i then cancel the upload without selecting a file, the folder stays and the lock file is not deleted.

the permissions for the new folder is
drwxr-xr-x www-data:www-data

Is this by design? or is there a permission issue here why the folder isn't removed?

**Comment by millzee01** [comment]
Hi,

i'm closing this Question as i've sorted the lagging issue when we cancel direct upload without selecting a file.

As new video filesize is set to 10, i've added the following code to object/video.php

        public function removeVideoFiles() {
            //CARL MOD - fix lagging issue when using B2 and no video file is selected
            if( $this->filesize > 10 ){
                $aws_s3 = AVideoPlugin::loadPluginIfEnabled('AWS_S3');
                $bb_b2 = AVideoPlugin::loadPluginIfEnabled('Blackblaze_B2');
                $ftp = AVideoPlugin::loadPluginIfEnabled('FTP_Storage');
                $YPTStorage = AVideoPlugin::loadPluginIfEnabled('YPTStorage');
                if (!empty($aws_s3)) {
                    $aws_s3->removeFiles($this->getFilename());
                }
                if (!empty($bb_b2)) {
                    $bb_b2->removeFiles($this->getFilename());
                }
                if (!empty($ftp)) {
                    $ftp->removeFiles($this->getFilename());
                }
                if (!empty($YPTStorage) && !empty($this->getSites_id())) {
                    $YPTStorage->removeFiles($this->getFilename(), $this->getSites_id());
                }
            } else {
                _error_log("CARL DEBUG: Bypass video as it's not been updated");
            }
            $this->removeFiles($this->getFilename());
            self::deleteThumbs($this->getFilename());
        }

This stops the b2 call and exits immediately.
