### ISSUE TITLE
After Moving files Capacity stays the same

### ISSUE THREAD

**Issue by HESSEBO** [WWBN/AVideo#5131]
My free space is running out so I bought YPTStorage plugins. after I move my files, the capacity stay the same or increasing every time. I did set up other external storage as a default to my website so that the encoded files would land there but still the same.

Any suggestions what might causing the problem? 

![55](https://user-images.githubusercontent.com/43477304/117915595-41277e80-b2ee-11eb-8925-910a6be13a8c.PNG)

**Comment by DanielnetoDotCom** [comment]
I can imagine it may happen only if the storage do not create the dummy file.

please check the local file size from one video that suppose to be on the storage.
