### ISSUE TITLE
How to monitor live streams  in real-time

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#5133]
How to monitor the live streams that are broadcasting in real-time from the site.
The one that is on the admin panel seems to not detect any live streams that are going on within the site to see how many people are on the broadcast. I really don't like the live counter because it is so old-looking and a distraction as well. 

Also, how to take off the trending from the main page of the site...that is distracting as some people wonder what is going on with the channels.

**Comment by milehighkaraoke** [comment]
Do you have your websocket configured? Real time Live stream notification is in the top tool bar. It will not function without the websocket properly configured.

**Comment by CROSSMediaNet** [comment]
Yes, I do. What I am talking about it the admin panel where we can see the
info about the livestream without the websocket. It is not what I need and
I do need something to indicate who is, was and were watching any of the
streams from the website
