### ISSUE TITLE
:BUG: direct uploads default to Inactive

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#5135]
Hi,

is there a new setting I am missing on version 11 that sets direct uploads to inactive by default?

**Comment by DanielnetoDotCom** [comment]
check this

![image](https://user-images.githubusercontent.com/18009293/117981312-421ad900-b30b-11eb-9a08-6133a8aedb60.png)

**Comment by millzee01** [comment]
I've always had this setting and unchecked.

When I encode a video, it's active.

If I direct upload a video it's inactive.

**Comment by millzee01** [comment]
I did try and test on the demo site but get:
Sorry!
$_FILES Error

when uploading a small mp4 file.

**Comment by TLCReuver** [comment]
Here the same, video **inactive** after direct upload.

![Snap1](https://user-images.githubusercontent.com/39981177/118084235-a5b30e00-b3c0-11eb-9f73-4baaf5bdd6ff.jpg)

**Comment by millzee01** [comment]
yeah, i think this needs to be upgraded to a bug.  

As an interim fix, i just updated $sql var in objects/video.php to make status = "a"

Just search for "INSERT INTO videos " and you will find where the sql INSERT command is

bear in mind that it'll revert back if you do an update.

**Comment by DanielnetoDotCom** [comment]
this should resolve it
