### ISSUE TITLE
fopen(/var/www/avideo/videos/configuration.php): failed to open stream: Permission denied in /var/www/avideo/objects/configuration.php on line 391

### ISSUE THREAD

**Issue by RvLDSDM** [WWBN/AVideo#5138]
**While uploading a video**
question: 

[12-May-2021 13:51:34 UTC] PHP Warning:  fopen(/var/www/avideo/videos/configuration.php): failed to open stream: Permission denied in /var/www/avideo/objects/configuration.php on line 391

Nginx proxies Apache on an ISPconfig webserver at another fysical node

my website.conf (names replaced by xxx):

`upstream avideocg {
    server 192.168.178.70;
}

server {
        listen *:80;
        listen [::]:80;
        listen *:443 ssl http2;
	ssl_protocols TLSv1.2;
        listen [::]:443 ssl http2;
        ssl_certificate /var/www/clients/client1/web28/ssl/xxx-le.crt;
        ssl_certificate_key /var/www/clients/client1/web28/ssl/xxx-le.key;

        server_name xxx www.xxx;

    location /.well-known {
        alias /usr/local/ispconfig/interface/acme/.well-known;
    }

    location / {
        proxy_pass https://192.168.178.70;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_set_header        Accept-Encoding   "";
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr; 
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        add_header              Front-End-Https   off;
        proxy_redirect     off;

    }
    
    location /encoder {
        proxy_pass https://192.168.178.70;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_set_header        Accept-Encoding   "";
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr; 
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        add_header              Front-End-Https   off;
        proxy_redirect     off;

    }    
}
`

**Comment by RememberForgottenHits** [comment]
You do not have administrator privileges! Do you have access to your server via SSH?

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo#important-information

> Streamer can be installed on any Server, including Windows, but the encoder and Livestream should work fine on any Linux distribution. However we recommend Ubuntu 16+ without any kind of control panel. The problem with cPanel, Plesk, Webmin, VestaCP, etc. It's because we need full root access to install some libs, and maybe compile them. Another important point is that to make Livestream work, we need to compile Nginx and the control panels often prevent us from running the commands forcing the installation available only on your panel.

There's no support for panels. You're having permissions issues.

**Comment by RvLDSDM** [comment]
> You do not have administrator privileges! Do you have access to your server via SSH? (then the problem can be solved)

Yes sir I do, there is not even another user on the system

**Comment by RvLDSDM** [comment]
> https://github.com/WWBN/AVideo#important-information
> 
> > Streamer can be installed on any Server, including Windows, but the encoder and Livestream should work fine on any Linux distribution. However we recommend Ubuntu 16+ without any kind of control panel. The problem with cPanel, Plesk, Webmin, VestaCP, etc. It's because we need full root access to install some libs, and maybe compile them. Another important point is that to make Livestream work, we need to compile Nginx and the control panels often prevent us from running the commands forcing the installation available only on your panel.
> 
> There's no support for panels. You're having permissions issues.

I am not running a Pannel, Proxmox is a type 1 hypervisor running on baremetal managing datacentres by clustering servers and disks in racks. I own the setup and have all access. The Turn-Key setup is running Debian, that should work to? 

`root@AVideoCG ~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster`

**Comment by DanielnetoDotCom** [comment]
try this

`sudo chmod 777 /var/www/avideo/videos/configuration.php`
