### ISSUE TITLE
Select theme in link

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#5140]
Hi together,

I have some content (live events) which looks much better with another theme selected.

Of course registered user could change their layout but i would like to preselect it for specific files or inside of the link to the live-stream.

Like:
http://myavideosite/live/user483?theme=cyborg

Or something like that...

Is it possible somehow so i can publish a link with a preselected theme for unregistered user?

**Comment by DanielnetoDotCom** [comment]
this update you should be able to add a ?customCSS=cyborg to enable a custom theme

**Comment by morbificagent** [comment]
Many thanks!
