### ISSUE TITLE
Question: How to remove the "Free" padlock Icon? My site is all free; this burns screen real estate and conveys no useful information

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5141]
**Describe the question**
If you could point me at the .php file that renders it, I can find/disable it.

**Screenshots**
![Screen Shot 2021-05-12 at 1 09 35 PM](https://user-images.githubusercontent.com/11711050/118038083-831ee780-b323-11eb-9641-7b5c6c183dd5.png)

**Comment by DanielnetoDotCom** [comment]
I do not have it on the top of my mind, but you can remove it with CSS
 or you can try to uncheck showCategoryTag


![image](https://user-images.githubusercontent.com/18009293/118492066-065e8580-b6f6-11eb-9202-6f43b461310d.png)
