### ISSUE TITLE
encoder - auto renaming videos to _HD

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#5143]
Is there a configurable way I can stop videos from being renamed with the added _HD when uploaded via the encoder?

the reason is we have apps that call the videos from our B2 bucket with their original name, and we disable auto creating the additional _240, _360, _480 & _540 video files as they are not required.

![avideo-formats](https://user-images.githubusercontent.com/28105720/118104450-119e7200-b3d3-11eb-91b9-d33ede9088a0.jpg)

"Do not save original video" i thought should trancode the video into the original format resolution?

**Comment by DanielnetoDotCom** [comment]
Sorry this would impact a lot on the current file system
