### ISSUE TITLE
all sorted

### ISSUE THREAD

**Issue by darkbooks** [WWBN/AVideo#5145]
I have spent thousands on this & now none of my videos play as of this morning & Daniel Neto stopped replying to me after i paid for 3 months of server time, I suspect this is because of an issue with LocalBitcoins but this is not my fault & now he has stopped my videos from working at all after huge investment

**Comment by darkbooks** [comment]
left with no choice but to use a month old backup these guys suck after paying so much Daniel treats me like this I am shocked tbh!

**Comment by DanielnetoDotCom** [comment]
Hi

I would never do that .

please tell me what is happening?

the last thing I remember is we have never complete the new server installation because you did not reply my emails

**Comment by darkbooks** [comment]
i replied lots of times and have had no responses

None of my videos would play after updating to streamer version 11 i just
had to use a 1 month old linux backup to get it working again

none of my plugins will update even when uploading the latest files :(

**Comment by millzee01** [comment]
dude, 
u just need to see the effort Daniel has put into this project to fully understand how lucky you are to have someone that is dedicated to updating the platform and helping everyone constantly!

Some people do have another life you know!

Next time, before making serious accusations like you did, i suggest stepping back and showing a little respect!

**Comment by darkbooks** [comment]
> dude,
> u just need to see the effort Daniel has put into this project to fully understand how lucky you are to have someone that is dedicated to updating the platform and helping everyone constantly!
> 
> Some people do have another life you know!
> 
> Next time, before making serious accusations like you did, i suggest stepping back and showing a little respect!

You don't know the story at all or what has gone on but in the end the only solution for me is to delete the whole thing and move on after thousands invested...
