### ISSUE TITLE
[Regression] After updating, /cat/ pages are no longer displaying images

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5147]
**Describe the bug**
Re>https://github.com//issues/5094 I pulled the update, and the behavior appears to have regressed.

I note that it is not consistent.

**To Reproduce**
1. Go to any category page
2. Observe

**Expected behavior**
Images and words

**Screenshots**
For some categories, no data is displayed:
![Screen Shot 2021-05-14 at 1 34 51 PM](https://user-images.githubusercontent.com/11711050/118326181-7af8b080-b4b9-11eb-817a-d89654016712.png)
![Screen Shot 2021-05-14 at 1 37 34 PM](https://user-images.githubusercontent.com/11711050/118326266-9cf23300-b4b9-11eb-927a-07c626c889fd.png)
![Screen Shot 2021-05-14 at 1 37 30 PM](https://user-images.githubusercontent.com/11711050/118326267-9d8ac980-b4b9-11eb-9693-665443fb1dbf.png)

For some categories, images are displaying:
![Screen Shot 2021-05-14 at 1 38 54 PM](https://user-images.githubusercontent.com/11711050/118326399-c9a64a80-b4b9-11eb-8335-d942fc738bd1.png)

**Comment by DanielnetoDotCom** [comment]
so did you add both images on a page and they are not showing?

did you try to clear the cache?

**Comment by walt93** [comment]
Yes, it is strange, I've cleared the caches and rebuilt the site index several times. I have a couple of category pages that are picking up 0 or 1 of the two images, have not checked all I have >200.

**Comment by DanielnetoDotCom** [comment]
I really need to check it myself.

can you reproduce it on demo site?

can you share the images with problems?

**Comment by walt93** [comment]
Can't repeat the same on avideo demo site. I just created a category with images, words and text - it isn't displaying text. https://demo.avideo.com/cat/category-test-1

Every category that I try to add images to now, no images are displayed. For categories that had images *prior* to about the 11.0 or possibly the last 10.x update - those /cat pages are displaying images. 

Old /cat page with images working:
 https://conspyre.tv/cat/ancient-civilizations/

/cat pages I'm trying to add images to, and nothing is happening:
https://conspyre.tv/cat/9-11

(Note that it draws a frame for the poster image, so it seems to think there is an image there - I observe that on some /cat pages that don't have an image, it doesn't draw this frame nor allocate space)
![Screen Shot 2021-05-31 at 1 23 56 PM](https://user-images.githubusercontent.com/11711050/120239613-8109c380-c213-11eb-987f-22f0cc90aac9.png)

On a /cat page that previously had an image attached, changing the image does not affect what is displayed (i.e. orig image A, update with image B, go to https://conspyre.tv/cat/graham-hancock page, see image A)

**Comment by walt93** [comment]
UPDATE: Works on (Mac OS) Safari, Chrome, Firefox, Opera, doesn't render on Brave :-/
