### ISSUE TITLE
keep getting this error starting to bug me as no one can join my site or activate there email!!

### ISSUE THREAD

**Issue by antuk21** [WWBN/AVideo#5151]
keep getting this error starting to bug me as no one can join my site or activate their email!!

https://prnt.sc/12z2cj6

I have followed the video and port forward the ports still nothing  any help with this will be greatful

**Comment by antuk21** [comment]
so i turn this  off and is works will it matter if there on   https://prnt.sc/12z2hfn

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Setting-up-AVideo-Platform-to-send-emails
