### ISSUE TITLE
can some one share there nginx config as my streams do not work right please

### ISSUE THREAD

**Issue by antuk21** [WWBN/AVideo#5153]
can someone share there Nginx config as my streams do not work right please thanks

**Comment by milehighkaraoke** [comment]
Post your nginx config and your live plug in configurations

**Comment by DanielnetoDotCom** [comment]
I always use this one for myself

https://github.com/WWBN/AVideo/blob/master/plugin/Live/install/nginx.conf

**Comment by antuk21** [comment]
thanks dan
