### ISSUE TITLE
Live Thumbnails Keep trying to generate when I have it disabled.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5154]
I have Live thumbnails disabled in the live plugin but it still always keeps trying to load them every so many seconds and causes timeout errors for the thumbs after idling for 5 minutes or more.

**Comment by JoshWho** [comment]
For now I have just enabled it and it is working fine but would like a fix for when it is disabled.

**Comment by DanielnetoDotCom** [comment]
Hi, what is not working when is disabled?

**Comment by JoshWho** [comment]
Live Thumbnails still keep generating in the background when it is disabled
