### ISSUE TITLE
Entering erroneous characters for a tag results in duplicated database entries in the "tags" table

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5155]
**Describe the bug**
Use an erroneous character in a tag, such as period or slash (example: 9/11, nasa.gov). The tag will complete. 
Later when you check the database, you see the tag repeated for each time it was used.

**To Reproduce**
1. Edit metadata
2. Add the tag "9/11" without quotes
3. Repeat for another video
4. From mysql, "select all name from tags;"

**Expected behavior**
Either the tag to accept the bad characters, or the UX to prevent their use. 

**Screenshots**
![Screen Shot 2021-05-15 at 7 10 27 PM](https://user-images.githubusercontent.com/11711050/118383268-39e3c780-b5b1-11eb-887d-07292af54071.png)
![Screen Shot 2021-05-15 at 7 12 00 PM](https://user-images.githubusercontent.com/11711050/118383296-757e9180-b5b1-11eb-9cce-520372ab8c77.png)

**Comment by DanielnetoDotCom** [comment]
Bug confirmed, this may not happen anymore
