### ISSUE TITLE
In Category editor, uploading and dismissing the editor without saving, leaves editor in a weird state and can't display same image

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5157]
**Describe the bug**
From the category editor, if you click away from the dialog/popup window it closes. If you do so without saving, you're in a weird state where it won't render the same image if you upload it again. To work around, change the filename and upload.

**To Reproduce**
1. Go to Categories
2. Click on pencil to edit a category that doesn't have images
3. Click on load image, and load something
4. Click in the browser window to dismiss the category editor
5. Re-open the category editor
6. Click on load image, and load the same image
7. Observe an empty image

**Expected behavior**
Expected the image to load

**Comment by DanielnetoDotCom** [comment]
I guess you must click in save to keep upload the image for real

**Comment by walt93** [comment]
Correct.

FWIW I plan to get up to speed on the code base and help fix some of these edge cases and smaller bugs that I am reporting.It is a big and complex project that you have built. ;)
