### ISSUE TITLE
Video encoding problem

### ISSUE THREAD

**Issue by SergejGrin** [WWBN/AVideo#5159]
I have a video encoding problem:
Updated site to version 11.0 and encoder to 3.8
Now, when you try to add a video, the file is uploaded to the server, but the encoding process does not start and does not go - it hangs. There is an error message in the logs. I looked at the plugin settings - everything is fine there. And I have not changed anything there before. What could be the problem and how to fix it?

<img width="1799" alt="2" src="https://user-images.githubusercontent.com/59236880/118399535-ee3b2780-b65d-11eb-83b9-fb9034c381f7.png">
<img width="1799" alt="3" src="https://user-images.githubusercontent.com/59236880/118399539-f2674500-b65d-11eb-8d54-d0c821461092.png">
<img width="965" alt="Снимок экрана 2021-05-16 в 15 56 28" src="https://user-images.githubusercontent.com/59236880/118399879-8a196300-b65f-11eb-9354-e674ffa52112.png">

**Comment by milehighkaraoke** [comment]
Check your encoder network 
![20210517_072847](https://user-images.githubusercontent.com/70327833/118496798-b1b10f80-b6e1-11eb-9d91-b99a60e4eec9.jpg)

**Comment by DanielnetoDotCom** [comment]
@SergejGrin check the encoder log.

also make sure you have the latest git pull

**Comment by SergejGrin** [comment]
Hello everyone and thank you for your help! I updated the streamer and encoder versions yesterday. Today I tried to update the encoder again, but it already has the latest version. (see screenshot) 
<img width="741" alt="Снимок экрана 2021-05-17 в 20 00 18" src="https://user-images.githubusercontent.com/59236880/118541088-9da4f680-b751-11eb-812b-5cf7343b7816.png">

Checked the settings as advised by **milehighkaraoke**. You can watch a video of the desktop. 
https://wakesoft.info/index.php/s/mE9srspJZiQTrEb
I attach the streamer and encoder logs. I will be very grateful for your help.
[avideo-stremer.log](https://github.com/WWBN/AVideo/files/6496176/avideo-stremer.log)
[avideo-encoder.log](https://github.com/WWBN/AVideo/files/6496178/avideo-encoder.log)

**Comment by DanielnetoDotCom** [comment]
From your log I can see the encode works fine and process your files

The only thing, (maybe is not a problem) was the non latin characteres in your title/filename

try to use only latin caracteres to see if it makes any difference

**Comment by SergejGrin** [comment]
Unfortunately, this did not solve the problem ... Watch the video
https://wakesoft.info/index.php/s/SaTpLW3PxrCFzrR

**Comment by DanielnetoDotCom** [comment]
I see, please do that.

delete your encoder log file. upload a file and check if it starts the encode process.

share the encoder log, it will make easier to detect what is the issue

**Comment by SergejGrin** [comment]
Here is the new log file
[avideo.log](https://github.com/WWBN/AVideo/files/6502815/avideo.log)

**Comment by DanielnetoDotCom** [comment]
Not sure what is the problem, I just tested it and it works fine on my side

**Comment by SergejGrin** [comment]
I still did not understand what the problem was, but ... the problem was solved by a complete reinstallation of the encoder. What did I do:
- deleted the old database;
- created a new database and a new user;
- deleted the entire encoder folder (upload);
- downloaded a new encoder package and started a new installation.
After that, the encoder started working. Thank you Daniel for the good and high-quality software. I think that such a solution might come in handy for someone who has a similar problem.
