### ISSUE TITLE
Need help with optimal ad settings

### ISSUE THREAD

**Issue by gosoaps** [WWBN/AVideo#5161]
**Describe the question**

I have a site where users can view and/or share videos. I currently use ExoClick to provide in-stream video ads, as well as banner ads around the site. Users do not have to create an account to view videos, but they do need an account to rate or comment on the videos or upload their own videos. Setting up an account is free, but if they want an ad-free site experience, it costs $4.99 a month. 

I am struggling with the optimal ad settings for the AVideo plugins and ExoClick account. The site is pretty new and there isn't a ton or traffic. I have about 120 users and about 5 of them pay for ad-free. I currently make about a $1 a month on ads. 

I want ads to not be so frequent that it discourages users from coming to the site, yet frequent enough to generate between $0.15 and $0.20 per day per site user. Is that reasonable? That would be $4.50 to $6.00 per month per user assuming they visited the site every day.

Can you or someone in this group who is more familiar with how this works help me with this? I will pay, of course. Any assistance you can provide would be much appreciated. Thank you.

Jack

**Comment by gosoaps** [comment]
I have averaged 1,368 impressions per day over the last 30 days. I realize I need to get this up to 10k-20k per day. I want to set this up AS IF I currently have 20k impressions per day.

**Comment by DanielnetoDotCom** [comment]
Hi, 

sorry, but what you are looking for is not clear to me.
