### ISSUE TITLE
cache dir not working

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#5162]
before I was using a symbolic link to the cache directory, not anymore.

The plugin gives an option to change the cache directory, but not working for me.
Also after clearing the cache, the settings got a reset to default cache dir ( videos/cache) .

Is there anyway to add this to the `configuration.php` file? The logs on another dir works fine.

Clearing question before hand. The directory has permissions , and ownership , log file works, only cache not working.

**Comment by DanielnetoDotCom** [comment]
Hi

some cache must be on a public directory (I mean can access using http protocol), for example, css, js, json, etc files

so the main location is on the videos/cache. I understand if you delete the cache folder it will be recreated as a folder, not a symbolic link

with this update, you may be able to use `$global['tmpDir']`, so it will use this location to create your cache folder, but you will still have the videos/cache folder for the files that must be on a public URL

**Comment by akhilleusuggo** [comment]
I still managed to keep symbolic link pointing to videos/cache. The only issue is the way the script clears the cache, it deletes the directory ( but it can not , gives error ). Works for me, just not as intended.

Could you explain what do you mean by :

> with this update, you may be able to use $global['tmpDir'], so it will use this location to create your cache folder, but you will still have the videos/cache folder for the files that must be on a public URL

If the files are still gonna be written to videos/cache and read from videos/cache, when what is the goal of changing the video's directory?

I don't mind mounting the extra drive ( for caching ) on `videos/cache/drive` , again , the only issue is how the script deletes the cache. It does delete the entire directory, and not the file inside the directory.

**Comment by DanielnetoDotCom** [comment]
Hi

the necessary public URL files will be saved on videos/cache/

the not necessary to be public will be saved on the predefined `$global['tmpDir']`

But I just sent an update that will not delete the cache folder anymore

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Thank you 👍
