### ISSUE TITLE
API calls

### ISSUE THREAD

**Issue by tbryantAE** [WWBN/AVideo#5164]
What API call is needed to get a list of your "Series" and "Collections" or "Playlists"?  You can do a GetPrograms but need to be able to call Series and get information along with what videos are in those Series or Collections.

**Comment by DanielnetoDotCom** [comment]
Did you try that

![image](https://user-images.githubusercontent.com/18009293/118686204-2cf5ec80-b7da-11eb-818f-65e26b78fea9.png)
