### ISSUE TITLE
Directory permission error

### ISSUE THREAD

**Issue by techiesces** [WWBN/AVideo#5168]
When I go into edit video title information I get this error.  I am logged in as admin and this is the admin uploaded video.

Sorry!
Directory /var/www/AVideo/objects/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777 

What should I do?

**Comment by techiesces** [comment]
Annnnnnndddd...... I just now did version updates and plugin updates and now the AVideo is not working... getting a 503 error now for the entire site. Apache2 seems to be running but cannot access video site any longer.

**Comment by techiesces** [comment]
ok back in business and running....  so back to original issue...

Sorry!
Directory /var/www/AVideo/objects/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777 

what should I do here?

**Comment by DanielnetoDotCom** [comment]
> ok back in business and running.... so back to original issue...
> 
> Sorry!
> Directory /var/www/AVideo/objects/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777
> 
> what should I do here?

`sudo chmod -R 777 /var/www/AVideo/objects/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer`

**Comment by techiesces** [comment]
I was worried that this would be too easy and there would be a security risk for some reason.

But thank you for the response.
