### ISSUE TITLE
[Request] Gallery plug-in, add sort section for All Channels

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5171]
**Is your feature request related to a problem? Please describe.**
I'd like use Channels as a way of organizing content, and it would be superlative if I could access my channels from the home page. 

**Describe the solution you'd like**
Similar functionality to SubscribedChannels, but, shows all channels.

**Describe alternatives you've considered**
I've tried the YPTFlix solution, it is not to my taste. I

![Screen Shot 2021-05-19 at 12 30 22 AM](https://user-images.githubusercontent.com/11711050/118773174-67db3d00-b839-11eb-9bd7-36956c0d876e.png)

**Comment by DanielnetoDotCom** [comment]
Sorry I do not understand, do you want to sort the subscribed channels?

**Comment by walt93** [comment]
No, in my use case, I'd like to display a list of all Channels on the home page (like the Netflix clone page does)

The same effect I would like is achieved by a logged in user subscribing to all channels, and enabling SubscribedChannels.

**Comment by DanielnetoDotCom** [comment]
Can you please screenshot how the Netflix clone does?

**Comment by walt93** [comment]
Everything below "Suggested" are channels, some even have the default hexadecimal name.

![Screen Shot 2021-05-21 at 2 25 46 PM](https://user-images.githubusercontent.com/11711050/119199758-819aa100-ba40-11eb-813a-dcdae232ea01.png)

Ideally, there would be a UI to control the order of channels, and a boolean to "Enable/Disable This Channel On Homepage".

**Comment by DanielnetoDotCom** [comment]
What about if you sort it?

![image](https://user-images.githubusercontent.com/18009293/119344181-bc355100-bc6d-11eb-89df-6c61720c9eb9.png)

**Comment by walt93** [comment]
Yes, this works.
