### ISSUE TITLE
[Request] Gallery plug-in, Sort Gallery Sections - would like to enable a subset of Categories.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5172]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when trying to organize 4,000 videos, audio files and PDFs in a meaningful way to present to the user. I'd like to use Categories as a way of slinging videos onto the home page. My site has >200 categories, I only want to view a subset of them.

**Describe the solution you'd like**
In the Sort Gallery Sections part of the Gallery plug-in, under Categories, it should have a hierarchy of categories with check boxes, and the ability to scroll.

**Describe alternatives you've considered**
In the Category editor, a "Display on Home page" should toggle the same database field as the check box in the Sort Gallery Sections list.

**Comment by DanielnetoDotCom** [comment]
do you mean choose what categories should appear on the main page?

**Comment by walt93** [comment]
Yes 💯
This would give me the ability to really dial in what appears on the home page.

**Comment by DanielnetoDotCom** [comment]
I will add this option for suggested categories on version 11.1

**Comment by walt93** [comment]
Updated to 11.1.  I see the new option on categories. Two issues.

#1 I have turned on "Suggested" for a few categories. When I enable Categories in "Sort Gallery Sections, I am still seeing all categories on the home page. 

#2 in the categories table view, there is a sort by "Suggested" but it is not sorting. 

![Screen Shot 2021-05-26 at 12 50 34 PM](https://user-images.githubusercontent.com/11711050/119722387-1b879280-be21-11eb-867b-499cc32c020b.png)
![Screen Shot 2021-05-26 at 12 50 27 PM](https://user-images.githubusercontent.com/11711050/119722391-1cb8bf80-be21-11eb-833f-1373203fa98c.png)

**Comment by DanielnetoDotCom** [comment]
1. make sure you enable the option on the plugin
![image](https://user-images.githubusercontent.com/18009293/119821125-9657b880-bec8-11eb-909b-06a73e8b2551.png)

2. I just sent a fix for the sort
