### ISSUE TITLE
Mobile app LIVE --> "This feature is not available on this device"

### ISSUE THREAD

**Issue by RememberForgottenHits** [WWBN/AVideo#5173]
The settings in the admin panel should be all ok. When I click "Go Live" on my mobile I get the answer "This feature is not available on this device"

All updates to the mobile app and streamer website have been made. I've tried on two different mobiles and tablets. All android devices.

Live settings also cannot be saved. Are there any restrictions somewhere or where should I start to solve the problem.

**Comment by DanielnetoDotCom** [comment]
Please make sure you download those apps:

iOS: https://itunes.apple.com/us/app/youphptube/id1337322357
Android: https://play.google.com/store/apps/details?id=mobile.youphptube.com

I guess you have an old non official version

**Comment by DanielnetoDotCom** [comment]
I will submit a new version soon

**Comment by milehighkaraoke** [comment]
Why does the mobile ap make you create a meet to go live. Should it not just connect to the phones camera and microphone broadcasting the live feed to the users account
![Screenshot_20210521-090654_AVideo Platform](https://user-images.githubusercontent.com/70327833/119159135-32d71200-ba14-11eb-81c9-a5fe300496ed.jpg)
![Screenshot_20210521-090639_AVideo Platform](https://user-images.githubusercontent.com/70327833/119159181-3bc7e380-ba14-11eb-96bd-e9d1f067cb66.jpg)

**Comment by RememberForgottenHits** [comment]
> I will submit a new version soon

Greetings, is there any news ;)
