### ISSUE TITLE
Avideo app time counter 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#5175]
Can you add a time counter to app player screen, both portrait and landscape?

**Comment by DanielnetoDotCom** [comment]
sorry, what exactly do you mean?

**Comment by fakeologist** [comment]
![Screenshot_20210520-120226_bitslide.jpg](https://user-images.githubusercontent.com/66537018/119011696-4d04e780-b963-11eb-9292-65efe1390d17.jpg) check bottom left of this bitchute screen

**Comment by DanielnetoDotCom** [comment]
I guess the progress depends on the player theme you are using.

try to change it here 
![image](https://user-images.githubusercontent.com/18009293/119146298-ddedc880-ba20-11eb-9d4e-348b5c8136e6.png)

**Comment by fakeologist** [comment]
I can't find that on my site.
