### ISSUE TITLE
Cannot login to Encoder after updating

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#5179]
Hi 
I cannot login to the encoder after updating to 11.0 Not sure what I am doing wrong.

I tried a git pull in the encoder folder, but still no joy..

Please advise.
Thanks

**Comment by DanielnetoDotCom** [comment]
check the encoder and streamer log at the login momment

**Comment by kollossus55** [comment]
Tried updating Encoder - saya it already upto date. 
Which directory does the streamer reside ? 
Do I do a git pull in that directory ?  Wil lcheck logs.
Regards

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by kollossus55** [comment]
Hi

I hvae got these errors as below.


[21-May-2021 19:58:34 Europe/London] PHP Warning:  opendir(path/to/my/streamer/site/videos/hd/): failed to open dir: No such file or directory in path/to/my/streamer/site/objects/functions.php on line 5570



[21-May-2021 19:53:23 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function _error_log() in path/to/my/streamer/site/objects/include_config.php:44

Does this mean Streamer problems ?

Whats the best thing to do and istructions.

Thanks


________________________________

**Comment by DanielnetoDotCom** [comment]
Seems to me you did not update it correctly 

make sure you always update it with `git pull`

**Comment by kollossus55** [comment]
Hi
Is possible for you to logon and check..ive done git pulls already.. not sure if i have done something else wrong.. i will buy some plugins as donation..

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by DanielnetoDotCom** [comment]
Hi, I probably can fix it for 1-hour support.

**Comment by kollossus55** [comment]
Sure..let me know what u require...

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by DanielnetoDotCom** [comment]
Please email me at developer@youphptube.com
