### ISSUE TITLE
Admin Page and Settings Page issue

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5181]
Whenever I want to access the /admin url and view the general_Settings page, it will take a long time to open, idk why. Also on the statistics page I am still missing information about videos, this has been there for quite some time now but haven't had a chance yet to tackle. Here is s a screen shot of the page:

![Screen Shot 5781-09-09 at 18 30 40](https://user-images.githubusercontent.com/58882903/119007623-11d1db00-b99a-11eb-8f2c-9beb9853abd4.jpg)
![Screen Shot 5781-09-09 at 18 31 32](https://user-images.githubusercontent.com/58882903/119007652-1ac2ac80-b99a-11eb-851f-baed581c4aa4.jpg)

**Comment by guymass** [comment]
Still waiting on replay to this issue we have. Every time I want to open the Control Panel it take about 20 seconds to load and when it loads, it is missing those three areas. Maybe you can give me some pointers into what to look, maybe its a missing apache module idk. I would like to see it resolved and working fast and good and it doesn't matter how many times we update/upgrade this issue still remains and passes on to the next version.

**Comment by DanielnetoDotCom** [comment]
the control panel still need to be reviewed , I have no solution for it now

**Comment by guymass** [comment]
OK thanks, we will be waiting.
