### ISSUE TITLE
Urgeant Bug on Mobile App and LDAP Login!!!

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5182]
We have switched to using out LDAP server to authenticate our users however we didn't take into consideration their usage of the Mobile APP. Our users claim they cannot login with the APP anymore once we switched off the native sign-in.

How do we overcome this? Here is a screen shot from one of our users:
![photo_2021-05-20 19 09 18](https://user-images.githubusercontent.com/58882903/119012766-00d79880-b99f-11eb-9193-ef55fefb65b4.jpeg)

Shows problem with capcha also not displaying properly on mobile.

**Comment by guymass** [comment]
OK I think the problem is that the user first needs to access through a browser before they can access the site through the mobile app. We will keep checking, however I think maybe some adjustments to the mobile app should take in consideration the LDAP login without any native signup or signin.

**Comment by DanielnetoDotCom** [comment]
I guess I do not have LDAP support on mobile yet, I have never tested it.
