### ISSUE TITLE
I'd like the ability to control the "published date" so I can have total control of the "Recently added" list

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5186]
**Is your feature request related to a problem? Please describe.**
My site has news/current events, and "other things". When I am uploading "other things", i.e. things that are not current events, I do not want them in "Recently added"

**Describe the solution you'd like**
Something like a "Published date" which is initially set to the "Created date", but, is editable.

**Describe alternatives you've considered**
This seems the easiest way to achieve it using the existing architecture, I could come up with other ideas but they increase in complexity.

**Comment by DanielnetoDotCom** [comment]
So do you mean to allow you to edit the created field on the database?

**Comment by walt93** [comment]
Yes. This would be one way to implement it.

**Comment by TLCReuver** [comment]
This would be a great feature for me because i have to modify it in phpMyAdmin (Running an archive back to  the year 1904)

**Comment by JeanDavis91** [comment]
Hello

Yes I find this remark very interesting especially for family videos where we could put the date of the video
