### ISSUE TITLE
Upload MP4 Bulk without Encoding

### ISSUE THREAD

**Issue by DrDoug88** [WWBN/AVideo#5188]
Is there a way to upload videos in bulk from a local directory without the encoding step? If I embed a link to a video on an NGINX server on the same host (I am using Apache for the main AVideo webserver, and NGINX as the streaming server), then the videos work great, there is no need for additional encoding. However, if I upload them individually and encode them, then the quality drops significantly and it takes a very long time to encode. I am having problems with the bulk utility as well, and I will submit a bug report accordingly (the utility only uploads about 4.5 MB of a 600 MB video)

**Comment by DanielnetoDotCom** [comment]
I have built a tool in the past, maybe you can edit it and do what you need

https://github.com/WWBN/AVideo/blob/master/install/recoverFilesToVideos.php

this will scan the videos folder and create the videos on the database

**Comment by DrDoug88** [comment]
I have never written a single line of PHP. I'll probably have to force myself to take a few days aside to learn the language in the near future. But I did take a look at the database, and the schema is straightforward, so I know what I am going to do for now to get the videos imported. Then its just a little bit of scripting to create the directories and set the thumbnails. Thank you for the code though. I will likely loop back around to this in the future. 

On a slightly related note, I like the fact that the number of views can be set manually. However, it would be great if the likes/dislikes could be manipulated as well. We are moving everything out of YouTube, due to the censorship and dishonest data manipulation. It would be nice if we could replicate the metadata as close as possible - perhaps a modifylikes and modifydislikes columns in the videos table which would add to the values calculated from the likes table. Should I make a separate feature request for this?

Anyhow, thanks for responding promptly and accurately. Your hard work on this project is much appreciated.
