### ISSUE TITLE
cache

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#5189]
Witch update made the cache to be automatically deleted ? Cache doesn't follow anymore the cache time, it's deleted every 10mn. I  believe it's the commit you made for apps to delete cache every 600s.

https://github.com/WWBN/AVideo/commit/3ed31a7b03400fb4ca3d648440ee6c6d2495ba07
https://github.com/WWBN/AVideo/commit/4110fdb69907d948bfa8da567f924f8c7f565191

**Comment by DanielnetoDotCom** [comment]
I am not sure, but the cache can be deleted in multiple situations. but the latest update the cache folder is not deleted anymore (only files), yous symlink should work fine now.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Not talking about symlinks, I'm talking about cache files being deleted automatically, not manually ( every 10mn or so )

**Comment by DanielnetoDotCom** [comment]
I am not sure, if is exactly 10 min it should be something in your crontab

**Comment by akhilleusuggo** [comment]
Ok, closing the issue until further debugging.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Ok, I may have a hint. Everytime a bot visits sitemap.xml ( and the proccess of generating the sitemap starts ) the cache get deleted. Maybe also when checking robot.txt but I'm not sure.
