### ISSUE TITLE
Is AVideo mainly a P2P based system?

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5190]
Just out of concern for security issues, a friend sent me this video lecture regarding the security risks in using a P@P based system and I was wondering if AVideo might be falling under this category and might be easily compromised by the issues presented in this informative lecture. I will leave a link here in hope to get some information about this matter in hopes that is will contribute to a safer and more secure system.

https://www.youtube.com/watch?v=ZZHPN6WNEAE&t=27s

**Comment by SubjectXXX** [comment]
P2P means that many peers (normal users) share data with many users (also normal users). Example would be torrent.

AVideo is in no way P2P, since its centralized.
