### ISSUE TITLE
is it posible to have GIF Support for the chat 

### ISSUE THREAD

**Issue by antuk21** [WWBN/AVideo#5191]
is it possible to have GIF Support for the chat like any other platform

**Comment by antuk21** [comment]
https://user-images.githubusercontent.com/74247098/119142811-ccb3b480-ba3e-11eb-90c3-d27e721c3086.mp4

something like this

**Comment by DanielnetoDotCom** [comment]
not yet, but maybe in the future I will allow you to upload your own gifs

**Comment by antuk21** [comment]
ok thank you

**Comment by JoshWho** [comment]
I have a high demand for that as well with my users.
