### ISSUE TITLE
v 11.1 - Live not Play

### ISSUE THREAD

**Issue by peterflitz** [WWBN/AVideo#5192]
Update to 11.1

Live not play, over Meet also over OBS.

**Comment by DanielnetoDotCom** [comment]
Hi, please check the logs

**Comment by DanielnetoDotCom** [comment]
I found something, i will send an update soon

**Comment by milehighkaraoke** [comment]
What's going on with this new update?
![20210521_103211](https://user-images.githubusercontent.com/70327833/119170016-e85b9280-ba1f-11eb-826d-89cbe539cf5b.jpg)

**Comment by DanielnetoDotCom** [comment]
Update your SendRecordedToEncoder to version 5.0

**Comment by milehighkaraoke** [comment]
Thank you @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
This update should avoid this error, but the plugin update still needed

**Comment by peterflitz** [comment]
Thanks Daniel.
Live funktionieren wieder, aber Meet ist fehler:
https://github.com/WWBN/AVideo/issues/5195
