### ISSUE TITLE
NO LINK on email - Verify Your E-mail[SOLVED]

### ISSUE THREAD

**Issue by RememberForgottenHits** [WWBN/AVideo#5193]
After registering a new user, there is no link to click to confirm the email address

E-MAIL CONTENT
![no-link](https://user-images.githubusercontent.com/34457020/119182004-0dc9ba00-ba7b-11eb-8ac0-806b50933c83.png)

Are the settings incorrect?

![seadistus-nolink](https://user-images.githubusercontent.com/34457020/119182124-32be2d00-ba7b-11eb-9103-cadf7ebd5ffd.png)

**Comment by DanielnetoDotCom** [comment]
Can you please copy and paste the original email here? I mean the email source code?

**Comment by RememberForgottenHits** [comment]
HI, you mean this source code?

`Delivered-To: pumplakollid@gmail.com
Received: by 2002:ad4:54aa:0:0:0:0:0 with SMTP id r10csp3122204qvy;
        Fri, 21 May 2021 11:01:00 -0700 (PDT)
X-Google-Smtp-Source: ABdhPJzqBL95Mm92EA4MehBzXzOYmSCzVucsYs60RoHF1WMGc/IRgPSTxh2+v7oMIYcj51Gl0LHX
X-Received: by 2002:aa7:c3d6:: with SMTP id l22mr12526559edr.21.1621620060811;
        Fri, 21 May 2021 11:01:00 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1621620060; cv=none;
        d=google.com; s=arc-20160816;
        b=W2mcehJsIYehTxqEet981T3R77ZKZIt1D1FuwJDRnW/ols2rk+fC6DTBtAzB3kPEKM
         VTWPkBFt3ZMXIHO5jADPQaheczE9mF8U/cSZ5OSWtsolBH9Pg4K72sVCuye+HaJfvOxY
         DWr+GUvLyVlxstHdMnokx5rwAMHFI2G1eKgWIKhnb/IQFQ3fR4TsCilWvTWWseXrwL/Q
         SXuTN3y1SEh0JUz8uDXffJrYcZR1YQyXjbyRPTp+ElQi731R/UIVMv/zTR6bIIJ06lLc
         kZ4nFRmIGefBqrdOJ8T12fRjOEk16DGm46LQSdnge08yDD2RhicgAsGgooV9n+8mmh3A
         681g==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=content-transfer-encoding:mime-version:message-id:subject:from:to
         :date;
        bh=TtM92q66sKerW6mwjRS+wASjn3QwlJPae8NQgCcVKiI=;
        b=DLVne+vwxeUov+drIUWADMihsyfwL1FW18v7K/6qNGuNVn59pVPOmGYUcn7JZV48/T
         nVit65/bdmhNbxj80vOoJFjJRlG2K4lS6oZ6sVHrTCzWnGU5dhQagUSS3rzTw7T4LxK0
         Y6eZly9HiA1PQGKCJDYUm3BEHK4/QuwPfzZJrDuUCjkW7r2LPPTmc9Cz7yiSf0QhGSTX
         OvhkokvaWSWQsHZDu8ga3Rkpc+wiA5jxDVy4xkqLSLvkvPdH1NtfDnoY6gOmE9vD8db+
         XvyX1cSrfWBJxfj6erWzdT7hB95RyBqsV0aQWAKkrSZL6XVEgCiEoiwKWtVOcK0Q6Io7
         Zydw==
ARC-Authentication-Results: i=1; mx.google.com;
       spf=softfail (google.com: domain of transitioning iffinland@pm.me does not designate 161.97.135.98 as permitted sender) smtp.mailfrom=iffinland@pm.me;
       dmarc=fail (p=QUARANTINE sp=QUARANTINE dis=QUARANTINE) header.from=pm.me
Return-Path: <iffinland@pm.me>
Received: from mustream.info (mustream.info. [161.97.135.98])
        by mx.google.com with ESMTPS id dn21si3787522edb.433.2021.05.21.11.01.00
        for <pumplakollid@gmail.com>
        (version=TLS1_3 cipher=TLS_AES_256_GCM_SHA384 bits=256/256);
        Fri, 21 May 2021 11:01:00 -0700 (PDT)
Received-SPF: softfail (google.com: domain of transitioning iffinland@pm.me does not designate 161.97.135.98 as permitted sender) client-ip=161.97.135.98;
Authentication-Results: mx.google.com;
       spf=softfail (google.com: domain of transitioning iffinland@pm.me does not designate 161.97.135.98 as permitted sender) smtp.mailfrom=iffinland@pm.me;
       dmarc=fail (p=QUARANTINE sp=QUARANTINE dis=QUARANTINE) header.from=pm.me
Received: from mustream.info (localhost [127.0.0.1]) by mustream.info (8.15.2/8.15.2/Debian-18) with ESMTP id 14LI10GW684593 for <pumplakollid@gmail.com>; Fri, 21 May 2021 21:01:00 +0300
Received: (from www-data@localhost) by mustream.info (8.15.2/8.15.2/Submit) id 14LI0xJJ684592; Fri, 21 May 2021 21:00:59 +0300
X-Authentication-Warning: mustream.info: www-data set sender to iffinland@pm.me using -f
Date: Fri, 21 May 2021 21:00:59 +0300
To: pumplakollid@gmail.com
From: IFFI-TUBE <iffinland@pm.me>
Subject: Please Verify Your E-mail IFFI-TUBE
Message-ID: <mzU19ObVE5gvH4mBtBKoAm4Kyqi5f6GWignXvI1Uho@mustream.info>
X-Mailer: PHPMailer 6.4.1 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="b1_mzU19ObVE5gvH4mBtBKoAm4Kyqi5f6GWignXvI1Uho"
Content-Transfer-Encoding: 8bit

--b1_mzU19ObVE5gvH4mBtBKoAm4Kyqi5f6GWignXvI1Uho
Content-Type: text/plain; charset=us-ascii

Hi Just a quick note to say a big welcome and an even bigger thank you for registeringCheers, IFFI-TUBE Team.You are just one click away from starting your journey with IFFI-TUBE!All you need to do is to verify your e-mail by clicking the link below NO LINK Verify

--b1_mzU19ObVE5gvH4mBtBKoAm4Kyqi5f6GWignXvI1Uho
Content-Type: text/html; charset=us-ascii

Hi <br><br>Just a quick note to say a big welcome and an even bigger thank you for registering<br><br>Cheers, IFFI-TUBE Team.<br><br>You are just one click away from starting your journey with IFFI-TUBE!<br><br>All you need to do is to verify your e-mail by clicking the link below NO LINK<br><br> <a href='https://mustream.info/objects/userVerifyEmail.php?code=eyJ1c2Vyc19pZCI6Niwic2FsdCI6ImFjNjlmN2ViZDZlOWViMmI3MjVmYzkzODg1MDAwNGUwODMyNTE4YzlkMDNmMGE4OWIyYjA2MTdhMjMyMTI0YmEiLCJyZWNvdmVyUGFzcyI6IlptWmtNa3N5V2pkNWNHYzBSME5ZVjFoWk5WaEJhVFpwYUVNMWVYVmFTMkZDTlZOWlNXNUNWemw0TkQwPSJ9'>Verify</a>


--b1_mzU19ObVE5gvH4mBtBKoAm4Kyqi5f6GWignXvI1Uho--`

If i'm copy and paste this link to browser. It works fine and email veryfed 
`https://mustream.info/objects/userVerifyEmail.php?code=eyJ1c2Vyc19pZCI6Niwic2FsdCI6ImFjNjlmN2ViZDZlOWViMmI3MjVmYzkzODg1MDAwNGUwODMyNTE4YzlkMDNmMGE4OWIyYjA2MTdhMjMyMTI0YmEiLCJyZWNvdmVyUGFzcyI6IlptWmtNa3N5V2pkNWNHYzBSME5ZVjFoWk5WaEJhVFpwYUVNMWVYVmFTMkZDTlZOWlNXNUNWemw0TkQwPSJ9`

**Comment by DanielnetoDotCom** [comment]
Hi, is almost that, but I can see in your source the link is present.

I guess your email reader do not support HTML

**Comment by RememberForgottenHits** [comment]
Hi man, i found a problem! I use ProtonMail and there it is possible to create PM.ME ending email addresses. My streamer's website was configured with a PM.ME-ending email address for general notifications. 

For some reason all the emails went to the spam folder and that's why they probably didn't see the active link. 

![careful](https://user-images.githubusercontent.com/34457020/119853800-2e7d8e00-bf19-11eb-820b-d62417a0551f.png)

I changed this email address and now everything works exactly as it should. ;)

Thank you for thinking along and trying to help me!! (Y)
