### ISSUE TITLE
Meet, wrong Authentification failed

### ISSUE THREAD

**Issue by peterflitz** [WWBN/AVideo#5195]
when I start a meet, I come to in the meet from this website:
https://live.goairrit.com/

And Notifikation:
Authentification failed

**Comment by DanielnetoDotCom** [comment]
what meet server are you using?

**Comment by peterflitz** [comment]
I have tested it further, all possible providers of the meet servers are displayed ...
The logo of the respective website is also displayed in the meet.

- >> online (Europe1)

**Comment by DanielnetoDotCom** [comment]
The meet error was on the meet server side.

the NA server was fine the problem was on EU one

**Comment by peterflitz** [comment]
yees, i see, sorry.

It is a coincidence that an update falls precisely on the failure of the eu server :-)
