### ISSUE TITLE
Can I force users to sign up and subscribe at the same time?

### ISSUE THREAD

**Issue by tbryantAE** [WWBN/AVideo#5196]
I have a customer that wants to force their users to sign up and subscribe to the portal at the same time.  I have tried to look at everything on system to see how to do that but did not see how.  Does anyone know how to configure the system to do that?

Thanks in advance.

**Comment by milehighkaraoke** [comment]
Toggle, the user must be logged in, under settings

**Comment by tbryantAE** [comment]
that forces them to sign up or sing in but not subscribe to portal as well.

**Comment by DanielnetoDotCom** [comment]
There is no such option
