### ISSUE TITLE
[Question] The debugger shows active web sockets. How can I see active *streaming* connections?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5197]
**Describe the question**
Looking at the LiveUsers, it appears to be showing users that have an open browser session.

![Screen Shot 2021-05-21 at 10 30 52 PM](https://user-images.githubusercontent.com/11711050/119215724-6c476600-ba84-11eb-84d4-0399271d3ac2.png)

Is it possible to know how many users are *streaming* concurrently?

**Comment by DanielnetoDotCom** [comment]
Only in the notification menu
