### ISSUE TITLE
Categories not showing first page

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#5202]
Like the title stated, the categories on Gallery not showing on the first page ( `view/index.php` ) after update.
Also, it does fetch tags when having tags disabled.

`Warning: Slow process detected [video::getAllVideos foreach] On  Line 1198 takes 0.6815 seconds to complete, Limit (0.48). /var/www/html/AVideo/view/index.php SCRIPT_NAME: view/index.php`

**Comment by TLCReuver** [comment]
Can confirm these two issues.

**Comment by DanielnetoDotCom** [comment]
> Like the title stated, the categories on Gallery not showing on the first page ( `view/index.php` ) after update.
> Also, it does fetch tags when having tags disabled.

I do not understand the issue

> `Warning: Slow process detected [video::getAllVideos foreach] On Line 1198 takes 0.6815 seconds to complete, Limit (0.48). /var/www/html/AVideo/view/index.php SCRIPT_NAME: view/index.php`

This is not an issue

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 
1-Categories not showing on first page. ( plugin gallery not working as expected ) 
2- `[video::getAllVideos foreach] ` it is an issue if you have it disabled.

**Comment by JeanDavis91** [comment]
Good evening

Enable this and all should work now

![categories](https://user-images.githubusercontent.com/61474191/119415711-72427e80-bcf2-11eb-9df2-e3cec47ec131.jpg)

Jfr

**Comment by antuk21** [comment]
ok that work for me :) thanks

**Comment by akhilleusuggo** [comment]
So the gallery options are now useless ?

**Comment by DanielnetoDotCom** [comment]
> So the gallery options are now useless ?

the Gallery property CategoriesShowOnlySuggested was missing.

I just sent a fix for it.
