### ISSUE TITLE
In the latest version 11.1, videos are not played!

### ISSUE THREAD

**Issue by Proton-people** [WWBN/AVideo#5203]
Version 11.0 works fine and on version 11.1 nothing happens when the Play button is pressed. Maybe something new has appeared in this version and I need to enable it? Please tell me what could be the problem?
![bandicam 2021-05-23 10-32-19-291](https://user-images.githubusercontent.com/48072457/119253724-55426a00-bb91-11eb-9b5c-642155963342.jpg)

**Comment by DanielnetoDotCom** [comment]
The provided log error looks like a bad installation not an bad update

**Comment by Proton-people** [comment]
> Предоставленная ошибка журнала выглядит как плохая установка, а не плохое обновление

I installed it several times and the result is the same. And when I put the site into maintenance mode, these errors appear in the log. If you turn off the service mode, then the problem remains - videos are not played.

**Comment by Proton-people** [comment]
> The provided log error looks like a bad installation not an bad update

I will try reinstalling again and report the results.

**Comment by Proton-people** [comment]
> The provided log error looks like a bad installation not an bad update

I reinstalled AVideo and the problem persists - videos won't play. Now I have other errors in the log.
![bandicam 2021-05-23 12-43-30-654](https://user-images.githubusercontent.com/48072457/119257269-4369c280-bba3-11eb-8d4a-1aec88667d8e.jpg)
![bandicam 2021-05-23 12-43-39-963](https://user-images.githubusercontent.com/48072457/119257273-482e7680-bba3-11eb-8cba-e8079bc7514d.jpg)

**Comment by DanielnetoDotCom** [comment]
Looks like you did not drop the old database on the new installation.

**Comment by Proton-people** [comment]
> Похоже, вы не сбросили старую базу данных при новой установке.

I removed the old base before a fresh install. I have been using your wonderful product for 2 years now and this is my first time.

**Comment by Proton-people** [comment]
> Похоже, вы не сбросили старую базу данных при новой установке.
I removed the old base before a fresh install. I have been using your wonderful product for 2 years now and this is the first time I have such an error.

**Comment by DanielnetoDotCom** [comment]
I do not understand.
Is this a new installation?

there is anything o the Apache or avideo  log?

**Comment by Proton-people** [comment]
> Я не понимаю.
> Это новая установка?
> 
> есть что-нибудь в журнале Apache или avideo?
This is a new installation.
[golosovanie.online.error.log](https://github.com/WWBN/AVideo/files/6528092/golosovanie.online.error.log)
[error.log](https://github.com/WWBN/AVideo/files/6528093/error.log)

**Comment by DanielnetoDotCom** [comment]
For me still looks like you are not making the installation correctly and you still not answer me if this is a new installation. 

Check if this file exists `/var/www/html/AVideo/videos/configuration.php`

1. if it does I have no idea what is the problem.

2. if it does not, drop the database and install it again. make sure the folder `/var/www/html/AVideo/videos/` exists and have the right permission.

**Comment by Proton-people** [comment]
> Мне все еще кажется, что вы делаете установку неправильно, и вы все еще не отвечаете мне, если это новая установка.
> 
> Проверьте, существует ли этот файл `/var/www/html/AVideo/videos/configuration.php`
> 
> 1. если это так, я понятия не имею, в чем проблема.
> 2. в противном случае отбросьте базу данных и установите ее снова. убедитесь, что папка `/var/www/html/AVideo/videos/`существует и у нее есть необходимые разрешения.

This is a new installation. I do the installation as follows: cd / var / www / html - next-sudo git clone https://github.com/WWBN/AVideo.git - next - sudo chown www-data: www-data / var / www / html / AVideo / -R Daniel here is the link: https://golosovanie.online/video/1/123 Try to play the video. You may be familiar with a similar problem.
![bandicam 2021-05-23 15-41-55-343](https://user-images.githubusercontent.com/48072457/119262974-ee867600-bbbb-11eb-8fbf-aeccfcc03940.jpg)
![bandicam 2021-05-23 15-42-34-418](https://user-images.githubusercontent.com/48072457/119262977-f34b2a00-bbbb-11eb-93e0-2973d264dd4c.jpg)

**Comment by DanielnetoDotCom** [comment]
The last error I can see in your log file is this

`PHP Fatal error:  require_once(): Failed opening required '/var/www/html/AVideo/upload/view/../videos/configuration.php'`

I assumed your request never reached the server, or I have no idea what you are missing as long as this looks like an installation error.
