### ISSUE TITLE
Playlist/Series starts on first item even if playOnSelect is disabled 

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#5204]
If you create a playlist and make it a series i get an object which can have a description and PPV and all these things.

But PPV doesnt work and the description is shown nowhere as the first object from the playlist is starting intermediately after clicking on the playlist...

**Comment by morbificagent** [comment]
Btw "playOnSelect" in the plugin is disabled... But looks like its not working

**Comment by DanielnetoDotCom** [comment]
Do you mean PPV is not working on the playlists?

**Comment by morbificagent** [comment]
Right, the button for ppv is there when i make it a series but it isnt working if configured.
It only plays the first track of the playlist.

And disabling "playonselect" doesnt work too...

You can try it on your demo site.

**Comment by DanielnetoDotCom** [comment]
On the playlist you should add each video from the playlist on PPV, if you want to charge a whole playlist in a single PPV you must use user groups for it.

![image](https://user-images.githubusercontent.com/18009293/119504714-9d54be80-bd42-11eb-956d-fe2e59f75c50.png)

**Comment by morbificagent** [comment]
OK, Thanks Daniel.

Could you take a look why disabling "playOnSelect" doesnt work?
