### ISSUE TITLE
Roku instructions

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5205]
Is there a way and if so how do I broadcast my site to Roku

**Comment by techiesces** [comment]
https://github.com/WWBN/AVideo/issues/4128

**Comment by milehighkaraoke** [comment]
@techiesces  Ok i looked over that and now my question is. How Do i add my mrss url in my roku account. I logged in via the link on 4128 but was brought to my dashboard. where do i go from there do i enter url instead of a channel code under add a channel? Sorry, Im lost lol
