### ISSUE TITLE
I Can not update version

### ISSUE THREAD

**Issue by calros** [WWBN/AVideo#5206]
"File not found" error occur when I click "update version"
Please help me 
![スクリーンショット (21)_LI](https://user-images.githubusercontent.com/84589906/119300187-4e078300-bc9b-11eb-913b-1e1153277d04.jpg)
![スクリーンショット (20)](https://user-images.githubusercontent.com/84589906/119300202-5495fa80-bc9b-11eb-8e08-3f013235391b.png)

**Comment by kamapapa** [comment]
//Server info//
 Ubuntu version: 18.04.5 LTS (Bionic Beaver)
 nginx version: 1.14.0
 PHP version: 7.2.24
 mysql  Ver 15.1 Distrib 10.1.48-MariaDB,

**Comment by milehighkaraoke** [comment]
you have to do a sudu git pull from your site folder and your encoder folder before it will show on your site as update available

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by kamapapa** [comment]
Thank you for advising me.
I tried both ways(1-Git Pull & 2- Download and Upload files) , but "File not found" is displayed when I click "update version" button.
I don't know why, directry "update" does not exist.

I executed the below command:

# 1- go to your AVideo dir and type git pull
cd /var/www/AVideo
sudo git pull

Then click button "update version"
Result: "File not found."
 
# 2- Download and Upload files)
scp -i web-server.pem -r AVideo-master.zip ubuntu@12.34.56.78:~/
cp AVideo-master.zip /var/www/AVideo
sudo unzip AVideo-master.zip
sudo systemctl reload php7.2-fpm nginx

Then click button "update version"
Result: "File not found."

**Comment by kamapapa** [comment]
ubuntu@ip-172-31-39-21:/var/www/AVideo$ sudo git pull
Already up to date.
ubuntu@ip-172-31-39-21:/var/www/AVideo$ cd upload/
ubuntu@ip-172-31-39-21:/var/www/AVideo/upload$
ubuntu@ip-172-31-39-21:/var/www/AVideo/upload$ sudo git pull
Already up to date.

**Comment by kamapapa** [comment]
I did Rollback the update but result was same - "File not found".

MariaDB [AVideo]> UPDATE configurations SET version = '6.5' WHERE id = 1;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

MariaDB [AVideoEncoder]> UPDATE configurations SET version = '6.5' WHERE id = 1;
Query OK, 1 row affected (0.01 sec)
Rows matched: 1  Changed: 1  Warnings: 0

**Comment by kamapapa** [comment]
![スクリーンショット (22)](https://user-images.githubusercontent.com/84589906/119454527-95f9d900-bd73-11eb-85ca-9f74deb0457d.png)

**Comment by DanielnetoDotCom** [comment]
you should not download/upload the files, you MUST use git pull.

**Comment by kamapapa** [comment]
I used git pull as below. What should I do next? Pls advise me. Sorry for the rudimentary question.


ubuntu@ip-172-31-39-21:/var/www/AVideo$ sudo git pull
remote: Enumerating objects: 132, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 78 (delta 64), reused 59 (delta 46), pack-reused 0
Unpacking objects: 100% (78/78), done.
From https://github.com/WWBN/AVideo
   a32c577fb..4b40f98a5  master     -> origin/master
Updating a32c577fb..4b40f98a5
Fast-forward
 objects/Object.php                             | 22 +++++++++++++++++++++-
 objects/video.php                              |  2 +-
 plugin/Gallery/view/modeGalleryCategory.php    | 10 ++++++++--
 plugin/Live/Live.php                           | 45 +++++++++++++++++++++++++++++++++++++++++++++
 plugin/Live/Objects/LiveTransmitionHistory.php | 18 ++----------------
 plugin/Live/indexCol1.php                      |  2 +-
 plugin/Live/install/nginx.conf                 |  2 +-
 plugin/Live/tabs/tabStreamKey.php              |  7 +++----
 plugin/Meet/Meet.php                           |  4 ++--
 plugin/Meet/saveMeet.json.php                  |  2 +-
 plugin/StripeYPT/build.php                     |  2 +-
 plugin/StripeYPT/ipn.php                       |  2 +-
 plugin/StripeYPT/lib/Webhook.php               |  2 +-
 plugin/WWBN/page/info.php                      | 10 +++++-----
 plugin/WWBN/page/wwbn_signup.php               |  2 +-
 view/css/custom/netflix.css                    | 10 +++++++++-
 16 files changed, 103 insertions(+), 39 deletions(-)
ubuntu@ip-172-31-39-21:/var/www/AVideo$ cd upload/
ubuntu@ip-172-31-39-21:/var/www/AVideo/upload$
ubuntu@ip-172-31-39-21:/var/www/AVideo/upload$ sudo git pull
Already up to date.

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by JeanDavis91** [comment]
Hello

Looks like the owner of the Avideo directory doesn't have the right one !!

see you soon

**Comment by milehighkaraoke** [comment]
to update with Git pull

**Comment by kamapapa** [comment]
I did clean installation on Ubuntu 20.04(LEMP Stack)

I tried "sudo git pull" in the encoder/streamer folder, but it say "Already up to date".

and also "File not found" is displayed when click "update version" on the drop-down menu

----------
ubuntu@ip-172-31-43-221:/var/www/AVideo$ sudo git pull
Already up to date.
ubuntu@ip-172-31-43-221:/var/www/AVideo$ cd upload/
ubuntu@ip-172-31-43-221:/var/www/AVideo/upload$ sudo git pull
Already up to date.

**Comment by DanielnetoDotCom** [comment]
probably you have a misconfiguration on the mod rewrite

**Comment by kamapapa** [comment]
![updatepage](https://user-images.githubusercontent.com/84589906/119910927-38dc6e00-bf93-11eb-89f0-cc109c546364.png)

I installed AVideo in fresh Ubuntu 20.04 server(LAMP stack) and it worked fine(update version page was displayed normally)
Thanks, calros
