### ISSUE TITLE
Search no longer works

### ISSUE THREAD

**Issue by JeanDavis91** [WWBN/AVideo#5209]
Good evening

Upgrade on version v11.1 it went well by reconfigured the categories (suggested new line) there is only one problem the search no longer works white screen 

The search is only done in DateAdded, MostWatched, MostPopular, SortByName but when there are only categories in index page there is no search found 

![fast](https://user-images.githubusercontent.com/61474191/119386604-119e4c00-bcc8-11eb-95ff-1f41571c4fb1.jpg)

thank you for your work

**Comment by DanielnetoDotCom** [comment]
Please try this update, also the parameter CategoriesShowOnlySuggested should work now.

**Comment by JeanDavis91** [comment]
Good evening

No, this does not work for the blank page search.
Please note that I only have the categories on the index if I add
Suggested or Trending or DateAdded or MostWatched or MostPopular or SortByName the search restarts 

I noticed that this does not work when there are only categories in index page

my website 
https://pnt-jfr.synology.me/avideo11/

Thanks for your help

**Comment by DanielnetoDotCom** [comment]
can you reproduce it on demo site?

**Comment by JeanDavis91** [comment]
Hello

Here I have just tested on your demo site and there is this problem on the demo site it is impossible to do a search when there are only categories in index as at the moment

I am working on a Linux Ubuntu 20.04 server and on an NGINX server

![demo](https://user-images.githubusercontent.com/61474191/119560261-00c30880-bda4-11eb-944b-adea7f409414.jpg)

Thanks for your help

**Comment by DanielnetoDotCom** [comment]
Please try this

**Comment by JeanDavis91** [comment]
Hello

I validate the new code it works perfectly for the categories now on Linux 20.04 and NGINX server

![valider](https://user-images.githubusercontent.com/61474191/119581323-9bcadb00-bdc2-11eb-9952-d634654391f7.jpg)

Thanks for your help
