### ISSUE TITLE
New Features and Functions

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#5210]
What is the Scheduler and its functionality?

Also, what are the new updates for 11.1?

**Comment by DanielnetoDotCom** [comment]
It allow you to suggest categories on the main page 

https://github.com/WWBN/AVideo/blob/master/updatedb/updateDb.v11.1.sql

**Comment by CROSSMediaNet** [comment]
Okay. Still don't understand it. I thought it would schedule broadcasts.

**Comment by DanielnetoDotCom** [comment]
The scheduler will be used for multiple propouses. for now, I do not have documentation for it.
and yes I will let you schedule a live record start/stop

**Comment by CROSSMediaNet** [comment]
Okay, so when will the documentation be out?
