### ISSUE TITLE
Update error?

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#5214]
When I updated the application first to 10.5, it gave me this error: 

![image](https://user-images.githubusercontent.com/63721378/119477887-085cc000-bd58-11eb-81d2-efc6b0c735b0.png)

Should I be worried?

**Comment by DanielnetoDotCom** [comment]
I guess you can ignore it

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform#problems

**Comment by JeanDavis91** [comment]
Hello

I have not encountered any problem updating Avideo v11.1 on my NGNIX server and on Ubuntu server 20.04.

I am thinking of a server configuration problem and I think like DanielnetoDotCom you can ignore the error for the users_extra_info table

goodbye
