### ISSUE TITLE
Video Player not remembering where I left off!

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5216]
I wanted to ask bc I am not sure if this is only on my site or this is how the player works. This is an issue on both mobile and browsers. When a user starts to play a video and for some reason needs to close or leave the page and then come back to the video (maybe electricity went off etc...), we never get the last viewed point where we left the video. I know this is possible to achieve and I think and important one. Can this be fixed or implemented?

I believe this will be very much appreciated by all AVideo Platform users.

**Comment by JeanDavis91** [comment]
Bonjour

Je viens de tester cette fonction et cela fonctionne parfaitement.

![tracking](https://user-images.githubusercontent.com/61474191/119586375-db96c000-bdcc-11eb-9379-6fe82449dc91.jpg)

Il faut simplement lire la video puis faire pause et cela reprend la video la ou l'on avait arreter

J'ai fait ces test sur un serveur Ubuntu 20.04 , sur un serveur NGINX et sur Android V9.0 avec Avideo V11.1

Bonne journée

**Comment by JoshWho** [comment]
I confirm the same issue. Videos always starting at the end when i watched it all the way through.

**Comment by guymass** [comment]
> Hello
> 
> I just tested this feature and it works perfectly you must have an account and be logged into the site for it to work!
> 
> ![tracking](https://user-images.githubusercontent.com/61474191/119586375-db96c000-bdcc-11eb-9379-6fe82449dc91.jpg)
> 
> Just play the video then pause and the video will resume where you stopped
> 
> I did these tests on an Ubuntu 20.04 server, on an NGINX server and on with Avideo V11.1
> 
> I did these reading tests on browsers following Firefox, Chrome, edge, and on Android v 9.0 (Chrome)
> 
> good day

What feature are we talking about? are you referring to a plugin? I don't have this feature and I have the same spec as yours. If I start playing a video and after a min or so I will try to go to another page and then hit back, the video will reset and start from beginning. Unless there is an option I misses maybe on the player? Maybe set it to start playing as the page loads? My videos I set to not play when user enter the video page, they need to click the > player button to start the video.

**Comment by JeanDavis91** [comment]
Hello

I don't have any additional plugins, however, I just reconnected 1 day later and playback resumed where I stopped it

So there is a problem with Avideo or the server

Jfr
