### ISSUE TITLE
Posting comments make dark transparent screen pop up and doesnt go away

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5218]
Having a issue with after you post the comment it just gets stuck in the dark transparent screen with a loading indicator. 

![d8a2309c-33ff-43f3-8235-95470e2c11dd](https://user-images.githubusercontent.com/39392449/119629682-ddb04d00-bdd3-11eb-8bc3-a3fbadb90ad9.png)

**Comment by DanielnetoDotCom** [comment]
Thanks, this should fix it
