### ISSUE TITLE
How to use Foldername from Video_title instead Video_date ?

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#5221]
Since one of the last updates foldernames  from stored videos are changed to video_date_time_key

How change this back to the earlier version generated from Title_name ?

![Snap1](https://user-images.githubusercontent.com/39981177/119683356-de80c780-be43-11eb-831a-761d8e192c61.jpg)

**Comment by DanielnetoDotCom** [comment]
Not possible

**Comment by TLCReuver** [comment]
Ok@y, i shall add descript.ion in filelist for folder_comments.

Thankz.

**Comment by DanielnetoDotCom** [comment]
Sorry I did not understand what you mean

**Comment by TLCReuver** [comment]
Hi Daniel,

Because i missing the title_names of the video in avideo.log and access.log from Apache it's difficult to see what is going on the server and which video is causing problems (names say me more than numbers).  So i have to add folder_comments with descript.ion so i have a quicker overview what content is in that folder. 

![Snap2](https://user-images.githubusercontent.com/39981177/119935558-f95c5480-bf87-11eb-9d4d-14bdf7105fcc.jpg)

**Comment by DanielnetoDotCom** [comment]
name can and will change, if you do that you will mess up the system. folders must be a permanent value.

**Comment by TLCReuver** [comment]
Folders will not be touched Daniel (same as Video>filename). Comments are stored outside video<dir> as descript.ion (=txt_file)
Th@nkz

**Comment by DanielnetoDotCom** [comment]
Sorry, I do not understand what and why you want to do.

comments are stored on the database, there is no reason to use text files for that.

**Comment by akhilleusuggo** [comment]
@TLCReuver the video's description is stored only on the database

@DanielnetoDotCom I believe he want to add comments to the folders ( to distinguish what videos are users watching from the log files ). Example

Default logs : `GET /video_ypt_ID1200`  ( we don't really know what video is the video 1200 ) .

Adding comments would look like this ;
`GET /MyVideoName_test`

Never tested it, not I knew about it.

**Comment by TLCReuver** [comment]
Exactly akhilleusuggo, that makes logs more usable.
