### ISSUE TITLE
Plugin update

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5226]
I would like to explain how to install updates correctly.
Step 1: Download the purchased plugins.
Step 2: Amount with the + Upload to Plugin button

![Cattura](https://user-images.githubusercontent.com/82677269/119742340-dc405c80-be87-11eb-9d98-d5e37bc8ebeb.PNG)

Step 3: Is it mandatory to use the git pull command?

Daniel explain me the correct steps?
Thank you

**Comment by akhilleusuggo** [comment]
Just download the plugins and upload them , then click "upload". I green symbol should appear to confirm your plugin upload.
Done;

**Comment by sharknetwork24** [comment]
![Cattura](https://user-images.githubusercontent.com/82677269/119887729-c8066900-bf34-11eb-9cd4-e64c21e0af36.PNG)

What should I do here?
How should I click?

**Comment by DanielnetoDotCom** [comment]
Click on the red button and install the tables

**Comment by sharknetwork24** [comment]
I installed the red button on the tables.
Now what should I do?
The orange one?

**Comment by sharknetwork24** [comment]
![Cattura](https://user-images.githubusercontent.com/82677269/119889977-89be7900-bf37-11eb-9adc-7e00e91d0909.PNG)

**Comment by sharknetwork24** [comment]
Do I have to execute this command to update the free plugins?
Including && must be entered?
Or just git pull is enough

![Cattura](https://user-images.githubusercontent.com/82677269/119890740-7c55be80-bf38-11eb-968e-cb1b5ec66f9f.PNG)

**Comment by akhilleusuggo** [comment]
1-Yes ( update to @5.3 )
2-Yes ( make sure your project it's folder directory name is YouPHPTube , or AVideo ) change it as you have.

the `cd` stands for Change Directory
You need to do go where you installed the script, then run `git pull` to update the free plugins.
