### ISSUE TITLE
How do different video resolutions work? 

### ISSUE THREAD

**Issue by VWarte** [WWBN/AVideo#5229]
I have a question about the different video resolutions that are created with the encoder. 

By default, while uploading a video, all video resolutions under the configuration tab are selected, starting from 240 up to 2160. 

So as far as I understand, the encoder will encode the video to all those resolutions, considering I have uploaded a 4k video. 

But what resolution will the streamer site use to playback the video in the player? Right now, it seems like it always picks the lowest available resolution video. As in the example above, it's 240p. Or is there some kind of dynamic playback, the depends on the bandwidth and so on?

I've also seen the paid plugin, that you can use to manually choose a playback video resolution while watching a video. Is that right, that there are only 3 resolution options available? And if so, are those options configured in the encoder, or on the streamer site? 

Thanks in advance!

Best regards, 
Vince

**Comment by DanielnetoDotCom** [comment]
Hi, 

if the video is MP4 you need the VideoResolutionSwitcher to switch between resolutions

if is the HLS it will be an adaptive bitrate and the video will switch depending on the available bandwidth

**Comment by joho1968** [comment]
Where and how is the VideoResolutionSwitcher configured?

**Comment by DanielnetoDotCom** [comment]
Hi, you can purchase it on the market place https://youphp.tube/marketplace/

also please read this 

https://github.com/WWBN/AVideo/wiki/About-Video-Upload#video-format

**Comment by mostafaaalii** [comment]
> I have a question about the different video resolutions that are created with the encoder.
> 
> By default, while uploading a video, all video resolutions under the configuration tab are selected, starting from 240 up to 2160.
> 
> So as far as I understand, the encoder will encode the video to all those resolutions, considering I have uploaded a 4k video.
> 
> But what resolution will the streamer site use to playback the video in the player? Right now, it seems like it always picks the lowest available resolution video. As in the example above, it's 240p. Or is there some kind of dynamic playback, the depends on the bandwidth and so on?
> 
> I've also seen the paid plugin, that you can use to manually choose a playback video resolution while watching a video. Is that right, that there are only 3 resolution options available? And if so, are those options configured in the encoder, or on the streamer site?
> 
> Thanks in advance!
> 
> Best regards,
> Vince

**Comment by mostafaaalii** [comment]
hello can i speak with you sir?

**Comment by DanielnetoDotCom** [comment]
@mostafaaalii Sorry, I cannot provide email support but I can provide direct support (meeting with a screen share), for this you can hire me for paid support. We just schedule a time and I will be with you online.

We also offer free support on GitHub, you just need to open an issue on GitHub and post any bug or usage question there. We will be happy to help you there and share this knowledge with others https://github.com/YouPHPTube/YouPHPTube/issues

If you are not sure how to open an issue check this tutorial https://help.github.com/en/github/managing-your-work-on-github/creating-an-issue
