### ISSUE TITLE
Timeout on login

### ISSUE THREAD

**Issue by SubjectXXX** [WWBN/AVideo#5230]
Fresh installation, Ubuntu 20.10, PHP8.0, everything updated. Using latest Chrome.

When I try to login with admin, circles keep spinning, then I get ERR_EMPTY_RESPONSE on /objects/login.json.php.

If I refresh page, I see that I'm logged in and directed to /user.

If I logout, click on Remember me and login back, same error happens.

PHP logs dont show anything.

Because of this error I also cannot set up encoder, since encoder tries to login to streamer but gets same error..

**Comment by SubjectXXX** [comment]
![Screenshot_12](https://user-images.githubusercontent.com/2082595/119798518-809fbe80-bedb-11eb-976e-d5b90472d33f.png)

**Comment by DanielnetoDotCom** [comment]
It is not a timeout, but check your logs

**Comment by SubjectXXX** [comment]
Thats the problem, php logs nor apache log doesnt mention anything here..

Could it be that, I cannot access port 80/443 via domain name on same machine?

**Comment by SubjectXXX** [comment]
I have double checked and its not on networking layer.
Its returns ERR_EMPTY_RESPONSE and then only reload helps, that logs me into the platform.

Then I went into plugins and disabled all plugins and it started working. I do get:

**Comment by SubjectXXX** [comment]
Didnt take long to find that if I have MobileManager enabled, this error happens.
I would need this plugin to be enabled because of API file upload.
How to debug this further?

**Comment by DanielnetoDotCom** [comment]
you do not need MobileManager  for the API, but if it is an 500 error MUST be something on the logs

**Comment by SubjectXXX** [comment]
Thats the problem, there is no error, just this timeout with nothing received from server/application.

I have errors turned on in PHP.

Interesting is, that I also cannot login to encoder now. I've managed to finish installation of encoder, since I can login now without error (with MobileManager turned off), but I cannot login into encoder.

Should I open different ticket for this?

**Comment by DanielnetoDotCom** [comment]
definitely, I do not know. 

I cannot tell you without the log (apache or avideo logs).

**Comment by SubjectXXX** [comment]
Are there any avideo logs or you mean php logs?

**Comment by DanielnetoDotCom** [comment]
both

**Comment by SubjectXXX** [comment]
Where can I find avideo logs then? PHP logs are empty..

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

you MUST find something on the apache log, NOT PHP log

By default apache log is on, `/var/log/apache2/error.log`

**Comment by SubjectXXX** [comment]
Apache log also empty :(

**Comment by SubjectXXX** [comment]
OK, I found something in avideo.log, will analyze it tommorow.

Problem with encoder login still persists tho, only thing I can find in avideo.log from encoder/videos/ is:
[27-May-2021 19:36:20 UTC] https://video.subjectx.net/ == https://video.subjectx.net/
[27-May-2021 19:36:20 UTC] login.json: Login::run
[27-May-2021 19:36:20 UTC] Login::run (admin, ***, https://video.subjectx.net/, false)
[27-May-2021 19:36:20 UTC] Login::run request login user (admin)
[27-May-2021 19:36:23 UTC] Login::run request login complete user (admin)
[27-May-2021 19:36:23 UTC] Get Login fail, try again user (admin)

But I'm entering same password that I successfully login to streamer..

**Comment by DanielnetoDotCom** [comment]
if the error is on encoder, make sure the encoder can access the site  https://video.subjectx.net/

**Comment by SubjectXXX** [comment]
Well, its on the same instance.. Is there any extra port that needs to be opened?

**Comment by DanielnetoDotCom** [comment]
I am not sure what is your error, but your encoder server must be able to resolve your streamer domain

the required ports are https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements#what-ports-do-i-need-to-open

**Comment by Maikuolan** [comment]
> Uncaught ReferenceError: isSocketActive is not defined

It seems, `isSocketActive` is defined by `plugin/YPTSocket/Script.js`:

https://github.com/WWBN/AVideo/blob/7bb2844fedd2d153e985472f8335c4f1c06660af/plugin/YPTSocket/script.js#L123-L125

When [searching the repository](https://github.com/WWBN/AVideo/search?q=isSocketActive), I don't see it defined anywhere else.

That in mind, is it possible, that particular error message has something to do with YPTSocket?

**Comment by SubjectXXX** [comment]
> > Uncaught ReferenceError: isSocketActive is not defined
> 
> It seems, `isSocketActive` is defined by `plugin/YPTSocket/Script.js`:
> 
> https://github.com/WWBN/AVideo/blob/7bb2844fedd2d153e985472f8335c4f1c06660af/plugin/YPTSocket/script.js#L123-L125
> 
> When [searching the repository](https://github.com/WWBN/AVideo/search?q=isSocketActive), I don't see it defined anywhere else.
> 
> That in mind, is it possible, that particular error message has something to do with YPTSocket?

Thank you for your reply.

Yes, I have found out, that problem is with plugins, thus I deactivated all of them and error went away. 
I will research later, which plugins triggers what errors, but now I'm mainly focused on why encoder cannot access streamer, problem is on my side, not with AVideo platform.
