### ISSUE TITLE
Customize Advanced - useVideoIDOnSEOLinks

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#5232]
Dear,

I checked a BUG when disabling the Plugin function:
In: CustomizeAdvanced (CustomizeAdvanced) Version: @1.0

When the function: "useVideoIDOnSEOLinks" is disabled, the links are broken and when you select a video, it displays a different video. Check out the video:

https://www.dropbox.com/s/8sphcf3l7lcoufg/2021-05-28%2001-18-26.mp4?dl=0

**Comment by akhilleusuggo** [comment]
maybe you should clear the cache, then try again.

Disabling video ID SEO doesn't completely disable the video id seo. Users can still browse and watch videos using the video's ID.
