### ISSUE TITLE
Force Thumb Size for Live Stream thumbs

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5235]
Need to make Live Stream thumb static 1280x720 

![87f572dc-9b74-4702-b4df-5e6e4adc4e78](https://user-images.githubusercontent.com/39392449/120065399-b907df80-c036-11eb-9d55-382bd3ccffb6.png)

**Comment by JoshWho** [comment]
Just needs actual size attributes

**Comment by DanielnetoDotCom** [comment]
As I can see on your site  it looks fine

![image](https://user-images.githubusercontent.com/18009293/121032837-09431800-c782-11eb-9368-15a8be2304d3.png)
