### ISSUE TITLE
Preferred video upload format

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#5239]
We have a user that is uploading .MP4 in "FullHD" (1920x1080) format. They take quite some time to process, even when the user uploads at idle times (4x vCPU). We also find that the resulting stream (using encoder on same server) is nowhere near the uploaded .MP4 when it comes to quality.

- What is the preferred upload format, when it comes to quality?
- Are there any CLI or config settings that we can change to improve the final stream result when it comes to quality?

**Comment by DanielnetoDotCom** [comment]
I just wrote this https://github.com/WWBN/AVideo/wiki/About-Video-Upload#resolutions

please check if is clear now.

**Comment by joho1968** [comment]
The [Configurations] tab, is it sticky? I mean, if I set MP4 HD there, that's what it will encode it to, and not any other resolution/format? I want to force MP4 HD only.

**Comment by DanielnetoDotCom** [comment]
If you want to force MP4 in a single resolution you may want to set it up like this...

![image](https://user-images.githubusercontent.com/18009293/120357842-4029b180-c2dc-11eb-819a-0144c25e7b1b.png)


I expect with this to use only the HD FFmpeg code
