### ISSUE TITLE
Update thumbnails automatically for direct uploaded MP4

### ISSUE THREAD

**Issue by joho1968** [WWBN/AVideo#5240]
Due to quality and encoding issues with many MP4 files, we try to do direct uploads of some MP4 files ("Direct import"). But it seems like we don't get any thumbnails generated when this is done.

How do we force re-creation/updating of the thumbnails of a video?

The video is visible under "My videos", but I can't seem to automatically scan the file for thumbnails and update them?

**Comment by akhilleusuggo** [comment]
There is a premium plugin for that. Make sure is what you're looking for. https://youphp.tube/marketplace/

### MP4ThumbsAndGif

> Automatic request to the encoder, an poster image and an animated gif from the Uploaded MP4 File

I've never used it, so I can't leave a feedback. But the plugin is straight forward.

**Comment by millzee01** [comment]
I use the plugin and it works great!
