### ISSUE TITLE
Category pages to display videos where tag_name == category_name

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5241]
**Is your feature request related to a problem? Please describe.**
I have videos that fit within a category, say, "Jeffery Epstein" has full shows on the single topic 
(i.e. media == fits into category)

There are other documentaries and podcasts where "Jeffery Epstein" is mentioned along with other topics.
(i.e. media == fits into multiple categories)
In this case the media gets multiple tags including "Jeffrey Epstein"

**Describe the solution you'd like**
I would like the items where tag name == category name to appear on the /cat page in their own distinct group, so a second section for "Tagged" videos.

[see other feature request - "Related" tags to display together - related tags will also display underneath this)

**Describe alternatives you've considered**
By applying the same tag to videos in the category, then guiding the user to the /tag page. You lose fidelity, there are not separate buckets for "program about x" and "multi-topic program including a segment on x"

**Comment by DanielnetoDotCom** [comment]
I see and it makes sense. I may add this feature in the future.
