### ISSUE TITLE
"Related" tags to display together

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5242]
**Is your feature request related to a problem? Please describe.**
I'm trying to build an index of videos to make researching a topic easier. There are tags that are highly correlated, and should appear together (i.e. "Jefferey Epstein", his handler "Ghislaine Maxwell" and her Mossad agent father "Robert Maxwell"), I have >500 tags and many examples...

**Describe the solution you'd like**
A table of "Related tags", where we can put Jeff, Ghislaine & Robert into one bucket together. Each of the /tag/ pages should have sections for all three related tags.

[see other feature request "Display associated tagged items on category page" - both correlate)

**Describe alternatives you've considered**

**Additional context**

**Comment by DanielnetoDotCom** [comment]
Hi, it is not clear, should the related tags be manually added?

**Comment by walt93** [comment]
Yes, think of it as a way to manually set up the indexing system. For another example, you might have a tag "Dogs" and related tags would be "Poodle", "Pomerainian", "Rottweiler", ...

You can then see the layout for the page /tags/Dogs would then show a section for the tag /dogs, and below that would be sections for /poodle /pomeranian /rottweiler, ...

------------
[In other feature request should be named "Display tagged items on category page when the tag name and category name are ==] so on /cat/dogs it would show everything in category dogs, below that a section for everything with /tag/dogs, and below that are your related tags /tag/poodle, ... -

Both of these features together make the /cat page a super-index of all content of that category, and content that is related to that category.

**Comment by walt93** [comment]
(and in my case related are going to be things like Jeffery Epstein and Ghislaine Maxwell, if you're not familiar with their story, it's fascinating and Ghislaine's trial is not over yet. But, I digress…) ;-)
