### ISSUE TITLE
PWA  Progressive Web App so we can just bypass the app stores for mobile

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5243]
This is the future and I have been telling others about it for a while. I have my news site https://www.joshwho.net  already using PWA so people can go to my website from their mobile devices and they will see a message to install shortcut to their home page. 

This is literally the future for all mobile apps because this bypasses all the censors and app stores from blocking you from others using your services with mobile devices.

Here is a article that will talk more about this https://yoast.com/what-is-a-progressive-web-app-pwa/

**Comment by DanielnetoDotCom** [comment]
Do you have any sample code that you are already using so it will be clear for me?

**Comment by JoshWho** [comment]
Google has an excellent, easy to follow tutorial on PWAS on the web.dev site. Mozilla has lots of documentation on building progressive web apps. Microsoft also has rich developer docs on building PWAs. Microsoft even built a tool called PWABuilder that’ll help you turn your site into a PWA. Of course, there are WordPress plugins that help you make a PWA of your site. In addition, Google is working on bringing base-support for PWAs to WordPress Core.

**Comment by JoshWho** [comment]
Basically u just have a manifest file in the webroot with all the icons sizes and screenshot and then you have it call a java worker that will ask mobile users if they want to install it to their phone.

I was checking out the site PWABuilder which they have a github i think but here is their site https://www.pwabuilder.com/

**Comment by DanielnetoDotCom** [comment]
This update is an start for a PWA app

**Comment by JoshWho** [comment]
Works great!!!!!!!!!!

**Comment by JoshWho** [comment]
Here is so more info on how to link buttons to it   https://components.pwabuilder.com/component/inking

A simple component that gives users a button to install your PWA directly from the browser https://components.pwabuilder.com/component/install_pwa

and Full Git Hub Project here https://github.com/pwa-builder/pwa-install
