### ISSUE TITLE
Premium Users Get ad free experience 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5245]
Make it to where a account can be a premium user and has no ads visible for them.

Basically  just make it to where no ad code is visible to them unless they still want it.

**Comment by DanielnetoDotCom** [comment]
If I am not wrong if you have the subscription and you subscribe to any plan you will not see ads anymore. (banners and video ads)

If you check that you will remove the banners for users that have a subscription active

![image](https://user-images.githubusercontent.com/18009293/120323425-d8fc0500-c2bb-11eb-814a-c7f1e880aa49.png)


If you check that it will remove the video ads

![image](https://user-images.githubusercontent.com/18009293/120323635-1365a200-c2bc-11eb-9363-77ff9a495bb3.png)

**Comment by JoshWho** [comment]
Is there a way to also make it not show the Vast video ads for premium as well?

**Comment by DanielnetoDotCom** [comment]
Yes, I am pretty sure the subscription will remove the Vast ads

**Comment by JoshWho** [comment]
No i still see them playing on a premium account

**Comment by DanielnetoDotCom** [comment]
You must use GoogleAds_IMA NOT AD_Server

but you can add the AD_Server VAST URL into the GoogleAds_IMA

**Comment by JoshWho** [comment]
I c Thank you
