### ISSUE TITLE
Updating to 11.1. "Fail to move"

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#5251]
Hey,

I'm having an issue updating my main server. 

After git pull and update versions, I run this:
`cd /var/www/html/AVideo/install
php moveFilesToFolder.php`

But the server prompts many lines of "fail to move": 

` 236/236 Searching /var/www/html/AVideo/videos/_YPTuniqid_60a7e2f43dfad3.08077185 
Creating dir /var/www/html/AVideo/videos/_YPTuniqid_60a7e2f43dfad3.08077185 
Found total of 6 items 
[1/6] Process file /var/www/html/AVideo/videos/_YPTuniqid_60a7e2f43dfad3.08077185 
-->
 236/236 move directory /var/www/html/AVideo/videos/_YPTuniqid_60a7e2f43dfad3.08077185 to /var/www/html/AVideo/videos/video_210521194228_81d2/ 
<--
[2/6] Process file /var/www/html/AVideo/videos/_YPTuniqid_608efdddcef125.02539863.gif 
233/236 fail to move _YPTuniqid_608efdddcef125.02539863.gif to /var/www/html/AVideo/videos/_YPTuniqid_60
8efdddcef125.02539863/_YPTuniqid_608efdddcef125.02539863.gif
[3/6] Process file /var/www/html/AVideo/videos/_YPTuniqid_608efdddcef125.02539863.jpg 
233/236 fail to move _YPTuniqid_608efdddcef125.02539863.jpg to /var/www/html/AVideo/videos/_YPTuniqid_60
8efdddcef125.02539863/_YPTuniqid_608efdddcef125.02539863.jpg
[4/6] Process file /var/www/html/AVideo/videos/_YPTuniqid_608efdddcef125.02539863.webp 
233/236 fail to move _YPTuniqid_608efdddcef125.02539863.webp to /var/www/html/AVideo/videos/_YPTuniqid_6
08efdddcef125.02539863/_YPTuniqid_608efdddcef125.02539863.webp
[5/6] Process file /var/www/html/AVideo/videos/_YPTuniqid_608efdddcef125.02539863_thumbsSprit.jpg 
233/236 fail to move _YPTuniqid_608efdddcef125.02539863_thumbsSprit.jpg to /var/www/html/AVideo/videos/_
YPTuniqid_608efdddcef125.02539863/_YPTuniqid_608efdddcef125.02539863_thumbsSprit.jpg
[6/6] Process file /var/www/html/AVideo/videos/_YPTuniqid_608efdddcef125.02539863_thumbsV2.jpg 
233/236 fail to move _YPTuniqid_608efdddcef125.02539863_thumbsV2.jpg to /var/www/html/AVideo/videos/_YPT
uniqid_608efdddcef125.02539863/_YPTuniqid_608efdddcef125.02539863_thumbsV2.jpg
 234/236 Searching /var/www/html/AVideo/videos/_YPTuniqid_608f0172552d84.36220763 
Creating dir /var/www/html/AVideo/videos/_YPTuniqid_608f0172552d84.36220763 
Found total of 7 items `

And a lot of (but not all) my cover thumbnails aren't showing. 

I have something like 230 videos. 

Can you tell what is the problem here, please? I can't update because of this. 

In my test server I have reduced the number of videos and the script worked right.

**Comment by DanielnetoDotCom** [comment]
can you check the permissions?

FYI if you have the MP4ThumbsAndGif plugin you can regenerate all images

`cd /var/www/html/AVideo/plugin/MP4ThumbsAndGif && php getAllMissing.php
`

**Comment by tonuzo** [comment]
Is this right?

![image](https://user-images.githubusercontent.com/63721378/120361103-27d48980-c312-11eb-8a35-2a6f76df9619.png)

**Comment by DanielnetoDotCom** [comment]
Try to run  with sudo

`sudo php moveFilesToFolder.php`

**Comment by tonuzo** [comment]
It didn't work. 

this didn't work either:
`cd /var/www/html/AVideo/plugin/MP4ThumbsAndGif && php getAllMissing.php`

It did the work, but jpgs and gifs are 0kb

![image](https://user-images.githubusercontent.com/63721378/120366538-708f4100-c318-11eb-8b2a-e73cd0b33dc4.png)

Somehow the MP4ThumbsAndGif haven't ever worked for me. 

This is what I get on log if I try to use it:

` [01-Jun-2021 20:26:52] AVideoLog::DEBUG: wget: ERROR the url download but is empty https://***************/upload/getImageMP4/aHR0cHM6Ly93d3cud2VsbG5lc3NvbmxpbmUuZmkvdmlkZW9zL3ZpZGVvXzIxMDUyMTE5NDIyOF9iZDBlL2luZGV4Lm0zdTg=/webp/1690.5, path/to/my/streamer/site/videos/cache/YPTurl_get_contents/d9d5460a0674cd7229533d5a548a5658 SCRIPT_NAME: /plugin/MP4ThumbsAndGif/get.php`

**Comment by DanielnetoDotCom** [comment]
Please update your site again and try the command 

`sudo php moveFilesToFolder2.php`

**Comment by tonuzo** [comment]
Only prompted this line:

`Open /var/www/html/AVideo/videos/avideo.log`

**Comment by tonuzo** [comment]
Wait. Now the thumbnails are in each video folder like this:
![image](https://user-images.githubusercontent.com/63721378/120374718-91f52a80-c322-11eb-9909-e25f413e0734.png)

Should I still php moveFilesToFolder.php or is this enough?

**Comment by DanielnetoDotCom** [comment]
you can run the` php moveFilesToFolder.php` as many times as you want.

if the videos are playing and the images are correct you can run the 

`php deleteOrphanFiles.php` to get delete the unecessary files

**Comment by tonuzo** [comment]
I mean I have now run the moveFilesToFolder2.php not moveFilesToFolder.php. Is it enough? Everything is working right now.

**Comment by tonuzo** [comment]
Folder names are _YPTuniqid_xxxxxx NOT video_xxxxxxxxxxx

**Comment by DanielnetoDotCom** [comment]
if is working you should be fine. no need to run it anymore.

**Comment by tonuzo** [comment]
Ok. Thank you!
