### ISSUE TITLE
Error Sorry webcam/meet

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5254]
I would like to know why this happens with this account?
With the other accounts it works fine but with one not why?

![ff](https://user-images.githubusercontent.com/82677269/120335751-05327880-c2f2-11eb-88a4-cc1174109bd9.PNG)

**Comment by DanielnetoDotCom** [comment]
does this account have meeting rights and live rights?

![image](https://user-images.githubusercontent.com/18009293/120358379-ccd46f80-c2dc-11eb-8cdc-7182e0c8b768.png)
