### ISSUE TITLE
Maintenance mode plugin doesn't work

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#5257]
When maintenance mode plugin is activated instead of maintenance-page it redirects to error 500 page.

` [01-Jun-2021 21:22:09] AVideoLog::ERROR: {"type":64,"message":"require_once(): Failed opening required '..\/..\/videos\/configuration.php' (include_path='.:\/usr\/share\/php')","file":"\/var\/www\/html\/AVideo\/plugin\/MaintenanceMode\/index.php","line":2} SCRIPT_NAME: /view/index.php`

![image](https://user-images.githubusercontent.com/63721378/120373106-a1737400-c320-11eb-9942-b9123d372479.png)

**Comment by DanielnetoDotCom** [comment]
Please try this update
