### ISSUE TITLE
Some CSS fixes

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5258]
The video blocks with the channel name and other options should be more nicely organised on RTL templates but also LTR. In my site they look out of alignments and I think you can separate those fields a bit more, maybe in a small table or give each part its own class.

I would like to see more clearly the channel name.
Edit video / Description / Add To

can be on their own line below the channel name imo.

![Screen Shot 5781-09-22 at 0 01 23](https://user-images.githubusercontent.com/58882903/120390460-667c3b00-c336-11eb-8d92-285f21aca483.jpg)

**Comment by DanielnetoDotCom** [comment]
What page is that? I just tested the RTL locally and it looks fine on my side

![image](https://user-images.githubusercontent.com/18009293/120482069-24c7b080-c387-11eb-822d-102c97a6e5fb.png)

**Comment by guymass** [comment]
It was on home page but since last git pull seems to be fixed
