### ISSUE TITLE
disableVideoTags not working

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#5259]
I made sure that disableVideoTags is selected on advanced configuration plugin. And just to make sure , I also added $global['disableVideoTags'] = 1; on configuration.php file. Still, the variable is not respected.

`AVideoLog::DEBUG: Warning: Slow process detected [getVideosURL_V2::VideoHLS::getSourceFil.............`
`AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1204 takes 12.6203 seconds to complete, Limit (2). `

I know this files are cached, but the option should be respected, since for me after clearing the cache, the first page takes 30s+ to generate and request. This is because the apache/PHP requests are not supporting multi-simultaneous ( parallel ) requests. Every request is made after the first got an answer. If each one takes 2s to response and you request 15 , then it's 30s.

This should be paralleled requested in case we want to keep it. ( that's why I wanna disable it )

`AVideoLog::DEBUG: Page generated in 50.577 seconds. User: xxx - No Cache (/) FROM: .......`

**Comment by DanielnetoDotCom** [comment]
how many videos are you selecting when this happens?

there is some more log around this? `getVideosURL_V2::VideoHLS::getSourceFil...`

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I'm not selecting any video. Just opening the first page. After that, every page ...

**Comment by DanielnetoDotCom** [comment]
I cannot reproduce this here, but please check if this update makes any difference

**Comment by akhilleusuggo** [comment]
```
AVideoLog::WARNING: VideoHLS:getSourceFile:returnAllSources ..............
AVideoLog::DEBUG: Warning: Slow process detected [getVideosURL_V2::VideoHLS::getSourceFile(_xx_601c31e4bc3054.26754273)] On  Line 1282 takes 2.0967 seconds to complete, Limit (0.7). /var/www.....
..........
and many more like
..........
AVideoLog::DEBUG: Page generated in 63.9667 seconds. User: xxxx- No Cache (/) FROM: 
```

**Comment by DanielnetoDotCom** [comment]
I would like to see more from the logs around it.

but how is the update, does it makes any difference?

**Comment by akhilleusuggo** [comment]
> I would like to see more from the logs around it.

There's nothing on the logs, they are almost all the same, the only difference is the file_name requested. If you wanna debug more on your side, go to `CustomizeAdvanced - disableVideoTags` select the option . Then clear all cache. Back to the first page and watch the logs

> but how is the update, does it makes any difference?

Not to my experience, nor to the logs.

**Comment by DanielnetoDotCom** [comment]
Please uncheck returnAllSources and see if makes any difference.

![image](https://user-images.githubusercontent.com/18009293/120662345-6deb3380-c45f-11eb-91f8-4114f527441f.png)

**Comment by akhilleusuggo** [comment]
It works, that's why I'm opening this issue. I'm saying that the setting `$global['disableVideoTags'] = 1` is not respected. Only after the latest updates. I always had this option enabled, and never had issues.

This gives faster load pages, but it removes the option **video quality selector**. I can't select any quality basically.

 `AVideoLog::DEBUG: Page generated in 0.1716 seconds. User: xxx - No Cache (/) .............`

**Comment by DanielnetoDotCom** [comment]
I see 

but the option I asked you to disable is not related to the videotags it is the resolution switcher

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom well then the issue is coming from there. Disabling this option, also disables resolution switcher

**Comment by DanielnetoDotCom** [comment]
But did you confirm the issue is coming from there?

**Comment by DanielnetoDotCom** [comment]
I just sent VideoHLS version 5.3 that will have a better cache for that.

**Comment by akhilleusuggo** [comment]
> But did you confirm the issue is coming from there?

yes

> I just sent VideoHLS version 5.3 that will have a better cache for that.

But what changes have you done lately to cause this issue?

I see a improvement after update. But yes, disabling the returnAllSources does speed up a lot, for some reason.
Again the issue is really related to the non-simultaneous requests. This is something that this project will have to work definitely.
