### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by redilee** [WWBN/AVideo#5260]
Anybody know what's messing this up? What/why is calling the non-existant files? 

==> /var/log/apache2/error.log <==
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugine9a568e6_ef61_4dcc_aad0_0109e9be8e36//fullstreem.live//http//-//notlogged_fa61fbd2e1d4ae996f20c232b9111ad6/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin10573225_3807_4167_ba81_0509dd280e06//fullstreem.live//https//-/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin10573225_3807_4167_ba81_0509dd280e06//192.99.1.141/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//getvideotags104//fullstreem.live//http//-//notlogged_fa61fbd2e1d4ae996f20c232b9111ad6/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin_getallenabled//fullstreem.live//https//US/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin10573225_3807_4167_ba81_0509dd280e06//fullstreem.live/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin10573225_3807_4167_ba81_0509dd280e06//fullstreem.live//https//-/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin_getallenabled//fullstreem.live//https/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin10573225_3807_4167_ba81_0509dd280e06//fullstreem.live//https//-/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin10573225_3807_4167_ba81_0509dd280e06//fullstreem.live/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin10573225_3807_4167_ba81_0509dd280e06/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin_getallenabled//fullstreem.live//https/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin10573225_3807_4167_ba81_0509dd280e06//fullstreem.live/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin10573225_3807_4167_ba81_0509dd280e06//fullstreem.live//https/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin10573225_3807_4167_ba81_0509dd280e06//fullstreem.live//https/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin_getallenabled//fullstreem.live//https//-/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin10573225_3807_4167_ba81_0509dd280e06//fullstreem.live//https/': No such file or directory
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache//plugin10573225_3807_4167_ba81_0509dd280e06//fullstreem.live//https/': No such file or directory
[Wed Jun 02 07:40:30.376558 2021] [mpm_prefork:notice] [pid 774] AH00169: caught SIGTERM, shutting down
[Wed Jun 02 07:41:43.627340 2021] [mpm_prefork:notice] [pid 815] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f configured -- resuming normal operations
[Wed Jun 02 07:41:43.663187 2021] [core:notice] [pid 815] AH00094: Command line: '/usr/sbin/apache2'
rm: cannot remove '/var/www/html/AVideo/videos/cache/YPTObjectCache/': Directory not empty

==> /usr/local/nginx/logs/error.log <==
2021/06/02 07:49:43 [error] 772#0: *244 open() "/HLS/live/6082cef659356/index.m3u8" failed (2: No such file or directory), client: 185.93.1.241, server: localhost, request: "GET /live/6082cef659356/index.m3u8 HTTP/1.1", host: "fullstreem.live", referrer: "https://fullstreem.live/"
2021/06/02 07:49:45 [error] 772#0: *245 open() "/HLS/live/6082cef659356/index.m3u8" failed (2: No such file or directory), client: 185.93.1.241, server: localhost, request: "GET /live/6082cef659356/index.m3u8 HTTP/1.1", host: "fullstreem.live", referrer: "https://fullstreem.live/"
2021/06/02 07:49:47 [info] 772#0: *246 client 24.111.119.124 closed keepalive connection
2021/06/02 07:49:47 [error] 772#0: *247 open() "/HLS/live/6082cef659356/index.m3u8" failed (2: No such file or directory), client: 185.93.1.241, server: localhost, request: "GET /live/6082cef659356/index.m3u8 HTTP/1.1", host: "fullstreem.live", referrer: "https://fullstreem.live/"
2021/06/02 07:49:50 [error] 772#0: *248 open() "/HLS/live/6082cef659356/index.m3u8" failed (2: No such file or directory), client: 185.93.1.241, server: localhost, request: "GET /live/6082cef659356/index.m3u8 HTTP/1.1", host: "fullstreem.live", referrer: "https://fullstreem.live/"
2021/06/02 07:49:52 [error] 772#0: *249 open() "/HLS/live/6082cef659356/index.m3u8" failed (2: No such file or directory), client: 185.93.1.241, server: localhost, request: "GET /live/6082cef659356/index.m3u8 HTTP/1.1", host: "fullstreem.live", referrer: "https://fullstreem.live/"
2021/06/02 07:49:54 [error] 772#0: *250 open() "/HLS/live/6082cef659356/index.m3u8" failed (2: No such file or directory), client: 185.93.1.241, server: localhost, request: "GET /live/6082cef659356/index.m3u8 HTTP/1.1", host: "fullstreem.live", referrer: "https://fullstreem.live/"
2021/06/02 07:49:56 [error] 772#0: *251 open() "/HLS/live/6082cef659356/index.m3u8" failed (2: No such file or directory), client: 185.93.1.241, server: localhost, request: "GET /live/6082cef659356/index.m3u8 HTTP/1.1", host: "fullstreem.live", referrer: "https://fullstreem.live/"
2021/06/02 07:49:58 [error] 772#0: *252 open() "/HLS/live/6082cef659356/index.m3u8" failed (2: No such file or directory), client: 185.93.1.241, server: localhost, request: "GET /live/6082cef659356/index.m3u8 HTTP/1.1", host: "fullstreem.live", referrer: "https://fullstreem.live/"
2021/06/02 07:50:00 [error] 772#0: *253 open() "/HLS/live/6082cef659356/index.m3u8" failed (2: No such file or directory), client: 185.93.1.241, server: localhost, request: "GET /live/6082cef659356/index.m3u8 HTTP/1.1", host: "fullstreem.live", referrer: "https://fullstreem.live/"
2021/06/02 07:50:02 [info] 772#0: *254 client 24.111.119.124 closed keepalive connection
2021/06/02 07:50:02 [error] 772#0: *255 open() "/HLS/live/6082cef659356/index.m3u8" failed (2: No such file or directory), client: 185.93.1.241, server: localhost, request: "GET /live/6082cef659356/index.m3u8 HTTP/1.1", host: "fullstreem.live", referrer: "https://fullstreem.live/"
2021/06/02 07:50:04 [error] 772#0: *256 open() "/HLS/live/6082cef659356/index.m3u8" failed (2: No such file or directory), client: 185.93.1.241, server: localhost, request: "GET /live/6082cef659356/index.m3u8 HTTP/1.1", host: "fullstreem.live", referrer: "https://fullstreem.live/"

**Comment by DanielnetoDotCom** [comment]
I do not think you should worry about those warnings.
