### ISSUE TITLE
Mobile Browsers having problems playing videos

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5262]
Some reason new videos r now not playing on mobile but works fine on desktop. When I click play it looks like it is gonna load then just shows a play button again and does nothing.  Android Chrome and Brave

**Comment by JeanDavis91** [comment]
Hello
Can you give the address of your website  pour tester ?

Thank

Have a day

**Comment by JoshWho** [comment]
it is JoshWho https://ww.joshwhotv.com

**Comment by DanielnetoDotCom** [comment]
Only new videos?

**Comment by JoshWho** [comment]
not sure now. May have just been the error u showed me yesterday. Looks good now.
