### ISSUE TITLE
Bug in template

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5263]
Qe have recently installed two new plugins one is the Video Thumbnail and the other was LiveUsers. Now whenever I open a video page and then fo back to home page the top menu gets scrambles where the language is and the main menu cannot be opened. This also occurs when logging out.

![Screen Shot 5781-09-22 at 19 15 41](https://user-images.githubusercontent.com/58882903/120515568-173a1700-c3d7-11eb-90f4-66b260a6a2d5.jpg)

**Comment by DanielnetoDotCom** [comment]
please make a git pull clear your cache and try again.

**Comment by guymass** [comment]
OK its fixed now thanks!
