### ISSUE TITLE
posting links from youtube on the site are not working. 

### ISSUE THREAD

**Issue by fishrdottv** [WWBN/AVideo#5265]
**Describe the bug**
When trying to post a link in the site it disappears again after pressing save.

**To Reproduce**

**Expected behavior**

**Error Logs**
Provide the log files at the moment you found the issue.
If you are not sure how to find the log file, please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DanielnetoDotCom** [comment]
What exactly link are you adding?

and in what menu are you clicking to add? (please screenshot)

**Comment by fishrdottv** [comment]
As usual. Adding links via the link section


Gareth Bagley - Co founder 
Business development 
CF LV1-Coach
***@***.***
+46 768986506
