### ISSUE TITLE
Uncaught Error: Call to undefined function _error_log

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#5267]
Hi 

I received the following Fatal error. Not sure what it means

[04-Jun-2021 22:04:06 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined function _error_log() in path/to/my/streamer/site/objects/include_config.php:44

Please advise.

**Comment by DanielnetoDotCom** [comment]
thanks for notice that. here is a fix.

but BTW it is regarding a database connection problem.

**Comment by kollossus55** [comment]
Hi 
what is the fix ?

**Comment by DanielnetoDotCom** [comment]
The solution is to enter the correct MySQL credentials on the configuration.php file and make sure MySQL is working properly 

the git pull update will not show you a fatal error anymore

**Comment by kollossus55** [comment]
Hi. .Sorry have been sorting a family personal matter.
What would I need to put in the configuration file to sort mysql connections? would it be the userid / password ?

**Comment by DanielnetoDotCom** [comment]
Hi, I hope is all fine with you and your family now.

First, make a `git pull`.  https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

if you are facing any database problem you will need to review your credentials.

**Comment by kollossus55** [comment]
Hi 

Everything seems fine now.. Did a git pull.. Will monitor..

Thanks for your help..
