### ISSUE TITLE
When showing Suggested in Gallery, top section disappears and second one is shown twice

### ISSUE THREAD

**Issue by gunthor-hammerwurf** [WWBN/AVideo#5269]
I use Gallery as the first page. In the sorting options, when I activate Suggested and put it above the other activated sections, the suggested videos are shown as expected. But the former upper section is replaced with the former second section, which is still displayed as third section.
When there are no suggested videos, there are of course no suggested videos displayed, but still the former upper section is replaced with the former second section, which is still displayed a second section.

For a better understanding without having suggested videos (please pay attention to the icons since I cannot show the names and thumbnails):

This

![image](https://user-images.githubusercontent.com/83225309/120895713-86557c80-c61e-11eb-8334-02f5274eb665.png)

leads to this

![image](https://user-images.githubusercontent.com/83225309/120895359-d3385380-c61c-11eb-9e8d-2cac73903d0e.png)

as expected. But this

![image](https://user-images.githubusercontent.com/83225309/120895720-91a8a800-c61e-11eb-95ae-96958ea72e5c.png)

leads this

![image](https://user-images.githubusercontent.com/83225309/120895309-a2f0b500-c61c-11eb-8d6b-6b0de4cd32c0.png)

As you can see, the second section is shown twice and former first section is gone.
When there are suggested videos, they are shown on top, but still the former first section is replaced by a copy of the second section.

![image](https://user-images.githubusercontent.com/83225309/120895645-42fb0e00-c61e-11eb-98a0-80812de135c5.png)

When Suggested is sorted below the other sections like this

![image](https://user-images.githubusercontent.com/83225309/120895769-ca488180-c61e-11eb-8869-c8f3dcbbfad7.png)

it's like Suggested wasn't activated

![image](https://user-images.githubusercontent.com/83225309/120895884-4a6ee700-c61f-11eb-8cc2-8c24f49a0ee0.png)

Server is Ubuntu 20.04, updated today and AVideo is 11.1 and was also updated today.

**Comment by DanielnetoDotCom** [comment]
Hi, 

are you talking about suggested categories or suggested videos?

the "sections" you are talking about are categories?

**Comment by gunthor-hammerwurf** [comment]
Hello,

sorry I called everything sections, I try to explain it again. For me it's only about suggested videos, since I don't have suggested categories.

Without having suggested anything and without having activated showing Suggested, it looks like this

![image](https://user-images.githubusercontent.com/83225309/120895359-d3385380-c61c-11eb-9e8d-2cac73903d0e.png)

Now in the sorting of Gallery 

![image](https://user-images.githubusercontent.com/83225309/121135641-ffc6b800-c834-11eb-8644-89e2cc222b65.png)

I activate the section Suggested and have it sorted on top like this

![image](https://user-images.githubusercontent.com/83225309/121135701-0e14d400-c835-11eb-9e23-e70c721e8f97.png)

Then on the first page, the former first category is gone and the second category is shown twice. At this time, I don't have any videos suggested, I just activated the section Suggested.

![image](https://user-images.githubusercontent.com/83225309/120895309-a2f0b500-c61c-11eb-8d6b-6b0de4cd32c0.png)

Now in I suggest a video. Then on the first page, the category/section with the suggested video appears on top, below there's the former second category twice and still the former first category is gone.

![image](https://user-images.githubusercontent.com/83225309/120895645-42fb0e00-c61e-11eb-98a0-80812de135c5.png)

But when in sorting the sections for Gallery, the section Suggested is sorted below the activated sections like this

![image](https://user-images.githubusercontent.com/83225309/120895769-ca488180-c61e-11eb-8869-c8f3dcbbfad7.png)

it appears as if the section Suggested wasn't activated at all.

![image](https://user-images.githubusercontent.com/83225309/120895884-4a6ee700-c61f-11eb-8cc2-8c24f49a0ee0.png)

I also tried to suggest a video first and afterwards activating the section Suggested, but that doesn't change the behavior.

**Comment by DanielnetoDotCom** [comment]
I am not sure if this will fix the issue, but can you please try this update?

**Comment by gunthor-hammerwurf** [comment]
That did the trick, thank you very much. The suggesting section now behaves as expected.
