### ISSUE TITLE
Latest git pull all videos display script......HELP

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5272]
@DanielnetoDotCom 
![Screenshot_20210606-034547_Samsung Internet](https://user-images.githubusercontent.com/70327833/120920056-1a086680-c67a-11eb-9240-63ab53f260b6.jpg)

**Comment by milehighkaraoke** [comment]
To fix this I had to shut off gallery and turn on yophptube plug in. Reason I had gallery as first page combined with phpflix is because I like the live link that is displayed on the first page of the gallery

**Comment by milehighkaraoke** [comment]
No combination is working. What is up with this
@DanielnetoDotCom 
![Screenshot_20210606-050816_Samsung Internet](https://user-images.githubusercontent.com/70327833/120922278-6dcc7d00-c685-11eb-97f1-906376e5b50f.jpg)

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom  I gotta get this functional for my show tonight. Please let me know what's going on with this

**Comment by milehighkaraoke** [comment]
totally blank error log when it does this
array(4) { ["type"]=> int(1) ["message"]=> string(483) "Uncaught Error: Attempt to assign property "videoStartSeconds" on string in /var/www/MHKTube/plugin/PlayerSkins/PlayerSkins.php:77 Stack trace: #0 /var/www/MHKTube/view/include/video.php(6): PlayerSkins::getMediaTag() #1 /var/www/MHKTube/view/modeYoutubeTop.php(23): require('...') #2 /var/www/MHKTube/view/modeYoutubeBundle.php(8): require('...') #3 /var/www/MHKTube/view/modeYoutube.php(390): require('...') #4 /var/www/MHKTube/view/index.php(36): require('...') #5 {main} thrown" ["file"]=> string(51) "/var/www/MHKTube/plugin/PlayerSkins/PlayerSkins.php" ["line"]=> int(77) }

**Comment by DanielnetoDotCom** [comment]
Hi, for some reason I guess you are not running the latest. 

please try a git pull again.

**Comment by DanielnetoDotCom** [comment]
Anyway I just sent an update that may prevent a similar error

**Comment by milehighkaraoke** [comment]
Fixed it thank you

**Comment by milehighkaraoke** [comment]
When 1st page is set to gallery this is still appearing. I am updated withe the latest git pull
![Screenshot_20210607-222728_Samsung Internet](https://user-images.githubusercontent.com/70327833/121123087-d596db00-c7df-11eb-9e6f-5fd2498db18f.jpg)

**Comment by milehighkaraoke** [comment]
I will just let it set so you can see what it is doing. Click on any video and you get the script
www.mhktube.com

**Comment by milehighkaraoke** [comment]
I turned the phptube plugin back on so it works for my customers but I really would like to have the gallery mode working. Thanks

**Comment by DanielnetoDotCom** [comment]
Hi

the main problem is that I cannot reproduce this error. so I am not sure where it comes from.

I am also using the gallery plugin

**Comment by milehighkaraoke** [comment]
All plugins have been re downloaded so I have the newest paid plugins. I did the sudo reset that you recommended but absolutely nothing is fixing this. Is there a way for me to roll back the gitpull from 2 days ago?  Only combination that slightly works is under design choose theme Netflix first page style needs to have both Netflix and gallery turned on and the youphpflix2 plugin enabled.   If it is anything but this combination it is a no go. 
Would you like to make account and I will give you admin privileges so you can see better what this is doing on this end?

**Comment by milehighkaraoke** [comment]
![20210608_135829](https://user-images.githubusercontent.com/70327833/121249772-2e0ebc80-c862-11eb-833a-d6783b67fb38.jpg)

**Comment by milehighkaraoke** [comment]
That fixed everything thank you @DanielnetoDotCom
