### ISSUE TITLE
Old Embed links from a few weeks and back no longer work need redirect for new embed please

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5273]
I am getting reports from users saying videos they embedded over a year ago is no longer working and reason is the embed link has changed. Can u please include a redirect from the old style to the new style please and thanx.

**Comment by JoshWho** [comment]
Seems like when using the new video seo link it no longer goes off the old video id anymore.

New embed style
`<div class="embed-responsive embed-responsive-16by9"><iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="https://www.joshwhotv.com/vEmbed/.QG8lwg" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no"></iframe></div>`

Old EMbed with video id
`<iframe width="560" height="315" style="max-width: 100%;max-height: 100%; border:none;" src="https://www.joshwhotv.com/vEmbed/30664" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no">iFrame is not supported!</iframe>`

**Comment by JoshWho** [comment]
Need some 301 redirects to fix this, this is also making a whole bunch of my old links in google search all stop working.

**Comment by DanielnetoDotCom** [comment]
Did you set this in your configuration.php??

`$global['makeVideosIDHarderToGuessNotDecrypted'] = 1;`

**Comment by JoshWho** [comment]
No didn't know that was a option.

**Comment by JoshWho** [comment]
@DanielnetoDotCom  I do not even see that anywhere in my config.php file

**Comment by JoshWho** [comment]
I do have it enabled but I want both to work. I have people that have the new video ids embedded and I have people with the old ones embedded. How can I make the old links still work?

**Comment by DanielnetoDotCom** [comment]
Hi, I found the issue, and your site is updated now

the video https://www.joshwhotv.com/vEmbed/.QG8lwg is the same as https://www.joshwhotv.com/vEmbed/41620

**Comment by JoshWho** [comment]
Thank you works great now!!! 😀
