### ISSUE TITLE
Cannot create Meet conference with Hebrew Title

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5275]
When trying to create a conference and give it an Hebrew text title I cannot access that room only in english titles or characters will this work.

![Screen Shot 5781-09-27 at 17 08 13](https://user-images.githubusercontent.com/58882903/121031699-4247b080-c7b3-11eb-82ff-0f7cc769d3cc.jpg)
![Screen Shot 5781-09-27 at 17 06 12](https://user-images.githubusercontent.com/58882903/121031706-44aa0a80-c7b3-11eb-8e38-148be9fe2633.jpg)

**Comment by DanielnetoDotCom** [comment]
please give me a sample title name

**Comment by guymass** [comment]
it can be any name doesn't really matter which one or more hebrew words you will use. Try translating something on google and than use that to create a meet and see if it allows you to enter the room.
