### ISSUE TITLE
Twitterbot being blocked by something can't render Twitter Card for video post

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5276]
![d73f3a6d-7afc-4aa4-8f9e-336d8874f16a](https://user-images.githubusercontent.com/39392449/121037664-3e953900-c775-11eb-8b0d-49212bf8801a.png)

URL is https://www.joshwhotv.com/v/.QG8inQ?channelName=SeekingTheTruth

**Comment by DanielnetoDotCom** [comment]
check your logs, maybe it is blocking by the bots block

**Comment by JoshWho** [comment]
I am not seeing anything in the server log or error log when I run the link in the twitter dev debugger. I am not sure it could be the bot script.

Twitter's ip for their bot is 




Netblock | Description | Num IPs
-- | -- | --
103.252.112.0/23 | 60 Robinson Road, # 11-02 BEA Building, Singapore 068892. | 512
103.252.114.0/23 | 60 Robinson Road, # 11-02 BEA Building, Singapore 068892. | 512
104.244.40.0/24 | Twitter Inc. | 256
104.244.41.0/24 | Twitter Inc. | 256
104.244.42.0/24 | Twitter Inc. | 256
104.244.44.0/24 | Twitter Inc. | 256
104.244.45.0/24 | Twitter Inc. | 256
104.244.46.0/24 | Twitter Inc. | 256
104.244.47.0/24 | Twitter Inc. | 256
185.45.5.0/24 | Twitter International Company | 256
185.45.6.0/23 | Twitter International Company | 512
192.133.76.0/22 | Twitter Inc. | 1,024
192.133.76.0/23 | Twitter Inc. | 512
192.44.69.0/24 | Crashlytics, Inc | 256
199.16.156.0/22 | Twitter, Inc. | 1,024
199.16.156.0/23 | Twitter, Inc. | 512
199.59.148.0/22 | Twitter Inc. | 1,024
199.96.56.0/23 | Twitter Inc. | 512
199.96.56.0/24 | Twitter Inc. | 256
199.96.57.0/24 | Twitter Inc. | 256
199.96.58.0/23 | Twitter Inc. | 512
199.96.60.0/23 | Twitter Inc. | 512
199.96.60.0/24 | Twitter Inc. | 256
199.96.61.0/24 | Twitter Inc. | 256
199.96.62.0/23 | Twitter Inc. | 512
202.160.128.0/24 | Twitter Asia Pacific Pte. Ltd. | 256
202.160.129.0/24 | Twitter Asia Pacific Pte. Ltd. | 256
202.160.130.0/24 | Twitter Asia Pacific Pte. Ltd. | 256
202.160.131.0/24 | Twitter Asia Pacific Pte. Ltd. | 256
209.237.192.0/24 | Twitter Inc. | 256
209.237.193.0/24 | Twitter Inc. | 256
209.237.194.0/24 | Twitter Inc. | 256
209.237.195.0/24 | Twitter Inc. | 256
209.237.196.0/24 | Twitter Inc. | 256
209.237.197.0/24 | Twitter Inc. | 256
209.237.198.0/24 | Twitter Inc. | 256
209.237.199.0/24 | Twitter Inc. | 256
209.237.200.0/24 | Twitter Inc. | 256
209.237.201.0/24 | Twitter Inc. | 256
209.237.203.0/24 | Twitter Inc. | 256
209.237.204.0/24 | Twitter Inc. | 256
209.237.205.0/24 | Twitter Inc. | 256
209.237.206.0/24 | Twitter Inc. | 256
209.237.207.0/24 | Twitter Inc. | 256
209.237.208.0/24 | Twitter Inc. | 256
209.237.209.0/24 | Twitter Inc. | 256
209.237.210.0/24 | Twitter Inc. | 256
209.237.211.0/24 | Twitter Inc. | 256
209.237.212.0/24 | Twitter Inc. | 256
209.237.213.0/24 | Twitter Inc. | 256
209.237.214.0/24 | Twitter Inc. | 256
209.237.215.0/24 | Twitter Inc. | 256
209.237.216.0/24 | Twitter Inc. | 256
209.237.217.0/24 | Twitter Inc. | 256
209.237.218.0/24 | Twitter Inc. | 256
209.237.219.0/24 | Twitter Inc. | 256
209.237.220.0/24 | Twitter Inc. | 256
209.237.221.0/24 | Twitter Inc. | 256
209.237.222.0/24 | Twitter Inc. | 256
209.237.223.0/24 | Twitter Inc. | 256
64.63.0.0/18 | MoPub, Inc. | 16,384
64.63.32.0/24 | MoPub, Inc. | 256
64.63.33.0/24 | MoPub, Inc. | 256
69.195.160.0/24 | Twitter Inc. | 256
69.195.162.0/24 | Twitter Inc. | 256
69.195.163.0/24 | Twitter Inc. | 256
69.195.164.0/24 | Twitter Inc. | 256
69.195.165.0/24 | Twitter Inc. | 256
69.195.166.0/24 | Twitter Inc. | 256
69.195.168.0/24 | Twitter Inc. | 256
69.195.169.0/24 | Twitter Inc. | 256
69.195.171.0/24 | Twitter Inc. | 256
69.195.174.0/24 | Twitter Inc. | 256
69.195.175.0/24 | Twitter Inc. | 256
69.195.176.0/24 | Twitter Inc. | 256
69.195.177.0/24 | Twitter Inc. | 256
69.195.178.0/24 | Twitter Inc. | 256
69.195.179.0/24 | Twitter Inc. | 256
69.195.180.0/24 | Twitter Inc. | 256
69.195.181.0/24 | Twitter Inc. | 256
69.195.182.0/24 | Twitter Inc. | 256
69.195.185.0/24 | Twitter Inc. | 256
69.195.186.0/24 | Twitter Inc. | 256
69.195.187.0/24 | Twitter Inc. | 256
69.195.188.0/24 | Twitter Inc. | 256
69.195.189.0/24 | Twitter Inc. | 256
69.195.190.0/24 | Twitter Inc. | 256
69.195.191.0/24 | Twitter Inc. | 256

**Comment by DanielnetoDotCom** [comment]
I mean maybe AVideo is blocking.  you may find something on Apache or Avideo log

I just checked the demo site and it is working

![image](https://user-images.githubusercontent.com/18009293/121362768-bc3f7d00-c90c-11eb-8bee-983a529a5458.png)

**Comment by DanielnetoDotCom** [comment]
I found you need to add Twitter in your whitelist on the configuration.php

`$global['stopBotsWhiteList'] = array('google','bing','yahoo','yandex', 'twitter');`

**Comment by JoshWho** [comment]
Thank you Working great
