### ISSUE TITLE
Timeout from site exceeded on player

### ISSUE THREAD

**Issue by 54wbvy54** [WWBN/AVideo#5278]
Hi dear AVideo creator please help me ! Thanks
I have a question. Not so long ago I created a server on your AVideo platform to show video.

Мy question is how to fix iframe problem . When i take iframe from my 34.75.178.29 AVideo server and publish this video on another site on the player, show me this (Timeout for response from site 34.75.178.29.)

What can i do thank you dear creator ?
If I'M doesn't right explains you i can send you a screenshot

Thanks you have a nice day

**Comment by DanielnetoDotCom** [comment]
timeout means your site 34.75.178.29 was not reachable.

you may also have problems regarding secure content. you cannot mix HTTP and HTTPS sites
