### ISSUE TITLE
Strange Image on Home Page

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5280]
This just happened suddenly I get this image appearing on the top Home page I am not sure where it came from.
This is the DIV:

![Screen Shot 5781-09-27 at 22 07 01](https://user-images.githubusercontent.com/58882903/121075163-88196e80-c7dd-11eb-9065-411f7f05d72c.jpg)

This is the image with the squares:

![Screen Shot 5781-09-27 at 22 11 59](https://user-images.githubusercontent.com/58882903/121075229-9bc4d500-c7dd-11eb-80f1-f0e6073b024d.jpg)

**Comment by DanielnetoDotCom** [comment]
Make sure you uncheck this

![image](https://user-images.githubusercontent.com/18009293/121177893-4c5dc380-c834-11eb-8fd3-38d6221c5fa2.png)

**Comment by guymass** [comment]
OK found it thank you. A quick question regarding this banner, can it be changed? can we put a slider in its place?

**Comment by akhilleusuggo** [comment]
This option is kinda useless. Just disable it. Activate the banner only on user profile, not on videos. It's laggy to load on every video, take too much bandwidth and also decrease the page load/SEO. It just got no purpose.
