### ISSUE TITLE
embed code for trailer in youphptube

### ISSUE THREAD

**Issue by aliceglitch** [WWBN/AVideo#5283]
Hi, I want to copy and save the embed code from another site in the ''embed code for trailer'' field of my site. But it is not saved in the my site youphptube. Why? thanks

![9](https://user-images.githubusercontent.com/72448881/121192071-ce280e00-c881-11eb-912c-053012ebd2a1.jpg)

**Comment by DanielnetoDotCom** [comment]
I see, I guess the name on this field is wrong, it should call embed link NOT code

I will send an update.

**Comment by aliceglitch** [comment]
> I see, I guess the name on this field is wrong, it should call embed link URL NOT code
> 
> I will send an update.
