### ISSUE TITLE
Eu atualizei o avideo e apareceu o seguinte erro no aws

### ISSUE THREAD

**Issue by gabrielmais** [WWBN/AVideo#5284]
array(4) { ["type"]=> int(1) ["message"]=> string(122) "Cannot redeclare Aws\constantly() (previously declared in /var/www/thykrontv/objects/aws/aws-sdk-php/src/functions.php:20)" ["file"]=> string(54) "/var/www/thykrontv/plugin/AWS_S3/aws/Aws/functions.php" ["line"]=> int(19) }

**Comment by DanielnetoDotCom** [comment]
Aparentemente seu plugin AWS_S3 está desatualizado.

Confirme se você está com o AWS_S3 na versão 4.0

**Comment by gabrielmais** [comment]
bom no sftp /plugins/AWS_S3 eu renomeei como .old ai consegui abrir a plataforma..... porem se eu tento colocalo colocalo normal ele ainda da esse erro. Eu teria que baixar o plugiin novamente pelo site de venda ou teria como fazelo pelo plataforma ?

**Comment by DanielnetoDotCom** [comment]
exato, tem que baixar novamente.
