### ISSUE TITLE
[Bug Characterized] Not seeing edits to category pages when changing images

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5286]
**Describe the bug**
It has been driving me crazy that when I edit categories to add images, the images do not show up in the browser. I have determined that it is the browsers aggressively caching the image URLs.

**To Reproduce**
1. Load a /cat page in the browser
2. Go to the category editor
3. Edit the image
4. Go back to the /cat page in the browser
5. Observe that you do not see any changes
6. Quit and relaunch the browser, and reload the same /cat page
7. Observe that you do not see any changes
6. Clear your browser cache (Safari: Develop->Empty Caches)
7. Reload the /cat page
8. Observe your changes

**Expected behavior**
The browser not to be so aggressive about caching. Is there a way to inform the browser that these pages ought not be cached so hard?

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by walt93** [comment]
Fixed.
