### ISSUE TITLE
YPTSorage video not found

### ISSUE THREAD

**Issue by HESSEBO** [WWBN/AVideo#5287]
Hi, 
I have this issue when I move a video file to my YPTStorage server in a remote location. The videos seem to move successfully and is there when I check, but after playing it, the remote server gives me an error message which states that video is not found. I did all the necessary  configuration and both my streamer and YPTstorage plugin is up to date.  After I did some code investigation  and log review I concluded that the path in the streamer page points to a folder with name of the video and looking to the video inside it, but originally the videos inside YTPStorage server gets created with no folder. 
May be the attachment can you better. 

![tempsnip2](https://user-images.githubusercontent.com/43477304/121303434-bc874a80-c903-11eb-9887-00a67eb21cca.png)

![Capture3](https://user-images.githubusercontent.com/43477304/121304124-9f06b080-c904-11eb-8b7e-e4916447d53e.PNG)

**Comment by DanielnetoDotCom** [comment]
Hi, I just checked on the demo site, storage, and seems to work even without create the folder.

please make sure you have the mod_rewrite enabled on the storage server.

**Comment by HESSEBO** [comment]
I did and it's giving me: Module rewrite already enabled
I hope there's other suggestions as I am exhausted trying all the possible solutions that I know.

**Comment by DanielnetoDotCom** [comment]
can you please share the video link so I can take a deeper look?

**Comment by HESSEBO** [comment]
https://myegy3.ddns.net/video/26/%D8%B2%D9%88%D8%AC-%D8%AA%D8%AD%D8%AA-%D8%A7%D9%84%D8%B7%D9%84%D8%A8---zoog-taht-el-talab

here you go. 
Notice that if I copy the link and go to the website the page is not found, but if I remove the folder link from the copied link it's called and gets downloaded.

**Comment by DanielnetoDotCom** [comment]
Hi, I suspect your mod_rewrite or the xsendfile is not properly configured on the storage

please check this https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

**Comment by DanielnetoDotCom** [comment]
Create a folder is not a solution, it really should work without it

Did you make a `git pull` on the Storage site?

**Comment by DanielnetoDotCom** [comment]
I just sent an update to help debug.

you will update your site and you will try to access the URL https://storage.yoursite.com/test

for example https://storage1.avideo.com/test

this should download a file successtest.txt

If download it is all fine and the error is not the mod_rewrite or the xsendfile if does not download you have a problem with one of those modules.

**Comment by HESSEBO** [comment]
So it worked on one storage servers and the other didn't, what I did, I copied the xsend related field in the .htaccess file and pasted it on the storage server .htaccess file that's not worked and the videos worked fine. 

but after moving files from the streamer to the storage server some smaller files get moved ok larger do not. 
I already modified upload_max and post_max to 8G. 

here are the logs that I got:

Start (Local to Site) Transfer of (502) zoogaat muttalakat
Found 5 files to transfer
3 - Start Transfer of mp4_240 file
moveFromLocalToSiteVideo: Sending request to the Site https://ej.ddns.net/storage_volume/str1/post.json.php?secret=d4cff43f83e7041f08509dkk3dfcef9&video_url=https%3A%2F%2Fytts.ddns.net%2Fvideos%2Fvideo_210610011729_0d19%2Fvideo_210610011729_0d19_240.mp4&filesize=
moveFromLocalToSiteVideo: Download done
moveFromLocalToSiteVideo: {"error":false,"msg":"","youPHPTubeStorageURL":"https:\/\/ej.ddns.net\/storage_volume\/str1\/","filename":"\/var\/www\/YouPHPTube\/storage_volume\/str1\/videos\/video_210610011729_0d19_240.mp4"}
moveFromLocalToSiteVideo: {"error":false,"msg":"","returned":false,"json":"{\"error\":false,\"msg\":\"\",\"youPHPTubeStorageURL\":\"https:\\\/\\\/ej.ddns.net\\\/storage_volume\\\/str1\\\/\",\"filename\":\"\\\/var\\\/www\\\/YouPHPTube\\\/storage_volume\\\/str1\\\/videos\\\/video_210610011729_0d19_240.mp4\"}"}
Replacing mp4_240 with Dummy File
3 - Start Transfer of mp4_480 file
moveFromLocalToSiteVideo: Sending request to the Site https://ej.ddns.net/storage_volume/str1/post.json.php?secret=d4cff43f83llllkjhj9d5bb3dfcef9&video_url=https%3A%2F%2Fytts.ddns.net%2Fvideos%2Fvideo_210610011729_0d19%2Fvideo_210610011729_0d19_480.mp4&filesize=
moveFromLocalToSiteVideo: Download done
moveFromLocalToSiteVideo: Error on URL https://ej.ddns.net/storage_volume/str1/post.json.php?secret=d4cff43f83e7041f085kjj9&video_url=https%3A%2F%2Fytts.ddns.net%2Fvideos%2Fvideo_210610011729_0d19%2Fvideo_210610011729_0d19_480.mp4&filesize=

the video files are three files but I only see 2, the one with largest size seemed to be rejected by the storage server due to big capacity which is 1.8G

**Comment by HESSEBO** [comment]
I tried to move another video files but it seems like they start to move but after a while they get interrupted. I checked them on the storage server they are all available but when I dive into the code in the chrome I can see there's 2 files embeded to the streamer and the other two embeded to the storage server. so it looks like the streamer does not know that all the files have moved to the storage server.

**Comment by HESSEBO** [comment]
Any body has any idea what's going on?

**Comment by akhilleusuggo** [comment]
> the video files are three files but I only see 2, the one with largest size seemed to be rejected by the storage server due to the big size which is 1.8G

Both servers must have 

> upload_max and post_max to 8G.

Another thing to note, make sure your apache log file doesn't reject the transfer just because you don't have signed certificate.

**Comment by DanielnetoDotCom** [comment]
Hi, I agree the SSL may be an issue but looks like it works for 240p (smaller file) and fails for 480p (check the file size)

you said this " I copied the xsend related field in the .htaccess". please make sure you do not copy anything. you MUST use `git clone` and `git pull` to handle installation/updates

Also, make sure you do not use any proxy (including cloudflare), it may give you file transfer problems.

**Comment by HESSEBO** [comment]
Thanks for respond and good to have you back guys. I actually use Nginx proxy server to distribute and hand ssl certificates on both (the remote and local servers) the reason for that I have multiple servers in each location so it distributes the loads and website handling. so is it possible that it could be causing this problem?

**Comment by HESSEBO** [comment]
Yeah, you were right buddy. sure the problem was on Nginx proxy server manager. What I did I disabled the Nginx proxy server from my router and directed the traffic to apache server directly , then I uploaded 2Gb file to my streamer and moved it the YPTSorage  server and it worked. I guess I'm gonna dive deep on my Nginx proxy server manager to see where's the problem at. If you have any experience regarding this matter please let me know as using Nginx proxy server in my network is inevitable. 

here's how the Nginx server looks :

![here's how the server looks](https://user-images.githubusercontent.com/43477304/122205510-fd093a00-cea8-11eb-9ae5-291bdf3279d2.PNG)

**Comment by DanielnetoDotCom** [comment]
> Thanks for respond and good to have you back guys. I actually use Nginx proxy server to distribute and hand ssl certificates on both (the remote and local servers) the reason for that I have multiple servers in each location so it distributes the loads and website handling. so is it possible that it could be causing this problem?

I am pretty sure that is the problem, but I guess you can resolve it with some Nginx configuration

**Comment by DanielnetoDotCom** [comment]
> Yeah, you were right buddy. sure the problem was on Nginx proxy server manager. What I did I disabled the Nginx proxy server from my router and directed the traffic to apache server directly , then I uploaded 2Gb file to my streamer and moved it the YPTSorage server and it worked. I guess I'm gonna dive deep on my Nginx proxy server manager to see where's the problem at. If you have any experience regarding this matter please let me know as using Nginx proxy server in my network is inevitable.
> 

Awesome this works. I am pretty sure there is some configuration to bypass it.
