### ISSUE TITLE
Allow/Disallow user uploads and other permissions

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5289]
Hi Daniel,

We have now many users on the site and at times we need to be able to edit all the users to not allow Video Upload and only allow it for selected users. Because over time we tested also ldap access and other options on the site, we have all sorts of users which some have the option enabled and some don't, and the process of going through thousands of users each one to check what state of permission they have is a very hard task. We need a way to do this if needed for all the users, so we can if we need to reset the whole permission state for uploading and streaming (I have seen there is an option for that), so we can select all the users and apply the new state to all of them. Then we can go and select those specific users who have the permission to upload. This would really help us manage the user's permission easier and faster.

**Comment by DanielnetoDotCom** [comment]
Try to run this MySQL command 

`````
UPDATE `users` SET `canUpload` = '0' WHERE (`id` > 0);
`````

**Comment by guymass** [comment]
Thanks, that worked great!
