### ISSUE TITLE
Double Live Stream when using Publish Stream

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5290]
When we use publish stream to set a stream for a future time, when the user starts the stream it auto connects to that set timer, however now I see the live stream appearing twice on the front page, one is from the publish and the other is the normal live stream.

![Screen Shot 5781-09-29 at 20 31 45](https://user-images.githubusercontent.com/58882903/121402038-1880bc00-c962-11eb-81e3-032e815460eb.jpg)

Maybe we are not using it properly or that there is an issue and there should only be left the one from the publish stream.

**Comment by DanielnetoDotCom** [comment]
I guess it is correct, you have one stream running now and another one scheduled for the future

**Comment by guymass** [comment]
But does the one scheduled for the future is going to start by its own? or does it recognize when the user start its stream and that it should combine them to a single one. How does it work? does the use need to wait until the timer is up to start his stream?

**Comment by DanielnetoDotCom** [comment]
none of it, you  will need to start it manually (if it is not a Livelink) and your schedule has to match with the live start time

**Comment by guymass** [comment]
OK understood
