### ISSUE TITLE
Live link not showing in homepage

### ISSUE THREAD

**Issue by mishcazzulani** [WWBN/AVideo#5291]
hello it seems i can't get live links working: i can add the link without errors, but it doesn't show on the homepage

you can check my test server at https://rl.webpulse.it

**Comment by DanielnetoDotCom** [comment]
please screenshot so I can understand what links are you talking about

**Comment by mishcazzulani** [comment]
![live-link](https://user-images.githubusercontent.com/52744187/121526170-6e547300-c9f9-11eb-8164-af3b2d99e08d.png)

**Comment by DanielnetoDotCom** [comment]
I guess the livelink only appears on the gallery style

but to see the notification on the top you will need the live plugin

**Comment by mishcazzulani** [comment]
thank you very much! i switched to gallery style, installed the live plugin and now it works!
