### ISSUE TITLE
Com a atualização para 11.1 meu encoder paraou de funcionar 

### ISSUE THREAD

**Issue by gabrielmais** [WWBN/AVideo#5292]
O seguinte erro esta constando no encoder 

SELECT f.*, e.* FROM encoder_queue e LEFT JOIN formats f ON f.id = formats_id WHERE (status = 'encoding' OR status = 'downloading' OR status = 'queue' OR status = 'error') ORDER BY priority ASC, e.id ASC \nError : ()

**Comment by DanielnetoDotCom** [comment]
você tem que compatilhar mais informações do seu log.

mas nitidamente é algo relacionado ao seu banco de dados.
