### ISSUE TITLE
Distance between objects on mobile

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#5293]
Hi together,

My users arent happy with the distance between the rows inside the categories.

The text from the upper objects are nearer on the following row than on the one which they belong too:

![Screenshot_20210611-094819_Edge.jpg](https://user-images.githubusercontent.com/50199132/121658142-55070180-caa1-11eb-9606-c6a9ac1037f3.jpg)

Is it changeable? Because the first look on the page is confusing like this.

**Comment by morbificagent** [comment]
On other screensizes its ok 🤷‍♂️

![Screenshot_20210611-114103_Edge.jpg](https://user-images.githubusercontent.com/50199132/121666833-fa25d800-caa9-11eb-942e-02ce83f51a05.jpg)

**Comment by DanielnetoDotCom** [comment]
I am not sure what type of mobile you are using and this is not happening here 

![image](https://user-images.githubusercontent.com/18009293/121685854-d2794480-ca96-11eb-9584-65952621c314.png)

but you always can add a custom CSS and change distances (You MUST know CSS)

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css

**Comment by morbificagent** [comment]
Uh i am not firm in css...

Could you give me a hint how to do that?
