### ISSUE TITLE
Purchased plugins

### ISSUE THREAD

**Issue by theshm00** [WWBN/AVideo#5296]
I have a strange problem, I bought 3 plugins (LiveUsers, VideoResolutionSwitcher and Customize).  My Avideo version is 11.1. All three purchased plugins say that new versions are available. When I download them from https://youphp.tube/marketplace/ and upload them to my Avideo I get no error but the plugins are not updated.  For example my "Customize" plugin still says version: @1.0 and that version v1.3 is available.

I am not sure how to update the plugins. Do I have a rights problem for the uploaded files? 

How can I make sure that the plugins are installed or how can I debug why the new plugin versions are not installed? I am grateful for any suggestion.

**Comment by DanielnetoDotCom** [comment]
It looks like a file permission problem.

try to change the folder permissions or manually delete the plugin then upload it again

**Comment by theshm00** [comment]
Thanks for your quick help, I deleted in the /plugins directory and in the plugin-updates directory the VideoResolutionSwitcher plugin directory. After that I uploaded the plugin again.  The plugin still has the version: @1.0. 

I unzipped the zip file which I can download from https://youphp.tube/marketplace/, in the VideoResolutionSwitcher.php it says * Crypted 2018-04-19 10:55:02

I seem to be able to download only an old version from https://youphp.tube/marketplace/.  Can it be that something is wrong with my account (user #2752)?

**Comment by DanielnetoDotCom** [comment]
Hi, I did not mean the plugin directory, I mean delete only the plugin

but I guess you are right, due to a bug it was providing you the older version, please download now and you should get the newest one

**Comment by theshm00** [comment]
Hi Daniel thanks for your help, I just tried again to re-download the 3 plugins. However, I still get the old versions.

**Comment by DanielnetoDotCom** [comment]
can you please double-check?

I download it here and seems to be correct

**Comment by theshm00** [comment]
Hello Daniel, I was able to solve the problem with your help. Now the correct plugin files are transferred. However, it did not work for me to simply upload the plugins via the upload plugin button. In this case the old plugin version remained, I had to manually delete the respective plugin directories. After that the upload worked and I now see the correct 
plugin versions. Thanks for your support!
