### ISSUE TITLE
Hide password protected videos

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#5298]
I had configured that password protected videos are hidden from the Gallery and the search i think...

I thought it was made by these two options:

![Screenshot_20210611-231940_Edge.jpg](https://user-images.githubusercontent.com/50199132/121750301-69ccaf00-cb0c-11eb-8c71-9c7cf56826f3.jpg)![Screenshot_20210611-232014_Edge.jpg](https://user-images.githubusercontent.com/50199132/121750306-6b967280-cb0c-11eb-9521-6db49483e7e1.jpg)

But even if they are configured like this the password protected videos are displayed in my gallery with an big red lock on it:

![Screenshot_20210611-095512_Edge.jpg](https://user-images.githubusercontent.com/50199132/121750400-9b457a80-cb0c-11eb-98f4-42750e5c0c42.jpg)

Or do i understand this options wrong and they arent for password protected files?

If so, would it be possible to hide them too?

**Comment by akhilleusuggo** [comment]
It will show up to you if you're connected. Try disconnected

**Comment by DanielnetoDotCom** [comment]
I guess currently the password-protected is not filtered as private videos.

**Comment by morbificagent** [comment]
ok, i have removed the possibility to password-protect files anyway. The users started to upload strange things with passwords ;-)
