### ISSUE TITLE
User_Controll plugin shows no ip

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#5299]
Bought the User_Controll plugin and trying to ban a user.

But when i click on ban it shows this:

![Screenshot_20210612-065817_Firefox.jpg](https://user-images.githubusercontent.com/50199132/121765589-4aee0d00-cb4c-11eb-9d9e-dc053267a060.jpg)

It is correct that the ip list is empty?

Have tested it with some other users but its the same there.

Looks like it doesnt work

**Comment by DanielnetoDotCom** [comment]
Hi

it will start to register login IPs only after the installation.
it will register the IPs on the login attempt, so it is normal to not have any IP now
