### ISSUE TITLE
Hide green lock symbol

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#5300]
Hi together,

I have disabled the possibility to make password protected files on my site now.

So i dont need the symbol of the lock on the bottom of the Videos because all will be green for sure:

![IMG_20210612_071805_524.jpg](https://user-images.githubusercontent.com/50199132/121765997-3eb77f00-cb4f-11eb-9de7-0ae555e94254.jpg)

Is there any option to hide them?

**Comment by DanielnetoDotCom** [comment]
Try to hide it with a custom CSS 

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css

```
.galeryDetails .label-success{
    display:none;
}
```

**Comment by morbificagent** [comment]
Not sure if i did anything wrong but this doesnt helps:

![image](https://user-images.githubusercontent.com/50199132/121898370-99093900-cd23-11eb-9aea-7c0e799c4f01.png)

**Comment by DanielnetoDotCom** [comment]
Seems fine to me. did you clear the cache?

**Comment by morbificagent** [comment]
yes i did... cache folder + first site cache + all my cdn cache

**Comment by DanielnetoDotCom** [comment]
What is your site URL, please let me check it directly

**Comment by morbificagent** [comment]
https://bit-link.de

Many Thanks Daniel

**Comment by DanielnetoDotCom** [comment]
I see, try this 

```
.galeryDetails .label-success {
    display: none !important;
}
```

**Comment by morbificagent** [comment]
Great! Its working ;-)
