### ISSUE TITLE
Which Server provider would be best for Avideo Live Streaming

### ISSUE THREAD

**Issue by nikstream** [WWBN/AVideo#5301]
Hi Daniel

If I need to cater 10 to 12  live adoptive streams per day with 5 thousand user per stream at 1.5 mb for HD
what server hardware or service provider  would be required for Avideo.

**Comment by DanielnetoDotCom** [comment]
Hi, I cannot tell you the numbers, I really recommend you to start with the best you can and upgrade/add servers if you need.

But please read this

https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements
