### ISSUE TITLE
Edit LDAP View

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5303]
I would like to edit the LDAP view on the login page to add some text info and a link to inform users. I see this plugin is encrypted. Would it be possible to maybe add another info text field on the plugin to serve as a text area where I can put in some HTML info?

We wish to make the distinction more cleared to our users as we have now decided to allow them to choose if they wish to use our LDAP or just use the native one.

![Screen Shot 5781-10-02 at 20 09 27](https://user-images.githubusercontent.com/58882903/121784028-2f215000-cbba-11eb-953f-88ea3de490da.jpg)

The complete login page look like this, the welcome should be above and I think maybe if you allow us to edit its text to enter some important info that would be great.

![Screen Shot 5781-10-02 at 20 13 44](https://user-images.githubusercontent.com/58882903/121784133-dacaa000-cbba-11eb-9382-00b56a182ea1.jpg)

**Comment by DanielnetoDotCom** [comment]
Try to add a custom CSS https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css

```
.loginPage  div.panel-footer.text-right > .text-muted{
    font-size: 1.5em;
    color: #000;
    font-weight: bold;
}
```
