### ISSUE TITLE
Websocket not connecting

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5304]
Web socket not connecting
After doing the installation web socket is not connecting. I was told by milehighkaraoke by ( You need to get your nginx configured with a listen 444) but it is listening. After running codes
php /var/www/AVideo/plugin/YPTSocket/test.php
&
php /var/www/AVideo/plugin/YPTSocket/server.php
This is what I got. can someone help me with this. I feel I was abandoned at the end of my project by milehighkaraoke... All good.
@DanielnetoDotCom can you help thansk

**Screenshots**
![php-test](https://user-images.githubusercontent.com/37937968/121790765-b5d12f80-cbb0-11eb-84df-fb7cc2a0f16e.png)
![php-Servert](https://user-images.githubusercontent.com/37937968/121790781-ee710900-cbb0-11eb-8850-593a836a5421.png)

**Comment by milehighkaraoke** [comment]
#4964

**Comment by DanielnetoDotCom** [comment]
Looks like you do not have a secure connection. make sure you properly install the certifiactes
