### ISSUE TITLE
edit database from terminal disableNativeSignIn

### ISSUE THREAD

**Issue by TheCazz** [WWBN/AVideo#5305]
Hi
I have install the latest YouPHPTube and is very nice and works fine.
I did try to disable people to create a account but I did also make so I can't login.
I think I have to change disableNativeSignIn to false again.
But I can't find it in the MariaDB and not sure where to look.

**Comment by TheCazz** [comment]
A update
I did find it in plugins in MariaDB but even when I edit and set it false I still get "Welcome back!" when I trying to login.
I know I did change some else but not sure what :)

**Comment by DanielnetoDotCom** [comment]
Hi, you can reset your plugins here 


```
cd /var/www/html/AVideo/
$ php resetPlugins.php
1 - Reset all plugins Parameters
2 - Reset CustomizeUser Plugin Parameters only
3 - Reset all plugins (Will also inactivate the plugins)
Choose an option:

```

you may want to choose option 2
