### ISSUE TITLE
Storage warning even when the Videos are stored on 3rd Party Storage

### ISSUE THREAD

**Issue by rielcomms** [WWBN/AVideo#5306]
System is connected to cloud storage but still prompts with  diskspace usage warning. Videos are supposedly stored in the 3rd party storage. Any ideas please?
![disk_usage_message](https://user-images.githubusercontent.com/46077574/121819135-ccc36080-cc48-11eb-9a3e-00c75be98c27.png)

**Comment by akhilleusuggo** [comment]
It's just a warning. For now there's no option to disable it.
The warning flags when you have lower then 15% left on the disk , and the number is below 50GB. ( local only )

https://github.com/WWBN/AVideo/blob/6c1c3a134461ad08269b812005a68239f52a2044/objects/functiondiskUsageBars.php#L27

**Comment by DanielnetoDotCom** [comment]
Also, 5 GB is a bit of space to handle videos.

remember in many cases we need to copy the video file to the streamer before send to external storage (S2, B2, FTP, etc)

**Comment by rielcomms** [comment]
I think it is more than a warning because now I can no longer login to the server so its no longer possible to upload or import videos.

**Comment by DanielnetoDotCom** [comment]
check if your disk is not full

try to keep at least 50 GB free

try to restart your server, this will delete your tmp files

**Comment by rielcomms** [comment]
Thanks it is resolved now, the restart of the server fixed it.

**Comment by rielcomms** [comment]
> Also, 5 GB is a bit of space to handle videos.
> 
> remember in many cases we need to copy the video file to the streamer before send to external storage (S2, B2, FTP, etc)

The who system has run out of space. Videos are saved in the c,loud but no one can logon to the servre again

**Comment by DanielnetoDotCom** [comment]
check your cache folder, also your /tmp folder.

you may need a larger hard drive to handle all the site processes.

**Comment by rielcomms** [comment]
> check your videos/cache folder (delete it), also your /tmp folder.
> 
> you may need a larger hard drive to handle all the site processes.

Is this the correct path? /var/www/html/YouPHPTube/videos

**Comment by DanielnetoDotCom** [comment]
almost, try this ...


`rm -R /var/www/html/YouPHPTube/videos/cache/`
