### ISSUE TITLE
One line for subscribers

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#5307]
Hello to you
This is the first time I'm writing here I'm using the Avideo platform
Under the name live528 (with Guy)
I would be happy for a response from you
Is there an option in any way to display the list of channels I subscribe to
In one line in the gallery (for example a video for each channel or the channel name) and not each channel in a separate cloumn?
Or alternatively is it possible to create a tab where you can see the list of List of channels I subscribe to?
Thank you very much Eitan

**Comment by DanielnetoDotCom** [comment]
Currently, we do not have this page, but for sure it will be added in the future.

**Comment by eitanwa** [comment]
Hello
Thanks for the quick response
