### ISSUE TITLE
Random channels

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#5308]
Hello to you
When I go in to watch a particular video
The following videos will always be from the same channel at random
Is there a possibility that the following videos will be shown from other channels
Somehow
For example related videos and so on
Or will the next video show always be from the same channel?
![photo_2021-06-13_22-25-36](https://user-images.githubusercontent.com/85537931/121819548-551c2280-cc96-11eb-89f4-515cd2248252.jpg)
Thank you very much Eitan

**Comment by DanielnetoDotCom** [comment]
Try to uncheck this 

![image](https://user-images.githubusercontent.com/18009293/121898946-51ba8280-ccfa-11eb-8a04-d8719ebae6e3.png)

**Comment by eitanwa** [comment]
Hi
I tried and it remains as the previous situation

**Comment by eitanwa** [comment]
Hi
Okay so I found that if I close this banner As shown in the screenshot
Then videos will appear randomly of the entire platform and not just the channel of the selected video
Now the question is Where is this plugin located That I can cancel it permanently?
Thank you
eitan

![1](https://user-images.githubusercontent.com/85537931/121947776-1f8f3c00-cd5f-11eb-89f8-abad8bbc30fe.jpg)

**Comment by DanielnetoDotCom** [comment]
Is this also unchecked?

![image](https://user-images.githubusercontent.com/18009293/122051352-e2f12e00-cdba-11eb-850c-b78c0b544bb3.png)

**Comment by eitanwa** [comment]
HEY DANIEL
yes it is
