### ISSUE TITLE
APIName=video_file does not work

### ISSUE THREAD

**Issue by tbryantAE** [WWBN/AVideo#5309]
So we are trying to use APIName=video_file in API and we only get an error.

https://video.americonictv.com/plugin/API/get.json.php?APIName=video_file&videos_id=1&APISecret=b50659819eb61ceae567ecd5dd51ea31

Please look for yourself.

What we are trying to do is get a list of the thumbnails on videos that are a part of a series.  If you use 

https://video.americonictv.com/plugin/API/get.json.php?APIName=video_from_program&playlists_id=658&APISecret=b50659819eb61ceae567ecd5dd51ea31

It lists the series and the video files belonging to it but no thumbnails.   How do we get the thumbnails for videos in the series?

**Comment by DanielnetoDotCom** [comment]
I could confirm the bug, I am not sure exactly what was it, but here is a fix that will resolve that issue.

**Comment by tbryantAE** [comment]
So what is the fix?  Updating the core code again or can I just update the API plugin?

**Comment by DanielnetoDotCom** [comment]
You MUST make a git pull. do not update files separately.
