### ISSUE TITLE
Restream disconnects Automatically under heavy load have to restart stream to get restream to reconnect

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5310]
Any way we can make the restream function in headless mode? 

Basically a way to keep functioning even if it thinks I disconnected from it. 

Make a manual "End Stream" Button option in the live dashboard.

**Comment by DanielnetoDotCom** [comment]
what exactly is your idea?

what is happening to disconnect your live??

I do not have anything on the script to auto disconnect it unless the live is done.

**Comment by JoshWho** [comment]
It seems like it is looking for the hangup of nginx like when I normally disconnect obs. Is there a way to make it ignore that and keep streaming until we click end stream?

**Comment by DanielnetoDotCom** [comment]
the restream is an FFMPEG command, FFMPEG control when to disconnect.

I am not aware of any way to manually disconnect.

**Comment by JoshWho** [comment]
What tells the ffmpeg to hangup?

**Comment by DanielnetoDotCom** [comment]
Sorry I really do not know

**Comment by JoshWho** [comment]
I will try some different config and see what I get from it. Could have been the drop idle publisher

**Comment by JoshWho** [comment]
Yes it was the drop idle publisher.  Just set it for x amount of seconds and the problem is solved my case is i just made it 900 seconds
