### ISSUE TITLE
Home page loads slow for logged in users that are subscribed to more than 20 channels

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5312]
There is a big large wait for channel video data to show on the home page of logged in users that have more than 20 channels subscribed to. Is there anyway to asnyc load these or something we can cache to make this not a live grab ever time they load home page?

**Comment by DanielnetoDotCom** [comment]
can you please email me a user with 20+ channels so I can look it directly in your site?

**Comment by JoshWho** [comment]
I sent it to u on Hangouts

**Comment by DanielnetoDotCom** [comment]
This update may use the infinity scroll and load 4 at a time

**Comment by JoshWho** [comment]
I ran the update but have no fast computer to see it on at the moment, could you tell me if it is freezing for you on the homepage now. My browser locks up when it tries loading more channels when I scroll down.

**Comment by JoshWho** [comment]
OK just figured out the latest update is not working with the Gallery Limits set for channel.

It is now trying to load every video of each channel on the home page

**Comment by JoshWho** [comment]
OK just figured out the latest update is not working with the Gallery Limits set for channel.

It is now trying to load every video of each channel on the home page

![be469d4d-031e-4ae0-8234-01f0cb42c65c](https://user-images.githubusercontent.com/39392449/122327956-5f3b5c80-cef4-11eb-8e53-49b4f85e33b8.png)

![505c2e50-5282-4d39-92ea-a933e66d7956](https://user-images.githubusercontent.com/39392449/122328092-a295cb00-cef4-11eb-8603-3d21e3c5fc05.png)

**Comment by JoshWho** [comment]
I disabled subscribers right now in the Gallery setting to prevent users from getting IP banned for loading too many files per page.

**Comment by DanielnetoDotCom** [comment]
I guess it is fixed now, please confirm

**Comment by JoshWho** [comment]
Yes works beautifly now. Thank you @DanielnetoDotCom
