### ISSUE TITLE
Failed to add translation

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5315]
Failed to add translation
![image](https://user-images.githubusercontent.com/47063171/122367863-66fc0f00-cf8f-11eb-9290-b3b491d08c72.png)

![image](https://user-images.githubusercontent.com/47063171/122368358-db36b280-cf8f-11eb-830c-55f2452d6878.png)

![image](https://user-images.githubusercontent.com/47063171/122368633-16d17c80-cf90-11eb-8bb1-f2b0fea876af.png)

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by chenjian9885** [comment]
Thank you

**Comment by chenjian9885** [comment]
Adding multiple translations is invalid
![image](https://user-images.githubusercontent.com/47063171/122457772-976c9900-cfe1-11eb-972b-caf0ae46a105.png)
![image](https://user-images.githubusercontent.com/47063171/122457844-af441d00-cfe1-11eb-9b6c-4729d4434123.png)
![image](https://user-images.githubusercontent.com/47063171/122459574-a94f3b80-cfe3-11eb-8350-64b1477ae464.png)
![image](https://user-images.githubusercontent.com/47063171/122459711-d0a60880-cfe3-11eb-9805-d36054e8ecd8.png)
![image](https://user-images.githubusercontent.com/47063171/122459859-05b25b00-cfe4-11eb-8f8e-53f29e02148c.png)

**Comment by chenjian9885** [comment]
Hope to support us to customize and add translation content
