### ISSUE TITLE
[Live streaming] Pasting links to live stream /live/0/Channelname the OpenGraph image tag -> image says "OFFLINE"

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5319]
**Describe the bug**
While streaming, I want to paste links to a live stream, so people might click on the link. The OG tag is pulling an image that suggests the stream is not live. At the time I'm doing this, the stream is live.

**To Reproduce**
1. Go through steps to start a live stream
2. Verify the stream is running by loading its url (i.e. https://conspyre.tv/live/0/VeritasWorldNews)
3. Copy/paste that URL into someplace (i.e. Telegram,  iPhone Messages, ...)
4. See image indicating the stream is offline

**Expected behavior**
1) (best) A keyframe ripped from the live stream in near-realtime. 
2) (ok) An image that says "On-line". 
3) (sub-optimal) No image. 
4) (current behavior) Detracts from use in real-time

**Screenshots**
Telegram:
![Screen Shot 2021-06-18 at 10 51 56 PM](https://user-images.githubusercontent.com/11711050/122632467-cccbc200-d087-11eb-8b19-92c10ffd7e5a.png)

 Messages:
![Screen Shot 2021-06-18 at 10 54 49 PM](https://user-images.githubusercontent.com/11711050/122632591-a8bcb080-d088-11eb-9e91-db59ce61ca34.png)

**Comment by DanielnetoDotCom** [comment]
can you please make a `git pull`/update and try again?

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform
