### ISSUE TITLE
Live thumbs does not always stay the same size

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5321]
any way we can just make them scale down to the same dimensions?

![275525dc-5fae-46df-bf40-d339fd7e8b83](https://user-images.githubusercontent.com/39392449/122637001-eb46b300-d0b1-11eb-869f-828b6ec0a54f.png)

**Comment by JoshWho** [comment]
Weird how sometimes it happens and sometimes it doesn't.

**Comment by DanielnetoDotCom** [comment]
Correct, I must timeout the thumbs to avoid slow down (even more) the thumbs

I really want to improve the auto live thumbs for the live. I may release something regarding this soon

**Comment by DanielnetoDotCom** [comment]
This update may improve the live thumbnails

**Comment by JoshWho** [comment]
Thank you that seems to have fixed it.
