### ISSUE TITLE
How do i find the Live link HLS .m3u8 on you tube?

### ISSUE THREAD

**Issue by GarethBagley** [WWBN/AVideo#5322]
Hi there!
I want to post a live link on my site, that is also live on youtube.
I need to add a live link in the format HLS .m3u8 on my side but i cannot find this feature/link format on youtube. The normal share links don't work.
Can anybody help me find these links i need?

Thanks//

**Comment by DanielnetoDotCom** [comment]
Hi

I do not think is possible to get the m3u8 from youtube.
the option you have is to stream to your site and restream to youtube

check this https://github.com/WWBN/AVideo/wiki/Live-Plugin#restream

**Comment by GarethBagley** [comment]
Ok! A big thankyou for your help.From which site can i post a live link?https://stackoverflow.com/questions/35140737/how-to-get-live-m3u8-files-rather-than-dvr-m3u8-files-of-youtube-live-streamsGareth Bagley, ***@***.***
-------- Originalmeddelande --------Från: Daniel Neto ***@***.***> Datum: 2021-06-20  12:54  (GMT+01:00) Till: WWBN/AVideo ***@***.***> Kopia: GarethBagley ***@***.***>, Author ***@***.***> Ämne: Re: [WWBN/AVideo] How do i find the Live link HLS .m3u8 on you tube? (#5322) 
Hi
I do not think is possible to get the m3u8 from youtube.
the option you have is to stream to your site and restream to youtube
check this https://github.com/WWBN/AVideo/wiki/Live-Plugin#restream

**Comment by DanielnetoDotCom** [comment]
usually, public/free ones are not good and no guarantee will work.

An important thing is for you to make sure the link users HTTPS and does not have a cors block policy.

this feature is designed for you to use with the m3u8 links that you control, not public ones which you may have problems/changes with no warning.

**Comment by GarethBagley** [comment]
Sure. But what can i use livelinks for?I don't understand this feature. Gareth Bagley, ***@***.***
-------- Originalmeddelande --------Från: Daniel Neto ***@***.***> Datum: 2021-06-20  14:19  (GMT+01:00) Till: WWBN/AVideo ***@***.***> Kopia: GarethBagley ***@***.***>, Author ***@***.***> Ämne: Re: [WWBN/AVideo] How do i find the Live link HLS .m3u8 on you tube? (#5322) 
usually, public/free ones are not good and no guarantee will work.
An important thing is for you to make sure the link users HTTPS and does not have a cors block policy.
this feature is designed for you to use with the m3u8 links that you control, not public ones which you may have problems/changes with no warning.

**Comment by DanielnetoDotCom** [comment]
You can use it for any m3u8 link 

I guess your problem is because you do not know where you can find one to use

**Comment by GarethBagley** [comment]
Yes exactly. Gareth Bagley, ***@***.***
-------- Originalmeddelande --------Från: Daniel Neto ***@***.***> Datum: 2021-06-20  15:38  (GMT+01:00) Till: WWBN/AVideo ***@***.***> Kopia: GarethBagley ***@***.***>, Author ***@***.***> Ämne: Re: [WWBN/AVideo] How do i find the Live link HLS .m3u8 on you tube? (#5322) 
You can use it for any m3u8 link
I guess your problem is because you do not know where you can find one to use
