### ISSUE TITLE
PLugin Subtitle Switcher não esta funcionando corretamente.

### ISSUE THREAD

**Issue by jonathanalvez** [WWBN/AVideo#5323]
**Describe the bug**
Na primeira instalação parecia tudo ok, porem para outras pessoas logadas a legenda não funcionava.
Agora aparece um erro ao tentar fazer qualquer coisa com o plugin.

Meu cliente comprou o plugin e não consegue usar, poderiam me ajudar a ajuda-lo nisso?

Ele pretende investir no app porem acha o suporte um problema e eu tambem não sei se posso recomendar pra ele fazer esse investimento.

Uncaught ReferenceError: addSubtitle is not defined
    at HTMLButtonElement.onclick (?page=videos:1)
onclick @ ?page=videos:1

?page=videos:1 Uncaught ReferenceError: createSubtitle is not defined
    at HTMLButtonElement.onclick (?page=videos:1)

**Comment by DanielnetoDotCom** [comment]
por favor tira um print da tela que vc está tendo o erro

tambem verifique se seu streamer está atualizado

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform
