### ISSUE TITLE
PWA missing Java Worker

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5325]
https://www.joshwhotv.com/manifest.json

I do not see a error on Java Worker in the manifest, browser doesn't see it is a PWA

![PWA-install-option-in-Omnibox-in-Chrome](https://user-images.githubusercontent.com/39392449/122658654-99477100-d135-11eb-97d2-6bd9acec1cd9.png)

go to my news site https://www.joshwho.net and you will see the install option.

**Comment by JoshWho** [comment]
Not sure if it is the call to the worker or what but it just seems like it is missing something from the avideo version

**Comment by JoshWho** [comment]
`{"short_name":"JoshWho TV | Free Speech Video Live Stream","name":"JoshWho TV | Free Speech Video Live Stream","description":"JoshWho TV | Free Speech Video Live Stream","icons":[{"src":"https:\/\/joshwho-cdn.com\/videos\/faviconPWA72.png","type":"image\/png","sizes":"72x72"},{"src":"https:\/\/joshwho-cdn.com\/videos\/faviconPWA96.png","type":"image\/png","sizes":"96x96"},{"src":"https:\/\/joshwho-cdn.com\/videos\/faviconPWA120.png","type":"image\/png","sizes":"120x120"},{"src":"https:\/\/joshwho-cdn.com\/videos\/faviconPWA128.png","type":"image\/png","sizes":"128x128"},{"src":"https:\/\/joshwho-cdn.com\/videos\/faviconPWA144.png","type":"image\/png","sizes":"144x144"},{"src":"https:\/\/joshwho-cdn.com\/videos\/faviconPWA152.png","type":"image\/png","sizes":"152x152"},{"src":"https:\/\/joshwho-cdn.com\/videos\/faviconPWA180.png","type":"image\/png","sizes":"180x180"},{"src":"https:\/\/joshwho-cdn.com\/videos\/faviconPWA192.png","type":"image\/png","sizes":"192x192"},{"src":"https:\/\/joshwho-cdn.com\/videos\/faviconPWA384.png","type":"image\/png","sizes":"384x384"},{"src":"https:\/\/joshwho-cdn.com\/videos\/faviconPWA512.png","type":"image\/png","sizes":"512x512"}],"start_url":"https:\/\/www.joshwhotv.com\/","background_color":"#000000","display_override":["window-control-overlay","minimal-ui"],"display":"fullscreen","scope":"\/","related_applications":[{"platform":"play","url":"https:\/\/play.google.com\/store\/apps\/details?id=mobile.youphptube.com"},{"platform":"itunes","url":"https:\/\/apps.apple.com\/us\/app\/youphptube\/id1337322357"}]}`

This is the manifest I see it grabbing from  https://www.joshwhotv.com/manifest.json

Is it the related app thing breaking it?

**Comment by JoshWho** [comment]
This is what I think it might be missing"

Promoting installation #
To indicate your Progressive Web App is installable, and to provide a custom in-app install flow:

Listen for the beforeinstallprompt event.
Save the beforeinstallprompt event, so it can be used to trigger the install flow later.
Alert the user that your PWA is installable, and provide a button or other element to start the in-app installation flow.
The beforeinstallprompt event, and the appinstalled event have been moved from the web app manifest spec to their own incubator. The Chrome team remains committed to supporting them, and has no plans to remove or deprecate support. Google's Web DevRel team continues to recommend using them to provide a customized install experience.

Listen for the beforeinstallprompt event #
If your Progressive Web App meets the required installation criteria, the browser fires a beforeinstallprompt event. Save a reference to the event, and update your user interface to indicate that the user can install your PWA. This is highlighted below.
https://web.dev/customize-install/#listen_for_beforeinstallprompt

**Comment by JoshWho** [comment]
Here is code to make it work: https://web.dev/codelab-make-installable/

**Comment by JoshWho** [comment]
I wonder if a simple java link for pwa install might work, or does it have to be with the builtin worker?

**Comment by JoshWho** [comment]
Just my wordpress one https://www.joshwho.net

**Comment by DanielnetoDotCom** [comment]
I guess I could do

**Comment by JoshWho** [comment]
It works now. Terrific It ask me even on Desktop if I want to install. THis is excellent, thank you @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Awesome, in the future, I will add a popup requesting installation.

**Comment by lunar54** [comment]
can we get a way to disable this and since this is installing on a device shouldn't there be a user agreement pop as well wit it?
