### ISSUE TITLE
Autoplay Video on Load Page

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#5327]
1-Autoplay Video on Load Page option can not be disabled.

2-Also, there's a problem with this option. It is supposed to be a browser policy, but seems like also when it's enabled, does also enable autoplay "next video" a.k.a Up NextAutoplay

**Comment by DanielnetoDotCom** [comment]
If you have a cookie set up to autoplay it overwrites your configuration.

clear the cookies and try again, autoplay should be disabled

**Comment by akhilleusuggo** [comment]
I'm talking about the site configuration tab. Can not enable/disable. 

![image](https://user-images.githubusercontent.com/52116577/122735321-98beef80-d287-11eb-8cba-86ff62ab442d.png)

So, the control place is not anymore on the SiteConfiguration tab, but rather on the next videos page...

Try to change the setting from there.

**Comment by DanielnetoDotCom** [comment]
Thanks, this may fix the issue

**Comment by akhilleusuggo** [comment]
I though this bug was ignored. Thanks @DanielnetoDotCom
