### ISSUE TITLE
Any way we can add the Theme YouPHPTube Navigation left bar  to the Gallery theme?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5328]
I would love to be able to have like the combination of the both, Gallery home page but with the YouPHPTbe page body .

Mainly would love for the Left Navigation to be open on desktop view on the home page.

Just for the Homepage and user created pages.  Make nav hide on video play.

I would really like the Left Navigation to be open by default and it doesn't look right doing that with the Gallery theme.

I no longer have the old YouPhPtube theme anymore i think you discontinued it but it looked so much more professional with the static Left Navigation.

**Comment by JoshWho** [comment]
![f9f588d3-0de6-4320-aeb1-0246947514db](https://user-images.githubusercontent.com/39392449/122892961-7cfd2d00-d30b-11eb-84e9-27d0c1ca52c2.png)

**Comment by DanielnetoDotCom** [comment]
For sure I may add this in the future
