### ISSUE TITLE
Cyborg Theme Video Description is Black Text on Dark Background

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5329]
![download (3)](https://user-images.githubusercontent.com/39392449/122889728-a799b680-d308-11eb-9781-d299f66a6b11.png)

**Comment by JoshWho** [comment]
![cyborg png pagespeed ce _fjAIAOgPc](https://user-images.githubusercontent.com/39392449/122897514-b20b7e80-d30f-11eb-8aa3-287b1f4899f4.png)

**Comment by JoshWho** [comment]
for now I just setup a style atrrib

```
body {
    font-family: "Roboto","Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 14px;
    line-height: 1.42857143;
    color: #000;
}
```

**Comment by JoshWho** [comment]
The themes need separate tags for each theme so we can define custom edits to each one without it affecting the other themes.

**Comment by DanielnetoDotCom** [comment]
This should be changed on each css file directly and sent as a pull request.

I am sending some updates to handle the texts

**Comment by JoshWho** [comment]
where can u edit the css files at?

**Comment by DanielnetoDotCom** [comment]
I already sent you an update for the cyborg.

maybe I still missing something. you need to add the CSS directly into the file 

https://github.com/WWBN/AVideo/blob/master/view/css/custom/cyborg.css

**Comment by JoshWho** [comment]
Will that get overtten with new git pulls?

**Comment by DanielnetoDotCom** [comment]
> Will that get overtten with new git pulls?

that is why when you change it you make a pull request, so it will be always on the master branch

**Comment by JoshWho** [comment]
Not quite understanding it, I am still getting use to the git pull stuff

**Comment by DanielnetoDotCom** [comment]
check this https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

probably is the best solution for you

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom

**Comment by JoshWho** [comment]
Ok I think I sent a pull request

**Comment by DanielnetoDotCom** [comment]
yes approved

**Comment by JoshWho** [comment]
YAY

**Comment by JoshWho** [comment]
i need to make some more changes to it will submit later tonight
