### ISSUE TITLE
AD_Server Advertising Manager NOT WORKING

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5331]
When I click on the Advertising Manager button I get this page as an error.
Can you tell me why it doesn't work?
How can I fix this error?
Thanks for your suggestions.

![1](https://user-images.githubusercontent.com/82677269/122962550-d3a74d00-d385-11eb-9054-457e887bdccf.PNG)

![2](https://user-images.githubusercontent.com/82677269/122962561-d6a23d80-d385-11eb-89c8-2db105819aa1.PNG)

**Comment by DanielnetoDotCom** [comment]
can you please make a git pull on your site?
I could not reproduce it on demo site

**Comment by peterflitz** [comment]
Pop-up blocker is switched off / deactivated for your website?

**Comment by sharknetwork24** [comment]
After giving the git pull command it now works perfectly.
Thanks Daniel
