### ISSUE TITLE
Xsendfile ERROR: Not Exist!

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5334]
This also keeps showing up constantly and is causing the log file to get over filled with these messages:

 AVideoLog::DEBUG: XSENDFILE ERROR: Not exists /var/www/html/AVideo/videos/v_210622093055_0b98/v_210622093055_0b98_Low.mp4 SCRIPT_NAME: /view/xsendfile.php
[22-Jun-2021 23:10:50 Asia/Jerusalem] AVideoLog::DEBUG: XSENDFILE ER

**Comment by DanielnetoDotCom** [comment]
Make sure XSendfile is installed correctly otherwise it may slowdown a lot your site 

https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

**Comment by guymass** [comment]
my config is set as follows:


<Directory /var/www/html/AVideo/>
        DirectoryIndex index.php
        XSendFile on
        XSendFilePath /var/www/html/AVideo/
        Options +FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

these two are set in main apache.conf
    Order Allow,Deny
    Allow from All

**Comment by DanielnetoDotCom** [comment]
I am not sure what is misconfigured on your side

check this https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

**Comment by guymass** [comment]
Actually since yesterday this message was gone so it also could be the issue of permissions or maybe some or the config options we tested, I am closing this as our config seems to be fine.
