### ISSUE TITLE
Support the same video and add multiple categories

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5336]
Hope to support one video and add multiple categories
For example, the categories of a movie are: action, science fiction, and horror, which cannot be realized on the current website.
![image](https://user-images.githubusercontent.com/47063171/123152314-0856f980-d497-11eb-8327-5c95338344f6.png)

**Comment by walt93** [comment]
I've run into the same issue. Suggest that you can achieve a similar result using Tags.

**Comment by chenjian9885** [comment]
Yes, now I can only use video tags
