### ISSUE TITLE
on the default screen after log in-have the upload button separately 

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#5337]
on the default screen after log in-have the upload button separately 

Have the latest version of the application

![image](https://user-images.githubusercontent.com/65802024/123174674-1eb48380-d49e-11eb-9e43-f53f759abb14.png)
![image](https://user-images.githubusercontent.com/65802024/123174744-40156f80-d49e-11eb-974e-dc11afab585f.png)

Please help

**Comment by DanielnetoDotCom** [comment]
Not sure how this happens

try to make sure your plugins are also up to date and make sure you clear the AVideo cache.

**Comment by vraghavans** [comment]
Dear daniel,

Noted ,any specific Plugin you are refering to as self have updated all plugins and cleared cache many times.

Rgds

**Comment by DanielnetoDotCom** [comment]
I do not know what plugin is this, I am just saying you may forget some.
as long as I cannot reproduce it I cannot help you

**Comment by vraghavans** [comment]
Dear Daniel,

Noted, will update all plugins and revert
Rgds
Vijay

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vraghavans** [comment]
Good Day,

I have checked and it is because of the bulk embed plugin-if it is active the above option comes below the top menu,

Also i have noticed that the custom top menu i had configured in the plugin has disappeared after the update,Please help

Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
please try to reproduce it on demo site, otherwise I can only asume you have outdated files

**Comment by vraghavans** [comment]
Good Day,i tried on the demo site,the bulk embed plug in by default disabled,andthe bulk embed is already present in the top menu .
Activating the bulk embed menu does not make any changes in the top menu.
![image](https://user-images.githubusercontent.com/65802024/123487022-c52d8f80-d62a-11eb-8ed9-fc2fc03e44f7.png)
Please advise
Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
Hi, I can only assume you do not have the correct files.

did you update with a git pull?

if yes try to run this instead 

`sudo git fetch --all && sudo git reset --hard origin/master`

**Comment by vraghavans** [comment]
Good Day,

Have done as instructed .

root@server:/var/www/html/YouPHPTube# sudo git fetch --all && sudo git reset --hard origin/master
Fetching origin
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/DanielnetoDotCom/YouPHPTube
   0e23f85d2..b688a8a98  master     -> origin/master
HEAD is now at b688a8a98 clearfix
root@server:/var/www/html/YouPHPTube# git pull
Already up to date.
root@server:/var/www/html/YouPHPTube#

However still the same issues,My purchased plugins are also not updating

**Comment by DanielnetoDotCom** [comment]
You must download the purchased plugins again (all of them) on marketplace 

manually delete the plugin and upload it again

**Comment by vraghavans** [comment]
All the plugins deleted and installed again.
Also ran the command as advised and below is the result.
++++++
root@server:~# sudo git fetch --all && sudo git reset --hard origin/master
fatal: not a git repository (or any of the parent directories): .git
root@server:~#
++++++
Please advise

**Comment by DanielnetoDotCom** [comment]
clearly, to me, you are having a problem with your git.

Sorry but if you cannot update I cannot help you.

what I can recommend to you is to make a clean installation.

**Comment by vraghavans** [comment]
good day,yes for me it is YouPHPTube
root@server:/var/www/html/YouPHPTube# sudo git fetch --all && sudo git reset --hard origin/master
Fetching origin
HEAD is now at 6999a95d5 Avoid error

Please advise

**Comment by DanielnetoDotCom** [comment]
If you add any custom code, remove it.

I am not sure where your error comes from.

**Comment by vraghavans** [comment]
Dear Daniel,
I have not added any custom code,
am not sure why this error is coming.
Will you able to take a look please,i can request for a session
rgds
vijay

**Comment by DanielnetoDotCom** [comment]
You can hire me for 1 hour and I can check where does it come from.

**Comment by vraghavans** [comment]
okies noted,
will send you a mail,
thanks
