### ISSUE TITLE
Clickable Categories Under Top Nav  to Make it Easier for users to browse the Content

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5340]
Just like how YT does theirs would make it easier for users to browse.

![01f43657-0d81-48e8-bed3-d96978acaeb8](https://user-images.githubusercontent.com/39392449/123258433-fb4b0200-d4b8-11eb-993a-be007f9d7a61.png)

I got something similar I did with just Link texts added to my CustomADvance UnderMenu box but it shows on every page. Would like this to be a built in feature that only shows on the Gallery home page or category page

![download (1)](https://user-images.githubusercontent.com/39392449/123258719-4a913280-d4b9-11eb-9e5a-b62843fcccfe.png)

**Comment by JoshWho** [comment]
Other option would be if you could just add a Under Menu Box on the Gallery theme so it will only show on the home page.

**Comment by JoshWho** [comment]
I made them buttons now

![aa81ce79-16a7-4987-9e9b-654584a305a4](https://user-images.githubusercontent.com/39392449/123411505-25162e80-d576-11eb-96a8-3a9bda1cd6bb.png)

**Comment by DanielnetoDotCom** [comment]
Thanks for the idea, I am sending an update that may do the trick

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/123650169-b567a400-d800-11eb-84b8-57f981c76e9e.png)

You may enable/disable this option here

**Comment by JoshWho** [comment]
Nice, just did the update and looks great. Any way we can change the container width to be just in the center block space and not the whole width across?

Like in this outline
![123258719-4a913280-d4b9-11eb-9e5a-b62843fcccfe](https://user-images.githubusercontent.com/39392449/123735818-859eb780-d865-11eb-8b21-4d9e9347c7be.png)

**Comment by JoshWho** [comment]
This is how it looks currently 

![1a009f81-4822-46ef-857e-fb8d5c957ce0](https://user-images.githubusercontent.com/39392449/123735942-c7c7f900-d865-11eb-95d5-2f9b0f4f0822.png)

**Comment by DanielnetoDotCom** [comment]
I guess all in one row if better, you may have hundreds of categories and it may take a large space at the top

sorry but I will keep one row only

**Comment by JoshWho** [comment]
Yes still keep it 1 row I am just talkinging about the container width. It is like 100% from the left to the right, there a way you can center it like how I had the links just in the center? Still just 1 row 

![5ea7a9c0-d40d-4ebe-b9cd-1d0010819c76](https://user-images.githubusercontent.com/39392449/123794103-18604600-d8a8-11eb-9a1c-2e76e716935c.png)

**Comment by JoshWho** [comment]
![77514b6b-b9e6-4359-bd97-3d8b750a11dd](https://user-images.githubusercontent.com/39392449/123794783-df74a100-d8a8-11eb-9c5b-32bd48676dab.png)

**Comment by JoshWho** [comment]
It looks great, Just wanted to center it instead of it going to the edges of the page on Desktop view.

**Comment by DanielnetoDotCom** [comment]
I see, I just do not agree center or reduce width will be better.

but you can add a custom CSS to reduce the width

**Comment by JoshWho** [comment]
Like how youtube's is

![123258433-fb4b0200-d4b8-11eb-993a-be007f9d7a61](https://user-images.githubusercontent.com/39392449/123861376-b675ff80-d8ec-11eb-805f-a2fe563da4c1.png)

**Comment by JoshWho** [comment]
For somereson I am seeing double arrows now on left and right

![download (2)](https://user-images.githubusercontent.com/39392449/123941209-8ddb1d80-d95f-11eb-9ab3-2515342a9862.png)


I do not see anything to hook css edits to to change the width of the container

**Comment by DanielnetoDotCom** [comment]
I am sending some finetuning to it, also an option to make the buttons row smaller


![image](https://user-images.githubusercontent.com/18009293/123986796-02807d00-d99d-11eb-931c-45ebcc8fb395.png)

**Comment by JoshWho** [comment]
Love it, looks beautiful. Thank you
