### ISSUE TITLE
Resolutions

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#5341]
Hello,

while I have turned off the high resolutions these continue to exist, any help for this? 
Thank you in advance!
Ilias

![resolutions](https://user-images.githubusercontent.com/60543030/123267556-70402b00-d4fd-11eb-83a1-ace08d39998e.jpg)
![resolutions1](https://user-images.githubusercontent.com/60543030/123267571-73d3b200-d4fd-11eb-81dd-b65d5f28b7ce.jpg)

**Comment by DanielnetoDotCom** [comment]
this will reflect only in new uploaded videos

**Comment by wetubeclub** [comment]
Thank you for your answer Daniel,
I will see it better and I will come back with newer ones about my question!!

Thank you
Ilias
