### ISSUE TITLE
Video showing the previouse video preview thumbnails

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5342]
After I watch a video and the next video loads it will still show the previous video preview thumbnails wile moving the mouse over the video to search for a location. Here is a screen shot.

![Screen Shot 5781-10-14 at 20 00 35](https://user-images.githubusercontent.com/58882903/123304057-25d3a400-d527-11eb-8b7d-df170c7d9885.jpg)

**Comment by guymass** [comment]
After refresh it goes back to showing the proper thumbs, but when videos load automatically they will keep the previous thumbs I think.

**Comment by akhilleusuggo** [comment]
I can confirm that.

**Comment by DanielnetoDotCom** [comment]
Does this happen on demo site?

Please make sure this option is unchecked

![image](https://user-images.githubusercontent.com/18009293/123668765-cf5db280-d811-11eb-8a7a-bce6f559aa1f.png)
