### ISSUE TITLE
How to use Block User

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5343]
Where can Block User be closed?
Where should I be clear about blocked users
![image](https://user-images.githubusercontent.com/47063171/123307003-8e854580-d554-11eb-983f-966c0cfb8d9e.png)

**Comment by DanielnetoDotCom** [comment]
If you block a user you will not see this user's content anymore. 

This feature is required to get approved on Apple store app

**Comment by chenjian9885** [comment]
Hello
My pc version, can I turn off this function

**Comment by DanielnetoDotCom** [comment]
Disable the ReportVideo plugin

**Comment by chenjian9885** [comment]
Thank you
