### ISSUE TITLE
Using channel pages for blog articles, the visual results leave a lot to be desired

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5344]
**Is your feature request related to a problem? Please describe.**
I'm trying a new thing, set up a user named "Blog" and started dumping articles into the user. Now I'd like to present these articles, and the results are not good.

**Describe the solution you'd like**
An alternate page layout, or an alternate layout for blog entries with proper contrast and layout to be legible.

**Describe alternatives you've considered**
Going completely outside of AVideo and setting up a blog. I already have that. It is not an integrated solution; I'd like to dump the blog and move it inside of AVideo, but, formatting issues… :-(

**Additional context**
![Screen Shot 2021-06-24 at 12 08 22 PM](https://user-images.githubusercontent.com/11711050/123319143-e3897300-d4e4-11eb-8b14-d8e9e8c14650.png)
(White text on white background, only shows one line of article subject and clips, multiple repeats of same icon conveys nothing, showing play indicator on top of distorted icon)

Selecting "Videos" changes some internal state; rendering is marginally better but a URL cannot be formed to go to this variant:
![Screen Shot 2021-06-24 at 12 10 23 PM](https://user-images.githubusercontent.com/11711050/123319368-2cd9c280-d4e5-11eb-9e8c-9357db4a4f19.png)

**Comment by DanielnetoDotCom** [comment]
Do you have some screenshots of ideas?
