### ISSUE TITLE
Direct upload issue after latest pull

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#5347]
When clicking direct upload, and cancelling the video record is not cleared, leaving a blank "automatically booked video"

**Comment by DanielnetoDotCom** [comment]
Looks like it is related to https://github.com/WWBN/AVideo/issues/5348

please reproduce it on demo site first

**Comment by millzee01** [comment]
same happens on demo site.

**Comment by millzee01** [comment]
After completing a git pull, the issue is resolved :-)
