### ISSUE TITLE
Embed issue after latest pull

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#5348]
If you embed a youtube video, then click direct upload, and click cancel, then the youtube video you just added is duplicated.

log into the test site as test user, and you will see duplicate videos and automatically booked videos.

**Comment by DanielnetoDotCom** [comment]
did you also reproduce it on demo site?

**Comment by millzee01** [comment]
yes, same happens on demo site.

**Comment by DanielnetoDotCom** [comment]
Thanks, I guess I found the problem
