### ISSUE TITLE
subpasta não esta recebendo o "/"

### ISSUE THREAD

**Issue by gabrielmais** [WWBN/AVideo#5349]
Consegui resolver o problema agora so tenho uma ultima coisa
como eu reenstalei o avideo eu mudei o pasta raiz para uma dentro do "site" em especifico.... nas configurações de instalação eu coloquei tudo certinho o site "http://imperialtv.com.br"/imperialrecord/" porem ele nao acha as "/" barras e fica como esta na imagem

![asfasf](https://user-images.githubusercontent.com/7960434/123420160-92838880-d591-11eb-81a7-014e478b242f.PNG)

todos os links estao indo dessa maneira "http://imperialtv.com.brimperialrecord/"

**Comment by DanielnetoDotCom** [comment]
edita o seu `videos/configuration.php` e adiciona a barra onde está faltando

procure pela variavel 
`$global['webSiteRootURL']`

**Comment by gabrielmais** [comment]
Opa obg pela ajuda e sim já havia feito isso mais ainda não resolveu o problema 

![sfasgasfasgasfasf](https://user-images.githubusercontent.com/7960434/123434244-a5eb1f80-d5a2-11eb-9a77-6f45d1bf6995.PNG)

**Comment by DanielnetoDotCom** [comment]
apaga a pasta videos/cache/

**Comment by gabrielmais** [comment]
eu consegui

$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME']."/".$subDir;

coloquei a barra entre o $server_name e o $subdir

**Comment by DanielnetoDotCom** [comment]
Não deveria precisar no $_SERVER['SERVER_NAME']

qual OS e versão PHP você está usando?

**Comment by gabrielmais** [comment]
ubunto 20 php 7.4

**Comment by DanielnetoDotCom** [comment]
realmente não deveria, mas ainda bem que está funcionando

**Comment by gabrielmais** [comment]
Obg ^^ Daniel tem alguma area de perguntas e ideias para futuras att ? 

Gostaria de saber se para cada canal terá giftcards e tambem a opção de ser membros do canal.

**Comment by DanielnetoDotCom** [comment]
Você pode usar o github para sugerir novas ideias.
