### ISSUE TITLE
webcam/meet erro

### ISSUE THREAD

**Issue by gabrielmais** [WWBN/AVideo#5350]
Olá eu não consigo ter acesso a audio e nem ao video do meet

![gasfasgasdfsfga](https://user-images.githubusercontent.com/7960434/123464313-08ecae80-d5c3-11eb-8af8-59572314f622.PNG)
![gasdgasdgsadg](https://user-images.githubusercontent.com/7960434/123464321-0ab67200-d5c3-11eb-8a0d-37737e90c184.PNG)

ele não da permissão eu acho ou não acha esses plugins

**Comment by DanielnetoDotCom** [comment]
seu site obrigatoriamente tem que ser https

**Comment by gabrielmais** [comment]
obg ^^
