### ISSUE TITLE
OpenGraph tags for /cat pages

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5351]
**Is your feature request related to a problem? Please describe.**
I'd like to drop links to /cat category pages on social media sites. When I do, I get the generic site OG tags. 

**Describe the solution you'd like**
OpenGraph tags to pull category artwork and description for /cat pages.

**Comment by DanielnetoDotCom** [comment]
This may improve the ogtag on the categories page

**Comment by walt93** [comment]
Still has issues.

1) If there is no image, a large black rectangle is displayed.
2) The description text is not used. Title is used for both title and description.

**Comment by DanielnetoDotCom** [comment]
> Still has issues.
> 
> 1. If there is no image, a large black rectangle is displayed.
> 2. The description text is not used. Title is used for both title and description.

Correct, that is what I expect to happen
