### ISSUE TITLE
Live stream don't show on the site

### ISSUE THREAD

**Issue by mostafaaalii** [WWBN/AVideo#5353]
I start live stream but in live page I'm still offline. I checked  rtmp it's working 
![20210627_192238](https://user-images.githubusercontent.com/72271443/123549716-67f72280-d77f-11eb-8064-3f9c42023b5a.jpg)

can it be happened  because I haven't hls plugin?

**Comment by mostafaaalii** [comment]
I checked test stats on live plugin
![Uploading 20210627_194341.jpg…]()

**Comment by DanielnetoDotCom** [comment]
I am pretty sure you are redirecting 

and your error is like those 

https://github.com/WWBN/AVideo/issues/3964
https://github.com/WWBN/AVideo/issues/3052
https://github.com/WWBN/AVideo/issues/1914

**Comment by mostafaaalii** [comment]
Hi mr.daniel. you are the most greatest man😘😘. When I installed ssl, I used this command:

sudo certbot --apache --agree-tos --redirect --hsts --staple-ocsp --email you@example.com -d tube.yourdomain.com

That command added this codes to Apache config file and it responsible for force redirecting from http to https. I just remove this  code and issue has resolved 😎😎😎


RewriteEngine on RewriteCond %{SERVER_NAME} =evolutionary.co RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]

**Comment by DanielnetoDotCom** [comment]
I am glad you found a solution
