### ISSUE TITLE
failed to translate avideo

### ISSUE THREAD

**Issue by mostafaaalii** [WWBN/AVideo#5355]
when i try to translate avideo, i get this notification on the left side of screen:
its hard for me to understand what it say

_ directory.
</code> and change <b>AllowOverride None</b> to <b>AllowOverride All</b>
After editing the above file your code should be like this:
Error Page
Error. Oops you've encountered an error
Find the section <code>
If you don't use apache, just let .htaccess stay or create a empty file - then this check will pass.
In order to use mod_rewrite you can type the following command in the terminal:</p>
It appears that either something went wrong or the mod rewrite configration is not correct.
Restart apache2 after
We need to allow Apache to read .htaccess files located under the 
You can do this by editing the Apache configuration file:
or

**Comment by DanielnetoDotCom** [comment]
can you reproduce it on demo site?

**Comment by mostafaaalii** [comment]
thanks a lot for your response. i got this error when i'm tried for adding some new language to website.
![screenshot-video baritis ir-2021 06 29-03_03_24](https://user-images.githubusercontent.com/72271443/123780519-21d9b600-d888-11eb-9575-c734a530451a.png)

 i changed AllowOverride None to AllowOverride All in the section <directory /var/www/html>

![Screenshot (1)](https://user-images.githubusercontent.com/72271443/123780561-2b631e00-d888-11eb-8f74-6d71abfc9d91.png)

**Comment by mostafaaalii** [comment]
Hi I have installed mod_rewrite completely and when I write this command (sudo a2enmod rewrite ) on terminal I got this message: mod_rewrite is currently working.

I restarted Apache but my translate page isn't working perfectly. What should I do mr thanks?

![Screenshot (2)](https://user-images.githubusercontent.com/72271443/124024696-ce40a700-da04-11eb-8971-7002f2311698.png)
