### ISSUE TITLE
YT Channel Import doesn't imports

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5356]
This option used to work but now it doesn't, trying to import several videos from a YT channel. I don't see anything in logs but the imports seems to show OK message.

![Screen Shot 5781-10-17 at 21 17 32](https://user-images.githubusercontent.com/58882903/123555285-8532ed80-d78d-11eb-81ac-19202445897d.jpg)
![Screen Shot 5781-10-17 at 21 17 36](https://user-images.githubusercontent.com/58882903/123555286-86fcb100-d78d-11eb-995d-2a16e2b3a2a5.jpg)

Nothing in queue, the encoder is empty.

![Screen Shot 5781-10-17 at 21 17 46](https://user-images.githubusercontent.com/58882903/123555292-8b28ce80-d78d-11eb-9bf6-c509aa0017f7.jpg)

**Comment by JoshWho** [comment]
I didn't even know this was a feature. holy cow, let me know if it works. This is awesome.

**Comment by DanielnetoDotCom** [comment]
Since this https://github.com/WWBN/AVideo/issues/3900 I guess the channel import does not work anymore

anyway, the best way to tell it is to check the encoder logs and try it manually
