### ISSUE TITLE
Install new fonts

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5357]
We wish to implement these Hebrew fonts on our sites, is the a guide to install and configure new fonts?

This is the one we want:
https://fonts.google.com/specimen/Heebo?subset=hebrew&preview.text=%D7%92%D7%A0%D7%9F%20%D7%92%D7%99%D7%93%D7%9C%20%D7%93%D7%92%D7%9F%20%D7%91%D7%92%D7%9F,%20%D7%93%D7%92%D7%9F%20%D7%92%D7%93%D7%95%D7%9C%20%D7%92%D7%93%D7%9C%20%D7%91%D7%92%D7%9F&preview.text_type=custom#about

**Comment by DanielnetoDotCom** [comment]
you may be able to add it on the head section as a CSS font

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css
