### ISSUE TITLE
APP Cannot change (ERROR)

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5358]
When I try to change the title I get an error message at the bottom left of the application.
Daniel you need to fix my apps as soon as possible.

Uploading signal-2021-06-23-162801.mp4…

**Comment by sharknetwork24** [comment]
https://user-images.githubusercontent.com/82677269/123558285-ca5b1d80-d795-11eb-85ef-b65a3ea1578b.mp4

**Comment by DanielnetoDotCom** [comment]
Hi, I could confirm the bug on the API, please update your streamer and you should be fine.

**Comment by sharknetwork24** [comment]
Should I use the git pull command?

**Comment by DanielnetoDotCom** [comment]
correct, please use `git pull`
