### ISSUE TITLE
About the MRSS Feed & Live Streaming

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#5361]
If it is possible to place live streaming as part of our categories within Amazon Creator?

Here's the link that I read about that can be possible: https://creator.amazon.com/documentation/ac/other-questions.html#video-content (read under "Video Content" with the subtitle "Do you support HLS (HTTP live streaming)?"

Any answers are open for debate...thanks

**Comment by DanielnetoDotCom** [comment]
I may add this in the future

**Comment by CROSSMediaNet** [comment]
Sounds good, however, is there another way or another solution that can
work outside from our networks?

**Comment by DanielnetoDotCom** [comment]
Currently, this request is only made when you go to the plugins page.

**Comment by CROSSMediaNet** [comment]
Ok, I'll check it out. So, I will have to make the request from the plugin
page...I will have to login to do that, correct?
