### ISSUE TITLE
Contact sending email error

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5365]
Hello there
I failed to send email in the Contact test, and the email configuration has been configured correctly
![image](https://user-images.githubusercontent.com/47063171/123751451-57af8680-d8ea-11eb-809f-17f5f268eebe.png)

testing successfully

![image](https://user-images.githubusercontent.com/47063171/123751639-8168ad80-d8ea-11eb-9cb5-d5d881cf2244.png)

Failed when testing Contact

![image](https://user-images.githubusercontent.com/47063171/123751783-ad842e80-d8ea-11eb-971e-5afe7007ff4c.png)
![image](https://user-images.githubusercontent.com/47063171/123752018-fd62f580-d8ea-11eb-84a8-ee4a7d9e0de2.png)
![image](https://user-images.githubusercontent.com/47063171/123752450-5e8ac900-d8eb-11eb-96de-3cff4a420e9c.png)
Please help thanks

**Comment by DanielnetoDotCom** [comment]
this message comes from your email server. you should check it on your side.

**Comment by chenjian9885** [comment]
Hello
Thank you for your answer. When I reconfigure it again, it now works normally again. It seems that I have overlooked something.

**Comment by chenjian9885** [comment]
Sorry to disturb you again
I don’t understand. I turn off (Enable SMTP Auth) Contact works normally
![image](https://user-images.githubusercontent.com/47063171/123852417-db02c380-d94e-11eb-9113-272f658a605f.png)
![iShot2021-06-30 02 45 54](https://user-images.githubusercontent.com/47063171/123852547-01c0fa00-d94f-11eb-8b9f-b60890caae6d.png)

But it reported an error when the password was retrieved

![iShot2021-06-30 02 48 19](https://user-images.githubusercontent.com/47063171/123852738-3cc32d80-d94f-11eb-945a-e82d6d6e91d7.png)

Enable (Enable SMTP Auth) Contact is abnormal, password retrieval is normal

![image](https://user-images.githubusercontent.com/47063171/123853156-b65b1b80-d94f-11eb-9536-4c51afb8298d.png)
![image](https://user-images.githubusercontent.com/47063171/123853436-0934d300-d950-11eb-87dd-a57065e82e49.png)
![iShot2021-06-30 02 49 02](https://user-images.githubusercontent.com/47063171/123853491-181b8580-d950-11eb-999c-d5d7d434aa72.png)
![iShot2021-06-30 02 49 22](https://user-images.githubusercontent.com/47063171/123853511-1ea9fd00-d950-11eb-9f40-d41dbfe47ea1.png)

(Enable SMTP Auth) It is normal if it is sent by the SMTP Username mailbox when it is started. Other mailboxes are abnormal.
![image](https://user-images.githubusercontent.com/47063171/123854478-582f3800-d951-11eb-8630-1dd18386c596.png)
![image](https://user-images.githubusercontent.com/47063171/123854532-68dfae00-d951-11eb-9f2c-d918eaf7227d.png)
![image](https://user-images.githubusercontent.com/47063171/123854737-aba18600-d951-11eb-9561-fcc791d9c0a6.png)
![image](https://user-images.githubusercontent.com/47063171/123854825-c247dd00-d951-11eb-9878-0a0e2d4a6e5f.png)

Sorry, hope you can understand

**Comment by DanielnetoDotCom** [comment]
Sorry I do not know your SMTP server, I use Google SMTP for myself https://tutorials.avideo.com/video/82/setup-gmail-smtp-with-2fa

**Comment by chenjian9885** [comment]
Ok, I will try Google SMTP server

**Comment by chenjian9885** [comment]
Yes google mailbox is normal

**Comment by JoshWho** [comment]
The test is using the wrong address to send with for the test is the problem. 

The test needs to come from the approved smtp username not the website admin email

**Comment by JoshWho** [comment]
It is functioning correctly to your users though, it is just the test that is messed up like this. Notify Subscribers Message also does this error because of email ownership. It has to use the email assigned with the smtp.

**Comment by guymass** [comment]
I have the same issue, the mail work for me as an admin but a user will get an error like this:

![photo_2021-06-30 15 52 08](https://user-images.githubusercontent.com/58882903/123963480-2e126000-d9bb-11eb-8f75-fdc2884d5247.jpeg)

**Comment by chenjian9885** [comment]
Yes, I am the same as you. I use the domain email service of (porkbun.com)
This is normal（No authentication required）

![image](https://user-images.githubusercontent.com/47063171/123967314-c6730980-d9e8-11eb-99f6-2b5c13043b13.png)


It will be abnormal here（Identity authentication required）

![image](https://user-images.githubusercontent.com/47063171/123967399-dbe83380-d9e8-11eb-9cb9-c03e4a00626e.png)

Is the sending method different on the two sides?

**Comment by chenjian9885** [comment]
The Google mailbox test is normal. I guess if the Google user authentication method is different from the user authentication method of other email service providers.

**Comment by JoshWho** [comment]
I think the template just has the "Send As" in place of the "SMTP account"

**Comment by chenjian9885** [comment]
Sorry!
Do you mean to set the email address of the first administrator as the SMTP account address for testing?

**Comment by chenjian9885** [comment]
Send this way successfully
![image](https://user-images.githubusercontent.com/47063171/124164761-a3715400-dad3-11eb-8644-cd82dd5b4f3e.png)
![image](https://user-images.githubusercontent.com/47063171/124165020-f519de80-dad3-11eb-90b6-055f2734a157.png)

**Comment by chenjian9885** [comment]
I tested the @qq.com mailbox and got the same error. Is it just me who encountered this problem?

**Comment by chenjian9885** [comment]
Hello:
I see ($_POST['email']) causing an email sending error. As shown
![image](https://user-images.githubusercontent.com/47063171/125201522-251a6c00-e2a2-11eb-8467-e5a9b1403814.png)
![image](https://user-images.githubusercontent.com/47063171/125201683-c5709080-e2a2-11eb-94f0-85444a2719ba.png)
![image](https://user-images.githubusercontent.com/47063171/125201770-0bc5ef80-e2a3-11eb-8d04-2750e887d509.png)
Whether the email address of the contact form should not be used as the sender

**Comment by JoshWho** [comment]
> Hello:
> I see ($_POST['email']) causing an email sending error. As shown
> ![image](https://user-images.githubusercontent.com/47063171/125201522-251a6c00-e2a2-11eb-8467-e5a9b1403814.png)
> ![image](https://user-images.githubusercontent.com/47063171/125201683-c5709080-e2a2-11eb-94f0-85444a2719ba.png)
> ![image](https://user-images.githubusercontent.com/47063171/125201770-0bc5ef80-e2a3-11eb-8d04-2750e887d509.png)
> Whether the email address of the contact form should not be used as the sender

This is the exact problem. I was trying to explain it above, but you laid out exactly what I was trying to say. The template is using the wrong email to send with in the test.

**Comment by chenjian9885** [comment]
> > 您好：
> > 我看到 ($_POST['email']) 导致电子邮件发送错误。如图所示
> > 联系表的电子邮件地址是否不应用作发件人
> > ![图像](https://user-images.githubusercontent.com/47063171/125201522-251a6c00-e2a2-11eb-8467-e5a9b1403814.png)
> > ![图像](https://user-images.githubusercontent.com/47063171/125201683-c5709080-e2a2-11eb-94f0-85444a2719ba.png)
> > ![图像](https://user-images.githubusercontent.com/47063171/125201770-0bc5ef80-e2a3-11eb-8d04-2750e887d509.png)
> 
> 这是确切的问题。我试图在上面解释它，但你完全说明了我想说的内容。模板在测试中使用了错误的电子邮件发送。只有这样的测试是错误的。

Yes, I hope to modify and update
