### ISSUE TITLE
Translation issue on home page main section titles

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5370]
Those are the title that will not translate anymore since one of our last git pulls while trying to fix the notification issue.

![Screen Shot 5781-10-16 at 12 28 58](https://user-images.githubusercontent.com/58882903/123508851-90e1bf80-d67a-11eb-96cd-1422cb012472.jpg)
![Screen Shot 5781-10-16 at 12 29 06](https://user-images.githubusercontent.com/58882903/123508853-9212ec80-d67a-11eb-90a0-ecea6ea80904.jpg)
![Screen Shot 5781-10-16 at 12 28 46](https://user-images.githubusercontent.com/58882903/123508854-92ab8300-d67a-11eb-889e-1279e6f7f054.jpg)

_Originally posted by @guymass in https://github.com/WWBN/AVideo/issues/5264#issuecomment-868975652_

**Comment by guymass** [comment]
Nope, like I said before the translations are the same and everything or most is translated, the only thing the doesn't is those main titles and they stopped translation about the second time you told me to pull and try to check if notifications work so idk.

As you can see I have them on both files:
![Screen Shot 5781-10-17 at 16 28 49](https://user-images.githubusercontent.com/58882903/123546323-d2e73000-d764-11eb-987e-736af19a128d.jpg)
![Screen Shot 5781-10-17 at 16 28 44](https://user-images.githubusercontent.com/58882903/123546324-d4b0f380-d764-11eb-9023-1fc1b03ad562.jpg)

**Comment by DanielnetoDotCom** [comment]
Is the same happening in other idioms?

I just checked and it is working on my side

![image](https://user-images.githubusercontent.com/18009293/123989030-e2ea5400-d99e-11eb-86a8-3ed57ac5f5ef.png)

**Comment by guymass** [comment]
I have this only on my site live.ahava528.com the others are fine. Any suggestion on where to mainly investigate? which files I might have edited idk.

**Comment by DanielnetoDotCom** [comment]
I have no idea, I can only imagine you do not have the correct files, also try to disable the cache plugin

**Comment by guymass** [comment]
Well its been two weeks now and I cannot solve this. I have no idea why it will not translate anymore those section titles. Even if I change the title and translation it will not do it. All other translations work. Only my front page will not translate. Any test I can do/put in the code to see? I am not even sure what to look for really.

**Comment by DanielnetoDotCom** [comment]
Try to run this 

`sudo git fetch --all && sudo git reset --hard origin/master`

**Comment by guymass** [comment]
OK I decided eventually to run this command today but still no change. The translation for those home page sections are not translating, idk anymore what is the issue.

**Comment by guymass** [comment]
Also, changing to any other language doesn't translate them as well. The constantly remain in English.

Most Recent
Recommended
Most Watched
Popular
Etc...

**Comment by guymass** [comment]
Just updated to Version 11.3 but still those headings will not translate, any suggestions?

**Comment by guymass** [comment]
I have also this word PODCAST which for some reason appears with a prefixed space and I noticed that all the words which have this spaces are not being translated properly.

![Screen Shot 5781-12-05 at 9 58 29](https://user-images.githubusercontent.com/58882903/129317446-f74bf03c-4903-42dd-a489-7dda27ea0f42.jpg)
![Screen Shot 5781-12-05 at 9 58 25](https://user-images.githubusercontent.com/58882903/129317449-9c85db01-8538-418b-8e60-64678cd3a054.jpg)

Where does this space comes from? and why I can translate some words but others don't?

I still cannot translate those section titles on home page and I don't have that issue on the other site I have under FETUBE.
