### ISSUE TITLE
Categories Top Menu now Has Number boxes at the end of the categories

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5373]
Not sure what all the number things r

![18b3d5b0-7d37-49df-872d-dfebfdef70d7](https://user-images.githubusercontent.com/39392449/124038821-63bd4600-d9c7-11eb-9a08-38e09487dcf5.png)

**Comment by DanielnetoDotCom** [comment]
Sorry this was a mistake, here is a fix

**Comment by JoshWho** [comment]
Yup all fixed now thank you
