### ISSUE TITLE
Some devices Iphone Mostly saying videos do not play

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5374]
Not sure if this was a google chrome update or what but last night and today getting random reports of video not playing on Chrome for Iphone and Some Androids. 

I myself cannot reproduce this error my android seems to be working fine with videos but I guess certain version r not. Not sure what has changed in the last updates but wondering if anyone else has also got these reports?

**Comment by DanielnetoDotCom** [comment]
Just tested on my iphone and it plays fine

**Comment by JoshWho** [comment]
Yeah this one is a weird one. I can't reproduce it either but there is 3 people telling me about it now.

**Comment by DanielnetoDotCom** [comment]
maybe it is in a specific video

**Comment by JoshWho** [comment]
they said it is all videos.

**Comment by DanielnetoDotCom** [comment]
maybe they neet to clear the cache

**Comment by JoshWho** [comment]
or update their app. Something is telling me it is a Apple Chrome thing.

**Comment by DanielnetoDotCom** [comment]
I have tested also on chrome and I could not reproduce

**Comment by JoshWho** [comment]
I am now starting to have issues with mobile playback on Chrome Android. Try playing this video on mobile

https://www.joshwhotv.com/v/.QDZ-2g

**Comment by JoshWho** [comment]
I think it has something to do with the part that tries to load the last time stamp you last viewed the video at.

**Comment by JoshWho** [comment]
I think this is solved haven't heard any more complaints about it.
