### ISSUE TITLE
Jitsi Meet with Custom https Server

### ISSUE THREAD

**Issue by DrDoug88** [WWBN/AVideo#5377]
**Describe the bug**
Jitsi Meet with custom server works with http, but not with https

**To Reproduce**
1. Set up a custom Jitsi server, change the settings in the plugin. Use http first to confirm it works, then enable https, and it will generate an "Authentication failed - You're not allowed to join this call" once the Jitsi window opens.

![image](https://user-images.githubusercontent.com/80653458/124181349-ff5bbe80-da7a-11eb-9035-5be0be7ea508.png)

**Comment by DanielnetoDotCom** [comment]
For sure it works with HTTPS, I am pretty sure the problem is on your jitsi configuration

**Comment by DrDoug88** [comment]
My apologies, it had to do with authentication on the Jitsi side. Can you provide some insight as to what the "secret" field in the Meet plugin is mapped to, or how we can use it for authentication on the Jitsi server? After removing the login authentication process from the Jitsi server, everything works, but that allows for anonymous guests to create/use Jitsi rooms. We'd like to have authenticated users only for the Jitsi server, but not sure how to set this up correctly on the AVideo side.  I also see the JWT_APP_ID and JWT_APP_SECRET, and I found this article, which appears to bridge the gap:

https://community.jitsi.org/t/solved-how-to-create-room-with-jwt-in-authentication-token-mode/67409

Any help on this is appreciated. Thank you!

**Comment by DanielnetoDotCom** [comment]
Please check this https://github.com/WWBN/AVideo/wiki/Custom-Jitsi

**Comment by DrDoug88** [comment]
Hi Daniel,

Thank you for the assistance. It took a bit, but I went the docker route as you suggested and everything seems to be working correctly with respect to JWT authentication, specific user groups etc. The only remaining issue is that of moderator rights. Based on this configuration, it appears that anyone joining a room has moderator rights, i.e. the ability to kick other participants, etc. Is there a way to set it so that only the user setting up the room has moderator rights? I have encountered a lot of forum posts out there related to JWT token authentication and moderator rights, but given how it is interweaved with AVideo in this case, I'm still unsure of the correct route. I'm a bit of a noob in this area, I apologize.  Thank you kindly for your help!

**Comment by DanielnetoDotCom** [comment]
You need to install this to make the moderator feature to work

https://github.com/nvonahsen/jitsi-token-moderation-plugin

**Comment by DrDoug88** [comment]
Okay, so does the AVideo Meet plugin already correctly send moderator token over on creation of meeting, i.e.:

{
  context: {
    user: {
      avatar,
      name,
      id
    }
  },
  sub,
  room,
  **moderator: true**
}

**Comment by DanielnetoDotCom** [comment]
Yes it is

**Comment by DrDoug88** [comment]
Okay, I implemented that plugin and it does indeed work correctly. The user creating the meeting becomes the moderator and anyone else joining is not, but the moderator can grant mod rights to other users. However, during testing, I also included a Mac, and was unable to join a meeting when initiated on the Mac. I logged in as same user on a Windows machine, and it worked fine. I'm not yet sure if the issues with the Mac are specifically from this plugin or from something more general to Meeting creation. But when a meeting is created from the Mac, if another user attempts to join, it gives an error and says "Meeting has not yet started". This likely will have to put through as a bug, but we just encountered it, so I thought it worth mentioning.

**Comment by DanielnetoDotCom** [comment]
I see, maybe it is something regarding the start time.

what time do you have here? is it correct?

![image](https://user-images.githubusercontent.com/18009293/126776823-5385e21a-563b-451d-9088-2e0db017aaad.png)

**Comment by DrDoug88** [comment]
It correctly posts the time when the meeting is created.  I'll try to get some more testing in on this shortly and post the findings.

![image](https://user-images.githubusercontent.com/80653458/126812852-0b7e2ba0-c9f3-405e-9fed-1375cd16b1a8.png)

**Comment by DrDoug88** [comment]
Okay, so we figured out the join issue. It wasn't because of the browser or operating system. It was due to time zones. I had my laptop still set to my home time zone, and I was in a time zone one hour earlier. This caused the join issue. If the device is set to the wrong time zone, then it could run into joining errors due to the calculated time. Thanks for all of your help Daniel!!!
