### ISSUE TITLE
footerHTMLCode

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5378]
footerHTMLCode is not beautifully displayed
![image](https://user-images.githubusercontent.com/47063171/124191099-dd535200-daf5-11eb-8865-f813f9b1712e.png)

![image](https://user-images.githubusercontent.com/47063171/124191339-3d49f880-daf6-11eb-9842-684d612af090.png)

**Comment by DanielnetoDotCom** [comment]
You may want to purchase the Customize plugin from here https://youphp.tube/marketplace/

![image](https://user-images.githubusercontent.com/18009293/124262768-d08c2980-db08-11eb-9b84-c687a9664a22.png)

**Comment by chenjian9885** [comment]
Yes, the plug-in is my first choice, but after saving the code and editing it again, it will be like this
![image](https://user-images.githubusercontent.com/47063171/124266275-563fc180-db69-11eb-8db4-10920819dab3.png)
![image](https://user-images.githubusercontent.com/47063171/124266920-2b09a200-db6a-11eb-892d-93203dace036.png)


Edit here like this
![image](https://user-images.githubusercontent.com/47063171/124266463-9c952080-db69-11eb-9674-dd7c725f0c13.png)


Save will look like this
![image](https://user-images.githubusercontent.com/47063171/124266760-f564b900-db69-11eb-8c4f-a281b370fc10.png)

**Comment by RememberForgottenHits** [comment]
Hei,
There is no need to add HTML code, write normally there.

![footer-edit](https://user-images.githubusercontent.com/34457020/124344412-ac991880-dbda-11eb-8558-fe8cda595014.png)

![footer](https://user-images.githubusercontent.com/34457020/124344413-b28ef980-dbda-11eb-8161-f279aaa1a0c7.png)

**Comment by chenjian9885** [comment]
Great programs shouldn’t be limited to this
![image](https://user-images.githubusercontent.com/47063171/124347306-98730c80-dc16-11eb-8363-2343a6da756b.png)
![image](https://user-images.githubusercontent.com/47063171/124347341-c9534180-dc16-11eb-9c6f-e4a0f9036592.png)

Should make it beautiful
![image](https://user-images.githubusercontent.com/47063171/124347352-d839f400-dc16-11eb-92e1-92175cf2961c.png)

**Comment by DanielnetoDotCom** [comment]
Did you try this to add your own HTML?

![chrome-capture](https://user-images.githubusercontent.com/18009293/124352627-cb49e000-dbd7-11eb-8f6d-b565a7e1f4b8.gif)

**Comment by chenjian9885** [comment]
Yes, I tried to add html code. After saving, it will not be the original code in the next edit
![image](https://user-images.githubusercontent.com/47063171/124360496-c5e2a900-dc5c-11eb-94f7-dd19a3295259.png)
![image](https://user-images.githubusercontent.com/47063171/124360515-e448a480-dc5c-11eb-9e4a-3bae4f6fc5f3.png)

Open the Customize plugin this time and become like this

![image](https://user-images.githubusercontent.com/47063171/124360629-689b2780-dc5d-11eb-89aa-6ad768510c7d.png)
![image](https://user-images.githubusercontent.com/47063171/124360664-9da77a00-dc5d-11eb-89f9-072187ef6e5b.png)

Of course I can change the code of footer to achieve my effect, but I am still happy to use plugins to manage
