### ISSUE TITLE
Video quality deteriorates when downloading

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#5381]
Why does the video quality drop when I download? I upload through an encoder and the video gets poor quality, how can I avoid it? On your site http://demo.avideo.com/ all videos are also in poor quality

**Comment by DanielnetoDotCom** [comment]
I do not control what youtube-dl download, to have a high resolution video you must upload it

Check this https://github.com/WWBN/AVideo/wiki/About-Video-Upload#automatic-resolutions-default-and-recommended
