### ISSUE TITLE
need help logging into cloudflare

### ISSUE THREAD

**Issue by Nealpatrick5410** [WWBN/AVideo#5382]
Hello.. my question is how do I log into cloudflare. I paid for the installation, but I didn't get any login info for cloudflare. I tried forgot password and forgot email, and that didn't work. I need to login because I'm trying to verify my domain with google. I hope this isn't a stupid question. My domain name is actually through google domains, but I had to change the name servers to cloudflare stuff. Please help

**Comment by DanielnetoDotCom** [comment]
Hi, I do not provide any Cloudflare account, but you can create a free one there and transfer your domain to you changing the name servers on your domain provider
