### ISSUE TITLE
Chat2 textarea missing intranet offline

### ISSUE THREAD

**Issue by lewis657** [WWBN/AVideo#5383]
I bought chat2 plugin, but it does not work on the intranet. there is a problem with the textarea (emojionearea) does not appear! how to fix it?

![image](https://user-images.githubusercontent.com/43966444/124225658-214f5280-db08-11eb-982b-aa68bb76994c.png)

in </head> I see link 
![image](https://user-images.githubusercontent.com/43966444/124226067-c23e0d80-db08-11eb-8fa3-183b08b69336.png)

maybe that's the problem? Because in Internet its all ok.

**Comment by DanielnetoDotCom** [comment]
Can you please check your JS console for errors?

**Comment by lewis657** [comment]
![image](https://user-images.githubusercontent.com/43966444/124267100-1a403880-db38-11eb-9def-d6820771496d.png)

**Comment by DanielnetoDotCom** [comment]
I will send update Chat 2 version 6.7

I could remove the jquery.textcomplete error, but looks like I need to use the CDN to use the emojis assets/icons.

I will upload the new version soon, can you please check if it resolves the issue?

**Comment by lewis657** [comment]
ofcourse, give me note here.

**Comment by DanielnetoDotCom** [comment]
Just making sure, you have no internet connection where you are using your AVideo site?

I can see your DNS could not resolve the cdn.jsdeliver.net

**Comment by lewis657** [comment]
Yes, I have intranet (offline) installation.  what else should I do?

**Comment by DanielnetoDotCom** [comment]
Hi, I guess I could make the Chat2 work offline

you will need to update your Chat2 to version 6.8 and also make a git pull on the AVideo Streamer site

**Comment by lewis657** [comment]
![image](https://user-images.githubusercontent.com/43966444/124874761-653ecd80-dfc8-11eb-9c06-0b034f54925a.png)

**Comment by lewis657** [comment]
![image](https://user-images.githubusercontent.com/43966444/124874822-7ab3f780-dfc8-11eb-95fa-4603f7b612c6.png)


still this same. missing textarea

**Comment by DanielnetoDotCom** [comment]
Now I can see there are some loading fails from your localserver.

did you also update the streamer?

**Comment by lewis657** [comment]
yes I also update. I go to avideo dir and type git pull

**Comment by DanielnetoDotCom** [comment]
Can you please check why this was not loaded?

![image](https://user-images.githubusercontent.com/18009293/124925565-f3b84c80-dfd2-11eb-85a2-eece10159cb3.png)
![image](https://user-images.githubusercontent.com/18009293/124925621-05015900-dfd3-11eb-88a7-8490135f699d.png)

**Comment by lewis657** [comment]
I do 

sudo git fetch --all && sudo git reset --hard origin/master

and it's looks good.

**Comment by DanielnetoDotCom** [comment]
Do you mean it is working now?
