### ISSUE TITLE
Category Top Links Hides text on Mobile Users not liking that

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5385]
On desktop the Links look fine you can read them
![download (3)](https://user-images.githubusercontent.com/39392449/124258513-1a6a1500-daf3-11eb-9a79-accddc0d3961.png)

Mobile makes the Text Hide and only shows the Icons
![a1a2d1ed-3097-468f-8985-b0149db2e06b](https://user-images.githubusercontent.com/39392449/124258660-47b6c300-daf3-11eb-9669-6a7f2d5a7fa6.png)

How can I keep the text expanded on mobile view for the

**Comment by DanielnetoDotCom** [comment]
Please try now

**Comment by JoshWho** [comment]
Looks good Thank you @DanielnetoDotCom
