### ISSUE TITLE
Show Different Custom Site Logo for Premium Users 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5386]
Would be cool to have a different logo file for Premium members that shows their account is Premium

Like how yt does it
![99f5c962-56cd-42a0-8f8d-fb80639b5ee0](https://user-images.githubusercontent.com/39392449/124259057-b7c54900-daf3-11eb-8cdf-dd4190bf5730.png)

![d09b6ce1-31f1-4066-9f49-c25f1de03600](https://user-images.githubusercontent.com/39392449/124259310-fd821180-daf3-11eb-9f51-bc085a45f7f1.png)

**Comment by DanielnetoDotCom** [comment]
There is no such feature, I may add it in the future
