### ISSUE TITLE
Playlist, favorite, watch later

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#5387]
Hello,
After the last update movies are not saved in the playlist
to demo site working normally
Any help?

Thanks

   thrown in path/to/my/streamer/site/objects/functions.php on line 4315
 #5 {main}
 #4 path/to/my/streamer/site/objects/playListAddVideo.json.php(5): require_once('/var/www/html/Y...')
 #3 path/to/my/streamer/site/videos/configuration.php(42): require_once('/var/www/html/Y...')
 #2 path/to/my/streamer/site/objects/include_config.php(146): AVideoPlugin::getStart()
 #1 path/to/my/streamer/site/plugin/AVideoPlugin.php(561): MP4ThumbsAndGif->getStart()
 #0 path/to/my/streamer/site/plugin/MP4ThumbsAndGif/MP4ThumbsAndGif.php(18) : eval()'d code(1) : eval()'d code(179): getVideos_id()
 Stack trace:
 [02-Jul-2021 14:38:39 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'PlayLists' not found in path/to/my/streamer/site/objects/functions.php:4315

**Comment by DanielnetoDotCom** [comment]
Please try now

**Comment by wetubeclub** [comment]
it's OK now!!!!
thank you Daniel
