### ISSUE TITLE
Live stopped - Security?  Live/on_publish.php

### ISSUE THREAD

**Issue by redilee** [WWBN/AVideo#5389]
Error Logs:
 [03-Jul-2021 13:57:38 America/Chicago] AVideoLog::SECURITY: NGINX ON Publish error, Transmition name not found (6082cef659356)  SCRIPT_NAME: /AVideo/plugin/Live/on_publish.php

 [03-Jul-2021 14:09:54 America/Chicago] AVideoLog::SECURITY: NGINX ON Publish denied  SCRIPT_NAME: /AVideo/plugin/Live/on_publish.php

Ran all system (apt) and AVideo (gitpull) updates last night.

**Comment by DanielnetoDotCom** [comment]
Looks like you are using the wrong keys to connect on the live

**Comment by markginter31** [comment]
I'm seeing something similar:
1) on my local network I can setup obs-studio from a desktop/wireless laptop and stream using the rtmp server-url and stream key/secret

2) if I use an android device on the same local network (Avideo app / camon / streamlabs) I get the security notice in my avideo logs and it doesn't connect/display.  I can't find any information in the nginx logs or apache logs to help me out.

3) this is the error -->  [08-Jul-2021 10:58:18 Africa/Abidjan] AVideoLog::SECURITY: NGINX ON Publish denied  SCRIPT_NAME: /plugin/Live/on_publish.php

**Comment by DanielnetoDotCom** [comment]
From the mobile app, you cannot connect to the internal network.

the Meet server needs access to your server to be able to livestream

**Comment by markginter31** [comment]
That makes sense for the Meet part...  
What confuses me is that I can put the rtmp url and key into obs-studio and it works fine.  But when I use the same rtmp url and key in an Android device (to live stream from it) it kicks up that warning/error and does not live stream.

**Comment by DanielnetoDotCom** [comment]
what app are you using to livestream?

**Comment by markginter31** [comment]
I've successfully used "cam on" in the past, and this time I also tried streamlabs.  Both allow for custom rtmp entries - and neither one is working.

I just ran a quick test with "cam on" over my LTE data connection.  It connects to the rtmp server, it writes files into the correct /HLS/live folder, but the video never loads on the website (circle just spings).

If I connect obs-studio, it writes the files to the same /HLS/live directory but the video loads and plays on my website.

**Comment by markginter31** [comment]
I've also set up so that anything streamed is automatically recorded - when I open the .flv saved from an obs-studio stream I get audio/video.  When I open the .flv saved from my android device stream it only has audio (no video).  Weird.

**Comment by DanielnetoDotCom** [comment]
It is probably the output configuration in your app

Try to use the adaptive mode https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream

**Comment by markginter31** [comment]
Stripped down my nginx.conf to Adaptive-Bitrates -- now I can stream audio/video from obs-studio, and cam on will stream audio but not video yet... Getting closer :)

**Comment by DanielnetoDotCom** [comment]
Try to modify the FFMPEG on the adaptive configuration, maybe transcode the video
