### ISSUE TITLE
GET http://66.29.134.71/AVideo-master/index.php 500 (Internal Server Error)

### ISSUE THREAD

**Issue by dakotath** [WWBN/AVideo#5391]
![Video Not Available · Home · AVideo and 35 more pages - Personal - Microsoft​ Edge 7_4_2021 10_14_14 AM](https://user-images.githubusercontent.com/72819403/124386450-db81be00-dcb0-11eb-99fb-ba299ce4fc28.png)

**Comment by DanielnetoDotCom** [comment]
Seems to me you did not install the mod_rewrite, install it first then check your log files

**Comment by dakotath** [comment]
how

**Comment by dakotath** [comment]
its enabled

**Comment by DanielnetoDotCom** [comment]
If it is enabled and working you should not use the index.php

anyway, check your log files.
