### ISSUE TITLE
FFMPEG Issue: Not Playing Audio on theta.tv and few other sites by Restream FFMPEG - Code below is Permit fix for this

### ISSUE THREAD

**Issue by ChisdealHDYT** [WWBN/AVideo#5393]
FFMPEG BUG for restream on line 

```
"ffmpeg -re -i \"{$m3u8}\" -max_muxing_queue_size 1024 -acodec copy -bsf:a aac_adtstoasc -vcodec copy -f flv \"{$restreamsDestinations[0]}\"" @ https://github.com/WWBN/AVideo/blob/master/plugin/Live/standAloneFiles/restreamer.json.php#L183

AND 

-max_muxing_queue_size 1024 -acodec copy -bsf:a aac_adtstoasc -vcodec copy -f flv @ https://github.com/WWBN/AVideo/blob/master/plugin/Live/standAloneFiles/restreamer.json.php#L177

It prevent some streaming platform Audio not to work Example Theta.TV and few other websites

Permit Fix for this:

change them Lines to

"ffmpeg -re -i \"{$m3u8}\" -max_muxing_queue_size 1024 -acodec acc -bsf:a aac_adtstoasc -vcodec copy -f flv \"{$restreamsDestinations[0]}\"" @ https://github.com/WWBN/AVideo/blob/master/plugin/Live/standAloneFiles/restreamer.json.php#L183

AND 

-max_muxing_queue_size 1024 -acodec acc -bsf:a aac_adtstoasc -vcodec copy -f flv @ https://github.com/WWBN/AVideo/blob/master/plugin/Live/standAloneFiles/restreamer.json.php#L177

We have changed it to test it and works all Livestreams platforms with no issues.

**Comment by ChisdealHDYT** [comment]
what i collected you guys made mistaken code, you put `-acodec copy` not `-acodec acc` and code works as normal, change that mistaken error on restream file

**Comment by akhilleusuggo** [comment]
Is not a bug as tagged. What if I don't want to re-encode the audio ? Re-encoding the audio takes resources ( decoding it , stress out 1 core at 100% ).

Your issue is that the video you're trying to stream or restream is not widely supported by ffmpeg or the video player destination. 
Yes, the common fix is `-acodec acc -bsf:a aac_adtstoasc`, **but is not a requirement.**

**Comment by ChisdealHDYT** [comment]
> Is not a bug as tagged. What if I don't want to re-encode the audio ? Re-encoding the audio takes resources ( decoding it , stress out 1 core at 100% ).
> 
> Your issue is that the video you're trying to stream or restream is not widely supported by ffmpeg ( depending on the builds ) or the video player destination.
> Yes, the common fix is `-acodec acc -bsf:a aac_adtstoasc`, **but is not a requirement.**

what i see changing copy to acc doesnt effect cpu, 100% confirm works but on your code it set to copy as Audio when pose be Audio acc

**Comment by akhilleusuggo** [comment]
Like I've said, it depends on the source. If my source input video is `aac`, then I don't need to encode the audio. It is required only if you're using other type of containers. Also `-strict -2` may be required. All depends on the source.

What software you're using to stream ? OBS ?



![image](https://user-images.githubusercontent.com/52116577/124618910-decba400-de80-11eb-9940-0640e3b94a34.png)

**Comment by ChisdealHDYT** [comment]
> Like I've said, it depends on the source. If my source input video is `aac`, then I don't need to encode the audio. It is required only if you're using other type of containers. Also `-strict -2` may be required. All depends on the source.
> 
> What software you're using to stream ? OBS ?
> 
> ![image](https://user-images.githubusercontent.com/52116577/124618910-decba400-de80-11eb-9940-0640e3b94a34.png)

this might be little odd, but OVH servers doesnt like FFMPEG, RTMP and few stuff on site. so i moved server over Contabovps. nothing changed and all working even audio.

plus OVH servers it random Disconnect your restream too every 5 min

so some reasons OVH was causes FFMPEG, RTMP and Access Origin issue that i tag @ #5396
