### ISSUE TITLE
Feature Request: Make Livepeer.com RTMP Servers supported to Site (System void NGINX RTMP selfhosted and go prehosted)

### ISSUE THREAD

**Issue by ChisdealHDYT** [WWBN/AVideo#5394]
i would like see if you can add https://livepeer.com/ supported for RTMP Server too, they have open API and for free Tier you can go up 10 viewers less they pay for service.

livepeer very good servers that doesnt require NGINX RTMP but sadly you cant add .php files in they servers as custom encoding

but it can be added on Live plugin on add Live Server lists, and make it detect keys / create keys there

API for Livepeer Docs: https://livepeer.com/docs/api-reference/

**Comment by ChisdealHDYT** [comment]
still for Feature Request if can be confirmed or not and its not issue, its Feature Request

**Comment by DanielnetoDotCom** [comment]
Hi

currently, I am not interested in using another live server, but Nginx
