### ISSUE TITLE
Access-Control-Allow-Origin header on (plugin/MobileManager/getConfiguration.json.php)

### ISSUE THREAD

**Issue by ChisdealHDYT** [WWBN/AVideo#5396]
how i fix this, because Mobile app not working and keeps returning as not working and causes is doing 2 `Access-Control-Allow-Origin` that pose be 1

nothing has changed like files and ect. so files all from Latest github branch

what it confuses me works fine on my other site but not stream4.fun site when both are same version

![image](https://user-images.githubusercontent.com/18028479/124452859-b3609080-dd7e-11eb-9a57-c2d8ec3015e6.png)

![3oeoxzOYp5](https://user-images.githubusercontent.com/18028479/124453069-e1de6b80-dd7e-11eb-9277-d2fb20816a73.png)

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by ChisdealHDYT** [comment]
will do gimmi sec update

**Comment by ChisdealHDYT** [comment]
still same issue @DanielnetoDotCom 

`Access to XMLHttpRequest at 'https://stream4.fun/plugin/MobileManager/getConfiguration.json.php' from origin 'http://ip:8000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'http://ip:8000, *', but only one is allowed.`

not sure its app self or not?

**Comment by DanielnetoDotCom** [comment]
I have used this for testing

https://www.test-cors.org/

I guess it is something in your server, I have tested the demo site and I could not see any error.

**Comment by ChisdealHDYT** [comment]
i goign reinstall it see issue, might be issue somethign that i can track, thats what my community doing atm. because getting bug of stremaign too when they not live shows they live

**Comment by DanielnetoDotCom** [comment]
Suddenly your error disappear for me, I am not sure if you changed something in your side

**Comment by ChisdealHDYT** [comment]
i inform you if reinstall fixes

**Comment by ChisdealHDYT** [comment]
whi;e it reinstalling @DanielnetoDotCom can you explain how i build my own payment system on site, i have LIB over @ https://github.com/ChisdealHDYT/Multi-module-PHP

in folder called https://github.com/ChisdealHDYT/Multi-module-PHP/tree/master/lib/cryptopay

is there way i can make this because i dont know how build my old plugin and i tried fork it from other Crypto plugin and change codes but partly ZENZO lib i made doesnt detect price and wallet address? and scans doesnt work too?

**Comment by DanielnetoDotCom** [comment]
Hi, to do it you MUST know how to program, for sure you can look into the code and figure out how to add your code

**Comment by ChisdealHDYT** [comment]
> Hi, to do it you MUST know how to program, for sure you can look into the code and figure out how to add your code

i have learned code since 2016 but some languages i code was full end nodejs. but i would love learn code since i did made them lib myself for Crypto side without wallet Core system, just i dont know how your plugin code operate make this code run on YPTWallet as gateway payment.

if there is some kind DOCS or something show me how build example plugin for YPT then let me know. and website reinstalled and still facing same issue

**Comment by ChisdealHDYT** [comment]
will it be `.fun` domain issue? since when i tired my `.co.uk` and `.com` they work just stream4.fun as `.fun` not

**Comment by DanielnetoDotCom** [comment]
I have never seen this before, I really do not know.
