### ISSUE TITLE
updating of the youphptube from version 7.5 to 11 (latest release)

### ISSUE THREAD

**Issue by aliceglitch** [WWBN/AVideo#5397]
Hi, I want to update my current youphptube script which is now on the host from version 7.5 to 11, I have already updated my script from version 7.2 to 7.5 with the script key, But that key no longer exists, Should this be done by replacing the files? How do I update my script from version 7.5 to 11? thanks.

![photo_2021-07-05_18-28-09](https://user-images.githubusercontent.com/72448881/124482695-d01cb880-ddbe-11eb-8469-6cf0c2098e8f.jpg)

![photo_۲۰۲۱-۰۶-۲۸_۱۹-۲۰-۲۱](https://user-images.githubusercontent.com/72448881/124482162-3e14b000-ddbe-11eb-9ca2-b16b2435fd8b.jpg)

**Comment by DanielnetoDotCom** [comment]
This will be a big step.
I really recommend you to update using the git pull command.

also make sure you follow this

https://github.com/WWBN/AVideo/issues/5075#issuecomment-833764155
