### ISSUE TITLE
FTP Plugin

### ISSUE THREAD

**Issue by ScoobyDooWaffle** [WWBN/AVideo#5400]
Hi , 
I try to setup FTP plugin but when i enter all info for FTP it's return me back Null message on test.php

**Comment by DanielnetoDotCom** [comment]
Can you please screenshot where are you seeing the Null?

**Comment by ScoobyDooWaffle** [comment]
![image](https://user-images.githubusercontent.com/76669896/124512495-80ca8e00-dda6-11eb-9ae3-4691658316f9.png)
No where i can see doccumentation etc..
I have tested with many different way

**Comment by DanielnetoDotCom** [comment]
check your avideo.log file

**Comment by ScoobyDooWaffle** [comment]
I dont want to be anyoying but where can i find it ?

**Comment by DanielnetoDotCom** [comment]
Here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by ScoobyDooWaffle** [comment]
[05-Jul-2021 19:52:14 Africa/Abidjan] AVideoLog::DEBUG: Live::createStatsCache {"bytes":155,"cachefile":"\/var\/www\/AVideo\/videos\/cache\/YPTObjectCache\/getstats\/getstatsnotifications\/stream4.fun\/https\/notlogged_2f13386e93d11969ed5227485911671f\/6944dde80236df5277fe7cef77215bf6.cache"} SCRIPT_NAME: /plugin/Live/stats.json.php
[05-Jul-2021 15:52:32 America/Toronto] AVideoLog::DEBUG: FTP_Storage: test start SCRIPT_NAME: /plugin/FTP_Storage/test.php
[05-Jul-2021 15:52:32 America/Toronto] AVideoLog::DEBUG: FTP_Storage: copy start SCRIPT_NAME: /plugin/FTP_Storage/test.php
[05-Jul-2021 15:52:32 America/Toronto] AVideoLog::DEBUG: FTP:getClient finish SCRIPT_NAME: /plugin/FTP_Storage/test.php
[05-Jul-2021 15:52:32 America/Toronto] AVideoLog::DEBUG: FTP_Storage: client->put SCRIPT_NAME: /plugin/FTP_Storage/test.php
[05-Jul-2021 15:52:32 America/Toronto] AVideoLog::DEBUG: FTP_Storage: test get URL SCRIPT_NAME: /plugin/FTP_Storage/test.php

**Comment by DanielnetoDotCom** [comment]
Please provide more from the log.

**Comment by ScoobyDooWaffle** [comment]
Just to check with you , 
I use this to creating my FTP : https://linuxize.com/post/how-to-setup-ftp-server-with-vsftpd-on-ubuntu-20-04/
On endpoint what i need to put exacly?

**Comment by DanielnetoDotCom** [comment]
endpoint  is the URL that you will use to access the uploaded file

Please check this https://github.com/WWBN/AVideo/wiki/FTP_Storage-Plugin

**Comment by ScoobyDooWaffle** [comment]
I still have a problem. 
I have tried to create an FTP via CPANEl for example which makes it easy to create and gives me the path to get there. 
But I still can't get AVideo to recognize it. 
Could you create a fake FTP account with 1Gb or less to prove that it works correctly.

**Comment by DanielnetoDotCom** [comment]
Please share your log files here

**Comment by ScoobyDooWaffle** [comment]
[avideo.log](https://github.com/WWBN/AVideo/files/6778201/avideo.log)

**Comment by ScoobyDooWaffle** [comment]
Did you found something ?

**Comment by DanielnetoDotCom** [comment]
Hi, I just sent a new plugin version 2.5.

the test file will give you a lot more information about your FTP configuration.

it will make different tests until finding the correct configuration

Also, I just create a new FTP server for testing

- hostname = "demo.avideo.com";
- username = "ftpuser";
- password = "123";
- port = 121;
- path = "/videos/";
- endpoint = "https://ftp.youphptube.com/videos/";
- SSL = false;
- passiveMode = true;

**Comment by ScoobyDooWaffle** [comment]
I tried to find best way to update the plugin. 
Doo you have wiki for it ?

**Comment by DanielnetoDotCom** [comment]
First, make sure you (update your streamer)[https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform]

Then delete the plugin folder (FTP_Storage), download it again from the [marketplace](https://youphp.tube/marketplace/) and (upload it again)[https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin]

**Comment by ChisdealHDYT** [comment]
> First, make sure you [update your streamer](https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform)
> 
> Then delete the plugin folder (FTP_Storage), download it again from the [marketplace](https://youphp.tube/marketplace/) and [upload it again](https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin)

i tried new FTP plugin for @ScoobyDooWaffle  since we both work on stream4.fun, FTP Storage works on your test server. but waiting for him come out of work so him test his own FTP server.

**Comment by ScoobyDooWaffle** [comment]
I gonna close this issue cause test server works very good and impressive speed. 
So it's gonna be my part to doo the reset thanks @DanielnetoDotCom for that support !
