### ISSUE TITLE
Notification bell

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#5401]
![image](https://user-images.githubusercontent.com/66537018/124608983-37794d80-de3d-11eb-9b90-365a762e7912.png)

The notification bell with hover message appears reversed.

I am actually receiving alerts, but this graphic with hover makes it seem like they are off.

**Comment by akhilleusuggo** [comment]
True.
It's basically shows you that if you click you will disable notifications. But it does give this reversed meaning specially since most of the users are using other platforms and it's getting confused.
