### ISSUE TITLE
Twitter Share  does not share valid link

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5403]
sometimes the link will be missing completely and sometimes I get a 400 error page when using the share twitter button

Try on this video to share to twitter sing the button on the page

https://www.joshwhotv.com/v/.QG463Q

**Comment by DanielnetoDotCom** [comment]
You should be good now.

the problem was the character` |` on the URL.

it is removed automatically

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom
