### ISSUE TITLE
How to block comment links

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5404]
How to block comment links
![image](https://user-images.githubusercontent.com/47063171/124742744-9929dc80-df4f-11eb-8ddf-f32c8b7c5d83.png)

**Comment by DanielnetoDotCom** [comment]
Currently there is no way to block it

**Comment by chenjian9885** [comment]
Okay, I hope this feature can be added in the future, after all, there will be a lot of spam links
