### ISSUE TITLE
Create a menu button to display my subscription

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5405]
Hello Danielneto
Can you add a menu button to display the content of the following figure on a new page?
![image](https://user-images.githubusercontent.com/47063171/124798413-e4f77880-df85-11eb-8ea5-087ba94e9220.png)
It's a good way for users to find the content of their subscribed channels

**Comment by DanielnetoDotCom** [comment]
Hi, on the Gallery you have an option to display your subscribed channels on the main page

**Comment by chenjian9885** [comment]
Yes, but it would be great if there was a menu button to distinguish it, or it would be a good choice to provide a link to (my subscription) and create our own custom menu.
