### ISSUE TITLE
there is hidden Space after /live on (Live Servers Settings)

### ISSUE THREAD

**Issue by ChisdealHDYT** [WWBN/AVideo#5407]
![image](https://user-images.githubusercontent.com/18028479/124937101-fc267c80-dffe-11eb-9bd3-dc0c0812b68c.png)

its showing `https://uklon1.stream4.fun:8443/live /60e4646a5dc70-1/index.m3u8`

but URL pose be `https://uklon1.stream4.fun:8443/live/60e4646a5dc70-1/index.m3u8` 

in 
![image](https://user-images.githubusercontent.com/18028479/124937301-29732a80-dfff-11eb-9022-27d36426ad7b.png)

**Comment by DanielnetoDotCom** [comment]
On what page exactly are you seeing this?

**Comment by ChisdealHDYT** [comment]
> On what page exactly are you seeing this?

all pages, Live page and main view page. there a hidden space somewhere but as default RTMP works but since i adding more in Edit Live servers it has hidden spaces after `/live /` so people unable see streams with multi servers RTMP

**Comment by DanielnetoDotCom** [comment]
Check if you do not have an extra space in some of those 

![image](https://user-images.githubusercontent.com/18009293/124956063-fbd1b580-dfed-11eb-988b-36f4abbd0fa5.png)

Also I just sent an update to try to prevent it

**Comment by ChisdealHDYT** [comment]
> Check if you do not have an extra space in some of those
> 
> ![image](https://user-images.githubusercontent.com/18009293/124956152-17d55700-dfee-11eb-90cd-4f8ca88e9c56.png)
> 
> Also, I just sent an update to try to prevent it

that update did fixed that error now, i dont see hidden spaces now :) thank you. i test restream part before i close this make sure.

**Comment by ChisdealHDYT** [comment]
yep that was permit fixed you did, Restream works too
