### ISSUE TITLE
When uploading videos via encoder avideo streamer site don't play!

### ISSUE THREAD

**Issue by erdal2021** [WWBN/AVideo#5408]
AVideoLog::WARNING: externalOptions Error {"videoStartSeconds":"00:00:00"} SCRIPT_NAME: /view/index.php
PHP Notice:  Undefined variable: title in /home/.../public_html/view/include/social.php on line 13
PHP Notice:  Undefined variable: url in /home/.../public_html/view/include/social.php on line 15
Youtube embeded and bulk upload works also videos are playing.
Live stream works!
Self uploaded videos don't play!
Ubuntu 20, apache2, nginx, php7.2/7.2/7.3/7.4 cgi_wrapper fcgid fpm etc.
Thanks.

**Comment by DanielnetoDotCom** [comment]
I guess the warnings are removed on this update but I do not think they have anything to do with the videos not playing

**Comment by erdal2021** [comment]
> I guess the warnings are removed on this update but I do not think they have anything to do with the videos not playing
Hello Daniel thanks for answer.

AVideo.log
PHP Notice:  Undefined variable: title in /home/avideo/public_html/view/include/social.php on line 15
PHP Notice:  Undefined index: myVote in /home/avideo/public_html/view/modeYoutubeBottom.php on line 187
PHP Notice:  Undefined index: myVote in /home/avideo/public_html/view/modeYoutubeBottom.php on line 190

**Comment by erdal2021** [comment]
AVideoLog::WARNING: externalOptions Error {"videoStartSeconds":"00:00:00"} SCRIPT_NAME: /view/index.php
PHP Notice:  Undefined variable: title in /home/avideo/public_html/view/include/social.php on line 15
PHP Notice:  Undefined index: myVote in /home/avideo/public_html/view/modeYoutubeBottom.php on line 187
Undefined index: myVote in /home/avideo/public_html/view/modeYoutubeBottom.php on line 191

**Comment by erdal2021** [comment]
AVideoLog::WARNING: externalOptions Error {"videoStartSeconds":"00:00:00"} SCRIPT_NAME: /view/index.php
PHP Notice:  Undefined variable: title in /home/avideo/public_html/view/include/social.php on line 15

**Comment by erdal2021** [comment]
Youtube embeded upload works with sample gif but bulk upload works without sample gif.
Live stream, self uploaded videos encoding, transport and play via browser with php7.4-fpm works for me.

avideo.log
PHP Notice:  Undefined variable: title in /home/avideo/public_html/view/include/social.php on line 15
