### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by Jmwill1** [WWBN/AVideo#5412]
Hello,
When I type in my URL (peakplay.io) the server responses by generating an Index of/ then there are the two folders that are in that are in the html folder. Those folders are the YouPHPTube and YouPHPTube-Encoder folders. When I type in my domain name I would like the landing page to be the page that is displayed when peakplay.io/YouPHPTube is the URL. 
Wondering what I need to do to make the URL land clients onto the main page.
**Screenshots**
![Screenshot (4)](https://user-images.githubusercontent.com/83097148/125170069-bd193800-e172-11eb-8a93-db0108d447eb.png)
Thank you,
-Jake

**Comment by ScoobyDooWaffle** [comment]
create a virtual host file for AVideo with a command-line text editor like Nano.

sudo nano /etc/apache2/sites-available/avideo.conf

`<VirtualHost *:80>
    ServerName tube.yourdomain.com
    DocumentRoot /var/www/AVideo

    <Directory /var/www/AVideo>
       DirectoryIndex index.php
       Options +FollowSymLinks
       AllowOverride All
       Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/avideo.error.log
    CustomLog ${APACHE_LOG_DIR}/avideo.access.log combined

</VirtualHost>`

**Comment by Jmwill1** [comment]
I tried that but for some reason it didn't work. So the folders that exist are /var/www/html/ html holds both the YouPHPTube and YouPHPTube-Encoder folder. I can't find index.php file until these folders. Maybe that is part of the issue.

**Comment by Jmwill1** [comment]
It almost seems like the YouPHPTube-Encoder folder should be inside the YouPHPTube folder.
