### ISSUE TITLE
Issues with Dashboard; likes/dislikes/comments always show 0. Total Views graphs empty. Bad performance loading list of users page.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5414]
**Describe the bug**
A number of features aren't working on the dashboard

**To Reproduce**
I. Let the site run for some time with a number of users watching videos, making accounts, liking/disliking and leaving comments
II. Go to the dashboard
III. Observe 

There are a number of areas that do not appear to be working
1. Likes, Dislikes and Comments all show 0 (each category should have non-zero values)
2. Total Views ? graph never displays any data (don't know what type of graph; never seen it)
3. Color Legend always shows videos uploaded on day #1; never changes
4. Total Views pie chart never displays any data either
5. Accessing the Users page from Total Users takes a very long time (20-30 seconds with <200 users)

**Expected behavior**
1. To see Likes, Dislikes and Comments
2. To see something in the Total Views graphs
3. The Color legend to represent what is shown in the Total Views graphs

**Screenshots**
![Screen Shot 2021-07-10 at 6 45 32 PM](https://user-images.githubusercontent.com/11711050/125180525-ddb3b300-e1af-11eb-8377-88cfe58d16fc.png)

**Comment by milehighkaraoke** [comment]
I noticed my total video count on 1 video is higher than my total video count in the dashboard.... I think they are working on a new Dashboard to fix this Dashboard that does not work....
