### ISSUE TITLE
BulkEmbed  plugin – Giff Picture does not appear for video when using this option

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#5417]
Hi

When doing a search through the plugin to bulk embed videos found, it does not seem to load the gif file. I look in “my videos” and when you look at the title picture, it is not there.
Its only when I do “Get Jpeg/Gif” under the created column and refresh it then appears. It does not seem to do it automatically.
Please advise. Thanks 
![Video Picture error](https://user-images.githubusercontent.com/53856825/125200283-507d6680-e262-11eb-844c-ea9919c01095.png)

**Comment by DanielnetoDotCom** [comment]
embed requires youtube-dl , we cannot guarantee that will be possible to get thumbs from it.

“Get Jpeg/Gif”  only gets thumbs from real video files (using FFMPEG), NOT embed

**Comment by kollossus55** [comment]
ok... no probs it will only be me using the embed.. I can get it manually..

Thanks for info..

I would also just like to say thanks for the support you have given us all for getting us through our projects.
Its not often we stop and just appreciate the work you guys do.. Keep it up..😎
________________________________
