### ISSUE TITLE
Get Name automatically for Contact

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5418]
Get Name automatically for Contact
![image](https://user-images.githubusercontent.com/47063171/125202066-90fdd400-e2a4-11eb-97b8-d9fd487a2942.png)
![image](https://user-images.githubusercontent.com/47063171/125202116-bbe82800-e2a4-11eb-8307-ebb8a6e1f51b.png)

**Comment by DanielnetoDotCom** [comment]
please be clear with your question, I do not understand what you are looking for

**Comment by chenjian9885** [comment]
Obtain user name automatically
![image](https://user-images.githubusercontent.com/47063171/125730571-daf9dee8-d95a-47fa-b3f4-2a6fff1a9479.png)

**Comment by DanielnetoDotCom** [comment]
I see, do you mean on the contact form.

this update may give you the name automatically

**Comment by chenjian9885** [comment]
Thank you Daniel Neto
