### ISSUE TITLE
Get Website for Contact form automatically

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5419]
Get Website for Contact form automatically
![image](https://user-images.githubusercontent.com/47063171/125202712-6a8d6800-e2a7-11eb-9478-96efbf4c98d9.png)

**Comment by chenjian9885** [comment]
Get website automatically
![image](https://user-images.githubusercontent.com/47063171/125730718-25a3440c-b3a3-4ce0-835e-8897c6cecb16.png)

**Comment by DanielnetoDotCom** [comment]
The idea for this is the user's website, maybe this field does not make any sense there. I am thinking to remove it.

**Comment by chenjian9885** [comment]
Well, maybe it can be changed to the title is a good choice
