### ISSUE TITLE
Added funds to wallet but not getting added ,however money deducted from account

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#5420]
![image](https://user-images.githubusercontent.com/65802024/125211382-78e97d00-e2c3-11eb-9b85-8763884edfd1.png)

**Comment by DanielnetoDotCom** [comment]
seems to me you are missing/wrong stripe credentions

Also make sure you have the correct webhook

Go to the Stripe dashboard Site here (you must have a Stripe account, of course)
Before you can verify signatures, you need to retrieve your endpoint’s secret from your Dashboard’s
(Webhooks settings)[https://dashboard.stripe.com/account/webhooks].
Select an endpoint that you want to obtain the secret for, then select the Click to reveal button.
The SigningSecret will be available after your first purchase attempt, Webhook will be created automatically.

**Comment by vraghavans** [comment]
Dear Daniel,
Thanks,
Yes i had not mentioned the signing key,in the plug in.
now its fixed.
rgds
vijay
