### ISSUE TITLE
Git pull

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#5422]
Hello Daniel
I'm trying to get the latest update but i get this error message

Thank you
Ilias
![git pull](https://user-images.githubusercontent.com/60543030/125326042-e936e380-e341-11eb-970f-650cecf3f052.jpg)

**Comment by DanielnetoDotCom** [comment]
Looks like something in your DNS that cannot resolve the github.com

try to ping github.com from your server.

also try to contact your server provider

**Comment by wetubeclub** [comment]
I restarted the server and it works normally now!!

Thank you Daniel
Ilias
