### ISSUE TITLE
Meetings Not linked to live stream anymore

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5425]
it is asking for youtube key

**Comment by JoshWho** [comment]
It seems like it is using its default config file

**Comment by DanielnetoDotCom** [comment]
please make sure you clear your browser cache, here seems fine

![image](https://user-images.githubusercontent.com/18009293/125441333-d803abec-c131-47fa-83d2-4813ee63b6f2.png)

**Comment by JoshWho** [comment]
I keep seeing this when logged in on my channel
![download (1)](https://user-images.githubusercontent.com/39392449/125452433-07640613-e5b1-48c9-a9fe-0d2b0d52df12.png)

**Comment by DanielnetoDotCom** [comment]
did you clear your browser cache?

I just access it again from another PC and seems to be fine

![image](https://user-images.githubusercontent.com/18009293/125455020-090c9f54-ee18-4df7-a430-c855235aa7c9.png)

FYI if you paste the **Server URL + Stream name/key:** it should work

![image](https://user-images.githubusercontent.com/18009293/125454860-8dc9be59-66f3-4f9e-85b4-811afa7b3469.png)

**Comment by JoshWho** [comment]
ok will try that tonight

**Comment by JoshWho** [comment]
Thank you. It was a glitch with the Linux browser I think
