### ISSUE TITLE
After latest git pull Sharing video links broken

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5426]
Unusable link being propagated under share video copy to clipboard 
https%3A%2F%2Fmhktube.com%2Fv%2F367%3FchannelName%3D_608543057090e

Here is the usable link I copied from the address bar
https://mhktube.com/video/367/trump-cpac-full-speech__?channelName=_608543057090e

**Comment by DanielnetoDotCom** [comment]
Sorry about that, you are right, please check this

**Comment by milehighkaraoke** [comment]
Thank you Sir, That fixed it :)
