### ISSUE TITLE
Advertising manager

### ISSUE THREAD

**Issue by timbrookers** [WWBN/AVideo#5428]
Dear

I would like to ask about the "Advertising Manager". 
1. If i understood right, after creating the campaign  I would add video from my list, in other words from the videos which I had added to server. As many videos as I would need in certain cases.
2. The campaign will run according to the setting in the AD_Server plugin, 
But here is but...
how shall i assign specific campaign for specific user or video? is this kind of function missing or am i missing something? (I guess  specifying the user would be related to location restriction, but this is not the issue)
Because it doesn't matter how you specify the ads by campaign, if the start and end time would be similar it will play the ads randomly.

So how shall assign specific ads to video?

thanks and awaiting for your kind support

**Comment by JoshWho** [comment]
Generally for right now the Video ads is just for sitewide and only the admin can modify what videos will be added.

There is no full ad manager yet but may be a future idea for selling ad spaces and slots.

**Comment by DanielnetoDotCom** [comment]
@JoshWho is correct but we may add this feature in the future

**Comment by timbrookers** [comment]
Dear All
Surely, only admin could add the video, but my question is whether the
campaign could be assigned to the specific video.

Yours truly

Batnyam

**Comment by DanielnetoDotCom** [comment]
Hi, the campaign is not per video, it is a global configuration.

usually, the ads provider, like Google can manage and feed your video based on the content.

if you are using the [ad server plugin](https://github.com/WWBN/AVideo/wiki/Ad-Server-Plugin) it is also global and random

**Comment by timbrookers** [comment]
Hi, 
Do you think to assign the campaign to specific video would be difficult to implement?
If you would make such a improvement i might be huge advantage.

**Comment by DanielnetoDotCom** [comment]
I am just sure it will not be easy and for sure I will only do it when I find a sponsor.

**Comment by timbrookers** [comment]
Well noted
