### ISSUE TITLE
Size issues with mobile live page

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5430]
Out of place objects on mobile Live page is making dimension of page improper. 
![Screenshot_20210713-071854_Samsung Internet](https://user-images.githubusercontent.com/70327833/125547611-d206c3fa-7d37-462d-adb0-a17a9b688556.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, here is a fix for the buttons

**Comment by milehighkaraoke** [comment]
Any ideas with the padding on th main screens? The right side is not accessible on mobile as you can see in this picture. The full screen switch is almost entirely missing 

![Screenshot_20210714-145638_Samsung Internet](https://user-images.githubusercontent.com/70327833/125691803-828904c3-f221-4d65-982c-4aee02764e92.jpg)

**Comment by DanielnetoDotCom** [comment]
can you please share this page link so I can check here?

**Comment by milehighkaraoke** [comment]
It is on the chrome and Samsung  internet browser. Firefox seems to not be affected 

https://mhktube.com/video/229/mhk-mobile-on-27-may-21-23-19-02?page=1&channelName=_60814e9341c04

**Comment by DanielnetoDotCom** [comment]
Sorry but I cannot see any problem here 

![image](https://user-images.githubusercontent.com/18009293/125944704-93c7ffcb-4bdb-4513-88ea-89148a74a2c7.png)

**Comment by milehighkaraoke** [comment]
Through need to click play and then it does it

**Comment by milehighkaraoke** [comment]
Wow, that's really strange..... OK must be my device

**Comment by JoshWho** [comment]
Certain versions of mobile chrome does this. If you go to google webmaster tools and do a page inspection on the home page it shows mobile view text is too small and stuff will look like it is all smashed to the left and tiny. 

When I view the site with my phone It looks perfect so I do not know why Google Webmaster shows this but what he is describing above is what you will see when testing in webmaster tools.

I was also getting robot warnings for the Cookie Consent thing being blocked by robots.
