### ISSUE TITLE
Predefined Category Not able to select new users with over 3k users 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5431]
Seems like it can only load so many usernames then just stops and you do not see any new ones after about 1k names all on one page

![e7d9baf9-622c-4047-91fc-072acd5b4e58](https://user-images.githubusercontent.com/39392449/125611495-b488356f-74d6-407a-be70-12d7a623db50.png)

**Comment by DanielnetoDotCom** [comment]
This update may improve it

**Comment by JoshWho** [comment]
Yes works good now. Thank you @DanielnetoDotCom
