### ISSUE TITLE
Animate the Donation Button on the Chat

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5435]
Make it flash or flicker to get people to notice it. Also make the one under videos animated too.

**Comment by JoshWho** [comment]
Nothing too fancy just make the Icon image a flashing GIF or something like that

**Comment by DanielnetoDotCom** [comment]
did you try a custom CSS for it?

you probably can add a custom one

**Comment by JoshWho** [comment]
How do u replace the icon with a gif?

**Comment by JoshWho** [comment]
I found some examples

```
<div class="fa-3x">
  <i class="fas fa-spinner fa-spin"></i>
  <i class="fas fa-circle-notch fa-spin"></i>
  <i class="fas fa-sync fa-spin"></i>
  <i class="fas fa-cog fa-spin"></i>
  <i class="fas fa-spinner fa-pulse"></i>
  <i class="fas fa-stroopwafel fa-spin"></i>
</div>
```

**Comment by JoshWho** [comment]
I am not sure how the class gets replaced without it getting overwritten

**Comment by JoshWho** [comment]
I tried doing it with java but not having any success

```
<script>
document.getElementById('fas fa-donate').className = 'fas fa-donate fa-spin';
</script>
```

**Comment by DanielnetoDotCom** [comment]
do you want the button icon to rotate?

are you sure?

**Comment by DanielnetoDotCom** [comment]
What about this?

![chrome-capture (1)](https://user-images.githubusercontent.com/18009293/126778728-bd24e066-c1ca-4ea2-b7d5-e1054a8b84fe.gif)

**Comment by JoshWho** [comment]
That looks sweet!!!

**Comment by JoshWho** [comment]
> What about this?
> 
> ![chrome-capture (1)](https://user-images.githubusercontent.com/18009293/126778728-bd24e066-c1ca-4ea2-b7d5-e1054a8b84fe.gif)

Yes this one

**Comment by JoshWho** [comment]
How do I set that one?

**Comment by DanielnetoDotCom** [comment]
this will be available on the next release

**Comment by JoshWho** [comment]
Sweeeeeeet thank you

**Comment by JoshWho** [comment]
will this be a setting somewhere to change or will it just be the new default?

**Comment by DanielnetoDotCom** [comment]
You will need to update the Chat2 plugin, it will be the default behaivor.

I may release it some day this week
