### ISSUE TITLE
DVR for people watching to record and save to their local device

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5437]
Basically just a local dvr that makes it easy for people to snip a clip or record the whole thing and save to their device or computer.

**Comment by JoshWho** [comment]
<iframe width="678" height="381" src="https://www.youtube.com/embed/jIcVut4k6zc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by JoshWho** [comment]
https://youtu.be/jIcVut4k6zc

https://dev.to/dak425/add-an-animation-overlay-on-a-video-with-ffmpeg-25na

**Comment by JoshWho** [comment]
Also thinking maybe give them a temp directory that auto deletes every 24 hours or something like that.

**Comment by DanielnetoDotCom** [comment]
All those features build require a sponsor.

**Comment by JoshWho** [comment]
I hope to do that soon. People r starting to see the other platforms that claim to be free speech is really a lie. Hopefully the world starts seeing it.
