### ISSUE TITLE
Video repeat filter function

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5439]
Hello:
Daniel Neto, if you can, please add a duplicate video check plugin to prevent users from uploading duplicate videos. Both administrators and users can filter duplicate videos to delete. This will help us save disk space, thank you!

**Comment by DanielnetoDotCom** [comment]
the thing is, how is it possible? I guess it is not a simple task

**Comment by chenjian9885** [comment]
Yes, ordinary screening can only be through the video title, I wonder if it can be compared through pictures.
