### ISSUE TITLE
Disable Ads for Logged in

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5440]
Make it ad free for regular user, or video streamer. Something like this

**Comment by JoshWho** [comment]
I figured out how to do this with groups nevermind

**Comment by JoshWho** [comment]
Nevermind this is not possible yet, I just realized it is the reverse of what I am saying.

How to make it automatically join a subscription apon email activation.

**Comment by DanielnetoDotCom** [comment]
currently, we only have ads free for paid-subscription users

**Comment by JoshWho** [comment]
I just made it a subscribable free plan users can click on if they want.
