### ISSUE TITLE
SEO is all out of order on Home Page

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5442]
Site title should not show the word "Home" it should only be the site name or brand name.

Site description on the Home Page is pulling from somewhere else I am not really too sure

![a35d66fd-a786-431f-bb6f-a3f65f3c6520](https://user-images.githubusercontent.com/39392449/126067001-475dee2c-ec50-4377-9d40-165cd04c37d4.png)

OG description should be pulled from site description on the home page

it is showing

`<meta property="og:description" content="JoshWho TV"/>`

**Comment by JoshWho** [comment]
This is yahoo's latest and is the most up to date I seen with today's SEO



```
<title>Yahoo \| Mail, Weather, Search, Politics, News, Finance, Sports & Videos</title><meta http-equiv="x-dns-prefetch-control" content="on"><link rel="dns-prefetch" href="//s.yimg.com"><link rel="preconnect" href="//s.yimg.com"><link rel="dns-prefetch" href="//search.yahoo.com"><link rel="preconnect" href="//search.yahoo.com"><link rel="dns-prefetch" href="//11.at.atwola.com"><link rel="preconnect" href="//11.at.atwola.com"><link rel="dns-prefetch" href="//geo.yahoo.com"><link rel="preconnect" href="//geo.yahoo.com"><link rel="dns-prefetch" href="//video-api.yql.yahoo.com"><link rel="preconnect" href="//video-api.yql.yahoo.com">    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
--
  | <meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="theme-color" content="#ffffff"><meta name="msapplication-navbutton-color" content="red"><meta name="msapplication-TileColor" content="#ffffff"><meta name="msapplication-TileImage" content="https://s.yimg.com/cv/apiv2/social/images/yahoo_default_logo.png"><meta name="application-name" content="Yahoo"><meta name="msapplication-tap-highlight" content="no"><meta name="full-screen" content="yes"><meta name="browsermode" content="application"><meta name="nightmode" content="disable"><meta name="layoutmode" content="fitscreen"><meta name="imagemode" content="force">
  | <meta name="description" content="News, email and search are just the beginning. Discover more every day. Find your yodel.">
  | <meta name="keywords" content="yahoo, yahoo home page, yahoo homepage, yahoo search, yahoo mail, yahoo messenger, yahoo games, news, finance, sport, entertainment">
  | <meta property="og:title" content="Yahoo \| Mail, Weather, Search, Politics, News, Finance, Sports & Videos" />
  | <meta property="og:type" content='website' />
  | <meta property="og:url" content="http://www.yahoo.com" />
  | <meta property="og:description" content="News, email and search are just the beginning. Discover more every day. Find your yodel."/>
  | <meta property="og:image" content="https://s.yimg.com/cv/apiv2/social/images/yahoo_default_logo.png"/>
  | <meta property="og:site_name" content="Yahoo \| Mail, Weather, Search, Politics, News, Finance, Sports & Videos" />
  | <meta property="fb:app_id" content="458584288257241" />
  | <meta name="format-detection" content="telephone=no" />


```

**Comment by DanielnetoDotCom** [comment]
Check if this update helps

**Comment by JoshWho** [comment]
![Screenshot from 2021-07-19 07-52-20](https://user-images.githubusercontent.com/39392449/126162529-c7e3b19a-c319-4be9-83b3-cbc47a657314.png)

Just this 1 more part OG Description is just showing site title on home page

**Comment by DanielnetoDotCom** [comment]
Check this now

**Comment by JoshWho** [comment]
Nope OG Description still just says JoshWho TV

![Screenshot from 2021-07-19 08-13-13](https://user-images.githubusercontent.com/39392449/126165278-7c65dab3-fde8-4b16-8641-13697b99c282.png)

**Comment by DanielnetoDotCom** [comment]
Do you have a description on the customize plugin?

**Comment by JoshWho** [comment]
I think so

**Comment by akhilleusuggo** [comment]
Also there's no canonical pages. Without them google will never pick the right page or description. Could pick anything from anyone ( randomly by google algorithm )

**Comment by DanielnetoDotCom** [comment]
This update should add the canonical tag

**Comment by JoshWho** [comment]
Still showing
<meta property="og:description" content="JoshWho TV"/>

It should show <meta property="og:description" content="Alternative Free Speech Live Streaming Video Platform with Monetization for Creators. Start having fun creating content without suppression of your free speech.  JoshWho TV"/>

**Comment by DanielnetoDotCom** [comment]
I guess I found it

**Comment by JoshWho** [comment]
Yes all corrected now. Thank you @DanielnetoDotCom
