### ISSUE TITLE
Please add a new plug-in to the demo station to facilitate testing

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5443]
Right (Video_Location_Block
) There is a need for the plug-in, please add it to the demo site to facilitate the test and purchase
![image](https://user-images.githubusercontent.com/47063171/126094039-3a4c7a28-ff39-4967-b420-dc63001e6c2e.png)

**Comment by DanielnetoDotCom** [comment]
Hi, thanks for notice that, I just added it, please check

**Comment by chenjian9885** [comment]
Okay thank you
