### ISSUE TITLE
Channel Search takes a long time for each query

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5444]
When using Browse Channels Search it takes a long to to make any searches. Not sure why.

**Comment by DanielnetoDotCom** [comment]
I just sent a bunch of updates to improve it, please check in your site

**Comment by JoshWho** [comment]
It is a little better not sure why it does that.

**Comment by DanielnetoDotCom** [comment]
if you do not mind, truncate your videos_statistics table. it is probably huge.

truncate it or deleting the old records may improve a lot the performance.

**Comment by JoshWho** [comment]
im not sure what u mean how is that done?

**Comment by DanielnetoDotCom** [comment]
I just build a tool on the Cache plugin.

by default, this will delete 6 month old statistics

![image](https://user-images.githubusercontent.com/18009293/126650687-9e36611f-8a58-40d9-8578-6740411546b1.png)

**Comment by JoshWho** [comment]
Sweeeeeet Thank you
