### ISSUE TITLE
Invalid video region block

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5445]
Invalid video region block
![image](https://user-images.githubusercontent.com/47063171/126186246-08f78f6d-4484-4cc8-9b5d-05943108d171.png)
![image](https://user-images.githubusercontent.com/47063171/126186602-217f1c03-1f7b-4fcf-b5f1-a29b7198d687.png)
![image](https://user-images.githubusercontent.com/47063171/126186784-240aaf99-646d-495a-96c9-fd869efbd06f.png)
The video can be played normally regardless of whether it is ticked or not

**Comment by chenjian9885** [comment]
Test at the demo station

**Comment by DanielnetoDotCom** [comment]
Hi, it depends on the IP that the system is detecting. if you play it locally it will not be blocked.

if your site is public and published you must check what is your IP

what is your public IP I will check if the database location match?

**Comment by chenjian9885** [comment]
I tested it with the demo site

**Comment by chenjian9885** [comment]
Test site：https://demo.avideo.com/

**Comment by chenjian9885** [comment]
113.15.122.76


发自我的iPhone


------------------ Original ------------------
From: Daniel Neto ***@***.***&gt;
Date: Wed,Jul 21,2021 0:57 AM
To: WWBN/AVideo ***@***.***&gt;
Cc: chenjian9885 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [WWBN/AVideo] Invalid video region block (#5445)





 
Hi, it depends on the IP that the system is detecting. if you play it locally it will not be blocked.
 
if your site is public and published you must check what is your IP
 
what is your public IP I will check if the database location match?

**Comment by DanielnetoDotCom** [comment]
To make it block only China, you must check all other countries and leave china unchecked.
if must be available only in China, check only china checkbox


The Video_Location_Block depends on the User_Location plugin and its tables, I just sent an update to it

can you please update and test it to check if it is detecting correctly?

![image](https://user-images.githubusercontent.com/18009293/126381766-0f43c849-64ae-4207-9bfa-e063fb498fa1.png)

**Comment by chenjian9885** [comment]
Still invalid in: https://demo.avideo.com/
![image](https://user-images.githubusercontent.com/47063171/126430568-90a43670-ad7f-42fa-86fd-37da03552892.png)
![image](https://user-images.githubusercontent.com/47063171/126430600-a10f5d03-c4c8-4774-9c3e-186050723f2d.png)
![image](https://user-images.githubusercontent.com/47063171/126430631-25629b85-f7a2-4dce-99c1-24534698ff06.png)
![image](https://user-images.githubusercontent.com/47063171/126430662-bf1df946-f570-437a-907f-5906b9d079c9.png)
![image](https://user-images.githubusercontent.com/47063171/126430698-8697ba14-305b-4a46-afb6-9db851fa4e35.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I just install the correct tables from the user_location plugin and now the demo site should be fine.

please try again

**Comment by chenjian9885** [comment]
Ok, great

**Comment by chenjian9885** [comment]
If you just block a region, such a check will be very troublesome, I hope to add a (reverse selection) button

**Comment by DanielnetoDotCom** [comment]
You are right, I may add this in the future

**Comment by chenjian9885** [comment]
Yes, I really need this feature now, I hope to update it as soon as possible, thank you

**Comment by DanielnetoDotCom** [comment]
I just released version 2.0 that you have the Whitelist and blacklist, also a search field

![image](https://user-images.githubusercontent.com/18009293/126659153-51dc0dab-e7fa-4cc1-868e-3e7c89457f4b.png)

**Comment by chenjian9885** [comment]
Great thanks
