### ISSUE TITLE
Live previews are no longer displayed. 

### ISSUE THREAD

**Issue by Waffleuncle** [WWBN/AVideo#5446]
Hello , 
I tried to locate the problem but I can't find it. Since a few days the preview of all my live or those of others is not displayed here is a capture of what I am talking about
![image](https://user-images.githubusercontent.com/76669896/126197790-2eaf540e-6a45-4e4f-b0f3-cad8e336fe08.png)

**Comment by DanielnetoDotCom** [comment]
check your streamer and encoder logs

**Comment by Waffleuncle** [comment]
i have nothing seems anormal on logs

**Comment by JoshWho** [comment]
this only happens if the ffmpeg is not generating thumbs anymore for your streams. Has there been any changes to this?

**Comment by Waffleuncle** [comment]
ffmpeg is same as before

**Comment by JoshWho** [comment]
You did change anything with your encoder path or server?
