### ISSUE TITLE
YPT Wallet Withdraw funds page shows a error

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5450]
![ee737674-a2b5-4bc5-8903-2b28d5a09b4a](https://user-images.githubusercontent.com/39392449/126358417-24663220-893c-4b25-a0a1-edbc9c99c0fd.png)

**Comment by DanielnetoDotCom** [comment]
Fixed, please check now

**Comment by JoshWho** [comment]
Yes it is correct now thank you.
