### ISSUE TITLE
On BigVideo pages, text area for description is unbounded. When auto-switching to the next featured video, long descriptions push all the videos off the page

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5452]
**Is your feature request related to a problem? Please describe.**
I think it looks terrible when the BigVIdeo switches to a title with a long description, and it pushes all of the videos off of the page.

**Describe the solution you'd like**
Wrapping a div with a scroll bar around it.

**Describe alternatives you've considered**
Nothing tasty comes to mind.

**Additional context**
I added this code to plugin/Gallery/view/BigVideo.php - specifically I added the div that is the second line of code here, and its matching </div> at the end. It is working for me. Would be cool if it came in a future build.

```
                        <div class="mainAreaDescriptionContainer">
new-->              <div style="height:420px;border:0px solid #ccc;overflow-y:auto;overflow-x:hidden;">
                            <p class="mainAreaDescription" itemprop="description"><?php
                                if (strpos($videoRow['description'], '<br') !== false || strpos($videoRow['description'], '<p') !== false) {
                                    echo $videoRow['description'];
                                } else {
                                    echo nl2br(textToLink(htmlentities($videoRow['description'])));
                                }
                                ?></p>
new-->                 </div>
                        </div>

```

**Comment by walt93** [comment]
maybe wrap that with a conditional and add a preference 💡

**Comment by walt93** [comment]
...and don't use the above HTML it produces bad results, ouch...

**Comment by JoshWho** [comment]
Yes it needs to be shortened with some kind of blurb that allows you to expand.

**Comment by walt93** [comment]
Not a HTML guy. Maybe I need to find a cost effective Ukrainian programmer on fiverr or something. Looking into it...

**Comment by DanielnetoDotCom** [comment]
can you please screenshot of what you mean with unbounded?

**Comment by walt93** [comment]
https://user-images.githubusercontent.com/11711050/127754333-65ecda2a-de94-4c58-8c80-b60fd96b567f.mov

Ideally the textarea should remain constant size, videos should not float vertically on the page as the featured videos change.

**Comment by DanielnetoDotCom** [comment]
At the latest, you suppose to have a "More/Less" button

![chrome-capture (6)](https://user-images.githubusercontent.com/18009293/127862343-705a6306-b0b0-4d25-b835-9f85a9e595e6.gif)
