### ISSUE TITLE
Turning off auto record does not stop the recording

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5454]
there is a few channels on my site that have 24 hour streams and I want to just turn their dvr off and not everyone else. I turned off the switch on their accounts for record but it still keeps recording 8 hour streams

**Comment by DanielnetoDotCom** [comment]
Did you change your Nginx config to the manual recording?

https://github.com/WWBN/AVideo/blob/5a13122786f5b466427e4251871d9dd1f41582c1/plugin/Live/install/nginx.conf#L41

also, did you update your control file?

https://github.com/WWBN/AVideo/blob/master/plugin/Live/standAloneFiles/control.json.php

**Comment by JoshWho** [comment]
I do not know what it should look like. My config is still from the old youphptube days. a lot has changed since then.

Does manual record in config need to be on or off?

**Comment by JoshWho** [comment]
Am I supposed to comment out all those lines in the record section?

**Comment by JoshWho** [comment]
My line says this

```
			    recorder video{
   record all;
    record_path /var/www/tmp;
    record_notify on;
    #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
    record_suffix -%d-%b-%y-%T.flv;
}

```

**Comment by DanielnetoDotCom** [comment]
Should be like this

```
 recorder video{
    record all manual; 
    record_path /var/www/tmp;
    record_notify on;
    #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
    record_suffix -%d-%b-%y-%T.flv;
}
```

but keep in mind to record you must click on the record button.

also, you can choose who can record videos 

![image](https://user-images.githubusercontent.com/18009293/126652002-ae316799-4011-413b-b891-c4e6cf760f08.png)

![image](https://user-images.githubusercontent.com/18009293/126652163-76c83809-07e2-4132-8b64-00b26d8eb47a.png)

**Comment by JoshWho** [comment]
Thank you. I have it that way now.

**Comment by DanielnetoDotCom** [comment]
Test it before you need to go live

you may need to setup your controls.php

**Comment by JoshWho** [comment]
Do these settings get deleted every update?

**Comment by JoshWho** [comment]
What is this COntrol server url thing? Says Localhost 8080

**Comment by JoshWho** [comment]
> Test it before you need to go live
> 
> you may need to setup your controls.php

I can not locate controls.php what folder is this in?

**Comment by DanielnetoDotCom** [comment]
> Do these settings get deleted every update? I had all of this configured a month ago and now it is blank fields again.

It never get deleted

**Comment by DanielnetoDotCom** [comment]
> > Test it before you need to go live
> > you may need to setup your controls.php
> 
> I can not locate controls.php what folder is this in?

https://github.com/WWBN/AVideo/blob/master/plugin/Live/standAloneFiles/control.json.php

**Comment by JoshWho** [comment]
I am not using StandAlone I am using local live

**Comment by DanielnetoDotCom** [comment]
So copy that file to the server and make sure you setup the correct control url on the plugin configuration

**Comment by JoshWho** [comment]
I do have that set

**Comment by JoshWho** [comment]
https://live.joshwhotv.com/sa/standAloneFiles

**Comment by JoshWho** [comment]
![6f53abcc-4908-4e54-a785-97a997ab6b2f](https://user-images.githubusercontent.com/39392449/126826885-f6e675e9-cad8-407f-b35d-6806891a142a.png)

**Comment by JoshWho** [comment]
All fixed. Thank you @DanielnetoDotCom
