### ISSUE TITLE
(BlockonomicsYPT) Use of plug-in

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5457]
Hello Daniel Neto:
Is there a (BlockonomicsYPT) plug-in tutorial? I need this payment method, but unfortunately I don’t know how to use it
![image](https://user-images.githubusercontent.com/47063171/126554135-06ba8cd3-4159-4989-b761-20a4fb463195.png)

**Comment by DanielnetoDotCom** [comment]
I do not use it for a while but I suspect it still working.

You probably need to grab the keys from blockonomics and add them here, and also set the HTTP Callback URL on the blockonomics API

![image](https://user-images.githubusercontent.com/18009293/126653463-5eee76b5-290a-4bfa-a0c1-463ff77355d0.png)


![image](https://user-images.githubusercontent.com/18009293/126653222-070c1085-992b-455f-b24b-45d94e2bad15.png)

**Comment by DanielnetoDotCom** [comment]
I just created this for future references

https://github.com/WWBN/AVideo/wiki/BlockonomicsYPT-Plugin

**Comment by chenjian9885** [comment]
thank you very much

**Comment by chenjian9885** [comment]
Can't recharge, no submit button?
![image](https://user-images.githubusercontent.com/47063171/126813612-6c2ce786-b27a-41ef-b68e-754efe669927.png)
![image](https://user-images.githubusercontent.com/47063171/126813613-56494825-a6cd-477f-99ed-bc8fc8770e5d.png)
![image](https://user-images.githubusercontent.com/47063171/126813840-5047d06d-2977-4d7f-b3dd-9aa132c4d56a.png)
![image](https://user-images.githubusercontent.com/47063171/126813973-53156167-0485-4f16-b5d9-d0618c47cdf9.png)
![image](https://user-images.githubusercontent.com/47063171/126814038-c5ad4a76-2763-467d-9e42-e91c9986990a.png)
