### ISSUE TITLE
Change or replace these items

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5459]
I would like to know how I can delete or change these entries.
Thank you

![menù](https://user-images.githubusercontent.com/82677269/126629148-44c71f3d-6688-44f2-924a-b3629ff032d9.PNG)

**Comment by chenjian9885** [comment]
The following method can be closed
![image](https://user-images.githubusercontent.com/47063171/126636730-5fb3a4f8-cf89-4c05-b3a4-400c27a89b74.png)
![image](https://user-images.githubusercontent.com/47063171/126636839-841cec08-3d8e-40bf-ab5d-50fde13b99df.png)

**Comment by sharknetwork24** [comment]
Thanks
