### ISSUE TITLE
S3 storage plugin

### ISSUE THREAD

**Issue by Lvortex777** [WWBN/AVideo#5461]
when i turn the S3 storage pugin  on old videos will not play, i cleared cache and does not resolve issue

**Comment by DanielnetoDotCom** [comment]
Hi, it supposes to work but I could confirm this is happening in your site, I am checking and working in a fix now

**Comment by DanielnetoDotCom** [comment]
I updated your plugin, please check

**Comment by Lvortex777** [comment]
yes it seems to be working now

**Comment by Lvortex777** [comment]
so now the uploaded videos are playing but the ones encoded from livestream are not

**Comment by DanielnetoDotCom** [comment]
Please give me a sample of the one that is not playing.
please remember S3 is not compatible with HLS

**Comment by Lvortex777** [comment]
https://speakloose.com/video/49/qube-test-stream-on-07-jul-21-02-47-57?channelName=Qube this a livestream it is not playing.

**Comment by Lvortex777** [comment]
none of the livestreams previous recorded are playing

**Comment by DanielnetoDotCom** [comment]
Checking

**Comment by Lvortex777** [comment]
im trying out cloudfares cdn network is there any settings incompatible?

**Comment by DanielnetoDotCom** [comment]
Regarding the videos playing, they should be good now.

regarding Cloudflare I do not recommend, personally I do not like it due to its proxy.

I see a bunch of unpredictable errors due to the proxy

**Comment by Lvortex777** [comment]
could you list the minimum requirements for server again please.

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements

**Comment by Lvortex777** [comment]
my live stream is continuously offline ? is there something i need to do?

**Comment by DanielnetoDotCom** [comment]
Hi, what do you mean is offline?

please open a separate issue for that and post some screenshots to help explain
