### ISSUE TITLE
How to allow video download

### ISSUE THREAD

**Issue by DrDoug88** [WWBN/AVideo#5463]
Where is the button for users to download a particular video? I have configured the setting correctly in the Site Configuration (Advanced), i.e. "Allow download video" is enabled. Next, I have enabled userCanAllowFilesDownload and userCanAllowFilesDownloadSelectPerVideo in the CustomizeUser plugin. Next, I have enabled "Allow Download My Videos" for the specific user. Finally, after uploading a video either by Direct Upload or using the encoder, I have enabled "Allow Download This media" specifically for a particular video. After enabling ALL of these settings, I still do not see a method for a user to download a video. Where should the button be located? Are there any other settings that need to be modified for this to happen? I have searched everywhere, but am still unable to allow users to download certain videos.

**Comment by DanielnetoDotCom** [comment]
What do you have here?

![image](https://user-images.githubusercontent.com/18009293/126776635-2d7adadb-aed0-41ee-a815-31c9c6c08aa1.png)

**Comment by DrDoug88** [comment]
By Category...ahhh....didn't know you could limit by category, nor was I aware of that button.  Thought I had clicked on every possible button on the site. Thank you! It was the category.
