### ISSUE TITLE
Discord login

### ISSUE THREAD

**Issue by Waffleuncle** [WWBN/AVideo#5469]
It would be nice to allow users to connect via their discord.

Now many platforms allow it and I believe that it could bring a lot of people.

**Comment by DanielnetoDotCom** [comment]
For this feature you can hire me to develop

**Comment by Waffleuncle** [comment]
How much you are billing for this

**Comment by DanielnetoDotCom** [comment]
Please email me at developer@youphptube.com for a quotation
