### ISSUE TITLE
Paid subscription button going to error page.

### ISSUE THREAD

**Issue by Lvortex777** [WWBN/AVideo#5470]
Paid subscription button getting error page

**Comment by DanielnetoDotCom** [comment]
please give more details about the steps, and also a screenshot to help me understand

**Comment by Lvortex777** [comment]
During livestreams specifically when someone hits the paid subscription button an error page pops up , also known as become a fan button on desktop. I would have to be live again to take a screenshot.

**Comment by Lvortex777** [comment]
Did you ever get a chance to look at this?

**Comment by DanielnetoDotCom** [comment]
Hi, you suppose to send me a screenshot

**Comment by Lvortex777** [comment]
I will have to wait til I'll go live again to take a screenshot , but if your live the button takes you to a page that reads error.
