### ISSUE TITLE
Live video cut on two or third part

### ISSUE THREAD

**Issue by NicolasErnult** [WWBN/AVideo#5473]
Hello

I meet a problems, all live video are ok but they're all cut on 1/2/3 or 4 part.

We do big live of 4 Hours, and on live the encodeur cut on part after 1 hour of live.

How i can change for i have juste 1 live without cut. Because for replay people have 2 or 4 videos of the live.

**Comment by DanielnetoDotCom** [comment]
the public meet has 30 min livestream limit

to have it unlimited you will need your own meet server.

currently, we charge a fee for the meet server license.

100 USD/month the meet installed in your own server and 120/month we will provide you a dedicated server.

the meet requires a dedicated server

**Comment by NicolasErnult** [comment]
We use restream for do live because we share screen, guest people and live on VK and Dlive on the same time.

How we can do for don't have after live 2 videos of the live we do on 1 time (the live is ok) it's when it's finish that was cut on 2...

Now we're in live since 14h00 (French time) for end at 18h00 and every 1 hour (the live continue without problem but in media we can see that the encode generate a replay of this live. 

We have a dedicate server already and we buy a CDN with 100 To

**Comment by DanielnetoDotCom** [comment]
I see

maybe your problem is on the recorder part

check this parameter on nginx.conf

https://github.com/WWBN/AVideo/blob/c0bbab02c92020c175a5b887927e8f3452752bc0/plugin/Live/install/nginx.conf#L44

the default max file size is 2GB change it to `record_max_size 10240M;` (10GB) and restart nginx


if you are interested on a dedicated meet server please email me at developer@youphptube.com

**Comment by DanielnetoDotCom** [comment]
I do not understand what you say about 

> the live continue without problem but in media we can see that the encode generate a replay of this live.

**Comment by NicolasErnult** [comment]
I mean that we do big live of 3 Hours and sometimes 10 hours of live in one day. And during the live, the stream is ok but if i go to MEDIAS i can that the live is already encode after 1 hours of live, and do the same every 1 hour.

It's mean that after, on replay people don't see juste 1 videos but 3 or 10 videos of the live (i must change title by live part 1, part 2 etc...)

If i just change on nginx with 10240M will be fine

**Comment by DanielnetoDotCom** [comment]
Not sure what file size you need to handle up to 10 hours live, but try the 10GB and increase it in case you need,

I just hope the file does not get too big so the encoder cannot handle it.

**Comment by NicolasErnult** [comment]
ok i will try this ;)

thanks a lot for your help

**Comment by DanielnetoDotCom** [comment]
My pleasure
