### ISSUE TITLE
Google Ads showing only on top container

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#5475]
I have added codes for all the Ad and used fixed Ad sizes fo the website,however the Ad is showing only on the top container and not in other containers-but the blank container is seen,

Please advise -website:maritimeplatform.com

**Comment by DanielnetoDotCom** [comment]
I am not sure exactly, maybe google is not providing you ads

**Comment by vraghavans** [comment]
Dear Daniel,

Thanks fr the reply but then i can still see the Ad in the top container ,please advise

**Comment by DanielnetoDotCom** [comment]
Yes, but maybe Google is not providing you all the ads you are requesting or maybe is something wrong in your script
