### ISSUE TITLE
I can not turn the switch to ON not functioning for some reason

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5476]
I am not sure why but the switch just stopped working one day.

![3b30ac60-305d-4e77-8054-3e2f78dca975](https://user-images.githubusercontent.com/39392449/126888059-7e8470d0-4037-4294-bbad-8a53fafc8a58.png)

**Comment by DanielnetoDotCom** [comment]
The latest update should resolve that

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom  It works again
