### ISSUE TITLE
Chat2 Static Layout Under Video Makes Chat cover the channel Header

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5477]
Stream view
![0241ba02-1c5a-464c-b0c4-3ab646be4e39](https://user-images.githubusercontent.com/39392449/126888320-d9fba0ad-1896-4182-8033-72a1bf031a53.png)

Channel View
![a52f1d1c-ee8f-4cff-9bc2-98bfbaed9cac](https://user-images.githubusercontent.com/39392449/126888305-374c6a7f-8003-4be6-9fd9-cf1180498661.png)

**Comment by DanielnetoDotCom** [comment]
Try the Static fixed on right, that is the one that is working better, even on mobile is better

**Comment by JoshWho** [comment]
Everyone loves the chat being next to the player but this is how it makes it look on the channel page

![11136270-dbfd96a097c6bfa3de39b3c63d988ab4](https://user-images.githubusercontent.com/39392449/127086688-adcb84b3-3fb0-4d37-a1ce-d2c24ddca7e4.png)

**Comment by JoshWho** [comment]
i just disabled it on channel for now

**Comment by JoshWho** [comment]
Looks great now with static layout on the right. Thank you
