### ISSUE TITLE
Sending emails to notify subscribers will make us bear more email costs

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5478]
Each user can send an email to notify the subscriber that we will be burdened with more email costs, and I hope to choose to close it.
![image](https://user-images.githubusercontent.com/47063171/126888549-c8ae2e1c-cc66-4d1c-90e2-7ba807ee0db9.png)

**Comment by JoshWho** [comment]
I agree if you do not have your own email server this can be really costly.

**Comment by chenjian9885** [comment]
Yes, I hope Daniel Neto can update for this
