### ISSUE TITLE
P1 updated last week playback badly broken - site traffic down - usability very low

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5481]
**Describe the bug**
 Video playback is badly broken. Sits and spins. Rarely, starts playing. 

**To Reproduce**
1. Go to conspyre.tv
2. Click on a video and play it
3. See what happens 
4. Sometimes maybe, most times no - just spinning....
Safari seems most impacted
While Safari is sitting spin-locked for 1-2 minutes, launch chrome - open same video  - playback starts right away and coincidentally or not the locked safari started playing. Tried to repeat and could not. 

HELP! pls leave git co  xxxx where xxxx is a value that will unscrew my server. Thanks. 

**Expected behavior**
Video playback not to regress. 

**Error Logs**
Provide the log files at the moment you found the issue.
If you are not sure how to find the log file, please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DanielnetoDotCom** [comment]
Just tested on Chrome windows and all videos play for me

**Comment by thedailymock** [comment]
runs fine for me on chrome also. 

have you switch ubuntu to run in bbr mode instead of factory cubic? if not do so makes a huge difference.  

https://www.linuxbabe.com/ubuntu/enable-google-tcp-bbr-ubuntu#:~:text=This%20tutorial%20shows%20you%20how%20to%20enable%20TCP,orders%20of%20magnitude%20higher%20bandwidth%20and%20lower%20latency.

**Comment by walt93** [comment]
It's working great in Chrome. Its Safari both desktop and mobile that are having problems (makes sense I believe they share code). Its about 25% of my user base that are affected, playback is super sketchy. 

Did things change wrt that JS player in the last 6-8 weeks?

**Comment by DanielnetoDotCom** [comment]
I just tested my safari on a MacBook and it is working

**Comment by DanielnetoDotCom** [comment]
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/18009293/127019643-4b515ff6-b470-4028-ba26-8e1028ab80e9.png">

**Comment by walt93** [comment]
Im still getting intermittent issues from Safari where it seems the whole process is blocked, either the page spins and doesn’t load or the video doesn’t play, spins. If I launch another browser it pops right up, the page or the video. I’m getting feedback like this on social media as well. Just asked the guy what browser/so hope he responds. 
![766360A9-AC0D-4F20-B857-0773D3295B47](https://user-images.githubusercontent.com/11711050/127534146-077d07e2-7677-4ad8-8604-459b12299270.jpeg)

**Comment by walt93** [comment]
One thing, when I’m on Safari and the page load is frozen, if I ssh into the box and kill -9 the Apache process, Safari loads the page immediately when the next Apache instance picks it up. 

Anything I can do to help diagnose on my end? Dev here, more mobile/desktop but I can hack my way around if I have some clues.

**Comment by DanielnetoDotCom** [comment]
Sorry, but I cannot reproduce it on my side.

it is working fine here on the safari

**Comment by walt93** [comment]
closing this thread reopening another, the issue persists
