### ISSUE TITLE
Footer is abnormal after executing Rollback the update

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5482]
Footer is abnormal after executing Rollback the update
![image](https://user-images.githubusercontent.com/47063171/126912859-42e957c0-6b18-4e26-9761-f9ed123e2d18.png)
![image](https://user-images.githubusercontent.com/47063171/126912891-f4738d02-c3ba-455f-963f-4cc31b546225.png)

**Comment by DanielnetoDotCom** [comment]
Mine is different

![image](https://user-images.githubusercontent.com/18009293/127005750-31c713ae-1220-4a9b-a3d8-a24ed0ebb6de.png)

**Comment by chenjian9885** [comment]
I don’t know why. Both of my sites are updated with (sudo git fetch --all && sudo git reset --hard origin/master), but the results are abnormal. Are there any steps I am missing?
![image](https://user-images.githubusercontent.com/47063171/127035251-3b25cb71-5d05-4b57-a9d3-50bcffc999c2.png)

**Comment by DanielnetoDotCom** [comment]
Not sure, can you reproduce it on demo site and share the link here?

https://demo.avideo.com/

**Comment by chenjian9885** [comment]
Thanks for your answer, I think I will restore it from backup to make it normal
