### ISSUE TITLE
How or is it possible to change the alt text for the upload dropdown menu?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5484]
![download](https://user-images.githubusercontent.com/39392449/126984937-fb4bb1e3-b547-4327-9cad-91bf2b81a254.png)

Now that Live streaming is also a option in that menu it would be better to say "Create Video"  or  "Live Dashboard"   instead of submit video

**Comment by DanielnetoDotCom** [comment]
You can customize the button title

![image](https://user-images.githubusercontent.com/18009293/127018516-7f51202f-c75a-4421-950a-60dc40f0153e.png)

**Comment by JoshWho** [comment]
Yes the tiel is editable, I am talking about the text that appears when you hover your mouse over it. It is in the screenshot what the arrow is pointing to.

**Comment by DanielnetoDotCom** [comment]
No, it is not editable but I just sent an update to the text will be the same as the button title

**Comment by JoshWho** [comment]
Sweeeet Thank you!!!!!!!!!!!!
