### ISSUE TITLE
 Allowed users to upload their videos without having to do it myself in the admin area

### ISSUE THREAD

**Issue by BenjiHVG** [WWBN/AVideo#5486]
Hello, I would like my users to be able to add their video directly after their registration I have struggled for a while with avideo to find the solution do you have an idea because authorized all people one by one in the administration it may be a bit long ? thanks you for your reply

**Comment by DanielnetoDotCom** [comment]
Did you see that?

![image](https://user-images.githubusercontent.com/18009293/127037897-20c6918b-0d02-4901-abf6-33a7a0f74ea4.png)

**Comment by BenjiHVG** [comment]
Oh Thanks you very much really appreciate your help Thanks i love a video its very simple thanks you for this et thanks you for your help
