### ISSUE TITLE
nginx wont start up ?

### ISSUE THREAD

**Issue by thedailymock** [WWBN/AVideo#5487]
some reason i can not get nginx to start. was working alongside apache until i installed the rtmp module. and now nginx will not start up at all.  the command to tell it to start fails with error. i track down errors and i cant seem to get it to work.  i used the notes daniel says to use. and installed the arut rtmp module.  i have hit a point stumped on getting nginx to work or to get some kinda help from community on. 

im pretty sure its something going on with nginx.conf which i posted in the other bug/help area where installed nginx next to apache. figured maybe not getting any help cause i need to start a new question ? not sure exactly how to get a REPLY from people on githb. seems the creator of the projects doesnt like to reply to people unless you gonna pay him $.  and i watched how that went down yesterday. where he locked someone out of their server for brute forcing wrong pw. cause the password was to hard for him. so instead he brute forced and locked isev7n out of his server.  i dont use ssh and will not install ssh on my server. so to pay someone to come brute force my server is not even a option. i am willing to make someone time worth while if can help me fix. but i will not give anyone ssh access to my server. not even my self. 
my server is sitting next to me. i can physically touch it. so no need for me to use ssh. and its to much a security risk to use ssh. 

so can someone please help or point me in the direction to get nginx fixed. im thinking i have to many .conf files. cause following all these HOW to DO sites. they have all told me to be in some different.conf file to edit and all that jazz. and i think nginx is now confused. my site works. and works fast. just can not get nginx to work at all. it was working FINE until i installed the rtmp module per daniel request in these bugs. i used the arut rtmp nginx module steps. and it will not work since.

**Comment by DanielnetoDotCom** [comment]
Hi, you may try to get some help on the nginx rtmp project 

https://github.com/arut/nginx-rtmp-module

**Comment by thedailymock** [comment]
awesome ty for reply. im so stressed trying to figure it out LOL> like i swear did i spell something wrong in .conf files ill be mad at my self lol.
