### ISSUE TITLE
Disable Top Live Button Makes Live Streams Disappear COmpletely

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5488]
Now that Go live is in the drop down menu on Upload I wanted to disable the big red go live button, but when I do that it makes all the live stream s disappear and you do not even see the notification bell anymore.

![11131408-760790ee88747b206b6ee09657ef8616](https://user-images.githubusercontent.com/39392449/127072398-8e5f13dc-6740-4c19-b1a7-f7dbc3318b67.png)

**Comment by DanielnetoDotCom** [comment]
I just sent an update

the correct option is doNotShowGoLiveButton

![image](https://user-images.githubusercontent.com/18009293/127208398-ee42228d-055e-4341-a3ba-a92c1b295e9a.png)

**Comment by JoshWho** [comment]
When I disable top Live Button it still hides all the live streams and also the notification bell

![11182729-f8297d2c7ad0f3dac264bedc7375b16e](https://user-images.githubusercontent.com/39392449/127222769-9c156fc7-52be-439d-8090-bfe9188352bc.png)

**Comment by DanielnetoDotCom** [comment]
Uncheck the "hide top button" and Clear the cache

**Comment by JoshWho** [comment]
I did

**Comment by DanielnetoDotCom** [comment]
I just update your site and setup the plugin as I told you and I can see the menu as expected 

![image](https://user-images.githubusercontent.com/18009293/127225096-37bfe9ed-9a5a-4dc1-8a3a-770958da5a69.png)

**Comment by JoshWho** [comment]
Sweet, maybe i didn't update it correctly. Looks good now. Thank you.
