### ISSUE TITLE
Chat too tall on mobile. Can't click the close button

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5490]
![Screenshot_20210726-231230](https://user-images.githubusercontent.com/39392449/127094351-0a3143fb-0bdd-452e-b8d6-cae0488276cc.png)

**Comment by JoshWho** [comment]
No matter what height i enter in the plugin it stays this size

**Comment by DanielnetoDotCom** [comment]
Hi, I guess you are not using the layout I have recommended to you.

The layout you are using requires you to fine-tune it with a custom CSS

**Comment by JoshWho** [comment]
this is the Fixed Static Layout on the right

**Comment by DanielnetoDotCom** [comment]
Why this does not happen on my side?

can you please make sure you clear the cache? also the CDN cache?

**Comment by JoshWho** [comment]
Your right it looks good now. Love it. I think it was the cache.

**Comment by JoshWho** [comment]
I figured it out. It only does when Looking at the user channel on mobile. On live stream mobile  it looks fine. On the user channel mobel the Exit button is higher than the header

**Comment by DanielnetoDotCom** [comment]
Update streamer and also the Chat2 version 7.2 should resolve that

**Comment by JoshWho** [comment]
Now the chat is just stuck too the side. I hav no way to pull it out 
![Screenshot_20210729-103005](https://user-images.githubusercontent.com/39392449/127520888-d8d40a98-81d3-48c6-8b0d-4f58474e0da5.png)

**Comment by JoshWho** [comment]
If I clicked the little people button I can get it to pop out. I will enable start minimized on mobile it should do the trick.
