### ISSUE TITLE
max concurrent live viewers

### ISSUE THREAD

**Issue by ashrafpro** [WWBN/AVideo#5491]
If I am live streaming with quality 1000kbps, how many online concurrent users a dedicated server with 1 Gbps port can serve?
i.e. what is the maximum number of viewers to my live streaming

**Comment by JoshWho** [comment]
Whatever your servers max upload can handle. Sky's the limit depending on the equipment.

**Comment by ashrafpro** [comment]
> Whatever your servers max upload can handle. Sky's the limit depending on the equipment. Ram also plays a big factor in this.

![image](https://user-images.githubusercontent.com/30162293/127149998-26fe1e3e-d9d6-4aa1-b464-77fbe382dca0.png)
RAM: 256 GB - Intel Xeon E5-1650V3

can this server for example 10K live users? or there are other technologies should be used to handle this number.

**Comment by DanielnetoDotCom** [comment]
Please check this https://github.com/WWBN/AVideo/wiki/Live-Plugin#how-many-simultaneous-users-can-i-have
