### ISSUE TITLE
Option to disable chat sound

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5492]
Some kind of user switch or for now a global option. People using obs says they hear it all the time when using it in their live.

**Comment by DanielnetoDotCom** [comment]
On Chat2 version 7.1 you will have the option disableChatSound

**Comment by thedailymock** [comment]
interesting. i have never in my life used a chat  for a website that was a active chat for anything have sounds. esp for video services. that would 100% defeat the purpose ? 

does daniel make it so can get into the code of the chat service and disable the remove the chat sound ?  i was about to buy the chat plugin. but maybe ill wait now.

**Comment by DanielnetoDotCom** [comment]
The option to disable the Chat sound is already published

![image](https://user-images.githubusercontent.com/18009293/127224378-fd732f09-f4f7-43e7-a13a-e8c8bd9259d9.png)

**Comment by thedailymock** [comment]
hes the man :) 
awesome and fast. curious i am having trouble getting the command to update to work ? by chance had this issue before josh ? scratches my head.

**Comment by JoshWho** [comment]
Sweeeeeeeeeet. Thank you @DanielnetoDotCom
