### ISSUE TITLE
How to enable http2

### ISSUE THREAD

**Issue by pedro0606** [WWBN/AVideo#5493]
dear bro,
i want enable http2 for avideo.
i was fllowed this guide https://gist.github.com/GAS85/8dadbcb3c9a7ecbcb6705530c1252831
but i get a error
_sudo a2enmod mpm_event
Considering conflict mpm_worker for mpm_event:
Considering conflict mpm_prefork for mpm_event:
ERROR: Module mpm_prefork is enabled - cannot proceed due to conflicts. It needs to be disabled first!_
Can change mpm_worker to mpm_event ?
can give me the guide for http2 ?
Thank you so much !

**Comment by JoshWho** [comment]
This is not the correct place for apache2 support. Please google how to enable apache2 on ubuntu18

**Comment by pedro0606** [comment]
> This is not the correct place for apache2 support. Please google how to enable apache2 on ubuntu18

did you used http2 on your website ?
