### ISSUE TITLE
internal encoder connected to main website

### ISSUE THREAD

**Issue by daoguey** [WWBN/AVideo#5496]
the purpose of this open ticket is that I have currently a setup that is interesting.

Wan-> firewall (SSL encryption over PFsense) -> internal IP of server over http

So I am trying to connect encoder.website.com to website.com over Pfsense, the only problem I have is that the encoder cannot get into the main website.

![image](https://user-images.githubusercontent.com/15695109/127257828-74519a31-4e5a-4105-bd0c-adb6d5bfe618.png)

it stays like this and nothing:
![image](https://user-images.githubusercontent.com/15695109/127257946-45b6dedc-6e64-4711-97c3-dc62fa238671.png)

So my main question is how can I setup the encoder so it can communicate?

I tried:
1) https://website.com
2)https://website.com
3)http://website.com
4)http://internalipaddress
5)https://internalipaddress

and none of them work.

Any idea to get the encoder to work without either connecting over http and encoding in the background vs having to expose VM to internet?

**Comment by DanielnetoDotCom** [comment]
your streamer site MUST be https, NOT http

![image](https://user-images.githubusercontent.com/18009293/127374940-82d14376-fffd-4dc5-a9ff-59e0de9916cd.png)

**Comment by daoguey** [comment]
ok this was fixed now it is just weird. this is my config something seems amiss:
![image](https://user-images.githubusercontent.com/15695109/127431403-76f8b796-98cd-471a-ac98-14a284abcb91.png)

and this is the Avideo log:
![foto](https://user-images.githubusercontent.com/15695109/127431705-610f36b9-f934-45e0-bfa6-c14b7132d0b3.png)


and this is what it stays after i trigger the loading from my admin account and correct password from my main website:
![image](https://user-images.githubusercontent.com/15695109/127432053-338b839f-d1b0-4361-928d-664da9462020.png)

**Comment by daoguey** [comment]
This is the error when i click in my main website and get redirected to encoder: 
![image](https://user-images.githubusercontent.com/15695109/127435489-fb2763e8-9d3d-4680-8e71-49aed95efd66.png)

**Comment by daoguey** [comment]
and my current port forwarding is as follows:
![image](https://user-images.githubusercontent.com/15695109/127435616-e58a5d0a-4b39-460c-a7f1-2ceba82ed82e.png)

**Comment by DanielnetoDotCom** [comment]
I guess you are entering the streamer site as an HTTP and it is redirecting to HTTPS, so it is missing the post variables


![image](https://user-images.githubusercontent.com/18009293/127495160-cbeef21e-3f68-4a79-9170-5db7fa6bcd0d.png)

**Comment by daoguey** [comment]
It is on https, but it remains like that. Can you explain why it does not work? Is there a bad config in configuration.php?

**Comment by DanielnetoDotCom** [comment]
I am not sure, check your encoder log file
