### ISSUE TITLE
Starting video at specific time does not work without autoplay turned on

### ISSUE THREAD

**Issue by gunthor-hammerwurf** [WWBN/AVideo#5497]
Basically the title says it all. When I use "Copy video URL at current time" and open that URL, the video only starts at that time when autoplay is activated. If it's deactivated and I have to click the play button, it starts at the beginning.

**Comment by DanielnetoDotCom** [comment]
I just tried it on demo page and it seems to work fine.

https://demo.avideo.com/video/54/father-hillsong-featuring-steve-mcpherson-?t=164

can you please make a git pull and update to make sure we both have the same code?

**Comment by gunthor-hammerwurf** [comment]
I made a git pull and updated, same result. I also compared your settings in "CustomizeAdvance", "CustomizeUser" and "PlayerSkins" with mine and adjusted mine, didn't help.

**Comment by DanielnetoDotCom** [comment]
If I cannot reproduce I cannot help, sorry :(

Try to find a way to reproduce it on demo site.

**Comment by gunthor-hammerwurf** [comment]
I think I figured it out. Most videos on your demo site have youtube as source. And starting these videos at certain times works. The problem occurs with local videos. I uploaded a new video to the demo site and tested it with Linux/Firefox and Windows 10/Edge & Firefox:
https://demo.avideo.com/video/352/modem-sound?t=15
This should start at 15 seconds, but actually starts from the beginning.

**Comment by DanielnetoDotCom** [comment]
Did you use the encoder or did you directly upload it?

**Comment by gunthor-hammerwurf** [comment]
I made this video with OBS Studio as mp4 and uploaded it directly.

**Comment by DanielnetoDotCom** [comment]
maybe it does not have a valid codec (I am not sure what are the good ones), but if you encode it I will make sure it will have a browser compatible codec. that is why I always recommend you to use the encoder NOT the direct upload 

check this https://github.com/WWBN/AVideo/wiki/About-Video-Upload#information

**Comment by gunthor-hammerwurf** [comment]
I uploaded the video again twice.
For https://demo.avideo.com/video/355/tis-but-a-second-test?t=52 I chose HLS
and for https://demo.avideo.com/video/356/tis-but-a-third-test?t=37 I chose mp4.
Still, starting at the video at a specific time mark only works, when I'm logged in.

What happens when you open the videos by clicking the links?

**Comment by DanielnetoDotCom** [comment]
Hi, I tested both videos and logged and non-logged the start time works for me.

tested on chrome/Windows
