### ISSUE TITLE
How to enable YPTSocket

### ISSUE THREAD

**Issue by pedro0606** [WWBN/AVideo#5498]
I was enabled YPTSocket plugin
and start _sudo nohup php /var/www/html/AVideo/plugin/YPTSocket/server.php &_
but get a mes bellow when run test command _php /var/www/html/AVideo/plugin/YPTSocket/test.php_
_Please configure your webSiteRootPath_

**Comment by DanielnetoDotCom** [comment]
Check your configuration.php file

and make sure your variable is like this 

`$global['webSiteRootPath'] = '/';`

Probably it is like this 

`$global['webSiteRootPath'] = '';`

**Comment by pedro0606** [comment]
It worked fine.
Thanh so much !
