### ISSUE TITLE
Problem with email config

### ISSUE THREAD

**Issue by pedro0606** [WWBN/AVideo#5501]
Dear bro,
i can't config email
![image](https://user-images.githubusercontent.com/57143299/127461809-8c3e25c4-f7b7-4596-b574-6f985c2251e8.png)
i was tried with gmail, still the same error
what is problem ?
tks so much,

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/WWBN/AVideo/wiki/Setting-up-AVideo-Platform-to-send-emails

**Comment by pedro0606** [comment]
> Check this https://github.com/WWBN/AVideo/wiki/Setting-up-AVideo-Platform-to-send-emails

i was fllowed guide above and i was tried with gmail, the same error.

**Comment by DanielnetoDotCom** [comment]
Did you save the modifications before test it?

**Comment by pedro0606** [comment]
> Did you save the modifications before test it?

tks alot, you are pro
i think must test before save ^^_^^
Thanh you so much !
