### ISSUE TITLE
cannot change the cache directory

### ISSUE THREAD

**Issue by 01123581321345589144233** [WWBN/AVideo#5502]
when i try to change the cache directory under the cache plugin parameters the cache its not working
The directorys from the cache are not shown in the new cache directory, the user from the new path is www-data.
So with the perms is no truble. I have also aktivatet and deaktivatet the plugin but it not helps

**Comment by 01123581321345589144233** [comment]
so from /var/www/AVideo/videos/cache to /video/cache
the directroy is there with the rigt perms
the new directory is a ssd

**Comment by DanielnetoDotCom** [comment]
The cache MUST be in a public URL, but you can create a symbolic link to your SSD and move the cache folder into it

**Comment by 01123581321345589144233** [comment]
what is the default path in the plugin config ? /var/www/AVideo/cache   ?

**Comment by DanielnetoDotCom** [comment]
> what is the default path in the plugin config ? /var/www/AVideo/cache ?

correct

**Comment by 01123581321345589144233** [comment]
ok i have changed from /var/www/AVideo/videos/cache to /var/www/AVideo/cache 
i restartet the apache and reenable the cacheplugin but i not working its still in the old path.

the old /var/www/AVideo/videos/cache path is a nfs mount

**Comment by 01123581321345589144233** [comment]
i have also alot of:
[31-Jul-2021 21:35:56 Europe/Berlin] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1129 takes 0.4557 seconds to complete, Limit (0.2). /var/www/AVideo/view/index.php SCRIPT_NAME: /view/index.php

**Comment by akhilleusuggo** [comment]
You can add it via config file
`$global['tmpDir'] = /path/to/location;`

Feature requested and added here ; https://github.com/WWBN/AVideo/issues/5162

Is not perfect but does work better then symbolic link. For symlink, you may need to add more complex script specially if you're like me and you're hosting the cache dir and log file on RAM.
