### ISSUE TITLE
Video views advanced at a steady pace to 1,000 then jumped to 11,000 overnight. Cannot be substantiated by logs.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5503]
**Describe the bug**
Video counts jumped by 10,000 overnight. This cannot be seen in the site traffic in the dashboard, cannot be seen in matomo analytics, cannot be seen in any video view counts. It is a mystery

**To Reproduce**
1. Run a site for four months with a slow user growth curve
2. Watch the video view counts advance slowly, day by day to ≈1100
3. Check the dashboard the next day, 11,000
4. Check all available logs. Find zero evidence of this, sorting videos by view count - nothing stands out (I watch these things pretty often...)

**Expected behavior**
There be some indication of where those views came from.

I don't know what to make of this. I'm just reporting it in case its useful information... Dashboard needs some love anyway... 🤷‍♂️

**Comment by DanielnetoDotCom** [comment]
are you using videos on an iframe?

**Comment by walt93** [comment]
Yes I use iframe all the time, my primary means of driving the traffic to the site is automated posts to social media accounts. Will try the patch this weekend. I think one of my posts got picked up and repeated heavily. Scrolling past the iframe could have caused this.

**Comment by walt93** [comment]
Curiously, I went to check the site today - have not applied the above patch - the ≈10k views vanished as mysteriously as they appeared. FYI and FWIW.
