### ISSUE TITLE
Search only on actual channel

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#5505]
Hi Daniel and others ;-)

I am searching for a way to keep the viewer on the channel of someone.
So i have removed all Items/Links which could send the viewer away from the channel.

But there is the search left.

Here the viewer dont get only channel-specific results but content from other channels too. So he could leave the channel by this.

Is there any option like "Only search on actual channel if you are on some"?

ManyMany thanks

edit: If its not so easy an option "dont show search on channels" would be great

**Comment by DanielnetoDotCom** [comment]
I see, currently, we do not have that, but we may add it in the future. but try that 

![image](https://user-images.githubusercontent.com/18009293/127653820-fd98c756-4f11-4547-a2dd-c05135b1c8d3.png)


This may help you keep users on the channel

**Comment by morbificagent** [comment]
Hi Daniel, yes i have already used this and it helps except of the search...

**Comment by morbificagent** [comment]
Does anyone knows how to remove the search-field completely than?

**Comment by DanielnetoDotCom** [comment]
try to use a custom CSS for it

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css
