### ISSUE TITLE
Site down when intergrated with ypt CDN 

### ISSUE THREAD

**Issue by pedro0606** [WWBN/AVideo#5506]
Hi bro,
I was bought the ypt CDN

**Comment by DanielnetoDotCom** [comment]
Hi, click on the yellow rebuild button, it MUST create some CDN URLs for you and add them on the plugin parameters


if you want email me an admin credential to your site and I will setup the CDN for you

my email is developer@youphptube.com

**Comment by DanielnetoDotCom** [comment]
also refresh the plugin page, you already may have the parameters

**Comment by DanielnetoDotCom** [comment]
I did rebuild it for you and seems to be working now

**Comment by peter-kangere** [comment]
Does YPT CDN work for streaming as well or only for file uploads?

**Comment by DanielnetoDotCom** [comment]
The CDN is for livestreams and VOD videos
