### ISSUE TITLE
How to config live server parameters plugin

### ISSUE THREAD

**Issue by pedro0606** [WWBN/AVideo#5507]
Hi,
I was setup a live server completed. And it work fine
Fllow guide: https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server
This live stream demo on my server: https://live.usnba.one/live/demo/index.m3u8
What are the parameters must assign in to live plugin ?
![image](https://user-images.githubusercontent.com/57143299/127648850-4b5017fb-34b3-477a-8d60-0db01ea8a2d7.png)
And what is config on the CDN plugin ? i want use ytb CDN for both vod/live streaming.
![image](https://user-images.githubusercontent.com/57143299/127648959-03f8e8ba-5bcb-47f1-b44e-5a63dc398033.png)

**Comment by DanielnetoDotCom** [comment]
Hi

Is your nginx RTMP setup in a separated server?

There is no difference when you enable the CDN, the CDN plugin will handle the URL replace on your live servers 

I will get a external live server screenshot for you later

**Comment by DanielnetoDotCom** [comment]
Your player server is probably: https://live.usnba.one/live

Get Remote File URL, Restreamer URL, and Control URL you must copy [the standalone files](https://github.com/WWBN/AVideo/tree/master/plugin/Live/standAloneFiles) into your live server, and make sure you can execute PHP scripts in your Nginx 

After that change, click on the rebuild button in your CDN again to make sure they are sync.

![image](https://user-images.githubusercontent.com/18009293/127651712-00b29e55-11db-440f-82fc-d1996c56f15a.png)


you do not need to change anything on the CDN plugin

**Comment by DanielnetoDotCom** [comment]
Also I just notice that in your nginx 

![image](https://user-images.githubusercontent.com/18009293/127651832-032de243-1c06-4aae-8101-1efc13f333f4.png)

and your error is like those 

https://github.com/WWBN/AVideo/issues/3964
https://github.com/WWBN/AVideo/issues/3052
https://github.com/WWBN/AVideo/issues/1914

**Comment by pedro0606** [comment]
Hi @DanielnetoDotCom 
I was re-config apache on stream server and nginx.conf in the nginx-rtmp server.
1. My website was supported both http/https: http://usanba.one and https://usnba.one
2. My nginx-rtmp streaming was supported both http/https with 8080/8443 ports.
3. RTMP stat was corrected
![image](https://user-images.githubusercontent.com/57143299/127723834-fb467ac2-2675-4313-8b24-ff36c3bd634e.png)
4. I was copied Get Remote File URL, Restreamer URL, and Control URL to /usr/share/nginx/html/ on nginx-rtmp server
https://live.usnba.one:8443/getRecordedFile.php
https://live.usnba.one:8443/restreamer.json.php
https://live.usnba.one:8443/control.json.php
https://live.usnba.one:8443/saveDVR.json.php
5. i used OBS push to nginx-rtmp server OK
rtmp://inges.usnba.one/live?e=U2s5UDUzR2NnVHQ1T2dvdkdRV2YxdG1JWlVJLzI1V3FOSmM2SzVScENieXloU0p1RGtmOWtCZDZvMU5Jc2p2cA==/
Streamkey: 6100e3d3a2025-1
![image](https://user-images.githubusercontent.com/57143299/127723958-c1a54fd3-3bf9-44ca-9b3b-69c352b03129.png)
6. I was rebuiled on CDN plugin
But still show OFFLINE
![image](https://user-images.githubusercontent.com/57143299/127723989-d0d6b763-3f90-40bf-8037-ea84f2f0a336.png)
the url streaming: https://usnbaonelives1.cdn.ypt.me/6100e3d3a2025-1/index.m3u8 
![image](https://user-images.githubusercontent.com/57143299/127724065-418ce73e-ef4d-4ee2-b00c-2c9028edbef8.png)

==> correct or not ? i think it should https://usnbaonelives1.cdn.ypt.me/live/6100e3d3a2025-1/index.m3u8
![image](https://user-images.githubusercontent.com/57143299/127724034-2d10f235-d365-4071-81d7-78cae2c1619d.png)

what is problem with my config ?
Thank you so much !

**Comment by DanielnetoDotCom** [comment]
The stats seems to be fine.

First I guess you do not have PHP enabled on your nginx configuration. please check the stand alone files are not executing.

Try test stats

![image](https://user-images.githubusercontent.com/18009293/127724313-678a56ca-867f-4b43-a291-d00c29f02d34.png)

also please check your logs

**Comment by DanielnetoDotCom** [comment]
Also please rebuild your CDN

the CDN has https://live.usnba.one as a live and suppose to be https://live.usnba.one:8443

**Comment by pedro0606** [comment]
Can play the stream live but still show offline. i was upated above
Live plugin work fine
![image](https://user-images.githubusercontent.com/57143299/127724432-e4b1a58e-5db3-4c66-99d5-e64c1e23ada9.png)

**Comment by DanielnetoDotCom** [comment]
Check if your live is listed

![image](https://user-images.githubusercontent.com/18009293/127724578-afed10fa-2687-45fb-b6a0-505492a17baa.png)

**Comment by pedro0606** [comment]
where i can check it ? i didn't found it

**Comment by DanielnetoDotCom** [comment]
![chrome-capture (5)](https://user-images.githubusercontent.com/18009293/127724870-36e1b96f-d6c8-4721-b0b4-a62c26627bdc.gif)

**Comment by pedro0606** [comment]
I was enabled it. it still offline and didn't show in first page
![image](https://user-images.githubusercontent.com/57143299/127725183-1d76966c-ca1a-4046-881c-fdbdb56c2bee.png)
is mistake with live plugin config ?
![image](https://user-images.githubusercontent.com/57143299/127725214-b04cad79-d3af-42ab-8821-8161f6cd01ae.png)
![image](https://user-images.githubusercontent.com/57143299/127725239-e06cda9d-043c-4063-a748-8e5f0af9eaa0.png)

**Comment by DanielnetoDotCom** [comment]
Your stats is NOT 

https://live.usnba.one:8443/stat.xsl but it MUST be https://live.usnba.one:8443/stats

Your control URL should be https://live.usnba.one:8443/control.json.php

**Comment by pedro0606** [comment]
What is Control URL ?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Live-Plugin#control

**Comment by pedro0606** [comment]
I was checked, can play but still OFFLINE
![image](https://user-images.githubusercontent.com/57143299/127725715-b2442d7c-d762-4697-9640-db2feba46384.png)
and i found a problem, all user the same Stream name/key ? what is this problem ?

**Comment by DanielnetoDotCom** [comment]
Hi, same stream key does not suppose to work

**Comment by pedro0606** [comment]
i was re-instaled nginx-rtmp on the stream server. all fine.
so complex when install nginx-rtmp on other server
