### ISSUE TITLE
When we look for a channel on the search, nothing happens

### ISSUE THREAD

**Issue by BenjiHVG** [WWBN/AVideo#5508]
Hello When I look for a channel on the home page of my site it does not work it returns me no results is normal? or is there a magic button to correct this?

**Comment by DanielnetoDotCom** [comment]
check your log file

**Comment by BenjiHVG** [comment]
![image](https://user-images.githubusercontent.com/57715790/127663781-970e9b1b-1abb-4a9b-9baa-ff62134860bc.png)
Who resolved that ?

**Comment by BenjiHVG** [comment]
I specify I have to look for my own account
