### ISSUE TITLE
Video -> Group = Under Maintenance or 403

### ISSUE THREAD

**Issue by morbificagent** [WWBN/AVideo#5509]
Hi Daniel and all the others,

actually i am trying to restrict the access to some files via a group.

So i created a Group "Group2021" and assigned it to a video:

![grafik](https://user-images.githubusercontent.com/50199132/127660284-6e000e68-a42e-42a8-a808-653022ac359a.png)

The result is: If i am not member of this group i get on your demo site:

![grafik](https://user-images.githubusercontent.com/50199132/127660366-33ab97de-14ec-4057-8ece-661adad55172.png)

And on my site:

![grafik](https://user-images.githubusercontent.com/50199132/127660216-e331be4b-062e-4e8c-8e94-7bf7185e7149.png)

**But there has to be a message "You have no rights on this file" or something the user understands and can navigate back.**

**Comment by DanielnetoDotCom** [comment]
Hi, this was an outdated plugin

please try again on demo site

**Comment by morbificagent** [comment]
Yes its working on the demo site now... will try to find out why its a problem on my site... eventually something outdated too.

Thanks
