### ISSUE TITLE
Embed Issue

### ISSUE THREAD

**Issue by shanesipe** [WWBN/AVideo#5510]
**Describe the bug**
When you embed then live embed code it only works for about 1.5 hours before logging out from your website leaving the avideo login page in its place.  when embeding a channel stream it should have a permanent keep alive or lock to one stream.

For Example view patriotnewsnetwork.us

**Comment by shanesipe** [comment]
Is this a setting we goofed up

**Comment by DanielnetoDotCom** [comment]
if you are embedding in a different domain, it not even should work because of the cross-domain policy that does not allow us to save cookies and keep the domain record

**Comment by shanesipe** [comment]
Would it be possible to cookie that embed to keep alive on other domains?

**Comment by DanielnetoDotCom** [comment]
Sorry is not possible to save cookies on crossdomains

**Comment by DanielnetoDotCom** [comment]
But, the video count should be fixed now , this error should not happen anymore on the latest update
