### ISSUE TITLE
Discord Chat Function

### ISSUE THREAD

**Issue by shanesipe** [WWBN/AVideo#5511]
**Is your feature request related to a problem? Please describe.**
I have streamers who are looking for a chat tie in to discord chat function or the ability to have discord chat plugin to activate for the streamers to integrate with.

**Comment by DanielnetoDotCom** [comment]
what exactly is that?

**Comment by shanesipe** [comment]
It is another chat feature that people have with other platforms

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom it's API integration

@shanesipe You can also add it manually on plugin customize advance plugin ( on html section, add the discord there )

**Comment by shanesipe** [comment]
How do you make it available to the individual users that want to use it.

**Comment by shanesipe** [comment]
Need to be able to allow the user to be able to add their discord chat to their channel instead of a universal one.

**Comment by JoshWho** [comment]
This sounds very interesting, and will make chat compatible with resream.io

**Comment by shanesipe** [comment]
Exactly I am trying to figure it out I have hundreds of people hitting the site every day and not able to chat with the host without host having the chat open.

**Comment by JoshWho** [comment]
Here is another project that will work https://widgetbot.io/

**Comment by DanielnetoDotCom** [comment]
Chat2 version 7.4 you can allow users to use their own embed code for any external chat. this code will replace the regulat chat

![image](https://user-images.githubusercontent.com/18009293/128250123-0b13bd20-d535-4407-a1eb-818e0f8846bf.png)

![image](https://user-images.githubusercontent.com/18009293/128250181-2f15fc8e-178e-43f3-a2cb-b527763663f4.png)

**Comment by JoshWho** [comment]
That is AWESOME!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by shanesipe** [comment]
I am testing it out  are we supposed to use our own Iframe embed because I am have a tough go making it work

**Comment by JoshWho** [comment]
Works Great I have it working. Get your titan embed link from here https://titanembeds.com

**Comment by JoshWho** [comment]
just made a tut here https://www.joshwhotv.net/2021/08/04/discord-chat-is-now-a-option-for-your-live-streams-and-profile/

**Comment by shanesipe** [comment]
Does it work for you as channel streamer

**Comment by JoshWho** [comment]
yes

**Comment by shanesipe** [comment]
I now have it up just covers half the screen

**Comment by JoshWho** [comment]
You can change the template in the chat settings. 

How come other users that are not using Discord see a maintenance page and no chat?

![57b230d1-3e7e-41f9-803b-b52b4f118d62](https://user-images.githubusercontent.com/39392449/128258968-0aa76103-5e98-47e8-9fc6-47a0a7a43a06.png)

**Comment by JoshWho** [comment]
> I now have it up just covers half the screen

You can change the template in the chat settings.

**Comment by shanesipe** [comment]
![image](https://user-images.githubusercontent.com/16483068/128268848-6e22b03c-7765-49ad-a94f-f8ff687c1f7c.jpeg)

**Comment by shanesipe** [comment]
Where at

**Comment by JoshWho** [comment]
scroll down more

**Comment by shanesipe** [comment]
![image](https://user-images.githubusercontent.com/16483068/128269419-51284984-4428-4594-b752-3f8d079a9cc4.jpeg)

**Comment by JoshWho** [comment]
Is there no more dropdown for Static and Template Left or RIght?

**Comment by shanesipe** [comment]
Not that I see

**Comment by JoshWho** [comment]
![e10422a5-fa22-4cd1-9b6f-5a7fd7ea737a](https://user-images.githubusercontent.com/39392449/128274108-d2ce3b88-236d-493e-998c-8a4ed56654ee.png)

**Comment by shanesipe** [comment]
Not on my end there isn't

**Comment by JoshWho** [comment]
need to update

**Comment by shanesipe** [comment]
I just updated it

**Comment by shanesipe** [comment]
Nothing

**Comment by JoshWho** [comment]
@DanielnetoDotCom is there any way to make it like "if no link in embed box" than "use local chat setting"?

**Comment by JoshWho** [comment]
This is so cool I love it. This really changes the game

**Comment by JoshWho** [comment]
Nevermind I just did a Git pull and now both chats work. Sweet thank you @DanielnetoDotCom

**Comment by shanesipe** [comment]
How do we get the layout selection to show

**Comment by shanesipe** [comment]
I am trying to restrict to bottom of screen and don't have drop downs at all

**Comment by shanesipe** [comment]
@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Hi,

First, make sure you have the plugin Chat2 version 7.4

Then try to delete the plugin parameters. 

![chrome-capture (1)](https://user-images.githubusercontent.com/18009293/129594569-c2b150e3-cb72-4cc5-ac7d-7964043270c8.gif)
