### ISSUE TITLE
Continuing to have performance issues, video load issues, Safari desktop and Mobile Safari (i.e. every possible browser on iOS)

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5512]
**Describe the bug**
After a recent update, I am seeing much less site traffic and nothing has changed about my marketing.
I am seeing on Desktop safari that videos don't load, spin forever.
Same on iOS, Safari, Brave (whatever, it doesn't matter, all browsers on iOS are window dressing over WebKit) 
I am staring at my iPhone which has been spinning trying to play a video for 3 minutes. I launched Desktop Chrome and it plays immediately.
I am getting comments like this on social media
![IMG_54DC19DA40C5-1](https://user-images.githubusercontent.com/11711050/127712648-3ca4141d-ca5d-4e43-a29d-596112c11ecd.jpeg)
I test this daily
It does not appear to be all media, only a subset.  One example posted below, watching it fail to play as I type this.

**To Reproduce**
1. Go to conspyre.tv from any WebKit browser (Mac OS: Safari, iOS: Any)
2. Try to play a video https://conspyre.tv/video/7436/richard-bandler---persuasion-engineering---8of8
3. Watch it spin
4. Try a real browser
5. Watch it play

**Expected behavior**
It to work for all of my users. ≈45% were on iPhone before I took an update ≈2 weeks ago. 
![Screen Shot 2021-07-30 at 2 23 27 PM](https://user-images.githubusercontent.com/11711050/127713021-726c5687-7495-4ea5-ae60-836ee94b5789.png)

** Datapoint **
While MacOS Safari is stalled loading, if I ssh into the box I can see an Apache2 process stuck at 100% CPU.

If I "sudo kill -9" that PID, Safari immediately loads the page it has been stalled on for 2-3 minutes.

**What can I do**
How can I collect further data to diagnose/debug? This seems low level.

**Comment by DanielnetoDotCom** [comment]
I just tested the movie you have mention and it works fine on macos chrome and safari

![image](https://user-images.githubusercontent.com/18009293/127740230-fbf70f7c-3d7f-4c6c-bb3a-5fa666895903.png)

![image](https://user-images.githubusercontent.com/18009293/127740346-55cb7cd8-6d2c-4162-8e4d-4395b3b0019e.png)



but on safari the first attempt I got this 

![image](https://user-images.githubusercontent.com/18009293/127740297-504a8a49-7db3-4271-bfa7-9bec0c1a2a26.png)

this is probably related to your server performance

https://github.com/WWBN/AVideo/wiki/Speed-up-your-page

maybe is a bandwidth problem, try our CDN https://github.com/WWBN/AVideo/wiki/CDN-Plugin

**Comment by walt93** [comment]
Thanks for the guidance!
