### ISSUE TITLE
php script to print source filename

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#5514]
Hello @DanielnetoDotCom 

Could you add a php script on `/install` dir to print the source filename based on the video ID, and vice-versa ?

Example, example.com/v/200

The video ID is 200, but what files does correspond to it? Must be checked manually from the DB.

Same goes to files that are located on the videos/ dir, and would like to know witch ID they have.

Thank you :)

**Comment by DanielnetoDotCom** [comment]
Hi, did you try the API?

https://demo.avideo.com/plugin/API/get.json.php?APIName=video_file&videos_id=70&APISecret=cf8639790c9a14fa1b01b8beb3f5565c
