### ISSUE TITLE
Questions on CDN - how to move existing server/files?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5515]
**Describe the question**
I set up a server with a 11.7TB RAID and it's currently ≈40% full.

What is the strategy to move this to a CDN? Build a 2nd server, clone, and point the DNS at it? Possible to do in-place?
Is there a script to clone all of the data? How does this work?...

What would be the difference between using an AWS clone like Backblaze or Wasabi vs. using the AVideo CDN?

**Comment by DanielnetoDotCom** [comment]
Hi, 

a CDN is not to resolve a storage space problem, [a CDN](https://github.com/WWBN/AVideo/wiki/CDN-Plugin) is to resolve a bandwidth problem

for storage, you can read this https://github.com/WWBN/AVideo/wiki/Storage-Options

**Comment by walt93** [comment]
I’m not tracking you. With a CDN isn’t the data replicated?

**Comment by DanielnetoDotCom** [comment]
It is but it will not be permanent. it is replicated only over demmand.

to store your videos you will need something else.

**Comment by walt93** [comment]
Ok I was thinking of Backblaze which pairs storage with Cloudflare CDN service and conflating the two.

My RAID is suffering from bad performance, md5_resync is running for hours on end. I need to figure out how to do a full backup, and I'm thinking its time to move my data somewhere else. I'm looking for advice on how best to proceed and plan out my setup. 

How best to proceed with getting advice, Github  interface is too narrow lol. Book a consult:?

**Comment by DanielnetoDotCom** [comment]
you can get Backblaze and it may work for MP4 files (does not work for HLS)

to move all the existing video files to the Backblaze may require some code and you can hire me for that.

regarding rsync in my opinion this is a great tool to backup the AVideo
