### ISSUE TITLE
Help! I have 100s of files that didn't encode properly. I can find them from the filesystem. How to efficiently remove?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5516]
**Describe the question**
I have thousands of transcoded files, and some % of them failed the encoder process. 
It would literally take days to comb through manually.
I found in the filesystem why these files do not play, they do not have .mp4 files (only gif jpg and webp + a database entry)

How can I efficiently purge all of these from my database? 

**Screenshots**

    ./video_210602000438_befd:
    video_210602000438_befd.gif
    video_210602000438_befd.jpg
    video_210602000438_befd_thumbsV2.jpg
    video_210602000438_befd.webp

    ./video_210604002823_3af4:
    video_210604002823_3af4.gif
    video_210604002823_3af4.jpg
    video_210604002823_3af4_thumbsV2.jpg
    video_210604002823_3af4.webp

    ./video_210604005246_0a27:
    video_210604005246_0a27.gif
    video_210604005246_0a27.jpg
    video_210604005246_0a27_thumbsV2.jpg
    video_210604005246_0a27.webp

   .... directory listing is >3mb of text

**Comment by milehighkaraoke** [comment]
Remove by logging into encoder as admin and then delete

**Comment by walt93** [comment]
I'm not tracking you. How do you do that from the encoder?

**Comment by milehighkaraoke** [comment]
![Screenshot_20210801-153329_Samsung Internet](https://user-images.githubusercontent.com/70327833/127786297-6cd2226a-1b68-457f-8923-8e822faf0b08.jpg)

Everything that is error will show up here.   You must be logged into the encoder as Admin to see these options.

**Comment by walt93** [comment]
That would have worked when I first encoded them. These I encoded when I spun the site up 4 months ago. 

Really AVideo should not present these to the user as if they can be played. If there is no MP4, then why do we let the user see a page and have a play button?
