### ISSUE TITLE
Shows live under upload with no live streams

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5517]
Is this a feature to let us know that live is encoding?
![Screenshot_20210801-015213_Samsung Internet](https://user-images.githubusercontent.com/70327833/127763740-5cfb4029-8cc2-42f3-9db7-3f8050d18043.jpg)

**Comment by DanielnetoDotCom** [comment]
Sorry I am not understanding your question

**Comment by milehighkaraoke** [comment]
When you go to upload there 8s now a blinking red Live icon  even when I am not broadcasting

**Comment by DanielnetoDotCom** [comment]
Correct, it is only blinking, does not mean it is streaming.

**Comment by milehighkaraoke** [comment]
What is the function of this icion?
