### ISSUE TITLE
If the encoder fails to produce an MP4 file, why do we allow the user to see it?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5518]
**Describe the bug**
I encoded over 2000 files when I started my site by filling the encoder queue for days at a time… I am now going through great pain clicking each one, seeing if it plays, deleting it when it does not. It is taking hours. I claim if no MP4 file was transcoded (looking in the filesystem you can see there are webp and jpg files but no mp4) then we should not be presenting this to the user.

**To Reproduce**
1. Go to your archive of 10 year old avi files
2. Throw a bunch in the transcoder
3. Observe many database entries created, poster frames, etc. but some of these files do not play
4. Track one down by looking in the HTML to find the folder name, check that folder on the filesystem, sure enough - no MP4

**Expected behavior**
Files that fail to transcode, do not get presented to the user.

**Comment by DanielnetoDotCom** [comment]
The easiest way is to drop the encoder database, delete the encoder videos folder and run the installation again.

this will make you a clean encoder

**Comment by walt93** [comment]
I must not be understanding you Daniel. The bad encodes are all in the videos_streamer folder.

**Comment by walt93** [comment]
Here is an example: https://conspyre.tv/video/1382/enemy-image 

looking at the HTML we find https://conspyre.tv/videos/`_YPTuniqid_604dde78126a85.33686165

/mnt/md0/videos_streamer/_YPTuniqid_604dde78126a85.33686165$ ls
_YPTuniqid_604dde78126a85.33686165.gif
_YPTuniqid_604dde78126a85.33686165.jpg
_YPTuniqid_604dde78126a85.33686165.notfound
_YPTuniqid_604dde78126a85.33686165.webp

Not all have the .notfound, or the .gif, many just have the .jpg and .webp

**Comment by DanielnetoDotCom** [comment]
I see, do you mean when an encoding process fails the video files stay on the server.

to remove them you can just delete them from the queue

**Comment by walt93** [comment]
These are in the streamer folder, not the encoder. 

If I delete them will something cleanup the database so these files aren’t showing to the user?

**Comment by JoshWho** [comment]
Auto Purge Errored Encode or something like that needed

**Comment by aleksis82** [comment]
Hi. How I can disable file encoding for uploaded files?

**Comment by DanielnetoDotCom** [comment]
do you want to only allow download (youtube-dl) and do not allow upload a file to the encoder?
