### ISSUE TITLE
From My Videos page, the links to get the list of videos only return a partial list

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5519]
**Describe the bug**
"Download your vides list (SEO .txt file)" and "Download your videos list (Permalink .txt file)" only return a partial list of videos

**To Reproduce**
1. Go to My Videos
2. Click on "Download your vides list (SEO .txt file)" and "Download your videos list (Permalink .txt file)"
3. Scroll to the end of the list
4. In my case, see the last video's number is 1894 (both lists end at the same video). My last video is number 7723. There are almost 6,000 videos missing from both  lists.

**Expected behavior**
To see all videos in each list

**Comment by walt93** [comment]
I am attempting to "automate" my manually checking every !@#$% one of 7,723 videos to look for files that failed to encode.

This is taking forever. Literally spent my weekend very painfully cleaning the first 1,000 files.  I do have better things to do with my time!

It will take much, much longer if I cannot get the lists of these videos!!!

**Comment by walt93** [comment]
It would be nice if AVideo didn't throw my users under a bus because the encoder failed...

**Comment by DanielnetoDotCom** [comment]
I am not sure what you are looking for and what does it return to you.

**Comment by walt93** [comment]
![Screen Shot 2021-08-02 at 5 49 43 PM](https://user-images.githubusercontent.com/11711050/127941303-c7099897-8a3e-4c1e-b3a3-c2fdb07810b0.jpg)

**Comment by DanielnetoDotCom** [comment]
Try to add this in your configuration.php

```
$global['limitForUnlimitedVideos'] = 99999;
$global['rowCount'] = 99999;
```

Check this for reference

https://github.com/WWBN/AVideo/wiki/Configuration.php-variable-(-some-are-hidden-)
