### ISSUE TITLE
Unable to open website

### ISSUE THREAD

**Issue by Lvortex777** [WWBN/AVideo#5522]
#
![Screenshot_2021-08-02-06-32-35-882](https://user-images.githubusercontent.com/86401367/127856089-5d73a1e9-9e44-40ec-a880-e1f7f1b23de0.jpg)

**Comment by DanielnetoDotCom** [comment]
You are having a problem with your DNS, check with your domain provider

**Comment by Lvortex777** [comment]
![Screenshot_2021-08-02-07-54-51-684](https://user-images.githubusercontent.com/86401367/127865421-b1d8040e-8b4a-47ca-b2ac-b431b6813ad1.jpg)

**Comment by Lvortex777** [comment]
![Screenshot_2021-08-02-07-58-11-389](https://user-images.githubusercontent.com/86401367/127865865-751b2b50-70e6-4614-8117-7df516bb817f.jpg)

**Comment by Lvortex777** [comment]
What should I do please.

**Comment by Lvortex777** [comment]
![Screenshot_2021-08-02-08-04-58-215](https://user-images.githubusercontent.com/86401367/127866626-92db1c87-9a98-4c3b-abe7-854f21d02e3f.jpg)

**Comment by Lvortex777** [comment]
I have host gator online just waiting for your response

**Comment by DanielnetoDotCom** [comment]
I do not have control over this domain

![image](https://user-images.githubusercontent.com/18009293/127870747-cfc1da09-e216-4ce8-8a89-75e813505635.png)


you need to deal with it directly with the hostgator

**Comment by Lvortex777** [comment]
The dns servers are cloudflare correct? So how can hostgator update cloudflare dns records and ipaddress?

**Comment by Lvortex777** [comment]
This is the message they sent

**Comment by Lvortex777** [comment]
![Screenshot_2021-08-02-08-44-00-719](https://user-images.githubusercontent.com/86401367/127871608-38662494-acb8-438b-97d0-377a5e8d9c11.jpg)

**Comment by Lvortex777** [comment]
So it looks like I need to add speakloose on cloudflare dashboard and update the ipaddress

**Comment by DanielnetoDotCom** [comment]
Done, please check it now

**Comment by milehighkaraoke** [comment]
You need to point your dns to your WAN IP
