### ISSUE TITLE
chat2

### ISSUE THREAD

**Issue by GarethBagley** [WWBN/AVideo#5523]
Is it possible to open up the chat function, so users with no inlogg can chat? Is there a tick box for this? 
Thankyou
//

**Comment by DanielnetoDotCom** [comment]
Currently, we require the user to be logged in to be able to chat.

**Comment by walt93** [comment]
Opinion: The internet being what it is, probably it's not wise to have an open chat. Seems a liability.

**Comment by GarethBagley** [comment]
I agree. It's just that we had an event and wanted to use open interaction. Is it possible to import chat from other platforms? Say instagram or something?

**Comment by DanielnetoDotCom** [comment]
If they provide an embed code you may add a custom js on your site

**Comment by Lordblanca** [comment]
Can we add 1 chat to multiple sites at a time and if so how. Thanks

**Comment by DanielnetoDotCom** [comment]
you can use the embed code

**Comment by Lordblanca** [comment]
Thanks I Found It After I asked. My apologies for not taking down the
post/request
