### ISSUE TITLE
How to show live broadcast to the first page in Netflix theme

### ISSUE THREAD

**Issue by pedro0606** [WWBN/AVideo#5524]
Hi Neto,
Can you help me. How to show the live broadcasst (live/live links) on the first page in the Netflix theme ?
I was tried with Gallery theme is OK
![image](https://user-images.githubusercontent.com/57143299/127879495-21b3a536-4f10-4266-b487-47b2e9c04a78.png)
Thank you so much !

**Comment by DanielnetoDotCom** [comment]
Hi, I will probably add this in the future, for now I am waiting for a sponsor for this feature
