### ISSUE TITLE
Square Merchant

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5525]
Can I use Square instead of paypal for receiving payment. And have it intergrate in to the server. And if so how to do it. 
thank you

**Comment by DanielnetoDotCom** [comment]
To add any other payment method requires development and code.

It may be added it the Square provide an API and if you are willing to pay for this new feature

**Comment by Lordblanca** [comment]
Sure How Much to add square intergration
I think adding a store and also an optional payment plan to the server would be a great feature for everyone.
2. Also how much to add google pay, Apple pay, Cash app, and zelle.
3. I think this would be a great additional feature to add as plugins. I know I will pay for them as a plug ins, giving my subscribers different payment method. Instead of just paypal

**Comment by DanielnetoDotCom** [comment]
for a quotation please email me at developer@youphptube.com

**Comment by Waffleuncle** [comment]
> for a quotation please email me at [developer@youphptube.com](mailto:developer@youphptube.com)

I think this might interest more than one person. 
But only if you develop the application plugins for a public purchase

**Comment by redilee** [comment]
Additional payment processors would be good options.

**Comment by Lordblanca** [comment]
We should have google pay, Apple pay, Cash app, Zelle
And they all should be paid plug ins. This will help to keep the network
funded
