### ISSUE TITLE
Can files by removed from the encoder's videos directory?

### ISSUE THREAD

**Issue by gregk63** [WWBN/AVideo#5526]
**Describe the question**
There are a lot of files in the encoder's videos directory. Should there be? Can I remove them? The files are large and I can recoup space. It seems to me that I have seen that it is ok somewhere but I am not finding it. Please forgive me if this a dup of something I have already asked.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
Yes you can remove them (if you are not encoding)

the only required file is the configuration.php

To avoid it, make sure you have this option checked

![image](https://user-images.githubusercontent.com/18009293/128042387-aaee2644-adcb-4e47-b7ee-0fb8e2113f4f.png)

**Comment by gregk63** [comment]
Thank you! I was able to recover a lot space by deleting them. I do have Auto Remove set. I think the files were from something I did. Been watching the videos directory and Auto remove is keeping the directory clean!

Ill close this issue. Thanks!
