### ISSUE TITLE
avideo sign up / register 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#5527]
Can't get past this page with any email address.
![Screenshot_20210802-221657_Fakeotube.jpg](https://user-images.githubusercontent.com/66537018/127947187-69aababe-1fc4-4b6b-a17b-2e7a1d45c300.jpg)

**Comment by DanielnetoDotCom** [comment]
I am not sure exactly where this error comes from

I guess you have this checked emailMustBeUnique

![image](https://user-images.githubusercontent.com/18009293/128049147-baec47d7-7e45-467d-bd4b-06c8af2c44e9.png)

And this email may already be used, I just tested it locally and it works

**Comment by fakeologist** [comment]
I tried many different emails from the app and all of them gave me the error.
The error message should also read "a valid".

**Comment by DanielnetoDotCom** [comment]
Thanks, I am sending a fix for the typo.

do you get the same error on the site?

also, please try again and share your screenshot, I have added more info regarding a debug help

**Comment by fakeologist** [comment]
no error on website. app only.

**Comment by DanielnetoDotCom** [comment]
Please update your streamer, try again and share the screenshot
