### ISSUE TITLE
Site won't come up after installing update chat from 7.1 to 7.2

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5529]
https://lblivestream.com/
In edge it comes up

array(4) { ["type"]=> int(1) ["message"]=> string(613) "Uncaught Error: Call to undefined function isChannelPage() in /var/www/html/AVideo/plugin/Chat2/Chat2.php(18) : eval()'d code(1) : eval()'d code:107 Stack trace: #0 /var/www/html/AVideo/plugin/Chat2/Chat2.php(18) : eval()'d code(1) : eval()'d code(448): Chat2::getLayout() #1 /var/www/html/AVideo/plugin/AVideoPlugin.php(62): Chat2->getHeadCode() #2 /var/www/html/AVideo/view/include/head.php(3): AVideoPlugin::getHeadCode() #3 /var/www/html/AVideo/plugin/YouPHPFlix2/view/modeFlix.php(20): include('/var/www/html/A...') #4 /var/www/html/AVideo/view/index.php(38): require('/var/www/html/A...') #5 {main} thrown" ["file"]=> string(82) "/var/www/html/AVideo/plugin/Chat2/Chat2.php(18) : eval()'d code(1) : eval()'d code" ["line"]=> int(107) }

In Firefox it says Under Maintance

**Comment by DanielnetoDotCom** [comment]
Please make a git pull in your streamer

**Comment by Lordblanca** [comment]
ok

**Comment by Lordblanca** [comment]
can't find my notes on the code what is it please

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by Lordblanca** [comment]
Thank You :)

**Comment by Lordblanca** [comment]
Much better config in 11.3. having the configuration tab separate makes for a clean look less clutter

**Comment by Lordblanca** [comment]
So about how much to integrate Square Into  the server

**Comment by DanielnetoDotCom** [comment]
Hi

please email me at developer@youphptube.com for a quotation
