### ISSUE TITLE
Google Adsense

### ISSUE THREAD

**Issue by balasi67** [WWBN/AVideo#5531]
Hi there, Just got accepted for Google Adsense on my website,

Struggling to find out how to actually apply the ads to my site. Are there any tutorials or can someone comment how to do it 

Thanks

**Comment by Waffleuncle** [comment]
> Hi there, Just got accepted for Google Adsense on my website,
> 
> Struggling to find out how to actually apply the ads to my site. Are there any tutorials or can someone comment how to do it
> 
> Thanks

https://github.com/WWBN/AVideo/wiki/AD_Overlay-Plugin
![image](https://user-images.githubusercontent.com/76669896/128245061-7c554f5f-d667-4839-9c2e-41ab3895cdc0.png)

Next time try opening your eyes?
