### ISSUE TITLE
Where I can change the FHD autoplay

### ISSUE THREAD

**Issue by Waffleuncle** [WWBN/AVideo#5532]
Where I can change the FHD autoplay

![image](https://user-images.githubusercontent.com/76669896/128244730-30d31144-e7e8-4ea3-91ac-6bdd876982cd.png)

Simple question

I am only allowed to make it by default into HD not FHD 

![image](https://user-images.githubusercontent.com/76669896/128244974-0188a52d-7a56-4521-be30-8d8fed6bf6e4.png)

**Comment by DanielnetoDotCom** [comment]
Currently this is not possible
