### ISSUE TITLE
import url in description 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#5534]
When importing a video, can the first or last line of the description of the imported video be the original url?

**Comment by DanielnetoDotCom** [comment]
Sorry this is not possible 

also this is a requirement only for you, I do not think a feature like that will be globally used

**Comment by fakeologist** [comment]
I'm sure others would love the feature too, but if it cannot be done, sobeit.

**Comment by DanielnetoDotCom** [comment]
Hi, 

sorry if I did not express myself clearly, it can be done, but I am only willing to do if it is a paid support feature.

**Comment by fakeologist** [comment]
ok...how much do you want and can you add background playing for paid as well?

**Comment by DanielnetoDotCom** [comment]
for a quotation please email me at developer@youphptube.com

not sure if currently, the background playing is possible
