### ISSUE TITLE
After rebooting my server from yesterdays update to 11.3 splash screen looks horrible!!!

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5535]
![Untitled-1](https://user-images.githubusercontent.com/37937968/128263474-0e8ce58e-c2f9-41be-a57e-dd748b9b4809.jpg)
![Untitled-2](https://user-images.githubusercontent.com/37937968/128263475-c0356468-83f2-4b66-b34c-b776f3db19c9.jpg)

**Comment by DanielnetoDotCom** [comment]
Manually Delete your videos/cache folder

**Comment by DanielnetoDotCom** [comment]
If persists make sure the videos folder is writable and check your logs

**Comment by Lordblanca** [comment]
Thank you.. Where would you find the video folder to make it writable. thanks

**Comment by DanielnetoDotCom** [comment]
probably `/var/www/html/Avideo/videos `

so it should be

`rm -R /var/www/html/Avideo/videos/cache/*`

then

`chmod -R 777 /var/www/html/Avideo/videos`

another thing, did you use git pull to update your site?

check your logs and make sure your plugins are also updated

**Comment by Lordblanca** [comment]
Yes I did. Ran Command as you told me. All was working well. Shut down server like I always do. Turned it on this afternoon and had the error. All good now thanks

**Comment by Lordblanca** [comment]
Just ran "rm -R /var/www/html/Avideo/videos/cache/*" and received error
![image](https://user-images.githubusercontent.com/37937968/128275337-07c002ce-ea08-4fc0-b171-826143545c47.png)

**Comment by Lordblanca** [comment]
Ran Next command chmod -R 777 /var/www/html/Avideo/videos
![image](https://user-images.githubusercontent.com/37937968/128275513-1f42b945-9132-4c08-afd5-b01749dc53ff.png)

Cannot Access /var/www/html/Avideo/videos'

**Comment by DanielnetoDotCom** [comment]
Sorry it is not Avideo. It is AVideo

also check if your disks are not full

**Comment by Lennofreitas** [comment]
Olá DanielnetoDotCom, Eu instalei no meu servidor web dedicado mas logo que fiz login, causou conflito no meu phpmyadmin por excesso de   requisições. Veja o erro no phpmyadmin e os processos que se abrem, veja se estão corretos e o que pode ser.
![Sem título](https://user-images.githubusercontent.com/88467006/128276678-5445b403-5656-494f-9772-ebf6eff41f5d.jpg)
os processos:
![inline1585731146](https://user-images.githubusercontent.com/88467006/128276752-c2740bdf-9bbb-42b1-a2d0-2a2848033ddb.png)

**Comment by DanielnetoDotCom** [comment]
nunca vi este erro, e estou certo que nao tem relação com o AVideo.

**Comment by Lordblanca** [comment]
You replied I think in portugese.?

**Comment by DanielnetoDotCom** [comment]
The Portuguese message was for @Lennofreitas but I guess it is not related to your issue
