### ISSUE TITLE
Unable to see the preview of the live broadcast

### ISSUE THREAD

**Issue by Waffleuncle** [WWBN/AVideo#5536]
Hello , 

Since I updated to the latest AVideo version I lost the live preview.
It just doesn't show the preview when you mouse over the live in question.

I have checked my logs to see if this is a problem on my side. 
Nothing is detected at this level and neither at the console level on google chrome for example. 

I also tried several Template differ if it would not be a CSS problem.

I then revised all my NGIX parameters to see if the problem would be from there but nothing to report either.

Do you have any idea? 

![image](https://user-images.githubusercontent.com/76669896/128348780-64ecd918-5e41-4c92-a25f-2158da4c808e.png)

**Comment by DanielnetoDotCom** [comment]
Probably the thumbnails are processing.

now we use the lazy load image.

check your logs: JS console and Streamer Server

**Comment by Waffleuncle** [comment]
However, if I hover over the live notifications. 
The Preview Image displays correctly but does not return to the main page.

**Comment by Waffleuncle** [comment]
> Probably the thumbnails are processing.
> 
> now we use the lazy load image.
> 
> check your logs: JS console and Streamer Server

![image](https://user-images.githubusercontent.com/76669896/128353926-16e97bcb-b4a8-42ea-90ea-f799aeffc0d9.png)

**Comment by DanielnetoDotCom** [comment]
can you please share your page link here?

make sure you have a live running so I can check

**Comment by Waffleuncle** [comment]
https://stream4.fun/  - WEBSITE URL 
https://stream4.fun/liveLink/4/live-akamai-%7C-stream-demo - LIVE URL

**Comment by Waffleuncle** [comment]
![image](https://user-images.githubusercontent.com/76669896/128357816-11ffc0cc-7f29-403c-bdea-671559b385e0.png)

**Comment by Waffleuncle** [comment]
I have uploaded short gif of this glitch i am talking about
https://i.imgur.com/jy7xLCc.gif

**Comment by DanielnetoDotCom** [comment]
I see you are talking about a Livelink

please try this update

**Comment by Waffleuncle** [comment]
Fixed
