### ISSUE TITLE
Video splitting

### ISSUE THREAD

**Issue by shanesipe** [WWBN/AVideo#5537]
I am trying to figure out how to fix the streaming so it does not split the stream up in to pieces. I have a streamer that stream a show for 3.5 hours and we get four separate sections trying to fix that.

**Comment by JoshWho** [comment]
Look to see if you have a file size limit set in your nginx settings for the live record

**Comment by shanesipe** [comment]
Changed file size now getting issue of Rtmp unknown directive 
nginx.conf:7

**Comment by DanielnetoDotCom** [comment]
Probably a mistyping

that is how the file suppose to looks like 

https://github.com/WWBN/AVideo/blob/8233d010ec293252dd98a7cbd5c203b14dea750a/plugin/Live/install/nginx.conf#L44

**Comment by shanesipe** [comment]
Got it one other question with sharing videos from the platform how can we make it easy for mobile users with out app.

**Comment by DanielnetoDotCom** [comment]
Hi I am not sure what you mean,

Also it looks like another issue, please close this one and open a new one with more details about your question
