### ISSUE TITLE
OBS not connecting to live stream after weeks of using it without issue 

### ISSUE THREAD

**Issue by balasi67** [WWBN/AVideo#5538]
OBS LOG FILE 
error says my RTMP server is offline and I don't know how to get back online for streaming. 

20:49:12.783: CPU Name: Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz
20:49:12.783: CPU Speed: 1796MHz
20:49:12.783: Physical Cores: 2, Logical Cores: 4
20:49:12.783: Physical Memory: 6036MB Total, 2685MB Free
20:49:12.784: Windows Version: 10.0 Build 19041 (revision: 1151; 64-bit)
20:49:12.784: Running as administrator: false
20:49:12.784: Aero is Enabled (Aero is always on for windows 8 and above)
20:49:12.784: Windows 10 Gaming Features:
20:49:12.784: 	Game Bar: On
20:49:12.784: 	Game DVR: On
20:49:12.784: 	Game DVR Background Recording: Off
20:49:12.788: Sec. Software Status:
20:49:12.824: 	Microsoft Defender Antivirus: enabled (AV)
20:49:12.825: 	Windows Firewall: enabled (FW)
20:49:12.849: Current Date/Time: 2021-08-05, 20:49:12
20:49:12.849: Browser Hardware Acceleration: true
20:49:12.849: Portable mode: false
20:49:17.827: OBS 24.0.3 (64-bit, windows)
20:49:17.827: ---------------------------------
20:49:17.890: ---------------------------------
20:49:17.890: audio settings reset:
20:49:17.890: 	samples per sec: 44100
20:49:17.890: 	speakers:        2
20:49:17.925: ---------------------------------
20:49:17.925: Initializing D3D11...
20:49:17.925: Available Video Adapters: 
20:49:17.930: 	Adapter 0: Intel(R) HD Graphics 4000
20:49:17.930: 	  Dedicated VRAM: 33554432
20:49:17.930: 	  Shared VRAM:    1845493760
20:49:17.930: 	  output 0: pos={0, 0}, size={1366, 768}, attached=true
20:49:17.944: Loading up D3D11 on adapter Intel(R) HD Graphics 4000 (0)
20:49:17.956: D3D11 loaded successfully, feature level used: b000
20:49:19.320: ---------------------------------
20:49:19.320: video settings reset:
20:49:19.320: 	base resolution:   1280x720
20:49:19.320: 	output resolution: 1024x576
20:49:19.320: 	downscale filter:  Bicubic
20:49:19.320: 	fps:               60/1
20:49:19.320: 	format:            NV12
20:49:19.320: 	YUV mode:          601/Partial
20:49:19.321: NV12 texture support not available
20:49:19.360: Audio monitoring device:
20:49:19.360: 	name: Default
20:49:19.360: 	id: default
20:49:19.388: ---------------------------------
20:49:19.515: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
20:49:19.566: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
20:49:19.844: [AMF] AMF Test failed due to one or more errors.
20:49:19.844: Failed to initialize module 'enc-amf.dll'
20:49:21.460: [obs-browser]: Version 2.7.15
20:49:21.499: [obs-browser]: Blacklisted device detected, disabling browser source hardware acceleration.
20:49:22.147: [obs-ndi] hello ! (version 4.7.1)
20:49:22.147: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Runtime\v4'
20:49:22.147: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll'
20:49:22.422: [obs-ndi] NDI runtime loaded successfully
20:49:22.430: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 12:23:23 Dec 19 2019 4.2.0.0)
20:49:23.501: Couldn't find VLC installation, VLC video source disabled
20:49:23.711: No blackmagic support
20:49:24.017: ---------------------------------
20:49:24.017:   Loaded Modules:
20:49:24.017:     win-wasapi.dll
20:49:24.017:     win-mf.dll
20:49:24.017:     win-dshow.dll
20:49:24.017:     win-decklink.dll
20:49:24.017:     win-capture.dll
20:49:24.017:     vlc-video.dll
20:49:24.017:     text-freetype2.dll
20:49:24.017:     rtmp-services.dll
20:49:24.017:     obs-x264.dll
20:49:24.017:     obs-vst.dll
20:49:24.017:     obs-transitions.dll
20:49:24.017:     obs-text.dll
20:49:24.017:     obs-qsv11.dll
20:49:24.017:     obs-outputs.dll
20:49:24.017:     obs-ndi.dll
20:49:24.017:     obs-filters.dll
20:49:24.017:     obs-ffmpeg.dll
20:49:24.017:     obs-browser.dll
20:49:24.017:     image-source.dll
20:49:24.017:     frontend-tools.dll
20:49:24.017:     enc-amf.dll
20:49:24.017:     decklink-ouput-ui.dll
20:49:24.017:     coreaudio-encoder.dll
20:49:24.017: ---------------------------------
20:49:24.032: ==== Startup complete ===============================================
20:49:24.105: Service '' not found
20:49:24.367: All scene data cleared
20:49:24.368: ------------------------------------------------
20:49:24.409: [rtmp-services plugin] Update file 'services.json' (version 176) rejected
20:49:24.411: [rtmp-services plugin] Successfully updated package (version 176)
20:49:24.903: WASAPI: Device 'Speaker/HP (Realtek High Definition Audio)' initialized
20:49:25.327: WASAPI: Device 'Microphone (Realtek High Definition Audio)' initialized
20:49:25.384: Switched to scene 'Scene'
20:49:25.499: ------------------------------------------------
20:49:25.499: Loaded scenes:
20:49:25.499: - scene 'Scene':
20:49:25.499:     - source: 'Display Capture' (monitor_capture)
20:49:25.499: ------------------------------------------------
20:49:25.515: adding 185 milliseconds of audio buffering, total audio buffering is now 185 milliseconds (source: Mic/Aux)
20:49:25.515: 
20:49:26.638: [obs-ndi] starting NDI main output with name 'OBSLAPTOP'
20:49:26.696: [obs-ndi] 'OBSLAPTOP': ndi output started
20:50:26.058: Settings changed (stream 1)
20:50:26.058: ------------------------------------------------
20:50:28.045: ---------------------------------
20:50:28.045: [x264 encoder: 'streaming_h264'] preset: veryfast
20:50:28.060: [x264 encoder: 'streaming_h264'] settings:
20:50:28.060: 	rate_control: CBR
20:50:28.060: 	bitrate:      2500
20:50:28.060: 	buffer size:  2500
20:50:28.060: 	crf:          0
20:50:28.060: 	fps_num:      60
20:50:28.060: 	fps_den:      1
20:50:28.060: 	width:        1024
20:50:28.060: 	height:       576
20:50:28.060: 	keyint:       250
20:50:28.060: 
20:50:28.108: ---------------------------------
20:50:28.108: [FFmpeg aac encoder: 'avc_aac_stream'] bitrate: 160, channels: 2, channel_layout: 3
20:50:28.108: 
20:50:28.192: [rtmp stream: 'adv_stream'] Connecting to RTMP URL rtmp://g-stream.xyz/live?e=cGlwcFFUdktuaW1Ba0tvUmhZZnFvaTVtbVdyZUg1NTR4c1ArQVJtUng3WXZqV3l0SXNLZTB4MHFOSERWc2NTYw==/...
20:50:28.330: [rtmp stream: 'adv_stream'] Interface: Realtek RTL8188EE 802.11 bgn Wi-Fi Adapter (802.11, 72 mbps)
20:50:30.524: g-stream.xyz/live e=cGlwcFFUdktuaW1Ba0tvUmhZZnFvaTVtbVdyZUg1NTR4c1ArQVJtUng3WXZqV3l0SXNLZTB4MHFOSERWc2NTYw==/ is offline. Try a different server (ECONNREFUSED).
20:50:30.562: [rtmp stream: 'adv_stream'] Connection to rtmp://g-stream.xyz/live?e=cGlwcFFUdktuaW1Ba0tvUmhZZnFvaTVtbVdyZUg1NTR4c1ArQVJtUng3WXZqV3l0SXNLZTB4MHFOSERWc2NTYw==/ failed: -2
20:50:30.563: ==== Streaming Stop ================================================

**Comment by DanielnetoDotCom** [comment]
Are you trying to run this on windows?
please read check this https://github.com/WWBN/AVideo#important-information

**Comment by balasi67** [comment]
Hi Yeah I have been streaming OBS on Windows to my RTMP server once or twice per week for 3/4 weeks and all of a sudden its not working today

**Comment by balasi67** [comment]
it was working fine till I turned on Google ads then next time I tried to stream it failed to connect to server straight away, So I restarted the server and tried to stream, connection was successful for approximately 1 minute then disconnected. googling the errors in the logs they recon its a proxy but I am sure you corrected that error before on cloudflare so don't know what has happened this time

**Comment by DanielnetoDotCom** [comment]
Check your nginx log and streamer log

also make sure the nginx is running

**Comment by DanielnetoDotCom** [comment]
try to run this `/usr/local/nginx/sbin/nginx`

**Comment by balasi67** [comment]
running that seems to have done the trick thanks, any idea what could have happened ?

**Comment by redilee** [comment]
Along that line, I get this in /var/log/nginx/error.log whenever nginx starts:

"2021/08/05 20:56:52 [emerg] 507909#507909: unknown directive "rtmp" in /etc/nginx/nginx.conf:7"

Any connection?
The site seems to be working, but I don't understand how!
$ sudo which nginx
/usr/sbin/nginx

but if I run 
/usr/local/nginx/sbin/nginx
I get ports already in use errors. 
If I understand it, /usr/sbin/nginx is the default, OS distributed version and /usr/local/nginx/sbin/nginx is the version compiled with rtmp support, and is the correct version to run. 

I'm nervous to get too "experimental" because we almost always have 20 to 50+ users connected.

**Comment by DanielnetoDotCom** [comment]
Looks like you did not install nginx+rtmp module properly

https://github.com/arut/nginx-rtmp-module#build

**Comment by redilee** [comment]
I know there are 2 different nginx instances **currently installed**; the default distribution version and the specially compiled version with rtmp. The wrong one is running.

    ubuntu@fullstreem:~$ which nginx
    /usr/sbin/nginx

    I also find this one, which I believe is the proper one to run.:
   /usr/local/nginx/sbin/nginx

I don't know how they are intertwined, or if they are. Nor do I know how to uninstall without risk - I'm ignorant and haven't found suitable how-to instruction by searching.   Also, I don't know how the system determines which one to run, or which config files to call.

I'm sorely tempted to use apt to uninstall nginx and hope for the best. I doubt that will just work, though, at least not automatically. So I need to find out how to eliminate the wrong nginx and make the right one start on boot using the right config files. 
Any thoughts, or do I really need to read the compile instructions? 
**Thanks!**
