### ISSUE TITLE
Share button

### ISSUE THREAD

**Issue by shanesipe** [WWBN/AVideo#5540]
**Describe the question**
Is there a share button that is easy for people to share a videos from the platform? Having a easy to recognize share button will help draw more traffic into individual sites.

**Comment by DanielnetoDotCom** [comment]
There is already a share button by default 

can’t you see it when you play a video?

can you please screenshot what you can see ?

**Comment by shanesipe** [comment]
![image](https://user-images.githubusercontent.com/16483068/128580925-77a46467-c569-4875-ab27-96166b01be97.jpeg)

**Comment by shanesipe** [comment]
![image](https://user-images.githubusercontent.com/16483068/128580945-545541ed-aa59-451d-b520-f0ad7a868d80.png)

**Comment by DanielnetoDotCom** [comment]
try this 

![image](https://user-images.githubusercontent.com/18009293/128581088-faa43b1d-26e6-4455-bc23-52bd8ce8df29.png)

**Comment by shanesipe** [comment]
![image](https://user-images.githubusercontent.com/16483068/128581180-c17dc8e3-efd8-4d00-b875-0af5034947ad.jpeg)

**Comment by shanesipe** [comment]
This is current setup no changes

**Comment by DanielnetoDotCom** [comment]
Also, check those

![image](https://user-images.githubusercontent.com/18009293/128581330-44f1c9ad-e410-4bf8-91c8-724acdc8e8ef.png)

try to change its configuration.

after a change, anything on the plugin, make sure you clear the cache.

**Comment by DanielnetoDotCom** [comment]
Also check your log file for 

`CustomizeUser::canShareVideosFromVideo ****`

you may find a clue why you cannot see the share button

**Comment by shanesipe** [comment]
Is the block embed supposed to be checked?

**Comment by DanielnetoDotCom** [comment]
no, unckeck it

**Comment by shanesipe** [comment]
Still nothing

**Comment by DanielnetoDotCom** [comment]
again, check your log file

**Comment by shanesipe** [comment]
[06-Aug-2021 19:32:05 America/Chicago] AVideoLog::DEBUG: CustomizeUser::canShareVideosFromVideo canShareVideosFromUser() = false SCRIPT_NAME: /plugin/Live/index.php

**Comment by DanielnetoDotCom** [comment]
please share more from your log, around this time 06-Aug-2021 19:32:05

**Comment by DanielnetoDotCom** [comment]
also, make sure userCanAllowFilesShare is unchecked and you clear the cache, also share a screenshot of your customizeUser plugin parameters

**Comment by shanesipe** [comment]
[06-Aug-2021 19:32:05 America/Chicago] AVideoLog::DEBUG: Page generated in 0.0677 seconds. User: ssadmin - No Cache (/live/0/GoodDog) FROM: 24.111.119.124 Browser: Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1 SCRIPT_NAME: /plugin/Live/index.php
#7 [06-Aug-2021 19:32:05 America/Chicago] AVideoLog::DEBUG: CustomizeUser::canShareVideosFromVideo canShareVideosFromUser() = false SCRIPT_NAME: /plugin/Live/index.php
#8 [06-Aug-2021 19:32:05 America/Chicago] AVideoLog::DEBUG: User::canWatchVideo Video is empty (0) SCRIPT_NAME: /plugin/Live/index.php
#9 [06-Aug-2021 19:32:05 America/Chicago] AVideoLog::DEBUG: User::canWatchVideo Video is empty (0) SCRIPT_NAME: /plugin/Live/index.php
#10 [06-Aug-2021 19:32:05 America/Chicago] AVideoLog::DEBUG: CustomizeUser::canShareVideosFromVideo canShareVideosFromUser() = false SCRIPT_NAME: /plugin/Live/index.php
#11 [06-Aug-2021 19:32:05 America/Chicago] AVideoLog::DEBUG: User::loadFromUser json [{"file":"\/var\/www\/html\/AVideo\/objects\/user.php","line":52,"function":"loadFromUser","class":"User","object":{},"type":"->","args":["GoodDog"]},{"file":"\/var\/www\/html\/AVideo\/plugin\/Live\/view\/modeYoutubeLive.php","line":32,"function":"__construct","class":"User","object":{},"type":"->","args":[0,"GoodDog",false]},{"file":"\/var\/www\/html\/AVideo\/plugin\/Live\/index.php","line":28,"args":["\/var\/www\/html\/AVideo\/plugin\/Live\/view\/modeYoutubeLive.php"],"function":"include"}] SCRIPT_NAME: /plugin/Live/index.php
#12 [06-Aug-2021 19:32:05 America/Chicago] AVideoLog::DEBUG: User::loadFromUser(GoodDog)  SCRIPT_NAME: /plugin/Live/index.php

**Comment by shanesipe** [comment]
![image](https://user-images.githubusercontent.com/16483068/128582399-4ea5c378-9d58-4c37-be44-d3413cce54a4.png)

**Comment by DanielnetoDotCom** [comment]
Uncheck userCanAllowFilesShareSelectPerVideo

**Comment by shanesipe** [comment]
Got it fixed thanks!!

**Comment by DanielnetoDotCom** [comment]
If you check that option you must select on each video if you want to allow share 

![image](https://user-images.githubusercontent.com/18009293/128582699-5ed211bc-85fb-492c-82d1-855ed27727f3.png)
