### ISSUE TITLE
Why is my youphptube so slow?

### ISSUE THREAD

**Issue by Nealpatrick5410** [WWBN/AVideo#5541]
Hello. I was wondering if there was something that could be done about the speed.. For example when I pull up my website the thumbnails take too long to show. Or it loads slow. 

And why don't the videos play when you click them from list? You have to click them twice. Can that be changed? And I don't mean auto play the next video, I mean the one your trying to watch right after yu select it should play but you have to click it again.

**Comment by milehighkaraoke** [comment]
are you fully updated? gitpull site and encoder to make sure you are updated

**Comment by DanielnetoDotCom** [comment]
Did you see that https://github.com/WWBN/AVideo/wiki/Speed-up-your-page

**Comment by Nealpatrick5410** [comment]
I think so. You guys installed it for me so I assumed I was set up the
best. I'm not really good in coding so I don't really know what a gitpull
is. I do know that if I try in update from the site it says I'm fully
updated.

**Comment by Nealpatrick5410** [comment]
I'm checking that link now thought

**Comment by Nealpatrick5410** [comment]
Okay I checked that link. That all looks complicated. How much to pay to just speed it up?

**Comment by DanielnetoDotCom** [comment]
Hi

you can hire us for 1 hour and we can run all this checks including updates . But if the reason of the slowness comes from your hardware there is nothing we can do.

AVideo is running pretty smoothly and fast on the latest updates
