### ISSUE TITLE
A minor styling issue on video playback page

### ISSUE THREAD

**Issue by JSY-Ben** [WWBN/AVideo#5543]
Hi Daniel :) As usual, thank you for the amazing software.

Just to point out to you a minor styling bug on the video playback page. It appears on the Demo Installation as well. The username of the person who has uploaded the video does not appear next to their subscribe button. As seen below.....

<img width="737" alt="Screenshot 2021-08-07 at 3 51 39 PM" src="https://user-images.githubusercontent.com/13555701/128604231-cad0d615-1d01-4aad-9e27-20169f774729.png">

Many thanks again
Ben

**Comment by DanielnetoDotCom** [comment]
Hi, thanks for notify this, but that is not how I see it on my side

![chrome-capture](https://user-images.githubusercontent.com/18009293/129593957-24452ac6-c448-4a57-a562-73c045ccd565.gif)

**Comment by JSY-Ben** [comment]
Just checked, and it's fine on Firefox/Chrome/Edge, but does this on Safari only.
