### ISSUE TITLE
Encode time

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#5544]
I noticed my lives are divided up into 90 minute videos - is there a place to change this?

**Comment by milehighkaraoke** [comment]
You have to adjust that in your PHP and your nginx configuration by increasing your upload sizes to something bigger  i am at 8 gig and it cuts me at 4.5 hr depending on my stream resolution

**Comment by DanielnetoDotCom** [comment]
You must change this parameter

https://github.com/WWBN/AVideo/blob/8233d010ec293252dd98a7cbd5c203b14dea750a/plugin/Live/install/nginx.conf#L44

this file is probably located on /usr/local/nginx/conf/nginx.conf
