### ISSUE TITLE
Sockets needs a way to restart if crashes (Auto Restart Sockets) Persistence

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5548]
I tried to just make a cron run sudo nohup php /var/www/html/YouPHPTube/plugin/YPTSocket/server.php &

but that fails because if the socket is running it kills it. 

Is there any way to say if socket is running ignore?

**Comment by DanielnetoDotCom** [comment]
Hi, 

Make a git pull, and to restart the server only if the port is not user (probably dead)

`sudo nohup php /var/www/html/AVideo/plugin/YPTSocket/serverRestart.php &`

To force kill and restart the PID on the port

`sudo nohup php /var/www/html/AVideo/plugin/YPTSocket/serverRestart.php force &`
