### ISSUE TITLE
CDN page is now accepting credit cards. After a few minutes the CDN page is displaying caching goodness from multiple locations. 👍

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5554]
**Describe the bug**
youphp.tube site is broken. ridiculously slow page load times (load wait 30 seconds close window reload try again and again but that's a separate issue)

When you -finally- get to the CDN page, you can input your credit card, press the button ... and ... nothing ... zip ... zilch ... zero

**To Reproduce**
1. Go to https://youphp.tube/marketplace/
2. Click on CDN
3. Enter credit card details
4. Press "recharge account"
5. Nothing happens

**Expected behavior**
To continue past that point.

**Comment by DanielnetoDotCom** [comment]
Hi, 

sorry for that it supposes to work, I just detect an error on the tutorials site certificate, I am working on a fix for it. I will update you as soon as it is fixed

**Comment by DanielnetoDotCom** [comment]
can you please check again now?

**Comment by walt93** [comment]
Well, for some definitions of "working". The site is working again, all of the window chrome (CSS) was also broken with the certificate. It took money. It is giving the warning "Sorry but you need to recharge your account immediately".

I'm watching videos in multiple browser tabs from both conspyre.tv and its mirror through https://conspyretv.cdn.ypt.me/ 

Nothing seems to be happening. Videos are playing. No bytes are cached. Groovy. 🤷‍♂️

![Screen Shot 2021-08-13 at 11 12 14 PM](https://user-images.githubusercontent.com/11711050/129435995-a2619c02-263f-4970-a7d8-04f543983caa.png)
![Screen Shot 2021-08-13 at 11 12 09 PM](https://user-images.githubusercontent.com/11711050/129435996-935f72e3-449e-4cb4-b213-70fe0e232297.png)
![Screen Shot 2021-08-13 at 11 12 03 PM](https://user-images.githubusercontent.com/11711050/129435997-f72c038a-3e69-4adc-87fc-ba2e1b428555.png)


![Screen Shot 2021-08-13 at 11 12 26 PM](https://user-images.githubusercontent.com/11711050/129435994-665cd845-907f-4f05-a0c0-8dba88a770f3.png)

**Comment by walt93** [comment]
Also now that CDN is turned on I'm loading pages, all of the window dressing and text renders - no video thumbnail - for like 20-30 seconds. It didn't feel like that before. There are <50 people on the server so its not loaded...

**Comment by DanielnetoDotCom** [comment]
I am glad you see some difference now
