### ISSUE TITLE
Help! Trying to modify social.css. Picking up cached version from cdn.ypt.me. How to invalidate cache?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5557]
**Describe the question**
Modify your css files. Observe there are no changes. Go to web inspector and look at style sheets. See they are coming from cdn.ypt.me

Tried clear first page cache, clear cache directory, generate sitemap, no change.

**Screenshots**
![Screen Shot 2021-08-15 at 4 39 24 PM](https://user-images.githubusercontent.com/11711050/129496174-40161432-498b-4ac2-8676-83719b537b41.png)

**Comment by JoshWho** [comment]
Does Purge all cache not clear the cdn?

**Comment by walt93** [comment]
Seems not to, no.

**Comment by JoshWho** [comment]
I am wondering if the cdn static files only reflect the original code and is maybe static

**Comment by DanielnetoDotCom** [comment]
Hi, you can purge the CDN here

![image](https://user-images.githubusercontent.com/18009293/129556636-b415b21f-a2a9-4c97-b55e-0b886e98f82a.png)
