### ISSUE TITLE
Error using AD_Server plug-in

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5558]
The AD_Server plug-in uses an error, the video advertisement cannot be played, and the advertisement is in the local MP4 format.
![image](https://user-images.githubusercontent.com/47063171/129508608-92aeb764-36cf-446f-80c1-e36e2862ba09.png)
![image](https://user-images.githubusercontent.com/47063171/129508685-f6c2f3cb-682e-4200-94df-4c3e6adbcf58.png)
![image](https://user-images.githubusercontent.com/47063171/129508723-50223126-22f3-4b20-bac4-d89796333a32.png)
![image](https://user-images.githubusercontent.com/47063171/129508781-d57320a9-1bfd-478d-81c9-636cfeb3bc80.png)
![image](https://user-images.githubusercontent.com/47063171/129508821-16867683-4e68-4295-a341-893a0737ac67.png)

**Comment by chenjian9885** [comment]
The update has been performed: sudo git fetch --all && sudo git reset --hard origin/master
![image](https://user-images.githubusercontent.com/47063171/129509073-206d16ea-aee7-4232-9c5b-3aff50aa0ff9.png)

**Comment by DanielnetoDotCom** [comment]
Hi, you must change your PHP to not recognize the <? as a PHP tag

In your php.ini you MUST have

`short_open_tag = Off`

https://github.com/WWBN/AVideo/blob/8233d010ec293252dd98a7cbd5c203b14dea750a/plugin/AD_Server/VAST.php#L18

**Comment by chenjian9885** [comment]
Hello, I have configured short_open_tag = Off. The address link is normal, and the advertisement still cannot be played normally. I don’t know if I missed something?
![image](https://user-images.githubusercontent.com/47063171/129681667-21d8fc10-8275-4986-ae89-c6b973aac8d0.png)
![image](https://user-images.githubusercontent.com/47063171/129682490-86236d25-e8e8-491e-9daa-37b355108553.png)
![image](https://user-images.githubusercontent.com/47063171/129682569-e48c75e2-ed30-4a2f-82c7-e1ad4a9449e0.png)
![image](https://user-images.githubusercontent.com/47063171/129682015-225aa971-ed55-4e3c-975a-ab4ae6e571d4.png)
![image](https://user-images.githubusercontent.com/47063171/129682264-14207fc5-9332-48ec-9532-796b47d603d1.png)
![image](https://user-images.githubusercontent.com/47063171/129681805-a5316b2f-785c-4dab-920e-191ffab77f9b.png)
![image](https://user-images.githubusercontent.com/47063171/129682725-95602f68-1c08-437a-ad43-d4c815b0e522.png)

**Comment by DanielnetoDotCom** [comment]
I see now, you are trying to use an embedded video as an ad.

you MUST encode the video as a MP4 file, then you can use it as an ad

**Comment by chenjian9885** [comment]
No, I uploaded the video to the encoder and converted it to MP4 format for advertising video
![image](https://user-images.githubusercontent.com/47063171/129751897-24e9966b-3af9-4c65-a095-bdea3a04fb28.png)
![image](https://user-images.githubusercontent.com/47063171/129751982-d4c6288e-f1ea-4c8b-b4b5-405966fecae5.png)
![image](https://user-images.githubusercontent.com/47063171/129752172-b09fbb39-1657-418e-a62c-66b4bda0c3e6.png)

**Comment by DanielnetoDotCom** [comment]
Ok, so I am not sure why it is not playing. can you please check your JS console, also share the video URL here so I can test

**Comment by chenjian9885** [comment]
website：https://shancaowucdn.com/
Advertising video：https://shancaowucdn.com/video/110/4566?page=1&channelName=Yld

**Comment by DanielnetoDotCom** [comment]
This is what I can see

![image](https://user-images.githubusercontent.com/18009293/129762675-05c5cb20-9140-4737-9119-2d4254a1c06f.png)

And you are using Cloudflare

![image](https://user-images.githubusercontent.com/18009293/129762802-055b82e3-f80f-4b78-9442-33d643d63f68.png)

that is why I do not recommend it, try to use let's encrypt and disable Cloudflare proxy

If you do not know how to install let's encrypt, try to google for that.

**Comment by chenjian9885** [comment]
Thanks, I think I know how to do it
