### ISSUE TITLE
I've coded a share button for Gab. When I try to push a branch I am 403. Can I get repo access to submit a PR?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5559]
**Is your feature request related to a problem? Please describe.**
I've coded a share button for Gab. It is incomplete, for instance there are strings hard coded into share.php that need to be pulled from preferences. Hoping you can help with that. :-)

**Describe the solution you'd like**
Commit access to push a branch, to submit a pull request from that branch.

**Describe alternatives you've considered**
Contacting people manually to add code to their site. Seems like a silly idea when we have Git.

**Additional context**
Font Awesome are leftist trash and won't add icons because they think cancel culture is cool. I found an alternative that is injecting svg directly into fontawesome, but it is not rendering properly - leaving an empty grey circle for a share button and offsetting it vertically - I believe I may not be initializing it? Or the SVG are messed up and we need another solution. Hoping to get eyes on this. 

Here is the font awesome hack for gab/parler:
https://vinyanalista.github.io/font-awesome-gab-parler/#.YRmcyS1h1zV

**Comment by DanielnetoDotCom** [comment]
We used to have a parler share button, but it was removed when parler was shouted down.

here is the old buton https://github.com/WWBN/AVideo/commit/e5fee1fe405de7c29e88ba1d47dacbeaaa5d5563

we can use it to bring it back. but seems that the old share link is not working anymore.

`https://parler.com/new-post?message={$title}&url={$url}`, it reurns a 404 page

**Comment by walt93** [comment]
I found the same when I tried to code one for Parler - their link is not working. Parler is IMO not worth using, so, meh. 

I have one working for Gab

**Comment by DanielnetoDotCom** [comment]
I see, sorry I got confused, you want to use Gab.

do you know the share link for gab?

**Comment by walt93** [comment]
Better, I could push a branch for you to review. But let me paste some code.

social.css add

.social-network a.icoGab:hover {
    background-color: #30ce7d;
}

.social-network a.icoGab:hover I,

social.php

$gabURL = "https://gab.com/compose?url={$urlSocial}&text={$theMessage}";

where $theMessage is something a little more complex that I worked out, but, I'm using two strings that need to be pulled from preferences (haven't figured out how to code that)




if ($videoLengthInSeconds > 0) {
    $hours = floor($videoLengthInSeconds / 3600);
    $mins = floor($videoLengthInSeconds / 60 % 60);
    $secs = floor($videoLengthInSeconds % 60);
    $durationSocial = sprintf('Running time: %02d:%02d:%02d', $hours, $mins, $secs) . '%0A';
} else {
    $durationSocial = 'PDF (Click through to download)%0A';
}

$tagline =      "Conspyre(dot)tv is a free resource for students of conspiracy, from current events to antedeluvian times. Thousand of videos, audio files and PDFs are organized into categories and tagged to facilitate navigation. Share and download links facilitate movement of information. You are the resistance...";
$taglineShort = "Conspyre(dot)tv is a free resource for students of conspiracy, from current events to antedeluvian times. You are the resistance…";

$theMessage = "{$titleSocial}{$durationSocial}{$breakSocial}{$tagline}";
$theMessageShort  = "{$titleSocial}{$durationSocial}{$breakSocial}{$taglineShort}";

$theMessageClipboard = "{$titleSocial}{$durationSocial}{$breakSocial}{$tagline}%0A%0A{$url}";
$theMessageClibboard = str_replace('%0A', '\n', $theMessageClipboard);

$gabURL = "https://gab.com/compose?url={$urlSocial}&text={$theMessage}";
$facebookURL = "https://www.facebook.com/sharer.php?u={$urlSocial}&title={$theMessageShort}";
$twitterURL = "http://twitter.com/intent/tweet?text={$theMessageShort}+%0A%0A+{$urlSocial}";
$tumblr = "http://www.tumblr.com/share?v=3&u=$urlSocial&quote=theMessage&s=";
$pinterest = "http://pinterest.com/pin/create/button/?url=$urlSocial&description=";
$reddit = "http://www.reddit.com/submit?url=$urlSocial&title=$theMessageShort";
$linkedin = "http://www.linkedin.com/shareArticle?mini=true&url=$urlSocial&title=$titleSocial&summary=&source=$urlSocial";
$wordpress = "http://wordpress.com/press-this.php?u=$urlSocial&quote=$titleSocial&s=";

    <li><a href="<?php echo $gabURL; ?>" style="" target="_blank" class="icoGab" title="Gab" data-toggle="tooltip" ><i class="fab fa-glide-g"></i></a></li>

**Comment by walt93** [comment]
All of that is to put nicely formatted messages into my social including the running time of the video (or a note to click through to download the PDF - necessary on social media where the PDF appears in-line as if it is a video)

**Comment by walt93** [comment]
In the above we would put $tagline and $taglineShort into preferences. That would be cool.

**Comment by walt93** [comment]
Oh, one more question, we're passing data into the social media functions via URL, so, limited to 2047 characters or some bullshit?

How do we pass the video object (id) through here so we can look it up on the other side? I want to put the video description into the formatted block - Gab allows posts of up to 1,000 words (as in whole words).

**Comment by DanielnetoDotCom** [comment]
This update should add the Gab icon
