### ISSUE TITLE
HELP!!! I've pasted some bad html into Customize Advanced and I've broken the site - cannot access plugins to fix, or render the majority of the site.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5560]
**Describe the question**
I need a mysql command to specifically zap the HTML, and forget the exact name of the field - it is the second place to insert menu code.

**Screenshots**
![Screen Shot 2021-08-15 at 9 42 23 PM](https://user-images.githubusercontent.com/11711050/129512356-af197572-e2aa-490b-b440-c3c96da2512f.png)

**Comment by walt93** [comment]
Ok. Site's still down. 

sudo mysql
use database AVideo_conspyretv;
select object_data from plugins where id=4;

now I have a very long string, in the middle of that string, I zap the contents for underMenuBarHTMLCode (inner JSON type=textarea value="this is my bad HTML that I am wiping out"

Ok I take that big long hairy string and I try to paste it into a 

update plugins set object_data=..... where id=4;

but when I paste in that string, I get a bunch of errors from mysql

ERROR:
Unknown command '\\'.
ERROR:
Unknown command '\\'.
ERROR:
Unknown command '\\'.
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"logoMenuBarURL":"","encoderNetwork":"https:\\/\\/network.avideo.com\\/","useEnc' at line 1
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'max-height: 100%' at line 1

because that big long string has a bunch of weird double back-quoted strings in the timezone field (e.g. timeZone":{"type":{"0":"Africa\\/Abidjan"," , ... about 150 entries with the \\ that it's choking on)

Help!!!

**Comment by walt93** [comment]
If I can make this big sql update work, my site will come back to life.

update plugins set object_data={"logoMenuBarURL":"","encoderNetwork":"https:\\/\\/network.avideo.com\\/","useEncoderNetworkRecomendation":false,"doNotShowEncoderNetwork":true,"doNotShowUploadButton":false,"uploadButtonDropdownIcon":"fas fa-upload","uploadButtonDropdownText":"","encoderNetworkLabel":"","doNotShowUploadMP4Button":false,"disablePDFUpload":false,"disableImageUpload":false,"disableZipUpload":false,"disableMP4Upload":false,"disableMP3Upload":false,"uploadMP4ButtonLabel":"","doNotShowImportMP4Button":false,"importMP4ButtonLabel":"","doNotShowEncoderButton":false,"encoderButtonLabel":"","doNotShowEmbedButton":true,"embedBackgroundColor":"white","embedButtonLabel":"","embedCodeTemplate":"<div class=\\"embed-responsive embed-responsive-16by9\\"><iframe width=\\"640\\" height=\\"360\\" style=\\"max-width: 100%;max-height: 100%; border:none;\\" src=\\"{embedURL}\\" frameborder=\\"0\\" allowfullscreen=\\"allowfullscreen\\" allow=\\"autoplay\\" scrolling=\\"no\\">iFrame is not supported!<\\/iframe><\\/div>","embedCodeTemplateObject":"<div class=\\"embed-responsive embed-responsive-16by9\\"><object width=\\"640\\" height=\\"360\\"><param name=\\"movie\\" value=\\"{embedURL}\\"><\\/param><param name=\\"allowFullScreen\\" value=\\"true\\"><\\/param><param name=\\"allowscriptaccess\\" value=\\"always\\"><\\/param><embed src=\\"{embedURL}\\" allowscriptaccess=\\"always\\" allowfullscreen=\\"true\\" width=\\"640\\" height=\\"360\\"><\\/embed><\\/object><\\/div>","htmlCodeTemplate":"<a href=\\"{permaLink}\\"><img src=\\"{imgSRC}\\">{title}<\\/a>","BBCodeTemplate":"[url={permaLink}][img]{imgSRC}[\\/img]{title}[\\/url]","embedControls":{"type":{"0":"No Controls","1":"All controls","-1":"Basic Controls"},"value":"-1"},"embedAutoplay":false,"embedLoop":false,"embedStartMuted":false,"embedShowinfo":true,"doNotShowEncoderHLS":false,"doNotShowEncoderResolutionLow":false,"doNotShowEncoderResolutionSD":false,"doNotShowEncoderResolutionHD":false,"openEncoderInIFrame":false,"showOnlyEncoderAutomaticResolutions":true,"doNotShowEncoderAutomaticHLS":false,"doNotShowEncoderAutomaticMP4":false,"doNotShowEncoderAutomaticWebm":false,"doNotShowEncoderAutomaticAudio":false,"saveOriginalVideoResolution":true,"doNotShowExtractAudio":false,"doNotShowCreateVideoSpectrum":false,"doNotShowLeftMenuAudioAndVideoButtons":true,"doNotShowWebsiteOnContactForm":true,"doNotUseXsendFile":false,"makeVideosInactiveAfterEncode":false,"makeVideosUnlistedAfterEncode":false,"usePermalinks":false,"useVideoIDOnSEOLinks":true,"disableAnimatedGif":false,"removeBrowserChannelLinkFromMenu":true,"EnableMinifyJS":true,"disableShareAndPlaylist":false,"disableShareOnly":false,"disableEmailSharing":false,"splitBulkEmailSend":"50","disableComments":false,"commentsMaxLength":"300","commentsNoIndex":false,"disableYoutubePlayerIntegration":false,"utf8Encode":false,"utf8Decode":false,"menuBarHTMLCode":{"type":"textarea","value":""},"underMenuBarHTMLCode":{"type":"textarea","value":""},"footerHTMLCode":{"type":"textarea","value":""},"signInOnRight":true,"signInOnLeft":true,"forceCategory":false,"showCategoryTopImages":true,"autoPlayAjax":false,"disablePlayLink":true,"disableHelpLeftMenu":true,"disableAboutLeftMenu":false,"disableContactLeftMenu":true,"disableNavbar":false,"disableNavBarInsideIframe":false,"autoHideNavbar":false,"autoHideNavbarInSeconds":"3","videosCDN":"","useFFMPEGToGenerateThumbs":true,"thumbsWidthPortrait":"170","thumbsHeightPortrait":"250","thumbsWidthLandscape":"640","thumbsHeightLandscape":"360","usePreloadLowResolutionImages":false,"showImageDownloadOption":false,"doNotDisplayViews":false,"doNotDisplayLikes":false,"doNotDisplayCategoryLeftMenu":false,"doNotDisplayCategory":false,"doNotDisplayGroupsTags":false,"doNotDisplayPluginsTags":false,"showNotRatedLabel":false,"showShareMenuOpenByDefault":true,"askRRatingConfirmationBeforePlay_G":false,"askRRatingConfirmationBeforePlay_PG":false,"askRRatingConfirmationBeforePlay_PG13":false,"askRRatingConfirmationBeforePlay_R":false,"askRRatingConfirmationBeforePlay_NC17":true,"askRRatingConfirmationBeforePlay_MA":true,"filterRRating":false,"doNotShowLeftHomeButton":true,"doNotShowLeftTrendingButton":true,"CategoryLabel":"Categories","ShowAllVideosOnCategory":true,"hideCategoryVideosCount":false,"paidOnlyUsersTellWhatVideoIs":false,"paidOnlyShowLabels":false,"paidOnlyLabel":"Premium","paidOnlyFreeLabel":"Free","removeSubscribeButton":false,"removeThumbsUpAndDown":false,"videoNotFoundText":{"type":"textarea","value":""},"siteMapRowsLimit":"100","siteMapUTF8Fix":false,"showPrivateVideosOnSitemap":false,"enableOldPassHashCheck":true,"disableHTMLDescription":false,"disableVideoSwap":false,"makeSwapVideosOnlyForAdmin":true,"disableCopyEmbed":false,"disableDownloadVideosList":false,"videosManegerRowCount":"[10, 25, 50, -1]","videosListRowCount":"[10, 20, 30, 40, 50]","twitter_site":"@conspyretv","twitter_player":true,"twitter_summary_large_image":true,"footerStyle":"position: fixed;bottom: 0;width: 100%;","disableVideoTags":false,"doNotAllowEncoderOverwriteStatus":false,"doNotAllowUpdateVideoId":false,"makeVideosIDHarderToGuess":false,"timeZone":{"type":{"0":"Africa\\/Abidjan","1":"Africa\\/Accra","2":"Africa\\/Addis_Ababa","3":"Africa\\/Algiers","4":"Africa\\/Asmara","5":"Africa\\/Bamako","6":"Africa\\/Bangui","7":"Africa\\/Banjul","8":"Africa\\/Bissau","9":"Africa\\/Blantyre","10":"Africa\\/Brazzaville","11":"Africa\\/Bujumbura","12":"Africa\\/Cairo","13":"Africa\\/Casablanca","14":"Africa\\/Ceuta","15":"Africa\\/Conakry","16":"Africa\\/Dakar","17":"Africa\\/Dar_es_Salaam","18":"Africa\\/Djibouti","19":"Africa\\/Douala","20":"Africa\\/El_Aaiun","21":"Africa\\/Freetown","22":"Africa\\/Gaborone","23":"Africa\\/Harare","24":"Africa\\/Johannesburg","25":"Africa\\/Juba","26":"Africa\\/Kampala","27":"Africa\\/Khartoum","28":"Africa\\/Kigali","29":"Africa\\/Kinshasa","30":"Africa\\/Lagos","31":"Africa\\/Libreville","32":"Africa\\/Lome","33":"Africa\\/Luanda","34":"Africa\\/Lubumbashi","35":"Africa\\/Lusaka","36":"Africa\\/Malabo","37":"Africa\\/Maputo","38":"Africa\\/Maseru","39":"Africa\\/Mbabane","40":"Africa\\/Mogadishu","41":"Africa\\/Monrovia","42":"Africa\\/Nairobi","43":"Africa\\/Ndjamena","44":"Africa\\/Niamey","45":"Africa\\/Nouakchott","46":"Africa\\/Ouagadougou","47":"Africa\\/Porto-Novo","48":"Africa\\/Sao_Tome","49":"Africa\\/Tripoli","50":"Africa\\/Tunis","51":"Africa\\/Windhoek","52":"America\\/Adak","53":"America\\/Anchorage","54":"America\\/Anguilla","55":"America\\/Antigua","56":"America\\/Araguaina","57":"America\\/Argentina\\/Buenos_Aires","58":"America\\/Argentina\\/Catamarca","59":"America\\/Argentina\\/Cordoba","60":"America\\/Argentina\\/Jujuy","61":"America\\/Argentina\\/La_Rioja","62":"America\\/Argentina\\/Mendoza","63":"America\\/Argentina\\/Rio_Gallegos","64":"America\\/Argentina\\/Salta","65":"America\\/Argentina\\/San_Juan","66":"America\\/Argentina\\/San_Luis","67":"America\\/Argentina\\/Tucuman","68":"America\\/Argentina\\/Ushuaia","69":"America\\/Aruba","70":"America\\/Asuncion","71":"America\\/Atikokan","72":"America\\/Bahia","73":"America\\/Bahia_Banderas","74":"America\\/Barbados","75":"America\\/Belem","76":"America\\/Belize","77":"America\\/Blanc-Sablon","78":"America\\/Boa_Vista","79":"America\\/Bogota","80":"America\\/Boise","81":"America\\/Cambridge_Bay","82":"America\\/Campo_Grande","83":"America\\/Cancun","84":"America\\/Caracas","85":"America\\/Cayenne","86":"America\\/Cayman","87":"America\\/Chicago","88":"America\\/Chihuahua","89":"America\\/Costa_Rica","90":"America\\/Creston","91":"America\\/Cuiaba","92":"America\\/Curacao","93":"America\\/Danmarkshavn","94":"America\\/Dawson","95":"America\\/Dawson_Creek","96":"America\\/Denver","97":"America\\/Detroit","98":"America\\/Dominica","99":"America\\/Edmonton","100":"America\\/Eirunepe","101":"America\\/El_Salvador","102":"America\\/Fort_Nelson","103":"America\\/Fortaleza","104":"America\\/Glace_Bay","105":"America\\/Goose_Bay","106":"America\\/Grand_Turk","107":"America\\/Grenada","108":"America\\/Guadeloupe","109":"America\\/Guatemala","110":"America\\/Guayaquil","111":"America\\/Guyana","112":"America\\/Halifax","113":"America\\/Havana","114":"America\\/Hermosillo","115":"America\\/Indiana\\/Indianapolis","116":"America\\/Indiana\\/Knox","117":"America\\/Indiana\\/Marengo","118":"America\\/Indiana\\/Petersburg","119":"America\\/Indiana\\/Tell_City","120":"America\\/Indiana\\/Vevay","121":"America\\/Indiana\\/Vincennes","122":"America\\/Indiana\\/Winamac","123":"America\\/Inuvik","124":"America\\/Iqaluit","125":"America\\/Jamaica","126":"America\\/Juneau","127":"America\\/Kentucky\\/Louisville","128":"America\\/Kentucky\\/Monticello","129":"America\\/Kralendijk","130":"America\\/La_Paz","131":"America\\/Lima","132":"America\\/Los_Angeles","133":"America\\/Lower_Princes","134":"America\\/Maceio","135":"America\\/Managua","136":"America\\/Manaus","137":"America\\/Marigot","138":"America\\/Martinique","139":"America\\/Matamoros","140":"America\\/Mazatlan","141":"America\\/Menominee","142":"America\\/Merida","143":"America\\/Metlakatla","144":"America\\/Mexico_City","145":"America\\/Miquelon","146":"America\\/Moncton","147":"America\\/Monterrey","148":"America\\/Montevideo","149":"America\\/Montserrat","150":"America\\/Nassau","151":"America\\/New_York","152":"America\\/Nipigon","153":"America\\/Nome","154":"America\\/Noronha","155":"America\\/North_Dakota\\/Beulah","156":"America\\/North_Dakota\\/Center","157":"America\\/North_Dakota\\/New_Salem","158":"America\\/Nuuk","159":"America\\/Ojinaga","160":"America\\/Panama","161":"America\\/Pangnirtung","162":"America\\/Paramaribo","163":"America\\/Phoenix","164":"America\\/Port-au-Prince","165":"America\\/Port_of_Spain","166":"America\\/Porto_Velho","167":"America\\/Puerto_Rico","168":"America\\/Punta_Arenas","169":"America\\/Rainy_River","170":"America\\/Rankin_Inlet","171":"America\\/Recife","172":"America\\/Regina","173":"America\\/Resolute","174":"America\\/Rio_Branco","175":"America\\/Santarem","176":"America\\/Santiago","177":"America\\/Santo_Domingo","178":"America\\/Sao_Paulo","179":"America\\/Scoresbysund","180":"America\\/Sitka","181":"America\\/St_Barthelemy","182":"America\\/St_Johns","183":"America\\/St_Kitts","184":"America\\/St_Lucia","185":"America\\/St_Thomas","186":"America\\/St_Vincent","187":"America\\/Swift_Current","188":"America\\/Tegucigalpa","189":"America\\/Thule","190":"America\\/Thunder_Bay","191":"America\\/Tijuana","192":"America\\/Toronto","193":"America\\/Tortola","194":"America\\/Vancouver","195":"America\\/Whitehorse","196":"America\\/Winnipeg","197":"America\\/Yakutat","198":"America\\/Yellowknife","199":"Antarctica\\/Casey","200":"Antarctica\\/Davis","201":"Antarctica\\/DumontDUrville","202":"Antarctica\\/Macquarie","203":"Antarctica\\/Mawson","204":"Antarctica\\/McMurdo","205":"Antarctica\\/Palmer","206":"Antarctica\\/Rothera","207":"Antarctica\\/Syowa","208":"Antarctica\\/Troll","209":"Antarctica\\/Vostok","210":"Arctic\\/Longyearbyen","211":"Asia\\/Aden","212":"Asia\\/Almaty","213":"Asia\\/Amman","214":"Asia\\/Anadyr","215":"Asia\\/Aqtau","216":"Asia\\/Aqtobe","217":"Asia\\/Ashgabat","218":"Asia\\/Atyrau","219":"Asia\\/Baghdad","220":"Asia\\/Bahrain","221":"Asia\\/Baku","222":"Asia\\/Bangkok","223":"Asia\\/Barnaul","224":"Asia\\/Beirut","225":"Asia\\/Bishkek","226":"Asia\\/Brunei","227":"Asia\\/Chita","228":"Asia\\/Choibalsan","229":"Asia\\/Colombo","230":"Asia\\/Damascus","231":"Asia\\/Dhaka","232":"Asia\\/Dili","233":"Asia\\/Dubai","234":"Asia\\/Dushanbe","235":"Asia\\/Famagusta","236":"Asia\\/Gaza","237":"Asia\\/Hebron","238":"Asia\\/Ho_Chi_Minh","239":"Asia\\/Hong_Kong","240":"Asia\\/Hovd","241":"Asia\\/Irkutsk","242":"Asia\\/Jakarta","243":"Asia\\/Jayapura","244":"Asia\\/Jerusalem","245":"Asia\\/Kabul","246":"Asia\\/Kamchatka","247":"Asia\\/Karachi","248":"Asia\\/Kathmandu","249":"Asia\\/Khandyga","250":"Asia\\/Kolkata","251":"Asia\\/Krasnoyarsk","252":"Asia\\/Kuala_Lumpur","253":"Asia\\/Kuching","254":"Asia\\/Kuwait","255":"Asia\\/Macau","256":"Asia\\/Magadan","257":"Asia\\/Makassar","258":"Asia\\/Manila","259":"Asia\\/Muscat","260":"Asia\\/Nicosia","261":"Asia\\/Novokuznetsk","262":"Asia\\/Novosibirsk","263":"Asia\\/Omsk","264":"Asia\\/Oral","265":"Asia\\/Phnom_Penh","266":"Asia\\/Pontianak","267":"Asia\\/Pyongyang","268":"Asia\\/Qatar","269":"Asia\\/Qostanay","270":"Asia\\/Qyzylorda","271":"Asia\\/Riyadh","272":"Asia\\/Sakhalin","273":"Asia\\/Samarkand","274":"Asia\\/Seoul","275":"Asia\\/Shanghai","276":"Asia\\/Singapore","277":"Asia\\/Srednekolymsk","278":"Asia\\/Taipei","279":"Asia\\/Tashkent","280":"Asia\\/Tbilisi","281":"Asia\\/Tehran","282":"Asia\\/Thimphu","283":"Asia\\/Tokyo","284":"Asia\\/Tomsk","285":"Asia\\/Ulaanbaatar","286":"Asia\\/Urumqi","287":"Asia\\/Ust-Nera","288":"Asia\\/Vientiane","289":"Asia\\/Vladivostok","290":"Asia\\/Yakutsk","291":"Asia\\/Yangon","292":"Asia\\/Yekaterinburg","293":"Asia\\/Yerevan","294":"Atlantic\\/Azores","295":"Atlantic\\/Bermuda","296":"Atlantic\\/Canary","297":"Atlantic\\/Cape_Verde","298":"Atlantic\\/Faroe","299":"Atlantic\\/Madeira","300":"Atlantic\\/Reykjavik","301":"Atlantic\\/South_Georgia","302":"Atlantic\\/St_Helena","303":"Atlantic\\/Stanley","304":"Australia\\/Adelaide","305":"Australia\\/Brisbane","306":"Australia\\/Broken_Hill","307":"Australia\\/Darwin","308":"Australia\\/Eucla","309":"Australia\\/Hobart","310":"Australia\\/Lindeman","311":"Australia\\/Lord_Howe","312":"Australia\\/Melbourne","313":"Australia\\/Perth","314":"Australia\\/Sydney","315":"Europe\\/Amsterdam","316":"Europe\\/Andorra","317":"Europe\\/Astrakhan","318":"Europe\\/Athens","319":"Europe\\/Belgrade","320":"Europe\\/Berlin","321":"Europe\\/Bratislava","322":"Europe\\/Brussels","323":"Europe\\/Bucharest","324":"Europe\\/Budapest","325":"Europe\\/Busingen","326":"Europe\\/Chisinau","327":"Europe\\/Copenhagen","328":"Europe\\/Dublin","329":"Europe\\/Gibraltar","330":"Europe\\/Guernsey","331":"Europe\\/Helsinki","332":"Europe\\/Isle_of_Man","333":"Europe\\/Istanbul","334":"Europe\\/Jersey","335":"Europe\\/Kaliningrad","336":"Europe\\/Kiev","337":"Europe\\/Kirov","338":"Europe\\/Lisbon","339":"Europe\\/Ljubljana","340":"Europe\\/London","341":"Europe\\/Luxembourg","342":"Europe\\/Madrid","343":"Europe\\/Malta","344":"Europe\\/Mariehamn","345":"Europe\\/Minsk","346":"Europe\\/Monaco","347":"Europe\\/Moscow","348":"Europe\\/Oslo","349":"Europe\\/Paris","350":"Europe\\/Podgorica","351":"Europe\\/Prague","352":"Europe\\/Riga","353":"Europe\\/Rome","354":"Europe\\/Samara","355":"Europe\\/San_Marino","356":"Europe\\/Sarajevo","357":"Europe\\/Saratov","358":"Europe\\/Simferopol","359":"Europe\\/Skopje","360":"Europe\\/Sofia","361":"Europe\\/Stockholm","362":"Europe\\/Tallinn","363":"Europe\\/Tirane","364":"Europe\\/Ulyanovsk","365":"Europe\\/Uzhgorod","366":"Europe\\/Vaduz","367":"Europe\\/Vatican","368":"Europe\\/Vienna","369":"Europe\\/Vilnius","370":"Europe\\/Volgograd","371":"Europe\\/Warsaw","372":"Europe\\/Zagreb","373":"Europe\\/Zaporozhye","374":"Europe\\/Zurich","375":"Indian\\/Antananarivo","376":"Indian\\/Chagos","377":"Indian\\/Christmas","378":"Indian\\/Cocos","379":"Indian\\/Comoro","380":"Indian\\/Kerguelen","381":"Indian\\/Mahe","382":"Indian\\/Maldives","383":"Indian\\/Mauritius","384":"Indian\\/Mayotte","385":"Indian\\/Reunion","386":"Pacific\\/Apia","387":"Pacific\\/Auckland","388":"Pacific\\/Bougainville","389":"Pacific\\/Chatham","390":"Pacific\\/Chuuk","391":"Pacific\\/Easter","392":"Pacific\\/Efate","393":"Pacific\\/Enderbury","394":"Pacific\\/Fakaofo","395":"Pacific\\/Fiji","396":"Pacific\\/Funafuti","397":"Pacific\\/Galapagos","398":"Pacific\\/Gambier","399":"Pacific\\/Guadalcanal","400":"Pacific\\/Guam","401":"Pacific\\/Honolulu","402":"Pacific\\/Kiritimati","403":"Pacific\\/Kosrae","404":"Pacific\\/Kwajalein","405":"Pacific\\/Majuro","406":"Pacific\\/Marquesas","407":"Pacific\\/Midway","408":"Pacific\\/Nauru","409":"Pacific\\/Niue","410":"Pacific\\/Norfolk","411":"Pacific\\/Noumea","412":"Pacific\\/Pago_Pago","413":"Pacific\\/Palau","414":"Pacific\\/Pitcairn","415":"Pacific\\/Pohnpei","416":"Pacific\\/Port_Moresby","417":"Pacific\\/Rarotonga","418":"Pacific\\/Saipan","419":"Pacific\\/Tahiti","420":"Pacific\\/Tarawa","421":"Pacific\\/Tongatapu","422":"Pacific\\/Wake","423":"Pacific\\/Wallis","424":"UTC"},"value":"132"},"keywords":"9\\/11, Bohemian Grove, Cathy O'Brien, Chemtrails, CIA, Club of Rome, Covid-19, Disinformation, Documentaries, Drunvalo Melchizedek, Federal Reserve, Freemasons, Great Reset, Illuminati, Jesuits, NASA, Neurolinguistic Programming, Michael Acquino, MK-Ultra, Mind Control, New World Order, NLP, Oaklahoma City, Orbs, ORME, ORMUS, Remote Viewing, Richard Bandler, Robert Anton Wilson, Ruby Ridge, Scientology, Secret Societies, Skull & Bones, Stanley Meyer, Stolen Election, Ted Gunderson, TR-3B, Trilateral Comission, Vatican, UFOs, Waco, Wilhelm Reich, William Cooper","robotsTXT":{"type":"textarea","value":"Allow: \\/plugin\\/Live\\/?*\\nAllow: \\/plugin\\/PlayLists\\/*.css\\nAllow: \\/plugin\\/PlayLists\\/*.js\\nAllow: \\/plugin\\/TopMenu\\/*.css\\nAllow: \\/plugin\\/TopMenu\\/*.js\\nAllow: \\/plugin\\/SubtitleSwitcher\\/*.css\\nAllow: \\/plugin\\/SubtitleSwitcher\\/*.js\\nAllow: \\/plugin\\/Gallery\\/*.css\\nAllow: \\/plugin\\/Gallery\\/*.js\\nAllow: \\/plugin\\/YouPHPFlix2\\/*.png\\nAllow: \\/plugin\\/Live\\/*.css\\nAllow: \\/plugin\\/Live\\/*.js\\nAllow: \\/plugin\\/*.css\\nAllow: \\/plugin\\/*.js\\nAllow: .js\\nAllow: .css\\nDisallow: \\/user\\nDisallow: \\/plugin\\nDisallow: \\/mvideos\\nDisallow: \\/usersGroups\\nDisallow: \\/charts\\nDisallow: \\/upload\\nDisallow: \\/comments\\nDisallow: \\/subscribes\\nDisallow: \\/update\\nDisallow: \\/locale\\nDisallow: \\/objects\\/*\\nAllow: \\/plugin\\/Live\\/?*\\nAllow: \\/plugin\\/LiveLink\\/?*\\nAllow: \\/plugin\\/PlayLists\\/*.css\\nAllow: \\/plugin\\/PlayLists\\/*.js\\nAllow: \\/plugin\\/TopMenu\\/*.css\\nAllow: \\/plugin\\/TopMenu\\/*.js\\nAllow: \\/plugin\\/SubtitleSwitcher\\/*.css\\nAllow: \\/plugin\\/SubtitleSwitcher\\/*.js\\nAllow: \\/plugin\\/Gallery\\/*.css\\nAllow: \\/plugin\\/Gallery\\/*.js\\nAllow: \\/plugin\\/YouPHPFlix2\\/*.png\\nAllow: \\/plugin\\/Live\\/*.css\\nAllow: \\/plugin\\/Live\\/*.js\\nAllow: \\/plugin\\/*.css\\nAllow: \\/plugin\\/*.js\\nAllow: .js\\nAllow: .css"},"AsyncJobs":false,"EnableWavesurfer":false} where id=4;

**Comment by DanielnetoDotCom** [comment]
check this https://github.com/WWBN/AVideo/issues/5561

**Comment by walt93** [comment]
😎 🙏
