### ISSUE TITLE
Help! Is there a way to use the audit table to roll back a config change that took down the site?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5561]
**Describe the question**
I see over two million records in my audit table. Many for ten seconds of time elapsing in the player; these seem like that can be coalesced but that's separate.

Is there a way to find the most recent config change and roll it back?

This command is giving me the audit history of writing to my configurationAdvanced plugin, one feels this is getting close:

select * from audit where statement like 'UPDATE plugins SET  `id` = 4%';

How to take one of these and apply it back?

**Comment by DanielnetoDotCom** [comment]
Sorry, it is not possible but you can reset a specific plugin

`UPDATE plugins  SET object_data = '' WHERE id = ?`

**Comment by walt93** [comment]
Thanks 🙏
