### ISSUE TITLE
Help! Update: opened firewall and database to use external SQL editor to "fix" broken HTML in my advanced config plugins table (see previous two reports). Now the site no longer renders.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5562]
**Describe the question**
I used an external SQL editor to edit the object_data of plugins table in an attempt to rescue the site.

I pasted bad HTML into the advanced config / menuBarHTMLCode and could no longer render anything below menuBarHTMLCode, which includes the entire plug-ins page (!)

I removed the HTML code from menuBarHTMLCode with Valentina Studio and now the entire site fails to render (!!!)

What is the procedure to blow out / restore from defaults the Configuration/Advanced plug-in configuration? 

**Screenshots**
I removed some HTML from here and saved. The text still looks the same, however after updating the object_data field of plugins id=4 from Valentina Studio, the site is in a bad state. The editor must have reformatted the text in some bad way...

![Screen Shot 2021-08-16 at 12 07 54 AM](https://user-images.githubusercontent.com/11711050/129524804-1b1bcf42-4ee2-49d1-ba47-0ff7986d777b.png)
![Screen Shot 2021-08-16 at 12 08 22 AM](https://user-images.githubusercontent.com/11711050/129524809-ce18110b-71fa-4614-be62-ccd7c01a6dcb.png)

**Comment by DanielnetoDotCom** [comment]
Hi, 

I am not sure what you have done, but there is a script that may help you
https://github.com/WWBN/AVideo/blob/master/install/resetPlugins.php

you may want to run this 

`php /var/www/html/AVideo/install/resetPlugins.php 1`

this will reset all parameters from all plugins

**Comment by DanielnetoDotCom** [comment]
Also if you make the object_data column from the database an empty value, it will reset the plugin parameters to the default values

**Comment by walt93** [comment]
Ok awesome this is what I needed - just to blow out the parameters for one plugin. 😎 🙏
