### ISSUE TITLE
Curl video upload 

### ISSUE THREAD

**Issue by aleksis82** [WWBN/AVideo#5563]
**Describe the bug**
When I upload video using curl I cant play video because video file in “encoding” state and format is Other. I checked file twice file in correct format mp4. When I upload same file via web interface it working 

**To Reproduce**
1. Avideo run in docker
2. Command used curl -F ‘upl=@sample.mp4’ -F ‘name=upl;type=file;accept=video/mp4’ https://…/MobileManager/upload.php?user=admin&pass=passwordhash

**Comment by DanielnetoDotCom** [comment]
Hi, the docker version is not 100%. I recommend you to use a plain installation on your server
