### ISSUE TITLE
Help! Site stuck in maintenance mode? I had to reset my database password to get into the db remotely. Where is AVideo config for db user/password?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5564]
**Describe the question**
After previous errors: 
   1. Paste badly formed HTML into Configuration Advanced->menuBarHTMLCode causing partial render failure including plugins (so can't fix the HTML)
   2. Find and attempt to fix the badly formed HTML by deleting it from plugins table (editing object_data) - after this the entire site stopped rendering - looks to be in a form of maintenance mode
   3. Cleared the object_data for plugins id=4 (Configuration->Advanced)
   4. No change in state; site is still rendering in maintenance mode
   5. Cleared the plugins table (delete from plugins where id>0;)
   6. No change in state...
   
  ...7. Realize that this has everything to do with resetting the mysql password late last night! 🤦‍♂️...... Where do I set that? Some config file?
   
**Screenshots**
![Screen Shot 2021-08-16 at 11 27 23 AM](https://user-images.githubusercontent.com/11711050/129612053-71976124-39a3-4853-b9f2-bc0f9bcbe6ab.png)

![Screen Shot 2021-08-16 at 11 37 37 AM](https://user-images.githubusercontent.com/11711050/129613259-fd11a110-c503-487f-a4d4-090c9fa76ac6.png)

**Comment by DanielnetoDotCom** [comment]
if the plugins table is empty your site should be accessible

check the avideo error log

**Comment by walt93** [comment]
Update: I also reset the database password, so, need to re-inform avideo of this. 🤦‍♂️

**Comment by DanielnetoDotCom** [comment]
yes, you must change it on the configuration.php file

**Comment by walt93** [comment]
There's several configuration.php files - assume you mean the one at AVideo/objects/configuration.php?

I see in the file it is referencing:
\$mysqlHost = '{$mysqlHost}';
\$mysqlUser = '{$mysqlUser}';
\$mysqlPass = '{$mysqlPass}';
\$mysqlDatabase = '{$mysqlDatabase}';

I do not see where to set these. Do I need to load this page?
