### ISSUE TITLE
3rd party Chat not able to be removed from my account menu

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5565]
when trying to go back to the old chat I delete the embed link one and click save and when I refresh it still shows the 3rd part embed link.

How to go back to normal chat from myaccount?

**Comment by JoshWho** [comment]
I cant find what the user id is to manually add the original chat link. How to find user ID number? When I click view chat rooms I only see 20 and not finding the one I need

**Comment by JoshWho** [comment]
For now I ended up disabled 3rd party chats then went to the channel and opened the chat in a new tab and copied the link to it and pasted it in the 3rd party chat embed box on MYACCOUNT  and then re enabled the 3rd party chats

**Comment by DanielnetoDotCom** [comment]
Hi, do you mean you cannot remove the third-party link?

**Comment by JoshWho** [comment]
correct

**Comment by DanielnetoDotCom** [comment]
I just added a delete button for the embed URL

![image](https://user-images.githubusercontent.com/18009293/129621630-d30afd79-bc1a-4de0-9d93-bd647ec3d85d.png)

for this, you MUST have the Chat2 version 7.5

**Comment by JoshWho** [comment]
Sweeeeeet. I will update thank you
