### ISSUE TITLE
Clouthub share button

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5566]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to share to CloutHub. Just kidding I don't use CloutHub. But if I did, I would.

**Describe the solution you'd like**
social.css
```
    .social-network a.icoCloutHub:hover {
        background-color: #F28829;
    }
    ...
```
social.php

```
    $cloutHubURL = "https://app.clouthub.com/share?url=${urlSocial}&text=${TheMessageShort}}
    ...
    <li><a href="<?php echo $cloutHubURL; ?>" style="" target="_blank" class="icoCloutHub" title="CloutHub" data-toggle="tooltip" ><i class="far fa-comment-dots"></i></a></li>

```
NOTE: fontawesome are political hacks and don't support clouthub. Using "far fa-comment-dots" is not correct; it is merely similar. Sigh......

**Describe alternatives you've considered**
Not a web coder, I would just use a set of graphics instead of font awesome. Finding a set of graphics including Gab and Clouthub seems problematic, and it seems that leftist hacks are dominant in the space. Weird.  

Probably if you had monochrome vector graphics for these logos you could do the injection trick like https://vinyanalista.github.io/font-awesome-gab-parler/#.YRmn7SJh1zV

**Additional context**
Mixing politics and code is wee Todd did. Say that three times out loud.

**Comment by DanielnetoDotCom** [comment]
Please check this update
