### ISSUE TITLE
I want to code a index page. Can you give me a couple of pointers?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5567]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I spend a bunch of time adding index tags, and do not have a proper index page. I want a page that looks like the following, with each tag being an active link to the /tag/N/tagname page
```
    A
        Aardvark, Apple, ...
    B
    ...

```
**Describe the solution you'd like**
I would like to code an index page. Can you answer couple questions to get me on my way?

**Describe alternatives you've considered**
I put in a feature request, but, you're busy.

**Additional context**
1) Where in the hierarchy would I create my tagIndex.php?

2) From what file do I copy the basic site structure? e.g. "clone foo.php, remove the middle, put your part there"

3) A code snippet to get array of tags from database

I'll figure the rest out and post back code, or, I can do pull requests. 🙏

**Comment by DanielnetoDotCom** [comment]
I recommend you copy a plugin (Gallery for example)

then you can rename it and create your own plugin

Please check this https://github.com/WWBN/AVideo/wiki/How-to-code-a-AVideo-Platform-plugin
