### ISSUE TITLE
Configuration: Chat2 seems not to be available when enabled, also, what are these arrows?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5568]
**Describe the question**
After blowing out plug-in configuration, chat seems not to be functioning.

Also, what are these arrows? (related?)

**Screenshots**
![Screen Shot 2021-08-16 at 11 05 29 PM](https://user-images.githubusercontent.com/11711050/129672501-bd6769ac-8475-4b25-b108-5e070e0f3fbe.png)

**Comment by DanielnetoDotCom** [comment]
What is the chat problem?

the arrows are to display the categories

![image](https://user-images.githubusercontent.com/18009293/129730625-698731a7-4784-4abb-b971-4f6c33b7c58a.png)

**Comment by walt93** [comment]
Chat is not showing at all. Also I am not seeing categories, only the arrows. Clicking them doesn’t do anything.

**Comment by DanielnetoDotCom** [comment]
Maybe you have something blocking scripts in your browser (check for ad-block)

![image](https://user-images.githubusercontent.com/18009293/129765027-54d86fcd-94d3-4105-af2a-b4d49ff932d2.png)

Regarding the chat please share a screenshot of your chat2 plugin parameters

**Comment by walt93** [comment]
It's displaying in Brave, not in Safari. Turning on "Fluid" mode produced a bad result in Brave (very long horizontal scrolling of >100 root categories)

Can't find a setting in Safari to allow it to pass. Safari doesn't really have an ad blocker. Do you know what setting to check?

**Comment by walt93** [comment]
Update: looks like a rendering bug in Safari, those elements are pushed to the right and you can only see them if you open the window very wide - bug filed.
