### ISSUE TITLE
Open DiskUploadQuota plug-in style is abnormal

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5569]
Open DiskUploadQuota plug-in, the style is abnormal when the storage space is not purchased
![image](https://user-images.githubusercontent.com/47063171/129686138-a65b54e5-8414-43e5-9d49-428b565a34c2.png)
![image](https://user-images.githubusercontent.com/47063171/129686164-8a9538d0-0a8e-424a-9eb2-1d2af7f8763b.png)
![image](https://user-images.githubusercontent.com/47063171/129686519-79cfac86-da59-4365-803c-e293e69c8bdf.png)

**Comment by chenjian9885** [comment]
Return to normal after purchasing storage space
![image](https://user-images.githubusercontent.com/47063171/129686875-78a75ce4-add5-49b5-915e-efcb4f33a02c.png)
![image](https://user-images.githubusercontent.com/47063171/129688551-393a0ef5-bad5-48ce-be63-2a6f8b798714.png)

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that and I could confirm the problem.

to resolve that please update your AVideo

**Comment by chenjian9885** [comment]
thanks
