### ISSUE TITLE
Missing download button

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#5570]
Two links that don't have download buttons.
https://fakeotube.com/video/3781/tom-macdonald---brainwashed
https://fakeotube.com/video/3775/chris-sky---end-of-tour---what-s-next-aug-21

**Comment by DanielnetoDotCom** [comment]
They are embed videos, we cannot download/control embeded videos

> Two links that don't have download buttons.
> https://fakeotube.com/video/3781/tom-macdonald---brainwashed

https://www.youtube.com/embed/zCBNwGHPZ2M

> https://fakeotube.com/video/3775/chris-sky---end-of-tour---what-s-next-aug-21

https://www.bitchute.com/embed/uqA7LG6dAYOV/?parent=fakeotube.com

**Comment by walt93** [comment]
Hey fakeologist, what I do is turn off ability to embed videos from Youtube/etc and just clone the media directly. Fk'n commies are censoring everything anyway, its the only way to be sure you've got the media...

**Comment by fakeologist** [comment]
where is that setting?

**Comment by DanielnetoDotCom** [comment]
Check the customize advanced plugin parameters

**Comment by fakeologist** [comment]
no option there is clear to me for no embed/clone.

**Comment by fakeologist** [comment]
can you show me the option to check @walt93

**Comment by walt93** [comment]
I need to find it again myself after I zapped my plugin settings. Here is the technique to do that:
check out the source onto your local drive where you have a programmers editor (SublimeText works great)
drag the entire folder onto your programmers editor so you can search through all files
search the source code for the string you are looking for, in this case "Embed a Video Link"
find it in a bunch of localizations, some crap places, and finally in navbar.php
lets look at the code; I grabbed the entire block above and below the string we are looking for
                                            if (empty($advancedCustom->doNotShowEmbedButton)) {
                                                ?>
                                                <li>
                                                    <a  href="<?php echo $global['webSiteRootURL']; ?>mvideos?link=1"  data-toggle="tooltip" title="<?php echo __("Embed videos/files in your site"); ?>" data-placement="left" class="faa-parent animated-hover" >
                                                        <span class="fa fa-link faa-burst"></span> <?php echo empty($advancedCustom->embedButtonLabel) ? __("Embed a video link") : __($advancedCustom->embedButtonLabel); ?>
                                                    </a>
                                                </li>
                                                <?php
                                            }
The code at the top tells us that the Custom Advanced plugin "doNotShowEmbedButton" turns off this chunk of HTML and you won't be able to import "references" to YouTube anymore.

This trick works for turning off everything that you can turn off in the interface, when you can't remember where the #$#$# it is. HTH.

**Comment by fakeologist** [comment]
I don't think that's the right idea.
Turning off embed means I don't have a copy embed code item in my videos menu.
Also, that video without a download button was a direct import from my files - it was not imported from anywhere.

**Comment by walt93** [comment]
Sorry I misunderstood, but that controls "Embed a Video Link" in the nav menu - the one that saves a URL to the media on external sites - will prevent you/your users from embedding more such media. That is how the tom Macdonald and chris sky vids above were imported. 

Not sure about the other video w/o a download button
