### ISSUE TITLE
Subscription page column credit card number overlap

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#5572]
HI

When you have 3 plans, credit card number overlaps with security number. It's confusing. 

see here:
![image](https://user-images.githubusercontent.com/63721378/129734473-94225378-8107-43bb-b80a-b6cb079db299.png)

Can columns be changed to "col-md-6" instead "col-md-4"?

![image](https://user-images.githubusercontent.com/63721378/129734878-f482161c-ccc6-4236-a083-7ebd62011eab.png)

**Comment by DanielnetoDotCom** [comment]
What resolution is your screen?

**Comment by tonuzo** [comment]
HD resolution (1920x1080)

**Comment by DanielnetoDotCom** [comment]
Agree, Subscription version 4.4 will use 2 columns only

**Comment by tonuzo** [comment]
thanks!
