### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by reuvygroovy** [WWBN/AVideo#5573]
I just updated to the latest version and I see:
![image](https://user-images.githubusercontent.com/1325158/129744820-c9b80972-169f-487a-9aab-0c1f9de85140.png)

But on the site you show the latest version to be:
![image](https://user-images.githubusercontent.com/1325158/129744893-4d5dd753-ebd4-4c00-8ac6-f23cb68b9ab5.png)

Is the site just not updated?

**Comment by DanielnetoDotCom** [comment]
This is just a marked release, I strongly recommend you install the version on the master branch.

for this you must use the `git clone`, do NOT download the zip

`sudo git clone https://github.com/WWBN/AVideo.git`

**Comment by reuvygroovy** [comment]
We originally cloned the repo when we started. Today we just updated. The latest version we got from git pull was 11.3. That means we're ok?

**Comment by DanielnetoDotCom** [comment]
go to the installed directory and type `sudo git pull`, then you  should be OK

**Comment by reuvygroovy** [comment]
That's what I did. And the version I got after upgrading was 11.3. That's why I asked why on the site it showed a different version.

**Comment by DanielnetoDotCom** [comment]
we only change the version number when there is an database update

**Comment by reuvygroovy** [comment]
Thanks!
