### ISSUE TITLE
Embedding iFrames (iFrame is not supported!)

### ISSUE THREAD

**Issue by reuvygroovy** [WWBN/AVideo#5574]
I'm on the latest version

When trying to generate embedding code for my site I get the following:
<div class="embed-responsive embed-responsive-16by9"><iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="https://video.mami.gov.il/videoEmbed/52/carmel?channelName=System&modestbranding=1&showinfo=1&autoplay=&controls=1&loop=&mute=&t=0&objectFit=" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no">iFrame is not supported!</iframe></div>             

When I try to browse to the URL of the frame I get the following error:
Fatal error: Uncaught ValueError: Path cannot be empty in /var/www/AVideo/objects/functions.php:1494 Stack trace: #0 /var/www/AVideo/objects/functions.php(1494): getimagesize() #1 /var/www/AVideo/view/videoEmbeded.php(65): getimgsize() #2 {main} thrown in /var/www/AVideo/objects/functions.php on line 1494
array(4) { ["type"]=> int(1) ["message"]=> string(241) "Uncaught ValueError: Path cannot be empty in /var/www/AVideo/objects/functions.php:1494 Stack trace: #0 /var/www/AVideo/objects/functions.php(1494): getimagesize() #1 /var/www/AVideo/view/videoEmbeded.php(65): getimgsize() #2 {main} thrown" ["file"]=> string(37) "/var/www/AVideo/objects/functions.php" ["line"]=> int(1494) }

**Comment by DanielnetoDotCom** [comment]
Make sure you are running the latest. looks like you are running an outdated version as long as you do not have the same lines as we have on the master branch

`Fatal error: Uncaught ValueError: Path cannot be empty in /var/www/AVideo/objects/functions.php:1494 `

https://github.com/WWBN/AVideo/blob/bf10d1c26eef008d56f6474bc3b9054deb914ca5/objects/functions.php#L1494

**Comment by reuvygroovy** [comment]
Just ran a git pull now:
![image](https://user-images.githubusercontent.com/1325158/129840894-6f146a15-3548-4795-b974-e0dabf3a3977.png)

And still when generating the frame I get:

<div class="embed-responsive embed-responsive-16by9"><iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="https://server/videoEmbed/52/carmel?channelName=System&modestbranding=1&showinfo=1&autoplay=&controls=1&loop=&mute=&t=0&objectFit=" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no">**iFrame is not supported!**</iframe></div>                    

And when I go to the URL in the "src" I get:


Fatal error: Uncaught ValueError: Path cannot be empty in /var/www/AVideo/objects/functions.php:1494 Stack trace: #0 /var/www/AVideo/objects/functions.php(1494): getimagesize() #1 /var/www/AVideo/view/videoEmbeded.php(65): getimgsize() #2 {main} thrown in /var/www/AVideo/objects/functions.php on line 1494
array(4) { ["type"]=> int(1) ["message"]=> string(241) "Uncaught ValueError: Path cannot be empty in /var/www/AVideo/objects/functions.php:1494 Stack trace: #0 /var/www/AVideo/objects/functions.php(1494): getimagesize() #1 /var/www/AVideo/view/videoEmbeded.php(65): getimgsize() #2 {main} thrown" ["file"]=> string(37) "/var/www/AVideo/objects/functions.php" ["line"]=> int(1494) }

I even then deleted the files and copy/pasted the content into a new file and go the same error.

**Comment by reuvygroovy** [comment]
So what's weird is that indeed I can now embed the code in an iFrame in a 3rd party app, but the text always appears "iframe not supported"

**Comment by DanielnetoDotCom** [comment]
It is really weird, I really cannot follow it.

the error you pasted above does not match with the latest code 
try to reproduce it on demo site, so I can check directly

**Comment by reuvygroovy** [comment]
<<try to reproduce it on demo site
how should I do that?

should I git a new site from scratch?

**Comment by DanielnetoDotCom** [comment]
https://demo.avideo.com/

User: admin
Pass: 123
