### ISSUE TITLE
Image Updating

### ISSUE THREAD

**Issue by reuvygroovy** [WWBN/AVideo#5575]
I'm using the latest version 11.3

I try to assign an image for my video. I upload a new picture. I see the picture was updated in the form:

![image](https://user-images.githubusercontent.com/1325158/129754048-f8c494a0-1b8d-4788-ba4c-8866d7d99426.png)

But after I save the picture doesn't get applied/saved.
![image](https://user-images.githubusercontent.com/1325158/129754193-9f1946a0-0144-4e77-acf5-e9da62dc7d61.png)

**Comment by DanielnetoDotCom** [comment]
There is no reason for that.

please check if it is not a browser cache.

also check it from another browser

**Comment by reuvygroovy** [comment]
Im using the latest version of Chrome.

I tried again from a different computer and it works.

I see in the video directory there was a png file which was created:
![image](https://user-images.githubusercontent.com/1325158/129755511-204ae354-249a-4b7f-a564-6d940c24ae40.png)

But it still appears with no picture.

**Comment by DanielnetoDotCom** [comment]
It is not clear, does it works from another PC?

are you using a CDN? can you purge the CDN cache if you are using?

**Comment by reuvygroovy** [comment]
I tried from another PC. I also tried in another browser.

What is CDN? and if I'm using it, how to I purge the cache? Sorry if I'm a nube.

**Comment by DanielnetoDotCom** [comment]
If you do not know, you are probably not using it.

https://github.com/WWBN/AVideo/wiki/CDN-Plugin

**Comment by reuvygroovy** [comment]
Guess not. So what else could be causing this?
Is this just cosmetic or will this show the black screen on the video before playing?

**Comment by reuvygroovy** [comment]
Tried again today from another machine and it works. Sorry about the confusion, and thanks very much for the help!
