### ISSUE TITLE
Top category nav rendering issue in Safari

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5576]
**Describe the bug**
For narrow window widths, arrow buttons are visible but have no effect when pushed.
Opening the window to wider widths, the nav buttons are seen off to the right, not "anchored" (as the window is expanded, horizontal position "drifts"...).

**To Reproduce**
Mac OS X/Safari 14.1.1 (16611.2.7.1.4) running on Mac OS X Big Sur (11.4)

**Screenshots**
![Screen Shot 2021-08-17 at 4 16 05 PM](https://user-images.githubusercontent.com/11711050/129812807-bf1200ed-493c-4581-8983-ec0b1de32b32.png)
![Screen Shot 2021-08-17 at 4 16 11 PM](https://user-images.githubusercontent.com/11711050/129812815-f14c19cf-9e33-42c7-87b4-11055370869d.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I can confirm it is failing on Safari, I will try to find a solution for it
