### ISSUE TITLE
Multiple Log in From same user different device

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5578]
One person is able to log in multiple times from different devices. The cell phone that is not on wifi. And the tablet is on there home network at the same time.

**Comment by DanielnetoDotCom** [comment]
Hi, 

I am not sure what you are looking for

**Comment by Lordblanca** [comment]
A person's account can log in multiple times from different devices and
different locations. When testing log-ins I noticed that.
Is there a way to allow only one account to log in from one device and one
location.

**Comment by DanielnetoDotCom** [comment]
I still do not know what is your question

**Comment by DanielnetoDotCom** [comment]
Sorry, understood now

please check this 

![image](https://user-images.githubusercontent.com/18009293/129914088-6c9a6997-f80a-4fe3-a300-87a3090d779b.png)


Also you must make sure the socket is running fine

**Comment by Lordblanca** [comment]
It works!
