### ISSUE TITLE
I want to build a dev server. What is the cheapest of these VPS that I can get away with?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5579]
**Describe the question**
While doing HTML/JS crap I managed to torch my site something fierce, and while trying to fix it, I massacred it even worse.

I need a dev server!

Which of these plans can I get away with?

**Screenshots**
![Screen Shot 2021-08-17 at 8 51 09 PM](https://user-images.githubusercontent.com/11711050/129834126-9b43b1b7-02c3-4bc9-8fff-99ab334c3f05.png)

**Comment by DanielnetoDotCom** [comment]
if is just for testing get the 11 USD one
