### ISSUE TITLE
DiskUploadQuota plug-in restricts users to still be able to over-upload videos?

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5581]
What is the purpose of DiskUploadQuota plug-in restricting the user's storage? The user can still upload the video, and the video can still be played normally.
![image](https://user-images.githubusercontent.com/47063171/129845563-6544b963-223f-445a-99ea-c7bbca29bd87.png)
![image](https://user-images.githubusercontent.com/47063171/129845988-b9b2760e-57c6-48eb-958a-82730ef0eca0.png)
![image](https://user-images.githubusercontent.com/47063171/129845802-a082a854-7365-40e8-9f79-6245cc092070.png)
![image](https://user-images.githubusercontent.com/47063171/129845871-1215ecbf-7325-44bf-9fe0-b775b242224f.png)

**Comment by DanielnetoDotCom** [comment]
Admin can play and upload and bypass all rules
I found some issue on the cache and I just sent a fix for it.
also, I just sent a new plugin version 1.4 that will improve some things.
To be clear when a user uploads something and exceeds the quota it may not reflect right the way the capacity to play videos, it may need you to clear cache

**Comment by chenjian9885** [comment]
thanks
awesome! Now the storage oversubscription has restricted the video can not be watched.
