### ISSUE TITLE
How does DiskUploadQuota plug-in support AVideo wallet payment

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5582]
Hello
How should the DiskUploadQuota plug-in support AVideo wallet payment? The entire site should support AVideo wallet payment. There is no reason why the user's top-up amount cannot be used on the site.
![image](https://user-images.githubusercontent.com/47063171/129853035-e879994a-8f03-41b7-a881-6d189b44b2fd.png)

**Comment by DanielnetoDotCom** [comment]
The disk quota works with a subscription plan, for now, we only support stripe

it will be auto recharged each 30 days

**Comment by chenjian9885** [comment]
It’s really a shame that after testing the DiskUploadQuota plug-in for so many days, I have to give up the plug-in due to payment problems.

**Comment by DanielnetoDotCom** [comment]
What is the payment problem?

**Comment by chenjian9885** [comment]
Users cannot use AVideo wallet to pay for storage space. It is unrealistic to use stripe to pay. For my user group, I can only give up the function of DiskUploadQuota plug-in.

**Comment by DanielnetoDotCom** [comment]
DiskUploadQuota requires a subscription plan (auto charge), it can also be implemented in PayPal and we may do it in a future

**Comment by chenjian9885** [comment]
I don’t understand, PayPerView, Subscription, FansSubscriptions and other plugins can all be paid with AVideo wallet, why DiskUploadQuota plugin can’t.

**Comment by chenjian9885** [comment]
Why is it so unique and only supports stripe

**Comment by DanielnetoDotCom** [comment]
I may add other payment options in the future

**Comment by chenjian9885** [comment]
Ok

**Comment by morbificagent** [comment]
I would be interested in using the Quota-Plugin too but with only stripe it isnt possible here as in germany everyone is using paypal...
So it would be great if you could add this...

**Comment by DanielnetoDotCom** [comment]
I may add a PayPal subscription support for it in the future
