### ISSUE TITLE
Failed to create live stream and google meet on demo website

### ISSUE THREAD

**Issue by isaac1232011** [WWBN/AVideo#5587]
I am trying to use admin to create live stream, and google meet on demo.avideo.com. For live stream, when I clicked go live, it keeps loading. For google meet, I cannot create a google meet meeting.Can you check live stream, and google meet?

**Comment by DanielnetoDotCom** [comment]
Hi, we do not have a google meet

before try to live a meet, please make sure you can go live with OBS first
