### ISSUE TITLE
Ftom mobile Within the live settings the broadcaster does not connect

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5590]
Being able to go live right from the phone is an awsome addition..... When I try to go live from my mobile devices it just spins and never makes the connection. 
![Screenshot_20210819-055710_Samsung Internet](https://user-images.githubusercontent.com/70327833/130065068-059209f2-2424-4efd-a0fe-7db681c214af.jpg)
![Screenshot_20210819-055620_Samsung Internet](https://user-images.githubusercontent.com/70327833/130065071-2f1d7779-d64e-41db-9ed3-1f30f55b583e.jpg)

**Comment by DanielnetoDotCom** [comment]
It should work on the phone

Try to use the Fullscreen mode

![image](https://user-images.githubusercontent.com/18009293/130079534-acf1e923-5fea-4b47-9ef2-fc44aa635b62.png)


Then click in go live

![image](https://user-images.githubusercontent.com/18009293/130079607-5c2279ec-bc17-4efe-b322-28f80cec1c17.png)

Also make sure your live server is running

**Comment by milehighkaraoke** [comment]
Same thing.   I can stream using the manycam app so I know the live server is up and running.

![Screenshot_20210819-081113_Samsung Internet](https://user-images.githubusercontent.com/70327833/130084242-c1543ff0-f454-4765-8b99-c18b407c3112.jpg)
![Screenshot_20210819-081105_Samsung Internet](https://user-images.githubusercontent.com/70327833/130084245-0d4976a5-4034-4086-8a39-fe1e2ab60c16.jpg)

**Comment by milehighkaraoke** [comment]
It just sits on please wait

**Comment by milehighkaraoke** [comment]
Anyway we can change button from saying Webcam to go live now?

**Comment by milehighkaraoke** [comment]
With Firefox mobile browser I get this . I did accept camera and microphone permissions @
![Screenshot_20210819-082336_Firefox](https://user-images.githubusercontent.com/70327833/130086027-4f880fb9-01c8-420a-affb-e7e259f8c762.jpg)

**Comment by DanielnetoDotCom** [comment]
I am really not sure, can you please test it on demo site?

also check your logs

**Comment by DanielnetoDotCom** [comment]
I can see you are forcing the user to be logged in. can you please disable that and test again?

![image](https://user-images.githubusercontent.com/18009293/130088472-f5262f1c-ac71-4e87-835a-35b0cbce2704.png)

**Comment by milehighkaraoke** [comment]
Here are the errors  and turning off force  user to log did not fix it. 
![Screenshot_20210819-085638_Samsung Internet](https://user-images.githubusercontent.com/70327833/130091798-28640e8a-cea6-49c8-8d64-046f8e6c312f.jpg)
![Screenshot_20210819-085632_Samsung Internet](https://user-images.githubusercontent.com/70327833/130091803-fe7fcf4b-a687-4235-9af9-e04742560eaa.jpg)
![Screenshot_20210819-085543_Samsung Internet](https://user-images.githubusercontent.com/70327833/130091804-08895964-942e-417e-8041-e4d44aa58ebd.jpg)
![Screenshot_20210819-085534_Samsung Internet](https://user-images.githubusercontent.com/70327833/130091808-f7e288cd-b4bf-4d28-a036-6803c1f06826.jpg)

**Comment by DanielnetoDotCom** [comment]
Please make a git pull, it is already fixed from yesterday

**Comment by milehighkaraoke** [comment]
Thank you Sir. Great work....... @DanielnetoDotCom
