### ISSUE TITLE
Switching servers 

### ISSUE THREAD

**Issue by Nealpatrick5410** [WWBN/AVideo#5591]
**Describe the question**
Hello, I want to know can i switch servers without corruption or losing anything on my site. Is there a tutorial on this. And would I be starting all over with install?

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
For myself, I like the clone plugin https://github.com/WWBN/AVideo/wiki/Clone-Site-Plugin

please read this https://github.com/WWBN/AVideo/wiki/How-to-make-a-backup

**Comment by Nealpatrick5410** [comment]
Okay thanks I will check it out
