### ISSUE TITLE
_addViewAsync - permission denied

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#5592]
Hi, 

i'm seeing this in the event log each time i refresh the page:

_addViewAsync 
Object { error: "Permission denied" }
​error: "Permission denied"

Is this the reason why when I change any video attribute via edit, the change gets written to db but not shown unless I close the browser and load it back up.

**Comment by DanielnetoDotCom** [comment]
On what exact page are you seeing this?

**Comment by millzee01** [comment]
on mvideos page

**Comment by millzee01** [comment]
@DanielnetoDotCom this also seems to be happening when i show a video on a webpage outside the streamer site.  if i clear the cache using the admin then the message disappears for a while.

**Comment by DanielnetoDotCom** [comment]
can you please update your code, as soon as I do not see it on my side?

![image](https://user-images.githubusercontent.com/18009293/130462627-3aaa290d-4d5c-40b6-bfc9-2f9b4dd48d4f.png)
