### ISSUE TITLE
Donate Button in chat

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5593]
I see there is a donate button in the chat on the main site. Is it a plug in and if so which one. Thanks

**Comment by Lordblanca** [comment]
never mind figured it out thanks

**Comment by Lordblanca** [comment]
I thought I figured it out. I see that you have the donation link in the chat. How do I get the donation link to be in the chat.. .Thank you

**Comment by DanielnetoDotCom** [comment]
Please check this 

https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform#donations

![image](https://user-images.githubusercontent.com/18009293/130230176-e0f4bb5c-1ad6-4c0f-8fa1-13aac4992f31.png)

![image](https://user-images.githubusercontent.com/18009293/130230239-a7a5749e-ecd5-4ee4-8bf2-6383e70d2094.png)

**Comment by Lordblanca** [comment]
Got it thank you
