### ISSUE TITLE
Notification on Stream Off

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#5594]
@DanielnetoDotCom  hello

Is there a possibility to add a notification for a stream that drops? Maybe send an email or an alert to the streamer and the admin that the stream is off? Of course with the option to turn alerts/emails on and off?

**Comment by DanielnetoDotCom** [comment]
If you are using Nginx (NOT Live links) it is possible with some code.

it will require development. if you need a quote please email me at developer@youphptube.com
