### ISSUE TITLE
Video Degragation when using the live stream from mobile internet

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5595]
This is the stream from mobile using AVideo internal webcam streamer
https://mhktube.com/video/521/mile-high-karaoke-live-on-20-aug-21-09-58-50?channelName=_607d8f37e6e2d
This is my same phone with manycam ap from ManyCam
https://mhktube.com/video/229/mhk-mobile-on-27-may-21-23-19-02?channelName=_60814e9341c04

It is a huge difference between the two, is there a setting i am missing to increase my resolution on the live stream through the web?

**Comment by DanielnetoDotCom** [comment]
Correct may be a difference. 

the webcam is still under test, but I will probably add a feature so you will be able to host your own WEBRTC (webcam) server that may improve the quality

FYI, I could not check your videos as long as it requires an account

![image](https://user-images.githubusercontent.com/18009293/130451170-193af811-f181-4585-a788-d16a060cce23.png)
