### ISSUE TITLE
Install live users plugins

### ISSUE THREAD

**Issue by ashrafpro** [WWBN/AVideo#5598]
I am trying to install LiveUsers plugin I purchased,
I uploaded it to: /var/www/html/AVideo/plugin/LiveUsers/
when I try to access it, it shows 500 error /plugin/LiveUsers/LiveUsers.php

from log file: PHP Fatal error:  require_once(): Failed opening required 'plugin/Plugin.abstract.php' (include_path='.:/usr/share/php') in /var/www/html/AVideo/plugin/LiveUsers/LiveUsers.php(18) : eval()'d code(1) : eval()'d code on line 3

sorry my knowledge is fair

**Comment by DanielnetoDotCom** [comment]
Hi, I am really not sure

did I make your installation?

if yes send me the ssh root credentials again and I will check it and install it for you.
