### ISSUE TITLE
CDN experiment is failing. Looking at the CDN page, it appears to have stopped caching.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5599]
**Describe the question**
Started using CDN. Had some site configuration "troubles" and re-did some plug-in configuration. Now I'm seeing the CDN is no longer caching. Checking the CDN plug-in its fields are empty. How to restore CDN functionality?

**Screenshots**
![Screen Shot 2021-08-20 at 1 43 31 PM](https://user-images.githubusercontent.com/11711050/130291405-9f468ef8-6ef0-41d7-a2ea-a4501e7d3d7b.png)
![Screen Shot 2021-08-20 at 1 43 59 PM](https://user-images.githubusercontent.com/11711050/130291456-f6376ed6-ecce-478c-b6b0-939e02dbf093.png)
![Screen Shot 2021-08-20 at 1 44 08 PM](https://user-images.githubusercontent.com/11711050/130291460-4072d0fd-8842-4f01-befc-e402f8de511f.png)

**Comment by DanielnetoDotCom** [comment]
Click on the rebuild button

![image](https://user-images.githubusercontent.com/18009293/130292252-7911b5ca-ea5b-4c72-95e6-d87fa4edc73a.png)
