### ISSUE TITLE
Jitsi Meet - Users in other time zones cannot join

### ISSUE THREAD

**Issue by DrDoug88** [WWBN/AVideo#5601]
We attempted to do a Jitsi Meet the other day with 3 people in 2 different time zones. I created the meet, and the two of us in the same time zone could join. However, the 3rd person, 2 time zones away, could not join and was given the error "Meet has not yet started". I don't have any screen shots, but I ran into this specific issue before and it had to do with the scheduling portion of AVideo within the Jitsi Meet session creation.

When creating a Jitsi Meet session, we only use the Schedule section, as we require the options of setting a name and password for the meeting as well as making the meeting private and only for certain groups. The actual scheduling portion, i.e. the date/time is not that important, just setting it for "Now" is sufficient. However, even scheduling for "Now" has caused users in other time zones to receive this error.  I confirmed with the person that their clock settings were correct and synchronized, so I'm not sure why this error was being generated.

Is there any way that the time requirement can be disabled for a scheduled time of "Now" or at least have the time functionality work correctly?

When creating a Scheduled Meet session, with the When set to "Now", upon the creation of the Meet session, it will launch directly into the Jitsi session and navigate away from the AVideo site. Can this be changed so that the meeting is simply created, and the user can then join with a separate click event?

**Comment by DanielnetoDotCom** [comment]
Hi, 

thanks, I did an update on the Meet plugin (version 3.0)

it will require you a git pull. from now on we also save timezone info on the schedule

**Comment by DrDoug88** [comment]
Thank you kindly Daniel for addressing this issue. I applied the update, and looking at it, it seems that the displayed logic isn't correct. I created a meeting with the schedule set for "Now". It immediately launched me into the meeting (I wish there was an option to disable the auto-launch feature, but I'll put that in Feature Requests). Anyhow, it did record the time zone that I currently am in (U.S Central Time Zone America/Chicago), I confirmed it in the database as well. However, in the "Starts" box it shows: "2021-08-23 15:47:10 Timezone: America/Chicago" and in the "Starts In" box "Coming in 3 hours 56 minutes 56 seconds". My time zone is currently 4 hours different from UTC, hence the 4 hour difference in the displayed value (I'm just guessing that you're logically using UTC as the base timezone). Looking at the database entry, I see the following:

created:     2021-08-23 11:47:10
modified:   2021-08-23 11:47:10
starts:        2021-08-23 15:47:10

I created the meeting at 10:47:10 in the Central Time Zone. The server where the AVideo site resides is in Eastern Time Zone, one hour ahead, hence the 11:47:10 created/modified time. However, the Starts and Starts In values are reflecting a calculation with respect to UTC rather than my local time zone. 

Thank you again for your hard work on this project.

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by DrDoug88** [comment]
It is much closer to correct, but still not 100%. I created a meeting at 2021-08-23 11:42:23 in CST. In the database, the created/modified times show 2021-08-23 12:42:23, which is correct with respect to the site server. The starts time in the database is 2021-08-23 11:42:23, which is also correct with respect to the recorded time zone. The only issue that is incorrect is the "Starts In" time on the site page. It shows that the meeting started an hour ago. The "Starts In" time is being calculated with a mixture of the server's time and my device in my local time.

**Comment by DanielnetoDotCom** [comment]
The created does not match with your starts time.

the starts time is your timezone, the created is the MySQL server timezone

I cannot reproduce this problem here, can you please screenshot where you are seeing the incorrect time?

**Comment by DrDoug88** [comment]
![image](https://user-images.githubusercontent.com/80653458/130488711-07a6c7aa-8af3-4d35-b707-6a568e556492.png)

**Comment by DrDoug88** [comment]
![image](https://user-images.githubusercontent.com/80653458/130489716-d2985f0f-5da9-4b66-b9ea-5103b3aea7ae.png)

**Comment by DanielnetoDotCom** [comment]
I sent a new update just to confirm the timezone

can you please screenshot again with the top clock?

![image](https://user-images.githubusercontent.com/18009293/130490085-527071c3-c088-4739-9034-3114b412a531.png)

**Comment by DrDoug88** [comment]
![image](https://user-images.githubusercontent.com/80653458/130490410-0d6aef47-eccf-4efd-b2c3-abd64cf5de14.png)

**Comment by DrDoug88** [comment]
Ahh, I think I see now. The Custom Jitsi server is possibly in a different time zone as the server. It looks like it is in the Central Time Zone.

**Comment by DanielnetoDotCom** [comment]
The time above is from your AVideo site, NOT jitsi.

please update and check it.

**Comment by DrDoug88** [comment]
I'm shelled into the server where the AVideo site resides. It shows the current Eastern time, an hour ahead of what it shows as the server time. Where is this difference occurring?

**Comment by DrDoug88** [comment]
Could this be due to the Eastern Time Zone currently in Daylight Savings, i.e. EDT (UTC-4), rather than EST (UTC-5)?

**Comment by DanielnetoDotCom** [comment]
It should always use the client timezone (NOT the server timezone)

so it should display your time,. and in the starts in should consider the difference. that is why we are saving the timezone.

Currently, I am not sure the difference, why is it happening. I am still checking

**Comment by DanielnetoDotCom** [comment]
I just create one meet on demo site and seems to work fine

![image](https://user-images.githubusercontent.com/18009293/130493664-d850e330-3616-4b25-b0bb-f5eaa2abcc74.png)

Can you please test it from your timezone?

https://demo.avideo.com/plugin/Meet/

user: admin
pass: 123

**Comment by DrDoug88** [comment]
![image](https://user-images.githubusercontent.com/80653458/130494039-6f3f6952-3f68-4096-8863-d213fe8c5ab4.png)

**Comment by DanielnetoDotCom** [comment]
I guess I found the problem, can you please check again?

**Comment by DrDoug88** [comment]
Yes, it appears to be working correctly. Awesome! I will have some more tests later this week with larger groups of around 20-30 people, so I'll report back after that. The other night we had a couple of users not able to join due to this "Meet has not started" error, so let me first ensure no one is getting that error again.

**Comment by DrDoug88** [comment]
I did a meeting test with someone one time zone behind me. I created the scheduled meeting, but when she got into the meet section, it produced the following error:

![image](https://user-images.githubusercontent.com/80653458/130552525-1d26b2a7-2603-47d7-b3c9-168af70df333.png)

I am on a Windows machine. She is on a Mac, and the error occurred for her using two different browsers: Brave and Safari. I had her clear the cache, but to no effect.

Then, I had her create a meeting, and I attempted to join it, and it created the same error for me:

![image](https://user-images.githubusercontent.com/80653458/130552653-1b3f11fa-7e93-4c03-a68b-8ccff54f97ef.png)

I was able to join my own meeting using a different Windows machine, and did not have any such errors. Only when she created it. Yesterday, before your most recent updates, she was able to join a meeting that I created. In fact about 20 people were able to join without any issues, using a wide array of OS's and architectures. So it looks like the most recent updates broke something.

**Comment by DanielnetoDotCom** [comment]
Hi

can you please check if all your plugins are up to date? 

also please check your error log

**Comment by DrDoug88** [comment]
Plugins are up to date. I checked both the AVideo and webserver (nginx) logs, nothing around that time. I can still regenerate the error if I go to past meetings. I was able to create my own meeting and join it, but she was unable. Same thing vice-versa - she was able to create a meet and join her own meeting, but when I tried to join, it gave me the same error.

**Comment by DrDoug88** [comment]
Here is what the db entries look like:

![image](https://user-images.githubusercontent.com/80653458/130621282-1974b646-cd03-416c-a5a4-4f13972eb25e.png)

**Comment by DrDoug88** [comment]
In the Chrome browser, I am seeing this:

![image](https://user-images.githubusercontent.com/80653458/130622842-b90138a0-1e02-4bc2-9879-d97c7f16b6b3.png)

**Comment by DanielnetoDotCom** [comment]
That means MUST be something in your avideo.log or apache.log

probably a fatal error. I need to see the error to be able to help

**Comment by DrDoug88** [comment]
There is nothing in any of the logs around that time. I checked both the Apache (httpd) logs, the nginx logs, the AVideo logs, you name it...nothing. Something was broken on one of those most recent updates from yesterday. I did just a simple test of creating a public meeting. Then I logged in with another user id on the same machine on the same browser, and it is generating that same error. It has nothing to do with Mac or timezones.

**Comment by DrDoug88** [comment]
If I sign in with an Admin account, I do not recieve the error when reaching the Meet page. However, I tried it with 2 other user accounts, and as soon as I open the Meet page, it generates that error.

**Comment by DanielnetoDotCom** [comment]
If it was a 500 error must be something

**Comment by DrDoug88** [comment]
I just logged into your site, and it is generating the error on there too. I created 2 users, TestUser1 and TestUser2. I gave them rights to Create a Meet, but not Admin rights. You should be able to see it your logs now.

**Comment by DrDoug88** [comment]
The pw for both users is hello.

**Comment by DrDoug88** [comment]
I did just find something in the php logs though. But you should have everything you need now.

**Comment by DrDoug88** [comment]
![image](https://user-images.githubusercontent.com/80653458/130648416-64861d41-55f6-4a92-92f6-a548756707a4.png)

**Comment by DanielnetoDotCom** [comment]
Please try now

**Comment by DrDoug88** [comment]
Everything seems to working correctly now. Thank you kindly Daniel. I'll keep this ticket open for another day or two in case anything else related arises.

**Comment by DanielnetoDotCom** [comment]
More fixes, please make sure you update it
