### ISSUE TITLE
Set Autoplay Next Video by Video ID

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5602]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm trying to set the "autoplay next video". The next video is never in the search results / popup menu of five choices.

**Describe the solution you'd like**
To be able to type the integer id of the video to link to. 
For that to gracefully fail and display an error if user puts in a bad ID / deleted video.

**Describe alternatives you've considered**
Alternative is to:
  1. Open the video that is the "next video"
  2. Rename it to include a unique string in the title (e.g. "xyzzy")
  3. Add "xyzzy" as the next video
  4. Rename the video back

**Comment by DanielnetoDotCom** [comment]
Do you mean is hard to find a video when it has a common title?

what is your idea to make it easier to find a video on the search?

**Comment by walt93** [comment]
The current search needs to be redesigned with a blowtorch and hammer starting with how you're querying the database. That's a much larger discussion.

Let me type the integer ID of the next video, and have the title populate so I can see that I've typed the right one.

**Comment by DanielnetoDotCom** [comment]
I just add the videos_id on the search, so now you may be able to get a video from its id

**Comment by walt93** [comment]
Thanks, that's working really well. MUCH easier to set the next video now. 👍
