### ISSUE TITLE
After latest pull the live notification shuts off 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5603]
Broadcast is live and is broadcasting on embedded links.  It is not showing up on my mhktube site under Live as Live @DanielnetoDotCom 
![Screenshot_20210821-002622_Samsung Internet](https://user-images.githubusercontent.com/70327833/130313028-36097c64-6514-4690-8838-f1cf3eb73829.jpg)
![Screenshot_20210821-002603_Samsung Internet](https://user-images.githubusercontent.com/70327833/130313031-70031a69-d35b-487b-ae0d-c09c608408b5.jpg)
![20210821_001700](https://user-images.githubusercontent.com/70327833/130313034-bde4e1b0-8f3d-47f6-9fd9-d70b17ebf14e.jpg)
![Uploading Screenshot_20210821-000823_Samsung Internet.jpg…]()

**Comment by milehighkaraoke** [comment]
Reseting the ypt socket plugin fixes it and brings it back on.

**Comment by milehighkaraoke** [comment]
Reseting the ypt socket plugin fixes it and brings it back on.

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom  any ideas? No errors in my logs and it continues to do this....

**Comment by DanielnetoDotCom** [comment]
the socket should be running to get the notification.

but you are saying it is running and the notification comes when you restart it?

**Comment by milehighkaraoke** [comment]
It is running, I start broadcasting and notification is there. Randomly the notification goes to 0 and I have to restart the ypt socket by turning the plugin off and then back on. After I do that notification comes back.

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom  If you would like you may make an account and I will give you admin privileges so you can see the logs As they are too long to send over github

**Comment by DanielnetoDotCom** [comment]
To direct look into it, only thru paid support.

also please make sure you have the latest `git pull`

**Comment by milehighkaraoke** [comment]
Should be no need to look into it because it worked perfectly fine until lates git pull on the encoder and site. 
![20210823_095647](https://user-images.githubusercontent.com/70327833/130478968-b98bd5a5-fba8-415d-bb4f-6a5dfc44a7fb.jpg)

**Comment by DanielnetoDotCom** [comment]
If you can reproduce it on demo site I can look into it.

**Comment by milehighkaraoke** [comment]
Log file that encoder is producing on a clean log after 1 encoder is to many characters for github. That's why I thought you might want to see the logs directly  and that's why I offered to let you in with admin privileges

**Comment by DanielnetoDotCom** [comment]
Also, you can check if you did all plugin updates.

Again, direct server support only thru paid support or if you host the server with me

**Comment by milehighkaraoke** [comment]
All plugins are updated.  Do you have an email where I can send the complete encoder file?

**Comment by milehighkaraoke** [comment]
All plugins are updated

**Comment by DanielnetoDotCom** [comment]
I do not need the encoder log as long as the error is on the live.

I do not need and do not recommend a complete log you to share it, I only need the logs at the time the error happend.

**Comment by milehighkaraoke** [comment]
The log from 1 single encoding is to large for git hub.  I cleared log and then did the upload and it did the encode but at 100 percent it puts it back in Q. I then copy and pasted fresh log and it is to many characters for git hub

**Comment by DanielnetoDotCom** [comment]
I am very confused, this issue is regarding a live, and you are talking about a encoder

**Comment by milehighkaraoke** [comment]
#5608
