### ISSUE TITLE
Update without Github

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#5604]
Daniel, tudo bem?

Meu site ainda está na versão 10.7.
![image](https://user-images.githubusercontent.com/37880073/130338635-88204413-34a0-4430-ba3b-9ce0978007e9.png)

Gostaria de saber se existe alguma maneira do site atualizar automaticamente tipo Wordpress?

Eu não consigo atualizar via GITHUB, pois meu servidor é compartilhado. Existe uma outra forma de atualizar?

Grato.

**Comment by RememberForgottenHits** [comment]
??? Can you write in English?

**Comment by walt93** [comment]
It's Portuguese. 

"Daniel, how are you?

My website is still at version 10.7.
image

I would like to know if there is any way for the site to automatically update Wordpress type?

I cannot update via GITHUB as my server is shared. Is there another way to update?

Grateful."

He has to update via Github, shared has nothing to do with his issue IMO. Let me take a stab at it.

Outro usuário aqui.

Você tem que usar git pull para atualizar. Você só atualizará a pasta AVideo. Literalmente,

cd /var/www/html/AVideo/
sudo git pull

Isso apenas atualizará a pasta AVideo, nada mais.

**Comment by RememberForgottenHits** [comment]
If I understand correctly now, you do not have access to ssh? _Then the question arises how you installed this software on your server!?_

If you uploaded the files to an FTP server manually, you can also try to upload new files like this & update your software. Of course, make a backup copy of your files first.

This software does not have the ability to upgrade like wordpress. You are currently using a very old version. The latest version is 11.3

**Comment by gbrn** [comment]
Dear, sorry for not writing in English. Sorry.

I use shared server. And for security reasons SSH is not released.

I understood that the system was able to notify the lack of update. It just says it's always up to date.

**Comment by DanielnetoDotCom** [comment]
You can download and upload the master branch zip file, but it is strongly recommended to use the git pull (also a lot easier)

another info is that a shared server is not good to run AVideo, you may want to use a VPS or a dedicated server

**Comment by RememberForgottenHits** [comment]
If you need a cheap and normal VPS server look here:  https://contabo.com/en/vps/ I have been using their service for almost 8 years.

My AVideo is running on this server https://contabo.com/en/vps/vps-xl-ssd/?image=ubuntu.267&qty=1&contract=1  plus AVideo software runs another 3x wordpress + azuracast software on this server

**Comment by gbrn** [comment]
I have an old plan for a host in Brazil. Whose price is very cheap, $6 a month.
Storage is unlimited and data traffic is also unlimited. This server is still beneficial to me.
Avideo has been running without bottlenecks.

About the update process and information on the system. Is there a possibility to add this process automatically or with one click?
