### ISSUE TITLE
Embed Rumble Videos Support

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5606]
![download (7)](https://user-images.githubusercontent.com/39392449/130374080-1cb455fb-4197-435a-ad17-5f9bee269468.png)

I can get the videos to play using the rumble iframe link for example https://rumble.com/embed/vixnn9/?pub=7dth1

It just has that big gap at the bottom and doesn't auto grab the thumbnail and title.

**Comment by DanielnetoDotCom** [comment]
Hi

the problem is that I do not see any relation between the URL and the embed code

![image](https://user-images.githubusercontent.com/18009293/130463641-0de18d37-c664-4818-bd41-0e80fced2382.png)

**Comment by JoshWho** [comment]
It is kinda weird how they have it. It works using the Embed url it just has that weird void on the bottom of it. Other than that i think it is a good alternative of embedding other platforms as well like Bitchute. 

As long as they have some kind of single line embed link we can call this the old version analog players. or something like that.  

Reason why I thought the Rumble video would be a good idea is because Rumble monetizes the videos but has a horrible way of getting your videos seen, so I figured if we can embed Rumble videos to JoshWho TV it will make it easy for people to also grow their rumble channels, and monetize. While saving us disk space also. this is a Win Win.

**Comment by DanielnetoDotCom** [comment]
I guess if you directly use the embed code, it should work. did you try it?

**Comment by JoshWho** [comment]
Yes and it fit correctly but the Avideo player takes over and it is no longer playable.

**Comment by DanielnetoDotCom** [comment]
I just copy and paste the embed link on my side and also into your side and it works

https://www.joshwhotv.com/video/.QDUjxQ/sniffin-joe-biden-couldn-apos-t-resist---knowing-he-is-known-as-that-creepy-sniffer-guy
