### ISSUE TITLE
Embedding a Video in Outlook 365

### ISSUE THREAD

**Issue by reuvygroovy** [WWBN/AVideo#5607]
Is there any way to show a video from within an Outlook 2016/365 client? For example, a video, where the user would click the play button and view the video within outlook instead of opening an external browser?

Like here: https://www.emailonacid.com/blog/article/email-development/a_how_to_guide_to_embedding_html5_video_in_email/

**Comment by DanielnetoDotCom** [comment]
This would be a good idea but I am not sure if all email clients will support that.

but what email are you receiving on Outlook?

new videos?
