### ISSUE TITLE
API call for Categories with a space between words will not show videos

### ISSUE THREAD

**Issue by tbryantAE** [WWBN/AVideo#5609]
So if you make the Get Categories API call and the Categories names have a space between the words, like "Testing Demo", it will not give the videos in the Category "Testing Demo", but it you change the name to "Testing_Demo" then it will display the videos using the API call.     How can we fix this?

**Comment by DanielnetoDotCom** [comment]
On my side, it works

![image](https://user-images.githubusercontent.com/18009293/130478386-148ff7f6-e839-420c-8fa2-211a7b113394.png)

**Comment by tbryantAE** [comment]
Yes, the API call shows the videos but in the APK app it will not populate the videos under that category unless you get rid of the spaces between words in category.

 

Todd

**Comment by DanielnetoDotCom** [comment]
Hi, sorry what APP are you referring to?

As long as the API is correct the error MUST be on the APP side

**Comment by tbryantAE** [comment]
On the app, if we change category to "Buffalo Hunt", it will now show videos in category.  If I change the category name to "Buffalo_Hunt", then they all show up.

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/130487220-d175ffcf-23fc-4543-a607-b8b2965c742f.png)

**Comment by tbryantAE** [comment]
OK.  So I will look into this.  What version of API is this?  11.2?

**Comment by DanielnetoDotCom** [comment]
I always use the latest
