### ISSUE TITLE
Bypass Encoder Login

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5613]
@DanielnetoDotCom 
Is there a way to have the upload button redirect directly to the encoder page while automaticly entering user credentials in the background?  My users are complaining that there are to many steps to upload. 

Would  look like this 
Step 1

![20210824_195150](https://user-images.githubusercontent.com/70327833/130713791-30d66ae7-eff3-4a6c-b628-3b6715a456f0.jpg)

Result would take me here. 
![Screenshot_20210824-195811_Samsung Internet](https://user-images.githubusercontent.com/70327833/130713855-9a3366b3-364e-40a1-97f1-c072f39b8fc2.jpg)

**Comment by DanielnetoDotCom** [comment]
I do not understand.

when you click on the encoder button from the streamer site it should auto login

**Comment by milehighkaraoke** [comment]
Eliminate these 2 steps
![20210824_195205](https://user-images.githubusercontent.com/70327833/130799096-a1f5a105-aa04-4552-bf38-01f4b2c3725c.jpg)
![20210824_195226](https://user-images.githubusercontent.com/70327833/130799100-9929b21b-4fff-469f-afb9-0ae667601fc8.jpg)

**Comment by milehighkaraoke** [comment]
Go directly from this page
![20210824_195150](https://user-images.githubusercontent.com/70327833/130799248-c389e137-3e8e-462c-898c-1a0d1092f772.jpg)

Directly to this with one click
![Screenshot_20210824-195811_Samsung Internet](https://user-images.githubusercontent.com/70327833/130799379-14ca21ef-fd44-42cb-9fc1-eec641ef6deb.jpg)

**Comment by DanielnetoDotCom** [comment]
This is how works on my side


https://user-images.githubusercontent.com/18009293/130800370-975e58b7-0f57-427a-b73f-47fef2e1fccd.mp4

**Comment by milehighkaraoke** [comment]
Yes, that's how it works on my end also. Users would like one click to get to the upload instead of 4 clicks

**Comment by DanielnetoDotCom** [comment]
sorry, it will not be changed now.

maybe in the future

**Comment by JoshWho** [comment]
It should already do that. You have some kind of java error going on. Look at how mine works.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/39392449/131284316-d64db373-634d-496b-a260-46abb431f962.gif)

**Comment by milehighkaraoke** [comment]
That's what mine does It would be nice to make one click on upload and have the encoder page open up that's what I was talking with was talking with Daniel about
