### ISSUE TITLE
How to update the encoder

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#5615]
The reason for the question is that the encoder from the stream is very slow to encode and it is a problem because my clients are asking questions about their videos from the streams.

I did update the site, but still, the encoder is very slow and no error messages from the log (I know that is what you are going to ask, but I check and nothing was there.

**Comment by DanielnetoDotCom** [comment]
in most cases, the encoder is directly related to the CPU of your server.

you should try to upgrade the server CPU

**Comment by CROSSMediaNet** [comment]
It's the server that I got from you

**Comment by DanielnetoDotCom** [comment]
The dedicated server has a good CPU but we also have better servers that may encode faster 

if you want to upgrade please email me at developer@youphptube.com

P.S update the code does not encode it faster.

BTW what video format are you encoding to?

What resolution?

**Comment by CROSSMediaNet** [comment]
How much does it cost?

We are using HLS format

**Comment by DanielnetoDotCom** [comment]
please email me at developer@youphptube.com for prices
