### ISSUE TITLE
VideoResolutionSwitcher throws Error "Call to undefined function getURL()"

### ISSUE THREAD

**Issue by tobiasjaehnelavl** [WWBN/AVideo#5623]
**Describe the bug**
I have installed the VideoResolutionSwitcher Plugin. As soon as a enable it, I geht the following error when opening any Video:

`array(4) { ["type"]=> int(1) ["message"]=> string(508) "Uncaught Error: Call to undefined function getURL() in /var/www/avideo/plugin/VideoResolutionSwitcher/VideoResolutionSwitcher.php(18) : eval()'d code(1) : eval()'d code:38 Stack trace: #0 /var/www/avideo/plugin/AVideoPlugin.php(62): VideoResolutionSwitcher->getHeadCode() #1 /var/www/avideo/view/include/head.php(3): AVideoPlugin::getHeadCode() #2 /var/www/avideo/view/modeYoutube.php(355): include('/var/www/avideo...') #3 /var/www/avideo/view/index.php(36): require('/var/www/avideo...') #4 {main} thrown" ["file"]=> string(113) "/var/www/avideo/plugin/VideoResolutionSwitcher/VideoResolutionSwitcher.php(18) : eval()'d code(1) : eval()'d code" ["line"]=> int(38) }`

My AVideo version ist 11.

**To Reproduce**
1. Install VideoResolutionSwitcher Plugin
2. Go to "Plugins" in the Admin Menu
3. Enable "VideoResolutionSwitcher" Plugin
4. Browse to any Video

**Expected behavior**
The Video page should open and video resolution should be selectable

**Error Logs**
`[27-Aug-2021 14:16:38 Europe/Berlin] AVideoLog::DEBUG: plugin::setCurrentVersionByUuid 4b9142c0-f0c3-42be-8fe5-a4775111239c, 3.1 SCRIPT_NAME: /objects/pluginSwitch.json.php
[27-Aug-2021 14:16:49 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function getURL() in /var/www/avideo/plugin/VideoResolutionSwitcher/VideoResolutionSwitcher.php(18) : eval()'d code(1) : eval()'d code:38
Stack trace:
#0 /var/www/avideo/plugin/AVideoPlugin.php(62): VideoResolutionSwitcher->getHeadCode()
#1 /var/www/avideo/view/include/head.php(3): AVideoPlugin::getHeadCode()
#2 /var/www/avideo/view/modeYoutube.php(355): include('/var/www/avideo...')
#3 /var/www/avideo/view/index.php(36): require('/var/www/avideo...')
#4 {main}
  thrown in /var/www/avideo/plugin/VideoResolutionSwitcher/VideoResolutionSwitcher.php(18) : eval()'d code(1) : eval()'d code on line 38
[27-Aug-2021 14:16:49 Europe/Berlin] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to undefined function getURL() in \/var\/www\/avideo\/plugin\/VideoResolutionSwitcher\/VideoResolutionSwitcher.php(18) : eval()'d code(1) : eval()'d code:38\nStack trace:\n#0 \/var\/www\/avideo\/plugin\/AVideoPlugin.php(62): VideoResolutionSwitcher->getHeadCode()\n#1 \/var\/www\/avideo\/view\/include\/head.php(3): AVideoPlugin::getHeadCode()\n#2 \/var\/www\/avideo\/view\/modeYoutube.php(355): include('\/var\/www\/avideo...')\n#3 \/var\/www\/avideo\/view\/index.php(36): require('\/var\/www\/avideo...')\n#4 {main}\n  thrown","file":"\/var\/www\/avideo\/plugin\/VideoResolutionSwitcher\/VideoResolutionSwitcher.php(18) : eval()'d code(1) : eval()'d code","line":38} SCRIPT_NAME: /view/index.php
`

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 92.0.4515.159

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by tobiasjaehnelavl** [comment]
Interesting.
I get this one:
![image](https://user-images.githubusercontent.com/87174106/131512986-da68b687-4e8c-4d6a-8c7a-767e81fbd8de.png)

And this is also what GitHub says:
![image](https://user-images.githubusercontent.com/87174106/131513182-f48c2c60-9e69-4cb2-a0f1-39ef46ccdc41.png)
![image](https://user-images.githubusercontent.com/87174106/131513227-abaa1ac8-8b5d-4f8b-921c-36cd2a94eeee.png)

Can you help me?

**Comment by DanielnetoDotCom** [comment]
You must update it to version 11.3

you must use the git command to it


Check this https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by DanielnetoDotCom** [comment]
Btw the gab links show a player for me

**Comment by tobiasjaehnelavl** [comment]
I've now temporarily switched to master now and it indeed solved the issue.
Thank you very much!

Still, I want to avoid staying on the master branch as it's constantly changing while the version number stays the same.
That's why I always go to defined tags to get a reliable version.
Otherwise, whenever I reinstall, i.e. rebuild my Docker image, I get a different code base.
I could also stick to a commit hash, but that seems a bit strange.

Would it be possible that you create a tag from whatever commit you define as version 10.3?

Thank you very much again for your help.
