### ISSUE TITLE
Downloaded file names are nonsense

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5628]
**Describe the bug**
I download a file. I expect its name to reflect the contents.

**To Reproduce**
1. Go to a file
2. Click on Download
3. Look at what you got

_YPTuniqid_6072939c451400.19045983_480.mp4
video_210510200946_d59a_480.mp4
...

**Expected behavior**
The file name to reflect the title of the file I downloaded. Additionally it can have suffixes like 360P 480P that would be a bonus.

**Comment by DanielnetoDotCom** [comment]
Are you self-hosting the files?

what type of storage do you have?

**Comment by walt93** [comment]
Self hosted 11TB RAID5

**Comment by DanielnetoDotCom** [comment]
Make sure you have this installed https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

the filename should be the video title. I am not sure what is going on in your side

**Comment by walt93** [comment]
Looks like you already set up XSendFile when you did the install.

```
sudo apt-get install libapache2-mod-xsendfile && sudo a2enmod xsendfile
Reading package lists... Done
Building dependency tree
Reading state information... Done
libapache2-mod-xsendfile is already the newest version (0.12-2).
0 upgraded, 0 newly installed, 0 to remove and 44 not upgraded.
Module xsendfile already enabled

sudo pico /etc/apache2/sites-available/youphptube.conf

    <Directory /var/www/html/AVideo/>
        Options Indexes FollowSymLinks
        XSendFile on
        XSendFilePath /var/www/html/AVideo/
        AllowOverride All
        Require all granted
        Order Allow,Deny
        Allow from All
    </Directory>
```

What else to check?

**Comment by DanielnetoDotCom** [comment]
Can you please detail where exactly are you downloading the file from? what are you doing to download?

**Comment by walt93** [comment]
Clicking the download button opens a browser tab instead of saving (thanks Safari), so right clicking like so:

![Screen Shot 2021-09-01 at 3 08 00 PM](https://user-images.githubusercontent.com/11711050/131752137-afbd76cc-2ffe-4175-a1f4-b20556cd2f1e.png)

**Comment by DanielnetoDotCom** [comment]
The idea is to click on the button, NOT save link

**Comment by walt93** [comment]
Right. Point goes to , Safari sucks. When you click on the button, Safari is opening into a new browser tab and playing the video. A lot of us mentally-tortured Safari users are going to right click as a result.

Is it a complete nightmare to inject the filename into this right-click-save-as scenario?

**Comment by DanielnetoDotCom** [comment]
Hi, 

I just tested on Safari on a MacBook, it downloads the file fine with the correct filename, just asked me a confirmation before download.

Also, the "save link as" works fine.

can you please test it on the demo site? https://demo.avideo.com/video/347/short-video-ads-sample

**Comment by walt93** [comment]
You are correct. Was this in your most recent fixes? Right click is still getting the wrong filename but regular click is actually downloading directly now.
