### ISSUE TITLE
Bug or configuration? Category pages do not show pagination, do not infinite scroll. Much media inaccessible.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5632]
**Describe the bug**
Category pages that have sub-categories do not show all content.

**To Reproduce**
1. Place 100 files in category A.
2. Place 100 files in category B
3. Set A as a the parent category of B
4. Load the category page for A
5. Observe no pagination, no infinite scroll, not all items in category A can be accessed.

**Expected behavior**
Pagination controls ideal, infinite scroll otherwise. 

**Screenshots**
![Screen Shot 2021-08-29 at 10 59 49 PM](https://user-images.githubusercontent.com/11711050/131292682-8475a287-ce8a-4a16-8ccf-f0a966cf1d4a.png)

**Comment by DanielnetoDotCom** [comment]
it supposes to be an infinite scroll, check for JS or PHP errors

**Comment by walt93** [comment]
There are no errors in the console. I'm not seeing the API call.

![Screen Shot 2021-08-30 at 3 40 35 PM](https://user-images.githubusercontent.com/11711050/131414943-f8ce5f5c-ecc5-42b8-90b4-3366c76f8530.png)
![Screen Shot 2021-08-30 at 3 40 51 PM](https://user-images.githubusercontent.com/11711050/131414962-ec0d81a8-f2c0-4e67-acb6-9ab0f8af5bc3.png)

**Comment by DanielnetoDotCom** [comment]
Do you approve if I look directly into your installation? I cannot reproduce it here

**Comment by walt93** [comment]
Yes of course, let me know if you can get in (forgot if I revoked your login or not)

**Comment by DanielnetoDotCom** [comment]
Hi, I have no access anymore.

but please make another git pull and clear the cache and check if it is working now.

BTW do you have the variable `$global['rowCount']` in your configuration.php file?

**Comment by walt93** [comment]
I did the pull, I cleared the cache, still not seeing the infinite scroll. I do not have the global[rowcount] being set in the streamers configuration.php file. What other information can I gather?

**Comment by walt93** [comment]
I re-enabled your login and e-mailed you the password, should you need to get in to check this, you have my blessings.

**Comment by DanielnetoDotCom** [comment]
The infinite scroll is working here 

![chrome-capture (1)](https://user-images.githubusercontent.com/18009293/131910298-1318da4f-94c8-4496-af63-84094ad5b3b7.gif)

**Comment by walt93** [comment]
Yes, it is not happening on all pages. I have a multiple-level hierarchy. Here is one example:

https://conspyre.tv/cat/parapsychology

parent category has 20 videos
subcategory has 117 videos
![Screen Shot 2021-09-02 at 3 11 39 PM](https://user-images.githubusercontent.com/11711050/131922941-96a5545d-f15f-44d9-9277-b527737e2d7a.png)

page shows 6 rows of 6 videos (36)

![Screen Shot 2021-09-02 at 3 13 43 PM](https://user-images.githubusercontent.com/11711050/131923124-a3a0c2a2-3f83-44fc-9b17-88745ac29755.png)

There are other examples, this is one.

**Comment by DanielnetoDotCom** [comment]
Hi, 

sorry for the late reply....

I see, I guess it is not listing subcategories. can you please confirm if that is the issue?

if that is the issue I may need some more time to be able to update it. but for sure in some future release I will send this update

**Comment by walt93** [comment]
Daniel, a more concise description "For *some* pages with subcategories, the subcategories are shown, but autoscroll isn't working so you can't access all the files for the category you're looking at".

When you fix this, just a suggestion, I personally dislike autoscroll with an unending passion - it's such terrible UX for the user compared to pagination. How do you know when it's available? How do you know where you are on the page? How can you bookmark and save your place? Pagination doesn't suffer these issues.

**Comment by para2022** [comment]
> Daniel, a more concise description "For _some_ pages with subcategories, the subcategories are shown, but autoscroll isn't working so you can't access all the files for the category you're looking at".
> 
> When you fix this, just a suggestion, I personally dislike autoscroll with an unending passion - it's such terrible UX for the user compared to pagination. How do you know when it's available? How do you know where you are on the page? How can you bookmark and save your place? Pagination doesn't suffer these issues.

I think it should be on the homepage only and on the pages it should have the numbered block again. How on earth could you find a video without the numbered block? For instance a user may want to jump to the first uploads on the site and now they have no way of doing so. The load more bar looks great on the homepage it is a big inrpovement as the numbered blocks on the homepage (how it was) was messy as it loaded the whole page making it confusing for users.

**Comment by DanielnetoDotCom** [comment]
I may add a pagination in the future.
