### ISSUE TITLE
I've started my live stream from OBS, but my Live is stuck in "offline"

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5633]
**Describe the question**
I've started streaming from OBS and everything looks good from that end, no dropped frames, "Live" indicator is active, counting time.

On https://conspyre.tv/plugin/Live/ I can press the play button and see the stream, but it's not appearing in my list of Live streams on the home page or in the menu.

What am I missing to take the stream "online"?

**Screenshots**
![Screen Shot 2021-08-29 at 11 40 46 PM](https://user-images.githubusercontent.com/11711050/131296404-60e3a390-5937-4516-ae7d-e33888b0a08e.png)

**Comment by DanielnetoDotCom** [comment]
is your live listed?

![image](https://user-images.githubusercontent.com/18009293/131325428-77ab0148-0cdd-4338-977f-861b0ee8b167.png)

**Comment by walt93** [comment]
Yes, it is. The first time I started streaming I’m not sure what I did in this page. It was offline. I reloaded the page. It went online. It seemed like it would go offline/online when I hit start/stop streaming on OBS. 

Now I cannot make it so that again.

**Comment by DanielnetoDotCom** [comment]
I am not understanding what you said.

**Comment by walt93** [comment]
When I first tried streaming, I loaded this page, pressed play - was looking at my stream playing in the OFFLINE state, and wondering how to make it go ONLINE. I reloaded the page. It went online.

Now I cannot replicate that behavior. It will not go online. Reloading the page seems not to have been the trigger, just a coincidence? I don't know. Just reporting the behavior.

I've tried this with a couple different user accounts. Same behavior. I copy the stream URL and key into OBS. Start streaming from OBS. OBS looks happy. I can only see the stream from https://conspyre.tv/plugin/Live/ if I hit the play button. It never goes online. 

![Screen Shot 2021-08-30 at 3 32 48 PM](https://user-images.githubusercontent.com/11711050/131414523-9ab356bd-5e47-442d-a26f-5785a504b692.png)

**Comment by DanielnetoDotCom** [comment]
Is your socket running?

**Comment by walt93** [comment]
This? Yes. 
![Screen Shot 2021-08-31 at 7 25 31 PM](https://user-images.githubusercontent.com/11711050/131601611-7ee1a4dd-161f-47c0-b054-5a2f941f7741.png)

**Comment by DanielnetoDotCom** [comment]
To be able to check I at least need the admin credentials

**Comment by walt93** [comment]
I created a admin user and sent you the credentials.

**Comment by DanielnetoDotCom** [comment]
I just found a missing update 

![image](https://user-images.githubusercontent.com/18009293/131898973-4bf1a5c1-a706-468c-9c00-f7789c911bf3.png)


also, you had this checked.

OMG took me a long time to figure it out. I will add this message to the log messages

**Comment by walt93** [comment]
Thank you Daniel I will apply the update. I’m not sure why I tried this option, but I believe it needs a “warning: prevents livestream connection don’t use unless you know what you’re doing” in that (I)nfo bubble.
