### ISSUE TITLE
mkdir(): Protocol error in functions.php

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#5634]
Since updating 11.1 to the last one i've a lot of the following errors:

[30-Aug-2021 08:40:35 Europe/Berlin] PHP Warning:  mkdir(): Protocol error in /var/www/html/www.mysite.com/objects/functions.php on line 1945

![Snap1](https://user-images.githubusercontent.com/39981177/131298099-14cfee3a-7f74-44ef-bef1-3ce3bcc70840.jpg)

Running the last update & plugins.

Already did sudo chown -R www-data:www-data /var/www/html/mysite and sudo chmod -R 777 /var/www/html/mysite

Also cleared cache and did sudo git fetch --all and sudo git reset --hard origin/master

Running on port 8080

**Comment by DanielnetoDotCom** [comment]
I have no idea where this error comes from.
here is an update to help debug it. in case it happens again please share the log.

**Comment by TLCReuver** [comment]
Thanks for update;

It seem that functions.php try to execute mkdir() with portnumber ':8080' as argument inside it (/media.beesel-reuver.nl:8080\/http\/admin_)

[avideo.log](https://github.com/WWBN/AVideo/files/7076969/avideo.log)

**Comment by DanielnetoDotCom** [comment]
Hi, I think I got it, please try this update

**Comment by TLCReuver** [comment]
It is perfect now.

Th@nkz Daniel
