### ISSUE TITLE
Install of webrtc server on the same server

### ISSUE THREAD

**Issue by nikstream** [WWBN/AVideo#5638]
Hi Daniel,

Thanks for WebRTC integration.  
I have gone through Your wiki for Ovenmedia server but can't
understand.

Do you mean to say that now we can install Ovenmedia on the same server with Avideo .
OR we need to install on different server and then configure.

And Once again 
Thanks, 
& Stay Safe.....

**Comment by DanielnetoDotCom** [comment]
It is not officially released yet, please check again next week
