### ISSUE TITLE
unable to set up Facebook OAuth

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5639]
I know I'm missing something simple can some on help

URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs

![facebook-OAuth](https://user-images.githubusercontent.com/37937968/131540660-c12d2158-a9a4-431c-b52a-1d5e9abea8d2.png)

**Comment by DanielnetoDotCom** [comment]
This is something you have to deal with Facebook.

As I can see you MUST submit an icon image

**Comment by Lordblanca** [comment]
This is the part Im not getting 
![image](https://user-images.githubusercontent.com/37937968/131744348-d39600a7-b48c-4cf2-82bb-e68474fda2b4.png)

**Comment by Lordblanca** [comment]
I found it.  URL ...https://tutorials.avideo.com/video/enable-facebook-login-and-making-a-video-private/page/2?firstPage=Default&theme=slate   
Hope this helps some one else looking for the same thing. Plus Setting up for groups. You have done alot of work on this. Blessings
