### ISSUE TITLE
Help Unable to complete Facebook OAuth Help thanks

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5640]
I know I'm missing something simple can some on help

URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs
![facebook-OAuth](https://user-images.githubusercontent.com/37937968/131541545-4f692cee-6c32-4082-b48e-e357f9c294ab.png)

**Comment by DanielnetoDotCom** [comment]
Duplicated https://github.com/WWBN/AVideo/issues/5640
