### ISSUE TITLE
User group videos cannot get thumbs

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5642]
Hi Daniel,
Cannot get thumbs after setting the user group for the video

![image](https://user-images.githubusercontent.com/47063171/131607882-e0b886ce-aeb0-4038-8323-8f7c7819b7ff.png)
![image](https://user-images.githubusercontent.com/47063171/131607929-ee292739-e71b-4199-a026-edac93a94a2a.png)

It also failed when I used the MP4ThumbsAndGif plug-in test, the test demo site (demo.avideo.com)

![image](https://user-images.githubusercontent.com/47063171/131608675-8f2dc919-af71-4eb0-b0cd-5bcc75f53253.png)
![image](https://user-images.githubusercontent.com/47063171/131608636-2fbcc7c6-044f-4e02-b433-19488c774b06.png)
![image](https://user-images.githubusercontent.com/47063171/131608716-11206638-d640-43b1-bf32-f0c3a1427312.png)
![image](https://user-images.githubusercontent.com/47063171/131608793-d08c74e2-f97e-40f9-b730-f531310e5f59.png)

**Comment by DanielnetoDotCom** [comment]
What AVideo version and VideoHLS plugin are you running?

**Comment by chenjian9885** [comment]
![image](https://user-images.githubusercontent.com/47063171/131719468-84ae5f5d-d283-49b3-b1b3-8553ac865452.png)
![image](https://user-images.githubusercontent.com/47063171/131719586-810465b9-5049-4d61-ba79-31f9ac2f0dff.png)

**Comment by chenjian9885** [comment]
I have the same result on the demo site (https://demo.avideo.com), as long as the video is set as a private video (user group), thumbs cannot be obtained

**Comment by DanielnetoDotCom** [comment]
Hi, I just sent some updates to the encoder, can you please update and check again?

**Comment by chenjian9885** [comment]
Hello
I just tested the same result on the demo site (https://demo.avideo.com).
![image](https://user-images.githubusercontent.com/47063171/131899585-1d72920b-1141-4f4d-9963-991b4dbb0a96.png)

**Comment by DanielnetoDotCom** [comment]
The demo was not updated, please try it now

You will need to update the streamer, the encoder, and the VideoHLS plugin to version 5.7

![chrome-capture](https://user-images.githubusercontent.com/18009293/131909826-51cee178-06d3-4645-b212-662a92f823b5.gif)

**Comment by chenjian9885** [comment]
Hello
How can I update the encoder.

**Comment by DanielnetoDotCom** [comment]
Go to the encoder folder and make a `git pull`

**Comment by chenjian9885** [comment]
Why is there no effect after I update
![image](https://user-images.githubusercontent.com/47063171/131949420-61b4b8a2-298b-42c8-b167-65c58837cff1.png)
![image](https://user-images.githubusercontent.com/47063171/131949651-c904b45e-25d4-44d4-960a-3a283628b914.png)
![image](https://user-images.githubusercontent.com/47063171/131949672-7ce7ba04-7991-4b7b-a960-dcfbde314542.png)
![image](https://user-images.githubusercontent.com/47063171/131949719-1cc61a86-9672-4aa0-ae34-a9a8fdc065db.png)

**Comment by DanielnetoDotCom** [comment]
can you please do this ...

1. delete your log file.
2. access the video that supposes to have a thumbs 
3. wait about 30 seconds and refresh the page
4. Share your log after the refresh is complete.

**Comment by chenjian9885** [comment]
I have purchased the PayPerView plug-in, and it works well now, I guess it has something to do with the PayPerView plug-in.
