### ISSUE TITLE
Blackblaze Error (I think it's the account ID, I don't see it)

### ISSUE THREAD

**Issue by Yoxed** [WWBN/AVideo#5644]
Received error from B2:

#0 /var/www/html/realmediatt/objects/gliterd/backblaze-b2/src/Http/Client.php(28): BackblazeB2\ErrorHandler::handleErrorResponse() #1 /var/www/html/realmediatt/objects/gliterd/backblaze-b2/src/Client.php(422): BackblazeB2\Http\Client->request() #2 /var/www/html/realmediatt/objects/gliterd/backblaze-b2/src/Client.php(38): BackblazeB2\Client->authorizeAccount() #3 /var/www/html/realmediatt/plugin/Blackblaze_B2/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(55): BackblazeB2\Client->__construct() #4 /var/www/html/realmediatt/plugin/Blackblaze_B2/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(326): Blackblaze_B2->getClient() #5 /var/www/html/realmediatt/plugin/Blackblaze_B2/test.php(18) : eval()'d code(1) : eval()'d code(14): Blackblaze_B2->copy_to_B2() #6 /var/www/html/realmediatt/plugin/Blackblaze_B2/test.php(18) : eval()'d code(1): eval() #7 /var/www/html/realmediatt/plugin/Blackblaze_B2/test.php(18): eval() #8 {main}

[https://imgur.com/undefined](url)

**Comment by Yoxed** [comment]
This is what i see, I entered all my information correctly. [https://imgur.com/Bx8UeF9](url)

**Comment by DanielnetoDotCom** [comment]
If you added all the information you should have a message from backblaze detailing the error

check more from your log

**Comment by Yoxed** [comment]
Where do i find the log? The information i provided above was the error messaged i received when i clicked on "Test it"

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by Yoxed** [comment]
[08-Sep-2021 21:35:42 America/La_Paz] AVideoLog::ERROR: {"type":1,"message":"Uncaught BackblazeB2\\Exceptions\\B2Exception: Received error from B2:  in \/var\/www\/html\/myMySQLUser\/objects\/gliterd\/backblaze-b2\/src\/ErrorHandler.php:36\nStack trace:\n#0 \/var\/www\/html\/myMySQLUser\/objects\/gliterd\/backblaze-b2\/src\/Http\/Client.php(28): BackblazeB2\\ErrorHandler::handleErrorResponse()\n#1 \/var\/www\/html\/myMySQLUser\/objects\/gliterd\/backblaze-b2\/src\/Client.php(422): BackblazeB2\\Http\\Client->request()\n#2 \/var\/www\/html\/myMySQLUser\/objects\/gliterd\/backblaze-b2\/src\/Client.php(38): BackblazeB2\\Client->authorizeAccount()\n#3 \/var\/www\/html\/myMySQLUser\/plugin\/Blackblaze_B2\/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(55): BackblazeB2\\Client->__construct()\n#4 \/var\/www\/html\/myMySQLUser\/plugin\/Blackblaze_B2\/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(276): Blackblaze_B2->getClient()\n#5 \/var\/www\/html\/myMySQLUser\/plugin\/Blackblaze_B2\/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(260): Blackblaze_B2->removeFilePath()\n#6 \/var\/www\/html\/myMySQLUser\/plugin\/Blackblaze_B2\/Blackblaze_B2.ph","file":"\/var\/www\/html\/myMySQLUser\/objects\/gliterd\/backblaze-b2\/src\/ErrorHandler.php","line":36} SCRIPT_NAME: /objects/videoDelete.json.php

**Comment by Yoxed** [comment]
Do you see any problem here where you can guide me?

**Comment by DanielnetoDotCom** [comment]
I guess you have wrong credentials 

please check this https://github.com/WWBN/AVideo/wiki/BackBlaze-B2-plugin

**Comment by Yoxed** [comment]
It says account ID but i don't see that? Is it supposed to be like that?

[https://prnt.sc/1rmtjxu](url)
[https://prnt.sc/1rmthwy](url)

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/132744131-7832b976-5362-4ce6-8b46-ed32e31b5d6a.png)

**Comment by Yoxed** [comment]
Okay we are getting different results now.
Now it is saying -

**"required filed accountId cannot be null** but I don't see accountId in my plugin form. How will I fill it in if I don't see it?

Received error from B2: **required field accountId cannot be null**
#0 /var/www/html/realmediatt/objects/gliterd/backblaze-b2/src/Http/Client.php(28): BackblazeB2\ErrorHandler::handleErrorResponse() #1 /var/www/html/realmediatt/objects/gliterd/backblaze-b2/src/Client.php(121): BackblazeB2\Http\Client->request() #2 /var/www/html/realmediatt/objects/gliterd/backblaze-b2/src/Client.php(439): BackblazeB2\Client->listBuckets() #3 /var/www/html/realmediatt/objects/gliterd/backblaze-b2/src/Client.php(173): BackblazeB2\Client->getBucketIdFromName() #4 /var/www/html/realmediatt/plugin/Blackblaze_B2/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(357): BackblazeB2\Client->upload() #5 /var/www/html/realmediatt/plugin/Blackblaze_B2/test.php(18) : eval()'d code(1) : eval()'d code(14): Blackblaze_B2->copy_to_B2() #6 /var/www/html/realmediatt/plugin/Blackblaze_B2/test.php(18) : eval()'d code(1): eval() #7 /var/www/html/realmediatt/plugin/Blackblaze_B2/test.php(18): eval() #8 {main}

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/132755590-7084cccd-2895-40d7-af1f-38f117e818ed.png)


Backblaze Account Id = Application keyID

**Comment by Yoxed** [comment]
Okay I used that and now I have the same error again?
What can I possibly be doing wrong, this should be simple but I can't seem to get it right...

I am providing more images to get it better sorted.

Plugin form --> https://imgur.com/a/rTuMcs2 (Note: I even used the 12 digit characters and that's when i got the accountid(null) error)

Bucket --> https://imgur.com/LaMgR3m

Master Application Key - https://imgur.com/ZclUy35

Application Key - https://imgur.com/Oy0MzX1 




Received error from B2:
#0 /var/www/html/realmediatt/objects/gliterd/backblaze-b2/src/Http/Client.php(28): BackblazeB2\ErrorHandler::handleErrorResponse() #1 /var/www/html/realmediatt/objects/gliterd/backblaze-b2/src/Client.php(422): BackblazeB2\Http\Client->request() #2 /var/www/html/realmediatt/objects/gliterd/backblaze-b2/src/Client.php(38): BackblazeB2\Client->authorizeAccount() #3 /var/www/html/realmediatt/plugin/Blackblaze_B2/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(55): BackblazeB2\Client->__construct() #4 /var/www/html/realmediatt/plugin/Blackblaze_B2/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(326): Blackblaze_B2->getClient() #5 /var/www/html/realmediatt/plugin/Blackblaze_B2/test.php(18) : eval()'d code(1) : eval()'d code(14): Blackblaze_B2->copy_to_B2() #6 /var/www/html/realmediatt/plugin/Blackblaze_B2/test.php(18) : eval()'d code(1): eval() #7 /var/www/html/realmediatt/plugin/Blackblaze_B2/test.php(18): eval() #8 {main}

**Comment by DanielnetoDotCom** [comment]
I am pretty sure you still have configuration confusion.

please make sure you follow this carefully, https://github.com/WWBN/AVideo/wiki/BackBlaze-B2-plugin

also, share your plugin parameters and your Backblaze screenshots

**Comment by Yoxed** [comment]
I provided Imgur links above in my previous comment

**Comment by DanielnetoDotCom** [comment]
you have a wrong keyID

![image](https://user-images.githubusercontent.com/18009293/132886836-c6bf78db-54df-4062-8960-e01e980265d4.png)

**Comment by Yoxed** [comment]
Okay i did that and it said the following "Received error from B2: required field accountId cannot be null"
i only used e482997f150e and i got that error. See now i'm confused, Is it the script?

**Comment by DanielnetoDotCom** [comment]
I am not sure, try to delete the master application key and create it again. maybe something is missing on the BackBlaze side

**Comment by DanielnetoDotCom** [comment]
I am testing it again, hold on

**Comment by DanielnetoDotCom** [comment]
Sorry about the inconvenience, I found something, I am releasing version 3.1 that may resolve that issue.

also, I made a video to try to help you configure it https://tutorials.avideo.com/video/111/how-to-configure-backblaze

**Comment by Yoxed** [comment]
Thank you so much for your help, it works perfectly now. You were very helpful for this issue. The update worked and the video was helpful aswell. Blackblaze plugin is working.
