### ISSUE TITLE
"Sorry! This streamer site is not allowed"

### ISSUE THREAD

**Issue by Yoxed** [WWBN/AVideo#5645]
My site is realmediatt.com and the encoder site is realmediatt.com/upload but when I installed the encoder I used realmediatt.com/realmediatt which was the file path. The encoder sites only logins on that URL but when I try to login to realmediatt.com/upload and putting realmediatt.com as Streamer Site it's saying "Sorry! This streamer site is not allowed". Any assistance would be appreciated.

**Comment by DanielnetoDotCom** [comment]
Delete the encoder database and the Encoder/videos/configuration.php file and install it again.

**Comment by Yoxed** [comment]
I  fixed it thanks, I reinstalled everything over but this time I create an alias link in my sites-available conf. file.
