### ISSUE TITLE
Chat Screen not showing complete and live stream not showing complete

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5646]
Chat window is pinned to the top of all my screens and devices.
Live Stream can not see top menu.
Chat and top of screen is not showing.  On desktop, tablet, and Iframe embed.
These are the settings for the chat.
![Chat-Settings1](https://user-images.githubusercontent.com/37937968/131919252-aed8aaa2-2b34-4e4f-8e4c-d3642c7ddc65.png)
![Chat-settings-2](https://user-images.githubusercontent.com/37937968/131919255-4bc58a4f-3e94-443f-bba1-9ee3dc0ab301.png)

Images firefox desktop 1 and 2

![Firefox-Desktop-lLive-Stream-1](https://user-images.githubusercontent.com/37937968/131919375-ae461c48-dda7-4919-a82e-c789a7c8eb18.png)
![Firefox-Desktop-lLive-Stream-2](https://user-images.githubusercontent.com/37937968/131919377-5a146470-10de-4208-9858-e8abe889b5d9.png)

Live Plugin settings
![Live-Plugin-Settings-1](https://user-images.githubusercontent.com/37937968/131919454-71024d32-a8d9-42a7-b060-d3d8a42c2dd7.png)
![Live-Plugin-Settings-2](https://user-images.githubusercontent.com/37937968/131919456-a8ed1b6d-2265-41df-bf6f-16e9a9bc879e.png)
![Live-Plugin-Settings-3](https://user-images.githubusercontent.com/37937968/131919460-47b25242-b133-4718-9cf8-2927294fa843.png)

Desktop embed
640x480 and 1920x1080
![MS-Edge-Desktop-embed-640x480](https://user-images.githubusercontent.com/37937968/131919526-b1a249a0-a147-4340-b4a2-c8da4020fefb.png)
![MS-Edge-Desktop-embed-640x480--2](https://user-images.githubusercontent.com/37937968/131919527-26bd8d13-0b5e-4bb0-8880-e54d6c66a42e.png)
![MS-Edge-Desktop-embed-1920x1080-1](https://user-images.githubusercontent.com/37937968/131919528-d1c409cf-b7b8-44c7-9d0d-fde61900cc8c.png)
![MS-Edge-Desktop-embed-1920x1080-2](https://user-images.githubusercontent.com/37937968/131919530-3904afba-705b-4a9d-937c-9fff062c6936.png)
![Samasung tablet A Screen Shot-1](https://user-images.githubusercontent.com/37937968/131919531-a8de3b20-d676-4db2-bf73-c3b85de7cbb0.jpg)
![Samasung tablet A Screen Shot-2](https://user-images.githubusercontent.com/37937968/131919532-97c05580-ba99-4fee-9a4f-c781a410f0d1.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, 

On Chat2 plugin parameters make sure you select `Static fixed on right`

![image](https://user-images.githubusercontent.com/18009293/131997530-8038fff9-8cbd-4e9e-ab27-69b09a2692aa.png)

**Comment by Lordblanca** [comment]
Did that. But still no top menu on desktop view.
![Desktop-view -No-Top-menu](https://user-images.githubusercontent.com/37937968/132057509-022ff78a-f453-4986-97f9-ca7031b55257.png)

and in tablet
Still on left and no top menu.
![Screenshot_20210903-152937_Firefox](https://user-images.githubusercontent.com/37937968/132057786-e44eecea-8d88-41b0-88b6-a2dbf7c00938.jpg)
![Screenshot_20210903-152953_Firefox](https://user-images.githubusercontent.com/37937968/132057796-a6d07f83-ce8c-4e03-a5f5-7fe82641b4cf.jpg)

**Comment by Lordblanca** [comment]
Is there a way to rest the live and the chat to default. I tried switching them off and them restarting the server. No Change

**Comment by DanielnetoDotCom** [comment]
To reset a plugin you can delete the parameters code and save it

![chrome-capture (4)](https://user-images.githubusercontent.com/18009293/132070451-a1c52fef-5c0d-4b78-aa1d-783ddcd7a273.gif)

after doing it on Chat and on Live delete the cookies from your browser

**Comment by Lordblanca** [comment]
I Reset the chat looks good. except the iFrame to my website. The Top Menu does not show.
![image](https://user-images.githubusercontent.com/37937968/132111972-5e252a7d-da79-421b-a68d-21959908f07b.png)

I'm testing everything before I go live. Plus I turned off the SignUpAgreement for now I think that my be part of the problem. Once I turned it off everything looks better. Except the IFrame to my web site... The top menu does not show in the Iframe. It did before.

**Comment by Lordblanca** [comment]
@DanielnetoDotCom Any info on how to resolve my issues... Thanks

**Comment by DanielnetoDotCom** [comment]
What top menu are you referring to?

**Comment by Lordblanca** [comment]
@DanielnetoDotCom You look at picture 4 ,13 and 17 in this thread you will see that the chat window is under the menu. And that the entire live stream does not show itself. Only on the desktop/laptop. Not on mobile nor on tablet

**Comment by DanielnetoDotCom** [comment]
Duplicated https://github.com/WWBN/AVideo/issues/5659
