### ISSUE TITLE
unlisted videos can be shown by standard url

### ISSUE THREAD

**Issue by macfori** [WWBN/AVideo#5651]
Maybe I didn't understand the concept of AVidoe; then please help me.

I rendered a new Video using HLS Plugin and recognized that the standard URL
https:://myDomain.com/v/1
shows the video also beeing unlisted.
So if that is the standard behaviour, the unlisting function is not useful.
Everyone can iterate about the videos. ..../v/1 ..../v/2

In the configuration of the Theme / Gallery I couldn't find an option, to switch that behavour of.
The option of suppressing unlisted videos is set and works on the main-page.
Is there a workaround.
Tx.

What's my goal:
I want do handle unlisted videos, that can be viewed on a external site (embeddig) or via users that know the link.
But it's a issue of security, of one can step over this videos only by changing the url  ../v1/.   ../v/2 ...
Making the videos private an offering to a special group is not useful. I don't wand to force my friends to register for viewing a video.

**Comment by DanielnetoDotCom** [comment]
unlisted means it will not appear on the first page but still accessible, you may want to use password protect on the video

**Comment by macfori** [comment]
Tx for explaining. But I look for a way to offer a link like youtube / vimeo for videos that are unlisted and not easy to find by /v/1 .... :)
So like you say, there would be no way for me to use that.

**Comment by macfori** [comment]
So maybe you have a trick for a behaviour I think it's a contradiction:
In video-edit-page I can set up websites / URLs where the video can be embedded. Great.
I would like to deny access by using the url for visitors trying .../v/1 .... v/2/ .... with success also the video is set up to be only embedded on https://anotherDomain.com
So is there a possibility to deny access by trying urls but using the embed function. I think it's a contradiction in thinking the embed function denies access on other sites - and on the other site the unlisted video can be seen by trying urls v/1 ...v/2.
Tx for further information.

**Comment by DanielnetoDotCom** [comment]
Try this

![image](https://user-images.githubusercontent.com/18009293/132515962-f9697672-30e7-4311-b757-b591c8a64429.png)

**Comment by macfori** [comment]
I think I got it: SecureVideosDirectory needs the Option "Play Only Whitelisted"
<img width="690" alt="Image" src="https://user-images.githubusercontent.com/62425593/132964064-2e9afa3d-4956-4c06-bcc1-85776b41db68.png">
