### ISSUE TITLE
AD_Server 

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#5652]
Hi
Choosing a place to advertise
Ads not working
Country City and Region
Can you check why?
![141414](https://user-images.githubusercontent.com/85537931/132116407-26c7dd26-ddaa-4e41-861c-c03ef0873dd5.jpg)
![1414143](https://user-images.githubusercontent.com/85537931/132116423-be756aa3-649e-441e-bca9-71a837e77b8d.jpg)

**Comment by DanielnetoDotCom** [comment]
Make sure you have installed all tables for this plugin 

![image](https://user-images.githubusercontent.com/18009293/132510084-9ae67e6b-4b20-4344-b9d0-caa4c8eba212.png)

**Comment by guymass** [comment]
OK I have installed those tables and the test shows success. We will continue testing to see how it works now. Much thanks!
