### ISSUE TITLE
webrtc via obs

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#5658]
Hi @DanielnetoDotCom , 

is it possible to push webrtc through obs instead of rtmp? if yes, how?

thank youuuu

**Comment by DanielnetoDotCom** [comment]
Hi

sorry but your question does not make sense for me

**Comment by jengajenga** [comment]
> Hi
> 
> sorry but your question does not make sense for me

@DanielnetoDotCom , let me clarify

right now i am using obs. i do rtmp://mystreamerserver.com/live/streamkey then convert rtmp video to hls.

can i do ws://mystreamerserver.com/live/streamkey? then convert the webrtc video to hls.

so that we offer two streaming options and you can choose to do rtmp-hls or webrtc-hls

**Comment by DanielnetoDotCom** [comment]
If you have the latest git pull version the WebRTC câmera should work

**Comment by jengajenga** [comment]
> If you have the latest git pull version the WebRTC câmera should work

Thanks @DanielnetoDotCom . i have the latest pull. 

i was trying to push a video from obs to my streamer using webrtc.  i read the wiki but didn't fully understand it.

do i put webrtc streamer url to obs and send or is it only working with camera?

**Comment by DanielnetoDotCom** [comment]
For now it only supports the public webrtc server . We still do not support you to use your own WebRTC server 

but if you are using OBS does not make sense use WebRTC. Sorry but again makes no sense

**Comment by jengajenga** [comment]
ok @DanielnetoDotCom .

thanks for the info and for making it clear.
