### ISSUE TITLE
Chat will not minimize on Mobile

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5659]
Android Phone. 
Chat does not minimize on mobile when clicking the down arrow. And top of chat. is under the top menu.
![Screenshot_20210907-162342_Chrome](https://user-images.githubusercontent.com/37937968/132406390-2ad3e89e-894e-4769-9e6e-64221c7f4dec.jpg)

**Comment by DanielnetoDotCom** [comment]
Is this the static right layout?

![image](https://user-images.githubusercontent.com/18009293/132510325-ae6da314-4488-47b9-af19-cd5719daf414.png)

what exact page is that?

**Comment by Lordblanca** [comment]
Yes it is 
![image](https://user-images.githubusercontent.com/37937968/132515225-55b02681-35c2-40b9-b883-e01162c30073.png)

**Comment by DanielnetoDotCom** [comment]
Did you clear the cache?
what exact page is that?

**Comment by Lordblanca** [comment]
Cache cleared. On my live stream. on any mobile device that I have tried the chat window fills the entire screen. And it does not minimize. when you click on the (X) to close out the chat it closes out everything and I have to go to the menu and get the live stream again

**Comment by Lordblanca** [comment]
please create an account and log in with your phone or tablet and you will see for yourself

**Comment by DanielnetoDotCom** [comment]
please reproduce it on demo site so I can check and direct access to try to find a fix

**Comment by Lordblanca** [comment]
Site is backed up. And an Image of the site is created. It is ok for you to do what needs to be done. back up site was not created by you. So it is different.. With the cloning program I can back up the your site to my back up?

**Comment by DanielnetoDotCom** [comment]
Is important to me to check it on demo site because I know exactly what is installed and what is modified, so I have more control over where to look for an issue.

**Comment by Lordblanca** [comment]
Since you built the lblivestream. I havn't used the lbcomsvr.com. and it is now not working properly. As I mentioned before. the main site is backed up and i can recover from an image. And I also did a snap shot so if anything goes wrong I can recover not a problem. Ive done it before. Don't worry. I would hold you responsible. I can always recover. You have my permission to make the changes

**Comment by Lordblanca** [comment]
rememeber the reason I had you build the lblivestream was because I could not figure out how to get the livestream to work with websocket

**Comment by DanielnetoDotCom** [comment]
To direct check it, I only do if it is a paid support or if the server is hosted with me. 

please use demo site.

also, it is not really an issue or but is an improvement or a misconfiguration.

**Comment by Lordblanca** [comment]
Wow this is because of your updates! All of this was fine until I did a pull form your updates. I should not have to pay because of your coding. If I screwed up I will pay. but all I'm doing is adding the updates that you provide. And like  I said I paid you to do the install. Because you did not want to give me the he proper coding for the websocket. I should not have to pay because of your coding.

**Comment by Lordblanca** [comment]
I paid for the chat2 and ran the plug in. Ever since I added the update to the chat. and did the pull (that your program recommend) this happened. I should not be held responsible for your plugins not functioning properly. Remember I pay for the plug ins they are not free. You are the programmer not me (us). Plus remember every time someone tells you about an issue with your program. You make it better for the next update. And if this chat problem was not an issue I would not have posted the problem.

**Comment by Lordblanca** [comment]
You don't get it . You made the installation... Here is the proof. Maybe you forgot. Here are copy of payment and receipt 
![Proof-Of-Payment-YOUPHPTUBE-Chase-bank](https://user-images.githubusercontent.com/37937968/132578837-1fb90bc2-a7a0-4710-8384-c871fcf200b5.png)
[Receipt for payment to daniel Santos Neto for YouPHPTube.pdf](https://github.com/WWBN/AVideo/files/7131569/Receipt.for.payment.to.daniel.Santos.Neto.for.YouPHPTube.pdf)

**Comment by Lordblanca** [comment]
And if it is a misconfiguration. Please show me exactly what it should look like.  So I can move. I got more plugins to buy and other things to verify with the program before I can go live.

**Comment by Lordblanca** [comment]
Just in

**Comment by Lordblanca** [comment]
You said to reporduce error on demo site. What demo site are you talking about

**Comment by DanielnetoDotCom** [comment]
https://demo.avideo.com/

**Comment by Lordblanca** [comment]
I had no Idea that even existed. I though you wanted me to use my old backup server.
