### ISSUE TITLE
After the PayPerView plugin selects Users Can Create PPV Plans, the new plan cannot be edited

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5661]
After the PayPerView plugin selects Users Can Create PPV Plans, the new plan cannot be edited
![image](https://user-images.githubusercontent.com/47063171/132446821-d2f6da2c-b80b-46c9-9e26-de253699ba71.png)
![image](https://user-images.githubusercontent.com/47063171/132446684-786d2f3b-ad92-4204-88e7-d66a66966f3b.png)
![image](https://user-images.githubusercontent.com/47063171/132446713-a7f0a859-98c3-4584-977d-8f4b16a82132.png)

**Comment by chenjian9885** [comment]
Existing PPV Plans cannot be displayed
![image](https://user-images.githubusercontent.com/47063171/132447441-f240e9da-90e1-4f18-957e-46ef1f7bf101.png)
![image](https://user-images.githubusercontent.com/47063171/132447465-6e42c4a6-b1c2-4f11-afb0-2a65363da947.png)

**Comment by DanielnetoDotCom** [comment]
Thanks, PayPerView version 5.3 may resolve that

**Comment by DanielnetoDotCom** [comment]
Also check the video owner for is movieclips user

the owner MUST create plans for himself because you checked the options `Users Can Create PPV Plans ` and `Users can set PPV plans on his videos `

![image](https://user-images.githubusercontent.com/18009293/132513289-05c5fb8d-2350-4635-8989-34585aad302a.png)

Or you can change the plan owner here

![image](https://user-images.githubusercontent.com/18009293/132513425-554ff7a5-c7e0-40a1-996c-21891ce51059.png)

![image](https://user-images.githubusercontent.com/18009293/132513480-adc3ad95-7493-420a-aad4-cb45a2a8fe1e.png)

**Comment by chenjian9885** [comment]
Hello
I’m very happy to be able to make the repair so soon, but the administrator should also have the right to modify and view the PPV Plans of the user’s video. Now the administrator does not know the PPV Plans of the user’s video.
![image](https://user-images.githubusercontent.com/47063171/132578180-da092cc7-7b97-4439-98a3-36ab861c5116.png)
Administrators cannot see PPV Plans of user videos
![image](https://user-images.githubusercontent.com/47063171/132578340-b4dff5e3-8c6e-4451-b808-d27e64822dd2.png)
![image](https://user-images.githubusercontent.com/47063171/132578413-964e53b3-dd8f-4596-8b14-4b0490943768.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I have sent a couple of updates to the PPV plugin, can you please update and try again?

**Comment by chenjian9885** [comment]
I updated it again, but I didn't see any changes.
![image](https://user-images.githubusercontent.com/47063171/132582700-83788dda-1be8-4ba8-9f3b-5f16e1f91009.png)
![image](https://user-images.githubusercontent.com/47063171/132582991-a461ef64-85ed-44b4-9f24-5433a14396de.png)

**Comment by chenjian9885** [comment]
After I git pull (AVideo), AD_Server plug-in ads are invalid, I think I should open a new topic

**Comment by DanielnetoDotCom** [comment]
I see now, you are complaining about admins that cannot see users PPV plans

it is because admins also have their own PPV plans.

I cannot let admins add other users plans on his videos, it may break the PPV

**Comment by chenjian9885** [comment]
If you can be an administrator, you won’t add other user plans randomly to his videos, but if the administrator has this permission, it can help users to use PPV plans, know whether the user’s video uses PPV plans, and whether they are affected by improper operation. User profitability.

**Comment by chenjian9885** [comment]
Does this show the number of PPV plans?
![image](https://user-images.githubusercontent.com/47063171/132590782-6d9e3b43-1b14-491f-afd8-c683f0120888.png)

**Comment by DanielnetoDotCom** [comment]
> If you can be an administrator, you won’t add other user plans randomly to his videos, but if the administrator has this permission, it can help users to use PPV plans, know whether the user’s video uses PPV plans, and whether they are affected by improper operation. User profitability.

I sent an update try the PPV version 5.6

**Comment by DanielnetoDotCom** [comment]
> Does this show the number of PPV plans?
> ![image](https://user-images.githubusercontent.com/47063171/132590782-6d9e3b43-1b14-491f-afd8-c683f0120888.png)

It supposes to show the total of users that signup for the PPV plan

**Comment by chenjian9885** [comment]
Great! Thank you Daniel Neto

**Comment by chenjian9885** [comment]
Great! Thank you Daniel Neto
