### ISSUE TITLE
My videos are not Playing 

### ISSUE THREAD

**Issue by Yoxed** [WWBN/AVideo#5662]
My video media play is not playing.
You can test it yourself here.
What can be causing this? Any assistance will be greatly appreciated.

[http://www.realmediatt.com/video/4/the-guilty-trailer-1-2021-movieclips-trailers?yptDeviceID=79835ec4-a6d1-4649-b1b1-6ac02f51cf84&page=1&channelName=contact](url)

**Comment by DanielnetoDotCom** [comment]
Did you use the encoder?

Looks like your video file does not exist

![image](https://user-images.githubusercontent.com/18009293/132511801-a3c089d7-4be6-49ef-a986-be533797446e.png)

check your logs

**Comment by Yoxed** [comment]
Okay fixed, turns out it was my blacblaze that was causing the error because i didn't set it up correctly.
