### ISSUE TITLE
The user group is enabled in the video, and users and tourists who are not in the user group cannot display thumbnails when watching the video

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5663]
The user group is enabled in the video, and users and tourists who are not in the user group cannot display thumbnails when watching the video
![image](https://user-images.githubusercontent.com/47063171/132463365-96c9c06b-8e33-4f13-8abf-9e630f981041.png)
![image](https://user-images.githubusercontent.com/47063171/132463542-bc9cc709-8f02-4361-85bf-67881d25ba22.png)

**Comment by DanielnetoDotCom** [comment]
Thanks, VideoThumbnails version 3.3 may fix that

**Comment by chenjian9885** [comment]
I have updated it and it runs well now, thank you Daniel Neto
