### ISSUE TITLE
AD_Server plugin ads are invalid after git pull

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5667]
AD_Server plugin ads are invalid after git pull
![image](https://user-images.githubusercontent.com/47063171/132584107-018e1dc6-6d8a-4934-b6ce-7c46ab0226ad.png)
![image](https://user-images.githubusercontent.com/47063171/132584030-dfb3db32-4202-45b9-b1fa-5862d6b190f0.png)

**Comment by DanielnetoDotCom** [comment]
what do you mean invalid?

**Comment by chenjian9885** [comment]
Hello:
Can you update the demo site (demo.avideo.com) (sudo git fetch --all && sudo git reset --hard origin/master
) So that I can reproduce the error at the demo station.

**Comment by DanielnetoDotCom** [comment]
I just did an update on demo site

**Comment by chenjian9885** [comment]
There are no ads in the video after the user logs in, but there are ads in the video in the user group.
![image](https://user-images.githubusercontent.com/47063171/132749205-7e26e198-fda2-474e-b999-eb77ed461bb2.png)
![image](https://user-images.githubusercontent.com/47063171/132749647-8d289c5c-ca7f-4ff1-b8eb-21f4382fdd5c.png)
![image](https://user-images.githubusercontent.com/47063171/132749743-5f199cb0-1eb4-41c6-95de-c7962971d3da.png)
![image](https://user-images.githubusercontent.com/47063171/132749907-40f4450d-f563-4f8c-acba-a699ed6ee62a.png)
![image](https://user-images.githubusercontent.com/47063171/132750004-9b31660f-412b-4cce-bfb0-ca05b39723fc.png)

**Comment by DanielnetoDotCom** [comment]
Do you mean there is no ads if the user is not logged?

try to clear the site cache and try again

**Comment by chenjian9885** [comment]
No, there are advertisements before the user logs in, and there are no advertisements after logging in, but it is only a normal user, not a video user.

**Comment by chenjian9885** [comment]
Reproduced the previous error, this is the feedback of the previous problem
https://github.com/WWBN/AVideo/issues/5553

**Comment by DanielnetoDotCom** [comment]
Thanks, PPV version 5.7 may resolve that

**Comment by chenjian9885** [comment]
For videos that are not in ppv plans, there are still no ads.
![image](https://user-images.githubusercontent.com/47063171/132809019-bbd09e09-2bf7-43ec-bcce-4d2051e82e8f.png)
![image](https://user-images.githubusercontent.com/47063171/132809094-c1a22dbe-b12d-466a-8e01-a47cafd6ffe2.png)
