### ISSUE TITLE
Why did someone take down my feed. Chat not working properly. Feed number 5659

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5668]
@DanielnetoDotCom What happen to feed 5659. We were discussing the chat not fitting properly in mobile and tablets
and you where telling me I had to pay to have you fix your install... What is going on.

**Comment by DanielnetoDotCom** [comment]
you closed that.

the install is correct, please read what I did wrote for you.

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/132593451-4f239490-ef27-4e36-a68c-382a8af9e868.png)

**Comment by DanielnetoDotCom** [comment]
If you still need help reopen that and reproduce it on demo site

**Comment by Lordblanca** [comment]
I did not close the thread. And you are the one that set up the web site.
And why do I have to put on my demo site. You are the one that set up my
lblivestream site. And I paid for it as well. What is going on?

**Comment by DanielnetoDotCom** [comment]
I am getting tired to keeping responding you the same thing
