### ISSUE TITLE
Hard to find live chat lock tab

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#5670]
I'm having a hard time viewing/popping out the live chat feature.
It seems that the buttons are hidden under the top banner, and hovering near the top only flashes them on the screen making them impossible to click,

![image](https://user-images.githubusercontent.com/66537018/132612029-3dc5e211-7b5c-4a6b-b8b5-16faad911114.png)

**Comment by DanielnetoDotCom** [comment]
what layout parameter are you using?

what device is that?

**Comment by fakeologist** [comment]
bottom right, brave/chrome browser.

**Comment by DanielnetoDotCom** [comment]
can you please use this option?

![image](https://user-images.githubusercontent.com/18009293/132710400-ae1ad148-235b-424e-aa9a-5bb402a8a533.png)

**Comment by fakeologist** [comment]
will do. will report back later.
Is there a permanent html link to the chat, or is it dynamic?

**Comment by DanielnetoDotCom** [comment]
Usually, this gives you a good link

![image](https://user-images.githubusercontent.com/18009293/132714742-855e13f7-c796-4557-ac2d-3988a9f09e35.png)

**Comment by fakeologist** [comment]
I use that, but does that url change each session? is it dynamic?

**Comment by DanielnetoDotCom** [comment]
I am pretty sure it does not change
