### ISSUE TITLE
Make Top Categories Display Videos in Random order

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5675]
It would be more entertaining for when users click on a category at the top to be presented a randomized order instead of the newest to oldest.

Reason why is because if users are seeking some entertainment they want to presented with a wide range of things related to the specific category.

Currently when users click on a category they will sometimes see blocks and blocks of 1 thing like a tv series that was previously uploaded or someone backing up their channel.   for example:

![download](https://user-images.githubusercontent.com/39392449/132845271-62f03349-c4dd-47c7-ae17-b57b61fb9812.png)

and thus when people see something like this they end up just losing interest in your website if it is not a tv show or something they really love.

I would still keep some kind of Sorting option at the top that way if the user wants to see newest to oldest order they could easily just select it.

**Comment by DanielnetoDotCom** [comment]
maybe the best option is to sort it by the latest uploaded video instead of a random

**Comment by JoshWho** [comment]
it makes looking for stuff to watch not too likable.

**Comment by JoshWho** [comment]
I can just see in my analytics reports when users browse categories they do not stay long. I am trying to bring life to all the old videos also that are being buried. 

I want to figure out a way to make randomized Programs of every category and have them live stream.

**Comment by walt93** [comment]
One thing I've tried, although the OBS interface is a little clunky... Set up a Live, and then from a separate machine you can set up any playlist you want using a VLC Playlist data source in OBS.
