### ISSUE TITLE
Streaming Issue after adding SSL

### ISSUE THREAD

**Issue by Yoxed** [WWBN/AVideo#5682]
The Nginx stat Server was working good on http. now that i moved over to https I don't see the stats and my stream is not going Live. 
I am providing imgur links that are images of my script etc.

Server --> https://imgur.com/WgD6yDq

http --> https://imgur.com/LZCPoXN

Plugin form --> https://imgur.com/ypjcHME

My Logs:
` [10-Sep-2021 19:53:47 America/La_Paz] AVideoLog::DEBUG: Live::createStatsCache {"bytes":155,"cachefile":"\/var\/www\/html\/myMySQLUser\/videos\/cache\/YPTObjectCache\/getstats\/getstatsnotifications\/www.mysite.com\/https\/admin_412a200b3fd0a96d74f70a61831dc95f\/56efaca3766a2a3ccfc4fbff9e6307a2.cache"} SCRIPT_NAME: /plugin/Live/stats.json.php
 [10-Sep-2021 19:53:47 America/La_Paz] PHP Notice:  Undefined variable: array in path/to/my/streamer/site/plugin/LiveLinks/LiveLinks.php on line 154`

**Comment by Yoxed** [comment]
Please help with this issue as soon as you possibly can.

**Comment by DanielnetoDotCom** [comment]
Sorry there is not much we can help, you must google for that

Cloudflare is strongly NOT recommended to use for multiple reasons, one of them is your RTMP that will not work.

how to configure the Nginx SSL without Cloudflare you MUST use google.

I recommend you yo use lets encrypt for your apache and Nginx and disable the Cloudflare proxy.

![image](https://user-images.githubusercontent.com/18009293/132955849-3d193c2e-d456-42a0-b813-3f49ad399dae.png)

**Comment by Yoxed** [comment]
Okay i was using lets encrypt at, i will use it again. But is everything configured correctly?

**Comment by Yoxed** [comment]
Okay i am using letsencrypt and this is what it says 

`[2021-09-12 15:10:06] Time Elapsed: 0.00004 seconds - Starting try to get URL https://realmediatt.com:8443/stat
[2021-09-12 15:10:06] Time Elapsed: 0.00012 seconds - url_get_contents start timeout=2

Warning: file_get_contents(https://realmediatt.com:8443/stat): failed to open stream: Connection refused in /var/www/html/realmediatt/plugin/Live/test.php on line 53
[2021-09-12 15:10:06] Time Elapsed: 0.00044 seconds - file_get_contents::
[2021-09-12 15:10:06] Time Elapsed: 0.00045 seconds - file_get_contents fail return an empty content
[2021-09-12 15:10:06] Time Elapsed: 0.00045 seconds - FAIL
[2021-09-12 15:10:06] Time Elapsed: 0.00045 seconds - Finish try to get URL`

**Comment by Yoxed** [comment]
I did every thing you said to do here --> https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server
I followed all the instructions correctly. 
I sent you images of my config file above, is everything in there correct?

**Comment by Yoxed** [comment]
Okay i managed to fix it. I changed
Listen 8080; to Listen 8443 ssl;
