### ISSUE TITLE
When userMustBeLoggedIn is turned on, the footer of the login page is abnormal

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5683]
When userMustBeLoggedIn is turned on, the footer of the login page is abnormal
![iShot2021-09-12 23 25 36](https://user-images.githubusercontent.com/47063171/132993484-5fa7ddc3-b6b8-4bc2-af61-ad3790dedf21.png)
![iShot2021-09-12 23 26 25](https://user-images.githubusercontent.com/47063171/132993486-b811adca-30e2-4186-8873-09701770dd64.png)

**Comment by DanielnetoDotCom** [comment]
Thanks, I just sent an update that may resolve that

**Comment by chenjian9885** [comment]
Hello, I just updated my website, but the footer of my homepage seems to be abnormal, the footer is floating
![image](https://user-images.githubusercontent.com/47063171/133134140-27798b53-23a3-4275-b6c2-d3106ebdee2d.png)

**Comment by DanielnetoDotCom** [comment]
Please try now

**Comment by chenjian9885** [comment]
Great thanks
