### ISSUE TITLE
Sharing a video

### ISSUE THREAD

**Issue by Luqsonic** [WWBN/AVideo#5684]
Hello please i a beginner so my explanation may not make alot of sense but help me out.

Is there a way i can share a link of an embeded video on telegram and it plays from telegram directly without leaving the app

For example if i share a like from YouTube,vimeo,twitch i can watch them without leaving telegram. See attached 
![20210912_195208](https://user-images.githubusercontent.com/62737177/132996084-d0142da3-14e3-4470-899c-7ab11dda4ccf.jpg)

**Comment by DanielnetoDotCom** [comment]
I made some research and I checked this on the demo site

![image](https://user-images.githubusercontent.com/18009293/133131105-e9e14fb1-999e-49f4-b7f5-f49590e16483.png)

Once I disabled it an mp4 link was generated

![image](https://user-images.githubusercontent.com/18009293/133131211-7fd2fc8b-892d-48ae-ab5e-b1f5471b3045.png)

But still not showing, 

Regarding this link https://telegram.org/blog/link-preview, 

this feature is only available for some sites. I guess this is something that must be done on the telegram side.

**Comment by Luqsonic** [comment]
Alright Thanks alot
