### ISSUE TITLE
The uploaded file exceeds the upload_max_filesize directive in php.ini

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#5687]
I uploaded video file from AVideo-Encoder.
Next error messages displayed

ERROR The uploaded file exceeds the upload_max_filesize directive in php.ini

Please tell me which parameter in php.ini to change to change the size of the uploaded file.

**Comment by chenjian9885** [comment]
The error has been stated very clearly, modify upload_max_filesize in the php.ini configuration file
For example: upload_max_filesize = 5000M
![image](https://user-images.githubusercontent.com/47063171/133100574-d2336e7d-cbc9-40c0-a3ea-c0bec8f7f7f5.png)

**Comment by chenjian9885** [comment]
Find the location of the php.ini configuration file and execute the following code
php -i | grep php.ini
or
php --ini

**Comment by redilee** [comment]
I have the same issue after recent upgrade to PHP Version 7.4.3.
I've been through every php.ini file on the server, set them all to 6000M, and still get that error. 
Some documentation I've found indicates that php 7.4 doesn't use php.ini files, but only user.ini. 
Anybody know anything about that?

**Comment by chenjian9885** [comment]
AVideo requires the configuration of php.ini: max_execution_time, memory_limit, post_max_size, upload_max_filesize, the parameters can be modified according to your own needs, you can check the official document: https://www.php.net/manual/en/ini.core.php
It should be noted that for uploading large files, the value of post_max_size must be greater than upload_max_filesize
