### ISSUE TITLE
Set the ppv plan to report an error

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5691]
Set the ppv plan to report an error
![image](https://user-images.githubusercontent.com/47063171/133239440-f1cc1d19-8d09-4012-bcc8-c84f61e89360.png)
![image](https://user-images.githubusercontent.com/47063171/133239689-aea1c5f1-cd2f-4007-a256-93e3d4f3e70d.png)
![image](https://user-images.githubusercontent.com/47063171/133239755-d97f4cdf-8729-4c29-87f4-3f4f0ca64a15.png)

**Comment by chenjian9885** [comment]
Please log in with the (movieclips) user to check

**Comment by DanielnetoDotCom** [comment]
thanks for notice that, I just release PPV version 5.8 that fix it

**Comment by chenjian9885** [comment]
Great thanks
