### ISSUE TITLE
Set 4k as default

### ISSUE THREAD

**Issue by pcprofi** [WWBN/AVideo#5693]
Hi @all,

i have the VideoResolutionSwitcher installed.

Is it possible to set 4k as default? In the backend i can only set HD for  720p ;(

Maybe it is also possible to set it in the admin-page?

Thanks for reply!

**Comment by DanielnetoDotCom** [comment]
Hi, first you MUST have 4K videos encoded. do you have any?

if you are using HLS the resolution is automatic depending on the bandwidth available.

On MP4 currently we do not have an option to force play 4K videos , I am pretty sure the default is 720p than the user can switch

**Comment by pcprofi** [comment]
Thank you for your fast reply!

Yes, i have a 4k .mp4 video and 2160p is checked on by the decoder.
"I am pretty sure the default is 720p then the user can switch" -> absolutly correct! Default is 720p and i can manual switch on 4k.  

So, to force play 4k-Videos I need the HLS-Plugin in combination with the switcher?
If yes, what would be the right file-format of the video to upload, when i export it with DaVinci Resolve?

**Comment by DanielnetoDotCom** [comment]
No, currently there is no option to force 4K, also I do not think it is a good idea.

4K requires a lot of bandwidth, maybe your clients do not have enough, so the video will lag a lot.

also even if your clients have a good connection but you have many clients watching 4K videos at the same time your server may not have enough bandwidth.

definitely, the best option is the HLS where the resolution will automatically switch depending on the bandwidth available. it will play your 4k videos softly if there is enough bandwidth between your server and clients. if there is not it will automatically downgrade
