### ISSUE TITLE
HLS with S3 Storage

### ISSUE THREAD

**Issue by aolvictim** [WWBN/AVideo#5694]
**Describe the question**
I am curious on why we cannot make HLS to work with S3 storage option. Can't we simply serve the `index.m3u8` the same way to server those MP4 files? Is it mainly due to the download protection and encryption feature (where we don't want to expose the key file)?

**Comment by DanielnetoDotCom** [comment]
Hi, HLS requires to transfer hundreds of files for a single video.

currently, I have no way to guarantee I can transfer them all without fail
