### ISSUE TITLE
How to set the user to display the video after logging in

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5696]
Hello: Daniel Neto, how can I set up a video so that the user can display the video after logging in?

**Comment by DanielnetoDotCom** [comment]
Hi

try to use this ...

![image](https://user-images.githubusercontent.com/18009293/133434907-6859485f-47c8-4ff5-ae7b-c4a9b773a9ab.png)

**Comment by chenjian9885** [comment]
No, this just jumps to the page after logging in. What I need is that some videos are not listed before logging in (unpublished), and videos are listed after logging in (public).

**Comment by chenjian9885** [comment]
No, this just jumps to the page after logging in. What I need is that some videos are not listed before logging in (unpublished), and videos are listed after logging in (public).

**Comment by chenjian9885** [comment]
No, this just jumps to the page after logging in. What I need is that some videos are not listed before logging in (unpublished), and videos are listed after logging in (public).

**Comment by DanielnetoDotCom** [comment]
I guess we do not have that option

**Comment by chenjian9885** [comment]
All right
