### ISSUE TITLE
Request support for translation

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5697]
Request classification translation support, thank you!
![image](https://user-images.githubusercontent.com/47063171/133443422-3d009924-b693-4694-b551-0f1e7a671d40.png)
![image](https://user-images.githubusercontent.com/47063171/133443490-a55a8a94-4721-436f-8275-be21a7a66249.png)

**Comment by DanielnetoDotCom** [comment]
You can add this to your translation file.

probably `$['Film & Animation'] = '....';`

**Comment by chenjian9885** [comment]
I have already added it, but the translation for this place does not take effect.
![image](https://user-images.githubusercontent.com/47063171/133601203-84fb9add-1d12-4fbf-a14e-0d119dba0154.png)
![image](https://user-images.githubusercontent.com/47063171/133601244-77a2fd00-e105-4d9f-9cd6-5502ad424730.png)

**Comment by DanielnetoDotCom** [comment]
Did you clear the cache after add it?

**Comment by chenjian9885** [comment]
Yes, I am pretty sure that I cleared the cache.

**Comment by DanielnetoDotCom** [comment]
Ok, I found something. please update

**Comment by chenjian9885** [comment]
That's great, thank you!
