### ISSUE TITLE
Just appear Under Maintenance while using the site

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5707]
**Describe the bug**
Just appeared Under Maintenance and i cannot login yo admin or any place at all is so weird. 

![Screenshot_20210917-105258_Chrome](https://user-images.githubusercontent.com/63973045/133804130-34596d10-a300-4997-84d2-135c2556aea8.jpg)

So i want to know what i can do since i cannot log in or anything i hate with this happened out of the blue.

**Comment by DanielnetoDotCom** [comment]
check the log files

if you have the FTP plugin manually delete it from the plugins folder, after that your site may be back

 then download the new version and upload

**Comment by LATINMIXMASTERS** [comment]
Can you tell me how i get to the plugin folder and also how can get logs since i am not able to login.

**Comment by LATINMIXMASTERS** [comment]
Dont worry i just a did a Git Pull and it fixed the issue.
