### ISSUE TITLE
How to authorize users to open Only Paid Users Can see

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5708]
How to authorize users to open Only Paid Users Can see
![image](https://user-images.githubusercontent.com/47063171/133828962-77222c62-eae8-409f-8ca1-b489668bc555.png)

**Comment by DanielnetoDotCom** [comment]
Sorry I am not understanding your question

**Comment by chenjian9885** [comment]
Ordinary users cannot take effect when setting the video ppv plan, and need to turn on (Only Paid Users Can see) to take effect
![image](https://user-images.githubusercontent.com/47063171/133868289-c99372c7-6b7d-40d8-8b99-efa579b69694.png)
![image](https://user-images.githubusercontent.com/47063171/133868321-276b9f99-f895-46b8-8972-5fe1cf335c33.png)
Still can play normally
![image](https://user-images.githubusercontent.com/47063171/133868427-d80dea95-ccaf-49e0-b0c6-45566e1dd4c7.png)

**Comment by chenjian9885** [comment]
Turn on (Only Paid Users Can see), and the ppv plan will take effect.
![image](https://user-images.githubusercontent.com/47063171/133868732-5d1a5d22-6f9f-4970-80fb-08274e57b2c5.png)
![image](https://user-images.githubusercontent.com/47063171/133868756-7f6afb13-29fc-4f0d-a61c-d504208f5946.png)

**Comment by chenjian9885** [comment]
But ordinary users cannot turn on the (Only Paid Users Can see) button

**Comment by chenjian9885** [comment]
Request a fix, users cannot add ppv plan to the video

**Comment by DanielnetoDotCom** [comment]
Make sure you have this

$advancedCustomUser->userCanNotChangeUserGroup = unchecked
advancedCustom->paidOnlyUsersTellWhatVideoIs = checked

**Comment by chenjian9885** [comment]
thank you very much

**Comment by chenjian9885** [comment]
Can now be displayed
