### ISSUE TITLE
HELP! All site admin logins failing "Your user or password is wrong!". I think I've been hacked.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5711]
**Describe the bug**
Both my logins with admin access aren't working. My other logins without admin access aren't working either. I can't log in to my server via AVideo's web interface at all.  It appears I was just hacked…

**To Reproduce**
...

**Expected behavior**
to be able to login

Where on the server do I go to fix my login?

**Comment by DanielnetoDotCom** [comment]
I am pretty sure you were not hacked and your disk is full

if you need to reset the password follow this.  https://github.com/WWBN/AVideo/wiki/Reset-a-Password#how-to-reset-a-password-with-ssh

**Comment by walt93** [comment]
Yes. I just figured out that running backup filled my disk. Where do I clear the backup files?

**Comment by walt93** [comment]
Ok found it. Root cause identified.
