### ISSUE TITLE
Size files no displayed

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#5717]
**Describe the bug**
Dear guys, I upgraded AVIDEO to version 11.3.
When I went to manage the files already stored, I verified that the size of the files were no longer displayed, they were all zeroed. I would like to know if this happened due to the update.
How can I solve this problem?

**Screenshots**
![image](https://user-images.githubusercontent.com/37880073/133906002-44c77efb-467c-46a9-9c62-4b3cb8da2d58.png)

**Comment by gbrn** [comment]
Dear, complementing the previous subject. I found that the disk quantity is also displayed wrong:

![image](https://user-images.githubusercontent.com/37880073/133948582-37a8a6d9-18a6-432f-885e-5fda37764d28.png)

**Comment by DanielnetoDotCom** [comment]
what type of file is that?

looks like you are not using the encoder so we could not get the resolution.

and regarding the filesize it is strange, please share your logs. I guess you have a misconfiguration

**Comment by gbrn** [comment]
Hi Daniel,
The problem is not just one file. I have 20 files, these files had all the information normally, after the 11.3 update they stopped displaying the information.
A detail, all files are running/viewing normally.

See attached log:
[log setembro.txt](https://github.com/WWBN/AVideo/files/7207063/log.setembro.txt)

**Comment by gbrn** [comment]
Hi Daniel,
This problem is persistent. I've already tried to update to the latest version, but I haven't changed anything.
I'm the only one having this problem?

**Comment by DanielnetoDotCom** [comment]
can you please run this command?


`du -sb path/to/my/streamer/site/videos/_YPTuniqid_60e9d2d7509663.58065663/`

make sure you replace the `path/to/my/streamer/site/videos/` with your videos folder path

share a screenshot of the results

**Comment by gbrn** [comment]
Hi Daniel,
I executed the command:
du -sb public_html/cnetv/_beta/videos/_YPTuniqid_60e9d2d7509663.58065663/

Result: 
1034052870      public_html/cnetv/_beta/videos/_YPTuniqid_60e9d2d7509663.58065663/

**Comment by DanielnetoDotCom** [comment]
I am pretty sure the problem is because you are NOT using Ubuntu

**Comment by gbrn** [comment]
Hi Daniel,

The server configuration is this:

Plataforma: CentOS 5.6 - 64 bits
Versão PHP:  7.3

I inform you again that this error only started to show after upgrading to 11.3

Is there a test I should do?
I am available for any solution.

**Comment by DanielnetoDotCom** [comment]
Sorry, I can only support Ubuntu

**Comment by DanielnetoDotCom** [comment]
Sorry for the late reply.

can you please check your log when you click on this button?
