### ISSUE TITLE
Live Users Color Change

### ISSUE THREAD

**Issue by Yoxed** [WWBN/AVideo#5722]
I want to change the color of the live users, I can’t see so as others can’t. It’s hard to view it. It's currently green, maybe I can make it red? It's just really hard to see how many people are watching the Livestream.

**Comment by DanielnetoDotCom** [comment]
If you know how to work with CSS you can use custom CSS.

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript

**Comment by Yoxed** [comment]
I am familiar with the css but i was looking for the css script in the files and i couldn't find it. Can you tell me exactly where it is?

**Comment by DanielnetoDotCom** [comment]
I also do not know where is it, but is possible to inspect and find out if you know how to deal with CSS

**Comment by Yoxed** [comment]
I already did the inspect and changed it but I want to change it permanently in the files directly.

**Comment by DanielnetoDotCom** [comment]
si if you figure it out, add the CSS permanently here https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript

**Comment by Yoxed** [comment]
Thank you, I was able to change it with your help.
