### ISSUE TITLE
Video playback page cannot recommend group videos

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5725]
The video playback page cannot recommend group videos, and all videos on the site have been added to the user group.
![image](https://user-images.githubusercontent.com/47063171/133990828-85394620-1b46-4b7d-b867-ae2530a5a74c.png)
![image](https://user-images.githubusercontent.com/47063171/133990891-bfa97073-cc55-4aa4-98ab-72530ecd856e.png)

**Comment by DanielnetoDotCom** [comment]
Can you reproduce it on demo site?

**Comment by chenjian9885** [comment]
Thank you Daniel Neto
I just updated the website and it can now be displayed normally.
