### ISSUE TITLE
cant login as root, initial setup

### ISSUE THREAD

**Issue by Techoweenie216** [WWBN/AVideo#5727]
Followed all the install instructions, got to the point of doing the install from the web interface but I get an error saying that root@localhost  cannot connect (error1698). This is a clean install of the OS (Ubuntu20.04) on the server. I've tried two times trying fresh installs and get the same message.

I have  double and triple checked my passwords are correct. Anyone have any ideas how I can fix?

**Comment by DanielnetoDotCom** [comment]
Looks like is something on your MySQL

check MySQL logs

**Comment by Techoweenie216** [comment]
I did. I can login on the sql server as root on the server. I just cant login from the install web page

**Comment by DanielnetoDotCom** [comment]
MUST be MySQL NOT SQL server

at this point, I cannot help you.

again check the MySQL logs also apache logs

**Comment by Techoweenie216** [comment]
sorry I thought it would be obvious I was using mysql since I followed the install instructions. 
the apache logs give a 200 status on the post
the error log for mysql doesn't show anything related to this

**Comment by DanielnetoDotCom** [comment]
I guess you did not check into the error log, you checked the access log.

but without logs, I cannot help you.

**Comment by Techoweenie216** [comment]
this is the only thing in the error log

[Fri Sep 24 00:21:14.006924 2021] [php7:notice] [pid 57357] [client 192.168.10.252:25320] Installation: 9 {"webSiteRootURL":"http:\\/\\/192.168.10.111\\/AVideo\\/","systemRootPath":"\\/var\\/www\\/html\\/AVideo\\/","webSiteTitle":"TinFoilHat","databaseHost":"localhost","databasePort":"33060","databaseUser":"root","databasePass":"testpassword","databaseName":"aVideo","mainLanguage":"us","systemAdminPass":"testpass","contactEmail":"testemail@nowhere.com","createTables":"2"}, referer: http://192.168.10.111/AVideo/install/index.php

[Fri Sep 24 00:21:14.007003 2021] [php7:notice] [pid 57357] [client 192.168.10.252:25320] Installation: 20, referer: http://192.168.10.111/AVideo/install/index.php

**Comment by DanielnetoDotCom** [comment]
Definitely, you need to find someone to help you with your server installation (not avideo installation)

I cannot confirm if your MySQL credentials are correct or if it is installed properly.

**Comment by Techoweenie216** [comment]
The SQL creds. are correct, as I stated I can login from a terminal session to the root SQL account so I know its working. I got no errors installing the server OS and I find it hard to believe that there would be a problem with an OS install 2 different times. If I have time again this week I will install a fresh new OS again.

**Comment by DanielnetoDotCom** [comment]
try this


Create a MySQL user like this 

`sudo mysql -u root -e "USE mysql;CREATE USER 'youphptube'@'localhost' IDENTIFIED BY 'youphptube';GRANT ALL PRIVILEGES ON *.* TO 'youphptube'@'localhost'; FLUSH PRIVILEGES; " `

and then use your MySQL credentials like this

user: youphptube
pass: youphptube


if does not work please specify what Ubuntu, MySQL and PHP version you are using
