### ISSUE TITLE
Offline While Live

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#5728]
Hi @DanielnetoDotCom 

I am getting this issue on my site and also on the app

![offline_while_live](https://user-images.githubusercontent.com/65451390/134245779-751324eb-3b16-4338-8615-81fd8e656ffe.png)

Socket is working and running fine. It will only come back ONLINE after refreshing the page.

Is there a fix for this?

Thanks

**Comment by DanielnetoDotCom** [comment]
I am not sure. 

are you running the latest git pull?

is your socket running fine?

**Comment by jengajenga** [comment]
> I am not sure.
> 
> are you running the latest git pull?
> 
> is your socket running fine?

Yes. Socket  is running fine and i am running the latest git.

![offline_while_live_2](https://user-images.githubusercontent.com/65451390/134477913-7e6e314b-a4f9-4b90-8cf9-c477fbbab522.png)

It  is still happening

**Comment by DanielnetoDotCom** [comment]
I am working on a few updates for the live what includes the online notification, please give me this week to finish the update and check if the error persists

**Comment by jengajenga** [comment]
> I am working on a few updates for the live what includes the online notification, please give me this week to finish the update and check if the error persists

alright @DanielnetoDotCom . thank you very much.
