### ISSUE TITLE
email notifications stopped

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#5740]
In the last few days, email notifications have stopped. Was anything changed with last few updates?

**Comment by DanielnetoDotCom** [comment]
No,

but check your log file

**Comment by fakeologist** [comment]
please remind me where that is

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/134708946-6c7b05ab-c136-42ff-8e03-289cfe1f0c06.png)

**Comment by fakeologist** [comment]
can't see anything in log file about email

**Comment by DanielnetoDotCom** [comment]
Hi, I just tested your site email and it seems to be fine.

maybe the email is going to the spam folder.

![image](https://user-images.githubusercontent.com/18009293/134769550-1c0410d1-b7f2-4890-956b-f0c9a3bf6742.png)

I am not sure what are you using to send the email, but if there is a problem it may be on the email provider side.

**Comment by DanielnetoDotCom** [comment]
Also, I just used your share form to email the page to myself and it seems to be working, and I could confirm I received the email....

![image](https://user-images.githubusercontent.com/18009293/134769625-f1fe5a0a-baf0-4b06-b0fa-015e963d2804.png)

what type of email are you missing?

again, please check the spam folder

**Comment by fakeologist** [comment]
tested notify plugin, got this. ![Screenshot_20210925-083729_Brave - Nightly.jpg](https://user-images.githubusercontent.com/66537018/134771905-9189a890-d64f-42e3-81e3-20398160fc58.jpg)

**Comment by DanielnetoDotCom** [comment]
This test button is for onesignal only https://github.com/WWBN/AVideo/wiki/Notifications-Plugin#onesignal

**Comment by fakeologist** [comment]
please check my log files no emails even in spam

**Comment by DanielnetoDotCom** [comment]
what type of email are you missing?

new videos? live online?

**Comment by fakeologist** [comment]
all notification emails

**Comment by DanielnetoDotCom** [comment]
I just sent you some updates, can you please check if you are receiving notifications now?

Also, I just notice the plugin will not notify a new video if the video is not active.

also will not notify embed videos

**Comment by fakeologist** [comment]
Update worked. Thanks.
