### ISSUE TITLE
Serious Security Issue 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5743]
A few different times when I am logged into my account and am scrolling through the site it randomly gives me full access to another user account by just giving me the page when I am browsing my site. Here is a random user that it just logged me into while I was logged into my personal administration account. 
![20210925_003127](https://user-images.githubusercontent.com/70327833/134761515-d900ba9e-055e-40fc-b6bb-d7aa609d4a48.jpg)
![20210925_003141](https://user-images.githubusercontent.com/70327833/134761517-817e27e3-e9be-42c1-8144-37fb8622684e.jpg)

@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Is your site on the latest git pull? about a month ago I fixed something that may cause that.

how are your cache parameters? can you please screenshot it?
