### ISSUE TITLE
ROKU Feed error

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#5744]
Dear,

I'm studying building an application for the ROKU system. I verified that AVIDEO has FEED compatibility for the ROKU system. But inserting the link, ROKU has an error, not detecting JSON and only detecting MRSS.
Have you guys checked this problem? Do you know what could be happening? Below is screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/37880073/134791935-548ff39c-0d52-4883-b125-7fbc1343b89b.png)

**Comment by gbrn** [comment]
After processing the link in the ROKU system, this invalid format error is displayed:

"The feed format is invalid. We are unable to parse it.: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 20; The processing instruction target matching "[xX][mM][lL]" is not allowed."

![image](https://user-images.githubusercontent.com/37880073/134792856-c6edef6c-f547-44b5-baad-4a6585c9cfa4.png)

**Comment by DanielnetoDotCom** [comment]
Hi

for this http://www.cnetv.com.br/feed/ I have no idea why you have an error on the first row

but for Roku you should use this URL http://www.cnetv.com.br/roku.json

**Comment by gbrn** [comment]
Daniel,

In my tests of Feed for Roku. I verified that the new updates are not in the Feed.
Added a new file and it wasn't listed on Roku.
I checked the URL and the new post isn't really there:
http://www.cnetv.com.br/roku.json

Another detail, when I access Roku's administrative, displays the following error message:
"O servidor retornou um código de status não 200 - (301)."

![image](https://user-images.githubusercontent.com/37880073/136668307-2651f368-d389-480d-8d96-1938a452ab48.png)

**Comment by gbrn** [comment]
So, I didn't do any redirection is the platform's original configuration.
I am using "http://www.cnetv.com.br/roku.json" because it was your instruction.
I changed the configuration on Roku's website and it looks like it was accepted.

I know how to change the htaccess, but I don't know which line is the right one, could you tell me?

**Comment by gbrn** [comment]
Hi Daniel,

I still don't understand how the Feed update works.
It seems to me that there is some scheduling routine that updates after some time, is that right?
The feed on Roku is working, but it takes a while to update, something like 24 hours later.

**Comment by gbrn** [comment]
Hi Daniel,
I verified that the inactive videos are still showing on the ROKU list. How can this be resolved?

**Comment by DanielnetoDotCom** [comment]
I just double check and it does not suppose to show inactive videos. but the Roku mrss uses a cache. so if you inactivate it after the cache was generated, you may need to clear the cache to generate a new json.

on the Roku side, the feed is not online and is not requested on every app opened. they update the feed after some time

**Comment by gbrn** [comment]
I did a test, I inactivated a video and after 24 hours, the video was still available for viewing. Without me cleaning the cache.

In addition to this issue of the cache taking a long time to update, there is the issue of the video being fully available to view even if it is not activated.
