### ISSUE TITLE
Reminder #5632 is still making a significant % of my sites videos inaccessible

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5747]
**Describe the bug**
I'm always frustrated when I spend hours uploading, collating, sorting, tagging videos only to find they are inaccessible to my users.

**To Reproduce**
https://github.com/WWBN/AVideo/issues/5632

**Comment by DanielnetoDotCom** [comment]
I do not get it, is it now loading the new video on the infinite scroll or the video is not loading at all?

**Comment by walt93** [comment]
There is no change in the behavior. This page should scroll through >180 videos; it shows 36. https://conspyre.tv/cat/parapsychology

**Comment by DanielnetoDotCom** [comment]
Very strange.

I cannot see any JS error or the infinite scroll

are you up to date with a git pull from yesterday?

**Comment by walt93** [comment]
Pulled. Fixed. 😎🙏 Please also close #5632 of which this is a duplicate. I will check the remaining and report again if any issues.
