### ISSUE TITLE
Series Thumbnails Broken

### ISSUE THREAD

**Issue by stevezemlicka** [WWBN/AVideo#5752]
I have just started experimenting with and setting up Playlists/Series to help group videos.  I notice that when looking at the Series (called "Programs" as was suggested by the interface if I recall), I notice that none of the video thumbnails works.  Every once-in-awhile, I will see 3 or so thumbnails but the rest are the yellow play button and most of the time all are just the yellow play button.

Thumnails for the videos (including the ones in the Series) work everywhere else.

Is there any known issues with thumbnails working for videos in a series?  Does anyone else have this issue?

**Comment by DanielnetoDotCom** [comment]
can you please screenshot what you mean?

**Comment by stevezemlicka** [comment]
![thumb-issue](https://user-images.githubusercontent.com/36158719/134975497-1a3f83f0-0cb0-4f23-b0c2-f48cced5337c.jpg)

Screenshot attached.  I have noticed that recently updated thumbnails do seem to show up for some time but eventually stop working.  Still unsure how long that takes but here's a screenshot showing videos updated today showing ok but older ones from a few days ago broken:
![thumb-issue2](https://user-images.githubusercontent.com/36158719/134975807-05ca6070-cfae-4b23-8444-785f5dff98dd.jpg)

**Comment by stevezemlicka** [comment]
I did a git pull as of about 3 or 4 days ago so I should be relatively up-to-date as of last week.  All of these series/playlists/videos were created/added after that pull

**Comment by DanielnetoDotCom** [comment]
can you please reproduce it on demo site?

**Comment by stevezemlicka** [comment]
I cannot seem to reproduce on the demo site

**Comment by stevezemlicka** [comment]
That's understandable.  Since this is a personal site, unfortunately the value in fixing this is probably lower than your hourly rate.  However, perhaps I can continue on this thread so that as I figure out what's going on, others may benefit (and perhaps contribute).

I've done a bit more digging and I suspect this has to do with a residual config somewhere.  While I was originally building this, I was debating whether to call it tube.domain.tld or video.domain.tld.  This is confirmed by the fact that I actually had both in my nginx config though I ultimately chose tube.

Somehow there seems to still be a config that is referencing video.domain.tld for these images...but it seems only for these images on this page.

I'm currently doing a grep for the video.domain.tld in the AVideo folder on the server and there are tons of results.  I'll need to sift through the results to see if one is a line of config.  If anyone has any ideas on what config would just affect these images, please let me know.

**Comment by DanielnetoDotCom** [comment]
If you cannot edit with sudo I suspect you are not using Ubuntu.

if sudo cannot edit, sorry but I cannot help you.

**Comment by stevezemlicka** [comment]
Well this ended up being totally my fault and due to my config.  I am running Debian rather than Ubuntu but the reason sudo/root was not working on this file was because I have it NFS mounted to my SAN.

So, ultimately this was a legacy config left over from my setup which is located at /var/www/AVideo/videos/configuration.php.  I had to change the else section of the $global['webSiteRootURL'] to the correct publicly accessible root URL.

All my problems with editing that file were likely due to NFS and permissions relating to that.  Had this location been on the local file system, I suspect sudo would have been sufficient to make the change.
