### ISSUE TITLE
SEO Google

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#5755]
Dear, 
I verify that the information presented on my site is incorrect or unformatted.
How do I correct the information that Google searches on my site.
How do I find the site map link to provide to Google?

Check out the attached image:

**Screenshots**
![image](https://user-images.githubusercontent.com/37880073/135180026-8364d38a-a8cc-4cdc-ba6b-0bbaafbee177.png)

**Comment by DanielnetoDotCom** [comment]
To see the sitemap just add sitemap.xml into your site URL

for example https://demo.avideo.com/sitemap.xml

**Comment by gbrn** [comment]
Thanks Daniel!

**Comment by gbrn** [comment]
Daniel, continuo com problemas para indexação no Google. Verifique como é apresentado as informações do site:

![image](https://user-images.githubusercontent.com/37880073/148001484-9bdc43b4-6368-49b6-a327-afb82f89e336.png)

**Comment by DanielnetoDotCom** [comment]
muito estranho. nao sei  por que o google está indexando assim. 

confirme se você está usando a ultima versão de todos os arquivos e plugins
