### ISSUE TITLE
System structure proposal

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#5756]
I suggest you do this: https://www.videoinedit.com/
Why is it good:
Users do not see the encoder script when adding a converted video.
Thus, it simplifies and improves your project. It will look more like a professional platform
Check out how it's done here: https://www.videoinedit.com/ and you'll see what to do. They also have a very well done mp3 download and playback.

**Comment by walt93** [comment]
Just a suggestion it would be helpful if you took some screenshots and annotated with some lines, arrows and comments, that would save the developer a whole bunch of time and would clarify your intent.

**Comment by palich91** [comment]
Just look at what I have shown and everything will be clear

**Comment by jengajenga** [comment]
> Just look at what I have shown and everything will be clear

there is absolutely nothing clear with what you have written or said. you might as well close this thread.

**Comment by JoshWho** [comment]
That website sucks. Lots of stuff not loading correctly.

![14762910-85ee979a91053fa2ed8432def406cdb1](https://user-images.githubusercontent.com/39392449/136642267-07b26892-bb1f-4333-8404-2fd5f13c50db.png)

**Comment by JoshWho** [comment]
You really should explain wtf it is you are trying to show fr

**Comment by JoshWho** [comment]
![51f79d36-00be-49ab-8ab7-c7b04972cddf](https://user-images.githubusercontent.com/39392449/136642519-ebe491c0-7097-4840-8fe8-4c7e00e888e4.png)

**Comment by JoshWho** [comment]
> I suggest you do this: https://www.videoinedit.com/ Why is it good: Users do not see the encoder script when adding a converted video. Thus, it simplifies and improves your project. It will look more like a professional platform Check out how it's done here: https://www.videoinedit.com/ and you'll see what to do. They also have a very well done mp3 download and playback.

You do know you can encode inside the webpage and not make it in a new tab don't you? The Cue is the best part about it. This lets others know if there will be  wait or not.
