### ISSUE TITLE
No skip button for viewing video ads in landscape orientation on mobile phones

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5757]
Mobile phone users watch the video horizontally in the browser, and the video ad cannot show the skip button
![iShot2021-09-30 00 13 02](https://user-images.githubusercontent.com/47063171/135308028-a8331b70-12c7-48a5-bca2-f381fe46e0f1.png)
Ad without skip butto
![iShot2021-09-30 00 14 02](https://user-images.githubusercontent.com/47063171/135308209-1b2c6b8a-aae2-4abc-ac53-0b6e3576e59e.png)
n

**Comment by chenjian9885** [comment]
I tested it on the demo site (demo.avideo.com) and got the same resul
![iShot2021-09-30 00 22 54](https://user-images.githubusercontent.com/47063171/135309479-7877328f-76a3-489f-93b5-a38b7f7bd875.png)
t

**Comment by DanielnetoDotCom** [comment]
iOS uses its native player, the skip button is not possible

**Comment by chenjian9885** [comment]
Ok, I see.
