### ISSUE TITLE
Debugging enhancement: Log levels (developer facing enhancement)

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5758]
**Is your feature request related to a problem? Please describe.**
You're always frustrated when users face issues that are not reproducible on the demo site.

**Describe the solution Daniel and his users would benefit from**
Adding additional logging messages on the server, which are conditionally executed based on a global variable.

 - DEBUG level logging all information that would be needed in diagnosing and troubleshooting
 - TRACE level logging adds function enters/exits/flow changes, passed parameters and returns. Overkill for most situations, sometimes just what you need...

The user would never operate in DEBUG/TRACE until/unless requested by the developer, so that debug logs may be provided, and then turn it off (for the obvious reasons of performance&disk; TRACE can produce very heavy log files..)

**Comment by DanielnetoDotCom** [comment]
It is a good idea, I may add this in the future

**Comment by walt93** [comment]
The way to do this is to start, create the macros for logging and trace, and on a day-to-day basis, when you're in some code - instrument it.

Also if you have a specific problem you're trying to isolate - instrument that. Your code base is too big to do this all at once.
