### ISSUE TITLE
Share links: Copy To Clipboard not working.

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5759]
Was testing all of the links in full screen mode and the copy link is not working properly. Nothing happens and nothing to copy to word pad. All other links work

![Share-links-Copy-To-Clipboard-not-working](https://user-images.githubusercontent.com/37937968/135477869-aec4dff1-284d-4eef-bcef-cedd06407099.png)

**Comment by DanielnetoDotCom** [comment]
please reproduce it on demo site so I can test, on my side, it is working

**Comment by Lordblanca** [comment]
ok

**Comment by Lordblanca** [comment]
Tested on demo site it is working. Just not on my end

**Comment by Lordblanca** [comment]
I Found the problem. Had to do a server update... all good thank you for your time
