### ISSUE TITLE
Can not configure Live STream anymore

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5761]
When trying to look at the Live Stream dashboard it doesn't load right and have no way to access the settings.

![81acd7fa-741c-473e-9c4a-e13c0cc9e87a](https://user-images.githubusercontent.com/39392449/135559411-498310d7-1352-4653-93f0-b7c65988d1fc.png)

**Comment by DanielnetoDotCom** [comment]
please check avideo.log

also make sure your plugins are up to date
