### ISSUE TITLE
More data loss. Category has 16 videos. Category page shows 2.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5762]
**Describe the bug**
I have a multi-level hierarchy of videos. At various points in the hierarchy, I can verify that videos are not accessible.

**To Reproduce**
1. Go to Categories, and check the number of videos
2. Go to the category page, and check the number of videos

**Expected behavior**
On a category page, to see all of the videos in a category

**Screenshots**
![Screen Shot 2021-10-01 at 12 10 17 AM](https://user-images.githubusercontent.com/11711050/135580206-18734fde-608a-4fe5-a70f-d234d23ef560.png)
![Screen Shot 2021-10-01 at 12 10 29 AM](https://user-images.githubusercontent.com/11711050/135580218-12df85b0-82af-4c75-8263-e2e393f9bcff.png)

**Comment by DanielnetoDotCom** [comment]
I can only guess the videos are unlisted or this user does not have right to see

is this user an admin?

can you reproduce it on demo site?

**Comment by walt93** [comment]
In this case I am logged in as an admin. I upload all of the videos to the site and none of these are unlisted. Hence why I am reporting this as a "data loss" issue.

My site is in the condition it is in after eight months of uploading files. I would like not to upload files to your demo site for days on end, and create hundreds of categories arranged in a hierarchy until the demo site falls down. That is not an efficient use of time. This is why I am guiding you towards a debuggable platform. Can I ship you a drive with a backup of my site for your debugging?

**Comment by DanielnetoDotCom** [comment]
I mean you can change all videos on demo site to a single category and test the category page.

the main problem is that I cannot reproduce this error on my side. if you can reproduce it on demo site I can resolve that. 

without being able to reproduce I cannot help you.

**Comment by walt93** [comment]
Daniel I will try but realize that I've spent several hundred hours uploading 6,000 pieces of media to make this happen. I really don't have the time to do that on your demo site.

You could take a backup of my database, run against that, and hack the code that accesses the filesystem to point to a dummy file. Then you could debug against my DB.

**Comment by DanielnetoDotCom** [comment]
maybe the best option is if I look it directly into your server/installation.

if is just the infinite scroll 1 hour of support should be enough.

if you are interested you can hire me here https://youphp.tube/marketplace/

**Comment by walt93** [comment]
No worries Daniel, I'm a software dev as well, I'll make sure I've pulled/updated plugins as well. Thanks!

**Comment by DanielnetoDotCom** [comment]
awesome :)!!
