### ISSUE TITLE
local files mount rclone

### ISSUE THREAD

**Issue by webdsf** [WWBN/AVideo#5763]
Hello, I want to use rclone to mount an encrypted folder and use video in it without encoding. And how do you use local mounted material packs at all?

**Comment by stevezemlicka** [comment]
I use local mounted NFS and it typically works pretty well with the odd issue here or there (just had an issue relating to permissions).  I think I tried linking first but had issues with that but if you copy the existing directory data and mount storage in the actual expected path(s), it seems to work ok.

As far as using videos without encoding, I'm pretty sure that's not supported.  But if you're really ambitious, I suppose you could manually create all the database entries and point it to your files manually...if you're thorough, you may be able to make that work.  Probably no small feat though.
