### ISSUE TITLE
does not show VAST Video ads

### ISSUE THREAD

**Issue by webdsf** [WWBN/AVideo#5764]
Advertising does not work at all. video mp4 and arranges it over the video, but nothing works. when you click on  [this](https://i.ibb.co/tMP337w/Screenshot-8.png) appears 500. And by the way, how to add regions, to whom to show, and to whom not?
https://youtu.be/wCEL7kVBxdw

**Comment by webdsf** [comment]
I threw a video where everything is shown. Yes, I uploaded an mp4 video at the beginning, then added it to the company. But nothing works. I wanted to do this on your site, but for some reason, it is buggy now.

**Comment by JoshWho** [comment]
I have the same issue with Vast ad server

**Comment by DanielnetoDotCom** [comment]
What is buggy on demo?

Please reproduce it on demo and let me know
