### ISSUE TITLE
Where are the Live Streams Saving? I no longer see them in the original tmp directory

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5766]
I was trying to find last nights stream it never uploaded and I do not see any videos in the tmp directory. Where do they now save?

**Comment by DanielnetoDotCom** [comment]
the saving location is defined on nginx.conf

**Comment by JoshWho** [comment]
it is showing the www/tmp and that really goes to /mnt/md0/tmp  and all I see in there is logs no flv files

**Comment by JoshWho** [comment]
does the flv auto delete?

**Comment by DanielnetoDotCom** [comment]
> does the flv auto delete?

Only after Streamer download it

**Comment by JoshWho** [comment]
I c. so it thinks it completed. I have no way to get that back do i?

**Comment by JoshWho** [comment]
any way I can turn that feature off and just go back to the cron deleting every 5 days old?

**Comment by DanielnetoDotCom** [comment]
Make sure this line is commented 

https://github.com/WWBN/AVideo/blob/b9d1f0eff782cbe290d3ff21842dbdbb801c7f4e/plugin/Live/standAloneFiles/getRecordedFile.php#L47

**Comment by JoshWho** [comment]
That is already like that.

**Comment by JoshWho** [comment]
Is there a spot where I tell this StandAlone version to use? I just noticed there is nothing that asks me for this file location.

Where do I put the info for the stand alone getRecordedFile.php

**Comment by DanielnetoDotCom** [comment]
if you have a separated live server check its file

![image](https://user-images.githubusercontent.com/18009293/135669310-b5bf3c63-009d-48bd-8616-937253021fc9.png)

**Comment by JoshWho** [comment]
it is not remote just on the main server

**Comment by DanielnetoDotCom** [comment]
I will need to check into the recorder plugin.

maybe if it is on the same server it is deleting 

I can’t check it now.

**Comment by JoshWho** [comment]
ok thank you
