### ISSUE TITLE
Thank You for this addition 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5767]
@DanielnetoDotCom  great addition  thsnk you so much....
![Screenshot_20211001-200209_Samsung Internet](https://user-images.githubusercontent.com/70327833/135700470-b6c865e7-0107-4cdc-9d1c-f955a8c080c5.jpg)

**Comment by jengajenga** [comment]
@milehighkaraoke is yours working? mine isn't. gives me an error and doesn't save despite changing the settings in nginx.

**Comment by milehighkaraoke** [comment]
It seems to be functioning properly.  I made no changes in my nginx
