### ISSUE TITLE
Feature request: Set date on video import

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5771]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I go to bring a new category of media onto the site; I am importing a slew of files from different sites, and don't want all of them filling the "recently added" pages. 

**Describe the solution you'd like**
A three-way radio group on the video import:
  [•] Use today's date (default)
  [  ] Use video's date (we take the create date from the video we are importing)
  [  ] Use this date _____ (some UX for date selection - example I am importing the movie Alien and I want it to appear with a created date of May 25, 1979 because, I don't know, because I'm weird - hey - this is a contrived example - what do you want from me lol)

**Describe alternatives you've considered**
I do this manually just logging into the terminal and using psql - but that's a pain in the you know where.

**Comment by DanielnetoDotCom** [comment]
Sorry but this is not clear to me. do you mean using the youtube-dl tool?

can you please screenshot of what page are you referring to?

**Comment by walt93** [comment]
![Screen Shot 2021-10-04 at 4 18 09 PM](https://user-images.githubusercontent.com/11711050/135937146-75cf63c6-c462-458c-9080-69883aa97117.png)

This could apply to uploaded files as well as imported.
