### ISSUE TITLE
Unsubscribe in email

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#5772]
Notification emails should have an unsubscribe option - many email server filters will add the notification emails to their spam pile and ban the server if they don't see this link option.

**Comment by DanielnetoDotCom** [comment]
Update streamer and Notification plugin version 2.6 should add a unsubscribe link at the bottom of emails

the unsubscribe will only disable notification, not really unsubscribe the user

**Comment by Lordblanca** [comment]
Which plug ins are they? Update streamer? and Notification Plug-ins?

**Comment by DanielnetoDotCom** [comment]
Notification plugin + latest stream version.

I guess your site is already updated
