### ISSUE TITLE
Question about confirming users

### ISSUE THREAD

**Issue by Denominator13** [WWBN/AVideo#5775]
As a test I created a new user which was okay, however I am unsure as to why the verify email throws me a "Sorry unknown error"?

**Comment by DanielnetoDotCom** [comment]
Hi, 

did you set up your email configuration properly?
https://github.com/WWBN/AVideo/wiki/Setting-up-AVideo-Platform-to-send-emails

On what page are you seeing this message?

please check your log files https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
