### ISSUE TITLE
Fatal autoload error.

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#5778]
@DanielnetoDotCom hi

I have just now updated to the latest git. Opening the website i get this error. Please assist. Thansk

Warning: require(/var/www/xxx/objects/composer/../react/promise-timer/src/functions_include.php): failed to open stream: No such file or directory in /var/www/xxx/objects/composer/autoload_real.php on line 71

Fatal error: require(): Failed opening required '/var/www/xxx/objects/composer/../react/promise-timer/src/functions_include.php' (include_path='.:/usr/share/php') in /var/www/xxx/objects/composer/autoload_real.php on line 71

**Comment by DanielnetoDotCom** [comment]
I am working on it.

if you update now should work

**Comment by jengajenga** [comment]
> I am working on it.
> 
> if you update now should work

I have and it has worked. Thank you @DanielnetoDotCom !
