### ISSUE TITLE
Rumble embed Kind of Broken after last git pull

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5781]
![a84b2881-0305-4155-a3ca-1045ab2fe6b7](https://user-images.githubusercontent.com/39392449/136139408-abc80513-695e-41f4-b24d-4003b48c677b.png)

This is the link trying to embed https://rumble.com/embed/vkra3l/?pub=2ieex

Not completely broken though because it does still post the video it just gets stuck.

**Comment by DanielnetoDotCom** [comment]
please check the log file

also, make sure you make a git pull before the test.

yesterday I sent multiple updates

**Comment by JoshWho** [comment]
not showing anything in the log about this. something about vast it is showing.

**Comment by JoshWho** [comment]
I think it might have just been cache it is no longer doing it. I have the latest git pull so no changes happened it just started working. Weird huh? lol
