### ISSUE TITLE
trying to change a video title 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#5786]
have this error
![Screenshot_20211006-141010_Brave - Nightly.jpg](https://user-images.githubusercontent.com/66537018/136259644-0fc03c5b-56b7-436b-86c5-df6f634b89d7.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi

copy the path: 
![image](https://user-images.githubusercontent.com/18009293/136261638-2da89a53-b384-4a57-beed-6271a6ad9946.png)

and make a `sudo chmod -R 777 [your path here]`
