### ISSUE TITLE
PPV Live Not wokring Properly

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5788]
![no PPV](https://user-images.githubusercontent.com/63973045/136322303-de392b9d-0194-4170-a0af-98fa0c7124a9.PNG)

After I create the Plan and go live every user see this instead of the Buying Screen.

here is your Demo like this
![PPV Demo](https://user-images.githubusercontent.com/63973045/136322419-2ccc760c-857f-49c8-adcd-96c20169dd59.PNG)

can you explain why is that.

**Comment by LATINMIXMASTERS** [comment]
Also the issue is when the live is happening no one can buy to see it because it shows the image saying User with no PPV as i showed above hope that issue can be resolve soon thank you.

**Comment by DanielnetoDotCom** [comment]
> Also the issue is when the live is happening no one can buy to see it because it shows the image saying User with no PPV as i showed above hope that issue can be resolve soon thank you.

I did not understand what do you mean

**Comment by LATINMIXMASTERS** [comment]
> > well Sir i don't know what the issue is, but apparently that one is an issue too.
> 
> What you can do now is to change the server timezone into your timezone. this may work
> 
> try to google how to do that.

But i dont wanna touch anything that you did since was installed properly by you can you check on it why is giving that error.

**Comment by LATINMIXMASTERS** [comment]
i just fix the time zone on server and now is working properly.
![ppv live](https://user-images.githubusercontent.com/63973045/136671132-93744fef-9552-451c-bcaa-52e84ebde416.PNG)
