### ISSUE TITLE
Disk Quota Error

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5794]
I want to know why the Disk Quota is not reflecting the right amont megabytes or GB because i have users with a plan but all the uploads look real short on the memory storage by what they are been uploading so if that continue they can get a real low plan and be good with it instead of buying the higher plan. example here i upload mp3 and is like 30 to50 megabytes but look how much is reflected on the disk quota.
![memory](https://user-images.githubusercontent.com/63973045/136446775-22aad30a-c826-410b-952c-60c2c4168190.PNG)

**Comment by sharknetwork24** [comment]
Give this command

cd /var/www/html/AVideo/install
php updateDiskUsage.php

**Comment by LATINMIXMASTERS** [comment]
> Please check both

Yes apparently is now registering the proper sizes for both. Thank you.
