### ISSUE TITLE
Email Sending when Registering in Different Language

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5795]
can you explain why is this happening.
![emails](https://user-images.githubusercontent.com/63973045/136451054-50989e98-d92f-45a8-bb3e-c358dbbf4e7e.PNG)

**Comment by LATINMIXMASTERS** [comment]
Well.supposed to be english you set up the site for me. when someone sign up is all good the next email different language. i am so confused because i did not setup anything you did for me.

![sign up](https://user-images.githubusercontent.com/63973045/136668313-3d8b6b15-4bfd-4b12-b2d2-5317642e6563.PNG)

**Comment by DanielnetoDotCom** [comment]
sorry, this is not wrong.

the email is based on the client language
