### ISSUE TITLE
Profile Photos and Fav Icon keep getting deleted when visiting the pages to edit- Any way to make it not try to grab from the cdn?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5796]
Every time you go to the MyAccount there is no profile picture. Shows a dead image

**Comment by JoshWho** [comment]
This also happen on Sit Configuration Script page when clicking save for the fav icon

**Comment by JoshWho** [comment]
![85f72814-bf71-4fa2-bdde-cbe8bed97823](https://user-images.githubusercontent.com/39392449/136616671-7285ad4a-eeec-453a-854f-31b0901e2e98.png)

**Comment by JoshWho** [comment]
Ok I disabled the login control plugin to continue with this isuue. I upladed a new avatar and clicked save. When I close this tab and reopen MyAccount the avatar is missing again

**Comment by JoshWho** [comment]
seems like it is not saving the physical file

**Comment by JoshWho** [comment]
this is what it is trying to read from 

Access to image at 'https://joshwho-cdn.com/videos/userPhoto/photo2.png?1633733657' from origin 'https://www.joshwhotv.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.


any way to make this not use the cdn?

**Comment by JoshWho** [comment]
or any way to make the site not force cors on photos

**Comment by DanielnetoDotCom** [comment]
Make sure your CDN treat differently the get variables, for example, the URL 

https://joshwho-cdn.com/videos/userPhoto/photo2.png?123
is different than https://joshwho-cdn.com/videos/userPhoto/photo2.png?456

then you will see the updates

**Comment by DanielnetoDotCom** [comment]
Also the cors rules should be possible to add on your CDN side

**Comment by DanielnetoDotCom** [comment]
BTW, I am not forcing CORS on photos, I am doing the opposite

https://github.com/WWBN/AVideo/blob/020ed15edaf4a5bb85ea61348886134956ac33bd/.htaccess#L57-L60

**Comment by JoshWho** [comment]
I cannot get this to load right no matter how I call it. Is there any way that these 2 files could just be called from the main domain?

**Comment by JoshWho** [comment]
1 request
Request	Status	Preflight Request (if problematic)	Header	Problem	Invalid Value (if available)
photo2.png?1633763741	blocked		Access-Control-Allow-Origin	Missing Header

**Comment by JoshWho** [comment]
I think the weird ?123   is what is causing the files to not match for the origin header

**Comment by JoshWho** [comment]
You are 100% right on the allow origin issue. All solved. Thank you brotha
