### ISSUE TITLE
Dashboard Total elimination of users on version 11.4

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5797]
Can you explain to me why the Total User item is missing on version 11.4?
It was also very useful to know the registered users.

**Comment by DanielnetoDotCom** [comment]
This update put back the users counter (for admin only)

**Comment by DanielnetoDotCom** [comment]
I mean, the admins will be able to see the total users on the dashboard.

the regular users will not see it.

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/137203780-c34add37-a975-4fe2-ab59-a4b10742faee.png)

**Comment by sharknetwork24** [comment]
thanks solved Daniel
