### ISSUE TITLE
MYAccount Page has a weird leak at the bottom

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5798]
![script leak myaccount](https://user-images.githubusercontent.com/39392449/136499317-95d00742-1116-4ba1-8da4-a479bb70f1ef.png)

**Comment by wetubeclub** [comment]
the same for me the problem comes from the plugin login control I disabled it and the code disappeared they activated it and it appeared again

**Comment by wetubeclub** [comment]
is ok now!!
Thank you Daniel

**Comment by JoshWho** [comment]
Thank you Daniel. All fixed

**Comment by JoshWho** [comment]
Neverrmind now it has more errors than before

![85f72814-bf71-4fa2-bdde-cbe8bed97823](https://user-images.githubusercontent.com/39392449/136615162-0fb53580-a277-4592-9f9b-04852c19bf99.png)

**Comment by JoshWho** [comment]
I disabled the login control plugin and it makes it go away
