### ISSUE TITLE
New ERRORS after latest gitpull

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5800]
![Screenshot_20211008-064721_Samsung Internet](https://user-images.githubusercontent.com/70327833/136560017-5ab16b64-02bf-4069-a5a2-73b21851df0f.jpg)
![Screenshot_20211008-064727_Samsung Internet](https://user-images.githubusercontent.com/70327833/136560045-e68a608f-3169-4e30-9f87-66e4b6bf1002.jpg)
![Screenshot_20211008-064744_Samsung Internet](https://user-images.githubusercontent.com/70327833/136560084-bae6cf68-a660-495c-b344-0799568dd08a.jpg)
![Screenshot_20211008-064800_Samsung Internet](https://user-images.githubusercontent.com/70327833/136560088-6d3eedea-4545-440d-a5f5-a26fefa232f1.jpg)
![Screenshot_20211008-064813_Samsung Internet](https://user-images.githubusercontent.com/70327833/136560089-3d6c0431-c1a7-41fd-b507-dc7b70012ec9.jpg)
![Screenshot_20211008-064823_Samsung Internet](https://user-images.githubusercontent.com/70327833/136560090-0f8a9d3f-ed54-4b0e-b4c1-2a1365f7f7b5.jpg)
![Screenshot_20211008-064832_Samsung Internet](https://user-images.githubusercontent.com/70327833/136560091-6690b710-3fe7-4311-bcf8-e0484072eb88.jpg)
![Screenshot_20211008-064841_Samsung Internet](https://user-images.githubusercontent.com/70327833/136560092-8fad5d3b-301c-45fa-a587-3ae688f3f9ac.jpg)

**Comment by JoshWho** [comment]
this is fixed
