### ISSUE TITLE
Errors after updating Ubuntu 18.04

### ISSUE THREAD

**Issue by dancoe77** [WWBN/AVideo#5801]
**Describe the bug**
After applying updates site will not load.
Tried rolling back to php7.3 but the errors continued.  Removed all versions pf php and then reinstalled php7.4

**To Reproduce**
1. Go to 'https://asgardiatv.com'
2. See error

**Expected behavior**
The desired behavior is that the site would come up.

**Error Logs**
[09-Oct-2021 04:38:26 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/AVideo/objects/include_config.php:38
Stack trace:
#0 /var/www/html/AVideo/videos/configuration.php(44): require_once()
#1 /var/www/html/AVideo/view/index.php(12): require_once('/var/www/html/A...')
#2 {main}
  thrown in /var/www/html/AVideo/objects/include_config.php on line 38
[09-Oct-2021 04:38:41 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/AVideo/objects/include_config.php:38
Stack trace:
#0 /var/www/html/AVideo/videos/configuration.php(44): require_once()
#1 /var/www/html/AVideo/view/robots.txt.php(5): require_once('/var/www/html/A...')
#2 {main}
  thrown in /var/www/html/AVideo/objects/include_config.php on line 38
[09-Oct-2021 04:38:58 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/AVideo/objects/include_config.php:38
Stack trace:
#0 /var/www/html/AVideo/videos/configuration.php(44): require_once()
#1 /var/www/html/AVideo/view/index.php(12): require_once('/var/www/html/A...')
#2 {main}
  thrown in /var/www/html/AVideo/objects/include_config.php on line 38
[09-Oct-2021 04:39:40 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/AVideo/objects/include_config.php:38
Stack trace:
#0 /var/www/html/AVideo/videos/configuration.php(44): require_once()
#1 /var/www/html/AVideo/view/index.php(12): require_once('/var/www/html/A...')
#2 {main}
  thrown in /var/www/html/AVideo/objects/include_config.php on line 38
[09-Oct-2021 04:40:22 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/AVideo/objects/include_config.php:38
Stack trace:
#0 /var/www/html/AVideo/videos/configuration.php(44): require_once()
#1 /var/www/html/AVideo/view/index.php(12): require_once('/var/www/html/A...')
#2 {main}
  thrown in /var/www/html/AVideo/objects/include_config.php on line 38
[09-Oct-2021 04:41:01 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/html/AVideo/objects/include_config.php:38
Stack trace:
#0 /var/www/html/AVideo/videos/configuration.php(44): require_once()
#1 /var/www/html/AVideo/view/index.php(12): require_once('/var/www/html/A...')
#2 {main}
  thrown in /var/www/html/AVideo/objects/include_config.php on line 38

**Screenshots**
![Error](https://user-images.githubusercontent.com/19907521/136642065-15c05d2a-1cb1-49e2-9773-f4c902b0a2cc.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 94

**Comment by JoshWho** [comment]
run command 

apt upgrade

**Comment by dancoe77** [comment]
Thank you so much for helping me.  I did make the changes.  Unfortunately I'm still seeing the error in the video log.  What is the next thing I should try?  If I need to tar up the files and send them to you let me know.  Or I can give you access to the server.  I also made a slight mistake.  We are running 20.04 instead of 18.04.  Is that the problem?

**Comment by JoshWho** [comment]
I know what you forgot, I just updated to 7.4 and remember this post.  You have to change the line in your nginx config towards the bottom to the new php version.

/usr/local/nginx/conf/nginx.conf

```

             }    
                    location ~ \.php$ {
                       include /etc/nginx/snippets/fastcgi-php.conf;
                       fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
                }

```
