### ISSUE TITLE
Pay with bitcoin error on Subscriptions

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5802]
Once you click pay with bitcoin on the Premium subscription page it does this.

![58a5b2d8-e3b3-4ff7-b913-dcdbaab75c14](https://user-images.githubusercontent.com/39392449/136656532-a2b889c1-8350-4115-8d67-b64a3b98ee08.png)

**Comment by DanielnetoDotCom** [comment]
What do you mean pay with bitcoins?
what payment gateway are you using?

**Comment by JoshWho** [comment]
> What do you mean pay with bitcoins? what payment gateway are you using?

block o nomics

**Comment by JoshWho** [comment]
So should I disable the bitcoin option for now?

**Comment by DanielnetoDotCom** [comment]
I do not test it for a while, but if Blockonomics didn't change anything it should work fine
