### ISSUE TITLE
Push Notifications and Emails Not Working

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5804]
After you fix the issue with Disk Quota now the push notifications are not working. getting this when doing a test 
![push](https://user-images.githubusercontent.com/63973045/136669721-496b1ba8-ea45-42f1-bc24-c8088c6fb8bf.PNG)

**Comment by wetubeclub** [comment]
![no1](https://user-images.githubusercontent.com/60543030/137532780-79c4b6f7-8c1d-4872-990c-4929feda0b84.jpg)

**Comment by wetubeclub** [comment]
I trust you Daniel
This is not the first time we have worked together!!

**Comment by DanielnetoDotCom** [comment]
I did make sure your files and plugins were up to date and now you are in PHP 8.1

```
# php -v
PHP 8.1.0RC4 (cli) (built: Oct 14 2021 16:10:05) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0RC4, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.0RC4, Copyright (c), by Zend Technologies
```

Please check now

**Comment by wetubeclub** [comment]
Thank you Daniel
everything looks ok now!  if something does not work i will come back!!!
Thanks again
Ilias
