### ISSUE TITLE
 Image of the Channel when is live not showing on APP

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5805]
Here as you can see when an user is live you cannot see the channel image.
![not image](https://user-images.githubusercontent.com/63973045/136669778-32165223-3a5a-42ef-b603-018dd9f9fd35.jpg)

**Comment by DanielnetoDotCom** [comment]
doe the same happens on the webpage or only on the mobile app?

**Comment by LATINMIXMASTERS** [comment]
Thanks
