### ISSUE TITLE
 Google Ads Adsense Not working

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5806]
After creating the google adsense acct and activate all it does not show any ads. i follow instructions and input  all code on the ads overlay plugin.

![ads](https://user-images.githubusercontent.com/63973045/136669894-a72daf24-9f4c-4d6a-b8e5-63f266688c9c.PNG)

if i put the same code here it will work but i want to have it as the instructions said.
![script](https://user-images.githubusercontent.com/63973045/136669965-c78474f8-337c-4e55-9711-def8fb6f6a47.PNG)

**Comment by DanielnetoDotCom** [comment]
I am not sure exactly what is the correct configuration on Google Ads. but there are some ads that are automatic and some types of ads that will display the place you paste the code.

you should use the head code for automatic ads and the ADs plugin for ads in the specific place
