### ISSUE TITLE
live streaming from Mobile app

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5810]
I want to know by when live streaming using the mobile app will be good to go.

**Comment by DanielnetoDotCom** [comment]
I just changed your Live server to adaptive mode. can you please try again?

**Comment by LATINMIXMASTERS** [comment]
Ok i will try in a few minutes.

**Comment by LATINMIXMASTERS** [comment]
Here i did a test on iphone and Android both show the same like is connecting but for some reason send the notification i am live and i am but using iphone only hear cannot see anything and Android i was able to set up but took me awhile because the camera was not showing prior going live and i had to change the quality on the configuration area so is a little hassle using the mobile stream is not like a one click thing.  I left the videos just in case you wanna see them are unlisted.

IPHONE STREAM

![IMG-20211029-WA0028](https://user-images.githubusercontent.com/63973045/139490056-34216974-86c9-471a-9416-83aaac20cb0b.jpg)



ANDROID STREAM 

![Screenshot_20211029-151122_Music and Stream](https://user-images.githubusercontent.com/63973045/139490097-b659f9ab-c627-4f41-88b5-1139aa0ce87a.jpg)

**Comment by DanielnetoDotCom** [comment]
can you please try a stream again?

**Comment by LATINMIXMASTERS** [comment]
Ok will do again on both platforms android and iphone. Give me a few minutes

**Comment by DanielnetoDotCom** [comment]
FYI I saw your testing and looks like is working.

In the first test you did I was trying some resolutions on the server that is why it was in portrait. I guess portrait is not ready yet

**Comment by LATINMIXMASTERS** [comment]
Thank you so much for your prompt help and service. I will keep testing the audio for my dj equipment if i find a solution i will share it. 

🚨🚨i recommended 100% anyone to get services and support with Daniel and your platform will be running smooth. Also Use the CDN Storage  is real fast and nice for the Platform. 🚨🚨
