### ISSUE TITLE
Question: What is the config to enable the horizontal scroller of categories at the top of the index page?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5813]
**Describe the question**
Had this on before, and it was totally broken in Safari so I disabled it. I cannot remember what the config is, would like to re-enable it since I see it is working now.

**Screenshots**
This is the thing I am looking to enable:
![Screen Shot 2021-10-10 at 1 20 38 PM](https://user-images.githubusercontent.com/11711050/136711901-a7475b09-671b-4fe8-b0a6-e147012ae3d8.png)
.

**Comment by wetubeclub** [comment]
where are these settings in which plugin`
Thank you
Ilias
