### ISSUE TITLE
Simulive in Avideo platform

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#5815]
Dear, I would like to know if the Avideo platform has some kind of "simulive" service (Run files based on real time)?
I think I saw this function somewhere.

**Comment by jengajenga** [comment]
> Hi Daniel, Simulive is nothing more than a playlist that runs a determined sequence of videos, simulating a LIVE programming. The detail is that all viewers watch the same time of the video simultaneously. Is there something like that on the platform?

it is there. it's called programs.
arrange your videos and "play as live". it's pretty good only that the playlist can't be changed midway. if you want to add/remove a video, you have to stop, rearrange and then play from the beginning.

i'm sure @DanielnetoDotCom will see to making a fix for that (i hope) :-

**Comment by CROSSMediaNet** [comment]
Question: can any user make their programs go live as well, or it will have to be the admin?

**Comment by gbrn** [comment]
Hi Daniel,

Returning to the subject of this post. I'm still interested in this role. In the past I called it simulive. Some market platforms call it Playout.
Check out this video of a similar function so you can understand what I'm referring to:
https://www.muvi.com/playout/wp-content/uploads/sites/3/2020/05/Muvi-Playout-Intro-Video.mp4

Interesting functions:
- Programs will be broadcast based on the scheduled time and your viewers will be able to access the programs on your channel.
- Schedule programs 24 hours a day, 7 days a week.
- Pre-schedule a live show in the scheduler. The scheduler allows you to broadcast a program on a recurring daily or weekly basis.
