### ISSUE TITLE
Deactivate

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5823]
Sorry Daniel.  Tell me how to disable this ?.  I don't remember how to do it.

![Screenshot_20211013-221306_Samsung Internet.jpg](https://user-images.githubusercontent.com/82677269/137206496-f335117a-8945-41c5-98af-99f141de60a9.jpg)

**Comment by DanielnetoDotCom** [comment]
Only admin can see that. 

If I am in your shoes I would keep it. there are nice information on it.

but you can disable it here 

![image](https://user-images.githubusercontent.com/18009293/137207382-325601c7-1c64-4f54-878a-291d5bc01c9c.png)

**Comment by sharknetwork24** [comment]
Plugin YPT SOCKET right?

**Comment by sharknetwork24** [comment]
I agree with you that it is very useful, however I have the problem that when an admin connects I cannot interact with the platform until the socket connects.  Is there a way to make it connect faster?

**Comment by sharknetwork24** [comment]
Ok Daniel. 
Thanks
