### ISSUE TITLE
Incredibly slow page load. Impossibly slow "create category. watch spinner" - up to 5 minutes to load "My Videos" - able to reproduce on demo site

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5830]
**Describe the bug**
My site has been so slow I could claw my eyeballs out. 3-4-5 minutes to load the page. Nothing in the browser developer logs until the page loads.

When Browser X is "stuck", it remains so even if you close and open new sessions in the same browser.
While Browser X is "stuck", if you launch browser Y, it may be able to connect, until Browser Y becomes "stuck".
While Browser X is "stuck", if you sudo kill -9 all apache processes, it usually, but not always, comes "unstuck".

Browser X, Y = Safari, Brave, Opera, Firefox, doesn't seem to matter

**To Reproduce**
1. Go to your AVideo site
2. Load the home page
3. Log in
4. Load the my videos page (<------ virtually guaranteed to trigger, categories->new category->save also may trigger)

On the demo site
1. Go to the demo site
2. Log in
3. Go to Categories
4. Create a new category
5. Save
6. Watch the spinner, after about 30 seconds reload the page
7. Observe the page reload doesn't happen after more than 2 minutes
8. Close the tab and open another
9. Observe loading demo.avideo.com is taking more than one minute

**Expected behavior**
Not to take up to five minutes to load the web page.

**Screenshots**
![Screen Shot 2021-10-16 at 1 03 07 AM](https://user-images.githubusercontent.com/11711050/137579744-7f092fc9-6dce-4fea-95f0-0d3208c4486b.png)

**Comment by walt93** [comment]
Checking quickly Daniel, I did a fresh git pull, My Videos came up right away - no data - and Safari still seems to be having problems

1. Loading /mvideos on Safari, after 3 minutes, still "loading"
2. Make a new tab in Safari and try to open /mvideos and nothing is loading - blank page after 3 minutes.
3. Loading /charts on Safari, it isn't seeing any data and all counts are 0 with no graphs.

4. Tried loading /mvideos on Brave, it works as expected, quickly.

5. Closed everything in Safari , reopened, and /mvideos loaded

Movie shows steps 1-4 - window with 3 tabs is safari - other window is brave.

https://user-images.githubusercontent.com/11711050/137606162-f2ae6eca-c93d-429b-a237-31b33f10f393.mov


Few months ago, I was having a variant of this problem, and IIRC that is why we commented out a line in my .htaccess (?) - but that was before moving to CDN

I'll write up a separate bug for /charts that seems unrelated. Behavior seems improved, I only had to use two browsers and take a couple of minutes to get the page to load. Previously it was like going to battle. Something is still wrong though...

**Comment by DanielnetoDotCom** [comment]
just confirming, is this happening only on safari?

I suspect it was only caching/fixing some info

**Comment by DanielnetoDotCom** [comment]
Hi

just tested on safari on the demo site and it is fine

![chrome-capture (2)](https://user-images.githubusercontent.com/18009293/137908785-a3aa83a1-526c-4d7a-aff2-96df966cf811.gif)

are you on the latest git pull?

what OS is your streamer installed?
