### ISSUE TITLE
Question: Building new server. Which storage is better, Backblaze or Wasabi?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#5835]
**Describe the question**
I can get a good deal on a more powerful server, thinking, maybe while I'm moving, move my storage into the cloud.

Which of these two plugins/providers works best with AVideo?

Is it better to try Backblaze+Cloudflare CDN, or the AVideo CDN?

**Comment by DanielnetoDotCom** [comment]
AVideo CDN + CDN storage for sure...

https://github.com/WWBN/AVideo/wiki/CDN-Storage

feel free to ask direct support to help configure it

**Comment by walt93** [comment]
Where is pricing? Does it bill per TB/Month, or ___?

**Comment by DanielnetoDotCom** [comment]
Hi

I just wrote this to make the prices clear https://github.com/WWBN/AVideo/wiki/CDN-Storage#prices
