### ISSUE TITLE
Found many wrong video-resolutions in SQL made from last 4 chars video_file

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#5836]
I found many resolutions which are uploaded for example as HD (720p) but stored in SQL as the value of the last 4 characters from the video_filename like the 2 images below. Not all videos have this problem and it look like that this problem only occurs when these 4 are numbers.

**Example 1**
![A1](https://user-images.githubusercontent.com/39981177/137621030-f83eeaef-1fc6-489e-8306-7c3209261c7d.jpg)

**Example 2**
![B1](https://user-images.githubusercontent.com/39981177/137621050-e17caaaa-d1f5-41ce-b5a4-76fdccbde768.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi

I just sent an update to avoid this happen again. but I could not reproduce it here.

what is the exact filename on your mp4 file? can you please show how it looks like in the videos directory?

**Comment by TLCReuver** [comment]
Hi

Here is the directory_listing from example 2. Thankz for the update.
![Snap1](https://user-images.githubusercontent.com/39981177/137796217-77e75b08-a840-4b40-b697-823e748b08a6.jpg)

**Comment by DanielnetoDotCom** [comment]
I see

you should just fix the HigestResolution, add the correct one. if it is 0 or empty the script will try to get it again.
