### ISSUE TITLE
Idea for chat

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5842]
Allow a space on top of chat to add image and or link. And it can be turned on and off
![Link-here](https://user-images.githubusercontent.com/37937968/137658364-fb71fd36-10d7-4bdd-ad0e-b33f68fc421e.png)
![Link-here-2](https://user-images.githubusercontent.com/37937968/137658366-84affa3b-c5fd-48bf-b225-ff08b5feb55c.png)

**Comment by DanielnetoDotCom** [comment]
I just not understanding why you need that.
