### ISSUE TITLE
User Login with Email Address

### ISSUE THREAD

**Issue by Yoxed** [WWBN/AVideo#5845]
Is there a way I can make it so user can use their email address to login instead of their usernames.
Alot of users are having problems with that, it would be easier if they can use their email address instead.

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/137782258-bf374967-d121-4dbe-835c-f2d7ae0b9eac.png)

**Comment by Yoxed** [comment]
Thank you I was able to resolve it. At first, I thought it was not working until I realized I had to change everyone's user to their email address.
