### ISSUE TITLE
ABR ffmpeg wrong command

### ISSUE THREAD

**Issue by streamthing** [WWBN/AVideo#5847]
Why there https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream
in command you are adding hls options and set output to rtmp?
`-f hls -hls_time 6 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_low`

**Comment by streamthing** [comment]
lol, still not corrected

**Comment by streamthing** [comment]
Remove this `-f hls -hls_time 6 -hls_list_size 0` from command here https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream

**Comment by DanielnetoDotCom** [comment]
> Remove this `-f hls -hls_time 6 -hls_list_size 0` from command here https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream

Why remove it. I agree it may work when I remove it, but there is any advantage to not specifying it?

**Comment by DanielnetoDotCom** [comment]
I just review it and you are correct. thanks

**Comment by streamthing** [comment]
> Why remove it. I agree it may work when I remove it, but there is any advantage to not specifying it?

It will be work without any problem, because you didn't generate HLS with this ffmpeg command.

**Comment by DanielnetoDotCom** [comment]
> > Why remove it. I agree it may work when I remove it, but there is any advantage to not specifying it?
> 
> It will be work without any problem, because you didn't generate HLS with this ffmpeg command.

Agree and understand now

it was a mistake
