### ISSUE TITLE
Docker install problem

### ISSUE THREAD

**Issue by mohmafia** [WWBN/AVideo#5848]
how to install on docker ?

problem is that the web container fails to start
and i can not access it and can not access the db container either
also port 80 and 443 is in use so need to set a different port
i like to test WWBN Avideo on docker thanks
![image](https://user-images.githubusercontent.com/61617857/137827023-c27259bb-bfe0-409d-9e0d-17e86e766b09.png)

**Comment by DanielnetoDotCom** [comment]
Hi, currently the docker is not well tested. I am accepting help to fix it.

**Comment by DanielnetoDotCom** [comment]
Awesome, when you can share with us

**Comment by mohmafia** [comment]
ok done did pull requests you still have to do the php.ini for the post max and the max filesize 3200m recomended for the post max and 3000M for the max file size
