### ISSUE TITLE
Streaming media cannot play video using YPTStorage plug-in

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5852]
Streaming media cannot play video using YPTStorage plug-in
![image](https://user-images.githubusercontent.com/47063171/138119388-03635cdf-64d9-4481-af79-468c2e14ff0f.png)
![image](https://user-images.githubusercontent.com/47063171/138117728-a211e5c6-7891-4a98-b894-3ee7d3c1c0d8.png)
![image](https://user-images.githubusercontent.com/47063171/138117979-6808426a-2ec8-468e-81e5-f202a27e0b56.png)
![image](https://user-images.githubusercontent.com/47063171/138118094-f2689523-fb2c-44dc-aea2-c78f3e242493.png)
![image](https://user-images.githubusercontent.com/47063171/138117883-a242660e-f522-42f7-b048-9c3f3f6ad4b9.png)

**Comment by chenjian9885** [comment]
Why can't I transfer the video
![image](https://user-images.githubusercontent.com/47063171/138208878-02758029-7697-486f-a539-58c2216c4032.png)
![image](https://user-images.githubusercontent.com/47063171/138208928-9a15e649-e14f-40bc-b15a-3dc8a547a1ee.png)
![image](https://user-images.githubusercontent.com/47063171/138208976-8ba780ec-f4c0-4ef9-ab74-749aa720100b.png)

**Comment by DanielnetoDotCom** [comment]
I went to your YPTStorage installation yesterday and it was not working.

when you try it, please make sure you disable the other storages. S3, B2, CDN Storage, etc

**Comment by chenjian9885** [comment]
I don't have other storage or cdn, I am tested at demo.avideo.com.

**Comment by chenjian9885** [comment]
I don't know why the folder is empty.
![image](https://user-images.githubusercontent.com/47063171/138385672-edb93dd2-a5dc-48cd-af78-2f57b7fafe93.png)

**Comment by chenjian9885** [comment]
Okay, I will check the installation and test again.
