### ISSUE TITLE
Since New Installation showing wrong TimeZone 

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5854]
While doing schedule Live or anything related to Time is showing wrong time prior installation was good and time was all good. The server in New York Time so i dont know why new installation that you did now showing wrong time. 

I went live at 2pm EST and was showing i went live a 1800hrs so 6pm and i was not able to schedule any live stream becauss was showi g i was already passed the time.

**Comment by DanielnetoDotCom** [comment]
are you located in NY?

if yes I guess it is converting the timezone wrong, I will need to review that.

**Comment by DanielnetoDotCom** [comment]
I just sent you an update, can you please check if makes any difference?

**Comment by LATINMIXMASTERS** [comment]
I put it for 11pm and still showing that already passed. 
![Screenshot_20211020-215100_Gallery](https://user-images.githubusercontent.com/63973045/138197468-14accf29-68f1-48ad-b620-28752accfdb9.jpg)

**Comment by DanielnetoDotCom** [comment]
I could confirm the bug, tomorrow I will review it directly on your server.

**Comment by LATINMIXMASTERS** [comment]
Ok Good Night
