### ISSUE TITLE
Since New Installation and using your CDN taking way too long for videos

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5855]
After i finished a live stream of 57min it took like 2.5 hrs to process and put it for viewers to see before on prior installation only took a few minutes. And then while it was doing the process on CDN storage was shwoing the video but when clikced on it was shwoing only 1sec and jumping to next video so is a little uncomfortable for users to see a video that they cannot watch. But like i said prior installation was good so i dont understand we move here for better placement and i am encountered more issues. 

Hope the problem can be solve. 

Here is the part where was showing the video but onmy played for 1 sec and jumped to next video 

![Screenshot_20211020-161127_Chrome](https://user-images.githubusercontent.com/63973045/138190212-5c5b2b3b-8830-4188-ba7b-0aed05d7e337.jpg)

**Comment by LATINMIXMASTERS** [comment]
Ok but we missing the point, so it will take 2.5 hrs everytime?? So you mean if i get more streamers that will get to like 4 to 6 hrs wait time???

**Comment by DanielnetoDotCom** [comment]
I am not sure how long it may take to transfer. it depends on your server upload speed and the cloud speed.

how big are your videos?

FYI the videos will be transferred in parallel so it may be faster.
another option is to not auto-transfer the video to the cloud but it will require manual transfer when you decide to host it on the CDN cloud.

**Comment by LATINMIXMASTERS** [comment]
Well thats my question because like i said prerty much as soon as i finished a live streaming was already there but now i finished a live streaming of 57minutes and took 2.5 hrs for me to see thats a lot of time and my server is on 1Gbit port so should be good speed upload like i said prior installation was quick so i am totally confused 😕

**Comment by DanielnetoDotCom** [comment]
I mean, if you encoded in HLS it was not uploaded to wasabi. also, MP4 files are faster to transfer.

HLS is a better format for playback. I recommend you to keep it.

**Comment by LATINMIXMASTERS** [comment]
Also Please let me know why takes too long... i did a live streaming today for 1hr and it took a few hours before the video was able to watch and then after the upload finished did not send the notifications 😪
