### ISSUE TITLE
disable a plugin

### ISSUE THREAD

**Issue by karlkunc** [WWBN/AVideo#5858]
I did a git pull and now the site is stuck in a maintenance mode due to a plugin that was enabled and not configured right. how can I disable this plugin without access to the gui?  it is the ftp plugin that needs to be disabled. also, i forgot to backup before the git pull like the idiot I am. thanks

**Comment by DanielnetoDotCom** [comment]
Try this

`cd /var/www/html/AVideo/install`

than

```
# php resetPlugins.php 
1 - Reset all plugins Parameters
2 - Reset CustomizeUser Plugin Parameters only
3 - Reset all plugins (Will also inactivate the plugins)
Choose an option: 
```

or you can do it directly in the database
