### ISSUE TITLE
Encoder online

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#5888]
HI,
do you have any breakdown? can't encode online, Max File Size 2.00MB 
![Screenshot_2021-10-28 Encoder Network](https://user-images.githubusercontent.com/93145787/139264974-5693c23b-d98a-4801-91af-6fb4636a65e2.png)

**Comment by DanielnetoDotCom** [comment]
I just change the encoder server configuration and you should be able to upload up to 2 GB files now

**Comment by KrzysioMisio** [comment]
thanks, it helped :-)
