### ISSUE TITLE
Play Live Feature not working. 

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5892]
I have tried to use this feature but wont work say is live after clicking Play it live so can you tell me what is wrong.

![Screenshot_20211028-223446_Chrome](https://user-images.githubusercontent.com/63973045/139364325-7f75d92f-8851-4ef1-8c63-07fe553bff98.jpg)

**Comment by DanielnetoDotCom** [comment]
Again, this is still experimental. 

it depends on a lot of factors, video type, resolution, codecs, etc...

right now I cant check that, but for sure I will return on that feature in the future.

**Comment by LATINMIXMASTERS** [comment]
Om thank you , so i know is experimental so is not offcial features so i can tell users. Thanks that would be a good thing to add as official features. Thanks.
