### ISSUE TITLE
installation 

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#5895]
installation error

https://user-images.githubusercontent.com/93145787/139486667-982eac05-80de-4ae0-9d88-51156577b7b3.mp4

avideo.log
[avideo.log](https://github.com/WWBN/AVideo/files/7444303/avideo.log)

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by KrzysioMisio** [comment]
thanks, it helped :-)
