### ISSUE TITLE
Plugin cache

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#5896]
Hello Daniel
I did the last git pull but the cache got worse the first page opens quickly 
but when you select a video the site hangs and shows that it is loading
I sipped a coffee and it still loads the video I chose to watch
I cleared caches but nothing
some quick help??

Thank you
Ilias

**Comment by wetubeclub** [comment]
in the end it does not load even the first page!!

**Comment by DanielnetoDotCom** [comment]
Did you install the tables for the cache plugin?

**Comment by wetubeclub** [comment]
I installed the tables normally
I just made a pull but again the same does not open any page

**Comment by DanielnetoDotCom** [comment]
checking oyur server

**Comment by wetubeclub** [comment]
what to check Daniel, after upgrade everything was done 
before everything was working normally
take a look at the site can work on you
what can I say I do not know

**Comment by wetubeclub** [comment]
the same again sticks to the page loading
I have been waiting for 5 minutes to log in to admin after the last gitpull

**Comment by wetubeclub** [comment]
only the first page is displayed
When I open for example the plugin page or the log file page I get a white page and the corresponding codes
int(54)
int(74)
int(162)

**Comment by DanielnetoDotCom** [comment]
I am checking for you. I am accessing your server now

**Comment by wetubeclub** [comment]
ok i see

**Comment by wetubeclub** [comment]
thank you

**Comment by DanielnetoDotCom** [comment]
FYI, your mysql is taking a while to restart. 

To try to improve MySQL I just follow this https://github.com/WWBN/AVideo/wiki/Speed-up-your-page#mysqltuner-script 

but it is still very slow, also I disabled the new cache, and makes no difference.

I suspect your harddrive is dying or you are having a problem on the mysql

**Comment by DanielnetoDotCom** [comment]
Rebooting the server now

**Comment by wetubeclub** [comment]
what i do not understand is this morning it worked normally i upgraded the plugins and a gitpull
after that the problems started
what is the problem and what is the solution I want you to tell me
if it's something i have to pay of course i will do but i need to know exactly what it is

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
I did all I can already. for now you are the only one I could see the site went slower with this new modification.
I reverted it to the old cache style, but I still feel your site is slow and I do not know why. I can only suspect on the hardware

I could see you have large disks. usually, large disks are slower. that is why is very common to have servers with large disks + small SSD disks, so the system do not slowdown

**Comment by wetubeclub** [comment]
we can put it all in the cloud? script and storage or we must have a server?

**Comment by DanielnetoDotCom** [comment]
if you mean a cloud server, yes you can. but I still think a dedicated server with SSD is better

**Comment by wetubeclub** [comment]
I will email you what I want to do and to find a solution about

**Comment by DanielnetoDotCom** [comment]
Ok, thanks

**Comment by wetubeclub** [comment]
by the way I was upgrading the other site
  that is, what I did on this site I did the same process on the other and it works faster now
so you must be right about the server time for a change

**Comment by DanielnetoDotCom** [comment]
Thanks for the info. I suspect the hard drive is very slow

FYI, the demo site is a small and slow VPS and the cache works fine on it
