### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by arkachat** [WWBN/AVideo#5900]
[Ubuntu](url) 20.04, php 7.4 , nginx 1.18, mysql 8

2021/11/01 11:02:59 [error] 195588#195588: *10 FastCGI sent in stderr: "PHP message: Installation: 9 {"webSiteRootURL":"http:\/\/xxx.online:8080\/","systemRootPath":"\/var\/www\/html\/","webSiteTitle":"knv-video","databaseHost":"localhost","databasePort":"3306","databaseUser":"xxxx","databasePass":"XXXX","databaseName":"xxxx","mainLanguage":"us","systemAdminPass":"xxxx","contactEmail":"webmaster@xxx.online","createTables":"1"}PHP message: Installation: 20PHP message: Installation: 33PHP message: Installation: 45PHP message: Installation: 55PHP message: Installation: 57PHP message: Installation: 66PHP message: Installation: 74PHP message: Installation: 96PHP message: Installation: 99PHP message: Installation: 109PHP message: Installation: 117PHP message: Installation: 125PHP message: Installation: 133PHP message: Installation: 141PHP message: Installation: 157PHP message: Installation: 166PHP message: Installation: 221PHP message: Installation: 225PHP message: Installation: 236PHP message: Installation: 240" while reading response header from upstream, client: 135.19.30.112, server: xxx.online, request: "POST /install/checkConfiguration.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "xxx.online:8080", referrer: "http://xxx.online:8080/install

Variable | Value
-- | --
USER | www-data
HOME | /var/www

Oct 25 2021 18:20:54
--
Server API | FPM/FastCGI
Virtual Directory Support | disabled
Configuration File (php.ini) Path | /etc/php/7.4/fpm
Loaded Configuration File | /etc/php/7.4/fpm/php.ini
Scan this dir for additional .ini files | /etc/php/7.4/fpm/conf.d
Additional .ini files parsed | /etc/php/7.4/fpm/conf.d/10-mysqlnd.ini, /etc/php/7.4/fpm/conf.d/10-opcache.ini, /etc/php/7.4/fpm/conf.d/10-pdo.ini, /etc/php/7.4/fpm/conf.d/15-xml.ini, /etc/php/7.4/fpm/conf.d/20-calendar.ini, /etc/php/7.4/fpm/conf.d/20-ctype.ini, /etc/php/7.4/fpm/conf.d/20-dom.ini, /etc/php/7.4/fpm/conf.d/20-exif.ini, /etc/php/7.4/fpm/conf.d/20-ffi.ini, /etc/php/7.4/fpm/conf.d/20-fileinfo.ini, /etc/php/7.4/fpm/conf.d/20-ftp.ini, /etc/php/7.4/fpm/conf.d/20-gettext.ini, /etc/php/7.4/fpm/conf.d/20-iconv.ini, /etc/php/7.4/fpm/conf.d/20-json.ini, /etc/php/7.4/fpm/conf.d/20-mbstring.ini, /etc/php/7.4/fpm/conf.d/20-mysqli.ini, /etc/php/7.4/fpm/conf.d/20-pdo_mysql.ini, /etc/php/7.4/fpm/conf.d/20-phar.ini, /etc/php/7.4/fpm/conf.d/20-posix.ini, /etc/php/7.4/fpm/conf.d/20-readline.ini, /etc/php/7.4/fpm/conf.d/20-shmop.ini, /etc/php/7.4/fpm/conf.d/20-simplexml.ini, /etc/php/7.4/fpm/conf.d/20-sockets.ini, /etc/php/7.4/fpm/conf.d/20-sysvmsg.ini, /etc/php/7.4/fpm/conf.d/20-sysvsem.ini, /etc/php/7.4/fpm/conf.d/20-sysvshm.ini, /etc/php/7.4/fpm/conf.d/20-tokenizer.ini, /etc/php/7.4/fpm/conf.d/20-xmlreader.ini, /etc/php/7.4/fpm/conf.d/20-xmlwriter.ini, /etc/php/7.4/fpm/conf.d/20-xsl.ini
PHP API | 20190902
PHP Extension | 20190902
Zend Extension | 320190902
Zend Extension Build | API320190902,NTS
PHP Extension Build | API20190902,NTS
Debug Build | no
Thread Safety | disabled
Zend Signal Handling | enabled
Zend Memory Manager | enabled
Zend Multibyte Support | provided by mbstring
IPv6 Support | enabled
DTrace Support | available, disabled
Registered PHP Streams | https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar
Registered Stream Socket Transports | tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3
Registered Stream Filters | zlib.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, convert.iconv.*

**Comment by DanielnetoDotCom** [comment]
Is it a ubuntu server?

I cannot see any clear error on that log

**Comment by arkachat** [comment]
Thats the issue , the installation passes and then we see this:

Error. Oops you've encountered an error
It appears that either something went wrong or the mod rewrite configration is not correct.
If you don't use apache, just let .htaccess stay or create a empty file - then this check will pass.

We need to allow Apache to read .htaccess files located under the /var/www/html directory. You can do this by editing the Apache configuration file:

Find the section <directory /var/www/html> and change AllowOverride None to AllowOverride All

**Comment by DanielnetoDotCom** [comment]
> Thats the issue , the installation passes and then we see this:
> 
> Error. Oops you've encountered an error It appears that either something went wrong or the mod rewrite configration is not correct. If you don't use apache, just let .htaccess stay or create a empty file - then this check will pass.
> 
> We need to allow Apache to read .htaccess files located under the /var/www/html directory. You can do this by editing the Apache configuration file:
> 
> Find the section <directory /var/www/html> and change AllowOverride None to AllowOverride All

Sorry I do not know what you mean

**Comment by arkachat** [comment]
What I mean is :

Installation passes but looks like its a false indication as it really does not install.
Or for some reason it fails and the installer does not detect it.
What exactly would you need from me for a better understanding?

**Comment by DanielnetoDotCom** [comment]
so you do not have the mod rewrite enabled or maybe is not properly set up. try google for that.

and really looks like you are not using Ubuntu

**Comment by arkachat** [comment]
@DanielnetoDotCom  ,  I am using Ubuntu 20.04 LTS , why would I lie?

 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

As for the rewrite , here is the code 

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		#try_files $uri $uri/ =404;
                try_files $uri $uri/ /index.php?$args;
	}

What am I missing here?

**Comment by DanielnetoDotCom** [comment]
I am not saying you are lying I am just saying you did not respond when I first asked you.

But looks like you not using apache then.

I am not sure how you will resolve that on nginx.

for me looks like you are not using the recommended configuration. 

https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements

**Comment by arkachat** [comment]
Thanks for getting back to me @DanielnetoDotCom ... the checkconfiguration should be checking this during the install right?

**Comment by DanielnetoDotCom** [comment]
the mod-rewrite is a prerequisite to install it. it suppose to be installed before proceeding.
