### ISSUE TITLE
Relosution Switcher showing some wrong information.

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5901]
Yesterday i did a live stream and for some reason after it finished encoding created two videos and also shows this and app and website and doing it in a few videos. So cannot swith between resolutions.

![Screenshot_20211101-011103_Chrome](https://user-images.githubusercontent.com/63973045/139701539-727f831a-c99f-4261-b4eb-e29c4f3446e3.jpg)

**Comment by DanielnetoDotCom** [comment]
There is a plugin fix for that.

![image](https://user-images.githubusercontent.com/18009293/139701809-d76edab5-f3b4-4538-9553-47fbd6414026.png)

**Comment by LATINMIXMASTERS** [comment]
Sorry the website and app were working properly and for some reason now showing that. I bought all plugins.

**Comment by DanielnetoDotCom** [comment]
I know. I will update it for you but is good for you to check your marketplace account so you can have access to the plugins updates. so you do not have to wait for me to update.

https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin

if for some reason you are missing a plugin in your account email me at developer@youphptube.com

**Comment by LATINMIXMASTERS** [comment]
For some reason the video stop playing 

https://musicandstream.com/video/158/dj-herman-live-halloween-mix-on-31-oct-21-19-54-01?channelName=DJHERMAN

**Comment by DanielnetoDotCom** [comment]
For some reason, the transfer to the cloud was not complete (maybe still transferring)

I just clicked on the upload button again it should transfer now

![image](https://user-images.githubusercontent.com/18009293/139732037-ba6491eb-caae-46f4-bb2f-b2f2af44fb4f.png)

**Comment by LATINMIXMASTERS** [comment]
Ok  so that could be an issue happening all the time? Also i dont know why the system broke my live stream in two parts i never lost connection or anything hope it does create this issues later. Also the HLS is working right? Because some videos shows HD SD on switcher but some videos shows the quality of video like 720p 480p etc. 

![Screenshot_20211102-131936_Chrome](https://user-images.githubusercontent.com/63973045/139914237-6e31119f-6e67-4300-a776-5e6dbe1c114a.jpg)
![Screenshot_20211102-131952_Chrome](https://user-images.githubusercontent.com/63973045/139914239-b0bdc56f-a30f-4f58-8411-6409ee96f3eb.jpg)

**Comment by DanielnetoDotCom** [comment]
Depends on how big is your live stream.

the default value is a 2GB file, it can be changed on the nginx.conf

think about someone can make a 24hours live and your file will be huge.

increase this parameter https://github.com/WWBN/AVideo/blob/e258385ae39c1c4007cfb55e3d7d70ec90b7624f/plugin/Live/install/nginx.conf#L45

and restart nginx

the nginx.conf should be on 

/usr/local/nginx/conf/nginx.conf

**Comment by LATINMIXMASTERS** [comment]
Ok ussually a DJ goes like a max of 3hrs so what do you think will be a good number ? And maybe he doing it at 1080p because i want to have the right amount because i understand what you are saying.

**Comment by LATINMIXMASTERS** [comment]
Ok i put 4096m i know they ussually do less but to be safe. I did restart nginx as you stated but said already in used. Hope is all good. And about the switcher why sometimes shows HD by itself and sometimes with Quality like 720p HD

**Comment by DanielnetoDotCom** [comment]
do not forget to restart nginx after change it

**Comment by LATINMIXMASTERS** [comment]
Which command is that? Because i did the one you sent me while back and it said nginx already in used.

**Comment by DanielnetoDotCom** [comment]
`sudo /usr/local/nginx/sbin/nginx -s stop `

than 

`sudo /usr/local/nginx/sbin/nginx`

**Comment by LATINMIXMASTERS** [comment]
Ok thank you. About the images i sent you prior on the quality why some has HD SD and Low and some has the 720p HD , 480p And so on.

**Comment by DanielnetoDotCom** [comment]
HD SD and Low is the old Plugin 

the new plugin uses the automatic resolution 

https://github.com/WWBN/AVideo/wiki/About-Video-Upload#automatic-resolutions-default-and-recommended

**Comment by LATINMIXMASTERS** [comment]
Ok thank you so much
