### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by cacodepaula** [WWBN/AVideo#5902]
Hi!
I'm having problems installing YouphpTube on my hosting. When I host locally, in WAMP, I can configure normally, however, when I upload to the server, the home page shows "500 Internal Server Error" and it's just that. Could someone help me with this error?

https://studio.i9ead.com.br/

**Comment by jengajenga** [comment]
do a fresh install directly to the server instead. wamp and lamp could be having different settings but we wouldn't be able to tell because we can't see and compare.

fresh install to the server.

**Comment by cacodepaula** [comment]
@jengajenga 

I did the installation in different ways. I did it initially through git, then through upload. The problem persists. I'm using 'Plesk' (I don't know if that influences...).
I took the log report, however, it didn't help me much. Here is the report:

177.104.9.47 - - [01/Nov/2021:15:59:57 -0300] "GET / HTTP/1.0" 500 1565 "https://studio.i9ead.com.br/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
177.104.9.47 - - [01/Nov/2021:16:01:19 -0300] "GET / HTTP/1.0" 500 1565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
177.104.9.47 - - [01/Nov/2021:16:01:26 -0300] "GET / HTTP/1.0" 500 1565 "https://studio.i9ead.com.br/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
34.241.29.190 - - [01/Nov/2021:16:02:17 -0300] "GET / HTTP/1.0" 500 1565 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/78.0.3882.0 Safari/537.36"
34.241.29.190 - - [01/Nov/2021:16:02:18 -0300] "GET /error_docs/styles.css HTTP/1.0" 200 3145 "https://studio.i9ead.com.br/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/78.0.3882.0 Safari/537.36"
34.241.29.190 - - [01/Nov/2021:16:02:18 -0300] "GET /error_docs/server.svg HTTP/1.0" 200 7849 "https://studio.i9ead.com.br/error_docs/styles.css" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/78.0.3882.0 Safari/537.36"
209.222.82.139 - - [01/Nov/2021:16:14:26 -0300] "GET / HTTP/1.0" 500 1565 "-" "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729)"
74.51.221.37 - - [01/Nov/2021:16:14:27 -0300] "GET / HTTP/1.0" 500 1565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
74.51.221.37 - - [01/Nov/2021:16:14:27 -0300] "GET /error_docs/styles.css HTTP/1.0" 200 3145 "https://studio.i9ead.com.br/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
74.51.221.37 - - [01/Nov/2021:16:14:28 -0300] "GET /error_docs/server.svg HTTP/1.0" 200 7849 "https://studio.i9ead.com.br/error_docs/styles.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
204.85.30.6 - - [01/Nov/2021:16:14:30 -0300] "GET / HTTP/1.0" 500 1565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
204.85.30.6 - - [01/Nov/2021:16:14:30 -0300] "GET /error_docs/styles.css HTTP/1.0" 200 3145 "https://studio.i9ead.com.br/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
204.85.30.6 - - [01/Nov/2021:16:14:31 -0300] "GET /error_docs/server.svg HTTP/1.0" 200 7849 "https://studio.i9ead.com.br/error_docs/styles.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
18.237.117.31 - - [01/Nov/2021:16:14:41 -0300] "GET / HTTP/1.0" 500 1565 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36"
217.182.175.162 - - [01/Nov/2021:16:19:09 -0300] "HEAD / HTTP/1.0" 500 137 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36"
177.104.9.47 - - [01/Nov/2021:16:24:03 -0300] "GET /install HTTP/1.0" 500 1565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
177.104.9.47 - - [01/Nov/2021:16:38:16 -0300] "GET /install HTTP/1.0" 500 1565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
177.104.9.47 - - [01/Nov/2021:16:39:14 -0300] "GET /install HTTP/1.0" 500 1565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
177.104.9.47 - - [01/Nov/2021:16:39:27 -0300] "GET /install HTTP/1.0" 500 1565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
177.104.9.47 - - [01/Nov/2021:16:39:44 -0300] "GET /install HTTP/1.0" 500 1565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
177.104.9.47 - - [01/Nov/2021:16:40:10 -0300] "GET /install HTTP/1.0" 500 1565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
177.104.9.47 - - [01/Nov/2021:16:42:11 -0300] "GET /install HTTP/1.0" 500 1565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
41.212.46.35 - - [01/Nov/2021:16:44:58 -0300] "GET / HTTP/1.0" 500 1565 "https://github.com/WWBN/AVideo/issues/5902" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
41.212.46.35 - - [01/Nov/2021:16:44:59 -0300] "GET /error_docs/styles.css HTTP/1.0" 200 3145 "https://studio.i9ead.com.br/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
41.212.46.35 - - [01/Nov/2021:16:44:59 -0300] "GET /error_docs/server.svg HTTP/1.0" 200 7849 "https://studio.i9ead.com.br/error_docs/styles.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
41.212.46.35 - - [01/Nov/2021:16:44:59 -0300] "GET /favicon.ico HTTP/1.0" 500 1565 "https://studio.i9ead.com.br/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
2a06:98c0:3600::103 - - [01/Nov/2021:16:57:17 -0300] "GET / HTTP/1.0" 500 1565 "-" "DowntimeDetector/4.0 (+https://downforeveryoneorjustme.com)"

Does it make any sense to you?

**Comment by jengajenga** [comment]
Plesk? You can''t have plesk - well you can but i don't think it will work. A fresh root-enabled virgin server.
