### ISSUE TITLE
I can't remove the SUGGEST

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5903]
I can no longer remove the suggest I put on the videos.  Why this anomaly?  Please resolve this issue as soon as possible.  The Star is always lit in orange.  I await an urgent solution.  Thanks Daniel!

[Screenshot_20211101-201626_Samsung Internet.jpg](https://user-images.githubusercontent.com/82677269/139728840-7d9f1168-beeb-47fa-a7ea-f620dc00f685.jpg)

**Comment by DanielnetoDotCom** [comment]
you supposed to click on the button NOT on the icon

![chrome-capture](https://user-images.githubusercontent.com/18009293/139836047-e5c9d45d-f6a0-49bf-b5b1-6ad608c6a2af.gif)

**Comment by DanielnetoDotCom** [comment]
try to make a git pull, clear the cache and try it again

**Comment by sharknetwork24** [comment]
Ok
