### ISSUE TITLE
Auto verify if login social

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#5904]
Hello @DanielnetoDotCom 

Long when i began to use this platform, it was possible for new users who signed up via social media to have their emails auto-verified (especially google).

Now i do not see the setting. i have almost 500 new users who i have to verify manually - very tiring. 

Could you please return that setting where social login's are automatically verified?

Thank you

**Comment by DanielnetoDotCom** [comment]
It supposes to be auto verified I just checked again on the code.

I am not sure what is missing.

**Comment by jengajenga** [comment]
Hmmm, that's interesting @DanielnetoDotCom because i have several that are unverified

![auto-not-verify](https://user-images.githubusercontent.com/65451390/139940644-c4c375b0-1f55-4d38-9760-4744f5b9ad08.jpeg)

these are some of my settings

![auto-not-verify-2](https://user-images.githubusercontent.com/65451390/139940673-a786cfa6-b410-4e46-91ed-e8fc778ed311.jpeg)

![auto-not-verify-3](https://user-images.githubusercontent.com/65451390/139940683-affe36b6-052d-4014-b4d6-16701e6813a1.jpeg)

Is there something else i should be looking at? maybe a setting that i should change?

**Comment by DanielnetoDotCom** [comment]
Are you running the latest git pull?

are those users recently added?

**Comment by Lordblanca** [comment]
Is  there a way to add animation to the new subscriber email and to the verification email?

**Comment by DanielnetoDotCom** [comment]
what type of animation?

do you mean an image?

it probably requires to change the email template that is currently hardcoded

**Comment by jengajenga** [comment]
> Are you running the latest git pull?
> 
> are those users recently added?

git pull is the latest

the new users are from around the 18th of october

**Comment by DanielnetoDotCom** [comment]
not sure what happened. I have to review it.

**Comment by jengajenga** [comment]
ok. please if you can find a solution, i'd appreciate.

thank you

**Comment by jengajenga** [comment]
@DanielnetoDotCom , I fiured this one out. You have to select "forceLoginToBeTheEmail"

Once I did that then verification has become automatic. 

For now I'll close this.
