### ISSUE TITLE
Health check issue

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#5907]
I click "health check" and get this error:

==

array(4) { ["type"]=> int(1) ["message"]=> string(203) "Uncaught Error: Call to undefined function apache_get_modules() in /var/www/xxx/admin/health_check.php:59 Stack trace: #0 /var/www/xxx/admin/index.php(323): include() #1 {main} thrown" ["file"]=> string(44) "/var/www/xxx/admin/health_check.php" ["line"]=> int(59) } array(4) { ["type"]=> int(1) ["message"]=> string(203) "Uncaught Error: Call to undefined function apache_get_modules() in /var/www/xxx/admin/health_check.php:59 Stack trace: #0 /var/www/xxx/admin/index.php(323): include() #1 {main} thrown" ["file"]=> string(44) "/var/www/xxx/admin/health_check.php" ["line"]=> int(59) }

==

Latest git for both streamer and encoder. 

I tried on demo site and it is working. is there something i am doing wrong? Please assist.

Thank you

**Comment by DanielnetoDotCom** [comment]
you are probably running as FPM.
I will send an update to skip this function if you are using FPM

**Comment by jengajenga** [comment]
i am actually using fpm :-)

thanks for the future fix.

**Comment by DanielnetoDotCom** [comment]
apache_get_modules() is only available when the PHP is installed as a module and not as a CGI.

This update should prevent you from this error.

It is not a big deal but we recommend you to use apache as a module NOT as FPM as long as we only test it as a module
