### ISSUE TITLE
No Download link for videos

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5909]
I am trying to allow downloading of videos from the site and to give each user the option to allow share/download of their contents, but when I enable those option I do not see any download link beneath the video. Here are some screen shots:
![Screen Shot 5782-02-27 at 19 11 01](https://user-images.githubusercontent.com/58882903/139913291-507cbf98-a1a2-4ddf-9118-afb3d5ad55ca.jpg)
![Screen Shot 5782-02-27 at 19 11 28](https://user-images.githubusercontent.com/58882903/139913316-59094911-d642-4678-8357-bbd1c2a42d8a.jpg)
![Screen Shot 5782-02-27 at 19 12 02](https://user-images.githubusercontent.com/58882903/139913329-5ab799f7-e907-4656-b06e-fcdf92494c9b.jpg)

Am I missing something?

**Comment by DanielnetoDotCom** [comment]
I cannot guarantee you can download a video from somebody else page

so that is correct, there is no download link for video link

**Comment by jengajenga** [comment]
admin panel -> site settings -> advanced configuration

allow download videos

save

**Comment by DanielnetoDotCom** [comment]
you may want to check this https://github.com/WWBN/AVideo/wiki/Enable-Video-Download

**Comment by guymass** [comment]
Great thanks, now its working like I wanted it to, much thanks. I wanted to have those two checkmarks on the post editor like in the screenshot.

![Screen Shot 5782-03-02 at 11 35 55](https://user-images.githubusercontent.com/58882903/140606098-d56060ee-ea0a-4b48-83e6-4e4d0b4bd299.jpg)
