### ISSUE TITLE
Latency on Video PlayBack

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5910]
Hey Daniel When you can check why the video look they have issue with latency because the sound and video not matching check this video. It out of sync. 

https://musicandstream.com/video/158/dj-herman-live-halloween-mix-on-31-oct-21-19-54-01?channelName=DJHERMAN

**Comment by DanielnetoDotCom** [comment]
I can see a little bid 

make sure you are not transmitting with latency. on AVideo we just record whatever we receive.

**Comment by LATINMIXMASTERS** [comment]
Ok thank you i thought something was wrong. I Appreciate your help and expertise. Keep up the Good Work. 👍🏻
