### ISSUE TITLE
Set thumbnails not showing on live streams

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5912]
![7a0106d0-797a-4557-adf5-0771979c10a0](https://user-images.githubusercontent.com/39392449/139958385-71c60063-fcee-4391-a2a5-30eac7f40b43.png)

**Comment by JoshWho** [comment]
That is all it shows when I turn off Live thumbnails

**Comment by DanielnetoDotCom** [comment]
I can see this on your page now

![image](https://user-images.githubusercontent.com/18009293/140059262-2c495ff7-de8c-4c2d-8ce0-99017328026e.png)

Only one is showing "online" image.

I guess you mean it supposes to show the default image instead of the online one, correct?

**Comment by JoshWho** [comment]
When I turn off live thumbs it does not show the thumbs users have set in
their live dashboard.

**Comment by Lordblanca** [comment]
joshwho how did you add pluto tv to your server. I would love to know.

**Comment by Lordblanca** [comment]
Wow Josh after being on your site for at least an hour. You have a lot to offer the community. I wish you well and may you can share some of your programming knowledge with DanielnetoDotCom to better this open source project. Blessings

**Comment by JoshWho** [comment]
Daniel is the best coder I have seen in the PHP industry. His core code is what makes other stuff easy for me.

**Comment by DanielnetoDotCom** [comment]
@JoshWho do you have a predefined poster on your Live?

![image](https://user-images.githubusercontent.com/18009293/140311756-59917e5e-30a3-4346-b35a-bb93eab423e4.png)

**Comment by JoshWho** [comment]
Yes almost all of them have 1 set. The ones that stream every day have a thumb set.
