### ISSUE TITLE
think it would be great if a live streamer can get  Featured Show ather users click a Featured button 

### ISSUE THREAD

**Issue by antuk21** [WWBN/AVideo#5913]
think it would be great if a live streamer can get a Featured Show when users click the Featured button. 

something  like  this  on this other platform     https://prnt.sc/1y9pnzy   just a idea not a demand :)

**Comment by Lordblanca** [comment]
nice idea

**Comment by DanielnetoDotCom** [comment]
Hi, the idea is not clear to me
