### ISSUE TITLE
TV link

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5914]
How to I access the EPG and TV link. I just did the latest pull and I see it there.. Plus What is the EPG?
![Untitled-1](https://user-images.githubusercontent.com/37937968/140213602-9758e873-2461-4226-b1b1-3f606065ed47.png)

**Comment by Lordblanca** [comment]
@DanielnetoDotCom how do I use the TV link. I want to add an IPtv to my website. Thank you

**Comment by DanielnetoDotCom** [comment]
Currently this still under development and it is a experimental feature, but yes the idea is to work like a IPTV

**Comment by Lordblanca** [comment]
I see Joshwhotv.com is already using the feature. He did some amazing stuff with his site.

**Comment by Lordblanca** [comment]
I see Joshwhotv.com is already using the feature. He did some amazing stuff with his site.

**Comment by Lordblanca** [comment]
Thank you for your time
