### ISSUE TITLE
Personal Business Subdomain Page directly to a users channel

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5915]
This will make it easier for individuals to get their own ad networks enabled for their channel. 

So for example my channel is https://www.joshwhotv.com/channel/SeekingTheTruth

Would be kewl to have a way to map this URL so u can put a sub domain on it like https://SeekingTheTruth.joshwhotv.com
Or you can even offer ability to use their own custom domain for it.

Of coarse the admin would have to set this in apache and for me that is not a problem. In the future it can be automated but right now I am willing to add my own vhost entries for it.

Just for the channel page alone. All the video links on channel page can stay the same. Just need a way for users to be able to claim a virtual property. this will be a huge thing in the future.

**Comment by JoshWho** [comment]
This ties into the Monetize Ad Overlay so they can verify their channel as a website.

**Comment by DanielnetoDotCom** [comment]
I am not sure how to resolve that. maybe a virtualhost or mod rewrite

**Comment by JoshWho** [comment]
I was playing around with some different things last night still no luck. Virtual Host I thought would have did it but the problem is are channel links is not a real document root file to set.

**Comment by JoshWho** [comment]
How can I tell apache there is a virtual path?

**Comment by JoshWho** [comment]
Hey @DanielnetoDotCom  I think I might be on to something check this out on desktop  https://baalbuster.joshwhotv.com/

**Comment by DanielnetoDotCom** [comment]
> Hey @DanielnetoDotCom I think I might be on to something check this out on desktop https://baalbuster.joshwhotv.com/

this is awesome. good job

I guess the way to think about it is like this https://stackoverflow.com/questions/49500/apache-rewrite-based-on-subdomain
