### ISSUE TITLE
Site slow for enter 

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#5916]
Help from today it's slow for enter with pc and phone. 
The page load load load. 

Thank 
![Screenshot_20211104_055029_com android chrome](https://user-images.githubusercontent.com/93554732/140261004-e7141d94-5e0d-4acc-87f7-54e124bf2171.jpg)

After

![Screenshot_20211104_060916](https://user-images.githubusercontent.com/93554732/140261247-25f5f1de-0dcb-466b-8f38-0d0a2c1e819e.jpg)

And after

![Screenshot_20211104_060923_com android chrome](https://user-images.githubusercontent.com/93554732/140261277-eebf00a8-9fd5-4005-9eee-e242356cd381.jpg)

**Comment by DanielnetoDotCom** [comment]
I guess you are having a connection problem at this momment. I could not confirm any connection problem on your server side

**Comment by toplive24** [comment]
Ok thank Neto
