### ISSUE TITLE
How do I Upload a Video?

### ISSUE THREAD

**Issue by minoush82** [WWBN/AVideo#5919]
Hi,

I installed AVideo in my server and I am able to access it. I registered a new user and I want to do the simple thing of uploading a video but I do not seem to be able to find how. I tried these paths:
- Main Menu -> Videos: not a single upload button in sight.
- Main Menu -> My Channel -> Videos (Tab) -> My Videos: I get an error "You can not manage videos".

So, how do I upload? Should it be this hard?

Cheers.

**Comment by DanielnetoDotCom** [comment]
Did you log in as Admin?

check this https://github.com/WWBN/AVideo/wiki/About-Video-Upload

**Comment by minoush82** [comment]
Thank you for your prompt reply :-)

I can upload using admin, but I am unable to upload from a newly-registered user account.

In [1], I show the button I expect in the user account (this is a screenshot from the admin account).
In [2] I show my admin configuration.

Thanks.

[1] Upload button in admin account: [here](https://www.dropbox.com/s/d491r7o1axo0mpw/admin-config.png?dl=0).
[2] Site configuration: [here](https://www.dropbox.com/s/xy2tw3hbfijbqtc/user-config.png?dl=0).

**Comment by jengajenga** [comment]
> Thank you for your prompt reply :-)
> 
> I can upload using admin, but I am unable to upload from a newly-registered user account.
> 
> In [1], I show the button I expect in the user account (this is a screenshot from the admin account). In [2] I show my admin configuration.
> 
> Thanks.
> 
> [1] Upload button in admin account: [here](https://www.dropbox.com/s/d491r7o1axo0mpw/admin-config.png?dl=0). [2] Site configuration: [here](https://www.dropbox.com/s/xy2tw3hbfijbqtc/user-config.png?dl=0).

go to the registered user and use the admin account to allow user to upload.

**Comment by DanielnetoDotCom** [comment]
![chrome-capture](https://user-images.githubusercontent.com/18009293/140518536-c6d8a928-40e0-48f6-83f5-fb8ad6903834.gif)

**Comment by minoush82** [comment]
Thanks. It works now :-)
I have a couple of questions:
1) How can I make any registered user have upload rights automatically without having to enable them manually?
2) Why is upload not enabled by default if this is meant to be a video sharing platform? I mean why would a user use this software and then wait for upload rights?

**Comment by DanielnetoDotCom** [comment]
The default is only Admin can Upload, but on the site configuration menu, you will find an option to let any authenticated users upload the video.

![chrome-capture (1)](https://user-images.githubusercontent.com/18009293/140549084-75252598-70e2-4678-b2ed-97724f940576.gif)

**Comment by minoush82** [comment]
Thanks a lot.
This solves my initial question.
I have been trying a few video-sharing scripts lately, and this is the only one that provides prompt support. So a bunch of thanks for that.
