### ISSUE TITLE
Powered by

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#5920]
By now I got drunk looking for things.
To change the voice Powered by I have seen everything here but I have not yet figured out where to act.

Thanks

![immagine](https://user-images.githubusercontent.com/93554732/140383171-bb57ff4e-be15-4712-acd9-28262dc2486b.png)

**Comment by DanielnetoDotCom** [comment]
Use the customize plugin.

once you make the change make sure you clear the cache.
![chrome-capture (2)](https://user-images.githubusercontent.com/18009293/140388177-3f89a814-f898-44b9-841a-0ff134c96760.gif)

**Comment by toplive24** [comment]
Thank Neto you are my Angel always.
We have big news
