### ISSUE TITLE
Auto play nolonger works after most recent git pull.

### ISSUE THREAD

**Issue by Social-Loafer** [WWBN/AVideo#5922]
Auto play has stopped working after updating.

I see no errors in the log.
Tried on Internet explorer, firefox and brave browser.
Fire fox and brave browser, Getting an endless loop of the circle like it is doing something.
Internet explorer, the video ends and does nothing more.

I did clear all the cache' and regenerated the site map, along with clearing all browser cookies, which changed nothing.

**Comment by Social-Loafer** [comment]
I got the auto next play to work by disabling the autoPlayAjax in the CustomizeAdvanced plugin.
But now nothing autoplays when clicked on and when the player advances to the next video it takes the screen out of Fullscreen.
This is very very annoying.
Is there a way I can role back the sql updates? so i can role the whole installation back to where all these things worked?

**Comment by DanielnetoDotCom** [comment]
This update may resolve the autoPlayAjax

you also may need to update VideoResolutionSwitcher to version 3.5

**Comment by Social-Loafer** [comment]
Can you fix the player also, so it doesnt take it out of fullscreen mode when the videos progress from one video to the next video?

**Comment by DanielnetoDotCom** [comment]
Hi, I just tested it locally and it is playing without leave fullscreen if you are using the autoPlayAjax

**Comment by Social-Loafer** [comment]
Thank you Daniel!
I verified it works as intended now.
Much appreciated!
