### ISSUE TITLE
Fresh install  Stat not working what did i miss?

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5924]
@DanielnetoDotCom sorry to bother you with this as I should know it. 
444 stat not working on fresh install. Been a year since I installed last

**Comment by milehighkaraoke** [comment]
Socket is connected and functional

**Comment by jengajenga** [comment]
mr milehigh, please for your own security, blur out some things. you will compromise your site when posting images such as these.

have you started up the nginx server?

**Comment by milehighkaraoke** [comment]
Yea I deleted  them.... yea nginx is running and ypt socket is connected

**Comment by milehighkaraoke** [comment]
I am busting out another install hopefully I will get the step that I missed

**Comment by milehighkaraoke** [comment]
New install exact same outcome.  I'm really scratching my head.... I have absolutely no idea what I missed. YPT Socket is connected NGINXis on I can not get the 444/stat to work and I do have the listendirectivein NGINXand I configured the live plugin for 444 @DanielnetoDotCom 
![20211105_054905](https://user-images.githubusercontent.com/70327833/140506363-56be4458-7b97-479b-991b-e511d5b5c24d.jpg)

**Comment by DanielnetoDotCom** [comment]
are you sure your Nginx is running?

try to start nginx with `/usr/local/nginx/sbin/nginx`

**Comment by milehighkaraoke** [comment]
Nginx misconfiguration
