### ISSUE TITLE
audio only streaming

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#5927]
@DanielnetoDotCom hi

Is it possible to have audio-only streaming option?

You can implement in 2 ways:

1. in settings "user can stream audio" then it allows only spectrum video with audio (so that user doesn't cheat and stream video) or he can only upload static image where the video would be
2. or in nginx, a setting for audio only then it is only audio player

Thanks

**Comment by DanielnetoDotCom** [comment]
I like the idea, and that is something I will definitely implement in the future.

if you need it right now, I probably can delivery it in one or two weeks, but you need to sponsor the feature.

If you are willing to pay to have it now, please email me at developer@youphptube.com

**Comment by jengajenga** [comment]
i would love to but I'm trying to raise money for the other thing I emailed you about

**Comment by Lordblanca** [comment]
That is a great Idea. This way you can do video stream and radio station at the same time. Make it a plug in. How much will it cost. This will keep you funded and keep this project going
