### ISSUE TITLE
Problem when trying to Sign Into App

### ISSUE THREAD

**Issue by Yoxed** [WWBN/AVideo#5928]
Hello, I have a common everyday problem with my users on the Mobile App

I changed user sign-in from using "user" to "email" which works fine on the website but on the error I am getting on the app is really bad. 

In "user" when you enter your email and there is a space at the end, the app registers that as a character and a lot of users don't know that and it can be very motivating for users. 

It gives an error message saying the user doesn't exist. 

![Screenshot_9](https://user-images.githubusercontent.com/30751181/140508394-f55a34d2-bc54-49d6-b3bc-ef82107ce775.png)
![Screenshot_10](https://user-images.githubusercontent.com/30751181/140508406-9207ea69-6573-4637-94ab-b74656bea602.png)

**Comment by DanielnetoDotCom** [comment]
I am not 100% about this issue. but if the "space" is the problem, this update should resolve this issue.

**Comment by Yoxed** [comment]
Yes the "space" I am awaiting for the new update. Please be advised that I am only getting this issue on the app and not the Website.

**Comment by DanielnetoDotCom** [comment]
I already sent the update, you need to make a `git pull`

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by Yoxed** [comment]
Okay the latest git pull fixed the error I was having thank you.

**Comment by Yoxed** [comment]
One more thing regarding the app, How do I change user to email? So that users wouldn't get confused as to what they are using because I have a much older base of people that's not so much tech savvy
