### ISSUE TITLE
Encoder package 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5930]
@DanielnetoDotCom 
Is there a problem with the newest encoder package?
This is a fresh install on Ubuntu 18.04   I'm using the exact same install procedure as I did a year ago and I am having lots of difficulty that was not present when I installed a year ago. 

Encoder is hanging  on install and not leaving any logs in the encoder video folder.

I am now trying it on 18.04 and getting same results 
![20211105_210239](https://user-images.githubusercontent.com/70327833/140596013-af26caac-9a60-454f-806f-37fbc88cf86b.jpg)

**Comment by milehighkaraoke** [comment]
I did successfully install this about 24 hrs ago so something has changed in the package

**Comment by DanielnetoDotCom** [comment]
I just install one encoder without any problem. please check your apache log

**Comment by milehighkaraoke** [comment]
absolutely nothing
i tried this on 18.04 through 21:10 exact same results
at Nov 06 03:11:43.200847 2021] [mpm_prefork:notice] [pid 31250] AH00163: Apache/2.4.48 (Ubuntu) configured -- resuming normal operations
[Sat Nov 06 03:11:43.200879 2021] [core:notice] [pid 31250] AH00094: Command line: '/usr/sbin/apache2'
[Sat Nov 06 03:13:17.830897 2021] [mpm_prefork:notice] [pid 31250] AH00170: caught SIGWINCH, shutting down gracefully
[Sat Nov 06 03:13:17.980980 2021] [mpm_prefork:notice] [pid 35073] AH00163: Apache/2.4.48 (Ubuntu) configured -- resuming normal operations
[Sat Nov 06 03:13:17.981007 2021] [core:notice] [pid 35073] AH00094: Command line: '/usr/sbin/apache2'
[Sat Nov 06 03:16:09.785675 2021] [mpm_prefork:notice] [pid 35073] AH00170: caught SIGWINCH, shutting down gracefully
[Sat Nov 06 03:16:09.844766 2021] [mpm_prefork:notice] [pid 35137] AH00163: Apache/2.4.48 (Ubuntu) configured -- resuming normal operations
[Sat Nov 06 03:16:09.844792 2021] [core:notice] [pid 35137] AH00094: Command line: '/usr/sbin/apache2'
[Sat Nov 06 03:38:40.471685 2021] [mpm_prefork:notice] [pid 35137] AH00171: Graceful restart requested, doing restart
AH00112: Warning: DocumentRoot [/var/www/MHKTube] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sat Nov 06 03:38:40.488361 2021] [mpm_prefork:notice] [pid 35137] AH00163: Apache/2.4.48 (Ubuntu) configured -- resuming normal operations
[Sat Nov 06 03:38:40.488373 2021] [core:notice] [pid 35137] AH00094: Command line: '/usr/sbin/apache2'
[Sat Nov 06 03:40:20.128445 2021] [mpm_prefork:notice] [pid 35137] AH00171: Graceful restart requested, doing restart
AH00112: Warning: DocumentRoot [/var/www/MHKTube] does not exist
AH00112: Warning: DocumentRoot [/var/www/MHKaraoke] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sat Nov 06 03:40:20.146381 2021] [mpm_prefork:notice] [pid 35137] AH00163: Apache/2.4.48 (Ubuntu) configured -- resuming normal operations
[Sat Nov 06 03:40:20.146392 2021] [core:notice] [pid 35137] AH00094: Command line: '/usr/sbin/apache2'
[Sat Nov 06 03:40:50.682793 2021] [mpm_prefork:notice] [pid 35137] AH00170: caught SIGWINCH, shutting down gracefully
[Sat Nov 06 03:40:50.742154 2021] [mpm_prefork:notice] [pid 37351] AH00163: Apache/2.4.48 (Ubuntu) configured -- resuming normal operations
[Sat Nov 06 03:40:50.742178 2021] [core:notice] [pid 37351] AH00094: Command line: '/usr/sbin/apache2'
[Sat Nov 06 03:41:38.016213 2021] [mpm_prefork:notice] [pid 37351] AH00171: Graceful restart requested, doing restart
AH00112: Warning: DocumentRoot [/var/www/MHKTube] does not exist
AH00112: Warning: DocumentRoot [/var/www/MHKaraoke] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Sat Nov 06 03:41:38.030590 2021] [mpm_prefork:notice] [pid 37351] AH00163: Apache/2.4.48 (Ubuntu) configured -- resuming normal operations
[Sat Nov 06 03:41:38.030601 2021] [core:notice] [pid 37351] AH00094: Command line: '/usr/sbin/apache2'
[Sat Nov 06 03:45:09.605756 2021] [mpm_prefork:notice] [pid 37351] AH00170: caught SIGWINCH, shutting down gracefully
[Sat Nov 06 03:45:09.659921 2021] [mpm_prefork:notice] [pid 38570] AH00163: Apache/2.4.48 (Ubuntu) configured -- resuming normal operations
[Sat Nov 06 03:45:09.659945 2021] [core:notice] [pid 38570] AH00094: Command line: '/usr/sbin/apache2'
[Sat Nov 06 03:45:14.522212 2021] [mpm_prefork:notice] [pid 38570] AH00170: caught SIGWINCH, shutting down gracefully
[Sat Nov 06 03:45:14.582769 2021] [mpm_prefork:notice] [pid 38595] AH00163: Apache/2.4.48 (Ubuntu) configured -- resuming normal operations
[Sat Nov 06 03:45:14.582811 2021] [core:notice] [pid 38595] AH00094: Command line: '/usr/sbin/apache2'
[Sat Nov 06 03:45:18.841249 2021] [mpm_prefork:notice] [pid 38595] AH00170: caught SIGWINCH, shutting down gracefully
[Sat Nov 06 03:45:18.899545 2021] [mpm_prefork:notice] [pid 38660] AH00163: Apache/2.4.48 (Ubuntu) OpenSSL/1.1.1l configured -- resuming normal operations
[Sat Nov 06 03:45:18.899580 2021] [core:notice] [pid 38660] AH00094: Command line: '/usr/sbin/apache2'
[Sat Nov 06 03:45:20.894575 2021] [mpm_prefork:notice] [pid 38660] AH00170: caught SIGWINCH, shutting down gracefully
[Sat Nov 06 03:45:20.957519 2021] [mpm_prefork:notice] [pid 38719] AH00163: Apache/2.4.48 (Ubuntu) OpenSSL/1.1.1l configured -- resuming normal operations
[Sat Nov 06 03:45:20.957547 2021] [core:notice] [pid 38719] AH00094: Command line: '/usr/sbin/apache2'
[Sat Nov 06 03:47:33.080565 2021] [mpm_prefork:notice] [pid 38719] AH00170: caught SIGWINCH, shutting down gracefully
[Sat Nov 06 03:47:33.142007 2021] [mpm_prefork:notice] [pid 38750] AH00163: Apache/2.4.48 (Ubuntu) OpenSSL/1.1.1l configured -- resuming normal operations
[Sat Nov 06 03:47:33.142034 2021] [core:notice] [pid 38750] AH00094: Command line: '/usr/sbin/apache2'
[Sat Nov 06 03:53:51.958467 2021] [mpm_prefork:notice] [pid 38750] AH00170: caught SIGWINCH, shutting down gracefully
[Sat Nov 06 03:53:52.025579 2021] [mpm_prefork:notice] [pid 49973] AH00163: Apache/2.4.48 (Ubuntu) OpenSSL/1.1.1l configured -- resuming normal operations
[Sat Nov 06 03:53:52.025606 2021] [core:notice] [pid 49973] AH00094: Command line: '/usr/sbin/apache2'
[Sat Nov 06 04:34:13.979908 2021] [mpm_prefork:notice] [pid 49973] AH00170: caught SIGWINCH, shutting down gracefully
[Sat Nov 06 04:35:12.417550 2021] [mpm_prefork:notice] [pid 981] AH00163: Apache/2.4.48 (Ubuntu) OpenSSL/1.1.1l configured -- resuming normal operations
[Sat Nov 06 04:35:12.470567 2021] [core:notice] [pid 981] AH00094: Command line: '/usr/sbin/apache2'

**Comment by DanielnetoDotCom** [comment]
I can see the problem now.

make them https


![image](https://user-images.githubusercontent.com/18009293/140607442-45597830-68f0-4ae5-b4ff-c0221bba2131.png)

**Comment by milehighkaraoke** [comment]
Thank you so much... I can't believe I missed  that. . Oh my... thank you thank you thank you!!!!!
