### ISSUE TITLE
Plugin store is off line

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5931]
![20211106_002901](https://user-images.githubusercontent.com/70327833/140600288-e3b600b2-5ff1-48b8-8d8d-e1213e04f51b.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, where did you click to get there?

the correct place is now https://youphp.tube/marketplace/

**Comment by milehighkaraoke** [comment]
I clicked on the redirect on the plugin page then I click on any of the options to buy a plugin  and it takes me to the not found

**Comment by milehighkaraoke** [comment]
![Screenshot_20211106-052547_Samsung Internet](https://user-images.githubusercontent.com/70327833/140607963-22a93af4-fa92-421e-8060-69399246782d.jpg)
![Screenshot_20211106-052553_Samsung Internet](https://user-images.githubusercontent.com/70327833/140607972-ba33f123-3b74-469a-aafa-befb34b419f8.jpg)
![Screenshot_20211106-052600_Samsung Internet](https://user-images.githubusercontent.com/70327833/140607976-605c38bb-2b96-4100-b04a-6c57d44ccbd3.jpg)

**Comment by DanielnetoDotCom** [comment]
Thanks I will fix that
