### ISSUE TITLE
Error log file more than 4478 errors?

### ISSUE THREAD

**Issue by RememberForgottenHits** [WWBN/AVideo#5932]
Server runs Ubuntu 20.04 & it updated and Avideo software is 11.4 version. I did a git pull update yesterday and after that the log is full of the error seen in the images.

How fix it??? I'm can use phpmyadmin,  I have full root access to the server.
![error-log](https://user-images.githubusercontent.com/34457020/140605483-c7dcb968-7529-4c7f-acd3-eb905c5f8bb8.png)
![more4478-errors-in-log](https://user-images.githubusercontent.com/34457020/140605491-fdd3d99b-98b4-414c-8e4b-7a14c0d59b2f.png)

**Comment by DanielnetoDotCom** [comment]
Go to the plugins menu, Cache plugin and install the tables

**Comment by RememberForgottenHits** [comment]
Thanks man, it was easy. However, it was incomprehensible that why this plugin was turned off and the tables had to be reinstalled. Everything worked before. But it is important that everything is in order without any major problems.
