### ISSUE TITLE
Thumbnails are corrput after updating.

### ISSUE THREAD

**Issue by Social-Loafer** [WWBN/AVideo#5933]
I updated from 10.7 and now alot of my thumbnails are corrupt, not sure how that happened.
How can I regenerate all of them?

Also I had to git reset --hard bfca6078, I would like to take it even further back but I applied all the sql updates and dont know how to role them back. Im almost at the point of rebuilding the whole site from scratch back to release 10.7 .
Reason being as the current state of the Current Release is unbearable. autoplayajax no longer works
and autoplay when you have the video full screen and it goes to the next video it takes the video out of full screen.
I tested this on the demo site and it does the same thing.

**Comment by DanielnetoDotCom** [comment]
Check if your paid plugins does not have updates

**Comment by Social-Loafer** [comment]
They are up to date.

**Comment by DanielnetoDotCom** [comment]
also please make sure you update your encoder.

if it persists share a screenshot and also your streamer and encoder logs

**Comment by Social-Loafer** [comment]
Yes the encoder is up to date.
[avideo.encoder.txt](https://github.com/WWBN/AVideo/files/7491150/avideo.encoder.txt)

**Comment by Social-Loafer** [comment]
[avideo1.txt](https://github.com/WWBN/AVideo/files/7491158/avideo1.txt)

**Comment by Social-Loafer** [comment]
![Screenshot_2021-11-06 Inuyasha](https://user-images.githubusercontent.com/62462922/140622519-5922e307-1793-48b0-add8-da786ff47fa1.png)

**Comment by DanielnetoDotCom** [comment]
Hi

I think you may just need to manually delete and let it create again.

try to run it manually to see if there is any error

`ffmpeg    -ss 00:10:00 -i 'http://www.animetube.gn/YouPHPTube/videos/FatestaynightunlimitedBladeWorksEp23Incarnation_6068187a458721.92217298.mp4' -f image2  -s 640x360 -vframes 1 -y /tmp/5b84dee5a7d1b57f5949aa342bacccc1.jpg`

this is basically a FFmpeg error maybe a server reboot may resolve that
