### ISSUE TITLE
Chat is not showing on Live Streams

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5934]
Chat no longer shows up when watching a live stream,

**Comment by JoshWho** [comment]
![aef81e00-765e-4bc9-9f7f-16bc7fcf4bb2](https://user-images.githubusercontent.com/39392449/140626484-8907b00d-6f3f-44fc-af82-cad015ae248a.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, here is a fix

**Comment by JoshWho** [comment]
All fixed thank you Daniel
