### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#5936]
Hello all

Why if you follow the size for upload the background the channel inside upload ok but after show not same?

thank

![immagine](https://user-images.githubusercontent.com/93554732/140638109-cf25113f-31a3-4d6c-995d-aa56c49c63d1.png)

![immagine](https://user-images.githubusercontent.com/93554732/140638140-2f528392-15ba-490e-b427-78c44b2fbd5d.png)

and in the channel this

![immagine](https://user-images.githubusercontent.com/93554732/140639714-cac72caa-4595-4203-9de6-daa806c180fc.png)

**Comment by DanielnetoDotCom** [comment]
Hi , I can confirm the background still need some improvements, we may release this in the future

**Comment by toplive24** [comment]
Ok thank Neto like always.
