### ISSUE TITLE
Make Recorded Streams go to a Static Encoder

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5937]
It would be kewl to use 1 certain encoder just for the recorded live streams. That way it can just handle the bulk encoding while leaving the other encoders available for regular uploads.

Some way to set send to recorder to use a manually entered encoder.

**Comment by JoshWho** [comment]
Bump is this possible?

**Comment by DanielnetoDotCom** [comment]
Sorry, currently the recorder uses the regular encoder URL all your website uses. there is no option for a specific encoder.
