### ISSUE TITLE
Lifetime of a Video from Upload to Viewing

### ISSUE THREAD

**Issue by minoush82** [WWBN/AVideo#5938]
Hello,

I am searching for a document that explains AVideo architecture. In particular, what is happening to a video from its upload by the owner to its streaming to the users.

I read the available pages and found that the video is uploaded using the (streaming) AVideo, and somehow it gets sent to the encoding AVideo - unless a private local encoder is implemented.

My questions are: 
(1) Is my understanding above correct?
(2) Where are the different resolutions of the video stored? Are they stored in the encoding server? In this case, are they fetched in real-time from the encoding server to the streaming server and from there get streamed? Or are they stored in the streaming server right after they are uploaded and encoded by the encoding server? In other words, is the lifetime of a video something like: 
(A) uploaded by owner -> encoded by encoder in different resolutions -> sent to streaming server -> requested by users -> desired resolution is shown from local copy;
or
(B) uploaded by owner -> encoded by encoder in different resolutions -> requested by users -> desired resolution is shown from encoding server;
or perhaps something else?

Thanks.

P.S. At the time of writing this, the page "https://avideo.tube/AVideo_FAQ" is not accessible to me.

**Comment by DanielnetoDotCom** [comment]
> Hello,
> 
> I am searching for a document that explains AVideo architecture. In particular, what is happening to a video from its upload by the owner to its streaming to the users.
> 
> I read the available pages and found that the video is uploaded using the (streaming) AVideo, and somehow it gets sent to the encoding AVideo - unless a private local encoder is implemented.
> 
> My questions are: (1) Is my understanding above correct? 

No, the videos are sent directly to the encoder unless it is a direct upload file

check this https://github.com/WWBN/AVideo/wiki/About-Video-Upload

(2) Where are the different resolutions of the video stored? Are they stored in the encoding server? In this case, are they fetched in real-time from the encoding server to the streaming server and from there get streamed? Or are they stored in the streaming server right after they are uploaded and encoded by the encoding server? In other words, is the lifetime of a video something like: (A) uploaded by owner -> encoded by encoder in different resolutions -> sent to streaming server -> requested by users -> desired resolution is shown from local copy; or (B) uploaded by owner -> encoded by encoder in different resolutions -> requested by users -> desired resolution is shown from encoding server; or perhaps something else?
> 
> Thanks.
> 
> P.S. At the time of writing this, the page "https://avideo.tube/AVideo_FAQ" is not accessible to me.

By default, it is stored on the streamer server

check this https://github.com/WWBN/AVideo/wiki/Storage-Options
