### ISSUE TITLE
Category creation

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#5939]
If you try to create a new category, somehow it increases the total on categories manager but it do not display. 
If you create a fake category, and it succeeded, you then delete it. Then if you try to create another category, the new one appears with data from the previous deleted.
My AVideo is updated to 11.4, with all plugins also updated, including the premiums. I've made a video showing what happens when you delete a category (does nothing), update (does nothing) and create (does not show although it is registered somehow in database):

https://user-images.githubusercontent.com/12404245/140650751-fbd3dc3b-31d2-4f78-b496-4c9bdfaeb0ab.mp4

**Comment by DanielnetoDotCom** [comment]
After create a new category please make sure you clear the cache

**Comment by swimitup** [comment]
Completely forgot about the cache. This solved the problem. Thanks.
