### ISSUE TITLE
Schedule Live Streaming not Sending Notifications 

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5940]
For some reason if you schedule a Live Stream it does not send any notification at all no email or push notifications plus when you are live on the schedule live stream still did not send any notification by email or push notifications. 

Is that normal ?

**Comment by DanielnetoDotCom** [comment]
Correct, there are no notifications yet for the schedule. but it suppose to have something when you start a live

**Comment by jengajenga** [comment]
@DanielnetoDotCom maybe you can integrate with FoxPush https://foxpush.com

It's free :)

**Comment by LATINMIXMASTERS** [comment]
Correct Daniel Supposed to but it did not, also after the live streaming ended and  video finsihed encoding and  moving to CDN storage it sent a push notifications that unknown user upload a video.  So i think something is happening. 

![Screenshot_20211108-111234_Chrome](https://user-images.githubusercontent.com/63973045/140777561-1f5ff6a7-c012-4605-bcd2-3b70af6c7320.jpg)

**Comment by DanielnetoDotCom** [comment]
Regarding the unknown user it is about how you identify the user


The order is 

Name
E-Mail
Username
Channel name

if all above are blank or disabled it will be unknow

check what is disabled on the advancedCustomUser plugin (checked = disabled)

![image](https://user-images.githubusercontent.com/18009293/140793024-6402c016-0154-4423-b6d5-a4deb38be3fb.png)

**Comment by LATINMIXMASTERS** [comment]
Daniel I am Using my account , i posted here just to tell you my account is well set up.

**Comment by DanielnetoDotCom** [comment]
You are correct!

I just sent you updates that may resolve the unknown user

**Comment by LATINMIXMASTERS** [comment]
Ok thank you.
