### ISSUE TITLE
Chat2 Plugin Request or Suggestion?

### ISSUE THREAD

**Issue by Yoxed** [WWBN/AVideo#5941]
Not sure if it's already possible.
The Ability to see all the participants on Chat2.
I see some but not all of them, maybe I can but I am not able to scroll all the way down.
Any ideas on this? I also don't understand the ones that are below the ones that are highlighted green.

![Screenshot_70](https://user-images.githubusercontent.com/30751181/140740918-447aab39-c333-406e-a354-b7be7b318a0f.png)

**Comment by DanielnetoDotCom** [comment]
Thanks for noticing that.

Chat version 7.9 will fix this

**Comment by Yoxed** [comment]
No problem, I will await the new version of Chat2

**Comment by DanielnetoDotCom** [comment]
the new version is available. just download it.

**Comment by Yoxed** [comment]
Okay, I just downloaded the latest version and the update works fine, I am now able to scroll and look for individual participants. Thank you so much once again.
