### ISSUE TITLE
Any plan for Redis ?

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#5942]
The more the project advances , the more it's becoming laggy and very slow to process the queries in time.
Tags, servers location, cache, trending etc etc etc.

Is there any plan to implement Redis for this project? It would be a life time savior.
Queries would be fetched in milliseconds and the most pages would seem preloaded, same with infinite-scroll  

All projects that I'm running on my home lab + hosted externally does support Redis except this one :(

**Comment by DanielnetoDotCom** [comment]
Hi

are you running our latest git pull?

the cache is now on the database

**Comment by akhilleusuggo** [comment]
This still doesn't solve any issue.
Anyway it was a sugestion about redis.

Thanks

**Comment by DanielnetoDotCom** [comment]
Hi, currently I will not use Redis, but I guess the latest git pull (30 min ago) may improve your site a lot 

I missed some details on the cache plugin.
