### ISSUE TITLE
no live/configuration tab

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#5943]
@DanielnetoDotCom hi

For the last 3 or so git pulls i've been missing the live/configuration tab

![no_live_config](https://user-images.githubusercontent.com/65451390/140803490-b9f46f5a-e72c-4b17-a902-00c5eb75f38e.jpeg)

I'm currently on the latest git. 

Thank you

**Comment by DanielnetoDotCom** [comment]
It is not missing, I just removed the video player to avoid confusion. all other resources are there

**Comment by jengajenga** [comment]
> It is not missing, I just removed the video player to avoid confusion. all other resources are there

ok. thanks for the update.

**Comment by partystreamsk** [comment]
Will be good idea at least to put STAT of stream like ONLINE/OFFLINE from stat. So streamer can know if the stream is started successfuly. Daniel?
