### ISSUE TITLE
How to use the Scheduler?

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#5944]
Is there any documentation on how to use the scheduler? Is it for live streams or can it be pre-recorded from our server itself?

**Comment by DanielnetoDotCom** [comment]
If you mean the plugin, it is only used by other plugins, there is nothing for the user

**Comment by CROSSMediaNet** [comment]
Okay...so, what is the purpose for scheduling live streams; or that is possible?

**Comment by DanielnetoDotCom** [comment]
If you mean that 

![image](https://user-images.githubusercontent.com/18009293/141151813-8323daec-1110-4c95-8f1e-dff1e70bd67a.png)

this will schedule a live and you will have a countdown timer on the notification
