### ISSUE TITLE
Live will not connect 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#5946]
Everything seems to be in order but OBS is failing to connect.   @DanielnetoDotCom 
![20211109_005651](https://user-images.githubusercontent.com/70327833/140885325-da4141c4-3ed9-4760-a6e2-2b29185421b5.jpg)
![20211109_005707](https://user-images.githubusercontent.com/70327833/140885326-0579dcb7-445d-4051-ac50-fbab01479646.jpg)
![20211109_005724](https://user-images.githubusercontent.com/70327833/140885327-0f43b98b-6785-4b6a-abff-5c939f7e6eee.jpg)
![20211109_005827](https://user-images.githubusercontent.com/70327833/140885328-54048ce7-a786-4d94-91eb-af53288549fa.jpg)
![20211109_005851](https://user-images.githubusercontent.com/70327833/140885330-8bce1442-0be9-48f9-9291-c38f5706d311.jpg)
![20211109_005911](https://user-images.githubusercontent.com/70327833/140885331-c0d7e75c-f782-4953-95be-c2d7838fac93.jpg)
![20211109_010006](https://user-images.githubusercontent.com/70327833/140885332-6662f9fb-2e04-4fff-b1c3-f68d8a7e3a0c.jpg)

**Comment by milehighkaraoke** [comment]
I believe it's populating incorrect url key

**Comment by DanielnetoDotCom** [comment]
what do you have in your nginx.conf?

check if your on_publish is accessible from your server.

https://github.com/WWBN/AVideo/blob/a900e6d7af16795aa371a2e057cc73844889509e/plugin/Live/install/nginx.conf#L29

for example `curl -v http://localhost/AVideo/plugin/Live/on_publish.php;`

make sure your `HTTP/1.1` response is not a 404 error (401 Unauthorized Error is expected)

```

# curl -v http://localhost/AVideo/plugin/Live/on_publish.php;
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> GET /AVideo/plugin/Live/on_publish.php HTTP/1.1
> Host: localhost
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized Error
< Date: Tue, 09 Nov 2021 13:27:42 GMT
< Server: Apache/2.4.29 (Ubuntu)
< Set-Cookie: key=value; secure; SameSite=None
< Set-Cookie: 84b11d010cced71edffee7aa62c4eda0=2ea0b3820299a105bd923aca86869316; expires=Tue, 09-Nov-2021 14:27:42 GMT; Max-Age=3600; path=/
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: max-age=1, private, must-revalidate
< Pragma: no-cache
< Set-Cookie: yptDeviceID=c0c36cdf-a1d6-4bd1-a186-b3d4a4919439; expires=Wed, 09-Nov-2022 13:27:42 GMT; Max-Age=31536000; path=/; domain=localhost; secure; SameSite=None
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Methods: GET,HEAD,OPTIONS,POST,PUT
< Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
< Vary: Accept-Encoding
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< 
* Connection #0 to host localhost left intact
```

**Comment by milehighkaraoke** [comment]
Well this is strange. I have always used the same nginx config by copy and paste. I changed the ip addresses in publish, record etc. To mhktube.com now it works. Any idea why it was not working this time with those same ip addresses?

**Comment by milehighkaraoke** [comment]
I think I might have forgotten to disable the apache site. Either way it's working now... thank you

**Comment by milehighkaraoke** [comment]
Changing it to the domain name caused other issues  so I changed it back to the IP addresse of the server and did a
sudo a2dissite 000-default.conf

Now it's all functional.
Thanks for pointing me in the correct direction....

**Comment by milehighkaraoke** [comment]
The live identification is showing 0 even though I am broadcasting. It is broadcasting because it is live on the embedded player on my web page. Ypt socket is on and functioning. @DanielnetoDotCom any ideas because  it does show a 1 when I start the broadcasting and it comes up on the site. After I broadcast for a few minutes it goes back to 0

**Comment by milehighkaraoke** [comment]
#
![Screenshot_20211109-232612_Samsung Internet](https://user-images.githubusercontent.com/70327833/141061964-2788d163-1ae5-4dad-bf0d-575c1a7cd7f8.jpg)

**Comment by DanielnetoDotCom** [comment]
I am pretty sure this 0 will only update when you refresh the page
