### ISSUE TITLE
can't upload more than one video

### ISSUE THREAD

**Issue by shirank26** [WWBN/AVideo#5947]
I try to upload 2 videos, the system loads them but after clicking save changes, the system uploads one video only . In the settings I can upload a maximum of 20 files at one time in 8GB size, now I tried to upload 2 files in 300 MB size,
 the version is AVideo version 11.3

**Comment by DanielnetoDotCom** [comment]
sorry, but the issue is not clear to me.

are you using the encoder?

**Comment by shirank26** [comment]
Do I have to use an encoder to upload several videos together?

**Comment by DanielnetoDotCom** [comment]
the direct upload is one video at a time

use the encoder is always better https://github.com/WWBN/AVideo/wiki/About-Video-Upload
