### ISSUE TITLE
Chat2 button (ver 7.6)

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#5948]
![chat-button](https://user-images.githubusercontent.com/65451390/140907620-34770eac-c416-4236-a591-1a02442dab90.jpeg)

@DanielnetoDotCom , can you put the option of having the chat button on the bottom right of the screen and **not** inside the video player itself? Then the chat2 opens like normal and **not** inside the video player?

that way, it doesn't ruin the experience when trying to watch while chatting.

**Comment by DanielnetoDotCom** [comment]
Hi, I am thinking to remove the other layouts and keep only the **static fixed on right**, so I strongly recommend you to use that layout. can you please check if the **static fixed on right** does not works properly for you

![image](https://user-images.githubusercontent.com/18009293/140921905-1235a972-ea37-4d97-b13c-4ba60b03dbd9.png)

**Comment by jengajenga** [comment]
It works.  But it's the round button I want. Can you put such that when you minimize you get the round button? and then when you click on the round button it opens as static fixed on right?

![round](https://user-images.githubusercontent.com/65451390/140923328-f959197f-fa5a-4c0e-8b14-aa48344a6433.jpeg)

this one is very high up and i have noticed that my viewers tends to click on my facebook icon (bottom left of screen) to chat instead of using the chat. the facebook icon is for customer service but the viewer thinks he is chatting with the channel.

![fb-icon](https://user-images.githubusercontent.com/65451390/140923916-400ae1fe-66ec-4925-bd8e-1f59e2bd0855.jpeg)


so i wanted the round button on the bottom right  so that the viewer doesn't make that mistake.

**Comment by DanielnetoDotCom** [comment]
do you mean when it is minimized to show a circle button at the bottom instead of the bar with the user's list?

**Comment by jengajenga** [comment]
> do you mean when it is minimized to show a circle button at the bottom instead of the bar with the users list?

EXACTLY! :-)

**Comment by DanielnetoDotCom** [comment]
We will have something like that on the next version
