### ISSUE TITLE
Blackblaze Videos Not working

### ISSUE THREAD

**Issue by Yoxed** [WWBN/AVideo#5949]
This started happening ever since I did the latest githull. I also realized that all of my video files got upload to my local storage and blackblaze but the site say "Local" But now my videos are not playing when I upload with the plugin enabled but if i upload with the plugin disabled it works fine. I had to delete all of my videos.

![Screenshot_72](https://user-images.githubusercontent.com/30751181/140925006-6c3526f4-f92c-4344-8033-68b3b4bfd51e.png)

![Screenshot_73](https://user-images.githubusercontent.com/30751181/140925024-3b984841-7cfa-4c31-8d57-9d7dd7ad34de.png)

**Comment by DanielnetoDotCom** [comment]
can you please share a video link with me?
I would like to inspect something

**Comment by Yoxed** [comment]
I just uploaded this one 
https://realmediatt.com/video/48/no-soe-and-curfew-at-the-end-of-the-month?channelName=Coff

**Comment by Yoxed** [comment]
As you can see aswell the Storage says Local 
![Screenshot_77](https://user-images.githubusercontent.com/30751181/140927284-f0cdb765-012c-440a-b264-a3679fb1208b.png)

**Comment by DanielnetoDotCom** [comment]
Hi, regarding the video above

the local storage is not an issue. this only changes when you use YPTStorage or CDNStorage

your video source is pointing to https://realmediattcom.cdn.ypt.me/videos/video_211109124413_va1f5/video_211109124413_va1f5_240.mp4 what is not the Backblaze CDN and it is pointing to this https://realmediatt.com/videos/video_211109124413_va1f5/video_211109124413_va1f5_240.mp4

your backblaze should be 

https://realmediattcomb2.cdn.ypt.me/video_211109124413_va1f5_240.mp4 

https://f002.backblazeb2.com/video_211109124413_va1f5_240.mp4

I can see your video does not exist on backblaze.

also something is wrong on the file transfer

The file https://realmediatt.com/videos/video_211109124413_va1f5/video_211109124413_va1f5_240.mp4 is a bummy file (10 bytes file)

https://f002.backblazeb2.com/video_211109124413_va1f5_240.mp4 is not on backblaze, so I guess 

1. maybe https://f002.backblazeb2.com/ is not your end point.
2. what is your bucket name?
3. can you please confirm your backblaze endpoint and if the file was transfered to your bucket?

**Comment by Yoxed** [comment]
Bucket Name: realmediattvideos
Yes the file got transferred to the bucket

**Comment by Yoxed** [comment]
Maybe this can help

![Screenshot_78](https://user-images.githubusercontent.com/30751181/140933357-37c665d2-0eef-4458-9a34-2f44a6fc44f7.png)

**Comment by DanielnetoDotCom** [comment]
thanks this helps a lot

but I guess I just find out.

you have the CDN plugin enabled but you have no balance on your account. 

please add more balance or disable the CDN plugin.

**Comment by Yoxed** [comment]
Thank you for the help, Daniel. He helped me out with this issue. 
I needed to recharge my CDN and I purchased the CDN Storage which works amazing! Thanks for all the help.
I am no longer using Backblaze, I am having a much better experience with the youphptube CDN storage. 
You can see the prices here - https://youphp.tube/marketplace/CDN/iframeTemplate.php
