### ISSUE TITLE
The video cannot be played after moving the video storage

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#5950]
The video cannot be played after moving the video storage
![image](https://user-images.githubusercontent.com/47063171/140952044-9aa7233a-d897-4dcc-ba4c-b6fa71758bb1.png)
![image](https://user-images.githubusercontent.com/47063171/140952574-4f5f9c6a-3cd5-4890-aac8-30dd1219a14f.png)

**Comment by DanielnetoDotCom** [comment]
I am away from pc now but can you please share the video links so I can inspect ?

**Comment by chenjian9885** [comment]
Demo station (demo.avideo.com), test link:https://demo.avideo.com/video/369/max-kellerman-explains-his-issue-with-aaron-rodgers-comments-about-covid-19-vaccine-status-%7C-kjm

**Comment by DanielnetoDotCom** [comment]
An error on the VIdeoResolution plugin, it is fixed now, please check
