### ISSUE TITLE
Live Stream Tab Video Not Showing & Donation link missing after update to chat 7.9 and Git Pull

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5951]
Just updated latest chat to 7.9. And now the live stream tab to monitor the live stream is no longer there. 
![Streaming-monitor-tab-missing](https://user-images.githubusercontent.com/37937968/140968956-75768ee3-e13d-4bb8-a80a-4ebfbf2113f8.png)

When opening  in web browser. I see that the donation link is gone in the chat. And already restarted server.
![Doantion-link-missing](https://user-images.githubusercontent.com/37937968/140970716-4b3e6f3e-7682-4eb1-a3aa-3764f7584f59.png)

**Comment by Lordblanca** [comment]
DanielnetoDotCom can we fix this problem? that last update removed key features

**Comment by DanielnetoDotCom** [comment]
Hi, I just checked on my side and I could see the donation link.

maybe the problem is something else 

check this ...

![image](https://user-images.githubusercontent.com/18009293/141352959-a830d3f8-0bd1-4533-8fe5-9900b74dc131.png)

and this 

![image](https://user-images.githubusercontent.com/18009293/141353070-4212be97-98ea-48c2-89be-49b9eee3074b.png)

**Comment by DanielnetoDotCom** [comment]
Regarding the player on the live configuration ...

Please check this https://github.com/WWBN/AVideo/issues/5943

**Comment by Lordblanca** [comment]
Wow, Can we have an option to have the tab or not. It is a great way to verify if we are connected or not.

**Comment by DanielnetoDotCom** [comment]
sorry no. the player on the configuration was complex and useless. only confuse people.

**Comment by Lordblanca** [comment]
wow. If I paid separate to have it put back in for me. How much

**Comment by DanielnetoDotCom** [comment]
Can you please tell me exactly what you need?

a tab with the player on the live configuration page?
