### ISSUE TITLE
Thumbnails of vertically filmes clips too wide

### ISSUE THREAD

**Issue by gunthor-hammerwurf** [WWBN/AVideo#5952]
As the title says, thumbnails of vertically filmed clips are too wide.

Video:
![grafik](https://user-images.githubusercontent.com/83225309/141087803-320698c9-a9ac-4b95-89ca-ea5fa6a62305.png)

Thumbnail:
![grafik](https://user-images.githubusercontent.com/83225309/141087862-9c5fcc0e-1890-47ca-9a0c-f7b962a20695.png)

This also applies to the preview thumbnails in the video:
![grafik](https://user-images.githubusercontent.com/83225309/141088195-14b8a185-74f5-4c0b-b0d1-38516eab36b0.png)

_Credits for the video go to [leopARTnik](https://www.instagram.com/leopartnik/)_

Even though chubby ducks are quite funny, this unfortunately also applies to serious videos in the format of 9:16.
It also happens on the demo site.

**Comment by DanielnetoDotCom** [comment]
It is a known issue. we still need to improve the encoder to create thumbs for portrait videos.

we for sure will add this in some future versions.
