### ISSUE TITLE
How to remove bounce effect when page loads

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#5953]
As the title says how to remove bounce effect when page loads. Need to have a choice of fade in bounce or nothing at all

**Comment by DanielnetoDotCom** [comment]
On what page are you referring to? all?

why do you want to remove it?

**Comment by Lordblanca** [comment]
I liked it simple or at least give me a choice of bounce or no bounce

**Comment by DanielnetoDotCom** [comment]
Now you can remove the animations with the disableAnimations on the customizeAdvanced plugin parameters

**Comment by Lordblanca** [comment]
Thank you
Before I do any more updates
Is the missing live stream tab in the live stream section fixed?

**Comment by DanielnetoDotCom** [comment]
Hi

I have no intention to put the live player with the configuration. it only confuses people.
