### ISSUE TITLE
Chrome displays "vertical" preview GIF incorrectly

### ISSUE THREAD

**Issue by aolvictim** [WWBN/AVideo#5956]
When user uploads a vertical video and preview was generated. In Chrome the preview shows "squashed" but in Safari it display correctly. I noticed Chrome loads `webp` format but Safari loads `gif` format for the preview. See screenshots below:

Chrome:
<img width="269" alt="Chrome" src="https://user-images.githubusercontent.com/7109995/141237145-c0bfdbfa-941c-4aa9-987f-11e7157fb91b.png">

Safari:
<img width="244" alt="Safari" src="https://user-images.githubusercontent.com/7109995/141237173-163492da-5d7b-4c34-b92e-bfeb032d3a15.png">

The page that has the example video:
https://hudll.com/?showOnly=dateAddedOrder

**Comment by aolvictim** [comment]
Looks like it's this line that serves `gif` to Safari and `webp` to everyone else:
https://github.com/WWBN/AVideo/blob/master/objects/video.php#L2914

I can think of two solutions:
- Make the encoder output correct `webp` preview for vertical/portrait videos (preferred)
- Just use GIF for portrait preview

**Comment by DanielnetoDotCom** [comment]
Hi, 

duplicated https://github.com/WWBN/AVideo/issues/5952
