### ISSUE TITLE
Change image Article

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#5957]
Hello i need change image of article why the image of default its non much beautiful.

I create new who help me?
thank

![article_portrait](https://user-images.githubusercontent.com/93554732/141366959-028aace7-4adc-46bb-94e5-ddd2e4d2d8c9.png)
![article](https://user-images.githubusercontent.com/93554732/141366964-e2d9c1a6-1d23-41a7-a71e-c820a4659773.png)

**Comment by DanielnetoDotCom** [comment]
I can change the folder permission for you then you will be able to use FileZilla to upload the images.
but be aware if you change those images you may lose your modifications if you need to update the site.

change any core file is not recommended.

**Comment by toplive24** [comment]
and therefore we can not make changes even just for the images?

**Comment by DanielnetoDotCom** [comment]
not those images

**Comment by toplive24** [comment]
I am probably ignorant of some things but it seems impossible to me that we cannot even replace images with the same name and extension, I understand intervening on the code side, but at least the images.

**Comment by toplive24** [comment]
Solved
