### ISSUE TITLE
Website don't sent nothing 

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#5962]
It hasn't been sending notifications for registered users for uploaded videos for a few days, nor has it sent a verification email, not even a test email.

**Comment by DanielnetoDotCom** [comment]
Hi, 

you must set up your site to send emails. https://github.com/WWBN/AVideo/wiki/Setting-up-AVideo-Platform-to-send-emails

In my opinion, the best option is to use the Gmail SMTP, check this https://tutorials.avideo.com/video/82/setup-gmail-smtp-with-2fa

**Comment by toplive24** [comment]
It's setup ok
Neto sorry, if I have a domain don't need use Gmail it's not professional when go to the user one email oh Gmail.

Solution?

**Comment by DanielnetoDotCom** [comment]
Yes, for myself I use this free solution https://github.com/WWBN/AVideo/wiki/Setting-up-AVideo-Platform-to-send-emails#set-up-email-forwarding

**Comment by toplive24** [comment]
I understand you but I want use email of domain, I don't touch nothing but now don't sent nothing,

**Comment by DanielnetoDotCom** [comment]
Please read the links I sent you above.

SMTP is one thing that has nothing to do with your "professional email"

SMTP is only a service to send your email, the sender will always be the one you configure on your site, so your users will never know you are using the gmail SMTP

![image](https://user-images.githubusercontent.com/18009293/141473530-347ffd47-0f23-4548-af48-edfb969131c3.png)

**Comment by toplive24** [comment]
I try
