### ISSUE TITLE
Home page popup or Welcome popup

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5963]
It would be nice to have the ability to choose to display a home page or welcome popup window with any HTML content we want to show and only show it once per session. In that way we can inform users of any important details first time they visit or once per active session.

**Comment by DanielnetoDotCom** [comment]
We have a similar thing with the SignUpAgreement Plugin https://github.com/WWBN/AVideo/wiki/SignUpAgreement-Plugin

**Comment by guymass** [comment]
OK thanks that should do the trick.
