### ISSUE TITLE
Marketplace Wrong plugin version.

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5965]
Hi Daniel
Urgent request for the correct plugins.
You need to upload the correct versions.
https://youphp.tube/marketplace/
The VideoResolutionSwitcher and Notification plugins are downloaded from the Marketplace version 1.0 only.
I need versions:
VideoResolutionSwitcher v.3.6
![000](https://user-images.githubusercontent.com/82677269/141492147-53a072c0-6293-4911-a7fe-f10476bb30e5.PNG)

Notification v.3.0
![001](https://user-images.githubusercontent.com/82677269/141492170-9445d77d-9482-4f94-b15b-42ada6eff124.PNG)

I kindly ask you to insert the updated versions for download.
Thanks and I await your reply.

**Comment by DanielnetoDotCom** [comment]
you have to download them from the marketplace 

if you do not have access, email me your user# from the marketplace site and I will enable the plugins for you

https://youphp.tube/marketplace/

**Comment by sharknetwork24** [comment]
> you have to download them from the marketplace 
> 
> if you do not have access, email me your user# from the marketplace site and I will enable the plugins for you
> 
> https://youphp.tube/marketplace/

My account is active and so is the plugin.  I should download version 3.0 and download version 1.0 instead.  I should download version 3.6 and download version 1.0 instead.  Daniel kindly can you check which versions you have uploaded?  Thanks

**Comment by DanielnetoDotCom** [comment]
Thanks , you are correct, please download them again now

**Comment by sharknetwork24** [comment]
> Thanks , you are correct, please download them again now 

Ok thanks
