### ISSUE TITLE
"Extra" folders in "videos" folder

### ISSUE THREAD

**Issue by aolvictim** [WWBN/AVideo#5966]
**Describe the bug**
I notice the `videos` has "extra" folders created. Are those correct behavior?

<img width="211" alt="Screen Shot 2021-11-12 at 9 11 32 AM" src="https://user-images.githubusercontent.com/7109995/141511692-ef7fec56-2caf-4827-91ae-91d0de9f3afa.png">

**Comment by DanielnetoDotCom** [comment]
Looks like this is related to this issue https://github.com/WWBN/AVideo/issues/5961

but I could not reproduce it. can you please describe exactly what you did so I can try to reproduce it here?

**Comment by aolvictim** [comment]
I notice I can replicate this problem when I import certain Youtube videos. 
Here is an example: https://www.youtube.com/watch?v=1ruCFtzohh8 caused that behavior.

After trying a few times, the symptoms I observed was the videos take a long time to encode. And ultimately not able to completely send all the files back to the streamer site.

**Comment by aolvictim** [comment]
The import is finished and these folders were generated for that video:

```
video_211112181653_v58e5
    |- video_211112181653_v58e5_480.mp4
    |- video_211112181653_v58e5_720.mp4
    |- video_211112181653_v58e5_thumbsSprit.jpg

video_211112181653_v58e5_1080.mp4
    |- video_211112181653_v58e5_1080.mp4
```

Here is the relevant log from the streamer (I use `grep` to filter the log for useful info): 

I compare the difference of logs between the `480`, `720` against the `1080` files and I noticed something interesting: the streamer received the 1080 file twice. 

### The first time it receives it, the `video` object is:
```
{
    "video": {
        "name": "avideoTmpFile_161_streamers_id_12__1080.mp4",
        "tmp_name": "\/var\/www\/html\/AVideo\/videos\/cache\/tmpFile\/avideoTmpFile_161_streamers_id_12__1080.mp4"
    }
}
```
and then:
`AVideoLog::DEBUG: decideMoveUploadedToVideos: destinationFile /var/www/html/AVideo/videos/video_211112181653_v58e5/video_211112181653_v58e5_1080.mp4 filesize=10 (10 bytes) SCRIPT_NAME: /objects/aVideoEncoder.json.php`
 
### But the second time the `video` object is only:
```
{
    "video": {
        "tmp_name": "\/tmp\/YTPChunk_TTLgKA"
    }
}
```
and :
`AVideoLog::DEBUG: decideMoveUploadedToVideos: destinationFile /var/www/html/AVideo/videos/video_211112181653_v58e5_1080.mp4/video_211112181653_v58e5_1080.mp4 filesize=10 (10 bytes) SCRIPT_NAME: /objects/aVideoEncoder.json.`

### So I cross reference the encoder log
And I noticed that the encoder received a `524 Origin Time-Out` error for the first attempt to send the `1080` version so it tried again. **But the second time it's not sending the correct data along with the file. And I think that's the real cause of the problem.**

Here is the encoder log: [youtube_import.log](https://github.com/WWBN/AVideo/files/7531241/youtube_import.log)

**Comment by DanielnetoDotCom** [comment]
I guess I found something. can you please check this update?

**Comment by aolvictim** [comment]
Yes it's fixed. Thanks
