### ISSUE TITLE
Preview is not seen

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5968]
Daniel can you help me understand where the problem lies?
On the timeline below the video from PC Browser I don't see the preview image.
From android browser it works.
From Android application it works.
Why doesn't it work from a PC with all Google chrome, Edge and Firefox browsers?
Thanks, I await your reply.

https://user-images.githubusercontent.com/82677269/141530558-9df21501-6a02-494c-a1cc-e45b45efaf5b.mp4

**Comment by DanielnetoDotCom** [comment]
Try to clear the cache on the site

**Comment by sharknetwork24** [comment]
> Try to clear the cache on the site 

Already done but still not working.

**Comment by DanielnetoDotCom** [comment]
can you please share the video link here?

**Comment by sharknetwork24** [comment]
> can you please share the video link here?

Daniel happens with all the videos.  Check for yourself with videos of your choice.

https://sharktube.info/

**Comment by DanielnetoDotCom** [comment]
Maybe something on your PC, I just tried here and works fine at the first attempt 
![chrome-capture](https://user-images.githubusercontent.com/18009293/141585175-4c4de593-0ee8-40cb-acd2-8e4331c79c90.gif)

**Comment by sharknetwork24** [comment]
Thanks Daniel.  
Now I'm sure everything works. 
I'll do some checks on my PC.
