### ISSUE TITLE
Embedding YT video is getting stuck

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5969]
It just stays on this

![b8f3e096-f4a8-4017-826e-2e2ac8ab50cb](https://user-images.githubusercontent.com/39392449/141531973-bd35dad9-51ba-4fdd-883e-4b7156a7a393.png)

**Comment by DanielnetoDotCom** [comment]
Can you please describe what steps you are doing and what links you are using?

**Comment by JoshWho** [comment]
Just the regular embed option with this link 
https://youtu.be/7_LZIZQo7oo

**Comment by JoshWho** [comment]
Also After embedding it will give just a blank black thumbnail and will not let me upload a new poster for it. It just errors when I try to upload one.

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by JoshWho** [comment]
It still just sits like it is waiting for something
![e3092d27-6d2a-4e83-b743-ebcf9a0d98dd](https://user-images.githubusercontent.com/39392449/141908342-00dd48d4-00a2-43a0-bee4-9dae1bce40f3.png)

If I refresh the page the embed is there now it just seems like the embedder doesn't ever close

**Comment by DanielnetoDotCom** [comment]
I just added the provided link on the demo site with no problem https://demo.avideo.com/video/367/the-overview-of-the-kershaw-concierge

check your log files, also your JS console log
