### ISSUE TITLE
Start Self hosted WebRTC server..

### ISSUE THREAD

**Issue by nikstream** [WWBN/AVideo#5970]
Hi Daniel
Does  Self hosted WebRTC server works on the same server now ..
As I Tried on which nginx and AVideo are already install but getting Socket error..
![Webrtc_ServerError](https://user-images.githubusercontent.com/58296408/141535453-3b209717-5f44-43c2-b7aa-bceed6b17d73.PNG)
.
Followed the wiki And PHP Command
php /var/www/html/AVideo/plugin/Live/standAloneFiles/WebRTCServer/server.php

**Comment by DanielnetoDotCom** [comment]
Not working yet, sorry

**Comment by nikstream** [comment]
Thanks for your prompt reply...
But are we going to try for it in future...
