### ISSUE TITLE
Thumbnail generation is not using the 1280 defined setting in CustomAdvance 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5971]
![cc0ecf72-6b17-4583-adfa-876be855eb00](https://user-images.githubusercontent.com/39392449/141543700-d00eb0fc-1189-4d72-aa51-248039055086.png)

These thumbnails are tiny for some reason

**Comment by JoshWho** [comment]
The weird part about this is these are videos some from 2 years ago, They use to have full size thumbnails, did something regenerate them?

**Comment by DanielnetoDotCom** [comment]
there is a minimum image size, it the provided thumbs is smaller then the minimum we add the black border

probably youtube-dl is only getting the small resolution ones

**Comment by JoshWho** [comment]
This is doing it just to the Youtube imported vids.  When looking at the thumb in the video manager it looks fine, Even on the big Video on the home page looks fine but when looking at it regular size it seems as if it is zoomed out.

**Comment by JoshWho** [comment]
I can confirm it is all thumbnails that get generated by the plugin making them look small

![262e239a-4f6b-4e81-a056-acda8512fdac](https://user-images.githubusercontent.com/39392449/143892727-decace7f-6a6d-415c-ae69-11cd728df1f4.png)

**Comment by JoshWho** [comment]
When I manually upload a 1280x720p it looks fine. I just changed it to the
settings the demo uses and I do not see any change

**Comment by DanielnetoDotCom** [comment]
when you change it it will not reflect on the thumbs that are already created.

you will need to manually delete the thumbs and let the script generate again.

> When I manually upload a 1280x720p it looks fine.

Looks fine because the script does not neet to over size it.

**Comment by JoshWho** [comment]
What made all my old thumbs from 2 years ago change? All the generated
thumbs are like this old and new

**Comment by DanielnetoDotCom** [comment]
probably this feature was not working before. and now it is working with the proper size.

**Comment by JoshWho** [comment]
It is only when the videos r being listed like On the homepage or on the side you see the thumb really
![f8511ae1-28f6-4d10-9777-63d6cc46aadc](https://user-images.githubusercontent.com/39392449/145346814-614983a4-ed73-4e0f-bb77-cd224bd9402d.png)
 small but when viewing it from the video play page it looks fine.

**Comment by JoshWho** [comment]
THis is the image URL on the video playback page that looks correct https://static7.joshwho-cdn.com/videos/video_211202193511_vd48a/video_211202193511_vd48a.jpg

This is the one that is zoomed out  https://static11.joshwho-cdn.com/videos/video_211202193511_vd48a/video_211202193511_vd48a_thumbsV2.jpg

**Comment by DanielnetoDotCom** [comment]
> I can see now
> 
> you are forcing 1280x720 on your thumbs, but the original file is not that big, that is why your black bars.
> 
> you should reduce it (I guess it is on customizeAdvanced plugin)
> 
> https://static420.joshwho-cdn.com/videos/video_211129001600_v503c/video_211129001600_v503c_thumbsV2.jpg
> 
> For example, the tutorials site thumbs are 500x280
> 
> https://tutorialsavideocom.cdn.ypt.me/videos/video_210910202753_4487/video_210910202753_4487_thumbsV2.jpg

Reduce the resolution and your thumbs will be fine

**Comment by JoshWho** [comment]
those r 2 different images

**Comment by JoshWho** [comment]
It is using the new V@ thumbnail instead of the old thumbnail's and they r zoomed out

**Comment by JoshWho** [comment]
Old one https://static420.joshwho-cdn.com/videos/video_211129001600_v503c/video_211129001600_v503c_thumbsV2.jpg
New one https://tutorialsavideocom.cdn.ypt.me/videos/video_210910202753_4487/video_210910202753_4487_thumbsV2.jpg

**Comment by JoshWho** [comment]
![971c3668-674e-4e22-b39d-bbdee318805f](https://user-images.githubusercontent.com/39392449/145444401-84a9e4df-88d7-42ce-9000-290aeb5fa578.png)
![download (4)](https://user-images.githubusercontent.com/39392449/145444427-8c57885b-226a-4a17-839e-f7bae03f0a88.png)

**Comment by JoshWho** [comment]
Whatever this change was changed all my video thumbs that were generated. Old ones from 2 years ago all the way up to now.

**Comment by JoshWho** [comment]
They looked fine before the V2 change

**Comment by JoshWho** [comment]
Seem like the Thumb Gen is only making the Canvas the right size and not the image in the middle of the canvas

**Comment by JoshWho** [comment]
Any way we can tell it to regenerate new thumbs?

**Comment by DanielnetoDotCom** [comment]
did you delete the thumbs after you changed the size?

after changing the plugin parameter you MUST delete the thumbs, so the script will recreate it.

**Comment by DanielnetoDotCom** [comment]
Thus thumb still looks large for me

https://x.joshwho-cdn.com/videos/video_210718211707_3026/video_210718211707_3026_thumbsV2.jpg 

1280x720 pixels

delete it and let the script regenerate

**Comment by JoshWho** [comment]
There is way too many videos to try to update that way. Is there a script I can run that will just regenerate the old video thumbs?

**Comment by DanielnetoDotCom** [comment]
There is a script to delete all the thumbs.

https://github.com/WWBN/AVideo/blob/master/install/deleteThumbsFiles.php

if you run 

`php deleteThumbsFiles.php` the script will delete all thumbs

if you add 1 as a parameter 

`php deleteThumbsFiles.php 1` the script will delete the corrupted thumbs only (we do our best to check it)

https://github.com/WWBN/AVideo/blob/bba84f6f6c8f0af4d42662cba3e58f5816dadd4c/objects/functions.php#L7635-L7645

you probably can modify this script to delete only the old ones.

try to copy the create an SQL and interate where the id < 100 for example.
