### ISSUE TITLE
yt-dl is very slow

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#5972]
It is very very slow.

Is it something we can fix or is it a youtube thing? because even a 4 minutes video is taking an hour to transfer.

**Comment by JoshWho** [comment]
YT is now throttling any connections that do not prove you are a real browser

**Comment by jengajenga** [comment]
> YT is now throttling any connections that do not prove you are a real human on a real browser

sigh...

**Comment by JoshWho** [comment]
Basically YTDL needs to make their bot a little more human to resolve this

**Comment by jengajenga** [comment]
there's this fix whihc i tried.. doesn't seem to work

https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-967772871

**Comment by JoshWho** [comment]
It worked for me surprisingly. It is a Human test I knew it. A java file that wasn't getting called by the agent. 

Generate a ytdl by running this

`wget https://github.com/ytdl-org/youtube-dl/archive/20fc43475289bd3335e5f96a8e0d8f5432f1d806.zip
unzip 20fc43475289bd3335e5f96a8e0d8f5432f1d806.zip
cd youtube-dl-20fc43475289bd3335e5f96a8e0d8f5432f1d806
sudo pip install .
`

then copy that into your original youtube-dl folder in /usr/local/lib/python2.7/dist-packages

**Comment by JoshWho** [comment]
@DanielnetoDotCom  check this out

**Comment by JoshWho** [comment]
also if your IP banned you can install proxychains

`apt install proxychains
`

Then add 

`$global['youtube-dl'] = 'proxychains youtube-dl';
`

to your Encoders config file

**Comment by jengajenga** [comment]
HA! let me try

> It worked for me surprisingly. It is a Human test I knew it. A java file that wasn't getting called by the agent.
> 
> Generate a new ytdl by running this
> 
> ```
> wget https://github.com/ytdl-org/youtube-dl/archive/20fc43475289bd3335e5f96a8e0d8f5432f1d806.zip
> unzip 20fc43475289bd3335e5f96a8e0d8f5432f1d806.zip
> cd youtube-dl-20fc43475289bd3335e5f96a8e0d8f5432f1d806
> sudo pip install .
> ```
> 
> then copy that into your original youtube-dl folder in /usr/local/lib/python2.7/dist-packages

i  did the install but i didn't do the copying. let's see.

**Comment by jengajenga** [comment]
> It worked for me surprisingly. It is a Human test I knew it. A java file that wasn't getting called by the agent.
> 
> Generate a new ytdl by running this
> 
> ```
> wget https://github.com/ytdl-org/youtube-dl/archive/20fc43475289bd3335e5f96a8e0d8f5432f1d806.zip
> unzip 20fc43475289bd3335e5f96a8e0d8f5432f1d806.zip
> cd youtube-dl-20fc43475289bd3335e5f96a8e0d8f5432f1d806
> sudo pip install .
> ```
> 
> then copy that into your original youtube-dl folder in /usr/local/lib/python2.7/dist-packages

so @JoshWho , do i copy what's inside that folder to the oiginal ytdl folder?

**Comment by jengajenga** [comment]
> HA! let me try
> 
> > It worked for me surprisingly. It is a Human test I knew it. A java file that wasn't getting called by the agent.
> > Generate a new ytdl by running this
> > ```
> > wget https://github.com/ytdl-org/youtube-dl/archive/20fc43475289bd3335e5f96a8e0d8f5432f1d806.zip
> > unzip 20fc43475289bd3335e5f96a8e0d8f5432f1d806.zip
> > cd youtube-dl-20fc43475289bd3335e5f96a8e0d8f5432f1d806
> > sudo pip install .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then copy that into your original youtube-dl folder in /usr/local/lib/python2.7/dist-packages
> 
> i did the install but i didn't do the copying. let's see.

well what'd'you know! issaworking! :)

thanks for the copying tip

**Comment by jengajenga** [comment]
@DanielnetoDotCom i found the fix, @JoshWho impelmented it.

So now you can incorporate it.

**Comment by DanielnetoDotCom** [comment]
> @DanielnetoDotCom i found the fix, @JoshWho impelmented it.
> 
> So now you can incorporate it.

Just update your encoder and follow this https://github.com/WWBN/AVideo/issues/5972#issuecomment-967806736

you should be able to do the same on your side

**Comment by jengajenga** [comment]
> > @DanielnetoDotCom i found the fix, @JoshWho impelmented it.
> > So now you can incorporate it.
> 
> Just update your encoder and follow this [#5972 (comment)](https://github.com/WWBN/AVideo/issues/5972#issuecomment-967806736)
> 
> you should be able to do the same on your side

proxychains didn't work for me.

i went with the yt-dlp option instead. it works like a charm.

**Comment by JoshWho** [comment]
I can vouche for that. I installed the yt-dlp and added that to my encoders config and WOW it is fast importing from Youtube again!!!!!!!!!!

**Comment by JoshWho** [comment]
> > > @DanielnetoDotCom i found the fix, @JoshWho impelmented it.
> > > So now you can incorporate it.
> > 
> > 
> > Just update your encoder and follow this [#5972 (comment)](https://github.com/WWBN/AVideo/issues/5972#issuecomment-967806736)
> > you should be able to do the same on your side
> 
> proxychains didn't work for me.
> 
> i went with the yt-dlp option instead. it works like a charm.

Yes Proxychains just got patched well TOR got patched. It does still work if you are ip banned and have your own socks proxies but this new dlp thing is the best working solution I have seen.

**Comment by JoshWho** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/39392449/145727279-1051b03f-919a-4dc2-aeb3-3b1e06b65c36.gif)

**Comment by JoshWho** [comment]
Add this to your encoder's config file

`$global['youtube-dl'] = 'yt-dlp ';`

**Comment by JoshWho** [comment]
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/39392449/145734100-5dde556e-beb5-4d49-8e53-f442d3e84af0.gif)
