### ISSUE TITLE
Move logo and how to delete

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#5973]
Hi Daniel, can you tell me how to remove the logo?

Is there a possibility to move it to another location?  If it is possible, tell me how to do it?  Thanks

![Screenshot_20211113-084417_SharkTube.jpg](https://user-images.githubusercontent.com/82677269/141610707-52caa67c-c39c-4e26-9ebe-c4412f9fdee2.jpg)

![Screenshot_20211113-085156_SharkTube.jpg](https://user-images.githubusercontent.com/82677269/141610801-c5bb3290-1f87-4719-b48f-dc95e132829d.jpg)

**Comment by DanielnetoDotCom** [comment]
disable the VideoLogoOverlay plugin
