### ISSUE TITLE
New error on one of my encoders

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5974]
[13-Nov-2021 03:42:10 America/Chicago] sendFileChunk: we found errors on video file (/var/www/html/YouPHPTube/Encoder/videos/avideoTmpFile_10_streamers_id_5__HD.mp4) we will not transfer it
[13-Nov-2021 03:42:10 America/Chicago] Encoder::run: Autodelete Not active

**Comment by DanielnetoDotCom** [comment]
This is a ffmpeg check if some video resolution have some error we do not transfer it (because the file will not be playable )

**Comment by JoshWho** [comment]
Says somthing about moov file not found and was looking into that and just found out the latest ffmpeg no longer supports +fastart  it now just uses plain fastart

**Comment by DanielnetoDotCom** [comment]
can you please share more about your logs so I can see where exactly has the +fastart error?

**Comment by JoshWho** [comment]
ever since i took the plus out I havent seen the moov missing error i think that corrected that

In the latest version of ffmpeg (3.x+ or 4.x+), the correct syntax is -movflags faststart indeed (without the + sign). See
https://ffmpeg.org/ffmpeg-formats.html#Options-8

**Comment by DanielnetoDotCom** [comment]
here is an update to the encoder. I hope it does not break anybody else encoder

**Comment by DanielnetoDotCom** [comment]
please update, and test, and confirm to me if it makes any difference

**Comment by JoshWho** [comment]
I did looks like one of the videos that said broken files is now working.

**Comment by DanielnetoDotCom** [comment]
Humm, so the +faststart corrupts your videos and did not transfer them to your streamer. and now it is working fine?

**Comment by JoshWho** [comment]
Looks like so far I see new uploads and they r all showing working now. Could have been it. Not 100% though

**Comment by DanielnetoDotCom** [comment]
the +faststart is there for a while, I am not sure why it starts to fail now.

**Comment by JoshWho** [comment]
Same. Not sure either. I am gonna close this thread for now.
