### ISSUE TITLE
Encoder 2 Locked error

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#5975]
Hi,
I'm trying to encode a video on https://encoder2.avideo.com/
There is an encoding locked there on the site: https://artindera-video.com/

![image](https://user-images.githubusercontent.com/37880073/141644522-997c9e92-4962-4cb5-aa45-fbf36a9ee550.png)

**Comment by DanielnetoDotCom** [comment]
thanks, removed the bad download from queue
