### ISSUE TITLE
This is idea for the TV guide EPG thing Add a m3u8 playlist extension to every channel

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5977]
Just like every channel has a RSS feed at the end of the channel url is there a way to make a playlist file of all the videos of that channel?

Make the channel playlist of all videos able to be added to the TV guide for a 24/7 stream that loops

THen this playlist could be used on all sorts of devices including Roku and other smart apps

**Comment by DanielnetoDotCom** [comment]
I guess we already have that 

![image](https://user-images.githubusercontent.com/18009293/141825576-0d28fbf4-48d8-41c0-9823-fdb394cef996.png)

**Comment by JoshWho** [comment]
Sweet I have to figure out a way users can stream line this. There is no references to these links for bot discovery other than the rss one. 

How can this be added to the TV guide? and How to make m3u8 playlist file auto polpulate the TV guild and TV Channels

**Comment by JoshWho** [comment]
When trying to get my roku link it hangs

https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json

**Comment by JoshWho** [comment]
I just submitted my channel to roku and made a tutorial here: https://www.joshwhotv.net/2021/11/16/joshwho-tv-is-now-roku-ready-add-your-channel-to-roku-today/
