### ISSUE TITLE
Direct upload and encoder

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#5980]
@DanielnetoDotCom hi

I have 2 questions

1. Is it possible to have direct mp4 upload but still have the encoder break it down to different resolutions?

if that is not possible, then

2. Is it possible to switch off the Import Video section in the encoder?

Thanks

**Comment by DanielnetoDotCom** [comment]
> @DanielnetoDotCom hi
> 
> I have 2 questions
> 
> 1. Is it possible to have direct mp4 upload but still have the encoder break it down to different resolutions?

to do so you have to upload your video to the encoder, not to the streamer

> 
> if that is not possible, then
> 
> 1. Is it possible to switch off the Import Video section in the encoder?
> 

Add this to your configuration.php file 

`$global['disableImportVideo'] = 1; ` 

 This will hide the import video tab

https://github.com/WWBN/AVideo-Encoder/wiki/Configuration.php-variable-(-some-are-hidden-)

**Comment by jengajenga** [comment]
thanks. these have worked.
