### ISSUE TITLE
Donation icons on the App 

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5981]
Will be good to have same features on the Mobile app as the website example the Donation icon and way to add money so people can donate thru app because only way now will be thru website and is a little hassle. Hope this can be done in near future.

**Comment by DanielnetoDotCom** [comment]
Hi, 

I cannot have all the features right the way on the mobile, but for sure we will implement all as we can when it is solid.

the donation button should appear on the Chat when you are on the mobile.

**Comment by LATINMIXMASTERS** [comment]
Well on the chat does not show the icon i was looking for it but not i have both of mine selected the donation thru website and also the donation link but only showing on the website not on the mobile app chat

![Screenshot_20211115-145153_Music and Stream](https://user-images.githubusercontent.com/63973045/141845081-06dc387e-2558-45f2-ac44-eae1a8032c2b.jpg)

**Comment by DanielnetoDotCom** [comment]
Please check if you have the donation enabled https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform#donations

**Comment by LATINMIXMASTERS** [comment]
Yes they are , only working on website not showing in mobile app chat.

**Comment by DanielnetoDotCom** [comment]
Hi, Chat2 version 8.0 may resolve that.

**Comment by LATINMIXMASTERS** [comment]
When that update came out? After you did the my platform?

**Comment by LATINMIXMASTERS** [comment]
Ok

**Comment by LATINMIXMASTERS** [comment]
Hey Daniel I only see one donation bottom where is the other one ?

**Comment by DanielnetoDotCom** [comment]
what other button are you referring to?

**Comment by LATINMIXMASTERS** [comment]
You have two donation  bottom tha you put your link adn one that people send mo ey using their wallet. See pucture above

**Comment by LATINMIXMASTERS** [comment]
So When you can please check about the second donation bottom , using the wallet .
