### ISSUE TITLE
I tried fixing someones live stream and after I clicked save it made their live stream go to my admin account

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5982]
After correcting someones settings in their live stream I clicked save and now they r broadcasting as the admin

**Comment by JoshWho** [comment]
https://www.joshwhotv.com/live/1/Zzzz?live_servers_id=1&c=Zzzz&u=zadmin&parentsOnly=1&leaveChannel=1

**Comment by JoshWho** [comment]
this is not correct. We need a way to log in to accounts as admin this is not working

**Comment by JoshWho** [comment]
seems like My admin account took over their stream key, I fixed it by resetting the admins key.

**Comment by jengajenga** [comment]
I realised this a long time ago. Only the user has access to his account. Any other attempt will result in what happened to you.

personally i would call the client and tell them to reset their key and save then restart their stream.

**Comment by DanielnetoDotCom** [comment]
how did you access somebody else settings? from what screen?

**Comment by JoshWho** [comment]
As admin I clicked on Live Info on one of their videos
![7d440711-7209-4d08-80ad-7af9f8c1d5ad](https://user-images.githubusercontent.com/39392449/141900730-7162dc69-92f6-445c-93c9-e1ddbd004d1c.png)

**Comment by DanielnetoDotCom** [comment]
Thanks for noticing it. 

this update may resolve that

**Comment by JoshWho** [comment]
Thank you Daniel
