### ISSUE TITLE
Unable to play uploaded videos but I can play live

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#5983]
@DanielnetoDotCom good morning

I'm not able to play any videos that i have uploaded via the encoder and also those using direct upload.

Latest git on both streamer and encoder. Live is playing but uploads are not.

Any help?

Thank you

**Comment by DanielnetoDotCom** [comment]
Share a video link here.

also, make sure the video is on the videos folder

**Comment by jengajenga** [comment]
> Share a video link here.
> 
> also, make sure the video is on the videos folder

@DanielnetoDotCom thanks. please allow me to send the link via email but you can respond here.

And yes the videos are in the videos folder inside their own specific folders

**Comment by jengajenga** [comment]
@DanielnetoDotCom I've sent an email with the title similar to the title of this thread

**Comment by DanielnetoDotCom** [comment]
I guess you are missing the apache xsendfile

https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

**Comment by jengajenga** [comment]
> I guess you are missing the apache xsendfile
> 
> https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

you genius! :) 

i had it installed but had forgotten to configure it. thanks for the link. it's now playing as it should.

i'm closing this and trying the yt-dlp one. 

thanks again.
