### ISSUE TITLE
Bug thumbnail poster

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#5985]
Hi,

I would like to know why there are videos that I added that the thumbnail is exposed to the portrait poster, whereas in others the thumbnail is the frame I uploaded. Why is there this difference and how to correct it?

One suggestion... the image named "poster", couldn't it be called "banner"?

![image](https://user-images.githubusercontent.com/37880073/141846172-2d9f7258-fe68-4420-b71c-ac3c33a91949.png)

**Comment by DanielnetoDotCom** [comment]
the best way is to make sure you upload the poster on the correct aspect ratio: 16:9

and upload it to the correct proposal...
![chrome-capture (2)](https://user-images.githubusercontent.com/18009293/141847876-79298208-3699-41b5-ac39-ed44416e414c.gif)

**Comment by gbrn** [comment]
Hi Daniel,
Ok for 16:9 format. But the problem I presented is that the images are not generated correctly, check:
https://drive.google.com/file/d/12Ar_m1hGEtiOZ2FocayyzGen4w0Z5kJ2/view?usp=sharing

In addition to the problem I presented, I believe the definition of poster is ambiguous. I understand that "POSTER PORTRAIT" is the vertical image.
And "POSTER LANDSCAPE" the horizontal image would be the best definition. It can also be understood as a BANNER.

**Poster Portrait**
![image](https://user-images.githubusercontent.com/37880073/142081841-1fe9781b-cc07-4518-9f8b-840241afd9c3.png)

**Poster Landscape**
![image](https://user-images.githubusercontent.com/37880073/142081609-e282534b-a789-4a30-aade-fd102b702471.png)

**Comment by DanielnetoDotCom** [comment]
I mean landscape works better with 16:9

the portrait also 9:16

but the video you shared I can see only the poster when you edit the video the poster is overlapping. but how it looks like on the front page?

**Comment by gbrn** [comment]
Hi Daniel,

On the first page the image displayed is the image I selected.
As I showed this image... the first file presents an image in Landscape and in the second file in the sequence, a poster of a movie in portrait appears. Both files I uploaded the same way. Only poster images that are different. I don't understand why they are treated differently, I have several other examples like this on my system.
![image](https://user-images.githubusercontent.com/37880073/142714848-df104244-22dd-4931-b73e-5bb61e6d87c9.png)

**Comment by gbrn** [comment]
Daniel,

I have been having problems with the images. After making a post, the images are not updated.
I need to understand what the thumbnail updates routine is. Is there an update rule?

![image](https://user-images.githubusercontent.com/37880073/145682472-2836dd43-7814-4145-b227-d4895b37f977.png)

**Comment by DanielnetoDotCom** [comment]
did you update the portrait image?

![image](https://user-images.githubusercontent.com/18009293/145684022-09d6f6c3-e49d-452c-963a-de3ead976c61.png)


If yes, try to clear the cache after the image update

**Comment by gbrn** [comment]
See the problem... because this has this difference:

No Login:
![image](https://user-images.githubusercontent.com/37880073/145688778-b4cd1853-43f3-4031-96e0-99c28b8392a3.png)

After login:
![image](https://user-images.githubusercontent.com/37880073/145688791-83753858-620e-49f6-be0f-ed4544458a23.png)

**Comment by DanielnetoDotCom** [comment]
so the problem is not clear to me.  I am not sure what you are complaining about.

**Comment by gbrn** [comment]
Daniel, I checked instabilities for the display of images.
In the previous example, a background image is displayed for when you are not logged in and after I login the image changes.
I'm always depending on cache cleaning to update images, don't you have an automatic feature?

Please. Don't take it as a complaint, I'm more trying to help make the system more robust for everyone.

**Comment by DanielnetoDotCom** [comment]
Let me see if I understand.

you updated the image and it does not update right the way on the main page. is that what you mean?

but when you clear the cache it displays correct?

the first page has a timeout. if you do not clear it will be updated after whatever you defined on cacheTimeInSeconds

![image](https://user-images.githubusercontent.com/18009293/145817072-5d86ec57-6b54-41e7-b1d9-152fe3425c2b.png)

**Comment by gbrn** [comment]
Hi Daniel, Caching is not enabled. Is this a problem for me? When Plugin Cache is not enabled, does it follow any other standard?

![image](https://user-images.githubusercontent.com/37880073/145841223-67063e43-3690-4c1f-8cf4-994f369adbd7.png)
