### ISSUE TITLE
Mobile App Push Notification taking users to Website

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#5986]
For Some Reason all push Notifications that users are getting , sent the users to the website instead of opening the app and taking them to that area of the push notification. I have a lot of users complaining why the have an app if the push notifications send them out of the app hope this can be fix.

**Comment by LATINMIXMASTERS** [comment]
Any update on why user receiving the push notifications on the app takes them to website instead opening the app to watch the video or live stream??

**Comment by DanielnetoDotCom** [comment]
Correct. for now is not possible to open the links directly into the app

**Comment by LATINMIXMASTERS** [comment]
So instead of having links i think is best reciving on the push saying the upload a new video because is real confusing for users that have the app and recived the push notifications and then the push notifications send them  out of the app

**Comment by LATINMIXMASTERS** [comment]
I think for push notifications will be best to open the app not to send then to website because the. The mobile app is not doing the function since everyone is going outside the app.

**Comment by DanielnetoDotCom** [comment]
I 100% agree with you

it may be changed in the future.
