### ISSUE TITLE
Problem with `git pull` latest commit at Windows-based systems

### ISSUE THREAD

**Issue by Maikuolan** [WWBN/AVideo#5987]
**Problem with `git pull` latest commit at Windows-based systems.**

In https://github.com/WWBN/AVideo/tree/master/plugin/CDN/tools, there are two files which, with the exception of the casing for one of the letters, are the same: `findMIssingEncKeys.php` and `findMissingEncKeys.php`.

For Linux and others with similar file systems, this shouldn't be a problem. But, for Windows and others with similar file systems, this will be a problem, because the file system will treat these two files as being the same file, which means that, when performing a `git pull`, when Git attempts to update the files to their latest versions, one of these two files will automatically overwrite the other, causing Git to mistakenly believe that the file has been modified, even though it has only just been updated by Git itself.

I would recommend renaming at least one of these two files to something else.

**Comment by DanielnetoDotCom** [comment]
Done, thanks
