### ISSUE TITLE
Automatically Unlist any video that is missing its mp4 files or Thumbnails 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5989]
We need a way to make non working videos not public including ones missing Thumbnails.

It is a eye sore to people browsing the site when others keep doing it.

![64042ad8-5e38-42ad-aa79-114ed84c480c](https://user-images.githubusercontent.com/39392449/142147697-fdcca9f5-0658-4e28-b4bb-baf741310bae.png)

**Comment by jengajenga** [comment]
I agree with this. I once had 22 videos looking like that. 

this would be a good fix.

**Comment by DanielnetoDotCom** [comment]
That is the idea about the "missing files" flags

but maybe your video is not working for another reason.

missing thumbnails I disagree is a reason to hide it.

**Comment by JoshWho** [comment]
The default thumb is a eye sore though. It makes the site look not professional when there is a bunch of videos like that

**Comment by DanielnetoDotCom** [comment]
any idea to replace that thumbs?

**Comment by JoshWho** [comment]
I am thinking, the problem is it is just 1 thumb any way to have like 10 different ones that can alternate? Or maybe make it static thumb images that it will just randomly use until a image replaces it spot.

I am not sure. I really think the best solution is to just make it unlisted until the user completes it. As of right now this is going to cause a lot of laziness and no one will be willing to fix their thumbnails.

**Comment by DanielnetoDotCom** [comment]
but to make unlisted is the video owner option

currently we do not have an option to force you add a thumbs

**Comment by JoshWho** [comment]
I c
