### ISSUE TITLE
Auto play next video will not disable on embed videos

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#5990]
We have a channel which embeds its videos on their site and when the video ends it will start a next video randomly from our site.
The problem is that we disabled that on the plugin but on their videos it still shows there is some video on the next play and when I try to remove it by clicking the red button it doesn't do anything. The channel wishes  that no other videos will be played after theirs are ended.

Here is a screen shot of one of their videos in the editor:
![Screen Shot 5782-03-13 at 18 41 08](https://user-images.githubusercontent.com/58882903/142244113-2a5e4bbb-fc10-4999-b70b-2147607a6179.jpg)

So I am not sure if this is something with the EMBED code or in the plugin. We would like to be able to disable that option if needed for some channels and allow it for those who use it or don't mind that other videos will be playing, but we hardly use this option although we should.

So how can we disable that for them?

Also on PlayerSkin the option for autoplay is disabled.
![Screen Shot 5782-03-13 at 19 01 12](https://user-images.githubusercontent.com/58882903/142246910-559de783-0a5a-41b1-b117-4b407b64bceb.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, autoplay is a cookie option. 

can you please clear the cookie and check if the error persists?

also can you please share here an embedded code sample so I can make sure about my answer?

**Comment by guymass** [comment]
Hi Daniel, im reopening this issue as I see this still bothers some of our channels embedding their own content. Here is an example of such embed code:


<div class="embed-responsive embed-responsive-16by9"><iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="https://live.ahava528.com/vEmbed/11421" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no">iFrame is not supported!</iframe></div>

**Comment by DanielnetoDotCom** [comment]
Check what do you have here 

![image](https://user-images.githubusercontent.com/18009293/151208259-631c611c-e666-40b5-9efc-9ce0b7e5200b.png)

**Comment by guymass** [comment]
OK in my case this was on, I have disabled it now and we will check if this solves the issue, much thanks.

**Comment by thiagoalecs** [comment]
I have same issue, embed auto play is disable everywhere, cookies have ben cleared and still. when embeded video is over, it search for a next randon video and auto play. but in Avideo demo works fine, can you help me find this settings?

**Comment by DanielnetoDotCom** [comment]
Please share here your embed page 

and also describe what behavior are you expecting
