### ISSUE TITLE
Latest Gitpull Made the homepage crazy

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5991]
![5d47129e-87de-45a7-bfdf-ef1c8e53dc03](https://user-images.githubusercontent.com/39392449/142253439-d8f01887-9502-475a-8cd7-671f1c2b3cfc.png)

**Comment by JoshWho** [comment]
could be the promoted channels I dont know but I cant fix it

**Comment by DanielnetoDotCom** [comment]
checking your server now

**Comment by JoshWho** [comment]
Looks like you fixed it

**Comment by DanielnetoDotCom** [comment]
you were missing this 

![image](https://user-images.githubusercontent.com/18009293/142254472-b48ea811-bafe-4b3b-83dc-4bac71fff4f6.png)

Also, all your plugins were updated. all seems to be fine for me

**Comment by JoshWho** [comment]
ahhhhh I didn't see that. Thank you @DanielnetoDotCom
