### ISSUE TITLE
Video Active while it is encoding

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5992]
![075f8f97-f0ca-4daf-bf13-3b0f32fbaa93](https://user-images.githubusercontent.com/39392449/142268605-3d86d0a0-964e-4d25-b222-cfd4a09954ec.png)

**Comment by JoshWho** [comment]
It is letting you watch the raw file I see while it is still encoding. Id this what is is suppose to do?

**Comment by DanielnetoDotCom** [comment]
I guess it does not suppose to happen, but would be a good feature to let you watch while it is encoding other formats

**Comment by JoshWho** [comment]
That is what I am thinking. I kinda like it. I just hope it isn't causing issues.
