### ISSUE TITLE
AVideo App for local IPs ?

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#5993]
I'm trying to run the AVideo app ( the free version on google store ), but it doesn't seem to work.
All I get is checking the site, but no response back.

### Details ;

Using self-signed SSL ; No errors, but also nothing happens ( at the least not visible )

Trying without SSL ( http ), getting errors :

![Screenshot_20211117-203155_Avideo Platform](https://user-images.githubusercontent.com/52116577/142272151-8aab9bcb-c3d2-41b4-bf39-47d1f455b01f.jpg)

EDIT : Is mainly for debugging/ local use / testing purposes.

**Comment by DanielnetoDotCom** [comment]
I just tested it on iPhone and works, and I guess it is an android limitation to make requests. 

Please double-check if you are on the same network

**Comment by akhilleusuggo** [comment]
Yes, I can confirm that I am on the same network.
The SSL maybe you're right, that android does not allow self-signed certs ( I have imported mine ).

But still not working, as you can see, the error bellow without SSL


The check site, what it does ? Does it go outsite of the local network ? Does it need to ping or ask some request to avideo.com? etc ?

**Comment by DanielnetoDotCom** [comment]
Not really. it works for me on my internal network
