### ISSUE TITLE
How can I add a new page?

### ISSUE THREAD

**Issue by LIBERTYLIBRART** [WWBN/AVideo#5994]
I want to add a custom page. How do I do that? I have the custom menu plugin but the amount of code I need to insert isn't acceptable. Clues?

**Comment by DanielnetoDotCom** [comment]
Hi

If you want to add web pages with information I recommend you to use a WordPress site with that information, but you also can use the TopMenu to create custom pages 

https://github.com/WWBN/AVideo/wiki/How-to-use-TopMenu-Plug-in

![chrome-capture (6)](https://user-images.githubusercontent.com/18009293/142631918-d926c604-705d-4489-81bd-39e886916474.gif)
