### ISSUE TITLE
Request - Aussie flag

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#5995]
I got this message today, I think it is about the wallet but not sure if this is a necessary thing maybe just the conversion table would be good to have.

11/17/21, 2:15 AM Request - Aussie flag added to joshwhoTV account flat system
Request - Aussie flag added to joshwhoTV account flat system
https://en.wikipedia.org/wiki/Flag_of_Australia
https://en.wikipedia.org/wiki/Flag_of_Australia#/media/File:Flag_of_Australia_(converted).svg
Also UK missing
Thanks

**Comment by DanielnetoDotCom** [comment]
The Australian flag/translation was a copy of the US translation. fell free to add any other different translation

**Comment by JoshWho** [comment]
Sweet. Thank you.
