### ISSUE TITLE
Cannot authenticate to our LDAP server via the LDAP Plugin

### ISSUE THREAD

**Issue by mcorvo** [WWBN/AVideo#5998]
Dear all,

hope you can help me solve this issue with the LDAP Plugin we've recently bought. Setup:

- Avideo running in a Docker container based on Ubuntu:latest
- Apache reverse proxy running on the VM hosting the docker containers
- ldap server reachable from the container, that is I can execute ldapsearch commands on it
- php7.4-ldap module installed

I followed the instructions, but I keep getting a "errno: 32" message from the server. These are my attempts:

1) define the LDAP server in the plugin form as ldap://myldapserver.it with port 389
2) define the rdn as follows: uid={$user},ou=People,dc=infn,dc=it

![media-ldap-2](https://user-images.githubusercontent.com/9268893/142616705-4eac9d23-8456-42f5-9484-c72b2f5ce725.png)

but the answer is always:

[19-Nov-2021 10:38:45 Europe/Berlin] AVideoLog::DEBUG: Password check new hash user not found SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php
[19-Nov-2021 10:38:45 Europe/Rome] AVideoLog::DEBUG: LDAP BIND fail: 32: No such object SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php

Then I tried to change the rdn to: cn={$user},ou=People,dc=infn,dc=it
but I still get the same error. 

To debug the issue I used a small php script which performs a simple ldap_bind:

 ```
  ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);
   $ds=ldap_connect($ldap)
           or die("Cannot connect");
   $ldapbind=false;
   if(ldap_set_option($ds, LDAP_OPT_PROTOCOL_VERSION, 3))
      if(ldap_set_option($ds, LDAP_OPT_REFERRALS, 0))
         if(ldap_start_tls($ds))
               $ldapbind = @ldap_bind($ds, $usr, $pwd);
   ldap_close($ds);
   
```

In this case $ldap is the same ldap server URL I use in the AVideo plugin form and for $usr I tried several solutions:

1) uid=myusername,ou=People,dc=infn,dc=it and my ldap password **-> doesn't work**. This is formally the same setup I used at the very biginning with the LDAP plugin.
2) cn=myusername,ou=People,dc=infn,dc=it and my ldap password **-> doesn't work**. Same attempt also with the LDAP plugin.
3) infnUUID=alphanumeric string,ou=People,dc=infn,dc=it and my ldap password -> **IT WORKS** 

Notice that this infnUUID=xxxx,ou=People,dc=infn,dc=it is the DN returned by a simple query to the ldap server and looking for my username, that is:

`ldapsearch -x  -H ldap://myldapserver.it:389 -b "ou=people,dc=infn,dc=it" -s sub 'uid=myusername'`

If I try to execute an authenticated query like

`ldapsearch -x -D "infnUUID=XXXXXXXXXXX,ou=People,dc=infn,dc=it" -W -H ldap://myldapserver.infn.it -b "ou=people,dc=infn,dc=it" -s sub 'uid=myusername'
`
I get the expected results.

At this point my guess was to try with the AVideo LDAP plugin and this DN, so I modified the configuration as visible in the following screenshot:

![media-ldap-3](https://user-images.githubusercontent.com/9268893/142616988-cf681a0b-f7ba-411e-8857-2554e792c38f.png)

But to my surprise, I got again the same error as before. To be sure, I also tried putting infnUUID={$user} , as shown in the attached screenshot, and then providing in the login form the same long alphanumeric string returned in mt DN, but got always the same "errno: 32" error.

![media-ldap-4](https://user-images.githubusercontent.com/9268893/142617084-1905eab2-0937-4ba5-8121-a0489d1cbdc3.png)

Is there something really stupid I'm doing wrong? Or is it a subtler issue?

Thanks in advance for any advices!

**Comment by DanielnetoDotCom** [comment]
Hi, 

let me use your working sample

**Comment by mcorvo** [comment]
Hi Daniel,

thanks for your reply. 

Yes, I tried with just {$user} as rdn, but didn't work. 

Just to clarify, here's the complete snippet of php code. The authentication works with the first $usr (the one with infnUUID) and does not with the second (uid=MYUSERNAME). 

```
<?php
  
   $ldap="ldap://ldapserver.it/";
   $usr="infnUUID=1b4c4a48-f360-4bae-b7ac-0d2820438bb4,ou=People,dc=infn,dc=it";
   #$usr="uid=MYUSERNAME,ou=People,dc=infn,dc=it";
   $pwd="MYPASSWORD";

   echo "Trying to connect to $ldap..........      ";
   ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);
   $ds=ldap_connect($ldap)
           or die("Cannot connect");
   $ldapbind=false;
   if(ldap_set_option($ds, LDAP_OPT_PROTOCOL_VERSION, 3))
      if(ldap_set_option($ds, LDAP_OPT_REFERRALS, 0))
         if(ldap_start_tls($ds))
               $ldapbind = @ldap_bind($ds, $usr, $pwd);
   ldap_close($ds);

   if(!$ldapbind)
      echo "ERROR";
   else
      echo "OK";
?>
```

To give a further example, here's the configuration I use for another service we provide with LDAP authentication:

```
- CMD_LDAP_URL=ldap://ldapserver.it:389
- CMD_LDAP_SEARCHBASE=OU=people,DC=infn,DC=it
- CMD_LDAP_SEARCHFILTER=(&(objectclass=inetOrgPerson)(uid={{username}})(isMemberOf=*))
- CMD_LDAP_USERIDFIELD=uid

```

That is we use the canonical searchbase plus an ldap searchfilter to search for the given username. Could it be that the plugin is picking up the wrong field while trying the ldap_bind?

Thanks again for the support.

Marco

**Comment by DanielnetoDotCom** [comment]
This is strange.

where do you inform the bind to search for your username?

so it should work if you set the rdn = `infnUUID=1b4c4a48-f360-4bae-b7ac-0d2820438bb4,ou=People,dc=infn,dc=it`


here is a snippet of the code on the plugin, it may be helpful for you.


                $ldap_server = $obj->server;
                $auth_user = str_replace('{$user}', $user, $obj->rdn);
                $auth_pass = $pass;
                if (($connect = ldap_connect($ldap_server, $obj->port))) {
                    ldap_set_option($connect, LDAP_OPT_PROTOCOL_VERSION, $obj->LDAP_OPT_PROTOCOL_VERSION);
                    if (($bind = @ldap_bind($connect, $auth_user, $auth_pass))) {
                        if ($bind === true) {
                            return User::USER_LOGGED;
                        } else {
                            _error_log("LDAP BIND NOT TRUE: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true));
                        }
                    } else {
                        _error_log("LDAP BIND fail: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true));
                    }
                } else {
                    _error_log("LDAP Connection fail: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true));
                }

**Comment by mcorvo** [comment]
Hi Daniel,

I went a little more on in debugging my issue and tried to replicate what I suppose the code should be doing. I took a simple html form to collect username and password:

```
<html>
<body>

<form action="ldaptlstest-av.php" method="post">
User: <input type="text" name="name"><br>
Password: <input type="password" name="passwd"><br>
<input type="submit">
</form>

</body>
</html>

```

Then I took your snippet and built around it a sort of "should work like" php page:

```
<?php

#
# Old parameters, superseded by db connection
#
$obj = new stdClass;
$obj->server = "ldap://ds-servnaz.infn.it";
$obj->port = 389;
$obj->LDAP_OPT_PROTOCOL_VERSION = 3;
$obj->rdn = 'infnUUID={$user},ou=People,dc=infn,dc=it';


#
# User and password retrieved from a simple HTML form
#
$user = $_POST["name"];
$auth_pass = $_POST["passwd"];
$bind = 0;

#
# Database credentials
#
$servername = "db";
$username = "root";
$password = "root";

// Create connection
$conn = new mysqli($servername, $username, $password);

// Check connection
if ($conn->connect_error) {
  die("Connection failed: " . $conn->connect_error);
}
echo "Connected successfully<br>";

#
# Use the right database, that is aVideo
#
$sql = "use aVideo";
$result = $conn->query($sql);

#
# Select the configuration associated to the LoginLDAP plugin
#
$sql = "SELECT object_data FROM plugins where name='LoginLDAP'";
$result = $conn->query($sql);

if ($result->num_rows > 0) {
  // output data of each row
  while($row = $result->fetch_assoc()) {
    $res = $row["object_data"];
    echo "object_data: " . $res ."<br>";
  }
} else {
  echo "0 results";
}
$conn->close();

#
# Decode the json with the information
#
$ldap_object = json_decode($res, false);
# The RDN
echo "RDN: " . $ldap_object->rdn . "<br>";
# The LDAP server name
$ldap_object->server = preg_replace('/[\\\\]/', '', $ldap_object->server);
echo "LDAP server: " . $ldap_object->server . "<br>";
echo "LDAP port: " . $ldap_object->port . "<br>";
echo "LDAP protocol version: " . $ldap_object->LDAP_OPT_PROTOCOL_VERSION . "<br>";

#
# Replace the '{$user}' string with the actual username retrieved from the HTML form
#
# From now on the code is the same as Daniel's snippet

$auth_user = str_replace('{$user}', $user, $ldap_object->rdn);
echo "Attempt to log user ". $auth_user . "<br>";

    if (($connect = ldap_connect($ldap_object->server, $ldap_object->port))) {
        ldap_set_option($connect, LDAP_OPT_PROTOCOL_VERSION, $ldap_object->LDAP_OPT_PROTOCOL_VERSION);
        ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);
        if (($bind = @ldap_bind($connect, $auth_user, $auth_pass))) {
	    if ($bind === true) {
		echo "Bind equal to " . $bind . ". User correctly logged in<br>";
                #return User::USER_LOGGED;
            } else {
                echo "LDAP BIND NOT TRUE: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true);
            }
        } else {
            echo "LDAP BIND fail: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true);
        }
    } else {
        echo "LDAP Connection fail: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true);
    }

?>

```
Essentially I:
- Connect to the database service in another docker container with the correct credentials
- Retrieve the "object data" associated with the LoginLDAP plugin
- Decode the json string with json_decode to pick up the server name, the port and the rdn
- Replace the '${user}' string with that retrieved from the html form
- Connect to the LDAP server using your snippet

With the fancy alphanumeric string (infnUUID) the bind is done correctly, as visible in the attached screenshot

![Screenshot 2021-11-22 195815](https://user-images.githubusercontent.com/9268893/142919550-87a7ab79-4bc0-4b0f-af9e-dea6723a0262.png)
 
At this point I'm really puzzled, because I'm able to bind to the ldap server with this simple php page and the workflow should be exactly the same as that of the plugin. Do you see any differences in the two procedures? The fact that I always see an error 32 (no such object) could be depending on the way the rdn is retrieved from the aVideo database?

Thanks again for your support and advices.

Regards,

Marco

**Comment by DanielnetoDotCom** [comment]
The error `LDAP BIND fail: 32: No such object` 

fails exactly on this line 

`if (($bind = @ldap_bind($connect, $auth_user, $auth_pass))) {`

and at this point, nothing is checked on the database

did you try this code on the exact same server as where you are hosting AVideo?

I am suspecting there is some difference in the environment.

I just sent an update to the LDAP plugin where it will log the RDN info before trying to bind it

**Comment by mcorvo** [comment]
Hi Daniel,

I found the issue. In the "journey" from the login form to the ldap_bind function, the DN string gets modified, as visible in this screenshot:

![Screenshot 2021-11-23 150027](https://user-images.githubusercontent.com/9268893/143038772-6408d3e6-d31a-4015-986a-8b359dbae07f.png)

That is the "infnUUID" that I insert in the configuration form gets changed into "uid" and this DN is not recognized by our ldap server. 

This leads to another point which I'd like to bring to your attention, in order to understand if the patch I'm going to ask is viable and worth developing.

We clearly cannot ask our users to authenticate to our mediacenter with that fancy string, but with their username. To match the username to the infnUUID, which then forms the user DN, we use a DN resolution mechanism. It takes the user’s name, then runs a search against the name attributes of all user entries to find the matching entry DN.

Our search filter is the following
```
(&(objectclass=inetOrgPerson)(uid=$user)(isMemberOf=*))
```
or a much simpler

```
filter = "(uid=$user)";
```

What we would need for the plugin to be usable is what the following snippet does:

```
#
# Decode the json with the information about the RDN
#
$ldap_object = json_decode($res, false);
# The RDN
echo "RDN: " . $ldap_object->rdn . "<br>";

#
# Split the RDN by comma
#
$temp = preg_split("/,/", $ldap_object->rdn);        <==============================

#
# Join the second up to the last item of the array to compose the "BaseDN" 
# which, in our case, is "ou=People,dc=infn,dc=it"
#
$base = join(",", array_slice($temp, 1));         <==========================
echo "BaseDN: ". $base . "<br>";

# The LDAP server name
$ldap_object->server = preg_replace('/[\\\\]/', '', $ldap_object->server);

# 
# Here $user is the "usual" username the user will put into the login form
# 
echo "Attempt to log user ". $user . "<br>";

    if (($connect = ldap_connect($ldap_object->server, $ldap_object->port))) {

# 
# HERE STARTS THE ADD-ON PART.
# I perform a lookup to look for the $user by running an ldap_search with the $base and $filter
# then I extract the DN (infnUUID.......) and use that value to complete the bind
# 
        #$filter = "(uid=$user)";                    ######## This is the simplest solution, otherwise we use the following line
        $filter = "(&(objectclass=inetOrgPerson)(uid=$user)(isMemberOf=*))";     <==============
        $ldap_result = @ldap_search($connect, $base, $filter);                                   <==============

        $attributes = array('eid' => 'uid', 'dn' => 'dn');                                            <===============
        if ($ldap_result) {                                                                                           <===============
            $entry_array = ldap_get_entries($connect, $ldap_result);                        <===============
            for ($i = 0; $i < count($entry_array) - 1; $i++) {
                if ($entry_array[$i]) {
                    $eid = $entry_array[$i]['uid'][0];
                    $dn = $entry_array[$i]['dn'];                                                             <===============
                }
            }
        }

# HERE IS THE STANDARD BIND OPERATION

        ldap_set_option($connect, LDAP_OPT_PROTOCOL_VERSION, $ldap_object->LDAP_OPT_PROTOCOL_VERSION);
        if (($bind = @ldap_bind($connect, $dn, $auth_pass))) {
            if ($bind === true) {
                echo "Bind equal to " . $bind . ". User correctly logged in<br>";
                #return User::USER_LOGGED;
            } else {
                echo "LDAP BIND NOT TRUE: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true);
            }
        } else {
            echo "LDAP BIND fail: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true);
        }
    } else {
        echo "LDAP Connection fail: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true);
    }

```
I understand this could be a patch which involves much more effort, but do you think it would be viable? For sure our LDAP server is a little choosy, but maybe others could be facing this problem of getting the right DN from their server. It should be possible to insert the ldap searchfilter maybe in the plugin configuration form, along with the other parameters, and then decide to perform the ldap search whether the filter has been defined by the administrator or not.
Otherwise could you suggest an alternative solution?

Many thanks again for your (much prompt) support.

Regards,

Marco

**Comment by DanielnetoDotCom** [comment]
Hi, I just sent the LoginLDAP version 2.7 where you can add a filter query using your code

![image](https://user-images.githubusercontent.com/18009293/143486267-9c0afd6c-5125-4bec-a4e9-c35f5649a384.png)


We will only perform a filter search if the Bind fails

Also if the errors still persist, please check the logs

here is the search snippet

```
   private static function authSearch($user, $pass) {
        if (empty($user) || empty($pass)) {
            _error_log("authSearch: LDAP EMPTY fail: Empty User and pass are not allowed");
            return User::USER_NOT_FOUND;
        }
        $obj = AVideoPlugin::getObjectData("LoginLDAP");
        if (!empty($obj->server) && !empty($obj->rdn)) {
            $rdn = explode("|", $obj->rdn);
            foreach ($rdn as $value) {
                $ldap_server = $obj->server;
                $auth_user = str_replace('{$user}', $user, $value);
                $auth_pass = $pass;
                if (($connect = ldap_connect($ldap_server, $obj->port))) {
                    $filter = str_replace('{$user}', $user, $obj->filter);
                    $ldap_result = @ldap_search($connect, $base, $filter);
                    $attributes = array('eid' => 'uid', 'dn' => 'dn');
                    if ($ldap_result) {
                        $entry_array = ldap_get_entries($connect, $ldap_result);
                        for ($i = 0; $i < count($entry_array) - 1; $i++) {
                            if ($entry_array[$i]) {
                                $eid = $entry_array[$i]['uid'][0];
                                $dn = $entry_array[$i]['dn'];
                            }
                        }
                    }

                    if(empty($dn)){
                        _error_log("authSearch: DN not found ". _json_encode($entry_array));
                        return false;
                    }
                    
                    ldap_set_option($connect, LDAP_OPT_PROTOCOL_VERSION, $ldap_object->LDAP_OPT_PROTOCOL_VERSION);
                    if (($bind = @ldap_bind($connect, $dn, $auth_pass))) {
                        if ($bind === true) {
                            return User::USER_LOGGED;
                        } else {
                            _error_log("authSearch: LDAP BIND NOT TRUE: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true));
                        }
                    } else {
                        _error_log("authSearch: LDAP BIND fail: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true));
                    }
                } else {
                    _error_log("authSearch: LDAP Connection fail: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true));
                }
            }
            if ($obj->ifLdapLoginFailTryDatabase) {
                $user = new User(0, $user, $pass);
                return $user->login(false, false, true);
            }
        } else {
            $object = new stdClass();
            $object->msg = "You need to set the server and the RDN";
            die(json_encode($object));
        }
        return User::USER_NOT_FOUND;
    }
```

**Comment by mcorvo** [comment]
Hi Daniel,

I tried the last version (2.7) but there's still something wrong. With the new configuration:

rdn: "uid={$user},ou=People,dc=infn,dc=it"
filter: "(uid={$user})"

the plugin returns:

[26-Nov-2021 09:36:57 Europe/Rome] AVideoLog::DEBUG: auth: LDAP RDN: uid=corvo,ou=People,dc=infn,dc=it SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php
[26-Nov-2021 09:36:57 Europe/Rome] AVideoLog::DEBUG: auth: LDAP BIND fail: 32: No such object SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php
[26-Nov-2021 09:36:57 Europe/Rome] AVideoLog::DEBUG: authSearch: DN not found  SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php

It looks like the DN is empty as well as the $entry_array 

```
if(empty($dn)){
    _error_log("authSearch: DN not found ". _json_encode($entry_array));
    return false;
}
```

which should be logged by this line. My only suspect goes on the "$base" variable for the ldap_search function:

```
$filter = str_replace('{$user}', $user, $obj->filter);
$ldap_result = @ldap_search($connect, $base, $filter);
```

The filter is correct, because it's the one I put in the configuration where you sustitute {$user} with the actual username, but the fact that the $entry_array is completely empty, makes me think that the $base is wrong and from your snippet I cannot recover how/where you collect that information, which should be "ou=People,dc=infn,dc=it". Could you please cross check that it is extracted correctly from the RDN?

Sorry for this long thread, but I hope we can converge to a solution which will be useful also to other users ;)

Thanks again for your very appreciated support!

Marco

**Comment by DanielnetoDotCom** [comment]
Hi

you are right, I missed the $base

I just submit version 2.8

here is the new snippet 


```

   private static function authSearch($user, $pass) {
        if (empty($user) || empty($pass)) {
            _error_log("authSearch: LDAP EMPTY fail: Empty User and pass are not allowed");
            return User::USER_NOT_FOUND;
        }
        $obj = AVideoPlugin::getObjectData("LoginLDAP");
        if (!empty($obj->server) && !empty($obj->rdn)) {
            $rdn = explode("|", $obj->rdn);
            foreach ($rdn as $value) {
                $ldap_server = $obj->server;
                $auth_user = str_replace('{$user}', $user, $value);
                $auth_pass = $pass;
                if (($connect = ldap_connect($ldap_server, $obj->port))) {
                    $temp = preg_split("/,/", $obj->rdn);
                    $base = join(",", array_slice($temp, 1)); 
                    $filter = str_replace('{$user}', $user, $obj->filter);
                    $ldap_result = @ldap_search($connect, $base, $filter);
                    $attributes = array('eid' => 'uid', 'dn' => 'dn');
                    if ($ldap_result) {
                        $entry_array = ldap_get_entries($connect, $ldap_result);
                        for ($i = 0; $i < count($entry_array) - 1; $i++) {
                            if ($entry_array[$i]) {
                                $eid = $entry_array[$i]['uid'][0];
                                $dn = $entry_array[$i]['dn'];
                            }
                        }
                    }

                    if(empty($dn)){
                        _error_log("authSearch: DN not found ". _json_encode($entry_array));
                        return false;
                    }
                    
                    ldap_set_option($connect, LDAP_OPT_PROTOCOL_VERSION, $ldap_object->LDAP_OPT_PROTOCOL_VERSION);
                    if (($bind = @ldap_bind($connect, $dn, $auth_pass))) {
                        if ($bind === true) {
                            return User::USER_LOGGED;
                        } else {
                            _error_log("authSearch: LDAP BIND NOT TRUE: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true));
                        }
                    } else {
                        _error_log("authSearch: LDAP BIND fail: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true));
                    }
                } else {
                    _error_log("authSearch: LDAP Connection fail: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true));
                }
            }
            if ($obj->ifLdapLoginFailTryDatabase) {
                $user = new User(0, $user, $pass);
                return $user->login(false, false, true);
            }
        } else {
            $object = new stdClass();
            $object->msg = "You need to set the server and the RDN";
            die(json_encode($object));
        }
        return User::USER_NOT_FOUND;
    }
```

**Comment by mcorvo** [comment]
Hi Daniel,

it works! Thank you very much for the big effort of satisfying our use case.

Regards,

Marco

**Comment by DanielnetoDotCom** [comment]
Also thank you for sharing your knowledge
