### ISSUE TITLE
slideshow 

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#5999]
hello, how to enable big video slideshow ?

**Comment by DanielnetoDotCom** [comment]
Make 2 or more videos suggested 
![chrome-capture (9)](https://user-images.githubusercontent.com/18009293/142864450-65f618ae-f891-43e4-b98e-964d84cf33f2.gif)

**Comment by KrzysioMisio** [comment]
thanks  Daniel 👍

**Comment by gbrn** [comment]
That didn't work for me, it only displays a selection.
