### ISSUE TITLE
Layout front page

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6001]
Hi,

How do I change the descriptive text layout? See this image the text layout is not in an interesting place.

![image](https://user-images.githubusercontent.com/37880073/142738982-a715382a-c668-4ae9-a343-872d7265bd2b.png)

**Comment by DanielnetoDotCom** [comment]
This is the video description ...
![chrome-capture (8)](https://user-images.githubusercontent.com/18009293/142864092-88befb3a-aedd-4102-aa37-4834812091ca.gif)

**Comment by gbrn** [comment]
Daniel, when I say Layout is the placement of the description (Top, Bottom, Right, Left).
Have to remove the description, because it is over the top of the image.

**Comment by gbrn** [comment]
Another issue, which I was unable to resolve, is the size of the highlighted image.
I've had reports from users, who don't remember to scroll the scroll bar and don't see the movie listing, because the image is covering the whole area.
![image](https://user-images.githubusercontent.com/37880073/143690550-ab26bf2d-97e2-486b-b04a-4e2926cbe8c0.png)

**Comment by DanielnetoDotCom** [comment]
Sorry this issue is not clear

**Comment by gbrn** [comment]
Hi Daniel, 

In the image of the previous post... The user who views my site cannot see where the other titles are. There is nothing indicating that below have more videos to view. There is no indication for the user to scroll the screen. Did you understand?

**Comment by gbrn** [comment]
Hi Daniel,

Returning to the topic discussed. Check out this example layout attached. I would like to know if I can make changes this way to the layout.

Information is well defined in easy-to-read locations.
Featured image with titles and buttons are at the top.
The description is below the image, with additional information.

![InkedInkedInkedInkedlayout01_LI](https://user-images.githubusercontent.com/37880073/147881470-79c12138-1984-442c-8b31-8c94932dd0dc.jpg)

**Comment by gbrn** [comment]
@DanielnetoDotCom Danny, returning to this topic, about the "BigVideo" layout of the home page.

Is there any possibility of changing the positioning of these description texts. In the past I even disabled it because it was very annoying for the text to overlap the image. It causes readability problems, due to the contrast between the text and the image, which can be of different colors.

I think there could be the option of placing the description at the bottom of the image, and further to the right.

![image](https://github.com/WWBN/AVideo/assets/37880073/39f1bab6-efa3-4c7e-9605-e732b6c8ba42)


![image](https://github.com/WWBN/AVideo/assets/37880073/2b04a2d2-ebbb-45b9-8e1f-c4a65f8c236d)

**Comment by DanielnetoDotCom** [comment]
Sorry, not right now
