### ISSUE TITLE
Update 11.4 to 11.5 broken 

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6002]
Hi Daniel,

I just upgraded to the version
And the site stopped working!!

![image](https://user-images.githubusercontent.com/37880073/142741775-9498ac98-75c8-4241-a761-33e8d9a34763.png)

**Comment by DanielnetoDotCom** [comment]
Make sure you update all the plugins, especially the VIdeoHLS and Resolution switcher.

If you cannot access the plugin page, try to Upload the unziped Folder

https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin#2---upload-the-unziped-folder

**Comment by gbrn** [comment]
I had to recover with backup. 
where can i get the instructions for this update 11.5?

**Comment by DanielnetoDotCom** [comment]
First update the plugins, then make a git pull

**Comment by gbrn** [comment]
Hi Daniel,

I can't see which plugins need updating:

![Plugins · CNETV](https://user-images.githubusercontent.com/37880073/142778923-b5d2df46-ddbd-4d9a-baac-d6025c376a5e.png)

**Comment by DanielnetoDotCom** [comment]
If you have those plugins you just need to download them again and upload it

otherwise just make a git pull and also make sure you install the table for version 11.5

**Comment by gbrn** [comment]
Hi Daniel,

Executei mais alguns testes na atualização.
Habilitei todas as tabelas conforme você informou.
Fiz a atualização completada do diretório PLUGIN. Depois da atualização é apresentada a seguinte mensagem

```
array(4) {
  ["type"]=&gt;
  int(64)
  ["message"]=&gt;
  string(81) "Cannot make static method ObjectYPT::setTimezone() non static in class CachesInDB"
  ["file"]=&gt;
  string(97) "/home/storage/e/88/c1/guilhermeblanco/public_html/cnetv/_beta/plugin/Cache/Objects/CachesInDB.php"
  ["line"]=&gt;
  int(190)
}
```
![image](https://user-images.githubusercontent.com/37880073/147888510-0d5529a5-0ac1-4cc3-a1e7-e80952447ad4.png)

**Comment by DanielnetoDotCom** [comment]
Atualize seu código com o comando `git pull`

Com certeza você está usando um código antigo

https://github.com/WWBN/AVideo/blob/master/plugin/Cache/Objects/CachesInDB.php

**Comment by gbrn** [comment]
Daniel, se eu usar o comando git pull, o site vai quebrar novamente. Vou tentar atualizar somente CachesInDB.php, depois tento atualizar se funcionar.

> Hi Daniel,
> 
> I just upgraded to the version And the site stopped working!!
> 
> ![image](https://user-images.githubusercontent.com/37880073/142741775-9498ac98-75c8-4241-a761-33e8d9a34763.png)

**Comment by DanielnetoDotCom** [comment]
O git pull é necessário, você nao pode atualizar somente um arqivo. você tem que obrigatóriamente atualizar todos.

**Comment by gbrn** [comment]
Daniel, executei o GIT PULL, está sendo apresentado a seguinte mensagem:


$ git pull origin master
From https://github.com/WWBN/AVideo
 * branch            master     -> FETCH_HEAD
Updating ff40021..fa0537f
error: Your local changes to the following files would be overwritten by merge:
        .github/workflows/validate.yml
        .htaccess
        Dockerfile
        admin/index.php
        feed/roku.json.php
        install/index.php
        objects/Object.php
        objects/aVideoEncoder.json.php
        objects/category.php
        objects/configuration.php
        objects/configurationClearCache.json.php
        objects/functionCroppie.php
        objects/functions.php
        objects/functionsGetTinyMCE.php
        objects/include_config.php
        objects/login.json.php
        objects/playlist.php
        objects/user.php
        objects/video.php
        objects/videoAddNew.json.php
        objects/video_statistic.php
        plugin/AD_Server/AD_Server.php
        plugin/AD_Server/Objects/VastCampaignsVideos.php
        plugin/AVideoPlugin.php
        plugin/CDN/Storage/CDNStorage.php
        plugin/Cache/Cache.php
        plugin/CustomizeAdvanced/CustomizeAdvanced.php
        plugin/CustomizeUser/CustomizeUser.php
        plugin/DiscordNotify/DiscordNotify.php
        plugin/Gallery/functions.php
        plugin/Gallery/view/BigVideo.php
        plugin/Layout/Layout.php
        plugin/Live/Live.php
        plugin/Live/Objects/Live_schedule.php
        plugin/Live/index.php
        plugin/Live/install/install.sql
        plugin/Live/install/nginx.conf
        plugin/Live/saveLive.php
        plugin/Live/tabs/tabStreamSettings.php
        plugin/Live/view/Live_schedule/panel.php
        plugin/Live/view/menuRight.php
        plugin/Live/view/modeYoutubeLive.php
        plugin/Live/view/videoEmbeded.php
        plugin/Live/webcamFullscreen.php
        plugin/Meet/api.js.php
        plugin/Meet/iframe.php
        plugin/PlayerSkins/PlayerSkins.php
        plugin/ReportVideo/ReportVideo.php
        plugin/User_Location/User_Location.php
        view/channelBody.php
        view/channels.php
        view/configurations_body.php
        view/css/main.css
        view/include/navbar.php
        view/include/social.php
        view/js/script.js
        view/logs.php
        view/managerPlugins_body.php
        view/managerVideos_body.php
        view/modeYoutube.php
        view/trending.php
        view/user.php
        view/videoEmbeded.php
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by DanielnetoDotCom** [comment]
Ao invé do git pull execute isso

`sudo git fetch --all && sudo git reset --hard origin/master`

**Comment by gbrn** [comment]
Daniel, fiz o reset hard. O site não caiu totalmente, mas ficou instável sem apresentar os vídeos.
Como a atualização anterior não foi concluida com sucesso, a opção de atualização não ficou disponível. Rebaixei a versão no Mysql, e consegui executar as atualizações. Atualizei os plugins todos. Mas não resolveu a questão da visualização dos vídeos.
Tirei o site do ar para fazer um recovery mais tarde com último backup.
Na sequência faço novos testes.

**Comment by DanielnetoDotCom** [comment]
Na verdade não entendi

se tiver algum problema , compartilha alguns screenshots e o log de erro do avideo

**Comment by gbrn** [comment]
Daniel, não estou conseguindo restaurar o site. Já fiz isso no passado e consegui com sucesso. Mas dessa vez alguma coisa com o Banco de Dados não deixa avançar... Me parece que foi o cache que habilitei.

Veja o erro que retorna da restauração do DB:

Database error processing line 12
Database server error reply:

ErrNo #1709
Index column size too large. The maximum column size is 767 bytes.
 SQL=CREATE TABLE `CachesInDB` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `content` blob,
  `domain` varchar(255) DEFAULT NULL,
  `ishttps` tinyint(4) DEFAULT NULL,
  `loggedType` enum('n','l','a') DEFAULT 'n' COMMENT 'n=not logged\nl=logged\na=admin',
  `user_location` varchar(255) DEFAULT NULL,
  `expires` datetime DEFAULT NULL,
  `timezone` varchar(255) DEFAULT NULL,
  `name` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cacheds1` (`domain`),
  KEY `caches2` (`ishttps`),
  KEY `caches3` (`loggedType`),
  KEY `caches4` (`user_location`),
  KEY `caches5` (`created`),
  KEY `caches6` (`modified`),
  KEY `caches7` (`expires`),
  KEY `caches8` (`timezone`),
  KEY `caches9` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
Raw query text:

CREATE TABLE `CachesInDB` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `content` blob,
  `domain` varchar(255) DEFAULT NULL,
  `ishttps` tinyint(4) DEFAULT NULL,
  `loggedType` enum('n','l','a') DEFAULT 'n' COMMENT 'n=not logged\nl=logged\na=admin',
  `user_location` varchar(255) DEFAULT NULL,
  `expires` datetime DEFAULT NULL,
  `timezone` varchar(255) DEFAULT NULL,
  `name` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cacheds1` (`domain`),
  KEY `caches2` (`ishttps`),
  KEY `caches3` (`loggedType`),
  KEY `caches4` (`user_location`),
  KEY `caches5` (`created`),
  KEY `caches6` (`modified`),
  KEY `caches7` (`expires`),
  KEY `caches8` (`timezone`),
  KEY `caches9` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

**Comment by gbrn** [comment]
Tentei restaurar em meu server e em minha máquina local, o erro do DB sempre acontece. Parece que o cache "lotou" a tabela.

**Comment by DanielnetoDotCom** [comment]
Pesquise no google 

`Index column size too large. The maximum column size is 767 bytes.`

**Comment by gbrn** [comment]
Daniel, encontrei essa informação no site oficial do MySQL:

https://bugs.mysql.com/bug.php?id=102597

Você já teve algum relato deste erro? Me parece que é uma condição dos dados que estão superiores ao tamanho do setup padrão do InnoDB (MySQL).

**Comment by gbrn** [comment]
Daniel, não consegui resolver essa questão do tamanho do DB.
Acabei efetuando uma nova instalação e importando o DB anterior. Com isso apresentou vários erros nas tabelas incompatíveis.
Tive que ir testando e importando as tabelas na "unha". Isso porque eu não tenho muita experiência com Banco de dados.
![image](https://user-images.githubusercontent.com/37880073/148309903-6785105d-aa34-4f33-b758-4fa985b60d2e.png)

No final consegui restaurar.

Perdi várias configurações que já fiz anteriormente, mas corrigirei isso com mais tempo. Importante que o site não está mais OFF...

Daniel, qual o melhor recurso para Backup neste sistema? Eu estava usando o Akeeba Solo, mas deu todo esse problema na hora de recuperar.

**Comment by DanielnetoDotCom** [comment]
Já vi o mesmo problema ser resolvido antes, só não lembro como. Por isso recomendo google

para backup veja aqui...

https://github.com/WWBN/AVideo/wiki/How-to-make-a-backup#tools-to-backup

**Comment by gbrn** [comment]
Daniel, não consegui retomar as configurações dos plugins.... elas não são armazenadas no BD?
Por exemplo, as configurações do  (CustomizeAdvanced), não consegui retormar.

**Comment by DanielnetoDotCom** [comment]
Sim as configurações dos plugins sao salvas no banco de dados

**Comment by gbrn** [comment]
Daniel, analisando aqui as duas bases... da versão 11.4 e para 11.5. Verifiquei que a tabela PLUGINS não existia anteriormente.
Muito provável que por isso não tenha conseguido importar as configurações anteriores, para a nova versão.
Estou certo dessa informação?

**Comment by DanielnetoDotCom** [comment]
Tente criar a tabela plugins manualmente , mas vc vai precisar configurar todos os plugins novamente

**Comment by gbrn** [comment]
Sim a tabela Plugins já estou com ela no DB. A questão é que não consegui importar os dados anteriores. 
Me informe por favor, em qual tabela era armazenado os dados dos plugins?

**Comment by DanielnetoDotCom** [comment]
Na verdade você tem conseguir importar o banco de dados completo 

caso haja uma falha não acredito que seja possível identificar o que faltou e simplesmente adicionar 

acho que você está indo pelo caminho errado e o que você está me solicitando. Ao tenho como lhe informar
