### ISSUE TITLE
Video ads are Auto playing by just going to the video page without clicking play

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6003]
Ad Server video ads are auto playing before the the user clicks play. This is also happening on embeds on external sites.

**Comment by DanielnetoDotCom** [comment]
can you please put a link here so I can test?

**Comment by JoshWho** [comment]
Any video on the site does it, but this is some that are embedded on another website https://creation.social/home

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/142894682-f46edb71-a3c6-4812-abf8-23e1cdcadd29.png)

I need to see the site and the embedded video.

**Comment by JoshWho** [comment]
crap I guess you have to be logged in to see it. On my site just view a video as a guest and you will see it.

**Comment by DanielnetoDotCom** [comment]
I just tested here and it is not auto playing

https://codepen.io/danielnetodotcom/pen/qBXeZbZ

**Comment by JoshWho** [comment]
I think it is a lot better now.
