### ISSUE TITLE
Email sent link share

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#6005]
Hello All

Where i change for come email ok when you share video from email?
Email its ok but dont see the Name and the Website why its blank

Thank
![Screenshot 2021-11-21 at 11-36-07 How to post an article](https://user-images.githubusercontent.com/93554732/142758665-f21acfcd-927e-4f29-8ecd-e9663cedd82d.png)

![Screenshot 2021-11-21 at 11-36-50 Message From Site Excalibur4 () - lucsan666 gmail com - Gmail](https://user-images.githubusercontent.com/93554732/142758672-e90dca79-409c-4b55-94f2-3b93ed6a7825.png)

**Comment by DanielnetoDotCom** [comment]
You are right, those fields are useless.

here is an update that removes it from the email.

you get this update you need to make  a git pull

**Comment by toplive24** [comment]
Hello Neto I don't know to do the git pull.
If you can help me I tell you thank

**Comment by DanielnetoDotCom** [comment]
Sure, please try to follow this...

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by toplive24** [comment]
This?

git pull

cd /var/www/html/AVideo/ && sudo git pull

**Comment by DanielnetoDotCom** [comment]
Login with SSH on your server and run this 

cd /var/www/html/AVideo/ && sudo git pull

**Comment by toplive24** [comment]
Thank so much like always Neto
