### ISSUE TITLE
VideoResolution Switcher visual error on hoover

### ISSUE THREAD

**Issue by markginter31** [WWBN/AVideo#6006]
I've attached a screen shot.  It's showing some code instead of the options.  

I'm on the latest git pull -- and I re downloaded / uploaded the videoresolutionswitcher plug
![error](https://user-images.githubusercontent.com/7345618/142761156-bb5a657b-292a-4f9d-90b6-a73363551baf.png)
in

**Comment by DanielnetoDotCom** [comment]
Please make sure you download and update the latest video resolution plugin

**Comment by markginter31** [comment]
I logged into the plugin site - downloaded from the provided link - and uploaded it to my site.  But I'm still seeing the same thing.  Is there a step I'm missing?

**Comment by DanielnetoDotCom** [comment]
Did you make a git pull on your server?

**Comment by DanielnetoDotCom** [comment]
Also try to clear the cache

**Comment by markginter31** [comment]
Yes sir - I've tried each of those steps.  Latest git.  Cleared first page cache / cleared cache - even pulled it up on a computer that I hadn't gone to the site with... Trying to think of what else I might be missing but I'm not sure.

**Comment by markginter31** [comment]
Ok - this is strange - In the Plugins List it says Update Available for VideoResolutionSwitcher.  I download it - upload it to the site - and then it still says that there's an update available.  It's telling me I'm running 3.1 and 3.7 is available...

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin#3---permissions

**Comment by markginter31** [comment]
Thank you! That did it!
