### ISSUE TITLE
YPT plugin consuming lots of cpu

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6007]
Why is the YPT plugin consume so much cpu? here is an output of a bot command that give me the most 5 consuming processes and YPT is among them.

Top 5 CPU consumers:
%CPU CMD
83.4 php /var/www/html/AVideo/plugin/YPT
40.6 /usr/sbin/mysqld
 5.8 htop
 5.6 /usr/bin/mongod --unixSocketPrefix=

Is there anything that can be done to reduce this?

**Comment by DanielnetoDotCom** [comment]
Please make sure you update your HLS and resolution plugins and then make the git pull

**Comment by guymass** [comment]
Im not sure what you mean by "Update your HLS and resolution", where do I do that? or I simply just run a gut pull?

**Comment by DanielnetoDotCom** [comment]
No

download them again from the marketplace and update them.

VideoHLS version 6.0
VideoResolutionSwitcher version 3.7

**Comment by guymass** [comment]
I don't have those plugins, is this the only way? everything else is updated.

**Comment by DanielnetoDotCom** [comment]
No, those are the ones I notice the problem with CPU consuming

but try to update all the plugins

**Comment by guymass** [comment]
Everything is updated, version 11.5 and also all our plugins. Now YPTSocket stoped working.
![Screen Shot 5782-03-20 at 17 50 46](https://user-images.githubusercontent.com/58882903/143271142-f23dd7f6-8594-40f5-af2e-b7c0d601c556.jpg)

**Comment by DanielnetoDotCom** [comment]
try to stop the socket then start again.

`/var/www/html/AVideo/plugin/YPTSocket/stopServer.php`


`/var/www/html/AVideo/plugin/YPTSocket/server.php`

make sure the socket port is not busy

**Comment by guymass** [comment]
OK thanks thats back now. Site is fully updated and also plugins, I will keep checking and see if YPTSocket continues to use high cpu resources and post back soon.

**Comment by guymass** [comment]
Still using high cpu % 

![Screen Shot 5782-03-20 at 20 29 29](https://user-images.githubusercontent.com/58882903/143296110-697db266-1627-48dc-97c1-75945030f9cf.jpg)

**Comment by DanielnetoDotCom** [comment]
does that mean the socket is consuming too much CPU?

how many users do you have live now?

Did you do that? https://github.com/WWBN/AVideo/wiki/Speed-up-your-page#yptsocket

**Comment by guymass** [comment]
Yes I did the instructions on that URL and we are mostly on average 200+ users.

**Comment by DanielnetoDotCom** [comment]
I am not sure what is causing this.

any clue on the log?

**Comment by guymass** [comment]
We have it now running as a systemd service with crontab to restart it daily. Still no real idea why its such a cpu hog.

**Comment by DanielnetoDotCom** [comment]
Please check the latest git pull . I release some improvements regarding MySQL

**Comment by guymass** [comment]
ok Thanks I will close this for now
