### ISSUE TITLE
VideoResolution Switcher visual

### ISSUE THREAD

**Issue by JeanDavis91** [WWBN/AVideo#6008]
Hello

There is no longer a red background for resolutions

![pas bon](https://user-images.githubusercontent.com/61474191/142786945-64d86681-d608-48ee-a7cf-1e562c4e5d96.jpg) ![bon](https://user-images.githubusercontent.com/61474191/142786952-0423744b-e71b-4e12-9d02-79c0e6d91db1.jpg)

I installed the latest version of the plugin's

Thank you for the work done

David

**Comment by DanielnetoDotCom** [comment]
Correct, the latest videojs does not support HTML on the player menus

**Comment by JeanDavis91** [comment]
Hello

Can something like this be done?
![autre](https://user-images.githubusercontent.com/61474191/142789128-6c54cbef-83bd-4f99-b669-e8e2fcdc39cd.jpg)

David

**Comment by DanielnetoDotCom** [comment]
Sorry no, we cannot. but as soon as I find out a way to add the HTML back I will do it.
