### ISSUE TITLE
getAllWebp.php isn't making the request

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#6009]
seems that getAllWebp.php isn't making the request, but rather just checks what ever they exist or not.

`/install $ sudo php getAllWebp.php`

```
Start (1) ******

Start: Day 2
Get webp
Get webp not found https://192.168.x.x/AVideo/videos/video_211119202200_v5562/index.m3u8
 Start (2) ******

Start: Day 3
Get webp
Get webp not found https://192.168.x.x/AVideo/videos/video_211119203038_va332/index.m3u8
 Start (3) ******

Start: Day 4
Get webp
Get webp not found https://192.168.x.x/AVideo/videos/video_211121214135_v8aae/index.m3u8
 Start (4) ******
.........
```

PS: I manually deleted the .webp gifs to request the new ones. But request fails

**Comment by DanielnetoDotCom** [comment]
Hi, 

I tested here locally and it should have some more information


 ```
Start (2) ******

Start: Memoji - AVENGERS INFINITY WAR
File exists: Memoji - AVENGERS INFINITY WAR
Finish: Memoji - AVENGERS INFINITY WAR
******

 Start (3) ******

Type (audio) is not a video: Memoji - AVENGERS INFINITY WAR
 End (3) ******

```

Or maybe the get_headers function is not working.

check the apache log or avideo log 

maybe if you remove the @ from the get_headers function make the script show some errors to you 

https://github.com/WWBN/AVideo/blob/244089213b5f15dd5f756e269fec4d82394a0b34/install/getAllWebp.php#L33

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom I'm getting the same outputs as you. The difference is that you haven't reproduced the issue as I've stated. Delete the webp manually from the video's directory, then run the php command, and see the output.

**Comment by DanielnetoDotCom** [comment]
I just manually delete a webp image and the command works and restore the image.

```
 Start (1) ******

Start: Memoji - AVENGERS INFINITY WAR
Get webp
Get done

```

try to get a log file. also try the encoder log

**Comment by akhilleusuggo** [comment]
Nothing showing up on 3 places. Nothing on apache log file, nothing on streamer log file & nothing on encoder log file. 

No errors, no output.

**Comment by DanielnetoDotCom** [comment]
that is weird 

not sure how to help you without a clue or reproducing it.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Could you confirm that this has nothing to do with self signed certificates ?

**Comment by DanielnetoDotCom** [comment]
Hi, this update will ignore the SSL, you may be right

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Hello Daniel, the issue has been fixed with the update. Indeed was checking for the SSL. Maybe a way to import the self-sighed in the future. I'll be googling for this, since many issues are related to the self-signed, one of them the Android App.

**Comment by DanielnetoDotCom** [comment]
the apps are different. the SSL is not a server thing, it is an app thing, and as I know I cannot tell google apps to not check the SSL.
