### ISSUE TITLE
Under maintenance after installing

### ISSUE THREAD

**Issue by ShrekisLyf** [WWBN/AVideo#6010]
I just installed the script via git clone - did git pull but it is already up to date
I did all configs and also did all apache related things

The currently problems is displayed on my website as followed:

![Screenshot_20211123-132744_Chrome](https://user-images.githubusercontent.com/63299919/143023988-195117d7-bd32-4452-a4e9-2d09cd3d9c3e.jpg)

**Comment by DanielnetoDotCom** [comment]
google for this error and you will find how to install php-gd

**Comment by ShrekisLyf** [comment]
> google for this error and you will find how to install php-gd

Oh I definetly didn't see that I need gd, I forgot to activate it.
Will come back if problems occur, thanks!

**Comment by ShrekisLyf** [comment]
The site works I will close this!
