### ISSUE TITLE
Sign-in button top right not clickable

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6012]
Hi @DanielnetoDotCom 

Latest git both streamer and encoder

The top right sign-in button isn't clicking. the one on the left menu is ok.

When you click it is like it has no link. So it does nothing and remains on the same page.

However when you click sign-out, it works.

Any fix for that?

Thank you

**Comment by DanielnetoDotCom** [comment]
can you please screenshot what button are you referring to?

**Comment by jengajenga** [comment]
> can you please screenshot what button are you referring to?

thanks @DanielnetoDotCom the quick response. screenshot below.

![trb](https://user-images.githubusercontent.com/65451390/143087397-27c8e1d2-dcb2-486c-8248-022d30b34d6f.jpeg)

**Comment by jengajenga** [comment]
@DanielnetoDotCom any fix for this. still on the latest git and no response. I have had to remove it from the website via the customizedAdvanced in the plugins tab.

**Comment by DanielnetoDotCom** [comment]
Sorry for the delay, here is a fix

**Comment by jengajenga** [comment]
Thank you @DanielnetoDotCom . Can confirm it is working.
