### ISSUE TITLE
Update From 11.4 to 11.5 Buggy

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#6013]
After update splash screen has big check box. 
![log in screen_lblivestream com](https://user-images.githubusercontent.com/37937968/143079272-9eb486b1-69bd-4462-b952-8341de87d230.jpeg)

Top Menu is gone. And is now on the side?! and every thing is oversized.
![After Clicking menu on top left lblivestream com](https://user-images.githubusercontent.com/37937968/143079386-bb178fa4-3d77-4f10-b695-c3dc328edc49.jpeg)

Did all of the basic before update 
sudo apt-get update && sudo apt-get upgrade. Then I updated all of my plug-ins.
Then did a git pull. Restarted the server and that is what I got. Help

**Comment by DanielnetoDotCom** [comment]
try to manually delete your cache folder

`sudo rm -R /var/www/html/AVideo/videos/cache`

also, make sure the videos folder is writable.

`sudo chmod -R 777 /var/www/html/AVideo/videos/`

**Comment by Lordblanca** [comment]
All Good Thank You. :)
