### ISSUE TITLE
Article copy and paste 

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#6017]
Hello all 

I need more info why inside in the article I can not paste the text but if I click dx mouse for paste tell me only insert the link and don't make me paste the text. 

Thank

**Comment by DanielnetoDotCom** [comment]
Most of the HTML tags are not allowed, unwanted tags can break your site.

if you are copying it from a web page or word you may be bringing a lot of unwanted tags

**Comment by toplive24** [comment]
Another solution Neto?
Why I have some people artist that have problem to upload only the photos not video.

Thank

**Comment by DanielnetoDotCom** [comment]
You need to give more details about the upload. 

also check your log

also try to reproduce it on demo site.

**Comment by toplive24** [comment]
> Most of the HTML tags are not allowed, unwanted tags can break your site.
> 
> if you are copying it from a web page or word you may be bringing a lot of unwanted tags

I understand but thus it's a problem for different users why we have different users artist that don't to do video but only photo with text.

Thsnk
