### ISSUE TITLE
Illegal email error

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6018]
I am configuring a new site and I get an illegal email error although the email is a valid gmail account.
![Screen Shot 5782-03-20 at 20 22 03](https://user-images.githubusercontent.com/58882903/143294034-844c890d-fefa-4fcb-8818-a39784b1ad33.jpg)

**Comment by DanielnetoDotCom** [comment]
I am not sure what this message means. but check your log. and I am pretty sure this message comes from google.

**Comment by guymass** [comment]
Oh sorry, it says email is not legal, but maybe its wrong configuration on the TXT record I set for google.
I used this Option A with our new domain name: edenews.co.il
![Screen Shot 5782-03-20 at 22 03 17](https://user-images.githubusercontent.com/58882903/143306126-cf4d0200-2f34-4e82-bdd5-07f46bc1a5f8.jpg)

**Comment by DanielnetoDotCom** [comment]
I guess this error is more an SMTP server issue, not an email forward issue.

**Comment by DanielnetoDotCom** [comment]
Sorry I cannot read the message.
