### ISSUE TITLE
Need a way for alternative analytic code per channel

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6019]
Is there a way we can have a spot like for the Google analytics but for alternative like my custom analytics I am running now, would be featurable if others could use it on their channel.

![5b4edca0-3d38-4a30-aef9-4ad6b3c87c33](https://user-images.githubusercontent.com/39392449/143301084-73973c3a-94f2-40f9-931c-ea805c2dd063.png)

This is my code snippet it can be done Java  the more preferred method, or php 

Example Java snippet
```

<!-- Start Open Web Analytics Tracker -->
<script type="text/javascript">
//<![CDATA[
var owa_baseUrl = 'https://analytics.joshwho.net/';
var owa_cmds = owa_cmds || [];
owa_cmds.push(['setSiteId', '2352e4576bbf3bdeca150041c5a78525']);
owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);
owa_cmds.push(['trackDomStream']);

(function() {
    var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
    owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
    _owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';
    var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
}());
//]]>
</script>
<!-- End Open Web Analytics Code -->

        
```

        Example PHP Not sure if the php one would be doable because it calls for a local file located https://analytics.joshwho.net/owa_php.php

```
require_once('/var/www/html/analytics_joshwho_net/owa_php.php');

$owa = new owa_php();
// Set the site id you want to track
$owa->setSiteId('2352e4576bbf3bdeca150041c5a78525');
// Uncomment the next line to set your page title
//$owa->setPageTitle('somepagetitle');
// Set other page properties
//$owa->setProperty('foo', 'bar');
$owa->trackPageView();
        
        
```

**Comment by JoshWho** [comment]
I will be offering this as a public service free for all, if you want to just make it another bar like the Google one and it can use my analytic site id instead.

**Comment by DanielnetoDotCom** [comment]
Hi, I cannot allow each user to add his own JS code, this will be a huge security branch.

if you want to allow them to use it the best option would be to create a custom plugin for AVideo.

**Comment by JoshWho** [comment]
I agree, I said to use the Google method but replace it with JoshWho ANalytics then they can just enter a Site id

**Comment by JoshWho** [comment]
I am not saying replace the Google one but add this on top of it as another option for analytics.

**Comment by JoshWho** [comment]
Or could make a Selector On the Bot And Make one Google the other JoshWho then it could just be the one box u put the site code in

**Comment by JoshWho** [comment]
> I will be offering this as a public service free for all, if you want to just make it another bar like the Google one and it can use JoshWho Analytics site id instead.

**Comment by JoshWho** [comment]
Would like this to be a permanent part of the core of Avideo please.

**Comment by DanielnetoDotCom** [comment]
Here is your custom plugin to do what you are trying to do

[JoshWho.zip](https://github.com/WWBN/AVideo/files/7604306/JoshWho.zip)

I hope this works as an example for those who try to do a similar thing

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom  You are the best

**Comment by JoshWho** [comment]
I love this is awesome!!!!!!!!!!

![b68db675-ce2d-4546-937d-248fa8f36ccf](https://user-images.githubusercontent.com/39392449/143476759-feb58570-30f5-4e2f-980b-cba036ebde56.png)
