### ISSUE TITLE
Share Bottom sending Wrong Information

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#6021]
When people sharing the live or Video is sending wrong information instead of the video sending the Logo. 

![Screenshot_20211124-214440_Chrome](https://user-images.githubusercontent.com/63973045/143370922-9438b6b6-781b-4a0e-a25e-2babe368566b.jpg)

On the image above when clicking the share icon is sending this instead of the video link. 

https://musicandstream.com/videos/userPhoto/logo.png?1636653416

Why is that??

**Comment by DanielnetoDotCom** [comment]
tested here and works fine

**Comment by LATINMIXMASTERS** [comment]
Well sorry i forgot to mentioned when the person is live , is sending that link only Is not sending the correct link

**Comment by LATINMIXMASTERS** [comment]
Right now a user is live and when clicking the share icon on app give this link. 

https://musicandstream.com/videos/userPhoto/logo.png?1636653416

So is not giving the right share link and is doing it every live stream 

![Screenshot_20211202-155503_Music and Stream](https://user-images.githubusercontent.com/63973045/144501561-caa05746-0601-401d-8f19-d99c13dfd77f.jpg)


Also on desktop doing the same.

**Comment by DanielnetoDotCom** [comment]
Can you please try this update?

**Comment by LATINMIXMASTERS** [comment]
What update ?

**Comment by DanielnetoDotCom** [comment]
make a git pull on your server 

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform
