### ISSUE TITLE
Live Link time

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#6024]
Hi, 

I checked my server date-time.  It's correct.

![1637902733820@2x](https://user-images.githubusercontent.com/57282919/143529272-caba5d90-87f4-4871-97d8-f80ece8760bf.jpg)

But on My Avideo webiste -> Add an external Live Link button.
the Date-time on this page is not correct.

![1637902321017](https://user-images.githubusercontent.com/57282919/143529059-e493c66f-03ab-430b-b6e1-df7911fc17c1.jpg)

So, How can I update date-time on this pages?

**Comment by DanielnetoDotCom** [comment]
check what timezone you are using here...
![chrome-capture (2)](https://user-images.githubusercontent.com/18009293/143614758-70ff2e66-4e8f-4098-82d2-96a51e522cb2.gif)

**Comment by guitarpound** [comment]
Thanks
