### ISSUE TITLE
I have a user that says he is banned in a Chat2 but the channel says he never banned him and has no way to unban

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6027]
Is there anywhere on the admin side to unban people in Chat2? I do not see a banlist or anything and I am thinking I might have to do it in the mysql tables

**Comment by DanielnetoDotCom** [comment]
Check the User_Controll plugin 

![chrome-capture (5)](https://user-images.githubusercontent.com/18009293/144044826-cc7b3a78-02fd-41d9-908b-59cd9c0746c1.gif)

**Comment by JoshWho** [comment]
I do not see him listed

**Comment by DanielnetoDotCom** [comment]
So I guess he is not banned anymore. or maybe his IP is banned

**Comment by DanielnetoDotCom** [comment]
Check if his user is not flagged as inactive

**Comment by JoshWho** [comment]
He is active and can chat on other channels just not the one

**Comment by DanielnetoDotCom** [comment]
can you please tell me what user is that had what chat is he banned from?

**Comment by JoshWho** [comment]
I sent you the account info

**Comment by DanielnetoDotCom** [comment]
I found the issue. 

I am sending a Chat2 update (version 8.6) that will include a "manage Bans" button that will let you see banned users from your account

![image](https://user-images.githubusercontent.com/18009293/147360830-31892296-a42c-4deb-836e-59ae21dad5b3.png)

**Comment by JoshWho** [comment]
Thank you. Just got the update and that made it real simple now. Thank you
