### ISSUE TITLE
Audit plugin error

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#6028]
With Audit plugin on, after the last update, 11.5, I get the message below before footer:

`[27-Nov-2021 08:04:37 America/Edmonton] AmyMySQLUserLog::ERROR: {"type":1,"message":"Uncaught TypeError: Return value of Audit::getEnd() must be an instance of boolean, none returned in \/var\/www\/www.mysite.com\/public_html\/plugin\/Audit\/Audit.php:67\nStack trace:\n#0 \/var\/www\/www.mysite.com\/public_html\/plugin\/AmyMySQLUserPlugin.php(584): Audit->getEnd()\n#1 \/var\/www\/www.mysite.com\/public_html\/objects\/include_end.php(3): AmyMySQLUserPlugin::getEnd()\n#2 \/var\/www\/www.mysite.com\/public_html\/view\/index.php(54): include('\/var\/www\/videos...')\n#3 {main}\n  thrown","file":"\/var\/www\/www.mysite.com\/public_html\/plugin\/Audit\/Audit.php","line":67} SCRIPT_NAME: /view/index.php
`
If I turn off and on, the message go away. But when I upload some video, the error message comes back.
Tried to clear cache, did not work.

**Comment by DanielnetoDotCom** [comment]
can you please try this update?

**Comment by swimitup** [comment]
Seems ok for now, I will let you know if there's any error message.
Thanks!

**Comment by swimitup** [comment]
Sorry, the error still coming after an upload:

`[27-Nov-2021 11:49:36 America/Edmonton] AmyMySQLUserLog::ERROR: {"type":1,"message":"Uncaught TypeError: Return value of Audit::getEnd() must be an instance of boolean, bool returned in \/var\/www\/www.mysite.com\/public_html\/plugin\/Audit\/Audit.php:68\nStack trace:\n#0 \/var\/www\/www.mysite.com\/public_html\/plugin\/AmyMySQLUserPlugin.php(584): Audit->getEnd()\n#1 \/var\/www\/www.mysite.com\/public_html\/objects\/include_end.php(3): AmyMySQLUserPlugin::getEnd()\n#2 \/var\/www\/www.mysite.com\/public_html\/view\/index.php(54): include('\/var\/www\/videos...')\n#3 {main}\n  thrown","file":"\/var\/www\/www.mysite.com\/public_html\/plugin\/Audit\/Audit.php","line":68} SCRIPT_NAME: /view/index.php
`

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by swimitup** [comment]
Hi Daniel,
it seems ok now. Thanks.
