### ISSUE TITLE
PPV LIVE ISSUE

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#6029]
When you installed the platform we run a few issues but now is showing this out the blue. I was creating an event and this will show when someone click on my event. Hope can be fix soon. 

![Screenshot_20211127-214150_Chrome](https://user-images.githubusercontent.com/63973045/143727551-a56e9880-a866-4a4d-abc6-bd0dc7f4b947.jpg)

**Comment by jengajenga** [comment]
is the plugin switched on? does the plugin need to be upgraded? or both?

**Comment by DanielnetoDotCom** [comment]
> When you installed the platform we run a few issues but now is showing this out the blue. I was creating an event and this will show when someone click on my event. Hope can be fix soon.
> 
> ![Screenshot_20211127-214150_Chrome](https://user-images.githubusercontent.com/63973045/143727551-a56e9880-a866-4a4d-abc6-bd0dc7f4b947.jpg)

Looks like you need to make a` git pull` on your server.

**Comment by LATINMIXMASTERS** [comment]
So you telling me things will stop working out the blue?? If i had it working then will stop working ???

**Comment by DanielnetoDotCom** [comment]
I am not sure what happened. I am just telling you the error code does not match the latest git pull.

so update it then if the error persists I will be able to find it based on your logs.

also, it can not appear from nothing. if was working before it only fails if you update or change some configuration.

**Comment by LATINMIXMASTERS** [comment]
Daniel i dont touch this you are the only one , thats why i am concern why a platform that has been working , for the sudden just create issues without touching it now i am scare for my users having something working and then stop because it change it selft 😳😳
