### ISSUE TITLE
A member that uses google pixel 3a. Probably over 5.5 inches says mobile site starts zoomed in

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6030]
A member posted to me that on mobile view with a google pixel 3a. Probably over 5.5 inches 

It starts out really zoomed in, but it corrects itself once switched from wide screen back to the long screen up and down rotating.

**Comment by DanielnetoDotCom** [comment]
tested on pixel 3 emulator and seems to be fine

![image](https://user-images.githubusercontent.com/18009293/143903629-8178595d-c09e-4129-8c87-ef0840209c47.png)
