### ISSUE TITLE
Modal hide behind new animation layer

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#6031]
If you enter into main page and then go to myvideos page through menu, the animation layer - nice - show the myvideos page. If you try any action for any video, like edit or move storage, the new modal window either do not show over the animation layer or it is way up in the screen. Check video:

https://user-images.githubusercontent.com/12404245/143777914-1225a26f-959b-4d66-82cb-a7659941bac2.mp4

But if you reload the page, all options appear ok once clicked.

**Comment by DanielnetoDotCom** [comment]
what browser are you using?

**Comment by swimitup** [comment]
Safari.

**Comment by DanielnetoDotCom** [comment]
I just tested on safari and it works. 

I am not 100% what is the issue, but can you please make a git pull and confirm if still a problem?
