### ISSUE TITLE
Where is this button to upgrade plugins?

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#6032]
![brave_Kes9M9Js3D](https://user-images.githubusercontent.com/66537018/143781083-bc2352b5-1323-48bb-82d0-777ce9005370.png)

**Comment by DanielnetoDotCom** [comment]
I guess you mean this ...

![chrome-capture (4)](https://user-images.githubusercontent.com/18009293/143871537-dd4e4258-fa29-44f4-a00d-1b64c0bbc403.gif)

FYI the free plugins are updated on the git pull.
the paid plugins you can update downloading it from marketplace

**Comment by fakeologist** [comment]
yes that's what I was looking for thanks.
