### ISSUE TITLE
Script Update

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#6033]
My site is not updating. I am still on version 8.0. I tried running the update command in the script itself and also ssh however its not updating. Can you please assist

**Comment by DanielnetoDotCom** [comment]
version 8 is too old but still possible to update.

Make sure you do not miss this 
https://github.com/WWBN/AVideo/issues/5075#issuecomment-833764155

also make sure you update all your paid plugins

**Comment by venwebsites** [comment]
Hello,Can you help assist with the update Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Daniel Neto ***@***.***> Date: 11/30/21  7:52 AM  (GMT-05:00) To: WWBN/AVideo ***@***.***> Cc: venwebsites ***@***.***>, Author ***@***.***> Subject: Re: [WWBN/AVideo] Script Update (Issue #6033) 
version 8 is too old but still possible to update.
Make sure you do not miss this
#5075 (comment)
also make sure you update all your paid plugins

**Comment by DanielnetoDotCom** [comment]
you can hire me to update it for you.

**Comment by venwebsites** [comment]
How much would you charge Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Daniel Neto ***@***.***> Date: 12/1/21  11:26 AM  (GMT-05:00) To: WWBN/AVideo ***@***.***> Cc: venwebsites ***@***.***>, Author ***@***.***> Subject: Re: [WWBN/AVideo] Script Update (Issue #6033) 
you can hire me to update it for you.

**Comment by DanielnetoDotCom** [comment]
If the original installation was made by me, 1 hour should be enough

if you or somebody else did the installation we can start with 2 hours of support and depending of what is missing you may need to hire me for extra hours 

you can purchase the support hours here https://youphp.tube/marketplace/

**Comment by venwebsites** [comment]
You did the installation if you remember I did it on Centos 7 however you took over and wiped it out and put it on Ubuntu. So how do I go about paying you my friendSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Daniel Neto ***@***.***> Date: 12/1/21  12:00 PM  (GMT-05:00) To: WWBN/AVideo ***@***.***> Cc: venwebsites ***@***.***>, Author ***@***.***> Subject: Re: [WWBN/AVideo] Script Update (Issue #6033) 
If the original installation was made by me, 1 hour should be enough
if you or somebody else did the installation we can start with 2 hours of support and depending of what is missing you may need to hire me for extra hours
you can purchase the support hours here https://youphp.tube/marketplace/

**Comment by venwebsites** [comment]
I do t see the support button I must be missing it Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Daniel Neto ***@***.***> Date: 12/1/21  12:00 PM  (GMT-05:00) To: WWBN/AVideo ***@***.***> Cc: venwebsites ***@***.***>, Author ***@***.***> Subject: Re: [WWBN/AVideo] Script Update (Issue #6033) 
If the original installation was made by me, 1 hour should be enough
if you or somebody else did the installation we can start with 2 hours of support and depending of what is missing you may need to hire me for extra hours
you can purchase the support hours here https://youphp.tube/marketplace/

**Comment by DanielnetoDotCom** [comment]
If still my installation (no changes) 1 hour should be enough

You should be able to find the support hour here 
![chrome-capture (8)](https://user-images.githubusercontent.com/18009293/144284163-92e8faba-d9a1-430d-8bb8-cc741c46370f.gif)

**Comment by venwebsites** [comment]
I am embarrassed to say but do you remember my username and password. I believe I used my venwebsites email to create the account. 

 

***@***.*** ***@***.***> 

***@***.*** ***@***.***> 

***@***.*** ***@***.***>

**Comment by DanielnetoDotCom** [comment]
You can recover the site password with this https://github.com/WWBN/AVideo/wiki/Reset-a-Password

**Comment by venwebsites** [comment]
Try this

 

Ssh : 47.21.13.248

User : prostreams

Password : @tsc0mptech

 

The 0 is a zero 😊 

 

I tested and I am in

**Comment by DanielnetoDotCom** [comment]
Make sure you do not provide passwords on github
