### ISSUE TITLE
Disk Upload Quota

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6036]
@DanielnetoDotCom 

the plugin disk upload quota, what else is available apart from Stripe? Stripe is not in my country but i would like to buy and use the plugin.

How does one pay via paypal?

**Comment by DanielnetoDotCom** [comment]
Hi, 

I may add PayPal in the future, for now, we support only stripe for subscriptions.

you can also use it for free plans or for using the wallet balance.

the wallet balance can be filled with Paypal (not recurrent payment.)
