### ISSUE TITLE
Incomplete app

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#6038]
Incomplete app.
In the menu missing some voices like, My channel, my video and others.

Where for setting for have this?

![Screenshot_20211201_084533_excalibur4 com](https://user-images.githubusercontent.com/93554732/144192990-44484608-be5a-4cad-b38f-fbc4b98a855e.jpg)
![Screenshot_20211201_084542_excalibur4 com](https://user-images.githubusercontent.com/93554732/144193016-f04e09dd-9bc7-43b5-b3e4-f8ef072910fb.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi

currently, we do not have those items on the app

**Comment by toplive24** [comment]
So what is this App for?

**Comment by DanielnetoDotCom** [comment]
you can make live streams and receive notifications on your phone.

also, watch videos VOD and Live

again, you will never find an app with all the same features that they have on the website.

I am not saying I will never add those features, I am just saying you cannot expect all the same features

**Comment by toplive24** [comment]
90 % of the people use now phone

**Comment by DanielnetoDotCom** [comment]
you can use the website thru your phone browser, and you will have ALMOST all the features you have on PC

**Comment by toplive24** [comment]
I know this but then it was useless to buy the Apps if the basic things are missing? 
I sent you a long email.
