### ISSUE TITLE
Video search disable playlist add option on Video manager when too many.

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#6039]
**Describe the bug**
When you search for a video on "My Videos", the option to add the video to a playlist ( program ), disappears when I select "Show all option"
![image](https://user-images.githubusercontent.com/52116577/144285007-ac7ef2de-6f30-49c9-b406-eaa0594f8202.png)
![image](https://user-images.githubusercontent.com/52116577/144284658-0fe7a6d2-9131-43f8-a596-8e2814c97c1e.png)

**To Reproduce**
1-Create a playlist ( any , or already an existing one )
2- Search for a video ( by title )
3- You can see the playlist add option is missing when selecting show all. 
![image](https://user-images.githubusercontent.com/52116577/144285455-f312c878-2e9f-40a4-b4f8-d79b9cc5a72b.png)

PS : This issue could be related to an old issue with some hidden variables, but I don't know witch one.

`$global['rowCount']` ?? or
`$global['limitForUnlimitedVideos']` ?

**Comment by DanielnetoDotCom** [comment]
Hi, if you list 50 or more items we do not show the playlists.

We do it to avoid overload your server, currently on the videos manager each playlist is a request

**Comment by akhilleusuggo** [comment]
I know, that was the question.
