### ISSUE TITLE
Wrong icon or position number of views

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#6040]
Using the gallery theme, the views number is displaying using the wrong icon, or maybe it is exchanged with the subscribers:

![Screen Shot 2021-12-01 at 13 06 36](https://user-images.githubusercontent.com/12404245/144306259-e9695454-085b-4c5a-8f01-b149bc67228c.jpg)

**Comment by DanielnetoDotCom** [comment]
they really are the same icon.

we use https://fontawesome.com/v5.15/icons , try to suggest another icon. if is a good idea we can change one of them

**Comment by JoshWho** [comment]
The live View count should not be showing on the regular playback videos. That is the confusion most see.
