### ISSUE TITLE
LDAP Plugin Authentication - rdn

### ISSUE THREAD

**Issue by aiot1974** [WWBN/AVideo#6041]
I recently bought the "login LDAP" plugin. But I don't see how to configure it to query users in active directory with a service account. In other words, consult the user accounts with an account with user read permissions.
Our internal domain is box.pma
We have tried configuring in rdn:
{$users}
{$user}@box.pma
uid={user},ou=Users,dc=box,dc=pma
We read what is explained in the following link; but we have not been able to implement the PlugIn
https://youphptube.readthedocs.io/en/latest/plugins/ldap.html

We do not see where we can place the username and password of the service user to consult the users within the active directory.

Our Active Directory is a 2019 standard OS and functional level 2012 r2.

How can I make use of LoginLDAP with this infrastructure.

I have very little knowledge in PHP

Thank you.

**Comment by DanielnetoDotCom** [comment]
Hi

the only thing I can see is this ...

`uid={user},ou=Users,dc=box,dc=pma`

it supposed to be this 

`uid={$user},ou=Users,dc=box,dc=pma`

Also please make sure you follow this https://github.com/WWBN/AVideo/wiki/Configure-LDAP-Plugin


the user name and password will be the ones you will put on the login form. we will use the user credentials to query your LDAP server

**Comment by aiot1974** [comment]
Hello, thanks for your prompt reply..

After reviewing my settings and making a change in the LoginLDAP Plugin..

In the server field, I changed the settings from ldap: //10.10.8.1 to 10.10.8.1
In the RDN field I use the format {$user}@box.pma
And it worked!
Each new user who enters through the LoginLDAP portal, the user is automatically added to the list of users on the server.

Thank you very much for your attention

Excellent Project!
