### ISSUE TITLE
Disable Webp Thumbnail Animation

### ISSUE THREAD

**Issue by DrDoug88** [WWBN/AVideo#6042]
Is there a way to disable Webp thumbnail animation creation? 

After encoding, I noticed that the videos were all resulting with the standard vanguard clip, rather than a short clip when mouse-over was performed. I found this article on the forum which addresses this:

https://github.com/WWBN/AVideo/issues/5737

Based on our current setup, I do not want to through the process of trying to recompile ffmpeg with --enable-libwebp, it is too much of a risk on the production machine. I don't have a test environment up and working right now, but I am looking to go this route for future issues that need more thorough testing. 

Anyhow, I'm just looking for a medium term fix. Right now, I am manually going into the video folder and simply deleting the webp file. It will then revert to the gif that is also created in the process, so I still get the mouse-over animation. I just want to disable the webp creation alltogether. Is this an easy request? Not sure if this should be in Questions or Feature Requests.

Thanks in advance

**Comment by DanielnetoDotCom** [comment]
what OS version are you using?

usually the default apt-get from Ubuntu 18+ works good
