### ISSUE TITLE
Error  after latest git pull

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6043]
![Screenshot_20211201-170438_Samsung Internet](https://user-images.githubusercontent.com/70327833/144334009-588af243-67bd-422a-80e7-0497185f47a5.jpg)

**Comment by DanielnetoDotCom** [comment]
If you do not have this installed, your notifications should never work

try this

`sudo apt-get install php-xml`

**Comment by milehighkaraoke** [comment]
Thank you, now I am wondering if ubuntu update did this.

**Comment by DanielnetoDotCom** [comment]
maybe, if you update PHP automatically you may be missing that

**Comment by milehighkaraoke** [comment]
Thank you kindly for your help today.....

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom I found the issue my ubuntu updated from 18:04 to 20:04. I must have not been reading when I was pushing ok and next.  Now my log in sits and spins and it takes it extremely long to finally log in. Is there another php extension or apache extension that I am missing that would cause  this as there is no error in the log

**Comment by DanielnetoDotCom** [comment]
Hi

make sure the videos folder has the correct permission (777) and your paid plugins are up to date

**Comment by milehighkaraoke** [comment]
I will apply those permissions again and no plugin is showing that there is an update available

**Comment by milehighkaraoke** [comment]
Lack of 777 permission was the entire log in hanging problem . thank you! @DanielnetoDotCom
