### ISSUE TITLE
After latest gitpull Live no longer shows on main page when streaming

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6044]
I have to share the direct link so people can access my live link it no longer shows up it shows 0 now for live streams
Link works from individuals live stream share tab
![16384138609738470297427433421102](https://user-images.githubusercontent.com/70327833/144349594-952efa37-b50f-4e1b-9bf0-cd6a38d4100f.jpg)
![16384138978062924820483448771360](https://user-images.githubusercontent.com/70327833/144349617-238d2ae2-a423-406c-a350-cd7d89155a6d.jpg)
![16384139292791466465492357136914](https://user-images.githubusercontent.com/70327833/144349768-d1f9d8d7-fa7a-4c7d-b41d-69eb00c744ca.jpg)

**Comment by milehighkaraoke** [comment]
![Screenshot_20211202-000049_Facebook](https://user-images.githubusercontent.com/70327833/144373871-ce3b280d-fe50-4aef-bcbf-f5e11730995f.jpg)

**Comment by DanielnetoDotCom** [comment]
try to clear your cache and see if it makes any difference.

If it does not make any difference. please restart your socket server, or maybe just restart your server.

**Comment by LATINMIXMASTERS** [comment]
Yes need to clear cache , that is happening to me a lot every time someone goes live i have to clear cache, Daniel can you check why??

**Comment by DanielnetoDotCom** [comment]
I am having a hard time reproducing it. 

@LATINMIXMASTERS does this always happen with you? if I start a stream now will I see this issue?

**Comment by LATINMIXMASTERS** [comment]
Yes been happening lately i had to clear cache so the live streaming be showing on app and website.

**Comment by jengajenga** [comment]
I am having the same error.  Streams suddenly disappear and the videos say offline. Then I have to clear cache (usually first page cache) or reset my streamkey. 

Could you possibly make an option for disabling cache (if that is really the case)?

![offline-while-live2](https://user-images.githubusercontent.com/65451390/144716936-b204769d-f1b0-4611-aa9c-f34179f893d5.PNG)

![offline-while-live](https://user-images.githubusercontent.com/65451390/144716925-4524e0c7-f596-491c-bcfa-74e316c29487.jpeg)

**Comment by ganddser** [comment]
@DanielnetoDotCom It's the same issue I told you about. Right now I can see 2 live notifications, but I know there are 3 live streams at this very moment. Sometimes it'll show 0 lives other times it shows 2 out of 3 or 3 out of 4 and so on. It's always missing all or 1. Strange error.
![Untitled-60](https://user-images.githubusercontent.com/37193130/144725586-4dd84caa-ce8c-4828-bc65-9e5519e4007e.jpg) (Not signed in at all)

![Untitled-2](https://user-images.githubusercontent.com/37193130/144725637-3580db82-277a-43be-bd01-6196e6461933.jpg) (Signed in as admin)

**Comment by DanielnetoDotCom** [comment]
I am not sure what is causing this and I could not reproduce it. but I will review the notification

**Comment by jengajenga** [comment]
@DanielnetoDotCom please review. I'm suffering heavy losses regards to streaming because of it.

**Comment by DanielnetoDotCom** [comment]
I need to be able to reproduce that.

on my side, it is working properly so it may be something specific to your configuration. but definitely, I will review the notifications.

**Comment by ganddser** [comment]
Yes it's a serious problem. @DanielnetoDotCom could you look at our sites to see if you're getting the live notifications?

**Comment by DanielnetoDotCom** [comment]
If you hire me for the support I can look it directly into your site.

**Comment by LATINMIXMASTERS** [comment]
His direct support is worth it. I will suggest getting it @ganddser

**Comment by ganddser** [comment]
@LATINMIXMASTERS Yeah that's typically how we handle issues, was only reaffirming the issue.

**Comment by jengajenga** [comment]
This is a bug issue. It is with the cache or the notification and the link surrounding the two. As we speak I have 22 streams, but showing 5 on the notification and 5 on the homepage.

I've raised this issue severally and it seems others have the same problem. Why now must we have you look at it exclusively for paid support?

It's not something that can be reproduced on the demo site because it is something that just happens. And we don't know how.

You said you'd look at notification; did you?

**Comment by jengajenga** [comment]
See above: 21 notifications, 5 actual streams.

Sometimes it's the opposite.

**Comment by jengajenga** [comment]
![offline-but-online](https://user-images.githubusercontent.com/65451390/145344839-6cc6308c-83d2-4d65-a3c8-5e07b007872f.jpeg)

And this as well. It shows offline but is very online. Customers call to ask why am I offline when i am streaming?

**Comment by milehighkaraoke** [comment]
Are you running 18.04 ?  If so update to Ubuntu 20.04 it updates php and it fixed this problem for me

**Comment by jengajenga** [comment]
I'm running 20.04, php8

> Are you running 18.04 ? If so update to Ubuntu 20.04 it updates php and it fixed this problem for me

**Comment by milehighkaraoke** [comment]
Php 8.0 gave me all sorts of issues. I reinstalled and started over

**Comment by jengajenga** [comment]
> Php 8.0 gave me all sorts of issues. I reinstalled and started over

Let me give you a brief

I've used this system since version 9.2. I'm on my 3rd server now due to growth of service.  It is on the second server that this began to happen. I had 18.04 and php7.3. I upgraded to 20.04 and php7.43. Still the same issues. I'm now on 20.04 with php8 and still the same issue.

If it is a php issue, or a socket issue, or a cache issue, then it can be stated clearly so that it is sorted permanently? I'm sure it is a known issue but the question of where the real problem occurs is what defeats me (and probably also Neto).

The log files don't really say anything when it happens.

**Comment by DanielnetoDotCom** [comment]
Currently I do not o ow where the problem comes from. That is why I will need to be able to reproduce it so I can find a solution.

I do not think update Ubuntu or php will resolve it .

**Comment by jengajenga** [comment]
@DanielnetoDotCom  can you make an option to NOT have first page cache?

**Comment by DanielnetoDotCom** [comment]
I just sent an update, if you set` $global['ignoreAllCache'] = 1;` in your configuration.php file your site will ignore all cache

**Comment by JoshWho** [comment]
I get this issue a lot and I usually resolve it by restarting NGINX still no clue why it happens. I think it has something to do with what detects there is a live stream going.

**Comment by jengajenga** [comment]
> I just sent an update, if you set` $global['ignoreAllCache'] = 1;` in your configuration.php file your site will ignore all cache

Thanks. I've just done the update. I'll monitor and let you know.

**Comment by jengajenga** [comment]
> I get this issue a lot and I usually resolve it by restarting NGINX still no clue why it happens. I think it has something to do with what detects there is a live stream going.

how many times do you restart nginx in a day? for me i would have to do it almost every 3 or so minutes.

**Comment by jengajenga** [comment]
> I just sent an update, if you set` $global['ignoreAllCache'] = 1;` in your configuration.php file your site will ignore all cache



> > I just sent an update, if you set` $global['ignoreAllCache'] = 1;` in your configuration.php file your site will ignore all cache
> 
> Thanks. I've just done the update. I'll monitor and let you know.

It's still doing the same thing. I think @JoshWho is right. It has something to do with the detection of streams. Either something times out or lags. Or the request for number of streams isn't being responded to.

**Comment by JoshWho** [comment]
I do not think it is site wide. It seems to be the individual viewing could
be getting timed out. While I see one of my computers not showing the live
s my other computer on another ip is seeing them.

**Comment by DanielnetoDotCom** [comment]
Hi, just to make clear, ever with` $global['ignoreAllCache'] = 1;` still the same problem?

**Comment by jengajenga** [comment]
> Hi, just to make clear, ever with` $global['ignoreAllCache'] = 1;` still the same problem?

Yes. Still the same problem.

**Comment by jengajenga** [comment]
@DanielnetoDotCom 

So in the Live settings, I clicked "Do not show notifications" and then clicked save. For the past 10 minutes, the site is only showing 2 Live Links that I added and One upcoming PPVLive event. In the notification bar in the navbar, it shows "3". The main streams are not showing.

This issue may be directly linked to notifications. 

When i uncheck "Do not show notifications" so that it shows notifications, then the site returns to normal, but continues to drop live streams and make them disappear.

How notifications is linked to live which is linked to the front page which is linked to requests for information from the server could be the problem. There is some miscommunication somewhere along that chain.

**Comment by DanielnetoDotCom** [comment]
Hi

the issue is on the Live plugin or livelinks plugin?

when disappear is one of them or both disappear?

**Comment by jengajenga** [comment]
> Hi
> 
> the issue is on the Live plugin or livelinks plugin?
> 
> when disappear is one of them or both disappear?

Live Links remain. The other lives from the live plugin disappear. 

I've sent you my site link via email with some brief instructions. you may respond here after observing.

**Comment by jengajenga** [comment]
@DanielnetoDotCom did you observe the situation on my site?

**Comment by jengajenga** [comment]
@DanielnetoDotCom 

See this screenshot. It looks like time this disappearance happens, this error is captured.

![on-publish](https://user-images.githubusercontent.com/65451390/146328101-ead0d290-dee3-4452-b802-2dda858489da.jpeg)

Could you check the on_publish.php and also the "disconnect before handshake"?

**Comment by DanielnetoDotCom** [comment]
I really need to find some free time to look deeper into it. as soon as I get some free time I will inspect it with more details.

**Comment by DanielnetoDotCom** [comment]
Please check the last update, I guess I found something.
