### ISSUE TITLE
What am I doing wrong with SaveDVR?

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6046]
@DanielnetoDotCom 

I have properly set up all the standalone files. When I click record, I get "Success" but no actual recording

When I click Save this Live i get this error

"Error saveDVR ERROR: File /home/xxx/xxx/public_html/videos/cache/v_21120xxxxxxxx_v29a5.mp4 is too small: 2.35KB"

Liveservers DVR is enabled
Live DVR is enabled
Necessary folders have the correct permissions 777

Any help?

**Comment by DanielnetoDotCom** [comment]
I would try 777 permission 

Please describe exactly how do you have your live server.

in a different server? on the same server?

how is your control URL?

**Comment by jengajenga** [comment]
Control server: http://localhost:port - there required port is open
Liveserver: On the same server. It works as streams are going through
Record path: /var/rec/ with chmod 777

**Comment by DanielnetoDotCom** [comment]
Save DVR does not read /var/rec/

It reads  hls_path `/HLS/live`

https://github.com/WWBN/AVideo/blob/6073004695fd84a9eec7c73ca4fe19aec6223986/plugin/Live/standAloneFiles/saveDVR.json.php#L36

please make sure your hls_path  is readable and also you have the FFMPEG installed on the Liveserver.

if still failing please check apache and avideo log files

**Comment by jengajenga** [comment]
> Save DVR does not read `/var/rec/`
> 
> It reads hls_path `/HLS/live`
> 
> https://github.com/WWBN/AVideo/blob/6073004695fd84a9eec7c73ca4fe19aec6223986/plugin/Live/standAloneFiles/saveDVR.json.php#L36
> 
> please make sure your hls_path is readable and also you have the FFMPEG installed on the Liveserver.
> 
> if still failing please check apache and avideo log files

that path is default. i was referring to the /var/www/tmp which i modified to /var/rec/ and gave 777 permissions.

i think i've figured out where the issue is - the user:group combination that i have in my setup. if it fails i will reopen another case.
