### ISSUE TITLE
YPT Wallet 2FA

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6047]
@DanielnetoDotCom 

Consider adding 2FA for the wallet transfer function. Maybe it can send a code via email or sms or even whatsapp. Just to make it extra secure in case some one by chance gets access without authority.

Please consider.

Thank you.

**Comment by DanielnetoDotCom** [comment]
Agree, on the wallet and also in other features a 2FA may be required

**Comment by jengajenga** [comment]
Thanks. Hoping to see this soon.
