### ISSUE TITLE
DISK QUOTA KEEP SHOWING VIDEOS

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#6048]
If an user does not have memory how his or her videos keep playing like normal. Right now i have an user with 500mb and he did a live streaming and the file is like 3.5gb but got saved and was send to the category. So i am confused if we ha e a disk quota and that user does not have memory how the video got stored and is playing normaly.

**Comment by DanielnetoDotCom** [comment]
I guess admin can play any video, you should try with a regular user

Also make sure you checked this

![image](https://user-images.githubusercontent.com/18009293/144504352-987472ff-0772-4668-9ada-acb0cc48eb82.png)

**Comment by LATINMIXMASTERS** [comment]
Yes i am using a regular account , but my issue is that still every live get saved not matter what the user not having memory so does not make sence i can understand  the video be there to let user see it if they want to buy memory but if they not then to deleted because take space and i am paying for it. Also the video should not be place in any area since the video cannot be play so what can be done. And when i click the video on regular user is showing this. 

![Screenshot_20211202-171300_Music and Stream](https://user-images.githubusercontent.com/63973045/144511634-9a3bd440-3c48-4201-b2ba-b3b57a8cb9d1.jpg)
![Screenshot_20211202-171312_Music and Stream](https://user-images.githubusercontent.com/63973045/144511639-2b174a75-df84-4237-afab-89a7a16ef2a0.jpg)

**Comment by DanielnetoDotCom** [comment]
That is the reason why you still see videos 

![image](https://user-images.githubusercontent.com/18009293/144512916-0ecfcc97-fd6a-4e04-8c40-0dfa8321358a.png)

**Comment by LATINMIXMASTERS** [comment]
Ok that setting is off but still showing video on list 
![Screenshot_20211202-174214_Chrome](https://user-images.githubusercontent.com/63973045/144514852-cfaab372-9ba6-4c2c-b72d-f3958521fd2b.jpg)

**Comment by DanielnetoDotCom** [comment]
try to clear the cache
if still showing you may need to inactivate the user to have his videos disappear. 

I may add some changes in the future to not list the user's videos.

**Comment by LATINMIXMASTERS** [comment]
I dont want to inactivate his account since nothing bad is just does not make sence having disk quota but still videos showing on app and website while they cannot be played due to his memory. Then i will have many users like that. So what can i do. I offer a plan fornfre with 500mb so i dont get why the disk quota is not working properly

**Comment by LATINMIXMASTERS** [comment]
Also how a User with 500mb can still have above that memory obviously the error here is the live streaming because it wont let you upload mp3 or mp4 thru encoder if you dont have memory. I hope so. Because if not then i will be paying as an admin for memory people are using but not paying for .  

![Screenshot_20211202-175533_Chrome](https://user-images.githubusercontent.com/63973045/144516284-235ca34e-34df-44be-b4ba-291aecd89c7d.jpg)

**Comment by DanielnetoDotCom** [comment]
but can this user still upload videos?

if he uploads something and the limit change later we cannot delete his videos.

**Comment by LATINMIXMASTERS** [comment]
Well the upload is not the issue , is when going live all videos are saved without the user having memory and then is appearing all over the app and website and when clicking said No PPV so i want to know why an user can have on their profile more memory aince they had only 500mb. But i will keep checking on my end. Hope you find a solution. I will keep you up to date if i find anything.

**Comment by DanielnetoDotCom** [comment]
I see, the live recorder is not respecting the Diskquota, is that correct?

**Comment by LATINMIXMASTERS** [comment]
Well what i can see correct.

**Comment by DanielnetoDotCom** [comment]
for you to understand. if you have a 1GB limit, and you send to the encoder a 1GB file. due to the multiple resolutions, this 1GB file may turn into a 2GB video.

and the same may happen if you upload a 2GB in 4K, when you encode it into a 720p video it may reduce the video size.

so we will store the video while you have storage free, but once the storage is full it does not suppose to accept new videos anymore even recorded videos.  

Can you please confirm if the user sends something to record again, will it be processed?

**Comment by LATINMIXMASTERS** [comment]
Ok i will test with a new account i created with no memory and see what happened when i finished the live streaming Let you know.
