### ISSUE TITLE
I need a permanent fix for channel/stream disappearance

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6049]
@DanielnetoDotCom  hi 

I've raised this issue before. Streams will suddenly disappear or drop where the notification is. I have around 35 streams regular and suddenly they are 6 or they are 4. DVR links under the screen disappear and the videos read offline but they still play. When this happens, at the front page only the 4 that are lucky to be left alive will be seen.

Because of this issue I now have 19 regular streamers - i have lost some clients coz of this.

My socket is working and it never goes off.

And no I am not able to replicate it on the demo server.

Can you please make a fix for it.

![4](https://user-images.githubusercontent.com/65451390/144568331-650ad4d4-b444-4868-b67f-9820f2efc477.jpeg)

![offline-while-live](https://user-images.githubusercontent.com/65451390/144568397-26bafa28-1f33-4104-81bb-ddf54e5e310f.jpeg)

Is it a cookie issue? Is it a cache problem? is it a category/live problem? is it a stats.json.php problem? is something timing out somewhere and then restarting?

Please assist.

Thank you.

**Comment by jengajenga** [comment]
![offline-while-live2](https://user-images.githubusercontent.com/65451390/144579650-b050f98b-2d07-4e9b-ac7b-923d4a4fccc9.PNG)

happens when it feels like

**Comment by jengajenga** [comment]
Looks like when I clear front page cache or reset the stream key it goes back to normal.

But then it happens randomly and I am not around always to clear cache or rese the key.

**Comment by DanielnetoDotCom** [comment]
Hi, this is related to this error. I will review it

https://github.com/WWBN/AVideo/issues/6044

lets follow the updates on that thread

**Comment by ganddser** [comment]
@DanielnetoDotCom this is exactly what's happening on my site something is triggering kill publish but it almost instantly republishes resulting in 3 or 4 pieces of a recording that should be an hour long. Can't find any issues with the server to explain this behavior.
