### ISSUE TITLE
Chat is broken on Firefox

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6050]
@DanielnetoDotCom  hi

Chat2 is broken on Firefox.

It won't close fully when you click the X button. Instead it remains on screen and covers the video player.

When you click the black icon at the bottom, it only pushes back the screen but doesn't expand outwards because it won't close.

Screenshot shows what happens when chat is open. The video side of the screen is pushed back.
![chat-open](https://user-images.githubusercontent.com/65451390/144580432-9802aa11-6419-4f76-a5d7-927a23574ea9.PNG)

Screenshot shows what happens when chat is closed. The chat remains open and the video side of the screen goes under the chat.
![chat-close](https://user-images.githubusercontent.com/65451390/144580662-5983e71b-0230-4bbe-9a53-d3cc7ef1e8d2.PNG)

**Comment by DanielnetoDotCom** [comment]
Can you please download the chat2 version I released yesterday?

**Comment by jengajenga** [comment]
I am using that very version. I never miss an update.

**Comment by DanielnetoDotCom** [comment]
I mean, I released an update yesterday and did not change the version number. can you please confirm if you have the latest?

**Comment by Lordblanca** [comment]
Hveing same problem after update to 8.5. Did update on 12-5-2021 with pull.  #6054
