### ISSUE TITLE
Rate limiting in Nginx

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6051]
@DanielnetoDotCom hi

I know it is possible by adding a few lines of code to limit the incoming bitrate to ensure it doesn't exceed a certain amount.

Can you add to the .conf file?

Ref: https://www.tuxtips.net/how-to-limit-http-bandwidth-in-nginx/

==================================

2- limit http bandwidth
For limiting http bandwidth, we use limit_rate directive. you can use it in location {}, server {} and http {} directive. here we use it in http {} directive and paste the following line in it:

# limit_rate 50k;
this line tells Nginx to limit bandwidth to 50 kilobytes per second for a single connection. this means that client can open more than one connection and get more bandwidth. so we need to limit number of connections also:

# limit_conn_zone $binary_remote_addr zone=addr:10m;
we put above line in http{} directive.

# limit_conn addr 1;
in this tutorial, we assume that there is directory called “download/” in /var/www/html” and Nginx has been configured to use “/var/www/html” directory as root document.
so we want to apply limit on “download/” directory. find directive related to “download” and add the following line in it:

location /download/ {
limit_rate 50k;
limit_conn addr 1;
}

this line tells Nginx to limit number of connections to 1 per IP address, because previously we used “$binary_remote_addr” as key.
for more information about usable keys, refer to https://nginx.org/en/docs/http/ngx_http_core_module.html?&_ga=2.240776960.2093580261.1579695212-898961125.1578754976#variables
so our final configuration will be something like this:

http {
limit_conn_zone $binary_remote_address zone=addr:10m

server {
root /var/www/html;
limit_conn addr 5;

location / {
}

location /download/ {
limit_conn addr 1;
limit_rate 50k;
}
}
}
Copy

3- Test limiting

to test if our configuration works properly, we put a 700MB file in “download” directory and download it with a download manager like IDM. also we configure IDM to establish more than 1 connection.

**Comment by DanielnetoDotCom** [comment]
Hi, 

sounds like a good idea, but first, let me make sure I understand it properly...


## The problem

you are worried about a single user starting/watching multiple lives at the same time and consuming too much bandwidth.

is that correct?

## Solution

### limit_rate 

add a limit that is enough to transmit/consume a live stream

### limit_conn 

limit the total client connection.

## What I think

I am not sure, the configuration snippet you shared here seems to be a web server configuration, NOT an Nginx RTMP configuration, so it would only limit the live stream playback

currently, the best solution I see for live stream [bandwidth and simultaneous lives ](https://github.com/WWBN/AVideo/wiki/Live-Plugin#how-many-simultaneous-users-can-i-have)is to use the [CDN](https://github.com/WWBN/AVideo/wiki/CDN-Plugin). [the CDN](https://github.com/WWBN/AVideo/wiki/CDN-Plugin) can handle thousands of viewers and you only pay as you use.

**Comment by jengajenga** [comment]
basically, see this screenshot. this streamer is sending in 7mbps - which is too high. i want him to send no more than 1.5mbps and if he sends higher, stream is dropped or made idle.

![bandwidth-2](https://user-images.githubusercontent.com/65451390/144645624-20c9cbde-508b-4e2d-9b74-f5ea203bf093.PNG)

Also if all the streams could be standard - like all of them 720p 25fps 1.5mbps - that would be great.

and if someone wants more he can pay 

just thinking out loud...

**Comment by DanielnetoDotCom** [comment]
the solution I can see is for you to use the adaptive mode 

so all will have the same resolution and bitrate 

https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream

**Comment by jengajenga** [comment]
> the solution I can see is for you to use the adaptive mode
> 
> so all will have the same resolution and bitrate
> 
> https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream

I tried it on my server and my my my the amount of processor it takes is always 100% and more. I have a 10-core server but with the number of streamers i have it is not even enough haha.

i'll use diplomacy and tell him to reduce.
