### ISSUE TITLE
error with Website after updating SSL Certificate. Cannot get into website

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#6052]
Hi 

I updated the SSL certificate on my server but now I cannot get into the website. I dont want to do any further damage, before i make it worse. Can I get assistance to check website through SSH please. Thank
![kollossus error on website](https://user-images.githubusercontent.com/53856825/144607064-6bb8e1ca-57b3-486b-b5f1-721856ffecb1.png)
s

**Comment by kollossus55** [comment]
Thanks

**Comment by DanielnetoDotCom** [comment]
try to manually delete the cache folder

or add the /user on the URL so you can login

**Comment by kollossus55** [comment]
Hi

Tried manually logging but no joy..
Where does the cache reside on system.. i can delete those files?

Regards

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DanielnetoDotCom** [comment]
`rm -R /var/www/html/AVideo/videos/cache`

or 

`rm -R /var/www/html/YouPHPTube/videos/cache`

**Comment by kollossus55** [comment]
Hi 

Done the above. re-updated the SSL certificate, but now the Website does'n seem to be showing properly. Is there something else I should do ?

regards 
![Website error](https://user-images.githubusercontent.com/53856825/144736047-2c176c13-7f43-47d7-bd61-3f0c2dede23f.png)

**Comment by Lordblanca** [comment]
Did you check that the name on the certs are the same as the  ones you had before?

**Comment by kollossus55** [comment]
hi  
I just re-installed the SSL certificate, without checking previous. Where would I need to go or what should I do now?

Thanks

**Comment by Lordblanca** [comment]
Who do you have for your SSL certs?

**Comment by Lordblanca** [comment]
The usual path in apache is:
/etc/ssl

**Comment by kollossus55** [comment]
hi 

there seems to be various in certs directory and openssl.cnf in  /etc/ssl.

I used certbot to issue a new one for openssl..
regards

**Comment by Lordblanca** [comment]
Are you using g lets encrypt?

**Comment by kollossus55** [comment]
Yes it was lets encrypt. Followed some instructions on the net. How should I approach this now..

**Comment by Lordblanca** [comment]
If so the directory for that is /etc/letsencrypt

**Comment by Lordblanca** [comment]
I'm no pro with lets encrypt but i'll try to help

**Comment by kollossus55** [comment]
sounds like I've got too many directories with the SSL stuff.

**Comment by kollossus55** [comment]
This is what Ive got in that directory..


accounts  csr   options-ssl-apache.conf  renewal-hooks
archive   keys  options-ssl-nginx.conf   ssl-dhparams.pem
cli.ini   live  renewal

**Comment by DanielnetoDotCom** [comment]
I guess you should google how to use the letsencrypt certbot and let it create your script automatically.

**Comment by kollossus55** [comment]
will do.. will it overwrite whats on the system now ?

**Comment by kollossus55** [comment]
If I have problems can I get support eg, logon to server..

**Comment by DanielnetoDotCom** [comment]
Letsenrypt is free and easy to install.

and definitely I can install it for you if you hire me for support

**Comment by kollossus55** [comment]
ok.. thanks trying it now..

**Comment by kollossus55** [comment]
Hi 
successfully loaded... All good now..

thanks for your help..
