### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6053]
Hi, Is it possible to install AVideo on Windows Server 2019 (Web Server IIS) without Apache ??

**Comment by jengajenga** [comment]
Nope. LAMP a must.

**Comment by milehighkaraoke** [comment]
Yes, First you have to install php packages in your IIS manager. 
https://youtu.be/k3hBfrGmNKk

**Comment by KrzysioMisio** [comment]
milehighkaraoke 
Everything works for you on Windows Server ??

> Yes, First you have to install php packages in your IIS manager. And MYSQL https://youtu.be/k3hBfrGmNKk

milehighkaraoke 
Everything works for you on Windows Server ??

**Comment by milehighkaraoke** [comment]
I had it installed and working on server 2016 with iis 7   it was a pain in the wazoo to get the php installed but 5hat might have been my servers prior configurations.
