### ISSUE TITLE
Chat 8.5 not working after last update

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#6054]
Upated chat to 8.5
First I did pull. downloaded the latest chat 8.5. 
After update. There is a Black circle at bottom right hand side of chat. Chat window will only open if I click on the black circle.
Chat will not close when I click on the X. The backround resizes.
Also I restarted the server
Video to show what it looks like

https://user-images.githubusercontent.com/37937968/144758636-91f5523f-f667-45af-8d8f-a782385331bd.mp4

**Comment by jengajenga** [comment]
Having the exact same issue with v8.5 both on microsoft edge (chromium) and firefox (gecko).

**Comment by DanielnetoDotCom** [comment]
what theme are you using?

**Comment by DanielnetoDotCom** [comment]
Also, make sure you have downloaded the plugin after Friday. 

there are some updates to fix some layout issues.

**Comment by Lordblanca** [comment]
I downloaded the chat app today 12-5-2021.. Did the pull today. All of it was done today.

**Comment by DanielnetoDotCom** [comment]
What theme are you using?

did you clear the cache?

**Comment by Lordblanca** [comment]
It is still the original theme that you put up. I'll cleared the cache.. Nothing has changed

**Comment by Lordblanca** [comment]
This is what I used. what you gave me...
sudo rm -R /var/www/html/AVideo/videos/cache

also, make sure the videos folder is writable.

sudo chmod -R 777 /var/www/html/AVideo/videos/

**Comment by Lordblanca** [comment]
Let me know if this is going to take a few days. I will revert back to the last back up I have.... Thanks

**Comment by DanielnetoDotCom** [comment]
can you please share your site URL where i can see the chat?

it does suppose to work

**Comment by Lordblanca** [comment]
https://lblivestream.com/

**Comment by DanielnetoDotCom** [comment]
requires a credentials, I could not check

**Comment by Lordblanca** [comment]
what do you need as far as credentials. let me know

**Comment by Lordblanca** [comment]
you already have an account on the server... **danielneto.com@gmail.com**

**Comment by Lordblanca** [comment]
Do you need root or just the server. IF just the server you are already admin on server danielneto.com@gmail.com

**Comment by Lordblanca** [comment]
Anything yet?

**Comment by Lordblanca** [comment]
Do you need. Access to sudo or to the server

**Comment by DanielnetoDotCom** [comment]
I am checking and this is really strange.

the same is not happening on my side.

I can only suspect or you did not update correctly with the git pull

or you did not update the plugin correctly.

try to delete the Chat2 plugin folder, download it again from the marketplace and upload it again.

**Comment by Lordblanca** [comment]
Ok I want to make sure I have the right code that you gave me. before I do this again. This is the code you gave me to do a pull
"cd /var/www/html/AVideo/ && sudo git pull".. Just so you know exactly what I did I did
"sudo apt-get update && sudo apt-get upgrade" then "cd /var/www/html/AVideo/ && sudo git pull"  then went to the app store and downloaded the latest version of the chat. 8.5. then uploaded the latest chat to the server. And that was on 12-05-2021. Restarted my server like I always do and then the error occurred with my server. Now before I came to the forum I ran the next set of code 

sudo rm -R /var/www/html/AVideo/videos/cache
also, make sure the videos folder is writable.
sudo chmod -R 777 /var/www/html/AVideo/videos/

Plus I had to recreate the *** in the "/var/www/html/AVideo/plugin/Backup" just to keep it 100...
Please let me know if this is the correct way to update and upgrade the server. Plus how do you want me to delete the chat 8.5 plugin so I do it exactly the way it needs to be done.

Plus I see that jengajenga #6044 had similar problems after the chat update as well.

**Comment by DanielnetoDotCom** [comment]
Basicaly you only need to run 

`cd /var/www/html/AVideo/ && sudo git pull`

after that please share the output, so we can confirm it was updated.

then delete the Chat2 folder

`sudo rm -R /var/www/html/AVideo/plugin/Chat2`

then upload the plugin again

**Comment by Lordblanca** [comment]
Ok be back in a few

**Comment by Lordblanca** [comment]
This is the latest Pull
Using username "root".
Keyboard-interactive authentication prompts from server:
End of keyboard-interactive prompts from server
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-91-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Sun Dec  5 23:23:21 2021 from 100.2.152.93
root@lblivestream:~# cd /var/www/html/AVideo/ && sudo git pull
remote: Enumerating objects: 87, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 59 (delta 50), reused 10 (delta 1), pack-reused 0
Unpacking objects: 100% (59/59), 6.82 KiB | 62.00 KiB/s, done.
From https://github.com/WWBN/AVideo
   2d99bc482..94d8034b9  master     -> origin/master
Updating 2d99bc482..94d8034b9
Fast-forward
 locale/function.php                           |  12 ++-
 objects/bcp47.php                             |   1 +
 objects/functions.php                         |   7 ++
 objects/include_config.php                    |   3 +
 objects/video_statistic.php                   |   4 +-
 plugin/AVideoPlugin.php                       |   1 +
 plugin/Cache/Cache.php                        |   1 -
 plugin/CustomizeUser/confirmVideoPassword.php |   4 +-
 plugin/Live/Live.php                          |  43 ++++++++-
 plugin/Live/Objects/LiveTransmition.php       |  21 ++++-
 plugin/Live/confirmLivePassword.php           | 126 ++++++++++++++++++++++++++
 plugin/Live/index.php                         |   3 +-
 plugin/Live/install/install.sql               |   1 +
 plugin/Live/install/updateV10.2.sql           |   2 +
 plugin/Live/saveLive.php                      |   1 +
 plugin/Live/tabs/tabStreamSettings.php        |  14 ++-
 plugin/Live/view/modeYoutubeLive.php          |  18 ++--
 plugin/User_Location/User_Location.php        |   7 ++
 18 files changed, 246 insertions(+), 23 deletions(-)
 create mode 100644 plugin/Live/confirmLivePassword.php
 create mode 100644 plugin/Live/install/updateV10.2.sql
root@lblivestream:/var/www/html/AVideo#

**Comment by Lordblanca** [comment]
doing upload to... Still same problem
![image](https://user-images.githubusercontent.com/37937968/144907767-7c0705b6-0d93-47b4-83f0-f41f262873c5.png)

**Comment by Lordblanca** [comment]
Will revert back to my back up and try again. This is not good

**Comment by Lordblanca** [comment]
reverted back to my back up everything is working correct now.

**Comment by Lordblanca** [comment]
Now going to do pull again with the way you want

**Comment by Lordblanca** [comment]
![image](https://user-images.githubusercontent.com/37937968/144910102-f0d086f4-36ac-4d06-96bb-f14f83be69e3.png)


Using username "root".
Keyboard-interactive authentication prompts from server:
End of keyboard-interactive prompts from server
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-91-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Tue Nov 23 22:16:36 2021 from 100.2.152.93
root@lblivestream:~# cd /var/www/html/AVideo/ && sudo git pull
remote: Enumerating objects: 395, done.
remote: Counting objects: 100% (345/345), done.
remote: Compressing objects: 100% (222/222), done.
remote: Total 395 (delta 248), reused 220 (delta 123), pack-reused 50
Receiving objects: 100% (395/395), 290.51 KiB | 2.48 MiB/s, done.
Resolving deltas: 100% (255/255), completed with 31 local objects.
From https://github.com/WWBN/AVideo
   3f2127a2b..3756de9a3  master     -> origin/master
Updating 3f2127a2b..3756de9a3
Fast-forward
 .github/workflows/validate.yml                |   2 +-
 .gitignore                                    |   3 +-
 install/deleteTGZFiles.php                    |  26 ++++++
 install/getAllWebp.php                        |  11 ++-
 install/updatedb.php                          |  62 +++++++++++++
 locale/function.php                           |  12 ++-
 objects/bcp47.php                             |   1 +
 objects/categories.json.php                   |   2 +-
 objects/category.php                          |   4 +-
 objects/functions.php                         |  65 ++++++++++---
 objects/include_config.php                    |   3 +
 objects/playlist.php                          |   4 +-
 objects/subscribe.php                         |   6 +-
 objects/user.php                              |  32 ++++++-
 objects/video.php                             |   4 +-
 objects/videoAddViewCount.json.php            |  12 +--
 objects/video_statistic.php                   |   4 +-
 plugin/ADs/ADs.php                            |  14 ++-
 plugin/AVideoPlugin.php                       |   1 +
 plugin/Audit/Audit.php                        |  35 +++++--
 plugin/Audit/Objects/AuditTable.php           |  16 ++++
 plugin/Cache/Cache.php                        |   1 -
 plugin/Cache/Objects/CachesInDB.php           |  12 +++
 plugin/CustomizeUser/CustomizeUser.php        |  12 +--
 plugin/CustomizeUser/confirmVideoPassword.php |   4 +-
 plugin/CustomizeUser/setSubscribers.json.php  |  25 +++++
 plugin/CustomizeUser/setSubscribers.php       |  58 ++++++++++++
 plugin/Gallery/functions.php                  |   4 +-
 plugin/Gallery/view/mainAreaCategory.php      |   2 +-
 plugin/Live/Live.php                          |  45 ++++++++-
 plugin/Live/Objects/LiveTransmition.php       |  21 ++++-
 plugin/Live/confirmLivePassword.php           | 126 ++++++++++++++++++++++++++
 plugin/Live/getImage.php                      |   2 +-
 plugin/Live/index.php                         |   6 +-
 plugin/Live/install/install.sql               |   1 +
 plugin/Live/install/nginx.conf                |   6 +-
 plugin/Live/install/updateV10.2.sql           |   2 +
 plugin/Live/saveLive.php                      |   1 +
 plugin/Live/socketMessageLiveOwner.json.php   |  44 +++++++++
 plugin/Live/tabs/tabStreamSettings.php        |  39 ++++++--
 plugin/Live/view/modeYoutubeLive.php          |  18 ++--
 plugin/Meet/Meet.php                          |   8 +-
 plugin/Meet/api.js.php                        |   4 +-
 plugin/Meet/iframe.php                        |   4 +
 plugin/MobileManager/MobileManager.php        |   4 +-
 plugin/MobileManager/upload.php               |  62 ++++++++-----
 plugin/PlayerSkins/PlayerSkins.php            |   2 +-
 plugin/User_Location/User_Location.php        |   7 ++
 view/css/main.css                             |   6 ++
 view/include/navbar.php                       |   2 +-
 view/js/script.js                             |  12 ++-
 view/managerVideos_body.php                   |   2 +-
 view/modeYoutubeBottom.php                    |  11 ++-
 view/trending.php                             |   4 +-
 view/videoEmbeded.php                         |   8 --
 view/videoViewsInfo.csv.php                   |   4 +-
 view/videoViewsInfo.php                       |  13 ++-
 57 files changed, 759 insertions(+), 142 deletions(-)
 create mode 100644 install/deleteTGZFiles.php
 create mode 100644 install/updatedb.php
 create mode 100644 plugin/CustomizeUser/setSubscribers.json.php
 create mode 100644 plugin/CustomizeUser/setSubscribers.php
 create mode 100644 plugin/Live/confirmLivePassword.php
 create mode 100644 plugin/Live/install/updateV10.2.sql
 create mode 100644 plugin/Live/socketMessageLiveOwner.json.php
root@lblivestream:/var/www/html/AVideo#

![image](https://user-images.githubusercontent.com/37937968/144910559-5c07511f-f983-48cf-b6cc-2ab2c3ac8772.png)

![image](https://user-images.githubusercontent.com/37937968/144910627-bea2acb5-c1d5-40bf-b1c0-596d1845e671.png)

![image](https://user-images.githubusercontent.com/37937968/144910683-b52a1bc6-cd2f-479a-ad95-18f734c93e59.png)

![image](https://user-images.githubusercontent.com/37937968/144911649-239cb558-335e-4bf1-b4c7-38e204187b98.png)
Now on the bottom right, you will see the cursor high lighting the chat bubble but there is not chat!

**Comment by DanielnetoDotCom** [comment]
I cannot log in to your site anymore (i do not know why)

can you please enable the annimation effects again?

![image](https://user-images.githubusercontent.com/18009293/144914380-cc465777-4bfe-400d-b436-db11f0dc14c4.png)

**Comment by Lordblanca** [comment]
You can't log in because I restored from my backup. You will have to go through the process again. Activated the animation

**Comment by Lordblanca** [comment]
you have admin. once you log in

**Comment by DanielnetoDotCom** [comment]
I could confirm the missing animation is the problem . 

You can enable it by your self you do not need me to do that for you

**Comment by Lordblanca** [comment]
It seems that the animation is part of the fix with the chat. I guess I'm going to have to live with the animation. Don't like the idea of not being able to turn it off with out it affecting the chat... That suxs
