### ISSUE TITLE
Course online 

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#6055]
Hello everyone, 
I state that I have all the AVdeo Plugins, Who can give me some advice on how to set up a paid online course in a channel?

Thanks

**Comment by DanielnetoDotCom** [comment]
you may want to mix [playlists/series](https://github.com/WWBN/AVideo/wiki/Program-(Playlist)-to-series) and [PPV](https://github.com/WWBN/AVideo/wiki/PayPerView-Plugin) os [subscription](https://github.com/WWBN/AVideo/wiki/Subscription-Plugin)

make sure you create playlists. and then all the videos on that playlist will be in a usergroup

then you can create some plans on those usergroups
