### ISSUE TITLE
Plugin don't work 

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#6056]
Hello 

Who can tell me why the plugin User location don't work? 
People about other language when look the website don't change language. 
Thank 

![Screenshot_20211206_145527](https://user-images.githubusercontent.com/93554732/144858404-e7ed2458-dadb-4405-b6c4-39d5e4004601.jpg)

**Comment by DanielnetoDotCom** [comment]
the way I can see, the lang select will use your browser language (not your IP location)

but once you select a language it will not change until your cookie expires.

**Comment by toplive24** [comment]
If I set with IP don't change again

**Comment by DanielnetoDotCom** [comment]
set the IP, clear your cookies, and try.

make sure you are not on an internal network.

also make sure you have install the tables

![image](https://user-images.githubusercontent.com/18009293/144878283-1e6084b5-b836-438e-97fd-05d845dd0863.png)

**Comment by toplive24** [comment]
Sorry Neto but we buy all plugin and we think all work ok

**Comment by DanielnetoDotCom** [comment]
Hi

I found the issue with the code.
your site is up to date and should work well now.

**Comment by toplive24** [comment]
Ok thank Neto
