### ISSUE TITLE
Encoder Install

### ISSUE THREAD

**Issue by lunar54** [WWBN/AVideo#6057]
Encoder install stalls on Processing and I am seeing this error. I am also using a real domain on top of Fresh install
Ubuntu 20.04 with php8 & mysql 8

Same Origin Policy disallows reading the remote resource at http://domain.xx/login. (Reason: Multiple CORS header ‘Access-Control-Allow-Origin’ not allowed
![stuck_install](https://user-images.githubusercontent.com/35050024/145121905-75bbf388-1d87-4037-a4c5-a7a6e478ae41.jpg)

**Comment by DanielnetoDotCom** [comment]
If you have the https on your encoder make sure your streamer url is also https

**Comment by lunar54** [comment]
No SSL is being used for initial install. I always add that after setting up any site.

**Comment by DanielnetoDotCom** [comment]
you should add SSL before installing avideo.

your problem looks like is a redirect problem (HTTP to https )

**Comment by lunar54** [comment]
ok thanks I will give it a go.
