### ISSUE TITLE
Did a gitpull today and got a huge error list-Anything of concern please?

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#6058]
**Describe the question**
![image](https://user-images.githubusercontent.com/65802024/145161654-bcbcca02-eb59-4ef9-bc4a-699541528712.png)

The above is the log of the errors.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
It looks for me your server is having problems to handle MySQL 

something is killing mysql 

the last time I access it I have warned you that your server was not behaving properly

**Comment by vraghavans** [comment]
Oh okies noted, any suggestions for how to go about checking and fixing it please 🙏🙏

**Comment by DanielnetoDotCom** [comment]
there is no fix, the problem is your server.

it is too slow, looks to me, it is a hardware failure.

**Comment by vraghavans** [comment]
Dear Daniel,

Well noted and thanks

However this server is an VPS sitting hostinger.Hence will check with them.

Thanks
