### ISSUE TITLE
Latest git live not working - php error

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6059]
@DanielnetoDotCom hi

Did the latest git pull today and live is not working.

I can stream
I open OBS
I put in streamurl and key
I click stream
Notification and homepage show live

BUT 

When I click live, I get a php error

===========

array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(711) "Uncaught Error: Class 'Live' not found in /var/www/xxx/objects/functions.php:4490
Stack trace:
#0 /var/www/xxx/objects/functions.php(4415): isLive()
#1 /var/www/xxx/objects/functions.php(4651): isVideo()
#2 /var/www/xxx/plugin/MP4ThumbsAndGif/MP4ThumbsAndGif.php(18) : eval()'d code(1) : eval()'d code(184): getVideos_id()
#3 /var/www/xxx/plugin/AVideoPlugin.php(564): MP4ThumbsAndGif->getStart()
#4 /var/www/xxx/objects/include_config.php(168): AVideoPlugin::getStart()
#5 /var/www/xxx/videos/configuration.php(48): require_once('/var/www/xxx...')
#6 /var/www/xxx/plugin/Live/index.php(2): require_once('/var/www/xxx...')
#7 {main}
  thrown"
  ["file"]=>
  string(42) "/var/www/golivecongo/objects/functions.php"
  ["line"]=>
  int(4490)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}

================

Please assist.

Thank you

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by jengajenga** [comment]
> Please try this update

Thank you @DanielnetoDotCom . It is now working as it should.

Closing this.
