### ISSUE TITLE
Some questions about LIVE and PAYD user.

### ISSUE THREAD

**Issue by RememberForgottenHits** [WWBN/AVideo#6060]
Can't find information on how to disable these LIVE videos on the front page!?
![LIVE-channel-first-page](https://user-images.githubusercontent.com/34457020/145278600-1e8264db-c11e-4eb8-85a6-8f627bf1e189.png)

What kind of plugin would I need "Subscription" or "PayPerViewLive"? I want a system where a registered and logged in user has to pay for a month's rights before they can watch a live stream. 
If the monthly tax time gets over then he will not have access to them or will extend it for a month.

**Comment by RememberForgottenHits** [comment]
If I now understand correctly, the answer to my question is on this subject!? :+1: 
https://github.com/WWBN/AVideo/issues/6055

**Comment by DanielnetoDotCom** [comment]
Hi

I guess you the subscription is the best option for you now.

I am not sure what do you want to remove. do you want to remove the whole seciont? or a single video?

**Comment by RememberForgottenHits** [comment]
Thanks for the reply! :+1: Yeah, I want to remove whole  LIVE section from the front page!

**Comment by RememberForgottenHits** [comment]
Thanks a lot, it was that easy :dancers:  I remember there was an opportunity somewhere but I couldn't find it
