### ISSUE TITLE
Video Descriptions are missing

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6061]
![59c325f6-fbf0-4203-9cb3-e4e2d479bcec](https://user-images.githubusercontent.com/39392449/145313680-6ae993e2-107e-4cad-8546-05925d4621e6.png)

**Comment by DanielnetoDotCom** [comment]
If there is no description on the video. The description field will not appear .

does this video has description?

**Comment by JoshWho** [comment]
Yes all the videos with descriptions look like this

**Comment by DanielnetoDotCom** [comment]
Can you please give me an example of a video that suppose to have a description, so I will inspect and check

**Comment by JoshWho** [comment]
https://www.joshwhotv.com/v/.QDB5kQ

**Comment by JoshWho** [comment]
https://www.joshwhotv.com/v/.QDAowg

**Comment by DanielnetoDotCom** [comment]
Sorry, you were right.

here is a fix

**Comment by JoshWho** [comment]
Thank you Daniel
