### ISSUE TITLE
Assigen a group to a page

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#6062]
Could you design a even if it is a plug in. A way to assign a web page to a group. For instance TopMenu I can add a web page and have a group assigned to it.

**Comment by DanielnetoDotCom** [comment]
Do you mean, modify the topMenu and add a user group to it. and then the menu will only be visible for that usergroup?

**Comment by Lordblanca** [comment]
Yes exactly that

**Comment by DanielnetoDotCom** [comment]
That is a good idea and I may add this in the future.

**Comment by Lordblanca** [comment]
Great
