### ISSUE TITLE
Align how ldap plugin creates users in the aVideo db to the hybridauth behaviour

### ISSUE THREAD

**Issue by mcorvo** [WWBN/AVideo#6064]
Dear Daniel,

We're implementing an SSO plugin which shall run in parallel with the LDAP one and came across a sort of "misalignment". In particular, when the SSO plugins authenticate a new user, this is what happens (file login.json.php):

```
$hybridauth = new Hybridauth($config);

        $adapter = $hybridauth->authenticate($_GET['type']);

        $tokens = $adapter->getAccessToken();
        $userProfile = $adapter->getUserProfile();

        //print_r($tokens);
        //print_r($userProfile);
        if (!empty($userProfile->email)) {
            $user = $userProfile->email;
        } else {
            $user = $userProfile->displayName;
```

So if the email is defined, then it is used as "user" in the Users table of the mysql db. This is not happening in the LDAP plugin, also because the email is not retrieved from the ldap_search query (my original fault of not having provided a more inclusive set of ldap attributes to keep).

What we'd like to have is the same behaviour as the SSO plugins, that is to get the email address of the user, e.g.:

(code is **very** pseudo...just to give an idea)

```
$ldap_result = @ldap_search($connect, $dn, $filter);
     $attributes = array('eid' => 'uid', 'email' => 'mail', 'name' => 'cn',  'dn' => 'dn');
     if ($ldap_result) {
         $entry_array = ldap_get_entries($x500, $ldap_result);
         for ($i = 0; $i < count($entry_array) - 1; $i++) {
             $profile = new UserProfile();
             if ($entry_array[$i]) {
                 $eid = $entry_array[$i]['uid'][0];
                 # This is used to get the correct DN in order to complete the authentication 
                 $dn = $entry_array[$i]['dn'];
                 foreach ($attributes as $label => $att) {
                     if (isset($entry_array[$i][$att])) {
                         $profile->$att = $entry_array[$i][$att][0];
                     } else {
                         $profile->$att = '';
                     }
                 }
             }
         }
      }
     .....

# Perform authentication with DN and password

      ldap_set_option($connect, LDAP_OPT_PROTOCOL_VERSION, $ldap_object->LDAP_OPT_PROTOCOL_VERSION);
                    if (($bind = @ldap_bind($connect, $dn, $auth_pass))) {
                        if ($bind === true) {
                            return User::USER_LOGGED;
   ..........
# Now take the attributes from the ldap_search query and create, in case, the new user
         if (!empty($userProfile->mail)) {
            $user = $userProfile->mail;
        } else {
            $user = $userProfile->cn;
        }
        $pass = rand();
        User::createUserIfNotExists($user, $pass,  $userProfile->cn, $userProfile->mail, $photoURL, false, true);

```

So when a user gets logged in either via LDAP or SSO, it is recognized as the same user with the email as uid.
Would it be possible to implement this behaviour in the LDAP plugin?

Thanks in advance for your help,

Marco

**Comment by DanielnetoDotCom** [comment]
Hi

can your ldap user be the email?

I just checked the code and if the LDAP authenticate it will use the LDAP user as the AVideo user. I guess the same may happen if you authenticate with the social media OAuth2

**Comment by mcorvo** [comment]
Hi Daniel,

let me try to clarify a little more the feature. Currently the ldap plugin returns two fields from the execution of the ldap_search: the dn, which we use to authenticate the user in the subsequent call to ldap_bind, and the uid which we don't use.
We would need to recover also the email address of the user for two reasons:
- keep the information in the db in order to be able to use the email address to send notifications
- match the user who might have authenticated himself with the SSO plugin

As far as I understood, in case of an "hybridauth" plugin, the code in login.json.php uses the email address of the user as the "user" field in the "Users" table of the db when the $userProfile->email attribute is not empty, otherwise it takes the displayName

```
if (!empty($userProfile->email)) {
            $user = $userProfile->email;
        } else {
            $user = $userProfile->displayName;
        }
$pass = rand();
User::createUserIfNotExists($user, $pass,  $userProfile->cn, $userProfile->mail, $photoURL, false, true);
```

and in fact our SSO plugin retrieves the user email from the Identity Provider and records it in the "user" field of the Users table. Now we would like that the same behaviour happens when a user authenticates with the LDAP plugin, so that we can check whether the user is the same matching the "user" field. Would it be possible? Otherwise would it be possible to make the LDAP plugin retrieve also the email in order to be able to send notifications?

Thanks again in advance for your support,

Marco

**Comment by DanielnetoDotCom** [comment]
But I guess in each LDAP environment the email field is different.

if you use the email to authenticate it should use your user for a single sign-on.

if you can please share more about your LDAP setup

what is your RDN value?

can you use the email as the username on your LDAP?

**Comment by mcorvo** [comment]
Hi Daniel,

sorry, I guess I understood now your objection: currently we have the following setup for the LDAP auth:

RDN: uid={$user},ou=People,dc=infn,dc=it
FILTER: (uid={$user})

but we could use:

FILTER: (mail={$user})

to search fo a given user by email address and retrieve the dn. The problem is this isn't working. I always get:

[20-Dec-2021 16:15:07 Europe/Rome] AVideoLog::DEBUG: auth: LDAP RDN: uid=marco.corvo@cnaf.infn.it,ou=People,dc=infn,dc=it SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php
[20-Dec-2021 16:15:07 Europe/Rome] AVideoLog::DEBUG: auth: LDAP BIND fail: 32: No such object SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php
[20-Dec-2021 16:15:07 Europe/Rome] AVideoLog::DEBUG: authSearch: DN not found {"count":0} SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php

What looks even stranger is that, when I use the uid={$user} filter, which works correctly and let me authenticate, the logs always report:

[20-Dec-2021 16:17:26 Europe/Rome] AVideoLog::DEBUG: auth: LDAP RDN: uid=corvo,ou=People,dc=infn,dc=it SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php
[20-Dec-2021 16:17:26 Europe/Rome] AVideoLog::DEBUG: auth: LDAP BIND fail: 32: No such object SCRIPT_NAME: /plugin/LoginLDAP/view/login.json.php

I tried with my test script, using mail=$user as filter, and it works, so I'm wondering whether there's something else in between which could make the plugin fail to find the user by email:

```
if (($connect = ldap_connect($ldap_object->server, $ldap_object->port))) {
        $filter = "(mail=$user)";
        #$filter = "(uid=$user)";
        $ldap_result = @ldap_search($connect, $base, $filter);
        print_r($ldap_result);

        $attributes = array('eid' => 'uid', 'dn' => 'dn');
        #$attributes = array('eid' => 'uid', 'dn' => 'dn', 'email' => 'mail', 'name' => 'cn', 'firstname' => 'givenname', 'lastname' => 'sn', 'office' => 'utexasedupersonofficelocation', 'phone' => 'telephonenumber', 'title' => 'title', 'unit' => 'ou');
        if ($ldap_result) {
            $entry_array = ldap_get_entries($connect, $ldap_result);
            for ($i = 0; $i < count($entry_array) - 1; $i++) {
                $person = array();
                if ($entry_array[$i]) {
                    echo "Entry array from ldap search: " . json_encode($entry_array[$i]) . "<br>";
                    $eid = $entry_array[$i]['uid'][0];
                    echo "User uid: " .  $eid . "<br>";
                    $dn = $entry_array[$i]['dn'];
                    echo "User dn: " .  $dn . "<br>";
                    $mail = $entry_array[$i]['mail'][0];
                    echo "User email: " .  $mail . "<br>";
                    $name = $entry_array[$i]['cn'][0];
                    echo "User displayname: " .  $name . "<br>";
                }
            }
        }

        ldap_set_option($connect, LDAP_OPT_PROTOCOL_VERSION, $ldap_object->LDAP_OPT_PROTOCOL_VERSION);
        if (($bind = @ldap_bind($connect, $dn, $auth_pass))) {
            if ($bind === true) {
                echo "Bind equal to " . $bind . ". User correctly logged in<br>";
                #return User::USER_LOGGED;
            } else {
                echo "LDAP BIND NOT TRUE: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true);
            }
        } else {
            echo "LDAP BIND fail: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true);
        }
    } else {
        echo "LDAP Connection fail: " . ldap_errno($connect) . ": " . print_r(ldap_error($connect), true);
```

Thanks again for your support and sorry for the "noise".

Marco

**Comment by DanielnetoDotCom** [comment]
Hi, sorry but I am a bit confused.

what exactly are you typing on the user's field?

Are you using those values?

- RDN: uid={$user},ou=People,dc=infn,dc=it
- FILTER: (uid={$user})

can you please clean up the sample code you used above (the one that works) and show me what exactly values did you use for RDN and Filter?
