### ISSUE TITLE
I have this problem with the mobile application

### ISSUE THREAD

**Issue by JeanDavis91** [WWBN/AVideo#6067]
Hello

I have this problem with the mobile application and I have to activate everything in avideo

Up-to-date plugins 
Avideo  v11.5

![m1](https://user-images.githubusercontent.com/61474191/145654496-205ebb36-b7e9-4565-8f56-f13dda2bc972.jpg)

![m2](https://user-images.githubusercontent.com/61474191/145654504-4fe11f6d-035e-4d4a-86e7-35acbbe51692.jpg)

Url of my site that is causing the problem:
https: //***-**r.synology.me/films-/

error 
![tel](https://user-images.githubusercontent.com/61474191/145654161-46c2cb80-7fc1-4d47-951b-6cf6d34011f9.jpg)

Thank you

**Comment by DanielnetoDotCom** [comment]
the SSL must be valid for Android

**Comment by Burdeau** [comment]
Bonjour,
J'ai le même problème que vous en ce qui concerne la connexion via l'application smartphones (iPhone et Android).
Comment l'avez-vous résolu ? 
Je suis en V11.1, où trouver la V11.5 ?
Merci pour votre aide.

**Comment by DanielnetoDotCom** [comment]
I will soon send some updates for the mobile apps

**Comment by JeanDavis91** [comment]
Bonjour Burdeau

Je n'ai pas résolu le problème, mais DanielnetoDotCom (merci à lui) va faire un update des applis mobiles peut être que cela va résoudre les problèmes par contre pour résoudre ce problème il faut prendre un vrai nom de domaine, et ne pas utiliser celui fourni avec le synologic, car il y a des problèmes avec Android d’après certaines ressources

Pour la version 11.5 c'est ici ==> https://github.com/WWBN/AVideo/archive/refs/heads/master.zip

Hello Burdeau

I haven't solved the problem, but DanielnetoDotCom (thanks to him) will update the mobile apps, maybe that will solve the problems, but to solve this problem, you have to take a real domain name, and not use the one that comes with synologic, as there are issues with android according to some resources 

Jfr

**Comment by Burdeau** [comment]
Bonsoir Jfr,

Merci à vous deux pour ces précieuses informations.
J’ai installé la V11.5. Dans Health Check, j’ai encore des carrés rouges mais je ferai des recherches pour les rendre verts.

Bon week-end

**Comment by DanielnetoDotCom** [comment]
Please write in english
