### ISSUE TITLE
Error Failed to write file to disk (ENCODER 3)

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6068]
Hi Daniel,

When using the encoder https://encoder3.avideo.com/ is showing the following error, when I click on START UPLOAD.
Error Failed to write file to disk

![image](https://user-images.githubusercontent.com/37880073/145663729-f643d11e-c05b-490c-80da-2ef945a23011.png)

**Comment by DanielnetoDotCom** [comment]
encoder 3 and 4 are on the same server, and I just notice the disk is full, I am resolving it. thanks
