### ISSUE TITLE
Reset CachesInDB counter_id to 1 when clearing cache

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#6069]
Storing cache in DB is not only very good for the performance but also very fast for my shadowcopy of Avideo (with the 'Backup'-plugin).

Because every video here are afterwards renamed to the actual release date like 1939, 1964 etc (video_390911120000_a086, video_640901120000_6959). I have to clear the cache before modifying 'created_datetime' and filename_varchar(255) belonging to the video in SQL.

Since the time that filenames are renamed from Article_name into Video_Datename this works perfect for me with about 2300 videos in the system.

You can imagine that by clearing cache with 2300 videos CachesInDB_ID number is getting very very huge when not resetting back to 1.

Is it possible to set CachesInDB_ID to 1 when clearing cache or where can i modify the startnumber of CachesInDB_ID ?

![Snap3](https://user-images.githubusercontent.com/39981177/145686443-a57aab6f-bb3e-42c7-91bb-e5b51ea126de.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, this update should do the trick when you clear all cache

**Comment by TLCReuver** [comment]
Thank you for the quick update. Top.
