### ISSUE TITLE
How to setup Youtube API for Upload 

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#6070]
Having issues to set up the API to upload videos to Youtube. Hope you have some instructions because i have followed the ones under the Video Tab but something is missing i put the API Key and nothing.

**Comment by Waffleuncle** [comment]
![image](https://user-images.githubusercontent.com/76669896/145699653-0454c01d-c257-4e0c-800e-46769e3dc90f.png)
You can take 1 hours plan

**Comment by LATINMIXMASTERS** [comment]
> ![image](https://user-images.githubusercontent.com/76669896/145699653-0454c01d-c257-4e0c-800e-46769e3dc90f.png) You can take 1 hours plan

Have done it before , but i need learn because following every step and not functioning.  👍🏻 so i want to make sure if anything else need to be done. ☺

**Comment by Waffleuncle** [comment]
Doo you correctly activate youtube v2 on google cloud ?

**Comment by LATINMIXMASTERS** [comment]
Yes every step , activate the api for youtube data as describe on instructions but still does not work. For that reason i am asking. I created the app and all .

**Comment by Waffleuncle** [comment]
Normaly you should have access imediatly

**Comment by LATINMIXMASTERS** [comment]
Well for some reason it give error to users 403 so i will wait and see , what Daniel will say. Also i sent google a ticket.

**Comment by DanielnetoDotCom** [comment]
First, you MUST enable LoginGoogle plugin and add the credentials

I am not 100% of all steps, but I do remember it recently changed and now you need google approval to be able to allow your users to upload to their account.

currently by default, you can only upload to the account where the API google keys belong to.

**Comment by LATINMIXMASTERS** [comment]
Ok thank you. So i think is that then approval from Google.
