### ISSUE TITLE
Missing Category

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#6072]
Missing category when upload video

![immagine](https://user-images.githubusercontent.com/93554732/145714875-a35ae4e8-f1f6-40d8-818b-a822a858a64a.png)

**Comment by DanielnetoDotCom** [comment]
Please make sure you have userCanNotChangeCategory unchecked

![image](https://user-images.githubusercontent.com/18009293/145816269-442a2845-5be1-40c9-84ad-147866e06acc.png)

**Comment by toplive24** [comment]
Hello Neto
Yes it's ok now

Thank
