### ISSUE TITLE
Android PWA Bug

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6073]
He uninstalled the old pwa and now it doesn't prompt him to install it anymore.

**Comment by DanielnetoDotCom** [comment]
correct. you need to clear the cookies for that. in the future I will create a button so you will be able to install it at any time

**Comment by JoshWho** [comment]
Sweet thank you. I will let them know

**Comment by JoshWho** [comment]
On the homepage there is something wrong with the PWA

![Screenshot_20211213-210939](https://user-images.githubusercontent.com/39392449/145926360-72b810a4-3f9c-4c58-b620-917394cf952b.jpg)


On a video page it works just not on the Home page

![Screenshot_20211213-210746](https://user-images.githubusercontent.com/39392449/145926401-9488063b-c88d-4b62-a0bd-6cfb45d30938.jpg)

**Comment by DanielnetoDotCom** [comment]
Something I notice and I am not sure why. the worker sometimes takes longer to load.

I am not sure where this problem comes from if it is a server issue or a browser issue.

**Comment by JoshWho** [comment]
Ahh I c.
