### ISSUE TITLE
ppv-live, wallet and paypal

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6074]
@DanielnetoDotCom hi

I have some question please

I bought the ppv live and i am charging for example 10USD for a client to watch a link

1. Can the link to watch be sent to the user email? My client is insisting that an email must be sent - with a unique url. is it possible?
2. Paypal deducts its fees from 10USD so I remain with 9.26 USD in Paypal. But in the wallet we split I take 3% and client takes 97%. My wallet says 0.3USD and client wallet says 9.7USD. How is that possible when Paypal is showing a different figure?
3. When the client does his withdraw, how much will the client receive?
4. Where is the IPN url?

Thank you

**Comment by jengajenga** [comment]
@DanielnetoDotCom hi

More questions

1. How does the client see the number of purchases that have been made?
2. How does the client directly add his own PPVLive plan without the admin?

Thank you

**Comment by jengajenga** [comment]
@DanielnetoDotCom can you assist here please?

**Comment by DanielnetoDotCom** [comment]
Sorry for the late reply

here are some answers:

> Can the link to watch be sent to the user email? My client is insisting that an email must be sent - with a unique url. is it possible?

What exactly do you mean?
all videos (live or VOD) you can share using the URL

> Paypal deducts its fees from 10USD so I remain with 9.26 USD in Paypal. But in the wallet we split I take 3% and client takes 97%. My wallet says 0.3USD and client wallet says 9.7USD. How is that possible when Paypal is showing a different figure?

what do you mean Paypal is showing different?
just to make clear. the PayPal plugin requires some API keys from the site owner's PayPal (SOPayPal). all the real money will go to that Paypal account (SOPayPal). 
the payment split will happen on the virtual wallet on the website. your users can request a withdraw and the money will come out from (SOPayPal) and will go to the account your user add as their PayPal account

> When the client does his withdraw, how much will the client receive?

depends on your Paypal deal. each country has different rules

> Where is the IPN URL?

This will be automatically informed to your Paypal transaction

but here is the file https://github.com/WWBN/AVideo/blob/master/plugin/PayPalYPT/ipnV2.php

> How does the client see the number of purchases that have been made?

Everything is recorded on his wallet history

> How does the client directly add his own PPVLive plan without the admin?

On his live configuration page

![image](https://user-images.githubusercontent.com/18009293/146048754-fb587a24-2d11-426c-a5db-71e72398f0f3.png)

**Comment by jengajenga** [comment]
> On his live configuration page

Can the user add his own plan instead of choosing a plan that has already been made by the admin?

**Comment by DanielnetoDotCom** [comment]
> What i mean is, when the PPVLive has been set for next week, and a user wants to watch and he buys it today, there should be an email sent to the user with the URL so that he can have the event details in his email.

If the user subscribes to the user that will make the live he will be notified if you have the notification plugin

> See the difference?

I see and I cannot respond to the PayPal fees, also if you use another payment gateway the fees may be different.
On Paypal, you will have less balance in most cases.

> Can the user add his own plan instead of choosing a plan that has already been made by the admin?

No, he must use the plans the Admin setup, if we allow the user to create his own plans, he will be able to decide the cut between admin and himself. he can also set the cut 0 for the admin.

**Comment by jengajenga** [comment]
> No, he must use the plans the Admin setup, if we allow the user to create his own plans, he will be able to decide the cut between admin and himself. he can also set the cut 0 for the admin.

I would suggest then this option be set as standard for the site. Admin chooses the cut and sets it. then anyone who wants to do a ppv live knows that the cut has already been set and it is up to them to accept.

Example, I can set 88% client and 12% admin. then from there, anyone who does ppv knows that he will get 88% of the fees and admin will get 12%.

What do you think @DanielnetoDotCom ?

**Comment by DanielnetoDotCom** [comment]
I suggest you create multiple plans with predefined prices and cuts and let your users choose what plan they want to go.
