### ISSUE TITLE
Restreamer is not working properly. 

### ISSUE THREAD

**Issue by Waffleuncle** [WWBN/AVideo#6077]
Hello, I have been using restreamer and it seems that it has a lot of impact on packet loss and never stays stable. 
Example on twitch I can observe an important problem that causes the pre-maturer stop.

We also have some errors related to the live plugin that is displayed repeatedly.

![image](https://user-images.githubusercontent.com/76669896/145929603-d258ab1d-f848-43f6-9355-056f870a5ef7.png)

The following errors seem to be affected by MYSQL or something that would come from it. 
We do have the latest version of the plugin and the website.

![image](https://user-images.githubusercontent.com/76669896/145929729-875a6aaf-cd9a-4622-acc9-65c8e06ba6aa.png)

I get this kind of error in large quantities which can slow down the server. We have not found the source of this problem. If it is possible to check or update the LIVE plugins let me know 

Thanks again.

**Comment by DanielnetoDotCom** [comment]
Go to your plugins menu and click on the install tables button on the live plugin.

**Comment by Waffleuncle** [comment]
Of course this is already done.
This is even the first thing that is done before configuring my NGINX servers

**Comment by Waffleuncle** [comment]
![image](https://user-images.githubusercontent.com/76669896/146032217-76914d99-9608-4c6f-9702-6ecba1593fba.png)
I have 3 RTMP servers all working properly but I still have the errors I show you

**Comment by DanielnetoDotCom** [comment]
If it was done those errors do not make sense.

try this. delete your avideo.log file and let it recreate. and grab the new errors.

**Comment by Waffleuncle** [comment]
I have installed a lot of plugins and their databases and I think but I am not sure that the errors do not come back anymore. 

If within the next hour after my tests I have nothing I will tell you what I did to solve the problem and close the post.

**Comment by Waffleuncle** [comment]
Regarding the errors we managed to correct them simply by installing the other plugins for some obscure reason. 

We also modified some lines in the restreamer.json.php file since the new parameter was causing the re-stream to stop prematurely. 

https://pastebin.com/PM8B4Sh3

We also had to modify regarding stability and prevent packet loss in stream in NGINX this. 

![image](https://user-images.githubusercontent.com/76669896/146086555-ee52bbf6-6c67-412e-a7e0-4e899a892d6e.png)


I think you should check, because with this configuration the re-stream works again without stopping and without loss

**Comment by JoshWho** [comment]
I just implemented your settings looks good to me.

**Comment by ChisdealHDYT** [comment]
another thing hls_fragment is delay of Stream and playlist too, in that settings its now 10 sec or 15 sec delay.

them settings been made by me and full tested. so only reasons Restream-json.php keeps crashing because Playback so slow and buffering because not rendering faster.

so right now 10 to 15 sec on Restream with that settings.

be lucky might able do 5 to 3 seconds delay but not fully tested make it as thing.
