### ISSUE TITLE
Any way to Force Rumble and Bitchute Embeds use Theatre mode Wide Screen Desktop?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6078]
The Rumble and Bitchute embeds look great in the wide theatre mode and wondering if there is a way to just make that automatic.

![5e47db21-7307-4fd6-99f9-37e63acdba7d](https://user-images.githubusercontent.com/39392449/145947306-3d2b0882-1c9a-480b-ae0e-1f78521dcbc4.png)

**Comment by JoshWho** [comment]
The Compressed view makes a giant space appear under the video before the description and you have to scroll down to see it, which is another reason why this would be kewl to force on Rumble and Bitchute.

**Comment by DanielnetoDotCom** [comment]
Can you please check this update?

there is no need to force the view

**Comment by JoshWho** [comment]
KK Thank you Will check it out in a few

**Comment by JoshWho** [comment]
It still shows it like this 
![e7525f0d-bdb8-4418-b1e5-42c6b95dd49f](https://user-images.githubusercontent.com/39392449/146058238-c4b4145d-70b2-49ed-9410-72fdbe66a543.png)

**Comment by JoshWho** [comment]
This is the video link I am testing with https://www.joshwhotv.com/v/.QDA_ng

**Comment by DanielnetoDotCom** [comment]
Looks like you did not update 

![image](https://user-images.githubusercontent.com/18009293/146058810-486b09fb-7128-4315-893b-222228de483e.png)

**Comment by DanielnetoDotCom** [comment]
You must have this HTML class in your page 
https://github.com/WWBN/AVideo/blob/50e7b5f9824292adacb2c0777b1f9bb181467677/plugin/PlayerSkins/PlayerSkins.php#L143

try also to clear the cache.

**Comment by JoshWho** [comment]
U r correct. I updated the wrong install LOL Thank you

**Comment by JoshWho** [comment]
![b80d36bb-e00d-4fc2-a477-c41fe17aa73b](https://user-images.githubusercontent.com/39392449/146059889-64c96f00-7eb2-41c5-be3f-c3deb5e5c3fe.png)
