### ISSUE TITLE
Slow process 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6079]
Any idea @DanielnetoDotCom 
![Screenshot_20211214-120150_Samsung Internet](https://user-images.githubusercontent.com/70327833/146062995-1c08778f-b9b9-4cc6-8fca-4da469173072.jpg)

**Comment by DanielnetoDotCom** [comment]
those are not really an issue, they are most to debug.

**Comment by milehighkaraoke** [comment]
I am experiencing 15 second plus dely on login. Once you are logged in site is very responsive it is just the initial log in ... All plugins and pulls are up to date.

**Comment by DanielnetoDotCom** [comment]
manually delete the avideo.log file.

login again and share the log file.

**Comment by milehighkaraoke** [comment]
Seems to function properly  If I go to www.mhktube.com   
 at mhktube.com is where it hangs.

**Comment by DanielnetoDotCom** [comment]
To speed up the site I recommend you to use SSD drives on the server.

I am having a good experience with it.
