### ISSUE TITLE
Post Editor missing option to edit post thumbnail

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6080]
Here is a screen shot of how the editor appears now and there is no way to get to the section where I add post thumbnail/image.
![Screen Shot 5782-04-10 at 22 18 29](https://user-images.githubusercontent.com/58882903/146073488-81163046-a10f-47c8-9316-68f2d8b52692.jpg)

This only happens when edition from the front page directly from the video links, the editor works fine when opening it from "My Videos" section.

**Comment by JoshWho** [comment]
Not missing just separated. 

Click the old edit button to see it combined.

![74cad50e-ec5c-477d-9029-c09e3a5143d0](https://user-images.githubusercontent.com/39392449/146081137-a90208dc-42c5-4de2-9c61-9eae05f8ef42.png)

**Comment by DanielnetoDotCom** [comment]
I see...

 he wants to change the poster from the front page. I will improve that.

**Comment by guymass** [comment]
yes I think also allowing to edit the poster will be great

**Comment by DanielnetoDotCom** [comment]
Hi

you should be able to see this now.
![chrome-capture (1)](https://user-images.githubusercontent.com/18009293/146388944-9cf4085b-c9f0-4a71-8a88-e58f7495fd78.gif)

**Comment by guymass** [comment]
Yes cool thanks now its great!
