### ISSUE TITLE
new LAMP

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6084]
Hi,
I have a new LAMP server
Downloaded videos do not work
errors in the log

`[15-Dec-2021 10:31:57 Europe/Warsaw] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/youhippo.com\/public_html\/objects\/mysql_dal.php","line":95,"function":"log_error"},{"file":"\/var\/www\/youhippo.com\/public_html\/plugin\/Cache\/Objects\/CachesInDB.php","line":146,"function":"writeSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/youhippo.com\/public_html\/plugin\/Cache\/Cache.php","line":338,"function":"_deleteCache","class":"CachesInDB","type":"::"},{"file":"\/var\/www\/youhippo.com\/public_html\/objects\/Object.php","line":545,"function":"deleteCache","class":"Cache","type":"::"},{"file":"\/var\/www\/youhippo.com\/public_html\/objects\/video.php","line":3727,"function":"deleteCache","class":"ObjectYPT","type":"::"},{"file":"\/var\/www\/youhippo.com\/public_html\/objects\/video.php","line":4277,"function":"clearImageCache","class":"Video","type":"::"},{"file":"\/var\/www\/youhippo.com\/public_html\/objects\/video.php","line":437,"function":"clearCache","class":"Video","type":"::"},{"file":"\/var\/www\/youhippo.com\/public_html\/objects\/videoEditLight.php","line":43,"function":"save","class":"Video","type":"->"}] SCRIPT_NAME: /objects/videoEditLight.php`

![serv](https://user-images.githubusercontent.com/93145787/146176466-7355c932-83d0-4112-8213-36b835704087.jpg)

**Comment by DanielnetoDotCom** [comment]
I suspect you did not install the cache plugin table.

but please share more about your logs

**Comment by KrzysioMisio** [comment]
the entire avideo.log file
[avideo.log](https://github.com/WWBN/AVideo/files/7719615/avideo.log)

**Comment by DanielnetoDotCom** [comment]
`Prepare failed: (1146) Table 'video_youtube.CachesInDB' doesn't exist`

Check the tables of your Live plugin

**Comment by KrzysioMisio** [comment]
is the CachesInDB table
![Screenshot_2021-12-15 www youhippo com localhost video_youtube CachesInDB phpMyAdmin 4 9 5deb2](https://user-images.githubusercontent.com/93145787/146199810-30b9aa1c-2920-4603-8739-a236f9d42ad1.png)

**Comment by DanielnetoDotCom** [comment]
So this error log may be old.

delete your avideo.log file and keep the eyes opened

**Comment by KrzysioMisio** [comment]
Downloading films works
the video is visible in FTP and my video
but playback does not work
new log file 
[avideo.log](https://github.com/WWBN/AVideo/files/7721017/avideo.log)

**Comment by DanielnetoDotCom** [comment]
share here a video link that does not playback

**Comment by KrzysioMisio** [comment]
website:  https://www.youhippo.com
login: qwert
pass: qwert

**Comment by DanielnetoDotCom** [comment]
Looks to me you forgot the xsend file

https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

**Comment by KrzysioMisio** [comment]
thanks a lot !!!
it works !!!
I forgot to configure the files  /etc/apache2/apache2.conf 
:-)
