### ISSUE TITLE
bunny used

### ISSUE THREAD

**Issue by webdsf** [WWBN/AVideo#6085]
how can bunny.net be used? When I change the link to bunny it doesn't work.

**Comment by DanielnetoDotCom** [comment]
What link did you change? 

you should add your CDN here 

![image](https://user-images.githubusercontent.com/18009293/146219878-2266ffc6-4866-47ce-bd33-36dba820a241.png)

**Comment by webdsf** [comment]
The link was changed in the player, instead of the main one.
Installed my link b-cdn.net and am getting a replay error.
How do I use CDN to deliver and secure my manifests? It will also set up DNS CNAME for this domain, but nothing, when you go to this domain, there is simply a redirect.

**Comment by DanielnetoDotCom** [comment]
I am not 100% what you are looking for. but you should give it a try on [our CDN](https://github.com/WWBN/AVideo/wiki/CDN-Plugin) that will cover the VOD and live stream.

**Comment by DanielnetoDotCom** [comment]
looks like your ssl certificate is invalid

**Comment by webdsf** [comment]
Yes, these are some strange glitches with certificates, as I understand it, you need to ask that all caches be cleaned and this certificate removed from my site. If you look under the ip that I used when I tried to install bunny, then this error comes out, but if you look under others, everything is fine. A very, very strange error. And your CDN is suitable for the location of Europe, when I figure it out, I'll take it from you, I just don't know how it will work
https://i.ibb.co/RBFmMs3/Screenshot-11.png

**Comment by DanielnetoDotCom** [comment]
Please share a video link here so I can check and have a better idea what is going on.

**Comment by webdsf** [comment]
I sent you an email so as not to burn the entire site. Thank you for paying attention to the errors and helping to solve them. Thank you very much.

**Comment by DanielnetoDotCom** [comment]
I need to access the video directly from my PC so I can inspect it the m3u8 file does not work

**Comment by DanielnetoDotCom** [comment]
FYI your link works as an embedded video link

![image](https://user-images.githubusercontent.com/18009293/146421353-43fcdaa5-a8a8-401c-83eb-c55941230166.png)


https://demo.avideo.com/video/369/index

**Comment by webdsf** [comment]
I'll write with this ... since it is on the IP pair that these playlists do not work, and if you use VPN, then everything will work.

**Comment by DanielnetoDotCom** [comment]
I am not sure what you mean by “IP pair”

 It seems to me a network problem. Something in your side. 

Try access from another network

**Comment by webdsf** [comment]
I subscribed to your service, indicated a link to my site, what's next? add this link as in the second post?
What other settings do you need to make to make it work?

**Comment by DanielnetoDotCom** [comment]
All seems to be fine.

just clear your cache and it should work.

if it fails the problem may be in your site and you will need to open access so I will be able to check
