### ISSUE TITLE
Save the moment - Error saveDVR ERROR

### ISSUE THREAD

**Issue by Waffleuncle** [WWBN/AVideo#6087]
**Issue**

We have detected a problem following the recent update. 
The button to save a moment does not work anymore. 
However, the stream can still be saved automatically but not via the buttons. 

We have no logs that show a major problem. 
We don't know where to look to solve the problem.

**To Reproduce**
1 - We launch a stream via the server where the encoder is located.
2 - We press the save the moment button
3- ![image](https://user-images.githubusercontent.com/76669896/146272415-385d8f4b-3dc4-4f2a-9a32-60f4193f0dfc.png)

**Error Logs**
No error logs appear
When I click on the save the moment button. 
I can see that a 0KB file is created in /var/www/AVideo/videos/cache/

**Screenshots**
![image](https://user-images.githubusercontent.com/76669896/146272448-ec6ce054-9e83-4ffd-952b-a11e8b79bc6a.png)
![image](https://user-images.githubusercontent.com/76669896/146272685-6067ec5f-4691-496a-9de1-bd241a447f0f.png)

**VERSION** 
AVideo version 11.5
AVideo Encoder version 3.8

**Comment by DanielnetoDotCom** [comment]
is your livestream on the same server as the streamer?

Are you using the default configuration?

what do you have on /HLS/live folder?

what do you have on /var/www/tmp/ folder?

check your apache log and avideo.log file when you save it. Search the logs for the word saveDVR

**Comment by Waffleuncle** [comment]
is your livestream on the same server as the streamer?  ( YES ) 

Are you using the default configuration?
![image](https://user-images.githubusercontent.com/76669896/146274486-ecebb407-6a07-4d16-b19b-a84d0a26034e.png)

What do you have on /HLS/live : 
![image](https://user-images.githubusercontent.com/76669896/146274540-2d39dc1f-707a-49db-b11c-79ee6adc1800.png)

What do you have on /var/www/tmp folder? 
![image](https://user-images.githubusercontent.com/76669896/146274588-0f0dcf5d-dadf-44b5-aee2-d04de91c7434.png)

**logs**
https://pastebin.com/ixaDteyL

**Comment by DanielnetoDotCom** [comment]
Your streamer is NOT up to date

you have this on your log

{"file":"\/var\/www\/AVideo\/plugin\/SendRecordedToEncoder\/saveDVR.json.php","line":18,"function":"eval"

what does not match with the current version 

https://github.com/WWBN/AVideo/blob/633026e31ddffb8f708efac92d27f3460f4d519a/plugin/Live/standAloneFiles/saveDVR.json.php#L19

**Comment by Waffleuncle** [comment]
![image](https://user-images.githubusercontent.com/76669896/146275461-22deea2a-99a1-415c-88a4-9fcafbe49891.png)

**Comment by Waffleuncle** [comment]
I have downloaded the version you are talking about and I still have the same result

**Comment by DanielnetoDotCom** [comment]
> I have downloaded the version you are talking about and I still have the same result

I mean the AVideo site 

Is your live server on the same server as AVideo?

if it is not or if you set up it as a Live servers, make sure you copy the standAlone folder again

![image](https://user-images.githubusercontent.com/18009293/146278167-413bf0fa-ee06-47fc-83a2-e21889e220c8.png)

**Comment by Waffleuncle** [comment]
I unchecked the box in question and indeed it works again. Sorry for the inconvenience.
