### ISSUE TITLE
Changing language does not work 

### ISSUE THREAD

**Issue by matheusfillipe** [WWBN/AVideo#6088]
**Describe the bug**
Changing the language is not working again as of 633026e. Not sure exactly when the bug was introduced. You can reproduce the problem here: https://live.ahava528.com/view/?lang=en_US. It is always displaying on the default language.

Also the language change combobox is always appending to the url instead of replacing the lang parameter (Generating long meaningless urls like https://live.ahava528.com/view/?lang=en_US&lang=th&lang=el_GR)

I believe there isn't any relevant info on the logs but if needed I could submit them.

**Comment by DanielnetoDotCom** [comment]
Hi

I am sending updates that may resolve the duplicated values. thanks for noticing it.

**Comment by guymass** [comment]
I ran a git pull but the problem still remains. Translation is not working. Site is stuck on the language set in the panel I guess. For us its Hebrew so when I try to switch to english for example, the main menu will remain in Hebrew as the rest of the site as well.

**Comment by DanielnetoDotCom** [comment]
> I ran a git pull but the problem still remains. Translation is not working. Site is stuck on the language set in the panel I guess. For us its Hebrew so when I try to switch to english for example, the main menu will remain in Hebrew as the rest of the site as well.

Hi

Thanks for noticing it. I guess it is fixed now

**Comment by matheusfillipe** [comment]
It works! Thanks Daniel.
