### ISSUE TITLE
switch the tawk.to icon to other side

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#6090]
![image](https://user-images.githubusercontent.com/65802024/146357977-db77e1ac-7713-4c5a-91c2-620837db9181.png)

Please advise if the icon can be shifted to other side as it is presently coming on top of the details of the website.

**Comment by jengajenga** [comment]
this one is in the tawk.to portal. there should be a right-left placement option. it cannot be done on the platform.

**Comment by vraghavans** [comment]
thanks got it!
