### ISSUE TITLE
How to make the lives bigger

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6091]
Hello

How does one make the lives bigger? Right now there are six in a row.

![bigger](https://user-images.githubusercontent.com/65451390/146437802-0a805cee-5a51-4a48-9171-efc1f26402f1.jpeg)

How to make it 5 or 4 or 3 or 2 like categories?

Thanks

**Comment by JoshWho** [comment]
Would be neat but, the thing I like about that is it makes it easier to tell the lives from the regular vod

**Comment by DanielnetoDotCom** [comment]
Currently we cannot change the total lives in a row.

I may add this in the future

**Comment by jengajenga** [comment]
> Currently we cannot change the total lives in a row.
> 
> I may add this in the future

I hope you do :)
