### ISSUE TITLE
Share from Live Stream Twitter doesn't work

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6093]
This is the live I tried to share https://www.joshwhotv.com/live/1/ResistanceChicks/1

This is the line it is using

`https://twitter.com/intent/tweet?text=Joe%20Rogan%20&%20Dr.%20Peter%20McCullough%20Must%20See%20Interview%20Plus%20Headline%20News+https%3A%2F%2Fwww.joshwhotv.com%2Flive%2F1%2FResistanceChicks%2F1`

This is what it shows on twitter
![68edf1b4-bf67-45fb-93ba-0b197b2666d2](https://user-images.githubusercontent.com/39392449/146624356-c682eb18-1d30-46c8-9c05-691b2d9386bf.png)

**Comment by DanielnetoDotCom** [comment]
Hi

any idea how should be the URL to make it work?
