### ISSUE TITLE
Easy one here - Make ppv live mobile friendly

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6094]
Hi @DanielnetoDotCom 

Please see what you can do to make ppv live mobile friendly. it looks ok on normal web/pc but on phone one has to scroll to read the descriptions and also scroll to clearly see the sign in button.

Desktop is ok
![ppvlive-mobile-friendly](https://user-images.githubusercontent.com/65451390/146638357-25100099-6937-4bcb-8f83-b7ae27f711b6.PNG)

Mobile is not
![ppv-live-unfriendly](https://user-images.githubusercontent.com/65451390/146638610-f3d30e44-5bb2-4771-a0d4-5dcce12d31da.jpeg)

Thank you

**Comment by DanielnetoDotCom** [comment]
Please update the PPVLive plugin to version 1.8 and it should be resolved

**Comment by jengajenga** [comment]
Hi @DanielnetoDotCom 

Thanks for this update. I've been unwell so sorry for the late response.

Let me update. 

Thank you.
