### ISSUE TITLE
Live Streaming not working

### ISSUE THREAD

**Issue by balasi67** [WWBN/AVideo#6097]
I was live streaming to my website and all of a sudden everything crashed and I have been unable to use the live stream feature since
when I run     /usr/local/nginx/sbin/nginx     it gives me an error    nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
![Capture](https://user-images.githubusercontent.com/85172526/146681052-dd0e03ab-0708-4841-9369-f0e1126036ff.PNG)

**Comment by DanielnetoDotCom** [comment]
Try to stop nginx first 

/usr/local/nginx/sbin/nginx -s stop

than start it

/usr/local/nginx/sbin/nginx

**Comment by balasi67** [comment]
This has not worked, really weird though as its attempting to stream and I can see the odd image coming through the live feed. 

So it is trying, just not working somewhere

**Comment by balasi67** [comment]
OBS connects fine and says its streaming but on the website there is nothing

**Comment by DanielnetoDotCom** [comment]
your live server seems to be OK, 

https://g-stream.xyz:8443/

share a link where you have a live that suppose to be running

**Comment by balasi67** [comment]
Yeah the site loads fine and OBS connects to the stream key with no issues,
stream even says online but nothing loads when you click play or struggles and loads a millisecond then spends 2 minutes loading plays another millisecond and loads for a futher 2 minutes again
________________________________

**Comment by DanielnetoDotCom** [comment]
The way you describe seems like your server is not able to handle your live stream. 

it may be a disk speed issue or a CPU issue or a bandwidth issue

VPS are not recommended for livestreams

**Comment by balasi67** [comment]
The server has been more than capable of handling live stream, I have been live streaming for over 5 months to 600 viewers watching the stream at the same time for months,

Is there any checks I can do to see the CPU or disk health and see if all okay ?

If you look back to the picture I attached, I highlighted where it says server is not ready? Is that an indicator for anything ?

I'd be happy to get one of you to migrate my site to a more suitable server but I don't know where to look for affordable ones with unrestricted bandwidth
________________________________

**Comment by DanielnetoDotCom** [comment]
First thing check your stats page when you are having problems on the live stream

check what resolution you are streaming 

If you can control it on your side try to make only 720p lives 

if you cannot control it you may need to use the adaptive mode what can increase a lot your CPU consumption

**Comment by balasi67** [comment]
Yeah, I have checked the stats on the VPS website and it keeps logs and the CPU is running really well according to it, never goes over 60% usage even when I have the 600 viewers on the stream

it is 4 cores/ 8GB/ 150GB SSD

Bandwidth is 4GB out of 3TB used


I am currently streaming and when I go on the stream it is playing but every 30/40 seconds the screen freezes for about 5 seconds, and that's with just me watching so worry if I go live tomorrow and 3/400 people try and watch it will not work

I stream at 720P already

________________________________

**Comment by DanielnetoDotCom** [comment]
So I can only assume it is the bandwidth

Please check this https://github.com/WWBN/AVideo/wiki/Live-Plugin#data-consuption

**Comment by balasi67** [comment]
I go over the bandwidth every month, It doesn't cut off it just charges me a fee for any extra bandwidth I use.

I'll attach photos of OBS stats I just test streamed today.

and my VPS stats for the last month,

I stream every 3 days which explains the spikes in the CPU but the massive spike was from the stream on the 15th December where I think I hit 700 views, but I cant see how it all of a sudden starts having issues after months of working absolutely fine.

If you have any recommendations for a new site I can rent a server from I am happy to pay for you to do a migration of my site to new server
my current deal is limited bandwidth 3TB 4 core/ 8GB / 150 GB SSD and I pay $38.99 per month with Hostwinds.

Ideally I want unlimited bandwidth but struggling to find any from my google searches
________________________________

**Comment by balasi67** [comment]
![stats](https://user-images.githubusercontent.com/85172526/146990673-5bb78240-9fa7-49e1-8d14-beffdd356934.PNG)
![obs](https://user-images.githubusercontent.com/85172526/146990690-3f336dfd-51c8-4573-9441-341d07fe77f9.PNG)

**Comment by DanielnetoDotCom** [comment]
The thing is, what is your bandwidth pipe?

I guess you should try the CDN, this will also work for your live stream,

If the problem is the bandwidth the CDN should resolve that. if the problem is something else the problem may persists

**Comment by balasi67** [comment]
how do I use the CDN ? just turn the plug in on ?
________________________________

**Comment by DanielnetoDotCom** [comment]
You will need to add at least 10 usd balance into the marketplace CDN menu 

I also recommend you to activate the auto recharge to guarantee that the service will not be interrupted 

then enable the plugin and add the site URL into the pull zone area

I can help you with that CDN configuration but first you need to add the CDN balance
