### ISSUE TITLE
Channel About

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#6098]
**Describe the bug**
Format "About" for user channel. On actual channel About displays properly, on Browse Channels shows code.

**To Reproduce**
1. User goes to My Account
2. Updates About and makes it look pretty, saves.
3. Goes to their channel, looks perfect.
4. Goes to Browse Channels and About displays code.

**Expected behavior**
Display without codes.

**Screenshots**
Added...

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, Edge, Brave, FireFox
 
**Smartphone (please complete the following information):**
 - Device: Samsung S20
 - OS: Latest Android
 - Browser: Chrome, Edge, Brave, FireFox, Samsung
 
![ChannelListing](https://user-images.githubusercontent.com/85363361/146686370-6e964478-ff83-47b9-b63c-382f13c50005.jpg)
![ActualChannel](https://user-images.githubusercontent.com/85363361/146686375-f52e3838-0c95-4778-8ca1-1a5f9d60befb.jpg)

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by GreenDragonTavern** [comment]
That did it, thank you.
