### ISSUE TITLE
Comment spam

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#6099]
Just got bombed with comment spam.
Is there anyway to limit/stop it? Plugins?

**Comment by DanielnetoDotCom** [comment]
what kind of email?

can you share it so I can find out where does it comes from?

**Comment by fakeologist** [comment]
just spam linking to a scam site.

**Comment by fakeologist** [comment]
Can you put a captcha on the comment form?

**Comment by DanielnetoDotCom** [comment]
> Can you put a captcha on the comment form?

Currently, that would be the best solution, I will see what I can do.

**Comment by fakeologist** [comment]
Is there a way to manually approve users? The spammers are solving the registration captcha.

**Comment by DanielnetoDotCom** [comment]
You can change this 

![image](https://user-images.githubusercontent.com/18009293/146938865-cd058420-d9d4-4205-b0ad-4941a0583f9a.png)

this may resolve most of the spammers

**Comment by DanielnetoDotCom** [comment]
I just added some rules on comments to avoid spams

1.  you can only comment each 5 seconds
2.  if you already commented 3x or + on the same video you must wait 30 seconds
3.  if you can only repeat the comment each 60 seconds

**Comment by Maikuolan** [comment]
> I just added some rules on comments to avoid spams

If possible, might be good to make those rules customisable/configurable. Maybe somebody wants to change it from 5 seconds, to 4 seconds, to 10 seconds, to something else, etc, or 3x to 4x/5x/2x/etc, and so on. Current default values look good to me, but maybe other users might want to make it something different, more strict, less strict, etc.

**Comment by Dosso93** [comment]
Yoo
