### ISSUE TITLE
Comment in email notification

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#6100]
Can admins get the whole comment in the email notification, complete with a link to delete the comment?

**Comment by DanielnetoDotCom** [comment]
Do you mean, a link that you can use to delete, just clicking on a link on the email?

**Comment by DanielnetoDotCom** [comment]
I guess this issue is related to this https://github.com/WWBN/AVideo/issues/6099

I will close it here and lets try to resolve it on the other thread
