### ISSUE TITLE
Download Bottom Does Not Show MP4

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#6101]
I have activated the Download Option but not working correctly please show some light. Only showing m3u8 i need mp4 so people can play it. 

![Screenshot_20211219-222932_Chrome](https://user-images.githubusercontent.com/63973045/146707847-990dc5c3-a8e2-47da-800e-b81c2c5d96ea.jpg)

**Comment by DanielnetoDotCom** [comment]
Currently, I cannot download HLS as MP4 from the CDN storage. 

I still thinking of a solution for it.

**Comment by LATINMIXMASTERS** [comment]
Oh 😳 , well while you look into that also check if mp3 option can be add it. Because some people can download audio only instead of video. Will be good too.

**Comment by DanielnetoDotCom** [comment]
this is another awesome idea.

**Comment by partystreamsk** [comment]
Hello, will be great idea to add this option without a cdn. Its possible? for example owner of video wanna download later video. thanks
