### ISSUE TITLE
Slack Notfiy

### ISSUE THREAD

**Issue by nathantolene** [WWBN/AVideo#6103]
Just did a git pull and now the slack notify stopped working?  Last pull was before Aug 2021.  Also, upgraded to 11.5?  Any ideas or suggestions?

thanks,

NT

**Comment by DanielnetoDotCom** [comment]
there is no change on it. but please check your log file for some clue

**Comment by nathantolene** [comment]
Sorry to bother you again.  I set up a testing environment. Clean fresh install Slack Notify still doesn't work.  I checked and then remade my slack webhooks app.  I can test it from the command line with curl and it works fine. 

What logs do you suggest I look at or can send you to help resolve this issue?

thanks,

NT

**Comment by DanielnetoDotCom** [comment]
check videos/avideo.log

I do not use it for myself and I did not develop it, I am not sure what is the problem

**Comment by nathantolene** [comment]
Any chance it was from the commit of "Filter plugins on the plugins menu" on Sept 22,  It looks like the only change to file in a long time?

**Comment by DanielnetoDotCom** [comment]
I do not think so, but the only way to have a clue is with the logs

**Comment by nathantolene** [comment]
[taillog.log](https://github.com/WWBN/AVideo/files/7757515/taillog.log)

I have attached the videos/avideo.log from the time of upload to encoder until available on the streamer.

I don't see anything calling the plugin.

**Comment by DanielnetoDotCom** [comment]
I could not see anything regarding slack on your log file.

try to check the JS console for some clue

**Comment by nathantolene** [comment]
I'm closing this as I am not using this plugin anymore.  Hope someone fixes it.  :)
