### ISSUE TITLE
Mobile App Playlists not working properly anymore

### ISSUE THREAD

**Issue by pchelferlein** [WWBN/AVideo#6104]
Hello,
If I use my mobile App i can play the videos by tapping them correctly.
If I switch to the Playlist tab and select a Playlist always the second last song I added is getting startet although it is not contained in The Playlist. 

I'd really wold love to have my app back in working order :)

Can you give some advice on this sissue or how to check and fix it?

Smartphone 
 - Device: Xiaomi Note 9 Pro
 - OS: Android 11
 - latest Avideo mobile App

Kind regards.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot exactly what is wrong?
and what supposed to be?

**Comment by pchelferlein** [comment]
Hi Daniel,
I expect the Playlist to be played when I start it. Instead of the Playlist he starts playing with the second last added Video and then randomly strolls through my library

Playlist looks like:

1 - Fox Amoore
2 - Antigravity
3 - Work from Home

Selecting the playlist results in playing
1 - Second last added video of the library (not in the playlist)
2 - Random song following up (not in the playlist)
3 - Random song following up (not in the playlist)

Don't know how to screenshot that :)

**Comment by DanielnetoDotCom** [comment]
screenshot on your phone in what exact page/screen you are

**Comment by pchelferlein** [comment]
ok i took a stupid example with that playlist but it shows how it does not workl :)

I got to Playlist page in mobile App
Select Elektro
start elektro and get the second last song I added from my libray which is clearly not in the Playlist
![1640113007138](https://user-images.githubusercontent.com/71848538/146983710-9b42f6c9-6c21-40d1-8967-be3277b5645e.jpg)
![1640113007131](https://user-images.githubusercontent.com/71848538/146983727-751e48a0-8f32-41e4-9e8f-9dc64bd63695.jpg)
![1640113007118](https://user-images.githubusercontent.com/71848538/146983750-bb50ce50-4aff-4e4e-a56a-009a4a8d7133.jpg)

**Comment by DanielnetoDotCom** [comment]
Thanks, I guess I found the issue, can you please update your streamer and check again?

**Comment by pchelferlein** [comment]
I updated my Site and cleaned the Cache from the app. Now the correct song appears but somehow Icannot see the playlist after starting it by selecting a song so it stops after playing the selected song. Do I miss a setting somewhere?

**Comment by DanielnetoDotCom** [comment]
Sorry you were right, please update again and now it should be good

**Comment by pchelferlein** [comment]
Still not showing the rest of the Playlist in the app after starting it but at least now it continues with the selected playlist properly. Thanks for the quick fixes. Is it planned to add a goto next or previous Video in the mobile App and show the playlist under der Video description or is that a bug that those things do not show up?
If you want I could also grant you access if you want to test around by yourself.
Kind regards

**Comment by DanielnetoDotCom** [comment]
Check this

![chrome-capture (8)](https://user-images.githubusercontent.com/18009293/146993125-800b67c1-e88f-4dd1-87be-f8a7f1ee72a5.gif)

**Comment by pchelferlein** [comment]
I am afraid it does not look like this in my case. 

I allowed myself to record a small file to show it to you

https://user-images.githubusercontent.com/71848538/146998831-fa3d00e7-edf0-409d-9512-914b0b3a35bc.mp4

I don't know why it does that. Do you think with all the issues I should book myself an hour of support?

**Comment by DanielnetoDotCom** [comment]
I am not sure what you want to show on your video 

but an hour support is a good start so I can look directly into your site and app

**Comment by pchelferlein** [comment]
No big deal. You could give the site anslight overhaul. Also getting troubble with my encoder Network as well :(
Lead the way I am more than willing to Support your hard work.
Just let me know what you need and when and where to drop the order.
If necessary we can also add another hour if one is not enough. Simply request it as needed.
Kind regards

**Comment by DanielnetoDotCom** [comment]
The best thing now is…

purchase an hour on the marketplace site the. We can book a meeting time or you can just email me the credentials and I can look into it from here 

we will schedule the meet by email after the purchase 

thanks for the support

**Comment by pchelferlein** [comment]
Done as requested :-)
Also snapped myself another Plugin. Btw you have a Typo in your Paypal Transaction list.
1 hour support pop up as 11 on Checkout but on the bill they are listed as 1 hour :)
Looking forward to hear from you

**Comment by DanielnetoDotCom** [comment]
Hi, thanks for the purchase and typo notification. 

I have sent you an email
