### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6105]
Hi, Daniel
the new version works tragically after the update, it was not a good idea to load subpages into frames
Backspace button on the keyboard does not work, after each modification you have to refresh the main page

**Comment by DanielnetoDotCom** [comment]
what browser are you using?

I do not have this problem here, maybe it is your browser configuration.

**Comment by KrzysioMisio** [comment]
all browsers
try to go to the contact, help or other page, for example, and click Backspace on the keyboard or the back arrow of the browser

**Comment by DanielnetoDotCom** [comment]
Can you please try in another computer?

seems to me specifically in your PC

does the same happen on demo site too?

**Comment by KrzysioMisio** [comment]
the demo page is the same
see the difference, go to the page contact or help or other and click on the keyboard Backspace
website before the update: [http://www.youhippo.pl/]http://www.youhippo.pl/(url)
after the update: [https://www.youhippo.com/]https://www.youhippo.com/(url)

**Comment by DanielnetoDotCom** [comment]
Did you try from another computer?

the described behavior does not happen here and you are the first customer complaining about it

**Comment by KrzysioMisio** [comment]
I checked on another computer and it's the same
and do you have a button on the backspace keyboard to go back ??
try to enter:
- contact page
- about the application
- help
and click the back arrow as shown in the photo 
![strzalka](https://user-images.githubusercontent.com/93145787/147092840-02c31023-8aa5-4f58-9e4a-9ee16d35ea19.png)

**Comment by DanielnetoDotCom** [comment]
I see what you mean, the back page button.

The backspace is to delete a letter not to back a page.

please try this update, make sure you clear your site cache and let me know if makes any difference

**Comment by KrzysioMisio** [comment]
IT WORKS !!!!!!!!!!
you are GREAT !!!
Thanks !!!
