### ISSUE TITLE
Editing on video page hangs

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#6106]
Everytime I edit title from this screen the page hangs and the save doesn't stick.

No issue if I do the edit from the myvideo admin menu.

![edit](https://user-images.githubusercontent.com/66537018/147165156-7e5c4c41-7c50-431a-9489-cf870b4ffdde.png)

**Comment by DanielnetoDotCom** [comment]
Does this happen on any video or only on this video?

can you please detail the steps so I can reproduce it here?

**Comment by fakeologist** [comment]
It happens on all videos, desktop or android browser.

I simply click edit video, type a new title, then the color wheel spins endlessly.

If I go to my videos, no issues.

**Comment by DanielnetoDotCom** [comment]
I just tested on my side and it works

can you please allow me to direct try to edit a title on your site, to see if I can reproduce the error?

what video can I edit?

**Comment by fakeologist** [comment]
Anyone you want is fine.

**Comment by DanielnetoDotCom** [comment]
thanks, I found the issue and you should be all set now.
