### ISSUE TITLE
Article problem

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#6107]
We have always problem with article why can not copy and paste text and problem with size of image.

Thank

**Comment by DanielnetoDotCom** [comment]
Is strongly not recommended to copy and paste text from word or web pages.

the format may mess up your site layout

**Comment by toplive24** [comment]
I understand you 

But the problem is that if one has to insert an article of perhaps 20 lines one has to write it and this is not very satisfying.

Thank

**Comment by DanielnetoDotCom** [comment]
Can you please detail what exactly are you doing?

FYI if you want to copy and paste something make sure you are copying a plain text 

you can copy your text on notepad first
