### ISSUE TITLE
The options available when someond right-clicks on the video

### ISSUE THREAD

**Issue by angelawong** [WWBN/AVideo#6109]
I noticed that when a video is public, if anyone right-clicks on the video the following shows up:

_Loop
Copy video URL
Copy vidoe URL at current time
Copy embed code
Share_

Is there a way for me to control what is listed when someone right-clicks on a video? Any help would be most appreciated.

Thanks so much,
Angela

**Comment by DanielnetoDotCom** [comment]
Do you want to remove things or add things to the list?

**Comment by angelawong** [comment]
Daniel,

I was hoping to remove things from the list. I tried unchecking a few things in the User Configuration plugin but to no avail. Basically, I don’t want people embedding my videos. Is there a way to control what shows up on the list when we right-click on a video?

Thanks so much,
Angela

**Comment by DanielnetoDotCom** [comment]
No, you cannot control the list

but you can forbid embed

![image](https://user-images.githubusercontent.com/18009293/147296057-c787491e-6697-433e-96af-aa38370138fe.png)


You can have more embed protection options with the SecureVIdeosDirectory plugin 

![image](https://user-images.githubusercontent.com/18009293/147296107-e9768b0b-10bb-4b82-8706-31591c007f13.png)

**Comment by angelawong** [comment]
Daniel,

Thanks for the advice. However, I have the blockEmbedFromSharedVideos already checked and the video can still be embedded on another website. The version I am using is 11.5. Please advise.

Thanks so much,
Angela

**Comment by DanielnetoDotCom** [comment]
Also uncheck option userCanAllowFilesShareSelectPerVideo

and It should work to deny embed

**Comment by angelawong** [comment]
I have had userCanAllowFilesShareSelectPerVideo unchecked before but to no avail:

<img width="332" alt="plugin" src="https://user-images.githubusercontent.com/1007028/147326276-5cc9a4c9-b3ba-40d7-a59f-3879b0bb5d0e.png">

**Comment by DanielnetoDotCom** [comment]
In that case, I am not sure what is missing.

after Christmas I will check this again

**Comment by angelawong** [comment]
Daniel,

I thought you would have a look at it after Christmas. Please advise. Thanks so much.

Angela

**Comment by DanielnetoDotCom** [comment]
Sorry for the delay. I probably forgot that. 

![image](https://user-images.githubusercontent.com/18009293/151857146-5d2bd208-d4f8-4827-a118-a9e84c1a2113.png)

**Comment by angelawong** [comment]
@DanielnetoDotCom it made no difference. They were already checked.

I do have a question. My version is 11.5 and the latest version in git is 11.1.1? Could this be a problem? I did a $ sudo git pull
Please advise. Thanks so much

**Comment by DanielnetoDotCom** [comment]
The latest is 11.5 , so you are correct 

did you clear the cache after uncheck them?

**Comment by angelawong** [comment]
Thanks so much for all your help, @DanielnetoDotCom! It worked!
