### ISSUE TITLE
Live Streams not showing on Home page and Notification after last git pull

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6112]
All I see at the moment are the LiveLink streams. but the regular Live Streamers is not showing.

![a49df5aa-4859-481c-9234-73586c0c3635](https://user-images.githubusercontent.com/39392449/147347514-25c89a7c-6ca0-4023-b39d-c582becd0696.png)

![e7354db1-c74f-47a4-a077-7ff9dff3a68e](https://user-images.githubusercontent.com/39392449/147347452-15c67a1d-bc3f-466f-b4bd-139b85c96b25.png)

**Comment by DanielnetoDotCom** [comment]
Something is blocking your streamer to access the live server.

the command `wget https://live.joshwhotv.com:444/stat ` just hangs

![image](https://user-images.githubusercontent.com/18009293/147348114-c76ae3ab-a067-4a09-b86e-2b183ae9f2c8.png)

**Comment by JoshWho** [comment]
I can see it no problem

![e7354db1-c74f-47a4-a077-7ff9dff3a68e](https://user-images.githubusercontent.com/39392449/147354668-a5106257-5d06-48d7-8d14-840314cea933.png)

**Comment by DanielnetoDotCom** [comment]
I also can see, but your streamer cannot see it. and your streamer needs to communicate with your live server

**Comment by JoshWho** [comment]
I think I fixed it. Not sure what I did

**Comment by JoshWho** [comment]
ok not sure what just happened

**Comment by JoshWho** [comment]
yup it was firewall issue Thank you for looking
