### ISSUE TITLE
Video Location Block

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#6113]
Hi everybody
I wish you all a Merry Christmas and a Happy New Year!
Question:
there is a case the plugin Video_Location_Block does not allow access to the site to anonymous ip addresses
this can be done?

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
What do you mean " anonymous ip addresses"

as I know you always need an IP, maybe it comes from a VPN IP, but still need an IP

**Comment by wetubeclub** [comment]
I mean for users who have a hidden ip

**Comment by Maikuolan** [comment]
> I mean for users who have a hidden ip

You mean, users behind a proxy?

**Comment by wetubeclub** [comment]
I want to know the ip of the user from where it is I mean country area etc
i want the videos to be displayed to those whose ip is displayed while to those who are behind a proxy and an unknown user can not see the videos

Thank you

**Comment by DanielnetoDotCom** [comment]
I am still confused, even with a proxy or VPN the client still have an IP address
