### ISSUE TITLE
Load for a long time

### ISSUE THREAD

**Issue by webdsf** [WWBN/AVideo#6114]
Hello. The site began to load for a long time. do not open. The main problems arise when you watch the list of videos, go to the next page for a very long time, and also after transcoding when the file is sent to the server, it also happens. It can be cut out when you clean the cache, it starts immediately and then again.

Before that, everything flew. Perhaps there is not enough capacity or there are contradictions somewhere.
![Screenshot_45](https://user-images.githubusercontent.com/60380221/147351168-59290517-ae20-4716-a994-00310b66a997.png)
![Screenshot_44](https://user-images.githubusercontent.com/60380221/147351169-96f60845-6911-4e4b-9946-2a03b9e1caea.png)
![Screenshot_43](https://user-images.githubusercontent.com/60380221/147351170-99c4fa4d-421c-48ab-8bca-d76393085ae0.png)
![Screenshot_42](https://user-images.githubusercontent.com/60380221/147351171-ae14c07b-eaf6-4449-8495-872818756a22.png)

**Comment by DanielnetoDotCom** [comment]
Please check if there is any plugin update or table to install

**Comment by webdsf** [comment]
How to update plugins?
![Screenshot_46](https://user-images.githubusercontent.com/60380221/147355084-88b2a57c-dbb4-4cb6-b765-edd3495bd326.png)
![Screenshot_47](https://user-images.githubusercontent.com/60380221/147355076-af5f520e-0fc6-4aa3-a6ca-ac027e9d19b0.png)

**Comment by DanielnetoDotCom** [comment]
Here is what you should check 

![chrome-capture](https://user-images.githubusercontent.com/18009293/147356872-bc90f645-c7a3-4ae3-8290-c01f6cb72aa6.gif)

Also for Install tables buttons, click on it even if your plugin is not enabled

![image](https://user-images.githubusercontent.com/18009293/147356927-394c08e8-e1a0-4001-aec3-46e02d992c14.png)

And updates on paid plugins

![image](https://user-images.githubusercontent.com/18009293/147356955-8ed3ce66-e888-44bd-b828-dffaafa1ae51.png)

**Comment by webdsf** [comment]
Updates are not displayed for me. only near Live, I have not installed it and the update link leads to the market
![Screenshot_49](https://user-images.githubusercontent.com/60380221/147357744-58a6bd49-b6d5-47f1-a75d-f57d10af46e2.png)
![Screenshot_48](https://user-images.githubusercontent.com/60380221/147357752-bc7da2c1-5933-4dcd-b99b-9b761b1bdddb.png)

**Comment by DanielnetoDotCom** [comment]
First click on all red buttons "Install tables"

then clear the cache and test your site again

**Comment by DanielnetoDotCom** [comment]
The paid plugins "Update available" means you need to signup on marketplace and download the new plugin version.

**Comment by webdsf** [comment]
Did as it was said, but shows nothing. I even opened another account where I did not open the site. But it still freezes. when everything was installed, it began to freeze, and also when uploading the transcode video to the site.

**Comment by DanielnetoDotCom** [comment]
The only thing I can see here is this ...

![image](https://user-images.githubusercontent.com/18009293/147361535-11918bdd-ac6d-43e0-ae98-91be981d52e4.png)

of your server is not able to handle the AVideo script or you have a misconfiguration on your MySQL

try to run this 

https://github.com/WWBN/AVideo/wiki/Speed-up-your-page#mysqltuner-script

**Comment by webdsf** [comment]
![Screenshot_54](https://user-images.githubusercontent.com/60380221/147362171-d0407478-a759-493c-9f3a-5936ec0da6d6.png)
![Screenshot_53](https://user-images.githubusercontent.com/60380221/147362174-fe0970f3-e468-470c-b3e0-8428f17b3ffc.png)

**Comment by DanielnetoDotCom** [comment]
So you need to adjust the variables and restart the MySQL.

if the problem persist you may need to google to find a solution for your MySQL or use another server
