### ISSUE TITLE
VideoHLS

### ISSUE THREAD

**Issue by webdsf** [WWBN/AVideo#6117]
Hello. And how to use it. When I turn on the boot lock. Playlists do not work, not on the site where they are stored. And how to use it, I tried to enter domains where it stands, but it doesn't work. I only used playlists, not embeddings.
![Screenshot_2](https://user-images.githubusercontent.com/60380221/147413579-962dd9db-9c71-47b8-b589-489a27e43c0a.png)
![Screenshot_1](https://user-images.githubusercontent.com/60380221/147413581-fafea525-d632-4be6-b5c9-4fc292430dc6.png)
Latest version 6.0?

**Comment by DanielnetoDotCom** [comment]
Check the log files it may talk you why irmos blocking

**Comment by webdsf** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/60380221/147415514-4f8ac25b-fd3c-4650-ae95-7d5934ae9a0a.png)

**Comment by DanielnetoDotCom** [comment]
The errors are a problem but I guess it is not related to problem o play the HLS

Click on the plus button for more from the logs

**Comment by webdsf** [comment]
And the site slows down a lot, you have to restart everything.
![Screenshot_5](https://user-images.githubusercontent.com/60380221/147415756-dad69dc5-7c54-4e69-a10b-5982b00f2453.png)

**Comment by DanielnetoDotCom** [comment]
I can see a lot of errors on your log

and seems to me your server cannot handle AVideo, (maybe due the errors)

is this a Ubuntu without control panel server?

Are you using AVideo player to play your videos or you are trying to use an external player?

**Comment by webdsf** [comment]
I use a clean system, but I use an external player playerjs, I insert an hls playlist into it. Above is a screenshot. You have access to my server. At u3dlover mail.

**Comment by DanielnetoDotCom** [comment]
If you want to use an external player you MUST disable the HLS download protection, otherwise it will only play on AVideo player

**Comment by webdsf** [comment]
but how to protect the download, is there no way? 
Also these are all errors. you can fix them, of course, not for free. Otherwise, it is not at all clear where they came from, and with what it is connected. work here for an hour?

**Comment by DanielnetoDotCom** [comment]
Forbid external player is download protect the video 

otherwise you can use players to download your video

I am not sure where your errors come from . And I cannot guarantee make it work 100%

The only way for me to guarantee is if you let me make a clean installation

**Comment by webdsf** [comment]
> Forbid external player is download protect the video

That is, it can be done somehow?
you can learn more about the other fields in this plugin. What are they responsible for?

**Comment by webdsf** [comment]
when downloading a video.
![Screenshot_6](https://user-images.githubusercontent.com/60380221/147416616-6e6be561-cb9a-45df-a481-0619917caeee.png)

**Comment by DanielnetoDotCom** [comment]
It the external player has his own user agent you can whitelist it

**Comment by DanielnetoDotCom** [comment]
I just check again and I do not think you will be able to use this player with the download protection enabled
