### ISSUE TITLE
Live Links not showing and Live Bell count just says zero 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6118]
![c07be631-4ab2-404f-92b3-19e11675d6e6](https://user-images.githubusercontent.com/39392449/147540168-535d19d5-4511-40f9-bd9e-bdbb1b1b8d57.png)

**Comment by JoshWho** [comment]
You know what, I like this actually. You can still find them in the categories scrolling down. This is great now it just needs the number count fixed for how many live streamers is on. For some reason it says 0

**Comment by DanielnetoDotCom** [comment]
Hi, I found the problem and I sent a fix already

**Comment by JoshWho** [comment]
Thank you. Working good again
