### ISSUE TITLE
No AD SERVER is it possible to exclude some users?

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#6119]
Hi Daniel
I would like to know if it is possible to exclude some users.
Only for some users I would not like to activate AD SERVER on their videos.
It's possible?
I give an example:
I activate AD SERVER and then advertising works on every video.
However, there is the XXX user who does not want the AD SERVER functionalities active on his videos.
Can I ban the XXX user?

I await a solution.

Thank you

![AD SERVER](https://user-images.githubusercontent.com/82677269/147553370-d5e909ca-5c68-403a-9d2d-dd33d2f42171.PNG)

**Comment by DanielnetoDotCom** [comment]
On Subscription and PayPerView plugins, there is an option for free play with ads

![image](https://user-images.githubusercontent.com/18009293/147569206-b6f1a8a9-051e-4b7b-bd2b-d598b12042ec.png)

![image](https://user-images.githubusercontent.com/18009293/147569345-4eeab7ce-9f32-41b8-82f8-93e9f3238894.png)

So you can enable the "pay to remove ads" or manually add users into plans to remove ads
