### ISSUE TITLE
Registration block for a mailing list

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#6120]
I would like to know if this is already possible.
I would like to insert a mail list to block registrations.
Example:
@ wiicheat.com
@ guerrillamail.com
@ zwoho.com
And many others.
There are so many temporary emails on the web and I would like to avoid signing up with temporary emails.

It's possible to do it?

**Comment by DanielnetoDotCom** [comment]
Sorry currently this is not possible

but you can start to block undesires IPs (User_Controll plugin)

![chrome-capture (1)](https://user-images.githubusercontent.com/18009293/147569696-e505be41-3fa5-4d83-bbae-a36f37a0ea6a.gif)

**Comment by sharknetwork24** [comment]
It would be great if you integrate this feature in future updates.  Or by creating a new plugin.  What do you think Daniel?

**Comment by JoshWho** [comment]
I have a really neat solution that has been working great for me for almost 3 years now. I too use to get those stupid comment spam bots talking about making money online and what not. I use AI and a few other things to scan all packets and entries and one of the methods that completely got rid of the comment spammers was when I integrated Stop Forum Spam https://www.stopforumspam.com/mods
