### ISSUE TITLE
apache:apache instead of www-data:www-data question

### ISSUE THREAD

**Issue by jtandev1** [WWBN/AVideo#6123]
My install on Centos 7
I did the sudo chown apache:apache  /var/www/html/YouPHPTube/videos

But still getting the permissions problem:
 Your videos directory must be writable

Then you can set the permissions (www-data means apache user).

sudo chown www-data:www-data /var/www/html/YouPHPTube/videos && sudo chmod 755 /var/www/html/YouPHPTube/videos 

How to I fix this? the user:group is apache:apache?

Thanks,
Joy

**Comment by jtandev1** [comment]
Hi,
This is the folder
drwxr-xr-x.  2 apache apache      6 Dec 28 12:01 videos

Joy

**Comment by DanielnetoDotCom** [comment]
Hi, we strongly recommend you to use Ubuntu without any type of control panel.

We do not support Centos

**Comment by JoshWho** [comment]
Centos is a nightmare with this. Ubuntu 18 and up is ok Debian maybe
