### ISSUE TITLE
CSS Code Showing On Video Player

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#6124]
Since I updated my site a few days ago, there is some CSS code showing up on the video player when you hover your mouse over the gear icon (video quality or resolution).

![Video-Player-bug](https://user-images.githubusercontent.com/45924889/147618870-8591b193-ea0a-4dba-ac62-21ba3f475b1e.jpg)

**Comment by DanielnetoDotCom** [comment]
You need to update all paid plugins also.

**Comment by The-Do-It-Yourself-World** [comment]
I have updated literally everything and all tables. There is nothing left to update.

**Comment by The-Do-It-Yourself-World** [comment]
I had some tables to update on plugins that I never used before. Fixed. Thanks.

**Comment by The-Do-It-Yourself-World** [comment]
I thought the issues was gone but someone complained and I checked again and there it is.

**Comment by DanielnetoDotCom** [comment]
Are you using VideoResolutionSwitcher version 3.7?

are you sure all your files are up to date?

clear your cache and check if the error persists
