### ISSUE TITLE
Video Thumbnails Not Showing On Imported Videos Since Update

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#6125]
Since I updated a few days ago thumbnails are not showing up on videos which are imported from YouTube or other sites. Thumbnails from direct uploads are working fine.

Far as I know, the only changes made were from the update process.

![Video-Thumbnail-Bug](https://user-images.githubusercontent.com/45924889/147619059-716cf915-97f8-4ec2-95cd-6eaff368c173.jpg)

**Comment by DanielnetoDotCom** [comment]
Did you also update the encoders?

**Comment by The-Do-It-Yourself-World** [comment]
It appears to be up to date:

![Encoder-Updated](https://user-images.githubusercontent.com/45924889/147686225-d59b9299-60b2-4856-b0c9-75cf2b1c874c.jpg)

**Comment by DanielnetoDotCom** [comment]
Yes seems to be fine, so then clear your log files (encoder and streamer)

import one more video and share both logs

**Comment by The-Do-It-Yourself-World** [comment]
Seems to be working. I did not know I had to manually update some things. Thanks.
