### ISSUE TITLE
Google Adsense-1) cannot update the latest version of the plug in-eventhogh i have the latest package2) oogle Ad only seen on topf of the page not seen in between the menus 

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#6126]
Google Adsense-
1) cannot update the latest version of the plug in-even though i have the latest package

2) Google Ad only seen on top of the page not seen in between the menus 

Please help;

website-www.maritimeplatform.com

**Comment by DanielnetoDotCom** [comment]
Google ads is a paid plugin, you need to download it from the marketplace site.

https://youphp.tube/marketplace/

if you do not have the user or plugin access anymore. find your Paypal receipt and email me at developer@youphptube.com

**Comment by vraghavans** [comment]
Dear Daniel,

Google Ads plugin i have and i downloaded the zip file and even uploaded ,but after uploading nothing happens-it does not get imported and i cannot see a install option

**Comment by DanielnetoDotCom** [comment]
Try to manually delete the plugin

then upload it again.

**Comment by vraghavans** [comment]
Dear Daniel,

Thanks done.

Could you please update on the 2nd point ,why the Ad is seen only on the top and not in between pease
Rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
can you screenshot so I can understand what do you mean?

also please provide a screenshot of your plugin parameters

**Comment by vraghavans** [comment]
<img width="961" alt="image" src="https://user-images.githubusercontent.com/65802024/147706771-426f2ab4-013e-4bf6-977a-ede3cbec8e9a.png">
Dear daniel,see i have marked the Ad but this Ad is not repeating on the page but only one instance is seen
screenshot of parameters
![image](https://user-images.githubusercontent.com/65802024/147706878-ea540244-a2a9-472c-bef7-e8780e8c3681.png)
thanks for your help!

**Comment by vraghavans** [comment]
![image](https://user-images.githubusercontent.com/65802024/147706906-e97d11b8-1fda-43e1-85fc-fdc40380d1c2.png)

**Comment by DanielnetoDotCom** [comment]
Looks like you are mixing ads

the google one requires you a vast tag. NOT a video file 

you should google about vast tags 

the ads at the top may come from the ADs plugin NOT from google IMA
