### ISSUE TITLE
API Search?

### ISSUE THREAD

**Issue by tbryantAE** [WWBN/AVideo#6127]
How do I use the API call for a "search".  Like I want to search for "Hello" to see which videos have that in their title?

Please let me know.

Thanks,

Todd

**Comment by DanielnetoDotCom** [comment]
Hi

the search searches on the title, description and category title and description

for example on demo site if I want to search for the word "narrative" I will use this ...

https://demo.avideo.com/plugin/API/get.json.php?APIName=video&searchPhrase=narrative
