### ISSUE TITLE
SignUpAgreement Appears on Embedded URLs

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6128]
We have been receiving complaints from some of our users that the SignUpAgreement popup keeps loading on each embedded video they post on other sites and platforms. They wish it would not. Is this a bug or intentional? if the latter, can something be done about it?

IMO it should only appear when a users actually enters the site and only once. Would appreciate your input.

God bless...

**Comment by DanielnetoDotCom** [comment]
On the plugin SignUpAgreement version, 2.3 should not show popups on the embed anymore.

**Comment by guymass** [comment]
OK thanks and when can we expect the new update?

**Comment by DanielnetoDotCom** [comment]
> OK thanks and when can we expect the new update?

It is already available :)
