### ISSUE TITLE
Query - Avideolog::Security  - Total: 385 errors needs your attention ??

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#6129]
Hi 

checking logs I found the above info, but everything seems to be running fine. 

In red is the below:
 [26-Dec-2021 14:32:12 UTC] AVideoLog::SECURITY: ddosProtection:: progressive timeout timeoutReal = (5) active_connections = (40) maxCon = (40)  SCRIPT_NAME: /plugin/TopMenu/index.php

Does this mean anything ?

I have bitninja protecting my website. Could this be related ?

Otherwise everything seems fine.

Regards

**Comment by DanielnetoDotCom** [comment]
this means something repeatedly tried to access the TopMenu/index.php file and it was blocked by the DDoS protection.

This is not a real security issue, but if someone, even with permissions, try to make multiple requests at the same time, it will be blocked

**Comment by kollossus55** [comment]
Ok thanks..

The main thing everything is alright..

Regards

________________________________
