### ISSUE TITLE
Error When Answering A Comment After Last Update

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#6131]
When I try to answer a comment under the link "Comments" on the menu side bar, I get an error saying "Error Video is Empty" which is odd. Then the comment I wrote is gone. I tried saying "thanks" and I tried again to say "Thank You" and both times I get the same error.

![Comment-Error](https://user-images.githubusercontent.com/45924889/147762037-c741e86e-02f1-41e4-a2f8-b2f6629928eb.jpg)

**Comment by The-Do-It-Yourself-World** [comment]
Update: I get the same error on my test server in my office. I just did a full, clean install yesterday on a new VM for testing. Same issue.

**Comment by DanielnetoDotCom** [comment]
How exactly do I get into this page?

**Comment by DanielnetoDotCom** [comment]
Nevermind, found and fixed

**Comment by The-Do-It-Yourself-World** [comment]
Thanks. Working now. Love the comment spam filter!!!
