### ISSUE TITLE
Question About Live Playlist Features 

### ISSUE THREAD

**Issue by LATINMIXMASTERS** [WWBN/AVideo#6133]
I like the feature of Been able to play live a playlist but what i dont like is that the playlist live after is finished i creates another file and saved the live broadcast, i think something need to be configured so the playlist live features does not record and save the same content again and waste space.

**Comment by DanielnetoDotCom** [comment]
you can set your record for manual record `record all manual;`.

this will require you to click on the record button when you want to record something 

```
recorder video{
    record all manual;
    record_path /var/www/tmp;
    record_notify on;
    record_max_size 2048M; 
    record_suffix -%d-%b-%y-%T.flv;
}
```

Than check this https://github.com/WWBN/AVideo/wiki/Record-Live-Stream#start-record

**Comment by LATINMIXMASTERS** [comment]
So this will make each user to decide what they want to send to recorder? And it will show on their videos later? Just making sure.

**Comment by DanielnetoDotCom** [comment]
Correct, that is the idea

**Comment by LATINMIXMASTERS** [comment]
Ok thank you so Much Daniel You are the Best
