### ISSUE TITLE
Upload page issue - "Sorry! This streamer site is not allowed"

### ISSUE THREAD

**Issue by jtandev1** [WWBN/AVideo#6134]
Where can I fix this, when I try to upload a video, it asks me to sign in and I got this message.

Sorry! This streamer site is not allowed.

Where can I change the site configuration for this?

Thanks,
Joy

**Comment by DanielnetoDotCom** [comment]
Go to your server terminal and run this ...

`php /var/www/html/AVideo-Encoder/install/makeEncoderPublic.php `

of course, replace `/var/www/html/AVideo-Encoder/` with your encoder installation path

**Comment by jtandev1** [comment]
HI,

After I login to the AVideo site, I clicked on the "Encode video and audio" link
It takes me to a login page and after a few minutes it comes up with 
X
Sorry!
We could not find your streamer site!

What am I doing wrong?

Thanks,
Joy

PS. I did run the makeEncoderPublic.php

**Comment by DanielnetoDotCom** [comment]
that means your encoder server could not reach your streamer site.

**Comment by jtandev1** [comment]
HI,

I was able login to my streamer site
so what is wrong with with my config that it required another login for the encoder?

Joy

**Comment by DanielnetoDotCom** [comment]
I am not saying you cannot, I am sure your encoder server could not connect to your streamer. 

check your encoder log for some clue

**Comment by jtandev1** [comment]
Thanks, I think I know what is the issue now.
Joy
