### ISSUE TITLE
Make Users Inactive After Set Time

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#6136]
Can we set users inactive after a certain number of days/months automatically and then make them active again if they sign back in one day?

It would be quite helpful for accounting reasons and to reduce sent emails (bulk email blasts) and so on.

**Comment by DanielnetoDotCom** [comment]
Hi, I may add this feature in the future

**Comment by The-Do-It-Yourself-World** [comment]
Please let me know. Especially for crypto, with a limited total available amount, paying into a dead wallet will reduce what we have in circulation. This can increase its value but also reduce what we have in circulation to pay members with.

**Comment by DanielnetoDotCom** [comment]
FYI when you inactivate a user you also inactivate his videos

**Comment by The-Do-It-Yourself-World** [comment]
That would not be good. But I am sure it can be separated tho.

**Comment by The-Do-It-Yourself-World** [comment]
How hard would it be to not pay members who have not been active for a set time? Lets say someone has not logged in for 6 months so they do not get paid until they come back again. Payment begins from the day they come back with no back pay for lost time. This reduces waste for inactive users and lost cryptocurrency which is a premium due to a limited amount available.

**Comment by DanielnetoDotCom** [comment]
there is a table called users_login_history

on that table, you can find out the last login for each user.

you may need to modify your script to only reward users that have the last login > (1 year ago)

Are you using the [MonetizeUsers](https://github.com/WWBN/Avideo/wiki/MonetizeUsers-Plugin) plugin to [reward](https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform#reward-per-view) your users?

**Comment by The-Do-It-Yourself-World** [comment]
I am using the old DIY plugin you wrote for me years ago. Sadly it is not finished and is paying full rewards for 0 seconds viewed as well as spam comments.

Can the MonetizeUsers plugin work with my existing crypto site and payments or would I have to shut down DIY and switch fully to MonetizeUsers?

And is that a better plugin these days? I have never tried it.

**Comment by The-Do-It-Yourself-World** [comment]
No, forget it. Looks like its only per view. My site pays for thumbs up - thumbs down on comments and videos as well as pay for writing a comment and for a video view.

**Comment by DanielnetoDotCom** [comment]
you may need to update your plugin with the new rules.

**Comment by The-Do-It-Yourself-World** [comment]
Which one? Everything shows its up to date now.

**Comment by DanielnetoDotCom** [comment]
You MUST code and update the " old DIY plugin"

**Comment by The-Do-It-Yourself-World** [comment]
Ok. I had no idea. I thought it was all automated.

**Comment by DanielnetoDotCom** [comment]
I guess you still do not understand.

If you need new features it will require some code work.

you can code by yourself or you can hire me to do it for you.

**Comment by The-Do-It-Yourself-World** [comment]
LOL. Ok, sorry. I just spent the last few minutes looking for updates.
