### ISSUE TITLE
Discord notify webhook still not working

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#6137]
Couldn't reopen old issues but this is still dead.

**Comment by Puyodead1** [comment]
> Couldn't reopen old issues but this is still dead.

As I said in the other issue, I'm looking into it.

**Comment by Puyodead1** [comment]
Okay, I've here's what I've found:
1. It fails to send if the duration is empty, I've got a PR ready to submit after I can test it.
2. It seems like the notifications don't even get triggered by AVideo. I don't get any of the logs from the `afterNewVideo` function in any plugin, and the only way I could get it to work in the slightest was editing `videoAddNew.json.php` and allow the `video` type to trigger notification, and even then I had to use postman to manually send a post request to trigger it. Maybe I'm missing something here? @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Hi, 

I checked your code and the method afterNewVideo is wrong

it is a static method on the abstract AVideoPlugin class, so your plugin should be the same (this become a problem on PHP8)

![image](https://user-images.githubusercontent.com/18009293/147949390-d403abb8-cc90-45a7-a596-06b62f5d7cb3.png)

![image](https://user-images.githubusercontent.com/18009293/147949366-c0422ea2-1494-4de1-b03c-dd8d97825b71.png)

I do not know how to test this plugin, but I sent you some changes that may make a difference.

**Comment by DanielnetoDotCom** [comment]
I do not see a problem with the plugin.

how are you submitting the videos? encoder or direct upload?

**Comment by Puyodead1** [comment]
> > Hi,
> > I checked your code and the method afterNewVideo is wrong
> > it is a static method on the abstract AVideoPlugin class, so your plugin should be the same (this become a problem on PHP8)
> > ![image](https://user-images.githubusercontent.com/18009293/147949390-d403abb8-cc90-45a7-a596-06b62f5d7cb3.png)
> > ![image](https://user-images.githubusercontent.com/18009293/147949366-c0422ea2-1494-4de1-b03c-dd8d97825b71.png)
> > I do not know how to test this plugin, but I sent you some changes that may make a difference.
> 
> Edited, I was wrong on the last comment

Ah alright, I was referencing other plugins so I didn't even notice this.



> I do not see a problem with the plugin.
> 
> how are you submitting the videos? encoder or direct upload?

I tried both encoder and direct upload, I couldn't see anything in the logs from afterNewVideo from any plugins

**Comment by DanielnetoDotCom** [comment]
I could confirm the issue and I am sending an update that may fix it.

please try now...

**Comment by Puyodead1** [comment]
> I could confirm the issue and I am sending an update that may fix it.
> 
> please try now...

Yep, that fixes it for me! Thank you

**Comment by fakeologist** [comment]
Thanks all good!  Happy New Year Daniel!
