### ISSUE TITLE
A Whole Lot Of Videos No Longer Play Since The Last Updates

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#6138]
I keep finding more and more videos that do not play anymore suddenly. These are videos that did work. They even have views and comments on them.

Here are some examples:

https://diytube.video/v/955
https://diytube.video/video/493
https://diytube.video/v/1012
https://diytube.video/v/2176

I can keep going. There are thousands across the entire website ranging from old to new.

I am using Wasabi cloud storage on AWS plugin. Wasabi says they do not lose data. The only thing that changed in the past year or so is a mess of updates on the software I just completed.

Here I am looking at "My Videos" in the admin menu and can find many broken files per page as I scan through.

![Missing-Files](https://user-images.githubusercontent.com/45924889/147858681-2a96728f-eb86-4367-8e06-ab878cd61d42.jpg)

**Comment by The-Do-It-Yourself-World** [comment]
I do not understand what is going on. As I browse through older videos on one of my channels, the videos all show up in the list on my channel page. But when I click them to view, they all open the first time. When I click on play, some fail. And then, the video page never loads again and I get a video not found error next time I try to open that video.

On "My Videos" in the admin panel, I was browsing videos and at first, before I view a video, there are no broken files. But once I view a video and come back to the admin panel, it shows that it has a broken file.

And yes, everything is updated fully.

**Comment by The-Do-It-Yourself-World** [comment]
I have been working on nothing but this for hours now. I have been screen printing random video pages before and after playing until I found one that fails. I cannot find a pattern. It seems random to me so far.

Here is a video play page before failute:

![Video-play-before-failure](https://user-images.githubusercontent.com/45924889/147859657-dc53044c-ea37-4326-b30f-f8a5e76ab801.jpg)



And "My Videos" showing the same video. Everything looks fine so far:

![Video-Before-Failure](https://user-images.githubusercontent.com/45924889/147859660-eb100168-d87f-4b0c-bfa8-0edf4ab5ff5c.jpg)

**Comment by DanielnetoDotCom** [comment]
that means it does not find a playable file in your videos folder 

try to check if inside the folder there is a playable file.

a helpful tool is to run this ...

https://github.com/WWBN/AVideo/blob/master/install/reviewBrokenVideos.php

run this ...

`php /var/www/html/AVideo/install/reviewBrokenVideos.php`

check if there is a file to play inside the folder, even a dummy file

**Comment by The-Do-It-Yourself-World** [comment]
Now, I clicked on play and this is what I get on the play page:


![Video-Play-After-Failure](https://user-images.githubusercontent.com/45924889/147859715-0f5dbd0f-2228-4c4d-be1a-9002a88af007.jpg)

And in the admin panel, a new error shows up:


![Video-After-Failure](https://user-images.githubusercontent.com/45924889/147859721-bcaa3de9-4087-42f3-881b-7ce75b667d82.jpg)

**Comment by DanielnetoDotCom** [comment]
this does not delete any video but if the video was not found it flags it as broken.

I hope when you update your videos you had run this 

https://github.com/WWBN/AVideo/blob/master/install/moveFilesToFolder.php

`php /var/www/html/AVideo/install/moveFilesToFolder.php`

**Comment by The-Do-It-Yourself-World** [comment]
No, I had no idea that had to be run. I used the automatic update button in the admin panel.

**Comment by The-Do-It-Yourself-World** [comment]
I am losing videos as fast as I can browse them. How can I fix this now?

**Comment by The-Do-It-Yourself-World** [comment]
"reviewBrokenVideos.php" just says "Command Line Only". What does that mean? How do I use this?

**Comment by DanielnetoDotCom** [comment]
yes, the command line only

If you do not run the command moveFilesToFolder.php, you will lose basically all old videos

I told you this here https://github.com/WWBN/AVideo/issues/6111#issuecomment-1000549220

**Comment by The-Do-It-Yourself-World** [comment]
Well, it was too late at that point because I had already run the updates by clicking on "Update Version". There were no warnings on the page, just updates.

Can I run that program now or is it too late?

**Comment by DanielnetoDotCom** [comment]
I think you still can run 

`php /var/www/html/AVideo/install/moveFilesToFolder.php`

after that run 

`php /var/www/html/AVideo/install/reviewBrokenVideos.php`

replace `/var/www/html/AVideo/` with your AVideo path

**Comment by The-Do-It-Yourself-World** [comment]
The first program is still running? How long should it take to finish?

**Comment by DanielnetoDotCom** [comment]
it may take a while, you need to leave it running.

you should see progress on the command

**Comment by The-Do-It-Yourself-World** [comment]
Not a thing visible. Just a blinking cursor.

**Comment by DanielnetoDotCom** [comment]
please wait, but keep in mind you can run it as many times as you want

**Comment by The-Do-It-Yourself-World** [comment]
Ok. I restarted it. I will leave it as long as it takes and get back to you.

**Comment by The-Do-It-Yourself-World** [comment]
Done running. Both programs did have some output info. Nothing is fixed.

**Comment by DanielnetoDotCom** [comment]
Then try this 

`php /var/www/html/AVideo/install/moveFilesToFolder2.php`

make sure you run this with sudo user

**Comment by The-Do-It-Yourself-World** [comment]
Still running the program over and over. Each time it finds more files. moveFilesToFolder2.php did not seem to do much. The first one keeps going for a while and stops. I run it again and it finds more. Hours and hours at it. I will keep going until it finds no more files.

**Comment by DanielnetoDotCom** [comment]
> Still running the program over and over. Each time it finds more files. moveFilesToFolder2.php did not seem to do much. The first one keeps going for a while and stops. I run it again and it finds more. Hours and hours at it. I will keep going until it finds no more files.

Keep going until move all the files, maybe it is a script timeout due to you have a lot of videos.

**Comment by The-Do-It-Yourself-World** [comment]
Yes, I think so. I now see only 8,600 files and over 22,300 folders

**Comment by DanielnetoDotCom** [comment]
those may be orphan files but keep running the script until nothing change anymore

then run the `php /var/www/html/AVideo/install/reviewBrokenVideos.php` and check if the videos are fixed

**Comment by The-Do-It-Yourself-World** [comment]
Still running the scripts. I will let you know how it goes later.

Is there a way to add "broken files" to the drop down list on the "my videos" page here:

![Add-Status](https://user-images.githubusercontent.com/45924889/147882594-1fa36a6e-8b6b-466d-83b1-48107c154789.jpg)

And also make videos with broken files hidden on the homepage and search results.

**Comment by DanielnetoDotCom** [comment]
Broken videos will be hidden and there is a filter on videos maneire right menu

**Comment by The-Do-It-Yourself-World** [comment]
Still running the script over and over again. Two days straight. I just changed the max execution time in the script. I think it was timing out before it finished because I have about 300,000 files total.

**Comment by DanielnetoDotCom** [comment]
Correct, I just checked the timeout was only 5 minutes.

I just increase the timeout to 30 minutes

**Comment by barrunning** [comment]
I am having the same problem. On the mobile app same problem. It is new videos as well as old videos.

**Comment by The-Do-It-Yourself-World** [comment]
Update: I am still running the scripts. It seems to be endless. I do have about 40,000 videos and about 300,000 files. It is taking me some time to complete. So far none of the broken videos has been fixed that I know of yet. I will keep going.

**Comment by DanielnetoDotCom** [comment]
what is the last message when the script stops?

**Comment by The-Do-It-Yourself-World** [comment]
It just times out and I start again. I had increased the time. No errors. Just keeps finding more. I just wanted to keep this thread alive until I get it fixed and let you know I am working on it. I am not on it full time all day but I come and go at it when I get a chance because it is taking time. There are a LOT of files.

**Comment by DanielnetoDotCom** [comment]
can you please copy and paste the message?
