### ISSUE TITLE
SignUpAgreement 2.3 Not saving the record.

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6139]
I updated to the 2.3 version and were still checking the issue with popup opening on embed links, so far so good. Now I am trying to edit the agreement I have set in the plugin and even tried to create a second one but it will not save the changes. Once I close the editor window and reopen the agreement it goes back to how its set currently. Here are screenshots of before and after trying to add a secondary agreement.
![Screen Shot 5782-04-29 at 10 34 16](https://user-images.githubusercontent.com/58882903/147870704-989a22cb-c0c2-48ea-93dd-6b7222af51a0.jpg)

after saving, closing and reopening the plugin:

![Screen Shot 5782-04-29 at 10 34 44](https://user-images.githubusercontent.com/58882903/147870714-11b8d35f-5c19-416d-9f47-bd820e0990f0.jpg)

**Comment by DanielnetoDotCom** [comment]
Can you please paste the whole text here so I can try it on my side?

**Comment by guymass** [comment]
1
פלטפורמה להנגשת תוכן לציבורLIVE 528מדיניות פרטיות הנך מתבקש /ת לקרוא מדיניות פרטיות זו בטרם תעשה /י כל שימוש בשירות (כהגדרתו להלן  .)בהיותך משתמש /ת בשירות הינך מצהיר /ה כי את/ה מסכים/ה לכך שפלטפורמה LIVE528 תעשה  שימוש במידע האישי שלך שיגיע לידיו /בכל תוכן אשר יונגש על ידך בפלטפורמה ,והינך מוותר /ת  על כל טענה בנוגע להפרת זכויות יוצרים.לידיעתך בהיותך עושה שימוש /משתמשת בשירותים /מנגיש/ה מידע כלשהו בטלטפורמהLIVE528 , הפלטפורמה רשאית מאותו הרגע להשתמש בכל חומר /תוכן/סרטונים מכל סוג שהוא באופן חופשי  ,והינך מוותר/ת על כל טענה בנוגע להפרת זכויות יוצרים או כל תלונה וטענה מכל סוג שהוא .אם אינך  מסכים/ה לתנאים שלהלן הנך מתבקש /ת לא לעשות כל שימוש בשירות.מדיניות פרטיותמדיניות פרטיות זו מתארת את הדרכים שבהן בכוונת הפלטפורמה לעשות שימוש במידע אישי שלך/תגובות שתעלה/י למדיה ו/או תמונות /סרטונים/שיגיעו לידינו /יפורסמו על ידך  ,דרך פלטפורמה זו ו/או  הערוץ ו/או השירותים הנלווים אליו ו/או באפליקצייה וכיוצא בזה.LIVE528 להלן הפלטפורמה (הערוץ/האפליקציה/האתר )להצגת תוכן סרטונים וכד 'נמצאת בכתובתlive.ahava528.comלהלן יוגדר  "השירות " :אפשרות לצפות /להאזין לשידורי הערוץ /לשדר דרכו ,לצרוך /להחשף /לחשוף  מידע/ידע /כתבות  /סרטונים וכד 'המונגשים בפלטפורמה  ,להגיב לשידורים ולמידע ו/או לשדר מהשטח ON LINE , פיתוח ויצירת טכנולוגיות וכיוצא בזה.(להלן  "השירות").תוכן הפלטפורמה תוכן הפלטפורמה מגוון ונוגע בשדות תוכן שונים ומונגש ונצפה באחריות מלאה של משתמשי השירות/השדרנים /הצופים וכו'.איסוף מידע ושימוש בו תכתובות ורשימת תפוצהבפלטפורמה עשויה להישמר היסטוריית התכתובות (באם היו כאלו )אשר נערכו וזאת לצרכי תיעוד  /שירות לקוחות/ניהול ושיפור השירות.1.בעת ההרשמה לפלטפורמה קיימת האפשרות להירשם לרשימת התפוצה ,כך שמדי פעם  תקבל/י עדכונים בנוגע לשידורים/מידע חדש /ידיעות נוספות ו/או שירותים ומוצרים שעשויים  לעניין אותך .לצורך עליך להזין את כתובת הדואר האלקטרוני שלך .חשוב לציין כי בכל עת  תוכל/י לצאת מרשימת התפוצה על ידי שליחת מייל עם בקשת הסרה לכתובת המייל admin@ahava528.comאו באמצעות הקלקה על לינק "הסרה מרשימת התפוצה ".2.בהורדת האפליקציה ו/או רישום לפלטפורמה /לאתר והשימוש בהם הנך מסכים/ה לקבל מאיתנו  דיוורים והתראות ,לרבות התראות דחיפה (Push Notifications), בנוגע לאפליקציה/לפלטפורמה  ,כולל ומבלי לגרוע בנוגע לאירועים ,שירותים ,עדכונים ,שינויים והתראות לגבי תכנים שסימנת כמועדפים (למשל  ,תזכורת כי תכנית שסימנת במועדפים עומדת  לעלות לשידור .)בכל עת תוכל/י לבטל קבלת התראות בהגדרות המשתמש בשירות ו/או הגדרות  מערכת ההפעלה של מכשירך.וקוקיס ( Cookies ) וווב ביקונס (Web Beacons)
קוקיס הם פיסות מידע קטנות המאוחסנות במחשב שלך וקשורות למידע עליך  .אנחנו משתמשים בקוקיס  של תעבורת תקשורת אשר הפעלתם מסתיימת בעת סגירת הדפדפן ,והן בקוקיסקבועים המאוחסנים בכונן הקשיח שלך .הקוקיס הקבועים לא יימחקו בעת סגירת הדפדפן  ,קוקיס אלו שומרים פרטי תעבורת  רשת ושימוש בשירות על-ידי המשתמש .אנו גם מאפשרים לצדדים שלישיים לעשות שימוש בקוקיס דרך  השירות למטרות ניתוח השימוש בשירות ,איסוף המידע המפורט במדיניות זו וקישור עם שירותים  חיצוניים (לדוגמא פלטפורמות אינטרנטיות או דפי אינטרנט המשתפים את הלינק לסרטון  /למידע  .)בדרך כלל הדפדפן קולט קוקיס באופן אוטומטי ,אך ברוב הדפדפנים קיימת האפשרות לחסום שימוש בקוקיס .אם אתה מעדיף זאת והדפדפן שלך תומך באפשרות זו תוכל לערוךאת אפשרויות הדפדפן  שלך כדי לחסום קוקיס בעתיד  .הפלטפורמה משתמשת בקוקיס מכמה סיבות .לדוגמה  ,קוקיס מאפשרים  לעקוב אחר השימוש אשר עושים המשתמשים בשירות וכך ללמוד איך לשפר את חוויית השימוש  בשירות זה וכן קוקיס מאפשרים לתפעל את השירות .אם תבחר לדחות קוקיס ייתכן שעדיין תוכל  להשתמש בשירות ;עם זאת ,הגישה שלך לאזורים מסוימים ושירותים מסוימים בשירות עשויה להיות  מוגבלת.הפלטפורמה/המערכת עשויה לעשות שימוש בשירות ובמיילים בווב ביקונס בכדי לאסוף את המידע  המפורט במדיניות זו .ווב ביקונס ,או "gifs", הם תמונות אלקטרוניות שמאפשרות למערכת לשלוח  קוקיס ,לנטר את השימוש שלך בשירות או לקבל אינדיקציה לכך שבוצעה פעולה בתכתובת דואר  אלקטרוני מטם המערכת שיתוף מידע כל הידע /הסרטונים /הכתבות וכד 'המונגש בפלטפורמה חופשי לשימוש והעברה.קבלני משנה וספקי שירותהפלטפורמה עשויה לשתף את המידע שלך עם ספקי שירות וקבלני משנה העובדים עם המערכת ו/או  המספקים שירותים מסוימים מטעמה בארץ ובחו"ל וזאת ככל שהדבר יידרש לצורך מתן השירות  ,שיפורו  ופיתוח שירותים נוספים .כמו כן ,הפלטפורמה/המערכת עשויה לאחסן מידע בשירותי ענן ששרתיו  ממוקמים מחוץ לישראל .חברות אלה אינן רשאיות לשתף או להשתמש בעצמן במידע המאפשר זיהוי  אישי שהמערכת מספקת שלא עבור הפלטפורמה או לצורך תפעול השירות .בנוסף, הפלטפורמה עשויה להעסיק גורמי צד שלישי מהימנים כדי לסייע בהפצת סקרים ,פרסום ו/או  תכנים .לאחר השלמת פרויקטים אלה ,הפטפורמה דורשת כי כל המידע יוחזר אליה .לבסוף ,המערכת  משתפת מדי פעם מידע אגרגטיבי עם ספקי השירות שלה .מידע זה אינו מכיל מידע המאפשר זיהוי אישי  באמצעים סבירים והוא משמש לפיתוח תוכניות ותוכן שעשויים לעניין את המבקרים בשירות.מיזוג ושיתופי פעולה המערכת הינה פלטפורמה עצמאית בלתי תלויה במניעים חיצוניים .מבוססת קוד פתוח ורשאית להמחות ולהסב זכויותיה והתחייבויותיה בכל מצב של שיתוף פעולה /איחוד בו משותף התפעול הטכנולוגי  במערכת ו/או נכסיה ו/או בשירות לצד שלישי כלשהו.קישורים בשים לב שהשירות הניתן בפלטפורמה כולל קישורים המובילים לאתרים/לערוצים ו/או שירותים נוספים .שירותים/ערוצים/אפליקציות/אתרים אלו עשויים לאסוף ממך מידע המאפשר זיהוי אישי .מדיניות  פרטיות זו אינה כוללת את נוהלי איסוף המידע או המדיניות של אתרי אינטרנט ושירותים כאלה ו/או כל  גורם שלישי ,וכל שימוש שתעשה בקישורים ו/או בשירותים אלה הינו באחריותך בלבד.אבטחת מידעבשים לב המערכת נוקטת צעדים סבירים כפי הנהוג בתחום על מנת לסייע בהגנה על המידע שמסופק  על ידך המאפשר זיהוי אישי  .המערכת גם מגבילים את הגישה למידע המאפשר זיהוי אישי לחברי  הפלטפורמה  /מתנדבים/עובדים הזקוקים למידע כדי לבצע משימה ספציפית .עם זאת יש לקחת בחשבון  ששום אמצעי ו/או שירות אינם בטוחים באופן מוחלט ,במיוחד כאשר הפעילות היא מקוונת.

**Comment by DanielnetoDotCom** [comment]
I just tested locally and on the demo site and works fine

![chrome-capture (4)](https://user-images.githubusercontent.com/18009293/147951483-305441dc-40f1-460e-9dd1-a01c09777ee5.gif)

can you catch some clue on the logs?

**Comment by guymass** [comment]
You are right, once I cleaned the formatting and pasted simple text it was able to save.
