### ISSUE TITLE
Fresh Install  Live not connecting 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6140]
@DanielnetoDotCom 
I have a fresh install on SSD's now and I got my slow log in issue fixed. Now, I am missing something with the Live Configuration  because I can not get OBS to connect not even to save my life.  Here are the only errors I am getting after I try to push a stream from OBS.
![20220102_020201](https://user-images.githubusercontent.com/70327833/147871698-fa3ba18e-da1a-4e63-bf52-d19c129bb848.jpg)
![20220102_020058](https://user-images.githubusercontent.com/70327833/147871699-12e402a0-aa4f-46e6-be53-c8167c38f798.jpg)
![20220102_020034](https://user-images.githubusercontent.com/70327833/147871700-e7458873-e97e-4f34-9e82-05ce07c73735.jpg)
![20220102_023144](https://user-images.githubusercontent.com/70327833/147871817-e6b9adfe-49df-4b32-905d-0db56b9fbe11.jpg)

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom I need this streaming tonight  do you have any ideas of what I am missing.

**Comment by DanielnetoDotCom** [comment]
Make sure your nginx.conf on_publish parameter is http NOT https and your server can access it properly

**Comment by milehighkaraoke** [comment]
Ok, On Publish was the issue.... Now it connects  but it is not showing up as a live notification and my socket is on and connected

**Comment by DanielnetoDotCom** [comment]
it is connecting and it is working? and no notification?

that is strange. clear your cache and check again

**Comment by antuk21** [comment]
put links to localhost or the IP of your server ! for example, you can do this on_publish http://localhost/plugin/Live/on_publi$ I had the same problem when I put it to my domain it works but no notification so i did the above to fix this just trying to help hope it works for you to (y)
