### ISSUE TITLE
Checkmark???? 

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#6141]
Hello all And happy new year 
Who can tell me what I do with this 3 Checkmark? 

Thank for reply 

![Screenshot_20220103_084950](https://user-images.githubusercontent.com/93554732/147909259-457f5a0d-d4d8-4dbb-96ca-db0d5a594d20.jpg)

**Comment by DanielnetoDotCom** [comment]
the checkmarks will appear with the username ...

![image](https://user-images.githubusercontent.com/18009293/147950413-114b10e9-00d1-4c4b-8d50-aaa7e18bef1c.png)

you can also customize the icon here 

![image](https://user-images.githubusercontent.com/18009293/147950545-dbc5e2bc-1c03-4f3a-a656-d493436919f2.png)

by default, we use the icons from [fontsawesome ](https://fontawesome.com/v5.15/icons)
