### ISSUE TITLE
back button does not work

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6142]
Hello Daniel,
back button does not work
the website address is false 
on my pages it is the same 
![adres_demo](https://user-images.githubusercontent.com/93145787/147926718-83c9aba2-5a3d-4923-b457-7a1f519567f9.png)
![adres_moja](https://user-images.githubusercontent.com/93145787/147927164-0f762c58-b698-41ba-9676-c31424bed1ff.png)

https://user-images.githubusercontent.com/93145787/147926752-3b82b6d1-c89b-4935-9c6b-f2d9635d3c17.mp4

**Comment by KrzysioMisio** [comment]
Daniel, you checked why it is false in the website address

**Comment by DanielnetoDotCom** [comment]
Hi

I am away from the office this week, I will check it next week

**Comment by KrzysioMisio** [comment]
ok

**Comment by KrzysioMisio** [comment]
it works
Thanks 👍
