### ISSUE TITLE
New CORB rules blocking link sharing / CORS scheme

### ISSUE THREAD

**Issue by OptimistPrimal** [WWBN/AVideo#6146]
In debugging the CORS header issues a new item has raised it's head:  the Cross Origin Read Blocking rules.  In trying to test out a video share URL, the player hangs on a CORB warning, generally (but not always) followed by a CORS "no header entry" warning.  Looking at the code it appears you may be requesting the url where the video is being shared/played and dynamically creating a CORS header for it.  The CORB appears to be blocking the destination system from returning its URL to the Sending AVideo app.

`Cross-Origin Read Blocking (CORB) blocked cross-origin response https://bannedtogether.tube/video/300/hunter-dja-operations-hub-overview---monday.com with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

The log shows:

`AVideoLog::DEBUG: Page generated in 0.1355 seconds. User: admin - No Cache (/video/300/hunter-dja-operations-hub-overview---monday.com) FROM: 73.37.51.74 Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 SCRIPT_NAME: /view/index.php`

I'm running all 3 AVideo components on the same Ubuntu 21 Server.

**Comment by OptimistPrimal** [comment]
![image](https://user-images.githubusercontent.com/97070118/147996507-611daa24-1fd7-4db6-aaa3-a32fce74091a.png)
This is a report from the Nunchee.tv app where we are looking to share it.

**Comment by DanielnetoDotCom** [comment]
I am not sure exactly what is this problem, but for testing proposes you should disable the download block from the VideoHLS plugin.

it will be 1 less problem to worry about while resolving the cors issue.

**Comment by OptimistPrimal** [comment]
I disabled the HLS Plugin and tried just before you answered - same error.

**Comment by DanielnetoDotCom** [comment]
what about disabling the secure videos directory?

the problem I am seeing is this  

![image](https://user-images.githubusercontent.com/18009293/147998642-f14737a6-35ee-4beb-b5f0-5efda77768e7.png)

The videojs players suppose to send a token with the .key file request and for some reason, it is not sending.

did you change something on the player? I am not sure why it is not sending

the player request should looks like this 

![image](https://user-images.githubusercontent.com/18009293/147998769-c6321e10-d06e-4463-94d8-fb02c0843e1f.png)

**Comment by OptimistPrimal** [comment]
I'm seeing the request with the token - I'm using the "Copy Video URL" from the right click box on the video.  Turned off Secure Video Directories and cleared the cache.  Same errors.

`https://bannedtogether.tube/video/300/hunter-dja-operations-hub-overview---monday.com`

**Comment by DanielnetoDotCom** [comment]
can you use your server terminal and check the real content of this file? 

videos/video_220103182223_vbf2a/enc_61d3853978508.key

on my side still no token.

also on your side, you have a token, can you check if the key is loading correctly?

**Comment by OptimistPrimal** [comment]
Here's the HLS link from the admin "copy m3u8" (it was uploaded as HLS): `https://bannedtogether.tube/videos/video_220103182223_vbf2a/index.m3u8`

Here's on the server for that file (ýM^UýýýsýG0ýnýýýf)

**Comment by OptimistPrimal** [comment]
This is the JWPlayer Response (Nunchee.tv):

`ERR: 102630 | Either an empty playlist was requested or none of the items passed our filter for valid files. | No playable sources found | This video file cannot be played.`

**Comment by DanielnetoDotCom** [comment]
> Here's the HLS link from the admin "copy m3u8" (it was uploaded as HLS): `https://bannedtogether.tube/videos/video_220103182223_vbf2a/index.m3u8`
> 
> Here's on the server for that file (ýM^UýýýsýG0ýnýýýf)

Is this the same you see on your browser?

if the key is not loading correctly the video will not play.

and the question still. why I cannot see your tokens or keys here?

check your logs for some clue if something is denying access to your keys

**Comment by DanielnetoDotCom** [comment]
Suddenly starts to play now

**Comment by OptimistPrimal** [comment]
I turned the VideoHLS Plugin back on - looks like HLS files don't play without it.  I disabled download protection - same errors unfortunately.

**Comment by OptimistPrimal** [comment]
Here is the right click URL: https://bannedtogether.tube/video/299/a-much-better-world-music-and-video-by-m-white-2022-20220101-1-2022-01-01-14-11-18

here is the Admin m3u8 copy url: https://bannedtogether.tube/videos/video_220101134540_v2d13/index.m3u8

Here is the Admin m3u8 1080 URL: https://bannedtogether.tube/videos/video_220101134540_v2d13/res1080/index.m3u8

**Comment by DanielnetoDotCom** [comment]
VideoHLS is required to play HLS files

the video is playing here now and you cannot use external players on it.

if you want to add it in another page use the embed player, not the direct link

What is the error?

**Comment by OptimistPrimal** [comment]
On Nunchee I have to use an m3u8 link.  The challenge is it is throwing the CORB error (with the HLS Plugin turned on).  I have other videos that were uploaded as mp4 - which Nunchee.tv will take, but there is no admin side copy url option.  The right click URL option doesn't work - it gives the JWPlayer error above.

**Comment by DanielnetoDotCom** [comment]
Sorry, the error is still not clear to me.

can you please try with some video from demo site so we can check if the error is on the script or on your installation?

**Comment by OptimistPrimal** [comment]
Ok, on AVideo.com I grabbed the right click URL: 
`https://avideo.com/video/88/avideo-platform?channelName=AVideo_5fafe3b04206b`
Gives the JWPlayer error

**Comment by DanielnetoDotCom** [comment]
this URL will never play on JSPlayer

also the demo site the videos are download protected 

try to play this 
https://tutorialsavideocomcdnstorage.cdn.ypt.me/video_191214100153_5abb/video_191214100153_5abb_HD.mp4

the mp4 above is from the video https://tutorials.avideo.com/video/78/welcome-to-avideo-platform

Or try this HLS ttps://tutorialsavideocomcdnstorage.cdn.ypt.me/video_210910202753_4487/index.m3u8

from video https://tutorials.avideo.com/video/111/how-to-configure-backblaze

**Comment by OptimistPrimal** [comment]
Ok, that's unfortunate - much of what we were trying to do was cutdown on the bandwidth usage on Nunchee for our daily newscasts and weekly global meetings (20k+ viewers).  

The .mp4 will play in a browser or an MP4 player, but Where do you grab the .mp4 URL?

**Comment by DanielnetoDotCom** [comment]
To get the MP4 , I inspected the source code and got the SRC parameter from the <source> tag
