### ISSUE TITLE
Bug on wallet

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6153]
The wallet is showing some strange characters when using Israel currency symbol.
![Screen Shot 5782-05-04 at 21 17 53](https://user-images.githubusercontent.com/58882903/148438871-4f915b41-00f4-49ff-a31a-4204b67eb630.jpg)

**Comment by DanielnetoDotCom** [comment]
Can you please paste the symbol here so I can test?

**Comment by guymass** [comment]
Sorry for late reply, here it is u20aa

**Comment by DanielnetoDotCom** [comment]
I only copy and paste it here 

![image](https://user-images.githubusercontent.com/18009293/148817649-270b4e23-3dee-4ec0-8aab-cac0987b69ac.png)

**Comment by guymass** [comment]
what is BRL? not the code for Israel money as far as I know.

**Comment by DanielnetoDotCom** [comment]
BRL is set here 

![image](https://user-images.githubusercontent.com/18009293/148824979-42537ce8-1565-48da-af09-665d8f58dec5.png)

you can change to whatever you want

**Comment by guymass** [comment]
OK thanks I fix it. It was like you said in the YPTWallet plugin.
