### ISSUE TITLE
Many thumbnails not showing in google chrome since updates

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#6155]
I have been getting complaints that many of the thumbnails are not showing up anymore since the latest updates. In Chrome browser I am missing a lot of thumbnails. On Brave, Opera and Firefox they are working.

I have cleared the cache a couple times myself and nothing changed. Thumbnails missing. I cannot figure this out. Some of these are newer videos, some are older.

Here is an example screen shot of Chrome browser AFTER cache cleared a couple times.

![Missing-Thumbs](https://user-images.githubusercontent.com/45924889/148650780-1cbe9180-cf45-4145-a58a-dada99da5643.jpg)

**Comment by DanielnetoDotCom** [comment]
Does not make sense fail only in one browser but right click on the image and try to open it directly in a new tab 

se if the image is failing to load

**Comment by The-Do-It-Yourself-World** [comment]
I dont understand what was going on. At least on my computer they are loading now.

**Comment by The-Do-It-Yourself-World** [comment]
Now in my Brave browser that I use every day thumbnails are failing at random. This is the homepage and these thumbnails worked a minute ago. I am getting reports from other people of the same issue on many different browsers. It appears to be quite random. But very unprofessional and never happened in the last 4 years.

![more broken thumbnails](https://user-images.githubusercontent.com/45924889/149752109-275f3405-f963-441b-bb51-8ea5792ecba8.jpg)


![broken thumbnails](https://user-images.githubusercontent.com/45924889/149752125-9acebb37-6ba2-4be2-8d7c-8f253a9231ca.jpg)

**Comment by DanielnetoDotCom** [comment]
Your Apache probably cannot handle multiple requests 

check your ja console 

also check this https://github.com/WWBN/AVideo/wiki/Speed-up-your-page#tuning-your-apache-server
