### ISSUE TITLE
My sign up agreement plug in not working-not able to see the checkbox

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#6156]
![image](https://user-images.githubusercontent.com/65802024/148677332-6871dc33-2287-462a-b724-cf538c251011.png)
![image](https://user-images.githubusercontent.com/65802024/148677354-54aa391a-9293-40f2-b483-60c90bcfec70.png)

I have also deleted the plug in reinstalled the same

**Comment by vraghavans** [comment]
can anyone help me on this please

**Comment by DanielnetoDotCom** [comment]
Make sure you create the agreement

![chrome-capture (1)](https://user-images.githubusercontent.com/18009293/148811132-8ca4bd46-d022-4077-b61d-23fcf8084f17.gif)

**Comment by vraghavans** [comment]
Dear Daniel,

Thanks for the reply,
yes i have 2 agreements but i just noticed that even though i save the agreements it is not getting saved,is there any steps iam missing please

**Comment by DanielnetoDotCom** [comment]
Check the error log when you save it.

also make sure you copy and paste the text on notepad before you copy and paste it into the HTML editor

**Comment by vraghavans** [comment]
copying on the notepad did the trick,thanks for the help!
