### ISSUE TITLE
Encoders com problemas

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6157]
Daniel, o Encoder 1 está imundado de arquivos parados, teria como limpar a lista?
E o Encoder 3 e 4 está inacessível, conseguiria verificar isso para nós?

**Comment by DanielnetoDotCom** [comment]
Olá

o 3 e 4 não existem mais.

retornarão futuramente,

estarei resolvendo o 1 agora

**Comment by gbrn** [comment]
Daniel, confira por favor os encoders... 1 e 2 parados.

**Comment by DanielnetoDotCom** [comment]
Please check it now

**Comment by gbrn** [comment]
Daniel, consegue verificar para nós como está o status dos codificadores? Já tem umas 5 horas que a lista é a mesma.

**Comment by DanielnetoDotCom** [comment]
Verificando agora
