### ISSUE TITLE
Filter videos based on language

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6159]
It would be a good idea to only show users content in their language or at least be able to filter out languages because we have for example german and french videos showing on mixed with hebrew and english. Maybe english should be a main language for everyone and an option to only show videos with titles of a certain language. We can identify the language from video titles and the posting channel language selection and allow filtering videos to different audiences in a more focused manner IMHO.

**Comment by DanielnetoDotCom** [comment]
I guess you are looking for a way to translate titles and descriptions for videos, correct?

I may add this in the future

**Comment by guymass** [comment]
Well that is a needed thing as well, but what I was referring to is actually also filtering the videos based on country or language so for example french people should only see french and english videos but nothing else like german or hebrew. Currently I see any video uploaded in all languages although I don't understand those languages I would prefer to filter them out from my home page which is set to be in Hebrew.

**Comment by DanielnetoDotCom** [comment]
Just thinking...

what about create a separate installation for each language?

like 

- en.mydomain.com for English
- es.mydomain.com for Spanish
- ar.mydomain.com for Arabic
- pt.mydomain.com for Portuguese

etc

also you can point more than one domain to the same installation.
