### ISSUE TITLE
PPVLive - money isn't transferred

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6160]
@DanielnetoDotCom hi

I've noticed something strange on PPVLive plugin. There are some users who uploaded money to the wallet. They paid for a livestream and the money remained in the wallet, but it transferred via PayPal.

So there are accounts who's history says 10USD. In PayPal it shows 10USD has been paid to the person doing the Livestream. But the account is of the person who paid still has the 10USD.

I have 6 accounts showing money retained in the wallet despite having paid and accessing the service.

Client "uploads" money
![ppv-2](https://user-images.githubusercontent.com/65451390/148825347-515612f2-a581-4792-a6da-2828a1a7d954.jpeg)

Client pays the uploaded money
![ppv-3](https://user-images.githubusercontent.com/65451390/148825389-bca04036-7f87-446f-84d0-0b0ac9a7fcee.jpeg)

Client still has the money in the account balance
![ppv-1](https://user-images.githubusercontent.com/65451390/148825476-f32bcf2b-63a9-4c16-890a-eebfc2cf8a2a.jpeg)

Any way you can assist to make sure the money paid is removed from the account?

Thank you

**Comment by DanielnetoDotCom** [comment]
check the history to see what happen

![image](https://user-images.githubusercontent.com/18009293/148826597-f78cb7e5-ff8e-48dd-9486-b96308edf7c6.png)


you should see all transactions.

**Comment by jengajenga** [comment]
> check the history to see what happen
> 
> ![image](https://user-images.githubusercontent.com/18009293/148826597-f78cb7e5-ff8e-48dd-9486-b96308edf7c6.png)
> 
> you should see all transactions.

history here only shows one transaction.

see the first picture I sent written "success" in green. that is the only history the client has.

**Comment by DanielnetoDotCom** [comment]
Hi, 

So if there is only one transaction it means it loads the account but did not purchase the PPV or subscription.

if the use purchase something it should be on the history

**Comment by jengajenga** [comment]
> Hi,
> 
> So if there is only one transaction it means it loads the account but did not purchase the PPV or subscription.
> 
> if the use purchase something it should be on the history

The person was able to access the livestream. in paypal, the money has been sent. in the ppv it shows that the money never left the wallet.
there are 6 similar issues all for the same stream.

client uploads, sends the money, gets access to the livestream. in paypal, money is received. in the wallet, the money remains with the sender.

**Comment by DanielnetoDotCom** [comment]
Really strange. 

can you manually remove the access to the live stream and force the user to purchase it again?
he will be forced to use the wallets money

if the money is not transferred check the logs for errors.

**Comment by jengajenga** [comment]
unfortunately I don't have logs from that far back. 

then also, forcing the user to purchase again spoils the user experience and can make them refuse to buy.

please have a look at it.

**Comment by jengajenga** [comment]
> > unfortunately I don't have logs from that far back.
> > then also, forcing the user to purchase again spoils the user experience and can make them refuse to buy.
> > please have a look at it.
> 
> As long as the money is in his wallet this should not be a problem.
> 
> I am just trying to reproduce the issue. for now, I have no clue what may cause that.
> 
> I have one question...
> 
> do you have customers that made the payment and the money went out of the wallet as supposed to be?

Yes I do, plenty. In fact that event attracted about 40 paying customers. It is only 6 of them that had this issue.

**Comment by DanielnetoDotCom** [comment]
I see, this makes it even harder to find out.

if you want email me your server SSH credentials and an admin user for your site.

also, tell me exactly what users you found what this error. I will try to understand what happened.

**Comment by jengajenga** [comment]
> I see, this makes it even harder to find out.
> 
> if you want email me your server SSH credentials and an admin user for your site.
> 
> also, tell me exactly what users you found what this error. I will try to understand what happened.

Sending them via email shortly

**Comment by DanielnetoDotCom** [comment]
FYI I still not received the email
