### ISSUE TITLE
Video plays in safari web browser but not chrome or edge

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6161]
Videos will not play in edge or chrome browser. Mac or windows operating. They will play in safari.
Using iPad Pro 15.0.2 4th generation 

same on windows 11 for chrome and edge.

**Comment by barrunning** [comment]
![9DD7B8E7-0A9E-4C27-8D3B-F5B1C9203A7A](https://user-images.githubusercontent.com/58601786/148884568-1380de40-7a08-408d-a80b-4ee8abf58f73.png)
This is screen shot of https://avideo.com/page/5

**Comment by DanielnetoDotCom** [comment]
I am using chrome and it works fine here

**Comment by barrunning** [comment]
Here is a screen recording. This is in safari.

**Comment by barrunning** [comment]
This is the mobile app. iPad Pro

**Comment by barrunning** [comment]
This is edge.

**Comment by DanielnetoDotCom** [comment]
Hi, I am not seeing any recording or screenshot on your comments

please use the site [demo](https://demo.avideo.com/) for testing
