### ISSUE TITLE
I can watch videos in categories that I don't have permission to watch. 

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#6162]
I set the user group for each category and
Only for users who belong to the set user group
I have the authority to watch the video,
I can watch videos in categories that I don't have permission to watch. 
[AVideo.log](https://github.com/WWBN/AVideo/files/7845237/AVideo.log)

**Comment by DanielnetoDotCom** [comment]
the category currently does not prevent users to watch videos.

private categories mean, only the category owner can add videos into that category.

the only way to prevent users to watch videos is to use user groups

**Comment by hnagasawa** [comment]
All category are public. For example categroy A and B.
UserGroup Mine bleong to user kazuki and umi
UserGroup Fukui belon to user takeuchi and hira.
We set next
Usergeoup A can watch videos in category A
UserGroup B can watch videos in category B
 
Yesterday, Admin user uploaded new video in category A.
But user "takeuchi(usergroup B) can coudl new video in category A.
What do we check ?

**Comment by DanielnetoDotCom** [comment]
you cannot ser user groups to watch categories. we do not have this feature.

**Comment by hnagasawa** [comment]
What does "the only way to prevent users to watch videos is to use user groups" mean? Or do we need a new plugin or our request new plugin ?

**Comment by DanielnetoDotCom** [comment]
This means, if you want to make a video private, you MUST add this video into a user group.

currently, there is no option to do it with categories.

Maybe I am misunderstanding you. please provide some screenshots of what you are doing, so it may help me to understand

**Comment by hnagasawa** [comment]
Please let me know what kind of screenshot you should send to get you to understand.

**Comment by DanielnetoDotCom** [comment]
To be honest, I think you misunderstand the feature. Again, you cannot make videos private using categories.

I am just saying if you think I misunderstand you, you can try to explain again with some screenshots

**Comment by DanielnetoDotCom** [comment]
The user group should make the video private.

the category public or private should make no difference

![image](https://user-images.githubusercontent.com/18009293/149565330-1bd52daa-1242-4f41-aa68-d7c0d5b075a5.png)

**Comment by hnagasawa** [comment]
If we select a User Group when uploading a video with AVdieo-Encoder, can the video be viewed only by the selected user group?
Do you recommend making the category private if only admin is uploading videos?

**Comment by DanielnetoDotCom** [comment]
> If we select a User Group when uploading a video with AVdieo-Encoder, can the video be viewed only by the selected user group?

Correct

> Do you recommend making the category private if only admin is uploading videos?

It is up to you, the category makes no difference on the videos permssions

**Comment by hnagasawa** [comment]
If we do not select a User Group(select categry only) when uploading a video with AVdieo-Encoder, 
can anyone watch this video?

**Comment by DanielnetoDotCom** [comment]
Correct
