### ISSUE TITLE
This link isn't showing the radio graphic 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#6164]
https://fakeotube.com/view/videoViewsInfo.php?hash=bWtrYTVIZ3d1clpwb0VsS2pJczVQMVpWOU5RWHRoRjRwMml6ZHJOSUhQUT0=

It's an mp3 file .

**Comment by DanielnetoDotCom** [comment]
Hi

I have no idea how this happen but this is not an audio, this is a video

![image](https://user-images.githubusercontent.com/18009293/149221563-559ffd02-a3a4-4831-afae-e171ee21e3df.png)
