### ISSUE TITLE
Nginx.config  completely missing after last gitpull

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6165]
Did git pull and I got a fail testing live stat. Started nginx and got error that no such file existed.
Replaced Nginx.config with backup

**Comment by DanielnetoDotCom** [comment]
git pull does not replace or change the nginx.conf

something else may happen

**Comment by milehighkaraoke** [comment]
That's what I thought....
 Thanks for that conformation @DanielnetoDotCom
