### ISSUE TITLE
Dramatically increase responsiveness of site

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6166]
2 things 
1st
![20220112_050538](https://user-images.githubusercontent.com/70327833/149138797-eb509e13-c05b-41df-9a99-fb9fbc6175a0.jpg)

2nd
Put this at the top of your virtual host.......
![20220112_050829](https://user-images.githubusercontent.com/70327833/149138696-5228bbb8-a965-449c-a83c-11245435515a.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, 

Thanks for your suggestion but I am lost. I have never seen this before.

what it does exactly?

**Comment by milehighkaraoke** [comment]
Bottleneck bandwidth control 
https://www.linuxbabe.com/ubuntu/enable-google-tcp-bbr-ubuntu

**Comment by milehighkaraoke** [comment]
The apache configuration speed up my login and redirect tremendously....

**Comment by DanielnetoDotCom** [comment]
That is awesome. I also recommend you to check this ...

https://github.com/WWBN/AVideo/wiki/Speed-up-your-page#apache2buddy

**Comment by jengajenga** [comment]
> 

the second image isn't clear.

what exactly are we putting in the virtual host?

**Comment by JoshWho** [comment]
> Bottleneck bandwidth control https://www.linuxbabe.com/ubuntu/enable-google-tcp-bbr-ubuntu

Tested and it fully works. Wow what a difference.

**Comment by JoshWho** [comment]
I am actually quite impressed with this improvement with the TFTTFB    there is now zero latency when a client request gets made.

**Comment by JoshWho** [comment]
> > 
> 
> the second image isn't clear.
> 
> what exactly are we putting in the virtual host?

I am am making out of the second image is this bypassing dns for the virtual host. I wouldn't recommend it for a normal site on the clearnet but good for local apps
