### ISSUE TITLE
Roku Feeds are breaking

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6169]
Couldn't find my channel any more on ROku and looked this is what it is showing

![97e41037-d20e-4986-b5f7-fbdcd9b6267c](https://user-images.githubusercontent.com/39392449/149252986-a6918f42-0a96-45fa-b331-9ac953f02ef5.png)

Feeds keep taking to long to load

This is my feed address https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json

**Comment by JoshWho** [comment]
There needs to be a way to cache this feed

**Comment by DanielnetoDotCom** [comment]
the feeds are cached

Before send it to Roku try to directly access the https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json first

**Comment by JoshWho** [comment]
Every time I click refresh I get a different result

![a4437b01-c6bf-4a71-bbb6-5998e8dfa96c](https://user-images.githubusercontent.com/39392449/149321332-f5d81a2e-0d2b-4453-b9d1-4e54cc939ed7.png)

**Comment by JoshWho** [comment]
Maybe we need to limit how many are being listed in the feed.

**Comment by JoshWho** [comment]
![6058ea6c-e793-428a-8008-4ce2015c3c4a](https://user-images.githubusercontent.com/39392449/149336597-a048ceda-9a53-49a6-8719-2d1f83613990.png)

**Comment by DanielnetoDotCom** [comment]
You probably can do this https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=10

this will limit to 10 results, you can change rowCount to whatever you want.

any idea if the error is due to a script timeout on your side or Roku side??

if it is on your side I probably can increase that

**Comment by JoshWho** [comment]
That did the job. Maybe there is a way to make it compressed like zip or gzip in future but this works perfect for now. Thank you https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100
