### ISSUE TITLE
Search My Videos Is Horrible And Useless Since Last Update

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#6170]
The search through "My Videos" used to be quite awesome until the last update. Now it is useless and not even really working.

Before the update, the more words I entered, the more refined the results. Now, the more words I enter, I get ever more useless results. It is like each keyword is being used as a separate search function, giving you a mess of results.

In this example, I do not even get what I am looking for at all. Rather I get a random mess of 6 pages of unrelated results from one keyword search "Ethereum"

![search-not-working](https://user-images.githubusercontent.com/45924889/149321300-3a983a20-45c9-4060-aba9-aca62eff7985.jpg)

**Comment by The-Do-It-Yourself-World** [comment]
Another example "clean ford carburetor" seems to bring up search results from each word separately instead of as a single keyword.

![search-results-bad](https://user-images.githubusercontent.com/45924889/149321895-f3415047-bc5f-4f19-9f82-d3e2bcaba948.jpg)

Here I get 18 pages with 173 results total and I know for a fact that there is only one video about cleaning a ford carburetor on my site.

![bad-search-results](https://user-images.githubusercontent.com/45924889/149322219-61b631d7-00fd-4f82-8ef6-84de25f21e78.jpg)

**Comment by The-Do-It-Yourself-World** [comment]
Notice above you see results using the word "clean" are showing up as well as all results from "ford" and all results from "carburetor".

In the past the search results only showed videos with all three keywords in the title. That is what I need. It is taking me hours each day now to go through videos rather than literally seconds before.

**Comment by DanielnetoDotCom** [comment]
I just add some search options on videos manager

![chrome-capture (5)](https://user-images.githubusercontent.com/18009293/149353263-ce18402f-0857-42e2-9184-ba04382df74e.gif)

**Comment by The-Do-It-Yourself-World** [comment]
I still get 134 results from searching for "Ford 8N Carburetor" which returned 1 single result before the updates. I loved the search before.

Now the search function is looking at ANY matching keyword and not ALL matching keywords in the title.

Now I get all results using the word "Ford".
All results with "8N"
All results with "Carburetor"

I am looking for one single video with a matching title like it used to be. Before if I refined the search with more words, it reduced results. Now it increases results.

**Comment by DanielnetoDotCom** [comment]
Did you update and select only the title on the search fields?

make sure you add "Ford 8N Carburetor" into quotes

**Comment by The-Do-It-Yourself-World** [comment]
Quotes work. Thank you.
