### ISSUE TITLE
Chat2 Plugin not loading New Message automatic

### ISSUE THREAD

**Issue by xXSandro1994Xx** [WWBN/AVideo#6171]
**Describe the bug**

When I write a message in the chat, the other people can't see my message. (screenshot 1)
When the other People reload the website or click on avatar picture  load (screenshot 2 and 3) the message and he can see my messagem
but it dosn't load automatically

I have uploaded a screenshot:
![1](https://user-images.githubusercontent.com/84159223/149334045-4a722360-e530-4a9f-8b13-41d2fb219771.png)
![2](https://user-images.githubusercontent.com/84159223/149334051-f86c7dc1-fc81-4dfe-b412-2b5571708d99.png)
![3](https://user-images.githubusercontent.com/84159223/149334056-91add316-a4c1-4581-9189-794aead572d2.png)

Server:
OS: Turnkey Container (Proxmox) 

Client:
**Desktop 
 - OS: Windows 10
 - Browser: Firefox Version 95.0.2 (64-Bit) and Chrome Version 97.0.4692.71 (Offizieller Build) (64-Bit) 
 - Version: AVideo Version 11.5!

**Comment by DanielnetoDotCom** [comment]
Is your socket plugin enabled and running?

https://github.com/WWBN/AVideo/wiki/Socket-Plugin

**Comment by xXSandro1994Xx** [comment]
I deactivated web socket and now it works.

will there still be a fix that it works with the websocket?

**Comment by DanielnetoDotCom** [comment]
the socket is strongly recommended for the chat. without it, you will not be able to handle many users.

I suspect your socket is not working properly

can you please screenshot the socket panel?
![image](https://user-images.githubusercontent.com/18009293/149345334-f30c2b5d-7122-4271-835d-3689c2bbe29a.png)

**Comment by xXSandro1994Xx** [comment]
oh i think the problem is with ssl because i use a nginx proxy server  before the apache
my port 443 and 80 is open to an other lxc container than came the avideo lxc container after the nginx proxy server

![4](https://user-images.githubusercontent.com/84159223/149347719-b4d7bda8-68a8-433d-a587-dd7e96cfc3b6.png)

**Comment by DanielnetoDotCom** [comment]
yes, this may be a problem. for myself I use letsencrypt to deploy the SSL, I am not sure how you can resolve that on your side.

**Comment by xXSandro1994Xx** [comment]
i use letsencrypt  too.

my frontemd server is hestia cp installed and has a letsencryp certifikat an may backend server has the letsencrypt certfikat from frondend (manuel installed)

**Comment by xXSandro1994Xx** [comment]
can show me a example nginx.conf from you?

**Comment by xXSandro1994Xx** [comment]
now i have a  new error 

![7](https://user-images.githubusercontent.com/84159223/149384037-db2d984b-6e1f-4bd7-b54f-086ac1aa91d1.png)

**Comment by DanielnetoDotCom** [comment]
Sorry I do not know anything about "hestia cp"

**Comment by xXSandro1994Xx** [comment]
ok so i have now created a certificate via letsencrypt via the avido lxc container

but he does not load the certificate

**Comment by DanielnetoDotCom** [comment]
yes, that may work. just make sure your certificate will update before expires
