### ISSUE TITLE
Installed SSL on Encoder and Now Its Broken Tried A New VM And Its Frozen

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#6172]
So, after having a nice working encoder for a while, I finally installed Lets Encrypt SSL. Now I cannot upload a local file anymore. I get this odd error:

![encoderbroken](https://user-images.githubusercontent.com/45924889/149389072-479d44be-6f78-4acb-acb6-2cc694e7ec4c.jpg)

So I started a brand new server and installed the software. First of all, I think there is an error on the instructions page:

![install-encoder](https://user-images.githubusercontent.com/45924889/149389296-c8665e92-2b86-4115-8079-1cfe98a7d03b.jpg)

After half an hour of work, I found myself on the streamer site and NOT the encoder. So I started over again.

Now that is just stuck on "Processing" over and over and over again. I have tried dropping the database. I tried manually installing the database in mysql and then just installing tables. No go. No matter what I try. It just gets stuck on "Processing".

**Comment by The-Do-It-Yourself-World** [comment]
Ok. Now I am having a bad day. On the new encoder VM I created another brand new user and granted privileges. Then logged into that user and created a new database. Went back to the setup page and tried again. Frozen at "processing".

**Comment by The-Do-It-Yourself-World** [comment]
I started a whole new server and installed everything again. Once more stuck on processing. What am I missing?

**Comment by jengajenga** [comment]
Do you have all the required extensions of php and apache2?

**Comment by The-Do-It-Yourself-World** [comment]
I am using the instructions from the link I shared.

**Comment by The-Do-It-Yourself-World** [comment]
I installed Ubuntu 18.04 and installed all upgrades and updates. Then copied the commands from the instructions. First I tried them all at once. Then I tried one by one. Then I tried them all again.

I have made sure I have a mysql user and database set up manually. All privileges granted to the user. I tried installing database and tables and also only tables.

Always freezes at "Processing".

I have tried 3 VMs and about 3x on each VM in the past 24 hours.

My biggest two questions are these. 1. Why is the encoder site erroring out on a remote website in the first place?
2. are the instructions not in error for just installing the encoder? Is there another set of instructions for just the encoder that I am not finding?

**Comment by The-Do-It-Yourself-World** [comment]
I started a new server. Installed updates and upgrades. Followed these instructions precisely: https://github.com/WWBN/AVideo-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x---For-AVideo-Encoder

Hangs on "Processing".

No error logs. No feedback. Nothing. How can I figure out what is failing if there are no log files created for me to look at?

I can get the streamer to work every time. But the encoder is failing on me. What am I missing?

**Comment by The-Do-It-Yourself-World** [comment]
So, I exported the database from my broken encoder server and manually imported it into my new encoder server. I copied the config file and edited the root url. Works perfect. I cannot figure out why the script could not do this. I tried everything I could think of.

Next I will install SSL and see if I can get the same error as last time.

**Comment by DanielnetoDotCom** [comment]
in what part exactly is hanging?

check the apache log file

**Comment by The-Do-It-Yourself-World** [comment]
Kept getting the following:

PHP Warning:  require_once(/var/www/..../..../view/../videos/configuration.php): failed to open stream: No such file or directory in /var/www/..../..../view/index.php on line 18

PHP Fatal error:  require_once(): Failed opening required '/var/www/.../.../view/../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/.../.../view/index.php on line 18

And this one:

PHP Warning:  mkdir(): Permission denied in /var/www/.../.../objects/functions.php on line 270

Which is strange because I had to create the /videos directly and set up the permissions according to instructions on the install page itself on the encoder site.

When I manually uploaded a config file and the database myself, it ran perfect.

Permissions on the /videos folder are www-data:www-data

**Comment by The-Do-It-Yourself-World** [comment]
I just started a brand new server. Followed the instructions here: https://github.com/WWBN/AVideo-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x---For-AVideo-Encoder

I should mention there were some apache errors. The instructions for rewrite modules is missing from this page.

And I got the same errors as before. Exact same errors.

**Comment by The-Do-It-Yourself-World** [comment]
Same thing. Manually copied the config file into /videos folder and manually imported a working database. Works perfect now.

But why is it hanging on the install program?

**Comment by The-Do-It-Yourself-World** [comment]
A person attempting to upload a video on the brand new encoder got this error:

<img width="640" alt="upload error jpg" src="https://user-images.githubusercontent.com/45924889/149627001-ac3d9f70-8742-4bab-834a-9ef34647e21e.png">

Why are we being sent to a third party website and why are we getting errors on there?

**Comment by DanielnetoDotCom** [comment]
Check if the configuration.php file exists

also, check what is the value of the variable (inside configuration.php)

$global['systemRootPath'] = '/path/to/avideo/';

**Comment by The-Do-It-Yourself-World** [comment]
I myself uploaded the configuration file as I said earlier. I manually had to import a working database as well. The path is good. The config file is from a working encoder I had (I edited the path to fit this server). For me this new encoder is working as it should. But some people can only copy a link from YouTube or another site but not upload a local file.

This is the same thing that happened to my old encoder when I installed the SSL which caused me to start this thread. But I have NOT installed SSL yet on the other two encoders I just made for testing.

The new encoders work for me but not for some people. It does not make sense at all.

I now have three encoders.

1. My original one was working perfect for months until I installed SSL. Now I cannot upload a local file but I can copy links from other sites just fine.
2. My second encoder I made for testing purposes since opening this thread. The installation fails every single time. It took me ten attempts on three servers to get one that worked and only when I manually set up a configuration file and imported a database myself.
3. My third encoder I made for testing purposes yesterday. Again the installation hung as always and stuck on "Processing" so I manually uploaded a configuration file and imported a database.

Number 1, my original encoder will not upload local files for anyone.
Number 2, my test encoder works for me but other people cannot upload local files. This one has NO SSL yet.

**Comment by DanielnetoDotCom** [comment]
Sorry, I am confused about what is working and what is not. 

you should open one issue for each problem/encoder.

**Comment by The-Do-It-Yourself-World** [comment]
Ok, here is one issue. My encoder worked fine for months. I installed an SSL and now nobody can upload local files anymore. Copy from YT and other sites works. But local files fail.

This error comes up:

<img width="640" alt="upload error jpg" src="https://user-images.githubusercontent.com/45924889/149630038-cce01a32-a162-49ba-97c6-9959616b9250.png">

**Comment by DanielnetoDotCom** [comment]
Hi, I do not know about the appspot.com file

how did you add the SSL? letsencrypt?

**Comment by The-Do-It-Yourself-World** [comment]
LetsEncrypt. I have used it for years on many many sites.

Your software takes us out to third party sites. I have seen this before through the years. I think its one of the Jquery files.

**Comment by The-Do-It-Yourself-World** [comment]
I found this on /view/jquery-file-upload/form.php

<form id="fileupload" action="https://jquery-file-upload.appspot.com/" method="POST" enctype="multipart/form-data">

This is in your code. It is sending us to a third party site and there is where I am seeing the failure.

**Comment by DanielnetoDotCom** [comment]
that means your JS is not loading correctly.

when you open the encoder page, check the JS console logs

**Comment by The-Do-It-Yourself-World** [comment]
I am sorry but where can I find the JS console logs?

**Comment by The-Do-It-Yourself-World** [comment]
Thanks. That did it. I forgot to edit the conf file to point to https.
