### ISSUE TITLE
Youth Protection Rating for Livestream

### ISSUE THREAD

**Issue by xXSandro1994Xx** [WWBN/AVideo#6173]
Would it be possible to make a youth protection rating for live streamings with a pop-up message?

**Comment by DanielnetoDotCom** [comment]
Is the "Youth Protection Rating" the same as rrating??


https://github.com/WWBN/AVideo/blob/072c6f2d1bb942518154ae24ad931a3520bec589/objects/video.php#L97

**Comment by xXSandro1994Xx** [comment]
yes but it cannot be selected on the live stream page

and we have other youth protection in germany
it would be good if you can change the texts in the admin panel

instead by sftp
