### ISSUE TITLE
black frame

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6174]
Hi Daniel, 
how or which file to change so that these black background lines are not visible. 
How to increase video size 
![ramki1](https://user-images.githubusercontent.com/93145787/149498853-f9eb1550-fce6-4114-a33a-8fc3ba74eadb.png)
![ramki2](https://user-images.githubusercontent.com/93145787/149498878-580aa3b5-2859-4a70-89f4-a43fe8fa150f.png)

**Comment by KrzysioMisio** [comment]
I already found it
in the file -> plugin/PlayerSkins/PlayerSkins.php
I added styles 
padding-left:0 padding-right:0;

**Comment by jengajenga** [comment]
> I already found it in the file -> plugin/PlayerSkins/PlayerSkins.php I added styles padding-left:0 padding-right:0; now it is without frames https://www.youhippo.com/video/34/sova---moja-spowiedz

Thanks. This really helped me.

**Comment by KrzysioMisio** [comment]
my modification from line 176:
`        $col1Classes = 'col-md-2 firstC';
        $col2Classes = 'col-md-8 secC';
        $col3Classes = 'col-md-2 thirdC';
	$col2Style = 'padding-left:0 !important; padding-right:0 !important;';

        if ($obj->playerFullHeight) {
            $col2Classes .= ' text-center playerFullHeight';
        }

        $html .= '
<div class="row main-video" id="mvideo">
    <div class="' . $col1Classes . '"></div>
    <div style="' . $col2Style . '" class="' . $col2Classes . '">
        <div id="videoContainer">
            <div id="floatButtons" style="display: none;">
                <p class="btn btn-outline btn-xs move">
                    <i class="fas fa-expand-arrows-alt"></i>
                </p>
                <button type="button" class="btn btn-outline btn-xs" onclick="closeFloatVideo(); floatClosed = 1;">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div id="main-video" class="embed-responsive embed-responsive-16by9">' . $htmlMediaTag . '</div>';`

**Comment by KrzysioMisio** [comment]
my modification from line 176:

`        $col1Classes = 'col-md-2 firstC';
        $col2Classes = 'col-md-8 secC';
        $col3Classes = 'col-md-2 thirdC';
			$col2Style = 'padding-left:0 !important; padding-right:0 !important;';

        if ($obj->playerFullHeight) {
            $col2Classes .= ' text-center playerFullHeight';
        }

        $html .= '
<div class="row main-video" id="mvideo">
    <div class="' . $col1Classes . '"></div>
    <div style="' . $col2Style . '" class="' . $col2Classes . '">
        <div id="videoContainer">
            <div id="floatButtons" style="display: none;">
                <p class="btn btn-outline btn-xs move">
                    <i class="fas fa-expand-arrows-alt"></i>
                </p>
                <button type="button" class="btn btn-outline btn-xs" onclick="closeFloatVideo(); floatClosed = 1;">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            <div id="main-video" class="embed-responsive embed-responsive-16by9">' . $htmlMediaTag . '</div>';`

**Comment by KrzysioMisio** [comment]
my modification from line 176:

`        $col1Classes = 'col-md-2 firstC';
        $col2Classes = 'col-md-8 secC';
        $col3Classes = 'col-md-2 thirdC';
	$col2Style = 'padding-left:0 !important; padding-right:0 !important;';`

line 189

`<div style="' . $col2Style . '" class="' . $col2Classes . '">`

**Comment by DanielnetoDotCom** [comment]
I do not recommend you to modify the core code

you can add some custom css on your site configuration menu

**Comment by KrzysioMisio** [comment]
yes, but you still need to modify the PlayerSkins.php file to add a new class
Because the col-md-8 class occurs 169 times in 64 files

**Comment by DanielnetoDotCom** [comment]
Again, you should not change the main code, but you should use a custom CSS, I am sure you can find a specific selector to change what ever you want

**Comment by KrzysioMisio** [comment]
OK I understand  :-)

**Comment by KrzysioMisio** [comment]
update
css code:
#modeYoutubeTop #mvideo .secC {
padding-left: 0! important; padding-right: 0! important;
}
add e.g. to a file: view/css/main.css

**Comment by DanielnetoDotCom** [comment]
The CSS looks good to me, but you should update it on the site configuration menu, NOT on the file.

check this 

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript

**Comment by KrzysioMisio** [comment]
I didn't even know that   :-)
code is added in tags ?? e.g. <style>
or the code itself ?

**Comment by DanielnetoDotCom** [comment]
code is added in tag  <style>

**Comment by KrzysioMisio** [comment]
OK thanks
