### ISSUE TITLE
Live Plugin Not working and Live Users on Live not working after renewing SSL

### ISSUE THREAD

**Issue by Yoxed** [WWBN/AVideo#6175]
Live Plugin Not working and Live Users on Live not working after renewing SSL

This stays empty when i click on broadcast a livestream
![Screenshot_81](https://user-images.githubusercontent.com/30751181/149560078-99917bbe-eeb1-4231-b2ec-71d15db45819.png)

The users won't show up, socket keeps loading
![Screenshot_82](https://user-images.githubusercontent.com/30751181/149560260-36c1d23c-e2e6-43bc-80e5-b632cfd49cdb.png)

The Socket Works fine on Main Page

**Comment by DanielnetoDotCom** [comment]
try to restart nginx with 

`/usr/local/nginx/sbin/nginx - stop`

than 

`/usr/local/nginx/sbin/nginx`

also stop and start the socket 

`php /var/www/html/AVideo/plugin/YPTSocket/stop.php`

than

`php /var/www/html/AVideo/plugin/YPTSocket/server.php`

**Comment by Yoxed** [comment]
My website randomly broke when i came back to use it, I left with it functioning properly 

![Screenshot_83](https://user-images.githubusercontent.com/30751181/149758884-1d98ae07-4408-4b68-b3c2-ea8e8e9cdaa2.png)

**Comment by DanielnetoDotCom** [comment]
I noticed your CDN had no balance. and it was deleted some time ago.

add this variable on your configuration.php and delete your cache folder.

`$global['ignoreCDN'] = 1;`

when your site is back disable the CDN plugin or add some credit and rebuild it

**Comment by Yoxed** [comment]
Okay

**Comment by Yoxed** [comment]
Is this correct? I tried enabling the CDN again but It just ended up breaking the site again and now this code will not work anymore.. 
![Screenshot_2](https://user-images.githubusercontent.com/30751181/152449647-aede60ff-d13a-4fef-af47-737dfee2d31d.png)

**Comment by Yoxed** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/30751181/152449685-aa3bacad-5237-443a-99ba-4bd5b843dbed.png)

**Comment by Yoxed** [comment]
How will I update this Plugin? I already git pull and the site is up to date

![Screenshot_4](https://user-images.githubusercontent.com/30751181/152452142-0f02a7f6-5c23-4440-b510-a9f80e004d20.png)

**Comment by DanielnetoDotCom** [comment]
to stop the socket run

`php /var/www/html/AVideo/plugin/YPTSocket/stopServer.php`

to start again run

`sudo nohup php /var/www/html/AVideo/plugin/YPTSocket/server.php &`

**Comment by Yoxed** [comment]
I was still unable to fix my Live Broadcast Problem, I do not see the configuration. I updated to 11.6 and still nothing.  and my socket is connected but I still do not see live users, it just keeps buffering in a circle on the live.

This is my log
![Screenshot_12](https://user-images.githubusercontent.com/30751181/156168629-e58e2fd4-c575-4ace-aaac-d35321b9671f.png)

**Comment by DanielnetoDotCom** [comment]
there is no error in your log.

Is this your site?

it seems to be working pretty good for me

![image](https://user-images.githubusercontent.com/18009293/156169383-6ff39304-3f8b-456c-86d0-e54bea5c9097.png)

**Comment by Yoxed** [comment]
Yes, check the edit I made please.

**Comment by DanielnetoDotCom** [comment]
I see now, you are talking about the socket.

try this https://github.com/WWBN/AVideo/wiki/Socket-Plugin#troubleshooting

**Comment by DanielnetoDotCom** [comment]
this is your live page


![image](https://user-images.githubusercontent.com/18009293/156169943-89f27ebb-53a3-44d2-b413-99ba50e52ec6.png)

looks like there is an error on the redirection, probably something on the SSL configuration.

first, make a git pull and make sure your plugins are also up to date.

those types of errors you will not find on avideo.log, they happen on apache, before accessing the AVideo software.

**Comment by Yoxed** [comment]
This is what i get


![Screenshot_16](https://user-images.githubusercontent.com/30751181/156170127-e226d79e-9376-4c3f-b134-aeb889fae388.png)

**Comment by DanielnetoDotCom** [comment]
> This is what i get
> 
> ![Screenshot_16](https://user-images.githubusercontent.com/30751181/156170127-e226d79e-9376-4c3f-b134-aeb889fae388.png)

you MUST follow all the instructions I sent to you

**Comment by DanielnetoDotCom** [comment]
Also I found this 

![image](https://user-images.githubusercontent.com/18009293/156170437-02fbdb29-a0b0-4e96-869f-00de6d04a5f6.png)

**Comment by DanielnetoDotCom** [comment]
Are you using a reverse proxy?

**Comment by Yoxed** [comment]
No I am not. I think it might be my www.realmediatt.com and not realmediatt.com Also the troubleshooting it still in progress. I will give an update.

**Comment by DanielnetoDotCom** [comment]
be careful www.realmediatt.com and realmediatt.com are 2 different sites

I recommend you to direct all requests to  www.realmediatt.com to realmediatt.com, but do it on your DNS configuration

then focus only on realmediatt.com to deploy certificates, etc, DO NOT mix www and non www
