### ISSUE TITLE
WebRTC Server Could not open input file

### ISSUE THREAD

**Issue by xXSandro1994Xx** [WWBN/AVideo#6176]
when I try to start the WebRTC server I always get an error message.

and the file to start is not in the standalone folder either

```
root@AVideo ~# sudo php /var/www/avideo/plugin/Live/standAloneFiles/WebRTCServer/server.php
Could not open input file: /var/www/avideo/plugin/Live/standAloneFiles/WebRTCServer/server.php

```

**Comment by DanielnetoDotCom** [comment]
Hi

Sorry, but currently the self-hosted WebRTC Server is not working properly

if may be fixed or removed in the future

**Comment by xXSandro1994Xx** [comment]
ok and is there another way to stream via the website?

**Comment by DanielnetoDotCom** [comment]
You can use the meet of the public webrtc server (beta).

**Comment by xXSandro1994Xx** [comment]
Yes But i can‘t See the chat There in the Same tab

**Comment by DanielnetoDotCom** [comment]
sorry, it is not clear to me.

can you please screenshot what do you mean?

**Comment by xXSandro1994Xx** [comment]
Ehen guest Write in the Chat on my Site i can‘t See it in Meet because it is Not the Same Chat service

**Comment by xXSandro1994Xx** [comment]
I'll look for a web broadcast client to work around the problem

**Comment by JoshWho** [comment]
He wants to see the Chat that people see on the Live Stream Watch Page viewable in the Jitsi Meeting. Only thing that does that at the moment is the Go Live from webcam function

![7dd858c7-b6df-4410-995b-2e126e46bda7](https://user-images.githubusercontent.com/39392449/150624536-ca3aa814-2b82-4338-a6b7-a6c04411b46f.png)
