### ISSUE TITLE
INVALID CAPTCHA on Upload

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6178]
![c2f0047a-394c-4d78-8957-a46b34d40b83](https://user-images.githubusercontent.com/39392449/149610781-1468ca8a-ca26-4f0e-b8af-487284aab428.png)

There is no captcha to fill out

**Comment by JoshWho** [comment]
For some reason If i manually go to the encoders main url it lets me log in but it isn;t from the upload button on the site

**Comment by JoshWho** [comment]
pretty sure this is the auto login that is messing up.

**Comment by DanielnetoDotCom** [comment]
the captcha is required after subsequent logins attempts

try to clear the cookies and try again.

anyway, next week I will review it to see what I can do to avoid this problem on the encoder login

**Comment by JoshWho** [comment]
Everyone on my site is having this issue

**Comment by DanielnetoDotCom** [comment]
set CustomizeUser->requestCaptchaAfterLoginsAttempts = 0

or increase it

![image](https://user-images.githubusercontent.com/18009293/149628448-fc778c68-4e11-4b97-9e87-c8c3befd6891.png)

**Comment by JoshWho** [comment]
> set CustomizeUser->requestCaptchaAfterLoginsAttempts = 0
> 
> or increase it
> 
> ![image](https://user-images.githubusercontent.com/18009293/149628448-fc778c68-4e11-4b97-9e87-c8c3befd6891.png)

will give this a try

**Comment by JoshWho** [comment]
That did the trick. I have it set to zero

Thank you @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
what was the value before you change it?

**Comment by JoshWho** [comment]
> what was the value before you change it?

It was on 4
