### ISSUE TITLE
Missing cast function for live stream

### ISSUE THREAD

**Issue by PrXenon** [WWBN/AVideo#6179]
**Describe the bug**
Since a few updates, I no longer have a cast function for live streams.

**To Reproduce**
1. Start a livestream
2. try to connect to a Chromecast device (edit)

**Desktop (please complete the following information):**
 - OS: Windows 10 / 11
 - all

**Smartphone (please complete the following information):**
 - Device: Android Samsung Note
 - OS: Android 10/11
 - Browser all

**Additional context**
For all recorded or uploaded Videos.. i see the cast icon.

Thanks

**Comment by DanielnetoDotCom** [comment]
what exactly is the cast feature? is the chromecast?

I may need to review it for livestream

**Comment by PrXenon** [comment]
> what exactly is the cast feature? is the chromecast?
> 
> I may need to review it for livestream

Yes Cast feature = Chromecast  :-)
