### ISSUE TITLE
Cannot Upload Local File On Encoder Site Get File Too Large Error

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#6181]
I have a brand new encoder site.

For me it is working perfect. But some people cannot upload a local file. Not once. They can copy from YT or other sites.

But every single time when trying to upload a local file this error comes up - 413 file too large.

Here is the error page:

<img width="640" alt="upload error jpg" src="https://user-images.githubusercontent.com/45924889/149630881-21d11eeb-479a-4cb2-81c3-d921e67b6cd9.png">

**Comment by The-Do-It-Yourself-World** [comment]
I found this on Encoder/view/jquery-file-upload/form.php line 1 of the code

form id="fileupload" action="https://jquery-file-upload.appspot.com/" method="POST" enctype="multipart/form-data"

This is in your code. It is sending us to a third party site and there is where I am seeing the failure.

**Comment by The-Do-It-Yourself-World** [comment]
From line 75 of the same file I find:

input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"

Which is related to the first site.

**Comment by JoshWho** [comment]
It includes files from the project it is not redirecting you. This is the project https://github.com/blueimp/jQuery-File-Upload

**Comment by The-Do-It-Yourself-World** [comment]
Look at the error I am getting though. This is where I end up. On that page.

**Comment by JoshWho** [comment]
Do u have any security like Modsecurity enabled ?

**Comment by JoshWho** [comment]
Is this server connected to the internet?

**Comment by JoshWho** [comment]
what is your sites URL so we can see what is going on

**Comment by The-Do-It-Yourself-World** [comment]
Yes the server is live and connected to the internet. I have fail2ban but not modsecurity. 

Here is the link: http://144.202.60.39/DIYTube-Encoder

**Comment by JoshWho** [comment]
I just uploaded using that encoder. Is there anything specific to make the error happen?

**Comment by The-Do-It-Yourself-World** [comment]
Upload a local file. I dont know what is going on. It works for me but not some other people. I have someone trying again now and he cannot upload from local but from another site it works for him.

**Comment by The-Do-It-Yourself-World** [comment]
You must be joshtest?

**Comment by JoshWho** [comment]
Yup

**Comment by The-Do-It-Yourself-World** [comment]
I dont get it. I cannot recreate the error myself but my friend gets the error every single time.

**Comment by JoshWho** [comment]
Maybe he is having dns cache issues

**Comment by The-Do-It-Yourself-World** [comment]
I am starting to think the same thing since we was using the old encoder before. I am going to close this now because I have him working on the old encoder anyway. Thanks for the help.
