### ISSUE TITLE
Audio Files No Longer Play Since Last Updates

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#6182]
Audio files no longer play since the last update. Someone just uploaded a brand new audio file. The page opens, but nothing really happens when you click play.

Same goes for literally every audio file on my entire site.

Here is the newest one for an example:

https://diytube.video/v/39329

**Comment by DanielnetoDotCom** [comment]
This is a dummy file https://diytube.video/videos/audio_220115165030_v334e/audio_220115165030_v334e.mp3

what type of storage are you using?

check if the file is on your storage and also check if your "Storage plugin" is up to date

**Comment by The-Do-It-Yourself-World** [comment]
I am using Wasabi with the AWS_S3 plugin. The audio files worked before the updates tho. Everything on my site is fully updated now.

I do not have a "Storage" plugin

**Comment by DanielnetoDotCom** [comment]
Is your AWS_S3 up to date?

**Comment by The-Do-It-Yourself-World** [comment]
yes. Shows version 4.3 and no updates available.

I think what happened to the audio is the same as my video files. My guess anyway. When the file system changed, I lost my audio files.

**Comment by DanielnetoDotCom** [comment]
really strange, try to clear the cache and see if it will get the correct path.

I guess the MP3 file is on your S3 bucket and it is fine.

the video is pointing to your local storage instead of your bucket

**Comment by The-Do-It-Yourself-World** [comment]
Cache is cleared. All my browsers are giving me the same issue. I would very much prefer that everything went to Wasabi.

**Comment by DanielnetoDotCom** [comment]
Also make sure your xsendfile is installed https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

and check this ...

![chrome-capture (6)](https://user-images.githubusercontent.com/18009293/149641025-0bc5cb64-4c9c-41a0-9d0d-abdd3185a10a.gif)

**Comment by The-Do-It-Yourself-World** [comment]
All good now. Thank you.
