### ISSUE TITLE
my left hand menu is showing-"Unknown Menu name" how could i correct this please?

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#6183]
![image](https://user-images.githubusercontent.com/65802024/149678892-e48fc1c2-cd75-4c05-987a-731446a5a37a.png)

**Comment by DanielnetoDotCom** [comment]
Maybe you have a bugged topMenu item

check your plugin

**Comment by vraghavans** [comment]
okies got it ,thanks!
