### ISSUE TITLE
Docker Image within Release

### ISSUE THREAD

**Issue by trickert76** [WWBN/AVideo#6184]
I'm not really sure, why, but the Dockerfile is a little bit strange. I've tried to build an image from it.

First - I need to checkout the whole project, then run a `docker build` command. 
Then - the docker build process itself also checks out the repository. That doesn't make sence to me - especially because the repository is huge.

The given 11.1.1 artifact contains a completly different Dockerfile. It doesn't work, because it stops at

    chmod 777 /var/www/html/AVideo/objects/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer/

It stops with

    chmod: cannot access '/var/www/html/AVideo/objects/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer/': No such file or directory

This is true, because it is in vendor not in objects (we are talking here abotu a release. This should be fixed. Also this doesn't make sence, because I've tried to install 11.1.1. I've used the tar.gz. That also makes a git checkout. That will never result in a 11.1. installation, but a "latest". You should make a tag and switch to that tag.

**Comment by DanielnetoDotCom** [comment]
/var/www/html/AVideo/objects/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer/ does not exists anymore.

I am not a docker expert, all help on this feature may be welcome

**Comment by trickert76** [comment]
Fixed by #6185
