### ISSUE TITLE
There is no way to browse Articles

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#6188]
There is no link to browse Articles anywhere on the site. You can browse audio, by category, videos, by channel but not by Articles.

Here is a shot of my sidebar menu for example:

![no article view links](https://user-images.githubusercontent.com/45924889/149836496-09613698-d77b-42ba-9c21-17fac7c17c33.jpg)

**Comment by DanielnetoDotCom** [comment]
I understand now. I may add this in a future update

**Comment by The-Do-It-Yourself-World** [comment]
Where would I have to go in the code to fix this myself? Or is it not a simple fix?

**Comment by DanielnetoDotCom** [comment]
This is not simple and it is not a fix

we never had a article search , this will be a new feature

**Comment by The-Do-It-Yourself-World** [comment]
Ok, thanks. I guess I will close this.
