### ISSUE TITLE
Using of https://tutorialsavideo.b-cdn.net/version

### ISSUE THREAD

**Issue by friedrichengel** [WWBN/AVideo#6191]
**Describe the bug**
In the error log there is one entry each day that trys to reach https://tutorialsavideo.b-cdn.net/version but the site is not working saying "Domain suspended or not configured".

Is used in https://github.com/WWBN/AVideo/blob/master/objects/functions.php in  "thereIsAnyRemoteUpdate()". So i suppose update checking is not working.

**To Reproduce**
Try to open the URL in Webbrowser.

**Comment by DanielnetoDotCom** [comment]
Thanks for noticing that. here is an update to fix it.
