### ISSUE TITLE
Unable to Log in tutorial site 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6192]
Trying to download my plugins but the tutorial site will not log in

**Comment by DanielnetoDotCom** [comment]
I just checked and it is fine here.

are you using a tutorial site user or a Facebook or Google user?

did you try to recover the password on the tutorials site?

**Comment by milehighkaraoke** [comment]
Seems it was all on this end... Low batteries in the keyboard...  thank you
