### ISSUE TITLE
On publish done not stopping.  

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6193]
![16425163543362569619432285911344](https://user-images.githubusercontent.com/70327833/149957219-6c33f829-e25f-4ab2-b9fa-676529bcc57d.jpg)
@DanielnetoDotCom  
Nginx are all #
![16425164609505595579442765452417](https://user-images.githubusercontent.com/70327833/149957477-9c609589-a58c-4e22-afe6-95123786710e.jpg)
 pointing at my localhost  I can view the broadcast,  broadcast shows up as live on the live ticker, green online in video window but when I stop broadcasting it does not unpublish......

**Comment by DanielnetoDotCom** [comment]
do you have the socket running?

try to clear the cache to see if disappear

check your log file

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom #
![20220118_181259](https://user-images.githubusercontent.com/70327833/150044934-cb1ecce0-77f6-409c-a242-884daabe9687.jpg)
Is this what the link is supposed to produce?

**Comment by milehighkaraoke** [comment]
Socket is running

**Comment by milehighkaraoke** [comment]
It finds it if I put the address in like this 
@DanielnetoDotCom 
![16425551294372475644069565015155](https://user-images.githubusercontent.com/70327833/150045539-45ffcf67-cb20-4d29-ab30-d01181f47104.jpg)

**Comment by milehighkaraoke** [comment]
[18-Jan-2022 18:24:15 America/Denver] AVideoLog::SECURITY: NGINX ON Publish denied {"error":true,"liveTransmitionHistory_id":0} SCRIPT_NAME: /plugin/Live/on_publish.php

**Comment by milehighkaraoke** [comment]
I have it like this
![16425558741745424792405916216311](https://user-images.githubusercontent.com/70327833/150046657-f532091b-730a-4c8c-a14a-67911e1696fd.jpg)

**Comment by milehighkaraoke** [comment]
It connects  but it does not show up on the site as live

**Comment by milehighkaraoke** [comment]
Uploading 20220118_183307.mp4…

**Comment by milehighkaraoke** [comment]
![16425560250528117664172046913430](https://user-images.githubusercontent.com/70327833/150046862-92089a1b-a720-4065-85f5-c3d3b07144bb.jpg)

**Comment by milehighkaraoke** [comment]
What on earth am I missing?

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom 
Do I need a different path if I am trying to come in from http://localhost

**Comment by milehighkaraoke** [comment]
My ip brings up my mhkaraoke.com vhost  how do I change it to point to my mhktube vhost?  Any help would be greatly appreciated...

**Comment by milehighkaraoke** [comment]
Ok I got the Localhost fixed  @DanielnetoDotCom 
![20220119_152510](https://user-images.githubusercontent.com/70327833/150227153-1c3b0ef4-0a1f-4311-8e72-3d0729dc7b32.jpg)

**Comment by milehighkaraoke** [comment]
Now it Published live
But it still does not  on Publish Done as you can see here the live is still live after broadcast is off.  Cleared Cache and still it shows live I also tried my IP addresse of my server instead of localhost and it is doing the same thing....
Any Idea 
![20220119_152531](https://user-images.githubusercontent.com/70327833/150228940-10519e96-3b00-4ba1-83f0-fee9b6b18a3c.jpg)
![20220119_152526](https://user-images.githubusercontent.com/70327833/150228986-12f1aaa0-acf6-4f12-aed8-2063648377df.jpg)

**Comment by DanielnetoDotCom** [comment]
Can you please make sure your live plugin is the latest and have all the tables installed?

also please click here and try again...

![image](https://user-images.githubusercontent.com/18009293/150233437-01249351-7c80-4b9f-9fe3-70df917c6174.png)

**Comment by milehighkaraoke** [comment]
Did above steps and it's still showing a broadcast I stopped over 2 hrs ago 

![20220119_161842](https://user-images.githubusercontent.com/70327833/150233926-6b0e1c7a-9295-428f-bf69-8555e786c486.jpg)
![20220119_161826](https://user-images.githubusercontent.com/70327833/150233927-6938263f-ada5-41db-b2a8-b8a52ce520ee.jpg)
![20220119_161820](https://user-images.githubusercontent.com/70327833/150233928-fbed8fb2-41b5-4540-8214-ac0faa41d408.jpg)
![20220119_161546](https://user-images.githubusercontent.com/70327833/150233930-c5a87f59-9a14-43c3-a551-bc79a2cbbda8.jpg)

**Comment by milehighkaraoke** [comment]
Nothing in the log

**Comment by DanielnetoDotCom** [comment]
if you did that, and clear the cache it does not suppose to show.

check the logs when you clear the cache. makes no sense it stay there.

**Comment by milehighkaraoke** [comment]
Ok, now I got it to stop by  clear cache, mark all as finished  and then clear cache again....  will I have to do this after every transmission? Seems like I am missing something

**Comment by DanielnetoDotCom** [comment]
no, but if the on_publish_done fails again it may happen again.

**Comment by milehighkaraoke** [comment]
Tried going live again and it stayed on again after broadcast was over and here is what I got in the log.
@DanielnetoDotCom 
![Uploading Screenshot_20220119-184221_Samsung Internet.jpg…]()

**Comment by milehighkaraoke** [comment]
Other than that error the only thing I got to go on is every time I go live I have to  mark all as finished and clear cache... ugh what on earth

**Comment by milehighkaraoke** [comment]
Where do I start my troubleshooting, what is causing the Publish stop to fail?

**Comment by milehighkaraoke** [comment]
I removed the redirect in the virtual host and disabled and enabled the sites with the tube site being the second I enabled  it looks like Apache defaults the last site enabled

**Comment by DanielnetoDotCom** [comment]
> I removed the redirect in the virtual host and disabled and enabled the sites with the tube site being the second I enabled it looks like Apache defaults the last site enabled

Exactly what I told you https://github.com/WWBN/AVideo/issues/6193#issuecomment-1016496050

![image](https://user-images.githubusercontent.com/18009293/150329082-4e0f4657-249f-4927-9a1a-af82a7c4c1f6.png)
