### ISSUE TITLE
When I view Audio Only The Homepage Gets Stuck On Audio Only

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#6194]
When I click on browse Audio only, I get a list of all audio files only, which is fine. But lets say I change my mind and do not play anything but instead I go back to the homepage - I am stuck on audio only.

Refreshing the browser or clicking on the home button keeps taking me back to audio only files.

The only way to get out of audio only is to play one of the audio files - and then click on the home button. This can be quite confusing to visitors.

Here I choose to browse audio files from the left side menu:

![stuck on audio](https://user-images.githubusercontent.com/45924889/150010901-9e92a597-22f6-4351-b022-292c6b0f2a9c.jpg)

Here we see I am browsing audioOnly in the top link:

![audio only](https://user-images.githubusercontent.com/45924889/150010920-78b9d12b-e4b6-495f-b0b1-10d2bd40c50a.jpg)

And now I have clicked on the "Home" button or refreshed the browser:

![stuckonaudio](https://user-images.githubusercontent.com/45924889/150011433-6148ee48-9ba7-49ce-bdc6-9f741c599c33.jpg)

**Comment by The-Do-It-Yourself-World** [comment]
I can continue to click on the "Home" button or refresh the browser and I keep seeing the same results every time. No videos. The only way out of this loop is to actually play an audio file and only then do I return to the homepage next time I refresh or hit the "Home" button.

**Comment by DanielnetoDotCom** [comment]
You should click on “audio and video “ menu

**Comment by The-Do-It-Yourself-World** [comment]
How do I tell every visitor the the site that comes along? Shouldnt the "Home" button take us "Home"?
