### ISSUE TITLE
Cannot Make Some Videos Active Because Popup Window Sticks Over The Button

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#6195]
I am working on a lot of videos. I am working in "myvideos" to make a mess of new uploads active.

Sometimes a popup window gets stuck saying the video is inactive and to click the button to make it active. But it is stuck over the button so I cannot make it active. This appears to be random and shows up on 5-7 out of ten videos sometimes and sometimes a page of videos are fine.

![cannot make active](https://user-images.githubusercontent.com/45924889/150021406-945b633d-d605-4074-8a93-15734cc66229.jpg)

**Comment by The-Do-It-Yourself-World** [comment]
I can refresh the browser and manually click through the pages on "my videos" to get back to where I was and the errors go away. But it comes back again sometimes at random.

**Comment by The-Do-It-Yourself-World** [comment]
Sometimes the message comes up AFTER I make it active:

![Another error](https://user-images.githubusercontent.com/45924889/150031074-98dc5230-f073-4d12-870b-2ca691832602.jpg)

**Comment by The-Do-It-Yourself-World** [comment]
When edit a video, the popup messages stay on top. Notice on the right side, I made one video active and another popup appeared on top of the first popup telling me I should make it active AFTER I already did.

![more-errors](https://user-images.githubusercontent.com/45924889/150032079-54b41fe9-57dc-4114-bc8d-101707933eb3.jpg)

**Comment by KrzysioMisio** [comment]
it's the same for me
and the page shrinks with each click

**Comment by The-Do-It-Yourself-World** [comment]
Yeah, I did not notice the page shrinking.

**Comment by DanielnetoDotCom** [comment]
What browser are you using?

I just tested on chrome and I could not reproduce it.

**Comment by KrzysioMisio** [comment]
for me on Firefox and Edge

**Comment by The-Do-It-Yourself-World** [comment]
I am using Brave on a Win 7 pc. I am working on a lot of videos and its really terrible. The more I work, the more these popups cover the screen.

**Comment by DanielnetoDotCom** [comment]
Please try this update
