### ISSUE TITLE
Login failed - can't login after Update

### ISSUE THREAD

**Issue by PrXenon** [WWBN/AVideo#6196]
**Describe the bug**
After the last update i cant login to the site

![image](https://user-images.githubusercontent.com/3627520/150031133-3e710877-5c3b-40f4-be25-b9a87ef72fff.png)

**Comment by PrXenon** [comment]
hm.. looks like a PHP 7.3 bug... if i switch back tu PHP 7.2 everything is good

**Comment by DanielnetoDotCom** [comment]
is recommended you use PHP7.3 or grerater

you may be missing some library for it.

check your avideo.log and your apache.log

**Comment by JoshWho** [comment]
make sure to run 

`apt upgrade`

 after switching the php

**Comment by PrXenon** [comment]
yep.. i  missed some library...
