### ISSUE TITLE
AD SERVER I can't find the video listed

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#6197]
I am using the AD SERVER plugin.
I had no problems at Christmas.
Today I had to post a video and it's not listed.
When I go to enter the name of the video I uploaded I cannot find the video listed.

![AD Server](https://user-images.githubusercontent.com/82677269/150039253-0ee3eb5d-50e1-43ae-b1b5-e654428f4f54.PNG)

May I know why?
Maybe there is a bug and it needs to be fixed?
Daniel help me.
Thank you

This is the fully functional video that I have to insert and I can't find it in the list.

![AD Server1](https://user-images.githubusercontent.com/82677269/150039173-0f03d689-ce0d-4c7a-abd1-969cc22e6174.PNG)
![AD Server2](https://user-images.githubusercontent.com/82677269/150039184-efd1fca8-d47a-4d62-8416-0f29a6f8f57f.PNG)

I do exactly like the video posted here.

https://github.com/WWBN/AVideo/wiki/Ad-Server-Plugin

**Comment by DanielnetoDotCom** [comment]
try to add the video title into quotes

**Comment by JoshWho** [comment]
My suggestion is find the video in the video manager and give it a unique keytag that no other video has then search for that in the video ad manager. 

![ae032fc4-4711-4f14-a27c-6ebecc00b759](https://user-images.githubusercontent.com/39392449/150624203-df15f507-76f1-4248-a045-4ba09d038d00.png)

**Comment by sharknetwork24** [comment]
Excellent solution.
Thank you

**Comment by sharknetwork24** [comment]
> Il mio suggerimento è trovare il video in Gestione video e assegnargli un tag chiave univoco che nessun altro video ha, quindi cercarlo in Gestione annunci video.
> 
> ![ae032fc4-4711-4f14-a27c-6ebecc00b759](https://user-images.githubusercontent.com/39392449/150624203-df15f507-76f1-4248-a045-4ba09d038d00.png)
> 
> ![a6364fc2-9957-4793-82ec-bab0d103aca8](https://user-images.githubusercontent.com/39392449/150624278-02467fd8-0cb5-436e-a80e-5f546b6f4ec1.png)

Excellent solution.
Thank you

**Comment by sharknetwork24** [comment]
I don't have these descriptions.
Can you tell me how to add these items to mine too?
Thank you

![2](https://user-images.githubusercontent.com/82677269/150652125-f87e7983-f4f8-4c31-8772-0b9ca343080c.PNG)

![1](https://user-images.githubusercontent.com/82677269/150652133-4066d567-6ccc-4810-b9cd-8a117267286e.PNG)

**Comment by JoshWho** [comment]
Just type it in that box and press the comma key 
![download](https://user-images.githubusercontent.com/39392449/150652208-75dd9dee-d4b0-4f2c-9da1-6b8802b7c797.png)

**Comment by sharknetwork24** [comment]
Thank you very much
