### ISSUE TITLE
PROGRAMS: User only has access to videos they own (including the admin)

### ISSUE THREAD

**Issue by OptimistPrimal** [WWBN/AVideo#6198]
This has been a consistent issue since first installing AVideo (which I do love btw):  I'm the admin, I'm trying to build programming for our site using the "Program" feature.  Unfortunately I can only select videos that I own regardless of the setting in the plugin.

There are no  errors showing in any logs so am stuck on what the problem could be.

**Comment by OptimistPrimal** [comment]
I read that as a user I can create a "program" from any video on the site,
but even as Admin I can only access the videos that I own.

**Comment by DanielnetoDotCom** [comment]
You can create a playlist using any video. than you can create a program

**Comment by OptimistPrimal** [comment]
Aren't programs the "playlist"?  I'm not seeing a playlist option.

**Comment by DanielnetoDotCom** [comment]
Check if your Programs plugin is enabled?

![image](https://user-images.githubusercontent.com/18009293/150329885-a9f0a42e-2a51-428e-aea8-21599fa08078.png)

**Comment by OptimistPrimal** [comment]
Definitely activated.  I have programs created, but it will not allow me to select any video on the site, only videos that I am the owner of.  I have tried toggling the setting in the programs plugin settings - no luck.

**Comment by DanielnetoDotCom** [comment]
Can you please describe and provide some screenshots to help me understand what exactly steps are you taking?

**Comment by OptimistPrimal** [comment]
It works from the Add To button, but not from the manage Programs interface - it will only show the videos that I own.  Apologies for not being more specific.

**Comment by OptimistPrimal** [comment]
I see.  So as Admin, I should be able to see any video that isn't inactive correct?

**Comment by DanielnetoDotCom** [comment]
yes, if it is not unlisted

**Comment by OptimistPrimal** [comment]
I see.  Is that flag (unlisted) changeable?  We have videos that are unlisted on the site that we want to use in the programs to only be shown in the programs...

**Comment by DanielnetoDotCom** [comment]
yes, On the videos manager when you click on the grey eye, it will turn green (active)

![chrome-capture (2)](https://user-images.githubusercontent.com/18009293/150420422-ef00ce0f-4988-4221-84fd-9bcbee8719d9.gif)
