### ISSUE TITLE
Apache2 Virtual Host Configuration for 2 sites making tube site default 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6200]
Apache expert on here?
I would like Apache to recognize my tube site as default. As soon as I put my site name in the host file it gives me my tube site as default but it also points my 2nd virtual host at my default site.
Default mhktube.com
2nd  mhkaraoke.com

Both direct to mhktube.com untill I remove mhktube in the host file and replace it with local host, after doing this the sites are accessible by their name but it defaults to mhkaraoke.com instead of mhktube.com for localhost.
What do I need to do to fix this?

**Comment by DanielnetoDotCom** [comment]
search for apache virtual hosts
