### ISSUE TITLE
Not able to get the live stream started-please help

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#6201]
![image](https://user-images.githubusercontent.com/65802024/150335026-247c35d3-c2e3-453a-8f64-a50c15e19b54.png)

dont have this file /var/www/html/YouPHPTube/plugin/Live/standAloneFiles/WebRTCServer/server.php
![image](https://user-images.githubusercontent.com/65802024/150335173-8c029178-89aa-4e8b-8d20-a85e12ef7732.png)

**Comment by DanielnetoDotCom** [comment]
Do you have a separate server as a Liveserver?

or do you use the Live server on the same server as the Streamer?

**Comment by DanielnetoDotCom** [comment]
If it is on the same server, do not use the external live servers, leave the plugin as the default

check this 
https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

**Comment by vraghavans** [comment]
![image](https://user-images.githubusercontent.com/65802024/150633505-6b915fe7-b2a9-49a8-8553-c3dabf9cc35c.png)
can see its online but the video is not coming.
![image](https://user-images.githubusercontent.com/65802024/150634251-4cd53db8-b2f6-4086-ab7e-bf9e3d0c15fa.png)
the live is showing success but offline is not changing
Can you please guide me

**Comment by DanielnetoDotCom** [comment]
before using the webrtc, please use OBS to start a live, so you can make sure your live server is properly set up.

once you can live with OBS, you may want to try the webrtc cam

FYI, the webrtc cam is still in beta.
