### ISSUE TITLE
Change Header Title of Scheduled Live Link

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6204]
All it says in the meta for title is Coming Soon. any way that can be changed to the real title so people can find it in search, and have some kind of "Notify me" option to click and it will email when it goes live or 5 minutes til maybe?

![e4c88cb4-0e0d-47f7-8702-2216af0e3797](https://user-images.githubusercontent.com/39392449/150605099-67655462-a359-4232-9f30-78c1a5a6b940.png)

This is the scheduled event here https://www.joshwhotv.com/liveLink/53/live-trump-rally---save-america-rally-in-conroe-tx

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by JoshWho** [comment]
Perfect. Thank you @DanielnetoDotCom
