### ISSUE TITLE
Videos ID is not defined

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#6205]
When I try to upload an image I get this error.
Videos_ID is not defined

![4](https://user-images.githubusercontent.com/82677269/150653364-b2d5c0eb-7931-4fe0-9fe6-656b96c70c3a.PNG)

![3](https://user-images.githubusercontent.com/82677269/150653367-735c13f0-1d97-4871-ac0a-bfc5fc2989b3.PNG)

I tried various types of images:
JPG, PNG, BMP
None of these are loaded.
You tell me Daniel how to kindly solve the problem.
Thank you

**Comment by DanielnetoDotCom** [comment]
I remember fixing this some time ago.

please try to make a git pull

**Comment by sharknetwork24** [comment]
I did this yesterday after updating 3 plugins. 
Daniel help me solve this problem.
Thank you

**Comment by DanielnetoDotCom** [comment]
Question are you editing or creating a new article/video?

the video id is only available when you are editing.

**Comment by sharknetwork24** [comment]
The video has already been inserted previously.  So I do this by making editing after.

**Comment by DanielnetoDotCom** [comment]
I see, I just tried it locally, and works fine.

can you please try to reproduce it on demo site?
