### ISSUE TITLE
How to Auto enable Meet for all users instead of enabling it manually.

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#6208]
Greetings. I would like to auto enable meet for all users instead of enabling it manually.Please help.

**Comment by JoshWho** [comment]
If too many are using it at once you will need to expand to external servers. 30 per room is how it works. Jitsi so if say you had 3k users and wanted to enable jitsi meet for them all would create 3k  sockets and Memory for every spawn being called.

**Comment by mrgodgiven** [comment]
@JoshWho  I'm not talking about the number of users in a meeting, but I want all users to be able to use meet automatically after sign up, because now I have to enable meet for every user after sign up.

**Comment by JoshWho** [comment]
I am saying if you have everyone enabled it can be a mess if you have lots of users all trying to use it at once.

**Comment by mrgodgiven** [comment]
@JoshWho  thanks for your advice, but right now i only have 1k users and i have a problem with some that install my app with the purpose of going live, but they can't go live until I enable the meet camera. They don't go live together at the same time. Please help me if you know how enable this feature. i want a new user to be able to use meet automatically after registering.

**Comment by DanielnetoDotCom** [comment]
Hi, currently we do not have this option to auto enable

**Comment by mrgodgiven** [comment]
Ok thanks for your response.
