### ISSUE TITLE
"Forgot Password" does not work

### ISSUE THREAD

**Issue by aolvictim** [WWBN/AVideo#6209]
**Describe the bug**
"I forgot my password" feature does not work. In fact, it doesn't work on the Tutorial site either.

**To Reproduce**
1. Go to 'https://tutorials.avideo.com/user'
1. Put in user name
1. Click on 'I forgot my password'
1. Put in CAPTCHA (actually it doesn't really matter if you put in CAPTCHA at all, the site does not validate CAPTCHA)
1. The dialog goes away and nothing happens.

**Expected behavior**
I expect to see a success message asking me to check my email.

**Error Logs**
There is no error log or any log

**Screenshots**

[Here is a video ](https://user-images.githubusercontent.com/7109995/151023538-8680ec91-f285-47f9-bdbf-eaaddbd8ffc1.mov)

**Comment by jengajenga** [comment]
I have a similar problem

**Comment by DanielnetoDotCom** [comment]
Thanks for noticing that. here is an update

**Comment by aolvictim** [comment]
Thanks.
