### ISSUE TITLE
updateCheck.php

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6210]
in view/include/updateCheck.php
in line 13-14
closing error 
" ?> "
`if (!empty($updateFiles)) {`
       ` //not updated system?>`

**Comment by KrzysioMisio** [comment]
https://github.com/WWBN/AVideo/blob/master/view/include/updateCheck.php
is
see line 13 and 14

**Comment by KrzysioMisio** [comment]
is
 `if (!empty($updateFiles)) {`
        `//not updated system?>`
it is supposed to be like this
 `if (!empty($updateFiles)) {`
        `//not updated system`
`?>`

**Comment by DanielnetoDotCom** [comment]
Sorry you are right

Fixing it now.;
