### ISSUE TITLE
Auto play next video will not disable on embed videos

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6211]
Hi Daniel, im reopening this issue as I see this still bothers some of our channels embedding their own content. Here is an example of such embed code:

So even when they remove autoplay they still get next videos from other channels.
They have cleared the cookie. and cache and the issue remains.

<iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="https://live.ahava528.com/vEmbed/11421" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no">iFrame is not supported!</iframe>

**Comment by DanielnetoDotCom** [comment]
Duplicated https://github.com/WWBN/AVideo/issues/5990
