### ISSUE TITLE
Need help with YPT socket. Doing Fresh install.

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#6212]
Please Need Help. I need detailed info on making this work. 
What needs to be installed
What needs to be added to conf files
And what conf files need to be modified
This websocket *&*&%% LOL
Thank you

**Comment by DanielnetoDotCom** [comment]
I just add some more info on the wiki

check this https://github.com/WWBN/AVideo/wiki/Socket-Plugin#check-list

and this https://github.com/WWBN/AVideo/wiki/Socket-Plugin#here-are-the-outputs-from-a-working-socket-server

**Comment by Lordblanca** [comment]
Do I need to set up a proxy server with this or some type of proxy and if so which type of proxy... Thank you

**Comment by DanielnetoDotCom** [comment]
On my installations I do not use any type of proxy

**Comment by Lordblanca** [comment]
Ok Thank you. Getting back to work
