### ISSUE TITLE
Error referring to login.json.php when some plugins are active

### ISSUE THREAD

**Issue by ecesarini** [WWBN/AVideo#6213]
**Describe the question**
Hi,
I'm running an instance of last mediavideo version on docker containers.
We wrote a plugin to login via sso using our internal idp (the plugin is based on hybridauth as LoginGoogle, LoginLinkedin etc. ), we purchased also LoginLDAP.

The plugin works fine until i try to activate other plugins: 
e.g. If LoginLDAP and LoginMySSO are active i get error if YoutubeAPI is active. Error occours also activating other plugins, and it seems not to depends on the number of plugins active but on the type of plugin .

**Screenshots**
Here's the error when i click on Mylogin 
```array(4) { ["type"]=> int(1) ["message"]=> string(149) "Uncaught Error: Call to a member function getDataObject() on string in /var/www/html/AVideo/objects/login.json.php:79 Stack trace: #0 {main} thrown" ["file"]=> string(43) "/var/www/html/AVideo/objects/login.json.php" ["line"]=> int(79) } {"error":true,"msg":"Under Maintanance"}```

My plugin snippet reference that could be related to the problem:
```    public function getEmptyDataObject() {
        global $global;
        $obj = new stdClass();
        
        $obj->id = "";
        $obj->key = "";

        return $obj;
    }
    
    public function getLogin() {
        $obj = new stdClass();
        $obj->class = "btn btn-danger btn-block my-sso"; 
        $obj->icon = "fas fa-unlock-alt"; 
        $obj->type = "mysso"; 
        $obj->linkToDevelopersPage = "https://mysite.com";
        return $obj;
    }
```

Thank you for any help,
EC

**Comment by DanielnetoDotCom** [comment]
Hi

Few things...

1. I recommend you update your code, looks like you are running an old version;
2. add a var_dump on variable `$value['loginObject']` on line 75 of file `objects/login.json.php`
3. make sure in your plugin file the following methods return unique names

```
    public function getName() {
        return "UniquePluginName"; // same as plugin file
    }

    public function getUUID() {
        return "uniqueID-75436025e8a7"; // any string
    }


```

**Comment by ecesarini** [comment]
Thank you very much for your help,

**1.** Updated avideo core code (anyway my Dockerfile pulls last avideo repo at build-time)
**2.** Checked apache, avideo log files but i couldn't find nothing indicative
**3.** On line _75 objects/login.json.php_  i added:
![sso_pluginDebug_01](https://user-images.githubusercontent.com/73652902/151255693-33257cd0-e175-46be-8831-e7c62a77534f.jpg) 
getting:
```string(1) "/" array(4) { ["type"]=> int(1) ["message"]=> string(149) "Uncaught Error: Call to a member function getDataObject() on string in /var/www/html/AVideo/objects/login.json.php:76 Stack trace: #0 {main} thrown" ["file"]=> string(43) "/var/www/html/AVideo/objects/login.json.php" ["line"]=> int(76) } {"error":true,"msg":"Under Maintanance"}```
so I don't know what to do with it
**4.** _return_ of functions you reported are right

Thank you again,
EC

**Comment by DanielnetoDotCom** [comment]
I am sending you an update that is not supposed to fix the issue. but it will give you some clue on the log what is wrong.

**Comment by ecesarini** [comment]
Thank you Daniel

**Comment by ecesarini** [comment]
Hi Daniel,
i tried your commit:
in objects/json.php
```
            if(!is_object($value['loginObject'])){
                _error_log('Error on getLogin: '. json_encode($value), AVideoLog::$ERROR);
                continue;
            }
```
The plugin works (i think becaues of **continue**).
Commenting **continue** i get similar error 
```array(4) { ["type"]=> int(1) ["message"]=> string(149) "Uncaught Error: Call to a member function getDataObject() on string in /var/www/html/AVideo/objects/login.json.php:84 Stack trace: #0 {main} thrown" ["file"]=> string(43) "/var/www/html/AVideo/objects/login.json.php" ["line"]=> int(84) } {"error":true,"msg":"Under Maintanance"}```

So i modified code
```
              if(!is_object($value['loginObject'])){
              var_dump($value);
                _error_log('Error on getLogin: '. json_encode($value), AVideoLog::$ERROR);
              //  continue;
            }
```

And i get 
```string(56) "/var/www/html/AVideo/plugin/LoginLDAP/view/loginForm.php" array(4) { ["type"]=> int(1) ["message"]=> string(149) "Uncaught Error: Call to a member function getDataObject() on string in /var/www/html/AVideo/objects/login.json.php:84 Stack trace: #0 {main} thrown" ["file"]=> string(43) "/var/www/html/AVideo/objects/login.json.php" ["line"]=> int(84) } {"error":true,"msg":"Under Maintanance"}```

Maybe something goes wrong with **LoginLDAP/view/loginForm.php**?
We purchased LDAP plugin and it has been modified by you according to [this issue (https://github.com/WWBN/AVideo/issues/6064) (mcorvo is my colleague).

Thank you very much for your support,
EC

**Comment by DanielnetoDotCom** [comment]
so did you modify the LDAP plugin?

I am completely lost about how is it happening.

did you modify the plugin or you did create a new one?

**Comment by ecesarini** [comment]
> so did you modify the LDAP plugin?
> 
> I am completely lost about how is it happening.
> 
> did you modify the plugin or you did create a new one?

No, I didn't modify LDAP plugin, it's encrypted. 
We're using LDAP plugin (purchased from the store), but you added some customization according to the issue I [linked](https://github.com/issues/6064) in the previous post.

I created a plugin to perform SSO using our internal idp, but we'd like to let the 2 auth plugins working together.

**Comment by DanielnetoDotCom** [comment]
Can you please share your plugin code ?

currently I have no idea what is causing this but I can try to install it locally and test it

**Comment by ecesarini** [comment]
> Can you please share your plugin code ?
> 
> currently I have no idea what is causing this but I can try to install it locally and test it

Hi Daniel,
here's [the link to the plugin](https://github.com/ecesarini/AVideo-LoginINFN). 
It misses a Provider.php file that manages Hybridauth according to our idp settings and it's directly copied into the container folder _vendor/hybridauth/hybridauth/src/Provider/_.
I don't think that code part could cause the error.
Anyway plugin works fine until i try to activate LDAP plugin: then i get the errors above.

Thank you,
EC

**Comment by DanielnetoDotCom** [comment]
I cloned your plugin and the only thing I did was to remove the extra LoginINFN directory you had

check this https://github.com/DanielnetoDotCom/AVideo-LoginINFN

should looks like this 

![image](https://user-images.githubusercontent.com/18009293/151364956-6a984b4a-16af-4d46-991e-40c9d4b3ad72.png)

**Comment by ecesarini** [comment]
Hi,
the directory structure is the same we're running in production. 
The plugin works fine: that error is due to the missing Provider.php i spoke above.

The error i reported 
```
string(56) "/var/www/html/AVideo/plugin/LoginLDAP/view/loginForm.php" array(4) { ["type"]=> int(1) ["message"]=> string(149) "Uncaught Error: Call to a member function getDataObject() on string in /var/www/html/AVideo/objects/login.json.php:84 Stack trace: #0 {main} thrown" ["file"]=> string(43) "/var/www/html/AVideo/objects/login.json.php" ["line"]=> int(84) } {"error":true,"msg":"Under Maintanance"}
```
comes out when i click INFNAAI plugin button and LoginLDAP is active. That is, LoginINFN return this error and stop working, but login through LDAP works.

Thank for your time

**Comment by DanielnetoDotCom** [comment]
The "Unknown Provider" error comes from [hybridauth](https://hybridauth.github.io/)

If you want to use hybridauth you may need to deal with them and add your provider to it.

or you can just create your own authenticator.


that is the snipped of the code on the LDAP plugin

````
    static function login($user, $pass) {
        if (!User::checkLoginAttempts()) {
            return User::CAPTCHA_ERROR;
        }
        $resp = self::auth($user, $pass);
        if ($resp === User::USER_LOGGED) {
            global $global;
            $obj = AVideoPlugin::getObjectData("LoginLDAP");
            require_once $global['systemRootPath'] . 'objects/user.php';
            // create user if need     
            $name = $user;
            $photoURL = $obj->defaultProfilePhoto;
            $email = $user;
            if (!$obj->savePassword) {
                $pass = rand();
            }
            $users_id = User::createUserIfNotExists($user, $pass, $name, $email, $photoURL, false, true);
            // login
            if (!empty($obj->autoAddNewUsersOnUserGroup)) {
                UserGroups::updateUserGroups($users_id, array($obj->autoAddNewUsersOnUserGroup->value), true, true);
            }

            $userObject = new User(0, $user, $pass);
            $userObject->login(true, false, true);
            return User::USER_LOGGED;
        }
        return $resp;
    }

````

**Comment by ecesarini** [comment]
> The "Unknown Provider" error comes from [hybridauth](https://hybridauth.github.io/)
> 
> If you want to use hybridauth you may need to deal with them and add your provider to it.
> 
> or you can just create your own authenticator.
> 
> that is the snipped of the code on the LDAP plugin
> 
> ```
>     static function login($user, $pass) {
>         if (!User::checkLoginAttempts()) {
>             return User::CAPTCHA_ERROR;
>         }
>         $resp = self::auth($user, $pass);
>         if ($resp === User::USER_LOGGED) {
>             global $global;
>             $obj = AVideoPlugin::getObjectData("LoginLDAP");
>             require_once $global['systemRootPath'] . 'objects/user.php';
>             // create user if need     
>             $name = $user;
>             $photoURL = $obj->defaultProfilePhoto;
>             $email = $user;
>             if (!$obj->savePassword) {
>                 $pass = rand();
>             }
>             $users_id = User::createUserIfNotExists($user, $pass, $name, $email, $photoURL, false, true);
>             // login
>             if (!empty($obj->autoAddNewUsersOnUserGroup)) {
>                 UserGroups::updateUserGroups($users_id, array($obj->autoAddNewUsersOnUserGroup->value), true, true);
>             }
> 
>             $userObject = new User(0, $user, $pass);
>             $userObject->login(true, false, true);
>             return User::USER_LOGGED;
>         }
>         return $resp;
>     }
> ```

Hi daniel [here's a video](https://youtu.be/NURjj0t8mVc) to explain my problem (maybe i didn't focus it so well):
My plugin works very fine (Provider.php is present but i didn't upload it)

Here are all the steps of my issue:
- SSO works and LDAP is inactive
- Go to the admin panels, activate LDAP
- Retry Login by SSO 
- Got error

Thank you

**Comment by DanielnetoDotCom** [comment]
I see, you are using as a hibridauth provider, but you can have your own button/form 

check this new pullrequest https://github.com/ecesarini/AVideo-LoginINFN/pull/1

**Comment by ecesarini** [comment]
> 

Hi again Daniel,
thank for the PR.

This is the code my plugin was triggering after you clicked on INFNAAI button. It is  a file named _InfnAAI.php_ loaded into _vendor/hybridauth/hybridauth/src/Provider/_ directory that accomplishes authentication.

```
<?php
/*!
* Hybridauth
* https://hybridauth.github.io | https://github.com/hybridauth/hybridauth
*  (c) 2017 Hybridauth authors | https://hybridauth.github.io/license.html
*/

namespace Hybridauth\Provider;

use Hybridauth\Adapter\OAuth2;
use Hybridauth\Exception\UnexpectedApiResponseException;
use Hybridauth\HttpClient;
use Hybridauth\Data;
use Hybriduth\Data\Collection;
use Hybridauth\User;



class InfnAAI extends OAuth2
{
    protected $scope = 'openid profile email';
    protected $apiBaseUrl = 'https://mydip.it';
    protected $accessTokenUrl = 'https://myidp.it/token';
    protected $authorizeUrl = 'https://myidp.it/auth';

    protected function initialize()
    {
        parent::initialize();
        
        if ($this->isRefreshTokenAvailable()) {
            $this->tokenRefreshParameters += [
                'client_id'     => $this->clientId,
                'client_secret' => $this->clientSecret,
                'grant_type'    => 'refresh_token',
            ];
        }

    }

    public function getUserProfile()
    {
    $response = $this->apiRequest('auth/realms/aai/protocol/openid-connect/userinfo');
    
    $colletion = new Data\Collection($response);

    $userProfile = new User\Profile();

    $userProfile->identifier = $colletion->get('sub');
    $userProfile->displayName = $colletion->get('name');
    $userProfile->email = $colletion->get('email');
    $userProfile->firstName = $colletion->get('given_name');
    $userProfile->lastName = $colletion->get('family_name');

    return $userProfile;
    }

}
```

Now the button does nothing. Should I put this snippet inside your below function?
```    
$(document).ready(function () {
        $('#LoginINFNButton').click(function () {

        });
    })
```

Could it let me authenticate both SSO and LDAP? This is my goal, that the two plugins don't interefere between theirselves and user can choose how to authenticate himself.

Thank you for you support

**Comment by DanielnetoDotCom** [comment]
I understand better now, so I guess we need to roll back the modification.

is your provider file case-sensitive? (MUST BE)

in what exactly folder did you save that file?

**Comment by ecesarini** [comment]
> I understand better now, so I guess we need to roll back the modification.
> 
> is your provider file case-sensitive? (MUST BE)
> 
yes

> in what exactly folder did you save that file?
A copy is stored in 
```
AVideo/plugin/LoginINFN/hybridauth/InfnAAI.php
```
but i think this is not used at runtime.

In the running container this file is also copied  (by our _Dockerfile_) into 
```
AVideo/vendor/hybridauth/hybridauth/src/Provider/
```
to let hybridauth match it during authentication request triggered by plugin.

**Comment by ecesarini** [comment]
Hi Daniel,

is there a way to let LDAP and my sso plugin getting along with? 
Anyway I could try to directly edit login.json.php inside my Dockerfile, by a sed statement. 
I'd prefer avoiding it 'cause I think it wouldn't be a good practice about some next future AVideo update.

Thank you very much

**Comment by DanielnetoDotCom** [comment]
Sorry, currently I am still lost what is missing and why it is happening.
