### ISSUE TITLE
navbar.php

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6214]
https://github.com/WWBN/AVideo/blob/master/view/include/navbar.php
line 547 
`//var_dump($lang);exit;?>`

**Comment by DanielnetoDotCom** [comment]
OMG, looks like some update made this. thanks for noticing again.

**Comment by DanielnetoDotCom** [comment]
Done, what PHP version are you using?
I am not getting any notifications on my side

**Comment by KrzysioMisio** [comment]
i have php 7.4
i have modified some files i update them manually
