### ISSUE TITLE
Couple issues or fixes to improve Meet 

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#6215]
1. It's not appropriate for users to see meetings created by others, users should only see their own meetings. 
2. Unless someone is invited to a meeting, there's no reason they should be able to join in (that's not secure at all).

Could you look at how to fix these @DanielnetoDotCom

**Comment by JoshWho** [comment]
Only the admin sees everyone's meetings.  Log in as a regular user you won't see someone elses unless you got invited
