### ISSUE TITLE
Repeat notifications

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6217]
@DanielnetoDotCom good morning

I'm having a situation where notifications for the same stream are showing up twice. See screenshot highlighted in red.

![repeat-notifications](https://user-images.githubusercontent.com/65451390/151299701-cfab2698-9794-4574-afaf-31b6e2bc9172.jpeg)

This has happened more than three times but the above is an example.

**Comment by DanielnetoDotCom** [comment]
are you running the latest git pull? I recently fixed a similar issue.

**Comment by jengajenga** [comment]
Actually no I'm not. I'll update later tonight and revert.
