### ISSUE TITLE
Offline streamer still on homepage

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6218]
@DanielnetoDotCom good morning

![still-here](https://user-images.githubusercontent.com/65451390/151305823-bf811a3e-2d7e-4732-9e46-2bb65f40b046.jpeg)

I have a problem with this stream.

1. I disconnected his stream by clicking disconnect livestream 
![dc-ls](https://user-images.githubusercontent.com/65451390/151306148-5487df02-0573-4aa3-a7d6-7a77892b6e20.jpeg)

2. I removed livestream rights in his account.
3. I deactivated the account
4. I restarted apache and nginx
5. In my settings i have "do not show live on categories" checked

Still he shows up on the homepage. Is there something else I can do to remove him? He just won't go. And when you click on the stream, it just refreshes the homepage.

Any help?

Thanks

**Comment by DanielnetoDotCom** [comment]
Hi, when you click this please check your log

you have to make sure your control is working...

https://github.com/WWBN/AVideo/blob/master/plugin/Live/standAloneFiles/control.json.php

and your nginx.conf has it

https://github.com/WWBN/AVideo/blob/4894b6908e5f0f09fb1cf1d4bc1aef9d6b518438/plugin/Live/install/nginx.conf#L131-L136

if your live server is not on the same server as the streamer, change this to your streamer server IP

https://github.com/WWBN/AVideo/blob/4894b6908e5f0f09fb1cf1d4bc1aef9d6b518438/plugin/Live/install/nginx.conf#L133
