### ISSUE TITLE
Mod_expired  with no help suggestions on how to fix

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6221]
@DanielnetoDotCom  what am I missing, I am not sure how to proceed so that I can get this mod updated
![20220128_090334](https://user-images.githubusercontent.com/70327833/151586489-7a9acac3-3bd0-4523-88a5-7e37f0e1840f.jpg)

**Comment by milehighkaraoke** [comment]
![20220128_110041](https://user-images.githubusercontent.com/70327833/151598301-9a82ddda-7205-417d-88ee-7e12f234aa43.jpg)

**Comment by milehighkaraoke** [comment]
What is the command to install the mod

**Comment by DanielnetoDotCom** [comment]
try to google for that.

**Comment by milehighkaraoke** [comment]
Is this referring to an apache mod or an nginx mod?

**Comment by DanielnetoDotCom** [comment]
Apache

**Comment by jengajenga** [comment]
sudo apt install -y apache2 apache2-utils libapache2-mod-xsendfile libapache2-mod-fcgid

sudo a2enmod rewrite headers userdir proxy expires xsendfile ssl mpm_prefork

try that

**Comment by milehighkaraoke** [comment]
Perfect... thank you @jengajenga
