### ISSUE TITLE
Love the new Upload Encoder Layout - Any way to add a Thumbnail Grabber to the preview Window?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6224]
![download (7)](https://user-images.githubusercontent.com/39392449/151655210-f09b8baf-fbe0-4ae8-88fa-7f2f6525d4d4.png)

**Comment by JoshWho** [comment]
A way to like play the video in the preview window and select what you want to be the thumbnail and then click save for it.

![7081c515-09ff-4635-a187-599a3454f384](https://user-images.githubusercontent.com/39392449/151655277-8f7b04dc-49f5-4b1c-be1c-8be428751e18.png)

**Comment by DanielnetoDotCom** [comment]
We are only able to extract a thumbnail after the encoder downloads the file.

But I have plans for the future to extract multiple thumbs and let you choose one.

**Comment by JoshWho** [comment]
Sweet sounds awesome Thanks for the update
