### ISSUE TITLE
Videos not playing after last git pull

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6225]
Here is what is happening 
Site is open and here is the link
https://mhktube.com/v/5

**Comment by DanielnetoDotCom** [comment]
Please make sure you have this https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom 
![20220129_064750](https://user-images.githubusercontent.com/70327833/151663665-d737f9f9-2fea-4d97-93c8-027721ba1d74.jpg)
![20220129_064541](https://user-images.githubusercontent.com/70327833/151663666-63ff0e65-168e-4681-94b9-553b12135ba0.jpg)

**Comment by milehighkaraoke** [comment]
They play  if I access local host

**Comment by DanielnetoDotCom** [comment]
I am pretty sure it is not properly setup, your video is returning 0 KB

If you have the SecureVideosDirectory plugin, check this 

![chrome-capture](https://user-images.githubusercontent.com/18009293/151663867-34917f19-2b5b-4571-937e-12e03d8ab3d9.gif)

Or update your code and test this URL https://mhktube.com/videos/test.mp4

If it is working you should see something like this https://demo.avideo.com/videos/test.mp4

![image](https://user-images.githubusercontent.com/18009293/151664214-4af4077d-fcfd-4e7b-84fb-0408b06a841a.png)

A blank page means is not working

**Comment by milehighkaraoke** [comment]
Update the code? 
No secure video plugin
![Screenshot_20220129-071833_Samsung Internet](https://user-images.githubusercontent.com/70327833/151664505-ce0ed5c4-4fe3-4655-9678-c10225caf9e8.jpg)

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/151664743-3e8abd92-7da1-402e-ae98-18d3a4ef6396.png)

**Comment by milehighkaraoke** [comment]
ok, I cold not find the mis-configuration as everything is as shown on the WiKi guide. I turned X-Send off and  reversed this https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle now they work but no X-Send any idea where the issue is? i followed this exactly https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

**Comment by DanielnetoDotCom** [comment]
I guess you are not putting the apache properties correctly to on the correct place;

**Comment by milehighkaraoke** [comment]
Are you saying the configuration at https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle
is not correct? 
![20220129_064541](https://user-images.githubusercontent.com/70327833/151667592-acf77b75-5195-49a6-8973-6908924c7232.jpg)

**Comment by DanielnetoDotCom** [comment]
In what exact file did you add it?

did you restart Apache after add it?

maré the directory paths correct?

**Comment by milehighkaraoke** [comment]
This is my virtual directory in apache for my site. 
I did restart apache and I also rebooted the server. 
When I disable xsend file and remove everything that I changed from here my videos work.
https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

Do I also need to add these values elsewhere?

**Comment by milehighkaraoke** [comment]
Ok I got it I see the updated directions to put it also in the -le-ssl.conf

Thank you kind sir
