### ISSUE TITLE
Docker compose 

### ISSUE THREAD

**Issue by ncamacho97** [WWBN/AVideo#6226]
I'm curious if anyone has used a reverse proxy when using the docker compose up because I have it up and running only app and db I tried nginx proxy manager I was able to point the IP: port to a domain but the HTML looks shitty plus I still have got a encoder via docker are you guys planning on updating the docker compose?

**Comment by ncamacho97** [comment]
@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Hi

I am not good at docker. some other users created this script

I am accepting docker help. if you have any update, please feel free to make a pull request

**Comment by trickert76** [comment]
Can you give a more detailed example? What reverse proxy config, etc. See #6185

**Comment by mohmafia** [comment]
the problem with nginx proxy maneger and Avideo in docker is that it refuses to use https Daniel has to look in to it and change the way Avideo parses files in https  also when you install avideo in docker on a apache container and use the nginx proxy manager the installer does not accept the https domain i did in the past do some docker work for Avideo but the way this video script loads only half in https so mixed contents it looks shitty as browsers block http requests over https

**Comment by trickert76** [comment]
The current docker image contains an Apache. 

It is configured to have a avideo.localhost virtualhost on Port 80/443. The 443 port should be used for HTTPS. But the current [configuration](https://github.com/WWBN/AVideo/blob/master/deploy/apache/avideo.conf) that is used inside the docker image isn't configured correctly. 

Neither is SSL enabled by default for port 443 nor is there any certificate that is mandatory. So the Docker integrated Apache response on Port 443 with plain HTTP (no S). This cannot work at all. I'm currently building a new image and try to create a working docker configuration.

So the external reverse proxy isn't really the problem.

**Comment by ncamacho97** [comment]
hey guys sorry for late respond, @trickert76  i had it working on localhost but as we both mentioned it looks ridiculous after using a reverse proxy lol hey im glad your working on the docker compose if you need help shoot me a message

**Comment by trickert76** [comment]
I've some questions for the environment.

- is there somewhere a documentation for the instalation process? My problem are
  - the docker image is installing AVideo in /var/www/html/AVideo and points a Vhost to that location. But it also installs the Encoder to /var/www/html/AVideo-Encoder. But there is nowhere a Apache2 Reference to that Docroot.
  - then the docker image is creating /var/www/html/AVideo/videos - is this the location, where the video files are stored (which would be relevant for Docker to mount that folder as a persist volume)
  - inside the git repo there is a folder storage/data. What is stored there and is it necessary to persist too?

- the docker-compose defines a database. The AVideo platform is starting and asks for the configuration. Because we already know everything about the database, is it possible to define the configuration during docker startup and skip the install process? Automation? What is the format? Or other way around - why do you set ENV vars about the DB inside the docker image when you don't use them?

- the docker compose is exporting some ports like 3306. Is this necessary?

**Comment by trickert76** [comment]
https://github.com/WWBN/AVideo/compare/master...trickert76:master?diff=unified

**Comment by trickert76** [comment]
https://hub.docker.com/r/trickert76/avideo-platform/tags

**Comment by trickert76** [comment]
I was able now to see the install script. I'm not sure, if all issues are solved. I'll test that now. The nginx reverse proxy has the following configuration

```
server {
  listen 80;
  listen [::]:80;
  server_name avideos.fqdn ;

  location / {
    return 301 https://avideos.fqdn$request_uri;
  }
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name avideos.fqdn;

  ssl_certificate /etc/letsencrypt/live/avideos.fqdn/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/avideos.fqdn/privkey.pem;

  include /etc/nginx/ssl/options-ssl-nginx.conf;
  ssl_dhparam /etc/nginx/ssl/ssl-dhparams.pem;

  client_max_body_size 200M;

  location / {
    proxy_pass https://avideo.local/;

    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains;";

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Nginx-Proxy true;

    proxy_redirect off;
  }
}
```

Where `avideos.fqdn` is the external domain and `avideo.local` is the docker image local dns name or IP etc...

**Comment by trickert76** [comment]
Ok, now I can answer the discussion about the encoder myself. Per default it is https://encoder1.avideo.com/ and it can only be changed via Web UI. This is now the same problem as the database config itself. An automation configuration process is not able to make human interactions.

I know, you store the database configuration in a newly file in videos/configurations.php.

- is it a good idea to extend the new docker-entrypoint to generate that file itself, when the necessary environment variables are given? For example a default configurations file and sed the DB and websiteRootURL settings? What about the admin credentials? Or maybe create a new PHP script as CLI that calls the function in the install process? Then we could also remove the install folder inside the container

- the encoderURL ist configured in the database. But it has a default value in objects/configuration.php. I would now extend that file to look into the config above, when it isn't configured in the database and only return encoder1.avideo.com when it also not available in the $globals?

Also I would remove the encoder from the avideo platform docker image and build a new separate container.

So please do not merge the PR yet.

**Comment by trickert76** [comment]
ah, checkConfiguration.php checks for /var/www/html/AVideo/Encoder, but the docker file is currently extracting the Encoder to the wrong location... my fault

**Comment by trickert76** [comment]
so - haha - now the configuration is automatically be written when it isn't already existing (we don't override them). So the web installer can be ignored in docker env. Now the only problems seems to be the installation of the Encoder. It says on the install screen

    Error creating streamer: Unknown column 'allowedStreamersURL' in 'field list'

Is it possible, that there are newer commits after release 3.7 that are mandatory for AVideo "master"? I'll check that next week.

**Comment by ncamacho97** [comment]
do u have a discord

**Comment by mohmafia** [comment]
aint it easier to create a container fully installed with all needed stuf and create  letsencrypt certs ?
i will try to create one and make it ask the user to set FQDM then have letsencrypt generate the certs for the user's domain name  then all they got to do to install it all is docker-compose up -d  no need for all the build stuff they only get asked for the domain name and after deploying all should run fine with ssl
