### ISSUE TITLE
delete user

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6228]
how to delete a user ??

**Comment by akhilleusuggo** [comment]
you can't

you can just disable it

**Comment by KrzysioMisio** [comment]
why ???
and if I remove it via phpmyadmin, there will be some trash after it ??

**Comment by akhilleusuggo** [comment]
Just disable the account.

**Comment by akhilleusuggo** [comment]
https://github.com/WWBN/AVideo/issues/5619
