### ISSUE TITLE
How to edit left side bar

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6229]
I wish to add Items to left side bar like access to pages and other info, how can this be done?

**Comment by DanielnetoDotCom** [comment]
Did you try the top menu plugin?

**Comment by guymass** [comment]
No cause that a Top menu no? but I will try maybe it is there.

**Comment by guymass** [comment]
Silly me you'r right, editing those sections are located there, was confusing to me, I forgot where it was, much thanks.
