### ISSUE TITLE
Optional per video text/html popup

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6230]
Would it be a hassle to allow a simple checkbox that will open a popup upon opening a video post show whatever text the user wishes to show prior to viewing the video. In my case I wish to be able to show such a warning on certiain content and to allow this on a per video, like another field in the post editor.

Here is what i want to show:
---
FAIR USE NOTICE: This video may contain copyrighted material.

Such material is made available for educational purposes only.

This constitutes a 'fair use' of any such copyrighted material as provided for in Title

17 U.S.C. section 107 of the US Copyright Law....

"I am in no way associated with the content of this video, and in no form take credit for the content shown"this video post is for education purposes only."
---

**Comment by DanielnetoDotCom** [comment]
I understand, but right now we do not have this option yet.

**Comment by guymass** [comment]
Maybe in the future :-)
