### ISSUE TITLE
WebSiteRootURL variable not defined in script.js

### ISSUE THREAD

**Issue by mcorvo** [WWBN/AVideo#6239]
Dear Daniel,

we recently came across what is most likely a bug in the script.js file. Up to some months ago, the "+" button to the right of the "Category" drop down menu in the Encoder page, opened a popup that let you define new categories. With the latest build from branch "master" it looks like this is no longer working. 

1. Go to Encoder
2. Click on '+' to the right of "Category"

Nothing happens. If you open the Dev Tools in Chrome, there's evidence of a missing variable:

Uncaught ReferenceError: webSiteRootURL is not defined
    at avideoModalIframeWithClassName (script.js:1338:37)
    at avideoModalIframe (script.js:1285:5)
    at addNewCategory (mediawall.infn.it/:677:45)
    at HTMLButtonElement.onclick (mediawall.infn.it/:407:115)

The variable is defined globally by the configuration.php file under Encoder/videos and is correctly seen in other context. We noticed that script.js experienced lots of changes/improvements, so it could be the case that along these modifications, something happend.

**Desktop:**
 - Windows 10
 - Browser: Chrome/Edge

Thanks in advance for the feedback,

Marco

**Comment by DanielnetoDotCom** [comment]
Thanks, fixed
