### ISSUE TITLE
Auto Verify Mail 2-3 Time Per Sec

### ISSUE THREAD

**Issue by DemonRem** [WWBN/AVideo#6240]
hey guys 
today i finished the configration of the website but i have a small error
with the mail verification after some testing i create 3 user each mail for example
mail1.gmail.com
mail2.gmail.com
mail3.gmail.com
each of my emails accept between 2-4 verification mail after signup
so its can be very confus i using Mailgun Platform for the website.

**Comment by DanielnetoDotCom** [comment]
are you running the latest git pull?

we recently fixed a similar issue

**Comment by LievreAI** [comment]
i run AVideo 11.5
and the website say "Your System is up to date"

**Comment by DanielnetoDotCom** [comment]
Again, make a git pull and try again

**Comment by LievreAI** [comment]
did it and now the webpage not even start HTTP ERROR 500

**Comment by DanielnetoDotCom** [comment]
Check your avideo.log

**Comment by LievreAI** [comment]
its not createing any log

**Comment by LievreAI** [comment]
in the edge i see error ERR_CONNECTION_TIMED_OUT
its like he stopped working but the apache2 in the ubuntu still working
check the site : http://www.rsvideos.tv

**Comment by LievreAI** [comment]
ok solved it

**Comment by DanielnetoDotCom** [comment]
I see, and now I see what is your site. the multiple emails should not happen.
