### ISSUE TITLE
Added categories are not shown in the list

### ISSUE THREAD

**Issue by mcorvo** [WWBN/AVideo#6241]
Dear Daniel,

working on the issue with the "+" button (https://github.com/WWBN/AVideo/issues/6239#issuecomment-1027935544), I probably came across another one. When adding new categories, the categories are not shown in the list, although the count is correct. I keep seeing a "Default" category, but the table says "Showing 1 to 4 of 4 entries". And indeed the entries are correctly inserted in the DB.

**To Reproduce**
1. Go to the Encoder or click on the "categories" button of the admin menu on the left
2. Click on "add new category" and fill the blanks
3. Save the newly created category
4. Refresh the page

**Expected behavior**
You should see the newly created categories in the list, but this is not happening

**Screenshots**

![image](https://user-images.githubusercontent.com/9268893/152184087-58bc273d-27fa-4a23-a54a-7b36de92d015.png)

![image](https://user-images.githubusercontent.com/9268893/152184516-77450d28-a4b2-418e-82a4-4f55aa290e12.png)

**Desktop:**
 - Windows 10
 -  Chrome, Edge

Thanks in advance for you support,

Marco

**Comment by DanielnetoDotCom** [comment]
Just for testing, can you log off and log in again?

can you check if the category was added on the streamer site?

can you clear the streamer cache?

**Comment by barrunning** [comment]
I have the same issue. I can add a new category. It shows up in other places but the list.
![72B543A2-0FEB-4ED7-97F4-6EA410E4B04B](https://user-images.githubusercontent.com/58601786/152209494-2f36fb99-e312-460b-a238-5791760127c0.jpeg)

**Comment by barrunning** [comment]
The new category does show on the up on the streamer site.

**Comment by mcorvo** [comment]
Dear Daniel,

I made some further tests following your advices. The only way to make the list show the correct content is by using the "clean cache directory" button. I tried to logoff and logon again, clear navigation data via Chrome but nothing happend. Only the internal "clean cache directory" works fine. 

Marco

**Comment by DanielnetoDotCom** [comment]
Please try this update.
