### ISSUE TITLE
User group restrictions not working

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6243]
User is in a user group that has no videos assigned to it. But upon log in they are able to view videos that are in a user group.

**Comment by DanielnetoDotCom** [comment]
Please check if your ppv plugin or subscription if you are not allowing watch with ads 

also check your logs

**Comment by barrunning** [comment]
Videos are not being restricted to a user group. I put all the videos in one user group. Then I assigned a user to a different group with no videos assigned. They have access to all the videos. Even when the category is assign to that user group. The user not assign can still see all the videos.

**Comment by DanielnetoDotCom** [comment]
Please screenshot the parameters from subscription and pay-per-view plugins

**Comment by barrunning** [comment]
![03693A88-8930-4EFE-9428-D4DDC02DAFFC](https://user-images.githubusercontent.com/58601786/152269147-3319067f-6c35-4c05-a305-b88430316571.png)
![B38D5406-0FDF-42CF-B0B4-B3ECD68DC547](https://user-images.githubusercontent.com/58601786/152269160-9e77fdb4-9d0b-4e96-839a-362038254b58.png)
![E43DBC8C-2566-4CFA-90EC-73322C6A2190](https://user-images.githubusercontent.com/58601786/152269161-860bb294-6b83-4d6f-8772-2b9f4a8a8b42.png)

**Comment by DanielnetoDotCom** [comment]
Ok, I do not know, please also share a user that does not suppose to see the video I will investigate it.

**Comment by barrunning** [comment]
Adminbarr same password

**Comment by barrunning** [comment]
In reality that user is in a group with no videos assigned to it.

**Comment by barrunning** [comment]
There is a video T Harris upload test that is a Ppv video. It plays.

**Comment by barrunning** [comment]
Disk quota is the issue. Turned off the Ppv, subscription and disk quota plug ins. Enabled Ppv, and restrictions are work and Ppv is working. Enabled subscription plug in and everything still work. Enable disk quota and full access is available to all users regardless of user group status.

**Comment by DanielnetoDotCom** [comment]
Thanks, I just sent you an update for DiskUploadQuota, can you please check if it is fine now?

**Comment by barrunning** [comment]
The plug in update script isn’t running. I have no idea how to update manually.

**Comment by DanielnetoDotCom** [comment]
It is updated on your site, I have sent them for you

**Comment by barrunning** [comment]
The plug in is 1.7 and turning on disk quota is giving access. It indicates there is an updated available but clicking on it takes you to youphp.tube/marketplace

**Comment by DanielnetoDotCom** [comment]
Sorry please try now.

but FYI if you login on marketplace you should be able to download the new plugin version

**Comment by barrunning** [comment]
Works great!
