### ISSUE TITLE
movie resolution

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6247]
How to enable the selection of the playback resolution of the movie ?
240p
360p
480p
720p

**Comment by jengajenga** [comment]
Get plugin from the marketplace.

Video Resoluton switcher or someting like that

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/WWBN/AVideo/wiki/About-Video-Upload#automatic-resolutions-default-and-recommended
