### ISSUE TITLE
Customize Encoder page

### ISSUE THREAD

**Issue by ecesarini** [WWBN/AVideo#6248]
**Describe the question**
Is there a way to customize, or add some code to Encoder page?
I would like to hide logoff button and you easily can do it with js but it seems that plugins' files or HEAD code additions are not loaded in the encoder page.

**Comment by DanielnetoDotCom** [comment]
Hi

currently, there is no such option, but you can try to pass the noNavbar parameter 

`https://yourEncoderURL.com?noNavbar=1`
