### ISSUE TITLE
[Upload]Mp4 Video Error

### ISSUE THREAD

**Issue by LievreAI** [WWBN/AVideo#6249]
hey guys it's kind odd to explain the error

![4](https://user-images.githubusercontent.com/84988313/152455854-6e369304-423e-46d5-879c-ab1e514c0e9a.png)

no log error too

**Comment by DanielnetoDotCom** [comment]
Looks like your apache/php is not allowing upload.

I am not sure how can you fix it. but check the apache error.log

**Comment by LievreAI** [comment]
ok i will check it thanks daniel
