### ISSUE TITLE
Viruses in Plugins

### ISSUE THREAD

**Issue by DrDoug88** [WWBN/AVideo#6252]
I went to update a few of the plugins, and they are generating virus warnings with Windows Security antivirus:

**Chat2 (https://youphp.tube/marketplace/downloadPlugin/31):**

![image](https://user-images.githubusercontent.com/80653458/152526337-07a3f7ec-2827-4dc4-a9d9-ab04cd53a461.png)

**MP4ThumbsAndGif.zip (https://youphp.tube/marketplace/downloadPlugin/6):**

![image](https://user-images.githubusercontent.com/80653458/152526619-7fc2aec7-f103-49a9-87f4-7ba9453e6f83.png)

Can you please look into this? I was able to download some other plugin updates, such as VideoResolutionSwitcher, VideoHLS, SendRecordedToEncoder, Notifications, and LiveUsers without anything being detected. However, I'm not sure I should install them just yet until this issue is resolved.

**Comment by DanielnetoDotCom** [comment]
I can guarantee there is no virus into the plugins, it is complaining because the plugins are encoded / obfuscated 

you may want to disable your antivirus

**Comment by DrDoug88** [comment]
I honestly do trust you Daniel. I just want to make sure the file server didn't gat hacked. You might consider posting checksums of the releases, just to add that layer of confirmation.

**Comment by DanielnetoDotCom** [comment]
I see

as long as you download from the marketplace there is nothing to worry about.

**Comment by JoshWho** [comment]
Microsoft does this to keep their monopoly alive. Files are safe, I recommend using Avast if you are on windows. Anything Microsoft is designed to spy on you and everything you do. I am not kidding about that.

**Comment by Maikuolan** [comment]
Not all anti-virus solutions are equal, and not all of them are reliable as all others. Personally, I would classify Windows' anti-virus solutions are being more on the less reliable end of the spectrum.

However, when in doubt, I would strongly recommend checking files against [Virus Total](https://www.virustotal.com/gui/home/upload). Although their service isn't something you can install, and will check only the files you upload to their service for that purpose, I would still strongly recommend keeping them bookmarked at your browser, for when in doubt. Their service will check files against more than 60 different anti-virus engines, and you can then compare the results of scanning the files you sent them between the various anti-virus engines used, to get a stronger "consensus" about whether the files are infected by anything, whether a engine might be generating false positives for the file, etc and etc.
