### ISSUE TITLE
Zoom webhook

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6253]
Where do I find the endpoint url? 
![46E9EA6F-50CB-425E-A3C6-3413955A2B42](https://user-images.githubusercontent.com/58601786/152534626-76a02cec-0214-4ea1-81f2-fb8047d07d41.jpeg)

**Comment by DanielnetoDotCom** [comment]
Hi

you can find it in your site plugin

![chrome-capture (5)](https://user-images.githubusercontent.com/18009293/152545193-f84acd45-b040-4af6-a21a-734a66b872b7.gif)
