### ISSUE TITLE
Single device log in doesn’t log off mobile

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6255]
Log in control
When set to single device. If I log onto more than one computer it will disconnect the first computer.
If I log onto a mobile it device, it disconnects the mobile device but the mobile device will log back in.
![0166BD36-37AD-4617-BF2E-59ABB842652B](https://user-images.githubusercontent.com/58601786/152598746-42403837-92a1-4911-b835-35ee23391eb2.png)
![879341D0-7475-450A-8EB2-6E9099D8570D](https://user-images.githubusercontent.com/58601786/152598760-129c4809-2797-4bae-b430-94547d5452b8.jpeg)

**Comment by DanielnetoDotCom** [comment]
Are you referring to the mobile app?

if yes, you are correct, it does not disconnect the mobile app

**Comment by barrunning** [comment]
Ok. Got it. Thank you for the clarification.
