### ISSUE TITLE
Help with CDN - recharged to the wrong account

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6257]
Hi Daniel-

I have two accounts linked to youphptube.com, I was running my CDN from one account, when it ran out I accidentally recharged from the wrong account 🤦🏻‍♂️

User #3106 has the CDN running, but is out of $
User #3114 I just recharged $100 on, but can't add a pull zone (error: "The site does not belong to your user")

Can you please fix or otherwise advise how to do same?

**Comment by DanielnetoDotCom** [comment]
I will transfer the balance for you

**Comment by DanielnetoDotCom** [comment]
User #3106 has no CDN 

what is your domain name?

**Comment by DanielnetoDotCom** [comment]
I guess I found, your user is 3108 NOT 3106

please confirm

**Comment by walt93** [comment]
Sorry, you are correct it's user #3108.

**Comment by DanielnetoDotCom** [comment]
But I guess you are all set with the credits, correct?
