### ISSUE TITLE
Category listed on mobile app

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6258]
What controls categories being listed here? They are there for the admin but not for anyone else. 
![591A94F0-BAD3-4074-B99F-E97DC0B9BF0E](https://user-images.githubusercontent.com/58601786/152629654-377cc6e3-79c4-4c44-8d61-e3abc0dee086.jpeg)

**Comment by DanielnetoDotCom** [comment]
It is supposed to be the same as the site. 

but we only show categories with videos, if the category has no videos it will not show

**Comment by barrunning** [comment]
They have videos. As admin I see the categories. As a regular user I do not.

**Comment by barrunning** [comment]
![D92B11FE-A54F-47DC-84AA-317C21A54D6F](https://user-images.githubusercontent.com/58601786/152642833-419abe26-5d49-451f-9dc6-99516c9f042b.jpeg)

**Comment by barrunning** [comment]
Movementanalysissolutions.com is the one. Barrunningmovementanalysis.com has the categories listed on the mobile app.

**Comment by barrunning** [comment]
Ok. Categories belong to the user that created it. The same categories for the user show up on the streamer and mobile. There doesn’t seem to be categories are global.

**Comment by barrunning** [comment]
Got it solved. If users are restricted from changing categories then they can’t see them.
