### ISSUE TITLE
YPTSocket running on a second port

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6259]
I am trying to start YPTSocket on my other site which resides on the same server as my main site. While the main site is running on port 2053 I wish to run the other site on port 2054, however when I try to do that YPTSocket will still not load.

Is there anything in particular I need to do beside opening the port 2054 and changing the port number on the YPTSocket of my second site? How can I run multiple YPTSockets on the same server?
![Screen Shot 5782-06-04 at 12 56 13](https://user-images.githubusercontent.com/58882903/152639250-7f385b15-9136-4689-8b37-d0a2547d9b47.jpg)
![Screen Shot 5782-06-04 at 12 42 17](https://user-images.githubusercontent.com/58882903/152639252-a61ce5a9-57a7-49b5-8ce7-563ee0f81401.jpg)

**Comment by DanielnetoDotCom** [comment]
it should work with no problem.

you can try the same troubleshooting as we do on the regular port

https://github.com/WWBN/AVideo/wiki/Socket-Plugin#troubleshooting

**Comment by guymass** [comment]
I get this error after running the test.php on second terminal:
![Screen Shot 5782-06-04 at 17 46 25](https://user-images.githubusercontent.com/58882903/152648636-f6ad0c7a-bebe-45db-83d5-ce29fe5a96b0.jpg)

**Comment by guymass** [comment]
Fixing SSL cert I now get this trying port 2053:
![Screen Shot 5782-06-04 at 17 51 49](https://user-images.githubusercontent.com/58882903/152648810-b962f636-e3ca-4e88-96ce-fb351a696061.jpg)

**Comment by DanielnetoDotCom** [comment]
> I get this error after running the test.php on second terminal, this is running on the same port 2053:
> 
> ![Screen Shot 5782-06-04 at 17 46 25](https://user-images.githubusercontent.com/58882903/152648636-f6ad0c7a-bebe-45db-83d5-ce29fe5a96b0.jpg)

stop the socket before running it.

`...plugin/YPTSocket/stopServer.php`

**Comment by DanielnetoDotCom** [comment]
> Fixing SSL cert I now get this trying port 2053: ![Screen Shot 5782-06-04 at 17 51 49](https://user-images.githubusercontent.com/58882903/152648810-b962f636-e3ca-4e88-96ce-fb351a696061.jpg)
> 
> So its working now I had an SSL certificate issue, once I set the correct path it started working again, but now the socket on the main site stopped working so it seems only one of them can run at any given moment.

Port 2053 seems to be fine. bake sure you do not have a firewall blocking outside connections

**Comment by guymass** [comment]
We fixed it by changing line 70 on server.php to use ips.

The ip was hardcoded to 0.0.0.0, this should be actually configurable. Matheos is recommending that you should to make that configurable on the interface and not hardcoded to 0.0.0.0. Currently both are working but next git pull it will be overwritten. Here is what we changed:
![photo_2022-02-05 20 06 28](https://user-images.githubusercontent.com/58882903/152653603-eb8d05b1-af41-47c0-8436-35e51a71b62a.jpeg)

**Comment by DanielnetoDotCom** [comment]
Hi, I just added a server URI option

**Comment by guymass** [comment]
Excellant, much thanks. Closing this.
