### ISSUE TITLE
New idea 

### ISSUE THREAD

**Issue by toplive24** [WWBN/AVideo#6262]
Hello all 
I have a new idea 
Solution for ad a system where people can gain point for look the video where in every video have the AD and generate point and after people can charge point in money? 
I think that this system help for come much people 

Thsnk to all for the answer

**Comment by toplive24** [comment]
Hello Neto

I mean similar but who look video gain pount

Thank

**Comment by DanielnetoDotCom** [comment]
I see, so the points are not for the video owner, but for whoever is watching.

right now we do not have that

**Comment by toplive24** [comment]
Ok Neto but can to be a good solution for make come more people on the website
