### ISSUE TITLE
how to enable

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6263]
how to enable notifications about comments, likes ??
![belka](https://user-images.githubusercontent.com/93145787/152682205-20b840d5-a7f6-46cf-b378-45bbd069363e.png)

**Comment by DanielnetoDotCom** [comment]
the top notification bar is for live streams only.

for email notification, you can use this https://github.com/WWBN/AVideo/wiki/Notifications-Plugin

**Comment by KrzysioMisio** [comment]
OK thanks

**Comment by KrzysioMisio** [comment]
is there a plugin informing about new comments and likes?
just like youtube there is a bell

**Comment by DanielnetoDotCom** [comment]
No, not yet
