### ISSUE TITLE
Mobile Embed Plays stopped working

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6265]
Not sure what exactly is causing this, i can't inspect element on my phone. Doesn't do it on desktop just mobile. 

Here is a embed you can test https://speedtest.joshwho.net/test420.html

Seems like it is just happening with Mobile Chrome

**Comment by DanielnetoDotCom** [comment]
Just tested on iOS chrome and works fine

**Comment by JoshWho** [comment]
It is android is what I am seeing the problem on
