### ISSUE TITLE
Why is the MRSS Feed so slow to load

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#6269]
Why is the MRSS Feed so slow to load? It took over 15 to 30 minutes to load and it is causing problems with the Amazon Fire app.

I clean the first-page cache, but still a problem.

What should I do?

**Comment by DanielnetoDotCom** [comment]
You probably have too many videos, try to reduce the total of listed videos.

for example https://www.yourdomain.com/roku.json?rowCount=100

check this https://github.com/WWBN/AVideo/issues/6169

**Comment by CROSSMediaNet** [comment]
Okay...how to do that, so I can have a general idea for both Roku and Amazon...also, is there a way for live feeds as well?

**Comment by DanielnetoDotCom** [comment]
[just add ](https://github.com/WWBN/AVideo/issues/6169#issuecomment-1012130850)

**Comment by CROSSMediaNet** [comment]
Okay...can this be done with Amazon as well?

**Comment by DanielnetoDotCom** [comment]
yes it may work on any feed

**Comment by CROSSMediaNet** [comment]
Okay...will do that...it was giving an error message about the video playback on the Amazon Fire app...I will try with Roku as well...can Roku pick up the live streaming or we don't have that option, yet?
