### ISSUE TITLE
GPU Encode

### ISSUE THREAD

**Issue by Allesanddro** [WWBN/AVideo#6271]
GPU Encode 
ffmpeg  -i \/media\/home\/html\/AVideo-Encoder\/videos\/183_tmpFile.mp4  -vf scale=-2:240  -preset p5 -vcodec hevc_nvenc -acodec aac -strict -2 -b:a 128k  -max_muxing_queue_size 1024 -y \/media\/home\/html\/AVideo-Encoder\/videos\/avideoTmpFile_183_streamers_id_4__240.mp4
works fine if i run it from terminal

But running it via the encoder ffmpeg fails with exit code 2 
any ideas?

**Comment by DanielnetoDotCom** [comment]
Sorry I really do not know. maybe apache does not have access to this hardware

check apache log also syslog

**Comment by Allesanddro** [comment]
nothing there

**Comment by DanielnetoDotCom** [comment]
can you please share the log around when the FFmpeg fails?

**Comment by Allesanddro** [comment]
[avideo.log](https://github.com/WWBN/AVideo/files/8023702/avideo.log)

**Comment by Allesanddro** [comment]
the gpu I use is a 1060 6GB on 495-dkms (tried other drivers aswell) cuda sdk is installed and also stated in the PATH

**Comment by DanielnetoDotCom** [comment]
from the log, the encoder seems to be working

the only error is on resolution 240p, what is not a big deal

**Comment by Allesanddro** [comment]
![image](https://user-images.githubusercontent.com/23656101/152987932-58fd36c9-c56b-466a-bf80-378c019c527d.png)
its stuck there cuz ffmpeg crashes even with 240p disabled

**Comment by DanielnetoDotCom** [comment]
I cannot see a crash on the log. 

please check apache log or syslog

**Comment by Allesanddro** [comment]
there is nothing in apache or syslog in relation to ffmpeg

**Comment by DanielnetoDotCom** [comment]
again, there is no crash on the log.

I cannot help you with no clue.

**Comment by Allesanddro** [comment]
alright thanks ^^

**Comment by Allesanddro** [comment]
Found the Issue it's cause of a NVIDIA POLICY that you cant transcode with consumer gpus :) there is a patch for that https://github.com/keylase/nvidia-patch
