### ISSUE TITLE
Ldap plugin periodically synchronize new from AD users and groups

### ISSUE THREAD

**Issue by KaMaToZzz** [WWBN/AVideo#6273]
Good afternoon!

Can you please tell me if you produce paid improvements for version 8 of the portal?

We need to extended functionality of the ldap plugin or have a way to periodically synchronize users and groups.:
Created groups in AD, had access only to the same created group of users in VideoPortal.
For the plugin to be able to synchronize users in the SIMPLE group with the SIMPLE group in the portal.
For the plugin to be able to map the users of the group in AD to the users of the groups created in the portal or import them into the portal.

If it is possible to implement such a plugin, please tell me the price of this development.

**Comment by DanielnetoDotCom** [comment]
Hi, 

yes, you can hire me for development.

this will probably require to test in your environment.

if you need a quote please email me at developer@youphptube.com

I just need to make clear that everything I develop I will keep the rights to resell or incorporate on the main project.

**Comment by nguyentienthu** [comment]
Its price is lifetime or monthly use.

**Comment by DanielnetoDotCom** [comment]
lifetime
