### ISSUE TITLE
Seeing disabled users in notification

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6274]
Hi @DanielnetoDotCom 

I hope you're well.

I'm seeing users I disabled still appearing in the notification tab. Very latest git.

Restarted Nginx but the notification bar remained 46 users - did not change or drop as it used to.

![banned](https://user-images.githubusercontent.com/65451390/153096513-ff13da96-817f-400b-a126-4b6341a45794.jpeg)

Cleared first page and directory cache, still have 46 users - no drop. However in the stat page, it shows they streams dropped and returning.

Part of the log file below

[09-Feb-2022 03:06:19 ] AVideoLog::WARNING: The plugin [Live::getLiveApplicationArray] takes 1.7085 seconds to complete. URL: https://www.mysite.com/view/iframe.php?type=log IP: xxx.xxx.200.234 SCRIPT_NAME: /view/iframe.php
 [09-Feb-2022 03:06:19 ] AVideoLog::DEBUG: getImage: [60755313b36db, 1] is live and ready SCRIPT_NAME: /view/iframe.php
 [09-Feb-2022 03:06:19 ] AVideoLog::DEBUG: getPoster(30, 1, ) SCRIPT_NAME: /view/iframe.php
 [09-Feb-2022 03:06:19 ] AVideoLog::DEBUG: isLiveAndIsReadyFromKey the m3u8 file is not present https://www.mysite.com:9998/live/xxx/index.m3u8 SCRIPT_NAME: /view/iframe.php
 [09-Feb-2022 03:06:19 ] AVideoLog::DEBUG: wget: ERROR the url download but is empty https://www.mysite.com:9998/live/xxx/index.m3u8, /videos/cache/YPTurl_get_contents/39ae0660f9dad1fef3c4eba5097acc1e SCRIPT_NAME: /view/iframe.php
 [09-Feb-2022 03:06:19 ] AVideoLog::DEBUG: getPoster(29, 1, ) SCRIPT_NAME: /view/iframe.php
 [09-Feb-2022 03:06:19 ] AVideoLog::DEBUG: isLiveAndIsReadyFromKey the m3u8 file is not present https://www.mysite.com:9998/live/xxx/index.m3u8 SCRIPT_NAME: /view/iframe.php
 [09-Feb-2022 03:06:19 ] AVideoLog::DEBUG: wget: ERROR the url download but is empty https://www.mysite.com:9998/live/xxx/index.m3u8, /videos/cache/YPTurl_get_contents/bf21f1b9719901b05385e94c50251d1c SCRIPT_NAME: /view/iframe.php
 [09-Feb-2022 03:06:19 ] AVideoLog::DEBUG: getPoster(55, 1, ) SCRIPT_NAME: /view/iframe.php
 [09-Feb-2022 03:06:19 ] AVideoLog::DEBUG: isLiveAndIsReadyFromKey the m3u8 file is not present https://www.mysite.com:9998/live/xxx/index.m3u8 SCRIPT_NAME: /view/iframe.php
 [09-Feb-2022 03:06:19 ] AVideoLog::DEBUG: wget: ERROR the url download but is empty https://www.mysite.com:9998/live/xxx7/index.m3u8, /videos/cache/YPTurl_get_contents/a0422dba14e3932da8257c276138c1ae SCRIPT_NAME: /view/iframe.php

Thanks

**Comment by DanielnetoDotCom** [comment]
the error is not clear to me. 

there are some notifications that not supposed to be there anymore? but they still?

or is it supposed to show something and it is not showing?

**Comment by jengajenga** [comment]
> the error is not clear to me.
> 
> there are some notifications that not supposed to be there anymore? but they still?
> 
> or is it supposed to show something and it is not showing?

THanks @DanielnetoDotCom 

There are some notifications that are not supposed to be there anymore. Like in the screenshot above, that client i disabled and deactivated. I restarted nginx but he's still there together with number 46. In the stat page, i have 40.

**Comment by jengajenga** [comment]
![actual live](https://user-images.githubusercontent.com/65451390/153145172-9b5750b9-3271-4e30-a385-47fdd29d80d1.jpeg)
Above is the actual number of streams on stat page

![notificatioins](https://user-images.githubusercontent.com/65451390/153145222-8e2efeba-2dbf-4745-87bd-40c6a6745277.jpeg)
This here is the corresponding notification number

**Comment by DanielnetoDotCom** [comment]
do you have any scheduled?

can you confirm if there is any duplicated?

is it showing lives that already finished?

**Comment by jengajenga** [comment]
> do you have any scheduled?
> 
> can you confirm if there is any duplicated?
> 
> is it showing lives that already finished?

1. No scheduled lives
2. No duplications
3. Well, yes. The screenshot of the email address i sent above

It is even worse on the app. I have 87 streams, but only 41 on stat page.

**Comment by DanielnetoDotCom** [comment]
I am more confused now. 

on the stats page, you have 41 lives

on the notification bell you have 49

where are the other lives?

**Comment by jengajenga** [comment]
> I am more confused now.
> 
> on the stats page, you have 41 lives
> 
> on the notification bell you have 49
> 
> where are the other lives?

Haha exactly my dilemma. There are NO other lives. Which is also confusing me. 

I think there's an error in what the notification is reading.

Right now Nginx=39, Notification=45

Then a new streamer joined and it became Nginx=40, Notification=46.

**Comment by jengajenga** [comment]
Looks like the formula for notifications is Nginx+6

**Comment by jengajenga** [comment]
I have restarted nginx and the notifications didn't drop as they should. it stayed at the 44 even as nginx was rebooting and returning the livestreams

**Comment by DanielnetoDotCom** [comment]
Restart will not drop the lives on the notifications, but you can finish them on the live plugin 

the thing is , the +6 lives , what are they?

1. duplicated lives? 
1. Finished lives?
1. Schedule lives?


You need to check where they come from

**Comment by jengajenga** [comment]
> Restart will not drop the lives on the notifications, but you can finish them on the live plugin
> 
> the thing is , the +6 lives , what are they?
> 
> 1. duplicated lives?
> 2. Finished lives?
> 3. Schedule lives?
> 
> You need to check where they come from

@DanielnetoDotCom , there are NO scheduled lives. There is one that has REFUSED to go.  The rest are all there as they should be. 

But there is this case

![user-1](https://user-images.githubusercontent.com/65451390/153461360-6d149b4b-80f1-473f-be4c-a780706d558a.jpeg)

![user-2](https://user-images.githubusercontent.com/65451390/153461398-c80f364c-f84a-4ae4-8e97-057ac6c7c97e.jpeg)

i disabled that account long ago but he still shows up on the front page. 

On the app it is worse. It seems everyone who has ever streamed before is shown as a streamer but offline. I have disabled

**Comment by DanielnetoDotCom** [comment]
Hi, inactive users do not suppose to be able to do lives. I will review it.

**Comment by DanielnetoDotCom** [comment]
I just review it and I could confirm inactive users cannot stream. 

are you running the latest `git pull `version?

**Comment by jengajenga** [comment]
doing git fetch brings this

30a7bdef4..a682024a2  master

do i do an update?

> I just review it and I could confirm inactive users cannot stream.
> 
> are you running the latest `git pull `version?

**Comment by DanielnetoDotCom** [comment]
can you please copy here the full command and the resulting output?

**Comment by jengajenga** [comment]
> can you please copy here the full command and the resulting output?

remote: Enumerating objects: 106, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 106 (delta 76), reused 38 (delta 8), pack-reused 0
Receiving objects: 100% (106/106), 53.80 KiB | 26.90 MiB/s, done.
Resolving deltas: 100% (76/76), done.
From https://github.com/WWBN/AVideo
   30a7bdef4..a682024a2  master     -> origin/master

**Comment by jengajenga** [comment]
That is the "git fetch" command

**Comment by DanielnetoDotCom** [comment]
the command should be not just git fetch, but ...

`sudo git fetch --all && sudo git reset --hard origin/master`

**Comment by jengajenga** [comment]
> the command should be not just git fetch, but ...
> 
> `sudo git fetch --all && sudo git reset --hard origin/master`

when i update i do sudo git stash && sudo git pull. I don't d reset because it overwrites some custom changes.

do i have to do git reset --hard everytime i update?

**Comment by DanielnetoDotCom** [comment]
That is what I am suspecting, your custom changes may be causing it.

also you are not able to get updates from me since you are not running my version anymore

**Comment by jengajenga** [comment]
> That is what I am suspecting, your custom changes may be causing it.
> 
> also you are not able to get updates from me since you are not running my version anymore
@DanielnetoDotCom , I think we are misunderstanding each other here

The custom changes are small changes eg on the notification bell, i have changed it to a video instead of a bell. I have also added the word "live channels" near the bell - html changes. Not changes that affect how the system runs.

I update using sudo git pull which pulls in the latest version at the time. I always update 8 hours or so after the latest git.

There is a bug in the notifications, I have mentioned it several times from disappearing channels to duplicate channels now disabled channels still appearing, as well as having a different number in the stat page compared to the notifications. It has nothing to do with my custom html changes.

The version I am running is 11.5, git 30a7bdef4

As we speak i have notification=48, nginx=42

**Comment by DanielnetoDotCom** [comment]
I can only help you if you are running the exactly same version as me

**Comment by jengajenga** [comment]
> I can only help you if you are running the exactly same version as me

@DanielnetoDotCom this is the problem, forget the version as the version I'm running is the same as yours.

Notification = 45
Nginx = 39

Where are the extra 6 coming from?
If Nginx has LESS than the notifications, the where are the extra 6 being pulled from since they are NOT passing through Nginx?

**Comment by jengajenga** [comment]
@DanielnetoDotCom have you looked at this further?
