### ISSUE TITLE
Autostart Subtitle plugin

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#6275]
Is there a toggle to autostart subtitle when video starts playing ?

**Comment by DanielnetoDotCom** [comment]
I guess the `defaultSubtitleLanguage`  should auto start the subtitle

<img width="746" alt="image" src="https://user-images.githubusercontent.com/18009293/153492271-3d4c610d-605e-49af-be7a-56944d2fc026.png">

**Comment by TLCReuver** [comment]
I have this already enabled, user location enabled & IP tables installed but when playing "**subtitles off**" are selected by default.

![Snap5](https://user-images.githubusercontent.com/39981177/153573525-e0169a4c-3350-4bba-93ba-754c4f53d882.jpg)

![Snap6](https://user-images.githubusercontent.com/39981177/153573637-15b9cb5e-2801-40da-8f11-c36457c8f25c.jpg)

![Snap7](https://user-images.githubusercontent.com/39981177/153573898-98cb15cd-9933-49f1-9840-e0b4f0dc9b8e.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, what is the complete file name for the Dutch vtt file?

**Comment by TLCReuver** [comment]
These files are in the folder video_460902115900_vcf5a
(46 = This video is from 1946)

![Snap5](https://user-images.githubusercontent.com/39981177/153633022-ebc4be2d-2616-4a38-9be5-9a55e1af5af3.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, as the default subtitle please try `nl_NL`
