### ISSUE TITLE
Managing multiple encoders with Network Encoder

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6278]
In simple terms my issue is a bit annoying and probably has a simple solution. What happens is that I have two encoders running under Network Encoder and in order to view and manage the queue I need to open each on of them separately from each domain site, in order for me to be able to view the list of files currently in the queue. While im using the same user with admin credential, while i am opening it from one site I am not able to view or manage the files on the other encoder and vise versa.

Here are screen shots of how it appears to me.
This is the files in queue on second encoder while it is selected and I opened the window from that domain, I can manage the queue

![Screen Shot 5782-06-12 at 19 25 02](https://user-images.githubusercontent.com/58882903/153767079-125db9b6-d0ec-4c57-b6cb-6963c49872d3.jpg)

However, while in the same page, selecting the first encoder I only see the process queue but not the management queue where I can refresh or delete files.

![Screen Shot 5782-06-12 at 19 25 15](https://user-images.githubusercontent.com/58882903/153767166-7c1a2e41-e900-44b1-b4e2-998e9ebe076a.jpg)

It would be awesome if I didn't have to close and reopen the tab each time I wanted to switch between encoder queue management.

**Comment by DanielnetoDotCom** [comment]
Hi, you must make your user an encoder admin

```
cd /var/www/html/AVideo/Encoder/install
php makeAdmin.php
```

Enter the username and enter.

**Comment by guymass** [comment]
I dont have that file
![Screen Shot 5782-06-15 at 22 13 12](https://user-images.githubusercontent.com/58882903/154349228-3a766fbd-558b-403a-bdf0-353136f3c111.jpg)

**Comment by guymass** [comment]
Cool!! all working now. Finally I can manage them in a single location, much thanks.
