### ISSUE TITLE
Live Notification button hide

### ISSUE THREAD

**Issue by partystreamsk** [WWBN/AVideo#6279]
Hi, how can i hide notification button on top bar? check screenshot, thanks
![issue3](https://user-images.githubusercontent.com/50631455/153767736-96882126-df51-41d3-be2e-f3c8b4593cf5.png)

**Comment by DanielnetoDotCom** [comment]
You can add a custom CSS

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript

or you can check this

![image](https://user-images.githubusercontent.com/18009293/153853259-1803952a-7e20-4178-96ed-1442150cbb3e.png)

**Comment by partystreamsk** [comment]
Thank you for your reply but "do not show notifications" will not hide sheduled lives and live links. So will be great if you add this possibility to hide also for sheduled + live links in option. Or option to hide it completly. Thanks
![shedule](https://user-images.githubusercontent.com/50631455/153878741-3f5cb392-3955-4ec2-a35e-a64a3418f053.png)
