### ISSUE TITLE
Redirect domain to sub folder

### ISSUE THREAD

**Issue by davidjmaxey** [WWBN/AVideo#628]
Is there a simple way to silently redirect the main domain (which points to the apache default index) to the YouPHPTube sub folder on ubuntu?

**Comment by ChrisSlS** [comment]
Check this : https://www.digitalocean.com/community/tutorials/how-to-move-an-apache-web-root-to-a-new-location-on-ubuntu-16-04

**Comment by davidjmaxey** [comment]
ended up creating a .htaccess in the /var/www/html directory and drop the following which seems to work great.

RewriteEngine On
RewriteRule !^YouPHPTube/ /YouPHPTube%{REQUEST_URI} [L,R=301]

**Comment by hersche** [comment]
whats the idea behind this?

why not just move the subdirectory to the root-directory?

**Comment by DanielnetoDotCom** [comment]
I like to use virtual Apache hosts
