### ISSUE TITLE
New comment in email notification

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#6281]
Can all new comments contents go into the email notification? Right now you have to click on the link to go see the comment on the web page.

**Comment by JoshWho** [comment]
You mean a way to put the text of the comment inside of the email notification so u do not have to go to the webpage to view it. 

Could be possible but needs to limit the number of characters, Some people pay super high bulk email fees and the less text the simpler.

**Comment by fakeologist** [comment]
Yes that's what I mean.

**Comment by fakeologist** [comment]
@DanielnetoDotCom any update?

**Comment by DanielnetoDotCom** [comment]
I will update it in the future, but right now I am engaged in something else.

**Comment by fakeologist** [comment]
Great stuff. What new things are planned?

**Comment by DanielnetoDotCom** [comment]
Is hard to describe everything I am doing, but right now I am working on an affiliate profile. where users can affiliate to other users (companies) and all published content from the affiliated users will be connected on the main "company" account.

**Comment by fakeologist** [comment]
Can you bump this Daniel? Sometimes I get comment notifications and I can't find the comment when I click on the link. If I could see the actual comment in the email I would know what to look for.

**Comment by DanielnetoDotCom** [comment]
I will review it, but I am moving this next couple of weeks, so there will be no development during this time.

only emergency updates.
