### ISSUE TITLE
Translation of variable text

### ISSUE THREAD

**Issue by partystreamsk** [WWBN/AVideo#6282]
Hi, how can i add a translation of this texts in placeholders? thanks
![vartran](https://user-images.githubusercontent.com/50631455/153782119-b680c1be-0c19-4c01-8f20-556333bfe245.png)

**Comment by DanielnetoDotCom** [comment]
First, you need to check on the source code if the text is translatable. if it is you can add the translation on the lang file

this is old but may help you understand

https://github.com/WWBN/AVideo/wiki/How-to-translate-AVideo-Platform-to-your-idiom-using-google-translate

**Comment by partystreamsk** [comment]
Thanks, im translating site using php files in /locale folder . This are variables and i tried to add 
$t['Subscribe to watch all our videos'] = "Bla bla bla"; but was not working. Its there any way to add translation to this variable text?  Or any other solution? thanks
