### ISSUE TITLE
Channel RSS feed is pulling main site Description

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6283]
![bf375f2f-607f-4e16-b292-891d304ecc7e](https://user-images.githubusercontent.com/39392449/153788312-a82cbcdf-d879-49e2-a757-d5de80393b24.png)

**Comment by DanielnetoDotCom** [comment]
This update should give you the correct description.

FYI, this update will remove the HTML tags from the user's channel about section.

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom  updating it now

**Comment by JoshWho** [comment]
I confirm it works great now
