### ISSUE TITLE
VideoLogoOverlay Issue

### ISSUE THREAD

**Issue by karlkunc** [WWBN/AVideo#6284]
**Describe the bug**
Clicking on "edit Parameters" does not open another window. Won't upload image. Won't save. 

**To Reproduce**
1. Go to plugins
2. Click on videologooverlay edit parameters
3. nothing happens

**Error Logs**
Provide the log files at the moment you found the issue.
If you are not sure how to find the log file, please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome

**Smartphone (please complete the following information):**
 - Device: samsung s10

 - Browser [e.g. stock browser,

**Additional context**
php 8.1

If I do an inspect of the edit logo window this is what is shown as errors.

![Untitled](https://user-images.githubusercontent.com/74743076/153996450-fc067538-d64c-4931-a84f-37e866b5d568.png)

**Comment by DanielnetoDotCom** [comment]
You were right, here is an update with a fix
