### ISSUE TITLE
Ordering from web using Android phone

### ISSUE THREAD

**Issue by Rfkhky** [WWBN/AVideo#6287]
Hi, Daniel I'm trying to order things using my Android phone and the shopping cart is in the way of my login screen. I can see the login screen, behind the shopping cart, but can't access it because the cart will not minimize or move out of the way.
![Screenshot_20220215-194030](https://user-images.githubusercontent.com/99774107/154176595-32616792-5cc5-47a9-9cad-985b5f734adf.png)
![Screenshot_20220215-194059](https://user-images.githubusercontent.com/99774107/154176597-a01a5f0f-4aeb-40da-92d5-d07f428a9ec3.png)

**Comment by DanielnetoDotCom** [comment]
I am so sorry but now I understand what do you mean.

you are, correct, this site is only designed for PC.

anyway, after the purchase you will need to access it from the PC so you can download the plugin file.

can you please try it from PC?

If you cannot, please let me know, and I will try to improve it this week

**Comment by Rfkhky** [comment]
Thanks, but I am able to use a PC, so no need to rush to fix. I will order and would like you to install on our in-house servers. I have the main server and then an encoder available for you to configure. I will purchase, as before, and have you install.

-Bob

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

------- Original Message -------
