### ISSUE TITLE
 AVideoLog::ERROR: Live::getStatsObject RTMP Server (https://www.mysite.com:8443/stat) is OFFLINE

### ISSUE THREAD

**Issue by nikstream** [WWBN/AVideo#6288]
Hi Daniel,
I am getting this error repetitively in my log

16-Feb-2022 00:02:09 Asia/Dili] AVideoLog::ERROR: Live::getStatsObject RTMP Server (https://www.mysite.com:8443/stat) is OFFLINE, timeout=(4) we could not connect on it => live_servers_id = (0)  SCRIPT_NAME: /view/index.php

[16-Feb-2022 00:40:01 Asia/Dili] AVideoLog::ERROR: Live::getStatsObject RTMP Server (https://www.mysite.com:8443/stat) is OFFLINE, timeout=(4) we could not connect on it => live_servers_id = (0)  SCRIPT_NAME: /view/index.php

16-Feb-2022 01:09:19 Asia/Dili] AVideoLog::ERROR: Live::getStatsObject RTMP Server (https://www.mysite.com:8443/stat) is OFFLINE, timeout=(4) we could not connect on it => live_servers_id = (0)  SCRIPT_NAME: /view/index.php

what would be the reason

![errorlog](https://user-images.githubusercontent.com/58296408/154203197-a2272f95-1856-4539-8e3c-70d1a5b79763.JPG)

**Comment by DanielnetoDotCom** [comment]
Do you have the Nginx RTMP installed?

what is the stats URL?

**Comment by nikstream** [comment]
Yes Nginx Rtmp is installed
![stats](https://user-images.githubusercontent.com/58296408/154278769-93eff313-25c0-4022-aab2-d54ba735856d.JPG)

**Comment by nikstream** [comment]
![log](https://user-images.githubusercontent.com/58296408/154279389-83a7fbaa-ec31-45e0-88f1-0ecf6c602343.JPG)

**Comment by DanielnetoDotCom** [comment]
for some reason, your server could not reach the stats page.

but I can see on the test it is working.

try to delete the log file and check if the error persists

**Comment by barrunning** [comment]
I get the same thing.

**Comment by DanielnetoDotCom** [comment]
@barrunning your Nginx was not running, I suspect that was the problem

to start the Nginx I did run `sudo /usr/local/nginx/sbin/nginx`
