### ISSUE TITLE
YPTSocket gets stuck on 100% and I need to restart apache

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6289]
At certain times this happens, so we set a cron job to restart YPTSocket once an hour, but sometimes this happens anyway. Here is an uploaded file with section of the error log file, maybe you can see there what is causing this issue.
[slow_problem.txt](https://github.com/WWBN/AVideo/files/8083195/slow_problem.txt)

**Comment by DanielnetoDotCom** [comment]
Hi

looks like it is a problem with MySQL

`Error in writeSql : (1205) Lock wait timeout exceeded`

Did you run this?

https://github.com/WWBN/AVideo/wiki/Speed-up-your-page#mysqltuner-script

make sure you run the mysqltuner multiple times

**Comment by guymass** [comment]
OK thanks I have done these steps.
