### ISSUE TITLE
Stream works but is shown as offline and video is not received

### ISSUE THREAD

**Issue by ShrekisLyf** [WWBN/AVideo#6290]
Hi Daniel, you recently helped me fix nginx rtmp and it seems to work now! 
Now I got another slight error
The stats page as seen here 
![Screenshot_20220216-222750_DuckDuckGo](https://user-images.githubusercontent.com/63299919/154360156-739aa3bd-580c-421e-b69c-494251bcf15f.jpg)
Shows my stream being online, it also seems to be received according to the traffic in the streaming app

But despite that fact it shows as offline on the website and if it does seem to be online miraculously
There is an eternal loading time without video

I hope this is fixable I really enjoy your project!

**Comment by DanielnetoDotCom** [comment]
Hi

do you have the socket running?

https://github.com/WWBN/AVideo/wiki/Socket-Plugin

It is required for notifications.

Also make sure all on_* parameters are working

https://github.com/WWBN/AVideo/blob/2a45ce4af4fd00d0e17c75044c7f2b18beabdffe/plugin/Live/install/nginx.conf#L29-L32

**Comment by ShrekisLyf** [comment]
The socket server is now running with no errors, I also get a valid stream both on the rtmp app and the stats page
Still I get this 
![Screenshot_20220217-155831_DuckDuckGo](https://user-images.githubusercontent.com/63299919/154508586-87c58be8-f267-4214-a001-772a56be261b.jpg)
At least it is showing up on the page

**Comment by DanielnetoDotCom** [comment]
Check your avideo.log file 

also make sure you have the latest git pull

**Comment by ShrekisLyf** [comment]
Where is avideo.log stored?

**Comment by DanielnetoDotCom** [comment]
I can see this 

`Live::getStatsObject RTMP Server (http://skate.ppnews.eu:444/stat) is OFFLINE`

the stats should be https NOT http

in your Live plugin parameter change http://skate.ppnews.eu:444/stat to https://skate.ppnews.eu:444/stat

**Comment by ShrekisLyf** [comment]
Ah this really was the catch! I thank you!
