### ISSUE TITLE
About using Viloud for TV on Roku

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#6291]
I am trying to figure this out and I am very confused because of what Viloud support is saying and telling me.
Here's what I am trying to do on Roku with this application:

It seems to me that the .M3U8 links are not working as a live (on-the-air) with Roku. (What I am trying to do through Roku is the channels that have content to be 24/7 that Viloud provides a scheduler when using the HLS, which they recommended to be).

Here are some of their responses:
After checking your channel I noticed that the link video is like that "https://impstreamscom.cdn.ypt.me/videos/v_210929105004_705a/hd/index.m3u8" uses encryption (METHOD=AES-128). Our platform is not compatible m3u8 manifest with keys. Probably this setup can be changed on your video hosting, we can help if you need technical advice to change this. It depends on your video hosting provider, probably you can change the delivery setting options when you upload the asset. Or maybe this is an account-level setting. Let me know your provider to figure out these options, please. Viloud needs no encryption on HLS.

They took a minute to figure out what is going on and how (which was over 3 months), then they responded to my inquiry:

Thanks for contacting us.
Reviewing our last conversation It seems you didn't receive our answer.

Your manifest: https://impstreamscom.cdn.ypt.me/videos/v_211103185923_vcfd9/index.m3u8 is protected by AES encryption, that is not supported by m3u8 output. Keep in mind that the m3u8 signal is a merge of any manifest from different sources and it's not possible to track AES for each chunk.

Any suggestion? I tried a lot of options and I am running out of them, or there's a better what to run 24/7 through our platform?

**Comment by DanielnetoDotCom** [comment]
So, Roku does not support encryption?

all our HLS videos use encryption there is no way to remove it.

but maybe they can support encryption but they had no access to the encryption file. to allow external players to access your encryption file you MUST disable the download protection


![image](https://user-images.githubusercontent.com/18009293/154474359-fa56e320-7263-4d69-95e6-59f74e980bc6.png)

**Comment by CROSSMediaNet** [comment]
When I check on the VideoHLS, the download Protection was unchecked...I think it could be Viloud...on the website player it is working fine with the HLS, but with their player on Roku, it doesn't play from our site at all...let me check the download protection and see what happens

**Comment by CROSSMediaNet** [comment]
I can do that, but it eats up from the minutes allotment on their website,
which some would love to see content ongoing for 24/7, like a TV network

**Comment by DanielnetoDotCom** [comment]
The live is also an HLS but it is not encrypted.

for now I do not have the live feed for Roku but I may add this in the future
