### ISSUE TITLE
Video marked with a label buy or Ppv

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6295]
Is there a way to mark videos with a label that indicates it is a Ppv video? Currently user doesn’t find out until clicking on video that it is PPV.

**Comment by DanielnetoDotCom** [comment]
To see tags like that 

![image](https://user-images.githubusercontent.com/18009293/154961592-692c5d66-3eed-4806-a0ca-5b9f00c05947.png)


Make sure you have this option checked

![image](https://user-images.githubusercontent.com/18009293/154961713-68b4f442-28ba-4a56-bf72-e921a21d28a4.png)
