### ISSUE TITLE
hep

### ISSUE THREAD

**Issue by Fre68** [WWBN/AVideo#6297]
Hello, I installed your super script to make a gallery of Christian video.
But I need help
Everything was fine and here is now the message I placed a video:
Array (4) {["Type"] => int (1) ["Message"] => String (195) "Uncaught Error: Call to a Member Function GetFileName () On Array In / Home / RIMMQFT / www3 / view /modeyoutube.php:285 Stack Trace: # 0 /home/rimmqft/www3/view/index.php(50): Require () # 1 {Main} Thrown "[" File "] => String (39)" / Home / Rimmqft / www3 / view / moderyoutube.php "[" line "] => int (285)}
Frédéric

**Comment by DanielnetoDotCom** [comment]
what version did you install?

did you use git clone to get the files?
