### ISSUE TITLE
Live Mouse over poster + main poster timeout on homepage

### ISSUE THREAD

**Issue by partystreamsk** [WWBN/AVideo#6299]
**Describe the question**
Hi, where i can change timeout for request encoder MAIN POSTER and MOUSE OVER POSTER of live streams? 

Currently its about 15 minutes for MOUSE OVER POSTER and 10minutes for MAIN POSTER 

Also can you tell me what is time out for first page cache? i need to reduce it.

I wanna keep fresh posters + mouse over animation every 5 minutes, without need to clear cache everytime. So if somebody join site, than see poster + animation max 5 min old.

Thanks

**Screenshots**
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/50631455/155246540-8628bf89-c535-4dea-8124-4bd2d7ba798b.gif)

**Comment by DanielnetoDotCom** [comment]
you cannot change the timeout this is hardcoded

you can change the first-page cache timeout value here,

cacheTimeInSeconds

![image](https://user-images.githubusercontent.com/18009293/155322943-e6937d17-cd20-46e9-990a-5696224ec1b8.png)

**Comment by partystreamsk** [comment]
Even if i dont using cache plugin?
