### ISSUE TITLE
Program plugin creating serie with season and episodes

### ISSUE THREAD

**Issue by thiagoalecs** [WWBN/AVideo#6300]
How can i create a series with different seasons and episodes? 

I'm able to create the playlist with all videos from a season but i can´t create multiple seasons using same "fake video" in a category. There is a feature caled collection where i can add multiple playlists but i was not able do make it to display on my home page in a category. 

is there a way to do what i need?

**Comment by DanielnetoDotCom** [comment]
did you try this ...

# upload all the videos 

A) season 1 episode 1
B) season 1 episode 2
C) season 1 episode 3
D) season 1 episode 4

E) season 2 episode 1
F) season 2 episode 2
G) season 2 episode 3
H) season 2 episode 4

# then create 2 playlists for the seasons

## Playlist Season 1
- Video A
- Video B
- Video C
- Video D

## Playlist Season 2
- Video E
- Video F
- Video G
- Video H

after that make sure you transform the playlist into series

# then create another playlist with the 2 seasons

## My serie
- Season 1
- Season 2

it should work, at least on the flix layout but also may work on gallery mode

**Comment by thiagoalecs** [comment]
thank you,
 I was trying on gallery mode but wasn´t working, now i changed to flix mode and it is working fine! 

I appreciate your fast answer.
