### ISSUE TITLE
Change video with a specific one

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#6301]
Change video with a specific one
When you join your channel, all the videos it has uploaded are displayed.
But at the top you see a bigger one on first impression.
Is it possible to change this video by putting one of my choice?
Thanks for the replies

![0](https://user-images.githubusercontent.com/82677269/155560179-ea242305-8d40-44e3-8c80-e33cf5df72b3.PNG)

![1](https://user-images.githubusercontent.com/82677269/155561095-9a071163-a378-440b-951e-74d944119778.PNG)

![2](https://user-images.githubusercontent.com/82677269/155561129-72fcd045-bdfd-4ae1-90fd-93f7df9ff698.PNG)

**Comment by DanielnetoDotCom** [comment]
did you try to suggest a video?

![image](https://user-images.githubusercontent.com/18009293/155725193-f11fa2f8-3908-4c1f-a429-a601ff59a282.png)

**Comment by sharknetwork24** [comment]
No Daniel.  I mean on each user profile page.  I also put pictures for you to understand what I'm talking about.

**Comment by sharknetwork24** [comment]
Perfect thanks Daniel
