### ISSUE TITLE
Multiple stream keys from a single channel issue

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6302]
We have a channel which is live streaming and while the stream is running the system generates a new stream key. This channel is using this second stream key to re stream its first live but in an audio format to be used as internet radio.

The issue started in last update. Until that time we were able to see both of those stream on the front page and bell alert and now we only see the first main stream and not the secondary one.

My question is this, does the system generates new keys for a channel so they can have multiple live stream?

Also I want to find out why we no longer see that second live showing on the alert.

I don't see anything special in logs but I also not sure really what I should look for, any suggestions will be greatly appreciated.

**Comment by DanielnetoDotCom** [comment]
Hi, 

I am not sure exactly what or how you are doing but you may be able to have more than one key per channel

For example lets say your key is ...

609e8c0972d12-1

you can also use 

609e8c0972d12-2
609e8c0972d12-3
609e8c0972d12-abc
609e8c0972d12-whateveryouwant
609e8c0972d12-X
609e8c0972d12-etc

all of them should follow the default stream setting (publicity/auto-record/poster/etc)

and also should appear on the notification bell

**Comment by DanielnetoDotCom** [comment]
I just tested it locally with live keys 

609e8c0972d12-1 and 609e8c0972d12-2

and it works as expected

Are you running the latest?

![chrome-capture (1)](https://user-images.githubusercontent.com/18009293/156024116-84f16312-7fb6-4ca5-8f93-211b138be1ab.gif)

**Comment by DanielnetoDotCom** [comment]
NVM, I could reproduce it somewhere else.

I am checking...

**Comment by guymass** [comment]
What is the second stream is only audio from OBS?

**Comment by DanielnetoDotCom** [comment]
can you please try this last update?

**Comment by guymass** [comment]
Great!!! seems to be back and working fine now, we will keep you posted of any changes, much thanks.

**Comment by guymass** [comment]
Sorry one last question regarding this issue or basically related to it. How can we control the title of the second stream to be unique and not like the title of the first stream + (123...) in the end of the name. Is it possible to separate titles for each new stream?

**Comment by DanielnetoDotCom** [comment]
Just a question, did you try to use the schedule?

with the schedule you will have different keys and also you can have a title and a poster for each live

**Comment by guymass** [comment]
No, I haven't I will try that, thanks.
