### ISSUE TITLE
Connect Error (2002) php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#6306]
stuck on install
Connect Error (2002) php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution
![Untitled-1](https://user-images.githubusercontent.com/37937968/155801611-db726cbd-b7ce-49ff-b880-7285ec853211.png)
![Untitled-2](https://user-images.githubusercontent.com/37937968/155801614-a7c8ccfd-2187-482b-a116-7064a78f1dfb.png)

**Comment by DanielnetoDotCom** [comment]
can you please make a git pull?

I guess I already updated this address

**Comment by Lordblanca** [comment]
Already up to date

**Comment by DanielnetoDotCom** [comment]
Can you please check the Apache error log? So Incan see where the error comes from?

**Comment by Lordblanca** [comment]
My apologies on taking so long.
[Wed Mar 02 00:00:02.935432 2022] [mpm_prefork:notice] [pid 1320] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Mar 02 00:00:02.935473 2022] [core:notice] [pid 1320] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 02:44:31.162935 2022] [php7:error] [pid 43885] [client 146.70.25.68:60529] script '/var/www/html/xmlrpc.php' not found or unable to stat
[Wed Mar 02 04:14:18.991944 2022] [core:error] [pid 43882] [client 45.146.165.37:37774] AH00126: Invalid URI in request POST /cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1
[Wed Mar 02 18:53:26.869574 2022] [mpm_prefork:notice] [pid 1320] AH00169: caught SIGTERM, shutting down
[Wed Mar 02 18:53:27.041801 2022] [mpm_prefork:notice] [pid 79669] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Mar 02 18:53:27.041881 2022] [core:notice] [pid 79669] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 19:00:09.798240 2022] [mpm_prefork:notice] [pid 79669] AH00171: Graceful restart requested, doing restart
[Wed Mar 02 19:00:09.859340 2022] [mpm_prefork:notice] [pid 79669] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Mar 02 19:00:09.859362 2022] [core:notice] [pid 79669] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 19:00:16.345736 2022] [mpm_prefork:notice] [pid 79669] AH00169: caught SIGTERM, shutting down
[Wed Mar 02 19:00:16.459763 2022] [mpm_prefork:notice] [pid 79915] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Mar 02 19:00:16.459925 2022] [core:notice] [pid 79915] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 19:01:37.548660 2022] [mpm_prefork:notice] [pid 79915] AH00169: caught SIGTERM, shutting down
[Wed Mar 02 19:01:37.663286 2022] [mpm_prefork:notice] [pid 79969] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Mar 02 19:01:37.663377 2022] [core:notice] [pid 79969] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 19:01:55.690623 2022] [mpm_prefork:notice] [pid 79969] AH00171: Graceful restart requested, doing restart
[Wed Mar 02 19:01:55.752138 2022] [mpm_prefork:notice] [pid 79969] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Mar 02 19:01:55.752162 2022] [core:notice] [pid 79969] AH00094: Command line: '/usr/sbin/apache2'
[Wed Mar 02 19:02:04.367168 2022] [mpm_prefork:notice] [pid 79969] AH00171: Graceful restart requested, doing restart
[Wed Mar 02 19:02:04.423006 2022] [mpm_prefork:notice] [pid 79969] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Mar 02 19:02:04.423029 2022] [core:notice] [pid 79969] AH00094: Command line: '/usr/sbin/apache2'

**Comment by DanielnetoDotCom** [comment]
I cannot see any error on your Apache log

but I can see your Apache is restating too many times

**Comment by Lordblanca** [comment]
Ok can you please send me a link for a complete installation from
beginning to end? Including nginx For Ubuntu 20.04. Thanks
