### ISSUE TITLE
View a paid video

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#6307]
Hi Daniel
A user after uploading a specific video wants it to be viewable only after paying.
I'll explain what he wants to do.
He uploads the video, but doesn't want to show it.
If someone wants to see it he must first pay with paypal and after making the payment he can watch the video.
Can you tell me if I can do it?
If it can be done would you be kind enough to explain me the steps of what to set?
From the image I posted when I go into editing a video there is this feature: Only paid users can see.
I've never created subscription plans for anyone before.
A user asked me if it is possible to show a specific video only after paying.
I await your help response.
Thanks Daniel

PS: Even if I enable this function, the video starts anyway, and I don't think it's suitable for what I want to do.

![3](https://user-images.githubusercontent.com/82677269/155858369-c4cb71e1-7fce-407c-9b33-1b0e645b21f3.PNG)

**Comment by sharknetwork24** [comment]
Maybe I need the PayPerView plugin?

**Comment by DanielnetoDotCom** [comment]
hI

your question is not clear.

do you want the video to be listed on the first page only after the payment?

or do you want to let users watch the video only after the payment?

if you mean watch the video, you may need subscription or PPV plugin

**Comment by sharknetwork24** [comment]
Yes Daniel

Allow users to watch the video only after payment?

**Comment by DanielnetoDotCom** [comment]
Check this 

https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform#paid-content

**Comment by DanielnetoDotCom** [comment]
> Can users manage by themselves by choosing which videos they want to pay before they can be viewed?


Hi

basically, the users can decide what video they want to add to a user group, the user group is what makes the video private or public

![chrome-capture](https://user-images.githubusercontent.com/18009293/156009194-9f0e51f3-73fa-42b8-979d-2686dd75ff55.gif)

**Comment by sharknetwork24** [comment]
Daniel I saw the PayperView plugin on your DEMO site.
I have seen that it accepts payments only with stripes.
Can't I use PayPal payments?
Users usually prefer to pay with PayPal.
Can you tell me how I can do for what I asked for?

![11](https://user-images.githubusercontent.com/82677269/156230075-ac076507-5704-400a-b8eb-b0c627cc398f.PNG)

**Comment by DanielnetoDotCom** [comment]
Hi

sorry for the late reply

I just wrote this to try to make this option clear 
https://github.com/WWBN/AVideo/wiki/PayPerView-Plugin#payment-gateways

**Comment by sharknetwork24** [comment]
Daniel I bought the 2 plugins, can you activate them so I can download them?
Thank you.

PayPerViewLive
PayPerView

**Comment by DanielnetoDotCom** [comment]
Hi

Thanks for the purchase and i can confirm the payment 

right after the purchase you just need to refresh the page than you will see the download button.

there is no need to activate .

please confirm if you can see the download button

**Comment by sharknetwork24** [comment]
Everything is OK.  
Daniel kindly explain to me how to set up YPT Wallet with PayPal?  
Thank you

**Comment by DanielnetoDotCom** [comment]
I just wrote this, I hope it helps 

https://github.com/WWBN/AVideo/wiki/YPTWallet-Usage#enable-paypal-on-the-wallet

**Comment by sharknetwork24** [comment]
I have to try
