### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6309]
I get this when using the search feature. What does it mean?
![A5AA8A6B-10F8-4551-B276-61E0E600AB01](https://user-images.githubusercontent.com/58601786/155878675-a9c0b5ca-0f53-406b-9553-8deba0fe7db0.jpeg)

**Comment by DanielnetoDotCom** [comment]
this is some error on the json. please check your avideo.log for some clue
