### ISSUE TITLE
Login problems and cache issues after last updates. URGENT

### ISSUE THREAD

**Issue by partystreamsk** [WWBN/AVideo#6310]
**Describe the bug**
As i write by email. On friday we had a live stream on my site and users reported me that had issues with login, after login they was loged off after few seconds/minutes. They tried different way to login (facebook, google) but same behavior. Even if they use anonymous window , same issue. Customers and friends dont wanna visit my site more. Even lot of members get errors durring login, they was unable to login. Tried to clear cache of first page + directory , not helped. Its there way to deactivate completly cache? 

**To Reproduce**
1. Login
2. stay on site
3. after few minutes loged out

**Expected behavior**
After somebody login, should be loged in till dont press logout. 

**Error Logs**
No errors in avideo.log

Thanks

**Comment by OptimistPrimal** [comment]
Uploaded Chat2 and SendRecordertoEncoder updates - site broken.

array(4) { ["type"]=> int(64) ["message"]=> string(207) "Declaration of Chat2::afterDonation($from_users_id, $how_much, $videos_id, $users_id, $extraParameters) must be compatible with PluginAbstract::afterDonation($from_users_id, $how_much, $videos_id, $users_id)" ["file"]=> string(98) "/home/WEBSITE/public_html/AVideo/plugin/Chat2/Chat2.php(18) : eval()'d code(1) : eval()'d code" ["line"]=> int(427) }

**Comment by DanielnetoDotCom** [comment]
Make also a git pull

**Comment by partystreamsk** [comment]
No new git pull.. last one is this : 2022-02-26 17:07
avoid errors

**Comment by DanielnetoDotCom** [comment]
@partystreamsk I think this error is not clear.

it seems to be has nothing to do with the cache.

if you do not check the Remember me switch button on the login form, you may be disconnected on the session timeout 

there are a few places to set it up, you may need to check where is it in your server, 

in most cases, you can find this configuration on php.ini or on apache 

also if there is nothing overwriting the PHP code (any server configuration) you may be able to increase it here 

![image](https://user-images.githubusercontent.com/18009293/155975885-cc592694-7c9b-439f-87df-50550eed216d.png)

**Comment by partystreamsk** [comment]
the problem was that people after login, joined my live stream and was not able to tip me because button of donation was orange that shows ,that user was not logged in. So afterč login, people was not able to chat. This is main problem.

**Comment by partystreamsk** [comment]
It was last sheduled live. Like this one :  https://partystream.tv/live/0/MaloFunAcademy?live_schedule=22 

Chat is same from last stream. They loged in, but in reality they was logged off.. Some people logged succesfuly after they try more times , but after few minutes they was disconnected and was not able to use chat. Same behavior was with incognito mode, but at least they logged in succesfuly, chat for few minutes and after that again unable and logged off. fortr that i thought that is something to do with cache.

**Comment by partystreamsk** [comment]
Yes its checked, but my live was not disconected, my live was stable and during this live people encounter this issues. i dont see any refreshes of live. Its there any way to deactivate cache of site? yes plugin cache is deactivated. During the problems i tried both activated and deactivated. Between before you do customisation of plugin with new features, login worked fine. So maybe there is issue.

**Comment by DanielnetoDotCom** [comment]
again, this is not related to the cache.

if you want to do not refresh on a live please uncheck that. otherwise, the chat will refresh when you start a new live

**Comment by DanielnetoDotCom** [comment]
Question ....

do you have your Chat setup on a separate server or on the same server?

can you please share a page where it does happen?

also a test user if it possible?

**Comment by partystreamsk** [comment]
Its on the same server, like before. 
Its happening on live page.  https://partystream.tv/live/0/MaloFunAcademy?live_schedule=22

Try to login by social login, there are three ways or test user is : DanielTest , pass : DanielTest

**Comment by partystreamsk** [comment]
1. Try to login on HomePage and than go to the stream. 
2. Try to login by native button of site , not on orange button
3. Try it with mobile phone.

**Comment by partystreamsk** [comment]
Its look like you are loged on site, but loged off on chat.

**Comment by partystreamsk** [comment]
Now i tried to reproduce issue on iphone and android phone and after last git pull its look like works fine on booth devices. No issues with login.
During this week i will try do do a stream show before a friday so i will test with public too. Thank you for now
