### ISSUE TITLE
Can't update User_Controll Plugin

### ISSUE THREAD

**Issue by CROSSMediaNet** [WWBN/AVideo#6311]
I am having issues with the User_Controll Plugin. I already did a git pull and got the "updated" plugin file, but it is still not updating the plugin...also, I did restart the server and the same results.

What I am doing that is causing this issue?

**Comment by DanielnetoDotCom** [comment]
try to manually delete the User_Controll folder, then Upload the unzipped Folder


https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin#2---upload-the-unzipped-folder

**Comment by CROSSMediaNet** [comment]
Okay...I am at the part that is asking me a question: decent into write-protected directory...what do I need to do at this moment and each time it keeps saying that Permission denied. Do I need this use this code: chown www-data:www-data /var/www/html/AVideo/plugin/ && chmod 755 /var/www/html/AVideo/plugin/

**Comment by DanielnetoDotCom** [comment]
Try 777 instead of 755

**Comment by CROSSMediaNet** [comment]
Okay

**Comment by CROSSMediaNet** [comment]
Okay...it is giving me another error message: changing ownership of /var/www/html/AVideo/plugin/: Operation not permitted

**Comment by DanielnetoDotCom** [comment]
try


`sudo chown www-data:www-data /var/www/html/AVideo/plugin/ && sudo chmod 777 /var/www/html/AVideo/plugin/`

**Comment by CROSSMediaNet** [comment]
Okay...got through that...now going to try to remove the plugin folder...do I need to use sudo as well?

**Comment by CROSSMediaNet** [comment]
Got it...thanks
