### ISSUE TITLE
encoder to pull the YouTube 

### ISSUE THREAD

**Issue by thushy07** [WWBN/AVideo#6313]
when I try to pull the you tube HD videos it's not play as HD videos
the same video's when i downloads it off to my computer and upload its with full HD, what could be the issues?
thank you in advance

**Comment by DanielnetoDotCom** [comment]
do you have the VideoResolutionSwitcher plugin?

you can get it here https://youphp.tube/marketplace/

if you do have maybe your youtube-dl is not downloading the highest resolution, in that case there is nothing we can do
