### ISSUE TITLE
Live - Make stream publicly listed bug

### ISSUE THREAD

**Issue by ccarlile1** [WWBN/AVideo#6314]
**Describe the bug**
We streamed live and had no problem. We did another stream and chose the not to be public option and it worked as expected. Later when we went to do another stream I set it to be public and saved the settings and now I can't get any of my streams to be listed (public).  The toggle seems to not turn it back on for public. Another user tried and the same thing happened. Once set to not be public you can't go back to public even when the option is turned on.

**To Reproduce**
1. Go to live
2. Make Stream Publicly Listed set to public
3. Save settings
4. Start a stream and it is not public. Only logged in users can see stream.

**Comment by ccarlile1** [comment]
Yes, is checked and green.

**Comment by ccarlile1** [comment]
After some more testing I have found if I password protect a stream it will then show up as public. So this kind of fixes the issue other than it says password protected behind the title and the user would need the password. However there seems to be a bug there also. If a user puts in the password when prompted then all other users do not get prompted and don't have to enter a password. It opens it to everyone.

**Comment by DanielnetoDotCom** [comment]
> After some more testing I have found if I password protect a stream it will then show up as public. So this kind of fixes the issue other than it says password protected behind the title and the user would need the password. 

I do not understand what did you do


>  If a user puts in the password when prompted then all other users do not get prompted and don't have to enter a password.

Not true. 
the password whitelists the browser you have entered it. if you try an incognito browser you will be prompted again

**Comment by ccarlile1** [comment]
I had a user on another computer try to watch a stream that had a password. It prompted them for a password but they hit cancel and did not enter one. I entered a password on my computer when prompted and I could watch the stream. They went back on their computer and it let them watch with no password. When 1 user puts in the password the others did not get prompted and have to put one in.

**Comment by DanielnetoDotCom** [comment]
show me a link I can do that.

what you are describing seems to be impossible for me

**Comment by ccarlile1** [comment]
www.diggertv.sugarsalem.org

I have this a password protected and the 1st person to go gets prompted. They enter the password and then others don't need to. See if you can watch without a password.

**Comment by ccarlile1** [comment]
https://diggertv.sugarsalem.org/

**Comment by DanielnetoDotCom** [comment]
For me is protected

![image](https://user-images.githubusercontent.com/18009293/156038854-c11eb185-3ea5-44e2-ba9a-54b67f49bce9.png)

**Comment by ccarlile1** [comment]
We are seeing a timeout. If someone puts in password it will open for all for a few minutes. Then after a few minutes it will prompt. If that person puts in a password it will open for all again for a few minutes. I'm trying to time it to see how long that time is.

**Comment by ccarlile1** [comment]
Can you do incognito and try again.

**Comment by DanielnetoDotCom** [comment]
I do not think it will happen if you use a different browser or an incognito window

Just tried again 

![image](https://user-images.githubusercontent.com/18009293/156040771-2813374d-5e36-4d7a-8dff-22d512b01022.png)

**Comment by ccarlile1** [comment]
I will keep testing with it. We have strange results.  But I still can't get a video to be listed unless I password protect it even if I have it set to be public. Like I said it only did this after doing a video as not public and then switching back to public. I can create a new user and streams will be public as long as they don't ever turn off the make public switch. Once you do that even if you switch back on to make public it won't be public.

**Comment by ccarlile1** [comment]
Just found out it is 10 minutes. We are all on the same network so I don't know if that has anything to do with it. If one person puts in the password no one else has to put in a password for ten minutes. Then it will prompt them after ten minutes.

**Comment by DanielnetoDotCom** [comment]
the password approval is saved on a session, the session is per browser, NOT per network.

I have no idea how this is happening to you.

maybe is some cache on your network, that is not requesting a new result for the page. it is just returning the last response from the server. (probably proxy)

**Comment by DanielnetoDotCom** [comment]
I can see this now.

I can confirm this is happening with you but the same is not happening on my side

check the demo site

https://demo.avideo.com/live/0/TheAdminChannel/135351

password 123

it is probably something on your PHP session configuration.

**Comment by ccarlile1** [comment]
Thanks for checking. I will do some digging and try and figure it out.
