### ISSUE TITLE
How to disable right click properties "Copy Video URL", "Copy Video at current time" and "Copy Embed code"?

### ISSUE THREAD

**Issue by aridzonan13** [WWBN/AVideo#6315]
**Describe the question**
A clear and concise description of what is your question.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
Check this 

![image](https://user-images.githubusercontent.com/18009293/156189945-14878212-8a7d-4526-8f70-3f8189ed358b.png)

**Comment by aridzonan13** [comment]
Perfect, thanks for the swift reply...
