### ISSUE TITLE
Username shown on live streams

### ISSUE THREAD

**Issue by consultingforge** [WWBN/AVideo#6318]
**Describe the bug**
A clear and concise description of what the bug is:
When a user that is also publisher sets his "Name" in the user profile all uploaded videos are shown as "Upload by *Name*". But when the user schedules a live stream or directly lunches live, in the home page or lives category what is shown is the username.

**To Reproduce**
1. Create a publisher user
2. Set name on profile
3. Upload a video
4. Scledule/launch a Live event

**Expected behavior**
A clear and concise description of what you expected to happen:
The user "Name" should be consistent in uploaded videos, live events, articles, etc...

**Screenshots**
Will be sent by email due to privacy

**Comment by DanielnetoDotCom** [comment]
check what do you have here ...

![image](https://user-images.githubusercontent.com/18009293/156363160-4dc18b68-f605-4f7b-88f3-8cabd1388941.png)


make sure you uncheck the option that you want to identify your users.

**Comment by jengajenga** [comment]
I can say this,

When you use gmall to log in, your email address will be exposed because your username is your email address.

doesn't matter what you check/uncheck. in fact, the moment you change the user name from your gmail address to something else, it becomes a different account altogether and you will see in the db that the accounts are now two different accounts.

**Comment by DanielnetoDotCom** [comment]
@jengajenga what about identifying your users by Name NOT username?


The name is open and you can put whatever you want.

**Comment by DanielnetoDotCom** [comment]
FYI the identification order will be ...

1. Try Name
2. Try email
3. Try Username
4. Try channel name

**Comment by consultingforge** [comment]
> check what do you have here ...
> 
> ![image](https://user-images.githubusercontent.com/18009293/156363160-4dc18b68-f605-4f7b-88f3-8cabd1388941.png)
> 
> make sure you uncheck the option that you want to identify your users.

if i understood correctly this is proper config but still happens
![Captura de pantalla 2022-03-04 a las 23 37 11](https://user-images.githubusercontent.com/12797403/156851551-2e327a53-2381-484e-83e6-e9aa6b434f76.png)

**Comment by DanielnetoDotCom** [comment]
can you please screenshot where exactly do you mean it is not showing correctly?

**Comment by consultingforge** [comment]
sent pic via email

**Comment by DanielnetoDotCom** [comment]
Please paste the pic here

**Comment by DanielnetoDotCom** [comment]
Do you mean the username on the live schedule?

**Comment by consultingforge** [comment]
yes

**Comment by consultingforge** [comment]
Solved!

**Comment by consultingforge** [comment]
yes, username on live-schedule




NOC Team
Network Operations Center
CONSULTINGFORGE SL
***@***.***
 ***@***.***>www.consultingforge.com <https://www.consultingforge.com/>
