### ISSUE TITLE
long time to load

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6319]
Hi Daniel, what could have gone wrong
videos take a long time to load
before that it was fine
I did the update and nothing has improved 
https://www.youhippo.com/

there seems to be a loophole in the code
because I had an xss alert before

**Comment by DanielnetoDotCom** [comment]
In most cases the Live server is offline or the encoder or network site is offline

but check your avideo log for some clue

**Comment by KrzysioMisio** [comment]
I have no bugs
I don't have Live
I only have video files saved 
this is only on the video page 
click on a video and see how much is loading
https://www.youhippo.com/

**Comment by DanielnetoDotCom** [comment]
Your page loads fine here. 

but if you need help you still need to share the logs, I am not searching, on the log, for errors or bugs, I am searching for clues

**Comment by DanielnetoDotCom** [comment]
I can see your videos are taking a while to load. 

for example access the mp4 file directly is just keeping loading https://www.youhippo.com/videos/video_220226112313_v54d5/video_220226112313_v54d5_240.mp4

maybe your problem is a bandwidth problem. the best solution I can give to you is the CDN

https://github.com/WWBN/AVideo/wiki/CDN-Plugin

**Comment by DanielnetoDotCom** [comment]
Also, I recommend you to make sure you have this installed 

https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

and also run this 

https://github.com/WWBN/AVideo/wiki/Speed-up-your-page#tuning-your-apache-server

**Comment by KrzysioMisio** [comment]
I have apache xsendfile installed
everything was ok, I have had these problems for 2 days
I will call the internet provider if they have any problems

**Comment by KrzysioMisio** [comment]
[avideo.log](https://github.com/WWBN/AVideo/files/8169853/avideo.log)
my log file

**Comment by DanielnetoDotCom** [comment]
I do not think the issue is your internet provider, but the server provider.

but you also can try to update your streamer and plugins. there are some performance updates on it

**Comment by KrzysioMisio** [comment]
I have server in my home :-)
and you have seen the log file
