### ISSUE TITLE
Video Embeding Question / Plugin property change?

### ISSUE THREAD

**Issue by aridzonan13** [WWBN/AVideo#6323]
**Describe the question**
We were able to generate type 1)"https://oursite.com/videoEmbed/22/on-site-video/ " link.  Note the "/videoEmbed/" sub directory.  We've not been able to duplicate this link w/ the /videoEbeded subdir again.. Now, we can only produce type 2)"https://oursite.com/video/22/on-site-video?channelName= ChannelName".. Note the /video/ sub directory.  The problem is type 1) works well. Where type 2)does not show our logo, etc.. See screenshots below. The top video is type 2) and the bottom is type 1). Note the difference in appearance.

Is there a property in the plugins that I could have changed that has removed the type 1) capability? 

**Screenshots**
Provide some
![solari_video-vs-videoEmbed-sub-dir](https://user-images.githubusercontent.com/6320576/156455353-ea19ab88-ab4d-42bc-8a98-221141bf6f9d.png)

**Comment by DanielnetoDotCom** [comment]
Please check this 

https://github.com/WWBN/AVideo/wiki/Video-Embed-URL-for-AVideo
