### ISSUE TITLE
Live plugin

### ISSUE THREAD

**Issue by Chomikmarkus** [WWBN/AVideo#6324]
**Describe the question**
A clear and concise description of what is your question.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.
Description:
Followed full tutorial:(https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server)
All seems fine nginx install, RTMP install, stats page works and displays! 
Altough when trying to configure Live plugin.
![Screenshot_20220303-014455](https://user-images.githubusercontent.com/92059377/156468855-41773b74-98b1-4c19-9f14-2a39d0d964c9.png)
![Screenshot_20220303-014515](https://user-images.githubusercontent.com/92059377/156468876-85794253-6297-4795-a394-07da3efe8ad7.png)

**Comment by Chomikmarkus** [comment]
Sytem Ubuntu 20.04 php version 7.4! I figured maybe its ssl error, so followed instructions! Now im getting error when starting nginx

root@vps168451:/var/www/html/plugin# /usr/local/nginx/sbin/nginx
nginx: [emerg] SSL_CTX_use_PrivateKey("/etc/letsencrypt/live/ukrainayhdistys.org/privkey.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)

**Comment by Chomikmarkus** [comment]
![Screenshot_20220303-015504](https://user-images.githubusercontent.com/92059377/156469651-2d1b7c54-4a98-464f-85da-5368e26ab619.png)

**Comment by DanielnetoDotCom** [comment]
I can see your Nginx is not running.

https://ukrainayhdistys.org:8443/

**Comment by Chomikmarkus** [comment]
![Screenshot_20220303-033931](https://user-images.githubusercontent.com/92059377/156480221-df9e818f-e07e-42af-8fb2-e7f324d587fa.png)

**Comment by Chomikmarkus** [comment]
Well when I check it with systemctl it's not finding service at all!

**Comment by DanielnetoDotCom** [comment]
this is the correct way to stop and start your Nginx RTMP server

`sudo /usr/local/nginx/sbin/nginx -s stop && sleep 3 && sudo /usr/local/nginx/sbin/nginx`

With this error, I can see your Nginx is not properly installed

`nginx: [emerg] SSL_CTX_use_PrivateKey("/etc/letsencrypt/live/ukrainayhdistys.org/privkey.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)`

Check this tutorial https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

but if you cannot make it work you may need to find help how to install Nginx and the SSL on the [Nginx RTMP page](https://github.com/arut/nginx-rtmp-module)

another tip, usually VPS servers do not like Live streams, and they may suspend you when you start to have a good audience.  

Live streams consume more CPU and bandwidth than the VPSs like to allow you to use.

**Comment by Chomikmarkus** [comment]
When I connect with android app it even allows to go live and RTMP shows statistics about
![Uploading Screenshot_20220303-222531.png…]()

**Comment by Chomikmarkus** [comment]
Tried to make clean install, Ubuntu 20.04 OS, followed full tutorial on installing rtmp nginx and SSL still getting same error! Everything seems to work NGINX and rtmp module, when try to activate ssl
nginx: [emerg] SSL_CTX_use_PrivateKey("/etc/letsencrypt/live/ukrainayhdistys.org/privkey.pem") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)

**Comment by Chomikmarkus** [comment]
And also post issue to https://github.com/arut/nginx-rtmp-module/
No answer still! But I'm sure that have done nothing wrong during install!
