### ISSUE TITLE
Embed Live STream support

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6325]
Just found out today people are able to embed live youtube feeds. look here https://www.joshwhotv.com/video/.QDt4mw/rt-uk-news-on-air-livestream-24-7

This is fascinating and wonder if possible to make embeds able to use the Live Stream template?

That way it can have a live chat just like the regular live links. 

Like some kind of option you can just enable for that single embed

![download](https://user-images.githubusercontent.com/39392449/156480125-b0b07949-e910-475a-8b17-6d01846f3453.png)

Make it more like this my flipping a switch on the video embed.

![494f43ac-916d-48f2-872c-82af70883236](https://user-images.githubusercontent.com/39392449/156480199-f8022cc7-0d28-4221-b71e-5a3e97495ad2.png)

**Comment by JoshWho** [comment]
I do not want chat on all videos just embeds that have live streams

**Comment by DanielnetoDotCom** [comment]
> Just found out today people are able to embed live youtube feeds. look here https://www.joshwhotv.com/video/.QDt4mw/rt-uk-news-on-air-livestream-24-7

Yes, you can embed it :)

> This is fascinating and wonder if possible to make embeds able to use the Live Stream template?

So you should use the LiveLinks, but this requires the m3u8 file

> That way it can have a live chat just like the regular live links.
> Like some kind of option you can just enable for that single embed
> Make it more like this my flipping a switch on the video embed.
> not chat on all VOD videos, just the embeds that have live streams that way it can be separated

I am not sure what you mean but probably separate chats. per video. we may add this option in the future.

**Comment by JoshWho** [comment]
YOu can't get the m3u8 links from the live youtube streams anymore. they expire. 

This is literally just embedded by using the link to the yt live stream.

**Comment by DanielnetoDotCom** [comment]
I see, it also works, but not on livelinks

I may add a different feature in the future.
