### ISSUE TITLE
Long load times

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6326]
What would cause long load times?
Mobile app just spins.
Main website loads 2 minutes.
Can’t pull log as nothing is responding.
Out of the blue.

**Comment by barrunning** [comment]
![EB004DB2-6C0B-4D7D-84AE-BA9BA3E02FEA](https://user-images.githubusercontent.com/58601786/156525878-e9f23f8a-28ca-43fc-8fde-9cac35ecaafb.jpeg)

would this have any effect? If so how do I connect it?

**Comment by DanielnetoDotCom** [comment]
Socket is required, but it does not affect the video play

video play is exclusively on your apache configuration and your bandwidth link. it has nothing to do with the PHP code.

**Comment by barrunning** [comment]
![B2CF8E67-65AB-4D09-92F2-1F696E70D5B3](https://user-images.githubusercontent.com/58601786/156599958-409231ed-f760-46f3-b015-7f5d36e6b64d.jpeg) error message. Trying to pull logs.

**Comment by barrunning** [comment]
![2161C1AE-E5A5-428D-9D87-EC84E9626710](https://user-images.githubusercontent.com/58601786/156617450-96b68ff6-2e72-45a0-90ff-d7b9555df0b9.jpeg)
