### ISSUE TITLE
Make Stream Publicly Listed does not work

### ISSUE THREAD

**Issue by Rolandhun74** [WWBN/AVideo#6327]
Hello!

My problem is that even if I turn it off, the stream is always visible

This site Already up to date.

Thx
Roland

<img width="1680" alt="Képernyőfotó 2022-03-03 - 7 15 13" src="https://user-images.githubusercontent.com/83669701/156507388-8da36de7-3d38-44c8-af11-5f9342bdf727.png">

**Comment by DanielnetoDotCom** [comment]
Are you checking it as Admin?

Admin may see even unlisted lives

also make sure you are up to date on the `git pull`

**Comment by Rolandhun74** [comment]
Hello!

Are you checking it as Admin?
No, logout

Admin may see even unlisted lives
Yeah I know

also make sure you are up to date on the git pull
Yes

**Comment by DanielnetoDotCom** [comment]
Issue confirmed, it may be fixed on the next update

**Comment by Rolandhun74** [comment]
Thx :)
