### ISSUE TITLE
Seperate page for all the Lives including Live Links as well

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6329]
We are getting more streams everyday now and this will takeover the homepage eventually. Is there a plan to separate these?

![aea4e5a0-51e2-43b3-b261-5a89f9981ba7](https://user-images.githubusercontent.com/39392449/156573276-a70fd84f-6f81-43cb-98ac-a0cdb61e4b05.png)

**Comment by DanielnetoDotCom** [comment]
I will add it on the next version

**Comment by JoshWho** [comment]
Sweet Thank you @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Check this 

https://joshwhotv.com/live

**Comment by JoshWho** [comment]
Is there a way to load some on the home page but have a link to that page to show more?

**Comment by JoshWho** [comment]
> Check this
> 
> https://joshwhotv.com/live

Perfect

**Comment by JoshWho** [comment]
Is there a way to load some on the home page but have a link to that page to show more?

**Comment by DanielnetoDotCom** [comment]
What about the topMenu plugin?

or do you suggest something?

**Comment by JoshWho** [comment]
Like just show like 4 live links and 4 live streams at the top of the homepage and then just a link to view more.

Maybe it can rotate by how many viewers it is getting or something like that.

**Comment by JoshWho** [comment]
Currently there is no way to disable the Live Links from the home page without just disabling the plugin. Seesmt to be hard coded into the Gallery theme

**Comment by DanielnetoDotCom** [comment]
Sure, I may add this in the future.

**Comment by JoshWho** [comment]
Thank you Daniel that will be awesome!!

**Comment by JoshWho** [comment]
Is there something I can do to not show the live Links on the home page ?

**Comment by JoshWho** [comment]
> Is there something I can do to not show the live Links on the home page ?

I found a switch in the Live Plugin that hides the streams from the homepage.
