### ISSUE TITLE
Video Embeds no longer working since last git pull

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6331]
When you try to embed from rumble or other platforms you get this error

![56b87902-eea5-4491-a8e7-118489aad1bd](https://user-images.githubusercontent.com/39392449/156705415-28eb805a-aed8-40f7-8299-f4eb893af24e.png)

**Comment by DanielnetoDotCom** [comment]
probably the same error as this one

https://github.com/WWBN/AVideo/issues/6332

**Comment by JoshWho** [comment]
Confirmed and solved.
