### ISSUE TITLE
Send to recorder has not worked since 10.7

### ISSUE THREAD

**Issue by Rolandhun74** [WWBN/AVideo#6333]
Hello

Encoder Error:
try [1] Error on return_vars->videos_id

Site log:
04-Mar-2022 10:16:21 Europe/Budapest] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/myMySQLDatabase\/objects\/mysql_dal.php","line":98,"function":"log_error"},{"file":"\/var\/www\/html\/myMySQLDatabase\/objects\/video.php","line":415,"function":"writeSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/myMySQLDatabase\/plugin\/SendRecordedToEncoder\/SendRecordedToEncoder.php(18) : eval()'d code(1) : eval()'d code","line":213,"function":"save","class":"Video","type":"->"},{"file":"\/var\/www\/html\/myMySQLDatabase\/plugin\/Live\/on_record_done.php","line":9,"function":"on_record_done","class":"SendRecordedToEncoder","type":"->"}] SCRIPT_NAME: /plugin/Live/on_record_done.php

[04-Mar-2022 10:13:11 Europe/Budapest] AVideoLog::ERROR: MySQL ERROR: [{"file":"\/var\/www\/html\/myMySQLDatabase\/objects\/mysql_dal.php","line":98,"function":"log_error"},{"file":"\/var\/www\/html\/myMySQLDatabase\/objects\/video.php","line":415,"function":"writeSql","class":"sqlDAL","type":"::"},{"file":"\/var\/www\/html\/myMySQLDatabase\/objects\/aVideoEncoder.json.php","line":166,"function":"save","class":"Video","type":"->"}] SCRIPT_NAME: /objects/aVideoEncoder.json.php

Thx

**Comment by DanielnetoDotCom** [comment]
Please make sure your encoder is up to date.

first, try on the nginx.conf `record all;` instead of `record all manual;`

https://github.com/WWBN/AVideo/blob/bcebb11ce78e74235323d7250b83e13f15f0b135/plugin/Live/install/nginx.conf#L42

share more of your log. I could not see your MySQL ERROR

**Comment by Rolandhun74** [comment]
Thanks for the help.

We looked through everything and finally resolved it after restarting the server

**Comment by Proxy-Ninja** [comment]
Same Issue in apache2, not fixed yet, any suggestion.

**Comment by DanielnetoDotCom** [comment]
@Proxy-Ninja open a new issue and provide your logs
