### ISSUE TITLE
update 11.6 

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6334]
I did the update to 11.6
and i have bugs
my log file  https://www.youhippo.com/hippo/avideo.txt
![bug](https://user-images.githubusercontent.com/93145787/156757076-ca29080f-bb6d-430b-84a1-e870d1a4aeaa.png)

**Comment by DanielnetoDotCom** [comment]
Hi

Did you update it correctly?

https://github.com/WWBN/AVideo/blob/bcebb11ce78e74235323d7250b83e13f15f0b135/objects/user.php#L97-L99

did you use git pull to update?

the method is there

**Comment by KrzysioMisio** [comment]
yes
probably did not create a table
![bug1](https://user-images.githubusercontent.com/93145787/156769407-3f4ce7d9-e124-443b-9836-f935f78203e2.png)

**Comment by DanielnetoDotCom** [comment]
the error is complaining of a missing code, but the code is present. maybe you need another `git pull`

**Comment by KrzysioMisio** [comment]
it's good
now I have manually uploaded the user.php file

**Comment by DanielnetoDotCom** [comment]
Please do not manually update. use the git pull is strongly recommended

**Comment by KrzysioMisio** [comment]
I used the git pull
but an error popped up, so I sent user.php manually

**Comment by DanielnetoDotCom** [comment]
Than run this

`sudo git fetch --all && sudo git reset --hard origin/master`
