### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6335]
![belka1](https://user-images.githubusercontent.com/93145787/156818389-89a17b2f-23b2-4be3-b996-299d5846c91a.png)

how to enable these icons  ??
I don't have them 

![belka](https://user-images.githubusercontent.com/93145787/156818588-0bd77938-43b3-4726-a978-164907737be2.png)

**Comment by DanielnetoDotCom** [comment]
Looks like you modified the script, you are probably missing the fontsawesome css file

**Comment by KrzysioMisio** [comment]
ok, I will look, I have my css custom file
and maybe he collides
