### ISSUE TITLE
Program LiveStreaming

### ISSUE THREAD

**Issue by OptimistPrimal** [WWBN/AVideo#6336]
I'm running more than one livestream server, is there a way to select which server that a PROGRAM will stream to?  I haven't been able to figure it out.

**Comment by DanielnetoDotCom** [comment]
can you please provide some screenshots of what you are referring to?

**Comment by JoshWho** [comment]
I requested this a while ago.  He is talking about the feature on Playlists where you can click Go Live and it will start Live Streaming the playlist.

My issue with that is it hogs all the cpu of my uploading server and crashes.  Would love to be able to select which encoder server to use just for that part.

Would also be neat to be able to select what encoder server generates your live thumbs.

**Comment by DanielnetoDotCom** [comment]
The go live feature is still under development.
