### ISSUE TITLE
Creating a high-quality design

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#6337]
Hello to all AVideo fans!

I suggest we team up, order a good design and include it in the distribution.

My suggestion is to make a design similar to YouTube, rutube.ru or something like this:
https://demo.mediacms.io/
https://www.kvs-demo.com/

I also suggest that @DanielnetoDotCom do this: when users add a video to the site, it was encoded by HLS, but the user did not see the encoder. (everything happened on the site). 
for example, how the video is added on this site: https://www.kvs-demo.com / when adding, a person does not have to switch to an encoder to add a video, Everything happens on the site and the video encoding capabilities are distributed among the servers.

Let's add up the money so that @DanielnetoDotCom makes this process faster and it was interesting for him to do it.

@DanielnetoDotCom waiting for your comment on this issue

**Comment by palich91** [comment]
I think Bootstrap is a good solution for a template

**Comment by phpeval** [comment]
Make a template on Bootstrap

**Comment by JoshWho** [comment]
FYI you can upload directly without leaving the site. I is the frame uploader network.

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/39392449/156893544-46378076-1682-46e2-a50a-ae67c3b2fe17.gif)

**Comment by JoshWho** [comment]
I have always liked the mediacms theme. Would be kewl to see the Gallery theme convert more to that. I like the static Navigation bar always out for desktop.

**Comment by palich91** [comment]
@DanielnetoDotCom can you do it?

**Comment by palich91** [comment]
Let's chip in and order a stylish template, I'm ready to pay $50.
I think Bootstrap is a good templating solution. And I suggest building a template on getbootstrap.com

**Comment by phpeval** [comment]
Write to me in a Telegram https://t.me/phpeval
I plan to buy plugins, but before that I have to be sure that the design will be attractive

**Comment by JoshWho** [comment]
> Write to me in a Telegram https://t.me/phpeval I plan to buy plugins, but before that I have to be sure that the design will be attractive

This is the most developed VOD Live Streaming Youtube like alternative. So much future with Avideo and it is still just the beginning. You can try others and watch how long it takes to get support or a update for something. 

Only thing left is some new themes and a future of evolution for the internet to evolve too.

**Comment by DanielnetoDotCom** [comment]
Hi

definitely I can improve the design when the time comes. But I do not do design jobs , even paid jobs

**Comment by palich91** [comment]
Let me hire a designer and order a design, offer your wishes. I will take them into account when ordering

**Comment by venwebsites** [comment]
@DanielnetoDotCom @palich91 @JoshWho @phpeval  I don't know if its me but the medicms theme looks a lot like youphptube

**Comment by JoshWho** [comment]
> @DanielnetoDotCom @palich91 @JoshWho @phpeval I don't know if its me but the medicms theme looks a lot like youphptube

It does kind of, but Daniel discontinued that theme.

**Comment by JoshWho** [comment]
Gallery could look like that if there was a way for the Nav to Stay open by default on the home page and shrink the gap a little

Gallery
![download (6)](https://user-images.githubusercontent.com/39392449/160036334-109f474e-4a0f-404c-9ea8-ba7582f7788e.png)

Mediacms
![5aca5f8e-eee6-4cc2-ad24-8003e729db43](https://user-images.githubusercontent.com/39392449/160036368-0ccb58e3-a1ab-40f5-b306-6ae9c67e7256.png)

**Comment by JoshWho** [comment]
Almost just like it especially when i changed the rows back to 6 on Gallery

![7fe2a77a-bd0b-4830-83ca-71b063c5d8cf](https://user-images.githubusercontent.com/39392449/160235351-e1c7c109-ba04-4d3f-8bbe-2c6c03a5bb93.png)

**Comment by DanielnetoDotCom** [comment]
CUrrently there is no way to keep the nav open

**Comment by GarethBagley** [comment]
> > Write to me in a Telegram https://t.me/phpeval I plan to buy plugins, but before that I have to be sure that the design will be attractive
> 
> This is the most developed VOD Live Streaming Youtube like alternative. So much future with Avideo and it is still just the beginning. You can try others and watch how long it takes to get support or a update for something.
> 
> Avideo is a blessing and I am super impressed with it. Check out my platform so far here https://www.joshwhotv.com
> 
> Only thing left is some new themes and a future of evolution for the internet to evolve too.

I second that!
Great platform, great support and great future if the community pulls together.

**Comment by Ritbit** [comment]
Is there a guide/documentation how to create your own plugins & themes ?

**Comment by DanielnetoDotCom** [comment]
Design: https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates

Plugins: https://github.com/WWBN/AVideo/wiki/How-to-code-a-AVideo-Platform-plugin
