### ISSUE TITLE
link cat

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6338]
https://github.com/WWBN/AVideo/blob/master/plugin/Gallery/view/BigVideo.php#L181

the link points to the video, and should be to a category 
it should be
`<a class="label label-default" href="<?php echo $global['webSiteRootURL']; ?>cat/<?php echo $videoRow['clean_category']; ?>">`

**Comment by DanielnetoDotCom** [comment]
This is not clear for me, can you please give more details?

**Comment by KrzysioMisio** [comment]
go to my website and click on BigVideo in the category 
https://www.youhippo.com/
the link points to the video and has to the category

**Comment by DanielnetoDotCom** [comment]
Thanks for noticing it. this update should resolve it
