### ISSUE TITLE
Limit Number of Image Loads from Notification View some how

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6340]
Seems like since we have 70 live streams now that the notification dropdown wont load because I think it is trying to load too many images.

![d5b757a0-5397-481d-848a-2ede10898ab6](https://user-images.githubusercontent.com/39392449/156892692-b47a6ca6-5ebe-4106-8042-17302f245e3b.png)

**Comment by JoshWho** [comment]
Is there a way I can just turn off the Notification Bell? Like make it not show anymore

**Comment by DanielnetoDotCom** [comment]
Did you try the Live plugin parameter -> hideTopButton (Hide Top Button)

**Comment by JoshWho** [comment]
I am still deciding if that is a good idea or not.

**Comment by JoshWho** [comment]
Ok just tried the Hide Top Button and it made all the Live Streams not Show anymore on all pages.

**Comment by JoshWho** [comment]
Honestly though I still like the bell notifications live list so I am gonna keep it.
