### ISSUE TITLE
config path of youtube-dl

### ISSUE THREAD

**Issue by webmasterandy** [WWBN/AVideo#6342]
I had installed youtube-dl but how can say AVideo where I install the file?

![image](https://user-images.githubusercontent.com/89803140/156923710-195fa10d-e6c1-4b52-8f8a-528cb2780d32.png)

**Comment by DanielnetoDotCom** [comment]
usually, it is installed and AVideo can find it by default. but if you have a specific path you can use a global variable on your configuratio.php file

`$global['youtube-dl'] = '/usr/local/bin/youtube-dl'; `

https://github.com/WWBN/AVideo-Encoder/wiki/Configuration.php-variable-(-some-are-hidden-)
