### ISSUE TITLE
Subscription not updated after payment 

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6343]
After a user pays, the membership isn’t changed. I have to manually update the user membership. This was a member whose membership had expired. 
The user paid through PayPal.

**Comment by DanielnetoDotCom** [comment]
Can you please detail what you are doing? 

There is something on the avideo.log?

**Comment by barrunning** [comment]
A user subscription expired. They renew the subscription. The payment goes through but the subscription isn’t being updated.
I have to manually update the subscription.
![1B5F8CCC-6B19-4010-B9A1-F46DC99C97E3](https://user-images.githubusercontent.com/58601786/156933364-a1c3f67b-fb7b-4575-b7e2-953a0d6556e2.png)

**Comment by barrunning** [comment]
![D05C4BD0-AD84-4F93-ABAF-933B44FC60ED](https://user-images.githubusercontent.com/58601786/156933416-25ffc3b4-f832-4fe3-8c08-0312294b5fa9.jpeg)
This a stripe payment that was captured.
The other payment was through PayPal.
Neither subscriptions were updated after payment was processed.

**Comment by DanielnetoDotCom** [comment]
Now I am confused, was it stripe or PayPal?

In the first post, you said PayPal, if it is stripe you may be missing the webhook key (SigningSecret)

Before you can verify signatures, you need to retrieve your endpoint’s secret from your Dashboard’s
[Webhooks settings](https://dashboard.stripe.com/account/webhooks).

![image](https://user-images.githubusercontent.com/18009293/157030610-d3d0463f-ecd1-4ee9-ba10-514fda28788e.png)

**Comment by barrunning** [comment]
Sign up for a subscription. I the admin then have to manually put in the subscription by accessing the plug in. 
The subscription plug in will show a person has paid and signed up. I then have to go to the stripe plug in and manually put in the subscription.

**Comment by DanielnetoDotCom** [comment]
Hi, if is stripe you need to add the webhook as I described above

**Comment by barrunning** [comment]
I have no idea how.

**Comment by DanielnetoDotCom** [comment]
1. go to this link https://dashboard.stripe.com/account/webhooks
2. get the webhook Signing Secret
3. Update your plugin YPTStripe -> SigningSecret

![chrome-capture (5)](https://user-images.githubusercontent.com/18009293/157106615-6c3f4ed3-252b-43fb-96af-c24dce6e0057.gif)
