### ISSUE TITLE
Full RTL template when switching to RTL language

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6344]
![Screen Shot 5782-07-03 at 23 20 56](https://user-images.githubusercontent.com/58882903/156942711-10c06fe2-93af-4315-9cab-6c1ae665aac6.jpg)

How can we get the main menu to appear on the right side as well as having all titles, text, images float to right while a user is using an RTL language. I think mostly this would be Arabic and Hebrew. Is it possible to make? do we need to create a complete new template?

**Comment by DanielnetoDotCom** [comment]
Try to add this into your lag file


`$t_isRTL = 1;`

**Comment by guymass** [comment]
I put it in the Hebrew language file at the top of the list and I see that now things moved to the right on the Hebrew template, thank that looks better. How can we also move the menu to open on the right side and slide to the left. Also the profile menu needs to switch position and move it to the left. How can I switch those?

**Comment by guymass** [comment]
My English language file has these three menu items that will not translate.

This is how it is in the EN file:

![Screen Shot 5782-07-04 at 20 17 21](https://user-images.githubusercontent.com/58882903/157093944-fe0a1254-c72e-49b1-abd5-f69b21a74359.jpg)

This is how it is in the HE file:
![Screen Shot 5782-07-04 at 20 17 33](https://user-images.githubusercontent.com/58882903/157094157-5c0c0a4e-bc45-471a-af19-4d5e5417bc28.jpg)


after uploading and clearing the site's cache I still see the menu like this:
![Screen Shot 5782-07-04 at 20 18 11](https://user-images.githubusercontent.com/58882903/157094272-1fc4844c-ad04-4067-bc95-a78008e2f147.jpg)

**Comment by guymass** [comment]
Sorry those were in the wrong post. I want these two menus switched on RTL language

![Screen Shot 5782-07-04 at 20 42 45](https://user-images.githubusercontent.com/58882903/157097618-982120aa-7876-4990-844d-ba3d508c4c78.jpg)
![Screen Shot 5782-07-04 at 20 42 59](https://user-images.githubusercontent.com/58882903/157097736-24230a79-161c-4f85-a223-2a7225c7c1d8.jpg)

**Comment by DanielnetoDotCom** [comment]
Are they not on RTL?

**Comment by guymass** [comment]
The text on those menus is RTL but that is not what I am asking. I want to actually move the main menu on the left to be opened on the right side of the screen and this will also require moving the menu currently located on the top right to the top left, so thus switching their location/position/places.

**Comment by DanielnetoDotCom** [comment]
I see, sorry, unfortunately, switching menu positions is not possible

Regarding the translation, I just checked the locale/he_IL.php file and it is a bit messed up.

there are some duplicated entries. also, there are a lot of items without translation.

I made some changes with google translation help, but still some things to do

**Comment by guymass** [comment]
I will complete the translation for those missing ones, but Im not sure if those duplicates really effect it but I will clean it up and test again.

**Comment by guymass** [comment]
Yes it seems some duplicated did effect some translation and I fixed those but for the ones on the Encoding menu I don't have any duplicates and they still don't translate. I am trying all sorts of things but non work and im not sure why.

**Comment by DanielnetoDotCom** [comment]
Once you clear it, make a pull request and let me know if something still missing.

**Comment by guymass** [comment]
I made the update and pull request, clear cache and I see I still get my language files but these two items will still not translate for some reason. I did manage to fix the "Add Article". Here is a SS:
![Screen Shot 5782-07-07 at 21 25 38](https://user-images.githubusercontent.com/58882903/157739731-608cf37f-12e9-4dc1-b648-601d99155d0c.jpg)

"Live Stream" and "Publish Live" will not translate like the others and I don't have any duplicates.

**Comment by DanielnetoDotCom** [comment]
You have to add

```
$t['Live Stream'] = '...';
$t['Publish Live'] = '...';
```

**Comment by guymass** [comment]
I added those to the en_US.php file but still it will not translate
![Screen Shot 5782-07-08 at 13 17 02](https://user-images.githubusercontent.com/58882903/157857403-07e3ca04-aeba-4bb4-9db9-bf70a8ef5b94.jpg)

**Comment by guymass** [comment]
Anyway this is becoming a duplicate with the translation file so I will close this and will continue in the other post as this one with RTL is OK.
