### ISSUE TITLE
Translation bug and missing menu titles

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6345]
I cannot get the "Add Article" to be translated no matter what I try and the other two menu items are totally missing, where do I edit those?

![Screen Shot 5782-07-03 at 23 37 02](https://user-images.githubusercontent.com/58882903/156943233-124a30ad-a755-4de5-809b-baf30b6cbd40.jpg)

**Comment by DanielnetoDotCom** [comment]
that is crazy.

can you make a pull request from your lang file so I can test it locally?

**Comment by guymass** [comment]
I have added these in the en_US file
$t['Live Stream'] = '...';
$t['Publish Live'] = '...';

but still I get no translation for those two.

**Comment by DanielnetoDotCom** [comment]
Noo, you should add these lines into your Hebrew lang file, and replace the ... with your translation.

**Comment by guymass** [comment]
Well that's what I was doing all the time, I thought this was a new thing haha. I will keep testing the file, something is not working with that wording maybe I will change the text and see if that will fix it.

**Comment by guymass** [comment]
I change the "Live Stream" to "Live Now" and it translated the red main button but not the menu item.
 
![Screen Shot 5782-07-09 at 0 06 58](https://user-images.githubusercontent.com/58882903/157977536-021cacff-be90-4460-a7a0-6f2a23233402.jpg)

**Comment by guymass** [comment]
The language file is OK, no duplicates and I also changed the name few times but it doesn't want to translate. It seems that this menu item is connected to the main Live button at the top so maybe there is something there causing a problem idk.

![Screen Shot 5782-07-11 at 18 50 20](https://user-images.githubusercontent.com/58882903/158221118-d77d8d35-6f7c-45ce-841d-100931bf44de.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, thanks I found something. I will send an update soon

**Comment by guymass** [comment]
There are few english typos in the language files you should also fix. I am translating the Hebrew file now and will send it to you when im done. Here are two I found in the hebrew file so I presume they also appear in the other english file.
![Screen Shot 5782-07-15 at 21 30 09](https://user-images.githubusercontent.com/58882903/159071642-1a1b8119-a6be-4f85-bc3e-4908e5b5c584.jpg)
![Screen Shot 5782-07-15 at 21 30 17](https://user-images.githubusercontent.com/58882903/159071649-abfd1de1-22cb-4c54-a754-2cfb73bd4931.jpg)

**Comment by guymass** [comment]
Not sure what this is so I give it a new spot:

![Screen Shot 5782-07-15 at 22 29 24](https://user-images.githubusercontent.com/58882903/159078844-80fe674c-94e0-48ec-8c4d-879a31bc739f.jpg)

**Comment by guymass** [comment]
"Transferring" and "Broken Missing files" cannot be translated as well.
![Screen Shot 5782-07-15 at 23 25 27](https://user-images.githubusercontent.com/58882903/159084921-d6b07062-9078-4b48-ae9b-4927203e676d.jpg)

**Comment by guymass** [comment]
"Encode Video" also doesn't translate. There are no duplicates but it does appear in other sentences.
![Screen Shot 5782-07-15 at 23 27 59](https://user-images.githubusercontent.com/58882903/159085186-9eec8b61-d9ce-4ab8-89e4-46161eabfe7a.jpg)

**Comment by guymass** [comment]
here is my he_IL.php please add its translation, just replace file extension back to php, I change to txt so I can uplaod it here.

[he_IL.txt](https://github.com/WWBN/AVideo/files/8307748/he_IL.txt)

**Comment by guymass** [comment]
How can we add "direction=rtl" to the whole site including the admin area when selecting the Hebrew language?

**Comment by guymass** [comment]
BTW these until today I still cannot get to translate.
![Screen Shot 5782-07-16 at 0 07 06](https://user-images.githubusercontent.com/58882903/159091132-641f19c8-da81-41da-99d3-e7d6f7ceebc7.jpg)
![Screen Shot 5782-07-16 at 0 07 15](https://user-images.githubusercontent.com/58882903/159091135-c6bb53df-4a4f-4bf8-aaa6-96739fd905c5.jpg)
![Screen Shot 5782-07-16 at 0 07 11](https://user-images.githubusercontent.com/58882903/159091140-325cdd27-d654-4654-87d4-0bd4d8ba4d3e.jpg)
![Screen Shot 5782-07-16 at 0 07 22](https://user-images.githubusercontent.com/58882903/159091141-9727ad50-0e07-4591-a31b-d2467ea67f5c.jpg)

**Comment by guymass** [comment]
Also I pulled latest updates, cleared caches and refreshed to see if it fixes those other missing translation like in the top of this post but still they remain the same.
![Screen Shot 5782-07-16 at 0 17 04](https://user-images.githubusercontent.com/58882903/159091816-30cbebdd-73c6-4792-91d8-a930d393a4dc.jpg)

**Comment by guymass** [comment]
YPTSocket is only translating the "Connected" title, the rest will not translate i tried.

![Screen Shot 5782-07-16 at 0 20 37](https://user-images.githubusercontent.com/58882903/159092092-b60562ee-9295-4683-bb44-e0b9c7797c20.jpg)

**Comment by guymass** [comment]
Here are my latest.

[he_IL.txt](https://github.com/WWBN/AVideo/files/8308811/he_IL.txt)
[en_US.txt](https://github.com/WWBN/AVideo/files/8308812/en_US.txt)

**Comment by guymass** [comment]
This button on programs tab will not translate as well, only partially as it seems to be constructed from two separate words.
![Screen Shot 5782-07-16 at 18 36 04](https://user-images.githubusercontent.com/58882903/159130076-472e5534-f747-4990-8945-0b4e3461db3a.jpg)

**Comment by guymass** [comment]
I also noticed that my encoders remain in english when I open them, how do I set them to use the translation file.
![Screen Shot 5782-07-16 at 18 41 25](https://user-images.githubusercontent.com/58882903/159130195-52f57a3a-f11a-40e0-9522-5ab2c3f7ec01.jpg)

**Comment by guymass** [comment]
This also used to be translated and now only showing in english even when HE is selected.

![Screen Shot 5782-07-16 at 19 12 27](https://user-images.githubusercontent.com/58882903/159131273-9afebf23-8d2f-489c-afe8-e8e7fd651542.jpg)

**Comment by guymass** [comment]
You have a typo here, Adertising should be Advertising
![Screen Shot 5782-07-16 at 19 52 19](https://user-images.githubusercontent.com/58882903/159132693-23a38e28-a6ae-403e-879e-3d44454ca1a4.jpg)

**Comment by DanielnetoDotCom** [comment]
> This also used to be translated and now only showing in english even when HE is selected.
> 
> ![Screen Shot 5782-07-16 at 19 12 27](https://user-images.githubusercontent.com/58882903/159131273-9afebf23-8d2f-489c-afe8-e8e7fd651542.jpg)

Currently we have no option to translate it

**Comment by DanielnetoDotCom** [comment]
> I also noticed that my encoders remain in english when I open them, how do I set them to use the translation file. ![Screen Shot 5782-07-16 at 18 41 25](https://user-images.githubusercontent.com/58882903/159130195-52f57a3a-f11a-40e0-9522-5ab2c3f7ec01.jpg)

There is no translation for encoders

**Comment by DanielnetoDotCom** [comment]
> This button on programs tab will not translate as well, only partially as it seems to be constructed from two separate words. ![Screen Shot 5782-07-16 at 18 36 04](https://user-images.githubusercontent.com/58882903/159130076-472e5534-f747-4990-8945-0b4e3461db3a.jpg)

Create a translation for Programs separately

$t['Programs'] = '...';

**Comment by guymass** [comment]
I have it separately and it was translating before, but now for some reason it doesn't and Im not sure why. Maybe another "Programs" somewhere is interrupting it. There are no duplicate entries.

**Comment by DanielnetoDotCom** [comment]
can you please paste here the URL you can see that button with the program word?

can you do it on demo site, so I can inspect and find where it is missing?

**Comment by guymass** [comment]
I don't have a demo site and the URL is basically the link to My Channel under the tab of programs on the programs page itself there is the button there. This is my URL:
https://alive528.com/view/channel.php?channelName=Streamer528&lang=he_IL

* Also when I click My Channel or My Videos it will transfer me back to an english template and I need to select again the Hebrew language.

**Comment by DanielnetoDotCom** [comment]
> 

I guess I found it. I just sent an update

**Comment by guymass** [comment]
Great I will update and test today.

**Comment by guymass** [comment]
OK some new found translation issues, here are screen shots of  two things not translating, one is the category list in the stream page for selecting the category and we have those translated and working on the left menu.

On the same page there are two buttons on the right side of the page for the restream list, the "Previous" and "Next" buttons will not translate. I don't have duplicates but the word Next appears in several other text entries.
![Screen Shot 5782-07-21 at 21 50 42](https://user-images.githubusercontent.com/58882903/159999298-f3301e4e-8c93-4827-a3ac-185d41b17e87.jpg)
![Screen Shot 5782-07-21 at 21 50 50](https://user-images.githubusercontent.com/58882903/159999308-775aeefa-b297-4afb-8ceb-e521d81767d4.jpg)

**Comment by guymass** [comment]
Also still having issue with the "Publish Live" translation for this menu item:
![Screen Shot 5782-07-21 at 22 18 31](https://user-images.githubusercontent.com/58882903/160002915-31d176ac-7bb0-4acb-9a9d-4022de964d73.jpg)

**Comment by guymass** [comment]
BTW here are two updates language files with many more missing and fixed translations, just change the extention back to php.
[he_IL.txt](https://github.com/WWBN/AVideo/files/8345220/he_IL.txt)
[en_US.txt](https://github.com/WWBN/AVideo/files/8345222/en_US.txt)

**Comment by guymass** [comment]
This also will not translate and im not sure as it seems miss-placed:

![Screen Shot 5782-07-21 at 23 48 04](https://user-images.githubusercontent.com/58882903/160016001-373f9b01-f386-4028-b0cc-3e4445553fb5.jpg)

**Comment by DanielnetoDotCom** [comment]
> OK some new found translation issues, here are screen shots of two things not translating, one is the category list in the stream page for selecting the category and we have those translated and working on the left menu.
> 
> On the same page there are two buttons on the right side of the page for the restream list, the "Previous" and "Next" buttons will not translate. I don't have duplicates but the word Next appears in several other text entries. ![Screen Shot 5782-07-21 at 21 50 42](https://user-images.githubusercontent.com/58882903/159999298-f3301e4e-8c93-4827-a3ac-185d41b17e87.jpg) ![Screen Shot 5782-07-21 at 21 50 50](https://user-images.githubusercontent.com/58882903/159999308-775aeefa-b297-4afb-8ceb-e521d81767d4.jpg)
> 
> The word "views" here also will not translate:
> 
> ![Screen Shot 5782-07-21 at 22 14 05](https://user-images.githubusercontent.com/58882903/160002211-4bab7e57-bf49-4135-b8c4-b1b4fbdc4ff9.jpg)

Password Protect should be there, you just need to create the translation in your file.

For the category, I just sent some updates that may translate it

**Comment by DanielnetoDotCom** [comment]
the grid I cannot translate it, I depend on bootstrap translation

**Comment by DanielnetoDotCom** [comment]
> BTW here are two updates language files with many more missing and fixed translations, just change the extension back to php. [he_IL.txt](https://github.com/WWBN/AVideo/files/8345220/he_IL.txt) [en_US.txt](https://github.com/WWBN/AVideo/files/8345222/en_US.txt)

Please make a. pull request

**Comment by DanielnetoDotCom** [comment]
> Also still having issue with the "Publish Live" translation for this menu item: ![Screen Shot 5782-07-21 at 22 18 31](https://user-images.githubusercontent.com/58882903/160002915-31d176ac-7bb0-4acb-9a9d-4022de964d73.jpg)
> 
> I tried splitting them up and combining them but nothing effects them.

You also need to translate` $t['Publish Live'] = "...";`

**Comment by guymass** [comment]
Now categories are translated however notice that it sometimes opens the english page while categories are in hebrew.

![Screen Shot 5782-07-22 at 23 40 37](https://user-images.githubusercontent.com/58882903/160197958-7d205462-a100-4fbc-aa7b-a3f1bf478461.jpg)

**Comment by guymass** [comment]
I think I figured it out why the languages keep changing for me, and its because I tend to click the logo to return to the home page and this basically takes me to the english default page although the site is set to Hebrew language as you can see here:
![Screen Shot 5782-07-25 at 22 02 26](https://user-images.githubusercontent.com/58882903/160468432-dad384f1-171d-441d-8514-d1a39926e942.jpg)

An than at time when I go back to my language it will "sometimes" open an english page like in the photo above for creating a live stream, the details of the post where the categories are will remain in Hebrew while the rest of the iframe page will open in English. 

Again this is probably because for some reason when I click the logo to go back to the home page it will load an English page and not the site's default language or the one I selected.
