### ISSUE TITLE
Could you please make articles to be like YouTube posts please

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#6346]
Please if we could have articles looking like this.

![Screenshot_20220307_032705](https://user-images.githubusercontent.com/72950503/156952932-75c46d7e-fbee-4402-8cf0-9fb0aac5eac0.jpg)

**Comment by DanielnetoDotCom** [comment]
can you please share here the youtube link for this page?

I would like to see how it looks like on a web browser

**Comment by mrgodgiven** [comment]
Here is the link

[[832977](https://www.youtube.com/c/brandy/community)](https://www.youtube.com/c/brandy/community)

**Comment by DanielnetoDotCom** [comment]
this update should change the layout a little bit
