### ISSUE TITLE
Hebrew URL conversion in post

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6347]
When I paste URLs which contain hebrew characters is will convert the link to this unreadable string. Is it possible to have this field retain the correct URL name with the hebrew text?

I want to paste the original link here but this text field does the same conversion and thus it changes to this:
https://ie2020.net/%d7%99%d7%95%d7%a6%d7%90%d7%99%d7%9d-%d7%9c%d7%98%d7%99%d7%a1%d7%aa-%d7%97%d7%99%d7%9c%d7%95%d7%a5/

![Screen Shot 5782-07-04 at 16 47 18](https://user-images.githubusercontent.com/58882903/157056952-c88021d3-15dd-469d-8c5a-859d86332bdb.jpg)

**Comment by DanielnetoDotCom** [comment]
Can you please paste the url here so I can test?

**Comment by DanielnetoDotCom** [comment]
So I suspect these letters are not browser friendly.

if does not work here I guess it will also not work on our page

**Comment by guymass** [comment]
But these are the same Hebrew letters we use on text fields, video titles etc.. so why with URLs it will encode them like that? Also the URLs the are generated by the system for each video, if we paste those we get the same issue but only with URLs.

**Comment by DanielnetoDotCom** [comment]
probably those characters are not allowed in the URL

we just keep the characters on the URL to help with the SEO

I am not sure if in your case (Hebrew chars) it helps

If you want you can disable the characters here ...

![image](https://user-images.githubusercontent.com/18009293/157447085-99dad483-7361-4558-b24f-09680e3f39c8.png)

**Comment by guymass** [comment]
OK thanks I will try that.
