### ISSUE TITLE
Why advertise between movies can't play?

### ISSUE THREAD

**Issue by aliceglitch** [WWBN/AVideo#6349]
Hi, I did steps for playing of advertising video between broadcast, But only appear sign of ad video (bottom, left side of screenshots), why do not ad video between broadcast? version of youphptube script is 11.1 as shown in screenshots.
Thanku.

![1](https://user-images.githubusercontent.com/72448881/157089128-d73a013e-3603-48d0-b24a-625101d03014.png)
![2](https://user-images.githubusercontent.com/72448881/157089284-38c7550c-928d-40e8-8d85-35eaea673f46.png)
![3](https://user-images.githubusercontent.com/72448881/157089389-ab7c5453-1c5a-4c66-a322-0b378c96c877.jpg)

**Comment by DanielnetoDotCom** [comment]
check your JS console log.

the yellow checkmark does not mean you have the ads properly configured

Check this https://github.com/WWBN/AVideo/wiki/Ad-Server-Plugin

also, make sure you are using a MP4 self-hosted video

**Comment by aliceglitch** [comment]
> check your JS console log.
> 
> the yellow checkmark does not mean you have the ads properly configured
> 
> Check this https://github.com/WWBN/AVideo/wiki/Ad-Server-Plugin
> 
> also, make sure you are using a MP4 self-hosted video

Hi, Can I send you my host access and you update the script on the host for me?

**Comment by DanielnetoDotCom** [comment]
@aliceglitch you can hire me for direct support.

you can purchase the support here https://youphp.tube/marketplace/

**Comment by aliceglitch** [comment]
Hi, I want to bring the video of the advertisement like the educational video (according to the attached figure), but my script in the regular configuration tab (according to the attached figure) is different from the regular configuration tab of the script in the educational film, so how can I follow the film to bring the advertisement?
![111](https://user-images.githubusercontent.com/72448881/167303185-332bd46b-c3cc-4508-bbf5-10599af00aad.jpg)
![222](https://user-images.githubusercontent.com/72448881/167303188-c17935d2-32da-4f6c-9b97-f8a98790c5ab.jpg)
![333](https://user-images.githubusercontent.com/72448881/167303194-b5ffbd1d-543c-4fd0-ba6c-2f39d71172a7.jpg)
![444](https://user-images.githubusercontent.com/72448881/167303197-e737bf20-ea4b-4753-9eb5-2992cda62cd2.jpg)

**Comment by DanielnetoDotCom** [comment]
I am not sure what you want to do , but the video tutorial is an older version. But you should still have all the options on it

**Comment by aliceglitch** [comment]
> I am not sure what you want to do, but the video tutorial is an older version. But you should still have all the options on it

Hi, I filled in these fields for the advertising video. Are these enough and correct?
![1](https://user-images.githubusercontent.com/72448881/169331321-6f357f7b-9568-4d71-aba2-0cc23a50ea8f.png)
![Untitled](https://user-images.githubusercontent.com/72448881/169331376-d6c697cd-b7d9-4781-a0d5-a68fca5a7dfe.png)
![Untitled1](https://user-images.githubusercontent.com/72448881/169331442-d6aa4157-a945-475f-a92c-65ce19f6c59c.png)
![Untitle9](https://user-images.githubusercontent.com/72448881/169331540-b9a15788-e0d1-481a-9343-4d4d2353e1ac.png)
![Untitle8](https://user-images.githubusercontent.com/72448881/169331580-780a3eb6-7c98-4f1c-94bd-c6dd7cb53c3c.png)

**Comment by DanielnetoDotCom** [comment]
Hi

only item 11 is not necessary
also for some reason looks like your videos are not working. 

at least the ones on the screenshot seems to do not have the thumbnail

**Comment by aliceglitch** [comment]
Hi, the videos do not have the thumbnail, but they are played and they do not have any problem, so why the advertising video is not played between the movies?

![photo_2022-05-25_18-37-09](https://user-images.githubusercontent.com/72448881/170282761-851ea578-29be-453e-993c-40fdba90a690.jpg)
![photo_2022-05-25_18-38-11](https://user-images.githubusercontent.com/72448881/170282827-82e3e9e5-d491-4e52-8325-8aaa933d078f.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi

the ad_server plugin is only tested if the ad video is self-hosted and also the video (where the ad will play) is also self-hosted

otherwise, the result is unpredictable.

**Comment by aliceglitch** [comment]
So 1489 videos (where the ad will play) remain unused? Is there any plugin for these 1489 videos to be a place to play ads? If there is no plugin for these 1489 videos, then what is the use of uploading a video with the link? Is there a way in the script to turn these 1489 videos into self-hosted videos If there is no plugin?

**Comment by DanielnetoDotCom** [comment]
If those 1489  videos are embedded from somewhere else, there is no guarantee it will work

**Comment by DanielnetoDotCom** [comment]
If you want to self-host them, you MUST use the encoder.

**Comment by aliceglitch** [comment]
Hello, I installed AVideo with VMWare and Ubuntu 22.04 on the LAMP, and then I installed Encoder, but why is there no place on the screen to upload a video in bulk from YouTube? How should I upload a video from YouTube in bulk, corresponding to a training video on the screen?
Thanks

![photo_2022-08-06_12-53-34](https://user-images.githubusercontent.com/72448881/183241231-8ee5a750-c1f2-4550-b23c-eab1a032be6e.jpg)
![photo_2022-08-06_12-55-47](https://user-images.githubusercontent.com/72448881/183241243-c466d1dc-27c3-41ac-a203-03a065431736.jpg)

**Comment by DanielnetoDotCom** [comment]
I guess your last post has nothing to do with this issue.

please open a new issue for your encoder question
