### ISSUE TITLE
Live Youtube Streams Clone of Live Links but using yt links instead

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6350]
Basically clone the Live Links plugin but instead of m3u8 links youtube stream links or other live stream links like yt

https://www.youtube.com/watch?v=hMHEHHk3gNo

![43229997-9342-43f8-b6b6-6ede9934858d](https://user-images.githubusercontent.com/39392449/157149174-12620be8-ce3e-49c8-93c5-ddbb2e191d8c.png)

**Comment by JoshWho** [comment]
The player seems to be able to do it https://www.joshwhotv.com/video/.QDsn2g/%F0%9F%94%B4-live-your-favourite-cops-moments-%7C-cops-tv-show-%7C-24-7-live-stream-2022-03-07-19-46

Hope this could be something easy to do. It would be a very attractive feature.

**Comment by DanielnetoDotCom** [comment]
This should do the trick

**Comment by JoshWho** [comment]
That is awesome thank you @DanielnetoDotCom  Would be kewl if it used the avideo player for it but this still works. I have the test here. https://www.joshwhotv.com/liveLink/161/test

**Comment by CROSSMediaNet** [comment]
> That is awesome thank you @DanielnetoDotCom
> 
> it is not using the Avideo custom player for it, Currently showing Youtubes PLayer but this still works. I have the test here. https://www.joshwhotv.com/liveLink/161/test
> 
> ![64e21d53-52fb-49a8-be31-2bb58f6cbd2d](https://user-images.githubusercontent.com/39392449/157289308-890bd096-e630-4fc6-8200-72a261a77836.png)

Question: do you have to update your site for your test?

**Comment by JoshWho** [comment]
Yes just run a git pull it will allow yt links now in the m3u8

**Comment by CROSSMediaNet** [comment]
Prefect... do that later today after some of the broadcasts from other users...thanks

**Comment by JoshWho** [comment]
> Also, we can do this from other places, like Oydessy, Rumble, and other platforms, correct?

Honestly I havent tried it yes but I am assuming as long as it is the embed url it should work like this for other platforms.

**Comment by CROSSMediaNet** [comment]
Cool...I also like your idea about having the actual channel with its live streaming. I also wonder can we embed that page, with the live stream and correspond videos with it

**Comment by JoshWho** [comment]
Yes this should work. The embed link is editable so U can always change it once the finished encoded stream gets done. Just make the actual one unlisted.

**Comment by JoshWho** [comment]
> That is awesome thank you @DanielnetoDotCom
> 
> it is not using the Avideo custom player for it, Currently showing Youtubes PLayer but this still works. I have the test here. https://www.joshwhotv.com/liveLink/161/test
> 
> ![64e21d53-52fb-49a8-be31-2bb58f6cbd2d](https://user-images.githubusercontent.com/39392449/157289308-890bd096-e630-4fc6-8200-72a261a77836.png)

@DanielnetoDotCom can you make it use the Avideo player instead of the youtube player?

**Comment by DanielnetoDotCom** [comment]
This last update should do the trick

**Comment by JoshWho** [comment]
> This last update should do the trick

Bravo Thank you. this is super awesome!!!!!!!!
