### ISSUE TITLE
You are able to embed your own live stream to make it appear on your channel!!!

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6351]
This is really kewl. I just figured out you can embed your own live stream and it will be seeable on your channel. So many people been asking for this and I guess this is a trick to do it.

Any way to make this a thing on here @DanielnetoDotCom  ? 

Look here for example
https://www.joshwhotv.com/v/.QDsn3Q?channelName=Infowars2

All I am doing is embedding the stream that is already streaming on my site using the embed url

https://www.joshwhotv.com/liveLinkEmbed/49/info-wars

![a7d39cb3-4442-483d-b26f-6634b4173e40](https://user-images.githubusercontent.com/39392449/157154444-9aba9669-bd4f-4e6e-a8d8-943afd96ce33.png)

**Comment by JoshWho** [comment]
![b002a112-7bae-4713-b651-02f68f63e5e2](https://user-images.githubusercontent.com/39392449/157152798-8b4e2506-237c-4c1c-b87f-c9e565f64e4a.png)

**Comment by DanielnetoDotCom** [comment]
thanks for sharing that

**Comment by JoshWho** [comment]
I was thinking this is a perfect method to show the live stream on the channel page, and also once the stream is over, have it embed the final version after it gets encoded.

That way the same link still links to the stream everyone just watched.

I believe this is how Youtube does it.

**Comment by CROSSMediaNet** [comment]
> I was thinking this is a perfect method to show the live stream on the channel page, and also once the stream is over, have it embed the final version after it gets encoded just replacing the live stream link with the finished upload that got encoded.
> 
> That way the same link on the channel to the stream will become the finished uploaded video as well.
> 
> I believe this is how Youtube does it.

Question: How did you make that happen to embed the live stream to that channel? I would love to learn how you did that so I can build it on my website as well.

**Comment by JoshWho** [comment]
> > I was thinking this is a perfect method to show the live stream on the channel page, and also once the stream is over, have it embed the final version after it gets encoded just replacing the live stream link with the finished upload that got encoded.
> > That way the same link on the channel to the stream will become the finished uploaded video as well.
> > I believe this is how Youtube does it.
> 
> Question: How did you make that happen to embed the live stream to that channel? I would love to learn how you did that so I can build it on my website as well.

I explain that all at the top https://github.com/WWBN/AVideo/issues/6351#issue-1162129583

**Comment by CROSSMediaNet** [comment]
I am having some problems with the embed to the channels page...I am must be doing something wrong or I got the wrong settings: 
![image](https://user-images.githubusercontent.com/62782361/157829015-a7cb73c6-e59c-4f9d-b082-c2573b7305b6.png)
