### ISSUE TITLE
Language message pop-up

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6353]
Dear, I would like to know where do I change the language for these message/warning pop-up? 
Is there a language script or is it a manual translation? The system is configured for Brazilian Portuguese.

![image](https://user-images.githubusercontent.com/37880073/157244727-e5da3bab-ba31-44a5-8064-875dd07c710f.png)

**Comment by DanielnetoDotCom** [comment]
Currently the files are hardcoded here 

https://github.com/WWBN/AVideo/tree/master/plugin/PlayerSkins/allowAutoplay

there is no translation for them

**Comment by gbrn** [comment]
@DanielnetoDotCom 

I need to do the site translations, which files should I change?
Without the proper translations, it is very complicated for the Brazilian user.

![image](https://user-images.githubusercontent.com/37880073/192165467-1b97f017-0a31-48fb-9f83-0a3c8eba6894.png)

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/192324140-b9a0525b-edb5-4019-b980-56912b50ec3a.png)

**Comment by gbrn** [comment]
Ok, thanks. I'm moving forward with the project and now I'm going to let all users login.
