### ISSUE TITLE
Error in translation

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#6354]
Correct the translation error in
the screenshot shown
language Russian
![12121](https://user-images.githubusercontent.com/54632469/157262167-49a8f067-2493-4f4b-b656-3977feae8df2.jpg)

4 месяца назад
3 месяца назад
3 года назад

**Comment by DanielnetoDotCom** [comment]
Can you please send a pull request?

**Comment by palich91** [comment]
Sent
