### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#6355]
Hi Daniel
Can you tell me if it is possible to give a color other than orange for each group I create?
Thanks, I await your response

![1](https://user-images.githubusercontent.com/82677269/157288594-079cdc42-4e55-4317-892c-14df78e833cf.PNG)

![3](https://user-images.githubusercontent.com/82677269/157289206-ad186f08-e68b-4ea9-a9f3-a34d6948c9ad.PNG)

**Comment by DanielnetoDotCom** [comment]
Those are predefined colors on the bootstrap color scheme you are using.

you can overwrite any color using CSS. but you MUST know how to deal with CSS first.

you can add your custom CSS here https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript

**Comment by sharknetwork24** [comment]
Ok.  I can try.

**Comment by sharknetwork24** [comment]
Please Daniel, reply to the email I sent you because I have a problem accessing the Marketplace.
Please fix it because I can't download updates.

https://youphp.tube/marketplace/?tab=plugin

Thank you
