### ISSUE TITLE
Live Streaming Video

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#6356]
I have uploaded videos on the channel.
How do I get them to go live by programming?
I would like to get the same thing as on your test site.
Can you kindly explain me the steps to do it too?
Thanks Daniel

![4](https://user-images.githubusercontent.com/82677269/157291088-faa97a37-40a6-423c-9184-e32fd4621d1f.PNG)

**Comment by sharknetwork24** [comment]
How do I check this button?

![5](https://user-images.githubusercontent.com/82677269/157292977-8c1f19d3-856b-4667-a49e-64c8077cfa73.PNG)

**Comment by DanielnetoDotCom** [comment]
Currently there is no way to stop it

FYI, this feature is a beta feature, it is not finished yet

**Comment by sharknetwork24** [comment]
Tell me if I'm wrong Daniel. 
If I delete the video within the created series, can I stop the playback?

**Comment by DanielnetoDotCom** [comment]
To be honest, I am not sure

you can try to kill the PID of the restream

or you can try to stop the live server (Nginx) for 1 minute.

**Comment by sharknetwork24** [comment]
It would be very functional and welcome if you could integrate the possibility of stopping the live.

Could you take a test on your demo site to find out if this is possible?

**Comment by sharknetwork24** [comment]
How to close the PID of the restream?

**Comment by barrunning** [comment]
When I tried to use that feature it froze the webpage.

**Comment by DanielnetoDotCom** [comment]
Hi, I recommend you guys to not use it yet...

to kill the PID please use google to find out how to

**Comment by sharknetwork24** [comment]
Can you indicate a website where he explains the thing?
Thank you

**Comment by DanielnetoDotCom** [comment]
@sharknetwork24 do you need to kill it now?

It requires some skills to first find out what process is running the stream then you will use the `kill -9 [PID-NUMBER]`

the main problem is to find out the PID, you can list the main PIDs with the `top` command
