### ISSUE TITLE
Live stream indicates streaming but no stream is happening 

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6360]
Trying to do a live stream. 
nothing is being streamed.
![20B93C5E-C84B-4A3D-BAF5-512C7DD53798](https://user-images.githubusercontent.com/58601786/157362859-725a52d2-cb82-4a94-90f3-c5386973e970.png)

**Comment by barrunning** [comment]
From today
![999D3961-FF30-48D4-92A9-AFA67B46D3BA](https://user-images.githubusercontent.com/58601786/157429134-fe5c0782-b01e-4c4e-bf63-dade22659ecf.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, I see now. 

as long as this is a new installation the port is 8443, NOT 444 

I will fix it, please try again in 30 min

**Comment by DanielnetoDotCom** [comment]
Please try again now .

**Comment by barrunning** [comment]
Down to one error. Still not able to see the stream.  But it is being recorded.
![Uploading 80E34C5F-0CD4-4894-9D51-4D654DF8A80A.png…]()

**Comment by DanielnetoDotCom** [comment]
What site exactly are you testing?

**Comment by DanielnetoDotCom** [comment]
Hi, I guess I gound something. give me 10 minutes

**Comment by DanielnetoDotCom** [comment]
Tested and seems to be good now


![image](https://user-images.githubusercontent.com/18009293/157509968-4aad4c6f-aeb6-4078-9fac-9cca36d255fc.png)

**Comment by barrunning** [comment]
It is working. 
now how do I stream a video?
