### ISSUE TITLE
Any way to ad the JoshWho Analytic Field to account edit

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6361]
In the account editor for admin is there a way you can also add the JoshWho Analytic box to it?

![d8b6b5d1-43e4-4149-a3b8-726fc5d9d96a](https://user-images.githubusercontent.com/39392449/157494263-14572f7e-f8f1-475b-86b5-f384706a507c.png)

**Comment by DanielnetoDotCom** [comment]
Currently, you cannot edit certain information from users. only the user himself.

**Comment by JoshWho** [comment]
I c
