### ISSUE TITLE
error

### ISSUE THREAD

**Issue by G-only1** [WWBN/AVideo#6362]
**Describe the question**
i am getting this error and i do not know how to fix it

**Screenshots**
![Screenshot 2022-03-09 123241](https://user-images.githubusercontent.com/96492140/157507957-6227dca0-6472-424f-be1e-88dcf079e267.png)

**Comment by DanielnetoDotCom** [comment]
You are missing the php-gd

google for your error and you will find a solution

**Comment by G-only1** [comment]
Thank you
