### ISSUE TITLE
Please configure your webSiteRootPath

### ISSUE THREAD

**Issue by xSonic22** [WWBN/AVideo#6363]
Hello,

can someone please tell me how to fix this?
Please configure your webSiteRootPath

Everything was installed properly and yet I have this problem.
Also under configurations.php I could not find anything where I have to change something.
I have no more ideas.

I would be glad about a feedback.
Thanks a lot!

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/WWBN/AVideo/issues/5498#issuecomment-888234246
