### ISSUE TITLE
Chat login using the SOcial Buttons doesn't log in

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6364]
Seems like users that just log in from the chat get logged out on next page load. Only happens when logged in from the Chat2 plugin

**Comment by DanielnetoDotCom** [comment]
Is your chat running in a different domain?

the only way I can see this happening is if it is a cross-domain issue.

**Comment by JoshWho** [comment]
No this is a self hosted chat. not sure why the cookie gets treated differently.

**Comment by DanielnetoDotCom** [comment]
can you please share a page with a chat that does not stay connected?

**Comment by JoshWho** [comment]
Ok he just replied back to me saying it is the social logins for the chat

**Comment by DanielnetoDotCom** [comment]
can you please provide me some more details with some screenshots?

**Comment by JoshWho** [comment]
![5fab1146-5288-4ab5-99d4-421c36a84b4f](https://user-images.githubusercontent.com/39392449/158702423-5597650a-4eed-4716-8fd5-d9ac1169bc5d.png)

**Comment by JoshWho** [comment]
I just did a test with this and seems fine to me but needs a whole page refresh once logged in.

**Comment by JoshWho** [comment]
Not sure where they get the fb error

**Comment by JoshWho** [comment]
It just needs a full page refresh after login and should work fine. Watch this https://www.joshwhotv.com/video/.QDp4kQ/testing-social-logins

**Comment by DanielnetoDotCom** [comment]
is this the FB login?

maybe it is disabled from other accounts, maybe it is on test mode.

**Comment by DanielnetoDotCom** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18009293/158880504-2ac128c1-5a8a-4895-9128-e7a56b340b6d.png">


Acctually it is working fine

**Comment by JoshWho** [comment]
Trippy isn't it? I was hoping that was the problem too. I really think it works fine just needs a whole page refresh after login.
