### ISSUE TITLE
rtmp address is too long

### ISSUE THREAD

**Issue by Rolandhun74** [WWBN/AVideo#6365]
Hello

My question would be how to shorten the rtmp address

There is a one device that does not handle such a long address

THX

**Comment by DanielnetoDotCom** [comment]
Hi

now it is smaller. I hope it works now

**Comment by partystreamsk** [comment]
Hi Daniel, still long for me the rtmp address..

**Comment by DanielnetoDotCom** [comment]
Manually remove &webSiteRootURL=.... from the URL
maybe it does not makes any difference for you

**Comment by partystreamsk** [comment]
yes it will work , but can you remove it directly , so people that wanna stream will copy only rtmp://website.com/live ?

**Comment by Rolandhun74** [comment]
YES!!!

"09&webSiteRootURL=.... "
it does not makes any difference for me

**Comment by partystreamsk** [comment]
It will be great to have:

Server URL : rtmp://website.com/live
Stream name/key: 12345667 

It will be clear and clean. Number after "?" have no sense, stream key is important.

**Comment by DanielnetoDotCom** [comment]
this is unsecure

rtmp://website.com/live

we need the encripted key to avoid other users to use your live server

**Comment by partystreamsk** [comment]
stream key is safe enought. All streaming services like facebook, twitch , yutube are using simple url for streaming.
But if is hard to change  at least shorting url till &webSiteRootURL will be good upgrade. more clean.

**Comment by ganddser** [comment]
@partystreamsk Agreed the rtmp url is too long @DanielnetoDotCom it would be much better for integration if the url was standardized, rtmp://example.com/live or rtmp://example.com/live1 as for keeping it secure made we could switch to rtmps protocol that would keep streams secure and no one should be able to use anyone's server unless they some how get the stream key.
