### ISSUE TITLE
How Do You remove an Option on the main Web Page

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#6366]
Hi 

I would like to remove an option on the main page but not sure which plugin to go to.

I would like to remove the Channel Option seen here in the picture enclosed.. Where do I go ?

![kollossus channel editing](https://user-images.githubusercontent.com/53856825/157658484-45cf76cd-02bd-47fc-872c-fde99e8a81c8.png)

Regards

**Comment by DanielnetoDotCom** [comment]
Currently there is no option to hide it

**Comment by kollossus55** [comment]
ok.. How do you make it accessable to everyone. When users click on it, it doesn't allow videos to be seen from the admins channel.
Regards

**Comment by DanielnetoDotCom** [comment]
The channel also shows your playlists even if you cannot upload videos.

**Comment by kollossus55** [comment]
Which plugin or option enables the subscriber / user to view the admins channel.
Regards

**Comment by DanielnetoDotCom** [comment]
can you please screenshot what option do you mean?

**Comment by kollossus55** [comment]
A user signs in and clicks on the admins channel but cannot see that channel. Where to enable views of the admins channel for the user.

![kollossus channel editing2](https://user-images.githubusercontent.com/53856825/157758726-70511a76-cc44-4b64-ac6c-3067bbf4e397.png)
l

**Comment by DanielnetoDotCom** [comment]
Once you have a playlist you will see a playlist tab

if you do not have any video, the channel is not publicly available. only the channel owner can access it.
