### ISSUE TITLE
Unknown error.

### ISSUE THREAD

**Issue by Proton-people** [WWBN/AVideo#6367]
I installed the engine and did everything right. There is no connection to the base. Please tell me the solution to the problem. Thanks.
![bandicam 2022-03-10 18-43-27-680](https://user-images.githubusercontent.com/48072457/157699126-a644578a-aaf9-426d-91c5-4fb606554399.jpg)
![bandicam 2022-03-10 18-51-07-266](https://user-images.githubusercontent.com/48072457/157699554-decf1fc1-7570-4cdf-85e7-e0583a40db94.jpg)
[error.log](https://github.com/WWBN/AVideo/files/8224852/error.log)
![bandicam 2022-03-10 18-55-32-823](https://user-images.githubusercontent.com/48072457/157700500-3945baf3-2d18-4970-a86a-fcf6540d1b3b.jpg)

**Comment by DanielnetoDotCom** [comment]
<img width="786" alt="image" src="https://user-images.githubusercontent.com/18009293/157717339-1b551569-8404-43c9-8d0f-a7de3875b45c.png">

Make sure you have the correct parameters on the videos/configuration.php file

seems to me you are using an external database, and your server cannot resolve the host name

**Comment by Proton-people** [comment]
> <img alt="изображение" width="786" src="https://user-images.githubusercontent.com/18009293/157717339-1b551569-8404-43c9-8d0f-a7de3875b45c.png">
> 
> Убедитесь, что у вас есть правильные параметры в файле videos/configuration.php
> 
> мне кажется, вы используете внешнюю базу данных, и ваш сервер не может разрешить имя хоста

Hello Daniel. The file videos/configuration.php is empty. There was no such problem before. Can you tell me where could be the problem in mysql?

**Comment by Proton-people** [comment]
> <img alt="изображение" width="786" src="https://user-images.githubusercontent.com/18009293/157717339-1b551569-8404-43c9-8d0f-a7de3875b45c.png">
> 
> Убедитесь, что у вас есть правильные параметры в файле videos/configuration.php
> 
> мне кажется, вы используете внешнюю базу данных, и ваш сервер не может разрешить имя хоста

I'll try installing Wordpress for now and see how it works.

**Comment by DanielnetoDotCom** [comment]
It must not be empty

you have to check the Apache error log when you click on the install button

**Comment by Proton-people** [comment]
> Он не должен быть пустым
> 
> вы должны проверить журнал ошибок Apache, когда вы нажимаете кнопку установки

![bandicam 2022-03-11 17-11-02-385](https://user-images.githubusercontent.com/48072457/157884089-dcef69af-c098-4dfc-bb7f-1efa3036828f.jpg)
![bandicam 2022-03-11 17-13-37-277](https://user-images.githubusercontent.com/48072457/157884116-a4af7030-08ff-45d4-b6b9-cf5530660217.jpg)

**Comment by Proton-people** [comment]
> videos/configuration.php

Daniel, can I fill in the videos/configuration.php file myself? Where to get content?

**Comment by DanielnetoDotCom** [comment]
I do not think you are filling the parameters correct on the installation form

check your database host name

**Comment by DanielnetoDotCom** [comment]
> > videos/configuration.php
> 
> Daniel, can I fill in the videos/configuration.php file myself? Where to get content?

strongly not recommended

**Comment by Proton-people** [comment]
> Я не думаю, что вы правильно заполняете параметры в форме установки
> 
> проверьте имя хоста вашей базы данных

Daniel you are great. I didn't see the rock and hit it with my head. Thank you friend.
