### ISSUE TITLE
errors needs your attention

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6369]
Hi Daniel
I have such an error 

` [10-Mar-2022 20:40:40 Europe/Berlin] AVideoLog::SECURITY: ddosProtection:: progressive timeout timeoutReal = (5) active_connections = (40) maxCon = (40)  SCRIPT_NAME: /view/xsendfile.php`

**Comment by DanielnetoDotCom** [comment]
this is too many requests from the same client.

chek your apache access log on that specific time for more clues

**Comment by KrzysioMisio** [comment]
and how to do it ?
in the Ubuntu terminal I have
There is 1 zombie process.
Z        939   12328 apache2 <defunct>
how to kill him?

**Comment by DanielnetoDotCom** [comment]
the information on the log is not really an issue, but it is something to have your eyes opened.

but I cannot teach how to check logs or how to identify a cause

**Comment by KrzysioMisio** [comment]
ok, 
I managed   :-)
