### ISSUE TITLE
Search Channels Error

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#6372]
Browse Channels; Search Channels gives exception error. AVideo is current with latest pull.

![SearchChannelsError](https://user-images.githubusercontent.com/85363361/157765327-70a1ce61-c3a1-4bc9-92ad-6f892b80a6b7.jpg)
[avideoLog_SearchChannelsError.txt](https://github.com/WWBN/AVideo/files/8227547/avideoLog_SearchChannelsError.txt)

**Comment by DanielnetoDotCom** [comment]
Can you please make a git pull and check again?

**Comment by GreenDragonTavern** [comment]
That did it, thank you.
