### ISSUE TITLE
Changing Domain Name cause some Encoder issues

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6374]
We have changed our domain name and now I get this error when trying to open the network encoder.
I changed the settings to refelect the new domain name in the network encoder and also the plugins like Live and Customize Advance. I can access the encoder with direct URL https://live.alive528.com/Encoder however not from within the site in an IFRAME.

Also, the users listed in the encoder as streamers are still having their old URLs registered as you will see in the next images.

Here are some screenshots of the changes I made and we have checked that all domain redirections are working fine so we must miss something small we overlooked.

![Screen Shot 5782-07-08 at 12 53 16](https://user-images.githubusercontent.com/58882903/157853785-5beb853b-072d-4fcd-a419-e81b904080fe.jpg)
![Screen Shot 5782-07-08 at 12 39 01](https://user-images.githubusercontent.com/58882903/157854432-66a575c4-1241-45cf-b147-e7b28fdb9f74.jpg)

The changes I made in the plugins:
![Screen Shot 5782-07-08 at 12 43 04](https://user-images.githubusercontent.com/58882903/157854515-d8d8e223-8282-4378-9b8a-de03c3ba0ddc.jpg)
![Screen Shot 5782-07-08 at 12 47 58](https://user-images.githubusercontent.com/58882903/157854537-44e0f688-70ca-4304-af75-830fcea11e8e.jpg)

**Comment by guymass** [comment]
This is the Encoders config as well as the checkConfiguration script output.

![Screen Shot 5782-07-08 at 13 03 44](https://user-images.githubusercontent.com/58882903/157855225-193bbf2f-9363-4e5d-b430-6006e652a8a8.jpg)
![Screen Shot 5782-07-08 at 13 03 53](https://user-images.githubusercontent.com/58882903/157855325-383dbc18-b849-4c3d-b79a-1cd77d927df4.jpg)

**Comment by guymass** [comment]
I ran these two commands for the encoder however I need to change the URL don't I?
![Screen Shot 5782-07-08 at 13 26 01](https://user-images.githubusercontent.com/58882903/157858432-408b9daa-cd89-467f-9726-e8792f8b7824.jpg)

**Comment by DanielnetoDotCom** [comment]
check your videos/configuration.php file.

looks like the database user name is missing, also update the domain on the configuration.php file

in worst case just drop the database and reinstall it

**Comment by guymass** [comment]
You mean the encoder database right?

**Comment by DanielnetoDotCom** [comment]
yes, I mean this error

![image](https://user-images.githubusercontent.com/18009293/157866081-fbfe4c3b-5984-41f8-9d86-4bf66d871f2e.png)

**Comment by guymass** [comment]
How do I change the SiteURL for all my streamers? I think if those where pointing to the correct url then it would work and I wont have to drop the database.

![Screen Shot 5782-07-08 at 15 01 03](https://user-images.githubusercontent.com/58882903/157871353-11c0dfb2-05c8-4e1b-beec-ca10f540d5d7.jpg)

**Comment by guymass** [comment]
OK that wasn't that hard, I replaced them all with this SQL Update:
update streamers set siteURL = "https://live.alive528.com/" where siteURL = "https://live.ahava528.com/";

Now lets test

**Comment by guymass** [comment]
OK I fixed it, is this the new Look of the page? and also how do I add again my user as an admin on the encoders?
![Screen Shot 5782-07-08 at 15 21 15](https://user-images.githubusercontent.com/58882903/157874708-9ff146df-edfe-4aae-bde9-2e07d9b6524b.jpg)

**Comment by guymass** [comment]
OK I got it through the php makeAdmin.php script and now all is back to normal. I will keep this open for a while just to make sure once we do more testing.

**Comment by guymass** [comment]
OK Now the problem is that live stream will not show on notification bell and front page and also no encoding takes place once the stream is done.

**Comment by DanielnetoDotCom** [comment]
can you make sure you are really live and this is listed on the plugin/Live/stats.json.php page? 
https://demo.avideo.com/plugin/Live/stats.json.php

If it is, please share that information

![image](https://user-images.githubusercontent.com/18009293/157879921-d0eb9a16-9db4-42ed-bc15-a283101d3fe3.png)


also, check if you were not using the domain you changed on the nginx.conf

also, check the plugin's parameters (Live and recorder)

also, check if the live has "Make Stream Publicly Listed" checked

also check the log files

**Comment by guymass** [comment]
OK things are now back to normal how ever I see these errors in log:
![Screen Shot 5782-07-08 at 23 11 19](https://user-images.githubusercontent.com/58882903/157974415-630f5dc1-fb8b-4d95-b805-960cbde6540b.jpg)
![Screen Shot 5782-07-08 at 23 10 20](https://user-images.githubusercontent.com/58882903/157974427-97731e7d-7f79-42d4-b2ff-759367c93165.jpg)

**Comment by DanielnetoDotCom** [comment]
I guess you do not have the latest git pull

**Comment by guymass** [comment]
We have made changes to our domain name and had to consider all sorts of changes and I have the latest pull. We have fixed most issues and everything is working fine now with the new domain name. I will keep testing for a day before I close this just in case.
