### ISSUE TITLE
Update from 11.4 to 11.6 fails.

### ISSUE THREAD

**Issue by nfguide** [WWBN/AVideo#6375]
**Describe the bug**
git pull update fails

**To Reproduce**
git pull on version 11.4

**Expected behavior**
update completes

**Error Logs**
plugin/Scheduler/Objects/Scheduler_co
error: The following untracked working tree files would be overwritten by merge:
        admin/premium.php
        plugin/AutoPostOnSocialMedia/AutoPostOnSocialMedia.php

**Screenshots**
See attached
![220311_git-pull-error](https://user-images.githubusercontent.com/29156911/157986153-ff9ba4f9-451d-4024-a286-f0c1aa2a2858.jpg)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by DanielnetoDotCom** [comment]
try this instead

`sudo git fetch --all && sudo git reset --hard origin/master`

**Comment by nfguide** [comment]
That worked.
sudo git fetch --all && sudo git reset --hard origin/master

Why did the above work and git pull did not?
