### ISSUE TITLE
Long time to initiate a new stream and more

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6376]
This is the issue and maybe there is a way to optimize it. After starting a new stream from OBS and the rate is showing green on the my channel video stream page it will take approx between 30sec to 1m sometimes more to start showing the stream so there is a big delay. However the main issue is when starting new stream and this is for all streams. The stream page will first remember the last stream and will play that stream from memory until the new stream arrives and replaces it.

Is it possible for it to clear that stream and not show anything besides the post image so it doesn't confuse viewers.

**Comment by DanielnetoDotCom** [comment]
the green online label only appears when the m3u8 file is available.

I am not sure what you can do to make it happen faster, you may have some help on the Nginx RTMP GitHub page.

**Comment by JoshWho** [comment]
It caches your last stream and keeps it in there until it gets overwritten by the new stream.

**Comment by guymass** [comment]
So I would like to clear that cache after the stream is over, is it possible?

**Comment by DanielnetoDotCom** [comment]
> So I would like to clear that cache after the stream is over, is it possible?

The Live stats should be cleared on each on_publish and on_publish_done

**Comment by guymass** [comment]
I will test again but I think they are not cleared because they show the last stream until the new one starts.

**Comment by guymass** [comment]
OK wonderful, translation seems to be fixed also for the home page, finally it's also translating. I will keep this open for a while and do some more tests tomorrow and hopefully this will close this post.

Much thanks, god bless.
