### ISSUE TITLE
Strange error message opening Dashboard

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6377]
I get this error message when opening my dashboard, not sure what it means.

![Screen Shot 5782-07-09 at 2 39 42](https://user-images.githubusercontent.com/58882903/157995963-aede01b3-640a-4394-ae39-2169a92889b2.jpg)

**Comment by DanielnetoDotCom** [comment]
check your avideo log and also your js log

it is an error on some ajax requests.

**Comment by guymass** [comment]
Last updates seem to fix this issue I don't know what you have done but I can now open the page much faster and I don't see that error anymore, awesome, closing this one as well.
