### ISSUE TITLE
Change the Clean Title will update the URL, but the old URL still works?

### ISSUE THREAD

**Issue by baoang** [WWBN/AVideo#6381]
**Describe the question**
in the admin control panel, **contents->videos**, admin users can modify the url of a video. For example, 
```
https://avideo.mydomain.tld/video/11/i-love-avideo
```
can be modified to 
```
https://avideo.mydomain.tld/video/11/we-love-avideo-platform
```
This also happens in the scenario that I replace the video from Encoder (so that I'll change the title of the video, thus the clean title/url changes).

However, I found that the old url still works. If I visit *.../we-love-avideo-platform*, the new URL, it works, and if I visit *.../i-love-avideo*, the old URL also brings visitors to the same update video.

I checked the MariaDB data, but there seems to be nothing hinting or relevant.

How can I remove the old URL and keep only the updated one?

**Comment by DanielnetoDotCom** [comment]
Not really, again, the ID is what defines it. and the ID is unchangable

**Comment by baoang** [comment]
> Not really, again, the ID is what defines it. and the ID is unchangable

OK, I caused some confusion. What I mean is the clean title (instead of the URL, which includes both the ID and the clean title).
To be more specific, after changing the (clean) title to *we-love-avideo-platform*, the working URL becomes

```
https://avideo.mydomain.tld/video/11/we-love-avideo-platform
```
and it should be the only working URL for that video, but in fact

```
https://avideo.mydomain.tld/video/11/i-love-avideo
```
is also a working URL. How can I remove this one, making it inaccessible?
