### ISSUE TITLE
Question about the encoder folder

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#6382]
Can I delete the contents in /var/www/html/youphptube/encoder/videos or would that break the site. I see a lot of temp files in there taking up space in my server. Please see the attached screenshot
![encoder](https://user-images.githubusercontent.com/58635493/158065044-f0f47da1-dd0f-4c05-88ac-f0851d00a710.JPG)

**Comment by DanielnetoDotCom** [comment]
definitely you can delete them (if they are not encoding)

I am not sure why it is not automatically deleting
