### ISSUE TITLE
Encoder won't go past this stage

### ISSUE THREAD

**Issue by G-only1** [WWBN/AVideo#6383]
the encoder will not go past this point when I try to upload a video

![Screenshot 2022-03-14 112459](https://user-images.githubusercontent.com/96492140/158216601-8f3cd075-75c0-48a1-8ea7-eb568c8e8229.png)

**Comment by G-only1** [comment]
it is a public encoder

**Comment by DanielnetoDotCom** [comment]
your site is not properly installed

http://jetdoge.tk/JetTube/AVideo-master/AVideo-master/info

**Comment by G-only1** [comment]
ok what do i need to do to get it properly installed?

**Comment by G-only1** [comment]
ok thank you for your help
