### ISSUE TITLE
User having trouble removing the password protection for live stream

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6385]
He says he deletes it and clicks save and the password just goes back for some reason

**Comment by JoshWho** [comment]
Is there a way to disable Autofill for that?

![download (2)](https://user-images.githubusercontent.com/39392449/158240110-f0173a29-bbe2-4955-b8a1-3b8df8af41a9.png)

**Comment by DanielnetoDotCom** [comment]
added `autocomplete="off" autofill="off"` but no guarantee it will work

**Comment by JoshWho** [comment]
I think this is fixed. I do not see a suggested password anymore. The user that complained to me hasn't responded I think it is fixed and will close this.
