### ISSUE TITLE
FTP Storage plugins

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#6387]
Hi Daniel,

I'm interested to purchase the FTP Storage plugins.
But I have a few question below.

1) Is it working with AVideo v9.7 ?
2) Do you have the User guide for this plugin ?
I would like to know how to use it.

Thanks
Pond

**Comment by DanielnetoDotCom** [comment]
> Is it working with AVideo v9.7 ?

I strongly recommend you to update, do not use it on 9.7
If you will update make sure you follow this https://github.com/WWBN/AVideo/issues/5075#issuecomment-833764155

> Do you have the User guide for this plugin ?

https://github.com/WWBN/AVideo/wiki/FTP_Storage-Plugin

**Comment by guitarpound** [comment]
Thanks
