### ISSUE TITLE
100% CPU loading

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#6392]
Hi Danial,

I found my server 100% CPU loading.
I use "top" command to check the running process and found "dhcpd" running by "root" user.
Then I checked crontab and found one command line below that I never add it.

38 * * * * /bin/dhcpd -o sg.minexmr.com:4444 -B >/dev/null

I have been remove it before.
But after around 1-2 month it always come back.

So, Could you please kindly advise how can it remove it permanently.

Thanks
Pond

**Comment by jengajenga** [comment]
Check the socket. It could be the cause. I once had the socket take 99% of my resources. A restart of the socket usually made it go back to normal.

**Comment by JoshWho** [comment]
Unless your server is running as a router I do not see a purpose to have that enabled. Should be a Static IP Network to begin with.
