### ISSUE TITLE
We could not verify your server from outside 

### ISSUE THREAD

**Issue by Rolandhun74** [WWBN/AVideo#6393]
Hello

Why am I getting this error message?
<img width="1680" alt="Képernyőfotó 2022-03-16 - 9 13 30" src="https://user-images.githubusercontent.com/83669701/158545965-0587d19d-a3a8-4fe4-8714-5c854bd8a104.png">

**Comment by Rolandhun74** [comment]
THX

**Comment by partystreamsk** [comment]
same error on my site. but i dont care

**Comment by sinaisinai** [comment]
Hi
I get the same error and i can not see any plugins
Can you help please ?
I´m newer, I don´t know how it works
![Capture d’écran 2022-03-24 à 16 22 21](https://user-images.githubusercontent.com/43705498/159952213-9d8cd2b3-fbf9-4f2f-811f-d22da2b9cabd.png)

**Comment by DanielnetoDotCom** [comment]
From your image I can see you have only 2.7 GB free, it can cause you a lot of problems, including database crash and connection lost.

I recommend you to free some space ASAP, keep at least 50 GB free, if you will upload something,
