### ISSUE TITLE
When I try to run Programs Live I receive a Static Call error.

### ISSUE THREAD

**Issue by OptimistPrimal** [WWBN/AVideo#6394]
**Describe the bug**
I open up a PROGRAM for EDIT and select the "GoLive" option.  It says it goes live.  (Show on TV switch is ON).
It does NOT go live AND it disables the site.  Still comes up, but is inoperative, no content shows, etc.  I also receive the following error:

`[int(1) ["message"]=> string(385) "**Uncaught Error: Non-static method PlayLists::getLivePosterImage() cannot be called statically** in /.../plugin/PlayLists/PlayLists.php:443 Stack trace: #0 /.../plugin/PlayLists/tv_body.php(37): PlayLists::getLiveImage() #1 /.../plugin/PlayLists/tv.php(152): include('...') #2 {main} thrown" ["file"]=> string(67) "/.../plugin/PlayLists/PlayLists.php" ["line"]=> int(443) }](https://bannedtogether.tube/live/0/GlobalNetworkNews?playlists_id_live=12359&embed=1)`

**To Reproduce**
1. Go to 'Organize Programs'
2. Click on 'EDIT icon'
3. Click on the "GO LIVE" option
4. Click "PLAY ALL"

**Expected behavior**
Expected the LiveStream to start with that Program List.

**Error Logs**
NGINX LOG
`2022/03/16 16:30:00 [error] 3946#0: *1366 open() "/HLS/live/HIDDEN.m3u8" failed (2: No such file or directory), client: 73.37.51.74, server: bannedtogether.tube, request: "GET /live/HIDDEN.m3u8 HTTP/1.1", host: "bannedtogether.tube:8443", referrer: "https://bannedtogether.tube/"
2022/03/16 16:30:10 [error] 3946#0: *1366 open() "/HLS/live/HIDDEN.m3u8" failed (2: No such file or directory), client: 73.37.51.74, server: bannedtogether.tube, request: "GET /live/HIDDEN.m3u8 HTTP/1.1", host: "bannedtogether.tube:8443", referrer: "https://bannedtogether.tube/"
2022/03/16 16:33:38 [crit] 3946#0: *1378 SSL_do_handshake() failed (SSL: error:14201044:SSL routines:tls_choose_sigalg:internal error) while SSL handshaking, client: 172.104.25.243, server: 0.0.0.0:8443
2022/03/16 16:36:07 [error] 3946#0: *1385 open() "/HLS/live/HIDDEN.m3u8" failed (2: No such file or directory), client: 73.37.51.74, server: bannedtogether.tube, request: "GET /live/HIDDEN.m3u8 HTTP/1.1", host: "bannedtogether.tube:8443", referrer: "https://bannedtogether.tube/"
2022/03/16 16:36:15 [error] 3946#0: *1385 open() "/HLS/live/HIDDEN.m3u8" failed (2: No such file or directory), client: 73.37.51.74, server: bannedtogether.tube, request: "GET /live/HIDDEN.m3u8 HTTP/1.1", host: "bannedtogether.tube:8443", referrer: "https://bannedtogether.tube/"
2022/03/16 16:44:19 [error] 3946#0: *1393 open() "/HLS/live/HIDDEN.m3u8" failed (2: No such file or directory), client: 127.0.0.1, server: bannedtogether.tube, request: "GET /live/HIDDEN.m3u8 HTTP/1.1", host: "bannedtogether.tube:8443"
2022/03/16 16:44:19 [error] 3946#0: *1394 open() "/HLS/live/HIDDEN.m3u8" failed (2: No such file or directory), client: 127.0.0.1, server: bannedtogether.tube, request: "GET /live/HIDDEN.m3u8 HTTP/1.1", host: "bannedtogether.tube:8443"
2022/03/16 16:44:19 [error] 3946#0: *1395 open() "/HLS/live/HIDEN.m3u8" failed (2: No such file or directory), client: 127.0.0.1, server: bannedtogether.tube, request: "GET /live/HIDDEN.m3u8 HTTP/1.1", host: "bannedtogether.tube:8443"
2022/03/16 16:44:19 [error] 3946#0: *1396 open() "/HLS/live/HIDDEN.m3u8" failed (2: No such file or directory), client: 127.0.0.1, server: bannedtogether.tube, request: "GET /live/HIDDEN.m3u8 HTTP/1.1", host: "bannedtogether.tube:8443"`

APACHE2 ERROR LOG
`[Wed Mar 16 16:30:55.421893 2022] [proxy_fcgi:error] [pid 3557:tid 140297380030016] [client 127.0.0.1:33886] AH01071: Got error 'PHP message: AVideo includeconfig ignoredPHP message: Restreamer.json.php start http://bannedtogether.tube/PHP message: Restreamer.json.php php://input {"m3u8":"https:\\/\\/bannedtogether.tube:8443\\/live\\/HIDDEN.m3u8","restreamerURL":"http:\\/\\/bannedtogether.tube\\/plugin\\/Live\\/standAloneFiles\\/restreamer.json.php","restreamsDestinations":["rtmp:\\/\\/a.rtmp.youtube.com\\/live2\\/HIDDEN"],"token":"HIDDEN","users_id":1}PHP message: Restreamer.json.php Found 1 destinations: ["rtmp:\\/\\/a.rtmp.youtube.com\\/live2\\/HIDDEN"]PHP message: Restreamer.json.php verifying token http://bannedtogether.tube/plugin/Live/verifyToken.json.php?token=HIDDEN=PHP message: PHP Warning:  file_get_contents(http://bannedtogether.tube/plugin/Live/verifyToken.json.php?token=HIDDEN=): Failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error\r\n in /home/bannedadmin/public_html/AVideo/plugin/Live/standAloneFiles/restreamer.json.php on line 112PHP message: Restreamer.json.php verification respond content PHP message: Restreamer.json.php empty json ERROR Could not verify token (http://bannedtogether.tube/plugin/Live/verifyToken.json.php?token=HIDDEN=) '`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: UBUNTU 21
 - Browser chrome, dissenter, safari, google app
 - Version Latest

**Comment by OptimistPrimal** [comment]
All of the pages (stats, on_play, etc) work, but not the on_publish - going live works, but viewing the livestream generates the Static Call error on the "TV" screen.

**Comment by DanielnetoDotCom** [comment]
Please try this update
