### ISSUE TITLE
2 tip buttons at the top of chat how to make it 1?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6395]
![97220d74-3fc1-4ab2-9d6f-4a865a110442](https://user-images.githubusercontent.com/39392449/158700664-04652835-42ff-4118-9afe-502dad88a56f.png)

**Comment by partystreamsk** [comment]
One is for donation links and second for direct wallet transfer. 
1. To disable donation link button,  go to CustomizeUser > uncheck "allowDonationLink" and you will have only donation button for direct wallet transfer.
![donation link](https://user-images.githubusercontent.com/50631455/158827934-ac113a11-8300-43af-8d32-12523dc2cc3b.png)

**Comment by JoshWho** [comment]
I do not use direct wallet transfer. I only use the external tip. I have Direct Wallet turned off

**Comment by DanielnetoDotCom** [comment]
Can you please confirm if one of those buttons is the wallet donation button?

can you please share a link with it?

**Comment by JoshWho** [comment]
They both go to the external Donation link

**Comment by DanielnetoDotCom** [comment]
can you please send me a link to that chat so I can inspect and try to find the issue?

**Comment by JoshWho** [comment]
Just seen this sorry took so long. It is all lives that has a donation link enabled https://www.joshwhotv.com/live/1/DreagusProd
