### ISSUE TITLE
VAST Ad Server and Google IMA both do not work

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6400]
I am starting to work with these kind of VAST ads systems and wanted to do a test and I can't get it to work on either system. 

The Ad_Server  plugin VMPAP here https://www.joshwhotv.com/plugin/AD_Server/VMAP.php

I can't get the IMA Google one to work with that either. 

I should be able to put https://www.joshwhotv.com/plugin/AD_Server/VAST.php?campaign_has_videos_id=86&vmap_id=623504db6709d&key=0

in one of the ad tags but nothing shows when I try it.

**Comment by JoshWho** [comment]
I am not sure if I am doing it right but just the regular VAST by itself use to work and now I do not see the markers or skip button load anymore.

**Comment by DanielnetoDotCom** [comment]
I am sending updates now for the ad_server

**Comment by DanielnetoDotCom** [comment]
please make a git pull and confirm

**Comment by JoshWho** [comment]
I confirm it is working great now. Thank you @DanielnetoDotCom
