### ISSUE TITLE
/* AD_Server canNOTLoadAds */

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6401]
bug can be seen on a live stream at the bottom 
Link tested was this https://www.joshwhotv.com/live/1/HardNewsNetwork/1

![download (5)](https://user-images.githubusercontent.com/39392449/159098812-4bf5c376-20c5-41c8-aad3-03c194bf47f2.png)

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that, please try this update

**Comment by JoshWho** [comment]
Fixed
