### ISSUE TITLE
I keep seeing weird errors like this Incorrect integer value

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6402]
`[18-Mar-2022 19:25:06 America/Chicago] AVideoLog::ERROR: Error in writeSql : (1366) Incorrect integer value: '' for column 'users_id_companny' at row 1, SQL-CMD:UPDATE live_transmitions_history SET  `id` = 50545 ,  `title` = '&zwnj;MSM is Lying to Us about Ukraine; NYT Admits Hunter Laptop is Real 3/18/2022' ,  `description` = 'The main stream media, big tech, and of course, our very own government, are in a full court press to allow one (and only one) narrative to come out of the Ukrainian-Russian conflict. Seasoned war correspondent Lara Logan recently pointed this out in a pointed interview. Tulsi Gabbard has been called a traitor to her country for pointing out that the United States is funding bio-labs in Ukraine.`

**Comment by DanielnetoDotCom** [comment]
Duplicated https://github.com/WWBN/AVideo/issues/6403
