### ISSUE TITLE
Correct Email address in install confix typo

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#6405]
I need to correct my email address. Made typo. From [contact@lblivstream.com](mailto:contact@lblivstream.com) to [contact@lblivestream.com](mailto:contact@lblivestream.com) 

Message could not be sent (The following From address failed: contact@lblivstream.com : MAIL FROM command failed,Requested action not taken: mailbox unavailable
invalid DNS MX or A/AAAA resource record
,550,SMTP server error: MAIL FROM command failed Detail: Requested action not taken: mailbox unavailable
invalid DNS MX or A/AAAA resource record
SMTP code: 550SMTP server error: MAIL FROM command failed Detail: Requested action not taken: mailbox unavailable
invalid DNS MX or A/AAAA resource record
SMTP code: 550)

**Comment by DanielnetoDotCom** [comment]
where is this email address?

a user or site configuration?

why cant you change it?

**Comment by Lordblanca** [comment]
![image](https://user-images.githubusercontent.com/37937968/159332042-8fbe9be1-5ee7-4adc-bc95-c7b6f1c26dcb.png)

**Comment by DanielnetoDotCom** [comment]
Do not save it from the admin panel, save it from Site configuration menu

![image](https://user-images.githubusercontent.com/18009293/159332894-7faea9a3-47c3-4c83-b6b8-0a6a5c876563.png)

**Comment by Lordblanca** [comment]
Made change as you requested. Still the same problem when testing email. 
![image](https://user-images.githubusercontent.com/37937968/159334107-94749d55-ce7b-4faa-af78-c4f306b52f87.png)

**Comment by DanielnetoDotCom** [comment]
If you saved, clear the cache and still the same error. the problem is in your Server or Domain/DNS

**Comment by Lordblanca** [comment]
The problem is a typo when I was on the config page. When entering the contact information. I entered the wrong email address as it said. If you click on the image it says contact@lbilvstrea.com and it is supposed to say contact@lblivestream.com. The "e" is missing in the domain name. is there a way to fix or I have to get back to the configuration screen.

**Comment by Lordblanca** [comment]
I did that multiple times and restarted the server still the same thing. I tried getting back to the install page but all i get is " Your system is installed, remove the /var/www/html/AVideo/install directory to continue" how can I get back to the configuration paget and make the change from there
