### ISSUE TITLE
Couple of issues on Chat 2 plugin

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6406]
It seems there are duplicate entries in the menu as well as two donation buttons appearing at the top where should only show one. Here is a screen shot of my chat menu.
![Screen Shot 5782-07-16 at 19 04 44](https://user-images.githubusercontent.com/58882903/159131045-333bf70e-cb17-48de-a04e-a8a6ecf589f3.jpg)

It seems like "Bubbles Only" and "Chat" appear twice but maybe this is how it should be idk, but how do I remove at least one of the donation buttons?

Also I would like to see this menu as RTL as well, all text floating to right and symbols are on right side of text.

**Comment by partystreamsk** [comment]
One button is for direct wallet donations, second one is for custom link donation. Go to CustomiseUser plugin and try to deactivate one of them.
