### ISSUE TITLE
Live video is not playing from the remote server.

### ISSUE THREAD

**Issue by Proton-people** [WWBN/AVideo#6407]
Hello. I have a problem. Live video is not playing. I have 2 servers. On one streamer with the playmy.org domain and on the other Nginx with the stream.playmy.org domain. Can you suggest what could be the problem? Thanks.
![bandicam 2022-03-19 23-36-11-702](https://user-images.githubusercontent.com/48072457/159168861-3522fc27-10af-40cb-9b20-e4522e0ca76e.jpg)
![bandicam 2022-03-20 18-00-29-771](https://user-images.githubusercontent.com/48072457/159168863-2124fc58-b898-473e-a3fa-b1394cd57ce2.jpg)
![bandicam 2022-03-20 18-02-03-046](https://user-images.githubusercontent.com/48072457/159168865-5b9c5268-bc4c-480c-bb12-8222940914c1.jpg)
![bandicam 2022-03-20 18-04-23-938](https://user-images.githubusercontent.com/48072457/159168871-6eb343ca-0dc1-4dce-9d8a-8d56e765a4be.jpg)
![bandicam 2022-03-20 18-05-19-547](https://user-images.githubusercontent.com/48072457/159168875-8ae1e34e-54c4-46a6-b43f-f93d306a8eb6.jpg)
![bandicam 2022-03-20 18-05-31-790](https://user-images.githubusercontent.com/48072457/159168877-d4670dfd-c8f8-4db5-87a1-931bdc8f147a.jpg)

**Comment by Proton-people** [comment]
![bandicam 2022-03-20 00-16-26-867](https://user-images.githubusercontent.com/48072457/159138622-8acb722a-020c-4695-932e-a334f536e206.jpg)

**Comment by partystreamsk** [comment]
English please

**Comment by Proton-people** [comment]
> пожалуйста, по английски

Ok.

**Comment by DanielnetoDotCom** [comment]
stream.playmy.org seems to not be a valid domain, probably your server cannot resolve it.

check your nginx error log file

**Comment by OptimistPrimal** [comment]
Having a similar problem.  Stat shows the streams go live, the recorder records and the encoder drops the processed file, but the index for the Streamer Server will not load after I try to view the livestream.  Checking an embed on another computer - doesn't play.  Shows the player can't find the error.

**Comment by Proton-people** [comment]
> stream.playmy.org не является действительным доменом, возможно, ваш сервер не может его разрешить.
> 
> проверьте файл журнала ошибок nginx
Hello Daniel. Here is the magazine. I don't understand what the problem is. Previously, everything worked in this configuration. Give advice please. Thanks.
![Uploading bandicam 2022-03-22 14-28-55-950.jpg…]()

**Comment by DanielnetoDotCom** [comment]
@Proton-people I can see something regarding your SSL

![image](https://user-images.githubusercontent.com/18009293/159505156-38937687-6400-4e15-952a-f3d71b4079b6.png)

**Comment by DanielnetoDotCom** [comment]
> 

Seems also to be a SSL problem

**Comment by Proton-people** [comment]
> @OptimistPrimal
> 
> Похоже, проблема с SSL

Hello. I reinstalled Linux and installed everything on one Apache + Nginx server. The broadcast is now playing. Terer I have a similar problem with the Webcam application (broadcast from Webcam does not play).
![bandicam 2022-03-23 13-30-14-092](https://user-images.githubusercontent.com/48072457/159680638-8b017aec-a549-4b63-b048-29abe01c6878.jpg)
![bandicam 2022-03-23 13-29-09-535](https://user-images.githubusercontent.com/48072457/159680696-25907935-09f4-4b0e-aa60-7990060d54c6.jpg)
![bandicam 2022-03-23 13-31-39-404](https://user-images.githubusercontent.com/48072457/159680725-62042f7e-1893-4c2e-95fa-e5f7181ebf13.jpg)
Can you make recommendations?

**Comment by DanielnetoDotCom** [comment]
First, try to livestream with OBS and make sure it is working

https://github.com/WWBN/AVideo/wiki/How-to-make-a-live-stream#from-pc

the live with the WebRTC webcam is still under development and may only work if you are using the adaptive mode

**Comment by Proton-people** [comment]
> Во-первых, попробуйте провести прямую трансляцию с помощью OBS и убедитесь, что она работает.
> 
> [https://github.com/WWBN/AVideo/wiki/Как сделать-а-живой-поток#из-ПК](https://github.com/WWBN/AVideo/wiki/How-to-make-a-live-stream#from-pc)
> 
> прямая трансляция с веб-камерой WebRTC все еще находится в разработке и может работать только в том случае, если вы используете адаптивный режим.
> 
> https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream

Everything works great with OBS. I will try adaptive mode. Webcam is a great solution. I will try to set up a remote server and change the certificates to Let's Encrypt. Thank you Daniel for your hard work. I'll post the results here in a couple of days.
