### ISSUE TITLE
Possibility to Sign up with a non-latin name.

### ISSUE THREAD

**Issue by cymesa** [WWBN/AVideo#6409]
Hello:
I'm testing AVideo Platform v11.7 and when try to register with a non-latin name, for example: Пепе Тесто
always returns the error:  "Name is required"

My solution:
Change the match regular expression in the file /view/signUp.php on the line 254 for something like this:

    if (!$(this).val().match(/[0-9a-z]+/i)) {

***  changed by

   if (!$(this).val().match(/[a-za-åa-ö-w-я0-9]+/i)) {

I'm not a high level programmer, but that worked!
Thanks you very much for your excellent work, God bless you forever!
Sincerely,
Carlos

**Comment by DanielnetoDotCom** [comment]
Hi, do you mean Latin chars on the name or username?

I guess username will not be a good idea to allow Latin chars, but I do not see a problem with the Name having special chars.

can you please confirm where are you referring it to?

**Comment by cymesa** [comment]
Sorry for my delay, the problem is in the "Name" field, for example, when you put a name in Cyrillic:
![image](https://user-images.githubusercontent.com/102000150/159657876-99ba9542-14d9-4f88-acba-2f1f4b67569c.png)
thank you very much, God bless you for your excellent work!

**Comment by cymesa** [comment]
Hi, Work perfect!
Thanks very much! God is with you!
Carlos

**Comment by DanielnetoDotCom** [comment]
> 

Amém
