### ISSUE TITLE
Wanting to Delete all _HD encoded files

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6411]
We have recently changed our policy to only allow SD i.e 720p encoding and remove all 1080 however since we already have many videos encoded as 1080p we are trying to find a way to easily reencode or remove all the HD files and leave the SD and LOW. IS there an easy way to go about this?

I think this will also solve the problem with the programs streaming stopping after the first video, maybe.

**Comment by DanielnetoDotCom** [comment]
Hi, 

it is possible with some script.  (shell script or PHP), I do not think I have anything ready for this.

I am not sure if you can do it with the Linux command line.

**Comment by DanielnetoDotCom** [comment]
Duplicated https://github.com/WWBN/AVideo/issues/6379#issuecomment-1074304283

> Hi,
> 
> it is possible with some script. (shell script or PHP), I do not think I have anything ready for this.
> 
> I am not sure if you can do it with the Linux command line.

**Comment by guymass** [comment]
OK thanks, we are using the video switch. We are importing the video to the encoder and creating a new post where the video is encoded with 720 and after we make the switch, clear cache and refresh we than delete the old file. It is more time consuming but we find it to be the best way to replace all those large videos and re encode them with 720p.
