### ISSUE TITLE
Advance in Editor will jump to My Videos

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6412]
When opening a video to edit its details and then clicking the Advance button it will take me to My Videos.

![Screen Shot 5782-07-18 at 20 48 18](https://user-images.githubusercontent.com/58882903/159348962-f4fba4e1-6b9c-4bd6-a05b-3fd54436d8d4.jpg)

It will jump to this page:

![Screen Shot 5782-07-18 at 21 23 55](https://user-images.githubusercontent.com/58882903/159348996-d939e298-3cba-4e7f-88e4-2b425fa5de20.jpg)

**Comment by DanielnetoDotCom** [comment]
I just sent an update, can you please check?

**Comment by guymass** [comment]
Still having this issue, jumping to My Videos.

**Comment by TLCReuver** [comment]
Can confirm too ==> Jumping to 'My videos'

**Comment by DanielnetoDotCom** [comment]
It supposes to jump to my videos, but also supposed to open a window to edit the video.

but I can see it is not listing the video. maybe a JS error, I will update the demo and check it later

**Comment by guymass** [comment]
Still issue with editor -> Advance mode not opening when its jumping to the videos page.
