### ISSUE TITLE
Stream + hls encoder enhancement

### ISSUE THREAD

**Issue by partystreamsk** [WWBN/AVideo#6413]
Hi Daniel! I have a smart ideas for live streaming. 

*FIRST IDEA*
Behavior now : 
1. You shedule livestream
2. you share link to friends and facebook
3. you do a livestream
4. you finish livestream
5. if somebody click on link that you shared, he see the protected livestream 
![private](https://user-images.githubusercontent.com/50631455/159348156-51050256-6c43-440f-ba17-7feeabd7926b.png)

Expected behavior: 
4. you finish the live stream
5. If somebody click on link you shared before, user will see a recorded video from livestream
6. if there is no video recorded , than redirect to homepage or channel of user

*SECOND IDEA*

Add extra 1080p MP4 encode pass to HLS , so encoder will encode HLS + MP4 to enable download file.
Will be great to add this to SendRecordedToEncoder, because lot of times i wanna download recording and modify/trim it but with HLS im not able to do it.

Thank you

**Comment by DanielnetoDotCom** [comment]
Those are good ideas and may be added in the future

**Comment by partystreamsk** [comment]
Great, thanks :)
