### ISSUE TITLE
Creating menus for mobiles doesn't work

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6414]
Trying to create menus for mobile and they will not work. All 4 items for mobile don't work or we don't know how to make them work.

![Screen Shot 5782-07-18 at 21 32 50](https://user-images.githubusercontent.com/58882903/159350105-77bcaeee-21a2-49d1-aec0-6e3e78c0bb03.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi

the moble means the mobile app, not the web mobile.

**Comment by guymass** [comment]
OK thanks.
