### ISSUE TITLE
trying to get livestream to work

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#6415]
I have all the everything in order. But I'm getting "Warning: file_get_contents(https://lblivestream.com:8443/stat): Failed to open stream: Connection refused in /var/www/html/AVideo/plugin/Live/test.php on line 54"
Here are screen shots of what is happening.
And below that is a copy of my ngxin config file:
![livestream-1](https://user-images.githubusercontent.com/37937968/159356265-fa206ee6-9841-4226-a922-ae19a3c77598.png)
![livestream-2](https://user-images.githubusercontent.com/37937968/159356275-34ef7e31-ce34-4458-9128-77c3bdf824bb.png)

Nginx config file
user    www-data;    
worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    buflen 1000ms;
                    chunk_size 4096;
                    ping_timeout 30s;
                    ### Use case option (max_streams; default is 32 )
                    #max_streams 10;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            hls_playlist_length 60m;
                            hls_fragment 4s;
                            drop_idle_publisher 30s;
                            sync 500ms;
                            #Experimental. Force dropped stream, or ended stream from being watched. (idle_streams)
                            #idle_streams off;
                            on_publish http://www.my domain is here.com/plugin/Live/on_publish.php;
                            on_publish_done http://www.my domain is here.com/plugin/Live/on_publish_done.php;
                            on_play http://www.my domain is here.com/plugin/Live/on_play.php;
                            #on_record_done http://www.my domain is here.com/plugin/Live/on_record_done.php;

                            #exec ffmpeg -re -i rtmp://localhost/live/$name 
                            #    -c:v libx264 -vf scale=-2:240 -r 20 -g 40 -keyint_min 40 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1400k -c:a aac -strict -2 -b:a 96k -f hls -hls_time 2 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_low  
                            #    -c:v libx264 -vf scale=-2:480 -r 30 -g 60 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 4200k -c:a aac -strict -2 -b:a 128k  -f hls -hls_time 2 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_mid  
                            #    -c:v libx264 -vf scale=-2:720 -r 30 -g 60 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 3000k -bufsize 6000k -c:a aac -strict -2 -b:a 128k  -f hls -hls_time 2 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi;

                            #recorder video {
                            #    record all manual;
                            #    record_path /var/www/tmp;
                            #    record_notify on;
                            #    record_max_size 2048M; 
                            #    record_suffix -%d-%b-%y-%T.flv;
                            ###If live-stream is over 30FPS and you want to limit it to 30FPS recording to light the encoding task #record_max_frames 30;
                            #    ## record_max_frames 30;
                            #}
                    
                            ### Record Audio Separately ( For podcast )
                            #recorder audio {
                            #    record audio;
                            #    record_path /var/www/tmp;
                            #    record_max_size 1024M;
                            #    record_suffix -%d-%b-%y-%T.mp3;
                            #}
                    }

                    #application adaptive {
                    #    live on; 
                    #    hls on; 

                    #    hls_path /HLS/live;
                    #    hls_nested on;
                    #    hls_playlist_length 10m;
                    #    allow play all;
                    #    allow publish 127.0.0.1;
                    #    deny publish all;

                    #    hls_variant _low BANDWIDTH=900000;
                    #    hls_variant _mid BANDWIDTH=2400000;
                    #    hls_variant _hi  BANDWIDTH=3500000;
                    #}
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    listen 8443 ssl;
                    listen [::]:8443 ssl;
                    #include /usr/local/nginx/snippets/self-signed.conf;
                    #include /usr/local/nginx/snippets/ssl-params.conf;
                    listen 8080;
		    listen 444 ssl;
                    server_name my domain is here www.my domain is here.com;
					ssl_certificate /etc/letsencrypt/live/my domain is here.com/fullchain.pem;
					ssl_certificate_key /etc/letsencrypt/live/my domain is here.com/privkey.pem;
					#ssl_certificate_chain_path/etc/letsencrypt/live/my domain is here.com/chain.pem:
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my ip address is here/live/my-stream-key/index.m3u8"      
                    location /live {
                            expires 60;
                            add_header 'Cache-Control' 'public';

                            location ~ \.m3u8$ {
                                expires -1;
                                # Disable cache
                                add_header 'Cache-Control' 'no-cache';

                                # CORS setup
                                add_header 'Access-Control-Allow-Origin' '*' always;
                                add_header 'Access-Control-Expose-Headers' 'Content-Length';
                            }

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my ip address is here/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            # replace this with the IP of your AVideo site
                            allow my ip address is here;
                            deny all;
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my ip address is here/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   

                    #location ~ \.php$ {
                    #       include /etc/nginx/snippets/fastcgi-php.conf;
                    #       fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
                    #}

            }
    }

**Comment by DanielnetoDotCom** [comment]
did you start your Nginx?

`sudo /usr/local/nginx/sbin/nginx`

**Comment by Lordblanca** [comment]
I copied the Server URL: and the Stream name/key: to obs. but no connection

**Comment by DanielnetoDotCom** [comment]
First, make sure your Nginx is running

https://lblivestream.com:8443/stat

**Comment by Lordblanca** [comment]
The connection has timed out

An error occurred during a connection to lblivestream.com:8443.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by DanielnetoDotCom** [comment]
> did you start your Nginx?
> 
> `sudo /usr/local/nginx/sbin/nginx`

?????

**Comment by Lordblanca** [comment]
Yes I Did restared the server and nginx
![image](https://user-images.githubusercontent.com/37937968/159568185-a279baed-18e1-405b-bf3c-4e2fcd4a0f41.png)

Copied and past the server Url and stream key to OBS and still
![image](https://user-images.githubusercontent.com/37937968/159569216-00f96930-4859-4071-a753-95c268bc4c10.png)

**Comment by DanielnetoDotCom** [comment]
please paste here the Nginx start output command

**Comment by Lordblanca** [comment]
![image](https://user-images.githubusercontent.com/37937968/159597766-0b96407c-0084-45b2-bef6-57ba013d447a.png)

**Comment by Lordblanca** [comment]
root@lblivestream:~# sudo /usr/local/nginx/sbin/nginx
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8443 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:8443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8443 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:8443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8443 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:8443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8443 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:8443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8443 failed (98: Address already in use)
nginx: [emerg] bind() to [::]:8443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] still could not bind()
root@lblivestream:~#

**Comment by Lordblanca** [comment]
![image](https://user-images.githubusercontent.com/37937968/159598075-000a9bfa-4563-4d7d-a7b4-aeef5452abf1.png)

**Comment by Lordblanca** [comment]
Using username "root".
Keyboard-interactive authentication prompts from server:
End of keyboard-interactive prompts from server
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-105-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Wed Mar 23 00:14:54 2022 from 100.2.152.93
root@lblivestream:~# sudo nano /usr/local/nginx/conf/nginx.conf
root@lblivestream:~# /usr/local/nginx/sbin/nginx -t
nginx: the configuration file /usr/local/nginx/conf/nginx.conf syntax is ok
nginx: configuration file /usr/local/nginx/conf/nginx.conf test is successful
root@lblivestream:~#

**Comment by DanielnetoDotCom** [comment]
Hi

let's do this, before you start Nginx, try to stop it

`sudo /usr/local/nginx/sbin/nginx -s stop`

then you start it

`sudo /usr/local/nginx/sbin/nginx`

please paste the output from both commands here

**Comment by DanielnetoDotCom** [comment]
The nginx start up seems to be fine, I can only imagine you have a firewall blocking you.

For example, if I try a telnet from here, I get an error

`telnet lblivestream.com 1935`

if nginx is running, the port 1935 MUST be opened

**Comment by Lordblanca** [comment]
Using username "root".
Keyboard-interactive authentication prompts from server:
End of keyboard-interactive prompts from server
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-105-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Thu Mar 24 18:19:13 2022 from 100.2.152.93
root@lblivestream:~# sudo ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), disabled (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
2053/tcp                   ALLOW IN    Anywhere
22/tcp                     ALLOW IN    Anywhere
1935                       ALLOW IN    Anywhere
8080                       ALLOW IN    Anywhere
80                         ALLOW IN    Anywhere
443                        ALLOW IN    Anywhere
8888                       ALLOW IN    Anywhere
444                        ALLOW IN    Anywhere
8443                       ALLOW IN    Anywhere
465                        ALLOW IN    Anywhere
8444                       ALLOW IN    Anywhere
1936                       ALLOW IN    Anywhere
80/tcp                     ALLOW IN    Anywhere
443/tcp                    ALLOW IN    Anywhere
2053                       ALLOW IN    Anywhere
2053/tcp (v6)              ALLOW IN    Anywhere (v6)
22/tcp (v6)                ALLOW IN    Anywhere (v6)
1935 (v6)                  ALLOW IN    Anywhere (v6)
8080 (v6)                  ALLOW IN    Anywhere (v6)
80 (v6)                    ALLOW IN    Anywhere (v6)
443 (v6)                   ALLOW IN    Anywhere (v6)
8888 (v6)                  ALLOW IN    Anywhere (v6)
444 (v6)                   ALLOW IN    Anywhere (v6)
8443 (v6)                  ALLOW IN    Anywhere (v6)
465 (v6)                   ALLOW IN    Anywhere (v6)
8444 (v6)                  ALLOW IN    Anywhere (v6)
1936 (v6)                  ALLOW IN    Anywhere (v6)
80/tcp (v6)                ALLOW IN    Anywhere (v6)
443/tcp (v6)               ALLOW IN    Anywhere (v6)
2053 (v6)                  ALLOW IN    Anywhere (v6)

root@lblivestream:~#  ufw status
Status: active

To                         Action      From
--                         ------      ----
2053/tcp                   ALLOW       Anywhere
22/tcp                     ALLOW       Anywhere
1935                       ALLOW       Anywhere
8080                       ALLOW       Anywhere
80                         ALLOW       Anywhere
443                        ALLOW       Anywhere
8888                       ALLOW       Anywhere
444                        ALLOW       Anywhere
8443                       ALLOW       Anywhere
465                        ALLOW       Anywhere
8444                       ALLOW       Anywhere
1936                       ALLOW       Anywhere
80/tcp                     ALLOW       Anywhere
443/tcp                    ALLOW       Anywhere
2053                       ALLOW       Anywhere
2053/tcp (v6)              ALLOW       Anywhere (v6)
22/tcp (v6)                ALLOW       Anywhere (v6)
1935 (v6)                  ALLOW       Anywhere (v6)
8080 (v6)                  ALLOW       Anywhere (v6)
80 (v6)                    ALLOW       Anywhere (v6)
443 (v6)                   ALLOW       Anywhere (v6)
8888 (v6)                  ALLOW       Anywhere (v6)
444 (v6)                   ALLOW       Anywhere (v6)
8443 (v6)                  ALLOW       Anywhere (v6)
465 (v6)                   ALLOW       Anywhere (v6)
8444 (v6)                  ALLOW       Anywhere (v6)
1936 (v6)                  ALLOW       Anywhere (v6)
80/tcp (v6)                ALLOW       Anywhere (v6)
443/tcp (v6)               ALLOW       Anywhere (v6)
2053 (v6)                  ALLOW       Anywhere (v6)

root@lblivestream:~#

**Comment by Lordblanca** [comment]
Using username "root".
Keyboard-interactive authentication prompts from server:
End of keyboard-interactive prompts from server
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-105-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Thu Mar 24 23:28:49 2022 from 100.2.152.93
root@lblivestream:~# sudo ufw allow 1935
Skipping adding existing rule
Skipping adding existing rule (v6)
root@lblivestream:~#

**Comment by DanielnetoDotCom** [comment]
The RTMP port is 1935 NOT 1936

`1936 (v6) ALLOW IN Anywhere (v6)`

if the error persists, stop your firewall and try again

**Comment by Lordblanca** [comment]
I figured it out. Nginx is not staying on.
Using username "root".
Keyboard-interactive authentication prompts from server:
End of keyboard-interactive prompts from server
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-105-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Fri Mar 25 22:23:27 2022 from 100.2.152.93
root@lblivestream:~# sudo netstat -tulpn | grep LISTEN
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN                                                                                          855/nginx: master p
tcp        0      0 0.0.0.0:444             0.0.0.0:*               LISTEN                                                                                          855/nginx: master p
tcp        0      0 127.0.0.1:33060         0.0.0.0:*               LISTEN                                                                                          894/mysqld
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN                                                                                          894/mysqld
tcp        0      0 0.0.0.0:1935            0.0.0.0:*               LISTEN                                                                                          855/nginx: master p
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN                                                                                          855/nginx: master p
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN                                                                                          703/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN                                                                                          859/sshd: /usr/sbin
tcp6       0      0 :::443                  :::*                    LISTEN                                                                                          876/apache2
tcp6       0      0 :::8443                 :::*                    LISTEN                                                                                          855/nginx: master p
tcp6       0      0 :::80                   :::*                    LISTEN                                                                                          876/apache2
tcp6       0      0 :::22                   :::*                    LISTEN                                                                                          859/sshd: /usr/sbin
root@lblivestream:~# sudo netstat -tulpn | grep LISTEN
tcp        0      0 127.0.0.1:33060         0.0.0.0:*               LISTEN      894/mysqld
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      894/mysqld
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      703/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      859/sshd: /usr/sbin
tcp6       0      0 :::443                  :::*                    LISTEN      876/apache2
tcp6       0      0 :::80                   :::*                    LISTEN      876/apache2
tcp6       0      0 :::22                   :::*                    LISTEN      859/sshd: /usr/sbin
root@lblivestream:~#

**Comment by Lordblanca** [comment]
And 1935 is one of the ports that is open. 1936 has nothing to do with the RTMP

**Comment by Lordblanca** [comment]
I guess you gave up. It might be the install. I just do it again do you have a install for nginx. other than the one that you have on the menu... https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

**Comment by DanielnetoDotCom** [comment]
> And 1935 is one of the ports that is open. 1936 has nothing to do with the RTMP

From your firewall output 1935 is NOT open
