### ISSUE TITLE
YPTStorage with DigitalOcean BlockStorage

### ISSUE THREAD

**Issue by OptimistPrimal** [WWBN/AVideo#6416]
I've been trying for a couple of days to get a clear understanding of configuring the YPTStorage plugin.  Even more challenging seems to be understanding how to utilize DigitalOcean Block Storage.  I've watched the "training video" but it doesn't appear to work that way - AVideo-Storage errors out, actually can't tell if AVideo-Storage is required, or just recommended.   Having an actual step by step with a clear explanation of configuring YPTStorage would really help.  Does it run standalone...does it need the AVideo-Storage git to function...troubleshooting the AVideo-Storage install....help.

**Comment by DanielnetoDotCom** [comment]
Hi

what exactly are the errors. 

If you describe here where is the problem I may be able to detail a bit more what is missing.

**Comment by OptimistPrimal** [comment]
A)  Does yptStorage plugin require AVideo-Storage to be installed in order to operate?
B)  If not, then I don't see how to configure it with digitalocean block storage
C)  If so, then AVideo-Storage causes a NON-SPECIFIC Error - no logs, just says talk to your admin.

**Comment by DanielnetoDotCom** [comment]
> A) Does yptStorage plugin require AVideo-Storage to be installed in order to operate?

Yes

> B) If not, then I don't see how to configure it with digitalocean block storage

I do not know what is "digitalocean block storage"

> C) If so, then AVideo-Storage causes a NON-SPECIFIC Error - no logs, just says talk to your admin.

Must be something, check your apache error.log

also share something about the error. without any clue we cannot help you

**Comment by OptimistPrimal** [comment]
Digital Ocean block storage is like having an external hard drive you can plug into your server.  It get's mounted onto the same server that AVideo is installed on.  If the main drive is your "C:" drive, the block storage is your "D:" drive.

I followed the directions on the AVideo-Storage install.  Pulled it down into a new directory on the "C:" drive, set the config as directed.  Attempted to follow the directions where it showed the new storage listed to get the pop-up to fill in and the system says: "Non-Specific" error occurred, contact your administrator.  There is nothing in any of the logs to give a clue so not sure what to do differently.

**Comment by DanielnetoDotCom** [comment]
Maybe you do not need the YPTStorage 

try to move your AVideo/videos directory into your Digital Ocean block storage

than create a symbolic link replacing the videos directory in the original path 

apache should be able to resolve that 

just make sure the Digital Ocean block storage is fast enough to handle all the disks requests
