### ISSUE TITLE
VideoResolutionSwitcher plugin: Is the resolution setup automatic or manual?

### ISSUE THREAD

**Issue by sizious** [WWBN/AVideo#6417]
Hello,

We are using AVideo for almost 1 year now and everything is working great, thank you very much for all you are doing.

We are planning to buy the **VideoResolutionSwitcher** plugin, but before we just want to know if this resolution is automatically switched based on the connection quality or do the user need to manually select the resolution he or she wants?

Thank you for your answer,

BR
Mike

**Comment by DanielnetoDotCom** [comment]
Hi

this feature is only on the VideoHLS plugin 


https://github.com/WWBN/AVideo/wiki/VideoHLS-Plugin

**Comment by sizious** [comment]
Ola Daniel,
And thank you for your answer! We will consider this option.
BR
Mike
