### ISSUE TITLE
CANCEL MEMBERSHIP

### ISSUE THREAD

**Issue by naluv4u2** [WWBN/AVideo#6418]
How can I cancel paid memberships for my members?  I tried to make them inactive but the member complained that funds are still coming out of his bank account.

**Comment by DanielnetoDotCom** [comment]
what payment gateway are you using?

usually, you can cancel the payment on the payment gateway panel (PayPal or Stripe), or cancel the subscription on AVideo

make a user or a plan inactive does not cancel the subscription

**Comment by naluv4u2** [comment]
I am using Stripe.  Thank you
