### ISSUE TITLE
Meet pages RTL

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6422]
When opening Meet, the entire interface although translated with float to the left and we need it floating right. How can we do this?
![Screen Shot 5782-07-21 at 23 50 11](https://user-images.githubusercontent.com/58882903/160016473-01110987-35ee-437d-9470-32cc376f7238.jpg)
![Screen Shot 5782-07-21 at 23 50 25](https://user-images.githubusercontent.com/58882903/160016488-28bb77dd-7f37-4c52-a12f-3bb795340e07.jpg)

**Comment by DanielnetoDotCom** [comment]
Check this update please

**Comment by guymass** [comment]
Things are still floating left and for RTL readers the whole page is strange.

![Screen Shot 5782-07-22 at 18 45 11](https://user-images.githubusercontent.com/58882903/160154353-f603fc81-f894-4b0e-87c3-416bff9e1900.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, I need your help to understand how it should looks like.

**Comment by guymass** [comment]
This would appear better for RTL on all pages.
![Screen Shot 5782-07-22 at 23 50 30](https://user-images.githubusercontent.com/58882903/160199119-41e28e21-3cf9-438e-a898-c957a425d55d.jpg)

**Comment by DanielnetoDotCom** [comment]
For some reason RTL does not work on datatables column titles

Also I cannot translate it now, but it will translated in the future

**Comment by guymass** [comment]
OK thanks, I will close this issue for now.
