### ISSUE TITLE
Channel button is covert with icons.

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6423]
When showing a channel on the front page the following is showing:
![Screen Shot 5782-07-22 at 0 27 56](https://user-images.githubusercontent.com/58882903/160020734-82799bbf-4b41-4f03-b6d3-ba63c7185143.jpg)

The buttons and info on the top right are hovering over the channel button.

**Comment by DanielnetoDotCom** [comment]
Can you please share a link for your site front page here, so I can inspect?

**Comment by guymass** [comment]
https://alive528.com

**Comment by DanielnetoDotCom** [comment]
I see, I guess it is a RTL issue, I will need to review it
