### ISSUE TITLE
Sync LDAP with local Database

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6425]
or AUTOMATICALLY CREATE AN LDAP USER APON REGISTRATION (any, normal, google, facebook, etc...)

LDAP is a great feature which allows integrating other services while maintaining a single user credentials and login, however it also causes a lot of head ache because they are not in sync and users which registered regular through other means on the site e.g. Google Login or Basic Registration and Login are still required to create an LDAP user if they wish to login to the other services and those who only registered to LDAP are still required to registered a second user to login to the AVideo platform and that is because we do not allow the LDAP login on the AVideo site currently because it is confusing users seeing two login options on the same page.

I think this process should be single, seemless and run in the background, meaning, if LDAP option is enabled than automatically when registering with any method an LDAP user should be created as well and the Login process should take into account checking LDAP in the background, so in this way there will only be a single login fields for username and password.

If we can solve this issue and have LDAP synced with AVideo registration than LDAP can be of great use as a background process that is seemingly creating its users based on the normal registration that should still hold a copy in case people want to disable LDAP and only use the local database user base.

I think there should also be a sync button to check that both are in sync and contain the same user base so switching LDAP on or off will always allow them to be in sync for any new registration that happened while it was off.

We are willing to help if we have some more insight into the workings of the AVideo registration and user creation process.

**Comment by DanielnetoDotCom** [comment]
I do not think it is that easy.

each LDAP has a different configuration. the only way it to happen is a custom plugin for your LDAP enviroment.

**Comment by guymass** [comment]
But can it be done? assuming we invest in such development? and I am sure it can be configurable and set in a standard way that can fit all if the follow a configuration guide. I do think this can greatly extend the system but not in the way it is used today. It causes confusion to many users who are not that technical and tend to loose their access credentials all the time.

**Comment by guymass** [comment]
I think one of our main issues in syncing those two databases is the hash you are using on the passwords of the mysql database as those passwords are hashed before they are stored.

**Comment by guymass** [comment]
https://github.com/WWBN/AVideo/issues/6428
