### ISSUE TITLE
button is cut on plugin page

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6427]
You latest update change something in the plugins page so that the selection button is cut by the top DIV i think.

![Screen Shot 5782-07-22 at 18 58 17](https://user-images.githubusercontent.com/58882903/160156949-6d955f93-7c59-43a7-9de3-9799f9de99a5.jpg)

**Comment by DanielnetoDotCom** [comment]
I guess also has something to do with the RTL thing, 

does it happen after the last RTL updatee?

**Comment by guymass** [comment]
Yes, I have updated few hours ago and than I have seen this while refreshing my plugins page.

**Comment by DanielnetoDotCom** [comment]
Hi

I just sent some updates, I hope it is better now.

**Comment by guymass** [comment]
Great, this issue is fixed, much better now.
