### ISSUE TITLE
Use a more standart password hashing method

### ISSUE THREAD

**Issue by matheusfillipe** [WWBN/AVideo#6428]
**The problem**
If I am not mistaken https://github.com/WWBN/AVideo/blob/8a416c4eacca26229e0d5191119a9cf88ade8bb0/objects/functions.php#L2654 is where the password hashing happens. Problem is `md5(hash("whirlpool", sha1($password)));` isn't any conventional password hashing method.

**Is your feature request related to a problem? Please describe.**
User migration to ldap or using the same database for multiple services. Using a more convenient password hashing algorithm would make everything easier since most other services like ldap.

**Describe the solution you'd like**
Use a more standard hashing method like on the php function `password_hash` https://www.php.net/manual/en/function.password-hash.php.
Then maybe let the admin choose between bcrypt or argon, of course this should be changed only during the installation unless some mechanism for hash updates after there are users already registered is implemented like: Create a password hash update table queue, if user is logging in and is on the list he will be forced to input his password again authenticating with the old hashing method and updating the hash to the be the one with the new algorithm. 

I understand it would be hard to keep backwards compatibility though and this can have pesky results, but you could always try both the new hash and the old hashing methods on the verify function, and keep the default to be the more standard hashing method. 

This would really help us on migrating to ldap.

**If this is too out of scope**

A way to force everyone to log out and have a weebhook or custom code to run for each user login would already help on those migration situations.

**Comment by DanielnetoDotCom** [comment]
You are correct, there is where the password is encrypted.

this is uncoventional for security reasons, but you can use the webservice to encrypt your pass

For example https://demo.avideo.com/objects/encryptPass.json.php?pass=123

this will provide you the password hash

![image](https://user-images.githubusercontent.com/18009293/160423276-2fbfa60f-05fc-48c4-8ac5-ace6d53e86a2.png)

if you enable the option above each site will give you a different hash

https://tutorials.avideo.com/objects/encryptPass.json.php?pass=123

just make sure you save the salt from your configuration.php file, in case you need to reinstall it.

**Comment by matheusfillipe** [comment]
Well I don't want to only check one user's pass, or test the hash.

I believe that for our migration to ldap it would be necessary to force log out all users, invalidating their session cookies in some way to force them to input their password again, and then add a login webhook that can capture user and password and register on ldap if he doesn't exist. At least that is the only way I could think about it because we already have some users on ldap and older ones on the sql database only (with avideo's password hash).

I don't think it would be necessarily hard to implement this, what do you think? Would that be a feature you would want built in on avideo? I think this would be two features, forcing everyone to log out and adding a custom login webhook. This webhook could be either a custom POST domain the admin would configure or at least some way to run custom php code on the backend on specific events like login, signup, etc. What we need for ldap migrations is the login weebhook and forcing logout.

What are your views on this? If you want to point me some directions on how you want this to be implemented I could give a try and open a PR, but right now, I'm not sure how you would want this or if you are interested on having this on avideo. Even if you don't want this feature on avideo would be still helpful to hear some advice from you anyway, maybe there is another way we could be doing this migrations, maybe I could modify just our instance for this but then I'm not sure how to make this force logout.

Thanks in advance.

**Comment by DanielnetoDotCom** [comment]
you should not copy the LDAP passwords into the AVideo. you should centralize the user creation into your LDAP and use the [LDAP ](https://github.com/WWBN/AVideo/wiki/Configure-LDAP-Plugin) plugin to authenticate on it.

For example, if you create a new user or some user updates his password, the AVIdeo will not be able to recognize that. until you update again

also, your LDAP system should not have the password in the clear text all should be encrypted with no way to decrypt it 

so makes no sense to me you want to import your passwords into AVideo users table.

**Comment by matheusfillipe** [comment]
Sorry @DanielnetoDotCom  maybe I've haven't explained it well enough.

Our goal is to migrate all our userbase to LDAP using its password hashing, which by default supports common algorithms like crypt, shad512, mmd5, ssha. That's why I thought it would be a nice feature to be able to use different password hashing algorithms on avideo, or a usual one by default, because then a transition like this one on the future would be painless. We already have ldap login working on our avideo instance and a separated registration website that register new users on ldap. 

The problem is migrating the password of the old AVideo userbase that didn't register on ldap. We wanted this transition to be as painless as possible, we don't want to ask them to register again on the new site, they already registered through avideo before. We want these users to already have access to our other services which require their accounts to be migrated to ldap.

I don't want to import any password into avideo's table, what I was asking about is for a way to force them to have to login again, just make everyon login again on the website, having to input their passwords again, forget their session cookie from the backend, so I can use the password they input to automatically register them on ldap. That was the best idea I could come up with to eventually have them all migrated to ldap, being that when they login again with their passwords I will have to add some code to do the ldap registration given that they are authorized to login on avideo.

No the ldap is not cleartext but I need a webhook that receives the password in cleartext so that I can create the hashes for ldap.

**Comment by DanielnetoDotCom** [comment]
I see, currently we do not have an option to change the hash algorithm

**Comment by guymass** [comment]
How about adding a secondary hash as an option?
