### ISSUE TITLE
Restream Not working

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#6429]
It t doesn't seem like Restream i s working. Anyone else having issues getting restream to work?

When I try nothing happens if I try to restream to another other platforms nothing happens.

**Comment by mrgodgiven** [comment]
same here I have the same problem.

**Comment by DanielnetoDotCom** [comment]
check your logs. 

you also should see a specific log file for the restream ffmpeg command.

**Comment by ganddser** [comment]
[Mon Mar 28 07:58:09.544561 2022] [php7:notice] [pid 000000] [client 0.0.0.0:0000] AVideo includeconfig ignored
[Mon Mar 28 07:58:09.544585 2022] [php7:notice] [pid 000000] [client 0.0.0.0:0000] Restreamer.json.php start https
[Mon Mar 28 07:58:09.546930 2022] [php7:notice] [pid 000000] [client 0.0.0.0:0000] Restreamer.json.php php://input {"m3u8":"https:\\/\\/live.cdn.ypt.me\\/0.m3u8","restreamerURL":"https:\\/\\/live.com\\/plugin\\/Live\\/standAloneFiles\\/restreamer.json.php","restreamsDestinations":[],"token":"0000=","users_id":e,"liveTransmitionHistory_id":0000,"key":"0002"}
[Mon Mar 28 07:58:09.546972 2022] [php7:notice] [pid 000000] [client 0.0.0.0:0000] Restreamer.json.php **ERROR There are no restreams Destinations**
[Mon Mar 28 07:59:29.254257 2022] [php7:notice] [pid 000000] [client 0.0.0.0:0000] AVideo includeconfig ignored
[Mon Mar 28 07:59:29.254279 2022] [php7:notice] [pid 000000] [client 0.0.0.0:0000] Restreamer.json.php start https://example.com/
[Mon Mar 28 07:59:29.256196 2022] [php7:notice] [pid 000000] [client 0.0.0.0:0000] Restreamer.json.php php://input {"m3u8":"https:\\/\\/example.cdn.ypt.me\\/0002.m3u8","restreamerURL":"https:\\/\\/example.com\\/plugin\\/Live\\/standAloneFiles\\/restreamer.json.php","restreamsDestinations":[],"token":"000CM20000=","users_id":e,"liveTransmitionHistory_id":0000,"key":"000002"}
[Mon Mar 28 07:59:29.256246 2022] [php7:notice] [pid 000000] [client 0.0.0.0:0000] Restreamer.json.php **ERROR There are no restreams Destinations**
[Mon Mar 28 08:03:41.723633 2022] [php7:notice] [pid 000000] [client 0.0.0.0:0000] SCORE ==> fileAge = 120 AND lifetimeSeconds = 60
[Mon Mar 28 08:03:41.739003 2022] [php7:notice] [pid 000000] [client 0.0.0.0:0000] PING ==> fileAge = 60 AND lifetimeSeconds = 30

**Comment by DanielnetoDotCom** [comment]
` ERROR There are no restreams Destinations`

so you do not have any restream active for that user.

**Comment by ganddser** [comment]
But I do have destinations set, therein lie the problem for some reason it's not seeing the restream destinations but they are there. Tried it on more than one channel, my users have tried it not working for any

**Comment by DanielnetoDotCom** [comment]
I am not sure, the key must match with the user.

please screenshot your restream datatable on the site

**Comment by ganddser** [comment]
![Untitled-5](https://user-images.githubusercontent.com/37193130/160661090-44dd4004-2595-4570-ab23-93558b4541c8.jpg)
The keys match for Facebook live and other Avideo channels Restream doesn't work for either
