### ISSUE TITLE
Uncaught mysqli_sql_exception: MySQL server has gone away

### ISSUE THREAD

**Issue by sinaisinai** [WWBN/AVideo#6430]
Hi,
Some one no this error ?
how can I solve it ?
I just installed a fresh the Avideo 11 and the encoder on Ubuntu 20.04.
![Capture d’écran 2022-03-26 à 00 31 48](https://user-images.githubusercontent.com/43705498/160214571-acdfd993-adbb-4f35-a6c5-d5347932342b.png)

**Comment by sinaisinai** [comment]
Any help ?
I face this issue when i go on plugin´s page

![Capture d’écran 2022-03-27 à 14 37 02](https://user-images.githubusercontent.com/43705498/160281770-eecc260b-926c-4645-9af9-53f5e4bde06e.png)

**Comment by DanielnetoDotCom** [comment]
Looks like your server cannot handle MySQL.

first check your server diskspace.

than check mysql error log.

sorry I cannot helkp you much with this

**Comment by sinaisinai** [comment]
Thank you very much Daniel !
It was a memory issue.
i upgraded my EC2 server and it works great now.
I can now continue my test.

![Capture d’écran 2022-03-28 à 18 01 54](https://user-images.githubusercontent.com/43705498/160439663-b9762261-20c2-433f-807a-7a27c939c61e.png)

![Capture d’écran 2022-03-28 à 17 57 53](https://user-images.githubusercontent.com/43705498/160438905-6794daec-bdb2-4b60-87f6-f1d95697b5b8.png)
