### ISSUE TITLE
share screen feature on mobile  web view 

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#6431]
Greetings , I would like to ask you to please  add the share  sreen feature on mobile webview .

**Comment by DanielnetoDotCom** [comment]
what is a "share screen feature"

**Comment by mrgodgiven** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/72950503/160308792-0e869366-b0b1-4ed9-a872-ee77f3c46260.png)
this is it, you can't  share  screen  on mobile

**Comment by DanielnetoDotCom** [comment]
I am still not sure what is it

**Comment by JoshWho** [comment]
In the Jitsi Meet there is a share screen option

**Comment by mrgodgiven** [comment]
Mr @DanielnetoDotCom it is the button highled by the pointer in the jitsi meet feature to share a screen or presentationduring a meeting. it only allows share screen via web desktop,but if i use a moble devie to host a meeting then it doesn't show the option or button to share screen. m asking you to help enable screen share button or feature on mobile devices.

**Comment by DanielnetoDotCom** [comment]
I see, I am not sure how can I resolve that. it is a jitsi feature. maybe will be better to ask it on the jitsi project.

https://jitsi.org/user-faq/
