### ISSUE TITLE
How to upgrade from Ubuntu18.4 to Ubuntu20.04 with AVideo and AVideo-encoder

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#6432]
I installed AVideo and AVideo-Encoder under Ubuntu18.04.
Please tell me the procedure to update Ubuntu from 18.04 to 20.04 while keeping the AVideo information.

**Comment by DanielnetoDotCom** [comment]
Hi, to update Ubuntu 18 to 20 you may find it on google. we do not give support to OS upgrade
