### ISSUE TITLE
Mobile View Video wont play Looks like Ad server was causing the issue 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6434]
I have minimize for Mobile selected with Chat2 but it still pops up by default and there is no way to close it.

![Screenshot_20220328-115155](https://user-images.githubusercontent.com/39392449/160448510-b40d74fe-da75-4500-a2da-2dc3595aa278.jpg)

**Comment by JoshWho** [comment]
At first I was thinking maybe the chat was causing it but it is not the issue. Not sure what it is this is the video https://www.joshwhotv.com/video/.QDo_mQ/will-smith-hits-chris-rock-full-video-with-deleted-audio?fbclid=IwAR1csXGRdsgYm5UHTjcM3oB60bL6Ir-AkTj9dRoo53097KHCdc9AJIHssVk

**Comment by JoshWho** [comment]
I disabled the ad server and now it plays. Seems it was the Vast Ads system

**Comment by DanielnetoDotCom** [comment]
does it happen in all videos?

I need to be able to reproduce it.

can you please enable it again or maybe find a way to reproduce it?

**Comment by JoshWho** [comment]
Let me know when u get a chance. Message me on hangouts and I will turn it back on

**Comment by JoshWho** [comment]
Maye be the Google Mod_pagespeed causing it. Closing for now
