### ISSUE TITLE
Only the TOP page works.

### ISSUE THREAD

**Issue by zusso1** [WWBN/AVideo#6436]
It used to work fine, but after a very recent update, only the TOP screen is now functional.
For example, selecting a video.
Trying to open the login page.
Then the whole site frieze.

The browser (Firefox) displays "There is a problem with Content-Encoding".
Is there a solution?

**Comment by DanielnetoDotCom** [comment]
make a git pull and add this in your videos/configuration.php file

`$global['ob_start_callback'] = false;`

**Comment by zusso1** [comment]
Thanks to you, it is back to normal operation.

**Comment by zusso1** [comment]
Question.
Is it possible to add a login with Discord (social login) to AVideo?

2022年3月29日(火) 10:47 Daniel Neto ***@***.***>:

**Comment by DanielnetoDotCom** [comment]
It is possible but it requires some code.

if you want to sponsor this feature you can email me at developer@youphptube.com

**Comment by zusso1** [comment]
Hi  Daniel

, I'm sorry for the inconvenience.
I have the latest version from the git source and I get an error in
functions.php and the site does not show up.
Please check it out.

array(4) { ["type"]=> int(1) ["message"]=> string(535) "Uncaught TypeError:
fgets(): Argument #1 ($stream) must be of type resource, bool given in
/var/www/AVideo/objects/functions.php:8858 Stack trace: #0
/var/www/AVideo/objects/functions.php(8858): fgets() #1
/var/www/AVideo/objects/functions.php(8840): getHtaccessForVideoVersion()
#2 /var/www/AVideo/objects/include_config.php(151): adminSecurityCheck() #3
/var/www/AVideo/videos/configuration.php(48): require_once('...') #4
/var/www/AVideo/view/index.php(26): require_once('...') #5 {main} thrown"
["file"]=> string(43) "/var/www/AVideo/objects/functions.php" ["line"]=>
int(8858) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(535) "Uncaught TypeError: fgets(): Argument #1 ($stream) must be
of type resource, bool given in /var/www/AVideo/objects/functions.php:8858
Stack trace:
#0 /var/www/AVideo/objects/functions.php(8858): fgets()
#1 /var/www/AVideo/objects/functions.php(8840): getHtaccessForVideoVersion()
#2 /var/www/AVideo/objects/include_config.php(151): adminSecurityCheck()
#3 /var/www/AVideo/videos/configuration.php(48): require_once('...')
#4 /var/www/AVideo/view/index.php(26): require_once('...')
#5 {main}
  thrown"
  ["file"]=>
  string(43) "/var/www/AVideo/objects/functions.php"
  ["line"]=>
  int(8858)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}


2022年5月23日(月) 22:29 Daniel Neto ***@***.***>:

**Comment by DanielnetoDotCom** [comment]
same as here: https://github.com/WWBN/AVideo/issues/6831 

please update and try again

**Comment by zusso1** [comment]
New problem.
After upgrading, YPTSocket will not start up.
I can't even start it after doing a kill.

# php /var/www/AVideo/plugin/YPTSocket/server.php and stopServer.php
commands show nothing and no change.
I do not know the cause.

2022年7月8日(金) 10:21 ずっと一人 ***@***.***>:

**Comment by DanielnetoDotCom** [comment]
Make sure you use sudo on the socket command line

**Comment by zusso1** [comment]
Thank you.
Your work is excellent.

2022年7月8日(金) 10:15 Daniel Neto ***@***.***>:
