### ISSUE TITLE
Installation instructions for Ubuntu

### ISSUE THREAD

**Issue by tbprince** [WWBN/AVideo#6439]
We were able to find installation instructions for Debian 11 but we couldn't find that for Ubuntu. Could you please provide them or a link?

Thanks.

**Comment by DanielnetoDotCom** [comment]
Please check this 

https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x-for-AVideo-Platform-version-11.x-or-newer

**Comment by tbprince** [comment]
Hello,

we are having issues when deploying Encoder Network. When trying to install it we receive the following error:

[Wed Apr 06 10:21:50.894840 2022] [php:warn] [pid 93182] [client XX.XX.XX.XX:30649] PHP Warning:  Undefined variable $global in /var/www/html/AVideo-Encoder-Network-master/install/index.php on line 28
[Wed Apr 06 10:21:50.894888 2022] [php:warn] [pid 93182] [client XX.XX.XX.XX:30649] PHP Warning:  Trying to access array offset on value of type null in /var/www/html/AVideo-Encoder-Network-master/install/index.php on line 28
[Wed Apr 06 10:21:50.895372 2022] [php:error] [pid 93182] [client XX.XX.XX.XX:30649] PHP Fatal error:  Uncaught ValueError: Path cannot be empty in /var/www/html/AVideo-Encoder-Network-master/install/index.php:45\nStack trace:\n#0 /var/www/html/AVideo-Encoder-Network-master/install/index.php(45): file_put_contents()\n#1 {main}\n  thrown in /var/www/html/AVideo-Encoder-Network-master/install/index.php on line 45

Any hint?

Thanks.
