### ISSUE TITLE
Deployment suggestions using YPTStorage plugin

### ISSUE THREAD

**Issue by tbprince** [WWBN/AVideo#6440]
Hello,

we would like to deploy like this:

- front-end
- storage servers
- transcoders

using YPTStorage plugin.

My first question is: can we consolidate transcoders and storage servers? Would that hurt the streaming performances too much? 

By the way, I understand that if we deploy the YPTStorage plugin hence storage servers, actual streaming will happen from the storage servers. Is that true for LIVE streaming as well or would that only happen from frontends? Generally speaking, we would prefer streaming to happen from storage servers as well so we could consolidate and also place different servers in different regions.

Does LIVE streaming only happen from frontends or using YPTStorage plugin that would also use storage servers like on-demand streaming?

Thanks.

**Comment by tbprince** [comment]
Also, can we assign specific storage servers to specific users only while leaving shared storage servers available to other users?

Thanks.

**Comment by DanielnetoDotCom** [comment]
> My first question is: can we consolidate transcoders and storage servers? Would that hurt the streaming performances too much?

Yes, encoders and storages can be on the same server
I do not think it will hurt the streamer as long as the encoder uses more CPU and the storage uses more bandwidth

> Does LIVE streaming only happen from frontends or using YPTStorage plugin that would also use storage servers like on-demand streaming?

there is no relation between live and storage but you also can use the storage serer to deploy a live server

> Also, can we assign specific storage servers to specific users only while leaving shared storage servers available to other users?

I did not understand this question

**Comment by tbprince** [comment]
> > Also, can we assign specific storage servers to specific users only while leaving shared storage servers available to other users?
> 
> I did not understand this question

My question is if we can dedicate one or more storage servers to a single user/channel while we let other server be shared among other users. For ex.

Server1 - Frontend with 10 users (user1, user2, user3...)
Server 2 - Storage server for user1
Server 3 - Storage server for all other users

The same question applies to transcoders and to live servers.

Thanks.

**Comment by DanielnetoDotCom** [comment]
> Server1 - Frontend with 10 users (user1, user2, user3...)
> Server 2 - Storage server for user1

You can select a default storage per user

> Server 3 - Storage server for all other users

yes

> The same question applies to transcoders and to live servers.

Encoders, "Encoder-Network" does not use a default encoder, it always try to use the one that is not busy
