### ISSUE TITLE
AD video campaigns

### ISSUE THREAD

**Issue by tbprince** [WWBN/AVideo#6441]
Hello,

I noticed that AD video campaigns (pre-rolls, mid-rolls, post-rolls etc.) get configured at admin level so that every user will basically run the same ads (a la YouTube). Is it possible to configure users so such campaigns are delegated to specific users/channels thereby allowing users to run their own AD video campaigns?

Thanks.

**Comment by DanielnetoDotCom** [comment]
For now we do not have this option, but we may add it in the future
