### ISSUE TITLE
Stream not playing on mobile app

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6444]
Where should I start looking as to why the stream plays on the website but not on the mobile app. There is a notification of a live stream on the mobile and a video window opens but the play icon just spins after clicking on it.
![8615BCB5-490D-4F32-AFA8-5097CE326D30](https://user-images.githubusercontent.com/58601786/161064976-2c8dd853-79d8-4cbd-a1e7-a3abb7f51820.jpeg)

**Comment by DanielnetoDotCom** [comment]
Is the problem the notification or the video playback?

do you mean it is playing on the browser but does not play on mobile?

How are you live streaming? with what tool? 

you may want to try a different output configuration on your OBS (if you are using it), for example, make sure you are using the output max 720p, also try to reduce the FPS

**Comment by barrunning** [comment]
Video playback.  Using OBS or from website. Yes plays on browser but not on mobile app.

**Comment by DanielnetoDotCom** [comment]
So, can you please make sure you are using the output max 720p, also try to reduce the FPS as well
