### ISSUE TITLE
YPT Socket Not Connecting

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#6445]
YPT Socket not connecting. Here is a screen shot for you to see what is happening
![ypt](https://user-images.githubusercontent.com/37937968/161132208-14587d85-76cd-4d4f-b254-a7960f31ab7a.png)

And Yes I Have A connection with OBS

![obs-connect](https://user-images.githubusercontent.com/37937968/161132826-dcedc9c2-10c7-4c6e-bb62-0d2434468709.png)

**Comment by DanielnetoDotCom** [comment]
stop your firewall and try again. 

if works the problem is your firewall

**Comment by DanielnetoDotCom** [comment]
I am pretty sure you also need to add the port 2053 UDP, you currently only have 2053 TCP

**Comment by JoshWho** [comment]
Might be the same issue I had with the certs directory changing with Letsencrypt

**Comment by Lordblanca** [comment]
[DanielnetoDotCom](https://github.com/DanielnetoDotCom) 
[JoshWho](https://github.com/JoshWho)
Are all of the secure sockets supposed to be green or just One of the three

**Comment by Lordblanca** [comment]
[DanielnetoDotCom](https://github.com/DanielnetoDotCom) You are the man. God Bless
