### ISSUE TITLE
Adding a channel live stream to its Channel Page

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6450]
We think it would be a great idea and a good feature to add the live stream also to the channel's own page, thus allowing people who only follow certain channels to enter and view the live stream on the channel page as well as through a direct url.

Maybe by adding additional tab for Live or having a copy of the url play above the tabs:

![Screen Shot 5782-07-29 at 19 45 46](https://user-images.githubusercontent.com/58882903/161306924-3afe6b75-2ca3-41e6-b8c3-fae30474f799.jpg)

**Comment by DanielnetoDotCom** [comment]
I agree, I may add something in the future

**Comment by guymass** [comment]
Cool, will be waiting...
