### ISSUE TITLE
Set the user permission to a group

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6452]
We have currently few 1000's users and we wish to change the permissions for all regular None-Admin users so that all of them appear as the following screen shot:
![Screen Shot 5782-07-29 at 21 21 01](https://user-images.githubusercontent.com/58882903/161320588-ea8ed9b4-8034-4f84-92ea-b8698e94b1e3.jpg)

Is there a quick way to set those options to all the users instead of going through them one by one, saving, closing and reopening a new user to edit, this is impossible task. Group permissions only deal with admin/managing stuff and not in regards to functions. For example I would like to have a group that can only stream, a group that can stream and record and upload, and a group that can have premium access to all functions including Meet. Also each group has its own DiskQuota and in this way we can manage services based on the user group rather than going through all those options for each user and we just can't overcome the amount of users and the time it takes to edit and set each user. 
If we wanted to charge users for different service like streaming/recording or uploading content not just viewing it as PPV etc. We need to have more flexibility on the permissions we can give users to use those options in groups as well.

**Comment by DanielnetoDotCom** [comment]
Hi, sorry currently that is the way

but I am accepting ideas of how an easy way should look like
