### ISSUE TITLE
Changing the way we select quota package

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6453]
Currently when setting the user's disk quota assuming we have few packages to choose from, a window pops up where I select the package like this:
![Screen Shot 5782-07-29 at 22 52 00](https://user-images.githubusercontent.com/58882903/161332551-76a893c7-5f85-4abf-9e7b-577fe720f01b.jpg)

Not only that, clicking "Save" will open another OK popup to click on. This is a bit too much and I think can be just added as simple selections under the user details:
Adding these packages as selections

![Screen Shot 5782-07-29 at 22 52 15](https://user-images.githubusercontent.com/58882903/161332753-d06c1cf9-3e27-41c6-b234-630ef0a7b46f.jpg)

where this list shows or in the user edit details so its all in a single window and a single quick save.
![Screen Shot 5782-07-29 at 22 52 08](https://user-images.githubusercontent.com/58882903/161332917-c5c139a2-d473-4cdb-baf6-6a2ddc639c5e.jpg)

Admins already know which packages are which by the title, this is enough to set a quota for a user, those boxes should only show to the user when they purchase extra storage package. and we wish them to see the package details. Setting quota should be like enable/disable option IMHO.

**Comment by guymass** [comment]
Also how can I preset quotas for users upon their registration? like having a default one selected for all new registered users.

**Comment by DanielnetoDotCom** [comment]
> Also how can I preset quotas for users upon their registration? like having a default one selected for all new registered users.

Setup a free plan, with value 0

**Comment by guymass** [comment]
OK thanks.
