### ISSUE TITLE
Quota selection is not being saved!

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6454]
I have created four different quota selections:

![Screen Shot 5782-07-29 at 23 36 07](https://user-images.githubusercontent.com/58882903/161338714-c953edd6-9478-4e5b-96ba-1d8195e4d9fa.jpg)

and after saving and refreshing the page and the list I reopen the same users quota and no selection appears, as if it has not been selected. I have repeated selecting and saving several times and I keep getting this back:

![Screen Shot 5782-07-29 at 23 36 33](https://user-images.githubusercontent.com/58882903/161338875-b968fe2e-7517-474d-bd6d-e5a2d1f49cca.jpg)

Also I would like to allow my users to keep their videos and embeds playing but only prevent them from creating or uploading new content if the exceeded their quota. They content they already have in their channels should remain running untouched.

**Comment by DanielnetoDotCom** [comment]
Hi

first, let's resolve your quota saving...

I can see they are valid for 0 days, it is requires add some days to the quota

also, check if the plans are active. can you please screenshot the Datagrid from the quota plans?

**Comment by guymass** [comment]
I disabled it for now because it causes issues to my users, I will need to find time late at night on the weekend to do testing again on this plugin. I will try to add those days and see if this solve this saving issue.

**Comment by guymass** [comment]
Still cannot save quota packages. Until this is fixed I cannot use the plugin as it blocks user's embeds and we want to allow the option that previous content will still be available even if the reached their quota. Only new Uploads, Stream and Encodings should be blocked IMO or at least allow the option for it.
 
![Screen Shot 5782-08-07 at 22 34 19](https://user-images.githubusercontent.com/58882903/162515310-9419c67e-3051-4747-8f4f-edd53e15448b.jpg)
![Screen Shot 5782-08-07 at 22 28 27](https://user-images.githubusercontent.com/58882903/162515330-696dcf5e-8472-4602-8760-ad85cbfe312d.jpg)
![Screen Shot 5782-08-07 at 22 34 42](https://user-images.githubusercontent.com/58882903/162515327-a18dca6a-bcc0-4589-8ca8-635065e8873b.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi

the issue is not clear

you still not able to save plans?
What is the error? 
there is something on avideo.log or js console?

regarding the improvement idea , can you please open an new issue for that ?

**Comment by guymass** [comment]
Yes, the issue is that I cannot save it. The first Image show the plan is marked with a V and the OK pop up (which I dont think is needed to press on another window). The second image shows that I open the same user's quota and it is showing non of the packages are selected, which mean IMO that it wasn't saved.

I pasted here screenshots and the info in the console but it doesn't tell me anything, so idk really what is going on there. Maybe because that package is a 1T space? maybe its a SQL error, currently idk.

**Comment by DanielnetoDotCom** [comment]
I just added the same configuration as you did and I saw this on the log file

`AVideoLog::DEBUG: UploadQuotaUser: addOrRenewUserInPlan the plan: (1) has empty days valid SCRIPT_NAME: /YouPHPTube/plugin/DiskUploadQuota/page/saveUserPlans.json.php`

I am pretty sure you have the same on your side, You need to change the total days to the same amount as the free trial (NOT ZERO)

![image](https://user-images.githubusercontent.com/18009293/163834423-e1f72cb6-005c-4f3b-b6c0-3f68c69958e9.png)

after that all is fine.

FYI: if there is no payment, the free trial makes no sense

**Comment by guymass** [comment]
OK thank you that solved it.
