### ISSUE TITLE
Problems with resolution and white squares on the screen

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6456]
Hi Daniel,

1- For some time now I have been facing a problem with the minimum resolution of the platform.
Check the link below, that I have to keep the browser zoom at 90%, because at 100% I can't see all the information. My monitor's current resolution is 1280x800 pixels.

2- Another problem that you can also see in this video is the presence of white squares on the screen. This problem only presents when I'm accessing the platform, other sites don't have it.

Link video:
https://vimeo.com/695086784/06da5c8440

**Comment by gbrn** [comment]
I did a test, in another browser (Microsoft Edge). The resolution problem presents the same.
The second problem, the white squares doesn't show up in Edge.

**Comment by DanielnetoDotCom** [comment]
do you have the VideoResolutionSwitcher plugin?

https://youphp.tube/marketplace/

**Comment by gbrn** [comment]
Hi Daniel,

It's not about the resolution of the videos.
I mean about the screen width pixels. Website width.
Using a monitor with a resolution of 1280x800 pixels, it is not possible to view all the information.

I show the example in this video: https://vimeo.com/695086784/06da5c8440

**Comment by DanielnetoDotCom** [comment]
yes, you are right, to see all the informations on the videos manager you may need a larger screen

try to zoom out 
Control and minus sign on the keyboard (ctrl)+(-)

**Comment by gbrn** [comment]
Yes Daniel, that's what I've been doing using the zoom in the browser.
But I think it could have an adaptive function, no?

What is the current minimum resolution programmed?

**Comment by gbrn** [comment]
@DanielnetoDotCom Estive verificando que a resolução padrão mínima é 1546 pixels de largura. 
![image](https://user-images.githubusercontent.com/37880073/171268905-54ebfc0a-fc10-4adc-9457-0de332c503cf.png)

Ainda existem os monitores 1280 pixels de largura (5ª resolução mais utilizada), e monitores de 1366 pixels sendo a segunda resolução mais utilizada.
![StatCounter-resolution-ww-monthly-202104-202204-bar](https://user-images.githubusercontent.com/37880073/171270332-b40b1b25-46aa-4e18-a5d3-06b226676581.png)

**Comment by DanielnetoDotCom** [comment]
esta é exatamente a mesma configuração do youtube
