### ISSUE TITLE
How to embed a facebook video or post  with link?

### ISSUE THREAD

**Issue by sinaisinai** [WWBN/AVideo#6458]
Hi
I try to embed a video from facebook but it doesn´t work. Is it normal ? is there some parameters that i have to enable before it works ?

![Capture d’écran 2022-04-02 à 17 43 46](https://user-images.githubusercontent.com/43705498/161391367-5fab78a2-62ee-4fe2-bd3b-834b19f3297f.png)

**Comment by DanielnetoDotCom** [comment]
no, the only thing I can see is that you do not have a thumbnail image
