### ISSUE TITLE
ad server not showing video ads

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#6461]
Hello Daniel
I've been trying to run ads for quite some time but they don't show up
any help?
![ads](https://user-images.githubusercontent.com/60543030/161428662-77ad69cc-c920-49cb-b57b-52b35c7ea115.jpg)

Thank you
Ilias

**Comment by wetubeclub** [comment]
I also tried it on the demo site and there it did not show ads

**Comment by DanielnetoDotCom** [comment]
Hi, 

in your case, I found this on your logs ...

`AVideoLog::DEBUG: showAds: Subscription said NOT to show ads on ...` 

so if a user is a paid user, he will not see ads.

only users without subscriptions plans will see ads

**Comment by wetubeclub** [comment]
> Hi,
> 
> in your case, I found this on your logs ...
> 
> `AVideoLog::DEBUG: showAds: Subscription said NOT to show ads on ...`
> 
> so if a user is a paid user, he will not see ads.
> 
> only users without subscriptions plans will see ads
Thank you very much Daniel!!!
