### ISSUE TITLE
Video won't play in chrome or safari phone browsers 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#6462]
But it will play on Android opera browser 

https://fakeotube.com/v/4725

This happens on many videos.

**Comment by DanielnetoDotCom** [comment]
the video plays on the browser and also on iPhone

![IMG_71E93FF61D36-1](https://user-images.githubusercontent.com/18009293/161602017-43a7d781-e063-4239-b980-1656b4dfb011.jpeg)

**Comment by fakeologist** [comment]
Still doesn't work in both my chrome browsers. It tries to start by just stops.
https://user-images.githubusercontent.com/66537018/161626110-537757f4-60b6-401e-a444-4a1b58283159.mp4

**Comment by DanielnetoDotCom** [comment]
Just tested again on iPhone Chrome and Safari, works on both.

![IMG_0393](https://user-images.githubusercontent.com/18009293/161818279-a231ee68-a644-4731-a684-bdf86cbc53e8.PNG)
![IMG_0392](https://user-images.githubusercontent.com/18009293/161818294-c80cc05b-376b-47c3-87f4-823eededf2c8.PNG)


maybe is your network.

if you can make some tests with the CDN, I am sure you will notice the network and speed playback improvements

https://github.com/WWBN/AVideo/wiki/CDN-Plugin

**Comment by fakeologist** [comment]
I doubt it's a network. It works fine on Firefox and opera Android browsers. It seems to be a problem with chrome browsers, which sadly are the most common browsers used on Androids. I've even cleared my caches as well. A friend with an iPhone has the same problem and he is in another country.

**Comment by DanielnetoDotCom** [comment]
I have disabled your AD_Server plugin, you had it enabled but was no video on it. I mean an empty video ad.

Looks like the android player crashes if you try to play an empty ad

please check it now

**Comment by fakeologist** [comment]
Thanks that worked! I knew you would fix it. Does it make sense for me to activate the CDN platform? Is that for live streams too?

**Comment by DanielnetoDotCom** [comment]
Yes. The CDN will improve your VOD and live playbacks
