### ISSUE TITLE
Help! What is the config that I turned on that covers the video page with a full screen player?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6463]
**Describe the question**
I was trying to figure out why my Video site on iPhone/Mobile does not play in full screen.

After drilling through all 11,000 of the preferences I turned on a setting that covers the video page and all useful metadata, description, sharing links, etc...

**Screenshots**
Here is a screenshot from me resizing the window wildly to see glimpses of the video page.

How do I turn this back off?
<img width="643" alt="Screen Shot 2022-04-04 at 11 30 40 AM" src="https://user-images.githubusercontent.com/11711050/161608802-1064acef-2ea7-4938-aa11-11fbbb054a06.png">

**Comment by DanielnetoDotCom** [comment]
Please disable the plugin FloatVideo and clear the cache and try again

**Comment by walt93** [comment]
![Screen Shot 2022-04-08 at 10 07 42 AM](https://user-images.githubusercontent.com/11711050/162489779-9d5e9e4a-29ff-4b73-bd7c-c1e5096673c7.png)

Negative. Turned off. Cleared first page cache. Cleared cache directory. Generated Sitemap. No change.

**Comment by DanielnetoDotCom** [comment]
Please share the link here so I can check

**Comment by walt93** [comment]
Any video on https://conspyre.tv. eg https://conspyre.tv/video/7706/the-vaxxed-may-no-longer-have-human-rights-and-this-is-why---explained

This mode seems broken and in need of some love... 
![D7FE31DC-D209-44A1-9284-E4AF5A72DD3D](https://user-images.githubusercontent.com/11711050/162546895-38bdec1c-c621-47c1-84da-cae4ea40d153.jpeg)

**Comment by DanielnetoDotCom** [comment]
Seems to me you messed up with some plugins configuration.

I do not know what is causing that., so I recommend you to reset all the plugins...

Try this

`cd /var/www/html/AVideo/install`

than

```
# php resetPlugins.php 
1 - Reset all plugins Parameters
2 - Reset CustomizeUser Plugin Parameters only
3 - Reset all plugins (Will also inactivate the plugins)
Choose an option: 
```

Choose option 1

**Comment by walt93** [comment]
Ouch
