### ISSUE TITLE
Can not run Webrtc server command line - OBS brodcast doesn´t appear on the first page

### ISSUE THREAD

**Issue by sinaisinai** [WWBN/AVideo#6464]
Hi Daniel,
I can not stream live properly. 

1-   When i try the command line to setup the live plugin, I get this error: Could not open input file: /var/www/html/AVideo/plugin/Live/standAloneFiles/WebRTCServer/server.php

2-  When i try to broadcast a live from OBS, the stream is not shown on the first page.
If i schedule a stream with the player URL (https://domain.ltd:8443/live/604b737gtbc47f-1.m3u8) there i can see the live stream on the first page.

3-  Also,  when i click on the button "**Broadcast a live**" I find that my view is little different from what we can see in your live broadcast tutorial video. there is no live preview. Is it normal ?

**Screenshots**
I
![Capture d’écran 2022-04-05 à 12 27 54](https://user-images.githubusercontent.com/43705498/161740988-72a05ff6-5f93-4e0b-897c-21ebdbc31639.png)
![Capture d’écran 2022-04-05 à 12 30 47](https://user-images.githubusercontent.com/43705498/161740997-0d4caec3-b73d-4862-b21c-9df6dd97e65d.png)

![Capture d’écran 2022-04-05 à 12 25 33](https://user-images.githubusercontent.com/43705498/161740972-64bf9d3e-2537-4036-bbee-3dc23cc92fc4.png)
![Capture d’écran 2022-04-05 à 12 26 34](https://user-images.githubusercontent.com/43705498/161740978-21f5bae4-42b3-47f5-aa05-c043d12f9b69.png)

**Desktop (please complete the following information):**
Avideo: 11 updated
Ubuntu 20.04
Google Chrome

Can you help please ?

**Comment by sinaisinai** [comment]
![Capture d’écran 2022-04-05 à 15 25 13](https://user-images.githubusercontent.com/43705498/161764112-4a9499a2-5038-4125-a44d-d0a2413c88f8.png)

**Comment by sinaisinai** [comment]
![Capture d’écran 2022-04-05 à 15 27 43](https://user-images.githubusercontent.com/43705498/161764547-35c622ba-460b-4d72-9f82-8f44048dab75.png)

**Comment by sinaisinai** [comment]
![Capture d’écran 2022-04-05 à 15 40 20](https://user-images.githubusercontent.com/43705498/161766990-1ff189e7-3c12-4490-a729-c7ed42db130e.png)

**Comment by DanielnetoDotCom** [comment]
Webrtc is still under development, and the server is not working yet

regarding the obs live stream, I recommend you to open a new issue and provide more details of what exactly is happening.
