### ISSUE TITLE
Allow specific access to videos

### ISSUE THREAD

**Issue by reuvygroovy** [WWBN/AVideo#6465]
Is there a way to deny anonymous access to videos and only allow specific and/or registered users to access/see a video?

**Comment by reuvygroovy** [comment]
So truth is that when I limit it like this
![image](https://user-images.githubusercontent.com/1325158/162013511-fd5bebd3-a063-408b-8f11-58e31996a100.png)

Then when a users tries to view the video they get:
![image](https://user-images.githubusercontent.com/1325158/162013574-02387f61-89db-4019-aaf6-bde902904171.png)

Problem is that it appears on the home page / list of videos:
![image](https://user-images.githubusercontent.com/1325158/162013427-4360ebd8-75cd-4be9-b82e-cf82de2f65fe.png)

Any way to hide it?

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/162015295-32363b4f-70e2-4da5-a9e1-a905fdf81733.png)

**Comment by DanielnetoDotCom** [comment]
This it the plugins menu on The top left menu

**Comment by reuvygroovy** [comment]
But I don't have any plugins.

**Comment by DanielnetoDotCom** [comment]
You must have

the default installation include a bunch of free plugins 

if they are not listing you may have a problem and you will need to share the avideo.log

**Comment by swi33ty** [comment]
Hi,
I'm connecting to this topic.
My scenario:
I did everything as DanielDotCom says.
- I have a user group called "Importand-G"
- One of my categories is called " Important-C"
- the movie clip "important-m" belongs to the "important-c" category
- there's a "test" user with is not a member of the Important-G user group
- the users need to log in to see the content.
- I have "hidePrivateVideos" option checked in the gallery plugin's option
Problems:
1. the "test" user can see thumbnails of all movies (including private and "important-C" category
2. the "test" user can see all categories on the left side of the main panel
when he clicks on the "Important-C" category, all thumbnails are listed and he can see the shorts of the videos.

Expectations :
1. Could users have the ability to list only categories that they have an access to 
2. Could you please fix  "hidePrivateVideos" option in the gallery plugin

**Comment by DanielnetoDotCom** [comment]
I am traveling this week, I will review it when I get back next week

**Comment by DanielnetoDotCom** [comment]
I just send an update, please check if it resolves the category user groups hide on first page

**Comment by swi33ty** [comment]
Thank you.

What I did:
Changed these files in my existing instance
- objects/video.php
- view/include/footer.php
- view/modeYoutubeBundle.php

to the new one from this commit 
https://github.com/WWBN/AVideo/issues/6465

Fixed:
- hidePrivateVideos option works fine
- users are able to see public videos and from groups, there are assigned to

Problems:
- users are unable to see videos (menu section my videos). It includes Admin users and regular users.
- I cannot finish the encoding process. Video is uploading, encoder putting it to the queue and stuck.

**Comment by DanielnetoDotCom** [comment]
> users are unable to see videos (menu section my videos). It includes Admin users and regular users.
> I cannot finish the encoding process. Video is uploading, encoder putting it to the queue and stuck.

the problems above seem to be different issues and they are not related to the update. please open a new issue for each and provide the logs for both

**Comment by DanielnetoDotCom** [comment]
Can you please check if this is fixed on the last update?

**Comment by swi33ty** [comment]
I've replaced all using the last available source on GitHub/master and it works perfectly.
Thank you for your time. The topic is closed from my side.
