### ISSUE TITLE
Fast Forward/ Scrubbing does not work on certain videos

### ISSUE THREAD

**Issue by aolvictim** [WWBN/AVideo#6466]
**Describe the bug**
I haven't be able to identify the common characteristics yet, but some videos does not allow "scrubbing". They seem to be longer videos.

Here is an example that DOES NOT allow scrubbing: 
https://juxxi.com/videoEmbed/28430/new-products-feat.-paul-levy-censorship-tool-of-cowards-liars-bullies-%7C-sotg-1124

Here is a long video that DOES allow:
https://juxxi.com/video/46802/color-wars-w-the-late-steve-lauer-also-scott-hambrick-%7C-sotg-1132?channelName=StudentoftheGun

**Comment by DanielnetoDotCom** [comment]
I suspect the movie (video file) is corrupted
