### ISSUE TITLE
What are .jpg files used for?

### ISSUE THREAD

**Issue by JeanDavis91** [WWBN/AVideo#6468]
Hello

I would like to know what is the use of these .jpg files framed in red

![A quoi cela](https://user-images.githubusercontent.com/61474191/162088259-cc096627-0368-4f36-abda-7c6b27b4cfbb.jpg)

Thank you for your great work

JfrPro

**Comment by DanielnetoDotCom** [comment]
For the MediaSession.metadata

https://developer.mozilla.org/en-US/docs/Web/API/MediaSession/metadata
