### ISSUE TITLE
Since last evening update Site is down!

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6469]
Since yesterday I made a git pull and since then the site is down, or very slow and no live stream working.

This is from the log:
![Screen Shot 5782-08-06 at 15 44 43](https://user-images.githubusercontent.com/58882903/162201972-ec7b2593-d4aa-46dc-9636-17569d3a7fe9.jpg)

**Comment by guymass** [comment]
OK made another update now and its back on, but I will keep checking for few more hours before I close this, not sure if there are other issues because of this update.

**Comment by guymass** [comment]
What I do see now is the the Network Encoders Iframe doesn't open my encoders page anymore.
![Screen Shot 5782-08-06 at 15 56 57](https://user-images.githubusercontent.com/58882903/162204448-90a9013b-6139-453e-8e4b-49f0db728325.jpg)

**Comment by guymass** [comment]
I also see these error repeating in the log:
![Screen Shot 5782-08-06 at 15 44 43](https://user-images.githubusercontent.com/58882903/162206682-f7664941-4ae2-4b42-a003-b335698a579e.jpg)

**Comment by guymass** [comment]
OK Im closing this issue because this was my fault as I forgot we were upgrading the Network Encoders server and it should have been restarting after the upgrade but it actually was shutdown and that is way the encoder page would not open. Sorry for this hassle, I am closing this issue/

**Comment by DanielnetoDotCom** [comment]
But check this for your error logs

https://github.com/WWBN/AVideo/issues/6389#issuecomment-1068284923
