### ISSUE TITLE
404 not found for plugin page when running NGINx

### ISSUE THREAD

**Issue by wakozuka** [WWBN/AVideo#6471]
Hi man,

after i failed to get RTMP up and failed to activate LIVE plugin with apache to link with OBS, i reinstalled the OS and install youPHPtube this time under NGINX so RTMP can work. but i get 404 error in plugin page.
![capture](https://user-images.githubusercontent.com/28747650/162259632-1e7469f9-4405-474b-aec9-2d889757e1bd.PNG)

thanks, man in advance, 
you've been a great help.

**Comment by DanielnetoDotCom** [comment]
probably the mod_rewrite

sorry, we only support apache.

**Comment by wakozuka** [comment]
> probably the mod_rewrite
> 
> sorry, we only support apache.

is there an integration plugin that works with apache that can enable OBS to connect?

**Comment by DanielnetoDotCom** [comment]
I am not sure what you are asking.

the default installation we use Apache (Webserver) and Nginx (RTMP server)

**Comment by wakozuka** [comment]
thanks, I've understood now, i need to create a ngix( rtmp server)
