### ISSUE TITLE
script errors:  array type when resetting streamkey

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6473]
array(4) { ["type"]=> int(1) ["message"]=> string(123) "Cannot redeclare cmp() (previously declared in xxx/plugin/AVideoPlugin.php:896)" ["file"]=> string(71) "xxx/plugin/AVideoPlugin.php" ["line"]=> int(896) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(123) "Cannot redeclare cmp() (previously declared in xxx/plugin/AVideoPlugin.php:896)"
  ["file"]=>
  string(71) "xxx/plugin/AVideoPlugin.php"
  ["line"]=>
  int(896)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}

@DanielnetoDotCom I receive this error when I attempt to reset my streamkey.

latest git.

also happens when I try to login using the app.

**Comment by DanielnetoDotCom** [comment]
can you please try this update?

**Comment by jengajenga** [comment]
array(4) { ["type"]=> int(1) ["message"]=> string(146) "Cannot redeclare getLiveApplicationArrayCMP() (previously declared in /xxx/plugin/AVideoPlugin.php:896)" ["file"]=> string(71) "/xxx/plugin/AVideoPlugin.php" ["line"]=> int(896) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(146) "Cannot redeclare getLiveApplicationArrayCMP() (previously declared in /xxx/plugin/AVideoPlugin.php:896)"
  ["file"]=>
  string(71) "/xxx/plugin/AVideoPlugin.php"
  ["line"]=>
  int(896)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}

@DanielnetoDotCom thanks for the update but I'm getting the same error. any other solution?

**Comment by DanielnetoDotCom** [comment]
Sorry can you please try this again?

**Comment by jengajenga** [comment]
> Sorry can you please try this again?

Thanks @DanielnetoDotCom this one has worked. I'll open another thread for another issue though I feel they're similar.

Thank you.
