### ISSUE TITLE
Server restart procedure

### ISSUE THREAD

**Issue by consultingforge** [WWBN/AVideo#6474]
Is there any specific procedure for server/vps reboot?

**Comment by DanielnetoDotCom** [comment]
Once you reboot check 2 things ...

1. if the Nginx RTMP is running or[ just restart it](https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server#7-start-nginx)
2. Check if the socket is running, [stop ](https://github.com/WWBN/AVideo/wiki/Socket-Plugin#stop) and [start ](https://github.com/WWBN/AVideo/wiki/Socket-Plugin#start) it again

**Comment by consultingforge** [comment]
Perfect! Thanks!
