### ISSUE TITLE
I am unable to log into the plugin store

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6475]
I use the log in with google and when I try I get a 500 error 

![Screenshot from 2022-04-08 08-42-58](https://user-images.githubusercontent.com/39392449/162447950-ce259ec9-2f63-41f2-bba5-8f1b3c1c7f24.png)

**Comment by DanielnetoDotCom** [comment]
Strange, I just login without any problem

can you please try again?

**Comment by JoshWho** [comment]
same error

**Comment by DanielnetoDotCom** [comment]
Hi

I found something...

looks like your user is from the tutorials site, NOT from google. but both have the same email, that is what was confusing.

can you please try again?

**Comment by JoshWho** [comment]
Working now, Thank you @DanielnetoDotCom
