### ISSUE TITLE
Plugin: SubtitleSwitcher

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo#6476]
**Describe the bug**
The plugin doesn't allow the same subtitles languages from different countries. Example:

-Subtitle Spanish ( Spain )
-Subtitle Spanish ( Latino America )

The second subtitle added gets ignored.

No logs recorded when adding subtitles.

**Comment by DanielnetoDotCom** [comment]
Hi

you may need to add the language here https://github.com/WWBN/AVideo/blob/master/objects/bcp47.php

if you do, please send a pull request so it will not be lost on next update

**Comment by DanielnetoDotCom** [comment]
reviewing the code ...


-Subtitle Spanish ( Spain ) => ['value' => 'es_ES','label' => 'Spanish (Spain)', 'flag' => 'es']
-Subtitle Spanish ( Latino America ) => ['value' => 'es','label' => 'Spanish', 'flag' => 'es']

so for Spain use `es_ES`
for LatAm use `es`

**Comment by akhilleusuggo** [comment]
Sorry, I was away. 

What I see is this:

`['value' => 'es_419','label' => 'Spanish (Latin America)', 'flag' => '419'],`

`['value' => 'es_ES','label' => 'Spanish (Spain)', 'flag' => 'es'],`

`['value' => 'es','label' => 'Spanish', 'flag' => 'es'],`

What should be identical is Spanish Spain to just Spanish.
Spanish Latino America should get it's own subtitle field.

**Comment by DanielnetoDotCom** [comment]
Sorry, but I did not get what you want to do.

as I see it is up to you whatever flag do you want to use
