### ISSUE TITLE
Blank Page every now and then this is what is shows when it does it

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6477]
This just randomly happens in between browsing from page to page. Not every time though, just random.

![Screenshot from 2022-04-09 05-17-43](https://user-images.githubusercontent.com/39392449/162567732-63453b69-086d-4711-85b3-fde29eb6ce37.png)

**Comment by JoshWho** [comment]
![74971bef-599c-4a19-bae6-c0f6df278d89](https://user-images.githubusercontent.com/39392449/162567832-ba1c85f9-abe2-406f-b41f-85563df8b363.png)

**Comment by DanielnetoDotCom** [comment]
Please update again, I guess has something to do with this 

https://github.com/WWBN/AVideo/issues/6473

**Comment by JoshWho** [comment]
Looks good now Thank you @DanielnetoDotCom
