### ISSUE TITLE
Blank category page, encoding error

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6478]
@DanielnetoDotCom ,

When I click on my categories, any category, 

on ms edge: blank page. but when I open console, I get the following error (screenshot)
![ms-category-error](https://user-images.githubusercontent.com/65451390/162585887-8885bc67-4554-462c-9c35-1373d093faba.PNG)

on firefox: i get this error (see screenshot)
![ff-category-error](https://user-images.githubusercontent.com/65451390/162585967-81e60f55-60c5-4937-89e3-4177605e9c46.PNG)

only happens when i click categories.

Any solution? Thank you.

**Comment by DanielnetoDotCom** [comment]
Please share the exact link to this error

**Comment by jengajenga** [comment]
I've shared the links via email. We can continue with this thread after you have seen them.

**Comment by DanielnetoDotCom** [comment]
Hi, are you running the latest git pull?

if persists can you please add this to your videos/configuration.php file?

`$global['ob_start_callback'] = false;`

**Comment by jengajenga** [comment]
I've added it. Let's see how it works.

**Comment by DanielnetoDotCom** [comment]
FYI: even the $global['ob_start_callback'] = false; requires the git pull

**Comment by jengajenga** [comment]
ok let me do it. one sec...

**Comment by jengajenga** [comment]
git pull and git fetch say that I am already up to date

**Comment by jengajenga** [comment]
Fetching origin
Updating files: 100% (39151/39151), done.
HEAD is now at 50f3b67b9 https://github.com/WWBN/AVideo/issues/6473#issuecomment-1093769513
root@foldername: /path/to/files#

Thats what i get whe i use the hard reset

**Comment by DanielnetoDotCom** [comment]
it seems to be good. 

so test the page, if persists change the configuration.php file

**Comment by jengajenga** [comment]
just done the git pull. it is displaying now on the front page. thank you.
 don't fiddle with it :-)

**Comment by DanielnetoDotCom** [comment]
Hi

I just found this but in PHP https://github.com/php/php-src/issues/7953

this seems to be the cause of the blank page.
I just made some changes on the script to try to work around it.
