### ISSUE TITLE
Stream Key

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#6482]
Is there a way to manually write in the stream key or keep the same stream key. Every time I reboot the server. the key changes which changes my embedd code

**Comment by DanielnetoDotCom** [comment]
Hi

the stream key does not suppose to change.

the stream key only changes if you request it by clicking on reset key.

**Comment by Lordblanca** [comment]
Just so you don't think I forgot about this. Putting together images and or video for you to see what happens. I can't use embedd because the key changes every time I reboot the server
