### ISSUE TITLE
Login password displayed URL

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6484]
Hi Daniel,

I verified that when I do a login, if this login is not completed, the password is displayed in the URL bar of the Browser. 
Is this correct?

`https://cnetv.com.br/user?redirectUri=&inputPassword=***********&captcha=`

**Comment by DanielnetoDotCom** [comment]
definitely no

where did you see that?

how do I reproduce?

**Comment by DanielnetoDotCom** [comment]
this is probably something on your internet provider.

our request uses POST method and the URL you show uses GET method
