### ISSUE TITLE
Can i get white labelled App for A video for play store and app store?

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#6485]
Can i get white labelled App for A video for play store and app store?

**Comment by DanielnetoDotCom** [comment]
Yes, you can purchase your ow with your icon and URL built-in here https://youphp.tube/marketplace/

or you can download the demo app (no expiration), that works just like the white label one and you can add your site URL and you test it before purchase

download the demo app here https://youphp.tube/mobile/
