### ISSUE TITLE
Quota Plugin enhancement request

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6486]
As I understand this plugin is will stop all embeds and videos of a user that his quota has been reached. We would like the option to allow the user's already uploaded content and the embed urls to continue working but only block all other means of uploading data, meaning, uploads, live stream recordings, video url imports etc...

I know that this plugin is meant to work on a basis of a user viewing content, however we would like the option to also work on a storage based model as well. I don't see any point in blocking a user's embed links to content they already uploaded, unless the model is storage based and the hire their space on a monthly basis.

Our current community that access our content are viewing it freely, only our streamers are actually currently donating but we want to start using AVideo monitization / wallet and charge users for certain services, mainly using the capabilities of the platform. I hope you would take this into consideration on add another way or more to work with the system, I believe felexibility will allow for a broader range of users.

**Comment by DanielnetoDotCom** [comment]
do you mean, if they exceed quota they just cannot upload videos anymore, but they will be able to embed links?
