### ISSUE TITLE
Notification notification notification! This issue really needs re-examination.

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6488]
As we speak, @DanielnetoDotCom , i have only 2 notifications in my notification bar. Those are from livelinks and not people streaming.

1. Streamer is on. I can stream perfectly.
2. Socket connects when it feels like - sometimes On sometimes Off
3. Even when it's on, it doesn't show any notifications
4. I have even done a hard reset this morning, latest git 11.7. This is after updating over the weekend
5. Socket shows a huge number of users which I am sure are not there (currently 350 but it has at one point reached 700) and it keeps climbing - right now 382. Now over 400. (see screenshot)
![total_online_users](https://user-images.githubusercontent.com/65451390/162711006-7f103faf-92e1-455e-a4e1-24b56e525e63.jpeg)

6. Unknown users in socket looks like this (see screenshot)
![unknown_user_socket](https://user-images.githubusercontent.com/65451390/162710730-1eb6766d-f132-4c62-b51a-60f279022f67.jpeg)

7. As i was typing this, the socket disconnected.

8. Error log says this
::ERROR: Could not connect: Connection to tls://www.mysite.com:7065 failed: Last error for IPv4: Connection to tcp://my_public_ip:7065 failed: Connection refused (ECONNREFUSED). Previous error for IPv6: DNS query for www.mysite.com (AAAA) did not return a valid answer (NOERROR / NODATA) wss://www.mysite.com:7065?webSocketToken=djBq 
However my port is open

9. Another error says:
:DEBUG: getStart language: got from config  SCRIPT_NAME: /plugin/LiveUsers/view/beat.json.php

**Comment by DanielnetoDotCom** [comment]
you are saying it is saying 300+ users and you do not have this audience?

the socket does not lie, if shows 300+ Users you do have this amount connected to it. maybe you have bots connected

**Comment by jengajenga** [comment]
1. If this is an issue of bots, how does one block the bots? is there a botlist?

2.  What about the perpetual disappearance of notifications and livestreams on the front page? I sent my domain url via email. Click and see what I mean.

**Comment by DanielnetoDotCom** [comment]
1. add this in your configuration.php
`$global['stopBotsList'] = array('bot','spider','rouwler','Nuclei','MegaIndex','NetSystemsResearch','CensysInspect','slurp','crawler','curl','fetch','loader');`

2. I am not sure exactly what notification do you want to hide. if you mean the top menu notification you may have some option on the live plugin, or you can use CSS to hide the element.

**Comment by jengajenga** [comment]
I've just added it. Let me see monitor and see how it goes.

About the notification, sometimes it is not there and i don't get the live  displays on the front page. but we'll figure it out later. 

for now let me monitor the bots. i will let you know. i'll keep this open until tomorrow.
