### ISSUE TITLE
Live Schedule not configurable for suscribes

### ISSUE THREAD

**Issue by consultingforge** [WWBN/AVideo#6489]
When a live stream is created from the "Live" button configuration works fine and only suscribers can access to the live.

BUT

If you generate a "Scheduled live stream" there is no option to configure the stream details like on Live and all streams configured from "Scheduled" are open to see by anyone even not registered on platform.

**Comment by DanielnetoDotCom** [comment]
I am pretty sure the schedule will use the default live configuration

**Comment by consultingforge** [comment]
is that default config stored in database?

**Comment by DanielnetoDotCom** [comment]
It is stored on the database, but I mean the default live configuration. What is set up per user

**Comment by consultingforge** [comment]
then i assume that same user account used in different devices uses same configuration. If that the case we will review in next live stream to confirm but it looks like scheduled is not correctly getting that default config.

**Comment by DanielnetoDotCom** [comment]
Ok

**Comment by DanielnetoDotCom** [comment]
If you mean the user group, please try the latest git pull.

the schedule may use the default live permission

**Comment by consultingforge** [comment]
Solved!
