### ISSUE TITLE
Live Servers is Disabled, if you want to use it, enable it on the (Live) Plugin 

### ISSUE THREAD

**Issue by wakozuka** [WWBN/AVideo#6491]
i get the above error when trying to start live stream

**Comment by DanielnetoDotCom** [comment]
it is only if you are using an external live server, which I suspect you do not suppose to.

the default installation the live server is on the same server as the streamer. so you are not supposed to enable it

**Comment by wakozuka** [comment]
Daniel you have been a great help but for sure now i can say I don't know what am doing. i have the server running 154.0.153.9 but i can't and don't figure out how to now stream from OBS and go live on the server. I've tried along the way to create a separate server to run RTMP service and its working fine since i tested it with VLC and i had a stream, again trying to push the stream to my Avideo server is where i failed again.   Sorry for disturbing you this much but am doing all i can to work on a project that will allow churches to stream their service and events to this site am creating, with youtube and other streaming services are worse here they have lots of brake ups. i need to create a local server for my region.

**Comment by DanielnetoDotCom** [comment]
If works on VLC and does not work on your website, I suspect you do not have SSL properly installed
