### ISSUE TITLE
A question regarding the PushRTMP

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6492]
Although I closed a post about live notifications being disappearing from front page, that issue continued to happen, however, we decided to try and activate the PushRTMP checkbox and for some reason now everything is working smoothly again.

My question is, what is this option for and should I used it? because it did solve our issue but I am not sure why. Until today that option was off and still we had very good experience as long as there were no bug due to updates.

This is the option I am referring to:
![photo_2022-04-12 18 49 48](https://user-images.githubusercontent.com/58882903/163003641-d88c8b4c-d314-41e5-a5aa-b57be584a209.jpeg)

**Comment by DanielnetoDotCom** [comment]
PushRTMP is for the webrtc only, and the webrtc is still under development. so this option is useless for you

**Comment by guymass** [comment]
OK thanks.
