### ISSUE TITLE
Live streaming issue

### ISSUE THREAD

**Issue by tbprince** [WWBN/AVideo#6493]
Hello,

we have configured LivePlugin and enabled it. When when setup a live streaming we use OBS to test the streaming we can configure OBS to actually push the contents to the server. We can actually see the stream being reported and accepted by the server and we can also see the stream being reported inside

https://[domain-name]:8443/stat

with its size, bandwidth and so on.

However, streaming never goes online. URL where the player is displayed shows "offline" mark while OBS is actually transmitting data. 

Live streams are configured to use the local server at this time, no external servers.

What can be wrong?

Thanks.

**Comment by DanielnetoDotCom** [comment]
the YPTSocket plugin is required for the notifications

https://github.com/WWBN/AVideo/wiki/Socket-Plugin

**Comment by tbprince** [comment]
Hello,

Web socket had already been configured.

![image](https://user-images.githubusercontent.com/15170491/163460376-c3e8c2a0-99b8-4194-9443-0a080003ee7e.png)

Could you please provide the instructions to install a new live streaming server separated from the frontend?

Thanks.

**Comment by DanielnetoDotCom** [comment]
Check your avideo.log when you start a live stream 

also make sure your status page is working
