### ISSUE TITLE
New installation, old users, no stream key

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6495]
@DanielnetoDotCom , I did a reinstallation of the platform.

Now my older users do not have stream key's. They're blank. (see screenshot)

![no-stream-key](https://user-images.githubusercontent.com/65451390/163190876-419475e3-e472-4ecf-a734-e1728d60a20b.PNG)

How to fix it? Urgent. Thanks.

**Comment by DanielnetoDotCom** [comment]
strange, this should not happen

can you please check the avideo.log?

also check if there is any plugin update or missing a plugin database installation

**Comment by jengajenga** [comment]
> strange, this should not happen
> 
> can you please check the avideo.log?
> 
> also check if there is any plugin update or missing a plugin database installation

all plugins are updated and the tables installed.

log says this but this is from 

AVideoLog::DEBUG: login.json.php trying to login SCRIPT_NAME: /objects/login.json.php
AVideoLog::DEBUG: Password check new hash user not found SCRIPT_NAME: /objects/login.json.php
AVideoLog::DEBUG: login.json.php login respond something SCRIPT_NAME: /objects/login.json.php
AVideoLog::DEBUG: Password check new hash user not found SCRIPT_NAME: /objects/login.json.php
AVideoLog::DEBUG: Password check new hash user not found SCRIPT_NAME: /objects/login.json.php
AVideoLog::DEBUG: loginFromRequest NOT FOUND this_user@gmail.com SCRIPT_NAME: /objects/login.json.php
AVideoLog::DEBUG: login.json.php is not logged SCRIPT_NAME: /objects/login.json.php
AVideoLog::DEBUG: login.json.php is done SCRIPT_NAME: /objects/login.json.php

Also the socket and mysql are taking a lot of cpu resources

**Comment by DanielnetoDotCom** [comment]
I can only see the error


 `AVideoLog::ERROR: Could not connect: Connection to tls://my.domain:7168 failed: Last error for IPv4: Connection to tcp://202.61.239.86:7168 failed: Connection refused (ECONNREFUSED). Previous error for IPv6: DNS query for my.domain (AAAA) did not return a valid answer (NOERROR / NODATA)`

I do not know where it come from

sorry there is no clue on this log

You should try to access the live page where the key suppose to appear and then share the log

**Comment by DanielnetoDotCom** [comment]
That is better and now your error makes more sense 

`AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: preg_match(): Argument https://github.com/WWBN/AVideo/issues/2 ($subject) must be of type string, stdClass given`

I am away from pc now but you can check if you do not have any missing plugin update 

I may be able to give a better check only tomorrow

**Comment by DanielnetoDotCom** [comment]
I just sent an update 

it may not resolve the problem but at least will not crashes and I will see more details about the error

**Comment by jengajenga** [comment]
I've done the update. Stream key is still missing.

**Comment by DanielnetoDotCom** [comment]
But check the logs, this update may give us more clues
