### ISSUE TITLE
Cannot Update Categories

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#6496]
Hi 

I updated categories in the admin page but its not showing up on the website. I am admin

I also noticed this in the Log files:-
 [13-Apr-2022 18:25:33 Europe/London] AVideoLog::ERROR: Live::getStatsObject RTMP Server (https://kollossus.com:8443/stat) is OFFLINE, timeout=(4) we could not connect on it => live_servers_id = (0)  SCRIPT_NAME: /view/user.php

What does this mean ?

Thanks

**Comment by DanielnetoDotCom** [comment]
As I can see your live server is offline

https://kollossus.com:8443/stat

try to start nginx `/usr/local/nginx/sbin/nginx `

**Comment by kollossus55** [comment]
hi 

Yes i restarted it, but it says there's an error in the file:-

Apr 18 13:38:46 kollossus.com nginx[1030]: nginx: [emerg] unknown directive "rtmp" in /etc/nginx/nginx.conf:7
Apr 18 13:38:46 kollossus.com nginx[1030]: nginx: configuration file /etc/nginx/nginx.conf test failed
Apr 18 13:38:46 kollossus.com systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Apr 18 13:38:46 kollossus.com systemd[1]: nginx.service: Failed with result 'exit-code'.
Apr 18 13:38:46 kollossus.com systemd[1]: Failed to start A high performance web server and a reverse proxy server.

what do I need to do ?
would I need to install files again ?

Regards

**Comment by DanielnetoDotCom** [comment]
that means your Nginx is not properly installed or you are not starting Nginx properly (like I describe [above](https://github.com/WWBN/AVideo/issues/6496#issuecomment-1098605625))

If you are not sure how to install Nginx + RTMP, please ask for help on their repository 

https://github.com/arut/nginx-rtmp-module

**Comment by kollossus55** [comment]
Hi

Was that not part of the re-install you performed last week?

If not then I will follow the instructions..

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DanielnetoDotCom** [comment]
It supposes to be installed.

Again, I guess you are starting nginx wrong

but I just checked your server again https://kollossus.com:8443/stat

and it seems to be working good now

**Comment by kollossus55** [comment]
Just done the following command:-

sudo service nginx status
* nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-04-18 13:38:46 BST; 2h 49min ago
       Docs: man:nginx(8)

Apr 18 13:38:45 kollossus.com systemd[1]: Starting A high performance web server and a reverse proxy server...
Apr 18 13:38:46 kollossus.com nginx[1030]: nginx: [emerg] unknown directive "rtmp" in /etc/nginx/nginx.conf:7
Apr 18 13:38:46 kollossus.com nginx[1030]: nginx: configuration file /etc/nginx/nginx.conf test failed
Apr 18 13:38:46 kollossus.com systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Apr 18 13:38:46 kollossus.com systemd[1]: nginx.service: Failed with result 'exit-code'.
Apr 18 13:38:46 kollossus.com systemd[1]: Failed to start A high performance web server and a reverse proxy server.

please advise if best to re-install nginx



________________________________

**Comment by DanielnetoDotCom** [comment]
Please read what I told you to do [above](https://github.com/WWBN/AVideo/issues/6496#issuecomment-1098605625).

`sudo service nginx ...` **is NOT the correct command to start Nginx**. 

this is may be conflicting with the compiled Nginx on the folder `/usr/local/nginx/`

**Comment by kollossus55** [comment]
Hi

Thanks for that.

I seem to have a problem with nginx. what does the below mean ?

* nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset:>
     Active: failed (Result: exit-code) since Thu 2022-04-14 13:19:33 BST; 5h 5>
       Docs: man:nginx(8)

Apr 14 13:19:33 kollossus.com systemd[1]: Starting A high performance web serve>
Apr 14 13:19:33 kollossus.com nginx[1081]: nginx: [emerg] unknown directive "rt>
Apr 14 13:19:33 kollossus.com nginx[1081]: nginx: configuration file /etc/nginx>
Apr 14 13:19:33 kollossus.com systemd[1]: nginx.service: Control process exited>
Apr 14 13:19:33 kollossus.com systemd[1]: nginx.service: Failed with result 'ex>
Apr 14 13:19:33 kollossus.com systemd[1]: Failed to start A high performance we
________________________________

**Comment by DanielnetoDotCom** [comment]
try to start with 

`sudo /usr/local/nginx/sbin/nginx`
