### ISSUE TITLE
A DB query plugins or via API? What's the best way?

### ISSUE THREAD

**Issue by elico** [WWBN/AVideo#6498]
OK so I have a system which I embed videos in from youtube.
It's kind of a whitelist/collection of videos from youtube that I like.
I wrote a system that updates the DB with everything that is needed daily ie connects to youtube and updates the DB with the most recent videos on a list of channels.
To find out if a specific video is already in the DB for external queries I wrote the next piece of code:
https://gist.github.com/elico/a3b5aa855d94d52ca92da7014cac9e85

which sits in: find-by-vid/find.php

The first issue I have seen was that it's not possible to open a video only with it's ID, the AVideo system requires you to also have the name. I would have expected that a http://site.domain.com/video/id would open the video page.
Instead I need to use the next workaround: http://site.domain.com/view/?v=id
(I believe it can be changed in the .htaccess with a single line.)
`RewriteRule    ^video/([0-9]+)/?$ view/?v=$1    [QSA]`

The reason I wrote the code of find.php was since it's the most simple code which runs faster then loading the whole plugins wrappers.

@DanielnetoDotCom 

What do you think about it?
Also, what is the complexity of adding a videos.videoLink based view? ( I am not too familiar with AVideo code yet but it seems pretty simple to dig in)

Thanks,
Eliezer

**Comment by DanielnetoDotCom** [comment]
Hi, 

you may be able to open the video with http://site.domain.com/v/id/

**Comment by elico** [comment]
Added a fix at #6500

**Comment by DanielnetoDotCom** [comment]
thanks, approved
