### ISSUE TITLE
Unexpected error 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#6502]
I can't duplicate this error but it came up for a few of my viewers.

Fakeotube.com

`string(22) "ERROR on output buffer" int(1) string(69) "/var/www/html/YouPHPTube/plugin/ReportVideo/actionButtonBlockUser.php" array(1) { ["users_id"]=> int(1) }

string(22) "ERROR on output buffer" int(1) string(69) "/var/www/html/YouPHPTube/plugin/ReportVideo/actionButtonBlockUser.php" array(1) { ["users_id"]=> int(1) }`

**Comment by DanielnetoDotCom** [comment]
Please make a git pull and test again 

this error is already removed
