### ISSUE TITLE
After latest git pull i can not watch newest encoded live video

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6503]
@DanielnetoDotCom 
Here is the result I am getting on tonight's broadcast that was sent to encoder.
https://mhktube.com/v/199

Both the encoder and site are up to date

**Comment by milehighkaraoke** [comment]
Here are latest errors
![Screenshot_20220414-211620_Samsung Internet](https://user-images.githubusercontent.com/70327833/163512774-a43ca0ac-f402-4b4a-a8fa-b33bbf393af7.jpg)
![Screenshot_20220414-211628_Samsung Internet](https://user-images.githubusercontent.com/70327833/163512778-c7ae287d-c214-44ed-90c8-8e5df0acacb6.jpg)
![Screenshot_20220414-211634_Samsung Internet](https://user-images.githubusercontent.com/70327833/163512779-8ec5fa98-4754-4a19-a99f-a7cf934a231b.jpg)
![Screenshot_20220414-211644_Samsung Internet](https://user-images.githubusercontent.com/70327833/163512782-7277e232-c2d1-4c7b-a6cc-2473ca29ee7a.jpg)
![Screenshot_20220414-211651_Samsung Internet](https://user-images.githubusercontent.com/70327833/163512786-9945024b-5f67-4ee6-931d-e92e87870f83.jpg)

**Comment by DanielnetoDotCom** [comment]
Check this 

https://github.com/WWBN/AVideo/issues/6389#issuecomment-1068284923

**Comment by milehighkaraoke** [comment]
Is there a typo in mine?

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DanielnetoDotCom** [comment]
was a typo in an old update.

the fix must be done directly into the database

this command should do the trick

`sudo mysql -u root -e  "ALTER TABLE live_transmitions_history RENAME COLUMN users_id_companny TO users_id_company;"`

**Comment by milehighkaraoke** [comment]
![16500232308425427214736463713137](https://user-images.githubusercontent.com/70327833/163567192-f523d8ac-c51b-4a95-bf00-49c1dce17248.jpg)

**Comment by milehighkaraoke** [comment]
Where do I enter my database name in this command

**Comment by DanielnetoDotCom** [comment]
Check that I did update the SQL code 

> 
> `sudo mysql -u root -e "USE [yourAvideoDatabase]; ALTER TABLE live_transmitions_history RENAME COLUMN users_id_companny TO users_id_company;"`
> 
> replace [yourAvideoDatabase] with your database name, you can find it on the videos/configuration.php file

**Comment by milehighkaraoke** [comment]
Do I need to do this to both site and encoder database?

**Comment by milehighkaraoke** [comment]
OK, i did this command with success but the video that encoded last night still does not play.
https://mhktube.com/v/200

**Comment by DanielnetoDotCom** [comment]
Try to submit a new video and see if the error persists. if you had an error like this on the last encode process, your video is probably lost.

make sure you make a git pull on your encoder as well

**Comment by milehighkaraoke** [comment]
Git pull is complete on both the site and encoder but I still have the same issue here is a resubmitted video
https://mhktube.com/v/203
Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by milehighkaraoke** [comment]
![20220415_133448](https://user-images.githubusercontent.com/70327833/163624449-262c91cb-acb9-4849-bf38-772f0b75ac89.jpg)
![20220415_133434](https://user-images.githubusercontent.com/70327833/163624462-09a8cb1d-d274-4ada-9e7b-52998fe41b23.jpg)

**Comment by DanielnetoDotCom** [comment]
If those are new errors you did not made the database update properly 

make sure you do it correctly https://github.com/WWBN/AVideo/issues/6503#issuecomment-1100063400

**Comment by milehighkaraoke** [comment]
![20220415_153804](https://user-images.githubusercontent.com/70327833/163635269-5c32bc87-aefe-431b-bcc0-b709ffbd59d0.jpg)

**Comment by DanielnetoDotCom** [comment]
That means those errors are old

try to delete the log file and try to submit a new video than share the log file

**Comment by milehighkaraoke** [comment]
nothing in log and newest submitted video is not working

https://mhktube.com/v/206

**Comment by DanielnetoDotCom** [comment]
Must be something on the log, check apache, encoder and streamer logs

if you do not share the logs I cannot help you

**Comment by milehighkaraoke** [comment]
Errors it generated from last night hopefully something here
![Screenshot_20220416-070845_Samsung Internet](https://user-images.githubusercontent.com/70327833/163676223-59b5117a-2ed4-4bb8-958a-77983893a6bc.jpg)
![Screenshot_20220416-070852_Samsung Internet](https://user-images.githubusercontent.com/70327833/163676227-f73fec24-76ca-4638-80dd-fc501f8e16a7.jpg)
![Screenshot_20220416-070905_Samsung Internet](https://user-images.githubusercontent.com/70327833/163676230-5fe0049a-4ec0-4a3d-8717-0eb41b82928c.jpg)

**Comment by DanielnetoDotCom** [comment]
If you delete the logs and this error appears again, I suspect you did not update the correct database

double-check your database name. also clear the cache and restart MySQL to make sure

**Comment by milehighkaraoke** [comment]
![Screenshot_20220416-071927_Outlook](https://user-images.githubusercontent.com/70327833/163676494-3f41c951-b79d-42a8-8b59-17f7e96d8d3b.jpg)

**Comment by milehighkaraoke** [comment]
What am I missing?

**Comment by milehighkaraoke** [comment]
Do I need to update the encoder database also?

**Comment by DanielnetoDotCom** [comment]
Do not need to update the encoder database.

check your videos/configuration.php for your database name.

**Comment by milehighkaraoke** [comment]
Checked videos/configuration php  it is MHKTube
I need to know what I need to do to fix this.

**Comment by DanielnetoDotCom** [comment]
so this does not make any sense

is your database on the same server as your streamer site?

again, I recommend you delete your log and let the script create a new one.

**Comment by milehighkaraoke** [comment]
I did delete log last night like you ask me to. This is what it generates after deleting log and trying to live stream to encoder

**Comment by milehighkaraoke** [comment]
@
![20220416_072804](https://user-images.githubusercontent.com/70327833/163676943-c5f17780-126b-40d4-9da3-7bb1b145878c.jpg)

**Comment by milehighkaraoke** [comment]
Database is on same server

**Comment by milehighkaraoke** [comment]
This all worked perfectly till the last gitpull

**Comment by DanielnetoDotCom** [comment]
try to reboot your server, the errors do not make sense since you have already updated the database.

**Comment by milehighkaraoke** [comment]
Nothing worked  .. I reinstalled a fresh site and now I can not get the rtmp module from git.... I made new issue...

**Comment by DanielnetoDotCom** [comment]
If you have issues installing the Nginx RTMP you should open an issue on their repository 

https://github.com/arut/nginx-rtmp-module
