### ISSUE TITLE
Zip archives display entire contents, which is confusing for the user.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6504]
**Describe the bug**
I have a zip archive with >700 files. It displays each filename, and confuses users greatly. Users are trying to click on individual files thinking they should download. They don't scroll down 15-20 pages to find the download link.

**To Reproduce**
1. Go to https://conspyre.tv/video/9176/collection-of-10-000-messages-from-hunter-biden-s-laptop
2. Observe

**Expected behavior**
1. To put a scrolling frame around the long list   
or
2. To truncate to a reasonable size
or
3. Each individual file to be a clickable downloadable link to retrieve a single file from the archive 

Probably 1 is best.

**Screenshots**
![Screen Shot 2022-04-14 at 10 04 00 PM](https://user-images.githubusercontent.com/11711050/163523401-04762576-1337-488d-be98-b347dd35c141.png)

**Comment by DanielnetoDotCom** [comment]
The download idea is a good idea, but that is not how the zip was implemented.

**Comment by walt93** [comment]
Understood, that would be a bunch of additional effort. Just looking for #1 above. Possible to wrap the file list in a scroller so the users are able to find the download link?

Checking the download count, and checking the comments from users, a lot of people aren't figuring this page out.
