### ISSUE TITLE
cant get stream to show on page

### ISSUE THREAD

**Issue by wakozuka** [WWBN/AVideo#6507]
this time around after a new clean installation, everything is running perfectly i can upload videos, but i can not llive stream, i get the OBS connected to my server but nothing happens, i [have]) the following errors in the picture. all services are running in one server.
![capture](https://user-images.githubusercontent.com/28747650/163587436-ff20c8d7-0ec1-45f4-b42f-40232a8b29d3.PNG)
![Capture1](https://user-images.githubusercontent.com/28747650/163587441-0a11f2b2-1891-4749-af54-06ce64c0ebc0.PNG)

**Comment by DanielnetoDotCom** [comment]
Seems to me your nginx is not properly installed or it is not running

**Comment by wakozuka** [comment]
i have  it running well, just dont get it still with the errors
![Capture3](https://user-images.githubusercontent.com/28747650/163685451-3158362c-b717-4459-be97-11bf0fd01f78.PNG)
![capture](https://user-images.githubusercontent.com/28747650/163685452-95721a70-eddc-4540-890e-c0d5c6a2eb9b.PNG)
![Capture1](https://user-images.githubusercontent.com/28747650/163685456-9b1b56f3-b2de-4854-a8c9-07a0f95f59b0.PNG)
![Capture2](https://user-images.githubusercontent.com/28747650/163685458-133a46c7-3060-4deb-8a8c-1610eea8a0ce.PNG)

**Comment by DanielnetoDotCom** [comment]
This is not the correct way to start nginx 

seems to me you did not compile nginx with RTMP 

check this https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

**Comment by wakozuka** [comment]
i did please check the first picture

**Comment by DanielnetoDotCom** [comment]
I can see your nginx ssl is not properly configured 

min your case it should be on port 444

**Comment by wakozuka** [comment]
ludovick@live:~$ sudo cat /usr/local/nginx/conf/nginx.conf
user    www-data;
worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    buflen 1000ms;
                    chunk_size 4096;
                    ping_timeout 30s;
                    ### Use case option (max_streams; default is 32 )
                    #max_streams 10;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            hls_playlist_length 60m;
                            hls_fragment 4s;
                            drop_idle_publisher 30s;
                            sync 500ms;
                            #Experimental. Force dropped stream, or ended stream from being watched. (idle_streams)
                            #idle_streams off;
                            on_publish http://live.techwondo.org/plugin/Live/on_publish.php;
                            on_publish_done http://localhost/AVideo/plugin/Live/on_publish_done.php;
                            on_play http://live.techwondo.org/plugin/Live/on_play.php;
                            on_record_done http://live.techwondo.org/plugin/Live/on_record_done.php;

                            #exec ffmpeg -re -i rtmp://localhost/live/$name -c:v libx264 -preset veryfast -c:a copy -f hls -hls_time 5 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi;
                            #exec ffmpeg -re -i rtmp://localhost/live/$name
                            #    -c:v libx264 -vf scale=-2:240 -r 20 -g 40 -keyint_min 40 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1400k -c:a aac -strict -2 -b:a 96k -f flv rtmp://localhost/adaptive/$name_low
                            #    -c:v libx264 -vf scale=-2:480 -r 30 -g 60 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 4200k -c:a aac -strict -2 -b:a 128k -f flv rtmp://localhost/adaptive/$name_mid
                            #    -c:v libx264 -vf scale=-2:720 -r 30 -g 60 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 3000k -bufsize 6000k -c:a aac -strict -2 -b:a 128k -f flv rtmp://localhost/adaptive/$name_hi;


                            #recorder video {
                            #    record all manual;
                            #    record_path /var/www/tmp;
                            #    record_notify on;
                            #    record_max_size 2048M;
                            #    record_suffix -%d-%b-%y-%T.flv;
                            ###If live-stream is over 30FPS and you want to limit it to 30FPS recording to light the encoding task #record_max_frames 30;
                            #    ## record_max_frames 30;
                            #}

                            ### Record Audio Separately ( For podcast )
                            #recorder audio {
                            #    record audio;
                            #    record_path /var/www/tmp;
                            #    record_max_size 1024M;
                            #    record_suffix -%d-%b-%y-%T.mp3;
                            #}
                    }

                    #application adaptive {
                    #    live on;
                    #    hls on;

                    #    hls_path /HLS/live;
                    #    hls_nested on;
                    #    hls_playlist_length 10m;
                    #    allow play all;
                    #    allow publish 127.0.0.1;
                    #    deny publish all;

                    #    hls_variant _hi BANDWIDTH=264000,RESOLUTION=1280x720; # this is for line 34 only, do not uncomment it
                    #    hls_variant _low BANDWIDTH=900000;
                    #    hls_variant _mid BANDWIDTH=2400000;
                    #    hls_variant _hi  BANDWIDTH=3500000;
                    #}
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    #listen 8443 ssl;
                    listen 444 ssl;

                        ssl_certificate /etc/letsencrypt/live/live.techwondo.org/fullchain.pem;

                        ssl_certificate_key /etc/letsencrypt/live/live.techwondo.org/privkey.pem;

                        server_name live.techwondo.org;
                    #listen [::]:8443 ssl;
                    #include /usr/local/nginx/snippets/self-signed.conf;
                    #include /usr/local/nginx/snippets/ssl-params.conf;
                    listen 8080;
                    server_name localhost;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            expires 60;
                            add_header 'Cache-Control' 'public';

                            location ~ \.m3u8$ {
                                expires -1;
                                # Disable cache
                                add_header 'Cache-Control' 'no-cache';

                                # CORS setup
                                add_header 'Access-Control-Allow-Origin' '*' always;
                                add_header 'Access-Control-Expose-Headers' 'Content-Length';
                            }

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            # replace this with the IP of your AVideo site
                            allow 127.0.0.1;
                            deny all;
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }

                    #location ~ \.php$ {
                    #       include /etc/nginx/snippets/fastcgi-php.conf;
                    #       fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
                    #}

            }
    }

**Comment by wakozuka** [comment]
please advice the above

**Comment by DanielnetoDotCom** [comment]
the conf file does not mean it is installed

if you are not sure how to install it you should open an issue on the Nginx RTMP page

https://github.com/arut/nginx-rtmp-module

**Comment by Lordblanca** [comment]
Make sure that your live plug in is correct and that it is pointing to your certs
![image](https://user-images.githubusercontent.com/37937968/164712105-24702575-c810-47cb-8edb-7fa516067a20.png)
