### ISSUE TITLE
SendRecordedToEncoder not working

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#6512]
OBS connects, live stream shows up on AVideo, chat up and running, all good. End live and NADA, no VOD recording of live. Attached are logs, screens:

[Apache2error.log](https://github.com/WWBN/AVideo/files/8506546/Apache2error.log)
[avideo.log](https://github.com/WWBN/AVideo/files/8506547/avideo.log)
[nginx_error.log](https://github.com/WWBN/AVideo/files/8506548/nginx_error.log)
[HLS-live-var-www-tmp.txt](https://github.com/WWBN/AVideo/files/8506551/HLS-live-var-www-tmp.txt)
[nginx.conf.txt](https://github.com/WWBN/AVideo/files/8506563/nginx.conf.txt)
[rtmp.conf.txt](https://github.com/WWBN/AVideo/files/8506565/rtmp.conf.txt)
[http.conf.txt](https://github.com/WWBN/AVideo/files/8506566/http.conf.txt)
![Live](https://user-images.githubusercontent.com/85363361/163831473-bfdc536d-70a9-4c92-98d0-4219a0cb6e54.jpg)
![SendRecordedToEncoder](https://user-images.githubusercontent.com/85363361/163831495-764c2f69-98f3-48d0-bb51-05ea0da1c416.jpg)
![Stat](https://user-images.githubusercontent.com/85363361/163831524-8bd8c8f1-697a-4e2c-b7b0-29472eda1fc2.jpg)

**Comment by DanielnetoDotCom** [comment]
Is the streamer and nginx live server on the same server?

Can you please check if you have files inside this directory? `/var/www/tmp/`

also check the permissions: `chmod -R 777 /var/www/tmp/`

**Comment by DanielnetoDotCom** [comment]
Also please remove this line from the recorder block

`record_max_frames 30;`

**Comment by GreenDragonTavern** [comment]
<< Is the streamer and nginx live server on the same server? >> Yes
<< Can you please check if you have files inside this directory? /var/www/tmp/ >> Attached SSH session showing files in both /var/www/tmp and /HLS/live/userkeydir

<< Also please remove this line from the recorder block >> Will do right now and update you.

**Comment by DanielnetoDotCom** [comment]
The attached  SSH session did not come

**Comment by GreenDragonTavern** [comment]
xxxxxxxx@x:~$ sudo dir /HLS/live/625cbd072d476-1
[sudo] password for xxxxxxxxxxxxxxxxxxxxxxx:
0.ts   11.ts  13.ts  15.ts  17.ts  19.ts  20.ts  22.ts  24.ts  26.ts  28.ts  2.ts   31.ts  33.ts  4.ts  6.ts  8.ts  index.m3u8
10.ts  12.ts  14.ts  16.ts  18.ts  1.ts   21.ts  23.ts  25.ts  27.ts  29.ts  30.ts  32.ts  3.ts   5.ts  7.ts  9.ts
xxxxxxxx@x:~$

xxxxxxxx@x:~$ sudo dir /var/www/tmp
625cbd072d476-1-18-Apr-22-14:21:38.flv  625cbd072d476-1-18-Apr-22-14:23:10.flv  625cbd072d476-1-18-Apr-22-14:24:50.flv
625cbd072d476-1-18-Apr-22-14:21:43.flv  625cbd072d476-1-18-Apr-22-14:23:18.flv  625cbd072d476-1-18-Apr-22-14:24:58.flv
625cbd072d476-1-18-Apr-22-14:21:46.flv  625cbd072d476-1-18-Apr-22-14:23:27.flv  625cbd072d476-1-18-Apr-22-14:25:07.flv
625cbd072d476-1-18-Apr-22-14:21:55.flv  625cbd072d476-1-18-Apr-22-14:23:35.flv  625cbd072d476-1-18-Apr-22-14:25:15.flv
625cbd072d476-1-18-Apr-22-14:22:03.flv  625cbd072d476-1-18-Apr-22-14:23:43.flv  625cbd072d476-1-18-Apr-22-14:25:23.flv
625cbd072d476-1-18-Apr-22-14:22:11.flv  625cbd072d476-1-18-Apr-22-14:23:52.flv  625cbd072d476-1-18-Apr-22-14:25:32.flv
625cbd072d476-1-18-Apr-22-14:22:20.flv  625cbd072d476-1-18-Apr-22-14:24:00.flv  625cbd072d476-1-18-Apr-22-14:25:40.flv
625cbd072d476-1-18-Apr-22-14:22:28.flv  625cbd072d476-1-18-Apr-22-14:24:08.flv  625cbd072d476-1-18-Apr-22-14:25:48.flv
625cbd072d476-1-18-Apr-22-14:22:37.flv  625cbd072d476-1-18-Apr-22-14:24:17.flv  625cbd072d476-1-18-Apr-22-14:25:57.flv
625cbd072d476-1-18-Apr-22-14:22:45.flv  625cbd072d476-1-18-Apr-22-14:24:25.flv  625cbd072d476-1-18-Apr-22-14:26:05.flv
625cbd072d476-1-18-Apr-22-14:22:53.flv  625cbd072d476-1-18-Apr-22-14:24:33.flv  625cbd072d476-1-18-Apr-22-14:26:13.flv
625cbd072d476-1-18-Apr-22-14:23:02.flv  625cbd072d476-1-18-Apr-22-14:24:42.flv
xxxxxxxx@x:~$

**Comment by GreenDragonTavern** [comment]
#record_max_frames 30; seems to have worked. Also had to keep Apache2 port 80 open with same config as 443 less the SSL stuff. Recorded properly, thank you.

**Comment by GreenDragonTavern** [comment]
Going keep this open for a bit, want to test out of FL, CA, and NY at same time. Appreciate efforts as always, Don.

**Comment by GreenDragonTavern** [comment]
Quick question, /var/www/tmp is cleared out after record. What about /HLS/live/userkeydir? Shouldn't that also be cleaned up after live is finished?

**Comment by DanielnetoDotCom** [comment]
If the recorder is working properly /var/www/tmp is cleared out after record. 

/HLS/live/userkeydir the Nginx server will auto-clear it. we do not control when they clear

**Comment by GreenDragonTavern** [comment]
Roger that. /var/www/tmp is being cleaned up after record, so all good there, and will let nginx do its thing :-)

**Comment by GreenDragonTavern** [comment]
Daniel, have a PowerEdge R630 dual 14-Core CPU's w/128GB RAM, 10Gb pipe to world. Runs AVideo, and nginx only, talking to a remote MariaDB server. Client has about 1,000 folks who currently watch his live with another vendor. Did some testing and seems fine handling load but real world is sometimes another issue. Any thoughts on config and 1K users watching his stream?

**Comment by DanielnetoDotCom** [comment]
Hi 

for this audience I strongly recommend you to use our CDN

https://github.com/WWBN/AVideo/wiki/CDN-Plugin

For the hardware configuration please check this https://github.com/WWBN/AVideo/wiki/Speed-up-your-page

**Comment by GreenDragonTavern** [comment]
Will check it out, thanks. The CDN-Plugin, can see benefit for VOD, but live stream/users watching stream?

**Comment by DanielnetoDotCom** [comment]
Correct, it will reflect on the VOD, Live, and also static files (css, images, js, etc)

**Comment by GreenDragonTavern** [comment]
Roger that. Guess the question is, who are you using, and price? We don't want anything to do with big boy cloud services; AWS; Azure, Big Blue, Google. The alphabet agencies in D.C. funded and built those behemoths with U.S. citizen's $. We can't get around using their networks, nor having them store data without consent, but refuse to help them any further ;-)

**Comment by DanielnetoDotCom** [comment]
Hi

sorry for the late reply


> Roger that. Guess the question is, who are you using, 

Based on Bunny's infrastructure 

> and price?

Please check here https://youphp.tube/marketplace/CDN/iframeTemplate.php

**Comment by GreenDragonTavern** [comment]
Will definitely check all out. Many thanks for your stellar efforts!
