### ISSUE TITLE
DiskQuota to work with PayPal

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6513]
Currently we do not have any way to charge payment for service because Stripe doesn't work with my country. 

Is it possible to add more payment options such as paypal? as we already have that plugin setup.

**Comment by DanielnetoDotCom** [comment]
PayPal may work, but I guess it will not be automatically recurrent. 

bu the user will be able to add balance on his wallet and make the payment renew manually

**Comment by guymass** [comment]
So for reoccuring payments they will have to pay us to add balance to their wallet and then pay the quota from the wallet?

How can we add the selection option in the packages page or maybe add a PP button to each package.

Also, if they pay us to top the wallet, how do they do that? (topup the wallet) We are still trying to understand how we want to work with those plugins as our service scheme is different in essence.

**Comment by DanielnetoDotCom** [comment]
Sorry I just review the plugin and you are correct, PayPal is not available, only Stripe for now

I may add PayPal in the future

**Comment by guymass** [comment]
Well PP is important because Strip doesn't work for us here. We have no way to charge people than. Maybe just for now add a PP field where we can paste a PP button code. Could be fairly easy to add I think. 

We will be waiting.
