### ISSUE TITLE
How does the Avideo score system work?

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6515]
We want to understand the scoring system and how it works. Do users get points which later can be converted to something else? How do the get those points?

**Comment by DanielnetoDotCom** [comment]
Hi, what scores are you referring to?

**Comment by guymass** [comment]
Well I thought there was a scoring system that gives points to users who view content, so in that way users can gain points and use them to buy stuff on our site.

**Comment by DanielnetoDotCom** [comment]
Are you talking about this?

https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform#reward-per-view

**Comment by guymass** [comment]
Yes, but I thought it was doing something else. I am closing this issue for now we are still trying to figure out how to use the monitization for our site.
