### ISSUE TITLE
Ad plugin

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#6516]
Hi I uploaded ads in the plugin
  In the leaderboard middle row
And the leaderboard top as shown in the pictures

![image](https://user-images.githubusercontent.com/85537931/163951039-bce257e2-2f33-427d-8784-c872943095ed.png)

![image](https://user-images.githubusercontent.com/85537931/163951113-26605674-9227-4c38-aa43-d8586a94d9f7.png)

Pictures from the site

![image](https://user-images.githubusercontent.com/85537931/163952122-e7b1729b-6027-43a9-ae89-be77fb64d8b2.png)
![image](https://user-images.githubusercontent.com/85537931/163952184-9b3236cc-65d6-413e-b6a4-c14aaff8d1b2.png)

The ads also appear on the mobile (browser) not the app

 as shown in the pictures
 
![photo_2022-04-19_10-44-25](https://user-images.githubusercontent.com/85537931/163951951-ce886133-15ab-4bbf-a74e-6bcdc2dc6a5a.jpg)
![photo_2022-04-19_10-44-20](https://user-images.githubusercontent.com/85537931/163951956-0c726296-e279-419d-bbc1-db34788c3a22.jpg)

Which should not be as far as I understand
Is it supposed to appear there?
And if so the links do not work on mobile (browser)

Thank you very much for the reference

eitan

**Comment by DanielnetoDotCom** [comment]
Hi, do you mean the mobile app?

you are correct the ads will not reflect into the mobile app

**Comment by eitanwa** [comment]
What I meant was the ads
Reflected on the website (mobile browser) not in the mobile app
That it's not supposed to happen as far as I understand
Because there are special mobile ads
As I sent in the pictures

Additionally, the links attached to the ads are not clickable
(On the cellular website)
