### ISSUE TITLE
Unable to login Not given options to input information

### ISSUE THREAD

**Issue by MedikatedTV** [WWBN/AVideo#6520]
Unable to login Not given options to input information. The sign in just says welcome back with no credentials. I can't sign in at all. The site still works but I cant log in to create my live or access any channels.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot it?

I suspect you disable the native login on the plugin configuration, if you did you may need to reset the plugin

Try this

`cd /var/www/html/AVideo/install`

than

```
# php resetPlugins.php 
1 - Reset all plugins Parameters
2 - Reset CustomizeUser Plugin Parameters only
3 - Reset all plugins (Will also inactivate the plugins)
Choose an option: 
```

**Comment by MedikatedTV** [comment]
________________________________

**Comment by MedikatedTV** [comment]
Thanks Daniel. I Need to hire you to configure my Cdn and Object Storage, Is this possible?
________________________________

**Comment by MedikatedTV** [comment]
I want to use my own so I can Have full control of everything. Also, What encoder can I use for install on server. Ive been looking into Azure media services.
________________________________

**Comment by DanielnetoDotCom** [comment]
I am not sure what you mean.
