### ISSUE TITLE
New Error Log

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6523]
![20220420_234054](https://user-images.githubusercontent.com/70327833/164382373-d04c0130-de5a-4aa6-9cab-70ed9d593409.jpg)

**Comment by DanielnetoDotCom** [comment]
is your socket running?

if it is, are you having a high audience? I mean over 1k users online?

**Comment by milehighkaraoke** [comment]
Only a few users... I am noticing that during broadcast I lose my Live ticker at the top. It does it randomly and this is the error I get. The live stream does not get interrupted only the live ticker goes to 0 and then returns after a few minutes... this is the error I amgetting when it happens

**Comment by DanielnetoDotCom** [comment]
I am really not sure what is happening. are you up to date with the latest git pull?
