### ISSUE TITLE
There is no indication of a live broadcast

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#6524]
hey 
Greetings
I would appreciate your attention
From time to time the indication for a live broadcast disappears
Although the broadcast is actually live
As shown in the picture

![photo_2022-04-21_10-40-45](https://user-images.githubusercontent.com/85537931/164404339-0dd4d5c4-152a-4bae-af6e-88019e0b9433.jpg)

thanks
eitan

**Comment by DanielnetoDotCom** [comment]
Watching a video with the live red circle in the player does not mean your stream is live. it means you are reading the DVR feature.

if the notification is 0, please check your Nginx stats page to see if the stream still live
