### ISSUE TITLE
Adding resource to CSP for iFrame

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6525]
We have resource we wish to use on our site using the iframe option. This is coming from canva.com, however I get an error.

The error indicates refused to iframe due to content policy. How do I add that resource so the site's iframe will be able to open it?

How would I set it in the site's header?

![Screen Shot 5782-08-20 at 14 58 49](https://user-images.githubusercontent.com/58882903/164453954-0371b34b-fc0f-4045-9065-153b28615e00.jpg)

**Comment by guymass** [comment]
One other thing which is strange, the user who created the iframe actually is able to open and view it, but no other user can including admin like me. So im not sure what really is going on here, this is a screen shot of what everyone who clicks the "WELLCOME" in the menu have to see, but now only the user who created that menu item is able to view it.

![Screen Shot 5782-08-20 at 15 35 04](https://user-images.githubusercontent.com/58882903/164459091-79529102-74d6-465e-a23e-476346e1b4c1.jpg)

**Comment by guymass** [comment]
https://alive528.com/menu/wellcome
https://alive528.com/menu/support

**Comment by DanielnetoDotCom** [comment]
Looks like there is a cors protection  (or something else)  on canva.com ,  I am not sure if is possible to do something on the AVideo site to allow embedding it

![image](https://user-images.githubusercontent.com/18009293/164791881-3d19a2dc-99dd-49bd-8b72-0c074348869f.png)

**Comment by DanielnetoDotCom** [comment]
The menu https://alive528.com/menu/support

can you please double-check the menuSeoUrlItem??

**Comment by guymass** [comment]
Sorry was mistaken, this url is not made yet, this is the correct one.
https://alive528.com/menu/features

What is strange is, that Eitan the admin user who created the menu item is able to open the iframe. So maybe their site recognizing his computer/browser and showing him the page?

I will try to see if maybe it is something that needs to be done on their side.

**Comment by guymass** [comment]
BTW I think this feature to be able to create a but more complex linked pages and inner menus within AVideo can be a great way for us to provide more content in variety of ways. Currently the editor is very limited when dealing with embedding extra HTML source code and also the amount of text maybe should be, enlarged.

Personally I would prefer to create such pages from within AVideo rather than getting them form a third party like CANVA.

**Comment by guymass** [comment]
Never mind bro, don't break a sweat on this, i am closing this because I just chose a different approach and now everything works within the iframe as all resources are now created locally. 
Here is how I set it up:
https://alive528.com/menu/wellcome
