### ISSUE TITLE
Unable to stream

### ISSUE THREAD

**Issue by MedikatedTV** [WWBN/AVideo#6527]
: Failed to open stream: HTTP request failed! HTTP/1.1 521 in /var/www/html/AVideo/plugin/Live/test.php on line 54
[2022-04-22 16:01:26] Time Elapsed: 0.07501 seconds - file_get_contents::
[2022-04-22 16:01:26] Time Elapsed: 0.07504 seconds - file_get_contents fail return an empty content
[2022-04-22 16:01:26] Time Elapsed: 0.07505 seconds - FAIL
[2022-04-22 16:01:26] Time Elapsed: 0.07506 seconds - Finish try to get URL 

Was working but stopped all together yesterday.

**Comment by DanielnetoDotCom** [comment]
Probably the Nginx is not started or is not installed

try to run:

`/usr/local/nginx/sbin/nginx`

**Comment by MedikatedTV** [comment]
***@***.***:/usr/local/nginx/conf# /usr/local/nginx/sbin/nginx
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:1935 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:8080 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:444 failed (98: Address already in use)
nginx: [emerg] still could not bind()

I started it and restarted and got this error
nginx: [error] open() "/usr/local/nginx/logs/nginx.pid" failed (2: No such file or directory)

________________________________

**Comment by DanielnetoDotCom** [comment]
what is the site URL?

nginx seems to be good

**Comment by DanielnetoDotCom** [comment]
Make sure your firewall is not blocking it

https://medikated.tv:444/

**Comment by MedikatedTV** [comment]
I think it might be cloudflare. Can I whitelist their I.P.s.

________________________________

**Comment by DanielnetoDotCom** [comment]
If you are using cloudflare as a proxy to provide you the ssl. the live stream will not work for sure

**Comment by MedikatedTV** [comment]
is there a workaround? How should i use the cdn?

________________________________

**Comment by DanielnetoDotCom** [comment]
There is no work around the Cloudflare proxy, for my self I use lets encrypt for SSL

but yes you can use a CDN 

https://github.com/WWBN/AVideo/wiki/CDN-Plugin
