### ISSUE TITLE
Cannot log in after latest git pull

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6529]
Clicking the signin button on the login page does nothing

![download](https://user-images.githubusercontent.com/39392449/164815606-8806a8bc-dcd2-45db-a865-c095fe7cb2c8.png)

**Comment by DanielnetoDotCom** [comment]
try this update please

**Comment by JoshWho** [comment]
All fixed. Than you @DanielnetoDotCom

**Comment by JoshWho** [comment]
Everything seems to be function now properly.
