### ISSUE TITLE
Sports Category not showing the Live streams that are set to the Sports Category 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6531]
![77afc2c5-9abc-428d-8d59-5750c1223219](https://user-images.githubusercontent.com/39392449/164867584-2e6dc647-867d-4ea8-8429-119ee11eae6b.png)

There is a few different 24/7 streams in the sports category but it doesn't show for some reason.

**Comment by DanielnetoDotCom** [comment]
can you please share the link to this page?

**Comment by JoshWho** [comment]
https://www.joshwhotv.com/cat/sports

**Comment by JoshWho** [comment]
We have several streams going that are in the Sports category but it only shows that 1.

**Comment by JoshWho** [comment]
Also I have noticed the Live Links Streams that suppose to be Entertainment can be seen in News. and Education appears in Entertainment.

**Comment by DanielnetoDotCom** [comment]
can you please give me an example of a stream that suppose to appear and is not showing?

**Comment by JoshWho** [comment]
Well mostly every live stream is showing in the news category.
![download (63)](https://user-images.githubusercontent.com/39392449/165846533-62b3d504-de72-429b-83dd-28e44cddbc53.png)
![e1a7302d-7729-4df8-a0c0-372c5bcdbf40](https://user-images.githubusercontent.com/39392449/165846564-77fef79c-c533-412f-9e04-b7018219866c.png)
![a482e431-380e-4066-975d-ae3e113bbb05](https://user-images.githubusercontent.com/39392449/165846618-4db7a334-305a-47ab-83de-79ddd8aa0616.png)

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by JoshWho** [comment]
Yes update works great thank you @DanielnetoDotCom
