### ISSUE TITLE
Upcoming Live no longer shows

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#6533]
Scheduled lives disappeared as of this morning. Checked schedule and still there. Did a pull late last night; DDos update...did it effect scheduled lives for anyone else?

**Comment by DanielnetoDotCom** [comment]
I cannot see any reason for that to happen.

check your JS console for errors

**Comment by GreenDragonTavern** [comment]
Good morning Daniel (well at least here ;-) Anyways, idrac hard reset did the trick for whatever reason. Back to normal, and thank you.
