### ISSUE TITLE
YouTube "broke" download by throttling it. Is there a high speed option in YouTube-dl script?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6535]
**Describe the bug**
Cloning videos from YouTube is proceeding at approx 1/3 realtime (e.g. in 24 hours its ingesting 8 hours of media).
I use an app (WonderShare Video Converter) to download that has a "high speed" option that actually works pretty well.
Can we script YouTube-dl to do better?

**To Reproduce**
1. Go to Encode Video and Audio->Import Video
2. Drop a bunch of YouTube video links
3. Wait
4. See how incredibly slow that was? :-(

**Expected behavior**
To beat the YouTube throttling algorithm.

**Comment by DanielnetoDotCom** [comment]
it is a youtube-dl thing.

check this https://github.com/WWBN/AVideo/issues/5972#issuecomment-991991452

**Comment by DanielnetoDotCom** [comment]
I just tested the solution above and it is 10x faster

**Comment by walt93** [comment]
Sweet! Will try this tonight. I have 175 files in the queue that look like will take a month to finish!

**Comment by walt93** [comment]
When it says to add the line to the Encoders config file, which file is that? :-D

**Comment by DanielnetoDotCom** [comment]
Encoder-path/videos/configuration.php

**Comment by DanielnetoDotCom** [comment]
BTW, id you update the encoder and install the yt-dlp you do not need to change anything. the encoder will detect and use the yt-dlp automatically

**Comment by walt93** [comment]
I've done everything, which looks like a step too many. I've installed yt-dlp. I've added the line to configuration.php. I've done a git pull, and I'm updated to 11.7. I had >150 files in the queue, killed the one that was encoding. The next one looks like it picked up with the old script, it's taken several minutes to download 1% of a short file...

Do I need to delete everything in the encoder queue, or, ___?

**Comment by walt93** [comment]
Doing a ps -ax I don't think it's picked up the script change...
```
11764 ?        S      0:00 sh -c /usr/local/bin/youtube-dl  --no-check-certificate --force-ipv4 --no-check-certificate --no-playlist -k -o /tmp/youtubeDlKiVHVH.mp4 -f 'mp4' "https://www.youtube.com/watch?v=iSXxgrTOJuk"  1> /var/www/html/AVideo/Encoder/videos/509_tmpFile_downloadProgress.txt  2>&1
11765 ?        S      0:13 /usr/bin/python /usr/local/bin/youtube-dl --no-check-certificate --force-ipv4 --no-check-certificate --no-playlist -k -o /tmp/youtubeDlKiVHVH.mp4 -f mp4 https://www.youtube.com/watch?v=iSXxgrTOJuk
```

**Comment by DanielnetoDotCom** [comment]
I do not think you need to remove the queue. 

but it may affect only the next one.
