### ISSUE TITLE
Code question. Accessing video duration from view/include/social.php

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6537]
**Describe the question**
I've made some changes to view/include/social.php. I tried to get the video description, but it is not working. _In my analysis it looks like only some of the metadata of the video is encoded into the URL that opens this page, but would take some for me to figure out how to pass it in - probably need to truncate the duration before passing as URL length has a limit._

In the code below, the description is empty. What code changes are necessary to get the video description to here?

This is my modified file /view/include/social.php to include branding/metadata on social posts:

```
<?php
global $socialAdded, $global;
$titleSocial = @$title;
$urlShort = $url;
$sec = "";
$desc = "";
if (empty($video['id']) && !empty(getVideos_id())) {
    $video['id'] = getVideos_id();
}
if (!empty($video['id'])) {
    $url = Video::getLinkToVideo($video['id']);
    $urlShort = Video::getLinkToVideo($video['id'], '', false, "short", [], true);
    if (!empty($video['title'])) {
        $titleSocial = str_replace(['"',"'"], "", $video['title']);
        $sec = $video['duration_in_seconds'];
        $desc = $video['description'];
    } else {
        $video = new Video("", "", $video['id']);
        $titleSocial = str_replace(['"',"'"], "", $video->getTitle());
        $sec = $video->getDuration_in_seconds();
        $desc = $video->getDescription();
    }
}
if ($sec > 3600) {
   $duration = $sec > 0 ? sprintf('Running time %02d:%02d:%02d', ($sec/ 3600),($sec/ 60 % 60), $sec% 60) : "Archive (click through to site, click download link)";
} else {
   $duration = $sec > 0 ? sprintf('Running time %02d:%02d', ($sec/ 60 % 60), $sec% 60) : "Archive (click through to site, click download link)";
}
$mess = $titleSocial . '\n' . $duration . '\n----\n' . '\n#conspyre is a free resource for students of conspiracy, from current events to antedeluvian times.\n' . $urlShort;
```
**Screenshots**
Sharing a post to social media or copying to the clipboard looks as follows: 
_This would be a cool feature to add into a plug-in so the site can configure their messaging/hashtags. Would also be very useful for the Twitter posts..._ 

```
An Evening With Richard Bandler
Running time 54:00
----
<description would go here if the code above worked to retrieve the description...>

#conspyre is a free resource for students of conspiracy, from current events to antedeluvian times.

https://conspyre.tv/v/5754
```

**Comment by DanielnetoDotCom** [comment]
what social media will use the duration?

why not use the field $video['duration'], which already has the formated duration?

**Comment by walt93** [comment]
...what issue did I face, I forget, wrote it months ago, probably just missed it.

How would I get description in here? Do I need to make a change somewhere else to pass description in to this page?

The goal, Daniel, is I manually create a spreadsheet with hundreds of social media posts like this:

![Screen Shot 2022-04-27 at 7 50 17 PM](https://user-images.githubusercontent.com/11711050/165666860-0d420a53-f4ba-4a08-8476-17d38df628e7.png)
s

I coded the copy-to-clipboard function to dump all of that into the clipboard & I'd like to add the description too.

**Comment by DanielnetoDotCom** [comment]
What app/site is that on the screenshot?

if you have a link that has a description and share it here, I can inspect it and try to reproduce it.

Also I still cannot see the duration, and it still seems to be useless for me

**Comment by walt93** [comment]
I think we are crossing signals. That is a post I put on gab to illustrate the goal. I want to push one button and emit the text formatted as above. I have everything working _except_ the videos description. The description is nil at the point of execution in social.php in the code I pasted above. 

I do not know what to change so I can get the videos description in that piece of code. Was hoping you could tell me, what function to call, or, if we need to modify another file to pass the description in. 

Duration is working. Let’s close the duration discussion.

**Comment by DanielnetoDotCom** [comment]
Hi, sorry I am still not sure what exactly you want to grab, but the videos query should have a description field that you can use.

Just like you did above `$desc = $video['description'];`
