### ISSUE TITLE
How to create specific CSS for Hebrew template.

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6539]
I am currently trying to implement a small menu in the site's footer. When I set the CSS for the code all is well when I am in English mode, LTR template, but when I switch to RTL Hebrew my CSS gets messed up by the change in direction.

How can I split my CSS so it behaves differently for both RTL and LTR templates?

**Comment by DanielnetoDotCom** [comment]
Do you mean to create a CSS only for RTL ?
all RTL will be the same or just hebrew?

**Comment by guymass** [comment]
Well for us its Hebrew but this can also serve Arabic language. Like you have the special script area to add scripts and CSS, these will only effect I think the LTR english version. It would be nice to have a second field specific for RTL as well.
