### ISSUE TITLE
Jitsi Meet still is not centered correctly cuts off other windows on live stream

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6540]
![50101dd4-ec8a-4633-8452-92087341e016](https://user-images.githubusercontent.com/39392449/165629287-bc49c393-c89f-4a3b-a7f1-ead42e2fa389.png)

**Comment by DanielnetoDotCom** [comment]
I just update the North America server to the latest jitsi version, can you please confirm if it is good now?

**Comment by JoshWho** [comment]
It looks beautiful Now. Thank you so much.

**Comment by JoshWho** [comment]
Any way you can enable the Background option on the Jitsi. It lets you fake your background behind you on camera.

**Comment by JoshWho** [comment]
I think it is called video background

**Comment by DanielnetoDotCom** [comment]
I just searched it here, I did not find any option about "Virtual Backgrounds", I guess it is already enabled

**Comment by JoshWho** [comment]
Found it this is not enabled 

![26419345-3f7bb6c8240066958960925d26df9eb7](https://user-images.githubusercontent.com/39392449/165831944-4b36a939-3770-4b54-9d87-18cd371532bf.png)

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by JoshWho** [comment]
Works perfectly now. Thank you so much. This is truly the best and way better than Zoom or Skype will ever be.
