### ISSUE TITLE
[enhancement] OpenGraph tags for category pages

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6544]
**Is your feature request related to a problem? Please describe.**
I’m always frustrated when I drop a link to a category page to share an organized collection of media, and I get a generic OG Tag with the site fav icon and tag line

**Describe the solution you'd like**
I’d like the /cat page to tag with the metadata/description we’ve already set up for the category.

If the category has no description we should fall back to what we’re using now. 

**Describe alternatives you've considered**
There is really no alternative, this is just sub-optimal. We're sharing the category page, and using the site description, we want to share the category description.

**Comment by DanielnetoDotCom** [comment]
Please check this update
