### ISSUE TITLE
[Collab request] Making a hierarchical categories left menu for mobile

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6546]
**Is your feature request related to a problem? Please describe.**
99% of the media on my site is censored by communist platforms  and GOOG, therefore I cannot use the white label mobile apps. I'm ok with sending my users to the free version. This is an unmonetized site I run as a hobby, after all…

The categories left menu displays the entire hierarchy, flat. My site has 500+ categories and is 5 levels deep. Keeping the hierarchy collapsed as per the web implementation is necessary...

**Describe the solution you'd like**
I'm a developer ( platforms) by day job. I'd like access to the repo to make the desired changes - implementing a tap-to-open tap-to-close hierarchy that shows indentation corresponding to hierarchy level. When done, to submit a pull request. As stated I can't white label this thing until Elon Musk buys both Apple **and** Google - and the guy just is not _that_ rich.

**Describe alternatives you've considered**
Completely re-doing the hierarchy of 500 categories/sub-categories/sub-sub-categories/sub-sub-sub-categories for 9,000 pieces of media. I'd rather not.

**Comment by DanielnetoDotCom** [comment]
Hi

if you have knowledge on IONIC V3 email me at developer@youphptube.com and we can talk about the updates :) . Thanks
