### ISSUE TITLE
How to translate the Terms of use

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6548]
In the registration page there is "Terms of use" section which is now in Hebrew. We would like to have an english version as well on the English registration page. How do we create a translation for this section?

**Comment by DanielnetoDotCom** [comment]
Currently, there is no option to translate.

why don't you create another web page, a static one for both languages, and use the external link replacing the "Terms of use"

this may be easier to update and control the language.

**Comment by guymass** [comment]
Great we did just that.much thanks.
