### ISSUE TITLE
Please restart your socket server v2.8 expecting v3.0

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6549]
I'v updated today and now i am getting this message indicating I should restart the socket server because i am running v2.8 and it is expecting v3.0. Everything seems to be updated so i am not sure what it is referring to.
![Screen Shot 5782-08-28 at 17 40 22](https://user-images.githubusercontent.com/58882903/165967568-292f76b7-8b81-4ce9-acd4-4d348db5b0ae.jpg)

**Comment by guymass** [comment]
The only plugin I have with version 2.8 is LDAP and it off.
![Screen Shot 5782-08-28 at 17 47 24](https://user-images.githubusercontent.com/58882903/165968444-3b4048d9-94e6-4a76-9f30-3b2071f9a087.jpg)

**Comment by guymass** [comment]
OK great thanks. You need to first stop, clear all caches and only start it after and it will work then.

**Comment by DanielnetoDotCom** [comment]
Hi, it does not need to clear cache
