### ISSUE TITLE
Meet - Can't Schedule nor Create a New Meet

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#6550]
Adding a Scheduled Meet circles forever; Create a New gives Ajax error. Below is single error for Meet;

AVideoLog::ERROR: {"type":1,"message":"Uncaught ArgumentCountError: Too few arguments to function Firebase\\JWT\\JWT::encode(), 2 passed in \\/var\/www\/html\/AVideo\/plugin\/Meet\/Meet.php on line 144 and at least 3 expected in \/var\/www\/html\/AVideo\/vendor\/firebase\/php-jwt\/src\/JWT.php:184\nStack trace:\n#0 \/\/var\/www\/html\/AVideo\/plugin\/Meet\/Meet.php(144): Firebase\\JWT\\JWT::encode()\n#1 \/var\/www\/html\/AVideo\/plugin\/Meet\/saveMeet.json.php(98): Meet::getToken()\n#2 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/vendor\/firebase\/php-jwt\/src\/JWT.php","line":184} SCRIPT_NAME: /plugin/Meet/saveMeet.json.php

**Comment by DanielnetoDotCom** [comment]
are you up to date?

I am not having those errors

**Comment by GreenDragonTavern** [comment]
Totally up to date (just updated Chat2, LiveUsers and killed socket process and restarted). Logged in your demo site and no issue creating a Meet. Ubuntu, PHP 8.1, using PHP8.1 mod under Apache. SQL Meet record is being created but as stated; endless circle hourglass on Schedule, Ajax error on quicky create.

**Comment by GreenDragonTavern** [comment]
Yes, did a pull just a bit ago. It wanted me to restart socket server, and I did. Meet does not work. https://tube.michaelkjaco.com created user DanielNeto@jacotube.com and use 1!DanielNeto. You're Admin, login and give it a shot.

**Comment by DanielnetoDotCom** [comment]
Hi

sorry for direct support, I need to charge one hour supports

**Comment by GreenDragonTavern** [comment]
Ubuntu (v20.04), PHP8.1, using PHP8.1 mod (not FPM) on Apache2.

**Comment by DanielnetoDotCom** [comment]
Your Ubuntu and php versions are fine 

, please share the logs

also try to reproduce this error on demo site and screenshots on the paga that the error happens

**Comment by GreenDragonTavern** [comment]
Mentioned previously that I did log into demo site and created meet with no issue. This was first line in avideo.log (the rest pertains to folks on site).

[29-Apr-2022 16:04:58 America/Los_Angeles] AVideoLog::ERROR: {"type":1,"message":"Uncaught ArgumentCountError: Too few arguments to function Firebase\\JWT\\JWT::encode(), 2 passed in \/var\/www\/html\/AVideo\/plugin\/Meet\/Meet.php on line 144 and at least 3 expected in \/var\/www\/html\/AVideo\/vendor\/firebase\/php-jwt\/src\/JWT.php:184\nStack trace:\n#0 \/var\/www\/html\/AVideo\/plugin\/Meet\/Meet.php(144): Firebase\\JWT\\JWT::encode()\n#1 \/var\/www\/html\/AVideo\/plugin\/Meet\/saveMeet.json.php(98): Meet::getToken()\n#2 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/vendor\/firebase\/php-jwt\/src\/JWT.php","line":184} SCRIPT_NAME: /plugin/Meet/saveMeet.json.php
[
![Meet-Error1](https://user-images.githubusercontent.com/85363361/166079268-3f4f9018-721a-4b7b-8d65-68c9743c5537.jpg)
![Meet-Error2](https://user-images.githubusercontent.com/85363361/166079295-7d5a5a26-53ae-43d8-9fd8-f43b27d60e03.jpg)

**Comment by DanielnetoDotCom** [comment]
I suspect you changed something ou your installation, I just double-checked the JWT file and it requires only 2 parameters

https://github.com/WWBN/AVideo/blob/6f50b18542056c0a1aab898f7c285b5348ab51f7/vendor/firebase/php-jwt/src/JWT.php#L181

try to reset your git `sudo git fetch --all && sudo git reset --hard origin/master`

**Comment by GreenDragonTavern** [comment]
That did it, thank you. Never had issue with git pull(s) so no idea what happened. You be 'da man!
