### ISSUE TITLE
Updated to Ubuntu 22.04 LTS  Wayland Gnome 42.0 PHP 8.1

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6555]
I have had no issues and it has made a huge improvement with my sites performance........save your current NGINX configuration, you will need it and it will save you lots of time. After the upgrade  You must dismount your current PHP and enable the new php 8.1 

sudo update-alternatives --set php /usr/bin/php8.1 && sudo a2dismod php8.0 && sudo a2enmod php8.1

Reinstall your NGINX with the latest Stable version 1.20.2
https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

**Comment by DanielnetoDotCom** [comment]
Hi, 

I have never tested on Ubuntu 22, but I suspect that would be a good Ubuntu version;

PHP 8.1 also works on other Ubuntu distributions.

**Comment by lunar54** [comment]
Anyone else test Ubuntu 22.04 ?

**Comment by milehighkaraoke** [comment]
It is running it flawless 
https://mhktube.com

**Comment by milehighkaraoke** [comment]
Currently streaming live at
https://mhktube.com/live/0/MileHighKaraokeLive

**Comment by lunar54** [comment]
Ok just did test install my self on Ubuntu 22.04 looks like should be working 

![av1](https://user-images.githubusercontent.com/35050024/179145742-fbf877e2-ea13-4c72-a6ac-ed6c58e0e767.PNG)
![av2](https://user-images.githubusercontent.com/35050024/179145766-581d7061-13cc-4452-8d3d-651edbff101b.PNG)
![av3](https://user-images.githubusercontent.com/35050024/179145793-2458daee-ddcd-4885-897f-0ee3fccfe859.PNG)
