### ISSUE TITLE
Force SSL HTTPS

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6557]
Hi @DanielnetoDotCom,

I did a recent Git PULL to update the AVideo platform.
I was notified by Git that I had changes to file .htaccess in local file.
The changes I made were on two lines, to force the browser to access SSL over HTTPS.
I had to remove these lines to be able to run the PULL:
```
RewriteCond %{SERVER_PORT} 80
RewriteRule ^(.*)$ https://domain.com.br/$1 [R,L]
```

I would like to know if there is any configuration or plugin that makes the site force SSL?
I didn't find instructions on this process.

Thanks.

**Comment by DanielnetoDotCom** [comment]
Change it on your Apache configuration or virtual host config . Do not change the .htaccess

**Comment by JoshWho** [comment]
Just run this and it will force the update

`git fetch --all && git reset --hard origin/master`

**Comment by gbrn** [comment]
@DanielnetoDotCom Returning to the SSL HTTPS problem....but a new problem.
With the exchange of the shared server for a new VPS, I am doing all the installations and configurations myself.
The AVideo platform is working normally... but I had to enable SSL...
Follow Digitalocean's tutorial for installing:
https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-22-04

I used CERTBOT to automate the installation in APACHE. My virtual host looks like this:

```
<VirtualHost *:80>
    DocumentRoot /var/www/html/AVideo
    ServerName cnetv.com.br
    ServerAlias www.cnetv.com.br cinetv.com.br www.cinetv.com.br
    ServerAdmin webmaster@localhost
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
RewriteEngine on
RewriteCond %{SERVER_NAME} =www.cnetv.com.br [OR]
RewriteCond %{SERVER_NAME} =cinetv.com.br [OR]
RewriteCond %{SERVER_NAME} =cnetv.com.br [OR]
RewriteCond %{SERVER_NAME} =www.cinetv.com.br
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
<VirtualHost *:443>
    DocumentRoot /var/www/html/AVideo
    ServerName cnetv.com.br
    ServerAlias www.cnetv.com.br cinetv.com.br www.cinetv.com.br
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
SSLCertificateFile /etc/letsencrypt/live/cnetv.com.br/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/cnetv.com.br/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
<Directory "/var/www/html/AVideo/">
    Options Indexes FollowSymLinks
    XSendFile on
    XSendFilePath /var/www/html/AVideo/
    AllowOverride All
    Require all granted
    Order Allow,Deny
    Allow from All
</Directory>
```

After configuration, the platform entered a redirection loop:
ERR_TOO_MANY_REDIRECTS

Check the following line that causes this looping redirection:
`RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]`

I don't know if this line is incorrect... or this CERTBOT configuration conflicts with another that is already written in some file of the AVIDEO platform.

Can you help me on this issue?
Detail... I'm using Cloudflare.

**Comment by gbrn** [comment]
@DanielnetoDotCom I checked that there are already some lines about SSL https in the `.htaccess` file:

```
<IfModule mod_rewrite.c>
    RewriteCond %{HTTPS} =on
    RewriteRule ^(.*)$ - [env=proto:https]
    RewriteCond %{HTTPS} !=on
    RewriteRule ^(.*)$ - [env=proto:http]

    RewriteEngine on
```
I don't know how much these lines are working for me or disturbing ...

**Comment by gbrn** [comment]
I disabled Cloudflare services, and the problem is not with them.

**Comment by gbrn** [comment]
I did a test commenting these lines in the file, but nothing changed...

```
RewriteCond %{HTTPS} =on
    RewriteRule ^(.*)$ - [env=proto:https]
    RewriteCond %{HTTPS} !=on
    RewriteRule ^(.*)$ - [env=proto:http]

    RewriteEngine on
```

**Comment by gbrn** [comment]
I did a new installation check and found that it wasn't installed:
apt-transport-https
software-properties-common

But it didn't make any difference either.

**Comment by gbrn** [comment]
I've run the apache tests....viewed the logs...nothing that indicated a problem.
```
sudo apachectl configtest
Syntax OK
```

**Comment by gbrn** [comment]
I redirected the subject to issue #7744
