### ISSUE TITLE
Accessibility Test on UserWAy

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6561]
We have ran this test on UserWay to see what issues may arise accessibility wise and have received many issues. I just thought you might want to take a look as well and see what other issues can be fixed and improved because those issues may and can incur a law suite from some individual who seeks to cause damage.
![Screen Shot 5782-09-03 at 22 30 22](https://user-images.githubusercontent.com/58882903/166812140-977edf3e-a8a4-4f44-b323-ca6619aeb5d0.jpg)

This is the testing site:
https://inspect.userway.org/

**Comment by DanielnetoDotCom** [comment]
thanks I will check
