### ISSUE TITLE
Proper way to extend session timeout

### ISSUE THREAD

**Issue by aolvictim** [WWBN/AVideo#6562]
**Describe the question**
The default session timeout is a bit too short. What's the proper way to set the value for it?

**Comment by elico** [comment]
@aolvictim what's the proper way?

**Comment by DanielnetoDotCom** [comment]
Try this

![image](https://user-images.githubusercontent.com/18009293/167025420-30375b96-6a92-42f4-a61b-d3520918a5df.png)


![chrome-capture-2022-4-5](https://user-images.githubusercontent.com/18009293/167025431-acd8c64e-16d9-428d-a0f0-30a8dc6c6adf.gif)

**Comment by aolvictim** [comment]
Yes that makes sense. I over think it. Thank you
