### ISSUE TITLE
Optional Ad Tag use case

### ISSUE THREAD

**Issue by aolvictim** [WWBN/AVideo#6563]
**Describe the question**
After reading the Wiki article on [GoogleAds_IMA Ads Plugin](https://github.com/WWBN/AVideo/wiki/Plugin:-GoogleAds_IMA---Videos-Ads-on-your-page), I am still not too sure how to use the optional ad tags.

I want to be able to use different ad tag for certain channels, is optional ad tag the right place to do it? If so how would I do that?

**Comment by DanielnetoDotCom** [comment]
Hi this is only useful if you are using the api to create third parties app

in most of the regular cases it is useless

**Comment by aolvictim** [comment]
I see. So is there a way to show different Ad Tag for different channel in the current code base? Or custom programming is needed?

**Comment by DanielnetoDotCom** [comment]
Sorry not yet
