### ISSUE TITLE
Mobile App Error

### ISSUE THREAD

**Issue by joex19x84** [WWBN/AVideo#6564]
**Describe the bug**
Unable to log in to mobile app.

**To Reproduce**
1. Click on 'Change site'
2. Enter site, then click on 'Check Site'
3. See error

**Expected behavior**
The login form should appear.

**Error Logs**
Provide the log files at the moment you found the issue.
If you are not sure how to find the log file, please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
A page of the apache log file at time of error.
/var/log/apache2/error.log (actual fqdn replaced with fqdn.com)

'^videos/(.*)/index.m3u8$' to uri 'objects/status.json.php', referer: http://localhost/
[Wed May 04 18:22:31.312430 2022] [rewrite:trace3] [pid 1374486:tid 139775007012608] mod_rewrite.c(483): [client 192.168.1.1:60874] 192.168.1.1 - - [fqdn.com/sid#7f1ffad88ec8][rid#7f1fe41c3ee8/initial/redir#1] [perdir /var/www/mytube/] strip per-dir prefix: /var/www/mytube/objects/status.json.php -> objects/status.json.php, referer: http://localhost/
[Wed May 04 18:22:31.312434 2022] [rewrite:trace3] [pid 1374486:tid 139775007012608] mod_rewrite.c(483): [client 192.168.1.1:60874] 192.168.1.1 - - [fqdn.com/sid#7f1ffad88ec8][rid#7f1fe41c3ee8/initial/redir#1] [perdir /var/www/mytube/] applying pattern '^videos/(.*)/index.m3u8.mp4$' to uri 'objects/status.json.php', referer: http://localhost/
[Wed May 04 18:22:31.312440 2022] [rewrite:trace3] [pid 1374486:tid 139775007012608] mod_rewrite.c(483): [client 192.168.1.1:60874] 192.168.1.1 - - [fqdn.com/sid#7f1ffad88ec8][rid#7f1fe41c3ee8/initial/redir#1] [perdir /var/www/mytube/] strip per-dir prefix: /var/www/mytube/objects/status.json.php -> objects/status.json.php, referer: http://localhost/
[Wed May 04 18:22:31.312445 2022] [rewrite:trace3] [pid 1374486:tid 139775007012608] mod_rewrite.c(483): [client 192.168.1.1:60874] 192.168.1.1 - - [fqdn.com/sid#7f1ffad88ec8][rid#7f1fe41c3ee8/initial/redir#1] [perdir /var/www/mytube/] applying pattern '^vast.xml/?([0-9]+)?$' to uri 'objects/status.json.php', referer: http://localhost/
[Wed May 04 18:22:31.312451 2022] [rewrite:trace3] [pid 1374486:tid 139775007012608] mod_rewrite.c(483): [client 192.168.1.1:60874] 192.168.1.1 - - [fqdn.com/sid#7f1ffad88ec8][rid#7f1fe41c3ee8/initial/redir#1] [perdir /var/www/mytube/] strip per-dir prefix: /var/www/mytube/objects/status.json.php -> objects/status.json.php, referer: http://localhost/
[Wed May 04 18:22:31.312455 2022] [rewrite:trace3] [pid 1374486:tid 139775007012608] mod_rewrite.c(483): [client 192.168.1.1:60874] 192.168.1.1 - - [fqdn.com/sid#7f1ffad88ec8][rid#7f1fe41c3ee8/initial/redir#1] [perdir /var/www/mytube/] applying pattern '(.*)$' to uri 'objects/status.json.php', referer: http://localhost/
[Wed May 04 18:22:31.312461 2022] [rewrite:trace3] [pid 1374486:tid 139775007012608] mod_rewrite.c(483): [client 192.168.1.1:60874] 192.168.1.1 - - [fqdn.com/sid#7f1ffad88ec8][rid#7f1fe41c3ee8/initial/redir#1] [perdir /var/www/mytube/] strip per-dir prefix: /var/www/mytube/objects/status.json.php -> objects/status.json.php, referer: http://localhost/
[Wed May 04 18:22:31.312464 2022] [rewrite:trace3] [pid 1374486:tid 139775007012608] mod_rewrite.c(483): [client 192.168.1.1:60874] 192.168.1.1 - - [fqdn.com/sid#7f1ffad88ec8][rid#7f1fe41c3ee8/initial/redir#1] [perdir /var/www/mytube/] applying pattern '.*$' to uri 'objects/status.json.php', referer: http://localhost/
[Wed May 04 18:22:31.312471 2022] [rewrite:trace1] [pid 1374486:tid 139775007012608] mod_rewrite.c(483): [client 192.168.1.1:60874] 192.168.1.1 - - [fqdn.com/sid#7f1ffad88ec8][rid#7f1fe41c3ee8/initial/redir#1] [perdir /var/www/mytube/] pass through /var/www/mytube/objects/status.json.php, referer: http://localhost/

**Screenshots**
![Screenshot_20220504-173612_AVideo Platform](https://user-images.githubusercontent.com/60396003/166835773-041284cf-1264-415e-b8f5-adeba1718ebe.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A51
 - OS: Android 11

**Additional context**
I was notified that an Apple iPad user also can't log in. I'm assuming it's the same error.

**Comment by joex19x84** [comment]
Yes. The site works fine in a web browser.

**Comment by DanielnetoDotCom** [comment]
what is your site link?

**Comment by joex19x84** [comment]
[https://tube.cartashosting.com](url)

**Comment by joex19x84** [comment]
[https://tube.cartashosting.com](https://tube.cartashosting.com)

**Comment by DanielnetoDotCom** [comment]
Inspecting your site you got an error 

CORS error

![image](https://user-images.githubusercontent.com/18009293/167263227-b5deb823-7150-4332-8fe5-0291ed427564.png)


probably is something on your server configuration

are you using apache?

try to find on your server where are you blocking CORS, try to google

**Comment by joex19x84** [comment]
Yes, I am using apache. I checked into this, and I don't think CORS is being blocked. It appears to be enabled in the .htaccess, and I also tried to allow it in my VirtualHost file, but I get the same error. I also can't see this CORS error that you're getting. Are you using the developer tools in a browser?

**Comment by DanielnetoDotCom** [comment]
It is cors for sure, maybe another configuration on your apache.

Yes I am using a developer tool that you can only have access with the mobile source code
