### ISSUE TITLE
Clearing cache periodically from CLI 

### ISSUE THREAD

**Issue by elico** [WWBN/AVideo#6566]
My site has more then 150k Embedded videos and the cache folder is being filled pretty fast.
I need to extend my disk space to allow the videos thumbnails storage however I had my cache filled up my disk.
I would like to periodically check the size of the disk cache directory and clean it up from CLI.
What are my options to do it?
Currently I am using the "Clear Cache Directory" button in the navbar but would like to be able to run it manually as the server admin.

Thanks,

**Comment by DanielnetoDotCom** [comment]
what AVideo version are you running?

the cache folder should not be big

I have a customer with about 11k videos, (real ones) and he is using less than 1GB on the cache.

if you want you can create a crontab and delete the cache folder 

also you can add this on your corn tab

`0 2 * * * php /var/www/html/AVideo/plugin/Cache/crontab.php`

the script above will delete files on your cache that are 3 days old or more

https://github.com/WWBN/AVideo/blob/master/plugin/Cache/crontab.php

**Comment by elico** [comment]
@DanielnetoDotCom Thanks!
I have seen the sources and I cleared manually the full cache in a similar way.
It's a very nice script.
I will run it daily.

Thanks!!
