### ISSUE TITLE
live streaming not working mean not capturing webcam 

### ISSUE THREAD

**Issue by sumperktv** [WWBN/AVideo#6568]
Hi Daniel

I installed software and it is working fine 4-5 days, after disconnected the live, next day onwards it is not working at all.  I attached log file with this. my site address is https://sumperk.tv

Thanking you
Walter

[error-log-file of AVideo.txt](https://github.com/WWBN/AVideo/files/8644667/error-log-file.of.AVideo.txt)

**Comment by DanielnetoDotCom** [comment]
Hi, what webcam are you referring to?

can you please screenshot it?

**Comment by sumperktv** [comment]
It is working before prepare for the WebRTC link but now it fully blank
[image: image.png]

**Comment by DanielnetoDotCom** [comment]
The WebRTC is experimental it is not fully working yet .

**Comment by sumperktv** [comment]
Then because of WebRTC only my streaming software auto integrating and
working. Then what is the next? Even  though, if you also installed the
same thing? It is not fully equipped yet? Like Dacast? RTMP links are not
accepting my Manycam software, it may accept , I don't know how to
configure it. Then what is the solution for WebRTC to work fully? Please do
the needful.

with regards
Walter

**Comment by DanielnetoDotCom** [comment]
Try to use obs 

if you installed it properly it should work fine

**Comment by sumperktv** [comment]
Manycam is the best software for live streaming and if I get working WebRTC, it is very fine.and it is very useful for me even though investing for your video server, Otherwise it is not worth to spend for this software it is better to do it by youtube and other social media directly without any problem.

Please make it work with the WebRTC and do the needful. 

Thanking you with regards
Walter
