### ISSUE TITLE
Meet  Photo backgrounds not working on my webview app

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#6569]
Greetings Mr @DanielnetoDotCom  could you please help me. The photo backgrounds are working fine on Google Chrome browser, but it's not working on my webview app please help. Here is my android app Link. 
https://play.google.com/store/apps/details?id=com.livefaces.restream

We what can I do?

**Comment by DanielnetoDotCom** [comment]
To be honest I have no idea

you may need to make some debug to find out.
