### ISSUE TITLE
Screen keeps moving down once page loads and wont show the true top. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6570]
Here is a example where on the live stream I cannot see what the user count is at the top left corner of the video

![download (1)](https://user-images.githubusercontent.com/39392449/167280146-a1cb9ef5-0bc6-4a21-9a37-61ef2a9515b4.png)

This is that page above https://www.joshwhotv.com/live/1/Ohiopoliticalnews

It wont let me scroll up

**Comment by JoshWho** [comment]
It is weird. You see the top of the screen when the page is loading but once everything is loaded it just scrolls up like a couple inches and won't let you scroll back down.

**Comment by DanielnetoDotCom** [comment]
from here it seems fine to me.

I am not sure what do you mean exactly

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/18009293/167456268-b21c701e-7919-415d-8cc4-c25d4d6de5d4.png">

**Comment by JoshWho** [comment]
I seen it do it on mobile also. Not sure what it is

**Comment by DanielnetoDotCom** [comment]
I am also not sure.

try to clear the site cookies. maybe is some cached CSS or something else.

FYI, I tested it on chrome Windows 10

**Comment by DanielnetoDotCom** [comment]
I am also not sure.

try to clear the site cookies. maybe is some cached CSS or something else.

FYI, I tested it on chrome Windows 10

**Comment by JoshWho** [comment]
I solved it by just adding some <br><br>  tags to the customize advance under menu html and looks perfect now.
