### ISSUE TITLE
CDN isn't. Not sure how to make it CDN again.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6571]
**Describe the question**
I have too many gmail accounts. I inadvertently created two accounts on youphp.tube.

I originally put a CDN refill on the wrong account. I thought we fixed this weeks ago, but just checked it.

How to restore CDN functionality? 

**Screenshots**
youphp.tube/marketplace:
![Screen Shot 2022-05-07 at 10 05 50 PM](https://user-images.githubusercontent.com/11711050/167282654-36704bc0-27ca-45c4-8b26-1bf6a3d36ada.png)

conspyre.tv/plugins:
![Screen Shot 2022-05-07 at 10 06 11 PM](https://user-images.githubusercontent.com/11711050/167282664-132c3ca2-0e44-4705-b126-1fc2756e5f64.png)

**Comment by DanielnetoDotCom** [comment]
Can you please directly email me what account you want to use the CDN and what email account you did refill wrong?

**Comment by walt93** [comment]
Closing issue as you had fixed this, thanks. :-)
