### ISSUE TITLE
LiveStream Camera Configuration Black Page

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6572]
I was trying to use  the camera feature and open the configuration and got a black page.
![Screen Shot 5782-09-08 at 20 15 27](https://user-images.githubusercontent.com/58882903/167466922-d7a78325-733a-42ac-a528-5f475d453acf.jpg)

**Comment by DanielnetoDotCom** [comment]
I guess this is the meet server, 

what server are you using NA or Europe?

**Comment by guymass** [comment]
We are using the America server because europe for some reason doesn't work for us anymore.

**Comment by DanielnetoDotCom** [comment]
Hi

I just tried Europe from 2 different sites and it works fine.

if you do not mind please try again. make sure you are up to date.

**Comment by guymass** [comment]
Well I tried it now, creating a new meet session I get the followings:
![Screen Shot 5782-09-10 at 18 36 57](https://user-images.githubusercontent.com/58882903/167890460-f10ee6bc-ecfc-416a-a9de-64f814fa7fc2.jpg)

![Screen Shot 5782-09-10 at 18 37 15](https://user-images.githubusercontent.com/58882903/167890521-df09a7d2-fab1-4352-9355-79221460759d.jpg)

Here is my config, disregard our own jitsi server, we are not using it inside the site currently but as an external server

![Screen Shot 5782-09-10 at 18 37 35](https://user-images.githubusercontent.com/58882903/167890781-06dc23fb-49c4-4928-94db-ada61f873986.jpg)

**Comment by guymass** [comment]
Had to reopen this because I forgot that the first issue was with the webcam not working. Jitsi is working so this is not the case. We have checked this also on the web site of JoshWhoTV and they have the same problem. We think this is an IFRAME issue. Currently we cannot go live with the webcam because even the "Go Live" button is faded out and cannot be clicked.
![Screen Shot 5782-09-10 at 19 27 33](https://user-images.githubusercontent.com/58882903/167900458-580660c4-0ae1-43a5-979b-22d5cfe4ca76.jpg)

**Comment by guymass** [comment]
We also noticed the even though the screen is black, while we move the mouse around and place it the top line, it opens like a menu, so my guess is that something is wrong with the iframe or that perticulare page has a bug.
![photo_2022-05-11 19 29 12](https://user-images.githubusercontent.com/58882903/167900875-81b1f6b1-19e2-4772-b3e8-46012275eb39.jpeg)

![photo_2022-05-11 19 31 08](https://user-images.githubusercontent.com/58882903/167901027-5505a7fd-0fec-4b35-a55b-4efde13a0feb.jpeg)

**Comment by guymass** [comment]
I went to Go Live and from there I click the webcam button next to the Meet button!

**Comment by guymass** [comment]
awesome!! much thanks its working now.
