### ISSUE TITLE
Customize User "don't identify by email or user name 

### ISSUE THREAD

**Issue by ahmedxda** [WWBN/AVideo#6573]
when I check on "don't identify by email or username " changing the value to true , my website stops working completely even my AWS EC2  server stops and I find no way to connect to my server..
maybe after few hours the website get alive again but with many bugs such as automatically the website signs me out ... the playlists dosen't work properly  and some other bugs ..
don't ask me for logs because the site goes down and I have no way to reach it !

**Comment by DanielnetoDotCom** [comment]
I do not think it has anything to do with the plugin configuration. it does not make sense.

but anyway. you must be able to get the logs using the command line.

without logs I cannot help you

**Comment by ahmedxda** [comment]
@DanielnetoDotCom 
well Daniel ,I found that  the Email field is duplicated... I should see a field for the Username and another field for the Email, but both fields require me to insert email...may be this why my website signs logged in users out "including the admin"

**Comment by ahmedxda** [comment]
![USER_SCOPED_TEMP_DATA_orca-image-1792013583](https://user-images.githubusercontent.com/104592418/167517000-480b31fc-3542-4423-8929-446f0409ca28.jpeg)

**Comment by DanielnetoDotCom** [comment]
Sorry I am confused what is your issue

but yes the email field seems to be wrong, but this cannot make your server crash

**Comment by ahmedxda** [comment]
at least please fix the duplicated email fields..
and I will try to get the logs..
thanks Daniel

**Comment by DanielnetoDotCom** [comment]
can you please specify what screen is that?

**Comment by ahmedxda** [comment]
the screen is from edit personal account page..
and here is the logs I got following your tutorial to get logs::

rNotifyIsDone.json.php
[09-May-2022 22:42:13 Africa/Abidjan] AVideoLog::WARNING: Vi
deo::setStatus(a) [{"file":"\/var\/www\/AVideo\/objects\/vid
eo.php","line":631,"function":"setStatus","class":"Video","o
bject":{"views_count_25":0,"views_count_50":0,"views_count_7
5":0,"views_count_100":0,"modified":"2022-05-09 22:42:13","o
rder":1},"type":"->","args":["a"]},{"file":"\/var\/www\/AVid
eo\/objects\/aVideoEncoderNotifyIsDone.json.php","line":40,"
function":"setAutoStatus","class":"Video","object":{"views_c
ount_25":0,"views_count_50":0,"views_count_75":0,"views_coun
t_100":0,"modified":"2022-05-09 22:42:13","order":1},"type":
"->","args":["a"]}] SCRIPT_NAME: /objects/aVideoEncoderNotif
yIsDone.json.php
[09-May-2022 22:42:13 Africa/Abidjan] AVideoLog::DEBUG: Vide
o:clearCache(4) SCRIPT_NAME: /objects/aVideoEncoderNotifyIsD
one.json.php
[09-May-2022 22:42:13 Africa/Abidjan] AVideoLog::DEBUG: dele
teVideoTags getVideoTags4 SCRIPT_NAME: /objects/aVideoEncode
rNotifyIsDone.json.php
[09-May-2022 22:42:13 Africa/Abidjan] AVideoLog::DEBUG: clea
rCache starts  SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDo
ne.json.php
[09-May-2022 22:42:13 Africa/Abidjan] AVideoLog::DEBUG: rrmd
ir: could not delete folder /var/www/AVideo/videos/cache/YPT
ObjectCache/firstpage/ SCRIPT_NAME: /objects/aVideoEncoderNo
tifyIsDone.json.php
[09-May-2022 22:42:13 Africa/Abidjan] AVideoLog::DEBUG: clea
rCache end in 0.002345085144043 seconds SCRIPT_NAME: /object
s/aVideoEncoderNotifyIsDone.json.php
[09-May-2022 22:42:13 Africa/Abidjan] AVideoLog::DEBUG: Vide
o::save (الزواج على طريقة الحاج الأسيوطي) Saved id = 4  SCRI
PT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
[09-May-2022 22:42:13 Africa/Abidjan] AVideoLog::DEBUG: Vide
o:clearCache(4) SCRIPT_NAME: /objects/aVideoEncoderNotifyIsD
one.json.php
[09-May-2022 22:42:13 Africa/Abidjan] AVideoLog::DEBUG: dele
teVideoTags getVideoTags4 SCRIPT_NAME: /objects/aVideoEncode
rNotifyIsDone.json.php
[09-May-2022 22:42:13 Africa/Abidjan] AVideoLog::DEBUG: getU
sageFromFilename: start /var/www/AVideo/videos/video_2205092
23754_v1f39/video_220509223754_v1f39 [{"file":"\/var\/www\/A
Video\/objects\/video.php","line":1511,"function":"getUsageF
romFilename"},{"file":"\/var\/www\/AVideo\/objects\/aVideoEn
coderNotifyIsDone.json.php","line":55,"function":"updateFile
size","class":"Video","type":"::"}] SCRIPT_NAME: /objects/aV
ideoEncoderNotifyIsDone.json.php
[09-May-2022 22:42:13 Africa/Abidjan] AVideoLog::DEBUG: getD
irSize: start /var/www/AVideo/videos/video_220509223754_v1f3
9/ SCRIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
[09-May-2022 22:42:13 Africa/Abidjan] AVideoLog::DEBUG: getD
irSize: found 16947527 from - 16947527  /var/www/AVideo/vide
os/video_220509223754_v1f39/ SCRIPT_NAME: /objects/aVideoEnc
oderNotifyIsDone.json.php
[09-May-2022 22:42:13 Africa/Abidjan] AVideoLog::DEBUG: getU
sageFromFilename: is Dir dirSize=16947527 16.16MB /var/www/A
Video/videos/video_220509223754_v1f39/ SCRIPT_NAME: /objects
/aVideoEncoderNotifyIsDone.json.php
[09-May-2022 22:42:13 Africa/Abidjan] AVideoLog::DEBUG: FTP:
getClient fail () (Ahmed), (ay.3152010) Unable to connect SC
RIPT_NAME: /objects/aVideoEncoderNotifyIsDone.json.php
[09-May-2022 22:48:49 Africa/Abidjan] AVideoLog::DEBUG: im_r
esizeV2: /var/www/AVideo/videos/video_220509223523_vfb67/vid
eo_220509223523_vfb67.jpg, /var/www/AVideo/videos/video_2205
09223523_vfb67/video_220509223523_vfb67_thumbsV2.jpg, 640, 3
60, 80 SCRIPT_NAME: /view/info.php
[09-May-2022 22:48:49 Africa/Abidjan] AVideoLog::DEBUG: im_r
esizeV2: /var/www/AVideo/videos/video_220509223637_vfb33/vid
eo_220509223637_vfb33.jpg, /var/www/AVideo/videos/video_2205
09223637_vfb33/video_220509223637_vfb33_thumbsV2.jpg, 640, 3
60, 80 SCRIPT_NAME: /view/info.php
[09-May-2022 22:48:49 Africa/Abidjan] AVideoLog::DEBUG: im_r
esizeV2: /var/www/AVideo/videos/video_220509223727_ve526/vid
eo_220509223727_ve526.jpg, /var/www/AVideo/videos/video_2205
09223727_ve526/video_220509223727_ve526_thumbsV2.jpg, 640, 3
60, 80 SCRIPT_NAME: /view/info.php
[09-May-2022 22:48:49 Africa/Abidjan] AVideoLog::DEBUG: im_r
esizeV2: /var/www/AVideo/videos/video_220509223754_v1f39/vid
eo_220509223754_v1f39.jpg, /var/www/AVideo/videos/video_2205
09223754_v1f39/video_220509223754_v1f39_thumbsV2.jpg, 640, 3
60, 80 SCRIPT_NAME: /view/info.php
[09-May-2022 22:51:52 Africa/Abidjan] AVideoLog::DEBUG: Erro
r : 1 You need a user and passsword to register SCRIPT_NAME:
 /view/index.php
[09-May-2022 22:51:52 Africa/Abidjan] AVideoLog::DEBUG: Erro
r : 1 You need a user and passsword to register SCRIPT_NAME:
 /view/index.php
[10-May-2022 01:45:37 Africa/Tripoli] AVideoLog::DEBUG: upda
teStatistic: add more [2627] to video [1] Opera SCRIPT_NAME:
 /objects/videoAddViewCount.json.php
[10-May-2022 01:46:00 Africa/Tripoli] AVideoLog::DEBUG: Star
t Login Request redirectUri=http://www.masperro.com/view/ifr
ame.php?type=log&avideoIframe=1 SCRIPT_NAME: /objects/login.
json.php
[10-May-2022 01:46:00 Africa/Tripoli] AVideoLog::DEBUG: logi
n.json.php trying to login SCRIPT_NAME: /objects/login.json.
php
[10-May-2022 01:46:00 Africa/Tripoli] AVideoLog::DEBUG: logi
n.json.php login respond something SCRIPT_NAME: /objects/log
in.json.php
[10-May-2022 01:46:00 Africa/Tripoli] AVideoLog::DEBUG: logi
n.json.php live plugin is disabled SCRIPT_NAME: /objects/log
in.json.php
[10-May-2022 01:46:00 Africa/Tripoli] AVideoLog::DEBUG: logi
n.json.php is done SCRIPT_NAME: /objects/login.json.php
[10-May-2022 01:46:01 Africa/Tripoli] AVideoLog::DEBUG: upda
teStatistic: add more [2652] to video [1] Opera SCRIPT_NAME:
 /objects/videoAddViewCount.json.php
[10-May-2022 01:46:02 Africa/Tripoli] AVideoLog::DEBUG: upda
teStatistic: add more [2653] to video [1] Opera SCRIPT_NAME:
 /objects/videoAddViewCount.json.php
[10-May-2022 01:47:55 Africa/Tripoli] AVideoLog::DEBUG: upda
teStatistic: add more [2765] to video [1] Opera SCRIPT_NAME:
 /objects/videoAddViewCount.json.php
[10-May-2022 01:48:09 Africa/Tripoli] AVideoLog::DEBUG: upda
teStatistic: add more [2780] to video [1] Opera SCRIPT_NAME:
 /objects/videoAddViewCount.json.php

**Comment by ahmedxda** [comment]
here is the guide I usually follow to install AVideo and it always work fine with me ..by the way I can delete the server and reinstall it again.. it's a test no more.. but whenever I solve this problem I will install an official version..

the guide that always work fine with me 

https://www.linuxbabe.com/ubuntu/install-avideo-youphptube-ubuntu-20-04-server

**Comment by ahmedxda** [comment]
ok Daniel, I managed to get the  error logs after a fresh installation.. I just ticked on ( don't identify by email and don't identify by username)  and cleared first page cashe ..
here are the errors log:
be\/objects\/plugin.php","line":349,"function":"readSql","cl
ass":"sqlDAL","type":"::"},{"file":"\/var\/www\/YouPHPTube\/
plugin\/AVideoPlugin.php","line":609,"function":"getAllEnabl
ed","class":"Plugin","type":"::"},{"file":"\/var\/www\/YouPH
PTube\/objects\/include_config.php","line":159,"function":"g
etStart","class":"AVideoPlugin","type":"::"},{"file":"\/var\
/www\/YouPHPTube\/videos\/configuration.php","line":47,"args
":["\/var\/www\/YouPHPTube\/objects\/include_config.php"],"f
unction":"require_once"}] SCRIPT_NAME: /view/index.php
[10-May-2022 10:31:20 UTC] AVideoLog::ERROR: [sqlDAL::readSq
l] (mysqlnd) Prepare failed again return false SCRIPT_NAME:
/view/index.php
[10-May-2022 10:31:20 UTC] AVideoLog::ERROR: MySQL ERROR: [{
"file":"\/var\/www\/YouPHPTube\/objects\/mysql_dal.php","lin
e":166,"function":"log_error"},{"file":"\/var\/www\/YouPHPTu
be\/objects\/plugin.php","line":166,"function":"readSql","cl
ass":"sqlDAL","type":"::"},{"file":"\/var\/www\/YouPHPTube\/
objects\/plugin.php","line":198,"function":"getPluginByUUID"
,"class":"Plugin","type":"::"},{"file":"\/var\/www\/YouPHPTu
be\/objects\/plugin.php","line":363,"function":"loadFromUUID
","class":"Plugin","type":"->"},{"file":"\/var\/www\/YouPHPT
ube\/plugin\/AVideoPlugin.php","line":609,"function":"getAll
Enabled","class":"Plugin","type":"::"}] SCRIPT_NAME: /view/i
ndex.php
[10-May-2022 10:31:20 UTC] AVideoLog::ERROR: [sqlDAL::readSq
l] (mysqlnd) Prepare failed: () ()  preparedStatement = "SEL
ECT * FROM plugins WHERE uuid = ? LIMIT 1" formats = "s" val
ues = ["55a4fa56-8a30-48d4-a0fb-8aa6b3fuser3"] refreshCache
= false stmt = false SCRIPT_NAME: /view/index.php
[10-May-2022 10:31:20 UTC] AVideoLog::ERROR: MySQL ERROR: [{
"file":"\/var\/www\/YouPHPTube\/objects\/mysql_dal.php","lin
e":171,"function":"log_error"},{"file":"\/var\/www\/YouPHPTu
be\/objects\/plugin.php","line":166,"function":"readSql","cl
ass":"sqlDAL","type":"::"},{"file":"\/var\/www\/YouPHPTube\/
objects\/plugin.php","line":198,"function":"getPluginByUUID"
,"class":"Plugin","type":"::"},{"file":"\/var\/www\/YouPHPTu
be\/objects\/plugin.php","line":363,"function":"loadFromUUID
","class":"Plugin","type":"->"},{"file":"\/var\/www\/YouPHPT
ube\/plugin\/AVideoPlugin.php","line":609,"function":"getAll
Enabled","class":"Plugin","type":"::"}] SCRIPT_NAME: /view/i
ndex.php
[10-May-2022 10:31:20 UTC] AVideoLog::ERROR: [sqlDAL::readSq
l] (mysqlnd) Prepare failed again return false SCRIPT_NAME:
/view/index.php
[10-May-2022 10:31:20 UTC] AVideoLog::DEBUG: plugin::getPlug
inByUUID CustomizeUser 55a4fa56-8a30-48d4-a0fb-8aa6b3fuser3
this plugin is On By Default we will install it (SELECT * FR
OM plugins WHERE uuid = ? LIMIT 1) SCRIPT_NAME: /view/index.
php
[10-May-2022 10:31:20 UTC] AVideoLog::ERROR: MySQL ERROR: [{
"file":"\/var\/www\/YouPHPTube\/objects\/mysql_dal.php","lin
e":166,"function":"log_error"},{"file":"\/var\/www\/YouPHPTu
be\/objects\/plugin.php","line":142,"function":"readSql","cl
ass":"sqlDAL","type":"::"},{"file":"\/var\/www\/YouPHPTube\/
objects\/plugin.php","line":460,"function":"getPluginByName"
,"class":"Plugin","type":"::"},{"file":"\/var\/www\/YouPHPTu
be\/objects\/plugin.php","line":185,"function":"getOrCreateP
luginByName","class":"Plugin","type":"::"},{"file":"\/var\/w
ww\/YouPHPTube\/objects\/plugin.php","line":198,"function":"
getPluginByUUID","class":"Plugin","type":"::"}] SCRIPT_NAME:
 /view/index.php
[10-May-2022 10:31:20 UTC] AVideoLog::ERROR: [sqlDAL::readSq
l] (mysqlnd) Prepare failed: () ()  preparedStatement = "SEL
ECT * FROM plugins WHERE name = ? LIMIT 1" formats = "s" val
ues = ["CustomizeUser"] refreshCache = true stmt = false SCR
IPT_NAME: /view/index.php
[10-May-2022 10:31:20 UTC] AVideoLog::ERROR: MySQL ERROR: [{
"file":"\/var\/www\/YouPHPTube\/objects\/mysql_dal.php","lin
e":171,"function":"log_error"},{"file":"\/var\/www\/YouPHPTu
be\/objects\/plugin.php","line":142,"function":"readSql","cl
ass":"sqlDAL","type":"::"},{"file":"\/var\/www\/YouPHPTube\/
objects\/plugin.php","line":460,"function":"getPluginByName"
,"class":"Plugin","type":"::"},{"file":"\/var\/www\/YouPHPTu
be\/objects\/plugin.php","line":185,"function":"getOrCreateP
luginByName","class":"Plugin","type":"::"},{"file":"\/var\/w
ww\/YouPHPTube\/objects\/plugin.php","line":198,"function":"
getPluginByUUID","class":"Plugin","type":"::"}] SCRIPT_NAME:
 /view/index.php
[10-May-2022 10:31:20 UTC] AVideoLog::ERROR: [sqlDAL::readSq
l] (mysqlnd) Prepare failed again return false SCRIPT_NAME:
/view/index.php
[10-May-2022 10:31:20 UTC] AVideoLog::ERROR: MySQL ERROR: [{
"file":"\/var\/www\/YouPHPTube\/objects\/mysql_dal.php","lin
e":166,"function":"log_error"},{"file":"\/var\/www\/YouPHPTu
be\/objects\/userGroups.php","line":145,"function":"readSql"
,"class":"sqlDAL","type":"::"},{"file":"\/var\/www\/YouPHPTu
be\/plugin\/CustomizeUser\/CustomizeUser.php","line":56,"fun
ction":"getAllUsersGroupsArray","class":"UserGroups","type":
"::"},{"file":"\/var\/www\/YouPHPTube\/plugin\/Plugin.abstra
ct.php","line":142,"function":"getEmptyDataObject","class":"
CustomizeUser","type":"->"},{"file":"\/var\/www\/YouPHPTube\
/objects\/plugin.php","line":470,"function":"getDataObject",
"class":"PluginAbstract","type":"->"}] SCRIPT_NAME: /view/in
dex.php
[10-May-2022 10:31:20 UTC] AVideoLog::ERROR: [sqlDAL::readSq
l] (mysqlnd) Prepare failed: () ()  preparedStatement = "SEL
ECT * FROM users_groups as ug WHERE 1=1 " formats = "" value
s = [] refreshCache = false stmt = false SCRIPT_NAME: /view/
index.php
[10-May-2022 10:31:20 UTC] AVideoLog::ERROR: MySQL ERROR: [{
"file":"\/var\/www\/YouPHPTube\/objects\/mysql_dal.php","lin
e":171,"function":"log_error"},{"file":"\/var\/www\/YouPHPTu
be\/objects\/userGroups.php","line":145,"function":"readSql"
,"class":"sqlDAL","type":"::"},{"file":"\/var\/www\/YouPHPTu
be\/plugin\/CustomizeUser\/CustomizeUser.php","line":56,"fun
ction":"getAllUsersGroupsArray","class":"UserGroups","type":
"::"},{"file":"\/var\/www\/YouPHPTube\/plugin\/Plugin.abstra
ct.php","line":142,"function":"getEmptyDataObject","class":"
CustomizeUser","type":"->"},{"file":"\/var\/www\/YouPHPTube\
/objects\/plugin.php","line":470,"function":"getDataObject",
"class":"PluginAbstract","type":"->"}] SCRIPT_NAME: /view/in
dex.php
[10-May-2022 10:31:20 UTC] AVideoLog::ERROR: [sqlDAL::readSq
l] (mysqlnd) Prepare failed again return false SCRIPT_NAME:
/view/index.php
[10-May-2022 12:37:47 Africa/Tripoli] AVideoLog::DEBUG: im_r
esizeV2: /var/www/YouPHPTube/videos/cache/_jpg_627a407b325a7
.jpg, /var/www/YouPHPTube/videos/cache/og_200X200.jpg, 200,
200, 100 SCRIPT_NAME: /view/index.php

eos/avideo.log

**Comment by DanielnetoDotCom** [comment]
> don't identify by email and don't identify by username

I did the same as you and my page is showing fine.

I suspect you are not on the latest version, did you install it using the `git clone` command?


Regarding the server 

`AVideoLog::ERROR: [sqlDAL::readSql] (mysqlnd) Prepare failed: () () preparedStatement = "SELECT * FROM plugins WHERE uuid = ? LIMIT 1" formats = "s" values = ["55a4fa56-8a30-48d4-a0fb-8aa6b3fuser3"] refreshCache= false stmt = false SCRIPT_NAME: /view/index.php`

It seems to me your MySQL is crashing.

maybe you do not have enough memory to run it.

what is your server configuration? is it a VPS or dedicated?

is it a shared server (if yes, it is not recommended)

**Comment by DanielnetoDotCom** [comment]
![chrome-capture-2022-4-10](https://user-images.githubusercontent.com/18009293/167649999-802a4220-9ff9-4c9b-bc8b-a2082bbe544b.gif)

**Comment by ahmedxda** [comment]
my server is AMAZON EC2  4 giga ram  2 cpu  120 giga storage..
and I used to install AVideo on a lower resources server and it worked smoothly ...
now I don't know what happened .. I follow the sames procedures to install AVideo but it crashes and got problems such as continuous loging out , force autoplay videos while I ticked it  false and some other problems

**Comment by ahmedxda** [comment]
I followed your guide to install AVideo on ubunto 20... I tried other tutorials and ended in the same problem..
do I miss something?
I even tried php8.1 and php4 .. I realy don't know what to do..

**Comment by ahmedxda** [comment]
> you should follow this
> 
> https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x-for-AVideo-Platform-version-11.x-or-newer

I followed all the commands from the beginning to "sudo apt-get install --reinstall zlibc zlib1g zlib1g-dev -y"  the commands aftrer that I thought it's  for nginx users ,however  I tried to use all commands to the end but no luck..
ok Daniel I will give it another try and install using all the commands provided not excluding a single command although I did that before.

**Comment by ahmedxda** [comment]
> ![chrome-capture-2022-4-10](https://user-images.githubusercontent.com/18009293/167649999-802a4220-9ff9-4c9b-bc8b-a2082bbe544b.gif)

After I "clear first page cache " the  website goes down but to be clear this happens after fresh installation...
in order to get my website alive, I wait few minutes after rebooting my EC2 instance and log into phpmyadmin to change the value of "don't identify by email and don't identify by username _ to be false..
once I do that, the website get back to life again but with errors in loging out the user... errors when I edit my personal account in the field of email which I have to fill the fields of username and email with an email in both fields!
also videos automatically autoplay although I didn't enable it in setting..
some errors in playlists..
what leading me crazy is that:
Your script is marvelous and takes only 5 minutes to install!!
I was having fun installing the script..I even keep in heart the procedures and rarely look at the installation tutorial!!

About you Daniel;
I think you're a great guy made a great script..
and honestly you over a paid help in case it's not because errors in your script ..
really thanks for the great script  and I hope you provide me with some "free" help if possible telling me why my website crashes. 🤍

**Comment by DanielnetoDotCom** [comment]
thanks, I hope you enjoy the script?

**Comment by ahmedxda** [comment]
> thanks, I hope you enjoy the script?



> you should follow this
> 
> https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x-for-AVideo-Platform-version-11.x-or-newer

I have just now followed this tutorial installing AVideo on a fresh EC2 instance,  after installation finished I ticked on "dont identify by email and don't identify by username " immediately the website went down 😪

**Comment by DanielnetoDotCom** [comment]
I have no idea.

I just did a new installation and did the same. 

the site still running
