### ISSUE TITLE
Broadcast scheduling

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#6574]
Greetings
Can you please explain what
remember me means

![תזמון שידור 8](https://user-images.githubusercontent.com/85537931/167704685-f31c803b-0f3e-4243-abe7-725ad8f555fe.jpg)

I understand that if you download the file
It's associated with my diary
But what does it mean to turn on the reminder button?
Should I receive an email?
I checked these options and did not receive a reminder email
I would appreciate it if you would sharpen this matter

eitan - live528

**Comment by DanielnetoDotCom** [comment]
this feature is about this

https://github.com/WWBN/AVideo/issues/6542#issuecomment-1122556548

**Comment by eitanwa** [comment]
thanks so much

**Comment by guymass** [comment]
Everything is working now, thanks!, Eitan will close this post soon.

**Comment by eitanwa** [comment]
Thank you
working now
