### ISSUE TITLE
Home page loading delay

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#6576]
Greetings Mr @DanielnetoDotCom  please help me reduce the homepage loading speed because it takes almost a minute or more to display videos and photos. Where can I reduce the the loading speed to less seconds.
![Screenshot_20220511_120819](https://user-images.githubusercontent.com/72950503/167826517-68d96ace-e328-4ab1-a099-7c8ec3b9d3ca.jpg)

**Comment by DanielnetoDotCom** [comment]
Please check your logs, 

you may find a clue about what is consuming your server.

also as a tip, 

disable the audit plugin if you do not need it
if your live is not working correctly or if you are not using disable it too
check if you have bad livelinks
