### ISSUE TITLE
Remote Live - app not found

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#6577]
Going to setup multiple live servers but having trouble getting 1st remove live server to work. All config files and error logs (nginx and avideo) are attached. Stats works, display of phpinfo on remote live works, but can't live stream from AVideo. Checked and doubled checked server URL and stream key for OBS, they are correct.

![OBS Error](https://user-images.githubusercontent.com/85363361/167899063-bb0035b4-368c-4884-b956-581761f95260.jpg)
![phpinfo](https://user-images.githubusercontent.com/85363361/167899065-0e7d9a55-1c64-4a64-bdef-c98ee838b89e.jpg)
![TestFromAVideo](https://user-images.githubusercontent.com/85363361/167899069-b2af8b48-6759-42b3-b29e-477a458e479f.jpg)
[avideo.log.pdf](https://github.com/WWBN/AVideo/files/8671706/avideo.log.pdf)
[control.json.php.pdf](https://github.com/WWBN/AVideo/files/8671707/control.json.php.pdf)
![Live-RemoteConfig](https://user-images.githubusercontent.com/85363361/167899077-67458f29-2f0a-4933-9745-a4b33f91af41.jpg)
[nginx.conf.pdf](https://github.com/WWBN/AVideo/files/8671708/nginx.conf.pdf)
[nginx.error.log.pdf](https://github.com/WWBN/AVideo/files/8671709/nginx.error.log.pdf)

**Comment by GreenDragonTavern** [comment]
Added rtmp and http server configs..
[rtmp.conf.pdf](https://github.com/WWBN/AVideo/files/8671745/rtmp.conf.pdf)
[http.conf.pdf](https://github.com/WWBN/AVideo/files/8671746/http.conf.pdf)
.

**Comment by DanielnetoDotCom** [comment]
I guess your RTMP should be rtmp://stream1.ourfreenation.org/live 
NOT rtmp://stream1.ourfreenation.org/

![image](https://user-images.githubusercontent.com/18009293/167919047-e3f86edb-5bb6-4cd0-99c6-78dac5ec93e9.png)

**Comment by jengajenga** [comment]
I would suggest you stop using FPM/FastCGI and change to Apache Handler. you will face issues when using the app.

**Comment by GreenDragonTavern** [comment]
Daniel, disabled Protect Live and this time it showed Offline entire stream. It is recording properly, and after completion, VOD shows up in AVideo properly. The live stream itself doesn't show in AVideo (just the Offline image) though...any thoughts as to why?

**Comment by DanielnetoDotCom** [comment]
No idea. but I suspect it is something regarding your SSL

I will need more info about what you are doing and logs.

please open a new issue regarding this new problem

**Comment by GreenDragonTavern** [comment]
Roger that, and will close this.
