### ISSUE TITLE
Embed a PayPal button code to quota packages

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6580]
We wish to use our paypal to allow the purchase of quota packages. Currently PayPal will give us a code like this:

```
<div id="paypal-button-container-P-8BN83455JG197344B*******"></div>
<script src="https://www.paypal.com/sdk/js?client-id=AY05zsfeVPvobNuNiGV-3C9E4rqJ9CDZocLWgbSMh8Ikd9S_79sFyx4ZifoImKjl_b3rfyG0*******&vault=true&intent=subscription" data-sdk-integration-source="button-factory"></script>
<script>
  paypal.Buttons({
      style: {
          shape: 'rect',
          color: 'gold',
          layout: 'vertical',
          label: 'subscribe'
      },
      createSubscription: function(data, actions) {
        return actions.subscription.create({
          /* Creates the subscription */
          plan_id: 'P-8BN83455JG197344B*******'
        });
      },
      onApprove: function(data, actions) {
        alert(data.subscriptionID); // You can add optional success message for the subscriber here
      }
  }).render('#paypal-button-container-P-8BN83455JG197344B*******'); // Renders the PayPal button
</script>

```
We would like to know how and where we can embed this code so that purchasing quota will go through paypal at least until we find a better service/solution. 

Can it be done?

**Comment by eitanwa** [comment]
Following Guy's question
Is it possible to embed a link in the subscribe button?
Or alternatively hide it?

![image](https://user-images.githubusercontent.com/85537931/168124627-9a10958a-1aad-48ba-b59f-73917039df6e.png)


Because we can not use stripe
We are looking for an alternative way to charge people

**Comment by DanielnetoDotCom** [comment]
No it is not possible

this button requires an API, also it will be a recurrent payment. so we also need a webhook. 

in other words, this is not that simple

**Comment by guymass** [comment]
What about just adding a text area where we can insert the code below it? We need help to find a way to work with the quota other wise we have no other way of charging people through this plugin.

Another solution maybe to extend the paypal plugin to allow paypal code embeds. Honestly we don't know what else to do and we cannot go ahead with the platform and make it earn income.

**Comment by DanielnetoDotCom** [comment]
The best idea would be to add the PayPal option

It will be added in the future but there is no ETA.

if you need this now you can sponsor this feature and I may be able to finish it in 3 to 4 weeks

If you want to sponsor it you can email me at developer@youphptube.com

**Comment by guymass** [comment]
I sent you mail.
