### ISSUE TITLE
How to Move Bulk Videos to New Storage Sites

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#6583]
How to Move Bulk Videos to New Storage Sites

**Comment by DanielnetoDotCom** [comment]
Hi

what exactly do you mean?

can you please give more details about what you are doing?

**Comment by chenjian9885** [comment]
Cumbersome when many videos need to be moved to other storage sites
![image](https://user-images.githubusercontent.com/47063171/168486671-9ac1f22f-52d8-4d48-953f-a878c68f5a55.png)

**Comment by chenjian9885** [comment]
Hope it can be done in batches

**Comment by DanielnetoDotCom** [comment]
Hi

you should be able to select multiple videos and than click on the storage at the top to move all of them 

![image](https://user-images.githubusercontent.com/18009293/168587283-34a86d7f-dc41-4033-a9e5-7a9053a5bf63.png)

**Comment by chenjian9885** [comment]
Okay thank you!
