### ISSUE TITLE
NGNIX Windows

### ISSUE THREAD

**Issue by whizardmagic** [WWBN/AVideo#6585]
[notice] 8768#11164: Access to sockapi succeded!
2022/05/14 11:52:09 [notice] 8768#11164: using sockapi from "4;148;"
2022/05/14 11:52:09 [notice] 14668#7240: sockinit() attempting to access sockapi
2022/05/14 11:52:09 [notice] 14668#7240: Access to sockapi succeded!
2022/05/14 11:52:09 [notice] 14668#7240: using sockapi from "4;8;"
2022/05/14 12:05:14 [error] 8768#14324: *3 CreateFile() "C:/nginx/srv/viewer.html" failed (3: The system cannot find the path specified), client: 73.173.207.208, server: , request: "GET /viewer.html HTTP/1.1", host: "73.173.207.208"
2022/05/14 12:05:14 [error] 8768#14324: *3 CreateFile() "C:/nginx/srv/favicon.ico" failed (3: The system cannot find the path specified), client: 73.173.207.208, server: , request: "GET /favicon.ico HTTP/1.1", host: "73.173.207.208", referrer: "http://73.173.207.208/viewer.html"
2022/05/14 12:06:01 [error] 8768#14324: *4 CreateFile() "C:/nginx/srv/viewer.html" failed (3: The system cannot find the path specified), client: 192.168.0.6, server: , request: "GET /viewer.html HTTP/1.1", host: "192.168.0.6"
2022/05/14 12:06:01 [error] 8768#14324: *4 CreateFile() "C:/nginx/srv/favicon.ico" failed (3: The system cannot find the path specified), client: 192.168.0.6, server: , request: "GET /favicon.ico HTTP/1.1", host: "192.168.0.6", referrer: "http://192.168.0.6/viewer.html"
2022/05/14 12:08:36 [error] 8768#14324: *5 CreateFile() "C:/nginx/srv/viewer.html" failed (3: The system cannot find the path specified), client: 192.168.0.6, server: , request: "GET /viewer.html HTTP/1.1", host: "192.168.0.6"
2022/05/14 12:08:47 [notice] 6376#6972: signal process started (quit)
2022/05/14 12:08:56 [notice] 10328#252: signal process started (quit)
2022/05/14 12:08:56 [error] 10328#252: CreateFile() "C:\ngnix/logs/nginx.pid" failed (2: The system cannot find the file specified)
2022/05/14 12:08:57 [emerg] 3028#4276: CreateDirectory() "/nginx/srv/hls/" failed (3: The system cannot find the path specified)

Why isn't it making its own directory?   I don't know anything about NGNIX. How can I fix in config file?  

How do I fix it?  Much appreciated.   Thanks very much!!

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by GreenDragonTavern** [comment]
Hello and below may be of assistance:
[Hardware, Software requirements for AVideo](https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements)
[Setting up your own Live Streaming Server](https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server)

**Comment by whizardmagic** [comment]
Posted above.. Thanks

**Comment by whizardmagic** [comment]
Its not letting ngnix create dir in c: ngnix/srv/hls.       I created a folder just in c: hls its works but I cant access video.

**Comment by whizardmagic** [comment]
I just got it working I believe. I don't know what it was, I was just messing with dir path. It was right, I retyped it back in. Maybe just a glitch. Let me keep testing before closing this.  Thanks very much. Been messing with this for days.

**Comment by whizardmagic** [comment]
It seems to be working!!  Thanks!!
