### ISSUE TITLE
Scrolling the page

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#6588]
Hey
Can not scroll from the video area
This is the case throughout the entire site, whether in live broadcasts or videos
You can scroll only from the "outside the video" area

I hope the picture will explain
The areas where there is a raised finger are the areas that can be scrolled
In the area where the x appears it is not possible

![image](https://user-images.githubusercontent.com/85537931/168619160-5cac8c94-9e93-4599-9d02-06826eee8259.png)

**Comment by DanielnetoDotCom** [comment]
sorry this is not clear for me

can you please send a link so I can try to reproduce here?

**Comment by eitanwa** [comment]
OK
I will try to clarify
The page cannot be scrolled up or down with the mouse scroll
When the mouse cursor is in the video area

image

What I'm trying to show in the picture using the finger icon
The area where the page cannot be scrolled
And that's from the video page and also from the broadcast page

https://alive528.com/live/0/News

https://alive528.com/v/3534?page=1

**Comment by guymass** [comment]
What Eitan means is that when the mouse is on the video area and you want to scroll down the page it will not work, you will need to move the mouse out of the video area in order to be able to scroll. Scrolling should work even if the mouse is on the video, this should be simple to fix.

**Comment by DanielnetoDotCom** [comment]
Disable the plugin hotkeys

**Comment by eitanwa** [comment]
hey
great, works
thanks
