### ISSUE TITLE
Here is Fix to NGINX stats page showing IP addresses in source 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6591]
This is a security issue and is getting live streamers ddos'ed. Need a way for the NGINX stats page to not show the IP addresses of the streamers.

When you go to https://live.joshwhotv.com:444/stats   and view page source you can still see the ip addresses of the streamers.

![00c8d7ec-b5dc-415a-a9d9-97863c5b7d7d](https://user-images.githubusercontent.com/39392449/168681572-9d2b94f3-d394-422b-b9cf-8e0cd8e8005e.png)

**Comment by JoshWho** [comment]
Solution I used was

Add deny all and only allow your server ip to see it in the nginx config

 ```
#allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                     allow 127.0.0.1;
                     allow 198.x.x.exampleip;
                     
                            deny all;

```

**Comment by JoshWho** [comment]
It's not really a bug just more a security suggestion that should be applied to all installs.

**Comment by DanielnetoDotCom** [comment]
I did some research and currently, I am not finding any way to hide it.

this is an Nginx configuration, maybe you want to ask about it on their project.

https://github.com/arut/nginx-rtmp-module

**Comment by JoshWho** [comment]
The deny all works fine for a fix. Just saying to add this to the instructions for install . That way outsiders can't see the stats page.

```
#allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                   #location /stats {
                   #        stub_status;
                   #}
                   location /stat {
                    allow 127.0.0.1;
                    allow 198.x.x.exampleip;
                    
                           deny all;


```
