### ISSUE TITLE
Autopost on facebook

### ISSUE THREAD

**Issue by partystreamsk** [WWBN/AVideo#6592]
Hello @DanielnetoDotCom 

Its possible to add a plugin like autopost plugin for twitter for facebook too?
![autopost](https://user-images.githubusercontent.com/50631455/168693364-5e82032a-fb4d-41da-aa7f-f8969ab77cdc.png)

**Comment by DanielnetoDotCom** [comment]
Hi, it is probably possible, but it is not on the roadmap for development.

if you need this now you can hire me to add this option.

**Comment by partystreamsk** [comment]
how much for this option?

**Comment by DanielnetoDotCom** [comment]
please email me for a quote
