### ISSUE TITLE
Full screen / theater screen mode-of articles

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#6595]
hey

Is there an option in the articles
Get into theater screen mode or full screen mode as you can in videos?
Currently the only option to switch to  theater screen mode full screen
That's if I did it before in one of the videos

This is the compressed state
![image](https://user-images.githubusercontent.com/85537931/168763376-072295c2-c745-43ed-9b0a-1794a3d016ea.png)

this is theater screen mode
That I was allowed to change to
Only when I changed to this mode in one of the videos

![image](https://user-images.githubusercontent.com/85537931/168763952-78410f55-69b5-440f-8da1-c9b0b9e8c546.png)

eitan live528

**Comment by DanielnetoDotCom** [comment]
With this new update, you may have the compress and expand button on the action toolbar


![chrome-capture-2022-4-17 (1)](https://user-images.githubusercontent.com/18009293/168869420-74fb4335-cb14-4dbd-81de-d155f609daf9.gif)

**Comment by eitanwa** [comment]
works fine thanks
