### ISSUE TITLE
Bug on the go live screen

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#6598]
Hey
Bug on the go live screen
Sending video
Where I try using the mouse cursor to show you the problem
Hope it is understandable
eitan live528

Here

![image](https://user-images.githubusercontent.com/85537931/168862874-e900c9c8-6398-4c2e-b443-989f7f80a67f.png)

https://user-images.githubusercontent.com/85537931/168862900-2d072ea8-dd15-4588-9b52-55cea2ed6c5e.mp4

**Comment by guymass** [comment]
The text saying "Load More" can only be seen if we maximize the window. Also I have seen a chat replay in that webcam window, not sure if it should be there but also the date in the chat bubbles says its "Invalid Date", maybe should be on separate post.


![Screen Shot 5782-09-16 at 19 52 14](https://user-images.githubusercontent.com/58882903/168867845-57adc863-e715-4fe6-b254-4f0cb99285f4.jpg)

**Comment by eitanwa** [comment]
Following Guy's comment


![image](https://user-images.githubusercontent.com/85537931/168870567-8566cd8d-e741-40a7-96ce-f336f10b7849.png)
