### ISSUE TITLE
User showing OFFLINE when I know he is ONLINE why?

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6600]
We have noticed that a channel is showing OFFLINE status when we know it is online. How can we check why this status is miss behaving? Or is this status only referring to when they are streaming?
![Screen Shot 5782-09-16 at 21 32 45](https://user-images.githubusercontent.com/58882903/168885917-b82a1464-824f-4b4b-bcbb-0a3035e9f571.jpg)

**Comment by DanielnetoDotCom** [comment]
this online, means the user is online, NOT the live.

maybe I need 2 different online signs (for user and for the live)
