### ISSUE TITLE
Incorrect indication

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#6601]
hey

Why do I get an indication that the channel is not Online
Although it is?
Is it also related to the issue of non-chat dates?

I think this is also the reason why the call sign cannot be seen on the channel itself either
Image from the channel screen
![image](https://user-images.githubusercontent.com/85537931/168884946-cf5b6e8a-8d80-442e-b76f-9e388997d33d.png)

In practice the channel is online
Image from the browse channels screen
And here too there is an indication that he is indeed so
![image](https://user-images.githubusercontent.com/85537931/168885367-62d91748-c9aa-4344-9e87-6e154962a0e8.png)

****There are no dates in chat****

![image](https://user-images.githubusercontent.com/85537931/168885525-e0eae9dd-9b67-49a1-9220-57f5e3a4590a.png)
thanks 

eitan live528

**Comment by guymass** [comment]
Sorry we opened a post each, you merge mine here:
https://github.com/WWBN/AVideo/issues/6600

**Comment by DanielnetoDotCom** [comment]
you guys are duplicating and sometimes triplicating the same issue. 

this does not help me to resolve,

I will close them now and please open one issue per error and do not duplicate them, otherwise I will be wasting time responding them

**Comment by guymass** [comment]
sorry, we will recheck between the team before.
