### ISSUE TITLE
Channel status is OFFLINE when should be ONILNE

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6602]
We are seeing that a channel who I know is ONLINE is showing me an OFFLINE status. On other sites of AVIDEO we have seen a status like so:
![photo_2022-05-17 21 45 55](https://user-images.githubusercontent.com/58882903/168887754-b5f9a76c-91c4-43e5-b136-7b0931fc74e8.jpeg)

On my site it appears like this:
![Screen Shot 5782-09-16 at 21 32 45](https://user-images.githubusercontent.com/58882903/168887821-85b14ea5-eb99-4f0c-929d-a35d230f06bb.jpg)

And I know the user is ONLINE. 

So what do I need to look at to debug this issue? as I want to have the same status showing on the page with the ability to call the user.

**Comment by guymass** [comment]
Socket seems to be running.

![Screen Shot 5782-09-16 at 21 51 34](https://user-images.githubusercontent.com/58882903/168888493-05d59c57-133b-4640-acdf-b72755afd5f1.jpg)

**Comment by DanielnetoDotCom** [comment]
try to clear the cache and refresh both pages (yours and the user)

**Comment by guymass** [comment]
I have done many times including mine. Here is a strange thing. I am online and connected, My channel page shows this:
![photo_2022-05-17 21 59 18](https://user-images.githubusercontent.com/58882903/168890027-62093e1f-f105-442b-92b1-7af065da417d.jpeg)


However on the Channels List page I am listed as Online:
![photo_2022-05-17 21 59 22](https://user-images.githubusercontent.com/58882903/168890106-8f3acd30-0be4-40a6-bc91-cbc7d932e751.jpeg)

**Comment by guymass** [comment]
This is my console:
![Screen Shot 5782-09-16 at 22 07 39](https://user-images.githubusercontent.com/58882903/168891297-61dad956-9527-4eca-9688-0a393560b681.jpg)

**Comment by DanielnetoDotCom** [comment]
can you please check if this update resolves?

**Comment by guymass** [comment]
Yes it did, thank you very much it working now.
