### ISSUE TITLE
Roku Channel

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#6603]
We're trying to create a Roku channel that will include all our live streamers so our users won't need to create their own channels (of course they can if they want to).

If using a category json it works fine but for live streams none of the json urls work

When we add the json feed for livestreams it doesn't work see the below results

Feed URL: [https://site.com/roku.json?catName=live-tv]

1 item has an error: No valid items were found in the feed: validate

1 item has an error: Required playlist itemId array is missing or empty.

Or
Feed URL[https://site.com/plugin/API/get.json.php?APIName=livestreams]

    Required property providerName is missing.
    05/17/2022 05:10PM
    Required property lastUpdated is missing or not in ISO 8601 format.
    No valid items were found in the feed: validate

    Required property providerName is missing.
    05/17/2022 05:09PM
    Required property lastUpdated is missing or not in ISO 8601 format.
    No valid items were found in the feed: validate

    Required property providerName is missing.
    05/17/2022 05:01PM
    Required property lastUpdated is missing or not in ISO 8601 format.
    No valid items were found in the feed: validate

**Comment by ganddser** [comment]
Yes this URL,  https://site.com/roku.json?catName=live-tv - returns these errors

1 item has an error: No valid items were found in the feed: validate

1 item has an error: Required playlist itemId array is missing or empty.

**Comment by DanielnetoDotCom** [comment]
seems to me you only add lives to this category

the Roku feed loads only VOD videos, currently, we have no support to live videos.

so the error is clear to me you are adding an empty category

<img width="372" alt="image" src="https://user-images.githubusercontent.com/18009293/169065079-8c70715c-3c41-4d6c-a553-f1517af207f5.png">


also, I am not sure if Roku support live videos

**Comment by DanielnetoDotCom** [comment]
Ok, I may add the live feed in the future, but for now, it only support VOD videos
