### ISSUE TITLE
Can’t connect to server live stream

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6605]
Using Obs 27.2.4 saying it can’t connect to server
It was fine a week ago.

![7E2F5C06-7218-4726-B90D-0B63809D9162](https://user-images.githubusercontent.com/58601786/168930421-e4cbb737-5b77-429a-aad9-0f92a29fabbc.png)

**Comment by DanielnetoDotCom** [comment]
For some reason, your Nginx was stopped

I just start it with the command  `/usr/local/nginx/sbin/nginx`

try to connect now

**Comment by barrunning** [comment]
Good to go
