### ISSUE TITLE
WEBSITE WILL NOT LOAD

### ISSUE THREAD

**Issue by naluv4u2** [WWBN/AVideo#6606]
I cannot open my website for domain http://biggsexxxy.com

**Comment by DanielnetoDotCom** [comment]
your server expired 2022-04-25

I have sent you a couple of emails warning you (April 20th)

then on may 3th

you have never responded or paid the renewed invoice.

you have paid the invoice on May 15th, but it was too late, so I already refunded you.

Sorry but all your data is lost now.

**Comment by naluv4u2** [comment]
I need PROOF.  SHOW ME THE EMAILS YOU SENT AND WHERE YOU SENT THEM TO.  I need to see copies of the emails you sent me.  I believe you are just trying to get rid of the people you offered yearly hosting services to because getting people to pay the same price monthly is so much more lucrative. In my opinion it is pure greed and you could not be more evil getting rid of all my data.  You could have at least offered me a backup copy.

**Comment by DanielnetoDotCom** [comment]
I am sure you found the email because you paid the link, but it was too late (20 days later)

I could not offer you anything because you have never responded to me.

anyway, here are the proves 

![image](https://user-images.githubusercontent.com/18009293/169167853-28062788-88e4-4c67-bc3a-b0b94ea39516.png)

![chrome-capture-2022-4-18](https://user-images.githubusercontent.com/18009293/169167868-e118160c-83df-416a-bed8-e0b1f351a18c.gif)

**Comment by naluv4u2** [comment]
I never found the old emails because I never correspond from ***@***.***  That is EXCLUSIVELY an email address I use for PayPal and PayPal only.  ALL OTHER CORRESPONDENCE I'VE EVER USED WITH YOU WERE EITHER FROM ***@***.*** or this one ***@***.***  When I could not longer contact you on the developer email address that your were contacting me from I went into a panic.  That is the mix up.  You got that email from PayPal and NOWHERE else otherwise I would have gotten them.  I never use that email address to correspond and you don't even see that on my videos on the website.  Its unfortunately you can be so cold as to tell a person years of their life has gone poof due to a email mix up.  This is devastating and heartbreaking as I thought I found a fair and honest person in the website business.  But I see you are just like all the rest who greedily make people pay expensive monthly rates instead of more affordable yearly rates.  Not because it is necessary but simply because you can because most people are not tech savvy to know the difference.
________________________________

**Comment by naluv4u2** [comment]
The only reason I even knew there was problem with my website is when I began getting errors from Stripe.

Here are my screenshots.  I NEVER corresponded with you from the ***@***.*** EVER!

05.18.2022-21.29.51 (screencast.com)<https://www.screencast.com/t/eXWXAFck78>
[https://tscscreencastlive.blob.core.windows.net/uploads/g000301NgQbmpFFmlchTShi99tuJz/thumbnail.jpg?sv=2019-07-07&sr=b&sig=8YQHvdqrZCZjVAz6fsznlMeh0LdSB9tEX347cK9H7TE%3D&st=2022-05-19T02%3A25%3A42Z&se=2022-05-20T02%3A30%3A42Z&sp=r]<https://www.screencast.com/t/eXWXAFck78>
05.18.2022-21.29.51<https://www.screencast.com/t/eXWXAFck78>
Shared from Screencast.com
www.screencast.com

05.18.2022-21.42.03 (screencast.com)<https://www.screencast.com/t/DlS8IT5d8s>


[https://tscscreencastlive.blob.core.windows.net/uploads/g000301lXY2kyuWqjjg2HhGiFTzaX/thumbnail.jpg?sv=2019-07-07&sr=b&sig=KV8UzBsmkQ5gI5BMhTPrX9nRw6lVH%2BvL4StVLy38QiQ%3D&st=2022-05-19T02%3A38%3A19Z&se=2022-05-20T02%3A43%3A19Z&sp=r]<https://www.screencast.com/t/DlS8IT5d8s>
05.18.2022-21.42.03<https://www.screencast.com/t/DlS8IT5d8s>
Shared from Screencast.com
www.screencast.com

________________________________

**Comment by DanielnetoDotCom** [comment]
I am sorry about what happened and I understand your side.

when you sent the payment I tried to recover the server but it was too late

FYI before delete the server the server remains 3 days suspended/offline but you pass too many days without any type of contact 

there is nothing I can do now

**Comment by naluv4u2** [comment]
At least you are human enough to admit you understand MY side. You destroyed all my dreams. I can never get my time and energy back and now I am an old woman defeated. The only thing I am sorry about is not being my own hero by having my own server. Server costs are such a fraud and ripoff and I will tell my whole story on social media, YouTube, Facebook,  Instagram and to anybody who will listen to AVOID doing business with you. I don't want people to think I am a con artist because you got rid of my data. I hope they can understand how you destroyed my life with an email miscommunication and that tech people literally have too much power in their hands because they feed like predators on the common person's ignorance about technology.

The fact that you will not even offer an alternative way to resolve our issue tells me you really don't care about how this affects my life so long as your life continues with wealth and possibilities because you can EASILY get rid of your yearly subscribers and exchange them for people paying same price MONTHLY. Must be a good life to never have to suffer bad consequences for what I consider neglect and bad business practices. I never told you my contact information was through live.com yet now I have to suffer from YOUR miscommunication.

Its a shame people in poverty like me have to suffer the most no matter how hard they work. At least you taught me a life lesson. I will never trust my life to a person out of the country who does not care about me beyond the money. I will also educate myself and others about how servers work so I do not get ripped off again.  I will be my own hero and pursue hosting my website on a server that belongs to me instead of trusting greedy people like you so I can never be violated like this again in the future by YOU or anyone else. This is pure evil and do not wish this experience on my worst enemy.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
