### ISSUE TITLE
Two asthetic changes requested

### ISSUE THREAD

**Issue by FFCTV** [WWBN/AVideo#6608]
I tried to overwrite a background.png via overwrite w/ FTP. Permission denied. Blue checker image is the .png:
![replace-blu](https://user-images.githubusercontent.com/105749323/169063386-37849180-e22b-488b-80dd-77f3adb56e55.JPG)
The next thing I request is to place a graphic in the header that will link to our home page https://ffctv.info
![put-logo](https://user-images.githubusercontent.com/105749323/169063715-deb7fc9e-7cd0-4575-8ffb-024d05eb58c8.JPG)

**Comment by DanielnetoDotCom** [comment]
you are not supposed to use FTP and upload anything.

if you want to change the color you MUST use CSS (also you need to know what to do)

check this https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript
