### ISSUE TITLE
Invalid Date on Chat2 bubbles

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6615]
I got this message on all chat bubbles indicating an "Invalid Date", not sure if its a bug or maybe something in our translation file maybe, here is a screenshot:
![Screen Shot 5782-09-18 at 21 39 35](https://user-images.githubusercontent.com/58882903/169376285-d7b8a972-43c0-49ba-bfb9-ec90bd81fbc8.jpg)

**Comment by DanielnetoDotCom** [comment]
this update should fix the invalid date

**Comment by DanielnetoDotCom** [comment]
Also I am sending a new chat, version 10.5 with better time improvements

**Comment by guymass** [comment]
OK great much thanks I will check after the update.

**Comment by guymass** [comment]
After updating the plugin the date is now fixed. much thanks.
