### ISSUE TITLE
[Request] on /mvideos, a count of number of downloads

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6618]
**Is your feature request related to a problem? Please describe.**
Some of my files are zip archives. I'd like to know how many downloads they get.

**Describe the solution you'd like**
On /mvideos page a column for number of downloads. It can default to off, its not a normal use case.

**Comment by DanielnetoDotCom** [comment]
can you please screenshare what exactly are you referring to and where are your uses downloading from?

**Comment by walt93** [comment]
![12965130-BDAE-4616-ACF7-65AA60099F1D](https://user-images.githubusercontent.com/11711050/170446710-ee1dcb3b-fcbe-421d-b68d-fff8988c4952.jpeg)

![4B7FEB42-7AF0-48A7-B199-AFEEDFE8DBC4](https://user-images.githubusercontent.com/11711050/170447700-2e31e551-b38e-4b6d-a7db-4aa8c51f1ac6.jpeg)

Also please see this link and try to access the download link. You will see a huge bug my users have been asking about. https://conspyre.tv/video/10161/biden-laptop-emails-all-windows

**Comment by DanielnetoDotCom** [comment]
I did test and it works fine, 

the only thing I saw is that your zip file has a lot of files in it, and it creates a huge list.

I will send an update to list max 100 files

**Comment by DanielnetoDotCom** [comment]
Actually, I just sent an update to limit it to display 15 files,, so it will fit better on the screen

**Comment by walt93** [comment]
Awesome, thank you - that fixes the issue! :)

Other question was more of a feature request, can we track the number of downloads? It would be useful as a column in /mvideos.
