### ISSUE TITLE
Scheduler Error in log

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6620]
I see this error in log regarding the Scheduler, I am not sure if this is a bug of something on our side, can you please confirm what this error indicate?
![Screen Shot 5782-09-19 at 13 43 37](https://user-images.githubusercontent.com/58882903/169511968-04aa271b-6459-44e2-a0cf-37261049089f.jpg)

**Comment by DanielnetoDotCom** [comment]
depends if you find any problem.

this log isolated means nothing.

**Comment by guymass** [comment]
OK thanks, as I am not getting feedback on error from my users I don't know sometime if this may cause an issue I am not aware of. I will close this post.
