### ISSUE TITLE
Thumbnail and description in link sharing

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6622]
Hi @DanielnetoDotCom,

I would suggest implementing meta tag provisioning in link sharing. See the example below when I share a link through Whatsapp. The thumbnail or description of the video does not appear.

https://cnetv.com.br/v/122
![image](https://user-images.githubusercontent.com/37880073/169590873-444d9af9-af76-4280-8edf-1923c8194beb.png)

https://cnetv.com.br/video/122/o-setimo-selo
![image](https://user-images.githubusercontent.com/37880073/169591016-1171149a-1a62-4c3b-bf2f-2c444f56c16b.png)

Thanks!

**Comment by DanielnetoDotCom** [comment]
We do have the og:image tag in all videos

I am not sure why WhatsApp is not loading the content

Check this 

https://stackoverflow.com/a/43154489

use this to check

https://www.opengraph.xyz/

**Comment by gbrn** [comment]
I have verified that it is a problem in Whatsapp Web. When sent through the APP it goes with the picture normally.
