### ISSUE TITLE
Fresh install error

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#6624]
Went to do a fresh install after git clone (just now) and below happens. Encoder install startup is fine, but obviously need AVideo first.

int(1) ["message"]=> string(247) "Uncaught Error: Class "AVideoPlugin" not found in /var/www/html/AVideo/objects/functions.php:7446 Stack trace: #0 /var/www/html/AVideo/objects/functions.php(7475): getCDN() #1 /var/www/html/AVideo/install/index.php(15): getURL() #2 {main} thrown" ["file"]=> string(42) "/var/www/html/AVideo/objects/functions.php" ["line"]=> int(7446) }

**Comment by DanielnetoDotCom** [comment]
can you please make a git pull again?

**Comment by GreenDragonTavern** [comment]
That did it, thank you Daniel.
