### ISSUE TITLE
A way to change the text color just for a certain theme  READABLE

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6647]
I am trying to change the title text to black but the element will not let me single it out. It does this globally and makes all the text links black.

![2253b140-fb20-4a99-9de8-4ea22739a96d](https://user-images.githubusercontent.com/39392449/170127670-bded31fb-3696-437c-a7b2-a1b7c677b113.png)

**Comment by JoshWho** [comment]
I just don't want it to effect the other themes if someone switched to a dark theme

**Comment by DanielnetoDotCom** [comment]
sorry, currently we do not have an option for a specific theme.

**Comment by JoshWho** [comment]
I just want to change the title part here 

and make it a {
    color: #000000;
    text-decoration: none;
}

but when I do that it makes all text-decoration globally and changes it all to black.

**Comment by JoshWho** [comment]
I thought u was able to add stuff to the git ignore or something like that

**Comment by DanielnetoDotCom** [comment]
you can change it globally, NOT for a specific theme

**Comment by JoshWho** [comment]
Am I able to make like a child theme of the READABLE style so it doesn't get erased by the git pull?

**Comment by JoshWho** [comment]
Go here and you can see the error  https://cors-test.codehappy.dev/?url=https%3A%2F%2Fcorder.tv%2F&method=get

**Comment by JoshWho** [comment]
Could you please add this to that theme style READABLE 

```
 {
color: #000000;
text-decoration: none;
}
```

Just make that the norm color for the VIdeo Title on side desktop view

![74234652-5f72-4069-b681-4dc8f125541c](https://user-images.githubusercontent.com/39392449/170388248-8398647f-529f-43b7-b2a1-8276f72b93b1.png)

**Comment by DanielnetoDotCom** [comment]
try this update for the CSS

**Comment by JoshWho** [comment]
I did the update not sure what I am looking for is there a new setting?

**Comment by DanielnetoDotCom** [comment]
the colors are different now

![image](https://user-images.githubusercontent.com/18009293/170574074-cf47f6f9-fe6a-4e53-a2bc-7c7d87d50cfd.png)

**Comment by JoshWho** [comment]
AHhhh I c i had to use incognito window cache was stuck Sweet thank you Looks great now!!
