### ISSUE TITLE
Meet failed to start after latest update please help

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#6649]
Please see the screenshort below as i tried to start meet and this message poped up
![Screenshot (38)](https://user-images.githubusercontent.com/72950503/170137908-9c057d36-6e70-4598-b010-38b3e897689a.png)

**Comment by mrgodgiven** [comment]
![Uploading Screenshot (39).png…]()

**Comment by GreenDragonTavern** [comment]
Try this inside AVideo directory:

sudo git fetch --all && sudo git reset --hard origin/master
sudo chown -R www-data /path/to/your/AVideo

**Comment by DanielnetoDotCom** [comment]
Please try this update, I found something
