### ISSUE TITLE
(Question) Is it possible to hide private videos so they do not appear on the page unless you are logged in?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6653]
**Describe the question**
I'd like to make sure that certain content isn't picked up by search engines. 

I can see the videos on the page when not logged in, so I'm pretty sure search engines can too.

How to make non-public videos, not appear to the public?

**Comment by DanielnetoDotCom** [comment]
Duplicated https://github.com/WWBN/AVideo/issues/6652
