### ISSUE TITLE
socket liveuser fatal error

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6656]
@DanielnetoDotCom 

when I start the socket server, i get this error

Fatal error: Uncaught Error: Undefined constant "Socket\LiveUsers" in /var/www/xxx/plugin/YPTSocket/Message.php:133
Stack trace:
#0 /var/www/xxx/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(142): Socket\Message->onOpen()
#1 /var/www/xxx/vendor/cboden/ratchet/src/Ratchet/Http/HttpServer.php(51): Ratchet\WebSocket\WsServer->onOpen()
#2 /var/www/xxx/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(112): Ratchet\Http\HttpServer->onMessage()
#3 /var/www/xxx/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(95): Ratchet\Server\IoServer->handleData()
#4 /var/www/xxx/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\Server\IoServer->Ratchet\Server\{closure}()
#5 /var/www/xxx/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()
#6 /var/www/xxx/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}()
#7 /var/www/xxx/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit()
#8 /var/www/xxx/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData()
#9 /var/www/xxx/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#10 /var/www/xxx/plugin/YPTSocket/server.php(83): React\EventLoop\StreamSelectLoop->run()
#11 {main}
  thrown in /var/www/xxx/plugin/YPTSocket/Message.php on line 133

**Comment by GreenDragonTavern** [comment]
All kinds of issues here after a git pull yesterday, and sockets quit working...could not get it working, like you errored out. Gave up and did a git clone in another directory, followed that up with the composer update. Moved videos directory to the new AVideo directory, deleted old AVideo, moved new AVideo to where it belongs. Socket was back up and running, added my paid plugins back in and back to normal. You may not have to go to such measures, but for the life of me, could not get sockets to work yesterday after a git pull.

**Comment by DanielnetoDotCom** [comment]
Check if this resolves your issue

**Comment by jengajenga** [comment]
fixed
