### ISSUE TITLE
Live and meeting don't work


### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#6657]
Daniel since we installed it on the new server it doesn't work
Live and meeting do not work and give this error from browser and android app.

![signal-2022-05-26-23-41-07-952.jpg](https://user-images.githubusercontent.com/82677269/170588121-d6c56f0e-05c5-4c3d-9acd-0cb9eac95185.jpg)

![signal-2022-05-26-23-42-40-835.jpg](https://user-images.githubusercontent.com/82677269/170588161-8656d505-86ba-46c4-94fa-dda924b0b324.jpg)

https://user-images.githubusercontent.com/82677269/170588193-99b99c18-907b-4a89-a43c-50e46a1816c8.mp4

**Comment by sharknetwork24** [comment]
![eeer](https://user-images.githubusercontent.com/82677269/170595254-0164bb65-cfc8-4d63-9617-fc6a6c46ec06.PNG)

**Comment by DanielnetoDotCom** [comment]
make a` git pull` and try again

**Comment by sharknetwork24** [comment]
> fare un ` git pull`e riprovare

Tell me if the command is correct.

cd /var/www/html/AVideo/ && sudo git pull
Thank you

**Comment by DanielnetoDotCom** [comment]
seems to be correct

**Comment by sharknetwork24** [comment]
Now it works perfectly.
Thanks Daniel
