### ISSUE TITLE
How do I get a "Top N" list across all users videos

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6658]
**Describe the question**
It seems that the Dashboard/chart only shows videos for the logged in user.

How can I get a chart for all users/videos on the site?

I'll take anything, even a mysql query that I can execute manually. 🙏

**Comment by DanielnetoDotCom** [comment]
The admin menu should give you that

![chrome-capture-2022-4-27](https://user-images.githubusercontent.com/18009293/170700345-f879fa02-f4a8-4a54-b3c5-4ba67990fc56.gif)

**Comment by walt93** [comment]
Thanks!
