### ISSUE TITLE
try [1] Error on return_vars->videos_id

### ISSUE THREAD

**Issue by Proxy-Ninja** [WWBN/AVideo#6659]
![Avideo Error](https://user-images.githubusercontent.com/30862397/170670240-4f43dc20-e086-4967-b642-032b5164e810.jpeg)

**Comment by DanielnetoDotCom** [comment]
If this is a local server, you cannot use the public encoder.

or if it is not the public encoder, check your streamer log

**Comment by Proxy-Ninja** [comment]
Encoder is is a local server, where can i find a log, can you please provide path.

Thanks.

**Comment by DanielnetoDotCom** [comment]
Disable the VR360 plugin or install its tables 

https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by Proxy-Ninja** [comment]
> Disable the VR360 plugin or install its tables
> 
> https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by Proxy-Ninja** [comment]
Thanks @DanielnetoDotCom you saved my day.
Issue Fixed.
