### ISSUE TITLE
PPV Live is not working

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6660]
Latest git.
Tried on 3 instances including the demo site 
PPV Live v2.4

1. GO to live
2. Choose plan
3. Click save
4. WILL NOT SAVE

![ppv-issue](https://user-images.githubusercontent.com/65451390/170695617-482af401-4594-4872-9933-89a3f20b694d.jpeg)

Please look into it @DanielnetoDotCom 

Thank you

**Comment by DanielnetoDotCom** [comment]
thanks for noticing that.

this update should fix it.

**Comment by jengajenga** [comment]
Most welcome Dan. Let me update. Thanks.

**Comment by jengajenga** [comment]
Fixed
