### ISSUE TITLE
Payment issues 

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6662]
I am having payment issues.
The credit card or PayPal option sometimes doesn’t appear 
![2085CB44-DA48-4206-B8A3-BDAE56485309](https://user-images.githubusercontent.com/58601786/170808672-db2e156b-1ca8-48e6-8a57-fd3646ec731e.png)
![380D62AF-9EC8-471A-8CF6-91149914B327](https://user-images.githubusercontent.com/58601786/170808678-1bdfd0ad-6152-4c4d-90a3-d597f9ae6eed.png)

Or

when the credit card option shows they person is being asked to add 50 dollars to their wallet, then pay for the pay per view in addition.

**Comment by barrunning** [comment]
![7CDBA71D-45AB-451E-B001-B01CF2EEAA59](https://user-images.githubusercontent.com/58601786/170808850-3d7a3f12-226e-4dee-a199-48bf6439ab10.jpeg)

**Comment by DanielnetoDotCom** [comment]
can you please share the link where the button does not appear?

**Comment by barrunning** [comment]
I will have to wait until it happens. The above pictures is what was sent to me. They hit credit card and buy now appeared. The click buy now and the next picture appeared. No way to purchase and no video.

**Comment by barrunning** [comment]
Also why is it asking to add to wallet?
![CE6F02DB-6B59-40EA-AD49-775A32116462](https://user-images.githubusercontent.com/58601786/170826439-0bcf3a63-8f96-473b-8a41-e791a987fdfe.jpeg)
![F743B0CD-4B95-44FA-BD7E-0657846A7509](https://user-images.githubusercontent.com/58601786/170826442-64eadbbc-762c-4cc6-8ea6-663a361b5326.jpeg)
![DBEEF17E-4017-42F9-AD72-AC3927572E78](https://user-images.githubusercontent.com/58601786/170826444-becbe3c8-52cb-4f94-92ae-6070b8d706bf.png)
![A1A74F81-7454-4DC3-9EB5-A32A4D4D1743](https://user-images.githubusercontent.com/58601786/170826445-6351bf63-5f0f-4bcf-814a-89429ffe39a2.png)

**Comment by barrunning** [comment]
Those photos are what happened on two different transactions.

**Comment by DanielnetoDotCom** [comment]
basically both mean the same thing account and wallet

the money always first go to the wallet, than you pay for the PPV or subscription

**Comment by barrunning** [comment]
by url you meant the page i was on? if so, this is it. https://movementanalysissolutions.com/plugin/Subscription/showPlans.phphttps://movementanalysissolutions.com/plugin/Subscription/showPlans.php

This is the url that user got when trying to pay..

**Comment by DanielnetoDotCom** [comment]
I am not seeing any issue here, sorry

**Comment by barrunning** [comment]
I couldn’t find anything either.
