### ISSUE TITLE
[Feature request / Idea] ability to set a category page to use portrait poster frames instead of landscape

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6664]
**Is your feature request related to a problem? Please describe.**
I have sections where all of the videos have portrait poster images that would make a great page 

**Describe the solution you'd like**
A checkbox on the category to turn on "portrait images"
In "portrait images" mode we should also remove all of these controls:
![Screen Shot 2022-05-27 at 11 23 06 PM](https://user-images.githubusercontent.com/11711050/170813247-6a5ee992-8c00-40f1-ac64-ce3c8bc828de.png)
(probably we want to keep "edit video" though since that's an admin/channel operator facing feature)

Enabling should yield a clickable gallery of poster images. Use case is books and conceptually, think movie posters. Just a super clean page of book covers / movie posters / documents / etc...

**Comment by DanielnetoDotCom** [comment]
can you please screen share what image are you referring to?

**Comment by walt93** [comment]
![Screen Shot 2022-05-28 at 12 44 12 PM](https://user-images.githubusercontent.com/11711050/170840797-b28b0e35-76e6-437e-bd1d-7ec7bf36dee6.png)

**Comment by DanielnetoDotCom** [comment]
On the flix style, there is an option for disabling the landscape posters. the portrait will take place

![image](https://user-images.githubusercontent.com/18009293/171038074-55309bb9-7616-4d98-a222-3b8e2a3c9eba.png)
