### ISSUE TITLE
My users are getting "You're out of storage space", not sure what's misconfigured

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6668]
**Describe the question**
This was working previously, with four plans configured for DiskQuota plug-in. Few weeks ago I had to blow out the plugins configuration, seems I missed something when I reconfigured?

**Screenshots**
User sees this: (warning icon out of space, can't upload, showing the plans & their storage limits)
![Screen Shot 2022-05-28 at 1 57 54 PM](https://user-images.githubusercontent.com/11711050/170842656-22c2a70f-c51c-49b1-9a1f-5ff0d069a4ef.png)

![Screen Shot 2022-05-28 at 1 55 30 PM](https://user-images.githubusercontent.com/11711050/170842587-4f3c6bc6-b9e1-4d2e-8fd4-4855fa1fcb10.png)

Admin sees this: (User is in the group that should have the storage)
![Screen Shot 2022-05-28 at 1 56 49 PM](https://user-images.githubusercontent.com/11711050/170842622-383807c8-a528-4bb0-89ed-36a4e7ea490d.png)

EDIT: I "fixed" this temporarily by disabling the DiskQuota plugin.

**Comment by DanielnetoDotCom** [comment]
It is not about usergroups 

your users must signup to a plan

**Comment by walt93** [comment]
I'm not planning to use PayPal, is there a way to do this where I can manually admin it?
