### ISSUE TITLE
Could you please add article section

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#6670]
Greetings @DanielnetoDotCom 
Could you please add an article section by the user channel profile after videos section. Please see my screenshot
![Screenshot_20220529_010502](https://user-images.githubusercontent.com/72950503/170845551-009518c5-1bb2-4aa0-903b-a59d0f5482ae.jpg)

**Comment by DanielnetoDotCom** [comment]
I will send an update soon

**Comment by mrgodgiven** [comment]
thanks
