### ISSUE TITLE
Completely white screen

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#6684]
Many users are complaining that on PC they cannot see sharktube.info platform.
When they open the page, a completely blank white page opens.
This only from PC.
I also checked with 2 different and older PCs and I actually confirm the complaints of the users.
White page.
This never happened on the old server before.
Why is this happening?
It's as if something isn't working at a lower resolution than your monitor or screen.
Other sites work perfectly fine.
The problem is just with the sharktube.info platform that's wrong.
Can you help me kindly solve?
They will put a video for you to see.
Thank you

**Comment by sharknetwork24** [comment]
This is a video of a user explaining that everything works perfectly from android app and mobile browser.
From a laptop PC you only see a blank page.

https://sharktube.info/video/5533/2022-05-30-help-sharktube?channelName=_61476777ae548

**Comment by DanielnetoDotCom** [comment]
Can you please check the users IP that is returning an empty page?

**Comment by sharknetwork24** [comment]
Daniel I have 3 PCs
In 2 PCs I have no problems.
On another laptop an Acer 5920G I don't see a white blank page.
The IP I use is always the same so I don't think it's an IP problem right?
We are all on the same network.
But if you want I can still provide you with the IPs of the users.
I don't think it's IP Daniel's problem.
We have to solve this problem.
Hello

**Comment by DanielnetoDotCom** [comment]
yes, I will need the IP

**Comment by DanielnetoDotCom** [comment]
please check if still a blank page for you now

**Comment by sharknetwork24** [comment]
Daniel I sent you my IP by mail.  Let's see if we fix it on my PC.

**Comment by DanielnetoDotCom** [comment]
I added a code on your configurtion.php file to protect you from the DDoS attack

in case you are under attack again you can uncomment it.

**Comment by sharknetwork24** [comment]
I assumed he was the cause of the block.
As soon as I have news of the users I will let you know.
Everything seems to work.

**Comment by sharknetwork24** [comment]
Daniel is working.
Users have confirmed that they now see the page correctly.

**Comment by DanielnetoDotCom** [comment]
Thanks for confirm
