### ISSUE TITLE
Display categories

### ISSUE THREAD

**Issue by JeanDavis91** [WWBN/AVideo#6690]
Hello

Before that displayed the categories as a visitor now with version 11.7 nothing and yet these videos are clearly visible to visitors

![categories](https://user-images.githubusercontent.com/61474191/171067417-1502d34b-d42e-4515-9e7c-53fc4f4cc01b.jpg)
![correct](https://user-images.githubusercontent.com/61474191/171067432-792005de-72b4-4b66-9445-abb941c21281.jpg)

thank you for your work

**Comment by DanielnetoDotCom** [comment]
you can only see the category if you have videos (that you can see)

but your videos seem to be public. please try to clear the cache

**Comment by JeanDavis91** [comment]
Hello

Indeed the 4 videos are in public and I had emptied all the cache files

Before with v11.5 it worked perfectly but since upgrade to v11.7 of 30-05-2022 there is this problem

Have a nice day and thank you for your great work.

**Comment by GreenDragonTavern** [comment]
Will do, has to be later today but will make a small clip detailing issue. Thanks @DanielnetoDotCom

**Comment by JeanDavis91** [comment]
Good evening

There is no longer the choice of icons for the categories (absent)

On my site there is this problem of empty categories (none) and the videos are in public when I am connected, everything becomes normal again

Thanks

![icone](https://user-images.githubusercontent.com/61474191/171500038-1ab72d32-f5dc-46ef-bad3-0a2d5b97a4e7.jpg)

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by GreenDragonTavern** [comment]
That fixed the dropdown being empty. The only way to maneuver though is via the scrollbar. Navigation keys, PgUp/PgDn don't work at all.

**Comment by JeanDavis91** [comment]
Good evening

Yes indeed the category icons work now.

For my problem of categories that are not displayed on the left under the menu, there is only admin who can see these categories so for connected members no categories are displayed in this category menu remains empty

Have a good evening

**Comment by JeanDavis91** [comment]
![cate hs](https://user-images.githubusercontent.com/61474191/171905320-c0416691-1abb-4610-a21f-ecbbaf49c198.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, I do not understand. 

there are 2 or 3 different bugs here?

I am not understanding when you say delete. does it really delete the categories or just uncheck the other ones?

maybe you need to check the hide private videos on YouPHPFlix2 plugin

![image](https://user-images.githubusercontent.com/18009293/171913015-ba147475-289f-4d23-8e81-26b7dc442937.png)


If I am still missing something and there are more than one bug here, please open one issue per bug

**Comment by JeanDavis91** [comment]
Good evening

I made a mistake in the post so I come back to the categories with a video this time
https://user-images.githubusercontent.com/61474191/171947940-903b8a76-fcc0-42bb-8db5-190fc7fe6537.mp4

Thanks

**Comment by DanielnetoDotCom** [comment]
Do you have a PPV or subscription plugin enabled?

do you have any paid plugins?

I guess it is a bad plugin configuration, I am not sure which one.

try to reset the plugins configurations.

execute this file

https://github.com/WWBN/AVideo/blob/master/install/resetPlugins.php

Try this

`cd /var/www/html/AVideo/install`

than

```
# php resetPlugins.php 
1 - Reset all plugins Parameters
2 - Reset CustomizeUser Plugin Parameters only
3 - Reset all plugins (Will also inactivate the plugins)
Choose an option: 
```

Choose option 3

**Comment by ahmedxda** [comment]
@DanielnetoDotCom 
@JeanDavis91 

I have just faced the same bug and I managed to solve it by just using the default category icon "folder icon" ..Now all videos in category are visible

**Comment by JeanDavis91** [comment]
Good evening

I solved the problem of public categories not showing but I found another problem see below

![catem](https://user-images.githubusercontent.com/61474191/174177494-39fe2f27-6500-474f-b1a9-31aeb62242df.jpg)

![cv2](https://user-images.githubusercontent.com/61474191/174177661-0c39f2fd-d31e-4323-b1be-227cee94d379.jpg)

Thanks

**Comment by DanielnetoDotCom** [comment]
why are you saying it should not see this category?

**Comment by DanielnetoDotCom** [comment]
Are you talking about this?

![image](https://user-images.githubusercontent.com/18009293/174334298-1db49c55-375e-412c-be91-f86cfaa955c2.png)

**Comment by JeanDavis91** [comment]
https://user-images.githubusercontent.com/61474191/174338494-e78eb687-e95d-4d49-81f6-45b74e197a49.mp4

**Comment by DanielnetoDotCom** [comment]
Can you please check if you are up to date (git pull)

I just tested here and it works as expected

**Comment by JeanDavis91** [comment]
Hello

(git pull) this does every 24 hours so the site is always up to date (Done 10 minutes ago).

There is the same problem on your demo site, we should not see the Games category by clicking in the left menu on categories

https://user-images.githubusercontent.com/61474191/174683871-081e2486-a5fb-47b3-bc3b-25601452fca3.mp4

On version v11.5 it works perfectly

jfr
