### ISSUE TITLE
Description box is gone

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6693]
@DanielnetoDotCom In this latest recent update, the description box is gone:
![image](https://user-images.githubusercontent.com/37880073/171275511-d575c306-de03-4c67-9567-ca3c8246b984.png)

**Comment by gbrn** [comment]
![image](https://user-images.githubusercontent.com/37880073/171275910-bb82b370-6f06-42a1-8310-67d0a7803e20.png)

**Comment by DanielnetoDotCom** [comment]
are you updating the site with git pull??

looks like you still missing updates

check for javascript errors on the JS console

**Comment by gbrn** [comment]
@DanielnetoDotCom The description box reappeared without needing any changes. Something must have been delayed from the update.
