### ISSUE TITLE
Question re>NGINX and SSL

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6695]
**Describe the question**
I vaguely remember reading about this like a year ago. Something about letsencrypt and nginx and SSL & the details are forgotten...

What do I need to do to ensure my SSL doesn't lapse? cron tab to restart it at 4am seems a bit of a hack.

I've got a podcaster that wants to use my platform & want to do everything I can to make it stable for him.

**Comment by DanielnetoDotCom** [comment]
the problem is when let's encrypt auto-renew the certs it reloads only apache. it is supposed to reload also the Nginx.
for now, I am also not sure how to do that, but maybe if you reload Nginx instead of restart works.


`/usr/local/nginx/sbin/nginx -s reload`

**Comment by walt93** [comment]
It looks like you can set it up as a post hook on letsencrypt. See https://community.letsencrypt.org/t/solved-automatically-restarting-nginx-upon-cert-renewal/26265

**Comment by DanielnetoDotCom** [comment]
make sure you check the crontab as sudo
