### ISSUE TITLE
PPV Live not saving descriptions

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6696]
@DanielnetoDotCom , come see this. Can it be fixed?

Tested on 2 sites
1. Go to live
2. Set event
3. Add description and schedule the live
4. Save

![ppv-not-saving](https://user-images.githubusercontent.com/65451390/171287447-87c61655-c8cb-4cbc-baff-0a6d8939ff37.PNG)

6. Go to event on main page
7. Click event
8. No description even when signed in

![ppv-no-desc](https://user-images.githubusercontent.com/65451390/171287538-009e21de-31a1-4029-b9bc-d6da2af58346.PNG)

**Comment by DanielnetoDotCom** [comment]
Hi

please check if you are running PayPerViewLive  Version: @2.4

I remember fixing is some time ago

**Comment by DanielnetoDotCom** [comment]
Hi, I can see there is no description of the event, but the description has been saved.

I will send an update soon to display the description on the PPV Live buy page

**Comment by jengajenga** [comment]
Tha

> Hi
> 
> please check if you are running PayPerViewLive Version: @2.4
> 
> I remember fixing is some time ago

I am running v 2.4



> Member

Ok. Please let me know when you make the update so that I can update my site.

**Comment by jengajenga** [comment]
Thank you

**Comment by jengajenga** [comment]
@DanielnetoDotCom , just made the update, and it is still not showing the description. it is the same as before. No text, no images, nothing.

I am running latest git and ppv live 2.5. no description at all. I tried on the demo site and still same thing.

**Comment by jengajenga** [comment]
@DanielnetoDotCom ,
I have seen the descriptions. 

How do I add a picture or image? When I use the source code option, everything disappears and there is no way to add a picture. 

How does the client add a picture or poster for the event?

**Comment by DanielnetoDotCom** [comment]
Currently, there is no custom image for PPV. PPV will use the default image for the default live

I may add an option for a custom image in the future

**Comment by jengajenga** [comment]
> Currently, there is no custom image for PPV. PPV will use the default image for the default live
> 
> I may add an option for a custom image in the future

This should be obvious. A customer buys imagery especially when it is a concert, comedy show, music festival etc. Can you put on priority?

**Comment by DanielnetoDotCom** [comment]
you can use different accounts for PPV.

if you want to sponsor this feature I can give you an ETA

for pricing please email me at developer@youphptube.com
