### ISSUE TITLE
Adding categories, channels

### ISSUE THREAD

**Issue by tsbmedia** [WWBN/AVideo#6697]
Hi as admin I created categories but they don't appear on side bar menu nor even on video pages. What is it that I might not be doing correct ? 

How do I create channels ? I can see My channels on side menu but when I click on next page there's nowhere the option to create channel.

I have changed the site logo under settings and yes on index page it's ok BUT on menu related pages, on top left default AVIDEO logo still appears . What might be the cause ? 

I also purchased Video thumbnail and uploaded plugin as admin but still I don't see thumbnail as video plays . What might be the cause ? 

Thanks.

**Comment by DanielnetoDotCom** [comment]
> Hi as admin I created categories but they don't appear on side bar menu nor even on video pages. What is it that I might not be doing correct ?

Categories only appear when you have videos in it
so first add videos in the category then you will see them

> How do I create channels ? I can see My channels on side menu but when I click on next page there's nowhere the option to create channel.

add some videos to your account, then you will have a channel

> I have changed the site logo under settings and yes on index page it's ok BUT on menu related pages, on top left default AVIDEO logo still appears . What might be the cause ?

The best place to change the logo is on the configurations menu

![chrome-capture-2022-5-1 (1)](https://user-images.githubusercontent.com/18009293/171467975-77ccbee2-cc22-4c86-b5b0-0442010e19b5.gif)


> I also purchased Video thumbnail and uploaded plugin as admin but still I don't see thumbnail as video plays . What might be the cause ?
> 

did you download and install the plugin? https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin

make sure it is enabled

![image](https://user-images.githubusercontent.com/18009293/171466649-7a19e371-65d0-42d4-8b0e-392c1292e6f7.png)

**Comment by DanielnetoDotCom** [comment]
> Thanks Daniel, site logo yes I changed as indicated on supplied video but still same challenge.

try to clear the cache

> Video thumbnail I shall have to request those having backEnd to assist.. what I did was uploading it on plugins manager, ( the zipped file) uploaded it and enabled it 🤦 instead of uploading on sever.

I am not sure what do you mean

**Comment by tsbmedia** [comment]
> > Thanks Daniel, site logo yes I changed as indicated on supplied video but still same challenge.
> 
> try to clear the cache
> 
> > Video thumbnail I shall have to request those having backEnd to assist.. what I did was uploading it on plugins manager, ( the zipped file) uploaded it and enabled it 🤦 instead of uploading on sever.
> 
> I am not sure what do you mean

I cleared the cache and THANKS LOGO it's ok.
With regard to video thumbnail , I meant since I am not IT person, I will need help to upload that videothumbnail properly on sever side. Can you do that for me

**Comment by DanielnetoDotCom** [comment]
try to update the logo on a PC, NOT a phone

**Comment by DanielnetoDotCom** [comment]
I can see your server is with me, I can do it for you. try again in 15 minutes

**Comment by DanielnetoDotCom** [comment]
I did update you and looks like the plugin was there. and also looks like the video on the first page does not play the videothumbs

I did enable the gallery mode for you. your thumbs should display properly now.

is it a problem to have the gallery enabled?

**Comment by tsbmedia** [comment]
I checked it's ok thanks ..

**Comment by tsbmedia** [comment]
![image](https://user-images.githubusercontent.com/57344248/171494341-eaf11b0e-d97b-4b07-8bfe-e74daf757c87.png)

Now that everything on thumbnails ok , i am now experiencing challenges with video uploads. I tried various mp4 videos they upload but dont appear on site attached is screenshot

**Comment by DanielnetoDotCom** [comment]
I found the issue, can you please try again?

**Comment by tsbmedia** [comment]
but it ok. thanks Danie;

**Comment by DanielnetoDotCom** [comment]
> now its ok ,,,but it seems thumbnails works with gallery theme

the thumbs will only not work on the first video on the page.

you should select a theme for your site.
