### ISSUE TITLE
PPV Live redirecting to the wrong place

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6700]
@DanielnetoDotCom , there is also this

1. Set up event
2. Give event link to user
3. User clicks to SIGN IN to buy

![ppv-sign-in](https://user-images.githubusercontent.com/65451390/171630041-c6f43918-8f79-4740-b45a-77c376cd0f4e.PNG)

4. If you are signed in and you can stream, it sends you here -> https://my.domain/plugin/Live/?live_servers_id=1 - the place where you get your stream url and key.
5. If you are signed in and you cannot stream, you get this error

![ppv-sign-in-2](https://user-images.githubusercontent.com/65451390/171630649-2cf79f26-6d55-4be7-a654-ef8a64e3f994.jpg)

It is supposed to take you to the page where you pay but instead it takes you that way.

Can it be fixed urgently please?

Thank you.

**Comment by jengajenga** [comment]
@DanielnetoDotCom , have you seen this one?

**Comment by DanielnetoDotCom** [comment]
I am sending version 2.6 I hope it will be better now

**Comment by jengajenga** [comment]
Looking good now. Thanks @DanielnetoDotCom
