### ISSUE TITLE
Comment re>Twitter SSO. Please read, then you may close.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6702]
**Describe the question**
I have no need for Twitter login on my site, so I've never used it. I was looking at another user's AVideo setup, and decided to try logging using twitter SSO and was shocked by what I saw...

**Screenshots**
![Screen Shot 2022-06-02 at 1 55 30 PM](https://user-images.githubusercontent.com/11711050/171736853-a08e614d-46c3-4ab1-99e9-c3b4f49b4ae0.png)

FYI: As a user, I'm not giving a SSO login permission to do any of those things, and would opt not to use Twitter SSO... (edit: just in case this is a site configuration issue, this was on excalibur4)

**Comment by DanielnetoDotCom** [comment]
Hi

if you do not want a Twitter login you can just not enable the plugin.

**Comment by walt93** [comment]
I'm not using it. If these are the default permissions, I think this would make a lot of people not want to use it. Just an observation.

**Comment by DanielnetoDotCom** [comment]
This info does not come from me , it is the default oauth2 permission request

**Comment by walt93** [comment]
Understood thanks for clarifying
