### ISSUE TITLE
YPTSocket Please restart your server

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6704]
After latest update I am getting this repeating message:
![Screen Shot 5782-10-05 at 20 08 57](https://user-images.githubusercontent.com/58882903/172017975-7d058d63-af16-47db-9c7b-ba86297ff651.jpg)

I tried stoping the plugin, running also this command:
sudo nohup php /var/www/html/AVideo/plugin/YPTSocket/stopServer.php 

and than running the start server:

sudo nohup php /var/www/html/AVideo/plugin/YPTSocket/server.php &

Than starting the plugin again but it still asking for server restart which I also ran this:

sudo nohup php /var/www/html/AVideo/plugin/YPTSocket/serverRestart.php

Of course I was clearing my cache at each time.

**Comment by DanielnetoDotCom** [comment]
Please make sure it really stopped and really start 

it should not happen if you restart it correctly

**Comment by guymass** [comment]
OK thanks, had to run stopServer few times than started it again and the message is gone.
