### ISSUE TITLE
Subtitles appear off acreen

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6705]
I uploaded two VTT subtitles to a video, one is English and the other is Hebrew.

I cannot see the English one at all and the Hebrew one is only seen a bit on the bottom right side of the video area.

![Screen Shot 5782-10-06 at 0 28 36](https://user-images.githubusercontent.com/58882903/172026023-165a5f4f-9f9b-413a-b3ca-31fadf75cbd9.jpg)

I see the plugin has some style option but i am not sure how to input the correct parameters, this is what I tried:
![Screen Shot 5782-10-06 at 0 21 14](https://user-images.githubusercontent.com/58882903/172026048-11a3fbbf-e8e9-49c3-9974-c02cbd4d37d0.jpg)

**Comment by guymass** [comment]
Also tried using SRT files but still I see no subtitles on my video:
![Screen Shot 5782-10-06 at 0 46 25](https://user-images.githubusercontent.com/58882903/172026465-d4feddac-0120-4a6a-85d5-2b9c38f84ffa.jpg)

**Comment by guymass** [comment]
This is what happens when I open the create subtitles button and click on the Hebrew Subs to edit them, all the encoding of the text is screwed up:
![Screen Shot 5782-10-06 at 10 03 42](https://user-images.githubusercontent.com/58882903/172039551-2ce6e08b-7cac-4839-b1ac-e4c1662b45fd.jpg)

Maybe this is only on the plugin editor page because on the video you can see the hebrew fonts are showing, it is. just the entire text is pushed to the right all the way almost outside the video frame, idk why.


![Screen Shot 5782-10-06 at 10 02 42](https://user-images.githubusercontent.com/58882903/172039567-eb0e3d25-151a-49b2-bf67-9daa115692fa.jpg)

**Comment by guymass** [comment]
Now when I enable the Hebrew subtitles on the video I see some X buttons on the right side:
![Screen Shot 5782-10-06 at 10 19 41](https://user-images.githubusercontent.com/58882903/172040379-55f4422b-b0b9-497c-9b7d-82fbc9975d63.jpg)

**Comment by guymass** [comment]
That didn't help for the hebrew, however the main issue is they are not displaying on the video, not even the english version and that doesn't have anything to do with UTF-8 I think.

The strange fonts on the subtitles editor is a second issue I noticed when trying to edit the subtitles.

I downloaded the english subtitles from YT and uploaded it to the video on my site, but even the english is not showing.

**Comment by DanielnetoDotCom** [comment]
can you please share a subtitle source here so I can test it?

**Comment by guymass** [comment]
These are the ones I tries. The SRT is a conversion of the first VTT file I extracted from youtube
[Archive.zip](https://github.com/WWBN/AVideo/files/8872193/Archive.zip)

**Comment by DanielnetoDotCom** [comment]
Hi, the subtitle files you sent to me are totally wrong


there is a big text, all in one line

![image](https://user-images.githubusercontent.com/18009293/172913262-a35c7765-6858-4e82-8e1d-fa086bd329d8.png)


than 5k empty lines

![image](https://user-images.githubusercontent.com/18009293/172913200-b288cd24-367e-414d-9f74-5c6ee3a8313e.png)

**Comment by guymass** [comment]
Well I used a subtitle extractor before so I thought this is how this should be. Thanks for the notice I will try again with a different version. I will close this issue for now.
