### ISSUE TITLE
FTPAutoImport plugins

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#6709]
Hi Daniel,

I have question about the FTPAutoImport plugins.

![1654484719733](https://user-images.githubusercontent.com/57282919/172088360-4f5ebbbb-29e3-4737-bfe5-5470ad310ad5.jpg)

I have to modify the settings below according to your advice for this plugin to work. But there are security vulnerability.

![messageImage_1654485694915](https://user-images.githubusercontent.com/57282919/172089175-6b32804b-0cfb-4986-bf03-0382c341b105.jpg)

So, Do you have instructions for a more secure setup? but makes this plugin still working?

Thanks

**Comment by DanielnetoDotCom** [comment]
To be honest I am not sure about this plugin and I do not remember how this custom plugin works.

Also, I am not an FTP configuration expert. but I guess somehow you must allow apache to execute or access your FTP

the best option for this is to hire me to directly interact with you and your configuration during a meeting.

According to my records, this plugin was made for you about 2 years ago

**Comment by guitarpound** [comment]
Hi Daniel,

I tried edit the config back to default and the Plugin still working.
It maybe my misunderstand.

Anyway, Thank you so much.
