### ISSUE TITLE
Analytics/Question re>Matomo event tracking, how can we track "user hits PLAY on video" events?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6719]
**Describe the question**
I've installed Matomo for tracking. Works great.

I want to track play events, we need to add some Javascript as per the instructions here https://matomo.org/faq/reports/implement-event-tracking-with-matomo/
...additional info in discussion in the forums here https://forum.matomo.org/t/can-i-track-as-a-goal-when-a-video-is-watched/14967/5

How would we go about hacking this into our sites Daniel? Looks like all we have to do is add a wee bit of javascript to the play button...

------------
(from the above docs)... ...
`<a href="mailto:name@example.com" title="Email Us" onclick="_paq.push(['trackEvent', 'Contact', 'Email Link Click', 'name@example.com']);">Email Us</a>
`As you can see above, the code largely follows the same format as the first link above, but with an additional onclick attribute. The actual JavaScript function that triggers the event is contained within the quotation marks. From the example above that would be:

`_paq.push(['trackEvent', 'Contact', 'Email Link Click', 'name@example.com']);
`

**Comment by DanielnetoDotCom** [comment]
so do you have a page to handle the requests?

if you do you may want to use the play event for video js

```
if (typeof player === 'undefined' && $('#mainVideo').length) {
   player.on('play', function () {
        // your code here
   });
}
```

also the javascript variable `mediaId` holds the videos_id value
