### ISSUE TITLE
add video

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#6722]
why some users get this message when they want to add a movie in the encoder ?

![image001](https://user-images.githubusercontent.com/93145787/172884134-2e0e2bb9-6443-46d4-9061-d76fa0c2d620.jpg)

If I manually type in www.youhippo.com/coder/, and manually type in my login information it works fine.

**Comment by DanielnetoDotCom** [comment]
check the encoder configurations

![image](https://user-images.githubusercontent.com/18009293/172913742-fcb7cae0-5b88-42ba-8cc5-e3bbb787dbfe.png)

**Comment by KrzysioMisio** [comment]
I have the correct streamer address

![2022-06-09_200250](https://user-images.githubusercontent.com/93145787/172914602-044eb056-2e16-4a89-906f-c698c529e7a5.png)

I can add videos normally 
but some users have problems

**Comment by DanielnetoDotCom** [comment]
you can make it blank or add a second line with your URL without the www

https://youhippo.com
