### ISSUE TITLE
Apache2 won't start after upgrade

### ISSUE THREAD

**Issue by dancoe77** [WWBN/AVideo#6723]
**Describe the bug**
I upgraded AVideo from 11.4 to 11.6 according to the wiki.  After the upgrade the apache2 service won't start.

**To Reproduce**
1. systemctl restart apache2
2. root@vmi491464:~# systemctl status apache2
● apache2.service - The Apache HTTP Server
     Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-06-10 07:35:04 CEST; 21min ago
       Docs: https://httpd.apache.org/docs/2.4/
    Process: 2467 ExecStart=/usr/sbin/apachectl start (code=exited, status=139)

Jun 10 07:35:04 vmi491464.contaboserver.net systemd[1]: Starting The Apache HTTP Server...
Jun 10 07:35:04 vmi491464.contaboserver.net apachectl[2467]: Segmentation fault
Jun 10 07:35:04 vmi491464.contaboserver.net apachectl[2467]: Action 'start' failed.
Jun 10 07:35:04 vmi491464.contaboserver.net apachectl[2467]: The Apache error log may have more information.
Jun 10 07:35:04 vmi491464.contaboserver.net systemd[1]: apache2.service: Control process exited, code=exited,>
Jun 10 07:35:04 vmi491464.contaboserver.net systemd[1]: apache2.service: Failed with result 'exit-code'.
Jun 10 07:35:04 vmi491464.contaboserver.net systemd[1]: Failed to start The Apache HTTP Server.
lines 1-13/13 (END)

**Expected behavior**

**Error Logs**
Jun 10 08:15:04 vmi491464.contaboserver.net systemd[1]: Starting The Apache HTTP Server...
-- Subject: A start job for unit apache2.service has begun execution
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit apache2.service has begun execution.
--
-- The job identifier is 1015.
Jun 10 08:15:04 vmi491464.contaboserver.net apachectl[3085]: Segmentation fault
Jun 10 08:15:04 vmi491464.contaboserver.net apachectl[3085]: Action 'start' failed.
Jun 10 08:15:04 vmi491464.contaboserver.net apachectl[3085]: The Apache error log may have more information.
Jun 10 08:15:04 vmi491464.contaboserver.net systemd[1]: apache2.service: Control process exited, code=exited,>
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- An ExecStart= process belonging to unit apache2.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 139.
Jun 10 08:15:04 vmi491464.contaboserver.net systemd[1]: apache2.service: Failed with result 'exit-code'.
-- Subject: Unit failed
Jun 10 08:15:04 vmi491464.contaboserver.net systemd[1]: apache2.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit apache2.service has entered the 'failed' state with result 'exit-code'.
Jun 10 08:15:04 vmi491464.contaboserver.net kernel: apache2[3093]: segfault at 88 ip 00007fa57f720258 sp 0000>
Jun 10 08:15:04 vmi491464.contaboserver.net kernel: Code: fd 41 54 49 89 f4 55 49 01 fc 53 48 83 ec 20 4c 39 >
Jun 10 08:15:04 vmi491464.contaboserver.net systemd[1]: Failed to start The Apache HTTP Server.
-- Subject: A start job for unit apache2.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit apache2.service has finished with a failure.
--
-- The job identifier is 1015 and the job result is failed.
##########################################################

[Fri Jun 10 01:05:46.237740 2022] [core:notice] [pid 537] AH00094: Command line: '/usr/sbin/apache2'
[Fri Jun 10 06:28:26.943300 2022] [php:warn] [pid 491684] [client 54.36.148.207:54497] PHP Warning:  require(/var/www/html/AVideo/vendor/composer/../guzzlehttp/psr7/src/functions_include.php): Failed to open stream: No such file or directory in /var/www/html/AVideo/vendor/composer/autoload_real.php on line 76
[Fri Jun 10 06:28:26.944257 2022] [php:error] [pid 491684] [client 54.36.148.207:54497] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/AVideo/vendor/composer/../guzzlehttp/psr7/src/functions_include.php' (include_path='.:/usr/share/php') in /var/www/html/AVideo/vendor/composer/autoload_real.php:76\nStack trace:\n#0 /var/www/html/AVideo/vendor/composer/autoload_real.php(59): composerRequirec3a61dba26daada128f5891f1a57c504()\n#1 /var/www/html/AVideo/vendor/autoload.php(7): ComposerAutoloaderInitc3a61dba26daada128f5891f1a57c504::getLoader()\n#2 /var/www/html/AVideo/objects/autoload.php(2): require_once('...')\n#3 /var/www/html/AVideo/objects/include_config.php(34): require_once('...')\n#4 /var/www/html/AVideo/videos/configuration.php(44): require_once('...')\n#5 /var/www/html/AVideo/view/index.php(26): require_once('...')\n#6 {main}\n  thrown in /var/www/html/AVideo/vendor/composer/autoload_real.php on line 76
[Fri Jun 10 06:34:34.879262 2022] [mpm_prefork:notice] [pid 537] AH00169: caught SIGTERM, shutting down
[Fri Jun 10 06:34:35.116456 2022] [mpm_prefork:notice] [pid 540632] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f configured -- resuming normal operations
[Fri Jun 10 06:34:35.116667 2022] [core:notice] [pid 540632] AH00094: Command line: '/usr/sbin/apache2'
[Fri Jun 10 06:35:26.418804 2022] [mpm_prefork:notice] [pid 540632] AH00169: caught SIGTERM, shutting down
[Fri Jun 10 06:35:56.075575 2022] [mpm_prefork:notice] [pid 518] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f configured -- resuming normal operations
[Fri Jun 10 06:35:56.075946 2022] [core:notice] [pid 518] AH00094: Command line: '/usr/sbin/apache2'
[Fri Jun 10 06:50:31.993570 2022] [mpm_prefork:notice] [pid 518] AH00169: caught SIGTERM, shutting down
####################################################################################

Jun 10 08:09:01 vmi491464 CRON[2934]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Jun 10 08:09:05 vmi491464 systemd[1]: Starting Clean php session files...
Jun 10 08:09:05 vmi491464 systemd[1]: phpsessionclean.service: Succeeded.
Jun 10 08:09:05 vmi491464 systemd[1]: Finished Clean php session files.
Jun 10 08:15:04 vmi491464 systemd[1]: Starting The Apache HTTP Server...
Jun 10 08:15:04 vmi491464 apachectl[3085]: Segmentation fault
Jun 10 08:15:04 vmi491464 kernel: [ 5032.381806] apache2[3093]: segfault at 88 ip 00007fa57f720258 sp 00007ffebe534890 error 4 in libphp8.0.so[7fa57f53a000+279000]
Jun 10 08:15:04 vmi491464 kernel: [ 5032.381821] Code: fd 41 54 49 89 f4 55 49 01 fc 53 48 83 ec 20 4c 39 e7 0f 83 db 00 00 00 66 2e 0f 1f 84 00 00 00 00 00 49 8b 45 00 49 83 c5 20 <8b> 90 88 00 00 00 85 d2 0f 85 b2 00 00 00 48 8b 68 18 48 85 ed 0f
Jun 10 08:15:04 vmi491464 apachectl[3085]: Action 'start' failed.
Jun 10 08:15:04 vmi491464 apachectl[3085]: The Apache error log may have more information.
Jun 10 08:15:04 vmi491464 systemd[1]: apache2.service: Control process exited, code=exited, status=139/n/a
Jun 10 08:15:04 vmi491464 systemd[1]: apache2.service: Failed with result 'exit-code'.
Jun 10 08:15:04 vmi491464 systemd[1]: Failed to start The Apache HTTP Server.
Jun 10 08:17:01 vmi491464 CRON[3124]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jun 10 08:18:01 vmi491464 CRON[3129]: (root) CMD (sync; echo 3 > /proc/sys/vm/drop_caches)
Jun 10 08:18:01 vmi491464 kernel: [ 5209.842659] sh (3129): drop_caches: 3

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome, and firefox]

**Additional context**
[AVideo_Error.log](https://github.com/WWBN/AVideo/files/8876179/AVideo_Error.log)

**Comment by DanielnetoDotCom** [comment]
If I am in your shoes, I would try to reboot the server, and apt-get update/upgrade again

**Comment by dancoe77** [comment]
Thank you.  Will try that:))

Dan

**Comment by dancoe77** [comment]
I did check out the ports and nothing is listening on port 80 or 443.  nginx has been configure to use 8080 and 8443. I also did do the apt-get update and upgrade again.  All it did was update the php7.3 and php7.4 modules.  I also insured that that php7.3 was enabled in Apache.

**Comment by DanielnetoDotCom** [comment]
Sorry I am not sure what you have done.

**Comment by dancoe77** [comment]
So all I did was do the git pull to update the site to the latest release.
I also performed ubuntu's recommended patch updates on the OS.

Dan

**Comment by DanielnetoDotCom** [comment]
sorry but this is clearly a server issue. you may hire me to TRY to fix (no guarantee) or try to google for a solution

**Comment by GreenDragonTavern** [comment]
Problem probably is PHP and two flavors. Uninstall all PHP7.3, and make sure apache2 is configured for php7.4. If you want a quick fix prior to removing php7.3: sudo a2dismod php7.3...sudo a2enmod php7.4...sudo systemctl restart apache2.
