### ISSUE TITLE
Federated Network Avideo Video Sharing Nodes

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6725]
A new way to integrate other Avideo websites videos into your own Avideo website.

There use to be a old plugin that did something like this. 

Basically become a public Avideo node and allow your videos to be played on other Avideo sites, allowing cross site linking and will help get videos seen to millions across the globe that sets up a Avideo website.

Let Avideo websites exchanges keys with each other so you can still approve what site will be indexed on your Avideo site.

**Comment by DanielnetoDotCom** [comment]
Hi, we did have a plugin that connect one or more AVideo sites, but it was discontinued because it was giving me more problems than solutions

**Comment by JoshWho** [comment]
What if there was a central database that linked them all together instead of it being the sites talking to each other. Just an idea 

Kinda thinking how a old botnet use to work or Limewire gnutella network.  Just a node that collects the info and makes it easy to link by the other sites aka nodes.
