### ISSUE TITLE
Getting an alert that Meeting plugin is required. How to disable this?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6727]
**Describe the bug**
Few weeks ago this alert started happening. Turning on Meet makes it stop. I'd like to turn off Meet. How to make it stop otherwise?

![Screen Shot 2022-06-11 at 11 47 44 PM](https://user-images.githubusercontent.com/11711050/173221044-ca7c9737-ea35-492f-a364-64ff1444c66b.png)

**Comment by DanielnetoDotCom** [comment]
this is not really a bug. 

disable the caller on the YPTSocket plugin

![image](https://user-images.githubusercontent.com/18009293/173357371-d7b4e9b3-891b-47d9-a9a1-2cd11bf12885.png)
