### ISSUE TITLE
Cannot send emails from website

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6729]
Trying to run tests on two different mail account, one is gmail and the other is our local server show the following error:
![Screen Shot 5782-10-13 at 20 24 48](https://user-images.githubusercontent.com/58882903/173246254-db29cc92-c2b0-470c-8767-60200123d26b.jpg)
![Screen Shot 5782-10-13 at 20 40 48](https://user-images.githubusercontent.com/58882903/173246257-dd5f1a07-e65e-491e-8c31-d17a6cea5fff.jpg)

I have checked the gmail account and sent direct emails from it to a mailbox on our mail server and mail was working just fine.
So this could be something internally I think.

**Comment by DanielnetoDotCom** [comment]
it is clear to me it is a misconfiguration on your SMTP credentials or server.

it is something specific from your side. you must deal with it

**Comment by guymass** [comment]
You are right, after restarting the mail server I was able to connect, thanks.
