### ISSUE TITLE
Requesting Audio section on user channel

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#6738]
Greetings @DanielnetoDotCom  Could you please add a section for Audio on the user channel section after Articles. Some users would like their podcasts to be separated from videos.

![Screenshot_20220613_114123](https://user-images.githubusercontent.com/72950503/173579274-6918eb71-528f-4b7f-a006-a38bcda0f43e.jpg)

**Comment by DanielnetoDotCom** [comment]
Sorry for the late reply, I will send an update soon
