### ISSUE TITLE
Bookmark Plugin

### ISSUE THREAD

**Issue by guitarpound** [WWBN/AVideo#6743]
Hi Daniel,

I've hired you to create a bookmark plugin for 2 years ago.
Now, I bought your FTP Storage plugin but it need to upgrade the AVideo from v9.7 to latest version to make it working.

But after upgrade it, I found the Current time in the bookmark plugin is not show when playback the video. (see below pic)

![1655458550887](https://user-images.githubusercontent.com/57282919/174271819-8016a167-8050-4cbd-978e-4d1381a56a15.jpg)

So, Could you please kindly let me know how to solve this problem.

Thanks

**Comment by DanielnetoDotCom** [comment]
Hi

I am not sure what exactly is this for. 

I may need to check it directly into your environment

what does this bookmark plugin suppose to do?

**Comment by JoshWho** [comment]
r u talking about this feature?
![2fe44438-508a-4388-bb65-780dbc42ecf6](https://user-images.githubusercontent.com/39392449/174987337-dd88cf7a-d2a6-47d4-8dda-20f82a34bb92.png)
