### ISSUE TITLE
Problem with Trending

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#6744]
Trending:

I have a problem with trending. At the moment it updates monthly apparently and it has now well passed a month and nothing has changed. However monthly Trending isn't practice for me and i know others have asked for this in the past to be monthly. God knows why. Users email in saying trending is broken as it never changes. Would it be possible for it to update based on views in 24 hours? If this used to update regular can i not just replace those files with the older ones where it used to update regular?

Thank you so much.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
I just sent an update, try to change the trending tolerance here 

![image](https://user-images.githubusercontent.com/18009293/174640304-f16fcfc0-6a96-4238-92a0-7e876070e024.png)

**Comment by para2022** [comment]
I cleared my cache and it’s there now thanks you so much Daniel you are an absolute marvel.

**Comment by para2022** [comment]
I’m sure it’s working proper Daniel. I have daily trending set and someone is in the homepage trending section and they have no likes, no comments but 18 views from 2 week ago and others have much higher so maybe it needs tweaking? Thank you

**Comment by para2022** [comment]
I think I found the bug. Page 2 is where page one stats should be. Page 1 is definitely not my sites trending. Page 2 is so it not displaying the results properly. This was the same before the update. Page 2 was where my real trending was and after the update it remains the same. Sorry Daniel it only became apparent the second time round. Once that bug is sorted it will probs be all sorted mate. Thanks for your efforts.

**Comment by DanielnetoDotCom** [comment]
Hi, the bug you mention is not 100% clear to me. can you please share some screenshots and more details? also the expected results?

**Comment by para2022** [comment]
The trending in the side panel and the trending category on the home page show different.  Basically the trending button in the side Panel, the results on the homepage and the results by clicking the homepage Trending link above the thumbnails all display different results. None of them are accurate other than about 3 results. Some results are from weeks, months, year without hardly any hits. It’s like it’s randomly selected some lol

**Comment by JoshWho** [comment]
Stop using that one and make a new side link to that one.

**Comment by para2022** [comment]
Thank you Josh. Ironically the side one is more accurate. Is the video statistics plugin meant to be turned on cos my trending stats are all over the place they are not what they should be. Somebody with 19 views from 2 week ago with no likes no comments shouldn’t be trending as it’s set to 1 day. Users have far more activity than that is the past few days

**Comment by JoshWho** [comment]
I think it goes off of Likes comments and logged user activity.

**Comment by JoshWho** [comment]
Here is how u make a left link to the new one
![7fcb1d33-8019-4d63-b94a-2a7920701823](https://user-images.githubusercontent.com/39392449/174667783-7e29328c-6651-4520-b16b-9d608c1e2fd6.png)
![57a5de64-d4a4-455f-9b44-300bdc5e6982](https://user-images.githubusercontent.com/39392449/174667810-02ba54a0-e1a1-49bf-baed-81e041d405ac.png)

**Comment by para2022** [comment]
Thanks josh this user has no likes or comments though. There are users with comments and likes and activity and high views but not in trending. And still a bug in that if you have a row of 6 of trending on home page and then click the actual trending link above the row I get completely different results a bit the same as the trending button in side panel

**Comment by JoshWho** [comment]
Clear the stat data I think that should get rid of that.

**Comment by para2022** [comment]
If I clear the stat data does it clear everyone’s dashboard statistics? And thank you for the link info :)

**Comment by JoshWho** [comment]
I think it is just the live data once recorded it is archived.

**Comment by para2022** [comment]
Ok thanks mate

**Comment by JoshWho** [comment]
> Ok thanks mate

Your welcome no probs

**Comment by DanielnetoDotCom** [comment]
> The trending in the side panel and the trending category on the home page show different. Basically the trending button in the side Panel, the results on the homepage and the results by clicking the homepage Trending link above the thumbnails all display different results. None of them are accurate other than about 3 results. Some results are from weeks, months, year without hardly any hits. It’s like it’s randomly selected some lol

I just tested on my side and it seems to be ok, maybe I am looking into the wrong place, that is why I asked for screenshots
