### ISSUE TITLE
playlists issue 

### ISSUE THREAD

**Issue by ahmedxda** [WWBN/AVideo#6745]
when creating a playlist, episodes don't come in order,  for example episode 7 comes after episode 1 while I already set episodes in the right order...
another thing is that, episodes are automatically arranged in the playlist according to the date uploaded not arranged as the way I want!

#update 
Also videos plays automatically while I disabled Auto Play in settings

**Comment by DanielnetoDotCom** [comment]
you are supposed to be able to sort the playlist. 

drag and drop it 

![chrome-capture-2022-5-17 (1)](https://user-images.githubusercontent.com/18009293/174352552-722758c1-5f09-4fb4-9d31-1dcd42d1da94.gif)

**Comment by ahmedxda** [comment]
my be this is not available on mobile!
I have also some needed features suggested by my users , I will talk about the needed features in another suitable topic🌷

**Comment by ahmedxda** [comment]
I think we will need your help in the future, but I just will write about some improvements.. maybe you can include these improvements as an update if you think it deserves 🌷
