### ISSUE TITLE
Restream

### ISSUE THREAD

**Issue by ricasht** [WWBN/AVideo#6748]
I'm trying to relay to facebook and youtube, I don't find errors and the transmission doesn't start on other platforms

**Comment by JoshWho** [comment]
Facebook requires ssl to restream too. You need to reinstall FFMPEG with ssl for it to work correctly. FB is the only service that does that.

If you disable fb the restream will work for the other sites.

**Comment by mrgodgiven** [comment]
@JoshWho I used this same instructions to install ffmpeg with ssl, but it's still not working with facebook. it only worked about 6 months back and now it's no longer working. what could have I done wrong or missed out.
