### ISSUE TITLE
Setting minrate {$minrate}k -crf 23 -maxrate {$maxrate}k -bufsize {$bufsize}k -c:a aac -b:a {$autioBitrate}k

### ISSUE THREAD

**Issue by sipero** [WWBN/AVideo#6750]
In the Encoder backend configuration here https://nimb.ws/GNFTeA there are settings for $minrate $maxrate $bufsize and $autioBitrate Can you please tell me where this information is found as I would like to tweak the settings so that I can have my own custom data rate settings for each of the resolutions as I find the ones used by default especially for FHD or higher are too high

**Comment by DanielnetoDotCom** [comment]
this is automatically extracted/generated from the source video

**Comment by sipero** [comment]
So is it not possible to tweak this to a better option especially if the data rate is much to high. I, for example, have seen videos with data rate of between 40mbps and 100mbps which are either going to have a lot of buffering or in some cases will not even play, especially if they are MP4 files.

Ideally I would like to be able to configure a maxmimum data rate for the video. This would mean a better playback experience for users especially if they have internet with lower download rates.

**Comment by DanielnetoDotCom** [comment]
I just doublechecked and the $minrate $maxrate $bufsize are only used on HLS files, NOT for MP4, on MP4 we only have the $autioBitrate

there is no such configuration for MP4, unless you change the default command line 

Basically, the audio information for all formats comes from here https://github.com/WWBN/AVideo-Encoder/blob/f14fc496fe4c26c99f72d10b7cd568c561a36724/objects/Format.php#L390-L402

480p, 360p and 240p = 128k audiobitrate
all other resolutions = 192k audiobitrate
