### ISSUE TITLE
Connect Error (1045) Access denied for user 'avideo'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo#6755]
Why can't I connect to the database? Login and password are correct
![image](https://user-images.githubusercontent.com/56869986/174588031-c2ca7bcc-a541-47e1-a892-b6de4f65e72d.png)

**Comment by DanielnetoDotCom** [comment]
make sure you know what is your database username

**Comment by JoshWho** [comment]
I was having that same issue when installing my buddies site. I ended up making new credentials that worked for it

**Comment by DittmerOk** [comment]
Thanks. everything is working. The problem was that I had incorrectly set the password for the user.
Required SET PASSWORD FOR 'video'@'localhost' = PASSWORD('blabla');
