### ISSUE TITLE
Encoder: how to enable the "advanced/configuration" page to select encoder resolutions/FFMPEG options

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6757]
**Describe the question**
When I installed the encoder, I was seeing a new panel of advanced config. with all the FFMPEG options. I thought this was super sweet. Now with the newly installed encoder, it is not enabled. How to?

**Screenshots**
(tab was last seen here...)
![Screen Shot 2022-06-20 at 3 00 13 PM](https://user-images.githubusercontent.com/11711050/174682680-96001b64-05bb-489e-b162-c44417e0b3e2.png)

**Comment by DanielnetoDotCom** [comment]
Try now

**Comment by walt93** [comment]
Perfect
