### ISSUE TITLE
Question re VPS/vCPU vs. Xeon for encoder (shopping server deals…)

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6759]
**Describe the question**
I just built a 4 core vCPU VPS and it feels a bit slower than running it on 2 cores of my Xeon main server.

Question: I can upgrade to 8 core vCPU for same price (if I lock in a contract) as a cheap 4c/8t Xeon.

If you were building a (cheap) encoder box would you do 8vCPUs  or a 4-core Xeon? Both work out to $24/mo. Any/all suggestions welcome!

**Comment by walt93** [comment]
I stuffed my encode queue last night and it looks like it’s going to take two more days to finish. My experience is that this 4vCPU VPS is much slower than 2 cores of real Xeon.

**Comment by JoshWho** [comment]
It depends on the main system at the datacenter running it. Is it a cloud based vps aka Instance, or is it a true vps on a giant dedicated server. That makes a huge difference.
