### ISSUE TITLE
Description for Website (SEO Google)

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6763]
@DanielnetoDotCom I've been checking that my site is missing a description on Google. I couldn't find the field to change this information. Google is probably displaying information found randomly in the Sitemap. I need to put a correct description so that users can understand what the site is. 
Check the image:

![image](https://user-images.githubusercontent.com/37880073/174913854-19a55c46-d0ba-4c94-a7e6-85b2e3752fbb.png)

**Comment by gbrn** [comment]
@DanielnetoDotCom I can't see this customize plugin.

What appears here for me is:
CustomizeAdvanced - Version: @1.0
and
CustomizeUser - Version: @3.0

![image](https://user-images.githubusercontent.com/37880073/175357406-cf6f7f44-35e4-4b17-bdbc-87fccab78972.png)

**Comment by DanielnetoDotCom** [comment]
this is a paid plugin, you can find it here https://youphp.tube/marketplace/
