### ISSUE TITLE
How to delete some resolutions

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6765]
**Describe the question**
I had a new encoder built & assumed it used my previous settings. Instead, it defaulted to transcoding to every possible resolution.

I encoded a bunch of media at too many resolutions. Is it possible to delete the unwanted resolutions?

...this is why the encoder was running soooo slooooow 😂😂😂

**Comment by DanielnetoDotCom** [comment]
I see, the only way to delete the resolutions that are already encoded is to do it manually.

another option is to reencode the video, swap the files and then delete the new encoded video

![image](https://user-images.githubusercontent.com/18009293/175042294-acbf022b-f54c-4442-973c-5d1cdf1df367.png)
