### ISSUE TITLE
Move the Wallet Display to the Myaccount Page or Dashboard or both

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6768]
I really want to remove the wallet from the Top menu but there is no page to display how much you have without that. Can that be moved to the My account page or the Dashboard maybe?

![3d45d395-3d36-4145-a0f7-083eef1cf36b](https://user-images.githubusercontent.com/39392449/174984527-e6edc8fc-a87d-446c-8bd0-eab4e925d9e8.png)

To maybe here

![bd64d66f-63d8-4ec5-9a7a-40e3f8819ef2](https://user-images.githubusercontent.com/39392449/174984765-3dbf37d5-c39e-408b-825d-1d617bdfe0af.png)
or
![8f2faa64-696e-482f-bfbd-05e8a0f1b33e](https://user-images.githubusercontent.com/39392449/174985026-c7562e3a-e6d6-4fc0-a9a8-01cec3c37673.png)
or
![bf4d1b42-2037-4453-9f8c-e0c9c122bb63](https://user-images.githubusercontent.com/39392449/174985270-3e083a60-0903-4445-96fc-5971e59cf50f.png)

**Comment by DanielnetoDotCom** [comment]
to be honest, I am researching I am not sure what to do to resolve that. 

I know this is an old problem, but I was expecting this is resolved on modern browsers.

I will keep researshing

**Comment by DanielnetoDotCom** [comment]
I guess I found
