### ISSUE TITLE
!!! Even after DNS propagation initial page load/reload takes 1 minute - Help!

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6770]
**Describe the bug**

Page loads are taking up to around a minute or more. Reloading a page may be immediate. May take a minute. 

This is going to murder my podcasters launch

Advice?

**To Reproduce**
1. Go to conspyre.tv
2. Wait for it to load
3. Click any video or other page link on conspyre
4. Wait for it to load

**Expected behavior**
Page load not to take a full minute before any resource begins loading

**Error Logs**
What logs are useful here? Apache?

**Comment by DanielnetoDotCom** [comment]
This is not the Server itself, it is the wasabi, when it tries to grab the resolution from old videos. the new videos have the resolution on the file name. but in the past we had to check the video file itself to extract the resolution

I just added it to your configuration.php

`$global['disableVideoTags'] = 1; `Pulls the videos maximum resolution to display on the home page, disabling it may speed up your site if you are using a remote storage

I also sent you an update and your page will load a lot faster now, but you will not have the resolution tag on the page

**Comment by walt93** [comment]
This is a good fix. I keep my media optimized for 720p and a plurality of media is lower than that. Thanks!

**Comment by DanielnetoDotCom** [comment]
Hi, I also find wasabi is taking a while to generate the token for private files. I will make your bucket public. it may also make a huge difference.
