### ISSUE TITLE
Encoder network not switching to the next best thing

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6774]
Right now currently my encoder server is under ddos and the Encoder network still keeps trying to use it but it is not accessible at all I can;t even ssh into it right now. 

Why doe the encoder network not switch to a working encoder?

**Comment by DanielnetoDotCom** [comment]
it is supposed to look for a 200 header, I am not sure why it is using this encoder.

**Comment by DanielnetoDotCom** [comment]
what encoder you are saying is not accessible?

**Comment by JoshWho** [comment]
It was this one here https://encoder.joshwho-cdn.com/upl2/ but it looks like it is back working again

**Comment by DanielnetoDotCom** [comment]
your encoder seems fine to me.

<img width="688" alt="image" src="https://user-images.githubusercontent.com/18009293/175142978-ca4e5984-e48e-4d41-9ba4-cfcca03d053c.png">


I guess you are locked out. probably a firewall

**Comment by DanielnetoDotCom** [comment]
I see.
