### ISSUE TITLE
track user activity

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo#6775]
Tell me, can I track the user's actions? In the administrator account, look at which of the users when they logged in.

**Comment by JoshWho** [comment]
Odd question, but yes. Like any Content Management software you have a user statistic analytics option and websocket roster

**Comment by DanielnetoDotCom** [comment]
depending on what type of information you are looking for. 

there is the audit plugin/database table

also, the videos statistics table where some information can be extracted.

**Comment by Lordblanca** [comment]
Is there a way joshwho and Daniel to change the user number to there name. example user 49326 has 53 views can I change user number to there name?

**Comment by DittmerOk** [comment]
> @DittmerOkЯ думаю, вы должны искать это: https://www.hotjar.com/ На этом сайте вы можете получить несколько статистических данных о его пользователях. В том числе запись экрана с кликами.
perhaps this is what I need. But the problem is that I want to install this plugin locally at 192.168.100.100

**Comment by DanielnetoDotCom** [comment]
you are not supposed to download a free plugin separately. to get the plugin you MUST update the whole platform with a `git pull`
