### ISSUE TITLE
Plugins installation problems (Video Resolution and Customize plugins)

### ISSUE THREAD

**Issue by naradwiono** [WWBN/AVideo#6776]
I bought the video resolution switcher and Customize plugins.

after I installed and activated it, the website was under maintenance.

![image](https://user-images.githubusercontent.com/108025298/175222838-319a1d1d-396a-4c38-9a5e-f20331cafc27.png)

his is the recorded log

`[23-Jun-2022 12:38:41 Asia/Jakarta] PHP Warning:  file_get_contents(/var/www/avideo/plugin/Customize/sass/variables.scss): failed to open stream: No such file or directory in /var/www/avideo/plugin/Customize/Customize.php(18) : eval()'d code(1) : eval()'d code on line 33
[23-Jun-2022 12:38:41 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Call to undefined function ScssPhp\ScssPhp\_ob_start() in /var/www/avideo/plugin/Customize/sass/scssphp/src/Formatter.php(18) : eval()'d code(1) : eval()'d code:274
Stack trace:
#0 /var/www/avideo/plugin/Customize/sass/scssphp/src/Compiler.php(18) : eval()'d code(1) : eval()'d code(284): ScssPhp\ScssPhp\Formatter->format(Object(ScssPhp\ScssPhp\Formatter\OutputBlock), NULL)
#1 /var/www/avideo/plugin/Customize/sass/compile.php(18) : eval()'d code(1) : eval()'d code(22): ScssPhp\ScssPhp\Compiler->compile('\n@import "asset...')
#2 /var/www/avideo/plugin/Customize/sass/compile.php(18) : eval()'d code(1): eval()
#3 /var/www/avideo/plugin/Customize/sass/compile.php(18): eval()
#4 /var/www/avideo/plugin/Customize/Customize.php(18) : eval()'d code(1) : eval()'d code(54): include('/var/www/avideo...')
#5 /var/www/avideo/plugin/AVideoPlugin.php(541): Customize->getStart()
#6 /var/www/avideo/objects/include_config.php(120): AVideoPlugin::getStart()
#7 /var/www/avideo/videos/configuration.php(39): require_ in /var/www/avideo/plugin/Customize/sass/scssphp/src/Formatter.php(18) : eval()'d code(1) : eval()'d code on line 274`

my website is running on Debian Linux 10 server, Apache version 2.4.38

**Comment by DanielnetoDotCom** [comment]
Did you resolve that?

**Comment by naradwiono** [comment]
I've been looking for this issue because the website is running on version 10.3, after I updated to the latest version this issue was resolved.
