### ISSUE TITLE
Is there a way to change the default Up Next Videos from Newest Upload to Most viewed?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6777]
Is there a way I can change what is displayed to every user by default. New uploads are not good to have there, because sometimes people just upload weird things so it can be next to the video you are watching.

![aa4798b5-65ca-45fc-8dd9-bb035e4514ac](https://user-images.githubusercontent.com/39392449/175295334-8202bac9-747a-4197-919d-dd3ff26db1f2.png)
![73f371ff-1ab3-40ee-8ec1-0008f5e6f8a5](https://user-images.githubusercontent.com/39392449/175295360-d0dac1dc-91ee-45ca-8a5d-9d68c7d1eee2.png)

Would be great to make it the suggested videos or people you subscribe to only maybe?

Just wanting a better default selection of videos listed other than the newest.

**Comment by DanielnetoDotCom** [comment]
Did you try the Autoplay Next Video?

<img width="786" alt="image" src="https://user-images.githubusercontent.com/18009293/175303953-71484502-d6fc-4feb-8510-c6bc48423666.png">

**Comment by JoshWho** [comment]
No I mean default for all guest and logged in

**Comment by JoshWho** [comment]
Im talking about making this default setting the most popular or something
![30e44103-18c9-4cd2-b132-608727c55eb8](https://user-images.githubusercontent.com/39392449/175355899-7e1a5f73-fd88-44a0-990a-8f7244662428.png)

**Comment by JoshWho** [comment]
Sweet thank you @DanielnetoDotCom

**Comment by JoshWho** [comment]
Is there a way to make it the Suggested Star ed videos?

![4258e814-3a91-4947-8be3-b38d648bbe8f](https://user-images.githubusercontent.com/39392449/176039937-2cfabc3e-d806-41dc-86b8-eadfe4d4b676.png)

**Comment by JoshWho** [comment]
Basically just the videos we mark for suggestion.

What I meant by random each page load is show different videos on each page load in that suggestion row next to the playing video.  That way people do not see the exact same videos there every day. 

Honestly would like this just for the guest views, I am just worried about first impressions and people purposely uploading titles with horrible words in it I do not want someone brand new joining and that is the first thing they see as suggested to watch next.

**Comment by DanielnetoDotCom** [comment]
do you mean have an option to sort videos by suggested?

**Comment by JoshWho** [comment]
Yes

> do you mean have an option to sort videos by suggested?

**Comment by DanielnetoDotCom** [comment]
This update may include the suggested

**Comment by JoshWho** [comment]
Sweeet. Thank you

**Comment by DanielnetoDotCom** [comment]
what was the issue ? why reopen?

**Comment by JoshWho** [comment]
OK noticing in a new logged out browser it still shows my old videos now as suggested.

![5137db37-f75a-43f0-9449-ea28e4c0a5b3](https://user-images.githubusercontent.com/39392449/177225904-820917d0-35a5-4043-8de2-2ffbb1bae4e9.png)


Weird part is I can change it to date added then switch it back to Suggested and now it sows the correct ones after doing that.

![95ba1d46-7228-414f-9534-1c314da4f625](https://user-images.githubusercontent.com/39392449/177225947-7c15186a-97fe-445f-b765-263bb4d76e5e.png)

**Comment by JoshWho** [comment]
Once that kink is worked out it is perfect. Will def increase engagements now.

**Comment by DanielnetoDotCom** [comment]
did you try to clear the cache?

**Comment by JoshWho** [comment]
yes that is a different browser

**Comment by DanielnetoDotCom** [comment]
did you change the default order on the plugin?

clear the cache?

**Comment by JoshWho** [comment]
Yes I did all that.

**Comment by JoshWho** [comment]
Go to this link in incogneto  https://www.joshwhotv.com/video/sjw-cringe-compilation-33-women-s-march-and-anti-trump-sjw-cringe-machine/page/1

if you see the videos showing in that picture you will see what I am seeing

**Comment by DanielnetoDotCom** [comment]
I basically remade all the videos list.

not it loads dynamically (avoiding the cache)

**Comment by JoshWho** [comment]
Seems like there is no limit anymore and maybe why it takes time to load

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/39392449/177648175-bac5d552-e749-428f-92e7-f8cfcf09372c.gif)

**Comment by JoshWho** [comment]
This is also causing scripts load errors now. Java keeps freezing

**Comment by DanielnetoDotCom** [comment]
really strange

the infinite scroll should not be there , I will check again

**Comment by DanielnetoDotCom** [comment]
did you make a complete git pull?
did you clear your cache?

**Comment by JoshWho** [comment]
Yes that is a new git pull

**Comment by DanielnetoDotCom** [comment]
Looks like your Customize advanced->videosListRowCount is messeup

any way, I sent you a fix that may prevent that

**Comment by JoshWho** [comment]
Perfect. Works great now.Thank you @DanielnetoDotCom
