### ISSUE TITLE
can't delete install page

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#6778]
Can't find install page to delete. When I go to lblivestream.com site comes up. But when I do basic hack of deleting https in front of lblivestream.com install page shows up... I deleted the install folder, rebooted the server and still the page comes up. Need code to delete page or directory please thank you. And yes I cleared the cache from all of my browsers
![image](https://user-images.githubusercontent.com/37937968/175441242-7ecd4642-ba60-492f-a90d-3bad407d7c9f.png)

**Comment by jengajenga** [comment]
Configure your apache server to serve only from https. Your server is seeing this as two different directories. 
Instead, have a subdomain without https but make sure the domain has https. This is because rtmp won't work with http.
Clear your browser cache as well.

**Comment by Lordblanca** [comment]
[jengajenga](https://github.com/jengajenga) thank you so much for the information. But that does not tell me how to delete the install page

**Comment by JoshWho** [comment]
Look you /var/www you should see s folder that says install and you should also see a file called install.php in the web directory.

**Comment by DanielnetoDotCom** [comment]
If you are seeing different results for  HTTP and HTTPS that means you have some error on your apache/virtual host configuration. 

probably they are pointing to different locations.
