### ISSUE TITLE
all plugins are gone. How to recover?

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo#6781]
![image](https://user-images.githubusercontent.com/56869986/175482159-c58b0654-5bce-4c16-afce-6ca482840a61.png)
tried to load a new plugin. But all the old ones are gone ... and now there is nothing at all. How to display them again?

**Comment by DanielnetoDotCom** [comment]
Check your avideo.log

**Comment by JoshWho** [comment]
You uploaded a wordpress plugin in your plugin directory. Delete it and everything should be fine after that.  https://github.com/WWBN/AVideo/issues/6775#issuecomment-1165291381
