### ISSUE TITLE
BackBlaze Plugin error of 404, related to // in URL of get_download_authorization call

### ISSUE THREAD

**Issue by techgalzar** [WWBN/AVideo#6786]
**Describe the bug**
When using the backBlaze plugin, I receive the following error:
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/108200411/175793280-02aeed17-710a-48b7-879a-c03d28404aec.png">

The reason why this error is ocurring is because the code is calling /v1//b2_get_download_authorization, instead of v1/b2_getdownload_authorization.

Furthermore, a previous ticket was opened by another user regarding this. It was unresolved. Notice the double / in the url.
https://github.com/WWBN/AVideo/issues/6304

**To Reproduce**
    Configure BackBlaze with a  private bucket. 

**Expected behavior**
     From a technical aspect,  the b2_get_Download_authorization method is supposed to return a token.

**Additional context**
Can you please update the code to remove the double slash and release another version for download.

**Comment by DanielnetoDotCom** [comment]
Can you please make sure you have e latest git pull and plugin version?

I remember this error a long time ago from the BACKBLAZE official plugin

**Comment by techgalzar** [comment]
I am using the latest git pull and plugin. Can you verify on your end by downloading the latest plugin from the store and checking the code for a double "//". Thank you.

<img width="214" alt="image" src="https://user-images.githubusercontent.com/108200411/175804152-9fb23785-e15d-40b0-ac2a-1fbb4c46fefc.png">

<img width="434" alt="image" src="https://user-images.githubusercontent.com/108200411/175804187-6cfca9c1-df2d-4268-a444-b2b4442378f6.png">

**Comment by DanielnetoDotCom** [comment]
what I mean the error was on the .../AVideo/vendor/gliterd/backblaze-b2/ folder (composer)

not really on AVideo.

I just search for the b2_get_Download_authorization and there is no reference for it.

I suspect something is outdated on your side

<img width="239" alt="image" src="https://user-images.githubusercontent.com/18009293/175809902-fc32d5cf-0236-42b6-a33a-66e999f30ed6.png">

**Comment by techgalzar** [comment]
Okay, I have done several development work with BackBlaze and have performed several integrations with them. In order to use a "private bucket" you must call the b2_getdownload_authorization function in your code, to receive an authorization token. Your plugin BlackBlaze 3.2 (Back Blaze)  is calling this function but is calling it using // instead.  Can you show me a working example? 

Is BlackBlaze 3.2 the latest version. Is can I get a previous version to see if that works?

API 
https://www.backblaze.com/b2/docs/b2_get_download_authorization.html

**Comment by techgalzar** [comment]
I noticed this too. When I  search glitterd, I get the same behavior, the b2_get_Download_authorization is not found. Why? Becausae it is constructed in the AVideo Blackblaze plugin in hte AVideoB2Client->get_download_authorization method. 

So here is the thing. The change they made on February broke your code.  Instead of removing the Backlash from the  following:

<img width="270" alt="image" src="https://user-images.githubusercontent.com/108200411/175832323-f705e87f-d464-4389-9998-e8f9d511e26b.png">

They  removed the backlash from the other methods in their library. Well, you use B2_API__V1  in get_download_authorization(). So if you remove  the "/" in this method, it should fix it. 


<img width="1135" alt="image" src="https://user-images.githubusercontent.com/108200411/175832181-ab152dce-8373-42d8-925c-b671a8059508.png">

**Comment by DanielnetoDotCom** [comment]
Sorry for making you waste time on it.

 for some reason, I just found the b2_get_Download_authorization 

I am sending version 3.3 which may resolve that.

I am sending it in 15 min
