### ISSUE TITLE
installation Failer 

### ISSUE THREAD

**Issue by schachtuncay** [WWBN/AVideo#6787]
i have the same problem on ubuntu VPS 18.04 and 20.04.

i have install all steps but i can not install AVideo Last Step.

i have the screenshot. 
and Write Unknown Error.

 
![image](https://user-images.githubusercontent.com/12613779/175827240-6ced171e-30f8-4c2f-a34f-94660a99d749.png)

Please can anywone Help Me

**Comment by DanielnetoDotCom** [comment]
Check your apache error log
