### ISSUE TITLE
Can we fix the height of the Big Video carousel so the page doesn't "jump"

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6796]
**Describe the bug**
As the carousel changes, its height can change, shifting all the elements below vertically. 

Especially as the user is scrolled down the page, this is an annoyance - on mobile, videos bounce up and down with no apparent cause.

https://user-images.githubusercontent.com/11711050/176046333-8b40bf35-6694-4cd3-9ba6-67e9aba1b839.mov

**Comment by JoshWho** [comment]
It has something to do with the body text of the video not so much the image.  If the description didn't show so much it would not jump the page like it does.
