### ISSUE TITLE
[Rendering] where is the ellipsis in the video title coming from (gallery)?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6797]
**Describe the bug**
See the hover-over, the video title is getting an ellipsis (…) appended to it.
![Screen Shot 2022-06-27 at 11 11 38 PM](https://user-images.githubusercontent.com/11711050/176106233-994c16ad-f8e9-4a91-b6c0-e69cb22c1fbc.png)
![Screen Shot 2022-06-27 at 11 11 49 PM](https://user-images.githubusercontent.com/11711050/176106230-d49a3701-235d-448a-99e3-df2eeb8a01dc.png)

**Comment by DanielnetoDotCom** [comment]
Problem confirmed, please check this update

**Comment by walt93** [comment]
Fixed, thanks.
