### ISSUE TITLE
[Rendering] Can this layout be extended to 3 (or even 4) lines of video description? (Gallery)

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6798]
![Screen Shot 2022-06-27 at 11 15 28 PM](https://user-images.githubusercontent.com/11711050/176106572-aa0b7162-0334-44d7-af4a-c62c493e055a.png)

**Comment by JoshWho** [comment]
I have mine set on 4

![aa4c31ec-216f-4f71-b099-6d0092e1deab](https://user-images.githubusercontent.com/39392449/176122746-d6fbab39-39f5-4820-a0fa-7a446e21798e.png)

It is a option in the gallery edit function

**Comment by JoshWho** [comment]
you can have up to 6 

![ef3c9e64-a386-4bd4-ac69-23d01ce8d227](https://user-images.githubusercontent.com/39392449/176123109-d789734e-8516-4573-aee3-bb5d34af2ab7.png)

**Comment by DanielnetoDotCom** [comment]
The main problem with the video title is the google SEO requirements.

titles with more than 74 chars, including special chars and icons will be low ranked.

so right now we always cut off to 60 chars to avoid google low rank us

**Comment by GreenDragonTavern** [comment]
Believe he's looking to increase height of video title directly underneath video. His first two videos have a title that wrap to a 3rd line but's only shows very top of 3rd line itself. Could height be a parameter an admin could adjust in Gallery mode?

**Comment by walt93** [comment]
Sorry I wasn't more clear, GreenDragon called it. I think it's just a CSS change? But I don't do front end dev...

**Comment by JoshWho** [comment]
Isn't there a way to make the meta for the bots show different then what we see?

**Comment by DanielnetoDotCom** [comment]
No, the bots were reading the <h*> tag directly

and the inspector was complaining about the long texts and lower-ranking the pages.

I also will review all <h*> tags and organize them better soon

**Comment by walt93** [comment]
I cannot complain about the SEO, my site gets sweet sweet google rank. Let’s not piss off the 🤖 

can we do something about the rendering glitch though? Seems like a CSS thing? 🤷‍♂️
