### ISSUE TITLE
The video after downloading is of poor quality

### ISSUE THREAD

**Issue by palich91** [WWBN/AVideo#6799]
Why the video after downloading is of poor quality. The picture of the video becomes fuzzy?

For example, I upload a video of good quality, and after downloading it is poorly reproduced and clarity is lost. uploading via hls

**Comment by DanielnetoDotCom** [comment]
What do you mean download?

can you please screenshot where are you downloading from?

**Comment by JoshWho** [comment]
did u download the low def version? HLS you should have multiple videos to be listed as a option to download or you are not encoding them correctly
