### ISSUE TITLE
User Groups Permissions

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#6800]
Hello Daniel,
I want to ask if it is possible in the plugin User Groups Permissions to add the file download function
this possibility exists in the category but is visible to everyone
I personally i want to configure this right from the User Groups Permissions plugin as well
I mean that the user who will be in another subscribed group can have the ability to download the file
those who are in the free group may not
if there is any extra cost send me an email

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
Do you mean, that if a user is part of a specific user group he will be able to download any video?

**Comment by wetubeclub** [comment]
yes that's what I mean!!
i.e.
I have a free group and a subscribed group
those who are in the free group do not display the download link
while other users belonging to a subscribed group have the ability to download files

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
Perfect I will send you a quote
