### ISSUE TITLE
Seems that Date added (oldest) and Date added (newest) in Up Next are ... confused

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6801]
**Describe the bug**
Selecting Date Added (oldest), we see that Date Added (newest) is displayed.

When Date Added (newest) is displayed, it is showing videos that are, in fact, oldest.

Here I have selected Date added (newest). It is displaying the oldest media on the site, from 1901, 1936, ...

![Screen Shot 2022-06-29 at 12 43 26 PM](https://user-images.githubusercontent.com/11711050/176525794-6f527fbd-9522-4eb2-bcf1-f77afc496ffa.png)

If I try to select Date added (oldest), as I have tried to do, I can simply re-use the above screenshot. You cannot select Date Added (oldest). Yet, that is what it displays. The logic is vexed.

**Comment by JoshWho** [comment]
Yes I am having that glitch as well. When I change the view from popular back to newist it keeps forcing Oldest instead

**Comment by DanielnetoDotCom** [comment]
This may fix it

**Comment by JoshWho** [comment]
I have to select Oldest to see the newest videos now. When I select Newest it shows the oldest.

![18cea099-f049-4af6-9112-b980d4dd67b1](https://user-images.githubusercontent.com/39392449/177032887-3cbbca59-1db2-4665-ac33-28a43271149f.png)

**Comment by JoshWho** [comment]
Sweet, thank you
