### ISSUE TITLE
Notifications of uploads stopped 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#6803]
Anyone else not getting new video notifications in the past few updates?

**Comment by DanielnetoDotCom** [comment]
Are you talking about uploads from the encoder? direct uploads? embed? all of them?

**Comment by DanielnetoDotCom** [comment]
BTW, when you upload a new video, what is the default status. 

I just checked in the code and it notifies only if the status is Active or unlisted

Inactive  videos will not be notified

**Comment by DanielnetoDotCom** [comment]
what was the issue?

**Comment by fakeologist** [comment]
It may have been working except the emails were being sorted out of my view in my email app.

**Comment by fakeologist** [comment]
Still not getting uploaded video notifications. I am getting live video notifications.

**Comment by DanielnetoDotCom** [comment]
It may be now fixed on the last git pull
