### ISSUE TITLE
Need a way to limit streaming time per user

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#6804]
@DanielnetoDotCom It would be great if we had a way to limit live streaming time per user/per day. With options of 5, 10 and unlimited streaming hours once the limit is exceeded the stream will stop. The clock resets every day.

**Comment by DanielnetoDotCom** [comment]
the best way would be if Nginx has some configuration to help that. currently, I do not know any.

maybe a way to develop a crontab to check it every minute and drop the live if it exceeds the limit. but it won't be an easy development. currently, the only way for me to develop it is if you sponsor this feature.

**Comment by DanielnetoDotCom** [comment]
Please email me and I will quote for you

**Comment by GarethBagley** [comment]
I like this development. Make sure it can be adjusted via the account levels so free accounts have limited time and pro accounts have another value.
I can share in this.
@DanielnetoDotCom
