### ISSUE TITLE
360 Video - How to add video 360 view

### ISSUE THREAD

**Issue by gamersalpha** [WWBN/AVideo#6808]
Hello there, 

i add some 360 video on my avideo platforme for home use

but when i push the video i don't have the 360 view like we see here : 
https://www.youtube.com/watch?v=hNAbQYU0wpg

i got this view on my home use platforme 👍 
![image](https://user-images.githubusercontent.com/32466950/176991837-86657d42-da25-4131-8492-e606f2f36434.png)

how activate a 360 ° view on Avideo 

thanks

**Comment by GarethBagley** [comment]
Hi there.
Test this using google chrome as your web browser.

**Comment by gamersalpha** [comment]
Hello not working in chrome to


i like to see avideo using : 

https://github.com/videojs/video.js

and looks like not work with 360 videos :'(

**Comment by DanielnetoDotCom** [comment]
@gamersalpha 

you MUST use the encoder and self-host the video using MP4 format.

videos hosted somewhere else the 360 will not work

**Comment by gamersalpha** [comment]
Hello, 

well i upluad the 360 video with avideo-encoder and the video is MP4 format : 

![image](https://user-images.githubusercontent.com/32466950/178153512-d94e116e-4125-4b56-852f-6bc3178fb094.png)

**Comment by DanielnetoDotCom** [comment]
Also a HTTPS is required, it will not work on HTTP (also do not work with Cloudflare proxy)

**Comment by gamersalpha** [comment]
Hello for sur i got my ssl certificat OK
