### ISSUE TITLE
iframe allow only certain domains with private videos

### ISSUE THREAD

**Issue by eortigoza5** [WWBN/AVideo#6810]
Hi,
nice platform
**Is your feature request related to a problem? Please describe.**
I have a feature reques, this is not a problem, 
I search in the marketplace site  https://youphp.tube/marketplace/
a plugin like PayPerView    but with the option to show video on specific extra domain
but I want a video as private video 
and the iframe allow only certain domains 
with this condition I or peoples-users can have private videos and share videos only on specific domains
or have public videos in the main domain and permit share iframe-videos only on specific domains
or to protec or  limit display of iframe from an external site,
 specific domains only for save bandwidth, etc.

please consider this reques, and thanks for make this platform every day best platform

**Describe the solution you'd like**
I found on the web some little code HTTP_REFERER header may can help for fast solution
`<?php

$allowed_domains = array(
        'a-good-domain.com',
        'another-nice-one.org',
        );

$allowed = false;
foreach ($allowed_domains as $a) {
    if (preg_match("@https?://$a/.*@", $_SERVER['HTTP_REFERER'])) {
        $allowed = true;
    } 
}

if ($allowed) 
    echo "Nice domain";
else
    echo "Ugly domain";
`

**Comment by DanielnetoDotCom** [comment]
Check the **embedWhiteList** on this link https://github.com/WWBN/AVideo/wiki/SecureVideosDirectory-Plugin#restrict-embed-videos

**Comment by eortigoza5** [comment]
thanks..
