### ISSUE TITLE
About using and publishing the original LDAP plug-in I developed

### ISSUE THREAD

**Issue by designet-inc** [WWBN/AVideo#6811]
**Describe the question**
We purchased a paid LDAP plugin. However, the method of authentication was different from what we were looking for.

Therefore, I am thinking of developing an LDAP plug-in that performs the following processing.
As a premise, consider the following settings.

```
ldapServer: LDAP Server IP addr
ldapPort: LDAP port
bindDn: LDAP manager dn
bindPw: manager password
baseDn: LDAP searchBase dn
searchFilter: LDAP serch filter: (uid=%s)
firstNameAttr: LDAP attribute
lastNameAttr: LDAPattribute
emailAttr: LDAPattribute
```

Authentication flow

0. The user logs in with a form on the web (like the current LDAP plugin)
1. Bind with LDAP manager
2. Use the searchFilter and login ID to search LDAP.
3. Get the user's dn from the search results
4. Try LDAP bind using the user's dn and password
5. If the authentication is successful, use the setting LDAP attributes to register the user.
6. Authentication is OK

Isn't it a license violation for us to make such a plugin?
Is it okay to publish this plugin as open source?

We want to protect your interests. However, we would like to respond to the requests of us and our customers.
I would appreciate it if you could tell me what you can do.

**Comment by DanielnetoDotCom** [comment]
Thanks for your post

As long as you do not unencrypt and share my plugin code, there is no problem with it.

> Isn't it a license violation for us to make such a plugin?

feel free to do it, no problem at all, I also incentive you to create new plugins
https://github.com/WWBN/AVideo/wiki/How-to-code-a-AVideo-Platform-plugin

> Is it okay to publish this plugin as open source?

no problem, at all

**Comment by designet-inc** [comment]
I appreciate your approval.
