### ISSUE TITLE
Invalid default value for 'created'

### ISSUE THREAD

**Issue by Ritbit** [WWBN/AVideo#6817]
**Describe the bug**
During installation on a clean system and database the installer fails midway.

The PHP-error logs shows:

`
[04-Jul-2022 11:06:48 UTC] Installation: 9 {"webSiteRootURL":"https:\/\/videocenter.domain.org\/","systemRootPath":"\/var\/www\/videocenter\/AVideo\/","webSiteTitle":"VideoCenter","databaseHost":"localhost","databasePort":"3306","databaseUser":"AVideo","databasePass":"XXXXXXXXXXXXXXXX","databaseName":"AVideo","mainLanguage":"us","systemAdminPass":"XXXXXXXXXXXX","contactEmail":"XXXXXXXXXXXXXX","createTables":"2"}
[04-Jul-2022 11:06:48 UTC] Installation: 20
[04-Jul-2022 11:06:48 UTC] Installation: 33
[04-Jul-2022 11:06:48 UTC] Installation: 45
[04-Jul-2022 11:06:48 UTC] Installation: 55
[04-Jul-2022 11:06:48 UTC] Installation: 57
[04-Jul-2022 11:06:48 UTC] Installation: 66
[04-Jul-2022 11:06:48 UTC] Installation: 74
[04-Jul-2022 11:06:48 UTC] PHP Fatal error:  Uncaught mysqli_sql_exception: Invalid default value for 'created' in /var/www/videocenter/AVideo/install/checkConfiguration.php:89
Stack trace:
#0 /var/www/videocenter/AVideo/install/checkConfiguration.php(89): mysqli->query()
#1 {main}
  thrown in /var/www/videocenter/AVideo/install/checkConfiguration.php on line 89
`

**To Reproduce**
1. drop database and recreate
2. Start AVideo installer and input all fields with sane data
3. Installer will show message stating "Generic Error"
4. See PHP errorlog

**Expected behavior**
Installer should finish or at least show a more comprehensive error that just stating "Sorry!
Unknown error!"

**Error Logs**
See the attached part of PHP errorlog above.

**Desktop:**
 - OS: Linux / Red Hat Enterprise Linux Server release 7.9.2009 (Maipo)
 - GoogleChrome 103.0.5060.53 (
 - PHP version 8.1.7 (remi-safe)
 - MariaDB 5.5.68
 - Apache 2.4.6

**Comment by Ritbit** [comment]
Replace mariadb 5.5 for 10.5 and now it works... <sigh>

Please update requirements on website as that states "MySQL 5.0+" after that you can close issue.

**Comment by Ritbit** [comment]
I also noticed AVideo prefer XSendfile..  
Please note XSendfile is obsoleted on modern(2.4+) Apache installs. 
Apache 2.2 is EOL since July 2017.

**Comment by Ritbit** [comment]
Well, XSendFile itself is not obsolete but the module is...

The module it self seems unmaintained for 10 years so its better not to use it at all. (very likely to be insecure by now): 
see  https://github.com/nmaier/mod_xsendfile
  
Apache2.4 has build in sendfile options, but it's slightly different from the plugin but native at lest. (see https://serverfault.com/questions/879130/is-mod-xsendfile-deprecated)

So as long as nobody want to maintain and adapt the XSendFile module for Apache 2.4+ you are forced to use an obsolete apache version. Which is falling behind in both features and security.

So best is to support current webservers like Apache 2.4+ or nginx  0.8.12+ which both have native support for sendfile.

* apache 2.4: https://httpd.apache.org/docs/2.4/mod/core.html#enablesendfile
* nginx: https://www.nginx.com/resources/wiki/start/topics/examples/xsendfile/
  and http://nginx.org/en/docs/http/ngx_http_core_module.html#sendfile

**Comment by DanielnetoDotCom** [comment]
So I guess the only move is to not install XSendFile on apache 2.4 and we should be good as long as this version already has the same feature

**Comment by Ritbit** [comment]
yes, seems so. Only advise uses to enable the sendfile setting in their server.
I have tested it myself and it seems to work fine so far.
