### ISSUE TITLE
E-mail notifications problem

### ISSUE THREAD

**Issue by GarethBagley** [WWBN/AVideo#6821]
The e-mail notifications are not working. Google have apparently changed some security settings and the mails are not geting through.

We really need this feature to work. 
Anybody know how we can fix the problem?
Maybe with new SMTP settings or something?

Thanks for any help we can get.
/Gareth

**Comment by walt93** [comment]
Not the answer you wanted but my recommendation is to avoid Google at all costs (in all areas). I use Mailgun & have no issues.

**Comment by GarethBagley** [comment]
> Not the answer you wanted but my recommendation is to avoid Google at all costs (in all areas). I use Mailgun & have no issues.

Thanks. Totally agree.
