### ISSUE TITLE
Question for Roku channel hosters. How much bandwidth / server iron did you build, or do you use CDN?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6823]
**Describe the question**
Looking into getting serious about putting up a Roku channel. Looking for specific advice as to how much network to build, what kind of numbers are people seeing, should I be focused on building big network as in 10Gbit/sec ports, or are people doing this with CDN? Any and all advice/suggestions/comments are welcome.

**Comment by walt93** [comment]
There is the cost of CDN vs building big network ports. I’m trying to get a handle on which way to go.

**Comment by JoshWho** [comment]
CDN is  must
