### ISSUE TITLE
homepage infinities scroll seems stuck

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6825]
After latest update, when I scroll down it never loads the next row. 

![cb404172-6104-43d1-bbfc-8789c36c76e7](https://user-images.githubusercontent.com/39392449/177671466-16665759-dcf1-40be-a4e8-0b89c1a43cff.png)

**Comment by DanielnetoDotCom** [comment]
I am sorry for that, this may resolve the issue

**Comment by JoshWho** [comment]
Live streaming seems broke too now. Not sure what is going on

**Comment by DanielnetoDotCom** [comment]
what link?

**Comment by DanielnetoDotCom** [comment]
make sure you make a git pull from 5 min ago.

there were a lot of changes regarding passwords and security. 

there is no way back, soon I will release more details (CISCO TALOS help)

**Comment by JoshWho** [comment]
Says I have the latest

**Comment by DanielnetoDotCom** [comment]
checking

**Comment by DanielnetoDotCom** [comment]
Update and try again please

**Comment by JoshWho** [comment]
Yup all fixed. Thank you
