### ISSUE TITLE
all embed video now 403

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6826]
![60703cbc-87fc-4083-b98c-7bc205e8f6f4](https://user-images.githubusercontent.com/39392449/177675201-f96215bc-5a5a-4666-9a91-a6e128e303de.png)

**Comment by JoshWho** [comment]
Test this here https://www.w3schools.com/html/tryit.asp?filename=tryhtml_intro

`<div class="embed-responsive embed-responsive-16by9"><iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;" src="https://www.joshwhotv.com/vEmbed/.QCMo2Q?modestbranding=1&showinfo=1&autoplay=&controls=1&loop=&mute=&t=0&objectFit=" frameborder="0" allowfullscreen="allowfullscreen" allow="autoplay" scrolling="no"></iframe></div>`

**Comment by DanielnetoDotCom** [comment]
please check the logs where is saying 
`
forbidIfRequestDoesNotComesFromSameDomainAsMyAVideo: ....`

**Comment by JoshWho** [comment]
what does that mean?

**Comment by DanielnetoDotCom** [comment]
try this update now

**Comment by JoshWho** [comment]
nope still doing it

**Comment by DanielnetoDotCom** [comment]
Right now we basically deny almost all delete and save requests that come from outside your site

Iframe is from outside

please try again now

**Comment by JoshWho** [comment]
Nope still the same.

**Comment by DanielnetoDotCom** [comment]
again

**Comment by JoshWho** [comment]
Working now

**Comment by DanielnetoDotCom** [comment]
Also make sure you update your encoders to version 4.0
