### ISSUE TITLE
Make the Auto Play Next video pick from the Suggested Videos

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6827]
Just like the video list by the player can the Auto Next video also be a random selection from the suggested videos as well?

![3b6913e2-e18f-4dee-8239-fd2eec34e66d](https://user-images.githubusercontent.com/39392449/177786679-f0cbb22d-f03a-4bd1-a540-78ef85e79dd7.png)

**Comment by DanielnetoDotCom** [comment]
I am sending an update that may do the trick

**Comment by DanielnetoDotCom** [comment]
No, 

the order of autoplay choice is ...

1. Next video seted on the video itself
2. random Suggested 
3. random video
