### ISSUE TITLE
Update to 12.0, correct or not?

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6835]
Hi @DanielnetoDotCom , I was able to successfully upgrade from version 11.7, to version 11.8 and the current 12.0. Everything worked correctly.

But I checked that the system still asks for the 12.0 update, this is a Bug or I'm not really on the 12.0 version, I was confused.

![image](https://user-images.githubusercontent.com/37880073/178019367-3498b6d5-61f6-40d5-ab11-9250de8d55b2.png)

**Comment by DanielnetoDotCom** [comment]
Hi

I guess with a clear cache or logoff and login it should be resolved 

also make sure you update the encoder

**Comment by gbrn** [comment]
It really was a cache issue. Thanks.
