### ISSUE TITLE
can't make new user 

### ISSUE THREAD

**Issue by Tinoisthe** [WWBN/AVideo#6841]
**Describe the question**
A clear and concise description of what is your question.
can't make a new user account with login 
**Screenshots**
Provide some screenshots to help us understand and explain your problem.

https://user-images.githubusercontent.com/76804686/178143079-83e5c73b-3965-4dbb-819c-9f21754b46e2.mp4

**Comment by DanielnetoDotCom** [comment]
without logs, I cannot help you

also click on the captcha refresh button and try again

**Comment by Tinoisthe** [comment]
captcha refresh button does nothing

and it is showing wrong  captcha 
![Inked22111](https://user-images.githubusercontent.com/76804686/178168020-ca0ff221-9eb8-4362-b83d-af27c8e58c87.jpg)
![c867f49e9c2aea9e429ca845686bd397fc208208e000e1c7af551d3b06864671](https://user-images.githubusercontent.com/76804686/178168029-7fcd9fe7-c55f-4230-8f55-1e6b409fa130.png)

**Comment by Tinoisthe** [comment]
fixed it with new update thank you
