### ISSUE TITLE
Loads of bugs since 12.0

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#6842]
Captcha on registration is now broken. You enter it (case sensitive) and it just complains every time now, so basically I'm getting loads of emails saying they cant register so i am loosing new members which are hard enough to get anyway.

The AVencoderNetwork is now also broken. It just hangs on load. I have reinstalled the encoder and avideonetwork and it will not work now. It was working fine before upload. Ive attached a screen shot.

Leaving peoples channel has also stopped working. If you look at the screen shot of the video load page, to the right where the users name is 'arch' and their is a cross to click on to go back to recent videos/popular ect but now it doesn't work and it did work before update.

You will see in that video page screen shot that their is a grey video box that loads on its own first and stays there for about 2 seconds and then the videos load in the side bar with new animations. This looks ugly when the blank thumbnail loads on its own for some bizarre reason. My user activity has dropped vastly since update which makes me think something is wrong  with my site now.
![Screenshot 2022-07-10 at 14 08 57](https://user-images.githubusercontent.com/107706817/178146733-95f37c4e-1024-49f4-b9ef-4ccfd66c998c.png)
![Screenshot 2022-07-10 at 14 12 27](https://user-images.githubusercontent.com/107706817/178146740-49c24e13-2a60-4805-be98-e39f81455f73.png)
![Screenshot 2022-07-10 at 14 18 47](https://user-images.githubusercontent.com/107706817/178146747-f5713696-54c5-45e2-9b28-9a4c37f0fbfa.png)

**Comment by para2022** [comment]
Ive just had this bug reported to me also from a user:

Hi Mate, how come that I’m listed on the channel list with only 854 views in the last 30 days. This is not correct because I had 5,000+ views.

**Comment by DanielnetoDotCom** [comment]
sorry no logs, I cannot help you

**Comment by DanielnetoDotCom** [comment]
Also I do not know what page is that. can you reproduce it on demo site?

**Comment by DanielnetoDotCom** [comment]
Hold on, I found something.

**Comment by para2022** [comment]
The capcha is broken. Just installed on a fresh site different server. Same error.

**Comment by para2022** [comment]
No errors show in the log Daniel which is why i didnt post them. I replicate the error with captcha then check the logs but nothing.

**Comment by para2022** [comment]
[10-Jul-2022 14:40:17 Europe/London] AVideoLog::DEBUG: Captcha validation Error: you type (JBG6b) and session is (2h4fx)- session_name da1e4d2cc1d52ccff2b00f3ab71db1e0 session_id: 79vbr91utt38757o9i7sb45acc SCRIPT_NAME: /objects/userCreate.json.php
 
Sorry mate

**Comment by DanielnetoDotCom** [comment]
I found something, I am working on it

**Comment by para2022** [comment]
Thank you Daniel :)

**Comment by para2022** [comment]
I keep seeing this in the encoder log too.

[10-Jul-2022 14:33:12 Europe/London] PHP Warning:  Undefined array key 2 in objects/functions.php on line 463 (edited to remove real path)

**Comment by DanielnetoDotCom** [comment]
please try this update

**Comment by para2022** [comment]
That fixed the capcha Daniel thank you.

I still get this error on the AVideo-Encoder-Network login. I get the error on a fresh install also. It will work with just the basic encoder and i can login but when i use AVideo-Encoder-Network it simply will not login and nothing is in the logs. This was working fine. Thanks.
![Uploading Screenshot 2022-07-10 at 15.55.59.png…]()

**Comment by DanielnetoDotCom** [comment]
I just sent an update to the Streamer and also to the encoder network. 

it may resolve the installation

what is exactly the problem with the chat and signup agreement?

**Comment by para2022** [comment]
Signup agreement i removed the plugin from the plugin dir and removed the database entry for a fresh install and this did not help. When i make a new entry in the signup agreement nothing pops up. It saves the title but will not save the actuall message which is why it will not display.

Chat simply wont show on a live stream where it is set to display, where it should be on the page is just a blank space. The plugin is there however but the chat doesn't display. You can see in the image where the blank space is where the chat should display.
![Screenshot 2022-07-10 at 16 24 43](https://user-images.githubusercontent.com/107706817/178151319-6e0dfac0-1605-4b65-9da9-2cbff5154a20.png)

**Comment by DanielnetoDotCom** [comment]
I found a couple of more issues on encoder and encoder network, please update again

**Comment by para2022** [comment]
Sorry Daniel i tried updating again but it says already up to date. I still have the processing error.

**Comment by para2022** [comment]
If i type in the network encoder in the url and login that way it works. If i try from the actual encoder tab on the site it cannot login and is stuck on processing, so it appears to be a problem with the way it logs it via the tab, if typing in the url to the network encoder and logging in with my username and password i can get to the network encoder fine. Hope this helps.

**Comment by DanielnetoDotCom** [comment]
You may need to download SignUpAgreement version 3.0
make sure the Encoder/Streamer/Network are up to date

after that clear your streamer cache and try again

**Comment by para2022** [comment]
Still no joy with AVideo-Encoder-Network i have updated encoder and AVideo-Encoder-Network and the site, cleared caches. Now i dont get the processing status it is just a dimmed screen and hangs at login. The problem is only with AVideo-Encoder-Network not the encoder. If i just use the encoder and not AVideo-Encoder-Network it will login.

**Comment by DanielnetoDotCom** [comment]
please screenshot the network and also check the JS log

if you can please share the network URL here and also a username and pass for testing

**Comment by para2022** [comment]
Signup agreement still not working after updated plugin. Now the socket stopped working after latest commit. I have even rebooted my server. Im going to leave it broken until everything is fixed as everywhere i go now i find new bugs appearing that was not there previously. It's just going to take forever to report them and fix them. It was all working fine before 12 update now i have a very broken site. Ive had to abandon network encoder as its clearly broken and just use the normal encoder.

**Comment by DanielnetoDotCom** [comment]
Update 12 is required from now on

https://github.com/WWBN/AVideo/issues/6830

if you can share your url I may be able to see something

**Comment by para2022** [comment]
I would but now i have to keep the network encoder turned off now as I'm getting tired of email complaints if i turn it back on for testing they will try and use it and start kicking off again. A user just did a 2 hour stream and it wouldn't save so he emailed in very angry saying he wont bother next time and that i should stop messing with the site when it was working. :(

**Comment by DanielnetoDotCom** [comment]
You can test the network without enable it on the streamer

**Comment by para2022** [comment]
I know. As i said earlier if i go to the network address https://ourtube.co.uk/network/ and login i can get to the network encoder, no problem. It is the upload link on the streamer site since update that blocks login. That is whats breaking the network encoder and preventing login and causing it to endlessly hang. The streamer sites upload link is this https://ourtube.co.uk/i/network/ (it has a /i/ in the path). Ive turned iframe off so it's nothing to do with that. 

The standard encoder, if i click the upload link on the streamer site, it works fine. This problem is only affecting the encoder network.

**Comment by para2022** [comment]
I kinda have it working now. If i remove the forward slash after the URL of the network encoder in advanced settings then click the upload link it takes me to the network encoder login page. Auto login is broken but auto login works on the standard encoder. If i put the forward slash after the URL it tries to auto login but hangs forever. If i remove it i have to login to the network encoder page and after that if i go back im still logged in and dont have to login again. Its not perfect but a work around for now.

**Comment by loso20p** [comment]
is 12.0 stable  to upgrade to yet?
