### ISSUE TITLE
Encoder question: How to set the number of cores it uses?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6844]
**Describe the question**
We're installing a new encoder on a 4-core box shared with an AVideo install. So by default it's going to use 50% of the cores.

For some time, I want to turn it up so it uses all four cores (won't be using the AVideo side for a while, might as well enjoy a faster encoder)

Later, I want to turn it down so it uses two cores.

How to configure this?

**Comment by DanielnetoDotCom** [comment]
On the encoder, we do not specify the cores. but you can specify how many parallels the process.

by default the encoder will try to use 100% of the CPU

check `$global['concurrent'] ` here https://github.com/WWBN/AVideo-Encoder/wiki/Configuration.php-variable-(-some-are-hidden-)
