### ISSUE TITLE
Question re>Roku JSON

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6845]
**Describe the question**
I seem to be able to import into the Roku direct publisher directly from the [Roku] export link in the Categories page.

Are there other ways of making Roku JSONs, or is it only by category?

Use case is I want to make a channel that's mixed from a bunch of different categories.

**Comment by DanielnetoDotCom** [comment]
I have plans to let you create the roku/mrss feeds from playlists (future, there is no ETA for that)
