### ISSUE TITLE
Version Updates

### ISSUE THREAD

**Issue by JamesMyer123** [WWBN/AVideo#6849]
If you have paid a developer to fix bugs or add features , when you do a Repository Upgrade / update will that delete all the developers work?

**Comment by DanielnetoDotCom** [comment]
If you do not submit the changes as a pull request, you may loose everything

**Comment by JamesMyer123** [comment]
OK so how does that work,?

**Comment by walt93** [comment]
The workflow I use, as a developer, is I keep my changes locally, do a "git stash" to put my changes aside, the "git pull" to get Daniels latest, then a "git stash pop" to put my changes back. If there are merge conflicts, I sort them out. **You: do not try this at home, have you developer do it, you will not understand how to "undo" if you make mistakes - your dev should already know all of this **

**Comment by JamesMyer123** [comment]
My developer says he needs Repo access permissions , so how do we get that?

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by DanielnetoDotCom** [comment]
If he read the link I sent you above he will realize he does not need it.
