### ISSUE TITLE
Cannot access network encoders

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6850]
After updating the system today I cannot access the network encoders, it just hangs in the login screen:

![Screen Shot 5782-11-12 at 21 20 06](https://user-images.githubusercontent.com/58882903/178331715-19cfaea7-0430-4191-86fe-cfd3b4e206f1.jpg)

![Screen Shot 5782-11-12 at 21 21 44](https://user-images.githubusercontent.com/58882903/178331827-2b18bb0e-62b0-4f33-af54-b05b6d4c4440.jpg)

**Comment by guymass** [comment]
I have done a git pull and also updated all plugins that needed an update

**Comment by guymass** [comment]
OK I think I know what to do, i will feedback if it works again.

**Comment by guymass** [comment]
OK I also made a git pull on the server running the network encoder but still I get the same issue. All plugins from the shop are updated, the site is version 12 and encoder is version 4, so everything is updated.

**Comment by DanielnetoDotCom** [comment]
that explains the problem, the HTTPS is required for your encoder

**Comment by guymass** [comment]
It has https, it was working fine until the update, not sure really what changed.

**Comment by guymass** [comment]
Sorry I need to reopen this as again the network encoders IFrame will not open and gets stuck on login screen. Here is a screenshot again.
![Screen Shot 5782-11-16 at 11 28 40](https://user-images.githubusercontent.com/58882903/179184915-e9512a2e-b2cf-48ad-8407-7d95a58156a3.jpg)

**Comment by guymass** [comment]
No problem accessing directly through the encoders subdomain url:
![Screen Shot 5782-11-16 at 11 43 25](https://user-images.githubusercontent.com/58882903/179187789-2c4aae19-2606-40cf-a629-4f398fdf9565.jpg)

**Comment by guymass** [comment]
Maybe it is related issue with the Editor's advanced tab iframe. Once I git pull the fix you made, that was working and the Network encoders iframe stopped to work again after it was OK after previous git pull, so maybe they are somehow effecting each other.

**Comment by DanielnetoDotCom** [comment]
Please again, make sure you 

# use HTTPS NOT HTTP, otherwise it will never work

remove your encoders from the network database and add them again with the HTTPS

**Comment by guymass** [comment]
My encoder config is just fine, this is something else:
![Screen Shot 5782-11-16 at 18 32 14](https://user-images.githubusercontent.com/58882903/179256685-7c838edd-128a-483d-81d0-fa1b2f4594a5.jpg)

**Comment by guymass** [comment]
Now this is all I see in console:
![Screen Shot 5782-11-16 at 19 00 13](https://user-images.githubusercontent.com/58882903/179261883-29e5d625-4d08-45a1-b1a3-7e1536da840d.jpg)

**Comment by DanielnetoDotCom** [comment]
can you drop the encoder network database and create it again?

I suspect your first record is the HTTP site.

**Comment by guymass** [comment]
Well this is not needed because everything was working great for weeks now without any issue until we had to git pull for security and update. The server were always put it with https, there is no reason for it to be http.  I would prefer not to and please check if there might be any other reason. The iframe to my understanding it taking the url I put in site settings and for some reason that is not opening in the iframe /i/network

**Comment by DanielnetoDotCom** [comment]
so check your table `streamers `on your network database

again, I am pretty sure there is some http:... there

if oyu want just update the records on the streamers table

**Comment by guymass** [comment]
OK I found one bad entry there and changed it with the following command:

update streamers set siteURL = "https://alive528.com/" where siteURL = "http://live.ahava528.com/";

Now all entries have https, and still the encoders iframe will now load. Now all I see in console is:
![Screen Shot 5782-11-16 at 23 02 36](https://user-images.githubusercontent.com/58882903/179302385-8145bf7a-b269-41cb-b7fa-274d510b0106.jpg)

**Comment by guymass** [comment]
Trying from our second site I get the same issue and nothing in console:

![Screen Shot 5782-11-16 at 23 15 27](https://user-images.githubusercontent.com/58882903/179304185-46c1197d-f817-46e7-9ccd-788c5623bffe.jpg)

**Comment by DanielnetoDotCom** [comment]
Ok, 

can you please check the logs from the network (apache), encoder, and streamer?

**Comment by guymass** [comment]
This is how my config looks like again:
![Screen Shot 5782-11-16 at 23 26 15](https://user-images.githubusercontent.com/58882903/179305647-b0eb5d90-72ab-4eab-80ab-63a5ecb4edb6.jpg)

Regarding logs I will see what I can find odd and post it here.

**Comment by guymass** [comment]
Also those options are set:

![Screen Shot 5782-11-16 at 23 41 11](https://user-images.githubusercontent.com/58882903/179307639-c7a24b3f-4a63-459b-bfaa-7f9e62f9ffe4.jpg)

![Screen Shot 5782-11-16 at 23 41 39](https://user-images.githubusercontent.com/58882903/179307629-40ba8b9e-2582-43b8-b8b9-add101cf5263.jpg)

**Comment by guymass** [comment]
![Screen Shot 5782-11-17 at 0 52 49](https://user-images.githubusercontent.com/58882903/179315975-fad66be6-1285-49c3-9439-526472bf4420.jpg)

**Comment by guymass** [comment]
This looks odd, there is a typo and maybe a bug.
![Screen Shot 5782-11-17 at 1 06 20](https://user-images.githubusercontent.com/58882903/179317402-7d586d04-22a8-43c2-a6b7-bf368024e22d.jpg)

**Comment by guymass** [comment]
I don't know why its like this, getting those files through http and not https, the whole domain is run under https.

![Screen Shot 5782-11-17 at 2 27 41](https://user-images.githubusercontent.com/58882903/179324006-9922081f-e454-47c0-a76a-bfff1ce18526.jpg)

**Comment by DanielnetoDotCom** [comment]
check your EncoderNetwork/configuration.php

$global['webSiteRootURL'] is using http instead of https

**Comment by GreenDragonTavern** [comment]
guymass, try this. Update Encoder Network database. Table ***streamers*** field ***pass*** and change from varchar(45) to varchar(255). There are probably records but the ***pass*** field data is incorrect. Your individual encoders have the correct passwords, you can either copy them and update on Encoder Network or remove and let Encoder Network recreate records with correct data. The ***pass** data should start with _user_hash_. I went thru same issue just yesterday,

**Comment by guymass** [comment]
Thank you [GreenDragonTavern](https://github.com/GreenDragonTavern) thia did the trick all is working fine now.

[DanielnetoDotCom](https://github.com/DanielnetoDotCom) You should fix that field to varchar(255) in the installation database.sql

Again much thanks, I would have never found this without your help.
