### ISSUE TITLE
Hebrew video titles are not being saved

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6851]
I cannot use Hebrew in video/post titles anymore, for some reason they are now being turned into a number like this: 
62cc6b9b709b4 
![Screen Shot 5782-11-12 at 21 29 08](https://user-images.githubusercontent.com/58882903/178333537-6f55169b-4576-4b59-af30-637939ccdae4.jpg)

**Comment by DanielnetoDotCom** [comment]
Please detail step by step how you are adding it and please give me a word example so I can try to reproduce it.

also try to reproduce on demo site

**Comment by guymass** [comment]
I was uploading a file through this page:

![Screen Shot 5782-11-13 at 17 38 50](https://user-images.githubusercontent.com/58882903/178516694-673a2196-5088-432d-bf4e-7f45181c734d.jpg)

Just gave it a title and when the file was created it gave me that number string, trying to reedit the name and save didn't do anything.

You can try this Hebrew line:

כותרת לסרטון וידאו בעברית

**Comment by guymass** [comment]
OK I updated again (git pull) and tied to change the title to Hebrew and now it was saving OK, so maybe its fixed.
