### ISSUE TITLE
Fresh install of V12 is messing up local connection 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6854]

**Comment by milehighkaraoke** [comment]
Different browser worked. . 
All my on publish is not working 
![20220711_152938](https://user-images.githubusercontent.com/70327833/178362592-d99cd6a8-14d9-4942-a48d-fb7b3346a69b.jpg)
![20220711_152811](https://user-images.githubusercontent.com/70327833/178362596-f0aaac04-a76e-4763-b19a-923f480a14bf.jpg)

**Comment by milehighkaraoke** [comment]
![20220711_153648](https://user-images.githubusercontent.com/70327833/178362832-14c438aa-d6c7-4dab-93de-f9bd23584f5b.jpg)

**Comment by milehighkaraoke** [comment]
Stat page also not working

**Comment by milehighkaraoke** [comment]
And I am guessing this is also the reason my socket will not connect

**Comment by DanielnetoDotCom** [comment]
your installation seems to be totally wrong.

what you are showing does not make sense

missing the first steps and probably all subsequent

**Comment by milehighkaraoke** [comment]
mhktube com  works

**Comment by milehighkaraoke** [comment]
What did I miss?

**Comment by milehighkaraoke** [comment]
This is my 3rd go at risk with the exact same outcome.  I used the same install methods that I have been using since version 7

**Comment by DanielnetoDotCom** [comment]
Looks like your apache did not install correctly. maybe some missing modules

I do not know what is missing.
