### ISSUE TITLE
[Documentation] In /admin while uploading plug-ins the documentation given is slightly incorrect

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6856]
**Describe the bug**
Missing text "sudo"

![Screen Shot 2022-07-11 at 3 43 01 PM](https://user-images.githubusercontent.com/11711050/178371000-856016d6-f19a-4e39-9270-da355e55589b.png)

Pedantic? Guilty as charged.

**Comment by DanielnetoDotCom** [comment]
Just copy and paste. 

do not forget to add sudo before the commands

**Comment by walt93** [comment]
That's my point. You need a sudo after the && and before the chmod. So you can't copy paste.

**Comment by DanielnetoDotCom** [comment]
Thanks, just sent an update
