### ISSUE TITLE
OneSignal Test issues

### ISSUE THREAD

**Issue by JamesMyer123** [WWBN/AVideo#6857]
I get this issue when I press Test OneSignal

Testing one signal
array(4) { ["type"]=> int(1) ["message"]=> string(597) "Uncaught Error: Class 'OneSignal\Config' not found in /var/www/******/plugin/Notifications/Notifications.php(18) : eval()'d code(1) : eval()'d code:498 Stack trace: #0 /var/www/******/plugin/Notifications/Notifications.php(18) : eval()'d code(1) : eval()'d code(469): Notifications->getOpenSignal() #1 /var/www/*******/plugin/Notifications/test.php(18) : eval()'d code(1) : eval()'d code(12): Notifications->sendOneSignal() #2 /var/www/******/plugin/Notifications/test.php(18) : eval()'d code(1): eval() #3 /var/www/******/plugin/Notifications/test.php(18): eval() #4 {main} thrown" ["file"]=> string(96) "/var/www/*****/plugin/Notifications/Notifications.php(18) : eval()'d code(1) : eval()'d code" ["line"]=> int(498) }

**Comment by DanielnetoDotCom** [comment]
Are you running version 12?

did you use git clone to install?

**Comment by JamesMyer123** [comment]
No, we are going to update asap.

**Comment by JamesMyer123** [comment]
I don't see Version 12 in the Versions page , only goes up to 11.6

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform
