### ISSUE TITLE
Editor Advanced Tab doesn't open

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6862]
Opening a video post with Edit and then trying to open the advanced tab leads me to this page.

The advanced tab here:

![Screen Shot 5782-11-13 at 18 07 09](https://user-images.githubusercontent.com/58882903/178523752-5c6c5eb0-ed6e-4a6f-a190-ad73964a88e8.jpg)

Leads to this:
![Screen Shot 5782-11-13 at 18 09 25](https://user-images.githubusercontent.com/58882903/178523875-edf21253-4c85-4803-ad75-432bf0c2f3d7.jpg)

**Comment by TLCReuver** [comment]
Here the same problem with 'Advanced'_button

**Comment by guymass** [comment]
Much thanks, its fixed.
