### ISSUE TITLE
Roku Json not showing correct video links

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6863]
This is just a snippet

My video urls should all start with https://v.joshwho-cdn.com and they r not

`{"providerName":"SeekingTheTruth JoshWho","language":"en","lastUpdated":"2022-07-12T13:46:30-05:00","movies":[{"id":"video_62845","title":"CERN will open a Portal on 5th of July 666 - Get ready to start seeing weird things","longDescription":"=> \nDitch the Duck use 2me Search. They won't track you or censor. https:\/\/2me.global \nReal Free Speech Video &amp; Live Streaming https:\/\/www.joshwhotv.com\n\n\u00a0\n\nLinux Server Security Tips https:\/\/server-security.joshwho.net\/","shortDescription":"=> \nDitch the Duck use 2me Search. They won't track you or censor. https:\/\/2me.global \nReal Free Speech Video &amp; Live Streaming https:\/\/www.joshwhotv.com\n\n\u00a0\n\nLinux Server Security Tips https:\/\/ser","thumbnail":"https:\/\/joshwho-cdn.com\/videos\/video_220704004024_v4496\/video_220704004024_v4496_roku.jpg?cache=1657382184_1657382184","tags":["News"],"genres":["special"],"releaseDate":"2022-07-04T00:40:24-05:00","categories_id":2,"content":{"dateAdded":"2022-07-04T00:40:24-05:00","captions":[],"duration":287,"language":"en","adBreaks":["00:00:00"],"videos":[{"url":"https:\/\/joshwho-cdn.com\/videos\/video_220704004024_v4496\/video_220704004024_v4496_HD.mp4","quality":"FHD","videoType":"MP4"}]}},{"id":"video_62289","title":"Trump Rally Mendon Illinois  - SeekingTheTruth JoshWho on 25-Jun-22-17:00:17","longDescription":"=> \nSend a tip to https:\/\/www.joshwho.net\/donate \n\nMy Amazon Wishlist: https:\/\/www.amazon.com\/hz\/wishlist\/ls\/2PEXF6MD5ZE1U\/ref=nav_wishlist_lists_1?_encoding=UTF8&amp; ;amp;type=wishlist\n\nCovid Lies 2021 https:\/\/www.joshwhotv.com\/program\/125270\/0\/seekingthetruth\/seekingthetruth-joshwho-documentaries\/covid-lies-2021---joshwho-documentary \n\nAdd us on Roku, Channel: SeekingTheTruth\n\nStreamed for free on JoshWho TV\n\nBrought to you by JoshWho Hosting https:\/\/www.joshwho-hosting.com","shortDescription":"=> \nSend a tip to https:\/\/www.joshwho.net\/donate \n\nMy Amazon Wishlist: https:\/\/www.amazon.com\/hz\/wishlist\/ls\/2PEXF6MD5ZE1U\/ref=nav_wishlist_lists_1?_encoding=UTF8&amp; ;amp;type=wishlist\n\nCovid Lies 2","thumbnail":"https:\/\/joshwho-cdn.com\/videos\/v_220625200657_v857e\/v_220625200657_v857e_roku.jpg?cache=1657575071_1657575071","tags":["Podcast"],"genres":["special"],"releaseDate":"2022-06-25T20:07:22-05:00","categories_id":32,"content":{"dateAdded":"2022-06-25T20:07:22-05:00","captions":[],"duration":11197,"language":"en","adBreaks":["00:00:00"],"videos":[{"url":"https:\/\/joshwho-cdn.com\/videos\/v_220625200657_v857e\/v_220625200657_v857e_HD.mp4","quality":"FHD","videoType":"MP4"}]}},{"id":"video_62171","title":"JoshWho Live - What Is Going on today in our world? on 23-Jun-22-20:41:56","longDescription":"=> Send a tip to https:\/\/www.joshwho.net\/donate\n\nMy Amazon Wishlist: https:\/\/www.amazon.com\/hz\/wishlist\/ls\/2PEXF6MD5ZE1U\/ref=nav_wishlist_lists_1?_encoding=UTF8&amp;type=wishlist\n\nCovid Lies 2021 https:\/\/www.joshwhotv.com\/program\/125270\/0\/seekingthetruth\/seekingthetruth-joshwho-documentaries\/covid-lies-2021---joshwho-documentary\n\nAdd us on Roku, Channel: SeekingTheTruth\n\nStreamed for free on JoshWho TV\n\nBrought to you by JoshWho Hosting https:\/\/www.joshwho-hosting.com","shortDescription":"=> Send a tip to https:\/\/www.joshwho.net\/donate\n\nMy Amazon Wishlist: https:\/\/www.amazon.com\/hz\/wishlist\/ls\/2PEXF6MD5ZE1U\/ref=nav_wishlist_lists_1?_encoding=UTF8&amp;type=wishlist\n\nCovid Lies 2021 http","thumbnail":"https:\/\/joshwho-cdn.com\/videos\/v_220623214925_v1996\/v_220623214925_v1996_roku.jpg?cache=1657575072_1657575072","tags":["Podcast"],"genres":["special"],"releaseDate":"2022-06-23T21:49:28-05:00","categories_id":32,"content":{"dateAdded":"2022-06-23T21:49:28-05:00","captions":[],"duration":4023,"language":"en","adBreaks":["00:00:00"],"videos":[{"url":"https:\/\/joshwho-cdn.com\/videos\/v_220623214925_v1996\/v_220623214925_v1996_HD.mp4","quality":"FHD","videoType":"MP4"}]}},{"id":"video_60694","title":"Alien invasion 2024 Fake Insurrection Wake UP Time is ticking","longDescription":"=> Send a tip: https:\/\/www.joshwho.net\/donate\nProject Blue Beam https:\/\/www.joshwhotv.com\/program\/125270\/12\nTTOR New Website https:\/\/corder.tv\n","shortDescription":"=> Send a tip: https:\/\/www.joshwho.net\/donate\nProject Blue Beam https:\/\/www.joshwhotv.com\/program\/125270\/12\nTTOR New Website https:\/\/corder.tv\n","thumbnail":"https:\/\/joshwho-cdn.com\/videos\/video_220612175355_vb012\/video_220612175355_vb012_roku.jpg?cache=1655109000_1655109000","tags":["News"],"genres":["special"],"releaseDate":"2022-06-12T17:53:55-05:00","categories_id":2,"content":{"dateAdded":"2022-06-12T17:53:55-05:00","captions":[],"duration":1784,"language":"en","adBreaks":["00:00:00"],"videos":[{"url":"https:\/\/joshwho-cdn.com\/videos\/video_220612175355_vb012\/video_220612175355_vb012_HD.mp4","quality":"FHD","videoType":"MP4"}]}},{"id":"video_60272","title":"School Shootings are Not Organic - CIA MKULTRA LSD Programming","longDescription":"=> \nThere has been a Mind control experiment going on for over a decade and now people are connecting the dots. Every known public incident has one of these CIA puppets behind it, and get covered up very quickly. IIA controls most these people today online. They are CIA social media influencers. Look into this all.","shortDescription":"=> \nThere has been a Mind control experiment going on for over a decade and now people are connecting the dots. Every known public incident has one of these CIA puppets behind it, and get covered up v","thumbnail":"https:\/\/joshwho-cdn.com\/videos\/video_220604051306_vdb9c\/video_220604051306_vdb9c_roku.jpg?cache=1657354463_1657354463","tags":["News"],"genres":["special"],"releaseDate":"2022-06-04T05:13:06-05:00","categories_id":2,"content":{"dateAdded":"2022-06-04T05:13:06-05:00","captions":[],"duration":431,"language":"en","adBreaks":["00:00:00"],"videos":[{"url":"https:\/\/joshwho-cdn.com\/videos\/video_220604051306_vdb9c\/video_220604051306_vdb9c_HD.mp4","quality":"FHD","videoType":"MP4"}]}},{"id":"video_60223","title":"Exposing Kent Hovind protecting Chris Jones pedo actions - JoshWho Live feat. TTOR Brett Keane","longDescription":"=> \nSend a tip to https:\/\/www.joshwho.net\/donate\n\nMy Amazon Wishlist: https:\/\/www.amazon.com\/hz\/wishlist\/ls\/2PEXF6MD5ZE1U\/ref=nav_wishlist_lists_1?_encoding=UTF8&amp;type=wishlist\n\nCovid Lies 2021 `

Here is the roku json https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100

**Comment by JoshWho** [comment]
It is showing the video links to be "https:\/\/joshwho-cdn.com\/videos\/v_220519201016_vf712\/v_220519201016_vf712_HD.mp4"

which is incorrect.

Here is a example video url

https://v.joshwho-cdn.com/file/joshwhotv/_YPTuniqid_5c772f56648ea4.84104964_Low.mp4?download=1&title=The+Adventures+of+Mark+Twain+-+The+Mysterious+Stranger+SATAN..._mp4_Low_.mp4

**Comment by PissedOffParent** [comment]
Hi everyone, I was the one that originally kicked this one off. It sounds like the json needs to be modified in some way to include the "v." subdomain. If it helps, this started happening about 3 weeks ago, prior to that all of my videos were working just find on the roku channel. Then, about June 17th'ish, it stopped, guessing that whatever changed at that point to remove the subdomain is what caused it. 

I am assuming that this is something at the joshwhotv admin level and not something that I could fix, assuming that it is impacting the other roku users as well.

**Comment by JoshWho** [comment]
> Hi everyone, I was the one that originally kicked this one off. It sounds like the json needs to be modified in some way to include the "v." subdomain. If it helps, this started happening about 3 weeks ago, prior to that all of my videos were working just find on the roku channel. Then, about June 17th'ish, it stopped, guessing that whatever changed at that point to remove the subdomain is what caused it.
> 
> I am assuming that this is something at the joshwhotv admin level and not something that I could fix, assuming that it is impacting the other roku users as well.

Correct. It is something wrong with the way it is grabbing the video file url. Waiting on @DanielnetoDotCom to check this out

**Comment by PissedOffParent** [comment]
just to add, I pulled down JoshwhoTV network on youtube and you are having the same issue I am with the videos not playing. Started happening around 6/17 to help with the troublshooting....guessing it impacts anyone who does the roku thing.

**Comment by DanielnetoDotCom** [comment]
where did you set up this URL?

https://v.joshwho-cdn.com/

usually, it should use the URL defined on configuration.php or on the CDN

**Comment by JoshWho** [comment]
that is my cdn for backblaze

**Comment by DanielnetoDotCom** [comment]
in what plugin did you set it up?

please screenshot

**Comment by JoshWho** [comment]
backblaze plugin

**Comment by JoshWho** [comment]
@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Hi

I am confused...

your feed uses this URL: https://joshwho-cdn.com/ (URL1) which seems to be OK for images and static files but not OK for videos, is that correct?

and your Backblaze suppose to use this https://v.joshwho-cdn.com/ (URL2)

- You said you set up URL2 on the Backblaze plugin
- where did you set up URL1?

**Comment by JoshWho** [comment]
The videos are hosted by backblaze

**Comment by JoshWho** [comment]
![9cfb98cc-f16b-4faa-8b3c-bfd0a645ac84](https://user-images.githubusercontent.com/39392449/179001119-49d1fd2b-0851-40e9-a3e2-e8030f75f11f.png)

**Comment by JoshWho** [comment]
This same problem exists even when you remove the cdn from the equation . So pretend the domain is still www.joshwhotv.com/videos/

the Roku Json url for the file is wrong and is missing the subdomain for the address which is https://v.joshwho-cdn.com/

**Comment by JoshWho** [comment]
> Hi
> 
> I am confused...
> 
> your feed uses this URL: https://joshwho-cdn.com/ (URL1) which seems to be OK for images and static files but not OK for videos, is that correct?
> 
> and your Backblaze suppose to use this https://v.joshwho-cdn.com/ (URL2)
> 
> * You said you set up URL2 on the Backblaze plugin Yes
> * where did you set up URL1? Customize Advance

**Comment by JoshWho** [comment]
https://joshwho-cdn.com/ = https://www.joshwhotv.com

**Comment by JoshWho** [comment]
Backblaze
https://v.joshwho-cdn.com/file/joshwhotv/ = https://www.joshwhotv.com/videos/

**Comment by JoshWho** [comment]
![2019-tny-poetry](https://user-images.githubusercontent.com/39392449/179023751-1a7a6f1d-9b5e-4e0c-97b8-13cc7fbc6127.gif)

**Comment by JoshWho** [comment]
just playing around with this while waiting. Never knew there was so many options on github.

**Comment by DanielnetoDotCom** [comment]
Sorry for the delay, please try this update

**Comment by JoshWho** [comment]
I do not see a change after I ran the update is there anything I can edit?

**Comment by DanielnetoDotCom** [comment]
you must clear the cache

**Comment by JoshWho** [comment]
with the cache purged still shows `https:\/\/joshwho-cdn.com\/videos\/video_220423004135_v55ab\/video_220423004135_v55ab_HD.mp4`

**Comment by DanielnetoDotCom** [comment]
I just run a git pull on your server and it updated

![image](https://user-images.githubusercontent.com/18009293/179059732-1fe52e50-5b73-4b0f-b6ff-25f4e6cd2ce6.png)

Checking now

**Comment by JoshWho** [comment]
incogeto still shows `https:\/\/joshwho-cdn.com\/videos\/video_220704004024_v4496\/video_220704004024_v4496_HD.mp4`

**Comment by DanielnetoDotCom** [comment]
I am still checking and testing directly in your server

**Comment by JoshWho** [comment]
```
https:\/\/joshwho-cdn.com\/videos\/video_220604051306_vdb9c\/video_220604051306_vdb9c_HD.mp4

to

https:\/\/v.joshwho-cdn.com\/videos\/video_220604051306_vdb9c\/video_220604051306_vdb9c_HD.mp4
```

**Comment by DanielnetoDotCom** [comment]
I did now. please try again

**Comment by JoshWho** [comment]
Perfect. Thank you so much @DanielnetoDotCom  Looks good again.

**Comment by PissedOffParent** [comment]
Problem is still occuring for both my and the joshwhoTV channel. A few of my videos loaded, but then would not play. This is for both joshowhoTV and my channel, pissedoffparent

**Comment by JoshWho** [comment]
That may be on Roku's end they need to refresh the cache and should soon. They do some kind of checkups daily I think

**Comment by PissedOffParent** [comment]
they have a build at "noon", but it usually takes a few hours for my new videos to get on the site, so assuming that in the next few hours we should be good. Checked the JSON and its showing the corrected format.

**Comment by JoshWho** [comment]
> they have a build at "noon", but it usually takes a few hours for my new videos to get on the site, so assuming that in the next few hours we should be good. Checked the JSON and its showing the corrected format.

Good deal. Yup I have good feelings it should all work once they refresh.
