### ISSUE TITLE
Question: Can I put my 2nd server on the same CDN account/billing, or must they be separate?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6864]
That's pretty much it.

**Comment by DanielnetoDotCom** [comment]
Yes

just add it as a new pullzone

I can add it for you if you need help

**Comment by walt93** [comment]
It worked, but FYI adding the pull zone took >3 minutes before the page rendered again, something a little slow about that process... maybe add a "please wait" textbox?

**Comment by DanielnetoDotCom** [comment]
I see.

but could you complete the request?

**Comment by walt93** [comment]
Yes it worked. It was just so slow that I thought it was broken.

**Comment by DanielnetoDotCom** [comment]
Thanks for the feedback. I will review it
