### ISSUE TITLE
[Live->Live Servers] Configuration question. Where do I get the "Get Remote File URL" and "WebRTC Player"?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6866]
Everything else I can find in the Live plug-in.

**Screenshots**
![Screen Shot 2022-07-12 at 10 54 25 PM](https://user-images.githubusercontent.com/11711050/178661134-e840a6ed-4285-464a-bd74-53e35cc039be.jpg)

**Comment by GreenDragonTavern** [comment]
Daniel, is there any way to get the WebRTC? Any mods here that work are yours :-)

**Comment by DanielnetoDotCom** [comment]
> Daniel, is there any way to get the WebRTC? Any mods here that work are yours :-)

webrtc still under development

**Comment by DanielnetoDotCom** [comment]
trying to, I will be back on it in the future

**Comment by GreenDragonTavern** [comment]
Keep that plate full Daniel! Many thanks again for all.
