### ISSUE TITLE
v12 errors 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#6867]
I have many of these same errors 
![Screenshot_20220713-045713_Samsung Internet](https://user-images.githubusercontent.com/70327833/178718527-09349201-739d-4907-91ef-9f413a2a4477.jpg)

**Comment by DanielnetoDotCom** [comment]
For now there is nothing to worry about this, unless you detect some feature that is not working.

**Comment by milehighkaraoke** [comment]
How about this one 
![20220714_005831](https://user-images.githubusercontent.com/70327833/178921152-cdd010bb-d677-4c38-b3bb-a77e5bf1f388.jpg)
