### ISSUE TITLE
AVideo - Encode video and audio link does not login to Encoder

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#6868]
Fresh install of AVideo and Encoder
Logged in as admin
Click the Encode video and audio link and see attachments.

![AVideo2Encoder](https://user-images.githubusercontent.com/85363361/178792768-27d0b6fe-1136-4dfd-9e77-66966020642c.jpg)

[avideo.log.pdf](https://github.com/WWBN/AVideo/files/9104498/avideo.log.pdf)

[Encoder-avideo.log.pdf](https://github.com/WWBN/AVideo/files/9104502/Encoder-avideo.log.pdf)

**Comment by GreenDragonTavern** [comment]
Unchecking enableOldPassHashCheck (it was checked by default) solved issue.

**Comment by DanielnetoDotCom** [comment]
once is all updated and you logoff and login (streamer and encoder), everything should back to normal

**Comment by GreenDragonTavern** [comment]
Hello Daniel. Disabling enableOldPassHashCheck worked immediately. Guessing the option is for backwards compatibility, yes? If so, will leave it disabled.

**Comment by GreenDragonTavern** [comment]
Roger that, and appreciate all.
