### ISSUE TITLE
Google login emails exposed after version 12 update

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#6872]
@DanielnetoDotCom  Google login emails are now exposed after the new update of version 12. Even if you put up a name, it automatically disappears and show your email and there is no way to hide the user email. Please help fix this because before users were able to type their names so that their emails wouldn't show. Spammers can easily steal user emails to spam them please help it's urgent.
![Screenshot_20220714_132607](https://user-images.githubusercontent.com/72950503/178973279-8318a383-b3ed-4cd4-ab2d-f5236ee3de9c.jpg)

**Comment by DanielnetoDotCom** [comment]
Check this please 

https://github.com/WWBN/AVideo/wiki/User-Identification

**Comment by mrgodgiven** [comment]
It was only hidden in the previous update, but now I tried my best to hide it but using the settings and the instructions you have me and it doesn't work.

**Comment by DanielnetoDotCom** [comment]
It MUST hide if you select properly

the Google login uses the email also as a username.

try to show the channel name instead
