### ISSUE TITLE
Autoplay starts a new video with a blank screen after new update

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#6873]
Mr @DanielnetoDotCom  please help fix autoplay because it starts a new video with a blank screen this was not happening before.
![Screenshot_20220714_140337](https://user-images.githubusercontent.com/72950503/178978742-cd8ee4b0-450e-476f-b95b-00be109631fc.jpg)

**Comment by DanielnetoDotCom** [comment]
please share the video link here please

**Comment by mrgodgiven** [comment]
https://livefaces.live/video/.hWg/he-dances-better-than-all-men
@DanielnetoDotCom  please note that the video plays well, but the problem begins when the next video auto plays

**Comment by mrgodgiven** [comment]
When the next video auto plays it starts on a blank black screen.

**Comment by DanielnetoDotCom** [comment]
the link is protected by a password. (login required)

try to detail more the problem, get avideo logs and also js logs
