### ISSUE TITLE
Socket server keeps randomly crashing

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6874]
Ever few hours I come back and have to start it up again.

**Comment by JoshWho** [comment]
I will run that next time it crashes

**Comment by JoshWho** [comment]
Also noticed `wss://live.joshwhotv.com:2053/?webSocketToken=MmU0SWZrRDF1bWh4b25VanQzWE1jUkU2N3Rrb2dBbXAycm1UNmVUOHRpeHRKbzJKUkhJeUJCbzdaQkFWend2RjJpbFNTM3lqTENPM0dLVkhtSFcyeWk3UG1WcHB6b3NZUWJudVlReW03cXlaUXVkcHMwbEVLbWpPc2xTdkJhSktmVlkzci9xdjB6VWp0eG9ZTXhTc1dCK3EvR0dVVnNoQnlEZjlVVTdYNzBJcXFXaHFtN1FERVdCa1B4Q1MvOXVmTmhKNkNvcXB0YkFvN0FwcUNnZGpBU0x6K2hlSFc0cFBjUVQzVHVGSjI3L1BFSnkyMWpST2pyVmE3REJtdkNkS1hmd2NmUTZuOU9leXBqSzBya01nNFVIcmQ4RnZtU01PV0dkYjcxZVVQSFJMM1JEMjMwWVBrWExvWmYwR0JkWU4ydHFkOUhJdmJQMmVrUWNFTEc0bzQ2VGJrVW5vdjJQTUNZTjJJOTJlQ3VNcHhXQThlWlVra0s5MDJ0cGFTZllscCs0UklSRFpIWGRCbEI2T0ZGWUtJMnBpbWZzNHQ2UEUrekFrbmZac2xObzZtVEdDVFh2R1RsOG5mc3ZGSUJ4QWxGelFhQTJzTFdqb1prQU1aRE1zekJ4a01wM0I0Qkx0ejdsYmg3ZjRsd052NmpKN3hIS0lnbVpmQkdybjBnYWUwNVdMWmIyTWJJc2xNbGZCQWc3SGMrTGhYN2QxazJWMFltUEVBVjJvNFFlaHpwZ05aL0N4Z3ZuKzJaZXpDVzY3NVFsbDFyeDhXY0VvVTJyZzhHUFNGa0VabXBHYkpXMUpJcFhGYWkyMHNuTWlValpSQzZTY0dwY2pucmFFc2I5MzlzVmVlTWdvbkpOeU5zd2t3aTY0WlRGUXMyWVFQWVFvTUlCektMREVsZXZnK3Q3NTJVUTJYVjUvdVlRbGczMUZQOHphc1BadUhpYi9xeTMwcXJ2OU1mdER2emN6S3B1ZndvdDdqZXVocHR6SUU3MzVCTVhRUDd0Y2RRWWcydzYr&isCommandLine=0&page_title=JoshWho%20TV`

Is what seems to keep freezing my browser randomly. is there any way to make the sockets work in pulses instead of a solid connection?

**Comment by JoshWho** [comment]
for right now I am gonna limit the sockets for only the live streaming pages.

**Comment by milehighkaraoke** [comment]
I changed my socket port to  12053  and that fixed my socket connection issues

**Comment by JoshWho** [comment]
> I changed my socket port to 12053 and that fixed my socket connection issues

I do not think that is my issue. Just seems to be a constant script loading and sometimes freezes the page.

**Comment by DanielnetoDotCom** [comment]
> I get this in the log
> 
> `Could not open input file: /var/www/html/AVideo/plugin/YPTSocket/server.php`

I guess you have to replace AVideo with YouPHPTube, so the command should be 

`sudo nohup php /var/www/html/YouPHPTube/plugin/YPTSocket/server.php > /var/logs/YPTSocket.log &`

**Comment by DanielnetoDotCom** [comment]
> 

Yes, I was suspecting it may be an overload. from the logs, I wish I could see where exactly the overload comes from.

**Comment by JoshWho** [comment]
K I will give it a try

**Comment by JoshWho** [comment]
k I have it running now with the log
```

[2022-07-15 09:38:25] AVideoLog::DEBUG: _mysql_connect HOST=localhost,DB=youPHPTube SCRIPT_NAME: /var/www/html/YouPHPTube/plugin/YPTSocket/server.php

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/YouPHPTube/objects/functions.php:3993) in /var/www/html/YouPHPTube/plugin/YPTSocket/server.php on line 26
[2022-07-15 09:38:26] AVideoLog::DEBUG: Starting Socket server at port 2053 SCRIPT_NAME: /var/www/html/YouPHPTube/plugin/YPTSocket/server.php
Starting AVideo Socket server version 3.3 on port 2053
Your socket server uses a secure connection
Parameter [local_cert]: /etc/letsencrypt/live/live.joshwhotv.com-0001/fullchain.pem 
Parameter [local_pk]: /etc/letsencrypt/live/live.joshwhotv.com-0001/privkey.pem 
Parameter [allow_self_signed]: 1 
Parameter [verify_peer]:  
Parameter [verify_peer_name]:  
Parameter [security_level]: 0 

Fatal error: Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:2053": Address already in use (EADDRINUSE) in /var/www/html/YouPHPTube/vendor/react/socket/src/TcpServer.php:184
Stack trace:
#0 /var/www/html/YouPHPTube/vendor/react/socket/src/Server.php(77): React\Socket\TcpServer->__construct()
#1 /var/www/html/YouPHPTube/plugin/YPTSocket/server.php(73): React\Socket\Server->__construct()
#2 {main}
  thrown in /var/www/html/YouPHPTube/vendor/react/socket/src/TcpServer.php on line 184

```

**Comment by JoshWho** [comment]
> I changed my socket port to 12053 and that fixed my socket connection issues

Well I guess it was the port I just changed it and restarted it and no more errors.

**Comment by DanielnetoDotCom** [comment]
> k I have it running now with the log
> 
> ```
> 
> [2022-07-15 09:38:25] AVideoLog::DEBUG: _mysql_connect HOST=localhost,DB=youPHPTube SCRIPT_NAME: /var/www/html/YouPHPTube/plugin/YPTSocket/server.php
> 
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/YouPHPTube/objects/functions.php:3993) in /var/www/html/YouPHPTube/plugin/YPTSocket/server.php on line 26
> [2022-07-15 09:38:26] AVideoLog::DEBUG: Starting Socket server at port 2053 SCRIPT_NAME: /var/www/html/YouPHPTube/plugin/YPTSocket/server.php
> Starting AVideo Socket server version 3.3 on port 2053
> Your socket server uses a secure connection
> Parameter [local_cert]: /etc/letsencrypt/live/live.joshwhotv.com-0001/fullchain.pem 
> Parameter [local_pk]: /etc/letsencrypt/live/live.joshwhotv.com-0001/privkey.pem 
> Parameter [allow_self_signed]: 1 
> Parameter [verify_peer]:  
> Parameter [verify_peer_name]:  
> Parameter [security_level]: 0 
> 
> Fatal error: Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:2053": Address already in use (EADDRINUSE) in /var/www/html/YouPHPTube/vendor/react/socket/src/TcpServer.php:184
> Stack trace:
> #0 /var/www/html/YouPHPTube/vendor/react/socket/src/Server.php(77): React\Socket\TcpServer->__construct()
> #1 /var/www/html/YouPHPTube/plugin/YPTSocket/server.php(73): React\Socket\Server->__construct()
> #2 {main}
>   thrown in /var/www/html/YouPHPTube/vendor/react/socket/src/TcpServer.php on line 184
> ```


the port is in use you should stop it first

`sudo php /var/www/html/YouPHPTube/plugin/YPTSocket/stopServer.php`

**Comment by DanielnetoDotCom** [comment]
I do not know what is `ERROR: (1025) Unable to write to stream: fwrite(): SSL: Broken pipe`

but I guess that is not the issue yet. maybe a client that does not exists anymore when it tries to send the message
