### ISSUE TITLE
How to get ride of links in left menu

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#6875]
where and what do I have to click to get rid of EPG and TV Link in left menu
![menu](https://user-images.githubusercontent.com/37937968/179118383-1f8eee65-1c00-49ee-953c-caba13307410.png)

**Comment by walt93** [comment]
Hi. I believe this is in the plugin Programs and it's showTVFeatures which disables both

![Screen Shot 2022-07-14 at 9 59 35 PM](https://user-images.githubusercontent.com/11711050/179153925-f3e3738a-8c2e-4738-9811-d755e3af66ca.png)

![Screen Shot 2022-07-14 at 9 59 24 PM](https://user-images.githubusercontent.com/11711050/179153893-42cf1fde-f717-4349-976d-918ff6d4cdd9.png)

**Comment by Lordblanca** [comment]
[walt93](https://github.com/walt93) thank you but that did not help. Thanks for trying

**Comment by DanielnetoDotCom** [comment]
@walt93 is correct, you should uncheck it

**Comment by walt93** [comment]
Always remember to do the clear first page cache / clear cache directory / generate site map dance or you simply won’t see these changes. 💡
