### ISSUE TITLE
Buffering since update

### ISSUE THREAD

**Issue by Lordblanca** [WWBN/AVideo#6876]
A lot of buffering during streaming since update to version 12 and fixes or suggestions?

P.S. I had NO Buffering issues before the update

**Comment by milehighkaraoke** [comment]
Fresh Install fixed it all up for me
I was streaming tonight without any issues

**Comment by Lordblanca** [comment]
There has to be another way to fix these problems. Most of the time there are issues it I do exactly that. Getting tired of having to do that. Daniel has to have a fix for his programs

**Comment by milehighkaraoke** [comment]
A roll back option would be nice.....

**Comment by DanielnetoDotCom** [comment]
I really do not believe the buffering has anything to do with the update unless you have some errors.

buffering in most of the cases is directly related to the bandwidth, and this only resolves with a CDN (if need)
