### ISSUE TITLE
Installing AVideo, can't get off the mod_rewrite error page

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6878]
**Describe the question**
I've set AllowOverride to All, rewrite is enabled, apache has been restarted. This error screen persists.

**Screenshots**
![Screen Shot 2022-07-14 at 9 44 11 PM](https://user-images.githubusercontent.com/11711050/179152315-efcc6a0a-e480-43f5-8f80-f53018468f40.png)

**Comment by milehighkaraoke** [comment]
Did you enter the commands at the bottom  to enable Mod?

**Comment by walt93** [comment]
Yes I did, I've done all of this, something else seems to be the issue.

**Comment by walt93** [comment]
Mishandling of files, user error.
