### ISSUE TITLE
Error ?

### ISSUE THREAD

**Issue by Tinoisthe** [WWBN/AVideo#6880]
**Describe the question**
A clear and concise description of what is your question.
had to move files to new vps now showing SELECT * FROM users_groups as ug WHERE 1=1 \nError : () when i try to load website

Did i do something wrong ??
**Screenshots**
Provide some screenshots to help us understand and explain your problem.
![Capture1234566](https://user-images.githubusercontent.com/76804686/179204420-94c19a49-4daf-4a17-bb6b-4a1b31f14bd4.PNG)

**Comment by DanielnetoDotCom** [comment]
check avideo logs

**Comment by Tinoisthe** [comment]
![Capture1234566](https://user-images.githubusercontent.com/76804686/179325729-577df817-69db-4d2f-97d5-0114af762d3b.PNG)
just shows this

**Comment by DanielnetoDotCom** [comment]
does not help much, but seems to me a bad installation somwhere

**Comment by Tinoisthe** [comment]
should i just reinstall it again if so how do i move the DB with the user on it from old to new one

**Comment by DanielnetoDotCom** [comment]
seems to be a bad OS/dependencies installation, but I am not sure, I do not know what you are missing

**Comment by Tinoisthe** [comment]
They logs aren’t saying much as well should I just redone load then
