### ISSUE TITLE
Socket server wont start

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6882]
No clue what changed just doesn't start and now when I try with the log command it dosnt show anything

```
root@joshwhotv:~# sudo php /var/www/html/YouPHPTube/plugin/YPTSocket/stopServer.php
You have new mail in /var/mail/root
root@joshwhotv:~#

```

**Comment by JoshWho** [comment]
```
root@joshwhotv:~# nohup: ignoring input and redirecting stderr to stdout

[1]+  Exit 255                sudo nohup php /var/www/html/YouPHPTube/plugin/YPTSocket/server.php > /var/logs/YPTSocket.log
root@joshwhotv:~#

```

**Comment by JoshWho** [comment]
YPTSocket.log is empty

**Comment by JoshWho** [comment]
Here is without the nohup

```
root@joshwhotv:~# sudo php /var/www/html/YouPHPTube/plugin/YPTSocket/server.php &
[1] 10677
You have new mail in /var/mail/root
root@joshwhotv:~#

```

**Comment by DanielnetoDotCom** [comment]
You have missed the `nohup` command the correct command is...

`sudo nohup  php /var/www/html/YouPHPTube/plugin/YPTSocket/server.php &`

if is not starting use only the command `php /var/www/html/YouPHPTube/plugin/YPTSocket/server.php` so you will be able to see the output

**Comment by JoshWho** [comment]
This is what it does with that command

```
root@joshwhotv:~# php /var/www/html/YouPHPTube/plugin/YPTSocket/server.php
You have new mail in /var/mail/root
root@joshwhotv:~#
```

**Comment by DanielnetoDotCom** [comment]
heck apache or avideo log

must be something, this does not make sense.

try to stop it before starting

`php /var/www/html/YouPHPTube/plugin/YPTSocket/stopServer.php`

**Comment by JoshWho** [comment]
`[15-Jul-2022 18:30:43 America/Chicago] AVideoLog::ERROR: Could not connect: Connection to tls://live.joshwhotv.com:12053 failed: Last error for IPv4: Connection to tcp://144.217.180.157:12053 failed: Connection refused (ECONNREFUSED). Previous error for IPv6: Connection to tcp://[2607:5300:203:a9d::]:12053 failed: Connection refused (ECONNREFUSED) wss://live.joshwhotv.com:12053?webSocketToken=MmU0SWZrRDF1bWh4b25VanQzWE1jWTNKMDIyNHkrdlFFQ0xWOEV4VDFHS0Q1cVBWUlg2VWIvdmlXODBDekwxc2FJa2ZsdllGQllVRTdEVHA3bzc5Z0I2anp6ZU1VR2pvenJJbEJTNEpWUERSU2U3amxsa0hEWnBFcTZHU0N4QkhjWWluVDBGU2c2U2VzeXhpQnh1dmRZM3p3YzBLem5VU0h2TTZpa3BkMVhFMDMwK3pHdWw0Z0VaQVl5TFVQcFN4d3BUdndnOTZuS2dVWU1EQVE5QUJPUDlsdWlSNXVIb0YzOGxBUGNabEgvVHAxSnpzWkNGVDYwdkZUSmZXNkdJOEFSSDlUWDV6NkJDVjJWTmxpamFoMWo5YVYwemU4SDBaRHJqNFJJVG1QanQ2NDZRd3hTNEcyUEgwNXNNeCtxRVkyTmNrdnlRdXA5UlNTUTJFTUxGTnlaM2svVGFvbDJSSWZEelk4VjJZZVdNc0RkUVRQazhwU2tLRGE5R2ZxNjBkaW9JTjh4UDhhb0daWXpoNGtKNC9XeDJGYVk3SUExVlZvSWl1bjFUb1JhaG9TYnUzNnFZelZtU2FIUkVrSUd4YllnTGNNcm9Zb0hjRkwwamxhL1R3TkdwN1dpZ25CTGdVUi9YWkw1U05McTNMa2hGTWJSM2N0S1o2YzB5RlVZNWNDWW85bUFKZTJtZk1uRW8zZHVpK1pBNlJOZmp3dnoxNTRVRmlLN1JhcDRyNk04b1oxNi9QOGdCQzRvV01TbzJndm5jZGhOOEJXRWQ1YmYxWVdCU3R4angyYUZLVTRhckxoS0lEK1V5VTZsQlY5K3I0VzdOa3RYdUVQREdMb1pPQkRwOEZXU3V3S0RvZUR1OGIwZkx1clBkeng4MndXR0xkMFFlb2pBRmxCMHZWa2wvK2xXOUUzQWRXUE5GQlZSOEw=&isCommandLine=1 SCRIPT_NAME: /YouPHPTube/plugin/Live/on_publish_done.php`

**Comment by JoshWho** [comment]
I tried stopping it starting I rebooted 3 times also

**Comment by DanielnetoDotCom** [comment]
Checking it directly into your server

**Comment by DanielnetoDotCom** [comment]
You are using a different version of PHP on the command line and you do not have all the modules installed (PHP 8.1.8)
```

Fatal error: Uncaught Error: Class "mysqli" not found in /var/www/html/YouPHPTube/objects/functions.php:4195
Stack trace:
#0 /var/www/html/YouPHPTube/objects/include_config.php(63): _mysql_connect()
#1 /mnt/md0/videos/configuration.php(55): require_once('...')
#2 /var/www/html/YouPHPTube/plugin/YPTSocket/server.php(10): require_once('...')
#3 {main}
  thrown in /var/www/html/YouPHPTube/objects/functions.php on line 4195
root@joshwhotv:/var/www/html/YouPHPTube/plugin/YPTSocket# 
```

Just resolved installing ....

`sudo apt-get install php8.1-mysqlnd`

**Comment by JoshWho** [comment]
Im using php 8? Didn't even know that. 

I see it connected now. Excellent thank you so much.

 I wonder if that is what was crashing it. 

Thank you so much @DanielnetoDotCom
