### ISSUE TITLE
Making the selection of encoder more clear

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6884]
On the network encoders page where a listing of encoders are, there used to be a highlight color indicating which encoder is currently selected. Now the encoders look all the same and a user might not understand they need to click on them to switch between encoders,

This is how it appears on the page:
![Screen Shot 5782-11-17 at 9 41 45](https://user-images.githubusercontent.com/58882903/179343670-f6f0a087-49dd-45ed-9146-f9045c5dc488.jpg)
![Screen Shot 5782-11-17 at 9 41 39](https://user-images.githubusercontent.com/58882903/179343677-b42803f7-2692-4f9c-bc5f-a6f1bd6236de.jpg)

I think maybe giving it a bit css like on mouseover effect and click effect to emphasis the UI just a little more.

**Comment by DanielnetoDotCom** [comment]
I guess some CSS is missing.

maybe the http/https problem persists

Check how the public network looks like https://network.avideo.com/

![image](https://user-images.githubusercontent.com/18009293/179360967-4406ac92-b274-40b2-9a95-5a0fd6ddef3a.png)

**Comment by guymass** [comment]
Would this might effect the problem? because the encoders now work since the mysql database fix. 
How do I solve this CORS problem? both my domains reside on the same server.
![Screen Shot 5782-11-18 at 21 01 31](https://user-images.githubusercontent.com/58882903/179418885-77e282a0-0a76-48ea-85e8-f994c24bebcc.jpg)

**Comment by DanielnetoDotCom** [comment]
On the PHP side, I do all I can to allow cors, so there is no restriction on the code.

this may be something on your Apache side or DNS side
