### ISSUE TITLE
Socket Server just keeps freezing the webpage

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6885]
I think it is the socket server. The page just keeps getting harder to navigate always getting the waring saying page is unresponsive do you want to wait or exit.

**Comment by JoshWho** [comment]
apon inspection I see this in the console

```
Uncaught ReferenceError: webSiteRootURL is not defined
    at HTMLDocument.<anonymous> (script.js?cache=1654434748_1654434748:288:24)
    at e (jquery.min.js?cache=1653393647_1653434754:2:30038)
    at t (jquery.min.js?cache=1653393647_1653434754:2:30340)
```

**Comment by JoshWho** [comment]
the link to that file is

https://joshwho-cdn.com/plugin/YPTSocket/script.js?cache=1654434748_1654434748

**Comment by JoshWho** [comment]
I turned off the socket server plugin and now it is not doing the freeze thing anymore.

**Comment by JoshWho** [comment]
I can confirm I can now leave the tab to another tab with a video playing come back to it 3 minutes later and it is not frozen.

I can't do that when the socket plugin is running. When the Socket server plugin is enabled I try the same test and it freezes and I have to wait for it to unfreeze or click exit page

**Comment by JoshWho** [comment]
Is there a way to fully limit the socket plugin to just the live stream pages?

Sitewide is a problem

**Comment by JoshWho** [comment]
My issue may be related to the cdn pulling the scripts through cloudflare and cloudflare gives limits to sockets. 

Once a socket disconnects from the client the client has to wait for a connection to establish back and that is what causes the whole webpage to freeze is the connection to the socket reconnecting.

**Comment by GreenDragonTavern** [comment]
@JoshWho what does ***ps aux | grep [p]hp*** show?

**Comment by JoshWho** [comment]
```
root@joshwhotv:~# ps aux | grep [p]hp
root      1773  0.0  0.1 656396 29884 ?        Ss   Jul15   0:03 php-fpm: master                                                                                                               process (/etc/php/7.4/fpm/php-fpm.conf)
root      1815  0.0  0.2 1538908 38244 ?       Ss   Jul15   0:03 php-fpm: master                                                                                                               process (/etc/php/7.2/fpm/php-fpm.conf)
root      1817  0.0  0.1 578044 24432 ?        Ss   Jul15   0:03 php-fpm: master                                                                                                               process (/etc/php/7.3/fpm/php-fpm.conf)
www-data  1915  0.0  0.0 580340 11948 ?        S    Jul15   0:00 php-fpm: pool w                                                                                                              ww
www-data  1916  0.0  0.0 580340 11948 ?        S    Jul15   0:00 php-fpm: pool w                                                                                                              ww
www-data  1919  0.0  0.0 658692 14268 ?        S    Jul15   0:00 php-fpm: pool w                                                                                                              ww
www-data  1920  0.0  0.0 658692 14268 ?        S    Jul15   0:00 php-fpm: pool w                                                                                                              ww
www-data  1929  0.0  0.0 1541204 14800 ?       S    Jul15   0:00 php-fpm: pool w                                                                                                              ww
www-data  1930  0.0  0.0 1541204 14800 ?       S    Jul15   0:00 php-fpm: pool w                                                                                                              ww
root     15429  0.0  0.2 331268 37284 ?        S    01:00   0:04 php /var/www/ht                                                                                                              ml/YouPHPTube/plugin/YPTSocket/serverCertbot.php
root     15499  0.0  0.0 187356  4012 ?        S    01:00   0:00 sudo nohup php                                                                                                               /var/www/html/YouPHPTube/plugin/YPTSocket/server.php
root     15500  1.6  0.3 356472 59096 ?        S    01:00  11:10 php /var/www/ht                                                                                                              ml/YouPHPTube/plugin/YPTSocket/server.php
You have new mail in /var/mail/root

```

**Comment by GreenDragonTavern** [comment]
My socket instance looks like this:
root        1372 86.4  0.0 126412 52528 ?        R    14:17 158:20 php /var/www/html/AVideo/plugin/YPTSocket/server.php

You have two instances of socket running, there should only be one. Try killing the sudo one and see what shakes out.

**Comment by JoshWho** [comment]
Ok I killed that we are now at 

```
root@joshwhotv:~# ps aux | grep [p]hp
root      1773  0.0  0.1 656396 29884 ?        Ss   Jul15   0:03 php-fpm: master process (/etc/php/7.4/fpm/php-fpm.conf)
root      1815  0.0  0.2 1538908 38244 ?       Ss   Jul15   0:03 php-fpm: master process (/etc/php/7.2/fpm/php-fpm.conf)
root      1817  0.0  0.1 578044 24432 ?        Ss   Jul15   0:03 php-fpm: master process (/etc/php/7.3/fpm/php-fpm.conf)
www-data  1915  0.0  0.0 580340 11948 ?        S    Jul15   0:00 php-fpm: pool www
www-data  1916  0.0  0.0 580340 11948 ?        S    Jul15   0:00 php-fpm: pool www
www-data  1919  0.0  0.0 658692 14268 ?        S    Jul15   0:00 php-fpm: pool www
www-data  1920  0.0  0.0 658692 14268 ?        S    Jul15   0:00 php-fpm: pool www
www-data  1929  0.0  0.0 1541204 14800 ?       S    Jul15   0:00 php-fpm: pool www
www-data  1930  0.0  0.0 1541204 14800 ?       S    Jul15   0:00 php-fpm: pool www
root     15429  0.0  0.2 331268 37284 ?        S    01:00   0:04 php /var/www/html/YouPHPTube/plugin/YPTSocket/serverCertbot.php
root     15500  1.6  0.3 356472 59096 ?        S    01:00  11:10 php /var/www/html/YouPHPTube/plugin/YPTSocket/server.php
You have new mail in /var/mail/root

```


I want to to come to my site here and let this vide play for a bit and go to another tab for a couple minutes then come back and tell me if the whole page is froze 

https://www.joshwhotv.com/v/.SSE4

**Comment by GreenDragonTavern** [comment]
Opened three (3) tabs in addition to your link, no issue here. Also curious why serverCertbot.php is still running? That's a one and done cron job.

**Comment by JoshWho** [comment]
Good question. Not sure. I will keep checking overtime. If it doesn't freeze up anymore than that was the issue was 2 ypt socket servers running.

**Comment by GreenDragonTavern** [comment]
I'd kill the certbot one too, has no business running as it should have closed long ago.

**Comment by JoshWho** [comment]
I killed the certbot one and now the socket server is disconnected

**Comment by GreenDragonTavern** [comment]
Weird, what does grep say now?

**Comment by JoshWho** [comment]
```
root@joshwhotv:~# ps aux | grep [p]hp
root      1773  0.0  0.1 656396 29884 ?        Ss   Jul15   0:03 php-fpm: master process (/etc/php/7.4/fpm/php-fpm.conf)
root      1815  0.0  0.2 1538908 38244 ?       Ss   Jul15   0:03 php-fpm: master process (/etc/php/7.2/fpm/php-fpm.conf)
root      1817  0.0  0.1 578044 24432 ?        Ss   Jul15   0:03 php-fpm: master process (/etc/php/7.3/fpm/php-fpm.conf)
www-data  1915  0.0  0.0 580340 11948 ?        S    Jul15   0:00 php-fpm: pool www
www-data  1916  0.0  0.0 580340 11948 ?        S    Jul15   0:00 php-fpm: pool www
www-data  1919  0.0  0.0 658692 14268 ?        S    Jul15   0:00 php-fpm: pool www
www-data  1920  0.0  0.0 658692 14268 ?        S    Jul15   0:00 php-fpm: pool www
www-data  1929  0.0  0.0 1541204 14800 ?       S    Jul15   0:00 php-fpm: pool www
www-data  1930  0.0  0.0 1541204 14800 ?       S    Jul15   0:00 php-fpm: pool www
You have new mail in /var/mail/root

```

**Comment by JoshWho** [comment]
Restarted it now show

```
root@joshwhotv:~# ps aux | grep [p]hp
root      1773  0.0  0.1 656396 29884 ?        Ss   Jul15   0:03 php-fpm: master process (/etc/php/7.4/fpm/php-fpm.conf)
root      1815  0.0  0.2 1538908 38244 ?       Ss   Jul15   0:03 php-fpm: master process (/etc/php/7.2/fpm/php-fpm.conf)
root      1817  0.0  0.1 578044 24432 ?        Ss   Jul15   0:03 php-fpm: master process (/etc/php/7.3/fpm/php-fpm.conf)
www-data  1915  0.0  0.0 580340 11948 ?        S    Jul15   0:00 php-fpm: pool www
www-data  1916  0.0  0.0 580340 11948 ?        S    Jul15   0:00 php-fpm: pool www
www-data  1919  0.0  0.0 658692 14268 ?        S    Jul15   0:00 php-fpm: pool www
www-data  1920  0.0  0.0 658692 14268 ?        S    Jul15   0:00 php-fpm: pool www
www-data  1929  0.0  0.0 1541204 14800 ?       S    Jul15   0:00 php-fpm: pool www
www-data  1930  0.0  0.0 1541204 14800 ?       S    Jul15   0:00 php-fpm: pool www
root     14722  0.0  0.0 187356  4124 pts/1    S    12:51   0:00 sudo nohup php /var/www/html/YouPHPTube/plugin/YPTSocket/server.php
root     14723  3.0  0.3 348844 50288 pts/1    S    12:51   0:00 php /var/www/html/YouPHPTube/plugin/YPTSocket/server.php
root     14765  0.0  0.0   4636   772 ?        Ss   12:52   0:00 /bin/sh -c php /var/www/html/YouPHPTube/plugin/Scheduler/run.php #Avideo Scheduler
root     14768 11.0  0.2 335652 37328 ?        S    12:52   0:00 php /var/www/html/YouPHPTube/plugin/Scheduler/run.php
```

**Comment by JoshWho** [comment]
there is the sudo one again. seems that automatically starts with the startup script

**Comment by GreenDragonTavern** [comment]
If you're root, no need for sudo on command line.

**Comment by JoshWho** [comment]
It was the copy script I didn't modify it before pasting

**Comment by GreenDragonTavern** [comment]
Highlight, Ctrl-C, then a right mouse click is sometimes in need of adjustment ;-)

**Comment by JoshWho** [comment]
Im talking about the one that shows on the debugger when it is disconnected.

**Comment by GreenDragonTavern** [comment]
No worries, was just kidding ya about the cut and paste. I troubleshoot as root to ensure sudo doesn't come into play. With that said, should only be one instance of AVideo socket per port.

**Comment by JoshWho** [comment]
Looks like it is running a lot smoother now. Im gonna have to check for that every reboot now until I can figure out why 2 starts up. I am gonna close this now.

**Comment by GreenDragonTavern** [comment]
If root is loading cron at boot, don't use sudo, not necessary.

**Comment by JoshWho** [comment]
It is doing it again

![image](https://user-images.githubusercontent.com/39392449/179369306-4b04c8ac-8f93-4d92-9d95-45b4fceef31a.png)

**Comment by JoshWho** [comment]
It is the socket server for sure. If this could just be used for the live stats page that would work better because the home page and video play page doesn't use it for how I have it setup.

**Comment by GreenDragonTavern** [comment]
Hmm...just put up a spanking new AVideo server, basically zero load. Socket at idle sucks up 4% of resources...100% of a single core. Something is amiss, agreed.

**Comment by JoshWho** [comment]
I just have the socket plugin turned off for now, it makes a huge difference.

**Comment by GreenDragonTavern** [comment]
Just got back to the house and going to run some simulations. Something is definitely up with socket interface. No way in hades does zero activity suck up cores for no reason, and this socket interface is hungry for NO REASON. Going to setup live stream for 30 minutes, attach 50 users and see what shakes out. Will post results of socket thereafter.

**Comment by JoshWho** [comment]
Looking forward to your findings

**Comment by GreenDragonTavern** [comment]
Jeez...15 users instantly did this! At 49% of which Sockets is almost ALL of a R630 Dual, 12 core bare metal box! Sockets is the kiss of death and thread KILLER! Box is at a slow CRAWL now. 50 users will easily kill it.
![SocketThreadKiller](https://user-images.githubusercontent.com/85363361/179375053-cb10defb-88e6-445a-be3f-0c4842ef7fea.jpg)

**Comment by JoshWho** [comment]
My site has increased in speed with everything ever since I disabled it. Day and night difference.

**Comment by GreenDragonTavern** [comment]
The reason for sockets is just the opposite of what's happening. Have company and have to partake but later tonight will dig deeper into why this flavor of sockets KILLS THRAEADS at a fearsome rate. You are correct, sockets is UNUSABLE as it stands now and folks at AVideo better believe it's a reality. An R630 with compiled PHP events should handle hundreds of active viewers without breaking a sweat vs KILLING a BOX!

**Comment by JoshWho** [comment]
I agree, something wonky with it majorly. Shouldn't even notice it is running in the background. I see youtubes running and their page loads are blazing. Mine are now really fast after I disabled it. Super weird.

**Comment by JoshWho** [comment]
I hope it is solvable, I really like the features for the chat and live user count. Im sure there is other background stuff that is important too not running at the moment. Wow I am so amazed how fast my site is right now without it though.

**Comment by JoshWho** [comment]
@DanielnetoDotCom Check out my site tell me if you think it is way faster than ever before. This is with the socket plugin disabled. 

I didn't know the socket server was hurting the performance that much and could explain why lot of people struggled with page loads on my site. Now every page loads super fast.

**Comment by JoshWho** [comment]
All the users that was complaining about the site freezing all are saying it is working great now. Only difference was me shutting off the socket plugin.

**Comment by GreenDragonTavern** [comment]
@JoshWho for whatever reason, below did the trick, just did a live test afterwards. Socket is no longer eating up threads like before, and when live finished server load settled right back down to normal.

sudo git fetch --all && sudo git reset --hard origin/master
sudo chown -R www-data:www-data /var/www/html/AVideo

**Comment by JoshWho** [comment]
Why the hard reset?

**Comment by JoshWho** [comment]
This is a huge factor in my site because It is live and is always under ddos so every bit of cpu is important here.

**Comment by JoshWho** [comment]
I have it back on for now for testing. Tell me if you see any slowdown. I did the chown and update

**Comment by GreenDragonTavern** [comment]
Have a live test on my social site: https://ourfreenation.org - Login is below, you'll see Tube on menu bar.

User: Demo
Password: Demo123!

**Comment by GreenDragonTavern** [comment]
Don't know what to tell ya, check out my demo site, there's much more going on than just AVideo and runs fine. Have a live setup and be interested on how it works for you. Above is login info...

**Comment by JoshWho** [comment]
It worked great. I didnt see any lag. Is your site under any load or anything?

Just trying to compare. My server is using right now 57-58 % cpu at the moment because of a ddos but so far still stable.

**Comment by DanielnetoDotCom** [comment]
@GreenDragonTavern  how do you simulate users?

**Comment by JoshWho** [comment]
I use a loader tool that simulates thousands of users at a time to do my test. check out loader.io

**Comment by GreenDragonTavern** [comment]
Live using cell and Larix, HLS video shows 864p, 57:41 time. Live is on same server as AVideo, use Encoder Network (remote encoder). Sockets showing 12% load, nothing active at the moment. Killed socket and went to 0%. Something is not right with socket or I have some sort of config issue that's causing a leak.

**Comment by JoshWho** [comment]
Im getting the page freezing again. The socket server is just not good. Why does it cause so much user complaints. I have a feeling this is what keeps people from staying on my site and browsing more videos. I have a stack of complaints about the page loads.

When I disable the socket server the users are all happy.

**Comment by GreenDragonTavern** [comment]
@JoshWho, try this...kill the certbot, and restart socket as root (remove sudo). Edit root cron and rem the Certbot #0 1 * * * nohup php /var/www/html/AVideo/plugin/YPTSocket/serverCertbot.php &

Do you have multiple IP's bound to interface?

**Comment by JoshWho** [comment]
I have ipv4 and ipv6 and cdn

I dont think it is certbot I never see that in the high cpu

**Comment by GreenDragonTavern** [comment]
All I know is removing certbot improved socket here. Was curious if you had multiple ipv4 addresses bound to your nic?

**Comment by JoshWho** [comment]
Nope just a single Ipv4

**Comment by JoshWho** [comment]
I wish there was a way to go back to just using the socket server for the chat and view counter for live streams. All the other functions needs really super fast processing and super fast dns response in order for it to run smooth.

**Comment by JoshWho** [comment]
@DanielnetoDotCom  Is there a way to test this using a remote socket server so it is not running on the same machine with the core?

**Comment by JoshWho** [comment]
a stand alone server might change this equation

**Comment by DanielnetoDotCom** [comment]
Hi

I just sent an update regarding the socket. 

can you please check if makes any difference?

**Comment by JoshWho** [comment]
Do I need to restart the socket server?

**Comment by JoshWho** [comment]
Now my live streams is not working. I had this scheduled for weeks

**Comment by JoshWho** [comment]
`[22-Jul-2022 15:02:07 America/Chicago] AVideoLog::ERROR: Could not connect: Connection closed before handshake ws://live.joshwhotv.com:12053?webSocketToken=MmU0SWZrRDF1bWh4b25VanQzWE1jWTNKMDIyNHkrdlFFQ0xWOEV4VDFHS0Q1cVBWUlg2VWIvdmlXODBDekwxc2FJa2ZsdllGQllVRTdEVHA3bzc5Z0I2anp6ZU1VR2pvenJJbEJTNEpWUERSU2U3amxsa0hEWnBFcTZHU0N4QkhjWWluVDBGU2c2U2VzeXhpQnh1dmRZM3p3YzBLem5VU0h2TTZpa3BkMVhFMDMwK3pHdWw0Z0VaQVl5TFVQcFN4d3BUdndnOTZuS2dVWU1EQVE5QUJPUDlsdWlSNXVIb0YzOGxBUGNabEgvVHAxSnpzWkNGVDYwdkZUSmZXNkdJOEFSSDlUWDV6NkJDVjJWTmxpamFoMWo5YVYwemU4SDBaRHJqNFJJVG1QanQ2NDZRd3hTNEcyUEgwNXNNeCtxRVkyTmNrdnlRdXA5UlNTUTJFTUxGTnlaUHBwcHZiT3JneUdaNGd1MkMvUDhNdXNFZmlHNnJCS1Q1bld5NDdwL1NQamIrMTdWQWwzOEFsbjQxSVZKT01wcndwSUJTOFN5QklQZUkrOCtqVXl4ejc5c3dicUJnb3dXQ0JEeW1ERHB5bFlZSitXbVd1UVNwZXpxOUc3bUcxa1I1MEw3Y2pMcE9RbmU2V2JjVU0wZkpKNnVQcDJvVUR4SkNibVJGb2luUzdFeVNBQ1M3cHFVeExhUksrVng5YjVHMWVmSnhKTDhCaUdERW9OZ3pleFByUkZiNlJVdFpwNVZiZ3l3MHFTYUoyaDZjN2tXZVJIMDRlTS9hUWlPR1ZOOWJTa3NlQldYZ1pMWGRyTEcvckRxZWdRTnNvOXFSWnF6UFVPMmUxSkNkYWd5ZzlQZDNZR3ZCYklQRnhxbWhqTjFscC9hY0MyWmlGZlFvTWp1Ulc3YlZjWjJ5anhPM0daREwxL1c2UW83Qjc=&isCommandLine=1 SCRIPT_NAME: /YouPHPTube/plugin/Live/on_publish_done.php`

**Comment by JoshWho** [comment]
Keeps disconnecting reconnecting sent out 500 emails already

**Comment by DanielnetoDotCom** [comment]
Hi, the live has nothing to do with the socket.

the only change on the socket was on the JS on the webpage, nothing on the server changes.

I guess your error is something else

**Comment by JoshWho** [comment]
It says the fail was a webSocketToken=MmU0SWZ

**Comment by DanielnetoDotCom** [comment]
First is should never use the ws://live.joshwhotv.com:12053 it should be wss://live.joshwhotv.com:12053 (SECURE)

otherwise you may face a lot of problems

I am not sure what did you changed

**Comment by JoshWho** [comment]
I never set this up. U did this and it has been the same since u last set it. No changes

**Comment by DanielnetoDotCom** [comment]
very strange it is using the ws 
let me check on your server

**Comment by JoshWho** [comment]
ok

**Comment by DanielnetoDotCom** [comment]
FYI this suppose to be your live server and this is what I got

https://live.joshwhotv.com:444/stat

![image](https://user-images.githubusercontent.com/18009293/180570804-10743b1b-e2bd-48dd-883d-169c7d4c3878.png)

this is how it should look like

![image](https://user-images.githubusercontent.com/18009293/180570996-fecdd092-8687-431a-9718-ecc55e02c61f.png)

**Comment by JoshWho** [comment]
> FYI this suppose to be your live server and this is what I got
> 
> https://live.joshwhotv.com:444/stat
> 
> ![image](https://user-images.githubusercontent.com/18009293/180570804-10743b1b-e2bd-48dd-883d-169c7d4c3878.png)
> 
> this is how it should look like
> 
> ![image](https://user-images.githubusercontent.com/18009293/180570996-fecdd092-8687-431a-9718-ecc55e02c61f.png)

That is like that for security. The server can see that page fine I have it in the allow list. Do not make that public it exposes streamers IP addresses

**Comment by DanielnetoDotCom** [comment]
Also, I found something regarding pagespeed that is loading the javascript out of order, it is causing some errors

![image](https://user-images.githubusercontent.com/18009293/180572291-35a9c916-cbe4-4eba-844a-3c0e3eb92d68.png)

I sent some updates to prevent this to happen and I guess it is working now

**Comment by JoshWho** [comment]
Sweet Thank you, I will keep a eye on this for a few hours to see how it works.

**Comment by JoshWho** [comment]
I can confirm it is working great now. Checked it after hours of leaving 2 browsers going with the live streams and the pages are not frozen. Awesome!!! Thank you @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Awesome, now that I know where the loads are coming from, I will try to make more improvements.
