### ISSUE TITLE
Autoplay is not working by default

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6887]
I have the settings switch for autoplay turned on

![6b9a9fba-5e0f-4f02-9984-c59807988722](https://user-images.githubusercontent.com/39392449/179374058-86802694-4699-450c-84d1-04edb929f613.png)

When checking the site on a new browser or incognito the autoplay is not on and you have to switch it on still

![download (9)](https://user-images.githubusercontent.com/39392449/179374108-70759180-3d73-486f-ba37-809b7e5e6408.png)

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Autoplay-and-Browser-Policies#user-overwrites-the-default-autoplay

**Comment by DanielnetoDotCom** [comment]
Really strange, I can confirm on your site it is going off by default, even with the correct configuration.

but on my side, it is working fine.

I can only suspect one of your JS is setting the autoplay cookie, for now I have no idea what is causing that.

**Comment by JoshWho** [comment]
Didn't know Java controlled it. What is the path of the script that it might need so I can whitelist it?

**Comment by JoshWho** [comment]
I found it. Thank you

**Comment by JoshWho** [comment]
It is not working again. I tried in a few different browsers.

**Comment by DanielnetoDotCom** [comment]
any JS error log?

**Comment by JoshWho** [comment]
Not that I see. No errors I do not even see the script that turns autoplay on in the source

**Comment by JoshWho** [comment]
I do not have pagespeed enabled so I know it is not that

**Comment by DanielnetoDotCom** [comment]
I am not sure what changes, but the autoplay works here from an incognito browser
