### ISSUE TITLE
Android app app

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#6888]
When users use the android application, something happens that did not happen before. 
When they upload a video and enter the TITLE AND DESCRIPTION, the title is not inserted. 
A wording is generated as you can see from the screenshot. 
This shouldn't happen and you need to fix this as soon as possible.
This problem happened after the last update done to version 12.
Can you fix it? 
Users all complain about this problem.

![Screenshot_20220717-022953_SharkTube.jpg](https://user-images.githubusercontent.com/82677269/179379324-90dc67c3-05b0-4511-bbec-f24aa8f2a2a4.jpg)

![Screenshot_20220717-022657_Gallery.jpg](https://user-images.githubusercontent.com/82677269/179379334-769bed1a-dfe0-40c9-b45e-6a37dcae5189.jpg)

![Screenshot_20220717-022623_Samsung Internet.jpg](https://user-images.githubusercontent.com/82677269/179379338-fead356c-62ff-434c-87be-ba8c6653028d.jpg)

![SmartSelect_20220717-022527_Samsung Internet.jpg](https://user-images.githubusercontent.com/82677269/179379346-3aa55ae2-374e-4e56-8e79-bdcd7f2cd9b2.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, I guess you have an old version of the APP.

the new one we use the encoder.

but, I may be able to fix it if you share the log at the moment you submit the video

![chrome-capture-2022-6-22](https://user-images.githubusercontent.com/18009293/180454288-ab2fed76-aa6d-4329-aba7-29b95db29ebb.gif)

**Comment by sharknetwork24** [comment]
Is it possible to have the app updated? 
You have never given me updates since I bought the apps.  
Is it possible to have Daniel?  
Thank you

**Comment by DanielnetoDotCom** [comment]
Hi

I need to charge to deploy a new version. (50 USD each)

all updates must be submitted for approval again on both platforms. I also need to charge if you want me to submit it for you. (50 USD each)

so to update both platforms I need to charge 200 USD

**Comment by sharknetwork24** [comment]
> Hi
> 
> I need to charge to deploy a new version. (50 USD each)
> 
> all updates must be submitted for approval again on both platforms. I also need to charge if you want me to submit it for you. (50 USD each)
> 
> so to update both platforms I need to charge 200 USD

Daniel would be okay to have the updates without needing to purchase the apps again.  After paying 400 USD the updates should be included, it would be more fair.  Paying $ 200 for the upgrade seems absurd to me.

**Comment by sharknetwork24** [comment]
If I had known that I would have to pay for the updates as well, I would not have bought the IOS and Anroid apps.  Developers usually pay first and subsequent updates are always free.  I'm sorry to tell you, but unfortunately it's not correct to charge for updates as well.

**Comment by DanielnetoDotCom** [comment]
every update requires manual work from my side. 

Sorry, but I cannot give updates for free.

**Comment by DanielnetoDotCom** [comment]
Also, you are not required to update. it may work with the newest version of AVideo,  but I also recommend you avoid updating avideo site, because there is no guarantee it will always work.

**Comment by sharknetwork24** [comment]
You could start by asking for $ 50 to upgrade everything, but not another $ 200.  I'm very sorry to come and find out about this.  I will look good in the future for Android and IOS applications.  Too expensive.

**Comment by sharknetwork24** [comment]
If I can give you some advice Daniel and to be more transparent for who will buy future applications it seems more than right that you write it down and let it be known.  I didn't even get the source files when purchasing the apps.  I was really very sorry.
