### ISSUE TITLE
Thumbnail images not been correctly generated

### ISSUE THREAD

**Issue by sipero** [WWBN/AVideo#6889]
Hi,

I'm using version 11.8 and over the past few days I am noticing that the roku thumbnails in most cases are not being generated but also the size of thumbnails has suddenly been reduced to 366x188. The Thumbmail that shows in AVideo site is fine but not in the feed.

How do I fix this?

**Comment by DanielnetoDotCom** [comment]
Check this

![image](https://user-images.githubusercontent.com/18009293/179518567-88e58656-48b8-4da8-8177-1e0af08718c6.png)

**Comment by sipero** [comment]
[https://nimb.ws/Tjn3kI](url)

It seems to work sometimes but not always and looks like it is dependant on the ecoder that I used

**Comment by sipero** [comment]
Any more news on this. As ROKU requires the  thumbnails to be 800x450 why are these n ow being created as 1280x720. It is kind of frustrating having to manually re-generate these to the righ size.

**Comment by sipero** [comment]
If you are not able to change this for me perhaps you can tell me the file(s) I need to change so I can get this fixed. I'm adding at least 240 videos per month so this is key for me to have these images correctly generated

**Comment by DanielnetoDotCom** [comment]
1. make sure you have the correct size on the plugin
2. make sure you upload high-resolution images to avoid the black border on the images. we will not upscale images
3. Run this command line to delete all thumbs `cd /var/www/html/AVideo/install/ && php deleteThumbsFiles.php` , then let the script create all of them again

**Comment by sipero** [comment]
1. What do you mean the correct size on the plugin?
2. Most of these are coming from Youtube so have thumbs like this https://i.ytimg.com/vi/g8zahGaM280/maxresdefault.jpg
3. Will the thumbnails get recreated automatically after they are all deleted?

**Comment by DanielnetoDotCom** [comment]
> What do you mean the correct size on the plugin?

you are right, forget this, the roku size is hardcoded

> Most of these are coming from Youtube so have thumbs like this https://i.ytimg.com/vi/g8zahGaM280/maxresdefault.jpg

this is a youtube-dl issue, we always get the max size as possible. the only solution I can provide you is to let you reupload a new thumbs

> Will the thumbnails get recreated automatically after they are all deleted?

yes, but you still need to upload a high resolution version, otherwise it will create the same as before

**Comment by sipero** [comment]
Previously you were generating the 800x450 thumbnail images for the ROKU thumbnails without issue. youtube-dl have not updated their program since Dec 2021 so just wondering why you cannot continue to do so.

**Comment by DanielnetoDotCom** [comment]
the image quality you will get from youtube does not depend on us.

it can be on youtube-dl side or on the youtube side. maybe youtube has changed something on their side

BTW: youtube-dl usually is on the crontab to update every day.

**Comment by sipero** [comment]
Yes as you say youtube-dl is on the daily crontab. I just wish there was an easy way to ensure that that 1280x720 images that get generated were resized to 800x450 and the correct link was added into the roku json feed.

Right now I am importing between 240 and 500 videos per month and that is likely to increase to 2000+  over the coming month. These are all being used on ROKU and Amazon Fire TV channels and will expand to other platforms soon like Android and AppleTV so would be a big help if this could be catered for.
