### ISSUE TITLE
Name category and sous category

### ISSUE THREAD

**Issue by lachainestoplinky** [WWBN/AVideo#6890]
Hello,
I updated my Avideo site to version 12.0
I was on version 10.5
I passed all the intermediate versions

in version 12.0, I noticed that the names of categories and subcategories are no longer displayed
and there is no longer the link to display the videos of the category on the right
only the icon is displayed with the link and the name of the category
see on my site
http://lachainestoplinky.tv/videos/

**Comment by DanielnetoDotCom** [comment]
I can see your categories

![image](https://user-images.githubusercontent.com/18009293/179518863-6c7cb174-20a7-4342-b962-87f935be4167.png)

**Comment by lachainestoplinky** [comment]
hello, 
thank you because, by installing a clean version 12, 
I was able to correct the parameters of the gallery plugin. 
it is in this presentation that I find it strange not to see the name of the category next to the icon on the right side of the thumbnails.
![Capture d’écran 2022-07-18 à 17 53 23](https://user-images.githubusercontent.com/39954233/179553473-a3243936-da6f-4db9-a9b2-a054e3f8f0ac.jpg)


on hover, there is the name and the link is valid
there was the tire in version 10.5
