### ISSUE TITLE
Thanks button 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#6891]
YouTube recently added a thanks button hooked to google pay. 
Is there any way to hook one up on youphptube? This is a great fast way to support creators.
https://youtu.be/30hmCcs4nZI 
![Screenshot_20220717-143744_YouTube.jpg](https://user-images.githubusercontent.com/66537018/179420139-903063f6-7d20-45dc-b6fa-563d12116a99.jpg)

**Comment by fakeologist** [comment]
It is. You click it, it sends a payment, then auto posts a comment showing the donation. It's very slick.

**Comment by DanielnetoDotCom** [comment]
You may have a similar thing if you use the wallet for donation.

https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform#donation-from-wallet
