### ISSUE TITLE
Members Only Area Plugin

### ISSUE THREAD

**Issue by JamesMyer123** [WWBN/AVideo#6892]
I would be a great idea to have a plugin that allow Chanel owners to have a Members Only area that members pay a monthly fee for , this area could host Premier Content and Members only Live Streams, etc

**Comment by JamesMyer123** [comment]
Really good, and very exciting @DanielnetoDotCom How will the Creator know of it , that its available? but very good

**Comment by DanielnetoDotCom** [comment]
Hi, I just made it available on the marketplace 

https://youphp.tube/marketplace/

**Comment by GarethBagley** [comment]
Great Josh! 

I Will purchase that 
/Gareth

Gareth Bagley, husfoto.
