### ISSUE TITLE
Categories Not viewing right

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6897]
Go here and you will see this https://www.joshwhotv.com/cat/news

![910ea7b3-2e5f-47b9-88b5-c3152b165007](https://user-images.githubusercontent.com/39392449/179613147-78aafd2a-357a-4281-8ef2-8df6de27ec9c.png)

**Comment by DanielnetoDotCom** [comment]
Please update and let me know if fixes it.

**Comment by JoshWho** [comment]
I updated and the top loads good but when u scroll down it seems like it keeps wanting to reload the same live streams when the infinite scroll loads more rows, 

![5272ed1a-d1fc-4b9b-a2d6-210698243e3d](https://user-images.githubusercontent.com/39392449/179632155-784465b0-92a1-47b5-bee9-34fa3eac3045.png)

**Comment by DanielnetoDotCom** [comment]
I update and debug yous site directly. 

please check now
