### ISSUE TITLE
Block download

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#6898]
@DanielnetoDotCom, doing some security tests, I found that it is possible to download files from my site, using the TubeDigger software, easily.

Is there any way to block this way of downloading?

![image](https://user-images.githubusercontent.com/37880073/179645609-d1ff6712-fc1a-4aba-b551-457bc2223324.png)

**Comment by DanielnetoDotCom** [comment]
The best way to avoid download is to use the HLS format 

https://github.com/WWBN/AVideo/wiki/VideoHLS-Plugin#download-protection
