### ISSUE TITLE
More renewed than subscribers

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6899]
Can anyone explain this? I am seeing more renewed subscriptions than I have subscribers.

![0E8362DF-BE95-4563-A0E1-2CFF4D243F24](https://user-images.githubusercontent.com/58601786/179688270-0fdf9945-4391-436e-8111-616c09c893cc.png)

**Comment by DanielnetoDotCom** [comment]
What do you mean?

**Comment by barrunning** [comment]
I was showing in the wallet history that I had like 20 renewed subscriptions. When I only have like 10 subscribers.

**Comment by barrunning** [comment]
![0CD71636-BB97-487A-9FA0-14DBD7C915EB](https://user-images.githubusercontent.com/58601786/180340526-dfee30e3-e6ba-4e4b-bfb5-e878f8a579f4.png)

where is this coming from. I don’t have that many subscribers to have that many renewed.

**Comment by DanielnetoDotCom** [comment]
Each wallet entry should be a message that you received from the payment gateway.

so if you have monthly subscriptions and 10 subscribers and all of them are with you for 2 months, yes you should have at least 20 entries on the wallet.

**Comment by barrunning** [comment]
But that shows renewed on the same day.

**Comment by DanielnetoDotCom** [comment]
Are you at least receiving the payment?

is the only problem the payment notification?
