### ISSUE TITLE
unverified users can't watch videos 

### ISSUE THREAD

**Issue by ahmedxda** [WWBN/AVideo#6900]
Is it possible to add an option that enables me to open website for people so that they can see the content but can't watch videos?

**Comment by DanielnetoDotCom** [comment]
you probably can require a login to access the site. and then share the password with him

## userMustBeLoggedIn

![image](https://user-images.githubusercontent.com/18009293/180456216-c191c030-f116-4405-9549-c41773850793.png)

**Comment by ahmedxda** [comment]
I know that option but I'm talking about an option that enables people to see the website but they can't play videos

**Comment by DanielnetoDotCom** [comment]
you may want to check usergroups 

https://github.com/WWBN/AVideo/wiki/Videos-Privacy-Options-:-Active,-Inactive-,-Unlisted-&-UserGroup

**Comment by ahmedxda** [comment]
I know all these options Dan..please keep in mind to add an option that enables people to see the website content but can't watch videos... make it per user please in next updates if possible..
I still have some problems with the private encoder which stopped completely after update to v12..
I'll try to get the logs in a separate post here..
thanks Dan for the help🌷

**Comment by DanielnetoDotCom** [comment]
I still do not understand the privacy you are looking for.

to add let a user watch a video just add it on the same user group as the video
