### ISSUE TITLE
Notifications for broken Videos???

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6902]
For some reason the notification is being sent out before the video is even confirmed to be uploaded and even broken video still send notifications.

![6cc791c5-a980-4bfb-ac51-c3df29b8a8fb](https://user-images.githubusercontent.com/39392449/180283651-f3e0e898-c27e-487f-ac3f-696fe762c18b.png)
![93740858-02c4-444a-ad20-8d99e02bd8c0](https://user-images.githubusercontent.com/39392449/180283745-9c6edeb6-5a48-4f02-837a-1eef8c877fa9.png)
![download (10)](https://user-images.githubusercontent.com/39392449/180283782-7c37c664-5c7a-4fa4-9983-3831706f8606.png)

**Comment by lachainestoplinky** [comment]
Hello,
I noticed the same problem
AVIDEO version 12.0

**Comment by DanielnetoDotCom** [comment]
Hi, 

First, we must find out why the video is broken.

the broken missing file is only detected on the first video play attempt, so before that, we consider the video active.

**Comment by JoshWho** [comment]
> Hi,
> 
> First, we must find out why the video is broken.
> 
> the broken missing file is only detected on the first video play attempt, so before that, we consider the video active.

This happened with one of your encoder servers so I have no way to check the log to see what went wrong.

**Comment by JoshWho** [comment]
Can we change how the notification is sent? Like a file check to see if the mp4 is there before doing it?

**Comment by JoshWho** [comment]
Sweet, thank you @DanielnetoDotCom
