### ISSUE TITLE
How do I disable embeds? How do I break someones embed?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6903]
**Describe the question**
functiongetShareMenu.php

```
$objSecure = AVideoPlugin::getObjectDataIfEnabled('SecureVideosDirectory');
...
                if (empty($objSecure->disableEmbedMode)) {
                    ?>
                    <li class="nav-item">
                        <a class="nav-link " href="#tabEmbed" data-toggle="tab">
                            <span class="fa fa-code"></span>
                            <?php echo __("Share Code"); ?>
                        </a>
                    </li>
                    <?php
                }
```

Been searching for where to turn this off. Thus far unable to find.

Second question. Someone has embedded a video and is racking thousands of views. I guess that's cool, but they should have linked instead of stealing bandwidth... How can I break their embed without deleting the video?

**Comment by walt93** [comment]
Here's how I handled the bandwidth thief. I rendered this out, and replaced the video, marking it as unlisted so it's not visible to the main site, but still plays as an embed. 😎

https://user-images.githubusercontent.com/11711050/180334786-3bebffa0-1a4c-4a07-969a-07a89e7f1ba6.mp4

**Comment by DanielnetoDotCom** [comment]
I like your video, I just did not understand what exactly you are trying to do.

**Comment by walt93** [comment]
Disable the “Share Code” links on the videos page. I hacked it out of the code, but I notice it has a switch to turn it off. I just couldn’t figure out which plug-in/setting is $objSecure->disableEmbedMode

**Comment by DanielnetoDotCom** [comment]
If you Restrict Embed Videos with the SecureVideosDirectory plugin, it should forbid access even if you get the share code.

https://github.com/WWBN/AVideo/wiki/SecureVideosDirectory-Plugin#restrict-embed-videos

**Comment by JoshWho** [comment]
Why not just enable hotlink protection if you do not want to share your videos?

**Comment by walt93** [comment]
Because I was unaware of this until I saw a video rack up a couple thousand views coming in through the back door as it were. I prefer them to come in through the front door. I don’t ‘mind sharing - I leave download links on too. 🤷‍♂️
