### ISSUE TITLE
Left Hand Menu

### ISSUE THREAD

**Issue by JamesMyer123** [WWBN/AVideo#6906]
Is there a way on the left hand menu to make it left justified, and no color , im trying to give the user experience very similar to YouTube?

**Comment by DanielnetoDotCom** [comment]
you may be able to add some custom CSS

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript

**Comment by JamesMyer123** [comment]
Is there a way I can just edit the existing one?
