### ISSUE TITLE
Limited videos display

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6907]
What happened to the other videos. It use to show additional selections via number. Now it only shows 7 videos of the 800 that are available.
![BC966841-36F5-4249-B19C-B925A594272B](https://user-images.githubusercontent.com/58601786/180416592-e004e629-4e4d-4e13-8e78-02860e9cfef9.png)
![61A5AE88-E377-4534-862A-80A731D4E4A1](https://user-images.githubusercontent.com/58601786/180416623-4e6b18be-00e7-4c41-9669-604f220eecbd.png)

**Comment by barrunning** [comment]
![D133938D-8DF9-4201-85D8-3CCEB4F927C0](https://user-images.githubusercontent.com/58601786/180419435-aebabb5f-fbf4-4f4a-be8e-eb303b5c5cfb.jpeg)

why isn’t the body circled portion showing up in the other pictures?

![063F3305-ABDA-4C7B-B127-0C7604D2DA59](https://user-images.githubusercontent.com/58601786/180419632-5157ffd0-376d-4b68-9617-fb36be81c092.jpeg)

**Comment by DanielnetoDotCom** [comment]
if you click on the category it may expand so you will be able to see all.

to list more videos on the first page you may want to increase it here:

![image](https://user-images.githubusercontent.com/18009293/180461823-58c522f6-0365-4eb2-bc38-03a8d778a712.png)

**Comment by DanielnetoDotCom** [comment]
suppose to have pagination on the gallery mode. 

on the flix mode, if you click on the category, you should see all the videos.
