### ISSUE TITLE
Chat shows everything is from 5 hours ago  when we type

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6908]
Not sure why the time is not synced with my system time server setting. 

![9233432d-07d6-4b66-bb1b-7094947c6b42](https://user-images.githubusercontent.com/39392449/180572178-5eec7119-8fa4-48e5-aeec-805c65e81086.png)

**Comment by DanielnetoDotCom** [comment]
are you using the latest chat2?

**Comment by JoshWho** [comment]
Yes

**Comment by DanielnetoDotCom** [comment]
Please check if this update resolves something. 

if persists, please screenshot the JS console.

**Comment by JoshWho** [comment]
My Live page is messed up now

![0b5fe57a-abd6-44d8-86d4-685484db8dc3](https://user-images.githubusercontent.com/39392449/180627530-2db13156-7181-4186-bf8f-df1fdea07673.png)

**Comment by DanielnetoDotCom** [comment]
checking

**Comment by DanielnetoDotCom** [comment]
Any idea where this code come from?

<script> var all_links = document.querySelectorAll('a'); for (var i = 0; i < all_links.length; i++){ var a = all_links[i]; if(a.hostname != location.hostname) { a.rel = 'noopener'; a.target = '_blank'; } } </script>

and you have it twice

**Comment by JoshWho** [comment]
> Any idea where this code comes from?
> 
> ```
> <script> var all_links = document.querySelectorAll('a'); for (var i = 0; i < all_links.length; i++){ var a = all_links[i]; if(a.hostname != location.hostname) { a.rel = 'noopener'; a.target = '_blank'; } } </script>
> ```
> 
> and you have it twice

That just forces external links to open in new tab

**Comment by DanielnetoDotCom** [comment]
this data-pagespeed-orig-index is messing up your javascript. you really need to disable it.

I do not know where it comes from.

**Comment by DanielnetoDotCom** [comment]
If you do not stop it, it will make it impossible for me to help you. this pagespeed is changing the JS on the page

**Comment by DanielnetoDotCom** [comment]
I could make a workaround and your site is back.

but this problem was the pagespeed fault.

**Comment by DanielnetoDotCom** [comment]
Looks like your server has some type of cache for PHP, if you access the site using a different URL (new cache) for example https://www.joshwhotv.com/live?nocache=1

the page will work. but your current https://www.joshwhotv.com/live is cached and not working

**Comment by JoshWho** [comment]
Sorry just got back home. 

It is Memcached that needed purged. I just purged it by running 

`/etc/init.d/memcached restart`

I have been using Pagespeed since the start. All Mod Page speed is doing is rewriting the java and putting it in separate blocks so the page loads are faster. It also minifies html and images and works with the memcached to keep it all cached in ram instead of disk. 

When you have a website run too much java all at once it creates bottlenecks. Same goes for css all at once. 

It shouldn't interfere with the code unless the code is being cut off by the limits created for maximum performance.

**Comment by JoshWho** [comment]
> If you do not stop it, it will make it impossible for me to help you. this pagespeed is changing the JS on the page

It is not a physical change just virtually dynamic.

**Comment by JoshWho** [comment]
It is working good again after flushing the memcached. Thank you @DanielnetoDotCom  you rock buddy!!!
