### ISSUE TITLE
Images on gallery take >1 minute to appear. I can't tell what's going on from the logs. 

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6909]
**Describe the bug**
![Screen Shot 2022-07-22 at 3 27 25 PM](https://user-images.githubusercontent.com/11711050/180576498-0bbc06a7-fab9-4fc3-9e00-cc8081fddfb2.png)

I loaded the page over a minute ago. On desktop it seems like it's simply never going to finish loading the page. On mobile images are showing up after ≈1 minute. Please advise!

Note: As I was typing this, images loaded on the desktop window screen capped above, so perhaps >2-3 minutes?

**Comment by DanielnetoDotCom** [comment]
Please check if with the last git pull this persists
