### ISSUE TITLE
video title

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#6911]
Hello,
the video title is too close to the thumbnail
and it no longer works if you click on the title to open the video but only in the thumbnail
the same happens in the demo

Thank you
Ilias

![link](https://user-images.githubusercontent.com/60543030/180614093-7ff64ead-4b32-444b-a988-73fbda81c899.jpg)

**Comment by DanielnetoDotCom** [comment]
It is not because it is too close.

the link was removed from the title. 

removing the link makes it easier to reuse the code.

**Comment by wetubeclub** [comment]
Ok! Thank you Daniel for your response!
