### ISSUE TITLE
A way to Mark Certain Channels Videos as suggested automatically 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6912]
The video suggestion system is working great making it easy for people to find watchable content that we can currait.

Idea is to make it to where I can Mark a Channel for automatically suggesting (staring) their videos. 

This way the mods do not have to search for new uploads to put in suggestion everyday and It will automatically include the channels videos for suggestion.

**Comment by JoshWho** [comment]
Not the creator, but the admin selects the channel or channels that will suggest all their videos.

**Comment by DanielnetoDotCom** [comment]
so all the videos on the channel ?

maybe a better option is for the admin let some users select their videos as suggested.

**Comment by JoshWho** [comment]
Hey that will work to as long as the users learn to do it. I just want it to be as automated as possible.

**Comment by JoshWho** [comment]
I can make a tutorial that explains that, so it wouldn't be to hard for people to learn. I think it is a great idea.

**Comment by DanielnetoDotCom** [comment]
I may add this option in the future. right now I am engaged in something else

**Comment by JoshWho** [comment]
Sweeeeeeeeeeeeeeeeeeeeeeeeeeeeeet

**Comment by JoshWho** [comment]
This is the other reason why I want this, Trying to manually curate the videos takes hours sometimes just to do a few of them. 


https://user-images.githubusercontent.com/39392449/182699488-34d0a684-b667-48da-9176-ed1abe40c0d4.mp4
