### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#6913]
site logo not showing in video player after last gitpull
any help?

Thank you
Ilias

![logo](https://user-images.githubusercontent.com/60543030/180660582-f937ab9b-1f1b-45e9-bc78-ac86a1f23a48.jpg)

**Comment by DanielnetoDotCom** [comment]
can you please check my latest git pull?

**Comment by wetubeclub** [comment]
works like a charm!!!!!!!!!!!!

Thank you
Daniel
