### ISSUE TITLE
Live Link Embeds not showing embedded live streams

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6924]
https://www.joshwhotv.com/liveLink/289/live-trump-rally-in-prescott-valley-arizona
![60d75fe2-9699-4144-99dd-220f5815af66](https://user-images.githubusercontent.com/39392449/180883540-a788a420-d27a-4ac0-bc99-91dee22182c9.png)

https://www.joshwhotv.com/liveLinkEmbed/289/live-trump-rally-in-prescott-valley-arizona

![4b6ad100-758a-425f-a742-c9217fd7b922](https://user-images.githubusercontent.com/39392449/180883609-ffc40885-9e13-4a7a-ba47-d7da5bfb81ef.png)

**Comment by DanielnetoDotCom** [comment]
Just checked, you are using this link https://rumble.com/embed/v19bkmj/?pub=7dth1

this working on the Livelink is magic. this is supposed to be an embedded link

but I like the idea and I was able to reproduce the magic on the livelink embed  :)

**Comment by JoshWho** [comment]
Brilliant. Love it thank you @DanielnetoDotCom
