### ISSUE TITLE
Video Calling not allowing me to answer the call

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6925]
@DanielnetoDotCom watch this video please. Not able to answer the call

https://user-images.githubusercontent.com/39392449/180928420-bc836cc6-84b9-4211-ac9b-b6d584c05839.mp4

This is a really neat feature by the way, and would love to help somehow with a phone page design tweak, and maybe hiding the footer.

![b7d5b12a-e05f-4852-b042-d8f81dbc94ce](https://user-images.githubusercontent.com/39392449/180937853-6f0488c3-61dc-4cce-8c88-4e79d59f0514.png)

**Comment by mrgodgiven** [comment]
I would love to have the video call feature as well. How do i get it @JoshWho

**Comment by JoshWho** [comment]
> I would love to have the video call feature as well. How do i get it @JoshWho

Make sure you have the latest Updates on the Core site and all the plugins. Then check the plugin called CustomizUser
look for 

![30701480-f9ecfd710cb1d36556501b50d06792ab](https://user-images.githubusercontent.com/39392449/181239226-a6a8a5f0-4ee9-4a7f-ba9f-ca2d2f6993ad.png)

**Comment by mrgodgiven** [comment]
Thanks

**Comment by DanielnetoDotCom** [comment]
@JoshWho can you see if there is any JS error on the JS console?

**Comment by JoshWho** [comment]
Doesn't let me run the debugger at the same time

**Comment by JoshWho** [comment]
I can make pagespeed ignore a script if I know the direct path to it, WHat is it I am looking for?

**Comment by JoshWho** [comment]
![image](https://user-images.githubusercontent.com/39392449/181380268-9d58d88d-fdc4-4859-9eb8-da14ebf186e5.png)

**Comment by JoshWho** [comment]
![image](https://user-images.githubusercontent.com/39392449/181381047-895140d1-b804-4a25-a708-9d4819b5343e.png)

**Comment by DanielnetoDotCom** [comment]
Hi, can you just disable the pagespeed to see if it is causing it?

**Comment by JoshWho** [comment]
Does the same thing when pagespeed is off

**Comment by DanielnetoDotCom** [comment]
I will make more tests on the caller next week

**Comment by JoshWho** [comment]
> I will make more tests on the caller next week
Thank you, no probs

**Comment by DanielnetoDotCom** [comment]
Josh, can you please check if the latest git pull makes any difference for you?

**Comment by JoshWho** [comment]
Here is the new test


https://user-images.githubusercontent.com/39392449/183507064-677c2dc4-eb85-4733-862a-98c15f0f49dc.mp4

**Comment by Lordblanca** [comment]
This is a fantastic Idea. I have the same problem I just disabled it. How about adding skype or google chat. To the chat instead. There is a developer site for skype... https://docs.microsoft.com/en-us/skype-sdk/skypedeveloperplatform... and also one for google chat... https://developers.google.com/chat ... just an idea.

**Comment by DanielnetoDotCom** [comment]
It should be better now

**Comment by JoshWho** [comment]
Awesome. Yes just tested it and it works great. Thank you @DanielnetoDotCom
