### ISSUE TITLE
Sign up box does not fully display

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6928]
When a person tries to sign up they sign up box  does not fully display.
It happens on safari and chrome. No idea about other browsers.
![E69A63FD-972B-4BFE-BADB-7099EB2663AA](https://user-images.githubusercontent.com/58601786/181074825-08166b0d-ef0e-4587-8997-76a010ecf789.png)

**Comment by DanielnetoDotCom** [comment]
Should be the same issue as here https://github.com/WWBN/AVideo/issues/6929
