### ISSUE TITLE
The mobile app doesn’t display an image of the video.

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6929]
The videos plays but no image of what is being selected is displayed.
![1577133C-EC91-4314-BAF4-D08757EA61BF](https://user-images.githubusercontent.com/58601786/181085578-92e8445c-8d16-46f0-b000-edb6d38b286f.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I can see your CDN is set up for the old domains, I am working on a fix for it now.

**Comment by DanielnetoDotCom** [comment]
Looks like you shut down the old domains so the CDN stopped.

I just update the CDN and all should be fine now

**Comment by barrunning** [comment]
Yes. I had asked if shutting them down would mess up anything. You said no.. so off line they went.

**Comment by DanielnetoDotCom** [comment]
I am so sorry, I forgot the CDN

**Comment by barrunning** [comment]
All good now. Thank you
