### ISSUE TITLE
Search is slow

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#6931]
Anyone else notice search is very slow?
Maybe it's just my instance.

**Comment by JoshWho** [comment]
No, it really is slow. Depends how large the database is also but it is slow. Would be nice to see it be a little more instant than the long hang it has most the time.

**Comment by JoshWho** [comment]
Somehow there needs to be a cache system for the search so the queries won't hang.

**Comment by walt93** [comment]
Search has been that way for a while. 

I assume switching to Postgres would be like open heart surgery or are we sitting on some ORM layer that can do so with relatively less pain? I've used it to query 250k-500k records building a video page similar to avideo and it was blazing fast. Or is mysql not the barrier here?

**Comment by JoshWho** [comment]
I questioned the SQL to it but I am sure that can't be the issue, I think there is a missing element here for cached queries or something.

**Comment by elico** [comment]
@JoshWho The question is: What and how the search query do?
It's possible that the issue is not the MySQL but rather a coding issue.
