### ISSUE TITLE
Inactive videos still show if suggested

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6932]
![5462aabe-f1ba-4163-ba7b-4535f5b613e2](https://user-images.githubusercontent.com/39392449/181148223-e62890e3-4892-4fc9-a9ea-54eac0b63d18.png)

![7b58f4d5-be32-4246-8994-b564dcf1d24a](https://user-images.githubusercontent.com/39392449/181148238-284251e6-1a36-4e03-abe6-e17be273166b.png)

**Comment by DanielnetoDotCom** [comment]
You are right, suggested should show only if it is active. 

even unlisted will not be suggested anymore

**Comment by JoshWho** [comment]
> You are right, suggested should show only if it is active.
> 
> even unlisted will not be suggested anymore

Thank you
