### ISSUE TITLE
When U click Thumbnail to Edit it shows a error page

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6933]
![bfe90bf9-db6a-4e17-a00b-8c5929810ce4](https://user-images.githubusercontent.com/39392449/181238063-5fa9b9f3-db99-472b-a7f4-1b8bf9553ee3.png)
![71806cfa-51b4-49fb-84ec-f0323efed8b5](https://user-images.githubusercontent.com/39392449/181238082-13c89db5-c94f-4bfd-85b9-cdbe35da9278.png)

**Comment by DanielnetoDotCom** [comment]
thanks for notice that, it may be fixed now

**Comment by JoshWho** [comment]
> thanks for notice that, it may be fixed now

No probs. Thank you
