### ISSUE TITLE
Mass Moving Videos to a Certain Category

### ISSUE THREAD

**Issue by JSY-Ben** [WWBN/AVideo#6934]
Hi Daniel. Really appreciate all the work you do on this project.

Would it be an easy enhancement to add an option in the 'My Videos' section to move all ticked videos to a video category?

Many thanks :)

**Comment by DanielnetoDotCom** [comment]
Hi

you should be able to bulk move them

select all the videos you want to move and click on the category dropdown

![chrome-capture-2022-6-27](https://user-images.githubusercontent.com/18009293/181381473-9c21fc8e-0684-4adb-8f3c-2a36ff89fce0.gif)

**Comment by JSY-Ben** [comment]
Ah I cannot believe I didn't spot that! Many thanks.

I suppose one more enhancement would be to show in 'My Videos' all videos in one category, so you can easily move a bunch of videos in one category to another.
