### ISSUE TITLE
New page refresh bug appeared

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#6936]
Hi,

When i refresh the homepage on any browser it doesn't refresh anymore. I get an old version until i either do a hard refresh of clear the browsers cache. I dont use the plugin cache and have no other caches running. Cleaning the cache makes no difference at all to the problem. It shows me as logged out when i hit the home button until i do cmd shift and R (MAC) for a hard refresh and then the page loads proper again. I have to keep clearing my browser cache or a hard refresh for the home page to display properly otherwise it shows an old version of the homepage i.e most recent will show uploads from days ago as the most recent uploads when this is not true so users think nobody is uploading. So my site has stalled for the past 24hrs and activity has dropped dramatically and nobody's uploading.

Also on safari now all of a sudden the home page thumbs are all broken (image attached). It is only affecting safari on my MAC not on my iphone and other browsers don't show this problem, and cleaning safari cache makes no difference as its still the same. 
![Screenshot 2022-07-29 at 08 39 34](https://user-images.githubusercontent.com/107706817/181709743-43362a21-3b11-40e2-9660-26fb5805bdd3.png)
It was fine up until a few days ago. I do not mess with the site the only thing i do is git pull regularly but my site has become so broken since 12.0. Some plugins don't work proper anymore and all i get is earache off my members blaming me for breaking the site. Ive done nothing to it. The site prior to 12 was working perfect i had no issues but now it seems it is going to take many months for all these bugs that keep appearing to be fixed and for the plugins working again. Im quite deflated over this.

**Comment by DanielnetoDotCom** [comment]
Please make sure you have the latest git pull.

clear the cookies from your browser and then reload the page again.

**Comment by para2022** [comment]
as i have stated many times i update daily.

Cookies have been cleared from all browsers. Server restarted. No caching services run on my server. It is not my browsers. The problems exist on all machines that i own and mobile devices. Same problem on work machines.

My ubuntu server is rock solid and run avideo for 5 months flawlessly.

As i stated all my issues started on the 12.0 update. I have even overwritten all files with a fresh download and ftp the files overwriting them so all files are clean. Permissions are fine. Some plugins are broken as i said like signup agreement popups now dont work amongst other things. Thumbnails worked on the homepage on safari on 11.8 and now its a mess and i have homepage cache issues that i mentioned earlier. The homepage does not update anymore without cmd+shift+R or clearing the browsers cache. As i said i dont run caches so why is the homepage caching and not updating anymore.

Nothing whatsoever has changed other the site being updated.

**Comment by para2022** [comment]
Hi Daniel the last git pull today fixed this issue with the cache and the homepage is loading properly now. But I still have the issue with the messed up thumbs on safari like the image above. Many thanks for the fix :)

**Comment by para2022** [comment]
Hi Daniel the latest git pull i did today seems to have fixed the issue with the cache and the homepage on firefox, chrome and brave browsers. It is now loading the current homepage videos properly just how it used to. However this problem still exists on iphone safari whereby it is a more serious problem as you have to go to iphone settings to clear the browser cache for the homepage to display the current version. The site does not update on iphone safari but it used to. On brave browser when you clicked home or the logo it would show you as logged out but when i did a hard refresh I am logged back in again. This is fixed now though with the latest git pull. 

Iphone chrome also had the same problem with the site not updating but again this now seems to be working with the latest git pull. 

On my Mac safari I still have missing thumbs throughout the site like in the image above. It is all loading properly on firefox, brave and chrome on the MAC just not safari. I have cleared its cache and still the same problem. No plugins installed on safari and not settings have been changed, it is at its default settings and i only use it for testing purposes but i can see a lot of my users are using safari so all they will see is a broken site and are unlikely to come back. Thanks so much for the fixes.

**Comment by para2022** [comment]
Its working fine now on iphone safari Dan. Great work.
The only browser having problems now is safari on my Mac with no thumbnails, same on a Mac at work too.

**Comment by DanielnetoDotCom** [comment]
strange, I am also using safari and it is working fine.

can you please check your PHP version?

if you can, can you please update to version 8+

**Comment by para2022** [comment]
Yes its 8.0 that ive always used.

**Comment by DanielnetoDotCom** [comment]
I am really not sure 

can you please share the link where the images are no working so I can check from my safari?

**Comment by para2022** [comment]
Hi Daniel I've finally worked this out. I have an old mac and i noticed some users were logged with Macs on my site. I emailed them and some said it was fine just like you with your Mac. One emailed back and said they have a new mac and an old mac and the problem occurred with missing thumbnails through the site (poster images) only on their old mac, the same as me. I have already posted an image of the broken images here, they are black or white depending on theme with question mark through them. It doesn't happen on php7 only 8.

As i said this was working on my Mac on version avideo 11 so its something that was changed at 12 as it was exactly at that point the problem started, and you wouldn't know if you dont have an older mac.

I have attached the email convo. When she refers to them working that was when i had to switch back to php 7.4 but i want to use the 8.0 for obvious reasons.

![Screenshot 2022-09-02 at 23 19 52](https://user-images.githubusercontent.com/107706817/188242381-afe870cc-af7f-49ee-9255-3d6f70244373.png)

**Comment by DanielnetoDotCom** [comment]
Hi

I also use a mac and I have no problem on my side.

On my servers I also use PHP8.1

I suspect you are missing some PHP library, try to use PHP8 and check your logs to try to identify what is missing

**Comment by para2022** [comment]
Hi Daniel I tried 8.1 but that has more issues with not been able to clear the cache and lots of other bugs. The issue exists also on another server so it’s not the server. Both 7.4 and 8.0 use the exact same extensions but 8 has the prob and 7 doesn’t. The server logs don’t report an error. Only affects safari. It’s really odd lol

**Comment by DanielnetoDotCom** [comment]
the only way to try to help you is if you share the logs

https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
