### ISSUE TITLE
Mysql 100% usage

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#6937]
@DanielnetoDotCom 

Still having this issue. Now it says 

![_maint](https://user-images.githubusercontent.com/65451390/181740166-bf89f529-b90b-4954-a1f5-647c687f5bc0.PNG)

I installed and run 'mytop' and the biggest problem is this line

![live_tr](https://user-images.githubusercontent.com/65451390/181740142-2bc1c1db-3df5-4252-84c3-9ef41ec967f0.PNG)

is this query necessary? is this table necessary? it is bringing my site down and making it very inefficient. in the picture below, it does it randomly and visitors come and see the site is down they go away.

![nd](https://user-images.githubusercontent.com/65451390/181740538-025505b2-a8af-4b2a-99da-c302aec06916.PNG)

those big spike are 100% usage during "SELECT * FROM live_transmitions_history WHERE finished..."

How can this be fixed?

**Comment by DanielnetoDotCom** [comment]
maybe your live_transmitions_history table is too big

try to clear that

`Delete from live_transmitions_history where id > 0;`

then restart your server

**Comment by jengajenga** [comment]
@DanielnetoDotCom 

When I try that, i get this error

mysql> DELETE from live_transmitions_history where id > 0;
ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`golivedb`.`live_transmition_history_log`, CONSTRAINT `fk_live_transmition_history_log_live_transmitions_history1` FOREIGN KEY (`live_transmitions_history_id`) REFERENCES `live_transmitions_hi)
mysql>

What other options are available?

**Comment by jengajenga** [comment]
OK, I have succeeded by first setting foreign key checks off.

I have cleared the table 44231 rows.

I'll let you know if it brings more trouble

**Comment by DanielnetoDotCom** [comment]
Also delete all the records from live_transmition_history_log

**Comment by jengajenga** [comment]
Let me do that now.
Thank you Dan

**Comment by jengajenga** [comment]
> Also delete all the records from live_transmition_history_log

It says that table does not exist

**Comment by DanielnetoDotCom** [comment]
it must have this table if you are using the live.

if you do not have it, please make sure you have all the tables here

https://github.com/WWBN/AVideo/blob/master/plugin/Live/install/install.sql

**Comment by jengajenga** [comment]
OK. I'll make the change tonight.
