### ISSUE TITLE
ID of a file( myQl )

### ISSUE THREAD

**Issue by lachainestoplinky** [WWBN/AVideo#6938]
ID d'un fichier( myQl )
Bonjour,
Je vous félicite tous pour tout ce travail !!
pour faciliter le remplacement d'une vidéo ou d'un fichier audio
est-il possible d'ajouter l' ID lié à la base de donnée dans la rubrique " Mes vidéos "

au moment de l'envoi vers l'encodeur , en mode avancé , il est possible de remplacer un fichier en indicant son ID.
Exemple : 1332 .

actuellement, il faut ouvrir la table " vidéos " pour trouver l'ID
cordialement

**Comment by DanielnetoDotCom** [comment]
Hi

please make questions in english

**Comment by lachainestoplinky** [comment]
ID of a file( myQl )
Hello,
I congratulate you all for all this work!!
to make it easier to replace a video or audio file
is it possible to add the ID linked to the database in the "My videos" section

when sending to the encoder, in advanced mode, it is possible to replace a file by indicating its ID.
Example: 1332 .

currently, you have to open the "videos" table to find the ID
Cordially

**Comment by DanielnetoDotCom** [comment]
Did you try this?
![chrome-capture-2022-6-29](https://user-images.githubusercontent.com/18009293/181749025-c7d769f8-a0fd-4948-ab17-efe733ef36c5.gif)

**Comment by lachainestoplinky** [comment]
Yes this is what I am doing.
to know the ID, you have to find it in the database.
if the ID was displayed in my videos it would be easier

**Comment by lachainestoplinky** [comment]
in the "my videos" section, there is the duration of a video
the display of its ID would be useful in the case of a replacement
to avoid searching the database

**Comment by DanielnetoDotCom** [comment]
usually you can see the ID on the video URL

**Comment by lachainestoplinky** [comment]
Thanks, indeed it is.
there is the video id
http://lachainestoplinky.tv/videos/video/1xxx/
1xxx
Cordially
