### ISSUE TITLE
change language

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#6941]
Hello Daniel,
how can i change these texts to another language?

Thank you
Ilias

![text](https://user-images.githubusercontent.com/60543030/182039177-7f88f7a4-d522-4d87-8564-94121e807ae9.jpg)

**Comment by DanielnetoDotCom** [comment]
With this update, you may be able to add those texts to your [locale file](https://github.com/WWBN/AVideo/tree/master/locale)

if you will add, please also send a[ pull request](https://docs.github.com/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request), so you will not lose the translation on future updates
