### ISSUE TITLE
Video response submittion section on video pages

### ISSUE THREAD

**Issue by Broly5551** [WWBN/AVideo#6948]
Hello there!  I run an AVideo instance called Corder, and one of my users told me that he would like to see a video response section on video pages like YouTube used to have in the old days.  I was wondering if creating that kind of plugin for AVideo could be done?

Basically the way this user and I envisioned it is that if you made a video response to a video, there would be some place right below the video player you could submit your video response at on the video page, and then the video response could show up 1) right below the video player, or 2) the submitted video responses could show up as a selectable list on the sidebar of a video page.  

I look forward hearing back from you guys on the feasibility of such a new feature.  Thank you for your time.

**Comment by DanielnetoDotCom** [comment]
Hi

you may need to hire me for that development.

just to make clear I keep the rights to resell or incorporate on the main project, everything I develop.

Regarding the idea, 

do you want to send/upload a video to the encoder?
the video is already encoded and you just want to use it as a response?

**Comment by Broly5551** [comment]
> Hi
> 
> you may need to hire me for that development.
> 
> just to make clear I keep the rights to resell or incorporate on the main project, everything I develop.
> 
> Regarding the idea,
> 
> do you want to send/upload a video to the encoder? the video is already encoded and you just want to use it as a response?

I have no problem with you reselling or incorporating this feature onto the main video project.  In fact, I would encourage you to do either one after you've made the feature.  

The idea behind a video response section on video pages is that you have made a video response to a video on your AVideo instance, your video response is already uploaded to your own channel, and you would just submit the link to your video response into a box on the page of the video that you're responding to.  The thumbnails of the submitted videos would show up in a box right below the video player on the page of the video that you're watching.  

The other idea behind this feature is that someone could be watching a video on your AVideo instance, and if they see a video responses box below the video they just watched that is full of video responses, they would start clicking on the video responses to watch them.  This would in theory expose the user to new Content creators that they might like, and they would be able to see both or all sides of a topic.

**Comment by JoshWho** [comment]
So basically, a way to upload a video in response, and have a way to tag another video that was already uploaded to add a response link to it.

`Video responses were designed to create a way for big-time YouTubers to foster a conversation and increased interaction with their fans. A video response would appear attached to a video, increasing exposure for the responder and demonstrating that a conversation was happening around the posted video.`

**Comment by DanielnetoDotCom** [comment]
This sounds like a good idea

do you have a screenshot how does it look like on youtube?

for a quotation please email me at developer@youphptube.com

**Comment by Broly5551** [comment]
Here is an article that explains how the video response feature worked, complete with screen shots.  

https://www.business2community.com/social-media-articles/how-to-make-a-video-response-on-youtube-0368241

Hope this helps.

**Comment by DanielnetoDotCom** [comment]
Hi, if I understand correctly it will be just like a comment but it will be linked to an existing video, also ir will respect all the comments rules (likes, dislikes, replies, etc)?

**Comment by Broly5551** [comment]
Haven't heard anything regarding a video responses plugin since August 4th.  Has there been any work or research done into creating this plugin?

**Comment by DanielnetoDotCom** [comment]
This is a good idea, but for now this is not on the development roadmap

this may be done in the future but there is no ETA for it. we only have ETA for sponsored features.
