### ISSUE TITLE
YPT CDN

### ISSUE THREAD

**Issue by peter-kangere** [WWBN/AVideo#6953]
I have just enabled the YPT CDN plugin. silly me I did not think to ask before, but does this YPT CDN work on Streaming, or does it only affect file upload/download?

sorry for the silly question but I need to know because I am looking to improve live viewing for my subscribers.

**Comment by peter-kangere** [comment]
I activated it but now the website is for the lack of a better word, looks corrupt, html code averywhere, not presentable. what can i do? what did i miss?

**Comment by DanielnetoDotCom** [comment]
Just tested your site and it seems to be fine from here

**Comment by JoshWho** [comment]
> I activated it but now the website is for the lack of a better word, looks corrupt, html code averywhere, not presentable. what can i do? what did i miss?

Clear your browser cache and cookies
