### ISSUE TITLE
Encoder Failure after update to v 12

### ISSUE THREAD

**Issue by ahmedxda** [WWBN/AVideo#6955]
after update to v 12 the private encoder doesn't work completely..

when I try to login, it always show this 
I use the public encoder which sometimes stuck or needs update..
![20220802_151255](https://user-images.githubusercontent.com/104592418/182384175-92172401-c5f2-4af4-a17b-e511da42f757.jpg)

**Comment by JoshWho** [comment]
update your encoder it too has updates

**Comment by ahmedxda** [comment]
@JoshWho 
would you please provide the encoder update link

**Comment by DanielnetoDotCom** [comment]
> @JoshWho would you please provide the encoder update link

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by ahmedxda** [comment]
I do update my website almost everyday .. I thought there's a special update code for the encoder..
my encoder still not work

**Comment by DanielnetoDotCom** [comment]
what is your encoder URL?

Make sure you update also the encoder, NOT just the streamer

**Comment by ahmedxda** [comment]
@DanielnetoDotCom 
URL:
masperro.com/upload

By the way would you please update the "general encoder" ... it doesn't work with importing from Facebook and also a Russian social network called OK ...I used to upload from this Russian website but now the videos I import from this website comes broken

**Comment by DanielnetoDotCom** [comment]
Your encoder uses https://www.masperro.com/ which is redirecting to https://masperro.com/ and it is causing a lot of errors 

![image](https://user-images.githubusercontent.com/18009293/182946539-c9f85b2b-d06b-4d0d-89d1-dee175ffba21.png)

![image](https://user-images.githubusercontent.com/18009293/182946287-0773c7fb-3bd1-4e9e-a684-010b33152fd1.png)

I guess the easiest solution is to drop the encoder database and delete the videos folder and run the installation again.

or you can manually update the streamers sites on your database

**Comment by ahmedxda** [comment]
would you please provide me a guide if possible

**Comment by DanielnetoDotCom** [comment]
guide? 

Sorry I cannot teach you MySQL or handle your server, you may google for that

**Comment by ahmedxda** [comment]
Ok Dan thanks..
please don't forget to update the General Encoder because we use it too much..
also there's some video being importing and stuck since the morning until now... please have a look there 🌷

**Comment by DanielnetoDotCom** [comment]
You should check this

https://network.avideo.com/

we have 4 encoders now

**Comment by ahmedxda** [comment]
Thanks Dan for the help... but would you please remove these annoying hints!☺
![Screenshot_20220805-175425_Opera Mini](https://user-images.githubusercontent.com/104592418/183115498-b2f1f99a-8093-4a55-acd1-71080fad1366.jpg)

**Comment by aliceglitch** [comment]
Hi, what is the user and password for this page?

![photo_2022-08-07_12-30-06](https://user-images.githubusercontent.com/72448881/183281355-d3a8cc1d-6f73-42de-8c44-db33ba1bd4e1.jpg)

**Comment by DanielnetoDotCom** [comment]
that is the sam as you use for your encoders

**Comment by aliceglitch** [comment]
Here? Here we have 4 types of encoders? Well, which of these 4 types of the encoder has the option of downloading or uploading, such as educational videos? Is it possible for you to tell me from the screen how I can find the option to download or upload videos in bulk from YouTube?

![photo_2022-08-09_11-50-20](https://user-images.githubusercontent.com/72448881/183590288-247079e1-9b5c-4fbd-94a7-e126aa1d7531.jpg)
![photo_2022-08-06_12-53-34](https://user-images.githubusercontent.com/72448881/183590383-b9a3d00b-6c13-4fae-b282-c95f9c0b6c2d.jpg)
![photo_2022-08-06_12-55-47](https://user-images.githubusercontent.com/72448881/183590535-43cc409d-6e95-47d3-9063-cd625cf07f1f.jpg)

**Comment by DanielnetoDotCom** [comment]
Try this

https://github.com/WWBN/AVideo-Encoder/wiki/Import-Channel-and-Playlist

FYI, this feature is disabled on public encoders

**Comment by aliceglitch** [comment]
That is, to install Encoder in the terminal, should I type the following statement?

sudo git clone https://github.com/WWBN/AVideo-Encoder/wiki/Import-Channel-and-Playlist

**Comment by aliceglitch** [comment]
> Try this
> 
> https://github.com/WWBN/AVideo-Encoder/wiki/Import-Channel-and-Playlist
> 
> FYI, this feature is disabled on public encoders

Hello, which one of these encoders should I install in order to be able to upload a video from YouTube on the host? (A or B or C? Or all three encoders?)
thank you
![ed](https://user-images.githubusercontent.com/72448881/189339924-7e1a0412-a284-4b66-b27d-0eb92adde5f8.png)

**Comment by aliceglitch** [comment]
> Try this
> 
> https://github.com/WWBN/AVideo-Encoder/wiki/Import-Channel-and-Playlist
> 
> FYI, this feature is disabled on public encoders

You have provided an encoder that has this capability (to be able to upload a video from YouTube on the host) in the training video, what is the difference between the encoder in the training video and this link that you sent?
thank you
![titled](https://user-images.githubusercontent.com/72448881/189345035-247f9ab1-fbb1-43f9-a84e-cd102dedefe7.png)

**Comment by DanielnetoDotCom** [comment]
the git clone URL should not make any difference as long as the project was moved form danielnetodotcom to wwbn

GitHub can redirect it in case you use any of those URLs

**Comment by aliceglitch** [comment]
> the git clone URL should not make any difference as long as the project was moved form danielnetodotcom to wwbn
> 
> GitHub can redirect it in case you use any of those URLs

Hello, I installed the avideo with the instructions in figure A, and it was executed on the lamp and local host, and then I entered the instructions in figure B to install the encoder, but whatever I type in the browser, why doesn't the encoder run? In order for the encoder to run in the browser, I typed the "localhost/YouPHPTube-Encoder/install/index.php" in the browser (according to Figure C), but why the encoder was not run? What should be written in the browser so that the encoder is executed like avideo (according to Figure D)?
Thank you.

![AAAAA](https://user-images.githubusercontent.com/72448881/192326485-5f773697-ece1-4eb7-ba5f-2a98f6820331.png)
![BBBBB](https://user-images.githubusercontent.com/72448881/192327063-6cc35aeb-fafb-4a92-b015-f85a6d8da283.png)
![cccccc](https://user-images.githubusercontent.com/72448881/192329371-91535897-3a50-4d10-b0f2-2f5cbb09c3cb.png)
![DDDDD](https://user-images.githubusercontent.com/72448881/192332235-1f713220-7262-4369-bf1e-82877e3e8675.png)
![ENCODER](https://user-images.githubusercontent.com/72448881/192332432-aeab9d4e-6294-4f8b-bbd4-335ba82eceeb.jpg)
![ENCODERFOLDER](https://user-images.githubusercontent.com/72448881/192332517-be8c6149-9414-4a08-88f8-18c642f2ba08.jpg)

**Comment by DanielnetoDotCom** [comment]
Did you use git clone?

I have no idea what you are missing.

**Comment by aliceglitch** [comment]
> Did you use git clone?
> 
> I have no idea what you are missing.

For both AVideo and Encoder, I have exactly the same ones that you sent me the link for, and I typed them in the terminal and nothing else.

**Comment by aliceglitch** [comment]
Hi, I want to install Encoder so that it has the ability to upload videos from YouTube and other sites, so I have to type Command B instead of command A when installing AVideo? Besides, after installing the AVideo, I will run all the "How to install LAMP, FFMPEG and Git on a fresh Ubuntu 16.x For AVideo Encoder" commands in the terminal to install the encoder, Are these steps correct for installing AVideo and encoder with the ability to upload videos from YouTube and other sites?
Thank you
![AAA](https://user-images.githubusercontent.com/72448881/196671780-590316e5-dfc2-44dd-bd03-56b34a84c30b.png)
![BBB](https://user-images.githubusercontent.com/72448881/196671888-e516e3c8-3e9d-4931-aea9-39c05ca3bddc.png)
![CCC](https://user-images.githubusercontent.com/72448881/196672069-65090f6e-b718-4c3d-a249-5bd5c42e0f7d.png)

**Comment by aliceglitch** [comment]
Hello, to install Encoder with the instructions in figure A, there is no command to create a database, so why are the database specifications included in the training video (according to the figure) when Encoder is installed? Where did this database come from?
Thank you.
![bbbbbb](https://user-images.githubusercontent.com/72448881/198869619-e5dd7a36-88b0-4d9f-8513-411eea8b9577.png)
![Encoder](https://user-images.githubusercontent.com/72448881/198869689-2f270b8f-c63b-4f80-b5ec-78c94ce2973b.jpg)


فاش
فا

**Comment by DanielnetoDotCom** [comment]
try to google and find how to create a user on the mysql

**Comment by aliceglitch** [comment]
> try to google and find how to create a user on the mysql

I know the command to create a database from figure ("https://www.inmotionhosting.com/support/server/databases/create-a-mysql-database/" site), so it is necessary to create a database for Encoder, and the command to create a database is not among the commands to install Encoder (Figure B) and we have to create it ourselves.
![database](https://user-images.githubusercontent.com/72448881/199882164-4a9d2411-4634-40e7-af56-91a30e9dfe8d.jpg)
![bbbbbb](https://user-images.githubusercontent.com/72448881/199882266-b5fe7e96-44ca-44b9-bf31-8b5d6e697bc1.png)

**Comment by DanielnetoDotCom** [comment]
when you create a user for the encoder give that user create database and tables privileges , the install script will need to create a new database and all tables

**Comment by aliceglitch** [comment]
Hello, I want to install an encoder that has the ability to upload videos from YouTube, but the encoder is installed twice, one encoder is installed along with the AVideo installation (Figure A), which is a public encoder, and one encoder is installed from Figure B. Do I have to follow the instructions(Both A and B) exactly and copy&paste and install both encoders? Or, when installing AVideo, instead of command A, should I type command B and install only the encoder of form B, which has the ability to upload videos from YouTube? And don't install Encoder A anymore?
Thank you.
![A](https://user-images.githubusercontent.com/72448881/201056678-80d904fe-bc85-4eb7-933c-61d02c704f1c.png)
![b](https://user-images.githubusercontent.com/72448881/201056806-fe01538e-2dbe-4e2e-9157-c18c5ea3ae4a.jpg)

**Comment by DanielnetoDotCom** [comment]
Correct, if you ran the streamer installation, you already probably does have the Encoder as well

**Comment by aliceglitch** [comment]
> Correct, if you ran the streamer installation, you already probably does have the Encoder as well

Hi, can I use the attached instructions to install the AVideo?
Does Ubuntu 22 not have bugs?
Thank you
![photo_2023-03-20_15-04-07](https://user-images.githubusercontent.com/72448881/226328207-11bececc-c9d4-4bc4-b19b-a3c5713fa0f8.jpg)


اه

**Comment by aliceglitch** [comment]
> 
Hi, can I run these commands on Ubuntu 20? 
Thank you
![photo_2023-03-20_15-04-07](https://user-images.githubusercontent.com/72448881/227877702-8bbcb721-4f60-4a6c-bf8b-b55e0d5b5a7f.jpg)

**Comment by aliceglitch** [comment]
> Use this https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x-for-AVideo-Platform-version-11.x-or-newer


Ok, I am using this link that you just sent, but why don't you have an opinion about this shot and Ubuntu 22? And why don't you recommend it for installation when Ubuntu 22 is a newer version than Ubuntu 20?
![photo_2023-03-20_15-04-07](https://user-images.githubusercontent.com/72448881/228200781-4cf06d1c-25e2-4373-aad9-ef3f6fc9757d.jpg)

**Comment by DanielnetoDotCom** [comment]
I do recommend ubuntu 22, where did you see I do not recommend it?

**Comment by aliceglitch** [comment]
> Use this https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x-for-AVideo-Platform-version-11.x-or-newer

Why did you not recommend Ubuntu 22 here?

**Comment by DanielnetoDotCom** [comment]
It is simple If you have Ubuntu 22 use Ubuntu 22 commands if you have Ubuntu 20 use Ubuntu 20 commands. 

any other thing different makes it at your own risk.

**Comment by aliceglitch** [comment]
Hi, I am installing Encoder first, and after installing Encoder, I want to install AVideo. Can I fill these fields later or do they have to be filled before pressing the install button?
Thank you
![image](https://user-images.githubusercontent.com/72448881/232042054-0840f38e-2a72-4d93-bb68-cbe53f92fe4b.png)

**Comment by DanielnetoDotCom** [comment]
you need an streamer before install the encoder

**Comment by aliceglitch** [comment]
> 

Is this a streamer?
![image](https://user-images.githubusercontent.com/72448881/232064280-d0554fae-a434-4a75-87f1-d42dbac5faf7.png)

**Comment by DanielnetoDotCom** [comment]
this will install both

**Comment by aliceglitch** [comment]
> this will install both

I installed this once on VMWare, but the encoder that installed it was a public encoder, and why didn't it install the encoder with the ability to upload videos from YouTube?

**Comment by aliceglitch** [comment]
> Here? Here we have 4 types of encoders? Well, which of these 4 types of the encoder has the option of downloading or uploading, such as educational videos? Is it possible for you to tell me from the screen how I can find the option to download or upload videos in bulk from YouTube?
> 
> ![photo_2022-08-09_11-50-20](https://user-images.githubusercontent.com/72448881/183590288-247079e1-9b5c-4fbd-94a7-e126aa1d7531.jpg) ![photo_2022-08-06_12-53-34](https://user-images.githubusercontent.com/72448881/183590383-b9a3d00b-6c13-4fae-b282-c95f9c0b6c2d.jpg) ![photo_2022-08-06_12-55-47](https://user-images.githubusercontent.com/72448881/183590535-43cc409d-6e95-47d3-9063-cd625cf07f1f.jpg)

I mean this encoder that I installed with this link, which is a public encoder

https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x-for-AVideo-Platform-version-11.x-or-newer

**Comment by DanielnetoDotCom** [comment]
this is a very old encoder screenshot. 

anyway, to install an encoder now you need a streamer, an encoder without a streamer is useless

**Comment by DanielnetoDotCom** [comment]
Start all over and only use this "https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-22.x-for-AVideo-Platform-version-11.x-or-newer"

**Comment by DanielnetoDotCom** [comment]
your server is not reachable. 

it will never work with the public encoder

![image](https://github.com/WWBN/AVideo/assets/18009293/39ec01b8-4dc7-48d0-84a2-2a832f41264b)

**Comment by aliceglitch** [comment]
> 

You entered the server IP incorrectly. My server IP is 5.57.38.237. You entered 5.57.38.137 by mistake.

**Comment by aliceglitch** [comment]
Meanwhile, I want to install an encoder with the ability to upload videos from YouTube and other sites.
Does Public Encoder have this feature? If not, please guide me on how to install an encoder with the ability to upload videos from other sites.

**Comment by DanielnetoDotCom** [comment]
you are right, the IP was incorrect

yes, the public does have the same features. 

if there is any error, check your streamer logs for some clue.

**Comment by aliceglitch** [comment]
> you are right, the IP was incorrect
> 
> yes, the public does have the same features.
> 
> if there is any error, check your streamer logs for some clue.
Hi Is there any guide to install and configure the encoder?
