### ISSUE TITLE
Live isn’t working 

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6957]
When I click on the link to live it says local host not available.
How do I correct this?
![6C00E4F8-62A8-4A32-916B-D657BD1FEDB8](https://user-images.githubusercontent.com/58601786/182518131-0b62f9b8-9269-4b50-ba33-1c465d6fd11b.jpeg)
![22F1D443-166E-41FB-8DA2-5C7DD3D6FDB0](https://user-images.githubusercontent.com/58601786/182518137-a5881375-02b2-464c-b4b1-595bc6eb8aa2.png)

**Comment by DanielnetoDotCom** [comment]
Hi

I just sent you updates , can you please try again?

**Comment by barrunning** [comment]
That is better but know all you get is the spinning wheel.

**Comment by DanielnetoDotCom** [comment]
Can you please screenshot?

**Comment by barrunning** [comment]
Live stream works from a meeting. It doesn’t work from OBS nor from the computer, nor from the mobile app unless it is from a meeting. 
I get an notification that a livestream is happening but the spinning icon is all that you see.

**Comment by DanielnetoDotCom** [comment]
It makes no sense because both uses the same url and credentials 

please clear your cache and double check you got the url and credentials correctly

**Comment by DanielnetoDotCom** [comment]
I just realized 

it may be your output resolution, make sure it is 720p maybe with a higher resolution you do not have enough bandwidth to transmit

**Comment by barrunning** [comment]
Ok. Looks like we are back in business. 
Thank you. 
Never had that issue before. No idea why it is an issue now..

**Comment by JoshWho** [comment]
> I just realized
> 
> it may be your output resolution, make sure it is 720p maybe with a higher resolution you do not have enough bandwidth to transmit

Is there anyway to force users to use 720p for stream? I haven't found anything yet.

**Comment by barrunning** [comment]
I had to change OBS to 720 output.

**Comment by DanielnetoDotCom** [comment]
> > I just realized
> > it may be your output resolution, make sure it is 720p maybe with a higher resolution you do not have enough bandwidth to transmit
> 
> Is there anyway to force users to use 720p for stream? I haven't found anything yet.

only if you use the [adaptive mode](https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream), but this consumes a lot more CPU, you will convert their videos
