### ISSUE TITLE
Need a way for Admin to be able to add the JoshWho Analytic code

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6958]
I want to be able to add it to the channel when users need help but I have no way to do that. There is no admin login to the user account to make changes.

![6aa788ba-93e0-4d4b-9c29-347a346e21e6](https://user-images.githubusercontent.com/39392449/182762531-59cb5ce7-e212-4015-8649-3dcbae519284.png)
![31044544-d2082dc67a50c0012365e59e067d4e62](https://user-images.githubusercontent.com/39392449/182762719-cddaff97-491a-455d-a6b9-2af48c743599.png)

**Comment by DanielnetoDotCom** [comment]
currently there is no way to do that, only possible with the client credentials

**Comment by JoshWho** [comment]
> currently there is no way to do that, only possible with the client credentials

That makes the user security no so good if we have to send passwords back and forth. Most users don't trust doing that.

**Comment by JoshWho** [comment]
What if there was a way to make it to when I enable the JoshWho Analytics Plugin it will use the Google analytics box for the code? That way I can paste in there code from the Admin users page

**Comment by DanielnetoDotCom** [comment]
Probably the best way would be to let the admin switch to any user and control all his content.

I will develop a feature like that in the future

**Comment by JoshWho** [comment]
Sounds good. Looking forward to that. Thank you @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Checkout this update
![chrome-capture-2022-7-5](https://user-images.githubusercontent.com/18009293/183104709-3c716816-59d2-4c5c-99db-5cc1e99da634.gif)

**Comment by JoshWho** [comment]
Thank you that is awesome!!!!!!!
