### ISSUE TITLE
What would cause this

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6962]
What would cause long load times. This is occurring on the computer and on the app.

![606D12D2-72C8-4C90-896C-C5F85BE96F3F](https://user-images.githubusercontent.com/58601786/182909195-0e1f3956-509a-4909-89df-306e2a3b51e9.png)

then after about 5 minutes
This
![635640FE-B3CF-4142-856D-42DF57B8CA71](https://user-images.githubusercontent.com/58601786/182909492-9d9c0d70-70a0-4b8d-8f84-4e1325e981e6.png)

**Comment by barrunning** [comment]
Also with videos

**Comment by barrunning** [comment]
Also the above videos where recorded from a livestream. Videos uploaded and encoded play just fine.

**Comment by barrunning** [comment]
The format of the video says HLS and not mp4 like the videos uploaded and encoded.

**Comment by barrunning** [comment]
Ok I figured out the video portion. The HLS works great when restreamed. 
is there a way for those links to be sent out when someone signs up to watch?

**Comment by DanielnetoDotCom** [comment]
Hi, I am confused, what is this issue about?

The question regarding HLS is not clear to me. please open a new issue with more details about this question.
