### ISSUE TITLE
Where can you purchase Ppv?

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6963]
I can set up the livestream and the restream as a Ppv. Question is where do you purchase this? It shows up no where on the site that say purchase Ppv here.
![5BB81E74-FC2B-478E-B780-4F36EBED3052](https://user-images.githubusercontent.com/58601786/182922737-98f9e147-daff-4b16-b98d-82084ba41d7c.jpeg)

**Comment by DanielnetoDotCom** [comment]
if you set up a live PPV you may see a notification on the bell.

then when your user clicks on that notification he will see the PPV plan purchase option.


you can see samples on [the demo site](https://demo.avideo.com/)

![image](https://user-images.githubusercontent.com/18009293/182924500-1b998cd0-fd49-4075-a3fb-1c28d2ec60ca.png)

**Comment by barrunning** [comment]
I get nothing like that.
As admin it just lets me schedule a Ppv. As non admin you click on the bell and nothing happens.

**Comment by DanielnetoDotCom** [comment]
Make sure you schedule the plan, otherwise it will count you are live streaming now
![chrome-capture-2022-7-4](https://user-images.githubusercontent.com/18009293/182929858-9c609632-7b90-43d4-8665-bb9ee02e563d.gif)

**Comment by barrunning** [comment]
Ok. So how does a user access a Ppv video not scheduled?

**Comment by DanielnetoDotCom** [comment]
if a user tries to watch an active live, and there is a PPV set for that time it will request access to the PPV

https://github.com/WWBN/AVideo/wiki/PayPerView-Live-Plugin#once-a-user-tries-to-play-the-live-he-will-be-prompt-for-choosing-the-plan-and-a-payment
