### ISSUE TITLE
Hls

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6965]
How does a person view the HLS formatted video without having to be given the link to a restream?
![56674FD6-5B11-4E4A-A7CC-FDD932209A32](https://user-images.githubusercontent.com/58601786/182932303-ac85c19e-3def-4708-9948-70c74566975b.jpeg)

**Comment by barrunning** [comment]
![CDACF6EA-3FDA-457B-B861-9750AE389CC9](https://user-images.githubusercontent.com/58601786/182932453-41e7d788-99e5-4f96-a174-244b572568cb.png)
![911D3193-A390-4FFD-AA87-14B966193D64](https://user-images.githubusercontent.com/58601786/182932459-20c9df6d-d71a-43cc-bb77-f62e3e5cacfd.png)

**Comment by DanielnetoDotCom** [comment]
I guess the correct word may not be restream. the restream feature is still under development and I guess it means something else.

maybe it is something about your live stream, but sorry, but I am not understanding your questions.

what exactly happens?

**Comment by barrunning** [comment]
Those livestreams are recorded. They don’t play in the HLS format unless you use the link from the restream, or you replay the live stream..
How does one access the recorded livestream?

**Comment by DanielnetoDotCom** [comment]
I see now, sorry the problem is still the old domain issue. I am working on a fix now.

**Comment by DanielnetoDotCom** [comment]
It should work now, please try again. 

I fixed both sites issue

**Comment by barrunning** [comment]
Outstanding! The HLS format plays now.
Thanks you
