### ISSUE TITLE
Pay per view link

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6966]
Nothing comes up under the pay per view link.

https://user-images.githubusercontent.com/58601786/182959916-197d1727-f2ac-4e2b-b411-2b6517c37770.MOV

https://user-images.githubusercontent.com/58601786/182960494-562356a9-7b3a-4ad5-8c37-301dab64d9fb.MOV

**Comment by DanielnetoDotCom** [comment]
All the lives listed on your schedule were in the past. to have them listed with a countdown you need to schedule it for the future date.
