### ISSUE TITLE
Live Streaming

### ISSUE THREAD

**Issue by stevespaw** [WWBN/AVideo#6967]
From the videos it seemed that this would just work. But I cannot get live streaming to work. The only info I have found is:
[https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server](https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server)
It seems that this is a setup for a separate server, not just running on the Streamer. Is this true?
Should the Live plugin just work, by turning it on? I don't think so without the nginx install. ???

I tried the above wiki and had it connecting to vMix, but the stream will not appear in AVideo.
What am I missing? 

Do livestreams only show in the bell or can they be like VOD clips in a channel?

I appreciate any help.

I am also interested in the ovenmedia connection as I am looking for SRT inputs into a system like this.
I cannot find much advanced information on these things, is there a good resource or is it just to buy time from Daniel in some way.

I would like to know as much as I can about this software and its future.
Thanks,
Steve

**Comment by DanielnetoDotCom** [comment]
Hi, the thing is ...

Install the Apache webserver for the streamer and encoder
Install Nginx webserver/live server 

Both web servers Apache/Nginx can coexist on the same server just make sure they have different ports

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server#making-it-clear

**Comment by stevespaw** [comment]
Thanks but something is still not right. The wiki says to change the port to 444. Should this be 8443?  ( have SSL pem setup.)
I have tried 8443 also and no go. I want to buy the save recorded plugin, but have to make this work first.
![image](https://user-images.githubusercontent.com/11045430/183101787-79bdf9bc-b424-46d0-a09e-5cef72bafa15.png)
also 444 is on this image. (I had to add this line - is it needed?)
![image](https://user-images.githubusercontent.com/11045430/183102350-c36322c6-e8b6-4d82-9c2b-7d4553298906.png)

**Comment by stevespaw** [comment]
I have even tried streaming to the demo site:  
https://demo.avideo.com/plugin/Live/
This also does not work...
I know I am missing something simple.

**Comment by DanielnetoDotCom** [comment]
The demo site is blocking external live stream connections.

**Comment by Lordblanca** [comment]
You may want to check you firewall settings. Make sure that the proper ports are open. These are the ports that I have open. 
TCP: 22, 80, 443, 444, 1935, 2053, 8080, 8443 | UDP: 2053
