### ISSUE TITLE
Categories repeating the live Streams again 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6968]
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/39392449/183073615-eab7f1d9-bfec-4862-b19c-184cf9e82215.gif)

**Comment by DanielnetoDotCom** [comment]
Which one exactly is repeating?

**Comment by JoshWho** [comment]
All categories do this

**Comment by JoshWho** [comment]
It seems like it does it when it loads a new row

**Comment by DanielnetoDotCom** [comment]
I could not find any repeated video. what video can you see repeating?

![image](https://user-images.githubusercontent.com/18009293/184965163-b8ec859c-61e0-49b4-ae68-9507a55a9b66.png)

**Comment by JoshWho** [comment]
> I have noticed that happen to another user I add multiple videos at the same time.
> 
> because the sort is based on the creation time, and all the videos have the same timestamp, looks like the script gets confused.
> 
> did you bulk add those videos?

No this were individuals using the lIve links thing

**Comment by JoshWho** [comment]
![download (17)](https://user-images.githubusercontent.com/39392449/184972719-9154485b-22db-4604-9524-cc8b2e9c68a9.jpg)

**Comment by DanielnetoDotCom** [comment]
Check the links, they are different videos. you are not loading them multiple times. but you probably added them into your videos library multiple times

![image](https://user-images.githubusercontent.com/18009293/184975952-fd9ad502-b5cf-4917-b1fd-908bcee8d55d.png)

![image](https://user-images.githubusercontent.com/18009293/184976027-1e7ece56-844d-4eca-a5b0-441d85d203a6.png)

![image](https://user-images.githubusercontent.com/18009293/184976119-afd84400-1c15-4b12-8441-449c6a1dddc1.png)

![image](https://user-images.githubusercontent.com/18009293/184976199-95d9100f-9c02-4777-9344-8ccc332e2683.png)

![image](https://user-images.githubusercontent.com/18009293/184976290-76e2a5a6-dc92-4ca2-8105-969af9a2b4fc.png)

**Comment by JoshWho** [comment]
that doesn't even make sense, they are all Live Links

**Comment by DanielnetoDotCom** [comment]
You are right, now I just sent an update to fix the bad links problem

I am checking now the duplicated problem (I have a better idea now)

**Comment by DanielnetoDotCom** [comment]
that update may fix the issue, thanks for finding it

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom Almost fixed. Looks like there is just 1 repeat at the top and the rest looks fine.

![News-·-JoshWho-TV (1)](https://user-images.githubusercontent.com/39392449/184986386-b76a1635-9181-425a-988b-51be4135a46b.jpg)

**Comment by DanielnetoDotCom** [comment]
which one exactly?

**Comment by JoshWho** [comment]
News still

**Comment by JoshWho** [comment]
![e42cb16a-e478-4fcb-a428-bb5b21966cdc](https://user-images.githubusercontent.com/39392449/184990862-5808179d-008d-4902-abbd-fc73eaa7dbfc.jpg)

**Comment by DanielnetoDotCom** [comment]
I am not sure how this is happening. but please try this update

**Comment by JoshWho** [comment]
Nope still the same. I cleared all caches too hoping that might have been it but still see the double live row for some reason at the top

**Comment by DanielnetoDotCom** [comment]
what about now?

**Comment by JoshWho** [comment]
That looks like it did the trick thank you @DanielnetoDotCom
