### ISSUE TITLE
Another Easier way to Mark videos as suggested for Admins and mods.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6980]
Make the suggestion Star available on the video player itself that way we can just click it on the front end instead of the video manager.

![16bd3539-caf8-47b8-9c88-6aa243028e0f](https://user-images.githubusercontent.com/39392449/183505352-b13ceb17-0608-4350-951d-c9507c0acf16.png)
![a65b67a2-b831-4bfa-8928-854e2714fa02](https://user-images.githubusercontent.com/39392449/183505369-719db3c7-3fcb-412f-9d3a-9cdfd9c46741.png)

**Comment by JoshWho** [comment]
Or maybe in the advance editor 

![af1c032a-bb76-4b20-9e69-8beef67e5fb0](https://user-images.githubusercontent.com/39392449/183505891-2e677315-842d-4a3f-9925-ad600b750a63.png)


It is difficult sometimes to do it from the video manager especially if the video is not searchable

**Comment by DanielnetoDotCom** [comment]
Suggested videos button added

![chrome-capture-2022-7-11](https://user-images.githubusercontent.com/18009293/184179745-bfc5e9cc-0c13-40f5-99e3-125181d97610.gif)

**Comment by JoshWho** [comment]
Thank you
