### ISSUE TITLE
Why the encoder that I installed is different from the educational video encoder? And it doesn't have the download or upload option?

### ISSUE THREAD

**Issue by aliceglitch** [WWBN/AVideo#6982]
Hello, I installed AVideo with VMWare and Ubuntu 22.04 on the LAMP, and then I installed Encoder, but why is there no place on the screen to upload a video in bulk from YouTube? How should I upload a video from YouTube in bulk, corresponding to a training video on the screen? Is the encoder in the video tutorial different from the one I installed? Because you said in one place that there are 4 types of encoders (according to the screen), am I using an encoder that is not for bulk video upload? If this is the case, introduce me to the encoder that is used to upload videos in bulk so that I can install it. Meanwhile, I installed AVideo, Encoder, Lamp, and all the steps from two links https://www.linuxbabe.com/ubuntu/install-avideo-youphptube-ubuntu-20-04-server and https://www.linuxbabe.com/ubuntu/install-lamp-stack-ubuntu-20-04-server-desktop.
Thanks

![photo_2022-08-06_12-53-34](https://user-images.githubusercontent.com/72448881/183564575-7f4236b0-fe87-410b-a4f3-e78136242ef6.jpg)
![photo_2022-08-06_12-55-47](https://user-images.githubusercontent.com/72448881/183564657-a596fdcb-85c2-4268-9096-526a33526157.jpg)
![photo_2022-08-08_15-49-38](https://user-images.githubusercontent.com/72448881/183564843-cfb3b790-1f40-4195-b506-e93d5ec662bf.jpg)

**Comment by JoshWho** [comment]
A lot has changed since then. Same functions and some new ones now. Better GUI for users to learn fast.

**Comment by aliceglitch** [comment]
> A lot has changed since then. Same functions and some new ones now. Better GUI for users to learn fast.

So, this video is for previous versions? So, how can I upload videos from YouTube in bulk in the encoder version that I installed? Can you tell me how to upload a video from YouTube in the screenshot I sent?

**Comment by JoshWho** [comment]
If I remember correctly you should be able to paste a public Playlist from youtube and it will grab it all in that. I do not think the channel grab is a thing anymore without it being file by file.
