### ISSUE TITLE
Email notifications are not a good way to attract viewers.

### ISSUE THREAD

**Issue by GarethBagley** [WWBN/AVideo#6983]
Hi everybody

Is there any other way of notifications without using e-mails?
My users are unsubscribing because of the amount of mail they are receiving. I have only notifications enabled for live streams but anyway.
Any ideas?

**Comment by JoshWho** [comment]
If people are unsubing because they get notified about you live streaming, I do not think it is the notifications making them unsub. 

Is it sending them constant emails? Why would they get more than 1 notification from when you go live, or do you go live multiple times a day?

**Comment by JoshWho** [comment]
You have to remember, the main problem with big tech is people do not get notified and now you are saying that is the problem?

**Comment by JoshWho** [comment]
There should be some kind of daily limit for email notifications but trying to figure what the amount is is the problem.

**Comment by GarethBagley** [comment]
Yes the e-mails are the problem. 
Trends have changed, especially here in Sweden, and i suspect in most places.
Mail boxes are not what they used to be. 
People don't like endless mails that they have to delete. And it doesn't really matter who they are from. It's just not good logistics.

My questions remains. Is there any other way of notifying without emails? I'm thinking like app notifications or similar?
Mails are so 1985.. :)

**Comment by JoshWho** [comment]
You have control of that. Just either Turn off Emails in the Notification Plugin
![download (15)](https://user-images.githubusercontent.com/39392449/183844439-b158ee7b-af64-43b6-abb1-eaa1f0073f5a.png)

You can also enable Push notifications using OneSignal or disable individual things.

![download (16)](https://user-images.githubusercontent.com/39392449/183844813-f38328a4-3408-47d4-9e5b-f6cd2bdd6f30.png)

**Comment by JoshWho** [comment]
Just saying most my users rely on those, thats how they know when what they r subscribed to goes live.

**Comment by JoshWho** [comment]
The user is also in full control of those emails they can just untick the bell and it stops sending them the mails. 

You are thinking about this all backwards.

**Comment by GarethBagley** [comment]
I'm not thinking about this backwards. I am asking a question. 
How does the push work? Is this still email based?

**Comment by GarethBagley** [comment]
Thanks Josh. So if i understand you right, there's no emails involved?

**Comment by JoshWho** [comment]
Correct

**Comment by GarethBagley** [comment]
![Skärmavbild 2022-08-10 kl  10 05 50](https://user-images.githubusercontent.com/31846556/183849070-6a4e264c-7368-430e-ad16-c3844bfb10d9.png)

Like this?

**Comment by JoshWho** [comment]
No did you create a Onesignal account? You need to set one up and fill in the api info in the notifications plugin.

You will see a animated bell on the bottom right or left cant remember.

**Comment by JoshWho** [comment]
GOt to warn you, the Push notifications I do not think works for each channel so ever upload will notify to all nomatter who uploads it.
