### ISSUE TITLE
YPT Socket server - where to set SSL certificate path?

### ISSUE THREAD

**Issue by cisfreak** [WWBN/AVideo#6988]
When starting YPT socket server I get the error:
SSL ERROR, we could not access the KEY file /etc/letsencrypt/live/www.domain.com/privkey.pem, try to run this command as root or use sudo
The SSL certificate is saved to /etc/letsencrypt/live/domain.com/privkey.pem
The correct path is set in AVideo YPTSocket plugin settings, but I don't see anywhere to change the SSL certificate path when starting the server.

**Comment by DanielnetoDotCom** [comment]
Hi

if you are using SSL on your site the SSL keys are required for yous socket as well. 

you have to update the plugin configuration with the correct SSL path

**Comment by cisfreak** [comment]
Hi Daniel,

Where do I change these parameters?
Parameter [local_cert]: /etc/letsencrypt/live/www.domain.com/fullchain.pem 
Parameter [local_pk]: /etc/letsencrypt/live/www.domain.com/privkey.pem 

They are correctly set in the YPTSocket plugin parameter page:
/etc/letsencrypt/live/domain.com/fullchain.pem
/etc/letsencrypt/live/domain.com/privkey.pem

When I launch the server with "sudo php /var/www/html/AVideo/plugin/YPTSocket/server.php" it uses the wrong directory with the "/www.domain.com/" instead of "/domain.com/"

**Comment by DanielnetoDotCom** [comment]
Edit it on the plugin 
![image](https://user-images.githubusercontent.com/18009293/184180261-432925b3-8d1a-49ca-8441-0089cb80a50e.png)
