### ISSUE TITLE
Question: can we generate a RTMP stream from a playlist?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#6991]
**Describe the question**

Just that. Can we start up a program playing and it generates a RTMP stream from it?

**Comment by DanielnetoDotCom** [comment]
we have an experimental feature, it is not working 100% yet, but we will have it in the future

**Comment by sipero** [comment]
If you need someone to help with testing please do let me know

**Comment by walt93** [comment]
Thanks Daniel, looking forward to it when you ship it!
