### ISSUE TITLE
Cannot Answer a Jitsi Call

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6992]
I am, trying to call a member in the site, I can see him trying to call me but I cannot answer or even hangup. Those buttons don't work as before.

I have done a full update today to the new version including all plugins. Made a cache clean, but still nothing:
![Screen Shot 5782-12-15 at 16 34 40](https://user-images.githubusercontent.com/58882903/184365543-53d8593b-7d60-40ef-9551-02024a6e71fb.jpg)
![Screen Shot 5782-12-15 at 16 32 35](https://user-images.githubusercontent.com/58882903/184365560-4d0dde16-966e-45d8-87ac-5f0f895a3166.jpg)

**Comment by DanielnetoDotCom** [comment]
Duplicated, working on it now https://github.com/WWBN/AVideo/issues/6925
