### ISSUE TITLE
Live stream recording stops after 90min

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#6993]
We used to have it set to 3.5 hours, but now its back again to stop after about 90min. How can I extend it again?

This is a message we have from one of our users abroad:
![Screen Shot 5782-12-15 at 17 41 29](https://user-images.githubusercontent.com/58882903/184379578-b80457b4-d63d-45c1-8394-962789871d02.jpg)

**Comment by DanielnetoDotCom** [comment]
check the record_max_size in your Nginx conf.

that is the only limitation that I am aware of.

https://github.com/WWBN/AVideo/blob/master/plugin/Live/install/nginx.conf#L45
