### ISSUE TITLE
Using Embed Video on Chromium Does Allow Full Screen Access?

### ISSUE THREAD

**Issue by aridzonan13** [WWBN/AVideo#6994]
Daniel,

Using an embed video Chromium Browser greys out the "Full Screen" box..  What are we doing wrong? 

Thanks,
JQ

**Comment by DanielnetoDotCom** [comment]
you have to add fullscreen to the allow attribute:

`<iframe allow="fullscreen;">`

For full browser support it should look like this:

```
<iframe src="your_page_url" 
        allowfullscreen="allowfullscreen"
        mozallowfullscreen="mozallowfullscreen" 
        msallowfullscreen="msallowfullscreen" 
        oallowfullscreen="oallowfullscreen" 
        webkitallowfullscreen="webkitallowfullscreen"> 
```

I will send an update with this full browser support if that is the case

**Comment by aridzonan13** [comment]
We really need to have an update to avoid <iframe> security problems.. 

Thanks,
JQ

**Comment by DanielnetoDotCom** [comment]
What are the security problems with iframes?

currently, I do not have chromium here for testing

**Comment by aridzonan13** [comment]
iframe security article.. 
https://blog.bitsrc.io/4-security-concerns-with-iframes-every-web-developer-should-know-24c73e6a33e4

Plus, your <iframe> code solution didn't function..

**Comment by DanielnetoDotCom** [comment]
Hi

thanks for the article, I have read it, but I have no time to argue or explain but 
1. basically the attack is a xss , what honest has nothing to do with iFrame only and can be used with any js command 

2. All the common browsers (2 years old ) do not allow cross domain script inside iFrames , including cookies access


 sorry this article is useless For nowadays
