### ISSUE TITLE
After last Update to 12.1 Live Links are now all missing

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#6995]
![f6df3da8-ad63-4c2b-9ad2-d990a2d5597a](https://user-images.githubusercontent.com/39392449/184496175-e16cc826-002e-4390-9f94-ba68cff7148d.png)

I ran the updates on it all not sure what it is doing

**Comment by DanielnetoDotCom** [comment]
Check the end date for your livelinks.

if the end date is lower than now it will not show anymore

**Comment by JoshWho** [comment]
All my live links is set for the year 2040

**Comment by JoshWho** [comment]
This didn't happen until the last update

**Comment by DanielnetoDotCom** [comment]
check this update

**Comment by JoshWho** [comment]
Nope didn't do it.

They appear and disappear on page load https://www.joshwhotv.com/live


https://user-images.githubusercontent.com/39392449/184511767-1d807051-a552-40aa-8209-9345b51edc90.mp4

**Comment by DanielnetoDotCom** [comment]
Your site is updated now and I found the issue

**Comment by JoshWho** [comment]
Sweet thank you looks good now.

**Comment by JoshWho** [comment]
When i try to play the streams they all show stream has finished with the live links now

**Comment by DanielnetoDotCom** [comment]
please try this update

**Comment by JoshWho** [comment]
> please try this update

That did the trick. Thank you @DanielnetoDotCom
