### ISSUE TITLE
Mobile App Loads But No Content Displays

### ISSUE THREAD

**Issue by jxbolt** [WWBN/AVideo#6997]
**Describe the question**
I have a single video loaded to https://videos.boltonfam.xyz/ from youtube. No issues appear in browser usage. When I use the Android app I can access the site, but there is no content and I do not see any errors in the various logs (error.log and avideo.log). I have tried to access from the mobile app via an authenticated user or anonymously and I get the same result. 

Edit 1: my categories show up in the menu of the mobile app. navigating to the categories results in a blank screen. The search function will not display results. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2523686/184520143-43994b04-908d-4468-bfae-0841b3084a21.png)

**Comment by DanielnetoDotCom** [comment]
Can you please add more videos for testing?

also make sure you are running version 12+

**Comment by DanielnetoDotCom** [comment]
Are your videos public?

is the API plugin enabled?

I could see this from your site

![image](https://user-images.githubusercontent.com/18009293/185184550-903cb51b-49bb-438a-a795-a62f76a1fa3b.png)
