### ISSUE TITLE
Accessibility tools 

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#6998]
Hello Daniel
there is an option to automatically hide accessibility tools from the chat?
it appears from above and it's not pretty!

Thank you
Ilias
![acesibility](https://user-images.githubusercontent.com/60543030/184528304-6f8c7dce-1647-44b8-bc7e-59cccd520cc3.jpg)

**Comment by DanielnetoDotCom** [comment]
try this update
