### ISSUE TITLE
Seek button dosen't work 

### ISSUE THREAD

**Issue by ahmedxda** [WWBN/AVideo#7008]
The Seek Button stopped working even when in v12.0
here are some logs which may help you diagnose:

[17-Aug-2022 11:00:34 Africa/Tripoli] AVideoLog::DEBUG: upda
teStatistic: add more [463] to video [2966] Opera SCRIPT_NAM
E: /objects/videoAddViewCount.json.php
[17-Aug-2022 11:00:34 Africa/Tripoli] AVideoLog::DEBUG: addS
econdsWatching: UPDATE videos SET total_seconds_watching = ?
, modified = now() WHERE id = ?=2966 SCRIPT_NAME: /objects/v
ideoAddViewCount.json.php
[17-Aug-2022 11:01:27 Africa/Tripoli] AVideoLog::DEBUG: upda
teStatistic: add more [471] to video [2966] Opera SCRIPT_NAM
E: /objects/videoAddViewCount.json.php
[17-Aug-2022 11:01:27 Africa/Tripoli] AVideoLog::DEBUG: addS
econdsWatching: UPDATE videos SET total_seconds_watching = ?
, modified = now() WHERE id = ?=2966 SCRIPT_NAME: /objects/v
ideoAddViewCount.json.php

**Comment by DanielnetoDotCom** [comment]
Seek button if is not working it should be a JS error, so the AVideo log, in this case, is useless.

try to check the JS console

**Comment by ahmedxda** [comment]
@DanielnetoDotCom 
Guess what!
I've just installed AVideo on a fresh server and the seek button doesn't work!
I think it's not a database issue

**Comment by DanielnetoDotCom** [comment]
please place a video link so I can test it here.
