### ISSUE TITLE
Encoder Stuck

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7009]
We have an issue with Live Streams not being recorded anymore and when the stream is done the encoder gets stuck. Here is a screen shot:
![Screen Shot 5782-12-20 at 19 11 12](https://user-images.githubusercontent.com/58882903/185190012-443c2c6d-336d-4c46-b838-8e21554e86e9.jpg)

It will stay like this until I delete it from the queue.

What should I look at?

**Comment by walt93** [comment]
I don't know the answer, but going to that encoder and grabbing the tail of the avideo.log in the encoders /video directory and pasting it here is where to start.

**Comment by DanielnetoDotCom** [comment]
check the encoder log file

**Comment by guymass** [comment]
OK I tried few live streams starting with a small 10m then a 20+m and finally a long 3hours stream. Also another try where the encoder got stuck for a 10m+ stream.

One try of 20m stream was successful in encoding the stream and creating the post.

This is the stats of the live stream in the time I stopped it:

The one I made for 3h seemed to have created an empty post as in the following screenshot:
![Screen Shot 5782-12-22 at 1 08 49](https://user-images.githubusercontent.com/58882903/185511097-fc0c517e-be7c-4dfc-9935-4b4cb5c01179.jpg)

This is the post created which is not working:

![Screen Shot 5782-12-22 at 2 11 16](https://user-images.githubusercontent.com/58882903/185511101-51773c28-3655-4c3a-bf06-f54e07d2dce9.jpg)


In the logs I haven't seen yet something besides this messages repeating several time from Schedule plugin:

AVideoLog::DEBUG: Scheduler::run callback ERROR {"error":true,"msg":"Live Key is empty 2","callbackURL":"","callbackResponse":"","vars":[],"tokenStopRecorder":{"error":true,"msg":"send_recorder_id cannot be blank"}} SCRIPT_NAME: /var/www/html/AVideo/plugin/Scheduler/run.php
[19-Aug-2022 01:08:03 Asia/Jerusalem] AVideoLog::DEBUG: Scheduler::run error [26] callbackURL=https://live.ahava528.com/plugin/SendRecordedToEncoder/recordStop.json.php SCRIPT_NAME: /var/www/html/AVideo/plugin/Scheduler/run.php

![Screen Shot 5782-12-22 at 2 22 04](https://user-images.githubusercontent.com/58882903/185511966-ba196af5-7292-4329-afb0-8275329e0c60.jpg)

But it was working on one of my medium stream test so im not sure what is going on.

**Comment by guymass** [comment]
This also is showing me an error as if the file is still being encoded.
![Screen Shot 5782-12-22 at 2 59 24](https://user-images.githubusercontent.com/58882903/185514938-7e8e256a-5d26-421e-b04a-29928bf8063d.jpg)

But the encoder is not showing any movement in the status bar or percentage % and is causing the entire queue to get stuck as well. I will give it few more tests and try to pinpoint the problem.

**Comment by guymass** [comment]
Encoding starts and then it just stops after 2-3%, this is on both sites, both queue on the network encoders:

![Screen Shot 5782-12-22 at 3 31 43](https://user-images.githubusercontent.com/58882903/185517608-2ee808db-41e0-4326-982c-ef561d638ec0.jpg)
![Screen Shot 5782-12-22 at 3 31 09](https://user-images.githubusercontent.com/58882903/185517595-0a3177a1-f630-4e9a-b730-3daa55259efd.jpg)

**Comment by guymass** [comment]
This one got stuck at 30% for no reason:

![Screen Shot 5782-12-22 at 8 48 26](https://user-images.githubusercontent.com/58882903/185551791-d935ed0b-44c1-4d59-ab39-f6dd4260ba96.jpg)

**Comment by DanielnetoDotCom** [comment]
Again, if it is stuck on the encoder you should check the encoder log

**Comment by guymass** [comment]
Well encoders are very slow, even more for streams over 2hours, it was very fast before. Here is something I see in the site's error log, not sure if its related.
![Screen Shot 5782-12-27 at 18 01 49](https://user-images.githubusercontent.com/58882903/186463433-43b260da-c8b3-48c3-a2d6-280fe5ee9544.jpg)

**Comment by guymass** [comment]
Here is another stuck encoding, its been on 34% for more than an hour:

![Screen Shot 5782-12-27 at 18 47 54](https://user-images.githubusercontent.com/58882903/186463949-ad2de68a-0419-4679-9f43-d0d48b5407a7.jpg)

![Screen Shot 5782-12-27 at 18 48 04](https://user-images.githubusercontent.com/58882903/186463933-738ced9a-3eb5-41e8-af92-1465fe019c5a.jpg)

**Comment by guymass** [comment]
And I see this error as well in avideo.log:
![Screen Shot 5782-12-27 at 20 10 47](https://user-images.githubusercontent.com/58882903/186480919-612df286-0d1f-4648-a62f-5dbbf56ff605.jpg)

**Comment by DanielnetoDotCom** [comment]
there are no changes on the encoders for a while .

also, the logs are not related to the encoder
you should share the encoder log, NOT the streamer log

**Comment by guymass** [comment]
Here is my encoder avideo.log after I started my live stream, I will test with a one hour stream and post the log again after I stop the live stream and see how it goes with the encoding. Here is my current log:
![Screen Shot 5782-12-28 at 20 34 06](https://user-images.githubusercontent.com/58882903/186732318-ccb01eb6-eb71-4e67-bbcc-cbae709ee030.jpg)

**Comment by DanielnetoDotCom** [comment]
before you test it, delete the whole log.
once if fails share it all

**Comment by guymass** [comment]
I just stopped a 2:30 hours stream. Here are the log screenshots, lets see how it goes:
![Screen Shot 5782-12-28 at 23 02 51](https://user-images.githubusercontent.com/58882903/186758372-a4164314-5d7d-440f-af4c-d9c536a4d4e9.jpg)
![Screen Shot 5782-12-28 at 23 03 53](https://user-images.githubusercontent.com/58882903/186758399-f4d74bff-245c-4d07-9e91-c62dcd546fd4.jpg)

I will delete the log in my next test.

**Comment by DanielnetoDotCom** [comment]
just this small piece of the log does not help, you need to share a lot of more than that

**Comment by guymass** [comment]
After almost 30m no even a single % movement. I already started the stream before I read your comment, my next test I will clear the log file and make a new stream and will post it here.
![Screen Shot 5782-12-28 at 23 13 34](https://user-images.githubusercontent.com/58882903/186763422-5a7df076-0ad1-415e-99bd-96370d29a7bd.jpg)

**Comment by guymass** [comment]
I now clicked the requeue button and the file started to do something, I get this strange output:
![Screen Shot 5782-12-28 at 23 35 03](https://user-images.githubusercontent.com/58882903/186763857-7e3f469f-1df0-4a40-b768-2bdaebf0b272.jpg)

**Comment by guymass** [comment]
OK now its just completed, didn't see any green bars loading or moving, the impression is that it gets stuck, but after about 45m it completed the encoding and created the post. Is this normal for a two and half video stream?

**Comment by DanielnetoDotCom** [comment]
it is not normal, but also I do not know the reason.

I can only suspect your server is not responding properly to the progress query. but sorry I am not sure how to debug it, I can only tell you this is working on my side.

**Comment by guymass** [comment]
So now I have two file being encoded from an upload or a youtube-dl url and they were going fine until I made a 3min Live Stream which added it to the queue. Now the file that was being encoded got stuck on 68% while the queue only has a 3m live stream size. 

Can't the encoder encode more than one file at a time? 
If the current encoded file gets stuck it effects the entire queue.  My server has resources that can handle more than one encoding at a time so if one gets stuck it doesn't effect the others.
![Screen Shot 5782-12-29 at 8 34 25](https://user-images.githubusercontent.com/58882903/186830291-6687d22c-1cbb-413e-af2b-e955df531655.jpg)
![Screen Shot 5782-12-29 at 8 34 40](https://user-images.githubusercontent.com/58882903/186830305-a013f664-339b-4b38-8457-1d9cda92e243.jpg)

**Comment by guymass** [comment]
Here is my Encoder avideo.log file:
[avideo.log](https://github.com/WWBN/AVideo/files/9430434/avideo.log)

**Comment by guymass** [comment]
More than an hour later my encoders are the same, both encodings are stuck on the same % as as when another file was added to the queue.
![Screen Shot 5782-12-29 at 10 15 05](https://user-images.githubusercontent.com/58882903/186845037-9d5c0b69-8863-4bec-8736-dea9f49c2bb8.jpg)

**Comment by DanielnetoDotCom** [comment]
the console image explains.

your server is blocking the status because your encoder is using HTTP connection. and it should be HTTPS

![image](https://user-images.githubusercontent.com/18009293/186962611-3abfa1fd-77ad-4a2f-b4fa-d8569adb0bea.png)

**Comment by guymass** [comment]
In what way can you be a bit more specific? is this the apache config? or is this the Network Encoders config? or is it in the site configuration itself? please, what file do I need to look at to fix this?

**Comment by DanielnetoDotCom** [comment]
Probably on the network database you have an http encoder regitered.

**Comment by guymass** [comment]
I have only these two encoders in the database, and also I get these errors:

Once is showing here above the menu:

![Screen Shot 5782-12-29 at 21 39 29](https://user-images.githubusercontent.com/58882903/186970590-4b195792-c059-45f7-ac2f-4bc55002b202.jpg)

running the check configuration:
![Screen Shot 5782-12-29 at 21 38 06](https://user-images.githubusercontent.com/58882903/186970813-87495c73-ee01-4d27-a120-9b93a601fabb.jpg)

**Comment by DanielnetoDotCom** [comment]
check the configuration.php file from your network and also from your encoders.

**Comment by guymass** [comment]
My encoders page loads just fine so I am not sure really where this is coming from.

**Comment by DanielnetoDotCom** [comment]
but inside configuration.php MUST use https://encoder.alive528.com/ redirect does not work

**Comment by guymass** [comment]
This is how my config looks:
![Screen Shot 5782-12-29 at 22 05 00](https://user-images.githubusercontent.com/58882903/186974338-0066b397-86ac-419f-a4c2-2c1779d81c27.jpg)

**Comment by DanielnetoDotCom** [comment]
remove this line

![image](https://user-images.githubusercontent.com/18009293/186974656-d54eff09-987b-4246-975f-9bd16283b1ef.png)

**Comment by guymass** [comment]
Now I get the following:
![Screen Shot 5782-12-29 at 22 10 19](https://user-images.githubusercontent.com/58882903/186975187-7661e3d5-7944-42ce-b34f-54e5ad47a8c0.jpg)

**Comment by DanielnetoDotCom** [comment]
Ok, now the problem is not the HTTP/HTTPS anymore, the problem is something on your server configuration that is blocking with CORS.

I do not know where your server is blocking it

**Comment by guymass** [comment]
Both my Encoders are stuck and the queue is getting bigger, besides deleting and loosing that stream and maybe channel, is there a way to restart it?
![Screen Shot 5782-12-29 at 22 11 47](https://user-images.githubusercontent.com/58882903/186975545-d707d608-93b1-4d12-af32-4f97696dce5c.jpg)

**Comment by guymass** [comment]
Does in anyway this CORS should affect the encoding? because I never has issues before. Is this an apache config issue? as both sites are basically the same AVideo site but on two separate domains residing on the same server.

**Comment by guymass** [comment]
I now noticed that trying to replace my encoder url will not save in site's settings, I think there is a bug. I tried to clear the caches but It will always show the previous url.
![Screen Shot 5782-12-29 at 22 29 17](https://user-images.githubusercontent.com/58882903/186978135-bc16f02d-71fd-4c25-8e57-96e3f4881732.jpg)

**Comment by guymass** [comment]
OK so I think my issue could be because of this wrong Encoder url as in the following screenshots:
![Screen Shot 5782-12-30 at 20 19 57](https://user-images.githubusercontent.com/58882903/187041183-1ee05f75-12b0-46d2-8945-d7b072c18101.jpg)
![Screen Shot 5782-12-30 at 20 22 08](https://user-images.githubusercontent.com/58882903/187041184-3fd2ed0b-75ee-417e-b0e7-2e7fefd5025f.jpg)

However now I have another issue arising from this one, it seems I cannot save my settings. When I try to change the url and then I save, after refreshing the page, the settings return to show again the bad url.

Should I open another secondary bug post?

**Comment by matheusfillipe** [comment]
The CORS issue is happening because the .htaccess is force setting `Access-Control-Allow-Origin` to `*` for every `.php` file.

https://github.com/WWBN/AVideo/blob/f47f5c4694d9709eced19f30212a153ea9bba735/.htaccess#L74

By commenting that line i am able to avoid it:

```
<filesMatch "\.(xml|txt)$">
        Header set Cache-Control "max-age=216000, public, must-revalidate"
    </filesMatch>
    <filesMatch "\.(html|htm|php|key|m3u8)$">
        # Header set Access-Control-Allow-Origin: *
        Header set Cache-Control "max-age=1, private, must-revalidate"
    </filesMatch>
</ifModule>
# END Caching
<IfModule mod_rewrite.c>
```

Requests with credentials can't work if the server is responding with `*`: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

**Comment by guymass** [comment]
Brilliant, that solves the CORS issue and good to know it was in the .htaccess file. Much thanks Matt. Now we will continue testing the encoders to see if the still have issues. I will close this post once we have good results.

**Comment by DanielnetoDotCom** [comment]
> The CORS issue is happening because the .htaccess is force setting `Access-Control-Allow-Origin` to `*` for every `.php` file.
> 
> https://github.com/WWBN/AVideo/blob/f47f5c4694d9709eced19f30212a153ea9bba735/.htaccess#L74
> 
> By commenting that line i am able to avoid it:
> 
> ```
> <filesMatch "\.(xml|txt)$">
>         Header set Cache-Control "max-age=216000, public, must-revalidate"
>     </filesMatch>
>     <filesMatch "\.(html|htm|php|key|m3u8)$">
>         # Header set Access-Control-Allow-Origin: *
>         Header set Cache-Control "max-age=1, private, must-revalidate"
>     </filesMatch>
> </ifModule>
> # END Caching
> <IfModule mod_rewrite.c>
> ```
> 
> Requests with credentials can't work if the server is responding with `*`: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

If you remove that you may have problems in other parts of the code, including the ADs.

I am pretty sure there is a configuration somewhere else (on the webserver) to make it work

**Comment by guymass** [comment]
OK everything seems to work fine now and as we don't use ads currently we will try another fix when we get to that issue. For now this is fixed.
