### ISSUE TITLE
Backup plugin 2.3

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#7010]
Hi,

i just updated the backup plugin to 2.3 and now when i open the backed up sql file i get:
mysqldump: Got error: 1045: Access denied for user 'root'@'localhost'

the videos however work fine.

any config i have missed anywhere?

**Comment by DanielnetoDotCom** [comment]
that means the database user you are using on the AVideo has no rights to execute a MySQL dump.

try to google to find out how to add propper permissions.

**Comment by walt93** [comment]
https://serverfault.com/questions/22712/minimum-permissions-for-a-user-to-perform-a-mysqldump
