### ISSUE TITLE
Socket 

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#7012]
Hello,
last pull and I see that while the socket works throughout the script,
1. in live it appears to be out of order
2. and it shows that they are live when it doesn't have any live

Thank you
Ilias

![live2](https://user-images.githubusercontent.com/60543030/185472455-73234b3f-7f8f-464b-80db-e014f5034424.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, 

it is important to have the socket running.

Try to stop and start the socket again:

# Stop

`sudo php /var/www/html/AVideo/plugin/YPTSocket/stopServer.php`

# Start

`nohup php /var/www/html/AVideo/plugin/YPTSocket/server.php &`

**Comment by wetubeclub** [comment]
Hello 
i did what you said but nothing happened about the socket i mean,
I deleted the cache on both the broswer and the site but the situation did not change
after a reboot on the server, the outlet also works live to the page
problem 2 remains though
i mean online label tag is showing instead of offline label
since I don't have any live!!

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
I found this on your server 

 ```
# sudo php /var/www/html/AVideo/plugin/YPTSocket/stopServer.php
[2022-08-19 14:44:16] AVideoLog::DEBUG: _mysql_connect HOST=localhost,DB=aVideo SCRIPT_NAME: /var/www/html/AVideo/plugin/YPTSocket/stopServer.php
Searching for port: 2053
sh: 1: lsof: not found
No Need to kill, port NOT found
```

the problem was that lsof command was not found so I installed it with `sudo apt-get install lsof`

Then run the stop again

```
# sudo php /var/www/html/AVideo/plugin/YPTSocket/stopServer.php
[2022-08-19 14:46:15] AVideoLog::DEBUG: _mysql_connect HOST=localhost,DB=aVideo SCRIPT_NAME: /var/www/html/AVideo/plugin/YPTSocket/stopServer.php
Searching for port: 2053
Server is already runing on port 2053 Killing, PID 1325
```
You should be good now and it also may work next time you try it

**Comment by wetubeclub** [comment]
Thank you
Daniel
