### ISSUE TITLE
Trying to add Subscription Plan to Website -  Query

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#7013]
Hi 

I recently bought the Subscrition plugin to add to my website. I seem to be struggling to configure it to work.  Do I need to do the Paypal IPN  part to get notifications ?

I am fine if they can subscribe normally. I know paypal offer options on their website also. 
Little bit of guidance please.
Thanks

**Comment by DanielnetoDotCom** [comment]
First, make sure your PayPal is working, and I recommend you to use the sandbox for testing.

once you make sure the keys are correct we can check the subscription.

I am not 100% but I am pretty sure the IPN/webhook is now automatic, you do not need to set it up on PayPal side
