### ISSUE TITLE
translation is not displayed correctly

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#7014]
Hello Daniel,
another problem i noticed is
the translation is not displayed correctly in the popup window
in watch later and favorite only numbers and letters instead of the Greek translation
in english it works normally

Thank you
Ilias
![translation](https://user-images.githubusercontent.com/60543030/185679757-89a96708-ebb2-44ed-b045-c74692169f0d.jpg)

**Comment by DanielnetoDotCom** [comment]
where exactly is this?

**Comment by wetubeclub** [comment]
when you hover over the watch later icon and favorite in the tooltip that pops up

**Comment by DanielnetoDotCom** [comment]
Thanks for notice that, I have sent you some updates and I guess your site is fine now
