### ISSUE TITLE
Usage Question: Does RTMP route over CDN in these scenarios?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7015]
**Describe the question**
We are using Wasabi for storage, and Cloudflare for CDN.

1. Does this also route our RTMP traffic over the CDN?
2. When we disengage Cloudflare and use YouPHPTube CDN, does our RTMP traffic route over the CDN?

**Comment by DanielnetoDotCom** [comment]
In my opinion, what I have seen so far is Cloudflare CDN/proxy brings more problems than solutions

> Does this also route our RTMP traffic over the CDN?

The RTMP CDN is only available with our [custom CDN](https://github.com/WWBN/AVideo/wiki/CDN-Plugin)

> When we disengage Cloudflare and use YouPHPTube CDN, does our RTMP traffic route over the CDN?

yes, but not really the RTMP, the RTMP is direct to the server, but the live video .m3u8 and .ts files will use the CDN

**Comment by walt93** [comment]
Thanks!
