### ISSUE TITLE
Crash loading page after uploading 1920x1080 thumbnail

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7016]
**Describe the bug**
After uploading the image, the video page loads a white page with a PHP stack trace.

**To Reproduce**
1. Go to Edit Video page
2. Upload a new poster 1920x1080
3. Save and close
4. Reload the video's page

**Expected behavior**
Not to crash

```
array(4) { ["type"]=> int(1) ["message"]=> string(776) "Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, bool given in /var/www/html/AVideo/objects/functions.php:1669 Stack trace: #0 /var/www/html/AVideo/objects/functions.php(1669): imagesx(false) #1 /var/www/html/AVideo/objects/functions.php(1731): im_resize('/var/www/html/A...', '/var/www/html/A...', '640', '360', 100) #2 /var/www/html/AVideo/objects/video.php(4085): im_resizeV2('/var/www/html/A...', '/var/www/html/A...', '640', '360') #3 /var/www/html/AVideo/objects/video.php(3908): Video::getImageFromFilename_('video_210514184...', 'video') #4 /var/www/html/AVideo/view/modeYoutube.php(234): Video::getImageFromFilename('video_210514184...', 'video') #5 /var/www/html/AVideo/view/index.php(50): require('/var/www/html/A...') #6 {main} thrown" ["file"]=> string(42) "/var/www/html/AVideo/objects/functions.php" ["line"]=> int(1669) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(776) "Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, bool given in /var/www/html/AVideo/objects/functions.php:1669
Stack trace:
#0 /var/www/html/AVideo/objects/functions.php(1669): imagesx(false)
#1 /var/www/html/AVideo/objects/functions.php(1731): im_resize('/var/www/html/A...', '/var/www/html/A...', '640', '360', 100)
#2 /var/www/html/AVideo/objects/video.php(4085): im_resizeV2('/var/www/html/A...', '/var/www/html/A...', '640', '360')
#3 /var/www/html/AVideo/objects/video.php(3908): Video::getImageFromFilename_('video_210514184...', 'video')
#4 /var/www/html/AVideo/view/modeYoutube.php(234): Video::getImageFromFilename('video_210514184...', 'video')
#5 /var/www/html/AVideo/view/index.php(50): require('/var/www/html/A...')
#6 {main}
  thrown"
  ["file"]=>
  string(42) "/var/www/html/AVideo/objects/functions.php"
  ["line"]=>
  int(1669)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}
```

**Comment by walt93** [comment]
Strangely this fixed itself, after a moment I reloaded the page and it looks good.

**Comment by GreenDragonTavern** [comment]
Same here doing any import from any source...

array(4) { ["type"]=> int(1) ["message"]=> string(1095) "Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, null given in /mnt/disk2/data/AVideo/objects/functions.php:1817 Stack trace: #0 /mnt/disk2/data/AVideo/objects/functions.php(1817): imagesx() #1 /mnt/disk2/data/AVideo/objects/functions.php(3840): scaleUpImage() #2 /mnt/disk2/data/AVideo/objects/functions.php(8808): convertImageIfNotExists() #3 /mnt/disk2/data/AVideo/objects/video.php(3986): getMediaSessionPosters() #4 /mnt/disk2/data/AVideo/objects/video.php(1513): Video::getMediaSessionPosters() #5 /mnt/disk2/data/AVideo/objects/functions.php(8841): Video::getMediaSession() #6 /mnt/disk2/data/AVideo/plugin/PlayerSkins/mediaSession.php(6): getMediaSession() #7 /mnt/disk2/data/AVideo/plugin/PlayerSkins/PlayerSkins.php(346): include('...') #8 /mnt/disk2/data/AVideo/plugin/AVideoPlugin.php(179): PlayerSkins->getFooterCode() #9 /mnt/disk2/data/AVideo/view/include/footer.php(90): AVideoPlugin::getFooterCode() #10 /mnt/disk2/data/AVideo/view/modeYoutube.php(386): include('...') #11 /mnt/disk2/data/AVideo/view/index.php(50): require('...') #12 {main} thrown" ["file"]=> string(44) "/mnt/disk2/data/AVideo/objects/functions.php" ["line"]=> int(1817) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(1095) "Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, null given in /mnt/disk2/data/AVideo/objects/functions.php:1817
Stack trace:
#0 /mnt/disk2/data/AVideo/objects/functions.php(1817): imagesx()
#1 /mnt/disk2/data/AVideo/objects/functions.php(3840): scaleUpImage()
#2 /mnt/disk2/data/AVideo/objects/functions.php(8808): convertImageIfNotExists()
#3 /mnt/disk2/data/AVideo/objects/video.php(3986): getMediaSessionPosters()
#4 /mnt/disk2/data/AVideo/objects/video.php(1513): Video::getMediaSessionPosters()
#5 /mnt/disk2/data/AVideo/objects/functions.php(8841): Video::getMediaSession()
#6 /mnt/disk2/data/AVideo/plugin/PlayerSkins/mediaSession.php(6): getMediaSession()
#7 /mnt/disk2/data/AVideo/plugin/PlayerSkins/PlayerSkins.php(346): include('...')
#8 /mnt/disk2/data/AVideo/plugin/AVideoPlugin.php(179): PlayerSkins->getFooterCode()
#9 /mnt/disk2/data/AVideo/view/include/footer.php(90): AVideoPlugin::getFooterCode()
#10 /mnt/disk2/data/AVideo/view/modeYoutube.php(386): include('...')
#11 /mnt/disk2/data/AVideo/view/index.php(50): require('...')
#12 {main}
  thrown"
  ["file"]=>
  string(44) "/mnt/disk2/data/AVideo/objects/functions.php"
  ["line"]=>
  int(1817)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}

**Comment by GreenDragonTavern** [comment]
Also noticed there's a corresponding _jpg folder for every video now, yet has nothing in it?

**Comment by DanielnetoDotCom** [comment]
please check this update to avoid this error

**Comment by GreenDragonTavern** [comment]
After update...

array(4) { ["type"]=> int(1) ["message"]=> string(1095) "Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, null given in /mnt/disk2/data/AVideo/objects/functions.php:1817 Stack trace: #0 /mnt/disk2/data/AVideo/objects/functions.php(1817): imagesx() #1 /mnt/disk2/data/AVideo/objects/functions.php(3840): scaleUpImage() #2 /mnt/disk2/data/AVideo/objects/functions.php(8808): convertImageIfNotExists() #3 /mnt/disk2/data/AVideo/objects/video.php(3986): getMediaSessionPosters() #4 /mnt/disk2/data/AVideo/objects/video.php(1513): Video::getMediaSessionPosters() #5 /mnt/disk2/data/AVideo/objects/functions.php(8841): Video::getMediaSession() #6 /mnt/disk2/data/AVideo/plugin/PlayerSkins/mediaSession.php(6): getMediaSession() #7 /mnt/disk2/data/AVideo/plugin/PlayerSkins/PlayerSkins.php(346): include('...') #8 /mnt/disk2/data/AVideo/plugin/AVideoPlugin.php(179): PlayerSkins->getFooterCode() #9 /mnt/disk2/data/AVideo/view/include/footer.php(90): AVideoPlugin::getFooterCode() #10 /mnt/disk2/data/AVideo/view/modeYoutube.php(386): include('...') #11 /mnt/disk2/data/AVideo/view/index.php(50): require('...') #12 {main} thrown" ["file"]=> string(44) "/mnt/disk2/data/AVideo/objects/functions.php" ["line"]=> int(1817) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(1095) "Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, null given in /mnt/disk2/data/AVideo/objects/functions.php:1817
Stack trace:
#0 /mnt/disk2/data/AVideo/objects/functions.php(1817): imagesx()
#1 /mnt/disk2/data/AVideo/objects/functions.php(3840): scaleUpImage()
#2 /mnt/disk2/data/AVideo/objects/functions.php(8808): convertImageIfNotExists()
#3 /mnt/disk2/data/AVideo/objects/video.php(3986): getMediaSessionPosters()
#4 /mnt/disk2/data/AVideo/objects/video.php(1513): Video::getMediaSessionPosters()
#5 /mnt/disk2/data/AVideo/objects/functions.php(8841): Video::getMediaSession()
#6 /mnt/disk2/data/AVideo/plugin/PlayerSkins/mediaSession.php(6): getMediaSession()
#7 /mnt/disk2/data/AVideo/plugin/PlayerSkins/PlayerSkins.php(346): include('...')
#8 /mnt/disk2/data/AVideo/plugin/AVideoPlugin.php(179): PlayerSkins->getFooterCode()
#9 /mnt/disk2/data/AVideo/view/include/footer.php(90): AVideoPlugin::getFooterCode()
#10 /mnt/disk2/data/AVideo/view/modeYoutube.php(386): include('...')
#11 /mnt/disk2/data/AVideo/view/index.php(50): require('...')
#12 {main}
  thrown"
  ["file"]=>
  string(44) "/mnt/disk2/data/AVideo/objects/functions.php"
  ["line"]=>
  int(1817)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}

**Comment by DanielnetoDotCom** [comment]
try this

**Comment by GreenDragonTavern** [comment]
Same result...did narrow down issue to YouTube uploads or YouTube embeds. Live stream to HLS works fine, native uploads of MP4, MKV, AVI etc all seem fine too. Rumble upload and embed links work without issue. Definitely a YouTube issue here, all others are working fine.

**Comment by DanielnetoDotCom** [comment]
can you please describe exactly how do I reproduce this issue?

**Comment by GreenDragonTavern** [comment]
Uploaded this...https://youtu.be/z6UzXDIZzsA as MP4. Below is result:

https://tube.tba.comcorpeco.com/video/20/jimmy-s-java---pilar-s-empanadas?channelName=Admin

**Comment by DanielnetoDotCom** [comment]
I just upload this same video to the demo site and I am not seeing any issue

HLS: https://demo.avideo.com/video/387/hls-jimmy-s-java---pilar-s-empanadas
MP4: https://demo.avideo.com/video/388/mp4-jimmy-s-java---pilar-s-empanadas

**Comment by GreenDragonTavern** [comment]
Tried a couple other installs, different youtube videos, and same error. Behavior on embed and upload are same...error.

array(4) { ["type"]=> int(1) ["message"]=> string(1095) "Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, null given in /mnt/disk2/data/AVideo/objects/functions.php:1817 Stack trace: #0 /mnt/disk2/data/AVideo/objects/functions.php(1817): imagesx() #1 /mnt/disk2/data/AVideo/objects/functions.php(3844): scaleUpImage() #2 /mnt/disk2/data/AVideo/objects/functions.php(8812): convertImageIfNotExists() #3 /mnt/disk2/data/AVideo/objects/video.php(3986): getMediaSessionPosters() #4 /mnt/disk2/data/AVideo/objects/video.php(1513): Video::getMediaSessionPosters() #5 /mnt/disk2/data/AVideo/objects/functions.php(8845): Video::getMediaSession() #6 /mnt/disk2/data/AVideo/plugin/PlayerSkins/mediaSession.php(6): getMediaSession() #7 /mnt/disk2/data/AVideo/plugin/PlayerSkins/PlayerSkins.php(346): include('...') #8 /mnt/disk2/data/AVideo/plugin/AVideoPlugin.php(179): PlayerSkins->getFooterCode() #9 /mnt/disk2/data/AVideo/view/include/footer.php(90): AVideoPlugin::getFooterCode() #10 /mnt/disk2/data/AVideo/view/modeYoutube.php(386): include('...') #11 /mnt/disk2/data/AVideo/view/index.php(50): require('...') #12 {main} thrown" ["file"]=> string(44) "/mnt/disk2/data/AVideo/objects/functions.php" ["line"]=> int(1817) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(1095) "Uncaught TypeError: imagesx(): Argument #1 ($image) must be of type GdImage, null given in /mnt/disk2/data/AVideo/objects/functions.php:1817
Stack trace:
#0 /mnt/disk2/data/AVideo/objects/functions.php(1817): imagesx()
#1 /mnt/disk2/data/AVideo/objects/functions.php(3844): scaleUpImage()
#2 /mnt/disk2/data/AVideo/objects/functions.php(8812): convertImageIfNotExists()
#3 /mnt/disk2/data/AVideo/objects/video.php(3986): getMediaSessionPosters()
#4 /mnt/disk2/data/AVideo/objects/video.php(1513): Video::getMediaSessionPosters()
#5 /mnt/disk2/data/AVideo/objects/functions.php(8845): Video::getMediaSession()
#6 /mnt/disk2/data/AVideo/plugin/PlayerSkins/mediaSession.php(6): getMediaSession()
#7 /mnt/disk2/data/AVideo/plugin/PlayerSkins/PlayerSkins.php(346): include('...')
#8 /mnt/disk2/data/AVideo/plugin/AVideoPlugin.php(179): PlayerSkins->getFooterCode()
#9 /mnt/disk2/data/AVideo/view/include/footer.php(90): AVideoPlugin::getFooterCode()
#10 /mnt/disk2/data/AVideo/view/modeYoutube.php(386): include('...')
#11 /mnt/disk2/data/AVideo/view/index.php(50): require('...')
#12 {main}
  thrown"
  ["file"]=>
  string(44) "/mnt/disk2/data/AVideo/objects/functions.php"
  ["line"]=>
  int(1817)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}

**Comment by GreenDragonTavern** [comment]
Just did latest pull and all good regarding YouTube videos. Thank you!

**Comment by DanielnetoDotCom** [comment]
but is still, missing something?

**Comment by GreenDragonTavern** [comment]
No, nothing missing anymore. Did have to update all encoders, encoder network, storage but so far so good with latest pull.

**Comment by walt93** [comment]
Looks like this is all resolved, thanks & closing.
