### ISSUE TITLE
move videos from one channel to another ?

### ISSUE THREAD

**Issue by lachainestoplinky** [WWBN/AVideo#7017]
Hello, 
currently I only have one "stop linky and 5G" channel.
I want to create an account for a second Channel.
will it be possible to move videos from one channel to another ?
Cordially

**Comment by walt93** [comment]
Edit the video's owner in the Advanced tab
![Screen Shot 2022-08-21 at 2 51 20 PM](https://user-images.githubusercontent.com/11711050/185812395-d4426a08-383b-4874-9772-d9e4a728d7f8.jpg)
.

**Comment by lachainestoplinky** [comment]
Hello, thank you !!
