### ISSUE TITLE
The AVideo script should be installed in the www folder or in the html folder?

### ISSUE THREAD

**Issue by aliceglitch** [WWBN/AVideo#7018]
Hello, the AVideo script is installed in the educational video of the ''https://tutorials.avideo.com/v/27'' site in the html folder (according to the shot) and it is installed in the www folder on the ''https://www.linuxbabe.com/ubuntu/install-avideo-youphptube-ubuntu-20-04-server'' site (according to the shot) and for the update of the AVideo script, the script is updated in the html folder on the "https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform" site. (According to the shot), which folder is the priority for installing the AVideo script? And which folder is more effective and useful for installing the AVideo script? html folder or www folder?
Thanks

![html filder for install](https://user-images.githubusercontent.com/72448881/185751143-880c8b2c-0d82-4da7-87f7-613091dd0451.png)
![www folder for install](https://user-images.githubusercontent.com/72448881/185751216-516c7ff5-5b92-4f69-b0be-b8e5af5fa91c.png)
![html folder for update](https://user-images.githubusercontent.com/72448881/185751238-aea8ec9c-282b-4053-8b2d-0265f0603bec.png)

**Comment by DanielnetoDotCom** [comment]
I recommend [this tutorial](https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x-for-AVideo-Platform-version-11.x-or-newer)

I do not know linuxbabe.com

**Comment by aliceglitch** [comment]
> I recommend [this tutorial](https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x-for-AVideo-Platform-version-11.x-or-newer)
> 
> I do not know linuxbabe.com

Why did you send me this link ''https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x-for-AVideo-Platform-version-11.x-or-newer'' and why didn't you send me this link "https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-22.x-for-AVideo-Platform-version-11.x-or-newer"? Isn't the installation on the "fresh Ubuntu 22.x" more up-to-date?

**Comment by aliceglitch** [comment]
> 



> I recommend [this tutorial](https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x-for-AVideo-Platform-version-11.x-or-newer)
> 
> I do not know linuxbabe.com

In this link, only the database has been created for e-video, and there is no command to create a database for Encoder. Do we have to create another database for Encoder ourselves?
