### ISSUE TITLE
How to verify that users are owners of published videos ?

### ISSUE THREAD

**Issue by sinaisinai** [WWBN/AVideo#7019]
To respect the laws, we have to verify (automatically or manually) that each video is published by it´s owner. How do can we do it ?
What is the solution allow others users to publish on our platform ?

**Comment by DanielnetoDotCom** [comment]
# 1. I suggest you create a private user group

# 2. then set all the videos to be saved on this user group by default with the PredefinedCategory plugin.

![chrome-capture-2022-7-22 (1)](https://user-images.githubusercontent.com/18009293/185946717-0e16f7bf-f0dd-42fc-b4b8-0500c47e1ed1.gif)

# 3. Do not allow users to change user groups

![image](https://user-images.githubusercontent.com/18009293/185946953-b0f57f9b-65e3-4ece-bd8c-2a677305af9a.png)

**Comment by sinaisinai** [comment]
Thank you for your answer.
Maybe my question was not clear.
If my platform wants to monetize users, How could I know that users have rights on videos that they upload to monetize ? To respect copyright

**Comment by DanielnetoDotCom** [comment]
I do not have an answer for that.

I cannot autodetect copyright issues

**Comment by walt93** [comment]
I believe there is a way to set videos to automatically appear in Unpublished state.
Someone then has to manually publish each video after verifying copyright.
This is labor intensive for sure...
