### ISSUE TITLE
Embed video from facebook no longer works

### ISSUE THREAD

**Issue by sinaisinai** [WWBN/AVideo#7020]
Daniel,
Last year we could embed facebook videos. Now we test it and it no longer works. We also test on your demo website and same issue.
It works for someone ? please let me know

**Comment by DanielnetoDotCom** [comment]
try this update. if still fail, please share what exactly FB link are you sharing

**Comment by sinaisinai** [comment]
> try this update. if still fail, please share what exactly FB link are you sharing

Hi Daniel,
The embed works after i did the update. But some embed video size is not correct. That is vertical videos recorded with phone
Please see these 2 exemples:

1- Horizontal video embed from facebook
https://demo.avideo.com/video/392/sans-engagement-resiliable-en-ligne

2- Vertical video embed from facebook
https://demo.avideo.com/video/393/l-afrique-veut-et-doit-savoir-toute-la-verite-sur-l-accusation-gravissime-du-mali-%F0%9F%87%B2%F0%9F%87%B1-contre-la-france-%F0%9F%87%AB%F0%9F%87%B7-%C3%80-l-onu-%F0%9F%87%BA%F0%9F%87%B3-le-15-ao%C3%9Bt-2022-pour-soutien-aux...-%7C-by-franklin-n

**Comment by DanielnetoDotCom** [comment]
Hi, sorry the demo site is already reset.

can you please share the video source (facebook link)?

**Comment by sinaisinai** [comment]
Try to embed the following facebook videos and you will face the issue between both:

1 - https://fb.watch/g6n6Kxl7of/ (Vertical video)
2 - https://fb.watch/g6ny5EuvUH/ (Horizontal video

**Comment by DanielnetoDotCom** [comment]
Ok, the Vertical is actually a reel  and the embed link is this https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Ffb.watch%2Fg6n6Kxl7of%2F&show_text=false&t=0&autoplay=1

the problem is, by default our videos are 16:9 aspect ratio. and I do not know any way to detect if the FB embed video is a reel

**Comment by sinaisinai** [comment]
Thank you Daniel.
Maybe you can put an option to allow users to choose the  ratio of the video they want to embed. So you can switch between both to obtain the right result

Otherwise, The horizontal  video result is right, but the sound is auto muted. How to fix that ?

**Comment by DanielnetoDotCom** [comment]
> Maybe you can put an option to allow users to choose the ratio of the video they want to embed. So you can switch between both to obtain the right result

Maybe in the future

> Otherwise, The horizontal video result is right, but the sound is auto muted. How to fix that ?

I do not know, this is a Facebook thing. I am not sending any volume information to the embed

**Comment by sinaisinai** [comment]
Okay
Thanks
