### ISSUE TITLE
User Notification-Error Message

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#7021]
Hey
an error message is recieved
When I try to send a new message (manually) from the User Notification plugin
The first time I did this it worked, and since then I get an error message
(even when all fields are filled)
Thanks Eitan Live528

![photo_2022-08-22_08-31-10](https://user-images.githubusercontent.com/85537931/185846310-233e2c01-7557-401c-b888-65fd6a5a6dd4.jpg)

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by eitanwa** [comment]
Works great now
Thanks
