### ISSUE TITLE
Getting HLS-url

### ISSUE THREAD

**Issue by sirdaddits** [WWBN/AVideo#7030]
Hello
is it possible to get video-hls-url from web-interface or from some plugin?

**Comment by sirdaddits** [comment]
I know, that possible to get url from browser-debug (for Live stream)
For VOD I know about url for download per-quality. 
Maybe your plugin video-HLS can do that? (Copy video URL for other site or server)

**Comment by DanielnetoDotCom** [comment]
Please I still do not know if you want the URL from VOD or Live.

FYI the URL from VOD videos will only work if you disable the download protection

**Comment by sirdaddits** [comment]
OK, I want to get HLS-URL for live and VOD 
For VOD it is possible with video-hls-plugin?
How it is possible for live-videos?

**Comment by DanielnetoDotCom** [comment]
> For VOD it is possible with video-hls-plugin?

Only inspecting the source code

> How it is possible for live-videos?

![image](https://user-images.githubusercontent.com/18009293/186729333-682575bc-3fe3-46c0-9a12-19407cfa8641.png)

**Comment by sirdaddits** [comment]
Thank you
