### ISSUE TITLE
Video thumbnails bug in safari

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#7031]
Hi,

i have narrowed this bug down as it has been going on since the 12 update. The bug whereby thumbnails do not display throughout the site only affecting safari is coming from php8+ if using php7.4 they work fine so the bug is in php8 and php8.1 and all extensions are installed on v8 so i am not missing any. The exact same extensions as 7.4 i use on 8.0. This worked fine before the 12 update as i was using v8 on safari every day. Ive had to fall back to 7.4 for now until this is fixed. However 7.4 is not as stable as 8 has been for me. At least we know where this issue is coming from now :)

**Comment by DanielnetoDotCom** [comment]
if works on PHP 7.4 and does not work on PHP 8 the Bug is on your installation or on PHP itself. 

please give more details when you mean the thumbs are not working, please screenshot and share the avideo log

**Comment by para2022** [comment]
Oh sorry i mean thumbnails. All of them throughout the site. They display on every singe browser but safari on my mac. If i run php 7.4 the thumbnails display fine. If i switch to php8 or 8.1 the thumbnails wont display even after clearing caches. Before the update i run php8.0 and i used safari as main browser and it always worked no problems so its not my php8.0 installation as its not changed and was working on v11 of avideo. It was after the 12 update this issue started. Nothing is displayed in the AVideo log so no point in posting that. My server logs report no error either.
If i mouse over the blank spaces it does display the gif
![Screenshot 2022-08-24 at 20 20 10](https://user-images.githubusercontent.com/107706817/186504929-f31c786f-349e-4bbe-a82b-b17e31794ffc.png)
![Screenshot 2022-08-24 at 20 19 27](https://user-images.githubusercontent.com/107706817/186505050-96cff3b6-5809-45da-b03f-2a174249c883.png)

**Comment by DanielnetoDotCom** [comment]
check your logs

now AVideo uses webp format as the main format. before it was jpeg
