### ISSUE TITLE
Comments panel missing

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#7032]
Hi,

The comments panel is now missing since yesterday when the comments section was updated. Ive switched php versions so its no issue with php, it is defo missing. Also if you make a comment and post it the comment box is still filled with the comment text. You have to refresh the page to clear the comments box. The comments box should be blank again after making a comment like it was before.

Thanks

**Comment by DanielnetoDotCom** [comment]
you need to provide some screenshots and more details so I will be able to help you.
