### ISSUE TITLE
LIve LInks are missing after latest git pull

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7034]
![221bd7c4-2a0d-4d89-81c1-470cb780a02b](https://user-images.githubusercontent.com/39392449/186528005-8da1897e-9950-437b-a8c5-77a8add4548f.png)

**Comment by DanielnetoDotCom** [comment]
what exact page is that?

did you make a git pull today?

**Comment by JoshWho** [comment]
The /live

**Comment by JoshWho** [comment]
> what exact page is that?
> 
> did you make a git pull today?

Yes about a hour ago

**Comment by DanielnetoDotCom** [comment]
Thanks for noticing that, I just sent you an update, it should be good now.

**Comment by JoshWho** [comment]
Perfect. Looks great. Thank you @DanielnetoDotCom
