### ISSUE TITLE
Roku JSON: Why do the description fields get a "=> \n" inserted into the beginning?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7035]
**Describe the bug**
```
{

	"providerName": "Conspyre\u2022TV",
	"language": "en",
	"lastUpdated": "2022-08-24T14:25:24-07:00",
	"movies": [{
		"id": "video_10742",
		"title": "Cult of the Medics (Chapter 8)",
		"longDescription": "=> \nCult Of The Medics - Chapter 8 - UNDERWORLD\nDavid Whitehead, Truth Warrior Productions 2022\n\nCatch up on the series here: https:\/\/cultofthemedics.com\/ \n\nDownload other chapters: https:\/\/concen.org\/content\/cult-medics-chapter-1-4-david-whitehead-2021 \n\n\"We live in the sunlit world of what we believe to be reality. But there is, unseen by most, an Underworld, a place that is just as real, but not as brightly lit, a dark side if you will\u2026\"\n\nThis is the culmination of 15 years of resear",
		"shortDescription": "=> \nCult Of The Medics - Chapter 8 - UNDERWORLD\nDavid Whitehead, Truth Warrior Productions 2022\n\nCatch up on the series here: https:\/\/cultofthemedics.com\/ \n\nDownload other chapters: https:\/\/concen.org",
		"thumbnail": "https:\/\/conspyre.tv\/videos\/video_220709134653_v69b9\/video_220709134653_v69b9_roku.jpg?cache=1661376324_1661376324",
		"tags": ["Cult of the Medics"],
		"genres": ["special"],
		"releaseDate": "2022-07-09",
		"categories_id": 426,
		"rating": {
			"rating": "R",
			"ratingSource": "MPAA"
		},


```

**To Reproduce**
This appears to be happening everywhere. see https://conspyre.tv/roku.json?catName=cult-of-the-medics for examples.

**Answer**
(from feed/roku.json.php)

            $movie->longDescription = "=> " . _substr(strip_tags(br2nl(UTF8encode($row['description']))), 0, 490);
            $movie->shortDescription = _substr($movie->longDescription, 0, 200);

**Question**
But why? 😃

**Comment by DanielnetoDotCom** [comment]
probably you have some break line at the beginning, or maybe you had HTML tags on the description.

**Comment by walt93** [comment]
Strangely when I modify this line of code (from feed/roku.json.php)

        $movie->longDescription = "=> " . _substr(strip_tags(br2nl(UTF8encode($row['description']))), 0, 490);

And remove this: "=> " .

        $movie->longDescription = _substr(strip_tags(br2nl(UTF8encode($row['description']))), 0, 490);

The "=>" characters disappear from my Roku JSON.

I'm calling this a fix. Can you please apply to master branch and thank you?

**Comment by DanielnetoDotCom** [comment]
Sorry you are right, here is the fix
