### ISSUE TITLE
Notification bell will not disable it just turned itself back on in last update

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7036]
I have the disable notification checked but it still shows.

**Comment by JoshWho** [comment]
![Uploading e8022e02-9479-4a35-8e96-94a3bd581fed.png…]()

**Comment by JoshWho** [comment]
Or is that a new static thing and future notifications will be there?

**Comment by DanielnetoDotCom** [comment]
Correct, this will be a site global notification. in the future, I will allow you to disable live notifications on it (if you want)

**Comment by JoshWho** [comment]
> Correct, this will be a site global notification. in the future, I will allow you to disable live notifications on it (if you want)

That is sweet. Looking forward to this.
