### ISSUE TITLE
Make Notifications use Static Image instead of Live thumb

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7037]
Any way to make the notifications able to use static thumbnail?

Live Generation doesn't works well when there is hundreds of streams and I don't want to disable the live globally, then there would be no thumbnails, most users dont know to upload one..

![43ed1746-fc62-4c7c-a5f5-73039d0e4e68](https://user-images.githubusercontent.com/39392449/186724492-b00ff7bc-083d-4d69-a0a8-29127c0bf180.png)

**Comment by DanielnetoDotCom** [comment]
Hi

it may take some time to be done. but what about if instead of live links you add the m3u8 links as an embed link on your videos manager?

like that, you will be able to edit images and all metadata just like a regular video.

also, you can create a separate category for them

**Comment by JoshWho** [comment]
That would be kewl

**Comment by DanielnetoDotCom** [comment]
it is working already, you should try it

**Comment by JoshWho** [comment]
How will the streams be findable?

**Comment by DanielnetoDotCom** [comment]
It will behave just like a video. but you can create a separate category just for them

**Comment by JoshWho** [comment]
I C.  I will Have a journey with this but It will look good in the end. Thank you.

**Comment by JoshWho** [comment]
Emedding the livelink use to work. Now it just does this

![71e3f924-6170-4013-afd4-721cc0c640bd](https://user-images.githubusercontent.com/39392449/186749905-c2fe120a-f349-491a-8e6b-303466b2ed4a.png)

**Comment by JoshWho** [comment]
You KNow what, Even better Now that redirect is built in I can redirect it to the LiveLink address. This will work

**Comment by JoshWho** [comment]
Ok nevermind redirect doesnt seem to work.

**Comment by DanielnetoDotCom** [comment]
what exactly link are you trying to embed?

**Comment by JoshWho** [comment]
> what exactly link are you trying to embed?

THis https://www.joshwhotv.com/liveLink/49/info-wars

**Comment by DanielnetoDotCom** [comment]
this is still a live link

you should try to embed this 

https://www.joshwhotv.com/4/streams/playlist.m3u8

**Comment by JoshWho** [comment]
> this is still a live link
> 
> you should try to embed this
> 
> https://www.joshwhotv.com/4/streams/playlist.m3u8

That didn't work, but I figured out why the redirect didn't work. I didn;t enable it, Now the redirect works fine and this will be perfect.

**Comment by JoshWho** [comment]
Not bad Now need a better way of sorting them Like a option for alphabetical or something

![996be24e-f6a8-4233-a2da-cd20bf7ad632](https://user-images.githubusercontent.com/39392449/186802986-9c0bdc8f-0447-4628-93f1-c2963ee62e8f.png)

**Comment by DanielnetoDotCom** [comment]
Create playlists
