### ISSUE TITLE
Live Thumbnail Size is tiny

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7039]
Not sure where to adjust this.

![6d296d66-de24-4bd1-8623-c88adfd1fcfc](https://user-images.githubusercontent.com/39392449/186798926-ef301fb5-cbf1-48af-8be1-30c541735b11.png)

**Comment by JoshWho** [comment]
Also starting to see copies of the same notification

![22a2a859-7b15-4878-bb6b-02b0df09f121](https://user-images.githubusercontent.com/39392449/186947907-66eff4a9-60c7-4766-9a31-c811fb646444.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure, your video is probably a low resolution.

or maybe it is an adaptive live and your server is only able to get the lower resolution.

**Comment by JoshWho** [comment]
No Every now and then they show correctly but then they go back to that. I think It has something to do with the encoder it selects to use.

**Comment by cisfreak** [comment]
The thumbnails on my live streams are doing the same thing. Adaptive live is not enabled and the content creator is streaming in 540p.

**Comment by JoshWho** [comment]
Most my users do 720p I think it has something to do with the encoder

**Comment by JoshWho** [comment]
Is there a way we can force the correct thumbnail dimensions?

**Comment by JoshWho** [comment]
After I turned on Live GIF thumbs it fixed the thumbnails from being tiny. So just enable the Live GIF thumbnails and it will be the correct size now.

**Comment by JoshWho** [comment]
Nevermind that didn't fix it

![421df27a-af0c-4c53-a178-0148e3b808a2](https://user-images.githubusercontent.com/39392449/188227941-e1f70bb2-1eed-414a-a1cf-9dabe9895893.png)

**Comment by DanielnetoDotCom** [comment]
that is the only explanation I have 

https://github.com/WWBN/AVideo/issues/7039#issuecomment-1228763820

but try this update, now I will try to scaleup the images

**Comment by JoshWho** [comment]
Looks like that did the trick. I disabled the GIF for them too and sped up the load time with it. Thank you @DanielnetoDotCom this is wonderful.
