### ISSUE TITLE
Lingering crash after uploading poster frame

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7040]
**Describe the bug**
I just uploaded another 1920x1080 poster frame, because of habit (Roku)

I got an interesting failure mode, screenshot attached - seems like the same we've seen before - only nicer rendering. The crash is rendering where the video poster should go.

<img width="1128" alt="Screen Shot 2022-08-25 at 11 33 52 PM" src="https://user-images.githubusercontent.com/11711050/186838020-500d96a1-f984-470b-be2e-68551da9e24a.png">

**Comment by DanielnetoDotCom** [comment]
this should avoid the crash, but I guess you will still have an image error

**Comment by walt93** [comment]
After reporting the problem I went through the clear first page cache/clear cache directory dance and the crash resolved & I was able to see the image I had uploaded.

**Comment by walt93** [comment]
NOTE: the above crash appears to resolve itself after two minutes, reloading the page works & the new image is present.

**Comment by DanielnetoDotCom** [comment]
but did you make a git pull after the update above?
