### ISSUE TITLE
Re wording for the Go Live Functions

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7041]
Need to change the Main Live on the Upload menu to Live Studio or Live Dashboard  

 Also Should add the Go Live with Webcam to the Upload Dropdown as well. Make It Say "Go Live with Webcam"

![9e3e8f2f-8bbc-403d-9a3f-bddd9b2d93b5](https://user-images.githubusercontent.com/39392449/186951548-bd07f430-bde6-407c-801a-7f2a5ea01698.png)

In the Live Studio Dashboard should change Webcam to Go Live with Webcam and Meeting to Live Stream Meeting
![c01b9d4c-7b7f-408c-9c0a-4fedd3d4b60f](https://user-images.githubusercontent.com/39392449/186951733-3af6a884-c82e-49fe-a791-c14bd590e157.png)

**Comment by JoshWho** [comment]
Did u see this @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
The `GO live` you can reword it on the Live plugin

![image](https://user-images.githubusercontent.com/18009293/187711219-4ca33b4d-89ca-4287-9d24-c7cbcea84278.png)

> Webcam to Go Live with Webcam and Meeting to Live Stream Meeting

Sorry but I do not want long names on those buttons

**Comment by JoshWho** [comment]
It doesn't have to be long text on the app, just use it for the hover description.

Either way I want users to realize they can 1 clic Go Live or they can use the studio

**Comment by JoshWho** [comment]
Currently if I tell someone to go Live they ask which one

**Comment by JoshWho** [comment]
If the users do not understand what they are looking at then this will be overlooked and always asked about. There needs to be some clerical

**Comment by JoshWho** [comment]
That 1 Click GO Live is gonna  be used so much once it catches on. There needs to be some kind of difference from the live dashboard control settings and the webcam go live

**Comment by DanielnetoDotCom** [comment]
I just sent some updates, and I hope it is better now

**Comment by JoshWho** [comment]
I do not see any changes after the git pull.

**Comment by JoshWho** [comment]
I do see the hover text for the Live Settings. I just do not see the Go live option in the upload dropdown.

**Comment by DanielnetoDotCom** [comment]
Can you please screenshot what is missing?

**Comment by JoshWho** [comment]
![download (29)](https://user-images.githubusercontent.com/39392449/188163058-521d8e34-fe1b-4c7b-b35d-3e82c2225c6b.png)

and

![186951733-3af6a884-c82e-49fe-a791-c14bd590e157](https://user-images.githubusercontent.com/39392449/188163517-6426c9fa-9e45-4bb3-a745-4f359370be1c.png)

**Comment by DanielnetoDotCom** [comment]
Done, but if the screen is small I will show only Webcam and Meeting buttons

**Comment by JoshWho** [comment]
Looks great. THank you @DanielnetoDotCom
