### ISSUE TITLE
How does a person purchase?

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#7042]
I have this set up a future livestream and Ppv. How does one purchase it?

https://user-images.githubusercontent.com/58601786/186969060-eb295652-b5a4-4380-a0b2-cd5821cc8136.MOV

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/PayPerView-Live-Plugin#once-a-user-tries-to-play-the-live-he-will-be-prompt-for-choosing-the-plan-and-a-payment

**Comment by barrunning** [comment]
I am getting two events. One is too purchase and one is to view.

**Comment by DanielnetoDotCom** [comment]
I can see one is a PPV another one is a schedule.

**Comment by barrunning** [comment]
This is what I get.

**Comment by DanielnetoDotCom** [comment]
I did create 2 different things, a schedule, and a PPV. 

I suspect that you want the PPV only, so delete the scheduled live
