### ISSUE TITLE
comment window not showing

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#7044]
When I click comments I get a blank screen.

**Screenshots**
![comments](https://user-images.githubusercontent.com/66537018/187005537-12353b9e-e6fd-42c5-8497-6e14bf61d9ea.png)

Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
this update should fix it, thanks

**Comment by fakeologist** [comment]
always happy to help improve!

**Comment by fakeologist** [comment]
Is it fixed? Don't see it.

**Comment by DanielnetoDotCom** [comment]
yes, it may require a git pull

**Comment by fakeologist** [comment]
Still not showing

**Comment by DanielnetoDotCom** [comment]
I can see from here 

![image](https://user-images.githubusercontent.com/18009293/187761298-b51f37ba-f6f9-4b8f-9755-14001a1d13b9.png)

**Comment by fakeologist** [comment]
ok well I can't see here on my desktop or phone

**Comment by DanielnetoDotCom** [comment]
can you please check in your desktop if there is any JS error?

is this a specific user with that error?

the main issue is that I am not showing a loading screen (I may change that in the future) and it is taking time to display all comments

**Comment by fakeologist** [comment]
Don't see any error.
All the other options popup and populate ok.
It's just the comment button opens up and stays empty.
This happens with my admin user.
Happens in brave and chrome. I'll try firefox.

**Comment by DanielnetoDotCom** [comment]
the problem seems to me that you have too many comments and it is taking some time to load.
I just sent an update that will load only 10 comments at a time (before was 1000)

it should make it load faster and then you will have a load more button

**Comment by fakeologist** [comment]
Fixed.
Good work.
