### ISSUE TITLE
Help transferring install to fresh git checkout

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7045]
**Describe the question**
I keep a number of changes to AVideo locally. My normal workflow is
```
  sudo git stash
  sudo git pull
  sudo git stash pop

```
I want to do this workflow on two machines & this is extremely tedious.

I made a fork of AVideo
I did a git clone of my fork
I checked out a branch on my fork
I made all my changes and checked into my branch
...so my workflow will now be to git merge upstream to my master, and then git merge from master into my branch

So I tried doing the swap, `sudo mv /var/www/html/AVideo /var/www/html/AVideo.old` and `sudo mv /var/www/html/MyAVideo /var/www/html/AVideo`
And it comes up with the installer page
And if I remove /install, it comes up blank

Please advise as to missing steps to move my running AVideo install to this new freshly git cloned directory.

**Comment by DanielnetoDotCom** [comment]
`
So I tried doing the swap, sudo mv /var/www/html/AVideo /var/www/html/AVideo.old and sudo mv /var/www/html/MyAVideo /var/www/html/AVideo
`
the Steps above seem to be perfect. I am not sure why it failed. try to check the folder permissions
