### ISSUE TITLE
PWA Not allowing Full screen when turning the phone sideways

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7047]
Instead of going full screen when you turn your phone it does this

![Screenshot_20220828-103720](https://user-images.githubusercontent.com/39392449/187083321-5df62c29-c165-4474-bcc4-cfc11165df90.jpg)

**Comment by DanielnetoDotCom** [comment]
do you have the plugin VideoLandscapeFullscreen enabled?

**Comment by JoshWho** [comment]
Yes

**Comment by walt93** [comment]
I have had this installed, and I have never seen full screen on iOS. The only way to get full screen is through airplay on the TV AFAIK.

**Comment by JoshWho** [comment]
Do I have to disable the Auto Rotate plugin?

**Comment by DanielnetoDotCom** [comment]
there is not much I can do, but here is an update for the latest version

**Comment by JoshWho** [comment]
Thank you That did the trick!!!!!!
