### ISSUE TITLE
Sign/up or Sign-in page is not Available how to disable or reset it back!

### ISSUE THREAD

**Issue by pmanhutch** [WWBN/AVideo#7048]
Sign/up or Sign-in page is not Available how to disable or reset it back to Admin!

![IMG_5421](https://user-images.githubusercontent.com/90740221/187091651-deeb60dd-a08f-494d-ae4e-7becd6e04fc7.jpg)

**Comment by DanielnetoDotCom** [comment]
Try this

`cd /var/www/html/AVideo/install`

than

```
# php resetPlugins.php 
1 - Reset all plugins Parameters
2 - Reset CustomizeUser Plugin Parameters only
3 - Reset all plugins (Will also inactivate the plugins)
Choose an option: 
```
