### ISSUE TITLE
TV Guide

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#7049]
Anyone has a guide on how to setup the TV Guide?

**Comment by DanielnetoDotCom** [comment]
Hi

as an EPG link, you MUST use a [XMLTV File format ](http://wiki.xmltv.org/index.php/XMLTVFormat)

![image](https://user-images.githubusercontent.com/18009293/187196200-7873bb9f-6e5b-40ea-90fd-cf6ba4a90fd0.png)

**Comment by ganddser** [comment]
Strange I don't seem to have EPG. It seems to be missing from the menu.

**Comment by DanielnetoDotCom** [comment]
you will only see the EPG if you add a video link

![image](https://user-images.githubusercontent.com/18009293/187240532-e0b10088-c360-4553-84bf-3fa7218c6a90.png)

![chrome-capture-2022-7-29](https://user-images.githubusercontent.com/18009293/187240548-b3824235-cd04-4e10-8ece-3c8e1244f574.gif)

**Comment by ganddser** [comment]
Ah, got it. Thanks
