### ISSUE TITLE
MYSQL Cloud Hosting

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7050]
Want to test this out Just curious to see how fast apache will be and if the queries will process the same.

**Comment by JoshWho** [comment]
My issue is trying to transfer my already filled out database and it is not taking it when I try

**Comment by DanielnetoDotCom** [comment]
I am not sure what you mean.

did you already make a MySQL dump?

where are you seeing the double quotes issue?

again, if it is not on the same network, it may slow down your AVideo

**Comment by JoshWho** [comment]
What is the best way to do this? I tried using the site cloner but it doesn;t see the key I set

**Comment by DanielnetoDotCom** [comment]
the clone sites also use the mysqldump

In my opinion, mysqldump is the best tool to migrate mysql. if it is not working you may need to google for that

**Comment by JoshWho** [comment]
Im not sure what program you mean . I was just calling it a sql dump is that a program?

**Comment by GreenDragonTavern** [comment]
mysqldump -u username -p db_name > dump_name.sql

**Comment by JoshWho** [comment]
> mysqldump comes with MySQL by default
> 
> that is the official MySQL backup tool https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html

I c what u mean. I was thinking maybe there was some new tool out now LOL I guess it is still the same old fashion way. Have to do it by sql queries

**Comment by JoshWho** [comment]
I will try some stuff tonight with it.

**Comment by JoshWho** [comment]
You were right @DanielnetoDotCom . It is super slow doing it this way. Sad
