### ISSUE TITLE
Algorithm to discard bogus views

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7051]
**Is your feature request related to a problem? Please describe.**
Sometimes videos increase by dozens or hundreds of views. A quick glance at the data reveals that these are not views. A simple algorithm discards the noise.

**Describe the solution you'd like**
Group views by date, and by IP address. Discard duplicates from the same date.

Here we see access from an IPV6 address, many short accesses all on the same date (actually occurring within moments of each other), however, the simple algorithm - group by date - group by IP - discard duplicates (e.g. only keep 1 view per IP address per 24 hour period - like YouTube and other sites) - doing this will significantly de-noise the data.

<img width="1168" alt="Screen Shot 2022-08-28 at 10 39 37 PM" src="https://user-images.githubusercontent.com/11711050/187130766-f364c939-d80f-45d9-a440-a60a46b35167.png">

_NOTE: the pattern here, monotonically incrementing view durations starting from 1sec, 2sec, 3sec - probably reveals something else interesting,  I could only guess at it…

**Comment by DanielnetoDotCom** [comment]
For IPv6 support check this

![image](https://user-images.githubusercontent.com/18009293/187192297-ed58b671-84d8-4c60-839d-20f35d657bbd.png)

**Comment by walt93** [comment]
No iframes. Will install and see if it changes things. Thanks!
