### ISSUE TITLE
Another install question

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7063]
**Describe the question**
Daniel, on that machine I just had you move the install for - my buddies install... 

I didn't have you install an an encoder (forgot to mention it), but he wants one. I'm going through the install steps right now & it's failing but not emitting anything into videos/avideo.log.

What could be going wrong here?

**Screenshots**
<img width="1166" alt="Screen Shot 2022-08-29 at 12 55 26 PM" src="https://user-images.githubusercontent.com/11711050/187287723-f53a4983-35c8-40e5-ae07-a6fd8444cd49.png">

**Comment by DanielnetoDotCom** [comment]
I suspect your MySQL user cannot create tables. but check the apache error.log for more clues
