### ISSUE TITLE
AVIDEO INSTALLATION ON UBUNTU 20 LIVE PLUGIN ERROR

### ISSUE THREAD

**Issue by motechgroup** [WWBN/AVideo#7064]
**Describe the question**
Hello, I tried to install AVideo platform on my server, everything went well until I logged into my website, I ran into an error when I tried to create a livestream, kindly assist.

**Error Log**
array(4) { ["type"]=> int(1) ["message"]=> string(788) "Uncaught mysqli_sql_exception: Table 'avideo.LiveLinks' doesn't exist in /var/www/html/AVideo/plugin/LiveLinks/LiveLinks.php:95 Stack trace: #0 /var/www/html/AVideo/plugin/LiveLinks/LiveLinks.php(95): mysqli->query() #1 /var/www/html/AVideo/plugin/LiveLinks/LiveLinks.php(126): LiveLinks::getAllActive() #2 /var/www/html/AVideo/plugin/AVideoPlugin.php(973): LiveLinks->getLiveApplicationArray() #3 /var/www/html/AVideo/objects/functions.php(7707): AVideoPlugin::getLiveApplicationArray() #4 /var/www/html/AVideo/plugin/Live/Objects/LiveTransmition.php(316): getStatsNotifications() #5 /var/www/html/AVideo/plugin/Live/Objects/LiveTransmition.php(173): LiveTransmition->save() #6 /var/www/html/AVideo/plugin/Live/index.php(81): LiveTransmition::createTransmitionIfNeed() #7 {main} thrown" ["file"]=> string(51) "/var/www/html/AVideo/plugin/LiveLinks/LiveLinks.php" ["line"]=> int(95) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(788) "Uncaught mysqli_sql_exception: Table 'avideo.LiveLinks' doesn't exist in /var/www/html/AVideo/plugin/LiveLinks/LiveLinks.php:95
Stack trace:
#0 /var/www/html/AVideo/plugin/LiveLinks/LiveLinks.php(95): mysqli->query()
#1 /var/www/html/AVideo/plugin/LiveLinks/LiveLinks.php(126): LiveLinks::getAllActive()
#2 /var/www/html/AVideo/plugin/AVideoPlugin.php(973): LiveLinks->getLiveApplicationArray()
#3 /var/www/html/AVideo/objects/functions.php(7707): AVideoPlugin::getLiveApplicationArray()
#4 /var/www/html/AVideo/plugin/Live/Objects/LiveTransmition.php(316): getStatsNotifications()
#5 /var/www/html/AVideo/plugin/Live/Objects/LiveTransmition.php(173): LiveTransmition->save()
#6 /var/www/html/AVideo/plugin/Live/index.php(81): LiveTransmition::createTransmitionIfNeed()
#7 {main}
  thrown"
  ["file"]=>
  string(51) "/var/www/html/AVideo/plugin/LiveLinks/LiveLinks.php"
  ["line"]=>
  int(95)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}

**Comment by DanielnetoDotCom** [comment]
Looks like you enabled the LiveLinks plugin but did not install the tables

**Comment by motechgroup** [comment]
ooooh, thanks for the assistance, how do i install the tables?
