### ISSUE TITLE
user notification

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#7066]
![photo_2022-08-31_12-52-32](https://user-images.githubusercontent.com/85537931/187651454-29febb74-6db7-4bef-82b9-74cec5b7d4a2.jpg)
Hey
It is possible that uploads of new videos
will also be shown in the notification?

As I understand what is currently being shown is live broadcasts,
New comments, and likes for videos

Additional questions: Is it possible to send a message to all subscribers manually? Is it currently possible to send to each subscriber separately?

Thanks Eitan Live528

**Comment by DanielnetoDotCom** [comment]
I will probably add it in the future

**Comment by eitanwa** [comment]
Excellent. Thank you very much
