### ISSUE TITLE
Go Live Webcam stopped working

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7068]
For some reason it is doing this now

![e5ef75ae-c1e2-4930-8636-8cf18e91d1ac](https://user-images.githubusercontent.com/39392449/187789386-cc939e9b-2c28-4cb8-9fba-0157764ecabf.png)

**Comment by JoshWho** [comment]
I cant click the config either

**Comment by JoshWho** [comment]
Looking directly here it seems like it is not running https://webrtc.ypt.me/player/

**Comment by ganddser** [comment]
Confirming this is not only @JoshWho. Having the same issue.

**Comment by DanielnetoDotCom** [comment]
webrtc is not 100% but it should be back to work now

**Comment by JoshWho** [comment]
> webrtc is not 100% but it should be back to work now

Thank you. This is the golden feature that is gonna make this huge. The simplest way to go live with a chat built in is the best.

**Comment by JoshWho** [comment]
THis server for the webrtc is offline again. Can This be a standalone that I can host that way I can have a monitor on it that says when it is offline to reboot it?

**Comment by DanielnetoDotCom** [comment]
> THis server for the webrtc is offline again. Can This be a standalone that I can host that way I can have a monitor on it that says when it is offline to reboot it?

Currently this is not possible

**Comment by DanielnetoDotCom** [comment]
> THis server for the webrtc is offline again. Can This be a standalone that I can host that way I can have a monitor on it that says when it is offline to reboot it?

Not sure what happened, it reverted the fixes I have sent. 

I guess it is back now

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom

**Comment by JoshWho** [comment]
There is a code leak somewhere I can't seen to figure out where it is coming from. 

![a7f46e65-ceb6-4873-b9b3-d7f4f7e786c1](https://user-images.githubusercontent.com/39392449/187981196-23ccfd9c-b866-4cac-aef7-617288f15f6f.png)

I checked all my custom html boxes and do not see that anywhere.

**Comment by DanielnetoDotCom** [comment]
can you please check if it persists?

**Comment by JoshWho** [comment]
You can see it here https://www.joshwhotv.com/plugin/Live/webcamFullscreen.php

**Comment by JoshWho** [comment]
Yup yup no probs.

**Comment by JoshWho** [comment]
I dont see any update for Chat2

**Comment by DanielnetoDotCom** [comment]
this still not recommended as long as it still under development 

there is no guarantee it will work, but feel free to try
