### ISSUE TITLE
Send Recorded Encoder: not working

### ISSUE THREAD

**Issue by rapiz** [WWBN/AVideo#7069]
I have followed the steps, the videos are saved in /var/www/tmp, but they are not published. Could you help me?

**Comment by DanielnetoDotCom** [comment]
1. First, check if your videos are saved on /var/www/tmp
2. if they are check if they are going to the encoder
3. check AVideo and encoder logs

**Comment by rapiz** [comment]
1. Vide are saved, but to stop live, this is removed.
2. in my videos is listed but stay in "Coding"
3. I don't see error on logs

**Comment by DanielnetoDotCom** [comment]
what about the encoder?
check the encoder and encoder log

**Comment by DanielnetoDotCom** [comment]
if the file on the /var/www/tmp folder disappears when you finish the live stream that means the plugin requested the recorded file properly.

if the encoder is empty that means the plugin fails to send it to the encoder.

the error may be on the streamer or on the encoder. MUST be something on the log file.

try this, make a short live stream (30 seconds), paid attention to the exact time you stop it, for example.

if you stop it at 11:10 AM, share all the log between 11:09 and 11:11. MUST be something on it.

**Comment by rapiz** [comment]
************* - - [01/Sep/2022:17:15:31 +0200] "POST /plugin/Live/on_publish_done.php HTTP/1.0" 200 762 "-" "-"
************* - - [01/Sep/2022:17:15:31 +0200] "POST /plugin/Live/on_publish_done.php HTTP/1.0" 200 762 "-" "-"
************* - - [01/Sep/2022:17:15:31 +0200] "GET /Network/ping/1 HTTP/1.0" 200 5767 "-" "-"
************* - - [01/Sep/2022:17:15:31 +0200] "GET /Encoder/serverStatus HTTP/1.0" 200 6225 "-" "-"
************* - - [01/Sep/2022:17:15:31 +0200] "GET /Network/view/score.php HTTP/1.0" 200 6513 "-" "AVideoEncoderNeetwork ***********"
************* - - [01/Sep/2022:17:15:31 +0200] "GET /Network/view/getBestEncoder.php HTTP/1.0" 200 5742 "-" "-"
************* - - [01/Sep/2022:17:15:31 +0200] "GET /objects/status.json.php HTTP/1.0" 200 1446 "-" "AVideoStreamer_8089b5047d7ab0c321ffc0d669030cce"
************* - - [01/Sep/2022:17:15:31 +0200] "GET /Network/view/score.php HTTP/1.0" 200 6513 "-" "AVideoEncoderNeetwork ***************"
************* - - [01/Sep/2022:17:15:31 +0200] "GET /Network/view/getBestEncoder.php HTTP/1.0" 200 5742 "-" "-"
************* - - [01/Sep/2022:17:15:31 +0200] "POST /login?user=*******&pass=******&encodedPass=1 HTTP/1.0" 200 6797 "-" "-"
************* - - [01/Sep/2022:17:15:31 +0200] "POST /Encoder/queue HTTP/1.1" 200 5583 "-" "-"
************* - - [01/Sep/2022:17:15:31 +0200] "POST /plugin/Live/on_record_done.php HTTP/1.0" 200 1448 "-" "-"
