### ISSUE TITLE
Top Notch doesn't translate to Hebrew

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7071]
The gallery Top Notch Heading doesn't translate to Hebrew, the rest title are translating fine.

![Screen Shot 5782-13-05 at 12 45 24](https://user-images.githubusercontent.com/58882903/187885029-5c17550c-1638-4b69-af33-1bfba25f3b64.jpg)

**Comment by DanielnetoDotCom** [comment]
I am not finding this word.

where exactly is it?

**Comment by guymass** [comment]
Its the first Heading field of the  Gallery.
