### ISSUE TITLE
Uncaught ReferenceError: getCookie is not defined

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7072]
For some reason on my second site under https://fetube.flatearth.co.il I am getting this error now trying to watch any video. They are in constant state of buffering it appears. What is strange is that my main site and this site are basically copies as far as I know and have the same code, so I am not sure where is this java error comes from.  A quick google search show its a coding error so idk. Here is a screen shot of the browser's console:

![Screen Shot 5782-13-05 at 15 07 36](https://user-images.githubusercontent.com/58882903/187912698-cec82e7b-7590-4a44-9004-aae1af26c05f.jpg)

My main site works just fine while this domain has errors, both are fully updated.

**Comment by DanielnetoDotCom** [comment]
Hi

for some reason, your JS files are loading out of order. please try this update

**Comment by guymass** [comment]
Thank Daniel, videos are working now but  I still see that error message:
![Screen Shot 5782-13-06 at 2 36 25](https://user-images.githubusercontent.com/58882903/188030034-2aa780aa-3290-4d56-a77b-1484f1235ffc.jpg)

**Comment by DanielnetoDotCom** [comment]
this should fix it. thanks

**Comment by guymass** [comment]
Now I have this:

![Screen Shot 5782-13-06 at 20 45 31](https://user-images.githubusercontent.com/58882903/188209302-a9673939-ce4d-4dd9-9393-cbe23ba1d1d2.jpg)

and video is hanging again.

**Comment by DanielnetoDotCom** [comment]
where is it?

it is a videojs error, it is not really my code.

there is any previews error?
how can I reproduce that?

**Comment by guymass** [comment]
IDK I can't duplicate its gone after latest update. For now it seems to be working again, I don't see that error anymore. So I don't know to tell you really what caused it but its probably fixed now in the update.
