### ISSUE TITLE
Comment order

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#7073]
Can you implement comment order? I'd like to see a options that displays oldest, newest, top for reordering the comments.

**Comment by DanielnetoDotCom** [comment]
Hi, sure it will be implemented, but I do not have an ETA now.

if you need an ETA you can sponsor that feature.

**Comment by fakeologist** [comment]
How much does it cost to sponsor?

**Comment by DanielnetoDotCom** [comment]
Please email me directly so I can give you a quote
