### ISSUE TITLE
LIVE STREAMING NOT WORKING

### ISSUE THREAD

**Issue by motechgroup** [WWBN/AVideo#7074]
**Describe the question**
I installed the platform properly, tested everything working very fine, but when i tried to go live using vmix i ran into this error yet my internet connection is stable, what could be the problem?

**Screenshots**
Provide some screenshots to help us understand and explain your problem.
![error](https://user-images.githubusercontent.com/57249534/187977843-66782087-b84c-4a0c-97a4-99fad012c601.jpg)

**Comment by DanielnetoDotCom** [comment]
or you did not install/start the Nginx RTMP correctly or something is blocking your port
