### ISSUE TITLE
Getting lots of request for the Live STream Notifications to be cleared

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7075]
This is the most asked question I am getting from everyone. Can they clear the Live notifications the same as comment and video notifications?

![2775fde8-e37b-4641-bb9d-0eb27416dee6](https://user-images.githubusercontent.com/39392449/188014656-a3e41b28-aa91-44f6-915e-4c8df5a14b49.png)

**Comment by DanielnetoDotCom** [comment]
Not really, but I will add an option to not receive them

**Comment by DanielnetoDotCom** [comment]
The live plugin doNotProcessNotifications should now disable the top notification

![image](https://user-images.githubusercontent.com/18009293/188151807-d9510f30-132d-4ba0-96d0-dfcccc939a3f.png)

**Comment by JoshWho** [comment]
> The live plugin doNotProcessNotifications should now disable the top notification
> 
> ![image](https://user-images.githubusercontent.com/18009293/188151807-d9510f30-132d-4ba0-96d0-dfcccc939a3f.png)

I have that enabled but it still shows

**Comment by JoshWho** [comment]
All fixed. The last git pull did it
