### ISSUE TITLE
Can we Make this Say "Go Live" please Or Is there a Place to Edit this?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7076]
In the notification drop down the Go Live doesn't show any text even for hover .

![download (29)](https://user-images.githubusercontent.com/39392449/188015033-39ae1601-921e-498e-bdd4-88c03fe85435.png)

**Comment by walt93** [comment]
I’d try searching the string through the source code. Most of the strings it seem go through localization as you will see when you dig into it. Search for the exact string surrounded by quotes.

**Comment by DanielnetoDotCom** [comment]
@JoshWho you are right, thanks for noticing that. here is the fix

**Comment by JoshWho** [comment]
Now that I have DO not Show Live Notifications I do not have a Go Love option anymore. Could you please add the webcam go live to the upload dropdown menu please @DanielnetoDotCom

**Comment by JoshWho** [comment]
I just made one for right now and disabled the ones in the upload menu.

Only downside to this method is now the circle is not flashing red and guest users will be able to see these links 

![5e22b8fc-b236-45c5-b2ac-0a2d78db3162](https://user-images.githubusercontent.com/39392449/188207733-925c09ec-069b-435f-a833-cdbced146908.png)

**Comment by DanielnetoDotCom** [comment]
is webcam working well for you?

I am not sure if it is ready

**Comment by JoshWho** [comment]
It works great.

I figured a solution

![c6010215-65d7-4b09-9451-1159f4a9e032](https://user-images.githubusercontent.com/39392449/188209287-11d8a401-eb1c-4405-ac3d-7f133d38a0b7.png)

**Comment by JoshWho** [comment]
![1df9a963-49fe-477a-adc9-4c8930fd8186](https://user-images.githubusercontent.com/39392449/188209509-26d273c9-be35-47b6-a7a2-f6c4268ce1ff.png)
