### ISSUE TITLE
Cdn storage and cdn caching 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#7078]
Can you tell me the difference between the two?

If you mirror your site with storage, do you need the cdn caching feature?

Do they go together?

Has anyone noticed great speed improvements?

**Comment by fakeologist** [comment]
Good explanation. 
Do the vod files replicate automatically?
I read you can add storage regions but not subtract them. Why is this?

**Comment by DanielnetoDotCom** [comment]
> Do the vod files replicate automatically?

Correct

>  I read you can add storage regions but not subtract them. Why is this?

Also correct

**Comment by fakeologist** [comment]
Why can't they be removed?

**Comment by DanielnetoDotCom** [comment]
To be honest I am not sure, I guess this is a hardware limitation of the data center
