### ISSUE TITLE
Ad server seems to only serve ads from the first campaign

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7079]
**Describe the question**
You can add multiple campaigns to the ad server. It only seems to play from the first. How do I get it to randomly pull from the different campaigns? Is that even possible or are they meant to drain serially? That’s the behavior I’m seeing - and it’s boring - I want to mix it up. 

See below, I had to disable the first campaign to get ads to roll from the second, etc. 
![B1AA9903-E5B3-487E-B2C3-C3FF94748D7F](https://user-images.githubusercontent.com/11711050/188042644-3495c791-a113-405c-b8c2-6ecc55cfaf70.png)

**Comment by DanielnetoDotCom** [comment]
what exactly campaign it is getting the ads from?

I can see you have 4 active campaign

**Comment by walt93** [comment]
It seems to only run ads from the first active campaign in the list. You see the last three active campaigns stuck at 10,000. Campaign #1 drained a bunch, then I deactivated it and it drained three off of the Campaign #2, then I deactivated it, and it started draining from Campaign #3.

I had assumed it would be random or round-robin order, but it seems to remain stuck on the first.

**Comment by lnc-greg** [comment]
Would be interested to have some informations regarding this too :)

**Comment by walt93** [comment]
This issue seems forgotten, re-opening so it's fresh.

**Comment by DanielnetoDotCom** [comment]
Hi

I just checked on my side and the ads are playing as expected.

Make sure you use the VMAP URL and your campaigns will be random

http://yoursite.com/plugin/AD_Server/VMAP.php
