### ISSUE TITLE
Is there a way to make the chat more brighter so it can be read easier? Webcam Live

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7080]
![download (30)](https://user-images.githubusercontent.com/39392449/188203715-05f331fa-ca4d-4f93-8f09-6e63c7d37913.png)

**Comment by DanielnetoDotCom** [comment]
I am sending some updates to the streamer and also to the Chat2 (version 11.3) plugin that may help with it

**Comment by JoshWho** [comment]
Looks great. Thank you @DanielnetoDotCom
