### ISSUE TITLE
Live Webcam page view by guest view goes to 403 should Redirect to the login page for guests 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7082]
Currently if a guest clicks it https://www.joshwhotv.com/plugin/Live/webcamFullscreen.php?avideoIframe=1

 it will go to a 403 page any way to make it say you must be logged in or something?

![download (32)](https://user-images.githubusercontent.com/39392449/188225087-f01b2ae7-4415-4d7e-9a9f-ad0a1e75ab8d.png)

**Comment by DanielnetoDotCom** [comment]
the user MUST have stream permission

![image](https://user-images.githubusercontent.com/18009293/188233800-b21b222a-8e83-4d86-81ae-18fcdd18654c.png)

**Comment by JoshWho** [comment]
> the user MUST have stream permission
> 
> ![image](https://user-images.githubusercontent.com/18009293/188233800-b21b222a-8e83-4d86-81ae-18fcdd18654c.png)

Correct I was saying it should have a page that redirects to the login instead of the 403. people might think they have done something bad. 403 is error code for ban

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom
