### ISSUE TITLE
Kubernetes, Ingress and HTTPS but CSS, JS are http

### ISSUE THREAD

**Issue by Sharrnah** [WWBN/AVideo#7084]
**Describe the question**
I now have installed this on my Kubernetes Cluster.
Since this uses a LoadBalancer and NGINX Ingress Controller, i need the application inside the container to run in HTTP mode.
The Port 80 is then routed through the Ingress Controller which makes it accessible over HTTPS.

My issue now is that the HTML seems to think it is HTTP and all links inside it for Styling and Javascript are tried to be loaded by HTTP which fails.

So currently the Website is unusable.

Is there something i need to change so the correct links are used?

Also for this to work with the Ingress Controller, i had to overwrite the apache config with this one:

```
<VirtualHost *:80>
    ServerName ${SERVER_NAME}
    ServerAdmin ${CONTACT_EMAIL}
    DocumentRoot "/var/www/html/AVideo"

    ErrorLog /dev/stderr
    TransferLog /dev/stdout
</VirtualHost>

<Directory /var/www/html/AVideo/>
    Options Indexes FollowSymLinks
    XSendFile on
    XSendFilePath /var/www/html/AVideo/
    AllowOverride All
    Require all granted
    Order Allow,Deny
    Allow from All
</Directory>
```

because otherwise it always redirected to HTTPS which resulted in an endless redirect loop.

I also already tried to change the configuration.php and hardwire "https://" in there, It changed the HTML a little bit, but its still mostly broken.
configuration.php change: (notice the commented out line and my change below that)
```php
//...
$global['logfile'] = '/var/www/html/AVideo/videos/avideo.log';
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) {
    // get the subdirectory, if exists
    $file = str_replace("\\", "/", __FILE__);
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), $file);
    //$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
    $global['webSiteRootURL'] = "https://".$_SERVER['SERVER_NAME'].$subDir;
}else{
//...
```

**Screenshots**
![yd3hHvO026](https://user-images.githubusercontent.com/55756126/188240898-5252901a-7650-47a5-8f7c-a2ceeb96e8aa.png)

**Comment by DanielnetoDotCom** [comment]
replace the whole if/else

```
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) {
    // get the subdirectory, if exists
    $file = str_replace("\\", "/", __FILE__);
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), $file);
    //$global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
    $global['webSiteRootURL'] = "https://".$_SERVER['SERVER_NAME'].$subDir;
}else{
```
with this only 

`$global['webSiteRootURL'] = "https://yoursitedomain.com/";`
