### ISSUE TITLE
Is there a way to change Default Live Stream Text to "I'm Live" with the date timestamp

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7086]
Instead of the default saying Untitled Stream have it say "I'm Live" or something like that please.

**Comment by DanielnetoDotCom** [comment]
where?

**Comment by JoshWho** [comment]
I am talking about what nginx saves the video file title when it gets saved to your channel.

Default currently says Untitled Stream with a date stamp on the ende. I am saying to just change the file name to Im Live  for the default text instead of Untitled.

**Comment by DanielnetoDotCom** [comment]
I guess this should do the trick

**Comment by JoshWho** [comment]
THank you
