### ISSUE TITLE
WOWZa Stream Target to AVideo Live Stream

### ISSUE THREAD

**Issue by helpgizmo** [WWBN/AVideo#7087]
We stream to the the WOWZa Streaming Engine and we restream to various platforms. I added the RTMP stream to the AVideo, the audio is great, but the video remains frozen. Is there something I'm missing as to why the video doesn't flow beyond the initial 1 to 2 seconds? The live video is frozen, but after it sends to the recorder, the video is good.

**Comment by DanielnetoDotCom** [comment]
check the output resolution, try to make it 720 p max

if you cannot try the adaptive resolution https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream
