### ISSUE TITLE
How to permanently disable embeds on my site?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7089]
**Describe the question**
Looking at my analytics I see thousands of connections coming from someone embedding a ton of my videos. Again. He's doing multiple videos.

I want to make them go away.

What can I disable to stop them doing this? Which setting or where do I go in the code to simply cripple the /embed endpoint?

----

ANSWER: AVideo/plugin/PlayerSkins/contextMenu.php
  uses contextMenuCopyEmbedCode to disable
  this is in the plugin Playerskins - disable it here

<img width="643" alt="Screen Shot 2022-09-04 at 5 00 31 PM" src="https://user-images.githubusercontent.com/11711050/188338637-d7a6fd0a-72f5-4d9b-bb39-66f40fa561e7.png">

@DanielnetoDotCom please note that the option "contextMenuDisableEmbedOnly" which appears here in the Playerskins plugin - does not occur anywhere the source code - maybe a leftover artifact?

----
I'm not having any luck searching the source code for where the /embed route is handled to disable it entirely.

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/SecureVideosDirectory-Plugin#restrict-embed-videos

**Comment by walt93** [comment]
Thanks!
