### ISSUE TITLE
Although userMustBeLoggedIn switch is on Program (Playlists) plugin play videos for users who do not logged in. 

### ISSUE THREAD

**Issue by ujtwr** [WWBN/AVideo#7091]
When userMustBeLoggedIn switch is on, video should be  able to be played only users with logged in. But users who do not logged in can play videos listed in playlist.

for example:
https://{site-url}/plugin/PlayLists/player.php?playlists_id=547

We can get This url from "play all" link at Program tab.

How can I limit all videos only for users with logged in?

**Comment by DanielnetoDotCom** [comment]
can you please check the update that I just sent

**Comment by ujtwr** [comment]
Thank you for so quick response and fix.

I made sure new version.
