### ISSUE TITLE
"ReferenceError: Can't find variable: $" after update 12.1

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#7095]
Hello,

After updating to 12.1, the Ads plugin is not displaying the Google Adsense ads anymore, causing the javascript to break:

Message from the console:

`"ReferenceError: Can't find variable: $"`

This is due this little code placed after the Google Adsense code:

```
<script doNotSepareteTag >
 $(function () {startGoogleAd('#adContainer6316226bea4f2');});
</script>

```
Is it part of AVideo or Google Adsense?

**Comment by DanielnetoDotCom** [comment]
can you please check if that update fixes it for you?

**Comment by swimitup** [comment]
Hi Daniel, yes, the update fixed.
Thanks and have a great week.
