### ISSUE TITLE
Notification Live Red Dot needs to Say "Go Live"

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7096]
Just noticed this.  

![72472853-63d5-4789-9c58-8979f6280613](https://user-images.githubusercontent.com/39392449/188508538-7251b226-e337-4cfe-b8f8-fafc928754e3.png)

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by JoshWho** [comment]
Yup looks good now

![0d14ee86-427f-4907-8187-5f75d895dd07](https://user-images.githubusercontent.com/39392449/189247404-507a5e1a-dbfc-4918-aa22-ec170837f4aa.png)

Thank you @DanielnetoDotCom
