### ISSUE TITLE
AVideo API - Oembed

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#7097]
Does AVideo have an API or oembed mechanism to facilitate grabbing information for a video to store locally in another application? That would include the video cover image. Just like YouTube, Vimeo, Twitch, Dailomotion etc. where only the URL is necessary on a social media post. This way you get a YouTube quality post on social media with an AVideo URL...https://avideo.site.com/v/10 as example would be no different than posting this: https://youtu.be/E_eCOG8vQYg

Thank you...

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/WWBN/AVideo/wiki/AVideo-Platform-API

**Comment by GreenDragonTavern** [comment]
Thanks for link. Did not see anything related to getting embed information based on video url. Was thinking more in line with what YouTube gives you...example below:

curl 'https://www.youtube.com/oembed?format=json&url=https://www.youtube.com/watch?v=uXBDgLglFig'

with YouTube returning this:

{"title":"BUILDING A DIY BASS GUITAR SYNTHESIZER WITH A SID CHIP","author_name":"LOOK MUM NO COMPUTER","author_url":"https://www.youtube.com/c/LOOKMUMNOCOMPUTER","type":"video","height":113,"width":200,"version":"1.0","provider_name":"YouTube","provider_url":"https://www.youtube.com/","thumbnail_height":360,"thumbnail_width":480,"thumbnail_url":"https://i.ytimg.com/vi/uXBDgLglFig/hqdefault.jpg","html":"\u003ciframe width=\u0022200\u0022 height=\u0022113\u0022 src=\u0022https://www.youtube.com/embed/uXBDgLglFig?feature=oembed\u0022 frameborder=\u00220\u0022 allow=\u0022accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\u0022 allowfullscreen title=\u0022BUILDING A DIY BASS GUITAR SYNTHESIZER WITH A SID CHIP\u0022\u003e\u003c/iframe\u003e"}

**Comment by DanielnetoDotCom** [comment]
What about this?


<link href="https://demoavideocom.cdn.ypt.me/oembed/?format=json&url=https%3A%2F%2Fdemo.avideo.com%2Fview%2F" rel="alternate" type="application/json+oembed" />

<link href="https://demoavideocom.cdn.ypt.me/oembed/?format=xml&url=https%3A%2F%2Fdemo.avideo.com%2Fview%2F" rel="alternate" type="application/xml+oembed" />

**Comment by GreenDragonTavern** [comment]
Having issues embedding AVideo videos in WordPress.

Your elements looks like this:

<link href="https://demoavideocom.cdn.ypt.me/oembed/?format=json&url=https%3A%2F%2Fdemo.avideo.com%2Fview%2F%3Fv%3D55" rel="alternate" type="application/json+oembed" />
 
<link href="https://demoavideocom.cdn.ypt.me/oembed/?format=xml&url=https%3A%2F%2Fdemo.avideo.com%2Fview%2F%3Fv%3D55" rel="alternate" type="application/xml+oembed" />

Shouldn't ombed look like this (per specification at [oembed.com - Discovery](https://oembed.com/#section4):

4. Discovery

oEmbed providers can choose to make their oEmbed support discoverable by adding [<link>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link) elements to the head of their existing (X)HTML documents or by setting [Link headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link).

Your same elements per their documentation:

<link rel="alternate" type="application/json+oembed"
  href="https://demoavideocom.cdn.ypt.me/oembed/?url=https%3A%2F%2Fdemo.avideo.com%2Fview%2F%3Fv%3D55&format=json"
  title="I Will Love | Hillsong (Featuring Miriam Webster)" />

<link rel="alternate" type="text/xml+oembed"
  href="https://demoavideocom.cdn.ypt.me/oembed/?url=https%3A%2F%2Fdemo.avideo.com%2Fview%2F%3Fv%3D55&format=xml"
  title="I Will Love | Hillsong (Featuring Miriam Webster)" />

Tried curl using your format:

https://demoavideocom.cdn.ypt.me/oembed/?format=json&url=https%3A%2F%2Fdemo.avideo.com%2Fview%2F%3Fv%3D55

and got nothing, below is modified version that did give back <oembed>

curl https://demo.avideo.com/oembed/?url=https%3A%2F%2Fdemo.avideo.com%2Fview%2F%3Fv%3D55&format=json

<oembed>
  <version>1.0</version>
  <type>rich</type>
  <width>480</width>
  <height>360</height>
  <title>I Will Love | Hillsong (Featuring Miriam Webster)</title>
  <url>https://demo.avideo.com/video/55/i-will-love-hillsong-featuring-miriam-webster-</url>
  <provider_name>AVideo Platform Demo</provider_name>
  <provider_url>https://demo.avideo.com/</provider_url>
  <html>&lt;div class=&quot;embed-responsive embed-responsive-16by9&quot;&gt;&lt;iframe width=&quot;640&quot; height=&quot;360&quot; style=&quot;max-width: 100%;max-height: 100%; border:none;&quot; src=&quot;https://demo.avideo.com/videoEmbed/55/i-will-love-hillsong-featuring-miriam-webster-?modestbranding=1&amp;showinfo=1&amp;autoplay=&amp;controls=1&amp;loop=&amp;mute=&amp;t=0&amp;objectFit=&quot; frameborder=&quot;0&quot; allowfullscreen=&quot;allowfullscreen&quot; allow=&quot;autoplay&quot; scrolling=&quot;no&quot;&gt;iFrame is not supported!&lt;/iframe&gt;&lt;/div&gt;</html>
</oembed>

You have <type> as **rich** versus **video**, is there a specific reason? It shows as a link to an AVideo video where it should be playable within the embed itself.

Many thanks again for all...

**Comment by DanielnetoDotCom** [comment]
I am not sure what is the issue you are referring to
