### ISSUE TITLE
Charts page: Uncaught Error

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#7099]
Hello again,

If you try to access your charts page:

https://YOURDOMAIN/charts

Maybe you will see an Uncaught Error like this at the end of the page:

```
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(758) "Uncaught Error: Call to a member function execute() on bool in YOUR-SITE-PATH/objects/mysql_dal.php:184
Stack trace:
#0 YOUR-SITE-PATH/plugin/Live/Objects/LiveTransmitionHistory.php(346): sqlDAL::readSql()
#1 YOUR-SITE-PATH/plugin/Live/report.php(20): LiveTransmitionHistory::getAllFromUser()
#2 YOUR-SITE-PATH/plugin/Live/Live.php(1457): include('/var/www/videos...')
#3 YOUR-SITE-PATH/plugin/AVideoPlugin.php(108): Live->getChartContent()
#4 YOUR-SITE-PATH/view/charts_body.php(41): AVideoPlugin::getChartContent()
#5 YOUR-SITE-PATH/view/charts.php(20): include('/var/www/videos...')
#6 {main}
  thrown"
  ["file"]=>
  string(58) "YOUR-SITE-PATH/objects/mysql_dal.php"
  ["line"]=>
  int(184)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}

```
It seems any or some of the mysql calls are returning false. Or there's a video/info that does not exist anymore and AVideo tries to query it.

Any ideas?

**Comment by DanielnetoDotCom** [comment]
you may have missing tables. check your plugins page.

if you not find anything you may need to share more from your logs

**Comment by swimitup** [comment]
SQL query from /plugin/Live/Objects/LiveTransmitionHistory.php file, line 346:

`SELECT *, (SELECT count(id) FROM live_transmition_history_log WHERE live_transmitions_history_id=lth.id ) as total_viewers_from_history FROM live_transmitions_history lth WHERE 1=1 AND (users_id = 1 OR users_id_company = 1) AND (total_viewers>0 OR (SELECT count(id) FROM live_transmition_history_log WHERE live_transmitions_history_id=lth.id )>0) ORDER BY `created` DESC , `total_viewers` DESC , `max_viewers_sametime` DESC LIMIT 0, 30
`
`ERROR 1054 (42S22): Unknown column 'users_id_company' in 'where clause'
`
But the column exists on MySQL:

```
mysql> show columns from live_transmitions_history;
+----------------------+--------------+------+-----+---------+----------------+
| Field                | Type         | Null | Key | Default | Extra          |
+----------------------+--------------+------+-----+---------+----------------+
| id                   | int          | NO   | PRI | NULL    | auto_increment |
| title                | varchar(255) | YES  |     | NULL    |                |
| description          | text         | YES  |     | NULL    |                |
| key                  | varchar(255) | NO   |     | NULL    |                |
| created              | datetime     | YES  |     | NULL    |                |
| modified             | datetime     | YES  |     | NULL    |                |
| users_id             | int          | NO   | MUL | NULL    |                |
| live_servers_id      | int          | YES  | MUL | NULL    |                |
| finished             | datetime     | YES  |     | NULL    |                |
| domain               | varchar(255) | YES  |     | NULL    |                |
| json                 | text         | YES  |     | NULL    |                |
| max_viewers_sametime | int unsigned | YES  |     | NULL    |                |
| total_viewers        | int unsigned | YES  |     | NULL    |                |
| users_id_companny    | int          | YES  | MUL | NULL    |                |
+----------------------+--------------+------+-----+---------+----------------+
14 rows in set (0.00 sec)

```

**Comment by swimitup** [comment]
oooooh, mistypo on the column name...

users_id_companny versus users_id_company.

**Comment by DanielnetoDotCom** [comment]
As I told you, you have missing updates

https://github.com/WWBN/AVideo/blob/master/plugin/Live/install/updateV10.5.sql

**Comment by DanielnetoDotCom** [comment]
the fix must be done directly into the database

this command should do the trick

sudo mysql -u root -e "USE [yourAvideoDatabase]; `ALTER TABLE live_transmitions_history RENAME COLUMN users_id_companny TO users_id_company`;"
