### ISSUE TITLE
Unable to play a video

### ISSUE THREAD

**Issue by niladrishekhar** [WWBN/AVideo#7101]
I am locally hosting it - not sharing over internet and just using it to organize my videos - can you please help or guide me in the right direction - 

The page works fine but when i click on a video I get the following error -

array(4) { ["type"]=> int(1) ["message"]=> string(678) "Uncaught mysqli_sql_exception: Table 'avideos.videos_VR360' doesn't exist in /var/www/AVideo/plugin/VR360/Objects/VideosVR360.php:48 Stack trace: #0 /var/www/AVideo/plugin/VR360/Objects/VideosVR360.php(48): mysqli->query() #1 /var/www/AVideo/plugin/VR360/Objects/VideosVR360.php(32): VideosVR360::getFromVideoDb() #2 /var/www/AVideo/plugin/VR360/Objects/VideosVR360.php(59): VideosVR360->loadFromVideo() #3 /var/www/AVideo/objects/functions.php(883): VideosVR360::isVR360Enabled() #4 /var/www/AVideo/objects/video.php(2896): canUseCDN() #5 /var/www/AVideo/view/modeYoutube.php(217): Video::getSourceFile() #6 /var/www/AVideo/view/index.php(51): require('...') #7 {main} thrown" ["file"]=> string(52) "/var/www/AVideo/plugin/VR360/Objects/VideosVR360.php" ["line"]=> int(48) } array(4) { ["type"]=> int(1) ["message"]=> string(678) "Uncaught mysqli_sql_exception: Table 'avideos.videos_VR360' doesn't exist in /var/www/AVideo/plugin/VR360/Objects/VideosVR360.php:48 Stack trace: #0 /var/www/AVideo/plugin/VR360/Objects/VideosVR360.php(48): mysqli->query() #1 /var/www/AVideo/plugin/VR360/Objects/VideosVR360.php(32): VideosVR360::getFromVideoDb() #2 /var/www/AVideo/plugin/VR360/Objects/VideosVR360.php(59): VideosVR360->loadFromVideo() #3 /var/www/AVideo/objects/functions.php(883): VideosVR360::isVR360Enabled() #4 /var/www/AVideo/objects/video.php(2896): canUseCDN() #5 /var/www/AVideo/view/modeYoutube.php(217): Video::getSourceFile() #6 /var/www/AVideo/view/index.php(51): require('...') #7 {main} thrown" ["file"]=> string(52) "/var/www/AVideo/plugin/VR360/Objects/VideosVR360.php" ["line"]=> int(48) }

**Comment by DanielnetoDotCom** [comment]
disable VR360 plugin or install its tables
