### ISSUE TITLE
videoresolutionswitcher stopped working

### ISSUE THREAD

**Issue by mcferdev** [WWBN/AVideo#7102]
**Describe the bug**
I have the plugin and it was working for a year. But recently some user reported that was not possible to change resolution of videos. I tried and that´s true. I uploaded a FHD video and it just show "LOW" when plays the video. When I go to myvideos, it says FHD video and there are many resolutions to download. Also, I checked in the configs and it´s active. I already tried to turn off and then turn on, but the problem remains.
I tested with MP4 format. 

My server runs 11.4 version of AVideo and 1.1 of Videoresolutionswitcher

**To Reproduce**

**Expected behavior**
Appear the LOW, HD, etc...
**Error Logs**
Provide the log files at the moment you found the issue.
If you are not sure how to find the log file, please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Screenshots**

![image](https://user-images.githubusercontent.com/17338668/188735862-844a5d08-d89c-4935-ae22-d6dd860a41e2.png)
![image](https://user-images.githubusercontent.com/17338668/188735970-6381f0c9-1413-4767-a026-7c0971683289.png)
![image](https://user-images.githubusercontent.com/17338668/188736083-ac755627-17cd-4ab8-9afd-c2666d930f6b.png)
![image](https://user-images.githubusercontent.com/17338668/188736498-7969ab6d-fefe-4203-afde-74d50b55d908.png)

**Desktop (please complete the following information):**
Tested with Chrome and IE Edge

**Comment by DanielnetoDotCom** [comment]
Hi, 

1. I strongly recommend you upgrade your site to version 12.1 https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform
2. Then install all plugins missing tables, even if you're not using them.

**Comment by mcferdev** [comment]
Ok. Thanks for answer me so fast. I will try it and so, I come back to give a feedback.

Thanks.
