### ISSUE TITLE
Sitemap.xml question

### ISSUE THREAD

**Issue by SergejGrin** [WWBN/AVideo#7104]
Please explain where is the sitemap.xml file? I click - create a sitemap, I get the message: Congratulations! File created!
But for some reason I don’t see it in the site folder and Google search engine doesn’t index it.
<img width="1254" alt="scrin 12022-09-07" src="https://user-images.githubusercontent.com/59236880/188894006-cf49f49e-004f-42da-8ec8-4a217a86c34f.png">

**Comment by DanielnetoDotCom** [comment]
you will not find any file, but you can access it with 

https://yourdomain.com/sitemap.xml

**Comment by SergejGrin** [comment]
Thank you Daniel! I do just that, I wanted to review this file and make a correction. It turns out it's impossible..
