### ISSUE TITLE
Files which should be downloadable, are not.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7105]
**Describe the bug**
Everything appears to be clear to download the file, yet, no download links show for the media (only for the images)

This is acting very sketchy, some files can download, some cannot, I can't spot the pattern - everything should be enabled for downloading everything on the site.

<img width="1742" alt="Screen Shot 2022-09-07 at 4 13 55 PM" src="https://user-images.githubusercontent.com/11711050/188999496-984fce05-98c5-4440-9953-42bb75df33e6.png">

**Comment by DanielnetoDotCom** [comment]
Check your log when you access the video.

also, where are you clicking to try to download it?

**Comment by walt93** [comment]
You can see here on the page that there is no button to download the file.

Also from the videos page, under sharing, there is no button to download the file.

Also from the videos list, there is no button to download the file. Although frankly this has never worked very well, only showing up maybe 10% of the time?

I am honestly not sure where/when to look for what in the logs, could you be more precise?

**Comment by DanielnetoDotCom** [comment]
> I am not sure what to look for what in the logs, could you be more precise?

Sorry I cannot, I also have no idea what is the issue. I need to see the log to see if I can find something weird

> This is a separate issue, it has been long standing as well. All of the videos you see here should be downloadable, but only one has a download link.

I suspect your problem is about the video format. 
just to make it clear. embed videos cannot be downloaded.

Also, check the category

![image](https://user-images.githubusercontent.com/18009293/189668065-03201826-e18d-42f6-8188-67d27abe85c1.png)

**Comment by walt93** [comment]
From mysql I tried `select name from categories where allow_download=0` and verified that all but a handful of categories are set to true, so this wasn't it. :-(

What user action should I try to catch the log around, just loading /mvideos, or ___?

**Comment by DanielnetoDotCom** [comment]
With this update, if the download button is not available you may see a comment on the HTML file with the reason why

just search for this `<!-- canDownloadVideosFromVideo`
