### ISSUE TITLE
I cannot figure out how to "Go Live"

### ISSUE THREAD

**Issue by fnbsullivan** [WWBN/AVideo#7106]
It is not clear to me how to "go live" with streaming

- I have successfully configured OBS and am able to "start streaming"
- When I visit the live URL the video shows offline
- I am able to click the video to get it to play, however the video continues to show offline in the upper left

Is this a bug?  Or am I missing something?

**Comment by DanielnetoDotCom** [comment]
Hi, 

how is your stats page? for example this the the demo site stats page https://demo.avideo.com:8443/stats

does the video play even show offline?

**Comment by fnbsullivan** [comment]
![image](https://user-images.githubusercontent.com/87485587/189436828-e29b24e8-9e54-4634-b118-5fbeb90b407f.png)
Yes, the video will play.

**Comment by DanielnetoDotCom** [comment]
Hi, if your stats is under HTTPS and your video plays the only missing part is probably the notification.

for the notification your socket is necessary 

https://github.com/WWBN/AVideo/wiki/Socket-Plugin

**Comment by fnbsullivan** [comment]
![image](https://user-images.githubusercontent.com/87485587/189447493-cd4fd8d8-fc48-446d-8dd2-e53c018bf943.png)
 
Got socket working.... still no "online" indication.  Also purchased the plugin to record from live and I don't see that working. Not sure if that's related.

Thank you!

**Comment by DanielnetoDotCom** [comment]
I do not think it is related, to make the record work you need to uncomment the recorder part on the nginx.conf

https://github.com/WWBN/AVideo/wiki/Record-Live-Stream#step-3

On the live plugin, test the stats page

![chrome-capture-2022-8-9](https://user-images.githubusercontent.com/18009293/189448339-f43547bc-c359-4738-9641-f956b3df379c.gif)

**Comment by fnbsullivan** [comment]
![image](https://user-images.githubusercontent.com/87485587/189448780-0ea094af-c7bf-4020-98ff-ed2e47296ddc.png)
 
SUCCESS for me too, but still shows offline

**Comment by DanielnetoDotCom** [comment]
ok, all seems right. 

the last shot is to check the JS console for javascript errors.

also, check if your AVideo is up to date

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by fnbsullivan** [comment]
![image](https://user-images.githubusercontent.com/87485587/189449997-5501a177-e543-41a5-8740-f1b1fbdc70b7.png)

I updated as well.

**Comment by DanielnetoDotCom** [comment]
I am not seeing any problem, 

make sure your live is listed clear the cache and try again.

![image](https://user-images.githubusercontent.com/18009293/189450431-27e1e132-e284-4e61-8eae-fe3fd1df1563.png)

**Comment by fnbsullivan** [comment]
Cleared cache... 

![image](https://user-images.githubusercontent.com/87485587/189451718-18bba6cc-f324-45e7-b867-c386162c270c.png)

Not sure what else to do...

**Comment by DanielnetoDotCom** [comment]
1. If you are up to date (AVideo and plugins)
2. If you did not "cheat" the on_publish on the nginx.conf
3. if there is no JS error when you go live.

**Sorry, but I have no idea what is missing.**

> I guess you understand that the online sign should only appear when you are actually transmitting a live. (just double checking)

**Comment by fnbsullivan** [comment]
well, issue must be here then:

![image](https://user-images.githubusercontent.com/87485587/189453435-442c5fa3-3ca0-4240-8111-ec708a416227.png)

**Comment by DanielnetoDotCom** [comment]
I suspect your christiansource.com is redirecting to HTTPS

it cannot be redirected. the on_* parameter MUST be HTTP https://github.com/WWBN/AVideo/issues/4880#issuecomment-814461018

**Comment by fnbsullivan** [comment]
turned this off:

![image](https://user-images.githubusercontent.com/87485587/189458427-e7275c55-dc59-4322-996a-b72eb2175071.png)
 
I think we are good now!  Thanks Daniel, bless you!

**Comment by fnbsullivan** [comment]
Yep, that did it!  Thank you!  So thankful for you.
