### ISSUE TITLE
Trending doesn't seem to stick to the last 30 days like I have it set to

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7107]
I am still seeing old videos from 3 years ago in the trending when I have it set to trending last 30 days.

![10e2b633-572b-4ba8-becb-d000d91e4366](https://user-images.githubusercontent.com/39392449/189439709-d34007aa-450b-4893-990a-765dcfbdb4cf.png)

**Comment by DanielnetoDotCom** [comment]
this feature filter the videos that was modified on the last 30 days (a view added count as a modification) 

the filter is not about videos created up to 30 days ago

**Comment by JoshWho** [comment]
That is kinda a bummer. This is more what people are looking for when they think of what's trending.  Need some kind of Trending Now  Trending this week trending this month kind of thing.

**Comment by DanielnetoDotCom** [comment]
I guess you are right, I will review it

**Comment by DanielnetoDotCom** [comment]
I just sent an update, please check if this attend you

**Comment by JoshWho** [comment]
Works perfect now. Thank you @DanielnetoDotCom
