### ISSUE TITLE
Upgrade youtube-dl

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#7109]
Hi Daniel
I'm trying to update YouTube codecs with the command you gave me in the past:

sudo pip install --upgrade youtube-dl

After giving the command it says it can't update and I get this:

Requirement already up-to-date: youtube-dl in /usr/local/lib/python3.8/dist-packages (2021.12.17)

Can you tell me what I need to do to fix this and be able to update YouTube?
Users can't upload some videos from YouTube, and they can't upload other types of videos either.
Can you help me solve it?
Can you tell me the commands to execute?

Thank you

**Comment by DanielnetoDotCom** [comment]
if you read the message, that means your youtube-dl is up to date. 

Try to run this on your server

`sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && sudo chmod a+rx /usr/local/bin/yt-dlp`

**Comment by sharknetwork24** [comment]
I sent the command as per instructions.
The answer is this:

![2](https://user-images.githubusercontent.com/82677269/189702447-2298e9be-76c0-4ade-ae2d-5f4acbbe3a97.JPG)

What it means?

**Comment by DanielnetoDotCom** [comment]
means that work, try to download a video again.

**Comment by sharknetwork24** [comment]
I tried to reload again but it doesn't charge.
Can you help me solve it because it also happens with other videos.

![3](https://user-images.githubusercontent.com/82677269/189732346-69571af7-4970-4e2b-b621-52101fc0b7a1.JPG)

![4](https://user-images.githubusercontent.com/82677269/189732369-852e8580-1897-49ed-a220-abf818263fe7.JPG)

![5](https://user-images.githubusercontent.com/82677269/189732394-60b64596-0c60-4e33-84db-9b48f06ecc35.JPG)

**Comment by sharknetwork24** [comment]
Can you tell me Daniel where I get the logs from the decoder and also those from the streamer.
You never explained to me why I always made you do it and I never needed it.
Could you tell me where I find the logs so I can show them to you?
Thank you

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by walt93** [comment]
On my system in the crontab for the superuser, I have the following. To access it, from the command line you type (followed by your password):

`sudo crontab -e
`
Inside of the crontab add this line, causes YouTube-dl to be downloaded regularly

1 1 * * * sudo pip3 install --upgrade youtube-dl

(If you're curious what schedule that is, go to https://crontab.guru and enter the first part of that string "1 1 * * *")

**Comment by sharknetwork24** [comment]
Tonight a user made a test live, it's the result and I'm making a bad impression.
He did a 2:15 minute live, and I don't understand why he split the 1 hour, 1 hour, and 13 minute live into 3 parts.
Can you tell me what's going on?
It is possible to fix this problem.
In this way I lose users who can help me financially.
I await your news Daniel.
Thank you

![10](https://user-images.githubusercontent.com/82677269/190791932-e64f0d19-382a-4ef7-bfbc-be9ef9513196.JPG)

![11](https://user-images.githubusercontent.com/82677269/190792053-f038aaea-a233-47b0-9c81-15fc17ed6636.JPG)

**Comment by sharknetwork24** [comment]
In practice, the two 1 hour hours are not seen and have not been loaded.
I'm desperate if I keep making these bad figures.

**Comment by sharknetwork24** [comment]
I sent you the logs to view them by email.
Is it possible to fix upload errors, live not being saved?

**Comment by DanielnetoDotCom** [comment]
Hi

please open a new issue regarding this problem. youtube-dl has nothing to do with the recorder.
