### ISSUE TITLE
Backup stuck

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#7110]
Backup stuck
I am unable to make new backups because it is blocked.
Tell me what to do to unlock it and be able to make new backups?
Thanks Daniel

![1q](https://user-images.githubusercontent.com/82677269/189527861-9cc93ca3-5062-4dd5-978f-e8b738c372f4.JPG)

**Comment by sharknetwork24** [comment]
As you can see from the photo it has been blocked since 09/06/2022 and today it is not possible to do anything more.
Daniel kindly tell me how to unlock.

**Comment by DanielnetoDotCom** [comment]
Check if you have enough free space on your server.

depending on how many videos you have. the backup may take a while.

for a large site, I recommend a [clone ](https://github.com/WWBN/AVideo/wiki/Clone-Site-Plugin) instead of a backup

**Comment by sharknetwork24** [comment]
How do I stop it?

**Comment by sharknetwork24** [comment]
Perfect Daniel I solved it thanks to your help.
I close the post

**Comment by sharknetwork24** [comment]
Daniel, do you have a guide on how to use the Clone procedure?
I would like to be able to use the Rsync functionality on my NAS but I don't know how.
You can help me?

**Comment by DanielnetoDotCom** [comment]
click on the clone link here https://github.com/WWBN/AVideo/issues/7110#issuecomment-1243763014
