### ISSUE TITLE
bug on header after latest update

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#7118]
Greetings Mr @DanielnetoDotCom  I just updated to the latest vesion and now header is messed up it has an i apropiate google ad  hat distplays vertically and on the header and the whole site is now blocked and not working. This only happened after the last update please help me to prevent ads from displaying on header.
![Screenshot (11)](https://user-images.githubusercontent.com/72950503/190149387-630998a6-6065-43df-b8dc-b230abb7e4b0.png)

**Comment by DanielnetoDotCom** [comment]
Please share the site link so I can check

**Comment by mrgodgiven** [comment]
https://livefaces.meetmycraft.live/view/

**Comment by DanielnetoDotCom** [comment]
I cannot check

![image](https://user-images.githubusercontent.com/18009293/190173540-bc0d5c62-f455-46b7-a597-fb1d633577b5.png)

**Comment by mrgodgiven** [comment]
please check now I changed the settings of user must be logged in you shopuld be able to check

**Comment by mrgodgiven** [comment]
https://livefaces.meetmycraft.live/view/

**Comment by DanielnetoDotCom** [comment]
where did you add this ad code? what plugin?

**Comment by mrgodgiven** [comment]
Site settings/ script code via admin panel

**Comment by DanielnetoDotCom** [comment]
For this type of ad, you should use the ADs plugin.

this ad writes wherever you add it

settings/ script  add the script to the page header

**Comment by mrgodgiven** [comment]
It's th google code. Where can I add it then ?

**Comment by mrgodgiven** [comment]
When I paste it here, then the ads dissappears
![Screenshot (12)](https://user-images.githubusercontent.com/72950503/190185351-17d5f733-fb98-458e-947a-76de237f6fa3.png)

**Comment by DanielnetoDotCom** [comment]
strange, 

remove from the header and add it on leaderBoardTop

**Comment by mrgodgiven** [comment]
please show me a screenshot showing the leaderboardtop where I can add the code .

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/190187878-ee61651e-75ad-48f0-aef5-6cef83305a4d.png)

**Comment by mrgodgiven** [comment]
ok let me try thanks
