### ISSUE TITLE
"Invalid Token" when playing video for the first time

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#7119]
Using plugin VideoHLS. If I load any video for the first time, any browser, the message 

`"Not authorized: {"authorization":false,"msg":"The token is invalid"}" `

is returned when player is making a request like

`https://storage.your-website/AVideo-Storage/videos/video_22091323215_va80f/index.m3u8?token=eyJzYWx0IjoiaHR0cHM6XC9cL3ZpZGVvcy5uYWRhci50diIsInRa2VuVGltZU91dCI6IjM2MCIsImZpbGVuYW1lIjoidmlkZW9fMjIwOTEzMjMyNzE1X3ZhODBmIiwidGltZSI6MTY2MzE1ODQ0Mn0=
`
Then reload the page and video can be played. Doesn't seem too much, but for first-time people visiting the page, it looks like a bug and they will not even try to reload the page.

Did anyone have similar problem?

VideoHLS plugin parameters:

`{"qualitySelector":true,"downloadProtection":true,"AlwaysAllowChromeCast":true,"LabelLow":"Low","LabelSD":"SD","LabelHD":"HD","IPWhitelist":"[\"127.0.0.1\",\"localhost\",\"my-ip\"]","RefferWhitelist":"[\"my-site\",\"my-2nd-site\"]","UserAgentWhitelist":"[\"AVideoMobileApp\"]","TSFilesCDN":"","overrideNative":false,"returnAllSources":true,"saveMP4CopyOnCDNStorageToAllowDownload":true,"saveMP3CopyOnCDNStorageToAllowDownload":true}
`

**Comment by DanielnetoDotCom** [comment]
what exactly player are you using?

is this from the AVideo player or a third-party one?

try to clear the cache and see if works

check your apache log on your storage server
