### ISSUE TITLE
On /mvideos saving any change sometimes causes it to jump back to the first page / clear page controls

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7121]
**Describe the bug**

This started happening several weeks ago.

Imagine editing the most recent 50 videos metadata. Some times when you edit/save, you jump back to the top of the list and the page controls are reset.

Now you either have to re-select [Show 50 items per page], or, scroll to the bottom of the screen and hit the page control. 

It's not clear what triggers it to happen, it happens maybe 1:5 - 1:10 times.

**Comment by DanielnetoDotCom** [comment]
With this update when you reload the grid it may keep on the same page.

but regarding the scroll bottom/top when edit, I could not reproduce that
