### ISSUE TITLE
Select a user to comment as if you were him is a option and needs to be removed or disabled

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7123]
![590ee2b4-6044-4304-b195-0cf2f9efffff](https://user-images.githubusercontent.com/39392449/190402027-f01620b8-70c4-430d-aad7-9cbfdd011507.png)

You can see here https://www.joshwhotv.com/v/.QDMjzg

**Comment by JoshWho** [comment]
![15df903d-577e-44b8-9999-e75174e90808](https://user-images.githubusercontent.com/39392449/190402331-9d6cf752-ce8d-4f07-8af6-dcfa7dc36052.png)

**Comment by JoshWho** [comment]
Nevermind false alarm that is as logged in as admin.

**Comment by JoshWho** [comment]
I thought I was seeing that as a guest didn't realize I was logged in as the sys admin LOL My bad

**Comment by DanielnetoDotCom** [comment]
Yes, only admin can do that
