### ISSUE TITLE
Can’t watch live stream from app

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#7124]
Live stream can be seen on website but not on app. Neither android nor apple

**Comment by DanielnetoDotCom** [comment]
Hi

it suppose to be the same. but if you want share a link and I can check from my side

**Comment by barrunning** [comment]
I have a stream today at 715 am pst time on Movingfsst.com

**Comment by DanielnetoDotCom** [comment]
Hi, sorry looks like this time already pass.

did you make a live?

does it work?

are you making a live in 720p max?

**Comment by DanielnetoDotCom** [comment]
I can see this

![image](https://user-images.githubusercontent.com/18009293/190703966-8b42f7b5-0d92-4d52-bb75-62e5f8881ae5.png)

the solution is simple, just restart your nginx. I am doing it now.

this explain why you could not watch

**Comment by DanielnetoDotCom** [comment]
You should be good to try again, and this may not happen anymore
