### ISSUE TITLE
Refresh after edit description 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#7125]
After editing a video description like changing the title can the page refresh to reflect the changes? A manual refresh is required in the browser to see any changes.

**Comment by DanielnetoDotCom** [comment]
A page refresh may be required, but clear chache is NOT required

**Comment by fakeologist** [comment]
A page refresh is always required can this be forced to be automatic?

**Comment by DanielnetoDotCom** [comment]
can you please screenshot so I will know what screen are you referring to?

**Comment by fakeologist** [comment]
https://user-images.githubusercontent.com/66537018/190699227-9ddc2bb5-043a-4335-b91c-840173470cf9.mp4

**Comment by DanielnetoDotCom** [comment]
Understood, it is possible but it is not an easy solution, so for now this does not worth to do it. unless someone is willing to pay for this feature.
