### ISSUE TITLE
All my Roku Feeds now do not work

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7126]
Now it is saying something about needing short descriptions. When did this all get changed? All my vids on Rok now do not work and I do not want to edit every single one of them.

![eb26236a-ccb9-4cd1-90c8-004a2c5d8498](https://user-images.githubusercontent.com/39392449/190525560-5b384b40-e1e6-43c7-9ac6-fa07e3cc8c46.png)

**Comment by JoshWho** [comment]
Can't the short description get pulled from the long description or something. THis is horrible

**Comment by JoshWho** [comment]
I have like over 300+ videos that would all need to be edited just for this new description line

**Comment by DanielnetoDotCom** [comment]
Roku is complaining about empty descriptions

Tomorrow I will send you an update, if your description is empty it will use the title as a description.

**Comment by JoshWho** [comment]
Thank you that will be awesome. That should do the trick

**Comment by JoshWho** [comment]
Thanks again @DanielnetoDotCom
