### ISSUE TITLE
Any changes made always return to page 1

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#7127]
If I am on page 10 and I make changes to the users of page 10, after saving the changes I go back to page 1.
It didn't happen before, it's really annoying to find yourself on page 10/20 / etc. and at each saving it always and exclusively returns to page 1.
Daniel can you kindly arrange?
I am very grateful if you fix this feature as it used to be.
Thank you

![6](https://user-images.githubusercontent.com/82677269/190646911-d7da8e02-53ae-4379-a602-31d42b33b62a.JPG)

**Comment by walt93** [comment]
Note: This is also happening on /mvideos, you're 10 pages in, you delete one video, you have to page all the way back....

**Comment by DanielnetoDotCom** [comment]
It should be fixed since yesterday

**Comment by sharknetwork24** [comment]
Ok I do a gitbull and I'll let you know how it goes.

**Comment by sharknetwork24** [comment]
After updating everything works as before.
Thanks Daniel
