### ISSUE TITLE
[Idea] Make a page for each playlist

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7128]
**Is your feature request related to a problem? Please describe.**
Making a videos page come out with the videos in the order you want is very cumbersome, usually need to hack "created" field in mysql directly.

We have Programs which have great UI for sorting the order. Let's make a page for each Program to load a videos list sorted by program order.

```
https://mysite.foo/programs/my-cool-program-title        # by program name
https://mysite.foo/program/9999                          # by program id
```

_Not only is this incredibly useful, seems it's a trivial implementation. High bang-for-buck factor_

-------

In the left navigation menu, like we have a "Categories" section, we would like to have a "Programs" section. 

The Programs section would have a two level hierarchy, and behave the same as the Categories  navigation menu.

```
User 1
   program 
   program 
   program 
User 2
   program 
   program
...
```

**Comment by DanielnetoDotCom** [comment]
Hi, 

do you mean show a program as a gallery and also add it on the left menu?

Currently we have something like this https://demo.avideo.com/program/1

and you can use the TopMenu plugin to add a link on the menu

**Comment by walt93** [comment]
Yes, exactly this. Seems incredibly useful.

Though the link you sent is showing a white page. Perhaps there are no programs defined on the demo server?

**Comment by DanielnetoDotCom** [comment]
maybe this playlist is not public, I can see it here

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/18009293/191106642-a60d8425-539c-4576-94ae-b1a9d9cd29ed.png">

**Comment by walt93** [comment]
I was thinking like a /cat/  page, but that's fantastic.
