### ISSUE TITLE
[Workflow] Can we increase the number of items in this list? Put a scroller on it?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7129]
**Is your feature request related to a problem? Please describe.**
This would literally have saved me _a ton_ of work if had like 50 items in it.  

**Describe the solution you'd like**
1. This list to hold more items. Increase N to 50 (Better: infinite scroll or pagination)
2. Wrap view in scroller if/when it's more than the current max items.3. 
 
![Screen Shot 2022-09-17 at 1 42 57 AM](https://user-images.githubusercontent.com/11711050/190848393-89a6ae80-a1b9-4d32-9b7a-83e689f36750.png)

**Comment by DanielnetoDotCom** [comment]
Soon I will send an update with the load more button

**Comment by walt93** [comment]
Sweet!
