### ISSUE TITLE
Why does the (videos) directory still take up a lot of space when the video is stored in a remote location?

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#7130]
Why does the (videos) directory still take up a lot of space when the video is stored in a remote location?
![image](https://user-images.githubusercontent.com/47063171/190849747-9d1b0ddb-c61a-424b-b252-5d5b715fdcf0.png)
![image](https://user-images.githubusercontent.com/47063171/190849770-12225460-329e-4717-a1f7-cb0ab13bc1f9.png)

**Comment by chenjian9885** [comment]
Can I delete files in the directory (videos)? It will have more and more files taking up a lot of my storage space

**Comment by DanielnetoDotCom** [comment]
maybe the video was not transfered successlfully. 

AVideo will only free the video space, after make sure the video was successuffly copied.

please check your logs for some clue. 

do not manually delete the video.

**Comment by chenjian9885** [comment]
I'm sure the video has been transferred, but don't know why there are so many directories left in the (videos) directory

![image](https://user-images.githubusercontent.com/47063171/192350473-c6d308ed-87e0-49b8-bbc9-12a4a8ec0cd1.png)
![image](https://user-images.githubusercontent.com/47063171/192351723-fb06c76c-6872-4b01-bd3e-0603036c1458.png)
![image](https://user-images.githubusercontent.com/47063171/192255594-beca4e5b-2d82-4e1b-bc04-6c3e49d97942.png)

**Comment by DanielnetoDotCom** [comment]
Megabytes is not a lot of space. this is probably the images.

FYI only the video files are hosted externally, you will always need space for the metadata files.

**Comment by chenjian9885** [comment]
It's just a handful of videos, and when I put more videos on other sites, it takes up a surprising amount of space
![image](https://user-images.githubusercontent.com/47063171/192363779-d4225d7d-f021-4fe5-90e4-371452c015de.png)

**Comment by chenjian9885** [comment]
Will need a lot of storage space after a long time

**Comment by DanielnetoDotCom** [comment]
I am not sure what you mean a lot, but yes, you need some space, for the metadata, cache and for the database.

**Comment by chenjian9885** [comment]
I mean the (videos) directory will generate a lot of directories and files unrelated to website videos, which will take up a lot of storage space over time.

**Comment by chenjian9885** [comment]
The directories of these videos have been transferred to (AVideo-Storage), do you still need to keep them in the (videos) directory?
![image](https://user-images.githubusercontent.com/47063171/192604714-0ae1d30f-0a97-4786-80fd-f834dc56f5a7.png)

**Comment by DanielnetoDotCom** [comment]
all the directories must be related to some video.

and also the directory should be removed when you delete a video.

**Comment by chenjian9885** [comment]
OK, thanks
