### ISSUE TITLE
Can we increase the number of items visible on this list from 3, to something like 7 or even 10?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7132]
**Is your feature request related to a problem? Please describe.**
This list is too small when you have more than 3 programs.

**Describe the solution you'd like**
Increase value of N from 3 to 7, maybe 10.

![Screen Shot 2022-09-17 at 2 56 00 AM](https://user-images.githubusercontent.com/11711050/190851173-fdfc98f5-791a-4611-84d8-dc27c666fd1e.png)

**Comment by DanielnetoDotCom** [comment]
I just made some improvements on the playlist menu

![chrome-capture-2022-8-21](https://user-images.githubusercontent.com/18009293/191515914-29c63a71-bab3-447f-88a6-64840fae5243.gif)

**Comment by walt93** [comment]
Nice!
