### ISSUE TITLE
Wrong count of videos

### ISSUE THREAD

**Issue by swimitup** [WWBN/AVideo#7133]
The MyVideos page is showing incorrectly the number of videos:

![Screen Shot 2022-09-17 at 06 59 49](https://user-images.githubusercontent.com/12404245/190858151-3e9f1ab0-e1e6-4b47-8390-9356d56224d9.jpg)

**Comment by DanielnetoDotCom** [comment]
it suppose to count the total of videos of your user

check the dashboad admin panel for a more precise count 

![image](https://user-images.githubusercontent.com/18009293/191067372-ebe3b9ba-042e-44eb-bd01-ab97d931df69.png)

**Comment by swimitup** [comment]
It seems the count is about the number of users, not videos:

![Screen Shot 2022-09-20 at 05 48 01](https://user-images.githubusercontent.com/12404245/191249878-299af930-98ed-4b90-8c80-b1386ebd9ff1.jpg)

Cache was cleared.

I checked the code, view/managerVideos_body.php, and it seems the Video class method, humanFileSize, is converting it to 1, since it's not dealing with filesize regex, but a integer:

```
        <small class="text-muted clearfix <?php echo getCSSAnimationClassAndStyle('animate__flipInX'); ?>">
            <?php
            $secondsTotal = getSecondsTotalVideosLength();
            $seconds = $secondsTotal % 60;
            $minutes = ($secondsTotal - $seconds) / 60;
            $totalVideos = **humanFileSize**(Video::getTotalVideosFromUser(User::getId()));
            $totalVideosSize = humanFileSize(Video::getTotalVideosSizeFromUser(User::getId()));
            printf(__("You are hosting %d videos total, %d minutes and %d seconds and consuming %s of disk"), $tota>
            ?>
        </small>

```

If I remove the function

`            $totalVideos =(Video::getTotalVideosFromUser(User::getId()));`

It shows the correct number

![Screen Shot 2022-09-20 at 06 04 55](https://user-images.githubusercontent.com/12404245/191252907-6d5562c9-c9c8-4f84-804a-f039db01ed84.jpg)
