### ISSUE TITLE
Error when I change the theme

### ISSUE THREAD

**Issue by tunopendientes** [WWBN/AVideo#7136]
**Describe the bug**
When I change the theme it always happen, only with theme "Default"

**To Reproduce**
1. Go to 'admin panel'
2. Click on Design
3. Scroll down to First page style/Default
![Captura de pantalla 2022-09-18 081551](https://user-images.githubusercontent.com/63250451/190899365-b08917ed-3bba-4b58-bbab-fcabda9a3c9d.png)

**Comment by DanielnetoDotCom** [comment]
Please try my latest update

**Comment by tunopendientes** [comment]
Now working!!!!

Thanks a lot!

**Comment by tunopendientes** [comment]
One another question if possible. The phpmyadmin shows blank. I had to install phpmyadmin apart. Thanks, this is not important

**Comment by DanielnetoDotCom** [comment]
> One another question if possible. The phpmyadmin shows blank. I had to install phpmyadmin apart. Thanks, this is not important

I do not recommend it and I do not like it, but it is up to you if you want.
