### ISSUE TITLE
Users "Go Live" help

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#7137]
I am a new user of this software. I just installed this software and trying to test it. I cannot figure out how users can go live. Please help me understand this. I understand that any user can live streaming in his or her channel, but I don't see the option for that except in the admin.

**Comment by DanielnetoDotCom** [comment]
This is how to make a live stream 

https://github.com/WWBN/AVideo/wiki/How-to-make-a-live-stream

you can also live stream using the meeting 

https://github.com/WWBN/AVideo/wiki/Meet-Plugin#live-directly-thru-the-webcam

to let users make live stream you need to give the propper permisssion 

https://github.com/WWBN/AVideo/wiki/How-to-make-a-live-stream#permissions
