### ISSUE TITLE
Google Adsense

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#7138]
I bought Google IMA plugin, but how can I configure it to work.

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Plugin:-GoogleAds_IMA---Videos-Ads-on-your-page

**Comment by mankota** [comment]
I logged in to my adsense account, but there is no my Ads. However, the is Ads and it doesn't have an apply link for adsense videos
![image](https://user-images.githubusercontent.com/25535711/191104471-3613479c-64fd-4851-8138-162e1b24839b.png)

**Comment by DanielnetoDotCom** [comment]
I am not 100% what is missing, try to google or contact google about it
