### ISSUE TITLE
Go Live with WebCam is not working

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#7140]
Hi Folks,
I want to test the "**Go Live With WebCam**" feature, it does not detect my webcam source.  Where do I need to go to configure it if possible? I appreciate the help. There is a configuration button for it but there is no camera sources in the drop downs.

![image](https://user-images.githubusercontent.com/25535711/190949881-2f713cbc-6f12-4d07-81cc-3b0de4882ccf.png)

**Comment by DanielnetoDotCom** [comment]
"Go Live With WebCam" still experimental, is not recommended to use yet

**Comment by ganddser** [comment]
Seems to be broken again @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
It never works properly, it is experimental
