### ISSUE TITLE
Ad server only serves ad from first active campaign.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7141]
**Describe the bug**
I am trying to configure my adserver.

I create N campaigns.

It serves ads from the first campaign in the list.

I disable the first campaign in the list.

It serves ads from the second campaign in the list.

**No matter what I do, it only serves ads from one campaign. The campaign it serves from is always the lowest ordinal index into the array of campaigns that is active.**

**To Reproduce**
1. Create more than one ad campaign.
2. Play media from your server
3. Observe the results are as I stated above.

Please advise as if to this can be addressed. See also https://github.com/WWBN/AVideo/issues/7079 (duplicate of same)

**Comment by walt93** [comment]
Use case. I need to split my ads - we want 85% of the ads to come from one campaign, 5% from another, and 10% from a third.

If we could create, for instance, 20 ad campaigns, we could load 17 of the buckets with one flavor of ad, 2 buckets with another, and 1 bucket with the third.

But ads do not seem to work this way.

How to achieve an 85/10/5 split from three campaigns. Only way I can see to do it is literally put 100 ads in one campaign, with lots of replication.

**Comment by DanielnetoDotCom** [comment]
sorry I do not know how you will spit it, I can only tell you the correct way to use multiple ads is using VMAP
