### ISSUE TITLE
Program TV

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#7149]
Hello Daniel,
How can I make the TV work, do you have instructions somewhere on how to do it?

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
Hi

if you mean the EPG link it is for external live links sources.

I just added 2 samples on demo site where you can see how the link should loks like and how the EPG XML shoudl looks like

https://demo.avideo.com/video/391/allied-esports and https://demo.avideo.com/video/390/history-film-channel

Here is the EPG result https://demo.avideo.com/plugin/PlayerSkins/epg.php?avideoIframe=1

![image](https://user-images.githubusercontent.com/18009293/191084933-0c1d721a-5481-4ce0-b561-6e8b74dac0b3.png)

**Comment by wetubeclub** [comment]
Thank you Daniel for the clarification!!
one last question on this issue:
we can also configure this in our own script? or only from other sources? if so how can I do this?

Thank you
Ilias
