### ISSUE TITLE
Direct upload broken from recent git pull

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#7150]
Hi,

Direct upload was working fine up until 2 git pulls ago, not todays but the one before that. Now when you upload it will not grab the thumb although it always worked before, it just shows a black blank for the image. It also affects the second server that i use with a clean install on for testing. A quick fix I'm guessing?

Thank you

**Comment by DanielnetoDotCom** [comment]
can you please screenshot what is the problem?

**Comment by para2022** [comment]
The working thumbnail in the image was a video uploaded with the encoder and the blanks are direct upload. I didn't change anything on the site other than a git pull and then a few things broke. Same thing on the other site too. Thanks

![Screenshot 2022-09-19 at 20 39 19](https://user-images.githubusercontent.com/107706817/191101537-d67006dd-c0f3-4b8f-b9ec-52dab8d81a94.png)

**Comment by DanielnetoDotCom** [comment]
does the video play?

do you mean the thumbnail is the problem?

did you try to update the plugin?

should be an update for it MP4ThumbsAndGif version 3.0

**Comment by para2022** [comment]
Yes i updated all plugins as i noticed a lot needed updating after that particular git pull. MP4ThumbsAndGif is version 3.0. The video plays fine. If i use 'get jpeg/gif' it does indeed grab a thumbnail fine. I tried it with MP4ThumbsAndGif version 2.9 and 3.0 to see if it was an issue there but it happens with both versions. Basically it's not grabbing the thumbnail on upload like it used to do. Note: Get thumbnails from ffmepg is turned off in the advanced settings)

**Comment by DanielnetoDotCom** [comment]
I see, so the only issue is when you upload new videos that the thumbnails are not automatically extracted?

**Comment by para2022** [comment]
yes mate.

**Comment by DanielnetoDotCom** [comment]
Hi, I am sending now the MP4ThumbsAndGif version 3.1 that may fix this issue.

thanks for noticing that.

**Comment by para2022** [comment]
Thank you. I will report back :)

**Comment by para2022** [comment]
That fixed the issue. It is now working again. Thank you very much 👍
