### ISSUE TITLE
Supercharge donation plugin

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#7151]
Is there any plugin for donation like youtube supercharge?

**Comment by DanielnetoDotCom** [comment]
We have something close to that, 

https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform#donation-from-wallet

https://github.com/WWBN/AVideo/wiki/Monetization:-How-To-Make-Money-on-AVideo-Platform#chat-integration
