### ISSUE TITLE
Can we turn off downloading of images from the videos page? It's confusing for the user.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7152]
**Is your feature request related to a problem? Please describe.**
The user wants to download a video. They are confronted with a dizzying array of choices including webp gif and seven flavors of JPEG. 

**Describe the solution you'd like**
To turn off downloading of images.

![Screen Shot 2022-09-19 at 12 59 53 PM](https://user-images.githubusercontent.com/11711050/191106675-9b590c19-ec21-4dc6-bbb1-1511536adea8.png)

**Comment by DanielnetoDotCom** [comment]
Make sure you uncheck this option

![image](https://user-images.githubusercontent.com/18009293/191250265-3574e942-71f0-4696-95c7-08ff26e75abe.png)

**Comment by walt93** [comment]
Awesome, now Download is super-clean. Thanks Daniel!
