### ISSUE TITLE
Stripe configuration and usage

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#7153]
I have configured my stripe plugin, I dont know where can I use it. When adding funds, I only see PayPal instead of Stripe option. Can you help show me what to do to enable it for customers?

**Comment by DanielnetoDotCom** [comment]
check this 

![image](https://user-images.githubusercontent.com/18009293/191134653-7ca475b3-3716-4a56-b439-b7b4216ff260.png)

**Comment by mankota** [comment]
Thank you
