### ISSUE TITLE
Live stream saving & comment

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#7154]
Danie,
I got two questions for you.
1. How can I turn/off comment during live streaming?
2. Where can the live streaming video saves after the streaming ended and how can I be able to access them?

**Comment by DanielnetoDotCom** [comment]
> Danie, I got two questions for you.
> 
> 1. How can I turn/off comment during live streaming?

What comments?
Are you refering to the Chat? if yes check the Chat2 plugin parameters

> 2. Where can the live streaming video saves after the streaming ended and how can I be able to access them?

https://github.com/WWBN/AVideo/wiki/Record-Live-Stream
