### ISSUE TITLE
Creating new page

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#7155]
1. How can I create a new page? I want to create a terms and condition page,  a privacy policies page etc. I don't know where to go and do that.
2. Are the mobile apps native iOs and native android or it is just a URL browser based?
3. Disk quota plugin - Can this allow the user to buy more space if his quota is full or just he must delete some of his content?

**Comment by DanielnetoDotCom** [comment]
> How can I create a new page? I want to create a terms and condition page, a privacy policies page etc. I don't know where to go and do that.

Try to use the [TopMenu Plugin](https://github.com/WWBN/AVideo/wiki/How-to-use-TopMenu-Plug-in) and create HTML pages or just add a URL to a more sophisticated page

> Are the mobile apps native iOs and native android or it is just a URL browser based?

they are hybrid build with Ionic 

> Disk quota plugin - Can this allow the user to buy more space if his quota is full or just he must delete some of his content?

Correct!
