### ISSUE TITLE
[Permissions error] User adding videos to their program, in search, can add videos from every user

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7156]
**Is your feature request related to a problem? Please describe.**
I am logged in from user A's account.
I am editing a program.
I am adding videos to this program.
Search returns videos from entire site (Users B, C, ..., ..., ...)

**What did you expect to happen?**
Search to only return videos that the user can see from their /mvideos page.

This:
![Screen Shot 2022-09-20 at 6 57 20 PM](https://user-images.githubusercontent.com/11711050/191397012-e63d3451-b16d-40e9-8950-04361a17f5be.png)

Is returning videos it should not (none of these videos belong to the logged in user):
![Screen Shot 2022-09-20 at 6 57 46 PM](https://user-images.githubusercontent.com/11711050/191397052-2cf430a2-952c-4dd6-8dcc-284aa1d41991.png)

**Comment by DanielnetoDotCom** [comment]
This is not a bug. 

You can add videos from any user as long as you can watch them. 

Even if you add a video and later it becomes private you will not be able to watch it anymore.

**Comment by DanielnetoDotCom** [comment]
maybe in the future we can add a filter to only list the videos that belongs to the user

**Comment by walt93** [comment]
Thanks Daniel!
