### ISSUE TITLE
Ad campaign link icon crash solved. Still trying to figure out my use case!

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7157]
**Describe the question**
Trying to figure out how to get the Ad server to serve ads from multiple Ad Campaigns.

There is a [LINK] icon for each campaign. I thought it might link the campaigns together.

It does not. It crashes.

**Screenshots**
Clicking any of the link icons here:
![Screen Shot 2022-09-20 at 9 02 04 PM](https://user-images.githubusercontent.com/11711050/191411621-5c03d982-fdb5-4bb5-99fd-f10343724b37.png)

Gets something like this:
![Screen Shot 2022-09-20 at 9 02 35 PM](https://user-images.githubusercontent.com/11711050/191411687-f7d752ee-924c-4b7b-a29f-2375128f75e9.png)

**Comment by walt93** [comment]
Ok this is fixed. So this is giving the VMAP link. AFAIK I do not need a VMAP link for anything I am doing. Roku wants VAST.

Is it possible to play ads from more than one ad campaign? I really need to solve this before we go live.

**Comment by DanielnetoDotCom** [comment]
this is the correct way to do `https://adserver.conspyre.tv/plugin/AD_Server/VAST.php?campaign_id=3`

**Comment by walt93** [comment]
Ok, so, that pulls from one campaign.

Here is the use case I am trying to solve. We want to run ads from three campaigns. We want them split 85% of ads from one campaign. 10% from a second. 5% from a third.

Only way I can see is one campaign with 100 ads. And we duplicate them a bunch of time to hit the numbers.

...is this correct, or, how would you solve the use case?

**Comment by DanielnetoDotCom** [comment]
> Only way I can see is one campaign with 100 ads. And we duplicate them a bunch of time to hit the numbers.

that may work
