### ISSUE TITLE
Commissions on subscriptions and donations

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#7158]
1, How does the admin set commission user subscriptions? Is it from the subscription plugin?
2.Is there any commission from donations? How is it configured if any?

**Comment by DanielnetoDotCom** [comment]
> 1, How does the admin set commission user subscriptions? Is it from the subscription plugin?
> 2.Is there any commission from donations? How is it configured if any?

Currently, we do NOT have the split option on those, there are only split payments for PPV

we may add the split option for donation in the future, but I am not sure if is possible to do it with the subscription.

**Comment by mankota** [comment]
It will be great if we have such option on donation and subscriptions.

**Comment by DanielnetoDotCom** [comment]
I totally agree
