### ISSUE TITLE
Error import DB (Cannot add foreign key constraint)

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7159]
Hi @DanielnetoDotCom ,

I'm doing some backup restore tests. And I saw an error when doing the import.
Using the MYSQL Workbeck software:
`ERROR 1215 (HY000) at line 8588: Cannot add foreign key constraint`

I verified that this line is this:

```
-- Limitadores para a tabela `livelinks_has_users_groups`
--
ALTER TABLE `livelinks_has_users_groups`
  ADD CONSTRAINT `fk_livelinks_has_users_groups_livelinks1` FOREIGN KEY (`livelinks_id`) REFERENCES `livelinks` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_livelinks_has_users_groups_users_groups1` FOREIGN KEY (`users_groups_id`) REFERENCES `users_groups` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
```

I don't use these groups or livelinks.

**Comment by DanielnetoDotCom** [comment]
you may need to google for that, sorry but I cannot teach you how to use MySQL or workbench
