### ISSUE TITLE
Search only finds the left portion of the target string on Add to Program UI

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7161]
**Describe the bug**
New add to program UI is cool, we can see more programs.

However search is broken (fails to find anything) & that's the fast workflow when you're scrolling 50 programs. 
  -Click to open list. 
  -Paste the name of the program. 
  -Click the switch to add programs.

My fast workflow is broken & now I have to scroll to find the program every time. We are adding >500 pieces of media………

https://user-images.githubusercontent.com/11711050/191626093-3a94f014-e68f-4864-85ba-6d40ad46f3a0.mp4

**Comment by DanielnetoDotCom** [comment]
Thanks for noticing that, this should fix it.

**Comment by walt93** [comment]
Daniel - it's *almost* fixed, think you need to check your SELECT statement probably there is an issue with a % in a LIKE statement - if I had to guess? It only finds the left most part of the query string.

https://user-images.githubusercontent.com/11711050/191845621-f0c193cb-cdaf-41a9-8856-58a6692516ca.mov

**Comment by DanielnetoDotCom** [comment]
please try this update

**Comment by walt93** [comment]
Thanks Daniel, working now!
