### ISSUE TITLE
Disk Quota plugin configuration

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#7162]
Daniel,
I just purchased the disk quota plugin and tried to create a plan. It seems to be saving but I can't see the plan. Secondly, when you click the buy storage it only giving me a blank screen. Can you help how to configure this?

![image](https://user-images.githubusercontent.com/25535711/191664016-03d9f321-c938-4200-a826-8e395d38793f.png)

**Comment by DanielnetoDotCom** [comment]
maybe it is not saving. can you please check your logs at the moment you try to save a plan?

**Comment by mankota** [comment]
It looks like it saves because after saving with less disk space than the current, it will not allow me to upload a new video. However, when I click the info icon, I seen the text but no option
![image](https://user-images.githubusercontent.com/25535711/191875161-c09368a2-391a-40a5-9db9-920eeae152fb.png)

**Comment by mankota** [comment]
Daniel,
 noticed that if I create a plan with 15GB and above it will not save. Is there a way that I can save more than 10 GB?

**Comment by mankota** [comment]
Also, instead of giving the plan an expiration date, is there a way to just force the user to buy a new storage quota after the purchased storage is been used? Does this mean I just have to put 0 on the how many days and free trial fields?

**Comment by DanielnetoDotCom** [comment]
Strange, I just add 2 different plans here and it works fine

![image](https://user-images.githubusercontent.com/18009293/191984482-549e75c9-ac04-430d-84e6-ca430f151e21.png)

can you please tell me what exactly are you inputting in the form so I can test on my side?

**Comment by DanielnetoDotCom** [comment]
> Also, instead of giving the plan an expiration date, is there a way to just force the user to buy a new storage quota after the purchased storage is been used? Does this mean I just have to put 0 on the how many days and free trial fields?

The idea here is a recurrent subscription, not pay once thing. 
but as a workaround maybe you can create a plan with 36500 days valid (100 years)

**Comment by mankota** [comment]
Daniel,
I know what was going on. It seems you have to fill in all the fields. The problem was I did not put anything in the free trial field so it did not save.

1. What I want also to do is allocate all new users certain storage for free automatically after they register. Only after that quota is been used they are forced to start buying storage. Is this possible?
2. I cannot able to buy storage. After filling the payment info and click subscribe, it will just spinning forever. What do I need to do to fix this issue? See below screenshot
![image](https://user-images.githubusercontent.com/25535711/192025935-4be72f13-f6fe-43bc-9525-c41862c24bbc.png)

**Comment by DanielnetoDotCom** [comment]
> What I want also to do is allocate all new users certain storage for free automatically after they register. Only after that quota is been used they are forced to start buying storage. Is this possible?

I understand. but this is not how we design the plugin at the beginning. Your idea makes total sense to me and we may make this type of business plan more friendly in the future

> I cannot able to buy storage. After filling the payment info and click subscribe, it will just spinning forever. What do I need to do to fix this issue? See below screenshot

check the AVideo logs for some clues, also make sure you are using or not the test environment for stripe.
