### ISSUE TITLE
Embedded content gets into a state where it is not hiding the transport controls (they stay visible throughout)

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7163]
**Describe the bug**
During playback, Prev-Next-Play controls remain visible and do not hide. 

**To Reproduce**
I just saw it doing this on Truth Social, and when I went back to play the same video a second time - it is not reproducing.
I went to another site - where someone is using my AVIdeo site to power their embeds, and it reproduced there.

This screenshot is from after letting the video play with the mouse outside the window for ≈1 minute:
![Screen Shot 2022-09-22 at 12 14 08 AM](https://user-images.githubusercontent.com/11711050/191682837-77f7ef2e-1794-4581-b621-69b8ac7e240c.png)

NOTE: second time loading the above site - problem did not reproduce. That's consistent. So it seems to only happen the first time you load the page.

**Comment by DanielnetoDotCom** [comment]
I need a way to reproduce it, otherwise, I cannot do anything.

**Comment by walt93** [comment]
Lol now when I go to try to reproduce it, it does not. I saw it twice last night & thought it might be best to report it before this podcaster noticed it.

File under unreproducible I guess? I'll see if I can find you a reproducible case, otherwise will close this if I cannot, thanks.
