### ISSUE TITLE
Installation using Docker

### ISSUE THREAD

**Issue by plani-de** [WWBN/AVideo#7164]
**Describe the bug**
Failed to run Encoder-Installation using a Docker image and not all links work with FQDN or IP-Address, as they are replaced by 'localhost'

**To Reproduce**
Created a docker-image as described, worked fine. Started the images using:
docker-compose up --build
or
docker-compose up 

Login works. Clicking on Video upload will open a new browserwindow which uses 'localhost' in the URL instead of the IP address and then wants to install encoder. When continuing I get different error messages like "Error creating streamer: Unknown column 'allowedStreamersURL' in 'field list'" or just a never ending "processing". This for example depends on wether I fill in http or https in the filed: AVideo Streamer Site URL

**Already done to solve**
* Rebuild docker image
* Make the configuration.php owned by www-data
* checked the mysql db, database already exists and looks good at first glance. 

Any help appreciated...

**Comment by plani-de** [comment]
After keeping on diving into the problem, the following question arises:
My understanding is, that avideo streamer and encoder are to pieces of the puzzle, but both are installed with the docker-image. So when it is installed, why does clicking the link to upload a video (https://aaa.bbb.ccc.ddd/mvideos#) redirect to the install page (https://aaa.bbb.ccc.ddd/Encoder/install/index.php)?

**Comment by DanielnetoDotCom** [comment]
Also, feel free to submit push requests if you fix something on docker
