### ISSUE TITLE
Highly inflated view counts, tired of explaining this to podcasters 😂 there is an easy fix!

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7165]
**Describe the bug**
We see in the logs that we are reporting between 1-10 (?very rough guesstimate) views per user.

I installed the IPV6 DB that you recommended, it still did not fix the issue.

Not sure how you have to code it, but the algorithm is straightforward. 

    LOOP through database, selecting entries in 24-hour time slices.
    FILTER each time slice by IP address, throwing away duplicates
    ADD them up and continue looping until finished

This discards all of the noise. There is **no** reason to count multiple views from a user in a single day. None whatsoever. 

This algorithm discards bugs in the view collection, it discards  bots, maybe the user really did watch it twice - who cares - they can only comprehend it once!

And this makes my podcasters happy. We like happy podcasters. Happy podcasters means we get more podcasters. 😉

![Screen Shot 2022-09-22 at 1 59 20 PM](https://user-images.githubusercontent.com/11711050/191849956-f3206c1d-ddcd-4c58-bae6-a99ad83b5065.png)

**Comment by walt93** [comment]
But please let me know if this can't be implemented so I can communicate very clearly to my podcasters the state of affairs......

**Comment by DanielnetoDotCom** [comment]
Hi, 

I disagree, we should collect multiple views from the same user on the same day.

but FYI Unknow User means we do not know who the user is. so no way to detect duplicates.

the only thing I usually see extra counts is when you use your videos embedded into iframes

**Comment by walt93** [comment]
It looks like you're checking IP address after the geolocation has thrown away the LSB?

I read that as "same computer in City of Industry, California" is generating 16 views - when you scroll the logs they *all* cluster like that, all right in the same minute or two.

I'm making some assumptions here, and based on them I'd recommend counting before you do a process that loses data. That seems to be what is happening here.

**Comment by DanielnetoDotCom** [comment]
the log above does not add a view count, it only adds more time watching the video.
