### ISSUE TITLE
Something odd with the tiny.cloud plugin?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7166]
**Describe the bug**
This ("Upgrade") icon appears in the editor. Clicking it takes one to https://tiny.cloud.

![Screen Shot 2022-09-22 at 2 13 06 PM](https://user-images.githubusercontent.com/11711050/191851984-73a02524-e944-4f81-b5d9-ac5810f3454b.png)

**Comment by DanielnetoDotCom** [comment]
I have no idea where this upgrade comes from.

maybe it is a browser plugin on your PC

**Comment by walt93** [comment]
That's truly strange. Screenshot is from macOS Safari with no browser extensions, thought this might be something to do with the rich text editor since it appears in its viewport.

**Comment by wetubeclub** [comment]
Hello,
the same thing happens to me on both sites

Thank you
Ilias

![tiny](https://user-images.githubusercontent.com/60543030/192089412-b642bf60-d534-4dc5-9f36-0f9b45f43da3.jpg)

**Comment by DanielnetoDotCom** [comment]
Hi, this is something from TinyMCE, try this update id will resolve it.

**Comment by wetubeclub** [comment]
problem solved!!!!
Thank you Daniel
Ilias

**Comment by walt93** [comment]
Thanks Daniel

**Comment by hervaden** [comment]
THis issue seems to have popped up again.  Downloaded and replaced the tiny editor folder, but the buttons is still there.
