### ISSUE TITLE
Issue with RSS feeds

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7167]
We see there are RSS feeds links to the content on the site, however when we take such url and put it in Spotify we get the following errors:

![photo_2022-09-23 00 16 33](https://user-images.githubusercontent.com/58882903/191852869-f631dde4-0be3-4a6f-8b22-6fdf2b00dcee.jpeg)

Is this a bug or just us not knowing how to use the RSS feature of the site.

**Comment by DanielnetoDotCom** [comment]
The author is an element of RSS NOT MRSS

so please update and try this 

https://alive528.com/rss?program_id=115313

**Comment by guymass** [comment]
I updated and tried that URL but the results are the same.

**Comment by DanielnetoDotCom** [comment]
I can see your RSS here https://alive528.com/rss?program_id=115313

what same results are you referring to?

**Comment by guymass** [comment]
The same message as the one in the photo appears. How do I edit the Description, Author and email of the RSS so Spotify can recognize my RSS?

**Comment by eitanwa** [comment]
hay
This is the Spotify link
where we feed the rss- Taken from the playlist 

https://podcasters.spotify.com/submit

This is what it looks like

![photo_2022-09-29_09-50-05](https://user-images.githubusercontent.com/85537931/192959719-3b933868-af51-44b3-b143-fce9eb106cc9.jpg)


This is the message that is received After typing the rss code

![photo_2022-09-29_09-48-03](https://user-images.githubusercontent.com/85537931/192959395-06506bef-1631-41c6-977e-fb02a4704fcd.jpg)

thanks 
eitan

**Comment by DanielnetoDotCom** [comment]
I found this

            <itunes:owner>
                <itunes:name>
                <![CDATA[ <?php echo $title; ?> ]]>
                </itunes:name>
                <itunes:email>
                <![CDATA[ <?php echo $author; ?> ]]>
                </itunes:email>
            </itunes:owner>

I guess that is the missing part

**Comment by guymass** [comment]
OK I updated and tested again and now the error says this:

![Screen Shot 5783-01-04 at 19 41 40](https://user-images.githubusercontent.com/58882903/193089767-c206bf46-0abc-475f-b354-e7dfcee2e735.jpg)

**Comment by DanielnetoDotCom** [comment]
ok we are getting closer, are you sure you do not have videos on your playlist?

**Comment by guymass** [comment]
Well that URL is from a playlist which has videos so idk what you mean.

**Comment by DanielnetoDotCom** [comment]
Spotify only allow you to share audio files, you MUST share a playlist with audio only

**Comment by guymass** [comment]
Oh ok I thought they extract the audio from the video, I see now, much thanks!

**Comment by DanielnetoDotCom** [comment]
Extract the audio is not a bad idea, but this is not ready yet

I may add this option in the future

**Comment by guymass** [comment]
One more thing when we use the URL in spotify it will send back a message to the site's email and not to the user's email:

![Screen Shot 5783-01-04 at 23 36 10](https://user-images.githubusercontent.com/58882903/193136786-33f05960-8ef2-4c7a-9383-064fc67225e3.jpg)

**Comment by DanielnetoDotCom** [comment]
check this update

**Comment by guymass** [comment]
OK currently it looks good but i`ll keep it for the weekend just to make few more test from other channels just to make sure.
