### ISSUE TITLE
disk-upload-quota - How to change this statement

### ISSUE THREAD

**Issue by jengajenga** [WWBN/AVideo#7172]
<img style="display: block;-webkit-user-select: none;margin: auto;cursor: zoom-in;background-color: hsl(0, 0%, 90%);transition: background-color 300ms;" src="https://user-images.githubusercontent.com/18009293/143444407-7288c117-4546-4382-9d57-e39194903bbe.png" width="437" height="189">

How can i change that statement "buy more storage 100% used" to something else?

**Comment by walt93** [comment]
It makes no sense. Searching the source code, sometimes you find these things, sometimes not. I only see this in the German localization file. I hope Daniel drops some bread crumbs here so I can better understand this code base.

_(If I had "really found" it with this technique, you would see it many times in each localization file, and also where the string is used... FYI & FWIW, YMMV...)_

![Screen Shot 2022-09-25 at 4 03 01 PM](https://user-images.githubusercontent.com/11711050/192169509-37e58411-e638-4eb1-a7da-c09535453e8c.png)

**Comment by jengajenga** [comment]
> It makes no sense. Searching the source code, sometimes you find these things, sometimes not. I only see this in the German localization file. I hope Daniel drops some bread crumbs here so I can better understand this code base.
> 
> _(If I had "really found" it with this technique, you would see it many times in each localization file, and also where the string is used... FYI & FWIW, YMMV...)_
> 
> ![Screen Shot 2022-09-25 at 4 03 01 PM](https://user-images.githubusercontent.com/11711050/192169509-37e58411-e638-4eb1-a7da-c09535453e8c.png)

Thanks for this. I had looooooooooked! I didn't even think about the localisation file. I'll check.

**Comment by jengajenga** [comment]
@DanielnetoDotCom some help here? The solution above did not work for me.

**Comment by DanielnetoDotCom** [comment]
Hi

didn't you try to add the translation??

`$t['Buy More Storage'] = 'Køb mere lagerplads';`

Currently, this option is not customized but it can be translated

**Comment by jengajenga** [comment]
> Hi
> 
> didn't you try to add the translation??
> 
> `$t['Buy More Storage'] = 'Køb mere lagerplads';`
> 
> Currently, this option is not customized but it can be translated

It's not in the en_US version. My site is in English.

**Comment by DanielnetoDotCom** [comment]
Currently, I do not have an option to reword it, only an option for translation.

I may add an update to let you reword it in the future

**Comment by jengajenga** [comment]
> Currently, I do not have an option to reword it, only an option for translation.
> 
> I may add an update to let you reword it in the future

"plugin/DiskUploadQuota/page/buy.php"

@DanielnetoDotCom 

This is where the statement is coming from but it is encrypted.

Can you make it general - **GET/ADD YOUR STORAGE HERE**

My customers see the word PURCHASE and are not even clicking it.

**Comment by DanielnetoDotCom** [comment]
the DiskUploadQuota version 2.1 will let you customize the text

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/193900196-43ea2146-7da0-4397-902f-08e2d1419307.png)

![image](https://user-images.githubusercontent.com/18009293/193900352-d28434ab-239c-43b6-b819-fd5c48a7cb0c.png)

**Comment by jengajenga** [comment]
Thanks @DanielnetoDotCom , this has worked.

Highly appreciated.
