### ISSUE TITLE
Ad Server fell down. Stopped serving ads. Ad campaign still appears valid but it's XML is empty.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7175]
**Describe the bug**
VAST server stopped serving ads. My Roku channel and web site are displaying this:

![Screen Shot 2022-09-25 at 6 39 29 PM](https://user-images.githubusercontent.com/11711050/192177501-8acc250d-41c7-44d5-b948-b250e79c9166.png)

VAST URL is returning nothing. Campaign started with 20,000 prints, has ran >4,000. Now when that campaign is active, it runs the above video.

Running literally any other campaign works, but this one can not be fixed it seems. I created a second campaign and put it up. Hopefully people only had to sit through that for maybe 7 or 8 hours.

TO CLARIFY: there is no reason whatsoever for it to be playing the above. It has MP4 files. It's always had MP4 files. Some other logic has failed and it's displaying this...

**Comment by DanielnetoDotCom** [comment]
you are seeing this video only because the script could not find your video file (for some reason)

also, this is not correct. the HLS format may work now

what video format are you using?

check your log file

**Comment by walt93** [comment]
Ok if I use the https://adserver.conspyre.tv/vast.xml I get a valid XML that has the "MUST be MP4" video link.

If I use the specific campaign link the XML contains videos https://adserver.conspyre.tv/plugin/AD_Server/VAST.php?campaign_id=8

Whatever is breaking, is breaking at that first endpoint.

**Comment by DanielnetoDotCom** [comment]
Please check this update and check if makes any difference

**Comment by walt93** [comment]
It didn't seem to make a difference.

If I load the /vast.xml url which is giving the "Must be MP4" video, it logs exactly one line to avideo.log

`[26-Sep-2022 15:28:59 America/Los_Angeles] AVideoLog::DEBUG: VastCampaignsVideos has not a valid link:  SCRIPT_NAME: /plugin/AD_Server/VAST.php`

**Comment by DanielnetoDotCom** [comment]
check what type of video you have on your campaign (make sure and double-check if it is MP4 or HLS), and also check your log file.

**Comment by walt93** [comment]
It's all MP4 (no HLS), and I did check the log file - when I access the /vast.xml and that campaign is active - it logs only one line (see last reply). Maybe you can put some extra logging in here so we can catch what's going on?

**Comment by DanielnetoDotCom** [comment]
First fix the ssl

![image](https://user-images.githubusercontent.com/18009293/192397783-857766b6-4896-41ff-9a74-6b1b29c2eefe.png)

**Comment by walt93** [comment]
How did I miss that? I just took the machine off of Cloudflare last night...
