### ISSUE TITLE
Default "Netflix" platform user, best options

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7179]
@DanielnetoDotCom 
Hi Dani, my project is based on a streaming platform and not a collaboration . So the user does not upload files to the site.
In this way I would like to simplify the menu available for the non-admin user. Removing the MY CHANNEL buttons and the Organize Programs button. It is possible?

![image](https://user-images.githubusercontent.com/37880073/192298847-617876e7-0bbe-47c1-a8ce-0a1a94a4dd4e.png)

Within MY ACCOUNT, you could also have the option to remove some elements such as: Channel name, Analytics Code, About, Channel Art.
Is there any way I can remove this?

![image](https://user-images.githubusercontent.com/37880073/192310039-d254480b-8644-4460-94e0-617b4930bb01.png)

**Comment by DanielnetoDotCom** [comment]
the thing is the channel page is where you manage your playlists

**Comment by gbrn** [comment]
@DanielnetoDotCom Dani, the problem I see is that the admin user is not actually a login Master. The admin user is a regular user with administrative privileges. It's not that?
The solution would be a Master login, which is not directly linked to the users table and their roles.

**Comment by gbrn** [comment]
@DanielnetoDotCom Dani, thinking better here... the menu of buttons that displays is different from the administrator and the common user. So isn't it just a matter of changing the selector of items that should or should not appear?

**Comment by DanielnetoDotCom** [comment]
if you are talking about the admin login only, the thing is, usually the AVideo admin can do everything. in most of the privileges checks if you are admin it will return true.

but maybe in the future, I will move the playlist manager to somewhere else and then I will be able to remove the channel info for those who do not have upload rights. (admin always have upload rights)
