### ISSUE TITLE
Is there a chapter option

### ISSUE THREAD

**Issue by JeanDavis91** [WWBN/AVideo#7180]
Hello

I would like to know if there is an option for chapters because I did not find anything in the v12.1 version

This is important when you have a mix of several videos that lasts more than 11:00!

Thank you for your excellent work that I pay for my facos by buying plugins, I have already bought 5!

good evening

![chapitre](https://user-images.githubusercontent.com/61474191/192328131-1432c20a-c80c-420a-bb0d-6653bc0e0e45.jpg)

**Comment by DanielnetoDotCom** [comment]
Thanks for your support, currently we do not have this option.
