### ISSUE TITLE
Chat plugin download issues

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#7182]
Daniel,
I have just purchased the chat plugin but I cannot able to download it. My laptop windows defender is blocking it. It says virus threat is detected.
![image](https://user-images.githubusercontent.com/25535711/192343286-e1e58570-9816-42c8-806b-1e850b3539b0.png)

**Comment by DanielnetoDotCom** [comment]
Hi

it is not a virus, but some times this is flagged as a virus because the PHP code is obfuscated

**Comment by mankota** [comment]
I turned of the antivirus and downloaded that. I installed it. I see 3 options in the plugin but I don't know which one is use for what?
![image](https://user-images.githubusercontent.com/25535711/192415846-c1bbe356-e142-4fbb-a9aa-6dcda36fc970.png)

**Comment by DanielnetoDotCom** [comment]
you do not need to use any of them

maybe you need to check the parameters for a finetuning.
