### ISSUE TITLE
Broken Missing Files

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7185]
**Describe the bug**
I don't even know where to begin. You put a file in the encoder. You notice that it says "Broken missing files" after it encodes.

You click on the filter in /mvideos to see if there are other broken files.

You recoil in horror at the sheer number; pages of them, not realizing when the site began eating itself, going back for months...

[This is a rhetorical report lol, files that I uploaded a year ago are showing up here **and I've already gone through this exercise before, just didn't report it then. Something about this database is _incredibly buggy_ Daniel]**

**Comment by DanielnetoDotCom** [comment]
try to open the video even with the missing file's label. some times it fixes by itself. 

if does not fix, it means some error happens and you may need to resubmit the video.

**Comment by walt93** [comment]
The errors have happened in the past. I'm not sure it's even possible to debug. {big sad emoji}

Pretty sure that some of the recent errors are due to Cloudflare. As you said. More problems than solutions!
