### ISSUE TITLE
Unable to enter other user's chat room

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#7189]
Unable to enter other user's chat room

![image](https://user-images.githubusercontent.com/47063171/192733237-452e35e4-bbcb-4ffb-8f75-5a4c7ff11182.png)

**Comment by DanielnetoDotCom** [comment]
seems to be a JS error, please check your JS console.

**Comment by chenjian9885** [comment]
Hi, I'm sorry I don't know much about js

**Comment by chenjian9885** [comment]
I found that I can enter my chat room but not the chat rooms of other users

**Comment by DanielnetoDotCom** [comment]
can you reproduce this on demo site? https://demo.avideo.com/

**Comment by chenjian9885** [comment]
Sorry I can't reproduce it I had this issue after updating the streamer and plugins

**Comment by DanielnetoDotCom** [comment]
if the issue is related to the code, it should also happen on the demo site. the demo site is up to date

**Comment by chenjian9885** [comment]
yes maybe it's my ubuntu problem, i'm checking check

**Comment by DanielnetoDotCom** [comment]
I still think you should check your JS console

https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform#javascript-errors
