### ISSUE TITLE
Uploaded (Video_Location_Block) plugin but unable to perform update

### ISSUE THREAD

**Issue by chenjian9885** [WWBN/AVideo#7190]
Uploaded (Video_Location_Block) plugin but unable to perform update
![image](https://user-images.githubusercontent.com/47063171/192733772-ec2d6b46-79be-44d8-a37f-3ca75fbfd9a5.png)
![image](https://user-images.githubusercontent.com/47063171/192733879-c7d9a568-05ab-4edb-9c28-46bcb277a69d.png)

**Comment by DanielnetoDotCom** [comment]
try to manually delete the Video_Location_Block plugin folder, then upload it again

**Comment by chenjian9885** [comment]
Okay, thank you
