### ISSUE TITLE
FFPMEG and strict option

### ISSUE THREAD

**Issue by tbprince** [WWBN/AVideo#7191]
We have (re)installed our servers and (re)deployed AVideo. We also installed a separated encoder and it seemed to work fine but we noticed that it wasn't encoding videos. We noticed an error code 2 then used logs to check which is the command that the encoder was trying to send to FFMPEG.

Long story short, after trying to issue the same command manually from the command line on the encoder itself, we notice this kind of error:

_Unrecognized option 'strict'._

However, sending the same command without the "-strict" option was working fine, at least it seems so. We were using FFMPEG v4 so we decided to update to v5.1.1 while Encoder version is the latest (v4.0).

All of the commands on the encoder seem to include the strict option, such as

_ffmpeg -i {$pathFileName} -vf scale=-2:540 -movflags +faststart -preset veryfast -vcodec h264 -acodec aac -strict -2 -max_muxing_queue_size 1024 -y {$destinationFile}_

Is this something expected? Since _strict_ is not supported on the latest FFPMEG, shall we downgrade to a specific version?

This is the version of FFPMEG we have installed:

_ffmpeg version 5.1.1-0ubuntu1~22.04.sav0 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)_

This is the error that encode is showing inside queue log:

_Execute code error 2 "" Code: ffmpeg -i /var/www_

Thanks.

**Comment by jengajenga** [comment]
Maybe remove the strict option from the avideo code itself? That way you don't mess around with ffmpeg.

**Comment by tbprince** [comment]
> Maybe remove the strict option from the avideo code itself? That way you don't mess around with ffmpeg.

Yes, this is an option but it wasn't necessary when we installed last time and I wonder if it might have any impact. That's why I opened this issue before removing the option. :-)

**Comment by DanielnetoDotCom** [comment]
I will remove that

**Comment by DanielnetoDotCom** [comment]
You may be able to edit the current encoder installation on the configuration tab

or just drop the encoder database and install it again

**Comment by tbprince** [comment]
We decided to edit the configuration. It worked fine. We just removed the _-strict -2_ where included.

Thanks.
