### ISSUE TITLE
Make a list

### ISSUE THREAD

**Issue by JeanDavis91** [WWBN/AVideo#7192]
Hello

I don't understand how to do this

![serie](https://user-images.githubusercontent.com/61474191/192902064-58fb4a83-18ae-4ad1-902c-497c5028f306.jpg)
![serie 2](https://user-images.githubusercontent.com/61474191/192902069-63d61e25-e2a6-4cd7-8141-5f62c516bf5d.jpg)

**Comment by DanielnetoDotCom** [comment]
Make sure you have the playlist plugin enabled

https://github.com/WWBN/AVideo/wiki/Program-(Playlist)-to-series

**Comment by JeanDavis91** [comment]
Hello

I managed to make my playlist and it works perfectly thank you.
I had a little trouble understanding the implementation but I found

video ok
ok series
Collections is what?

I will make video tutorials on Avideo (user manual and configuration procedure)

Thank you for this very good work

jfr

**Comment by DanielnetoDotCom** [comment]
where did you see the Collections??

**Comment by JeanDavis91** [comment]
Hello DanielnetoDotCom

I found this list here https://alive528.com

Have a good evening

jfr
