### ISSUE TITLE
Get video URLs from CDN

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7193]
**Is your feature request related to a problem? Please describe.**
I am using my AVideo site manage files on a CDN, and need to get the URLs to videos on the CDN for various workflows. Getting the URL from page source is tedious.

**Describe the solution you'd like**
1. On the /mvideos page we've got some vertical space in the Tags we can use2. 

![Screen Shot 2022-09-28 at 10 51 12 PM](https://user-images.githubusercontent.com/11711050/192949747-d02f7326-7e9c-453e-9f78-32c5b77938b0.png)

3 In Categories [RSS,MRSS,Roku] and Programs, a new button here to generate a human-readable JSON (with CR/LF) that has all the video URLs and the video title and duration.

![Screen Shot 2022-09-28 at 11 01 46 PM](https://user-images.githubusercontent.com/11711050/192951355-5b40760e-aeee-4b44-af58-e511c6f11a7b.png)

```
{
  "Videos" : [
    {
      "name" : "My Great Movie",
      "duration" : "01:39",
      "duration_in_seconds" : "5940",
      "urls" : [
        {
          "url" : "[https://](https://conspyre-bumpers.s3.us-west-1.wasabisys.com/video_220831052254_v130b_1080.mp4)",
          "resolution" : "1920x1080"
        }
      ]
    }
  ]
}
```
We can read this by hand, or write further scripts to use them for say, Ant Media Server (24/7 media loop player), or other external services.

**Comment by DanielnetoDotCom** [comment]
Hi, I do not understand. 

DO you need to get the direct link to your video files?

also, get all the different resolutions?

**Comment by walt93** [comment]
Yes. I need to get a link to video files on the CDN for different workflows, adding to Ant Media Server, using external ad servers, lots of reasons to get that URL.

I have to view page source, and hunt down the video URL each time. If I could throw a bunch of videos into a program and get a text file - would make this work go much faster.

**Comment by DanielnetoDotCom** [comment]
did you try to use the API?

https://github.com/WWBN/AVideo/wiki/AVideo-Platform-API

for example, with this endpoint you can get all resolutions

https://demo.avideo.com/plugin/API/get.json.php?APIName=video&videos_id=388

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/18009293/193121546-a7738e83-db82-427d-ad43-4c7174358ad1.png">

**Comment by walt93** [comment]
This isn't really a solution. 

What I'm finding is that the ad server is unstable, and I'm looking at other options. All of them involve getting the URL for our video, and the use case is I need for users to load these URLs into an adserver. I need an interface for them to get the URL, something to click and get it into the clipboard.

How can a user get the URL to a video which they have uploaded? That's the use case to solve.

**Comment by DanielnetoDotCom** [comment]
Sorry I do not have that

**Comment by walt93** [comment]
You do if you add code similar to this to `/view/managerVideos_body.php`

```
                                                if (row.filename && row.filename !== '' && row.maxResolution && row.maxResolution.resolution_string && row.maxResolution.resolution_string !== '0p') {
                                                   $res = row.maxResolution.resolution_string.substr(0, row.maxResolution.resolution_string.length - 1)
                                                   $xname = "https://conspyre-1.s3.us-west-1.wasabisys.com/" + row.filename + "_" + $res + ".mp4";
                                                   tags += "<div class=\"clearfix\"></div>"
                                                   tags += "<span class='label label-primary tagTitle'><?php echo __("Filename") . ":"; ?> </span>"
                                                   tags += "<span class=\"label label-default \">"
                                                   tags += "<a href=\"#\" class=\"icoCopy\" onclick=\"copyToClipboard('" + $xname + "');$(this).closest('.modal').modal('hide');return false;\" >"
                                                   tags += row.filename
                                                   tags += "</a></span>";
                                                }
```

I wasn't able to figure out how to get my bucket URL from this spot in the code, so had to hard-code the value 🫤

**Comment by DanielnetoDotCom** [comment]
Hi, so do you mean each user should be able to get a direct URL to his video files?

for each resolution?

I am not sure if this is something the user should play around with; 

for example, on the channel, you can get the roku.json https://demo.avideo.com/channel/HillsongUNITED/roku.json

that includes all the video files.

![image](https://user-images.githubusercontent.com/18009293/193575740-44aec87b-abe0-48eb-a883-a93291e69433.png)

also you will find the image links

![image](https://user-images.githubusercontent.com/18009293/193575901-1cd2a250-1670-44cb-a977-c8b3924ee67c.png)

what you want is still not clear to me, and I still think the end user should not access the video links directly. 

if you need some different type of feed we should build it just like we did with the roku.json

**Comment by walt93** [comment]
I'm thinking how this should work. One example. I'm using Ant Media Server to run a looping playlist. - will be used to back the RTMP stream when there's no RTMP connection, giving us a 24/7 channel on Roku.

In this case "user" is a podcaster that has his own private RTMP & media server, and will be setting up the UI you see below.

Hmm... I see your point, they can just pick it out of the JSON - but I think the JSON is a bit overwhelming, maybe the feature is a [FILES] button next to Roku/RSS/MRSS and it's just a text file.

![Screen Shot 2022-10-03 at 2 32 11 PM](https://user-images.githubusercontent.com/11711050/193688004-531a21ca-cd00-45b1-9c62-1c9d1dd34e1a.png)

**Comment by DanielnetoDotCom** [comment]
I do not know an ant media server but it may have some type of file that you can import a video list

**Comment by walt93** [comment]
The basic Ant media server does not, it just has the crappy UI you see above (that doesn't have scroll, you can only put in as many videos as you have screen real estate for) - Revive ad server also seems just to have a web interface to paste URLs.

I think perhaps a [VIDEO_URLS] button next to RSS MRSS and ROKU would make this workflow easier. It just needs a list with the video's name/resolution and URL. Probably the URL sitting on its own line so you can triple-click-copy-paste it.

**Comment by walt93** [comment]
![Screen Shot 2022-10-07 at 1 14 31 PM](https://user-images.githubusercontent.com/11711050/194645763-2f405f8f-3ace-482e-a016-6d4b9024c068.png)

Maybe this is an admin function?

I don't know but I have been using the hell out of it this morning………

**Comment by DanielnetoDotCom** [comment]
Please check this update, it will show the source files 

![chrome-capture-2022-9-10](https://user-images.githubusercontent.com/18009293/194892438-2cab4bcd-03b6-47e6-a126-d3826643ec57.gif)
