### ISSUE TITLE
I paid for a plugin but I have no idea where to download it from...

### ISSUE THREAD

**Issue by Geoff-Hurst** [WWBN/AVideo#7194]
I purchased the Customize Footer, About and Meta Description plugin from the avideo plugins website.

I received an acknowledgement by email... and... what now?

![dn](https://user-images.githubusercontent.com/25431085/192966691-c826d57f-a908-4f0d-a9de-18567622fc7e.png)

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin

**Comment by Geoff-Hurst** [comment]
Thanks.
