### ISSUE TITLE
Need to reset password in DB

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7196]
I need to reset a password for an admin but I need to do it from the database. What is the type of password hash I need to select in PHPMyAdmin under the user's password field.

Thank for your help.

**Comment by DanielnetoDotCom** [comment]
you cannot reset it directly into the database

but you can use the command line to reset it 

https://github.com/WWBN/AVideo/wiki/Reset-a-Password#how-to-reset-a-password-with-ssh

**Comment by guymass** [comment]
Thanks, yes I figured it out you need to go to the /install directory and run the PHP password recovery script.
