### ISSUE TITLE
Fixing CORS issues on LAN installation

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7197]
I am trying to setup AVideo on my local LAN and I have a reverse ssh proxy setup to redirect all traffic to the server on my local machine. I was able to install the script and I can open the site from outside world using TOR browser, however I have couple of issues:

On the TOR browser everything loads fine however I cannot login to the site it keeps sending me back to home page.

On my local machine when I open the site I get a lot of mixed content issues as in the following Screenshots:

![Screen Shot 5783-01-04 at 14 56 04](https://user-images.githubusercontent.com/58882903/193025733-cdce456c-227b-4507-834d-ff5b48125916.jpg)
![Screen Shot 5783-01-04 at 14 55 57](https://user-images.githubusercontent.com/58882903/193025757-e654d117-403c-4823-8a25-f822ac3e3ac4.jpg)

So my question is, how come from my local machine I get all those cors errors, but from the outside the site loads without any issue but I cannot login.

How can I fix these mixed content issue?

The site is at https://tube.feisafe.com

Thanks for any help.

**Comment by guymass** [comment]
This is the error I get when trying to login:
![Screen Shot 5783-01-04 at 15 29 09](https://user-images.githubusercontent.com/58882903/193031498-57fbf7f1-a70f-4e93-aca4-a817c70a068d.jpg)

**Comment by DanielnetoDotCom** [comment]
That is what I got

<img width="435" alt="image" src="https://user-images.githubusercontent.com/18009293/193037557-fb0b1d9c-11e9-4745-818c-0a7747860fd2.png">

I cannot help you with your network configuration

the "contentSearchFound" is not an error, it is just a debug log

**Comment by guymass** [comment]
ok thanks bro
