### ISSUE TITLE
Hide header on embed doesn't seem to work anymore

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7198]
Did something change? Now when I embed a page it shows the header again

**Comment by DanielnetoDotCom** [comment]
what header exactly?

**Comment by JoshWho** [comment]
When I embed paged like in the menu it use to hide the headers on those pages. Now it doesn't

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/193055835-771ceb66-2ae7-4099-96f6-f733aebffe5d.png)

If you mean the header above, there is nothing I can do, I do not control this page

**Comment by JoshWho** [comment]
It use to. There was a CSS trick doing it. Now it is no longer that is why I even brought this up. Maybe it wasn't intentionally designed for this whatever it was, but it was working now it is not. Just pointing out a change that has happened.
