### ISSUE TITLE
Limit Ads from Videos and Channels

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7200]
We currently see this new option to limit the ads from videos however this would be much appreciated of it could be also set per channel as we have some users we would like to limid ads from their videos and they have many, it would take a long time to set this for each one. What do you say champ, is it doable :-)

![photo_2022-09-30 17 45 52](https://user-images.githubusercontent.com/58882903/193296240-c52f6af4-915a-46f8-9b21-b385fb5e008c.jpeg)

**Comment by DanielnetoDotCom** [comment]
Great idea, I will send an update for that later
