### ISSUE TITLE
The replay of the films no longer works!

### ISSUE THREAD

**Issue by JeanDavis91** [WWBN/AVideo#7202]
Hello

I noticed on Avideo v12.1 that resuming movies no longer works even on the demo site of Avideo
It resumes playback from the beginning

![reprise](https://user-images.githubusercontent.com/61474191/193358266-b2f6d3da-7661-4c79-bfe7-ab7f2342af55.jpg)

jfr

**Comment by DanielnetoDotCom** [comment]
I will send some updates regarding the time controll soon. but I am not detecting any issue on my side

Also I have tested on demo site nad seems to be fine for me
