### ISSUE TITLE
live stream won't working

### ISSUE THREAD

**Issue by mypride-Fortis** [WWBN/AVideo#7204]
Hello guys
I recently installed AVideo. All seems working but the Live stream.
When OBS was set up it gave the error "Could not access the specified channel or stream key. please double-check your stream key/ If it is correct there may be a problem connecting to the server"
So I checked past issus - unable to make live stream working #6970, 
I then followed the instruction but same I got
it looks as if I did not set the NGIX correctly. I then use the curl -I http://mysite.com/plugin/Live/on_publish.php
The error message was
http:/1.1 404 not found

Can you please help me
![rtmperver](https://user-images.githubusercontent.com/42104400/193440473-15419368-77d4-496d-bfda-d439169d55f8.PNG)

**Comment by mypride-Fortis** [comment]
when I tested the /stat function The Log error 
 [02-Oct-2022 06:01:45 Africa/Abidjan] AVideoLog::ERROR: Live::getStatsObject RTMP Server (https://www.mysite.com:8443/stat) is OFFLINE, timeout=(4) we could not connect on it => live_servers_id = (2)  SCRIPT_NAME: /view/index.php

**Comment by mypride-Fortis** [comment]
> check the on_publish parameter at your nginx.conf
> 
> it MUST be HTTP and cannot redirect to HTTPS
> 
> [#6970 (comment)](https://github.com/WWBN/AVideo/issues/6970#issuecomment-1216725011)

Thank you so much Daniel, 
I have the On_publish set at http://
The only thing I did not include which I removed during the installation was the localhost i.e
on_publish http://localhost/mysite.com

What I have presently is 
on_publish http://mysite.com/plugin/Live/on_publish.php;
                            on_publish_done http://mysite.com/plugin/Live/on_publish_done.php;
                            on_play http://mysite.com/plugin/Live/on_play.php;
                            on_record_done http://mysite.com/plugin/Live/on_record_done.php;

I'm I suppose to add the localhost to the on_publish?
Thank you one more time.

**Comment by DanielnetoDotCom** [comment]
no, 

you have to make sure the http://mysite.com/plugin/Live/on_publish.php; is accessible thru your server, and again 

THE HTTP CANNOT REDIRECT TO HTTPS

**Comment by mypride-Fortis** [comment]
After checking I decided to do the curl -I http://mysite.com/plugin/Live/on_publish.php substituting the mysite.com with my real site name, this is what I got

# curl -I http://mysite.com/plugin/Live/on_publish.php
HTTP/1.1 301 Moved Permanently
Date: Mon, 03 Oct 2022 17:16:53 GMT
Server: Apache/2.4.41 (Ubuntu)
Location: https://mysite.com/plugin/Live/on_publish.php
Content-Type: text/html; charset=iso-8859-1

Wondering if I have to re instal ngix.

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/193643289-80e29ab8-3782-4006-9387-75126a3b0ad6.png)

try to use the IP instead of the domain name, and DO NOT REDIRECT TO HTTPS

**Comment by mypride-Fortis** [comment]
Thank you for your guide. Unfortunately I have  added listen 444 ssL; and also listen -ip; in the server section of the ngix configuration but it won't change from https. Guess I don't know what to do. so I checked some guides and found this, 
**9. in case you use an HTTPS connection you may need to Enable secure WebSocket
sudo nano /etc/apache2/mods-available/proxy.conf

Add : ProxyPass /wss/ ws://127.0.0.1:8888/

Make the file looks like this :

![image](https://user-images.githubusercontent.com/42104400/193654157-11259395-6bf3-40ea-8d37-a326e9cb055e.png)

Enable the module and restart apache

sudo a2enmod proxy_wstunnel

/etc/init.d/apache2 restart**

Is this what I should do?

**Comment by mypride-Fortis** [comment]
Thank you Daniel'
I used my IP address instead of the domain name but unfortunately the Location is still showing https://mysite.com....
Please at this time kindly help check the configuration , Probably I ommited an item, Ngix conf is as shown below


user    www-data;
worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    buflen 1000ms;
                    chunk_size 4096;
                    ping_timeout 30s;
                    ### Use case option (max_streams; default is 32 )
                    #max_streams 10;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video man>
                    application live {
                            allow play all;
                            live on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            hls_playlist_length 60m;
                            hls_fragment 4s;
                            drop_idle_publisher 30s;
                            sync 500ms;
                            #Experimental. Force dropped stream, or ended stream from being watched. (idle_streams)
                            #idle_streams off;
                            on_publish http://myIP/plugin/Live/on_publish.php;
                            on_publish_done http://myIP/plugin/Live/on_publish_done.php;
                            on_play http://myIP/plugin/Live/on_play.php;
                            on_record_done http://myIP/plugin/Live/on_record_done.php;



                            #exec ffmpeg -re -i rtmp://localhost/live/$name -c:v libx264 -preset veryfast -c:a copy -f hls -hls_time 5 -hls_list_size 0 -f flv r>
                            #exec ffmpeg -re -i rtmp://localhost/live/$name
                            #    -c:v libx264 -vf scale=-2:240 -r 20 -g 40 -keyint_min 40 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1>
                            #    -c:v libx264 -vf scale=-2:480 -r 30 -g 60 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize>
                            #    -c:v libx264 -vf scale=-2:720 -r 30 -g 60 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 3000k -bufsize>


                            #recorder video {
                            #    record all manual;
                            #    record_path /var/www/tmp;
                            #    record_notify on;
                            #    record_max_size 2048M;
                            #    record_suffix -%d-%b-%y-%T.flv;
                            ###If live-stream is over 30FPS and you want to limit it to 30FPS recording to light the encoding task #record_max_frames 30;
                            #    ## record_max_frames 30;
                            #}

                            ### Record Audio Separately ( For podcast )
                            #recorder audio {
                            #    record audio;
                            #    record_path /var/www/tmp;
                            #    record_max_size 1024M;
                            #    record_suffix -%d-%b-%y-%T.mp3;
                            #}
                    }

                    #application adaptive {
                    #    live on;
                    #    hls on;

                    #    hls_path /HLS/live;
                    #    hls_nested on;
                    #    hls_playlist_length 10m;
                    #    allow play all;
                    #    allow publish 127.0.0.1;
                    #    deny publish all;

                    #    hls_variant _hi BANDWIDTH=264000,RESOLUTION=1280x720; # this is for line 34 only, do not uncomment it

                    #    hls_variant _low BANDWIDTH=900000;
                    #    hls_variant _mid BANDWIDTH=2400000;
                    #    hls_variant _hi  BANDWIDTH=3500000;
                    #}
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    #listen 8443 ssl;
                    #listen [::]:8443 ssl;
                    #include /usr/local/nginx/snippets/self-signed.conf;
                    #include /usr/local/nginx/snippets/ssl-params.conf;
                    listen 8080;
                    listen 444 ssl;
                    server_name mysite.com;
                    ssl_certificate /etc/letsencrypt/live/mysite.com/fullchain.pem;
                    ssl_certificate_key /etc/letsencrypt/live/mysite.com/privkey.pem;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"
                    location /live {
                            expires 60;
                            add_header 'Cache-Control' 'public';

                            location ~ \.m3u8$ {
                                expires -1;
                                # Disable cache
                                add_header 'Cache-Control' 'no-cache';

                                # CORS setup
                                add_header 'Access-Control-Allow-Origin' '*' always;
                                add_header 'Access-Control-Expose-Headers' 'Content-Length';
                            }

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';


                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            # replace this with the IP of your AVideo site
                            allow 127.0.0.1;
                            deny all;
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }

                    #location ~ \.php$ {
                    #       include /etc/nginx/snippets/fastcgi-php.conf;
                    #       fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
                    #}

            }
    }

**Comment by mypride-Fortis** [comment]
I shall remain grateful for your kindness. Thank you.

**Comment by DanielnetoDotCom** [comment]
share the output for `curl -I http://myip/plugin/Live/on_publish.php`

**Comment by mypride-Fortis** [comment]
Thanks for your response. the output for curl -I http://myip/plugin/Live/on_publish.php as shown at the terminal is as follows:

HTTP/1.1 404 Not Found
Date: Tue, 04 Oct 2022 16:18:32 GMT
Server: Apache/2.4.41 (Ubuntu)
Content-Type: text/html; charset=iso-8859-1

Thanks

**Comment by DanielnetoDotCom** [comment]
`HTTP/1.1 404 Not Found`

Fix it to the correct URL

**Comment by mypride-Fortis** [comment]
Thank you
When I did curl -I http://mysite/plugin/Live/on_publish.php I got:
HTTP/1.1 301 Moved Permanently
Date: Tue, 04 Oct 2022 17:29:22 GMT
Server: Apache/2.4.41 (Ubuntu)
Location: https://mysite/plugin/Live/on_publish.php
Content-Type: text/html; charset=iso-8859-1

However when I did curl -I https://mysite/plugin/Live/on_publish.php I got:
HTTP/1.1 401 Unauthorized Error
Date: Tue, 04 Oct 2022 17:32:03 GMT
Server: Apache/2.4.41 (Ubuntu)
Set-Cookie: key=value; secure; SameSite=None
Set-Cookie: 84b11d010cced71edffee7aa62c4eda0=e6ng6o765aitare6m9qtoupikq; expires=Tue, 04-Oct-2022 18:32:03 GMT; Max-Age=3600; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: max-age=1, private, must-revalidate
Pragma: no-cache
Set-Cookie: yptDeviceID=5da6a416-ff60-4ba8-8df8-607a4fb2740a; expires=Wed, 04-Oct-2023 17:32:03 GMT; Max-Age=31536000; path=/; domain=e-vidbox.com; secure; HttpOnly; SameSite=None
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,HEAD,OPTIONS,POST,PUT
Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
Vary: Accept-Encoding
Content-Type: text/html; charset=UTF-8

I did that based on the on_publish parameters using myip. Is that what you want me to do?
Thanks

**Comment by DanielnetoDotCom** [comment]
`HTTP/1.1 401 Unauthorized Error` is expected but it cannot be https

you must receive the 401 code without https

**Comment by mypride-Fortis** [comment]
You said in other chats that it is not an Apache rewrite issue but Ngix. I am so confused now that I don;t know how to go forward. I had tried mysite.com and myip and both failed. If you don't mind giving a hand, please.

**Comment by DanielnetoDotCom** [comment]
that is why I am telling you to use the IP, but the URL with the IP must be valid. 

I cannot teach you how to configure sites on apache.

**Comment by JoshWho** [comment]
mysite.com is just suppose to be a reference to your real domain.  It doesn't literally mean mysite.com. If this whole entire time you have been running commands with it that is your problem.
