### ISSUE TITLE
Received errors after loading customize plugin

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#7213]
Hi 

Received following errors after loading customize plugin:- What do I need to do ?
--------------------------------------------
array(4) { ["type"]=> int(1) ["message"]=> string(758) "Uncaught Error: Class "ScssPhp\ScssPhp\Compiler" not found in /var/www/html/AVideo/plugin/Customize/sass/compile.php(18) : eval()'d code(1) : eval()'d code:15 Stack trace: #0 /var/www/html/AVideo/plugin/Customize/sass/compile.php(18) : eval()'d code(1): eval() #1 /var/www/html/AVideo/plugin/Customize/sass/compile.php(18): eval() #2 /var/www/html/AVideo/plugin/Customize/Customize.php(18) : eval()'d code(1) : eval()'d code(54): include('...') #3 /var/www/html/AVideo/plugin/AVideoPlugin.php(632): Customize->getStart() #4 /var/www/html/AVideo/objects/include_config.php(167): AVideoPlugin::getStart() #5 /var/www/html/AVideo/videos/configuration.php(47): require_once('...') #6 /var/www/html/AVideo/view/index.php(7): require_once('...') #7 {main} thrown" ["file"]=> string(93) "/var/www/html/AVideo/plugin/Customize/sass/compile.php(18) : eval()'d code(1) : eval()'d code" ["line"]=> int(15) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(758) "Uncaught Error: Class "ScssPhp\ScssPhp\Compiler" not found in /var/www/html/AVideo/plugin/Customize/sass/compile.php(18) : eval()'d code(1) : eval()'d code:15
Stack trace:
#0 /var/www/html/AVideo/plugin/Customize/sass/compile.php(18) : eval()'d code(1): eval()
#1 /var/www/html/AVideo/plugin/Customize/sass/compile.php(18): eval()
#2 /var/www/html/AVideo/plugin/Customize/Customize.php(18) : eval()'d code(1) : eval()'d code(54): include('...')
#3 /var/www/html/AVideo/plugin/AVideoPlugin.php(632): Customize->getStart()
#4 /var/www/html/AVideo/objects/include_config.php(167): AVideoPlugin::getStart()
#5 /var/www/html/AVideo/videos/configuration.php(47): require_once('...')
#6 /var/www/html/AVideo/view/index.php(7): require_once('...')
#7 {main}
  thrown"
  ["file"]=>
  string(93) "/var/www/html/AVideo/plugin/Customize/sass/compile.php(18) : eval()'d code(1) : eval()'d code"
  ["line"]=>
  int(15)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}

**Comment by DanielnetoDotCom** [comment]
On what page exactly are you seeing this error?

how did you upload the plugin?

**Comment by kollossus55** [comment]
This is the main page.. I uploaded plugin as per instructions. Logged in into marketplace, downloaded plugin. I then uploaded to website..

**Comment by DanielnetoDotCom** [comment]
can you please run a git pull and check if the error persists?

**Comment by kollossus55** [comment]
Will do... On it now...

**Comment by DanielnetoDotCom** [comment]
please run a git pull and check again. I could not reproduce it here

**Comment by kollossus55** [comment]
Hi

I tried.. its now in maintenance..

Please advise..

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DanielnetoDotCom** [comment]
check your log file, 

also what PHP version are you using?

**Comment by kollossus55** [comment]
Hi 

I reloaded the plugin, and it seems to have worked ok..  Server health is good... PHP is  v8.1.9


Checked the logfile and found these errors..Are these ok?
--------

![kollossusweb logfile](https://user-images.githubusercontent.com/53856825/193787793-3199222f-e060-4d6c-adeb-5480dc93cdbf.png)

**Comment by DanielnetoDotCom** [comment]
delete the log file and keep your eyes open. I am pretty sure most of the errors were due to the bad plugin upload you have made

**Comment by kollossus55** [comment]
Ok..

Everything seems fine now..

Where does the logfile reside, to double check..

Will delete and monitor...

Thanks
________________________________

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by kollossus55** [comment]
ok thanks..

Closing issue...
