### ISSUE TITLE
Spelling error in email

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#7216]
Should read "uploaded"

![Screenshot_20221004_071632.jpg](https://user-images.githubusercontent.com/66537018/193806122-77b8a8dd-0b65-43c9-bd13-d40fb1795dcc.jpg)

**Comment by DanielnetoDotCom** [comment]
Thanks

the default text will be updated, but you also chan change it here 

![image](https://user-images.githubusercontent.com/18009293/193892607-f4dd57c5-cb49-4569-9543-1ce80a4d3a3b.png)

**Comment by fakeologist** [comment]
Also comment change to commented

**Comment by DanielnetoDotCom** [comment]
> Also comment change to commented

where?
