### ISSUE TITLE
Encoder Broke since AVideo Update

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#7217]
Same issue opened on AVideo-Encoder.

Logs attached...

Live, MP4, YouTube, doesn't matter nothing converts properly on all encoders (have 3). This just started after AVideo pull earlier today...

[AVideo-Log.pdf](https://github.com/WWBN/AVideo/files/9709821/AVideo-Log.pdf)
[Encoder-AVideo-Log.pdf](https://github.com/WWBN/AVideo/files/9709822/Encoder-AVideo-Log.pdf)

**Comment by DanielnetoDotCom** [comment]
I am not seeing any error on your logs.

make sure both are up to date, encoder and streamer

**Comment by GreenDragonTavern** [comment]
Just created a new encoder, AVideo up to date...Have HLS plugin and specified HLS via encoder. It gave me an MP4.

**Comment by DanielnetoDotCom** [comment]
I found the issue, please update

**Comment by GreenDragonTavern** [comment]
Thank you, that seems to have solved all. Tested live, YouTube download, MP4 and MKV off disk all encoded properly. Appreciate prompt fix and your effort!
