### ISSUE TITLE
Hide or randomize video ID in embed code.

### ISSUE THREAD

**Issue by smaku14** [WWBN/AVideo#7220]
Hello all,

First the following scenario. My youPHPtube page is public and contains only unlisted videos. So, should someone stray to the page, no videos will be shown to them. (Which is fine.) The videos should only be visible if they are embedded on other web pages.

Videos that are uploaded are assigned an ascending ID.

For example:
https://**xx**x**.com/v/375
https://**xx**x**.com/v/376
etc.

This ID is also visible in the embed code. So if a user examines the source code of a page where one of my videos is embedded, he can easily find the ID of the video. Now if he goes for it and randomly swaps the IDs in the link, he can get access to videos he shouldn't have access to.

So my question is, how can I prevent this? Is there any way to hide the video ID in the embed code? Or maybe randomize or manually adjust the link / embed code? 

Thanks in advance!

**Comment by DanielnetoDotCom** [comment]
To prevent other sites to embed your videos check this

https://github.com/WWBN/AVideo/wiki/SecureVideosDirectory-Plugin#restrict-embed-videos

To make the ID harder to guess, try this

![image](https://user-images.githubusercontent.com/18009293/194335782-ed8e8100-b97f-474b-a72d-8fd2cec3b44a.png)

**Comment by smaku14** [comment]
Thanks a lot! That will do the trick.
