### ISSUE TITLE
Top Menu got larger for no reason

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7221]
I have a new installed AVideo site, when I open the site after last update, when not logged in I see the menu OK in height, but after I log in the top menu gets larger and I don't know why. This is how it appears after a login:

![Screen Shot 5783-01-12 at 12 39 26](https://user-images.githubusercontent.com/58882903/194524514-406c8615-f750-470b-8281-6e4e2b0dc102.jpg)

Notice that the notification bell is duplicated.

**Comment by DanielnetoDotCom** [comment]
did you update it correctly?

the live bell should not be there. it was replaced with the UserNotifications's bell

**Comment by guymass** [comment]
What do you mean "Update correctly"? I just did a git pull.

**Comment by DanielnetoDotCom** [comment]
not sure, this menu should not be there.

did you clear the cache?

**Comment by DanielnetoDotCom** [comment]
or maybe this is a CSS that is not updated, if you have a CDN or a proxy cache, try to purge it.

looks like your still loading an old CSS file

**Comment by guymass** [comment]
Yes I cleared cache. This is the notifications plugin I have:
![Screen Shot 5783-01-12 at 16 25 24](https://user-images.githubusercontent.com/58882903/194564535-21246955-9e07-4548-a7df-4adae887b164.jpg)

**Comment by guymass** [comment]
ok, I will check that although I restarted that machine so the cache should be clean.

**Comment by DanielnetoDotCom** [comment]
NOT notification plugin, I mean UserNotifications

but it really looks like the CSS is not loading properly.

**Comment by guymass** [comment]
I deleted everything on the videos/cache, however if the CSS is not loading properly than why does it only effect the top menu?

**Comment by DanielnetoDotCom** [comment]
the CSS modification made for the menu.

as I told you, looks like you are loading only the old version 

I guess your network is making you not load the new version.

what is the URL for this site?

**Comment by guymass** [comment]
This is a VM machine running behind a ssh proxy, everything is working fine this just happened in my last update but before whenI installed it everything looked perfect.

**Comment by guymass** [comment]
URL is - https://tube.feisafe.com

**Comment by DanielnetoDotCom** [comment]
again, it is probably a proxy cache

**Comment by guymass** [comment]
ok I will check to see if this is a cache issue.

**Comment by guymass** [comment]
OK I see that my page is loading the css like this:
https://tube.feisafe.com/view/css/custom/cosmo.css?cache=1664442328_1665148881

I am not sure where this cache=166444... is coming from.

**Comment by DanielnetoDotCom** [comment]
not this, the menu CSS should be this https://tube.feisafe.com/plugin/UserNotifications/style.css

for some reason, you do not have it 

this is the tutorials CSS https://tutorials.avideo.com/plugin/UserNotifications/style.css

that means a wrong update

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/blob/master/plugin/UserNotifications/style.css

**Comment by guymass** [comment]
This is strange because my clone is the latest and this is a fresh installation. Even when I change the template to something else I still get that menu.
![Screen Shot 5783-01-12 at 17 30 46](https://user-images.githubusercontent.com/58882903/194578590-50486862-4db6-4417-a69d-55e110b625dd.jpg)

This is what I have in the UserNotification plugin:
![Screen Shot 5783-01-12 at 17 34 06](https://user-images.githubusercontent.com/58882903/194578897-abb1fb23-3b87-4026-b97b-7db3f03b0e12.jpg)

**Comment by DanielnetoDotCom** [comment]
the CSS file is on the GitHub version, and for some reason you do not have it on the plugin, I am not sure what have you done

try to run this `sudo git fetch --all && sudo git reset --hard origin/master`

**Comment by guymass** [comment]
OK great this fixed this issue, much thanks!
