### ISSUE TITLE
Sending mail to users is limited to 1000

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7222]
We are trying to extend the emails to all users but we see we can only send emails to 1000 users. How can we send emails to all of them? Also how to make sure it sends them not all at once?

**Comment by DanielnetoDotCom** [comment]
what exactly feature are you referring to?

can you please screenshot?

**Comment by guymass** [comment]
![Screen Shot 5783-01-12 at 17 35 48](https://user-images.githubusercontent.com/58882903/194579273-790b18b8-e351-4063-834f-04fce3cf19ce.jpg)

Something in the emails link doesn't open well, sometimes it doesn't do anything.

Here is where we write the email to send to the susers, but it will only send to 1000 users.

![Screen Shot 5783-01-12 at 17 35 57](https://user-images.githubusercontent.com/58882903/194579405-26e4b6bb-d3e3-444e-935f-42e87585b236.jpg)

**Comment by DanielnetoDotCom** [comment]
this update increase it to 10K users

**Comment by JoshWho** [comment]
working good

**Comment by guymass** [comment]
Excellant!!
