### ISSUE TITLE
Is there a way to move Left Nav Categories to the top of the Nav?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7223]
![30605ad4-9e7a-4a90-9354-7e2dc95d8fba](https://user-images.githubusercontent.com/39392449/194642327-14a23820-40da-4a0b-8732-bfde3c0fb34a.png)

It gets buried on my Navigation and i guess a lot of users never knew it was there.

![f55a6e71-d429-4ef5-9596-563248dc5362](https://user-images.githubusercontent.com/39392449/194642542-11498c39-33f1-41a3-8f47-cb08feb5bad9.png)

**Comment by JoshWho** [comment]
Under the Dash Buttons.

Not the complete top but just more towards it.

**Comment by DanielnetoDotCom** [comment]
if you mean to change the category menu position order on the left menu. sorry we do not have this option yet
