### ISSUE TITLE
240P is "wonky"

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7224]
**Describe the bug**
I've got videos that are between 240P and 360P, weird sizes like you find on interweb.

Throwing them in the encoder with [240P] checked is not transcoding them down to 240P. I've re-encoded a bunch, they're still throwing the " AVideoLog::DEBUG: Roku Empty video source" error - and when I go to look at the video I'm still seeing weird sizes like "316P". (WTF is 316? sounds like an old phone…)

Throwing some videos in the encoder that are super crap resolution, they loop encoding over and over - Daniel I believe you saw this…

**Comment by DanielnetoDotCom** [comment]
Please send me a video with this weird size so I can test encode here locally
