### ISSUE TITLE
[Workflow optimization] Image upload from /mvideos page

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7226]
**Is your feature request related to a problem? Please describe.**
I am going through and uploading >600 poster frames. This is taking an absurd amount of time.

**Describe the solution you'd like**
From the /mvideos page, without consuming much screen real estate, we can add a pencil icon (or something). This should bring up the file/open dialog and this does upload/save of the image in one step.
![Screen Shot 2022-10-08 at 12 41 47 AM](https://user-images.githubusercontent.com/11711050/194696386-5b7a0a3c-ca4e-4dc3-967f-624cac444dff.jpg)

**Comment by DanielnetoDotCom** [comment]
what about this?

![chrome-capture-2022-9-10 (1)](https://user-images.githubusercontent.com/18009293/194893871-1b09fba2-3bd8-4c33-af0e-4e4e4f55b924.gif)

and this?

![chrome-capture-2022-9-10 (2)](https://user-images.githubusercontent.com/18009293/194893893-7bbd7500-28a2-436c-b989-43e8c5df9e1d.gif)
