### ISSUE TITLE
Can't set the description to "" (empty).

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7229]
**Describe the bug**
Sometimes when you're importing videos, you paste something incorrect for a description.

Later, when you're looking at the video & you see the description is incorrect - maybe you just want to erase the description.

But you can't. You have to put some text in the description. It won't let you save an empty description.

This must be some attempt to rescue the user from accidentally wiping out the description? But sometimes, this is the desired behavior.

**Comment by DanielnetoDotCom** [comment]
On what page are you editing this?

I tried here and I could save an empty description.

**Comment by walt93** [comment]
/mvideos

https://user-images.githubusercontent.com/11711050/194964632-ae4cd5ec-205e-464b-8cc5-3991df27af86.mov

**Comment by DanielnetoDotCom** [comment]
the video you are trying to edit seems to be encoding or corrupted.

wait for the encode process to finish and try again
