### ISSUE TITLE
[Workflow optimization] Import posterframe from first frame of video

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7230]
**Is your feature request related to a problem? Please describe.**
I just imported nearly 1,000 videos. For almost half of those videos, the first frame of the video *is* the poster frame that we want to use. OBSERVATION: when you upload videos to popular social media platforms, they use the first frame of the video as a poster frame, so people put their poster frame as the first frame of the video - it's like its a standard or something. 💡

On AVideo, however, we grab a random frame of video hoping that's going to give a good result (observation: it rarely does).

So I had to script FFMPEG to pull the poster frames, and have to hand edit nearly 500 videos. I'm still not done. This is taking forever and it's painful…

*IF* there were a checkbox or preference - during encoding - "Use first frame of video as poster frame" it would have saved a lot of work.

**Comment by DanielnetoDotCom** [comment]
If you have the MP4ThumbsAndGif plugin, check this 

![chrome-capture-2022-9-10 (2)](https://user-images.githubusercontent.com/18009293/194894507-be96fcc7-63c5-4d62-bbc2-cf262403e191.gif)

**Comment by walt93** [comment]
What would cause it to fail to open? I've tried for a bunch of videos. Screen dims, spinner spins, screen un-dims.

**Comment by DanielnetoDotCom** [comment]
do you mean the plugin?

If that is the first time you will open this, it may take some time, because the encoder will need to process the video to extract the images.

check the streamer and encoder logs for some clue.
