### ISSUE TITLE
Some (1%?) Roku images are "broken", only rendering part of the image and the rest obscured by a grey rectangle

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7231]
**Describe the bug**
Out of 2,400 videos, we have a bunch that are doing this (haven't counted). Here are a couple sizes of JPG image. Observe that they are fine (all of them are fine, only putting two here to make some kind of example):

https://conspyre.tv/videos/video_220913222504_v59d8/video_220913222504_v59d8_512.jpg?cache=16632006781663200678&download=1&title=call-to-pilots.mp4
![image](https://user-images.githubusercontent.com/11711050/194739926-1c8a51e3-9c63-424c-a1ee-2bb9acc532ff.jpeg)

https://conspyre.tv/videos/video_220913222504_v59d8/video_220913222504_v59d8_128.jpg?cache=16632006781663200678&download=1&title=call-to-pilots.mp4
![image](https://user-images.githubusercontent.com/11711050/194739931-cb90e485-0e2e-46d1-ad68-e66af134d374.jpeg)

But the Roku image?

https://conspyre.tv/videos/video_220913222504_v59d8/video_220913222504_v59d8_roku.jpg?cache=16632930611663293061&download=1&title=call-to-pilots.mp4
![image](https://user-images.githubusercontent.com/11711050/194739939-dd9f7d8a-fa49-455a-b6a8-ba44e3acc160.jpeg)

**Comment by JoshWho** [comment]
Cache handler bug seems like

**Comment by walt93** [comment]
I can blow out thousands of images & re-create all of them.

I will get a bunch more grey images if I do this.

How can I blow out an individual video's images?

**Comment by DanielnetoDotCom** [comment]
to delete a single video you have to do it manually.

but I build a tool that scans all the images and tries to detect corrupted ones.

https://github.com/WWBN/AVideo/blob/master/install/deleteThumbsFiles.php

run this ...

```
cd /var/www/html/AVideo/install
php deleteThumbsFiles.php 1
```

the 1 at the end of deleteThumbsFiles.php is very important, that is what will tell the script to delete only corrupted images.

**Comment by walt93** [comment]
Daniel running this script deletes one image. Then running it again it doesn't do anything. But there are still many gray images.

**Comment by DanielnetoDotCom** [comment]
it may not detect all the images. this is a try to detect corrupted ones. 

the last chance is to delete the corrupted images manually.

**Comment by walt93** [comment]
Daniel what is the process for finding them (the poster image for a video) manually? I'll try to get that sorted out. My marketing guy is going to be pissed if his videos have trashed poster frames for launch.

I think I need to find a better solution. What I am doing is clearing the cache, then, running a script which rebuilds the roku json by hitting about 60 roku JSON URLs in a row. Is this what is putting memory pressure on my server and causing images to break?

If I start going through manually I can find dozens of these - and I have 2,400 to check.

I need to be able to automatically rebuild them & know it isn't going to randomly whack 5% of the images (exact % unknown).

Thoughts?

**Comment by DanielnetoDotCom** [comment]
For example this image

`https://conspyre.tv/videos/video_220913222504_v59d8/video_220913222504_v59d8_roku.jpg`

it will be located inside your videos directory, probably

`/var/www/html/AVideo/videos/video_220913222504_v59d8/video_220913222504_v59d8_roku.jpg`
