### ISSUE TITLE
Cannot Stream from Mobile

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7232]
I have a fresh installation and trying to use both AVideo apps on GStore however I cannot stream from either of them.

I am getting the following error in the log and I hope maybe you will be able to find something in it. I am sorry for it being a bit long but I will upload a text file for you to view. I would really like to be able to use the mobile app and I think we need to have a good AVideo app.

[login_error.log](https://github.com/WWBN/AVideo/files/9742624/login_error.log)

Also while getting error messages on the mobile app live stream those messages appear so fast it is very hard to read and see what was the error. I suggest maybe fixing at least the error reporting to be more viewable so it will be easy for us to give you better feedback.

**Comment by guymass** [comment]
I am currently only logged in through my mobile but still I get this message in the avideo.log when trying to start a live stream from the mobile app:
![Screen Shot 5783-01-15 at 12 32 53](https://user-images.githubusercontent.com/58882903/194837109-0e18d4ac-b7de-4cd6-b640-6ea0632c30df.jpg)

I think AVideo should be able to handle multiple sessions and user logins form different devices so idk what this error means.

**Comment by DanielnetoDotCom** [comment]
the logs on the image have nothing to do with the on_publish logs

if there are no on_publish logs or the error is on your Nginx installation or your mobile never reaches the Nginx to request a connection.

**Comment by guymass** [comment]
Does the mobile app try to connect on different ports? if I can stream from OBS why wouldn't connect from my mobile?

**Comment by guymass** [comment]
Sorry this issue still open I closed accidentally.

**Comment by guymass** [comment]
OK I figured on that the Chat 2 plugin will cause an issue on the mobile app so after disabling it I was able to connect with the app. The app still needs some work imho, the connection is slow even through a good wifi internet connection.
