### ISSUE TITLE
Will not save my encoder URL when NetworkEncoder is selected

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7233]
I want to connect a site to the NetworkEncoder. current when I select the option to use my network encoder site it will automatically set the encoder url in the Site Settings to a wrong URL and any try to change and save a different url doesn't work. Only when I deselect the use NetworkEncoder option will it allow me to set the url.  I need to be able to set the encoder url and save it with the correct URL so this site will also be able to open the network encoders list.

Here are the screen shots of the config areas:
This has wrong URL, should be https://tube.feisafe.com.Encoder

![Screen Shot 5783-01-15 at 1 43 08](https://user-images.githubusercontent.com/58882903/194783060-b0f35309-ce94-45be-bce2-6890a3488c72.jpg)

and I cannot change it while this option in on:

![Screen Shot 5783-01-15 at 1 42 56](https://user-images.githubusercontent.com/58882903/194783134-31ce6d1f-25d0-4512-8d9f-c56b5e2220fc.jpg)

Why is it setting its own url and where is it taking this url from idk but its the wrong one.

**Comment by DanielnetoDotCom** [comment]
First, do you have the network installation?

https://github.com/WWBN/AVideo-Encoder-Network

then add the encoders with the command line

```
cd /var/www/html/AVideo-Encoder-Network/install
php encoders.php

```
https://github.com/WWBN/AVideo-Encoder-Network/blob/master/install/encoders.php

https://github.com/WWBN/AVideo/issues/4609#issuecomment-785859499

**Comment by guymass** [comment]
I have done that and I have the network encoder working. This is not the issue. The problem is the in the Site Settings the encoder url should point to the local site e.g. domain/Encoder and not the domain the network encoder runs on. This URL is done in the Settings tab where it asks for the network encoder URL.

My problem is I cannot edit that field at all in the Site Settings when that option is enabled in the Settings page.

**Comment by guymass** [comment]
OK its fixed, I had in Customize Advanced - > doNotShowEncoderNetwork checked so it was opening the wrong URL. Not I have the correct menu item and I can access the Network Encoders page.
