### ISSUE TITLE
Latest uploaded video is shown on start page, even if it is unlisted

### ISSUE THREAD

**Issue by smaku14** [WWBN/AVideo#7241]
Hello all,

First the following scenario. My youPHPtube page is public and contains only unlisted videos. So, should someone stray to the page, no videos will be shown to them. (Which is fine.) The videos should only be visible if they are embedded on other web pages.

Now for my problem: Although all videos on the page are unlisted, the most recently uploaded video is always displayed on the start page. Is there any way to prevent this?

As a work-around, I uploaded a meaningless placeholder video with the status Active, hoping that this video will be displayed when you get to the page. But as soon as I upload a new unlisted video, it displaces the previous video and shows up on the start page (even though unlisted).

**Comment by DanielnetoDotCom** [comment]
unlisted should not be there

are you sure you are on the latest?

can you reproduce it on demo site?

**Comment by smaku14** [comment]
Hi Daniel,

yes I'm sure.
![videolist_sorted_by_newest_first](https://user-images.githubusercontent.com/115157749/195116766-362852a8-6763-40be-a6db-1d7b219d213e.png)
![unlisted_video_displayed_on_start_page](https://user-images.githubusercontent.com/115157749/195116772-6776db67-bc28-4991-93b2-f163ae475f43.png)

When I visit the start page (also in incognito mode), always the latest uploaded video is shown. No matter if active or unlisted.

Unfortunately, I am not a dev guy, so I can not reproduce it by myself.

**Comment by smaku14** [comment]
Hi Daniel,

The thing is that I don't access the video directly in the second screenshot. What you see there is what appears when someone enters my page (https://video.xxxxx.com). It is NOT a direct link to the video with a video ID (e.g. https://video.xxxxx.com/v/123).

When I deactivate the video, it shows the next newest unlisted video at https://video.xxxxx.com.

**Comment by DanielnetoDotCom** [comment]
Enable the gallery plugin or the NetFlix mode

**Comment by smaku14** [comment]
That solved the problem. Thanks!
