### ISSUE TITLE
French language syntax

### ISSUE THREAD

**Issue by lachainestoplinky** [WWBN/AVideo#7244]
Hello, in French, we write:
" Depuis 3 minutes "
Depuis = "ago"
On avideo it is written
3 minutes ago ( Depuis )
it should be possible to display "Depuis" just before the 3

**Comment by Maikuolan** [comment]
I created a pull request for this issue just now (#7247). :-)

**Comment by Maikuolan** [comment]
PR has been merged. If you update, the problem should be fixed. :-)

**Comment by lachainestoplinky** [comment]
Hello,
in French we write "Since" 3 hours and not 3 hours Since
Since = ago
the lines of code are corrected in the "locale/fr.php" and "objects/fonctions.php" files
but as you can see, Since, still displays after the date.

I forgot a file? in my update?
![Capture d’écran 2022-11-06 à 13 05 07](https://user-images.githubusercontent.com/39954233/200170140-06a87dfb-fcfa-40a1-a757-5f7654f18bfc.png)

**Comment by DanielnetoDotCom** [comment]
Hi, I am not sure what is the correct translation for your idiom. but all the translation files are on the locale folder

https://github.com/WWBN/AVideo/tree/master/locale

**Comment by lachainestoplinky** [comment]
Hello,Thanks, I'll manage.it's code and in the function.php file, it's good.I will get there one day!I installed the latest patches Cordially Message ID: ***@***.***>

**Comment by lachainestoplinky** [comment]
Hello, what is the file or files that manage the display of what I have framed in the image.in French, instead of “Since” ( Depuis ) you can say “there is” ( Il y a )n the locale directory, what is %s next to ago in the language files ?have a good day Message ID: ***@***.***>

**Comment by lachainestoplinky** [comment]
Hello, I have the impression that there is a bug because it is not possible to display ago 3 day sinstead of 3 days ago Same with: %s ago = ago %s Sincerely—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by DanielnetoDotCom** [comment]
I am not sure what should be the translation, google said that

![image](https://user-images.githubusercontent.com/18009293/200837070-dab16e09-24e2-4414-a947-4bb0621d7802.png)

if you want to follow google you should use 

```
$t['%s Ago'] = 'Il ya %s';
...
$t['Days'] = Jours';
```

**Comment by lachainestoplinky** [comment]
Hello,framed in red, which I wish.There is , after the clock logo CordiallyMessage ID: ***@***.***>

**Comment by lachainestoplinky** [comment]
Hello,
framed in red, which
I wish.There is , after the clock logo
Cordially
![site](https://user-images.githubusercontent.com/39954233/200911851-6ed9793f-ce57-42fb-98cf-d874b58182f2.png)

**Comment by DanielnetoDotCom** [comment]
So google is not correct?

**Comment by lachainestoplinky** [comment]
Yes GOOGLE is correct
it is AVIDEO which is not because it replaces "ago" with the correct translation
but not as it should.
the correct position is the one framed in red.

if ago = ago
in French, we write: ago 6 hours
but not 6 hours ago
nothing serious but a syntax error
![site](https://user-images.githubusercontent.com/39954233/200959901-1f63d8f4-4317-4e7d-918f-d42a305ec8c4.png)

**Comment by DanielnetoDotCom** [comment]
Please detail how is written now (in french) and how it supposed to be written in french

**Comment by lachainestoplinky** [comment]
Hello
On image 1, you have the French translation on
AVIDEO , framed in red .... Depuis

![001](https://user-images.githubusercontent.com/39954233/201204077-3344fbb8-a89d-4a30-ac23-90bd5460c61f.jpeg)

In image 2 , what AVIDEO should display
Depuis ....

![002](https://user-images.githubusercontent.com/39954233/201204268-bc3625bb-b556-41df-a328-620865b88f42.png)

**Comment by DanielnetoDotCom** [comment]
Please check this update 

![image](https://user-images.githubusercontent.com/18009293/201363091-31a9ea8e-8dd2-48a6-98e9-b86f66a60c03.png)

**Comment by lachainestoplinky** [comment]
Hello,
I download the update from this page, right?
and I replace the directories and files

![Capture d’écran 2022-11-11 à 17 33 08](https://user-images.githubusercontent.com/39954233/201387488-92e213ed-212c-46eb-a685-24b830783b48.png)
