### ISSUE TITLE
Replies to comments 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#7246]
I noticed replies to comments don't show up in the comments tab on the admin panel.

Can it be made more clear that a comment has replies? Maybe bold text to click on?

**Comment by DanielnetoDotCom** [comment]
do you mean on the comments tab or on the video itself?

**Comment by fakeologist** [comment]
No on the left sidebar of admin panel

**Comment by DanielnetoDotCom** [comment]
can you please screenshot?

**Comment by fakeologist** [comment]
No on the left sidebar of admin panel

**Comment by fakeologist** [comment]
I can't get screenshot upload to work here

**Comment by fakeologist** [comment]
[cid:eu.faircode.email.12036]
* - * - *
All past streams found at
https://fakeotube.com

Join/follow fakeologist sites:
https://fakeologist.com
https://fake11.com/discord
https://fakeologist.com/forums2
https://fake11.com/telegram
https://fake11.com/tiktok
https://fake11.com/youtube1
https://fake11.com/youtube2
https://fake11.com/twitter1
https://fake11.com/twitter2

Oct. 12, 2022 9:06:43 a.m. Daniel Neto ***@***.***>:

**Comment by DanielnetoDotCom** [comment]
I just sent some updates, I know it is still not perfect, but I guess it is better now
