### ISSUE TITLE
Download file name

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#7248]
Downloading files from the cdn network gives a long filename without the title of the video.
I need an option to download the file with the video title as the file name.

**Comment by DanielnetoDotCom** [comment]
As long as we download it directly from the CDN I do not think it is possible, but I will think about if I can change the header and inject some file name

**Comment by fakeologist** [comment]
Any update?

**Comment by DanielnetoDotCom** [comment]
I am sorry, I am still not able to find a solution.
