### ISSUE TITLE
%s now showing in description of video

### ISSUE THREAD

**Issue by markginter31** [WWBN/AVideo#7250]
Latest git pull - just refreshed the browser - seeing this:
![Screenshot 2022-10-12 11 45 48 AM](https://user-images.githubusercontent.com/7345618/195389865-8ae94d1c-6d58-49d2-bc7d-15c3ee7b6a29.png)

I'm not sure how to make the %s go away.  It shouldn't be there.  Health check shows that all php modules are installed.  All plugins have updated tables.  I didn't notice anything in the log file that would indicate a problem.

**Comment by DanielnetoDotCom** [comment]
It should be fixed on the last update

**Comment by markginter31** [comment]
Just git pulled and you're right! Thanks!!
