### ISSUE TITLE
Intermittent Roku images not working

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7252]
**Describe the bug**
I have a number of videos that regularly do not produce an image for Roku. 

Then, curiously, when you're looking for the broken images by chasing down the image URL through the Roku JSON, they start working. 

But this time when I am looking I can clearly see those images are returning 404.

            "id": "video_2683",
            "title": "The MENA Coverup (govt, drugs, corruption, murder) Fixed video",
            "thumbnail": "https://conspyre.tv/videos/TheMENAConnectiongovtdrugscorruptionmurder_60739eed78abb1.43526106/TheMENAConnectiongovtdrugscorruptionmurder_60739eed78abb1.43526106_roku.jpg?cache=1665563402_1665563402",

            "id": "video_5577",
            "title": "The Great Awakening",
            "thumbnail": "https://conspyre.tv/videos/video_210521231320_b4ec/video_210521231320_b4ec_roku.jpg?cache=1665562803_1665562803",

            "id": "video_4921",
            "title": "Altiyan Childs Reveals the Worlds Secret Religion: Freemasonry",
            "thumbnail": "https://conspyre.tv/videos/XFACTORWINNERREVEALSWORLDSSECRETRELIGIONfreeMASONRY_608f7b8ab87403.06575801/XFACTORWINNERREVEALSWORLDSSECRETRELIGIONfreeMASONRY_608f7b8ab87403.06575801_roku.jpg?cache=1665563402_1665563402",

            "id": "video_11454",
            "title": "FBI LOST Biden Child Porn Evidence",
            "thumbnail": "https://conspyre.tv/videos/video_220914191453_va167/video_220914191453_va167_roku.jpg?cache=1663293055_1663293055",

---> all four of these thumbnail URLs return https://conspyre.tv/view/img/image404.php?notFound=1

When this occurs, also on /mvideos you can see that the [Roku_jpg] download is not there.

These particular videos seem to fail to produce a Roku JPG roughly 50% of the time. @Daniel this is the issue we went to find last Friday. Specifically these videos (and others) are in some weird way - they are sometimes failing that Roku JPG creation,..

**Comment by DanielnetoDotCom** [comment]
first, try to fix the SSL

<img width="974" alt="image" src="https://user-images.githubusercontent.com/18009293/195600368-d2e9c3df-c575-4647-9494-4b2311e29123.png">

**Comment by walt93** [comment]
Yeah, Cloudflare being more problems than solutions - they broke certbot last night. Fixed.

**Comment by DanielnetoDotCom** [comment]
I totally do not recommend Cloudflare proxy

**Comment by walt93** [comment]
I have Cloudflare 99% disabled & am just using it to serve files from Wasabi.

**Comment by walt93** [comment]
Closing and re-opening to keep fresh.
