### ISSUE TITLE
Registration and login form

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7253]
Hi @DanielnetoDotCom ,

Thinking about usability. I think the login/registration could be simplified. Email and username are required. I verify that the pattern of other projects in the market is to request only the email, serving as the user identifier.
Is there a way to customize these registration/login form fields?

![image](https://user-images.githubusercontent.com/37880073/195488223-cd234375-cb6b-465c-b2cd-aebefaf032b9.png)

**Comment by gbrn** [comment]
![image](https://user-images.githubusercontent.com/37880073/195492166-b1863a11-a052-4e55-8270-688d909ea598.png)

**Comment by DanielnetoDotCom** [comment]
The only thing I can see could be simplified is the name

<img width="777" alt="image" src="https://user-images.githubusercontent.com/18009293/195600863-d13624a9-accb-4fcc-8030-6d88af28f3f2.png">

**Comment by gbrn** [comment]
Dani, ok. Replacing the username, by just the email, is already a very good thing.

But I tested it and it didn't work. When I login with email, the login is invalid, but if I login with the username it works. 

Check out the video:

[CNETV.webm](https://user-images.githubusercontent.com/37880073/195729406-1b019d28-9c19-4bd8-8c5b-94dd85f9b92e.webm)

**Comment by DanielnetoDotCom** [comment]
You Must check this


![image](https://user-images.githubusercontent.com/18009293/195856115-445dcc96-7b31-400d-b650-b5d58ad6eaee.png)


but it should be done from the beginning. I am not sure what will happen with the already registered users.

**Comment by gbrn** [comment]
@DanielnetoDotCom  Returning to the subject of this question:
Analyzing database data. It turns out that there is the column USER and another EMAIL.
So if the user makes the first registration, using 2 different fields USER + EMAIL, the information is different in two fields.
When the EMAIL field is used as USER, there will be 2 EMAILS filled in. The system does not fix this earlier.
So it remains to do the correction manually in the database.

![image](https://user-images.githubusercontent.com/37880073/204113004-c67857eb-6c50-47ec-b127-7fad7a0dd098.png)
