### ISSUE TITLE
A new payment company

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7256]
We have been looking for a company that can solve our problem with being able to charge money. As PayPal now gone wild and is threatening to fine its users with 2500 pounds if they think they go against the PayPal political world view, we have found this company who is also providing service in our country and from what we see they have very low exchange rates.

This is the link to the company and I wanted to ask if this can maybe taken into consideration to implement in the script as currently the only option we have is Strip, so maybe this can also be a good option to use.

https://wise.com/

**Comment by DanielnetoDotCom** [comment]
Hi

I can add it in 3 weeks if you agree to sponsor.

if you are interested email me at developer@youphptube.com

**Comment by guymass** [comment]
I will pass it on to my team and will get back to you.
