### ISSUE TITLE
Is there a way to display the [CHANNEL NAME] for the video on the videos list?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7259]
**Describe the question**
![Screen Shot 2022-10-13 at 5 20 00 PM](https://user-images.githubusercontent.com/11711050/195734765-e27b51f5-2f3e-4e8f-a755-ce27f1b89d6e.png)

**Comment by DanielnetoDotCom** [comment]
Check all this options 

![image](https://user-images.githubusercontent.com/18009293/195870055-f17a0b08-bc3c-484c-8ec3-b155294cb2b7.png)
