### ISSUE TITLE
[IDEA] Show the user what resolutions the encoder is going to encode to.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7260]
**Is your feature request related to a problem? Please describe.**
I've been doing some different encoder settings.

It occurs to me that it would be useful for the user to know things like:
 • This encoder is configured for FHD]
 • This encoder is configured for HD]
 • ⚠️This encoder is configured to vomit out horrid SD 🤮

**Comment by DanielnetoDotCom** [comment]
Do you mean show it on the main encoder page, so you can decide what encoder to use on a encoder network?

**Comment by DanielnetoDotCom** [comment]
Check this 

![image](https://user-images.githubusercontent.com/18009293/195874034-9c8ac820-7093-48cc-8064-caef7dbd1425.png)

**Comment by walt93** [comment]
Thanks Daniel, yes that is the use case, and this is a great solution - that's awesome. Now I can configure my encoders as one for FHD, two for HD and one for SD - and I can make it make sense for the users. 😎
