### ISSUE TITLE
Restream only for Admins?

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#7267]
Have restream enabled but seems only Admin can restream. Normal users who can live stream do not get restream tab on live, whereas Admin has tab. Is this normal behavior?  Thanks...

**Comment by DanielnetoDotCom** [comment]
check your logs for something like `Live::canRestream:... `and you will find what is going on

**Comment by GreenDragonTavern** [comment]
[15-Oct-2022 12:53:37 America/Los_Angeles] AVideoLog::DEBUG: Live::canRestream: permission is false SCRIPT_NAME: /av/plugin/Live/index.php
[15-Oct-2022 12:53:37 America/Los_Angeles] AVideoLog::DEBUG: Live::canRestream: permission is false SCRIPT_NAME: /av/plugin/Live/index.php

![RestreamSettings](https://user-images.githubusercontent.com/85363361/196005428-acc32203-4bc4-42a4-9a4e-7c02d4aac0fb.jpg)

**Comment by DanielnetoDotCom** [comment]
try this update and make sure `All Users` Selected 

![image](https://user-images.githubusercontent.com/18009293/196005984-3c552e94-cb8e-46b3-ab5b-7b399a9e2069.png)

**Comment by GreenDragonTavern** [comment]
All Users is already selected.

**Comment by DanielnetoDotCom** [comment]
Did you make another git pull?

**Comment by GreenDragonTavern** [comment]
Just did, and that did it...thank you for prompt fix!
