### ISSUE TITLE
“Group Watch” for AVIDEO

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7269]
Dani, I've been testing a synchronized screen-sharing feature called Disney+ Group Watch.
  I found very interesting.  I've been trying to see something like this for a while.
  The service is like a fake live.

  Do you know this feature?  Have you thought of something along these lines for AVIDEO?

https://disneyplusbrasil.com.br/faq/groupwatch-o-que-e-e-como-funciona/

**Comment by gbrn** [comment]
@DanielnetoDotCom can you tell me something about this issue?

**Comment by DanielnetoDotCom** [comment]
Sorry but this is NOT an issue and for now, I have no plans to build something in that direction.
