### ISSUE TITLE
Making categories "private" does not make them "private"; all users see all categories, private or not.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7270]
**Describe the bug**
I have >650 categories. I would like to make all but about 100 of them private so my users don't have to scroll through hundreds of categories that they don't need to use.

_I would like to use the feature of categories where they are owned by a user, and are set to private so that a user under my "Podcasters" section will only see their category_

But this is not working. All users can see all categories, for example, in the encoder when they are selecting a category.

![Screen Shot 2022-10-16 at 12 31 21 AM](https://user-images.githubusercontent.com/11711050/196023793-506c40c2-7520-472a-bf05-75d2498b6732.png)

_Here I am logged in as the podcaster TRUreporting. I should only see the one Podcaster "TRUreporting" under categories, as that category has a users_id set to  this user's id. I should not see any of the other podcasters, nor should I see most of what is in that menu. Most of those are set to "private"._

**Comment by DanielnetoDotCom** [comment]
Making a category private will not make your videos private or hide them, this option is to prevent other users to be able to include their videos in this category.

**Comment by walt93** [comment]
Correct Daniel.

What I am saying is that this does not work.

A user, from the encoder - sees all 650+ categories, despite more than 400 of them being set to private. That's what I mean by "all". 

Access controls are not working.

**Comment by DanielnetoDotCom** [comment]
Is this user admin?

or maybe the "private categories" are from the same user logged on the encoder?

I just double-checked in the code and if this user is not admin, it should not see the private category from somebody else.

**Comment by walt93** [comment]
I've set up a bunch of users. When I log in as any of them, I can see all of the categories. See the screen shot above. That user is logged in - not an admin - can see every category. 

From **here**, which is the videos edit page, yes you are correct - you are respecting the private flag. On the encoder page? The private flag is ignored. Unfortunately this is the user's first point of contact with the categories popup - and for my site its very sub-optimal to see all 650 categories (again, see screenshot above - shows the problem - screenshot below - shows correct behavior - look at the # of entries under "podcasts" in both screenshots & you will see)

![Screen Shot 2022-10-16 at 2 59 35 PM](https://user-images.githubusercontent.com/11711050/196060266-ca0773a3-1265-42b3-ab25-115d411563f4.png)

**Comment by DanielnetoDotCom** [comment]
I just tested it on the demo site and it is working fine

<img width="495" alt="image" src="https://user-images.githubusercontent.com/18009293/196273576-202f655f-3d52-48ce-b9f7-b57efabff48c.png">

![image](https://user-images.githubusercontent.com/18009293/196273688-14bfc615-8afc-4b8e-aeab-634407ec7954.png)

![image](https://user-images.githubusercontent.com/18009293/196273845-2ab099a1-1fac-4903-ac21-3dbe7966f4cd.png)

I suspect you have something outdated.

or try to reproduce it on demo site

**Comment by DanielnetoDotCom** [comment]
please reproduce it on demo site

**Comment by walt93** [comment]
I might have to check out an old version of the encoder code to do that, Daniel - don't have access to do that.

**Comment by DanielnetoDotCom** [comment]
the encoder for the demo site is the latest (streamer and encoder)

https://demo.avideo.com/

https://encoder1.wwbn.net/

**Comment by walt93** [comment]
Daniel - our messages here are out of sync. 

I did a git pull on all of my encoders & the encoder network app. 

Problem is fixed.

**Comment by DanielnetoDotCom** [comment]
sorry you are right
