### ISSUE TITLE
Category count in left menu disagrees with category count on video page

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7271]
**Describe the bug**
The left nav menu shows the correct count of number of videos in a category.
The main screen shows the count of number of videos in a category INCLUDING DELETED VIDEOS.

**To Reproduce**
I encoded 17 videos, then cancelled 7 of them, so there are 10 videos in the category.

Observe in the left menu under Podcasts / L there are 10 videos.
Observe in the right under the "L" category it shows the incorrect value 17.
Observe that in L's section it shows 10 actual videos.
(if I did something like `select * from videos where users_id=123` and 123 was L's users_id - it would show 17 records………)

![Screen Shot 2022-10-16 at 12 43 52 AM](https://user-images.githubusercontent.com/11711050/196024203-74ff2c7c-000b-4749-8859-d710163629c8.png)

![Screen Shot 2022-10-16 at 12 45 06 AM](https://user-images.githubusercontent.com/11711050/196024261-76f47b06-795e-4479-9e78-07a7c5e473ee.png)

**Comment by DanielnetoDotCom** [comment]
what happens if you clear the cache?

also as long as you are not showing the category count on the main category list, the subcategories should not have a counter as well. 

I will need to send a fix for that later.

**Comment by walt93** [comment]
Clearing the cache doesn't change this. It looks like it's counting deleted videos, at least that's what the arithmetic suggests.
