### ISSUE TITLE
How can a user stop getting mails from a channel

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7273]
I have users who are subscribed to channels however they wish to not receive any emails, how do I prevent that?

**Comment by walt93** [comment]
Unsubscribe works.

**Comment by guymass** [comment]
They still want to be subscribed, so is there another way or just that?

**Comment by DanielnetoDotCom** [comment]
There is a bell button on the subscription button to stop notifications but still subscribed

**Comment by guymass** [comment]
OK much thanks!
