### ISSUE TITLE
direct upload model shows duplicate buttons

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#7283]
**Describe the bug**
When you click direct upload on the demo site, you see 2 sets of save, cancel buttons.

**To Reproduce**
1. click my videos
2. click direct upload

is this by design?

**Screenshots**
![image](https://user-images.githubusercontent.com/28105720/196175456-a7c1a33d-3600-4344-9f83-c63fda75751a.png)

**Comment by DanielnetoDotCom** [comment]
Yes

both buttons does the same thing, it is like that because some times you need to scroll the window and one of the buttons can disappear

**Comment by millzee01** [comment]
coolio, thanks.  just so i know thats all.
