### ISSUE TITLE
Views counter miss behaving

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7289]
We got this message from one of our members:

Hi Eitan, hope you're doing well. Question about the view counters... all of a sudden (starting early in October) view counts on Anthony's videos (and Lost Arts Radio too, I think) really shot up 7 to 10 times what they were before. When I go into the metrics on them it appears to be just multiple "views" from the same computer. For instance, I'm in Nashville and it may show "Nashville, Tennessee" as 50 different views. Any idea what's going on?

This is not just him but we have noticed this on other channels as well. Is this a bug? currently we have no way to tell but it seems strange that suddenly numbers been jumping up, so maybe there is a problem with the way views are being counted.

**Comment by DanielnetoDotCom** [comment]
I need a way to reproduce it.

**Comment by guymass** [comment]
We see a huge increase in the following two channels, and a specific video is reaching over 80K. This is weired and I don't know what is going on? The second smaller channel also have a major increase however they didn't see anyone paying their subscription to those private and hidden videos, so we don't know how is it possible for those to go up. So either there is a bug in the video's counter or we have maybe an sql injection? maybe someone is testing some security hole in the script? IDK, but those numbers are not real or pumped up in some other way I fail to understand at the moment.

Here are SS statistics of those two videos:

This is the big one:
![Screen Shot 5783-01-26 at 18 03 37](https://user-images.githubusercontent.com/58882903/197232027-bca28abe-7652-4624-95a3-e5b0700f319f.jpg)

This is the smaller one:
![Screen Shot 5783-01-26 at 18 03 54](https://user-images.githubusercontent.com/58882903/197231912-3cffbaa2-7015-448e-8e2b-5dc7f5d876b0.jpg)

**Comment by guymass** [comment]
This video has already got over 100K since my last post, something strange is happening with it.
https://alive528.com/v/3687

Its a 2hour video, so maybe someone is trying to create multiple requests to cause an overload of the server?
Although it doesn't appear to be that busy. IDK.

![Screen Shot 5783-01-27 at 11 25 45](https://user-images.githubusercontent.com/58882903/197329076-33b24128-c7d6-4ca6-b6c0-d3928e6a76b8.jpg)

**Comment by guymass** [comment]
Could this be causing some effect on something related to the counter?

[Sat Oct 22 18:24:07.146831 2022] [core:error] [pid 1855835] [client 147.161.8.166:29336] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: https://alive528.com/sw.js?0.45306597954423067

**Comment by guymass** [comment]
Thank you Matheous for creating this amazing script to check the requests load on the apache server and give us more info into what is going on. So here are some screen shots from the script running on my server and here is the URL to the script itself for anyone who need it and again much thanks to Matheous who is helping us to investigate this issue.
https://gist.github.com/matheusfillipe/8b5e278fa98cdebb2e11eaaa7bc6a337

![Screen Shot 5783-01-28 at 13 56 10](https://user-images.githubusercontent.com/58882903/197388501-55537d71-78fa-47ab-b937-d47210fb6f3c.jpg)

These are repeating IP address and the number on the right keeps increasing as the script is running indicating they are very active. I think one of them is a local server address however the rest are not. Currently this only gives me some indication into what IPs are accessing my site and what is they usage based on the information gathered in the apache log files.

**Comment by walt93** [comment]
This is probably completely unrelated, but a few months ago someone uploaded an Eric Dubay / Flat Earth video to my site & within two hours site traffic spiked w/a swarm of 30 bots watching the video at 2x speed, in a loop, for several days.  _My theory is we have state level actors propping up FE material - but why?_

**Comment by guymass** [comment]
IDK, but how would such bots work? how can we block such bots from creating such traffic?

I my case we have this health and healing video who we found out is copyrighted and being charged 5$ per view, by the time I noticed it that video is going over 100K and I am worried that maybe someone uploaded this video to create large traffic so later they can sue us in court for violating their copyrights. 

This can totally not only destroy all our work but also destroy our personal life. We need a solution urgeant, please.

**Comment by DanielnetoDotCom** [comment]
@guymass are you using iframes? I mean are you embedding your videos into some iframe?

**Comment by guymass** [comment]
No, we checked, it was an uploaded video. However once I put that video in hidden mode and since last few git pulls it has seemed to reduce, so im going to keep it open for few more days to see how it goes and maybe it was just a spike related to that video.

**Comment by guymass** [comment]
OK for now it seemed to have settled, still not sure what was causing it but like walt93 said it could be  some bots causing this. So for now i am closing this issue and hope it will not arise again. In any case maybe it would be a good idea to think of a way to block bots or allow only certain bots to scan the site.
