### ISSUE TITLE
Menu navigation issue

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#7291]
**Describe the question**
Is there a reason why the video page becomes the main page for the menu navigation, and if so is there a way to stop this because since the update when we click a video and play it, we have to use the browser back button to go back to the my videos page?

I'm not sure this is by design because it causes additional clicks to get back to your original place.

To reproduce the issue:

1. Navigate to https://demo.avideo.com/mvideos
notice the 3 bars on the top left hand menu
![image](https://user-images.githubusercontent.com/28105720/196351106-a602883f-5f19-49d9-8786-6112084793c1.png)

2. click menu and select dashboard 
notice the menu now has a back arrow to the previous page
![image](https://user-images.githubusercontent.com/28105720/196351255-2ad1ab5d-0e39-44a8-be61-c664b68ce7d0.png)

3. Click the menu arrow button to go back to the videos page
Notice the 3 bars appear on the menu (this is working as it should)
![image](https://user-images.githubusercontent.com/28105720/196355882-997df475-fae9-4d45-8c7f-ef890bf7cd3a.png)

4. Now click a video to play it
Notice how the top menu now changes to the 3 bars and becomes the main page.
![image](https://user-images.githubusercontent.com/28105720/196351483-53e29621-7506-4d3d-9818-dc3f4a2e6aef.png)

5 Ok, we want to go back to our videos page, so now you have to click the menu and select "my videos".
notice now that the videos page top menu is now an arrow
![image](https://user-images.githubusercontent.com/28105720/196351579-f548fcda-60d6-4600-b09d-752c5ca4c227.png)

6. Click the arrow 
Notice the video page we just played is now our main page and has the 3 bars on the menu.

To get around this, we now need to click the video to play then use the browser back button.

**Comment by DanielnetoDotCom** [comment]
Sorry but this is not a bug, this is exactly how it should work

**Comment by millzee01** [comment]
So playing a video makes it the main page and resets previous page? wow
