### ISSUE TITLE
Ad server for 

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7295]
**Describe the question**
I have an ad server that can serve banner ads. I'd like to use it in AVideo. I _think_ I can do that with the AD_Overlay Plugin??

Instructions for AD_Overlay Plugin say:

![Screen Shot 2022-10-18 at 9 56 43 PM](https://user-images.githubusercontent.com/11711050/196601121-d1bc2ae8-ad29-4de3-a268-7c7f6ccc344f.png)

I've been looking & cannot find where that is. Doesn't seem to be in ADs or CustomizeAdvanced or Customize User plugins...

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/196679410-7ff6c8cd-2d7a-464e-8327-b2e332ae349a.png)

**Comment by walt93** [comment]
Thanks!
