### ISSUE TITLE
Cloudflare gone. Some videos still fail to produce images for Roku. 

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7298]
**Describe the bug**
Previously, Cloudflare was not the cause of this problem. To prove this, I have closed the Cloudflare account - it's gone.

Roku images are still failing.

**To Reproduce**
1. Go to https://conspyre.tv/videos/TheMENAConnectiongovtdrugscorruptionmurder_60739eed78abb1.43526106/TheMENAConnectiongovtdrugscorruptionmurder_60739eed78abb1.43526106_roku.jpg
2. See no image
3. Go to https://conspyre.tv/videos/TheMENAConnectiongovtdrugscorruptionmurder_60739eed78abb1.43526106/TheMENAConnectiongovtdrugscorruptionmurder_60739eed78abb1.43526106.jpg
4. See image

Few more examples:
```
            "id": "video_2683",
            "title": "The MENA Coverup (govt, drugs, corruption, murder) Fixed video",
            "thumbnail": "https://conspyre.tv/videos/TheMENAConnectiongovtdrugscorruptionmurder_60739eed78abb1.43526106/TheMENAConnectiongovtdrugscorruptionmurder_60739eed78abb1.43526106_roku.jpg?cache=1665563402_1665563402",

            "id": "video_5577",
            "title": "The Great Awakening",
            "thumbnail": "https://conspyre.tv/videos/video_210521231320_b4ec/video_210521231320_b4ec_roku.jpg?cache=1665562803_1665562803",

            "id": "video_4921",
            "title": "Altiyan Childs Reveals the Worlds Secret Religion: Freemasonry",
            "thumbnail": "https://conspyre.tv/videos/XFACTORWINNERREVEALSWORLDSSECRETRELIGIONfreeMASONRY_608f7b8ab87403.06575801/XFACTORWINNERREVEALSWORLDSSECRETRELIGIONfreeMASONRY_608f7b8ab87403.06575801_roku.jpg?cache=1665563402_1665563402",

            "id": "video_11454",
            "title": "FBI LOST Biden Child Porn Evidence",
            "thumbnail": "https://conspyre.tv/videos/video_220914191453_va167/video_220914191453_va167_roku.jpg?cache=1663293055_1663293055",

```

To verify, I've been through the steps of 
  - deleting all thumbnails using `deleteThumbsFiles.php`
  - regenerating thumbnails by running python script to generate Roku JSONs (py script reads many JSON URLs, performs concatenation)

Question(1): what is the recipe to force it to regenerate *one* roku image so we can see what's failing? We need a flow to debug this.

Question(2): why do we have to use this .roku jpg anyway? It seems that I should be able to simply strip the _roku out of the filename & my thumbnails are going to start working. What is the point of having to generate this image (when it fails like 2% of the time)?

**Comment by DanielnetoDotCom** [comment]
you need a valid SSL

<img width="850" alt="image" src="https://user-images.githubusercontent.com/18009293/196825981-35201800-4561-4e25-a0c4-37ff16a85f2c.png">
