### ISSUE TITLE
3x comments bugs

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#7303]
Hi guys,

1. When you commenting when the thread gets long it goes off screen.
2. When you complete a comment what you type in the comments box is still there. 
3. Pin doesn't work, i see it working for admin only.

The first bug. Each time you type a reply it goes off a bit to the right. The longer people keep comment replying in the thread it eventually will go off screen completely, always to the right. You may not have noticed this if a lengthy comment reply thread wasn't made. This is a new bug as it wasn't happening last week in lengthy comment reply threads. This happens on the other system too.

Second bug is when you type in the comments input text box it doesn't clear the text from the box like it used too, as once you submit your comment the text shouldn't remain there in the input box also. This also happens on my other system.

Third bug if a user tries to pin a comment it just hangs and never completes. It works for admins though.

Many thanks

**Comment by DanielnetoDotCom** [comment]
On this new update

1, I could not reproduce it, please screenshot
2. fixed
3. fixed

**Comment by para2022** [comment]
Thanks mate that defo fixed 2. and 3.

![Screenshot 2022-10-24 at 18 07 50](https://user-images.githubusercontent.com/107706817/197585080-384d2fdb-1311-4516-bf0f-5aaa28f4bd61.png)

**Comment by DanielnetoDotCom** [comment]
I am not seeing the "off screen"

**Comment by para2022** [comment]
it will eventually go off screen the longer the thread continues especially on smaller screens, my screen is huge on a mac so its not so obvious

**Comment by para2022** [comment]
Another little bug i just stumbled across in comments is if I reply to a comment and thumb that comment up....it also thumbs up mine but if i refresh the page it displays correctly
