### ISSUE TITLE
Update error - urgent

### ISSUE THREAD

**Issue by awistudio** [WWBN/AVideo#7306]
pleas help

from version 11.4
after that
cd /var/www/html/AVideo/ && sudo git pull

login page displays

    array(4) { ["type"]=> int(1) ["message"]=> string(1024) "Uncaught Error: Call to a member function execute() on boolean in /var/www/html/AVideo/objects/mysql_dal.php:184 Stack trace: #0 /var/www/html/AVideo/plugin/Live/Objects/LiveTransmition.php(275): sqlDAL::readSql('SELECT u.*, lt....') #1 /var/www/html/AVideo/plugin/Live/Objects/LiveTransmition.php(407): LiveTransmition::keyExists('', true) #2 /var/www/html/AVideo/plugin/Live/Live.php(3478): LiveTransmition::getFromKey('') #3 /var/www/html/AVideo/plugin/Live/view/menuRight.php(7): Live::getInfo('', NULL) #4 /var/www/html/AVideo/plugin/Live/Live.php(59): include('/var/www/html/A...') #5 /var/www/html/AVideo/plugin/AVideoPlugin.php(261): Live->getHTMLMenuRight() #6 /var/www/html/AVideo/view/include/navbar.php(119): AVideoPlugin::getHTMLMenuRight() #7 /var/www/html/AVideo/plugin/Gallery/view/modeGallery.php(17): include('/var/www/html/A...') #8 /var/www/html/AVideo/view/index_firstPage.php(58): require('/var/www/html/A...') #9 /var/www/html/AVideo/view/index.php(20): include('/var/www/html/A...') #10 {main} thro" ["file"]=> string(42) "/var/www/html/AVideo/objects/mysql_dal.php" ["line"]=> int(184) } 

array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(1024) "Uncaught Error: Call to a member function execute() on boolean in /var/www/html/AVideo/objects/mysql_dal.php:184
Stack trace:
#0 /var/www/html/AVideo/plugin/Live/Objects/LiveTransmition.php(275): sqlDAL::readSql('SELECT u.*, lt....')
#1 /var/www/html/AVideo/plugin/Live/Objects/LiveTransmition.php(407): LiveTransmition::keyExists('', true)
#2 /var/www/html/AVideo/plugin/Live/Live.php(3478): LiveTransmition::getFromKey('')
#3 /var/www/html/AVideo/plugin/Live/view/menuRight.php(7): Live::getInfo('', NULL)
#4 /var/www/html/AVideo/plugin/Live/Live.php(59): include('/var/www/html/A...')
#5 /var/www/html/AVideo/plugin/AVideoPlugin.php(261): Live->getHTMLMenuRight()
#6 /var/www/html/AVideo/view/include/navbar.php(119): AVideoPlugin::getHTMLMenuRight()
#7 /var/www/html/AVideo/plugin/Gallery/view/modeGallery.php(17): include('/var/www/html/A...')
#8 /var/www/html/AVideo/view/index_firstPage.php(58): require('/var/www/html/A...')
#9 /var/www/html/AVideo/view/index.php(20): include('/var/www/html/A...')
#10 {main}
  thro"
  ["file"]=>
  string(42) "/var/www/html/AVideo/objects/mysql_dal.php"
  ["line"]=>
  int(184)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avidoeShutdown"
    ["args"]=>
    array(0) {
    }
  }
}

**Comment by DanielnetoDotCom** [comment]
looks like you have a problem o the database.,

please make sure MySQL is running properly

**Comment by awistudio** [comment]
how can i check it?

after executing this command it happened
after that
cd /var/www/html/AVideo/ && sudo git pull

**Comment by DanielnetoDotCom** [comment]
The only information on the log is that you could not connect in your database , delete your log file and try again , than share your whole log file

**Comment by awistudio** [comment]
I logged into the mysql database. but I don't know where to delete this log file

**Comment by DanielnetoDotCom** [comment]
The log is the videos/avideo.log file

**Comment by awistudio** [comment]
deleted avideo.log file
. but unfortunately there is no change. the page displays this error

**Comment by awistudio** [comment]
[avideo.log](https://github.com/WWBN/AVideo/files/9844251/avideo.log)
what can I do?

**Comment by GreenDragonTavern** [comment]
Shot in the dark but give this a try:
cd /var/www/html/AVideo
sudo git fetch --all && sudo git reset --hard origin/master
sudo chown -R www-data:www-data /var/www/html/AVideo

**Comment by DanielnetoDotCom** [comment]
@awistudio your errors are weird, looks like your update is not correct, try to do what @GreenDragonTavern recommends [above](https://github.com/WWBN/AVideo/issues/7306#issuecomment-1287821236).

**Comment by awistudio** [comment]
unfortunately that didn't help either.
how to get the website back to work?

**Comment by DanielnetoDotCom** [comment]
The problem is that your error is not clear 

make sure the database user and password matches with the variables in the configuration file

**Comment by awistudio** [comment]
Daniel, can you help me?
You did an installation on this server.
I think you have login details

**Comment by DanielnetoDotCom** [comment]
Hi

I can only provide free upgrades if you host with me

otherwise you need to have some server configuration background or hire me to do it for you

**Comment by GreenDragonTavern** [comment]
Have you tried a clean install? Might want to sudo apt update, sudo apt upgrade prior to below.

sudo systemctl stop apache2
cd /var/www/html
sudo mv AVideo AVideo-OLD
sudo git clone https://github.com/WWBN/AVideo.git
sudo mv ./AVideo-OLD/videos ./AVideo/.
sudo chown -R www-data:www-data ./AVideo
cd ./AVideo
sudo -u www-data composer update --prefer-dist --ignore-platform-reqs
sudo systemctl start apache2

See if you can login as admin. Paid plugins? If so, pull down latest and install.

**Comment by awistudio** [comment]
[GreenDragonTavern]
it didn't help either

[DanielnetoDotCom]
I understand well
you can take care of it? I'll pay it 

I wrote an email <developer@youphptube.com>

**Comment by DanielnetoDotCom** [comment]
I did not received any email yet but I am traveling now, I will be available in 4 hours

**Comment by DanielnetoDotCom** [comment]
Please send me the email

**Comment by awistudio** [comment]
Daniel write me an email. what data do you need?

**Comment by awistudio** [comment]
I wrote an email 
developer@youphptube.com

**Comment by DanielnetoDotCom** [comment]
Sorry I still didn’t get anything

**Comment by DanielnetoDotCom** [comment]
I need server and site admin credentials and also the 1 hour support purchase

**Comment by awistudio** [comment]
I have already sent to this address,
developer@youphptube.com

**Comment by awistudio** [comment]
i made the payment. please take care of it.

**Comment by DanielnetoDotCom** [comment]
I found this

you have the gallery plugin enabled, but you have all the sections disabled

<img width="805" alt="image" src="https://user-images.githubusercontent.com/18009293/197396412-2bc49d65-3b84-4aa7-ba83-650621aea85d.png">

I just enabled one section dateAdded

also code and plugins are now up to date, I am not seeing any other issue now

**Comment by awistudio** [comment]
I wrote to you on gmail.

**Comment by DanielnetoDotCom** [comment]
I keep sending you emails and you never respond

**Comment by awistudio** [comment]
we have some communication problem.
I sent you to this address
danielneto.com@gmail.com

**Comment by awistudio** [comment]
my address is awistudio@awistudio.pl

**Comment by awistudio** [comment]
sorry,
I found your email in spam
