### ISSUE TITLE
Big Videos are blurry and can't disable GifOnBigVideo

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#7312]
BigVideos are blurry. In the past it shows the *.jpg picture (which are sharper) and when you hover it shows the *.gif

When disabling **GifOnBigVideo** and clear the cache it still showing the *.gif

![Snap7](https://user-images.githubusercontent.com/39981177/197609451-e5efb6c2-fe5b-4cf3-8b9a-12f7988352ec.jpg)

**Comment by TLCReuver** [comment]
Hi Daniel, 

 I have updated today from 16-10-2022 to 25-10 2022 but have the same issue.
 
 Trying disable GifOnBigVideo and clearing cache (also browser) but it still shows the Animation_gif 
 
I thought in previous versions that images (*.jpg) are shown and when you hover over this *jpg it was showing the *.gif picture. The images weren't so blurry then.
 
![Snap8](https://user-images.githubusercontent.com/39981177/197782226-3059346d-f291-45ae-be75-625d9866facb.jpg)

 
 
**This is a snapshot from BigVideo:**

![_Snap8](https://user-images.githubusercontent.com/39981177/197780468-87a5cf3c-eba9-47fc-8960-c83d55da15f4.jpg)

**This is the *.jpg stored in the Videofolder:**

![_video_221007120000_vc2e0](https://user-images.githubusercontent.com/39981177/197780845-fe632eca-0e49-4972-9762-27bb2f6d96f8.jpg)

Trying disable GifOnBigVideo and clearing cache (also browser) but it still shows the Animation_gif

**Comment by DanielnetoDotCom** [comment]
please try this update

**Comment by TLCReuver** [comment]
I updated it, cleared cache (Avideo) & cache (Browser) but can not see any difference.

**Comment by DanielnetoDotCom** [comment]
Sorry, there was a missing update

Make sure you uncheck the GifOnBigVideo

**Comment by TLCReuver** [comment]
Updated and the "GifOnBigVideo"toggle is working now.
