### ISSUE TITLE
Comment on all videos

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#7313]
Daniel,
I don't know if this is a bug or not but it seems when you comment on one video, that comment show to all the other videos. This is likely a bug or a configuration issue. Comments should be exclusive to specific video. Please help fix this.

**Comment by DanielnetoDotCom** [comment]
yes, should be specific and I have never seen it.

can you reproduce it on the demo site?

**Comment by mankota** [comment]
Here is a video

https://user-images.githubusercontent.com/25535711/198141876-19e3fbf2-0bf6-43ac-a118-dc968a2ab2f0.mp4

**Comment by DanielnetoDotCom** [comment]
so you mean chat, NOT comment. yes, the chat is the channel chat, it will be shared on all videos that belong to the same user. 

only live streams can have separated chats
