### ISSUE TITLE
Pay Per View

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#7315]
Hello
the PPV plugin does not show the checkboxes
I'm doing something wrong?

Thank you
Ilias

![ppv](https://user-images.githubusercontent.com/60543030/197802023-4c00e707-5e5e-4472-943b-c052c13d7c82.jpg)

**Comment by DanielnetoDotCom** [comment]
Did you create a PPV plan?

**Comment by wetubeclub** [comment]
Yes!

**Comment by DanielnetoDotCom** [comment]
if you add the plan to a usergroup you cannot select a video for it.

to use usergroups, just add the video into that usergroup and all will be connected (easier way)

**Comment by wetubeclub** [comment]
You're right, I had forgotten
be well
thanks!!
