### ISSUE TITLE
Login  

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#7317]
Hello Daniel,
what settings should I make so that only I can have access to the site as an admin?
and no other user has access to connect to the site to the same time?

Thank you i advance
Ilias

**Comment by DanielnetoDotCom** [comment]
Sorry, what do you mean?

**Comment by wetubeclub** [comment]
if I disable the native login so that the button for entering the site does not appear, will I be able to log in as admin if so how?

Thank you
Ilias

**Comment by DanielnetoDotCom** [comment]
You can add the credentials on the url

?user=admi&pass=123

**Comment by wetubeclub** [comment]
this also applies to users?
ie if he does the same in the url he will be able to connect?
code 123 is for example?

thank you
Ilias

**Comment by wetubeclub** [comment]
the issue is that when I have the site under maintenance no one can log in except me!

Thank you
Ilias
