### ISSUE TITLE
Importing videos ignores the selected category.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7319]
**Describe the bug**
I just encoded ≈30 videos. For each video, I set the category before putting into the encoder.

Now? All of those videos are showing up with no category.

For each video, I set the category here:

![Screen Shot 2022-10-25 at 3 00 34 PM](https://user-images.githubusercontent.com/11711050/197890408-dfb1be58-4fd3-437b-a872-fafc115819e5.png)

And all of those videos are in categories_id=1:

![Screen Shot 2022-10-25 at 3 01 28 PM](https://user-images.githubusercontent.com/11711050/197890539-6543351b-9527-4154-affa-ad626369694f.png)

This wastes 15-20 minutes changing each of those DB entries by hand, after I already set the categories_id. 🤦‍♂️

This workflow is terrible.

**Comment by DanielnetoDotCom** [comment]
I also could not reproduce it here, I need your help to reproduce it.

**Comment by walt93** [comment]
Daniel-

This is about 95% reproducible for me here. Last night I did a git pull on the main site & on all encoders. I uploaded about 30 videos to a dozen different users accounts. All but a couple of them went to categories_id=1. Strangely, a couple of videos did go to the correct categories_id - so there is something intermittent about it.

You can give it a run on my system from your account, just leave it unpublished and delete when done.
