### ISSUE TITLE
Mass Upload and audio file link

### ISSUE THREAD

**Issue by olamidebello** [WWBN/AVideo#7320]
Please we need to do mass upload and we are also having issue with live stream link like this http://line.my-tv.cc:80/60d73136bd/d8fbf556c8/45446

**Comment by DanielnetoDotCom** [comment]
if your site is HTTPS (probably it is)

the HTTP link will not work

**Comment by olamidebello** [comment]
You had this issue fixed from the last build you did for us before the
server ceased. please advice

**Comment by DanielnetoDotCom** [comment]
Sorry, this is not an issue and I have never fixed that. this is a browser security limitation. it is impossible to work around it. 

the only solution is to reencode the link, but it will consume a lot of CPU, it does not worth
