### ISSUE TITLE
[+] Add to playlist button only works for some videos.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7326]
**Describe the bug**
Beyond a certain row  - the add to playlist button only works for some of the videos on a page.

**To Reproduce**
1. Go to a page of videos
2. For videos on the top row, click on [+] Add to 
3. Scroll down a bit and try, until it fails (when it does, you'll scroll back to the top)

**Expected behavior**
Should work for all videos on a page

![Screen Shot 2022-10-27 at 11 41 20 PM](https://user-images.githubusercontent.com/11711050/198520719-2c397fa1-7fa4-48fa-a527-042e440bd545.png)

**Comment by DanielnetoDotCom** [comment]
can you please share a link here so I can test?

**Comment by walt93** [comment]
https://conspyre.tv/cat/featured
