### ISSUE TITLE
Someone has created huge sharing queue on our server (from company) how to cancel/remove all?

### ISSUE THREAD

**Issue by BananamanCoolDude** [WWBN/AVideo#7328]
**Describe the bug**
Someone has created a huge sharing queue on our server (from our company) how to cancel all of the uploads as it's stuck for days now and does not load at all?

**To Reproduce**
Trying to upload video.

Trying to upload a video and it's been put at the back of the Queue and does not move on. **Not out of space.** Tried rebooting multiple times this does not sort out this issue..

**Expected behavior**
Upload a video.

**Screenshots**

[https://i.ibb.co/LRky9pw/queue.png](https://i.ibb.co/LRky9pw/queue.png) <-image of the issue

**Comment by DanielnetoDotCom** [comment]
Run this script manually on the terminal

https://github.com/WWBN/AVideo-Encoder/blob/master/install/deleteAllQueue.php

```
cd /var/www/html/Encoder/install/
php deleteAllQueue.php
```
replace /var/www/html/Encoder/install/ with your Encoder installation folder path
