### ISSUE TITLE
add text files

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo#7329]
Tell me, I need to add certain users, not only video, but also text files. Can this be done somehow? With the help of the Articles plugin, for example?

**Comment by DanielnetoDotCom** [comment]
sorry I do not understand what you want

**Comment by DittmerOk** [comment]
> sorry I do not understand what you want

I have a text document. in microsoft word. And I want the user to be able to see the contents of this file in their profile. Is it possible?

**Comment by DanielnetoDotCom** [comment]
you can upload zip files, you can make it as a zip and upload it

**Comment by DittmerOk** [comment]
> you can upload zip files, you can make it as a zip and upload it

What plugin can do this?

**Comment by DanielnetoDotCom** [comment]
Uncheck disableZipUpload

![image](https://user-images.githubusercontent.com/18009293/198639013-6080b17d-2cb4-4093-badd-dc382943fe1a.png)

**Comment by DittmerOk** [comment]
> Uncheck disableZipUpload
> 
> ![image](https://user-images.githubusercontent.com/18009293/198639013-6080b17d-2cb4-4093-badd-dc382943fe1a.png)

and where can i download it?
![image](https://user-images.githubusercontent.com/56869986/198660163-10e44284-340b-43c1-93c6-c11d90d2ecbb.png)

**Comment by DanielnetoDotCom** [comment]
Also uncheck doNotShowUploadMP4Button, then clear the cache

![image](https://user-images.githubusercontent.com/18009293/199001545-3a2fed4c-a1b3-4316-ae37-eda417b6c7c7.png)

**Comment by DittmerOk** [comment]
thanks, all is work

**Comment by DittmerOk** [comment]
![image](https://user-images.githubusercontent.com/56869986/199459185-023fe96d-4ae3-4b3a-82be-43ff0b93ea1c.png)
how can i download zip file?

**Comment by DanielnetoDotCom** [comment]
Duplicated https://github.com/WWBN/AVideo/issues/7350
