### ISSUE TITLE
disable all sections on the main page? Such as : Trending, Date added, Most watched?

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo#7330]
Tell me ... is it possible to somehow disable all sections on the main page? Such as : Trending, Date added, Most watched?

**Comment by DanielnetoDotCom** [comment]
Gallery plugin 

![chrome-capture-2022-9-28](https://user-images.githubusercontent.com/18009293/198654737-99a19089-7d4c-45ab-9ad9-9784d8e3aac5.gif)

**Comment by DittmerOk** [comment]
oh, thanks. this is what i need
