### ISSUE TITLE
Remove the side menu for user

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo#7331]
![image](https://user-images.githubusercontent.com/56869986/198666610-d7eed2b7-fca9-483c-ac28-04564fa01601.png)
Can I remove all additional functionality from users? Remove the side menu?

**Comment by DanielnetoDotCom** [comment]
probably the best option for you is to use CSS, but it requires some CSS background knowledge

**Comment by DittmerOk** [comment]
ok... where is all the markup on the page?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript

**Comment by DittmerOk** [comment]
So it's empty there. Where can I find the entire source code of a page so that it can be edited?
