### ISSUE TITLE
Skip intro and credits

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7332]
@DanielnetoDotCom , I check that the videos that are playing in the playlist in Full frame, do not show if there is a next video.
For example what streaming platforms do today. Enter a countdown and a button for the user to skip the credits. Or even at the beginning of the video, an option to skip the intro.
Does it already exist? I think it's a very interesting function to keep the user's interest in the playlist.

**Comment by DanielnetoDotCom** [comment]
yes that is a good idea, but we do not have it yet

**Comment by DanielnetoDotCom** [comment]
are you up to date on that site?

the problem is that I could not reproduce it on my side, also it is working fine on demo site.
