### ISSUE TITLE
How do we turn off the "Source" display on the video's page

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7333]
**Describe the question**

How to remove the 2nd field and link in this screenshot?
![Screen Shot 2022-10-28 at 5 42 56 PM](https://user-images.githubusercontent.com/11711050/198753981-57deaa13-941b-49ea-b638-9aa92e778177.png)

**Comment by wetubeclub** [comment]
disable it in customize advanced settings plugin is at the end

![soucre](https://user-images.githubusercontent.com/60543030/198827707-3817589f-9b8f-463e-9f38-1eda76dd983d.jpg)
