### ISSUE TITLE
Remove publishing time

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7335]
@DanielnetoDotCom , How do you remove this publishing time?

![image](https://user-images.githubusercontent.com/37880073/198815498-cd268fb4-bf66-4a73-9233-b7ae497f1de6.png)

**Comment by DanielnetoDotCom** [comment]
try to use CSS to remove it

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript
