### ISSUE TITLE
How do u turn this off or make it not visible? FHD

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7336]
![491c88ac-637c-4b39-a993-e6815c57e267](https://user-images.githubusercontent.com/39392449/198821121-f2c5a133-1bdd-4021-8b72-89c854cd5974.png)

**Comment by DanielnetoDotCom** [comment]
Try to use CSS to hide it

**Comment by JoshWho** [comment]
It doesn't have a switch? I thought it did

**Comment by JoshWho** [comment]
Trying with css doesn't seem to work unless I am doing this wrong maybe.

`<style>
.span.label.label-danger.videoLabelPlugin.alreadyTooltip

display: none;
</style>

<style>
  .label-danger {
    display: none;
}
</style>`

**Comment by JoshWho** [comment]
Nevermind it is working now. That is the solution above

**Comment by JoshWho** [comment]
This still does not hide it on the home page. Just on the video player page. How to make it Hide on the homepage?

**Comment by DanielnetoDotCom** [comment]
Hi Josh, try this:

```
.videoLabelPlugin.label-danger{
    display: none;
}
```
Also if you can please share this on your page https://tutorials.avideo.com/video/126/fraude-na-eleicao-2022-auditoria-privada-brazilwasstolen

#BrazilWasStolen

**Comment by JoshWho** [comment]
Didn't work still shows on the home page 


Will Share that.

**Comment by DanielnetoDotCom** [comment]
I did not see the CSS on your page. 

anyway try to add !important to it

```
.videoLabelPlugin.label-danger{
    display: none !important;
}

```

**Comment by JoshWho** [comment]
> I did not see the CSS on your page.
> 
> anyway try to add !important to it
> 
> ```
> .videoLabelPlugin.label-danger{
>     display: none !important;
> }
> ```

That did the trick, Thank you @DanielnetoDotCom
