### ISSUE TITLE
The Registration Date and Location.

### ISSUE THREAD

**Issue by lachainestoplinky** [WWBN/AVideo#7337]
Hello,
I suggest you add these two pieces of information on the player page of a video.
  The Registration Date and Location.
in manual addition to be able to write it as desired in a dedicated area. ( under the title )
currently I put the date in the title and the location in the description.

Who do you think of this idea?
Cordially
![Capture d’écran 2022-10-29 à 11 17 06](https://user-images.githubusercontent.com/39954233/198824041-bd51f4ff-7c0e-4d92-830b-e8cdd151c976.png)
![Capture d’écran 2022-10-29 à 11 17 06 - copie](https://user-images.githubusercontent.com/39954233/198824749-8a36fa0d-aac8-4e1c-9027-9852913af997.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure about registration, but I have plans to enter the publication date and let you schedule the videos for future publishing

**Comment by lachainestoplinky** [comment]
ello, I was thinking of a text box under the title to add the date and location. or anything else.
