### ISSUE TITLE
Change log for plugins updates

### ISSUE THREAD

**Issue by mankota** [WWBN/AVideo#7338]
Hi Daniel,
Are there changelog for these updates for these plugins? The reason I am asking is because sometimes you will see update available in the plugin but you don't know what was changed. So, it is difficult to understand how the update affect your website. I just updated the sendrecordedtoencoder plugin and try to go live for testing. I noticed that the recorded video is showing not available and I don't know what went wrong. Here is some of the configuration settings
![image](https://user-images.githubusercontent.com/25535711/198841544-3a4070d2-3f88-4814-90d6-d06883c4820b.png)

**Comment by DanielnetoDotCom** [comment]
Not every plugin update includes a new feature, some time it is just an adaptation for the new Streamer version.

Always when you make a git pull, is strongly recommended your plugins are also up to date.

do not update your plugins if you do not make a git pull on the Streamers site
