### ISSUE TITLE
happens after sometime

### ISSUE THREAD

**Issue by Tinoisthe** [WWBN/AVideo#7340]
**Describe the question**
A clear and concise description of what is your question.
AVideoLog::ERROR: [sqlDAL::readSql] (stmt) is empty SELECT * FROM users_groups as ug WHERE 1=1 with formats SCRIPT_NAME: /view/index.php
**Screenshots**
Provide some screenshots to help us understand and explain your problem.
![avid](https://user-images.githubusercontent.com/76804686/198971033-0d3bbf13-772a-422c-a586-3b308511a519.PNG)
![image](https://user-images.githubusercontent.com/76804686/198971098-03678c34-14e7-4779-b8f6-3bebb4282bf0.png)

**Comment by DanielnetoDotCom** [comment]
I need to see more from your log, but I suspect you did not configure MySQL peoperly

**Comment by Tinoisthe** [comment]
thanks

**Comment by rprabhune** [comment]
i am also facing the same issue after fresh install 
![Screenshot 2022-11-07 202717](https://user-images.githubusercontent.com/38142203/200341768-16a7c474-c321-4278-a270-92da6fb75284.jpg)
