### ISSUE TITLE
how to bulk transfer videos to another group?

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#7346]
Hello,
i have many videos which are for the free group,
but I want to transfer them to the other two premium and privilege groups
my question is the following:
it is possible to do it with some command and update everything at once?
because there are a lot if I do them manually I want at least a year!!!

Thank you i advance
Ilias

**Comment by DanielnetoDotCom** [comment]
Hi, the easiest way is to do it with a MySQL command line.

I do not have it on top of my mind but it depends on what user group will be removed and what will be added. and also the date limit.
