### ISSUE TITLE
Imojies popup in chat are not showing

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7347]
Opening the imojies popup in the chat will show like this screen shot:

![Screen Shot 5783-02-07 at 11 53 53](https://user-images.githubusercontent.com/58882903/199208073-513cd170-b7b9-4f6d-8d24-d685b029396b.jpg)

and in the text field it will show as follows but when sent it will show in the chat:

![Screen Shot 5783-02-07 at 11 54 10](https://user-images.githubusercontent.com/58882903/199208215-cd090e44-1b6b-439d-b8be-06d8b67167bf.jpg)

Not sure if it only occurs on my site.

**Comment by DanielnetoDotCom** [comment]
try to inspect the JS console and detect what file and what reason something is not loading

**Comment by guymass** [comment]
This is what I get:

![Screen Shot 5783-02-07 at 17 47 44](https://user-images.githubusercontent.com/58882903/199276604-311ef308-b647-4d4c-b428-2a30f35c4d32.jpg)

**Comment by DanielnetoDotCom** [comment]
Are you using an old Chat2 plugin version? the current version is Version: @11.3

those images suppose to be pushed from your domain, NOT from a external CDN

**Comment by guymass** [comment]
This is my version, im fully updated.

![Screen Shot 5783-02-09 at 18 08 17](https://user-images.githubusercontent.com/58882903/199773381-78133fdf-cda1-4305-9f9e-6f290a752275.jpg)

**Comment by DanielnetoDotCom** [comment]
can you please share the chat page here so I can inspect it?

**Comment by guymass** [comment]
You know you still have admin account on my site so you can check anything. This is the page for all the channel's chat rooms, so you can open anyone of them to test.

https://alive528.com/plugin/Chat2/listRooms.php

**Comment by DanielnetoDotCom** [comment]
I do not have a user to use, and I tired to register a new user and I found a bug. 

I do not think this bug has anything to do with your chat, but please make a git pull on your streamer.

**Comment by guymass** [comment]
I cleaned caches and made a git pull but still same bug. I sent you an email to gmail with your account details. let me know if you can login.

**Comment by DanielnetoDotCom** [comment]
Can you please disable the Onesignal on the Notification plugin?

![image](https://user-images.githubusercontent.com/18009293/199785168-91473a1b-7a7c-4297-b10b-75744d8a63f3.png)

**Comment by guymass** [comment]
Ok its disabled

**Comment by guymass** [comment]
OK its working now:
![Screen Shot 5783-02-09 at 19 55 54](https://user-images.githubusercontent.com/58882903/199798463-0326a562-9700-4196-a107-3f6ba7f18e87.jpg)

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Notifications-Plugin#onesignal

**Comment by guymass** [comment]
Greate that seems to fix this issue, i am closing this one, much thanks.
