### ISSUE TITLE
SecureVideosDirectory Plugin

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#7348]
Also using SendRecorderToEncoder.

Documentation (https://github.com/WWBN/AVideo/wiki/SecureVideosDirectory-Plugin) has section to modify .htaccess. Below is from documentation:
sudo nano /var/www/html/YouPHPTube/.htaccess
<IfModule mod_xsendfile.c>
    RewriteRule    ^videos/([A-Za-z0-9-_.]+)$ view/xsendfile.php?file=$1    [NC,L]
</IfModule>

.htaccess had the following prior to following documentation:
    <IfModule mod_xsendfile.c>
        RewriteRule    ^videos/([_A-Za-z0-9.-]+/)?([^!#$&'()*+,\/:;=?@[\]]+(\.(mp4|webm|m3u8|mp3|ogg)))$ view/xsendfile.php?file=$2&folder=$1    [QSA]
        RewriteRule    ^videos/cache/download/([_A-Za-z0-9.-]+/)?([^!#$&'()*+,\/:;=?@[\]]+(\.(mp4|webm|m3u8|mp3|ogg)))$ view/xsendfile.php?file=$2&cacheDownload=1    [QSA]
    </IfModule>

AVideo does not record live when adding SecureVideosDirectory Plugin documented code. Removed the code and all good. Please update SecureVideosDirectory Plugin documentation.  Thank you.

**Comment by GreenDragonTavern** [comment]
Umm...Your documentation says to. The plugin has a direct link to configuration...below is exactly what you specify in documentation. I restored .htaccess and issue went away. Guess I'm confused on why documentation states to do something you specifically state NOT TO DO.

https://github.com/WWBN/AVideo/wiki/SecureVideosDirectory-Plugin#uncomment-your-htaccess-file

**Comment by DanielnetoDotCom** [comment]
I see...

 the document is outdated, this line is already uncommented by default.

I will update the document.

**Comment by GreenDragonTavern** [comment]
Thank you. While I have you, plugin also states this for encoders:
$global['watermarkDomainWhitelist'] = 'https://domain.com/';

Using multiple encoders and encoder network. What happens when domain1.com and domain2.com both use plugin? Do I modify encoder configuration.php with this:
$global['watermarkDomainWhitelist'] = 'https://domain1.com/';
$global['watermarkDomainWhitelist'] = 'https://domain2.com/';
or
$global['watermarkDomainWhitelist'] = 'https://domain1.com/, https://domain2.com';

Thanks again for all, Don.

**Comment by DanielnetoDotCom** [comment]
Before using, the watermark, first make sure your recording and encoder are working.

**Comment by GreenDragonTavern** [comment]
They are, live and live recording are working as advertised after restoring .htaccess.

**Comment by DanielnetoDotCom** [comment]
So I am still not sure what is the issue

**Comment by GreenDragonTavern** [comment]
SecureVideosDirectory Plugin states to add $global['watermarkDomainWhitelist'] = 'https://domain.com/'; to your encoder(s). My question is what if two (2) domains are applicable (we use multiple encoders, encoder network for 2 AVideo sites). If both sites use SecureVideosDirectory what is format to update encoder(s) configuration.php:

This:

$global['watermarkDomainWhitelist'] = 'https://domain1.com/';
$global['watermarkDomainWhitelist'] = 'https://domain2.com/';

or this:

$global['watermarkDomainWhitelist'] = 'https://domain1.com/, https://domain2.com/';

Not sure how to update Encoder(s) configuration.php with multiple AVideo domains.

**Comment by DanielnetoDotCom** [comment]
The watermark is still under development but it should be like this:


`$global['watermarkDomainWhitelist'] = array('https://domain1.com/', 'https://domain2.com/', ...);`

**Comment by GreenDragonTavern** [comment]
Ah, got it and thank you. Also, have a separate server that has OvenMediaEngine installed and running. What I can't find are files referenced here: https://github.com/WWBN/AVideo/wiki/WebRTC-Server

Is there any way to download and test here?  Again, appreciate your AVideo efforts and timely responses.

**Comment by DanielnetoDotCom** [comment]
OvenMediaEngine is still under development, I do not think it is working properly yet.

**Comment by GreenDragonTavern** [comment]
Would you mind if I could get access to WebRTC files, test and see if I can get it working here? Any mods done that are positive would certainly be shared with you, or anyone involved with AVideo. Won't bug ya a lot on it but may have a question or two if amendable there. Thoughts?

**Comment by DanielnetoDotCom** [comment]
sorry right now I cannot provide it.

**Comment by GreenDragonTavern** [comment]
Understand, you don't know me from Adam. Is there any way to get vetted by you and create a comfort zone between us?

**Comment by DanielnetoDotCom** [comment]
I am not sure if I will share, but email me at developer@youphptube.com

**Comment by GreenDragonTavern** [comment]
That's a start, and thank you.
