### ISSUE TITLE
Bug in notification bell

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7359]
I have just noticed that when I get notification showing in the bell, like comments and likes, after I click any of them or even just going into any video to watch, those notifications are no longer shown on the bell and it gets a grey icon. I can only view them on the home page of the site as in the following screen shots:

The first shows them on home page:
![Screen Shot 5783-02-12 at 16 48 27](https://user-images.githubusercontent.com/58882903/200177804-02dcaccc-3cb9-41d6-8323-ef5dbcf90e7a.jpg)

After clicking any one of those notifications it takes me to the video post page and there the bell is showing like this:
![Screen Shot 5783-02-12 at 16 48 36](https://user-images.githubusercontent.com/58882903/200177833-198dec4e-2014-4479-bbd8-6ed35aab823c.jpg)

I believe you want those notifications to show up throughout the entire site on any page.

**Comment by DanielnetoDotCom** [comment]
Check your JS console, for errors
