### ISSUE TITLE
Installation error: Failed opening required '/xxxx/www/view/img/../../videos/configuration.php'

### ISSUE THREAD

**Issue by ekc-fr** [WWBN/AVideo#7365]
hi, 
just installing Avideo on a centos7.9 with apache 2.2 php8 and mariadb10.5
i use the zip file because my server is not connect to internet
I use a virtualhost apache and tls configuration to use https

on the installation page i got the error
![image](https://user-images.githubusercontent.com/44778782/200355042-973dfc4d-528f-45bd-a3bd-82b363d7a0b2.png)
in the apache log:
PHP Fatal error:  Uncaught Error: Failed opening required '/xxxx/www/view/img/../../videos/configuration.php'
the file doesn't exist, apache own all the directory

what can i do ?
(excuse my poor english )

**Comment by DanielnetoDotCom** [comment]
I strongly recommend you use Ubuntu without any type of control panel.

you can try centos with your own risk

https://github.com/WWBN/AVideo#important-information

**Comment by DanielnetoDotCom** [comment]
not recommended but if you know how to do it, you can

**Comment by ekc-fr** [comment]
the problem will be the `$global['salt']`
