### ISSUE TITLE
Feature request: Turn off this UI

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7366]
**Is your feature request related to a problem? Please describe.**
This is not good. How do we remove it? I do not want nor do the users need a matrix of login buttons. This looks awful, Daniel.

![Screen Shot 2022-11-08 at 3 29 09 PM](https://user-images.githubusercontent.com/11711050/200698043-cf411c44-127c-4f8f-a94d-f5b21f4cd64d.png)

**Comment by DanielnetoDotCom** [comment]
I just checked your site and I cannot see that button, I do not know where it comes from

**Comment by DanielnetoDotCom** [comment]
![chrome-capture-2022-10-8](https://user-images.githubusercontent.com/18009293/200700546-22c785c4-8296-408e-bd3d-4029d47edc9d.gif)

**Comment by walt93** [comment]
That is really strange, that it happened, that it stopped... Never seen it before. Maybe a Safari issue that nobody sees because I'm one of the few masochists that still use this 💩 browser
