### ISSUE TITLE
Sorry Unknown error!

### ISSUE THREAD

**Issue by R4T0** [WWBN/AVideo#7368]
![image](https://user-images.githubusercontent.com/73944522/201179507-2e59c23c-cda4-489e-b28e-03c56eb114b7.png)

Está dando um erro durante a instalação 
Meu servidor Debian 10 Buster
10Gb RAM 8cores
php 8.1 - fpm 8.1
todos os plugins instalados normalmente

**Comment by DanielnetoDotCom** [comment]
check apache error, but your MySQL user probably does not have create database and table privileges
