### ISSUE TITLE
AD_Overlay not working as expected

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7369]
**Describe the bug**
On **Youtube** the 468x60 banner is displayed nicely centered in the bottom 1/3 of the screen.

On **AVideo** the 468x60 banner is clipped and the screen placement is bizarre.

How to achieve bottom 1/3 of screen and displaying at 468x60?

**To Reproduce**
1. Create Adspeed account, upload 468x60 banner, and get a script for the zone that contains your 468x60 banner
2. Drop Adspeed code into AVideo AD_Overlay plug-in
3. Observe unexpected / bad results.

**Expected behavior**
A 468x60 image to appear, centered in the bottom 1/3 of the screen.

Here's trying "center":
![Screen Shot 2022-11-10 at 2 20 24 PM](https://user-images.githubusercontent.com/11711050/201218219-5cdac08b-eaf3-422e-900b-b3b757288007.png)

Here's trying "bottom":
![Screen Shot 2022-11-10 at 2 22 19 PM](https://user-images.githubusercontent.com/11711050/201218596-a025d63d-b9b7-4662-b869-6ae94c23543a.png)

When I say "center" or "bottom" I mean the "align:" parameter, which defaulted to "bottom-left":
![Screen Shot 2022-11-10 at 2 23 32 PM](https://user-images.githubusercontent.com/11711050/201218778-ddd559ac-f87d-4744-bd3f-a5e0d1d8f21b.png)

Here's "bottom-left":
![Screen Shot 2022-11-10 at 2 26 43 PM](https://user-images.githubusercontent.com/11711050/201219281-0d358beb-45d7-4b5a-a0f5-af48bacb6c09.png)

Here is the script from Adspeed for a 468x60 image, as you can see, it encodes the resolution in its HTML numerous ways:

```
<!-- AdSpeed.com Tag 8.1 for [Zone] Conspyre.tv 468x60 overlay 468x60 -->
<script type="text/javascript">var asdate=new Date();var q='&tz='+asdate.getTimezoneOffset()/60 +'&ck='+(navigator.cookieEnabled?'Y':'N') +'&jv='+(navigator.javaEnabled()?'Y':'N') +'&scr='+screen.width+'x'+screen.height+'x'+screen.colorDepth +'&z='+Math.random() +'&ref='+escape(document.referrer.substr(0,255)) +'&uri='+escape(document.URL.substr(0,255));document.write('<ifr'+'ame width="468" height="60" src="https://g.adspeed.net/ad.php?do=html&zid=118516&oid=28182&wd=468&ht=60&target=_blank'+q+'" frameborder="0" scrolling="no" allowtransparency="true" hspace="0" vspace="0"></ifr'+'ame>');</script>
<noscript><iframe width="468" height="60" src="https://g.adspeed.net/ad.php?do=html&zid=118516&oid=28182&wd=468&ht=60&target=_blank" frameborder="0" scrolling="no" allowtransparency="true" hspace="0" vspace="0"><a href="https://g.adspeed.net/ad.php?do=clk&zid=118516&oid=28182&wd=468&ht=60&pair=as" target="_blank"><img style="border:0;max-width:100%;height:auto;" src="https://g.adspeed.net/ad.php?do=img&zid=118516&oid=28182&wd=468&ht=60&pair=as" alt="i" width="468" height="60"/></a></iframe>
</noscript><!-- AdSpeed.com End -->
```

Here's how it renders in Brave. This, I believe is "align: bottom-left"

I've tried numerous align modes, it's not rendering an image in Brave.

![Screen Shot 2022-11-10 at 6 43 26 PM](https://user-images.githubusercontent.com/11711050/201251321-33d0fc3f-24f5-4042-8b0d-4bb2f678a2e1.png)

I removed the javascript from the Adspeed tag, and tried only the <iframe>, and, results are unchanged.

Chrome, we get the image, but the height is too short like Safari:

![Screen Shot 2022-11-10 at 6 51 06 PM](https://user-images.githubusercontent.com/11711050/201252398-66cd7337-d121-40be-963d-02b11ba77cdf.png)

FWIW this is the 468x60 pixel image we're trying to display:
![switch1](https://user-images.githubusercontent.com/11711050/201252675-552e94a0-7c95-4aa5-b715-34565b0ac2f9.png)

**Comment by walt93** [comment]
Here's how it renders in Brave. This, I believe is "align: bottom-left"

I've tried numerous align modes, it's not rendering an image in Brave.

![Screen Shot 2022-11-10 at 6 43 26 PM](https://user-images.githubusercontent.com/11711050/201251321-33d0fc3f-24f5-4042-8b0d-4bb2f678a2e1.png)

I removed the javascript from the Adspeed tag, and tried only the <iframe>, and, results are unchanged.

**Comment by DanielnetoDotCom** [comment]
it may require some tweaks.

try to see your js console output

I suspect you will need to force increase the ad placeholder height, it is hard to tell because you are using a dynamic JS, the results are unpredictable

**Comment by walt93** [comment]
I didn't see any JS errors in the console. Comparing the script tags, AVideo defaults to some Google tags:

```
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- AVideo Videos -->
<ins class="adsbygoogle"
     style="display:inline-block;width:468px;height:60px"
     data-ad-client="ca-pub-8404441263723333"
     data-ad-slot="6092946505"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
```

Looking at AD_Overlay.php, it looks like you're defining that adsbygoogle class and giving it that 60px height.

Hacking that class into the output sees to give it some vertical space, though it's a bit much now.

```
<ins class="adsbygoogle" style="display:inline-block;width:468px;height:60px”></ins>

<iframe width="468" height="60" src="https://g.adspeed.net/ad.php?do=html&zid=118516&oid=28182&wd=468&ht=60&target=_blank" frameborder="0" scrolling="no" allowtransparency="true" hspace="0" vspace="0">
	<a href="https://g.adspeed.net/ad.php?do=clk&zid=118516&oid=28182&wd=468&ht=60&pair=as" target="_blank">
		<img style="border:0;max-width:100%;height:auto;" src="https://g.adspeed.net/ad.php?do=img&zid=118516&oid=28182&wd=468&ht=60&pair=as" alt="i" width="468" height="60"/>
	</a>
</iframe>
```

![Screen Shot 2022-11-19 at 2 59 06 PM](https://user-images.githubusercontent.com/11711050/202874839-c997e1a6-e193-428c-837e-0bc05beeb1bc.png)
