### ISSUE TITLE
Is it possible to fix the open graph tags?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7370]
**Describe the bug**
I want to share open graph tags. But the messaging is mixed & not working when we do.

**To Reproduce**
1. Share a link to a category page. Example: https://conspyre.tv/cat/disclosure-hub
2. Look at the card it renders in Twitter, Gab, etc.3. 

![IMG_3567AA992ABE-1](https://user-images.githubusercontent.com/11711050/201247301-926670e9-5c91-461e-9fae-360f6fd54c3e.jpeg)

Here we see the name of the category, and the tagline for the website.

The tagline for the website has _nothing whatsoever_ to do with the category. The category has a description. Let's use it. I am getting complaints from the Disclosure Hub account, who has a *massive* following on Telegram. Think of D-hub as a brand. He is saying things to me like "dude, your site is retarded".

I reported this like a year ago, and you didn't want to change it. Would you please let me know where in the code to go hack this together so I can modify it for my users?

**Comment by DanielnetoDotCom** [comment]
Sorry, I am not understanding what are you looking for

is it only the description?
What does it suppose to look like? 
what exactly is wrong?

**Comment by walt93** [comment]
"We are the news now" is the tagline for the site, I believe coming from "Customize Advanced". Conspyre is my brand.

"Disclosure Hub" is an entrepreneur with socials that get 100,000-300,000 engagement per day, that his his brand.

When we post a link to his media, he is getting the messaging from my brand.

Posting the category to social media, should include some text from that categories description, not from the site.

https://mysite/cat/foo should emit

conspyre.tv
{category title}
{category description}

not

conspyre.tv
{category title}
{site description}

**Comment by DanielnetoDotCom** [comment]
Please check this update
