### ISSUE TITLE
Question. How to place an embed within the site.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7371]
**Describe the question**
I'd like to create a menu on the left like the links on JoshWhoTV.com (like the FAQ and Support etc. - they load some embed content - example - you hit the "support center" menu item and the web page is https://www.joshwhotv.com/menu/support_center - and the support center content comes from an embed.

How to achieve this?

**Screenshots**
![Screen Shot 2022-11-12 at 12 14 24 AM](https://user-images.githubusercontent.com/11711050/201465167-43a1285e-f082-410d-b51f-b308d3bb0241.png)

(I can't give a good screenshot of the support center because the site Josh is embedding is down) @JoshWho FYI

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/WWBN/AVideo/wiki/How-to-use-TopMenu-Plug-in
