### ISSUE TITLE
Streamer Failed after update to v12.2

### ISSUE THREAD

**Issue by mypride-Fortis** [WWBN/AVideo#7373]
Hello guys, after update to v12.2 from 12.1 using the following command:
cd /var/www/html/AVideo/ && sudo git pull
and then
cd /var/www/html/AVideo/Encoder && sudo git pull 
the response was update successful.
When I try to login, I could not have access to the front end. The Encoder works but frontend to streameer not showing anything. It is blank'
https://e-vidbox.com

Kindly assist, thank you.

**Comment by DanielnetoDotCom** [comment]
here your page seems to be fine
