### ISSUE TITLE
pay-per-view

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#7375]
Hello Daniel
when there are pay-per-view videos the video photo is not displayed
appeared before
the same happens in the demo
it's some setting i need to do?

Thank you
Ilias
![avideo](https://user-images.githubusercontent.com/60543030/201514010-67665483-3003-4e08-a1d3-badf1ad0413f.jpg)

![goo](https://user-images.githubusercontent.com/60543030/201514014-4eddcf05-4837-4d9f-9752-62d05c5aa74a.jpg)

**Comment by DanielnetoDotCom** [comment]
Thanks, please check PPV plugin version 7.1

**Comment by wetubeclub** [comment]
Thank you Daniel
it works like a charm!!!
Ilias
