### ISSUE TITLE
 bugs report

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#7376]
hey
Recently several features stopped working

Changing the theme does not work

![photo_2022-11-13_22-39-02](https://user-images.githubusercontent.com/85537931/201543570-5f503095-9a73-46dc-a5d7-50f6ff379068.jpg)

get jpeg/gif does not work

![photo_2022-11-13_22-41-22](https://user-images.githubusercontent.com/85537931/201543660-95f39d00-78df-45a5-9569-994cf490d335.jpg)

add bookmarks dont work

![photo_2022-11-13_22-55-01](https://user-images.githubusercontent.com/85537931/201544153-2a3c89f6-13a8-41da-8bdb-b39af8086ce7.jpg)

tnx
eitan live528

**Comment by DanielnetoDotCom** [comment]
This may fix the change theme

on get jpeg/gif and book mark, what error do you see?

**Comment by eitanwa** [comment]
hey
Regarding the Jpeg/gif files, at the moment I see that it works
(At first the files were broken, then they didn't appear at all)
So I will test it again in the next few days

Regarding the bookmarks

This is a link to a video that I bookmarked
They just don't show up

https://alive528.com/v/17645

![image](https://user-images.githubusercontent.com/85537931/201735105-8511b365-e800-4605-81fd-f94ec61970c1.png)

Tnx
eitan live528

**Comment by DanielnetoDotCom** [comment]
I could not find the problem, but as long as you are not using the AD_server try to disable it first.

**Comment by eitanwa** [comment]
Yes, as soon as I turned it off, the bookmarks appear
