### ISSUE TITLE
Allow download and Allow share not working

### ISSUE THREAD

**Issue by ganddser** [WWBN/AVideo#7377]
These features turn off on their own.

Allow the download and Allow share videos turn off on all accounts. After turning on again they stay on for a few minutes, then when the site reloads or you log off the features are off again.

**Comment by DanielnetoDotCom** [comment]
Where are you turning it on? please screenshot it

Also check your avideo logs

**Comment by ganddser** [comment]
Turned it on from the My Account and on the My Videos pages three or four times, and every time either after a few minutes or after logging off and logging back in, the settings would have turned off again. However, after the last git pull and upgrade to v12.2 two days ago, the allow download and allow share have remained enabled.

**Comment by ganddser** [comment]
This issue was never fixed.
![Untitled-2](https://github.com/WWBN/AVideo/assets/37193130/56e23c69-e5c7-460e-948e-4646cd4d6c1b)
![Untitled-4](https://github.com/WWBN/AVideo/assets/37193130/ad7c3b5b-2e57-4edd-b6ae-a6504311b835)
![Untitled-6](https://github.com/WWBN/AVideo/assets/37193130/8b08fec1-e329-495f-9de3-d16173467d81)
![Untitled-8](https://github.com/WWBN/AVideo/assets/37193130/22385230-017b-485b-9925-c4298eb74ea4)
