### ISSUE TITLE
Can no longer update the Live Search Plugin

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7385]
Live search is showing back for sale on my store login

**Comment by DanielnetoDotCom** [comment]
Hi

livesearch was always part of the paid plugins. 

you may have access to it already

**Comment by JoshWho** [comment]
I am just saying it wants me to purchase it again. I need access to it so I can update it. My login which is my Gmail on here is the account I thought that was attached to/ Not sure.

**Comment by DanielnetoDotCom** [comment]
try now

**Comment by JoshWho** [comment]
Working now thank you
