### ISSUE TITLE
Change display of CONNECTED SOCKET app

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#7386]
Is it possible to delete 1?

Can I decide which one to keep?  
The one above or below.

How to get rid of both?

Thanks 

![Screenshot_20221115-235119_Admin Shark.jpg](https://user-images.githubusercontent.com/82677269/202042253-282a9fd7-df0b-4bb8-be4f-abde89406c4d.jpg)

**Comment by DanielnetoDotCom** [comment]
Uncheck this 

![image](https://user-images.githubusercontent.com/18009293/202195568-ea3a3585-785f-4dea-998d-4c7869703fc9.png)
