### ISSUE TITLE
Images for channel art, sometimes the site graphic are being scaled/zoomed in.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7388]
**Describe the bug**
For approximately 2-3 months, the channel art and site images have been getting zoomed in, seemingly of their own accord. Adjusting the slider to change the scaling, does not work (value is ignored / forgotten)

**To Reproduce**
1. Go to User Profile
2. Upload channel art
3. Exit the page and come back to it

**Expected behavior**
The images to remain at the scaling set by the user.

Upload this:
![Screen Shot 2022-11-16 at 1 03 05 AM](https://user-images.githubusercontent.com/11711050/202136469-20bac371-8242-4e47-9882-22e0f2eb778e.png)

Get this:
![Screen Shot 2022-11-16 at 1 03 15 AM](https://user-images.githubusercontent.com/11711050/202136508-d35cb4b6-baf8-4b6d-a038-1bfefc000d2c.png)

And this:
![Screen Shot 2022-11-16 at 1 06 26 AM](https://user-images.githubusercontent.com/11711050/202137183-b02c7d57-731a-430b-8e3e-cbb76cdb823e.png)

**Comment by DanielnetoDotCom** [comment]
can you please share the original image file that you are using?

I want to make sure the size matches

**Comment by walt93** [comment]
Original attached
![wwg1wga](https://user-images.githubusercontent.com/11711050/202308922-85e72129-245e-4b27-b87a-374932bb4997.jpeg)
