### ISSUE TITLE
Live stream notification issue after update

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7389]
We had that issue before, again now after updating, when going live stream we get multiple notifications of the stream and it seems to go crazy, still not sure why, I will keep checking but for now here are screenshots of how it looks.

![photo_2022-11-16 20 28 00](https://user-images.githubusercontent.com/58882903/202262989-954942e0-316f-4cb7-90a5-e61ff0e8345a.jpeg)
![Screen Shot 5783-02-22 at 20 25 32](https://user-images.githubusercontent.com/58882903/202263044-0acce2ff-ede7-4a12-be09-e3fd1a2ac8fe.jpg)

**Comment by guymass** [comment]
Live stream keeps disappearing and appearing on front page, it gets couple of notifications but only the one named false is working. Something is wrong.

**Comment by guymass** [comment]
Now it is showing again but like this:

![Screen Shot 5783-02-22 at 20 34 24](https://user-images.githubusercontent.com/58882903/202264428-85ecceba-d65c-4c97-8067-50f1699dbb34.jpg)

**Comment by guymass** [comment]
Also while the stream is running is will create a post every few seconds which makes us keep deleting those posts.
![Screen Shot 5783-02-22 at 20 38 27](https://user-images.githubusercontent.com/58882903/202265355-5983637e-7688-4865-b1a7-b64f9e8ff38e.jpg)

This is the same stream, check the time between each created post on 'My Videos' page.

**Comment by DanielnetoDotCom** [comment]
the symptoms seem to be your live is disconnecting and auto-reconnecting. 

I do not think avideo is doing that, maybe it is your RTMP publisher, or maybe is your live server. 

I recommend you restart your live server and also your PC and network

**Comment by eitanwa** [comment]
Just to add that the broadcast is via the camera live broadcast
And not through external streaming software


![image](https://user-images.githubusercontent.com/85537931/202377626-9ea63ac4-634f-4b8a-9b98-95ea9794d810.png)

**Comment by DanielnetoDotCom** [comment]
you are not supposed to use this feature. this is still experimental.

**Comment by eitanwa** [comment]
tnx

**Comment by guymass** [comment]
OK thank I keep forgetting :-)
