### ISSUE TITLE
throwing below error after update-Please help!

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#7390]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/65802024/202394417-12f5774e-9749-4311-bbdf-fae1f9f1c6fd.png">

**Comment by DanielnetoDotCom** [comment]
did you update with git pull?

**Comment by vraghavans** [comment]
Hi Daniel,

Yes updated through git pull and updated to latest version

**Comment by DanielnetoDotCom** [comment]
what PHP version are you running?

**Comment by DanielnetoDotCom** [comment]
in the command line terminal type `php -v`

**Comment by DanielnetoDotCom** [comment]
try to update to php 8

php 7.4+ is required now

**Comment by vraghavans** [comment]
upgraded to version still same issue

**Comment by vraghavans** [comment]
![image](https://user-images.githubusercontent.com/65802024/202467022-56a6a295-01b0-4e60-a44e-de8edbb0f66e.png)

**Comment by DanielnetoDotCom** [comment]
I guess your apache still using the php7.2

but try this update. it may fix php 7.2 issue.

**Comment by vraghavans** [comment]
okies, how do i do that ,can you tell me please

**Comment by DanielnetoDotCom** [comment]
Just make a git pull

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by vraghavans** [comment]
yes fixed! thanks for your quick response and support as always!!! hope you have your succession planning.

What will i do without you?
