### ISSUE TITLE
Redirecting the ad to the site

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#7391]
The advertisement's reference to an external website (link)
(Works great on PC)
But does not work on the mobile web site
(not in the app)
When you click on the screen there is no response
Is it supposed to be like this or should it also work on mobile (web)?
Thanks
eitan live528

![image](https://user-images.githubusercontent.com/85537931/202413832-6601e017-ab8f-4fdf-a173-022ed13013e5.png)

**Comment by DanielnetoDotCom** [comment]
Yes, it is supposed to work, but for some reason, the Google IMA plugin still does not support it.

**Comment by eitanwa** [comment]
So I understand you are on it
Thanks, I'm closing the post
