### ISSUE TITLE
RSS link to channel page

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#7394]
An amazing feature for importing videos into a podcast catcher is the RSS feed on odysee. No other video platform offers it and it works great.
Can you add this?
![rss](https://user-images.githubusercontent.com/66537018/202606419-6eb0a208-2de2-471b-a268-e32fbce1cc0a.png)

**Comment by DanielnetoDotCom** [comment]
what exactly is that?

FYI you can add a /rss in almost all URLs

# Main page

https://demo.avideo.com/rss

# Channel 

https://demo.avideo.com/channel/HillsongUNITED/rss

# Playlist

![chrome-capture-2022-10-19](https://user-images.githubusercontent.com/18009293/202850160-73986ead-dba6-43fd-9c0b-e540492260aa.gif)

**Comment by fakeologist** [comment]
Oh amazing that's what I wanted.

Are there RSS links shown on the pages for users to easily see?

**Comment by DanielnetoDotCom** [comment]
If you mean the channel, currently we do not have a RSS button, but I may add a button for it in the future

**Comment by fakeologist** [comment]
An copy RSS url button would be great.

**Comment by DanielnetoDotCom** [comment]
I will send an update on next week

**Comment by fakeologist** [comment]
Fantastic everyone should look into RSS feeds and how they make reading and downloading so much easier for offline or later use.
