### ISSUE TITLE
Encoder not loading-Please help

### ISSUE THREAD

**Issue by vraghavans** [WWBN/AVideo#7396]
Good Day !,

Please note ,from yesterday iam trying to import a video from youtube,1st it was unable to import and now the encoder screen itself is not loading.

attached the last part of the log file.

Can you please advise.
[error.txt](https://github.com/WWBN/AVideo/files/10045227/error.txt)

**Comment by DanielnetoDotCom** [comment]
this log does not help

you MUST share the encoder log (NOT STREAMER) and only share the mommend you tried to import a video, NOT the whole thing

**Comment by vraghavans** [comment]
Dear Daniel,

Sorry for the wrong log.

PFA .the encoder screen just freezes after clicking the share button while importing video from youtube.
[Uploading error.txt…]()
.

**Comment by vraghavans** [comment]
pfa the error
[error.txt](https://github.com/WWBN/AVideo/files/10065555/error.txt)

**Comment by vraghavans** [comment]
can anyone help me on this please

**Comment by DanielnetoDotCom** [comment]
I can see this error in your log

`[21-Nov-2022 08:08:13 UTC] PHP Fatal error:  Uncaught Error: Class "mysqli" not found in /var/www/html/YouPHPTube/Encoder/objects/include_config.php:15`

you are missing php-mysqli lib, you may want to google for that

**Comment by vraghavans** [comment]
Dear Daniel,
i tried googling and tried some fixes, still not working.any specific directions i should look for please
Rgds
Vijay

**Comment by vraghavans** [comment]
home page crashed !

![image](https://user-images.githubusercontent.com/65802024/204123724-75d32f05-bd81-4acf-b505-140672a948bd.png)

**Comment by DanielnetoDotCom** [comment]
sorry I cannot teach it, but for sure you can find help on google

in my opinion, you should hire some one to help you with that.

**Comment by vraghavans** [comment]
hi Daniel,

who can help me on this please? not able to find a suitable solution

**Comment by DanielnetoDotCom** [comment]
you can hire me to make a clean installation for you, I only require the payment and a clean ubuntu server

**Comment by vraghavans** [comment]
tried installing php and was successful got the site to work.
now getting a new error

![image](https://user-images.githubusercontent.com/65802024/204695586-ca228c22-89c7-4e8e-af54-205b48f85e82.png)

any suggestions please

**Comment by DanielnetoDotCom** [comment]
I guess you have the wrong encoder version.

on the repository, the error line above is commented out

https://github.com/WWBN/AVideo-Encoder/blob/8bf0b43050dd5a4682028a74f0fe1f8410635923/objects/Encoder.php#L1088

**Comment by vraghavans** [comment]
Okies thanks! error fixed.

new one please-kindly advise

![image](https://user-images.githubusercontent.com/65802024/204818021-4831515d-e2b3-4a59-a9cd-c9696c071a2d.png)

**Comment by vraghavans** [comment]
what am doing is manually copying the files which are not there in my encoder.
Can you pls guide me on git clone please

**Comment by DanielnetoDotCom** [comment]
that is the basis for how to install

https://github.com/WWBN/AVideo-Encoder/wiki/How-to-install-LAMP,--FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x---For-AVideo-Encoder

**Comment by vraghavans** [comment]
Dear Daniel,

reinstalled ,same error again though
![image](https://user-images.githubusercontent.com/65802024/204918660-036ee9a2-9c3e-4936-8005-78b6ad880e93.png)

**Comment by DanielnetoDotCom** [comment]
the problem is not the installation, the problem is because you are NOT using git clone and git pull to get your files.

**Comment by vraghavans** [comment]
okies got it have done the git clone and i see that the scree itself has changed from the earlier one.however i have got a new error.please help

![image](https://user-images.githubusercontent.com/65802024/205426123-ae4ff400-49db-4cef-a391-34b079e3d88a.png)
this is the encoder screen how it looks
![image](https://user-images.githubusercontent.com/65802024/205426161-3acecf15-3e1b-41ed-ab8e-eb70cd67ee11.png)

**Comment by DanielnetoDotCom** [comment]
make sure your streamer is also up to date.

**Comment by DanielnetoDotCom** [comment]
also please try this update, it is not really a fix, but there are more checks to avoid fatal errors

**Comment by vraghavans** [comment]
Dear Daniel, 
updated and did a git pull

The error remains the same.
![image](https://user-images.githubusercontent.com/65802024/205440263-8e577402-5682-4ff5-abec-78052beabef1.png)

Could be advise link for git clone on streamer please
 rgds
Vijay

**Comment by DanielnetoDotCom** [comment]
instead of screenshot your error copy and paste more of it

**Comment by DanielnetoDotCom** [comment]
what type of server are you using? shared server? ubuntu? dedicated or VPS?

**Comment by DanielnetoDotCom** [comment]
I have checked 4 different servers with logs of over 1 year of records

I checked 4 different servers and I do not have this error on them, sorry I suspect I cannot help you

**Comment by vraghavans** [comment]
> what type of server are you using? shared server? ubuntu? dedicated or VPS?

Ubuntu dedicated server on hostinger

**Comment by DanielnetoDotCom** [comment]
How are you opening the logs if you are not using the terminal?

Also I went to host ginger and I did not see any dedicated server offer , can you please send a link of what server you are using?

**Comment by vraghavans** [comment]
for logs am using Winscp,and using terminal for git pull and clone.

![image](https://user-images.githubusercontent.com/65802024/205443805-6f64dddd-969c-4d80-877b-99ea83665df8.png)

**Comment by DanielnetoDotCom** [comment]
The image explains a lot

Your server is a VPS NOT a dedicated 

VPS is ok but you will have limited resources 

You are using Ubuntu 16 it is also OK but I recommend you to use Ubuntu 22.04

You are using webmin what is strongly NOT recommend, if you insist to use a control panel it is on your own risk

**Comment by DanielnetoDotCom** [comment]
Also, stay away from any type of control panel. otherwise, the errors are unpredictable.
