### ISSUE TITLE
LIVE TV IS NOT WORKING

### ISSUE THREAD

**Issue by Oceanithub** [WWBN/AVideo#7402]
Live TV is not working. Thumb nail shows he Live tv thumbnail and notificaion too. But video do not starts.
![Screenshot 2022-11-21 053918](https://user-images.githubusercontent.com/106688994/202932839-bb25cc4a-f36d-43c1-932d-eb107167bbf5.jpg)
![Screenshot 2022-11-21 053954](https://user-images.githubusercontent.com/106688994/202932842-0728eef9-6bfa-41bf-b03e-22d932209894.jpg)

**Comment by DanielnetoDotCom** [comment]
please try this update

**Comment by Oceanithub** [comment]
No Luck
![Screenshot 2022-11-21 064344](https://user-images.githubusercontent.com/106688994/202936838-d610aa04-2f01-4bd4-99db-b60c9e97a8c6.jpg)
![Screenshot 2022-11-21 064409](https://user-images.githubusercontent.com/106688994/202936842-c9b4ab98-a7f6-4215-9656-d970f76ddee9.jpg)

**Comment by DanielnetoDotCom** [comment]
seems to me you did not update correctly

make sure you use git pull

https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform

**Comment by Oceanithub** [comment]
livelinks are not showing content. but the thumbnail shows the image.
![Screenshot 2022-11-21 122009](https://user-images.githubusercontent.com/106688994/202979574-6a538806-181b-443a-9a96-cafb843e8c97.jpg)
![Screenshot 2022-11-21 122101](https://user-images.githubusercontent.com/106688994/202979582-064cfaaa-4963-4fe7-899b-6906b8332a69.jpg)

**Comment by Oceanithub** [comment]
no luck. no video play on livelink. always m3u8 small files download. but
no video

**Comment by DanielnetoDotCom** [comment]
what exactly link are you using?

**Comment by Oceanithub** [comment]
Now no issue or error...... But no video play...... I am using http:// m3u8
link........ And my address is https://

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/203060624-385c5d39-5c3b-4a47-b549-507a9b121eab.png)

https://github.com/WWBN/AVideo/issues/7402#issuecomment-1321953830

**Comment by Oceanithub** [comment]
http://45.127.56.3:9698/live/Corpus-POL/SRV4/1/SONY-AATH/video.m3u8

**Comment by DanielnetoDotCom** [comment]
#  you CANNOT USE HTTP on an HTTPS site

**Comment by Oceanithub** [comment]
then how to disable https?

**Comment by DanielnetoDotCom** [comment]
Strongly not recommended to do that. I recommend you find a link with HTTPS

if you insist to disable HTTPS you may google to do that, but I am pretty sure this is NOT a good idea.

**Comment by Oceanithub** [comment]
tried https link but no luck yet......

https://b1world.beritasatumedia.com/Beritasatu/B1World_manifest.m3u8

[image: image.png]

**Comment by DanielnetoDotCom** [comment]
I just tested it on the demo site and it is working fine

https://demo.avideo.com/liveLink/3/b1world-beritasatu-media

![image](https://user-images.githubusercontent.com/18009293/203076359-c7d44e0d-61ac-42e7-9e78-76612a36aea2.png)

**Comment by Oceanithub** [comment]
ok. so simple step by step video is available or not?

**Comment by DanielnetoDotCom** [comment]
I do not know what you are doing wrong. I do not know if the error is your steps, your PC, or your server installation. 

I could only check the feature is working properly and you can check on demo site

**Comment by Oceanithub** [comment]
Hi.

Finally
# I can run the https m3u8 link. (example:
https://live-hls-v3-aje.getaj.net/AJE-V3/index.m3u8 )
# But I can not run http m3u8 link. (example
http://45.127.56.3:9698/live/Corpus-POL/SRV4/1/SONY-AATH/video.m3u8 )

I did not install an ssl certificate on my VM machine. but yet no luck with
http link.

I follow this article to do it.
https://www.linuxbabe.com/ubuntu/install-avideo-youphptube-ubuntu-20-04-server

how to open or run http m3u8 link?

**Comment by Oceanithub** [comment]
whenever i want to play http m3u8 link this error shows:

AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Call to a member
function getLanguage() on null in
\/var\/www\/AVideo\/locale\/function.php:129\nStack trace:\n#0
\/var\/www\/AVideo\/objects\/include_config.php(164): setSiteLang()\n#1
\/var\/www\/AVideo\/videos\/configuration.php(47): require_once('...')\n#2
\/var\/www\/AVideo\/plugin\/LiveLinks\/proxy.php(4):
require_once('...')\n#3 {main}\n
 thrown","file":"\/var\/www\/AVideo\/locale\/function.php","line":129}
SCRIPT_NAME: /plugin/LiveLinks/proxy.php
