### ISSUE TITLE
Missing Category settings

### ISSUE THREAD

**Issue by dxbender** [WWBN/AVideo#7410]
**Describe the bug**
Category selection switch on video edit screen missing after move to youphptube server on doctorstalk.ch site

**To Reproduce**
All videos in backend video list.

**Expected behavior**
Return of category switches

**Error Logs**
Daniel:  You have access to the backend of the server.  I don't.

**Screenshots**
![Missing Categories](https://user-images.githubusercontent.com/118817025/203306614-7a82ec91-6bb2-4482-968f-da91a4221b79.jpg)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox
 - Version Latest

**Smartphone (please complete the following information):**

**Additional context**
I think this is a remnant of the move to your server.

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/203547428-0c3c5651-84c1-46b0-9487-09727a3f8cf0.png)

1. this has nothing to do with category, this is for the Playlist plugin
2. this space is required because the buttons on the right side
