### ISSUE TITLE
Overrun with bots

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7411]
**Describe the question**
I know my site is overrun with bots because videos are being bombarded with "users" that watch them at 2x speed in a loop. Even private videos. 

Overnight, a video has 1000 views, and like 950 of them look like they are coming from probably the same IP address all within the same two hours period...

**Screenshots**
![Screen Shot 2022-11-22 at 4 05 56 PM](https://user-images.githubusercontent.com/11711050/203445469-df30a0c1-2055-441f-b5b2-51fb0207984a.png)

3 users cannot watch 2 hours of videos for 8.4 days. That is not "legit". Sure there was a computer there. Yes those bits traveled to their destination. Sure a player played those bits. But they should not count.

More. Two bots racked up 4 days of view time. This is not legit.

![Screen Shot 2022-11-22 at 4 10 26 PM](https://user-images.githubusercontent.com/11711050/203445866-1cba5336-2a64-45cf-a355-17c0a10843b5.png)

Anyway, this is more rhetorical than anything else. Though I wish we had some switch we could toggle to turn on an algorithm to filter/discard these, like YouTube and other sites do, because advertisers and stuff…

Anyone else getting these crazy bot swarms on their site? Any ideas why other than bored people with too many computers?

**Comment by Maikuolan** [comment]
Curious about that affecting private videos. If a video is private, shouldn't bots not be able to find the video in the first place? I wonder whether either (A) the private videos can still somehow be accessed publicly (e.g., by bots), or (B) something else going on, maybe stats not being calculated correctly, or something similar.

**Comment by DanielnetoDotCom** [comment]
can you detect those bots on your access.log?

**Comment by walt93** [comment]
Daniel we don't even need to drill down to access.log. Common sense tells us that you don't have 100 hits to the video in the same minute from the same city. Those would be distributed to different cities, different states, different countries if that were a natural pattern. Adjacent videos to this get 6 views in a week. This is the pattern. Bot swarm selects video, works on video for a couple of days, bot swarm moves on.

![Screen Shot 2022-11-23 at 1 02 39 PM](https://user-images.githubusercontent.com/11711050/203645530-0ad8fc68-45c1-4a92-b689-0ba7f684572b.png)

But let's drill down and see who this "United States, Dallas, Texas" is…

Hmm... "HeadlessChrome" is the browser. Weird way to surf the net.  Damn millennials... 🤣

There's a <expletive deleted> TON of these. 🤖🤖🤖

Hey Daniel, I've got a pretty easy fix for your bot logging problem if you're parsing access.log…
```
 NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75"
40.77.139.20 - - [23/Nov/2022:12:46:37 -0800] "GET /node_modules/video.js/dist/video.min.js HTTP/1.1" 200 164470 "https://conspyre.tv/sw.js?0.03189029204702609" "Mozilla/5.0
 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75"
40.77.139.20 - - [23/Nov/2022:12:46:37 -0800] "GET /plugin/PlayerSkins/player.css HTTP/1.1" 200 909 "https://conspyre.tv/sw.js?0.03189029204702609" "Mozilla/5.0 (Windows NT
6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75"
40.77.139.20 - - [23/Nov/2022:12:46:37 -0800] "GET /plugin/VideoResolutionSwitcher/videojs-resolution-switcher.css HTTP/1.1" 200 1171 "https://conspyre.tv/sw.js?0.0318902920
4702609" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75"
40.77.139.20 - - [23/Nov/2022:12:46:37 -0800] "GET /plugin/VideoResolutionSwitcher/videojs-resolution-switcher-v7/videojs-resolution-switcher-v7.js HTTP/1.1" 200 4408 "https
://conspyre.tv/sw.js?0.03189029204702609" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.141 Safari/537.36 Edg/87.
0.664.75"
40.77.139.20 - - [23/Nov/2022:12:46:37 -0800] "GET /plugin/VideoResolutionSwitcher/script.js HTTP/1.1" 200 1453 "https://conspyre.tv/sw.js?0.03189029204702609" "Mozilla/5.0
(Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75"
40.77.139.20 - - [23/Nov/2022:12:46:37 -0800] "GET /plugin/PlayerSkins/skins/avideo.css HTTP/1.1" 200 2041 "https://conspyre.tv/sw.js?0.03189029204702609" "Mozilla/5.0 (Wind
ows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75"
87.250.224.16 - - [23/Nov/2022:12:46:37 -0800] "GET /robots.txt HTTP/1.1" 200 2210 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
40.77.139.20 - - [23/Nov/2022:12:46:37 -0800] "GET /plugin/PlayerSkins/player.js HTTP/1.1" 200 872 "https://conspyre.tv/sw.js?0.03189029204702609" "Mozilla/5.0 (Windows NT 6
.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75"
40.77.139.20 - - [23/Nov/2022:12:46:37 -0800] "GET /plugin/PlayerSkins/shareButton.css HTTP/1.1" 200 662 "https://conspyre.tv/sw.js?0.03189029204702609" "Mozilla/5.0 (Window
s NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75"
40.77.139.20 - - [23/Nov/2022:12:46:37 -0800] "GET /plugin/VideoOffline/offlineVideo.css HTTP/1.1" 500 823 "https://conspyre.tv/sw.js?0.03189029204702609" "Mozilla/5.0 (Wind
ows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75"
40.77.139.20 - - [23/Nov/2022:12:46:37 -0800] "GET /plugin/PlayerSkins/autoplayButton.css HTTP/1.1" 200 679 "https://conspyre.tv/sw.js?0.03189029204702609" "Mozilla/5.0 (Win
dows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75"
40.77.139.20 - - [23/Nov/2022:12:46:37 -0800] "GET /plugin/VideoOffline/offlineVideo.js HTTP/1.1" 500 823 "https://conspyre.tv/sw.js?0.03189029204702609" "Mozilla/5.0 (Windo
ws NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75"
207.46.13.77 - - [23/Nov/2022:12:46:37 -0800] "GET /video/11130/s-election-code-2022?yptDeviceID=55af0e5e-c0e4-4cd8-855d-bbb470fa0a35&page=1 HTTP/1.1" 200 37611 "-" "Mozilla
```

**Comment by walt93** [comment]
There's all sorts of indicators that the traffic is unnatural too, just this is telling. I uploaded this video like 12 hours ago. There simply are not this many users on the site.

This reminds me, there is another issue with view count logging with embeds. I have a user that powers his blog with embeds from my site. When they were testing embeds, they picked some obscure video and embedded it. During their week of testing they racked up over 4,000 views. There is absolutely no way they generated more than say 50 of those views, there was one web developer and one person helping test. Something weird happens with the embed path where <unknown user action> generates <many> views (we don't know what, have not characterized).

Seems that something like that is going on with these bots?

![Screen Shot 2022-11-23 at 1 11 07 PM](https://user-images.githubusercontent.com/11711050/203646768-9cb03906-b1e7-46df-a110-26f1282c5693.png)

**Comment by DanielnetoDotCom** [comment]
Hi, 

yes, embedding may be a problem with videos count.

but I want to see the log so I can try to find out what bot may it be and also I may find a way to block it.

**Comment by walt93** [comment]
Look at the log above. If we can filter on browser type and block HeadlessChrome we can knock out the 🤖 🤖 🤖

**Comment by DanielnetoDotCom** [comment]
I am not 100% but I think you are right, and HeadlessChrome is a bot.

try this

# 1. add this in your configuration.php

`$global['stopBotsList'] = array('bot','spider','rouwler','Nuclei','MegaIndex','NetSystemsResearch','CensysInspect','slurp','crawler','curl','fetch','loader');`

# 2. to make sure you will not block all the bots also add this

`$global['stopBotsWhiteList'] = array('curl','google','bing','yahoo','yandex','Googlebot');`

**Comment by walt93** [comment]
Ok I've added. Is there anything else to do, or just check over time and see if there are less recorded activities by bots?

HeadlessChrome is used by a lot of QA teams for automated testing. Which makes it a great platform for coding bots. 🤖
