### ISSUE TITLE
A problem installing on a vps

### ISSUE THREAD

**Issue by kollhall** [WWBN/AVideo#7416]
I was trying to install AVideo on a vps, and followed the tutorial available on github. When going to IP/AVideo the system alerted to modify some permissions. I followed the request, but an error occurs, that instead of loading the html to install, it returns the code that generates the page and I cannot install the system

![erro](https://user-images.githubusercontent.com/88242096/203667407-ef1ccdc3-1da3-4e60-a85b-d4a853b04605.png)

**Comment by DanielnetoDotCom** [comment]
your apache/php is not properly installed
