### ISSUE TITLE
ReWrite Rules

### ISSUE THREAD

**Issue by lunar54** [WWBN/AVideo#7417]
What should the correct output look like  for curl -I http://example.com/plugin/Live/on_publish.php 
HTTP/1.1 401 Unauthorized Error
?
?
?
?

also since lets encrypt is adding rewrite rules should rules be applied to all files below to not enforce https ?

on_publish            http://example.com/plugin/Live/on_publish.php;
on_publish_done   http://example.com/plugin/Live/on_publish_done.php;
on_play                 http://example.com/plugin/Live/on_play.php;
on_record_done    http://example.com/plugin/Live/on_record_done.php;

**Comment by DanielnetoDotCom** [comment]
401 is what we expect.

you need to setup your site in another domain (or IP) to NOT use HTTPS

**Comment by lunar54** [comment]
Yes I understand HTTP/1.1 401 Unauthorized Error is correct output but that is not the only output you get so what should the full correct output look like ?

if you are thinking i am using example.com as a domain then you are mistaken example is exactly that an example.
nginx conf is set to use stats behind a domain not as a sub domain so using another domain would not work

lets encrypt adds rules in apache conf so by adding rules to not force https to on_ parameters as you said in this post

_Originally posted by @DanielnetoDotCom in https://github.com/WWBN/AVideo/issues/4880#issuecomment-814438694_
