### ISSUE TITLE
Bootstrap Editor

### ISSUE THREAD

**Issue by lunar54** [WWBN/AVideo#7419]
Can any recommend a Bootstrap Editor and What is Current Bootstrap Version being used ?

**Comment by DanielnetoDotCom** [comment]
We are using Bootstrap version 3

**Comment by lunar54** [comment]
Thanks ya seen that in file not sure why i dint look at it before 3.4.1. 
Any Editors to recommend ?

**Comment by walt93** [comment]
Was using IntelliJ IDEA, recommend trying the 60 day free trial of GitHub Co-pilot. It's wild. Context aware AI autocomplete for code.
