### ISSUE TITLE
Encoder Broke after last Core update videos not transferring anymore

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7421]
Nothing is transfering to backblaze anymore

I updated everything even the encoders and now no longer transfers 

![download (8)](https://user-images.githubusercontent.com/39392449/204098297-0de8c2b8-dbf5-46e2-bed0-0d1db50e91dd.png)

**Comment by DanielnetoDotCom** [comment]
The streamer is the one who transfer the files , check the streamer logs for clues

**Comment by JoshWho** [comment]
Im just waking up and trying to make sense of it.

**Comment by JoshWho** [comment]
` [26-Nov-2022 10:15:57 America/Chicago] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: Return value of BackblazeB2\\File::jsonSerialize() must be an instance of BackblazeB2\\mixed, array returned in \/var\/www\/html\/YouPHPTube\/vendor\/gliterd\/backblaze-b2\/src\/File.php:57\nStack trace:\n#0 [internal function]: BackblazeB2\\File->jsonSerialize()\n#1 \/var\/www\/html\/YouPHPTube\/plugin\/Blackblaze_B2\/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(397): json_encode()\n#2 \/var\/www\/html\/YouPHPTube\/plugin\/Blackblaze_B2\/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(314): Blackblaze_B2->copy_to_B2()\n#3 \/var\/www\/html\/YouPHPTube\/objects\/functions.php(2182): Blackblaze_B2->move_uploaded_file()\n#4 \/var\/www\/html\/YouPHPTube\/objects\/aVideoEncoder.json.php(152): decideMoveUploadedToVideos()\n#5 {main}\n  thrown","file":"\/var\/www\/html\/YouPHPTube\/vendor\/gliterd\/backblaze-b2\/src\/File.php","line":57} SCRIPT_NAME: /objects/aVideoEncoder.json.php`

**Comment by JoshWho** [comment]
`[26-Nov-2022 10:16:19 America/Chicago] AVideoLog::SECURITY: NGINX ON Publish denied {"error":true,"liveTransmitionHistory_id":0} SCRIPT_NAME: /YouPHPTube/plugin/Live/on_publish.php`

**Comment by DanielnetoDotCom** [comment]
That error is something and I cannot check it directly now

Did you update something recently?

If you did , did you update streamer and plugins?

**Comment by JoshWho** [comment]
Yes last night  updated the streamer and the encoders before I went top sleep

**Comment by DanielnetoDotCom** [comment]
Check if there is any update on the plugin 

Maybe the backblaze api lib update something

**Comment by JoshWho** [comment]
Currently it is using Blackblaze_B2 (Blackblaze_B2)
  Version: @3.3 I do not see any update

**Comment by JoshWho** [comment]
This is the test outcome

```
7.4.33

getClient
keyId=0fc7432a82de applicationKey=0024df30140dfdeb810de7c74151fa41441416ed73 $B2ClientFail=null $try=1
array(4) { ["type"]=> int(1) ["message"]=> string(703) "Uncaught TypeError: Return value of BackblazeB2\File::jsonSerialize() must be an instance of BackblazeB2\mixed, array returned in /var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/File.php:57 Stack trace: #0 [internal function]: BackblazeB2\File->jsonSerialize() #1 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(397): json_encode() #2 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/test.php(18) : eval()'d code(1) : eval()'d code(14): Blackblaze_B2->copy_to_B2() #3 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/test.php(18) : eval()'d code(1): eval() #4 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/test.php(18): eval() #5 {main} thrown" ["file"]=> string(65) "/var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/File.php" ["line"]=> int(57) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(703) "Uncaught TypeError: Return value of BackblazeB2\File::jsonSerialize() must be an instance of BackblazeB2\mixed, array returned in /var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/File.php:57
Stack trace:
#0 [internal function]: BackblazeB2\File->jsonSerialize()
#1 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/Blackblaze_B2.php(18) : eval()'d code(1) : eval()'d code(397): json_encode()
#2 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/test.php(18) : eval()'d code(1) : eval()'d code(14): Blackblaze_B2->copy_to_B2()
#3 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/test.php(18) : eval()'d code(1): eval()
#4 /var/www/html/YouPHPTube/plugin/Blackblaze_B2/test.php(18): eval()
#5 {main}
  thrown"
  ["file"]=>
  string(65) "/var/www/html/YouPHPTube/vendor/gliterd/backblaze-b2/src/File.php"
  ["line"]=>
  int(57)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avideoShutdown"
    ["args"]=>
    array(0) {
    }
  }
}
```

**Comment by DanielnetoDotCom** [comment]
I will check it later when I get back to the office, I suggest you to disable uploads now, backblaze may not work

**Comment by JoshWho** [comment]
> I will check it later when I get back to the office, I suggest you to disable uploads now, backblaze may not work

I have a note up telling users not to use it for now

**Comment by DanielnetoDotCom** [comment]
I just found something weird, i am not sure if it is something from backblaze or in php

Try to download the backblaze plugin version 3.4 and test again

**Comment by JoshWho** [comment]
That might have done the tick I will test a upload. So far the backblaze test looks good now.

**Comment by JoshWho** [comment]
All Fixed after updating the plugin. Thank you @DanielnetoDotCom
