### ISSUE TITLE
Video old Embed Code nolonger working

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7422]
This is the video embed link https://www.joshwhotv.com/vEmbed/.Q2E9wQ

Working video link is https://www.joshwhotv.com/v/.7C76KQ not sure what happened

Seems like the video ID some how changed

**Comment by JoshWho** [comment]
Seems like everything is working it is just some videos that this happened to. Not really too sure what to think

**Comment by JoshWho** [comment]
Yup it is all the old embed links 

![918839ae-b41e-4ef5-b59c-068d1e6b0914](https://user-images.githubusercontent.com/39392449/204108279-69b7634c-a099-4141-a58d-1445d32bd247.png)

**Comment by JoshWho** [comment]
@DanielnetoDotCom did u see this?

**Comment by DanielnetoDotCom** [comment]
please try this update

**Comment by JoshWho** [comment]
I did not see a change after doing the git pull. It wont let me purge the cache

**Comment by JoshWho** [comment]
After I ran the git pull I click the Purge Cache and it just hangs never completes

**Comment by JoshWho** [comment]
Embed video still shows 403

![4d96a346-b530-4631-ba4f-f516838e0957](https://user-images.githubusercontent.com/39392449/204288031-e98c3cb6-53fd-48a5-8461-b335bce1fab1.png)

**Comment by DanielnetoDotCom** [comment]
try to manually delete the videos/cache folder (BE CAREFUL TO NOT DELETE THE VIDEOS FOLDER)

then try again and check the avideo.log

**Comment by JoshWho** [comment]
I think the cache is purged it just never fixed the embed

**Comment by DanielnetoDotCom** [comment]
Did you change the salt or something?

it works on my side, but definitely is not on your site

what video id does it suppose to load?

**Comment by JoshWho** [comment]
I do not even know where you would change that. this is the old embed https://www.joshwhotv.com/vEmbed/.Q2E9wQ
Here is what it says it is now https://www.joshwhotv.com/v/.7C76KQ

**Comment by DanielnetoDotCom** [comment]
I may have an idea of what is happening...

on the new PHP versions if you do not pass the correct keylen and iv it crashes.

so I need to update it here https://github.com/WWBN/AVideo/commit/90d26d926c99e2d1c273c4f38d4490468660e07d

for now, I added a fallback function in case the new one fails, but I recommend you update your embed codes because in the future when you upgrade PHP this may fail.

**Comment by JoshWho** [comment]
Thank you that did it. I hopefully will not have to update php anymore. It is working good again now thank you @DanielnetoDotCom
