### ISSUE TITLE
Weird text in password recovery

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7423]
@DanielnetoDotCom I checked the login recovery popup text is weird as it asks a question: "Are you sure?". 
I don't see this type of user questioning as a platform standard. I think that the system should not doubt the user.

$t['Are you sure?'] = 'Você tem certeza?';
![image](https://user-images.githubusercontent.com/37880073/204108442-1a35a827-fc64-443c-af3e-997ce0de9c7f.png)

Netflix:
![image](https://user-images.githubusercontent.com/37880073/204108610-9a4e9938-33ff-4560-bafe-68e3277a9778.png)

Amazon Prime
![image](https://user-images.githubusercontent.com/37880073/204108763-92988dcf-aaa1-4819-90f9-3dfa7b449a8e.png)

I know the change has to be made in several languages, but it's something to think about...

This is a low priority question, but for the end user I think it looks weird.

**Comment by DanielnetoDotCom** [comment]
You are right, it now says "I forgot my password"
