### ISSUE TITLE
Strange crash on video page

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7425]
**Describe the bug**
This page is failing to load:

https://conspyre.tv/video/9840/satanic-ritual-abuse-sra---from-the-deep-state-war-4---satanic-abuse---a-film-by-mrtruthbomb

**To Reproduce**

**Expected behavior**
To see the video's page.

**Error Logs**
As printed to the web page itself:

`int(1) ["message"]=> string(463) "Uncaught Error: Cannot use object of type Video as array in /var/www/html/AVideo/plugin/PlayerSkins/contextMenu.php:131 Stack trace: #0 /var/www/html/AVideo/view/include/video.php(10): include() #1 /var/www/html/AVideo/view/modeYoutubeTop.php(25): require('/var/www/html/A...') #2 /var/www/html/AVideo/view/modeYoutubeBundle.php(37): require('/var/www/html/A...') #3 /var/www/html/AVideo/view/modeYoutube.php(377): require('/var/www/html/A...') #4 {main} thrown" ["file"]=> string(55) "/var/www/html/AVideo/plugin/PlayerSkins/contextMenu.php" ["line"]=> int(131) }

array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(463) "Uncaught Error: Cannot use object of type Video as array in /var/www/html/AVideo/plugin/PlayerSkins/contextMenu.php:131
Stack trace:
#0 /var/www/html/AVideo/view/include/video.php(10): include()
#1 /var/www/html/AVideo/view/modeYoutubeTop.php(25): require('/var/www/html/A...')
#2 /var/www/html/AVideo/view/modeYoutubeBundle.php(37): require('/var/www/html/A...')
#3 /var/www/html/AVideo/view/modeYoutube.php(377): require('/var/www/html/A...')
#4 {main}
  thrown"
  ["file"]=>
  string(55) "/var/www/html/AVideo/plugin/PlayerSkins/contextMenu.php"
  ["line"]=>
  int(131)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avideoShutdown"
    ["args"]=>
    array(0) {
    }
  }
}
`
**Screenshots**
![Screen Shot 2022-11-26 at 4 48 25 PM](https://user-images.githubusercontent.com/11711050/204114294-90e3f925-3db9-43b0-ad12-6ffbdcbba56b.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure how this happen, but please try this update

**Comment by walt93** [comment]
Did a git pull, did a clear first page/cache directory/build sitemap, and the error appears to have moved from contextMenu.php to modeYoutubeBundle.php.
![Screen Shot 2022-11-28 at 4 54 58 PM](https://user-images.githubusercontent.com/11711050/204411825-6216c77c-363c-4b50-a03a-426ce0e2d2a1.png)

**Comment by DanielnetoDotCom** [comment]
Did you recently update?

I remember to fix that a couple days ago

**Comment by DanielnetoDotCom** [comment]
Anyway, I am sending updates now

**Comment by walt93** [comment]
I did a git pull, the full clear first page cache/cache directory/rebuild sitemap, loaded the page, and the error seems to have moved from modeYoutubeBottom.php to modeYoutubeBundle.php:
![Screen Shot 2022-12-06 at 2 16 01 PM](https://user-images.githubusercontent.com/11711050/206035194-566685bb-79c9-41af-8104-c1334a8b3434.png)

```
array(4) { ["type"]=> int(1) ["message"]=> string(203) "Uncaught Error: Cannot use object of type Video as array in /var/www/html/AVideo/view/modeYoutubeBundle.php:26 Stack trace: #0 /var/www/html/AVideo/view/modeYoutube.php(377): require() #1 {main} thrown" ["file"]=> string(47) "/var/www/html/AVideo/view/modeYoutubeBundle.php" ["line"]=> int(26) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(203) "Uncaught Error: Cannot use object of type Video as array in /var/www/html/AVideo/view/modeYoutubeBundle.php:26
Stack trace:
#0 /var/www/html/AVideo/view/modeYoutube.php(377): require()
#1 {main}
  thrown"
  ["file"]=>
  string(47) "/var/www/html/AVideo/view/modeYoutubeBundle.php"
  ["line"]=>
  int(26)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avideoShutdown"
    ["args"]=>
    array(0) {
    }
  }
}
```

**Comment by DanielnetoDotCom** [comment]
can you please check if this update makes any difference?
