### ISSUE TITLE
I want to edit the language of http://URL/upload/

### ISSUE THREAD

**Issue by hogehoge55** [WWBN/AVideo#7426]
Hello, I'm a new member of the forum and I'm looking for a new member of the forum.
I would like to translate the following URL into Japanese: http://URL/upload/

There was no language in ja_JP.php.
en_US.php also had no language.

Where should I refer to?

Thank you very much.

**Comment by Maikuolan** [comment]
> There was no language in ja_JP.php.
> en_US.php also had no language.

You mean, the files don't exist? Or something else? If the files: Maybe something went wrong at your installation? The files exist at the repository here.

https://github.com/WWBN/AVideo/blob/master/locale/en_US.php
https://github.com/WWBN/AVideo/blob/master/locale/ja_JP.php

**Comment by hogehoge55** [comment]
As an example, the term "Sharing Queue" is not mentioned in ja_JP.php.
![2022-11-27_23h12_04](https://user-images.githubusercontent.com/13326673/204139832-001c8d51-7197-4783-8be3-5ea84e51f444.png)

**Comment by DanielnetoDotCom** [comment]
Hi

currently, we do not have a translation for the encoder. we may add it in the future

**Comment by DanielnetoDotCom** [comment]
Not a good idea, you will loose your changes on the next update

**Comment by hogehoge55** [comment]
So what should we do?
What is the best way?

**Comment by DanielnetoDotCom** [comment]
currently, there is no good way.

to let you add some translation we need to change the encoder code.

we will do it in the future, but we do not have plans to do it now;

**Comment by hogehoge55** [comment]
Understood.
Is the update automatic?
Can I choose to do so at my discretion?

**Comment by walt93** [comment]
Updates are done when you do a git pull. There is no auto-update.

For workflow, you can make your own fork of the repository and work from that.

A lazy way is to do a
   git stash
   git pull
   git stash pop

First step saves your locally modified files away safely. Second step pulls the latest code update from the git repository. Third step restores your locally modified files.
