### ISSUE TITLE
Inconsistencies texts and translations password recovery

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7427]
@DanielnetoDotCom I checked some inconsistencies with texts and translations of the password recovery process:

**01 - ISSUE:**
`
Erro
The user is not active
`

![image](https://user-images.githubusercontent.com/37880073/204182673-5d18687f-739e-40d0-8c33-678dfd9c7cd4.png)

I checked that the translation exists in the translation file, but it is not displayed correctly:
$t['The user is not active'] = 'O usuário não está ativo';

**02 - ISSUE:**

`Recover Pass from...`

![image](https://user-images.githubusercontent.com/37880073/204183863-a3ce7d9f-8c3c-4e3a-980b-011f20ce06dd.png)

I couldn't find the translation in `/locale/`
https://github.com/WWBN/AVideo/blob/master/locale/pt_BR.php

I verified that it is only in: [objects/userRecoverPass.php]

How can I correct that?

**Comment by gbrn** [comment]
Complementing...
Also does not display the translation:

$t['Please verify your email address'] = 'por favor verifique seu endereço de email';

![image](https://user-images.githubusercontent.com/37880073/204191903-da1fd2b5-38fd-494e-841b-c43492c23bf3.png)

**Comment by gbrn** [comment]
Mais alguns problemas com a exibição de tradução:

`$t['Save Profile Photo'] = 'Salvar foto do perfil';`
![image](https://user-images.githubusercontent.com/37880073/204928986-b8396fb1-b842-46ac-83b3-787e9a66ea76.png)

![image](https://user-images.githubusercontent.com/37880073/204929353-8d2f6c69-02bc-42e1-bc90-09df00ddd211.png)

**Comment by DanielnetoDotCom** [comment]
I just double checked all is already translated

![image](https://user-images.githubusercontent.com/18009293/205183060-bd791d82-9329-4ec9-bdc4-df8c72326376.png)

**Comment by gbrn** [comment]
> **02 - ISSUE:**
> 
> `Recover Pass from...`
> 
> ![image](https://user-images.githubusercontent.com/37880073/204183863-a3ce7d9f-8c3c-4e3a-980b-011f20ce06dd.png)
> 
> I couldn't find the translation in `/locale/` https://github.com/WWBN/AVideo/blob/master/locale/pt_BR.php
> 
> I verified that it is only in: [objects/userRecoverPass.php]
> 
> How can I correct that?


@DanielnetoDotCom This problem still exists... How do you correct this translation of the email that is sent?
