### ISSUE TITLE
Adjust Warning Screen

### ISSUE THREAD

**Issue by smaku14** [WWBN/AVideo#7433]
Is there a way to customize the warning and image that displays when a video is not found? If so, where can I make this adjustment?

![warning_video](https://user-images.githubusercontent.com/115157749/204321076-69d828a2-c8a8-4532-a0b4-61adab77d40a.png)

**Comment by gbrn** [comment]
@smaku14 I have been waiting for these changes for over a year.
Confira: https://github.com/WWBN/AVideo/issues/5870
No changes expected...
something for us to say @DanielnetoDotCom ? An alternative way?

**Comment by DanielnetoDotCom** [comment]
Nothing yet
