### ISSUE TITLE
Hiding Category under Video Player

### ISSUE THREAD

**Issue by smaku14** [WWBN/AVideo#7437]
Is there a way to hide the category which is shown underneath each video?

![Category_Video](https://user-images.githubusercontent.com/115157749/204468278-7a9f0028-6a7a-4f87-af7d-eef47acc65a9.png)

**Comment by DanielnetoDotCom** [comment]
If you know CSS you can add a custom CSS to hide it 

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript
