### ISSUE TITLE
Login screen, not possible to identify, no information, logo is not displayed

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7439]
@DanielnetoDotCom I've been trying to organize my project to increase its visibility. That's why I've seen several graphical, text and user usability problems. 
I know that this is normal during system development, and that changes make it more robust. I support it.

On the login screen, it is not possible to identify which site is being accessed. It has no information. The website logo is not displayed, why?

![image](https://user-images.githubusercontent.com/37880073/204641622-d029f1aa-edec-4c0a-af97-148bd7e15e33.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure what options you selected, but by default the navbar is present.

you probably removed that checking some option

**Comment by gbrn** [comment]
I only found these options to change. I did the tests but it didn't work.

Any other settings I should look out for?

![image](https://user-images.githubusercontent.com/37880073/204675315-9d13d4e1-d3a0-4f55-9c2f-4816fa949248.png)

**Comment by gbrn** [comment]
@DanielnetoDotCom I couldn't find where to enable or disable this top bar. Could you tell me where it is?
