### ISSUE TITLE
Password recovery: Update code button not work

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7441]
@DanielnetoDotCom In the password recovery popup, the green update code button does not work.
Click and does not update.
If you close and open the popup, the code updates correctly. But clicking the green button doesn't work.

![image](https://user-images.githubusercontent.com/37880073/204673034-6ecd0bae-53aa-4568-ac53-df8314d21be0.png)

**Comment by DanielnetoDotCom** [comment]
I will send an update tomorrow regarding it
