### ISSUE TITLE
Error with OG tags for a video's page

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7444]
**Describe the bug**
Posting a link to social media for a video's page, we get open graph tags that have neither title nor description.

**To Reproduce**
Post a link to https://conspyre.tv/v/6208

Observe the open graph tags have no title and have no description.

![IMG_92E394133A7E-1](https://user-images.githubusercontent.com/11711050/205161190-b625b1b8-7593-4fc2-b939-58ff789f7bef.jpeg)

**Comment by DanielnetoDotCom** [comment]
The description is there, I am not sure why it did not show

![image](https://user-images.githubusercontent.com/18009293/205186544-a2591ed7-9320-4578-b82d-a37aa663d767.png)

**Comment by walt93** [comment]
I know that 1) You are correct and 2) Twitter doesn't like the tags, there is something else causing it to trip…

Check it here. I remember implementing OG tags on my website. It was much more frustrating than it should have been because Twitter is a fussy little b***ch.

https://cards-dev.twitter.com/validator

**Comment by DanielnetoDotCom** [comment]
try to disable the twitter_player

![image](https://user-images.githubusercontent.com/18009293/205375587-27d947bd-88f7-4fdc-9593-4d46d608aff4.png)


If does not work try to check twitter_summary_large_image
