### ISSUE TITLE
Live Stream and Meat error

### ISSUE THREAD

**Issue by krsamue101** [WWBN/AVideo#7447]
I'm trying to start live stream but i get this error. Even tried reinstalling AVideo 2 times.

https://user-images.githubusercontent.com/105032235/205323103-cdbeb81b-ef87-41c7-ada8-8186fd6f2bc6.mp4

**Comment by DanielnetoDotCom** [comment]
I cannot tell you what is wrong but looks like you have a lot of errors in your installation.

make sure you have a valid SSL installed

**Comment by krsamue101** [comment]
My site doesn't use ssl. Is it necessary?

**Comment by DanielnetoDotCom** [comment]
For a meeting yes, this is required 

For livestream I suspect you did not install it properly

**Comment by krsamue101** [comment]
thanks you for reply, and I installed SSL on it. But it site doesn't load properly [https://github.com/WWBN/AVideo/issues/7449](url)
