### ISSUE TITLE
Ridiculous-sized profile pics on comments sections

### ISSUE THREAD

**Issue by Broly5551** [WWBN/AVideo#7448]
When I updated my Avideo site a couple months ago, a bug occurred where the profile pics on people's comments quadrupled in size or worse when my browser's zoom level is set to 100 percent.  JoshWho TV, which also uses AVideo and has up-to-date components as well as an up-to-date core script, doesn't have this problem when the browser zoom level is set to 100 percent.

![Corder Comments Section Problem 1](https://user-images.githubusercontent.com/45298486/205395439-51f27859-cbfd-4d38-85f4-f3eea537b74b.png)

![Corder Comments Section Problem 2](https://user-images.githubusercontent.com/45298486/205396636-e89141e2-0ab2-4daf-bf57-c4a63d45c483.png)

![JoshWho TV Comments Section 1](https://user-images.githubusercontent.com/45298486/205396849-658404d0-a9fa-40ef-b14f-90979e2837fc.png)

The comments can be seen in their entirety when I turn the browser zoom level to 80 percent or below, but users shouldn't have to turn the browser zoom level to below 100 percent in order to see comments in their entirety.

How can I fix this problem?

**Comment by DanielnetoDotCom** [comment]
Make sure you clear your cache and update it properly

I just tested my sites and all seems to be fine 

![image](https://user-images.githubusercontent.com/18009293/205399184-57bdbf05-9ebe-47d5-867f-b2353fb56901.png)

https://tutorials.avideo.com/video/78/welcome-to-avideo-platform

**Comment by Broly5551** [comment]
> Make sure you clear your cache and update it properly
> 
> I just tested my sites and all seems to be fine
> 
> ![image](https://user-images.githubusercontent.com/18009293/205399184-57bdbf05-9ebe-47d5-867f-b2353fb56901.png)
> 
> https://tutorials.avideo.com/video/78/welcome-to-avideo-platform

I have been clearing my cache (including last night), I have my site updated to the latest version of AVideo, and all my plugins are up to date.  Everything should be working fine like it is for you, but it's not for me.

Since this is the case, what should I look at next as a possible place to fix?

**Comment by DanielnetoDotCom** [comment]
I am not sure where you can look, but looks like you have a cached or missed css file

**Comment by Broly5551** [comment]
> I am not sure where you can look, but looks like you have a cached or missed css file

We went into the code of the comments, and we were unable to discover any CSS element that we could adjust.  The following code is what we saw:


<div class="animate__animated animate__flipInX media isNotAResponse userCanAdminComment userCanEditComment myVote0 isNotPinned isNotResponse" id="comment_306">
<div class="media-left">
<img src="https://corder.joshwho-cdn.com/videos/userPhoto/photo39.png?cache=1657056920_1657056920" class="media-object">
</div>
<div class="media-body">
<h3 class="media-heading hideIfHasVideosId">
<a href="https://corder.tv/video/713/world-class-loser-pig-man-of-the-outback?channelName=VJAYENTERTAINMENTNEWS" class="keychainify-checked"><i class="fas fa-video"></i> WORLD CLASS LOSER PIG MAN OF THE OUTBACK</a>
</h3>
<h4 class="media-heading">
<a href="https://corder.tv/channel/VJAYENTERTAINMENTNEWS" class="keychainify-checked"><i class="fas fa-user"></i> vjaytv</a>
<small><i>3 months</i></small>
<i class="fas fa-thumbtack pull-right hideIfIsUnpinned" onclick="pinComment(306);" style="cursor: pointer;"></i>
</h4>
<p>FREEDOM OF SPEECH IN THE REAL WORLD DOES NOT MEAN FREEDOM TO HARRASS, NAME CALLING AND SPAMMING ALL THE COMMENT BOARDS. CHUCKLES IS A COWARD . AND DESERVES TO BE MOCKED AND SHAMED.<br>
I NEVER ARGUE WITH IDIOTS</p>
<div class="btn-group pull-right commentsButtonsGroup">
<button class="btn btn-default no-outline reply btn-xs hideIfCanNotComment" onclick="popupCommentTextarea(306, '');"><i class="fas fa-reply"></i> Reply</button>
<button onclick="saveCommentLikeDislike(306, 1);" class="faa-parent animated-hover btn btn-default no-outline btn-xs commentLikeDislikeBtn commentLikeBtn hideIfremoveThumbsUpAndDown hideIfUserNotLogged">
<i class="fas fa-thumbs-up faa-bounce"></i>
<small class="totalLikes4">4</small>
</button>
<button onclick="saveCommentLikeDislike(306, -1);" class="faa-parent animated-hover btn btn-default no-outline btn-xs commentLikeDislikeBtn commentDislikeBtn hideIfremoveThumbsUpAndDown hideIfUserNotLogged">
<i class="fas fa-thumbs-down faa-bounce faa-reverse"></i>
<small class="totalDislikes1">1</small>
</button>
<button class="btn btn-default no-outline btn-xs hideIfremoveThumbsUpAndDown hideIfUserLogged">
<i class="fas fa-thumbs-up"></i>
<small>4</small>
</button>
<button onclick="saveCommentLikeDislike(306, -1);" class="btn btn-default no-outline btn-xs hideIfremoveThumbsUpAndDown hideIfUserLogged">
<i class="fas fa-thumbs-down"></i>
<small>1</small>
</button>
<button class="btn btn-default no-outline allReplies btn-xs isNotOpen hideIfNoVideosId" onclick="toogleReplies(306, this);">
<span class="hideIfIsOpen">
View all replies <span class="total_replies badge">0</span> <i class="fa fa-chevron-down" aria-hidden="true"></i>
</span>
<span class="hideIfIsNotOpen">
Hide Replies <i class="fa fa-chevron-up" aria-hidden="true"></i>
</span>
</button>
<button class="btn btn-default no-outline pin btn-xs hideIfUserCanNotAdminComment hideIfIsResponse" onclick="pinComment(306);">
<span class="hideIfIsPinned">
<i class="fas fa-thumbtack"></i> Pin
</span>
<span class="hideIfIsUnpinned">
<i class="fas fa-map-marker"></i> Unpin
</span>
</button>
<button class="btn btn-default no-outline btn-xs hideIfUserCanNotEditComment" onclick="editComment(306);">
<i class="fas fa-edit" aria-hidden="true"></i>
</button>
<button class="btn btn-default no-outline btn-xs delete hideIfUserCanNotAdminComment" onclick="deleteComment(306)">
<i class="fa fa-trash" aria-hidden="true"></i>
</button>
<button class="btn btn-default no-outline btn-xs hideIfHasVideosId" onclick="document.location=webSiteRootURL+'video/713#comment_306'">
<i class="fas fa-external-link-square-alt"></i> Go to video
</button>
</div>
<div class="repliesArea isNotOpen"></div>
</div>
</div>
.media, .media-body {
overflow: hidden;
zoom: 1;
}
.media {
/* margin-top: 15px; */
}
.media, .media-body {
overflow: hidden;
zoom: 1;
}
.media {
margin-top: 15px;
}
.animate__flipInX {
-webkit-backface-visibility: visible!important;
backface-visibility: visible!important;
-webkit-animation-name: flipInX;
animation-name: flipInX;
}
.animate__animated {
-webkit-animation-duration: 1s;
animation-duration: 1s;
-webkit-animation-duration: var(--animate-duration);
animation-duration: var(--animate-duration);
-webkit-animation-fill-mode: both;
animation-fill-mode: both;
}

**Comment by Broly5551** [comment]
We went into the code of the comments, and we were unable to discover any CSS element that we could adjust. The following code is what we saw:

"<div class="animate__animated animate__flipInX media isNotAResponse userCanAdminComment userCanEditComment myVote0 isNotPinned isNotResponse" id="comment_306">
<div class="media-left">
<img src="https://corder.joshwho-cdn.com/videos/userPhoto/photo39.png?cache=1657056920_1657056920" class="media-object">
</div>
<div class="media-body">
<h3 class="media-heading hideIfHasVideosId">
<a href="https://corder.tv/video/713/world-class-loser-pig-man-of-the-outback?channelName=VJAYENTERTAINMENTNEWS" class="keychainify-checked"><i class="fas fa-video"></i> WORLD CLASS LOSER PIG MAN OF THE OUTBACK</a>
</h3>
<h4 class="media-heading">
<a href="https://corder.tv/channel/VJAYENTERTAINMENTNEWS" class="keychainify-checked"><i class="fas fa-user"></i> vjaytv</a>
<small><i>3 months</i></small>
<i class="fas fa-thumbtack pull-right hideIfIsUnpinned" onclick="pinComment(306);" style="cursor: pointer;"></i>
</h4>
<p>FREEDOM OF SPEECH IN THE REAL WORLD DOES NOT MEAN FREEDOM TO HARRASS, NAME CALLING AND SPAMMING ALL THE COMMENT BOARDS. CHUCKLES IS A COWARD . AND DESERVES TO BE MOCKED AND SHAMED.<br>
I NEVER ARGUE WITH IDIOTS</p>
<div class="btn-group pull-right commentsButtonsGroup">
<button class="btn btn-default no-outline reply btn-xs hideIfCanNotComment" onclick="popupCommentTextarea(306, '');"><i class="fas fa-reply"></i> Reply</button>
<button onclick="saveCommentLikeDislike(306, 1);" class="faa-parent animated-hover btn btn-default no-outline btn-xs commentLikeDislikeBtn commentLikeBtn hideIfremoveThumbsUpAndDown hideIfUserNotLogged">
<i class="fas fa-thumbs-up faa-bounce"></i>
<small class="totalLikes4">4</small>
</button>
<button onclick="saveCommentLikeDislike(306, -1);" class="faa-parent animated-hover btn btn-default no-outline btn-xs commentLikeDislikeBtn commentDislikeBtn hideIfremoveThumbsUpAndDown hideIfUserNotLogged">
<i class="fas fa-thumbs-down faa-bounce faa-reverse"></i>
<small class="totalDislikes1">1</small>
</button>
<button class="btn btn-default no-outline btn-xs hideIfremoveThumbsUpAndDown hideIfUserLogged">
<i class="fas fa-thumbs-up"></i>
<small>4</small>
</button>
<button onclick="saveCommentLikeDislike(306, -1);" class="btn btn-default no-outline btn-xs hideIfremoveThumbsUpAndDown hideIfUserLogged">
<i class="fas fa-thumbs-down"></i>
<small>1</small>
</button>
<button class="btn btn-default no-outline allReplies btn-xs isNotOpen hideIfNoVideosId" onclick="toogleReplies(306, this);">
<span class="hideIfIsOpen">
View all replies <span class="total_replies badge">0</span> <i class="fa fa-chevron-down" aria-hidden="true"></i>
</span>
<span class="hideIfIsNotOpen">
Hide Replies <i class="fa fa-chevron-up" aria-hidden="true"></i>
</span>
</button>
<button class="btn btn-default no-outline pin btn-xs hideIfUserCanNotAdminComment hideIfIsResponse" onclick="pinComment(306);">
<span class="hideIfIsPinned">
<i class="fas fa-thumbtack"></i> Pin
</span>
<span class="hideIfIsUnpinned">
<i class="fas fa-map-marker"></i> Unpin
</span>
</button>
<button class="btn btn-default no-outline btn-xs hideIfUserCanNotEditComment" onclick="editComment(306);">
<i class="fas fa-edit" aria-hidden="true"></i>
</button>
<button class="btn btn-default no-outline btn-xs delete hideIfUserCanNotAdminComment" onclick="deleteComment(306)">
<i class="fa fa-trash" aria-hidden="true"></i>
</button>
<button class="btn btn-default no-outline btn-xs hideIfHasVideosId" onclick="document.location=webSiteRootURL+'video/713#comment_306'">
<i class="fas fa-external-link-square-alt"></i> Go to video
</button>
</div>
<div class="repliesArea isNotOpen"></div>
</div>
</div>
.media, .media-body {
overflow: hidden;
zoom: 1;
}
.media {
/* margin-top: 15px; */
}
.media, .media-body {
overflow: hidden;
zoom: 1;
}
.media {
margin-top: 15px;
}
.animate__flipInX {
-webkit-backface-visibility: visible!important;
backface-visibility: visible!important;
-webkit-animation-name: flipInX;
animation-name: flipInX;
}
.animate__animated {
-webkit-animation-duration: 1s;
animation-duration: 1s;
-webkit-animation-duration: var(--animate-duration);
animation-duration: var(--animate-duration);
-webkit-animation-fill-mode: both;
animation-fill-mode: both;
}"

**Comment by Broly5551** [comment]
[Corder Comment Problem Code 1.odt](https://github.com/WWBN/AVideo/files/10193049/Corder.Comment.Problem.Code.1.odt)

The attached file shows the code that we are looking at when we look at the comments.  We don't see any CSS element that can be adjusted.

**Comment by DanielnetoDotCom** [comment]
> [Corder Comment Problem Code 1.odt](https://github.com/WWBN/AVideo/files/10193049/Corder.Comment.Problem.Code.1.odt)
> 
> The attached file shows the code that we are looking at when we look at the comments. We don't see any CSS element that can be adjusted.

I am not sure what do you mean

**Comment by Broly5551** [comment]
> > [Corder Comment Problem Code 1.odt](https://github.com/WWBN/AVideo/files/10193049/Corder.Comment.Problem.Code.1.odt)
> > The attached file shows the code that we are looking at when we look at the comments. We don't see any CSS element that can be adjusted.
> 
> I am not sure what do you mean

What I mean is that there is no element for the CSS to lock on to.

**Comment by DanielnetoDotCom** [comment]
The CSS is there, I think you do not have the right files

**Comment by JoshWho** [comment]
@DanielnetoDotCom I looked through the css and I do not see anything you can adjust css wise for this. 

There is no element to hook to without changing global elements. 


We went into the code of the comments, and we were unable to discover any CSS element that we could adjust. The following code is what we saw:
```

<div class="animate__animated animate__flipInX media isNotAResponse userCanAdminComment userCanEditComment myVote0 isNotPinned isNotResponse" id="comment_306">
<div class="media-left">
<img src="https://corder.joshwho-cdn.com/videos/userPhoto/photo39.png?cache=1657056920_1657056920" class="media-object">
</div>
<div class="media-body">
<h3 class="media-heading hideIfHasVideosId">
<a href="https://corder.tv/video/713/world-class-loser-pig-man-of-the-outback?channelName=VJAYENTERTAINMENTNEWS" class="keychainify-checked"><i class="fas fa-video"></i> WORLD CLASS LOSER PIG MAN OF THE OUTBACK</a>
</h3>
<h4 class="media-heading">
<a href="https://corder.tv/channel/VJAYENTERTAINMENTNEWS" class="keychainify-checked"><i class="fas fa-user"></i> vjaytv</a>
<small><i>3 months</i></small>
<i class="fas fa-thumbtack pull-right hideIfIsUnpinned" onclick="pinComment(306);" style="cursor: pointer;"></i>
</h4>
<p>FREEDOM OF SPEECH IN THE REAL WORLD DOES NOT MEAN FREEDOM TO HARRASS, NAME CALLING AND SPAMMING ALL THE COMMENT BOARDS. CHUCKLES IS A COWARD . AND DESERVES TO BE MOCKED AND SHAMED.<br>
I NEVER ARGUE WITH IDIOTS</p>
<div class="btn-group pull-right commentsButtonsGroup">
<button class="btn btn-default no-outline reply btn-xs hideIfCanNotComment" onclick="popupCommentTextarea(306, '');"><i class="fas fa-reply"></i> Reply</button>
<button onclick="saveCommentLikeDislike(306, 1);" class="faa-parent animated-hover btn btn-default no-outline btn-xs commentLikeDislikeBtn commentLikeBtn hideIfremoveThumbsUpAndDown hideIfUserNotLogged">
<i class="fas fa-thumbs-up faa-bounce"></i>
<small class="totalLikes4">4</small>
</button>
<button onclick="saveCommentLikeDislike(306, -1);" class="faa-parent animated-hover btn btn-default no-outline btn-xs commentLikeDislikeBtn commentDislikeBtn hideIfremoveThumbsUpAndDown hideIfUserNotLogged">
<i class="fas fa-thumbs-down faa-bounce faa-reverse"></i>
<small class="totalDislikes1">1</small>
</button>
<button class="btn btn-default no-outline btn-xs hideIfremoveThumbsUpAndDown hideIfUserLogged">
<i class="fas fa-thumbs-up"></i>
<small>4</small>
</button>
<button onclick="saveCommentLikeDislike(306, -1);" class="btn btn-default no-outline btn-xs hideIfremoveThumbsUpAndDown hideIfUserLogged">
<i class="fas fa-thumbs-down"></i>
<small>1</small>
</button>
<button class="btn btn-default no-outline allReplies btn-xs isNotOpen hideIfNoVideosId" onclick="toogleReplies(306, this);">
<span class="hideIfIsOpen">
View all replies <span class="total_replies badge">0</span> <i class="fa fa-chevron-down" aria-hidden="true"></i>
</span>
<span class="hideIfIsNotOpen">
Hide Replies <i class="fa fa-chevron-up" aria-hidden="true"></i>
</span>
</button>
<button class="btn btn-default no-outline pin btn-xs hideIfUserCanNotAdminComment hideIfIsResponse" onclick="pinComment(306);">
<span class="hideIfIsPinned">
<i class="fas fa-thumbtack"></i> Pin
</span>
<span class="hideIfIsUnpinned">
<i class="fas fa-map-marker"></i> Unpin
</span>
</button>
<button class="btn btn-default no-outline btn-xs hideIfUserCanNotEditComment" onclick="editComment(306);">
<i class="fas fa-edit" aria-hidden="true"></i>
</button>
<button class="btn btn-default no-outline btn-xs delete hideIfUserCanNotAdminComment" onclick="deleteComment(306)">
<i class="fa fa-trash" aria-hidden="true"></i>
</button>
<button class="btn btn-default no-outline btn-xs hideIfHasVideosId" onclick="document.location=webSiteRootURL+'video/713#comment_306'">
<i class="fas fa-external-link-square-alt"></i> Go to video
</button>
</div>
<div class="repliesArea isNotOpen"></div>
</div>
</div>
.media, .media-body {
overflow: hidden;
zoom: 1;
}
.media {
/* margin-top: 15px; */
}
.media, .media-body {
overflow: hidden;
zoom: 1;
}
.media {
margin-top: 15px;
}
.animate__flipInX {
-webkit-backface-visibility: visible!important;
backface-visibility: visible!important;
-webkit-animation-name: flipInX;
animation-name: flipInX;
}
.animate__animated {
-webkit-animation-duration: 1s;
animation-duration: 1s;
-webkit-animation-duration: var(--animate-duration);
animation-duration: var(--animate-duration);
-webkit-animation-fill-mode: both;
animation-fill-mode: both;
}


```

**Comment by DanielnetoDotCom** [comment]
Is this also happening with you @JoshWho ??

you guys are NOT supposed to add any CSS, the default files suppose to work fine.

**Comment by JoshWho** [comment]
No it is just on his site for some reason. Wondering if Linux kernel lang
or something is different
