### ISSUE TITLE
SSL on apache2 not working

### ISSUE THREAD

**Issue by krsamue101** [WWBN/AVideo#7449]
https://user-images.githubusercontent.com/105032235/205441930-e60aec88-9bf3-4a11-921d-d37512d9b548.mp4

I installed AVideo and SSL but page is not loaded normally with https. But with http works fine

**Comment by DanielnetoDotCom** [comment]
I cannot teach you how to install a server , you may need to google for some help

**Comment by krsamue101** [comment]
Oh I restarted apache2 and it worked :) thanks you for your help!
