### ISSUE TITLE
Trying to add a video to a program through search. Search freezes. Never returns. Happens ≈80% of the time.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7453]
**Describe the bug**

Organize Program->Open any program->[+Add]->Videos tab

Type in a search phrase. Too often, the window dims, the spinner spins, and remains that way until you close the window, re-open and try again.

Failure rate is approximately 80%.

RECOMMENDATION: can we re-use the SQL code from /mvideos?

**Comment by walt93** [comment]
I’ll try to dig in and help characterize it some more. There are certain searches that freeze it like every time and searches that fail some times. It’s definitely weird.

**Comment by DanielnetoDotCom** [comment]
Any idea what search that always happens?

I really need to reproduce it

**Comment by DanielnetoDotCom** [comment]
Unfortunately, it is working here.

when this happens can you please also check the access.log and apache error log?

**Comment by JoshWho** [comment]
I think it has to do with how much IO and SQL server is being used when you are trying to run the search.  https://github.com/WWBN/AVideo/issues/7523
