### ISSUE TITLE
Roku json for program is 404?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7455]
**Describe the bug**
https://conspyre.tv/roku.json/?program_id=106939 has a podcasters VoD media. We're launching the Roku channel Monday. His livestream airs Tuesday nights. But his VoD is broken. 

**To Reproduce**
1. Go to https://conspyre.tv/roku.json/?program_id=106939
2. Observe 404 error

**Expected behavior**
Valid Roku JSON

**Comment by DanielnetoDotCom** [comment]
roku.json is a file. 

the correct URL is https://conspyre.tv/roku.json?program_id=106939 (without the last slash)

**Comment by walt93** [comment]
Makes sense. Here is the bug.

1) I log in as admin
2) From the Users page, I log in as my user
3) From my user, I go to Organize program
4) From my user's program, I edit that program
5) From that program, I go to the Feed menu and select Roku

What my monkey brain is looking for is after that page opens, I want to get the program_id out of the URL. Monkey brain saw 404. Monkey brain confused. Where is banana? Logged bug.

The page https://conspyre.tv/plugin/PlayLists/managerPlaylists.php opens and after it is done running the page is redirected to https://conspyre.tv/roku.json/?program_id=106939

So it's just a typo, somewhere in that code path… 

From here is where we got the URL with the misplaced /
vvvvvv
![Screen Shot 2022-12-05 at 3 12 33 PM](https://user-images.githubusercontent.com/11711050/205763356-6c565959-1e64-47ee-9a56-3b2a2fc743c6.png)
