### ISSUE TITLE
Clone Function Abends on Tube3..

### ISSUE THREAD

**Issue by aridzonan13** [WWBN/AVideo#7464]
Daniel,

Tube3's clone plugin has shutdown again.

FYI,
JQ

**Comment by aridzonan13** [comment]
Mark did and found nothing..

**Comment by DanielnetoDotCom** [comment]
As long as you guys does not have any info, you may need to hire me so I can check it directly

**Comment by aridzonan13** [comment]
Mark found the following.. 
"[05-Dec-2022 22:00:01 Africa/Abidjan] AVideoLog::DEBUG: Your Clone Site URL is empty, please click on the Edit parameters buttons and place an AVideo URL ({"cloneSiteURL":"","cloneSiteSSHIP":"","cloneSiteSSHUser":"","cloneSiteSSHPort":"","cloneSiteSSHPassword":{"type":"encrypted","value":""},"useRsync":false,"MaintenanceMode":false,"myKey":""}) SCRIPT_NAME: /var/www/AVideo/plugin/CloneSite/cloneClient.json.php
[05-Dec-2022 22:00:01 Africa/Abidjan] AVideoLog::DEBUG: Clone: Your Clone Site URL is empty, please click on the Edit parameters buttons and place an AVideo URL SCRIPT_NAME: /var/www/AVideo/plugin/CloneSite/cloneClient.json.php"

**Comment by DanielnetoDotCom** [comment]
Based on your logs, your Clone plugin parameters are empty

check it and fill the information again

**Comment by aridzonan13** [comment]
Not the case.  All of the parameters are filled still populated..

**Comment by aridzonan13** [comment]
Mark just saw the client form clear itself too.  Let's schedule another hour..

**Comment by DanielnetoDotCom** [comment]
Hi, please purchase an hour support on market place and lets schedule the time for tomorrow, here is 10:15 PM now
