### ISSUE TITLE
Chat2

### ISSUE THREAD

**Issue by lunar54** [WWBN/AVideo#7466]
Does anyone have chat2 installed and is there a Demo ?

Also after clicking a plugin within the plugin tab in admin section shouldn't it be redirected to AVideo site ? The link stays as a sub page and does not redirect to AVdieo plugin page  even adding it to cart makes it look like the plugin store is not on AVideo Site just stays on sub page.

**Comment by DanielnetoDotCom** [comment]
Regarding the Chat2 you can check it on the demo site https://demo.avideo.com/

**Comment by lunar54** [comment]
@DanielnetoDotCom will that show up on the right as well for live streams ?

and is that plugin page after you click on plugin suppose to be displayed as a sub page of site our should redirect to https://avideo.tube/Plugins ?
and whats the correct price one time 59.99 1 time purchase ? 
![chat2](https://user-images.githubusercontent.com/35050024/206569007-542e28d0-3d8d-4a48-a0c6-d52cc67cb127.PNG)

**Comment by DanielnetoDotCom** [comment]
Thanks, definitely this is a wrong page

this is the correct one

https://youphp.tube/marketplace/
