### ISSUE TITLE
iOS/Safari uses curly quotes, which causes search to fail when you quote the search string

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7467]
**Describe the bug**
My users are uploading duplicate videos. It is simply not possible for them to check for duplicates though. 

I want to tell them to check for dups before uploading. But search does not work. The main page search has been broken since the beginning of time. Takes minimum 60 seconds to return. 

Search from /mvideos seems broken. We have three copies of this documentary but search does not find it. 

Can’t tell users to search for duplicates when that doesn’t work. 
![AE63CA02-1837-4877-852C-78C485C18E56](https://user-images.githubusercontent.com/11711050/206540036-ddf71cda-c237-45a9-9ed3-5f03770ba0e5.png)
![A39AD02D-0BED-4ED7-8E6E-0961FA19DA4D](https://user-images.githubusercontent.com/11711050/206540041-7f1efe7e-aca6-4634-8bbc-e8c28555698e.png)

**Comment by walt93** [comment]
Aha! It's a combination of user error & Apple doing dumb things.

I was on mobile. Look at the quotes. Safari/iOS put in curly quotes. “Bob Lazar” not "Bob Lazar"

**Comment by walt93** [comment]
Not broken on Mac. On iOS devices. Smart quotes are turned on system wide by default. It's sketch AF. iOS, that is, not AVideo. iOS is sketch AF… Quoted search is a rare search case but  breaks it with their craptastic browser…

**Comment by DanielnetoDotCom** [comment]
I see, do you know any solution for that?

maybe force to replace ''(two single quotes) with "(one double quote)?

**Comment by DanielnetoDotCom** [comment]
Maybe this https://stackoverflow.com/a/21491305/2478180

**Comment by walt93** [comment]
Yeah that's what I was thinking, just do some hard string replace, it's going to be using the curly double quotes. From my Mac it looks like

```
8220     [201C](https://www.fileformat.info/info/unicode/char/201C/index.htm)     “     LEFT DOUBLE QUOTATION MARK
8221     [201D](https://www.fileformat.info/info/unicode/char/201D/index.htm)     ”     RIGHT DOUBLE QUOTATION MARK
```

and confirmed on iOS is the same (https://qaz.wtf/u/show.cgi)

**Comment by DanielnetoDotCom** [comment]
Can you please try this update?
