### ISSUE TITLE
Encoding, load tuning

### ISSUE THREAD

**Issue by yoshida-git-ai** [WWBN/AVideo#7469]
How to set a higher CPU load during encoding?

Right now it's working on an instance without a GPU, but the CPU still has spare power, so I'm looking for ways to tune it.
![video1](https://user-images.githubusercontent.com/94094919/206608647-003ac418-691f-41a9-9546-1dfc8c425716.png)

**Comment by walt93** [comment]
@yoshida-git-ai I asked the same question some time ago, and filed this away in case I needed it again.

_On the encoder, we do not specify the cores. but you can specify how many parallels the process._

_by default the encoder will try to use 100% of the CPU_

_check $global['concurrent'] here:_

https://github.com/WWBN/AVideo-Encoder/wiki/Configuration.php-variable-(-some-are-hidden-)
