### ISSUE TITLE
Time watched is reporting numbers that don't make sense.

### ISSUE THREAD

**Issue by dxbender** [WWBN/AVideo#7471]
**Describe the bug**
I uploaded a video that is about 1hr and 43mins long several days ago.  
The backend reports "51 Views and watched 12 d, 11 h, 33 min, 20 sec "

51 views X 1.75hrs = 89.25hrs...  divided by 24 = 3.71 days of viewing.  

1 viewer reports to have watched most of those 12 days.

Not a critical issue, but might want to look into it at some point.

See attached screen capture.
![time_watched](https://user-images.githubusercontent.com/118817025/206724485-51fea1dc-49a2-4f8a-94e7-96ef0942cb02.jpg)

**Comment by walt93** [comment]
I have been getting a ton of these, and there seem to be legit bots flooding our sites, if you do the math you might find that they are also watching the video at 2X speed in a loop. At one time I had 30 of them swarming one video. Your apache log might reveal the browser type as HeadlessChrome. Internet is weird. https://github.com/WWBN/AVideo/issues/7411 (I closed it after Daniel pushed a potential fix, but, I don't think its truly resolved)
