### ISSUE TITLE
Videotags don't show correct pages ( #1530 Still exists)

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#7473]
Hi Daniel,

The issue https://github.com/WWBN/AVideo/issues/1530 from 2019 still exist.

Videotags show the total amount of pages but only the first page is correct.
 
I know you can't reproduce it on the demo site.

Is there a chance to solve this issue ?

**Comment by DanielnetoDotCom** [comment]
I can only investigate if I can reproduce it.

what you can do is hire me by the hour and I can look directly at your server.

**Comment by TLCReuver** [comment]
Hi Daniel,

You need only VNC-access for testing/modifying or you need another tools too ?

Have nice Christmas days

**Comment by DanielnetoDotCom** [comment]
Hi

VNC is useless for me.

For myself I only need SSH root access and website admin access
