### ISSUE TITLE
Encoder looping

### ISSUE THREAD

**Issue by para2022** [WWBN/AVideo#7474]
Hi my encoder has started looping in a recent git update.

No errors in my logs, actually my logs have been error free for a long time now.

The file uploads, completes the encode then it flashes along at the end as usual then starts the encode again over and over again. 

I have changed nothing on my site other than git updates, file permissions are correct. I have tones of resources.

I just did a fresh encoder install and the problem still persists.

Thanks

**Comment by para2022** [comment]
Hi mate the bug is php 8.2 ive rolled back to 8.1 and its fine now. Just thought id let you know for development :)
I remember when the encoder always used 99% cpu on a 8 core server but now it hardly uses any 👍

**Comment by DanielnetoDotCom** [comment]
Strange, I also have some installations with PHP8.2 and it works fine.

but thanks, I will keep my eyes open.

**Comment by walt93** [comment]
I have run into it a few times now. Most recently I was cloning a podcasters channel, he's got a bunch of weird 696P and some other odd resolution, and the encoder had 35 files in it & got stuck there for hours re-doing a file, I kicked it out of the encoder & it got stuck again 10 files later. Rinse. Repeat. 

Also when I am doing the same with these long winded podcasters that have 4-6 hour shows, failure rate goes up.

**Comment by DanielnetoDotCom** [comment]
@walt93 what resolutions did you select to encode?

you must have something smaller than 696P, otherwise it may fail

**Comment by para2022** [comment]
I only use 360 240 and 720

**Comment by DanielnetoDotCom** [comment]
FYI, I just got a customer with a similar, problem, he was using FFMPEG version 3, once we update to version 4 the problem went away.
