### ISSUE TITLE
change ip

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo#7483]
Hello. I changed the ip, and now I can not upload the video. In Encoder it remains the same, where can I change it?

**Comment by DanielnetoDotCom** [comment]
the easiest solution is to reinstall the encoder.

or change it on the database.

**Comment by DittmerOk** [comment]
well, or in the database, I found the user Encoder. What should be changed in it?

**Comment by DittmerOk** [comment]
PS. there is no internet on this subnet

**Comment by DittmerOk** [comment]
tell me .. how to change through the database? If I immediately redirect to the old address /old address/upload+

**Comment by DanielnetoDotCom** [comment]
you will need to change it in your videos/configuration.php file and also in the table streamers column siteURL in your database

**Comment by DittmerOk** [comment]
weird, i changed the siteUrl to the one i need. And also does not enter the encoder. Although everything was ok on the old ip. What other options might be available to solve the problem? Ps ...there is no internet on my server, and I only need an encoder to upload videos locally.
![1](https://user-images.githubusercontent.com/56869986/207564759-a2665761-13b5-49a3-82f9-dee1f41c3aa5.jpg)
![2](https://user-images.githubusercontent.com/56869986/207564780-fb3664a6-301e-4739-9487-b3da101466dc.jpg)

**Comment by DanielnetoDotCom** [comment]
did you also change it on the videos/configuration.php?

**Comment by DanielnetoDotCom** [comment]
what is the error?

**Comment by DittmerOk** [comment]
as in the picture above. Unable to login to encoder. I click download video. goes to ..../upload and that's it. although the encoder is exactly set for me. before that, I went and downloaded the video on the old ip, where there was Internet

**Comment by DittmerOk** [comment]
then I transferred the computer to a network where there is no Internet, changed the ip in video / configuration and in the streamers database. and now he visits the site, but the link where the video is loaded does not enter

**Comment by DanielnetoDotCom** [comment]
that is weird. what is the exact URL for your jquery.min.js file?

![image](https://user-images.githubusercontent.com/18009293/208115215-b5c4a410-9fb8-4a20-9bd7-cae255351d81.png)

**Comment by DittmerOk** [comment]
hmm...yes, it's strange, the request goes to a completely different ip. Where can it be corrected?
![photo_2022-12-12_15-40-36](https://user-images.githubusercontent.com/56869986/208368717-ad36e56c-e603-40f2-a784-db25f217db08.jpg)

**Comment by DanielnetoDotCom** [comment]
> you will need to change it in your videos/configuration.php file and also in the table streamers column siteURL in your database

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/issues/7483#issuecomment-1348829751

**Comment by DittmerOk** [comment]
so I changed it in the database, and I have the right site. Where else does the second site come from, the old one?

**Comment by DanielnetoDotCom** [comment]
If you did [this](https://github.com/WWBN/AVideo/issues/7483#issuecomment-1352974457) and still a problem, you probably should try to reinstall

**Comment by DittmerOk** [comment]
but I can only reinstall it on a computer with Internet, and then I will need to change the network where there is no Internet. I'm right?

**Comment by DanielnetoDotCom** [comment]
the IP MUST be on your configuration.php file or in your database. 

I guess you are not finding it. so sorry I cannot help you.

**Comment by DittmerOk** [comment]
maybe I understood what the problem is) that the configuration.php 2 files ... the first one is the video / configuration. a SECOND video/encoder/videos/configuration . and everything works. However, on another server, such an error appeared when loading the main page ... where to change it, in which column in the database?
![photo_2022-12-12_15-40-36](https://user-images.githubusercontent.com/56869986/208707197-6cd8fbad-5cda-4a0b-ac84-ddbaea4ad15e.jpg)

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/issues/7483#issuecomment-1348829751

**Comment by DittmerOk** [comment]
I changed two configuration files. And a column of streamers. in the database. But the main page is still unavailable and there is a request for the previous ip. For the main page, maybe you still need to change something? Although earlier it was enough to change the url only in one configuration file?

**Comment by DittmerOk** [comment]
Thank you. Everything worked. But there was an encoder error. Why doesn't he want to work? On a local network without the absence of the Internet?
![f66163d3-2ec9-4a8c-bcf9-2fa729210fa9](https://user-images.githubusercontent.com/56869986/208887043-1dec199e-ecdb-4464-8eb7-8355e7ca1101.jpg)

**Comment by DanielnetoDotCom** [comment]
Duplicated https://github.com/WWBN/AVideo-Encoder/issues/463
