### ISSUE TITLE
Your encoders force open in new tab for some reason

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7485]
When all my encoders get busy it goes to yours and when it does it makes them all open in new tab for some reason.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/39392449/207255711-4f6e627c-80b9-402e-ba8c-249bb4cb2c74.gif)

**Comment by DanielnetoDotCom** [comment]
If it is a different domain it MUST open in a new tab. iframes will fail due to the cross-site script blocking

**Comment by JoshWho** [comment]
Ahhh I c. Makes since
