### ISSUE TITLE
QUERY - Where to put Embed code in the Header page of website

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#7489]
hi 

Not an issue as such. I have some code that I need to place just before the body tag of the main website page.

This is for Compliance for disability access.  This will make  disability users with impaired eye sight easier to look at website.
Code Below:-
Please advise.
Thanks..
--------------------------------------------------------------------
<script>
    (function(i,s,o,g,d,p,a,m){
      a=s.createElement(o);
      m=s.getElementsByTagName(o)[0];
      a.async=1;
      a.src=g+"/widget/wai-widget.js";
      a.charset="utf-8";
      m.parentNode.insertBefore(a,m);
      p.url = g;
      p.id = d;
      i["widgetAppParams"] = p;
    }
    )
    (window,document,"script", "https://soft.adaleadz.com","750",{});
      </script>

-----------------------------------------------------------------------------

**Comment by DanielnetoDotCom** [comment]
in the <head> tag (what is before the <body> tag)? or before the </body> tag?

**Comment by kollossus55** [comment]
The index page of the Website (HTML page). Its the header HTML and then the body HTML of the main page. Is it the Index.html page...

**Comment by DanielnetoDotCom** [comment]
To add in the header 

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript

Add in the bottom before </body> use CustomizeAdvanced plugin

![chrome-capture-2022-11-14](https://user-images.githubusercontent.com/18009293/207734806-235d4300-5c07-43e8-863d-2065beb02b50.gif)

add in a specific position https://github.com/WWBN/AVideo/wiki/ADs-plugin

**Comment by kollossus55** [comment]
It works...

Thanks for that...
