### ISSUE TITLE
Truth Social not picking up on Open Graph tags, Twitter has problems too

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7492]
**Describe the bug**
Posting video links to Truth Social yields nothing but a link. No nice pretty UX showing OG tags.

**To Reproduce**
1. Post a linkt o a video from any AVideo site to Truth Social
2. Observe that its not picking up the tags: 

![Screen Shot 2022-12-15 at 4 55 11 PM](https://user-images.githubusercontent.com/11711050/207997637-a14698cc-f9bf-481e-aec7-8d34318582b8.png)

**Additional data**
Just because tags are displaying on Twitter, does not mean that the tags are correct. In fact, Twitter is telling us that the tags have some error, unfortunately they don't tell us what the error is. 🤦‍♂️

![Screen Shot 2022-12-15 at 4 52 20 PM](https://user-images.githubusercontent.com/11711050/207997301-f42f3286-4e76-4572-a088-cc6faceacef0.png)

Can confirm, on Twitter, it fails to render the OG tags about 10% of the video links:

![Screen Shot 2022-12-15 at 4 53 46 PM](https://user-images.githubusercontent.com/11711050/207997454-fd7cfe32-8891-4267-b09f-cf1bf93bdb4a.png)

**Comment by DanielnetoDotCom** [comment]
the tags are the same for all videos.

so I suspect a few things:

1. network error on your side
2. a different Twitter bot that was blocked on AVideo

**Comment by JoshWho** [comment]
That twitter tool is broke do not rely on it. Og images are perfect. That is just big tech purposely sabotaging

**Comment by walt93** [comment]
Any theories on Truth Social? I've no idea where to begin with that one.  Links to other sites get them.

**Comment by Maikuolan** [comment]
I'm not sure that even Twitter itself knows what's going on at Twitter nowadays. At the moment, I would be wary about implementing any big changes to AVideo, or to any connected websites, for merely the sake of catering to any sudden changes at Twitter, because what's required today, might not be what's required tomorrow, or the day after, due to the unstable environment at Twitter at the moment.
