### ISSUE TITLE
Logo not displaying to a player

### ISSUE THREAD

**Issue by wetubeclub** [WWBN/AVideo#7494]
Hello Daniel,
after the last git pull the logo doesn't show in the player
cleared the memory and did everything related but the same result
some help?

Thank you
Ilias
![logo](https://user-images.githubusercontent.com/60543030/208106592-1d2e6956-d12d-4272-92a2-6fc078ae661e.jpg)

**Comment by DanielnetoDotCom** [comment]
I can see your logo 
![image](https://user-images.githubusercontent.com/18009293/208117166-3bf67550-38e3-4dfb-b26f-b6e577c3a6b6.png)

**Comment by wetubeclub** [comment]
chrome does not show the logo
in microsoft edge it appears
I'll see what happens
thanks daniel

**Comment by DanielnetoDotCom** [comment]
My screenshot was made on chrome.

maybe you have some chrome plugin that is blocking it

**Comment by wetubeclub** [comment]
you are right i disabled ADBLOCK extension and all good
but this was not the case before!
after all, we can live without it....
be well Daniel and I wish you all the best for the holidays

Thank you
Ilias
