### ISSUE TITLE
Video Ad switch is missing

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7496]
I no longer see the slide switch for this

![d2b832f8-86f2-4f27-8afb-661e8d6ca366](https://user-images.githubusercontent.com/39392449/208235222-2f36525f-6674-412c-acf6-e5453bb1a776.png)

**Comment by DanielnetoDotCom** [comment]
This is your CSS

https://joshwho-cdn.com/view/css/main.css?cache=1667020093_1667020093

something removed the spaces...

And the CSS rule` .material-switch > label::before` in your file is `.material-switch>label::before`

chrome is not recognizing the rule without the spaces 

if you disable the compression, everything should work again.

**Comment by JoshWho** [comment]
Ahhh Ok Thank you
