### ISSUE TITLE
Login button disabled

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo#7520]
Why does nothing happen when I enter my username and password, when I press the login button...? It does not even write that the username and password are incorrect. It feels like the login button is disabled. Although the button to register or forgot password works?

**Comment by DittmerOk** [comment]
On the main computer, the login succeeds, but on everyone else on the network, the login fails

**Comment by DanielnetoDotCom** [comment]
I am not sure what you mean

can you please screenshot?

**Comment by DittmerOk** [comment]
![ticket1](https://user-images.githubusercontent.com/56869986/210178365-b08ec32b-6902-4762-b7d8-a44a4baedc5d.jpg)
after filling in the login and password and pressing the login button, writes modal is not defined. Weird. This is written on all computers on the network, except for the main one.

**Comment by DanielnetoDotCom** [comment]
I am still not sure what you mean, but the first step is to fix/remove the script that is rising the first error

![image](https://user-images.githubusercontent.com/18009293/210233822-141ed71e-8e6d-4652-b596-1dd0ff2c75fa.png)

**Comment by DittmerOk** [comment]
I don't think that's the issue. Because I don't have internet access. That's why this script doesn't work. Google analytics. Well, on the main computer it shows this error in the console, but it still enters the account.
![1](https://user-images.githubusercontent.com/56869986/211823166-bbcf67fd-4225-40a9-9304-89617c292b3b.jpg)

**Comment by DittmerOk** [comment]
![1](https://user-images.githubusercontent.com/56869986/211823423-cb428b4f-c431-4d74-b0ed-4430679d0274.jpg)

![2](https://user-images.githubusercontent.com/56869986/211823572-b1309c4f-0fc5-456b-aafc-17ff13779634.jpg)
but such an error on other computers that are on the network.

**Comment by DanielnetoDotCom** [comment]
what type of browser is that? what version?

**Comment by DittmerOk** [comment]
hmm...maybe it's actually the browser. Because all computers on the network have a browser version of 54.0.2840.99m. They were last updated in 2018. And on the main computer, the version is fresher. Hmm ... and is there any way to get around this problem? Or do I need to update browsers on all computers?

**Comment by DanielnetoDotCom** [comment]
Can you install a new browser version?

**Comment by DittmerOk** [comment]
To do this, I need to update about 50 computers that are located in different locations. It will take a very long time.

**Comment by DanielnetoDotCom** [comment]
AVideo requires the newest JS support.

looks like your old browsers do not offer this support.

To be honest, I do not think you will find any script that works in browsers from 2018

**Comment by DittmerOk** [comment]
thanks. I updated my browser and it worked.
