### ISSUE TITLE
Roku poster frames should be 1280x720

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7521]
**Is your feature request related to a problem? Please describe.**
Our poster frames are 1920x1080, but will never be displayed full screen.
On Roku, users scrolling through videos burn huge amounts of image loads. Think the app loads 15 images per row & the user is scrolling rows…
This is a noticeable hit on our CDN bill.... Hundreds of $$$ lol

**Describe the solution you'd like**
Roku poster frames at 720P & JPEG the heck out of them like 50%…

**Comment by DanielnetoDotCom** [comment]
The roku images are always converted to 1280x720, check your feed.
