### ISSUE TITLE
Users Balance should show in the Promotion box Would make it easier

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7524]
Would be nice to add the users balance in this box so they know how much is in their wallet before promoting something. 

![3b6af5e1-4607-4e25-af7b-45a05f1b558f](https://user-images.githubusercontent.com/39392449/210156457-9ffcd60c-45a7-4623-b126-56134acb991f.png)

**Comment by DanielnetoDotCom** [comment]
I agree, but why don't you have the wallet on the top bar?

**Comment by JoshWho** [comment]
> I agree, but why don't you have the wallet on the top bar?

Because it takes up too much space. Plus when I take screenshots I hate having to keep hiding it blurring it so figure just needs to be in buying places and user account pages.

**Comment by DanielnetoDotCom** [comment]
Please check this update, and also the PromoteVideos version 2.0

![chrome-capture-2023-0-4 (1)](https://user-images.githubusercontent.com/18009293/210567611-0e3ca484-b018-440d-a731-75b092976749.gif)

**Comment by JoshWho** [comment]
Sweet looks great thank you
