### ISSUE TITLE
Update is not letting me run its full course 500 error

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7525]
Trying to run the upgrade goes to 500 error after a while

**Comment by JoshWho** [comment]
im gonna do a reboot first and see but seems like something stops when upgrading

**Comment by JoshWho** [comment]
YEah it still just hangs on the upgrade

**Comment by DanielnetoDotCom** [comment]
Go to your install directory and run the command `sudo php updatedb.php`

**Comment by JoshWho** [comment]
root@joshwhotv:/var/www/html/YouPHPTube# sudo php updatedb.php
Could not open input file: updatedb.php
root@joshwhotv:/var/www/html/YouPHPTube#

**Comment by DanielnetoDotCom** [comment]
Wrong directory, I told you **install** directory 

**cd /var/www/html/YouPHPTube/install**

**Comment by JoshWho** [comment]
I figured it out LOL forgot the /install

**Comment by JoshWho** [comment]
now waiting for the site to come back is it stuck?

**Comment by DanielnetoDotCom** [comment]
Once you run the update it should not stuck. It may be something else . Check your logs

**Comment by JoshWho** [comment]
nothing is loading

**Comment by JoshWho** [comment]
I possibly banned myself LOL

**Comment by DanielnetoDotCom** [comment]
Here opens fine ![image](https://user-images.githubusercontent.com/18009293/210158370-be237b6f-a146-4464-b029-44176c6024d8.png)

**Comment by JoshWho** [comment]
I think it worked then. I just got to wait out this ip block or wait till I get home. Thank you @DanielnetoDotCom
