### ISSUE TITLE
Something broke with the Roku Feed 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7526]
![86894f2d-152a-40d6-bb72-f49fde459859](https://user-images.githubusercontent.com/39392449/210158678-405521e6-96b9-4e91-961f-63932f49618d.png)

**Comment by JoshWho** [comment]
![1f4150d2-4b3b-4dce-8725-919ff24e7cd5](https://user-images.githubusercontent.com/39392449/210158702-fec63202-e38d-468b-8ecd-1fe32d7ebeda.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure what is the error, you need to specify the URL with the error.

but | suspect you blocked the roky bot somehow

**Comment by DanielnetoDotCom** [comment]
you need to check in the Roku feed what exactly URL is that, then check in your server what is happening when you or Roku bot is trying to access it.

**Comment by JoshWho** [comment]
It wont even let me view it now. It is just trashed. Weird.  https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json

**Comment by JoshWho** [comment]
That logic makes no sense. It was working for a whole year and now all of a sudden something got changed and it stopped working. I didn't change anything, so it has to be something that got changed in a update.

**Comment by JoshWho** [comment]
Connections are fine on the firewall with Roku
```

Tue Jan 03 2023 17:16:41 GET | 200 | 18.235.243.72 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:16:22 GET | 200 | 18.235.243.72 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:16:10 GET | 200 | 54.160.160.131 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:16:05 GET | 200 | 18.235.243.72 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:13:37 GET | 200 | 18.235.243.72 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:13:29 GET | 200 | 18.235.243.72 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:11:07 GET | 200 | 54.160.160.131 | https://www.joshwhotv.com/channel/JoshWhoNews/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:11:01 GET | 200 | 54.160.160.131 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:10:55 GET | 200 | 54.160.160.131 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:07:42 GET | 200 | 18.235.243.72 | https://www.joshwhotv.com/channel/JoshWhoNews/roku.json?rowCount=100 | event body

```

**Comment by DanielnetoDotCom** [comment]
It looks like a timeout or a server block.

check your access log

I guess you have too many videos, try to limit to the last 100

https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100

**Comment by JoshWho** [comment]
You must not have seen this post
```

Tue Jan 03 2023 17:16:41 GET | 200 | 18.235.243.72 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:16:22 GET | 200 | 18.235.243.72 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:16:10 GET | 200 | 54.160.160.131 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:16:05 GET | 200 | 18.235.243.72 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:13:37 GET | 200 | 18.235.243.72 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:13:29 GET | 200 | 18.235.243.72 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:11:07 GET | 200 | 54.160.160.131 | https://www.joshwhotv.com/channel/JoshWhoNews/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:11:01 GET | 200 | 54.160.160.131 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:10:55 GET | 200 | 54.160.160.131 | https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100 | event body
Tue Jan 03 2023 17:07:42 GET | 200 | 18.235.243.72 | https://www.joshwhotv.com/channel/JoshWhoNews/roku.json?rowCount=100 | event body
```

**Comment by JoshWho** [comment]
I do have a limit set and the logs show it as fine

**Comment by DanielnetoDotCom** [comment]
Try to reduce the limit to 10 (just for testing)

The only way to help you is if you can detect what video and what url is not valid

**Comment by JoshWho** [comment]
It wont load in Roku dev portal anymore been errored for too long

![f8f8eaf9-37cb-4371-9bb4-137074e2004b](https://user-images.githubusercontent.com/39392449/210464035-c1f8ffe6-4a22-49bb-a9ea-ad07bec856bb.png)

**Comment by DanielnetoDotCom** [comment]
Sorry, I do not know what the issue may be.

the only thing I can suggest is for you to try to add another website to it. 

BTW,[ this log](https://github.com/WWBN/AVideo/issues/7526#issuecomment-1370354645) does not look like an apache access log or error log

**Comment by JoshWho** [comment]
It is my dns log.

**Comment by DanielnetoDotCom** [comment]
You MUST check apache access and avideo error log

**Comment by JoshWho** [comment]
I do not know why that would change what is going on with Roku. My point is Roku is not being blocked by any firewall.

**Comment by DanielnetoDotCom** [comment]
If you want to figure out what is going on with Roku, this is required.

we need to know if Roku is your server or not.

if it is reaching, the error log may reveal what is the issue.

**Comment by JoshWho** [comment]
It is working. It is just erroring for Roku. The videos showing the error are embed videos that doesn't have a video link. That is the error it says the video does not have a video link

**Comment by JoshWho** [comment]
According to the Roku logs the Feed got changed. Last month the feed was fine, this month the errors exist.

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/210676753-86b131f7-e86a-4c32-8a19-c3d8b53b871c.png)

**Comment by JoshWho** [comment]
![f1109edb-578c-4105-94cd-a08733719d53](https://user-images.githubusercontent.com/39392449/210677266-f754b6de-5b59-477c-8b1e-2fd5b8893c3c.png)

**Comment by DanielnetoDotCom** [comment]
So you can check by yourself what is the feed for those videos.

**Comment by JoshWho** [comment]
THis is where it is getting that from https://www.joshwhotv.com/channel/SeekingTheTruth/roku.json?rowCount=100

**Comment by DanielnetoDotCom** [comment]
that is what you supposed to do 

![image](https://user-images.githubusercontent.com/18009293/210678032-62e4d29b-d9ef-4609-927b-7289cf994b25.png)

your video is not found https://v.joshwho-cdn.com/file/joshwhotv/v_221109040229_v66fa_HD.mp4

![image](https://user-images.githubusercontent.com/18009293/210678172-0af4c6ba-0d77-4d98-9221-1b14ab3db976.png)

this is your video https://www.joshwhotv.com/v/72047

**Comment by JoshWho** [comment]
IF those files do not exist why do they show as active and not broken?

**Comment by DanielnetoDotCom** [comment]
this does not exist in your B2/S3 storage, NOT locally. locally it has the dummy file 

or it was never uploaded or something else happen

**Comment by JoshWho** [comment]
I know but usually it will say broken if that happens

**Comment by DanielnetoDotCom** [comment]
You do have something there  https://www.joshwhotv.com/videos/v_221109040229_v66fa/v_221109040229_v66fa_HD.mp4

**Comment by JoshWho** [comment]
looks like a dud weird

**Comment by JoshWho** [comment]
Im gonna have to wait for Roku to get the dev thing back on. Looks like they have it disabled right now.

**Comment by JoshWho** [comment]
Looks like everything is back in order after they re enabled the dev panel.

![0c852d18-18fc-4960-9cdf-9f8afd1fadff](https://user-images.githubusercontent.com/39392449/211186074-7f9f69ff-c2cd-4b55-9dbf-0549abbcbcd3.png)

**Comment by gbrn** [comment]
@JoshWho I don't know if your Roku Feed issue is resolved... but I had a similar issue and found that the AVideo system does not support the Feed display when the site is closed to registered users only.
Check it out here: #7517
