### ISSUE TITLE
encoder - php8.1, php8.2

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#7532]
Hi Daniel
the encoder does not work in PHP8.1 and PHP8.2
you can check what is wrong and how to fix it

PHP8.1
![8 1](https://user-images.githubusercontent.com/93145787/210400057-e54f4db6-d8c8-4c7f-8e56-f6b0e8808170.png)

PHP8.2
![8 2](https://user-images.githubusercontent.com/93145787/210400121-962afa35-80b5-41bd-8e82-534dab0bc5e9.png)

**Comment by DanielnetoDotCom** [comment]
Google and find a way to configure your PHP to not show deprecated errors
