### ISSUE TITLE
Health Check

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#7551]
Hi Daniel
I updated all the files on the server except the videos folder and I have this information

![red](https://user-images.githubusercontent.com/93145787/211866573-ff1d1898-0334-4d9e-9398-1fc8c90a0dd2.png)

**Comment by DanielnetoDotCom** [comment]
your domain seems to be good. maybe was a timeout error, you can try again later, but as I can see, there is nothing to worry about

**Comment by KrzysioMisio** [comment]
OK thanks
I'll check later
