### ISSUE TITLE
All plugins missing after update

### ISSUE THREAD

**Issue by karen20ced4** [WWBN/AVideo#7555]
hello my friends, 

after update to the last version of Avideo (i use methode git pull), after all steps for updating all database versions, 
the plugins menu show me NO PLUGINS installed, just give me the message: No results found! . please see the picture

i check the files and folders on the server and all plugins are there, with propper 0775 rights
the site work OK, and i have some paid plugins that are still working ok but don't show up in menu

please help, any comments or suggestion are welcome

thanks

![1](https://user-images.githubusercontent.com/37412485/212351864-66cb1b2b-f7a8-4ff8-9d49-033808c2cb99.jpg)

**Comment by DanielnetoDotCom** [comment]
check your avideo.log

**Comment by DanielnetoDotCom** [comment]
did you update using` git pull`?

also looks like you are not using the latest version. looks like you are using a very old version.

the file with error does not exists anymore for a long time

**Comment by karen20ced4** [comment]
my original site was 2 year old, with no updates. i made around 47 steps of updating DB, 
last DB file was  updatedb/updateDb.v6.2.sql

maybe you have right and i don't use git pull for this site, i downloaded the latest version of AVIDEO available in DEC2022 , 
and i overwritten files over site


there is a way that i can fix this ? 
thanks

**Comment by DanielnetoDotCom** [comment]
the only way I can see is if you can update it properly with the git commands.

also, update all the plugins

**Comment by karen20ced4** [comment]
i fix the problem, by remove all old plugins. thanks for your support
