### ISSUE TITLE
Something changed on my AVideo/server/installation, all of my backend scripts now fail to connect to mysql

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7560]
**Describe the question**
Probably something simple, but I don't know what changed, what's the correct solution?

All of my python scripts (formerly quite functional) are now failing with:

Code:
`db = mysql.connector.connect(user='youphptube',
                              password='********',
                              host='127.0.0.1',
                              database='AVideo',
                              use_unicode=True, charset="utf8")`

Error:
`_mysql_connector.MySQLInterfaceError: Host '127.0.0.1' is not allowed to connect to this MySQL server
`

Not sure why this is failing, as the script I am running is on the same box as AVideo.

_--Update--_

I found that:

`mysql -u youphptube -p -h 127.0.0.1
`

fails, while

`mysql -u youphptube -p -h localhost
`

succeeds. However using 'localhost' doesn't work in the mysql connector case, it still fails and the error still says '127.0.0.1' (and not 'localhost'.)

**Comment by DanielnetoDotCom** [comment]
this is clearly your MySQL user rights.

I do not have it on top of my mind but you must google and check how to create a user or give permission to it.

**Comment by walt93** [comment]
Daniel, this was working before I had you debug the problem with my encoders.

I spent about 2 hours on it last night, I set up a mysql user to connect from a specific IP addresss, punched a hole in the firewall for that address, and set the mysql.cnf to bind to the machines IP address - as should be standard for any linux/mysql installation - and this also fails

Something has been configured to disallow connections & I can't find it. Can you remember what you locked down?

**Comment by DanielnetoDotCom** [comment]
try to run this command

sudo mysql -u root -e "USE mysql;CREATE USER 'youphptube'@'127.0.0.1' IDENTIFIED BY 'youphptube';GRANT ALL PRIVILEGES ON *.* TO 'youphptube'@'127.0.0.1'; FLUSH PRIVILEGES; "

**Comment by walt93** [comment]
Very strangely it looks like its listening on 33060 not 3306

```
sudo netstat -lnp | grep mysql
tcp        0      0 127.0.0.1:33060         0.0.0.0:*               LISTEN      2620050/mysqld
tcp        0      0 45.88.201.127:3306      0.0.0.0:*               LISTEN      2620050/mysqld
unix  2      [ ACC ]     STREAM     LISTENING     82829732 2620050/mysqld       /var/run/mysqld/mysqlx.sock
unix  2      [ ACC ]     STREAM     LISTENING     82829734 2620050/mysqld       /var/run/mysqld/mysqld.sock
```

**Comment by walt93** [comment]
Changing the python code to connect to port 33060 we get some progress. Now it's failing with a protocol mismatch

`mysql.connector.errors.DatabaseError: 2007 (HY000): Protocol mismatch; server version = 11, client version = 10`

Daniel, how did the port change to 33060 and not have AVideo break? Seems like the code base must be changed too?

**Comment by DanielnetoDotCom** [comment]
I am so sorry, I do not know what you have done in your MySQL, and I cannot help you with that.

**Comment by walt93** [comment]
Ok Daniel. I will debug this. I know my python scripts which access the database were working. Was hoping you had some clues. My best theories:
  Maybe something changed with AVIdeo?
  Maybe when you went in to debug my servers, you restored some default configuration which broke my scripts?
  Maybe mysql automatically configured to port 33060 when I added a user coming from an external IP address?

I'm just looking for clues & trying to do this in a way so as not to break my AVideo install… Site's been down for a month because of issues between Wasabi and my datacenter………

**Comment by walt93** [comment]
Daniel, I disabled the binding in mysqld.cnf to the NIC address and put it back to 127.0.0.1 and it started working again.

Not sure what happened that caused it to fail, but, your command above to re-create the mysql user worked. Thanks!
