### ISSUE TITLE
new server

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#7564]
Hello Daniel,
I want to transfer my entire website to a new server (new computer)
no domain change !!
Is it enough for me to copy the database and the videos folder and upload it via FTP ?
do i need to do anything else ??

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-make-a-backup

**Comment by KrzysioMisio** [comment]
you can check not working video tutorial
https://tutorials.avideo.com/video/backup-or-clone-your-site

**Comment by DanielnetoDotCom** [comment]
what do you mean?

**Comment by KrzysioMisio** [comment]
click on the link, the tutorial video doesn't work
https://tutorials.avideo.com/video/backup-or-clone-your-site

**Comment by DanielnetoDotCom** [comment]
for me it is working fine.

**Comment by KrzysioMisio** [comment]
doesn't work for me on Firefox
on Edge and Brave it works :-)
OK thanks
