### ISSUE TITLE
having trouble shrinking the Video Avatar Overlay 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7566]
![31e25ec9-e57d-4d45-9aae-8768a2750299](https://user-images.githubusercontent.com/39392449/213086370-f586281f-95d6-4d1f-ada1-2256727a4615.png)

this page https://www.joshwhotv.com/video/.7CD7eQ/mr-cellophane-1

Css I am using is not working

.VideoLogoOverlay img {
    max-height: 70px;
    max-width: 39px;
}

**Comment by JoshWho** [comment]
@media (max-width: 1200px){
    .VideoLogoOverlay img{
        max-height: 30px;
        max-width: 150px;
    }


@media (max-width: 767px) {
    .VideoLogoOverlay img{
        max-height: 20px;
        max-width: 120px;
    }

**Comment by DanielnetoDotCom** [comment]
I have no idea what you are trying to do. 

if is to change the image size, try to modify the image instead

#mainVideo > div.VideoLogoOverlay img{

}

**Comment by JoshWho** [comment]
> 

not sure what u mean

**Comment by JoshWho** [comment]
We had this solved in the past but the glitched erased it in the advance config

**Comment by JoshWho** [comment]
So you are saying to use


```
@media (max-width: 1200px){
div.VideoLogoOverlay img{
max-height: 30px;
max-width: 150px;
}

}

@media (max-width: 767px) {
div.VideoLogoOverlay img{
max-height: 20px;
max-width: 120px;
}
```

@DanielnetoDotCom ?

**Comment by JoshWho** [comment]
> @media (max-width: 1200px){
> div.VideoLogoOverlay img{
> max-height: 30px;
> max-width: 150px;
> }
> 
> 
> 
> @media (max-width: 767px) {
> div.VideoLogoOverlay img{
> max-height: 20px;
> max-width: 120px;
> }

That didn't work

**Comment by JoshWho** [comment]
Ok figured it out. For the correct size like how Youtube has it use this css style in your custom header box

```
<style>
@media  {
    .VideoLogoOverlay img{
        max-height: 20px;
        max-width: 120px;
    }
</style>
```
