### ISSUE TITLE
Please Make the Encoders Auto Delete error videos so it is not holding up the encoder network

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7572]
Encoder Network thinks encoders are busy because there will be a errored video in the cue list. Why can't it just ignore that or auto delete the error so the Encoder can be used by the encoder network? 

![75a13d45-db00-4514-bf85-851a4f3b4a2a](https://user-images.githubusercontent.com/39392449/213877486-12ad9c67-ae6b-4257-ac4c-58cd72dddc30.png)

**Comment by JoshWho** [comment]
![download (7)](https://user-images.githubusercontent.com/39392449/213878727-22db6a53-b1d1-41ae-99dc-167c2c973eb2.png)

**Comment by DanielnetoDotCom** [comment]
Good idea, I just created a command line to it, and I will add it in a crontab

**Comment by JoshWho** [comment]
What is the new command for it so I can add the cron on mine. Just ran the git pulls on them

**Comment by JoshWho** [comment]
Is there a cron job I need to run or something for this function to work? @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
This file https://github.com/WWBN/AVideo-Encoder/blob/master/install/deleteAllQueueWithError.php

this will delete all queue that has errors in your encoder.

it is up to you if you want to put in a crontab

**Comment by JoshWho** [comment]
Sweet thank you 

> This file https://github.com/WWBN/AVideo-Encoder/blob/master/install/deleteAllQueueWithError.php
> 
> this will delete all queue that has errors in your encoder.
> 
> it is up to you if you want to put in a crontab

What is the exact command?

**Comment by DanielnetoDotCom** [comment]
correct, to run it manually

`php /var/www/html/AVideo/AVideo-Encoder/install/deleteAllQueueWithError.php`

to put in a crontab 

1. Open your crontab file for editing using the following command:

`crontab -e`

1. Add the following line to the end of the file:

`````
0 4 * * * php /var/www/html/AVideo/AVideo-Encoder/install/deleteAllQueueWithError.php
`````

This line specifies that the command should be executed at 4:00 AM every day. 

1. Save the file and exit the editor.
