### ISSUE TITLE
In Netflix mode, the player is broken - crashes - exception - stack trace - hopefully easy fix :-)

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7580]
**Describe the bug**
I've tried on both conspyre.tv and a new site I am installing.

Clicking the play button gets an exception on both.

**To Reproduce**
1. Put site into "Netflix" mode
2. Click on the Play button for any video
3. See error

**Expected behavior**
The video to play.

**Error Logs**
`[23-Jan-2023 13:24:39 America/Los_Angeles] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Class \"LiveLinks\" not found in \/var\/www\/html\/AVideo\/plugin\/LiveLinks\/view\/liveVideo.php:17\nStack trace:\n#0 \/var\/www\/html\/AVideo\/view\/videoEmbeded.php(442): include_once()\n#1 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/plugin\/LiveLinks\/view\/liveVideo.php","line":17} SCRIPT_NAME: /view/videoEmbeded.php
`
**Screenshots**
![Screen Shot 2023-01-23 at 1 22 12 PM](https://user-images.githubusercontent.com/11711050/214152743-edaca429-6c9f-4741-ba06-d2815bfa76ee.png)

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by walt93** [comment]
The fix is almost working, however, when I click on Play to go to the videos page, I get a white page. Reloading the page works.

On clicking play, the following errors are emitted to the JS console:

![Screen Shot 2023-01-23 at 8 46 45 PM](https://user-images.githubusercontent.com/11711050/214214104-891b7dcb-e524-49ac-af6c-4ecd54b59ce6.png)

**Comment by DanielnetoDotCom** [comment]
Hi, this error is not happening on my side, but please try this update to see if fixes the issue.

**Comment by walt93** [comment]
Getting closer, but still the page loads in an inconsistent state and can't play the video until the user hits reload.

https://user-images.githubusercontent.com/11711050/214417109-f16b56dd-8e01-4115-b3c4-f7a8e6747677.mov

![Screen Shot 2023-01-24 at 1 14 12 PM](https://user-images.githubusercontent.com/11711050/214417730-6f89bd1d-bba0-4696-9f5e-58df540fb3a4.png)

I also seem to be having an issue with YPTSocket on this server...

**Comment by DanielnetoDotCom** [comment]
# Socket

debug your socket: https://github.com/WWBN/AVideo/wiki/Socket-Plugin#troubleshooting

# Play

inspect your HTML source code, try to direct access the video file (<source> tag) and find out why it is 404

**Comment by walt93** [comment]
Video file isn't 404 Daniel, again, hitting reload fixes the issue and video plays. What else could cause that?

**Comment by DanielnetoDotCom** [comment]
Sorry I have no idea, it has never happened to me

**Comment by walt93** [comment]
It's happening for me on my main site, on the replacement site I'm building, on the new site I'm building & since I just tore down that server and replaced it I rebuilt that site a 2nd time. So it happens on every AVideo installation.

Why don't you try a fresh install, use the install script that the rest of us use so you can see that it fails to install Nginx properly while you're at it.

And then you'll be left with a site that doesn't work in netflix mode. 100% **guaranteed**

**Comment by DanielnetoDotCom** [comment]
please share a video link with error

**Comment by walt93** [comment]
We've decided to use the gallery skin.
