### ISSUE TITLE
Signature plugin server test

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7584]
@DanielnetoDotCom the URL of this wiki is not working... https://netflix.youphptube.com/
https://github.com/WWBN/AVideo/wiki/Configure-a-Netflix-Clone-Page

I would like to do some tests on the signatures plugin. Any other servers available for testing?

**Comment by DanielnetoDotCom** [comment]
I am sorry for this outdated doc, please try this https://flix.avideo.com/

I will update the document.
