### ISSUE TITLE
Glitch in many strings (site title, customize plugin, video descriptions, etc…) after restoring via CloneSite plugin

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7590]
**Describe the bug**
I did a fresh install onto a new server, installed plug-ins and ran CloneSite. After the clone is completed. the string for the window title is glitched. "Conspyre•TV" -> 

![Screen Shot 2023-01-25 at 7 29 20 PM](https://user-images.githubusercontent.com/11711050/214752837-adfcbb81-db76-4b60-9664-2d7c8dc3fdfc.png)

I'm seeing other glitches, such as this:
![Screen Shot 2023-01-25 at 7 36 00 PM](https://user-images.githubusercontent.com/11711050/214753521-34732b88-3e92-4f3c-9a0c-beb7c46e9a4b.png)

Note: Same glitch appears in Site Settings for website title

Note: It seems it's all over the site. This is from Topmenu plugin:

![Screen Shot 2023-01-25 at 8 06 32 PM](https://user-images.githubusercontent.com/11711050/214756548-d072904b-ff61-4b38-b17a-4a9e1a5dfdf1.png)

Update: it's also in other metadata, video descriptions. Seems like some global SQL setting could do this?

**Expected behavior**

The original strings to appear after the clone is completed.

**Comment by DanielnetoDotCom** [comment]
This may happen if the database has different versions

Before doing anything try this...

Edit your `videos/configuration.php` file

add this

`$global['mysqli_charset'] = 'latin1';`

**Comment by walt93** [comment]
Thanks Daniel!
