### ISSUE TITLE
Archive LOG Error

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7595]
@DanielnetoDotCom In the new installation, I tried to compress the LOG and it presents the following error:
`
 [27-Jan-2023 16:13:17 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught Error: Class \"ZipArchive\" not found in \/var\/www\/html\/AVideo\/view\/logArchive.json.php:23\nStack trace:\n#0 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/view\/logArchive.json.php","line":23} SCRIPT_NAME: /AVideo/view/logArchive.json.php`

Is this a bug in the code... or some application that is not installed?

Unzip is installed and running normally:
![image](https://user-images.githubusercontent.com/37880073/215181764-698cc88f-0145-4095-8167-0397b6aabc4c.png)

**Comment by DanielnetoDotCom** [comment]
you are missing php-zip

`sudo apt install php-zip`

**Comment by gbrn** [comment]
Strange, it is installed, I did the full installation.
The system says it is installed and in the latest version.

```
ubuntu@ubuntu-server-arm-01:~$ sudo apt-get install php-zip
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
php-zip is already the newest version (2:8.2+93+ubuntu22.04.1+deb.sury.org+2).
The following packages were automatically installed and are no longer required:
  apport-symptoms augeas-lenses bc gir1.2-glib-2.0 gir1.2-packagekitglib-1.0
  iso-codes javascript-common libappstream4 libaugeas0 libdw1 libexpat1-dev
  libgirepository-1.0-1 libglib2.0-bin libgstreamer1.0-0 libinih1 libjs-jquery
  libjs-sphinxdoc libjs-underscore libmspack0 libnetplan0
  libpackagekit-glib2-18 libpython3-dev libpython3.10-dev libstemmer0d
  libunwind8 libxmlsec1 libxmlsec1-openssl packagekit packagekit-tools
  python-apt-common python3.10-dev run-one zerofree zlib1g-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

In the module listing it is there:

```
ubuntu@ubuntu-server-arm-01:~$ php -m
[PHP Modules]
calendar
Core
ctype
curl
date
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
random
readline
Reflection
session
shmop
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zip <------------------------------
zlib

[Zend Modules]
Zend OPcache
```

**Comment by DanielnetoDotCom** [comment]
check what is your php version.

you may need to install a specific version.

for example
`
sudo apt install php8.1-zip
`

**Comment by gbrn** [comment]
I think I installed php8.1... and then I installed 8.2... the system must have lost the references of which modules to use.
I did a full reinstall, installing only PHP 8.2 and it's working now.
