### ISSUE TITLE
Clone site works once. Clone site does not work subsequently.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7596]
**Describe the bug**
It seems that when we use CloneSite it completely overwrites the database including clonesite settings.

However, no matter how many times you try to reconfigure clonesite, it fails.

**To Reproduce**
1. Go to Target site -> plugins -> Clonesite
2. Set up URL, SSHIP, SSHUser, SSHPassword and copy myKey from SiteToClone
3. Click on Clone Now
4. Get dialog telling you to activate your client on SiteToClone
5. Go to SiteToClone -> plugins -> Clonesite and activate the key
6. From Target site, hit "Clone Now"
7. Now the error message is "Invalid key"

**Expected behavior**
To be able to clone a site more than one time

**Comment by DanielnetoDotCom** [comment]
check if both keys match (cloneSite plugin). 

I guess this is a bug that removes the key on the first clone attempt

**Comment by walt93** [comment]
Yeah they match, clone site only works one time.
