### ISSUE TITLE
Some users are having Login issues Is there new security settings?not logging them In. I cant seem to make it happen on my end but 3 people now are saying it

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7606]
Not sure why but some accounts do not login anymore and older ones do. Password salt is checked so I have no clue what else would cause this

**Comment by JoshWho** [comment]
[30-Jan-2023 09:01:18 America/Chicago] PHP Warning:  Undefined variable $total_viewers in path/to/my/streamer/site/plugin/YPTSocket/Message.php on line 506

**Comment by JoshWho** [comment]
[30-Jan-2023 09:34:41 America/Chicago] AVideoLog::ERROR: {"type":1,"message":"Maximum execution time of 30 seconds exceeded","file":"\/var\/www\/html\/YouPHPTube\/objects\/functions.php","line":1853} SCRIPT_NAME: /feed/index.php

**Comment by JoshWho** [comment]
Im going to lay around with some settings.

**Comment by JoshWho** [comment]
@DanielnetoDotCom Is there a way we can just expire all the old cookies and use a new cookie so all the user accounts work again?

**Comment by JoshWho** [comment]
Something is going on I got 7 people now all saying they can't login @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Check your logs...

If there is no clue try to reset the password and try again .

If does not work after reset the password, please let me know

**Comment by JoshWho** [comment]
I am not seeing thing that is the weird thing

**Comment by JoshWho** [comment]
User submitted me this video 

![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/39392449/215881873-31666bb2-0afb-40e3-9667-0722394bfe9d.gif)

**Comment by DanielnetoDotCom** [comment]
Sorry but I have no idea what is it

**Comment by DanielnetoDotCom** [comment]
Did you reset the password?

**Comment by JoshWho** [comment]
not my account I have 12 people now saying this is happening

**Comment by JoshWho** [comment]
Could have something to do with the new plugin hardening thing?

**Comment by DanielnetoDotCom** [comment]
I do not think so.

If some user cannot login reset his pass and check if makes any difference

**Comment by JoshWho** [comment]
I changed one users password and that did nothing, then I tried changing his username and that did nothing

**Comment by JoshWho** [comment]
Only error I keep seeing is this 


[31-Jan-2023 15:11:26 America/Chicago] PHP Warning:  Undefined variable $total_viewers in path/to/my/streamer/site/plugin/YPTSocket/Message.php on line 506

**Comment by DanielnetoDotCom** [comment]
Do you mean, it does not work even after change the password?

If yes please send me a user sample so I ca test it here

**Comment by JoshWho** [comment]
Not sure what you mean?

**Comment by DanielnetoDotCom** [comment]
Could it be the browser?

If you try the user in your PC, does it work?

**Comment by JoshWho** [comment]
nope tested all of them

**Comment by JoshWho** [comment]
> Could it be the browser?
> 
> If you try the user in your PC, does it work?

If I do Yes. If they do no

**Comment by DanielnetoDotCom** [comment]
Só e-mail me the user and password so I can test.

**Comment by JoshWho** [comment]
> Só e-mail me the user and password so I can test.

sent

**Comment by DanielnetoDotCom** [comment]
I just tested the user you sent to me on Chrome windows, and works fine

**Comment by JoshWho** [comment]
Works fine for me. BUt doesnt for them

**Comment by JoshWho** [comment]
and this is 12 people now

**Comment by DanielnetoDotCom** [comment]
Maybe is the browser, can you please check what browser they are using?

**Comment by JoshWho** [comment]
Chrome Brave OPera Firefox Waterfox Edge and a few others

**Comment by JoshWho** [comment]
Or everyone just happens to have the same antivirus and it is stopping them or something

**Comment by DanielnetoDotCom** [comment]
No idea then. the antivirus may be something 

the only thing that changed was this 

https://github.com/WWBN/AVideo/blob/0e299f7166f2e79f7639bb58a05073d06641269f/objects/include_config.php#L42-L45

https://stackoverflow.com/a/138748/2478180

**Comment by JoshWho** [comment]
You think that would do it?

**Comment by DanielnetoDotCom** [comment]
I have no idea and I can see no relation. but you can try to delete those lines and see if changes something.

**Comment by DanielnetoDotCom** [comment]
also, you can ask them to force clear the cookies and see if something will change.

**Comment by JoshWho** [comment]
I am trying to get them all to to a password reset first. SOmething seems out of sync or something

**Comment by JoshWho** [comment]
That is not working. 1 user said it is like they are not even logged in once it loads. Totally keeps them as guest

**Comment by JoshWho** [comment]
Another one @DanielnetoDotCom  
![1b25643a-cf82-4fea-a3c1-b570743df57e](https://user-images.githubusercontent.com/39392449/215908391-8b355908-b01c-47e0-ba35-aa353ecbc950.png)

**Comment by JoshWho** [comment]
When trying to log in as him with admin It gave me this 

https://www.joshwhotv.com/?toast=You%20are%20user%3A%20Jay%20t%20Nygard

@DanielnetoDotCom

**Comment by JoshWho** [comment]
Usernames with spaces maybe?

**Comment by DanielnetoDotCom** [comment]
> When trying to log in as Jay Nygard with admin It gave me this
> 
> https://www.joshwhotv.com/?toast=You%20are%20user%3A%20Jay%20t%20Nygard
> 
> @DanielnetoDotCom
> 
> I think this is the bug


Why this is a bug?

**Comment by JoshWho** [comment]
It doesnt let me log in as him

**Comment by DanielnetoDotCom** [comment]
> Usernames with spaces maybe?

I do not think so, the user you sent to me for testing. does not have spaces

**Comment by JoshWho** [comment]
From the admin account try to login as Jay Nygard

**Comment by DanielnetoDotCom** [comment]
> It doesnt let me log in as him. It kicks me back to the home page like them

this maybe means something

**Comment by JoshWho** [comment]
> > It doesnt let me log in as him. It kicks me back to the home page like them
> 
> this maybe means something

Something to do with account session maybe Security or anything User Plugin

**Comment by DanielnetoDotCom** [comment]
this is what is weird

you have a lot of  `user::recreateLoginFromCookie: do cookie-login`

that means you have no user logged.

did you do some type of configuration you have made in your apache or PHP?

**Comment by JoshWho** [comment]
No not that I know of

**Comment by DanielnetoDotCom** [comment]
Looks like your sessions are not persistent. 

I will reboot your server now

**Comment by JoshWho** [comment]
> Looks like your sessions are not persistent.
> 
> I will reboot your server now

in PHP?

**Comment by JoshWho** [comment]
> Looks like your sessions are not persistent.
> 
> I will reboot your server now

So what would resolve this?

**Comment by JoshWho** [comment]
Ok I got that forced to www

**Comment by JoshWho** [comment]
What happened to the socket server user list?

**Comment by DanielnetoDotCom** [comment]
I sent you an update performance. this list will not be available anymore but the socket will run much better

**Comment by JoshWho** [comment]
> I sent you an update performance. this list will not be available anymore but the socket will run much better

Smoother is better thank you

**Comment by DanielnetoDotCom** [comment]
I have no idea what is happening in your server ...

in all my servers the session_id never changes. 

https://demo.avideo.com/plugin/CustomizeUser/swapUser.json.php?users_id=22

in your server, it is changing with every request.

https://www.joshwhotv.com/plugin/CustomizeUser/swapUser.json.php?users_id=22

Unless you find what is different in your server configuration I am afraid I cannot help you.

**Comment by JoshWho** [comment]
I think it is the www not being forced. I am waiting to hear back from one of them now

**Comment by JoshWho** [comment]
500 Error now @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Ok, what is weird is that your server does not persist the session, you always log in with cookies all the time.  this also overload your server.

if you do not check the "remember me" your login will not work


please also check your email

**Comment by JoshWho** [comment]
That is the 500 error page

**Comment by DanielnetoDotCom** [comment]
I guess I am locked out 

even this is crashing https://www.joshwhotv.com/t.php

![image](https://user-images.githubusercontent.com/18009293/215925147-9bd03cae-5eef-494f-aa0a-05cee8da21be.png)


I guess you changed something again, It is almost 11 pm here, and I cannot keep trying to find the error and face things like this.
I am about to go to sleep

**Comment by JoshWho** [comment]
The only thing I changed was forcing the www

**Comment by DanielnetoDotCom** [comment]
```
[Tue Jan 31 19:50:41.207834 2023] [:error] [pid 535] mod_qos(030): access denied, QS_SrvMaxConn rule: max=800, concurrent connections=801, c=108.162.241.132
[Tue Jan 31 19:50:48.773008 2023] [:error] [pid 570] mod_qos(030): access denied, QS_SrvMaxConn rule: max=800, concurrent connections=801, c=172.69.156.202
[Tue Jan 31 19:50:48.839702 2023] [:alert] [pid 493] mod_qos(035): QS_SrvMaxConn: no free IP slot available! Check log for unclean child exit and consider to do a graceful server restart if this condition persists.
[Tue Jan 31 19:50:48.839811 2023] [:error] [pid 493] mod_qos(030): access denied, QS_SrvMaxConn rule: max=800, concurrent connections=801, c=172.69.3.198
[Tue Jan 31 19:50:49.580378 2023] [:error] [pid 671] mod_qos(030): access denied, QS_SrvMaxConn rule: max=800, concurrent connections=801, c=172.70.131.58
```

I strongly recommend you uninstall all those fancy modules, they are making your life a lot harder.

**Comment by JoshWho** [comment]
I disable those and the problem still exist. It is not that

**Comment by DanielnetoDotCom** [comment]
I just remove the module qos and it is working again

**Comment by JoshWho** [comment]
I disabled the forced www

**Comment by JoshWho** [comment]
Can you lease set it in apache to force the www please @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
I had to do a lot of changes regarding the cookie and session domain.

I am not sure why this was happening to you. but now the cookie should work for www and  no www

I guess it will work now

**Comment by JoshWho** [comment]
Super sweet thank you. I will let you know how it works. You rock @DanielnetoDotCom

**Comment by JoshWho** [comment]
Socket server is not starting

**Comment by JoshWho** [comment]
Good news, they are all able to login again

**Comment by JoshWho** [comment]
Al looks good now. Thanks for fixing the socket server. Yay so glad this is all out of the way. Thank you all and @DanielnetoDotCom for being so speedy with this.
