### ISSUE TITLE
Are the video Keytags suppose to look like this?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7612]
![6afdba9b-a276-4fba-b3a0-dde249ed1466](https://user-images.githubusercontent.com/39392449/215942798-e21e512d-c7fc-47fd-b8d3-4d7fd69c1359.png)

**Comment by DanielnetoDotCom** [comment]
yes and no, 

I was not expecting large tags like that, but I will try to improve.

with this, you can subscribe to tags and also use them as a playlist.

and will get notified whenever a new video is added to the tag.

you also can disable it here 

![image](https://user-images.githubusercontent.com/18009293/216066137-84610677-a05a-4327-b0b4-9404176d470b.png)

**Comment by JoshWho** [comment]
That is pretty kewl. Kewl I like it.

**Comment by DanielnetoDotCom** [comment]
I just noticed I have some missing css and js files on the last update.

a git pull should fix this
