### ISSUE TITLE
php 7.2 still needed?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7615]
I am not sure why it is there but could be half the reason for things being slow.

![87911587-3c69-48ac-9730-209c02cee406](https://user-images.githubusercontent.com/39392449/216165294-6d34f9bf-df4d-41fb-b1c0-d40d3e52e3fd.png)

Do I need this php 7.2?

**Comment by JoshWho** [comment]
I even see a 7.3 running Not sure how any of that got added

**Comment by DanielnetoDotCom** [comment]
I recommend you to upgrade to php8x for performance proposes

**Comment by DanielnetoDotCom** [comment]
Any other php version is useless for me

**Comment by JoshWho** [comment]
I think I had it using 8, at the beginning but had to downgrade if I remember correctly.
