### ISSUE TITLE
after running the most recent Upgrade my site seems to be really slow now. I do not know what has changed

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7616]
Is there now more functions running or somthing from this latest upgrade. What is causing the slowness?

**Comment by DanielnetoDotCom** [comment]
It supposed to be faster

Where are you nothing the slowness?

**Comment by JoshWho** [comment]
Page loads sometimes the Plugin page hangs but Im not 100% sure it might been because of a attack at the moment because it seems fast now. I will close for now.
