### ISSUE TITLE
Problem with LoginLDAP after latest git pull

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7621]
I made a git pull on my fetube.flatearth.co.il site which is using the LDAP login plugin and now I get error 502 on the login url

https://fetube.flatearth.co.il/plugin/LoginLDAP/view/login.json.php

I cannot login anymore to that site, please check what changed and maybe the plugin needs an update im not sure if there is already one in the shop but I will check.

![Screen Shot 5783-05-11 at 19 14 13](https://user-images.githubusercontent.com/58882903/216395837-ecef10bc-faa3-416d-b6c7-6e1f19a53655.jpg)

**Comment by DanielnetoDotCom** [comment]
502 means Bad Gateway

probably something on your side, but check your logs

**Comment by KrzysioMisio** [comment]
[DanielnetoDotCom](https://github.com/DanielnetoDotCom)
I can't log in after the update either
![login](https://user-images.githubusercontent.com/93145787/216449444-f8dceec7-f684-4ed8-9cdb-eda955d8bba7.png)

**Comment by guymass** [comment]
Mainly what I see in debug log mode is the following repeating errors:

[Thu Feb 02 23:05:05.480044 2023] [authz_core:debug] [pid 3470910] mod_authz_core.c(817): [client 127.0.0.1:49446] AH01626: authorization result of Require all granted: granted, referer: https://alive528.com/
[Thu Feb 02 23:05:05.480080 2023] [authz_core:debug] [pid 3470910] mod_authz_core.c(817): [client 127.0.0.1:49446] AH01626: authorization result of <RequireAny>: granted, referer: https://alive528.com/
[Thu Feb 02 23:05:05.480149 2023] [authz_core:debug] [pid 3470910] mod_authz_core.c(817): [client 127.0.0.1:49446] AH01626: authorization result of Require all granted: granted, referer: https://alive528.com/
[Thu Feb 02 23:05:05.480155 2023] [authz_core:debug] [pid 3470910] mod_authz_core.c(817): [client 127.0.0.1:49446] AH01626: authorization result of <RequireAny>: granted, referer: https://alive528.com/
[Thu Feb 02 23:05:07.569726 2023] [proxy:debug] [pid 3471826] proxy_util.c(1931): AH00924: worker ws://127.0.0.1:8888/ shared already initialized
[Thu Feb 02 23:05:07.569744 2023] [proxy:debug] [pid 3471826] proxy_util.c(1988): AH00926: worker ws://127.0.0.1:8888/ local already initialized
[Thu Feb 02 23:05:07.569749 2023] [proxy:debug] [pid 3471826] proxy_util.c(1931): AH00924: worker ws://127.0.0.1:8888/ shared already initialized
[Thu Feb 02 23:05:07.569753 2023] [proxy:debug] [pid 3471826] proxy_util.c(1988): AH00926: worker ws://127.0.0.1:8888/ local already initialized
[Thu Feb 02 23:05:07.797232 2023] [authz_core:debug] [pid 3470904] mod_authz_core.c(817): [client 127.0.0.1:49454] AH01626: authorization result of Require all granted: granted, referer: https://encoder.alive528.com/
[Thu Feb 02 23:05:07.797259 2023] [authz_core:debug] [pid 3470904] mod_authz_core.c(817): [client 127.0.0.1:49454] AH01626: authorization result of <RequireAny>: granted, referer: https://encoder.alive528.com/
[Thu Feb 02 23:05:07.797324 2023] [authz_core:debug] [pid 3470904] mod_authz_core.c(817): [client 127.0.0.1:49454] AH01626: authorization result of Require all granted: granted, referer: https://encoder.alive528.com/
[Thu Feb 02 23:05:07.797334 2023] [authz_core:debug] [pid 3470904] mod_authz_core.c(817): [client 127.0.0.1:49454] AH01626: authorization result of <RequireAny>: granted, referer: https://encoder.alive528.com/
[Thu Feb 02 23:05:08.573233 2023] [proxy:debug] [pid 3471835] proxy_util.c(1931): AH00924: worker ws://127.0.0.1:8888/ shared already initialized
[Thu Feb 02 23:05:08.573252 2023] [proxy:debug] [pid 3471835] proxy_util.c(1988): AH00926: worker ws://127.0.0.1:8888/ local already initialized
[Thu Feb 02 23:05:08.573258 2023] [proxy:debug] [pid 3471835] proxy_util.c(1931): AH00924: worker ws://127.0.0.1:8888/ shared already initialized
[Thu Feb 02 23:05:08.573262 2023] [proxy:debug] [pid 3471835] proxy_util.c(1988): AH00926: worker ws://127.0.0.1:8888/ local already initialized
[Thu Feb 02 23:05:08.574226 2023] [proxy:debug] [pid 3471836] proxy_util.c(1931): AH00924: worker ws://127.0.0.1:8888/ shared already initialized

**Comment by DanielnetoDotCom** [comment]
avideo.log please

**Comment by KrzysioMisio** [comment]
` [02-Feb-2023 21:02:54 UTC] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in \/var\/www\/html\/hippo\/objects\/user.php:1145\nStack trace:\n#0 \/var\/www\/html\/hippo\/objects\/user.php(1145): property_exists()\n#1 \/var\/www\/html\/hippo\/objects\/user.php(1013): User->setLastLogin()\n#2 \/var\/www\/html\/hippo\/objects\/user.php(2710): User->login()\n#3 \/var\/www\/html\/hippo\/plugin\/Live\/Live.php(15): User::loginFromRequest()\n#4 \/var\/www\/html\/hippo\/plugin\/AVideoPlugin.php(304): require_once('...')\n#5 \/var\/www\/html\/hippo\/plugin\/Plugin.abstract.php(138): AVideoPlugin::loadPlugin()\n#6 \/var\/www\/html\/hippo\/plugin\/AVideoPlugin.php(412): PluginAbstract->getDataObject()\n#7 \/var\/www\/html\/hippo\/plugin\/AVideoPlugin.php(382): AVideoPlugin::getDataObject()\n#8 \/var\/www\/html\/hippo\/plugin\/AVideoPlugin.php(436): AVideoPlugin::getObjectData()\n#9 \/var\/www\/html\/hippo\/locale\/function.php(121): AVideoPlugin::getDataObjectIfEnabled()\n#10 \/var\/www\/html\/hippo\/objects\/include_config.php(170): setSiteLang()\n#11 \/var\/www\/html\/hippo\/videos\/configuration.php(47): require_once('...')\n#12 \/var\/www\/html\/hippo\/objects\/login.json.php(8): require_once('...')\n#13 {main}\n  thrown","file":"\/var\/www\/html\/hippo\/objects\/user.php","line":1145} SCRIPT_NAME: /objects/login.json.php`

**Comment by DanielnetoDotCom** [comment]
@KrzysioMisio you need to make a git pull, your files are outdated

**Comment by guymass** [comment]
or should I make hard rest? My only problem is this file:

-rw-r--r-- 1 www-data www-data 14177 Nov 19 17:55 /var/www/html/YouPHPTube/plugin/LoginLDAP/view/login.json.php

**Comment by DanielnetoDotCom** [comment]
@guymass you need to provide the correct log

**Comment by guymass** [comment]
I see this in avideo.log:

**Comment by DanielnetoDotCom** [comment]
see what?

> I see this in avideo.log:

**Comment by DanielnetoDotCom** [comment]
Your log seems to be fine, you need to investigate the error 502 in your side

**Comment by guymass** [comment]
I don't understand what you mean when you say on my side? Do you mean on the server side apache/nginx?
are the permission on this file correct?
-rw-r--r-- 1 www-data www-data 14177 Nov 19 17:55 /var/www/html/YouPHPTube/plugin/LoginLDAP/view/login.json.php

I am fully updated git pull wise and I hard reset the master branch, I never had any logging issues until the git pull today.
My configuration files haven't change since the start, nothing else was updated, just a simple git pull. This is a problem loading this login.json.php file. so what could be going on?

**Comment by DanielnetoDotCom** [comment]
502 is not an apache code error, it seems to be a proxy error

FYI a PHP error is code 500, anything else is not PHP

**Comment by guymass** [comment]
No, that didn't do anything.

**Comment by DanielnetoDotCom** [comment]
So check you proxy, on your internal configuration I cannot help you much

**Comment by guymass** [comment]
I am still investigating, could these errors have anything to do with my issue? What are those errors indicating?
![Screen Shot 5783-05-12 at 8 50 39](https://user-images.githubusercontent.com/58882903/216531974-82885ae1-a0d0-479e-884c-35553c911f63.jpg)

**Comment by guymass** [comment]
This is from the apache error log of the site:

![Screen Shot 5783-05-12 at 8 57 54](https://user-images.githubusercontent.com/58882903/216533157-78656eb2-07f9-4e7e-befb-2dff7fbdd23b.jpg)

**Comment by DanielnetoDotCom** [comment]
Yes, this seems to be the issue. but again, this is your server issue. not a code issue.

Also, I do not update the LDAP for a while.

**Comment by guymass** [comment]
OK I fixed it by adding to my server block of the virtual host for the nginx server the followings:

 proxy_busy_buffers_size   512k;
 proxy_buffers   4 512k;
 proxy_buffer_size   256k;
 
 This solved my issue and now I can finally log in.
