### ISSUE TITLE
Why my  Live Stream is displaying an OFFLINE preview image

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7627]
Whenever I start my live stream I see that It show this offline image, it only happens to my channel as far as I can tell or that other channel's just set their preview image, but I don't, I expect the live stream to produce a preview or that the ONLINE image will be showing up. Can you please tell me what I need to check or why this issue might happen.

![Screen Shot 5783-05-13 at 15 30 32](https://user-images.githubusercontent.com/58882903/216770477-12365024-9b71-49a5-81a1-7e82b0a5f20d.jpg)

**Comment by guymass** [comment]
OK, I was running a very long test stream of several hours to test the time limit. On the first part it only showed me as OFFLINE however once the stream reached the limit and a post was created, my stream was still continuing creating a part 2, and only than did the preview image was showing like the following screenshot:

![Screen Shot 5783-05-13 at 18 14 14](https://user-images.githubusercontent.com/58882903/216778053-02563319-de4d-440a-be98-ccca70d82c3d.jpg)

So currently i am not sure why its behaving like this, any suggestions?

**Comment by guymass** [comment]
And not its showing both:
![Screen Shot 5783-05-13 at 18 18 49](https://user-images.githubusercontent.com/58882903/216778116-9a016403-1fc6-474e-bf18-1847692286ce.jpg)

**Comment by guymass** [comment]
OK eventually I stopped my long live stream and the second part is not being encoded and I think its just lost, I don't know where it went as it is not appearing on my video list.

**Comment by guymass** [comment]
I still have files under my stream key folder under /HLS/live, I think those are my part 2 of the stream, no? Is there a way to reencode them again?

![Screen Shot 5783-05-13 at 19 26 19](https://user-images.githubusercontent.com/58882903/216781102-44b5083d-88ce-42be-9cc1-0c166b750f41.jpg)

**Comment by DanielnetoDotCom** [comment]
the false offline image is something that I am also facing.

I still do not have a final solution for it

**Comment by guymass** [comment]
Well wish I could help you there buddy, but idk how you programmed it. I will close that for now and hope you will find a solution in one of the updates. Maybe try to use ChatGPT :-)
