### ISSUE TITLE
Facebook URL encoding error

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7628]
I am getting errors when trying to import a url of a video from facebook, this also causes the encoder to hang after downloading the file I think. Here is a screen shot of the ffmpeg process showing an issue with FB url:

![Screen Shot 5783-05-13 at 21 17 42](https://user-images.githubusercontent.com/58882903/216785770-19cfa54c-3077-4b6e-a092-a8a4074b4b51.jpg)

**Comment by guymass** [comment]
So could this be a restream to FB?

**Comment by DanielnetoDotCom** [comment]
maybe yes

**Comment by guymass** [comment]
OK thanks, im closing this.
