### ISSUE TITLE
Import video, keep original creation date

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7631]
**Is your feature request related to a problem? Please describe.**
I am about to embark once more on importing a slew of podcasters videos.

My previous workflow has been to carefully note the date of each, and go and hand edit the database using sudo mysql. This is a very painful solution.

**Describe the solution you'd like**
A checkbox on import from a site "Keep original created date".

**Comment by DanielnetoDotCom** [comment]
Hi, do you mean the creation date from youtube?

**Comment by walt93** [comment]
Yes, or Rumble, or any other site. When I onboard a podcaster I want to grab a bunch of their existing media. It's important to keep the date for sorting videos.

**Comment by DanielnetoDotCom** [comment]
I may add this in the future, if you need an ETA you can sponsor this feature

if you are interested to sponsor it you can send me an email at developer@youphptube.com
