### ISSUE TITLE
 auto export

### ISSUE THREAD

**Issue by DittmerOk** [WWBN/AVideo#7640]
I want to ask a little strange question) Hmm .... is it possible to automatically upload files to the server? For example, when I have files on disk d, in the server folder. They must be uploaded to the server, every day at 6 am for example. How can this be implemented? As I understand it, it is necessary to write a script using the Ubuntu file system? All my videos are saved along the path AVideo / Avideo-Encoder / video. But then how to set, for example, the privacy of these videos?

**Comment by DanielnetoDotCom** [comment]
it is possible with a code (if you know how to do)

or you can use the [clone plugin](https://github.com/WWBN/AVideo/wiki/Clone-Site-Plugin)

**Comment by DittmerOk** [comment]
and through this plugin you can copy the data that is locally on the computer?
![1](https://user-images.githubusercontent.com/56869986/217477851-93149d29-ad42-4453-b4bc-d51197eb7b13.jpg)

**Comment by DanielnetoDotCom** [comment]
No, you cannot.

you are requesting a custom thing. 

I am not sure how to resolve it. but you probably can use the clone plugin to guide you in a coding solution.

BTW, I do not think you can do it in a windows computer

**Comment by walt93** [comment]
I would use python as it is a very easy scripting lanuguage to work with. You can use mysql connector, you can even get ChatGPT to code your access functions as long as you give it thorough descriptions.  ("Act as a backend developer. Write a python function to access a mysql database table named videos with a schema as: <paste the schema>." Literally tell it everything it needs to do & it will turn your english into Python code)

Start in mysql interactive mode and look at the videos schema. All you need to do is emulate that, and fill it with data.
