### ISSUE TITLE
SQL query asking for wrong field name

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#7642]
scheduler_commands.php:
line 82: $sql .= " AND (repeat_day_of_week IS NULL OR repeat_day_of_week = {$times['day_of_week']}) ";

from error log:
SELECT * FROM  scheduler_commands WHERE status='r'  AND (repeat_minute IS NULL OR repeat_minute = 4)  AND (repeat_hour IS NULL OR repeat_hour = 9)  AND (repeat_day_of_month IS NULL OR repeat_day_of_month = 7)  AND (repeat_month IS NULL OR repeat_month = 2)  AND (repeat_day_of_week IS NULL OR repeat_day_of_week = 2) \nError : (1054) Unknown column 'repeat_day_of_week' in 'where clause'

**Comment by DanielnetoDotCom** [comment]
Make sure you update it correctly.

the Scheduler plugin [version 3](https://github.com/WWBN/AVideo/blob/master/plugin/Scheduler/install/updateV3.0.sql) has this field 

FYI, we are in the version 4

**Comment by GreenDragonTavern** [comment]
Roger that and thank you.
