### ISSUE TITLE
Problem displaying videos after update 12.1 to 12.4

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7643]
@DanielnetoDotCom I don't know if this is a bug or some misconfiguration.

After I updated from version 12.1 to 12.4.
1- Bigvideo images and Bigvideo thumbnails are not displayed to users not logged in outside the group. (But the posters below are displayed).
2- After I login, Bigvideo images are displayed.
3- When I try to access the videos, they are not loaded. It loads infinitely and does not display any errors.

Watch the video:
https://vimeo.com/796880443

I thought this was a Linux file permissions error... but I've already revised and used the permissions in the "video" directory and its files and respective subdirectories:
```
sudo mkdir /var/www/html/AVideo/videos
sudo chmod -R 777 /var/www/html/AVideo/videos
sudo chown -R www-data:www-data /var/www/html/AVideo/videos
```

**Comment by DanielnetoDotCom** [comment]
check your log file

**Comment by gbrn** [comment]
The transfer of files from one server to the other server was done using the RSYNC command. So I ran the command again to verify and the result is that the files are all in sync.
Except for the .htaccess file I couldn't find in the 12.4 version directory.
![image](https://user-images.githubusercontent.com/37880073/217550045-2754cc40-0016-4d83-80c7-435c6f465010.png)

In the log, DEBUG informs that it is not finding the images in the directory "AVideo/videos/"
`[08-Feb-2023 12:08:33 America/Sao_Paulo] AVideoLog::DEBUG: Image not found for AVideo/videos/serie_playlists_609c6efecca69/serie_playlists_609c6efecca69_portrait_thumbsV2.jpg we are using /var/www/html/AVideo/videos/serie_playlists_609c6efecca69/serie_playlists_609c6efecca69_portrait.jpg instead  SCRIPT_NAME: /view/img/image404.php`

The correct is `AVideo/videos/` or `/var/www/html/AVideo/videos/` ?

**Comment by gbrn** [comment]
Apache is pointing to the correct directory:

```
<IfModule mod_ssl.c>
        <VirtualHost _default_:443>
                ServerAdmin webmaster@localhost
```

and

```
                DocumentRoot /var/www/html/AVideo
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/AVideo
```


The apache2.conf file has these settings:

```
<Directory />
        Options FollowSymLinks
        AllowOverride None
        Require all denied
</Directory>

<Directory /usr/share>
        AllowOverride None
        Require all granted
</Directory>

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
```


I must apply the settings informed here:
https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-22.x-for-AVideo-Platform-version-11.x-or-newer
It's a little confusing because apache is using more than one file for the settings.

**Comment by gbrn** [comment]
I applied the following lines... but I didn't see a difference:

```
<Directory /var/www/html/AVideo/>
        Options Indexes FollowSymLinks
        XSendFile on
        XSendFilePath /var/www/html/AVideo/
        AllowOverride All
        Require all granted
        Order Allow,Deny
        Allow from All
</Directory>
```
