### ISSUE TITLE
Server getting crushed by apache/youtube-dl - looking for a strategy

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7664]
**Describe the question**
Just noticed my disk was nearly full. Culprit is 100s of GB of mp4, jpg, webp and empty files in

/tmp/systemd-private-17857bf7db284c46a0599d8f80a1b2a5-apache2.service-cY8wIt/tmp

Just nuked like 800GB, but, this is my encoder box (24 core running 6 encoder processes) and it's going to fill up again. I guess I can crontab -e a rm *.mp4 in this directory every 4am though it's some hashed name and who knows when it changes.

Ideas?

-----

I came up with this, seems super sketch…

```
crontab -e
0 4 * * * root find /tmp/systemd-private-17857bf7db284c46a0599d8f80a1b2a5-apache2.service-cY8wIt -type f \( -name "*.mp4" -o -name "*.jpg" -o -name "*.webp" \) -delete
```

**Comment by DanielnetoDotCom** [comment]
/tmp/systemd-private* are apache files, I still did not find any way to clean it up, the only safe way that I know is rebooting the server.

where are you seeing the remaining mp4 files? what directory?

**Comment by walt93** [comment]
That's the exact directory Daniel. Something Apache is making up.

**Comment by DanielnetoDotCom** [comment]
I just create a script that will delete files that are 1 day old

```
cd /var/www/html/AVideo/install
php deleteSystemdPrivate.php 
```
