### ISSUE TITLE
Rendering glitch, videos->edit video->advanced->change owner

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7665]
**Describe the bug**
Rendering glitch.

**To Reproduce**
![Screen Shot 2023-02-13 at 8 18 14 PM](https://user-images.githubusercontent.com/11711050/218638342-d69598a4-a903-4e58-9710-8431ffeb26b3.png)

**Comment by DanielnetoDotCom** [comment]
Thanks for reporting that. 

this update may fix the issue, you may need to clear the site cache
