### ISSUE TITLE
VideoThumbnails

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#7674]
Latest update breaks VideoThumbails - A single thumbnail is displayed no matter where on progress bar. Image looks like a capture of first seconds but never updates and shows same image no matter where on progress bar. Uploaded multiple videos and all the same, image is of first second and that carries thru progress bar throughout.

![ProgressBar3](https://user-images.githubusercontent.com/85363361/219458229-c8a80b9e-ae4e-4966-ac42-eb7b83ad4cb8.jpg)
![ProgressBar4](https://user-images.githubusercontent.com/85363361/219458233-119767e4-a6b9-4099-915c-9c9a426d7102.jpg)
![ProgressBar1](https://user-images.githubusercontent.com/85363361/219458236-260686e6-4e1f-4f65-9cf0-071b86ae7790.jpg)
![ProgressBar2](https://user-images.githubusercontent.com/85363361/219458237-9c2f1b0b-7339-4f01-be9f-6af398d07727.jpg)

**Comment by GreenDragonTavern** [comment]
Uploaded a short video to your demo site (both mp4 and hls). Normal message on progress bar "Creating images. Please come back later" whereas mine has immediate single image right out of the shoot.

**Comment by DanielnetoDotCom** [comment]
please check this update

**Comment by GreenDragonTavern** [comment]
You be 'Da Man and thank you for prompt fix...
