### ISSUE TITLE
VR360 Plugin error since latest update

### ISSUE THREAD

**Issue by JSY-Ben** [WWBN/AVideo#7688]
Hi Daniel :) Thank you as ever for the great software.

Just a bug since the latest update. The error below appears when you click on a video. If I rename the 'VR360' folder in the Plugins folder to 'VideosVR360', the error goes away, but the plugin doesn't work. Any thoughts?

Many thanks :) Ben

`array(4) { ["type"]=> int(1) ["message"]=> string(343) "Uncaught Error: Class "VideosVR360" not found in /var/www/html/hightube.highlands.ac.uk/streamer/objects/functions.php:984 Stack trace: #0 /var/www/html/hightube.highlands.ac.uk/streamer/objects/video.php(3472): canUseCDN() #1 /var/www/html/hightube.highlands.ac.uk/streamer/view/modeYoutube.php(196): Video::getSourceFile() #2 {main} thrown" ["file"]=> string(69) "/var/www/html/hightube.highlands.ac.uk/streamer/objects/functions.php" ["line"]=> int(984) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(343) "Uncaught Error: Class "VideosVR360" not found in /var/www/html/hightube.highlands.ac.uk/streamer/objects/functions.php:984
Stack trace:
#0 /var/www/html/hightube.highlands.ac.uk/streamer/objects/video.php(3472): canUseCDN()
#1 /var/www/html/hightube.highlands.ac.uk/streamer/view/modeYoutube.php(196): Video::getSourceFile()
#2 {main}
  thrown"
  ["file"]=>
  string(69) "/var/www/html/hightube.highlands.ac.uk/streamer/objects/functions.php"
  ["line"]=>
  int(984)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avideoShutdown"
    ["args"]=>
    array(0) {
    }
  }
}`

**Comment by DanielnetoDotCom** [comment]
Please test this update

**Comment by JSY-Ben** [comment]
Amazing, thank you for such a quick response. Working perfectly now. Thanks again.
