### ISSUE TITLE
Public encoder youtube import stopped working

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7689]
after updating my encoders it does that same thing. there is something making the youtube importer to not work 

wwbn2 i think it was

**Comment by DanielnetoDotCom** [comment]
Please check this 

https://github.com/WWBN/AVideo/issues/7682#issuecomment-1434799136

**Comment by JoshWho** [comment]
THis is on your encoders I cant run that on there

**Comment by JoshWho** [comment]
![image_2023-02-23_05-40-51](https://user-images.githubusercontent.com/39392449/220830192-7d9181f2-20ce-4349-a08a-2f4fe81afa81.png)

I just repaired mine by upgrading the Python to the 3.7. You wwbn4 server is still doing that error

**Comment by DanielnetoDotCom** [comment]
what wwbn encoders are you seeing it?

I am not seeing any issue on them

**Comment by sysfu** [comment]
Verified this problem occurring with https://encoder4.wwbn.net/ too

**Comment by JoshWho** [comment]
I got mine fixed by upgrading python to 3.7 and then running the fix @DanielnetoDotCom suggested after https://github.com/WWBN/AVideo/issues/7682#issuecomment-1434799136

**Comment by JoshWho** [comment]
![image](https://user-images.githubusercontent.com/39392449/221322773-e17b7059-0977-43fb-b244-188247e2b963.png)

**Comment by DanielnetoDotCom** [comment]
What exactly link did you try?

Also please test it on demo site

**Comment by JoshWho** [comment]
He said it was a youtube link

**Comment by DanielnetoDotCom** [comment]
I have tested YouTube and it works 

I need to know what link exactly he tested

**Comment by sysfu** [comment]
> I have tested YouTube and it works
> 
> I need to know what link exactly he tested

https://www.youtube.com/watch?v=6WVVDWdTw3I

**Comment by JoshWho** [comment]
> > I have tested YouTube and it works
> > I need to know what link exactly he tested
> 
> https://www.youtube.com/watch?v=6WVVDWdTw3I

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/221325619-1c67813b-e485-40ee-9d46-f4150c69442e.png)

Just tested on demo and encoder4 

It is encoding now

**Comment by DanielnetoDotCom** [comment]
Btw no change

You should try yourself in your site

**Comment by DanielnetoDotCom** [comment]
Encode compete and it is working fine 

https://demo.avideo.com/v/399

**Comment by JoshWho** [comment]
yes it is working on my encoders as well.

**Comment by JoshWho** [comment]
Looks fixed to me

**Comment by sysfu** [comment]
Tested and confirmed working on encoder1.wwbn.net
