### ISSUE TITLE
how to limit avideo.log

### ISSUE THREAD

**Issue by karen20ced4** [WWBN/AVideo#7697]
Hello,
Is there any way to control avideo.log size ? or how many lines to keep, or limit to 2MB
1k lines would be sufficient to solve many of the problems. 
now my avideo.log file have 70mb

thanks

**Comment by DanielnetoDotCom** [comment]
you can use crontab for this

Create a shell script that compresses the log file using gzip. For example, create a file called `compress_logs.sh` with the following contents:
```
#!/bin/bash
gzip /var/www/html/AVideo/videos/avideo.log
```

This script uses the gzip command to compress the log file located at `/var/www/html/AVideo/videos/avideo.log`. Save the script in a location where the web server has permission to execute it, such as `/usr/local/bin/compress_logs.sh`.

Make the script executable by running the command `chmod +x /usr/local/bin/compress_logs.sh.`

Add an entry to the crontab file to run the script every day at a specified time. For example, to run the script every day at 4:30 AM, add the following line to the crontab file:

`30 4 * * * /usr/local/bin/compress_logs.sh`

This line specifies the minute and hour (30 and 4, respectively) to run the script, and the asterisks indicate that the script should run every day of the month, every month, and every day of the week.

Save and exit the crontab file.

The script will now run every day at the specified time, compressing the log file located at /var/www/html/AVideo/videos/avideo.log. You can adjust the script and the crontab entry as needed to suit your specific requirements, such as using a different compression tool or running the script at a different time.
