### ISSUE TITLE
security alert

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#7705]
Hi Daniel, I have these errors and security alert

`[22-Feb-2023 21:06:56 UTC] AVideoLog::SECURITY: ddosProtection:: progressive timeout timeoutReal = (5) active_connections = (40) maxCon = (40)  SCRIPT_NAME: /view/xsendfile.php`

`[22-Feb-2023 21:30:54 Europe/Warsaw] AVideoLog::ERROR: Id for table CachesInDB not defined for deletion [{"file":"\/var\/www\/html\/AVideo\/plugin\/Cache\/Cache.php","line":368,"function":"delete","class":"ObjectYPT","type":"->"},{"file":"\/var\/www\/html\/AVideo\/objects\/Object.php","line":572,"function":"getCache","class":"Cache","type":"::"},{"file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1556,"function":"getCache","class":"ObjectYPT","type":"::"},{"file":"\/var\/www\/html\/AVideo\/objects\/video.php","line":1528,"function":"getInfo","class":"Video","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/Gallery\/functions.php","line":85,"function":"getAllVideos","class":"Video","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/mainArea.php","line":89,"function":"createGallery"},{"file":"\/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/modeGallery.php","line":33,"args":["\/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/mainArea.php"],"function":"include"},{"file":"\/var\/www\/html\/AVideo\/view\/index_firstPage.php","line":58,"args":["\/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/modeGallery.php"],"function":"require"},{"file":"\/var\/www\/html\/AVideo\/view\/index.php","line":20,"args":["\/var\/www\/html\/AVideo\/view\/index_firstPage.php"],"function":"include"}] SCRIPT_NAME: /view/index.php`

**Comment by DanielnetoDotCom** [comment]
nothing to worry

**Comment by KrzysioMisio** [comment]
OK thanks
