### ISSUE TITLE
Playlist is missing its program ID 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7707]
I am looking at this after all the updates and now see the playlist bug on another account. THe PLaylist ID is missing

https://www.joshwhotv.com/channel/XylenRoberts

![download (20)](https://user-images.githubusercontent.com/39392449/220857831-0ddec54e-e26c-43d2-adec-3915ec11b13d.png)

They just have this as the link

https://www.joshwhotv.com/plugin/PlayLists/player.php?playlists_id=

**Comment by JoshWho** [comment]
https://www.joshwhotv.com/channel/XylenRoberts that channel click the programs tab and you will see when trying to play them

**Comment by GreenDragonTavern** [comment]
@DanielnetoDotCom, same thing happened here. Created a Series from Playlist. If I'm logged on as the creator of the Series/Playlist it works. If I'm any other user, it displays the end of link as @JoshWho states: ?playlists_id=

**Comment by DanielnetoDotCom** [comment]
It should be fixed now, thanks

**Comment by GreenDragonTavern** [comment]
That fixed the ?playlists_id= issue, thank you. Weird though, the playlist has 10 videos, created Series and it showed all 10 when created. When I go to view the series to play it only shows the last 6 in series. The first 4 are missing and the total series time only reflects the six, not the 10 videos in the playlist/series. When I click play, all 10 do show up.

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom working great now
