### ISSUE TITLE
2FA does it need a PGP key or is that Seperate?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7708]
![6ea581d2-0eeb-4758-be7b-1eb3e34999c4](https://user-images.githubusercontent.com/39392449/220871366-b81018af-61d2-46be-b7d1-5f92dd187db8.png)
![b3342502-5c0b-4fd9-a9d5-a24847d2063a](https://user-images.githubusercontent.com/39392449/220871396-21e9b0d4-1bdb-44b7-964b-12be6cb1f7d2.png)

**Comment by JoshWho** [comment]
I do not see a QR code generator for 2FA by itself.

**Comment by DanielnetoDotCom** [comment]
The 2FA is a email confirmation

any other ideas? what 2FA method do you use?

**Comment by JoshWho** [comment]
![c1100b76-73bb-4a3c-8281-ac6b7eea932d](https://user-images.githubusercontent.com/39392449/220909269-97699621-1f04-4457-bb02-93db5e93fd15.png)

https://stefansundin.github.io/2fa-qr/

**Comment by JoshWho** [comment]
I guess it is just a different type. I am just worried if the email doesn't work how would they get in.
