### ISSUE TITLE
Footer still high not sure if this was fixed

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7710]
https://www.joshwhotv.com/menu/faq
![bc6bd7c0-747e-4938-80cd-f7486b6cd520](https://user-images.githubusercontent.com/39392449/221104842-e3490c02-3031-466b-8f5e-143d9b311731.png)
https://www.joshwhotv.com/menu/faq

**Comment by DanielnetoDotCom** [comment]
The only solution I found was to remove the footer on these iframe pages

check now

**Comment by JoshWho** [comment]
Perfect. Thank you @DanielnetoDotCom
