### ISSUE TITLE
webrtc is not working

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7712]
The Go Live is offline again. Webrtc with Built in chat
![e63b062c-dd10-4834-b869-b7a130f96100](https://user-images.githubusercontent.com/39392449/221121225-b76e4710-b2d0-4e1f-8114-7c529b01fddc.png)

**Comment by DanielnetoDotCom** [comment]
It does not suppose to work.

I recommend you disable this feature in the Live plugin. this feature will be removed and replaced for another webrtc camera

**Comment by JoshWho** [comment]
It is a huge request right now. Any ETA when the new one will be available?

**Comment by DanielnetoDotCom** [comment]
Sorry but there is no eta for that 

It will be done , but it is not in the roadmap now

**Comment by JoshWho** [comment]
I have it disabled for now. I just wanted something to put in my blog for it. https://www.joshwhotv.net/one-click-go-live-is-being-redesigned-so-we-have-it-disabled-for-right-now/
