### ISSUE TITLE
Create Series from Playlist

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#7717]
**Describe the bug**

Creating Series does update database but no folder is created under videos directory. Replicated on Demo site. After manually creating proper folders, could update images for posters. In addition, only one series displays videos on program tab (created 3 series from playlists) and all have exact same time. That time is the total of the only series that shows videos (and that time is incorrect as it for some reason totals the six (6) videos shown when there are thirty videos in total). Creating Series is a little confusing too, seems like after creating it should leave the pop-up or at least say created but just stays there and if you click it again it asks if you want to delete...very confusing.

![Replicate-Demo-Site](https://user-images.githubusercontent.com/85363361/221381045-2b6c8904-dae4-4fd1-b8fb-64ae352cd1fc.jpg)

![Series-Display](https://user-images.githubusercontent.com/85363361/221381066-46b24e4e-f2cd-4c3e-aa95-9ae7319294ab.jpg)

**Comment by GreenDragonTavern** [comment]
Series when you activate as a video does work, it's the creating and displaying on channel that is out of wack.

![Series-As-Video](https://user-images.githubusercontent.com/85363361/221381477-8f4f876f-3da7-4c8d-adaf-b4a1ff4cbcc9.jpg)

**Comment by DanielnetoDotCom** [comment]
can you please try this update?

**Comment by GreenDragonTavern** [comment]
Thank you...that fixed creating directory under folders, and for Articles too. Attached screenshots question why length is included on Series (it's the same for every Series, on every Channel no matter the Series and isn't necessary to display). Also, suggestion on how Series should be displayed on Channel that makes more sense to user viewing Channel. Many thanks again for quick fix!

![Series1](https://user-images.githubusercontent.com/85363361/221428403-5c20582a-c8ba-4022-9e09-34f88bb64f15.jpg)

![Series2](https://user-images.githubusercontent.com/85363361/221428424-d0d3427c-cce6-44c4-b308-bbbbe31bcc90.jpg)

**Comment by DanielnetoDotCom** [comment]
do you mean to not show the episodes? only the main poster?

**Comment by GreenDragonTavern** [comment]
Here, two images, one is actual current display on channel (shows bogus total time, and poster). The second is what makes more sense (no time at all, and poster with video count which displays on gallery first page and is perfect).

![Channel-Is-Now](https://user-images.githubusercontent.com/85363361/221440212-30f2e3f4-294f-4b7c-bdfb-28e26a77c335.jpg)

![Channel-Should-Be](https://user-images.githubusercontent.com/85363361/221440246-323a4131-810b-4397-af57-d4d9753a5364.jpg)

Does this make sense?

**Comment by DanielnetoDotCom** [comment]
Understood, but the total time should be the total time of all videos together, is that not correct?

**Comment by DanielnetoDotCom** [comment]
thanks, I found some issues, here are some fixes

**Comment by GreenDragonTavern** [comment]
Top of the morning @DanielnetoDotCom. Change to Series poster with total number of videos is perfect on Channel, thank you.  Question for ya, why bother displaying any videos for a Series on Channel page? On to how you have it set up now:

None of Series here is six (6) videos, yet every Series, no matter the Channel, shows six (6) videos (all are more than six (6) here).   Regarding total time, the total time displayed is of the six (6) videos that are in fact displayed, not the Series itself.

To me a more simple and eloquent solution is for any Series on any channel is to show the poster as you now do (poster with total number of videos) and description, that's it. No need for total time, any individual videos nor anything else for that matter. It would be nice for the description to be limited to the height of the poster with a "Show More" button and when expanded, "Show Less". It's less overhead, allows multiple Series to be shown in a consistent format, height size on every Channel.

**Comment by DanielnetoDotCom** [comment]
This update may fix this issue

**Comment by DanielnetoDotCom** [comment]
for the videos total, I do not pretend to show more than 6.

to remove the complete row, for now you can only do it using a custom CSS

**Comment by GreenDragonTavern** [comment]
Roger that, and thanks for prompt updates!
