### ISSUE TITLE
Many bugs after updated to AVideo version 12.4 

### ISSUE THREAD

**Issue by sinaisinai** [WWBN/AVideo#7718]
Hi Daniel,
After update, video upload from file no longer works, embed video from youtube don`t import title, desc, thumbnail etc...
The live stream doesn't work. OBS can't connect to the server. Also when we go to the admin panel and click on dashboard, it takes 5 min to show content... Many bugs. What to to ?

![Capture d’écran 2023-02-26 à 00 01 33](https://user-images.githubusercontent.com/43705498/221385746-3d0e6557-133d-4790-a91e-7b46f00406fe.png)
![Capture d’écran 2023-02-26 à 00 02 31](https://user-images.githubusercontent.com/43705498/221385747-b13f6ad1-ac54-4f65-a827-6124ca064749.png)
![Capture d’écran 2023-02-26 à 00 04 14](https://user-images.githubusercontent.com/43705498/221385748-aff13063-6931-4d52-b2f3-e096737635eb.png)
![Capture d’écran 2023-02-26 à 00 16 45](https://user-images.githubusercontent.com/43705498/221385755-1d391d64-f438-4b84-a16c-ceed8b847445.png)

**Comment by DanielnetoDotCom** [comment]
looks to me your port 1935 is blocked

**Comment by sinaisinai** [comment]
> looks to me your port 1935 is blocked

![Capture d’écran 2023-02-26 à 01 45 13](https://user-images.githubusercontent.com/43705498/221386319-8f5b0a82-801f-46de-bd02-9574b5c34dc9.png)

**Comment by sinaisinai** [comment]
Everything worked. I just updated to the last version

**Comment by DanielnetoDotCom** [comment]
> > looks to me your port 1935 is blocked
> 
> ![Capture d’écran 2023-02-26 à 01 45 13](https://user-images.githubusercontent.com/43705498/221386319-8f5b0a82-801f-46de-bd02-9574b5c34dc9.png)

this does not mean it is unblocked.

if it has something to do with the update, MUST be something in the AVideo log

**Comment by sinaisinai** [comment]
Here is the log. I tried embed from youtube in first time, Then in second time I tried to upload a video from file:


![Capture d’écran 2023-02-26 à 03 02 40](https://user-images.githubusercontent.com/43705498/221388243-75d1ddf0-6a4f-428a-8330-2404c453ea67.png)

**Comment by DanielnetoDotCom** [comment]
I can only help you if you focus in 1 issue at a time 
You start this issue saying your live was not working 

Also your log is very incomplete 

If you really want help open one thread per issue 

For now I am totally lost of what you want

**Comment by sinaisinai** [comment]
Ok I will do that
