### ISSUE TITLE
Latest update broke videos category in my site

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#7720]
@DanielnetoDotCom I just updated my site and it was immediately broken by videos category, please help fix this error. Please help it urgent sir.
![Screenshot (314)](https://user-images.githubusercontent.com/72950503/221412921-f62fcbd4-db08-4ca3-a02e-880883ec3125.png)

**Comment by mrgodgiven** [comment]
![Screenshot (316)](https://user-images.githubusercontent.com/72950503/221413061-c0d47e2d-53c2-488d-92bf-cb5c3bec3463.png)

**Comment by DanielnetoDotCom** [comment]
can you please check this udpate?

**Comment by mrgodgiven** [comment]
ok. thanks, Problem solved
