### ISSUE TITLE
red progress bar

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#7732]
I reported it to AVideo-Encoder but you didn't respond
new encoder installation
red progress bar is missing

![progress](https://user-images.githubusercontent.com/93145787/221936423-73771690-30e9-4d80-993a-23e157d1cde0.png)

**Comment by DanielnetoDotCom** [comment]
For some reason, I can see it on my side.

Anyway, I am sending some updates regarding the progress bar

**Comment by KrzysioMisio** [comment]
the fix doesn't work

![progress](https://user-images.githubusercontent.com/93145787/222273747-b372ccd5-6a00-41aa-ba21-1ec4831deb7d.png)

**Comment by DanielnetoDotCom** [comment]
I just tested from my side and it is all working fine.

**Comment by KrzysioMisio** [comment]
then why isn't it working for me?
i have a fresh install, latest files from the repository and it's not working
If I upload an old copy of files from 2 weeks ago it works fine
It doesn't work in your demo either, change the theme to e.g. Slate

**Comment by DanielnetoDotCom** [comment]
Can you please check the public encoders?

for example https://encoder4.wwbn.net/

also please describe exactly what steps you are taking

**Comment by KrzysioMisio** [comment]
i made changes and the progress bar is back
Your html editor is adding white space
Somewhere else there is a problem with css because the progress bar was red and now it's green

**Comment by DanielnetoDotCom** [comment]
it is not a problem. if the download is complete it will turn green

**Comment by KrzysioMisio** [comment]
did you change the colors??
where it was green is now grey
where it was red is now green

![progress](https://user-images.githubusercontent.com/93145787/222747825-3c187a80-7b4a-4015-859e-ae460b715544.png)

**Comment by DanielnetoDotCom** [comment]
the color is based on your streamer template.

and yes, the colors were changed, when it is complete it will change to success.

**Comment by KrzysioMisio** [comment]
does not turn green when the download is complete
on the public encoder as well as mine


https://user-images.githubusercontent.com/93145787/222768762-80939e9f-eae3-437f-a0ec-08d6a591293c.mp4

**Comment by DanielnetoDotCom** [comment]
> Can you please check the public encoders?
> 
> for example https://encoder4.wwbn.net/
> 
> also please describe exactly what steps you are taking

here

**Comment by KrzysioMisio** [comment]
this video above is from public encoder
is this progress bar supposed to turn green after downloading  ??

**Comment by KrzysioMisio** [comment]
download video from public encoder

https://user-images.githubusercontent.com/93145787/222800549-efc86ec1-f1ea-4fa7-8cbe-6516ef1e7f3d.mp4

**Comment by DanielnetoDotCom** [comment]
I still do not see any issue.
