### ISSUE TITLE
My Videos - Source files

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#7735]
**Describe the bug**
Upload video with non-standard resolution; in this case 512x384. My setup on Encoder is 480p, 720p and 1080p. Using dynamic mp4 I'm thinking it will encode video at 720x480 (nearest resolution defined) when in fact encodes at native resolution. Which is all well and good. Go to My Videos, Source files and get a *404*. Replicated on AVideo demo site and screenshots are attached below. On my server changed videos table, externalOptions field from "HigestResolution":384 to *"HigestResolution":480* and renamed actual mp4 to ..._*480.mp4* and Source files actually displays location on server.

**To Reproduce**
demo.avideo.com - video name "Test of Source in All Videos" replicates error.

![Source-Files-Error1](https://user-images.githubusercontent.com/85363361/222269577-1a9a5a63-7bc5-40b3-a38d-c7df03331d4b.jpg)

![Source-Files-Error2](https://user-images.githubusercontent.com/85363361/222269616-4b190da6-0317-493b-bf95-598983fb5a59.jpg)

**Comment by DanielnetoDotCom** [comment]
can you please share the source file ?

the demo site is probably gone by now

**Comment by GreenDragonTavern** [comment]
Good morning, and you don't need the actual file.

240p, 360p, 480p, 540p, 720p, 1080p, 1440p, 2160p are available in AVideo.
Encoder has 480p, 720p, 1080p checked off as resolutions I want ffmpeg to create for the system. 

Let's say we encode an mp4 that has a resolution of 1920x800...results are 1152x480 and 1728x720. Exactly what you'd expect, matching resolutions that are selected for system and precise ratio as original mp4. Source files show up properly in AVideo, My Videos, Source files for this encoded video.

Now, encode an mp4 with a resolution of 512x384. I don't have 240p nor 360p selected, if they were this issue would not arise as the encoder would create an mp4 of 320x240 and or 480x360. What it does encode is a single mp4 as is; 512x384.

The bug in displaying sources is that the array of files the code is looking for is limited to exactly: 240p, 360p, 480p, 540p, 720p, 1080p, 1440p, 2160p. Any video outside those bounds will error out.

**Comment by DanielnetoDotCom** [comment]
for now videos that are not in standard size/resolution are unpredictable

**Comment by GreenDragonTavern** [comment]
https://tube.ofneco.com/upload/Jefferson1.avi

**Comment by DanielnetoDotCom** [comment]
With HLS format and works fine

![image](https://user-images.githubusercontent.com/18009293/222520585-5cac132b-7164-4678-bb0d-16559ba1d79b.png)

Trying now with MP4

**Comment by GreenDragonTavern** [comment]
It was ***Never*** about video encoding, playing...all of these avi files have played fine. The bug is ***Source files*** on My Videos page. My first screenshot of your demo site is in My Videos, on the right side I moved the mouse as to highlight ***Source files*** and then clicked it. The second (2nd) screenshot is net result. There's a bug in how AVideo displays actual files residing on disk for a particular video if they are encoded in a resolution not ending in 240p, 360p, 480p, 540p, 720p, 1080p, 1440p, or 2160p.

**Comment by DanielnetoDotCom** [comment]
Try this update

**Comment by GreenDragonTavern** [comment]
That did it, and thank you for all your efforts here!
