### ISSUE TITLE
In standard theme the way videos appear in each category

### ISSUE THREAD

**Issue by pegases-Marie-Galante** [WWBN/AVideo#7737]
I used to work with nextflix thème but now I am using the standard one. My problem is that I do not know how to define the way videos appear in each category. As far as I can see it looks like random. I wish I could sort them one wqy or another (most seen or at least chronologic). Thanks for you advices.

**Comment by walt93** [comment]
Everything is chronological by "created" date.

```
# From your server
sudo mysql

# From the mysql command line
show databases;
use my_avideo_database;  
select id,title,created from videos;
update videos set created = "01/01/1901" where id = 1234;  
etc… 
```

HTH

**Comment by pegases-Marie-Galante** [comment]
thanks, it should be but in my categories it is not the case. For instance the videos of a specific category 
![image](https://user-images.githubusercontent.com/126733533/222312315-3deea079-ccf7-4a77-8828-9a07210710c0.png)

**Comment by DanielnetoDotCom** [comment]
Check for the dateAdded, it will appear as the latest first

![image](https://user-images.githubusercontent.com/18009293/222419719-82a50bc1-83e5-4777-bb9d-43d933d420c6.png)

**Comment by pegases-Marie-Galante** [comment]
thanks again. the issue is that I do not use the gallery theme but right now the default one. May I put these options directly in the customized plugin (via Code directly) ? anyway I will try and let you know. thanks for your suggestion.

**Comment by DanielnetoDotCom** [comment]
I guess you are writing the same thing in 2 different issues, I will close this one

https://github.com/WWBN/AVideo/issues/7438
