### ISSUE TITLE
Live Streams Always showing? 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7745]
Not sure what is causing this on this page https://www.joshwhotv.com/live/

This is that same glitch I said last week
![106e7800-8fed-419d-8a7c-f0f889dc0376](https://user-images.githubusercontent.com/39392449/222873525-47a3a914-d035-4ce8-ae90-bd5a12dd8aad.png)

**Comment by DanielnetoDotCom** [comment]
Hi

I am confused, what I can see is different ...

![image](https://user-images.githubusercontent.com/18009293/222897629-03d36593-7abe-4f72-b466-f1b831e718ab.png)

I can see most of them are lives, and looks like they are scheduled to happen.

Looks strange to me but what exactly is the glitch?

**Comment by DanielnetoDotCom** [comment]
Regarding the restream, you can see the test date on each, are you sure your users did not click on the test button?

**Comment by JoshWho** [comment]
I am sure they did not. This happens in the middle of the night sometimes when no one is streaming

**Comment by DanielnetoDotCom** [comment]
I am sorry for what happened. 

 this is weird, and your users may need to add the titles again. also also I may need to put a trigger in the code to detect when they change or click in the restream test. 

currently, I have no idea how this happens.

**Comment by JoshWho** [comment]
hmmm.   I will keep any eye on it

**Comment by JoshWho** [comment]
![995bbeb1-9f39-4ca4-9186-d5a966ae9ad7](https://user-images.githubusercontent.com/39392449/223294688-d7371cbc-296a-4076-9c2a-57662a1478dd.png)
 Some of these that say COming soon show they are a week old

**Comment by DanielnetoDotCom** [comment]
Also when you request all restreams it will NOT list the tests

**Comment by JoshWho** [comment]
Thank you YOu ROck @DanielnetoDotCom

**Comment by JoshWho** [comment]
Should the streams eventually disappear on that page? I still see the old one

**Comment by GreenDragonTavern** [comment]
@JoshWho - same here. When ***Live** ends should be removed immediately from front page and notification bell. Right now it hangs around like a neighbor, too long.

**Comment by DanielnetoDotCom** [comment]
> @JoshWho - same here. When _**Live**_ ends should be removed immediately from front page and notification bell. Right now it hangs around like a neighbor, too long.

your problem is probably the socket, @JoshWho issue is something else.

**Comment by DanielnetoDotCom** [comment]
> Should the streams eventually disappear on that page? I still see the old one

please try this update and clear the cache

**Comment by GreenDragonTavern** [comment]
> please try this update and clear the cache

That did it here...socket was already up to snuff, it was update that solved issue...thank you!

**Comment by JoshWho** [comment]
Mine haven't changed.  This stream still shows it is live https://www.joshwhotv.com/live/1/Fallbackusa

**Comment by GreenDragonTavern** [comment]
@JoshWho - I spoke too soon. Just tested two sites and yes, it never leaves front page, nor notification bell.

**Comment by GreenDragonTavern** [comment]
@JoshWho - quick question, are you using adaptive streaming?

**Comment by JoshWho** [comment]
> @JoshWho - quick question, are you using adaptive streaming?

nope just the raw format

**Comment by GreenDragonTavern** [comment]
> nope just the raw format

Roger that, I am, so behavior is consistent no matter how we're streaming.

**Comment by DanielnetoDotCom** [comment]
@GreenDragonTavern you MUST check your Streamer logs when you finish the stream, you may have some on_publish_done and on_record_done

@JoshWho I just checked your site and I cannot see the restream titles anymore. you MUSt rename the lives to its default text, and if it happens again we have some triggers in the code to catch where it comes from.

**Comment by JoshWho** [comment]
> @GreenDragonTavern you MUST check your Streamer logs when you finish the stream, you may have some on_publish_done and on_record_done
> 
> @JoshWho I just checked your site and I cannot see the restream titles anymore. you MUSt rename the lives to its default text, and if it happens again we have some triggers in the code to catch where it comes from.

I am not sure what you mean. HOw do they re name it all?

**Comment by DanielnetoDotCom** [comment]
Hi, I mean if there is some live that is supposed to appear and it is not appearing is because has the title "restream test..."

to make it appear again, just rename it.

If the title "restream test" appear again we may find some clue in the log file

**Comment by GreenDragonTavern** [comment]
@DanielnetoDotCom - sorry for delay, life got in the way past couple days. I have had to manually update the table: ***live_transmissions_history***, field: ***finished*** and then Clear First Page Cache - Clear Cache Directory for it to go away on Front Page. The actual live stream shows fine in AVideo, and records properly after completion. Just never leaves the Front Page...
```
[10-Mar-2023 13:02:16 America/Los_Angeles] AVideoLog::DEBUG: rrmdir: could not delete folder /var/www/html/AVideo/OFN-Eco/videos/cache/YPTObjectCache/firstpage/ SCRIPT_NAME: /plugin/Live/on_publish_done.php

[10-Mar-2023 13:02:16 America/Los_Angeles] PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/AVideo/OFN-Eco/plugin/Live/on_publish_done.php on line 63
[10-Mar-2023 13:02:16 America/Los_Angeles] PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/AVideo/OFN-Eco/plugin/Live/on_publish_done.php on line 64
[10-Mar-2023 13:02:16 America/Los_Angeles] PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/AVideo/OFN-Eco/plugin/Live/on_publish_done.php on line 64
[10-Mar-2023 13:02:16 America/Los_Angeles] PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/AVideo/OFN-Eco/plugin/Live/on_publish_done.php on line 64
[10-Mar-2023 13:02:16 America/Los_Angeles] AVideoLog::DEBUG: NGINX ON Publish Done finishFromTransmitionHistoryId XXXXXXXXXXXXX-X id= key= live_servers_id= insert_row= SCRIPT_NAME: /plugin/Live/on_publish_done.php
[10-Mar-2023 13:02:16 America/Los_Angeles] PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/AVideo/OFN-Eco/plugin/Live/on_publish_done.php on line 65
```
![finished-filed-never-updated](https://user-images.githubusercontent.com/85363361/224438385-b387e70b-c871-45bd-9365-ec1050c9065b.jpg)

**Comment by DanielnetoDotCom** [comment]
@GreenDragonTavern, thank you for reaching out to me. However, I cannot continue to assist you without the necessary information. Also, please note that the issue at hand is not related to your comments. For me to better assist you, kindly provide the requested information and open a new issue. If the required information is not provided, I regret to inform you that I will not be able to offer further assistance. Thank you for your understanding
