### ISSUE TITLE
Emails Not Working.. Since Upgraded

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#7765]
Hi 

My smtp email is not working now since I upgraded the system recently. 
  Cannot see any log errors for it. 
Trying test email in Site settings in Advance Configuration, comes up with the following:-
============================
Message could not be sent (SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/TroubleshootingSMTP server error: Failed to connect to server SMTP code: 110 Additional SMTP info: Connection timed out)
===========================
I'm sure I had this some time ago, not sure how to rectify.

Please advise.

**Comment by DanielnetoDotCom** [comment]
check your smtp side, sorry but this has nothing to do with the update

**Comment by kollossus55** [comment]
ok.. I have changed the smtp to gmail and the user email to gmail account, but I'm getting the following:-
==========================
Your message could not be sent!
Message could not be sent (The following From address failed: admin@kollossusgroup.com : MAIL FROM command failed,Authentication Required. Learn more at https://support.google.com/mail/?p=WantAuthError g11-20020a05600c310b00b003eb68bb61c8sm1763wmo.3 - gsmtp ,530,5.7.0SMTP server error: MAIL FROM command failed Detail: Authentication Required. Learn more at https://support.google.com/mail/?p=WantAuthError g11-20020a05600c310b00b003eb68bb61c8sm1763wmo.3 - gsmtp SMTP code: 530 Additional SMTP info: 5.7.0SMTP server error: MAIL FROM command failed Detail: Authentication Required. Learn more at https://support.google.com/mail/?p=WantAuthError g11-20020a05600c310b00b003eb68bb61c8sm1763wmo.3 - gsmtp SMTP code: 530 Additional SMTP info: 5.7.0)
===============
what do I need to do?

**Comment by kollossus55** [comment]
Cleared cache.

Now I get -
===================
Your message could not be sent!
Your code is not valid
==================

**Comment by DanielnetoDotCom** [comment]
you really need to check your SMTP configuration

https://tutorials.avideo.com/video/82/setup-gmail-smtp-with-2fa
