### ISSUE TITLE
Socket not connecting after latest gitpull

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#7771]
@DanielnetoDotCom 
Unable to get my socket to work on the port that I had it working on prior to the gitpull error is port is busy  I tried default port and got the same error
12053, 2053

**Comment by milehighkaraoke** [comment]
This is what I get when I run command 
[1] 7161
![20230309_220755](https://user-images.githubusercontent.com/70327833/224228879-ea34fd86-ccd2-4c4a-bd64-7f2659d8d73a.jpg)

**Comment by milehighkaraoke** [comment]
OK, it looks like www got added here also but I do not see where to change it .As in the ypt plugin it is correct.
@DanielnetoDotCom do you know where I would change this value so my socket starts working again?

**Comment by milehighkaraoke** [comment]
@
![20230309_221925](https://user-images.githubusercontent.com/70327833/224230502-ba7eea12-0131-4522-a8a3-bf5c3bd7eac5.jpg)

**Comment by milehighkaraoke** [comment]
![Screenshot_20230309_221855_Chrome](https://user-images.githubusercontent.com/70327833/224230596-f7b9fd78-9a8d-4217-aae5-158c75c31d82.jpg)

**Comment by milehighkaraoke** [comment]
![Screenshot_20230309_224335_Chrome](https://user-images.githubusercontent.com/70327833/224233357-46ba9601-c032-457e-91d3-9ea6569c7572.jpg)

**Comment by milehighkaraoke** [comment]
![Screenshot_20230309_224504_Chrome](https://user-images.githubusercontent.com/70327833/224233886-d1eacb88-7cb9-421d-9ae5-671ac00afa07.jpg)

**Comment by DanielnetoDotCom** [comment]
troubleshoot it: https://github.com/WWBN/AVideo/wiki/Socket-Plugin#troubleshooting

**Comment by milehighkaraoke** [comment]
W8ke up this morning and it is now showing that it is connected
