### ISSUE TITLE
Website Down - MAin Page

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#7791]
Hi.. Website down with following error..

Was investigating smtp issuses. Updating Certbot,  then this happened?

Please advise..
==============================================

array(4) { ["type"]=> int(1) ["message"]=> string(1478) "Uncaught Error: Undefined constant ScssPhp\ScssPhp\Type::T_FUNCTION_REFERENCE in /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php:3946 Stack trace: #0 /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php(3669): ScssPhp\ScssPhp\Compiler->getFunctionReference() #1 /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php(3641): ScssPhp\ScssPhp\Compiler->fncall() #2 /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php(2979): ScssPhp\ScssPhp\Compiler->reduce() #3 /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php(2378): ScssPhp\ScssPhp\Compiler->compileChild() #4 /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php(744): ScssPhp\ScssPhp\Compiler->compileChildrenNoReturn() #5 /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php(522): ScssPhp\ScssPhp\Compiler->compileRoot() #6 /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php(444): ScssPhp\ScssPhp\Compiler->compileString() #7 /var/www/html/AVideo/plugin/Customize/sass/compile.php(22): ScssPhp\ScssPhp\Compiler->compile() #8 /var/www/html/AVideo/plugin/Customize/Customize.php(18) : eval()'d code(1) : eval()'d code(54): include('...') #9 /var/www/html/AVideo/plugin/AVideoPlugin.php(648): Customize->getStart() #10 /var/www/html/AVideo/objects/include_config.php(194): AVideoPlugin::getStart() #11 /var/www/html/AVideo/videos/configuration.php(47): require_once('...') #12 /var/www/html/AVideo/view/index.php(7): require_once('...') #13 {main} thrown" ["file"]=> string(60) "/var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php" ["line"]=> int(3946) }
array(4) {
  ["type"]=>
  int(1)
  ["message"]=>
  string(1478) "Uncaught Error: Undefined constant ScssPhp\ScssPhp\Type::T_FUNCTION_REFERENCE in /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php:3946
Stack trace:
#0 /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php(3669): ScssPhp\ScssPhp\Compiler->getFunctionReference()
#1 /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php(3641): ScssPhp\ScssPhp\Compiler->fncall()
#2 /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php(2979): ScssPhp\ScssPhp\Compiler->reduce()
#3 /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php(2378): ScssPhp\ScssPhp\Compiler->compileChild()
#4 /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php(744): ScssPhp\ScssPhp\Compiler->compileChildrenNoReturn()
#5 /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php(522): ScssPhp\ScssPhp\Compiler->compileRoot()
#6 /var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php(444): ScssPhp\ScssPhp\Compiler->compileString()
#7 /var/www/html/AVideo/plugin/Customize/sass/compile.php(22): ScssPhp\ScssPhp\Compiler->compile()
#8 /var/www/html/AVideo/plugin/Customize/Customize.php(18) : eval()'d code(1) : eval()'d code(54): include('...')
#9 /var/www/html/AVideo/plugin/AVideoPlugin.php(648): Customize->getStart()
#10 /var/www/html/AVideo/objects/include_config.php(194): AVideoPlugin::getStart()
#11 /var/www/html/AVideo/videos/configuration.php(47): require_once('...')
#12 /var/www/html/AVideo/view/index.php(7): require_once('...')
#13 {main}
  thrown"
  ["file"]=>
  string(60) "/var/www/html/AVideo/vendor/scssphp/scssphp/src/Compiler.php"
  ["line"]=>
  int(3946)
}
array(1) {
  [0]=>
  array(2) {
    ["function"]=>
    string(14) "avideoShutdown"
    ["args"]=>
    array(0) {
    }
  }
}

**Comment by DanielnetoDotCom** [comment]
I am not sure what is it, did you update with git pull?

**Comment by kollossus55** [comment]
just trying to restore it.. will run git pull also, see if it will work...

**Comment by kollossus55** [comment]
Hi 

Done restores and git pulls.. All good now.. Thanks...
