### ISSUE TITLE
Ansible installer.

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#7792]
**Is your feature request related to a problem? Please describe.**
Problem is that for some people it can be hard to install a basic youPHPtube. 
Great for testing purpose or initial install.
Spinning up test machines before upgrading to a newer version.

**Describe the solution you'd like**
I already created a set of installer files to install youPHPtube on Ubuntu 16.x 18.x 20.x and Centos. Ubuntu 22.x is on the roadmap.
It will install all needed packages for it and configures it to basic setup with Apache and SSL support.

**PRO**
Simple file to edit ( just need to add passes and locations for install)
Takes 5 minutes.
Ready to run.

**CON**
Can only be used on new environments.
Not tested yet when using it an a configured LAMP server.

**Additional context**
If developed further correctly it can also correct mistakes or wrong configured servers.
Fixing things like : 
write directory settings.
Missing packages.
Update packages.

**Your input**
I'm willing to publish it if people are interested. You need some knowledge of Ansible as it works perfect in mine lab not sure if it will on others.

**Comment by DanielnetoDotCom** [comment]
Thank you for your support and for sharing your solution to the installation issue of youPHPtube. I appreciate your effort in creating a set of installer files for Ubuntu and Centos (I am surprised it works with no problem). It seems like a very useful tool for quickly setting up a basic youPHPtube with Apache and SSL support.

If you decide to publish it, please let me know. I'm interested in learning more about it and potentially sharing it with our community. Thank you again for your contribution!

**Comment by ronaldod** [comment]
Will place it on gitlab later. As soon i tweaked the ytb-dl fix as i still installed it with pip and that gives as for i know only the old version and need to get the nightbuild to get it working.

The idea is to create one installer that detects the different types of OS and based on that it will install the correct apps and configuration. You only need a ssh key or account with sudo access. And it run everything remote. With one installer on a main server it will install everything as long you have ssh access and the server a clean install. As said not tested with other websites.
It pulls almost everything from the git and only pushes 2 templates like the apache conf.

Working as far now are: 
- Apache2
- Avideo
- Avideo encoder
- ssl with letsencrypt

Testing stage
- mariadb
- nginx

future
 - ngnix live stream
 - grafana
 - telegraf
 - influxdb

**Comment by DanielnetoDotCom** [comment]
Why are you using Centos instead of Ubuntu?

**Comment by ronaldod** [comment]
> Why are you using Centos instead of Ubuntu?

Just for fun not for a special purpose. And most all customers i have use RHEL so it also keeps me trained on this flavor of Linux.
