### ISSUE TITLE
Video file replay not working from server.

### ISSUE THREAD

**Issue by ronaldod** [WWBN/AVideo#7793]
**Describe the bug**
Clean website and uploading file with encoder. Video not playing. screenshots are working. Downloaded the video file to  the PC and it plays in the browsers and vlc

**To Reproduce**
1. new install
2. upload video with encoder
3. play the video
4. error in console  "VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. "
5. delivered file size is 0 bytes. 

**Expected behavior**
Playing video.

**Error Logs**
No error to be found in avideo/encoder and apache.

**Screenshots**
![image](https://user-images.githubusercontent.com/31585599/224788303-e364db9f-f4d1-4591-92f3-33668867aa4c.png)

**Server
- Ubuntu 20
- all installed with latest command. Not version specific.

**Desktop (please complete the following information):**
 - OS: win 11
 - Browser firefox,chrome and edge

**Additional context**
Fresh install nothing special. It is behind a ha proxy but also tested direct connection. No difference

**Comment by DanielnetoDotCom** [comment]
Check your health check also check if you install this

https://github.com/WWBN/AVideo/wiki/Install-Apache-XSendFIle

**Comment by ronaldod** [comment]
That was the fix.
