### ISSUE TITLE
Ban User doesn't Delete their Comments

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7800]
![14e5c013-4faa-411a-b3ed-0abc633cdafd](https://user-images.githubusercontent.com/39392449/225295198-4efb12f7-702f-4230-bfba-d9585277bed5.png)
![download (28)](https://user-images.githubusercontent.com/39392449/225295235-9b08ae95-ce4e-4f6a-bb2f-3b1c6b465b1e.png)
After I ban them I check to see if comment is still there and it is.

![last](https://user-images.githubusercontent.com/39392449/225295263-e42da6c9-c7d6-4dd5-834f-d4b8f985c28d.png)

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom
