### ISSUE TITLE
Layout trending cut off

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7802]
@DanielnetoDotCom Video descriptions are being cut off on the trending page.
I've seen this problem for a while now. I tried adjusting the browser's zoom, but it doesn't change anything.

![image](https://user-images.githubusercontent.com/37880073/225466940-c0358bb3-857e-4f62-9acc-cdbe02811bc9.png)

**Comment by DanielnetoDotCom** [comment]
check this update

**Comment by gbrn** [comment]
OK. It's correct now. Thanks.
