### ISSUE TITLE
Default incorrect language

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7822]
@DanielnetoDotCom Dani, I noticed that there is a problem on the demo site, which is present on my site. When I select the language, it does not change correctly and is displaying the default English language.

![image](https://user-images.githubusercontent.com/37880073/226487217-64e9cf08-0647-4b76-a181-4e74008b28a7.png)

![image](https://user-images.githubusercontent.com/37880073/226486935-63572ced-09a2-49c4-890c-40a68a81476f.png)

**Comment by DanielnetoDotCom** [comment]
here is working fine, tested on demo site

**Comment by palich91** [comment]
indeed, after the update, the translation stopped working correctly. I have a Russian icon and the translation is English

**Comment by gbrn** [comment]
@DanielnetoDotCom The problem exists, including the image above is on the demo site...
Watch this video I recorded on my platform.
The site is initially correct... but after login, the language is wrong, different from what is indicated.

https://user-images.githubusercontent.com/37880073/226978899-92b559db-0eaf-4c82-9160-cfdaa8520790.webm

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by gbrn** [comment]
@DanielnetoDotCom The problem is still present.
1- The default language is not correct.
2- After login, the defined language is reset on the next login.

Check video:
https://user-images.githubusercontent.com/37880073/227753723-6a6773fd-4b81-4d0c-8461-21de3e5d18a9.webm

I couldn't find any place to change the default language.

No errors are reported in the LOG.

**Comment by DanielnetoDotCom** [comment]
DId you make a git pull recently?

**Comment by gbrn** [comment]
@DanielnetoDotCom After the latest Git pull.... new test, check video.
The problem is the same.... Wrong default language.... After the user language is selected, the configuration is not returned on the new login.

https://user-images.githubusercontent.com/37880073/228017387-db091703-bd37-4edb-b804-406a6c05ecfe.webm

**Comment by gbrn** [comment]
Explain to me, how the platform defines the default language. Through IP? Any specific configuration?

**Comment by DanielnetoDotCom** [comment]
Check your user_location plugin

it depends, it can be thru the browser lang or IP, depending on what you configure

https://github.com/WWBN/AVideo/blob/a95b632bc4601372fb7c75d08a4e522ebc2b9fba/plugin/User_Location/User_Location.php#L102-L115

**Comment by gbrn** [comment]
The default language that always pops up for me is American English.

The _User_Location_ plugin is not enabled. This is optional, correct?
![image](https://user-images.githubusercontent.com/37880073/228092254-06dc979c-e4e4-4c66-b3f2-5621491eae12.png)

My ip is provided by TIM in Brazil.
![image](https://user-images.githubusercontent.com/37880073/228092719-b7d8c0d8-763f-44ff-bb10-938326237223.png)

My default language set in Chrome is Brazilian Portuguese (as I expect the platform to start).
![image](https://user-images.githubusercontent.com/37880073/228093475-0d30d5b9-f030-4970-a998-d4065fa359cc.png)

The Ubuntu server has the correct Timezone:
```
ubuntu@ubuntu-server-arm-02:~$ sudo cat /etc/timezone
America/Sao_Paulo
```

Git pull updated successfully:
```
ubuntu@ubuntu-server-arm-02:/var/www/html/AVideo$ sudo git pull
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 16 (delta 9), reused 15 (delta 8), pack-reused 0
Unpacking objects: 100% (16/16), 10.20 KiB | 474.00 KiB/s, done.
From https://github.com/WWBN/AVideo
   a95b632bc4..3343803cf0  master     -> origin/master
Updating a95b632bc4..3343803cf0
Fast-forward
 objects/functions.php | 3 +++
 view/modeYoutube.php  | 8 +++++---
 2 files changed, 8 insertions(+), 3 deletions(-)
```

Follow the new test, with the same result:
https://user-images.githubusercontent.com/37880073/228095532-2275a402-1e59-40c1-b0bc-61c3a3f05dee.webm


I don't know if there is anything else I can do to try to solve it.
Any additional configuration needed?

**Comment by DanielnetoDotCom** [comment]
You MUST enable the plugin

![image](https://user-images.githubusercontent.com/18009293/228213992-e5630467-7bf0-4150-aa22-94ba7e04da61.png)

**Comment by gbrn** [comment]
@DanielnetoDotCom This plugin was not enabled, as it was of no use to me yet and trying to reduce the amount of elements that could cause problems.

So I enabled the plugin now and the platform started to recognize my browser language.

Now I have a curiosity... in previous versions of the platform this plugin was not necessary to select the language. Previously was the browser language identified as the default, even without a plugin?

**Comment by DanielnetoDotCom** [comment]
this plugin was always required for language recognition

**Comment by gbrn** [comment]
@DanielnetoDotCom I found the problem again...
The flag shows the correct language, but the site is in English.
![image](https://user-images.githubusercontent.com/37880073/229360675-faea7999-03bc-406f-9693-03af65e56f28.png)

The current plugin settings are these:
![image](https://user-images.githubusercontent.com/37880073/229360905-082c9131-04de-41bb-bea8-214dce2d3c06.png)

**Comment by DanielnetoDotCom** [comment]
can you please make a git pull and try again?

**Comment by gbrn** [comment]
Updated and monitoring...

**Comment by gbrn** [comment]
Ok corrected!
