### ISSUE TITLE
Cache doesn't let go of embeded bad thumbnails from Rumble

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7823]
When you embed a video from Rumble sometimes the thumbnail will be black. If the user tries to update it, they never see a change until I purge the Avideo cache.

**Comment by DanielnetoDotCom** [comment]
can you please check if this update makes any difference?

**Comment by JoshWho** [comment]
It looks like that did the trick. Thank you @DanielnetoDotCom

**Comment by JoshWho** [comment]
I see it doing it again. I have to click clear site cache for it to release it for some reason

**Comment by JoshWho** [comment]
I wonder if it is possible to have like a default Rumble Logo thumb for bad rumble thumbs?   Just for the  Rumble embeds

**Comment by DanielnetoDotCom** [comment]
Hi, 

Rumble logo is not possible, but is is a bad thumbs or just a cache issue?

**Comment by JoshWho** [comment]
Might be both that cause one or the other. The bad thumb is the image that wont be released

**Comment by JoshWho** [comment]
> Hi,
> 
> Rumble logo is not possible, but is is a bad thumbs or just a cache issue?

I meant of serve a static file that can resemble the Rumble logo just to act as a filler for the dead thumbnail

**Comment by DanielnetoDotCom** [comment]
can you help me reproduce the issue?

what link should I test? please describe the steps

**Comment by JoshWho** [comment]
Here is one https://www.joshwhotv.com/video/.7Hvvdg/20-minutes-of-revelation---ep-01-last-days-wef-cbdc-apocalypse-end-times

**Comment by DanielnetoDotCom** [comment]
looks like it is an embedded video and the yt-dlp could not download the thumbnail, 

but did you manually update the thumbs ?

FYI, the image you see on your page is an image from your embed video, it is not possible to download it.

**Comment by JoshWho** [comment]
Rumbles static directory is this https://sp.rmbl.ws/s8/1/A/O/o/N/AOoNi.qR4e-small-Dr.-Fauci-is-just-as-evil-a.jpg

**Comment by DanielnetoDotCom** [comment]
this is something implemented in the yt-dlp 

but please check this encoder update and check if it makes any difference. 

but I guess, to test it, it will need to be a new video,

**Comment by JoshWho** [comment]
> this is something implemented in the yt-dlp
> 
> but please check this encoder update and check if it makes any difference.
> 
> but I guess, to test it, it will need to be a new video,

Try with this one https://rumble.com/v2dsace-debunking-cnn-again-with-their-j6-claims-they-are-really-desperate-lol.html

**Comment by DanielnetoDotCom** [comment]
Got it, update your streamer and you should be fine

**Comment by JoshWho** [comment]
> Got it, update your streamer and you should be fine

Thank you @DanielnetoDotCom  Perfect.
