### ISSUE TITLE
Fresh install of encoder cannot copy videos from YouTube

### ISSUE THREAD

**Issue by The-Do-It-Yourself-World** [WWBN/AVideo#7828]
I have set up a brand new server with a fresh install of the encoder using the instructions here: https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-AVideo-Platform-version-4.x-or-newer

Everything works fine except for copy from youtube.

I can upload a file from PC. Works great. I can even copy from other sites like archive.org

But when I try to copy a video from youtube, nothing happens. Nothing at all.

So I started up another brand new server and tried again. Fresh install. Same issue. Everything works fine. Just cannot copy from YT

**Comment by GreenDragonTavern** [comment]
@The-Do-It-Yourself-World - When you say *"copy a video from youtube"* are you referring to ***Import Video*** using AVideo-Encoder?

**Comment by The-Do-It-Yourself-World** [comment]
Yes

**Comment by The-Do-It-Yourself-World** [comment]
I can "import video" from Archive.org. I can upload a local file from my computer. All work fine.

But when I try to "import video" from YouTube, nothing happens. The screen goes gray like it always does. Then it clears and nothing happens at all. Its like I never did anything.

I have two servers with a fresh install. I updated everything on both. I updated the youtube.dl repeatedly as well.

Same thing.

**Comment by GreenDragonTavern** [comment]
Check for videos in AVideo that were created but never encoded properly.

Regarding youtube.dl - Try this (it's better, faster and maintained):
```
sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
sudo chmod a+rx /usr/local/bin/yt-dlp
```
AVideo-Encoder, modify configuration.php in the videos directory and add the following:
```
$global['youtube-dl'] = 'yt-dlp';
```
Don't use youtube-dl...and if you'd like to keep it on server, use below:
```
sudo mv /usr/local/bin/youtube-dl /usr/local/bin/youtube-dl-molasses
sudo ln -s /usr/local/bin/yt-dlp /usr/local/bin/youtube-dl
```

**Comment by The-Do-It-Yourself-World** [comment]
I did all you said. Nothing changed.

**Comment by The-Do-It-Yourself-World** [comment]
Update. I archived the log file so it would create a new one.

I am making multiple attempts to import a YT video on the encoder. I am not seeing anything much in the log file being generated except that the navbar takes 10 seconds to load. Nothing about a video import attempt.

**Comment by GreenDragonTavern** [comment]
What does AVideo-Encoder/videos/avideo.log show?

Configuration.php - did you change it in the AVideo/videos folder or the AVideo-Encoder/videos (or wherever you have encoder setup) folder? It has to be AVideo-Encoder/videos/configuration.php for yt-dlp to work.

In the AVideo-Encoder folder videos (use your correct path to Encoder), clean it out first:
```
sudo rm -r /var/www/html/AVideo/AVideo-Encoder/videos/chunk/*
sudo rm -r /var/www/html/AVideo/AVideo-Encoder/videos/thumbs*
sudo rm /var/www/AVideo/AVideo-Encoder/videos/sprit*
sudo systemctl restart apache2
```
Try a YouTube video again, check AVideo-Encoder/videos/avideo.log file and what does it report?.

**Comment by The-Do-It-Yourself-World** [comment]
Interesting...

I renamed the old log file and tried again so there was nothing in my way. Got this...

Error in the log: Exception: You are using an unsupported version of Python. Only Python versions 3.7 and above are supported by yt-dlp

I will upgrade and try again.

**Comment by The-Do-It-Yourself-World** [comment]
Got the same error for python. Working on that. Here is the log file entry from my last attempt:

[25-Mar-2023 21:03:40 UTC] getTitleFromLink: Get Title Error: LC_ALL=en_US.UTF-8 yt-dlp   --no-check-certificate --no-playlist --force-ipv4 --skip-download -e 'https://youtu.be/1bJevKoZ-Mk' 
Array
(
    [0] => Traceback (most recent call last):
    [1] =>   File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 2, in <module>
    [2] => ModuleNotFoundError: No module named 'contextvars'
    [3] => 
    [4] => During handling of the above exception, another exception occurred:
    [5] => 
    [6] => Traceback (most recent call last):
    [7] =>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    [8] =>     "__main__", mod_spec)
    [9] =>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    [10] =>     exec(code, run_globals)
    [11] =>   File "/usr/local/bin/yt-dlp/__main__.py", line 14, in <module>
    [12] =>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    [13] =>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    [14] =>   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
    [15] =>   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
    [16] =>   File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 5, in <module>
    [17] => Exception: You are using an unsupported version of Python. Only Python versions 3.7 and above are supported by yt-dlp
)

**Comment by GreenDragonTavern** [comment]
Just curious, why Ubuntu 18.04? For python 3.7...
```
sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.7
python --version
```

**Comment by The-Do-It-Yourself-World** [comment]
THANK YOU!!!

Got it working. And the new yt-dlp is awesome!!!

I am comfortable with 18.04 so I hope to keep using it.

**Comment by The-Do-It-Yourself-World** [comment]
Can someone maybe update the old instructions pages?

**Comment by GreenDragonTavern** [comment]
Welcome and personally Debian is my preferred STABLE cup of tea ;-)
