### ISSUE TITLE
Issue with encoding

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7839]
I was trying to import a video from my secondary AVideo site to my main one, the encoding seemed  to run OK, but finally when the post is created the video will not play. Since recent updates I notice that I have issues with the encoding again, they get stuck and I need to either re download the files or rencode and sometimes even that doesn't work and i need to delete them.

BTW, is the nginx version of running AVideo have changed or upgraded?

Here is screenshot of my post which was created OK: 

![Screen Shot 5783-07-05 at 16 46 08](https://user-images.githubusercontent.com/58882903/227958792-2fc6c2f8-2274-4786-aa21-47cc93749628.jpg)

And here is how it appears on the site:

![Screen Shot 5783-07-05 at 16 45 58](https://user-images.githubusercontent.com/58882903/227958979-4f38d12d-283b-45fc-b82d-2b81c2a0a1ec.jpg)

nothing changed on my server, I only do git pulls on AVideo.

**Comment by guymass** [comment]
OK I will try to do some test tonight. I also wanted to mention that I get more then few comlaints that some of the uploaded videos suddenly don't play anymore, I had to remove them and I don't know why. Some of those videos were uploaded months ago and were playing just fine, but something caused them to not play anymore and there was nothing else I could do but remove them.

**Comment by DanielnetoDotCom** [comment]
also get the latest updates

**Comment by walt93** [comment]
Daniel, we could really benefit from some admin features to help debug the site. 

Example, you have to do a whole bunch of steps and take notes to follow where your video and image files live in the filesystem. 

As an admin, in that /mvideos page, I ought to be able to see these things directly. It would make the workflow a lot easier for site maintenance when these issues occur, and having run an AVIdeo platform for more than two years, I can say they definitely do occur…

BTW the AWS plugin is working awesomely with the CDN, don't know when you slid that update in there, but its phenomenal.

**Comment by guymass** [comment]
I am fully updated. This is the log form the Encoder:
![Screen Shot 5783-07-06 at 19 42 06](https://user-images.githubusercontent.com/58882903/228310058-b7a82bca-72ce-4d3d-b4cf-ccc612f56268.jpg)

Also I see this repeating all the time and now users start reporting that videos they just upload don't play, live streams don't create the port properly after encoding, the post appears on the site, but the video is unavailable.

I don't know what to look for? Idk what went wrong from last update.

![Screen Shot 5783-07-07 at 17 23 44](https://user-images.githubusercontent.com/58882903/228569846-ee0a281f-71cf-49e7-b9fa-5bbe8d695760.jpg)

**Comment by guymass** [comment]
This also:

![Screen Shot 5783-07-07 at 17 29 31](https://user-images.githubusercontent.com/58882903/228571540-383324b2-fcda-4697-a778-c5b2a2b4d6f2.jpg)

**Comment by guymass** [comment]
for example this channel's videos are now not playing. I haven't checked them all but you can se there is a problem.

https://alive528.com/?search=%D7%A9%D7%A8%D7%95%D7%A0%D7%94

And I can see this as well in the log:

:33:01 Asia/Karachi] PHP Notice:  Undefined index: en_us in /var/www/html/AVideo/plugin/Layout/Layout.php on line 306
[29-Mar-2023 20:33:01 Asia/Karachi] PHP Notice:  Trying to access array offset on value of type null in /var/www/html/AVideo/plugin/Layout/Layout.php on line 306

**Comment by guymass** [comment]
How can I track for example where this video file is and what's its name to check if its missing or damaged?
https://alive528.com/v/19084

**Comment by guymass** [comment]
OK managed to get those faulty videos to work again. I first restarted my apache server, then I opened the faulty post and just clicked the save button and after that the video was loaded just fine, in my case.

It could be the apache had some issue that was cleared on restart or that those files weren't saved properly idk, but now it works. i`ll keep it open just in case the streaming issue for saving lives streams occurs again ill keep testing.

**Comment by guymass** [comment]
Well so far so good, everything seems to be back to normal. So my guess is that after a long time I haven't restarted the apache and nginx servers and I was making updates almost daily, I think after awhile it is a good idea to restart them to clear and refresh them so they can load the site from start with all the updated files. Just an hunch, so I will close this for now.
