### ISSUE TITLE
Update Scheduler 4.3 and YPT Socket 2.1 plugins

### ISSUE THREAD

**Issue by sharknetwork24** [WWBN/AVideo#7840]
When I go to download Scheduler 4.3 and YPT Socket 2.1 plugins on Marketplace, here (https://youphp.tube/marketplace/) they are not in the list.
Even doing a gitpull they don't update.
My YPTSocket keeps disconnecting.
I give the command to start:
sudo nohup php /var/www/html/AVideo/plugin/YPTSocket/server.php &

He boots up for a few seconds and immediately disconnects.
Daniel why are there no plugins on the marketplace?
Can you kindly tell me how to fix and upgrade my YPTSocket to 2.1 version?
I'm waiting for your answer.
Thank you

**Comment by milehighkaraoke** [comment]
Look to see if you have an update tab in your plugins under specific plugins

**Comment by DanielnetoDotCom** [comment]
To update  Scheduler and YPT Socket  you mast do a git pull

if you cannot make a git pull share your output

**Comment by sharknetwork24** [comment]
I no longer see the update prompt, but errors pop up that weren't there before.

**Comment by DanielnetoDotCom** [comment]
So the issue seems to be fixed, I will close this thread

If you see any other error please open a new issue. do not mix issues, it makes it harder for me to help you.

**Comment by sharknetwork24** [comment]
> So the issue seems to be fixed, I will close this thread
> 
> If you see any other error please open a new issue. do not mix issues, it makes it harder for me to help you.

No Daniel is not solved.
From the phone I could not see, but now from the PC you can see.
I took screenshots for you

**Comment by sharknetwork24** [comment]
> To update Scheduler and YPT Socket you mast do a git pull
> 
> if you cannot make a git pull share your output

what output?
I already did a gitpull but it doesn't solve the problem.

**Comment by DanielnetoDotCom** [comment]
> > To update Scheduler and YPT Socket you mast do a git pull
> > if you cannot make a git pull share your output
> 
> what output? I already did a gitpull but it doesn't solve the problem.

It probably did not work, that is why I am requesting you the git pull output.

**Comment by DanielnetoDotCom** [comment]
delete the nohup.out file and make a git pull again

`sudo rm /var/www/html/AVideo/nohup.out`

**Comment by sharknetwork24** [comment]
Ok

**Comment by DanielnetoDotCom** [comment]
you should be good now, do not forget to update your encoder as well

**Comment by sharknetwork24** [comment]
![7](https://user-images.githubusercontent.com/82677269/228226301-d0a26dcd-3c21-49f8-80ce-45ac86f3c529.JPG)
![8](https://user-images.githubusercontent.com/82677269/228226306-a5699282-d494-46f3-b80b-d08fb9ab1129.JPG)
![9](https://user-images.githubusercontent.com/82677269/228226311-8d7f1f59-0248-4e80-be24-25f8b3b4e3bd.JPG)

**Comment by sharknetwork24** [comment]
I just updated and restarted.
As soon as it ends I'll tell you what happens.

**Comment by sharknetwork24** [comment]
![11](https://user-images.githubusercontent.com/82677269/228231568-008197ae-085a-4d70-9002-406ee2a43cd8.JPG)

Daniel but is the vove in red RESTART always there?
Is it normal to be like this?
And your update probably.

**Comment by DanielnetoDotCom** [comment]
yes, also check your Scheduler plugin for instructions.

**Comment by sharknetwork24** [comment]
> yes, also check your Scheduler plugin for instructions.

Thanks Daniel
