### ISSUE TITLE
Live STreams never ends  Some go to 403 error if clicked and the coming soon never goes away

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7848]
When I look at the /live tab once the stream is finished it still stays there and also still shows live on the users channel. What makes it hang-up the stream?

**Comment by JoshWho** [comment]
![0da14642-9e01-4319-903a-394d8f9dc79f](https://user-images.githubusercontent.com/39392449/229198379-3e7f57ab-55d4-4f30-9f46-9443445d59f3.png)

![image](https://user-images.githubusercontent.com/39392449/229198469-523bce59-26a5-40f8-8f72-b5572add5513.png)

**Comment by DanielnetoDotCom** [comment]
try this

![image](https://user-images.githubusercontent.com/18009293/229201759-06530e7b-89c8-40eb-9b4a-e1f9fca4871a.png)

**Comment by JoshWho** [comment]
![dfc911d7-91f9-4686-a1e4-d7a4490354f2](https://user-images.githubusercontent.com/39392449/229204183-24b2e044-3aea-4efb-8e07-ce57eeac15de.png)

That did it.

Is this something that has to be done all the time?

**Comment by DanielnetoDotCom** [comment]
Only if it fails to mark it offline. 

the best is to investigate why the on_publish_done fail
