### ISSUE TITLE
We need AI

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7850]
**Is your feature request related to a problem? Please describe.**
Example: use Vosk to extract the text from a video, take the output text from Vosk and feed it to a LLM to summarize into a description and keywords. https://alphacephei.com/vosk/

Example: use LLM to create 64 character title and 200 character description, which is required for Roku feed, by summarizing existing data. (this can be done with a chatGPT prompt, chatGPT will write the code for you to interface with ... chatGPT to basically bind the AI to become an API endpoint). Oh, and, don't need to give OpenAI any $, just embed a LLM https://github.com/nomic-ai/gpt4all

Example: gonna be a **bit** more work to do the AI subtitle generator. Why let YouTube have all the fun?

Example: Now you've got the keywords for every video, how hard is it to make a next videos list out of things that are like what you're watching now?

Duuuuudddeeeeee……………

**Describe the solution you'd like**
For Daniel to sit down with ChatGPT 4 and ask it how to implement these things, and then integrate/test/debug the bots code.

**Describe alternatives you've considered**
Doing so myself.

**Additional context**
🤖 makes this stupid simple Daniel. 

ChatGPT Prompt: Lets run through the base code, we're on a Linux server, in a Python/Flask app, this is "back-end" functionality that's going to be accessed through the web interface. I want to work on the function that does the text extraction with Vosk, so, lets start with a function that takes a path to a video file and the id of the file in the "videos" table of the mysql database, and lets get the raw text output & store it back into the database.

![Screen Shot 2023-03-31 at 2 03 09 PM](https://user-images.githubusercontent.com/11711050/229229629-82cb01d6-8426-4205-8700-c1cbc4f94dea.png)

**Comment by GreenDragonTavern** [comment]
@walt93 - https://youtu.be/_Klkr6PtYzI

**Comment by walt93** [comment]
Meh, start out with some training wheels then, into a queue for human moderation.

I've done some very limited testing of a chatgpt title/description condenser & it actually seems to work. Will run it through a database of 8K videos and see how it performs with my sites data. I've got plenty for it to expose its biases on. 🤣
