### ISSUE TITLE
can I skip creating virtual host file and SSL with let's encrypt?

### ISSUE THREAD

**Issue by gseiki** [WWBN/AVideo#7851]
Setting up AVideo on Ubuntu 22.04.  I'm setting up my server on locally on a school campus.  I don't have a domain name.  I skip creating the virtual host file and SSL with let's encrypt?  I was just planning to use IP address.

**Comment by milehighkaraoke** [comment]
Don't install lets encrypt and just use local host Set up apatchy file for local host

**Comment by GreenDragonTavern** [comment]
This will help if you find later on that a SSL Cert is necessary to satisfy all on campus:

https://github.com/antelle/generate-ip-cert

**Comment by gseiki** [comment]
Thanks, I think I got the streamer site up, but not sure.  I'm trying to test it out, but have an encoder problem now. I'll open another ticket.

**Comment by gseiki** [comment]
I referenced the Ubuntu 22.xx wiki page.  I didn't create a virtual host file and I skipped the SSL steps.  Is this why my encoder is not working.  My configuration page says that if I don't want to use the public encoder, I should download my own encoder.  But, I thought that the first step from the wiki page was to curl the streamer, encoder, and nginx.
