### ISSUE TITLE
listen tcp4 0.0.0.0:80: bind: address already in use

### ISSUE THREAD

**Issue by gseiki** [WWBN/AVideo#7854]
Trying to enable Jitsi.  When I run sudo docker-compose up -d. I get an error message that ends with "listen tcp4 0.0.0.0:80: bind: address already in use".  How do I fix this?

**Comment by JoshWho** [comment]
Can't use the same port if you already have 80 in use on that server.

**Comment by gseiki** [comment]
Gonna revisit my Jitsi setup later.  Trying to fix other issues with my Streamer.
