### ISSUE TITLE
Embed is broke again

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7857]
![4d484a9d-ea56-45f6-86f9-04e386e77587](https://user-images.githubusercontent.com/39392449/229370154-6a584e75-dd55-40bd-aac2-b3b9afabee09.png)

From video https://www.joshwhotv.com/video/.7Cu4Jg/the-covid19-scam-that-killed-and-injured-the-world-timeline

`<div class="embed-responsive embed-responsive-16by9" style="position: relative;padding-bottom: 56.25% !important;"><iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;position: absolute;top: 0;left: 0;width: 100%; height: 100%;" src="https://www.joshwhotv.com/videoEmbed/.7Cu4Jg/the-covid19-scam-that-killed-and-injured-the-world-timeline?modestbranding=1&showinfo=1&autoplay=&controls=1&loop=&mute=&t=0&objectFit=" frameborder="0" allow="fullscreen;autoplay;camera *;microphone *;" allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" msallowfullscreen="msallowfullscreen" oallowfullscreen="oallowfullscreen" webkitallowfullscreen="webkitallowfullscreen" scrolling="no" videoLengthInSeconds="2696">iFrame is not supported!</iframe></div>`

**Comment by DanielnetoDotCom** [comment]
I sent an update 30 min ago, please check

**Comment by JoshWho** [comment]
Will do thanks

**Comment by JoshWho** [comment]
I confirm it is fixed Thank you @DanielnetoDotCom
