### ISSUE TITLE
Suscription plugin + Stripe problem

### ISSUE THREAD

**Issue by rapiz** [WWBN/AVideo#7869]
Hello,

When a user registers a subscription, in Stipe we see it duplicated, one is completed and the other is not. Because of this, Stripe cancels the subscription and it does not renew automatically.

Can you help us with this?

![image](https://user-images.githubusercontent.com/7936334/229713730-6e5fff28-3d53-403c-818c-556720be64ca.png)

**Comment by DanielnetoDotCom** [comment]
I am not sure what that means, but those 2 subscriptions are from the same user?

as long as you get paid, this is not an issue, it may be some stripe check before make a real transaction.

**Comment by rapiz** [comment]
The 2 subscriptions are generated when the user tries to subscribe (when only 1 subscription should be generated). The problem is that the second one (which we do not understand why it is generated) remains in error, which causes Stripe to cancel the recurring subscription and the user must recreate it every month

**Comment by rapiz** [comment]
[suscription.log](https://github.com/WWBN/AVideo/files/11148658/suscription.log)
![image](https://user-images.githubusercontent.com/7936334/229796153-1f38644d-3711-4236-b1a1-40b86519200c.png)

**Comment by DanielnetoDotCom** [comment]
anyway to get the seconds when this happen?

![image](https://user-images.githubusercontent.com/18009293/229799422-3a609475-6328-4e77-ac2f-b064d71c65ad.png)

**Comment by rapiz** [comment]
I can't see a date with seconds in stripe

**Comment by DanielnetoDotCom** [comment]
based on your log that is the only time we connect with Stripe to create a subscription

````
[04-Apr-2023 14:43:20 Europe/Madrid] AVideoLog::DEBUG: setUpSubscription: parameters {"customer":"cus_NeS6V4B6fUpAHb","items":[{"plan":"plan_NeS6uW5kxtzuui"}],"metadata":{"users_id":2878,"plans_id":1,"stripe_costumer_id":"cus_NeS6V4B6fUpAHb"}} SCRIPT_NAME: /plugin/YPTWallet/plugins/YPTWalletStripe/requestSubscription.json.php

[04-Apr-2023 14:43:22 Europe/Madrid] AVideoLog::DEBUG: setUpSubscription: result ...
````

maybe you can try to find another moment that we attempt to create another subscription

https://github.com/WWBN/AVideo/blob/a6bce4ec3f2be1b97e6276435c7e1b9e7f8a6edb/plugin/StripeYPT/StripeYPT.php#L473-L475

**Comment by rapiz** [comment]
Hello,

I have reported to Stripe and they confirms that 2 requests are made:

POST /v1/subscriptions
POST /v1/payment_intents

Apparently only the creation of the subscription should be received.

**Comment by DanielnetoDotCom** [comment]
can you please share the complete stripe response with me?

**Comment by rapiz** [comment]
The email from stripe support?

**Comment by DanielnetoDotCom** [comment]
Yes the complete message, I am trying to find some clues

**Comment by rapiz** [comment]
Also add captures:
<img width="1343" alt="Captura de pantalla 2023-04-04 a las 21 31 32" src="https://user-images.githubusercontent.com/7936334/229902598-e12b5cc6-38ac-4c66-81e4-895e7a80e684.png">


<img width="1343" alt="Captura de pantalla 2023-04-04 a las 21 31 44" src="https://user-images.githubusercontent.com/7936334/229902270-006d6ef4-dbca-4ce3-b58f-b20ca1cdaeaa.png">


**Spanish Stripe support message:**
`Hola,

Muchas gracias por tu respuesta y por la nueva información. No es ninguna molestia, es un placer para mí poder seguir ayudándote.

Me gustaría decirte que entendiendo lo confusa que puede ser esta situación. Para responderte directamente, gracias a la información que nos has brindado, hemos analizado el caso que nos has enviado y de nuestro lado seguimos viendo el comportamiento siguiente:

Con el ID que has enviado (cus_NeS6V4B6fUpAHb), seguimos recibiendo, de la misma fuente, una solicitud de creación de suscripción y una solicitud de intención de pago:

-https://dashboard.stripe.com/logs/req_az1iSqzjvJWlPt (POST/v1/subscriptions - Source: Stripe/v1 PhpBindings/8.12.0)

-https://dashboard.stripe.com/logs/req_ZwiSzHck2Xqn1F (POST/v1/payment_intents - Source: Stripe/v1 PhpBindings/8.12.0)

Aunque hemos revisado varias veces este y los otros casos, confirmamos que solo el desarrollador/tercero que se encarga de tu integración con Stripe y tu sitio web puede abordar por qué sucede esto.

Entiendo que esto significa redirigirte nuevamente, y aunque me hubiera encantado encontrar de nuestro lado la razón, hemos confirmado que solo ellos pueden descubrir el origen de la situación.

Realmente espero que si indagamos un poco más del lado de tu aplicación, encontremos la respuesta a esta situación. Si tienes más preguntas o comentarios sobre este tema, por favor házmelo saber. Estaré más que encantada de ayudarte.

Cordialmente,`

**Comment by DanielnetoDotCom** [comment]
Thank you for bringing this issue to our attention, and we apologize for any inconvenience caused. I have updated the script code to prevent any duplicate payment attempts in the future. To apply these changes, simply perform a git pull on your AVideo site. If the issue persists or you encounter any other problems, please feel free to open a new issue or comment on this one.

**Comment by rapiz** [comment]
I would appreciate if you could indicate the files that I should update. I cannot bring all the changes since we have our own changes to adapt some parts of views and so on.

**Comment by rapiz** [comment]
Inifite loop
![Captura desde 2023-04-05 20-09-44](https://user-images.githubusercontent.com/7936334/230168299-46dd2d18-aa03-4a53-91fa-421eadb28a50.png)

[log.txt](https://github.com/WWBN/AVideo/files/11161870/log.txt)

Does not show authorization window in two steps (3d secure in strip)

**Comment by DanielnetoDotCom** [comment]
Did you update all the files? including JS?

make sure you also clear the cache. 

if still hanging in this window please check your js console the[ ajax request](https://github.com/WWBN/AVideo/wiki/Check-Ajax-answer)
