### ISSUE TITLE
ERROR: Id for table CachesInDB not defined for deletion 

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#7873]
@DanielnetoDotCom Ever since I enabled Cache, I've been getting these CachesInDB errors. How do I resolve this error?

`[05-Apr-2023 11:22:40 America/Sao_Paulo] AVideoLog::ERROR: Id for table CachesInDB not defined for deletion [{"file":"\/var\/www\/html\/AVideo\/plugin\/Cache\/Cache.php","line":368,"function":"delete","class":"ObjectYPT","type":"->"},{"file":"\/var\/www\/html\/AVideo\/objects\/Object.php","line":573,"function":"getCache","class":"Cache","type":"::"},{"file":"\/var\/www\/html\/AVideo\/objects\/user.php","line":826,"function":"getCache","class":"ObjectYPT","type":"::"},{"file":"\/var\/www\/html\/AVideo\/objects\/user.php","line":926,"function":"canWatchVideo","class":"User","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/row_info.php","line":118,"function":"canWatchVideoWithAds","class":"User","type":"::"},{"file":"\/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/row_video.php","line":17,"args":["\/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/row_info.php"],"function":"include"},{"file":"\/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/row.php","line":136,"args":["\/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/row_video.php"],"function":"include"},{"file":"\/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/modeFlixBody.php","line":271,"args":["\/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/row.php"],"function":"include"},{"file":"\/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/modeFlix.php","line":30,"args":["\/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/modeFlixBody.php"],"function":"include"},{"file":"\/var\/www\/html\/AVideo\/view\/index_firstPage.php","line":58,"args":["\/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/modeFlix.php"],"function":"require"},{"file":"\/var\/www\/html\/AVideo\/view\/index.php","line":20,"args":["\/var\/www\/html\/AVideo\/view\/index_firstPage.php"],"function":"include"}] SCRIPT_NAME: /view/index.php`

**Comment by DanielnetoDotCom** [comment]
this is not a big issue, but this update may prevent this warning

**Comment by gbrn** [comment]
ok thanks

**Comment by gbrn** [comment]
This problem no longer appeared. I keep monitoring.
