### ISSUE TITLE
Turned on email notifications but no video metadata is sent

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7876]
**Describe the bug**
Turned on email notifications. Received this notification, which is not super useful. 

![4CDE33A5-78A5-46C8-9B51-8023F3DDC983](https://user-images.githubusercontent.com/11711050/230657081-431bec2a-bd19-4045-ae67-b694adedd8e6.jpeg)

expected result: title of video would be nice.

Curiously, GitHub is not displaying the screenshot of the e-mail, the salient point is that the video title is "Article automatically booked".

I also noticed that this user uploaded two videos, but only one notification e-mail appears to have been sent.

**Comment by DanielnetoDotCom** [comment]
what type of video is that?
embed? article?
check and share the email source

**Comment by walt93** [comment]
Looks like she posted an article.

We should not waste users time sending them such a useless e-mail.

"Video automatically booked" is not going to make someone want to click on this link, it's more likely IMO that someone would want to hit unsubscribe from being spammed.

Second issue, user is uploading multiple videos, yet. I am not seeing a notification for each of them. I know this because I am looking at my e-mail and there are only two notifications from this user, and... looks like she's uploaded 10 pieces in the last 3 days, so I should have _definitely_ gotten more than 2 emails.

**Comment by DanielnetoDotCom** [comment]
I currently don't have the option to disable automatic notifications for new articles. However, you can set the default status of your new media uploads to inactive, which will prevent automatic email notifications from being sent.

![image](https://user-images.githubusercontent.com/18009293/230891054-6070bab3-e890-4046-83a4-69ef52413091.png)


As for the missing emails, it is essential to check the logs at the time they were supposed to be sent to investigate the issue further.

**Comment by walt93** [comment]
Ok, if we make the video inactive, no notification is sent.

This will add more steps for every video a user uploads.

Then does it send a notification every time a video goes active? Or are we just going to suppress all notifications?

**Comment by DanielnetoDotCom** [comment]
I am pretty sure the notification will not be sent. 

I have plans to:

1. let you decide the status per video type
2. create a button (per video) to notify subscribers at any time

**Comment by walt93** [comment]
The problem with this Daniel is that the current use case is semi-broken half-dumb

What you want:
   User subscribes to publisher
   Publisher posts video
   Notification sent to subscriber
   
What you don't want
   Publisher posts article
   Half-formed notification is sent to subscribers

Seems stupid simple, Daniel, when you send the notification check if its an article. If it is, return. What is that like if video.type == 'A' or something? I don't know your code base, it could take me a couple of hours to figure out where to do that. You it would take 5 minutes.........................................................................................
