### ISSUE TITLE
I never want scheduled publish. I always select publish now. It always makes me go back to /mvideos and publish

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7880]
**Describe the bug**
I want my old workflow. There are already too many time wasting steps like I have to wait for the encoder to be done, so we can upload a meaningful poster frame, because the pick-a-random-poster-frame algorithm needs to be taken out back and given a proper execution and burial, and no, just because it's Easter, I don't expect it to be resurrected either. BTW, don't use Google, the godless commies can't even acknowledge the holiday. But I digress...

This new feature further bogs down our workflow.

![Screen Shot 2023-04-09 at 3 37 20 PM](https://user-images.githubusercontent.com/11711050/230799716-d9a8bc32-277b-420d-9da5-356b0c2c7806.png)

It *looks* like we can take the default value, and it will "Publish Now".

But that's not what happens. The video is not published, and we have to take extra steps to do what we have already done.

**To Reproduce**
1. Go to the encoder
2. Select "Publish Now"
3. Encode the video
4. Observe that the video does not "Publish Now". 

**Expected behavior**
The video to be published.

**Comment by DanielnetoDotCom** [comment]
make sure you have the crontab for the scheduler 

![image](https://user-images.githubusercontent.com/18009293/230890570-72829740-b0de-43e4-8f56-c97f21b7a645.png)
