### ISSUE TITLE
Some videos don't play as Admin

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#7889]
Some Videos (not all) do not play/show when logged in as **Admin** and the Video_list at the right is not loading (See Picture)
When logged in as **Admin**, the embedded video is okay (https://archief.beesel-reuver.nl/videoEmbeded/2909) 
 
 **Remark**: I've have the same issue on a clone with exactly the same videos.

![Snap4](https://user-images.githubusercontent.com/39981177/231137773-df9ab76b-370c-40ea-ba37-fb13d4c07218.jpg)
 
  
 
  
When i l**og off** or log in as **another user** everything is okay

![Snap5](https://user-images.githubusercontent.com/39981177/231138060-d31d2f2d-8896-44ce-a6b9-91aae7129d84.jpg)
 
 
No errors found in *.log, trying clearing cache etc but the only way to show the video is to Log Off as Admin

**Comment by DanielnetoDotCom** [comment]
what video did not play?

check your js console log

I can see you modified the script, that is probably something crashing in your modification.

**Comment by TLCReuver** [comment]
Deeleted own scripts, cleared cache (& brwoser)

Video local stored on drive (Using plugin SecrureVideoDirectory)

![Snap8](https://user-images.githubusercontent.com/39981177/231156671-cb32dc71-528f-4236-9135-8e436c06d48f.jpg)
 
Logs when logged as Admin: (**No errors** when **logged off** or **as another user**)
 
![Snap6](https://user-images.githubusercontent.com/39981177/231156913-e3d267e5-6cd7-47b8-800e-9d66f86f5303.jpg)
 
![Snap7](https://user-images.githubusercontent.com/39981177/231156961-84c4c4fd-d5d8-4752-b9d8-cc5ca07ea8be.jpg)

**Comment by DanielnetoDotCom** [comment]
that is what I mean, check where it comes from

![image](https://user-images.githubusercontent.com/18009293/231158456-6561bbd5-8e5e-48fc-ad2f-b0bfd5463b92.png)

probably your modification.

**Comment by TLCReuver** [comment]
You are right, I removed the hyphen '-' in the title and the video is playing now when logged in as Admin.  Waiting for a bugfix for this issue. 

Thanks JSY-Ben

![Snap9](https://user-images.githubusercontent.com/39981177/232000519-495bc817-7f46-44cc-82bd-bedc354965fd.jpg)

**Comment by DanielnetoDotCom** [comment]
how can I reproduce this issue?

![image](https://user-images.githubusercontent.com/18009293/232026531-eefa81e3-0240-484d-a116-bb537ab16ba8.png)

can you help me to reproduce it?

**Comment by JSY-Ben** [comment]
Perhaps do a title with a space then hyphen then space? That's the only difference I can see?

**Comment by DanielnetoDotCom** [comment]
please give me a title example that may fail.

**Comment by JSY-Ben** [comment]
One of the videos that failed on mine was....

DJI RS3 PRO Gimbal - Setup and Use Tutorial

Many thanks.

**Comment by DanielnetoDotCom** [comment]
Still working for me

![image](https://user-images.githubusercontent.com/18009293/232033238-94d7c55f-b398-4329-b7db-6a81aa9d5718.png)

are you guys using Ubuntu with PHP as a module? (NOT FPM)

**Comment by DanielnetoDotCom** [comment]
YTPSocket should make no difference. 

what may cause things like that is the apache.conf or .htaccess

**Comment by TLCReuver** [comment]
Once more in short:

Logged in as ADMIN ===> Some videos with has "-" in Title are not displaying correctly.
Logging OUT as ADMIN ==> There is no issue  and video is okay and also layout is okay.

Both have same apache.conf,  .htaccess, PHP-version & Ubuntu version.

I noticed that the problem is not the 'title' but the 'clean_title'.

Example: 2023 Commercial - Sloepverhuur Limburg Kessel ad Maas
![Snap_01](https://user-images.githubusercontent.com/39981177/232123626-ece77d98-b411-4132-bad6-6f7ff6486a7a.jpg)
When i change --- into - (one -) i have no issue

It look like when logged in as ADMIN the script is referring to '**clean title**'
and when logged in as NON_ADMIN the script is referring to '**title**' 

[JSY-Ben](https://github.com/JSY-Ben) can you confirm when you change --- in clean_title into - (only 1 -) that your display is correct ?

**Comment by DanielnetoDotCom** [comment]
Sorry, I still cannot reproduce it,

![image](https://user-images.githubusercontent.com/18009293/232144930-3f044ddf-e3c5-40f6-8b29-55fcc4479c51.png)

**Comment by TLCReuver** [comment]
I tried it on demo page [DanielnetoDotCom](https://github.com/DanielnetoDotCom) but cannot reproduce it too.

No problem, i change the '**clean_title'** by hand. 

Thankz for your time.

**Comment by JSY-Ben** [comment]
Just an update on this issue.

I found it appears to be linked to VR360 plugin. If you have VR360 plugin enabled, and have a video with a hyphen - in the title, the video won't play when you are an admin. You can get an error in console saying that an unexpected token (,) is in the code. This is where it points out the error to be. Disabling the VR360 plugin is fixing it for now

<img width="582" alt="Screenshot 2023-04-28 at 6 19 11 PM" src="https://user-images.githubusercontent.com/13555701/235213281-114b49d8-c0b1-42b2-84c8-2790a9cd7322.png">

**Comment by DanielnetoDotCom** [comment]
Thanks, this update may resolve that

**Comment by JSY-Ben** [comment]
Work like a dream now, thank you very much :)

**Comment by TLCReuver** [comment]
Works perfect now... Top 

Th@nkz
