### ISSUE TITLE
Plugins page shows empty

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7894]
After updating when I try to open the plugins page I get a white page without any listings, here is a screen shot:

![Screen Shot 5783-07-22 at 17 58 16](https://user-images.githubusercontent.com/58882903/231801221-667c2258-0273-4e81-a7a7-0bbadc5d4fd3.jpg)

**Comment by DanielnetoDotCom** [comment]
Logs please

**Comment by guymass** [comment]
maybe this?
![Screen Shot 5783-07-22 at 18 05 47](https://user-images.githubusercontent.com/58882903/231802899-a533318c-8294-4468-9103-9e021979fe41.jpg)

**Comment by guymass** [comment]
I see this as well:

[13-Apr-2023 18:03:15 Asia/Jerusalem] AVideoLog::DEBUG: Live::getStatsObject[0] 4: cache not found SCRIPT_NAME: /view/managerPlugins.php

**Comment by guymass** [comment]
My error log is constantly showing this:

[Thu Apr 13 18:09:52.291164 2023] [socache_shmcb:debug] [pid 1942156] mod_socache_shmcb.c(493): AH00831: socache_shmcb_store (0xf5 -> subcache 21)
[Thu Apr 13 18:09:52.291179 2023] [socache_shmcb:debug] [pid 1942156] mod_socache_shmcb.c(847): AH00847: insert happened at idx=12, data=(547:579)
[Thu Apr 13 18:09:52.291184 2023] [socache_shmcb:debug] [pid 1942156] mod_socache_shmcb.c(850): AH00848: finished insert, subcache: idx_pos/idx_used=46/55, data_pos/data_used=2856/11772
[Thu Apr 13 18:09:52.291189 2023] [socache_shmcb:debug] [pid 1942156] mod_socache_shmcb.c(515): AH00834: leaving socache_shmcb_store successfully
[Thu Apr 13 18:09:52.377848 2023] [ssl:debug] [pid 1941575] ssl_engine_kernel.c(415): [client 147.235.218.150:12396] AH02034: Subsequent (No.6) HTTPS request received for child 37 (server alive528.com:443), referer: https://alive528.com/mvideos
[Thu Apr 13 18:09:52.379326 2023] [authz_core:debug] [pid 1941575] mod_authz_core.c(817): [client 147.235.218.150:12396] AH01626: authorization result of Require all granted: granted, referer: https://alive528.com/mvideos
[Thu Apr 13 18:09:52.379343 2023] [authz_core:debug] [pid 1941575] mod_authz_core.c(817): [client 147.235.218.150:12396] AH01626: authorization result of <RequireAny>: granted, referer: https://alive528.com/mvideos
[Thu Apr 13 18:09:52.437780 2023] [ssl:debug] [pid 1941139] ssl_engine_io.c(1102): [client 2.54.52.217:17133] AH02001: Connection closed to child 61 with standard shutdown (server alive528.com:443)
[Thu Apr 13 18:09:52.663091 2023] [ssl:debug] [pid 1935347] ssl_engine_kernel.c(415): [client 80.179.231.115:47904] AH02034: Subsequent (No.3) HTTPS request received for child 47 (server alive528.com:443), referer: https://alive528.com/sw.js?0.3512711140816662
[Thu Apr 13 18:09:52.664465 2023] [authz_core:debug] [pid 1935347] mod_authz_core.c(817): [client 80.179.231.115:47904] AH01626: authorization result of Require all granted: granted, referer: https://alive528.com/sw.js?0.3512711140816662
[Thu Apr 13 18:09:52.664480 2023] [authz_core:debug] [pid 1935347] mod_authz_core.c(817): [client 80.179.231.115:47904] AH01626: authorization result of <RequireAny>: granted, referer: https://alive528.com/sw.js?0.3512711140816662
[Thu Apr 13 18:09:52.664755 2023] [deflate:debug] [pid 1935347] mod_deflate.c(854): [client 80.179.231.115:47904] AH01384: Zlib: Compressed 3261 to 1036 : URL /sw.js, referer: https://alive528.com/sw.js?0.3512711140816662
[Thu Apr 13 18:09:52.667493 2023] [ssl:debug] [pid 1942232] ssl_engine_io.c(1102): [client 2.56.190.176:64290] AH02001: Connection closed to child 19 with standard shutdown (server alive528.com:443)
[Thu Apr 13 18:09:52.753249 2023] [ssl:info] [pid 1941191] [client 109.67.47.194:56417] AH01964: Connection to child 64 established (server live.ahava528.com:443)
[Thu Apr 13 18:09:52.753446 2023] [ssl:debug] [pid 1941191] ssl_engine_kernel.c(2372): [client 109.67.47.194:56417] AH02043: SSL virtual host for servername rtmp2.alive528.com found
[Thu Apr 13 18:09:52.753463 2023] [core:debug] [pid 1941191] protocol.c(2430): [client 109.67.47.194:56417] AH03155: select protocol from , choices=h2,http/1.1 for server rtmp2.alive528.com
[Thu Apr 13 18:09:52.815485 2023] [ssl:debug] [pid 1941191] ssl_engine_kernel.c(2254): [client 109.67.47.194:56417] AH02041: Protocol: TLSv1.3, Cipher: TLS_AES_256_GCM_SHA384 (256/256 bits)
[Thu Apr 13 18:09:52.931779 2023] [ssl:debug] [pid 1941137] ssl_engine_kernel.c(415): [client 147.235.218.150:12485] AH02034: Subsequent (No.21) HTTPS request received for child 58 (server alive528.com:443), referer: https://alive528.com/mvideos
[Thu Apr 13 18:09:52.933234 2023] [authz_core:debug] [pid 1941137] mod_authz_core.c(817): [client 147.235.218.150:12485] AH01626: authorization result of Require all granted: granted, referer: https://alive528.com/mvideos
[Thu Apr 13 18:09:52.933249 2023] [authz_core:debug] [pid 1941137] mod_authz_core.c(817): [client 147.235.218.150:12485] AH01626: authorization result of <RequireAny>: granted, referer: https://alive528.com/mvideos
[Thu Apr 13 18:09:52.935408 2023] [ssl:debug] [pid 1923380] ssl_engine_kernel.c(415): [client 147.235.218.150:12407] AH02034: Subsequent (No.15) HTTPS request received for child 45 (server alive528.com:443)
[Thu Apr 13 18:09:52.936868 2023] [authz_core:debug] [pid 1923380] mod_authz_core.c(817): [client 147.235.218.150:12407] AH01626: authorization result of Require all granted: granted
[Thu Apr 13 18:09:52.936883 2023] [authz_core:debug] [pid 1923380] mod_authz_core.c(817): [client 147.235.218.150:12407] AH01626: authorization result of <RequireAny>: granted
[Thu Apr 13 18:09:52.937004 2023] [authz_core:debug] [pid 1923380] mod_authz_core.c(817): [client 147.235.218.150:12407] AH01626: authorization result of Require all granted: granted
[Thu Apr 13 18:09:52.937015 2023] [authz_core:debug] [pid 1923380] mod_authz_core.c(817): [client 147.235.218.150:12407] AH01626: authorization result of <RequireAny>: granted
[Thu Apr 13 18:09:52.937081 2023] [authz_core:debug] [pid 1923380] mod_authz_core.c(817): [client 147.235.218.150:12407] AH01626: authorization result of Require all granted: granted
[Thu Apr 13 18:09:52.937090 2023] [authz_core:debug] [pid 1923380] mod_authz_core.c(817): [client 147.235.218.150:12407] AH01626: authorization result of <RequireAny>: granted
[Thu Apr 13 18:09:53.124834 2023] [ssl:info] [pid 1933158] [client 5.29.12.142:3332] AH01964: Connection to child 3 established (server live.ahava528.com:443)
[Thu Apr 13 18:09:53.125099 2023] [ssl:debug] [pid 1933158] ssl_engine_kernel.c(2372): [client 5.29.12.142:3332] AH02043: SSL virtual host for servername alive528.com found
[Thu Apr 13 18:09:53.125116 2023] [core:debug] [pid 1933158] protocol.c(2430): [client 5.29.12.142:3332] AH03155: select protocol from , choices=h2,http/1.1 for server alive528.com
[Thu Apr 13 18:09:53.132352 2023] [ssl:debug] [pid 1941245] ssl_engine_io.c(1102): [client 199.64.75.87:10981] AH02001: Connection closed to child 75 with standard shutdown (server alive528.com:443)
[Thu Apr 13 18:09:53.196989 2023] [ssl:debug] [pid 1933158] ssl_engine_kernel.c(2254): [client 5.29.12.142:3332] AH02041: Protocol: TLSv1.3, Cipher: TLS_AES_256_GCM_SHA384 (256/256 bits)
[Thu Apr 13 18:09:53.197103 2023] [socache_shmcb:debug] [pid 1933158] mod_socache_shmcb.c(493): AH00831: socache_shmcb_store (0x5f -> subcache 31)
[Thu Apr 13 18:09:53.197119 2023] [socache_shmcb:debug] [pid 1933158] mod_socache_shmcb.c(730): AH00842: expiring 1 and reclaiming 0 removed socache entries
[Thu Apr 13 18:09:53.197124 2023] [socache_shmcb:debug] [pid 1933158] mod_socache_shmcb.c(750): AH00843: we now have 57 socache entries
[Thu Apr 13 18:09:53.197129 2023] [socache_shmcb:debug] [pid 1933158] mod_socache_shmcb.c(847): AH00847: insert happened at idx=38, data=(914:946)
[Thu Apr 13 18:09:53.197133 2023] [socache_shmcb:debug] [pid 1933158] mod_socache_shmcb.c(850): AH00848: finished insert, subcache: idx_pos/idx_used=69/58, data_pos/data_used=2574/12421
[Thu Apr 13 18:09:53.197138 2023] [socache_shmcb:debug] [pid 1933158] mod_socache_shmcb.c(515): AH00834: leaving socache_shmcb_store successfully
[Thu Apr 13 18:09:53.197373 2023] [ssl:debug] [pid 1933158] ssl_engine_kernel.c(415): [client 5.29.12.142:3332] AH02034: Initial (No.1) HTTPS request received for child 3 (server alive528.com:443), referer: https://alive528.com/v/19843
[Thu Apr 13 18:09:53.198812 2023] [authz_core:debug] [pid 1933158] mod_authz_core.c(817): [client 5.29.12.142:3332] AH01626: authorization result of Require all granted: granted, referer: https://alive528.com/v/19843
[Thu Apr 13 18:09:53.198828 2023] [authz_core:debug] [pid 1933158] mod_authz_core.c(817): [client 5.29.12.142:3332] AH01626: authorization result of <RequireAny>: granted, referer: https://alive528.com/v/19843
[Thu Apr 13 18:09:53.384655 2023] [ssl:debug] [pid 1940568] ssl_engine_io.c(1102): [client 5.29.15.12:1031] AH02001: Connection closed to child 17 with standard shutdown (server alive528.com:443)
[Thu Apr 13 18:09:53.386580 2023] [ssl:debug] [pid 1941223] ssl_engine_io.c(1102): [client 5.29.15.12:1071] AH02001: Connection closed to child 70 with standard shutdown (server alive528.com:443)
[Thu Apr 13 18:09:53.593364 2023] [ssl:debug] [pid 1936433] ssl_engine_io.c(1102): [client 172.56.80.182:32179] AH02001: Connection closed to child 23 with standard shutdown (server alive528.com:443)
[Thu Apr 13 18:09:53.776342 2023] [ssl:info] [pid 1941222] [client 17.241.219.109:54802] AH01964: Connection to child 69 established (server live.ahava528.com:443)
[Thu Apr 13 18:09:53.776543 2023] [ssl:debug] [pid 1941222] ssl_engine_kernel.c(2372): [client 17.241.219.109:54802] AH02043: SSL virtual host for servername alive528.com found

**Comment by DanielnetoDotCom** [comment]
check the response here

![image](https://user-images.githubusercontent.com/18009293/231873045-9e305406-c5cf-4c19-8110-8a60fa760031.png)

in the other one looks like you are having internet problems or network problems in your server

![image](https://user-images.githubusercontent.com/18009293/231873256-5aa9383a-7b02-49f4-90b1-3a9a3ee25ff3.png)

**Comment by guymass** [comment]
Well site is loading and I can upload videos as ususal. Everything seems to work fine just the plugins do't load.

There is nothing in the Response Tab. Here are more screenshots:

![Screen Shot 5783-07-23 at 12 38 30](https://user-images.githubusercontent.com/58882903/232009036-b8b6fe20-cd47-413e-972e-1b1bbb3c4133.jpg)
![Screen Shot 5783-07-23 at 12 38 11](https://user-images.githubusercontent.com/58882903/232009062-c239d80a-fb17-4f67-8c15-7ecbe14beea1.jpg)
![Screen Shot 5783-07-23 at 12 39 00](https://user-images.githubusercontent.com/58882903/232009070-d4e5216e-ae6f-4d73-afc8-6ce3f7e5b6d5.jpg)

Honestly im not sure what is going on there, the rest of the sites I have on that server are working fine. This has to be something with the recent updates.

**Comment by guymass** [comment]
This is from Chrome and here I don't see any errors at all.
![Screen Shot 5783-07-23 at 12 55 07](https://user-images.githubusercontent.com/58882903/232012465-5c475144-f780-42f1-99eb-c1a71c2ae4f0.jpg)
![Screen Shot 5783-07-23 at 12 54 55](https://user-images.githubusercontent.com/58882903/232012483-f41aae29-f36b-4169-9696-134ca206035f.jpg)

**Comment by DanielnetoDotCom** [comment]
This is how it should look like

![image](https://user-images.githubusercontent.com/18009293/232028523-709c5811-56f6-421e-b76c-f50805d97ba7.png)

also, check the headers


![image](https://user-images.githubusercontent.com/18009293/232028655-ab3dcbb0-32e4-4f0a-bfcb-8730b1d7fee1.png)

![image](https://user-images.githubusercontent.com/18009293/232028745-f784befb-4d6c-47ea-b26e-9cbe8f1616f8.png)

**Comment by guymass** [comment]
This is really weired! I open the plugins page and I don't see the list of plugins, but when I click refresh to view the console it suddenly gives me a connection error and doesn't load the page anymore. My internet is fine and working, I can open the site normally, this only happens whenI open the plugins page.

This is what I get when trying to refresh the page:

![Screen Shot 5783-07-24 at 16 14 56](https://user-images.githubusercontent.com/58882903/232226200-1cb51176-c975-43f7-9822-c3214847d12b.jpg)

I have another site which I run on my own computer for testing as well, its not operational but I update it the same as the other main site and I have the same issue there as well.

The only version of the site I have which is fine is my fetube.flatearth.co.il site which is also updated fully but there the plugins open just fine.

IDK what to do more or what to look for. could this be permission issue? 
I haven't changed anything, I only made the daily git pull and since the last one or two updated I have this plugins issue.

**Comment by guymass** [comment]
opening the plugins page while the console is open will show me this:
![Screen Shot 5783-07-24 at 16 23 02](https://user-images.githubusercontent.com/58882903/232226605-3fedcc8d-418d-4fa6-9710-7fceadfac051.jpg)
![Screen Shot 5783-07-24 at 16 23 26](https://user-images.githubusercontent.com/58882903/232226619-a66f6c89-2912-4129-83d6-8cfa315c2d5e.jpg)

**Comment by DanielnetoDotCom** [comment]
That is clear to me it is a connection problem

**Comment by guymass** [comment]
Also I noticed that the YPTSocket stops working on the plugins page but on any other page of the site it works fine.

![Screen Shot 5783-07-24 at 16 25 00](https://user-images.githubusercontent.com/58882903/232226754-81f36a68-2f95-4843-afb3-df401b8ff396.jpg)
![Screen Shot 5783-07-24 at 16 25 14](https://user-images.githubusercontent.com/58882903/232226758-3130006a-6851-401a-ba67-82b7e84cdff4.jpg)

**Comment by guymass** [comment]
Well if there is a connection problem its not from my computer or my server as they are both connected and working fine, this is specific to the script.

**Comment by guymass** [comment]
The connection error only happens whenI use Brave browser, but when I use Chrome I can refresh and this is what I see:

![Screen Shot 5783-07-24 at 16 35 50](https://user-images.githubusercontent.com/58882903/232227301-08bccb83-f3a5-49cb-9f6a-baae714ed73b.jpg)
![Screen Shot 5783-07-24 at 16 35 11](https://user-images.githubusercontent.com/58882903/232227330-64202702-b417-43b1-89b7-0234df8ffbac.jpg)

**Comment by guymass** [comment]
Does this mean something:
![Screen Shot 5783-07-24 at 16 42 11](https://user-images.githubusercontent.com/58882903/232227714-db046ee3-9478-4497-917f-153113537bae.jpg)

**Comment by DanielnetoDotCom** [comment]
Nothing in the logs to help

**Comment by guymass** [comment]
maybe I should just reinstall everything? but I need to use the same database and im not sure really where the problem relays. Can I set a new folder and just transfer the videos directory and config files?

**Comment by DanielnetoDotCom** [comment]
It may work but I really think is a connection issue, that is what your browser said, maybe Apache is crashing when you push it too much , check Apache log maybe you find something

**Comment by guymass** [comment]
I am going to do some updates and maintenance on the server and reboot it. it haven't been updated for a long time. I also wanted to ask regarding PHP version as I am still using 7.4, can I use version 8 now?

**Comment by DanielnetoDotCom** [comment]
I use 8.1 for my self, and yes, an update may help.

**Comment by guymass** [comment]
8.1 give me this error:

![Screen Shot 5783-07-24 at 17 57 38](https://user-images.githubusercontent.com/58882903/232232514-9823fe74-dec6-47aa-9a65-c5a13144f3b1.jpg)

**Comment by guymass** [comment]
Still after updating and upgrading my server, PHP to 8.1 I still have the same issue :-|

![Screen Shot 5783-07-24 at 18 05 11](https://user-images.githubusercontent.com/58882903/232232955-7d712ba3-1daf-4214-bb28-4c8c59002526.jpg)

**Comment by DanielnetoDotCom** [comment]
you should check this 

https://github.com/WWBN/AVideo/issues/7894#issuecomment-1508346961

**Comment by guymass** [comment]
This is what I have:
![Screen Shot 5783-07-24 at 18 16 27](https://user-images.githubusercontent.com/58882903/232233565-0f7e5368-0f2e-453f-84b2-b245adf2b28e.jpg)
![Screen Shot 5783-07-24 at 18 16 46](https://user-images.githubusercontent.com/58882903/232233571-44a63fb0-2fc8-4fc3-941d-fceff11fcd77.jpg)
![Screen Shot 5783-07-24 at 18 16 18](https://user-images.githubusercontent.com/58882903/232233572-1c84d86e-3c6d-49d5-a95c-242b25b1f6ed.jpg)

**Comment by guymass** [comment]
Could it be related to the Hebrew language? maybe its not reading the database correctly because of bad escaping, missing quotes or single quote?

![Screen Shot 5783-07-24 at 18 51 26](https://user-images.githubusercontent.com/58882903/232235322-06a23391-4f77-4a89-9aca-8ef14940c69e.jpg)

**Comment by guymass** [comment]
Here is how it looks on the site I run from my local machine, same issue:
![Screen Shot 5783-07-24 at 19 55 24](https://user-images.githubusercontent.com/58882903/232239363-b83a7b09-03de-4fd4-8f1d-f1c7e90b30f9.jpg)

**Comment by DanielnetoDotCom** [comment]
When the pluginsAvailable is red or complete what is in the response?

**Comment by guymass** [comment]
There is no response from what I can see.
![Screen Shot 5783-07-24 at 21 34 37](https://user-images.githubusercontent.com/58882903/232247509-7a845dfd-5717-4b0c-bf76-1c230dbdf1d9.jpg)

**Comment by DanielnetoDotCom** [comment]
what is the response code (check in the headers)

**Comment by guymass** [comment]
Which url to open in a new tab? this one?
https://alive528.com/objects/pluginsAvailable.json.php
It just shows a white page, here is a screenshot of the console:

![Screen Shot 5783-07-24 at 23 12 36](https://user-images.githubusercontent.com/58882903/232251372-225da3ab-9634-407b-b02d-505c1e62abe8.jpg)
![Screen Shot 5783-07-24 at 23 12 46](https://user-images.githubusercontent.com/58882903/232251386-39fe43cd-9979-4048-949d-7d414a7fd158.jpg)

This is when I open the url:
![Screen Shot 5783-07-24 at 23 14 20](https://user-images.githubusercontent.com/58882903/232251405-fff137ab-b72c-4643-9f72-8ef463717de4.jpg)

Anything I have seen in logs while I was accessing the plugins page I already shared here, there is nothing else I have seen in them regarding the plugins. I will keep checking, if I find anything new I will post it.

**Comment by DanielnetoDotCom** [comment]
Now, when you access this https://alive528.com/objects/pluginsAvailable.json.php

you MUST check your logs apache log, access log and avideo log.

MUST be something, otherwise, I cannot help you

**Comment by guymass** [comment]
this is the only thing I see regarding the plugin CombineSites, it says its missing maybe this what is causing this?
![Screen Shot 5783-07-24 at 23 26 25](https://user-images.githubusercontent.com/58882903/232251831-adcb2124-d89d-4245-a974-10e108d15667.jpg)

**Comment by guymass** [comment]
could it be related to this:
![Screen Shot 5783-07-24 at 23 34 50](https://user-images.githubusercontent.com/58882903/232252145-f204fa83-e791-4e2f-87e7-a1fa7c48f1bc.jpg)

**Comment by DanielnetoDotCom** [comment]
no nothing to help, you can try to reset all your plugins and see if that work.

https://github.com/WWBN/AVideo/blob/master/install/resetPlugins.php

**Comment by guymass** [comment]
what does it do this reset?

**Comment by DanielnetoDotCom** [comment]
```
# php resetPlugins.php 
1 - Reset all plugins Parameters
2 - Reset CustomizeUser Plugin Parameters only
3 - Reset all plugins (Will also inactivate the plugins)
Choose an option: 
```

**Comment by DanielnetoDotCom** [comment]
this also may mean something

![image](https://user-images.githubusercontent.com/18009293/232254697-0765cbeb-5fb6-4319-b0fb-348af28a65a0.png)

also, check your health_check page

![image](https://user-images.githubusercontent.com/18009293/232254774-d0d1fd78-64c0-4702-9926-85f1b67515b0.png)


https://alive528.com/admin/?page=health_check

**Comment by guymass** [comment]
I have been also looking on my local test site which its logs are less full and busy but there were no errors showing in logs, neither the avideo.log nor the apache logs, nothing is showing. Even when I open the pluginsAvailable.json.php page, I also get a white page and the logs don't record anything. 

Here is my health status and even though sshpass is not installed, I never has an issue before.

![Screen Shot 5783-07-25 at 0 56 52](https://user-images.githubusercontent.com/58882903/232254849-f47bbb2e-4632-4cad-96d2-c90d34fc1228.jpg)

And this is my local test site

![Screen Shot 5783-07-25 at 1 06 57](https://user-images.githubusercontent.com/58882903/232255174-161aa81c-7e00-43ad-832c-75c22b6d56e6.jpg)

**Comment by DanielnetoDotCom** [comment]
sshpass is not required, 

for now, I have no clue what is your issue.

**Comment by guymass** [comment]
OK it turns out there was a a new strange plugin named "weglot" as the following screen shot show:
![Screen Shot 5783-07-26 at 13 02 55](https://user-images.githubusercontent.com/58882903/232454496-0b70533e-1c77-4a03-8bd4-c8ec08aa7de9.jpg)
![Screen Shot 5783-07-26 at 13 03 48](https://user-images.githubusercontent.com/58882903/232454695-28bb0571-d30b-4845-9889-2ee218138560.jpg)

once moving it out side plugin directory the plugins page was finally
 coming back up.

![Screen Shot 5783-07-26 at 12 58 15](https://user-images.githubusercontent.com/58882903/232454756-06a0b4c3-6464-4d88-84e3-73c657340386.jpg)

Thanks to Matt he found this solution and that this plugin is crashing the new version of the site while maybe previous versions didn't mind it. Matt also says this is a wordpres plugin, maybe? idk but I didn't put it there for sure.

Anyawy this is now fixed finnaly. Much thanks for the effort trying to help.

**Comment by DanielnetoDotCom** [comment]
I do not know this plugin, but I am glad you find it out
