### ISSUE TITLE
Checklist to move an avideo site's domain

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7898]
**Describe the question**
I've decided that "news.conspyre.tv" needs to be "conspyre.news". 

I know I need to:

1) point DNS to the box
2) edit domain in apache config, reload/restart apache
3) in site/videos/configuration.php whack the $global['webSiteRootURL']
4) In AVideo dashboard i've got the logo image
5) ???

What have I left out?

**Comment by DanielnetoDotCom** [comment]
you may need to redeploy the ssl, also check the socket plugin to fix the ssl path
