### ISSUE TITLE
re>plug-in that lets you pick the first frame as the poster frame? 

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7899]
**Describe the question**
Trying to solve the "use first frame of video for poster frame issue. I revisited MP4ThumbsAndGif and it's still broken for me.

MP4ThumbsAndGif

![Screen Shot 2023-04-14 at 9 06 15 PM](https://user-images.githubusercontent.com/11711050/232182078-f8af2bfc-0349-4b8d-8069-17a1dc3df387.png)

This is what I need to solve. I'm hoping it lets me pick the first frame and that it works for 1,000 videos at a time.

When I import a podcasters row, 100 episodes at a time, I get a disappointing result:
Podcasters row on Rumble
![Screen Shot 2023-04-14 at 7 25 16 PM](https://user-images.githubusercontent.com/11711050/232178710-427ce735-953c-425b-baf4-f9b289596047.png)

Podcasters row on AVideo
![Screen Shot 2023-04-14 at 7 27 37 PM](https://user-images.githubusercontent.com/11711050/232178786-d8b28a3b-5c30-44a2-86c0-44bee5b124f4.png)

**Comment by DanielnetoDotCom** [comment]
the error may be resolved once you make a gut pull
