### ISSUE TITLE
Live Stream is stuck on home page

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7902]
I have a live stream that some user started and now it is just stuck on my home page and doesn't clear out. How can I clear this?

![Screen Shot 5783-07-24 at 19 47 29](https://user-images.githubusercontent.com/58882903/232238920-70759f27-8d47-481c-8f50-78d43110d0f0.jpg)

**Comment by DanielnetoDotCom** [comment]
check this, then clear the cache...

![image](https://user-images.githubusercontent.com/18009293/232246757-881dd56e-ca09-4bb5-a678-b304044f0d38.png)

**Comment by guymass** [comment]
I cannot open my plugins page ;-), but I do I will check it, thanks.
