### ISSUE TITLE
Live stream doesn't work anymore

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7904]
Starting a new live stream it appears on the home page but the stream doesn't show at all.

![Screen Shot 5783-07-24 at 20 24 46](https://user-images.githubusercontent.com/58882903/232242804-96c9a301-94c0-45ce-8310-f822c461e582.jpg)
![Screen Shot 5783-07-24 at 20 24 13](https://user-images.githubusercontent.com/58882903/232243076-b6339f2e-851f-4f3a-8c0d-ceea74ef2c41.jpg)

**Comment by guymass** [comment]
OK I fixed that by recreating the file with touch /HLS/live/62fbc53959301-1.m3u8, but this is not a solution, for some reason nginx cannot write inside the /HLS/live directory even through it has all the proper permissions.

**Comment by DanielnetoDotCom** [comment]
`chmod -R 777 /HLS/`

**Comment by guymass** [comment]
It was already set to 777, but I will keep checking, idk why it does it sometimes.
