### ISSUE TITLE
Trying to stop a hung live stream doesn't work

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7919]
I have this live stream from a user named Anthony Patch of which his live stream is stuck and showing on my front page and notifications for few days. Today I fixed my plugins issue so I was able to use the "Mark all as finished" button and it stopped the stream for a minuet but then after the live stream was popping up again. I know the user is not streaming currently.

Here are some screen shots of the log and front page:
![Screen Shot 5783-07-26 at 18 05 37](https://user-images.githubusercontent.com/58882903/232529213-b73b9e70-de72-425d-9d07-dfeda4d8547c.jpg)

on front page it appears like this:

![Screen Shot 5783-07-26 at 17 12 16](https://user-images.githubusercontent.com/58882903/232529430-ab0eca93-7bee-40c5-acbe-bd29b2a1256e.jpg)

WhenI click on it it appears like this:
![Screen Shot 5783-07-26 at 18 05 49](https://user-images.githubusercontent.com/58882903/232529900-a9d330da-2688-4fcc-8c7e-ffe4c4924599.jpg)

as is it is online, but its is stuck. Now every new live stream gets stuck the same, and the button doesn't help.

![Screen Shot 5783-07-26 at 18 13 16](https://user-images.githubusercontent.com/58882903/232530305-d64abed8-564b-4d7e-9886-aff2680fadbf.jpg)

**Comment by GreenDragonTavern** [comment]
@guymass sometimes I've had to clean out the /HLS/live directory, then clear first page and cache directory on AVideo to remove a dead live off front page.

**Comment by milehighkaraoke** [comment]
I am having the same issue  even when my socket is showing connected. 
![Screenshot_20230417_011652_Chrome](https://user-images.githubusercontent.com/70327833/232560983-c0acf419-9514-4b5d-a6cb-cef3e686bf61.jpg)
@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
After finishing all, clear your cache.

**Comment by GreenDragonTavern** [comment]
> After finishing all, clear your cache.

Guess the question is why have cache when it takes manual intervention to eliminate what should be a normal process? Go live, shows on front page, live ends, remove from front page.

**Comment by milehighkaraoke** [comment]
I never had to do this until the last get pulled can you please figure out what's wrong

**Comment by DanielnetoDotCom** [comment]
Agree, but for now, I do not know what is causing that on your side. I could not reproduce it here

**Comment by guymass** [comment]
still after doing all the suggested above I still see them return to the home page and pop up again.

**Comment by guymass** [comment]
they still show on the page. isn't there a way I can manually stop them or remove them? the reset button doesn't work and I deleted /HLS/live/* several times. At first I had only one stream stuck now I have two.

![Screen Shot 5783-07-28 at 16 14 39](https://user-images.githubusercontent.com/58882903/233087299-27e321a1-3740-44ff-b4a0-928b99fcc486.jpg)

**Comment by DanielnetoDotCom** [comment]
the last update may prevent this to happen again. For now you will need to clear the cache, but in the future, it may happen automatically

**Comment by guymass** [comment]
Great thanks!  for now they stopped, i`ll keep checking.

**Comment by guymass** [comment]
Its backm even after the update. Maybe this is an attack or my script is completely corrupt I will need to re install.

![Screen Shot 5783-07-29 at 1 40 57](https://user-images.githubusercontent.com/58882903/233215213-a8fd1b6d-92c0-42e6-beb9-04590c3bd0a7.jpg)

**Comment by DanielnetoDotCom** [comment]
when you stop the live you need to check the avideo logs

**Comment by milehighkaraoke** [comment]
Whatever you did it Fixed the issue on my end @DanielnetoDotCom

**Comment by guymass** [comment]
OK I can say that it also stopped for me but not before I had to create missing /HLS/live directories and after a while it stopped so for now I am closing this post.

**Comment by guymass** [comment]
Im just gonna post any error I see in logs until we find this little bugger. Here is the first batch:


![Screen Shot 5783-08-14 at 21 31 52](https://user-images.githubusercontent.com/58882903/236539936-c1e3e48b-7a33-4307-9fd3-fdb4b42b32e0.jpg)

![Screen Shot 5783-08-14 at 21 28 28](https://user-images.githubusercontent.com/58882903/236539296-0d067e2f-d64d-4156-8dd5-78748ec4fc27.jpg)

![Screen Shot 5783-08-14 at 21 30 13](https://user-images.githubusercontent.com/58882903/236539598-30e88d63-fcd8-4032-83cf-5dba67d26e86.jpg)


![Screen Shot 5783-08-14 at 21 32 06](https://user-images.githubusercontent.com/58882903/236539907-e555769a-c95b-4f16-8629-5489868816d6.jpg)

**Comment by guymass** [comment]
Could it be something to do with LiveTransmissionHistory?

![Screen Shot 5783-08-14 at 21 33 55](https://user-images.githubusercontent.com/58882903/236540310-a6404f2a-235d-4597-a6fa-74a7d25c2ec8.jpg)

**Comment by DanielnetoDotCom** [comment]
yes, it may be because of the history, but if you did this https://github.com/WWBN/AVideo/issues/7925#issuecomment-1530297923

live_transmitions_history should not be a problem. as long as I cannot reproduce I can not help

**Comment by guymass** [comment]
OK for now it seems the issue has subsided, things work better since last updates so for now everything seems to back to normal. I will keep testing and post a new thread if I find something else.
