### ISSUE TITLE
my error log is filled with this /HLS error

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7925]
I constantly see my error log getting filled with /HLS related errors. I don't know where they come from and how to stop them, can you please give me some insight into what to look for?

This even happens when no live stream is taking place and unless I recreate the folder and file the message will not stop. Even when I get all the directories _low _mid _hi created for each key with the respective index file and it stops for a while, it will return again within the hour.

This could be related to my other issue having live streams stuck on my home page.
Here is the SS of my error.log:

![Screen Shot 5783-07-28 at 5 34 24](https://user-images.githubusercontent.com/58882903/233146180-748dba15-7d0c-4bea-90fc-4d6c11642326.jpg)

Could this maybe be error in my site's nginx configuration? or is it something stuck in the script on my site? IDK.

**Comment by guymass** [comment]
I find that the only way to stop this continuous stream of error messages is to create the files and directories its looking for. All those error messages regarding many keys of users, some of which we reset manually ourselves, probably users who have tried to live stream at some point or have done a live stream. For now I managed to stop the errors manually but I need a solution please,

**Comment by guymass** [comment]
It looks like each account or new key needs to have its own folder in the /HLS/live directory and only inside those does the index.m3u8 gets cleaned up, but the directories need to remain other wise my error logs get bloated and creates many GZ files on my server.

**Comment by DanielnetoDotCom** [comment]
the error is probably because a live is already finished and someone still has an open page.

**Comment by guymass** [comment]
Well I don't know. The problem is they show up again, specially this particular channel. I keep going back and creating any missing directories and files under the /HLS/live which is comping from nginx.

BTW I am running nginx 1.18 so I haven't been updated regarding if we can also update that. Currently the system on my site is a bit buggy but well done on the rest of really great improvements.

**Comment by guymass** [comment]
now suddenly I begin to see these appearing as well:
![Screen Shot 5783-07-29 at 11 39 31](https://user-images.githubusercontent.com/58882903/233317098-34b7ce94-f934-40e5-b3d1-a7bb4afb34a0.jpg)

but for now this is what make my stuck live streams to close finally. I believe this issue has to be related to my other issue. This needs to be addressed. My nginx is using the www-data user and my /HLS/live directory is also set to www-data user permissions, but still I keep seeing those error indicating it cannot create those needed folders on the fly and than remove what ever needs o be removed. Instead, something is getting stuck in this stage.

**Comment by DanielnetoDotCom** [comment]
there is nothing I can do regarding your nginx logs but seems to me your folders do not have the propper permissions

**Comment by DanielnetoDotCom** [comment]
your logs say it does not have the proper permission

and this is a nginx error, nothing regarding avideo code

**Comment by guymass** [comment]
but what does it mean? Those are account stream keys are they not?

re these not keys? why are they bothering my nginx? is this coming from the network encoders? Am I being hacked?
should I disregard those error? and finally, do those directories need to be created at all?

641d97a130574-1
643ee1f24e57c-1

$ tail -f /var/log/nginx/error.log
2023/04/20 17:40:16 [error] 116224#116224: hls: cleanup unlink() failed on '/HLS/live/641d97a130574-1_hi/index.m3u8' (13: Permission denied)
2023/04/20 17:40:16 [error] 116224#116224: hls: cleanup unlink() failed on '/HLS/live/643ee1f24e57c-1_low/index.m3u8' (13: Permission denied)

**Comment by guymass** [comment]
So now I started another live stream test for about an hour, the live was great I closed it, closed my OBS, the stream was successfully encoded however choosing the wrong encoder imo, then created the post  and then it got stuck on my home page still showing a live stream taking place when its not. Here are some screen shots of what I found in the logs.

![Screen Shot 5783-08-02 at 18 28 13](https://user-images.githubusercontent.com/58882903/233849059-db687d6c-e74b-4e97-a8bf-16997caea29d.jpg)
![Screen Shot 5783-08-02 at 18 27 46](https://user-images.githubusercontent.com/58882903/233849071-f30bf59d-f17c-4786-8e5c-962f8b757f41.jpg)
![Screen Shot 5783-08-02 at 18 20 58](https://user-images.githubusercontent.com/58882903/233849080-414f38ba-f9fe-475c-b6b1-f1c6a755d13c.jpg)


Now I will try to use the button but that is not a solution. There is a problem and I can pin point it exactly and I think it also has todo with the /HLS directory issue I have.

**Comment by guymass** [comment]
I think it could be related this file offlineVideo.php. Nothing I do removes it from my home page, of course i've done the usual cache clearing, only thing left is to ry to restart the servers apache and nginx and see whats in the logs.

**Comment by guymass** [comment]
OK this is new, now I see the same old Live stream of this user Anthony Patch, only that now his stream name is actually the name of my last stream name. Now every live gets stuck. I still think it's something to do with the HLS directory idk what to to do anymore. Maybe I need a database maintenance or to remove and recreate this "Anthony Patch" user.

**Comment by DanielnetoDotCom** [comment]
I saw in one of my clients, the live_transmitions were duplicating the record per user, so I suspect you are facing the same issue
Try to clear some tables

```sql
delete from live_transmition_history_log where id > 0;
delete from live_transmitions_history where id > 0;
delete from live_transmitions where id > 0;
```
all the keys will be reset

**Comment by guymass** [comment]
OK I reset all key and hope this will work because I had to write a python script to handle all those errors and automatically create the correct directories and files with the right permissions and so far it was working not bad. I hope now it will stop. I will keep checking and post back or close if all is well finally. 

Much thanks for the help much appreciated.

**Comment by guymass** [comment]
We are not all streaming and getting this user name Anthony Patch as the name for our live stream, something  is seriously wrong with this issue, idk what to do anymore.

**Comment by guymass** [comment]
I don't know about his errors, it just that user names are mixing on live stream. When Shay goes live his user name now appears to be Anthony Patch, or at least it take the values for the stream information from the last stream of a different user.
I for sure don't have enough knowledge about the script to find this bug I can only post what I see but im still investigating.

I will try to remove that user's account  or close it and set him with a new account and see how it works in couple of days/

**Comment by guymass** [comment]
OK since last updates this issue seems to be gone, I will keep testing if something else comes up, for now im closing this thread.
