### ISSUE TITLE
Where do I save the .srt file?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7929]
**Describe the question**
I've got my back end set up to use Vosk to create .srt files automatically 

what do I need to do to inform AVideo of them? Copy to the same directory as the video file? Naming identical? Any database action necessary?

second question. I'm having the AI generate a ton of metadata from the content. How can I get this stored back in AVideo the right way? Can we add a database migration to a plugin to get some extra juice in the database or am I better off setting up a parallel database? Doing things like feature and keyword extraction, sentiment analysis. Goal here is AI powered "up next" list a. la. YouTube.

**Comment by DanielnetoDotCom** [comment]
Regarding your first question, to inform AVideo of the .srt files created by Vosk, you would need to copy the files to the same directory as the video file and name them identically. However, I would like to note that the HTML 5 player in AVideo supports vtt files, not srt files. Therefore, you may need to install the plugin SubtitleSwitcher to add the subtitles to your videos.

As for your second question, unfortunately, there is no easy solution for adding the metadata generated by Vosk to AVideo. This would require a more elaborated design to handle the new metadata. You could potentially explore adding a database migration to a plugin to get some extra juice in the database or setting up a parallel database. However, doing things like feature and keyword extraction and sentiment analysis would require significant effort and resources to implement in AVideo. The goal of an AI-powered "up next" list a la YouTube is definitely achievable, but it would require a more complex and customized solution than what AVideo currently offers.

**Comment by DanielnetoDotCom** [comment]
FYI, I will release the SubtitleSwitcher version 4 which will automatically extract the transcription with vosk-transcriber

**Comment by walt93** [comment]
Daniel, in my system I used RabbitMQ/Celery to build a task scheduler, and configured a bunch of parallel tasks to run to keep all the server cores busy. 

I think you want something similar, people might have a lot of back catalog videos to generate subtitles for.
