### ISSUE TITLE
Wrong Encoder Set

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7932]
I keep having my network encoder set the wrong encoder as the primary one. For example, if I have an encoder off line, the network encoder will not move to the next available encoder. It will get stuck on the one that was set, and I dont know how it is set.

How can i set the primary encoder and second how can we make it check which encoders are available and online, which is more free to use and select that one. Other wise any live stream can send the live stream to an offline encoder and it will all be lost.

![Screen Shot 5783-08-01 at 1 26 55](https://user-images.githubusercontent.com/58882903/233744141-1fba445b-8728-4a22-abee-b161cf783f07.jpg)

**Comment by guymass** [comment]
Again even when I change the priority of the encoders my live stream will still got to the second encoder and not the first. They are both online and the first is the local one, it should be the main and only if it is overly capacitated in the queue does the second encoder should be selected. I just don't get how the selection works here.
![Screen Shot 5783-08-02 at 17 58 05](https://user-images.githubusercontent.com/58882903/233847335-7c5665cf-91a4-485b-8b1d-b3a5322347f8.jpg)

**Comment by guymass** [comment]
Ok so I just installed a new encoder server and what I have noticed that the encoder name in the Admin Panel/ Site Settings has changed to the new encoder4 and before it was constantly set on encoder3. Whenever I try to change the url of the encoder and save, after I refresh the page the old encoder url is still there. For some reasonI cannot change and save this value even though the Save shows successfully.

I need to be able to change this value even manually in the database because  need to control which encode is the default for each site. Please take a look into why this is happening. Here is my SS:

![Screen Shot 5783-08-04 at 16 41 32](https://user-images.githubusercontent.com/58882903/234296597-2c279dfc-fcb6-4428-a3f5-e0ce4ec456e7.jpg)

Now I cannot save my new URL what can I do? Nothing in logs so far.

**Comment by guymass** [comment]
This is on all sites, as soon as a new encoder is added to the network encoders list all sites sing it will point to it so I recon there is something there I can use to set the default encoder for the site. IMO there should be a button in the network encoders to selects the default encoder for that site, it is a needed feature.

**Comment by DanielnetoDotCom** [comment]
I am lost, what is that? encoder network?

encoder network will use what ever you have in the database

**Comment by guymass** [comment]
but its alway stuck on the last installed encoder. If I have three is will always select the same one. I need to be able to set the default encoder per site.

**Comment by DanielnetoDotCom** [comment]
if you want a default encoder, do not use the network. just specify the encoder in the site configuration menu.

**Comment by guymass** [comment]
but I want to use the network encoders, this is not an option, the network encoders should be able to set. Why am I not able to save it in the Admin Panel Site settings?

**Comment by DanielnetoDotCom** [comment]
The network will decide what encoder you will use, it will try to get what is available. 

if you want to specify an encoder, the network does not make sense to use.

**Comment by guymass** [comment]
Still its constantly choosing the same encoder which is a remote one instead of using the local one when its free. anyway it would be good to be able as admin to have more control of this just in case I want to still set a default encoder per server.
