### ISSUE TITLE
Can we change the wording to be more inviting to Sign up or Create Account

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7933]
Would be better to have the words   "Log In Or Create an Account" Just some way to make it more inviting for users that want to comment or like and don't have an account, 

![e7900de5-8a51-47e1-90b1-05d3899927d8](https://user-images.githubusercontent.com/39392449/233750399-b72f1e82-a141-4171-97dd-27ed6855f2b8.png)

**Comment by DanielnetoDotCom** [comment]
Allowing users without accounts is really dangerous, it can attract a lot of trolls. strongly not recommended

regarding the reword it can be improved, I just did not decide yet what it would be

**Comment by JoshWho** [comment]
No no, not guest just an easy crest account button

**Comment by JoshWho** [comment]
Create account button

**Comment by JoshWho** [comment]
I am talking about the wording. Instead of it just saying Login

**Comment by DanielnetoDotCom** [comment]
I cannot guarantee I will add it now, but I am open for ideas

**Comment by JoshWho** [comment]
Sweeet
