### ISSUE TITLE
Set Automatic Subtitle for a Video

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7934]
Would be a great feature if we could set the subtitle for a video one exists so that it will be loaded and selected automatically with the video. What do you think, is it possible?

**Comment by walt93** [comment]
You can already upload a srt file manually. Would you like one generated automatically? I've got a solution 90% done sans integration...

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/issues/7929
