### ISSUE TITLE
Live stream OFFLINE IMAGE

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7936]
Why when I start live stream the notification on home page will display the live stream with an OFFLINE image?

![Screen Shot 5783-08-02 at 17 31 21](https://user-images.githubusercontent.com/58882903/233845883-5b986c95-b2ac-4398-824e-ed0bfa529845.jpg)

How do I change this Image or fix this so is shows the LIVE preview.

**Comment by guymass** [comment]
after a min or so is shows me those two, but still the black  one should be something from the video no?

![Screen Shot 5783-08-02 at 17 40 26](https://user-images.githubusercontent.com/58882903/233846315-7257aa8b-11f0-4304-9266-b4ccafb84eb9.jpg)
![Screen Shot 5783-08-02 at 17 40 32](https://user-images.githubusercontent.com/58882903/233846317-add4d864-c877-4ae6-a1ed-187f8fe8c3e1.jpg)

**Comment by milehighkaraoke** [comment]
Upload an image

![Screenshot_20230423_112744_Chrome](https://user-images.githubusercontent.com/70327833/233855243-33b780ba-56e8-44dc-9e98-a042de8ad7e8.jpg)
![Screenshot_20230423_112734_Chrome](https://user-images.githubusercontent.com/70327833/233855247-7f051d78-5424-43f7-9677-11a571bb9d6c.png)

**Comment by guymass** [comment]
OK great I will try that and see how it works.
