### ISSUE TITLE
Encoder/videos/ is full of thumbnails

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7938]
I have about 200k files and folders of thumbnails inside my Encoder/videos directory, are they suppose  to be there?
Can I delete them?

![Screen Shot 5783-08-02 at 21 57 42](https://user-images.githubusercontent.com/58882903/233859535-c2e6487e-86cf-4ec2-8f2c-e73a8200a026.jpg)

**Comment by DanielnetoDotCom** [comment]
you can delete those folders safely, also there is an encoder update to avoid creating unnecessary files. so the folder size will be a lot smaller
