### ISSUE TITLE
Subtitleswitcher broke Twittercard SEO header too large

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7955]
This just started after latest gitpull from last night.

![2558055d-7a0b-460f-9f6b-64ccdb048d46](https://user-images.githubusercontent.com/39392449/235016555-3a886632-a3e3-46d5-87b7-ae881511e4e9.png)

![download (53)](https://user-images.githubusercontent.com/39392449/235017010-358fa3ea-248a-4449-b8bc-331d10e139ed.png)

Testing with link https://www.joshwhotv.com/v/.7Hy4eA

ERROR: Fetching the page failed because the response is too large.

from https://cards-dev.twitter.com/validator

**Comment by DanielnetoDotCom** [comment]
I have never seen that error, but I suspect your ads are too big images, maybe that is the reason.

https://ads.joshwho.net/www/images/a39b54d7de672cad3a0dd4401a2623fc.gif

![image](https://user-images.githubusercontent.com/18009293/235029668-b81b596c-eb30-45d8-a364-b88ee7328313.png)


Try to replace your ads with a webp image animation, or just a static image.

**Comment by JoshWho** [comment]
I revert back and it works fine. New git does this

**Comment by DanielnetoDotCom** [comment]
humm, do you mean the last git pull made this?

**Comment by JoshWho** [comment]
Correct

**Comment by DanielnetoDotCom** [comment]
for me still the error

**Comment by JoshWho** [comment]
thats not behind cloudflare

**Comment by DanielnetoDotCom** [comment]
what do you mean? I am testing https://www.joshwhotv.com/v/.7Hy4eA

**Comment by JoshWho** [comment]
In the twitter card tool test

**Comment by DanielnetoDotCom** [comment]
![image](https://user-images.githubusercontent.com/18009293/235030499-29f05ba3-2589-48ac-8846-fccdf74ec147.png)

**Comment by JoshWho** [comment]
correct

**Comment by DanielnetoDotCom** [comment]
still not working for me, and you said you did revert and works for you

**Comment by DanielnetoDotCom** [comment]
my tutorials site is in the latest git pull and works fine

![image](https://user-images.githubusercontent.com/18009293/235030719-8537d7c3-11f6-406e-bd7c-b1d13c09bb3d.png)

**Comment by JoshWho** [comment]
```
<html>
<body>
<!--StartFragment-->

<meta name="twitter:url" content="https://www.joshwhotv.com/video/.7Hy4eA/chunk-yogurt-tyt-incites-tranies-to-get-guns-and-rifles-days-before-the-nashville-shooting"/>
--
  | <meta name="twitter:title" content="Chunk Yogurt TYT incites tranies to Get Guns and Rifles days before the Nashville Shooting"/>
  | <meta name="twitter:description" content=""/>
  | <meta name="twitter:image" content="https://static.joshwho-cdn.com/videos/video_230328201452_v3b63/video_230328201452_v3b63.jpg?cache=16800544721680054472"/>
  | <!-- ld+json --><!-- ld+json videos_id 78889 -->

<!--EndFragment-->
</body>
</html>
```

**Comment by JoshWho** [comment]
That is the only data it is trying to read.

**Comment by DanielnetoDotCom** [comment]
so I have no idea what is the error

**Comment by JoshWho** [comment]
I think it has something to do with the cache plugin

**Comment by DanielnetoDotCom** [comment]
no idea, I cannot see a reason. I can only see the ad's image size, try to disable it and try again.

**Comment by JoshWho** [comment]
That has nothing to do with this

**Comment by DanielnetoDotCom** [comment]
you should at leas try, I have no other idea

**Comment by JoshWho** [comment]
I don't want to break another thing is what I am trying to prevent'

**Comment by JoshWho** [comment]
Look https://twittercommunity.com/t/error-fetching-the-page-failed-because-the-response-is-too-large/170295

**Comment by JoshWho** [comment]
maybe it was 2 git pulls ago

**Comment by JoshWho** [comment]
What increased the headers size?

**Comment by JoshWho** [comment]
Ads are disabled still same problem

**Comment by JoshWho** [comment]
You still there?

**Comment by JoshWho** [comment]
This worked for 5 years on twitter and now all of a sudden it stopped. I didn't change anything.

**Comment by JoshWho** [comment]
Subtitle Switcher is the newest change to the headers. Why couldn't that been said? I am now looking at this in the fb debug and yes the header is over the twitter limit  with the new stuffed subtitle switcher

**Comment by JoshWho** [comment]
I re enabled the ads

**Comment by JoshWho** [comment]
This is specifically a problem with the HTTP headers size for this site - it exceeds 8192 bytes which is larger than the crawler will accept. The content-security-policy-report-only field is nearly 8k in total.

THis could also explain the TTFB being slow

@DanielnetoDotCom

**Comment by JoshWho** [comment]
> you should at leas try, I have no other idea

This is specifically a problem with the HTTP headers size for this site - it exceeds 8192 bytes which is larger than the crawler will accept. The content-security-policy-report-only field is nearly 8k in total.

THis could also explain the TTFB being slow

@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Got it. 

the problem is that in the last update, we were listing the tags, to improve the search

you had thousands of tags, but now I am only listing the 100 first tags with more videos in it. 

it should work now

**Comment by JoshWho** [comment]
Sweeet. Do I need to git pull or did you already do that?

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
> Sweeet. Do I need to git pull or did you already do that?

I did already

**Comment by JoshWho** [comment]
Thank you
