### ISSUE TITLE
XSendFile issue

### ISSUE THREAD

**Issue by gujarraju** [WWBN/AVideo#7961]
Hello Mr. Denial,

My XSendFile is not enbled. plz help me.

![image](https://user-images.githubusercontent.com/35865505/235142437-b9b44a9c-a931-4dd3-9878-c6ea49e84efb.png)

<Directory /var/www/html/YouPHPTube/>
    Options Indexes FollowSymLinks
    XSendFile on
    XSendFilePath /var/www/html/YouPHPTube/
    AllowOverride All
    Require all granted
    Order Allow,Deny
    Allow from All
</Directory>

**Comment by DanielnetoDotCom** [comment]
try to restart apache.

**Comment by gujarraju** [comment]
still same

**Comment by gujarraju** [comment]
Hi ,
My Apache error log.

[Sat Apr 29 09:25:03.973302 2023] [php7:notice] [pid 311334] [client 172.70.219.144:17584] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://www.yooyoutube.com/sw.js?0.10896306666752964
[Sat Apr 29 09:25:15.567450 2023] [php7:notice] [pid 311890] [client 162.158.22.160:9698] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.9532036881527013
[Sat Apr 29 09:25:17.341548 2023] [php7:notice] [pid 311775] [client 172.70.189.45:41726] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://yooyoutube.com/sw.js?0.9320308880551007
[Sat Apr 29 09:25:45.317569 2023] [php7:notice] [pid 311971] [client 172.69.111.161:18864] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.8404932642974747
[Sat Apr 29 09:25:57.301965 2023] [php7:notice] [pid 309197] [client 172.71.202.171:58612] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.039810227214202354
[Sat Apr 29 09:26:10.947132 2023] [php7:notice] [pid 312007] [client 162.158.22.44:12062] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.4486431026037483
[Sat Apr 29 09:26:11.638645 2023] [php7:notice] [pid 312024] [client 162.158.95.65:10898] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.22730464266256423
[Sat Apr 29 09:26:55.741011 2023] [php7:notice] [pid 312230] [client 162.158.86.122:17220] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.5772725829638541
[Sat Apr 29 09:27:21.743794 2023] [php7:notice] [pid 311591] [client 108.162.226.246:16712] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.7517936381599561
[Sat Apr 29 09:27:49.036436 2023] [php7:notice] [pid 312431] [client 162.158.22.45:54914] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.6590068910327187
[Sat Apr 29 09:27:51.849838 2023] [php7:notice] [pid 312470] [client 162.158.110.129:39040] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.5887673286873223
[Sat Apr 29 09:28:11.260273 2023] [php7:notice] [pid 311591] [client 172.71.246.127:38846] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.9391408809055279
[Sat Apr 29 09:28:13.714980 2023] [php7:notice] [pid 312488] [client 172.71.135.74:13662] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.1791494288424984
[Sat Apr 29 09:28:30.031529 2023] [php7:notice] [pid 312412] [client 108.162.226.128:27964] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.4213111555025588
[Sat Apr 29 09:29:13.112978 2023] [php7:notice] [pid 312446] [client 162.158.190.28:28958] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.11665504968468965
[Sat Apr 29 09:30:04.617783 2023] [php7:notice] [pid 312698] [client 172.71.198.176:56852] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.5776294278510847
[Sat Apr 29 09:30:27.487398 2023] [php7:notice] [pid 313025] [client 162.158.95.66:64640] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.14348043959924084
[Sat Apr 29 09:30:33.017796 2023] [php7:notice] [pid 312227] [client 172.70.142.250:28872] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.07979234578952021
[Sat Apr 29 09:30:36.601609 2023] [php7:notice] [pid 312704] [client 172.71.102.45:48212] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.7295584180969401
[Sat Apr 29 09:30:43.858572 2023] [php7:notice] [pid 312218] [client 162.158.94.6:12046] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.8689758286400242
[Sat Apr 29 09:30:53.642554 2023] [php7:notice] [pid 312741] [client 172.71.186.30:14366] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://www.yooyoutube.com/sw.js?0.8480640854891575
[Sat Apr 29 09:30:54.878643 2023] [php7:notice] [pid 313044] [client 172.71.186.86:35342] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.10723645230754864
[Sat Apr 29 09:30:56.913306 2023] [php7:notice] [pid 313171] [client 162.158.111.18:39028] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.9540185452770222
[Sat Apr 29 09:31:24.306563 2023] [php7:notice] [pid 313056] [client 162.158.110.70:49036] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.6329383861029756
[Sat Apr 29 09:31:28.101817 2023] [php7:notice] [pid 312705] [client 172.69.59.93:37336] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://yooyoutube.com/sw.js?0.23707896261511485
[Sat Apr 29 09:31:30.837372 2023] [php7:notice] [pid 312440] [client 162.158.87.160:50932] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.441806754509128
[Sat Apr 29 09:31:43.301421 2023] [php7:notice] [pid 313171] [client 172.71.186.214:47658] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://www.yooyoutube.com/sw.js?0.06625270246623494
[Sat Apr 29 09:31:49.772096 2023] [php7:notice] [pid 313068] [client 172.69.46.136:13538] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.05562403356469825
[Sat Apr 29 09:31:59.031895 2023] [php7:notice] [pid 312684] [client 108.162.226.178:64796] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.5991682724560266
[Sat Apr 29 09:32:07.897040 2023] [php7:notice] [pid 312708] [client 172.70.218.128:53098] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://www.yooyoutube.com/sw.js?0.8446262113021421
[Sat Apr 29 09:32:21.926050 2023] [php7:notice] [pid 311979] [client 162.158.110.71:42416] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.6062500480429418
[Sat Apr 29 09:32:22.017143 2023] [php7:notice] [pid 312015] [client 162.158.106.101:25284] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.9900613883066474
[Sat Apr 29 09:32:31.851085 2023] [php7:notice] [pid 313315] [client 172.71.142.108:47088] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://yooyoutube.com/sw.js?0.6610686586454904
[Sat Apr 29 09:32:32.041775 2023] [php7:notice] [pid 313387] [client 172.70.142.102:47610] /var/www/html/YouPHPTube/view/../plugin/VideoOffline/offlineVideo.php, referer: https://mkt.yooyoutube.com/sw.js?0.5252161058298208
