### ISSUE TITLE
Connected users doesn't work very well these days (different failure mode desktop/mobile)

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7964]
**Describe the bug**
On desktop, won't show users.
On mobile, just shows disconnected.

Desktop:
![Screen Shot 2023-04-28 at 11 46 38 AM](https://user-images.githubusercontent.com/11711050/235228799-adfc16a7-2300-4e9e-b0b8-c381f3109ff8.png)

Mobile:
![IMG_DD6D3EB6398B-1](https://user-images.githubusercontent.com/11711050/235229245-af64ac16-b3f2-4ae5-a4bf-3c591056e1f1.jpeg)

**Comment by DanielnetoDotCom** [comment]
Can you please try to restart the socket?

**Comment by JoshWho** [comment]
Mine keeps crashing. Every so many hours I always have to manually restart it again. Is there a way to just make a cron check to see if running and if not run script ?

**Comment by walt93** [comment]
See https://github.com/WWBN/AVideo/issues/7976

**Comment by DanielnetoDotCom** [comment]
> Mine keeps crashing. Every so many hours I always have to manually restart it again. Is there a way to just make a cron check to see if running and if not run script ? average around usually it says 300 online
> 
> Like a auto restart socket server if not connected or something?

any idea why it is crashing?

any log?
