### ISSUE TITLE
embed video not working

### ISSUE THREAD

**Issue by gujarraju** [WWBN/AVideo#7973]
Hi Mr. Daniel,

I am trying to embed videos from https://vk.com/  blank screen is coming.

Please help me.

Ex: https://vk.com/video_ext.php?oid=-211446896&id=456242197&hash=dfb9e5cf72d758c2

**Comment by DanielnetoDotCom** [comment]
I can see something else in this link

**Comment by gujarraju** [comment]
Hi,

I want embed videos from  https://vk.com/

Ex: https://vk.com/video_ext.php?oid=-211446896&id=456242197&hash=dfb9e5cf72d758c2

**Comment by DanielnetoDotCom** [comment]
try to embed on demo site or share  a link in your site so I can inspect

**Comment by gujarraju** [comment]
Hi ,

Plz check..

https://demo.avideo.com/video/399/test-embed

**Comment by gujarraju** [comment]
Yes its working thank you.
