### ISSUE TITLE
System .service to manage YPTSocket

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#7976]
**Is your feature request related to a problem? Please describe.**
Every once in altogether too often my YPTServer is not working.

**Describe the solution you'd like**
Perpetual motion. If not that, for the system to restart it gracefully when it falls down.

**Describe alternatives you've considered**
Could we use a system service to manage YPTSocket?

**Additional context**
I think the solution looks like this. Please advise.

`sudo nano /etc/systemd/system/yptsocketserver.service`

```
[Unit]
Description=YPTSocketServer
After=network.target

[Service]
ExecStart=/usr/bin/php /var/www/html/AVideo/plugin/YPTSocket/server.php
WorkingDirectory=/var/www/html/AVideo/plugin/YPTSocket/
Restart=always
User=www-data

[Install]
WantedBy=multi-user.target

```

**Comment by JoshWho** [comment]
That looks like it will work. Thank you I will give this a shot tonight when I get home

**Comment by GreenDragonTavern** [comment]
Copied certificate files to /var/www/html/AVideo/plugin/YPTSocket/ and updated YPTSocket plugin to reflect same and works like a champ so far.

**Comment by DanielnetoDotCom** [comment]
I also create a scheduler that checks some ports and SSL in the default configuration

for example, for the live server, it should be installed here `/usr/local/nginx/sbin/nginx`

if you do not want the automatic checks, disable them in the plugin parameters

![image](https://user-images.githubusercontent.com/18009293/235941681-4478f88d-50cf-4e55-8a74-57b19dcacd00.png)

**Comment by GreenDragonTavern** [comment]
@DanielnetoDotCom you can use apt install for nginx, no need to compile nginx. You get the benefit of nginx service and nginx will get updated accordingly. Ubuntu 22.04 with AVideo/apache2 on same server:
```
sudo apt install software-properties-common ca-certificates lsb-release apt-transport-https
sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/nginx-mainline
sudo apt install nginx
sudo apt install libnginx-mod-rtmp
```
I breakout rtmp, control and http but using your default requires little modification to utilize the apt install of nginx.

/etc/nginx/nginx.conf
```
user www-data www-data;
worker_processes 1;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events { worker_connections 1024; }

rtmp { include /etc/nginx/conf.d/rtmp.conf; }

http {
	include       mime.types;
	default_type  application/octet-stream;

	access_log /var/log/nginx/access.log;
	error_log  /var/log/nginx/error.log info;

	# PHP max upload limit cannot be larger than this
	#client_max_body_size 10240M;

	# Upstream to abstract backend connection(s) for PHP.
	# This should match value of "listen" directive in php-fpm pool
	#upstream php { server unix:/run/php/php8.2-fpm.sock; }

	include /etc/nginx/conf.d/control.conf;
	include /etc/nginx/conf.d/http.conf;
}
```
/etc/nginx/conf.d/rtmp.conf
```
server {
	listen 1935;
	chunk_size 4096;
	timeout 30s;
	ping 5s;
	ping_timeout 30s;
	### Use case option (max_streams; default is 32 )
	max_streams 32;
	#max_message 1M;
	buflen 1s;
	# creates our "live" full-resolution HLS videostream from our incoming encoder
	# stream and tells us where to put the HLS video manifest and video fragments 
	application live {
		live on;
		on_publish      http://AVideoDomain/plugin/Live/on_publish.php;
		on_publish_done http://AVideoDomain/plugin/Live/on_publish_done.php;
		on_play         http://AVideoDomain/plugin/Live/on_play.php;
		on_record_done  http://AVideoDomain/plugin/Live/on_record_done.php;

		exec ffmpeg -re -i rtmp://AVideoDomain/live/$name
		 -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:240 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1200k -b:a 96k -r 20 -f flv rtmp://AVideoDomain/adaptive/$name_low
		 -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:480 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 2400k -b:a 128k -f flv rtmp://AVideoDomain/adaptive/$name_mid
		 -c:a aac -strict -2 -b:a 128k -c:v libx264 -vf scale=-2:720 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 4200k -bufsize 100000k -b:a 128k -f flv rtmp://AVideoDomain/adaptive/$name_hi;

		recorder video {
			record all;
			record_path /var/www/tmp;
			record_notify on;
			record_max_size 10240M;
			record_suffix -%d-%b-%y-%T.flv;
			#record_max_frames 30;
		}

		### Record Audio Separately ( For podcast )
		#recorder audio {
			#record audio;
			#record_path /var/www/tmp;
			#record_max_size 1024M;
			#record_suffix -%d-%b-%y-%T.mp3;
		#}
	}

	application adaptive {
		live on;

		hls on;
		hls_path /HLS/live;
		hls_nested on;
		hls_playlist_length 10m;

		allow play all;
		allow publish AVideoIP-Address;
		deny publish all;

		hls_variant _low BANDWIDTH=700000;
		hls_variant _mid BANDWIDTH=2100000;
		hls_variant _hi  BANDWIDTH=4200000;
	}
}
```
/etc/nginx/conf.d/control.conf
```
server {
	listen 8080;
	server_name localhost;
	root /var/www/html/live;
	location /control {
		allow 127.0.0.1;
		rtmp_control all;
	}
	#location ~ \.php$ {
	#	include /etc/nginx/snippets/fastcgi-php.conf;
	#	fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
	#}
}
```
/etc/nginx/conf.d/http.conf
```
server {
	server_name AVideoDomain;
	#listen	    8080;
	listen      8443 ssl;

	ssl_certificate     /etc/letsencrypt/live/AVideoDomain/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/AVideoDomain/privkey.pem;
	include             /etc/letsencrypt/options-ssl-nginx.conf;
	ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

	# creates the http-location for our full-resolution (desktop) HLS stream
	# - "http://my-ip/live/my-stream-key/index.m3u8"
	location /live {
		expires 60;
		add_header 'Cache-Control' 'public';

		location ~ \.m3u8$ {
			expires -1;
			# Disable cache
			add_header 'Cache-Control' 'no-cache';

			# CORS setup
			add_header 'Access-Control-Allow-Origin' '*' always;
			add_header 'Access-Control-Expose-Headers' 'Content-Length';
		}

		# CORS setup
		add_header 'Access-Control-Allow-Origin' '*' always;
		add_header 'Access-Control-Expose-Headers' 'Content-Length';

		# allow CORS preflight requests
		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Allow-Origin' '*';
			add_header 'Access-Control-Max-Age' 1728000;
			add_header 'Content-Type' 'text/plain charset=UTF-8';
			add_header 'Content-Length' 0;
			return 204;
		}
		types { application/vnd.apple.mpegurl m3u8; }
		alias /HLS/live;
	}

	root /var/www/html/live;
	# allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"
	#location /stats { stub_status; }
	location /stat {
		rtmp_stat all;
		rtmp_stat_stylesheet stat.xsl;
	}
	#location /stat.xsl { root /var/www/html/live; }
	#location /control {
		# replace this with the IP of your AVideo site
	#	allow AVideoDomain;
	#	deny all;
	#	rtmp_control all;
	#}
        # allows us to host some webpages which can show our videos: "http://my-ip/my-page.html
	location / {
	#	root /var/www/html/live;
		index index.html index.htm;
	}

	#location ~ \.php$ {
	#	include /etc/nginx/snippets/fastcgi-php.conf;
	#	fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
	#}
}
```

**Comment by walt93** [comment]
Question: @DanielnetoDotCom does your just now implemented Scheduler code augment or replace using the system service?

@GreenDragonTavern not tracking how the nginx changes are related, that's a bit much nginx code to take in in one sitting.

**Comment by GreenDragonTavern** [comment]
@walt93 - yes, should have put it somewhere else. Daniel mentioned where your nginx live should be and I quit using the compile method and just installed rtmp module after installing nginx. As mentioned, it's just easier to manage rtmp, control, http, start/stop service in addition to getting nginx updates when they occur.

**Comment by JoshWho** [comment]
After updating my socket server now doesn't work

**Comment by GreenDragonTavern** [comment]
***doesn't work*** - do you mean after making it a service? If so, what does ```sudo systemctl status yptsocketserver.service``` say?

**Comment by JoshWho** [comment]
May 03 21:55:04 joshwhotv.com php[30988]: SSL ERROR, we could not access the KEY file /etc/letsencryp
May 03 21:55:04 joshwhotv.com php[30988]: Your socket server uses a secure connection
May 03 21:55:04 joshwhotv.com php[30988]: Parameter [local_cert]: /etc/letsencrypt/live/live.joshwhot
May 03 21:55:04 joshwhotv.com php[30988]: Parameter [local_pk]: /etc/letsencrypt/live/live.joshwhotv.
May 03 21:55:04 joshwhotv.com php[30988]: Parameter [allow_self_signed]: 1
May 03 21:55:04 joshwhotv.com php[30988]: Parameter [verify_peer]:
May 03 21:55:04 joshwhotv.com php[30988]: Parameter [verify_peer_name]:
May 03 21:55:04 joshwhotv.com php[30988]: Parameter [security_level]: 0
May 03 21:55:04 joshwhotv.com php[30988]: DO NOT CLOSE THIS TERMINAL
May 03 21:55:04 joshwhotv.com php[30988]: 2023-05-03 21:55:04 Using: 17.56MB RAM Construct
lines 1-18/18 (END)

**Comment by GreenDragonTavern** [comment]
***www-data*** does not have rights to /etc/letsencrypt/live/live.joshwhot. I didn't want to give www-data rights so I just copied certificate files to /var/www/html/AVideo/plugin/YPTSocket/ and updated YPTSocket plugin to reflect same. A restart of service then worked.

**Comment by JoshWho** [comment]
will they still update when certbot runs?

**Comment by GreenDragonTavern** [comment]
No, you'll have to copy again unless you give www-data rights to read /etc/letsencrypt/live/yourdomain.

**Comment by JoshWho** [comment]
Im reverting back since @DanielnetoDotCom has this built in. Still dont know what broke my socket server now wont connect at all. I didn't change anything but add the server and started that

**Comment by JoshWho** [comment]
OK back in business Watchdog enabled now

**Comment by GreenDragonTavern** [comment]
A benefit of the service is it solves the zombie process that does occur with using socket via cron.

**Comment by JoshWho** [comment]
> A benefit of the service is it solves the zombie process that does occur with using socket via cron.

I would keep it if it didn't have the ssl issue. My site is in live production and that downtime killed all the live streams going.

**Comment by GreenDragonTavern** [comment]
setfacl solves that. ```sudo setfacl -R -m u:www-data:r /etc/letsencrypt/live/yourdomain```

**Comment by GreenDragonTavern** [comment]
Hmm, just changed the service user to root and modified plugin back to /etc/letsencrypt/live/domainname. A quick ```sudo systemctl daemon-reload``` and restart service. The cron job is under root so figured service user as root should not be an issue.
