### ISSUE TITLE
My logo always deletes if I modify admin config on another machine

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7978]
This keeps happening if I open admin configuration and make a change like on my smtp pass or something like that, I don't get why

![f7f9b17c-40ea-4ef2-8e50-1bac34747b53](https://user-images.githubusercontent.com/39392449/235827676-49371cb8-79aa-40d6-b83b-71d7383bf145.png)

![74193792-9964-4c66-8638-79f4eacc078c](https://user-images.githubusercontent.com/39392449/235828034-f4fb414f-dacb-476b-b6dd-24ef5e6de886.png)

**Comment by DanielnetoDotCom** [comment]
I do not have a solution, this is intermittent for me, and I am not sure what is happening. but this some times happen with me as well
