### ISSUE TITLE
Why does the Hashtag cut off twitter share links?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7984]
Go here and try to share to twitter https://www.joshwhotv.com/video/.7H75dQ/%F0%9F%94%B4joshwho-truth-intel-tv-seekingthetruth-%7C-joshwho-tv

**Comment by DanielnetoDotCom** [comment]
what do you mean exactly?

can you please screenshot?

**Comment by JoshWho** [comment]
![image](https://user-images.githubusercontent.com/39392449/236519817-ba3290c2-bbbd-49a5-8f46-46cf143cdee1.png)

**Comment by DanielnetoDotCom** [comment]
Unfortunately for security reasons, we need to clean up the titles that will be in URLs

**Comment by JoshWho** [comment]
> 

That is a bummer, The hashtag gets used so much in titles making it sharable people won't understand why it cuts off. Hopefully they figure out to just type the rest
