### ISSUE TITLE
Telegram and Matrix Integration

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7986]
Would it be possible to add telegram to the list of social shares? It would be nice to see some more Telegram integration or even better integration with Matrix Element, just imagine to be able to run my python bots inside the an integrated chat room from Matrix. 

For now a simple share to TG and Matrix would be nice :-), we use them both as we have our own private Matrix server.

**Comment by DanielnetoDotCom** [comment]
what is Matrix ?

telegram should be just a copy link, but there is a way to direct post into telegram?

**Comment by guymass** [comment]
I am sure there is, many WP sites now include TG in the social link. I will do more research and let you know what can be done.

Regarding matrix that is an awesome script as well based on RIOT CHAT. 

The server is https://matrix.org and the main app is https://element.io/ but you can use few other apps as well to connect to the chat server. I know NextCloud has a really nice integration of chatrooms in their script, I am using it on my cloud.

**Comment by DanielnetoDotCom** [comment]
I did not find how to add it to the matrix, but I just add WhatsApp and Telegram

**Comment by guymass** [comment]
Great much thanks will test it now.
