### ISSUE TITLE
Search seems to jam up now

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#7988]
It was fast a couple days ago, especially when I can now select a category, but it is now just locking when I try it

**Comment by DanielnetoDotCom** [comment]
what exactly are you doing?

**Comment by JoshWho** [comment]
any query I do just hangs

**Comment by JoshWho** [comment]
Is this just never going to work? Everytime I am in a debate and need to find a video real quick that whole real quick part seems to be impossible.

**Comment by JoshWho** [comment]
Anyone go to my website and try to use the search. Just put something simple in like "Apple "  watch what it does

https://www.joshwhotv.com

**Comment by JoshWho** [comment]
I am never going to get picked up by any huge investor just because of small things like this. Everytime I have people testing the site this is what they complain about the most. Why can't they search anything

**Comment by JoshWho** [comment]
I already lost 10 different opportunities from investors just because of these small things.

**Comment by JoshWho** [comment]
https://github.com/WWBN/AVideo/issues/7993

**Comment by JoshWho** [comment]
What is this? 
![32d922de-84c9-4d2b-8001-a391a9699316](https://github.com/WWBN/AVideo/assets/39392449/329dfd6f-db69-488e-8670-928a27b2bba3)

**Comment by JoshWho** [comment]
See do a search here with my JoshWho Search  for apple  https://search.joshwho.net/search?q=site%3Awww.joshwhotv.com%20apple&categories=general&language=en-US

Here is the search on the JoshWho TV site  https://www.joshwhotv.com/?search=apple&catName=history&tags_id=&created=&minViews=

**Comment by JoshWho** [comment]
I don't understand what happened. The search use to work a while ago. I do not even see the dropdown Search Live anymore

**Comment by JoshWho** [comment]
I have been researching this all week, I came to the conclusion, large php mysql websites need to be search indexed by a separate service. There needs to be a search bot engine that crawls all the links and and can index them for faster delivery to be served in large quantities. 

Need a Avideo Search Engine Spider

**Comment by DanielnetoDotCom** [comment]
I am checking your search, there is something weird, looks like a loop in it

**Comment by DanielnetoDotCom** [comment]
The first thing I found, there are Google bots searching pages that do not exist, I am not sure why, they are searching infinitely 

I just add a script so if it is a bot only search 10 pages maximum, I am still looking

**Comment by JoshWho** [comment]
> The first thing I found, there are Google bots searching pages that do not exist, I am not sure why, they are searching infinitely
> 
> I just add a script so if it is a bot that only search 10 pages maximum, I am still looking
> 
> it was searching millions of records for nothing, killing your server

Probably a new form of DoS

**Comment by DanielnetoDotCom** [comment]
maybe, 

that was the server variable

{"UNIQUE_ID":"ZGI9OqA1nNDEH@9TCsiG8QAAAAM","QS_SrvConn":"13","QS_IPConn":"1","QS_AllConn":"13","QS_ConnectionId":"16841598022667600325624","QS_EventRequest":"66.249.65.215","QS_Event":"66.249.65.215","QS_Block":"66.249.65.215","QS_Block_seen":"","proto":"https","HTTPS":"on","SSL_TLS_SNI":"www.joshwhotv.com","HTTP_HOST":"www.joshwhotv.com","HTTP_AMP_CACHE_TRANSFORM":"google;v=\"1..8\"","HTTP_CONNECTION":"keep-alive","HTTP_ACCEPT":"text\/html,application\/xhtml+xml,application\/signed-exchange;v=b3,application\/xml;q=0.9,*\/*;q=0.8","HTTP_FROM":"googlebot(at)googlebot.com","HTTP_USER_AGENT":"Mozilla\/5.0 (Linux; Android 6.0.1; Nexus 5X Build\/MMB29P) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/112.0.5615.142 Mobile Safari\/537.36 (compatible; Googlebot\/2.1; +http:\/\/www.google.com\/bot.html)","HTTP_ACCEPT_ENCODING":"gzip, deflate, br","PATH":"\/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin:\/sbin:\/bin:\/snap\/bin","SERVER_SIGNATURE":"<address>Apache Server at www.joshwhotv.com Port 443<\/address>\n","SERVER_SOFTWARE":"Apache","SERVER_NAME":"www.joshwhotv.com","SERVER_ADDR":"144.217.180.157","SERVER_PORT":"443","REMOTE_ADDR":"66.249.65.215","DOCUMENT_ROOT":"\/var\/www\/html\/YouPHPTube","REQUEST_SCHEME":"https","CONTEXT_PREFIX":"","CONTEXT_DOCUMENT_ROOT":"\/var\/www\/html\/YouPHPTube","SERVER_ADMIN":"webmaster@localhost","SCRIPT_FILENAME":"\/var\/www\/html\/YouPHPTube\/view\/modeYoutube.php","REMOTE_PORT":"46418","GATEWAY_INTERFACE":"CGI\/1.1","SERVER_PROTOCOL":"HTTP\/1.1","REQUEST_METHOD":"GET","QUERY_STRING":"v=.HmIv&page=8207&PageSpeed=noscript&lang=ar_SA&yptDeviceID=f598d979-a8c4-40d6-b2d2-49014c7caf68","REQUEST_URI":"\/view\/modeYoutube.php?v=.HmIv&page=8207&PageSpeed=noscript&lang=ar_SA&yptDeviceID=f598d979-a8c4-40d6-b2d2-49014c7caf68","SCRIPT_NAME":"\/view\/modeYoutube.php","PHP_SELF":"\/view\/modeYoutube.php","REQUEST_TIME_FLOAT":1684159802.26676,"REQUEST_TIME":1684159802}

**Comment by DanielnetoDotCom** [comment]
I guess your search is better now

**Comment by JoshWho** [comment]
> I guess your search is better now

Holy cow that is way faster. Thank you @DanielnetoDotCom
