### ISSUE TITLE
Transferring a channel to a new channel

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#7994]
I have this channel of a user that I think his account is what causing my live stream issues, so i suggested to open a new account for them to test the live stream from it for the time being so we can test further this issues. Assuming this solves the problem, they currently about 600 video embeds in their website. Is there a way to transfer all those videos and embeds into the new channel?
What can I do in such case where I have to set a new channel for the user?

**Comment by DanielnetoDotCom** [comment]
the easiest way is to update the users_id in the videos table.

**Comment by guymass** [comment]
Can you please elaborate a bit more? what do you mean? So if I change the users_id to the new channel user id then all will be moved to the new user and this will not effect the embeds on their website?

**Comment by DanielnetoDotCom** [comment]
correct. 

> Can you please elaborate a bit more? what do you mean? So if I change the users_id to the new channel user id then all will be moved to the new user and this will not effect the embeds on their website?
