### ISSUE TITLE
Uploading a PDF is recognized as a video

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8000]
I have been uploading PDFs to my site when suddenly it started to recognize my PDFs as videos and since then I cannot upload PDFs properly, what could the reason for this be? Is there a size limit to PDF files?

![Screen Shot 5783-08-18 at 23 49 26](https://github.com/WWBN/AVideo/assets/58882903/c515783b-2532-4f4a-96b0-2a94a60998d9)

**Comment by DanielnetoDotCom** [comment]
I just tested a pdf here and works fine, can you reproduce it on demo site?

**Comment by guymass** [comment]
It working now, not sure what happened but after updating and clearing cache I tried again and it worked, so maybe just something go caught in my  cache and wasn't cleared properly before. I am closing this.
