### ISSUE TITLE
No Sub Categories in Standard Edit mode

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#8002]
Hi Daniel,

In 'Standard' edit mode there are no **Sub Categories** found to select.

**Advande Mode**
![Snap4](https://github.com/WWBN/AVideo/assets/39981177/5c71a41e-d64c-44ee-8b62-29f98df2f3a6)

**Standard Mode**
![Snap5](https://github.com/WWBN/AVideo/assets/39981177/d7072b71-5563-4df0-8396-4e25382dd31f)

**Comment by DanielnetoDotCom** [comment]
thanks, check this update

**Comment by TLCReuver** [comment]
Work perfect now... th@nkz
