### ISSUE TITLE
Ads overlay plugin not working

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8010]
This plugin stopped working for some reason on our main site but on the test site it does work so I don't know what the problem is.

It does not show the code and the ad's screen opens but without its content, while on the test site same code works.

![photo_5783-08-20 14 03 02](https://github.com/WWBN/AVideo/assets/58882903/11f70094-4760-4f6c-b8bf-7a02a269a7ca)

On test site:

![photo_5783-08-20 14 05 38](https://github.com/WWBN/AVideo/assets/58882903/9b1e7ecf-0545-443b-bc64-541d26fcb056)

**Comment by DanielnetoDotCom** [comment]
be aware that ppv or subscription plugins will remove ads. 

If you have one of them try to disable it and check if the ads will show

**Comment by guymass** [comment]
We don't have either of these plugins yet. This issue is related to something else.

**Comment by guymass** [comment]
Plugin shows the following error in console:
![photo_5783-08-23 13 58 06](https://github.com/WWBN/AVideo/assets/58882903/2ac19679-2820-47e7-ae94-a52ef6f5e7b2)

**Comment by eitanwa** [comment]
Hi, I'll try to explain it another way
As soon as you activate the plugin, this background (of the ad) appears in all the videos
(even without uploading an ad code)
It appears on all channels and in all videos

![image](https://github.com/WWBN/AVideo/assets/85537931/37e38c7e-7a7d-4c50-937a-ba6306d98355)

For example this channel
It has no ad code at all
And so it is in all videos as soon as you activate the plugin

![image](https://github.com/WWBN/AVideo/assets/85537931/65e3e09b-f489-4713-a331-44bd1a1d229a)

**Comment by DanielnetoDotCom** [comment]
Thanks, can you please try to remove the comment?

I guess it should be blank to not appear the ads box

**Comment by guymass** [comment]
But if it is blank / empty, it shouldn't appear at all in the videos. It should only appear when there is content in the ad IMO. Is it possible to remove it from videos even when the plugin is on? So only when there is an add and the video or channel are set to allow adds in their videos will it appear. On Ad-Free videos this gray empty ad space should stay hidden.

**Comment by eitanwa** [comment]
Now I understand what the problem is
Strange I checked it earlier (pic)
However, I removed the check mark, now it's fine
But it's still a bug
Thank you


![image](https://github.com/WWBN/AVideo/assets/85537931/807d4853-5c3a-4c36-820d-ffc14433862e)

**Comment by DanielnetoDotCom** [comment]
did you delete the comment from the user?

**Comment by eitanwa** [comment]
Yes I tried at first it didn't help
I removed the marking from the background as in the picture and it helped
 
But now although the background has gone down, he does not receive the code
Two sites, same plugin, same settings and one doesn't work, what could be the reason?

**Comment by eitanwa** [comment]
sure 
site
https://tube.feisafe.com/

A link to a video that shows that the ad plugin is working fine and working great
  on the site
  
   https://tube.feisafe.com/article/69/%D7%91%D7%A0%D7%99%D7%AA-%D7%90%D7%AA%D7%A8%D7%99%D7%9D?channelName=EitanwaAdmin
  [A link to a website that doesn't work (ads plug)
](https://alive528.com/)

**Comment by DanielnetoDotCom** [comment]
there is no overlay on the site you have mentioned and it is not working. please point a direct link to the video.

**Comment by guymass** [comment]
What do you mean by "no overlay"?

**Comment by eitanwa** [comment]
Link to a video with an ad
https://tube.feisafe.com/v/69

A link to a site where the ad code doesn't work
https://alive528.com/

tnx 
eitan

**Comment by DanielnetoDotCom** [comment]
it is something in your ads provider

![image](https://github.com/WWBN/AVideo/assets/18009293/923def9b-b9a5-4da0-805d-fdc9c68b383c)

the ads code is there but it is returning nothing. 

![image](https://github.com/WWBN/AVideo/assets/18009293/581debdf-d134-4a57-aa72-2d048d780a6e)


you may want to contact your ads provider

**Comment by guymass** [comment]
I made a new installation on a VM just to test this bug. We tried to set a new AD and load it on few videos we uploaded to the site and we get the same issue. We cannot see the AD all we get is a grey box. Now since this is a new installation the logs will be much cleaner and I hope to be able to pinpoint this bug.

Just a question I would like to know. Currently this installation only uses Apache, there is no Live stream and I haven't setup yet the NGINX part. Does the ADs plugin need to use nginx in anyway? My guess is that it doesn't but I wan't to make sure.

**Comment by guymass** [comment]
What we were doing is creating a post where we upload the ad to it, then we use the generated URL from the post and we put that URL in the AD. This is working well on feisafe.com site but not on the main Live site or this new installation.

**Comment by DanielnetoDotCom** [comment]
you may want to use the docker version https://github.com/WWBN/AVideo/wiki/Running-AVideo-with-Docker

**Comment by guymass** [comment]
On the new installation we have found this error while we were trying to save the AD which is our own created gif file. Here is a screenshot from the log:

![Screen Shot 5783-09-23 at 22 22 44](https://github.com/WWBN/AVideo/assets/58882903/0913b82e-cffb-4b5a-b793-e389865665be)

However I have a working installation on feisafe.com with no issues. Does the AD server rely on RTMP? on the NGINX configureation or does apache is enough for it to work?

**Comment by guymass** [comment]
The I have no idea why on one installation it works on the other is doesn't, both installations are the same, only difference is that one had the live server and the other doesn't. We are not using ads from google or any other source. We create our own gif, we upload it to a post and use the post's URL as the AD. It works on one of them so why not the other?

**Comment by DanielnetoDotCom** [comment]
the only way to find out is if we find some clue in the logs

**Comment by guymass** [comment]
Maybe this? Maybe the plugin is looking for a google URL or some other ad provider but the URL is generated from a local post from the site. Maybe plugin should be set to also receive other urls or simply just images, gifs etc...

![photo_5783-10-01 03 27 28](https://github.com/WWBN/AVideo/assets/58882903/9c45264d-f31e-4606-a7fa-7e8c91850428)

**Comment by DanielnetoDotCom** [comment]
I guess you are confusing things, AD_Server has nothing to do with overlay plugin

**Comment by guymass** [comment]
Well I don't know how it all works, as there are three ad plugins. All I know is that on one site when we use our created URL for the AD it works and shows just fine on the videos while on the second site it doesn't.

**Comment by guymass** [comment]
Currently not using ADs so im going to close this issue until we test ads again in the future.
