### ISSUE TITLE
ads on chanel

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#8011]
Hey
When you check the boxes of do not show ads on this channel
In practice it works but the box doesn't stay checked
It can be confusing
Actually what I do is I press it again and then it turns on or off

Thanks eitan live528
Thanks for your great work mate

![image_2023-05-11_16-39-00](https://github.com/WWBN/AVideo/assets/85537931/288bbc21-1878-47ca-afee-4d285b7cdfb9)

**Comment by DanielnetoDotCom** [comment]
thanks, this update may fix it

**Comment by eitanwa** [comment]
tnx you
