### ISSUE TITLE
Im still having a hard time logging in

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8018]
Now I got other users saying the same thing. It just sits and hangs once you click the sign in button

![7f47cb7c-359a-4b29-81b4-4fb20fe29664](https://github.com/WWBN/AVideo/assets/39392449/8d2eeed1-cb14-4766-847b-c687f7cdcaef)

**Comment by JoshWho** [comment]
Any word on what this is @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Josh, I just try and it works for me. not sure what issue you are facing. 

look for a js error

**Comment by JoshWho** [comment]
No try with my Seekingthetruth login  other accounts work fine just certain ones do this

**Comment by JoshWho** [comment]
As a admin I can login to that but I cannot log using the normal log in form, and other users are also having the same issue

**Comment by JoshWho** [comment]
This has to be something with maybe the login username having spaces or something similar.

**Comment by DanielnetoDotCom** [comment]
I am sorry for the delay answer it, I was about to test it on your site, but I am glad it is working now. 

just asking, did you reset your password with the same old password? just recreate it?

I want to make sure the issue is not related to some character in the password.

**Comment by JoshWho** [comment]
I made it back to my same password it was. I also changed the name field because it kept showing it as SeekingTheTruth JoshWho   and now just what the username was.

**Comment by DanielnetoDotCom** [comment]
Thanks for the info, and it still good correct?

**Comment by JoshWho** [comment]
> Thanks for the info, and it still good correct?

Yup working good now
