### ISSUE TITLE
[Q.] So, about those .srt files

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8033]
**Describe the question**
Ok I am at the point of coding my back-end where I start to do the AI stuff.

I have to have the vosk subtitles here to work with, so I'm vosking the video right when I'm uploading it to the streamer site.

How do I compute where the video's directory is? What's the algorithm to derive both the path and the filename? Can you point me the code that goes from a videos.id to a /some/where/on/the/disk/video349432432422423_somthing.mp4 lives?

I think if I just copy the .vtt file* there it could just work? 

_*I believe you said that is the format, please confirm_

**Comment by DanielnetoDotCom** [comment]
First, the Subtitle switcher is required. 

then you should save the .vtt file with the same file name as the video. 

![image](https://github.com/WWBN/AVideo/assets/18009293/8af9730c-21d2-47c5-90e4-02c28ed69675)

the srt is useless for HTML 5 players.

**Comment by DanielnetoDotCom** [comment]
If you get the plugin, you should use this 

https://github.com/WWBN/AVideo/wiki/Video-Transcription-for-the-SubtitleSwitcher-Plugin

that will be the easiest solution for you

**Comment by walt93** [comment]
Daniel-

What I need is to hook into the pipeline - when vosk'ing is done, I need to immediately queue a bunch of other tasks. I need to control when the vosk'ing is done, for instance, new media when it comes in - I want that vosk'ed first, then, old media, I want vosked by date, most recent files get vosking first.

If there is a way to turn of AVideo vosk'ing that would be ideal.

**Comment by DanielnetoDotCom** [comment]
I guess for you the best option would be to create a custom AVideo plugin and create a method `public function afterNewVideo($videos_id)`

For example https://github.com/WWBN/AVideo/blob/bc1b2619f9ca93982603ffd6b394d8f2836a5aa0/plugin/CustomizeUser/CustomizeUser.php#L669-L687

**Comment by walt93** [comment]
Hmm… ok so getting back to this, I'm going to create an empty plug-in and give it this afterNewVideo code

basically what I want to do is POST to https://yada.yada.yada/api/ingest-new-video&id=1234?apikey=XXXXX right here then.

Ok this looks straightforward...
