### ISSUE TITLE
Ability to import other types of posts from other AVideo sites

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8038]
I would like to also have the ability like I import a video post URL from another AVideo site, the same with posts that contains files such as PDF. I have a PDF section one of my sites I would like to duplicate to another site without having to recreate all those posts again and upload all those PDF files. Trying to import them like I do with videos doesn't work, so this would also be a great feature  I think to be able to transfer and import any type of posts between two AVideo sites.

**Comment by DanielnetoDotCom** [comment]
Do you want to import only specific pdfs or all the site?

if is all the site including the pdf, you should try the clone plugin. 

for the pdf only I currently have no solution for this.

**Comment by guymass** [comment]
would be nice to import a channel as well. Anyway I hope you will take into consideration in the future. Cloning the whole site is too much. Either as a single post or a playlist or a complete channel would be good.
