### ISSUE TITLE
After Upgrade HLS Stopped working.

### ISSUE THREAD

**Issue by aridzonan13** [WWBN/AVideo#8040]
**Describe the bug**
After our recent upgrade HLS stopped working.

**To Reproduce**
Failure happens after unploading a video to the server.

**Expected behavior**

**Error Logs**
Provide the log files at the moment you found the issue.
If you are not sure how to find the log file, please check here https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![AVideo-bad-2023-05-19](https://github.com/WWBN/AVideo/assets/6320576/808173c3-f18f-43ce-8158-d3f5186d3afd)
![AVideo-Good-2023-05-19](https://github.com/WWBN/AVideo/assets/6320576/c9419372-cbbc-4bd4-9303-e0e7452abac5)

**Comment by para2022** [comment]
My HLS is also not working i noticed it over a week ago but have been focusing on the broken missing files issue.

**Comment by DanielnetoDotCom** [comment]
Similar issue 

https://github.com/WWBN/AVideo/issues/8019

**Comment by para2022** [comment]
No HLS still broken 

https://ourtube.co.uk/v/46020?channelName=OurTube

**Comment by DanielnetoDotCom** [comment]
Right here it says your video is inactive

![image](https://github.com/WWBN/AVideo/assets/18009293/daa43c70-d338-4b0b-a6b6-2f5665920a6d)

**Comment by para2022** [comment]
You can check now. I just dont like having broken stuff on the site for all to see so i turned it inactive.

**Comment by para2022** [comment]
Oh actually cycling it back to active seems to have fixed it. So another bug?

**Comment by DanielnetoDotCom** [comment]
Here is working

![chrome-capture-2023-4-20](https://github.com/WWBN/AVideo/assets/18009293/7262ae6b-34fb-4147-b418-48f06fd0407b)

**Comment by para2022** [comment]
All my streams generally do not play afterwards as they are encoded with HLS. But i need HLS as i have some HLS movies and removing it means those would not play. Its been happening for about 1-2 weeks this Dan but i ignored it as the broken files was more of a problem.

**Comment by para2022** [comment]
do you want me to encode another and show you?

**Comment by DanielnetoDotCom** [comment]
yes, try again

**Comment by DanielnetoDotCom** [comment]
make sure your streamer is up to date

**Comment by para2022** [comment]
I update daily you never need to worry about me not been up to date LOL. Just saving a stream il post link in a mo.

**Comment by para2022** [comment]
Here is the new one Dan

https://ourtube.co.uk/v/46026?channelName=OurTube

**Comment by para2022** [comment]
So cycling the video status is a bit of a clue whats going on. Similar to the broken files when the vid was clicked on it came back and worked. Now this seems to work when the status is cycled back to active again.

**Comment by para2022** [comment]
When i edited its title it started playing again LOL

**Comment by DanielnetoDotCom** [comment]
I suspect it is just a cache thing, I may review it next week

**Comment by para2022** [comment]
Ok this video was 1.2 GB mate he did a live stream and it was broken files. Now it is playing. 

https://ourtube.co.uk/v/45812?channelName=TalkingReally

So they are taking a really long time after conversion to actually play? It seems that way. However the user may delete it if its not playing straight away.

**Comment by para2022** [comment]
No biggie for now though if you plan on looking into it. I will just the live streamers to leave the video and not delete it for now. I only use HLS for streams so its not a massive biggie right now. Im just glad the broken files has been fixed so thanks a lot for that pal!

**Comment by para2022** [comment]
I cant find the donation link again 🤦‍♂️

**Comment by DanielnetoDotCom** [comment]
https://youphp.tube/

![image](https://github.com/WWBN/AVideo/assets/18009293/bf968709-6673-4d2f-9e87-3f451bdea624)


thanks
