### ISSUE TITLE
Encoder Server install Unknown Error No log

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8045]
![65f5667b-8a96-4a6d-96c7-8eb969c5c944](https://github.com/WWBN/AVideo/assets/39392449/03fb2cdc-06d9-4069-b6d3-ab3d7f35e94c)

This is a fresh install is there a certain type of mysql user need to be created for this? I am trying to use the root

**Comment by JoshWho** [comment]
https://encoder.corder.tv/install/index.php

For website  https://corder.tv

**Comment by JoshWho** [comment]
I used a fake username just to see if it would reject it and it did. It turned red and said wrong username so I know I am using the correct name and it is talking to the streamer site what else could be stopping this @DanielnetoDotCom ?

**Comment by JoshWho** [comment]
I figured it out. JUst make the root no password for mysql and boom it worked

**Comment by DanielnetoDotCom** [comment]
this is probably because your previews user cannot create databases and tables.
