### ISSUE TITLE
POST to MobileManager/upload.php is consuming too many resources (apparently trying to read entire file into memory)

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8047]
**Describe the question**
On the side of calling, we are running out of system memory, because apparently requests.post is retarded and reads the entire file into memory.

    upload_url = (
        f"{get_base_url(podcast.conspyre_server)}"
        f"/plugin/MobileManager/upload.php?user={secret['conspyre_username']}"
        f"&pass={secret['conspyre_password']}"
    )
        files = {"upl": file}
        response = requests.post(upload_url, files=files, data=data)

Suggested way of fixing this is using application/octet-stream which causes request.post to stream, like so:

```
with open(file_path, 'rb') as file:
    response = requests.post(upload_url, data=file, headers={'Content-Type': 'application/octet-stream'})

```
but this doesn't work, call fails & response back from upload.php indicates it's trying to parse an empty JSON ("Expecting value: line 1 column 1 (char 0)") and that makes sense because we switched the content type on it.

QUESTION (tl;dr) does upload.php support streaming?

**Comment by walt93** [comment]
It turns out there was a different way to solve it. For whatever reason octet-stream wasn't working, turns out we can solve it this way:


            m = MultipartEncoder(
                fields={
                    'upl': (os.path.basename(file_path), file, 'application/octet-stream'),
                    'data': json.dumps(data),  # Ensure data is in string format
                }
            )
            headers = {'Content-Type': m.content_type}
            response = requests.post(upload_url, data=m, headers=headers)

(ChatGPT 4 to the rescue lol)

**Comment by DanielnetoDotCom** [comment]
You can try to use my PHP script sample https://github.com/WWBN/Upload-Sample
