### ISSUE TITLE
Unable to Attach A User To a Plan On DiskUploadQuota Plugin

### ISSUE THREAD

**Issue by osvaldolivondeni** [WWBN/AVideo#8048]
Hi guys, I'm having some difficulties with the plugin DiskUploadQuota.

I am unable to attach a user to a quote using the plugin I bought. 

Something is missing in this tutorial: https://github.com/WWBN/AVideo/wiki/DiskUploadQuota-plugin

Creating a plan is easy. The problem is to attach a user to a specific plan.

Has anyone managed to link a user to a quota plan?

Thanks alot.

**Comment by DanielnetoDotCom** [comment]
There is no way to attach a user directly. 

the plugin is designed so your user can purchase a plan. 

I am pretty sure you can create plans that cost 0, and your users can subscribe in the plan for free. 

currently there is no way to manually add users into plans

**Comment by osvaldolivondeni** [comment]
Thank you very much for your answer, @DanielnetoDotCom .
