### ISSUE TITLE
Encoders in iFrame doesn't work

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8053]
On my other sites it works but on this new install for some reason even when I mark the checkbox to open the encoder inside an iframe it will still open it in a new tab.

![Screen Shot 5783-09-02 at 15 47 25](https://github.com/WWBN/AVideo/assets/58882903/93fe3ec2-9ba8-4ccc-9ddf-5275efd51d3a)
![Screen Shot 5783-09-02 at 15 46 35](https://github.com/WWBN/AVideo/assets/58882903/12463ff8-5c40-48f0-9a3c-cdf661de2b63)

Is there any other option I need to check or make sure is unchecked for it to work?

**Comment by DanielnetoDotCom** [comment]
if the encoder is not on the same domain as your streamer, it will not open in an iframe

**Comment by guymass** [comment]
but this is network encoders. on all sites they all open in iframe

**Comment by guymass** [comment]
How does it open on some of the sites like alive528.com and fetube and the other sites it will not.
