### ISSUE TITLE
Squarespace member area integration e.g. login e.g. OAUTH2

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8057]
**Describe the question**
We have a site behind a member area on Squarespace and have done some horrendous hack to make it work.

It seems that we could dispense with the horrible hack if we integrated via OAUTH?

It _looks_ like we could clone one of the auth plug-ins and change some things...

What would the steps be to do this integration?

**Comment by DanielnetoDotCom** [comment]
If I were in your shoes, I would copy some plugins, for example, the LoginGoogle 

and this is what I use for oauth2 https://hybridauth.github.io/
