### ISSUE TITLE
Search is broken, but, the site is implemented in a super weird way

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8058]
**Describe the question**
Search isn't working out. I see the search results flash by super briefly, then we're looking at a large subset of all videos.

Very difficult to explain.

We've implemented the site via html embed tag to hide it inside of a Squarespace member area. I _think_ that may be the root cause of the issue. I was only able to reproduce it twice where I saw the correct search results flicker briefly, it's sketch AF, so sorry no screenshot just yet.

Before going down this rabbit hole, just wanted to see if you had any thoughts on this kludgy html embed way of showing the avideo site*? Probably the fix is to do the OAUTH integration and then mv this junk <embed> code to /dev/null…

* we wanted to hide the AVideo site, so we slapped a javascript on it that asked for a password, then, we embedded the site in the Squarespace members area and the only way to get the password is when you're logged in. IT'S SOOPER SKETCH AF DO NOT TRY THIS AT HOME OR ANYWHERE

**Comment by walt93** [comment]
Since the explantation is probably difficult to visualize, here is the implementation.

User has logged in to the squarespace site in order to find this page.

AVideo site is literally embedded inside the window. Scrolling is as erratic as you would expect, and behaves differently for different browsers. It's a nightmare.  I think we don't even look at this (search) issue, it's too horrible to contemplate. Let's just fix the squarespace integration https://github.com/WWBN/AVideo/issues/8057

![Screen Shot 2023-05-23 at 3 46 09 PM](https://github.com/WWBN/AVideo/assets/11711050/23f179a4-77a0-47aa-bd9a-f7e63f462bd3)

**Comment by DanielnetoDotCom** [comment]
to be honest I am not sure what you want to do, 

but if you want to sell access or videos you should use the PPV or subscription plugins

**Comment by walt93** [comment]
Thing is we've already got too much traction on Squarespace, over 1K users. Too many to migrate without pain. OAUTH is the way to go.

Just super weird that search is broken on <embed>. OAUTH lets us not embed...
