### ISSUE TITLE
Short summary (H2) + Meta Description not saved

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8060]
@DanielnetoDotCom The fields Short summary (H2) and Meta Description, the inserted information is not being saved. See the video.
#8041 I'm looking for information about it.

https://github.com/WWBN/AVideo/assets/37880073/4c0f1fb7-cd8a-4ae4-9dcf-10d93bcc19e4

**Comment by DanielnetoDotCom** [comment]
check your logs, I just tested here and works fine

**Comment by gbrn** [comment]
Apparently it's working again... some strange instability, as you saw in the video.
Nothing about this was recorded in the LOG.

**Comment by gbrn** [comment]
@DanielnetoDotCom This problem happened again... I put the text in the field, I select to save, when I come back the data is no longer there.

**Comment by DanielnetoDotCom** [comment]
you must check the logs, apache and js
