### ISSUE TITLE
What config settings are you using on the public encoder

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8063]
Just curious Yours seems to make multiple qualities all at once. how do you make it do that?

**Comment by DanielnetoDotCom** [comment]
All like this

![image](https://github.com/WWBN/AVideo/assets/18009293/96fae012-0b19-4317-9e82-b3d87fbc0f39)

**Comment by JoshWho** [comment]
Any specific way of doing the processes in the config file? I just look at
how my encoders work and a fresh install I did for corder. Tv and both
don't do what yours is doing .

**Comment by JoshWho** [comment]
How do you disable **Dynamic MP4**  something is definitely different

**Comment by JoshWho** [comment]
How many cores do you have for your encoder server @DanielnetoDotCom ?

**Comment by DanielnetoDotCom** [comment]
2 encoders here

![image](https://github.com/WWBN/AVideo/assets/18009293/27fe4680-0f2f-4fc0-86a7-c2ffa0f9d70a)

and other 2 encoders here

![image](https://github.com/WWBN/AVideo/assets/18009293/d50ab77e-efd1-4145-8a1c-94676c252d50)

**Comment by JoshWho** [comment]
I'm trying to figure out what horse power those servers need. How many cores does it have?

**Comment by JoshWho** [comment]
I figured it out. Automatic MP4 is the dynamic.
