### ISSUE TITLE
/MobileManager/upload.php is getting the encoders into trouble

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8065]
**Describe the question**
I'm trying to characterize what's going on. Encoders are getting "stuck" where they appear to be encoding, but this state persists for days.

1. I don't have autoscraping turned on - I'm doing these by hand - so I queued some last night, and came in today and added one video to the queue using the scraper.
2. After some time I wondered why the video wasn't appearing on the site, so I went to check the queue. These are all stuck since last night:

![Screen Shot 2023-05-26 at 1 01 57 PM](https://github.com/WWBN/AVideo/assets/11711050/3a11317b-9a6f-4893-aa5d-f4d569bf29c8)

Note: the progress bar is not moving.

Last 1,000-ish lines of avideo.log: https://pastebin.com/tWX8vgi8

Daniel- one thing we for sure need is - when we throw these files into the encoder - to use the actual name of the file - "original_v_NNNNNN" isn't useful to help discriminate between what encoded and what failed to encode…

**Comment by DanielnetoDotCom** [comment]
Hi, I couldn't see any error in your logs. 

try to check the logs when you send the scraped video to the encoder.
