### ISSUE TITLE
Live stream no longer shows on channel

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8077]
I don't know what changed but now it no longer shows the live link I had going on my SeekingTheTrtuh channel 

![1892db75-1f4b-4403-9e2c-f69ba3148ab9](https://github.com/WWBN/AVideo/assets/39392449/6630dddf-7579-4909-bdfc-59e4ea5f235e)

**Comment by JoshWho** [comment]
Where did that go?
![5bd1d310-dba9-48cd-b19c-a213e7f89f3c](https://github.com/WWBN/AVideo/assets/39392449/14d8489b-f793-4a4a-9ae1-913db1d54e34)

**Comment by DanielnetoDotCom** [comment]
it is still there

https://demo.avideo.com/channel/MovieclipsTrailers
![image](https://github.com/WWBN/AVideo/assets/18009293/d80f957a-9059-4244-af73-8f5e964af0a8)

but remember you must have a live running to be able to see it.

**Comment by JoshWho** [comment]
Not on my site

**Comment by DanielnetoDotCom** [comment]
verify the plugin Customize user -> showChannelLiveTab

remember your site is not saving plugin configuration

**Comment by JoshWho** [comment]
I had that enabled I never turned it off.

**Comment by JoshWho** [comment]
> sorry it was already checked?

yes

**Comment by JoshWho** [comment]
Is it because I have it unlisted?

**Comment by DanielnetoDotCom** [comment]
> Is it because I have it unlisted?

probably yes

**Comment by JoshWho** [comment]
Ahhh I switched it on and that fixed it. OK nevermind.
