### ISSUE TITLE
Popup menu for category select is showing categories in random order

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8085]
**Describe the bug**
I have >500 categories, with the list in random order, it is making my brain hurt to find the right one. 

**To Reproduce**
1. Video->edit->metadata
2. Click on popup menu for category

**Expected behavior**
Categories to display in sensible order.

**Screenshots**
![Screen Shot 2023-06-04 at 3 15 59 PM](https://github.com/WWBN/AVideo/assets/11711050/377bfccf-281d-4173-8e8b-046c18221959)

**Comment by DanielnetoDotCom** [comment]
hi, the categories are in alphabetical order. but I guess we need a search in the category list.
