### ISSUE TITLE
mobileManager/upload.php has two doozies: sends notifications 3x per video, can't log in unless admin

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8086]
**Describe the bug**
I'm using mobileManager/upload.php script. Two issues:

1. Cannot use just any user; all users fail unless are admin user.

2. Uploading as admin user, if notifications are on, for each video uploaded, three notifications are sent. Since we have to upload the video, then, hit the database to change the users_id and categories_id and created date, the emails even go out with the wrong user.

**Comment by DanielnetoDotCom** [comment]
> Cannot use just any user; all users fail unless are admin users.

Any error in the log? 

> Uploading as admin user, if notifications are on, for each video uploaded, three notifications are sent. Since we have to upload the video, then, hit the database to change the users_id and categories_id and created date, the emails even go out with the wrong user.

I also need the logs for it. so I can see at what point it is triggering the emails.
