### ISSUE TITLE
[Request] /MobileManager/upload.php to have direct upload method

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8095]
**Is your feature request related to a problem? Please describe.**
I am scraping podcasts from Rumble. They literally just came out of the encoder pipeline at Rumble.

We can reasonably expect that Rumble have used a modern encoder pipeline and do not need to re-encode videos.

**Describe the solution you'd like**
An API parameter "bypassEncoder" - defaults to False if not specified in the API - If set to true, we will use the "direct MP4 upload" method instead of the encoder. 

Net result: think of all that carbon footprint saved by not re-encoding videos 🤣 but seriously, the site will publish to OTT much faster…

**Comment by DanielnetoDotCom** [comment]
you may be able to direct upload to this

https://github.com/WWBN/AVideo/blob/master/view/mini-upload-form/upload.php

it is not tested but may work
