### ISSUE TITLE
5 column layout does not seem possible. Only 6 or 3? Not making sense here.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8097]
**Describe the bug**
It may just be too late at night. But when I try to back from 6 column layout to 5, it is refusing to cooperate.

![5 up](https://github.com/WWBN/AVideo/assets/11711050/d402c64b-7b63-4412-b6f9-a70fb0013411)
![6 up](https://github.com/WWBN/AVideo/assets/11711050/2aa7f0eb-98f8-4f34-b286-a7c8b46856c4)

**Comment by DanielnetoDotCom** [comment]
You are not supposed to use 5 columns, this is a bootstrap layout, and there are 12 columns max, so you should use only 
1, 2, 4, 6, 12 only

**Comment by walt93** [comment]
Bootstrap is weird.
