### ISSUE TITLE
Encoders getting stuck are causing huge problems

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8099]
**Describe the question**
My back-end ingests videos by uploading them to my avideo site, and after the upload is successful it stores the metadata (title/url) in a database so it knows not to download that video ever again.

![Screen Shot 2023-06-10 at 5 16 42 PM](https://github.com/WWBN/AVideo/assets/11711050/b97d9302-e934-4e39-8c59-3e00d9837de6)

There are no encoders currently running. These videos are orphaned off into outer space, and are a research project to figure out which videos they are, and "hand cure" the database.

What does the minimum plug-in look like again? I need one that, after encode is successful, calls an endpoint with the id of the video.

**Comment by DanielnetoDotCom** [comment]
try to restart it 

![image](https://github.com/WWBN/AVideo/assets/18009293/e6bea840-af52-41c9-a72b-1e149ddfd96a)
