### ISSUE TITLE
Peer to peer general help question

### ISSUE THREAD

**Issue by RobertFULL30** [WWBN/AVideo#8107]
Is this the only place I can seek help for the AVideo platform?
I want to make some general enhancements to my site, like be able to add buttons in the videoCreator clearfix area, both for all creators and also for just select creators, I'm not an advanced coder by any stretch of the sober imagination

I tried to do a general one like this

![image](https://github.com/WWBN/AVideo/assets/43112761/ef370636-b14b-4b69-a769-c7d4b468d5d7)

using this area and snippet

![image](https://github.com/WWBN/AVideo/assets/43112761/be8274c4-4ca7-40f9-88f1-6425139315f5)

and it landed here

![image](https://github.com/WWBN/AVideo/assets/43112761/4d98d605-20cf-4642-9050-dd8d8e78f255)

I'd like to be part of the community 

Thank you

**Comment by DanielnetoDotCom** [comment]
the proper way is to create a custom plugin just for you and then add the code you want

check this add a trailer button :

https://github.com/WWBN/AVideo/blob/ae9e43a1e18a5d5cc03bdf4c596918c7780d517d/plugin/CustomizeAdvanced/CustomizeAdvanced.php#L814-L817

https://github.com/WWBN/AVideo/blob/master/plugin/CustomizeAdvanced/actionButton.php
