### ISSUE TITLE
Short form portrait mode videos

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8108]
**Is your feature request related to a problem? Please describe.**
I think it's time, Daniel. Internet is full of this crap. One of my content creators has a TON of these that I'd like to have on the site.

**Describe the solution you'd like**
Set it up like a different row type in Gallery mode, there are simply rows of vertical content. Lots of different ways to make that design work

**Comment by GreenDragonTavern** [comment]
Addressed this in #7733 and echo sentiments. The ***type*** field in table ***videos*** could be something like ***dart*** (akin to the Poison Dart Frog, small but deadly 😁) to identify said videos. A 1080x1920 video no longer than 60 seconds or 10 minutes depending on which big boy video platform you want compatibility with.

**Comment by DanielnetoDotCom** [comment]
@walt93 do you mean like shorts as @GreenDragonTavern describes?

**Comment by walt93** [comment]
Yes I do. Oh dear Lord I believe I just asked for compatibility with Tik Tok. What has happened to the world?

**Comment by GreenDragonTavern** [comment]
@DanielnetoDotCom - Can you give us an update/timetable on when or even if you're considering adding shorts to AVideo? Thank you.

**Comment by DanielnetoDotCom** [comment]
Currently, I am not working on it and this is not on the roadmap, but I will start it as soon as I find some free time.

**Comment by DanielnetoDotCom** [comment]
Check the Shorts plugin

**Comment by walt93** [comment]
I just turned it on. Wow. Very nice work. Doom scrolling and everything!
