### ISSUE TITLE
Question: using mobileManager/upload.php how to direct which encoder to use?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8111]
**Describe the question**
I'm using an encoder farm and have different encoders set to different resolutions (e.g.right now, mostly 720P and one is set to 1080P)

At the time of upload, is it possible to direct to a specific encoder?

**Comment by DanielnetoDotCom** [comment]
Currently, to do it, you need to create a new (upload.php) custom script (upload.php)
