### ISSUE TITLE
AI content moderation for chat

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8123]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when shills post garbage.

**Describe the solution you'd like**
AI to do content moderation

I'm thinking..
  comment comes in
  send it to openAI
  if AI says flag the comment, mark it for manual review
  UI/screen for manual review is list of comments with approve/delete and ban IP address/deactivate user button right there
  plug-in needs OpenAI key

At about $.002-$.004 per request, cheaper than human mods. 💡

**Comment by DanielnetoDotCom** [comment]
Agree, this may be a good idea, I may add it in the future.
