### ISSUE TITLE
Can Program be called playlist?

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#8124]
Can this feature be re-labeled **playlist** so people can easily identify it?

**Comment by DanielnetoDotCom** [comment]
Where exactly do you want people to identify it?

you already can have a custom name

![image](https://github.com/WWBN/AVideo/assets/18009293/06d60d84-c46c-4645-9e8f-6c24013af6be)

**Comment by fakeologist** [comment]
Thank you that solved it!
