### ISSUE TITLE
MYSQLD is running 100% on all cpu cores

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8125]
I don't know if this is a bug or a hack or some other  issue. My problem is that since last couple of days is the site is gradually incrementing database requests until all 32 cpu cores on my server run at 100%. This is directly occurring to the main site's database. Here are some screen shots:

After first restarting my maria-server I run "show processlist"  to show all processes in the mysql server:
![Screen Shot 5783-10-06 at 19 48 46](https://github.com/WWBN/AVideo/assets/58882903/a6c36bb5-d3ea-4fd9-ad01-f9569de1a9ce)
![Screen Shot 5783-10-06 at 23 25 07](https://github.com/WWBN/AVideo/assets/58882903/1002df1c-10fe-44df-b78c-ba494680f610)

Then after 5-10min:
![Screen Shot 5783-10-06 at 18 10 03](https://github.com/WWBN/AVideo/assets/58882903/f092bef7-c076-4b18-8651-256d98f3c0b4)
![Screen Shot 5783-10-06 at 23 24 29](https://github.com/WWBN/AVideo/assets/58882903/3fdc653c-e5fc-4536-922a-d23c3ac39370)

Which then renders the site usable and the whole server gets clogged. I am trying to investigate it but not sure really what is going on.

Site has been updated as well as the server. This is for sure coming from the AVideo site and the AVideo database.

**Comment by DanielnetoDotCom** [comment]
try to run this

https://github.com/WWBN/AVideo/wiki/Speed-up-your-page#mysqltuner-script

**Comment by guymass** [comment]
I ran the script and this is what I got, I am not that good with databases, not sure about few of these points:

![Screen Shot 5783-10-07 at 0 37 21](https://github.com/WWBN/AVideo/assets/58882903/510baf2b-647f-47d4-9507-bf0bc8af12c4)

**Comment by guymass** [comment]
OK I think I managed to reduce the amount of cpu usage and now it runs much better and doesn't reach 100% anymore. I am still not sure about all those recommendations above like primary keys etc. I don't want to mess the database in some way. Maybe if there was a script that can run those checks automatically it would be great for those who are not that DB proficient.
