### ISSUE TITLE
I can't log in as a user or administrator

### ISSUE THREAD

**Issue by Hootu** [WWBN/AVideo#8130]
And so, the problem is this. 
As soon as I install the plugin Live (Live) Version: @11.1 after exiting the admin panel, it is impossible to log back in, as the user also does not log in. After pressing the login button, eternal loading.
There is nothing in the error log
Where to look for what to fix?

**Comment by Hootu** [comment]
When exiting the admin panel or as a user in the browser, the error 502 Bad Gateway nginx/1.20.2 appears with the address https://domain/logoff

**Comment by DanielnetoDotCom** [comment]
502 Bad Gateway is probably something in your webserver configuration.

we also strongly recommend Apache instead of Nginx.

**Comment by Hootu** [comment]
> 502 Bad Gateway, вероятно, что-то в конфигурации вашего веб-сервера.
> 
> мы также настоятельно рекомендуем Apache вместо Nginx.

I figured out the 502 Bad Gateway error, the extension in the browser interfered with the work.
Plugins Meet (Meet) Version: @3.0, and Live (Live) Version: @11.1 had to be removed because it is impossible to log into the admin panel, and there is no login as a user, it loads, but it does not enter.

I have a CentOS 7 VPS server with an ISPmanager panel
Domain https://hootu.ru/

How to fix the error I can't imagine, tell me?

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/AVideo-Platform-Hardware-Requirements#server-operational-system

![image](https://github.com/WWBN/AVideo/assets/18009293/6b934ae4-3ce4-4ed0-ab9f-6a366d30ecb8)

**Comment by Hootu** [comment]
> Убедитесь, что вы делаете чистую установку Ubuntu без какой-либо панели управления.

Understood, thank you!
I have already found out that there is an 8 GB VPN and 8 Ubuntu 22.04 processors 
What about doing without the ISPsystem panel? how to work without it?

**Comment by DanielnetoDotCom** [comment]
you need to use the command line
