### ISSUE TITLE
Add to program taking >1minute and sometimes fails

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8131]
**Describe the bug**
User reported: add to program is taking inordinate amounts of time (spinning animation for minutes) and then fails to add to program.

I went to reproduce, took >45 seconds of spinning animation, then the video was added to the program.

**To Reproduce**
1. Go to any video
2. Click on "[+] Add to"
3. Turn on the switch for some program
4. Wait…

**Expected behavior**
The database access (or whatever its doing) not take so long

**Error Logs**
I scanned a couple thousand lines of log and didn't see anything.

**Comment by DanielnetoDotCom** [comment]
are you using the latest version? all the plugins are up to date?
