### ISSUE TITLE
AI Arms Race: Whisper is dominating Vosk in all categories, it's not even a competition!

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8132]
**Is your feature request related to a problem? Please describe.**
OpenAI released whisper and we can use it on our servers for free, rather than paying them to do it with a ridiculous API that makes us chop audio up into 25MB segments (wot?)

Whisper emits full sentences with capitalization and punctuation. We can even give whisper a prompt with, for example, technical terms so it gets the spelling correct. Vosk doesn't come close…

**Describe the solution you'd like**
Where you dropped in vosk? Drop in whisper. Add support for the prompt. It's just a text box in some plug-in, probably a checkbox or something to disable, defaults to off.

**To consider**
Running whisper without a GPU is … painful, need a solution like Encoder that runs on a separate box (or two (or three…))

OpenAI have that paid option, it costs about $0.35/hour for transcription, too expensive for my tastes but building this is an option for someone that wanted to give OpenAI a bunch of money…

**Comment by DanielnetoDotCom** [comment]
Thanks for that, whisper seems to be awesome. 

just asking to run whisper do I need to install something on the server?

how did you install or use it?

can you show a command line example?

**Comment by DanielnetoDotCom** [comment]
This is an awesome idea, I may check this as soon as I have some free time.

**Comment by walt93** [comment]
```
time whisper --model tiny.en --output_format all --language en awkjun30.mp3 > whisper.tiny.txt	1973MiB	330	11.22x
time whisper --model base.en --output_format all --language en awkjun30.mp3 > whisper.base.txt	2189MiB	526	7.04x
time whisper --model small.en --output_format all --language en awkjun30.mp3 > whisper.small.txt	3077MiB	1499	2.47x
time whisper --model medium.en --output_format all --language en awkjun30.mp3 > whisper.medium.txt	6071MB	3476	1.06x
```
