### ISSUE TITLE
Help with the installation

### ISSUE THREAD

**Issue by Hootu** [WWBN/AVideo#8134]
Hello! 
Need help from the creators youphp
I can't figure out how to install it? 
I rented a VPS server with a clean Ubuntu 22.04 without a panel.
I do everything according to the instructions, but through putty 
https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-22.x-for-AVideo-Platform-version-11.x-or-newer
Nothing works out, how to open a file where to open it and how to change it there?
And how to install the domain on the server and how to upload it?
I am not familiar with Ubuntu, and the whiter the server is without a panel, I do not understand how to manage it.

Help me install youphp or install it yourself?
Contact me via email hooturu@yandex.ru 
I will give access to the server.
Or record a video of how to do everything?

**Comment by DanielnetoDotCom** [comment]
you can hire me for installation here: https://youphp.tube/marketplace/

**Comment by Hootu** [comment]
> Вы можете нанять меня для установки здесь: https://youphp.tube/marketplace/

I agree, but I can't pay you where I live, my country is under sanctions (Russia). And I can't pay for your services yet, all transfers, banks, terminals to Europe or another country don't work (( But I promise that as soon as I have the opportunity, I will definitely pay

**Comment by DanielnetoDotCom** [comment]
We also accept bitcoins, if you are interested, send me an email at developer@youphptube.com

**Comment by Hootu** [comment]
> Мы также принимаем биткойны, если вы заинтересованы, отправьте мне электронное письмо по адресу [developer@youphptube.com.](mailto:developer@youphptube.com)

I have written to your email, I am waiting for an answer.

**Comment by DanielnetoDotCom** [comment]
I am not sure if I get it.

what is the sender?

**Comment by Hootu** [comment]
> Я не уверен, получу ли я это.
> 
> что такое отправитель?

Look at the mail, you already have a letter from me.

**Comment by DanielnetoDotCom** [comment]
Still do not get it. what is your email?

**Comment by Hootu** [comment]
> Все еще не получают его. какой у тебя адрес электронной почты?

My mail hooturu@yandex.ru 
I wrote you pna your mail developer@youphptube.com

**Comment by Hootu** [comment]
> developer@youphptube.com.

My letter has not reached you. You have specified the email address developer@youphptube.com . there is a dot at the end of your mail, I copied and sent it with this dot, I will forward the letter now, I'm sorry.

**Comment by DanielnetoDotCom** [comment]
I did responded you 3 days ago

![image](https://github.com/WWBN/AVideo/assets/18009293/612b5794-f933-4e22-b3c6-dec8d66251ea)

**Comment by Hootu** [comment]
> developer@youphptube.com

I don't have a letter from you((( 
Perhaps the Russian Yandex mail has messed up something. I have unsubscribed you from my Google mail.
Have you received a letter?

**Comment by DanielnetoDotCom** [comment]
Should I send again?

**Comment by Hootu** [comment]
> Должен ли я отправить снова?

Yes, to Google mail. vikingsfun.com@gmail.com
There is no letter from you to Yandex mail.
