### ISSUE TITLE
Errors after pull  ypt socket disconnects

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#8135]
![Screenshot_20230629_022031_Chrome](https://github.com/WWBN/AVideo/assets/70327833/645dd440-8fd3-4ff2-b50c-ed4f55d84a40)
@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
this is something in your PHP installation

https://laracasts.com/discuss/channels/laravel/app-suddenly-freezing-due-to-maximum-exec-time-error-in-symfony
https://stackoverflow.com/questions/59851923/max-execution-timeout-30-seconds-mbstring-error-laravel-6
