### ISSUE TITLE
How to make Uploading a Subscription only access

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8143]
I want to charge a monthly access fee to the uploader and wondering how to do that with the subscription group settings automatically. 

That way a user has to have the premium access to upload.

**Comment by DanielnetoDotCom** [comment]
Check this https://github.com/WWBN/AVideo/wiki/PredefinedCategory-Plugin

**Comment by JoshWho** [comment]
I do not see just a way to make uploading a pad feature. I want to charge 5 dollars a month to the uploader.

**Comment by DanielnetoDotCom** [comment]
I mean, to make all the videos private make sure you auto-add them to a user group

currently, there is no subscription to enable upload, the closest we have is this https://github.com/WWBN/AVideo/wiki/DiskUploadQuota-plugin.

 but for now, it is only working properly if you are hosting the video on your server, not in external storage.

**Comment by JoshWho** [comment]
I see. I will wait for something like that in the future.
