### ISSUE TITLE
Video Shorts are still showing live streams that have no time stamp it seems

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8150]
![download](https://github.com/WWBN/AVideo/assets/39392449/57ed2f7b-885d-49a5-88c0-9c0a24f8d11f)

**Comment by DanielnetoDotCom** [comment]
what do you mean by no timestamp?

**Comment by JoshWho** [comment]
Nevermind, I think I overlooked it. I just went through like 100 and didn't see it no more.

**Comment by JoshWho** [comment]
Spoke too soon. This video just popped up in it https://www.joshwhotv.com/video/.7Wrq/april-4-2019

**Comment by JoshWho** [comment]
This one too https://www.joshwhotv.com/video/.t27n/david-icke-banned-bill-gates-nano-technology-daniel-chapter-2

**Comment by DanielnetoDotCom** [comment]
I am lost what do you mean, are you talking about Shorts?

**Comment by JoshWho** [comment]
Yes

**Comment by JoshWho** [comment]
I have shorts set to 60 seconds some of these videos are past that https://www.joshwhotv.com/video/.7Wrq/april-4-2019

This one too https://www.joshwhotv.com/video/.t27n/david-icke-banned-bill-gates-nano-technology-daniel-chapter-2
https://www.joshwhotv.com/video/.727_dg/putin-dropping-some-serious-truth-bombs-here

**Comment by DanielnetoDotCom** [comment]
I am not seeing them in the shorts

also, I cannot see any reason to show those videos

**Comment by JoshWho** [comment]
Maybe it is because I am viewing as video admin

**Comment by JoshWho** [comment]
I think that is what it was. Guest view I do not see these

**Comment by DanielnetoDotCom** [comment]
no, the time (duration_in_seconds ) is strict, 

https://github.com/WWBN/AVideo/blob/6e22738d27ca5d27d4cc0b41b386ea88ea6e1ccd/objects/video.php#L2035-L2038

**Comment by JoshWho** [comment]
Was that the problem

**Comment by DanielnetoDotCom** [comment]
I have no idea, show anything greater than duration_in_seconds should not show. 

try my last update, I just sent something.

**Comment by JoshWho** [comment]
I think you solved it. Thank you
