### ISSUE TITLE
ypt socket keeps disconnecting after git pull

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#8153]
socket disconnecting and will not reconnect until I change the port number. It will then be OK for a day and then it disconnects again. no error except that it cannot connect on that port.

**Comment by DanielnetoDotCom** [comment]
if disconnect check your logs, 

regarding the port, stop the socket before starting it again

https://github.com/WWBN/AVideo/wiki/Socket-Plugin#troubleshooting

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom 
![Screenshot_20230705_174431_Firefox](https://github.com/WWBN/AVideo/assets/70327833/058adc22-da6b-49a2-964d-1d4e54af4255)
![Screenshot_20230705_174426_Firefox](https://github.com/WWBN/AVideo/assets/70327833/2658bf29-2c1b-40d6-a185-1aeecf627e70)
![Screenshot_20230705_174418_Firefox](https://github.com/WWBN/AVideo/assets/70327833/db3efdd0-869f-4885-986c-6b970ffa4baa)

stop and start socket does not work, reboot does not work, I have to change port and then restart server and then it connects until the next time I live stream. After the live stream is over the socket disconnects

**Comment by milehighkaraoke** [comment]
funny thing... showes disconnected but it is still producing the live icon and the live shows in the gallery @DanielnetoDotCom 
![20230705_211149](https://github.com/WWBN/AVideo/assets/70327833/9da65639-d7e8-4997-9751-060ae9075075)

**Comment by DanielnetoDotCom** [comment]
as long as the issue is the port, it looks like some security feature in your server, maybe something else, but it is specific to your server.

**Comment by milehighkaraoke** [comment]
well whatever was done in the latest git update has fixed this problem @DanielnetoDotCom
