### ISSUE TITLE
Mobile App Live Stream "Connection Failed publish permitted failed"

### ISSUE THREAD

**Issue by markginter31** [WWBN/AVideo#8154]
**Describe the bug**
When trying to live stream from the Mobile App - it will fail with "publish permit failed"

**To Reproduce**
1. Go to live stream in mobile app
2. Click on camera icon at top
3. Click on camera icon at bottom to start stream
4. after a few seconds, error message pops up -- "Connection failed:  Error configure stream, publish permitted failed"

FROM THE LOGS - I can see that when the mobile app tries to stream it sends the key ************* --- If I stream from OBS (which works fine) the logs show that it uses key *************-1      The mobile app does not append the -1 to the end of the key for some reason.

**Update** -- I tried deleting the -1 from the key in OBS and it sent/streamed fine without it.  Apparently this appended number is simply a way to differentiate between streams and each additional -# allows for a new stream with the same base key.  

Running the latest Mobile App from Google Play Store.  Running latest AVideo from git pull.

**Comment by DanielnetoDotCom** [comment]
the key is not the issue. check your [avideo log](https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform#live-stream-errors) for some clues. 

also, check your [nginx rtmp log](https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform#live-stream-errors)

**Comment by markginter31** [comment]
This shows up in the AVIDEO log --> AVideoLog::DEBUG: NGINX ON Publish error, Password does not match
and this in the nginx access.log (nothing in the error.log)
 [05/Jul/2023:13:05:23 +0000] PUBLISH "live" "64a54501ed0af" "" - 770 292 "" "FMLE/3.0 (compatible; Lavf57.56" (0s)
 [05/Jul/2023:13:05:26 +0000] "GET /stat HTTP/1.1" 200 597 "-" "AVideoStreamer_46edfc4f2f10fa04f461650dee45fbf4"

**Comment by DanielnetoDotCom** [comment]
what mobile app are you referring to?

are you using OBS or a mobile app?

**Comment by markginter31** [comment]
It's the AVideo Platform mobile app that refuses to connect.  I have OBS setup on my laptop.  My phone with the AVideo Platform app gives the password does not match error.  My laptop with OBS works fine.

**Comment by DanielnetoDotCom** [comment]
Ok, I see.

Are you talking about this app: https://github.com/WWBN/AVideo/wiki/YPT-Media-Mobile-app

**Comment by markginter31** [comment]
Here's more from the log:
[05-Jul-2023 13:14:43 UTC] AVideoLog::DEBUG: NGINX ON Publish new User(1) SCRIPT_NAME: /video/plugin/Live/on_publish.php
[05-Jul-2023 13:14:43 UTC] AVideoLog::DEBUG: NGINX ON Publish error, Password does not match (_user_hash_**********) expect (********************) SCRIPT_NAME: /video/plugin/Live/on_publish.php
[05-Jul-2023 13:14:43 UTC] AVideoLog::DEBUG: NGINX ON Publish deciding ... SCRIPT_NAME: /video/plugin/Live/on_publish.php
[05-Jul-2023 13:14:43 UTC] AVideoLog::SECURITY: NGINX ON Publish denied User Not verified

**Comment by DanielnetoDotCom** [comment]
> Ok, I see.
> 
> Are you talking about this app: https://github.com/WWBN/AVideo/wiki/YPT-Media-Mobile-app

???

**Comment by markginter31** [comment]
This one:
https://play.google.com/store/apps/details?id=platform.avideo.com

**Comment by DanielnetoDotCom** [comment]
> This one: https://play.google.com/store/apps/details?id=platform.avideo.com

this one is wrong, forget it

use this one: https://play.google.com/store/apps/details?id=ypt.media

also, look at this:

`[05-Jul-2023 13:14:43 UTC] AVideoLog::SECURITY: NGINX ON Publish denied User Not verified`

make sure you are using a valid user in the app. 

maybe you add some login restriction only for verified users.

**Comment by markginter31** [comment]
I'll look into it more and try with the YPT Media app.  Thanks for the guidance!

**Comment by markginter31** [comment]
YPT works fine.  Thank you!
