### ISSUE TITLE
Gallery Title RTL

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8155]
Is it possible to set the gallery title and in general any small heading title to directior=rtl when the language is set and recognised and Hebrew or Arabic?

If I inject CSS code it will also effect the english titles. I only need those titles on RTL mode when the site language is set to RTL without effecting the original LTR for english and other LTR languages.

**Comment by DanielnetoDotCom** [comment]
can you please check if the latest update improves something?
