### ISSUE TITLE
Emoji reactions

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8157]
**Is your feature request related to a problem? Please describe.**
Thumbs up and down is so 2000s. Let's get modern!

**Describe the solution you'd like**
- I think it replaces thumbs up/down - it's an either/or proposition (admin preferences)
- Limited number of emoji reactions 
- Maybe let the admin configure which/how many emoji in the preferences? A few complexities there… 
- Default with a set like 😁😍🤨😟😤😳🤡
- Users get to pick one emoji "vote" (which emoji they pick)
- Display full row of emoji/reaction counts on videos detail page
- Videos list page, maybe just a badge with a count of the total # of reactions (hover to see all reactions/counts)

**Comment by DanielnetoDotCom** [comment]
I may add some reactions in the future. for videos live and shorts

**Comment by walt93** [comment]
Something to get them interacting with the platform until we get AI moderation. Looks like OpenAI actually have a model trained for moderation. They're not the only one. Wow, check this out… https://www.activefence.com/free-plan

**Comment by JoshWho** [comment]
> **Is your feature request related to a problem? Please describe.** Thumbs up and down is so 2000s. Let's get modern!
> 
> **Describe the solution you'd like**
> 
> * I think it replaces thumbs up/down - it's an either/or proposition (admin preferences)
> * Limited number of emoji reactions
> * Maybe let the admin configure which/how many emoji in the preferences? A few complexities there…
> * Default with a set like 😁😍🤨😟😤😳🤡
> * Users get to pick one emoji "vote" (which emoji they pick)
> * Display full row of emoji/reaction counts on videos detail page
> * Videos list page, maybe just a badge with a count of the total # of reactions (hover to see all reactions/counts)

I would like to see these added and making it rain down
