### ISSUE TITLE
Guide: How to develop code for AVideo platform

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8158]
**Step 1. Get an account on OpenAI **
We need gippity 4 for this. Gippity 3.5 doesn't have the juice.

**Step 2. Prompt**
![Screen Shot 2023-07-06 at 10 49 04 PM](https://github.com/WWBN/AVideo/assets/11711050/db95b172-4843-4262-91e8-380b6e8ed83e)

Comment: Initial prompt "Act as" is current standard/best practice to open a session. Sets the tone. Achieves better results than not.

**Step 3. Review code and integrate **
![Screen Shot 2023-07-06 at 10 49 52 PM](https://github.com/WWBN/AVideo/assets/11711050/e955d88b-f338-46ac-80f8-998cf5cde901)

Comment: Any time you ask for code that could have a bug? Simply prompt "check your work" or anything similar. GPT catches its own bugs with high success rate, if not it explains the code.

**Step 4. Ask 🤖 for clarification **
![Screen Shot 2023-07-06 at 10 50 32 PM](https://github.com/WWBN/AVideo/assets/11711050/883f853d-d4c2-41b9-bb11-b1f57c00a3b1)

Comment: Treat the bot as your personal offshore dev. Make it do all the coding. It types faster than you anyway.

**Step 5. 😲
![Screen Shot 2023-07-06 at 10 51 23 PM](https://github.com/WWBN/AVideo/assets/11711050/30dedc03-7819-440a-99ed-c7ba26817fb7)

Holy poop emoji! OpenAI's training data includes _**all**_ of GitHub up until Nov 21' lol

You can continue, giving code snippets from the other server's POV, asking it what is required to make CORS work, etc…

If you encounter a bug & have no clue, simply copy the code and error back to gippity. For all intents and purposes you don't even need to prompt it at this point, just paste the crash log and the code which is crashing and it usually figures it out.

Let's go build Skynet together!

**Comment by Maikuolan** [comment]
> Holy poop emoji! OpenAI's training data includes all of GitHub up until Nov 21' lol

That's interesting. I just went there now, and asked it, "What is (name)?", naming some of the various packages that I've created and made available at GitHub, to see what it would say, and it answered correctly.

Haven't tried asking it for any code yet, because TBH, I've got no idea what I'd even ask it for right now. But, it's interesting to see where things are going with it.
