### ISSUE TITLE
Shorts crash on android pwa now when going to next video

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8159]
It crashes now for me when I click next on my phone.

**Comment by JoshWho** [comment]
It only crashes in vertical layout. Wide screen it doesn't crash. Wide screen I cannot click the next arrow, the like is ontop of the next arrow

**Comment by TLCReuver** [comment]
Crashes here too, vertical & wide screen. Also have no images & closing shorts does nothing. All plugins are updated.
Restored back to earlier version.

**Comment by DanielnetoDotCom** [comment]
Not sure what is causing it.

is hard when I cannot test it. 

check if this update makes any difference

if persist check if the same happens in the same happen here 

https://codepen.io/danielnetodotcom/full/ZEmrVbb

**Comment by JoshWho** [comment]
> Not sure what is causing it.
> 
> is hard when I cannot test it.
> 
> check if this update makes any difference
> 
> if persist check if the same happens in the same happen here
> 
> https://codepen.io/danielnetodotcom/full/ZEmrVbb

codecanyone version Works fine I do not see that pause before it loads the next frame

**Comment by TLCReuver** [comment]
Codepen_script works here fine too.

https://github.com/WWBN/AVideo/assets/39981177/28875510-5015-44a4-8147-92e8ca1ef74a

**Comment by TLCReuver** [comment]
MOBILE:

https://github.com/WWBN/AVideo/assets/39981177/c28c1ccd-9897-40f7-9701-4fad728195c7

**Comment by TLCReuver** [comment]
BTW, have updated 3 times en shows every time below warnings (skipping). Maybe nothing to do with this issue ?

![Snap11](https://github.com/WWBN/AVideo/assets/39981177/06555d9a-87d2-43bc-836b-cf8f80da9f16)

**Comment by DanielnetoDotCom** [comment]
Just confirming, is it crashing on the next button and close button or only the close button?

**Comment by TLCReuver** [comment]
Only "Close"_button now. Did a last update from ealier version and images are now present.

Screenshot:

https://github.com/WWBN/AVideo/assets/39981177/12d64b73-6c94-4d4b-bae1-de8bb0670a25

**Comment by DanielnetoDotCom** [comment]
can you please check if that update makes any difference?

**Comment by TLCReuver** [comment]
Updated but the same issue.

 I inserted a Phone_Screen_Record in my earlier reply with Web-view popup when it crashes.

**Comment by DanielnetoDotCom** [comment]
thanks, but did you clear the cache after the update?

**Comment by TLCReuver** [comment]
Yes, but i tried again and the result is the same.

**Comment by DanielnetoDotCom** [comment]
Hi, 

I still need your help to test it as long as this error does not happen on my side.

On my side I tested on the site https://tutorials.avideo.com/, does the same happen with you on tutorials site?

does this happen on this simplified version?

https://codepen.io/danielnetodotcom/full/JjeLVwr

**Comment by TLCReuver** [comment]
For me https://tutorials.avideo.com/ and https://codepen.io/danielnetodotcom/full/JjeLVwr is working perfect, horizontal, vertical on phone and also perfect on Windows. I see now difference.  Do you see a difference [JoshWho] ???

**Comment by TLCReuver** [comment]
@Daniel,
I copied the source on one of my vhost and tested it. 

Demo: https://www.metashare.nl/avideo_tutorials.htm  <=== Working perfectly here !!!

**Comment by DanielnetoDotCom** [comment]
I am lost. so it is working on my site. the code is the same as the one you guys have. 

maybe some other plugin is making it crash?

**Comment by TLCReuver** [comment]
- On clone all external scripts are removed so everything is original.
-  Disabled all plugins except Gallery, SecureVideoDirectory and Shorts
-  Every overlays (video-logo) are disabled
-  Cleared cache several times (also browser)
But the problem remains

**Comment by DanielnetoDotCom** [comment]
very weird, there is any custom js?

like Google ads?

**Comment by JoshWho** [comment]
None one mine. It is only when it does that thumbnail load first before the player loads . Maybe a memory leak

**Comment by JoshWho** [comment]
Resource Loading: If there are issues with loading resources (e.g., videos, images) or AJAX requests on Android devices, it could lead to crashes when trying to navigate to the next video.

Memory or Performance Issues: Playing videos or using certain animations may consume significant resources on mobile devices, especially older ones, leading to crashes due to insufficient memory or poor performance.

**Comment by DanielnetoDotCom** [comment]
@TLCReuver or @JoshWho do you have a link that always crashes so I can test with my mobile?

**Comment by TLCReuver** [comment]
Yes http://media.beesel-reuver.nl:8080/ 

This clone Is only today online because i'm a few days in Egypt and can't use VPN there,

**Comment by DanielnetoDotCom** [comment]
Also why the close button is not working?

there is no error is it the latest git pull?

**Comment by DanielnetoDotCom** [comment]
Check this update

**Comment by DanielnetoDotCom** [comment]
can you please uncheck this option advancedCustom->disableAnimations

**Comment by DanielnetoDotCom** [comment]
This update may also resolve even with the advancedCustom->disableAnimations checked

**Comment by TLCReuver** [comment]
Done (@ Clear cache)
![Snap6](https://github.com/WWBN/AVideo/assets/39981177/69aef5d7-9982-46b2-95b5-12e31d47c6bd)

Also updated
![Snap7](https://github.com/WWBN/AVideo/assets/39981177/9e497fca-951a-4528-bfea-82de8221f4b5)

**Comment by DanielnetoDotCom** [comment]
can you please try this update?

**Comment by DanielnetoDotCom** [comment]
Hold on I found something

**Comment by TLCReuver** [comment]
Okay, i wait...

**Comment by DanielnetoDotCom** [comment]
try this update...

also, I found that when we close it was trying to call the Picture-in-Picture, which may crash your phone.

now it is ignored inside iframes.

**Comment by TLCReuver** [comment]
Update & Clear cache...  Scrolling & closing work like a charn now. You can test it.

![Snap8](https://github.com/WWBN/AVideo/assets/39981177/b474f744-17d0-4fb5-809f-97ea3c03068c)

**Comment by DanielnetoDotCom** [comment]
Awesome, but is it crashing on Android?

**Comment by TLCReuver** [comment]
Not crashing on Android.... test Google Crome, Firefox & Samsung Internet.

Awesome, problem solved. Thank you very much.

**Comment by TLCReuver** [comment]
The larger the project, the more complex the whole becomes thats for sure ; )

**Comment by JoshWho** [comment]
Looks like it is fixed. I do not see it crashing anymore. I clicked the next button hundreds of times so Not sure what did it but it is fixed.
