### ISSUE TITLE
Uncaught mysqli_sql_exception: Can't find FULLTEXT index matching the column list in...

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8164]
@DanielnetoDotCom I checked that there are new MYSQL errors, do you know what this is?

`[05-Jul-2023 20:06:43 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Can't find FULLTEXT index matching the column list in \/var\/www\/html\/AVideo\/objects\/mysql_dal.php:129\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/mysql_dal.php(129): mysqli->prepare()\n#1 \/var\/www\/html\/AVideo\/plugin\/Cache\/Objects\/CachesInDB.php(223): sqlDAL::writeSql()\n#2 \/var\/www\/html\/AVideo\/objects\/playlist.php(789): CachesInDB::_deleteCacheStartingWith()\n#3 \/var\/www\/html\/AVideo\/objects\/playlist.php(730): PlayList::deleteCacheDir()\n#4 \/var\/www\/html\/AVideo\/objects\/playlist.php(636): PlayList->save()\n#5 \/var\/www\/html\/AVideo\/objects\/video.php(1864): PlayList::getWatchLaterIdFromUser()\n#6 \/var\/www\/html\/AVideo\/objects\/video.php(1773): Video::getWatchLaterIdFromUser()\n#7 \/var\/www\/html\/AVideo\/objects\/video.php(1633): Video::getInfo()\n#8 \/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/modeFlixCategory.php(94): Video::getAllVideos()\n#9 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":129} SCRIPT_NAME: /plugin/YouPHPFlix2/view/modeFlixCategory.php`

`[05-Jul-2023 20:06:14 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Can't find FULLTEXT index matching the column list in \/var\/www\/html\/AVideo\/objects\/mysql_dal.php:129\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/mysql_dal.php(129): mysqli->prepare()\n#1 \/var\/www\/html\/AVideo\/plugin\/Cache\/Objects\/CachesInDB.php(223): sqlDAL::writeSql()\n#2 \/var\/www\/html\/AVideo\/objects\/playlist.php(789): CachesInDB::_deleteCacheStartingWith()\n#3 \/var\/www\/html\/AVideo\/objects\/playlist.php(730): PlayList::deleteCacheDir()\n#4 \/var\/www\/html\/AVideo\/objects\/playlist.php(620): PlayList->save()\n#5 \/var\/www\/html\/AVideo\/objects\/video.php(1857): PlayList::getFavoriteIdFromUser()\n#6 \/var\/www\/html\/AVideo\/objects\/video.php(1771): Video::getFavoriteIdFromUser()\n#7 \/var\/www\/html\/AVideo\/objects\/video.php(1097): Video::getInfo()\n#8 \/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/BigVideo.php(7): Video::getVideo()\n#9 \/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/modeFlixBody.php(2): include('...')\n#10 \/var\/www\/html\/AVideo\/plugin\/YouPHPFlix2\/view\/modeFlix.php(30): include('...')\n#11 \/var\/www\/html\/AVideo\/view\/index_firstPage.php(58): require('...')\n#12 \/var\/www\/html\/AVideo\/view\/index.php(20): include('...')\n#13 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":129} SCRIPT_NAME: /view/index.php`

**Comment by DanielnetoDotCom** [comment]
can you please check if your Cache plugin is at least version 3.0?

Looks like you are missing this update https://github.com/WWBN/AVideo/blob/master/plugin/Cache/install/updateV3.0.sql

**Comment by gbrn** [comment]
It wasn't really updated...
![image](https://github.com/WWBN/AVideo/assets/37880073/62c57059-2c19-497d-a637-68fe5ff9e8ec)

I don't constantly access plugins, so I didn't see it.
Would you like to put the plugins to update along with the rest of the system?
