### ISSUE TITLE
unknown users ?

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#8172]
@DanielnetoDotCom 
what's going on with this?
![Screenshot_20230712_220738_Firefox](https://github.com/WWBN/AVideo/assets/70327833/da1e7849-b377-492b-87f1-e94ca011c936)

**Comment by milehighkaraoke** [comment]
it's growing expediently. I do not have bandwidth for this many users so I know something is totally wrong @DanielnetoDotCom 
![Screenshot_20230712_224304_Firefox](https://github.com/WWBN/AVideo/assets/70327833/7bd5b240-783b-4be7-af0c-401d91dafa7e)

**Comment by milehighkaraoke** [comment]
site is locked so how can unknown users even access it?

**Comment by milehighkaraoke** [comment]
![Screenshot_20230712_234948_Firefox](https://github.com/WWBN/AVideo/assets/70327833/e1e9180b-2d85-4a3e-8888-63d5fb340a8b)

**Comment by milehighkaraoke** [comment]
end result when broadcast is over @DanielnetoDotCom 
![Screenshot_20230713_011720_Firefox](https://github.com/WWBN/AVideo/assets/70327833/fb582ae6-d29a-4567-9571-9caee1e355c4)

**Comment by milehighkaraoke** [comment]
this only happens during live broadcastvandbitvis immediate. My site sits idiol all day
![Screenshot_20230713_181230_Firefox](https://github.com/WWBN/AVideo/assets/70327833/dfd8080f-ffec-4d78-af6b-39b2db9d9abb)

**Comment by GreenDragonTavern** [comment]
@milehighkaraoke if anyone say, embeds one of your videos, once the embed page is displayed, socket gets it.
