### ISSUE TITLE
tables Cache - progress bar

### ISSUE THREAD

**Issue by KrzysioMisio** [WWBN/AVideo#8174]
Hi Daniel, I have updated AVideo to 12.5 
In the plugins I am told to update the tables in the Cache, but I can't because the progress bar spins all the time

`[14-Jul-2023 15:19:59 Europe/Warsaw] AVideoLog::ERROR: {"type":1,"message":"Uncaught mysqli_sql_exception: Table 'myMySQLDatabase.live_transmitions_history' doesn't exist in \/var\/www\/html\/AVideo\/objects\/mysql_dal.php:129\nStack trace:\n#0 \/var\/www\/html\/AVideo\/objects\/mysql_dal.php(129): mysqli->prepare()\n#1 \/var\/www\/html\/AVideo\/plugin\/Live\/Objects\/LiveTransmitionHistory.php(491): sqlDAL::writeSql()\n#2 \/var\/www\/html\/AVideo\/plugin\/Cache\/Cache.php(46): LiveTransmitionHistory::finishALL()\n#3 \/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php(1336): Cache->updateScript()\n#4 \/var\/www\/html\/AVideo\/objects\/pluginRunUpdateScript.json.php(18): AVideoPlugin::updatePlugin()\n#5 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/objects\/mysql_dal.php","line":129} SCRIPT_NAME: /objects/pluginRunUpdateScript.json.php`

`[14-Jul-2023 15:19:59 Europe/Warsaw] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'myMySQLDatabase.live_transmitions_history' doesn't exist in path/to/my/streamer/site/objects/mysql_dal.php:129`

**Comment by DanielnetoDotCom** [comment]
Install all the missing tables in your plugin menu

install them even if the plugin is not enabled

**Comment by KrzysioMisio** [comment]
thanks, it helped
