### ISSUE TITLE
Rumble embed not centered anymore

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8188]
https://www.joshwhotv.com/video/.7HCxMw/the-shocking-truth-about-blood-sacrifices-in-the-music-industry

Not sure what changed

**Comment by DanielnetoDotCom** [comment]
For me seems to be fine

also, I resize and it is still good

![chrome-capture-2023-6-18](https://github.com/WWBN/AVideo/assets/18009293/ab4ef3a6-3cd3-400b-a668-0441d54fe0ef)

**Comment by JoshWho** [comment]
hmmm?

**Comment by JoshWho** [comment]
this is how it loads for me. Maybe it is because I am logged in on rumble let me check
![56d9e6f3-7d4a-4169-8f22-86802ac297c1](https://github.com/WWBN/AVideo/assets/39392449/e6b8fdf1-c34d-4e2e-af7a-48d2ef3cd059)

**Comment by JoshWho** [comment]
same thing incognito
![2c14841e-2a52-4825-ab27-faa8da87544f](https://github.com/WWBN/AVideo/assets/39392449/16395a43-bb9a-4067-9a48-e519860d4650)

**Comment by DanielnetoDotCom** [comment]
Please check this update, clear your cache and try again.

**Comment by JoshWho** [comment]
Now the video player is a tiny thin line at the top
![f8bbe6a4-de3f-43c9-89d4-0f088ed8ed2a](https://github.com/WWBN/AVideo/assets/39392449/7b5015bd-5311-424d-85bb-a58456a07718)

**Comment by DanielnetoDotCom** [comment]
I just reverted this change, also I tested the same video on my site without this change and it is perfect on my side

it may be some custom script or css from your side

![image](https://github.com/WWBN/AVideo/assets/18009293/a8c58c52-ea94-4c67-9e69-1dd3e1d26f6b)

**Comment by JoshWho** [comment]
It has me dumbfounded I do not know

**Comment by DanielnetoDotCom** [comment]
please try this update

**Comment by JoshWho** [comment]
Perfect
![421849a4-511e-44c6-bcdc-402a124ae844](https://github.com/WWBN/AVideo/assets/39392449/af44e2eb-34d0-44fd-bbc8-b3e973d79d20)
All fixed Thank you

**Comment by JoshWho** [comment]
I just realized When I click theatre mode it is the thin line still.  Compressed looks correct but wide theatre mode all videos are that thin line again

**Comment by DanielnetoDotCom** [comment]
I updated your site and you should be good now

**Comment by JoshWho** [comment]
Thank you looks good now
