### ISSUE TITLE
Youtube front page How to make the left navigation stay open by default

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8189]
How to make the left nav expanded as the default?

**Comment by KrzysioMisio** [comment]
you mean something like me ?
https://www.youhippo.com/

**Comment by DanielnetoDotCom** [comment]
It is nice. it could be a plugin or a topMenu update.

**Comment by JoshWho** [comment]
> you mean something like me ? https://www.youhippo.com/

Very impressive. How did you get it so light weight on the page loads. It is so smooth

**Comment by JoshWho** [comment]
Im talking more through
![download (18)](https://github.com/WWBN/AVideo/assets/39392449/eb706494-86da-41b8-b244-93bb9ecbaa4d)
 about this theme with the left nav stuck out by default

**Comment by JoshWho** [comment]
Also the Shorts row needs to be added to it

**Comment by JoshWho** [comment]
Honestly All I want is the Left Nav design from the youtube theme to be on Gallery theme, and make it stay popped out by default would look perfect.

**Comment by JoshWho** [comment]
If you can make Gallery look like this it will be perfect this is what I described in the post above i made in photoshop
![f66c0123-5eb6-4be1-a95e-331090a960f0 copy](https://github.com/WWBN/AVideo/assets/39392449/63dfbcc0-68b6-46f4-a873-0f1347308ff0)

**Comment by KrzysioMisio** [comment]
> > you mean something like me ? https://www.youhippo.com/
> 
> Very impressive. How did you get it so light weight on the page loads. It is so smooth

In your case it works very slowly because you have all categories enabled
- Trending
- Recommended
- New Uploads
- Most Viewed
- Popular
- Health
- News 
- Comedy
- Entertainment 
- Gaming 
- Cartoons 
etc...
I have visible 2 categories that need to load and the rest are visible by clicking on the button in the category menu

**Comment by KrzysioMisio** [comment]
> It is nice. it could be a plugin or a topMenu update.

Daniel, a plug-in would have been better 
you would have made an option to choose which buttons to display
I did that the logged in user sees more menu buttons

**Comment by JoshWho** [comment]
If the Left nav from the old Youtube Theme could be put into the galley theme it will look perfect. this is it in photoshop

![f66c0123-5eb6-4be1-a95e-331090a960f0 copy](https://github.com/WWBN/AVideo/assets/39392449/9ddca520-dda3-4402-9c6d-693463c1f46b)

**Comment by walt93** [comment]
@KrzysioMisio did you implement your sidebar as a mod to the source code or injected HTML in the customizeAdvanced plugin?

**Comment by JoshWho** [comment]
> If the Left nav from the old Youtube Theme could be put into the galley theme and kept It displayed out by default, it will look perfect. this is it in photoshop
> 
> ![f66c0123-5eb6-4be1-a95e-331090a960f0 copy](https://user-images.githubusercontent.com/39392449/254631075-9ddca520-dda3-4402-9c6d-693463c1f46b.png)
For the record I want the Nav from the Youtube Theme moved into the Gallery Theme. and a way to keep it opened by default.

**Comment by JoshWho** [comment]
I did it 

I added 

```
<style>
#sidebar{

    background-color: #f5f5f5;
}
#sideBarContainer{
    padding: 0;
}

#sideBarContainer li a {
    color: #0a0a0a;
    padding: 10px 20px;

}
#sideBarContainer li span:not(.badge), #sideBarContainer li i {
    color: #888;
    margin-right: 20px;
    font-size: 1.4em;
}
#sideBarContainer ul li h3, #sideBarContainer ul li h2 {
    color: #555;
    font-weight: bolder;
    text-transform: uppercase;
    font-size: 1.3rem;
}
#sideBarContainer .btn  {
    background: transparent;
    border-width: 0;
    text-align: left;
    border-radius: 0;
}

#sideBarContainer .btn:focus, #sideBarContainer .btn:hover{
    text-decoration: none;
    background-color: #eee;
}
#sideBarContainer .selected, .rightProfile .selected  {
    background-color:#DDD;
}
</style> 
```

to the header and boom. 
![bbbacf46-4fd1-4e38-9de6-d1041e449954](https://github.com/WWBN/AVideo/assets/39392449/c2fabb47-0f8c-4fdc-8856-29599094c2ce)

https://www.joshwhotv.com

Love it 👏🥳🎉

**Comment by JoshWho** [comment]
Now to just make a switch that makes the left nav open by default on the Home page only

**Comment by JoshWho** [comment]
> > > you mean something like me ? https://www.youhippo.com/
> > 
> > 
> > Very impressive. How did you get it so light weight on the page loads. It is so smooth
> 
> In your case it works very slowly because you have all categories enabled
> 
> * Trending
> * Recommended
> * New Uploads
> * Most Viewed
> * Popular
> * Health
> * News
> * Comedy
> * Entertainment
> * Gaming
> * Cartoons
>   etc...
>   I have visible 2 categories that need to load and the rest are visible by clicking on the button in the category menu

I like this when it is closed. Looks nice

**Comment by JoshWho** [comment]
I think you got it all good now. I even see the cookie so it remembers to stay out. Super nice. Thank you @DanielnetoDotCom
