### ISSUE TITLE
end live every hour not working

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8190]
I have the new feature to end lives every hour enabled but still see dead lives on the live page. 
![09b97cc4-6697-42e8-afa3-b7e6cc4811ab](https://github.com/WWBN/AVideo/assets/39392449/3574864e-aeed-4a59-b67c-97f4834e74d5)

![1834f2f6-a3a7-431d-99bb-6d9105f08bef](https://github.com/WWBN/AVideo/assets/39392449/057aa23e-7194-4176-8526-7166467be940)

**Comment by JoshWho** [comment]
When I manually click the end all live streams it clears them

![0b7024b9-42c9-45f9-8ef5-9eb6f13e1ad8](https://github.com/WWBN/AVideo/assets/39392449/5e4e4fc1-86b3-4116-84d9-6472ea0af4fd)

**Comment by DanielnetoDotCom** [comment]
did you wait one hour?

**Comment by JoshWho** [comment]
I had it running all day over 18 hours

**Comment by JoshWho** [comment]
Look now They are just sitting there until I click end all

**Comment by JoshWho** [comment]
root@joshwhotv:~# php /var/www/html/YouPHPTube/plugin/Live/view/finishAll.json.ph
Could not open input file: /var/www/html/YouPHPTube/plugin/Live/view/finishAll.json.ph

**Comment by DanielnetoDotCom** [comment]
you missed the last "P"

you typed `finishAll.json.ph` and it should be `finishAll.json.php`

**Comment by JoshWho** [comment]
root@joshwhotv:~# php /var/www/html/YouPHPTube/plugin/Live/view/finishAll.json.php
PHP Warning:  require_once(../../../videos/configuration.php): Failed to open stream: No such file or directory in /var/www/html/YouPHPTube/plugin/Live/view/finishAll.json.php on line 3
PHP Fatal error:  Uncaught Error: Failed opening required '../../../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/html/YouPHPTube/plugin/Live/view/finishAll.json.php:3
Stack trace:
#0 {main}
  thrown in /var/www/html/YouPHPTube/plugin/Live/view/finishAll.json.php on line 3
You have new mail in /var/mail/root

**Comment by DanielnetoDotCom** [comment]
can you please update and try this?

**Comment by JoshWho** [comment]
That looks like it did it. It stopped in the middle of running and had to cancel and rerun it but it finished the second time and cleared the old streams

![a32f7935-3845-4236-b057-d15ef8a1e37f](https://github.com/WWBN/AVideo/assets/39392449/c10689c8-266b-441e-914f-26bf636efca4)
