### ISSUE TITLE
Gallery Plugin-ShortsCustomTitle is ignored

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#8193]
After change, save and clearing cache, Gallery front page still shows **Shorts** as title.
 
![Gallery-Shorts-CustomTitle](https://github.com/WWBN/AVideo/assets/85363361/0adc8d11-c32e-4364-ad9f-01cc217e0476)

![Gallery-Shorts-FrontPage](https://github.com/WWBN/AVideo/assets/85363361/ca391d7f-e5dc-49a0-b2c2-0e8b1a3ddade)

**Comment by DanielnetoDotCom** [comment]
please try this

**Comment by GreenDragonTavern** [comment]
You be Da'Man! Thank you...
