### ISSUE TITLE
Filters ☕️

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8195]
**Is your feature request related to a problem? Please describe.**
Finding videos using the /mvideos interface can be frustrating when there are a lot of videos. My sites have a lot of videos. :-(

If we only had a way to cut through the noise…

**Describe the solution you'd like**
We need a filter feature for /mvideos. 

Filters remove content. Opening /mvideos displays _all_ content. If we had filters, we could reduce content in the view until we are focused on specifically what we are looking for.

Filter by: Channel name (i.e. select a channel), now, only videos from this channel are displayed. Popup menu with all categories, select, and selected category is displayed. To clear it, probably the first menu item is "All", so user selects "All" again.

Filter by: Owner (i.e. select an owner), now, only videos from this owner are displayed. Probably, type to select is best, text field can auto complete from the list of user names so user only has to type 2-3 characters or something. Just clearing the text here reverts to "All" for the filter.

Filter by: Date range popup. This can really narrow down the window for some modalities of search.

Probably there should always be an (X) button by the filters to clear all selected filters. Each individual filter could have its own (x).

_if this were a table view with columns, you could put a filter per column, that's pretty dope, but I think these three cover most of the use cases_

![Screen Shot 2023-07-19 at 12 33 06 PM](https://github.com/WWBN/AVideo/assets/11711050/4862e085-d889-4fcd-abc8-531136d53fe2)

**Comment by DanielnetoDotCom** [comment]
Hi, basically if I understand correct you need a filter per channel, is that correct?

**Comment by walt93** [comment]
Channel, owner, date
