### ISSUE TITLE
How is this implemented? (JoshWho Support Center page integrated into AVideo)

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8196]
**Describe the question**
I want to do this:

**Screenshots**
It looks to me like there's some sort of empty AVideo page that has an embed in it pointing to an osTicket install. I need a skeleton/template to make a couple of similar pages - integrated into my AVideo with nav controls to access in the left menu.

![Screen Shot 2023-07-19 at 2 10 29 PM](https://github.com/WWBN/AVideo/assets/11711050/972252d2-1c4b-42c1-a22e-99e09bf8d03a)

**Comment by JoshWho** [comment]
You can host any other site and have it embedded into a page using the About Menu plugin thinggy. Just make a side link then you can make it redirect to a link or embed it using Iframe.

**Comment by walt93** [comment]
I'm not tracking you. I don't see an About Menu plugin. From the "Topmenu" plugin, it can add the left menu items, but they just have a URL and it's not clear to me if/how it supports the embed/iframe.

**Comment by JoshWho** [comment]
![download (20)](https://github.com/WWBN/AVideo/assets/39392449/616c0148-f91f-4c38-bce5-e6cdea6f57e0)

![398d1541-2d27-4e2f-a92d-7e531650098f](https://github.com/WWBN/AVideo/assets/39392449/4180f9d7-23e1-48eb-905b-6e2d579da6d7)

![download (21)](https://github.com/WWBN/AVideo/assets/39392449/962a134c-b7cd-4ff5-ba85-6d262f295aa9)

**Comment by walt93** [comment]
Ohhhhhhh TY, TYVM! :-D
