### ISSUE TITLE
Super minor UI tweek, corners & colors

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8197]
**Is your feature request related to a problem? Please describe.**
We've added shorts and they have rounded corners. But they don't match the other videos on the page. 

**Describe the solution you'd like**
![Screen Shot 2023-07-19 at 6 31 59 PM](https://github.com/WWBN/AVideo/assets/11711050/d059c2d8-1f93-4294-8f6f-78118cea31eb)

**Comment by DanielnetoDotCom** [comment]
for now I think you can do it with a custom CSS
