### ISSUE TITLE
Safari sucks. Long live Safari. Can we hide the top category scroller on Safari?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8198]
**Describe the bug**
If this is too much of a pain to fix, can we at least hide its controls on desktop Safari? (long standing bug is the control simply does not render)

![Screen Shot 2023-07-19 at 6 46 25 PM](https://github.com/WWBN/AVideo/assets/11711050/6dbbb86b-7e30-4a2c-b24c-b8b3e85435f5)

**Comment by para2022** [comment]
Yes it affects the mobile device too (phone) the same thing happens on safari and chrome on iPhone creating a blank space at the top. It’s needed fixing for over a year. Works fine on desktop.

**Comment by DanielnetoDotCom** [comment]
please check this update
