### ISSUE TITLE
Left Side Bar Menu

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#8204]
Why does it stay open now on certain pages, My Account for example? When I click My Account, if you're going to keep it open the below screenshot shows what is and what should be. Anytime the menu is open there should be an **X** to close vs the three horizontal bars to open. It's kind of confusing the way you have it now.

![Behavior](https://github.com/WWBN/AVideo/assets/85363361/ae96bc45-ad96-4b72-a229-7da7d4fa781f)

**Comment by GreenDragonTavern** [comment]
Same with clearing cache. Open menu, clear cache, click top bar icon to refresh Front Page and this shows up...

![Behavior2](https://github.com/WWBN/AVideo/assets/85363361/23b76035-8c7f-4ae5-a081-e0c55b5620ea)

**Comment by GreenDragonTavern** [comment]
Something weird is happening with Front Page. Now I'm getting the first Category menu item highlighted as selected. On Front Page, no category should be highlighted as selected.
 
![Categories-Behavior-Front-Page](https://github.com/WWBN/AVideo/assets/85363361/d6cd4721-b3c3-4254-9670-2674ffc89f90)

**Comment by DanielnetoDotCom** [comment]
I am still sending updates. 

It may be done in 30 min

regarding the menu, it should memorize what ever you open or close.

**Comment by GreenDragonTavern** [comment]
Roger that if that's the case now. Still should show **X** as you traverse AVideo with menu open. Right now it does keep menu open but reverts to the three horizontal lines once you click past the initial open menu (shows **X** to close). As you navigate AVideo with menu open, shouldn't it show **X** until menu is actually closed? Only time three horizontal lines should show is when menu is hidden.

**Comment by DanielnetoDotCom** [comment]
The X should show properly, did you clear the cache?

what is your site link?

**Comment by GreenDragonTavern** [comment]
> what is your site link?

https://tube.farmersmarket.site

**Comment by DanielnetoDotCom** [comment]
the URL does not work here

**Comment by GreenDragonTavern** [comment]
When ya get a chance, try again: https://tube.farmersmarket.site/

**Comment by DanielnetoDotCom** [comment]
did you update your site with git pull?

did you clear the cache?

you still have a reference to the /jquery.scrolling-tabs.min.js but this does not exist anymore.

I guess you are missing some update or cache clean up

**Comment by DanielnetoDotCom** [comment]
I just sent you another update, please try this and clear the cache

**Comment by DanielnetoDotCom** [comment]
NVM, I could reproduce it, I will have a fix soon

**Comment by DanielnetoDotCom** [comment]
This update may fix it, make sure you clear your cache after update.

**Comment by GreenDragonTavern** [comment]
Looks like that did the trick, and smoother look and feel...good work!
