### ISSUE TITLE
Uploading using mobileManager/upload.php - how could I put certain videos into "unpublished" state awaiting moderator review?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8206]
**Is your feature request related to a problem? Please describe.**
I want my scraper to proactively get things I *might* want to publish. If I could put them into "unpublished" state I could treat it as a "review queue" (example: I've got one scraping rumble with a search for "Jim Caviezel" but there are too many, some are in the wrong language, publishing them all is flooding the site)

**Describe the solution you'd like**
A parameter on mobileManager/upload.php

**Comment by DanielnetoDotCom** [comment]
I just added a new status

Check the customize advanced plugin -> Video moderation

When enabled, leaves all videos unpublished. Only the administrator and video moderators have the authority to activate and make these videos public
