### ISSUE TITLE
Why does avideo insist on asking for storage? Why is it always asking for more?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8208]
**Describe the question**
Before it was 1.4GB, later 2.something, now it wants 3.7GB. At times, I've told it "Allow" and others I've told it otherwise. When does it end? 

**Screenshots**
![Screen Shot 2023-07-20 at 12 16 30 PM](https://github.com/WWBN/AVideo/assets/11711050/2cc8acf0-1a97-406a-8092-c8d9271da28a)

**Comment by DanielnetoDotCom** [comment]
Maybe cache?

I am not sure where does this come from.

**Comment by walt93** [comment]
Is this Safari-specific?

**Comment by DanielnetoDotCom** [comment]
I am not sure, I have never seen this before

**Comment by walt93** [comment]
Seems Safari specific…
Seems that from the Develop menu -> Empty Caches… makes it stop
