### ISSUE TITLE
Shorts still showing long videos and also Embeds

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8210]
![5dc61f7e-45a6-4f75-a31d-8135add01c72](https://github.com/WWBN/AVideo/assets/39392449/fe3f4276-fe15-438c-9137-177ae163cd31)

I still see embeds from Rumble to appear in it

**Comment by DanielnetoDotCom** [comment]
Hi, does it appear when it autoplay, or does it appears when it autoplay?

I still need to improve the Shorts autoplay to play the next video in the shorts list

**Comment by JoshWho** [comment]
I am not sure I just ran the update I will check When I get home tonight if that did it.

**Comment by JoshWho** [comment]
That looks like it is fixed. Super awesome. Thank you @DanielnetoDotCom
