### ISSUE TITLE
Categories Top Bar - Selection Behavior

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#8212]
Don't know why but it now does not highlight category after selection anymore. Image; 1) Front Page, 2) Result of clicking Markets (and what currently displays), **3) What it should look like for a selected category (in this instance Markets)**.

![Selected](https://github.com/WWBN/AVideo/assets/85363361/09be7559-d5b0-41f5-a77f-f62159b30879)

**Comment by DanielnetoDotCom** [comment]
Try this update

**Comment by GreenDragonTavern** [comment]
Bada Bing! Thank you.
