### ISSUE TITLE
How do "Action" menus send the video information to the specified URL?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8213]
**Describe the question**
I was hacking the source code directly to get a button for each video that calls my back end & passes the video's id. 

But I noticed that in the TopMenu plugin we can create an "Action" menu that calls a URL. It creates exactly the UI that I want, and it puts it exactly where I want it. Soooo very close.

Is it possible for this to send the video_id to that URL as a query parameter or in the body or something? 

**Screenshots**
![Screen Shot 2023-07-21 at 1 04 08 PM](https://github.com/WWBN/AVideo/assets/11711050/e0544548-ca03-41b2-933c-9c7ac7c0234a)
![Screen Shot 2023-07-21 at 1 04 23 PM](https://github.com/WWBN/AVideo/assets/11711050/0c0e6c0b-0ee2-451e-a40a-6a0eb80b93d4)
![Screen Shot 2023-07-21 at 1 05 37 PM](https://github.com/WWBN/AVideo/assets/11711050/6c42ec05-67a7-45ca-8301-3e262ddc0af2)

**Comment by DanielnetoDotCom** [comment]
I see, for now, I do not have it, but I may add some placeholders in the future. for example:

add http://mylint.com/someURL?videos_id={videos_id}

{videos_id} will be replaced with the actual videos ID

**Comment by walt93** [comment]
That would be fantastic. I'd also need to be able to discriminate at the endpoint, which server the request came from, probably I can pick that out of the headers or something. With those two pieces I can get it done!
