### ISSUE TITLE
WWBN Encoder not sending to site

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8214]
![image](https://github.com/WWBN/AVideo/assets/39392449/5f6c8882-832c-40f9-b5e6-2cda058bcbf1)

![f1186fa4-3c46-4464-8f81-af4097012721](https://github.com/WWBN/AVideo/assets/39392449/5fe942c4-c955-425a-a30a-e74763df8393)

**Comment by DanielnetoDotCom** [comment]
I just checked and the video is not there. I guess it was transferred

**Comment by JoshWho** [comment]
it never showed see the images I took when uploading. It never showed it encoding

**Comment by JoshWho** [comment]
I did it 3 times' now

**Comment by JoshWho** [comment]
Might just need to update it git pull

**Comment by JoshWho** [comment]
OK I Found the video but it is not in the place as the next new video I had to go to page 2 and found it

![46b7d343-40e1-4aa9-9793-bb9696c8d07e](https://github.com/WWBN/AVideo/assets/39392449/0eabe21f-6d5e-435b-b7c9-185da156f4ad)

**Comment by JoshWho** [comment]
So it is transfering fine. It is just not putting it in the right place once done

**Comment by DanielnetoDotCom** [comment]
make a git pull and check this https://github.com/WWBN/AVideo/issues/8205#issuecomment-1644390551

**Comment by JoshWho** [comment]
Done thank you
