### ISSUE TITLE
Anyone else see the thin line on playlist in wide screen theatre mode? 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8215]
![e086525c-6bca-4ac2-9057-6b888584db17](https://github.com/WWBN/AVideo/assets/39392449/1e27cdf0-cdd1-4883-8ea4-c0a2d6b89cf3)

**Comment by DanielnetoDotCom** [comment]
What is the link for it?

**Comment by JoshWho** [comment]
> What is the link for it?

https://www.joshwhotv.com/plugin/PlayLists/player.php?playlists_id=165116

**Comment by DanielnetoDotCom** [comment]
Try this update

**Comment by JoshWho** [comment]
All fixed. Thank you @DanielnetoDotCom
