### ISSUE TITLE
Directory to import videos that are locally stored

### ISSUE THREAD

**Issue by ruzakuku** [WWBN/AVideo#8217]
Hello,

AVideo is running at /home/domain/public_html/

We have stored some .mp4 videos to be encoded by the "import" function 
at /home/domain/public_html/storage/

In the "Import local videos" menu we tried a few variants for the "Local path":
/home/domain/public_html/storage/
/public_html/storage/
/storage/
storage

Etc,

None of them work. What is the correct path to write?

By the way it *seems* that the 3 buttons (List files, and the two boxes) don't work. Using Brave and Firefox browsers. Maybe rhe problem is here?

Thank you!

**Comment by DanielnetoDotCom** [comment]
`/home/domain/public_html/storage/` should be the correct one, but as I mentioned before we do not support centos.

and I am pretty sure this is a permission issue, that one site cannot access another site's files. 

I cannot help you resolve that but you may find a solution on google.

**Comment by ruzakuku** [comment]
Fixed, thank you.

**Comment by ruzakuku** [comment]
It was indeed a permission point. Thank you!
