### ISSUE TITLE
User Controll plugin

### ISSUE THREAD

**Issue by ruzakuku** [WWBN/AVideo#8231]
This plugin is supposed to allow to block users on their IP.

Question: Where can we see the IP of a connected user? There is no "IP" in the user data, nor in the uploaded video data.

**Comment by DanielnetoDotCom** [comment]
The User_Controll plugin provides administrators with the ability to manage, control, and ban users and IP addresses from their AVideo platform. This functionality also extends to halting a user's live-stream broadcast. 

**NOTE:** Ensure your [NGINX control module](https://github.com/arut/nginx-rtmp-module/wiki/Control-module) is enabled for controlling live stream broadcasts.

## How it Works

Upon installation, the User_Controll plugin begins recording all login attempts. This includes capturing various details about the user at each login.

### Banning a User

The simplest way to ban a user is through the User Manager menu. Here are the steps:

1. Open the User Manager menu.
2. Search for the user you wish to ban.
3. In the user's row, you will see a "Ban" button. Click on it.

This action will open a list of all IP addresses the user has used to log in to the platform.

4. Select the IP address you wish to ban.
5. Click the "Add" button to add this IP to the banned list.

Once banned, the user will no longer be able to access the site from the banned IP, and if they were broadcasting a live stream, it will be interrupted and stopped.

Please use this feature with caution and be sure to only ban users or IP addresses when it's absolutely necessary to maintain the safety, security, and integrity of your AVideo platform.

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/User_Controll-plugin

**Comment by ruzakuku** [comment]
Cristal clear, thank you !
