### ISSUE TITLE
Bug in the "most recent" videos display?

### ISSUE THREAD

**Issue by ruzakuku** [WWBN/AVideo#8233]
Simply the most recently added videos are not at the top.

In the DB table "videos" the "created" data is correct.

But when sorting the videos on the site (using the "Gallery" plugin on the homepage or in the "up next" column when looking at a video) the order is not correct. That is easily visible on the website homepage by looking at the date created.

By the way in the table some videos have "NULL" as "order" and it is those videos that don't show up at their right order.
![2023-07-24_232052](https://github.com/WWBN/AVideo/assets/38063103/71ba3d83-45ae-4c0f-98a9-114728f3ffbc)

**Comment by DanielnetoDotCom** [comment]
it should be sorted by oder, then by date (newest first)

null order is ignored

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/issues/8205#issuecomment-1644390551

**Comment by ruzakuku** [comment]
Ok but how the ORDER is defined? And why these NULL values? Now all videos we upload come with a NULL value. How to make them ordered normally?

**Comment by DanielnetoDotCom** [comment]
null is expected, it will always be null unless you specify an order.
