### ISSUE TITLE
Gallery view / theater mode - can we pin the video to the window edges (as does Youtube)?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8237]
**Is your feature request related to a problem? Please describe.**
Our "theater mode" has black bars to the left and right of the video. Black bars are uninteresting compared to the changing pixels of the video. The flow down the page is chunky. 🫤

**Describe the solution you'd like**
I think it would flow better as the full width of the window, as per YouTube. In Theater mode the video is the highlight. 🤩

![Screen Shot 2023-07-24 at 8 47 22 PM](https://github.com/WWBN/AVideo/assets/11711050/71259df4-0903-4e55-8e95-0ad82a972726)

_If you take this change up (and you should, it would look a **lot** better), recommend also pinning the views below the video to the left/right sides. The posterboxed look is ... dated._

**Comment by GreenDragonTavern** [comment]
@walt93 - You can play around with these style settings and possibly get a little closer to what you're looking for.

```<style> .col-lg-offset-2 { margin-left: 10.5% !important; } </style>```
```<style> .col-lg-8 { width: 79% !important; } </style>```

**Comment by walt93** [comment]
@GreenDragonTavern where would I hack that in? A search is showing many instances throughout the bootstrap classes.

**Comment by GreenDragonTavern** [comment]
> @GreenDragonTavern where would I hack that in? A search is showing many instances throughout the bootstrap classes.

Play with it in **Script Code** section of Site Configurations.

**Comment by walt93** [comment]
Just got back to this, this is so cool, thank you @GreenDragonTavern
