### ISSUE TITLE
Errors in Apache when trying to optimize website

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#8240]
Hi 
There seems to be an issue with apache. My colleague was updating the SEO side of it, but came across errors in the apache configuration. Now cannot restart apache apache:- 
================================================
Yeah your apache is broke or something was configured incorrectly, the changes I am making in there are not being reflected.

I get this when I attempt to restart apache:

root@kollossus:/home/kollossus/public_html# apache2 -k restart
[Tue Jul 25 14:29:06.320721 2023] [core:warn] [pid 1892376] AH00111: Config variable ${APACHE_PID_FILE} is not defined
[Tue Jul 25 14:29:06.320770 2023] [core:warn] [pid 1892376] AH00111: Config variable ${APACHE_RUN_USER} is not defined
[Tue Jul 25 14:29:06.320775 2023] [core:warn] [pid 1892376] AH00111: Config variable ${APACHE_RUN_GROUP} is not defined
[Tue Jul 25 14:29:06.320785 2023] [core:warn] [pid 1892376] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Tue Jul 25 14:29:06.328797 2023] [core:warn] [pid 1892376] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Tue Jul 25 14:29:06.328933 2023] [core:warn] [pid 1892376] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Tue Jul 25 14:29:06.328943 2023] [core:warn] [pid 1892376] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Tue Jul 25 14:29:06.328986 2023] [core:warn] [pid 1892376] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Tue Jul 25 14:29:06.328994 2023] [core:warn] [pid 1892376] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Tue Jul 25 14:29:06.329020 2023] [core:warn] [pid 1892376] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Tue Jul 25 14:29:06.329031 2023] [core:warn] [pid 1892376] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
AH00543: apache2: bad user name ${APACHE_RUN_USER}

===================================================

root@kollossus:~# apache2 -k restart
[Tue Jul 25 14:53:09.107222 2023] [core:warn] [pid 17006] AH00111: Config variable ${APACHE_RUN_DIR} is not defined
apache2: Syntax error on line 80 of /etc/apache2/apache2.conf: DefaultRuntimeDir must be a valid directory, absolute or relative to ServerRoot

Same error when trying to restart apache as before ^
====================================================
Website currently down.
Please advise or can I get support. Thanks

**Comment by DanielnetoDotCom** [comment]
I have no idea what is it.

**Comment by kollossus55** [comment]
Does it need to be re installed or Re-configured ?

**Comment by GreenDragonTavern** [comment]
Umm, find a new colleague? Have your colleague undo whatever he did would be a good first step.

**Comment by kollossus55** [comment]
Ok.. lets go for it.. will send payment over shortly.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kollossus55** [comment]
Thanks
