### ISSUE TITLE
OpenGraph tags are dead. Long live OpenGraph tags.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8252]
**Describe the bug**
Pasting a link to a video on my avideo site does not pull OG tags in Telegram, Twitter, Truth Social or Gab (and I expect, nowhere else either, I just tested four…)

**To Reproduce**
1. Copy the  link to a video from your avideo site
2. Post it on social media
3. Look at your post
4. See that it has not pulled the OG tags, it is just a link.

**Expected behavior**
Video to display and play in-line on social media platforms.

**Screenshots**
Twitter:
 ![Screen Shot 2023-07-26 at 4 06 37 PM](https://github.com/WWBN/AVideo/assets/11711050/36400cf2-4d6b-4f93-857d-6b5d66b47b25)
Telegram: 
![Screen Shot 2023-07-26 at 4 07 06 PM](https://github.com/WWBN/AVideo/assets/11711050/b24bf1c0-9cf8-44a9-b069-5aab36fb9c99)
Truth Social: 
![Screen Shot 2023-07-26 at 4 07 51 PM](https://github.com/WWBN/AVideo/assets/11711050/4bc3da01-b170-4d64-8d3f-27f0da564c85)
Gab: 
![Screen Shot 2023-07-26 at 4 08 24 PM](https://github.com/WWBN/AVideo/assets/11711050/610f6924-45ac-4317-b3c1-669f8989252a)

**Comment by DanielnetoDotCom** [comment]
can you please test if the same happens with the tutorials site? please test any video.

https://tutorials.avideo.com/

**Comment by walt93** [comment]
![Screen Shot 2023-07-26 at 4 34 23 PM](https://github.com/WWBN/AVideo/assets/11711050/870a526f-7055-47a5-81df-0d5d1d344133)

So how did it break for me? What can I check?

**Comment by DanielnetoDotCom** [comment]
first compare your og tags and mine. 

then check if you are not blocking the bots

**Comment by walt93** [comment]
Daniel I think the computer is trying to drive me nuts today. I posted four screenshots above, those all happened. Now I went back to test in the Twitter card validator, and, no errors, and I tried it again in Twitter, and it is somehow working now.

Current theory? I had just uploaded that video. Maybe it was set to publish-in-the-future?

**Comment by DanielnetoDotCom** [comment]
maybe yes. if is set to the future, it will only work for admin

**Comment by walt93** [comment]
That's it then, thanks.
