### ISSUE TITLE
About the (paid) "customize" plugin.

### ISSUE THREAD

**Issue by ruzakuku** [WWBN/AVideo#8262]
In the admin panel the installed version is 1.0 and a message invites to update to 1.4

We downloaded the file from personal area on your site, unzipped it. We removed all previous files of the "Customize" directory and uploaded the new one.

1- In the admin panel the installed version is still 1.0 with the same message inviting to upgrade.

2- None of the data (header, footer, etc) are saved, all remain blank.

We checked the DB table "extraConfig" is created correctly, according to the install.sql file. 

Thank you to tell us what to do!

**Comment by DanielnetoDotCom** [comment]
check this

https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin#addressing-permission-issues

**Comment by ruzakuku** [comment]
Yes we did it, deleting the directory and reinstalling it by uploading the files. But nothing is saved in the database when we try to use the plugin.

**Comment by DanielnetoDotCom** [comment]
but are you on version  1.4? or still 1?

If still 1, you need to resolve that. try to download the Customize plugin again. 

if is 1.4 check your AVideo logs

**Comment by ruzakuku** [comment]
Fixed by re-re-installing it :)
