### ISSUE TITLE
Is shorts working?

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#8277]
I have many shorts but only a few pages (3) are showing.

**Comment by milehighkaraoke** [comment]
check length and set it in your shorts plugin

**Comment by fakeologist** [comment]
I did...still seems like some are missing.

**Comment by DanielnetoDotCom** [comment]
@fakeologist please check not, I sent you updates

**Comment by fakeologist** [comment]
Seems ok now thanks
