### ISSUE TITLE
How could we import .m3u8 playlists into AVideo

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8280]
**Describe the question**
Bunny.net have a pretty dope HLS pipeline, upload mp4, get m3u8 link (they've even got a JS player but we don't need)

How might we use these in AVideo?

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
I am not sure what is it

**Comment by walt93** [comment]
HLS playlist

**Comment by DanielnetoDotCom** [comment]
I am not sure about this bunny feature
