### ISSUE TITLE
How to disable Paypal?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8284]
**Describe the question**
Paypal are communists, and we must not give them our business.

I've turned off the PayPal plug-in. My subscriptions are still offering users to use PayPal.

**Screenshots**
![Screen Shot 2023-08-06 at 5 53 16 PM](https://github.com/WWBN/AVideo/assets/11711050/08a0d0bc-f8f9-4461-8b2b-a73f86b99846)

![Screen Shot 2023-08-06 at 5 53 43 PM](https://github.com/WWBN/AVideo/assets/11711050/2b7406d8-f6b7-480b-9a35-10f059b1c548)

**Comment by DanielnetoDotCom** [comment]
![image](https://github.com/WWBN/AVideo/assets/18009293/71d1f9f2-2f64-4fe5-9a43-a4163a377dd6)

**Comment by walt93** [comment]
Ok. Just a note, I had this turned off, so probably would have never, ever thought to look there.

![Screen Shot 2023-08-07 at 2 58 15 PM](https://github.com/WWBN/AVideo/assets/11711050/ff58e6b7-92da-40f6-842e-39b582c2fb8f)
