### ISSUE TITLE
Encoders inaccessible

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8293]
@DanielnetoDotCom The encoders are inaccessible, yesterday I checked that they were all full of files. And today it is without access:
https://network.avideo.com/

**Comment by DanielnetoDotCom** [comment]
checking now, thanks

**Comment by DanielnetoDotCom** [comment]
looks like the MySQL crashed, it should be back now, thanks

**Comment by gbrn** [comment]
Started working again. Thanks
