### ISSUE TITLE
How could I create an "Editor's Choice" row?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8295]
**Describe the question**
We tried using the "sort order" to pin some videos to the top row. It was too confusing, too many complaints, people expect "Date Added" to be in order. _We need to put some UI on this to make it usable IMO, see https://github.com/WWBN/AVideo/issues/8279_

I'd like to create a category called "Editor's picks" and sort it up above Date Added using Gallery.

I'm super confused about how to do that.

**Comment by DanielnetoDotCom** [comment]
Hi, I am reviewing this sort order, I like your idea to have a specific row for that, the thing is I also would like to respect that order when you are listing videos by category

**Comment by walt93** [comment]
That would be super phenomenal.

While you're contemplating the implementation, we need something like this for shorts as well. Currently the trending algorithm, it doesn't produce a good result from my database. Ideally date added + some variant of this sort order function. Maybe it comes out as two (or three) shorts rows we can turn on in the Gallery plug-in. 

IMO this would be rad: 
• Shorts/Trending 
• Shorts/Date Added 
• Shorts/Specified sort order
