### ISSUE TITLE
(Feature request) A preference for shorts: [X] Only use 9x16 portrait videos

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8299]
**Is your feature request related to a problem? Please describe.**
In my mind, the shorts feature should be portrait mode videos, that's the use case out in the wild (Tik Tok, YouTube) 

We just refer to them as "shorts" because the sites that host them have restrictions like 1min and 3min

**Describe the solution you'd like**
Ideally, since it's already deployed, we add a preference to restrict shorts to the Tik Tok vertical format. We can derive the aspect ratio from that extendedInfo JSON -unknown but probably we want to distill that out into a BOOL field like "Portrait" or something to optimize the query.

**Describe alternatives you've considered**
I got nothing, no way to pull that off with the current implementation.

**Comment by DanielnetoDotCom** [comment]
this idea may also be added in this thread https://github.com/WWBN/AVideo/issues/8295
