### ISSUE TITLE
Encoder scheduling error

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8300]
Encoder scheduling error. When you select a time other than now. Displays the error:

![image](https://github.com/WWBN/AVideo/assets/37880073/a0f5f7b3-935e-4860-957b-6550e17e8edb)

![image](https://github.com/WWBN/AVideo/assets/37880073/1c21a5e4-9061-459b-9b54-c77de5089175)

**Comment by DanielnetoDotCom** [comment]
thanks, please make a git pull and this may be resolved

**Comment by gbrn** [comment]
Danny, check your correction... when I select 1 month from now, the date doesn't change automatically in the calendar. Check it out.

![image](https://github.com/WWBN/AVideo/assets/37880073/b6b023a4-ada1-4968-9097-4da4afaa0510)

![image](https://github.com/WWBN/AVideo/assets/37880073/75b6feeb-4244-4b2a-9b59-327df6d15df6)

![image](https://github.com/WWBN/AVideo/assets/37880073/08aaeb84-0c08-4779-9f73-0044ff3a8ac9)

**Comment by DanielnetoDotCom** [comment]
Sorry you were right, please try now
