### ISSUE TITLE
[Question] regarding YPTSocket and high user counts

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8302]
**Describe the question**
I was watching as something went viral, one video had 200, 250, 300, 350 users watching simultaneously, and the count was increasing. Now the plug-in won't render number of users, it just spins.

What do I need to tune for the site taking on more traffic like that?

**Screenshots**
Both the video eyeballs counter and the YPT plugin are spinning, and spinning.

![Screen Shot 2023-08-10 at 7 53 07 PM](https://github.com/WWBN/AVideo/assets/11711050/3bfd27b7-d5dc-40e2-8928-4f556bbf4d16)

It looks like something is glitching with YPTSocket itself, there are only a few views that are showing in the log for today:

![Screen Shot 2023-08-10 at 8 01 43 PM](https://github.com/WWBN/AVideo/assets/11711050/6bac3b83-ce54-49ea-a1ae-d4e1bd61fd01)

**Comment by DanielnetoDotCom** [comment]
just asking, do you have the php-sqlite3 installed?

**Comment by walt93** [comment]
I did install it, and it said it's already installed, and when I run the YPT/stopserver script it continues to complain about it's absence. 

```
$ sudo apt install php-sqlite3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
php-sqlite3 is already the newest version (2:8.2+93+ubuntu22.04.1+deb.sury.org+2).
The following packages were automatically installed and are no longer required:
  libllvm13 libvulkan1 libxcb-randr0 mesa-vulkan-drivers
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 33 not upgraded.

$ sudo php /var/www/html/conspyre.tv/plugin/YPTSocket/stopServer.php
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlite' (tried: /usr/lib/php/20220829/pdo_sqlite (/usr/lib/php/20220829/pdo_sqlite: cannot open shared object file: No such file or directory), /usr/lib/php/20220829/pdo_sqlite.so (/usr/lib/php/20220829/pdo_sqlite.so: undefined symbol: php_pdo_unregister_driver)) in Unknown on line 0
Searching for port: 2053
Server is already runing on port 2053 Killing, PID 4144796
```

**Comment by DanielnetoDotCom** [comment]
### Detecting PHP Version & Installing `php-sqlite3`

1. **Detect PHP Version:**
    Open your terminal and run:
    ```bash
    php -v
    ```

    The output will show your PHP version, e.g., `PHP 7.4.15`.

2. **Install `php-sqlite3`:**

      Replace `7.4` with your PHP version:
      ```bash
      sudo apt-get update
      sudo apt-get install php7.4-sqlite3
      ```
