### ISSUE TITLE
Date Picker on Advance Options->Created date and time

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8303]
**Is your feature request related to a problem? Please describe.**
I LOVE THIS NEW FEATURE IT IS A GODSEND! [HUG EMOJI]

**Describe the solution you'd like**
A date picker would be the 💣

**Describe alternatives you've considered**
Typing dates by hand in ISO format is so... retro

**Comment by lachainestoplinky** [comment]
Hello, I am proposing by a calendar
but be careful not to lose the possibility of changing
Hours Minutes Seconds
