### ISSUE TITLE
How could we make the whole title of the video visible?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8304]
**Describe the bug**
Many video titles are cut off. It seems that we could extend the layout to three lines of text. This is probably changing one simple constant. If you don't want to do it, could you please tell us where in the code to change this?

**To Reproduce**
1. Create a video with a long title
2. Observe the videos page, how the title cuts off

**Expected behavior**
To be able to read the entire title

**Screenshots**
Example row: 4 out of 6 titles are truncated. This makes the site look very clunky and we get complaints from users. We have >10,000 titles, and simply cannot edit every single one for length.

![Screen Shot 2023-08-11 at 1 21 44 AM](https://github.com/WWBN/AVideo/assets/11711050/b5862bb7-5fdf-4d0d-9440-12caf0c260fd)

**Comment by DanielnetoDotCom** [comment]
Due to SEO requirements, this is limited to 120 chars. also, this is hardcoded

I may add an option to increase it in the future, but after some research, I found that titles must be max 120 chars

**Comment by walt93** [comment]
Understood. Look at the screenshot. We seem to have <120 chars but we are clipping nonetheless. Layout issue.

**Comment by walt93** [comment]
Now we have a large icon taking up more space in a layout that was already too crowded.

Daniel, can you see that every single title is cut off? Is it possible that we could extend this layout to three lines? This looks bad, so many people complain about the look of the site, I don't know if you're aware?

![Screen Shot 2023-08-14 at 9 50 57 PM](https://github.com/WWBN/AVideo/assets/11711050/0e173e10-b326-40f2-be30-59733d15215a)

**Comment by DanielnetoDotCom** [comment]
Add a custom CSS to make the title font smaller, it will fit your needs
