### ISSUE TITLE
How did these two categories / users (?) make it into the Gallery sort sections?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8305]
**Describe the question**
Something is confusing. Where did the gallery sections with the (>) play icon come from? I thought these came from Categories->Suggested, but I have a different set of categories with Suggested set to true, and they do not appear here.

**Screenshots**
![Screen Shot 2023-08-11 at 3 46 23 AM](https://github.com/WWBN/AVideo/assets/11711050/905cbee5-5fe3-4712-949d-70034506b8aa)

**Comment by DanielnetoDotCom** [comment]
is this a category or a channel?

**Comment by walt93** [comment]
Uuhhhh geez I have thousands of users and 700 categories. I THINK they are users. There are no categories named that which are marked "suggested"
