### ISSUE TITLE
Video doesn't show on My Videos after encoding

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8314]
Recentrly i notice a problem in the way the "My Videos" list is being displayed. First I noticed that some newer vides that were uploaded are showing out of order on my channel videos page. I had older videos appearing before new ones.

Now the issue is that after encoding a video it doesn't even show on my list, not even the process of encoding. What strange is that eventually the video appears on my channel and on the front page but not on my videos list.

Here is a screen shot of my videos list with latest date and one of the video I uploaded yesterday which is working.

![Screenshot 5783-11-26 at 16 50 39](https://github.com/WWBN/AVideo/assets/58882903/0c0fa1df-0698-41af-97d8-478d2aa76208)

This was uploaded yesterday:

![Screenshot 5783-11-26 at 16 50 55](https://github.com/WWBN/AVideo/assets/58882903/08779f80-bdf2-4437-82c0-8c6f7fc9be93)

This is the URL: https://alive528.com/v/21358

This is what the encoder log is showing me:

![Screenshot 5783-11-26 at 17 01 57](https://github.com/WWBN/AVideo/assets/58882903/1b764413-8353-4ddd-a996-53840afc77ee)

**Comment by guymass** [comment]
It looks like on my channel the order is correct now and the video is showing there as the latest one. However I can't see it in my videos list.

![Screenshot 5783-11-26 at 17 35 33](https://github.com/WWBN/AVideo/assets/58882903/741040cd-eca7-4138-9c2a-511bc4c7407f)

**Comment by lachainestoplinky** [comment]
ello, I noticed the same thing, my thumbnail on the channel and no video.
and there is the Encoding bug just like you. for 2 or 3 days

for information, I tested the demo site and it works.

**Comment by DanielnetoDotCom** [comment]
Please check this

https://github.com/WWBN/AVideo/issues/8205#issuecomment-1644390551

**Comment by guymass** [comment]
That worked for me much thanks!
