### ISSUE TITLE
Encoders stopped working

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8316]
https://encoder3.wwbn.net/

![e1aa75b3-aa85-432c-8d5c-2ec3d3ef1384](https://github.com/WWBN/AVideo/assets/39392449/f3aa42ca-21b5-43ab-96fa-2125890c18a4)
![90e63400-ee8e-409d-854b-bb58a9525d6c](https://github.com/WWBN/AVideo/assets/39392449/44a9d379-8015-4296-a1b6-c4309fde6688)

**Comment by DanielnetoDotCom** [comment]
Submit the files again , if the queue is too big the public encoder delete the uploaded files.

To be honest I recommend you to use your private encoders

**Comment by JoshWho** [comment]
I am, Just letting you know

**Comment by JoshWho** [comment]
Any way I can priority my private encoders first before it tries yours?

**Comment by DanielnetoDotCom** [comment]
The problem is some times users send many videos at once and the servers does not have enough space to save and process them, so to avoid a server crash in need to delete them

**Comment by DanielnetoDotCom** [comment]
I may add a feature in the future to suspend uploads if the server is getting full

**Comment by JoshWho** [comment]
> I may add a feature in the future to suspend uploads if the server is getting full

That would be kewl.
