### ISSUE TITLE
Image sizes

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8318]
**Is your feature request related to a problem? Please describe.**
Ex. I'm **always** frustrated when I try to create category and profile images.

I end up fussing around to find an aspect ratio that actually works. 

**Describe the solution you'd like**
Put a label that says ("xxx by yyy pixels" - you want to put the optimal size for the image here).

This should go in two places:
   - the Category editor / dialog
   - the User's profile page

**Comment by DanielnetoDotCom** [comment]
Hi, sorry this is not clear, can you please provide some screenshots?

**Comment by walt93** [comment]
Like this, but with the right numbers. The optimum image size.

![Screen Shot 2023-08-14 at 4 56 37 PM](https://github.com/WWBN/AVideo/assets/11711050/432b4653-d57d-4993-a95d-7a3139b9e07a)

**Comment by walt93** [comment]
Here as well. 

![Screen Shot 2023-08-14 at 4 58 06 PM](https://github.com/WWBN/AVideo/assets/11711050/db5b1a41-d4ad-46c7-be4e-ed4c34dce86b)

**Comment by DanielnetoDotCom** [comment]
Got it, thanks

**Comment by DanielnetoDotCom** [comment]
Please check this update 

![image](https://github.com/WWBN/AVideo/assets/18009293/caebf221-3a51-4e21-9a43-23bfa2b71f38)
