### ISSUE TITLE
[Feature request] Category page layout improvement.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8319]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I fuss around for twenty minutes to create category images, and they do not display.

**Describe the solution you'd like**
Category images to display.

No category images:
![Screen Shot 2023-08-13 at 7 06 15 PM](https://github.com/WWBN/AVideo/assets/11711050/a1167001-6424-415b-a2b2-0e128862a9a8)

The category:

![Screen Shot 2023-08-13 at 7 06 48 PM](https://github.com/WWBN/AVideo/assets/11711050/eec18b4b-1729-4a73-8080-8f63a85ab049)
![Screen Shot 2023-08-13 at 7 06 57 PM](https://github.com/WWBN/AVideo/assets/11711050/870ab198-e828-4a9b-83dc-fbe8dd25ebb8)

(many such examples...)

**Comment by DanielnetoDotCom** [comment]
Is it the same?

https://github.com/WWBN/AVideo/issues/8318

**Comment by walt93** [comment]
https://github.com/WWBN/AVideo/issues/8318 - is different - just add a static text label with best image size where we upload images.

Latest is working. 

I think the page would look a lot better with a little bit of layout.

Notice how the bottom of the banner is faded/cutting off the bottom of the 'M' - is that because I have the image at the wrong size? (see #8318!)

Also notice how the poster is overlapping the banner? Perhaps the banner should sit above the poster, the and the title/description of the category can move into the rectangular space underneath.

![Screen Shot 2023-08-14 at 4 44 14 PM](https://github.com/WWBN/AVideo/assets/11711050/87ac0a4b-4ff1-4ee0-84a2-5388c5580d8b)

Maybe something like?

![Screen Shot 2023-08-14 at 4 50 16 PM](https://github.com/WWBN/AVideo/assets/11711050/5df96804-b979-41a3-989b-c0481ac43208)

**Comment by DanielnetoDotCom** [comment]
Not bad, but you can fine-tune the layout with a custom CSS

**Comment by walt93** [comment]
Daniel, which CSS? Where?  If I knew, I'd feed it to the AI and tell it how I want it modified. Tracking back from the HTML to the PHP that generated it is kinda rough…

Wouldn't you like to improve the platform so all users don't face ugly pages like this?

**Comment by DanielnetoDotCom** [comment]
I understand your concern regarding the CSS. The specific modifications largely depend on your desired outcome. For customization, You need to have some CSS knowledge as one typically uses browser tools to inspect the page and identify the relevant CSS elements and selectors. 

I recognize that everyone has unique aesthetic preferences, and what may seem less appealing to one might be perfectly fine for another. but you can always fine-tune it in your CSS
