### ISSUE TITLE
Metadata not deleted correctly

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8323]
@DanielnetoDotCom Description metadata form is not updated in the database after deleting the text leaving the box blank.
Check out the video:
https://github.com/WWBN/AVideo/assets/37880073/97809c0f-92d6-4eda-b61e-613257e8efa2

When I put any other text it works.

**Comment by DanielnetoDotCom** [comment]
Thanks, please check this update

**Comment by gbrn** [comment]
Danny, adjusted! Thanks
