### ISSUE TITLE
Translation not found - "... is required"

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8325]
@DanielnetoDotCom I can't find the translation for `... is required`

![image](https://github.com/WWBN/AVideo/assets/37880073/e2025bc2-4341-4f2f-9c57-e196285f9f46)

After this popup appears, there is no "X" to close, it is necessary to correct this.

**Comment by DanielnetoDotCom** [comment]
I am improving, JS translation, I may send updates regarding it soon

**Comment by gbrn** [comment]
Also check that there is no way to close this popup...

**Comment by DanielnetoDotCom** [comment]
I already sent updates regarding it.

**Comment by gbrn** [comment]
Ok, popup issue resolved. The translation has not yet been done.

![image](https://github.com/WWBN/AVideo/assets/37880073/3ff15938-617f-4e97-8b66-2c2d1e4febb1)

**Comment by DanielnetoDotCom** [comment]
Check this update
