### ISSUE TITLE
No email notifications on live stream start

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#8327]
This hasn't worked in a while - did you turn if off somewhere?

**Comment by DanielnetoDotCom** [comment]
Not really. 

is it not working only for live stream or is also not working on new videos and other notifications?

**Comment by 1tpg1** [comment]
Not working for live streams only.

**Comment by fakeologist** [comment]
Still not working any update?

**Comment by DanielnetoDotCom** [comment]
I think I found something, can you please test it?

**Comment by DanielnetoDotCom** [comment]
I am sorry for that again. 

I am sending you a new update that may work now.

**Comment by fakeologist** [comment]
Still not working .... I started live streaming from Fakeotube app.

**Comment by DanielnetoDotCom** [comment]
I am sorry, I found another issue. 

I just sent you another update. please keep me updated if that is working or not.

**Comment by fakeologist** [comment]
Still not working.

**Comment by DanielnetoDotCom** [comment]
I am so sorry, Now it is tested locally and it will work

BTW, your site is up to date now

**Comment by fakeologist** [comment]
Can you test again it didn't work last night.

**Comment by DanielnetoDotCom** [comment]
I could see the error, I am sending you updates now
