### ISSUE TITLE
local encoder

### ISSUE THREAD

**Issue by nofianadi** [WWBN/AVideo#8329]
Hi,
I just installed on my server  and I followed step on https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-22.x-for-AVideo-Platform-version-11.x-or-newer#install-streamer--encoder--live-nginx-rtmp. It said already install all features including the encoder. So, how I can use the encoder? or what url I should use?

Thanks

**Comment by milehighkaraoke** [comment]
your url/your encoder folder

**Comment by milehighkaraoke** [comment]
mine is https://mhktube.com/upload

**Comment by nofianadi** [comment]
There is AVideo-Encoder. So I need to create vhost that redirect to that folder, right?

**Comment by nofianadi** [comment]
so we need install it manually. thanks @milehighkaraoke
