### ISSUE TITLE
[Feature request] Categories/Playlists as first-class citizens in Gallery/Sort Section Order

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8331]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it is simply not possible to design the site the way I want.

**Describe the solution you'd like**
I'd like more flexibility in customizing the website's sections. At the moment, we can only display user videos chronologically or list them under general alphabetical categories. We need more control to achieve the design we have in mind. Here's a suggested solution:

1. To Categories, add a checkbox  "[X] Appears in Gallery".  This would make the Category appear as a draggable item in Gallery/Sort Sections Order.
2. To Playlists, we want the same thing. To make the Playlist appear as a draggable item in Gallery/Sort Sections Order.

The goals are to:

 - Decide where a specific video section is placed on the website.
 - Choose the content that goes into that section.
 - Determine the sequence/order of the content within that section.

Remember, this is about showcasing hand-picked videos, NOT videos chosen by an algorithm.

To give an example, I'd like to be able to design custom sections such as "Editors Choice", "Pick of the Week", or even "Gobbledygookhobshchinoble". Regardless of the title, I should have the ability to control every aspect of it – its name, its position on the site, and the order of videos displayed.

Our platform is almost perfect, but it lacks this essential feature.

Implementing this would greatly empower our 4,000 users by giving them the tools to design freely, without feeling restricted by our platform's current limitations.

**Describe alternatives you've considered**
Considering another platform that offers the flexibility we need.

**Comment by DanielnetoDotCom** [comment]
I agree, it may be added in the future
