### ISSUE TITLE
theme on gallery taking long time to load since last gitpull

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#8337]
@DanielnetoDotCom 
![Screenshot_20230818_005500_Firefox](https://github.com/WWBN/AVideo/assets/70327833/501dc4d4-ada4-4ed1-af72-517736c7a6f8)
![Screenshot_20230818_005505_Firefox](https://github.com/WWBN/AVideo/assets/70327833/2bc5207b-039d-4739-a652-0af0a55b3780)

**Comment by DanielnetoDotCom** [comment]
I am not sure what is causing this.
