### ISSUE TITLE
YPT Socket is connected but is blinking    latest gitpull 

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#8340]
https://mhktube.com/video/206/mobile-live-mhk-on-18-aug-23-08-32-35?channelName=MileHighKaraoke
@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
check your error log at the moment it blinks

**Comment by DanielnetoDotCom** [comment]
Please check this

**Comment by milehighkaraoke** [comment]
Thank you that fixed it

**Comment by milehighkaraoke** [comment]
It's doing it again after last git pull

**Comment by DanielnetoDotCom** [comment]
hummm, this is not happening to me. 

is there any specific page where it is happening?

did you cleat the cache?
