### ISSUE TITLE
Autoplay code, bottom login page

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8348]
@DanielnetoDotCom Danny, at the bottom of the login page, is leaking an Autoplay code... just started that in the last update.

`$(document).ready(function () {enableAutoPlay();});`

![image](https://github.com/WWBN/AVideo/assets/37880073/b0bbd111-b34a-4055-bedf-e94f71f93dfa)

![image](https://github.com/WWBN/AVideo/assets/37880073/d5ee72bd-2727-4aa9-ae9c-1dd83ae5153e)

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by gbrn** [comment]
ok Solved
