### ISSUE TITLE
[BUG] Gallery plug-in, displaying "Categories" disables sections below it.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8349]
**Describe the bug**
Displaying "Categories" in the Gallery plug-in is disabling all sections which should display below categories.

E.g. I just put categories above Date Added. Now my homepage does not display Date Added.

**To Reproduce**
1. Set up Categories to display before date added
![Screen Shot 2023-08-22 at 1 43 21 PM](https://github.com/WWBN/AVideo/assets/11711050/bbbef841-a684-44d0-8434-43d78f18ad73)

2. Clear First Page Cache, Clear Cache Directory, Generate Sitemap & reload the home page
3. Observe that nothing displays after the Categories section.

**Expected behavior**
To be able to see all sections below the Categories section.

Here is the home page. Observe that there are no videos in {date added} order:

![Screen Shot 2023-08-22 at 1 45 00 PM](https://github.com/WWBN/AVideo/assets/11711050/c7f4b947-2c3a-4820-b19b-f364908bac82)

**Comment by DanielnetoDotCom** [comment]
What happen if you clear the whole cache, not only the first page

**Comment by walt93** [comment]
Same

**Comment by DanielnetoDotCom** [comment]
I found the issue. thanks
