### ISSUE TITLE
Could we modernize the Article icon?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8351]
**Describe the solution you'd like**
I threw the AI at it. It came up with a couple cool ideas.
![UFaJy9hqXFN2ZFohjy5K--grid](https://github.com/WWBN/AVideo/assets/11711050/d2e92f25-ead8-45a1-82aa-8b5bd15971e9)
![bwfpGOoePth2Tx5tfjmJ--grid](https://github.com/WWBN/AVideo/assets/11711050/71fd31bd-7109-4346-96cc-afbb0ffea1d8)

**Comment by DanielnetoDotCom** [comment]
Agreed, can you suggest a nice png image that we can replace?

**Comment by walt93** [comment]
Anything stand out in this batch? 

Dall-E:
![Screen Shot 2023-08-23 at 12 40 58 PM](https://github.com/WWBN/AVideo/assets/11711050/48ec009e-631c-467e-bab7-36251fcda459)
Stable Diffusion XL:
![Screen Shot 2023-08-23 at 12 43 26 PM](https://github.com/WWBN/AVideo/assets/11711050/ac3c361a-f9bb-4be0-a382-dc9fdb3d50bd)
![Screen Shot 2023-08-23 at 12 45 11 PM](https://github.com/WWBN/AVideo/assets/11711050/b106b9a8-ef3e-49de-8840-758f57c4f32a)
![Screen Shot 2023-08-23 at 12 46 29 PM](https://github.com/WWBN/AVideo/assets/11711050/c6e1930d-9309-4883-8951-4d5d5909baa6)
![Screen Shot 2023-08-23 at 12 52 36 PM](https://github.com/WWBN/AVideo/assets/11711050/7aced177-727f-437d-ab2d-404aa7a0efd1)
