### ISSUE TITLE
Categories page sorts by reverse date order, the category page itself sorts in proper oder

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8353]
**Describe the bug**
When we are looking at the a category page with sub-categories, the sub-category videos display in most-recent first order.
When we click through to the sub-category page (and it has no sub-categories), the videos display in oldest first order

**To Reproduce**
1. Go to https://conspyre.tv/cat/punishdem1776
2. Observe that "Agenda 2030" and "Corporation of America" display in most-recent first
3. Click on "Agenda 2030" (https://conspyre.tv/cat/agenda-2030)
4. Observe the videos display in oldest first order
5. Go back and click on "Corporation of America" (https://conspyre.tv/cat/corporation-of-america)
6. Observe the videosdisplay in oldest first order

**Expected behavior**
Both to display in the same order.

**Screenshots**
Here is https://conspyre.tv/cat/punishdem1776
![Screen Shot 2023-08-22 at 10 46 09 PM](https://github.com/WWBN/AVideo/assets/11711050/00a020ec-9e03-4502-882e-30dd33c3df16)

And here is https://conspyre.tv/cat/agenda-2030
![Screen Shot 2023-08-22 at 10 47 06 PM](https://github.com/WWBN/AVideo/assets/11711050/14ab083b-c764-405b-9b2e-ec49ddc97bbf)

And here is https://conspyre.tv/cat/corporation-of-america
![Screen Shot 2023-08-22 at 10 47 20 PM](https://github.com/WWBN/AVideo/assets/11711050/335dc831-bad5-4264-842d-5548108cb568)

**Comment by DanielnetoDotCom** [comment]
I have no idea, I am trying to reproduce it here and I couldn't, 

can you please reproduce it on demo site?

**Comment by walt93** [comment]
This seems related. https://github.com/WWBN/AVideo/issues/8358

To to reproduce it on the demosite... I can export my database and get it to you, probably 0.6TB, how do you want it?

**Comment by DanielnetoDotCom** [comment]
I do not think the error is in the DB, the error may be in the code or some configuration. 

I need to be able to reproduce so I can fix.

**Comment by walt93** [comment]
Is there a way to export my config and import onto the demosite? I'm not really sure what config to change TBH.

**Comment by DanielnetoDotCom** [comment]
Sorry, currently there is no way to do it.
