### ISSUE TITLE
[Feature request] Faster page load (≈1 minute is really pushing usability)

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8354]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it takes 45-60 seconds to load the site.

**Describe the solution you'd like**
To do some analysis of the database calls. There are always so many messages that the SQL transactions are slow, and there are so many SQL transactions to load a page, that it seems this is where to look.

**Comment by DanielnetoDotCom** [comment]
I agree that some times is slow, but I am doing my best to improve it. 

for now, you can try this

https://github.com/WWBN/AVideo/wiki/Speed-up-your-page#optimize-first-page-video-display

**Comment by walt93** [comment]
It's the initial connection that's brutal. After you've loaded the first page, your session seems to go smoother.

**Comment by barrunning** [comment]
I was just about to ask the same question. 
safari seems to be the worse, then chrome with edge almost loading instantly.
![IMG_9729](https://github.com/WWBN/AVideo/assets/58601786/87ca0db2-9b1b-4720-9077-82d65a2ed9f6)
![IMG_9730](https://github.com/WWBN/AVideo/assets/58601786/7ccfd25f-0fe4-4ab7-b22f-a48d1a3baa9a)
![IMG_9731](https://github.com/WWBN/AVideo/assets/58601786/2ad0b4c2-97fd-4f9d-8edc-55d0c1fdccb2)

**Comment by walt93** [comment]
Yeah Safari is generally the worst all around browser.  engineers expect the spec to conform to them. We need to find someone that lives and breathes SQL optimizations to analyze this thing.
