### ISSUE TITLE
[Encoder] lets USER select release date. [Encoder] lets USER select created date. Neither should be available.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8355]
**Describe the bug**
It seems that the user is presented with the option to select the created date. But when they select a created date, it doesn't work. The user should not be presented with this option.

The same goes for the release date option. The User should not have this option at all.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot where the user can see the created date option?

**Comment by walt93** [comment]
I am logged into the encoder from a regular user account. I tried setting the created date here, and it did not work. And Daniel, literally none of us want any of our users to use "Release date".  Both of these must be for admins only.


![Screen Shot 2023-08-24 at 12 44 00 PM](https://github.com/WWBN/AVideo/assets/11711050/b8230d5e-ea0b-4008-a620-f93c7cee7b10)

**Comment by DanielnetoDotCom** [comment]
Hi, now the regular user should view the release date. 

also, there is an option to disable the release date

![image](https://github.com/WWBN/AVideo/assets/18009293/d072ee0a-83b1-40e6-bdb3-4fa8c588e435)
