### ISSUE TITLE
Two bugs on the videos list page related to the [DOWNLOAD] control

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8360]
**Describe the bug**
1. When the [ DOWNLOAD ] button appears on the videos page, the [...]/[+Add to] buttons cannot be pressed
2. All of the videos here are the same, they are all downloadable, and can be downloaded from the videos page. Only one video shows the [ DOWNLOAD ] button here

**To Reproduce**
1. Go to ['...'](https://conspyre.tv/cat/jake-angeli-america-s-shaman)
2. Scroll down to Interviews
6. See errors

**Expected behavior**
The [...][+Add to] buttons to be accessible when the [ DOWNLOAD ] button is rendered
The [ DOWNLOAD ] button to be rendered consistently

**Screenshots**
![Screen Shot 2023-08-24 at 5 53 00 PM](https://github.com/WWBN/AVideo/assets/11711050/bca4ff18-851d-4509-826f-68ce688253ee)

**Comment by DanielnetoDotCom** [comment]
can you please share the link to this page?

**Comment by DanielnetoDotCom** [comment]
I guess I found the issue
