### ISSUE TITLE
subs not play index page 

### ISSUE THREAD

**Issue by junflix** [WWBN/AVideo#8373]
hello any idea why not play subs index page https://prnt.sc/q2LmhvlQnpz3 

but in panel video page it works fine subs  https://prnt.sc/bvOI2qO2wOxr

**Comment by DanielnetoDotCom** [comment]
If you have only 1 subtitle you will see the CC button, if you have more then one you will see a menu

**Comment by junflix** [comment]
yes i have only one and i see cc button after press button not show subs ..but video panel subs works normal 
https://prnt.sc/pXh2sIIF1Ap2

**Comment by DanielnetoDotCom** [comment]
can you please send the video link to me so I can test?

**Comment by junflix** [comment]
fixed thank you for the support need to upload 2 subs to works

**Comment by DanielnetoDotCom** [comment]
Only one should work, I will lookt at it next week, and if I find something I will send updates to the plugin.

**Comment by junflix** [comment]
ok tthank youuu

**Comment by junflix** [comment]
I would like to let you know that when I press this  VR360 Subtitles play normally only when I press this in case you upload only one subtitle...
https://prnt.sc/BOSnBhkcILEu
So that way you know exactly where the problem is thank you very much

**Comment by DanielnetoDotCom** [comment]
I do not think subtitles will work good with VR360 

I recommend you to disable VR360 , unless you really need this feature.
