### ISSUE TITLE
After trasfer not play video

### ISSUE THREAD

**Issue by junflix** [WWBN/AVideo#8375]
hello i have one problem ..after Encoder video HLS everything works fine from local server ..but if transfer to storage server not play video
https://prnt.sc/JKfu_Dioowy0 
any idea for this? thanks

(ALL VIDEOS AFTER ENCODER MP4 IT WORKS NORMAL STORAGE SERVER)

**Comment by DanielnetoDotCom** [comment]
What type of storage are you using?

For HLS I strongly recommend the CDN storage

https://github.com/WWBN/AVideo/wiki/CDN-Storage
