### ISSUE TITLE
While changing something in customize advanced, the site can no longer be loaded.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8377]
**Describe the question**
I believe that I only changed the customizeAdvanced->VideoCDN URL, specifically, I added one.

After that, the site cannot be loaded. 
![Screen Shot 2023-09-03 at 7 35 43 PM](https://github.com/WWBN/AVideo/assets/11711050/cf8bb3cb-c700-4bee-aa28-ded5f925785d)

I must have typed something into a field of customizeAdvanced without realizing it, hit save, and this is the result.

This site has backups issued with the Backup plugin. 

How might I restore it in-place without using the GUI?

**Comment by DanielnetoDotCom** [comment]
you can reset the plugin configuration here

````bash
cd /var/www/html/AVideo/install
````

than

```bash
# php resetPlugins.php 
1 - Reset all plugins Parameters
2 - Reset CustomizeUser Plugin Parameters only
3 - Reset all plugins (Will also inactivate the plugins)
Choose an option: 1
```
