### ISSUE TITLE
Broken Missing files

### ISSUE THREAD

**Issue by junflix** [WWBN/AVideo#8385]
https://prnt.sc/Nx1_dHMmTiBH

hello the last 2 days i have this problem and files video stop to working from local server ..any idea how to fix this?  error log i not have for this 

IN THE LOCAL  FOLDER PAGE FILES VIDEOS THEY EXIST

**Comment by DanielnetoDotCom** [comment]
You need to clear your cache and check your logs

https://github.com/WWBN/AVideo/wiki/AVideo:-Understanding-the-%22Broken-Missing-Files%22-Status

**Comment by junflix** [comment]
thanks fixed
