### ISSUE TITLE
Network Encoders going offline

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8386]
This is not a bug as far as I can see, however my Network encoders are constantly switching status from online to offline and back forth and recently some live streams will not encode the stream.  I would like to know for example if one of my encoders is a local encoder under the AVideo/Encoder directory and this is registered also as a network encoder. Now the ping indicates quite a large ping because the actual server sunning the NetworkEncoders script is a separat server on DigitalOcean. My question is, why would that encoder go offline when it is located on the same server of the site itself and why would the ping be that long? Isn't there a way to distinguish between the local encoder end other encoders located on other server?

![Screenshot 5783-12-19 at 11 25 49](https://github.com/WWBN/AVideo/assets/58882903/e84afcf7-af6c-44e9-bdf6-18b819d0ae43)

I also noticed that script hasn't been updated for a long time, maybe it needs to be revised?

And I still cannot control the recommended encoder or selected default encoder from my list, that would be a great option to be able to set which one is the default from the list.

**Comment by guymass** [comment]
Also my encoders don't encode anymore, I have the following error in my PHP:
![Screenshot 5783-12-20 at 12 32 25](https://github.com/WWBN/AVideo/assets/58882903/873c36d4-12b7-4b70-ab3b-c4ecc8a21759)

![Screenshot 5783-12-20 at 11 38 18](https://github.com/WWBN/AVideo/assets/58882903/9816f70e-be06-4ead-95f7-8dd5e1aa27d6)

![Screenshot 5783-12-20 at 12 29 06](https://github.com/WWBN/AVideo/assets/58882903/53ed0bd0-5994-4eac-9569-6ab752932638)
![Screenshot 5783-12-20 at 12 30 02](https://github.com/WWBN/AVideo/assets/58882903/9f0e16ed-cc34-4579-bcaa-d7ea1ce07cee)

**Comment by DanielnetoDotCom** [comment]
You need to copy and paste the php erros properly. I cannot read them

**Comment by guymass** [comment]
in the NetworkEncoder error log I se the following constantly repeating:

[Tue Sep 19 21:22:20.262958 2023] [proxy_fcgi:error] [pid 2821670] [client 127.0.0.1:58390] AH01071: Got error 'PHP message: PING ==> fileAge = 34 AND lifetimeSeconds = 30', referer: https://encoder.alive528.com/?webSiteRootURL=https%3A%2F%2Falive528.com%2F&user=eitanwa&pass=_user_hash_V3FxQi9HMEg1QW1sWmE4ZnQ2ZDE1cFdDRUFsNmluZXNpcmxCb0Nua1J1VUZlekhUUUdMY051V3l1cDJLRWJ5Q21Xa01XSjRxelFQa3ExWkZaOWFJeEE9PQ%3D%3D&encodedPass=1&justLogin=1&PHPSESSID=34vimbbiel9740f5seni10ujlf
[Tue Sep 19 21:22:52.620104 2023] [proxy_fcgi:error] [pid 2825238] [client 127.0.0.1:54092] AH01071: Got error 'PHP message: PING ==> fileAge = 32 AND lifetimeSeconds = 30', referer: https://encoder.alive528.com/?webSiteRootURL=https%3A%2F%2Falive528.com%2F&user=eitanwa&pass=_user_hash_V3FxQi9HMEg1QW1sWmE4ZnQ2ZDE1cFdDRUFsNmluZXNpcmxCb0Nua1J1VUZlekhUUUdMY051V3l1cDJLRWJ5Q21Xa01XSjRxelFQa3ExWkZaOWFJeEE9PQ%3D%3D&encodedPass=1&justLogin=1&PHPSESSID=34vimbbiel9740f5seni10ujlf
[Tue Sep 19 21:22:52.637173 2023] [proxy_fcgi:error] [pid 2821669] [client 127.0.0.1:54094] AH01071: Got error 'PHP message: PING ==> fileAge = 32 AND lifetimeSeconds = 30', referer: https://encoder.alive528.com/?webSiteRootURL=https%3A%2F%2Falive528.com%2F&user=eitanwa&pass=_user_hash_V3FxQi9HMEg1QW1sWmE4ZnQ2ZDE1cFdDRUFsNmluZXNpcmxCb0Nua1J1VUZlekhUUUdMY051V3l1cDJLRWJ5Q21Xa01XSjRxelFQa3ExWkZaOWFJeEE9PQ%3D%3D&encodedPass=1&justLogin=1&PHPSESSID=34vimbbiel9740f5seni10ujlf
[Tue Sep 19 23:02:43.918429 2023] [proxy_fcgi:error] [pid 2925574] [client 43.129.97.125:54820] AH01071: Got error 'Primary script unknown'
[Tue Sep 19 23:02:45.146573 2023] [proxy_fcgi:error] [pid 2936917] [client 43.129.97.125:55720] AH01071: Got error 'Primary script unknown'

**Comment by guymass** [comment]
again after a live stream although my live stream and encoding process was just fine, I see these repeating errors in the NetworkEncoder log:

![Screenshot 5784-01-06 at 21 22 59](https://github.com/WWBN/AVideo/assets/58882903/a7ca5c55-6e94-4afb-8196-583f0c55611a)


My both encoders get stuck at times idk why, but it never shows a constant  "encoder online" status (green).
Some uploads or URL downloads get stuck for hours not completing. 
The following few screen shots will show some indication to what I see:

![Screenshot 5784-01-06 at 21 26 56](https://github.com/WWBN/AVideo/assets/58882903/e5d9986b-b470-4c77-b092-e504e1c8bcad)
![Screenshot 5784-01-06 at 21 26 47](https://github.com/WWBN/AVideo/assets/58882903/56e82fff-bd27-4bc9-882b-a3adcb8a8a65)
![Screenshot 5784-01-06 at 21 26 20](https://github.com/WWBN/AVideo/assets/58882903/e87ed383-e03e-4c8e-865e-680589b2bae7)

**Comment by guymass** [comment]
Now their both off line again:
![Screenshot 5784-01-06 at 21 29 09](https://github.com/WWBN/AVideo/assets/58882903/df807700-330b-4d5f-b0ef-dbe0a803fea2)

**Comment by DanielnetoDotCom** [comment]
clearly network issues

**Comment by guymass** [comment]
Can you explain to me why the encoders go off line? especially the alive528.com encoder which is on the same server as the main site. I have my network encoder server sitting at Digital Ocean, is that why the ping is so slow on the encoders web page? because my direct ping to my remote encoder is much faster then the one show on the web page as in the following screen shots:
![Screenshot 5784-01-20 at 0 54 08](https://github.com/WWBN/AVideo/assets/58882903/f8d0a8e7-0074-43e2-b004-90ef60a3155c)

These screen shots were taken about 20 sec apart and this On/Off cycle keeps going all the time, is this normal?

![Screenshot 5784-01-20 at 0 57 51](https://github.com/WWBN/AVideo/assets/58882903/42669c5f-1f8a-47e1-8a9b-ed9ae07cb898)

![Screenshot 5784-01-20 at 0 58 45](https://github.com/WWBN/AVideo/assets/58882903/f4d4a4e8-6438-439c-95ec-f461dab7fa67)

**Comment by guymass** [comment]
Yes you are correct I am going to change my network encoders server, will be closing this post. I do recommend if someone is using network encoders to select a server with the lowest ping possible to all encoders including to the main site.

**Comment by guymass** [comment]
Yes you are correct I am going to change my network encoders server, will be closing this post. I do recommend if someone is using network encoders to select a server with the lowest ping possible to all encoders including to the main site.
