### ISSUE TITLE
Translation not found - Favorites

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8394]
@DanielnetoDotCom 

I can't find this translation in the translation file. There is only _Favorite_ and not _Favorites_.

![image](https://github.com/WWBN/AVideo/assets/37880073/dd4b06ab-1c47-431b-a936-86a1a25244e6)

Danny teaches me here... to add a non-existing translation line, just add a new line in the `/locale/pt_BR.php` ? Or do you have to add some reference in the source file?

This is correct:
![image](https://github.com/WWBN/AVideo/assets/37880073/fbdd42fc-5e5a-427c-ba1e-1d69e62e2c76)

**Comment by DanielnetoDotCom** [comment]
Just a new line :)

**Comment by gbrn** [comment]
OK I learned how to do it. Thanks.
