### ISSUE TITLE
Layout - Strange image for USER.PNG

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8396]
@DanielnetoDotCom Danny, changing this image isn't interesting, it's contrasting too much with the dark layout. The previous silhouette that was black and white was much better. I think it's better to leave the colors neutral and without effects.

Now it has many colors and a "question mark" has been added that has nothing to do with the image. The user may simply never want to change it and not put any images. In this case the symbol looks like it has an error.

![image](https://github.com/WWBN/AVideo/assets/37880073/fb3233d4-c55e-4f37-b4a2-c3e9beadd9b0)
![image](https://github.com/WWBN/AVideo/assets/37880073/3d99cb99-7b09-4bf7-87d7-1c47ad181202)
![image](https://github.com/WWBN/AVideo/assets/37880073/93d06c06-9be5-48e8-8ae6-726c74684bba)

https://github.com/WWBN/AVideo/blob/master/view/img/placeholders/user.png

**Comment by DanielnetoDotCom** [comment]
You can change it with the Customize plugin

![chrome-capture-2023-8-7](https://github.com/WWBN/AVideo/assets/18009293/ef5dda86-88dd-4cfe-9669-d0f593a381d3)

**Comment by walt93** [comment]
Where is the documentation? Where are the release notes? How do we know when cool new features are developed other than **reading other peoples bug reports?**

**Comment by gbrn** [comment]
@walt93 I know you've been using the platform for a long time, so have I. And I've been insistently demanding changelog change and modification documentation #8170 .... but I was completely ignored.

I understand the premises of a project inside github.

I try to elevate the project to a more professional level, but I never succeed, due to the relentless changes without any control. I don't have the confidence to raise the level of a project. Unfortunately.

**Comment by DanielnetoDotCom** [comment]
Thank you for your feedback and concerns regarding the documentation and release notes. I truly value your commitment to the platform.

Currently, I do not have a dedicated section or system in place to detail what is new in the updates. I acknowledge the importance of having a changelog and release notes, and I understand how crucial they are for the users and contributors like you. Please bear with me as I work on establishing a more systematic approach for this.

Your patience and continued support mean a lot. Please rest assured that your concerns are heard and will be addressed.

**Comment by gbrn** [comment]
@DanielnetoDotCom Danny, you can be sure that me and all the contributors to the AVIDEO project are here to make this system better every day. Your idea is brilliant and we want it to keep getting better every day. Many of us dedicate a lot of our time to this.
Sometimes we get frustrated, because some changes don't go as we imagined. I understand that these are the consequences of an Open Source project.
I think that if the changes were more discussed, it would be more relevant for the entire community. That way we could give our opinion.
You can count on my support. Let's go!
