### ISSUE TITLE
How could I turn on Ad Server but *only* do so for specific videos.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8398]
**Describe the question**
I want to run ads over 4 specific videos only. How could I achieve this?

Specifically, I have these videos de-activated so they don't show up on the site, they are being used for embedded content.

**Comment by DanielnetoDotCom** [comment]
We do not have it per video, but maybe you can set it up per channel

and all the videos that you want to have ads, put in a different channel

![image](https://github.com/WWBN/AVideo/assets/18009293/1003b639-039d-4812-bb3f-5da27f636e49)

**Comment by walt93** [comment]
Channel is what, per category? per user?
Then, what, I have to turn off ads on **all** categories/users?

**Comment by DanielnetoDotCom** [comment]
Channel is per user

Yes, by default all the channels show ads, unless you say to not show
