### ISSUE TITLE
[MOTD] Static message

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8401]
**Is your feature request related to a problem? Please describe.**
The original use case for the MOTD plug-in would be a static message, e.g. set the MOTD once, and users see it once every day - a message we want them to see at spaced intervals.

**Describe the solution you'd like**
A) A static MOTD which displays if no "dynamic MOTD" is defined for the day; if a "dynamic MOTD" is defined, it overrides the static.

ALTERNATIVE: 
B) Each day, if no MOTD is defined, it should use the _next most recent_ MOTD. 

**Also**… the MOTD should always play once per calendar day (set the cookie duration to expire at midnight the day it fires).

**Comment by DanielnetoDotCom** [comment]
Sorry but it is not clear to me, if you can provide some screenshots:

1. **Dynamic vs. Static MOTD**: Can you explain the difference between the "dynamic MOTD" and the "static MOTD" in your context?

2. **Frequency of MOTD**: You mentioned the MOTD should play once per calendar day. Does this mean you'd want a new message every day or is it acceptable to have the same message for multiple days until a new one is set?

3. **Next Most Recent MOTD**: You've mentioned that if no MOTD is defined for a particular day, it should use the "next most recent MOTD". I'm curious about the use case for this. If the MOTD plays once per calendar day, why would we need to pull up the next most recent MOTD?

4. **Multiple MOTDs per Day**: Do you envision scenarios where you'd want to display more than one MOTD within the same day?

**Comment by walt93** [comment]
1. Current implementation I am calling "Dynamic", I guess that is the wrong term - we now have a table of messages to fire on specific dates.

Static = there is just one MOTD. It plays once per day, assuming the user is on the site daily. So it should fire and set a cookie to expire at midnight.

2. I want to have the same MOTD every day, until a new MOTD replaces it.

3. Yes, another way to say this is, a MOTD in the database for a specific date, persists until replaced with a new one.

4. No. Just a single "Message Of The Day".

I think it IMO better to go with (3) than (1), no new feature needed just make the MOTD persistent until a new one comes in.

**Comment by walt93** [comment]
User #3108

**Comment by DanielnetoDotCom** [comment]
try to download it now
