### ISSUE TITLE
How might I manually edit the database to control the order of Programs in the Programs tab of the Users page

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8403]
**Describe the question**
I'm setting up a user with a specific set of programs. I need them to appear in order (e.g. "101 - Introduction", "102 - Something", "103..."), but I didn't create them in the order I want them.

What can I edit in the database to get them to render in the order I want?

**Screenshots**
![Screen Shot 2023-09-08 at 11 29 11 PM](https://github.com/WWBN/AVideo/assets/11711050/6ecafcb6-fb9c-4c4b-90cb-9dda8c950a79)

**Comment by DanielnetoDotCom** [comment]
Sorry, there is no specific order in how they are displayed. 

at least not yet;

**Comment by DanielnetoDotCom** [comment]
Their response from them was this

```
[11-Sep-2023 11:57:47 UTC] /usr/local/bin/yt-dlp   --no-check-certificate --force-ipv4 --no-playlist -k -o /tmp/youtubeDlRO5P0S.mp4 'https://www.youtube.com/watch?v=kYkXkuvFb7E'
[youtube] Extracting URL: https://www.youtube.com/watch?v=kYkXkuvFb7E
[youtube] kYkXkuvFb7E: Downloading webpage
[youtube] kYkXkuvFb7E: Downloading android player API JSON
[info] kYkXkuvFb7E: Downloading 1 format(s): 247+251
ERROR: unable to download video data: HTTP Error 403: Forbidden
root@ns525371:~# /usr/local/bin/yt-dlp   --no-check-certificate --force-ipv4 --no-playlist -k -o /tmp/youtubeDlRO5P0S.mp4 'https://www.youtube.com/watch?v=naopp_KF678'
[youtube] Extracting URL: https://www.youtube.com/watch?v=naopp_KF678
[youtube] naopp_KF678: Downloading webpage
[youtube] naopp_KF678: Downloading android player API JSON
[info] naopp_KF678: Downloading 1 format(s): 248+251
```

but after updating the yt-dlp all seems to be working fine now

`
pip install --upgrade yt-dlp
`
I also added the update to your corn tab to run it daily so it may work with no problem
