### ISSUE TITLE
Two YouTube videos won't encode / upload

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#8405]
Any idea why?
https://youtu.be/naopp_KF678?si=mHYJ2_cmwECCibpx
https://youtu.be/kYkXkuvFb7E?si=MHDiwNyPH2GVHhkX

**Comment by walt93** [comment]
Youtube downloads seem like they fail much more often than they work. Mostly I get this:

![Screen Shot 2023-09-09 at 3 10 46 PM](https://github.com/WWBN/AVideo/assets/11711050/91b0ffff-062e-4777-996a-677d5a64f312)

**Comment by fakeologist** [comment]
What is yt-dlp? I like the encoder because it includes the source in the description.

**Comment by walt93** [comment]
Tech stack for the encoder is it uses the yt-dlp script to download videos, and ffmpeg to encode
For me, it's always failing to download with this "max tries reached" error & only for YouTube.

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/issues/8403#issuecomment-1713742747

**Comment by fakeologist** [comment]
> https://github.com/WWBN/AVideo/issues/8403#issuecomment-1713742747

Was my cron updated?

**Comment by DanielnetoDotCom** [comment]
Now it is
