### ISSUE TITLE
subs not play

### ISSUE THREAD

**Issue by junflix** [WWBN/AVideo#8406]
hello i have put link video  and subs not working any idea for this ?  ...if encoder video subs works fine ...

(https://mydomain/movies/xxx/xxxxxx.mp4)    this link it works but not play subs

https://prnt.sc/diwiIOcMD0CX

**Comment by junflix** [comment]
hello any news?

**Comment by DanielnetoDotCom** [comment]
Subtitles are designed to work only on videos you self-host. not embed or video links

**Comment by junflix** [comment]
thanks
