### ISSUE TITLE
I'm getting this same error, how can I solve it, I don't know

### ISSUE THREAD

**Issue by GamerAcchin1234** [WWBN/AVideo#8407]
Under Maintenance is showing

**Comment by GamerAcchin1234** [comment]
I don't know how to solve

**Comment by GreenDragonTavern** [comment]
Have you verified database connection?

**Comment by GamerAcchin1234** [comment]
where to check

**Comment by GamerAcchin1234** [comment]
no

**Comment by GreenDragonTavern** [comment]
Videos directory, configuration.php has database parameters.

**Comment by GamerAcchin1234** [comment]
ok

**Comment by GamerAcchin1234** [comment]
which line should I change

**Comment by GreenDragonTavern** [comment]
Verify you can connect to database server prior to changing anything. Below are parameters, in configuration.php
```
$mysqlHost = 'YOUR HOST NAME or IP Address';
$mysqlPort = '3306';
$mysqlUser = 'Database User Name';
$mysqlPass = 'Database User Password';
$mysqlDatabase = 'Database Name';
```

**Comment by GamerAcchin1234** [comment]
and then

**Comment by GamerAcchin1234** [comment]
that's it
$mysqlHost = 'localhost';
$mysqlPort = '3306';
$mysqlUser = 'Kidtube';
$mysqlPass = 'GamerAcchin@0608';
$mysqlDatabase = 'kid_tube';

**Comment by GamerAcchin1234** [comment]
sorry

**Comment by GreenDragonTavern** [comment]
Can you login using command line? mysql -u Kidtube -p

**Comment by GamerAcchin1234** [comment]
ok
 but how tutorial

**Comment by GreenDragonTavern** [comment]
Shell into your server, the command line is: ```mysql -u Kidtube -p```

It will prompt for password, type it in, you'll know whether it connects or fails after entering in password.

**Comment by GamerAcchin1234** [comment]
ok

**Comment by GamerAcchin1234** [comment]
what do I do
![image](https://github.com/WWBN/AVideo/assets/144597625/83974bbf-5ad9-4cd6-b452-e484c10e7651)

**Comment by GamerAcchin1234** [comment]
responds

**Comment by GreenDragonTavern** [comment]
> responds

Huh?

**Comment by GreenDragonTavern** [comment]
Have you tried logging into database server as root and list all users?

**Comment by GamerAcchin1234** [comment]
yes

**Comment by GamerAcchin1234** [comment]
no

**Comment by GamerAcchin1234** [comment]
![image](https://github.com/WWBN/AVideo/assets/144597625/234a6d89-3c3e-497f-9034-e1a3d1233bd5)

**Comment by GamerAcchin1234** [comment]
DanielNeto

**Comment by GamerAcchin1234** [comment]
I'm getting this same error, how can I solve it, I don't know

**Comment by DanielnetoDotCom** [comment]
Your PHP installation is not correct. you are missing the php-gd


```
sudo apt update
sudo apt install php-gd
sudo systemctl restart apache2
```

**Comment by GamerAcchin1234** [comment]
ok

**Comment by GamerAcchin1234** [comment]
in the shell

**Comment by GamerAcchin1234** [comment]
Look Here 
![image](https://github.com/WWBN/AVideo/assets/144597625/c3b81218-ea75-4be9-af1c-a108b56a798f)

**Comment by DanielnetoDotCom** [comment]
I've noticed that you're using Windows, not Ubuntu. We primarily support Ubuntu. While our software might run on Windows, setting it up and configuring it on that platform is up to you.

**Comment by GamerAcchin1234** [comment]
ok

**Comment by GamerAcchin1234** [comment]
but how do I use other games and apps

**Comment by GamerAcchin1234** [comment]
but as I use other games and apps it doesn't work

**Comment by GamerAcchin1234** [comment]
I will be able to run Windows
