### ISSUE TITLE
After a git pull (today tue sep-12), Twitter tags are not showing up at all.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8414]
**Describe the bug**
I'd like to be able to share links to my site from Twitter. However, most of the time we get very poor results.

**To Reproduce**
Share a link to something on Twitter.

Observe that you get no image, some placeholder image, the sites favicon, anything but an actual usable image that has something to do with your post.

**Expected behavior**
AVideo platform to use the correct image for the post. If it is a post with a video, to use the videos image. If it is a post from a category, to use the categories image. If it is a post to a users page, to use the users image.

THE POINT OF POSTING THINGS TO TWITTER IS TO GET ENGAGEMENT. WHEN OUR POSTS DO NOT HAVE IMAGES -ENGAGEMENT GOES DOWN 90-95%. THERE IS ONE DAY PER YEAR TO POST THE FOLLOWING, AND IT'S ALL SHITE:

**Screenshots**
These videos all have images:
![Screen Shot 2023-09-11 at 1 11 20 PM](https://github.com/WWBN/AVideo/assets/11711050/359a50f8-725b-47df-977d-adf269586bbd)

![Screen Shot 2023-09-11 at 1 11 44 PM](https://github.com/WWBN/AVideo/assets/11711050/0baafbe2-81a2-4366-8527-5e3c57fe31e1)

![Screen Shot 2023-09-11 at 1 11 52 PM](https://github.com/WWBN/AVideo/assets/11711050/e67d6bb5-7fa7-44fa-a535-0db37f7c0338)

![Screen Shot 2023-09-11 at 1 12 02 PM](https://github.com/WWBN/AVideo/assets/11711050/808367ff-f00e-40a2-9c2e-62addddb4141)

**Comment by DanielnetoDotCom** [comment]
I am not sure what happened, also this image does not exist anymore. we have updated it. 

I guess your AVideo is outdated.

**Comment by walt93** [comment]
I updated it less than two weeks ago. 

I updated another site last week and taking a git pull blew away enough configuration that the site is completely !@#$ing dead, and I haven't had a chance to resurrect it.

I'm somewhat paranoid of taking a pull until I have some confirmation that it isn't going to nuke the site.
