### ISSUE TITLE
Twitter/OpenGraph tags fail more often than they work. Only on Twitter itself, it seems. Validators show no issue.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8424]
**Describe the bug**
Daniel, do you remember my telling you that Twitter tags are a real b**ch to get right? I did a project a few years ago and it took what felt like heroic effort to get Twitter tags working reliably. Now that we can use the platform again, it's time to get focused on making this work, this brain damaged platform is how we do marketing for our video sites.

After upgrading mainsite and all plugins yesterday, I am still finding that OpenGraph/Twitter tags do not work reliably.

Twitter: 2 out of 7 posts are showing an image.
![Screen Shot 2023-09-14 at 1 37 56 PM](https://github.com/WWBN/AVideo/assets/11711050/8832dc1d-0261-4fb0-9c04-e8c3b91ed817)

Truth: 7 out of 7 (the same) posts are all showing an image.
![Screen Shot 2023-09-14 at 1 40 50 PM](https://github.com/WWBN/AVideo/assets/11711050/35948a61-ba7c-4090-b5df-9657c5fa94ed)

Twitter Card Validator isn't showing any errors nor is opengraph.xyz. But they're still broken, something Twitter doesn't like, the order they appear in, how far down the page the tags are, SOMETHING (IMO shitty code at X) is making it fail.

**Comment by DanielnetoDotCom** [comment]
Check your Apache access logs to see if at least Twitter is trying to get your images when you place a URL

**Comment by walt93** [comment]
I've got too much traffic on the site, how am I going to even find that? Have you tried this recently Daniel? When you paste the URL in to the tweet composer, it should bring up the OG tags immediately. I find that I have to cut/paste/cut/paste/cut/paste multiple times to get it to display the metadata - then - in the timeline - it probably doesn't show it.

**Comment by DanielnetoDotCom** [comment]
that is what I got in the first try

![image](https://github.com/WWBN/AVideo/assets/18009293/885d1b94-491e-4180-a981-2a227aa52908)
![chrome-capture-2023-8-14](https://github.com/WWBN/AVideo/assets/18009293/c26b3bad-b59d-4983-bf5c-54ea1e77beba)

**Comment by DanielnetoDotCom** [comment]
try something from here  https://tutorials.avideo.com/

**Comment by walt93** [comment]
Working great from demosite. Try posting something from here https://conspyre.tv. I wonder if my site got onto one of their various censorship mechanisms.

**Comment by walt93** [comment]
Daniel, I remember also running into this problem a long time ago, before I got my accounts (plural) banned from Twitter, I had to post / delete / post / delete until I got a post onto Twitter with the OG tags...

**Comment by DanielnetoDotCom** [comment]
Do you have the git pull from this week?

there were some image updates/fixes this week
