### ISSUE TITLE
Correct permissions for /var/www/html/scripts/youtube-cookies.txt?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8425]
**Describe the question**
I have six encoders running on two machines. ONE of them was giving a permissions error. 

![Screen Shot 2023-09-14 at 3 57 43 PM](https://github.com/WWBN/AVideo/assets/11711050/f5405904-41a7-4b3e-9f31-fbb9f3eb8e6c)

While trying to fix it, it is now seemingly blown on ALL of my encoders. I've opened it up, doing a chmod 777 on the file, and still getting errors. Checking permissions on all directories leading to, looks good.

```
$ namei -l /var/www/html/scripts/youtube-cookies.txt
f: /var/www/html/scripts/youtube-cookies.txt
drwxr-xr-x root     root     /
drwxr-xr-x root     root     var
drwxr-xr-x root     root     www
drwxr-xr-x root     root     html
drwxr-xr-x www-data www-data scripts
-rwxrwxrwx www-data www-data youtube-cookies.txt
```

What is the correct solution here?

**Comment by DanielnetoDotCom** [comment]
to be honest I do not know, as you can see it is an issue with yt-dlp utils.py

maybe it does not like the 777 permission, try to make it 755

or try to google for a solution

**Comment by walt93** [comment]
You could just like fucking do a ls -l and post the output but I suppose that is too much to fucking ask
