### ISSUE TITLE
Upload using the mobileManager/upload.php produces unusable video titles when the encoder fails. The encoder fails often. ☹️

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8426]
**Describe the bug**
When my scraper calls mobileManager/upload.php, and the encoder fails, the metadata for the video is not usable.

**To Reproduce**
1. Call mobileManager/upload.php ten times, you will see failures like this at least once:
![Screen Shot 2023-09-14 at 5 53 40 PM](https://github.com/WWBN/AVideo/assets/11711050/5cd9cc19-f94f-4a67-9a5f-5679cd0c309b)

Maybe this video is stuck in the encoder? But I could not tell what video it is. My web scraper app marks the database as "complete" when upload to the encoder is successful, so the scraper will never revisit this. It is lost in the ether. 

This happens at least 1x/day as I'm ingesting from 40+ channels & this causes a huge problem, I'm using this AVideo setup to run a Roku channel & it means my podcasters are sometimes missing episodes. _Please fix the upload.php script to use the filename so I can at least manually fix these when the encoder fails_

**Expected behavior**
For the upload.php script / encoder to use the actual name of the video, not a hash.

**Comment by DanielnetoDotCom** [comment]
I have no idea where this issue comes from. you may need to find where it comes from instead of changing the way the temp names are created
