### ISSUE TITLE
Weird interface bug. Changing a video's membership to Public is not working.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8427]
**Describe the bug**
I have a video marked "Private" as belonging to a group. I don't seem to be able to make it public from /mvideos->edit.

https://github.com/WWBN/AVideo/assets/11711050/717832c0-4985-47ea-90a7-60cdd0f536a3

**Comment by DanielnetoDotCom** [comment]
if you clear the cache, does something change?

**Comment by walt93** [comment]
No

**Comment by DanielnetoDotCom** [comment]
can you please check this update?

**Comment by walt93** [comment]
Not fixed.
