### ISSUE TITLE
What happened to TopMenu? Recent TopMenu changes broke my site design.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8429]
**Describe the bug**
I han designed my TopMenu to have 6 menus, some of them rather long.

After some recent update, with no warning, I have one TopMenu that scrolls for such a ridiculous amount of time that no one is going to use it.

How to get back the old behavior?

**Comment by DanielnetoDotCom** [comment]
I have no idea what do you mean.

You need to provide a screenshot and a link

**Comment by walt93** [comment]
![Screen Shot 2023-09-15 at 4 09 08 PM](https://github.com/WWBN/AVideo/assets/11711050/3c6add46-4aac-47f1-b1f3-93857b5a7787)

These are my six top menus, all in one menu that scrolls for multiple screen lengths. "Podcasts" is the first menu, "Conferences" is the second menu"

Formerly, these were arranged across the top menu.

**Comment by DanielnetoDotCom** [comment]
check this

![image](https://github.com/WWBN/AVideo/assets/18009293/018aa4dd-7fc7-4700-b3b4-89dc9f3c5d29)
