### ISSUE TITLE
[FEATURE REQUEST] Process

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8430]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when a random git pull breaks my site, or changes fundamental features in a way I can't get back.

**Describe the solution you'd like**
Software engineering process. Release cycles. Beta test periods. Release notes.

Suggest you move to a 6 or 12 per year release strategy. Take the last week or two from each release for testing.

Develop on a branch. If people want to take a pull from /dev and get bleeding edge feature development, they can. The rest of us can stick to your release cycle.

The continual development - check out often - test and pray - don't let your checkouts drift too far as I just did or a git pull is going to nuke your site configuration. This cycle is no good Daniel. We're developers. We can do better. Internally you have a version number. Don't merge /dev to /main until you've hit that milestone. Minor change in process. Major benefit to your, what, 4K installed users?

Thank you for coming to my TEDx talk. _Heart emojis on this post act as votes, please and thank you_

**Comment by gbrn** [comment]
More precise launch control is important.

I think that identifying the commits helps a lot in tracking...

![image](https://github.com/WWBN/AVideo/assets/37880073/4e77f369-20d8-4d99-9430-040be7cf2738)

**Comment by walt93** [comment]
I'd rather not micromanage. I would be totally down to download the beta onto a box, clone my database onto it and test the heck out of it every 6-8 weeks & I'm sure a few more of us would too.
