### ISSUE TITLE
Player not working properly after updating to new version

### ISSUE THREAD

**Issue by chenzisuifeng** [WWBN/AVideo#8431]
Player not working properly after updating to new version
![image](https://github.com/WWBN/AVideo/assets/47063171/37a9cf88-2c9b-4142-84aa-d70baee0ae3d)
My play link:https://www.goolada.com/video/1473/davii-%7C-spring-summer-2022-%7C-full-show?channelName=Fffashion

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform

**Comment by DanielnetoDotCom** [comment]
I am pretty sure this is a missing plugin update, https://github.com/WWBN/AVideo/wiki/How-to-Update-your-AVideo-Platform#3-update-plugins

**Comment by chenzisuifeng** [comment]
Yes, maybe the plug-in really failed to be updated, but my versions are all the latest.
![image](https://github.com/WWBN/AVideo/assets/47063171/14f50e4e-f6f7-4824-b085-915b68da3424)
![image](https://github.com/WWBN/AVideo/assets/47063171/3606740b-31c2-406a-8349-1afe925d6750)

**Comment by chenzisuifeng** [comment]
But I found that my plug-in is different from the plug-in on the demo site (demo.avideo.com)
My (CustomizeAdvanced，CustomizeUser) plugin looks like this
![image](https://github.com/WWBN/AVideo/assets/47063171/d6e36b29-2806-4c82-a61c-6e6434a17b18)
![image](https://github.com/WWBN/AVideo/assets/47063171/9a8fcbe6-ff47-4a8c-a632-3b61734a4174)

**Comment by DanielnetoDotCom** [comment]
In your VideoHLS plugin uncheck the p2p_media_loader

![image](https://github.com/WWBN/AVideo/assets/18009293/a9fe0b1d-09e5-4e90-919b-96c0453f5447)

**Comment by chenzisuifeng** [comment]
Thank you very much for your help Daniel Neto
Now my site can be played normally

**Comment by chenzisuifeng** [comment]
But I don’t understand why it could play normally before and now there is a problem with p2p_media_loader after updating.

**Comment by DanielnetoDotCom** [comment]
Videojs was updated to the latest and currently, this feature is not compatible anymore.
