### ISSUE TITLE
Missing text login not displaying

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8437]
@DanielnetoDotCom Some part of the code is missing, it is not displaying the full text.

![image](https://github.com/WWBN/AVideo/assets/37880073/b0e9e0f6-e964-4bcc-a656-a60340b3f6bb)

**Comment by DanielnetoDotCom** [comment]
please guide me how can I reproduce it.

**Comment by gbrn** [comment]
This was displayed during my testing. I don't remember the way. If it happens again I will report it here.
