### ISSUE TITLE
Large images on the first page

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8438]
@DanielnetoDotCom In this last pull, there was a change in the images on the first page. They are large and are not reducing in size, as was the case previously. I imagine this is a mistake, as the image is very large, ugly and doesn't even have enough resolution to be displayed like this.

![CNETV imagem grande](https://github.com/WWBN/AVideo/assets/37880073/4954c60f-87e5-4db0-a006-5bb7a95b9f9e)

**Comment by gbrn** [comment]
Below is the video of the problem. It is not even possible to see the buttons below in the image.

[problema primeira página.webm](https://github.com/WWBN/AVideo/assets/37880073/cb1a1258-5e3b-4e62-8199-f2fcdc9eff4d)

**Comment by gbrn** [comment]
I believe it was these recent changes that caused this issue: 5560fd2
plugin/YouPHPFlix2/view/BigVideoPosterDescription.php

**Comment by DanielnetoDotCom** [comment]
please try this update

**Comment by gbrn** [comment]
Ufa! Issue resolved. Thanks.

![image](https://github.com/WWBN/AVideo/assets/37880073/405cbed9-7174-488f-9c0c-87eb7ff2c2e3)
