### ISSUE TITLE
BUG Public encoder

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8451]
@DanielnetoDotCom When I send a video to the public code, the layout I defined is not loaded, and the logo is not loaded either. The progression bar doesn't appear either.

![image](https://github.com/WWBN/AVideo/assets/37880073/d547e8bb-637b-4376-af7c-24c0d1c153c4)

**Comment by gbrn** [comment]
The encoder is also not finishing...

![image](https://github.com/WWBN/AVideo/assets/37880073/7bf9ce17-8f19-4372-ae37-ca6c23bcf846)

**Comment by DanielnetoDotCom** [comment]
what is the layout problem?

**Comment by gbrn** [comment]
Can't you see it in the images? The system is not pulling my layout into the Encoder. The layout is white, the logo does not appear. Were there any changes?

**Comment by DanielnetoDotCom** [comment]
make sure you are using https, NOT http
