### ISSUE TITLE
Can anyone post their yt-dlp permissions? Mine are totally borked…

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8452]
**Describe the question**
I had one encoder that was giving me an error about permissions to /var/www/html/scripts-youtube-cookies.txt

I tried setting the permissions to something sane and the owner to www-data:www-data.

Now none of my encoders work, not for youtube, not for rumble...

**Screenshots**
![Screen Shot 2023-09-19 at 1 59 43 PM](https://github.com/WWBN/AVideo/assets/11711050/4be5e7a1-3b1b-47d2-9fe0-27482a9c117d)

```
$ namei -l /var/www/html/scripts/youtube-cookies.txt
f: /var/www/html/scripts/youtube-cookies.txt
drwxr-xr-x root     root     /
drwxr-xr-x root     root     var
drwxr-xr-x root     root     www
drwxr-xr-x root     root     html
drwxr-xr-x www-data www-data scripts
-rw-r--r-- www-data www-data youtube-cookies.txt

$ ls -l /var/www/html/scripts/youtube-cookies.txt
-rw-r--r-- 1 www-data www-data 772 Sep 14 05:01 /var/www/html/scripts/youtube-cookies.txt
```

**Comment by DanielnetoDotCom** [comment]
Why don't you try to purge and reinstall Python?

**Comment by walt93** [comment]
Because it was in a weird state.

I have 6 encoders running on two boxes. Only 1 encoder was giving this error, which still makes no sense. 

I issued a chmod+chgrp on youtube-cookies.txt, stupidly, on both machines & now all 6 are in the same state (at least its consistent now).

It seems like a chmod+chgrp should restore things, but I have not found any combination yet that makes it work.
