### ISSUE TITLE
Error on NGINX SSL 

### ISSUE THREAD

**Issue by techisgreat** [WWBN/AVideo#8453]
When we are on step of where we have to put this line 
`sudo apt-get install python3-certbot-nginx -y`

I got this error
![image](https://github.com/WWBN/AVideo/assets/100486259/efb18c21-c9e2-4754-af8c-1f9827efaf77)

**Comment by milehighkaraoke** [comment]
you need to set up your site in apache

**Comment by techisgreat** [comment]
Of course it is installed. 
But where i am stuck is where it ask 2 option 1 or others not working. 
I follow step by step of this page. 

https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x-for-AVideo-Platform-version-11.x-or-newer

You can see NGINX is after Apache install

**Comment by DanielnetoDotCom** [comment]
your nginx.conf is probably wrong

**Comment by techisgreat** [comment]
I never touch the nginx.conf 
Be cause you have line specified this things. 

`sudo mv /usr/local/nginx/conf/nginx.conf /usr/local/nginx/conf/nginx.conf.old && cd /usr/local/nginx/conf/ && sudo wget https://raw.githubusercontent.com/WWBN/AVideo/master/plugin/Live/install/nginx.conf && sudo mkdir /HLS && sudo mkdir /HLS/live && sudo mkdir /HLS/low
sudo mv /usr/sbin/nginx /usr/sbin/nginx.old && sudo cp /usr/local/nginx/sbin/nginx /usr/sbin/nginx
sudo mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.old && sudo cp /usr/local/nginx/conf/nginx.conf /etc/nginx/nginx.conf`

**Comment by techisgreat** [comment]
So i have to modifiy Something ? 
I suggest you to re-work instruction you gave

**Comment by DanielnetoDotCom** [comment]
there was a missing section in the tutorial, I just added it.

https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-20.x-for-AVideo-Platform-version-11.x-or-newer#add-the-domain-in-the-nginxconf

please check this

**Comment by techisgreat** [comment]
Perfect it works for this part. 

Now i am facing to this 

![image](https://github.com/WWBN/AVideo/assets/100486259/41b8f45a-7926-433f-96ff-8fc6262eab50)

**Comment by DanielnetoDotCom** [comment]
Seems to be missing database tables. 

check your plugins and install all tables, even if you are not using them. 
if it persists check your logs.

**Comment by techisgreat** [comment]
Everythings works well thanks !

**Comment by techisgreat** [comment]
Reboot was fixing issue.
