### ISSUE TITLE
yt-DLP 

### ISSUE THREAD

**Issue by techisgreat** [WWBN/AVideo#8457]
I got this error on trying downloading from youtube. 
What i try is re-installing but same issue 
`python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz`

`Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`
![image](https://github.com/WWBN/AVideo/assets/100486259/062f9a3c-8de4-4c83-ba5d-f53dc0a92b9c)

Any one have fix ?

**Comment by DanielnetoDotCom** [comment]
duplicated

https://github.com/WWBN/AVideo/issues/8454
