### ISSUE TITLE
Unable to switch to FHD automatically on viewing

### ISSUE THREAD

**Issue by techisgreat** [WWBN/AVideo#8462]
Unable to switch to FHD automatically on viewing.
As a user, you can't switch to FHD, only to HD automatically. 
As an administrator, it's impossible to program higher than HD by default.

I own: VideoResolutionSwitcher 
I thought I could automatically have FHD or 4K compatible.

**Comment by DanielnetoDotCom** [comment]
To ensure we do not waste disk space and bandwidth, we will examine the file source before encoding and will not upconvert the video. For example, if you upload a 720p video, we will only convert it into 720p, 480p, 360p, and 240p. 

Also to auto switch the resolution the VideoHLS is required. Also the HLS format of course

**Comment by techisgreat** [comment]
I Guess... VideoHLS is not supported by FTP storage ?

**Comment by DanielnetoDotCom** [comment]
You are right, they are not compatible
