### ISSUE TITLE
Unable to move a video from private to public

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8464]
**Describe the bug**
In /mvideos the "Remove User Group" menu does not work
In the video editor, setting the video to "public" does not work.

**To Reproduce**
1. Go to /mvideos
2. Select a video that is "Private" (has a group membership)
3. Select Remove User Group->the group it is a member of
4. Observe that nothing happens

1. Go to the video editor for that video
2. Go the the Privacy tab
3. Click "Public"
4. Click "Save"
5. Observe that nothing happens

**Expected behavior**
To be able to change the membership of the video

There is a common pattern here. Changing anything in the database is broken. The cache is broken. We're in a really bad state.

**Comment by DanielnetoDotCom** [comment]
tested on the demo site and seems to be working fine. are you sure you are up to date?

![chrome-capture-2023-8-23](https://github.com/WWBN/AVideo/assets/18009293/f0aa9589-84dd-41fa-ab02-4d1bb8b8547c)

**Comment by walt93** [comment]
Yes Daniel. I just did a git pull. The behavior is unchanged. Take a look at the last I don't know how many bugs I reported.

I can't edit video titles/descriptions reliably.
I can't change anything to do with categories without going through a painful dance of clearing every possible thing and reloading the browser and hoping that it works.
The mobileManager/upload.php script is broken AF (sets the wrong title, doesn't set description, doesn't work for any but the admin user) I just got tired of reporting to you & you gaslighting me saying it works.

I am having a _very frustrating time_ with AVideo right now. You can't even take a git pull reliably. Sometimes, if you hadn't done it for some time, your site just gets blown away. Seriously, Daniel…

**Comment by DanielnetoDotCom** [comment]
Sorry if I cannot reproduce I cannot help. 

Try to reproduce it on demo site

**Comment by walt93** [comment]
Daniel if you cannot reproduce it, then I doubt if I can either.

Could you please explain to me the database schema so I can go in and set these videos to the correct state myself? What controls group ownership and how do I revert something to public?

**Comment by DanielnetoDotCom** [comment]
All the database schema is open source , just check in the install folder 

Make sure videos folder and all sub folders and files are chmod 777

**Comment by walt93** [comment]
Yes, I understand that Daniel, I am looking at the database schema:

```
mysql> describe videos_group_view;
+-----------------+------+------+-----+---------+----------------+
| Field           | Type | Null | Key | Default | Extra          |
+-----------------+------+------+-----+---------+----------------+
| id              | int  | NO   | PRI | NULL    | auto_increment |
| users_groups_id | int  | NO   | MUL | NULL    |                |
| videos_id       | int  | NO   | MUL | NULL    |                |
+-----------------+------+------+-----+---------+----------------+
3 rows in set (0.00 sec)

```
What I asked is - if I delete - you know what - it doesn't matter - I ask a question - you provide an answer to a different question from what I asked. I'll reverse engineer the thing myself. Thank you very much!
