### ISSUE TITLE
 /cat/XXX category page does not display media in the sub-categories correctly, duplicating some videos & hiding others

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8483]
**Describe the bug**
I am on a category page that has sub-categories.

Let's say that the sub-category contains 25 items. I might see 16 unique items and 9 items are repeated - the other 9 unique items are not displayed. 

This causes media to be "hidden" from the user, and they will never find it (why would they drill down further? It looks like you can see all the media. It looks like there are duplicates.

This also makes us look like we are always uploading "duplicate" videos to every category.

Can you **please** give this some attention Daniel? I have a **lot** of media on my site, and bugs like this make me feel like I'm wasting my time assembling it because no one can find it. I will happily send you a clone of my database so you can recreate it. 

**To Reproduce**
1. Create a site with 10,000+ videos and 500+ categories
2. Drill through that site ... pretty much anywhere on any category page with sub categories
3. Scroll down to any subcategory
4. Observe

**Expected behavior**
To see unique videos, not repeated.

**Screenshots**
Observe page https://conspyre.tv/cat/good-lion-films is showing 31 videos in sub-category "Documentaries". There are 9 duplicates and 8 videos are "hidden":

![Screen Shot 2023-09-30 at 12 48 27 PM](https://github.com/WWBN/AVideo/assets/11711050/0bfafdd6-20d7-4c38-9df7-0323b6848fcd)

Observe as we drill down into sub-category "Documentaries" there are 30 unique videos. **This is how we expect the videos to display on the previous page**

![Screen Shot 2023-09-30 at 12 57 45 PM](https://github.com/WWBN/AVideo/assets/11711050/7dcf2199-3586-418d-8ddb-dfd203a497a9)

**Comment by DanielnetoDotCom** [comment]
I am sorry, I tried so hard to reproduce it and I could not.

**Comment by walt93** [comment]
Daniel I have >10,000 videos in 500 categories and I can reproduce this all over the site.

It's really frustrating, you know? Users simply can not find media because the site hides it from them. Best way I can think of is for me to send you my database. What's the most efficient way to do it? 
A) Can you set up something for me to scp to?
B) I have multiple servers. I could clone the database onto a fresh install and give you access?

**Comment by DanielnetoDotCom** [comment]
the database will not work because the script will mark all the videos as "broken missing files"
that is what I got for testing. it is a pretty good amount

```sql

MariaDB [avideo]> select count(*) from playlists;
+----------+
| count(*) |
+----------+
|       57 |
+----------+
1 row in set (0.000 sec)

MariaDB [avideo]> select count(*) from playlists_has_videos;
+----------+
| count(*) |
+----------+
|     3798 |
+----------+
1 row in set (0.001 sec)

MariaDB [avideo]> select count(*) from videos;
+----------+
| count(*) |
+----------+
|      662 |
+----------+
1 row in set (0.000 sec)
```

**Comment by walt93** [comment]
If you're not able to reproduce it, then, the data set is not good.

What do you mean you will only get "broken missing files"?

Does this mean it is not possible to restore from a backup, ever?

**Comment by DanielnetoDotCom** [comment]
Regarding the 3-5 level deep hierarchy, I want to inform you that I already have such a setup on my site for testing. 

In terms of obtaining your database, the database alone will not work since, without the associated video files (even dummy files), they will be flagged as missing. 

If you'd like a more direct examination of your setup, you can consider hiring me through the marketplace for a detailed analysis of your installation.
