### ISSUE TITLE
[Bug] Sort order; after setting the order, on re-opening the Sort Order screen, the order is scrambled

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8487]
**Describe the bug**
I carefully set the order for 36 videos. After clearing the cache, the site loads in the correct order.

I want to modify the sort order.

I open the sort order, and, the videos have been "scrambled" - they are not in the order that was just set.

**Comment by DanielnetoDotCom** [comment]
why don't you use playlists on the first page? then you can specify the order

**Comment by walt93** [comment]
What? How do you even set this up? I have >100 playlists for the admin user, they're used to build Roku channels.

**Comment by DanielnetoDotCom** [comment]
I also have hundreds of playlists and videos in it. and this does not happen to me.
