### ISSUE TITLE
[Google IMA + Ad Server] plays 4 ads when it should only play 1

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8490]
**Describe the bug**
We're set to play one pre-roll ad.
Two ads play, then a few seconds of video, then two more ads - for a total of four.
After this, the video plays...

**To Reproduce**
1. Turn on Ad server, create a campaign, add one ad to it
2. Set Ad server for one preroll ad
3. Turn on Google IMA
4. Give Google IMA the Ad Server url
5. Set Google IMA to play one pre-roll
6. Play a video
7. Watch two ads play
8. Watch the first few seconds of the video play
9. Watch two more ads play
10. VIdeo continues to play without interruption after that

**Expected behavior**
One ad to play

**Comment by DanielnetoDotCom** [comment]
To better understand and diagnose the issue, could you please provide screenshots of the following:

1. Your googleads_ima parameters/settings.
2. The configuration of your Ad Server.
3. The list of videos you have on your platform.

These screenshots will help in identifying any configuration discrepancies that might be causing the behavior you've described.

**Comment by walt93** [comment]
![Screen Shot 2023-10-02 at 12 17 28 PM](https://github.com/WWBN/AVideo/assets/11711050/a7d70547-a60b-4927-a35a-1a14270c324f)
![Screen Shot 2023-10-02 at 12 17 49 PM](https://github.com/WWBN/AVideo/assets/11711050/685c08e9-ee8d-430d-8ed1-54db1f26cc29)
![Screen Shot 2023-10-02 at 12 18 57 PM](https://github.com/WWBN/AVideo/assets/11711050/150aeeb6-db51-4cd3-b0b2-f1343167f537)
![Screen Shot 2023-10-02 at 12 20 31 PM](https://github.com/WWBN/AVideo/assets/11711050/4dfcab63-0a03-4f00-b9f7-75879220b479)

Daniel do you seriously want a list of videos on the platform? The whole database perhaps? There is only one video ad loaded into the campagin.

**Comment by DanielnetoDotCom** [comment]
No, I mean only the videos on the ads, like you did. I will check it

**Comment by DanielnetoDotCom** [comment]
![image](https://github.com/WWBN/AVideo/assets/18009293/9db8a6d5-c79d-4a7b-910e-142c24a8c424)

delete this value in the image above and make it blank
if you are using "Show AD on Start" you do not need it

![image](https://github.com/WWBN/AVideo/assets/18009293/5d81e4cb-37cd-4095-9aec-8b5867f7c46d)


regarding the 2 ads, are they the same ad? or 2 different ones?

**Comment by walt93** [comment]
Updated to GoogleAds_IMA 2.6

Now it plays the ad 0 times. The advertisement briefly shows for ≈0.5 seconds. You see the UI for the ad appear and then the video play.

At least it no longer plays the ad 4 times…

**Comment by walt93** [comment]
I tried various combinations of turning on [X] Show AD on Start on both plugins. I am unable to get it to play the ad now.

**Comment by DanielnetoDotCom** [comment]
I can see your ads on the demo site

![image](https://github.com/WWBN/AVideo/assets/18009293/64eb6e45-7ca3-4a44-bde6-65e650003122)

![chrome-capture-2023-9-2 (1)](https://github.com/WWBN/AVideo/assets/18009293/f814a7f3-b513-4c4b-a246-18020cf711d1)

**Comment by walt93** [comment]
Maybe users of the demo site will buy my merch.

**Comment by DanielnetoDotCom** [comment]
Can you please screenshot your GoogleAds_IMA plugin parameter?

also Show Advanced Options

**Comment by walt93** [comment]
![Screen Shot 2023-10-04 at 2 03 46 PM](https://github.com/WWBN/AVideo/assets/11711050/6cedad02-ed73-46c6-95ed-ab0c3ba61e8b)
![Screen Shot 2023-10-04 at 2 03 39 PM](https://github.com/WWBN/AVideo/assets/11711050/62733eba-793b-4c5d-8e4a-d4b85975c279)

**Comment by walt93** [comment]
Yes, I just updated to v2.6 yesterday

**Comment by DanielnetoDotCom** [comment]
I see now. you have AD_Server and also GoogleAds enabled. remove the AD Tag URL from Google 
also I suspect you have 2 active Campaigns with this video on AD_Server.
