### ISSUE TITLE
Proper settings for Cache plug-in?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8499]
**Describe the question**
My site performance did not get significantly better after purging the CachesInDB table

Example: logging in takes 90-120 seconds.

What are reasonable settings for this Cache plug-in?

**Screenshots**
![Screen Shot 2023-10-02 at 9 52 44 PM](https://github.com/WWBN/AVideo/assets/11711050/2818f033-a358-447c-9d64-457a3cfbeb2b)

**Comment by DanielnetoDotCom** [comment]
Another similar issue, it does not help

https://github.com/WWBN/AVideo/issues/8500
