### ISSUE TITLE
Cannot retrieve Youtube videos 

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8502]
When I try to import videos from Youtube it doesn't work anymore, file is not appearing on the encoder queue. I see the following repeating errors when I try to run an import:

![Screenshot 5784-01-20 at 0 42 31](https://github.com/WWBN/AVideo/assets/58882903/861b31db-9592-4d57-802d-f934fbc54716)
![Screenshot 5784-01-20 at 0 38 47](https://github.com/WWBN/AVideo/assets/58882903/f9579914-4492-43f1-bdb8-8f164e1fd43b)

My python youtube-dl is the most recent and I also have yt-dlp. I am not sure how it is set and how to switch between them, however it used to work, so im not sure if it is related to my previous issues with live streaming and my network encoders.

**Comment by GreenDragonTavern** [comment]
I'd delete youtube-dl. If ya want to reference it ```sudo ln -s /usr/local/bin/yt-dlp /usr/local/bin/youtube-dl``` will do the trick since yt-dlp is parameter compatible. Also what does yt-dlp -U return and encoder avideo.log, what does it reflect?

**Comment by guymass** [comment]
Well my yt-dlp -U shows:
Available version: stable@2023.09.24, Current version: stable@2023.09.24
yt-dlp is up to date (stable@2023.09.24)

I have create the symbolic link like you showed me and here are some screen shots of my log when trying to import a YT url:
![Screenshot 5784-01-21 at 5 12 11](https://github.com/WWBN/AVideo/assets/58882903/1da7c526-3a34-4666-a0ae-365581a4dec1)
![Screenshot 5784-01-21 at 5 11 36](https://github.com/WWBN/AVideo/assets/58882903/2e625ad3-5d99-4277-9581-d3c3e6b8eb52)
![Screenshot 5784-01-21 at 5 11 15](https://github.com/WWBN/AVideo/assets/58882903/08dd673e-c142-44df-8ece-573a253c8304)

imported video is not being encoded and is broken:

![Screenshot 5784-01-21 at 5 18 23](https://github.com/WWBN/AVideo/assets/58882903/98f29034-8f0d-428f-b92e-ae77705de80b)

**Comment by guymass** [comment]
Am I missing anything in my FFMPEG configuration?

configuration: --host-ldflags=-L/usr/local/lib --enable-gpl --enable-libgsm --enable-libxvid --enable-libmp3lame --enable-libvorbis --enable-shared

**Comment by DanielnetoDotCom** [comment]
I am not seeing any issue, you need to provide more info from your encoder log

**Comment by guymass** [comment]
I have this info running yt-dlp:

Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)

I still cannot retrieve URLs from Youtube. I see the following errors in my logs:

Unrecognized option 'preset'.
Error splitting the argument list: Option not found
![Screenshot 5784-01-30 at 11 57 29](https://github.com/WWBN/AVideo/assets/58882903/52f1060f-7a05-426d-875b-064960917a7d)

![Screenshot 5784-01-30 at 12 03 48](https://github.com/WWBN/AVideo/assets/58882903/752f5043-2864-4016-b448-fdd992cfa367)
![Screenshot 5784-01-30 at 12 03 28](https://github.com/WWBN/AVideo/assets/58882903/e577bc14-3b36-4fa0-a874-2c3ea08dfd11)

File missing or broken:

![Screenshot 5784-01-30 at 12 04 32](https://github.com/WWBN/AVideo/assets/58882903/d0f401c9-7426-4c66-ac68-30572a22fb3a)

**Comment by guymass** [comment]
Also trying to upload a video to the encoder show me now this error:
![Screenshot 5784-01-30 at 12 13 14](https://github.com/WWBN/AVideo/assets/58882903/565f46f8-71dc-424d-9fc4-44bd8fc05ff2)

I have changed the server for the network encoders and it has a much lower ping and is working faster, but it still doesn't encode properly.

**Comment by guymass** [comment]
My bottom encoder  works just fine, the issue is only with my top encoder which is the one located locallay on the same server as the site. The only difference I see between the two is in this ffmpeg configuration:

![Screenshot 5784-01-30 at 12 27 18](https://github.com/WWBN/AVideo/assets/58882903/4097d997-6d7c-4a0e-b6c1-71252215d901)

Where would I change that for the encoder?

**Comment by DanielnetoDotCom** [comment]
Make sure you are using ffmpeg 4 or greater. 

you have a bad ffmpeg version

**Comment by guymass** [comment]
Ok thanks I will check this and if goes well will close this post. This is what my version shows:

![Screenshot 5784-02-02 at 23 19 10](https://github.com/WWBN/AVideo/assets/58882903/0cbb9288-d581-44c7-bc46-ee5b540459a7)

**Comment by guymass** [comment]
Ok yes this was my problem, the ffmpeg wasn't updated to the correct version, so I did the following and now everything works.

From this post https://askubuntu.com/questions/1360827/safest-way-to-install-latest-stable-ffmpeg-4-3-on-ubuntu-20-04-ppa-not-wor

I short:

sudo add-apt-repository ppa:savoury1/ffmpeg4
sudo apt-get update
sudo apt-get install ffmpeg

Then you should make a backup of the old ffmpeg and copy the new one as follows in ubuntu at least:

cp /usr/local/bin/ffmpeg /home/youhomedir/
cp /usr/bin/ffmpeg /usr/local/bin/

In my case that did the trick!
