### ISSUE TITLE
Playlist not working

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8505]
I try to play my playlist here https://www.joshwhotv.com/plugin/PlayLists/player.php?playlists_id=165116

and it just shows a blank video

![bbfa5f5b-baa4-45f1-8d36-0ba082aa8cd7](https://github.com/WWBN/AVideo/assets/39392449/9cbd6458-32bb-463b-956f-bfe03b86a729)

**Comment by DanielnetoDotCom** [comment]
please try now

**Comment by JoshWho** [comment]
Perfect thank you Daniel.
