### ISSUE TITLE
Shorts seems to have no view limit set? 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8506]
![9540ef39-4ca9-4dc7-a55f-0ed1855a1981](https://github.com/WWBN/AVideo/assets/39392449/e3a4f2b4-e7f4-4e04-8dfd-10774d0083c8)

**Comment by DanielnetoDotCom** [comment]
removing the custom CSS you have added to make it work again. 

avoid add a custom CSS, they were wong, also you have HTML tags at the head it was wrong

**Comment by JoshWho** [comment]
> removing the custom CSS you have added to make it work again.
> 
> avoid add a custom CSS, they were wong, also you have HTML tags at the head it was wrong

Odd, I haven't touched that in years.
