### ISSUE TITLE
Rumble embed not grabbing data

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8535]
![ae5bc468-de14-4f8b-b9d6-8e287a6c52ad](https://github.com/WWBN/AVideo/assets/39392449/c2dec255-16ba-4830-8725-48df9f0257b0)

This is the embed link https://rumble.com/embed/v3myz7t/?pub=7dth1

this is the reg link https://rumble.com/v3pkd5e-a-real-cear-that-cant-be-called-a-cear-joshwho-truth-intel-tv-seekingthetru.html

**Comment by DanielnetoDotCom** [comment]
please try now

**Comment by JoshWho** [comment]
It embeds now but I noticed the View counter is not changing staying at zero

![8c7f2fad-0fc3-4a5d-9e05-59e34fe8f6da](https://github.com/WWBN/AVideo/assets/39392449/d9333a5d-3c2b-41a1-997c-5543e1b9a302)

**Comment by JoshWho** [comment]
Give this link a try see if the view counter changes for you https://www.joshwhotv.com/video/.7HPseQ/world-economic-forum-now-wants-to-target-the-water?channelName=SeekingTheTruth
