### ISSUE TITLE
Embedding Live Links is not passing embed links anymore

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8538]
https://rumble.com/embed/v3npa1d/?pub=4

When try to use in Live links just shows a online thing and a play button.

**Comment by DanielnetoDotCom** [comment]
Rumble is blocking it 

![image](https://github.com/WWBN/AVideo/assets/18009293/531d7fb7-aa28-4b6f-b2e0-d1cc3c993327)

**Comment by JoshWho** [comment]
That doesn't make sense unless it is only the live streams they are doing that too. Regular uploads embed with that style url.

**Comment by JoshWho** [comment]
> Sorry, this update will make it work
> 
> just make a git pull and clear the cache

That did the trick. Thank you
