### ISSUE TITLE
View Counter not working on rumble embed

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8545]
![2cf0d7ba-0c46-4c82-be95-d0aa77a9659f](https://github.com/WWBN/AVideo/assets/39392449/2ad67301-5993-4013-b5f1-6a67c2d55b7c)

This is the link to that video https://www.joshwhotv.com/video/.7HPsdg/bill-gates-tells-a-bare-faced-lie-saying-quot-i-don-apos-t-remember-talking-about-masks.-quot-%F0%9F%99%84%F0%9F%A7%90?channelName=SeekingTheTruth

**Comment by DanielnetoDotCom** [comment]
Any idea where this comes from?
````
<script src="/cdn-cgi/apps/head/5JL--ijaV5foCnu_LpipyDYLBjs.js">
````

**Comment by JoshWho** [comment]
looks like a cloudflare thing

**Comment by JoshWho** [comment]
Did you figure out why it is staying at zero views?

**Comment by JoshWho** [comment]
I took it off cloudflare and it is still doing it.

**Comment by JoshWho** [comment]
> Any idea where this comes from?
> 
> ```
> <script src="/cdn-cgi/apps/head/5JL--ijaV5foCnu_LpipyDYLBjs.js">
> ```

That was cloudflare I think. I don't have it on cloudflare anymore

**Comment by JoshWho** [comment]
Here is another one the view counter stays at zero https://www.joshwhotv.com/video/.7HPseQ/world-economic-forum-now-wants-to-target-the-water?channelName=SeekingTheTruth

**Comment by JoshWho** [comment]
Thank you it is fixed
