### ISSUE TITLE
Under Maintanance ???

### ISSUE THREAD

**Issue by Rolandhun74** [WWBN/AVideo#8550]
Hello

After updating, you will receive this page:

https://eventstream.eventes.hu

THX
Roland

<img width="1680" alt="Képernyőfotó 2023-10-20 - 15 11 32" src="https://github.com/WWBN/AVideo/assets/83669701/1689cab2-9adc-4e27-bfda-c57b512d7e96">

**Comment by Rolandhun74** [comment]
Thanks for the help Daniel. Now I get this error when I want to play a video

https://eventstream.eventes.hu/video/live-stream-02-15?channelName=EVENTES

<img width="1680" alt="Képernyőfotó 2023-10-20 - 15 34 23" src="https://github.com/WWBN/AVideo/assets/83669701/083c8d45-5141-4b3e-8512-440f0c7fb2a4">

**Comment by DanielnetoDotCom** [comment]
The video ID is missing

![image](https://github.com/WWBN/AVideo/assets/18009293/d08a977c-8137-49f6-ac13-6ab3bfae9933)

where did you get this URL from?

**Comment by gbrn** [comment]
I've been facing this problem _videos id is empty_ for a long time! #8059

**Comment by Rolandhun74** [comment]
> The video ID is missing
> 
> ![image](https://user-images.githubusercontent.com/18009293/276948193-d08a977c-8137-49f6-ac13-6ab3bfae9933.png)
> 
> where did you get this URL from?

I do not understand the question

**Comment by DanielnetoDotCom** [comment]
Where did you click to get a URL without ID?

**Comment by Rolandhun74** [comment]
> Where did you click to get a URL without ID?

on any video on the whole site
on the homepage, video management… anywhere

**Comment by DanielnetoDotCom** [comment]
make sure you have this checked

![image](https://github.com/WWBN/AVideo/assets/18009293/f7fad837-e8da-48f6-a8c6-888f6902ee5c)

**Comment by Rolandhun74** [comment]
Thank you Daniel
it works
