### ISSUE TITLE
php 8.2 update Ubuntu

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8551]
@DanielnetoDotCom Danny, these new settings requested in the php 8.2 update Ubuntu, do you know if this could cause any problems for the platform?
![image](https://github.com/WWBN/AVideo/assets/37880073/30982532-d36a-48e1-8872-6276332477db)

![image](https://github.com/WWBN/AVideo/assets/37880073/29054045-5240-4603-ad72-602e76782f10)

**Comment by DanielnetoDotCom** [comment]
I guess you can keep the version

**Comment by gbrn** [comment]
Ok I keep the local version. It's all OK.
