### ISSUE TITLE
Could you make the programs list be the maximum height of the row/view it is contained in?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8554]
**Is your feature request related to a problem? Please describe.**
I have a lot of programs to scroll in a small viewport. There is dead space below the viewport, we could optimize use of that screen real estate.

**Describe the solution you'd like**
For the bottom edge of the programs list view to anchor to the bottom edge of the containing row.

**Describe alternatives you've considered**
Hacking the source code, I know, it is not recommended...

![Screen Shot 2023-10-21 at 12 17 38 AM](https://github.com/WWBN/AVideo/assets/11711050/fabfa5c3-b7ba-4657-9ea7-1afd97632120)

**Comment by DanielnetoDotCom** [comment]
I can increase the height, but I cannot make it occupy 100% (A CSS knowledge limitation)
