### ISSUE TITLE
Internal Notifications for new videos don't go to the video

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8555]
Seems like when you click the notification it just goes to a random video instead of the video you are being notified about.

**Comment by DanielnetoDotCom** [comment]
can you post here a sample link of what you are clicking?

what exact notification are you referring to?

**Comment by JoshWho** [comment]
I think it might be fixed. I haven't seen it do it yet again. I will close this for now. The last update might have fixed it and was just seeing older notifications doing it.
