### ISSUE TITLE
Site crash after git pull

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8556]
Getting the following error after I made a git pull.

![Screenshot 5784-02-07 at 23 57 27](https://github.com/WWBN/AVideo/assets/58882903/276349c5-4dc5-42c2-b4b6-be043e2c7167)

[22-Oct-2023 23:59:41 Asia/Jerusalem] AVideoLog::ERROR: {"type":64,"message":"Cannot redeclare secondsToTime() (previously declared in \/var\/www\/html\/AVideo\/objects\/functions.php:11963)","file":"\/var\/www\/html\/AVideo\/plugin\/SubtitleSwitcher\/functions.php(18) : eval()'d code(1) : eval()'d code","line":102} SCRIPT_NAME: /view/xsendfile.php

**Comment by guymass** [comment]
OK I moved the plugin folder and now its up again. probably I need to download an update. I will check with updated plugin again and see if this is solving this error.

**Comment by DanielnetoDotCom** [comment]
Update the SubtitleSwitcher plugin

**Comment by JoshWho** [comment]
Yup it is ubtitle Switcher causing it if out of date

**Comment by guymass** [comment]
Ok I managed to update the plugin but now I see the following errors and the site doesn't load or loads very very slow.
![Screenshot 5784-02-08 at 19 31 45](https://github.com/WWBN/AVideo/assets/58882903/450b98af-a793-47bb-b7a5-d0c904e1f814)

Looks like something wrong in my SQL. I have Mariadb installed.

**Comment by guymass** [comment]
Ok thanks I will try it, currently been running it for couple of min. How long does this process roughly should take?

**Comment by guymass** [comment]
OK great that fixed it. Its loading now although I am still suffering from slowness when moving between pages like entering a video and then going back to home page sometimes take me 15-20sec it just hangs. Anyway for this issue its fixed so i am closing this, much thanks your the man ;-)
