### ISSUE TITLE
Something weird going on with Twitter Embed No thumbnails load

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8557]
![image](https://github.com/WWBN/AVideo/assets/39392449/bf950d24-9696-4c90-a69a-7eff4be8873b)

Test link https://www.joshwhotv.com/video/.u3r4/bitch-is-you-the-hobbit-kanye-defends-kim?channelName=WhatsNew

**Comment by DanielnetoDotCom** [comment]
I guess it is something in your CDN

I am trying to add this video 

https://www.joshwhotv.com/video/.7Cq4cA/tiffany-dover-gone-forever?channelName=HickJames

this is the image that is supposed to be added https://static.joshwho-cdn.com/videos/video_220903031145_v4c92/video_220903031145_v4c92_thumbsV2.jpg?cache=16889080241695853857

but if you inspect the Apache access log this image was never requested

If you want try the videos from https://tutorials.avideo.com/

**Comment by JoshWho** [comment]
It looks like it is working now. Not sure what happened.
