### ISSUE TITLE
How can I embed the playlist player in another site?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8568]
**Describe the question**
Trying to embed a playlist into another site, it's only rendering the video player in the top left corner. No playlist. No video title/description/etc.

**Screenshots**
![Screen Shot 2023-10-23 at 11 32 15 PM](https://github.com/WWBN/AVideo/assets/11711050/a04ef880-9024-4e81-93ff-81c8128516c6)

I've used both the [Copy embed code] and [Copy embed gallery] and dropped them into a custom code block. Both options render as this (we've left a big HTML block to render into, it's only getting that player):
![Screen Shot 2023-10-23 at 11 33 05 PM](https://github.com/WWBN/AVideo/assets/11711050/6bc5b619-1d60-49b3-bd93-ba580feae592)

Update: I guess the viewport size in that embed script was too small. The [Embed Gallery] is cool, I guess, I wish it could be configured to be 3 or even 4 columns. I thought we had an embeddable page with player and scrolling playlist?

**Comment by DanielnetoDotCom** [comment]
can you share a link sample? a link where the playlist is embed?

**Comment by walt93** [comment]
Not readily, site isn't published, I got it working Daniel but it's just the two-across view. Copying the code from the UI above points to playerEmbed.php

![Screen Shot 2023-10-24 at 3 03 42 PM](https://github.com/WWBN/AVideo/assets/11711050/f61ed597-8bb3-4971-ad55-03e922c45df4)

I guess if I go and change it to point to player.php I get what I was looking for, sort of, but the formatting is crunched:
![Screen Shot 2023-10-24 at 3 05 34 PM](https://github.com/WWBN/AVideo/assets/11711050/3723515f-4c19-42d4-9851-96e25c77142d)

**Comment by walt93** [comment]
Is it possible to update playerEmbed.php to do 3-up or 4-up layout?

**Comment by DanielnetoDotCom** [comment]
Sorry, I am still not sure what you want.

**Comment by walt93** [comment]
I figured it out, it was the iframe width as set in the script - that's what was keeping it fix
