### ISSUE TITLE
Site got very slow

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8569]
Not sure really what is the problem but the site gotten very slow, meaning, just moving between pages, going into a live stream and then just going back to home page or any other click will take me 15-20sec to move between pages. This wasn't like this before, any click would move really fast out of and into pages and posts. Loading videos was much faster, now I am waiting for almost 30sec until I load the video.

In log I see the followings:

![Screenshot 5784-02-09 at 14 30 38](https://github.com/WWBN/AVideo/assets/58882903/36c8a583-12ad-46c1-a033-753aeb881422)
![Screenshot 5784-02-09 at 14 44 17](https://github.com/WWBN/AVideo/assets/58882903/7318dffc-cc15-4102-a829-ed5e5cb2e07d)

And I see this also in the browser console:
![Screenshot 5784-02-09 at 14 20 19](https://github.com/WWBN/AVideo/assets/58882903/26439aeb-de82-4bf8-b5b5-0813f06cddb9)

Now this comes and goes, but mostly  lately the site feels more heavy or as if something is causing it to hang more then usual when browsing the site.

See how it loads for you and how easy it is for you to switch through few of the videos. https://alive528.com

**Comment by DanielnetoDotCom** [comment]
First check in your logs what is this error

![image](https://github.com/WWBN/AVideo/assets/18009293/af3c05b4-376e-49c6-acf1-898f37399cda)

BTW, your site loads fine here

**Comment by guymass** [comment]
Ok it could be DNS and we are also experiencing a lot of internet issues in Israel since late so it could also be network related I will keep testing as it comes and goes.

**Comment by guymass** [comment]
This also be something in my cache. I ran php cacheReconstruction script again and now seems to be better, so it could be just related to my previous issue, I will close this for now.
