### ISSUE TITLE
Is there a way to upload an unlisted video?

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#8598]
I know you can restrict the video to user groups but I just want a public ly accessible unlisted video.

**Comment by DanielnetoDotCom** [comment]
If you want all the videos to be unlisted by default you can change it here 

![image](https://github.com/WWBN/AVideo/assets/18009293/a1ad5eb3-6def-4b92-ba71-d09a8d12942f)

if it is just a single video you can change it here 

![image](https://github.com/WWBN/AVideo/assets/18009293/f370c2c9-a5c2-4edb-ad11-12b7b65718a9)

**Comment by fakeologist** [comment]
Thank you that's the only one I didn't click.

**Comment by fakeologist** [comment]
Once the video is uploaded, where are these settings? I can't find them to change them.

**Comment by DanielnetoDotCom** [comment]
What settings?

**Comment by fakeologist** [comment]
the override status settings you circled above. I can't find them to change them once uploaded.

**Comment by DanielnetoDotCom** [comment]
Please be specific which one

**Comment by fakeologist** [comment]
the override status. Once uploaded, where can you change the status? There is no area to change it to unlisted, unlisted searchable, etc as there is when you are uploading it.

**Comment by DanielnetoDotCom** [comment]
Please provide some screenshots and steps to reproduce what you are doing. otherwise, I cannot help you.

**Comment by fakeologist** [comment]
Show me the steps to make an already uploaded video unlisted and searchable.

**Comment by DanielnetoDotCom** [comment]
# Option 1 (1 video only)

![chrome-capture-2023-10-2 (1)](https://github.com/WWBN/AVideo/assets/18009293/4f1ce12e-7d60-42e3-8a30-b3342bfcacbd)

# Option 2 (Multiple videos)

![chrome-capture-2023-10-2 (2)](https://github.com/WWBN/AVideo/assets/18009293/f4cd0a84-e304-412f-a2c8-fcf8de03615e)

**Comment by fakeologist** [comment]
ok thanks it's the "status" that I was trying to change.
