### ISSUE TITLE
Unknown error is causing site to hang.

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8609]
I will try to pinpoint this error and only focus on this one. It is constantly repeating and I don't know why I get this error and how I get rid of it.

![Screenshot 5784-02-23 at 13 21 38](https://github.com/WWBN/AVideo/assets/58882903/c96df1d9-cd5c-49f4-907e-6c8357a40c75)

And this one:

![Screenshot 5784-02-23 at 13 25 24](https://github.com/WWBN/AVideo/assets/58882903/d3f6d856-5fac-4507-b529-fbb73d04a851)

**Comment by guymass** [comment]
Also I see an error with the Thumbnail plugin:

![Screenshot 5784-02-23 at 13 34 42](https://github.com/WWBN/AVideo/assets/58882903/c00db10b-71ef-4b70-8709-073f9143a726)

**Comment by guymass** [comment]
Its seems all related to my network encoder, when it gets stuck for some reason the entire site gets stuck. I see this repeating in my network encoders log:

![Screenshot 5784-02-23 at 15 18 07](https://github.com/WWBN/AVideo/assets/58882903/2291101c-b4d2-48e1-a509-0666698e4280)

**Comment by guymass** [comment]
I have very low ping, all domains are also set in hosts file. Here is another error I found:

![Screenshot 5784-02-23 at 15 55 54](https://github.com/WWBN/AVideo/assets/58882903/53d86639-b9e2-4cb6-9bc8-a7bf8dd679ce)

This is my Networks Encoder server. I need tor restart the apache every 10m other wise it gets stuck and causes the entire site to get stuch as well, even when there are no encoding or uploading taking place.

**Comment by DanielnetoDotCom** [comment]
definitely is something in your network.

when it fails check here https://encoders.alive528.com/view/score.php

and at the same time check your logs

**Comment by guymass** [comment]
It gets stuck that I cannot even use CURL:
![Screenshot 5784-02-23 at 16 55 55](https://github.com/WWBN/AVideo/assets/58882903/f8e34519-2b2f-449e-abe1-e4d8040a8f2f)


only after restarting it I see in the log this:

[Tue Nov 07 14:56:16.653065 2023] [proxy_fcgi:error] [pid 63789:tid 139910547670720] [remote 147.235.213.143:2156] AH01071: Got error 'PHP message: PING ==> fileAge = 2 AND lifetimeSeconds = 30', referer: https://encoders.alive528.com/?webSiteRootURL=https%3A%2F%2Falive528.com%2F&user=eitanwa&pass=_user_hash_V3FxQi9HMEg1QW1sWmE4ZnQ2ZDE1a09ROE5NdXE0VWxNeG1ucWFNcUo5RWhBQ0YvNHZwckFDRzV1Y0tIc0hNdFZSQm4vd0dqMEtaMVJmdmNEZmdQQ3c9PQ%3D%3D&encodedPass=1&justLogin=1&PHPSESSID=v8ejjodp4uh4qqpp06n26cfrge

**Comment by DanielnetoDotCom** [comment]
![image](https://github.com/WWBN/AVideo/assets/18009293/f2561c06-3501-4d2e-a846-7b9a070f45d8)

**Comment by guymass** [comment]
OK here is the output of this, what does it say?

root@localhost:/var/www/html/Encoders/view# php score.php 
PHP Warning:  Undefined array key "SERVER_NAME" in /var/www/html/Encoders/configuration.php on line 10
SCORE ==> fileAge = 35 AND lifetimeSeconds = 60
{"7":{"ping":{"value":0.428,"output":"rtt min\/avg\/max\/mdev = 0.428\/0.428\/0.428\/0.000 ms","addr":{"scheme":"https","host":"encoder1.alive528.com","path":"\/"}},"siteURL":"https:\/\/encoder1.alive528.com\/","serverStatus":{"queue_size":0,"concurrent":1,"is_encoding":false,"queue_list":[],"msg":"There is no file on queue","encoding":[],"cmd":"","encoding_status":[],"version":"4.0","downloaded":[],"transferring":[],"memory":{"command":"free","output":["               total        used        free      shared  buff\/cache   available","Mem:         8123176     1740252     1750064      134896     5150760     6382924","Swap:        8388604           0     8388604"],"memTotalBytes":8318132224,"memUsedBytes":1782018048,"memFreeBytes":1792065536,"success":1,"memTotal":"7.75GB","memUsed":"1.66GB","memFree":"1.67GB","percent":21,"title":"Total: 7.75GB | Free: 1.67GB | Used: 1.66GB"},"file_upload_max_size":"3.91GB"}},"8":{"ping":{"value":0.021,"output":"rtt min\/avg\/max\/mdev = 0.021\/0.021\/0.021\/0.000 ms","addr":{"scheme":"https","host":"encoder2.alive528.com","path":"\/"}},"siteURL":"https:\/\/encoder2.alive528.com\/","serverStatus":{"queue_size":0,"concurrent":1,"is_encoding":false,"queue_list":[],"msg":"There is no file on queue","encoding":[],"cmd":"","encoding_status":[],"version":"4.0","downloaded":[],"transferring":[],"memory":{"command":"free","output":["               total        used        free      shared  buff\/cache   available","Mem:         4000580      806408     2929716        5624      498100     3194172","Swap:         524284           0      524284"],"memTotalBytes":4096593920,"memUsedBytes":825761792,"memFreeBytes":3000029184,"success":1,"memTotal":"3.82GB","memUsed":"787.51MB","memFree":"2.79GB","percent":20,"title":"Total: 3.82GB | Free: 2.79GB | Used: 787.51MB"},"file_upload_max_size":"4.00GB"}}}root@localhost:/var/www/html/Encoders/view#

**Comment by guymass** [comment]
OK in my case I found that my network encoders server causes at times the site to slow down because it hangs for some reason I still cannot figure out. Nothing really shows in the logs and apache status seems that it is running, but it doesn't load my encoders and this causes the entire site to just hang as well while simply browsing. So my solution was to set a crontab to restart apache server every 30min as a start and for now this seems to hold quite well. 

Maybe the Networks Encoder script hasn't been updated or revised in a while IDK. For now I will close this issue.
