### ISSUE TITLE
Network Encoder Errors in Network console

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8622]
![Screenshot 5784-02-28 at 17 28 19](https://github.com/WWBN/AVideo/assets/58882903/c30a6d13-f45d-485a-9c91-02bd235fb6b7)

I see that serverStatus.php and getTime.json.php have errors. Can you please elaborate more about them, what may cause this and how I can fix this.

**Comment by DanielnetoDotCom** [comment]
first you need to show what error code it is
