### ISSUE TITLE
Make Live Links playable on Twitter

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8630]
Right now when you share a live link this is what it looks like
![image](https://github.com/WWBN/AVideo/assets/39392449/4de0aa4c-e8fc-466b-a7a2-9a7c72ee6872)

https://www.joshwhotv.com/liveLink/296/joshwho-truth-intel-tv-seekingthetruth-live-stream-%7C-come-hang-out

Now I figured out how to make it playable was to Embed the live stream Like a regular video embed from a external site and it does work like that

![image](https://github.com/WWBN/AVideo/assets/39392449/1d1a7284-624b-4b00-97ff-979456540bfc)
![image](https://github.com/WWBN/AVideo/assets/39392449/d8744b78-afd1-432f-92b2-8f80a9a4bed5)
https://www.joshwhotv.com/channel/SeekingTheTruth/video/86514/%F0%9F%94%B4%F0%9F%8C%90joshwho-tv-%F0%9F%93%BA%7C-news-your-gov-is-a-liar-%F0%9F%95%B5%EF%B8%8F%E2%80%8D%E2%99%82%EF%B8%8F-a-channel-for-intelligent-people.-expand-your-mind.-%7C-seekingthetruth-live-24-7

**Comment by JoshWho** [comment]
Perfect Looks great now. 

Live STream I just tested and it has this error 
![image](https://github.com/WWBN/AVideo/assets/39392449/9cfb825f-7709-46a8-8670-8c71260fae86)
INFO:  Page fetched successfully
INFO:  33 metatags were found
INFO:  twitter:card = player tag found
ERROR: Possibly invalid value (if specified) (twitter:title)
ERROR: Possibly invalid value (if specified) (og:title)
ERROR: Possibly invalid value (if specified) (twitter:text:title)

and that is with this stream currently going https://www.joshwhotv.com/live/1/Newstimelive/1

**Comment by DanielnetoDotCom** [comment]
Please try now

**Comment by JoshWho** [comment]
Looks good now. Thank you
