### ISSUE TITLE
Save category detail remove logo and banner configuration

### ISSUE THREAD

**Issue by paolosim** [WWBN/AVideo#8634]
**Describe the bug**
If you save the category details with the save button in the Metadata and User Groups tab, the logo and banner in the first tab are deleted. If you save in the first tab, the banner and logo remain. Other settings are always saved correctly.

**To Reproduce**
View images.

**Expected behavior**
Don't miss logo and banner settings

**Screenshots**
![1](https://github.com/WWBN/AVideo/assets/62661600/8840fe10-2daa-4a0e-951d-e81d312f28cc)
![2](https://github.com/WWBN/AVideo/assets/62661600/29a6fba7-8efc-415a-a830-da5de477df0c)
![3](https://github.com/WWBN/AVideo/assets/62661600/f6d8c385-2e72-4abd-802a-10d2dcdc9f3d)

Version 14.0

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by paolosim** [comment]
Fixed. Thank you! 
--------------------
Paolo Simontacchi
Project Manager Sistemi
A VIA PALMANOVA 28 – MILANO – 20132
T 02 26161226 – 331 6746810
VOIP 64 4226
***@***.***
-------- Messaggio originale --------
Da: Daniel Neto
Data: mar 14 nov 2023, 19:29
A: WWBN/AVideo
Cc: paolosim , Author
Oggetto: Re: [WWBN/AVideo] Save category detail remove logo and banner configuration (Issue #8634)


Attenzione: Questa email arriva da un mittente insolito.
Attenzione: Assicurati che sia qualcuno di cui ti fidi.

Please check this update

-- 
Reply to this email directly or view it on GitHub:
 https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2FWWBN%2FAVideo%2Fissues%2F8634%23issuecomment-1810893762&e=dbae357a&h=9da06ab5&f=y&p=n 
You are receiving this because you authored the thread.

Message ID: ***@***.***>



Questo messaggio e-mail ed i suoi allegati sono formati 
esclusivamente per il destinatario. Tutte le informazioni ivi contenute sono da 
ritenersi esclusivamente confidenziali e riservate secondo quanto stabilito dal 
vigente D.Lgs. 196/2003 e s.m.i. in materia di privacy e del Regolamento europeo 
679/2016 GDPR. Ogni revisione, uso, diffusione o distribuzione non autorizzata 
sono quindi vietati. Se avete ricevuto questo messaggio per errore, vi preghiamo 
di distruggerlo e di informarci immediatamente inviando un messaggio 
all indirizzo e-mail ***@***.*** .

This e-mail message including any attachments is for the sole use of the 
intended recipient and may contain confidential and privileged information 
pursuant to Legislative Decree 196/2003 and the European General Data Protection 
Regulation 679/2016 GDPR. Any unauthorized review, use, disclosure or 
distribution is prohibited. If you have received this e-mail in error please 
destroy any copies and delete it from your computer system, then inform us 
immediately sending a message to ***@***.***
