### ISSUE TITLE
Infinite scroll & pagination does not work on different Port

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#8636]
HI Dan,

Infinite scroll & pagination does not work for port 8080 (my clone).... the script points to port 80

Example

http://media.beesel-reuver.nl:8080/

The next page is referring to:

http://media.beesel-reuver.nl/page/2/?rowCount=20&current=2  (missing port)

**Comment by DanielnetoDotCom** [comment]
Where are you clicking to get this URL?

can you please share your videos/configuration.php (hide the credentials)

**Comment by TLCReuver** [comment]
I have the clone online now, you can test it..

![Snap8](https://github.com/WWBN/AVideo/assets/39981177/1f25bf32-fa6b-4b80-b0a2-2629ba4b44ca)


<?php
$global['configurationVersion'] = 3.1;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
$global['disableTimeFix'] = 0;
$global['logfile'] = '//var/www/html/media.beesel-reuver.nl/videos/avideo.log';
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { 
    // get the subdirectory, if exists
    $file = str_replace("\\", "/", __FILE__);
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), $file);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'http://media.beesel-reuver.nl:8080/';
}
$global['webSiteRootURL'] = 'http://media.beesel-reuver.nl:8080/';
$global['systemRootPath'] = '//var/www/html/media.beesel-reuver.nl/';
$global['salt'] = '=============';
$global['enableDDOSprotection'] = 0;
$global['ddosMaxConnections'] = 40;
$global['ddosSecondTimeout'] = 5;
$global['strictDDOSprotection'] = 0;
$global['noDebug'] = 0;
$global['webSiteRootPath'] = '';
if(empty($global['webSiteRootPath'])){
    preg_match('/https?:\/\/[^\/]+(.*)/i', $global['webSiteRootURL'], $matches);
    if(!empty($matches[1])){
        $global['webSiteRootPath'] = $matches[1];
    }
}
if(empty($global['webSiteRootPath'])){
    die('Please configure your webSiteRootPath');
}
$global['webSiteRootPath'] = 'http://media.beesel-reuver.nl:8080/';

$mysqlHost = 'localhost';
$mysqlUser = '8888';
$mysqlPass = '888888';
$mysqlDatabase = 'youPHPTube';

/**
 * Do NOT change from here
 */

require_once $global['systemRootPath'].'objects/include_config.php';

**Comment by DanielnetoDotCom** [comment]
Replace this

````php
if(!empty($_SERVER['SERVER_NAME']) && $_SERVER['SERVER_NAME']!=='localhost' && !filter_var($_SERVER['SERVER_NAME'], FILTER_VALIDATE_IP)) { 
    // get the subdirectory, if exists
    $file = str_replace("\\", "/", __FILE__);
    $subDir = str_replace(array($_SERVER["DOCUMENT_ROOT"], 'videos/configuration.php'), array('',''), $file);
    $global['webSiteRootURL'] = "http".(!empty($_SERVER['HTTPS'])?"s":"")."://".$_SERVER['SERVER_NAME'].$subDir;
}else{
    $global['webSiteRootURL'] = 'http://media.beesel-reuver.nl:8080/';
}
````
with this

````php
$global['webSiteRootURL'] = 'http://media.beesel-reuver.nl:8080/';
````
also remove the extra slash `/`
so your config will be 

````php
$global['configurationVersion'] = 3.1;
$global['disableAdvancedConfigurations'] = 0;
$global['videoStorageLimitMinutes'] = 0;
$global['disableTimeFix'] = 0;
$global['logfile'] = '/var/www/html/media.beesel-reuver.nl/videos/avideo.log';
$global['webSiteRootURL'] = 'http://media.beesel-reuver.nl:8080/';
$global['webSiteRootURL'] = 'http://media.beesel-reuver.nl:8080/';
$global['systemRootPath'] = '/var/www/html/media.beesel-reuver.nl/';
...
````

**Comment by TLCReuver** [comment]
Replaced configuration.php with the new one, cleared Avideo cache & browser cache but it is still missing port 8080

![Snap9](https://github.com/WWBN/AVideo/assets/39981177/3cdf66fd-3b21-4ee2-b9a0-e71aabd187f4)

http://media.beesel-reuver.nl/page/2/?rowCount=20&current=2

It has to be : http://media.beesel-reuver.nl:8080/page/2/?rowCount=20&current=2

**Comment by DanielnetoDotCom** [comment]
Sorry currently I have no clue what is causing it

**Comment by DanielnetoDotCom** [comment]
Hold on, I got something.

**Comment by DanielnetoDotCom** [comment]
Try this update

**Comment by TLCReuver** [comment]
Okay its working now but  page  2, 3, 4 etc. are the same as page 1

Load More is working perfect now.

**Comment by DanielnetoDotCom** [comment]
can you please try this?

**Comment by TLCReuver** [comment]
Okay, both working perfect now

Th@nkz
