### ISSUE TITLE
End all Streams error

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8637]
![image](https://github.com/WWBN/AVideo/assets/39392449/8e3c9a1d-0eef-486a-9dfe-8e93732c47db)

![image](https://github.com/WWBN/AVideo/assets/39392449/98fc5963-d1d8-4807-ab4a-a8b567a5488c)

I see a lot of weird things in the log but nothing relating to this.

**Comment by DanielnetoDotCom** [comment]
It should be good now

**Comment by JoshWho** [comment]
Thank you
