### ISSUE TITLE
Error subscription plan

### ISSUE THREAD

**Issue by rapiz** [WWBN/AVideo#8641]
<img width="1223" alt="image" src="https://github.com/WWBN/AVideo/assets/7936334/c0fc458a-b8ef-4232-8f96-c16889593597">
<img width="1219" alt="image" src="https://github.com/WWBN/AVideo/assets/7936334/05e0e959-85f6-4b77-92e8-760f9f7e3238">

Error to access to a video with an without subscription user (suscription pluggin are updated)

Before updating, the subscription plans were displayed.

**Comment by rapiz** [comment]
The problem is in path, if you removed /channel/XXXX/ the subscription plans are displayed. Can fix this?

**Comment by DanielnetoDotCom** [comment]
/channel/XXXX/ is required, but can you please check this update?

**Comment by rapiz** [comment]
Solved
