### ISSUE TITLE
Can't upload new videos!

### ISSUE THREAD

**Issue by rapiz** [WWBN/AVideo#8648]
After the last update, uploading videos does not work. Before in My videos, you could see the progress, now you don't. And when the Encoder ends, the video remains in state "I" but it does not even appear in the lists

First in new version AVideo
<img width="1221" alt="image" src="https://github.com/WWBN/AVideo/assets/7936334/e4c4e538-a41d-4b43-b49a-d2aee09312da">
<img width="1267" alt="image" src="https://github.com/WWBN/AVideo/assets/7936334/7c30f90b-d885-433d-a014-cd64e8282fe7">

**Comment by DanielnetoDotCom** [comment]
i means inactive. it does not seem an error to me

**Comment by DanielnetoDotCom** [comment]
order can be null, and there is no problem

**Comment by rapiz** [comment]
I just uploaded a video to "https://demo.avideo.com/" and the same thing happens, it does not appear, I see that an image appears in shorts but it does not appear in the list of videos nor can it be played

<img width="283" alt="image" src="https://github.com/WWBN/AVideo/assets/7936334/ebe78236-bcd4-4b91-85fd-75a66dcf4d61">

<img width="1241" alt="image" src="https://github.com/WWBN/AVideo/assets/7936334/73f8e464-83cb-4ec2-91de-4665fb78535b">

**Comment by DanielnetoDotCom** [comment]
the video is there

![chrome-capture-2023-10-16 (1)](https://github.com/WWBN/AVideo/assets/18009293/0cc3b5ed-b650-4c4c-b4d0-15e10f335c6c)

**Comment by rapiz** [comment]
The problem was in the "video shorting" deleting that (thanks to your video) they already appear!
