### ISSUE TITLE
BUG videos_id is empty 

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8653]
@DanielnetoDotCom I have been facing Usability problems on the platform for a long time. UX and UI, I see that this is not a concern in development.

For example, I have a serious problem. When the user accesses a video without login, it presents an error without any logic. With a text that cannot be interpreted by a human being! This is something that goes beyond all usability and user interactivity standards. This greatly reduces the quality of the platform and denotes unprofessional work in this regard. I receive many access complaints due to these errors.

![image](https://github.com/WWBN/AVideo/assets/37880073/1784365e-a540-4aa2-a1f2-f7335ba7d33b)

What I realize is that I'm the only admin who uses the closed platform. Because I don't see anyone complaining about these access bugs. Am I going the wrong way?

https://github.com/WWBN/AVideo/assets/37880073/0900b11e-5571-4f8e-8d61-f402681042cc

**Comment by DanielnetoDotCom** [comment]
Are you running the last update? I guess last Friday I sent updates regarding this

**Comment by gbrn** [comment]
I was running the update Update cc09186c0e and now: 25586a0e37.
This problem is now resolved.
