### ISSUE TITLE
I created a new site and used the backup plugin. The newly restored site is missing many images.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8679]
**Describe the question**
Using the "backup" plugin to restore the videos directory, I observed that it was failing to uncompress the entire videos directory (75GB); it "stalled out" at 21GB (ps -ax revealed no tar process runnong), so I restarted it and it "stalled out" (ps -ax again revealed that "tar" had stopped running) at 68GB, so I transferred the entire "videos" directory with scp and the cloned site is still missing many video images.

How could we clone the site in a way that it copies all of the videos/images?

**Screenshots**
![Screenshot 2023-11-29 at 11 30 06 AM](https://github.com/WWBN/AVideo/assets/11711050/da264020-1ce7-454a-8110-09410bdcbee6)

It looks like the data is there & it should be working. Let's go to the first video's page and inspect it (page is https://iv.conspyre.tv/video/17324/c771dbbd-d8fc-4c9f-9ba1-e0782e1b0ae9.mp4):

![Screenshot 2023-11-29 at 2 16 42 PM](https://github.com/WWBN/AVideo/assets/11711050/8eb83ad1-62ff-4fd4-9897-2d0099b2be92)

Looks like the video is there and we get the placeholder image. Ok the video is called v_231119034712_v84ca - lets check it

```
cd /var/www/html/conspyre.tv/videos/v_231119034712_v84ca
ls -ls 
total 1976
620 -rw-r--r-- 1 www-data www-data 634307 Nov 29 10:58 v_231119034712_v84ca.gif
 96 -rw-r--r-- 1 www-data www-data  96304 Nov 29 10:58 v_231119034712_v84ca.jpg
352 -rw-r--r-- 1 www-data www-data 357674 Nov 29 10:58 v_231119034712_v84ca.png
132 -rw-r--r-- 1 www-data www-data 133900 Nov 29 10:58 v_231119034712_v84ca.webp
  4 -rw-r--r-- 1 www-data www-data     10 Nov 29 10:58 v_231119034712_v84ca_1080.mp4
 12 -rw-rw-r-- 1 www-data www-data   8308 Nov 29 10:58 v_231119034712_v84ca_128.jpg
 16 -rw-rw-r-- 1 www-data www-data  15308 Nov 29 10:58 v_231119034712_v84ca_192.jpg
 24 -rw-rw-r-- 1 www-data www-data  22700 Nov 29 10:58 v_231119034712_v84ca_256.jpg
 44 -rw-rw-r-- 1 www-data www-data  42235 Nov 29 10:58 v_231119034712_v84ca_384.jpg
 64 -rw-rw-r-- 1 www-data www-data  63501 Nov 29 10:58 v_231119034712_v84ca_512.jpg
  8 -rw-rw-r-- 1 www-data www-data   5894 Nov 29 10:58 v_231119034712_v84ca_96.jpg
248 -rw-rw-r-- 1 www-data www-data 252091 Nov 29 10:58 v_231119034712_v84ca_roku.jpg
248 -rw-r--r-- 1 www-data www-data 250688 Nov 29 10:58 v_231119034712_v84ca_thumbsSprit.jpg
 88 -rw-rw-r-- 1 www-data www-data  88371 Nov 29 10:58 v_231119034712_v84ca_thumbsV2.jpg
 20 -rw-r--r-- 1 www-data www-data  17080 Nov 29 10:58 v_231119034712_v84ca_thumbsV2_jpg.webp
```

It is not entirely clear why the videos should have no images; it appears they have all been copied successfully.  To see if any errors are logged, I cleared avideo.log and /var/log/apache2/error.log, then loaded the page. No apache errors are logged and this is all that is in the avideo.log:

```
[29-Nov-2023 17:45:49 America/Lima] AVideoLog::DEBUG: Unmatched image request: apple-touch-icon-precomposed.png SCRIPT_NAME: /view/img/image404.php
[29-Nov-2023 17:45:50 America/Lima] AVideoLog::DEBUG: Unmatched image request: apple-touch-icon.png SCRIPT_NAME: /view/img/image404.php
[29-Nov-2023 17:45:50 America/Lima] AVideoLog::DEBUG: Unmatched image request: /view/img/image404.php?notFound=1 SCRIPT_NAME: /view/img/image404.php
[29-Nov-2023 17:45:50 America/Lima] AVideoLog::DEBUG: Unmatched image request: /view/img/image404.php?notFound=1 SCRIPT_NAME: /view/img/image404.php
```

**Comment by TLCReuver** [comment]
I use daily Backup plugin and have no problems (clone from original)

You can alse export/import in phpMyadmin

![Snap10](https://github.com/WWBN/AVideo/assets/39981177/fbcfe210-9ab6-4c01-b95c-850cb5fbc008)

**Comment by DanielnetoDotCom** [comment]
Not really, I am not sure what happen on your server
