### ISSUE TITLE
Error 500 When I Enable AllowOveride To : All

### ISSUE THREAD

**Issue by RoboD246** [WWBN/AVideo#8683]
**Describe the bug**

**To Reproduce**
1. Go to '[Ubuntu 16.04 AVideo](https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-16.x-For-AVideo-Platform-version-4.x-or-newer)'
2. Copy and Paste into command line 'sudo apt-get install apache2 php7.0 libapache2-mod-php7.0 php7.0-mysql php7.0-curl php7.0-gd php7.0-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube.git && cd /var/www/html && sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube-Encoder.git && sudo apt-get install python && sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && sudo chmod a+rx /usr/local/bin/youtube-dl && sudo a2enmod rewrite'
3. Wait For Install
4. Go to "/etc/apache2/apache2.conf" and enable this 
"<Directory /var/www/>
          Options Indexes FollowSymLinks
          AllowOverride none
          Require all granted
 </Directory>" 
to this 
"<Directory /var/www/>
          Options Indexes FollowSymLinks
          AllowOverride All
          Require all granted
 </Directory>"

**Expected behavior**
AVideo setup and Install screen

**Error Logs** and more...
[Fri Dec 01 18:03:21.734473 2023] [:error] [pid 10745] [client 10.0.2.2:63764] PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/html/YouPHPTube/objects/functions.php on line 2226
This Is the Exact Line that the error happened on : "        public const FILTER_BOX = 1;"
The entire code that line 2226 is apart of is "[PasteBin Link](https://pastebin.com/8DLFPvES)" or if you want a direct link "https://pastebin.com/8DLFPvES"

**Screenshots**
![image](https://github.com/WWBN/AVideo/assets/132953173/48e81c77-da69-4abb-92a0-973506ea0292) I hid the private IP address because of reasons. Just pretend that "Ubuntu Ip Address" is an actual Ip Address.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [22H2]

**Additional context**
I am running on an Virtual Machine, On Virtual Box. I am using Ubuntu Server 16.04.

**Comment by DanielnetoDotCom** [comment]
Avoid Ubuntu 16.

use Ubuntu 20 or 22

also make sure you are using PHP version 7.4 or greater

**Comment by RoboD246** [comment]
I was using Ubuntu 16 to install YouPHPTube because I did not need a domain name, is it still possible to install YouPHPTube on Ubuntu 20 without a domain name? I only want this to run LAN, not public.

**Comment by RoboD246** [comment]
I got it to work! I just installed YouPHPTube for ubuntu 16 on my ubuntu 20 machine, but I just had to change all of the php 7.0 to php 7.4 Thanks!
