### ISSUE TITLE
[BUG] Uncaught TypeError: implode(): Argument #1 ($array) must be of type array, string given in

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#8685]
` [02-Dec-2023 11:43:35 America/Sao_Paulo] AVideoLog::ERROR: {"type":1,"message":"Uncaught TypeError: implode(): Argument #1 ($array) must be of type array, string given in \/var\/www\/html\/AVideo\/view\/modeYoutube.php:85\nStack trace:\n#0 \/var\/www\/html\/AVideo\/view\/modeYoutube.php(85): implode()\n#1 \/var\/www\/html\/AVideo\/plugin\/PlayLists\/PlayLists.php(1121): include('...')\n#2 \/var\/www\/html\/AVideo\/plugin\/PlayLists\/PlayLists.php(973): PlayListPlayer->checkPlayMode()\n#3 \/var\/www\/html\/AVideo\/plugin\/PlayLists\/player.php(11): PlayListPlayer->__construct()\n#4 {main}\n  thrown","file":"\/var\/www\/html\/AVideo\/view\/modeYoutube.php","line":85} SCRIPT_NAME: /plugin/PlayLists/player.php`

**Comment by gbrn** [comment]
I'm getting this message several times.

**Comment by DanielnetoDotCom** [comment]
Please try this update
