### ISSUE TITLE
Pagination does not work properly in Categories (Infinite scroll solved)

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#8688]
Hi Dan,

When you are **not logged in** Infinite Scroll & LoadMore in **_Categories_** show only the content of the first page also when you select next page or use 'Load More' button. It is very strange that it is not working randomly. When you are **logged in** it work properly.

You can test it on:

https://archief.beesel-reuver.nl/cat/112-nood-
https://ourtube.co.uk/cat/autos-vehicles
https://www.joshwhotv.com/cat/news

**Comment by DanielnetoDotCom** [comment]
Just tested in https://www.joshwhotv.com/cat/news and it works fine for me

**Comment by TLCReuver** [comment]
Hi Dan,

I just tested but see something else on https://www.joshwhotv.com/cat/news  (seeing it double, like picture of Trump & Date)

![_FireShot Webpage Capture 009 - 'News · JoshWho TV - Free Speech TV and Media · news · JoshWho TV - Free Speech TV and Media' - www joshwhotv com](https://github.com/WWBN/AVideo/assets/39981177/8642cd01-326a-4e8f-b98d-2346de6ccbb1)

**Comment by TLCReuver** [comment]
>> Pagination will only change if you click on the pagination menu

I know, here are screenshots from Page 1 & 2

**Page 1**

![_Page_1](https://github.com/WWBN/AVideo/assets/39981177/aa0af833-97f3-4ec9-848a-55e520764201)

**Page 2**

![_Page_2](https://github.com/WWBN/AVideo/assets/39981177/6508ec33-67c2-489e-94e2-f792dc209ea2)
