### ISSUE TITLE
Problem with get jpeg/gif not working with long videos

### ISSUE THREAD

**Issue by TheCableGuy99** [WWBN/AVideo#8689]
**Describe the bug**
When I click to "get jpeg/gif for thumbnails/videos in the "My Videos" section it doesn't seem to work with long videos. It will grab an image but it grabs the same thing. See this screenshot:

![Screenshot 2023-12-04 083309](https://github.com/WWBN/AVideo/assets/39552752/66b24fcb-08b0-46e3-90a3-0a4242873c2b)

I don't know if it needs longer to look through the video when it's a longer one but for whatever reason it's not working on this video which is well over 2 hours long.

**To Reproduce**
Upload a video over 2 hours long
Go to "My Videos"
Click "Get jpeg/gif"
See thumbnails

**Expected behavior**
Different thumbnails

**Comment by DanielnetoDotCom** [comment]
Hi, your screenshot has a 2:12:54 video and it seems to be working. 

what exactly do you mean does not work?

**Comment by TheCableGuy99** [comment]
Well it's a new site and i've done many shorter videos which are fine. I've also re-uploaded this many times and it's the same every time so I can only assume it's on long videos yes.

**Comment by TheCableGuy99** [comment]
Do you have any instructions on how to update the encoder please?

**Comment by DanielnetoDotCom** [comment]
Use `git pull`, just like the streamer

**Comment by TheCableGuy99** [comment]
> Sorry this is the wrong thread, please ignore it and remove the code

Code removed, thanks

**Comment by TheCableGuy99** [comment]
> try to add a custom CSS
> 
> https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript
> 
> ```css
> #mainFooter{
> 	background-color: black;
> }
> ```

I've updated both the encoder now and the plugin but the issue is exactly the same. I don't even think it's searching the video and it comes up pretty much instantly with the same image. I have also selected "delete thumbnails" first for the video to be sure.

**Comment by TheCableGuy99** [comment]
Okay that's fixed it thank you! It does just come up with a white screen for a little white whilst going through the video so maybe in the future you could make it appear like it's loading rather than a blank white screen? Just a suggestion. Also it would be nice to select other parts of the video in case none of the ones that appear are suitable?

There is another issue though....

When I select the default front page the thumbnails don't load properly. I really want to use this front page as well because it's the most like YouTube's. Please see this screenshot where it loads the very top of the thumbnails but 99% is missing.
![Screenshot 2023-12-04 165455](https://github.com/WWBN/AVideo/assets/39552752/b46df129-007f-4439-90fd-98d0c500271b)

Thanks again.

**Comment by DanielnetoDotCom** [comment]
that is weird, can you reproduce that on demo site?

https://demo.avideo.com/

I need to be able to reproduce that, otherwise I cannot help

**Comment by TheCableGuy99** [comment]
I've resolved this by deleting the thumbnails and they were re-generated.
