### ISSUE TITLE
Struggling with "SecureVideosDirectory" Plugin and need a helping hand

### ISSUE THREAD

**Issue by TheCableGuy99** [WWBN/AVideo#8690]
**Describe the question**
To the best of my knowledge this plugin should secure the true location of a video so users cannot just go grab it... is this correct?

If so, something is not working as I can open a new browsers and just go direct to the video @:
https://cdn.mydomain.com/video_231201015759_va987_720.mp4

Then the video plays outside the website.

I have done as the instructions suggest here:
https://github.com/WWBN/AVideo/wiki/Moving-videos-directory-and-securing-files-from-direct-access-to-the-video-source-file

But I can still access it directly. What could I be missing or is this a bug?

**Comment by DanielnetoDotCom** [comment]
the main thing is to make sure the [xsendfile ](https://github.com/WWBN/AVideo/wiki/Moving-videos-directory-and-securing-files-from-direct-access-to-the-video-source-file#install-apache-xsendfile) is correctly installed

![image](https://github.com/WWBN/AVideo/assets/18009293/52e7ac21-2aba-4679-85c0-c37141ae6f65)

when you test it use an incognito window. 

Make sure you have the "Enable Token on Videos URL" checked

![image](https://github.com/WWBN/AVideo/assets/18009293/7272e8b6-e8ef-481f-8924-0ffaadadb370)

**Comment by DanielnetoDotCom** [comment]
With this plugin, you still can find the link, but you should only be able to download it with the key. but it is more effective to avoid embedding. 

if you really want to protect the download you should try VideoHLS https://github.com/WWBN/AVideo/wiki/VideoHLS-Plugin#download-protection

combine VideoHLS  + SecureVideosDirectory to prevent download and embedding.

**Comment by DanielnetoDotCom** [comment]
Sorry there is no refund for digital contents

and yes it works

check this video https://demo.avideo.com/video/388/mp4-jimmy-s-java---pilar-s-empanadas

try this direct link https://demoavideocom.cdn.ypt.me/videos/video_220822141910_vcd96/video_220822141910_vcd96_1080.mp4

then this one with the token 
https://demoavideocom.cdn.ypt.me/videos/video_220822141910_vcd96/video_220822141910_vcd96_1080.mp4?token=eyJzYWx0IjoiaHR0cHM6XC9cL2RlbW8ueW91cGhwdHViZS5jb21cLyIsInRva2VuVGltZU91dCI6IjIxNjAwIiwiZmlsZW5hbWUiOiJ2aWRlb18yMjA4MjIxNDE5MTBfdmNkOTZfMTA4MCIsInRpbWUiOjE3MDE3MTI5MTF9

**Comment by TheCableGuy99** [comment]
Okay firstly, mine isn't even giving a token to the link in the source, it's just giving the direct URL so something is not working.

Secondly how is that protecting a file? I was able to go directly to the video page, look at the source, copy the URL with the token in there and paste it into a new windows and save the file. There's no protection at all if you can just add the publicly available token to the end.

Unless you can offer what you said it offers "Deny direct access to the video source file" then it's false advertising and I will put in a paypal dispute. It does not work even with your above example!

**Comment by TheCableGuy99** [comment]
Firstly I've not got the cache plugin loaded.

If you are going to advertise something as "Deny direct access to the video source file" then that's what I expect it to do. I don't expect you to say, "you need to buy something else to make it work and then it still won't work 100%". 

Then when I question it you and want a refund on a single one of 6 plugins I purchased costing me in the region of $150 for all of them you say I can't have one and if I question it with paypal I should find another video solution.... WOW, just WOW.

I'll offer you one last chance to give me a refund on this one plugin that doesn't work and if not I'll be raising a dispute for ALL plugins I've purchased from you because if you're forcing me to use another video solution, I'll do just that and want my money back for plugins purchased as won't be able to use them.

You can't advertising something to do something, when it doesn't do it say you can't have a refund! That's illegal!

**Comment by DanielnetoDotCom** [comment]
Please proceed as you think is right,  you know the rules that I do not refund. the plugin is working. Please do what you believe is the correct behavior as the agreement is clear

I will close this topic because GitHub issues are not the ideal place for this discussion.
