### ISSUE TITLE
Help changing colour of the footer banner

### ISSUE THREAD

**Issue by TheCableGuy99** [WWBN/AVideo#8691]
Can anyone help me change the colour of this banner for the footer please?

I have the customize plugin but still can't see how to do it.

**Comment by TheCableGuy99** [comment]
Hi,

I just want to change the background colour to something darker so the text in the footer is more visible. White/cream that it currently is doesn't really go with the rest of the sites theme.

**Comment by DanielnetoDotCom** [comment]
try to add a custom CSS

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript

```html
<style>
#mainFooter{
	background-color: black;
}
</style>
```

**Comment by DanielnetoDotCom** [comment]
yes, it is possible, but I cannot help you with your CSS customization. try to google to learn some CSS
