### ISSUE TITLE
Incorrect download link

### ISSUE THREAD

**Issue by TheCableGuy99** [WWBN/AVideo#8692]
**Describe the bug**
After creating a backup with the Backup plugin there is a download link. However the link is incorrect, it takes you to:
https://my.domain.com/plugin/Backup/backupDir/videos-2023-12-04-07-443e5edsf3fdf43f49573ea4f37f5c18d2.tgz

However in the URL the "backupDir" is not the backup dir. I'm guessing there's something in the plugin which should insert the actual backup directory here instead?

**To Reproduce**
Create a backup with the backup plugin and click to download it.

**Expected behavior**
It should start downloading the backup instantly when clicking the button.

Another couple of questions I have about this plugin that don't make sense to make if you wouldn't mind taking the time to answer them please because there's nothing in the documentation about them...

1) What does the "key" do? It comes across as a password but as I can just extract it without a password it's clearly not that?
2) Can I store the backups on a remote drive?
3) Can the backups be set to do so many iterations then overwrite themselves? I doubt this is a feature but it would be a great one so backups are not just taking up huge amounts of space if you don't have time to keep coming back and deleting older ones.

Thanks.

**Comment by TheCableGuy99** [comment]
Okay, i just thought it was supposed to link to whatever directory I set, or what's the point of being able to set it? But that's cool, i'll set a symlink.

Any comment on my other questions please? 

Thank you!

**Comment by TheCableGuy99** [comment]
Okay I've just moved the custom named folder back and the link works now but as said I don't see the point of allowing us to specify the backup directory if the link to it doesn't reflect that. Surely that a simple fix for a future update?

In regards to the "key" I was referring to it is the "authKey" you can specify in the settings here:
![Screenshot 2023-12-04 161542](https://github.com/WWBN/AVideo/assets/39552752/f976e292-f669-477c-b4ed-56a2eb0ac3bb)

What is this for exactly please? It's not documented.

I'll look into the clone feature, thanks but something to delete older backups would be nice to be written into the script as it's part of backup management.

Thanks!

**Comment by DanielnetoDotCom** [comment]
I will review it in the future, for now just use the default

**Comment by TheCableGuy99** [comment]
Thank you but you still have not said what the authkey is for?

**Comment by DanielnetoDotCom** [comment]
auth key is that allows you to add a crontab to automatically make a backup, also you can allow external scripts requests to back it up

![image](https://github.com/WWBN/AVideo/assets/18009293/55dca296-1fb4-4800-bed7-918d574db872)

**Comment by TheCableGuy99** [comment]
I see, thank you. I'll close this now as well.
