### ISSUE TITLE
Error: Git Pull did not send all necessary objects

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8702]
Been trying to update my site running git pull I get an error saying :

fatal: bad object refs/remotes/origin/dependabot/compose/aws/aws-sdk-php-3.293.2

error: https://github.com/WWBN/AVideo.git did not send all necessary objects.

**Comment by GreenDragonTavern** [comment]
@guymass - If still having issues, try this after navigating to AVideo directory:

```
sudo git fetch --all && sudo git reset --hard origin/master
```

**Comment by guymass** [comment]
Tried that as well but still it doesn't allow me. This is a VM I setup on MXLinux version which is a debian, its the only one causing me this issue so it could be system related idk. Currently the only way I was able to update is to clone it to a separate directory and copy the files. 

This could be just on my side so I will keep troubleshooting it on google as this is not AVideo related.
