### ISSUE TITLE
Site completely broke after last git pull

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#8703]
@DanielnetoDotCom 
![Screenshot_20231205_174359_Chrome](https://github.com/WWBN/AVideo/assets/70327833/3de3fa81-7002-4dee-b4aa-839f84027fed)

**Comment by DanielnetoDotCom** [comment]
Check this

https://github.com/WWBN/AVideo/issues/8701

In summary, manually delete the plugin SendRecordedToEncoder and download the new version and upload it

**Comment by milehighkaraoke** [comment]
Thank you!
