### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by GamerAcchin1234** [WWBN/AVideo#8707]
It's giving me an error on my YouPHPTube, I created a virtual machine on Windows and the error is Unknown error, and how can I solve.

**Comment by GamerAcchin1234** [comment]
I have ubuntu on windows

**Comment by GamerAcchin1234** [comment]
my ubuntu version is 22.04.3

**Comment by GamerAcchin1234** [comment]
![Captura de tela 2023-12-07 210915](https://github.com/WWBN/AVideo/assets/144597625/81e5b2be-cd11-49f2-a6e5-10cb7217e3a4)

**Comment by GamerAcchin1234** [comment]
ok

**Comment by GamerAcchin1234** [comment]
how do I check the apache log and how do I solve it

**Comment by DanielnetoDotCom** [comment]
Sorry I cannot teach that but for sure you can find it on google

**Comment by GamerAcchin1234** [comment]
what do I search

**Comment by GamerAcchin1234** [comment]
speak soon

**Comment by DanielnetoDotCom** [comment]
Given the technical nature of the installation process and the specific expertise required, it might be more efficient and effective for you to consider professional assistance. In this regard, Sorry but I cannot teach you how or what to google.

**Comment by GamerAcchin1234** [comment]
ok

**Comment by DanielnetoDotCom** [comment]
https://letmegooglethat.com/?q=how+to+find+apache+error+log+on+ubuntu+

**Comment by GamerAcchin1234** [comment]
![Captura de tela 2023-12-08 205822](https://github.com/WWBN/AVideo/assets/144597625/d6cd0d93-9497-4799-aab9-8718dfe4906d)

**Comment by GamerAcchin1234** [comment]
![Uploading Captura de tela 2023-12-08 205950.png…]()

**Comment by GamerAcchin1234** [comment]
![Captura de tela 2023-12-08 205950](https://github.com/WWBN/AVideo/assets/144597625/983647b9-2bf6-481f-8535-0c021e5e68a0)

**Comment by GamerAcchin1234** [comment]
look what's happening

**Comment by DanielnetoDotCom** [comment]
please read your logs

![image](https://github.com/WWBN/AVideo/assets/18009293/23f2c028-ff0b-49a1-a74e-f77c89700d1f)


you added the wrong credentials.

**Comment by GamerAcchin1234** [comment]
I put it right, I still make a mistake 
![Uploading Captura de tela 2023-12-09 130949.jpg…]()

**Comment by GamerAcchin1234** [comment]
![image](https://github.com/WWBN/AVideo/assets/144597625/7c1f1dae-c21c-4f80-b3cb-73369cd9c339)

**Comment by GamerAcchin1234** [comment]
![Captura de tela 2023-12-09 131130](https://github.com/WWBN/AVideo/assets/144597625/cbc1e584-acad-47d4-b05d-2c140ea27c3d)

**Comment by GamerAcchin1234** [comment]
If you have to see it again you would have seen it but I created a database

**Comment by GamerAcchin1234** [comment]
error 
![Uploading Captura de tela 2023-12-09 131449.jpg…]()

**Comment by GamerAcchin1234** [comment]
error again 
![Captura de tela 2023-12-09 131449](https://github.com/WWBN/AVideo/assets/144597625/7510b506-882b-4e8e-a368-ea0b0688ab9e)

**Comment by GamerAcchin1234** [comment]
I put it right, but it gave me an error again

**Comment by DanielnetoDotCom** [comment]
It is your MySQL configuration sorry I cannot help you with that. 

but If you want you can hire me for a clean installation.
you can hire me here https://youphp.tube/marketplace/

I cannot teach you how to install but I can install it for you.

**Comment by GamerAcchin1234** [comment]
ok

**Comment by GamerAcchin1234** [comment]
It's free I don't have money

**Comment by GamerAcchin1234** [comment]
create one for free so I can hire you

**Comment by GamerAcchin1234** [comment]
I will install dnv if an error occurs I will let you know

**Comment by GamerAcchin1234** [comment]
I will install it again if an error occurs I will let you know
