### ISSUE TITLE
Pagination on Categories does not work (also on DemoSite)

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#8712]
Pagination on Categories does not work (also on demosite)

You can check it on: https://demo.avideo.com/cat/default

**Page 1**

![Snap20](https://github.com/WWBN/AVideo/assets/39981177/dc53c0fe-ed5c-4d19-baa6-70f8b56d9036)

**Page 2**

![Snap21](https://github.com/WWBN/AVideo/assets/39981177/29f4f107-28c5-484c-828c-32af1b628b72)

**Comment by DanielnetoDotCom** [comment]
Can you please check this update?

**Comment by TLCReuver** [comment]
Updated & cleared cache but still the same problem Page 1 is same as Page 2,3, etc.

http://media.beesel-reuver.nl:8080/cat/112-nood-
http://media.beesel-reuver.nl:8080/cat/112-nood-/page/2?current=2
http://media.beesel-reuver.nl:8080/cat/112-nood-/page/3?current=3

**Comment by DanielnetoDotCom** [comment]
Please check this update
