### ISSUE TITLE
VR360 doesn't work anymore

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#8713]
VR360° movies does not play anymore. Nothing has been changed with these movies. No log errors.

![Snap22](https://github.com/WWBN/AVideo/assets/39981177/0a3e9b27-3d3a-48a3-be23-5ba4b102bd44)

![Snap14](https://github.com/WWBN/AVideo/assets/39981177/28f119f5-b1b4-41a0-a1da-c9b8d81b4a2a)

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by TLCReuver** [comment]
Update & Clear cache... no rotation possible :(

**Comment by DanielnetoDotCom** [comment]
Please try this now

**Comment by TLCReuver** [comment]
Updated & cleared cache

Sorry, no rotation possible :(

**Comment by DanielnetoDotCom** [comment]
I guess it is not updated. I cannot see the modifications there. can you please try again?

I sent new updates

**Comment by TLCReuver** [comment]
The latest Update did the job... ferfect now. Thankz

![Snap27](https://github.com/WWBN/AVideo/assets/39981177/6433adb9-17e5-439a-a967-c733886ae5f4)
