### ISSUE TITLE
Video embedding seems to hang when trying to add a RUmble video

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8722]
Using this link here https://rumble.com/embed/v3y8mam/?pub=7dth1

![25430523-6d66-40b4-a276-4adfdb57cd0b](https://github.com/WWBN/AVideo/assets/39392449/4bd77208-8bd2-4f62-956f-0e701d9770b6)

Not seeing anything in the log reflecting this.

**Comment by DanielnetoDotCom** [comment]
I tried it locally and works, 

I tried it in 4 different servers and fail in all of them 

```
 yt-dlp   --no-check-certificate --no-playlist --force-ipv4 --skip-download -e 'https://rumble.com/embed/v3y8mam/?pub=7dth1'
ERROR: [RumbleEmbed] v3y8mam: Unable to download JSON metadata: <urlopen error timed out> (caused by URLError(timeout('timed out')))
```

I am think rumble may be blocking something.

**Comment by JoshWho** [comment]
Super weird.
