### ISSUE TITLE
Latest Git Pull automatically plays latest video on home page.

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#8723]
Git pull update now plays latest video on home page, is this expected behavior and if so, how do we disable it?

**Comment by DanielnetoDotCom** [comment]
![image](https://github.com/WWBN/AVideo/assets/18009293/a9ebeeb5-4dcb-44c4-8e96-6401900ec844)

Set it to disable

**Comment by GreenDragonTavern** [comment]
OK, Disable worked. My question is what purpose is below image? Not having a BigVideo should override Big Video Live, yes?

![BigVideo](https://github.com/WWBN/AVideo/assets/85363361/084d7057-0e69-4fcf-b766-b7bd7a5f6aab)

**Comment by DanielnetoDotCom** [comment]
No, you can have the BigVideoLive and also the BigVideo below it

**Comment by GreenDragonTavern** [comment]
Roger that...must be new to latest git pull because don't remember behavior prior. As always, many thanks for your efforts.
