### ISSUE TITLE
Latest videos are on scheduled release

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#8727]
and I can't release them to publish now.
Please advise.
![image](https://github.com/WWBN/AVideo/assets/66537018/0c97c952-f67b-4707-b115-b17efebad16b)

**Comment by fakeologist** [comment]
these are uploaded videos from other sites.

**Comment by DanielnetoDotCom** [comment]
I just sent you updates, can you please try again?

**Comment by fakeologist** [comment]
Seems ol
