### ISSUE TITLE
Missing NEXT preview video 

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#8730]
Hi Dan,

Missing the NEXT video in the right top corner or is it toggled off in settings ?

(This picture is taken from an earlier version)

![Snap12](https://github.com/WWBN/AVideo/assets/39981177/b332f75a-8478-4f4c-887b-9df1a8098410)

**Comment by DanielnetoDotCom** [comment]
Sorry but I can see the next video on my side

![chrome-capture-2023-11-18](https://github.com/WWBN/AVideo/assets/18009293/81930d18-c077-439c-8495-5dbbfde69be6)

**Comment by TLCReuver** [comment]
I'm missing that Auto play toggle & autoplay is enabled in configuration

![Snap14](https://github.com/WWBN/AVideo/assets/39981177/20939c62-71e2-4721-8892-f0e71ce9adb6)

![Snap15](https://github.com/WWBN/AVideo/assets/39981177/6656c4ed-4fce-49d3-861e-5320461b6a63)

![Snap16](https://github.com/WWBN/AVideo/assets/39981177/f8c9cbc8-f903-4f6f-8180-def979ead942)

**Comment by DanielnetoDotCom** [comment]
I am not sure what is happening or how is your configuration. 

![image](https://github.com/WWBN/AVideo/assets/18009293/3e082c3b-aacc-441d-a326-49c98215312b)

Make sure 

showShareAutoplay = checked
forceAlwaysAutoplay = unchecked
