### ISSUE TITLE
PreCache 'first page' after Clear Cache

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#8732]
Maybe a feature to PreCache the 'First Page' after a Clear Cache.

Since a time i use Cron with Bash to clear the cache & precache the 'first page' for Desktop & Mobile.
The website always load in a split second.

#!/bin/bash

sudo rm -f /var/www/html/www.website,com/videos/cache/Desktop.html
sudo rm -f /var/www/html/www.website,com/videos/cache/Mobile.html

cd /var/www/html/website.coml/install/
sudo php /var/www/html/website/install/clearCache.php

wget https://www.website.com -O /var/www/html/www.website.com/videos/cache/Desktop.html

wget --debug --header="User-Agent: Mozilla/5.0 (Android 13; Mobile; rv:120.0) Gecko/120.0 Firefox/120.0" https://www.website.com -O /var/www/html/www.website.com/videos/cache/Mobile.html

**Comment by DanielnetoDotCom** [comment]
the problem on the auto pre-cache first page is that the cache is different depending on the language. depending on the idiom selected the cache will be different

**Comment by TLCReuver** [comment]
Too bad, I hadn't thought about that.
