### ISSUE TITLE
Is this a glitch

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#8734]
Is this live supposed to be showing all the time? Even when offline?
@DanielnetoDotCom 
![Screenshot_20231216_200836_Firefox](https://github.com/WWBN/AVideo/assets/70327833/c837136c-462d-4443-9e7d-d1d53a830506)

**Comment by DanielnetoDotCom** [comment]
No, it is only supposed to load a live video if there is one active. 

if is not active it is supposed to show the latest VOD video. 

I am not sure what is happening on your side

**Comment by milehighkaraoke** [comment]
It will display the first active live stream.  Do I need a certain plugin configured 

This is alli have in log.
18-Dec-2023 15:17:50 America/Denver] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in path/to/my/streamer/site/plugin/YPTSocket/MessageSQLite.php:384

 [18-Dec-2023 15:17:50 America/Denver] PHP Warning:  Undefined array key 341 in path/to/my/streamer/site/plugin/YPTSocket/MessageSQLite.php on line 384

**Comment by DanielnetoDotCom** [comment]
this update should fix the "PHP Fatal error"

but I think it has nothing to do with your question.

**Comment by milehighkaraoke** [comment]
Do I need to be running adaptive bitrate or is there a description I need to enter in my nginx config for the VOD?

**Comment by DanielnetoDotCom** [comment]
Sorry, I am not understanding the issue or your question. 

can you please detail what is the issue you are facing?

**Comment by milehighkaraoke** [comment]
I am asking if I need to make any special c configurations or need a special plugin to make this work? 
![Screenshot_20231216_200836_Firefox](https://github.com/WWBN/AVideo/assets/70327833/39d90085-4d3f-46da-a97b-aa71e324d013)

**Comment by milehighkaraoke** [comment]
The live has always worked properly.. The v o d is not working how do I fix it

**Comment by milehighkaraoke** [comment]
If the live is not working properly, the logs should be picking that up, so can we fix the log so that it picks up all the errors, please?

**Comment by DanielnetoDotCom** [comment]
If you did not install the server properly the error may not be in the logs. 

sorry I do not know your what is your live error

**Comment by milehighkaraoke** [comment]
Are you saying your install from git does not install properly? 
How do we figure this out?

**Comment by DanielnetoDotCom** [comment]
The live server is installed separately, not from git

https://github.com/WWBN/AVideo/wiki/Live-Plugin

https://github.com/WWBN/AVideo/wiki/Set-up-my-own-Stream-Server

**Comment by milehighkaraoke** [comment]
The window displays the first live stream of the day.. After live video is over it shows that it goes offline and it does not display a VOD.  I am actually helping people with their installs. So I would sure like to know what may be wrong so as to not propagate it. 
Thanks

**Comment by DanielnetoDotCom** [comment]
Ok, if the live shows fine, then the live is not an issue. 

if there is no live it will try to get a valid LiveLinks

if there is no LiveLinks then it will try to show a VOD video.

are you using LiveLinks? can you disable it to see if that is the issue?

if you can make a git pull to make sure we have the same version

**Comment by milehighkaraoke** [comment]
Live Links is the issue. I disabled that plugin, logged off, logged on and it is now working 
Thank you

**Comment by DanielnetoDotCom** [comment]
Maybe you have an invalid live link 

Btw live links are working on my side

**Comment by milehighkaraoke** [comment]
Where do I find published live links. I do not ever remember sharing a live link

**Comment by DanielnetoDotCom** [comment]
![image](https://github.com/WWBN/AVideo/assets/18009293/a15eabbb-1939-4f03-8fce-078ead4f89cc)


![chrome-capture-2023-11-20](https://github.com/WWBN/AVideo/assets/18009293/1815f16f-dd46-422f-ba6b-61986d36480d)

**Comment by milehighkaraoke** [comment]
I do not have that option
![Screenshot_20231220_200314_Firefox](https://github.com/WWBN/AVideo/assets/70327833/3ff14af6-c897-4e87-9a22-428441b5053d)

**Comment by DanielnetoDotCom** [comment]
Probably is because you disabled the Live Links plugin

**Comment by milehighkaraoke** [comment]
Yup, ok.... Got it... I deleted the link that was in there and everything is now working great. Thank you
