### ISSUE TITLE
Socket server not working anymore on latest gitpull after reboot

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8752]
I cannot get the socket server to work again. not sure what it is.

**Comment by JoshWho** [comment]
It might be ssl I noticed lets encrypt didn't renew, will right back

**Comment by DanielnetoDotCom** [comment]
Yes, SSL is important. 

also the plugin parameter, SSL location must match. 

![image](https://github.com/WWBN/AVideo/assets/18009293/7214a7d2-eb27-4dab-9f8b-d66d76986ea8)

**Comment by JoshWho** [comment]
I never changed it not sure what or why it would have changed.

**Comment by DanielnetoDotCom** [comment]
I just checked and your socket is working fine now

**Comment by JoshWho** [comment]
Yup I see it. must have just been that.  Thank you for quick response.
