### ISSUE TITLE
Installation configuration seems to stumble upon a include missing _uniqid()

### ISSUE THREAD

**Issue by hevisko** [WWBN/AVideo#8758]
**Describe the bug**
Installation configuration seems to stumble upon a include missing _uniqid()

[Mon Jan 01 16:56:15.331691 2024] [php:error] [pid 24441] [client 102.217.187.117:58478] PHP Fatal error:  Uncaught Error: Call to undefined function _uniqid() in /var/www/html/AVideo/install/checkConfiguration.php:201\nStack trace:\n#0 {main}\n  thrown in /var/www/html/AVideo/install/checkConfiguration.php on line 201, referer: https://video.basuin.web.za/install/index.php

**To Reproduce**
1. Ubuntu 22 installation procedure
2. hitting the "Install configuration" on the website gives error and the above shown in /var/log/apache2/error.log

**Expected behavior**
Installation of configuration succesfull

**Error Logs**
[Mon Jan 01 16:56:15.325233 2024] [php:notice] [pid 24441] [client 102.217.187.117:58478] Installation: 101, referer: https://video.basuin.web.za/install/index.php
[Mon Jan 01 16:56:15.325246 2024] [php:notice] [pid 24441] [client 102.217.187.117:58478] Installation: 104, referer: https://video.basuin.web.za/install/index.php
[Mon Jan 01 16:56:15.326176 2024] [php:notice] [pid 24441] [client 102.217.187.117:58478] Installation: 116, referer: https://video.basuin.web.za/install/index.php
[Mon Jan 01 16:56:15.326378 2024] [php:notice] [pid 24441] [client 102.217.187.117:58478] Installation: 126, referer: https://video.basuin.web.za/install/index.php
[Mon Jan 01 16:56:15.328135 2024] [php:notice] [pid 24441] [client 102.217.187.117:58478] Installation: 135, referer: https://video.basuin.web.za/install/index.php
[Mon Jan 01 16:56:15.329404 2024] [php:notice] [pid 24441] [client 102.217.187.117:58478] Installation: 144, referer: https://video.basuin.web.za/install/index.php
[Mon Jan 01 16:56:15.330292 2024] [php:notice] [pid 24441] [client 102.217.187.117:58478] Installation: 153, referer: https://video.basuin.web.za/install/index.php
[Mon Jan 01 16:56:15.331142 2024] [php:notice] [pid 24441] [client 102.217.187.117:58478] Installation: 170, referer: https://video.basuin.web.za/install/index.php
[Mon Jan 01 16:56:15.331599 2024] [php:notice] [pid 24441] [client 102.217.187.117:58478] Installation: 179, referer: https://video.basuin.web.za/install/index.php
[Mon Jan 01 16:56:15.331691 2024] [php:error] [pid 24441] [client 102.217.187.117:58478] PHP Fatal error:  Uncaught Error: Call to undefined function _uniqid() in /var/www/html/AVideo/install/checkConfiguration.php:201\nStack trace:\n#0 {main}\n  thrown in /var/www/html/AVideo/install/checkConfiguration.php on line 201, referer: https://video.basuin.web.za/install/index.php

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 - Version: Release Notes v1.61.109 (Dec 21, 2023) Chromium to 120.0.6099.144. 

**Additional context**

I'm redeploying after initial test deploy that worked circa 27 Dec, that installation succeeded.

Still trying to find the exact file/change that might be responsible

**Comment by hevisko** [comment]
@DanielnetoDotCom https://github.com/WWBN/AVideo/commit/eeaa44f871376b26005edb614bfdc2dddfe9ef23 seems to be the addition, needs some include to the functions.php perhaps?

**Comment by DanielnetoDotCom** [comment]
Can you please check this update?

**Comment by hevisko** [comment]
`array(4) { ["type"]=> int(1) ["message"]=> string(249) "Uncaught Error: Failed opening required 'objects/functionSecurity.php' (include_path='.:/usr/share/php') in /var/www/html/AVideo/objects/functions.php:11988 Stack trace: #0 /var/www/html/AVideo/install/index.php(2): require_once() #1 {main} thrown" ["file"]=> string(42) "/var/www/html/AVideo/objects/functions.php" ["line"]=> int(11988) }`

**Comment by hevisko** [comment]
dropping the "$global['systemRootPath'].'objects/" from objects/functions.php seems to get passed it to the configuration screen

**Comment by DanielnetoDotCom** [comment]
Sorry, try this now

**Comment by hevisko** [comment]
thanks that works!

**Comment by hevisko** [comment]
current fixes work
