### ISSUE TITLE
Videos don't play. The encoder is set up correctly

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#8759]
Here is the config of my system. I have the encoders set up correctly however the videos still will not play. Can you please assist. Please see the attached screenshots
![cs_setting_2](https://github.com/WWBN/AVideo/assets/58635493/d80f6f85-a83c-4cf0-b733-b0e1ba3acf04)
![cs_setting_1](https://github.com/WWBN/AVideo/assets/58635493/a0c415b1-9092-40be-a19b-19719b35d745)
![cs_2](https://github.com/WWBN/AVideo/assets/58635493/3ebf37d5-f96d-4930-a79f-c2e6b91418b5)
![cs_1](https://github.com/WWBN/AVideo/assets/58635493/28903b00-bd0c-4066-b6aa-b564e6783ecc)

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/What-to-do-if-your-video-does-not-play

**Comment by venwebsites** [comment]
Hello, I did that and I still have the same issue. Can you please assist

**Comment by DanielnetoDotCom** [comment]
Hi, you can hire me and I can direct check it.

**Comment by venwebsites** [comment]
Hello,

 

   I hired you back in 2019. I know the script has changed since then however I lost all the plugins I paid for. Can you check your records between 11/2019 and December 2019

**Comment by DanielnetoDotCom** [comment]
Hi, 

Sorry, I did not find any plugin payment record.

I found installation and support payments

**Comment by DanielnetoDotCom** [comment]
If you find it in your PayPal, I can restore the plugins for you.

**Comment by venwebsites** [comment]
Hello Daniel, it should be under VEN Interactive Media or ***@***.***

**Comment by DanielnetoDotCom** [comment]
If you find it in your PayPal, I can restore the plugins for you.

**Comment by venwebsites** [comment]
Ok I have to call paypal because I can’t go back that far. Stand by 😊

**Comment by venwebsites** [comment]
What would your paypal email be around that time

**Comment by DanielnetoDotCom** [comment]
my paypal is danielneto.com@gmail.com

**Comment by venwebsites** [comment]
Here are all the paypal transactions as per your request

**Comment by DanielnetoDotCom** [comment]
I cannot see anything here, all info here is public. 

please email (developer@youphptube.com) me **only the plugin purchase transactions.** 

I did find many support transactions.

**Comment by venwebsites** [comment]
Hello Daniel,

 

I emailed you directly
