### ISSUE TITLE
Update copyright & Twitter icon

### ISSUE THREAD

**Issue by amanr-dev** [WWBN/AVideo#8762]
The copyright year and Twitter logo appear to be outdated and require an update.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot where?

**Comment by amanr-dev** [comment]
> can you please screenshot where?

On the Navbar and Footer.

footer :
![Screenshot 2024-01-03 204534](https://github.com/WWBN/AVideo/assets/124811276/db50b772-7ce4-427e-b914-0628e626bac5)

navbar :
![Screenshot 2024-01-03 204523](https://github.com/WWBN/AVideo/assets/124811276/0d662797-1e37-46a7-a005-ab712b50521d)

**Comment by julzxcapz** [comment]
@amanr-dev done updating, thank you for noticing
