### ISSUE TITLE
All video's prior to todays gitpull no longer play

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#8763]
@DanielnetoDotCom 
All my videos that played 30 minutes ago no longer play including all my new years eve parties.  Any video that I uploaded after git pull encodes and plays. How do I fix the issue

**Comment by DanielnetoDotCom** [comment]
Please make sure all your plugins are up to date 

Please share a site link and also please share the error log

**Comment by DanielnetoDotCom** [comment]
Please let me know if you find something.

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom 
https://mhktube.com/video/900
Log empty

**Comment by DanielnetoDotCom** [comment]
what files do you have in that folder?

..../AVideo/videos/v101012316_v2f23/ ?

**Comment by milehighkaraoke** [comment]
![20240103_071444](https://github.com/WWBN/AVideo/assets/70327833/2c24d862-59df-42d5-9070-a96f7ef7230a)

**Comment by DanielnetoDotCom** [comment]
any idea why I cannot access them?

https://mhktube.com/videos/v101012316_v2f23/v101012316_v2f23_540.mp4

https://mhktube.com/videos/v101012316_v2f23/v101012316_v2f23_720.mp4

**Comment by milehighkaraoke** [comment]
? @DanielnetoDotCom 
![Screenshot_20240103_072315_Chrome](https://github.com/WWBN/AVideo/assets/70327833/f63bff57-8659-433f-aa75-3c89c334d7f3)

**Comment by DanielnetoDotCom** [comment]
Exactly, why I can't access it? seems to be something in your server

**Comment by DanielnetoDotCom** [comment]
I found something that may help you, hold on

**Comment by milehighkaraoke** [comment]
Prior to doing this pull everything worked. Now only the videos I upload after the pull work.

**Comment by DanielnetoDotCom** [comment]
can you please try this update?

**Comment by milehighkaraoke** [comment]
That fixed it.... thank you
