### ISSUE TITLE
Videos not showing up on front page

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#8766]
*I have uploaded 2 videos as a test however they don't show up on the front page. If I log in I can see them but they are not available public and I have everything set to public. Any suggestions

**Comment by venwebsites** [comment]
ok I figurerd out the issue. the videos are not releasing right away. there is something wrong with the scheduler. Can you please assist. also the categories are showing empty however there are videos assigned to the categories

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Scheduler-Plugin
