### ISSUE TITLE
Live Streamer not working

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#8767]
Live steamer refused to connect. NGINX failed saying port 8080 is in use.

Port 8080 is running Wekan (not sure why) 

RTMP fails to connect to OBS and VNC. Can you please assist

**Comment by venwebsites** [comment]
Here are some screenshots
![live_2](https://github.com/WWBN/AVideo/assets/58635493/1e1ae4a9-88df-46b7-aee8-fc79b4e625e6)
![live_config](https://github.com/WWBN/AVideo/assets/58635493/be8e4d4e-9b64-4017-a57b-90b773ff5e12)
![live_3](https://github.com/WWBN/AVideo/assets/58635493/029e02fe-780e-4828-9258-b2a1e423e66e)

**Comment by venwebsites** [comment]
Do you have any suggestions on the RTMP

**Comment by DanielnetoDotCom** [comment]
Not sure what you did wrong in the installation, try to get some help in the nginx rtmp community 

https://github.com/arut/nginx-rtmp-module

**Comment by venwebsites** [comment]
I followed your tutorial and did the one click install on a fresh ubuntu 22.0.4.3 LTS Server. Are you able to take a look and see what happened. also Not sure why your script install installed Wekan. can you please assist

**Comment by venwebsites** [comment]
I am defiantly well versed in Linux . There seems to be issues with the script itself (eg: SMTP, and RTMP) Perhaps this script is not designed for ubuntu 22.04.3 as older versions of Linux works fine with this script

**Comment by venwebsites** [comment]
I don't know how much clearer this config can be. The RTMP server is defiantly
![live_config](https://github.com/WWBN/AVideo/assets/58635493/57f83108-3bea-4044-879a-b8363c53330e)
![nginx](https://github.com/WWBN/AVideo/assets/58635493/c483c4d4-76a1-4ec7-a78c-691b03c7f2e1)
 listening with the rules open. your Script says otherwise. please assist. 

Please see the screenshots

**Comment by DanielnetoDotCom** [comment]
If you have only one liveserver you do not need to configure it

**Comment by venwebsites** [comment]
Live streams is still down, I brought someone on to look into the server environment, They concurred that everything is set up correctly however the live streams still don't display or post the recording on the platform. This is clearly a bug issue in the avideo code. Please assist as I want this RTMP live streaming service up

**Comment by DanielnetoDotCom** [comment]
For nginx rtmp installation please ask their community https://github.com/arut/nginx-rtmp-module

AVideo is fine, as long as we have thousands of sites runing

**Comment by venwebsites** [comment]
That's fair statement to make, I did check with the community and they also concurred that Everything is set up correctly. I do have to say I am disappointed that you don't want to at least help to find out what the issue is

**Comment by DanielnetoDotCom** [comment]
The issue with port 8080 is clear to be a server or Nginx configuration problem, **not related to AVideo**. This isn't something I can assist with, as it's outside the scope of AVideo support.

It's best to consult with a Linux server administrator to resolve this issue, as it's more related to server setup than a bug in AVideo.
