### ISSUE TITLE
Configuration and use of the new big video on the home page

### ISSUE THREAD

**Issue by chenzisuifeng** [WWBN/AVideo#8768]
Hello
Where should I modify or close the new large video configuration on the homepage? Is there any documentation on this?

**Comment by para2022** [comment]
It seems it needs more work to fix it properly as it has bugs. It’s bringing the views on my site down even further cos it does not register them. You can turn it off in the gallery plugin.

**Comment by DanielnetoDotCom** [comment]
![image](https://github.com/WWBN/AVideo/assets/18009293/eca5018b-b3a6-4c4a-85d7-7667a4ee71b0)

**Comment by chenzisuifeng** [comment]
OK, thanks
