### ISSUE TITLE
fix icon alignments

### ISSUE THREAD

**Issue by amanr-dev** [WWBN/AVideo#8778]
Fix social icon alignments on the Footer at '/About' route.

screenshot:
![Screenshot 2024-01-08 152905](https://github.com/WWBN/AVideo/assets/124811276/a0ffd11d-fa7e-4323-b190-bb242ecb80f0)

**Comment by jaymehta002** [comment]
please assign me this issue

**Comment by amanr-dev** [comment]
assigned to @jaymehta002 👍

**Comment by jaymehta002** [comment]
can you please share the reference to the footer code?
i am unable to find it in php files

**Comment by amanr-dev** [comment]
I also didn't find it.

**Comment by amanr-dev** [comment]
You can ask to maintainers

**Comment by julzxcapz** [comment]
Done applied fixed. Thank you!
