### ISSUE TITLE
If Storage limits are enabled there needs to auto make all accounts on to free plan when they sign up

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8793]
There is no warning or anything beside it saying they are out of storage and new users do knot understand that. 

Just something that tells to them to Please Pick a Storage plan in order to upload

or something like that.

**Comment by JoshWho** [comment]
Just something to make it more easy for them to know they need to select a plan in order to upload.

**Comment by DanielnetoDotCom** [comment]
I agree, I will have an update soon

**Comment by DanielnetoDotCom** [comment]
check this to edit messages

![image](https://github.com/WWBN/AVideo/assets/18009293/3fcfeeb5-1d9b-42e2-9f4c-ff8b9fbc766a)
