### ISSUE TITLE
Video files uploaded after updating from Ver12.9 to Ver14.2 cannot be played on AVideo.

### ISSUE THREAD

**Issue by hnagasawa** [WWBN/AVideo#8796]
I updated AVideo form Ver12.9 to Ver14.2.
After updating, videos uploaded from Avideo-Encoder no longer play. 
Video Files uploaded with Ver12.9 can be played with AVideo.

[20240111_Problem with posted videos after AVideo version update.xlsx](https://github.com/WWBN/AVideo/files/13944183/20240111_Problem.with.posted.videos.after.AVideo.version.update.xlsx)

I check AVideo.log and AVideo-encoder's avideo.log.
I can not find error in both logs.

What do I check again.

Updates will be made after 13:00 on 1/11.
Videos will be uploaded to AVideo-Encoder after 15:30 on 1/11.

[20240111.zip](https://github.com/WWBN/AVideo/files/13944208/20240111.zip)

**Comment by DanielnetoDotCom** [comment]
I see, can you please make another git pull and try again?

**Comment by hnagasawa** [comment]
@Danielneto

Do I git pull both AVideo an AVideo-Enconder again ?

**Comment by DanielnetoDotCom** [comment]
Please do on both

**Comment by hnagasawa** [comment]
Updated today 13:00(JST). There were no plugin updates. When I upload a video to AVideo-Encoder, it is queuing and does not proceed.
It was the same even after clearing the all caches.

after "start upload"

![queing1](https://github.com/WWBN/AVideo/assets/46562199/a2b03a47-40fc-4e46-b22f-dfaeae469a58)
![queing2](https://github.com/WWBN/AVideo/assets/46562199/29dbed16-f833-44a8-bbe4-76e321955805)
[avideoencoder20240122.log](https://github.com/WWBN/AVideo/files/14006796/avideoencoder20240122.log)
[avideostreamer20240122.log](https://github.com/WWBN/AVideo/files/14006799/avideostreamer20240122.log)

What do we check ?

**Comment by DanielnetoDotCom** [comment]
I am not 100% sure what it is, but it may be related to the filename. can you please rename the uploaded video to a simple name and try again?

**Comment by hnagasawa** [comment]
Do you think it's a problem because the file name is Japanese?
Up to Ver12.9, there was no problem even if the file name was in Japanese.

**Comment by DanielnetoDotCom** [comment]
I guess it is, but please try, I am not 100%.

**Comment by hnagasawa** [comment]
Like #8802, isn't there a bug with 2byte code?

**Comment by DanielnetoDotCom** [comment]
the error can be the same, but I need you to test

**Comment by DanielnetoDotCom** [comment]
looks like I am in circles, I am asking to use regular chars for testing.

# No Special chars and no space. use the simplest file name as possible

I will be back once someone tests it as I am requesting

**Comment by DanielnetoDotCom** [comment]
@KrzysioMisio in your case, open a new issue and share the encoder and streamer logs

**Comment by hnagasawa** [comment]
After changing the video file name to English and uploading it from AVideo-Encoder, I was able to successfully upload it to streamer.
Next, I tried uploading the video file name to Japanese using AVideo-Encoder, but I could not upload it to the streamer.
This issue is bug of Ver14.2.
I will send you an mp4 file with a Japanese file name for debugging.


https://github.com/WWBN/AVideo/assets/46562199/2e5bdc0a-bfe0-426a-9d97-15d7767ff021

**Comment by DanielnetoDotCom** [comment]
Hi, ok, thanks the video with a Japanese name helps to find the issue

please send it to my email danielneto.com@gmail.com

**Comment by DanielnetoDotCom** [comment]
Update your encoder with the latest `git pull`

**Comment by hnagasawa** [comment]
I updated AVideo and AVideo-Enconder but no improvement. I have sent the mp4 file name that I sent to you to your email address.
![20240124error](https://github.com/WWBN/AVideo/assets/46562199/26352cc3-a6eb-4206-99eb-bce7c6ce318a)

**Comment by DanielnetoDotCom** [comment]
Hi, it is definitely something with the filename. 

The last fix I made with your file. 

If the error persists, it may be something specific in your environment

**Comment by hnagasawa** [comment]
I have uploaded an mp4 with another Japanese file name.
AVideo-enconder display next messages."Error occured during AJAX request"
![encoder20240126](https://github.com/WWBN/AVideo/assets/46562199/dc28e0f5-d5de-4ef0-9c99-afc9d4698f72)

What do I need to install ?

[avideoencoder20240126.log](https://github.com/WWBN/AVideo/files/14064746/avideoencoder20240126.log)

**Comment by DanielnetoDotCom** [comment]
The Ajax is not a real issue. 

if the file is encoding. do not worry about it

**Comment by hnagasawa** [comment]
Not encode.What do we check ?

**Comment by DanielnetoDotCom** [comment]
for now, you should just rename the file. 
I may review the filename issue in the future

**Comment by hnagasawa** [comment]
I tried to upload rename video file name(japanaese) again. But same error ocurred.
I uploaded your demo site same video file(次雲.mp4). 
It seems that the upload was successful, but I can't watch it on streamer.
The upload time is February 1st at 16:10 (JST). (February 1st 4:10 in your local time) Could you please check if it has been uploaded to the streamer?

**Comment by DanielnetoDotCom** [comment]
When I say rename, I mean, use regular characters, ABC....

**Comment by hnagasawa** [comment]
We have prepared two AVideo servers.
The OS is Ubuntu 18.04.
AVideo1
Below is /var/www/html:

drwxr-xr-x 20 www-data www-data  4096  3月 18 11:13 AVideo
drwxr-xr-x 14 www-data www-data  4096  4月 21  2023 AVideo-Encoder

AVideo2
Below is /var/www/html:
drwxr-xr-x 20 www-data www-data  4096  3月 19 09:12 AVideo
AVideo-Encoder was installed under the AVideo directory
and AVideo-Encoder change name upload

First,I uploaded video files with alphabetical file names to both AVideo servers through Encoder. Both were successfully uploaded to AVideo Stremer

Next, I uploaded video files with Japanese file names to both AVideo servers through Encoder.
AVideo1 could not upload to AVideo streamer.

AVideo2 was successfully uploaded to AVideo stremer.

The attached log is avideo.log of AVideo-Encoder of AVideo1 and AVideo2.

What do you think is the problem?


[AVideo1fail.txt](https://github.com/WWBN/AVideo/files/14644386/AVideo1fail.txt)


[AVideo2success.txt](https://github.com/WWBN/AVideo/files/14644387/AVideo2success.txt)

**Comment by DanielnetoDotCom** [comment]
I found something, you will need to update the encoder

but you need to make sure you have the php-mbstring installed

1. **Update Package Lists:**
   Open a terminal and update the package lists to ensure you install the latest versions of packages:
   ```bash
   sudo apt update
   ```

2. **Install PHP mbstring Extension:**
   The `mb_detect_encoding` function is part of the `mbstring` extension. Install it using the following command:
   ```bash
   sudo apt install php-mbstring
   ```

3. **Restart Apache or PHP-FPM:**
   If you're using Apache, restart it to apply the changes:
   ```bash
   sudo systemctl restart apache2
   ```

**Comment by hnagasawa** [comment]
@DanielnetoDotCom 
Yesterday, I installed all patches. This issue fix.
Thank you for your support.
