### ISSUE TITLE
Live Streaming Issue

### ISSUE THREAD

**Issue by venwebsites** [WWBN/AVideo#8814]
When using OBS, the live stream captures and saves once you disconnect. When you start a new live stream, nothing captures or saves. Please assist

**Comment by venwebsites** [comment]
The live stream and encoder is very janky. this is coming from one programmer to another

**Comment by milehighkaraoke** [comment]
Have you done a git pull on both site and encoder

**Comment by venwebsites** [comment]
> Have you done a git pull on both site and encoder

Yes, and configured it correctly. This makes no sense. either there is a bug in the script for nginx (RTMP) or the developer knows something we don't and banking on paid support. I am almost convinced its banking on paid support
