### ISSUE TITLE
Total comment in email notification 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#8815]
Requesting entire comment text be placed in email notification.

**Comment by DanielnetoDotCom** [comment]
Good idea, I will have the update soon

probably version 5.9

**Comment by fakeologist** [comment]
thanks it will save logging in unless replying.

**Comment by fakeologist** [comment]
Looks good good improvement.

**Comment by fakeologist** [comment]
Daniel please put the content in any responses to comments, which is generated by a different template it seems.

**Comment by DanielnetoDotCom** [comment]
Hi, 

can you please detail what you mean?

it is not clear for me

**Comment by fakeologist** [comment]
> Hi, 
> 
> can you please detail what you mean?
> 
> it is not clear for me

When there is a response comment it doesn't show the content of the comment like the original comment does (which you just added).

**Comment by DanielnetoDotCom** [comment]
I see, do you mean, you want to show the parent comment, in the email? is that correct?

**Comment by DanielnetoDotCom** [comment]
Please check the Notifications plugin version 6.2

**Comment by fakeologist** [comment]
trying to login to plugin store - I cannot - I am getting this error.

![image](https://github.com/WWBN/AVideo/assets/66537018/ba3f39c7-7d38-4466-9837-61cadb97f32f)

**Comment by DanielnetoDotCom** [comment]
Not sure, but I could login with google with no problem.

anyway I am sending you the updates now.

**Comment by fakeologist** [comment]
Looks good thanks!
