### ISSUE TITLE
Eliminate popup screen in encoder 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#8816]
Recently a popup screen to edit file details was introduced in the encoder.

Can this be eliminated or made an option? 

It slows down uploading.

**Comment by DanielnetoDotCom** [comment]
Hi, the popup does not slow the upload. 

once you are filling the video information the video is uploading and encoding in the background

**Comment by fakeologist** [comment]
Still I used to upload in one step now it takes two and when the server is slow it wastes time. I don't need the box as the info is already there. Please make it an option.

**Comment by DanielnetoDotCom** [comment]
There is an option to not edit the video

![image](https://github.com/WWBN/AVideo/assets/18009293/7dc2a9de-eb96-4971-aab4-540acfe07c24)

**Comment by fakeologist** [comment]
Thanks !
