### ISSUE TITLE
404 Page Not Found when upgrading distros

### ISSUE THREAD

**Issue by guillaumesoucy94** [WWBN/AVideo#8825]
**Describe the bug**
After upgrading to Ubuntu 22.04 I've got this blue page 404 Page Not Found

![Screenshot at 2024-02-05 16-19-42](https://github.com/WWBN/AVideo/assets/22561876/6f6ee399-a89f-4431-a795-92b7fa83fd60)

**To Reproduce**
1. Take a fully working system from Ubuntu 20.04 
2. Upgrade it to 22.04 
3. And it will throw that error. 

**Expected behavior**
The usual home page.

**Error Logs**

https://pastebin.zsites.ca/view/0dd4d936

**Screenshots**
![Screenshot at 2024-02-05 16-19-42](https://github.com/WWBN/AVideo/assets/22561876/1cbcda37-6e43-44f5-bb20-62454003c560)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3
 - Browser: Mozilla Firefox
 - Version: 122

**Additional context**
I tried at first to upgrade Avideo to 14.3 then to upgrade the distros, same error occurred after upgrading Ubuntu Server.

**Comment by Social-Loafer** [comment]
If its the same issue I ran into, you can try this:
Set your php back to 7.4 or whatever version you had it at previously.
a2dismod php*
update-alternatives --config php

**Comment by DanielnetoDotCom** [comment]
Hi 

I guess your Apache also update and you are missing some Apache modules 

You can try check your Apache mod rewrite

**Comment by guillaumesoucy94** [comment]
It works now!  The solutions was effectively to downgrade php back to 7.4 and also php-zip and php-intl was missing. That odd as those two packages was there before the distros upgrade.

Thanks, 

Guillaume
