### ISSUE TITLE
Serve the same video from multiple streaming servers

### ISSUE THREAD

**Issue by tbprince** [WWBN/AVideo#8826]
Hello,

is there a way to setup a file to be served and streamed from multiple storage servers in order to aggregate bandwidth? We have already split frontend, encoders and streaming servers however if we expect much traffic (i.e. clients) for one video, can we aggregate bandwidth by serving that file from multiple servers?

Thanks.

**Comment by DanielnetoDotCom** [comment]
For an unlimited bandwidth solution, the best solution I can offer is

to use our CDN https://github.com/WWBN/AVideo/wiki/CDN-Plugin

the best combination is the CDN + [CDN Storage](https://github.com/WWBN/AVideo/wiki/CDN-Storage) + [HLS format](https://github.com/WWBN/AVideo/wiki/VideoHLS-Plugin)

**Comment by tbprince** [comment]
Thank you for that but we aim not to depend on or use external services besides our own. If there's an option to create such config, we would be interested in that. We can also consider paid options, if reasonably priced. 

Thanks.

**Comment by DanielnetoDotCom** [comment]
Sorry, we do not have an option for that.
