### ISSUE TITLE
VideoTags

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#8827]
Is there a possibility that tags will not be visible?

![image](https://github.com/WWBN/AVideo/assets/85537931/3514a683-3c2e-4fc9-954c-5a9f182170ae)

tnx

**Comment by DanielnetoDotCom** [comment]
you can add a custom css to hide it

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript

**Comment by eitanwa** [comment]
got it tnks
