### ISSUE TITLE
Articles plugin

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#8830]
Hey
There is a bug in the articles, it doesn't save the set format
For example, font size, color, image size, etc
I tested it on 3 different platforms
For example, this is the design I set

![image](https://github.com/WWBN/AVideo/assets/85537931/54ef15d7-6c6c-4c54-9b40-8f9ebc4f1f83)

This is the result

![image](https://github.com/WWBN/AVideo/assets/85537931/6a06abf8-0211-466f-afb9-7ec7ff19f73a)

Thanks

**Comment by DanielnetoDotCom** [comment]
This is not a bug, this is expected, we do not allow all the tags in it. 

if you allow all the tags it can break your layout

But if you want to allow it all you can try this

![image](https://github.com/WWBN/AVideo/assets/18009293/c0817f38-c60d-46dc-be0f-f2c94bcd7273)

**Comment by eitanwa** [comment]
I am aware of that
I have everything marked

![image](https://github.com/WWBN/AVideo/assets/85537931/58a9bd95-6743-48be-a2b9-b4348600c525)

and still cannot be changed
I have used it many times I use percentages to avoid breaking a layout
something has changed

**Comment by DanielnetoDotCom** [comment]
What exactly HTML are you trying to add?

**Comment by eitanwa** [comment]
I'm trying to write an article, to add plain text
The font size does not work ,The alignment does not work, the color of the background text does not work, and so on
Even when adding an image file, Its source size cannot be changed, all of these worked until recently
When I write not working I mean not saved as I defined in editing the article

In the first picture I sent to illustrate I showed you a Screenshot of an article With the words "for example this is the design I set"
Simple text that I changed font size and color-red
plus the image file of the chess horse (jpeg)

 The second picture is after saving 
 You can see that the design is not saved

**Comment by eitanwa** [comment]
By the way, the new gallery Image plug-in is excellent, thank you very much for everything you do

**Comment by DanielnetoDotCom** [comment]
that is what I mean, after creating the code you are expecting, please share the HTML here, I will try the same as you

**Comment by eitanwa** [comment]
This is the code while creating the article before saving

<p><span>This is a test I am producing an article</span><br><span>&nbsp; Font size 36 in red color pinned to the center</span></p>

This is the code after saving

<p><span>This is a test I am producing an article</span><br><span>&nbsp; Font size 36 in red color pinned to the center</span></p>

tnks

**Comment by eitanwa** [comment]
This is the code before saving

``<p><span>This is a test I am producing an article</span><br><span>&nbsp; Font size 36 in red color pinned to the center</span></p>``

**Comment by DanielnetoDotCom** [comment]
Where is the font size info?

![image](https://github.com/WWBN/AVideo/assets/18009293/16e496a8-912e-47e7-8b12-eb6138ce9bd2)

**Comment by eitanwa** [comment]
That's exactly the problem

**Comment by eitanwa** [comment]
That should be clearer

https://github.com/WWBN/AVideo/assets/85537931/a140e16c-4c35-4a93-9a3d-75af5408e7ba

tnks

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by guymass** [comment]
OK this update fixed the font issue and color, however we used to be able to do many things with this editor we are no longer able to do. The alignment still doesn't work and we were also able to control the size of the media embedded in the post whether its an image or a video. It seems that the editor still has some issues and it was working better before.

Here is an example of a post we used to be able to create and now we cannot create such a page anymore.

https://alive528.com/article/19968/%D7%90%D7%A0%D7%97%D7%A0%D7%95-%D7%A8%D7%A7-%D7%A0%D7%9C%D7%9A-%D7%95%D7%A0%D7%92%D7%93%D7%9C

**Comment by eitanwa** [comment]
This affects virtually all places where the editor is used
Also, when using a cell phone browser web (not the app),   
for example, when you expand the description of the video, it aligns to the left
  
![image](https://github.com/WWBN/AVideo/assets/85537931/b163c13a-b255-4569-a8c5-c61922eeb5ad)

  
![image](https://github.com/WWBN/AVideo/assets/85537931/38b48d01-5bdb-4c9d-aa89-a9c718abe169)

After expanding the option, it is also not possible to reduce it again
![image](https://github.com/WWBN/AVideo/assets/85537931/c0f8ae5a-fcae-49ca-886a-38e4a8ec010c)

And in the description of the channel as well, etc

I thought maybe it was related to the update that the tiny docks editor has?

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by eitanwa** [comment]
Thank you very much looks great

**Comment by guymass** [comment]
Brilliant, that sorted few other things as well on the RTL view, much thanks.
