### ISSUE TITLE
Missing deactivate "Sign In" in admin

### ISSUE THREAD

**Issue by Adi-18** [WWBN/AVideo#8841]
I wish an option in admin page to prevent "self Sign In".
![image](https://github.com/WWBN/AVideo/assets/29123730/966a2be8-4163-44c5-851a-10f0b6c36a67)

**Comment by DanielnetoDotCom** [comment]
![image](https://github.com/WWBN/AVideo/assets/18009293/8ac03801-444c-40be-9578-80fd4f564a31)
