### ISSUE TITLE
Editing video description or article description

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#8845]
Hey
When editing a video description or an article description
even changing a letter or deleting just one letter
This completely deletes the entered Short summary and Meta Description text in seo section

The Ai plugin is not active for us, but maybe it is somehow related to this plugin?

Thanks

**Comment by guymass** [comment]
Try to create a post, edit its SEO META descriptions and save. Then reopen and just edit the title and change it and save again, reopen and go to the SEO section and see if they are still there or they are empty like in our case.

**Comment by DanielnetoDotCom** [comment]
It is working here 

![chrome-capture-2024-1-19](https://github.com/WWBN/AVideo/assets/18009293/c1e01496-3790-445b-b922-f474a1918b15)

**Comment by eitanwa** [comment]
Not these tags
These tags

![image](https://github.com/WWBN/AVideo/assets/85537931/f6bff238-7b18-44c5-b1b8-fd1fb02d57bf)

**Comment by DanielnetoDotCom** [comment]
If you check the image I attached you will see I also edited those

**Comment by DanielnetoDotCom** [comment]
Did you see this ?
https://github.com/WWBN/AVideo/issues/8845#issuecomment-1952416389

**Comment by eitanwa** [comment]
ok sorry that was too fast
I had to repeat it several times
Although I checked earlier
Apparently this only happens just in Hebrew
Thanks

**Comment by DanielnetoDotCom** [comment]
Can you please send me some Hebrew text so I can copy/paste to test it?

**Comment by eitanwa** [comment]
Yes sure thanks daniel 

הוספת קישורים חיצוניים מסרטונים היא דרך רבת עוצמה להניע תנועה ומעורבות. בעוד שפלטפורמות רבות מגבילות את היכולת הזו, בולטת בכך שהיא מציעה את היכולת הייחודית למקם קישורים חיצוניים על המסך כולו, כולל כל הצדדים (עליון, תחתון, ימין, שמאל), כמו גם תמונות בגדלים שונים. תכונה זו מספקת יתרון שיווקי ופרסום משמעותי, משפרת את חווית המשתמש ומגדילה את הזדמנויות המונטיזציה.

**Comment by DanielnetoDotCom** [comment]
Works fine

you can try reproduce it here https://demo.avideo.com/

![chrome-capture-2024-1-19 (1)](https://github.com/WWBN/AVideo/assets/18009293/f111f042-654b-49cf-901c-12ab037416e6)

**Comment by eitanwa** [comment]
Hi Daniel, the problem exists there as well
Now I understand why you don't see it
You edit and check on different screens
You check the edit in the video editing screen
And indeed that is how it is preserved
But if you edit and check the way I show in the video, it will be deleted in English and all languages as well
Try it as I do
Before sending you this problem I tested on several platforms and several languages
I was surprised your it was saved now I understood what the difference is
Thanks


https://github.com/WWBN/AVideo/assets/85537931/c09e416d-c6d1-4c5b-908d-894724817c89

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by eitanwa** [comment]
Excellent Daniel
Right now it looks great it even fixed a few more small issues that were in the text editor
Thanks

**Comment by eitanwa** [comment]
Hey
So after the updates something went wrong with the left menu
It looks kind of broken I demonstrate in the video

https://github.com/WWBN/AVideo/assets/85537931/163a7ff2-146f-4869-89cb-c5d476d24566
On mobile, this menu cannot be scrolled to the end

In addition, what has disappeared is the clear first page cash button

![image](https://github.com/WWBN/AVideo/assets/85537931/1801f40d-f37e-459d-bb8f-48c3a7105e15)

thanks

**Comment by DanielnetoDotCom** [comment]
make another git pull and clear the whole cache

**Comment by eitanwa** [comment]
thanks for that 
works now

**Comment by eitanwa** [comment]
hey Daniel
after the update
The AD_Server plugin stopped working
It worked great before
Thanks

**Comment by guymass** [comment]
Yes something change from recent update and now our ads don't work as they used to. It hard to explain but they just stopped working for us, they don't show up on our videos on alive528.com and feisafe.com.

**Comment by guymass** [comment]
Here is the error message I see in the console:

![Screenshot 5784-06-16 at 18 07 28](https://github.com/WWBN/AVideo/assets/58882903/9748ef76-0d06-430a-bcc8-e9fd9728f627)

**Comment by guymass** [comment]
[DanielnetoDotCom](https://github.com/DanielnetoDotCom) Hi Daniel can you please help us sort this out? We have a presentation tomorrow with someone and this feature was something we wanted to show and offer them to use on their own website. It would be great if we can get it to work as before the last git pull. Can we revert the changes maybe?

**Comment by DanielnetoDotCom** [comment]
I went to both of your sites and I could not see the ADs plugin enabled AD_Server 

Also open a new issue, because the AD_Server has nothing to do with this issue

**Comment by guymass** [comment]
Hi Daniel, sorry, I am not sure what you mean by ADs plugin not enabled, because it is enabled, maybe this is the issue? I will open a separate post for that as you requested, but be assured that we know how to work with the platform very well and know when our plugins are off.
