### ISSUE TITLE
New Encoder Upgrade now wants PHP Zip extension but wont install no matter what

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8849]
Every method fails to install the apt install php8.1-zip && sudo /etc/init.d/apache2 restart

**Comment by DanielnetoDotCom** [comment]
Hi, you can try `apt install php-zip `

if still not work you need to google for that

**Comment by JoshWho** [comment]
Can you please take a look . I do not see why my versersion would be different from the Main git pull something doesn't seem right

**Comment by DanielnetoDotCom** [comment]
php version has nothing to do with `git pull`, it is about your server installation, NOT AVideo installation

**Comment by JoshWho** [comment]
You installed it

**Comment by DanielnetoDotCom** [comment]
what server is that?

**Comment by JoshWho** [comment]
live.joshwhotv.com

**Comment by DanielnetoDotCom** [comment]
where are you seeing the zip error?

**Comment by JoshWho** [comment]
The uploader

**Comment by DanielnetoDotCom** [comment]
screenshot please

**Comment by JoshWho** [comment]
![image](https://github.com/WWBN/AVideo/assets/39392449/0e1aa3c1-d710-4c1a-baf3-0e23a35744fa)

**Comment by DanielnetoDotCom** [comment]
I guess you should try the 

```
New release '20.04.6 LTS' available.
Run 'do-release-upgrade' to upgrade to it.
```

try to upgrade to 22.04

**Comment by JoshWho** [comment]
This is what is says

```
root@joshwhotv:/var/www/html/YouPHPTube# do-release-upgrade
Checking for a new Ubuntu release
Please install all available updates for your release before upgrading.
root@joshwhotv:/var/www/html/YouPHPTube#

```

**Comment by DanielnetoDotCom** [comment]
Hi, you man need to google to find out how ho upgrade it

**Comment by DanielnetoDotCom** [comment]
The packages on your server are messed up, probably due to some extra broken installation. 

I cannot help you today, but if you cannot figure it out, I can try (no guarantee) during the week

**Comment by JoshWho** [comment]
I will try some things and will let u know if I get it solved or not

**Comment by JoshWho** [comment]
What is it doing differently that it needs this update? I am so confused why this method changed to begin with. It was working fine, why was there a new version that made this problem?

**Comment by DanielnetoDotCom** [comment]
this is not an AVideo issue, 

what is not working is your PHP, probably there is another solution instead of upgrading the OS, but you may need to google for that. 

But if I were in your shoes, I would upgrade the OS. I am not sure what you have installed, I am also not sure if something will break when you upgrade the OS. I can only guarantee you AVideo will still work after the upgrade

**Comment by JoshWho** [comment]
I cannot on that vps it is the only version
Why was avideo able to work before and now can't what has changed that needs an OS upgrade?

**Comment by DanielnetoDotCom** [comment]
what do you mean VPS?

you have a dedicated server on live.joshwhotv.com

**Comment by DanielnetoDotCom** [comment]
FYI, I could fix your apt-get, you may be able to upgrade your distro if you want.

**Comment by DanielnetoDotCom** [comment]
Another info if you downgrade to PHP 7.4 you will find the zip on Ubuntu 18

**Comment by JoshWho** [comment]
> FYI, I could fix your apt-get, you may be able to upgrade your distro if you want.

If u can please do

**Comment by DanielnetoDotCom** [comment]
> > FYI, I could fix your apt-get, you may be able to upgrade your distro if you want.
> 
> If u can please do

I can try but I need to make clear there is a risk of breaking it, and I can only guarantee that AVideo will work in the latest Ubuntu

**Comment by JoshWho** [comment]
Do what it takes. It can't kill us I hope LOL

**Comment by DanielnetoDotCom** [comment]
All up to date now, Ubuntu 22 and PHP 8.1

**Comment by JoshWho** [comment]
> All up to date now, Ubuntu 22 and PHP 8.1

Thank you so much

**Comment by JoshWho** [comment]
Something funky about how it is working

**Comment by JoshWho** [comment]
Looks like it is saved not sure why it says broken

**Comment by DanielnetoDotCom** [comment]
I guess you should resend all the videos. all the videos in the queue were there when I upgraded your server.

**Comment by JoshWho** [comment]
I see. Thank you
