### ISSUE TITLE
Something weird with characters everywhere HOW did this happen

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8857]
â€¢

![image](https://github.com/WWBN/AVideo/assets/39392449/19aecc95-cd64-4418-8c5c-1a651645e8a0)

![image](https://github.com/WWBN/AVideo/assets/39392449/d0034b7d-5898-4ecd-8078-78d24c380708)

**Comment by JoshWho** [comment]
No clue what's doing that

**Comment by JoshWho** [comment]
The appearance of characters like "â€¢" between certain elements on your website usually indicates a character encoding issue. This often happens when the character encoding used to display the content doesn't match the encoding of the content itself. Here are steps you can take to troubleshoot and fix this issue:

Check Character Encoding Settings: Make sure that the character encoding settings are consistent across all components of your website, including the HTML documents, server configuration, and database. UTF-8 is commonly used and recommended for encoding.

Meta Tag in HTML: Ensure that your HTML documents include a meta tag specifying the character encoding. Place this meta tag within the <head> section of your HTML documents:

html
Copy code
<meta charset="UTF-8">
Server Configuration: Verify that your web server is configured to send the correct Content-Type header specifying the character encoding. This can typically be set in the server configuration files (e.g., Apache's httpd.conf, Nginx's configuration).

Database Character Encoding: Check the character encoding settings of your database. Ensure that it matches the character encoding specified in your HTML documents and server configuration.

File Encoding: Make sure that the files containing your website content are saved with the correct character encoding. Use a text editor that allows you to specify the encoding when saving the files.

PHP Configuration: Check the PHP configuration to ensure that it's using the correct default character encoding. This can be set in the php.ini file with the default_charset directive:

ini
Copy code
default_charset = "UTF-8"
Content Display: If the issue persists, check how the content is being fetched and displayed by your PHP scripts. Ensure that the content is fetched and echoed/displayed correctly without any unintended character encoding conversions.

Browser Settings: Occasionally, browser settings or browser extensions can interfere with character encoding. Try accessing your website from different browsers or devices to see if the issue persists.

By following these steps and ensuring consistent character encoding settings throughout your website's components, you should be able to resolve the issue with characters like "â€¢" appearing between certain elements.

**Comment by Maikuolan** [comment]
"â€¢", transcoded from ANSI to UTF-8, gives "•" (bullet point). Do we have "•" hiding somewhere in the codebase, maybe? If so, that *might* be from where this originates (in terms of the actual bytes themselves). But yeah; Following the above process to fix any potential coding issues would be the best way to go about solving the issue.

**Comment by DanielnetoDotCom** [comment]
this is probably regarding the mysql update.

please send me the ling for this video

**Comment by JoshWho** [comment]
I corrected it in that video but you see it in the Footer text too on the site

**Comment by DanielnetoDotCom** [comment]
if is not a big deal, try to edit the footer. 

the second option is to change all site encoding, but this can also break other texts.

**Comment by JoshWho** [comment]
I think it did it to a lot of things I just haven't looked through it all yet

**Comment by JoshWho** [comment]
https://www.joshwhotv.com/channel/SeekingTheTruth/video/86514/%C3%B0%C5%B8%E2%80%9D%C2%B4%C3%B0%C5%B8%C5%92%C2%90joshwho-tv-%C3%B0%C5%B8%E2%80%9C%C2%BA%7C-news-your-gov-is-a-liar-%C3%B0%C5%B8%E2%80%A2%C2%B5%C3%AF%C2%B8%C2%8F%C3%A2%E2%82%AC%C2%8D%C3%A2%E2%84%A2%E2%80%9A%C3%AF%C2%B8%C2%8F-a-channel-for-intelligent-people.-expand-your-mind.-%7C-seekingthetruth-live-24-7

**Comment by JoshWho** [comment]
https://www.joshwhotv.com/channel/SeekingTheTruth/video/86110/%C3%B0%C5%B8%C5%A1%C2%A8another-obama-secret-basement-microphone-exposed%C3%A2%E2%82%AC%C2%BC%C3%AF%C2%B8%C2%8F-%7C-remember-when-he-said-he-wouldn-t-mind-doing-this

**Comment by DanielnetoDotCom** [comment]
Just add this to your configuration.php

$global['mysqli_charset'] = 'latin1';

try now

**Comment by JoshWho** [comment]
> Just add this to your configuration.php
> 
> `$global['mysqli_charset'] = 'latin1';`
> 
> try now

Thank you all fixed now.
