### ISSUE TITLE
ADs stopped working since recent updates

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8870]
Hi Daniel since last couple of updates the ADs Server stopped working on all three sites, even that which is not behind any proxy, our main streaming site alive528.com. I don't know what to check on this plugin as I don't see anything much in logs. Can you guid me to what I should look for? or what is this plugin depends upon maybe I am missing a PHP library. Maybe My PHP8.1 version is wrong for the installations? IDK as it just suddenly stopped working after one of my recent pulls. I will try to add here any screenshot I will think will add info, but currently I really have none.

This is also true for the AD Overlay.

**Comment by DanielnetoDotCom** [comment]
please share a link where the ADs Server is supposed to appear and it is not.

**Comment by eitanwa** [comment]
hey daniel

https://alive528.com/video/22690

And in all the videos on the entire site

thank so much

**Comment by DanielnetoDotCom** [comment]
Can you please check this update?

**Comment by guymass** [comment]
I made the update. Currently when I open Eitan's URL https://alive528.com/video/22690 I get a messed up page as if the CSS is not working.

![Screenshot 5784-06-26 at 19 09 06](https://github.com/WWBN/AVideo/assets/58882903/535df226-da53-44dc-a16d-bbb998ca8367)
![Screenshot 5784-06-26 at 19 08 58](https://github.com/WWBN/AVideo/assets/58882903/c206e806-fb18-4754-820a-57a7075cf5ae)

Eitan will do the test for the ads and will post how it goes soon.

**Comment by guymass** [comment]
This last update screwed up the entire site, now every video CSS is broken.

**Comment by DanielnetoDotCom** [comment]
Hi, is the CSS still broken?

can you make sure all your plugins are also up to date?

**Comment by DanielnetoDotCom** [comment]
I found the issue, please make another git pull

**Comment by guymass** [comment]
Much thanks bro your the best, all working now including ads, but I will keep this open another 24hr just to make sure as we haven't tested yet all sites.

**Comment by guymass** [comment]
OK we can see that ads don't work yet on our regular video posts but they do work on embedded videos as in this example.

https://alive528.com/article/20660/%D7%94%D7%99%D7%99%D7%A0%D7%95-%D7%A6%D7%A8%D7%99%D7%9B%D7%99%D7%9D-%D7%9C%D7%94%D7%A7%D7%A9%D7%99%D7%91-%D7%9C%D7%A4%D7%95%D7%98%D7%99%D7%9F-%D7%91%D7%9E%D7%A9%D7%9A-%D7%9B%D7%9C-%D7%94%D7%A9%D7%A0%D7%99%D7%9D-%D7%94%D7%90%D7%9C%D7%94

**Comment by eitanwa** [comment]
Just to add on Guy and make it easier for you
in each of the videos on the site
The setting is to show an advertisement in every video
https://alive528.com/

**Comment by DanielnetoDotCom** [comment]
can you please try this now?

**Comment by guymass** [comment]
OK great it seems to work now again, however it doesn't work on Brave maybe something to look into in time. I am closing this post, much thanks.

**Comment by DanielnetoDotCom** [comment]
Brave is probably an ad-blocking. 

Brave has a native one
