### ISSUE TITLE
AD Overlay has some issues inserting code

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8872]
Its time to try and fix this one as well ;-)

The issue of this plugin is related to the areas where one can insert the code for the ad banner that appears on videos as in the following screenshot.

![photo_5784-06-27 13 41 21](https://github.com/WWBN/AVideo/assets/58882903/077219d7-d274-4b81-8068-fff65c433a22)

When we insert the code either ours or google ad code in the main plugin are the code will be saved properly and the add is displayed on the videos just fine. Here is where I am reffering to:

![photo_5784-06-27 13 41 07](https://github.com/WWBN/AVideo/assets/58882903/80bed61f-354a-4326-9eb1-60a184c5403b)

However if we try to insert the same code in the following code sections as in the next two screenshots, the code is not saved or there is no response or error, it just doesn't work on those editor locations.

Here its like it is doing an endless save and gets stuck sometimes for awhile but will not be applied.

![photo_5784-06-27 13 41 11](https://github.com/WWBN/AVideo/assets/58882903/6bff72cd-e160-4bfe-8c2e-97b8c04c6447)

Here it doesn't respond or save at all:

![photo_5784-06-27 13 41 16](https://github.com/WWBN/AVideo/assets/58882903/df0d793f-e6d0-49cd-b6be-fa183d2ebd4d)

It seems that the code should work the same on all those places but it only works on the main plugin itself.

We would love to see this one fixed as it has been like that for over a year now.

**Comment by DanielnetoDotCom** [comment]
Thanks for noticing it, 

I found the bug can you please try again?

**Comment by guymass** [comment]
YESSSSS!!! its working finally ;-), much thanks. Closing this one.

**Comment by eitanwa** [comment]
yesss great much thanks daniel
