### ISSUE TITLE
Online/Offline user status for Jitsi calls doesn't work anymore

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#8881]
We used to be able to see when a user is online and start a Jitsi video call with them but now it doesn't work anymore. Also the user status when they are online or offline isn't showing the proper status. I can be online and still be viewed as offline even when i am logged into the site. Here are some screenshots maybe they can help us find out the problem. Mind that we are also using own private Jitsi server and it is working properly so I am not sure what has changed since last couple of updates.

![photo_5784-06-30 21 52 26](https://github.com/WWBN/AVideo/assets/58882903/aefe598a-0c6a-45ea-a0c3-642e044df61e)
![photo_5784-06-30 21 52 35](https://github.com/WWBN/AVideo/assets/58882903/e4cd95d3-4fda-48d1-8fdb-3e234d590969)
![photo_5784-06-30 21 52 41](https://github.com/WWBN/AVideo/assets/58882903/cc13be7c-9ea5-432f-8e6e-73623b1fbccb)

We would really love to see this feature working again :-)

**Comment by DanielnetoDotCom** [comment]
Only our premium custom jitsi can make livestreams. 

the jitsi you have installed cannot do it. 

I do not think you never could make livestreams with your custom jitsi. you need our modified version. 

out modified version is not free, you need to get it from us

**Comment by guymass** [comment]
OF course we did, we solved this 3 years ago, we can make live stream diretly from our Jitsi. The problem is when I try to use my Jitsi from within the AVideo site using the Custom setting. Then I get those errors, but we can make live streams from our Jitsi to my channel if I wish. The only difference is that our Jitsi onyl allows users which are part of a specific LDAP group, so they need our LDAP credentials to use our Jitsi.

This is when I create a Meet from AVideo and try to enter it, I get this error but if I go to my direct Jitsi URL and start a chat room it works just fine.
 
![Screenshot 5784-07-02 at 16 42 05](https://github.com/WWBN/AVideo/assets/58882903/434a54ed-aa71-4b9e-8fda-4651c4282923)

**Comment by guymass** [comment]
Also wanted to addf that I wasn't going to live stream my Meet, so why do I need streaming services if I just want to start a video chat with someone using my own Jitsi server?

**Comment by DanielnetoDotCom** [comment]
Hi, I do not know what you have done in your jitsi, but by default, jitsi does not make live stream to AVideo. 
Regarding the Chat call it should work, I just tested the meet call here and it works fine. 

just to make sure we are on the same page, where are you clicking to start the call?

**Comment by guymass** [comment]
I create a room here:
![Screenshot 5784-07-02 at 18 42 20](https://github.com/WWBN/AVideo/assets/58882903/f0121ab3-bdf7-4ee6-952e-acda8539d62c)

It was working before no problem with video chats. I still havn't test the direct call to a user but Eitan also tells me it doesn't work. I know there was no option to live stream from jitsi, that is why we developed a specific configuration that we have published to you as well, so we were able to live stream to our site for at least 3-4 years now, maybe even more.

If I create the meat, whether im logged in through LDAP or a regulare user, I should be able to at least access my own room. Also if its an LDAP user, my Jitsi requires access with an LDAP user credentials, so it would be great if AVideo can identify when Jitsi is asking for a user password and test it with the user's credentials, specially if it already an LDAP user.

**Comment by DanielnetoDotCom** [comment]
Sorry I cannot help you with your custom jitsi

**Comment by guymass** [comment]
Hi I just wanted to clarify and understand the service you are offering, otherwise why have a "Custom Jitsi" in the plugin if I cannot use it? Assuming I don't want live stream, why wouldn't it work for simple video calls to online users as before? That doesn't require Live Streaming, that is just a Jitsi chat room for video calls. Shouldn't that at least work without the live stream? because there is no point for having a custom Jitsi if I can't use it right?

Also currently if I use you Jitsi without Live Streaming, just for video chats, it still doesn't work to allow online users to call each other, they can only join an open chat room, so the telephony option also doesn't work when using your servers. Basically this is the only option we wanted, no live streaming, just to use our jitsi to make calls and that was working fine until recently. 

I understand your wish to have a premium jitsi streaming service, but I think that shouldn't interfere with the custom Jitsi configuration unless you remove that option altogether which would be unfortunate as it is one of the great features of this site. I hope you will take into consideration and allow us to use again the basic Jitsi configuration as it once was.

**Comment by DanielnetoDotCom** [comment]
It is supposed to work with the call, and without live stream but I could not reproduce your error here.

**Comment by guymass** [comment]
If I give you the credentials to my Jitsi would you be able to test it? I can email them to you of course.

**Comment by DanielnetoDotCom** [comment]
> If I give you the credentials to my Jitsi would you be able to test it? I can email them to you of course. Just to see if you can view you logs against my service maybe you will know what is wrong. IMO it relates to the LDAP plugin.

Sorry, I am not willing to fix your jitsi
