### ISSUE TITLE
Cannot Update Plugins - Customize Backups, Subscription

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#8896]
hi 

Trying to update the plugins, but they dont seem to show the updated files in the directory. Tried through FTP Filezilla, 
and unzip in command line, but the files do not show up. Dont know what I am doing wrong. Have done this straight forward on previous updates.
Nothing untowards in the logfiles.

Please advise...

**Comment by DanielnetoDotCom** [comment]
Usually, this is due to file permissions. 

https://github.com/WWBN/AVideo/wiki/How-To-Install-a-new-Plugin#addressing-permission-issues

**Comment by kollossus55** [comment]
Followed the instructions, Files still not showing in  directory. Done via unzip and filezilla. Even deleted the plugin/subscription folder and uploaded still showing a few files
![Filezilla transfer](https://github.com/WWBN/AVideo/assets/53856825/45e94004-c7b6-4865-a263-66343e4c1d95)

**Comment by DanielnetoDotCom** [comment]
I can see files are missing, 

are those files missing when you unzip them on your PC? Can you open the folder?

![image](https://github.com/WWBN/AVideo/assets/18009293/49f9cb9a-1cac-4b04-9dc2-c10a419cd1da)

**Comment by kollossus55** [comment]
All the files are in my local drive. I upload them to plugins directory, and you can see them uploading as per logs at the bottom, but once finish it shows just the 4 files and folders. Never come across this before. I have done this previous times no problems..
Cannot see what the problem is.

**Comment by DanielnetoDotCom** [comment]
For example, you are supposed to have all those files in your Subscription plugin 

![image](https://github.com/WWBN/AVideo/assets/18009293/a2048367-3036-4d23-9437-bc5c6e4ad63f)

but in your image, all the PHP files are missing

**Comment by kollossus55** [comment]
Thats the problem. I upload all the subscription plugin  files from the left local server  to my remote website server on the right. You can see them copy across, but once it finishes, it only shows the only the files in pic, there seems to be a problem copying the PHP files.

**Comment by kollossus55** [comment]
I've got bitninja protection software. maybe thats causing the problem.. 
I will uninstall then try again.. That makes sense now..

**Comment by kollossus55** [comment]
yes sorted now.. it was the protection software causingthe issue.. All plugins now uploaded..

Thanks
