### ISSUE TITLE
Default user profile picture

### ISSUE THREAD

**Issue by nathantolene** [WWBN/AVideo#8897]
Is there any way to set a default profile picture for all users?  Of course, I still want them to be able to change it.

**Comment by DanielnetoDotCom** [comment]
You can do it with the Customize plugin

![chrome-capture-2024-2-13](https://github.com/WWBN/AVideo/assets/18009293/3b628078-64ba-4ec9-b4f5-ba9405894bcf)

you can purchase it here https://youphp.tube/marketplace/

**Comment by nathantolene** [comment]
THANK YOU!
