### ISSUE TITLE
image galery

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#8901]
Hey
The image gallery plugin is great and very effective
It would be good if he would get a proper place as a separate tab as well
For now it is under the videos tab
Thanks for your great work

![image](https://github.com/WWBN/AVideo/assets/85537931/80bd89f1-d1f4-477f-a065-25a5edf8bfd7)

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by eitanwa** [comment]
looking great
Thanks Daniel

**Comment by eitanwa** [comment]
Hi Daniel, I now see that after the update
The advanced mode stopped working

![image](https://github.com/WWBN/AVideo/assets/85537931/3cfd180e-07d5-4592-b2da-742f4d0f6ae6)

And the gallery file appears in a distorted view
I am sending a link to an image file 

https://feisafe.com/channel/Feisafe/video/287/test

here some screenshots of the edited interface that שalso went wrong

![image](https://github.com/WWBN/AVideo/assets/85537931/8b535103-9d98-4f4c-baaa-458a687d9aa8)
![image](https://github.com/WWBN/AVideo/assets/85537931/92aa4138-1f83-48e6-9f4e-4827927f2b2b)

thank

**Comment by DanielnetoDotCom** [comment]
thank you, I will check

**Comment by DanielnetoDotCom** [comment]
can you please check this update?

**Comment by eitanwa** [comment]
It looks okay

But the problem of advanced editing still remains
When I click on it, it doesn't go into advanced editing mode
  Instead the following screen opens
As I send in the picture

![image](https://github.com/WWBN/AVideo/assets/85537931/651b3ef7-95bf-46f8-8be1-85f2b3a1dbcd)
 tnk daniel

**Comment by DanielnetoDotCom** [comment]
can you reproduce it on demo site?

check your js console log

**Comment by eitanwa** [comment]
yes the same in the demo 

![image](https://github.com/WWBN/AVideo/assets/85537931/8a8a89ee-b981-4775-bfc3-900113c8f902)

**Comment by DanielnetoDotCom** [comment]
can you please make a git pull and try again?

**Comment by eitanwa** [comment]
So far looks good
tnk
