### ISSUE TITLE
Update didn't go right on Gitpull

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#8912]
![Under-Maintanance](https://github.com/WWBN/AVideo/assets/39392449/6f381248-d640-41c1-b687-a3bc8f9d92a6)

This is what the site looks like after latest git pull

**Comment by JoshWho** [comment]
seems like it is just the homepage that is doing that

**Comment by DanielnetoDotCom** [comment]
Check your js console for errors

**Comment by JoshWho** [comment]
Not sure for what

**Comment by JoshWho** [comment]
![image](https://github.com/WWBN/AVideo/assets/39392449/de301009-a8fc-4faf-9890-93a9816c6ef1)

**Comment by DanielnetoDotCom** [comment]
Check the network tab

Probably there are many files that are not loading 

In the past I saw an issue on your CDN, for some reason it was not loading the files properly 

Remove your CDN , clear the cache and try again

**Comment by JoshWho** [comment]
THere is no cheche other than the images. I do not cache anything scripts. System literally follows what you have set. AS soon as it sees a expire header it does it no delays.

**Comment by DanielnetoDotCom** [comment]
Remove the CDN and test it

**Comment by JoshWho** [comment]
that is not simple

**Comment by DanielnetoDotCom** [comment]
Remove from the plugin

**Comment by JoshWho** [comment]
It is the main Avideo plugin

**Comment by DanielnetoDotCom** [comment]
Probably in customize advanced

**Comment by JoshWho** [comment]
yes

**Comment by DanielnetoDotCom** [comment]
Did you removed?

**Comment by JoshWho** [comment]
No because I have to unlock the plugins first then I have to remove it purge cache then purge cd re lock the plugin

**Comment by DanielnetoDotCom** [comment]
You need to do it

**Comment by JoshWho** [comment]
this is crazy

**Comment by JoshWho** [comment]
It is literally the same website

**Comment by JoshWho** [comment]
I bet it has something to do with plugins not being updated first.

**Comment by JoshWho** [comment]
Updates should even been seen until everything is ready for it plugin wise. should be some kind of checksum failsafe

**Comment by JoshWho** [comment]
Im sitting here eating me some ramen noodles scraping together change for more water Just love life

**Comment by JoshWho** [comment]
I can't access the admin

**Comment by JoshWho** [comment]
I can't even update all the plugins missing Backup, Disk Quota, Video HLS I do not have access to download in the store

**Comment by JoshWho** [comment]
> This is how I see your site ![image](https://private-user-images.githubusercontent.com/18009293/316180382-4d05ec58-a964-46a1-a18f-2e13f772d581.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNjQxNjksIm5iZiI6MTcxMTE2Mzg2OSwicGF0aCI6Ii8xODAwOTI5My8zMTYxODAzODItNGQwNWVjNTgtYTk2NC00NmExLWExOGYtMmUxM2Y3NzJkNTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDAzMTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YWQ5ZmMwZDUwNmFmOTkwMzgyOGNmNjVlZDJhZjliMGQ5OTllZDA0NTkxZWRhOTgxMTBmZTYxY2Q0OGU3ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CGvcDVvIuLS2LaDan_WkZ3ZHlnsH4ZNclPCh1xH1C5Y)

See all the not loaded Icons in your screenshot. Not sure what that is

**Comment by JoshWho** [comment]
GET https://www.joshwhotv.com/ 500 (Internal Server Error)
(index):63 Uncaught ReferenceError: $ is not defined
    at (index):63:13
(anonymous) @ (index):63
(index):154 Uncaught ReferenceError: $ is not defined
    at (index):154:13
(anonymous) @ (index):154
(index):245 Uncaught ReferenceError: $ is not defined
    at (index):245:13
(anonymous) @ (index):245
(index):336 Uncaught ReferenceError: $ is not defined
    at (index):336:13

**Comment by JoshWho** [comment]
My CDN url Loads everything correctly https://static.joshwho-cdn.com/
![JoshWho-TV-Free-Speech-TV-and-Media-·-JoshWho-TV-Free-Speech-TV-and-Media](https://github.com/WWBN/AVideo/assets/39392449/f003e5fe-c7cc-43a1-84ed-a3bf1a47bdde)

The main domain is what is doing this https://www.joshwhotv.com/

![image](https://github.com/WWBN/AVideo/assets/39392449/da470929-a5b7-4459-9303-eae355d935a5)

**Comment by DanielnetoDotCom** [comment]
Try from another pc, your site is loading fine for me

**Comment by JoshWho** [comment]
No I see in your screenshot the non loading icons

**Comment by JoshWho** [comment]
CDN url works fine it is the main that is not loading correctly

**Comment by DanielnetoDotCom** [comment]
It is not loading icons for months 

That is why I am saying it is your CDN

**Comment by JoshWho** [comment]
No go to this https://static.joshwho-cdn.com/ everything loads fine

**Comment by JoshWho** [comment]
> It is not loading icons for months
> 
> That is why I am saying it is your CDN

No go to this https://static.joshwho-cdn.com/ everything loads fine

**Comment by DanielnetoDotCom** [comment]
This is probably a cors issue on your CDN

, Josh you will only know if is your CDN, if you remove it 

And I really this this is the issue

**Comment by JoshWho** [comment]
HOw can there be a cors issue? Image files and static scripts are not supposed to be bound by cors

**Comment by JoshWho** [comment]
Site is still jacked up

**Comment by JoshWho** [comment]
So now my site is still broken

**Comment by DanielnetoDotCom** [comment]
On my side I can see the icons now

![image](https://github.com/WWBN/AVideo/assets/18009293/f46881d2-902b-4234-b20c-0ee79a083c10)

try clear the cookies on your side

**Comment by JoshWho** [comment]
Cookies got changed. SO that was the problem the whole entire time.

**Comment by DanielnetoDotCom** [comment]
the problem is the CDN

**Comment by JoshWho** [comment]
> the problem is the CDN

No I deleted the cookies and now there is a new set for www and non  www   this was not like that before
