### ISSUE TITLE
Where do I find the header settings 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#8946]
Trying to edit this area but can't find it in settings.
Please advise.![Screenshot_20240402_145948_Brave.jpg](https://github.com/WWBN/AVideo/assets/66537018/8493dd45-fe1f-45ee-b44d-5d9fc36eb3b4)

**Comment by DanielnetoDotCom** [comment]
![image](https://github.com/WWBN/AVideo/assets/18009293/7b17943b-59f0-483e-8b25-fe5c668d1f2a)

**Comment by fakeologist** [comment]
Thanks hard to find!
