### ISSUE TITLE
How would I use Bunny.net's HLS encoding platform with AVideo

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8959]
**Is your feature request related to a problem? Please describe.**
Bunny gives me the ability to upload a video, and it transcodes to HLS & provides a player at a URL. I use this for a variety of purposes.
I'd like to drop the URL into AVideo and have it play off of this feature of the CDN.

![Screenshot 2024-04-07 at 1 15 22 PM](https://github.com/WWBN/AVideo/assets/11711050/c6ebae59-09c9-4796-b1d0-627bea8c9fc5)

**Describe the solution you'd like**
Bunny.net give a "direct play URL". I'd like to be able to drop this into the AVideo site on a per-video basis and have it play from this HLS player.

**Comment by DanielnetoDotCom** [comment]
you may want to embed the links then

**Comment by walt93** [comment]
Could you remind me again how I do that? It's been a while and I believe I turned off the embed links setting a long time ago - I don't recall offhand where to enable it.

**Comment by DanielnetoDotCom** [comment]
Make sure this is unchecked 

![image](https://github.com/WWBN/AVideo/assets/18009293/5f696ab8-4c05-4fac-962f-92c34a0ee6a1)
