### ISSUE TITLE
A user's /channel page has ... broken and the /cat page for the user is also having weird issues. Seems related to when I last did a git pull.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#8972]
**Describe the bug**
A user reported in a panic that her page was "gone". On closer inspection, her "/channel" page looks like it's missing and her "/cat" page is not properly showing sub-categories. All her videos appear to be there & her saved "programs" appear intact.

I spot checked several other users accounts, and didn't find any other occurrences of this happening.

**To Reproduce**
1. Go to https://conspyre.tv/channel/truthisknowledge
2. See error (no data / missing data)
![Screenshot 2024-04-10 at 10 57 14 PM](https://github.com/WWBN/AVideo/assets/11711050/22a183ac-337c-489d-aac1-1e7baaa9011a)

1. Go to https://conspyre.tv/cat/truthisknowledge
2. See error (no sub-categories though it says + More (6), the 6 sub-categories cannot be accessed and their tiles do not render

![Screenshot 2024-04-10 at 10 57 38 PM](https://github.com/WWBN/AVideo/assets/11711050/932f94b2-12e8-4c26-a76d-4a1980c99d3e)

**Expected behavior**
Thiis was working for her 2 days ago (Apr 8). I did a git pull yesterday (Apr 9), seems that was the only event in between her successfully accessing ti, and it being broken.

**Comment by DanielnetoDotCom** [comment]
I am not sure what do you mean

channel is not the same as category

**Comment by walt93** [comment]
Daniel I said that both pages are broken. I provided screenshots and descriptions. To "see what I mean" please see screenshots above. Both the /cat and the /channel routes are showing problems for her.

**Comment by walt93** [comment]
I guess what I will do is have her create a new user and I will go in with MySQL and surgically move her videos into her users_id and the same with her programs. It would sure be nice to know why her user account broke after doing a fit pull.........

**Comment by DanielnetoDotCom** [comment]
I am not seeing any issue in any of them

Check what tabs you have enabled

![image](https://github.com/WWBN/AVideo/assets/18009293/fb7ac8f2-2980-4c0c-8360-6b620f3dbf28)

**Comment by walt93** [comment]
I spot checked a few of the other user accounts that I upload videos from, and no issues - it only seems to be hers. If I check any of the others, I am seeing the ChannelVideosTab, ChannelArticlesTab, etc...

they only seem to be missing for the one user.

WHAT can I check in her database records? What can be broken to cause this? I'd like to not have to go create a new user and move all the data in SQL...

![Screenshot 2024-04-11 at 10 07 41 PM](https://github.com/WWBN/AVideo/assets/11711050/958bd697-057a-4b02-b791-ea89baa8e5dc)

Any channel EXCEPT poor Christa (she was really bummed when she thought I deleted her account!):
![Screenshot 2024-04-11 at 10 08 25 PM](https://github.com/WWBN/AVideo/assets/11711050/23ea7ed3-848f-4159-aadd-8ecb737b0727)

And again, Christa's channel AFTER DOING A GIT PULL ON THE 9TH:

![Screenshot 2024-04-11 at 10 09 19 PM](https://github.com/WWBN/AVideo/assets/11711050/a1367bdb-0e95-4949-95c4-399e77b76deb)

**Comment by walt93** [comment]
Nothing in the logfiles related to this error, the /cat or the /channel routes when I tested.

Daniel, I'm not certain how I could explain it any clearer.
1) Her account was working.
2) I did a git checkout on the 9th
3) Her account is now toasted, as you can see above.

Do you have any insight into the database structure and what would be screwed up to cause this or do I have to fix this the hard way?

**Comment by DanielnetoDotCom** [comment]
not really

you are the only one I am aware that is facing this.

I can only help if I can reproduce and debug.

**Comment by walt93** [comment]
Ok well it's 100% reproducible on my site if you wanted to take a look.

Otherwise I'm about to go create a new user, transfer her videos to it, and pray I don't fuck it up worse in the process. I believe all I need to do is change the users_id for her videos, and to change the users_id for her "playlists" (which I believe are her "Programs" which I use to drive the Roku channel)

Any other insight you can offer into transferring her data to a new user before I begin?

**Comment by DanielnetoDotCom** [comment]
Please email me the server credentials

**Comment by DanielnetoDotCom** [comment]
If you run the update you probably do not need to do anything else

**Comment by walt93** [comment]
Ok I just did an update to 14.3 and updated the database via "Update Version" on the main menu. There is no apparent change to the affected users account. I just sent over credentials. Let me know what you see.

**Comment by DanielnetoDotCom** [comment]
The credentials did not work.

but BTW, this category description seems to be weird, 

![image](https://github.com/WWBN/AVideo/assets/18009293/bcae8f29-7418-4d0e-abe8-6a038ea60180)

you  can try to clean it up

**Comment by walt93** [comment]
That happened when I did a backup/restore of the site, it fried a lot of text & it is a lot of work to fix all of it again. :-/

I reported that a long time ago, the last time I did a backup/restore.

Oh, I think I have password login turned off, thats why you can't log in. Can you e-mail me back a SSH pubkey?

**Comment by DanielnetoDotCom** [comment]
I currently do not have any public key setup here, you can create any and then send me the private one

**Comment by DanielnetoDotCom** [comment]
The user TRUTHISKNOWLEDGE cannot upload which is why you do not see videos on her channel

![chrome-capture-2024-3-12](https://github.com/WWBN/AVideo/assets/18009293/2147848c-a3a2-44c9-aabe-19ad2ec2038f)

but looks like you have 2 users with similar usernames and the same channel name 

![chrome-capture-2024-3-12 (1)](https://github.com/WWBN/AVideo/assets/18009293/d8d016e1-ff88-4801-ac48-796bf40d55e1)

this is confusing your system

**Comment by walt93** [comment]
Thanks so much for finding this Daniel! She had made that account forever and a day ago way back when she started!
