### ISSUE TITLE
Upload a Plugin no longer works

### ISSUE THREAD

**Issue by GreenDragonTavern** [WWBN/AVideo#8973]
**Describe the bug**
Procedure to update plugins via gui no longer works. It just hangs doing nothing. Nothing in error log helps (cleared prior to recreating bug).

**To Reproduce**
1. Plugins
2. Click on '+ Upload a Plugin'
3. Nothing...shows file but does not act same prior to git pull.

Can manually update plugin, return to GUI and update version but again, using Upload a Plugin is broken.

**Comment by DanielnetoDotCom** [comment]
Can you please try this update

**Comment by GreenDragonTavern** [comment]
Nice fix, thank you!
