### ISSUE TITLE
Update to 14.3 does nothing except refreshe update page.

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#8975]
@DanielnetoDotCom 
Click update and it just refreshes the page. I updated all plugins and still the update to 14.3 is not working

**Comment by DanielnetoDotCom** [comment]
check your logs

**Comment by milehighkaraoke** [comment]
12-Apr-2024 17:29:33 America/Denver] AVideoLog::ERROR: Time: 12.573s  | Limit: 0.5s | Location: path/to/my/streamer/site/view/sitemap.xml.php Line 2412 [siteMap getAllVideos] IP=95.108.213.222 BOT  USER_AGENT=Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots) backtrace=[{"file":"\/var\/www\/myMySQLUser\/objects\/functions.php","line":2412,"function":"TimeLogEnd","args":["siteMap getAllVideos",2412,0.5]},{"file":"\/var\/www\/myMySQLUser\/view\/sitemap.xml.php","line":45,"function":"siteMap","args":[]}] SCRIPT_NAME: /view/sitemap.xml.php

**Comment by milehighkaraoke** [comment]
12-Apr-2024 23:26:31 UTC] AVideoLog::ERROR: Time: 2.542s   | Limit: 0.5s | Location: path/to/my/streamer/site/view/index.php Line mysql_dal [[SELECT * FROM ip2location_db3 WHERE INET_ATON(?) <= ip_to LIMIT 1], s, ["52.167.144.203"], ] IP=52.167.144.203 BOT  USER_AGENT=Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36 backtrace=[{"file":"\/var\/www\/myMySQLUser\/objects\/mysql_dal.php","line":345,"function":"TimeLogEnd","args":["[SELECT * FROM ip2location_db3 WHERE INET_ATON(?) <= ip_to LIMIT 1], s, [\"52.167.144.203\"], ","mysql_dal",0.5]},{"file":"\/var\/www\/myMySQLUser\/plugin\/User_Location\/Objects\/IP2Location.php","line":39,"function":"readSql","class":"sqlDAL","type":"::","args":["SELECT * FROM ip2location_db3 WHERE INET_ATON(?) <= ip_to LIMIT 1","s",["52.167.144.203"]]},{"file":"\/var\/www\/myMySQLUser\/plugin\/User_Location\/User_Location.php","line":78,"function":"getLocation","class":"IP2Location","type":"::","args":["52.167.144.203"]},{"file":"\/var\/www\/myMySQLUser\/plugin\/User_Location\/User_Location.php","line":74,"function":"getLocationFromIP","class":"User_Location","type":"::","args":["52.167.144.203"]},{"file":"\/var\/www\/myMySQLUser\/plugin\/Cache\/Cache.php","line":93,"function":"getThisUserLocation","class":"User_Location","type":"::","args":[]},{"file":"\/var\/www\/myMySQLUser\/plugin\/Cache\/Cache.php","line":130,"function":"getFileName","class":"Cache","object":{},"type":"->","args":[]},{"file":"\/var\/www\/myMySQLUser\/plugin\/AVideoPlugin.php","line":776,"function":"getStart","class":"Cache","object":{},"type":"->","args":[]},{"file":"\/var\/www\/myMySQLUser\/objects\/include_config.php","line":235,"function":"getStart","class":"AVideoPlugin","type":"::","args":[]},{"file":"\/var\/www\/myMySQLUser\/videos\/configuration.php","line":48,"args":["\/var\/www\/myMySQLUser\/objects\/include_config.php"],"function":"require_once"},{"file":"\/var\/www\/myMySQLUser\/view\/index.php","line":7,"args":["\/var\/www\/myMySQLUser\/videos\/configuration.php"],"function":"require_once"}] SCRIPT_NAME: /view/index.php

**Comment by milehighkaraoke** [comment]
[12-Apr-2024 18:59:22 America/Denver] AVideoLog::SECURITY: isUntrustedRequest: "SAVE live_transmition_history_log" SCRIPT_NAME: /plugin/LiveUsers/view/beat.json.php

**Comment by DanielnetoDotCom** [comment]
sorry no clue in the logs

**Comment by milehighkaraoke** [comment]
Is there a command I could put in the terminal to force a manual update?

**Comment by DanielnetoDotCom** [comment]
yes

```
cd /var/www/html/AVideo/install/
php updatedb.php 

```

**Comment by milehighkaraoke** [comment]
Ok, I got it to update to 14.3 with terminal  However, the update available continues to show...
![Screenshot_20240413_160452_Firefox](https://github.com/WWBN/AVideo/assets/70327833/d2b0c14b-6540-455c-918b-4296fe453d58)

I did get a Undefined variable $template in updatedb.php on line 50 during terminal update.

**Comment by DanielnetoDotCom** [comment]
Try clear the cache and check if the error persists

also try git pull and update again

**Comment by milehighkaraoke** [comment]
Reinstalled fresh....
