### ISSUE TITLE
Crontab to start nginx at reeboot

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#8986]
@DanielnetoDotCom 
What is the directive that I need to put in my crontab to have nginx successfully start when the server reboots.

**Comment by DanielnetoDotCom** [comment]
There are 2 things ...

### Start nginx on restart
`````
@reboot sleep 30; &&  /usr/local/nginx/sbin/nginx 
`````

### The scheduler has a service that is called watchdog, if nginx is off it will try to restart

`````
* * * * * php /var/www/html/AVideo/plugin/Scheduler/run.php
`````

**Comment by milehighkaraoke** [comment]
So, I finally got nginx to start on boot. I had to alter that crontab to. 
@reboot sleep 60 ; sudo /user/local/nginx/sbin/nginx
