### ISSUE TITLE
Fresh Install YPT socket will not connect

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#8987]
i have my port 2053 open and the socket will not connect. I tried several random ports and opened them up in my firewall and regardless the port i use i am returning a 
15-Apr-2024 12:06:11 Africa/Abidjan] PHP Fatal error:  Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:12053": Address already in use (EADDRINUSE) in path/to/my/streamer/site/vendor/react/socket/src/TcpServer.php:184
[15-Apr-2024 08:33:43 America/Denver] PHP Fatal error:  Uncaught RuntimeException: Failed to listen on "tcp://0.0.0.0:2053": Address already in use (EADDRINUSE) in path/to/my/streamer/site/vendor/react/socket/src/TcpServer.php:184

what am i missing @DanielnetoDotCom ?

**Comment by DanielnetoDotCom** [comment]
Maybe it is already running but it is just not connecting due to your firewall.

for testing, I recommend you to completely disable the firewall and test it.

**Comment by milehighkaraoke** [comment]
ufw is inactive

**Comment by DanielnetoDotCom** [comment]
but if is already in use, try to find out what is running on it
Google to learn how to kill it

but I suspect it is already running, and for some other reason, you are not connecting to it.

**Comment by milehighkaraoke** [comment]
php is running on whatever port i put in the ypt socket plugin

**Comment by DanielnetoDotCom** [comment]
Yes, the certificate must be valid

Try to stop the socket before run again

When you run with the command line you can see if the certificate is valid or not

**Comment by milehighkaraoke** [comment]
they are valid....... i am asking if i need to enter their path on any other configurations or if it is just the nginx where they need their path to be configured

**Comment by milehighkaraoke** [comment]
Yes it was running 
![Uploading 20240415_092114.jpg…]()

**Comment by milehighkaraoke** [comment]
Yes it was running 
![20240415_092114](https://github.com/WWBN/AVideo/assets/70327833/c6a7aea3-66d9-479f-a014-167194f37ef6)

**Comment by milehighkaraoke** [comment]
Restarted and it says same thing
![20240415_092451](https://github.com/WWBN/AVideo/assets/70327833/ad26c55c-cac7-4c24-a271-ba75807736fc)

**Comment by milehighkaraoke** [comment]
![20240415_093007](https://github.com/WWBN/AVideo/assets/70327833/75918916-36c6-4099-91c4-8b69874d0ae7)

**Comment by DanielnetoDotCom** [comment]
I can see this is running, 

If you killed it and it still not working, something else is running it.

sorry I am not aware about this error, there is no much I can do and I am pretty sure it is something in your network

**Comment by milehighkaraoke** [comment]
new install, this server is the only thing running on the network and AVideo is the only php that i am using. 

mhk@localhost:~/Desktop$ sudo lsof -i -P -n | grep LISTEN
[sudo] password for mhk: 
systemd-r  424 systemd-resolve   14u  IPv4  21695      0t0  TCP 127.0.0.53:53 (LISTEN)
cupsd      584            root    6u  IPv6  20408      0t0  TCP [::1]:631 (LISTEN)
cupsd      584            root    7u  IPv4  20409      0t0  TCP 127.0.0.1:631 (LISTEN)
apache2    679            root    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2    679            root    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
mysqld     681           mysql   21u  IPv4  24180      0t0  TCP 127.0.0.1:33060 (LISTEN)
mysqld     681           mysql   24u  IPv4  24650      0t0  TCP 127.0.0.1:3306 (LISTEN)
apache2    694        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2    694        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2    696        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2    696        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2    697        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2    697        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2   1359        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2   1359        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
php       2096             mhk    5u  IPv4  29441      0t0  TCP *:2053 (LISTEN)
apache2   2134        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2   2134        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2   2148        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2   2148        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2   2150        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2   2150        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2   2222        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2   2222        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2   2268        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2   2268        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2   3166        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2   3166        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
mhk@localhost:~/Desktop$

**Comment by milehighkaraoke** [comment]
mhk@localhost:~/Desktop$ sudo lsof -i -P -n | grep LISTEN
[sudo] password for mhk: 
systemd-r  424 systemd-resolve   14u  IPv4  21695      0t0  TCP 127.0.0.53:53 (LISTEN)
cupsd      584            root    6u  IPv6  20408      0t0  TCP [::1]:631 (LISTEN)
cupsd      584            root    7u  IPv4  20409      0t0  TCP 127.0.0.1:631 (LISTEN)
apache2    679            root    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2    679            root    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
mysqld     681           mysql   21u  IPv4  24180      0t0  TCP 127.0.0.1:33060 (LISTEN)
mysqld     681           mysql   24u  IPv4  24650      0t0  TCP 127.0.0.1:3306 (LISTEN)
apache2    694        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2    694        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2    696        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2    696        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2    697        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2    697        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2   1359        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2   1359        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
php       2096             mhk    5u  IPv4  29441      0t0  TCP *:2053 (LISTEN)
apache2   2134        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2   2134        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2   2148        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2   2148        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2   2150        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2   2150        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2   2222        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2   2222        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2   2268        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2   2268        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
apache2   3166        www-data    4u  IPv6  24004      0t0  TCP *:80 (LISTEN)
apache2   3166        www-data    6u  IPv6  24008      0t0  TCP *:443 (LISTEN)
mhk@localhost:~/Desktop$

**Comment by milehighkaraoke** [comment]
![20240415_102544](https://github.com/WWBN/AVideo/assets/70327833/fc4d4b86-d695-42ee-bd55-66399ee5119a)

**Comment by GreenDragonTavern** [comment]
@milehighkaraoke - Is Apache only listening on IP6? YTPSocket with IP4 of 0.0.0.0 will use an unsecured connection on localhost and secured connection on whatever IP address is defined for mhktube.com...using IP4 only. BTW, what does ```sudo netstat -nap | grep apache``` come back with?

**Comment by DanielnetoDotCom** [comment]
whatever is using it, kill it

if you want to avoid the auto start, comment out the [scheduler](https://github.com/WWBN/AVideo/wiki/Scheduler-Plugin) from the crontab

after resolving the ports issue put the scheduler back in the crontab

**Comment by milehighkaraoke** [comment]
@GreenDragonTavern 
![20240417_035440](https://github.com/WWBN/AVideo/assets/70327833/7ada53fa-8027-49c5-ae19-8a904e246709)

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom And now it is randomly connecting with one starting it in terminal 
![20240417_051141](https://github.com/WWBN/AVideo/assets/70327833/044c7331-b3c1-4d7c-9208-74b7d7e50a1d)

**Comment by milehighkaraoke** [comment]
After starting on its own, I did a  reboot and it decides it does not want to connect  again. What am I missing?
![17133534758122948006541475011037](https://github.com/WWBN/AVideo/assets/70327833/1135da78-9567-483b-aeaf-fed1f3f76b43)

**Comment by milehighkaraoke** [comment]
That is exactly what I did and the results I am posting are with this in root crontab
![20240417_161820](https://github.com/WWBN/AVideo/assets/70327833/b97d99e5-715c-48f8-ba54-92be47a44df5)
![20240417_161737](https://github.com/WWBN/AVideo/assets/70327833/e8eb47bf-fe8d-40c6-b45d-bc1ce9fe9de3)

**Comment by milehighkaraoke** [comment]
If I use this for install it works everything without fail. Unfortunately this one is laced with bad links and outdated php so I have to change lines as I install. 
How to install LAMP, FFMPEG and Git on a fresh Ubuntu 18.x for AVideo Platform version 4.x or newer

Now going to this new installation code under Wiki  and using the complete installation with all the new links and updated php yields this issue.

The newest installation code is so much faster so it would really be a blessing if we could figure out what's going on wth this so i do not have to waste a complete day using the old installation method..... Thank you @DanielnetoDotCom

**Comment by milehighkaraoke** [comment]
![20240417_173723](https://github.com/WWBN/AVideo/assets/70327833/14447f78-837e-40f7-8769-b3e88c1e4337)
![20240417_161737](https://github.com/WWBN/AVideo/assets/70327833/de57354f-d38c-41fb-af71-e61af47be5b6)

**Comment by milehighkaraoke** [comment]
latest image installed and worked!!!!
