### ISSUE TITLE
start Nginx on boot  no crontab needed?

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#8988]
How to add Nginx to autostart

Execute the command:

systemctl enable nginx

Reboot the server and check if Nginx is running:

service nginx status

How to delay the launch of Nginx
Method 1

Replace the line /etc/systemd/system/multi-user.target.wants/nginx.service in the configuration file Nginx

After=network.target remote-fs.target nss-lookup.target

with

After=network-online.target remote-fs.target nss-lookup.target

Reboot the server and check if Nginx is running:

service nginx status

**Comment by DanielnetoDotCom** [comment]
I do not know about your specific installation

but if you installed as recommended you already got the answer https://github.com/WWBN/AVideo/issues/8986

https://github.com/WWBN/AVideo/issues/8986
