### ISSUE TITLE
Every random port that i assign for ypt socket says in use

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#8992]
@DanielnetoDotCom 
Here is the grep listen...... Notice every random port that I have opened for the socket automatically is in use by system php....
![20240417_045201](https://github.com/WWBN/AVideo/assets/70327833/5ef3125a-f9a1-44ab-bad2-c8964ea2ec8b)
![20240417_035440](https://github.com/WWBN/AVideo/assets/70327833/2403e606-c478-40bc-bf91-16ca61ac22c4)

**Comment by DanielnetoDotCom** [comment]
I do not know why you opened a new issue , if you keep the questions on the same thread you may find the answers, I will close it to keep organized
