### ISSUE TITLE
Many error after installation ( liveStreaming ) 

### ISSUE THREAD

**Issue by verticalhost** [WWBN/AVideo#8993]
Hi , after following simple step for installation. 
I activated live stream by enable it and now i have webpage showing this" 

Doo you have any idea what causing it ? 

![image](https://github.com/WWBN/AVideo/assets/100486259/e5c9e094-6bd4-4c38-b9bc-7111212ce113)

**Comment by DanielnetoDotCom** [comment]
I have no idea how this could happen, but here is an update that will prevent the crash

**Comment by verticalhost** [comment]
After re-installing

i have this : 
![image](https://github.com/WWBN/AVideo/assets/100486259/356ee30a-f78b-438d-9bae-9be0290d9c2f)
 
 Seem Nginx dont like me

**Comment by verticalhost** [comment]
i am not sure if i have to remplace all localhost by AVVideo URL  there : /usr/local/nginx/conf/nginx.conf  

I can see everything is localhost and also 127.0.0.1 not mentionned on doccumentation to change it

**Comment by DanielnetoDotCom** [comment]
Make sure all your plugins tables are installed 

Check the plugins manager page

**Comment by verticalhost** [comment]
Seems it working thanks
