### ISSUE TITLE
Video is missing after upload

### ISSUE THREAD

**Issue by verticalhost** [WWBN/AVideo#8994]
Sorry to reach you again. 
Soon i upload any video from public encorer the video is missing

![image](https://github.com/WWBN/AVideo/assets/100486259/27c574b1-1910-4a4d-a4b1-ff74be95e133)

**Comment by verticalhost** [comment]
Also when i am on stream no notification nothing is showing channel is running but we can manually click to watch the stream it works

**Comment by DanielnetoDotCom** [comment]
check your logs

**Comment by verticalhost** [comment]
`[18-Apr-2024 16:30:42 America/Toronto] AVideoLog::DEBUG: contentSearchFound NOT FOUND [{"file":"\/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/modeGallery.php","line":21,"function":"include"},{"file":"\/var\/www\/html\/AVideo\/view\/index_firstPage.php","line":58,"args":["\/var\/www\/html\/AVideo\/plugin\/Gallery\/view\/modeGallery.php"],"function":"require"},{"file":"\/var\/www\/html\/AVideo\/view\/index.php","line":20,"args":["\/var\/www\/html\/AVideo\/view\/index_firstPage.php"],"function":"include"}] SCRIPT_NAME: /view/index.php
[18-Apr-2024 16:30:42 America/Toronto] AVideoLog::DEBUG: contentSearchFound NOT FOUND LAST SQL SELECT STRAIGHT_JOIN  u.*, u.externalOptions as userExternalOptions, v.*,  nv.title as next_title, nv.clean_title as next_clean_title, nv.filename as next_filename, nv.id as next_id, c.id as category_id,c.iconClass,c.name as category,c.iconClass,  c.clean_name as clean_category,c.description as category_description, v.created as videoCreation , (SELECT `like` FROM likes as l where l.videos_id = v.id AND users_id = '1' LIMIT 1 ) as myVote  FROM videos as v LEFT JOIN categories c ON categories_id = c.id LEFT JOIN users u ON v.users_id = u.id LEFT JOIN videos nv ON v.next_videos_id = nv.id  WHERE 1=1  AND u.status = 'a'  AND (  v.status IN ('a','k','f','h') OR v.status = 'p'  ) AND v.id != 1  SCRIPT_NAME: /view/index.php
[18-Apr-2024 16:30:42 America/Toronto] AVideoLog::DEBUG: contentSearchFound NOT FOUND LAST TOTAL SQL SELECT count(v.id) as total FROM videos v LEFT JOIN categories c ON categories_id = c.id  LEFT JOIN users u ON v.users_id = u.id  WHERE 1=1  AND u.status = 'a'  AND v.status IN ('a','k','f','h') SCRIPT_NAME: /view/index.php
[18-Apr-2024 16:30:42 America/Toronto] AVideoLog::DEBUG: Live::getInfo LiveStreamObject= => , , ,  SCRIPT_NAME: /plugin/Live/latestOrLive.php
[18-Apr-2024 20:30:45 UTC] AVideoLog::DEBUG: getPasswordFromUserHashIfTheItIsValid: string not decrypted _user_hash_M1hVWnh4cnBUSldiRitHTy9EMitKdE5kbEtpNUZNWUsvdVFxYU53WlJ3ZmV3cDRHSTJXOUIvMSt0c29SbmkxWldBc0JGWm SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 UTC] AVideoLog::DEBUG: Password check Old encoded pass SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 UTC] AVideoLog::DEBUG: Password check Old not found SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 UTC] AVideoLog::DEBUG: getPasswordFromUserHashIfTheItIsValid: string not decrypted _user_hash_M1hVWnh4cnBUSldiRitHTy9EMitKdE5kbEtpNUZNWUsvdVFxYU53WlJ3ZmV3cDRHSTJXOUIvMSt0c29SbmkxWldBc0JGWm SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 UTC] AVideoLog::DEBUG: Password check Old not encoded pass SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 UTC] AVideoLog::DEBUG: Password check Old not found SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 UTC] AVideoLog::DEBUG: loginFromRequest NOT FOUND admin SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 UTC] AVideoLog::DEBUG: getPasswordFromUserHashIfTheItIsValid: string not decrypted _user_hash_M1hVWnh4cnBUSldiRitHTy9EMitKdE5kbEtpNUZNWUsvdVFxYU53WlJ3ZmV3cDRHSTJXOUIvMSt0c29SbmkxWldBc0JGWm SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 UTC] AVideoLog::DEBUG: Password check Old encoded pass SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 UTC] AVideoLog::DEBUG: Password check Old not found SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 UTC] AVideoLog::DEBUG: getPasswordFromUserHashIfTheItIsValid: string not decrypted _user_hash_M1hVWnh4cnBUSldiRitHTy9EMitKdE5kbEtpNUZNWUsvdVFxYU53WlJ3ZmV3cDRHSTJXOUIvMSt0c29SbmkxWldBc0JGWm SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 UTC] AVideoLog::DEBUG: Password check Old not encoded pass SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 UTC] AVideoLog::DEBUG: Password check Old not found SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 UTC] AVideoLog::DEBUG: loginFromRequest NOT FOUND admin SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 Africa/Abidjan] AVideoLog::DEBUG: login.json.php user found [admin] SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 Africa/Abidjan] AVideoLog::DEBUG: User::find line= 1642 SCRIPT_NAME: /objects/login.json.php
[18-Apr-2024 20:30:45 Africa/Abidjan] AVideoLog::DEBUG: User:login finish with success users_id=1 SCRIPT_NAME: /objects/login.json.php
`

**Comment by DanielnetoDotCom** [comment]
You need to get the logs when the encoder finish to process a video and transfer it

**Comment by verticalhost** [comment]
I saw on logs to install 2 plugins required. 
But unable to solve the prob when some one start stream why it's not showing they streaming or showing on page

**Comment by verticalhost** [comment]
[avideo.log](https://github.com/WWBN/AVideo/files/15030300/avideo.log)

**Comment by DanielnetoDotCom** [comment]
your log is incomplete

**Comment by verticalhost** [comment]
Let's doo 1 things by 1 

First.. When i start stream exemple with OBS.. 
I can stream on air .. but on website nothing as showing up i am streaming but i double check and url 
https://video.verticalpixelzone.com:8443/stats

This record 1 session so means NGINX is correct.

**Comment by verticalhost** [comment]
Second here is the Video upload test failed and complete logs.
[avideo.log](https://github.com/WWBN/AVideo/files/15030585/avideo.log)

**Comment by DanielnetoDotCom** [comment]
Your nginx is not installed https://video.verticalpixelzone.com:8443/

**Comment by DanielnetoDotCom** [comment]
> Second here is the Video upload test failed and complete logs. [avideo.log](https://github.com/WWBN/AVideo/files/15030585/avideo.log)

same log, no difference

**Comment by verticalhost** [comment]
> Your nginx is not installed https://video.verticalpixelzone.com:8443/

Re-check is valide sorry at same time i restart it on time you checked

**Comment by DanielnetoDotCom** [comment]
you should create 2 different issues, one for your live server and another for your encoding videos. 

in both issues, you must provide more precise and complete information. for now, there is not enough info in both of them

**Comment by verticalhost** [comment]
[avideo.log](https://github.com/WWBN/AVideo/files/15030638/avideo.log)
This is the new log files second test upload. 
I joined video to proof somethings missing if you not having full logs. 
https://streamable.com/67ebkh

**Comment by verticalhost** [comment]
I drop you also new issue for Livestream here : https://github.com/WWBN/AVideo/issues/8995

**Comment by DanielnetoDotCom** [comment]
> [avideo.log](https://github.com/WWBN/AVideo/files/15030638/avideo.log) This is the new log files second test upload. I joined video to proof somethings missing if you not having full logs. https://streamable.com/67ebkh

same log again

**Comment by verticalhost** [comment]
> > [avideo.log](https://github.com/WWBN/AVideo/files/15030638/avideo.log) This is the new log files second test upload. I joined video to proof somethings missing if you not having full logs. https://streamable.com/67ebkh
> 
> same log again

It's the same logs gave me each time i c'ant doo better if it's same for you something is worng on server.. 
On video i showed you i removed the log to clean it first on : /var/www/html/AVideo/videos/

**Comment by DanielnetoDotCom** [comment]
I need a complete log when you submit a video to the encoder, the log must also contain the logs when the encoder finishes the process

**Comment by verticalhost** [comment]
[bunnytestavideo.log](https://github.com/WWBN/AVideo/files/15030736/bunnytestavideo.log)
New logs

**Comment by DanielnetoDotCom** [comment]
Looks like you have pligins that you did not install the tables, make sure all the tables are installed, even the ones you are not using

**Comment by verticalhost** [comment]
Still not working. 
I am pretty sure the lastest version occured mulitple prob.. 
it's not my first installation of Avideo and first time this append for me

**Comment by DanielnetoDotCom** [comment]
I am running the latest in many sites

Now you install all the tables , try to encode again and share the new logs

**Comment by verticalhost** [comment]
I can confirm you . 
I installed it on fresh VPS and got same result no capable of reading any video : https://vide.vps.webdock.cloud/channel/admin/video/1/he-spent-3-years-begging-me-for-a-pc.-good-luck-finding-it

**Comment by DanielnetoDotCom** [comment]
share the logs

**Comment by verticalhost** [comment]
[avideo.log](https://github.com/WWBN/AVideo/files/15031187/avideo.log)

**Comment by DanielnetoDotCom** [comment]
Your video is there 

https://vide.vps.webdock.cloud/videos/video_240418223325_v3bd6/video_240418223325_v3bd6_480.mp4
https://vide.vps.webdock.cloud/videos/video_240418223325_v3bd6/video_240418223325_v3bd6_720.mp4

but it is not playing, looks like it is corrupter

what video is that? how can I test it from my side?

**Comment by verticalhost** [comment]
test with 

admin 
123soleil

it's test instance so no worry

**Comment by DanielnetoDotCom** [comment]
I need the video to test from my side, for some reason it is not playing

**Comment by verticalhost** [comment]
https://github.com/WWBN/AVideo/assets/100486259/1e95775e-83f4-4882-9597-729f04b0e9d6

**Comment by verticalhost** [comment]
It's append also for Youtube video any kinds of

**Comment by DanielnetoDotCom** [comment]
I see now, it happens with any video?

so I have no idea, I can only imagine is something on your network. maybe a proxy, if you can access the file directly try to download videos/video_240418223325_v3bd6/video_240418223325_v3bd6_480.mp4 without use the http protocol, and test the video

I just made  a clean instalaltion for a customer, and all tested/encoded videos are working. sorry I cannot reproduce it, so there is nothing I can do to help you

**Comment by verticalhost** [comment]
Nothing is not on HTTP it's very strange cause i followed exact things you have on guide.

**Comment by DanielnetoDotCom** [comment]
# your video

https://vide.vps.webdock.cloud/videos/video_240418223325_v3bd6/video_240418223325_v3bd6_480.mp4

![image](https://github.com/WWBN/AVideo/assets/18009293/8f5cb03a-18bc-46c4-967e-4e06d44ce0b1)


# a regular video

https://videos.forjesus.tv/videos/video_200414195835_1b06/video_200414195835_1b06_SD.mp4
![image](https://github.com/WWBN/AVideo/assets/18009293/f840c3ab-77dc-4401-abef-7b8ecce2ad73)

Definitely something on your network

**Comment by verticalhost** [comment]
I can 100% tell you i followed the exact guide you have. 
Nothing change on my side. I know you show me this. but it's append for every single video even if it's from youtube etc..
Nothing as change SSL is installed everywhere with let'S encrypt 

All corresponding to it ...

**Comment by DanielnetoDotCom** [comment]
try to manually upload with ftp a video to your server, try to play it using https

check if the error persists, if persists, open a ticket on Contabo

**Comment by DanielnetoDotCom** [comment]
> I can 100% tell you i followed the exact guide you have. Nothing change on my side. I know you show me this. but it's append for every single video even if it's from youtube etc.. Nothing as change SSL is installed everywhere with let'S encrypt
> 
> All corresponding to it ...

my guides does not cover the network, this is something with your and your server provider. there is nothing I ca do

**Comment by verticalhost** [comment]
> try to manually upload with ftp a video to your server, try to play it using https
> 
> check if the error persists, if persists, open a ticket on Contabo

It's playing without any issue.

**Comment by DanielnetoDotCom** [comment]
share the link

**Comment by verticalhost** [comment]
https://video.verticalpixelzone.com/videos/big_buck_bunny.mp4

**Comment by verticalhost** [comment]
If you think it's ssl why i have the lock and saying let's encrypt

**Comment by verticalhost** [comment]
![image](https://github.com/WWBN/AVideo/assets/100486259/af61fee3-3a65-4a33-9f18-5c2d3c8f56ef)

**Comment by DanielnetoDotCom** [comment]
I do not know, it is your network

**Comment by verticalhost** [comment]
> I do not know, it is your network

Network or not Contabo and Webdock as same issue OVH aswell Linode and many others.. 
How you can explain it ?

**Comment by verticalhost** [comment]
You have some provider in head you know it's maybe working ?

**Comment by DanielnetoDotCom** [comment]
I use OVH for myself

**Comment by verticalhost** [comment]
> I use OVH for myself

Like i say OVH are not working aswell getting same error. 
So ....it's not network

**Comment by DanielnetoDotCom** [comment]
> > I do not know, it is your network
> 
> Network or not Contabo and Webdock as same issue OVH aswell Linode and many others.. How you can explain it ?

to to upload a video to a directory that does not use the AVIdeo

**Comment by verticalhost** [comment]
i am testing on DigitalOcean now
Let,s see

**Comment by verticalhost** [comment]
I confirm you i have same issue on OVH Baremetal server. 
I joinded the AVIDEO LOGS
[avideo.log](https://github.com/WWBN/AVideo/files/15046502/avideo.log)

Doo you thinks it's somethings that certbot fucked 
Here is the Nginx conf 

`user    www-data;    
worker_processes  1;
    error_log  logs/error.log debug;
    events {
            worker_connections  1024;
    }
    rtmp {
            server {
                    listen 1935;
                    ping 5m; 
                    ping_timeout 4m;
                    ### Use case option (max_streams; default is 32 )
                    #max_streams 10;
                    allow play all;
                    #creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
                    application live {
                            allow play all;
                            live on;
                            hls on;
                            hls_nested on;
                            hls_path /HLS/live;
                            hls_playlist_length 60m;
                            hls_fragment 4s;
                            drop_idle_publisher 30s;
                            sync 500ms;
                            #Experimental. Force dropped stream, or ended stream from being watched. (idle_streams)
                            #idle_streams off;
                            on_publish http://localhost/AVideo/plugin/Live/on_publish.php;
                            on_publish_done http://localhost/AVideo/plugin/Live/on_publish_done.php;
                            on_play http://localhost/AVideo/plugin/Live/on_play.php;
                            on_record_done http://localhost/AVideo/plugin/Live/on_record_done.php;
                            
                            #exec ffmpeg -re -i rtmp://localhost/live/$name -c:v libx264 -preset veryfast -c:a copy -f hls -hls_time 5 -hls_list_size 0 -f flv rtmp://localhost/adaptive/$name_hi;
                            #exec ffmpeg -re -i rtmp://localhost/live/$name 
                            #    -c:v libx264 -vf scale=-2:240 -r 20 -g 40 -keyint_min 40 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 400k -maxrate 700k -bufsize 1400k -c:a aac -strict -2 -b:a 96k -f flv rtmp://localhost/adaptive/$name_low  
                            #    -c:v libx264 -vf scale=-2:480 -r 30 -g 60 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 1200k -maxrate 2100k -bufsize 4200k -c:a aac -strict -2 -b:a 128k -f flv rtmp://localhost/adaptive/$name_mid  
                            #    -c:v libx264 -vf scale=-2:720 -r 30 -g 60 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -b:v 2400k -maxrate 3000k -bufsize 6000k -c:a aac -strict -2 -b:a 128k -f flv rtmp://localhost/adaptive/$name_hi;


                            #recorder video {
                            #    record all manual;
                            #    record_path /var/www/tmp;
                            #    record_notify on;
                            #    record_max_size 2048M; 
                            #    record_suffix -%d-%b-%y-%T.flv;
                            #}
                    
                            ### Record Audio Separately ( For podcast )
                            #recorder audio {
                            #    record audio;
                            #    record_path /var/www/tmp;
                            #    record_max_size 1024M;
                            #    record_suffix -%d-%b-%y-%T.mp3;
                            #}
                    }

                    #application adaptive {
                    #    live on; 
                    #    hls on; 
                    #    hls_fragment 2s;
                    #    hls_path /HLS/live;
                    #    hls_nested on;
                    #    hls_playlist_length 10m;
                    #    allow play all;
                    #    allow publish 127.0.0.1;
                    #    deny publish all;

                    #    hls_variant _hi BANDWIDTH=264000,RESOLUTION=1280x720; # this is for line 34 only, do not uncomment it
                    #    hls_variant _low BANDWIDTH=900000;
                    #    hls_variant _mid BANDWIDTH=2400000;
                    #    hls_variant _hi  BANDWIDTH=3500000;
                    #}
            }
    }
    http {
            include       mime.types;
            default_type  application/octet-stream;
            server {
                    #listen 8443 ssl;
                    #listen [::]:8443 ssl;
                    #include /usr/local/nginx/snippets/self-signed.conf;
                    #include /usr/local/nginx/snippets/ssl-params.conf;
                    listen 8080;
                    server_name beta.verticalpixelzone.com;
                    #creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
                    location /live {
                            expires 60;
                            add_header 'Cache-Control' 'public';

                            location ~ \.m3u8$ {
                                expires -1;
                                # Disable cache
                                add_header 'Cache-Control' 'no-cache';

                                # CORS setup
                                add_header 'Access-Control-Allow-Origin' '*' always;
                                add_header 'Access-Control-Expose-Headers' 'Content-Length';
                            }

                            # CORS setup
                            add_header 'Access-Control-Allow-Origin' '*' always;
                            add_header 'Access-Control-Expose-Headers' 'Content-Length';

                            # allow CORS preflight requests
                            if ($request_method = 'OPTIONS') {
                                    add_header 'Access-Control-Allow-Origin' '*';
                                    add_header 'Access-Control-Max-Age' 1728000;
                                    add_header 'Content-Type' 'text/plain charset=UTF-8';
                                    add_header 'Content-Length' 0;
                                    return 204;
                            }
                            types {
                                    application/vnd.apple.mpegurl m3u8;
                            }
                            alias /HLS/live;
                    }
                    #allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
                    #location /stats {
                    #        stub_status;
                    #}
                    location /stat {
                            rtmp_stat all;
                            rtmp_stat_stylesheet stat.xsl;
                    }
                    location /stat.xsl {
                            root html;
                    }
                    location /control {
                            # replace this with the IP of your AVideo site
                            allow 127.0.0.1;
                            deny all;
                            rtmp_control all;
                    }
                    #allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
                    location / {
                            root   html;
                            index  index.html index.htm;
                    }   

                    #location ~ \.php$ {
                    #       include /etc/nginx/snippets/fastcgi-php.conf;
                    #       fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
                    #}

            
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/beta.verticalpixelzone.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/beta.verticalpixelzone.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
    }
`

**Comment by DanielnetoDotCom** [comment]
Sorry I have no idea what is wrong with your installation,

maybe is the SSL but I have never seen this before

**Comment by verticalhost** [comment]
> Sorry I have no idea what is wrong with your installation,
> 
> maybe is the SSL but I have never seen this before

Sir i try to say you lot's of time it's something on guide are not writed correctly to let's any one install it. 

With all respect doo you want i record any video to show you all process i did as proof

**Comment by verticalhost** [comment]
> Sorry I have no idea what is wrong with your installation,
> 
> maybe is the SSL but I have never seen this before

Hi , 
Just to let's you know after hiring some one to help me here all modification was missing on Guide to let's it working. 


1- use external encoder, because the one that is included serves badly encoded files.
2- change PID file in /lib/systemd/system/nginx.service to /usr/local/nginx/logs/nginx.pid
3- make the url in the /usr/local/nginx/conf/nginx.conf to remove /AVideo/
4- you need to shutdown apache2 first to generate the certificate for nginx

**Comment by milehighkaraoke** [comment]
I just deleted the pid file.

**Comment by milehighkaraoke** [comment]
I also have no saved video and this is the first time this has happened to me in 3 years.

**Comment by verticalhost** [comment]
> I also have no saved video and this is the first time this has happened to me in 3 years. #8998

I try to tell @DanielnetoDotCom something is not working on this side form the script and guide it self but he dont seems to try him self to make compare.

**Comment by milehighkaraoke** [comment]
I got tired of playing and wasting time.  I wiped my ssd's clean and started from scratch. Onlthis time I started at root.  Sudo -I   and installed absolutely everything from root and it is all working perfectly now....

**Comment by milehighkaraoke** [comment]
I have to say it works really nice now, no lag and really responsive.  Oh on reinstall do not enter domain names in NGINX for encryption, Apache takes care of that. Only skip that one step. You have to complete the steps after. Anyway this is how I got mine going
