### ISSUE TITLE
Live Stream - Not showing anything live on main page

### ISSUE THREAD

**Issue by verticalhost** [WWBN/AVideo#8995]
I currently have Ubuntu 22.04 installed and I'm using the installation script to complete the server setup. I've also installed the live plugin and left the configuration at default. When I start a live session, nothing appears on the main page, but if I force the stream page and click on the stream itself, I can see my content.

Here is video to show you : https://streamable.com/aouzwh

**Comment by DanielnetoDotCom** [comment]
do you have the socket and the scheduler running?

check your admin health check page, screenshot and share it here

**Comment by verticalhost** [comment]
> do you have the socket and the scheduler running?
> 
> check your admin health check page, screenshot and share it here

![image](https://github.com/WWBN/AVideo/assets/100486259/f3482160-d2f8-449e-8880-bc163d822ec2)

**Comment by DanielnetoDotCom** [comment]
make sure your socket plugin and scheduler are running properly

**Comment by verticalhost** [comment]
> make sure your socket plugin and scheduler are running properly

It's running and still nothing showing on live stream : 
![image](https://github.com/WWBN/AVideo/assets/100486259/46784c1f-af6d-435c-9e75-547a6d50e924)

**Comment by DanielnetoDotCom** [comment]
I see, if is not showing, then you should start a live and also check your logs

**Comment by milehighkaraoke** [comment]
This is what mine did until I changed my on publish to my servers IP in the NGINX config.

**Comment by milehighkaraoke** [comment]
copy your current on publish and paste it into your browser and see what it returns. It should return a blank page. a 404 is no good

**Comment by milehighkaraoke** [comment]
I had to change my on_publish to
http://your server I-P/plugin/Live/on_publish.php

**Comment by milehighkaraoke** [comment]
I hope this helps your situation
