### ISSUE TITLE
The encoder redirects to the default site encoder1.wwbn.net

### ISSUE THREAD

**Issue by verticalhost** [WWBN/AVideo#8999]
When I click on the button for the encoder, it sends me back to the default website, even after I've modified it to send it to the right place.

Also if you look at it from another perspective, 
Sending to the public encoder means that the password is never good.

![image](https://github.com/WWBN/AVideo/assets/100486259/96235069-53d6-413a-a204-201724afdefa)

https://github.com/WWBN/AVideo/assets/100486259/8bcc26b1-6ed5-4c45-8058-88a4718b744f

**Comment by DanielnetoDotCom** [comment]
you do not have an encoder network, you are not supposed to change that

check this for more details about the network

https://github.com/WWBN/AVideo-Encoder-Network
