### ISSUE TITLE
Error 524 - Move files Local to storage 

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9007]
@DanielnetoDotCom Danny, regarding the transfer of files from the local server to storage.
I can make the transfer, but apparently files larger than 1 GB cannot complete the transfer.
I can view the file on the storage, but the Streamer does not update it.
It seems to me that the transfer takes place a Time Out due to the size of the file....
What is error 524?

![image](https://github.com/WWBN/AVideo/assets/37880073/1aacaf3c-bf88-4d47-ad6d-07febb99865b)

![image](https://github.com/WWBN/AVideo/assets/37880073/850670cc-ee04-4b04-990f-6df32204ebf2)

**Comment by tcreek** [comment]
I would check the php.ini configuration to check the size limit of files.

**Comment by DanielnetoDotCom** [comment]
Are you using Cloudflare?

Error 524 indicates a timeout error and is specifically associated with Cloudflare. 

Cloudflare is strongly not recommended.

**Comment by gbrn** [comment]
Dear all, I managed to solve it.
@DanielnetoDotCom Yes, I am using Cloudflare. But I managed to get around the problem:

I disabled AVideo Storage's Cloudflare PROXY function, kept only the DNS service.
![image](https://github.com/WWBN/AVideo/assets/37880073/f4a78daf-049f-4274-aba8-8ed8edb6df90)

Result ok:
![image](https://github.com/WWBN/AVideo/assets/37880073/c791b4dc-4e31-40ac-9497-e2e35e33f879)
