### ISSUE TITLE
SecureVideosDirectory  Plugin doesn't play Videos

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#9008]
Hi Dan,

I  updated the system (clone) to Ubuntu 20.04 & 22.04 and since videos doesn't play anymore.
All files in videos are accessible accept the *.mp4 files. Videos are stored on /mediafolder and worked pefect before the update.

XSendfile is working:
 {
    "test": "VideosDirectory"
}
The encoder sends file properly (gif, jpg & mp4) to the videofolder but can't read the mp4_file the encoder stored.
The videos are stored on  /media/Avideo/videos  

Avideo & Apache_logs gives no hint only this message in console

![Snap20](https://github.com/WWBN/AVideo/assets/39981177/6a959ff2-f50b-4cf5-972e-666b4c04a31b)

Videos stored in /media/test (not in avideo) working perfect,

**Comment by TLCReuver** [comment]
Found another Error:
![Snap21](https://github.com/WWBN/AVideo/assets/39981177/6b5b6240-3d3a-47a4-9e1d-a9c114ec8e3b)

**Comment by DanielnetoDotCom** [comment]
If you disable the plugin, does it work?

**Comment by TLCReuver** [comment]
Disabling the plugin gives the same result.
Its very strange that only the videos in folder Avideo does not work... other folders in the same root gives no problem.

**Comment by DanielnetoDotCom** [comment]
So I guess it has nothing to do with the plugin, but probably something on the XSendfile 

what is your site domain?

**Comment by TLCReuver** [comment]
>>So I guess it has nothing to do with the plugin, but probably something on the XSendfile

I was thinking that too but installing gives no error

Clonesite on: http://media.beesel-reuver.nl:8080

sudo apt-get install libapache2-mod-xsendfile && sudo a2enmod xsendfile
Pakketlijsten worden ingelezen... Klaar
Boom van vereisten wordt opgebouwd       
De statusinformatie wordt gelezen... Klaar
libapache2-mod-xsendfile is reeds de nieuwste versie (0.12-2).
0 opgewaardeerd, 0 nieuw geïnstalleerd, 0 te verwijderen en 15 niet opgewaardeerd.
Module xsendfile already enabled

**Comment by DanielnetoDotCom** [comment]
you are right your xsendfile is working 

but I am not sure what is wrong with your network http://media.beesel-reuver.nl:8080/videos/video_240405120000_v1855/video_240405120000_v1855_1080.mp4

**Comment by TLCReuver** [comment]
First i tried to install on Ubuntu 22.04 but because of this issue 20.04 is now installed

To easy switch between versions it is running under the latest "Oracle VM VirtualBox" like the old 18.04 that is working perfect.

Permissions like
sudo adduser root vboxsf & sudo adduser www-data vboxsf are made but i noticed that all connectitons made are with ip 10.0.2.2

**Comment by TLCReuver** [comment]
I make a new fresh install, it is faster than to solve this problem(s).

Th@nkz for replies
