### ISSUE TITLE
Is there an API or script to call which could replace a videos image?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#9029]
**Describe the question**
Many videos have "meh" poster frames and we can quickly generate dope posters with AI. But the process to replace an image is tedious requiring many steps to complete. 

If I had an API or endpoint I could quickly have the bot code a page for me to jackhammer in poster frames in one workflow optimized fell swoop. 

Does such a thing (API/endpoint) exist?

**Comment by DanielnetoDotCom** [comment]
Sorry I do not have this API yet
