### ISSUE TITLE
Is 720 the highest resolution when saving a stream?

### ISSUE THREAD

**Issue by gregk63** [WWBN/AVideo#9032]
**Describe the question**
Is 720 the highest resolution when saving a stream? I don't see how I can increase it.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
Hi, the recorder saves in the same resolution as you stream. so if you stream in 1080 it will be saved in 1080

**Comment by gregk63** [comment]
Thank you! I found the OBS setting to adjust it.
