### ISSUE TITLE
Changing the encoder in "Advanced Configuration" does not work. THe system continues to use the old encoder.

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#9064]
**Describe the bug**
Changing the encoder does not work; the system continues to use the old encoder.

**To Reproduce**
0. Because your encoder does not work (is stuck, see previous bug report), install a new one.
1. Go to Site Configurations
2. Click on Advanced Configuration
3. Enter the address of your new encoder
4. Save the configuration
5. Open the encoder
6. Observe that it is the previous encoder. The one you just provisioned is not used.

**Expected behavior**
The system to use the encoder it is told to.

**Comment by walt93** [comment]
Update: After doing a clear cache directory / Rebuild site map / standing on my head and waving a rubber chicken - it worked.

You should not need to do the chicken dance when we have changed configuration and hit "Save". "Save" should flush the  cache.

**Comment by DanielnetoDotCom** [comment]
I am not sure what you mean, Is it still a problem with the new encoder?
