### ISSUE TITLE
Is there a new update for the network encoder / install instructions?

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#9065]
**Describe the bug**
I didn't note the errors which occurred when I went to install the network encoder, it was a couple of weekends ago. Apologies for the very thin bug report, is there a plan to update this soon?

Also just realized I cannot find this in the Wiki now to even re-check it... I don't recall where this was, in the github repo? Appreciate if you could link it here so I can retry & report findings.

**Comment by milehighkaraoke** [comment]
open terminal in your encoder directory and sudo git pull

**Comment by walt93** [comment]
The Network encoder is a separate app. I'll find it I guess. Thanks.
