### ISSUE TITLE
subtitle plugin is not working

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#9102]
Greetings mr @DanielnetoDotCom  please help fix the subtitle plugin it is not showing the subtitles.

**Comment by DanielnetoDotCom** [comment]
can you please give more details?

make sure you clear the cache.

**Comment by mrgodgiven** [comment]
Cache is cleared. I had to re install the whole site thinking it was buggy, but still the plugin does not work for about 3 months now. please play this video https://livefaces.live/channel/Admin/video/2/the-book-of-daniel

**Comment by DanielnetoDotCom** [comment]
I got this in your site

![image](https://github.com/WWBN/AVideo/assets/18009293/37e9ba61-6544-4d40-ae7c-d56bce0af79a)

**Comment by mrgodgiven** [comment]
Please try this one https://livefaces.live/video/.3AzluReAIpiTc6Ngwi_yxw

**Comment by DanielnetoDotCom** [comment]
can you please update your SubtitleSwitcher plugin to version 6.4?

**Comment by mrgodgiven** [comment]
Now it works thanks
