### ISSUE TITLE
Can't upload poster @ direct uload video

### ISSUE THREAD

**Issue by TLCReuver** [WWBN/AVideo#9143]
Hi Dan,

When (direct) upload a video everything is okay but uploading a image (poster) i got 'You can't edit this file'.

When i manually edit the video and change the image (poster) it is okay.

So i have to upload the video without poster and afterwards i have to add it manually by editing the video.

No erros foumd,  last update with last plugins & chown -R www-data:www-data /var/www/.. & chmod -R 777 /var/www/..

![_Snap14](https://github.com/WWBN/AVideo/assets/39981177/4caf28f8-b573-4979-a810-33ac8f74eda9)

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by TLCReuver** [comment]
That was a turbo quick fix.... :) 

Working fine now.

Thanks
