### ISSUE TITLE
Display easiest video ID

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9147]
@DanielnetoDotCom Danny, I would like to request that you display the easiest video ID, along with the video information in the information column. An example is this video that has the status of "Broken Missing files". I need the video ID to resend the video and overlay it.
Thanks!

![image](https://github.com/WWBN/AVideo/assets/37880073/466f6a1d-b94d-4673-9926-8ec8cc26fb91)

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by gbrn** [comment]
Very good Danny! This update will speed things up a lot! Thanks for your attention!
![image](https://github.com/WWBN/AVideo/assets/37880073/fc7bfc59-3c50-4cae-806a-6474ad6c73fe)
