### ISSUE TITLE
Need help disabling password salt

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9150]
Working on a new installation and already had a user account enabled password salt now can't login as admin

**Comment by JoshWho** [comment]
I turned Salt on and got locked out

**Comment by JoshWho** [comment]
Salt should be on by default. I seen it was off and turned it on and now why I am in this situation.

**Comment by JoshWho** [comment]
How can I disable the Salt via Mysql to turn it off?

**Comment by JoshWho** [comment]
I would really hate to have to resinstall

**Comment by JoshWho** [comment]
There is no simple table for this setting seems like it is is in a college of other settings in a table instead of it being its only table to change.

**Comment by JoshWho** [comment]
Please help me here @DanielnetoDotCom

**Comment by JoshWho** [comment]
or just resetting the admin password please

**Comment by JoshWho** [comment]
I ended up doing it in the MYSQL

**Comment by DanielnetoDotCom** [comment]
Hi sorry for the late reply

next time you can try this

https://github.com/WWBN/AVideo/wiki/Reset-a-Password#reset-plugins-configuration
