### ISSUE TITLE
I have a bug wit adding categories

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9158]
When I click save nothing saves.

![Screenshot - 2024-06-25T151833 853](https://github.com/WWBN/AVideo/assets/39392449/ea7ac302-743b-4f71-a46d-451703c11a63)

I do not see anything in the log saying why

**Comment by DanielnetoDotCom** [comment]
if there is nothing in the log, check the js console and ajax request

https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform#javascript-errors

**Comment by JoshWho** [comment]
It is a fresh install not sure why it would not work

**Comment by JoshWho** [comment]
Cache had to purge then they all showed up. Weird.
