### ISSUE TITLE
Is there a way to disable the Dynamic Encode?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9163]
I remember my old encoders didn't use the dynamic encoding and was much faster how to disable that so it just process the 720p? Please and thanks

![Screenshot - 2024-06-26T155231 315](https://github.com/WWBN/AVideo/assets/39392449/9bc2d6b4-931f-4970-a17f-edab9c827cf1)

**Comment by DanielnetoDotCom** [comment]
I am not sure what you mean, and it does not supposed to be faster

**Comment by JoshWho** [comment]
I had it to where dynamic was not a thing and it just did the formats all separated 1 at a time. Dynamic makes all the formats at the same time.
