### ISSUE TITLE
Dark theme wont save keeps going back to light

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9177]
Not sure why or what is doing this. I want Cyborg to be the default theme and everytime I set it is goes back to the light default theme. 

![Screenshot - 2024-07-03T024914 719](https://github.com/WWBN/AVideo/assets/39392449/063d055c-aa7a-45b9-bb1d-25053afe7a94)

Now when I come back to the Themes in a new page load it is back to the light theme

![Screenshot - 2024-07-03T025020 300](https://github.com/WWBN/AVideo/assets/39392449/25def4c8-bac6-47fb-8e1b-50c486728b8a)

**Comment by DanielnetoDotCom** [comment]
I am not sure what you have done, but I tested it on demo site and it works as expected

https://demo.avideo.com/admin/?page=design_themes

![image](https://github.com/WWBN/AVideo/assets/18009293/7fb23885-47fc-4f87-9f4a-ccb45b63fd94)

**Comment by JoshWho** [comment]
I haven't done anything, I am still getting it set up from fresh install

**Comment by DanielnetoDotCom** [comment]
you did many things, specially your security adds

sorry, this always work on my installation.  I cannot help you

**Comment by JoshWho** [comment]
My security is just a firewall. I did nothing to the code. Everything is exact as the last git pull
