### ISSUE TITLE
Need to know the meeting ports I need open on firewall

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9178]
what ports need to be open for the Meeting thing on here?

**Comment by JoshWho** [comment]
![Screenshot - 2024-07-03T041018 468](https://github.com/WWBN/AVideo/assets/39392449/5c60d01b-4594-4560-8df0-4e08a506431c)

**Comment by DanielnetoDotCom** [comment]
sorry I am not 100% but should be the default ports.

check what is jitsi default ports

**Comment by JoshWho** [comment]
Says north american server offline but when I click custom that one goes green but never creates a meeting room.

**Comment by JoshWho** [comment]
What is the ip of the north american server?

**Comment by JoshWho** [comment]
Can you tell me what port that is using?

**Comment by DanielnetoDotCom** [comment]
> Can you tell me what port that is using?

All jitsi default ports, I do not have it mapped, but the server check should be ports 80/443

**Comment by JoshWho** [comment]
Jitsi Meet uses the following default ports:

80 TCP - for SSL certificate verification/renewal with Let's Encrypt
443 TCP - for the main secure access to the web UI
10000 UDP - for general network video/audio communications
22 TCP - if you are using SSH to manage your server (recommended)

**Comment by JoshWho** [comment]
Please confirm to me the ip of the north american server

**Comment by DanielnetoDotCom** [comment]
149.56.107.4

**Comment by JoshWho** [comment]
am I supposed to install Jitsi video bridge or something?
