### ISSUE TITLE
Seek Buttons not showing on player is there somthing needing chaged?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9179]
I do not see thew  seek buttons on the player what do I need to turn on seek. I have the Seek plugin Enabled but not showing.
![image](https://github.com/WWBN/AVideo/assets/39392449/d3d6bff2-26b1-499d-937b-724f9fea3e55)

![Screenshot - 2024-07-03T204217 777](https://github.com/WWBN/AVideo/assets/39392449/f9efffb6-f1dd-4c28-a898-069d27e7dc89)

**Comment by DanielnetoDotCom** [comment]
there was a bug, it is fixed now

it suppose to be hidden only if the screen is small

and you can set what will be hidden here 

![image](https://github.com/WWBN/AVideo/assets/18009293/5c24c1d0-0053-466d-9a86-a5eebbddca6f)

**Comment by JoshWho** [comment]
Thank you
