### ISSUE TITLE
Question about the max Post and File Size for the main streamer site

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9182]
I just realized my main streamer site was set to 1 Gig for max post and max file size.  Would this cause an issue when a encoding server tries to transfer something over larger than that?

I had some bad transfers again today but it seems they were really large when I test a small file it uploads fine. 

I am trying a large upload now with the main streamer being set at 10G now so hoping that solves this.

**Comment by DanielnetoDotCom** [comment]
Usually on my installations I make minimum 8GB max post, but the best is to check the logs to get some clues
