### ISSUE TITLE
Disable encoding of import files that are already encoded

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9184]
Needs to be an option to just import from youtube the file they already have without encoding. JUst make it like a direct mp4 upload.

Basically cutting out the extra work of re encoding it.  JUst grab the file and add it to the channel. No encoding.

**Comment by JoshWho** [comment]
No one wants to chime in about this?

**Comment by DanielnetoDotCom** [comment]
I cannot guarantee yt-dlp will be able to download a mp4, it download different formats

also there is no guarantee the mp4 is compatible with the webbrowser. 

so, for now it is not a good idea
