### ISSUE TITLE
User Login history just keeps showing repeated bad logins that never happens

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9195]
![Screenshot - 2024-07-10T020024 195](https://github.com/WWBN/AVideo/assets/39392449/ee2d3130-ced3-454c-964f-a5a2bd850dbc)

No clue why. It is my ip and my browser but that's not me trying to login

**Comment by JoshWho** [comment]
Does this only show failed logins? I browse them all and I do not ever see it say correct or successful. If so the Lang should be changed to  "Failed Login attempts."

**Comment by JoshWho** [comment]
No answers? So this is new

**Comment by DanielnetoDotCom** [comment]
For now you can ignore it. 

it is regarding the 2FA, but it is still under development.

**Comment by JoshWho** [comment]
> For now you can ignore it.
> 
> it is regarding the 2FA, but it is still under development.

kk no probs just seeing. I had another user asking me about it.
