### ISSUE TITLE
Question about Video Offline

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9198]
What does converting all videos to video offline format actually do?

![Screenshot - 2024-07-10T161719 270](https://github.com/WWBN/AVideo/assets/39392449/2eb10358-844c-419f-a37d-47e1e352b297)

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/VideoOffline-Plugin#pre-convert-all-your-videos
