### ISSUE TITLE
EMBED is missing the video link

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9200]
`<div class="embed-responsive embed-responsive-16by9" style="position: relative;padding-bottom: 56.25% !important;"><iframe width="640" height="360" style="max-width: 100%;max-height: 100%; border:none;position: absolute;top: 0;left: 0;width: 100%; height: 100%;" src="" frameborder="0" allow="fullscreen;autoplay;camera *;microphone *;" allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" msallowfullscreen="msallowfullscreen" oallowfullscreen="oallowfullscreen" webkitallowfullscreen="webkitallowfullscreen" scrolling="no" videoLengthInSeconds="7235">iFrame is not supported!</iframe></div>`

https://ftjmedia.com/channel/GiuseppeVafanculo/video/.X3rbrTXUQrpPQsqS4O780w/the-sane-asylum-249-based-hump-day---10jewlie24---guest-pk-from-panama

![Screenshot - 2024-07-10T220127 742](https://github.com/WWBN/AVideo/assets/39392449/e4cdc98f-c2c5-4857-8ccf-549f6a194720)

**Comment by JoshWho** [comment]
Even on your demo site it is doing the same thing

https://demo.avideo.com/video/430/1-hour-timer---beautiful-ocean-sunset-relaxing-and-calm-music

**Comment by DanielnetoDotCom** [comment]
please try this update

**Comment by JoshWho** [comment]
> please try this update

Solved that did the trick. Thank you @DanielnetoDotCom
