### ISSUE TITLE
Twitter card is broken

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9201]
![Screenshot - 2024-07-10T232147 673](https://github.com/WWBN/AVideo/assets/39392449/1f4e1838-c09b-4168-9c57-7be941ac09ea)

The Sane Asylum  https://ftjmedia.com/channel/GiuseppeVafanculo/video/.X3rbrTXUQrpPQsqS4O780w/the-sane-asylum-249-based-hump-day---10jewlie24---guest-pk-from-panama FTJ Media 😎

**Comment by DanielnetoDotCom** [comment]
maybe it is related to this issue https://github.com/WWBN/AVideo/issues/9200

please check

**Comment by JoshWho** [comment]
> maybe it is related to this issue #9200
> 
> please check

Yup that fixed it. Thank you
