### ISSUE TITLE
Is there a way to also encode an MP3 last when a file gets imported or uploaded?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9203]
I have someone asking me to be able to have a mp3 version, of the video file, also available for download. Is there any way to make this work?

So basically when the enoder makes the different formats it can also include just a mp3 version of it? and make it available for download.

**Comment by DanielnetoDotCom** [comment]
Currently there is no such option

**Comment by JoshWho** [comment]
We will pay for this addon if u can make a price and think it is possible.

**Comment by DanielnetoDotCom** [comment]
Hi, if you want please send me details on developer@youphptube.com, so I can quote it

**Comment by JoshWho** [comment]
Email sent

**Comment by JoshWho** [comment]
Payment sent

**Comment by JoshWho** [comment]
I was seeing the download mp3 buttons under the videos but now it seems it all went away. Do I have to enable the convert all videos to mp3 or is that something different?

**Comment by DanielnetoDotCom** [comment]
Hi, 

do you mean the buttons disapears or is not creating the mp3 for the new ones?

**Comment by JoshWho** [comment]
> Hi,
> 
> do you mean the buttons disapears or is not creating the mp3 for the new ones?

Both I do not see it anymore under the new videos

**Comment by DanielnetoDotCom** [comment]
but do you stil see on old videos?

**Comment by JoshWho** [comment]
Yes Looks like older ones still have it
![Screenshot (33)](https://github.com/user-attachments/assets/8ce8f991-d2de-4509-a490-761f8a34d093)

**Comment by JoshWho** [comment]
![Screenshot (34)](https://github.com/user-attachments/assets/4a92c087-6860-46a9-a4de-662d9c89f2fa)

**Comment by DanielnetoDotCom** [comment]
Ok, the issue is they are not converting. you can use this script to convert the videos manually

you can add it in the crontab so it will execute periodically and it will scan your videos and will convert the mp3 if the file does not exists 

````
php /var/www/html/AVIdeo/install/getMp3FromAll.php
````

**Comment by JoshWho** [comment]
Should I run it every minute?

**Comment by JoshWho** [comment]
Terminal spit this out when I ran it

PHP Warning:  require_once(../videos/configuration.php): Failed to open stream: No such file or directory in /var/www/html/AVideo/install/getMp3FromAll.php on line 3
PHP Fatal error:  Uncaught Error: Failed opening required '../videos/configuration.php' (include_path='.:/usr/share/php') in /var/www/html/AVideo/install/getMp3FromAll.php:3
Stack trace:
#0 {main}
  thrown in /var/www/html/AVideo/install/getMp3FromAll.php on line 3

**Comment by JoshWho** [comment]
Kewl that did the trick, Thank you will add it once an hour.
