### ISSUE TITLE
encoder network recommends offline server

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9204]
![Screenshot - 2024-07-12T024009 346](https://github.com/user-attachments/assets/b5ef3020-0e32-4e1f-ae77-14dde67ec37c)

**Comment by DanielnetoDotCom** [comment]
clearly something is blockling access to your encoder, maybe cors. 

try to inspect the js console

**Comment by JoshWho** [comment]
Not it was rebooting, I still do not know why it would recommend a encoder that wasn't online.

**Comment by DanielnetoDotCom** [comment]
I agree it should not be recommended, also it should not be offline

**Comment by JoshWho** [comment]
Anything showing offline should be not available when it does it test
