### ISSUE TITLE
Plugin Justwatch

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9205]
@DanielnetoDotCom Danny, this time I'm not coming here for a problem. I now come to congratulate you on the new integration of the Justwatch Plugin. Brilliant idea, this site is excellent at indexing and cataloging content.
I'm going to start these immediately.
CONGRATULATIONS!

**Comment by DanielnetoDotCom** [comment]
Appreciate that, thanks

**Comment by gbrn** [comment]
@DanielnetoDotCom I know the Plugin is still very new... but could you tell me which way to register my content on the Justwatch website?

**Comment by DanielnetoDotCom** [comment]
I do not know how you will register on justWatch but they will use this feed https://youriste.com/plugin/JustWatch/feed.json.php

for example https://flix.avideo.com/plugin/JustWatch/feed.json.php

**Comment by gbrn** [comment]
@DanielnetoDotCom Danny, I'm in contact with JustWatch, I've provided the JSON Feed URL for them to review. They informed me the following:

> ...our team already took a look at the feed you sent us, and they only saw offers for US. If you want your service to be listed in BR we also need the offers for BR so we can display it on the titles for that market. 

Could you tell me if when you developed JSON it was only for the US scenario? How to create the file for Brazil?

**Comment by DanielnetoDotCom** [comment]
I see,

Please check this update and edit the plugins parameter "country_iso"

**Comment by gbrn** [comment]
@DanielnetoDotCom I have some bad news... JustWatch no longer accepts free registrations... unfortunately.
