### ISSUE TITLE
How can I force Low Res to only use 240p instead of 480p?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9206]
![Screenshot - 2024-07-12T152415 782](https://github.com/user-attachments/assets/bbee581b-6a22-4630-8742-e4cdcb8804ba)

So far this will only make it 480p/ How to change that?

**Comment by DanielnetoDotCom** [comment]
I am not sure what you mean

**Comment by JoshWho** [comment]
Right now with the settings you see above forces encoder to use HD and LD and those are only 720p and 360p and wondering if there was a way to add a lower definition to the custom advance here.

**Comment by DanielnetoDotCom** [comment]
you can replace the resolution in the encoder configuration ffmpeg code

**Comment by JoshWho** [comment]
I did that but it is not like a global kind of thing across the whole code. SHould be more options here to say not show or show.
