### ISSUE TITLE
When fast forwarding streams in 2x it should auto go back to 1x once it is back to the current Realtime.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9208]
Users that pause and then want to catch up to a live stream in fast play says it stays stuck in fast play on MacOS  14.3.1 once it reaches the realtime of the live.

**Comment by JoshWho** [comment]
Is this possible @DanielnetoDotCom ?

**Comment by JoshWho** [comment]
![-9-Skype](https://github.com/user-attachments/assets/fbc0c70e-348a-4233-aa24-1bb257f8d82c)

**Comment by JoshWho** [comment]
![-9-Skype (1)](https://github.com/user-attachments/assets/1db95882-d2f1-4fc5-91a3-deaf2ab70873)

**Comment by DanielnetoDotCom** [comment]
I do not control it, it is a videojs feature. 

and continue in 2x when is realtime does not make sense
