### ISSUE TITLE
After a git pull (JUL 13 12:11PM PST) site menus do not function and cannot proceed with "Update Site" menu action from UI

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#9211]
**Describe the bug**
Just did a git pull

![Screenshot 2024-07-13 at 12 13 13 PM](https://github.com/user-attachments/assets/a26f586f-7315-42f6-881c-8df981554c0c)

**Expected behavior**
Menus should continue to work after a git pull

**Comment by DanielnetoDotCom** [comment]
Clear the cache if it persists check the js console 

Maybe you also have paid plug-ins updates

**Comment by DanielnetoDotCom** [comment]
Also check your AVideo.log

**Comment by walt93** [comment]
Cannot clear cache as clear cache is available through the menus.

Do not see anything relevant in the log. https://pastebin.com/R34gPWjf

Claude 3.5 Sonnet sees a bunch of slow execution times:

----
Based on the log snippets provided, there are a few concerning issues that could be related to the menu functionality problems:

1. There are multiple errors related to slow execution times, particularly in the navbar and category top buttons sections:

```
AVideoLog::ERROR:      Time: 5.692s   | Limit: 0.7s | Location: /var/www/html/conspyre.tv/view/index.php Line 14 [CategoryTopButtons]
AVideoLog::ERROR:      Time: 5.680s   | Limit: 0.2s | Location: /var/www/html/conspyre.tv/view/index.php Line 178 [navbar.php]
```

These slow execution times could be causing timeouts or performance issues that affect the menu functionality.

2. There are warnings about plugins taking too long to execute, particularly the Layout plugin:

```
AVideoLog::WARNING:    The plugin [Layout::navBarAfter] takes 5.68 seconds to complete.
```

This suggests that the Layout plugin, which likely handles some menu-related functionality, is experiencing performance issues.

3. There are database-related warnings indicating that certain queries are not finding expected results:

```
AVideoLog::DEBUG:      contentSearchFound NOT FOUND LAST SQL SELECT
```

This could indicate potential data inconsistencies or missing information that the menus rely on.

4. There are multiple errors related to exceeding time limits across various parts of the application, which could be causing overall instability:

```
AVideoLog::ERROR:      Time: 2.450s   | Limit: 0.2s | Location: /var/www/html/conspyre.tv/view/modeYoutube.php Line 166 [navbar.php]
```

To address these issues and potentially restore menu functionality, you might want to:

1. Check your server resources to ensure they are sufficient for the upgraded version.
2. Review any changes in the database schema or data migration steps that might have been required for the upgrade.
3. Clear caches and temporary files.
4. Check plugin compatibility with the new version and consider disabling problematic plugins temporarily.
5. Review your AVideo configuration, particularly any settings related to execution time limits or database connections.
6. Consider rolling back to the previous version if the issues persist and are severely impacting site functionality.

If you continue to experience issues, you may need to consult the AVideo documentation or support channels for version-specific troubleshooting steps.

**Comment by walt93** [comment]
I determined that some (but not all) files in the AVideo directory were of the wrong owner (plugins, some AdBlockerDetector which I have not previously used).

After fixing permissions site is happy again.
