### ISSUE TITLE
Video won't play because it is trying to play the Low Offline Download which shouldn't be apart of the standard selections

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9212]
![Screenshot - 2024-07-13T215550 049](https://github.com/user-attachments/assets/2fb4f828-e272-4af5-8b94-9902e851e4f4)

https://ftjmedia.com/channel/FLOOD/video/.AsmchOaKHqoiuKR8zCXziQ/the-flood---071224---0326---fuhrerfriday-without-davis-lurmann-on-12-jul-24-10-54-29

![image](https://github.com/user-attachments/assets/65d1d1f7-bbec-4134-986d-27919e4fa86e)

**Comment by DanielnetoDotCom** [comment]
I see, you are using the offline video. 

the offline video is not tested on the backblaze, I am not sure if it will work with it.

**Comment by DanielnetoDotCom** [comment]
Another thing, I suspect all the offline videos are not being transferred to your B2, so it may consume space in your disk 

I am not sure if it is a good idea for you.

**Comment by JoshWho** [comment]
I disabled it now video works again
