### ISSUE TITLE
Disable hover text for ad block

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9214]
![Screenshot - 2024-07-14T095345 514](https://github.com/user-attachments/assets/159dd989-3a7c-4295-98ed-65d1c39bbd8f)

**Comment by DanielnetoDotCom** [comment]
This only shows for admin 

Regular users do not see it

**Comment by JoshWho** [comment]
> This only shows for admin
> 
> Regular users do not see it

Ahhhh I c thank you
