### ISSUE TITLE
Centering the Live streams on home page

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9226]
A way to just add like a center tag to the whole row of live streams at the top so they start in the center and not on the left. 

`<center>     Live Stream Row   </center>`

**Comment by DanielnetoDotCom** [comment]
<center>  is HTML deprecated tag

I am not sure what you want to do, but you probably can center it with a custom CSS

**Comment by JoshWho** [comment]
Not sure how u would do that in css

**Comment by JoshWho** [comment]
![Screenshot - 2024-07-15T164111 445](https://github.com/user-attachments/assets/c0849a5d-79d2-4d20-ba0b-48ed151e3cb5)

**Comment by JoshWho** [comment]
Like this
![bbbb](https://github.com/user-attachments/assets/44b5af05-33de-474a-a7e0-7a7cd3c47734)

**Comment by DanielnetoDotCom** [comment]
We are using Bootstrap 3, and it is a grid system. 

I cannot say is impossible to do it, but it for sure will be pretty hard

**Comment by JoshWho** [comment]
What about making the Live row block embedable? 

Then I can just turn off the normal one on home page, and then embed it back with the center tags in a top ad block.

**Comment by DanielnetoDotCom** [comment]
It may work, but for me this change does not worth 

Currently I am not interested in this change
