### ISSUE TITLE
Live on Home starts muted Is there a setting to change on this?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9234]
![Screenshot - 2024-07-16T234642 186](https://github.com/user-attachments/assets/3af7fc26-c5d9-4002-8f57-39a4538e0738)

How to enable controls when you hover over it?

**Comment by JoshWho** [comment]
Our site starts **Muted** and I do not see anyway that changes https://ftjmedia.com/

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Autoplay-and-Browser-Policies#important-note-on-browser-control

**Comment by DanielnetoDotCom** [comment]
Play with sound or not is a brower decision. 

maybe is something in your SSL or apache configuration.

**Comment by JoshWho** [comment]
> Play with sound or not is a brower decision.
> 
> maybe is something in your SSL or apache configuration.

Not sure. I am wondering if it is a setting in custom advance maybe that I do not have unchecked or checked.
