### ISSUE TITLE
categories interface

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#9235]
Hi Daniel, how are you?

Is it possible to hide only one of the categories from the menu?
without deleting it?

![image](https://github.com/user-attachments/assets/0ff4d835-1cce-48a5-bdbb-057f5ab6bc8f)

I thought that what should determine whether it is offered or not, is what appears in the picture

![image](https://github.com/user-attachments/assets/309a8224-4e41-4277-a01c-84a5a2d12af8)

So if it's not a bug, what does this button control?
And is it possible to hide a certain category from the menu

This interface has had some bugs for a long time
1) The images always lose their proportion
This happens after a certain period of time or after making changes to other settings such as name description and so on

![image](https://github.com/user-attachments/assets/5409573f-5de4-47c4-aa4d-ded24673b025)

2) I don't know if it's a bug or that's how it's supposed to be
This is supposed to be parent categories, but it also creates the possibility of subcategories, is this correct?

![image](https://github.com/user-attachments/assets/11c96a41-7c19-4dad-a605-4c6eca8a4ad3)

Thank you

**Comment by DanielnetoDotCom** [comment]
**Is it possible to hide only one of the categories from the menu without deleting it?**

- No, it's not possible to hide only one category from the menu without deleting it.

**If this is not a bug, what does this button control?**

- No, this is not a bug. This button is intended to display a section on the first page.

**Is it possible to hide a certain category from the menu?**

- Again, no. It's not possible to hide a category from the menu without deleting it.

**The images always lose their proportion. This happens after a certain period of time or after making changes to other settings such as name, description, etc.**

- I am aware of this issue, but currently, I have no solution.

**This is supposed to be for parent categories, but it also creates the possibility of subcategories. Is this correct?**

- Yes, this is correct.

**Comment by eitanwa** [comment]
Thanks Daniel
for the answer and accuracy
