### ISSUE TITLE
show more/less

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#9237]
Hi Daniel

I am sending you screenshots from the mobile (web)
After clicking on show more, the inscription aligns to the left
and leaves the center
I'm almost sure it's a bug because it's only on mobile (web) and not on PC
 after you click again on show less, it doesn't align again
I tested it in several languages ​​and on several of our platforms
Thanks again Daniel

b4
![image](https://github.com/user-attachments/assets/025b9eb4-68ce-4c5e-bc61-cb66536e9b3f)

after
![image](https://github.com/user-attachments/assets/2ba65c41-90ba-40da-903e-fd30a956fcc2)

**Comment by DanielnetoDotCom** [comment]
does this happen in all videos descriptions? or only in a specific description?

**Comment by eitanwa** [comment]
Hi Daniel, thank you for answering
in all of them
I checked in several of our systems and in several languages,
It has been a long time for at least half a year

**Comment by DanielnetoDotCom** [comment]
Can you please ty this update?
