### ISSUE TITLE
Videos have disappeared

### ISSUE THREAD

**Issue by rapiz** [WWBN/AVideo#9240]
For a few weeks, without making changes, some videos have disappeared, they are in the DB, but their folder in /xxx/videos/zzzz is empty, could you help me get some idea of ​​what may be happening?

![image](https://github.com/user-attachments/assets/4f9ee6a4-d5b1-4958-99bb-4a6c4100c590)

**Comment by eitanwa** [comment]
Hi, this is a bug I think we've encountered for a while now
It has to do with the release date of the video
Go there and change manually, it usually works

![image](https://github.com/user-attachments/assets/8a902641-9855-42bc-8170-f5022d57d97c)

**Comment by rapiz** [comment]
Thanks, but that's not the problem. If yo seen in the screenshot, the video was online and had views. The problem is that the encoded files have disappeared from the disk

**Comment by eitanwa** [comment]
I have seen and know this problem
 That's why I wrote to you
Have you tried changing? As I have shown

**Comment by DanielnetoDotCom** [comment]
Hi

there is no code to remove files and leave the video directory /xxx/videos/zzzz

maybe the video was never there. 

if this is happening, may be something in your server
