### ISSUE TITLE
One person updating their live stream title is changing someone else's?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9245]
Always the same 2 accounts seems like one channel grabs the info from the other channel everytime they go live. 

What could cause such a thing?

**Comment by JoshWho** [comment]
I figured it out, some how they both had the same stream key. Solved by changing one of them.

**Comment by JoshWho** [comment]
This just happened again and this time they they do not have admin privileges' so not sure how sessions are mixing and give 2 users the same stream key

**Comment by DanielnetoDotCom** [comment]
what user exactly?

can you provide the key and user ids?

**Comment by JoshWho** [comment]
User IDs is  https://ftjmedia.com/channel/GiuseppeVafanculo

and     https://ftjmedia.com/channel/Davis

**Comment by DanielnetoDotCom** [comment]
What common key do they have?

**Comment by JoshWho** [comment]
> What common key do they have?

Just a sec will login as them

**Comment by JoshWho** [comment]
This is  GiuseppeVafanculo
![Screenshot - 2024-08-28T152015 245](https://github.com/user-attachments/assets/cd9a1628-f0d2-4732-a928-c86e1b75e39a)
rtmp://ftjmedia.com/live?s=RHFVS1RqMzB2ZGdaWUFJQVR5ZXFiZz09&webSiteRootURL=aHR0cHM6Ly9mdGptZWRpYS5jb20v

669a1d9ca15ba-1

This is Davis Lurman

![Screenshot - 2024-08-28T152226 038](https://github.com/user-attachments/assets/f68860ab-28a9-45e8-adff-baa045c24a94)

rtmp://ftjmedia.com/live?s=Rm9CaXhLQ2t3YlkveDVubklQSFh3UT09&webSiteRootURL=aHR0cHM6Ly9mdGptZWRpYS5jb20v

66c917068eb66-1

**Comment by DanielnetoDotCom** [comment]
the keys are different

also you should not share it, there are sensitive info on it. 

you may want to investigate who got the wrong key, because the keys are different from where I can see

**Comment by JoshWho** [comment]
No both of those ended with the same last segments did u not see the tail ends of those?

**Comment by DanielnetoDotCom** [comment]
what last segment?

`&webSiteRootURL=aHR0cHM6Ly9mdGptZWRpYS5jb20v`?

this will be the same for all on your site

**Comment by JoshWho** [comment]
=aHR0cHM6Ly9mdGptZWRpYS5jb20v       this is at the end of both stream urls

**Comment by DanielnetoDotCom** [comment]
Exacly, this must be the same for all.

**Comment by JoshWho** [comment]
So why would the sessions get mixed?

**Comment by DanielnetoDotCom** [comment]
check with them what keys they are using, one of them got the wrong key somehow.

**Comment by JoshWho** [comment]
I just showed you both of them. That is what they are using

**Comment by DanielnetoDotCom** [comment]
AGAIN, THE KEYS ARE DIFFERENT. it will not be mixed

**Comment by DanielnetoDotCom** [comment]
who connect in who session?

**Comment by JoshWho** [comment]
G when he did his live today it showed Davis Lurmans info for the title and description

**Comment by DanielnetoDotCom** [comment]
Davis users_id=25

GiuseppeVafanculo users_id=4

looks at the logs

## Davis 2 connections

1 yesterday another today

````
root@server:~# tail -n 99999 /var/www/html/AVideo/videos/avideo.log | grep -i -A 20 'NGINX ON Publish new User(25)'
[27-Aug-2024 20:16:40 America/New_York] AVideoLog::DEBUG:      NGINX ON Publish new User(25) SCRIPT_NAME: /AVideo/plugin/Live/on_publish.php
...
[27-Aug-2024 20:16:40 America/New_York] AVideoLog::DEBUG:      NGINX ON Publish success (246, 25, 66c917068eb66-1, 1) SCRIPT_NAME: /AVideo/plugin/Live/on_publish.php
--
[28-Aug-2024 13:00:08 America/New_York] AVideoLog::DEBUG:      NGINX ON Publish new User(25) SCRIPT_NAME: /AVideo/plugin/Live/on_publish.php
...
[28-Aug-2024 13:00:08 America/New_York] AVideoLog::DEBUG:      NGINX ON Publish success (251, 25, 66c917068eb66-1, 1) SCRIPT_NAME: /AVideo/plugin/Live/on_publish.php
````

## GiuseppeVafanculo no connection

````
root@server:~# tail -n 99999 /var/www/html/AVideo/videos/avideo.log | grep -i -A 10 'NGINX ON Publish new User(4)' 
````

# Nginx logs

2024/08/26 20:03:07 [info] 3221511#0: *101545 publish: name='66c917068eb66-1' args='' type=live silent=0, client: 34.67.184.198, server: 0.0.0.0:1935
2024/08/27 20:16:40 [info] 3221511#0: *121894 publish: name='66c917068eb66-1' args='' type=live silent=0, client: 35.184.69.241, server: 0.0.0.0:1935
2024/08/28 13:00:08 [info] 3221511#0: *139466 publish: name='66c917068eb66-1' args='' type=live silent=0, client: 35.224.225.235, server: 0.0.0.0:1935


todays connection was from the IP 35.224.225.235 check who is this

From the logs I can see (I AM SURE), today's connection uses the correct key and URL

so if the IP is from GiuseppeVafanculo he somehow could copy the Davis credentials

**Comment by JoshWho** [comment]
Interesting. I know they both share a account with Streamyard and that is the streamyard IP address.

**Comment by DanielnetoDotCom** [comment]
Streamyard may be mixing things

**Comment by JoshWho** [comment]
> Streamyard may be mixing things

Very possible as well.
