### ISSUE TITLE
Why do all the previous videos have a Download button but newest ones do not?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9248]
Just trying to figure out what makes that happen any way to make the button on all videos including latest?

![Screenshot - 2024-07-20T020855 305](https://github.com/user-attachments/assets/ceb9343e-deac-4e05-a43e-dec4ff3d7f4e)

**Comment by DanielnetoDotCom** [comment]
Do they have different format? HLS/MP4?

what file format does it download.

Usually HLS videos does not allow you to download

**Comment by JoshWho** [comment]
No they are all 720p

**Comment by JoshWho** [comment]
Looks like it has to do when it has multiple files to download.

**Comment by DanielnetoDotCom** [comment]
I am taling about file format (HLS or MP4) NOT video resolution

**Comment by JoshWho** [comment]
Might be related to the mp3 thing. https://github.com/WWBN/AVideo/issues/9203 Seems like those r the ones that have the download button.
