### ISSUE TITLE
Is there a way to have rebroadcasts playing in Home Big video until a real live happens?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9251]
Some way to keep the Big live video on homepage always playing and when someone actually goes live it will switch over to that?

**Comment by DanielnetoDotCom** [comment]
I guess this is how it supposed to work

**Comment by JoshWho** [comment]
I need a understanding how to use the rebroadcaster. I tried it a while ago and couldn't get it to work I will play with the settings tonight to see If I can have it  do that.

**Comment by DanielnetoDotCom** [comment]
this is what I got

**Comment by JoshWho** [comment]
> this is what I got https://github.com/WWBN/AVideo/wiki/Rebroadcaster-Plugin

Thank you
