### ISSUE TITLE
Chat minimizes when going to a live channel

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9252]
![Screenshot - 2024-07-20T040319 146](https://github.com/user-attachments/assets/d9e01ddb-4409-4d20-b7c7-9f7b5b754a37)

I have these settings above like what u see in the pic and the chat still starts minimized on live streams. 

Example https://ftjmedia.com/live/1/FLOOD/ls/23/    starts in 1 hour but should see it still in next few hours

**Comment by DanielnetoDotCom** [comment]
It will auto close because it is a Live Schedule and it does Not Have a Chat History

once it is live it may be opened

**Comment by JoshWho** [comment]
> It will auto close because it is a Live Schedule and it does Not Have a Chat History
> 
> once it is live it may be opened
