### ISSUE TITLE
Notification bell disappears if there is nothing to notify?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9254]
![Screenshot - 2024-07-20T231127 278](https://github.com/user-attachments/assets/8287a145-775c-4d16-8e09-3b2d7ed7eefe)

**Comment by DanielnetoDotCom** [comment]
you added this code in your page somwhere 

.text-muted {
    color: #88888800;
}

**Comment by JoshWho** [comment]
ahhhhhhhhhhh

**Comment by JoshWho** [comment]
Was just trying to remove the channel view counts on the bottom of the channel rows
