### ISSUE TITLE
Big VOD Video on homepage doesn't start where I have it set to. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9255]
I advanced edit the video it is playing and put in to start video at 00:06:48    but when I refresh the home page the video starts at the beginning.

**Comment by JoshWho** [comment]
![Screenshot - 2024-07-21T221511 786](https://github.com/user-attachments/assets/7bc39ed9-1d28-48c7-8146-a3d4e0704268)

**Comment by JoshWho** [comment]
![Screenshot - 2024-07-21T221605 997](https://github.com/user-attachments/assets/8d18b04f-7cd1-44fd-baad-73c3f014f31f)

**Comment by DanielnetoDotCom** [comment]
try in an icognito browser. 

your last viewed position should overwrite the video setting
