### ISSUE TITLE
Videos are breaking again. Not sure what changed. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9264]
For some reason new videos are breaking now just started yesterday.

**Comment by JoshWho** [comment]
I had videos encoding in just 720p and now I see the encoder using the HLS even though I never enabled it in the CustomAdvance

![Screenshot (1)](https://github.com/user-attachments/assets/70868cdd-6f61-40c5-a7bf-46245f7053e6)

**Comment by JoshWho** [comment]
I purposely had that disabled because it was breaking the files now there is no way to stop it.

**Comment by JoshWho** [comment]
This video https://ftjmedia.com/channel/BaalBusters/video/.XXw9sfNXmOPvLRnVax6Kxw/journey-home-stream-on-22-jul-24-11-12-30 says it is complete yet has no video files to play.

![Screenshot (2)](https://github.com/user-attachments/assets/ae3fc71b-cb1e-4cbf-9372-e526c9c26aef)

**Comment by JoshWho** [comment]
![Screenshot (3)](https://github.com/user-attachments/assets/831a1a42-e1fa-45e3-a389-b4274cb29439)

**Comment by JoshWho** [comment]
Should I just disabled the HLS plugin will that make it go back to the 720p encoding?

**Comment by JoshWho** [comment]
> Should I just disabled the HLS plugin will that make it go back to the 720p encoding?

This did the trick to make it encode back to 720p

**Comment by DanielnetoDotCom** [comment]
Sorry but I have no idea what you are talking about.

For sure automatic resolution is much better then try to force a specific resolution 

I do not understand why you are forcing it, this will lead in a bad quality video if you need to upscale the video

**Comment by JoshWho** [comment]
makes it smaller

**Comment by JoshWho** [comment]
> You can configure the encoder to automatically convert it and make it smaller, and make sure it will not upscale , also if you disable the hls the videos you have converted to hls will not work anymore

I never converted any videos to HLS. Everytime I tried it never saved and became a broken file. When I mad it go back to just 720p every upload was working fine and encodes a lot faster.

**Comment by DanielnetoDotCom** [comment]
I am pretty sure saw some HLS video on your site, and they were playing fine. 
I am not sure if you deleted them

**Comment by JoshWho** [comment]
I never seen one work right when I was trying it. The CDN does a great job solved the Iphone issue somehow.

**Comment by DanielnetoDotCom** [comment]
the ones I tested on your site works good, also I have many other sites using HLS

**Comment by JoshWho** [comment]
I am sure it was a mis config or something. I reuploaded the videos and now have them in 720p
