### ISSUE TITLE
Does backblaze still work with your cdn?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9267]
We are out of diskspace so trying to figure out the best solution

**Comment by DanielnetoDotCom** [comment]
For some reason I noticie your lives have heron recorded but not deleted 

/var/www/tmp folder

**Comment by JoshWho** [comment]
> For some reason I noticie your lives have heron recorded but not deleted
> 
> /var/www/tmp folder

that's weird

**Comment by JoshWho** [comment]
I only see one from the 23rd

**Comment by JoshWho** [comment]
Does Backblaze work with this?

**Comment by JoshWho** [comment]
I see a b2 option in the CDN advance config, so I am guessing it does work with it?

**Comment by JoshWho** [comment]
Is there a easy script to upload the videos directory back to backblaze?

**Comment by JoshWho** [comment]
@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
While Backblaze can be used with our CDN, it will not offer the same performance as our CDN storage.

Our CDN storage is on the same network as our CDN, providing significantly better video playback performance.

Additionally, if you decide to move everything back to Backblaze, the process will be quite cumbersome. There is no script for that.

You would need to transfer the files to your SERVER first and then to Backblaze, and you currently do not have enough disk space for that.

**Comment by JoshWho** [comment]
I am working on doubling the hard disks hopefully will be done soon

**Comment by JoshWho** [comment]
> While Backblaze can be used with our CDN, it will not offer the same performance as our CDN storage.
> 
> Our CDN storage is on the same network as our CDN, providing significantly better video playback performance.
> 
> Additionally, if you decide to move everything back to Backblaze, the process will be quite cumbersome. There is no script for that.
> 
> You would need to transfer the files to your SERVER first and then to Backblaze, and you currently do not have enough disk space for that.

Let me know the steps I need to do and I will move it all

**Comment by DanielnetoDotCom** [comment]
I am not 100%, but you can use the FTP to transfer

The CDN storage credentials in the CDN plugin are the same for FTP

but again I do not think this is a good idea, and also I do not think this is an easy task

**Comment by JoshWho** [comment]
Do I have to take the files out of their folders and upload just the thumbs and videos or do the whole folders also go to backblaze now? It didn't before is why I am asking about the file structure.

**Comment by JoshWho** [comment]
I thought the files were still on the server and only using the cdn?  What storage are you saying I need to ftp?

**Comment by DanielnetoDotCom** [comment]
FTP to transfer your files form CDN storage to your server.

**Comment by JoshWho** [comment]
So what filled up my server then?

**Comment by JoshWho** [comment]
Do I have to transfer or can I just keep everything where it is at and all new videos go to backblaze?

**Comment by JoshWho** [comment]
OK I will use your storage. What do I need to get that done to fix this?

**Comment by DanielnetoDotCom** [comment]
```
root@server:~# du --max-depth=1 -h /var/www/html/
33G     /var/www/html/radio
28M     /var/www/html/mail
89G     /var/www/html/AVideo
9.3G    /var/www/html/AVideo-Encoder
131G    /var/www/html/
root@server:~# du --max-depth=1 -h /var/www/html/AVideo | grep G
88G     /var/www/html/AVideo/videos
89G     /var/www/html/AVideo
root@server:~# du --max-depth=1 -h /var/www/html/AVideo/videos/ | grep G
4.2G    /var/www/html/AVideo/videos/v_240724032003_v2f8e
2.9G    /var/www/html/AVideo/videos/video_240719032944_v8dde
36G     /var/www/html/AVideo/videos/cache
88G     /var/www/html/AVideo/videos/
root@server:~# 
```
```
root@server:~# ls -lah /var/www/html/AVideo/videos/  | grep G
total 44G
-rwxrwxr-x   1 www-data www-data  17G Jul 24 21:40 avideo.log
-rwxrwxr-x   1 www-data www-data 5.9G Jul  9 03:02 original_v_240708230223_vb924
-rwxrwxr-x   1 www-data www-data 5.9G Jul 12 03:02 original_v_240711230214_v292c
-rwxrwxr-x   1 www-data www-data 5.9G Jul 13 03:02 original_v_240712230211_vf792
-rwxrwxr-x   1 www-data www-data 5.9G Jul 17 03:02 original_v_240716230252_va4ff
-rwxrwxr-x   1 www-data www-data 4.1G Jul 22 07:49 original_v_240722034913_v3d7a
```

# check 
- 33G     /var/www/html/radio
- 36G     /var/www/html/AVideo/videos/cache

I am not sure why you have those original_* files, but I am pretty sure you can safely delete the original_* files

-rwxrwxr-x   1 www-data www-data 5.9G Jul  9 03:02 original_v_240708230223_vb924
-rwxrwxr-x   1 www-data www-data 5.9G Jul 12 03:02 original_v_240711230214_v292c
-rwxrwxr-x   1 www-data www-data 5.9G Jul 13 03:02 original_v_240712230211_vf792
-rwxrwxr-x   1 www-data www-data 5.9G Jul 17 03:02 original_v_240716230252_va4ff
-rwxrwxr-x   1 www-data www-data 4.1G Jul 22 07:49 original_v_240722034913_v3d7a

**Comment by JoshWho** [comment]
I will use your storage system what all do I need to get that going to fix this?

**Comment by JoshWho** [comment]
![Screenshot (17)](https://github.com/user-attachments/assets/c1e7d480-404c-4308-8d26-61f8e77c5772)
  
Do I just click add storage?

**Comment by DanielnetoDotCom** [comment]
do not click, you aready have a storage

**Comment by JoshWho** [comment]
So what is there to do to get this all set?

**Comment by DanielnetoDotCom** [comment]
You need to manually free some space

https://github.com/WWBN/AVideo/issues/9267#issuecomment-2248950037

**Comment by JoshWho** [comment]
![Screenshot (18)](https://github.com/user-attachments/assets/c6d73fbe-abd6-4439-b1cd-912467892479)
already made room

**Comment by DanielnetoDotCom** [comment]
so what are you asking?

**Comment by JoshWho** [comment]
How to use your storage with this?

**Comment by JoshWho** [comment]
Am I understanding you have a cloud storage?

**Comment by DanielnetoDotCom** [comment]
It is already configured and working, there is nothing else to do. 
Your usage now

166.7GB / 31,775 files Region: NY

**Comment by JoshWho** [comment]
So the disk should not fill up no more?

**Comment by DanielnetoDotCom** [comment]
depends on what you do, it will not filled up with videos. but may be filled with cache or other files

**Comment by JoshWho** [comment]
> depends on what you do, it will not filled up with videos. but may be filled with cache or other files

Excellent. Thank you
