### ISSUE TITLE
How can we make the Live Big video on home page open to the real live page with the chat?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9272]
![Screenshot (30)](https://github.com/user-attachments/assets/15e03620-df9e-469b-8796-91fa04f8dcaa)

Like how it works now is you click it and it goes full screen but doesn't have chat. 

Any way to make it when you click it it will go to the actual live page so they can also chat. 

![Screenshot (31)](https://github.com/user-attachments/assets/f4583da7-ff3e-41a1-86b2-5df1d1758730)

**Comment by eitanwa** [comment]
Hi josh
Sharing my thoughts with you as I too am trying to understand the purpose of this plugin
In my opinion, this is how it should work, as a sort of advertisement for the live broadcasts themselves
When there are several live broadcasts at the same time, it will randomly show a different broadcast every time, and then it won't be "fair" to the other broadcasts that you allowed exit/escape for that broadcast
Then in practice if you want to enter the live broadcast itself that you have chosen it will be in the line of broadcasts under it on the home page
Note that even after enlarging the video you cannot minimize it from the player itself
but from the x on the upper right side (as in the advertisements)

**Comment by JoshWho** [comment]
Yes I agree, should not play full screen on the home when clicked.

**Comment by eitanwa** [comment]
I think that's exactly the point
and/or the purpose of this feature
Advertising
in which you actually "force" the viewer to watch

**Comment by JoshWho** [comment]
THe users on my website are confused about and keep complaining the chat is not there when they click it. Should take the user to the actual Live stream page so they can subscribe to the channel and interact.

**Comment by JoshWho** [comment]
What you think @DanielnetoDotCom can this be done please?

**Comment by DanielnetoDotCom** [comment]
Hi, I think add a chat is is a good idea, also some way to direct the user to the video owner channel,  but may be done in the future.
