### ISSUE TITLE
Any way to change the Hover text on the Seek buttons to just say Skip 15s  Back 15s

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9275]
![seek](https://github.com/user-attachments/assets/18f008d8-088a-424d-afd5-e258e1e246dc)

Instead of it saying Seek Forward 

change to Skip 10 seconds     
Back 10 seconds or whatever seconds the user has selected for their install.

**Comment by DanielnetoDotCom** [comment]
This text is from the [library](https://github.com/mister-ben/videojs-seek-buttons), this is out of my control

**Comment by JoshWho** [comment]
> This text is from the [library](https://github.com/mister-ben/videojs-seek-buttons), this is out of my control

k no probs
