### ISSUE TITLE
User groups in "My Videos" btn-group open / btn btn-primary dropdown-toggle

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9277]
@DanielnetoDotCom Danny, I can't manipulate user groups from "My Videos".
Removing from group doesn't work either. A black box appears and shows nothing.
`btn-group open` `btn btn-primary dropdown-toggle`

![image](https://github.com/user-attachments/assets/20a20d38-eb33-4078-a064-e41d079607f5)

**Comment by JSY-Ben** [comment]
+1 to this. Appears to be an issue on the demo site too :)

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by gbrn** [comment]
Ok thanks
