### ISSUE TITLE
Doing a new install

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#9287]
I am trying to install a new server that I want to use also as a testing server and my own personal site. I previously had a Wordpress installed but was thinking to change it to AVideo and only use the options I wanted. You would think that simply replacing the current site directory with the new AVideo directory pulled form github would be easy enough to just start the installation process and have it up and running quickly, however that is not the case. It seem I am having an issue and I cannot get the first step of the installation to start. I do not see anything in the logs of apache beside  something regarding the functions.php file. 

Here are some screenshots:

![Screenshot 5784-11-23 at 19 39 57](https://github.com/user-attachments/assets/e1c26947-2243-487f-9d16-2944c0ae6f22)
![Screenshot 5784-11-23 at 19 33 03](https://github.com/user-attachments/assets/5ae62fb3-1e93-43c6-ac00-8b841016eb58)
![Screenshot 5784-11-23 at 19 45 46](https://github.com/user-attachments/assets/ea195716-f0ad-4559-9185-973b75287b62)

Besides this info I don't see why I cannot install the database and load the site.

**Comment by DanielnetoDotCom** [comment]
The erron in the web page this update should resolve 

the error in your logs, I could not find it, I guess you have outdated files

the most common unknow error is because your mysql user does not have permission to create database and tables.

**Comment by guymass** [comment]
Thank you very much for the update the functions.php warning is now gone. Going to try an install again and see if that helps.

**Comment by guymass** [comment]
OK you are correct it was a wrong password, however there should be at least something indicating that is the issue and not some general error. I was able to install the site so I will close this. Thank you for the update.
