### ISSUE TITLE
Video tags are enabled but I do not see the bos for it anywhere

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9291]
where do you put in tags for a video?

![Screenshot (80)](https://github.com/user-attachments/assets/44695de8-5f3b-4af4-9f4e-95a0c355c327)

**Comment by DanielnetoDotCom** [comment]
If you enable it, and created some tags groups https://github.com/WWBN/AVideo/wiki/VideoTags-Plugin

it should be in the SEO tag

**Comment by JoshWho** [comment]
> If you enable it, and created some tags groups https://github.com/WWBN/AVideo/wiki/VideoTags-Plugin
> 
> it should be in the SEO tab

Got it found it and now created thank you
