### ISSUE TITLE
App Icon for Android WPA just shows the Avideo Icon and not what we have set for the Fav Icon. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9293]
How can this be changed. I thought it was just Brave Browser but now installed using Chrome it is still the yellow Play button Icon and not our Icon we have loaded.

**Comment by JoshWho** [comment]
This is from today retrying to see if it shows our Icon and it still shows the original Avideo on Android

![Screenshot_20240818-080619](https://github.com/user-attachments/assets/b61d2055-75bc-4c2e-a257-611c27e1804d)

**Comment by JoshWho** [comment]
@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
try to force delete all the videos/faviconPWA* icons and let it recreate again. 
`````
rm /path/to/your/AVideo/videos/faviconPWA*
`````

**Comment by JoshWho** [comment]
> try to force delete all the videos/faviconPWA* icons and let it recreate again.
> 
> ```
> rm /path/to/your/AVideo/videos/faviconPWA*
> ```

That did the Trick. Thank you
