### ISSUE TITLE
Live meetings how to Go live for 4 hours on it?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9300]
Seems like it cuts off every 30 minutes how can we change this?

**Comment by DanielnetoDotCom** [comment]
For unlimited livestreams you need to get a meer server from me 

https://github.com/WWBN/AVideo/wiki/Meet-Plugin#premium-server-packages

**Comment by milehighkaraoke** [comment]
Josh are you running your own jitsu server

**Comment by JoshWho** [comment]
Looks like we will be soon. Currently it is using the free one.

**Comment by JoshWho** [comment]
Email sent for quotes @DanielnetoDotCom
