### ISSUE TITLE
Ability to dump your Live stream watchers to another stream on the site when finished. They call this Raiding a Live Stream

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9304]
Raiding a Live Stream on Rumble is a feature that allows a streamer to redirect their audience to another live stream on Rumble at the end of their own stream. It's a way to share viewers and promote other creators.

Here's how it works:
The streamer initiates a raid by copying the URL of the live stream they want to send their viewers to.
A notification appears in the chat, alerting viewers to the upcoming raid.
Viewers can choose to opt-in to the raid by clicking a "join" button. If they opt-in, they'll be redirected to the raided stream once the countdown is over.

This feature is similar to raids on other platforms like Twitch, where streamers can help each other grow their audiences and foster a sense of community.

**Comment by milehighkaraoke** [comment]
This would definitely be helpful
