### ISSUE TITLE
Cannot upload and Encode videos since last update

### ISSUE THREAD

**Issue by guymass** [WWBN/AVideo#9306]
I made a git pull for both Encoder and the site, also all plugins are fully updated. Since then, two days ago, I cannot upload and encode anything. Here are some screenshot:

![Screenshot 5784-12-03 at 19 04 44](https://github.com/user-attachments/assets/a541962e-8fbb-4238-984e-74dd7b491778)

![Screenshot 5784-12-03 at 19 02 20](https://github.com/user-attachments/assets/bf2ea899-8b9a-44b8-8885-4d6d9627821c)
![Screenshot 5784-12-03 at 19 02 12](https://github.com/user-attachments/assets/4144ea7a-6377-45f3-a351-ef960a343b79)

**Comment by DanielnetoDotCom** [comment]
Check the AVideo log

**Comment by guymass** [comment]
![Screenshot 5784-12-03 at 19 23 46](https://github.com/user-attachments/assets/61c4ed88-78f6-48d8-a520-9584d2f66912)

**Comment by guymass** [comment]
Also when I click reload file on queue on the encoder, it created three encoded file posts, showing on the My Videos page:

![Screenshot 5784-12-03 at 19 26 44](https://github.com/user-attachments/assets/63ad8d92-b33d-4d66-b356-258b01eac68b)

I only uploaded one file but the encoder creates three.

**Comment by DanielnetoDotCom** [comment]
If you are up to date, how come you do not have this?

https://github.com/WWBN/AVideo/blob/5531ed91ec23bc74b41a810c246ce1056b917456/objects/video.php#L6135-L6142

try to restart your server.

**Comment by guymass** [comment]
OK I rebooted and still same error and git pull shows I am fully updated so idk. I still see these repeating errors in the log:

![Screenshot 5784-12-03 at 20 29 37](https://github.com/user-attachments/assets/6f4f7eac-638c-49cd-ac9f-a729c0919a4b)


Encoder log:
![Screenshot 5784-12-03 at 20 32 51](https://github.com/user-attachments/assets/6e1c5861-d1f8-45fc-9d8a-0faea46081e7)

**Comment by DanielnetoDotCom** [comment]
You are probably updating the wrong folder , your logs does not make sense

**Comment by guymass** [comment]
im doing the same update process i've been doing since day 1. Nothing has changed.

**Comment by DanielnetoDotCom** [comment]
Sorry I cannot help you then . Your logs indicated this is not updated

**Comment by guymass** [comment]
What about doing  a hard reset, would that work?

**Comment by guymass** [comment]
OK I figured it out, you are correct my site version is 14.3 while you have 14.4, however I usually get the update request appearing on my site after a git pull, but currently i didn't get any notification for version update. So I think a hard reset is needed in this case, correct?

**Comment by guymass** [comment]
OK after updating my encoding is now working again:

![Screenshot 5784-12-03 at 21 09 27](https://github.com/user-attachments/assets/4042abce-fdfd-4b3b-ac34-9de4b5a5994c)

Im closing this post.
