### ISSUE TITLE
[Plugin HLS + Storage] Incorrect storage information

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9308]
@DanielnetoDotCom Danny, I'm using the HLS plugin and I also use external Storage. For each HLS encoder, the Streamer is miscalculating the disk consumption. Remembering that not all videos are in HLS yet.
See, my videos directory is only 25GB:
![image](https://github.com/user-attachments/assets/7eeb0984-938e-42f5-ba84-939016b362b5)

But the streamer system says I'm consuming 55.73GB:
![image](https://github.com/user-attachments/assets/1219d00b-5883-4d8e-bbce-7975676d3836)

I don't understand where he is getting this information from? Is it a sum of the Streamer HD + HD Storage?

In the individual video information, it shows different from the one shown on the Stramer 1.34 GB HD:
![image](https://github.com/user-attachments/assets/d8b6cd31-1201-4c94-85de-639bb46a3d30)

The streamer's HD has only 2.8M:
![image](https://github.com/user-attachments/assets/ea0e88f2-fe69-4192-9809-cdb577a02283)

**Comment by DanielnetoDotCom** [comment]
how much this video ocupy in the storage?

you are correct the file size should be  Streamer HD + HD Storage

**Comment by gbrn** [comment]
@DanielnetoDotCom On the Storage server, this folder that I mentioned previously has the following sizes:
```
601M    ./res472
271M    ./res240
412M    ./res360
1.3G    .
```
Total: 1.3GB

![image](https://github.com/user-attachments/assets/a08edc30-8ed0-4808-a6e6-7c1419b8c035)

**Comment by DanielnetoDotCom** [comment]
So the displayed size makes sense.

**Comment by DanielnetoDotCom** [comment]
It is based in your database records. 

it sum all the videos sizes in the database

**Comment by gbrn** [comment]
Oh, that's right... for me the information was pulled from the videos directory.
