### ISSUE TITLE
upgrade from 14.3 to 14.4 DB update issue

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#9309]
**Describe the question**
Since doing a git pull on the main site and encoder I cant seem to update the db. 

When i click update, it just refreshes the page and does nothing.

I cleared the log and check after i click update and nothing is placed into the log.

in the console I get an error:
Uncaught TypeError: $(...).selectpicker is not a function in https://vid.hooptactix.com/update  1340:19

any ideas?

**Screenshots**
![image](https://github.com/user-attachments/assets/78d16d39-0e30-40e4-8e1b-bf736d859e93)

**Comment by millzee01** [comment]
ok, after a hard reboot and a git pull -f i can now update the database on the main site.

The issue now comes when I do an update on the encoder.
![image](https://github.com/user-attachments/assets/fabcbdb6-26f3-4323-97cb-9b41970afa18)

I notice there is no "upgrade" tab?

Is there anything I have missed?

**Comment by DanielnetoDotCom** [comment]
The upgrade message is regarding your Streamer

if is still failing, check your logs

**Comment by lachainestoplinky** [comment]
Hello,
for me,
I had to launch the update 4 times for it to work.

cordially

**Comment by millzee01** [comment]
thanks, should i see the "upgrade" tab on the streamer?

**Comment by lachainestoplinky** [comment]
so I had to try the update from the update page (yes), I left time between attempts because I had bugs.
empty page, gateway problem !!

and after 4 times, quickly, I had this message : 14.4
![Capture d’écran 2024-08-08 à 22 10 03](https://github.com/user-attachments/assets/bbd1bc97-fc48-471d-ba3e-2401c0b0cea2)

**Comment by h3ll3** [comment]
Same here - had nothing in my log but after clearing the site cache and several attempts it finally worked.
