### ISSUE TITLE
[Plugin SubtitleSwitcher] Subtitle wrong info after HLS

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9310]
@DanielnetoDotCom Danny, after updating an MP4 video to HLS, the video's subtitles were removed, but the information still states that there are subtitles. Can you tell me how to resolve this?

[Vídeos-·-CNETV.webm](https://github.com/user-attachments/assets/43f2301a-efd0-45e1-b7a0-6a8f4ae1a8db)

![image](https://github.com/user-attachments/assets/f275cc58-4467-4e0f-a5cc-e82d96ff753b)

**Comment by DanielnetoDotCom** [comment]
I have no idea what happen, can you please share this video link here?

**Comment by gbrn** [comment]
Now the information I mentioned about subtitles has come out... it was either cache or the processing time of the routines. OK.

![image](https://github.com/user-attachments/assets/d00ccf42-d518-4d35-bcaf-f070d15dd0c4)
