### ISSUE TITLE
Is it normal now for the new Jitsi server to show this

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9311]
![image](https://github.com/user-attachments/assets/a8ad889d-d22c-42f9-af26-b502099c508e)

**Comment by JoshWho** [comment]
Orange Camera that says We do not have any Streaming Services Purchase one here

**Comment by JoshWho** [comment]
Looks like it all works right. Probably a non issue I am closing this.

**Comment by JoshWho** [comment]
Can you confirm if that is normal to see @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
For now it is, but I may change the message in future updates.

**Comment by JoshWho** [comment]
> For now it is, but I may change the message in future updates.

K No prbs
