### ISSUE TITLE
Unable to get the Encoder running

### ISSUE THREAD

**Issue by AlexVinet** [WWBN/AVideo#9312]
**Describe the question**
Hi, I followed the instructions here: https://github.com/WWBN/AVideo/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-22.x-for-AVideo-Platform-version-11.x-or-newer

But the encoder doesn't seems to run. According to the information I found, the encoder should run at http://myhost.com/Encoder, but it is not. I'm sure I'm missing a step.

Can anyone help me please.

**Screenshots**
Provide some screenshots to help us understand and explain your problem.

**Comment by DanielnetoDotCom** [comment]
Provide more details about the error and also provide the encoder logs

**Comment by AlexVinet** [comment]
I don't see any errors and I'm not sure where to find the Encoder logs. In the apache2 error.log it doesn't seems to have nothing related to the encoder.

**Comment by DanielnetoDotCom** [comment]
Check in 

Encoder/videos/avideo.log

**Comment by AlexVinet** [comment]
The file doesn't exist.

I used: sudo find / -name avideo.log

and only got:
/var/www/html/AVideo/videos/avideo.log

But the /var/www/html/AVideo-Encoder/ folder exist.

**Comment by GreenDragonTavern** [comment]
You installed the encoder in a directory that requires a separate domain. If you want to use http://myhost.com/Encoder and you installed AVideo in the default of /var/www/html/AVideo/ then use ```cd /var/www/html/AVideo/ && sudo git clone https://github.com/WWBN/AVideo-Encoder.git Encoder```. This way the encoder is located at /var/www/html/AVideo/Encoder and http://myhost.com/Encoder resolves as desired.
