### ISSUE TITLE
logged in sessions being logged out for no reason after idle for 30 mins

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#9327]
**Describe the bug**
Sessions logged in gets logged out automatically after 30mins [this is happening with manual login and api login)
This has never happened before since I upgraded 

This also happens on the demo site! 
Logged in as test users and it logs me out after a few minutes.

**To Reproduce**
1. Log into the platform
2. go to the movies page
3. minimize page and leave for 30-40 minutes
4. refresh the page and user is presented with login page again

**Expected behavior**
Videos should load when page is refreshed

**Error Logs**
lots of messages in avideo log without any page interaction:
gotToLoginAndComeBackHere() xxx.xxx.xxx.xxx [{"file":"\/var\/www\/html\/plugin\/CustomizeUser\/CustomizeUser.php","line":786,"function":"gotToLoginAndComeBackHere","args":[""]},{"file":"\/var\/www\/html\/plugin\/AVideoPlugin.php","line":780,"function":"getStart","class":"CustomizeUser","object":{},"type":"->","args":[]},{"file":"\/var\/www\/html\/objects\/include_config.php","line":236,"function":"getStart","class":"AVideoPlugin","type":"::","args":[]},{"file":"\/var\/www\/html\/videos\/configuration.php","line":48,"args":["\/var\/www\/html\/objects\/include_config.php"],"function":"require_once"},{"file":"\/var\/www\/html\/view\/index.php","line":7,"args":["\/var\/www\/html\/videos\/configuration.php"],"function":"require_once"}] SCRIPT_NAME: /view/index.php

lots of same messages as above then then finally:
[11-Aug-2024 17:20:54 America/Toronto] AVideoLog::DEBUG:      gotToLoginAndComeBackHere(We could not load the video, please login) xxx.xxx.xxx.xxx [{"file":"\/var\/www\/html\/objects\/functions.php","line":4352,"function":"gotToLoginAndComeBackHere","args":["We could not load the video, please login"]},{"file":"\/var\/www\/html\/view\/modeYoutube.php","line":291,"function":"forbiddenPage","args":["We could not load the video, please login"]},{"file":"\/var\/www\/html\/view\/index_firstPage.php","line":56,"args":["\/var\/www\/html\/view\/modeYoutube.php"],"function":"require"},{"file":"\/var\/www\/html\/view\/index.php","line":20,"args":["\/var\/www\/html\/view\/index_firstPage.php"],"function":"include"}] SCRIPT_NAME: /view/index.php

Console logs:
this is the last websocket console logged
ResourceId: "7323"
​autoUpdateOnHTML: Object { webSocketServerVersion: "6.1", socket_mem: "13.04MB", socket_users_id: "10", … }
callback: ""
​isAdmin: ""
live_key: ""
mem: "13.04MB"
msg: Array [ {…} ]
0: Object { msg: {…}, type: "NEW_CONNECTION" }
	msg: Object { users_id: 10, yptDeviceId: "ypt-Firefox-Windows_10-ffde9eaeefd0e7b7529e6338681a27b8-d90c91ba47074ebc106cbdef0c8105ed-10", live_key_servers_id: "_0", … }
​​​	type: "NEW_CONNECTION"
​​​	<prototype>: Object { … }
​​	length: 1
	<prototype>: Array []
resourceId: "7323"
type: "MSG_TO_ALL"
uniqid: "66b9d49569154"
users_id: "10"
users_id_online: Array [ {…} ]
0: Object { 0: "10", 2: "_0", 3: "0", … }
	0: "10"
	1: ""
​​​	2: "_0"
​​​	3: "0"
​​​	4: "https://vid.hooptactix.com/view/managerVideos.php"
​​​	5: "0"
​​​	6: "Videos · HoopTactixVideo Hub"
​​​	7: "7323"
​​​	8: "0"
​​​	9: "0"
​​​	10: "Carl Miller"
​​​	chat_is_banned: "0"
​​​	country_name: "0"
​​​	identification: "Carl Miller"
​​​	isAdmin: ""
​​​	live_key_servers_id: "_0"
​​​	page_title: "Videos · HoopTactixVideo Hub"
​​​	resourceId: "7323"
​​​	room_users_id: "0"
​​​	selfURI: "https://vid.hooptactix.com/view/managerVideos.php"
​​​	users_id: "10"
​​​	videos_id: "0"
​​​	<prototype>: Object { … }
​​	length: 1
​​	<prototype>: Array []
​videos_id: "0"
webSocketServerVersion: "6.1"

**Screenshots**
Not applicable as refreshed page just goes to the login screen.

**Desktop (please complete the following information):**
same happens on multiple browsers and different pc's

**Comment by DanielnetoDotCom** [comment]
are you checking in the "remember me" when you login?

**Comment by millzee01** [comment]
interesting, i set remember me to 1 but i remember there used to be a rememberme coookie as well which doesn't appear now.
