### ISSUE TITLE
Trying to edit encoders on Encoder network why is it doing this?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9329]
root@server:/var/www/html/AVideo-Encoder/install# php encoders.php
Could not open input file: encoders.php
root@server:/var/www/html/AVideo-Encoder/install# php install.php
Can not create configuration again: {"SHELL":"\/bin\/bash","NVM_INC":"\/root\/.nvm\/versions\/node\/v22.5.1\/include\/node","PWD":"\/var\/www\/html\/AVideo-Encoder\/install","LOGNAME":"root","XDG_SESSION_TYPE":"tty","MOTD_SHOWN":"pam","HOME":"\/root","LANG":"en_US.UTF-8","LS_COLORS":"rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:","SSH_CONNECTION":"24.14.187.195 60713 185.75.21.101 22","NVM_DIR":"\/root\/.nvm","LESSCLOSE":"\/usr\/bin\/lesspipe %s %s","XDG_SESSION_CLASS":"user","TERM":"xterm","LESSOPEN":"| \/usr\/bin\/lesspipe %s","USER":"root","SHLVL":"1","NVM_CD_FLAGS":"","XDG_SESSION_ID":"18557","XDG_RUNTIME_DIR":"\/run\/user\/0","SSH_CLIENT":"24.14.187.195 60713 22","XDG_DATA_DIRS":"\/usr\/local\/share:\/usr\/share:\/var\/lib\/snapd\/desktop","PATH":"\/root\/.nvm\/versions\/node\/v22.5.1\/bin:\/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin:\/sbin:\/bin:\/usr\/games:\/usr\/local\/games:\/snap\/bin","DBUS_SESSION_BUS_ADDRESS":"unix:path=\/run\/user\/0\/bus","NVM_BIN":"\/root\/.nvm\/versions\/node\/v22.5.1\/bin","SSH_TTY":"\/dev\/pts\/0","_":"\/usr\/bin\/php","OLDPWD":"\/root","PHP_SELF":"install.php","SCRIPT_NAME":"install.php","SCRIPT_FILENAME":"install.php","PATH_TRANSLATED":"install.php","DOCUMENT_ROOT":"","REQUEST_TIME_FLOAT":1723521169.74947,"REQUEST_TIME":1723521169,"argv":["install.php"],"argc":1}root@server:/var/www/html/AVideo-Encoder/install#

**Comment by JoshWho** [comment]
What happened?

**Comment by DanielnetoDotCom** [comment]
Sorry edit what?

what is it?
