### ISSUE TITLE
latest version causes a bootstrap error in the console

### ISSUE THREAD

**Issue by millzee01** [WWBN/AVideo#9330]
**Describe the bug**
i.fn.fileinputThemes is undefined appears in the console

**To Reproduce**
Just click "my videos" and check the logs (could be down to the default theme)

![image](https://github.com/user-attachments/assets/0ba3b8a0-94a6-40a7-862c-df11b5d416ca)

happens on all browsers

Looking into it, the cause is the order the bootstrap/jquery files are loaded.

**Comment by millzee01** [comment]
it doesn't however i suspect my site config is using something the demo site isnt:

If you look at the console you'll see that my site loads:
Gallery/script.js [like yours]
however my site load node)modules/@fontawesome.....

which the demo site doesn't

So im wondering where this @fontawesome is being called from as this is why the erro appears.

![image](https://github.com/user-attachments/assets/1ba042ed-b0d3-4095-b695-13c54bbcf652)

**Comment by DanielnetoDotCom** [comment]
when you load the page, there is any other error or warning in the JS console?

**Comment by DanielnetoDotCom** [comment]
If currently is working fine, there is nothing to worry

**Comment by millzee01** [comment]
sure, i agree, will close.
