### ISSUE TITLE
How to disable Live Stream Password field

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9336]
Need a way to just not show the Live Stream password field. It gets autofilled sometimes and then the user doesn't know why people are asking for a password to watch. 

![Screenshot - 2024-08-14T214037 140](https://github.com/user-attachments/assets/6de9cae0-7338-49d8-94b4-e5c038abce39)

**Comment by DanielnetoDotCom** [comment]
Currently you cannot disable it, but I just send an update that will try to not autocomplete the field. but it may not work in some browsers.

**Comment by JoshWho** [comment]
Thank you
