### ISSUE TITLE
Plugins - ImageGallery usage question

### ISSUE THREAD

**Issue by AlexVinet** [WWBN/AVideo#9340]
**Describe the question**
Hello, I installed/activated the ImageGallery plugin, but I don't understand how to use it. I don't understand how to upload image. Do you have documentation on that plugin, I can't find anything so far.

**Screenshots**
<img width="295" alt="image" src="https://github.com/user-attachments/assets/6d79377d-91b4-450d-84b4-74b7ba83906e">
<img width="156" alt="image" src="https://github.com/user-attachments/assets/405a83f7-e486-40c5-b0a7-dc77e49ac388">

**Comment by DanielnetoDotCom** [comment]
Once you upload a image you will see the "Image Gallery"

![chrome-capture-2024-7-16](https://github.com/user-attachments/assets/b851a408-cfcf-48b4-9547-d84bdb3850cc)

**Comment by AlexVinet** [comment]
It seems I don't have the same options as you:
<img width="494" alt="image" src="https://github.com/user-attachments/assets/c1729180-43d7-4e25-a3f1-e8f8fe55aabd">

**Comment by AlexVinet** [comment]
Got it! I uncheck the "DisableDirectUpload".

**Comment by AlexVinet** [comment]
Thank you!
