### ISSUE TITLE
Calling is still real buggy. Doesn't stop ringing once you get to answer the call. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9361]
It takes a few tests and then it will start ringing the other device but once you answer it doesn't stop ringing.

**Comment by DanielnetoDotCom** [comment]
Can you please check this update?

**Comment by JoshWho** [comment]
Will give a try soon.

**Comment by JoshWho** [comment]
This is what it does when I click call to someone

![Screenshot - 2024-08-28T160332 784](https://github.com/user-attachments/assets/6c2294a5-a6b7-41b7-b850-1546918e0942)

**Comment by JoshWho** [comment]
![Screenshot - 2024-08-28T160414 746](https://github.com/user-attachments/assets/82a80fb6-b92f-447d-aa52-5e1a47730543)

**Comment by JoshWho** [comment]
After clicking the call button a second time it works and the ringing does stop.

**Comment by JoshWho** [comment]
After last Git pull
![Screenshot - 2024-08-28T163122 796](https://github.com/user-attachments/assets/30c3c96e-f895-4cae-a779-22fc1ec89b2c)

**Comment by JoshWho** [comment]
Should hide the footer on this

**Comment by JoshWho** [comment]
Also noticed after hanging up on the one that initiated the call does not take you back to the home page

**Comment by DanielnetoDotCom** [comment]
This update should remove the footer

**Comment by JoshWho** [comment]
Now the only other issue is when you first make a call it always shows user is offline then on the second try it lets you call.  Any way to make it wait for the connection to show online before allowing it to call. 
![Screenshot_20240829-084921](https://github.com/user-attachments/assets/728600af-f17a-47e1-846c-72337537b723)

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by JoshWho** [comment]
Is there a way we can have like a page of contacts and be able to click call if they are online?

I do not think searching a channel to find a page to click call is the best method, there should also be an option for the users if they want to accept calls or not.

**Comment by JoshWho** [comment]
This has all the right things to be like our own Telegram app, we just need it in one page to be better for video calling and messaging.

**Comment by JoshWho** [comment]
Maybe just create a new page for avideo like /messenger or something like that and the ability to add friends instead of it being able to call everyone at random.

**Comment by DanielnetoDotCom** [comment]
I like this, but I may add this in the future.

**Comment by DanielnetoDotCom** [comment]
Check this plugin 

https://github.com/WWBN/AVideo/wiki/UserConnections-Plugin

**Comment by JoshWho** [comment]
> Check this plugin
> 
> https://github.com/WWBN/AVideo/wiki/UserConnections-Plugin

Looks beautiful
