### ISSUE TITLE
Request to Remove a Section Below the Video

### ISSUE THREAD

**Issue by quantnlp** [WWBN/AVideo#9364]
**Description**
I would like to inquire about the possibility of removing a specific section that appears below the video on the page. As shown in the attached snapshot, this section is contributing to a less compact layout.

**Details**

**Objective:** Make the layout more compact by removing the section below the video.
**Current Situation:** Despite reviewing the CSS files, I have not found a way to modify or remove this section.
**Request:** Can you provide guidance on how to completely remove this section from the page? Any insight on how to achieve this would be greatly appreciated.
![how to remove section under video](https://github.com/user-attachments/assets/89ec7e1c-2587-42c1-961e-d5a176d2abe4)

Thank you for your assistance!

**Comment by DanielnetoDotCom** [comment]
Hi

fisrt you need to know how to handle CSS, then you can add it like this

https://github.com/WWBN/AVideo/wiki/Site-Design-and-Templates#add-a-custom-css-or-javascript

**Comment by quantnlp** [comment]
Thanks Daniel.
