### ISSUE TITLE
Hide non html Unsubscribe if email HTML is used

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9370]
![Screenshot - 2024-09-02T130343 767](https://github.com/user-attachments/assets/d5362bce-5f3a-407b-8b99-b3653540afd7)

Some way to div null that bottom left Unsubscribe on on html view?

**Comment by DanielnetoDotCom** [comment]
It will be fixed in the next Notifications plugin version, probably 7.4
