### ISSUE TITLE
Expand category list

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9374]
@DanielnetoDotCom Danny, am I trying to expand this category list?

![image](https://github.com/user-attachments/assets/791b88d4-7970-4f6f-a260-493c4f70a801)

**Comment by DanielnetoDotCom** [comment]
Hi, what exactly do you mean?

**Comment by gbrn** [comment]
Sorry, I meant that I'm trying to increase the amount of categories displayed in this menu. 
I have a total of 8 categories that I'm using:
 
![image](https://github.com/user-attachments/assets/0afd99e2-7705-40c2-8dd4-fb178f0abad0)

But only 5 categories appear in the sidebar.

**Comment by DanielnetoDotCom** [comment]
It works for me when I click on it

![chrome-capture-2024-8-4](https://github.com/user-attachments/assets/69df2d77-b831-4e7a-8e3d-ecd3d1e5cf9f)

**Comment by gbrn** [comment]
@DanielnetoDotCom Not working properly:

Look at this image, it only displays 5 categories:

![image](https://github.com/user-attachments/assets/e61268c0-bcf5-4459-8d3e-e6374b5ff471)


![image](https://github.com/user-attachments/assets/44816acd-a248-4df1-b02d-0cfdafed40e5)

When I click on "Brazilian Independents" it doesn't open the subcategory, it goes directly to the category page.
Do I need to do any additional configuration for the category?

**Comment by DanielnetoDotCom** [comment]
can you reproduce it on demo site?
