### ISSUE TITLE
[Plugin SubtitleSwitcher] Automatic Transcript + VOSK

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9376]
@DanielnetoDotCom Danny, subtitle generation is disabled in the SubtitleSwitcher plugin, but the system still generates subtitles, check it out:

![image](https://github.com/user-attachments/assets/d4272ded-c5fa-4384-8291-8fe2686f3a16)

VOSK's inaccuracy is gigantic. It takes orchestrated music and creates subtitles. Sound effects and creates subtitles. It's really bad. For example below, it took the sound of a train and turned it into "Xuxa Xuxa".

![image](https://github.com/user-attachments/assets/5ab25c1a-faf7-43df-bddf-333d7c0d33ef)

What is your advice to improve this? Remove VOSK completely?

**Comment by DanielnetoDotCom** [comment]
To be honest, I don't like Vosk. It's free, but not very accurate. For precise transcription and translation, I use the AI plugin: https://github.com/WWBN/AVideo/wiki/AI-Plugin#automatic-transcription.

The AI is a paid service, costing USD 1.50 per transcription and USD 1.50 per translation, but it works very well.

**Comment by gbrn** [comment]
> Danny, subtitle generation is disabled in the SubtitleSwitcher plugin, but the system still generates subtitles, check it out:
> 
> ![image](https://private-user-images.githubusercontent.com/37880073/364434964-d4272ded-c5fa-4384-8291-8fe2686f3a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjkzNzEsIm5iZiI6MTcyNTQ2OTA3MSwicGF0aCI6Ii8zNzg4MDA3My8zNjQ0MzQ5NjQtZDQyNzJkZWQtYzVmYS00Mzg0LTgyOTEtOGZlMjY4NmYzYTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDE2NTc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MTY0MjNiMDBlMGNhMjRmNGQ3ZGI1OTc3OWMxNmFhYmRiMjE2ODk3ODNmMDE3OGJkZWJjOGE3MTE4MTRhNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C0oJVtYaiu1AYXY0DzcKvUsnE8tqri1HQyBnXuyIMR8)

Ok, I'll remove VOSK...

Regarding this bug, is there any way to see what's going on? The system is not respecting the Automatic Transcript OFF option.

**Comment by DanielnetoDotCom** [comment]
if the transcription is already generated you need to delete the files that are already generated

new videos not supposed to generate transcriptions anymore. 

to delete all transcriptions try this
```
cd /var/www/html/AVideo
php deleteCC.php
```

**Comment by gbrn** [comment]
ok the script worked. Thanks.
