### ISSUE TITLE
Live Links needs a thumbnail image incase it can't pull from the feed

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9377]
Would be awesom for Live links to have a thumbnail option Currently using rumble for a live stream to it and it just stays on the default ONLINE image. If there was a thumbnail placeholder it will make this perfect.

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by JoshWho** [comment]
It doesn't seem like it is adding the Thumbnail I gave it. I cleared the cache and it is still showing the default. 
![image](https://github.com/user-attachments/assets/b7b1b771-ac13-4749-a318-773735b1101f)

**Comment by JoshWho** [comment]
Neverminded I got it to work. This is awesome. Thank you
