### ISSUE TITLE
Live Notifications stopped working 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9379]
https://github.com/WWBN/AVideo/issues/9371#issuecomment-2331994745

Stopped working after the last update. 

Regular upload email notifications still work but no longer seeing when users go live in the email notifications.

**Comment by DanielnetoDotCom** [comment]
Anything in the logs?

**Comment by JoshWho** [comment]
No nothing showing for Live only the upload ones show

**Comment by JoshWho** [comment]
Every once in a while I see a live notification. Not sure what makes one users work but others not?

**Comment by DanielnetoDotCom** [comment]
Same here? 
https://github.com/WWBN/AVideo/issues/9371
I will close the other one

**Comment by JoshWho** [comment]
I can't find when this is happening. Live streams are constant on here but I do not see them in the log

**Comment by JoshWho** [comment]
I also noticed the Notification bell also does not show when they are live but does show when they upload. No records of going live it seems.

**Comment by DanielnetoDotCom** [comment]
I can see this here 

![image](https://github.com/user-attachments/assets/00ece0da-80ee-4ac2-835e-ee0e5db18157)

To make sure the notification is correct you should be able to access and compare this here https://ftjmedia.com:8443/stats

**Comment by JoshWho** [comment]
There use to also be ones that says they are live now and shows the red circle I have in the template. I seen one get through yesterday.

**Comment by DanielnetoDotCom** [comment]
Sorry, I am not understanding what you are saying

**Comment by JoshWho** [comment]
Have to wait until I see one again. I already cleared it.

**Comment by DanielnetoDotCom** [comment]
do you mean if you clear the cache does it appear?

**Comment by JoshWho** [comment]
![download](https://github.com/user-attachments/assets/9fbacb4b-e5d8-450b-af2b-89356c4d5046)
Last night I got this one but didn't get any new ones sense then

**Comment by DanielnetoDotCom** [comment]
you must check here if he is really live https://ftjmedia.com:8443/stats

**Comment by JoshWho** [comment]
Only thing I get for the on publish is this error all the time

  [12-Sep-2024 09:35:03 America/Chicago] PHP Warning:  Undefined array key "HTTP_USER_AGENT" in path/to/my/streamer/site/plugin/Live/Live.php on line 3012

**Comment by JoshWho** [comment]
![da744fde-1ab5-4c2d-af87-304e3ffe4740](https://github.com/user-attachments/assets/b3b77cdf-05d6-4939-8e6e-e46bb7a4c009)

**Comment by DanielnetoDotCom** [comment]
forget the HTTP_USER_AGENT log, and get the logs from the tail command

**Comment by JoshWho** [comment]
See how some show me the notification I supposed to get by email and shows my the live notification and then some never show 
![197a17b0-78bb-4839-86c4-72fe164a97ac](https://github.com/user-attachments/assets/b670c38c-e39d-4998-a9bc-9b4657946e19)
