### ISSUE TITLE
Live Watchers count sometimes closes all the sockets and when hundreds still watching it only shows 6 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9388]
There needs to be a better heart beat keep alive going back and fourth from the clients browser. If they lose connection they should be able to ping back once the connection is re established. 

There was 130 watching and this stream is over 48 hours and just a few minutes ago it dropped to just 6 watching. 
![5e624c87-f2e7-40bf-9a5a-b3df9d3f556b](https://github.com/user-attachments/assets/1c778c5c-9c21-4f5e-91fd-dd30cd502343)

**Comment by JoshWho** [comment]
Now all the old watchers have to refresh to show again as viewing.

**Comment by DanielnetoDotCom** [comment]
Sorry what?

**Comment by JoshWho** [comment]
There is 130 people actually watching but something killed their connection with the live users watching and now only showing new people watching.

**Comment by DanielnetoDotCom** [comment]
how do you know there are 130?

**Comment by JoshWho** [comment]
I have external analytics installed and can see them

**Comment by JoshWho** [comment]
Plus you can also still see the online user count in the YOT Sockets thing

**Comment by DanielnetoDotCom** [comment]
The number in your live comes from the socket. 

If you are not 100% about the numbers you can restart your socket

some times you have more users then what really is, but never less.

some times you have lost connections in the socket.

**Comment by JoshWho** [comment]
It is people that has been watching this stream for over 12 hours so until they refresh or something they will not be counted.

**Comment by DanielnetoDotCom** [comment]
whatching now is a live count, 

the users that did disconnect are not counted anymore
