### ISSUE TITLE
Live Link Twitter Card Not showing description or thumbnail

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9400]
![-1-Home-X](https://github.com/user-attachments/assets/fbc223d4-3da3-4228-94f0-5c210856cb5b)

![Card-Validator-Twitter-Developers](https://github.com/user-attachments/assets/2e9e07d1-48ec-44c0-97bb-44c25aabf2e2)

This is that link https://ftjmedia.com/liveLink/1/joshwho-truth-intel-tv---learn-what-the-gov-doesn-t-want-you-to-know---seekingthetruth-live-stream

**Comment by DanielnetoDotCom** [comment]
Sorry I do not know what is going on, I rested in 2 different testers and seems to be fine

https://orcascan.com/tools/open-graph-validator?url=https%3A%2F%2Fftjmedia.com%2FliveLink%2F1%2Fjoshwho-truth-intel-tv---learn-what-the-gov-doesn-t-want-you-to-know---seekingthetruth-live-stream
![captures_chrome-capture-2024-8-13](https://github.com/user-attachments/assets/20d013f0-d0d7-4626-9be3-56e00bf23c57)

https://toolsaday.com/seo/open-graph
![captures_chrome-capture-2024-8-13 (2)](https://github.com/user-attachments/assets/c5957bfb-5625-4d84-ba9c-f58beca40c2d)

**Comment by JoshWho** [comment]
https://x.com/JoshWhoX/status/1834318525999337875 here is the link on X  I use https://cards-dev.x.com/validator to make these tests.

**Comment by DanielnetoDotCom** [comment]
Can you please try this update?

**Comment by JoshWho** [comment]
Didn't fix it and now there is a new error

![80c9114f-2377-4441-a4aa-254c9148d743](https://github.com/user-attachments/assets/07ed4dee-529a-4764-9142-b32c30fb96c6)

**Comment by DanielnetoDotCom** [comment]
I sent you updates directly, can you please try again?

**Comment by JoshWho** [comment]
> I sent you updates directly, can you please try again?

That did the trick. Thank you @DanielnetoDotCom
