### ISSUE TITLE
Meaning of "status" of a video in SQL table "videos"

### ISSUE THREAD

**Issue by ruzakuku** [WWBN/AVideo#9406]
Could I know the meaning of the "status" value of a video in the "videos" table ?
I notice most of "a", some "b", some "i", some "e".

Thank you

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/blob/0825d38d68918222b2fb961167a61cb1fdc7ef99/objects/video.php#L74-L88

**Comment by ruzakuku** [comment]
Thank you !
