### ISSUE TITLE
Categories - Not showing on the Left hand side. No errors showing anywhere

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#9412]
Hi 

My categories on the left menu are not showing for some reason. No errors in the Logfile. 

Trying to find if any errors as well as make the categories show at the top of the left menu.
Please advise.
Thanks

**Comment by kollossus55** [comment]
Screenshot enclosed..

Regards

________________________________

**Comment by DanielnetoDotCom** [comment]
there is no screenshot here, make sure you add it direcrly on github

https://github.com/WWBN/AVideo/issues/9412

**Comment by kollossus55** [comment]
![categories no options](https://github.com/user-attachments/assets/5cdfacdb-2e09-46f7-9dfb-5714f23f0b63)

Apologies

**Comment by DanielnetoDotCom** [comment]
Make sure this is unchecked

![image](https://github.com/user-attachments/assets/70d266b6-494f-4707-a929-7cee2746bea5)

**Comment by kollossus55** [comment]
ok

**Comment by kollossus55** [comment]
Hi 
Yeah its still not showing..
Please advise...

**Comment by DanielnetoDotCom** [comment]
Check if this is checked

![image](https://github.com/user-attachments/assets/a838cfee-f660-45d9-bb9f-8e7bdaa23105)

**Comment by kollossus55** [comment]
Hi 
Yes its now showing... I must of changed it at some stage. 
How do I move "categories" up higher the menus...

**Comment by kollossus55** [comment]
Also. Now the Ads are not showing.. Do you want me to open a new ticket ? 
When I check the Ad server plugin, I can see that the "Enable Ads Plugin" butoon in top right corner is always off. I click it on, but when I go back in again it is off.. There's something wrong there.

**Comment by kollossus55** [comment]
Closing this issue. Will open new issue regarding ADs plugin
