### ISSUE TITLE
recapche code is invisible

### ISSUE THREAD

**Issue by mrgodgiven** [WWBN/AVideo#9413]
Greetings Mr @DanielnetoDotCom  The code is not visible when I try to make a donation , please help.![image](https://github.com/user-attachments/assets/d5449630-44af-4bc4-8637-00cadc7f504c)

**Comment by DanielnetoDotCom** [comment]
check if you add any custom CSS, I could not reproduce it here.

**Comment by mrgodgiven** [comment]
ni I did not add any css

**Comment by DanielnetoDotCom** [comment]
can you please reproduce it on demo site?

https://demo.avideo.com/

**Comment by mrgodgiven** [comment]
code option is disabled on demo 
![image](https://github.com/user-attachments/assets/3d3f2df3-08bb-470f-bd9d-c0b68e941429)

how do i disable it on mine as well 
![image](https://github.com/user-attachments/assets/963c7cfa-01be-48d3-b61e-2e74d3a4e193)

**Comment by DanielnetoDotCom** [comment]
CustomizeUser -> disableCaptchaOnWalletDirectTransferDonation
