### ISSUE TITLE
So now that we have friend requests and video calling and messaging where is our Buddylist?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9415]
Need to have a Buddylist page so we can browse to see if our friends are online and able to call them or not.

**Comment by JoshWho** [comment]
Buddylist should show their status if they are available or busy or sleeping if extras get added lol

Also Should only show online when they are really online making this a complete communications system.

**Comment by JoshWho** [comment]
But what about the buddlylist page that lets us see our friends we added?

**Comment by DanielnetoDotCom** [comment]
I see, you mean a separated page like the one you have in the "My Account" -> My Friends?

**Comment by JoshWho** [comment]
Yes something like a messenger or something of it.

**Comment by milehighkaraoke** [comment]
@JoshWho what plugin is needed for friend requests

**Comment by JoshWho** [comment]
Should be in the next version I think @DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
The plugin is already available 

https://github.com/WWBN/AVideo/tree/master/plugin/UserConnections

**Comment by milehighkaraoke** [comment]
Ok, where do I find the friend request feature
@DanielnetoDotCom 
![Screenshot_20240923_130921_Chrome](https://github.com/user-attachments/assets/ce8737f6-b05a-4624-90a4-d69b7fbe803e)

**Comment by DanielnetoDotCom** [comment]
When you are is someone's channel you can request friendship.

![image](https://github.com/user-attachments/assets/56baeb2e-b9e0-48c2-8131-57102801c6cd)

 they need to approve it in "My Account"

![image](https://github.com/user-attachments/assets/e88df26d-1915-4c19-aa9f-45d964b8bdc5)

**Comment by JoshWho** [comment]
So will there be a buddylist like messenger we can click on to see if our friends are online?

**Comment by DanielnetoDotCom** [comment]
I just sent you updates with a Friends list


![chrome-capture-2024-8-25 (1)](https://github.com/user-attachments/assets/0e91b15f-fdd3-49ff-a79c-bd4a408b94da)

**Comment by JoshWho** [comment]
Do I need to turn it on I do not see it after updating

**Comment by JoshWho** [comment]
I see it now. AWESOME Thank you @DanielnetoDotCom
