### ISSUE TITLE
Twitter Card still showing sites description and not the video description

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9418]
![5b20dcc3-7740-4e93-a521-f1e7c9d84aef](https://github.com/user-attachments/assets/b224632a-8294-4c23-b564-53f0f1ce96c2)

from video https://ftjmedia.com/video/.GiEyowHAepNeBpnbWPUlsg

**Comment by DanielnetoDotCom** [comment]
If you have no description in your video it will use the site description. 

also here is what I see now

![image](https://github.com/user-attachments/assets/b7012e8a-2029-4aa5-9b92-9780de73ae48)

**Comment by JoshWho** [comment]
Thnk you yes fixed
