### ISSUE TITLE
Need a way to change ownership to a Live links via as admin

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9427]
I am making accounts for each tv network I am adding and want to switch the live links to go to those accounts but can only do this by editing the mysql tables, need a way to do this in live links as a admin. All streams needs to have their own chats and this is the best way to do it. Just need an easier option to change who is the owner for the live link stream.

**Comment by JoshWho** [comment]
![130e810a-33e5-49fb-9795-aefd8ad76576](https://github.com/user-attachments/assets/2d324e50-622f-40d4-9180-06117cc49150)
 I made a account for RT but now there is no way to set the live links to that account unless I do it by mysql.

**Comment by JoshWho** [comment]
Just like the VOD there should be a way to set the owner of it for Live Links
![db4dd0c8-183d-4f9e-926a-ec0af70a1247](https://github.com/user-attachments/assets/157af17e-0fc9-4f33-b964-cf7f6bb00a11)

**Comment by JoshWho** [comment]
No rush just would be a nice feature.

**Comment by DanielnetoDotCom** [comment]
This update should do it.
