### ISSUE TITLE
Need a way to not show Live Links in Notification bell but still show on categories.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9428]
Would be awesome to exclude from the other real live streams and only show in the categories set in the Live links stream. 
![24-7-Live-TV-·-FTJ-Media-·-24-7-Live-TV-·-·-24-7-live-tv-·-FTJ-Media-09-22-2024_02_49_AM](https://github.com/user-attachments/assets/c9d7f540-282f-4531-a551-f5009a41933e)
do not show here

**Comment by JoshWho** [comment]
but still show in he category selection.

**Comment by DanielnetoDotCom** [comment]
Update and try this  

```
#userNotificationsFilterButtons .LiveLink_app{
    display: none;
}
```

**Comment by JoshWho** [comment]
ok Just ran the update not sure if this is related but I am seeing double notification now for a single live stream 
![5b3ed11d-67f6-49fd-90a8-0e575adc44b4](https://github.com/user-attachments/assets/f29a783f-462f-4c82-a6b0-7ded0c883fea)

**Comment by JoshWho** [comment]
Also How do I get it to not show on the top home but still in the category?
![2163c8ff-2b6b-4cfe-9bdf-ccc614dd2dac](https://github.com/user-attachments/assets/d826d034-5389-4e51-b635-e9873d6dd2db)
![4ec80685-8835-488e-931d-96f5633ccf35](https://github.com/user-attachments/assets/96826efb-e531-46f7-a9ed-2f3d39ef163f)

**Comment by JoshWho** [comment]
It is also showing the live link count in the bell 
![fba1c847-2409-4242-9353-fb4be05a4c38](https://github.com/user-attachments/assets/d3a12ad9-1d1a-4007-b2b7-62cd0aa2e49c)

**Comment by DanielnetoDotCom** [comment]
Sorry, please try this update

**Comment by JoshWho** [comment]
> Sorry, please try this update

That fixed the double notification. Thank you

**Comment by DanielnetoDotCom** [comment]
this?

https://ftjmedia.com/live

**Comment by JoshWho** [comment]
No Live Links separate it from the notification bell icon.  

That way I can have them showing only in the Category pages Like eg. want the Live links **CMC music network** to appear in the **Music Category,** but when I mark it active it shows up on the **bell notification** as a number and still on the **top of the home page.**

**Comment by DanielnetoDotCom** [comment]
So instead of livelink why dont you add as an video embed link?

**Comment by JoshWho** [comment]
Well I was thinking if other people who live stream will get the hint they can make their streams appear in these categories to go live. Like the news category I want to show all the live links I have for that.

**Comment by JoshWho** [comment]
So basically just a way to **hide on front page** and not show in the **notification bell**.

**Comment by JoshWho** [comment]
Answer
The error message you're encountering suggests that the record_max_size directive in your NGINX configuration is either incorrectly formatted or not recognized. Here are some steps to troubleshoot and resolve this issue:

1. Check Syntax for record_max_size
Ensure that record_max_size is formatted correctly. The correct syntax should look like:
