### ISSUE TITLE
Corrupted videos not showing as broken How can we make them apart of the Broken listed?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9431]
![1957b983-449b-46d5-b0d9-a088cd9fcf8a](https://github.com/user-attachments/assets/3cd23542-a708-4932-92db-502c26f0baaf)

I am listing the videos that are all corrupted
SMOKO
Dr. Pierces Birthday Stream on 11-Sep-24-19:50:14 https://ftjmedia.com/channel/Smoko/video/.jVwjkJP6mWD-J4C01nMbXQ/dr.-pierces-birthday-stream-on-11-sep-24-19-50-14
Dr. Pierces Birthday Stream on 11-Sep-24-11:03:11 https://ftjmedia.com/channel/Smoko/video/.SPCRcKurkGSrzBuV7-HVYg/dr.-pierces-birthday-stream-on-11-sep-24-11-03-11

FLOOD
The Flood - 091724 - 0382 - Tuesday of Legend on 17-Sep-24-07:01:58 https://ftjmedia.com/channel/FLOOD/video/.4dpzrNEPVorWaxCVQ6LpLw/the-flood---091724---0382---tuesday-of-legend-on-17-sep-24-07-01-58
The Flood - 083024 - 0367 - THE SLOW SHOW SUICIDE SHOWCASE on 30-Aug-24-07:02:45 https://ftjmedia.com/channel/FLOOD/video/.xljg9ZJl42_5aqcB6EzGqg/the-flood---083024---0367---the-slow-show-suicide-showcase-on-30-aug-24-07-02-45
The Flood - 071724 - 0330 - Wednesday Ethnostream! on 17-Jul https://ftjmedia.com/channel/FLOOD/video/.YyJsYzdsTEurI_GqWp5hQA/the-flood---071724---0330---wednesday-ethnostream-on-17-jul-24-10-55-37

DAVIS
David Ben Lehrman Kvetches https://ftjmedia.com/channel/Davis/video/.wygRVEe3yvubcCwKHn-NBg/david-ben-lehrman-kvetches

BENTANKLIN
Ben Tanklin- 8/7/24 - Wednesday's White UPDATE! https://ftjmedia.com/channel/BenTanklin/video/.mGAclobGxhcezt90KtB1gg/ben-tanklin--8-7-24---wednesday-s-white-update
Ben Tanklin- DayWalker Series Episode #3- MidWeek Report https://ftjmedia.com/channel/BenTanklin/video/.b3y9AEq-uZ--nNmopUlS8Q/ben-tanklin--daywalker-series-episode-3--midweek-report

CULTEREDTHUG
Q & A On Fascism (Oswald Mosley) https://ftjmedia.com/channel/CulturedThug/video/.WAWfcL6xhMvtbqp45b7csw/q-a-on-fascism-oswald-mosley
 https://ftjmedia.com/channel/CulturedThug/video/.JRp15ZcKmRFNtXSUVVexOg/hilaire-belloc-on-the-jews

ZACK
Interview with Pyschodrilla on 25-Jul-24-00:06:19 https://ftjmedia.com/channel/LogosRevealed/video/.Gp1dEzYgHKA7WgwZFZ1Kcw/interview-with-pyschodrilla-on-25-jul-24-00-06-19

**Comment by JoshWho** [comment]
![94f44733-820c-4d9c-b9de-b061c3a2f909](https://github.com/user-attachments/assets/e09d4cdb-60d7-46be-80db-3f627c1d6756)

**Comment by JoshWho** [comment]
![31f90c0d-d02b-46d7-a7a5-fc9b7ac47bc9](https://github.com/user-attachments/assets/a7f57abf-3d38-4562-ab34-1fa0a11c7aa9)

**Comment by JoshWho** [comment]
Is there a cron we can run that just checks the videos for corruption and flags it to broken?

**Comment by DanielnetoDotCom** [comment]
First we should investigare why are they corrupted 

Broken missing files is an error and should not happen. 

And it should be flagged as Broken when you try to access the video

**Comment by JoshWho** [comment]
That's why I was thinking maybe some kind of bot or something that tries to play it to see if it is corrupt and if so mark it as broken.

**Comment by JoshWho** [comment]
> First we should investigare why are they corrupted
> 
> Broken missing files is an error and should not happen.
> 
> And it should be flagged as Broken when you try to access the video

The encoder should check the file before deleting the raw file to see if it is not corrupted.

**Comment by JoshWho** [comment]
Here is another corrupted video from last night 
 https://ftjmedia.com/channel/NightNationReview/video/.jWgpiaQGG3Iik3zj3rQqRg/night-nation-review-on-23-sep-24-21-48-37

**Comment by JoshWho** [comment]
![357d1b9c-c2a6-418c-a4fd-7eba0594376f](https://github.com/user-attachments/assets/3bae2727-c6e2-45bc-83ce-c3875600e8db)

**Comment by JoshWho** [comment]
Here is another one https://ftjmedia.com/channel/FLOOD/video/.LeofS4G-Ao7QgyCW0XnQJQ/live-review-1488-radio-webcast-on-23-sep-24-10-17-29

![b327fa88-78bf-4a4a-a5da-4f4c9c666f02](https://github.com/user-attachments/assets/d2b46ddd-e3c8-4306-a8ef-9119b1ff81ad)

**Comment by DanielnetoDotCom** [comment]
> Here is another one https://ftjmedia.com/channel/FLOOD/video/.LeofS4G-Ao7QgyCW0XnQJQ/live-review-1488-radio-webcast-on-23-sep-24-10-17-29
> 
> ![b327fa88-78bf-4a4a-a5da-4f4c9c666f02](https://private-user-images.githubusercontent.com/39392449/370458542-d2b46ddd-e3c8-4306-a8ef-9119b1ff81ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMDk3MzcsIm5iZiI6MTcyNzIwOTQzNywicGF0aCI6Ii8zOTM5MjQ0OS8zNzA0NTg1NDItZDJiNDZkZGQtZTNjOC00MzA2LWE4ZWYtOTExOWIxZmY4MWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDIwMjM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMGVlNmY3NzE5MTc5MGFiNzBlNGVhNjVkMzM0ZWJhNDljZmQxNDg1YWMzNTYxNGQ3NmQ5YTQyYjRhZDNjYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0fUhh18wNPq12j8f83KGWcP9Y1rfuFeS6K9jyXJSSuc)

This one is playing, maybe you tried to watch the video too earlier, before the script unpack it.
it was a false flag

**Comment by JoshWho** [comment]
No it marked it as broken and redirects to a video that plays

**Comment by DanielnetoDotCom** [comment]
you are right, so you need to check the logs then

**Comment by JoshWho** [comment]
It is your encoder

**Comment by JoshWho** [comment]
My theory is that 11 hour video was causing the server to be at max resources and made the other videos also corrupt during the time it was trying to process it. 

Is there a way to make the dvr cut off after 4 hours and start recording a new video?

**Comment by DanielnetoDotCom** [comment]
I see

I will only be able to check logs tomorrow 

A 11 hours video will probably be corrupted if you use the public server

**Comment by JoshWho** [comment]
> I see
> 
> I will only be able to check logs tomorrow
> 
> A 11 hours video will probably be corrupted if you use the public server

I agree it is very long. Any way to stop dvy if it exceeds 4 hours?

**Comment by JoshWho** [comment]
I tried to use the record max value and says this version of nginx does not have that it is a older version

**Comment by JoshWho** [comment]
So for a fix I made a bash script

```
#!/bin/bash

# Path where recordings are stored
RECORDING_PATH="/var/www/tmp"
# Maximum size in bytes (5GB = 5368709120 bytes)
MAX_SIZE=5368709120
# Maximum duration in seconds (e.g., 4 hours = 14400 seconds)
MAX_DURATION=14400

# Function to start a new recording
start_new_recording() {
    # Logic to signal NGINX or start new recording based on your setup
    echo "Starting new recording..."
}

# Main loop
while true; do
    # Find the current recording file (assuming naming convention)
    current_recording=$(find "$RECORDING_PATH" -name "*.flv" -type f -printf "%T@ %p\n" | sort -n | tail -1 | cut -d ' ' -f2-)
    
    if [ -n "$current_recording" ]; then
        # Get creation time and current time
        create_time=$(stat -c %Y "$current_recording")
        current_time=$(date +%s)
        duration=$((current_time - create_time))
        
        # Check size and duration
        current_size=$(du -b "$current_recording" | cut -f1)
        
        if [ $duration -gt $MAX_DURATION ] || [ $current_size -gt $MAX_SIZE ]; then
            # Here you might want to rename or move the file, and start a new recording
            echo "Recording has exceeded size/duration limits, renaming and starting new."
            
            # Rename the file with a timestamp or move it to an archive
            new_name=$(date '+%d-%b-%y-%T')-$(basename "$current_recording")
            mv "$current_recording" "${RECORDING_PATH}/${new_name}"
            
            # Call function to start new recording
            start_new_recording
        fi
    fi
    
    # Check every 60 seconds
    sleep 60
done
```

and then have a cron run

`* * * * * /usr/local/nginx/recordtimscript.sh > /dev/null 2>&1`

**Comment by DanielnetoDotCom** [comment]
To ensure that the recorded file does not exceed the size limit for a 4-hour video, it's essential to adjust the `record_max_size` parameter in your `nginx.conf` based on the bitrate of your video stream.

### Example Configuration:
```nginx
recorder video { 
    record all manual; 
    record_path /var/www/tmp; 
    record_notify on; 
    record_max_size 4600M;  # Set max size for a 4-hour video, adjust as needed
    record_suffix -%d-%b-%y-%T.flv; 
}
```

### Steps to Determine the Maximum Size:
1. **Calculate the Bitrate:**
   - Estimate the bitrate of your video stream. For a 720p resolution, the average bitrate is typically around 2.5 Mbps. However, this value is just a sample and can vary significantly based on the resolution and compression settings used.

2. **Determine the File Size:**
   - Convert the bitrate to megabytes per second (1 Mbps = 0.125 MBps).
   - Calculate the total file size for a 4-hour video (14,400 seconds).
   - Example for 720p at 2.5 Mbps:
     ```bash
     Bitrate (in MBps) = 2.5 * 0.125 = 0.3125 MBps
     Total File Size (in MB) = 0.3125 * 14,400 = 4,500 MB (approximately 4.5 GB)
     ```

3. **Adjust Based on Resolution:**
   - If you are using a higher resolution, such as 1080p or 4K, or if you have different compression settings, the bitrate will be higher, and you will need to increase the `record_max_size` parameter accordingly.

4. **Restart Nginx After Configuration Update:**
   - After modifying the `nginx.conf` file, restart Nginx to apply the changes:
   ```bash
   /usr/local/nginx/sbin/nginx -s stop && /usr/local/nginx/sbin/nginx
   ```

**Comment by JoshWho** [comment]
> To ensure that the recorded file does not exceed the size limit for a 4-hour video, it's essential to adjust the `record_max_size` parameter in your `nginx.conf` based on the bitrate of your video stream.
> 
> ### Example Configuration:
> ```nginx
> recorder video { 
>     record all manual; 
>     record_path /var/www/tmp; 
>     record_notify on; 
>     record_max_size 4600M;  # Set max size for a 4-hour video, adjust as needed
>     record_suffix -%d-%b-%y-%T.flv; 
> }
> ```
> 
> ### Steps to Determine the Maximum Size:
> 1. **Calculate the Bitrate:**
>    
>    * Estimate the bitrate of your video stream. For a 720p resolution, the average bitrate is typically around 2.5 Mbps. However, this value is just a sample and can vary significantly based on the resolution and compression settings used.
> 2. **Determine the File Size:**
>    
>    * Convert the bitrate to megabytes per second (1 Mbps = 0.125 MBps).
>    * Calculate the total file size for a 4-hour video (14,400 seconds).
>    * Example for 720p at 2.5 Mbps:
>      ```shell
>      Bitrate (in MBps) = 2.5 * 0.125 = 0.3125 MBps
>      Total File Size (in MB) = 0.3125 * 14,400 = 4,500 MB (approximately 4.5 GB)
>      ```
> 3. **Adjust Based on Resolution:**
>    
>    * If you are using a higher resolution, such as 1080p or 4K, or if you have different compression settings, the bitrate will be higher, and you will need to increase the `record_max_size` parameter accordingly.
> 4. **Restart Nginx After Configuration Update:**
>    
>    * After modifying the `nginx.conf` file, restart Nginx to apply the changes:
>    
>    ```shell
>    /usr/local/nginx/sbin/nginx -s stop && /usr/local/nginx/sbin/nginx
>    ```

Doesn't work and is why I came up with the above trick  https://github.com/WWBN/AVideo/issues/9431#issuecomment-2372391879

**Comment by DanielnetoDotCom** [comment]
It must work, it works in all my servers 

Did you restart nginx after change it?

**Comment by DanielnetoDotCom** [comment]
Or just remove and reinstall nginx , it should not be a big deal

**Comment by JoshWho** [comment]
Yes when I click restart It errors and shows this:

sudo /usr/local/nginx/sbin/nginx
nginx: [emerg] "record_max_size" directive invalid value in /usr/local/nginx/conf/nginx.conf:39
nginx: [emerg] "record_max_size" directive invalid value in /usr/local/nginx/conf/nginx.conf:39

**Comment by DanielnetoDotCom** [comment]
> record_max_size

I guess you add it in the wrong place, check this https://github.com/WWBN/AVideo/issues/9431#issuecomment-2372445342

```nginx
recorder video { 
    record all manual; 
    record_path /var/www/tmp; 
    record_notify on; 
    record_max_size 4600M;  # Set max size for a 4-hour video, adjust as needed
    record_suffix -%d-%b-%y-%T.flv; 
}
```

**Comment by JoshWho** [comment]
That is where it is. U can see it I never changed what it had from the install. I uncomment it and click save and restart nginx and kicks out that error.

**Comment by JoshWho** [comment]
```
	    # record all; # Use this line if you NOT want to use the controls
			    record all manual;
			    record_path /var/www/tmp;
			    record_notify on;
			    #record_max_size 12582912KM;
			    #will produce files of the form yourUserKey-24-Apr-13-18:23:38.flv
			    record_suffix -%d-%b-%y-%T.flv;
}

```

**Comment by JoshWho** [comment]
I tried g then G than MB mb all variables shows that error.

**Comment by JoshWho** [comment]
Answer
The error message you're encountering suggests that the record_max_size directive in your NGINX configuration is either incorrectly formatted or not recognized. Here are some steps to troubleshoot and resolve this issue:

Check Syntax for record_max_size
Ensure that record_max_size is formatted correctly. The correct syntax should look like:

**Comment by JoshWho** [comment]
> So for a fix I made a bash script. This will Cut the stream once it reaches 4 hours or 5 gigs and start a new recording.
> 
> ```
> #!/bin/bash
> 
> # Path where recordings are stored
> RECORDING_PATH="/var/www/tmp"
> # Maximum size in bytes (5GB = 5368709120 bytes)
> MAX_SIZE=5368709120
> # Maximum duration in seconds (e.g., 4 hours = 14400 seconds)
> MAX_DURATION=14400
> 
> # Function to start a new recording
> start_new_recording() {
>     # Logic to signal NGINX or start new recording based on your setup
>     echo "Starting new recording..."
> }
> 
> # Main loop
> while true; do
>     # Find the current recording file (assuming naming convention)
>     current_recording=$(find "$RECORDING_PATH" -name "*.flv" -type f -printf "%T@ %p\n" | sort -n | tail -1 | cut -d ' ' -f2-)
>     
>     if [ -n "$current_recording" ]; then
>         # Get creation time and current time
>         create_time=$(stat -c %Y "$current_recording")
>         current_time=$(date +%s)
>         duration=$((current_time - create_time))
>         
>         # Check size and duration
>         current_size=$(du -b "$current_recording" | cut -f1)
>         
>         if [ $duration -gt $MAX_DURATION ] || [ $current_size -gt $MAX_SIZE ]; then
>             # Here you might want to rename or move the file, and start a new recording
>             echo "Recording has exceeded size/duration limits, renaming and starting new."
>             
>             # Rename the file with a timestamp or move it to an archive
>             new_name=$(date '+%d-%b-%y-%T')-$(basename "$current_recording")
>             mv "$current_recording" "${RECORDING_PATH}/${new_name}"
>             
>             # Call function to start new recording
>             start_new_recording
>         fi
>     fi
>     
>     # Check every 60 seconds
>     sleep 60
> done
> ```
> 
> and then have a cron run
> 
> `* * * * * /usr/local/nginx/recordtimscript.sh > /dev/null 2>&1`

The beauty of this is now you do not need to calculate the variable bit rate now it works of file size or time limit. The latest NGINX can't even do this yet so we would be the first.

**Comment by DanielnetoDotCom** [comment]
trust me you are doing it wrong

I strongly recommend you to use the record_max_size

or just reinstall the live nginx rtmp server.

**Comment by JoshWho** [comment]
Summing it up to that server was bottleknecking resources and what trying to do more than what set ram was able to. Now solved by upgrading to 64 gig memory dedicated.
