### ISSUE TITLE
Chat Overlay Bubbles only is not working on OBS

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9432]
![Untitled7-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/4fd3cbe9-25d3-40d0-bb0d-916013ee8c95)

**Comment by DanielnetoDotCom** [comment]
can you please share what exacly URL are you using?

**Comment by JoshWho** [comment]
That one is this https://ftjmedia.com/plugin/Chat2/?live_transmitions_history_id=442&room_users_id=34&noFade=1&iframe=1&bubblesOnly=1&showCollapseButtons=1

**Comment by JoshWho** [comment]
Maybe the question mark somehow breaks it in OBS

**Comment by JoshWho** [comment]
![image](https://github.com/user-attachments/assets/913407df-bb34-4a73-b86b-aed002aaa460)

**Comment by JacekLange** [comment]
You have an unclosed tag in PHP.

![image](https://github.com/user-attachments/assets/4681cc4b-aceb-4e1e-8482-09822a0a0095)

**Comment by DanielnetoDotCom** [comment]
Check the latest Chat version

**Comment by JoshWho** [comment]
> Check the latest Chat version

Fixed Thank you @DanielnetoDotCom
