### ISSUE TITLE
Bulk Youtube embedder not grabbing thumbnails

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9433]
Tried the Bulk embedder and it didn't get the thumbnails when I tried to import 30 videos, I just ended up deleting them all.

**Comment by DanielnetoDotCom** [comment]
How are you doing that?

**Comment by JoshWho** [comment]
![bbce37d4-9c1b-41e2-bfbf-4cdd1775445c](https://github.com/user-attachments/assets/0b538330-f333-464b-88e2-3334bc128e79)

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by JoshWho** [comment]
Nope still blank 
![Users-·-FTJ-Media-09-23-2024_01_27_PM](https://github.com/user-attachments/assets/d559c595-8d72-401f-9599-1c6809cc6173)

**Comment by DanielnetoDotCom** [comment]
When you click in the video to watch the thumbs should appear

**Comment by DanielnetoDotCom** [comment]
hold on, I found something.

**Comment by DanielnetoDotCom** [comment]
Please try this update

**Comment by JoshWho** [comment]
> Please try this update

That did the trick thank you
