### ISSUE TITLE
Certain pages makes the Socket Connect thing disconnect

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9439]
![c3267013-9f97-4cf5-88ea-06bcc2cbfb11](https://github.com/user-attachments/assets/495e3520-966b-40d5-b6f3-313954589064)
https://ftjmedia.com/liveLink/23/bloomberg-tv

But when I go back to the home page it is fine

![f683a31b-8338-4339-8927-8ffd4f658dde](https://github.com/user-attachments/assets/898d9f66-c7a2-4d26-bb6d-3399483f0528)

**Comment by DanielnetoDotCom** [comment]
I guess if it is inactive, the socket drop the old ones, once it is active again it will still

**Comment by JoshWho** [comment]
Why on video pages and Live link pages it disconnects. I never seen it do that before

**Comment by JoshWho** [comment]
Even on live streams it disconnects, something is missing here

**Comment by JoshWho** [comment]
![8bf70fb2-79db-4b4e-a8fb-58089f05e296](https://github.com/user-attachments/assets/cb32663e-ef72-40b5-aaa8-06829d772507)

**Comment by JoshWho** [comment]
![image](https://github.com/user-attachments/assets/b139dd22-129f-4adb-8dbd-21ef74910850)

**Comment by JoshWho** [comment]
Is there a firewall or something?

**Comment by JoshWho** [comment]
Maybe SE linux or somthing?

**Comment by JoshWho** [comment]
even the copy code script is not working.

**Comment by JoshWho** [comment]
![83bfb1bf-d31a-4c06-bab9-8632947fb4f7](https://github.com/user-attachments/assets/d3bd514c-107f-4ed1-8d2d-f8c4b5ea1abf)

You never added the scheduler cron

**Comment by JoshWho** [comment]
I see the * * * * * php /var/www/html/AVideo/plugin/Scheduler/run.php in the cron tab. Not sure what is going on

**Comment by JoshWho** [comment]
When I click run it shows this

```
pre>.htaccess version mismatch. Updating to version 5.2.

Updated .htaccess to version 5.2.

Folder and subfolders are now secure.

CachesInDB::_deleteCacheStartingWith(hashName_live_) DELETE FROM CachesInDB WHERE MATCH(name) AGAINST('hashName_live_*' IN BOOLEAN MODE) OR name like 'hashName_live_%';
isLiveAndIsReadyFromKey::key: 66f5f30454a73-1 checking live_servers_id=1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Live::getStatsObject[1] 5: forced to be recreated
execAsync Linux: nohup sh -c "rm -R /var/www/html/AVideo/videos/cache/YPTObjectCache/live/ & echo \$!" > /dev/null 2>&1 &
Command output: []
Return value: 0
deleteCache not schedule /var/www/html/AVideo/videos/cache/YPTObjectCache/live/ [{"file":"\/var\/www\/html\/AVideo\/plugin\/Live\/Objects\/LiveTransmitionHistory.php","line":870,"function":"deleteCache","class":"CacheHandler","object":{},"type":"->","args":[]},{"file":"\/var\/www\/html\/AVideo\/plugin\/Live\/Live.php","line":1967,"function":"save","class":"LiveTransmitionHistory","object":{"live_transmitions_id":24,"categories_id":20},"type":"->","args":[]},{"file":"\/var\/www\/html\/AVideo\/plugin\/Live\/Live.php","line":1907,"function":"unfinishAllFromStats","class":"Live","type":"::","args":[true]},{"file":"\/var\/www\/html\/AVideo\/plugin\/Live\/Live.php","line":4391,"function":"checkAllFromStats","class":"Live","type":"::","args":[true]},{"file":"\/var\/www\/html\/AVideo\/plugin\/AVideoPlugin.php","line":3093,"function":"executeEveryMinute","class":"Live","object":{},"type":"->","args":[]},{"file":"\/var\/www\/html\/AVideo\/plugin\/Scheduler\/run.php","line":80,"function":"executeEveryMinute","class":"AVideoPlugin","type":"::","args":[]}]
unfinishAllFromStats saving LiveTransmitionHistory 66f5f30454a73-1 [472] 
</pre>
```

**Comment by DanielnetoDotCom** [comment]
your socket is not disconnecting for me

is it disconnecting for you?

please do not install anything, you site looks fine for me, check if is not something on your side

**Comment by JoshWho** [comment]
I have not installed anything yet

**Comment by JoshWho** [comment]
on that page?

**Comment by DanielnetoDotCom** [comment]
I have now 3 pages open, all fine and stable 

1. https://ftjmedia.com/channel/DrSeanBrooks/video/.JOsObe9ep1HRDOU2M7i7QA/this-is-war-part-657.-1
2. https://ftjmedia.com/live/1/Davis/1
3. https://ftjmedia.com/liveLink/23/bloomberg-tv

ask if someone else is having the same issue

**Comment by JoshWho** [comment]
On different computer using VPN still see this on the live stream playing 
![29da3c1a-f99c-4c4f-a268-63fd25744ed3](https://github.com/user-attachments/assets/f68a3815-115a-4459-a540-f12e216ab942)

**Comment by JoshWho** [comment]
Very possible it could be DNS. I can't see any other reason why

**Comment by DanielnetoDotCom** [comment]
how offten this happen to you?

I am not seeing here

![image](https://github.com/user-attachments/assets/e428d390-187d-4419-a627-8890a51ba28c)

**Comment by JoshWho** [comment]
Solved it was DNS error. All good now
