### ISSUE TITLE
Just a minor bug I am seeing double notifications again

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9440]
![f883e20f-dc99-471f-ad56-1fc6957a6c60](https://github.com/user-attachments/assets/2697fd4d-6b5a-43c4-99c7-da18cce31c2e)

**Comment by DanielnetoDotCom** [comment]
One is a scheduled live and anothe one is a real live you are doing. 

did you use the scheduled live key to connect or you use a regular key?

**Comment by DanielnetoDotCom** [comment]
I found, please check now!

**Comment by JoshWho** [comment]
Solved
