### ISSUE TITLE
Storage question

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9442]
Is there a process to make the other videos also go to the storage? 

![442df3e4-dda8-4b8e-ab9c-d816ddbbe01d](https://github.com/user-attachments/assets/82d48840-2776-46ff-8c48-ebb9350778e6)

**Comment by DanielnetoDotCom** [comment]
I just enabled the crontab that daily will sync the videos to the storage

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom

**Comment by JoshWho** [comment]
I also had to add

0 * * * * php /var/www/html/AVideo/install/getMp3FromAll.php
