### ISSUE TITLE
Video will not upload

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9445]
I tried this like 6 times now
![3827b09f-140f-4a51-8414-ae2260a62690](https://github.com/user-attachments/assets/47a1ace7-4caa-4af1-bcc9-f8615809c9e6)

As soon as it gets done uploading nothing happens, I never see it process.

**Comment by JoshWho** [comment]
![6e4c12b3-54c3-46ae-b8b8-f036a6b641c8](https://github.com/user-attachments/assets/a1f7d5fa-4402-447a-89a6-f026142361ec)

**Comment by JoshWho** [comment]
This video here https://odysee.com/@InBlackAndWhite:d/In-Black-and-White-Episode-6-Sexual-Perversion:9  I tried importing it I tried downloading it then uploading it I tried hand Breaking it and then uploading it all failed.

**Comment by DanielnetoDotCom** [comment]
Remove the sex word from the video URL and from the file name and try agaín

**Comment by JoshWho** [comment]
Why would that stop it?

**Comment by DanielnetoDotCom** [comment]
There are some triggers to try to avoid porn content

**Comment by JoshWho** [comment]
> There are some triggers to try to avoid porn content

Would have been nice to know or alerted that is what it was, I thought my internet was the issues after 6 times trying to upload this file been here all day for 8 hours trying to get this one uploaded.

**Comment by JoshWho** [comment]
Anyway to change that?

**Comment by JoshWho** [comment]
There are many other words that has sex in it and will confuse users why their upload is not working

**Comment by milehighkaraoke** [comment]
@DanielnetoDotCom 
Proverbs 16:4 The LORD has made everything for its purpose, even the wicked for the day of trouble.

Our father gave each of us free will and the ability to Sin, like it or not, it is part of that free will. We are not burdened to hold someone's hand in force as that is not free will..........
Censorship is SIN.
Matthew 23:13

**Comment by JoshWho** [comment]
This is also making it hard to setup as a series playlist and make all auto next I can't get it to populate episode 6 or seven. PLEASE we need to remove the censors on that word

**Comment by JoshWho** [comment]
![a2033768-6c58-41b9-a875-5c3750d9e83e](https://github.com/user-attachments/assets/4f262a69-5235-4831-9a16-1e1c56b44f35)

Also noticed you can't click the Play all on the series.

![200f3a5f-c2ef-498a-8490-2aa9f37a669b](https://github.com/user-attachments/assets/648cc251-446f-4d3f-92fe-72eef74899c1)
https://ftjmedia.com/channel/InBlackandWhite

**Comment by JoshWho** [comment]
Get ready for the biggest change in mass society and censorship will have us at the weakest point with it. We need not to fall into their hands.

**Comment by DanielnetoDotCom** [comment]
please check this update

**Comment by JoshWho** [comment]
It is not clickable still. It just darkens and says play all but won't let u click it.

**Comment by DanielnetoDotCom** [comment]
Please try now

**Comment by JoshWho** [comment]
> Please try now

perfect now it clicks

**Comment by JoshWho** [comment]
> There are some triggers to try to avoid porn content

Is there a way to disable that for our site?

**Comment by DanielnetoDotCom** [comment]
Add this in the encoder configuration.php
````
$global['disableCheck'] = 1;
````

**Comment by JoshWho** [comment]
Thank you
