### ISSUE TITLE
I can't get a new live link to show up 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9454]
![FTJ-Media-10-01-2024_07_41_PM](https://github.com/user-attachments/assets/07f180e6-651b-4e68-8bb1-5edcb45c014c)

![722699ee-c2d7-44fe-b686-94714dcfbebf](https://github.com/user-attachments/assets/261a5868-5e5c-4c41-a06a-66a11a4d340b)

**Comment by JoshWho** [comment]
I have no clue what is going on here 
![be2b9b02-709b-44a8-bd21-ec8d7612706f](https://github.com/user-attachments/assets/38f423c2-0ddd-4c02-9461-1bfafed35e43)

**Comment by JoshWho** [comment]
It is about to start in 15 minutes

**Comment by JoshWho** [comment]
Just set it to expire in 2026 and now it is working

**Comment by JoshWho** [comment]
I think something is either wrong with how time clocks work on the server or the scheduler is way off. We have been complaints when people schedule their streams that it cuts them off hours early then what they set.

**Comment by JoshWho** [comment]
Like a live streamer will scheduled their show for x time and ends at x time and they say they stream will end within the first hour which was nowhere close to what they scheduled it to.

**Comment by DanielnetoDotCom** [comment]
> Like a live streamer will scheduled their show for x time and ends at x time and they say their stream will end within the first hour which was nowhere close to what they scheduled it to.

this is probably a client/server timezone difference, and can you screen capture what do you mean with "tream will end within the first hour"

**Comment by JoshWho** [comment]
Not sure what it exactly is. The Live link I tried making work last night wouldn't work until I made it expire later than what it was I set the expire date to 202 and then it started working.

**Comment by JoshWho** [comment]
Thank you

**Comment by JoshWho** [comment]
The calenderer gets covered up by the Autofill drop down 
![image](https://github.com/user-attachments/assets/3a2a344d-8e33-4c67-95e5-29cdb6b9cb1c)

**Comment by DanielnetoDotCom** [comment]
Sorry I cannot control the autofill, also calendar is a native browser input. so it all is a browser fault.

**Comment by JoshWho** [comment]
> Sorry I cannot control the autofill, also calendar is a native browser input. so it all is a browser fault.

I c that sucks. Makes it hard to click the date for the calendar but I can manually fill it.

**Comment by JoshWho** [comment]
I have a test set up will let you know how it goes once done
![fdce6fdb-9e6d-4f15-8ade-96662de9a730](https://github.com/user-attachments/assets/8675bc8b-4acb-45c3-a861-366e699005e0)

**Comment by JoshWho** [comment]
Ok noticing how it is not showing on the home page as scheduled.

**Comment by DanielnetoDotCom** [comment]
what do you mean?

**Comment by JoshWho** [comment]
I scheduled
![39d052ac-ea94-4963-8d54-562db93ca9ce](https://github.com/user-attachments/assets/8618d985-733b-491f-94f5-2ea371e2acbb)
 it for 3:30 pm ct time and it is not showing on the home page like scheduled streams use to show.

**Comment by DanielnetoDotCom** [comment]
Do not forget you MUST update the plugin table in the plugins manager. 

![image](https://github.com/user-attachments/assets/17ceaf1d-adbe-4b8d-8b9a-feca74135aee)

**Comment by JoshWho** [comment]
> Do not forget you MUST update the plugin table in the plugins manager.
> 
> ![image](https://private-user-images.githubusercontent.com/18009293/373022388-17ceaf1d-adbe-4b8d-8b9a-feca74135aee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MDA4MTUsIm5iZiI6MTcyNzkwMDUxNSwicGF0aCI6Ii8xODAwOTI5My8zNzMwMjIzODgtMTdjZWFmMWQtYWRiZS00YjhkLThiOWEtZmVjYTc0MTM1YWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDIwMjE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMTQ2YWZjNzY0ZGI0OTMzMWFlNjFmOTY3NDdlMmZkYjBlNTIyMWQ3MmQ3NWMwZGE2MGQwNzhiZDg1OTkyODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7HVx4drs2_3ZjUhRfKb5XMS1dH_Tew_88TSVsjnrUQ0)

🤦 Forgot that part

**Comment by JoshWho** [comment]
I clicked install and now stuck on this page
![19de0f20-3cda-4921-821e-61271f497eab](https://github.com/user-attachments/assets/882ca36d-1615-45cb-a99c-985eb59e1ff1)

**Comment by JoshWho** [comment]
Reloaded the page and tried again and it just gets stuck

**Comment by DanielnetoDotCom** [comment]
Please check this update

**Comment by JoshWho** [comment]
Looks like it is working now. Thank you
