### ISSUE TITLE
CDN outage?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9456]
something weird is going on with the cdn resources not loading right.

**Comment by DanielnetoDotCom** [comment]
what exactly?

**Comment by JoshWho** [comment]
Like this link https://ftjmediacom.cdn.ypt.me/videos/v_240924070548_ve443/v_240924070548_ve443_thumbsV2_jpg.webp?cache=1727178416_1727891281

**Comment by DanielnetoDotCom** [comment]
![image](https://github.com/user-attachments/assets/2e7c0ee3-d215-4cd6-a74d-97ef91b9117d)

**Comment by JoshWho** [comment]
Weird must be my isp I see a bunny cdn error page

**Comment by DanielnetoDotCom** [comment]
can you screenshot the page

**Comment by JoshWho** [comment]
![a6bcc3ab-6b4e-4a66-adda-149b67d4c206](https://github.com/user-attachments/assets/354715d0-2809-4709-bc2e-e5735ef2d9f3)

**Comment by DanielnetoDotCom** [comment]
I guess you are not resolvind the ftjmediacom.cdn.ypt.me correctly

check your location here https://dnschecker.org/#A/ftjmediacom.cdn.ypt.me

and check if you are resolving the IP correclty

**Comment by JoshWho** [comment]
Yeah dns change probably
