### ISSUE TITLE
Added Stripe, how to set up Premium accounts for certain things?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9457]
We want to make only premium accounts able to upload and live stream, how do I go about setting that up?

Also How do I turn on tips with stripe in the live stream chats for only the premium accounts?

**Comment by DanielnetoDotCom** [comment]
Currently livestream and upload videos permisisons must be manually added

I may add options to do it with user groups in the future. 

once it is in the usergroup you will be able to create subscriptions to allow it.

**Comment by JoshWho** [comment]
That will be perfect.

**Comment by JoshWho** [comment]
When do you think you will be able to add Live streaming and Uploading to the permissions?

**Comment by JoshWho** [comment]
Donate from wallet captcha is too small to read in chat

![00e94332-3bdf-43e1-8a0a-bb91454879ad](https://github.com/user-attachments/assets/084c10ef-0793-4300-89c0-dbdce400de00)

**Comment by DanielnetoDotCom** [comment]
> When do you think you will be able to add Live streaming and Uploading to the permissions?
> 

This is not in my roadmap yet, but I have intrested to do, if you want to sponsor that I can start it next week

**Comment by JoshWho** [comment]
> > When do you think you will be able to add Live streaming and Uploading to the permissions?
> 
> This is not in my roadmap yet, but I have intrested to do, if you want to sponsor that I can start it next week

Will see, have to ask Dave will let you know.

**Comment by DanielnetoDotCom** [comment]
> Donate from wallet captcha is too small to read in chat

I found the issue, it will require a git pull and also update the Chat2 plugin to version 16.1

**Comment by JoshWho** [comment]
How does a user request funds like how do they get the money someone tipped them?

**Comment by DanielnetoDotCom** [comment]
If you mean how regular users load their wallets, it can be done with real money (stripe or paypal)

**Comment by JoshWho** [comment]
No like when people Request Withdraw how does that work or does the admins just get the request and send out with whatever we can.

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/YPTWallet-Usage#withdrawing-funds

**Comment by JoshWho** [comment]
My test payment of 5 dollars reflect to my wallet as 5 dollars but tripe takes a fee and should say 4.55  is there a way to calculate the fee in to reflect the real amount?

**Comment by JoshWho** [comment]
Let's re-examine the math you provided with the general understanding of Stripe's fee structure:

You mentioned:
Original amount: $5.00
After fee, the amount: $4.55

From this, we calculated:
Fee = $5.00 - $4.55 = $0.45

The percentage we calculated was 9%, but let's align this with Stripe's known fee structure:

Stripe's typical fee for online transactions at the time of my last update: 2.9% + $0.30.

Let's apply Stripe's fee to $5.00:

Percentage Fee: 2.9% of $5.00 = $5.00 * 0.029 = $0.145
Flat Fee: $0.30

Adding these together gives:
Total Fee = $0.145 + $0.30 = $0.445, which rounds to $0.45.

Now, if we calculate the final amount after applying this fee:
$5.00 - $0.445 = $4.555, which would typically round to $4.56 in practical terms due to cent rounding.

Given this calculation:
The math you initially provided ($4.55 after a $0.45 fee) doesn't align perfectly with Stripe's standard fee structure if we consider precise cent accounting. However, due to rounding or if there were slight variations in fee structure or if additional factors like currency conversion or specific account settings come into play, it could be seen as roughly consistent.

**Comment by DanielnetoDotCom** [comment]
in the payout you must agree you and your customers the cut for the payment gateway fees

usualy the site get a cut on the payout

each one has a different deal with the payment gateway

**Comment by DanielnetoDotCom** [comment]
this is something you must be clear on your agreement, 

I do not have it yet, but I the future I can can setup a wallet donnation cut so you will get a cut on every donnation to cover your fees

**Comment by JoshWho** [comment]
The fee should be included with the purchase of 5 dollars so when someone wants to add $5 to their wallet then it should add the fee and make the total on checkout with the stripe fee to make it correct.

**Comment by JoshWho** [comment]
If not set this way we will lose money in a 2.9% on every transaction

**Comment by DanielnetoDotCom** [comment]
For now you should discount that when you payout

**Comment by JoshWho** [comment]
> For now you should discount that when you payout

It is going to cause lots of confusions and people are not going to understand

**Comment by DanielnetoDotCom** [comment]
We do not have it yet, but it requires the Site to get a cut, or in the donation or in the payout. 

Youtube does that with super chat.

**Comment by JoshWho** [comment]
I can't just tell the customer there is a invisible fee and not have anything reflecting it.

**Comment by JoshWho** [comment]
If you pay for a super chat on Youtube like % dollars you get charged the 5 and their fee

**Comment by JoshWho** [comment]
From everything I have read up on it will be illegal to run it like this. We have to show there is a fee applied.

**Comment by DanielnetoDotCom** [comment]
Soon I will release an update that should let you create user groups with upload and livestream permissions.

**Comment by DanielnetoDotCom** [comment]
> From everything I have read up on it will be illegal to run it like this. We have to show there is a fee applied.
> 
> ## $5.00 wallet credit should show fee included charged
> $5.00
> $0.46 fee
> $5.46

can it be done in the payout?

that would be easier, because there are a lot different ways to generate income $ to the wallet.

**Comment by JoshWho** [comment]
I would think to just make it in the stripe plugin a auto 2.9% charge then when customer rings up 5.00 credit it will say how much it will cost them.

**Comment by JoshWho** [comment]
Or just add it to the pricing schema when they click purchase 5 it charges them in that transaction the fee but only reflect the correct wallet credit of $5

**Comment by DanielnetoDotCom** [comment]
Not a good idea, each location and payment gateway has a different fee, for example in Brazil the fees are different

also you may receive income from different ways, maybe a reward per view. 

I guess the most solid would be retreive the fee in the payout.

**Comment by JoshWho** [comment]
As long as it doesn't negative us and we don't need to manually subtract 2.9% every payout. That will be a lot of data work and will have errors here and there.

**Comment by DanielnetoDotCom** [comment]
No, lets say you have a 10% fee, I will request 5 USD withdraw, 
We can describe in the withdraw it he will receive only 4.50 USD, and the other 0.50 is regarding the 10% fee

In your site you can also request a higher fee, so you will also make money

For example YouTube takes a 30% cut of all Super Chat revenue

**Comment by JoshWho** [comment]
I c. This is awesome. Thank you @DanielnetoDotCom
