### ISSUE TITLE
Live link chats using the wrong chat

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9460]
https://ftjmedia.com/liveLink/28/accuweather

![download (11)](https://github.com/user-attachments/assets/f44b5ab7-402f-439b-b1fb-aa6b520a359b)

![bf0847f5-9411-4e34-89ea-cea7d8517563](https://github.com/user-attachments/assets/4c78ec03-55a2-4567-8321-72c2db92b43c)

**Comment by JoshWho** [comment]
Also the chat time stamps seems to be off as well

**Comment by DanielnetoDotCom** [comment]
Please update the Chat2 to version 16.2

**Comment by JoshWho** [comment]
> Please update the Chat2 to version 16.2

Fixed Thank you
