### ISSUE TITLE
What is this page Donation options in the My Account tab

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9465]
![1c8274ba-1da5-42ce-af5b-13b10f60ea27](https://github.com/user-attachments/assets/2f1c6f54-90d0-40d0-8587-009f4c577775)

What do all the switches do?

**Comment by JoshWho** [comment]
I was originally looking for a switch to turn off donations including wallet transfers on certain channels.

**Comment by JoshWho** [comment]
I was thinking that was the optio to do it but then seen all these options in the screenshot above.

**Comment by DanielnetoDotCom** [comment]
If I am not wrong, there you can set a custom behaivor dependeing on the value donated, a different text and icon

this will appear in the chat.

**Comment by JoshWho** [comment]
Ahhh so all of those is a different value I see. Interesting. Will play around with this. Thank you @DanielnetoDotCom
