### ISSUE TITLE
When someone donates to someone using the wallet in the chat?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9466]

**Comment by JoshWho** [comment]
Nevermind I see it
![c8a06204-c7bc-411f-8727-9bf5143bc5ad](https://github.com/user-attachments/assets/a05dab38-67ac-4b75-bd24-7aa07ec1e031)

**Comment by JoshWho** [comment]
How can we make that fancier? Like Animated GIF or something that says A tip was sent.

**Comment by JoshWho** [comment]
Like make it stand out more and instead of thanking it should just say 
![alert_donation](https://github.com/user-attachments/assets/617021bc-cd6b-4444-811f-12808ae3ec2e)


**JoshWho Sent you a $2.00 tip**

Don't use that gif but just showing something for example

**Comment by JoshWho** [comment]
Just need it to stand out more, Currently it just looks like I typed it. I want something bright flashy and with a sound to make others want to join in the fun.

**Comment by DanielnetoDotCom** [comment]
you probably can configure it here https://github.com/WWBN/AVideo/issues/9465
