### ISSUE TITLE
Need the Subscription button moved to left side of the search and also maybe customizable 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9467]
![1a03b339-159e-4de6-8809-ebbd878fd926](https://github.com/user-attachments/assets/a6874dbf-0270-4597-8b02-2fc45cee1426)

Need a away to be able to move this to the left side of the search and also some way to customize it. The checkmark Icon doesn't seem right for it. 

Would be better to just be able to use a custom button or something more adjustable. 

Can the GET FTJ PRO button be modified in any way, including the emoji symbol?

Also, can we change the text in the blue PLAN buttons & change the text in the WITHDRAW FUNDS page?

**Comment by JoshWho** [comment]
Also, can we change the text in the blue PLAN buttons & change the text in the WITHDRAW FUNDS page?

![download (12)](https://github.com/user-attachments/assets/36fb9844-f0b2-4887-95cb-140ddc8289c6)
 Just make it say Subscribe  instead of subscribe with credit card

**Comment by DanielnetoDotCom** [comment]
Sorry I cannot customize that deep

1. menu, cannot repositon that easy, but for a better customized button you can create your own plugin
2. cannot change  PLAN buttons
3. you cannot change the title on WITHDRAW FUNDS page
4. this update should remove the space between symbol and number
