### ISSUE TITLE
Users can upload videos without paying something is not right

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9468]
I just made a test account username is bobsmyuncle to try to replicate what this user did and I figured it out.

I seen this channel last night uploading yet they do not have a premium subscription. 

https://ftjmedia.com/channel/Ruski_Waffen

He knows the uploader path was /Encoder and was able to upload

![249af2bd-a8b9-4968-a130-588b7be8d565](https://github.com/user-attachments/assets/1ff637a0-42d1-4ca0-9b6a-9b7d0770a630)

Once he did that the My Videos button shows after the upload and now can put them into playlists

![c7867732-3f48-48c5-a2c8-58e293b7b2ca](https://github.com/user-attachments/assets/6fdabfcf-998d-4d44-9f09-7b6f71837c7a)

Then he creates Program/Playlist to get it to show up on his channel

![0514e808-6c93-464e-8ac4-e921a985131c](https://github.com/user-attachments/assets/3fbf40bb-b7f8-4a44-834f-eacb41a7b298)

**Comment by DanielnetoDotCom** [comment]
What exactly video did he upload?

**Comment by JoshWho** [comment]
All that you see on his channel

**Comment by DanielnetoDotCom** [comment]
I found the issue, sorry for that

**Comment by JoshWho** [comment]
> I found the issue, sorry for that

All patched?

**Comment by DanielnetoDotCom** [comment]
yes, also check this

![image](https://github.com/user-attachments/assets/0b0b291e-23c2-40a9-840f-db0cf7ef716f)

**Comment by JoshWho** [comment]
> yes, also check this
> 
> ![image](https://private-user-images.githubusercontent.com/18009293/373997014-0b0b291e-23c2-40a9-840f-db0cf7ef716f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNjUwMjYsIm5iZiI6MTcyODI2NDcyNiwicGF0aCI6Ii8xODAwOTI5My8zNzM5OTcwMTQtMGIwYjI5MWUtMjNjMi00MGE5LTg0MGYtZGIwY2Y3ZWY3MTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDAxMzIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYWRhN2NkMjJhNmUxMGIwZTM4NmE0ZmU1YzExZTZjMzBjMmMwN2YwYmMyMDdhZjcyYzUyMmM1OTVjODczNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RdD2Z3-843bB8gn9qzxg9CJUn5akFj03cO0ZBWDcB2k)

Excellent

**Comment by JoshWho** [comment]
Thank you so much @DanielnetoDotCom Super awesome.
