### ISSUE TITLE
Redirect Live after stream didn't work

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9475]
Is something not set right?

Stream https://ftjmedia.com/live/0/WhiteRabbitRadio/1

First ended here
![Live-·-FTJ-Media-10-07-2024_06_02_PM](https://github.com/user-attachments/assets/001178cc-5390-4c86-be19-132985198e9a)

He has this set
![Live-·-FTJ-Media-10-07-2024_06_05_PM](https://github.com/user-attachments/assets/f8f8e329-5281-4155-9a2d-c169d9cb4e50)

![e5b63780-cd45-4b94-a353-e1739d127fa1](https://github.com/user-attachments/assets/dad928c9-2bb6-4011-88b4-2bb66933dad6)

**Comment by JoshWho** [comment]
![a41a41d3-49c0-4d09-b72d-dfc4562f5d8f](https://github.com/user-attachments/assets/763de89d-664c-4896-8945-ad39aa7c58ca)

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Live-Plugin#important

**Comment by JoshWho** [comment]
He did have that set. I was just showing from my admin login

**Comment by JoshWho** [comment]
and there should be a default if they choose not to select anything make it redirect to the home page.

**Comment by DanielnetoDotCom** [comment]
No need to forget the ULR, If you do not click on the button the set URL will not be redirected, there is no need to clean it.
but you can add a different URL
If you want to go to the homepage, put the homepage there

**Comment by DanielnetoDotCom** [comment]
> set. I was just showing from my admin login

Each user must set his own URL, this is saved in a cookie (that browser only) not in the database

**Comment by JoshWho** [comment]
Why not default it to the homepage for everyone if not set. The whole point is Dave didn't want it to stay on the page that just shows a spinning player.

**Comment by DanielnetoDotCom** [comment]
But it still requires the live owner to click on the button.

if no click it will not be redirected

**Comment by JoshWho** [comment]
Can it be if no click then default to the home page. That is what Dave was looking for, he didn't want it to stay on the same page with the spinning circle on the player. Just like how the scheduled live links end it does it correctly.

**Comment by DanielnetoDotCom** [comment]
Even if the default is the home page it will still need the live owner to click in the button

We talked about it

**Comment by JoshWho** [comment]
Why can't it be when it see's the stream has disconnected? Or when they set a schedule for ending

**Comment by JoshWho** [comment]
Like make it wait for reconnect 120 seconds and if never reconnects drop it.

**Comment by JoshWho** [comment]
I am not sure how Rumble and Youtube does it but it doesn't keep you on the page when it is over it goes to something else once they disconnect.

**Comment by DanielnetoDotCom** [comment]
We talked about it already and we all agreed.  even before develop the feature. 

right now I cannot guarantee I will not redirect the user while he is watching. 

also do it now requires extra development.

**Comment by DanielnetoDotCom** [comment]
@JoshWho this new update may autoredirect after the live ends.  but the issues still

Make sure you select and add a new URL, the URLs and messages now are saved on the database not in a cookie anymore

> **DVR Feature:** Our live streams have a DVR function, allowing users to rewind and watch from an earlier point. If someone rewinds 30 minutes, for example, they might still be watching even after the live stream has officially ended. Auto-refreshing in this case could disrupt their viewing experience.
> **Streamer Disconnections:** If the streamer loses connection temporarily, the page would refresh, causing confusion for viewers who might think the stream has ended when it’s just a temporary issue.
