### ISSUE TITLE
How to force streamers using my rtmp server running nginx to only use 720p

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9482]
Answer
To ensure that streamers using your RTMP server (which is running on Nginx) can only stream in 720p, you'll need to configure your Nginx setup to enforce this resolution. Here's how you can do that:

1. Edit Nginx Configuration
First, you need to edit your nginx.conf or the specific configuration file for your RTMP module. The typical location for this file could be /usr/local/nginx/conf/nginx.conf or /etc/nginx/nginx.conf, depending on your installation.

Add or modify the application block in the RTMP module section to include settings for transcoding:

```
rtmp {
    server {
        listen 1935; # RTMP default port
        chunk_size 4096;

        application live {
            live on;
            record off;

            # Transcoding to ensure 720p output
            exec ffmpeg -i rtmp://localhost/$app/$name
                -c:v libx264 -profile:v main -preset medium -b:v 1500k -maxrate 1500k -bufsize 3000k -vf "scale=-2:720"
                -c:a aac -b:a 128k -f flv rtmp://localhost/show/$name;

            push rtmp://localhost/show/$name; # Push the transcoded stream to another application or server if needed
        }

        application show {
            live on;
            # Here you can add more settings for viewers, like HLS, DASH, etc.
        }
    }
}
```

2. Explanation of Configuration:
exec ffmpeg: This command uses ffmpeg to pull the incoming stream, transcode it, and then push it back to Nginx. 
-i rtmp://localhost/$app/$name: Input stream from the live application.
-c:v libx264: Specifies the video codec for encoding.
-profile:v main: Sets the encoding profile.
-preset medium: Balancing between encoding speed and compression efficiency.
-b:v 1500k: Sets the video bitrate, adjust as necessary but this works for 720p.
-maxrate 1500k -bufsize 3000k: These control the bitrate tolerance.
-vf "scale=-2:720": This scales the video to 720p height, maintaining aspect ratio. -2 means the width will be calculated automatically to keep the aspect ratio.
-c:a aac: Audio codec for the stream.
-b:a 128k: Audio bitrate.
-f flv rtmp://localhost/show/$name: Format and destination of the transcoded stream.
push: This will push the transcoded stream. If you're not pushing to another server or application, you might not need this, but it's useful for distributing the stream further.

3. Restart or Reload Nginx
After modifying the configuration:

```
sudo nginx -t # Test the configuration for errors
sudo systemctl reload nginx # Or restart if reload doesn't apply changes
```

4. Considerations:
Performance: Transcoding in real-time can be CPU-intensive. Make sure your server has enough processing power, or consider hardware acceleration if available.
Quality vs. Bitrate: The bitrate settings (1500k) are an example. You might need to adjust this based on your quality expectations and network conditions.
Legal and Ethical: Ensure you have the rights to transcode user content, as some streamers might object to their stream being altered.

This setup forces all incoming streams to be transcoded to 720p before they are redistributed or saved, effectively limiting your streamers to this resolution.

-----------
Let me know what u think about this @DanielnetoDotCom no rush.

**Comment by JoshWho** [comment]
and this forces the 720p 2 mpb a second?

Answer
The configuration provided earlier sets some parameters for bitrate but doesn't strictly enforce a 2 Mbps limit directly. To ensure the stream is at 720p and around 2 Mbps, you'll need to adjust and specify the bitrate settings more precisely. Here's how you can modify the ffmpeg command to enforce a bitrate closer to 2 Mbps:
```

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            record off;

            exec ffmpeg -i rtmp://localhost/$app/$name
                -c:v libx264 -profile:v main -preset medium -b:v 2000k -maxrate 2000k -bufsize 4000k
                -vf "scale=-2:720"
                -c:a aac -b:a 128k -f flv rtmp://localhost/show/$name;

            push rtmp://localhost/show/$name;
        }

        application show {
            live on;
        }
    }
}
```

Key Adjustments:
-b:v 2000k: This sets the target bitrate to 2000 kbps (2 Mbps). 
-maxrate 2000k: This ensures that the maximum bitrate does not exceed 2000 kbps, which helps in maintaining the quality close to what you desire.
-bufsize 4000k: The buffer size is set to twice the maxrate. This allows for some flexibility in bitrate adjustment over time, which can help in maintaining quality with varying scenes.

Additional Notes:
Resolution and Bitrate: The scale=-2:720 ensures that the height is 720 pixels, and the width is adjusted automatically to maintain the aspect ratio. The bitrate settings here are targeted at providing good quality for 720p at around 2 Mbps. However, depending on the content (e.g., high motion video vs. static), you might need to fine-tune these numbers for optimal quality.
Quality Considerations: 
Preset: The medium preset provides a balance between encoding speed and compression efficiency. If your server has more processing power, you might experiment with slow or slower for better compression at the cost of more CPU usage.
Profile: main is generally good for compatibility; however, if all your clients support it, consider high for better compression at the same bitrate.
Testing: After implementation, it's crucial to test with various types of content to ensure that the quality meets expectations at the specified bitrate. You might need to adjust the bitrate or other parameters like the buffer size based on real-world performance.
Monitoring: Use tools or scripts to monitor the actual bitrate of outgoing streams to ensure your settings are working as intended.

This setup should force the streams to 720p with a bitrate close to 2 Mbps, adjusting dynamically within the limits you've set to maintain quality.

**Comment by JoshWho** [comment]
Is this the same thing that will cost cpu?

**Comment by DanielnetoDotCom** [comment]
yes, the ffmpeg will consume your server CPU

it is the same as use adaptive https://github.com/WWBN/AVideo/wiki/Adaptive-Bitrates-on-Livestream

also instead of making anything different, you should use adaptive and will cost you CPU anyway.
