### ISSUE TITLE
Issues after last git pull

### ISSUE THREAD

**Issue by milehighkaraoke** [WWBN/AVideo#9483]
@DanielnetoDotCom 
After the latest pull i get a white screen on the mobile app when trying to launch video. If you scroll video a little off of the main screen  it will appear. Also lots of errors 
![Screenshot_20241010_042116_Chrome](https://github.com/user-attachments/assets/d05f8c0f-6a0e-4d28-a07a-fcf48ca7a2ed)
![Screenshot_20241010_041457_Chrome](https://github.com/user-attachments/assets/06a801e8-eb1f-443e-b649-a629c28e41d2)
![Screenshot_20241010_041450_Chrome](https://github.com/user-attachments/assets/1f576b10-30d8-40b2-99c8-8121162701be)

**Comment by DanielnetoDotCom** [comment]
Not sure, those logs are not enough, you should use command line to get the logs

but check your disk space, if your disk is not full

**Comment by milehighkaraoke** [comment]
Fixed by deleting all internet data from all browser applications under settings
