### ISSUE TITLE
[Subscription Plugin] plugin/PayPalYPT/ipn.php = IPN Fail

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9487]
@DanielnetoDotCom Danny, I'm starting some tests for Subscription Plugin.
I followed the steps, but when I get to Configure PayPal IPN, I can't move forward:
![image](https://github.com/user-attachments/assets/a8d0407f-374a-4d0c-b357-f4e3fbc205e0)

It shows the error:
`IPN Fail`

Can you tell me what's going on?

**Comment by DanielnetoDotCom** [comment]
IPN is made for paypal, you cannot use it directly

**Comment by gbrn** [comment]
So I didn't understand the instructions... it says "Enable your IPN".
This tells me that I should enter the link to enable the IPN. In fact, I have to go to Paypal and enter the link.
Ok, I got it here.
