### ISSUE TITLE
Anyway to hide the Language selcetion?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9488]
How can I hide the Language selector in the top nav?

![FTJ-Media-10-11-2024_07_45_PM](https://github.com/user-attachments/assets/76144746-97aa-4c30-ad91-25ff66d24a06)

**Comment by JoshWho** [comment]
If can't hide it, is there a way to reorder the languages by Alphabet?

**Comment by JacekLange** [comment]
> How can I hide the Language selector in the top nav?
> 
> ![FTJ-Media-10-11-2024_07_45_PM](https://private-user-images.githubusercontent.com/39392449/375911241-76144746-97aa-4c30-ad91-25ff66d24a06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjMyNjEsIm5iZiI6MTcyODcyMjk2MSwicGF0aCI6Ii8zOTM5MjQ0OS8zNzU5MTEyNDEtNzYxNDQ3NDYtOTdhYS00YzMwLWFkOTEtMjVmZjY2ZDI0YTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA4NDkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTYxNTM4ZmRiNTgzMzM3YzI3YmM0OGQyNTE1ZjQ1MjM2MzBkZWU2NDBhYjA3YzY2Y2I5ZTk3NTY2N2M1OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jOofnPcLxVg_Uy9bkoji_kUPqJoAyvIyGr3glU60448)

Add to custom css:

`<style>
.navbar-lang-btn {
 display: none;
}
</style>`

**Comment by JoshWho** [comment]
> > How can I hide the Language selector in the top nav?
> > ![FTJ-Media-10-11-2024_07_45_PM](https://private-user-images.githubusercontent.com/39392449/375911241-76144746-97aa-4c30-ad91-25ff66d24a06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjMyNjEsIm5iZiI6MTcyODcyMjk2MSwicGF0aCI6Ii8zOTM5MjQ0OS8zNzU5MTEyNDEtNzYxNDQ3NDYtOTdhYS00YzMwLWFkOTEtMjVmZjY2ZDI0YTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA4NDkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTYxNTM4ZmRiNTgzMzM3YzI3YmM0OGQyNTE1ZjQ1MjM2MzBkZWU2NDBhYjA3YzY2Y2I5ZTk3NTY2N2M1OTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jOofnPcLxVg_Uy9bkoji_kUPqJoAyvIyGr3glU60448)
> 
> Add to custom css:
> 
> `<style> .navbar-lang-btn { display: none; } </style>`

Perfect. That did the trick. Thank you.
