### ISSUE TITLE
Socket server runs up the cpu to max sometimes have to restart socket server to make normal again.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9490]
Is there any way to auto restart socket server if it is using too much cpu?

restarting it makes it go back to normal.

**Comment by DanielnetoDotCom** [comment]
This update will quickly restart the socket every day.

but you can also restart it in the socker restart button

![image](https://github.com/user-attachments/assets/b5204599-66a3-4d14-a6c2-610dc208fc52)


or manually https://github.com/WWBN/AVideo/wiki/Socket-Plugin#restart-socket

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom
