### ISSUE TITLE
Bulk yt embedder should use the original dates the videos where uploaded on

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9491]
Should be a way on the bulk embed to make the videos all keep their original dates. This helps space things out in the order listing.

**Comment by DanielnetoDotCom** [comment]
This update should do the trick, also there is an option (useOriginalYoutubeDate) to disable and use the date when the video was embeded

**Comment by JoshWho** [comment]
> This update should do the trick, also there is an option (useOriginalYoutubeDate) to disable and use the date when the video was embeded

Super sweet. Thankyou @DanielnetoDotCom

**Comment by JoshWho** [comment]
Weird I can't make a git pull for t says all up to date.

**Comment by DanielnetoDotCom** [comment]
Yes I did update you

**Comment by JoshWho** [comment]
Ahhh Thank you
