### ISSUE TITLE
What happened to the random video row in Gallery called Recomended.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9506]
I was going to enable that row in the middle our our home page and no longer see it as a option in Gallery.

We didn't want to go off suggestions because it would be a endless battle of repetitive having to change them all the time. I thought the random Recommended one was awesome.

**Comment by DanielnetoDotCom** [comment]
I guess you want the suggested, and add a custom title as you want

![image](https://github.com/user-attachments/assets/f2aed3fc-26b9-4061-8fd6-c54abdb2de58)

**Comment by JoshWho** [comment]
Isn't that the row for only Star Suggested. I thought there was one called Recommended and it was just random vids.

**Comment by DanielnetoDotCom** [comment]
Maybe you are looking for Trending, Trending is randoom
