### ISSUE TITLE
Live search missing thumbs

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9507]
![f037a0e1-f5d6-419c-ab0e-4d1ea268d672](https://github.com/user-attachments/assets/668df130-826d-4ef2-b9c7-b5b2f02d3d5a)

Here is a link to that first one https://ftjmedia.com/videos/v_241014135429_vb4a0/v_241014135429_vb4a0_thumbsV2_jpg.webp

Gives a 404

**Comment by DanielnetoDotCom** [comment]
Please run this update, wait 1 minute and try again.

**Comment by JoshWho** [comment]
It now has the thumbnail placeholder but no thumb

![d28ecc7f-2534-4247-8068-50a94fba09be](https://github.com/user-attachments/assets/a9c8212d-c993-4343-87f4-e84c2c41cdbe)

https://ftjmedia.com/videos/v_241014135429_vb4a0/v_241014135429_vb4a0_thumbsV2_jpg.webp

**Comment by JoshWho** [comment]
Nevermind I think it is working now. Had to upload the new plugin.

**Comment by JoshWho** [comment]
Is it building the thumbnails?
![138be26b-0a04-4bdd-ab93-174ecba9ed42](https://github.com/user-attachments/assets/e8120285-f8cd-40ee-af1c-6f97e6bdeb6a)
