### ISSUE TITLE
[ERROR] external_referrer include_config.php

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9510]
@DanielnetoDotCom Danny, 117 errors PHP

![image](https://github.com/user-attachments/assets/51793ec6-9c56-490c-a2e6-37a6f1e2b434)

`[14-Oct-2024 23:01:20 UTC] AVideoLog::ERROR:      external_referrer changed[{"file":"\/var\/www\/html\/AVideo\/objects\/include_config.php","line":161,"function":"storeAndGetExternalReferrer","args":[]},{"file":"\/var\/www\/html\/AVideo\/videos\/configuration.php","line":49,"args":["\/var\/www\/html\/AVideo\/objects\/include_config.php"],"function":"require_once"},{"file":"\/var\/www\/html\/AVideo\/view\/index.php","line":7,"args":["\/var\/www\/html\/AVideo\/videos\/configuration.php"],"function":"require_once"}] SCRIPT_NAME: /view/index.php`

**Comment by DanielnetoDotCom** [comment]
Sorry, this not supposed to be flagged as an error, it is fixed now.
