### ISSUE TITLE
[YPTWallet Plugin] Button not display settings

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9511]
@DanielnetoDotCom Danny, I noticed that the Settings button does not display anything related to the wallet. Please check this.

[Configuração-·-CNETV.webm](https://github.com/user-attachments/assets/ab6e5059-1fba-49b9-93c4-03e1693c5aeb)

**Comment by DanielnetoDotCom** [comment]
This update will give you more info why it is blank

**Comment by DanielnetoDotCom** [comment]
Did you make a git pull?

**Comment by gbrn** [comment]
Ok, now the information is being displayed. Thanks.
![image](https://github.com/user-attachments/assets/e8c56670-6ca2-4133-a478-1cb91fa952df)
