### ISSUE TITLE
add bulk embedder to Groups permision

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9525]
This would make it easier to manage the automated accounts. 

I made a group called automated for these channels that pulls feeds and need them to be able to access the bulk embed feature without being a admin please.

**Comment by DanielnetoDotCom** [comment]
Make a git pull and check this

![image](https://github.com/user-attachments/assets/fd2c29fe-06f7-428f-84df-1861d56f13ad)

**Comment by JoshWho** [comment]
> Make a git pull and check this
> 
> ![image](https://private-user-images.githubusercontent.com/18009293/378467943-fd2c29fe-06f7-428f-84df-1861d56f13ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MzczOTUsIm5iZiI6MTcyOTYzNzA5NSwicGF0aCI6Ii8xODAwOTI5My8zNzg0Njc5NDMtZmQyYzI5ZmUtMDZmNy00MjhmLTg0ZGYtMTg2MWQ1NmYxM2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDIyNDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYzg4YWRjZDUxM2E5MWNmMjAxNDM2NThlNjM5ZjcyMTE3N2E1MzdmNGNlZGYwNDcyNjI4MDk3MWJhMTUyYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v1zSNvCm4vff7HSVPhfjoiFVIWkvF5siJrpraup1zj4)

Thank you just seen this. Now it will be easy to update these channels. Thanks again
