### ISSUE TITLE
We have view count publicly disabled but it is now showing on the channels on home page with Gallery.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9533]
![0345598f-0f4c-461b-8c13-e812d18a963a](https://github.com/user-attachments/assets/42d407b4-c959-4094-b4e8-13c1b7c8c738)

Now I can make a css change that will hide this but it also hides other things seems to be global, how can we just not display it?

![8abc3858-6dd8-4a8d-9c4b-18fc787ffa99](https://github.com/user-attachments/assets/f4d37176-c82e-4d0e-8788-04e3b349f3c7)

**Comment by DanielnetoDotCom** [comment]
This update should resolve that.
