### ISSUE TITLE
Donate messages from the person donating. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9536]
A way a user can also attach a message in the chat with their donation.

**Comment by JoshWho** [comment]
I am guessing they want to be able to do it in the chat
![f034e8ca-abb3-4d76-8b12-a1d3063956a8](https://github.com/user-attachments/assets/e111d9a9-6c46-43a4-b24e-d893c730e52e)

Like add a message box under the donate amount where they can add a brief message

They was also asking for like a sound effect when it happens also.

**Comment by DanielnetoDotCom** [comment]
And this message will be displayed and highlited to everyone like superchat?

**Comment by JoshWho** [comment]
> And this message will be displayed and highlighted to everyone like superchat?

Yes correct

**Comment by DanielnetoDotCom** [comment]
Tomorrow I will send an update, it will also require a new Chat plugin, version 17+

**Comment by JoshWho** [comment]
> Tomorrow I will send an update, it will also require a new Chat plugin, version 17+

Super awesome looking forward to it.

**Comment by DanielnetoDotCom** [comment]
You are up to date now, please check.

**Comment by JoshWho** [comment]
![Live-·-FTJ-Media-10-24-2024_11_58_PM](https://github.com/user-attachments/assets/d48038cb-867c-4090-9fb0-63a975b7ad5e)

**Comment by JoshWho** [comment]
Other viewer guest or logged in sees it like this. 
![fdac96d4-1017-4ffd-89d9-35462b236049](https://github.com/user-attachments/assets/a7a3921c-56d8-40f9-842c-72890c41eabc)
