### ISSUE TITLE
Make Lobby on Jitsi a default and also everyone follows me

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9537]
Is it possible to have these 2 options made default?

I found the lobby option today and am very impressed, it is exactly how streamyard works. How can that be enabled by default so all new joining members to conference wait in the lobby until approved?

![cf2bd79c-890a-472a-adcc-50ce25f4c53a](https://github.com/user-attachments/assets/bccae003-da79-47cb-81ec-ec8049947ef7)

and Everyone follows me for moderator admin

![35218611-b43a-42bd-9487-795840abfab3](https://github.com/user-attachments/assets/13680042-e85a-44aa-9e16-6b45cfec81b5)

**Comment by DanielnetoDotCom** [comment]
Lobby is on by default, 

the "Everyone follows me" is not possible for now

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom This is great. Love it
