### ISSUE TITLE
Bulk embedder is not keeping the original dates again

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9538]
Just realized all the embeds I did last night all have the same time stamps. Wish there was a way to back track and redo them.

**Comment by JoshWho** [comment]
![Uploading b6c0687e-ed5b-429e-87b5-4462c22312eb.png…]()

**Comment by JoshWho** [comment]
![b6c0687e-ed5b-429e-87b5-4462c22312eb](https://github.com/user-attachments/assets/da6cd8b6-2144-4eda-9748-f26e3ce82314)

**Comment by DanielnetoDotCom** [comment]
In the BulkEmbed parameters, do you have the option useOriginalYoutubeDate checked?

Is this user admin?

I guess only admin can do change the creation date, but I will make an update to allow BulkEmbed change it too.

**Comment by JoshWho** [comment]
> In the BulkEmbed parameters, do you have the option useOriginalYoutubeDate checked?
> 
> Is this user admin?
> 
> I guess only admin can do change the creation date, but I will make an update to allow BulkEmbed change it too.

I bet that is exactly what it was. I wasn't using user admin. So this new update now works for the automated group I made now that is not admin?

**Comment by DanielnetoDotCom** [comment]
Yes now it should work with regular users too

**Comment by JoshWho** [comment]
> Yes now it should work with regular users too

Thank you.

**Comment by JoshWho** [comment]
![da5f4447-366c-49ff-b811-480481f919ae](https://github.com/user-attachments/assets/271ce7b5-a72f-458a-91b0-4ca215f4e0d1)

Still not using the original dates.

**Comment by DanielnetoDotCom** [comment]
I am sorry, you are right

there is still a limit for regular users

but this last update should resolve that limit
