### ISSUE TITLE
Odyssey links break in the chat

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9541]
![0b1d8b46-d335-4055-9647-382ee189b105](https://github.com/user-attachments/assets/7448006e-75b1-4d24-9cef-4c31f0c60778)

the @ sign seems to break it but that is their only format. I tried using the Bitly plugin hoping it would link shorten in but seems to not do that like I was thinking.

**Comment by DanielnetoDotCom** [comment]
This update should fix that

**Comment by JoshWho** [comment]
Just tested it still breaks 
![127b7149-04fc-420b-9fcb-8c2967f919d3](https://github.com/user-attachments/assets/1c55d73f-b45a-484f-8b8e-ede8390a036e)

**Comment by DanielnetoDotCom** [comment]
It is working here


![chrome-capture-2024-9-28](https://github.com/user-attachments/assets/5cb9fe87-6af5-4657-8104-a565a99d76b2)

maybe you are looking for something else

**Comment by JoshWho** [comment]
No it is a link from the website odyssey that is being broke. Their links have a @ sign in it and look like this https://odysee.com/@KingDDDuke1080p:a/tihydpre2r1080p:f

When you try to post that in the chat the link gets broken up at the @ sign

![127b7149-04fc-420b-9fcb-8c2967f919d3](https://github.com/user-attachments/assets/8b65e9e0-5ef3-4eea-a99c-3542df3751f0)

**Comment by DanielnetoDotCom** [comment]
I see, please try this update the

**Comment by JoshWho** [comment]
> I see, please try this update the

That did the trick. Thank you Daniel.
