### ISSUE TITLE
This 1 user when he goes live it always shows zero but when you click it you see the real count.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9542]
username Flood

![download (7)](https://github.com/user-attachments/assets/6545a5e9-6641-4fe1-a24b-8c95a10ef1b8)

![6ab289b1-9538-4a3f-9b97-a8cfef3474a9](https://github.com/user-attachments/assets/c0cbf8cd-d81b-4a59-935d-fab4e445f85a)

**Comment by DanielnetoDotCom** [comment]
Please check or reset his stream key

**Comment by JoshWho** [comment]
I told him to change his key after he is done streaming.

**Comment by JoshWho** [comment]
It has something to do with scheduled streams. He did a stream today unscheduled and it shows the user count. Stream he did yesterday showed zero and he changed his stream key.

**Comment by DanielnetoDotCom** [comment]
I see, do you I just tested a scheduled stream here and it works fine

maybe he setup something different, unlisted, password, etc?

**Comment by DanielnetoDotCom** [comment]
Also I can see he is live now and the count is working

But I also can see it is not a scheduled live, I am not sure yet

![image](https://github.com/user-attachments/assets/2b011b8a-8c3b-4a87-ac6f-227f0dc301e3)

**Comment by JoshWho** [comment]
Correct he did his streamtoday not using the schedule and now it works normal, which is why I think the schedule has something to do with it.
