### ISSUE TITLE
UserConnections plugin

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#9554]
Hi Daniel, how are you?

This is the message I get when I run this new plugin
(The message is received in the tab: My account When I open it)

![image](https://github.com/user-attachments/assets/6c47e4ab-73fa-4302-8e67-e1ab7df07f2b)

*The other plugins needed to run the UserConnections plugin As requested in the plug-in activation instructions
 Chat and meeting are enabled 
* Sending the membership request and the notification are working in the plugin

I am attaching a screenshot image where you can see all the necessary details
1) The online users
2) That the membership application has been approved
3) the option to make calls is activated

* in the new menu of the UserConnections plugin you can see Failed to load connections

![image](https://github.com/user-attachments/assets/eb0e9df2-1d1e-4191-9221-7bf554543df1)

As usual, many thanks for the support

**Comment by DanielnetoDotCom** [comment]
First make sure all your plugins are up to date and all the tables installed

if it persists check your avideo logs

**Comment by eitanwa** [comment]
Yes, the chat plugin was not updated
It seems to be fine (after the update)
excellent thanks
