### ISSUE TITLE
Mass Moving Videos to a Certain Category  - similiar #6934

### ISSUE THREAD

**Issue by stankov19** [WWBN/AVideo#9555]
Hi Danielo I have a problem with mass moving videos, after yesterday update script.
In tab "my videos" disapeared sub tab (categories) which allows to mass changing video category.
it is a bug ? or this function are be delete?
on below creen 
![screen 2024-10-30 145551](https://github.com/user-attachments/assets/83afb98c-134c-47e9-8258-deae4e470b3a)
![screen 2024-10-30 145658](https://github.com/user-attachments/assets/b9ece8f0-de89-4900-9e13-93de8465c46f)
![image](https://github.com/user-attachments/assets/65abc46b-92e1-461a-a2fc-2688ae4437d3)

**Comment by DanielnetoDotCom** [comment]
You are right, it was missed.

please check this update

**Comment by stankov19** [comment]
Wes problem was solved.
very thx 
issue to close.
