### ISSUE TITLE
Mass video Import grab from Youtube Bitchute Rumble etc

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9560]
Need some kind of way to grab videos from external channels to import to our platform. 

I know I can do it with Youtube channel playlist but was wondering if a way for Bitchute and other platforms?

Or maybe some kind of link list grabber for all the videos and then import that.

**Comment by JoshWho** [comment]
Als needs to be a way to mass change the video owner to a different owner.   I am bulk importing videos using one account so it is not sending notifications for every video out on the channel I want it to be on.

**Comment by DanielnetoDotCom** [comment]
Here are 2 things, 

1. bulk import
1.1 first the platforms must provide an api for searching
1.2 it it does provide the API, it will require some development and this is not in my road map at the moment. if you sponsor a feature I can estimate an ETA

2. bulk change owner, I do not have this option yet, but you can do it direcly in the database (if you know how to do)
