### ISSUE TITLE
How can we embed a Live Link like this instead of the normal embed?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9561]
https://rumble.com/c/RSBN/live this is the static link for RSBN with every live stream. How can we add this to the live links?

**Comment by DanielnetoDotCom** [comment]
did you try to add this https://rumble.com/embed/v5j9qbz/?pub=4 ?

**Comment by JoshWho** [comment]
I was trying to keep it static so when they go live again it will be the next live stream. All the lives play under the 1 static url.
