### ISSUE TITLE
I see a lot of new videos that never went to the storage for some reason. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9576]
![a3c33fe3-cad7-4f91-8e01-5cd86270bbc9](https://github.com/user-attachments/assets/80b51777-1f2e-43d8-a706-dbef5191d5ec)

The last video I just uploaded transferred.

**Comment by DanielnetoDotCom** [comment]
I did checked your site and all seems to be good.

any video exactly?

**Comment by JoshWho** [comment]
I am just going off the thing that is orange and says it is in the storage while other videos do not show that label. 
![1c365e8a-24cd-4aa1-abc8-22cc30e5a022](https://github.com/user-attachments/assets/0ccbc5a7-c08e-476f-b266-db8617a1f882)

**Comment by DanielnetoDotCom** [comment]
wait the next day, the sync run once a day
