### ISSUE TITLE
Live streams keep buffering not sure why or what changed.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9582]
Lately the last few days live streams have been really buffering bad. Not sure why or what would cause it. 

Is it not going through the cdn?

**Comment by DanielnetoDotCom** [comment]
It is thru the. CDN but make sure you are streaming in 720p

**Comment by JoshWho** [comment]
Is there a way we can make it like a message in the Live Dashboard that says, "Make sure to use 720p" somewhere. I will add it to our FAQ as well.

**Comment by DanielnetoDotCom** [comment]
Done

**Comment by DanielnetoDotCom** [comment]
![chrome-capture-2024-10-12](https://github.com/user-attachments/assets/3c85b3c0-531f-44f0-a2f2-0ca159be0596)
