### ISSUE TITLE
Do you have a map of all ad placement spots?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9583]
A diagram that shows where and what each ad placement is titled.

I am trying to figure out how to get a ad under the video player on video play page and not sure which one that is. 

![53e6c1a6-500d-47ad-a1d0-ed5b0717985f](https://github.com/user-attachments/assets/3df97628-6145-4040-937e-c81ece8acc7c)

**Comment by DanielnetoDotCom** [comment]
Get this update, in any page pass the variable AdsDebug=1 in the URL

and you will see something like this 

![image](https://github.com/user-attachments/assets/30fc1bf5-d84b-48e8-b934-f9a6b6fab3a1)

**Comment by JoshWho** [comment]
> Get this update, in any page pass the variable AdsDebug=1 in the URL
> 
> and you will see something like this
> 
> ![image](https://private-user-images.githubusercontent.com/18009293/385461833-30fc1bf5-d84b-48e8-b934-f9a6b6fab3a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NDUxODgsIm5iZiI6MTczMTQ0NDg4OCwicGF0aCI6Ii8xODAwOTI5My8zODU0NjE4MzMtMzBmYzFiZjUtZDg0Yi00OGU4LWI5MzQtZjlhNmI2ZmFiM2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDIwNTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwODdiOWIzNTQyZTk1MjRiMWVlNzgxNDUyYjEwZDM5MjQ3Mzk0MjUwMzE0ZDgwY2ZhMzM3YjhjOWY5Y2E3MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GMrGGOBbp7Nnde-b_tZ9r9Dm_oPdIGwe40UNFWTgUH0)

Thank you

**Comment by JoshWho** [comment]
Does the ad big video work on Live stream page too?

**Comment by JoshWho** [comment]
I can't figure out to show a ad on the live stream page.

**Comment by JoshWho** [comment]
Leaderboard Top2 is not showing on the video page

**Comment by JoshWho** [comment]
![a030e2d7-bbc6-4d40-9893-8d9083541e08](https://github.com/user-attachments/assets/bfa24cf8-43e4-4756-b979-3918305e18cc)

**Comment by JoshWho** [comment]
Also the Square add is not showing on the video page top right as well for the Rectangle ad space.

**Comment by JoshWho** [comment]
Viewing the page source of a video page in incognito mode looking for my ad code I see none.

**Comment by DanielnetoDotCom** [comment]
I found something and I sent you the updates

**Comment by JoshWho** [comment]
> I found something and I sent you the updates

Thank you works perfect now.
