### ISSUE TITLE
Video resync issue again?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9590]
Video https://ftjmedia.com/channel/GiuseppeVafanculo/video/.PA9SAewt9XVYdS9-jfC8NA/the-sane-asylum-based-hump-day-284---13nov24-on-13-nov-24-18-00-18

Not playing just spins

Says it transferred to storage and has time stamps.

**Comment by DanielnetoDotCom** [comment]
Hold on

**Comment by JoshWho** [comment]
Find anything?

**Comment by DanielnetoDotCom** [comment]
I have no idea why your video does not have the encryption key file (I have never seen that) that is why it is not playing

did you delete or maybe some security protocoll delete the file?

I did find anything in the logs

Is it a recorder livestream?

I found 4 recorded lives from today in your server, I sent them again to encode, onve it is done delete the duplicated ones and check it the video works

![image](https://github.com/user-attachments/assets/d6de15e1-98fc-41a6-a744-a6b52a64c4c7)


I also set your encoder to not delete the files after encode so I can detect where the issue comes from.

**Comment by JoshWho** [comment]
Yes it is a recorded live stream

**Comment by DanielnetoDotCom** [comment]
Once the video you want is encoded, please test if it has the key. 
again, I have never seen that happen, something may delete the file

**Comment by JoshWho** [comment]
Looks like the one that is broken was ran through https://encoder1.wwbn.net/

**Comment by JoshWho** [comment]
I do not think your encoder is set like mine. Mine is set with this for hls

`ffmpeg -i input -c:v libx264 -pix_fmt yuv420p -vf "scale=-2:{$resolution}" -r 24 -g 48 -keyint_min 48 -sc_threshold 0 -bf 2 -b_strategy 1 -minrate {$minrate}k -crf 23 -maxrate {$maxrate}k -bufsize {$bufsize}k -c:a aac -b:a {$audioBitrate}k -threads 4 -f hls -hls_time 6 -hls_list_size 60 -hls_flags +independent_segments+program_date_time -hls_segment_filename "res{$resolution}/segment_%03d.ts" -hls_key_info_file {$destinationFile}keyinfo {$destinationFile}res{$resolution}/index.m3u8`

**Comment by DanielnetoDotCom** [comment]
Also no records in the encoder 1 server, I did checked it

**Comment by DanielnetoDotCom** [comment]
> I do not think your encoder is set like mine. Mine is set with this for hls
> 
> `ffmpeg -i input -c:v libx264 -pix_fmt yuv420p -vf "scale=-2:{$resolution}" -r 24 -g 48 -keyint_min 48 -sc_threshold 0 -bf 2 -b_strategy 1 -minrate {$minrate}k -crf 23 -maxrate {$maxrate}k -bufsize {$bufsize}k -c:a aac -b:a {$audioBitrate}k -threads 4 -f hls -hls_time 6 -hls_list_size 60 -hls_flags +independent_segments+program_date_time -hls_segment_filename "res{$resolution}/segment_%03d.ts" -hls_key_info_file {$destinationFile}keyinfo {$destinationFile}res{$resolution}/index.m3u8`

I am not sure what is the difference, but again that is the first time I have seen the key file disappear
Let it finish

**Comment by JoshWho** [comment]
my ffmpeg command above is an optimized version and sets it to only use 4 cores.

**Comment by JoshWho** [comment]
What is the difference in Multi VOD HLS and Dynamic HLS?

**Comment by DanielnetoDotCom** [comment]
Please keep dynamic 

The other one is old it is just for backwards compatibility

**Comment by JoshWho** [comment]
I noticed looking in the tmp folder all the dates are wrong. What is causing that?

**Comment by JoshWho** [comment]
None of the ones encoding are the one that is broken

**Comment by JoshWho** [comment]
Why streams today say it is the 12th in the file system?
![image](https://github.com/user-attachments/assets/46f3133b-9c89-481a-8b6c-9e76e19b0f6a)

**Comment by JoshWho** [comment]
![image](https://github.com/user-attachments/assets/e3e39054-3320-4947-94bc-9e358f9fe2db)

**Comment by JoshWho** [comment]
must be GMT

**Comment by DanielnetoDotCom** [comment]
the server time now is 

Wed Nov 13 23:55:35 UTC 2024

**Comment by JoshWho** [comment]
Weirdest thing I have seen so far. Feel like we time traveled now 😂😅🤣

**Comment by DanielnetoDotCom** [comment]
Did you delete the files I sent to the encoder?

**Comment by DanielnetoDotCom** [comment]
why? are you sure the one is encoding now is the right one?

**Comment by JoshWho** [comment]
> Did you delete the files I sent to the encoder?

Yes I didn't see the one we was looking for it was all other shows.

**Comment by DanielnetoDotCom** [comment]
I do not understand what you mean but I hope you kept the right video in the encoder

**Comment by JoshWho** [comment]
> I do not understand what you mean but I hope you kept the right video in the encoder

I can see the thumbnails and none of them was the one I was looking for. I am downloading them all to my computer now to see them clearly

**Comment by JoshWho** [comment]
Is there a way to make finding these easier? Like give them a certain tag number or something so it matches the temp file to the live real file name some how.

**Comment by DanielnetoDotCom** [comment]
If I am not wrong the filename is the key + the date 

`record_suffix -%d-%b-%y-%T.flv;`

**Comment by JoshWho** [comment]
The key though doesn't tell me what channel or any hint to what the video is.

**Comment by DanielnetoDotCom** [comment]
This cannot change, it is a nginx configuration and we do not choose the name from AVideo

**Comment by JoshWho** [comment]
> This cannot change, it is a nginx configuration and we do not choose the name from AVideo

That is a bummer

**Comment by JoshWho** [comment]
Same thing just happened to this video https://ftjmedia.com/channel/Joshwho/video/.wB88ne7XkWUGff6yEJ459A/joshwho-morningstar-seekingthetruth-%E2%83%A3---alien-invasions-%F0%9F%91%BD%F0%9F%9B%B8-are-next.-project-blue-beam-project-skybeam-for-year-2024-this-agenda21-is-being-played-out-to-the-fullest-and-we-are-..

**Comment by JoshWho** [comment]
Am I just having bad luck today or has something changed?

**Comment by DanielnetoDotCom** [comment]
> Same thing just happened to this video https://ftjmedia.com/channel/Joshwho/video/.wB88ne7XkWUGff6yEJ459A/joshwho-morningstar-seekingthetruth-%E2%83%A3---alien-invasions-%F0%9F%91%BD%F0%9F%9B%B8-are-next.-project-blue-beam-project-skybeam-for-year-2024-this-agenda21-is-being-played-out-to-the-fullest-and-we-are-..


This one still encoding ,

![image](https://github.com/user-attachments/assets/552d98b0-f9d9-455f-9643-028240b2d6d3)


The other one must be one of those files I sent to the encoder, but you said it was not, so I hope you can find it

**Comment by JoshWho** [comment]
No that is a new one I am doing now

**Comment by DanielnetoDotCom** [comment]
also I can see you deleted the videos from yesterday from the tmp folder, they are not there anymore.

I hope you know what you are doing!

**Comment by JoshWho** [comment]
I didn't delete anything

**Comment by DanielnetoDotCom** [comment]
impossible the video was thare , maybe you moved to your desktop instead of copy

BTW this video is working here https://ftjmedia.com/channel/Joshwho/video/.wB88ne7XkWUGff6yEJ459A/joshwho-morningstar-seekingthetruth-%E2%83%A3---alien-invasions-%F0%9F%91%BD%F0%9F%9B%B8-are-next.-project-blue-beam-project-skybeam-for-year-2024-this-agenda21-is-being-played-out-to-the-fullest-and-we-are-

**Comment by JoshWho** [comment]
> impossible the video was thare , maybe you moved to your desktop instead of copy
> 
> BTW this video is working here https://ftjmedia.com/channel/Joshwho/video/.wB88ne7XkWUGff6yEJ459A/joshwho-morningstar-seekingthetruth-%E2%83%A3---alien-invasions-%F0%9F%91%BD%F0%9F%9B%B8-are-next.-project-blue-beam-project-skybeam-for-year-2024-this-agenda21-is-being-played-out-to-the-fullest-and-we-are-

I am onto something. That is the replacement video and this time I did not watch it in the video manager. The last times I did.

**Comment by JoshWho** [comment]
I think somehow prematurely accessing a video before it is truly completed is causing this.

**Comment by DanielnetoDotCom** [comment]
they were here 
![image](https://github.com/user-attachments/assets/321167c7-f8ba-4e84-aaa7-97b7cd62dabd)

and I did asked you to not delete and the video will remain there for investigation

![image](https://github.com/user-attachments/assets/caa2fc01-1534-44a1-b7b7-bea7bb4778ce)


![image](https://github.com/user-attachments/assets/08252728-89b1-44a0-aabc-d19e664f1d0a)


I do not know how to recover them now

**Comment by JoshWho** [comment]
I never touched the files. Only downloaded them

**Comment by DanielnetoDotCom** [comment]
Again, I have never see this happen, I need to check it.

lost key file is almost impossible, no idea what happen, but now all your videos from yesterday are gone, I do not know what to do

as I asked you, you are not supposed to delete the videos from the encoder.

**Comment by JoshWho** [comment]
I didn't delete anything. What are you talking about?

**Comment by JoshWho** [comment]
It is not a problem I have the video

**Comment by DanielnetoDotCom** [comment]
> I never touched the files. Only downloaded them

Didnt you delete the files from the encoder?
how they were removed?
how do you have the files did you download them? maybe moved them?

**Comment by JoshWho** [comment]
The only problem I am seeing is this weird thing by watching a video process in the video manager makes it break.

Not watching it , it works. 

What is viewing the page doing to it?

**Comment by DanielnetoDotCom** [comment]
If you have the file send them to encode again, and do not delete from the encoder, lets see how the key disappear

**Comment by JoshWho** [comment]
Still encoding
![703e06a9-7936-4d1a-b67b-cc8f9da7aab3](https://github.com/user-attachments/assets/b5b05cb7-ffe7-45ba-bc4e-0b6dc91084dc)

**Comment by DanielnetoDotCom** [comment]
Ok, Use your encoder, if that happens again, just make the video unlisted and let me know, do not delete the video from the encoder 
I will investigate.

**Comment by JoshWho** [comment]
> Ok, Use your encoder, if that happens again, just make the video unlisted and let me know, do not delete the video from the encoder I will investigate.

I don't directly have the file the user is the one that re uploaded it. I was just going to swap it out.

**Comment by JoshWho** [comment]
go to that encoder and turn off do not delete before it is too late so you can grab it.

**Comment by DanielnetoDotCom** [comment]
I did that on yours

> go to that encoder and turn off do not delete before it is too late so you can grab it.

**Comment by DanielnetoDotCom** [comment]
> > Ok, Use your encoder, if that happens again, just make the video unlisted and let me know, do not delete the video from the encoder I will investigate.
> 
> I don't directly have the file the user is the one that re uploaded it. I was just going to swap it out.

again, if happens again, keep it so I can investigate

the missing key is a surprise for me.

**Comment by JoshWho** [comment]
> > > Ok, Use your encoder, if that happens again, just make the video unlisted and let me know, do not delete the video from the encoder I will investigate.
> > 
> > 
> > I don't directly have the file the user is the one that re uploaded it. I was just going to swap it out.
> 
> again, if happens again, keep it so I can investigate
> 
> the missing key is a surprise for me.

Me too. Something super weird going on.

**Comment by JoshWho** [comment]
Get this....

So after I had the guy reupload the file I swapped the videos and it was working fine. Then I deleted the bad one and now the good one also does not work. How does that make any since?

**Comment by DanielnetoDotCom** [comment]
I need you to reupload and do not swap or delete anything 

I suspect you are doing things while the video is sinking with the storage, this is messing up

The swap tool is not to be used all the time is only to be user as an emergency

**Comment by DanielnetoDotCom** [comment]
There is a very good chance of unexpected behaviors if you swap videos while it is syncing with storage, you really should avoid that

**Comment by JoshWho** [comment]
I ended up just deleting then and start a fresh encode. It is better now.

**Comment by JoshWho** [comment]
> There is a very good chance of unexpected behaviors if you swap videos while it is syncing with storage, you really should avoid that

I think the swap did happen while it was moving.
