### ISSUE TITLE
Request Max payout in wallet.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9592]
A max option on the withdraw that will add the amount you have in your wallet to the request. 

Like in the pulldown menu that says amounts have a last option Max wallet.

**Comment by DanielnetoDotCom** [comment]
Hi

do you mean a maximum amount limit for withdraw or a button to withdraw all your wallet balance?

**Comment by JoshWho** [comment]
A button to withdraw all what you have in your wallet.

**Comment by DanielnetoDotCom** [comment]
Please check this
