### ISSUE TITLE
Malware detection of file on website, please advise

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#9604]
Hi 

My malware detector found this file on the website, but not sure what it is. It has not come up before; just this week.

Please advise if you recognise it:-

/var/www/html/AVideo/vendor/james-heinrich/getid3/demos/demo.write.php
{SA-MD5}S3.3ab669bea01e59a7508952913713d758

Otherwise no issue on website.

**Comment by DanielnetoDotCom** [comment]
This is a third party app

I am not using the demos, so it is removed in this update

**Comment by kollossus55** [comment]
Thx
