### ISSUE TITLE
I do not think encoding videos on the same server for live streams is the best way of going about things. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9608]
Everytime a video goes to the encoder it takes up all the cpu.

This makes the sites quality really bad. Load times sometimes takes up to 2 minutes for a page during this, and also double sends emails every time it is maxed on CPU. 

We are losing to competition that does not have theses buffers and problems we keep having. There needs to be a real solution.

**Comment by JoshWho** [comment]
![download (17)](https://github.com/user-attachments/assets/874186c1-cbd4-456c-8994-d04837de48d6)

**Comment by JoshWho** [comment]
Has to be some way to limit the ffmpeg process down to like 25% of the cpu and not 100%

**Comment by JoshWho** [comment]
Streams have been lately getting cut of buffering and so many other issues and I believe it is related to this encoding server taking all the CPU

**Comment by JoshWho** [comment]
![download (18)](https://github.com/user-attachments/assets/95f07948-e241-4a03-abc2-fea2ff4ffac6)
Last stream still encoding

**Comment by DanielnetoDotCom** [comment]
You can use a encoder in a separate server if you want, just change it in the site configurations. 

![image](https://github.com/user-attachments/assets/6c156711-3c4c-41a1-a988-0e9db4b61a10)

**Comment by walt93** [comment]
What about GPU servers? What's the cheapest 4090 going for?
Can we find a solution that has on demand GPU?
Rent by the hour?

https://www.primeintellect.ai/competitor

A RTX 3090 for $.19/hr ≈$137/mo, add some sauce to the ffmpeg command and probably spend a couple of hours in the seventh circle of hell getting drivers working and sorting out the ffmpeg voodoo (thank the lucky stars we have LLMs to make short work of this). Speed wise I'm guessing it's going to crush it over CPU. And @JoshWho all of your server slowdowns are history.
