### ISSUE TITLE
Live streams sometimes give the wrong link to view

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9611]
This one currently going now on Homepage Logos Academy and it is linked https://ftjmedia.com/live/0/LogosRevealed

When going to that this is what I see

![49f9b555-f3d7-4c46-92bb-3498af49b4cc](https://github.com/user-attachments/assets/8f971bcb-52e1-45a8-be65-39d3f34b813c)

If I add a question mark 1 to the end it works   https://ftjmedia.com/live/0/LogosRevealed?1

![06caf58e-5238-4a19-a305-72df6fd48be7](https://github.com/user-attachments/assets/d9c835f5-d1c9-4634-84c8-b3401676bec0)

**Comment by DanielnetoDotCom** [comment]
I am not sure the difference, but when I click in the menu it works


![image](https://github.com/user-attachments/assets/38e28375-0465-482c-a367-d53aeaf4324f)

**Comment by DanielnetoDotCom** [comment]
Let me investigate it, I also just notice the lives are not passing thru the CDN, not sure why

**Comment by JoshWho** [comment]
> Let me investigate it, I also just notice the lives are not passing thru the CDN, not sure why

I thought something was up about that with the lives.

**Comment by JoshWho** [comment]
Let me know when you get that fixed for the live cdn. That explains a lot why the streams were buffering

**Comment by DanielnetoDotCom** [comment]
I can see you used to use live servers, but not anymore, that is why, the CDN is now enabled on the live and you should gain performance. 

Also I guess I found the issue for that link, please try again.

**Comment by JoshWho** [comment]
Thank you Looks good now. Could you please email Dave about the live CDN info he wanted to know more about it.

**Comment by JoshWho** [comment]
Still happening. I have to tell people the correct link to watch in chat

![408d06dc-1bbc-478b-9b94-fb53375fca60](https://github.com/user-attachments/assets/90059737-5408-4172-a7a5-e908d528ab12)

**Comment by JoshWho** [comment]
![202efdc7-9e63-4ada-9824-e2b390db3666](https://github.com/user-attachments/assets/18d8ea1e-9943-49b9-bddc-a9af8c372012)

**Comment by DanielnetoDotCom** [comment]
are you able to reproduce a live that generates the wrong link so I can test it from here?
