### ISSUE TITLE
What recommendations do you give for increasing the Playlist in Nginx to 60m?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9612]
I seen the default was 20m and I know it stores in memory but we have a request to increase it to 60m.

Would you advise that working or will it be problems?

for 

 hls_playlist_length 20m;

**Comment by DanielnetoDotCom** [comment]
For myself I use 60m by default with no problem, cound be even more

**Comment by JoshWho** [comment]
kk will change it.
