### ISSUE TITLE
Playing the live streaming in VLC and can see what is happening. There is 500 errors every now and then

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9613]
Please watch this video here https://ftjmedia.com/channel/Joshwho/video/.nx8v1nKW1UeJO2klxi7SPw/2024-11-20-20-54-49

I recorded what is lively happening.

**Comment by DanielnetoDotCom** [comment]
What m3u8 link are you using?

make sure the m3u8 you are using is using the CDN

what 500 error are you seeing?

**Comment by DanielnetoDotCom** [comment]
please check what is the m3u8 URL are you getting

is it after enable the CDN?

Also check what resolution is this user using on his livestream

**Comment by JoshWho** [comment]
It is the cdn one  That show isn't going now. There is another stream you can check live going https://ftjmediacomlive.cdn.ypt.me/673f1eca5bd47/index.m3u8

**Comment by DanielnetoDotCom** [comment]
I can see this with no issue

https://ftjmedia.com/live/0/Psychodrilla/1

can you see any issue on it?

**Comment by JoshWho** [comment]
Watch it with inspect element every now and then a playlist file will give 503 error

**Comment by JoshWho** [comment]
> I can see this with no issue
> 
> https://ftjmedia.com/live/0/Psychodrilla/1
> 
> can you see any issue on it?

I am not seeing it happen to that stream.

**Comment by JoshWho** [comment]
> I cannot watch it now. I am away from pc I probably gonna be able to watch only tomorrow. So check what is the live resolution in the stats page
> 
> What livestream is that, that is giving 503 error? What's the user? Who is the owner?
> 
> Also, when you see a 503 error, click and check what it returns, what's the content of that file. If there is any message

Will do when I see it again.

**Comment by DanielnetoDotCom** [comment]
But Psychodrilla is not buffering correct?

**Comment by JoshWho** [comment]
> But Psychodrilla is not buffering correct?

Just that one time in the screen shot.

**Comment by DanielnetoDotCom** [comment]
I am at home now, and I am not seeing any 503 error in the log

I checked the CDN log and I could see 503 error from only 2 IPs, I guess one of them is yours

98.97.153.* (85% of all the errors)
73.109.160.* (15% of all the errors)

so it seems to be more related to most from these IPs

**Comment by JoshWho** [comment]
Interesting. Does it say why or what the actual error was?

**Comment by JoshWho** [comment]
> I am at home now, and I am not seeing any 503 error in the log
> 
> I checked the CDN log and I could see 503 error from only 2 IPs, I guess one of them is yours
> 
> 98.97.153.* (85% of all the errors) 73.109.160.* (15% of all the errors)
> 
> so it seems to be more related to most from these IPs

Sadly none of those is my ip.

**Comment by DanielnetoDotCom** [comment]
Not sure then

So when he goes live again check his live parameters in the stats

**Comment by JoshWho** [comment]
> Not sure then
> 
> So when he goes live again check his live parameters in the stats

Will do

**Comment by JoshWho** [comment]
Is the old m3u8 link being 301 redirected to the cdn? Wonder if an attacker can just change it back to the original domain and ddos it?

**Comment by DanielnetoDotCom** [comment]
No, m3u8 and ts are just a static files, should be no impact on it

**Comment by DanielnetoDotCom** [comment]
Is possible to protect the livestream but it will stop the mrss feed and third parties players like VLC


https://github.com/WWBN/AVideo/wiki/Live-Plugin#setting-up-key-protection-in-nginxconf

**Comment by JoshWho** [comment]
No way to make this just the live stream and still send raw to the encoder?

**Comment by DanielnetoDotCom** [comment]
the encoder will still work, I am not sure what do you mean

**Comment by JoshWho** [comment]
That sounds perfect. I do not care about watching it on vlc I was just doing that for a second view test. If we can make it locked on to our player that will be great. Just for the live streams.

**Comment by JoshWho** [comment]
This is what the 503 looks like when it happens

![f7c38a61-c9a3-4851-8693-2e87e5c20f0d](https://github.com/user-attachments/assets/628f2724-d35e-4215-81d3-fbd517f80f9b)

![image](https://github.com/user-attachments/assets/abf51c3a-e45d-46ac-b173-1658f9528fa8)

**Comment by JoshWho** [comment]
This is making me have wars with others now. I have no explanation why it is happening.

**Comment by JoshWho** [comment]
Could you please change that setting for me to make it protected in the live player?

**Comment by DanielnetoDotCom** [comment]
can I restart your nginx server now?
I was planing to do this on monday

**Comment by JoshWho** [comment]
Yes go for it. No one is streaming.

**Comment by DanielnetoDotCom** [comment]
ok, working on it now

**Comment by DanielnetoDotCom** [comment]
Please check it now, VOD HLS and Live should be protected now and only AVideo player can play them

**Comment by JoshWho** [comment]
> Please check it now, VOD HLS and Live should be protected now and only AVideo player can play them

but people can still download the mp3 and mp4 correct?

**Comment by JoshWho** [comment]
My stream is not playing

**Comment by JoshWho** [comment]
![image](https://github.com/user-attachments/assets/7839d2f8-5703-40fc-bbd1-14160891a38c)

**Comment by DanielnetoDotCom** [comment]
It is playing here fine

**Comment by JoshWho** [comment]
That is odd

It just spins for me

**Comment by DanielnetoDotCom** [comment]
clear the cache and refresh

**Comment by JoshWho** [comment]
It was the limit I had. I disabled it now that the cdn is working. It was only allowing 1 ip to watch and if same ip tries to open a second it blocks . I disabled that now. Looks good. Thank you @DanielnetoDotCom

**Comment by JoshWho** [comment]
There is a rate limit in the HLS proxy pass.  You can't Live stream and watch it at the same time

**Comment by JoshWho** [comment]
In the configuration you've provided, indeed all explicit rate limiting directives (limit_req and limit_req_zone) have been commented out or removed. However, here are a few points to consider:

External Services for Authorization: 
The /auth_key_check location block uses proxy_pass to forward requests to an external PHP script for authorization. This script might implement its own rate limiting. You'll need to check the script (authorizeKeyAccess.php) to ensure there are no internal rate limits or restrictions applied.

```
location = /auth_key_check {
    ...
    proxy_pass http://localhost/AVideo/plugin/Live/authorizeKeyAccess.php;
    ...
}
```

**Comment by DanielnetoDotCom** [comment]
there is no rate limit, and if you comment out, your videos are not protected anymore, please do not change anything

**Comment by JoshWho** [comment]
I am not changing that. I just want to see what is doing this.

**Comment by DanielnetoDotCom** [comment]
no, there is no rate limit, I do not implement those things

**Comment by JoshWho** [comment]
Can you try the obs and see if it plays for you.

**Comment by JoshWho** [comment]
Maybe nginx is not fully rebooting

**Comment by DanielnetoDotCom** [comment]
it is rebooted, it is a new installation

> Maybe nginx is not fully rebooting

**Comment by DanielnetoDotCom** [comment]
> Can you try the obs and see if it plays for you.

I did it to test and it works

**Comment by JoshWho** [comment]
Hopefully it is just me this is happening too. Will see tonight. Thank you @DanielnetoDotCom

**Comment by JoshWho** [comment]
Config is broke I cannot get it to restart

**Comment by JoshWho** [comment]
Can you please give me a default config with the new setting. So sorry and will not try messing with this again

**Comment by JoshWho** [comment]
Hold on I might have it

**Comment by JoshWho** [comment]
Ok I got the nginx server back on I think you just need to add the hls key stuff again Please and thank you.

**Comment by JoshWho** [comment]
No it is still broke. i NEED A NEW DEFAULT CONFIG WITH THE CORRECT SETTINGS. sO SO SORRY Daniel. This is horrible.

**Comment by DanielnetoDotCom** [comment]
It was working, what did you do?

**Comment by JoshWho** [comment]
I was trying to remove all the limit request blocks and I deleted something else I am not sure of and would not let me restart it. Now I put back the default config I had saved but it is not working right. 

I broke it badly.

**Comment by DanielnetoDotCom** [comment]
I can see you modified the conf, it is probably not protected anymore, I can only help you if you do not change thing, I also do not knwo what to do, sorry, if you can just put the conf back

**Comment by DanielnetoDotCom** [comment]
I will add it one last time, please do not change it

**Comment by JoshWho** [comment]
All the other confs I had saved in there are gone. I do not have a working one.

**Comment by JoshWho** [comment]
> I will add it one last time, please do not change it

Thank you and I promise I will not touch it.

**Comment by JoshWho** [comment]
There also might be a mod called request limit needs to be disabled or deleted.

**Comment by DanielnetoDotCom** [comment]
I did re compile/install all nginx, It is back now, and should be fine, please be careful.

**Comment by JoshWho** [comment]
> I did re compile/install all nginx, It is back now, and should be fine, please be careful.

Thank you thank you thank you so much.

**Comment by JoshWho** [comment]
This is also the best I have ever seen the streams play. Thank you again.

**Comment by JoshWho** [comment]
Only thing I worry about now is I can see every broadcasters IP address publicly looking at the nginx stats page.

NGINX statistics pages, which are often accessed via the nginx_status or similar endpoints, can indeed expose sensitive information if not properly secured. These statistics can include details like the number of active connections, server uptime, and more importantly, might inadvertently reveal IP addresses or other network-related information about the server or its clients. Here are the reasons why this information should not be publicly visible:

Privacy Concerns: The IP addresses of clients or even backend servers (in case of load balancing or proxy setups) can be exposed. This includes both the IP of the NGINX server itself and possibly the IPs of clients connecting to the server, which could lead to privacy breaches, especially under regulations like GDPR where personal data protection is paramount.

Security Risks: Exposing server statistics publicly can provide attackers with valuable reconnaissance information. Knowledge about server load, active connections, and other operational metrics can be used to plan or time attacks like DDoS (Distributed Denial of Service) or to identify potential vulnerabilities or misconfigurations.

Internal Network Disclosure: If NGINX is used as a reverse proxy or load balancer within an internal network, the stats might leak internal IP addresses or network topology information, which should not be exposed to the public internet.

IP Leakage Through WebRTC or Similar Protocols: While not directly related to NGINX stats, similar concerns about IP exposure exist with technologies like WebRTC, where improper configuration or lack of security can lead to IP address leaks. This analogy can be drawn to understand the broader implications of exposing network-related information.


To mitigate these risks:

Restrict Access: Ensure that the NGINX status page is only accessible from trusted IPs or networks using allow and deny directives in the configuration.

Use Authentication: Implement basic HTTP authentication or more secure methods to protect the status page from unauthorized access.

Disable or Modify: If the stats are not needed publicly, consider disabling them or modifying the NGINX configuration to only log or display necessary information internally.

Monitor and Audit: Regularly review access logs and security audits to ensure no unintended exposure occurs.

In summary, making NGINX stats publicly visible can compromise both privacy and security, hence it's crucial to manage and secure this information appropriately.

**Comment by DanielnetoDotCom** [comment]
where you can see the IP exactly?

screenshot

**Comment by JoshWho** [comment]
![image](https://github.com/user-attachments/assets/96314b00-9546-4d85-b0c3-a4ad3f9f0525)

**Comment by JoshWho** [comment]
> where you can see the IP exactly?
> 
> screenshot

It is in the source of the page

**Comment by JoshWho** [comment]
Have a important stream that will start tomorrow around 12pm ct so if you need to reboot it please go for it before the live show tomorrow.

**Comment by JoshWho** [comment]
I ended up doing that with the deny in the blocks
```

                location /stat {
                        rtmp_stat all;
                        rtmp_stat_stylesheet stat.xsl;
                        allow 127.0.0.1;
                        allow 142.44.139.17;
                        deny all;
                }
                location /stat.xsl {
                        allow 127.0.0.1;
                        allow 142.44.139.17;
                        deny all;
                        root html;
                }

```

Figure as long as localhost and server ip is allowed shouldn't break anything.
