### ISSUE TITLE
MP3 url doesn't end with file extension mp3

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9614]
This is what it is showing https://ftjmediacom.cdn.ypt.me/videos/video_241120144059_vdfdf/video_241120144059_vdfdf.mp3?download=1&title=The+Sane+Asylum+Based+Hump+Day+%23286+-+20NOV24+-+CoHost%3A+David+Scorpio%3B+Guest%3A+PK+from+Panama_mp3_.mp3

When you click it it downloads the file without the .mp3 extension

**Comment by JoshWho** [comment]
Should be like https://ftjmediacom.cdn.ypt.me/videos/video_241120144059_vdfdf/video_241120144059_vdfdf.mp3

**Comment by DanielnetoDotCom** [comment]
Please check this update
