### ISSUE TITLE
[users] BUG error "Email Must be unique"

### ISSUE THREAD

**Issue by gbrn** [WWBN/AVideo#9616]
@DanielnetoDotCom Danny, I'm getting an error _"Email Must be unique"_ when running new user registration. Check out this Bug.

**Comment by DanielnetoDotCom** [comment]
search for this email, it already probably exists

**Comment by gbrn** [comment]
No, there is no email. The problem has nothing to do with what the message says. The message is generic. I can type any email. The problem and the message are the same. 
Can you do a test on your side?

**Comment by DanielnetoDotCom** [comment]
It works here, so check your logs

![chrome-capture-2024-10-21 (4)](https://github.com/user-attachments/assets/ae61a0d2-2833-4e97-aac4-93b98743d23a)

**Comment by gbrn** [comment]
Danny,

The video shows how you register with random data. And then I change the email to another random email.
The problem is not the data entered, you can see that in the video.
[CNETV.webm](https://github.com/user-attachments/assets/aed231c5-0435-4afd-ae50-7547c729f97f)

Here is an excerpt from the log I was registering from. I didn't find anything referring to new user registration:
[log.txt](https://github.com/user-attachments/files/17850874/log.txt)

What is this message? "Email Must be unique", to me it is a strange message because it has never been displayed, and there is no translation for it.
In the code, when is this message supposed to be displayed at what times?

Ps.: It is important to say that the registration of new users is ok through SIGNUP: https://cnetv.com.br/signUp.
It is just not working when the Administrator tries to create a new user.

Could you check the following code:
/objects/userCreate.json.php
/objects/userAddNew.json.php

Make sure the code correctly checks if the email already exists in the database.
The logic may be searching in an incorrect table or field, or ignoring upper/lower case.

Email format and consistency:
The email may be normalized (e.g., all lower case) before being saved or compared. Make sure the same process is applied during the uniqueness check.

Database query:
The query snippet may not be returning the expected results due to connection issues or data inconsistencies.

Generic error messages:
The message may be displayed as standard error, even though the problem is something else (e.g., failure to insert the record into the database).

**Comment by DanielnetoDotCom** [comment]
I can affirm the email is in your database, there is no other reason

remember to also check inactive users

**Comment by gbrn** [comment]
@DanielnetoDotCom I showed you in the video, typing anything. I have less than 400 registered users.

Watch the videos... I'm typing any name, any email... how can this be in the database?

The problem may be on my side... but I'm sure the error message is generic.
This isn't hard to test... it's right there in the video.

**Comment by DanielnetoDotCom** [comment]
Get this update and try again, this will give you more info what is happening

**Comment by gbrn** [comment]
The error now displayed is:
`Email Must be unique FALSE: Invalid email address. testedeusuario22112024ok`
I used a random email that was never registered: testedeusuarios22112024ok@testesdeusuarios.com

I tested other emails, it could be a fictitious or real email, but the error is the same: "Email Must be unique FALSE: Invalid email address."
