### ISSUE TITLE
IMA not  loadig and cant use any options or see plugin or play video 

### ISSUE THREAD

**Issue by antuk21** [WWBN/AVideo#9617]
<img width="662" alt="ima" src="https://github.com/user-attachments/assets/11021f35-1223-476f-8117-c4170bc83cdf">

**Comment by DanielnetoDotCom** [comment]
Are you using https?

you must use a valid SSL

**Comment by DanielnetoDotCom** [comment]
Or just disable the plugin AdBlockerDetector

**Comment by antuk21** [comment]
ok fixed that thank you.  one more issue now    says not finding gibsonplatform.co.uk:8443/live/67445e4c67ae5-1/index.m3u8:1
