### ISSUE TITLE
Now that hls protection is on does that stop the Restreaming from working?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9621]
A user today that normally used the built in restreaming says he can't get it to work now. 

Does it have the Push config in it for that to work?

![c0ee2fc1-3823-4b9d-84a1-92ce2355c818](https://github.com/user-attachments/assets/5ea04a7d-1d71-4639-99ef-2d14ba458e4e)

**Comment by DanielnetoDotCom** [comment]
Restream should work with the HLS protected. 

the issue may be something else

**Comment by DanielnetoDotCom** [comment]
Sorry you were right, the secure live was blocked to restream, this update should fix it.
