### ISSUE TITLE
video not loading again this errors im getting just loading no live video 

### ISSUE THREAD

**Issue by antuk21** [WWBN/AVideo#9630]
<img width="960" alt="gghhjjk" src="https://github.com/user-attachments/assets/6a848b0b-89fb-4659-b080-cec3b95c9b41">

**Comment by DanielnetoDotCom** [comment]
You probably have the CDN plugin enabled and you did not setup the CDN properly, disable it

but your liive stream is something else, search for somethign like `authorizeKeyAccess.php` in the log file

**Comment by antuk21** [comment]
<img width="960" alt="logs" src="https://github.com/user-attachments/assets/e7805fa8-ccef-43b7-a255-6e75d9e00fd4">

**Comment by DanielnetoDotCom** [comment]
Can you please make a git pull and try again?

**Comment by DanielnetoDotCom** [comment]
why did you changed those files?

make sure you overwrite all your changes. 

```bash
sudo git fetch --all
sudo git reset --hard origin/master
```

**Comment by antuk21** [comment]
ok fixed thank you
