### ISSUE TITLE
DVR is cutting off all the live streams.

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9633]
None of them lately from last night recorded all of the way. They always get cut short, and now looking at my tmp folder the files in there are all in the hundreds of megabytes. 

Here is a stream from last night https://ftjmedia.com/channel/Davis/video/.Wduei7SxUiqJcT-rYAfhBA/right-perspective-radio-with-davis-lurmann-162-25-nov-2024-on-25-nov-24-19-00-11 which is 1:31:13

This is that same stream recorded on Rumble https://rumble.com/v5t47oq-right-perspective-radio-with-davis-lurmann-162-25-nov-2024.html?e9s=src_v1_ucp which is 3:05:09

**Comment by JoshWho** [comment]
Looking at the config I noticed thi

2048M is the set record limit

![93c62dd0-d0e3-4cc3-a473-d53cbcf0df7d](https://github.com/user-attachments/assets/bac4bb6b-36c6-4f98-9caa-2a2b270c666c)

**Comment by DanielnetoDotCom** [comment]
Your record was limited to 2GB, now I updated and it is 10GB

I missed that when I reisntall your nginx last time 

You should have no problem anymore

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom
