### ISSUE TITLE
Video from yesterday never created download links, how to manually make it do it?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9635]
Not sure why but this video https://ftjmedia.com/channel/GiuseppeVafanculo/video/.GKX4e2QmE_Issae8PXTlmA/the-sane-asylum-287-based-monday---25nov24

never generated a mp3 or mp4 but it is fully playable.,

**Comment by DanielnetoDotCom** [comment]
I am not sure either, but I deletet the mp3 file in the video folder, 

It forces the script to create a new one, and the new one is good

https://ftjmedia.com/channel/GiuseppeVafanculo/audio/.GKX4e2QmE_Issae8PXTlmA/the-sane-asylum-287-based-monday---25nov24

**Comment by JoshWho** [comment]
Thank you
