### ISSUE TITLE
Fun with Broken Missing Files

### ISSUE THREAD

**Issue by walt93** [WWBN/AVideo#9638]
**Describe the bug**
"BROKEN MISSING FILES"  multiply. Many such cases.

https://github.com/user-attachments/assets/f6a969b4-9bdf-4405-9a9b-24855f0abf3e

**Comment by DanielnetoDotCom** [comment]
Are they HLS?

Do not delete them, give 5 min and try to access the video, I guess the broken missing may disappear

**Comment by walt93** [comment]
No HLS, just MP4, I'm just showing you the insanity of my day. Upload 30 files. Delete 10 "broken missing files". 
Try to delete one "broken missing file" and watch them literally multiply. 

I assume by previous lack of responses from any other users that this must be localized to my server, so that's encouraging. Maybe this is an easy fix, I just don't know what to look for - what do you suggest searching for in the encoder log?

**Comment by DanielnetoDotCom** [comment]
Check avideo and encode logs at the moment the encode process finishes and transfer the file to the streamer

try not delete the files and resend the broken ones

https://github.com/WWBN/AVideo-Encoder/wiki/Finding-Errors-on-the-Encoder

**Comment by walt93** [comment]
Thanks, reading that now. P.S. What the heck does "Broken Missing Files" *actually* mean? That a "mp4" file is not present in some certain location? And we don't have this file until the encoder is done ripping &/or copying it to it's final destination? And ergo, maybe there is a 5 minute or some delay in copying? (and if that guess is lucky, is that not a state which we could report?) Just spitballing here.

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Understanding-the-Broken-Missing-Files-Status

**Comment by walt93** [comment]
🤖: **2-Hour Timeout Issue:**
```
logCopy[20-Nov-2024 14:17:10 UTC] CreateSpirits: request is older then 2 hours, we will try again
[20-Nov-2024 16:01:57 UTC] CreateSpirits: request is older then 2 hours, we will try again
```
The encoder is failing after 2 hours on larger files, particularly with podcast-length content. This appears to be a hard timeout, affecting the sprite creation process even after successful encoding.

**Resolution Validation Error:**

`[18-Nov-2024 10:28:36 UTC] {"error":true,"msg":"This resolution is not possible 464","forbiddenPage":true}`

The encoder is rejecting content with non-standard resolutions (in this case 464p). This particularly affects content sourced from social media which often uses arbitrary resolutions. The error occurs during chunk processing, as evidenced by:

`logCopy"chunkFile":"/tmp/YTPChunk_9UJIqL","encoderURL":"https://phoenix.conspyre.tv/","keepEncoding":"0"
`

**Additional context:**

The 2-hour timeout appears to be affecting long-form content (2hr+ podcasts)
The resolution error is primarily affecting social media content
Both issues can result in "broken missing files" status

** Proposed Enhancement**

Add automatic resolution normalization as a pre-processing step, using ffmpeg to conform non-standard dimensions to AVideo's supported resolutions:

ffmpeg -i input.mp4 -vf "scale=-2:720:force_original_aspect_ratio=decrease,pad=1280:720:-1:-1:color=black" -movflags +faststart -preset veryfast -c:v h264 -b:v 1700k -c:a aac -b:a 128k output.mp4

Benefits:
Prevents "resolution not possible" errors
Maintains aspect ratio using letterboxing/pillarboxing
Uses existing encoder codec settings
Improves compatibility with social media sources
Reduces support requests for resolution-related issues

------
Human here, I guess I can just try this on my local encoder, just wanted your thoughts on it.

**Comment by DanielnetoDotCom** [comment]
Please stop to share AI things and share the raw log.

AI is useless here and only make things more confused.

**Comment by walt93** [comment]
I had examined the log and the AI analysis. 

There are multiple classes of error affecting my encoder. Several I was able to fix. 

The thumbnail generation code is failing with a log message that states it is more than two hours old. That seems like an easy fix. Increase timeout value.  

Then it fails on odd resolution videos like 462P or whatever crazy res social medias are using. My question is do you see any issues with using ffmpeg to pre-scale the resolution while transcoding.  The reason I am asking is because really vetting this means coming up with dozens of test cases. 

Just a note I've used Claude to sling about 45K LOC in the last three months, building a Roku channel with integrated website/backend, an AI SaaS and countless little tools and scripts. AVideo is just too much code to fit into context and I don't know what pieces to feed it to work on it. Soon....

**Comment by DanielnetoDotCom** [comment]
Hi,

### Thumbnail Generation:  
This is unrelated to "Broken Missing Files." I recommend opening a new issue for it and share the related logs on it. 

### Odd Video Resolutions (e.g., 462P):  
To avoid issues with non-standard resolutions, ensure your encoder has lower resolutions enabled (e.g., 240P or 360P). 462P will not generate 480P, as we do not upscale.

### Regarding Your Note About Claude:  
I’m not sure what this refers to

Best regards,  
Daniel

**Comment by walt93** [comment]
How can we enable these resolutions, and have the encoder run exactly one time? I only want one transcode, I do not want a 1080P + 720P + 480P + 360P for every video.

**Comment by DanielnetoDotCom** [comment]
Automatic transcode is better, because you do not gain quality if you upscale a video.

You have 2 options, 

1. do not use the encoder, only direct upload (not recommended)
https://github.com/WWBN/AVideo/wiki/About-Video-Upload#direct-upload

2. Force a specific reolution, so you need to disable the automatic resolutions
https://github.com/WWBN/AVideo/wiki/About-Video-Upload#disabling-automatic-resolutions

**Comment by walt93** [comment]
I HAVE ASKED THE SAME QUESTION 5 DIFFERENT WAYS AND YOU STILL CAN'T ANSWER IT SO I GUESS THE ANSWER IS NO
