### ISSUE TITLE
CDN has ip addresses being blocked

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9643]
This is what I get when trying to see a live stream 

![image](https://github.com/user-attachments/assets/20f39af0-0b44-4462-8b96-8e2451b62587)

This is a ip ban because if I change to a vpn it works. 

My IP

![image](https://github.com/user-attachments/assets/857d82f2-baf2-4242-9299-870be99ab95c)

Now with VPN

![image](https://github.com/user-attachments/assets/e746cedf-fe58-4fc3-ba65-081104bb0b8c)

![image](https://github.com/user-attachments/assets/196cd178-e1ba-401c-a741-1c35798e3c3a)

**Comment by JoshWho** [comment]
Please figure out how to un ban all ip addresses. There is a lot of false positive I am imagining.

**Comment by DanielnetoDotCom** [comment]
I will check later but I can tell you , I have nothing blocked on the CDN. I never block anything there

**Comment by JoshWho** [comment]
> I will check later but I can tell you , I have nothing blocked on the CDN. I never block anything there

Iwas looking at how bunny works and it is a auto thing and sometake signals from nginx and when I had requests limited I think it banned a lot of people on the cdn when that happened and my ip is still blocked.

**Comment by DanielnetoDotCom** [comment]
Now I could see your images and I do not need to check the CDN

the bunny block or error page are customized.

I am 100% this is something in your nginx. 

I am not sure what you have added in it but something is blocking your IP

BTW, can you share your IP?

**Comment by JoshWho** [comment]
> Now I could see your images and I do not need to check the CDN
> 
> the bunny block or error page are customized.
> 
> I am 100% this is something in your nginx.
> 
> I am not sure what you have added in it but something is blocking your IP
> 
> BTW, can you share your IP?

I sent it in email. Just turned off the vpn. As soon as I get unblocked the live stream should just start working again for me

**Comment by JoshWho** [comment]
I wonder if purging the push zone cashes would fix it.

**Comment by DanielnetoDotCom** [comment]
If you can share your IP so I can search for more details

**Comment by JoshWho** [comment]
> If you can share your IP so I can search for more details

I emailed it to you

I am getting this arror with the cdn url https://ftjmediacomlive.cdn.ypt.me/674853b785cd6/2520.key?token=cmd0cjl5VVFzcEh1bng0ZFljMnZFVGpxNFdkR1ErdnpwMXRRYkNRUk5GTnZvb2xVVWpMRndCUytwREZzdkhiNjVlV1ZBZmNLbmdZU3pWcmpPTWtpbVdySzltNWo3M01IWUdsSTNKNHI3QVZDTmJDMk1oMzM3c01zbzNFbk9pZVE2emxnTmp3MzNFbVdGSWUwRDFLR2hkdm02NjNyZUU4QXBRaGFLTXRVczd6ckhVSTUvMUROS2N1UlE0VWxPN0NURW53SHMrSCt6OUdHSEViK1ZHc3lxNmRJaW9CZFNQd3VjeXBYMXJLZXdNc0ZUSDFzUXloNU9MR1BBaCtqV1FGckR0ZG1welozRnFqbXZtT2d6WlRXdGc9PQ==

**Comment by DanielnetoDotCom** [comment]
Got your IP and your last logs are like this

````
[28-Nov-2024 15:16:41 UTC] AVideoLog::DEBUG:      VideoHLS: verifyToken the time is wrong {"time":1732803971,"videos_id":0,"ip":"****","atoken":"","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/131.0.0.0 Safari\/537.36"} HTTP_USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 (obj->time=1732803971 < time=(1732807001)). Token expired 3030 seconds ago. SCRIPT_NAME: /AVideo/plugin/Live/authorizeKeyAccess.php
````

that means your browser has issues to request the new token 
Check what happen with the `plugin/VideoHLS/getToken.json.php` request

![image](https://github.com/user-attachments/assets/3cb12314-3ef3-467f-8a29-48ca7582a7f8)

**Comment by JoshWho** [comment]
why would changing my ip make it work?

**Comment by DanielnetoDotCom** [comment]
No idea, that is why I am asking you to check what is happening.

**Comment by DanielnetoDotCom** [comment]
Let me know when you check the getToken.json.php

**Comment by JoshWho** [comment]
> Let me know when you check the getToken.json.php

where is that?

**Comment by JoshWho** [comment]
![image](https://github.com/user-attachments/assets/d262160e-bafa-4929-9dee-c2e4b9011a2a)

**Comment by JoshWho** [comment]
![image](https://github.com/user-attachments/assets/b59fdc0d-f483-4579-90a9-b4fce37a151b)

**Comment by JoshWho** [comment]
```
root@ftjmedia:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

```

**Comment by DanielnetoDotCom** [comment]
I need to see the content response

**Comment by JoshWho** [comment]
> I need to see the content response

This?

![image](https://github.com/user-attachments/assets/0f94f6d3-faf2-454a-b29e-bcd9bfd4f1c6)

**Comment by DanielnetoDotCom** [comment]
Please look my screenshot

https://github.com/WWBN/AVideo/issues/9643#issuecomment-2506352950

**Comment by JoshWho** [comment]
![image](https://github.com/user-attachments/assets/b19d1e66-9eef-49d9-9d16-997381558a18)

**Comment by JoshWho** [comment]
![image](https://github.com/user-attachments/assets/5fea72f2-a16f-4834-87a7-eaa77402cceb)

**Comment by DanielnetoDotCom** [comment]
> It is this pullzone https://ftjmediacomlive.cdn.ypt.me/ that is blocking
> 
> it won't let me clear the cache
> 
This is how supposed to be

the issue is something else

**Comment by JoshWho** [comment]
Look here is using the vpn

![image](https://github.com/user-attachments/assets/ad1ca376-684b-4ed8-a8da-cc9a1f12cdbf)




Now same page without vpn using my ip


![image](https://github.com/user-attachments/assets/4f6598b1-b261-4735-8cdf-7a8608a83adf)

**Comment by DanielnetoDotCom** [comment]
403 is expected it you try to direct access or use another player, so forget it!

403 is NOT expected if you use the avideo player and it get the propper getToken.json.php

your getToken.json.php seems to be fine, I am now trying to find why you are getting a 403 in the player

**Comment by JoshWho** [comment]
It downloads with no problem as shown in the screenshot

**Comment by JoshWho** [comment]
Just look at the cdn it has to be the only thing doing this.

**Comment by JoshWho** [comment]
What is used to ban a ip from nginx that is built into Avideo there has to be a list or something.

**Comment by DanielnetoDotCom** [comment]
I do not have anything to ban.

lets do this ....

1. disable auth_request, in your nginx.conf comment out auth_request /auth_key_check;

![image](https://github.com/user-attachments/assets/1582c372-29a1-4ab9-ada4-c67c8adb4d89)

2. restart nginx
3. test it again

I am suspect is something in your header that is not sending to the nginx.
we use some header info to validate the key

**Comment by JoshWho** [comment]
That unblocked me

**Comment by DanielnetoDotCom** [comment]
No idea, but again, I suspect is something in your header, do you have some filter in your IP output?

**Comment by JoshWho** [comment]
> No idea, but again, I suspect is something in your header, do you have some filter in your IP output?

No and like I said all my devices work now on that link. Phone laptop and desktop. 

I do not think it is browser related, if this stops that maybe we should keep it like this.

**Comment by DanielnetoDotCom** [comment]
No browser, I mean router from your internet provider, maybe it is filtering something.

**Comment by JoshWho** [comment]
> No browser, I mean router from your internet provider, maybe it is filtering something.
> 
> Specifically something in your header information

No clue just a cable modem router from comcast. No way to change that.

**Comment by DanielnetoDotCom** [comment]
FYI I found this in your log
 '2**.1**.1*7.1*5' is your IP
 
 that is probably something
 
 ```
tail -n 99999 /var/log/apache2/error.log | grep '2**.1**.1*7.1*5'
[Thu Nov 28 08:22:27.791372 2024] [qos:error] [pid 1835748] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 08:26:21.362498 2024] [qos:error] [pid 1836868] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 08:26:21.423488 2024] [qos:error] [pid 1837309] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 08:34:04.348392 2024] [qos:error] [pid 1838785] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 09:36:18.334377 2024] [qos:error] [pid 1855446] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 09:36:18.438385 2024] [qos:error] [pid 1855726] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 09:36:20.860478 2024] [qos:error] [pid 1853962] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 10:07:16.875476 2024] [qos:error] [pid 1861741] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 10:07:25.073391 2024] [qos:error] [pid 1862381] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 10:27:25.524360 2024] [qos:error] [pid 1866941] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 10:27:25.614423 2024] [qos:error] [pid 1867258] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 10:27:25.616453 2024] [qos:error] [pid 1867259] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 10:27:25.634479 2024] [qos:error] [pid 1867282] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 10:28:07.593418 2024] [qos:error] [pid 1866988] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 10:33:14.781376 2024] [qos:error] [pid 1866663] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 10:36:58.506367 2024] [qos:error] [pid 1868857] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5
[Thu Nov 28 10:36:58.801358 2024] [qos:error] [pid 1869739] mod_qos(034): access denied, QS_SrvMinDataRate rule (in:0): min=120, this connection=0, c=2**.1**.1*7.1*5


```

**Comment by JoshWho** [comment]
That is just Apache. This is nginx doing it.

**Comment by DanielnetoDotCom** [comment]
Apache is validating your key, that explains a lot

**Comment by JoshWho** [comment]
> Apache is validating your key, that explains a lot

Then how is it telling NGINX to deny?

**Comment by DanielnetoDotCom** [comment]
![image](https://github.com/user-attachments/assets/06baaef4-6960-4025-9476-73d3bb684aaf)


Disable or correct configure  mod_qos  and it will work

**Comment by JoshWho** [comment]
Everything is good it seems now, could have been that qos all along. That is a bummer, it does so good stopping slow loris attacks.

**Comment by JoshWho** [comment]
I will wait for there to be no more lives and uncomment that restart nginx and test it later.

**Comment by DanielnetoDotCom** [comment]
> Everything is good it seems now, could have been that qos all along. That is a bummer, it does so good stopping slow loris attacks.

Maybe you can just increase some values

Lower the minimum data rate threshold to accommodate slower connections. For example, in your Apache configuration:
apache

````
QS_SrvMinDataRate 60
````

**Comment by JoshWho** [comment]
It was the download protection the whole entire time. I disabled it now all videos play for me now.

**Comment by DanielnetoDotCom** [comment]
Do not forget to put back the `auth_request /auth_key_check;`

it is what make your live secure
