### ISSUE TITLE
Another video didn't generate the mp3 and when I try to manually do it it errors

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9652]
![image](https://github.com/user-attachments/assets/b653259b-df9e-4786-969c-00f545677395)

Video is https://ftjmedia.com/channel/DaveGahary/video/.fZwRlQC8kGqwFbhlzo6VuQ/thanksgiving-2024-special-broadcast

**Comment by DanielnetoDotCom** [comment]
Hi, I found the issue and sent you an update, you should be good now.

**Comment by JoshWho** [comment]
Thank you. Do I need to manually run it or will cron get it?

**Comment by DanielnetoDotCom** [comment]
It is runing now, but not in a cron

![image](https://github.com/user-attachments/assets/ae84d01c-e294-4927-a894-1a8ad755e698)

**Comment by JoshWho** [comment]
I was meaning for the other videos that also never generated it.

**Comment by DanielnetoDotCom** [comment]
it should create now, I cant check now if there is a crontab for it, but was a bug in the protection for it. but now it should be good to go.

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom

**Comment by JoshWho** [comment]
Is there anyway to tell FFmpeg to do 1 file at a time. This is running 5 of them now server is maxed 100%cpu in use site is not really functional at the moment.

**Comment by JoshWho** [comment]
If you put -Nice

**Comment by JoshWho** [comment]
I already have the cpu limit installed.

**Comment by JoshWho** [comment]
> If you put: `nice -n 19 cpulimit -l 30 -i -- `before the ffmpeg command it will only use 30% the cpu and also not make it number 1 priority.

So if another service is called like Apache for example it will allow Apache to get as much cpu as it needs

**Comment by JoshWho** [comment]
This is the real solution to not letting the main site go to crash by no CPU available.
