### ISSUE TITLE
Back to Top button

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#9656]
Hi something small that is missing and could be effective
Back to Top button
Thanks Daniel

**Comment by DanielnetoDotCom** [comment]
what exactly do you mean?

**Comment by eitanwa** [comment]
A button that scrolls the page back up

**Comment by JoshWho** [comment]
Problem would location for the button, it will cover the Navigation bar or the chat.

**Comment by eitanwa** [comment]
I don't know what you used I tried many things too
There are new things all the time
I'm currently testing one hovering right now it's on the bottom left
You can exclude certain pages or alternatively decide which pages to include
This is important mainly for the pages of the articles and/or texts in my opinion
My problem for now with it is the double i frame pages
But I'm sure there is a solution to this
Prefers to have one in the platform and not an external implementation and believes that Daniel is capable of everything
I will let you know if it works properly
And let's see what Daniel says 
tnks 4 replying 
@JoshWho

**Comment by KrzysioMisio** [comment]
[DanielnetoDotCom](https://github.com/DanielnetoDotCom)  I think that's what it's about on my site
you scroll down the page and a back to top button appears
look on my site in the bottom right corner
https://www.youhippo.com/

**Comment by DanielnetoDotCom** [comment]
Please chek this TopMenu update, it includes the back to top button.

the button can be disabled in the parameters

**Comment by eitanwa** [comment]
Do you mean in the TopMenu  plugin?
Because I don't see an update

**Comment by DanielnetoDotCom** [comment]
Yes, you must make a git pull first

**Comment by eitanwa** [comment]
You are the best of all Daniel
exactly in the right place @JoshWho 
it disappears under the floating menu and appears only on pages that need great
Excellent especially for posts
thanks
