### ISSUE TITLE
Unverified emails are able to chat in our live streams. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9662]
Just noticed unverified email users able to chat in our live streams we need that somehow disabled and for them to verify their email first.

**Comment by eitanwa** [comment]
I wanted to ask you
The new feature The reference to the link after the live broadcast
 works for you?
  
 @JoshWho JoshWho

**Comment by JoshWho** [comment]
> I wanted to ask you The new feature The reference to the link after the live broadcast works for you?
> 
> @JoshWho JoshWho

Not sure what you mean. Can you please explain a little more about your question.

**Comment by eitanwa** [comment]
Yes, of course, thanks
Sending a screenshot
If I'm not mistaken, this is the interface you requested (your idea)
Either way, it's a significant addition
For now, it doesn't work for me

![image](https://github.com/user-attachments/assets/4a57c18f-fdb0-4656-b7e3-71bb09767ced)

![image](https://github.com/user-attachments/assets/ca31eaa5-4b74-4e1c-abaf-edcb58ac3a66)

Thanks Josh

@JoshWho

**Comment by eitanwa** [comment]
On the same subject of live broadcasts and permissions
Even if the live broadcast is set to hidden and/or locked with a code
it still appears in the big video

**Comment by DanielnetoDotCom** [comment]
Regarding the unverified, you should now allow them to login

if they login they can chat and comment videos. 

![image](https://github.com/user-attachments/assets/3648391e-fe5b-4d21-a9fd-fe8928826442)

**Comment by JoshWho** [comment]
That is not good because it locks out people from being able to verify.

**Comment by DanielnetoDotCom** [comment]
They do not need to login to verify

the verification email will be sent on each login attempt. 

once they click in the email he should be verified

**Comment by JoshWho** [comment]
What if they used the wrong email and need to change it?

**Comment by DanielnetoDotCom** [comment]
They can create a new account or contact you to change the email
