### ISSUE TITLE
Up Next does not work as expected

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#9663]
Hi Daniel, how are you?

This problem is very old, I wrote to you about it before, probably I was not understood
Anyway, there is a very strange bug here (maybe this is the reason)
I will try again because in my humble opinion it is very important

The up next button does not work as expected
1) The auto play works the same way in off or on mode
It shows the videos according to some sort of order, which by the way I would be happy to know what it is and whether it is possible to control it 
according to what I understand is a random order

When the button is off, it should display the videos according to one of the settings
And it doesn't happen
 As I wrote, it always works the same way (autoply)

A very important thing and this is the strange part
When you are logged in to the system, it will always show you 2 videos After you click next from any video you choose in the system (the same 2 first videoes ever uploaded to the system) in a loop, So you must check at the same time as not logged or not admin

In addition, there are parameters here that may be related to the topic

If this feature (picture)
![image](https://github.com/user-attachments/assets/1abddc6e-5b6b-4fa7-ab49-44d55da4e4bf)

controls this part, so it doesn't work changing the plugin doesn't affect the area shown in the image
![image](https://github.com/user-attachments/assets/cf646f78-0e1f-48d3-ba1a-bb81609c92e9)

PS This is a problem that exists in all our systems

And if it is possible to add here also the channels I subscribe to (following)
It could be great

![image](https://github.com/user-attachments/assets/7dbb4482-f41c-4ce4-9235-984e2b3ec776)

I hope I was clearer this time
As usual, thanks for everything

@DanielnetoDotCom

**Comment by DanielnetoDotCom** [comment]
Can you reproduce it on demo site?

FYI the sort and the autoplay is saved on a cookie, so once your user choose something that browser will remember his option, so this is not a BUG

try to clear your cookies or a incognito browser

**Comment by eitanwa** [comment]
Yes I checked the same thing on the demo site
Same thing on our sites
I checked on other friends' sites from here the same

 (about this-sort and the autoplay)
 thanks

**Comment by DanielnetoDotCom** [comment]
Sorry, I need a step by step how to reproduce it

**Comment by eitanwa** [comment]
Just press the next button on the player itself
and see how the player reacts
Do it also as a user who is not registered or not logged in (name and password)
in order for you to see the differences

**Comment by eitanwa** [comment]
not logged in

![image](https://github.com/user-attachments/assets/028a3600-e662-4138-b1c7-7b0f2ea299ab)
Click Next in the player
Look at the "behavior" of the video


logged in 
![image](https://github.com/user-attachments/assets/291db6d8-d9e1-46d8-ba2a-06679b7c15d8)
Look at the "behavior" of the video

and enable/disable automatic activation
![image](https://github.com/user-attachments/assets/f8820f14-dcb9-4c43-acb3-e200a3891a0e)

And you will see that it has no effect

**Comment by eitanwa** [comment]
And another important thing
All of this ultimately affects the big live video
When bookmarking favorite videos
These are the videos that will appear in the big video
And not the ones that were uploaded recently which I assume is the default

Maybe it's related to the settings that there are two large videos?

Summary:
In my humble opinion this is how it is expected to react
Automatic play: random video or preset option which is excellent
Turning off automatic activation: preset + choice option of the viewer

In the big (live) video (in the gallery plugin) the option of determining what will be shown
Right now it's either video or live
But (as I wrote before) once you set favorites it will display the favorites
(and not as defined in the plugin)

**Comment by DanielnetoDotCom** [comment]
Please check if this update resolves the issue.

**Comment by eitanwa** [comment]
nop
the same

**Comment by DanielnetoDotCom** [comment]
do you have suggested videos?

I am not sure when and why I did that but the autoplay was getting the suggested only if you have any. 

I removed that for now, untill I remember why I did that.

**Comment by eitanwa** [comment]
I tried both
If I didn't set suggested
It will repeat in a loop the first two videos that are in the system
(the first ever uploaded)

If I set suggested it will return in the same way in a loop on 2 suggested

**Comment by eitanwa** [comment]
I'll wrap it up
When the user is not logged in
Autoplay will work randomly
And there is no meaning to turning it off (it will not be the choice defined in the system or the user's determination)
act the same 

When the user is logged in (also admin)
The autoplay will show the same two videos explained earlier
And the same thing as soon as you turn it off (autoplay)

This actually stops the natural flow of the system
in each case
Therefore, at the moment it is better that the user is not logged in
 Because in such a situation at least there is a flow of videos (random)

**Comment by eitanwa** [comment]
Hi Daniel, I updated the previous message
and you should read it

I must point out that it is not easy to describe this problem
because it depends on a lot of parameters In different situations
Mainly the matter of whether a user is logged in or not
So sorry if I wasn't precise

**Comment by eitanwa** [comment]
Another interesting thing to note
When a video ends naturally
(just scroll to the end)
Nothing happens

Maybe the autoplay is blocked by the browsers themselves?
Like Brave, for example, blocks the possibility of ads

**Comment by DanielnetoDotCom** [comment]
can you please screencapture you reproducing it on demo site?

I could not reproduce it here

**Comment by eitanwa** [comment]
up next 

https://alive528.com/video/23951

**Comment by DanielnetoDotCom** [comment]
I saw your video and it is working as expect. when you click next it goes to whatever is set in the autoplay not the next one on the list.

for example embed videos does not have that list and can have the next button.

**Comment by eitanwa** [comment]
Actually that's the only thing it doesn't do

This is also very noticeable on the demo site
It is fixed by date from new to old, and when you click next
You can clearly see that it goes between different dates (years)
I think it goes randomly

And what about the difference between logged in and not
Didn't you see the loops?

Look there are a lot of additional parameters here
I was sure we would get to them by now
But as long as you don't see the problem
I don't know what to say
I don't understand how you don't see it
It's really noticeable

And this is important, it just stops the entire flow of videos
I know it can be confusing switching between this Next
It made me dizzy trying to explain it to you
But please try to check it again

Maybe I'll make another video?

**Comment by DanielnetoDotCom** [comment]
the next button has nothing to do with the list on the right side. 

it will not follow that.

**Comment by eitanwa** [comment]
So according to what I understand now
I have to choose "suggested" !!!
This is the mechanism (the playlist)
And those "suggested" will work according to what is predetermined in the category (plugin)
Otherwise the system does not know which video to choose
if it is true
So maybe I'm starting to understand how it works
And that will complete the picture for me

According to what you say, the list on the right is not relevant
So what does turning off autoplay mean?

And what about the loops?
Why when a user is logged in?
Is it playing 2 videos in a loop?
do you see that

And why when a video ends it just stops and does not move on?

**Comment by DanielnetoDotCom** [comment]
If you want to play something in sequence you should use a playlist.

The loop should be already fixed

it will move on only if the autoplay is enabled (checked)

**Comment by eitanwa** [comment]
I finally found the problem

Now it works beautifully

But only when the user is not logged in
When the user is logged in it continues to loop over two videos
I checked it again on the demo site as well

Thanks Daniel

> The loop should be already fixed

I finally found the problem

Now it works beautifully

But only when the user is not logged in
When the user is logged in it continues to loop over two videos
I checked it again on the demo site as well

Thanks Daniel

**Comment by DanielnetoDotCom** [comment]
I did tested logged and it works fine. 

maybe something with a specific user

what user on demo site you are testing?

**Comment by eitanwa** [comment]
eitanwa@gmail.com
eitanwa

Just keep in mind that this also happens on our website

**Comment by eitanwa** [comment]
https://github.com/user-attachments/assets/69269e56-3552-41db-b24c-433bf01f6d7c

**Comment by DanielnetoDotCom** [comment]
Tutorials site did not have the update I sent above

**Comment by eitanwa** [comment]
![עיצוב ללא שם (11)](https://github.com/user-attachments/assets/94408bc8-a0cc-4021-89f6-97f0a9cae703)

Thanks Daniel
Finally it works
I can't find better words than thank you!!
express my appreciation to you
Beyond the work of art you have created here
Your patience is above all


The system looks stunning
the best in the world


I wish you all the best in the world
eitan
