### ISSUE TITLE
Download mp4 converts video with no sound

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9665]
This show never made a mp4 and mp3 for it but still lets me generate the mp3 and mp4.
https://ftjmedia.com/channel/DaveGahary/video/.cjDVjbjcn_s4ZAwZ9jSrbw/the-dave-duke-call-in-show-december-1-2024-001

mp3 works fine but the video mp4 has no sound and I generated it twice. 

and the page stays stuck like this after generating the mp4

![421926c4-9035-4b70-98e4-7ab5618a184b](https://github.com/user-attachments/assets/c63099e8-66e6-4c6b-88ad-842257b9a044)

**Comment by DanielnetoDotCom** [comment]
what button exactly did you click?

**Comment by JoshWho** [comment]
The download mp4 button under it.

**Comment by DanielnetoDotCom** [comment]
can you please screenshot what exactly?

**Comment by JoshWho** [comment]
![d6f5afff-22c4-49ed-bce0-5c92ec6d0ceb](https://github.com/user-attachments/assets/ed90d55f-5e07-415b-8573-28d01078a4c5)

**Comment by JoshWho** [comment]
Click mp4 and watch what it does and see if the video has audio

**Comment by JoshWho** [comment]
That video also never auto generated the mp4 and mp3 so it keeps wanting to generate it instead of just saving it. 

![2d22ee82-77ab-4af4-b152-ac8314ff0a94](https://github.com/user-attachments/assets/edddadf2-e3db-4dd7-a361-13d22d1d95aa)

**Comment by DanielnetoDotCom** [comment]
I am not sure what happened, but I delete the mp4 and mp3, and it is converting again. 

soon the download will be available
