### ISSUE TITLE
Message all users still has a default template the says Message from site. Needs to be more personalized to the channel owner. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9666]
Needs to say from the channel name and not a message from the website. 

Talking about the subject line it sends. 

![48f98dfd-08f4-4bcc-be39-82309c20e98f](https://github.com/user-attachments/assets/a2efca5d-8096-44f6-8c64-09e696d29c53)

**Comment by DanielnetoDotCom** [comment]
This update should improve the template, but the subject still the same
