### ISSUE TITLE
Need help finding out what is using 300 mbs every few seconds

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9672]
![f70cb0a3-76ad-49f4-b375-8e839038a0ed](https://github.com/user-attachments/assets/e1ee16a5-26cb-4e77-9927-fe968a5fe405)

It is showing it is the upload but there is no streams going Not sure what this is.

**Comment by JoshWho** [comment]
There is now a stream that just started but I was watching this be like this for weeks.

**Comment by DanielnetoDotCom** [comment]
Sorry what?

**Comment by JoshWho** [comment]
There is something always sending out from the server that uses 300 mbs and I cant figure out what keeps doing it or if this is some kind of attack we are not seeing.

**Comment by DanielnetoDotCom** [comment]
I do not know how you checking this and I do not know if this is not a false alert. 

for me all is working fluid from my end.

**Comment by DanielnetoDotCom** [comment]
Just checked in all 3 devices I tested last time (mac iphone and pc)

all fluid and fine and all playing in HD

**Comment by JoshWho** [comment]
Yes it is working great. It is just the network data I am seeing.
