### ISSUE TITLE
I have other mobile users seeing the loop I was seeing earlier today. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9674]
Mobile browsers for some reason are playing the beginning of the buffer of the live stream and not letting you go to the real time when the stream first started.

**Comment by JoshWho** [comment]
Maybe need to add a header to the live stream pages that forces browser not to use cache on it.

**Comment by JoshWho** [comment]
![808a7bb2-891b-4b45-97ae-8cca9b378d2f](https://github.com/user-attachments/assets/ba65bf37-df12-4c8e-9b53-9b95c3f3c366)

Seems to get solved by forcing the cache cleared

**Comment by JoshWho** [comment]
Maybe if adding the no cache tags to the live video player page

```
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />
```

It saying the best it by using server-side HTTP headers but I do not think you can make that work for specific pages. More of a global thing.

**Comment by DanielnetoDotCom** [comment]
The playlists are not cached 

At least not in the CDN , unless you added something on the server to cache it

**Comment by JoshWho** [comment]
No it is Just how chrome is trying to cache things now. Those headers will tell chrome not to do that

**Comment by JoshWho** [comment]
Wonder if just adding random string to the end like ?1234 would solve this. That is what use to work for the Cloudflare cache thing a long time ago. Might work the same for Chrome. 

example instead of https://ftjmedia.com/live/0/Davis/1

make it https://ftjmedia.com/live/0/Davis/1?123randomstring

**Comment by JoshWho** [comment]
The re encoding was the best solution I have ever seen for the live streaming here. Just need to now make sure Chrome doesn't try caching the page. It is just like how Cloudflare Speed cache use to break everything and now Chrome is doing the same thing. This will tell it to be bypassed. 

> It is caching the playlist m3u8 files at the start of the stream and some browsers keep looping those and not pull from the real playlist files. Now that the files are so small with re encoding it the browser assumes it is static and caches it.
> 
> Maybe if adding the no cache tags to the live video player page
> 
> ```
> <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
> <meta http-equiv="Pragma" content="no-cache" />
> <meta http-equiv="Expires" content="0" />
> ```
> 
> It is saying the best setting is using server-side HTTP headers like:
> 
> ```
> <IfModule mod_headers.c>
>   Header set Cache-Control "no-cache, no-store, must-revalidate"
>   Header set Pragma "no-cache"
>   Header set Expires "0"
> </IfModule>
> ```
> 
> but I do not think you can make that work for specific pages. More of a global thing.
> 
> Reasons for Buffering loop Issues: Browser Caching: Even with live streams, browsers might cache certain parts of the stream if they mistakenly treat it as a static resource.

**Comment by JoshWho** [comment]
> I cannot confirm that is the issue, and I cannot change something just to try.
> 
> I am watching this live now to see if this will happen to me.
> 
> I am trying different devices.

I can't guess how it plays the start of the stream if I only have the playlist is set for 20 minutes yet they see the begging that started an hour ago. Has to be cache.

**Comment by DanielnetoDotCom** [comment]
I guess it is something when the player changes the playlist automatically, probably something on videojs

I will try to update videojs , if it fails I will force only one resolution 720p only

**Comment by JoshWho** [comment]
> I guess it is something when the player changes the playlist automatically, probably something on videojs
> 
> I will try to update videojs , if it fails I will force only one resolution 720p only

I think Apple and slower devices need the 480

**Comment by DanielnetoDotCom** [comment]
lets see the videojs update, 

I want to avoid witch playlists on live, so I think 720 is better, the problem before was the high bitrate

**Comment by DanielnetoDotCom** [comment]
Videojs is up to date now

I guess was an issue on it.

I was able to reproduce it on my mac, but now after the update it is gone

of course they will need to refresh the page

**Comment by JoshWho** [comment]
> Videojs is up to date now
> 
> I guess was an issue on it.
> 
> I was able to reproduce it on my mac, but now after the update it is gone
> 
> of course they will need to refresh the page

Excellent. They will that is what most do to catch up to the stream so should resolve itself now 

Thank you @DanielnetoDotCom

**Comment by JoshWho** [comment]
Now it is jumping around for me. Skipping backwards and then going back to the end

**Comment by JoshWho** [comment]
It was the end of the stream and they was closing out and then it went back 2o minutes.

**Comment by JoshWho** [comment]
Can't tell now cause it has ended.

**Comment by DanielnetoDotCom** [comment]
make sure you clear your cache, once you can reproduce tell me the device

**Comment by JoshWho** [comment]
Looks like it is Good to go. Thank you @DanielnetoDotCom

**Comment by JoshWho** [comment]
It is still lopping for me now on this stream https://ftjmedia.com/live/0/BaalBusters/1

**Comment by JoshWho** [comment]
This stream just buffers https://ftjmedia.com/live/0/FLOOD/1

**Comment by DanielnetoDotCom** [comment]
https://github.com/user-attachments/assets/ac345858-2e20-47eb-8817-94767fdbef28

It plays fine here on mobile

**Comment by JoshWho** [comment]
It might have been a DDoS causing it. I just enabled Crowdsec security. I had it turned off for the last 3 days to make sure it wasn't that causing it but now it is needed.

**Comment by DanielnetoDotCom** [comment]
Maybe you can fine tune it and keep it enabled

**Comment by JoshWho** [comment]
> Maybe you can fine tune it and keep it enabled

Yes definitely.

**Comment by JoshWho** [comment]
Try Floods stream again it just started buffering again. Might be something else

**Comment by JoshWho** [comment]
Might be right about just having the 720 bitrate enabled only

**Comment by DanielnetoDotCom** [comment]
Tested on mobile and it is not buffering 

Are you sure this is not buffering just for you?

Last time your buffering was because of Crowdsec

**Comment by JoshWho** [comment]
I am thinking about if there is another attack that is stronger for some reason the 480p is not in sync, it always plays at the start of the stream. 

It only happens when it makes you watch 480p and 480p keeps starting at the beginning of the stream or 20 minutes into it some times.

**Comment by DanielnetoDotCom** [comment]
Again it is playing fine here

**Comment by JoshWho** [comment]
> Again it is playing fine here

You didn't get to see it when it was under attack. once forced to watch 480p it doesn't even let you fast forward.

**Comment by JoshWho** [comment]
If that could be fixed it could stay but there is something wrong with it.

**Comment by DanielnetoDotCom** [comment]
I cannot do it now but yes make it 720 only may resolve it

**Comment by JoshWho** [comment]
I will later once these streams end and please check it later when u can to see if I done it right. just incase.

**Comment by JoshWho** [comment]
I still also think because 480p is so small is w3hy chrome is caching and the no cache headers might fix that

**Comment by DanielnetoDotCom** [comment]
I’ve updated all live streams to 30 FPS (`-r 30`), which could help address the unalignment issue. For some reason, when the player switches to 240p, it may cause slight frame timing differences, possibly due to how the `-2` scaling interacts with other resolutions.  

When you can, please restart Nginx. This update might resolve the issue without disabling other resolutions. Let me know how it works!

**Comment by JoshWho** [comment]
It has been a busy day people are still streaming As soon as I get a chance I will restart it.

**Comment by JoshWho** [comment]
Restarted. All good now.

**Comment by DanielnetoDotCom** [comment]
If stil an issue we will enable 720p only
