### ISSUE TITLE
The plug-ins have all exploded.

### ISSUE THREAD

**Issue by ManTatC** [WWBN/AVideo#9681]
As I said in the title, I wanted to make my own idea of exchanging decorations based on the user's forum coins and planned some channels to get them, but after I uploaded him as a .zip file all the plugins, including him, disappeared, but the functionality works fine, so I'm curious as to what went wrong
Ubuntu 24X. 
Tencent Cloud Server
[EcoinAvatarStore.zip](https://github.com/user-attachments/files/18047854/EcoinAvatarStore.zip)
I named my coins as the "Ecoins"

**Comment by ManTatC** [comment]
Also, I don't have a backup, I tried logging out as well as refreshing, and all of this was written by ChatGPT O1 since I've only been in web development for a total of 3 days, which is a side note to Avideo's ease of deployment

**Comment by milehighkaraoke** [comment]
It is probably a good idea to let @DanielnetoDotCom inspect your code before you try and implement it.

**Comment by DanielnetoDotCom** [comment]
you may what to chaeck your avideo logs

but if you use AI to create your plugin it probably create all wrong

YOU MUST KNOW PHP

try to follow this https://github.com/WWBN/AVideo/wiki/How-to-code-a-AVideo-Platform-plugin

**Comment by walt93** [comment]
Daniel is correct about the LLM. I have been coding extensively for the last four months with Claude Sonnet (don't use GPT 4, o1 can be made to be good if you really know what you are doing e.g. prompt it with proper and correct engineering). 

But Claude falls on its face with PHP, I've tried to work on AVideo code with it and the results are ... terrible. If you need to do things with AVideo, I've had success with a) understanding the data model and b) writing python or react code to talk to the mysql database. Claude is phenomenal with those languages. HTH

**Comment by ManTatC** [comment]
However, I believe I know some basic concepts and I used the o1 version. Anyway, the final solution is just delate all the data and rebuild the whole system. Luckily, I just started my works, so it no a big deal for me to do that. Thanks you for all the answers under this questions!
