### ISSUE TITLE
Jitsi Meet Call in Shows the persons telephone number and is a privacy issue

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9683]
So when you give the user a option to calling it shows their telephone number as their username on Jitsi

To hide telephone numbers of participants joining a Jitsi Meet call via Jigasi (the SIP gateway for Jitsi), there are a few steps you can consider based on the available information:

Modify Display Names:
If someone is brought into a Jitsi room by calling them through Jigasi, they typically join with their dialed number as their display name. To hide this, you can manually change the display name of the participant once they have joined. However, this would require manual intervention for each participant.

Customize Jigasi Configuration:
Jigasi can be configured to use a generic or custom name for participants instead of their phone number. This involves modifying the configuration files for Jigasi. Look into the Jigasi documentation or configuration files where you might find options to set a default name or hide the actual phone number. For example, setting up a custom display name for all SIP participants in the configuration could be an approach. Unfortunately, specific steps or exact configuration lines are not detailed in the provided results, suggesting you might need to delve deeper into Jigasi's documentation or community forums for precise settings.

Jigasi's Privacy Concerns:
There have been discussions about privacy concerns with displaying phone numbers in video calls. While the exact method to hide numbers wasn't detailed, the community has expressed interest in this feature, suggesting you might find more detailed guidance or workarounds in community discussions or by proposing changes directly to the Jitsi developers through their forums or GitHub.

Using External Services or Plugins:
Although not directly mentioned in the provided results, you might explore integrating third-party services or plugins that could manage participant identities more privately. This would involve extending the functionality of Jitsi Meet beyond its default capabilities, possibly through custom development or integration with services like Twilio, but specifics would depend on available plugins or APIs.

**Comment by DanielnetoDotCom** [comment]
I do not know this feature can you please screenshot?

also I can only update something if nginx offer this option, otherwise I cannot do it.

**Comment by JoshWho** [comment]
Watch this video you will see when I call in it uses my phone number as the username in the meeting. https://ftjmedia.com/channel/Joshwho/video/.t_-JBUfYXLoQcUn3aWe6nA/ftj-live-conference-testing-telephone-call-in.-ftj-pro-feature

**Comment by JoshWho** [comment]
![image](https://github.com/user-attachments/assets/f46b4ab6-feed-4e92-a62b-d78beaed4e79)

**Comment by JoshWho** [comment]
![upscaled-2x-80381778-4423-44cf-ab33-9c27db9da98a](https://github.com/user-attachments/assets/98479e2a-56a5-4d57-ada3-06361aded6ae)

**Comment by DanielnetoDotCom** [comment]
the thing is, does jitsi allow us to change it?

**Comment by JoshWho** [comment]
> the thing is, does jitsi allow us to change it?

It says it can be done or replaced with a generic name.

**Comment by JoshWho** [comment]
Not sure. I was thinking it was in the config for usernames maybe but not sure never seen what the config all has in it.

**Comment by DanielnetoDotCom** [comment]
To be able to modify it must be some instructions on Jitsi documentation.

AI always say it is possible and easy, but not true.

**Comment by JoshWho** [comment]
> Nevermind, css will not work

Thats a bummer

**Comment by JoshWho** [comment]
It might actually be possible

.```
css-5bay1g-displayName {
    font-size: 12px;
    line-height: 16px;
    font-weight: 600;
    letter-spacing: 0.16px;
    color: rgb(255, 255, 255);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```

element

`<span class="displayname css-5bay1g-displayName" id="participant_3a6aa720_name">AUSTIN       TX (+15129533820)</span>`


```

.css-7vcbwr-nameContainer > div {
    display: flex
;
    overflow: hidden;
}
```

Problem though I think it will hide all participants names.

**Comment by JoshWho** [comment]
I just opened a thing on Jitsi community here https://community.jitsi.org/t/privacy-issue-with-call-in-participants-how-to-hide-their-telephone-number/135902

**Comment by DanielnetoDotCom** [comment]
Ok, I see currently it is not possible

**Comment by JoshWho** [comment]
> Ok, I see currently it is not possible

U think they would have thought of this.

**Comment by JoshWho** [comment]
They just replied back with this.

![e3d3b73d-0c04-43ad-9684-73df8dc2165a](https://github.com/user-attachments/assets/ecb21968-3bd8-4a3a-afc4-a035c9f00dcc)

**Comment by DanielnetoDotCom** [comment]
that is the thing, how to build a custom prosody module

I will research but not sure If I can do

**Comment by DanielnetoDotCom** [comment]
Can I play around with your meeting?
It may take a couple of days

**Comment by JoshWho** [comment]
> Can I play around with your meeting? It may take a couple of days

Yeah no probs. Just let me know if it won't be operational at some point so I can tell host it is down.

**Comment by DanielnetoDotCom** [comment]
I may need to rebuild it a couple of times, so it will be unstable and non operational

**Comment by DanielnetoDotCom** [comment]
Is that ok? it is 5PM here now, will you use it tomorrow between 8 AM and 1 PM (my time)?

**Comment by JoshWho** [comment]
> Is that ok? it is 5PM here now, will you use it tomorrow between 8 AM and 1 PM (my time)?

That will be fine. I posted to them it is being worked on and will let them know when it is ready to use again.

**Comment by JoshWho** [comment]
Also see if you can have the call be accepted like the web guest are where it shows the moderator they are calling in and have to click approve for them to join. 

Currently when someone calls they just pop in the room announced

**Comment by DanielnetoDotCom** [comment]
Not sure if I can do that. for now I am just trying to hide the phone number

**Comment by DanielnetoDotCom** [comment]
I did

our custom meeting now mask the phone numbers

![image](https://github.com/user-attachments/assets/910c67cf-ec63-4ce9-a232-80bf51ae41ea)
