### ISSUE TITLE
Wonder what keeps stopping the auto mp3 generator and mp4 from working?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9696]
Another video that never generated its files. I do not understand what it is u delete to make it regenerate the mp4 and mp3 files.

![f3ea4039-d07e-46c5-bdf0-8f2849d741fc](https://github.com/user-attachments/assets/d02b190a-7f35-4048-993f-fc9e2eb6825e)

https://ftjmedia.com/channel/GiuseppeVafanculo/video/.9YdtKwCdoVziVMPybu1giw/the-sane-asylum-291-based-monday---09dec24-on-09-dec-24-12-00-13

**Comment by DanielnetoDotCom** [comment]
Not sure yet

but on this MP4 was fine, I could download with no problem
mp3 was corrupted I forced it to regenerate

I am still investigating why is it generating corrupted mp3

**Comment by JoshWho** [comment]
Did it again here for vid https://ftjmedia.com/channel/GiuseppeVafanculo/video/.DXcNpcrToO9vb3tofAcZTA/the-perfect-triangle-220---13dec24-on-13-dec-24-12-01-24

![download (34)](https://github.com/user-attachments/assets/739e7072-055d-4e12-9a5f-2d78eef2c6cf)

**Comment by JoshWho** [comment]
Maybe there could be some fail check that detects this and forces it to generate again or something.,

**Comment by JoshWho** [comment]
If I see a video that doesn't generate these there should be a button to fix it.

**Comment by JoshWho** [comment]
![92c2736d-c46b-48c5-a693-eb46f504e21b](https://github.com/user-attachments/assets/f83a83e3-5b1a-4249-a221-db65c51bfd17)

https://ftjmedia.com/channel/DaveGahary/video/.gVOt0EsRcWex5ScpHQGtRg/the-dave-duke-call-in-show-003

**Comment by JoshWho** [comment]
Tonight it is a lot of videos not generating the mp3

**Comment by DanielnetoDotCom** [comment]
This video download the mp3 fine to me.

convert mp3 takes some time, you need to wait it.  it is not instantly created

**Comment by JoshWho** [comment]
That video should have a stored mp3 file shouldn't have to keep regenerating it. Notice there is no download bar under the video in the screen shot while the others has one.

**Comment by JoshWho** [comment]
That is what tells me something didn't self generate is when I do not see that download button.

**Comment by JoshWho** [comment]
It is trying to generate a file that doesn't exist yet basically.

**Comment by JoshWho** [comment]
![a8b26379-5481-4d4b-b581-038c43c53602](https://github.com/user-attachments/assets/ddf4adee-e609-4a91-b203-96ee64b04c1f)

**Comment by DanielnetoDotCom** [comment]
I sent you updates, can you please check again?

**Comment by JoshWho** [comment]
So far so good. Will close this for now. Thank you.
