### ISSUE TITLE
I have a user that says his videos keep getting switched to Premium members only. How can I turn that feature off completely?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9697]
![3d3038c2-5c0c-4ade-8da6-abbc4fe6a82a (1)](https://github.com/user-attachments/assets/719c47fe-404a-40ff-8bac-caf41f735e1f)

Just make this not an option anymore. How can I turn it off and force them to stay public?

**Comment by JoshWho** [comment]
I think it is user error so I just want to force it to not be an option.

**Comment by DanielnetoDotCom** [comment]
Sorry I do not have this option

**Comment by JoshWho** [comment]
He said it just happened again

![40a477bc-5320-4c17-8690-def695f1c305](https://github.com/user-attachments/assets/60950ca1-4d8a-4c14-a917-5134c9435708)

![99c7e3a1-88ea-4dc7-bfd1-12cad7630c31](https://github.com/user-attachments/assets/14f2b5d2-cfdc-4f5f-a187-69d978ee300a)

Why would his videos default to this?

**Comment by JoshWho** [comment]
It is like somehow he is defaulted to Premium Members only and I see no way to fix this.

**Comment by DanielnetoDotCom** [comment]
He has a user group selected on this live 

then you selected hideUserGroups on live plugin 

the video was a recorded live and the recoded live follow the usergroup in the live. 

![image](https://github.com/user-attachments/assets/7a1813f2-d427-436f-9aad-6039bf14a982)

![image](https://github.com/user-attachments/assets/cb12f31d-3b4b-4c29-b4ef-13ba9287fc33)

it is fixed for you now.

**Comment by JoshWho** [comment]
Thank you @DanielnetoDotCom
