### ISSUE TITLE
For some reason when you share a link with a video title that has a hashtag it stops the rest of the title in share. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9699]
Example:

Try to share this link on twitter aka X: https://ftjmedia.com/channel/GiuseppeVafanculo/video/.9YdtKwCdoVziVMPybu1giw/the-sane-asylum-291-based-monday---09dec24-on-09-dec-24-12-00-13

Anything past the pound sign aka # stops showing in the title of the video share and including the video link. 

This is the link here https://ftjmedia.com/channel/GiuseppeVafanculo/video/.9YdtKwCdoVziVMPybu1giw/the-sane-asylum-291-based-monday---09dec24-on-09-dec-24-12-00-13  Try to share it on X and you will see what I am saying

![-7-Home-X-12-11-2024_02_12_AM](https://github.com/user-attachments/assets/5949037a-baa4-4f46-88e5-c92c48772c32)

**Comment by DanielnetoDotCom** [comment]
I am not sure what do you mean, here works fine

![image](https://github.com/user-attachments/assets/1816dea3-3453-4f51-800a-1d829efdf8a3)

**Comment by JoshWho** [comment]
No click the Share button for X and you will see it.

**Comment by DanielnetoDotCom** [comment]
please try now

**Comment by JoshWho** [comment]
> please try now

That did the trick. Thank you
