### ISSUE TITLE
VideoHLS - Codec Selector

### ISSUE THREAD

**Issue by JacekLange** [WWBN/AVideo#9703]
Hi there, Daniel

Could you add a variable in the VideoHLS plugin in autoConvertToMp4, where I can set "-c:v h264_nvenc" instead of "c:v libx264" (like you did in Rebroadcaster?

**Comment by DanielnetoDotCom** [comment]
Make a git pull and check the CustomizeAdvanced -> ffmpegParameters

**Comment by JacekLange** [comment]
Thanks for your quick response.
Works great. :)
