### ISSUE TITLE
AD_Overlay stopped working

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#9704]
Hi, 
I now see that after the last update AD_Overlay stopped working
Worked fine before

and also VideoLogoOverlay The associated link
not responding

Both worked fine before
On my site that is not updated both still work

thanks daniel

**Comment by DanielnetoDotCom** [comment]
Please share more details what do you have and what you are expecting. also provide the js console log

**Comment by eitanwa** [comment]
> Please share more details what do you have and what you are expecting. also provide the js console log

sorry you are right
As for the ad, it does not appear

Regarding the logo, the link provided in the plug-in itself does not respond

**Comment by eitanwa** [comment]
![image](https://github.com/user-attachments/assets/4e3eae9c-559c-4dfe-b49e-45521983799e)

**Comment by DanielnetoDotCom** [comment]
Sorry what plugin is that?

what is your issue?

I am totally confused now

**Comment by eitanwa** [comment]
Sorry maybe because I was talking about two different plugins
I just checked the site after the update and noticed both

1) ad overlay:
The ad does not appear

2) VideoLogoOverlay:
The link provided in the plugin did not click
And the logo image uploaded in the plugin is not displayed

I accidentally sent a log file earlier from our website that is not updated
This is from the updated one

But looks the same


![image](https://github.com/user-attachments/assets/a1509e2a-ddbc-4da2-9547-4098769e944e)

**Comment by eitanwa** [comment]
![image](https://github.com/user-attachments/assets/3924ea30-55fb-4203-9970-609f1fbdf6ec)

![image](https://github.com/user-attachments/assets/5fa8f6a1-45cf-41f5-82b0-7c0d2f94d70e)

![image](https://github.com/user-attachments/assets/1f730005-4ec1-4c52-9c61-a13a8009fb4a)
![image](https://github.com/user-attachments/assets/4bc012f6-2652-45fe-9e10-533d1614d770)

**Comment by DanielnetoDotCom** [comment]
are you plugins also up to date?
did you make a git pull?
what page exactly is that where are you seeing this  can you share with me?

**Comment by eitanwa** [comment]
yes they are 
yes i did 

https://feisafe.com/video/86

**Comment by DanielnetoDotCom** [comment]
Check this update, this update should remove some errors

but I still see some errors that does not belong to AVideo. but lets see if that resolves.

**Comment by t2hasnain** [comment]
where i host plz explain me i am new plz

**Comment by eitanwa** [comment]
Thanks, it's back to work great
Thanks Daniel
you are a champion
