### ISSUE TITLE
When scheduling a Live stream is there a way to make the Live Meetings use that scheduled spot?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9711]
So when you create a schedule for a live I see it gives you a unique stream key to it. Will the live meetings know to use that or will it just start another stream?

**Comment by JoshWho** [comment]
I found how to do it. Just grab the stream url key and when going live paste that into the box. Can you confirm if that should do it?

**Comment by JoshWho** [comment]
![2ce7e84c-0758-4bcf-8e9e-1170b05d523c](https://github.com/user-attachments/assets/ad8c22a2-d610-41d1-aa3a-f21e958a2624)
![f2f73944-ede0-430a-a228-4576b3b68d71](https://github.com/user-attachments/assets/8b1133fc-7838-4392-9ac3-ba2815d94afa)

**Comment by DanielnetoDotCom** [comment]
Yes, that may work
