### ISSUE TITLE
User group switch just keeps Turning back on. What or why is this happening

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9713]
![4636d2cf-55d9-4c8c-81e7-c5e824d34949](https://github.com/user-attachments/assets/cbfc16fd-84f3-4596-a23a-9e1e93c397d8)

I do not understand why it keeps switching back on

**Comment by JoshWho** [comment]
If his browser cache has that setting stored every time he clicks save is going to turn it back on again. There has  be a no cache header on pages like live dashboard.

**Comment by DanielnetoDotCom** [comment]
question, you did disabled the user group for livestream right?

**Comment by JoshWho** [comment]
> question, you did disabled the user group for livestream right?

I disabled the hide groups on live so the user can see it himself before he goes live now until it is certain not to switch back anymore. I think his browser cache was keeping the switch on and every time his clicked save it was truing it back on. Now he just did a test and seems to be good now .

**Comment by DanielnetoDotCom** [comment]
I do not think it has anything to do with the cache. maybe something else. 

when some live setting is saved you will see this in your log `LiveTransmition::save users_id=`

**Comment by JoshWho** [comment]
What I did this time was turn the switch off made it public then I clicked save live settings and then I changed his key and clicked save again and seemed to stop it from reverting back.

**Comment by JoshWho** [comment]
I think this is solved now.
