### ISSUE TITLE
Auto-redirect at the end of the livestream

### ISSUE THREAD

**Issue by eitanwa** [WWBN/AVideo#9723]
**Another amazing feature made by Daniel**
It's worth a try
New monetization options open up
and a fun and efficient web browsing experience for the user
and especially to the creator
Thanks Daniel for another great idea!!

![image](https://github.com/user-attachments/assets/78b5f665-25cc-41d7-a0b7-9a1d0ee59b3f)

**Comment by DanielnetoDotCom** [comment]
You are welcome, and thanks @JoshWho for sponsor it
