### ISSUE TITLE
Disk Space warning main server

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9726]
Not sure what or where but I think something is not transferring or deleting tmp files.

**Comment by JoshWho** [comment]
![a38b4ed7-90e5-49f9-a371-0b763c9de5c6](https://github.com/user-attachments/assets/6fea523c-7835-46b1-a257-39a64ba07f0f)

**Comment by DanielnetoDotCom** [comment]
I could clean up your server ...

30GB from mysql logs, set mysql to keep the logs only for 2 days

Not sure why some recorded files were not deleted from the videos folder when it finishes I could clean up 130GB deleting all recorder that was 2 day old

**Comment by JoshWho** [comment]
> I could clean up your server ...
> 
> 30GB from mysql logs, set mysql to keep the logs only for 2 days
> 
> Not sure why some recorded files were not deleted from the videos folder when it finishes I could clean up 130GB deleting all recorder that was 2 day old

Thank you. Yeah it is weird.
