### ISSUE TITLE
New Premium user is not able to live stream. 

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9730]
Account email lykanonyt@gmail.com

He has purchased a premium package and when he tries to broadcast 

![image](https://github.com/user-attachments/assets/71e502c7-0027-4db7-a25c-a3d199b1fe31)
 Could not access specified channel or streamkey

I am trying it for him and got the same error. I even reset his stream key and that didn't fix it.

**Comment by JoshWho** [comment]
Stream keys now mixed Daves stream with the Christmas Channel

**Comment by DanielnetoDotCom** [comment]
what key are you refering to?

you probably save something on his page

**Comment by DanielnetoDotCom** [comment]
question, what plugin are you using to sell premium access?

**Comment by JoshWho** [comment]
The Subscription plugin

**Comment by JoshWho** [comment]
I reset Daves Key and the christmas channels key then restarted nginx

**Comment by DanielnetoDotCom** [comment]
Ok, found it I will send you updates soon, also the VideoPlaylistScheduler update to handle the continuos playback

**Comment by DanielnetoDotCom** [comment]
the VideoPlaylistScheduler may need to stay for tomorrow, I cannot update it now.

**Comment by DanielnetoDotCom** [comment]
It should be OK now. 

there are some missing updates that will be made this week, but everything should work as expected now
