### ISSUE TITLE
How to disable the mp4 option on encoder?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9741]
Is there a global config to disable the mp4 option on the uploader?

![f775340d-92ab-4dfd-93a3-862de510ff04](https://github.com/user-attachments/assets/1afb0514-9bb4-4eea-8723-07fd07761282)

**Comment by DanielnetoDotCom** [comment]
![image](https://github.com/user-attachments/assets/111c5047-9059-450b-99e5-814d5d3dfa66)

**Comment by JoshWho** [comment]
Got it  thank you.

**Comment by JoshWho** [comment]
I have that option checked but the upload encoders still show it

![4537f1db-f96c-4b09-ac98-b473d0938dae](https://github.com/user-attachments/assets/372c63a9-d602-4d81-9c1d-bfc6a64c6962)

**Comment by DanielnetoDotCom** [comment]
Sorry the correct option is this one

![image](https://github.com/user-attachments/assets/f08ef85f-6670-4e0f-b65e-0c4e37ca69d2)

**Comment by JoshWho** [comment]
Thank you
