### ISSUE TITLE
Public encoder says everything exceeds the php upload limit

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9742]
Just tried to upload a video using Pub encoder 1 and 720mb file exceeds the php upload limit. 
![2dbdb17e-e148-4a8c-af2d-36c2b6a5407f](https://github.com/user-attachments/assets/b688979a-a96c-4a38-b9d3-6a9652e10be8)

**Comment by JoshWho** [comment]
Looks like encoder 2 also exceeds the upload limit for a 720mb file.

**Comment by DanielnetoDotCom** [comment]
I see, I will update it in 30 min

**Comment by JoshWho** [comment]
Also says dlp is not installed on both of them

Traceback (most recent call last):, File "/usr/local/bin/yt-dlp", line 5, in , from yt_dlp import main, ModuleNotFoundError: No module named 'yt_dlp'

**Comment by JoshWho** [comment]
> can you please try now?

Working good now.
