### ISSUE TITLE
FFMPEG monitor for all servers that can clearly show what is processing

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo#9748]
Would be neet to have a GUI monitor for all FFMpeg services running that can show everything happening in the back end. 

Today currently I assume what is processing without even knowing what it is until it gets done. Would like to see in real time why the server is maxed at CPU and if it is something useless would like to be able to terminate it. 

A monitor for all FFmpeg conversions including mp3, with controls to stop it if need to.

**Comment by JoshWho** [comment]
With my netdata monitor this is all I see

![image](https://github.com/user-attachments/assets/cb02ea28-4582-4cde-bd98-583a54c7cf7a)


CPU is maxed

Top shows this

![image](https://github.com/user-attachments/assets/0a9d6a3a-d691-40bc-944f-c8d463f3b61a)

but I still have no clue what it is processing.

**Comment by DanielnetoDotCom** [comment]
Later I will add an update to display a simple ffmpeg process panel, also an option to kill them

**Comment by JoshWho** [comment]
This will be awesome. Where would it be located to view?

**Comment by DanielnetoDotCom** [comment]
Admin panel-> FFMPEG Monitor

**Comment by JoshWho** [comment]
This is beautiful Thank you @DanielnetoDotCom
