### ISSUE TITLE
Clickable timestamps in comments 

### ISSUE THREAD

**Issue by fakeologist** [WWBN/AVideo#9750]
YouTube has clickable timestamps in comments that allow you to jump to this time in the video.
Great for descriptions and chapters.
Here's an example - check the newest comments.
https://youtu.be/ey3YfcVnJvQ?si=cPpRG9SGUrjmVtuM

I posted this enhancement before but can't find it anymore.

**Comment by DanielnetoDotCom** [comment]
Sorry but I did not see anything on this sample, can you please share a screen record how it works?

**Comment by fakeologist** [comment]
https://github.com/user-attachments/assets/4404d564-6f0b-449d-86ad-0d3fe68dcc5d

**Comment by DanielnetoDotCom** [comment]
How do you add those comments?

**Comment by fakeologist** [comment]
just type in the timestamp and it gets converted to a hyperlink.

**Comment by DanielnetoDotCom** [comment]
timestamp right before the comment?

for example:

`26:44 this is a comment`

is that correct?

**Comment by fakeologist** [comment]
Yes anytime stamp anywhere in the comment gets linkified

**Comment by DanielnetoDotCom** [comment]
`26:44` this is enough to be a timestamp?

or need to be something like `07:26:44`

**Comment by DanielnetoDotCom** [comment]
This update may do what you requested.

**Comment by fakeologist** [comment]
Wow awesome and quick !

Can this feature be added to the video description field so chapters can easily be accessed?

**Comment by DanielnetoDotCom** [comment]
Yes I can do it in the future, but for now you can use this

https://github.com/WWBN/AVideo/wiki/Bookmark-Plugin

**Comment by fakeologist** [comment]
> Yes I can do it in the future, but for now you can use this
> 
> https://github.com/WWBN/AVideo/wiki/Bookmark-Plugin

I think this is a great feature never used it. This meets my needs thanks happy new year 🎊
