### ISSUE TITLE
Download MP4: Converts the video to MP4 and downloads it . how remove these two buttons?

### ISSUE THREAD

**Issue by tchingo** [WWBN/AVideo#9751]
**Describe the question**
Hello,
 how do I remove these two buttons mp3 and mp4 button ?
Because I don't want to convert the video to mp4, the other buttons are enough. Because all videos are in hls format.

**Screenshots**
![Immagine 2024-12-28 094019](https://github.com/user-attachments/assets/bafed8a8-69ad-4d20-9b5f-27831f5868cb)

**Comment by DanielnetoDotCom** [comment]
https://github.com/WWBN/AVideo/wiki/Enable-Video-Download

**Comment by tchingo** [comment]
It seems that you did not understand me, I know this post very well
And I do not know how to explain the problem to you. Please look at the image carefully
I do not want the second mp4 button to appear
![Immagine 2024-12-28 094019](https://github.com/user-attachments/assets/20abefee-b8ae-4b0e-8323-a4a8ce819611)

**Comment by tchingo** [comment]
Please understand me
I want to control each button separately
Can I remove that button indicated in red in the picture?

**Comment by DanielnetoDotCom** [comment]
Regarding the mp4 conversion check this

https://github.com/WWBN/AVideo/wiki/Automatically-Convert-Videos-to-MP4-and-MP3

if there is no MP4 the button will not appear.
